### ISSUE TITLE
Nested <material-tab> controls not working

### ISSUE THREAD

**Issue by nzmedet** [angular/material#100]
When having 2 tabs, parent tab works not as expected, even both tabs have different scope objects

**Comment by ajmajma** [comment]
Nesting tabs  - I don't have access to the innter tabs selected scope object. What was the resolve for this? I don't see anything in outline docs. Thanks!

**Comment by e-oz** [comment]
Nested tabs don't work and link to "online docs" is too broad.

**Comment by ThomasBurleson** [comment]
@robertmesserle - comments ?

**Comment by e-oz** [comment]
I found an answer: https://github.com/angular/material/issues/3703#issuecomment-137818694

**Comment by e-oz** [comment]
And for future readers: try out md-menu-bar - much more sane DOM behavior and much more great UX than md-tabs.
