### ISSUE TITLE
select: form remains valid in a required md-select when empty option is selected

### ISSUE THREAD

**Issue by dephiros** [angular/material#10005]
**Actual Behavior**:
 -  `What is the issue? *`
    - mdSelect with "required" set in a form; use <md-option></md-option> as empty option to clear select
    - select a non-empty option, form become valid
    - select empty option, form remains valid
 -  `What is the expected behavior?`
    - form should become invalid

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/dephiros/pen/ObMqBY?editors=1000
 -  `Details:` 

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *` latest
 -  `OS: *` macOS
 -  `Stack Traces:`

**Comment by topherfangio** [comment]
I don't think I am understanding your use-case. If the field is required, you shouldn't have any empty option right?

**Comment by dephiros** [comment]
The requirement that I have designing the form is all select should have the an empty option to clear the select after user selecting a valid value. We just use this as the standard select across everywhere in the application regardless if the field is required or not

**Comment by topherfangio** [comment]
I guess if you're attempting to use these together, it does seem like the `md-empty-option` should indeed reset the validity of the model. However, I'll leave this to @ThomasBurleson's judgement as to whether or not this should be considered a bug.

**Comment by Splaktar** [comment]
This [updated CodePen](https://codepen.io/Splaktar/pen/NWKpXyY?editors=1010) demonstrates how this is still an issue in `1.1.20` in addition to providing a side-by-side comparison to a regular `select` with AngularJS. This certainly seems like a bug that needs to be fixed.
