### ISSUE TITLE
Feat: Add `md-danger` to themes

### ISSUE THREAD

**Issue by epelc** [angular/material#1000]
Right now themes only have a primary, accent, and warning color. However the warning color is usually red which I think strikes more a feeling of danger. There is no real warning color only normal/primary and `md-warn` which acts like danger.

I think it would be nice if we added an `md-danger` and kept the `md-warn` so that we can convey both dangerous things and non fatal warnings. This would be similar to bootstraps use of warn and danger colors.

I couldn't find anything in the spec against this and I think it would help because right now you would use something like `md-theme="yellow"` then add `md-primary` which feels a bit hacky.

**Comment by rschmukler** [comment]
@ajoslin this sounds good to me, what are your thoughts?

**Comment by rschmukler** [comment]
@epelc sorry on the delay on this one - the team hans't had time to discuss it yet. Punting to 0.9 for now.

**Comment by epelc** [comment]
@rschmukler No problem. Thanks for the heads up though!

**Comment by rahatarmanahmed** [comment]
If we have `md-warn` and `md-danger`, it'd be nice to also have the option of an `md-success` as well. I have a few uses for both success and danger colors (positive and negative numbers).

**Comment by getuliojr** [comment]
+1

**Comment by dcolley** [comment]
+1 also md-info ala bootstrap and poss. a custom color

**Comment by rschmukler** [comment]
After discussing this with the team, we think that `md-danger` should mostly be covered by hues of `md-warn` (eg. `md-warn md-hue-3`). We realize that this deviates from bootstrap, but material design tends to recommend only a few colors in an app. With the addition of `$mdColor`, this will also be less necessary.
