### ISSUE TITLE
Tabs disappear when using input or select elements (Chrome on Android, Chrome desktop small width windows)

### ISSUE THREAD

**Issue by josecbraga** [angular/material#10004]
**Actual Behavior**:
Tabs disappear when using a input or select element contained inside a tab. Issue occurs on Chrome Browser for Android and Chrome for desktop. On Firefox mobile animations are shaky and select does not work very well. Behavior on Firefox desktop is exactly what is expected.

**CodePen** (or steps to reproduce the issue): *
 -  https://data-management-josebraga.c9users.io/team
 -  https://data-management-josebraga.c9users.io/person

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome Browser on Android, Chrome on desktop
 -  `Browser Version: *`  54.0.2840.85 (Android), 54.0.2840.87 m (64-bit) (desktop)
 -  `OS: *` Android 7.0, Windows 7 Pro
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
Links are not working. If you are still experiencing this issue on master, please refile this issue with a codepen.
