### ISSUE TITLE
Why is the discrete slider at minimum value displayed differently?

### ISSUE THREAD

**Issue by cadilhac** [angular/material#10012]
I have an horizontal slider defined with a step, min and max.
When I release the knob at the minimal value, the pin label becomes grey and the circle becomes black.
Why?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
