### ISSUE TITLE
nextTick error with Chips and md-autocomplete

### ISSUE THREAD

**Issue by Darkbladecr** [angular/material#10011]
**Actual Behavior**:
When deleting md-chips that contains the md-autocomplete directive there is a warning that appears in the logs:

> TypeError: Cannot read property 'nextTick' of undefined

![screen shot 2016-11-13 at 02 39 09](https://cloud.githubusercontent.com/assets/4283896/20243329/d7c0b12a-a94a-11e6-872f-eeb286e1d788.png)

**CodePen** (or steps to reproduce the issue): 
This behavior is seen on the [demo page](https://material.angularjs.org/latest/demo/chips), under Custom Inputs. Simply add a chip to the input and try to remove it.

**Angular Versions**: 
 -  `Angular Version:1.5.8`
 -  `Angular Material Version:1.1.1`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: v54`
 -  `OS: MacOs`

**Comment by DevVersion** [comment]
This is already fixed in `master`

**Comment by stephengardner** [comment]
Please release 1.1.2 to fix this issue 😭
