### ISSUE TITLE
datepicker: md-max-date causes panel to scroll to the next month

### ISSUE THREAD

**Issue by FlorianBurgevin** [angular/material#10013]
**Actual Behavior**:
 -  `What is the issue? *` When I use md-max-date with md-datepicker, if the value selected is on the first line of the current month (1st, 2nd,..), opening the datepicker cause a scroll to the next month.

Example with md-max-date
![with-maxdatepng](https://cloud.githubusercontent.com/assets/6703118/20268063/dbbeb932-aa7d-11e6-8554-033041adf13b.PNG)

 -  `What is the expected behavior?` Datepicker scroll to the date

Example without md-max-date
![without-maxdate](https://cloud.githubusercontent.com/assets/6703118/20268064/dbc3acd0-aa7d-11e6-9dd1-93a702bc23ed.PNG)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` IE11, Chrome Android
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

my code: 
```html
<md-datepicker id="start" name="start"
                       ng-model="values.startDate" md-placeholder="Start"
                       md-open-on-focus
                       md-max-date="today">
</md-datepicker>
```

```javascript
$scope.today = new Date();
```

**Comment by jesusmtzarvizu** [comment]
Could you please share the value of **values.startDate**  ??

**Comment by FlorianBurgevin** [comment]
values.startDate = Tue Nov 01 2016 00:00:00 GMT+0100 (Paris, Madrid)

In mode code I init it by moment(new Date).startOf('day').toDate();

**Comment by Splaktar** [comment]
Please verify that this is still an issue in 1.1.7 and provide a CodePen demo of the problem so that we can debug.

**Comment by Splaktar** [comment]
No demo supplied. This does not appear to still be an issue.
