### ISSUE TITLE
Google Geo Chart does not render inside Angular Material mdTabs

### ISSUE THREAD

**Issue by Joystan** [angular/material#10019]
up vote
0
down vote
favorite
I am using [Google Geo chart](https://developers.google.com/chart/interactive/docs/gallery/geochart) inside Angular Material tabs.

The chart renders fine for the first time when you load the page, but when you change pages and come back to this page it gives a container error and the charts don't load.

Unfortunately can't replicate this error on and editor to explain the bug.

Is anyone aware any fix for this?

**Comment by Splaktar** [comment]
I would suggest using [md-nav-bar](https://material.angularjs.org/latest/demo/navBar) instead. Closing as there is no demo.
