### ISSUE TITLE
md-item-text function has no impact on display value in md-autocomplete

### ISSUE THREAD

**Issue by ed4becky** [angular/material#10028]
**Actual Behavior**:
 -  `What is the issue? *`  return value from function in md-item-text in md-autocomplete is not displayed
 -  `What is the expected behavior?` returned string should be displayed

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/ed4becky/pen/pNExyP
 -  `Details:` should replace all item labels with 'Bob'

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` N/A
 -  `OS: *` N/A
 -  `Stack Traces:` N/A

**Comment by alex-nac** [comment]
Same thing happened to me...

**Comment by Splaktar** [comment]
Is [this](https://codepen.io/Splaktar/pen/baeMPp?editors=1011) what you are looking for?

`md-item-text` only modifies the display of the selected item. In your example, if you select a state, it will be displayed as 'Bob'. `md-item-text` does not change the display of the items in the dropdown panel. You can do that in the `md-item-template` like my [CodePen shows](https://codepen.io/Splaktar/pen/baeMPp?editors=1011).
