### ISSUE TITLE
Pagination with md-grid-list?

### ISSUE THREAD

**Issue by simonaco** [angular/material#10021]
Is there any grid component in angular material that supports pagination out there?

The only grid directive available on the documentation page is md-grid-list (https://material.angularjs.org/latest/api/directive/mdGridList) but I see no pagination options.

**Comment by Splaktar** [comment]
There are no plans at this time to add a pagination feature to the grid-list. 

The mat-table in Angular Material includes pagination and is quite flexible for extending. That may be an option for you, but there is no information here to describe your use case so I can't be sure.

@simonaco 👋  It was great to meet you at AngularMix 😄

**Comment by sw-carlin** [comment]
https://material.angular.io/components/table/overview does seem to satisfy my requirements and hopefully everyone else's. Thanks for pointing that out Splaktar.

**Comment by naxisinc** [comment]
Hi. I need to put three db element (images) per row but I don't know if mat-table allows me that. The idea is do something like a gallery. Thank in advance

**Comment by Splaktar** [comment]
@naxisinc Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
