### ISSUE TITLE
Do not want auto focus in md-menu

### ISSUE THREAD

**Issue by deejay220989** [angular/material#10038]
**Actual Behavior**:
 -  `What is the issue?`
I have an md-menu with a list of items where each item has a md-button. Every time the md-menu is opened, the first md-button is focused, I do not want this behavior as it is not suitable in my use case.

 -  `What is the expected behavior?`
I'm hoping that there is a way to disable the auto focus in md-menu

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/deejay220989/pen/aBppKg
 -  `Details:` Just have a md-menu with md-buttons in it, the first md-button will be focused.

**Angular Versions**: *
 -  `Angular Version:` 1.6.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type:` Chrome
 -  `Browser Version:` 54.0.2840.99 m
 -  `OS:` Win 8
 -  `Stack Traces:`

**Comment by manish2535** [comment]
Where would you want the focus to go then?

**Comment by deejay220989** [comment]
I do not want it to focus anywhere when the menu is opened. Right now, when the menu is opened, the first button will have its background grey which indicates that it is focused. It only seems to happen when using md-button and not bootstrap button..

**Comment by deejay220989** [comment]
Here's my codepen: http://codepen.io/deejay220989/pen/aBppKg

Also, I tried setting md-autofocus at the "Add all items" button, but when my mouse pointer goes into the items container, the first "Add"  button will be focused. I do not want this behaviour.

**Comment by BigLiao** [comment]
I meet this question too. When I open a `dialog`,  the `input` will be focused. I do not want that, how to disable this behavior?

**Comment by owen2** [comment]
I ended up putting `md-autofocus` on a `<h2>` in the dialog to effectively not auto-focus any fields.

**Comment by Splaktar** [comment]
There is not enough information here to describe a compelling use case (that provides a quality UX) for why you would want to open a menu and unfocus the page completely. It seems like that behavior would introduce clear a11y issues. No plan to change this at this time.

Offtopic:
@BigLiao and @owen2 please see the [mdDialog docs](https://material.angularjs.org/latest/api/service/$mdDialog) for how to manage focus behavior. Specifically:
```
focusOnOpen - {boolean=}: An option to override focus behavior on open. Defaults to true.
```
And the important note, **Only disable if focusing some other way, as focus management is required for dialogs to be accessible.**

**Comment by TimKitGit** [comment]
[matMenuTriggerRestoreFocus]="false"

**Comment by Splaktar** [comment]
@TimKitGit This repo is for AngularJS Material. Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues).
