### ISSUE TITLE
menu: open only once with a nested mdDialog

### ISSUE THREAD

**Issue by FlorentinBurgeat** [angular/material#10037]
I reproduced the demo from mdMenu but with a custom dialog :
 -  When adding attribute scope:$scope to the $mdDialog.show it disables the ng-click action for the menu button once the dialog is shown.
 - In brief I can open the menu multiple times as long as I don't click on the md-menu-item in the list opening the dialog, but if I do, I can't reopen the menu, and not even the ng-click action is fired.

`
      function menuController($scope, $mdDialog, StoredProcCallService, ColumnBuilder) {
     
     var originatorEv;

      this.openMenu = function($mdOpenMenu, ev) {
        originatorEv = ev;
        $mdOpenMenu(ev);
      };

      this.openDialog = function(title, template, request, lineId) {
        $mdDialog.show(
          {
            templateUrl: template,
            locals:{
              title: title,
              request:request,
              lineId:lineId,
              column:$scope.column
            },
            scope:$scope,
            controller: ['$scope','$mdDialog','ColumnBuilder','title','request','lineId','column', DialogController],
            parent: angular.element(document.body),
            targetEvent: originatorEv,
            clickOutsideToClose:true,
            fullscreen: true
          }
        );

        originatorEv = null;
      };
  }
`

**Angular Versions**: *
 -  `Angular Version:`1.5
 -  `Angular Material Version:`1.0.9 but doesn't work either on 1.1.1

**Additional Information**:
 -  `Browser Type: Chrome`

**Comment by manish2535** [comment]
Please provide a Codepen example.

**Comment by Splaktar** [comment]
Closing as no reproduction demo was provided.
