### ISSUE TITLE
Datepicker cover whole site in white in hirez

### ISSUE THREAD

**Issue by CapitanPlanet** [angular/material#10032]
**Actual Behavior**:
 -  I have problem with datepicker. In old version (before relese) it was ok, but i switch to v 1.1.1, menaged to fix all problems but this one. I have datepicker in flexbok with flex 25, and in resolution under about 1000px it is working fine, but above it, when i click on calendar icon whole site became white (i see calendar and nothing else). Turnet out md-scroll-mask is covering screen - it is wierd, because in styles this element background color is transparent. Also in flex 50 is working fine.
Edit: I removed md-scroll-mask, and body is white and have no content...
Edit: I find out the resolution do not matter... it is working fine if opened datepicker is located near right or bottom edge of browser... its wierd. My friend open this site on his computer, and is the same.

**CodePen** (or steps to reproduce the issue): *
 -  i tying to replicate problem on http://codepen.io/ , but with no luck.

**Angular Versions**: *
 -  `Angular Version:`1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome, Firefox
 -  `Browser Version: *` newest

**Comment by aminal** [comment]
Experiencing a similar issue. There seems like there might be an issue with the scroll mask. It also seems to only apply to version 1.1.1, version 1.1.0 is fine.

**Comment by reesemartin** [comment]
I have confirmed that this is only an issue if the datepicker is adjusted to compensate for screen height.  Essentially datepickers at bottom of page are fine while ones at top that dont get adjusted create the white screen.

I have found that if you manually add the class "md-datepicker-pos-adjusted" to the md-datepicker-calendar-pane element the issue goes away for that instance of the datepicker.

**Comment by CapitanPlanet** [comment]
It was a silly error. I worked on not mine project. And there was a problem with Bower - every file was in bower_components folder but for some reason, angular-material.min.css was connected to the solution (in another folder) and this file was in use. So I changed the version in packages.json; files in bower_component was new, but an old file was in use. 

Sorry for the disturbance.

**Comment by Splaktar** [comment]
Closing as this was reported to be fixed in 1.1.3.
