### ISSUE TITLE
[Solved] .md-icon-button ripple effect error

### ISSUE THREAD

**Issue by GeekOSK** [angular/material#10033]
The Angular Material issue which is pretty disturbing. When I hold-click the icon and ripple sticks on the element. After that when release the hold-click, the icon's background becomes absolute colored with the same color as that of the ripple!

![error](https://cloud.githubusercontent.com/assets/13559340/20390229/e198534a-acf3-11e6-942b-644b897d6d5c.gif)

[`Here's the codepen for that`](http://codepen.io/GeekOSK/pen/wooovv)

I have Angular Material 1.1.0.

**Comment by clshortfuse** [comment]
IIRC, this is a WebKit issue based on a workaround we use for a rounded corner overflow issue.

**Comment by GeekOSK** [comment]
Well maybe. So do you know how to solve it. Because I have not been able to solve until now

**Comment by GeekOSK** [comment]
## ERROR FIXED!!!
![errorfix](https://cloud.githubusercontent.com/assets/13559340/20431399/cbbce370-adbf-11e6-8eca-b84d00906bd1.gif)

I just changed to tag from `<md-button>` to `<a>` and added the **needful CSS** and voila!
**This is the needful CSS:**
`.md-icon-button:not(.md-button){
    position: relative;
    overflow: visible;
    padding:8px;
}
.md-icon-button:not(.md-button) .md-ripple-container{
    overflow: visible;
}`
[Here's the codepen for the fixed one](http://codepen.io/GeekOSK/pen/wooovv)

**Comment by GeekOSK** [comment]
# @clshortfuse Thanks to Participate!!
