### ISSUE TITLE
Error appears on delete chip

### ISSUE THREAD

**Issue by AlexAffter** [angular/material#10047]
**Actual Behavior**:
 -  When you using md-chips with autocomplete and delete some chips it cause error:
    angular.js:13550 TypeError: Cannot read property 'nextTick' of undefined 
    because of that I can't use md-on-remove callback. This error comes with 1.1.1 version.

**CodePen** (or steps to reproduce the issue): 
 -  https://material.angularjs.org/latest/demo/  
 - Try to delete chip in 'Contact Chips' section or add, then delete vegitable in 'Custom Inputs' demo  section.

**Angular Versions**: 
 -  Angular Version: v1.5.8
 -  Angular Material Version: 1.1.1

Sorry for broken english.

**Comment by recursionbane** [comment]
I see this too, with the same versions.

**Comment by DevVersion** [comment]
This has been fixed with https://github.com/angular/material/commit/a3b3e7b037fb02acae5c1d979e8373d7e8c93dfd

**Comment by stefan-leye** [comment]
So when will this fix be properly released? There is the "g3_v0_x" release but I can't install it via npm. With this bug md-chips are basically broken. 
On your main page you promise to build patch releases every week but the last one is from beginning of September.
