### ISSUE TITLE
card: content pushed off of card in Chrome

### ISSUE THREAD

**Issue by bigboii** [angular/material#10043]
**Actual Behavior**:
 -  `What is the issue? *` The contents of md-card gets pushed out or cards overlap in chrome.  This does not happen in internet explorer or other browsers.

![cardissue](https://cloud.githubusercontent.com/assets/13086286/20645458/f792906c-b42c-11e6-895c-bd65e2a5ca74.JPG)

 -  `What is the expected behavior?` md-card should overlap + content shouldn't be pushed out just like the codepen demo below

**CodePen** (or steps to reproduce the issue): *
https://codepen.io/yqkim91/pen/MbpEPJ

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 54.0.2840.99 m
 -  `OS: *` windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
I fixed up some issues with the image paths in your demo. But after [doing that](https://codepen.io/Splaktar/pen/MBazmY?editors=1010), I can't see any overflow issues. Your comments above seem to indicate that the demo actually works as expected. But then you only provide a screenshot of the problem, but no demo for us to debug or reproduce the issue.

I've seen this kind of thing before and it is usually related to custom content or layout issues, so we would need to see your custom content and/or layout to be able to look into this.
