### ISSUE TITLE
Not able to pass clickOutsideToClose in a variable

### ISSUE THREAD

**Issue by vineethvnair0** [angular/material#10048]
**Actual Behavior**: clickOutsideToClose should accept a variable which can be changed programatically
 -  `What is the issue? *` not working its taking the old value not the updated one
 -  `What is the expected behavior?` should take the updated value and close the tag

**CodePen** (or steps to reproduce the issue): * only jsfiddle demo i have 
 -  `CodePen Demo which shows your issue:`http://jsfiddle.net/e5j1p6mo/
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
A described in the [docs](https://material.angularjs.org/1.1.21/api/service/$mdDialog#mddialog-show-optionsorpreset), `clickOutsideToClose` optionally takes a `boolean` and not an expression that might change over time.

> clickOutsideToClose - `{boolean=}`: Whether the user can click outside the dialog to close it. Default false.

We don't support dynamically changing the `clickOutsideToClose` setting while a dialog is open.
