### ISSUE TITLE
generate the colors of a theme dynamically

### ISSUE THREAD

**Issue by max-SS** [angular/material#10044]
**Actual Behavior**:
 -  `What is the issue? *`
Hello good morning, I need to generate the colors of a theme dynamically, but these are not being updated, they are only updated the first time, and then it no longer works.
I was looking at the isuss #5502
But the solution they propose to does not work for me.

 -  `What is the expected behavior?`
I need to choose a primary or accent color to generate the theme using those colors

**CodePen** (or steps to reproduce the issue): *
https://codepen.io/maxSS/pen/ObWXmW

**Angular Versions**: *
 -  `Angular Version: 1.5.5
 -  `Angular Material Version: 1.1.1

**Additional Information**:
 -  `Browser Type: All
 -  `Browser Version: Latest
 -  `OS: Windows 7 and Windows 10 Aniversary Update

**Comment by Splaktar** [comment]
Please take a look at the following docs:
https://material.angularjs.org/latest/api/service/$mdTheming
https://material.angularjs.org/latest/Theming/04_multiple_themes
https://material.angularjs.org/latest/Theming/05_under_the_hood

Here's a working [demo](https://codepen.io/Splaktar/pen/QBbYqV).
