### ISSUE TITLE
Using ng-blur to trigger $mdDIalog provoke infinite loop 

### ISSUE THREAD

**Issue by dchirutac** [angular/material#10055]
**Actual Behavior**:
 -  `What is the issue: ` I use **ng-blur** event to show **$mdDialog.sow()**. What happens is after **$mdDialog.cancel()**  the cursor is autofocused into blurred input. This behavior provoke infinite loop of blur event.
 -  `What is the expected behavior?` Should lose focus of blurred input

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows the issue:`  [here](http://codepen.io/dchirutac/pen/QGvYvP)
 -  `Details: After first invoking of blur event it enter in infinite loop to showing $mdDialog`

**Angular Versions**: *
 -  `Angular Version:`1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type:` Chrome
 -  `Browser Version: ` 54

@ThomasBurleson, @robertmesserle can you help me ?

**Comment by dchirutac** [comment]
I've resolve this issue by using ngModelOptions directive that allows you to modify the behaviour of ngModel directives within your application
```
<input type="number" ng-model="value1"   ng-blur="change($event)" ng-model-options="{updateOn: 'blur' }" />
```

**Comment by mpacary** [comment]
Thanks for the idea @dchirutac ; this greatly helped me to solve a very similar problem.

I was using `<select ng-model="myModel" ng-change="onChange()">...</select>` in a dialog.

On a `$mdDialog.cancel()` call, `myModel` was automatically set to `null` and the `ng-change` handler called, which I did not want at all.

Adding `ng-model-options="{updateOn: 'click'}"` fixed the issue 👍
