### ISSUE TITLE
md-no-float does not seem to work

### ISSUE THREAD

**Issue by dbrgn** [angular/material#10054]
**Actual Behavior**:
 -  `What is the issue? *` Adding [md-no-float attribute to a md-input-container](https://material.angularjs.org/latest/api/directive/mdInputContainer#api-section) doesn't seem to have an effect.
 -  `What is the expected behavior?`The placeholder text doesn't "float up" when clicking into the input field

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/anon/pen/pNPLdP
 -  `Details:` Both fields behave the same way

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chromium
 -  `Browser Version: *` 54.0.2840.100 (64-bit)
 -  `OS: *` Arch Linux

**Comment by DevVersion** [comment]
Per documentation `placeholder` attributes on the inputs will be not converted to floating labels.

> When present, placeholder attributes on the input will not be converted to floating labels.

You are still creating the "placeholder" by using the `<label>` element.

**Comment by dbrgn** [comment]
Ah, thanks! I knew I was missing something :)
