### ISSUE TITLE
dialog: avoid window scrolling to start when dialog is opened from the end of page

### ISSUE THREAD

**Issue by sinhpn92** [angular/material#10053]
I have a page with width is over 100% (2000px). When I click to show dialog from  button in the end of page (by horizontal page), window scroll to the start of page (by horizontal page) and display the dialog. 

This is my code: [codepen](http://codepen.io/anon/pen/BQRxGY)

I use angularjs 1.5 and newest angular material js.

How can i show dialog from button in the end of page (by horizontal page)  and window not scroll to the start of page?

**Comment by Splaktar** [comment]
This should be possible now using [`$mdPanel](https://material.angularjs.org/1.1.21/demo/panel) with [`MdPanelPosition`](https://material.angularjs.org/1.1.21/api/type/MdPanelPosition).
