### ISSUE TITLE
Selecting a date with md-datepicker doesn't set model and sets date error on input

### ISSUE THREAD

**Issue by MaelstromCdn** [angular/material#10050]
**Actual Behavior**:
 -  `What is the issue? *`
Setting md-datepicker by selecting a date attaches a "date" error to the input and doesn't set model. An example error object is { 'date': true }
 -  `What is the expected behavior?`
Model is set and no error is shown

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
Unable to reproduce in CodePen
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
1.5.8
 -  `Angular Material Version:`
1.1.1

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
54.0.2840.98
 -  `OS: *`
OSX 10.11.6
 -  `Stack Traces:`

**HTML**
```
<form name="dependentForm" ng-submit="dependent.onSubmit()">
    Date: {{ dependent.data.birthDate }}<br>
    Error: {{ dependentForm.birthdate.$error }}<br>
    <md-datepicker name="birthdate" ng-model="dependent.data.birthDate" md-placeholder="Enter date" ng-required="true"></md-datepicker>
    <button type="submit">Save</button>
</form>
```

**Controller**
```
.controller('ChildAddController', [function () {
        var ctrl = this;

        // Properties
        ctrl.data = { birthDate: null };

        // Events
        ctrl.onSubmit = function () {
            ...
        };
    }]);
```

**Comment by topherfangio** [comment]
If you cannot reproduce it inside a Codepen, then there is likely an issue within your own code.

If you can provide a Codepen, we will reopen.

**Comment by MaelstromCdn** [comment]
Have since moved on to a different datepicker control so I'll leave it closed.
