### ISSUE TITLE
mdMenuBar: Submenu closing

### ISSUE THREAD

**Issue by bojan88** [angular/material#10066]
Menu is not closing when sub menu is opened and clicked on toolbar.

Steps to reproduce:
1. go to [menu bar demo](https://material.angularjs.org/latest/demo/menuBar)
2. click on "File"
3. hover "New". Sub menu will open
4. move your cursor up and click on toolbar (e. g. on white space next to "Untitled document")
Sub menu will close, but main menu will stay opened.

I think all of the browsers are affected with this bug.

**Comment by bradrich** [comment]
I can confirm. This is an issue. Working on this now.

**Comment by bradrich** [comment]
Looks like this is actually fixed and awaiting the 1.1.2 release: #9602. Please await that release for a resolution.
