### ISSUE TITLE
md-tabs and md-nav-bar should have shared code

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#10065]
**Actual Behavior**:
 -  `What is the issue? *` md-tabs and md-nav-bar don't share any code makes bug fixes and adding features more difficult than it needs to be

**Angular Versions**: *
 -  `Angular Material Version:` 1.1.1

----

**Comment by Splaktar** [comment]
This would be nice, but given the short time span remaining to support these components and the possible risk of this refactoring, I don't feel that the impact of this outweighs the risk and effort.
