### ISSUE TITLE
Datepicker breaks after upgrading to angular 1.6.0-rc.1 or 1.6.0-rc.2

### ISSUE THREAD

**Issue by aresn** [angular/material#10070]
**Actual Behavior**:
 -  `What is the issue? *`
Angular 1.6.0-rc.1 and 1.6.0-rc.2 breaks datepicker. Datepicker opens up with an empty placeholder where the dates should be. After scrolling up for a while, dates starts appearing.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/madani/pen/ENbPMp
click on any of the Datepickers on the page to see the issue for yourself.

**Angular Versions**: *
 -  `Angular Version: 1.6.0-rc.1 and 1.6.0-rc.2`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: * Firefox, Chrome`
 -  `Browser Version: * Firefox: 50.0.1,  Chrome: 54.0.2840.98`
 -  `OS: * Mac OS X 10.12.1`

**Comment by rudzikdawid** [comment]
same issue on Linux

Browser Type: * Firefox, Chrome
Browser Version: * Firefox: 50.0, Chrome: 54.0.2840.100
OS: * Fedora 24

**Comment by BNigmatov** [comment]
same issue with Angular v.1.6.0 (stable) on Chrome 55.0.2883.75 m

**Comment by jr-cobweb** [comment]
Having the same issue. I've started looking into it, but unfortunately my angular skills are somewhat limited.  From what I can tell, the problem occurs on line #121352. I've included the code block below for context.

It looks like offset and oldOffset are always equal when using angular 1.6. Will continue looking into this, but thought I'd drop it here in case it is useful for anyone else.

```
scope.$watch(function() { return monthBodyCtrl.offset; }, function(offset, oldOffset) {
    if (offset !== oldOffset) {
        monthBodyCtrl.generateContent();
    }
});
```

**Comment by rupalchawla** [comment]
Angularjs has released 1.6.1-build.5199+sha.7f8bc58, did anyone test datepicker on this version?

**Comment by DevVersion** [comment]
@rupalchawla We should have fixes those issues on `master` with SHA https://github.com/angular/material/commit/342ee53363e06a46958541eac980e5ff3d62029d, but we haven't released the changes yet.

Going to track this issue with #10111

**Comment by angularnewbee** [comment]
I can confirm issue persists in angularjs v1.6.1 with angular-material v1.1.1

**Comment by rupalchawla** [comment]
thanks @rudzikdawid this works!

**Comment by eseliger** [comment]
This is just a workaround and not a fix though.

**Comment by GollaVenkatesh** [comment]
angular.module('myApp', []).config(function($compileProvider) {
    $compileProvider.preAssignBindingsEnabled(true);
  }).config(['$qProvider', function ($qProvider) {
    $qProvider.errorOnUnhandledRejections(false);
  }]);
