### ISSUE TITLE
open select option, html page will show [object Object] text

### ISSUE THREAD

**Issue by lxy305859844** [angular/material#10077]
![screen shot 2016-12-01 at 4 14 37 pm](https://cloud.githubusercontent.com/assets/17747113/20812915/6cb64386-b7e1-11e6-8882-7afc52baf555.png)
**Actual Behavior**:
 -  `What is the issue? *`
now we try to change format from boostrap to angular material, but we face issue when we replace the select field. every time when I open option list, the homepage will print [object Object]
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:
                                                <md-input-container class="md-block" flex-gt-sm style="width :100%">
                                                    <label>Account Manager</label>
                                                    <md-select 
                                                    required
                                                    ng-model="filled_form.salesperson"
                                                    ng-if="!quoteBookId"
                                                    >
                                                      <md-option ng-repeat="salesperson in customer_form.salespersons"
                                                      ng-value="salesperson">[[salesperson.username]]</md-option>
                                                    </md-select>
                                                </md-input-container>`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version: 1.3.20`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: *chrome and firefox`
 -  `Browser Version: *`
 -  `OS: * OSX`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by learnseleniumtesting** [comment]
what did you do to solve this? I am in same boat and unable to solve it. Please share if possible.

**Comment by lxy305859844** [comment]
@learnseleniumtesting Hi, I think it was because my angular version. 
I used angular material 1.0.7 at that time, and I upgrade my angular to 1.3.20 to solve this issue.

**Comment by learnseleniumtesting** [comment]
And you were also using bootstrap along with if I am correct.
