### ISSUE TITLE
mdProgressLinear: Buffer mode with md-primary is not visually consistent with md-warn/md-accent

### ISSUE THREAD

**Issue by jonahbron** [angular/material#10078]
**Actual Behavior**:
 -  md-primary buffer mode progress bars show only a solid position for `buffer-value` and `value`.  The `value` is not distinguished from the `buffer-value` position by color, nor is the dotted section visible.

**Expected Behavior**:
 -  The `value` should be represented by the primary color, the `buffer-value` should be represented by a lighter bar, and the dotted section should be visible, as with the `md-warn` style.

**CodePen** (or steps to reproduce the issue):
 -  http://codepen.io/anon/pen/MbrVrR
 -  This shows two md-progress-linears, both identical in every way except the class 

**Angular Versions**:
 -  Angular 1.5.5
 -  Angular Material 1.1.1

**Additional Information**:
 -  Browser Type: Chrome
 -  Browser Version: 53.0.2785.143
 -  OS: Ubuntu 16.10

This is a duplicate of an existing ticket, but that ticket was closed in April without resolution.  Figured I'd open a new one to be on the safe side. https://github.com/angular/material/issues/3690

**Comment by joaocraveiro** [comment]
+1

**Comment by joaocraveiro** [comment]
Just submitted a [fix ](https://github.com/angular/material/pull/10563) for this.
