### ISSUE TITLE
skipHide Bug

### ISSUE THREAD

**Issue by scriptsure** [angular/material#10076]
**Actual Behavior**:
 -  `What is the issue? *`

**I HAVE UPGRADED FROM 1.1.1 TO THE MASTER BRANCH AND NOW ALL THE SKIPHIDE: TRUE NO LONGER WORK. IN OTHER WORDS THE CHILD DIALOG OPENS BUT IN THE PROCESS ALSO CLOSES THE PARENT DIALOG.**

CODEPEN: http://codepen.io/scriptsure/pen/ObzxvR

 -  `What is the expected behavior?`
**THE PARENT DIALOG SHOULD REMAIN OPEN**

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/scriptsure/pen/ObzxvR
 -  `Details:`
**CLICK CUSTOM DIALOG BUTTON.
THE PARENT DIALOG WILL APPEAR.
CLICK THE CUSTOM DIALOG BUTTON AGAIN
THE PARENT WILL CLOSE AND THE CHILD WILL OPEN**

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` MASTER

**Additional Information**:
 -  `Browser Type: *` CHROME
 -  `Browser Version: *`
 -  `OS: *` WINDOWS 8
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
We have changed `skipHide` to `multiple`.

> See Pull Request #9053 

Codepen: http://codepen.io/DevVersion/pen/YpYrgy

**Comment by ekevoo** [comment]
A deprecation warning wold be very helpful, guys.

**Comment by mgol** [comment]
Such a rename shouldn't happen in a patch update as it's clearly a breaking change.

**Comment by chm0815** [comment]
this rename cost me 3 hours :(

**Comment by daryldcL** [comment]
Yeah, me too. :(
