### ISSUE TITLE
autofocus: condition statements don't seem to be working properly

### ISSUE THREAD

**Issue by alee046** [angular/material#10072]
I am trying to use the md-autofocus directive on an md-dialog modal. The behavior I am trying to get is for the autofocus to switch its target when the md-dialog tab changes. There is only one example on the docs to go off for conditional statements for md-autofocus. So I am a bit unsure of how to accomplish what I am trying to do. 
` <md-dialog-content>
            <md-tabs md-dynamic-height ng-show="dialogCtrl.isReady" md-selected="dialogCtrl.selectedTabIndex">
                <md-tab label="Email">
                    <md-content class="md-padding content" ng-class="{ 'min-width': !dialogCtrl.useFullScreen }">
                        <div layout="row" layout-align="center center">
                   
                        </div>

                        <form layout="row" layout-align="center center">
                            <div layout="column">
                                <md-input-container>
                                    <label>Postal Code</label>
                                    <input md-autofocus="{{dialogCtrl.selectedTabIndex === 0}}" ng-model="dialogCtrl.data.postalCode" type="text">
                                </md-input-container>

                                <md-input-container>
                                    <label>Email Address</label>
                                    <input  ng-model="dialogCtrl.data.emailAddress" type="email">
                                </md-input-container>

                                <md-button ng-click="dialogCtrl.submitEmail()" type="submit" class="md-accent md-raised">Check Availability</md-button>

                                <p class="fineprint">By continuing, you agree to our  <a href="http://www.freedompop.com/terms.htm" target="_blank" class="black-anchor-tag">terms of use</a> and <a href="http://www.freedompop.com/privacy.htm" target="_blank" class="black-anchor-tag">privacy policy</a>.</p>
                            </div>
                        </form>

                    </md-content>
                </md-tab>

                <md-tab label="Street Address">
                    <md-content class="md-padding content" ng-class="{ 'min-width': !dialogCtrl.useFullScreen }">                            
                        <div layout="row" layout-align="center center">
                            <h3 class="md-title no-margins">See if you qualify for this special offer!</h3>
                        </div>

                        <form layout="row" layout-align="center center">
                            <div layout="column">
                                <p class="instructions">Please include your street address to qualify.</p>
                                <md-input-container>
                                    <label>Street Address</label>
                                    <input md-autofocus="{{dialogCtrl.selectedTabIndex === 1}}"  ng-model="dialogCtrl.data.streetAddress" type="text">
                                </md-input-container>

                                <md-button ng-click="dialogCtrl.submitStreet()" type="submit" class="md-accent md-raised">Check Availability</md-button>
                            </div>
                        </form>
                    </md-content>
                </md-tab>
</md-content>
`

The condition statements should evaluate to true, ({{dialogCtrl.selectedTabIndex === 1 ||0}}), but it doesn't seem to be effecting the autofocus.

**Comment by tiaoshi** [comment]
Could you open a codepen or anything else to demonstrate?

**Comment by alee046** [comment]
Sorry, there's alot of dependencies that goes along with the logic for this modal. Just assume that the conditions for the md-auto-focus should be evaluated to true. Autofocus only works on the first tab (when dialogCtrl.selectedTabIndex == 0). When navigating to the next tab, autofocus is not working (but dialogCtrl.selectedTabIndex ===1)

**Comment by Splaktar** [comment]
As mentioned in the [docs](https://material.angularjs.org/latest/api/directive/mdAutofocus)

> [md-autofocus] provides an optional way to identify the focused element when a `$mdDialog`, `$mdBottomSheet`, `$mdMenu` or `$mdSidenav` opens or upon page load for input-like elements.

It does not have any effect when the selected tab changes. You would need to write custom code for that.
