### ISSUE TITLE
mdTabs: add support for varied height in tab content; with transitions

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#1008]
### Animation for growing content

1. Slide the new content into frame, maintaining the original height
2. After the new content is horizontally focused, animate the height of the container to reveal the content

### Animation for shrinking content

1. Shrink the height to the height of the new content
2. Slide the new content into view

**Comment by robertmesserle** [comment]
This is related to #1246 ad #1235.

**Comment by mnill** [comment]
Resolved?

**Comment by robertmesserle** [comment]
This feature is implemented in master. There is still a bug logged against
this for when content resizes dynamically.

**Comment by rscafi** [comment]
Is there a way to set md-tabs height to be the height of the biggest md-tab?
If I remove `md-dynamic-height`, the md-caps will then have a fixed size that matches none of the tabs.

**Comment by robertmesserle** [comment]
Not at the moment; however, I believe there is an issue open for this.
