### ISSUE TITLE
Handling of 'touchmove' input event was delayed for 111 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by ruant** [angular/material#10081]
**Actual Behavior**:
 -  `What is the issue? *`
Handling of 'touchmove' input event was delayed for 111 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.
Webapp (which is a customer check-in form) turns unresponsive, keep tapping it will eventually respond.

Not 100% sure if this is an Angular/Material issue, it does point to moment.min.js, but I don't understand why moment is messing around with touchstart..

 -  `What is the expected behavior?`
That the web app responds correctly everytime.
I haven't seen this issue on while running the webapp on a desktop, but that's probably due to this being a touch issue...

**Angular Versions**: *
 -  `Angular Version:` 1.5.9
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` WebView/Chrome
 -  `Browser Version: *`Chrome/54.0.2840.85
 -  `OS: *` Android 5.0.1
 -  `Stack Traces:`

**Comment by Remco75** [comment]
is this while doing remote debug? That really slows things down. The message is exactly what it states: your device is too busy, so stuff takes longer. This not an issue with the event (it can happen on every event) but more probably an issue in your application: 
See if that page uses a lot of bindings, actions that block the page, loads of css etc.

You could try to replicate on your desktop this by 'throtling' your CPU / bandwidth  in the chrome dev tools

**Comment by ruant** [comment]
Thanks for the input @Remco75 

It is during remote debugging yes, but it looks like I'm still hitting something since the web app stops responding for a while even without me remote debugging the session.

The app isn't really big (7kb), but there must be some bad code in there somewhere that the execution hangs on.

I'll need to dig some more to get to the bottom of this it looks like.
Or get the customer to buy some better tablets 😆

I'll keep posting my findings, but I'll close the issue.
