### ISSUE TITLE
open md-select using button

### ISSUE THREAD

**Issue by kadosh1000** [angular/material#10088]
Hi I wonder if there is a way to open md-select using a button.

Basiclly to just replace how the md-select is shown when it's closed to be a button

**Comment by nnmrts** [comment]
try this:

there is a function called `$mdSelect.show();`, in select.js, maybe that will help you somehow

**Comment by Splaktar** [comment]
You probably want to look at https://material.angularjs.org/latest/demo/menu for this behavior.
