### ISSUE TITLE
Documentation site is not keyboard-friendly

### ISSUE THREAD

**Issue by dplassgit** [angular/material#10095]
**Actual Behavior**:
 -  `What is the issue? *`On material.angularjs.org, I cannot use the keyboard to scroll; only the mouse.
 -  `What is the expected behavior?`I can use the keyboard to scroll up or down

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`latest

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *`55.0.2883.75
 -  `OS: *`Ubuntu
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DanieleTorino** [comment]
Seems to be [quite an old issue](https://github.com/angular/material/issues/2961).
Kind of ironic that the documentation site of AngularJs Material is not user friendly at all...

**Comment by Splaktar** [comment]
This is an important issue to get resolved. I've reopened https://github.com/angular/material/issues/2961 which this issue duplicates.
