### ISSUE TITLE
select: dropdown arrows don't render properly in Chrome

### ISSUE THREAD

**Issue by sam-g-roberts** [angular/material#10093]
**Actual Behavior**:
 In chrome the select dropdown arrows are being replaced by this icon
<img width="323" alt="screen shot 2016-12-06 at 11 59 52" src="https://cloud.githubusercontent.com/assets/12782773/20925080/958029fc-bbac-11e6-84c0-4613ae117937.png">

**Expected Behavior**:
 The icon should be an arrow pointing down

**Angular Versions**:
 -  Angular Version: 1.5.8
 -  Angular Material Version: 1.0.9

**Additional Information**:
 -  Chrome
 -  54.0.2840.98
 -  OSX Yosemite

**Comment by sam-g-roberts** [comment]
Example from main demo site

<img width="830" alt="screen shot 2016-12-06 at 12 09 33" src="https://cloud.githubusercontent.com/assets/12782773/20925135/e6d3f496-bbac-11e6-87a9-4da18efba7ad.png">

**Comment by Splaktar** [comment]
Can't reproduce on the docs site in either
- https://material.angularjs.org/1.1.21/demo/select
- https://material.angularjs.org/1.1.0/demo/select

On macOS Catalina and Chrome 80.
