### ISSUE TITLE
refactor(css): include Roboto font as part of themes

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#1009]
Right now, we are including the Roboto font from Google through a `<link>` tag.  It occurred to me that we could just as easily include it via `@import` in our CSS.

This also begged the question: where should this live?  Should this be tied into themes?

**Comment by marcysutton** [comment]
It isn't included, you have to include the `<link>` tag from Google fonts. We can easily swap it out for an `@import` in the Typography stylesheet.

```css
@import url(http://fonts.googleapis.com/css?family=Roboto:500,400italic,700,400);
```

**Comment by marcysutton** [comment]
Given Roboto is *the* font for Material Design, I don't think this should be configurable. Adding it to `typography.scss` and removing the link from our index HTML.

**Comment by marcysutton** [comment]
Moving to 0.10.0 to hold discussion about best approach for including font. Options include a non-blocking JS utility to load font if not already included.

**Comment by robertbaker** [comment]
Whatever the choice, 'RobotoDraft' is now obsolete and can be removed from the font-families.
