### ISSUE TITLE
docs: some examples rewritten by pagespeed

### ISSUE THREAD

**Issue by btford** [angular/material#1010]
See https://material.angularjs.org/#/api/material.components.tabs/directive/mdTabs

This is an issue with the nginx configs. I'll take a look when I have a moment.

**Comment by ThomasBurleson** [comment]
@btford - Did you get the nginx fixes resolved for this issue ?

**Comment by btford** [comment]
Fix'd

**Comment by bonatoc** [comment]
Praise [The Ford](https://www.wikiwand.com/en/Brave_New_World) :-)
