### ISSUE TITLE
input: indentation different from the Material Design spec

### ISSUE THREAD

**Issue by rvarbanov** [angular/material#10105]
**Actual Behavior**:
 -  `What is the issue? *` Input indentation different from the official Material Design page.
 -  `What is the expected behavior?`The Angular Material input have padding-left: 2px, but the Material Design page doesn't. If we are following the Material Design there the input label, input text, and input underline should be equally aligned to the left.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/latest/demo/input
 -  `Details:` Compare both pages https://material.angularjs.org/latest/demo/input and https://material.io/archive/guidelines/components/text-fields.html#text-fields-layout to see the difference

**Angular Versions**: *
 -  `Angular Version:` 1.5.9
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` Version 55.0.2883.75 (64-bit)
 -  `OS: *` macOS Sierra, 10.12.1
 -  `Stack Traces:` n/a

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by rvarbanov** [comment]
@clshortfuse thoughts?

**Comment by EladBezalel** [comment]
@rvarbanov as this is true, this is a breaking change means it would only get in in `1.2.x` in case we do it,
and if we do - we need to make sure every other input (sidenav, autocomplete. etc..) is properly aligned as spec (which may vary over time)

This would be nice to have but not that important right now imo :)
