### ISSUE TITLE
select: displayed value behaves like multi-select when it should not.

### ISSUE THREAD

**Issue by hemvignesh** [angular/material#10106]
**Actual Behavior**: md-select's displayed value behaves like multi-select when it should not.
 -  `What is the issue? *` When an object that holds the model of an `md-select` is updated to its clone by doing an `angular.copy(<obj-with-ng-model>)`, the displayed value on the `md-select` is a repetition of itself.
 -  `What is the expected behavior?` The displayed value of the md-select should not be repeated.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/hsomi/pen/YpvKOO
 -  `Details:` Please click the `SEE BUG` button (before clicking on the md-select) and note that the displayed value updates to `Option 0, Option 0` while one would expect the value to stay at `Option 0`. Depending on how fast you click you could get the value to repeat itself 3 to 4 times. We would expect the value to not repeat like when you click the `SEE EXPECTED` button.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55.0.2883.75 (64-bit)
 -  `OS: *` Ubuntu Linux, OS X El Capitan
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by oemmes** [comment]
Maybe the same as #9442?

**Comment by hemvignesh** [comment]
Yup. track by index workaround works for this case. Thank you.

**Comment by Splaktar** [comment]
Fixed in `1.1.2` via https://github.com/angular/material/commit/d553919130cf85314c10a19b27a9b5c9665cdac9.
