### ISSUE TITLE
Md tab with 6 tabs

### ISSUE THREAD

**Issue by lio1972** [angular/material#10104]
I have an angular material single page application with several tabs. I am trying not to load all data on page load. I would like to load only the data that the tab needs. How can I do that. I created directives for every  tab.

**Comment by DAquilina** [comment]
You can store the active tab in a scope variable and key those directives with ng-if. This is simple (see below) but does mess with the animations a bit if you're using md-dynamic-height.

```
  <md-tabs md-selected="currentTab">
    <md-tab label="tab 1">
      <my-directive ng-if="currentTab === 0"></my-directive>
    </md-tab>
    ...
  </md-tabs>
```

Alternatively, initialise your directives with an ng-change switching function of some kind.

**Comment by Splaktar** [comment]
This is documented [here](https://material.angularjs.org/latest/api/directive/mdTabs#attributes) via the `md-enable-disconnect` attribute. However, it is highly recommended to use the [md-nar-bar](https://material.angularjs.org/latest/demo/navBar) instead.
