### ISSUE TITLE
md-navbar  accessibility - Can't focus on first tab when content is closed

### ISSUE THREAD

**Issue by frkfir** [angular/material#10119]
**Actual Behavior**:
 -  `What is the issue? * When you try to focus with the keyboard (tab key)  on the first navbar item with closed content, the focus is only on the whole navbar and not on the first item 
 -  `What is the expected behavior? If you have clickable tabs with closed content, you should still can focus on them. The focused item should be visibly selected.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue: http://codepen.io/rhmubus/pen/mOjNpP
 -  `Details: I  changed in the JS file " currentNavItem = 'page0' " - this page doesn't really exist. 

**Angular Versions**: *
 -  `Angular Version:`1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: * Google Chrome
 -  `Browser Version: * Version 55.0.2883.75 m (64-bit)
 -  `OS: * Windows 7
 -  `Stack Traces: n/a

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ErinCoughlan** [comment]
There needs to be an active item in order for the nav-bar to be accessible. It's fine to use ng-if to hide/show items, but one of the items still needs to be active.

Here's the accessibility guidelines the nav-bar complies to:

"Focus management: When the widget receives focus, the item in the widget that is currently active (e.g., currently displayed) should receive the focus." - [WAI-ARIA Site Navigator](https://www.w3.org/TR/wai-aria-practices/#Site_Navigator_General)

"Keyboard interaction: Tab - only the active tab is in the tab order. The user reaches the tabbed panel component by pressing the tab key until the active tab title receives focus." - [WAI-ARIA Tab Panel](https://www.w3.org/TR/wai-aria-practices/#tabpanel)
