### ISSUE TITLE
please publish a release for angularjs 1.6.0

### ISSUE THREAD

**Issue by mikeandersun** [angular/material#10111]

**Comment by DavidHooper** [comment]
Builds are broken this morning.

**Comment by rudzikdawid** [comment]
similar issues: https://github.com/angular/material/issues/10070 https://github.com/angular/material/issues/10090 (datepicker)

**Comment by ivanwagner** [comment]
Is this issue going to be checked?

**Comment by david-gang** [comment]
hi,

Will setting $compileProvider.preAssignBindingsEnabled(true) fix the issue with 1.6?
Will upgrading to angular 1.6.1 solve the issue without setting the previous option?

Thanks,
David

**Comment by kibertoad** [comment]
bower-material peerDependency versions should also be bumped.

**Comment by sdebionne** [comment]
@david-gang 
> Will setting $compileProvider.preAssignBindingsEnabled(true) fix the issue with 1.6?

Yes. The picker does not show the current date but something like 3 months in the future. That issue may be unrelated though.

> Will upgrading to angular 1.6.1 solve the issue without setting the previous option?

No. But it works with `$compileProvider.preAssignBindingsEnabled(true)`.

Aside of the DatePicker component, 1.6 also breaks the Tab component: the content of the tab is not displayed until the tab header is clicked. `$compileProvider.preAssignBindingsEnabled(true)` fix the issue to.

For the records, from Angular doc:

> preAssignBindingsEnabled([enabled]);
> If disabled (false), the compiler calls the constructor first before assigning bindings.
> **The default value is true in Angular 1.5.x but will switch to false in Angular 1.6.x.**

Emphasis is mine.

**Comment by ThomasBurleson** [comment]
@topherfangio, @crisbeto - we need to update ngM1 to work with 1.6.x; preferrably without setting the `$compileProvider.preAssignBindingsEnabled(true)`.

**Comment by sbmadhav** [comment]
Is there a timeline to get this issue fixed ?

**Comment by skortchmark9** [comment]
angular 1.6.1 is out now.

**Comment by fnc314** [comment]
Does 1.6.1 angular work with material 1.1.3? @skortchmark9.  Thanks for the info.

**Comment by graingert** [comment]
@ThomasBurleson it looks like you only need to bump the peerDep because Angular 1.6 works with angular material

**Comment by Elecash** [comment]
Also this is important because Snyk detects a vulnerability that is fixed in Angular 1.6.1.

**Comment by mgol** [comment]
@Elecash it doesn't matter whether you use 1.6.0, 1.6.1 or 1.6.2 - they all have the same API as AngularJS introduces breaking changes only in minor updates (i.e. between 1.4 & 1.5, 1.5 & 1.6, 1.6 & 1.7 etc.). Once Material gets officially compatible with 1.6.0 it will be compatible with any 1.6.x.

Maybe it'd be less confusing if the issue title mentioned `1.6`, not `1.6.0`.

**Comment by Elecash** [comment]
@mgol I agree, it should be 1.6.X but I think that the vulnerability was fixed in 1.6.1, that's why I mentioned that version.

**Comment by fnc314** [comment]
@mgol you are correct. I should've generalized my question. I just happened to grab 1.6.2 on a new project and ran with that version.

Thanks tho.

Anyone familiar with release cycles have an ETA on a dependency update? Many thanks for everything

**Comment by sbmadhav** [comment]
I am still getting npm WARN angular-material@1.1.3 requires a peer of angular@>=1.3 <1.6 but none was installed.

**Comment by topherfangio** [comment]
@sbmadhav It has been merged into master, but we have not pushed a new release. This will be available in 1.1.4.

**Comment by sbmadhav** [comment]
When is 1.1.4 scheduled for release?

**Comment by topherfangio** [comment]
@sbmadhav It was scheduled for a few days ago, but many of the developers are getting ready for ngConf right now and it has been pushed back. Our goal is to get it out ASAP, though.

**Comment by graingert** [comment]
@topherfangio 

> and it has been pushed back

till?

**Comment by graingert** [comment]
@topherfangio how was ng-conf? Did you have a good time?
