### ISSUE TITLE
$mdDialog.hide(dialogPromise, data) not resolving promise

### ISSUE THREAD

**Issue by garretwilson** [angular/material#10113]
In an Angular 1.5 component I'm showing a Material mdDialog, which itself has an embedded component:

```javascript
var dialog = $mdDialog.show({
  controller: function($scope, $log) {
    $scope.done=function() {
      $mdDialog.hide(dialog, "new foobar!");
    }
  },
  template: "<md-dialog aria-label='Add Foobar'><new-foobar-panel on-ok='done()'></new-foobar-panel></md-dialog>",
  clickOutsideToClose: true,
  fullscreen: true
}).then(function(answer) {
  $log.debug('You said the information was "' + answer + '".');
}, function() {
  $log.debug('You canceled the dialog.');
});
```

The [documentation](https://material.angularjs.org/latest/api/service/$mdDialog) says this should be possible:

```javascript
function closeAlert() {
  $mdDialog.hide( alert, "finished" );
  alert = undefined;
}
```
But try as I may, in the code above calling `$mdDialog.hide(dialog, "new foobar!")` will never resolve the promise. As it turns out `$mdDialog.hide("new foobar!")` will resolve the promise, but this isn't very modular and depends on the global service just somehow "remembering" which dialog you happen to have open. I have a reference to the `dialog` promise, and the example code seems to indicate I can resolve the promise by invoking `$mdDialog.hide(dialogPromise, data)`. Am I doing something wrong? Is the example wrong? Or did I misinterpret something? Thanks

**Comment by gabovanlugo** [comment]
Did you found a solution to this? I'm facing a the same problem.

**Comment by ThomasBurleson** [comment]
@garretwilson - `$mdDialog` does not support dialog-stacking (e.g. multiple instances of dialogs). So therefore the AngularJS Material architecture does not provide a reference to the dialog instance; rather `$mdDialog` internally caches that reference and hides the dialog upon request.

**Comment by enri90** [comment]
+1
