### ISSUE TITLE
tooltip: attaches a scroll handler for each tooltip

### ISSUE THREAD

**Issue by NicolasThierion** [angular/material#10125]
On the latest version (1.1.1 & master), md-tooltip registers a scroll listener per tooltip. This cause some perfomrance issue especially when I create tooltips within a scrollable list.

The slowdown seems to be caused directly by the listener being attached, not by the $digest process.
I don't see why this listener is needed, appart from hiding the tooltip on scroll.

If so, I suggest registering the listener within `enterHandler`, and removing it within `leaveHandler`.

**Comment by NicolasThierion** [comment]
The issue doesn't seem to affect everyone (ie: Chrome on windows works perfectly fine). I use google chrome 54 (64bit) on Linux.

**Comment by Splaktar** [comment]
Unable to reproduce as there was no reproduction demo provided.
