### ISSUE TITLE
Since Angular 1.6.0, Datepicker is blank until scroll - PLNKR

### ISSUE THREAD

**Issue by steveharan** [angular/material#10122]
**Actual Behavior**:
Datepicker is blank:

https://puu.sh/sNbCk/616eae9a00.png

Until scrolled, then contents of datepicker appear

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 - 1.6.0
 -  1.1.1

DEMO:

https://plnkr.co/edit/phZR6W?p=preview

It's sure broke

**Comment by rudzikdawid** [comment]
stop creating duplicate issue, first just use search bar
https://github.com/angular/material/issues/10070
https://github.com/angular/material/issues/10090
https://github.com/angular/material/issues/10111

https://github.com/yunity/foodsaving-frontend/pull/194

**Comment by steveharan** [comment]
I do apologize

**Comment by graingert** [comment]
@steveharan please close this issue
