### ISSUE TITLE
since angular 1.6.0 > md-select: md-option does not get pre selected by ng-model

### ISSUE THREAD

**Issue by organismen** [angular/material#10129]
**Actual Behavior**:
 -  `What is the issue?` When i use angular 1.6.0 my option (test 1 in codepen) doesn't get pre selected by the md-select ng-model object. If I switch back to 1.5.9 it works as expected
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/organismen/pen/vyVmxX
 -  `Details:` Test 1 should be pre selected.

**Angular Versions**: *
 -  `Angular Version:`1.6.0
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 54.0.2840.98 (64-bit)`
 -  `OS: Mac OS`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by lemonmuncher** [comment]
+1 Also experiencing this issue.

**Comment by watat83** [comment]
I'm currently using Angular 1.5.8 and I have the same issue here

**Comment by organismen** [comment]
Interesting @watat83, Do we have the same issue? I tested 1.5.8 in my codepen above and it seems to work, could you provide an example for you situation?

**Comment by ThomasBurleson** [comment]
Angular 1.6.x not yet supported.

**Comment by ThomasBurleson** [comment]
@topherfangio - see https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-directives-select

**Comment by topherfangio** [comment]
Just verified that this is fixed in our master branch and will available in the next release (which is coming out VERY soon).

http://codepen.io/topherfangio/pen/jyZGBK?editors=1010
