### ISSUE TITLE
$mdDialog animation duration

### ISSUE THREAD

**Issue by praveenk-telsiz** [angular/material#10123]
**Actual Behavior**:
I am using $mdDialog and the animations are pretty cool. I am trying to change the animation duration. Is there a way one can control this?

**Angular Versions**: *
 -  `Angular Version: v1.5.8
 -  `Angular Material Version: v1.1.1

**Comment by Splaktar** [comment]
`$$mdAnimate.translate3d()` allows this, but `$mdDialog.show()` doesn't expose an API to configure that option (`duration`).

**Comment by Splaktar** [comment]
Oh and you can now use [`$mdPanel`](https://material.angularjs.org/1.1.21/demo/panel) if you want to get more control over your dialogs. This includes changing the animation type and duration.
