### ISSUE TITLE
Setting today's date in datepicker

### ISSUE THREAD

**Issue by anandts88** [angular/material#10128]
**Actual Behavior**:
 -  `What is the issue? *`

I am designing an application which runs in the Pacific TimeZone, whereas the application can be accessed from any part of the world. For example: If today's date is Dec 13 2016 1:00PM(Pacific Time), then if I open the date picker in "Los Angeles" then Dec 13 2016 is highlighted as today's date which is good, but if I open the date picker in IST which is (Dec 14 2016 12:30AM) then the datepicker is considering Dec 14th as todays date.

 -  `What is the expected behavior?`

Expectation is today's date should be Dec 13 2016 irrespective of any time zone. 
Even if I open datepicker in Dec 14 2016 12:30 AM IST, the datepicker needs to highlight current Pacific Time which is Dec 13 2016 in this case.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by stevenxzhou** [comment]
+1
We encountered the exact same issue and it was very hard for debugging. We solve it by overrding mdDateLocaleProvider to convert time to UTC time at front instead of local time.

**Comment by anandts88** [comment]
@stevenxzhou It would be great if you provide a snippet.

**Comment by topherfangio** [comment]
The only other option I can think of here is to provide a `md-today="..."` option which would let you set the value of Today to something else. However, if your app needs to display in a timezone different than the user's, something like what @stevenxzhou mentioned is great.

You can override `$mdDateLocaleProvider` in your `.config()` like so:

```js
.config($mdDateLocaleProvider) {
  $mdDateLocaleProvider.formatDate = function(date, timezone) {
    // Provide a different date format...
  }
}
```

I'm not sure your exact needs, but it sounds like you might be able to just set the date to a different timezone and be done.

**Comment by Splaktar** [comment]
This looks like a very specific use case that is handled by the customizations provided above. As there has been no further feedback, I'm going to close this one.
