### ISSUE TITLE
md-chips with ng-message need animation just like md-input do?

### ISSUE THREAD

**Issue by redyyu** [angular/material#10131]
**Actual Behavior**:
 -  `What is the issue? *`
      md-chips able to work with `ng-messages` when `md-max-chips` error. But it's doesn't play animation, also doesn't have CSS. 
 -  `What is the expected behavior?`
     I think md-chip might use with other form fields (in md-input-container) often, so the ng-message should looks same with other form fields which created by md-input, both css and animation. the Theme setting must effect it as well, other wise I have to custom the font-size, color, and animation by custom css, could be break when Theme settings is changed.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
     Sorry I didn't have CodePen Demo, but you can get it on Official site / Demo / md-chips/
    https://material.angularjs.org/latest/demo/chips  
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`  v1.5.9
 -  `Angular Material Version:` v1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` v 54.0.2840.98(64-bit)
 -  `OS: *` MacOS 10.12.1 (16B2657)
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
If you would like to submit a PR to add this functionality, we would very much welcome it, however, this is not currently on our list of priorities. If we find many users giving this 👍 we will reconsider.
