### ISSUE TITLE
$mdDialog.prompt input required

### ISSUE THREAD

**Issue by simonered** [angular/material#10135]
**Actual Behavior**:
 -  `What is the issue? *` The dialog promise is resolved even if the input is blank
 -  `What is the expected behavior?` Cannot confirm the dialog if input is blank, or at least you should decide it in dialog creation, something like `$mdDialog.prompt().required(true|false)`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Open the demo prompt dialog at [Angular Material website](https://material.angularjs.org/latest/demo/dialog), remove the input initial value and click on "Okay!"
 -  `Details:` The dialog is closed, the promise confirmed and no value is printed (obviously)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`  55.0.2883.75
 -  `OS: *` Ubuntu 16.10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by kylekrzeski** [comment]
+1
