### ISSUE TITLE
dialog: should let me run code when the "cancel" button is pressed

### ISSUE THREAD

**Issue by dplassgit** [angular/material#10130]
**Actual Behavior**:
 -  `What is the issue? *` $mdDialog.confirm only lets me run code when the user clicks the "confirm" button on the dialog. I want to run code when the user clicks the "cancel" action button. (This is documented at https://material.angularjs.org/latest/api/service/$mdDialog)
 -  `What is the expected behavior?` N/A

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` N/A
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.1

**Comment by Roundaround** [comment]
Correct me if I'm wrong, but if I recall correctly, $mdDialog.show() returns a promise, where .then's resolve function (the first parameter) is when .hide() is called - like when the confirm button is clicked - and the reject function (the second parameter) is when .cancel() is called - like when the cancel button is clicked.

From the dialog demo:

    $scope.showConfirm = function(ev) {
      // Appending dialog to document.body to cover sidenav in docs app
      var confirm = $mdDialog.confirm()
          .title('Would you like to delete your debt?')
          .textContent('All of the banks have agreed to forgive you your debts.')
          .ariaLabel('Lucky day')
          .targetEvent(ev)
          .ok('Please do it!')
          .cancel('Sounds like a scam');

      $mdDialog.show(confirm).then(function() {
        $scope.status = 'You decided to get rid of your debt.';
      }, function() {
        $scope.status = 'You decided to keep your debt.';
      });
    };

**Comment by dplassgit** [comment]
It's possible, but the documentation says "You can call show and the promise returned will be resolved only if the user clicks the confirm action on the dialog."  It does not mention if the "reject" function will be called if the user hits cancel.  If so, this is a documentation issue (not a FR)
