### ISSUE TITLE
tabs: label expression not replaced when tab has a md-menu

### ISSUE THREAD

**Issue by iboffa** [angular/material#10139]
**Actual Behavior**:
 -  `What is the issue? *` When a md-tab has a md-menu, its label is not being replaced by angular expression value
 -  `What is the expected behavior?` md-tab-label should show angular expression value

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/bBQYyy
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` Version 55.0.2883.87 m (64-bit)
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

EDIT: in the codepen controller is not correct, but even correcting it, the problem doesn't get solved

**Comment by Splaktar** [comment]
This pattern of putting menus where tab labels should be is not part of Material Design and not supported by AngularJS Material.

I messed with [the CodePen](https://codepen.io/Splaktar/pen/oNjxZeb?editors=1010) a bit and got close to what you were looking for (outside of some styling changes needed to make the menu buttons take up the full tab label area). But we do not recommend this UI pattern.
