### ISSUE TITLE
toolbar: md-scroll-shrink not working in demo on docs site

### ISSUE THREAD

**Issue by samal84** [angular/material#10133]
**Actual Behavior**:
The toolbar shrink demo is not shrinking.

**CodePen** (or steps to reproduce the issue): *
https://material.angularjs.org/latest/demo/toolbar

**Angular Versions**: *
The current demo seems to be using 1.5.5. I tried changing it in codepen to use 1.5.9, and saw no difference.

**Additional Information**:
Tried in latest Chrome and Firefox on Windows 7.

**Comment by Splaktar** [comment]
There isn't much detail here, but this looks like a duplicate of https://github.com/angular/material/issues/10413.

**Comment by samal84** [comment]
Oh wow. Yeah I only vaguely remember making this issue. Good idea to close it. If it is not a duplicate, then it it at least very out of date.
