### ISSUE TITLE
Md- Picker allows to type 6 digits in the year.

### ISSUE THREAD

**Issue by nareshkumarsrm** [angular/material#10138]
**Actual Behavior**:
In year, the mdP picker allows to type 6 digits
For example, in year we can  able to type 201666. So this needs to be restricted to 4 digits. Can anyone help me out.

**Comment by Splaktar** [comment]
This seems related to https://github.com/angular/material/issues/9994 which has an open PR (https://github.com/angular/material/pull/11110).

Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
