### ISSUE TITLE
tabs: clicking on buttons, then switching away from and back into the tab makes them focus

### ISSUE THREAD

**Issue by marcospgp** [angular/material#10137]
**Actual Behavior**:
 -  `What is the issue? *`

 Clicking on buttons, then switching away from and back into the tab makes them have focus.

 -  `What is the expected behavior?`

 Buttons should not be focused on just because you clicked on the tab where they are.

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` Latest

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `OS: *` Windows 10

 This doesn't happen all the time, takes a few tries. It happens even in the angular material demo page, go ahead and give it a try.

**Comment by Splaktar** [comment]
Unclear what version "Latest" refers to.

Reproduction steps are unclear. Which demo and what are the exact steps to reproduce?
