### ISSUE TITLE
layout: flex="noshrink" does not grow on Safari

### ISSUE THREAD

**Issue by Burtan** [angular/material#10134]
flex="noshrink" does not grow on safari:
 -  `What is the issue? *` The middle div of my CodePen demo should grow (it does on firefox and chrome)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/Burtan/pen/ZBqVGe

**Angular Versions**: *
 -  `Angular Version:` 1.6.0
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Safari
 -  `Browser Version: *` Version 10.0.1 (12602.2.14.0.7)
 -  `OS: *` macSierra

**Comment by Splaktar** [comment]
It looks like this was a Safari Flexbox bug. It seems to be working in Safari 11.1 and may well work in 10.3 as well.
