### ISSUE TITLE
Show toolbar tools with md-tabs

### ISSUE THREAD

**Issue by apmeena** [angular/material#10141]
@gmoothart  I am using Angular Material Design in my project, everything is good but a want to show some toolbar buttons with `md-tabs` as you can see in this image I have shown a search icon and an add icon. I have tried using `CSS positions` but the icons got hidden any of my custom CSS is not working for it. What can I do? Thanks.

![image](https://cloud.githubusercontent.com/assets/6169344/21225411/bcf7aa36-c2f6-11e6-8834-f46550149aad.png)

**Comment by gmoothart** [comment]
Can you post a plunkr/codepen of what you've tried that isn't working?

**Comment by apmeena** [comment]
@gmoothart  This is my code

```
            <md-content ng-scrollbars class="md-whiteframe-2dp">
                    <md-tabs md-dynamic-height md-border-bottom>
                        <md-tab label="MY DIARY">
                            <md-content class="">
                                <md-table-container >
                                    <table md-table  ng-model="selected" md-progress="promise"  class="font-effect-content">
                                        <thead md-head>
                                        <tr md-row>
                                            <th md-column><span>Currency</span></th>
                                            <th md-column ><span>TT Buy</span></th>
                                            <th md-column ><span>TT Sell</span></th>
                                            <th md-column md-numeric>Bill Buy</th>
                                            <th md-column md-numeric>Bill Sell</th>
                                        </tr>
                                        </thead>
                                        <tbody md-body>
                                        <tr md-row ng-repeat="dessert in desserts">
                                            <td md-cell>{{dessert.name}}</td>
                                            <td md-cell>{{dessert.calories.value}}</td>
                                            <td md-cell>{{dessert.fat.value | number: 1}}</td>
                                            <td md-cell>{{dessert.carbs.value}}</td>
                                            <td md-cell>{{dessert.name}}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </md-table-container>
                            </md-content>
                        </md-tab>
                        <md-tab ng-click="showAdvanced($event)" style="float:right;position: absolute;right:0;">
                             <md-tab-label>
                                 <i class="material-icons">add</i>
                             </md-tab-label>  
                        </md-tab>
                    </md-tabs>
                </md-content>
```

![image](https://cloud.githubusercontent.com/assets/6169344/21285467/735b8c16-c45f-11e6-9eda-413ba9fdc82d.png)


Using this code I am at least able to show the icon properly. Now my problem is when I click on the plus icon it becomes active, which is it's default behavior but without making it active I want to open the dialog. Right now dialog is coming properly but the tab becomes active and its position should be in right corner it is not going in right side. Thanks.

**Comment by apmeena** [comment]
Finally, I achieved it, using some CSS and some trick in HTML, My CSS code is:

```
md-tab-item> .md-tab, .ng-scope, .ng-isolate-scope, .md-ink-ripple, .md-disabled{
      cursor: pointer;
      pointer-events:auto;
}
```

and the HTML code is:

```
<md-tab ng-click="openCustomDialog($event)" ng-disabled="true">
    <md-tab-label>
        <i class="material-icons" style="color:#222d32;">add</i>
    </md-tab-label>  
</md-tab>
```

 I am not sure it is a good way to achieve it or not but It's working properly for me.

**Comment by gmoothart** [comment]
md-tabs takes a single transcluded block and then does some processing on the md-tab items. If you want to add content there that is not an md-tab, you can just add it in and then position it correctly. No need to put it in an md-tab if it is not a tab.

**Comment by apmeena** [comment]
Thanks, @gmoothart. Earlier it was not taking the `position `because I was placing it inside `<md-tabs>` now I changed the code, the tools are not outside of `<md-tabs>`. I am fine with it.
