### ISSUE TITLE
mdVirtualRepeat: stops at virtual-repeat-sizer height of 0x1FFFFFF

### ISSUE THREAD

**Issue by CBenni** [angular/material#10153]
**Actual Behavior**:
 -  `What is the issue? *` When I create a huge md-virtual-repeat with a total length of over 2 million items, each being 20px high, in all browsers I tested, the length is truncated at a value close to 1.5-1.6 million items.
At that size, the md-virtual-repeat-sizer contains 112 elements, each ELEMENT_MAX_PIXELS high, the total computed height of the virtual-repeat-sizer is 3.35544e+07px (according to chrome devtools), which is approximately 33554431, in hex 0x1ffffff. Remaining elements are cut off and the model is never queried for them. The `md-top-index` value is truncated as well.
 -  `What is the expected behavior?` In theory, no such maximum size of the scroll bar should exist.
If this is a technical limitation, a scaling for the scrollbar could be considered, meaning each pixel on the scrollbar scrolls for a multiple of the scroll height, reducing the height by a constant factor

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/CBenni/pen/zoyZOK

 -  `Details:` This is exactly the virtual-repeat demo, just upscaled to 50 million items (from 50 thousand). In my trials on chrome stable, it truncated the list at 932066.5 items (half an item is cut off)

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome, Firefox
 -  `Browser Version: *` 55.0.2883.87 m, aurora 52.0a2
 -  `OS: *` Windows 10 Pro
 -  `Stack Traces:` -

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'will not support' category for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
