### ISSUE TITLE
datepicker: does not open when coded inside a uibModal

### ISSUE THREAD

**Issue by gmarshall56** [angular/material#10151]
I have coded a standard md-datepicker inside a uibModal template like this:

```html
<script type="text/ng-template" id="modalAddContent.html">
   <div layout-gt-xs="row">
       <div flex-gt-xs>
           <h4>Standard date-picker</h4>
           <md-datepicker ng-model="someDate" md-placeholder="Enter date">
          </md-datepicker>
       </div>
   </div>
   <div class="modal-header">
       <button type="button" class="close" ng-click="cancell()">
           <span class="glyphicon glyphicon-remove" ></span>
       </button>
       <h4 class="modal-title custom_align">Add Image</h4>
   </div>
</script>
````
The date-picker displays fine on the modal however when clicking on it it does not open and behind the modal I see a large blank area beginning about where the md-datepicker is coded in the modal.

When I place the same md-datepicker on the HTML page (non modal code) it works fine.

*  All of the Angular code is version 1.5.3.  
*  I am also using ui-bootstrap-tpls-0.14.3 for the uibModal and other ui components. 
*  Angular Material version is 1.1.0.
*  Testing so far in Chrome.

Is there some issue with using Angular Material with ui-bootstrap?

Thank you for your time.
Gary

----

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

---

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.x** (or greater) < 1.6.0

**Comment by Splaktar** [comment]
No demo provided.
