### ISSUE TITLE
theming: ruleMatchRegex variable not actually used

### ISSUE THREAD

**Issue by OpenSiteMobile** [angular/material#10154]
**Actual Behavior**:
 -  `What is the issue? *` The ruleMatchRegex variable (assigned a Regex) is not used.
 -  `What is the expected behavior?` Not sure. Probably just leftover code, but just wanted to make sure.

**CodePen** (or steps to reproduce the issue): * na
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: * Any
 -  `Angular Version:` Any
 -  `Angular Material Version:` v1.1.1

**Additional Information**:
 -  `Browser Type: *` Any
 -  `Browser Version: *` Any
 -  `OS: *` Any
 -  `Stack Traces:`

The ruleMatchRegex variable under the generateAllThemes function in theming.js (https://github.com/angular/material/blob/v1.1.1/src/core/services/theming/theming.js) doesn't do anything as far as I can tell. It gets used in the following line:
 
```
var match = rule.match(ruleMatchRegex);
```
...under the the "rules.foreach" annonymous function, but the "match" variable isn't used either. So it is probably just some leftover code, thus I thought I would note it for removal in you next updates.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
It looks like this was added in the [original commit](https://github.com/angular/material/commit/47f0d09e9ebd87891703fa2b7e81355ce3952a86#diff-2a98812fedf7173f142f890cb0c29b850), but even there it doesn't appear to be used.

**Comment by Splaktar** [comment]
This was fixed in 1.1.6 via https://github.com/angular/material/commit/f1e4fcb151a62a4930e983247ddccd5e877a386e#diff-2a98812fedf7173f142f890cb0c29b85.
