### ISSUE TITLE
mdDialog border-radius issue

### ISSUE THREAD

**Issue by guzza** [angular/material#1015]
While working with md-dialog I've noticed the border-radius goes crazy and sometimes some corners radius is not visible/working. I've narrowed down the issue to the content of md-dialog pushing back the corners and showing theirs. You can even see it in the demo page of mdDialog. The solution that I've found to work is to add some padding to md-dialog element.

https://material.angularjs.org/#/demo/material.components.dialog

![screen shot 2014-12-20 at 13 28 15](https://cloud.githubusercontent.com/assets/188076/5514805/50531b04-884c-11e4-8f86-337add5d27e5.png)

![screen shot 2014-12-20 at 13 28 26](https://cloud.githubusercontent.com/assets/188076/5514806/5611e804-884c-11e4-98c1-0e73e3f8dc2a.png)

**Comment by ajoslin** [comment]
I don't see a problem with this fix. I'll go ahead and implement it, and if something comes up we can always fix it! Thanks @EladBezalel.

**Comment by EladBezalel** [comment]
@ajoslin Sure :smile:

**Comment by Splaktar** [comment]
Looks like this fix broke dialogs in IE: #3480, #3005, #3187. Looks like `overflow: auto` fixes this issue and avoids breaking IE.
