### ISSUE TITLE
dialog: pass content value from parent controller

### ISSUE THREAD

**Issue by palmani** [angular/material#1016]
Hi, 

I'm using templateUrl for mdDialog.

Dynamically mdDialog conent have to change, Let me know how to acheive this.

Scenario: from other controller, while button click pass status message to mdDialog controller.

Thanks in Advance,
Palmani. K

**Comment by sasivarnan** [comment]
@theGlenn Thanks man. It worked. :+1: :)

**Comment by rfink** [comment]
Is there any plan to have locals available to the sidenav component as well?

**Comment by maddes** [comment]
This should be on the docs… and the [demo](https://material.angularjs.org/latest/demo/dialog)

**Comment by yskomur** [comment]
is this possible return data from mdDialog for parent controller.

**Comment by bhamde** [comment]
Can we send through methods in 'locals' like variables? what would the syntax be?

**Comment by yskomur** [comment]
$mdDialog.hide(returnData);

Heh simple

**Comment by Berg-it** [comment]
*to send data from $mdDialog controller to parent controller you can use the bellow code:*
```javascript
$mdDialog.show({
  template: tmpl,
  scope: $scope,
  preserveScope: true,
  controller: 'myCtrl'
});```

**Comment by kcampion** [comment]
+1 @Berg-it

**Comment by hamidyfine** [comment]
@Berg-it Hi ~ I want to pass value from `$mdDialog` to its parent.
I try your code but no luck! 
Something I have to tell you that I use `$mdDialog` in the service. this is my code:
```javascript
angular.module('app.service')

.factory('alertService', function($rootScope, $mdDialog, $mdMedia) {
    return {
        showAlertByTemplateUrl: function(code, ev) {
            $mdDialog.show({
                    templateUrl: code,
                    parent: angular.element(document.body),
                    clickOutsideToClose: false,
                    targetEvent: ev,
                    scope: $rootScope,
                    preserveScope: true,
                    controller: 'jobSuggestController',
                    bindToController: true
                })
                .then(function(answer) {
                    $rootScope.status = answer;
                    console.log($rootScope.status);
                }, function() {
                    $rootScope.status = 'You cancelled the dialog.';
                });
        }
    };
});
```
and this is function to close the `$mdDialog`:
```javascript
$scope.showCode = function(answer) {
        // $scope.status = alertService.returnVal(answer);
        $mdDialog.hide(answer);
    }
```
Why I can't use `$scope.status` in the view?

**Comment by cayrescript** [comment]
@theGlenn Thank youuuuu so much, you save me :)
