### ISSUE TITLE
Dropdown items is giving black background when opened in Edge

### ISSUE THREAD

**Issue by vpanugaling** [angular/material#10161]
**Actual Behavior**:
 -  `What is the issue? *` When the dropdown items is shown, it gives black background either in the whole document or the dropdown items itself as shown in this screen capture http://i.imgur.com/o8Eme83.gif
 -  `What is the expected behavior?` The black screen should not be shown.

**CodePen** (or steps to reproduce the issue): * 
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/BzRjBx
 -  `Details:` Issue occurs when the drop down is clicked multiple times. It doesn't show at first 2 - 3 clicks.

**Angular Versions**: *
 -  `Angular Version:` 1.4
 -  `Angular Material Version:` 1.0.9 and 1.1.0

**Additional Information**:
 -  `Browser Type: *` Microsoft Edge
 -  `Browser Version: *` 25.10586.0.0
 -  `OS: *` Windows 10
 -  `Stack Traces:` No stack traces

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
I don't believe this is an issue with our code, but a graphical bug with your machine/drivers and Microsoft Edge. Can you disable hardware acceleration in Edge and see if the problem persists?

**Comment by vpanugaling** [comment]
Thanks for the prompt action on this @clshortfuse 

You are right it's a graphical bug with my machine.

**Comment by clshortfuse** [comment]
@vpanugaling No problem. I hope you can solve your issue.
