### ISSUE TITLE
md-datepicker not showing

### ISSUE THREAD

**Issue by Andrew-Lahikainen** [angular/material#10168]
**Actual Behavior**:
 -  `What is the issue? *`
md-datepicker does not show any dates to select. It is completely blank.
 -  `What is the expected behavior?`
User should be able to select dates.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/Lahikainen/pen/woZxBK

**Angular Versions**: *
 -  `Angular Version:`
1.6.0, 1.5.8
 -  `Angular Material Version:`
1.1.1

**Additional Information**:
 -  `Browser Type: *`
All browsers
 -  `Browser Version: *`
Chrome 55, Firefox 51, Edge 38
 -  `OS: *`
Windows
 -  `Stack Traces:`
None

`Screenshots`:
![image](https://cloud.githubusercontent.com/assets/10571313/21437714/6078bfda-c8ea-11e6-9efd-7e68e0b5c4fb.png)

**Comment by victordelacruz** [comment]
It seems the problem presents itself when upgrading to Angular 1.6.

Try this in your app:

```
angular.module('myApp', [])
  .config(function($compileProvider) {
    $compileProvider.preAssignBindingsEnabled(true);
  });
```

It worked for me.

**Comment by Andrew-Lahikainen** [comment]
Yep that worked for me victor, thanks for the tip!

**Comment by pgrodrigues** [comment]
Was experiencing the same issue in Chromium (node-webkit) and @victordelacruz solution worked for me aswell. Thanks.

**Comment by Blair2004** [comment]
Thank you @victordelacruz for your solution, i was near to give up !!!

**Comment by batsauto** [comment]
Something I found before I implamented @victordelacruz solution. 

When you open the calendar via the triangle nothing shows up. but if you scroll a bunch while inside the calendar either up or down the months start to show up. I don't know what causes this I just found it interesting.

**Comment by muchrm** [comment]
It worked for me.

**Comment by topherfangio** [comment]
I believe this has been fixed in the latest release (1.1.3). Can someone else verify?

http://codepen.io/topherfangio/pen/ggzamo

**Comment by batsauto** [comment]
> I believe this has been fixed in the latest release (1.1.3). Can someone else verify?

According to my tests I believe it has been fixed with this update.

**Comment by topherfangio** [comment]
Awesome! I am going to go ahead and close this. If someone else continues to experience issues, please comment and we will reopen!

**Comment by akirna** [comment]
Enabling "preAssignBindings" fixed my datepicker too, **however, the rest of my webpage goes white while selecting a date.**

Using Angular 1.6.2, Angular Material 1.1.1, and Google Chrome. Any tips?

**Comment by batsauto** [comment]
Try updating your angular material to 1.1.3. This update cleared out the issue for me.

**Comment by akirna** [comment]
Nah, the whole webpage goes white when I update past Angular Material 1.1.1 for some reason. I'm sourcing the framework from googleapis and they don't seem to have 1.1.2+ yet.

**Comment by thomasmoreaumaster** [comment]
Hi everyone,

i post that comment cause i try to implement  @victordelacruz solution but it does not work, however i am in 1.1.4 version of angular-material.

My problem is when i put my crhome browser in 90% size, my md-datepicker is blank, i have to scroll in it to make it appear :/

![datetimeblank](https://user-images.githubusercontent.com/9032878/31219383-5d7de058-a9bd-11e7-9ffa-9b151e883c3b.png)

**Comment by arpit9295** [comment]
The problem seems to be back again.

Screenshot -
![image](https://user-images.githubusercontent.com/17565234/32138004-a13abfc6-bc48-11e7-89df-15a6517d6b4a.png)

Months appear again when scrolled, though.

**Comment by ashutoshbibyan** [comment]
same issue with me i am using the "@angular/material": "^5.0.0-rc0","@angular/core": "^5.0.3",
can anyone tell me where should i put  
angular.module('myApp', [])
    .config(function($compileProvider) {
      $compileProvider.preAssignBindingsEnabled(true);
    });

so i can check if that fix the problem .

**Comment by Splaktar** [comment]
@ashutoshbibyan Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by Arns** [comment]
@thomasmoreaumaster I'm having the same issue, on Macbook Pro when zooming the datepicker starts off blank but then dates appear once scrolled. Any fix yet?

**Comment by Arns** [comment]
More specifically, I'm having the issue when zooming out (90% and less). AngularJS Material 1.1.7 does not fix it. The compileProvider preAssignBindings option did not work either.

**Comment by Arns** [comment]
In my case, I've narrowed it down to being directly related to the datepicker having an "md-max-date" that is before the current date. It DOES NOT have an issue if you reverse it: "md-min-date" that is AFTER the current date.

Also seems that the reason it is missing is because the virtual repeat offset has not applied the translate css yet...

**Comment by Arns** [comment]
digging deeper yet:
<img width="1176" alt="localhost_8088_travel_1445000000013_search_1533000000016" src="https://user-images.githubusercontent.com/4078954/36497873-32a587b6-1702-11e8-9ced-4091d25ecef9.png">

**Comment by Splaktar** [comment]
@Arns please open a new issue for this with a CodePen demonstration of the problem.

**Comment by Arns** [comment]
@Splaktar https://github.com/angular/material/issues/11138

**Comment by VeBhairab** [comment]
I am using  "@angular/material": "^6.4.7", and Angular 6 and i got this above issue .
Please let me know what is solution for it.
Thanks .

**Comment by Splaktar** [comment]
@VeBhairab Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
