### ISSUE TITLE
md-options does not save the value in the field

### ISSUE THREAD

**Issue by nlamblin** [angular/material#10167]
Hello,

I'm using Angular Material 1.1.0

When i want to select an item from a list (md-select), the item isn't saved in the field.

Here's the input to select the favorite genre :
http://image.noelshack.com/fichiers/2016/51/1482413590-capture-du-2016-12-22-14-22-48.png

List of genres : 
http://image.noelshack.com/fichiers/2016/51/1482413590-capture-du-2016-12-22-14-23-03.png

After the choice, field is empty : 
http://image.noelshack.com/fichiers/2016/51/1482413590-capture-du-2016-12-22-14-23-25.png

My code :
http://image.noelshack.com/fichiers/2016/51/1482413805-capture-du-2016-12-22-14-36-34.png

Do you have any solutions? 

Thanks

**Comment by almothafar** [comment]
What Angular version are you using? if 1.6 I think it is a bug with Material because of breaking changes: 
https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-directives-select

**Comment by nlamblin** [comment]
@almothafar thank a lot for your answer.

I'm using AngularJS v1.5.5.

When I replace 

`<md-option ng-value="{{ genre }}" ng-repeat="genre in genres">`
      `{{ genre.name }}`
`</md-option>`

with

`<md-option ng-repeat="genre in genres" ng-value="{{ genre.name }}" value="string:{{ genre.name }}">`
          `{{ genre.name }}`
`</md-option>`

new errors appear. Errors like : 
Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 7-7 [&] in expression [Action & Adventure].
http://errors.angularjs.org/1.5.5/$parse/lexerr?p0=Unexpected%20nextharacter%20&p1=s%207-7%20%5B%26%5D&p2=Action%20%26%20Adventure

I presum a lexical error but i don't understand why ...
Some chars are not allowed by ng-value ?

**Comment by nlamblin** [comment]
I agree but when I do it, errors like that appear ...

Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 7-7 [&] in expression [Action & Adventure].

Error: [$parse:syntax] Syntax Error: Token 'Fiction' is an unexpected token at column 9 of the expression [Science Fiction] starting at [Fiction].

Error: [$parse:syntax] Syntax Error: Token 'Movie' is an unexpected token at column 4 of the expression [TV Movie] starting at [Movie].

Error: [$parse:lexerr] Lexer Error: Unexpected next character  at columns 4-4 [&] in expression [War & Politics].

And they appear when the "space" is present in the name.
So, i think that "space" is not allowed.

I don't how i can resolve it ...

**Comment by enzonotario** [comment]
I also have this problem. With angular-material 1.0.9, md-select works perfectly, but with 1.1.1 doesn't

**Comment by topherfangio** [comment]
@enzonotario Have you tried with the latest release? This should have been fixed by https://github.com/angular/material/commit/a73ab43c437ec7468d51da54f159b9f2845ec07b and released in 1.1.3.

If you're still having trouble, can we get a Codepen to investigate?

**Comment by enzonotario** [comment]
Sorry, but I'm now on angular2...

I'll find the old project where I have the error and try to make a codepen soon...

**Comment by ThomasBurleson** [comment]
@EladBezalel - can you investigate and fix?
