### ISSUE TITLE
checkbox: does not toggle when using indeterminate

### ISSUE THREAD

**Issue by Luca1234** [angular/material#10166]
The md-checkbox does not transition properly between states when using the indeterminate flag.
Even the initialization is broken.

Here is a demo showing the expected values. The demo also has buttons to transion between states.
https://codepen.io/lcodrutlucian/pen/ObGmGJ

For instance, it never transitions properly from (!checked, !indeterminate) to (checked, indeterminate).
Or, as in the demo, from (false, false) to (true, true).

The fix is simple:
In the checkbox.js file (for mdCheckbox directive), remove the "!isIndeterminate" condition from the first test in the method.

**Comment by Splaktar** [comment]
From the [`md-indeterminate` docs](https://material.angularjs.org/1.1.21/api/directive/mdCheckbox):

> This determines when the checkbox should be rendered as 'indeterminate'. If a truthy expression or no value is passed in the checkbox renders in the md-indeterminate state. If falsy expression is passed in it just looks like a normal unchecked checkbox. The indeterminate, checked, and unchecked states are mutually exclusive. A box cannot be in any two states at the same time. Adding the 'md-indeterminate' attribute overrides any checked/unchecked rendering logic. When using the 'md-indeterminate' attribute use 'ng-checked' to define rendering logic instead of using 'ng-model'.

[This CodePen](https://codepen.io/Splaktar/pen/OJyNpZz?editors=1010) demonstrates how this should work by removing the 'TRUE TRUE' and 'TRUE FALSE' options and replacing them with only a 'TRUE' option for `md-indeterminate="true"`. It also updates the `testClicked()` function to not set `test.checked` if `test.indeterminate` is `true`.
