### ISSUE TITLE
Doubts on md nested layout

### ISSUE THREAD

**Issue by hg533** [angular/material#10179]
**Angular Versions**: *
 -  `Angular Version:1.5.8`
 -  `Angular Material Version:1.1.1`

**Additional Information**:
 -  `Browser Type: chrome`
 -  `Browser Version: 53`
 -  `OS: win10`
I set window to 1000px. the following fine, blue width is 800px and the red is 200px;
```html
<body>
    <div ng-app="app">
        <div layout="row" >
            <div flex="80" style="background-color:blue">80</div>
            <div flex style="background-color:red">20</div>
        </div>

    </div>
    <script>
        var app = angular.module('app', ['ngMaterial']);
    </script>
</body>
```
When i change code to the following, the blue's width change to 900px,and the red change to 100px, why?
```html
<body>
    <div ng-app="app">
        <div layout="column" layout-gt-sm="row">
            <div flex="80" style="background-color:blue">80</div>
            <div flex style="background-color:red">20</div>
        </div>

    </div>
    <script>
        var app = angular.module('app', ['ngMaterial']);
    </script>
</body>
```

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)

> You must set a height/min-height to the `<div layout="column">` element.
