### ISSUE TITLE
grid-list: squeezed during page-refresh

### ISSUE THREAD

**Issue by Debananda** [angular/material#10171]
Grid list is getting squeezed during page-refresh. The issue persists for a fraction of second. I guess it is due to the height and width calculation that happens for the md-grid-tile. Is there a solution available to fix this
![issue](https://cloud.githubusercontent.com/assets/5937232/21445249/9f2e7822-c8dc-11e6-86f2-6e354c66ad58.png)

 `<md-grid-list md-cols-md="3" md-cols-lg="3" md-cols-sm="3" md-cols-xs="2" md-row-height-gt-sm="6:1" md-row-height="7:1" md-gutter="33px">
                    <md-grid-tile ng-repeat="language in vm.languages" class="language">
                        <a data-ng-click="vm.changeLanguage(language.key)">
                             <span ng-bind="language.language | humanize"></span>
                        </a>
                    </md-grid-tile>
                </md-grid-list>`

`

**Comment by beaubarbour** [comment]
Same problem here.  Very frustrating, have you figured anything out?

**Comment by mih-kopylov** [comment]
Same for me. Is there any ETA?

**Comment by Rejns** [comment]
Try to use ng-cloak.

**Comment by mih-kopylov** [comment]
@Rejns doesn't work for me

**Comment by Debananda** [comment]
I finally dropped the idea of md-grid-list. I found flex layout quite interesting to work with . It provides the same feature(with some twist in it).

**Comment by Splaktar** [comment]
Can you please provide the version of AngularJS and AngularJS Material that you are seeing this issue with?
Can you please provide a demo via CodePen?

I'm not able to reproduce this in [CodePen](https://s.codepen.io/Splaktar/debug/ppeQYa/LQAExPDawGpr) using the "Responsive Usage" demo from the docs.
