### ISSUE TITLE
md-dialog error when template is a directive

### ISSUE THREAD

**Issue by hg533** [angular/material#10174]
when template is directive md-dialog create nested two "<md-dialog..>" element.
my mydirective's template file like this:
-----------------------------------------------------------------------------------------------
```html
<md-dialog >
    <md-toolbar>
        <div class="md-toolbar-tools">
            <md-icon md-font-icon="fa fa-user"></md-icon>
            <h4>ttt</h4>
            <span flex></span>
            <md-button class="md-icon-button" ng-click="cancel()">
                <md-icon md-font-icon="fa fa-times" aria-label="Close dialog"></md-icon>
            </md-button>
        </div>
    </md-toolbar>
    <md-dialog-content layout-padding class="nodrag">
        <form name="frmProfile">
          ...
        </form>
    </md-dialog-content>
</md-dialog>
```
----------------------------------------------------------------------------------------
my directive is:
----------------------------------------------------------------------------------------
```js
app.directive('staffProfile', function () {
        return {
            restrict: 'EA',
            replace: true,
            priority:99,
            scope: {
                ngModel: '=?'
            },
            controller: 'staffProfileController',
            templateUrl: '/app/setting/staff/detail.html?ver=0.016',
        }
    });
```
----------------------------------------------------------------------------------------
my dialog code is:
----------------------------------------------------------------------------------------
```js
$mdDialog.show({
  fullscreen: true,
  parent: angular.element(document.body),
  template: "<staff-profile ng-model='staff.ID'/>",
  controller: ctrl
});
```
----------------------------------------------------------------------------------------
the md-dialog generate html is:
----------------------------------------------------------------------------------------
```html
<div class="md-dialog-container ng-scope" tabindex="-1" style="top: 0px; height: 700px;">
   <div class="md-dialog-focus-trap" tabindex="0"></div>
   <md-dialog class="_md md-dialog-fullscreen md-transition-in" role="dialog" tabindex="-1" id="dialogContent_1" aria-describedby="dialogContent_1">
   <md-dialog  ng-model="staff.ID" submit="ok" dismiss="cancel" usr-self="true" class="ng-pristine ng-untouched ng-valid ng-isolate-scope _md flex-70 ng-not-empty" aria-invalid="false" style="">
    <md-toolbar class="_md _md-toolbar-transitions">
        ...
    </md-toolbar>
    <md-dialog-content layout-padding="" class="nodrag layout-padding">
        ...
    </md-dialog-content>
 </md-dialog>
 </md-dialog>
<div class="md-dialog-focus-trap" tabindex="0">
</div>
</div>
```
----------------------------------------------------------------------------------------
It generate 2 md-dialog element and the 2nd opcity=0,so the dialog is only a small white box,nothing in it .

i post it to stackoverflow [http://stackoverflow.com/questions/41246561/angularjs-material-error-when-template-is-a-directive](url)

**Comment by iamfrontender** [comment]
Have you tried using `autoWrap: false` when calling `$mdDialog.show({ ... })`?

**Comment by EladBezalel** [comment]
I close this issue as i got the feeling it's not a real issue,
@hg533 if you still have the feeling it's an issue please comment here again and i will reopen and address it.

Thanks
