### ISSUE TITLE
FAB Toolbar - Blocking scrolling activity problem !!!

### ISSUE THREAD

**Issue by ctaihua** [angular/material#10182]
Hello, I recently apply the FAB Toolbar component in my ionic APP. I found the scrolling problem. I can not process the scrolling activities in the Toolbar area. Is there any way I can by pass this issue? thank you.  
Please refer my screen shoot file, thank you.

(https://cloud.githubusercontent.com/assets/3983194/21490806/e8026046-cc32-11e6-9795-ef3774514cd9.png)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
