### ISSUE TITLE
Predefined md-dialog, button event is undefined

### ISSUE THREAD

**Issue by skylee91** [angular/material#10184]
**Actual Behavior**:
 -  `What is the issue? *` The close button is not working after clicked. But it is working when clicked outside area of dialog. The error message I get using Batarang Angular is cancel is undefined.
 -  `What is the expected behavior?` Click the close button, will fire the ng-click="cancel()" event.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` (http://codepen.io/skylee91/pen/yVdPga?editors=1000)
 -  `Details:` If I change the angular material version to 1.1.0 instead of 1.1.1, the button event is fired and closed as expected.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Desktop
 -  `Browser Version: *` Version 55.0.2883.87 m (64-bit)
 -  `OS: *` Windows 10 Pro
 -  `Stack Traces:` none

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by marcusasplund** [comment]
Just a thought, might have something to do with this change:
https://github.com/angular/material/pull/9303

**Comment by DevVersion** [comment]
Pre-rendered Dialogs will be not linked to any scope and will not instantiate a new controller.

> This means that there is no controller with the `cancel` method.

See https://material.angularjs.org/HEAD/api/service/$mdDialog#pre-rendered-dialogs

It would be desired to have a warning in the `$mdCompiler` when options like `controller` are used, but a `contentElement` is specified.
