### ISSUE TITLE
md-slider is not working in chrome 55 version in Android Phones

### ISSUE THREAD

**Issue by manakbhard** [angular/material#10187]
**Actual Behavior**:
Drag of slider is not working properly only click is working

**CodePen** (or steps to reproduce the issue): *

Open the demo link of angular material in Chrome 55 on Android Phone
https://material.angularjs.org/latest/demo/slider

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:`0.11.4

Note :- these are versions of my current app it is not working for even 1.1.1 version of angular material

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *` 55
 -  `OS: *`Android
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by praveengupta29** [comment]
+1

**Comment by bbialas** [comment]
+1

**Comment by clshortfuse** [comment]
Might be because fastClick. Will investigate

**Comment by clshortfuse** [comment]
Not working properly on ChromeOS either. Might be all touch systems.

**Comment by bbialas** [comment]
Any new ideas?

**Comment by mohammadrafigh** [comment]
it's related to #10145

**Comment by mustaqahmed** [comment]
As I commented on the md-slider issue above, this bug is an existing crack in handling PointerEvents in Angular. That's why Edge on a Windows touch device shows the same bug.

Adding a <code>touch-action: none</code> style to the slider element fixes the problem.

@clshortfuse: perhaps adding a <code>touch-action: none</code> for .md-slider-wrapper is enough.

**Comment by salsaverde123** [comment]
You're fucking awesome, You saved my live. Thank You. "No all super heroes wear capes "
