### ISSUE TITLE
md-nav-ink-bar doesn't update when dynamic change nav-item

### ISSUE THREAD

**Issue by gengen1988** [angular/material#10197]
**Actual Behavior**:
 -  `What is the issue? *` md-nav-link-bar doesn't change position after nav-item has been removed
 -  `What is the expected behavior?` it will stay the position of the current nav item

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/GqpByo
 -  `Details:` select tab 3, then check the checkbox.

**Angular Versions**: *
 -  `Angular Version:` 1.5.10
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *`  55.0.2883.95 (64-bit)
 -  `OS: *` Mac OS X 
 -  `Stack Traces:` N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by bradrich** [comment]
@gengen1988 I believe that you are mistaken about the functionality of the `mdNavBar`. It seems that you are confusing the `md-selected-nav-item` with a controller for dynamic items within the nav bar, where you would be able to set the expression referenced in that attribute to undefined and it would delete the nav item. That is not what that attribute is intended to do. 

`md-selected-nav-item` is used for two things:

1. Control what tab you are currently on from the controller.
2. Gain access to tab-specific information from within the tab's content.

Please see http://codepen.io/bradrich/pen/PWNyGB. It is an approach that provides dynamic nav items within the nav bar. It is a basic approach, but you could extend it to allow you to add tabs, etc.

Unless I am mistaken, I am going to close this issue. Please let me know if you have any questions.

**Comment by gengen1988** [comment]
Hi bradrich, thanks for the example. It works just as my want.

PS. the CodePen in the first post seems like my mistake. It should be this one:
http://codepen.io/alsorunning/pen/EZmybx

I may misuse `ng-if` in that case. However, the latest example is ok for me. Thanks again.

**Comment by Huespal** [comment]
Fail in Safari https://codepen.io/bradrich/pen/PWNyGB
ink bar is bad calculated. Larger than in chrome. Can be fixed?
It also happens in angular demo, but not always.

https://material.angularjs.org/latest/demo/navBar

Thanks.

**Comment by Splaktar** [comment]
@Huespal please open a separate issue.
