### ISSUE TITLE
 mdIsError doesn't work with mdChips and mdAutocomplete

### ISSUE THREAD

**Issue by ppham27** [angular/material#10193]
**Actual Behavior**:
 -  `What is the issue? *` mdIsError doesn't work with mdChips and mdAutocomplete
 -  `What is the expected behavior?` I should be able to provide an expression to toggle the container to the error state.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/phillypham/pen/KNOrbM?editors=1010
 -  `Details:` It works when mdChips is used with an input. Use the switches at the top to make errors appear and disappear. If you uncomment Line 28 of the JavaScript, where I override the container's `isErrorGetter` method, everything works as expected.

**Angular Versions**: *
 -  `Angular Version:` 1.5.9
 -  `Angular Material Version:` 1.1.1, current master branch

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55
 -  `OS: *` macOS Sierra, OS 10.12.2 or Ubuntu 14.04 LTS
 -  `Stack Traces:` N/A

There's also an issue with labels, but that's an entirely separate issue.

**Comment by Splaktar** [comment]
As noted in https://github.com/angular/material/issues/11155, `md-chips` is not supported within `md-input-container` at this time. Additionally, `md-autocomplete` is not supported within `md-input-container` either. You can see how to make Autocomplete work in a form with other inputs in the "Floating Label" [demo here](https://material.angularjs.org/latest/demo/autocomplete).

`md-is-error` is a feature of `md-input-container`, thus it does not work for chips or autocomplete.
