### ISSUE TITLE
md-tabs only swipes one direction with md-swipe-content

### ISSUE THREAD

**Issue by jonbernard** [angular/material#10194]
**Actual Behavior**:
 -  `What is the issue? *` When using `md-swipe-content` with `md-tabs`, the tabs only move to the right, regardless of which way you swipe.

**CodePen** (or steps to reproduce the issue): *
 -  `Details:` Set up `md-tabs` with the `md-swipe-content`. Try swiping.

**Angular Versions**: *
 -  `Angular Version:` At least 1.5.5 & 1.5.10.
 -  `Angular Material Version:` At lease 1.1.1.

**Additional Information**:
 -  Chrome android 55.0.2883.91, Chrome 55.0.2883.95 Mac (mobile emulator)  and Cordova applications 6.3.1

**Comment by Jodes81** [comment]
I'm getting the same problem for all the other components - I raised this issue too: https://github.com/angular/material/issues/10195

**Comment by RoniPa** [comment]
I think both of these are related to this issue: #10145

**Comment by jonbernard** [comment]
Closing issue because #10145 encompasses the fixes for this issue.
