### ISSUE TITLE
is there any option to give md-virtual-repeat for whole page ?

### ISSUE THREAD

**Issue by DeveBj** [angular/material#10199]
I need to have md-virtual-repeat for whole page, if the page is scrolled the virtual scroll must take place within the body, if I use md-virtual-repeat-container am getting a container within that am getting virtual repeat but I need to take the container and achieve virtual scroll in the whole page (scrollable), please help me to resolve this issue

**Comment by speedmax123** [comment]
two steps:

* you need to adjust the <md-virtual-repeat-container>'s height with data binding to fit the browser's height and make it like full screen
* put all your element inside the <md-virtual-repeat-container>

if you follow these two steps, your basic requirement should be satisfied, plus maybe you should add a window resize event handler to calculate the browser height dynamically and and using data-binding to adjust the <md-virtual-repeat-container>'s height.(of course, width of it is always 100%)

all these can make a perfect full page virtual repeat
