### ISSUE TITLE
Bottom Sheet example not going away with down swipe

### ISSUE THREAD

**Issue by Jodes81** [angular/material#10195]
**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

List demo does not go away with down swipe. Grid demo does not go away at all - with down swipe or touch elsewhere.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

1. Go to https://material.angularjs.org/latest/demo/bottomSheet
2. Tap "show as list" button or "show as grid"
3. Swipe down on menu that appears, or outside, but still in "basic usage" box, or outside that

Edit: Likely cause: only left swipe works on swipe demos:
https://material.angularjs.org/latest/demo/swipe

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

Tested on above URL as at 7:27am GMT 30the Dec 2016

**Additional Information**:
 -  `Browser Type: Chrome browser `
 -  `Browser Version: 55.0.2883.91`
 -  `OS: Android Lollipop (Galaxy Tab 4)`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This is working now in 1.1.7 (and likely a number of earlier releases). Tested on Chrome stable for Android and Chrome for macOS.
