### ISSUE TITLE
CDN sample code wrong

### ISSUE THREAD

**Issue by Erhannis** [angular/material#10196]
**Actual Behavior**:
 -  `What is the issue? *` - The sample CDN code is wrong.  It links the wrong css - it says it's using 1.0.7, but it's using 0.11.2.  This makes dialog action buttons show up above the content.
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): * - Try using the css given; it probably breaks newer code depending on that css.
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: * - All of them, I guess?  Anything new.  The current one, at least.
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *` - Firefox
 -  `Browser Version: *` - 50.1.0
 -  `OS: *` Windows 10 x64 Enterprise
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
FYI - We only support demo issues from 

* [Latest Release](https://material.angularjs.org/latest/)
* [Dev Master](https://material.angularjs.org/HEAD/)
