### ISSUE TITLE
select: with ng-model-options not working correctly

### ISSUE THREAD

**Issue by sky10p** [angular/material#10201]
**Actual Behavior**:
 -  `What is the issue? *`
    md-select with a ng-model-options doesn't work. 
 -  `What is the expected behavior?`
     The ng-model option should appear as the selected item. However, the field is empty.

**Code Pen**:
-http://codepen.io/anon/pen/vgYLoY

**Angular Versions**: *
 -  `Angular Version:` 1.6.0
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` google chrome 
 -  `Browser Version: *` 55.0.2883.87 m
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
I was able to reproduce this in the provided CodePen for `1.1.1`. I [updated the CodePen](https://codepen.io/Splaktar/pen/JjPWMBd?editors=1010#0) to `1.1.20` and verified that this issue is fixed.
