### ISSUE TITLE
md-input-container input doesn't blur

### ISSUE THREAD

**Issue by jarekskuder** [angular/material#10213]
When i blur simple inputs without md-input-container - it blurs. When i blur an md-input-container input - it woun't blur. 
I tried add ng-blur function - still no luck.

HTML code:

`<div layout="row" layout-align="center center">
        <md-input-container class="uppercase">
            <label>{{translates.enter_car_plate_template}}</label>
            <input class="uppercase" type="text" ng-model="auto_number_edit" ng-blur="hideKeyboard()" style="text-align: center;font-size: 28px;font-weight: 600;color: white; width: 200px; height: 50px">
        </md-input-container>
    </div>`

**Comment by atishaybaid** [comment]
facing the same issue

**Comment by hexadecy** [comment]
I had to remove the class md-input-focused.

**Comment by noosxe** [comment]
Same here, is anybody going to have a look at this ?

**Comment by hexadecy** [comment]
From the input:
```
element.blur();
element.parent().removeClass('md-input-focused');
```

**Comment by noosxe** [comment]
I don't event get ng-blur event on input itself.

**Comment by Splaktar** [comment]
It's not clear what is being requested here. There is no demo and the OP doesn't use the issue template.

If you have found an issue with using `ng-blur` on an `input` within `md-input-container`, please open a new issue with a CodePen reproduction.
