### ISSUE TITLE
md-text-float: Flashes regular input styles on load

### ISSUE THREAD

**Issue by epelc** [angular/material#1021]
As you can see in the following gif `md-text-float` will flash with the browsers default styles when loading. My guess is that the input is created and then the class for styles is added slightly after creation. But I haven't confirmed this so maybe someone can take a look at it. It might also have something to do with the transitions.

![input lag](https://cloud.githubusercontent.com/assets/5204642/5517060/e38820d8-8895-11e4-97c3-9b1f08f24b0f.gif)

**Comment by trazek** [comment]
I am having this same issue but on page refresh. It seems to happen on pages/partials with a `<div>` as the root element rather than `<md-content>`. 

@epelc See if you have a similar experience.

**Comment by epelc** [comment]
@trazek Saddly that along with other various placements of `md-content` didn't work

As a side note are you supposed to put content inside of `md-card` inside of `md-content`? I remember seeing something about possibly adding `md-card-content` but it was awhile ago.

**Comment by DefunctExodus** [comment]
Looks like md-card-content was added a few minutes ago.

@trazek <https://github.com/trazek> Saddly that along with other various
placements of md-content didn't work

As a side note are you supposed to put content inside of md-card inside of
md-content? I remember seeing something about possibly adding
md-card-content but it was awhile ago.

—
Reply to this email directly or view it on GitHub
<https://github.com/angular/material/issues/1021#issuecomment-68942054>.

**Comment by epelc** [comment]
@trazek I'm on a master from about a week ago. I'll check with the latest tomorrow though.

**Comment by trazek** [comment]
@epelc I upgraded and have the flashing issue on only one element out of several strangely. I'll keep an eye out and post back if I find anything helpful to solving the problem.

**Comment by epelc** [comment]
@trazek Thanks for the info.

I won't bother with updating today then. I'm busy learning redis now anyways.
