### ISSUE TITLE
Starter Project 

### ISSUE THREAD

**Issue by FadyM** [angular/material#1022]
I am unable to create a starter project for material angular 
I have used https://github.com/achudars/AngularJS-MVC-Web-App-Template to create the starter template for angular and then i used bower to install it ? is it possible to create a starter project that we can start with if not can anyone provide help on how to create one ?

Thank you,

**Comment by ThomasBurleson** [comment]
A starter project, starter CodePen, and start Plunkr will be available soon...

**Comment by marcysutton** [comment]
@FadyM here is a starter repo: https://github.com/angular/material-start

**Comment by mzbyszynski** [comment]
Hi @marcysutton! Is that a private repo? That link isn't working for me...

**Comment by marcysutton** [comment]
Ahh! It might not be public yet. Sorry about that! I'll repost it when it's ready.

**Comment by marcysutton** [comment]
The Starter project is now available: http://github.com/angular/material-start
