### ISSUE TITLE
datepicker: adds a -top value to body when body has a margin-top value set

### ISSUE THREAD

**Issue by killyosaur** [angular/material#10223]
**Actual Behavior**:
 -  `What is the issue? *`
Currently working on a app that uses bootstrap for most of its design elements and would like to start using Material Design components. Problem is, the app has a fixed navbar with a margin on the body to be sure that content is visible under the navbar, and because of the nature of the app, all overflow is hidden. Angular material's Datepicker puts styles on the body to remove that margin causing the headers under the nav bar to vanish.
 -  `What is the expected behavior?`
The Date picker should not cause the page to move, especially when there is no need for it (scrolling of the page is turned off.)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen:` [http://codepen.io/Killyosaur/pen/egmLoE](http://codepen.io/Killyosaur/pen/egmLoE)
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome, Internet Explorer
 -  `Browser Version: *` 54, 11
 -  `OS: *` Windows 7

**Comment by Splaktar** [comment]
I am able to reproduce this with the given CodePen (AngularJS Material 1.1.0). I updated [the CodePen](https://codepen.io/Splaktar/pen/QWjKZeP) to AngularJS Material 1.1.21 and I was able to verify that this issue has been resolved.
