### ISSUE TITLE
interpolation throw exception on md-datepicker

### ISSUE THREAD

**Issue by sohail85** [angular/material#10238]
Unable to use conditional expression inside ng-disabled directive on md-datepicker
and it throws following exception

> angular.js:14110 Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{Criteria1 || Criteria2}}] starting at [{Criteria1 || Criteria2}}].

the way its being use :

`<md-datepicker  ng-model="myModel" ng-disabled="{{Criteria1 || Criteria2}}"></md-datepicker>`

**Comment by Splaktar** [comment]
This is because we don't accept an expression for `ng-disabled`, it needs to be a value that evaluates to `boolean` [as documented](https://material.angularjs.org/HEAD/api/directive/mdDatepicker).
