### ISSUE TITLE
fab-speed-dial: multiple within ngRepeat open at the same time when using ng-mouseenter

### ISSUE THREAD

**Issue by arnaumanyosa** [angular/material#10237]
**Actual Behavior**:
 -  `What is the issue? *` Multiple mdFabSpeedDial created with ngRepeat open all together at the same time when using `ng-mouseenter/ng-mouseleave` and `md-open`
 -  `What is the expected behavior?` Would be nice to be able to open just the one FabSpeedDial that is hoovered

**Code example**
```
<md-list-item class="md-2-line" ng-repeat="item in results.list">
   <div class="list-item-content-wrapper">
      <div layout="row">Title</div>
      <div layout="row">
         <md-fab-speed-dial md-direction="right" md-open="demo.isOpen"
                       ng-mouseenter="demo.isOpen=true" ng-mouseleave="demo.isOpen=false">
            <md-fab-trigger>
              <md-button class="md-fab md-mini">
                <md-icon md-svg-src="images/menu.svg"></md-icon>
              </md-button>
            </md-fab-trigger>
            <md-fab-actions>
              <md-button class="md-fab md-raised md-mini" 
                <img src="option1.png">
              </md-button>
              <!-- more buttons -->
            <md-fab-actions>
         </md-fab-speed-dial>
      </div>
   </div>
</md-list-item>
```

**Angular Versions**: *
 -  `Angular Version:` v1.5.8
 -  `Angular Material Version:` v1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` 55.0.2883.95 (64-bit)
 -  `OS: *` Mac OS X El Capitan 10.11.6

**Comment by Splaktar** [comment]
This is just because they are sharing the same field for whether or not they should open.

[This demo](https://codepen.io/Splaktar/pen/ZEbgRoe) shows how you can have each item has it's own `isOpen` value and see only 1 opening at a time.
