### ISSUE TITLE
Text Field minlength doesn't set ng-invalid

### ISSUE THREAD

**Issue by madvas** [angular/material#1023]
Let's say I have this element
```<md-text-float label="LastName" minlength="5" ng-model="user.lastName" class="long"></md-text-float>````

When I put too short input it sets `ng-invalid` to `<md-input-group>` element but it doesn't set `ng-invalid` to underlying `<input>` element. It stays `ng-valid`.

So result code from upper element would be:
```
<md-input-group tabindex="-1" label="LastName" minlength="5" ng-model="user.lastName" class="long ng-isolate-scope md-default-theme md-input-has-value ng-invalid ng-invalid-minlength" aria-invalid="true"> 

<label for="008" class="ng-binding">LastName</label> 

<input id="008" ng-disabled="isDisabled()" ng-model="value" type="text" tabindex="false" aria-invalid="false" aria-disabled="false" class="ng-valid ng-dirty ng-valid-parse ng-touched">

</md-input-group>
```

`ng-minlength` doesn't work at all.

Thanks!

**Comment by ajoslin** [comment]
Fixed via 60fcd6f4d8b895162b37a940c3f33164d8044382
