### ISSUE TITLE
blank screen in md-datepicker

### ISSUE THREAD

**Issue by gokulanbu26** [angular/material#10244]
![blank_date](https://cloud.githubusercontent.com/assets/23076162/21795324/2b4f1db8-d727-11e6-927c-76410019a139.png)

<md-input-container class="md-block" flex-gt-xs>
                <label>Start date</label>
                <md-datepicker name='start_date' ng-model="vm.plan.start_date" ng-init="vm.plan.start_date = vm.startDate" required></md-datepicker>
                <span style="color: red" ng-show="userForm.start_date.$touched && userForm.start_date.$error.required">Start date is required.</span>
              </md-input-container>
              <md-input-container class="md-block" flex-gt-xs>
                <label>End date</label>
                <md-datepicker name='end_date' ng-model="vm.plan.end_date" ng-init="vm.plan.end_date = vm.endDate" required></md-datepicker>
                <span style="color: red" ng-show="userForm.end_date.$touched && userForm.end_date.$error.required">End date is required.</span>
              </md-input-container>

**Comment by bopm** [comment]
https://github.com/angular/material/issues/10168#issuecomment-268886473

**Comment by grantfeldman** [comment]
+1
