### ISSUE TITLE
input: ng-messages do not work if animation is disabled

### ISSUE THREAD

**Issue by nikclayton** [angular/material#10240]
**Actual Behavior**:

With a form like:

```html
<form name="f">
  <md-input-container class="md-block">
    <label>Some text</label>
    <input type="text" name="i" placeholder="Enter something" required />
    <div ng-messages="f.i.$error">
      <div ng-message="required">This field is required.</div>
    </div>
  </md-input-container>
</form>
```

Everything works -- tab in to the field, tab out, and the field behaves as expected. Specifically:

1. The placeholder text "Enter something" appears in red.
2. The form field is underlined in red.
3. The text "This field is required." appears underneath the field.

However, if your app turns off animation by, for example, injecting a $animate instance and calling $animate.enabled(false), (1) and (2) still occur, but (3) no longer happens -- the ng-message does not appear.

This is a regression from 1.0, where it did work.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/dNYKwr
 -  `Details:` That codepen is identical to the one at https://material.angularjs.org/latest/demo/input (the "Errors Advanced" section). All I've done is change the controller to inject `$animate`, set `$scope.showHints = false`, and then called `$animate.enabled(false);`.

If you change that to `$animate.enabled(true)` the errors will start appearing again.

**Angular Versions**: *
 -  `Angular Version:` 1.5.x
 -  `Angular Material Version:` 1.1.x

**Additional Information**:
 -  `Browser Type: *` Chrome.
 -  `Browser Version: *` 55.0.2883.87
 -  `OS: *` Ubuntu 14.04
 -  `Stack Traces:` N/A

**Comment by nikclayton** [comment]
Suspect that https://github.com/angular/material/commit/cf7f21aa6c633d9f0bd22013e9a79f99b82b16af is the culprit, which unconditionally uses $animate() to add new classes instead of checking to see if animation is enabled.

**Comment by clshortfuse** [comment]
@nikclayton Correct. I'm the process of moving the animations to pure CSS. It just needs more testing but I'll probably have it ready for today. 

The reason why we moved to $animate was due to a flicker bug. We can now move back to CSS because of the newer ng-enter-prepare class that was added since.

**Comment by topherfangio** [comment]
I've removed the `has: Pull Request` label because the PR didn't account for many instances. I think we should just check if animation is enabled and if not, call `element.addClass()`. I will look into this soon.

**Comment by Splaktar** [comment]
I updated the [CodePen](https://codepen.io/Splaktar/pen/MLGPRg) to `1.1.12` and it appears to be working properly. It looks like this was fixed indirectly already.

**Comment by clshortfuse** [comment]
Looks like it was fixed in https://github.com/angular/material/commit/0151b4bed9d90aa942734591615878f5fcc0fe52

The commit didn't closed the issue. I'm not entirely sure why.

**Comment by Splaktar** [comment]
@clshortfuse thank you! It didn't close it because you need a `Fixes` for each issue #. I.e. `Fixes #. Fixes #.`
