### ISSUE TITLE
md-autocomplete calculates invalid original height

### ISSUE THREAD

**Issue by Venthe** [angular/material#10249]
**Actual Behavior**:
 -  `What is the issue? *`
When using md-autocomplete as multiselect (selecting item from list removes it from suggestions) SOMETIMES the original height will be reduced by eg. 2px. 
The change occurs on md-virtual-repeat-container, where inline style-height reduces.
Faulty behaviour can be seen in VirtualRepeatContainerController.prototype.autoShrink
 -  `What is the expected behavior?`
List height con changing from original

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome; Firefox Devel
 -  `Browser Version: *` 55; 52.02
 -  `OS: *`Win10
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
