### ISSUE TITLE
md-datepicker CSS empty display issue - v 1.1.1

### ISSUE THREAD

**Issue by elgambet** [angular/material#10241]
I've upgraded to Angular Material 1.1.1. I'm using Angular JS v1.6.1.

The issue I have is when I use the standard code as follows:

```
<md-content>
  <h4>Standard date-picker</h4>
  <md-datepicker ng-model="test" placeholder="Test date"></md-datepicker>
</md-content>
```

When I select the picker, I get an empty div that is loaded only when i scroll.

[Codepen example](http://codepen.io/anon/pen/MJaBxZ?editors=1000)

**Comment by bopm** [comment]
https://github.com/angular/material/issues/10168#issuecomment-268886473

**Comment by elgambet** [comment]
Yep that worked for me @bopm, thanks!

**Comment by elgambet** [comment]
Should be closed. Duplicated of #10168
