### ISSUE TITLE
md-chips : $mdUtil should be bound to instance

### ISSUE THREAD

**Issue by myagoo** [angular/material#10245]
There is a typo in https://github.com/angular/material/blob/v1.1.1/src/components/chips/js/chipsController.js#L444

$mdUtil is used from `this` but was never bound to it upon construction

**Actual Behavior**:
 -  `What is the issue? *` An error is thrown when removing a chip
 -  `What is the expected behavior?` No error thrown

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This should have been fixed in `master` already. `$mdUtil` was not added to the controller instance in the constructor

**Comment by Splaktar** [comment]
Fixed in `1.1.2` via PR https://github.com/angular/material/pull/9528.
