### ISSUE TITLE
md-tag-input for Tag based inputs?

### ISSUE THREAD

**Issue by vipulsaxena** [angular/material#1024]
We still don't have any tag inputs like http://angular-js.in/ngtagsinput/

should we expect this any sooner into material-angular?

**Comment by breandr** [comment]
I guess it's a combination of autocomplete and chips?

**Comment by adamelevate** [comment]
+1

**Comment by ThomasBurleson** [comment]
See Chips and ContactChips.

**Comment by longsangstan** [comment]
But the style of chips is not similar to normal input?
For example, in an input box when you start typing the label will float up.

Also, functions like required and showing error messages don't work in chips.
