### ISSUE TITLE
util: disableScrollAround improperly adds scrollBar to body

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#10252]
**Actual Behavior**:
 -  `What is the issue? *` mdUtil.disableScrollAround sometimes improperly detects scrollbar
 -  `What is the expected behavior?` scrollbar not should be added if not previously present

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` With hidden overscroll on body and iframes: http://codepen.io/shortfuse/pen/xgVRWL
 -  `Details:` I added the results of getBoundingClientRect() which is what I believe we should be using instead of using scrollHeight and clientHeight

**Angular Versions**: *
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` v55
----

There may also be a sub 1px issue because of the fact scrollHeight and clientHeight use rounded integers. I wasn't able to create a page to exhibit the issue, but moving to `getBoundingClientRect` would correct this possible issue.

ping @jelbourn

**Comment by Splaktar** [comment]
It looks like this was referring to

https://github.com/angular/material/blob/ff531361e6d6943191a24b16dc11165cdc24a1fb/src/core/util/util.js#L286

I updated the [CodePen](https://codepen.io/Splaktar/pen/exrPKq) to `1.1.12` and this appears to have been resolved via another change already.
