### ISSUE TITLE
subheader: incorrect position when md-content has layout-padding attribute

### ISSUE THREAD

**Issue by Skryabind** [angular/material#10259]
**Actual Behavior**:
 -  `What is the issue? *`
Adding layout-padding in md-content causes incorrect position of sticky subheader when scrolling. Also horizontal scrolling appears. 
 -  `What is the expected behavior?`
No horizontal scroll, position of subheader without extra left margin.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/skryabind/pen/VPKvEq
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
1.5.5
 -  `Angular Material Version:`
1.1.1
**Additional Information**:
 -  `Browser Type: *`
Google Chrome
 -  `Browser Version: *`
55.0.2883.95 (64-bit)
 -  `OS: *`
MacOS 10.12.2
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
I can't reproduce the horizontal scrolling with any release. But I do see a second vertical scroll bar.

I would recommend that you don't use `layout-padding` or `layout-margin` on an `md-content` with a sticky toolbar. It would be best if you selectively applied your styles to the specific elements that need them.

Here's [an example](https://codepen.io/Splaktar/pen/zYrGxjm) of that where the section has extra padding, but the`md-content` does not.
