### ISSUE TITLE
While using nested tab attribute md-align-tabs to bottom on top most tab but unfortunately it's also getting applied to inner tabs

### ISSUE THREAD

**Issue by DipParmar** [angular/material#10256]
<md-tabs layout="column" class="md-primary" md-selected="data.selectedIndex" md-align-tabs="{{checks[data.selectedIndex] ?'bottom':'top'}}" layout-fill >
               			<md-tab id="Tab{{checkBottom}}" ng-repeat="checkBottom in checkDataBottom">
                  			<md-tab-label>Tab{{checkBottom+1}}</md-tab-label>
                  			<md-tab-body>
				  				<div layout="row" layout-sm="column" layout-align="left center">
            						<md-checkbox ng-model="checks[checkBottom]" ng-change="change()" aria-label="Align tabs to bottom?" style="margin: 5px;">Tab to bottom</md-checkbox>
            							<md-tabs layout="column" class="md-primary" md-align-tabs="top" md-selected="" layout-fill>
            							<md-tab>
            								<md-tab-label>Tab 1</md-tab-label>
            								<md-tab-body>Tab2</md-tab-body>
            							</md-tab>
            							</md-tabs>
         		 				</div>
         		 			</md-tab-body>
               			</md-tab>
            		</md-tabs>

**Comment by DipParmar** [comment]
Please Help me what can I do right now?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
