### ISSUE TITLE
button: needs to be tapped twice in order to fire the click event (iOS)

### ISSUE THREAD

**Issue by perry2of5** [angular/material#10257]
Bug, feature request, or proposal:
Bug

**Actual Behavior**:
 -  `What is the issue? *`
The first tap highlights the button. The second tap fires the click event.
 -  `What is the expected behavior?`
A tap on the button should fire the click event.

**CodePen** (or steps to reproduce the issue): *
Buttons must be double clicked on iOS mobile Safari. For example, the share button on:
EDIT: 2017-02-08: the link below no longer leads to an app with the problem. See comment below for work-around used.
https://app.sharerevolution.com/index.html#!/find/Cleaning/businesses?in_city=none

**Angular Versions**: *
 -  `Angular Version:`
1.6.1
 -  `Angular Material Version:`
1.1.1

**Additional Information**:
 -  `Browser Type: *`
iOS Safari on iOS 10.0.2
 -  `Browser Version: *`
iOS Safari on iOS 10.0.2
 -  `OS: *`
iOS 10 on iPhone 5. Replicable in iPhone 5 emulator with iOS 10. Not replicable with iPhone 7 emulator and iOS 10.

Seems nearly identical to the issue for Material 2
https://github.com/angular/material2/issues/1316

**Comment by barryvdh** [comment]
I'm also getting a similar problem on Android, but not sure if that's the same issue.
According to that issue, it would require disabling the `::hover` styles on devices with touch?

**Comment by barryvdh** [comment]
Sorry I think my issue is different; it was buttons getting a hover class (which was differently styled in my case), which made the users think they clicked correctly, but instead just tap/focused.

**Comment by doronsever** [comment]
+1

**Comment by perry2of5** [comment]
I replaced all my md-content elements with a div with one of the following classes according to my needs:

.sr-scroll-overflow-y {
  display: block;
  position:relative;
  overflow-x: hidden;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}

.sr-scroll-overflow-y-no-position {
  overflow-x: hidden;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
}

Then iOS clicks worked on the first click. I'm not sure where the issue lies exactly, but this is the second app I've removed md-content elements from to fix issues. However, it sometimes gets tough to keep the footer at the bottom of the page after this. The following class works around the bugs in IE and Safari:

.sr-fill-above-footer {
    flex:1 0 auto;
}

**Comment by perry2of5** [comment]
that is the same issue @barryvdh! The hover classes need to be enabled only for mouse interactions which is a non-trivial chore. If only people knew a button was a button with flat design....

**Comment by supportQuadra** [comment]
We dont have the md-content, but we have the same problem on Android in 2 hybid apps using cordova !
Angular version : 1.5.8
Angular material : 1.1.1

**Comment by fabienmoyon** [comment]
+1

**Comment by Splaktar** [comment]
It looks like this was solved in Angular Material via this PR https://github.com/angular/material2/pull/1792. We should be able to implement a similar solution.

Would anyone from the community be willing to investigate and open a PR for AngularJS Material based on the Angular Material PR?

**Comment by Splaktar** [comment]
The fix in https://github.com/angular/components/pull/1792 appears to have mostly been related to the use of `::after` for styling buttons. AngularJS Material buttons don't use `::after` at all.

There is [one bit](https://github.com/angular/components/pull/1792/files#diff-750d8b0165eb725928c42839553a022bR8) where `touchstart` events have their default behavior prevented. That could potentially be helpful here.

There was no CodePen demo or clear reproduction steps provided with this issue. How can I reproduce and verify this issue?

There is a mention of `md-content`. The Button demos on https://material.angularjs.org/latest/demo/button wrap the demos with `md-content` and I can't seem to reproduce the issue there.

Is this only when the buttons have tooltips? I didn't see them mentioned in this issue, but it would be a possible way that `:hover` could be involved or problematic.

Does this happen in apps with click hijacking turned on or off or both? Details about how to turn that off can be found [here](https://material.angularjs.org/latest/api/service/$mdGestureProvider).

**Comment by Splaktar** [comment]
No response to my request for feedback or for a demo reproduction. Closing.
