### ISSUE TITLE
card: overlap issues

### ISSUE THREAD

**Issue by smuellerus** [angular/material#10267]
I've spent hours on this and have posted this issue on StackOverflow before, but with no success:
http://stackoverflow.com/questions/41246596/angular-material-cards-with-flex-layout-overlap

**Actual Behavior**:
 -  `What is the issue? *` When using several md-cards in a flex layout, the cards overlap, see the following screenshot:

![image](https://cloud.githubusercontent.com/assets/2101681/22028522/c6e2d692-dcd7-11e6-91a0-af4496151684.png)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/smuellerus/pen/oBYeyR
 -  `Details:` **Important**: Note that everything looks good in the CodePen, but if you save the HTML to a file and open it in Chrome, the md-cards overlap - see the md-cards at the bottom.

**Angular Versions**: *
 -  `Angular Version:` 1.5.9
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55.0.2883.87
 -  `OS: *` Ubuntu 16.04

**Comment by Splaktar** [comment]
It looks like this [was resolved](https://stackoverflow.com/a/41718042/633107) by adding `<!DOCTYPE html>`.
