### ISSUE TITLE
datepicker: display bug on Angular 1.6.1

### ISSUE THREAD

**Issue by saidelimam** [angular/material#10261]
**Actual Behavior**:
 -  `What is the issue? *` Datepicker display is not as expected
 -  `What is the expected behavior?` Show datepicker

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/saidelimam/pen/oBzyOw
 -  `Details:` Datepicker Demo with AngularJs 1.6.1

**Angular Versions**: *
 -  `Angular Version:` 1.6.1
 -  `Angular Material Version:` 1.1.1

![md-1_1_1-bug-ng-1_6](https://cloud.githubusercontent.com/assets/169009/21981279/f0697404-dbe6-11e6-9018-79dade16978a.PNG)

**Comment by mahdiraddadi** [comment]
[#10168 (comment)](https://github.com/angular/material/issues/10168#issuecomment-268886473)

**Comment by Splaktar** [comment]
Fixed in `1.1.2` ([Updated CodePen](https://codepen.io/Splaktar/pen/MddrXG)).
