### ISSUE TITLE
datepicker: inside md-list with class="md-2-line"

### ISSUE THREAD

**Issue by Helvio88** [angular/material#10262]
**Actual Behavior**:
 -  `What is the issue? *` Having a `md-datepicker` with a `md-input-container` as a wrapper offsets the `md-list-item-text` texts
 -  `What is the expected behavior?` the `md-list-item-text` texts should still be aligned with the avatar

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/helvio/pen/WRGWYZ
 -  `Details:` Comment out (or delete) the HTML section to see the difference

**Angular Versions**: *
 -  `Angular Version:` 1.6.1
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This caused by two factors
- The calendar button is `40px` height and `8px` of top/bottom padding.
- The `.md-errors-spacer` has a `min-height: 24px`

You can solve the first with `md-hide-icons="calendar"` and the second with
```css
md-input-container .md-errors-spacer {
  min-height: 0;
}
```
Working example [here](https://codepen.io/Splaktar/pen/mdeZJyv).
