### ISSUE TITLE
tabs: md-on-select should have an option to run asynchronously 

### ISSUE THREAD

**Issue by achadee** [angular/material#10269]
Synchronous md-on-select causes the animation to lag or not work on long running tasks such as querying the server each time a tab has changed

**Comment by Splaktar** [comment]
Expressions bound to the template should not include long running tasks, especially those that query the server.

You should make those operations asynchronous by calling them from a function passed to [`$timeout()`](https://docs.angularjs.org/api/ng/service/$timeout).
