### ISSUE TITLE
menu-bar: unable to close md-menu

### ISSUE THREAD

**Issue by jiffify** [angular/material#10265]
I have a toolbar and I'm using few `md-menu` as a part of `md-menu-bar`. I also have another independent md-menu not part of `md-menu-bar`. 

Now when I hover over `md-menu` to open it (part of `md-menu-bar`) and then click on independent `md-menu`, I cannot close my previously open `md-menu`.

seems similar to #3741 

using 1.1.1

Also, when I removed `md-menu-bar` and kept all my `md-menu` independent, everything worked as expected.

**Comment by thorvx** [comment]
same problem

**Comment by Splaktar** [comment]
Follow on work to #3741 is being handled in https://github.com/angular/material/issues/11481. Since this issue has no CodePen/Plunker reproduction, I'm going to close it.
