### ISSUE TITLE
md-select (option popup)  on top of the page. how to fix it?

### ISSUE THREAD

**Issue by manoz2000** [angular/material#10277]
![md-select](https://cloud.githubusercontent.com/assets/10231649/22099739/8f5cb220-de52-11e6-9973-8791502397b4.png)

# Angular material version  * v1.1.1
## #Angular version AngularJS v1.6.1

`                    <md-select ng-model="weapon" placeholder="Weapon">
          <md-option value="axe">Axe</md-option>
          <md-option value="sword">Sword</md-option>
          <md-option value="wand">Wand</md-option>
          <md-option value="pen">Pen?</md-option>
        </md-select>`

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue and sorry for the long delay in responding. The issue does not follow our required issue template. The CodePen demo is not optional.

If this is still a problem and it is not already covered by an existing open issue, please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
