### ISSUE TITLE
toolbar: md-background class does not theme toolbar as expected

### ISSUE THREAD

**Issue by jiffify** [angular/material#10275]
I'm sure that I'm making some mistake somewhere, but cannot put my finger on it. 

For <md-toolbar> all default themes work

class="md-primary"  works
class="md-accent" works
class="md-warn" works
class="md-background" does not work 

http://codepen.io/anon/pen/wggeoE

**Comment by Splaktar** [comment]
I [updated the CodePen](https://codepen.io/Splaktar/pen/pojEQMR?editors=1010) to be a little more clear. However, you can see in the [theming docs](https://material.angularjs.org/latest/Theming/02_declarative_syntax) that we don't support `md-background` as a theme class.
