### ISSUE TITLE
Layout options page is thoroughly broken in IE11

### ISSUE THREAD

**Issue by altufaltu** [angular/material#1028]
Layout options page (https://material.angularjs.org/#/layout/options) is thoroughly broken in IE11.
Can reveal many issues.

![IE11 screenshot showing overlap](https://cloud.githubusercontent.com/assets/1045233/5573843/910bf37e-8f67-11e4-903a-d7f42ceea697.png)

**Comment by rschmukler** [comment]
This seems to be working now. Closing
