### ISSUE TITLE
md-datepicker does not display calendar until scrolling is done

### ISSUE THREAD

**Issue by Grunmir** [angular/material#10280]
**Actual Behavior**:
 -  `What is the issue? *`

      I have a project where I installed angular-material: 1.1.1 with bower, when using <md-datepicker> the calendar is not displayed until I do scroll.

      I have tried installing angular-material: master with bower and if it works.

      My question is, what should I use in my bower.json?
   
      Regards, thank you.

 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.6
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` chrome, safari
 -  `Browser Version: *`  55.0.2883.95 (64-bit), 10.0.2
 -  `OS: *` macOS
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by parikshit999** [comment]
I had same problem, check out this link, second answer works as well
http://stackoverflow.com/questions/41384085/md-datepicker-not-rendering-calendar-correctly

**Comment by Grunmir** [comment]
Ok, it works correctly as stated in stackoverflow.

angular.module('App', []).config(function($compileProvider) {
    $compileProvider.preAssignBindingsEnabled(true);
});

Thank you

**Comment by ThomasBurleson** [comment]
@see https://github.com/angular/angular.js/blob/master/src/ng/compile.js#L1375-L1402

```js
  /**
   * @ngdoc method
   * @name  $compileProvider#preAssignBindingsEnabled
   *
   * @param {boolean=} enabled update the preAssignBindingsEnabled state if provided, otherwise just return the
   * current preAssignBindingsEnabled state
   * @returns {*} current value if used as getter or itself (chaining) if used as setter
   *
   * @kind function
   *
   * @description
   * Call this method to enable/disable whether directive controllers are assigned bindings before
   * calling the controller's constructor.
   * If enabled (true), the compiler assigns the value of each of the bindings to the
   * properties of the controller object before the constructor of this object is called.
   *
   * If disabled (false), the compiler calls the constructor first before assigning bindings.
   *
   * The default value is true in AngularJS 1.5.x but will switch to false in AngularJS 1.6.x.
   */
  var preAssignBindingsEnabled = false;
  this.preAssignBindingsEnabled = function(enabled) {
    if (isDefined(enabled)) {
      preAssignBindingsEnabled = enabled;
      return this;
    }
    return preAssignBindingsEnabled;
  };
```

**Comment by ThomasBurleson** [comment]
Refs https://github.com/angular/material/issues/10016

**Comment by gkalpak** [comment]
It seems to have [work as expected][1] with 1.1.3.

[1]: http://codepen.io/ExpertSystem/pen/NpLyLw

**Comment by mgol** [comment]
Yes, it's been broken in 1.1.1 but it's been working fine since 1.1.2. I think this issue can be closed now.

**Comment by ThomasBurleson** [comment]
Closing as fixed.
