### ISSUE TITLE
input-container label blurry

### ISSUE THREAD

**Issue by whittssg** [angular/material#10293]
Anyone know how to fix the blurring that seems to occur on the md-input-container when its focused (when the label moves to the top). The text seems super blurry and i can fix it using this css but it also effects the labels that havent been pushed to the top:

`md-input-container >label {
    transform: skew(0deg, 0deg) !important;
    -webkit-transform: skew(0eg, 0deg) !important;
}`

![image](https://cloud.githubusercontent.com/assets/6453857/22222881/a146f068-e186-11e6-8896-02f44d27b65c.png)

I cant figure out how to just target the label that is raised... 

FYI the text is this small because i set everything to 12px  (fonts) alot of people where i work seem to set their windows text size to 125% so everything was way to big). Also the text looks fine in IE.. not in chrome or firefox

**Comment by whittssg** [comment]
Never mind... this css seemed to do the trick:

.md-input-has-value label {
    transform: skew(0deg, 0deg) !important;
    -webkit-transform: skew(0eg, 0deg) !important;
}

.md-input-focused label {
    transform: skew(0deg, 0deg) !important;
    -webkit-transform: skew(0eg, 0deg) !important;
}

**Comment by elmeerr** [comment]
I know that you close but this doesn't solved the problem properly...I'm facing the same but only on Chrome...have you manage to solve or are still using this workaround?

**Comment by dinumarathe** [comment]
> I know that you close but this doesn't solved the problem properly...I'm facing the same but only on Chrome...have you manage to solve or are still using this workaround?

Yes I am also still facing this issue...😒

**Comment by Splaktar** [comment]
@dinumarathe please open a new issue that follows the issue template and provides a CodePen reproduction.

**Comment by dinumarathe** [comment]
okay.
