### ISSUE TITLE
dynamic heights with md-grid-list

### ISSUE THREAD

**Issue by durga-telsiz** [angular/material#10297]
How do i achieve following dynamic heights with md-grid-list. 
In my case First row has four widgets, all 4 should have fixed height. Second row has only one widget that occupies full width and full remaining height(100% - 200px)

<md-grid-list md-cols="4" md-row-height="fit" md-gutter="8px">

      <md-grid-tile md-colspan="1">hi</md-grid-tile> //Fixed height 200px

      <md-grid-tile>hi</md-grid-tile> //Fixed height 200px

      <md-grid-tile>hi</md-grid-tile> //Fixed height 200px

      <md-grid-tile>hi</md-grid-tile> //Fixed height 200px

      <md-grid-tile md-colspan="4">hi</md-grid-tile> //Need (100% - 200px) height based on screen size
</md-grid-list>

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
