### ISSUE TITLE
md-datepicker not showing any dates in angular material 1.1.1

### ISSUE THREAD

**Issue by ErikVanDenHoorn** [angular/material#10299]
I am using Angular version 1.6.1 together with Angular material version 1.1.1. When I open the datepicker I dont see any dates. Only the grey bar with the first letter of the day of the week is visible. After rolling back to Angular material version 1.1.0 the dates are being display correctly again.

**Comment by BenEfrati** [comment]
Hi,
Same as https://github.com/angular/material/issues/10280

Solution:
http://stackoverflow.com/questions/41384085/md-datepicker-not-rendering-calendar-correctly

TL;DR:
add this to your config

```
angular.module('App', []).config(function($compileProvider) {
    $compileProvider.preAssignBindingsEnabled(true);
});
```

**Comment by ErikVanDenHoorn** [comment]
Hi Ben,

Thanks that solved the issue.

**Comment by parzibyte** [comment]
Thank you. It works! does somebody know why this happens?
