### ISSUE TITLE
md-slider not working in chrome on windows touch devices

### ISSUE THREAD

**Issue by AxxlForce** [angular/material#10294]
**Actual Behavior**

Drag of slider is not working properly only click is working. The slider can be dragged for a short time but is lost after a few pixels. When the slider is configured as discrete the slider always jumps to the beginning when dragged. Might be related to #10187

**CodePen (or steps to reproduce the issue)**

Open the demo link of angular material in Chrome 55 on a windows touch device (e.g. Surface, WinPad etc.)
https://material.angularjs.org/latest/demo/slider

**Angular Versions**

Angular Version: 1.5.8
Angular Material Version: 1.1.1

**Additional Information**

Browser Type: Chrome
Browser Version: 55.0.2883.87 m
OS: Windows 8 & 10 (on touch device)

**Comment by mustaqahmed** [comment]
Edge is also affected by this Angular bug, [here](https://github.com/angular/material/issues/10187#issuecomment-275240212) is a solution.
