### ISSUE TITLE
Touch does not place cursor on input fields on Android

### ISSUE THREAD

**Issue by vbraun** [angular/material#10301]
**Actual Behavior**:
 -  `What is the issue? *`

Touch on input field does not place the cursor at different text positions on Android phone 

 -  `What is the expected behavior?`

When there is a input field with text, the cursor should be placed at the touch location.

**CodePen** (or steps to reproduce the issue): *

1. Open the input demos (https://material.angularjs.org/latest/demo/input) on an Android phone. 
2. Enter some text in an input field. 
3. Touching different positions in the entered text does not place the cursor.

You can move the cursor by dragging the blue cursor location icon, but the cursor cannot be placed by touch events inside the text. 

With $mdGestureProvider.skipClickHijack() this also works, i.e., touch events change the cursor location.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Mobile chrome
 -  `Browser Version: *` Android
 -  `OS: *` 7

Related tickets:
* #10058 references ionic, but the issue is independent of ionic.
* #9333 was imho wrongly closed; The issue is on Android but it was closed because iOS behavior is different.
* #8829 same issue reported for mobile firefox, comment says it also happens on mobile chrome

**Comment by dkirsanov** [comment]
Any progress here, guys? I have the same issue.

**Comment by loggerq** [comment]
Good to see this is a known issue and others have run into it.   It is a pretty impactful bug for a special p2p web app we're trying to launch.

**Comment by uapixart** [comment]
I have the same issue.

**Comment by niroussel** [comment]
Same problem here, reproduced with chrome developper console.

1. Go to https://material.angularjs.org/latest/demo/input
2. Activate the "mobile" view of chrome developper console
3. Refresh (Ctrl + F5)

This is really impactful.

**Comment by PhMetzger** [comment]
Agreed, this is really impactful.

This is the kind of issue which make an entire app down. It's probably something with focus events...
I understand the effort to move to angular 4, but leaving the communauty which such an issue don't encourage to move to angular 4...

**Comment by simentesempre** [comment]
Any progress on this one? This is a blocking issue. Unfortunately this makes the whole framework useless because this is a major issue that makes any app unusable. Is there at least a workaround?
Thank you very much.

**Comment by jelbourn** [comment]
Also reported by at least one Google team

**Comment by gelordi** [comment]
This problem still happening on mobile

**Comment by vbraun** [comment]
Its fixed for me; Do you have the right version?

**Comment by gelordi** [comment]
yes, i have 1.1.5 and it doesn't work on chrome/mobile

**Comment by gelordi** [comment]
Can you guys check this problem?

**Comment by Splaktar** [comment]
@gelordi please open a new issue with a CodePen reproduction.
