### ISSUE TITLE
elements are not properly hidden at certain resolution

### ISSUE THREAD

**Issue by Liron-K** [angular/material#10303]
**Actual Behavior**:
 -  `What is the issue? *`
Elements that are marked with show or hide do not hide as expected. This happens exactly at the point between sm and md.
 -  `What is the expected behavior?`
Only one of the elements should be shown at a time.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/anon/pen/RKZMqa
 -  `Details:`
![codepen](https://cloud.githubusercontent.com/assets/2301443/22291104/4877549a-e30d-11e6-8475-32073c40a256.PNG)

**Angular Versions**: *
 -  `Angular Version:`
1.5.5
 -  `Angular Material Version:`
1.1.1

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
55.0.2883.87 m (64-bit)
 -  `OS: *`
Windows 10 Version 1607

- 'Repeatability':
I am not able to replicate this on OSX in either chrome or firefox. 

 -  `Stack Traces:`
N/A
----

**Comment by Liron-K** [comment]
Has anyone had a chance to look into this?

**Comment by Splaktar** [comment]
I am also not able to replicate this on macOS. 

I tried on Windows 10 (v1511) with IE11 and Edge and also could not reproduce the issue there. 

Finally I installed Chrome 63 on Windows 10 (v1511) and I was unable to reproduce this with your CodePen either with the Browser or with the mobile emulator in DevTools.

If this is still an issue for you, please provide additional information that can help with the reproduction.
