### ISSUE TITLE
Branding consistency fixup

### ISSUE THREAD

**Issue by IgorMinar** [angular/material#10304]
Please search (case insensitive) and replace within md files in this repo as follows:

`angular (1\.\d)` -> `AngularJS $1`
`angular 1\.x` -> `AngularJS`
`angular 1` -> `AngularJS`
`angular1` -> `AngularJS`

`angular 2\.0` -> `Angular`
`angular 2` -> `Angular`
`angular 2\.x` -> `Angular`
`angular2` -> `Angular`

**Comment by IgorMinar** [comment]
Please also reflect these changes on material.angular.io. Thanks!

**Comment by jelbourn** [comment]
@EladBezalel can you tackle this? Igor wants it done yesterday :smiling_imp:
