### ISSUE TITLE
button: layout is rendered incorrectly in Safari and Firefox

### ISSUE THREAD

**Issue by chanturia** [angular/material#10302]
**Actual Behavior**:
 -  `What is the issue?
the layout of a button is rendered incorrectly in safari and  firefox (the funny fact is that IE 11 renders it correctly),  at this moment the layout of a button is the code below: 

```
<md-button class="md-raised" layout="row" layout-align="center center">                     
                        <div layout="row" layout-align="space-around center" flex-gt-xs="60">
                            <i class="fa fa-facebook-official"></i>
                            <span layout-margin></span>
                            <span>Log-in with Facebook</span>
                        </div>
</md-button>
```
but when i change the layout of md-button to column the safari and firfox render them corectly but this action brakes the lay out of IE 11

does anyone know the solution to this problem? or it is a bag of angular material

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue: http://codepen.io/chanturia/pen/ggxoqK

**Angular Versions**: *
 -  `Angular Version: 1.5.5
 -  `Angular Material Version: 1.1.1

----

**Comment by chanturia** [comment]
Has no one any **solution** yet?

**Comment by Splaktar** [comment]
I don't currently see any difference between how Chrome, Firefox, or Safari render the CodePen example provided. What is the expected outcome? What is the problem? It's not clear to me.
