### ISSUE TITLE
list: list-item height doesn't meet Material Design specs

### ISSUE THREAD

**Issue by kybarg** [angular/material#10310]
**Actual Behavior**:
 -  `What is the issue? *` List items are 52px height
 -  `What is the expected behavior?`  Only text or icon list item should be 48px height according to specs https://material.io/archive/guidelines/components/lists.html#lists-specs

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/latest/demo/list
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.6.1
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55
 -  `OS: *` Windows 10
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
On our demo page, I observed the following heights:
- single line list item: `48px`
- avatar list item: `56px`
- two line list item: `72px`
- three line list item: `88px`

These all align with the specs. I am not able to find any `52px` height list items on the docs (for either 1.1.1 or 1.1.21) and a demo was not provided with this issue, so I'm not able to reproduce this problem.
