### ISSUE TITLE
when using an md-autocomplete with a custom template and md-not-found, a not found results breaks clicking anywhere on a non-input on mobile

### ISSUE THREAD

**Issue by darudude** [angular/material#10312]
**Actual Behavior**:
 -  `What is the issue?` When using an md-autocomplete with a custom template and md-not-found, a not found results breaks clicking anywhere on a non-input on mobile
 -  `What is the expected behavior?` I should be able to click away from the message, or on a link on the page, and I'd expect it to fire

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/zNEaJw
 -  `Details:` Load the page up in chrome. In dev tools view as iPhone 6. Enter some garbage into the input till you the get the not-found message. Try clicking anywhere else on the body. The not found message doesn't dismiss as expected

**Angular Versions**: *
 -  `Angular Version:` 1.5.9
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Latest stable
 -  `OS: *` Windows 10 (though seeing this on Android phones as well)
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This was fixed at some point between 1.1.1 and 1.1.7. [CodePen](https://codepen.io/Splaktar/pen/aqPvBy) showing it working in 1.1.7.
