### ISSUE TITLE
Angular ng-click issue with mac safari browser.

### ISSUE THREAD

**Issue by anilpallikonda4** [angular/material#10327]
Hi All,

Angular click event not working with mac safari browser.
Please find below link and help someone on this.

http://plnkr.co/edit/QNKZDT9N5k2tQaRrFlwY?p=preview

**Comment by graphefruit** [comment]
This is not an angular-material issue, you're referencing a plain angular.js instance.
Also you're using angular 1.0.3, update to the latest 1.5.X or 1.6.X and have a look if its working then.

**Comment by anilpallikonda4** [comment]
Hi @graphefruit 

 Thanks for your quick update,but  in my machine that code I am checking with angular 1.5 version.
I observed mac safari not able to append these ng-click events.
Any help now?

**Comment by graphefruit** [comment]
After your description it looks like an angular issue, not an angular-material issue.
Also it would be interesting which safari version you're using.
Ng-Click has the problem on iOS-Devices that you sometimes need to click twice, because the first click triggers the hover and the second executes the click event.

**Comment by anilpallikonda4** [comment]
Hi @graphefruit 

Thanks for your update.
Currently I am using Safari 9.1.3 version.
Ng-Click not working for several clicks also. Its not triggering at all.

**Comment by graphefruit** [comment]
Try:
- to bind a click event via javascript/jquery, 
- try another element - is ng-click working here?
- try to write a custom directive for ng-click
- have a look in console if error occures
- try other versions of angular.js

And else please open a new issue on https://github.com/angular/angular.js here you can get a more appropriate help.
Greetings

**Comment by anilpallikonda4** [comment]
@graphefruit 
Thank You somuch

**Comment by topherfangio** [comment]
Closing as not material. Please comment if I'm incorrect.

**Comment by graphefruit** [comment]
@topherfangio Its an material problem because of the CSS which is causing first the hovering and then the click is executed. Thats why you need to overwrite and add your own ng-click event.
Don't know - you're using the angular.js ng-click or your're overwriting with your own?

**Comment by topherfangio** [comment]
@graphefruit You have a Codepen?
