### ISSUE TITLE
datepicker: showing invalid date

### ISSUE THREAD

**Issue by gokulanbu26** [angular/material#10326]
![invalid date](https://cloud.githubusercontent.com/assets/23076162/22418000/03be8884-e6fd-11e6-92d4-6f7c388463e2.png)

**Comment by sdesmond** [comment]
If you want this issue looked at, please re-submit it and fill out the issue template.  The screenshot doesn't really show any issue without some explanation.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
