### ISSUE TITLE
md-autocomplete and $mdDialog rendering issues

### ISSUE THREAD

**Issue by ghost** [angular/material#10322]
**Actual Behavior**:
 -  `What is the issue? 
 **- md-autocomplete and $mdDialog rendering issues*`**
 -  `What is the expected behavior?
**-Remove white background from page footer and mdDialog follow center of screen when scrolling page`**

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version: v1.5.9`
 -  `Angular Material Version: v1.1.1`

**Additional Information**:
 -  `Browser Type: Chrome*`
 -  `Browser Version: 55.0.2883.87 m (64-bit)*`
 -  `OS: Windows 10
![ngmaterialissue1](https://cloud.githubusercontent.com/assets/22476009/22396684/cc3ea496-e546-11e6-892a-22285941b211.png)
![ngmaterialissue2](https://cloud.githubusercontent.com/assets/22476009/22396687/d9f3f122-e546-11e6-9800-5b7a0eda76b3.png)

*`
 -  `Stack Traces:` **The errors always fire after scrolling the page, I've already changed the md-backdrop to fixed md-dialog-is-showing to visible but the problem persists.
If you can help me. I thank you**

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. We need a CodePen demo in order to debug and investigate this issue.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
