### ISSUE TITLE
select: focus on separate text input after selecting option is not working 

### ISSUE THREAD

**Issue by srjahir32** [angular/material#10323]
Apparently it looks like bug and on stackoverflow people also considering this as bug. 
When I try to focus on input type text after selecting option from select type, focus is give for micro second and again given back to select box.

Here is jsFiddle.
https://jsfiddle.net/7gx1u96L/4/

StackOverflow link
http://stackoverflow.com/questions/41895023/focus-on-input-text-after-selecting-option-from-selectbox-in-angularjs?noredirect=1#comment71004584_41895023

**Comment by Splaktar** [comment]
`md-select` has its own focus management that returns the focus to the `md-select` after the options panel is closed. You will need to wait until after that is done if you want to programmatically move the focus. We don't provide an `on-selection-done` or similar API for this, but you can use something like `$mdUtil.nextTick` or `$timeout` for move the focus after `md-select`'s focus management has finished running.

https://jsfiddle.net/s1o3jexq/
