### ISSUE TITLE
nav-bar: should scroll on mobile devices

### ISSUE THREAD

**Issue by smuellerus** [angular/material#10336]
**Actual Behavior**:
 -  `What is the issue? *` On mobile devices, md-nav-bar does not scroll horizontally, so the nav bar content is cut off and cannot be accessed on screens with smaller widths.
 -  `What is the expected behavior?` The md-nav-bar should scroll when tapping and holding.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Not needed.
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.9
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55.0.2883.87
 -  `OS: *` Ubuntu 16.04
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
This can be reproduced on the [demo page](https://material.angularjs.org/latest/demo/navBar).

However, in cases where you have embedded content you should use `md-tabs` and in cases where you need to have navigation items, you should probably use the [Transform pattern](https://material.io/archive/guidelines/layout/responsive-ui.html#responsive-ui-patterns) on mobile to move the navigation to a sidenav or a top nav with a menu overflow.

It would be nice if `md-nav-bar` could be tweaked to support something like [bottom navigation](https://material.io/components/bottom-navigation#), however that's not something that's in scope for AngularJS Material. Angular Material may eventually have a component that does this, but it's likely quite a ways out (no ETA).
