### ISSUE TITLE
navbar: can't move right/left with keyboard arrows on Firefox and IE11 and screen reader indication like in Chrome (for example: TabName 1 of 3)

### ISSUE THREAD

**Issue by frkfir** [angular/material#10333]
**Actual Behavior**:
 -  `What is the issue? *You can't move right or left  with the keybords arrows and no text indication like in Chrome (for example: TabName 1 of 3)
 -  `What is the expected behavior? You can move right or left with keybords arrows, and you should see with screen reader the text indication like - TabName 1 of 3.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version: 1.5.5
 -  `Angular Material Version: 1.1.3

**Additional Information**:
 -  `Browser Type: *Firefox and Explorer
 -  `Browser Version: *` Firefox: version 51.0.1, Explorer version 11.0.9600.18537CO
 -  `OS: * Windows 7
 -  `Stack Traces: n/a

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This was fixed by PR https://github.com/angular/material/pull/11494 in `1.1.11`. You can verify it here: https://material.angularjs.org/1.1.11/demo/navBar.

If you see additional a11y issues with the navBar, please open a new issue.
