### ISSUE TITLE
theming: add ability to specify hues as options to defineTheme

### ISSUE THREAD

**Issue by chenav** [angular/material#10335]
**Actual Behavior**:
 -  `What is the issue? *`

When using defineTheme to generate theme on the fly, we can only indicate the "name" of a palette. It is not possible to inject hues options, as we could do it before with : 
` $mdThemingProvider.theme(name).primaryPalette(palettes.primaryPalette.name, {
                'default': palettes.primaryPalette.main,
                'hue-1': palettes.primaryPalette.hue1,
                'hue-2': palettes.primaryPalette.hue2,
                'hue-3': palettes.primaryPalette.hue3
            })`
We are stuck now with the default hues, if we use defineTheme.
As a conclusion, today, we have to stick to the provider methods.

 -  `What is the expected behavior?`
We should be able to pass a whole set of palette options containing name & hues, in order to dynamically set the hues of the relevant palette.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
No code pen would show anything. The present signature of defineTheme only takes: 
`defineTheme(themeName, paletteName) `   (String, String)
A different signature could be: 
`defineTheme(themeName, paletteOptions)` (String, Objet)
paletteOptions could be an object like this:
`{
'name': 'paletteName',
'options': {
                'default': '500',
                'hue-1': '100',
                'hue-2':'200',
                'hue-3': '800'
            }
}`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.11
 -  `Angular Material Version:` 1.1.2 & 1.1.3

**Additional Information**:
 -  `Browser Type: *`    All
 -  `Browser Version: *` All
 -  `OS: *` All
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This actually looks pretty straight forward. We already have internal support for doing this. We just don't allow for these options to be specified in the API and then passed in.

You can see the options coming in [here](https://github.com/angular/material/blob/v1.1.10/src/core/services/theming/theming.js#L705-L729).

Then you can see [here](https://github.com/angular/material/blob/v1.1.10/src/core/services/theming/theming.js#L528-L568) that these `xPalette()` functions take both a `paletteName` and `hues`.

The docs [here](https://github.com/angular/material/blob/v1.1.10/src/core/services/theming/theming.js#L660-L675) would also need to be updated.
