### ISSUE TITLE
IE11 rendering and performance issue

### ISSUE THREAD

**Issue by GeorgianSorinMaxim** [angular/material#10334]
Hi, 

I have an issue with angular-material in IE 11. Pretty much all elements are unusable, they are rendered weirdly, the performance is very bad, the page elements being very slow. The app works fine on Chrome, Safari, Opera, Firefox on Windows, Linux and macOS. I tried mainly some CSS suggestions found in other issues, but nothing worked so far.

Here's how a simple page looks in Chrome:
<img width="558" alt="screen shot 2017-01-31 at 10 36 54" src="https://cloud.githubusercontent.com/assets/6978480/22461627/e89ceb18-e7a1-11e6-8aa8-3f1448b9eadf.png">

Here's the same page in IE 11:
<img width="552" alt="screen shot 2017-01-31 at 10 37 05" src="https://cloud.githubusercontent.com/assets/6978480/22461631/ee922074-e7a1-11e6-9cd6-66638a32d152.png">

**Project details**: *
 -  `Stack:`Meteor App
 -  `Angular Version:`1.5.8
 -  `Angular Material Version:` 1.1.1

**Issue seen when running**:
 -  `Browser Type:` Internet Explorer 11
 -  `Browser Version:` 11.0.9600.17843
 -  `OS:` Windows 7

Any ideas?
Thank you

**Comment by mckenzielong** [comment]
is IE11 running in compatibility mode?

**Comment by GeorgianSorinMaxim** [comment]
No, happens on normal mode. Also it's not machine dependent.

**Comment by GeorgianSorinMaxim** [comment]
Anyone having a guess? Is it be possible that the bug is caused by package incompatibilities?

**Comment by GeorgianSorinMaxim** [comment]
@mckenzielong Apparently, this issue was because I was **not** running in Compatiblity mode. As soon as I added the URL in the 'Compatibility View' list, the site was rendering normally.
