### ISSUE TITLE
button: disable doesn't work when using ng-click or ng-href on it

### ISSUE THREAD

**Issue by molikh** [angular/material#10332]
`md-button` disable doesn't work when use `ng-click` `ng-href` on it.

http://codepen.io/anon/pen/YNePKB
add this to `md-button` on the link which ones is disabled 
```html
ng-click="hi()" ng-href="1"
```
and this to js file  
```js
 $scope.hi = function () {
   alert("hi")
 }
```

you will see disabled `md-button` will trigger the `hi()` function

**Comment by molikh** [comment]
no idea?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. It's not clear which browser you were seeing this behavior on.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

I can't reproduce this issue on Chrome 83 using `1.1.3` or an [updated CodePen](https://codepen.io/Splaktar/pen/dyGbMWd?editors=1010) for `1.1.22`.
