### ISSUE TITLE
Latest version published to npm, 1.1.2-master-b2562cg, fails on npm install.

### ISSUE THREAD

**Issue by kid-icarus** [angular/material#10331]
**Actual Behavior**:
 -  `What is the issue? *`

  `npm install angular-material` fails with the latest version published a few hours ago.
   (npm outdated is listing the version as `1.1.2-master-b2562cf`)

 -  `What is the expected behavior?` The module is installed

**CodePen** (or steps to reproduce the issue): 

 1. `npm install angular-material`
 2. There is no step 2, it just fails.

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:` 1.1.2-master-b2562cg

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:

FWIW, using node 6.9.1, npm 3.10.8

**Comment by kid-icarus** [comment]
For anyone else experiencing this, locking the version down to 1.1.1 resolves the issue until this is fixed.

**Comment by johnvarv** [comment]
Some here. It seems that npm requests the targz of the 1.1.2 version but then for some reason tries to install 1.1.1 and so it tries to find the 1.1.1 targz
```
npm ERR! Linux 4.4.0-47-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm v4.0.5
npm ERR! code EREADFILE

npm ERR! Error extracting /root/.npm/angular-material/1.1.1/package.tgz archive: ENOENT: no such file or directory, open '/root/.npm/angular-material/1.1.1/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by vbraun** [comment]
Version 1.1.3 now installs from npm for me

**Comment by johnvarv** [comment]
Yes, it installs 1.1.3 properly now and as I noticed on npm latest version is `1.1.3` instead of `1.1.2-master-b2562cf`.

**Comment by kid-icarus** [comment]
Confirming that version 1.1.3 now installs. Thanks for the feedback, y'all.
