### ISSUE TITLE
md-autocomplete 'required' validation broken in 1.1.3

### ISSUE THREAD

**Issue by Karasuni** [angular/material#10346]
In 1.1.3 md-autocomplete does not work using 'md-required' or 'required' tags. This is inconsistent with other elements and the documentation.

See https://github.com/angular/material/issues/6393#issuecomment-270139045 and #6393

**Comment by Splaktar** [comment]
[The demo](https://material.angularjs.org/latest/demo/autocomplete#floating-label) shows this working in 1.1.7.
