### ISSUE TITLE
chips: regression to component focus in 1.1.2

### ISSUE THREAD

**Issue by sivakrrish1994** [angular/material#10344]
**Actual Behavior**:
 -  `md-chips focus is being applied only inside md-chip-input-container`
 -  `Focus should be there through out the md-chips`

**Angular Versions**: *
 -  `Angular Material Version:1.1.3`

**Comment by cmacdonnacha** [comment]
How are you setting focus to it?

**Comment by sivakrrish1994** [comment]
@cmacdonnacha Still I have not done. Concerned party has to fix the code. Previously in angular material version: 1.1.1 it was working fine while in v1.1.3, they might have missed to add md-focused on md-chips-wrap when a click is made on it.

v1.1.1: https://material.angularjs.org/1.1.1/demo/chips
v1.1.3: https://material.angularjs.org/latest/demo/chips

**Comment by cmacdonnacha** [comment]
@sivakrrish1994 I ran into a similar issue. Trying having a look at my last comment on this [issue](https://github.com/angular/material/issues/10355):

**Comment by tyrdavis** [comment]
Seeing the same thing. To clarify on the issue, if you click on the far right of the chips component (a part of it that doesn't have the chip-input-container directly under your click) in the 1.1.1 docs, the chip-input-container will be focused, while the same action in 1.1.13 docs does nothing.

**Comment by sivakrrish1994** [comment]
ya @cmacdonnacha that's one of the option but literally this functionality needs to be implemented by the material team.
Let us wait for the material team to fix this issue @cmacdonnacha  @tyrdavis

**Comment by rajathms** [comment]
+1 for this feature 

Till then any workaround would be appreciated.

**Comment by jpike88** [comment]
This is a serious usability bug... how is this being overlooked? +1

**Comment by matteomartinelli** [comment]
Same here, 👍

**Comment by jpike88** [comment]
Sorry @matteomartinelli, it’s time to fork it. They stopped development on it ages ago. But it’s worth using!

**Comment by dhwang-xactly** [comment]
What's the difference between 1.1.1 and 1.1.3+? In addition the the click on right side not triggering the focus, you will also notice that the placeholder text is truncated because default input box is not wide enough to show the full placeholder text.

**Comment by dhwang-xactly** [comment]
Workaround CSS using flex layout.

.md-chips {
  display: flex;
  flex-flow: row wrap;
  border: 1px solid #ccc;
  padding: 4px;
  font-family: Verdana, Arial, sans-serif;
  font-size: 11px;
  box-shadow: none;
}
/* make input box full width of md-chips */
 .md-chip-input-container {
  flex: 1 1 auto;
}

**Comment by Splaktar** [comment]
Verified that this was introduced in 1.1.2. Will have a PR up for this soon. It takes a better approach than #11082.

**Comment by Splaktar** [comment]
The PR ran into some presubmit failures on internal Google tests. I will see about trying to get it into 1.1.8.

**Comment by jpike88** [comment]
wouldnt hold my breath. It’s time to fork!

**Comment by beazergood** [comment]
🤦
