### ISSUE TITLE
md-switch button overlaps the list subheader

### ISSUE THREAD

**Issue by juristr** [angular/material#1034]
When using the default team with the latest `master` version, it seems as if the `md-switch` button goes over a list subheader `md-subheader` when scrolling.

![image](https://cloud.githubusercontent.com/assets/542458/5526671/65c72fb0-89f6-11e4-8f55-82e1d331498b.png)

![image](https://cloud.githubusercontent.com/assets/542458/5526677/75f6be32-89f6-11e4-9054-b0df2919f523.png)

It's the `md-thumb` to be precise.

**Comment by ThomasBurleson** [comment]
@robertmesserle  - z-index issue?

**Comment by mahesh-ziffi** [comment]
How we have to solve this type of issue ? Any idea ?

**Comment by DevVersion** [comment]
@mahesh-ziffi If you still can reproduce that issue, please file a new one and ping me on that.
