### ISSUE TITLE
White background for disabled chips with autocomplete

### ISSUE THREAD

**Issue by viktarkorshun** [angular/material#10343]
**Actual Behavior**:
 -  If you have custom theme and disabled chips widget with autocomplete the autocomplete element's background is white instead of transparent.
 -  Background needs to be transparent, like it is without theme applied.

**CodePen** (or steps to reproduce the issue): *
 -  http://codepen.io/anon/pen/RKQyZX
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version: 1.5.5`
 -  `Angular Material Version: v1.1.3-master-f887652`

**Additional Information**:
 -  `Browser Type: Chrome 56.0.2924`
 -  `OS: Linux`

**Comment by Splaktar** [comment]
I am unable to get this demo to work at all. The autocomplete popup never appears and the autocomplete doesn't seem to be focusable. Please fix the demo if this is still an issue.
