### ISSUE TITLE
Wrong behaviour of border radius on mdDialog

### ISSUE THREAD

**Issue by Venthe** [angular/material#10340]
**Actual Behavior**:
 -  `What is the issue? Rounded header will leave background showing`
 -  `What is the expected behavior? For the background to not show itself`

**CodePen** (or steps to reproduce the issue): *
 -  `Details: It can be seen on your demo site: https://material.angularjs.org/latest/demo/dialog with custom dialog. Open modal and fiddle with window size`
![capture](https://cloud.githubusercontent.com/assets/1686874/22472667/9edca1aa-e7d6-11e6-99f0-564599c94577.JPG)

**Angular Versions**: *
 -  `Angular Version: 1.5.5 (Your demo) and 1.5.8`
 -  `Angular Material Version: lastest as of 31.01.2017`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 55`
 -  `OS: Win 10 Anniversary`

**Comment by sdesmond** [comment]
I had seen this too.  It seems to happen when there was a dialog that was resized after loading.  So I had a dialog that loaded, then the errors messages showed and bumped up the width causing the title thing.

Checking the 1.1.3 docs (https://material.angularjs.org/latest/demo/dialog) I'm not seeing the issue anymore (Chrome).  Maybe it's been resolved?

**Comment by Venthe** [comment]
Seems working as for now
