### ISSUE TITLE
nav-bar: anchor created by md-nav-sref does not inherit aria-label attribute

### ISSUE THREAD

**Issue by alanpurple** [angular/material#10350]
there is no way I can get rid of aria-label warning when I use like this

```
<md-nav-item md-nav-sref="home" name="home" aria-label="home button">
            <md-icon md-svg-icon="home"></md-icon>
</md-nav-item>
```

**Comment by Splaktar** [comment]
Fixed in `1.1.11` by PR https://github.com/angular/material/pull/11486.

[CodePen Demo](https://codepen.io/Splaktar/pen/QWyLNGe?editors=1010)
