### ISSUE TITLE
ngUpgrade perf issues related to Zones.

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#10368]
A new performance issue with a large scrolling table has been reported. This perf issues manifested after a change in Zone code. The problem shows up within the scroll event, for a page that uses mixed Angular 1 (with ngUpgrade) and Angular 2 components. 

Investigations should consider @petebacondarwin comments:

"At the moment upgrade will not support AngularJS watches that trigger async operations inside their watcher functions. E.g. "

```js
scope.$watch(function watcherFn() {
  setTimeout(doSomethingLater(), 1000);
  return someValueBeingWatched;
}, function handlerFn(newValue) {
  doSomethingWithValue(newValue);
});
```

>  These perf issues manifest using with ngM v1.1.3; but are not present when using ngM v1.1. At a minimum, we should identify what changes from 1.1 -> 1.1.3 affected performance

**Comment by ThomasBurleson** [comment]
@topherfangio, @crisbeto - let's discuss this on Monday.

**Comment by ThomasBurleson** [comment]
See https://github.com/angular/angular/commit/20b454cbc96f9d67bb8ca6e966f2aa0feeb12392 for additional information.

Review MutationObservers as perf impactors: https://github.com/angular/material/commit/65239b71ac5ece40155f1b4895561162ea1ec6d4

**Comment by henrymana** [comment]
Do you know if there is a sample project which uses ngUpgrade with material 1 and 2?

I would love to play with this (with the expectation material 2 is beta and ngUpgrade may not fully work yet). Thank you.

**Comment by Splaktar** [comment]
I believe that this is fixed with ngUpgradeLite in Angular v5+. I have a StackBlitz demo and some additional details in [a forum post](https://groups.google.com/forum/?pli=1#!topic/ngmaterial/9dgqZG2e13o).
