### ISSUE TITLE
layout-gt-(something) not working correctly anymore

### ISSUE THREAD

**Issue by marshfire** [angular/material#10361]
**Actual Behavior**:
 -  `What is the issue? *`
When I design a responsive layout that splits at 2/3 of the width if it is on a device larger than xs and is below on xs, and do this by layout="column" and layout-gt-xs="row" then I do not get the intented behaviour. Instead I get two divs side by side split at 50%.

 -  `What is the expected behavior?`
a 2/3 width split (as in version 1.1.1)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/BpxRQL
 -  `Details:`
As a workaround I can add any resolution itself that should have been covered with layout-gt-(something) but that is not very convenient. I know a quick fix for the pen is to change the default behaviour to row and use layout-xs as column, but the design principle says mobile first as default and exceptions for larger resolutions, not the other way around. Please also note that in the commit of the new flex behaviour the previously used layout-gt-md in the demo has been replaced by many specific calls instead, probably because it did also not work anymore.

previous behaviour (1.1.1): http://codepen.io/anon/pen/Grdmxq

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *`  Chrome, Firefox
 -  `Browser Version: *` current
 -  `OS: *` Ubuntu 16.04 LTS
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by marshfire** [comment]
hmm, I'm beginning to realize that the new behaviour is not necessarily wrong. If I use flex-gt-xs below, then it works. Hmm, I might have been using it wrong.

Would be nice if someone can confirm that, so we can close the issue, though there might be some apps out there living with the same behaviour of the old code.

**Comment by ppham27** [comment]
I had the same issue. I had to change all my flex children to `flex-gt-md` to get the behavior that I would expect.
