### ISSUE TITLE
md-tab error on Safari: 

### ISSUE THREAD

**Issue by eazibizapps** [angular/material#10365]
```
EXCEPTION: Error in ./MdTabGroup class MdTabGroup - inline template:0:0 caused by: 'undefined' is not a function (evaluating 'window.requestAnimationFrame(function () {
                _this._alignInkBarToSelectedTab();
            })')
vendor.bundle.js:46971
ORIGINAL EXCEPTION: 'undefined' is not a function (evaluating 'window.requestAnimationFrame(function () {
                _this._alignInkBarToSelectedTab();
            })')
```

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

In this case, it's important that we have a CodePen reproduction along with the versions of Safari, AngularJS Material, and the OS in use.
