### ISSUE TITLE
calendar: unexpectedly grabbing focus

### ISSUE THREAD

**Issue by decko** [angular/material#10363]
**Actual Behavior**:
 -  `What is the issue? `*
When I use `md-calendar` on a view, it grabs the focus and drags the window to it.
 -  `What is the expected behavior?`
When used alone (outside `mdDatePicker`) it should grab no focus at all.

**CodePen** 
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
"Add a `mdCalendar` to a view and make it outside of window when loaded"

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: 1.1.3`

**Additional Information**:
 -  `Browser Type: Google Chrome*`
 -  `Browser Version:  56.0.2924.76`
 -  `OS: * Fedora 25`
 -  `Stack Traces:`

**Comment by gabrieltaets** [comment]
Almost three years later, this issue is still ignored.
I've tracked down the problem to lines 349 and 356 of the file: https://github.com/angular/material/blob/master/src/components/datepicker/js/calendar.js

We could add a flag (defaulting to true, in order to be non-breaking) whether to focus or not.
When I have some spare time I might make a PR for this.

**Comment by Splaktar** [comment]
We probably need a new API to disable the call to `this.focus()` when `setNgModelValue()` is triggered.
https://github.com/angular/material/blob/595fefee3ca7bea220086a874d6b92eee319f08d/src/components/datepicker/js/calendar.js#L304-L310

@gabrieltaets we certainly would appreciate your PR and I can help you through the process. I apologize for not getting 100% through triaging all of the issues yet. I hope to finish that before the end of the year.

**Comment by gabrieltaets** [comment]
Hi @Splaktar 
I've been investigating this issue and I've noticed something quite odd. This behavior is easily reproducible in the reported version of angular@1.5.8, but not on angular@1.7.8.
I have seen this behavior at my workplace, where we happen to also use 1.5.8, but oddly enough, working on this CR at home (where angular@1.7.8 was firstly installed) it didn't reproduce at all. Switching back to 1.5.8 reproduces the issue. It appears that setNgModelValue is being called when the component is initialized in angular@1.5.8, but not in angular@1.7.8.
I was thinking of adding a new scoped parameter md-autofocus to indicate whether to autofocus on the calendar or not, but that wouldn't make sense if it the autofocus doesn't happen in 1.7.8. I guess we could explicitly call setNgModelValue in $onInit and be done with it.

Anyways, I'm just hesitant to work on a PR that fixes a problem that does not occur on newer versions of angular. What are your thoughts on this?

**Comment by Splaktar** [comment]
This should be fixed in `1.1.26` and `1.2.1`.
