### ISSUE TITLE
select: can not click outside of popup to close when inside of a dialog or panel

### ISSUE THREAD

**Issue by johnico** [angular/material#10373]
**Actual Behavior**:
 -  `What is the issue? *` can not close outside md-select on md panel/ dialog
 -  `What is the expected behavior?` close the select popup when clicking outside of the popup

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` add `md-select` to `md-panel` - add z-index 999 to the `md-select`. Try to close the select by clicking outside of the popup.
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.10
 -  `Angular Material Version:` 1.1.3

**Comment by jpike88** [comment]
+ 1, this is a major PITA. I'll try to fix it now

**Comment by josentiago** [comment]
What is the status of this issue? I have the same problem.

**Comment by brianpkelley** [comment]
so.... any solutions?

**Comment by Splaktar** [comment]
Please provide a CodePen demo so that we can start investigating and debugging this issue.

**Comment by Splaktar** [comment]
No demo provided. If you are still seeing this, please submit a new issue using the issue template and providing a CodePen reproduction.
