### ISSUE TITLE
Controller with prerendered $mdDialog never called.

### ISSUE THREAD

**Issue by creahard** [angular/material#10377]
**Actual Behavior**: A controller can be assigned to a prerendered dialog but it will never be used.
 -  `What is the issue? *` Buttons calling functions of the controller have no effect.
 -  `What is the expected behavior?` I expected a controller assigned to a prerendered dialog to work the same as with a compiled dialog, or something in the documentation to warn that this is the case.

**CodePen** (or steps to reproduce the issue): * Create a simple dialog that will be compiled with a controller and any number of functions. Assign any one of these functions to a button on the dialog. Then convert the dialog to be an element in the main page (prerendered) and try the button again.
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` v1.6.1
 -  `Angular Material Version:` v1.1.3

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` 54.0.2840.99
 -  `OS: *` Windows 7 Enterprise
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by zeruel01** [comment]
did you found a solution its happening the same to me

**Comment by creahard** [comment]
My only solution at this time is to take any dialogs that need the controller to do something with them out of my main page and put into separate files.

**Comment by zeruel01** [comment]
i did the same, thanks man

**Comment by ThomasBurleson** [comment]
We are working on AngularJS 1.6 support; see PR #10726
