### ISSUE TITLE
progress-circular: bad animation when md-diameter is set > 60px

### ISSUE THREAD

**Issue by rac146** [angular/material#10376]
**Actual Behavior**:
 -  `What is the issue?` In IE11, md-progress-circular does not animate as expected if md-diameter is set > 60.
 -  `What is the expected behavior?` No matter the md-diameter, the animation should be consistent.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/VPBbWq
 -  `Details:` This is a replica of the normal md-progress-circular demo using Angular Material 1.1.3 . Please look at the md-progress-circular components with md-diameter > 60 (the ones towards the bottom).

**Angular Versions**: *
 -  `Angular Version:` 1.6.1
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Internet Explorer 11
 -  `Browser Version: *`11.713.10586.0
 -  `OS: *` Windows 10
 -  `Stack Traces:`

![image](https://cloud.githubusercontent.com/assets/6462376/22666717/bb3e88c6-ec87-11e6-97ed-06f588bc7410.png)

Far left: md-diameter = 60
Middle: md-diameter = 70
Far right: md-diameter = 96

**Comment by ginmot** [comment]
Getting the same issue.

**Comment by rac146** [comment]
This is still occurring with the latest 1.1.4 release!

**Comment by ayZagen** [comment]
@rac146 i can confirm too
+1

**Comment by praveenraji2i** [comment]
+1

**Comment by LoganDupont** [comment]
Also happening for chrome (#10796)

**Comment by marosoft** [comment]
It is still happening in v1.1.21 [CodePen](https://codepen.io/marosoft/pen/ZEbyZXz)

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material/commit/0cca317c3dfb6455609c840d2b03bb575a4cc35b.
