### ISSUE TITLE
md-datepicker violates CSP (since v1.1.2)

### ISSUE THREAD

**Issue by christophercr** [angular/material#10389]
**Actual Behavior**:
 -  `What is the issue?` The  `md-datepicker` violates CSP 'unsafe-inline' style rule when displaying the calendar months and also the available years.
 -  `What is the expected behavior?` The `md-datepicker` component should not violate CSP.

**CodePen** (or steps to reproduce the issue): *
 -  `Details:` Set nonce via `$mdThemingProvider`. Add an `md-datepicker` component. Display the calendar, display the available years.

**Angular Versions**: *
 -  `Angular Version:` 1.5.x
 -  `Angular Material Version:` 1.1.2, 1.1.3

**Additional Information**:
 -  `Browser Type: ` Chrome, Firefox
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:` 
-- Chrome `Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-XXXXX'". Either the 'unsafe-inline' keyword, a hash ('sha256--YSPiAb7HOcmfeceuMH0SwetjSNWlGXGMwTufBOKnds='), or a nonce ('nonce-...') is required to enable inline execution.`
-- Firefox `Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src http://localhost:3000 'nonce=XXXXX”).`

This issue was introduced in  [de5e7e9](https://github.com/angular/material/pull/9893/commits/de5e7e90ed03902f26620ba9e2401fe1664ec1c9) to fix #9893

**Comment by Frank3K** [comment]
CSP-related: #10085.

**Comment by christophercr** [comment]
Is there any news about this?
