### ISSUE TITLE
layout-wrap broken on safari after update to version 1.1.2 

### ISSUE THREAD

**Issue by maxalencar** [angular/material#10388]
**Actual Behavior**:
 - When we add layout-wrap and layout="row" on safari the divs are showing as layout="column" even accessing https://material.angularjs.org/1.1.3/ on safari you can see it.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` >= 1.1.2

**Additional Information**:
 -  `Browser Type: *` Safari
 -  `Browser Version: *` 10.0.3
 -  `OS: *` OSX 10.12.3
 -  `Stack Traces:`

![screen shot 2017-02-09 at 12 45 44](https://cloud.githubusercontent.com/assets/514719/22783898/b3c01d18-eec5-11e6-8dcb-9c85d0ca62d2.png)
![screen shot 2017-02-09 at 12 45 59](https://cloud.githubusercontent.com/assets/514719/22783907/bc3252d6-eec5-11e6-8aae-5309732f099b.png)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by emi101** [comment]
+1

**Comment by geertjansen** [comment]
+1

**Comment by worsnupd** [comment]
+1

**Comment by PhMetzger** [comment]
Layout extra options (and my app ;-) ) are also broken under Safari (iOS Android macros)

**Comment by mgovorun** [comment]
+1

**Comment by rorydpayne** [comment]
+1

**Comment by mrbatista** [comment]
+1

**Comment by johann-devo** [comment]
+1

**Comment by htuoma** [comment]
+1

**Comment by mgol** [comment]
I confirm the issue. FWIW, it works fine in WebKit Nightly r213509 so it must be Material not accounting for a Safari issue that's only fixed in Nightly so far.

**Comment by ThomasBurleson** [comment]
Refs #10345

**Comment by blindeveloper** [comment]
+1

**Comment by tipodisimmia** [comment]
+1

**Comment by tipodisimmia** [comment]
It's broken also the example "https://material.angularjs.org/latest/layout/children" on "Flex Percent Values" the problem is the "layout-wrap" is not working from the 1.1.2 version.

**Comment by blindeveloper** [comment]
Guys, it is not the best, maybe be helpful for someone, here is my "fix".
`<div class="some-wrapper" layout="row" layout-wrap>
  <div class="some-wrapper_item" flex="50">50</div>
  <div class="some-wrapper_item" flex="50">50</div>
  <div class="some-wrapper_item" flex="50">50</div>
</div>

<style>.some-wrapper .some-wrapper_item {flex: 1 1 50%;}</style>`

it works for me in safari also

**Comment by blindeveloper** [comment]
Guys, it is not the best, maybe be helpful for someone, here is my "fix".

<div class="some-wrapper" layout="row" layout-wrap>
  <div class="some-wrapper_item" flex="50">50</div>
  <div class="some-wrapper_item" flex="50">50</div>
  <div class="some-wrapper_item" flex="50">50</div>
</div>

<style>.some-wrapper .some-wrapper_item {flex: 1 1 50%;}</style>

it works for me in safari also

**Comment by blindeveloper** [comment]
Here is not the best, but working solution. Maybe would be helpful for someone, while it's not fixed on library side
http://plnkr.co/edit/Xip5vwdPXZSd9HtLyZQ0?p=catalogue

**Comment by vwillyams** [comment]
Same issue as https://github.com/angular/material/issues/10345, the root cause is https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items and this was introduced by this fix for this issue: https://github.com/angular/material/issues/5345

**Comment by bduebel** [comment]
+1

**Comment by LoganDupont** [comment]
+1

**Comment by 1ne8ight7even** [comment]
+1

**Comment by owenhope** [comment]
+1

**Comment by francosioquim** [comment]
+1

**Comment by karin-n** [comment]
+1

**Comment by luispeerez** [comment]
+1

**Comment by mustafahlvc** [comment]
+1

**Comment by xjdesigns** [comment]
Is it possible to revert the change for layout to be proper with the flex-basis property. I feel it goes against the grain of flexbox by defaulting the flex basis to be 100%. This is telling the browser to be 100%, but grow/shrink it allowed and handling the width with a max.

**Comment by Splaktar** [comment]
As mentioned above, this is a duplicate of https://github.com/angular/material/issues/10345
