### ISSUE TITLE
md-date-picker misbehaves

### ISSUE THREAD

**Issue by sivakrrish1994** [angular/material#10393]
**Actual Behavior**:
 -  `date-picker is not getting opened when resizing the window while it works fine after refreshing the page.*`

**Expected Behavior**:
 -  `date-picker should open properly even when the screen is resized without refreshing.`

**Steps to reproduce the issue**: 
 -  `open the date picker with a md-open-on-focus`
 -  `Now without refreshing change it to mobile view`
 -  `Now try to open the date-picker by clicking on the input or the icon or with the triangle icon.`
 -  `Fails to open the date-picker but try the same by refreshing the page, it will work properly.`

**Angular Versions**: 
 -  `Angular Version: v1.6.1`
 -  `Angular Material Version:1.1.3`

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further.

**Comment by sivakrrish1994** [comment]
**Codepen**
http://codepen.io/sivakrrish/pen/gmvgQw


![screen_cast_md_date_picker](https://cloud.githubusercontent.com/assets/16810263/24104455/47c48f02-0da8-11e7-8b1c-05afb18bfb6b.gif)

**Comment by EladBezalel** [comment]
@topherfangio do you think this is a valid issue?

**Comment by topherfangio** [comment]
@EladBezalel Yes...ish. I don't think this has anything to do with resizing specifically, I think it has to do with when the tab/window is blurred.

I can reproduce this most easily by navigating to another page while the text input still has focus, but the datepicker isn't open.

**Steps to Reproduce**

1. In our [demo](https://material.angularjs.org/1.1.3/demo/datepicker), click on the date picker that has `md-open-on-focus` set to `true` (it's the second one on the left of the Basic Usage demo).

2. The date picker opens.

3. Hit `esc`. This will close the datepicker but leave the text input focused.

4. Change tabs away from, and then back to, the demos.

5. You can no longer open the datepicker via focus OR clicking the dropdown icon.

As far as I can tell, this is a legitimate bug. Likely has something to do with our `handleWindowBlur()` method in `datepickerDirective.js`.

**Comment by EladBezalel** [comment]
@sivakrrish1994 can you describe a real situation where this is a bug? 
I'm closing this issue as i feel like we will waste a lot of time solving something pretty rare correct me if i'm wrong and i'll reopen.

**Comment by sivakrrish1994** [comment]
@EladBezalel I am not sure but this may happen in such a case that take ipad as an example & if we are changing the screen orientation between landscape/portrait, this bug arises. I have tested this using chrome device inspector. 

Check this demo,
![date-picker-screen-orientation](https://cloud.githubusercontent.com/assets/16810263/25933742/03fa06d2-3637-11e7-9d1d-ea0ae08c2feb.gif)
