### ISSUE TITLE
select: creates a select element that doesn't follow the parent disabled status

### ISSUE THREAD

**Issue by mahmoudajawad** [angular/material#10396]
**Actual Behavior**:
 -  `md-select creates a select element that doesn't follow the parent disabled status`
 -  `a disabled attribute is supposed to be added to the script-created select element`

**CodePen** (or steps to reproduce the issue): *
 -  https://codepen.io/anon/pen/apPKWO

**Angular Versions**: *
 -  AngularJS: `1.6.1`
 -  AngularJS Material: `1.1.3`

**Additional Information**:
 -  `Tested on Chrome`
 -  `Latest`
 -  `Windows, Mac`

**Comment by merchant-hub** [comment]
me 2

**Comment by merchant-hub** [comment]
here 2

**Comment by Splaktar** [comment]
The provided demo does not reproduce the issue mentioned.
```html
      <md-input-container>
        <md-select ng-model="$ctrl.someModel" placeholder="Select a state" disabled required>
          <md-option ng-value="opt1">option</md-option>
          <md-option ng-value="opt1">option</md-option>
        </md-select>
      </md-input-container>
```
However, if you add a `name` attribute like:
```html
      <md-input-container>
        <md-select ng-model="$ctrl.someModel" placeholder="Select a state"
                   disabled required name="state">
          <md-option ng-value="opt1">option 1</md-option>
          <md-option ng-value="opt2">option 2</md-option>
        </md-select>
      </md-input-container>
```
Then an autofill clone `<select>` is created. [Demo](https://codepen.io/Splaktar/pen/WNwdJKw?editors=1010).
```html
<select class="md-visually-hidden" name="state" aria-hidden="true" tabindex="-1">
  <option ng-value="opt1" aria-checked="false">option 1</option>
  <option ng-value="opt2" aria-checked="false">option 2</option>
  <option ng-value="$ctrl.someModel" selected="" aria-checked="false"></option>
</select>
```

I can verify that only the `name` attribute is passed on from the `md-select` to the `select`. `disabled` and `required` are not.

- Can you please provide a use case where this is needed?
- If so, what attributes need to be passed on here?
  - I doubt all of the `md-select` attributes would make sense or be valid on a native `select`
  - Would we need to support passing on every attribute that native `<select>` supports?

**Comment by mahmoudajawad** [comment]
This is years old issue. I'm not using AngularJS anymore so can't confirm anything. I'm closing it.
