### ISSUE TITLE
$mdThemingProvider.theme is undefined

### ISSUE THREAD

**Issue by ricardogomes** [angular/material#1039]
I'm getting a weird problem 

$mdThemingProvider.theme is undefined

All the methods I have on $mdThemingProvider are SetDefaultTheme and AllwaysWatchTheme

Are the $mdThemingProvider (https://material.angularjs.org/#/Theming/03_configuring_a_theme) docs outdated?

**Comment by rosscdh** [comment]
+1 reolved issue with "angular-material": "0.7.0-rc1-master-84842ff" but the code example on the site: https://material.angularjs.org/#/Theming/02_declarative_syntax is still broken

```
          .config(function ($mdThemingProvider) {
              $mdThemingProvider.theme('default')
                .primaryPalette('pink')
                .accentPalette('orange');
          })
```

**Comment by louiswilbrink** [comment]
+1 for using "0.7.0-rc1-master-84842ff" version as well.  This also confused me until I looked into the v0.6.0 code, then found this thread.

**Comment by ThomasBurleson** [comment]
@rosscdh, @louiswilbrink - Plz look at this CodePen Demo - [mdInputs with Theming](http://codepen.io/ThomasBurleson/pen/gCrKt):

```js
.config(function($mdThemingProvider) {
    $mdThemingProvider.theme('default')
      .primaryPalette('blue')
      .accentPalette('red');
  
    $mdThemingProvider.theme('darkTheme')
      .primaryPalette('yellow')
  });
```

This all works.

**Comment by louiswilbrink** [comment]
@ThomasBurleson does it work because you are using a newer but non-release version of angular-material?  Couldn't tell what resource you were pulling in on the codepen

**Comment by ThomasBurleson** [comment]
@louiswilbrink I am using the latest version from [bower-material/#master](http://rawgit.com/angular/bower-material/master/)
