### ISSUE TITLE
chips: enable-chip-edit allows creation of duplicate chips

### ISSUE THREAD

**Issue by kaanjeepan** [angular/material#10392]
**Actual Behavior**:
 -  `Chips editable is accept the same name while edit the existing names as like new name? *`
 -  `Chips editable is should not accept the same name while the edit scenarios.`
**Refer**
![chipseditableissue](https://cloud.githubusercontent.com/assets/20426104/22854313/b10934a6-f091-11e6-8736-bf8850d694c3.png)
[https://material.angularjs.org/latest/demo/chips](url)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:v 1.6.1`
 -  `Angular Material Version:v 1.1.3`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: Version 55.0.2883.87 (64-bit)`
 -  `OS: Ubuntu 16.04`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by sivakrrish1994** [comment]
@kaanjeepan I think the issue was there in the earlier version too.
