### ISSUE TITLE
select: position is calculated incorrectly in rtl when long label is used

### ISSUE THREAD

**Issue by gkorland** [angular/material#10395]
When the label text is longger than all the option texts the position is wrongly calcualted in RTL.
http://codepen.io/anon/pen/mRarGr

![screenshot from 2017-02-12 14-08-06](https://cloud.githubusercontent.com/assets/753206/22861918/b7bd887e-f12c-11e6-9b85-c709bdc4f4b6.png)

Strangely, reopening of the dropdown fixes the position calculation (Or any other action that causes recalculation).

**Comment by EladBezalel** [comment]
@ThomasBurleson @topherfangio this probably would be solved if we'd convert select to use panel.. thoughts?

**Comment by topherfangio** [comment]
It's likely. I'd love to see the Select (and other components) get converted to Panel.

**Comment by marosoft** [comment]
It is still a problem in version 1.1.21: [CodePen](https://codepen.io/marosoft/pen/MWwPgaP)

**Comment by Splaktar** [comment]
Fixed in PR https://github.com/angular/material/pull/11894 via https://github.com/angular/material/commit/9f49e1043b98977ab4e7e1053d0f4ea5ee978df5.
