### ISSUE TITLE
md-tabs: text turns to dots on small screen on IE11

### ISSUE THREAD

**Issue by jarekskuder** [angular/material#10406]
I need tabs to be streched always and on small screans to, but words are turning in to dots or half of a word turns to dots. I thought maybe words are too big, but then i tried to resize the window and then it turns to normal words.

My code:
```
<md-tabs class="main-tabs" md-selected="vm.selectedIndex"
             md-center-tabs md-border-bottom md-autoselect md-no-ink
             md-no-pagination="false"
             md-stretch-tabs="auto"
             style="width: auto !important; margin-top: 10px;">
        <md-tab ng-click="openLeftMenu()" id="tab1">
            <md-tab-label>{{translates.top_menu_meniu}}</md-tab-label>
        </md-tab>
        <md-tab ui-sref="map" id="tab2">
            <md-tab-label>{{translates.top_menu_map}}</md-tab-label>
        </md-tab>
        <md-tab ui-sref="list" id="tab3">
            <md-tab-label>{{translates.top_menu_list}}</md-tab-label>
        </md-tab>
    </md-tabs>
```

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further.

**Comment by gbruins** [comment]
This also happens in IE11.  Open the demo page in IE 11 to see the issue:
https://material.angularjs.org/latest/demo/tabs

**Comment by gbruins** [comment]
May I suggest that the 'needs:demo' and 'P5 - Needs Investigation' labels be removed?  This issue is  'demoable' on this page when viewing in IE11:  https://material.angularjs.org/latest/demo/tabs

Perhaps the "browser: IE" label can be added as well to give this issue more visibility and urgency.

**Comment by gbruins** [comment]
This bug was introduced in 1.1.2

**Comment by waegen** [comment]
+1

**Comment by peter-imrich** [comment]
+1 for a fix - We are too running into this issue when number of tabs exceeds the horizontal space

**Comment by LoganDupont** [comment]
+1

**Comment by hurricane987** [comment]
+1

**Comment by amritk** [comment]
+1

**Comment by motabass** [comment]
**+1**

**Comment by Splaktar** [comment]
Verified that this is not reproducible on Chrome, Firefox, or Safari.

**Comment by SanjanKalsi** [comment]
I too got into the same issue however a temporary yet dirty way (static) to fix this is to use
`nth-of-type`  CSS selector and set `min-width`  statically to each tab.
This of course is not suitable if you are using dynamic tabs with varying label lengths.

I found that `position: absolute` to `<md-pagination-wrapper>` is not getting rendered in IE.
The same if I remove from Chrome and Firefox styling in the developer tools it recreates the same issue.

![md-tab-ellipsis](https://user-images.githubusercontent.com/34156248/38488795-25b1de54-3c02-11e8-9176-79a7b35c8515.jpg)

**Comment by SanjanKalsi** [comment]
**Found the Reason !!!**

As per @gbruins comment that this issue happened from 1.1.2, I saw the CSS applied to 1.1.1 (no issue in this version in the dynamic tabs demo) on `<md-pagination-wrapper>` and compared it to v1.1.8 and found that:
`width: 999999px` is missing in the current version CSS.
Adding this to `<md-pagination-wrapper>` makes it working in IE.

Hope this helps.

![md-tab-issue-fix-github](https://user-images.githubusercontent.com/34156248/38717548-2780c410-3f05-11e8-9896-d59e9acbaac6.jpg)

**Comment by Splaktar** [comment]
That's interesting. Do any more sane values for `width` work as well? What is the `width` without setting it to `999999px`?

**Comment by SanjanKalsi** [comment]
It seems that all values of `width` will work until the labels and the left/right control icons can be accommodated within that `width`.

I think that the general idea till v1.1.1(**for IE fix only**) was that we can allow closest maximum static width compatible with all browsers ([maximim pixel value](https://stackoverflow.com/questions/16637530/whats-the-maximum-pixel-value-of-css-width-and-height-properties))to the `<md-pagination-wrapper>`  which can accommodate maximum number of tabs as possible.

My hunch is that in the subsequent versions this static CSS was removed from the `angular-material.css` during a review process since static styling is not desirable.

**Comment by SanjanKalsi** [comment]
@Splaktar, found the commit from where the `width: 999999px;` was removed. (from 1.1.2 change log): 

**Commit**: [5b799e2](https://github.com/angular/material/commit/5b799e2)
**File**: src/components/tabs/tabs.scss

**Comparision**:

@@ -159,13 +159,11 @@ md-pagination-wrapper {
    display: flex;
    transition: transform $swift-ease-in-out-duration $swift-ease-in-out-timing-function;
    position: absolute;
 -  **width: 999999px;**
    @include rtl-prop(left, right, 0, auto);
    transform: translate3d(0, 0, 0);
    &.md-center-tabs {
      position: relative;
 -    width: auto;
 -    margin: 0 auto;
 +    justify-content: center;
    }
  }

**Comment by Splaktar** [comment]
It looks like that commit references the move to flexbox for sizing of tabs. I wonder if it is possible to use flexbox to properly size the `md-pagination-wrapper` on IE.

**Comment by zakaoai** [comment]
Hello I have the same Issue with my md-tabs in IE. The temporary Fix ( width : 999999px ) work well for the display.
There is still a problem with the usage of the Arrows (Next Page and Previous Page) and the click on the tab header.

Try on IE : https://codepen.io/anon/pen/qYaZYW

![image](https://user-images.githubusercontent.com/31382994/39292689-33eb2bfa-4937-11e8-8bb7-5298b4dd39ea.png)

How to reproduce : 
- Click two times on the last tab header you can see
- Click on the right Arrow

**Comment by Nickproger** [comment]
![image](https://user-images.githubusercontent.com/1409078/44260273-948f3f80-a21c-11e8-8c01-d68502693c6d.png)

We've got the same issue :(

**Comment by Splaktar** [comment]
As mentioned by @zakaoai, just setting the `md-pagination-wrapper`'s width is not enough. If you only change that, then the inkbars and paging buttons can get very out of sync and broken.

I tried just adding `flex: auto` but that didn't help at all. I'm going to explore some other flexbox compatible options. I really don't want to revert back to manual width calculations since that caused issues with tabs and more.

**Comment by Splaktar** [comment]
I have opened PR https://github.com/angular/material/pull/11432 to address this via CSS changes to `md-tab` and `md-tab-item`.

**Comment by thesunfern** [comment]
Try setting the CSS property for it. `.md-tabs{ overflow : visible; }`
