### ISSUE TITLE
md-date picker send keys in Protractor test

### ISSUE THREAD

**Issue by lararogu** [angular/material#10404]
I have an angular app and I would like to test that a user always enters a valid date  of birth in a form.I am using a date picker:
(md-datepicker  class="inputForm" id="myDate" name="dateField" required md-min-date="minDate" md-max-date="maxDate" > /md-datepicker>

I am trying to use the sendkeys() function in protractor to set a value for the date but it doesn't work:
 var today = new Date();
var date = element(by.id('myDate')).sendKeys(today);

When I run the test nothing happens?Any ideas?

**Comment by dovydas55** [comment]
Yeah im having a same issue. Would be great to get some feedback on this.

**Comment by seanlarge** [comment]
+1

**Comment by lararogu** [comment]
Found the solution:
 element.all(by.css('.md-datepicker-input')).get(0).click().sendKeys('10/16/1947');

**Comment by mathieub93** [comment]
Just to clear this issue up for everyone getting it.

`md-datepicker` is a class containing multiple elements, a button and 2 divs in my case.
The button can be interacted with to set a date and the first div has a input field which can be interacted with. The test itself can interact with the `md-datepicker` itself.

Still fixing this issue for myself as well (by getting the correct xpath from the known location of the `md-datepicker`).

**Comment by jogaga1819daw2** [comment]
That didn't work for me, instead I used something like this:
element(by.css('#myDate input')).click().clear().sendKeys('10-03-2019');

**Comment by chriskapp** [comment]
For me it worked with the standard date format i.e.

```
element(by.model('filter.from')).click().sendKeys('2015-06-01');
```

**Comment by ravindranathakila** [comment]
This works for me. Idea is to reach the year selection, navigate to an year and hit enter 3 times.

```
    element.all(by.xpath('//mat-datepicker-toggle')).get(0).click();

    element.all(by.css('.mat-calendar-period-button')).get(0).sendKeys(protractor.Key.ENTER, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.LEFT, protractor.Key.ENTER, protractor.Key.ENTER, protractor.Key.ENTER);

```

For your reference, my HTML code, if applicable:

```
        <mat-form-field fxFlex="100">
          <input required placeholder="{{today}}" matInput [matDatepicker]="picker"
                 (dateInput)="setBirthday('input', $event)" (dateChange)="setBirthday('change',$event); validateBirthday();" (focus)="picker.open();">
          <mat-label>Birthday</mat-label>
          <mat-datepicker-toggle  matSuffix [for]="picker"></mat-datepicker-toggle>
          <mat-datepicker opened #picker></mat-datepicker>
        </mat-form-field>
```

**Comment by Splaktar** [comment]
@ravindranathakila Angular Material and CDK questions are handled [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
