### ISSUE TITLE
docs: Boolean attrs that should contain interpolation

### ISSUE THREAD

**Issue by vladimir-barsuchenko** [angular/material#10407]
**Actual Behavior**:
 -  `What is the issue? *` Attrs that are involved into `defineBooleanAttribute` func should be documented as $observables. Thus to contain interpolation `{{ }} `
 -  `What is the expected behavior?` docs

    noInkBar
    dynamicHeight
    noPagination
    swipeContent
    noDisconnect
    autoselect
    noSelectClick
    centerTabs
    enableDisconnect

**Comment by ThomasBurleson** [comment]
@levgaas - please elaborate with more information.
