### ISSUE TITLE
md-tooltip styling applied incorrectly

### ISSUE THREAD

**Issue by valeriemaite** [angular/material#10401]
**Actual Behavior**:
 -  `What is the issue? *` The following syntax is not working as of release 1.1.2:
md-tooltip .md-content {
   ///custom values, styling is not applied
}
 -  `What is the expected behavior?` To apply the styling

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.6.9
 -  `Angular Material Version:` 1.1.2 and above (it was working with 1.1.1)

**Additional Information**:
 -  `Browser Type: *` All
 -  `Browser Version: *` most recent
 -  `OS: *` Windows
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by levgaas** [comment]
Yes you are right. Now tooltips have different layout and API due to changes in `1.1.2`

Thus tooltips don't have `._md-content` inside. 
Plus they are aligned globally inside `md-panel-auto-wrapper`

That said to provide custom stylings please add a class to `md-tooltip` element

**Comment by EladBezalel** [comment]
please follow as @levgaas said
