### ISSUE TITLE
Could we add escapeToClose(Boolean) md-sidenav 

### ISSUE THREAD

**Issue by hafridign** [angular/material#10411]
I am trying to have it ignore the Escape Key for closing the sidebar. I did not want to lock my sidebar as i wanted it to be toggled by user.

I wanted to it to be locked on gt-md without having it be fully locked so that the user can toggle it but indoing that it ends up making the escape key toggle the sidenav. I wanted to see if could please add escapeToClose(BOOLEAN) to the sidenav.

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/ngmaterial)

Closing this issue as 'invalid'. Thank you.
