### ISSUE TITLE
Feature request: add ability to change swipe sensitivity

### ISSUE THREAD

**Issue by no-more** [angular/material#10417]
**Actual Behavior**:
 -  `What is the issue? *`
Swipe triggers too easily in my case.
 -  `What is the expected behavior?`
Be able to reduce sensitivity

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.*
 -  `Angular Material Version:` 1.1.*

**Additional Information**:
 -  `Browser Type: *` Chrome web view on android
 -  `Browser Version: *`
 -  `OS: *` Android
 -  `Stack Traces:`

----

Hi,

I have seen an old request someone complaning about not enough sensitivity for swipe, in my case it's the opposite. Do you think this could be a parameter ? Everybody would be happy then.

Thanks.

**Comment by ThomasBurleson** [comment]
This issue is closed due to one of the following reasons:

*  Issue has a reasonable workaround
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests (PR) are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Keep your PR small and focused; PRs with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
