### ISSUE TITLE
background-color has NaN, thus does not work

### ISSUE THREAD

**Issue by nefcanto** [angular/material#10418]
**Actual Behavior**:
 -  `What is the issue? *` I've added angular material to my framework, and color is not applied. I see `background-color: rgb(3,51,NaN);` or even `background-color: rgb(NaN,NaN,NaN);`. At first I thought maybe one of my styles interfere with Angular, but as I see no style from mine is applied.
 -  `What is the expected behavior?` I want buttons to have color. Right now no color whatsoever is applied.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` I can't reproduce this issue. I just include
 -  `Details:` I don't work with **gulp** or **npm**. I very simply include css and js files. That's it.

**Angular Versions**: *
 -  `Angular Version:` 1.5.6
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` 56.0.2924.87 (64-bit)
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by codymikol** [comment]
What kind of element are you trying to apply a background-color to? If you try to add a class to an angular-material component, the background color will be overridden by the built in theming. That however does not explain you getting NaN.

**Comment by ThomasBurleson** [comment]
@nefcanto - please provide a plunkr or specific code to reproduce this issue.

**Comment by Splaktar** [comment]
Closing as no demo was provided.
