### ISSUE TITLE
angular material md-option width issue with long value

### ISSUE THREAD

**Issue by MoAsmar** [angular/material#10410]
**Actual Behavior**:
 -  `What is the issue? *`
angular material md-option width issue with long value
 -  `What is the expected behavior?`
It should wrap the text in the limited flex size (ellipsis text by default), but instead it pushes the next element to the right to take more width.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/MoAsmar/pen/apxBNQ
 -  `Details:` 

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 56
 -  `OS: *` Windows
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Nextt1** [comment]
A very Simple mistake. According the official docs `A layout child's flex directive can be given an integer value from 0-100`. In your case its 100+5+100. Just make it as 40+10+40 and it will work. 
Working [Codepen](http://codepen.io/next1/pen/apxGXY)

**Comment by MoAsmar** [comment]
Problem was in flex values, issue solved thanks.

http://stackoverflow.com/a/42283575/4086736
