### ISSUE TITLE
improve md-nav-bar demo

### ISSUE THREAD

**Issue by sebakerckhof** [angular/material#10422]
**Actual Behavior**:
 -  `What is the issue? *`
This example: https://material.angularjs.org/latest/api/directive/mdNavBar
Has click handlers to a non existing `goto` function. And a non-working `Disable Ink Bar` check box

 -  `What is the expected behavior?`
Goto function removed from templated or implemented in controller. Disable ink bar checkbox working.

**Comment by bfalzarano** [comment]
@sebakerckhof agree w you on the disable ink bar checkbox not working.  However, with regards to the non-existing goto function what you will find is that if you remove the click handler the nav item will not be displayed and therefore will not function.  the `md-nav-click` handler and the associated javascript goto statement `"goto('page3')"` is certainly being used.

**Comment by sebakerckhof** [comment]
@bfalzarano well, the thing is that the navigation is controlled by `md-selected-nav-item` on the nav bar. But having the click handlers there, doing actually nothing, is confusing.
