### ISSUE TITLE
Demo codepens are not working, because ng-material cdn are pointing to incorrect URL. 

### ISSUE THREAD

**Issue by pankajparkar** [angular/material#10429]
**Actual Behavior**:

 -  I went to [angular material select](https://material.angularjs.org/1.0.1/demo/select) page and then clicked on code pen to play with live code. But the codepen got broken. I opened a console & found that `ngMaterial` module haven't got loaded. Further investigation said that, angular-material.js is pointing to `localhost:8080` instead of `google cdn`.

![screen shot 2017-02-21 at 10 04 58 am](https://cloud.githubusercontent.com/assets/5320044/23174258/ce4ac640-f881-11e6-8cbb-8f8d5f461919.png)
 
 -  `What is the expected behavior?`

Angular material should point to correct CDN link, so that demo codepen get into working state.

**Comment by ThomasBurleson** [comment]
@pankajparkar - your link uses Angular 1.0.1... which is no longer supported. Please upgrade to Angular Material v1.1.3 or higher. The CodePen links for those demos work:  https://material.angularjs.org/HEAD/demo/select

**Comment by pankajparkar** [comment]
@ThomasBurleson Apologies, I was trying something and got ver `1.0.1` version link from Google result. Thanks for quick response 👍
