### ISSUE TITLE
theme:what is the default shade for intentions ?

### ISSUE THREAD

**Issue by LabN36** [angular/material#10420]
Hi,
as we know by default angular material uses these palette 
**1.indigo(as a primary)
2.pink(as a accent)
3.red(as a warn)
4.grey(as a background)**

here my question is what exact value it uses for intention group like(for light/dark)
1. **md-primary/md-accent/md-warn**
2. **md-hue-1/md-hue-2/md-hue-3**

because this  link [color-palette](https://material.io/guidelines/style/color.html#color-color-palette) show no of shades in a single palette for eg. 50,100,200,300,...

I've also looked source code but not able to understand as I'm a beginner here
[theme](https://github.com/angular/material/tree/master/src/core/services/theming)

**Comment by EladBezalel** [comment]
I'm sorry but i couldn't understand your question, what do you mean by intention group?

Also please have in mind that these kind of question are related to our forums and aren't an issue.
