### ISSUE TITLE
Black artifacts when using md-menu and page contains scroll in IE11

### ISSUE THREAD

**Issue by hengun348** [angular/material#10428]
**Actual Behavior**:
 -  `What is the issue?` 
1. Have an md-menu on a page in IE11.
2. Make sure the page shows a scrollbar to the side.
3. Click the md-menu trigger

A weird black background appears for parts of the screen. Sometimes it is only visible for less than a second.

![image](https://cloud.githubusercontent.com/assets/5662093/23157659/5dfde274-f81c-11e6-8246-f401795c8ee9.png)

 -  `What is the expected behavior?`

It works without any weird artifacts.

**CodePen** :
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/apeJOb
 -  `Details:` follow steps above to reproduce. Make sure there is a scrollbar visible and that you have scrolled all the way to the bottom.

**Angular Versions**:
 -  `Angular Version:` 1.5.10
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type:` IE11
 -  `Browser Version:` 11.576.14393.0
 -  `OS:` Windows 10

**Comment by hengun348** [comment]
**I have been doing some investigation:**
1. This does not happen in the demo pages for ng-menu in IE11 (only in our project

2. I have noticed that angular material adds inline styles to the body 
`body {position: fixed; width: 100%; top: -100px;}`
This only happens in our project not on the demo pages on am site.

3. If I add the following I dont get the issue:
```
html, body, form {
position: relative !important;
top: 0 !important;
}
```
4. The following in angular-material.js seems to be responsible for adding the styles to body:

```
function disableBodyScroll() {
  var htmlNode = body.parentNode;
  var restoreHtmlStyle = htmlNode.style.cssText || '';
  var restoreBodyStyle = body.style.cssText || '';
  var scrollOffset = $mdUtil.scrollTop(body);
  var clientWidth = body.clientWidth;

  if (body.scrollHeight > body.clientHeight + 1) {
    applyStyles(body, {
      position: 'fixed',
      width: '100%',
      top: -scrollOffset + 'px'
    });

    htmlNode.style.overflowY = 'scroll';
  }
```

**Comment by hengun348** [comment]
We have had some success with the following theory/solution:

When the mdMenu opens, a transparent backdrop element gets added to the body. At the same time, Angular Material adds inline styling to the body element that moves it upwards such that it leaves an empty rectangle in the bottom of the browser. In IE11, showing a transparent element over "nothing" turns black.

By adding background-color to the root <form> and our root wrapper element, the backdrop element can then display the bg-color through its transparency.

An additional fix to this was needed since the form and the wrapper don't cover the part where a possible horizontal scroll appears. The fix here was to actually set a horizontal scroll on the backdrop element itself so that it covers the bottom artifact. Not the prettiest of fixes but it feels reasonable at this point.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'will not support' category for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests to resolve this issue are encouraged! Note, however, that Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
