### ISSUE TITLE
mdIcon: Icons based on SVG, font-faces, and CSS 

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1042]
A suite of icons should be support within Angular Material. Many components (BottomSheet, Lists, Cards, Chips, FABs, etc.) will use `md-icon` as a child element.

![screen shot 2014-12-23 at 1 24 39 pm](https://cloud.githubusercontent.com/assets/210413/5542046/00641582-8aa7-11e4-92b6-bae178fccaf0.png)
![toolbar_icons](https://cloud.githubusercontent.com/assets/210413/5541945/b332b274-8aa5-11e4-9d5e-ba1c4a35a47a.png)
![keyboard_icons](https://cloud.githubusercontent.com/assets/210413/5541946/b3361d1a-8aa5-11e4-9ad6-67a77e72feaa.png)

#### Icon Types

While Material Design icons come with SVG and CSS sprites for various resolutions, the full set of icons is enumerated below:

* SVG
* Animated SVG
* Color SVG
* Font Faces
* PNG
* JPEG

A live preview of all icons in the [Material-Icons](https://github.com/google/material-design-icons) repository is shown here:  [Live Preview](http://google.github.io/material-design-icons/)

![screen shot 2014-12-23 at 1 26 37 pm](https://cloud.githubusercontent.com/assets/210413/5542065/4bae1a7e-8aa7-11e4-8e2f-f84cfb978fd9.png)

<h2>Visual requirements:</h2>
 * Font-icons only
   *  class name used to specify desired icon; e.g. `<md-icon icon="refresh" />`
 * Hover effects to animate, colorize, etc.
 * Media support for responsive changes
 * Support for Dark themes

<h2>Functional requirements:</h2>
 * Ability to use remote SVG, PNG, or JPEG resources
 * Ability to use embedded (aka inlined) resources

<h2>Questions:</h2>
 * How can developers easily select a subset of icons for their needs?
 * How can developers easily embedded their own SVGs ?
   * Can we provide a template and a batch gulp tool to easily embedded a first-pass rendition of 1..n remote SVGs ?
 * How will the icons be deployed as part of Angular Material releases ?
 * Will Theming impact icon choices (colors) ?

### Additional Resources

*  [FlatIcon](http://www.flaticon.com/packs/material-design)
*  [SVG Animations and CSS Transforms](http://css-tricks.com/svg-animation-on-css-transforms/)
*  http://www.filamentgroup.com/lab/bulletproof_icon_fonts.html
*  http://www.sitepoint.com/tips-accessible-svg/

### Version 2 Wishlist

 * SVG support for colors and animations
 * Multi-state icons may be needed where each state is represented by animated SVGs
   * See [FAB with Progress Indicators](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B0NGgBg38lWWbTlSaHdQZEMtalk/components-progressactivity-typesofindicators-061101_Circular_Aspirational_xhdpi_002.webm)
   * State features are not for user-interactions but rather for icon animations.
   * More information is needed about transitions between animation states of icons
 * State support; where each state display an icon visualization. State changes update visuals.
   *  This would be very powerful...

Here is a sample of states with `md-icon`

```html
 <md-icon>
  <md-icon-state state="start" src="" />
  <md-icon-state state="animated" src="" />
  <md-icon-state state="done" src="" />
</md-icon>
```
### Design Doc

A Google design document will be prepared to present issues, constraints, solutions, and impacts.

**Comment by ilanbiala** [comment]
@ThomasBurleson will this depend on angular-material-icons?

**Comment by CICCIOSGAMINO** [comment]
Actually i use the directive md-icon like this : 

     <md-icon icon="bower_components/material-design-icons/action/svg/design/ic_android_24px.svg"></md-icon>

how can set a different color or size in md-icon ?

**Comment by marcysutton** [comment]
Should we leave SVG out of @font-face resources? @robertmesserle mentioned using it for anti-aliasing in Chrome/IE, but it is being deprecated in Chrome (and possibly Firefox). https://groups.google.com/forum/#!topic/icomoon/ttjKOE7fEv8

Inline SVG is good as long as we expose alternate text.

**Comment by ThomasBurleson** [comment]
As recently discussed, we will still support Javascript overrides for SVG content in mdIcons.
But that will be part #2. Part #1 will support font faces.

**Comment by janesconference** [comment]
Also, http://materialdesignicons.com/ - cool icons drawn by the community.

**Comment by justindujardin** [comment]
There are a few material design icons that will not convert well to fonts: the editor color selection icons and the device wifi/signal/battery icons.  Will these be supported in some way?

**Comment by calidion** [comment]
i would like to know how to incorporate fontawesome icons into md-icon.

**Comment by ThomasBurleson** [comment]
Using FontAwesome with `<md-icon />`: [CodePen Demo](http://codepen.io/ThomasBurleson/pen/JopjjN?editors=101)

**Comment by calidion** [comment]
great.

**Comment by moeduffdude** [comment]
i don't know whether or not i should create an issue, but when going through 0.8.0-rc1, the md-icon used on md-tabs is barely visible on iOS devices
![ios simulator screen shot feb 16 2015 15 57 18](https://cloud.githubusercontent.com/assets/2365328/6212333/14e34ad6-b5f5-11e4-84b8-d30771162a16.png)

**Comment by 3Pi** [comment]
What is the right way for using material icons (as shown on [Google Material Design Icons](https://google.github.io/material-design-icons/) in a md-button ?
Ligatures are OK wherever else but in md-buttons and I didn't find out how to use md-font-icon properly...

**Comment by edaquinta** [comment]
Hey, I know this issue is closed but I still don't get how I can use the Material Icons (http://google.github.io/material-design-icons/) with the <md-icon> directive in a seamless way. I think I still need some CSS individual classes to use md-font-icon right?

**Comment by edaquinta** [comment]
btw, I create my own approach: 

CSS
---------------------------------
.menu:after { content: "\E5D2" }

HTML
---------------------------------
<md-icon md-font-icon="menu"></md-icon>

so I define the icons I'll be using but probably I working double, maybe there is a better way, but I didn't find it cause I don't wanna use the svg, just the web font.

**Comment by ThomasBurleson** [comment]
@edaquinta  plz open a new issue.
@moe-szyslak - do you still have this issue with the code in master? If yes, plz open a new issue with a Demo.
@3Pi - Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
