### ISSUE TITLE
slider: text input linked to a same model. Changing text doesn't move slider

### ISSUE THREAD

**Issue by cadilhac** [angular/material#10427]
**Actual Behavior**:
 -  `What is the issue? *`
When a slider and an input are linked to the same model (expected to hold a number), modifying the text through the input does not reflect in the slider if the input has not the "number" type set.
 -  `What is the expected behavior?`
I expect that it still works if I don't want to show up and down arrows in the input (therefore setting type="text")

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
[Codepen](http://codepen.io/anon/pen/EZBMjd)
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.6.1
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` I am under Chrome
 -  `Browser Version: *` 56
 -  `OS: *` Win 7
 -  `Stack Traces:`

**Comment by AndriIushchuk** [comment]
The model of `<md-select>` component expect `Number` as value. Other values will be formatted to `undefined` and represented as starting point of slider range.

It would be easier to hide arrows of `input[number]` by css .

**Comment by cadilhac** [comment]
You mentioned md-select. Did you mean md-slider? If yes, know that I'm only typing digits in the input field.

**Comment by AndriIushchuk** [comment]
I mean `<md-slider>`, sorry. Even if you're typing only digits in the `input[text]` they will be bound as `String`.

**Comment by Splaktar** [comment]
As mentioned in https://github.com/angular/material/issues/10288 and by @AndriIushchuk above, the `ng-model` expression for `md-slider` needs to resolve to a `number` and not a `string.

Here's a [CodePen](https://codepen.io/Splaktar/pen/ZxmZzZ?editors=1010#0) that shows you how to implement this using an `<input type="text" ...>`.
