### ISSUE TITLE
md-dropdown-items doesn't work if you use md-menu-class to style the menu's list items

### ISSUE THREAD

**Issue by chrismortega** [angular/material#10435]
**Actual Behavior**:
 -  `What is the issue? *` 
md-dropdown-items seems to multiply the height of a single unstyled item times the number specified to arrive at the height of the dropdown.

 -  `What is the expected behavior?`
md-dropdown-items applies the md-menu-class style before computing the height for the dropdown

**CodePen** (or steps to reproduce the issue): *
http://codepen.io/chrismortega/pen/bqGwxv

Looks like styling the li elements is what really affects it

**Angular Versions**: *
 -  `Angular Version:` 1.1.3
 -  `Angular Material Version:` 1.5.11

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Version 56.0.2924.87 (64-bit)
 -  `OS: *` Windows 10
 -  `Stack Traces:`

**Comment by chrismortega** [comment]
What's super weird is that my codepen shows it working fine now. Yesterday when I wrote the issue it definitely wasn't. I'll look into it some more and add more detail if I can figure out what's going on.

**Comment by EladBezalel** [comment]
Any updates?

**Comment by chrismortega** [comment]
Only that it I haven't seen the issue again. I guess it could have been something up with Chrome? This can probably be closed. Thanks.
