### ISSUE TITLE
md-select required does not work?

### ISSUE THREAD

**Issue by gsjohal** [angular/material#10436]
**Actual Behavior**:
 -  `What is the issue? * Even If I do not fill the required field, it lets me to save the form. 
 -  `What is the expected behavior?` It should not let me save the form instead me error saying please fill this feild.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further.

**Comment by jgall** [comment]
I have created a codepen that demonstrates this issue: http://codepen.io/johngallagher/pen/PpawXW

**Comment by Splaktar** [comment]
@jgall the provided CodePen demo is now a 404. If this is still an issue for you, please submit a new issue using the issue template and providing a CodePen reproduction.
