### ISSUE TITLE
Autocomplete inside Dialog not sizing height properly, falling off page.

### ISSUE THREAD

**Issue by stephengardner** [angular/material#10437]
When opening an autocomplete inside an mdDialog on a scrolled page, the suggestions will fall off the page if the viewport is small enough.

Real life use case - mobile phone -> scrolls page -> opens dialog -> inputs location based on autocompletions -> suggestions fall off page.

<img width="168" alt="offscreen" src="https://cloud.githubusercontent.com/assets/7368566/23275874/19945080-f9d6-11e6-8fbb-b343b799eebe.png">

If the page is not scrolled, everything is OK.  If the page is scrolled, this problem occurs.  Seems like the autocomplete doesn't take into account the scroll distance when calculating max-height for the container.

**Comment by chaithanyabi** [comment]
We have a similar issue. Can you please let us know how the issue was resolved
