### ISSUE TITLE
mdSelect and mdDatepicker (still) causing jump to top of page

### ISSUE THREAD

**Issue by kdbruin** [angular/material#10432]
Using Angular Material 1.1.3 I'm still experiencing a jump to the top of the page when using mdSelect with Firefox 51.0.1. I've tried to create a pen to reproduce the issue but whatever I try it won't fail. However, my application fails it will jump to the top of the page.

I've tried the work-around from [here](https://github.com/angular/material/issues/1648#issuecomment-187821627) but that won't work either.

**Comment by kdbruin** [comment]
Changed the title to reflect that also the datepicker causes a jump to the top of the page.

**Comment by veritas** [comment]
@kdbruin Can you check my pull request  #10549 , it should solve the issue.

**Comment by rajathms** [comment]
@veritas what is the last build(release version ) which includes your code.

**Comment by rajathms** [comment]
@veritas thank you,
@kdbruin I confirm that this issue is fixed in the latest version ( i.e **version 1.1.5**) tested and it is working fine.
