### ISSUE TITLE
Material becomes outdated

### ISSUE THREAD

**Issue by LoganDupont** [angular/material#10430]
**Actual Behavior**:
 -  `What is the issue? *` 
 The problem is that AngularJS Material should still be updated on regular time (at least as long there is no stable version for material 2). As i see it, the problem that we as users have are that we are not aware of what's happening behind the scenes for Material at the moment. For example important changes that needs to happen are still postponed, milestones are outdated, a lot of issues has been closed because the team focus on material 2 and whole bunch of other bugs that are just open without any feedback or label on it. For example a new release with a milestone on 11 Februari with some important fixes that was postponed to 24 Februari. But will probably get postponed again because no improvements were made until now.

So please act on this problem because each day there are new bugs that are added and the list keeps growing every day. Even if it's just an weekly update we would already really appreciate. We all know that the team is busy and working really hard on Material 2. We really appreciate the effort the team put in that project. But that doesn't mean that Material shouldn't get updates on regular time because of that.

I hope that i am not the only one who is expecting these issues and that the Material Team will act on these problems.

Greets,
Logan

PS: I still like Material!

**Comment by ThomasBurleson** [comment]
We plan on regular bi-monthly patch releases and bi-yearly minor releases (which support breaking changes). Thank you for this post. Angular 1.1.4 should be released on March 16.
