### ISSUE TITLE
Styling the md-dialog-container

### ISSUE THREAD

**Issue by paramsingh88** [angular/material#10445]
I want a particular md-dialog-container to have a background color of blue, but it doesn't seems possible with the current options. 

```
this.dialog.open(TdAddLabelDialogComponent, {
			
});
```

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/ngmaterial)

Closing this issue as 'invalid'. Thank you.
