### ISSUE TITLE
md-autocomplete first click not showing anything

### ISSUE THREAD

**Issue by wilker7ribeiro** [angular/material#10449]
My autocomplete doesn't show any options on first click.
It should show all options on first click.
It get back to normal when anything is typed.

CodePen: http://codepen.io/anon/pen/oZxxjJ

 -  Angular Version: 1.5.5
 -  Angular Material Version: 1.1.0

 -  Browser: Chrome v56 / Firefox v47
 -  OS: Win 7

**Comment by abartolo** [comment]
I'm having a similar issue. When I click on it, it opens and when I select something it work fine. As soon as I click the "X" to clear the input it doesn't reopen the autocomplete.

Hard to replicate :/

**Comment by EladBezalel** [comment]
Seems to be working with the latest version:
http://codepen.io/EladBezalel/pen/WpKGXG
