### ISSUE TITLE
media: breakpoints always false at 599px

### ISSUE THREAD

**Issue by FlorianBurgevin** [angular/material#10443]
**Actual Behavior**:
 -  `What is the issue? *` At 599, none of mdMedia('xs') or mdMedia('gt-xs') are working. Idem at 959px for 'md'
 -  `What is the expected behavior?` At 599px, mdMedia('xs') is true, and at 600px mdMedia('gt'xs') is true

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`  http://codepen.io/anon/pen/ryVGBo
 -  `Details:` If you resize the browser to be at 599px, both of tests are false

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *`  chrome
 -  `Browser Version: *` latest
 -  `OS: *`  window
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Tested in 1.1.7 with an [updated CodePen](https://codepen.io/Splaktar/pen/BrzqyE) and I am not able to reproduce this. I believe that this was fixed sometime in the last few releases.
