### ISSUE TITLE
md-primary button into md-toolbar

### ISSUE THREAD

**Issue by konan2** [angular/material#10451]
When i use md-primary.md-raised button into md-toolbar the button must be contrast than now, instead if i use not md-raised button - it disappears because has the same font-color as toolbar background.

Example here:
https://www.screencast.com/t/wwgUc2B9G

I can to make pull request to fix this issue. Thanks.

**Comment by codymikol** [comment]
Are you adding class="md-primary md-raised" ?

**Comment by konan2** [comment]
Yes i use class="md-primary md-raised"

**Comment by konan2** [comment]
button class="md-primary" has the same font-color as md-toolbar background color. Please check it. Here is pic:
 https://www.screencast.com/t/5Bqlq3Ow4d  -- with custom css
https://www.screencast.com/t/wdCzz2p4en -- angular material css only

**Comment by konan2** [comment]
All ok when i use md-raised class, without it button disappears

**Comment by codymikol** [comment]
Can you make a plunker?

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
