### ISSUE TITLE
md-card-avatar is no longer working

### ISSUE THREAD

**Issue by RedFour** [angular/material#10459]
I've recently upgraded to beta 2, and md-card-avatar is no longer working. It use to make a small circle image, but now it just shows the what looks to be the default picture. The example in the new documentation in https://material.angular.io/components/component/card is broken as well, where it doesn't show anything at all for that element.

**Comment by mckenzielong** [comment]
Looks like this is a bug against material2.  The repo for that project is located here: https://github.com/angular/material2

**Comment by RedFour** [comment]
oops, thank you.
