### ISSUE TITLE
md-require-match not working as expected when search returns empty set

### ISSUE THREAD

**Issue by Bobdina** [angular/material#10450]
**Actual Behavior**:
 -  `What is the issue? *`
     md-autocomplete does not go back to a valid state after being emptied
 -  `What is the expected behavior?`
     md-autocomplete goes back to a valid state

see also https://github.com/angular/material/issues/9072
solved by @DevVersion 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
     http://codepen.io/anon/pen/zZqmgy
 -  `Details:`
    1. type 'i' in the autocomplete field
    2. lose focus on the autocomplete field by clicking outside of it, do not select an item
    3. focus autocomplete field, empty field with backspace
    4. lose focus

At this point the autocomplete shows invalid, even though the searchtext is empty

**Angular Versions**: *
 -  `Angular Version:` 1.5.11
 -  `Angular Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *`56.0.2924.87 (Official Build) (64-bit)
 -  `OS: *`windows

**Comment by johnjesse** [comment]
I have a similar issue, interestingly on your codepen, if you change the` md-require-match attribute` to `"true"` it clears the error when the search text is empty, see

**Comment by Splaktar** [comment]
Removing `md-min-length` doesn't change the behavior, so it doesn't appear to be related.

**Comment by Splaktar** [comment]
The docs for `md-require-match` say:
> `boolean` - When set to true, the autocomplete will add a validator, which will evaluate to false, when no item is currently selected.

You are trying to set the value like it is an `expression`, like `md-search-text`, instead of a `boolean`.

Here's an updated [CodePen](https://codepen.io/Splaktar/pen/qxgpBY?editors=1011) that seems to work via the following syntax: `md-require-match="'{{self.countrySearchText && self.countrySearchText.length > 0}}'"`
