### ISSUE TITLE
mdChip:  Implement Chip component with drag, expando, and animations

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1045]
[Material Chips](https://www.google.com/design/spec/components/chips.html#) are small blocks that represent a complex entity, such as a calendar event or contact. They can contain a photo, short title string (truncated if necessary), and other brief information. Chips are easily manipulated through drag and drop. Touching them invokes the full entity view in a card or full screen view or invokes a menu of options related to that chip’s entity.

Animations invoking and invoked from chips should resize the chip material between entity views for element persistence.

![contactchips](https://cloud.githubusercontent.com/assets/210413/5543572/de364466-8abb-11e4-8c3a-e1a06bab71a2.png)

**Comment by PhilAndrew** [comment]
Just as a note,  there exists a polymer chip https://github.com/bendavis78/paper-chip

**Comment by PaulMougel** [comment]
Duplicate of #74? Also, the milestones don't match between the two issues.

**Comment by ilanbiala** [comment]
@PaulMougel yes this seems like a dupe.

**Comment by BogdanRusinka** [comment]
I've written a chips-component, check it out https://github.com/B1naryStudio/md-chips

**Comment by EladBezalel** [comment]
@BogdanRusinka Its awesome!
but i think you should add keyboard support and make it more "material" when hovering a chip
