### ISSUE TITLE
ngChecked Bug with md-checkbox

### ISSUE THREAD

**Issue by drinkspiller** [angular/material#10468]
I'm experiencing different behavior with an md-checkbox than with a vanilla checkbox and expected they would work the same. The [master/slave example from the ngChecked page](https://docs.angularjs.org/api/ng/directive/ngChecked) does not work when the checkboxes are md-checkbox but does work when <input type="checkbox" ...> is used.

Here is a [Plunk with the example from the ngChecked documentation but with the ngMaterial dependencies added](https://plnkr.co/edit/gccAaC56xl9HHRm8GeID?p=preview). It behaves as expected — the 'slave' checkbox can be toggled whether or not the 'master' checkbox is selected.

Now here is a [Plunk with the same example but both instances of <input type="checkbox" ...>  have been changed to <md-checkbox> elements](https://plnkr.co/edit/xFd6V4BulOHKwnPrAKb5?p=preview) (with closing tags). **Note that the 'slave' checkbox does not toggle its state when clicked, irrespective of whether the 'master' is selected or not.**

**Comment by ThomasBurleson** [comment]
@drinkspiller - master-to-slave works for both versions. Independent slave selection does NOT work for `md-checkbox`:

![screen shot 2017-03-07 at 1 37 38 pm](https://cloud.githubusercontent.com/assets/210413/23674417/74c0d122-033b-11e7-8992-404468493372.png)

![screen shot 2017-03-07 at 1 38 18 pm](https://cloud.githubusercontent.com/assets/210413/23674420/78dc592a-033b-11e7-83a9-b5977763a87a.png)

**Comment by ThomasBurleson** [comment]
@topherfangio - should be  a fun, easy one to resolve.

**Comment by busiq** [comment]
Hey, I just pushed the easiest possible solution here https://github.com/angular/material/pull/10472, let me know what do you think.
