### ISSUE TITLE
GridList with ng1.6.x has rendering issues

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#10460]
#### 

Gridlist with ng1.5.x:

![screen shot 2017-03-06 at 3 36 54 pm](https://cloud.githubusercontent.com/assets/210413/23631043/d71f5334-0282-11e7-9dc1-7c368792ae48.png)

#### Gridlist with ng1.6.2:

![screen shot 2017-03-06 at 3 34 49 pm](https://cloud.githubusercontent.com/assets/210413/23631059/e5657d42-0282-11e7-8eaa-8dc9f85b4006.png)

**Comment by ThomasBurleson** [comment]
@EladBezalel - Perhaps this is an icon issue.

**Comment by topherfangio** [comment]
I can't seem to reproduce. @EladBezalel can you?

**Comment by EladBezalel** [comment]
Can't reproduce - [codepen with 1.6.2](http://codepen.io/EladBezalel/pen/PpWbgL)
