### ISSUE TITLE
input: ng-messages animation errors

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#10461]
![screen shot 2017-03-06 at 3 44 25 pm](https://cloud.githubusercontent.com/assets/210413/23631360/d040ab52-0283-11e7-9c18-d65749c19a4a.png)

<img width="1052" alt="screen shot 2017-03-06 at 3 44 11 pm" src="https://cloud.githubusercontent.com/assets/210413/23631364/d48ec072-0283-11e7-82ae-ae42c922da34.png">

Visible with ng 1.5.x and 1.6.x

**Comment by EladBezalel** [comment]
Also happens on [1.5.5](http://codepen.io/EladBezalel/pen/bqggWV) - repro on [1.6.2](http://codepen.io/EladBezalel/pen/OpWbeY) aswell

@topherfangio as the one who wrote this code, do you know what's going on?

**Comment by rw-bkew** [comment]
I am also seeing this in 1.1.3

**Comment by mckenzielong** [comment]
I've also seen the opposite where input errors can stick, _however I am having trouble duplicating in a codepen_.  Here is a tiny code pen for demonstrating something similar to what @ThomasBurleson  is showing:

https://codepen.io/mckenzielong/pen/qmZVyo

1. Show field
2. enter an invalid number (say 500)
3. click submit
4. hide field and reshow

**Comment by tamsler** [comment]
We are seeing this issue as well:
using:
Angular Material v1.1.4
Angular v1.6.4

**Comment by Splaktar** [comment]
@AnushaputtaUI no one has investigated this issue yet. If you'd like to look into it, I'd like to know what you find. If you can find a solution, then sending a PR would be great.

Verified that it still exists with AngularJS 1.7.0 and AngularJS Material 1.1.9 in this [updated CodePen](https://codepen.io/Splaktar/pen/gKmYKW).

**Comment by marosoft** [comment]
This was implemented in ce5f7c2 

This was to fix a problem with displaying the messages.
However I am not sure why this introduced showing warnings when ng-messages are not provided.

There are situations like the one provided in the demo where you just would like to highlight the problematic filed but without showing any extra error messages.

I believe the fix required was in 4 lines (the rest was not really needed):
https://github.com/angular/material/commit/ce5f7c28770bd928afd31a33ee33000deb3311e6#diff-da06475ed96460fbcb944d6f1f31748aR1059

I will test it.

**Comment by marosoft** [comment]
Adding [CodePen](https://codepen.io/marosoft/pen/LrMMwp) with my fix applied.

**Comment by marosoft** [comment]
Adding [CodePen](https://codepen.io/marosoft/pen/qKLgZZ) for the other issue #9468. Fix for the autocomplete introduced the warnings in the console. This is to show that the fix itself is still working fine.
