### ISSUE TITLE
mdDialog: not closing in Safari

### ISSUE THREAD

**Issue by flavioreis13** [angular/material#1046]
My mdDialog isn´t closing on Safari 5.1.7 for Windows, but it works on Chrome, IE and Firefox. Please help. Thanks

```html
<html>
<head>
    <!-- Angulars Material CSS using RawGit to load directly from `bower-material/master` -->
    <link rel="stylesheet" href="//rawgit.com/angular/bower-material/master/angular-material.css">
    <!-- Angular Material Dependencies -->
    <script src="//cdn.jsdelivr.net/hammerjs/2.0.4/hammer.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-aria.js"></script>
    <!-- Angular Material Javascript using RawGit to load directly from `bower-material/master` -->
    <script src="//rawgit.com/angular/bower-material/master/angular-material.js"></script>
</head>
<script type="text/javascript">
angular.module('app', ['ngMaterial'])
    .controller('AppCtrl', function($scope, $mdDialog) {
        $scope.showAlert = function(ev) {
            $mdDialog.show(
                $mdDialog.alert()
                .title('This is an alert title')
                .content('You can specify some description text in here.')
                .ariaLabel('Password notification')
                .ok('Got it!')
                .targetEvent(ev)
            );
        };

    });
</script>
<body>
    <div ng-app="app" ng-controller="AppCtrl">
        <md-button class="md-primary" ng-click="showAlert($event)">
            Alert Dialog
        </md-button>
    </div>
</body>
</html>
```

**Comment by epelc** [comment]
@flavioreis13 Hasn't safari been discontinued for windows?

**Comment by ilanbiala** [comment]
@epelc yep. @flavioreis13 why not use a different browser?

**Comment by epelc** [comment]
I think this should be closed if it's only occurring in safari on windows. It doesn't seem like angularjs or angular-material intends to support safari for windows. After all apple even ditched it and it hasn't been updated in for ever.

**Comment by flavioreis13** [comment]
Yes Safari has been discontinued for Windows, but the Demo page (https://material.angularjs.org/#/demo/material.components.dialog) works fine.

Btw, on iOS is working.

**Comment by ilanbiala** [comment]
iOS uses a much newer rendering engine.

**Comment by epelc** [comment]
I'd assume it'd follow the same rules as angularjs with versions of ie that are no longer supported. They aren't actively breaking things on purpose but they also aren't spending time fixing them.

Also I would highly recommend against using safari for windows. Even at the time it was abandoned their were over 100 security issues and that was 2 years ago.

http://www.maximumpc.com/article/news/safari_windows_abandoned_apple_leaving_users_vulnerable_no_warning

**Comment by ThomasBurleson** [comment]
Not supported.
