### ISSUE TITLE
md-tooltip slow/unresponsive in 1.1.3

### ISSUE THREAD

**Issue by leosco** [angular/material#10467]
https://material.angularjs.org/latest/demo/tooltip

Not sure what was the logic behind slowing down the transition time for `md-tooltip` to appear, but even with the default delay of 0ms, it's still pretty drastic in my opinion. I don't think it looks quite as nice as before and mousing over multiple buttons close together (in a toolbar for example) or even the same button in quick succession causes it to not appear sometimes. This might give the user the impression that the template is slow or glitchy. 

I've also noticed that when having buttons close to the edge of the viewport, the offset for the tooltip is far more exaggerated than necessary and with small icon buttons side by side, it can look a bit messy. 

Compare it 1.1.1 https://material.angularjs.org/1.1.1/demo/tooltip 
where it's super quick, responsive and smooth, and the default delay actually looks like it's closer to 0ms than what it is in 1.1.3.

**Comment by henrymana** [comment]
What web browser are you using? It looked OK for me in chrome... I see there were quite a few changes to the mdtooltip in 1.2 (including refactoring to use mdPanel). https://github.com/angular/material/blob/master/CHANGELOG.md

**Comment by leosco** [comment]
I'm also using Chrome. Don't get me wrong, it's not *horrible* but comparing it to the previous release, it does appear less responsive to me.

**Comment by EladBezalel** [comment]
@leosco you might be right,
The [specs](https://material.io/guidelines/components/tooltips.html#tooltips-interaction) says it should have 150ms to appear
