### ISSUE TITLE
Breakpoints not working when just Layout CSS?

### ISSUE THREAD

**Issue by jfyzhao** [angular/material#10463]
Hi,

Is it possible to use just the Angular Material Layout API if working on a project not using Angular?

I noticed that when I only included the css files from https://github.com/angular/bower-material/tree/master/modules/layouts that everything works as expected, except breakpoints (e.g. somethinng like `<div layout-gt-xs="row" layout-xs="column">...</div>` will lead to a row layout in both mobile and desktop views.

The files I've included from the build are:
angular-material.layout-attributes.min.css
angular-material.layouts.ie_fixes.css
angular-material.layouts.min.css

**Comment by ThomasBurleson** [comment]
*  If you are build with AngularJS (1.x), you can use the above CSS files which must be manually applied. The ngM1  Layout directives are embedded within `angular-material.js`. These directives convert the layout API to classnames and apply those to the hosting element. Without ngM1, you must manually assign the classnames to your elements.
*  If you are building with Angular (2 or higher) use [@angular/flex-layout](http://github.com/angular/flex-layout). This library is standalone and can be used with any Angular application with or without Material2.

**Comment by jfyzhao** [comment]
Just to clarify, I want to use this layout API without using Angular in my app. Adding angular-material.js did not resolve that issue for me with the breakpoints.
