### ISSUE TITLE
autocomplete: scroll doesn't return to top when dropdown is opened again

### ISSUE THREAD

**Issue by ghost** [angular/material#10479]
I'm trying to use md-autocomplete with md-chips scroll and it all works fine but after picking an item
from the drop down of the autocomplete when I start tyiping a new item to look for
the drop down scroll starts from the same position it last ended.
how do I make it start from the top of the drop down every time???

I've added my project if any one has a fix thank you
[good-chips.zip](https://github.com/angular/material/files/831305/good-chips.zip)

**Comment by ruivbi** [comment]
![capture](https://cloud.githubusercontent.com/assets/26305006/23755492/2ebde84a-04e9-11e7-8921-882a97f1f332.PNG)
 I added a picture of the problem

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further.

**Comment by pawelbujna** [comment]
I think it may be related to the md-autocomplete itself: https://material.angularjs.org/latest/demo/autocomplete
Open first autocomplete, scroll down, close, open once again. Scroll stays at the place you've last left it. Is there a way to scroll it to top for example on close?

**Comment by BrendanDcruze** [comment]
I am facing the same issue.
Is there any workaround for this.??

**Comment by Splaktar** [comment]
Can reproduce this in the following [CodePen](https://codepen.io/Splaktar/pen/zRMBwP?editors=1010) based on the docs and 1.1.7.

**Comment by marosoft** [comment]
Hi @Splaktar 

Please see the [CodePen](https://codepen.io/marosoft/pen/QzQmmX) with my fix.
I could not see any CodePen with the autocomplete and chips I could use to reproduce the original issue.

**Comment by Splaktar** [comment]
@marosoft yeah, sorry, it looks like I either didn't save or I linked the wrong CodePen above. I've removed the link.

**Comment by Splaktar** [comment]
Here's a [CodePen](https://codepen.io/Splaktar/pen/roJvxm) that demonstrates the issue without chips based on `1.1.11`.

**Comment by Splaktar** [comment]
@marosoft your fix seems to work. Please go ahead and open a PR.

I was not able to reproduce the problem with [autocomplete chips](https://codepen.io/Splaktar/pen/pqaVbE?editors=1010#0) either.
