### ISSUE TITLE
Bower/Angular 1.5.8 Issue with Sub Dependency Aria 1.6.3

### ISSUE THREAD

**Issue by MatthewVita** [angular/material#10475]
Hello all. Just leaving this here in case someone runs into the same issue. Feel free to close it.

Our team is using bower and we're using `"angular": "1.5.8"` and `"angular-material": "1.0.9"`. However, it seems as though material pulling down a version of `angular-aria` (1.6.3 ?) that is incompatible with our version of angular.

The fix was adding `"angular-aria": "1.5.8"` to the root node of the dependencies.

Thanks,
Matthew

**Comment by LoganLehman** [comment]
Awesome. Glad you can override. Truly it seems as though the module.info() call was all that was utilized from 1.6. Seems odd that they would be willing to break everyone's project <=1.5.9 just for that.

**Comment by MatthewVita** [comment]
Yep, `.info` is critically important xD

**Comment by lennonjesus** [comment]
Here, we have a problem with angular-material 1.1.1. Build broked. :/

**Comment by adam-back** [comment]
Also breaks Angular 1.4.8. Thanks for the help @MatthewVita!

**Comment by MatthewVita** [comment]
Btw, my coworker @ShaneChesnutt and I tried using the `overrides` config for this, but got nowhere. Not that my suggested solution is nothing more than a workaround.

**Comment by Narretz** [comment]
Are you guys using jspm?

**Comment by ShaneChesnutt** [comment]
No, we are using bower.

**Comment by Narretz** [comment]
The material bower file is too lax in this case: https://github.com/angular/bower-material/blob/v1.0.9/bower.json

**Comment by ThomasBurleson** [comment]
The AngularJS Material (v1.x) team only supports the latest release of ngM1. We do not support older versions of ngM1. Only ngM v1.1.3.

If a developer installs (npm or bower) ngM, then v1.1.3 will be installed and ngM1.x has
 a) bower dependencies on ng 1.6.3.
 b) npm peer dependencies on ng 1.6.3

Per the AngularJS 1.x core team: It is not supported to use non-matching version and there can always be things that break. So combinations like `angular: 1.5.8 + angular-aria:1.6.3` are not supported.

Closing as "not a Material issue".

**Comment by mtrogers** [comment]
Just a heads up to people who might be smashing their head in with this error: _clear your browsing data_.

I had consistent versions (angular 1.6.3) across the board, and I was still hitting the errors.
In the browser, on inspecting the angular-aria.js code, it was listing the .info function as looking for kept listing angular "1.6.4"... wtf?

Clearing the browser data and refreshing solved the problem.

**Comment by p-rogulski** [comment]
@MatthewVita Thanks!
