### ISSUE TITLE
Error concatenating angular-material.js

### ISSUE THREAD

**Issue by janesconference** [angular/material#1047]
Latest version of material on bower, gives a `Uncaught TypeError: object is not a function` in the minified code of angular-material.js. Minification is the default one of yeoman angular generator (uglifyjs + ngMin) or uglifyjs + ngAnnotate.

**Comment by epelc** [comment]
@janesconference Have you considered using webpack instead?

**Comment by janesconference** [comment]
@epelc - the issue is closed for me: I just needed to switch the concatenation order. Btw, I'm leaving it open because it could be interesting to know there is an issue concatenating (or including) the js file after other libraries.
