### ISSUE TITLE
md-nav-bar is lost in the last version of Angular Material?

### ISSUE THREAD

**Issue by lukecorf** [angular/material#10483]
I try to use md-nav-bar in my Angular 2 aplication but the navigator doesn't recognize this item. 

I need use tabs for angular? Or the navbar item change?

**Comment by ThomasBurleson** [comment]
[Angular Material 2.x](https://github.com/angular/material2) has a different repository and issue list from [AngularJS Material 1.x](https://github.com/angular/material/).

Material 2 does not yet have a NavBar.
Material 1 is not officially supported with ngUpgrade + Angular (2.x).

**Comment by lukecorf** [comment]
Thanks
