### ISSUE TITLE
bower-material should use ~ instead of ^ for angular dependencies

### ISSUE THREAD

**Issue by iiredalert** [angular/material#10484]
**Actual Behavior**:
 -  `What is the issue? *`Your project depends on angular version 1.5.x and angular-material 1.1.3.  Before the angular 1.6.x release, build worked as expected.  After the 1.6.x release, build brings 1.6.x versions of material's angular dependencies (animate, aria & messages) which introduce breaking changes not compatible with angular 1.5.x.  Now project is forced to explicitly define those dependencies.
 -  `What is the expected behavior?`Depending on angular-material should not break your app out of the blue when a new angular version is released.

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.7
 -  `AngularJS Material Version:`1.1.3

**Additional Information**:
 -  `Build Environment: *`bower

**Comment by ThomasBurleson** [comment]
Fixed in https://github.com/angular/bower-material/blob/master/package.json#L8-L11
