### ISSUE TITLE
can't set tomorrow date as default value in datepicker

### ISSUE THREAD

**Issue by claubanu** [angular/material#10486]
Hi there!
My issue: the user must select two dates, the beginning and the end of the interval. By default, first option is today and the second option (the end of the interval) should be tomorrow (by default, for a better user experience).
Can somebody, please, help me set tomorrow as default value for the second date option with Angular Material Datepicker?
Thanks in advance!

**Comment by octavian-mirica** [comment]
Try to set the second date's default (tomorrow) in your code:

var startDate = new Date(); // today
var endDate = new Date();
endDate.setDate(endDate.getDate() + 1); // add 1 day, i.e. endDate = tomorrow

Then bind these variables to md-datepicker's ng-model property.

**Comment by claubanu** [comment]
@octavian-mirica 
Thanks for the suggestion but unfortunatelly it isn't working for me.

In controller, the code looks like this (quite similar to my approach for setting "tomorrow date"):
var startDate = new Date(); 
var endDate = new Date();
endDate.setDate(endDate.getDate() + 1); 

$scope.dataIn = startDate;	
$scope.dataOut = endDate;	

The output into: <md-datepicker ng-model="dataIn" md-placeholder="Enter date"></md-datepicker> is today.
Can't figure out what's wrong with it...

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further.

**Comment by ThomasBurleson** [comment]
Closing as invalid without demo.
