### ISSUE TITLE
Add new tab with md-text-float

### ISSUE THREAD

**Issue by truyet** [angular/material#1048]
While i add new tab used to button Add Item, text float lable issue : 

![issue](https://cloud.githubusercontent.com/assets/710057/5549297/e3bff3ec-8bb9-11e4-9403-76afe195fd39.png)

text float don't have data.

**Comment by ThomasBurleson** [comment]
@robertmesserle - sounds like a tab addition is not properly announce new 'tab activation' ?

**Comment by truyet** [comment]
Yes, I create new tab, but i don't active tab. Then, the bug happens while I click to tab.
I try to the new tab and activate it, the bug doesn't happen

**Comment by ThomasBurleson** [comment]
@robertmesserle - simplified version http://plnkr.co/edit/WYv3j1tLr7ubxyU34YXy?p=preview
