### ISSUE TITLE
md-autocomplete not see in dark template

### ISSUE THREAD

**Issue by truonghoangnguyen** [angular/material#10489]
md-autocomplete not see in dark template screen :  
![image](https://cloud.githubusercontent.com/assets/1657877/23855715/62048522-0829-11e7-9cfe-2e74e996399c.png)
Setup:
`$mdThemingProvider.theme('docs-dark').backgroundPalette('grey').dark();`

Form:
```
<md-content md-theme="docs-dark" layout-padding>
	<div>
		<md-subheader>Nhập hóa đơn</md-subheader>
		<form name="lineForm" ng-submit="$ctrl.addInvoiceLine()" novalidate layout-gt-sm="row" layout="column">
			<md-input-container class="md-block" flex-gt-sm="20" flex="100">
				<md-autocomplete
					name="product"
							placeholder="Vui lòng chọn sản phẩm">
					<md-item-template>
					</md-item-template>
				</md-autocomplete>
			</md-input-container>
			<md-input-container class="md-block" flex-gt-sm="10" flex="100">
				<label>Đơn vị tính</label>
				<md-select ng-model="$ctrl.invline.unit_raw" name="unit" required >
					<md-option ng-repeat="unit in $ctrl.productUnits" value="[[unit]]">
					[[unit.name]]
					</md-option>
				</md-select>
				<div class="errors" ng-messages="productForm.unit.$error">
					<div ng-message="required">Vui lòng nhập đơn vị</div>
				</div>
			</md-input-container>
 ...
```
**Actual Behavior**:
 -  `What is the issue? md-autocomplete not see in dark template`
 -  `What is the expected behavior? : md-autocomplete after selected must see content`

**AngularJS Versions**: *
 -  `AngularJS Version: 1.6.1`
 -  `AngularJS Material Version: 1.1.3`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate further.

**Comment by ThomasBurleson** [comment]
Closing as invalid without demo.
