### ISSUE TITLE
registerStyles generated multiple styles

### ISSUE THREAD

**Issue by je3f0o** [angular/material#10485]
**Actual Behavior**:
 -  Hello, I'm new for material design. Only third day playing it. I just want to register a simple dynamic class
```javascript
$mdThemingProvider.registerStyles(`
  [md-theme="THEME_NAME"] .md-accent-bg {
     color :{{accent-contrast}};
     background-color :{{accent-color}};
  }
`);
```
 -  I was expected new style tag generated contains
```
[md-theme="default"] .md-accent-bg {
  color: rgb(255,255,255);
  background-color: rgb(255,64,129);
}
```

 - But I got multiple style tags generated and oddly all generated styles are different from each others... Which is unuseable. Same css selectors overriding each other and result is not correct value.

![screen shot 2017-03-12 at 9 31 48 pm](https://cloud.githubusercontent.com/assets/1854769/23832357/0ec81480-076d-11e7-9df8-66e959aae230.png)

**AngularJS Versions**: *
 -  `AngularJS Version: 1.6.1`
 -  `AngularJS Material Version: 1.1.3`

----
I created a plunker [Demo](http://plnkr.co/edit/jiVQQYMkSN53j4ZwTI3s).

**Comment by DevVersion** [comment]
Using `.md-THEME_NAME-theme` instead of `[md-theme="default"]` will do the trick.

See http://plnkr.co/edit/YrrJt9K0GbC2IUS71LsS?p=preview
