### ISSUE TITLE
md-autofocus="md-autofocus" do not trigger focus

### ISSUE THREAD

**Issue by Head** [angular/material#10482]
**Actual Behavior**:
 -  `What is the issue? *`
having only `md-autofocus` in a pug file results to be `md-autofocus="md-autofocus"` in the html inspected code. That's not triggering the autofocus.

 -  `What is the expected behavior?`
From your test file: // By default, we assume an undefined value for the expression is true
`md-autofocus` should be `undefined` and should trigger.

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` latest
 -  `OS: *` Win 10

**Comment by EladBezalel** [comment]
Please provide codepen so we can investigate further.

**Comment by Head** [comment]
Codepen is messing up with the md-autofocus.
Just take any site where you have `md-autofocus` and set it to: `md-autofocus="md-autofocus"`

**Comment by EladBezalel** [comment]
`md-autofocus="md-autofocus"` isn't intended to work, in the [api](https://material.angularjs.org/latest/api/directive/mdAutofocus) we're expecting a boolean
