### ISSUE TITLE
Select component doesn't match Material Design spec?

### ISSUE THREAD

**Issue by maciaszczykm** [angular/material#10494]
**Actual Behavior**:
 -  `What is the issue? *` https://material.angularjs.org/latest/demo/select doesn't match https://material.io/guidelines/components/buttons.html#buttons-dropdown-buttons spec.
 -  `What is the expected behavior?` Currently chosen item should have blue color, but background should be white. Hover item should have gray background.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` n/a
 -  `Details:` Just take a look on demo from https://material.angularjs.org/latest/demo/select and https://material.io/guidelines/components/buttons.html#buttons-dropdown-buttons spec.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.2
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` all
 -  `Browser Version: *` all
 -  `OS: *` Linux
 -  `Stack Traces:` n/a

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by sdesmond** [comment]
This is working as expected.  The gray background applies to the item being hovered over _and the item that has focus_.  If you open the select and press up/down you'll see that gray background moves to the currently selected item.  This is for keyboard navigation.

**Comment by maciaszczykm** [comment]
@sdesmond Ahh, okay. It seems a bit strange, that gray background doesn't follow mouse too (only keyboard). Thanks.

**Comment by sdesmond** [comment]
I see it following the mouse on hover as well (using Chrome)

**Comment by maciaszczykm** [comment]
@sdesmond I've misspoken. It follows mouse (CA), but it's also visible on current state (AZ):

![image](https://cloud.githubusercontent.com/assets/2823399/24034680/9949c030-0af2-11e7-8b60-ffd4034dc619.png)

**Comment by maciaszczykm** [comment]
I'm using Chrome as well.
