### ISSUE TITLE
md-tooltip broken with angular-material 1.1.3 + angular-message 1.5.11

### ISSUE THREAD

**Issue by simonemazzoni** [angular/material#10490]
**Actual Behavior**:
 -  `What is the issue?` md-tooltip not displayed
 -  `What is the expected behavior?` md-tooltip displayed

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.11 (imposed by the fact that angular-material 1.1.3 does not work with angular 1.6.x)
 -  `AngularJS Material Version:`  1.1.3

**Additional Information**:
 -  `Browser Type:` Chrome
 -  `Browser Version:` 56
 -  `OS: ` macOSsierra/Windows10

----

Hello,
it looks like that `angular-message v1.5.11` breaks `md-tooltip` with `angular-material v1.1.3`.
I don't know exactly where the problem is, since I discovered it 5 minutes ago.
Notice that with `angular-message v1.5.9` works properly, so I guess is an `angular-material` problem.

Any idea?

**Comment by EladBezalel** [comment]
Actually that sounds like the problem is with `angular-messages`,
As this issue doesn't meet out issue standards i still want you to provide an reproduction of this issue so we can investigate further.

**Comment by simonemazzoni** [comment]
Hello @EladBezalel 
It turns out that it was my fault. I was including the wrong scss version statically from a CDN.
I was using angular-material.scss from version 1.1.1 instead of the one from versone 1.1.3

Sorry about that, but it wasn't that easy to debug on my project. :)

I'll close the issue.
