### ISSUE TITLE
Uncaught TypeError: y.module(...).info is not a function

### ISSUE THREAD

**Issue by surjit** [angular/material#10505]
**Actual Behavior**:
 -  `What is the issue? *` Uncaught TypeError: y.module(...).info is not a function
 -  `What is the expected behavior?` clean console

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/surjit/pen/aJVGym
 -  `Details:`  please see console

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.1
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 57.0.2987.110
 -  `OS: *` Windows
 -  `Stack Traces:`  angular-animate.js:4123Uncaught TypeError: y.module(...).info is not a function
    at angular-animate.js:4123
    at angular-animate.js:6
angular-aria.min.js:6 Uncaught TypeError: p.module(...).info is not a function
    at angular-aria.min.js:6
    at angular-aria.min.js:13
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by henrymana** [comment]
Angular 1.6 support is in progress... see related work for this: https://github.com/angular/material/issues?q=is%3Aissue+is%3Aopen+1.6+label%3A%22needs%3A+Angular+1.6+support%22

**Comment by mgol** [comment]
You're loading different versions of AngularJS, Animate & Aria modules; you need to use 1.6.3 for all of them; loading different ones is not supported.

There's no issue to fix here and it's not relevant to AngularJS 1.6 support.

**Comment by rev-robert** [comment]
I am getting the issue while all libraries are the same version:

**Comment by Splaktar** [comment]
@rev-robert please open a new issue, with a CodePen reproduction, and reference this issue in the description.
