### ISSUE TITLE
md-select closes suddenly and unexpectedly

### ISSUE THREAD

**Issue by jmazin** [angular/material#10503]
**Actual Behavior**:
 -  `md-select` select box closes suddenly

**CodePen** (or steps to reproduce the issue): *
 -  [CodePen Demo](http://codepen.io/jmazin/pen/bqYgXj)
 -  select 'sword' in the first dropdown => the box will suddenly close
- **n.b.**  using `ng-show` instead of `ng-if` works around the issue

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5.
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` 56.0.2924.87
 -  `OS: *`  OS X 10.11.6 (15G31)
 - using `ng-show` instead of `ng-if` works around the issue

**Comment by henrymana** [comment]
This is probably not a defect: ng-if changes the underlying DOM (https://docs.angularjs.org/api/ng/directive/ngIf) but ng-show does not (https://docs.angularjs.org/api/ng/directive/ngShow). If the DOM of the underlying md-card contents change I would expect the page to refresh and the md-select to close... imo

**Comment by EladBezalel** [comment]
I think that happens because the DOM around it changes (ng-if creates new instance of the element unlike ng-show which hides and shows the element), Imo this is not a bug, something is happening on the page and the select reacts to it.

**Comment by jmazin** [comment]
Figured something like that.  Thanks for taking the time to look.
