### ISSUE TITLE
ng-click not fired when clic on mobile device

### ISSUE THREAD

**Issue by supportQuadra** [angular/material#10501]
**Actual Behavior**:
 -  `What is the issue? sometimes we need to double click to fire ng-click !`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): use website angular-material on mobile device, exemple tabs, sometimes, the tab not change when we click
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: 1.5.8
 -  `AngularJS Version: 1.5.8`
 -  `AngularJS Material Version:1.1.1`

**Additional Information**:
 -  `Browser Type: crosswalk`
 -  `Browser Version: 2.1.0`
 -  `OS: Android`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EladBezalel** [comment]
This bug report doesn't meet our issue standards, please provide a codepen and explain your issue further.
