### ISSUE TITLE
Closure core.css contains hundreds of duplicate rules

### ISSUE THREAD

**Issue by shyndman** [angular/material#10504]
**Actual Behavior**:
 -  `What is the issue? *`
I'm seeing 42-44 of each of the following rules (all permutations):
`.layout-{row,column} > .flex-{33,66}`
`.layout-{row,column} > .flex-{xs,sm,gt-sm,md,gt-md,lg,gt-lg,xl}-{33,66}`

 -  `What is the expected behavior?`
One of each!

**AngularJS Versions**: *
 -  `AngularJS Material Version:`
1.1

**Comment by jelbourn** [comment]
@ThomasBurleson can you look into this?

**Comment by shyndman** [comment]
Doesn't look like this was an issue back in 1.0.

**Comment by ThomasBurleson** [comment]
I will I.

**Comment by shyndman** [comment]
Hey @ThomasBurleson,

Want me to take a look at this?

**Comment by ThomasBurleson** [comment]
@shyndman - yes please. But only check based on code in HEAD.
