### ISSUE TITLE
Cannot blur md-autocomplete on touch device

### ISSUE THREAD

**Issue by arubinoff** [angular/material#10518]
**Actual Behavior**:
When the autocomplete input is selected and the autocomplete dropdown opens on a touch device, it is impossible to blur the input/close the dropdown by tapping outside of the input. The only way to close the dropdown is to select one of the items.

**Demo** (or steps to reproduce the issue): *
Reproducible on the md-autocomplete demo page: https://material.angularjs.org/latest/demo/autocomplete
Steps to reproduce:
1. Select the autocomplete input
2. Tap outside the input

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5
 -  `AngularJS Material Version:` 1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 56.0
 -  `OS: *` Android 7.1.1, Pixel

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by jithureddy** [comment]
I have added similar issue #10521

**Comment by jithureddy** [comment]
I can see that  md-scroll-mask  is not getting removed if do on blur or click elsewhere on the page, after going through DOM
![image](https://cloud.githubusercontent.com/assets/5911189/24145796/d8413f84-0e58-11e7-96ef-062f7c84fc4e.png)

**Comment by maghidini** [comment]
any update on this issue for Angular Material 1.1.6 version?

**Comment by Splaktar** [comment]
It looks like this is working properly on Chrome for Android since AngularJS Material 1.1.5.

**Comment by Splaktar** [comment]
This was fixed in https://github.com/angular/material/commit/baa869a.
