### ISSUE TITLE
Tooltip not visible in Firefox with Angular Material 1.1.3

### ISSUE THREAD

**Issue by raminenisk2003** [angular/material#10514]
**Actual Behavior**:
 -  `What is the issue? *` Tooltip is not visible in firefox
 -  `What is the expected behavior?` Tooltip should be visible when button is focused or hovered

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/1.1.3/demo/tooltip
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.5
 -  `AngularJS Material Version:`1.1.3

**Additional Information**:
 -  `Browser Type: *` Firefox
 -  `Browser Version: *` ESR 45.7.0
 -  `OS: *` Windows
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by bbourget** [comment]
Probably caused by the 'layout' directive on the body...

see #6891

**Comment by ThomasBurleson** [comment]
Latest builds of AngularJS Material, tooltips work with Firefox 53.0.3 (64-bit, Mac OSX)
