### ISSUE TITLE
dialog: with preserveScope refreshing scope issue

### ISSUE THREAD

**Issue by redpanda8814** [angular/material#10523]
I need to use parent scope in my dialog template, so I used 
`scope: $scope,
 preserveScope: true, ` as it mentioned in [official docs](https://material.angularjs.org/latest/api/service/$mdDialog). It worked for me, but now when I'm calling mdDialog it seems to refreshing scope (just like when page is loading), how to avoid it?
Here is my code
```
$scope.addWalletDialog = (targetEvent) => {
      $mdDialog.show({
        controller: WalletsController,
        templateUrl: 'views/wallets/add-editWalletDialog.html',
        targetEvent,
        scope: $scope,
        preserveScope: true,
        clickOutsideToClose: true
      }).then(() => {
        $scope.wallets.push($scope.wallet);
        delete $scope.wallet;
      }, () => {});
    };
```

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. Without a CodePen, StackBlitz, or GitHub reproduction we are unable to investigate your issue.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
