### ISSUE TITLE
Can't copy/paste in BitBox

### ISSUE THREAD

**Issue by bentaly** [angular/material#10522]
**Actual Behavior**:
 -  `What is the issue? *` I can't copy paste with the keyboard (ctrl+c/v) but I can using the mouse. 
All other websites not running Angular Material allowed copying. Official docs and our Angular Material powered app prevented the copy. This only happens in BitBox (Browser in the Box).
 -  `What is the expected behavior?` We should be able to let users copy paste between sites on all browsers.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.11
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type:` Browser in the box (Firefox)
 -  `Browser Version:` 4.3.2-r211 (enterprise edition) - 00105-bitbox-firefox-45.5.1esr Jan 2017 3072.zip
 - `OS:` Windows

**Comment by ThomasBurleson** [comment]
Will not support.
