### ISSUE TITLE
mdSwipe: Add demo page

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#1052]
Both [mdSwipeLeft](https://material.angularjs.org/#/api/material.components.swipe/directive/mdSwipeLeft) and [mdSwipeRight](https://material.angularjs.org/#/api/material.components.swipe/directive/mdSwipeRight) both offer demo page that redirects to: https://material.angularjs.org/#/demo/material.components.swipe
but it doesn't exist..

**Comment by ajoslin** [comment]
Instead of adding a demo page, I just made the View Demo button not show up if there's not a demo.
