### ISSUE TITLE
using md-autocomplete in md-chips is extremely slow(UI gets stuck for 5-6 seconds)

### ISSUE THREAD

**Issue by jbacalo** [angular/material#10531]
Hi,
I'm using md-autocomplete inside md-chips the following way:
`<md-content flex class="md-padding" layout="column">
            <md-chips ng-model="ctrl.selectedVegetables" md-require-match="true">
                <md-autocomplete
                        md-dropdown-items="5"
                        md-selected-item="ctrl.selectedItem"
                        md-search-text="ctrl.searchText"
                        md-items="item in ctrl.querySearch(ctrl.searchText)"
                        md-item-text="item.name"
                        placeholder="Search for a vegetable">
                    <span md-highlight-text="ctrl.searchText">{{item.name}}</span>
                </md-autocomplete>
                <md-chip-template>
                <span>
                  <strong>{{$chip.name}}</strong>
                </span>
                </md-chip-template>
            </md-chips>
        </md-content>`
I have 30000 simple items generated(containing one string field).
The filter function works fast(~3ms) but the problem is that once i type the first letter i can see that 60000 watchers are being created and after that every action on the UI takes about 2-5 seconds.
Any idea why all of those watchers are being created(and never gets cleaned up...) even though the list is virtualized(i made sure only 5 HTML elements are rendered at a time)?

Many thanks for the helpers.

Jonathan

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

We're tracking some performance issues that may be related in https://github.com/angular/material/issues/10744.
