### ISSUE TITLE
The last two releases are missing from the Google CDN.

### ISSUE THREAD

**Issue by BigBadaboom** [angular/material#10530]
The last version of Angular Material that is present in the Google CDN seems to be 1.1.1.

https://ajax.googleapis.com/ajax/libs/angular_material/1.1.1/angular-material.min.css

1.1.2 and 1.1.3 are missing.

Since the Getting Started page suggests using the Google CDN, people will be confused by the missing releases if they try to use the latest.

Also: once they are uploaded, update the Getting Stated page to use 1.1.3.  Since some of the demos in the documentation require 1.1.3. :)

**Comment by BigBadaboom** [comment]
Workaround for now: Use cloudfare CDN

https://cdnjs.com/libraries/angular-material

**Comment by tracernz** [comment]
Came here to report the same. 👍

**Comment by Trixter313** [comment]
Also applies to new 1.1.4 version

**Comment by ThomasBurleson** [comment]
Fixed.
