### ISSUE TITLE
button: horizontal padding not in sync with spec

### ISSUE THREAD

**Issue by aipsensmall** [angular/material#10535]
**Actual Behavior**:
 -  `What is the issue? *`
md-button currently has padding: 0 6px;

 -  `What is the expected behavior?`
md-button should have padding: 0 8px; per Material spec: https://material.googleplex.com/components/buttons.html#buttons-style

**Comment by Splaktar** [comment]
Yep, but [Button Spec](https://material.io/archive/guidelines/components/buttons.html#buttons-style) does indicate an `8px` internal horizontal padding.

It also specifies that buttons should have a minimum touchable height of `48px`, but we only use `36px`.

As this would break a lot of screenshot tests and cause some UIs to require layout changes, this would need to be targeted at `1.2.0` but that release is not likely to by sync'd into google3. Please let me know if you have any concerns with this.

**Comment by Splaktar** [comment]
> It also specifies that buttons should have a minimum touchable height of 48px, but we only use 36px.

I'm not going to address this as it's not straightforward to implement a touch target that is different from the element's padding. We would need to have the ripple cover 36px, but the padding go to 48px. For now, I'm deeming this too risky to do at a library level. Individual apps can override these styles if desired.
