### ISSUE TITLE
bug in show location <md-tooltip> on rtl page

### ISSUE THREAD

**Issue by mohsen77sk** [angular/material#10536]
bug in show location md-tooltip on rtl page.
Worked properly in vr 1.1.1
But had problem in vr 1.1.3

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/1.1.3/demo/tooltip
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.11
 -  `AngularJS Material Version:` 1.1.3

**Comment by EdoMagen** [comment]
+1

**Comment by zehavibarak** [comment]
+1
