### ISSUE TITLE
Displacement today in Momentjs

### ISSUE THREAD

**Issue by smahdi** [angular/material#10547]
**Displacement today**

[Demo](https://codepen.io/s-mahdi/pen/zZMLqy/)

I use **moment-jalaali** for **Persian date** but "_md-calendar-date-today_" set to Gregorian date and also for month is this problem.
year`s in view _md-calendar-year_ is Gregorian.

best rigard.
----

**Comment by ThomasBurleson** [comment]
Will not support.
