### ISSUE TITLE
Dark mode, Wrong color on form input

### ISSUE THREAD

**Issue by onigetoc** [angular/material#10544]
I use the dark theme on my testing app and the form input color are and seem to be to dark to see well button radio, select on focus. (version 1.1.3)

On focus, label texts, radio button, the search icon become black on black or grey background.

http://codepen.io/onigetoc/pen/OpaxzV?editors=1010

**Comment by ThomasBurleson** [comment]
This is not a focus-issue for the core team; you are welcome to provide a PR to fix this issue. At that time we can reopen this issue.
