### ISSUE TITLE
dialog(multiple): md-dialog-is-showing class is removed incorrectly before all dialogs are closed

### ISSUE THREAD

**Issue by JavierSalvador** [angular/material#10548]
**Actual Behavior**:
 -  `What is the issue? *`
When you open multiple "$mdDialogs" with the option multiple as true and you close one of them the "md-dialog-is-showing" class is removed.
The error could be something related to this, 
https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L821 ,
here it doesnt check anything and directly remove the class.
 -  `What is the expected behavior?`
It shouldn't be removed until the last of the "$mdDialogs" is closed.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/anon/pen/EWOpKr
 -  `Details:`
Although you can see the md-backdrop the class is still removed

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.11
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome , Safari
 -  `Browser Version: *` 57.0.2987.98 , 10.0.3
 -  `OS: *` MacOS Sierra
 -  `Stack Traces:`

**Comment by codymikol** [comment]
I'm going to take a crack at fixing this :chicken:

**Comment by Splaktar** [comment]
Can someone please test this again now that PR #11472 got merged and released in 1.1.14?

**Comment by Splaktar** [comment]
No feedback received on the request to test this with `1.1.14`. Assuming it is fixed or no longer an issue.
