### ISSUE TITLE
theming: exception is thrown when applying md-theme to md-checkbox

### ISSUE THREAD

**Issue by amitport** [angular/material#10559]
**Actual Behavior**:
 -  `What is the issue? exception is thrown when applying md-theme on md-checkbox`
 -  `What is the expected behavior? no exception`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details: apply custom md-theme to md-checkbox
$mdThemingProvider.definePalette('cutomPalette', $mdThemingProvider.extendPalette('orange', {
  '200': '#f18815'
}));
$mdThemingProvider.theme('custom').accentPalette('cutomPalette', {
  'default': '200'
 });

<md-checkbox ... md-theme="custom">..
`

**AngularJS Versions**: *
 -  `AngularJS Version: 1.6.3`
 -  `AngularJS Material Version: 1.1.3`

**Additional Information**:
 -  `Browser Type: chrome`
 -  `Browser Version: 56`
 -  `OS: win7`
 -  `Stack Traces:
angular.js:14516 expression.split is not a function
(anonymous) @ angular.js:14516
applyThemeColors @ angular-material.js:8482
(anonymous) @ angular.js:1336
$digest @ angular.js:18010
$apply @ angular.js:18280
(anonymous) @ angular.js:26974
dispatch @ jquery.js:5200
elemData.handle @ jquery.js:5008`
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
There was no reproduction demo provided here, but I put one together anyway since it was straightforward. https://codepen.io/Splaktar/pen/yLJgwxY?editors=1010

This exception no longer occurs with recent builds on AngularJS Material.
