### ISSUE TITLE
Theming in custom components

### ISSUE THREAD

**Issue by sashich** [angular/material#1055]
Hi, there
We want to apply theming to custom components (directives) but don't understand how to do it.
For example, there is __a rating distribution__ on the next picture:
![Rating Distribution](https://photos-2.dropbox.com/t/2/AABUKOGuFrphhkm80-Rs_naxfqzY1gQY021M9UZJktmhnw/12/34132754/png/1024x768/3/1419609600/0/2/Screenshot%202014-12-26%2017.51.11.png/CJKmoxAgASgBKAI/Ptx7g70BrAF_byJ7s86UjNGj1VLmF7JJjahoQ0GWjd8)

We want change colors of rating distribution on fly through JS. As you can see this component is not standard for angular material(AM), but we want use valid palettes from AM.  

It would be nice if we can append our styles to `$MD_THEME_CSS`(using provider or smth. else):
```
function generateThemes($injector) {
  var themeCss = $injector.has('$MD_THEME_CSS') ? $injector.get('$MD_THEME_CSS') : '';
```
[from here](https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L408)

**Comment by rschmukler** [comment]
We are exploring this is #2118 and #1269. Please follow those for reference.
