### ISSUE TITLE
First Item in DropDown Menu always selected

### ISSUE THREAD

**Issue by fogcitymarathoner** [angular/material#10569]
**Actual Behavior**:
 -  `What is the issue? *` First Item in md-menu is permanently selected
 -  `What is the expected behavior?` The mouse entering anyother button besides the first will unselect the first and select the entered upon button.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/fogcitymarathoner/pen/bqJPVy?editors=1010
 -  `Details:` In my implementation, when the second button is deliberately selected and when the first button is mistakenly selected, rolling the mouse wheel to scroll to lower items makes the scroll happen followed by an immediate pop to the top of the menu.  In the CodePen demo, everything works as expected, but the first element stays selected.

I wrote a directive that unselects siblings, and reselects the currently selected, however, it only works when one of the menu items is inspected.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.12
 -  `AngularJS Material Version:` 1.0.9 and 1.1.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Version 57.0.2987.110 (64-bit)
 -  `OS: *` Ubuntu 14.04.5 LTS
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd?editors=1010).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by AesSedai** [comment]
It looks like the problem stems from your HTML structure. The <md-menu-item> element has to be a direct descendent of the <md-menu-content> element. [codepen](http://codepen.io/anon/pen/mWZmdV?editors=1010)

**Comment by fogcitymarathoner** [comment]
The visual effect I want can be handled with CSS (see demo)
The menu popping back to the first menu item upon mouse wheel was fixed with a mouse wheel directive that stops event propagation

**Comment by fogcitymarathoner** [comment]
@AesSedai I corrected http://codepen.io/anon/pen/mWZmdV?editors=1010 to demonstration the problem.  I fixed the problem with css and a directive triggered by the mouse wheel to prevent the menu pop problem.
