### ISSUE TITLE
feat(dialog): controller should support AngularJS 1.6 lifecycle events

### ISSUE THREAD

**Issue by smcardle** [angular/material#10567]
The Controller attached to an $mdDialog does not honour the angularjs lifecycle events such as `$onInit` and `$onDestroy`.

This causes issues when working towards migration of our project to Angular (2/4 etc).

The issue here is that currently event listeners are registered against the `$scope` via `$scope.$on` in the $mdDialog controller.

In preparation for migration / upgrade of a significant project towards Angular (2) we are undertaking re-engineering towards Typescript / ES6 classes etc and are removing all references to `$scope` and `$rootScope` in the process. As part of this process we have introduced a new EventEmitter framework for registering and subscribing to events through the application.

All of our 'non-$mdDialog' controllers and services are able to take advantage of the Angular 1.6 `$onDestroy` lifecycle methods as a place to unregister these event handlers.

However, $mdDialog does not honour these lifecycle methods and without the use of `$scope`. There is NO WAY to deregister these events in a common way, which then causes memory leaks. 

We can of course recognize when an $mdDialog is dismissed using its various close handlers but this is messy and requires more thought and discipline on behalf of our developers, a different train of thought is needed, resulting in this not always being done or only partially done. i.e. on the OK / continue but being missed on the close / cancel.

It would be a big help for teams like ours looking at migrating away from the AngularJS 1.x stack if the angular-material team also honoured the AngularJS lifecycle events thus allowing us to use the `$onDestroy` as common solution for deregistering event handlers.

Regards

Steve

**Comment by Splaktar** [comment]
@smcardle can you please take a look at https://github.com/angular/material/issues/9259 and see if that is the same case that you are describing? Also can you reproduce this in 1.1.8?

It would be extremely helpful if you could provide a CodePen reproduction of the issue that you're seeing.

**Comment by garretwilson** [comment]
Could someone clarify what this issue is about? I thought this was fixed in #8153 .

**Comment by Splaktar** [comment]
Based on https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L648-L670, this does appear to be fixed in 1.1.5.

**Comment by jacob-robertson** [comment]
@Splaktar @garretwilson : I'm not sure this is fully resolved. There's no support for `$onDestroy` in 1.1.5. I don't think `$onChanges` makes sense, but `$doCheck` _might_.

**Comment by Splaktar** [comment]
@jacob-robertson please open a new issue with a bit more detail and some CodePen examples based on AngularJS Material `1.1.17`.

**Comment by Splaktar** [comment]
Issue https://github.com/angular/material/issues/11847 tracks the need for implementation of the `$onDestroy` hook.

**Comment by oliversalzburg** [comment]
I implemented `$onDestroy` in #11858. Similary, `$doCheck` could probably be implemented by porting https://github.com/angular/angular.js/blob/2b28c540ad7ebf4a9c3a6f108a9cb5b673d3712d/src/ng/compile.js#L3294 to mdCompile
