### ISSUE TITLE
dialog: $mdDialog.hide( dialogref, "closed" ) closes the last opened dialog instead of the specified dialog

### ISSUE THREAD

**Issue by simonemazzoni** [angular/material#10562]
**Actual Behavior**:
 -  `What is the issue? *` `$mdDialog.hide( dialogref, "closed" )` should close the specified dialog passed as first argument, but actually closes the last opened dialog.
 -  `What is the expected behavior?` Close the specified dialog!

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/simomazzoni/pen/YZgdoZ
 -  `Details:` Click on `LAUNCH DIALOGS ONE AND TWO` button, and then clink on `'ONE' ONLY` button to see that dialog 'TWO' is closed instead. Same behavior if you open dialog 'ONE' and press `'TWO' ONLY` button.
 
These behaviors lead me to think that $mdDialog.hide() arguments are ignored.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.3 (Same happens also in previous versions)
 -  `AngularJS Material Version:` 1.1.3 (Same happens also in previous versions)

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *`57.0.2987.133 (Official Build) (64-bit)
 -  `OS: *` macOSsierra
 -  `Stack Traces:`

----

Why it happens? Am I doing something wrong?

Notice that [these](https://github.com/angular/material/blob/v1.1.3/src/components/dialog/dialog.js#L641-L643) lines of code, seem to confirm my suspects.

**Comment by Splaktar** [comment]
Thank you for reporting this. You are right, this example code is incorrect as specifying the dialog reference to close is not supported:
```js
    // Close the specified dialog instance and resolve with 'finished' flag
    // Normally this is not needed, just use '$mdDialog.hide()' to close
    // the most recent dialog popup.
    function closeAlert() {
      $mdDialog.hide( alert, "finished" );
      alert = undefined;
    }
```
I've opened a PR to remove this confusing example code.

**Comment by simonemazzoni** [comment]
Hello @Splaktar,
so the issue will not be properly fixed?
I mean the behaviour of the old example has been completely removed in newer versions?
May I ask why it has been removed? It looks useful in some situations.

Thanks.

**Comment by Splaktar** [comment]
@simonemazzoni that example [was added](https://github.com/angular/material/commit/af1a5cae510f8b55be5dcaccf15bc28b7a4c4186) back in `0.7.-rc.2` (2014) prior to the 1.0 release of the library. I don't believe that it was accurate then (i.e. the functionality didn't exist) or that the functionality was ever added.

I agree that there may be some advanced usages where this could be useful in some apps. However, UX patterns that involve multiple dialogs fall outside of the Material Design spec. Here is some related guidance from [the dialog guidelines](https://material.io/archive/guidelines/components/dialogs.html):
- Avoid dialogs launching dialogs
- Dialogs should avoid: Opening dialogs from within a dialog
- Dialogs should never be obscured, either by other elements or the screen edge. 
- Dialogs always retain focus until dismissed or a required action has been taken.

[$mdPanel](https://material.angularjs.org/latest/api/service/$mdPanel) is our solution for more complex, custom dialogs. With that, you still can't do `hide(id)` or `close(id)`, but you get an [MdPanelRef](https://material.angularjs.org/latest/api/type/MdPanelRef) from each panel that you open. Then you can call close on the specific `MdPanelRef` that you want to close.

**Comment by simonemazzoni** [comment]
@Splaktar thanks a lot for the explanation. I'm aware of the material specification about multiple dialogs, but I wanted to be sure of the reason of this behaviour since the API actually allows to create multiple dialogs.
The reason sounds completely reasonable to me though.
