### ISSUE TITLE
aria-label not read by ChromeVox on md-slider component

### ISSUE THREAD

**Issue by daiches** [angular/material#10565]
**Actual Behavior**:
 -  `What is the issue? *` aria-label is not read by ChromeVox on an md-slider component, since the role="slider" is added to a different element.
 -  `What is the expected behavior?` aria-label and role end up on the same element, and the aria-label is read by ChromeVox on md-slider component.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` Just create <md-slider aria-label="test"></md-slider> and select the slider with ChromeVox.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.8
 -  `AngularJS Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 57.0.2987.133
 -  `OS: *` Linux
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by jelbourn** [comment]
The bug here is that the `role="slider"` attribute is on a child of the `md-slider` element rather than on the element itself. (and any associated attributes like `aria-valuenow` should also go on the `md-slider` element).

**Comment by ThomasBurleson** [comment]
@EladBezalel - please fix.
