### ISSUE TITLE
Strange behaviour with md-input autofilled

### ISSUE THREAD

**Issue by GiacomoK** [angular/material#10574]
Hi,
I have a strange behaviour with an md-input (password field actually) when its autofilled.

The image should explain my issue:

![screen](https://cloud.githubusercontent.com/assets/16156317/24796153/27837a9a-1b8c-11e7-9606-14f1a5d902d2.png)

Thanks.

**Comment by antoinebrault** [comment]
see https://github.com/angular/material/issues/1376

**Comment by EladBezalel** [comment]
closed as dup of #1376

**Comment by Splaktar** [comment]
@rayfoss that issue does have a Milestone. Any of the issues with `Deprecated` as the Milestone can be considered to have the label `won't fix`.

**Comment by luckylooke** [comment]
Google it self was not able to fix this :/
![Screenshot at Jun 10 07-23-32](https://user-images.githubusercontent.com/3660030/59492339-0c53e800-8e89-11e9-94d0-cc8702ce8df7.png)
