### ISSUE TITLE
Angular-Material is not working fine with requirejs and ui-router in Google Chrome only.

### ISSUE THREAD

**Issue by rahulgupta20nov** [angular/material#10579]
Hi,
I am sharing a GitHub repo [https://github.com/rahulgupta20nov/angMat-with-requirejs](url). 
I have used some lib with Angular-material, like- angular-ui-router and requirejs. 
 This is not working fine with **Google Chrome**, but working fine with Firefox and Safari. I am not getting why this some material attribute is not compiled. 
I have used Angular-material 1.1.3, If I use Angular-material 1.0.9 then above code is working fine, Even I add _angular-material.js(1.1.3)_ and _angular-material.css(1.0.9)_ then the layout is working fine and compile all angular-material attribute.

If I am uploading code in plunkr then this is also working fine.
[https://plnkr.co/edit/haL9mgXEhYf1LD2nSEjw?p=preview](url)

There have some other links, where I have tested code with ui-router and without requirejs [
https://github.com/rahulgupta20nov/angular-without-requirejs](url) then this is absolutely working fine with all browsers, Also I made an app with requirejs and without ui-router [
https://github.com/rahulgupta20nov/angular-with-requirejs ](url), then this app also working fine with all browsers.

I am not getting where is the exact problem. Which library is giving a problem. Maybe this problem comes cause of Angularjs, Angular-ui-router or requirejs. But all above possibility point problem in Angular-material, Because Application layout is successfully coming with angular-material js(1.1.3 ) & CSS(1.0.9)

https://github.com/rahulgupta20nov/angMat-with-requirejs and https://plnkr.co/edit/haL9mgXEhYf1LD2nSEjw?p=preview, code are same. But the output is not same.

**_Demo:-_**
1. Angularjs + angular-material + requirejs + ui-router - [http://54.191.187.52/angular-with-uirouter-requirejs](url)
2. Angularjs + angular-material + requirejs - [http://54.191.187.52/angular-requirejs-without-uirouter](url)
3. Angularjs + angular-material + ui-router - [http://54.191.187.52/angular-uirouter-without-requirejs](url)

**As I told**, If I use AngularMaterial-CSS-1.0.9 and AngularMaterial-JS-1.1.3, then the application is working fine, So try to find difference b/w AngularMaterial-CSS-1.0.9 and Angular-Material-CSS-1.1.3, Then I found major difference in layout CSS,
Example:-
**1.0.9-**
[flex-order] {
  -webkit-order: 0;
      -ms-flex-order: 0;
          order: 0; }

[flex-order="-20"] {
  -webkit-order: -20;
      -ms-flex-order: -20;
          order: -20; }

[flex-order="-19"] {
  -webkit-order: -19;
      -ms-flex-order: -19;
          order: -19; }
**1.1.3**
.flex-order {
  -webkit-box-ordinal-group: 1;
  -webkit-order: 0;
          order: 0; }

.flex-order--20 {
  -webkit-box-ordinal-group: -19;
  -webkit-order: -20;
          order: -20; }

.flex-order--19 {
  -webkit-box-ordinal-group: -18;
  -webkit-order: -19;
          order: -19; }

_Then,_ I replace some layout CSS-1.0.9 to CSS-1.1.3, 
Then UI is working very fine.
But I am not getting the exact solution.

**Comment by rahulgupta20nov** [comment]
[https://github.com/rahulgupta20nov/angMat-with-requirejs](url) and [https://plnkr.co/edit/haL9mgXEhYf1LD2nSEjw?p=preview](url), code are same. But output is not same.

**Comment by ThomasBurleson** [comment]
General discussion and how-to questions should be posted to the community forum areas:

*  [Google Groups](https://groups.google.com/forum/#!forum/ngmaterial)

Closing this issue as 'invalid'. Thank you.

**Comment by ThomasBurleson** [comment]
@rahulgupta20nov - In our recent Angular Material v1.1.4 release we made improvements to our Layout CSS. See the [v1.1.4 ChangeLog](https://github.com/angular/bower-material/blob/v1.1.4/CHANGELOG.md). Can you retest your issue with the latest release ?

**Comment by rahulgupta20nov** [comment]
thanks @ThomasBurleson 

plunkr [link](http://plnkr.co/edit/whxWS3crh20wp8rqGAWZ?p=preview)
Angular-AngularMaterial-angularRoute-requirejs [link](http://54.191.187.52/angular-material-requirejs-route)
Plunkr is working fine with all browser, But another link is not working with Chrome.
The code is 100% same. This is very simple code, Only I made the app with requirejs.
         
<img width="375" alt="screen shot 2017-04-26 at 21 27 44" src="https://cloud.githubusercontent.com/assets/10140041/25443985/3d4f1f6a-2ac7-11e7-8824-c47a3bbc12a8.png">

**Comment by rahulgupta20nov** [comment]
move on Webpack.
