### ISSUE TITLE
tabs: how can I disable the animation of switching tabs

### ISSUE THREAD

**Issue by MherX** [angular/material#10577]
code:

```
<md-content>
    <md-tabs md-dynamic-height="" md-border-bottom="" md-no-ink> 
      <md-tab label="one">
        <md-content class="md-padding">
          <h1 class="md-display-2">Tab One</h1>          
        </md-content>
      </md-tab>
      <md-tab label="two">
        <md-content class="md-padding">
          <h1 class="md-display-2">Tab Two</h1>          
        </md-content>
      </md-tab>      
    </md-tabs>
  </md-content>
```

Thanks!

**Comment by Chan4077** [comment]
Did you mean the ink bar at the bottom of the tab?
You have to use the `md-no-ink-bar` attribute to disable the ink bar.
```html
<md-content>
  <md-tabs md-dynamic-height md-border-bottom md-no-ink-bar>
    <md-tab label="one">
      <md-content class="md-padding">
        <h1 class="md-display-2">Tab One</h1>
      </md-content>
    </md-tab>
    <md-tab label="two">
      <md-content class="md-padding">
        <h1 class="md-display-2">Tab Two</h1>
      </md-content>
    </md-tab>
  </md-tabs>
</md-content>
```

**Comment by MherX** [comment]
@Chan4077 No, I want to disable the animation of the md-tab, in the header I don't need to disable.

**Comment by fberthel** [comment]
Hey,

I was running into the same issue today.

To disable the animation you could simply go for a pure CSS solution as long as there is no attribute:
```html
<md-content>
  <md-tabs md-dynamic-height md-border-bottom class="md-no-animation">
    <md-tab label="one">
      <md-content class="md-padding">
        <h1 class="md-display-2">Tab One</h1>
      </md-content>
    </md-tab>
    <md-tab label="two">
      <md-content class="md-padding">
        <h1 class="md-display-2">Tab Two</h1>
      </md-content>
    </md-tab>
  </md-tabs>
</md-content>
```

and then in CSS:
```CSS
md-tabs.md-no-animation md-tab-content {
    transition: none;
}
```

To also disable the animation of the ink-bar:
```CSS
md-tabs.md-no-animation md-ink-bar {
    transition: none;
}
```

For completeness:
You could also disable the translate3d property, but it transforms to (0, 0, 0) anyways, so you don't need it necesserily, also check the render-specific transitions (e. g. webkit-transition), although I don't feel like any barely modern Browser (besides some IE or Safari maybe) uses the renderer-prefixed properties.
Just open the DevTools and inspect the styles of the md-tab-content nodes.

**Comment by izabelacdsa** [comment]
@fberthel 

Hi there!

Thank you so much! Your comment was very useful to me.

Besides, it solves a Iphone Bug that I was trying to fix a long.... time.

=D

**Comment by anurbol** [comment]
Agree, thanks for the solution @fberthel. Why not close this issue?

**Comment by Splaktar** [comment]
The posted workaround would be the best way to do this.

Of course if you don't want animations and you want better performance for larger tab contents, then `md-nav-bar` is the way to go.

**Comment by depiction** [comment]
@fberthel's solution didn't work for me in Angular 5. I also tried the following:

```
::ng-deep {
    .mat-tab-body {
        transition: none !important;
        transform: none !important;

        .mat-tab-body-content {
            transition: none !important;
            transform: none !important;
        }
    }
}
```

**Comment by anurbol** [comment]
@depiction This repo is for Angularjs (Angular 1), it is not supposed to work with Angular 2+
