### ISSUE TITLE
$mdDialog.confirm() .htmlContent doesn't show anything

### ISSUE THREAD

**Issue by GokuSSL5** [angular/material#10575]
**Actual Behavior**:
Using .htmlContent with $mdDialog.confirm() to show some custom html on the page vs text. When i use .textContent, it displays fine. But when is switch to using .htmlContent and pass in html, nothing displays. Dialog doesn't even come up. No error from the browser. Checked dev tools, no errors.

Expected behavior is to have the confirm dialog window show with the custom html content

**CodePen** (or steps to reproduce the issue): *
https://codepen.io/ITAndy/pen/jBjVee
 -  `Details:`

**AngularJS Versions**: *
https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.js
https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0/angular-material.min.js

**Additional Information**:
Tested on Google Chrome and IE using Windows 8

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by sdesmond** [comment]
I see two errors in the console when the Code Pen runs:

1. Error: The ngSanitize module must be loaded in order to use htmlContent.
2. Error: [$sce:unsafe] Attempting to use an unsafe value in a safe context.

Adding the ng-sanitize module makes it work just fine (check the settings to see where I added it in the javascript tags).

https://codepen.io/anon/pen/wJLeOL?editors=1010#0

**Comment by GokuSSL5** [comment]
Ok, that worked! 
I was curious about the use of ngSanitize but the documentation for the dialog didn't mention it. 

Thanks again! 
You can close this issue.

**Comment by sdesmond** [comment]
You should be able to close this yourself, thanks!
