### ISSUE TITLE
md-select multiple is not $dirty after changing selected options

### ISSUE THREAD

**Issue by reesemartin** [angular/material#10584]
**Actual Behavior**:
 -  `What is the issue? *` When changing the selected options in a md-select with the multiple attribute, the form is dirtied but the select is not.
 -  `What is the expected behavior?` The form AND select should be dirty.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/PmoBrE
 -  `Details:` Change the selected items in the multiple select and see that the form is dirty but the select remains pristine.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.8 and 1.5.7
 -  `AngularJS Material Version:` 1.1.3 and 1.1.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 57.0.2987.133
 -  `OS: *` Windows 10
 -  `Stack Traces:` No errors

**Comment by EladBezalel** [comment]
@reesemartin would you mind submitting a pr for that?

**Comment by alopezsanchez** [comment]
Hello @EladBezalel. PR submitted!
