### ISSUE TITLE
Simplify tabs code

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1058]
It would be nice to not have to deal with checking the index and using `ng-switch`, because it's a little more messy. I'm not really sure of any **much** better options, but here are a couple:

* `md-tabs` + `md-tab-content`, where the order matters
* `md-tabs` > `md-tab` + `tab-content`, and things are compartmentalized
* `md-tabs` with `md-tab-id` and `md-tab-content` with `md-tab-id`, and it is matched.

These are a couple ideas, I think option 2 is pretty good, but there's probably still room for improvement if you guys think this is a good idea.

**Comment by ilanbiala** [comment]
Or something like

```
<md-tabs>
  <md-tab-pane tab-name="Tab1">
    content here
  </md-tab-pane>
  <md-tab-pane tab-name="Tab2">
    content here
  </md-tab-pane>
</md-tabs>
```

**Comment by ThomasBurleson** [comment]
@ilanbiala - I am not sure what you are suggesting. Can you provide more details?

> The Tabs features are some of the more complex features in Angular Material. Tab architecture has, in fact, been rewritten three (3) times already. It has signifcant features for swipe (pending), dirty checking, and supports the complex scenarios regarding internal and/or external content.

**Comment by ilanbiala** [comment]
The static tabs demo uses ng switch, it isn't clear whether that is necessary, but that component is  particularly annoying to use, and I'm proposing simplifying it.

**Comment by ThomasBurleson** [comment]
@ilanbiala - 

*  the [Static Tabs](https://material.angularjs.org/#/demo/material.components.tabs) Demo with the `ng-switch` shows have **external** content can be used with Tabs
*  the [Dynamic Demo](https://material.angularjs.org/#/demo/material.components.tabs) shows how internal Tab views can be easily used.

**Comment by ilanbiala** [comment]
Ah, the external content wasn't clear, I thought it was part of the tab view. Thanks for clearing that up.

**Comment by ThomasBurleson** [comment]
@marcysutton  - I think the confusion here highlights a need for each demo to have a summary paragraph/description. I recommend we include such a feature in the requirements for Docs v2.

**Comment by marcysutton** [comment]
@ThomasBurleson agreed. I'll make sure it is included in the UX planning!
