### ISSUE TITLE
select: multiple control issues while showing selected values

### ISSUE THREAD

**Issue by pshivareddy** [angular/material#10583]
**Actual Behavior**: 
 -  `What is the issue? *`
    I am using `md-select` with the `multiple` attribute and trying to save the selected values into DB as per users. I am trying to display it back, but not able to show the user selected values when landing on the page.
 -  `What is the expected behavior?`
When ever user logs in to my page, I should have to show saved selected values. 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/NjWpPE?editors=1010
 -  `Details:` should be able to show selected values in multi select

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.11
 -  `AngularJS Material Version:`1.1.3

**Additional Information**:
 -  `Browser Type: *`Firefox, Chrome

**Comment by EladBezalel** [comment]
@pshivareddy i think i misunderstood your issue,
As far as i understood it you are asking how can you save the selected values per user?
If that's the case you should have a backend and a db which you send an update each time the selected value is changed and save it to your db..

Is that it? if not can you explain it better?

**Comment by Splaktar** [comment]
More information was requested but not provided. Closing.

Please note that the [Option groups](https://material.angularjs.org/latest/demo/select#option-groups) example shows how to display the selected values when using `multiple`.
