### ISSUE TITLE
md-icon not getting removed by *ngIf

### ISSUE THREAD

**Issue by abadru** [angular/material#10590]
**Actual Behavior**:
 -  `md-icon is not hidden by *ngIf*`
 -  `When *ngIf condition is false the icon should have been removed from the dom?`

**CodePen** (or steps to reproduce the issue): *
 -  ` <md-icon *ngIf="!showAddForm">home</md-icon>`

**AngularJS Versions**: *
 -  `AngularJS Version: 4.0.2`
 -  `AngularJS Material Version: angular material beta 3`

**Comment by mckenzielong** [comment]
This is the issue tracker for Angular Material 1.x (for AngularJS).  You should check out the material 2.x project (for Angular) here: https://github.com/angular/material2
