### ISSUE TITLE
Get focused tab after coming back from a routed page.

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#10591]
**Actual Behavior**:
 -  `I am not able to make focus on the tab when i am coming back from a routed page. *`
 -  `I want to implement a functionality like i am on page (localhost:3000/home) and there are two tabs. I have clicked on second tab and selected some item inside this second tab only which is redirecting to (localhost:3000/home/list_item). So second tab must be in focus when i am coming back to (localhost:3000/home) from (localhost:3000/home/list_item)?`

**Comment by EladBezalel** [comment]
Please ask in our forums, these issues are to report bugs.
