### ISSUE TITLE
The zero number with the numpad on the md-select floatbox, not working

### ISSUE THREAD

**Issue by Zangalot** [angular/material#10593]
When you try to find on the md-select floatbox numbers that contains zero like 300, when you type with the numpad, nothing occurs.
 You have be able to find with all numbers of the numpad.

**The error is in src/core/util/constants.js, in the line 49:**

_**Don't get the zero number on the numpad, only from the one.**_
isNumPadKey : function(e) { return (3 === e.location && e.keyCode >= 97 && e.keyCode <= 105); },

_**Get the zero number on the numpad, changing e.keyCode to 96 that correspond to the zero.**_
isNumPadKey : function(e) { return (3 === e.location && e.keyCode >= 96 && e.keyCode <= 105); },

**Comment by ThomasBurleson** [comment]
Closing since the PR was not squashed!
