### ISSUE TITLE
md-menu-bar not working properly with  ng-repeat 

### ISSUE THREAD

**Issue by Ashish142** [angular/material#10595]
**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: 
 -  `AngularJS Version:`1.5.3
 -  `AngularJS Material Version:`1.1.1

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Ashish142** [comment]
i am using md-menu-bar for display categories , and in the category there are four levels 
by clicking on main first level will come, by clicking on any one in the response of first level second level will come , this is going up to four levels , i have checked md-menu-bar with static data up to four levels then its working fine, but as i am using it with dynamic data its not working properly , i am able to click on main categories only for first time , and if click on second time on main categories then it will disappears.
please help me to resolve 

thanks

**Comment by Ashish142** [comment]
@gmoothart @mprobst @wesalvaro @mprobst

**Comment by wesalvaro** [comment]
Please provide a demo when filing an issue like this.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. This gives the team the information needed to investigate the bug or prioritize the feature.

Specifically, the CodePen reproduction is required. It was requested again on June 22nd, but there has been no movement here. Closing it.
