### ISSUE TITLE
simpleToast not displaying

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1059]
Hi,

I'm trying to get the toast service working but I simply cannot see the toast when it is called.

Code is simply...

```
$scope.showToast = function($event) {
    console.log('Show Toast!')
    $mdToast.show(
        $mdToast.simple('Hello!')
            .position('top right')
            .hideDelay(0)
    );
};  
```

I can see the 'Show Toast' in the console, but there is no evidence of the md-toast element in the dom tree.

Is there any known issues here?

**Comment by kai23** [comment]
Hi,

I have the same issue. How did you solve it.
