### ISSUE TITLE
chips: when readonly='true', support displaying a message as a placeholder

### ISSUE THREAD

**Issue by praveenk-telsiz** [angular/material#10604]
**Actual Behavior**:
 -  `What is the issue? *`
I have the md-chips template as:

`<md-chips dropdown ng-model="chipArray" readonly="true" md-on-remove="blah($chip)" ng-click="blahBlah()" placeholder="Add an item">
        <md-chip-template><span>{{$chip.name}}</span></md-chip-template>
  </md-chips>
`

The md-chips is a dropdown in my case and I have my search inside the dropdown. Since `readonly=true`, the placeholders do not get displayed. 

 -  `What is the expected behavior?`
If I remove the readonly attribute, the placeholders are fine but I feel in cases as mine we would be still needing a placeholder. Or an alternative would be fine. I tried with container-hint which I am not sure is the right case here but it doesn't seem to work.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
            https://codepen.io/anon/pen/bWpaoB
 -  `Details:`
     First example is non-readonly and the second example is read-only

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.4
 -  `AngularJS Material Version:`1.1.1

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by henrymana** [comment]
I just found the same issue. I will patch my local version of the md-chips-wrap tamplate (chipsDirective.js) with the following code...

        <div class="md-chip-input-container" ng-if="$mdChipsCtrl.readonly">\
         .... placeholder text here....
        </div>\

If the core team is fine with such a change. I will be glad to send a pull request once I do it and test it for a few days.

Would this change be acceptable if I submit a PR?

**Comment by henrymana** [comment]
Maybe it is simpler to have a separate div for read only... this is my change. It seems to work fine.

Insert this
```
        <div class="md-chip-input-container" ng-if="$mdChipsCtrl.readonly">
          <input placeholder="{{$mdChipsCtrl.getPlaceholder()}}" readonly/>
        </div>
```

Right after this pre-existing code:

```
        <div class="md-chip-input-container" ng-if="!$mdChipsCtrl.readonly && $mdChipsCtrl.ngModelCtrl">
          <div md-chip-transclude="$mdChipsCtrl.chipInputTemplate"></div>
        </div>
```

**Comment by Splaktar** [comment]
Here's a [CodePen](https://codepen.io/Splaktar/pen/mXvxQQ?editors=1010#0) that demonstrates this issue for 1.1.7 and also shows that it effects `secondary-placeholder` as well.

**Comment by Splaktar** [comment]
What kind of a message would you expect to put in a `readonly="true"` placeholder? The OP's demo shows a message of `Add an item` but that doesn't seem useful in a readonly component?

**Comment by Splaktar** [comment]
@praveenk-telsiz and @henrymana can you provide any further information about why it would be helpful to show a placeholder on a `readonly` `md-chips`? If you look at the [our demos](https://material.angularjs.org/latest/demo/chips), those placeholders don't make sense to show when `readonly` either.

It seems like, if anything, it should be a different placeholder that would be used if `readonly` as the `placeholder` and `secondary-placeholder`s don't seem like they would be useful.

Do you want something like a `disabled-placeholder`?

**Comment by Splaktar** [comment]
No feedback provided to the above questions.
