### ISSUE TITLE
toast: css background-color appear to be hardcoded 

### ISSUE THREAD

**Issue by Olivier-Henry** [angular/material#10608]
**Actual Behavior**:
 -  `What is the issue?`
 the md-toast css file has hardcoded background-color css `provided
```
md-toast.md-THEME_NAME-theme {
 .md-toast-content {
    background-color: #323232;
    color: '{{background-50}}';
    ...
```

 -  `What is the expected behavior?`
It should be interesting to add a variable like a {{background-100}} or another of your choice to allow easy customization.

Best regards.

**AngularJS Versions**: *
 -  `AngularJS Version: All`
 -  `AngularJS Material Version: All`

**Additional Information**:
 -  `Browser Type: All`
 -  `Browser Version: All`
 -  `OS: All`
 -  `Stack Traces: None`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by mckenzielong** [comment]
Hmm, this appears to be to [spec](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage).

> Default background fill: #323232 100%

**Comment by eknowles** [comment]
I agree with @mckenzielong, this is not an issue and is working as intended.

**Comment by Splaktar** [comment]
This does appear to be as defined in the spec. You can override this via using `toastClass(string)` to set a class on the toast which you can use to apply custom styling.

As for theming, the only place that I can see this possibly being an issue is in dark mode, but as we haven't received any reports on that, I believe that it is working fine.
