### ISSUE TITLE
#Feature: $mdLoading

### ISSUE THREAD

**Issue by talgleichger** [angular/material#1060]
I think a loading service such as $ionicLoading is pretty needed. would like to see something like that in the close versions.

I.E:
http://ionicframework.com/docs/api/service/$ionicLoading/

**Comment by talgleichger** [comment]
@marcysutton will do a pull request when i'll have some spare time, I think this is needed

**Comment by ThomasBurleson** [comment]
@talgleichger - The team would love to see your ideas and implementation in a PR. Thank you for you Issues and contributions support.

**Comment by amritk** [comment]
@talgleichger any progress on this? I think its definitely needed
