### ISSUE TITLE
Microsoft Edge browser compatibility

### ISSUE THREAD

**Issue by dharveshmydeen** [angular/material#10616]
My app  should support microsoft edge and above version .

So is there any source file or any other cdn i should add in my project for supporting all animations and all features of material...?

**Comment by henrymana** [comment]
Please post questions on the google group: https://groups.google.com/forum/#!forum/ngmaterial

To get started see: https://material.angularjs.org/latest/getting-started

**Comment by Splaktar** [comment]
The suggestion to post to the forums is the right one. MS Edge is supported w/o anything special needing to be done. If you have more questions, the forum is the place to post. If you find a reproducible bug, please post a new issue with a CodePen reproduction.
