### ISSUE TITLE
mdMenu y-position

### ISSUE THREAD

**Issue by patrikx3** [angular/material#10610]
**Actual Behavior**:
 -  `What is the issue? *`

WIth static menu position works, with dynamic position not working.

```html
<md-menu [y-position]="yPosition" x-position="before" #menuTheme="mdMenu">
            <cory-mat-theme-menu></cory-mat-theme-menu>
        </md-menu>

```

```typescript
export class ThemeButton {

    @Input('cory-y-position')
    yPosition: MenuPositionY = 'below';

```

```bash
Can't bind to 'y-position' since it isn't a known property of 'md-menu'.
1. If 'md-menu' is an Angular component and it has 'y-position' input, then verify that it is part of this module.
```

 -  `What is the expected behavior?`

dynamic position

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
Simple, y-position not working with a dynamic directive

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`
latest

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`
all
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by henrymana** [comment]
You did not fill out the AngularJS Version and AngularJS Material Version fields....

Looking at your snippet of html it seems you are trying to use material 2. This is the wrong repository.

**Comment by patrikx3** [comment]
ohh sorry! thanks! i fill fix it up! ciao!
