### ISSUE TITLE
layout: remove old flexbox support

### ISSUE THREAD

**Issue by avelad** [angular/material#10618]
According to https://developers.google.com/web/tools/lighthouse/audits/old-flexbox "the old, 2009 specification for Flexbox is deprecated and is 2.3x slower than the latest specification"

[no-old-flexbox.txt](https://github.com/angular/material/files/958151/no-old-flexbox.txt)

Can you remove this support?

**Comment by Splaktar** [comment]
Fixed in PR https://github.com/angular/material/pull/11340 in `1.1.11`.

You can see our latest CSS does not include these anymore: https://github.com/angular/bower-material/blob/master/angular-material.css
