### ISSUE TITLE
nav-item: indicator is not responsive when aligned right using flex span

### ISSUE THREAD

**Issue by nd-victor** [angular/material#10617]
**Actual Behavior**:
 -  When `<span flex></span>` is used to align nav items right as suggested, the item indicator is not mobile responsive any more.
 -  The item indicator to be responsive on window resizing. 

**CodePen** (or steps to reproduce the issue): *
 -  https://codepen.io/anon/pen/GmjGKg
 -  The only difference from the demo is the addition of the flex span. When you resize the window, the item indicator does not stay underneath the selected item but shifts.

**Comment by Splaktar** [comment]
I believe that this has been resolved as I can't reproduce it with an [updated CodePen](https://codepen.io/Splaktar/pen/JjKmEGw) using AngularJS Material `1.2.1`.
