### ISSUE TITLE
switch: flicker with ng-show

### ISSUE THREAD

**Issue by samal84** [angular/material#10612]
**Actual Behavior**:
 -  `What is the issue? *`
When putting two spans inside a md-switch that use ng-show on the md-switch model to show/hide, you'll see a flicker, with both options showing for a split second,
 -  `What is the expected behavior?`
No flicker.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://plnkr.co/edit/x5kru0z8OzplNp5mrk10?p=preview
 -  `Details:` Try clicking the switch quickly to see that the first one has a flicker, while the other does not.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.4
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 58
 -  `Browser Type: *`  Firefox
 -  `Browser Version: *` 52
 -  `OS: *` Windows 7
 -  `Stack Traces:`

**Comment by samal84** [comment]
This css works as a workaround:

```
.ng-hide.ng-hide-animate {
  display: none !important;
}
```

**Comment by Splaktar** [comment]
You should avoid using `ng-show` for this. Please take a look at the 2nd example in my [updated Plunker](http://plnkr.co/edit/Fv9TLlBL899vNztM5eZa?p=preview) which just uses an interpolated ternary expression.

**Comment by Splaktar** [comment]
What i18n solution are you working with? Do you have a demo CodePen/Plunker that uses translation?

**Comment by samal84** [comment]
Oh sorry, I've gotten so used to the translate directive that I forgot the translate filter exists :)

I'm just using angular-translate.
