### ISSUE TITLE
mdDialog  the page scrollTop on close

### ISSUE THREAD

**Issue by jayeshrwo** [angular/material#10623]
**Actual Behavior**:
 -  `What is the issue? *`  mdDialog  the page scrollTop on close
 -  `What is the expected behavior?` focus on clicked element instead of scroll to top of the page

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.8
 -  `AngularJS Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` FireFox
 -  `Browser Version: *` 49.0
 -  `OS: *` Linux
 -  `Stack Traces:`

In crome browser it's working properly. 
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by veritas** [comment]
Could you please check if the pull request #10549 does fix your issue?

PLEASE NOTE: This fix has not yet been merged. You need to build the material lib from raw source (not npm). I have described this process in more details in this comment: https://github.com/angular/material/issues/10588#issuecomment-296161827

**Comment by amritk** [comment]
@veritas Has the fix been merged yet? Seems like this is becoming a big issue

**Comment by akvaliya** [comment]
@amritk which version has fixed issue. can you tee me?

**Comment by jalchr** [comment]
Confirmed the fix is working
