### ISSUE TITLE
icon: unable to get property 'element' of undefined or null reference at isIcon 

### ISSUE THREAD

**Issue by SalilLambe** [angular/material#10621]
**Actual Behavior**:
 -  `What is the issue? *` 
```
TypeError: Unable to get property 'element' of undefined or null reference at isIcon
```

 -  `What is the expected behavior?`
 This error should not come and the angular-material1.1.4.js should run with no errors

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.5
 -  `AngularJS Material Version:`1.1.4

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`IE 11
 -  `OS: *`
 -  `Stack Traces:`
```
index.php (458,99)
TypeError: Unable to get property 'element' of undefined or null reference
   at isIcon (tmpl/lib/angular/angular-material%201.1.4.js:32403:5)
   at updateCache (tmpl/lib/angular/angular-material%201.1.4.js:32318:7)
   at Anonymous function (tmpl/lib/angular/angular.min.js:130:216)
   at n.prototype.$eval (tmpl/lib/angular/angular.min.js:144:456)
   at n.prototype.$digest (tmpl/lib/angular/angular.min.js:142:39)
   at n.prototype.$apply (tmpl/lib/angular/angular.min.js:145:247)
   at l (tmpl/lib/angular/angular.min.js:97:53)
   at H (tmpl/lib/angular/angular.min
```

I get this error at  below part of the angular material JS
```js
 /**
   * Check target signature to see if it is an Icon instance.
   */
  function isIcon(target) {
    return angular.isDefined(target.element) && angular.isDefined(target.config);
  }
```

**Comment by tnargib** [comment]
Have you tried adding this to your index.html ?
`<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-114/svg-assets-cache.js"></script>`

and this to your app depedency :
`angular.module('angularFullstackApp', [
    'ngMaterial',
    'material.svgAssetsCache'
])`

**Comment by Splaktar** [comment]
Can you please provide reproduction steps and a CodePen demo?
