### ISSUE TITLE
Datepicker month view isn't visible on IE 

### ISSUE THREAD

**Issue by tom94zoe** [angular/material#10628]
**Actual Behavior**:
 -  `What is the issue? *`
If I use the Internet Explorer version 11 and opens a Datepicker everything is perfect until I click on the arrow to access the view of month selection. Actually, a customer sent me a picture of the issue with specs because I couldn't reproduce the error. The behavior is only observed for one datepicker, all other datepickers are ok. This datepicker is located in a container with following styles:
position:absolute and z-index:2.

 -  `What is the expected behavior?`
The datepicker should display the grid of month. 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
Isn't possible because, I cannot reproduce the error myself 
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.8
 -  `AngularJS Material Version:`1.1.1

**Additional Information**:
 -  `Browser Type: *` Internet Explorer
 -  `Browser Version: *` 11
 -  `OS: *` 
 -  `Stack Traces:` Win 7 professional

![datepicker](https://cloud.githubusercontent.com/assets/17591511/25521236/17051376-2bff-11e7-92ce-6627e286ebb3.png)

----
Thank you in advance

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However, we haven't been able to reproduce it. 

Please feel free to reopen the issue when you are able to provide a reproduction via [CodePen](https://codepen.io/team/AngularMaterial/pen/bEGJdd).
