### ISSUE TITLE
empty chips are created in md-chips while entering two space keys 

### ISSUE THREAD

**Issue by h9945394143** [angular/material#10625]
we are using the below directive and delimiters  . we need to use space as one of the delimiters to create the chip . Please assist . 

	$scope.keys = [$mdConstant.KEY_CODE.COMMA, $mdConstant.KEY_CODE.SPACE, $mdConstant.KEY_CODE.ENTER];

```
app.directive('mdChips', function () {
    return {
        restrict: 'E',
        require: 'mdChips',
        link: function (scope, element, attributes, mdChipsCtrl) {
            mdChipsCtrl.onInputBlur = function () {
                this.inputHasFocus = false;
                var chipBuffer = this.getChipBuffer();
                if (chipBuffer !== "") {
                    this.resetChipBuffer();
                }
            }
        }
    }
});

```

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a CodePen demo that reproduces the problem. 

I believe that this was fixed last year. If this is still an issue for you, please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
