### ISSUE TITLE
dialog: doesn't revert aria-hidden to previous value when closed

### ISSUE THREAD

**Issue by jonathantyates** [angular/material#10624]
**Actual Behavior**:
 -  `What is the issue? *`
If you have open an MdDialog on a page that has an aria-hidden="true" element as a direct descendent of the body, it will get set to aria-hidden="false"
 -  `What is the expected behavior?`
It should retain it's original value when it closes.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/anon/pen/YVNoWX?editors=1111
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5
 -  `AngularJS Material Version:` 1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 57
 -  `OS: *` Linux
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by jonathantyates** [comment]
In the aria 1.1 spec, there is now the property aria-modal="true" which is doing what the walkDOM function is trying to accomplish.  http://w3c.github.io/aria-practices/#dialog_modal

**Comment by Splaktar** [comment]
I am not able to reproduce this with a [CodePen](https://codepen.io/Splaktar/pen/yLJgrBJ?editors=1010) using recent versions. However, I can confirm that it was a problem with `1.1.0` via [this CodePen](https://codepen.io/Splaktar/pen/GRqrLKe?editors=1010).
