### ISSUE TITLE
Flex Element Heights Layout Troubleshooting docs faulty

### ISSUE THREAD

**Issue by isherwood** [angular/material#10637]
The [Troubleshooting section](https://material.angularjs.org/latest/layout/tips#flex-element-heights) for Layout describes using the overflow property to remedy a layout problem with Firefox:

> Notice in the above Codepen how we must set overflow: auto on the div with the change-my-css class in order for Firefox to properly calculate the height and shrink to the available space.

However, the demo doesn't implement this fix:

`.change-my-css {
  /*overflow: hidden;*/
}`

As you can see, not only is the fix not what's described, it's been commented out. 

What is the correct fix for the flex height issue in Firefox?

**Comment by ThomasBurleson** [comment]
We use  `  flex-basis: auto;` in wrapper div. Vertical fills are tricky and the Layout API may not provide out-of-the-box solutions. Custom tweaks/workarounds may be required.
