### ISSUE TITLE
Icon code not working

### ISSUE THREAD

**Issue by matheuscaldasrj** [angular/material#10632]
Hi, I am trying to use something like

`<i class="material-icons">{{myClass.attribute}}</i>`

when `myClass.attribute` is something like `brightness_6` it works like a charm.

But when `myClass.attribute` is something like `&#xE430` (code for icon, should be use to compatibility with older browsers) it doesn't work. 
I have already test `E430` and it does not work too.

Looks like angular does not evaluate the correct value to interpret as an icon. 

Do you know how can i figure it out?

**Comment by Splaktar** [comment]
You need to use `<md-icon>` and its [associated APIs](https://material.angularjs.org/1.2.1/api/directive/mdIcon).

The docs seem to indicate that `<md-icon> numerical_character_reference </md-icon>` should work.
