### ISSUE TITLE
chips: support for languages in separatorKeys

### ISSUE THREAD

**Issue by yossivcita** [angular/material#10639]
When defining separator keys for chips:
`scope.separatorKeys = [$mdConstant.KEY_CODE.ENTER, $mdConstant.KEY_CODE.COMMA, $mdConstant.KEY_CODE.SEMICOLON, $mdConstant.KEY_CODE.SPACE]` 
Some hebrew letters such as 'ת' and 'ף' are read as ',' or ';' so they separate the chip.

**Comment by Splaktar** [comment]
What do you propose as a solution to this?

Neither comma or semicolon are default separator keys, so this would only be an issue when defining custom separator keys.

Is simply not defining `$mdConstant.KEY_CODE.COMMA, $mdConstant.KEY_CODE.SEMICOLON` as custom separator keys in your app if using Hebrew enough? 

The [custom separator key demo](https://material.angularjs.org/latest/demo/chips) shows how to use specific key codes if they are not defined in `$mdConstant`. Perhaps using that method would allow you to specify the specific codes that make sense with a Hebrew keyboard?

**Comment by AlmogCohen** [comment]
It just doesn't make any sense that `$mdConstant.KEY_CODE.COMMA` counts as a ת too. "," and "ת" indeed come from the same physical button on a Hebrew keyboard but they are not the same...Is there an actual technical difficulty to distinguish the two?

Thanks for the great work!

**Comment by Splaktar** [comment]
> It just doesn't make any sense that `$mdConstant.KEY_CODE.COMMA` counts as a ת too. "," and "ת" indeed come from the same physical button on a Hebrew keyboard but they are not the same...Is there an actual technical difficulty to distinguish the two?

It's just based on key codes. If a user has a custom keyboard or a keyboard with a different locale, then it may assign the same key codes to different characters. At this point, I think that my previous guidance on customizing your app to use specific key codes for separators based upon locale is the best solution.

> Thanks for the great work!

❤️
