### ISSUE TITLE
Protractor tests

### ISSUE THREAD

**Issue by mlb6** [angular/material#1063]
It seems there is no e2e tests with Protractor in this project for the moment.
It would be useful to have an example of test for each component. There is some component like "Toast" that does not seem easy to test since DOM Elements can appear for only few seconds.

It could also be nice to have some "[Locator](http://angular.github.io/protractor/#/api?view=ProtractorBy.prototype.addLocator)" specific to material design components. 
For example, the input field in the "Text Field" component is wrapped by md-input-group.
The following:
```html
<md-text-float id="myId" label="Test" > </md-text-float>
```
is transformed in something like this
```html
<md-input-group id="myId">
  <label for="001">Test</label>
  <input id="001" type="text"/>
</md-input-group>
```
But in my test I want to be able to get the input element, and not the md-input-group. And as a user of the library I don't want to know how it is implemented because implementation can change.
So it would be very helpful to have a locators like this:
```javascript
element(by.mdID("myId")) // should return element "md-input-group#myId input"
```

**Comment by marcysutton** [comment]
:1 to including protractor examples, I'd love to see this.

**Comment by JJB1980** [comment]
I would like to interact with the button on the dialog component.  However protractor can't select the button e.g.
element(by.css('md-actions')).element(by.css('md-primary')).click();

Any ideas?

**Comment by marcysutton** [comment]
@JJB1980 Are you missing the `.` for a CSS class?

**Comment by bvaughn** [comment]
I'd love to see an example of such a test as well. I've been trying (and failing) to write some Protractor tests in a project I'm working on that makes use of Angular Material.

FYI [material-start issue #30](https://github.com/angular/material-start/issues/30).

**Comment by tkrotoff** [comment]
+1

**Comment by ThomasBurleson** [comment]
While e2e tests will be provided in the future, they are not currently a priority; our current focus is component implementation, unit tests, performance, and effects.

**Comment by chayutzee** [comment]
+1
