### ISSUE TITLE
layout-fill in md-card-content is always ignored by Safari and Chrome

### ISSUE THREAD

**Issue by Burtan** [angular/material#10644]
**Actual Behavior**:
 -  `What is the issue? `layout-fill does not fill the parent on Safari and Chrome. The issue on Chrome appears when the div containing the layout-fill attribute is placed inside a md-card-content element which is placed inside a md-content element. The issue on Safari appears when the div containing the layout-fill attribute is placed inside a md-card-content element regardless of it being insde a md-content element.
 -  `What is the expected behavior?` Filling the parent like on Firefox

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`layout-fill in md-card-content issue on Safari https://codepen.io/Burtan/pen/pPrXQR
 -  `CodePen Demo which shows your issue:`layout-fill in md-card-content in md-content issue on Safari and Chrome https://codepen.io/Burtan/pen/EmvBEb

**AngularJS Versions**: 
 -  `AngularJS Version:` 1.6.4
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: `Safari and Chrome
 -  `Browser Version: *`Safari 10.1 (12603.1.30.0.34), Chrome 57.0.2987.133

**Comment by ThomasBurleson** [comment]
We will not fix this in AngularJS Material. You are welcome to provide a Pull Request to resolve this for Material 1.1.x.
> Ongoing support for Flexbox layouts is provided in Angular 4.x with @angular/flex-layout.
