### ISSUE TITLE
min-height is ignored for div in md-content on safari

### ISSUE THREAD

**Issue by Burtan** [angular/material#10643]
**Actual Behavior**:
 -  `What is the issue?` When adding a div to md-content with min-height = 100% set via css class, safari ignores the property
 -  `What is the expected behavior?` Safari should have the same behaviour as chrome and firefox

**CodePen** (or steps to reproduce the issue):
 -  `CodePen Demo which shows your issue:` https://codepen.io/Burtan/pen/PmKvdB
 -  `Details:` Change the height of the viewport to see the differences

**AngularJS Versions**:
 -  `AngularJS Version:` 1.6.4
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type:` Safari
 -  `Browser Version:` Version 10.1 (12603.1.30.0.34)
 -  `OS: macOS Sierra 10.12.4`

**Comment by Splaktar** [comment]
This appears to have been a bug in Safari related to Flexbox. It appears to be working properly now in Safari 12 (tested on macOS Mojave). Also note that with the release of Safari 12, we've dropped support for Safari 10. We support the last 2 versions only (11, 12).
