### ISSUE TITLE
Step Wizard

### ISSUE THREAD

**Issue by vipulsaxena** [angular/material#1064]
This is quit a rare element to ask for but it'd be nice to have a Step-wizard. 
Maybe this element can be added to later milestones, being less important.

Something of this sort: https://github.com/mgonto/angular-wizard

**Comment by afrad** [comment]
Please take a  look to:

https://github.com/Matesign/material-wizard

**Comment by zfarooq2** [comment]
Is there a demo for this, afrad?

**Comment by LeoLozes** [comment]
Hi! I understand that a full wizard is not something that is in the scope of this project. 

However, are the steps from the Material Design guidelines (http://www.google.es/design/spec/components/steppers.html) going to be implemented at some point?

**Comment by EladBezalel** [comment]
@LeoLozes angular material aim to implement the full Material Spec.
