### ISSUE TITLE
Weird behavior with animation in chrome

### ISSUE THREAD

**Issue by lexyfeito** [angular/material#10641]
-  `What is the issue? *`
After i update chrome this morning some weird behavior started to happened to animations, some weird black stripes are left on the screen and sometimes images of an element, all of this happens randomly.

**AngularJS Versions**: *
 -  `AngularJS Version:` v1.6.1
 -  `AngularJS Material Version:` 1.1.3

Chrome Version 58.0.3029.96 (64-bit)
![capture](https://cloud.githubusercontent.com/assets/2266638/25680371/948f4d7a-301e-11e7-8b4b-b1ce9b8e7622.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2266638/25680369/948b3aaa-301e-11e7-9463-0f795e5e11cc.PNG)
![capture3](https://cloud.githubusercontent.com/assets/2266638/25680370/948c69b6-301e-11e7-8ffd-9862430e33fc.PNG)

**Comment by ThomasBurleson** [comment]
Please retry to latest from `master`: https://rawgit.com/angular/bower-material/master/angular-material.js

Closing issue as invalid without demo/Plunkr
