### ISSUE TITLE
toolbar: subheader toolbar issue not working after page loading completed

### ISSUE THREAD

**Issue by Dakshank** [angular/material#10642]
I have faced issue while implementing a module. and checked over demo having the same issue in both firefox and chrome browser.
https://material.angularjs.org/latest/demo/subheader
Here you can find out the issue.

Page has done completely load after scrolling the subheader doesn't hide as per the functionality. But after waiting for some seconds it works as it should.

I Don't know why it doesn't work on page load.

FYI I am using windows 7 system.

I hope this issue has been seen by other as well.

**Comment by mckenzielong** [comment]
possibly related to #10413

**Comment by Splaktar** [comment]
@Dakshank are you seeing the same issue here as https://github.com/angular/material/issues/10413?

If not, can you please provide more details on the behavior that you are seeing and what you expect to happen?

With `md-scroll-shrink` in the demo, the toolbar hides on scroll, but the subheader does not.
