### ISSUE TITLE
md-progress-circular memory leak

### ISSUE THREAD

**Issue by rudzikdawid** [angular/material#10653]
**Actual Behavior**:
 -  `What is the issue? Memery leak, using md-progress-circular`
 -  `What is the expected behavior? nice memory profile without leak`

![memory profile](http://i.imgur.com/jvjHT0r.jpg)

![memory allocation timeline](http://i.imgur.com/LdSMxLF.png)

**Demo** (or steps to reproduce the issue): *
 - https://material.angularjs.org/HEAD/demo/progressCircular
 - chrome devTool, Performance, record memory profile

**AngularJS Versions**: *
 -  `AngularJS Version: 1.6.4`
 -  `AngularJS Material Version: 1.1.4`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 58`
 -  `OS: Fedora 25`

**Comment by ThomasBurleson** [comment]
The core team will not fix this in AngularJS Material. You are welcome to provide a Pull Request to resolve this for Material 1.1.x.
