### ISSUE TITLE
md-slider handle and gauge split up

### ISSUE THREAD

**Issue by SK0RM** [angular/material#10656]
**Actual Behavior**:
 -  `What is the issue? *`
The slider handle and the gauge split up when sliding, on Ipad in safari.
 -  `What is the expected behavior?`
Should not split up.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
Just add a md-slider and act like a dumb user, rapidly sliding until it breaks.
(See screenshot: https://ibb.co/fCGV35)

**AngularJS Versions**: *
 -  `AngularJS Version:` 4.1.1
 -  `AngularJS Material Version:` 2.0.0-beta.3

**Additional Information**:
 -  `Browser Type: *` Safari
 -  `Browser Version: *` 602.1
 -  `OS: *` iOS 10.3.1
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by MorgothsHammer** [comment]
Has there been any progress on this issue or did you find a workaround @SK0RM ?  I'm working on an app that has a variety of these sliders and they are doing exactly the same thing on Safari.  Thanks!

**Comment by SK0RM** [comment]
Still no progress on this. I was becoming to feel alone :/

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
