### ISSUE TITLE
dialog: glitch behaves incorrectly in IE 11 

### ISSUE THREAD

**Issue by KrlosG** [angular/material#10655]
**Actual Behavior**:
 -  I have a problem with the component mdDialog since this breaks the body which produces gliches in the page distorting the content.

If I remove the fixed position that places the mdDialog to the body this is fixed

![sin titulo-2](https://cloud.githubusercontent.com/assets/9244536/25904078/85bf49b6-3574-11e7-9261-676a4d4d5a7d.jpg)
![sin titulo-1](https://cloud.githubusercontent.com/assets/9244536/25904103/9a800ade-3574-11e7-8cdf-c81cf29afce4.jpg)

**AngularJS Versions**: *
 -  `Angular 1.5.8:`
 -  `AngularJS Material 1.1.4:`

**Additional Information**:
 -  `Browser Type: IE
 -  `Browser Version: 11.5`
 -  `OS: All Windows`

**Comment by Splaktar** [comment]
If this is still a problem for you, can you please try using a more recent version `1.1.26` or `1.2.1`?

If it is still a problem there, can you please provide a CodePen or StackBlitz demo?
