### ISSUE TITLE
md-grid-list responsive attributes for screen size do not work

### ISSUE THREAD

**Issue by user2301** [angular/material#10654]
**Actual Behavior**:
 -  `What is the issue? *`
md-grid-list upon resizing the browser window size, will not be displayed correctly. The number of rows in the grid do not change upon changing the window size and the contents in the md-card gets overlapped.
 -  `What is the expected behavior?`
Upon resising the browser window, the md-grid list should resize properly and card contents should be readable and number of cards in a row should be adjusted according to the window size. when sceern size is medium 4 cards to be displayed in a row and when screen is reduced 2 cards to be displayed
**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
2.4.10
 -  `AngularJS Material Version:`
2.0.0-beta.2

**Additional Information**:
 -  `Browser Type: *`
chrome
 -  `Browser Version: *`
latest
 -  `OS: *`
windows and linux
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by MythriManjunath** [comment]
`<md-grid-list cols="4" cols-xs="1" cols-sm="2" cols-md="4"  rowHeight="250px" gutterSize="20px">
  <md-grid-tile  *ngFor="let data of myData">
	  <md-card [style.background]="'lightBlue'" [style.minHeight]="'100%'" >	
    <md-card-title></md-card-title>
	<md-card-title></md-card-title>
	<md-card-content>
	<h2>	
	</h2>
	</md-card-content>	
	</md-card>
  </md-grid-tile>
</md-grid-list>`

**Comment by bruteforce** [comment]
Experiencing the same issue.

**Comment by kirtiesl** [comment]
Same issue. Please help!!

**Comment by vinothrao** [comment]
same issue. any updates on this?

**Comment by CDXdev** [comment]
I have the same issue. Apparently the responsive number of cols is not implemented since 1.0.0-rc4. But here is a solution to wait for a better upgrade : https://stackoverflow.com/questions/45188134/change-the-layout-or-cols-value-of-md-grid-list-based-on-screen-size

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
