### ISSUE TITLE
feat(autocomplete): should be able to define dropdown item heights

### ISSUE THREAD

**Issue by gustavocampos** [angular/material#10658]
**Actual Behavior**:
 -  `What is the issue? *`
If we change md-autocomplete dropdown items height through CSS, the list will have a lot of empty spaces at the end (or the list being cut at 2 items with a scroll bar when there's 50 items), since the calculation of the dopdown height is fixed on 48px height per item times the number of visible items.
The autocomplete is inside a md-chips control.
 -  `What is the expected behavior?`
As a height of 48px is a lot of blank space per item, we tried to reduce it to 24px through CSS, the list could then have double the items occupying the same space.
Something like being able to define a height like it was done for defining number of items at https://github.com/angular/material/issues/8751

**CodePen** Demo or steps to reproduce: *
I could reproduce it only once and briefly at codepen, after the first iterations the list seems to adapt itself if it has to grow (from like 5 items and 5 blanks to showing 10 items) when I click outside and click on the text to search again, but it won't grow if it has shrunk (like having 2 items and searching for something that brings 100 items, will keep showing 2 items with a long scroll bar).
Please check the screenshot and CSS below.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.4.8
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome 64-bit
 -  `Browser Version: *` 58.0.3029
 -  `OS: *` Windows 10
 -  `Stack Traces:`

Screenshot:
![test1](https://cloud.githubusercontent.com/assets/4368993/25913892/be6fccae-3592-11e7-9dd9-e2cbad1c8f36.png)

CSS:
`.md-autocomplete-suggestions li {
    font-size: 12px;
    padding: 0 8px;
    line-height: 24px;
    height: 24px;
}
.md-autocomplete-suggestions li .layout-column {
    line-height: 16px;
}
.md-virtual-repeat-container.md-not-found {
    height: 24px;
}`

**Comment by begemott** [comment]
+1

**Comment by Splaktar** [comment]
The [spec](https://material.io/guidelines/components/menus.html#menus-specs) defines `48px` as the size for mobile, but desktop should be `32px` and dense desktop is `24px`.

**Comment by Splaktar** [comment]
This is now possible when specifying `md-mode="standard"` to use `ng-repeat` instead of `md-virtual-repeat` in your autocomplete: [md-mode docs](https://material.angularjs.org/HEAD/api/directive/mdAutocomplete#specifying-repeat-mode)
