### ISSUE TITLE
Chip control allowing duplicate values when number fields are used

### ISSUE THREAD

**Issue by DeneroWatz** [angular/material#10663]
**Actual Behavior**:
 -  `What is the issue? *`
I initially have an array [123, 456, 789] and using a number type field to add.
Now when I add 123 again it is adding that. But from second time onwards it is not allowing. Seems like the new values added are treated as string hence this is happening.

Also in the codepen here, the parser added by the myModelValidate directive is never gets called when a new value is added or edited.

 -  `What is the expected behavior?`
It should not allow duplicates

**CodePen** (or steps to reproduce the issue): *
 -  https://codepen.io/denero_watz/pen/wdmgyy

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome, FF etc
 -  `Browser Version: *` NA
 -  `OS: *` Windows 10
 -  `Stack Traces:` None

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
From the [mdChips docs](http://localhost:8080/api/directive/mdChips):
> Assignable angular expression to be data-bound to the list of chips. The expression should evaluate to a `string` or `Object` Array.

Arrays of `number`s are not supported.
