### ISSUE TITLE
gestures: incorrect behavior touchstart events on mobile, or chrome dev mode. (duplicate event trigger)

### ISSUE THREAD

**Issue by AlexTimofeyev** [angular/material#10662]
**Actual Behavior**:
 -  `What is the issue? *`
	Touchstart event duplicated within Mousedown event if "ngMaterial" included, without "ngMaterial" module, events firing more correctly.
 -  `What is the expected behavior?`
	Touchstart event triggering without Mousedown event.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/AlexTimofeyev/pen/BRrpmm
 -  `Details:`  Open in Chrome with dev tools, or  chrome mobile.

**AngularJS Versions**: *
 -  `AngularJS Version:`1.6.1
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *`Chrome,Safari   
 -  `OS: *`  Ubuntu, Android

**Comment by Splaktar** [comment]
You list Safari here, but don't list an OS which Safari runs on. Did you see this on iOS?

**Comment by Splaktar** [comment]
With your CodePen, I'm able to get a `touchstart` even by touching and dragging, then releasing. If I touch and release, then I get both the `touchstart` and `mousedown` events.

Can you please provide some details on the specific use case that this report is related to?

Can you please provide more details on how you would expect this to behave along with some references to how these events should be properly triggered?

**Comment by Splaktar** [comment]
Unfortunately, I don't have enough information here to take any action.
