### ISSUE TITLE
md-mini-fab position issue

### ISSUE THREAD

**Issue by deephakdd** [angular/material#10661]
md-mini-fab button is not being placed at the bottom right 

<div >
       Content.....................
       <button md-mini-fab color="accent" class="md-fab-bottom-right">
        <md-icon class="md-24">add</md-icon>
        </button>
   </div>

when is use this code the button is being displayed below the content but to the left

i tried using md-button as a tag too , in this case m getting md-button is not a know element
<md-button class="md-fab md-fab-bottom-right" aria-label="Add a category">
  <md-icon>add</md-icon>
</md-button>

any help is appreciated

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
