### ISSUE TITLE
requestAnimationFrame still run when set md-progress-circular ng-show='false'

### ISSUE THREAD

**Issue by feichao** [angular/material#10668]
**Actual Behavior**:
 -  `requestAnimationFrame is still running when set md-progress-circular ng-show='false', and the usage of cpu retains 19% `
 -  `when set ng-show='false' or ng-hide='true', the requestAnimationFrame should pause`

**AngularJS Versions**: *
 -  `AngularJS Version: 1.5.8`
 -  `AngularJS Material Version: v1.1.1`

**Additional Information**:
 -  `Browser Type: chrome`
 -  `Browser Version: 58`
 -  `OS: Mac OS`

**Comment by ThomasBurleson** [comment]
We will not fix this in AngularJS Material. You are welcome to provide a Pull Request to resolve this for Material 1.1.x.

**Comment by Splaktar** [comment]
It would be helpful if you could provide a CodePen that demonstrates this. Here is a starter http://codepen.io/team/AngularMaterial/pen/RrbXyW

**Comment by Splaktar** [comment]
No demo provided. If you are still seeing this, please submit a new issue using the issue template and providing a CodePen reproduction.
