### ISSUE TITLE
tabs: initializes twice on load

### ISSUE THREAD

**Issue by alagarrk** [angular/material#10660]
**Actual Behavior**:
 Currently, We are trying to generate md-tabs dynamically, its working fine. But onLoad it initialize twice for each tab. Don't know how to control it.

PS :  Not using ng-click in md-tab. Using md-on-select event

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.8
 -  `AngularJS Material Version:` Latest

Can you please give some idea, how to control it?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a CodePen reproduction demo. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
