### ISSUE TITLE
$broadcast and $emit not working in dialog boxes. 

### ISSUE THREAD

**Issue by hadihonarvar** [angular/material#10665]
$broadcast and emit does not work on dialog box so that it is not possible to make dynamic content in dialog boxes based on the trigger page.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a CodePen reproduction demo. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

I believe that this was as application mistake with handling `$scope`, but without a reproduction, I can't verify that.
