### ISSUE TITLE
virtual-repeat with grouping in table

### ISSUE THREAD

**Issue by m3Lith** [angular/material#10672]
I'm not sure if this is supported, but I saw a similar issue ( #10251) and thought I'd ask for help again.

**Actual Behavior**:
 -  `What is the issue? *`virtual-repeat doesn't seems to work properly when using nested repeats (for grouping). Scrolling doesn't work.
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://codepen.io/anon/pen/ZKMZeo
 -  `Details:`I've forked the pen from the mentioned issue and basically left only a bare table. As I've mentioned, I'm not sure if that is possible to do, and if I'm doing it correctly (e.g. nesting md-virtual-repeat-container tags).

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.5
 -  `AngularJS Material Version:`1.1.4

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *`Latest
 -  `OS: *`Win 10
 -  `Stack Traces:`

**Comment by henrymana** [comment]
Looking at the code, this is not supported. 

The virtual repeat is designed for homogeneous elements with the same size...

See this function for example:

VirtualRepeatContainerController.prototype.scrollToIndex = function(index) {
  var itemSize = this.repeater.getItemSize();
  var itemsLength = this.repeater.itemsLength;
  if(index > itemsLength) {
    index = itemsLength - 1;
  }
  this.scrollTo(itemSize * index);
};
