### ISSUE TITLE
datepicker: ng-click is not triggered by clicking the calendar icon

### ISSUE THREAD

**Issue by duyh90** [angular/material#10679]
**Actual Behavior**:
I have a ng-click function registered on a md-datepicker directive, which changes the disabled status of a date picker, i.e. clicking the datepicker should turn it from disabled to enabled.
However only clicking the date part does the job. Clicking the calendar icon doesn't trigger the function.

**CodePen** (or steps to reproduce the issue): *
See https://codepen.io/duyh90/pen/LyMzap

**AngularJS Versions**: *
AngularJS: 1.5.5 
AngularJS Material Version: 1.1.4

**Additional Information**:
Chrome 58.0.3029.110 (64-bit)

**Comment by duyh90** [comment]
Another issue is that, after clicking the date, the date picker is enabled, but not focused, i.e. not turning blue. Clicking on the date input again will focus on the date picker, i.e. turnning into blue.

**Comment by Splaktar** [comment]
This is not a UX behavior that is defined in the Material Design spec or that we support. `disabled` elements do not normally accept click events. Additionally, the `md-datepicker-button` element already has `ng-click="ctrl.openCalendarPane($event)"`, so it wouldn't be possible to add another `ng-click` to the element.

What are you trying to accomplish by disabling the datepicker and then having it enabled just by a click on it? Normally, there would be another action, perhaps updating another form field, that would trigger enabling the datepicker.
