### ISSUE TITLE
Disabled slider fires onChange 

### ISSUE THREAD

**Issue by SK0RM** [angular/material#10673]
**Actual Behavior**:
 -  `What is the issue? *` A disabled slider fires onChange event on drag the first time
 -  `What is the expected behavior?` Should not fires onChange

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` Place a slider with onChange handler (ie. (change)="myHandler()"). Make sure to get a feedback in the handler (ie. alert, log, ...).

**AngularJS Versions**: *
 -  `AngularJS Version:` 4.1.1
 -  `AngularJS Material Version:` 2.0.0-beta.3

**Additional Information**:
 -  `Browser Type: *` Chrome / Safari / Firefox
 -  `Browser Version: *` 58.0.3029.110 (64-bit) / Version 10.0.3 (12602.4.8) / 53.0.2 (64 bits)
 -  `OS: *` MacOS Sierra 10.12.3 (16D32)
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
