### ISSUE TITLE
Add md-content in md-select with md-select-header

### ISSUE THREAD

**Issue by Spanja** [angular/material#10670]
**Actual Behavior**:
 -  `What is the issue? *`
When selecting a md-select item, the item is well selected but the select panel is not closed, with a stack in console.
 -  `What is the expected behavior?`
The md-select panel should be closed correctly

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
https://codepen.io/Assidator/pen/oWMROq
 -  `Details:`
I just forked the Select Header from https://material.angularjs.org/latest/demo/select#select-header
and switched the md-optgroup to a md-content in the select, to get the md-select-header fixed (I want the md-content to be the only element scrollable).

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.4
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` 58.0.3029.110 (64-bit)
 -  `OS: *` W10
 -  `Stack Traces:`
Uncaught TypeError: Cannot read property 'offsetWidth' of null
    at mouseOnScrollbar (angular-material.js:20929)
    at HTMLElement.checkCloseMenu (angular-material.js:20905)
    at defaultHandlerWrapper (angular.js:3456)
    at HTMLElement.eventHandler (angular.js:3444)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
`md-content` is not supported within `md-select`. `md-options`, `md-optgroup`, and `md-select-header` are supported.
