### ISSUE TITLE
Changing sidebar when dependance 'ngMaterial' added

### ISSUE THREAD

**Issue by LaureMonlouis** [angular/material#10681]
**Actual Behavior**:
 -  `What is the issue? *` My sidebar is changing only by adding 'ngMaterial' to my dependances : angular.module('app', [..., 'ngMaterial']);
Title are center-aligned or right I don't know and they take much more place.
![anormal_behaviour](https://cloud.githubusercontent.com/assets/11017332/26357256/049cf27e-3fcf-11e7-8593-bea60a2bc7d2.png)
 -  `What is the expected behavior?`Titles should be aligned on left and smaller.
![normal_behaviour](https://cloud.githubusercontent.com/assets/11017332/26357257/049e87a6-3fcf-11e7-8cc8-08d168d8022d.png)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
import 'angular-material';
angular.module('app', [..., 'ngMaterial']);
 -  `Details:` If I remove 'ngMaterial' it is ok again.

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.5
 -  `AngularJS Material Version:` 1.0.8

**Additional Information**:
 -  `Npm Version: *`3.10.10

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a CodePen reproduction demo. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
