### ISSUE TITLE
angular-material-source npm update

### ISSUE THREAD

**Issue by ultish** [angular/material#10687]
Hi all,

I'm currently working with ember-paper and it uses the sass source files from this repo. However, there haven't been any new versions of angular-material-source published to npm since v1.0.10 (https://www.npmjs.com/package/angular-material-source).  To overcome this, ember-paper has used a github url dependency to angular-material but I'm having issues with that due to my own work environment (see https://github.com/miguelcobain/ember-paper/issues/712).

I was just wondering why angular-material-source had stopped being published to npm and if it could be updated?

**Comment by ThomasBurleson** [comment]
We have AngularJS Material v1.1.4 available on NPM:  https://www.npmjs.com/package/angular-material

**Comment by ultish** [comment]
@ThomasBurleson I realise this, but it seems the original sass files have already been compiled in angular-material, bit they weren't in angular-material-source?
