### ISSUE TITLE
On Dropdown Selection the virtual keyboard gets opened on iOS- Webview

### ISSUE THREAD

**Issue by mananjindal1818** [angular/material#10689]
**Actual Behavior**:
 -  `What is the issue? *` We have a input box and a dropdown. When we tap on the dropdown selection (the layout of dropdown selectives overlays the textbox layout), along with Dropdown selection, virtual keyboard of iOS is also getting opened. 
 -  `What is the expected behavior?` Only the Dropdown should open. 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.0
 -  `AngularJS Material Version:`1.1.0

**Additional Information**:
 -  `Browser Type: *`iPhone 
 -  `Browser Version: *`
 -  `OS: *`Latest
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by lrpina** [comment]
I have the same problem. The virtual keyboard opens with on an Android Tablet. Does anyone have an update?

**Comment by Splaktar** [comment]
Please provide a CodePen demo with reproduction steps. This is a **required** part of our template and we cannot investigate otherwise. It's not clear from the description here that the input or dropdown are even using AngularJS Material components.
