### ISSUE TITLE
feat(datepicker): year only mode

### ISSUE THREAD

**Issue by 3vi21** [angular/material#10686]
Is possibile to have datepicker mode for selecting only year?

**Comment by ElakiyaS** [comment]
Selecting only year is not possible, month year format is possible using md-mode="month".

**Comment by yong2khoo88** [comment]
hm... i have tested the md v1.1.4 at local, even the `md-mode="month" `it doesn't work. what did i do wrong? (it still shows month and date

**Comment by tom94zoe** [comment]
I think md-mode="month" will be included in v1.2.0

**Comment by ptitdam2001** [comment]
what's new about that issue? the documentation specifies it, but it isn't working....

**Comment by Splaktar** [comment]
`md-mode="month"` is supported in 1.1.6. Example here https://codepen.io/Splaktar/pen/zpygNK.

`md-mode="year"` is not supported at this time.

**Comment by Splaktar** [comment]
If you just need a year input, we suggest that you use an input rather than a datepicker. We don't have plans to support a year-only mode.
