### ISSUE TITLE
chips: Cannot read property 'length' of undefined in hasMaxChipsReached

### ISSUE THREAD

**Issue by PragramingFleur** [angular/material#10696]
**Actual Behavior**: It should add chips on enter
 -  `What is the issue? *`
It returns the following error:
ypeError: Cannot read property 'length' of undefined
    at MdChipsCtrl.hasMaxChipsReached (angular-material.js:27588)
    at MdChipsCtrl.validateModel (angular-material.js:27595)
    at MdChipsCtrl.shouldAddOnBlur (angular-material.js:27809)
    at MdChipsCtrl.onInputBlur (angular-material.js:27746)
    at fn (eval at compile (angular.js:15358), <anonymous>:4:202)
    at callback (angular.js:26994)
    at ChildScope.$eval (angular.js:18161)
    at ChildScope.$apply (angular.js:18261)
    at HTMLInputElement.<anonymous> (angular.js:26999)
    at HTMLInputElement.dispatch (jquery.js:5206)
(anonymous) @ angular.js:14525
(anonymous) @ angular.js:11008
$apply @ angular.js:18266
(anonymous) @ angular.js:26999
dispatch @ jquery.js:5206
elemData.handle @ jquery.js:5014
 -  `What is the expected behavior?` Don't give that error and add the new chip like it is supposed to

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/programmingFleur/pen/GmaYyP
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.5
 -  `AngularJS Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` chrom
 -  `Browser Version: *` 58.0.3029.110 (64-bit)
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by PragramingFleur** [comment]
I don't mean to sound sarcastic

**Comment by omril1** [comment]
I have the same problem, but only in `IE11`, on chrome it works fine for me.
I think it is happening when the blur event is triggered, and there are no options to complete from.
Somehow `this.items` inside the MdChipsCtrl controller gets a value of undefined instead of an empty array like in chrome.

**Comment by Splaktar** [comment]
Here's a fixed [CodePen](https://codepen.io/Splaktar/pen/vdvBde?editors=1011). The issue was that you were using the controller as `ng-model="ctrl.roFruitNames"` but you were missing the `as ctrl` in `ng-controller="BasicDemoCtrl as ctrl"`.
