### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by BadiuAlexandru** [angular/material#10698]
I followed this basic example (https://codepen.io/iamisti/pen/mVOKEw) and many others from the docs and at every one i got the same error on repeat (i attached 1 photo so you can view the full error)
https://postimg.org/image/6nnep9g0z/

I am using angular 1.6.2

I don't know why but this part of code :        var reader = element[0].querySelector('.mdtTable-reader'); returns null reader ... can somebody help me

**Comment by henrymana** [comment]
The mdTable is not a an angular-material component. You may want to re-post on the corresponding project.

**Comment by ThomasBurleson** [comment]
Closing as invalid.
