### ISSUE TITLE
select(multiple): with checkbox, panel not closing in AngularJS v1.3.16

### ISSUE THREAD

**Issue by subhashekkaluru** [angular/material#10697]
Dear all, here am using angular meterial design md-select multiple but this multi select window not closing when i was using the AngularJS v1.3.16 and it will work properly if i use AngularJS v1.5.11.
so i need solve this issue what was wrong going on please help to me... thanks

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a CodePen reproduction demo. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
