### ISSUE TITLE
how to use $mdCompiler.compile

### ISSUE THREAD

**Issue by alluri24** [angular/material#10690]
Why is mdCompiler not picking up controller.. Its compiling only  DOM (HTML) Elements.

var myElement = document.querySelector('#second_div');
$mdCompiler.compile({
  templateUrl: 'modules/modal.tpl.html',
  controller: 'ModalCtrl',
controllerAs: 'vm',
contentElement: myElement,
  locals: {

  }
}).then(function (compileData) {
  compileData.element; // Compiled DOM element
  myElement.prepend(compileData.element[0]);
});

**Comment by DevVersion** [comment]
Here you can find some documentation about it: [here](https://material.angularjs.org/latest/api/service/$mdCompiler)

If you use `contentElement` it only accepts DOM elements that are already created. If you use `template` or `templateUrl` then it will instantiate the controller for you.

If you really want a controller for your `contentElement` just apply the `ng-controller` directive onto the element.
