### ISSUE TITLE
Submit fired twice on mobile devices

### ISSUE THREAD

**Issue by leibale** [angular/material#10699]
**Actual Behavior**:
 -  `What is the issue?` For some reason when i add material to my module, the submit is fired twice (only on mobile devices).
 -  `What is the expected behavior?` Submit should be fired once per click.

**CodePen** (or steps to reproduce the issue): *
 -  https://codepen.io/anon/pen/mmYNJO (Use chrome mobile emulator).
 -  You can see the stack trace, one from native code and one from material.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.4
 -  `AngularJS Material Version:` 1.1.4

**Comment by marjohr** [comment]
We're having the same problem with the following versions. 

**AngularJS Versions:** *
- AngularJS Version: 1.6.4
- AngularJS Material Version: 1.1.4

**Comment by marjohr** [comment]
We found the following way that seems to work for us at least. Found it in an Ionic thread. Could not find any documentation on the angular material docs page though.

`.config(['$mdGestureProvider', function ($mdGestureProvider) {
      $mdGestureProvider.skipClickHijack();
}])`

**Comment by czelusniakdawid** [comment]
I had the same issue. Thank you very much for sharing your solution!

**Comment by Splaktar** [comment]
As mentioned in https://github.com/angular/material/issues/10699#issuecomment-323320739 and in a number of other issues, `$mdGestureProvider.skipClickHijack();` is the solution to this issue.
