### ISSUE TITLE
tooltip: md-visible is not working

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#10695]
**Actual Behavior**:
 -  `md-visible` is not working with `md-tooltip`. I tried to give both of them boolean values but none of the effect happened.
 -  If we provide true value to it then it should be show tooltip on hover of the element and if we change the value of `md-tooltip` to false then it should not show the element.

**CodePen** (or steps to reproduce the issue): *
 -  https://codepen.io/jainshravan123/pen/rmgdQQ
 -  I took `md-visible="false"`. So `md-tooltip` should not appear but still it's opening.

**Comment by ElakiyaS** [comment]
Use latest version of angular-material atleast v1.1.4 supports.
https://material.angularjs.org/latest/angular-material.min.js

**Comment by Splaktar** [comment]
I updated [the CodePen](https://codepen.io/Splaktar/pen/MWaNBXX?editors=1010) to AngularJS Material `1.1.22` and `md-visible` is behaving as expected on `md-tooltip`.

`md-visible` doesn't disable the tooltip from working at all. It just sets the initial value and tracks the value as it changes via mouse hover.
