### ISSUE TITLE
codepen.io not working

### ISSUE THREAD

**Issue by gberger101** [angular/material#10692]
Just letting you know that the codepen.io examples are not working.

**Comment by ThomasBurleson** [comment]
@gberger101 - thank you. We are investigating.

**Comment by ThomasBurleson** [comment]
Dependent upon https://github.com/angular/material/issues/10734

**Comment by ThomasBurleson** [comment]
Fixed with SHA aa922904e6. Use https://material.angularjs.org/HEAD/
