### ISSUE TITLE
fix(ink ripple) - Tab InkRipple on Mobile

### ISSUE THREAD

**Issue by thienedits** [angular/material#107]
Ripple on tabs sometimes does not fade all the way out on mobile, specifically tested on Nexus 5. This happens the quicker and more time you click between tabs. Here is a screen recording of the behavior.

https://www.youtube.com/watch?v=16KEN9JMQ2k&feature=youtu.be

On a side note, on the radio buttons the ripple's opacity seem to get darker the more times you click on the radio button.

**Comment by shusain** [comment]
Having a somewhat related problem with buttons in a sidenav.  The md-ripple effect works fine in cases when I clearly touch down on a button and release my finger while still over that button.

If I touch down the ripple appears then I drag my finger away a bit and when I release my finger it's not over the button and consequently the button has the dark ripple color left behind it as though it is still being pressed.  Seems it can be reproduced on a Nexus 5 or Nexus 10 but doesn't happen on the desktop (this problem occurs on the angular material site as well as my app).

Any tips, workarounds or fixes welcome.
