### ISSUE TITLE
Incorrect Peer Dep

### ISSUE THREAD

**Issue by mcblum** [angular/material#10703]
Hey is there any way to update the peer dependencies so that we don't see these errors every time?

```
      01 warning "angular-material@1.1.3" has incorrect peer dependency "angular@>=1.3 <1.6".
      01 warning "angular-material@1.1.3" has incorrect peer dependency "angular-animate@>=1.3 <1.6".
      01 warning "angular-material@1.1.3" has incorrect peer dependency "angular-aria@>=1.3 <1.6".
```

It's possible ngMaterial is incompatible with 1.6 but I don't think that's the case or at least we haven't seen it break yet.

Thank you!
Matt

**Comment by henrymana** [comment]
I think there is still at least one more issue to resolve for full 1.6 support.

I see this open issue still:
https://github.com/angular/material/labels/needs%3A%20Angular%201.6%20support

**Comment by ThomasBurleson** [comment]
We have PR #10726  in-progress for AngularJS 1.6 support.
And with that PR, I think we can update our peer support to `"angular": ">=1.4 <1.7"`

> see  https://github.com/angular/bower-material/blob/master/package.json#L8-L10

**Comment by Splaktar** [comment]
This was fixed in https://github.com/angular/bower-material/commit/1148ba0f3ee1704ca61d3fe9ae5aecbb8fa62030.
