### ISSUE TITLE
select: orderBy selection

### ISSUE THREAD

**Issue by tiagojavaman** [angular/material#10705]
Hello, I have a **md-select multiple**, in which I would like to get the value in the select order.
Ex: [1,3,2]

Currently it returns [1,2,3] indifferent to the order of selection, any tips?

`$scope.itemList = [
{"ID":1,"Name":"Graphic 1"},
{"ID":2,"Name":"Graphic 1"},
{"ID":3,"Name":"Graphic 1"}
];`
`<md-select class="form-control" ng-model="test" multiple>
	<md-option ng-value="{{d.ID}}" id="{{d.ID}}" ng-repeat="d in itemList">{{d.Name}}</md-option>
 </md-select>`

Angular-material: v1.1.1

**Comment by AkhilNaidu09** [comment]
Try this

<md-select class="form-control" ng-model="test" multiple> <md-option ng-value="{{d.ID}}" id="{{d.ID}}" ng-repeat="d in itemList | orderBy:'d.Name'">{{d.Name}}</md-option> </md-select>

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

If the suggestion above does not resolve your issue, please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
