### ISSUE TITLE
calendar: not showing days

### ISSUE THREAD

**Issue by danillocesar** [angular/material#10704]
I created a simple md-calendar and its only showing the header but not days of the month.

Im using  AngularJS v1.6.4 and angular material v1.1.1

See screenshot

http://i.imgur.com/fLv0ZKz.png

**Comment by henrymana** [comment]
I don't think that works yet. There is a "TODO" in the code (datepicker/calendar.js) for a future enhancement...

"TODO: Support md-calendar standalone on a page (as a tabstop w/ aria-live announcement and key handling)."

**Comment by henrymana** [comment]
Should this issue be closed as "won't fix" since this is more of an internal directive for use only by the md-datapicker?

**Comment by Splaktar** [comment]
This should be working now and we even have a [demo for it](https://material.angularjs.org/latest/demo/datepicker#calendar) in the `md-datepicker` docs.
