### ISSUE TITLE
sidenav: how to implement the persistent push pattern

### ISSUE THREAD

**Issue by matt212** [angular/material#10707]
**we know that there exists slidenav in angular material**:
 -  `my query is how to achieve below feature ? *`

![slidenav](https://cloud.githubusercontent.com/assets/1698139/26617996/d596aee8-45f5-11e7-9e88-130e4f576c7a.gif)

**CodePen** (or steps to reproduce the issue): *
 -  `https://jsbin.com/seqola/2/edit?output`
 -  `Details:`
whereas my current only has singular view pattern. please refer attached screenshot for your reference !

![material version](https://cloud.githubusercontent.com/assets/1698139/26618070/4db3cbd6-45f6-11e7-8897-b9fb212cefc6.gif)

my objective is to how a lot of browser-based mobile apps have the primary navigation hidden out of the left of the screen, and when the toggle icon is pressed (toggled) in the top-right corner, the primary navigation slides out to the right about 2/3 of the way into the screen, i wanted to achieve the same using angular material ! is it feasible options to achieve it 

**AngularJS Versions**: *
 -  `AngularJS Version: angular1.5.7.js`
 -  `AngularJS Material Version: v1.1.3`

**Additional Information**:
 -  chrome
 -  Version 58.0.3029.110 (64-bit)
 -  Win 8.1

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Here you go: https://codepen.io/Splaktar/pen/PozyGbE?editors=1010
