### ISSUE TITLE
virtual-repeat: makes too many requests for items with large datasets

### ISSUE THREAD

**Issue by aeslinger0** [angular/material#10709]
**Actual Behavior**:
 -  `What is the issue? *` Even when scrolling down as fast as you can on ~12,000 records, getItemAtIndex gets called 20+ times - putting unneeded burden on the server.
 -  `What is the expected behavior?` That getItemAtIndex only get called if the user keeps the item index in the viewable area for a given amount of time - even a minimal num of milliseconds should do it.

**CodePen** (or steps to reproduce the issue): * Use md-virtual-repeat with +12,000 records and watch how often getItemAtIndex gets called even when scrolling quickly.
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.4
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 54.0.2840.59
 -  `OS: *` Windows 7 Enterprise
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. A CodePen demo is **required**.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
