### ISSUE TITLE
select: icon is wrongly positioned in IE11

### ISSUE THREAD

**Issue by johnjesse** [angular/material#10714]
**Actual Behavior**:
 -  `What is the issue? *`
The dropdown icon is in the wrong place in internet explorer
Open the following website in internet explorer: 
https://material.angularjs.org/HEAD/demo/select, the icon is very close to the text

it looks like this
![image](https://cloud.githubusercontent.com/assets/6839660/26731649/a0e54a2a-47ac-11e7-89a9-8aa684dcc849.png)

 -  `What is the expected behavior?`
Open the page in chrome and firefox, and observe that the drop down icon is at the far right of the select box:
 https://material.angularjs.org/HEAD/demo/select

it should look like this
![image](https://cloud.githubusercontent.com/assets/6839660/26731665/aadbd53a-47ac-11e7-8ba5-9d2230f8e4ea.png)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

See above, open the page in internet explorer

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

Browser: Internet Explorer, Version: 11.0.9600.18665CO

**The actual problem** is you are using `text-align: end` to define the position of the icon, Internet Explorer has no support for using end with `text-align` (note Edge also has questionable support according to MDN https://developer.mozilla.org/en-US/docs/Web/CSS/text-align?v=example)

**Solution**
Use `text-align: right` in ltr environments and `text-align: left` in rtl environments 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by johnjesse** [comment]
https://github.com/angular/material/pull/3840 It seems to have been raised before, although it is clearly not fixed

**Comment by Splaktar** [comment]
This was tweaked in https://github.com/angular/material/commit/70c0c6e80391026c09785c4703becb34a690ba7b, but that only made the carrot not show up under the text. It didn't fix the left-to-right alignment.

I'll try out the changes from https://github.com/angular/material/pull/3840/files to see if they are still effective.

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11544 posted to fix this.
