### ISSUE TITLE
Codepen link is broken on main site

### ISSUE THREAD

**Issue by DanielFurmanov** [angular/material#10713]
Hello, sorry for posting none-code-related issue, but in docs I am not able to "Edit in codepen". It just opens an https://codepen.io/pen/?  link.     Same in Chrome and Firefox.

**Comment by tilhari95** [comment]
same here
+1

**Comment by bonatoc** [comment]
same here.

**Comment by ThomasBurleson** [comment]
Duplicate of #10692
