### ISSUE TITLE
<md-autocomplete> needs change or select event on options

### ISSUE THREAD

**Issue by dihar** [angular/material#10724]
### I need a output event in `<option>` of `<md-autocomplete>` when we choose it.
I have a use case:
```html
<md-input-container>
  <input mdInput name="someSideInput" [(ngModel)]="someAnotherProperty">
</md-input-container>

<!--
options: {name: string; sideValue: string}[];
-->

<md-input-container>
  <input mdInput [(ngModel)]="autocompleteProperty" [mdAutocomplete]="autoComp" 
    name="autocompleteInput">
</md-input-container>
<md-autocomplete #autoComp="mdAutocomplete">
  <md-option *ngFor="let opt of options" 
    [value]="opt.name" 
    (click)="someAnotherProperty = opt.sideValue">
    {{ opt.name }}
  </md-option>
</md-autocomplete>
```
On choose autocomplete's option I need do some side effect with some local template variable (like `opt` in template). This template is working great. But on key interaction it doesn't work. `(keyup)` doesn't work. It's need to add output event on option `(choose)` or `(select)` .

The final result I want:
```html
<md-autocomplete #autoComp="mdAutocomplete">
  <md-option *ngFor="let opt of options" 
    [value]="opt.name" 
    (select)="someAnotherProperty = opt.sideValue">
    {{ opt.name }}
  </md-option>
</md-autocomplete>
```

It must work for click and key interaction.
Thanks!

**Comment by skonx** [comment]
Hi @dihar, did you try a (mouseover) instead? 
For the keystroke, I'm facing a similar issue : (keyup.enter) is not triggered and the default behavior is set value property with the specified (in your case opt.name).
Cheers.

**Comment by dihar** [comment]
@skonx, `(mouseover)` doesn't suitable for this case. And I said about high-level event: `(select)` or `(choose)`. Thanks.

**Comment by dihar** [comment]
Sorry, I wrong, I confused repositories. I said about 2.x material.
