### ISSUE TITLE
$mdOpenMenu undefined on initial page load till a $mdDialog.show is called 

### ISSUE THREAD

**Issue by Bartaf83** [angular/material#10723]
I have a md-menu working well since a long time in my app but then it stopped to work so i thought angular material weren't injected on the app controller but that wasn't the cause of this problem as also there is an md-dialog which still working well and i found that once i open the md-dialog, the md-menu start to work and the $mdOpenMenu which is passed as paramter on the md-menu template is no longer undefined.
i also noticed that when i partially reload the view where lie the md-menu, then it also start to work.

this is the template where is the md-menu :
```
<md-menu class="pp_menu" ng-controller="popupCtrl as basicm">
    <div class="ui-grid-cell-contents" style="text-align: center; vertical-align: middle;" ng-click="grid.appScope.openMenu($mdOpenMenu, $event, row, col)">{{grid.getCellValue(row, col)}}</div>
    <md-menu-content class="pp_menu_cnt" layout="column">
        <md-menu-item class="pp_menu_item" layout="column" md-autofocus="false" ng-repeat="item in basicm.items1">
            <md-button md-ink-ripple="{{item.rippleColor}}" ng-click="grid.appScope.menuItemClick($event, item, row, col )">
                <div layout="row"  layout-align="space-around center">
                    <svg ng-if="item.showLabelsColorOpt" class="coloricon" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
                        <path d="M24 24H0V0h24v24z" fill="none" />
                        <circle id="cicircle" cx="12" cy="12" fill="{{item.rippleColor}}" r="8" />
                    </svg>
                    <p flex>{{item.content}}</p>
                </div>
            </md-button>
        </md-menu-item>
    </md-menu-content>
</md-menu>
```

the function to open it : 

```
$scope.openMenu = function($mdOpenMenu, ev, row, col) {            

// some other code here
            console.log('%c $mdOpenMenu : ' + JSON.stringify($mdOpenMenu), 'background: blue; color: white; display: block;');   
            originatorEv = ev;
            $mdOpenMenu(ev);
        };
```

I also tried replacing $mdOpenMenu with $mdMenu and call $mdMenu.open(ev) later but i got "TypeError: Cannot read property 'open' of undefined" error.

**Comment by kientv** [comment]
The same to me. `$mdOpenMenu : undefined`

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. A CodePen reproduction is required.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

Are you adding `$scope.$mdOpenMenu = $mdOpenMenu` in your controller so that you can access it from the template?
