### ISSUE TITLE
select: aria-labelledby not supported on transcluded inputs

### ISSUE THREAD

**Issue by npbenjohnson** [angular/material#10738]
**Actual Behavior**:
 -  `What is the issue? *`
There is no declarative way to pass aria-labelledby into a transcluded input (such as md-select)
 -  `What is the expected behavior?`
aria-labelledby passed down from the input container when it fixes up "for" labeling, PR #10737

**Comment by Splaktar** [comment]
@npbenjohnson the first PR got messed up and you said that you would submit another PR and link it. Is there any chance that you can still do that? Is this issue still a concern for you? If so, can you please create a CodePen demo of the issue?
