### ISSUE TITLE
dialog: bindings not listening/changing when updated outside dialog controller

### ISSUE THREAD

**Issue by zwergius** [angular/material#10739]
I need to add a spinner to my dialog, this spinner I would like to toggle from the parent opening this dialog. However it seems I cannot update any bindings in the dialog. My plunker illustrates the issue with a timeout function changing the 'item' value.

I have even tried to do this through a service as well, but changes in the service is not reflected in the dialog either.

http://plnkr.co/edit/ctz9Jb1onM4rbHVVKa2R?p=preview

angular@1.6.4
angular material@1.1.4

**Comment by Splaktar** [comment]
You can use `scope: $scope` and pass in the parent controller's scope in order to share a reference to the same value and get data binding like you want.

Demo: http://plnkr.co/edit/Ahjd265NeOM3D2Ee
