### ISSUE TITLE
mdAutocomplete: dropdown list and scrolling

### ISSUE THREAD

**Issue by AkhilNaidu09** [angular/material#10730]
![830caf60-e1e3-11e4-9edb-9c97ec5a311c](https://user-images.githubusercontent.com/13352708/27087083-a7f2fb32-5071-11e7-8b65-a45609af079b.png)

Autocomplete Suggestion are in wrong position if we scroll the browser when the suggestions are in open state

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

I believe that this was fixed as I can't reproduce this. Using the mousewheel causes no scroll on the background window. Clicking on the scrollbar auto-hides the dropdown.
