### ISSUE TITLE
flex-gt-sm should have same behavior as flex on large screens for overflowing content

### ISSUE THREAD

**Issue by aeslinger0** [angular/material#10742]
**Actual Behavior**:
 -  `What is the issue? *` Using flex-gt-sm on large displays, text spills out of a div that has overflow:auto on it where using flex instead works.
 -  `What is the expected behavior?` flex-gt-sm should behave like flex on large screens

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/anon/pen/LLbbPp?editors=1000#anon-login
 -  `Details:` This happens in Chrome. IE miraculously works fine.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.4
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 54.0.2840.59
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by aeslinger0** [comment]
Here's a screenshot of that codepen as I see it in Chrome.

![image](https://user-images.githubusercontent.com/8813038/27187880-fe5990bc-51b1-11e7-9dde-04e90c519037.png)

**Comment by ThomasBurleson** [comment]
Ongoing support for flex-box layouts is only provided in @angular/flex-layout (for Angular 4.x and higher). The ngM1.x Layout engine will not be enhanced by the core team. Pull Requests are welcomed.
