### ISSUE TITLE
panel: relativeTo($event.srcElement) does not work

### ISSUE THREAD

**Issue by zhenya2224** [angular/material#10743]
**Actual Behavior**:
 -  `What is the issue? *` Cannot open any md-panel menu items on page https://material.angularjs.org/latest/demo/panel which have relativeTo($event.srcElement) using Firefox
 -  `What is the expected behavior?`  

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`  https://material.angularjs.org/latest/demo/panel try to open any panel item with relative positioning in Firefox
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.5
 -  `AngularJS Material Version:Latest`

**Additional Information**:
 -  `Browser Type:` Firefox 
 -  `Browser Version:`53.0.3
 -  `OS:` Windows 8
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by zhenya2224** [comment]
Its working if I use $event.target instead of $event.srcElement

**Comment by henrymana** [comment]
The samples (https://material.angularjs.org/latest/demo/panel) use MdPanelPosition for positioning. Where did you see $event.srcElement in the samples or documentation? Maybe the documentation needs to be fixed (can you point out where you saw it)?

https://material.angularjs.org/latest/api/type/MdPanelPosition
https://material.angularjs.org/latest/api/service/$mdPanel

This is how the sample sets the relative positioning:

var position = this._mdPanel.newPanelPosition()
      .relativeTo('.demo-menu-open-button')
      .addPanelPosition(this._mdPanel.xPosition.ALIGN_START, this._mdPanel.yPosition.BELOW);

Could you please close the issue if setting the position with MdPosition works?

**Comment by zhenya2224** [comment]
![123](https://user-images.githubusercontent.com/11735491/27535036-bd7fe8f2-5a71-11e7-9888-7fb5a9e2238c.png)
Please take a look. Open https://material.angularjs.org/latest/demo/panel in Firefox, and click the menu button 
![12443](https://user-images.githubusercontent.com/11735491/27535090-fe74f85c-5a71-11e7-8a0b-c0c4503966e6.png)
I described the issue as clear as possible.

**Comment by supruniuk** [comment]
It also doesn't work if to use class name:
      let position = this.$mdPanel.newPanelPosition()
      .relativeTo('.filter-toolbar')
      .addPanelPosition(this.$mdPanel.xPosition.ALIGN_END, this.$mdPanel.yPosition.BELOW);

**Comment by Splaktar** [comment]
Fixed by PR #11234 in `1.1.9`.
