### ISSUE TITLE
tabs: input inside md-tab-label does not handle spaces well

### ISSUE THREAD

**Issue by barzik** [angular/material#10751]
**Actual Behavior**:
 -  Insert input to md-tab-label repository
 -  You cannot insert spaces to the input.
 - It is happening because of [line 396 in tabsController.js](https://github.com/angular/material/blob/master/src/components/tabs/js/tabsController.js#L306)
Here is a [pull request](https://github.com/angular/material/pull/10752), tell me if it is )the desired path:

**Steps to reproduce the issue):**
 -  https://codepen.io/barzik/pen/RgpvRP
 -  `Details:` Just try to insert space to the input. It is important to me because the my usecase is allowing some users to edit the code.

**AngularJS Versions**: *
 -  `AngularJS Version: 1.6`
 -  `AngularJS Material Version: 1.1.4`

**Additional Information**:
 -  `Browser Type: All`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by andrewseguin** [comment]
An API change seems unnecessary for this since you can just prevent the input's event from propagating upward to the header.

**Comment by alimcharaniya** [comment]
Did you find a solution to enter spaces here? I have the same issue.

**Comment by Splaktar** [comment]
Re-opening this until we can provide a CodePen that demonstrates @andrewseguin's guidance in https://github.com/angular/material/issues/10751#issuecomment-351131181.

**Comment by Splaktar** [comment]
@alimcharaniya OK, here's the solution via [CodePen](https://codepen.io/Splaktar/pen/gzOObw?editors=1010#0). As hinted at by @andrewseguin, you can catch the keydown event on the input and avoid it getting propagated up to `md-tabs` via `event.stopPropagation()`.
