### ISSUE TITLE
mdChips: Option to convert pending value to a chip on "onblur"-event

### ISSUE THREAD

**Issue by BrunnerLivio** [angular/material#10753]
**Actual Behavior**:
 -  `What is the issue?` Often times when I enter something in a chips-input field I dont press the seperation key, because it actually looks like a normal text field. 
-  `What is the expected behavior?` I would like to have an option on the `md-chips` directive, like `md-create-chip-onblur` or something, which creates a chip from the text inside the input field, which is not a chip yet. 

Example:
1. Enter "asdf" into a chip-text field
2. Move focus
3. "asdf" should automatically be a chip now

Is there any workaround at the moment?

**Comment by norkunas** [comment]
@BrunnerLivio https://material.angularjs.org/latest/api/directive/mdChips

> md-add-on-blur
> boolean	
> When set to true, remaining text inside of the input will be converted into a new chip on blur.

**Comment by BrunnerLivio** [comment]
@norkunas Oups, overlooked that one, sorry! Thanks alot
