### ISSUE TITLE
toolbar(scroll-shrink): will not shrink if it is inside ng-include url page

### ISSUE THREAD

**Issue by clientsites** [angular/material#10755]
Take a standard md-toolbar code from the documentation page, added md-scroll-shrink="true" attribute, and put it to index.html.
Add a md-content with 20 paragraphs of lorum lipsum and put it to index.hml.

Everything works fine.

Extract the md-toolbar into a header.html.
Using ng-include to load header.html onto index.html.

md-scroll-shrink is not working anymore!

Is there a scope blocking with ng-include added?

**Comment by henrymana** [comment]
Could you post questions to the newsgroup? Or if you think it is a defect provide the details requested in the issue template? It's hard to tell what you are running into otherwise.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. It does not include a CodePen or StackBlitz reproduction of the issue.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
