### ISSUE TITLE
Datepicker background and font color

### ISSUE THREAD

**Issue by j-tee** [angular/material#10757]
![datepicker](https://user-images.githubusercontent.com/5064641/27391085-df4e6858-569a-11e7-94b3-6006726a6b60.png)
**Actual Behavior**:
 -  `What is the issue? *`
My date picker has a dark background with a dark colour for the fonts as indicated above
 -  `What is the expected behavior?`
A lighter background or a lighter font color to provide contrast

[SO](https://stackoverflow.com/questions/44652147/md2-datepicker-background-and-font-color) has not been very helpful so here I am hope somebody can help me out

**Comment by henrymana** [comment]
The issue you are reporting is for material 2. This repository is for angular material 1.

Could you close this issue and repost in the corresponding mailing list or github repo for material 2?

**Comment by j-tee** [comment]
Oh Sorry. My mistake
