### ISSUE TITLE
Publish all released versions of angular material to yarn & npm

### ISSUE THREAD

**Issue by jayanthm** [angular/material#10762]
There have been several versions being hosted on bower and not on yarn/npm. It would be helpful to people trying to just use one package manager if all versions can be found in both places. Few examples, v1.0.0-rc4 is available on bower but not on yarn.

**Comment by Splaktar** [comment]
@jayanthm this should be resolved as all recent releases have been published to NPM. If there is a specific release (not RC) that isn't on NPM, please let me know and I will see what I can do to fix that.

**Comment by miguelcobain** [comment]
@Splaktar as you can see on the npm page, the last version published is 1.0.10: https://www.npmjs.com/package/angular-material-source

**Comment by Splaktar** [comment]
@miguelcobain that should not be needed at all. You can see all of the recent releases listed on the Versions tab [here](https://www.npmjs.com/package/angular-material) or via `npm view angular-material versions`.

We also have instructions for installing on our [README](https://github.com/angular/material/tree/v1.1.10#npm) and more in depth instructions [here](https://github.com/angular/bower-material/#installing-angularjs-material).

**Comment by miguelcobain** [comment]
@Splaktar the problem is that package does not include angular material source files, just the built project.
angular-material-source package includes all the source files.

Some projects might want to use angular material sass stylesheets, for example.
Would it be to much of a problem to publish angular-material-source package as well?

**Comment by miguelcobain** [comment]
@Splaktar publishing the package myself was something I did not think about. Thanks for the heads up. 👍

**Comment by Splaktar** [comment]
@miguelcobain the source is included via `npm i angular-material` already:
![screen shot 2018-09-05 at 11 47 46 am](https://user-images.githubusercontent.com/3506071/45105153-a4a28c80-b101-11e8-9097-488bc1435814.png)

Under `modules/js` you can find all of the individual `.js` files. Under `modules/scss` you can find all of the SASS files.

We also have https://github.com/angular/material-tools if you want to build a custom version of AngularJS Material without layouts, etc.

**Comment by Splaktar** [comment]
If you have any further questions, please let us know via the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial).

**Comment by miguelcobain** [comment]
Thank you for bringing that up. Unfortunately it doesn't include the individual scss files, which is the only thing I really need.

There are individual css files, though, but that won't help sass users a lot.
