### ISSUE TITLE
md-selected-text calls function multiple times on single check

### ISSUE THREAD

**Issue by nikita-ag** [angular/material#10764]
While using md-selected-text, function is called multiple times on DOM load. Also whenever item is checked. its is called 2-3 times.

https://material.angularjs.org/HEAD/demo/select

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

**Comment by Artemas-Muzanenhamo** [comment]
@nikita-ag did you file a new issue because I am also having the same problem. I can also then post my resolution there as well and I have found a possible solution. Thanks.
