### ISSUE TITLE
Problem to bind [(ngModel)] in <md-radio-group> highlight at startup fails with class attribute

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/material#10761]
Hey people,

I'm using **Angular Material beta 7**, and I have a component with the following code snippet

```html
{{question.answer}}
<md-radio-group [(ngModel)]="question.answer" name="question{{i}}">
               <div id="problem" *ngFor="let alternative of question.alternatives" class="my-class">
                  <md-radio-button [value]="alternative.id">
                    {{alternative.title}}
                  </md-radio-button>
                  <div>remove<div>
                </div>
</md-radio-group>
```

if the `div#problem` has `class` attribute the  `[(ngModel)]="question.answer"` in md-radio-group doesn't bind when the component is started, see below behavior when `div#problem` does not have `class` attribute:

![example2](https://s9.postimg.org/9foqqi3xb/Screen_Shot_2017-06-21_at_22.04.48.png)

But if I add `class` attribute, the bind does not work when the component is started.

![example1](https://s9.postimg.org/rtz9uhg7z/Screen_Shot_2017-06-21_at_20.36.40.png)

**Demo**: http://plnkr.co/edit/k3xXPY?p=preview

**Simulate the problem when you add and remove `class` in `div#problem`**

**Comment by ThomasBurleson** [comment]
@GustavoCostaW  - My apologies sir. Your issue should be in the [Angular Material2 repository](https://github.com/angular/material2/issues/new). Could you copy ^ over to that repos plz.

> This is the repository for AngularJS v1.x and Material .

**Comment by GustavoCostaW** [comment]
@ThomasBurleson Ooops! sorry for this, I only clicked on your link and I did not pay attention to this repository, 

is done:

https://github.com/angular/material2/issues/5309
