### ISSUE TITLE
tabs: performance issues, Chrome, Firefox slow but Edge is fast (video)

### ISSUE THREAD

**Issue by PawelOwczarekFalcon** [angular/material#10768]
Animation in chrome and firefox are slower than Edge. I enclosed video url to watch how this issue is looking. Really I don't know how to fix it.

https://www.youtube.com/watch?v=3CPU3EheHT8

angular js 1.6.4 angular-material: 1.1.4

Tested on Windows 10 and Ubuntu 16.04 with Chrome 60 and 59 and fast computer

**Comment by trippal** [comment]
I think this is cause of  css (IE not use some css styles)... may be transitions + box shadow?

**Comment by PawelOwczarekFalcon** [comment]
appearance on IE is the same

**Comment by Splaktar** [comment]
This looks like a performance issue with `md-tabs`, can you please try the latest `1.1.11` preview to see if this helps? There are a number of perf fixes for tabs in this release.

https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.10-master-1512aa1/angular-material.js
https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.10-master-1512aa1/angular-material.css

**Comment by Splaktar** [comment]
Feedback on performance not provided. Should be fixed in `1.1.12`.
