### ISSUE TITLE
Toast fixed size on large screens

### ISSUE THREAD

**Issue by elmeerr** [angular/material#10765]
**Actual Behavior**:
 -  `What is the issue?`: Toast text message is wrapping on big screens
 -  `What is the expected behavior?`:  Toast size increases within it content

**AngularJS Versions**: *
 -  `AngularJS Material Version:` 1.1.4

Hi guys, I'm using toast and noticed that when I have it displayed on large screen, the size is fixed, this make the content inside `<span class="md-toast-text"></span>` be wrapped. As I imagined, this is cause because of this css:
`@media (min-width: 1920px) {
  md-toast .md-toast-content {
    max-width: 568px; } }`

So the max size is set, avoiding the toast to increase it size to fit it content. Is that the correct behavior?

Kind regards,

**Comment by abhinavpraneeth** [comment]
Same problem for me as well.
