### ISSUE TITLE
tabs: md-selected not being preserved when md-tab ng-repeat array data is changed

### ISSUE THREAD

**Issue by manish2535** [angular/material#10763]
**Actual Behavior**:
 -  `What is the issue? *` When the array on which the md-tab is repeating on changes, the selectedIndex is reset back to 0
 -  `What is the expected behavior?` The selectedIndex should remain at the same index even when the array is changed

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/manish2535/pen/jwLOaK?editors=1010
 -  `Details:` First change the selected Tab. Then click on the  UseDummy2 or UseDummy3 btn, the selectedIndex is changed to 0.

**AngularJS Versions**: *
 -  `AngularJS Version:` Happens in all
 -  `AngularJS Material Version:` Happens in all

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
So when the ng-repeat removes all of the tabs, the `MdTab` controller's `$destroy` listener is called which calls `removeTab()` for each of the tabs. Eventually this means that there are no tabs and thus no valid value for `selectedIndex`. Then as the new array data is used, the `MdTab` controller's `postLink` calls `insertTab()` for each tab. This adds each new tab, one at a time.

Hopefully this shows that you aren't just popping in an array to replace another like might be done via `ng-model`. Instead with how this is done using `ng-repeat`, as each tab is destroyed or linked, they are individually inserted/removed.

I would suggest that you keep a value of the `selectedIndex` and restore it after the array change. You may also want to add a progress spinner overlay or something else to hide the inkbar animation possibly going back to the first item and then jumping back to the selected item.

Please note that if you have a lot of content in these tabs, `md-tabs` will not perform great. It's recommended that you use `md-nav-bar` along with a router to performantly handle navigations between tabs with significant amounts of content or when many tabs are needed.
