### ISSUE TITLE
dialog: locals value passed to the dialog, when changed, effects source object

### ISSUE THREAD

**Issue by newmesiss** [angular/material#10778]
When I pass a row to the dialog and modify or add more parameters, these are saved when closing the dialog, passed the information and reflected in the ng-repeat

When closing the dialog should the row remain the same as it was from the beginning ??

     ´´´   vm.showAdvanced = function (ev, rowEmployee) {
            var employee = rowEmployee;
            $mdDialog.show({
                    controller: DialogController,
                    templateUrl: 'app/main/liquidaciones/liquidaciones-detail/dialog-liqui.tmpl.html',
                    parent: angular.element(document.body),
                    targetEvent: ev,
                    clickOutsideToClose: true,
                    fullscreen: true,
                    locals: {
                        employee: employee
                    }

                }) ´´´

**Comment by mckenzielong** [comment]
If I understood the issue correctly, then no, the row you passed in and modified while the dialog was open will change.  This is how javascript works and isn't really a bug with angular material.  Check out this stackoverflow post for a solid example: https://stackoverflow.com/questions/6605640/javascript-by-reference-vs-by-value

You can create a copy of the object using [angular copy](https://docs.angularjs.org/api/ng/function/angular.copy), but even that does have limitations.
