### ISSUE TITLE
Component request: Expansion panels

### ISSUE THREAD

**Issue by jaminroe** [angular/material#10779]
Would be nice if Expansion Panels could be added to the components provided. Materialize does them quite well: http://materializecss.com/collapsible.html

Thanks!

**Comment by djleonskennedy** [comment]
@jaminroe its easy to implement it without library

**Comment by jaminroe** [comment]
@djleonskennedy well I have no idea how. I'm not a developer

**Comment by cosmosdesigner** [comment]
Would be awesome if this component could be added!
Sure we could use https://www.npmjs.com/package/angular-material-expansion-panel, but why download one more dependency if we could just use a built-in one.

I vote +1 for this request.

Thx!

**Comment by pragalbrewengage** [comment]
+1

**Comment by avikawale** [comment]
Hi Angular Team,
is this part of any upcoming release  ?

**Comment by eknowles** [comment]
@Splaktar @mgol is this being developed?

https://material.io/guidelines/components/expansion-panels.html

If not I would love to build it

**Comment by Splaktar** [comment]
This component was investigated but there were issues found while trying to implement the animations properly. The expansion panel is available in Angular Material which can be used with ngUpgrade lite. Also the above linked library is another great option.

There are no plans to implement this component in AngularJS Material at this time. We're currently focused on non-destabilizing bug fixes, performance improvements, and accessibility improvements.
