### ISSUE TITLE
select: input floatPlaceholder lacks documentation

### ISSUE THREAD

**Issue by FrancisS** [angular/material#10771]
Documentation for input floatPlaceholder on component md-select should include the possible values which are always, auto and never.
https://material.angular.io/components/select/api 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by henrymana** [comment]
You seem to be working with material 2. This github project is for material 1.
