### ISSUE TITLE
Can support Persian calendar ?

### ISSUE THREAD

**Issue by saeedjalali1** [angular/material#10777]
**Actual Behavior**:
 -  `What is the issue? *`
         My problem is how to use Persian calendar in Angular Material?

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
In [material-ui](http://www.material-ui.com/#/components/date-picker) implement this feature. How we can do this? 
![image](https://user-images.githubusercontent.com/15178117/27673980-dc509652-5cb8-11e7-8005-9fa6552b2e5d.png)

**AngularJS Versions**: *
 -  `AngularJS Version:` 4  
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` firefox
 -  `Browser Version: *` 53
 -  `OS: *` Linux
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by m98** [comment]
Unfortunately Jalali calendar is not supported by Angularjs Material.

**Comment by Splaktar** [comment]
As mentioned in https://github.com/angular/material/issues/10211#issuecomment-411605151, there is some support for this in Angular Material, but there are no plans to add this to AngularJS Material.
