### ISSUE TITLE
theme: how to define contrast colors when extending a palette

### ISSUE THREAD

**Issue by shivanisaz** [angular/material#10782]
Angular Material Documentation for theming states the following to extend an existing palette for custom theming-

```
var neonRedMap = $mdThemingProvider.extendPalette('red', {
    '500': '#ff0000',
    'contrastDefaultColor': 'dark'
  });
```
In this, if i want to specify which color i want as the contrast using 

`'contrastLightColors': ['800']`

is it possible? Doesn't seem to be working at all. Just defaults to black on giving contrastDefaultColor.
Is defining a whole new custom palette for this the only option?

I can't exactly use color css property since there are icons also that need to take that color. All those icons are web components (Angular 1.5x) so i want a centralised control over the colors.

What should i do?

**Comment by Splaktar** [comment]
I posted a CodePen demo and a code snippet to show how to do this in https://github.com/angular/material/issues/9918#issuecomment-404634847. If you have more questions, please try the  [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial).
