### ISSUE TITLE
nav-bar: need to set a non-assignable expression for mdNavBar.mdSelectedNavItem

### ISSUE THREAD

**Issue by mrmashal** [angular/material#10783]
**Actual Behavior**:
 -  `What is the issue? *` need to set a non-assignable expression for mdNavBar.mdSelectedNavItem
 -  `What is the expected behavior?` prevent the exception: Expression 'selected | takeFirst:2' in attribute 'mdSelectedNavItem' used with directive 'mdNavBar' is non-assignable!

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/mrmashal/pen/RgJxzz?editors=1011
 -  `Details:` I need to use a filter in my mdSelectedNavItem to highlight tabs from parent states of ui-router without polluting my controller code. thanks

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.6
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *` 59.0.3071.115
 -  `OS: *` windows
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
I had to update the [CodePen demo](https://codepen.io/Splaktar/pen/QWEZdxa?editors=1010) to the latest AngularJS and AngularJS Material and add `md-nav-sref` to the `md-nav-items` to get it to render. Then clicking on a tab does indeed throw this exception:
```js
Error: [$compile:nonassign] Expression 'selected | takeFirst:2' in attribute 'mdSelectedNavItem' used with directive 'mdNavBar' is non-assignable!
https://errors.angularjs.org/1.8.2/$compile/nonassign?p0=selected%20%7C%20takeFirst%3A2&p1=mdSelectedNavItem&p2=mdNavBar
    at angular.js:138
    at parentSet (angular.js:11450)
    at parentValueWatch (angular.js:11463)
    at interceptedExpression (angular.js:17683)
    at Scope.$digest (angular.js:19262)
    at Scope.$apply (angular.js:19630)
    at HTMLAnchorElement.<anonymous> (angular-material.min.js:7)
    at defaultHandlerWrapper (angular.js:3891)
    at HTMLAnchorElement.eventHandler (angular.js:3879)
```

**Comment by Splaktar** [comment]
At this point, the best approach here is going to be handling this filtering and the model values coming in and out of `md-selected-nav-item` in your controller and not in the template.
