### ISSUE TITLE
Almost all of the CodePen links on the demos do not work anymore

### ISSUE THREAD

**Issue by aeslinger0** [angular/material#10781]
**Actual Behavior**:
 -  `What is the issue? *` Links to CodePen in the documentation bring up a blank CodePen.
 -  `What is the expected behavior?` The link should bring up the example.

**CodePen** (or steps to reproduce the issue): * Click on almost any CodePen link from any demo page.
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:` N/A
 -  `AngularJS Material Version:` All of the newer versions

**Additional Information**:
 -  `Browser Type: *` Any
 -  `Browser Version: *` Any
 -  `OS: *` Any
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by tusharshuklaa** [comment]
Hope this gets fixed soon, seeing a working demo and fiddling with code is really good for better understanding.

**Comment by Splaktar** [comment]
This was resolved.
