### ISSUE TITLE
md-tab focus first time

### ISSUE THREAD

**Issue by daniele-zurico** [angular/material#10799]
The first time that I load the tabs by default is set the first tab correctly however the opacity of the first tab is not set to 1. After that I click on it the opacity change in the correct way.
Is that an Issue or I'm missing something?
![screen shot 2017-07-14 at 11 52 34](https://user-images.githubusercontent.com/3193095/28209564-f8d1ae82-688a-11e7-921d-67afef413adb.png)

After I click
![screen shot 2017-07-14 at 11 53 04](https://user-images.githubusercontent.com/3193095/28209574-0388d3a0-688b-11e7-8854-8f33e873c4fe.png)

`<md-tab-group>
		<md-tab>
			<ng-template md-tab-label>
				All Orders
				<div class="bubble" #allOrdersBubble >{{allOrdersCount}}</div>
			</ng-template>
			<iag-all-orders (onPickup)="refreshItems()"></iag-all-orders>
		</md-tab>
		<md-tab>
			<ng-template md-tab-label style="opacity: 1">
				My Orders
				<div class="bubble"  #myOrdersBubble>{{myOrdersCount}}</div>
			</ng-template>
			<iag-my-orders (onRefresh)="refreshItems($event)"></iag-my-orders>
		</md-tab>
	</md-tab-group>`

**Comment by mckenzielong** [comment]
This repo is for the angularjs implementation of material.  Was this issue meant for the [angular material version?](https://github.com/angular/material2)
