### ISSUE TITLE
dialog: theme option not taken into account if no targetEvent

### ISSUE THREAD

**Issue by matthieusieben** [angular/material#10801]
**Actual Behavior**:
 -  `What is the issue? *` When the `targetEvent` option of `$mdDialog.show` is null, then the `theme` option is not take into account.
 -  `What is the expected behavior?` The theme should be taken into account regardless of the value of `targetEvent`.

```js
$mdDialog.show({
  template,
  theme: 'customTheme',
  targetEvent: event
})
```

If the `event` variable is null, then the theme is not take into account.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/anon/pen/VWOMGL
 -  `Details:` When `targetEvent` is null (checkbox not checked), then the custom theme is not applied.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.5
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 59.0.3071.115
 -  `OS: *`MacOS 10.12.5

**Comment by Splaktar** [comment]
Thank you for the report on this. There is certainly an issue with our documentation not calling out this requirement more clearly. That is being tracked in https://github.com/angular/material/issues/11229, where you can find a more in depth explanation.

Also https://github.com/angular/material/issues/11229#issuecomment-660627609 explains a way to set the theme w/o `targetEvent`.
