### ISSUE TITLE
angular.injector(['ng', 'myApp']) throw exception

### ISSUE THREAD

**Issue by caoyongfeng0214** [angular/material#10800]
cannot use `angular.injector([.....])`

**CodePen** (or steps to reproduce the issue): *
 -  https://codepen.io/cyf/pen/YQMjda

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.5
 -  `AngularJS Material Version:` 1.1.4

**Comment by Splaktar** [comment]
Looks like you just had some badly formatted brackets. Here's a [couple of examples](https://codepen.io/Splaktar/pen/KKdjdJr?editors=1010) of using the `$injector`. Though in this case, you could just inject it in the controller normally.
