### ISSUE TITLE
md-Maxlength not watch changes in md-Maxlength value

### ISSUE THREAD

**Issue by UserCoreNet** [angular/material#10806]
**Actual Behavior**:
 -  `What is the issue? *` When change value of md-Maxlength attribute (example: length = 30; md-maxlength='length', change length = 20, count not change ) 
 -  `What is the expected behavior?` when change md-maxlength by one int or empty -for remove-, detected changes correctly.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: 
 -  `AngularJS Version:` 1.6.5
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a CodePen reproduction demo. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

You can see in https://material.angularjs.org/latest/api/directive/mdInput that `md-maxlength` take a `number` type and not an `expression` type. It does not have a watcher and cannot be changed dynamically.
