### ISSUE TITLE
Add bidirectional support for all components

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#1080]
Most of the components support rtl but there are some components that don't work properly,

for example #964, #1068 or in the [list component ](https://github.com/angular/material/blob/629b753ff348b805e4ff73a2f66d354f2d42841d/src/components/list/list.scss#L42) that supports only ltr and needs to be overridden for fix.

![bidirectionally](https://cloud.githubusercontent.com/assets/6004537/5586800/e48438d8-90e1-11e4-85dc-decb63b7902a.png)

**Comment by EladBezalel** [comment]
@ThomasBurleson maybe you should add bi-directional label?

**Comment by ThomasBurleson** [comment]
@EladBezalel - label already created. assigning now.

**Comment by naomiblack** [comment]
@EladBezalel -- I am sad that we haven't been able to commit to more RTL support on our 1.0 timeline. This is a formal invitation from me: would you like to join us and help get these issues resolved in the next 2 weeks so we can have strong bidi support in our 1.0? I can't think of a better person to own it and really dig into the use cases. :)

Interested...? Please ping Thomas if you are available.

**Comment by EladBezalel** [comment]
@ThomasBurleson @naomiblack sure! thanks :)

**Comment by EladBezalel** [comment]
@naomiblack i contacted @ThomasBurleson, as i said, i'd love to help and will try to make myself available! thanks again it's very flattering!!

**Comment by Qlbaz** [comment]
من فضلك، كيف يمكنني تحويل اضافة md-tabs للاتجاه اليمين
مع العلم ان الشكل قمت بتحويله بطريقة صحيحة، ولكن ازرار md-next-button لم تعمل عندما قمت بتحويل الاجتاهات
ارجو توضيح ذلك الأمر

**Comment by Splaktar** [comment]
All of the listed issues appear to have been resolved prior to 1.0.0. Please submit new issues for any current bidi issues.
