### ISSUE TITLE
tabs: md-tabs-content-wrapper full height

### ISSUE THREAD

**Issue by FeeFelipe** [angular/material#10809]
I need to use 100% height of my page, but the element "md-tabs-content-wrapper" explode the 'md-tabs'

What did I miss?
[See preview](http://plnkr.co/edit/4nYFGYTVbTdbc8SXxw1F?p=preview)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
