### ISSUE TITLE
tabs: using a ton of cpu on host machine

### ISSUE THREAD

**Issue by shadow1349** [angular/material#10811]
To start off I am using a Windows machine (most current version of Windows 10 Enterprise).

I noticed that whenever I use the md-tabs and start switching in-between them the amount of CPU that that particular chrome tab is using spikes from about 3% up to 30%-40%

I want to note that this behavior ONLY occurs when I start switching tabs.
If you are loading pictures into that tab then that makes it even worse.

I have tested this and gotten the same behavior from these browsers:

Chrome 59.0.3071.115 (Official Build) (64-bit)
and
Firefox 54.0.1 (32-bit)

My computer is fairly powerful (i7 2.6gHZ and 32 gig of RAM).

You can recreate this issue by using the tabs here: https://material.angularjs.org/latest/demo/tabs and open up your task manager and watch the CPU usage spike.

This is starting to become a problem in my app as not all the computers are as powerful as mine in my company.

**Comment by SuperITMan** [comment]
Same issue for me... Really annoying

**Comment by shadow1349** [comment]
Does anyone have an answer for this or something that will help?

**Comment by Splaktar** [comment]
Please try out the latest builds mentioned here (https://groups.google.com/d/msg/ngmaterial/2u8PllMZjls/2nWmHUhCEQAJ) as they include a number of `md-tab` performance improvements including fixes to
- https://github.com/angular/material/issues/6375
- https://github.com/angular/material/issues/9690
- https://github.com/angular/material/issues/11377

**Comment by Splaktar** [comment]
Also since the OP did not use the issue template, I don't know which version of AngularJS Material you are trying to report this against. Was this encountered using the latest at the time (`1.1.4`)?

**Comment by Splaktar** [comment]
Also [md-nav-bar](https://material.angularjs.org/latest/demo/navBar) provides a higher performance (less feature rich) tabs component that is a better fit for tabs with more than a trivial amount of content (especially when data binding is involved). To make them even faster, you can use `md-no-ink-bar` to disable some of the animations as mentioned in [the docs](https://material.angularjs.org/latest/api/directive/mdNavBar).

**Comment by codymikol** [comment]
My company makes very heavy use of the tabs and we don't suffer from heavy CPU usage, at least not in recent versions.

**Comment by Splaktar** [comment]
@codymikol thank you for the feedback. This has been an area that has needed improvement for a long time and I think that it's come a long ways in the last year.
