### ISSUE TITLE
Dropdowns produce opaque overlay covering screen

### ISSUE THREAD

**Issue by mcverter** [angular/material#10813]
**Actual Behavior**:t 
 -  `What is the issue? *
When an element with a dropdown (eg: md-select or md-datepicker) is selected, it produces an overlay that obscures the rest of the screen.  In certain cases, it even covers over the dropdown options

 -  `What is the expected behavior?`
Users should be able to see the rest of the screen as well as the options provided by the dropdown

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.1

 -  `AngularJS Material Version:`1.1.0

**Additional Information**:
 -  `Browser Type: *`
Chrome 

 -  `Browser Version: *`
 -  `OS: *`
Any 
Dependant on screen size  => Laptop with MDPI screen, 12 inch Macbook pro
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by mcverter** [comment]
![angularmaterial](https://user-images.githubusercontent.com/1453956/28484184-fe3ebd7e-6e3e-11e7-9266-58d8ac9362dd.png)

**Comment by mcverter** [comment]
UI Elements:

![angularmaterial3](https://user-images.githubusercontent.com/1453956/28484241-48b6c98c-6e3f-11e7-84db-8e47473e70cb.png)

When Select is Pressed:
![angularmaterial](https://user-images.githubusercontent.com/1453956/28484242-48b8fe96-6e3f-11e7-8ef5-fb7f6ace680a.png)

W
![angularmaterial2](https://user-images.githubusercontent.com/1453956/28484240-48b6cac2-6e3f-11e7-9cf8-0dcdcf95d8a2.png)

**Comment by Splaktar** [comment]
This was fixed some time ago and should work fine in `1.1.12`. No demo was provided, so I can't provide an example of it working properly.
