### ISSUE TITLE
select: on click is producing a black background in IE11

### ISSUE THREAD

**Issue by praveenaccion** [angular/material#10817]
**Actual Behavior**:
 -  `What is the issue? *`
`md-select` in IE 11, on click, is producing a black background with a vertical scroll bar as shown in the attachment. This is not the issue in Chrome, Firefox, Edge and Safari browsers.
 -  `What is the expected behavior?`
It should not open that black background with a vertical scroll bar.

**CodePen** (or steps to reproduce the issue): * NA
 -  `CodePen Demo which shows your issue:` NA
 -  `Details:` NA

**AngularJS Versions**: *
 -  `AngularJS Version:` ~1.4.0
 -  `AngularJS Material Version:` 1.1.3

**Additional Information**:
 -  `Browser Type: *` IE 11
 -  `Browser Version: *` 11.483.15063.0
 -  `OS: *` Windows 10
 -  `Stack Traces:` NA

**Note:- In our web application, we have used `md-select` with some bootstrap styles. But i don't think, this will cause the issue, because issue is not re-producible in other browsers.**
![md_select_ie11_issue](https://user-images.githubusercontent.com/23306697/28613323-bdd990e0-720f-11e7-8605-84dbfe7f72f9.png)

**Comment by Splaktar** [comment]
I can't reproduce this in `1.1.12` and no demo was provided to verify that it was fixed.
