### ISSUE TITLE
chips: md-max-chips validation error not working as expected

### ISSUE THREAD

**Issue by mrmashal** [angular/material#10816]
md-max-chips validation doesn't allow the maximum number of chips specified.
e.g. with md-max-chips="2", model validation error is triggered when 2 chips are added.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.6
 -  `AngularJS Material Version:` 1.1.4

**Comment by kwkofler** [comment]
+1

**Comment by seriesoftubes** [comment]
+1

I'm able to repro when I remove all my chips, then re-add them.  When I do this, the $valid field says `false` when there are less than `md-max-chips` elements in my ng-model.

**Comment by lizy1630** [comment]
md-max-chips works but you have to add 1 to the count. eg md-max-chips="3" when you want maximum 2 chips

**Comment by mbarakaja** [comment]
I am having this same issue.

@lizy1630 , The behavior should be that, if the maximum number of chips (md-max-chips) are honored, the field must be considered valid and no the `md-max-chips - 1` approach that you are proposing.

**Comment by Splaktar** [comment]
This is fixed and available in `1.1.10`. You can see it in action in the [Validation Demo](https://material.angularjs.org/latest/demo/chips#validation).
