### ISSUE TITLE
progress-linear: should be mirrored when page direction is RTL

### ISSUE THREAD

**Issue by hovavo** [angular/material#10814]
**Actual Behavior**:
 -  `What is the issue? `
Linear progress doesn't change direction on RTL pages.

 -  `What is the expected behavior?`
When direction is RTL, progress should be represented as filling from right to left.

**CodePen**:
https://codepen.io/anon/pen/RZbJVe

**AngularJS Versions**: *
 -  `AngularJS Version:` Latest
 -  `AngularJS Material Version:` Latest

**Additional Information**:
 -  `Browser Type: All`
 -  `Browser Version: All`
 -  `OS: All`

**Comment by 3ehzad** [comment]
You can use this temproray solution in rtl pages:
md-progress-linear {
    transform: scale(-1, -1);
}

**Comment by hovavo** [comment]
Yep, that's just what I did :)

**Comment by marosoft** [comment]
It is still a problem in 1.1.21 for both linear and circular progress indicators.
I created [CodePen](https://codepen.io/marosoft/pen/bGVWaqZ) showing both.
