### ISSUE TITLE
menu: brings up a second scrollbar 

### ISSUE THREAD

**Issue by lauraerinmann** [angular/material#10822]
Request to re-open #3266 doesn't seem to be fixed unless i'm missing documentation in the current version.

**Comment by Splaktar** [comment]
#3266 can be reproduced on the menu demo page with `0.10.0`, but I can't reproduce this on https://material.angularjs.org/1.2.1/demo/menu. If you can provide a reproduction demo with a recent version of AngularJS Material, I would be happy to investigate further.
