### ISSUE TITLE
`<select>` elements are unclosed.

### ISSUE THREAD

**Issue by mikewest** [angular/material#10828]
**Actual Behavior**:
 -  `What is the issue? *`

https://bugs.chromium.org/p/chromium/issues/detail?id=750575#c5 describes a scenario in which a form is constructed. The form opens `<select>` elements, but never closes them. This is unfortunate, as Chrome is experimenting with dangling markup mitigations that prevent form submission in the presence of unclosed `<select>` elements (see https://bugs.chromium.org/p/chromium/issues/detail?id=680462 for some detail).

 -  `What is the expected behavior?`

The `<select>` elements should be closed. :)

Thanks!

**Comment by nuragic** [comment]
@mikewest Thanks! (I'm the guy who filed https://bugs.chromium.org/p/chromium/issues/detail?id=750575). 

Please, could you take a quick look also at this one? https://github.com/thingsboard/thingsboard/issues/132

Seems exactly the same error but, no experimental flags involved on there, apparently… 😕
