### ISSUE TITLE
autocomplete: screen reader should differentiate between the name of the combo box, and the selected option

### ISSUE THREAD

**Issue by RajivPrab-Google** [angular/material#10838]
**Actual Behavior**:

When selecting a value from an auto-complete, the screenreader reads it out as "{Combo box name} {Value} collapsed combo box". It's unclear to the user which part of the text read is the combo-box-name, and which is the value.

Expected: When selecting a value from an auto-complete, the screenreader should read it out as "{Combo box name} combo box collapsed {Value} selected"

**CodePen** (or steps to reproduce the issue): *

Download and enable the ChromeVox extension, on a Chrome browser. Go to https://material.angularjs.org/latest/demo/autocomplete. Enter an input, and select a value from the autocomplete.

**AngularJS Versions**: *

1.6.4-local+sha.617b36117

**Additional Information**:

Chrome 59.0.3071.115
MacOS Sierra

I'm a SWE at Google, and we're hitting this bug while trying to improve accessibility for an internal app we're building. My ldap is rajivprab@, if you'd like to chat further.

**Comment by Splaktar** [comment]
I was able to reproduce this on ChromeOS 69. I will read through https://www.w3.org/TR/wai-aria-1.1/#combobox to determine if there is a specific aria field that needs to be set or some other way to indicate that an item is selected versus just having text in the input read to the user.

Have you observed Chromevox working properly in any other combobox? I would love to take a look at an example/demo that works properly.

**Comment by Splaktar** [comment]
It looks like our current `md-autocomplete` a11y is implemented using the WAI-ARIA 1.0 combobox guidance which changed significantly in WAI-ARIA 1.1.

**Comment by Splaktar** [comment]
With the 1.1 implementation it will announce the following:
"{md-autocomplete aria-label} {Value} selected, Search"

If required:
"{md-autocomplete aria-label} {Value} selected, Required, Search"

**Comment by Splaktar** [comment]
I had to back off some of the changes in PR #11441 since WAI-ARIA 1.1 is not well supported yet and the GoogleChrome/accessibility-developer-tools only support WAI-ARIA 1.0. Those tools, even though currently unmaintained, are used in the presubmit process.

After making these changes, the fix to Chromevox works, but the text read is slightly different:
"{md-autocomplete aria-label} {Value} selected, Edit text, search entry"
