### ISSUE TITLE
autocomplete: when selecting an entry, ChromeVox screen reader does not notify user of the selection made

### ISSUE THREAD

**Issue by RajivPrab-Google** [angular/material#10837]
**Actual Behavior**:

When selecting an entry in an auto-complete, the screen reader reads out the entry name. Once the user hits enter, the reader simply says "entry deleted", and does not tell the user that a chip was successfully selected and added.

Expected behavior: When the user hits enter, the screenreader should notify the user in some way that the chip was successfully selected and added. It would be great if the screenreader also notified the user which chip exactly was added.

**CodePen** (or steps to reproduce the issue): *

Download and enable the Chromevox extension on a chrome browser. Go to https://material.angularjs.org/latest/demo/chips#custom-inputs, enter something into the auto-complete field, and select an auto-complete entry. This behavior was reproduced on chromevox-extension, on a chrome browser.

**AngularJS Versions**: *

1.6.4-local+sha.617b36117

**Additional Information**:

Chrome 59.0.3071.115
MacOS Sierra

I'm a SWE at Google, and we're hitting this bug while trying to improve accessibility for an internal app we're building. My ldap is rajivprab@, if you'd like to chat further.

**Comment by Splaktar** [comment]
This is also reproducible on VoiceOver for macOS. 

I've opened PR https://github.com/angular/material/pull/11403 to address this issue.
