### ISSUE TITLE
datepicker: md-autofocus not working

### ISSUE THREAD

**Issue by p1tt1** [angular/material#10836]
**Actual Behavior**:
 -  md-autofocus not working with md-datepicker

**CodePen** (or steps to reproduce the issue): *
 -  [jsfiddle Demo](https://jsfiddle.net/p1tt1/4onjc7yx/)

**AngularJS Versions**: *
 -  `AngularJS Version: 1.6.5`
 -  `AngularJS Material Version: 1.1.4`

**Comment by Splaktar** [comment]
From the [`md-autofocus` docs](https://material.angularjs.org/HEAD/api/directive/mdAutofocus):

> `[md-autofocus]` provides an optional way to identify the focused element when a `$mdDialog`, `$mdBottomSheet`, `$mdMenu` or `$mdSidenav` opens or upon page load for input-like elements.

> When one of these opens, it will find the first nested element with the `[md-autofocus]` attribute directive and optional expression. An expression may be specified as the directive value to enable conditional activation of the autofocus.

Your demo does not have a `$mdDialog`, `$mdBottomSheet`, `$mdMenu` or `$mdSidenav`.
