### ISSUE TITLE
Angular Material Description too long

### ISSUE THREAD

**Issue by fybwid** [angular/material#10843]
**Actual Behavior**:
 -  `What is the issue?`
Angular Material Description too long caused Angular Material Description in Yarn truncated,
Why i call it too long? [Check this](https://github.com/yarnpkg/website/issues/590)
`[main AngularJS Material repository](https://github.com/angular/materi`
from the [Yarn Registry](https://registry.yarnpkg.com/angular-material)

Screenshot from Yarn:
![angular material yarn](https://user-images.githubusercontent.com/17536001/29154099-88908554-7dc4-11e7-901f-db5423550a53.png)

 -  `What is the expected behavior?`
The description should contain full link to `[main AngularJS Material repository](https://github.com/angular/material)`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
Go to [source](https://yarnpkg.com/en/package/angular-material) 

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` Version 60.0.3112.90 (Official Build) (32-bit)
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/bower-material/commit/f573b8a84f7d5b5f9875b14c31b8aa5e8369a2b1.
