### ISSUE TITLE
Removing html background added by angular material

### ISSUE THREAD

**Issue by ryannz** [angular/material#10842]
How could I remove or set the background of the whole html added by angular material

`body.md-default-theme, body, html.md-default-theme, html {
    color: rgba(0,0,0,0.87);
    background-color: rgb(250,250,250);
}`

I can't seem to overwrite this in angular material css. Please check this demo:

https://embed.plnkr.co/DUoVpi20JODtHU2evviP/

I would love to remove the pink background or set the background to none (not the default grey).

Regards;

**Comment by Splaktar** [comment]
Something like the following will work:
```css
body.md-default-theme,
body,
html.md-default-theme,
html {
  background-color: white;
}
```
However, you will still have the theme background on items like the datepicker ([Example Demo](https://next.plnkr.co/edit/GkMoxTXl0D89sWoO)).

Note that I had to add the following to your `<head>`:
```html
  <link rel="stylesheet" href="style.css">
```
