### ISSUE TITLE
Fonts for Material Angular List

### ISSUE THREAD

**Issue by ghost** [angular/material#10841]
The image below demonstrates a list of items according to the material design specifications on [material.io](http://material.io). The issue I'm  facing is when I follow your example using Material Angular the fonts and design in general fails to resemble the fonts and design of the specifications. Could you take a look at this?

![Image](https://storage.googleapis.com/material-design/publish/material_v_11/assets/0B9msDEx00QXmZzEwU09Ta2lVbHM/components_lists_keylines4.png)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
