### ISSUE TITLE
has this project been ended?

### ISSUE THREAD

**Issue by alanpurple** [angular/material#10857]
please make us know

It's been a few month since there's no update or news or clues of improvements

**Comment by vitaly-t** [comment]
The next release is well overdue at this point.

**Comment by graingert** [comment]
@ThomasBurleson I currently use angular-material in production and am happy to help out maintaining while we still do.

**Comment by graingert** [comment]
:skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: :skull: ?

**Comment by ThomasBurleson** [comment]
@graingert  - your previous comment violated our code of conduct and was deleted. The Angular teams are attending off site events Thurs and Friday.. v1.1.5 will be released next week.

**Comment by graingert** [comment]
@ThomasBurleson great stuff. Can you mark this issue as closed?

**Comment by vitaly-t** [comment]
> The Angular teams are attending off site events Thurs and Friday.. v1.1.5 will be released next week.

We are all still hoping for this very much... ;)

**Comment by ThomasBurleson** [comment]
I am working to have v1.1.5 released this week of 9/5. Thank you all for your patience.
