### ISSUE TITLE
Unknown provider: $mdUtilProvider

### ISSUE THREAD

**Issue by cheshirefirewire** [angular/material#10858]
**Actual Behavior**:
I am getting this error when I try to use the material library in my angularjs application, I am using bower etc. but I have no idea where it is coming from.
`Error: [$injector:unpr] http://errors.angularjs.org/1.4.14/$injector/unpr?p0=%24mdUtilProvider%20%3C-%20%24mdUtil%20%3C-%20mdColumnDirective%20%3C-%20%24mdTheming`
[https://docs.angularjs.org/error/$injector/unpr?p0=$mdUtilProvider%20%3C-%20$mdUtil%20%3C-%20mdColumnDirective%20%3C-%20$mdTheming](https://docs.angularjs.org/error/$injector/unpr?p0=$mdUtilProvider%20%3C-%20$mdUtil%20%3C-%20mdColumnDirective%20%3C-%20$mdTheming)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`Unfortunately since it's a large codebase the issue could be coming from anywhere, I'm not sure how to reproduce it.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.4.14
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 60.0.3112.90 (Official Build) (64-bit)
 -  `OS: *` Mac Sierra v10.12.6
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by AkhilNaidu09** [comment]
Its looking like you missed to inject ngMaterial in your module

`angular.module('ExampleApp', ['ngMaterial','ngAnimate'])`

**Comment by Splaktar** [comment]
Please take a look at the [Getting Started Docs](https://material.angularjs.org/latest/getting-started).
