### ISSUE TITLE
Broken "Edit on Codepen" links

### ISSUE THREAD

**Issue by elise-fastpay** [angular/material#10852]
**Actual Behavior**:
Several "Edit on CodePen" links result in empty/blank CodePen rather than the demo as expected.

**Expected Behavior**:
CodePen link opens with pre-populated working Angular Material demo corresponding with the link user just clicked.

**CodePen** (or steps to reproduce the issue): *
1. Go to go to https://material.angularjs.org/latest/demo/chips (for example)
2. Click on an "Edit on CodePen" link in the demo toolbar
3. Observe blank CodePen opens

**AngularJS Versions**: *
 -  `AngularJS Version: N/A`
 -  `AngularJS Material Version: N/A`

**Additional Information**:
 -  `Browser Type: Chrome, Firefox`
 -  `Browser Version: latest`
 -  `OS: Mac OS X 10.12.6`
 -  `Stack Traces: N/A`

**Comment by LoganDupont** [comment]
It's already solved in #10692. Just go to the master branch https://material.angularjs.org/HEAD/demo/chips
