### ISSUE TITLE
Angular material flex grid system not working in IE11

### ISSUE THREAD

**Issue by aimad-majdou** [angular/material#10854]
**Actual Behavior**:
I have an application built with angularjs (1.5.5) and angular material (1.0.5).

I used the flex layout by the angular material, but I'm having an issue on IE11 when I zoom the webpage, the flex rows are getting overflowed on each other.

**CodePen**:
https://codepen.io/anon/pen/wqPBLa?editors=1010

**AngularJS Versions**: 
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.0.5

**Additional Information**:
 -  `Browser Type: *` Internet Explorer 
 -  `Browser Version: *` 11

**Comment by AkhilNaidu09** [comment]
@aimad-majdou can you please attahc the screenshot. Its working fine for me with the same codepen

**Comment by aimad-majdou** [comment]
Hi, sorry for my late answer, I've attached the screenshots on both IE11 and Chrome : 

![chrome](https://user-images.githubusercontent.com/16216620/31657651-d4e61af8-b326-11e7-8efa-f7d922ec66e5.PNG)
![ie11](https://user-images.githubusercontent.com/16216620/31657652-d50721f8-b326-11e7-88b8-6cdc562613a5.PNG)

**Comment by AkhilNaidu09** [comment]
@aimad-majdou Try this once hope it will work [codepen](https://codepen.io/anon/pen/rGQqgV?editors=1010)

**Comment by aimad-majdou** [comment]
@AkhilNaidu09  Thanks it worked

**Comment by AkhilNaidu09** [comment]
Welcome @aimad-majdou .. close this issue :+1:  Have a great day :-)
