### ISSUE TITLE
md-autocomplete clear text entry when item is not selected

### ISSUE THREAD

**Issue by nazhet** [angular/material#10865]
I would like to clear the text entry when no item is selected, this is causing me problems because the parameter is set as null. So if the text is empty the person will notice and will select again.

On my code the person can write a new word that does not exist and after needs to select this word to set the parameter, if don't select and only click outside, the word will still there but the parameter will be null.

**Comment by RodrigoFraga** [comment]
+1

**Comment by RodrigoFraga** [comment]
Estou com o mesmo problema

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

The param may be null, but your form should be marked invalid if `md-require-match` is set to true. Then you can make sure that the user can't submit without making a proper selection or clearing the text.
