### ISSUE TITLE
input-container(datepicker): label overlapping with carrot

### ISSUE THREAD

**Issue by apeeters** [angular/material#10860]
**Actual Behavior**:
 -  `What is the issue?`
When using `md-datepicker` with a long label in an `md-block` layout the label is not truncated and overlaps with the arrow.
![image](https://user-images.githubusercontent.com/180816/29462824-eddaac9c-8430-11e7-9d68-521e9ddc5bda.png)

 -  `What is the expected behavior?`
The text should be truncated similar to how md-select handles this.

**CodePen**:
https://codepen.io/anon/pen/VzQzaP

**AngularJS Versions: **
 -  `AngularJS Version:` 1.x
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type:` All browsers

**Comment by Splaktar** [comment]
Verified that this is still an issue in `1.1.12` via this [updated CodePen](https://codepen.io/Splaktar/pen/QYBwvN?editors=1010).

**Comment by Splaktar** [comment]
Is there any reason that you can't remove the `md-block` on the `md-input-container`? That seems to fix it ([CodePen](https://codepen.io/Splaktar/pen/Jqqpoj?editors=1010)).
