### ISSUE TITLE
bottom sheet - random items show as selected

### ISSUE THREAD

**Issue by 0101adm** [angular/material#10862]
**Actual Behavior**:
 -  `What is the issue? *`
opening as list or grid, random item has gray background
 -  `What is the expected behavior?`
should not show a gray background.  could confuse UX.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
https://material.angularjs.org/latest/demo/bottomSheet
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`

**Additional Information**:
 -  `Browser Type: *`
chrome 60, firefox 54
 -  `Browser Version: *`
 -  `OS: *`
OSX
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
For the list, it uses `md-autofocus="$index == 2"` to give the "Copy" action focus when opened.
For the grid, it always focuses the first item in my testing.

You didn't indicate the version of AngularJS Material that you were using, but this seems to be working as expected in 1.1.7.
