### ISSUE TITLE
making label and placeholder work together with * for required to be displayed with Label n not options in md-select

### ISSUE THREAD

**Issue by Saak-sri** [angular/material#10864]
**Actual Behavior**:
 -  `Not able to use label and placeholder go together and make it look like button or any other input.  *`

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a require CodePen reproduction demo. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
