### ISSUE TITLE
fab-speed-dial: items are behind toolbar

### ISSUE THREAD

**Issue by holtjonathan** [angular/material#10873]
**Actual Behavior**:
FABSpeedial items are being put behind a seconardy toolbar that my page has.  I would have expected these items to be displayed 'on top' of this toolbar.

**CodePen** (or steps to reproduce the issue): *
[https://codepen.io/anon/pen/gxBGbp?editors=1000](https://codepen.io/anon/pen/gxBGbp?editors=1000)
You will see the speedial items (1, 2, 3, 4, etc) are being put behind the secondary toolbar (marked as 'Secondary header')

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.0

Please see the codepen (above) or you can simply reference this screenshot: 
![fabspeeddial](https://user-images.githubusercontent.com/1995569/29779028-47b3a880-8bdf-11e7-8650-28963090f7a4.png)

**Comment by mckenzielong** [comment]
This is because the two toolbars have the same z-index.  They will be placed into the stacking context in the order they appear in the html.  Bumping your main toolbar up to z-index:3 will solve the problem.

https://codepen.io/mckenzielong/pen/prxVWb?editors=1000

**Comment by Splaktar** [comment]
As McKenzie said, this is an issue with both toolbars having the same `z-index`. [Updated CodePen](https://codepen.io/Splaktar/pen/QWjexoE) for `1.1.22`.
