### ISSUE TITLE
input: length property and model not updated after using IE "clear field" button

### ISSUE THREAD

**Issue by n0is** [angular/material#10872]
**Actual Behavior**:
 -  Using IE, WHEN an input has 'md-maxlength="x"' attribute AND the user clicks on the "Clear field" button ", THEN the field is cleared but the length property is not updated.
 -  The length property should be updated to display '0/x' in this case because the field is empty.

**Screen**:
![image](https://user-images.githubusercontent.com/5237095/29773088-1ea0fce6-8bfc-11e7-9370-cdd643d293a4.png)
This issue can be reproduced on the Angular Material website: https://material.angularjs.org/latest/demo/input

**AngularJS Versions**: *
 -  `AngularJS Material Version:` 1.1.4

**Comment by mckenzielong** [comment]
FWIW I also see this happening on a regular input too: https://plnkr.co/edit/s8B7cuhlUOtK8UBFudpz?p=preview

**Comment by Splaktar** [comment]
This is a bug in AngularJS: https://github.com/angular/angular.js/issues/11193

There is a PR for it (https://github.com/angular/angular.js/pull/14772) but it has been abandoned and no one has continued with the work yet.

This [StackOverflow question](https://stackoverflow.com/questions/28638389/handling-ies-clear-button-with-angularjs-binding) has a lot of possible workarounds.

If you are following Material Design, then I would suggest taking the [following approach](https://codepen.io/Splaktar/pen/OobyOw) to hide the `-ms-clear` buttons. Then you can add a clear icon button that aligns with the [Material Design Spec](https://material.io/archive/guidelines/components/text-fields.html#text-fields-layout) and works across all browsers.
