### ISSUE TITLE
md-table performance issue

### ISSUE THREAD

**Issue by fusionUI** [angular/material#10876]
**Actual Behavior**:
 -  `I have integrated the material dataTable and followed the exact same code provided in the sample(https://material.angular.io/components/table/examples).But the table is taking very long to just render the 100 rows and if you increase the loop count to 500 the browser gets stuck and finally gets crashed. This is behaving very poorly for just 100 or 500 rows, unexpected :(
 -  `What is the expected behavior?`
     500 rows are not that high to render on a browser. they should gets render with in few sec i believe.Moreover, even if its taking long there should be a busy spinner.

my requirement is to show all the available data using scroll and there is no paging expected

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version: 4.3.1`
 -  `AngularJS Material Version:material 2`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: Latest 60.0.3112.113 *`
 -  `OS: Windows`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Chan4077** [comment]
Please report [here](https://github.com/angular/material2/issues) instead of this repo.

**Comment by fusionUI** [comment]
Thanks posted ...can you confirm same for material 1 data table? any workable example for 500 rows of data

**Comment by henrymana** [comment]
Material 1 does not have an md-table component in core. There are some from the community in github but I have not used them.

**Comment by AkhilNaidu09** [comment]
Material 1 does not have md-table, may be you can refer this module (third party) https://github.com/daniel-nagy/md-data-table .

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
