### ISSUE TITLE
tooltip: wrong parent (pointer-events) when using ng-include

### ISSUE THREAD

**Issue by Hartaxfr** [angular/material#10878]
( bad english sorry :/ )

**Actual Behavior**:
 -  `What is the issue? *` If md-direction is bottom ( for exemple ), the md-tooltip is displayed on bottom of screen instead of bottom of the parent element.
 -  `What is the expected behavior?` The md-tooltip has to be next to its parent

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Can't reproduce with code pen because I need two html files
 -  `Details:` 

File 1
```
<body>
     <md-button>
          <md-tooltip>A</md-tooltip> <----- this one is not ok
     </md-button>
     <div ng-include="File 2"></div>
</body>
```
File 2
```
<div>
     <md-button>
          <md-tooltip>B</md-tooltip> <----- this one is ok
     </md-button>
</div>
```

The problem is that the parent of tooltip "A" is body instead of button.

![azeazeazeazeazeazez](https://user-images.githubusercontent.com/3418195/29871423-f79f555c-8d8b-11e7-9634-b88d93616b09.gif)

In tooltip.js : 

```
function MdTooltipDirective($timeout, $window, $$rAF, $document, $interpolate,
    $mdUtil, $mdPanel, $$mdTooltipRegistry) {

....

function linkFunc(scope, element, attr) {
    // Set constants.
    var tooltipId = 'md-tooltip-' + $mdUtil.nextUid();
    var parent = $mdUtil.getParentWithoutPointerEvents(element); <-----
    var debouncedOnResize = $$rAF.throttle(updatePosition);
    var mouseActive = false;
    var origin, position, panelPosition, panelRef, autohide, showTimeout,
        elementFocusedOnWindowBlur = null;

....

}
```
In util.js : 

```
/**
     * Scan up dom hierarchy for enabled parent;
     */
    getParentWithPointerEvents: function (element) {
      var parent = element.parent();

      // jqLite might return a non-null, but still empty, parent; so check for parent and length
      while (hasComputedStyle(parent, 'pointer-events', 'none')) {
        parent = parent.parent();
      }

      return parent;
    }
```

I have two solutions to fix my problem, add `style="pointer-event:all"` on concerned buttons or comment this loop :

```
while (hasComputedStyle(parent, 'pointer-events', 'none')) {
        parent = parent.parent();
      }
```

 I think this is because the "getParentWithPointerEvents()" function is called before the ng-include
 
**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.3
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` last
 -  `OS: *` X
 -  `Stack Traces:` X

**Comment by Hartaxfr** [comment]
But in any case, I'm not sure getting the first parent with pointer-events is a good solution. Normaly we just have to put the md-tooltip in element we want to display tootlip. With these lines : 

```
while (hasComputedStyle(parent, 'pointer-events', 'none')) {
        parent = parent.parent();
      }
```

we can't be sure what element handle the tooltip. Maybe an error or a warning in browser console like "md-tooltip can't be show if parent has pointer-events style put to none" instead of changing parent is a better solution ?

**Comment by Splaktar** [comment]
@Hartaxfr sorry for the delay on this. Is there any chance that you could create a reproduction in Plunker then? I created a template that you can use [here](https://plnkr.co/edit/YlsEz96i3CnRAntafd1j?p=info) it has the latest AngularJS Material 1.1.6 and AngularJS 1.6.7.

**Comment by Hartaxfr** [comment]
Do you have a plunker exemple with ui-router ? I'm not be able make this one running .. https://plnkr.co/edit/pOdfYFg9s3otEsrI5rBE?p=preview

**Comment by Hartaxfr** [comment]
I don't know how reproduce it in plunker ... I also try to include my own minified libraries but still working in plunker ...

**Comment by Splaktar** [comment]
No, sorry I don't have any ui-router + tooltip Plunkers available atm 🙁 

If it is easier for you to create a GitHub repo that contains the reproduction where we can debug it locally, then we can look at it there as well.

**Comment by Hartaxfr** [comment]
trying make lite version of my app for you, don't reproduce bug. I think some part of my code is in conflict with mdTooltip. Just strange I can't fix this behaviour by forcing "pointer-event:all;" on the md-tooltip parent element.

**Comment by Hartaxfr** [comment]
I'll tell you i found the reasons of the bug

**Comment by Splaktar** [comment]
Related to https://github.com/angular/material/issues/9464.

**Comment by Splaktar** [comment]
Going to close this as it appears to be specific to just this one app and a debuggable reproduction cannot be provided.
