### ISSUE TITLE
Md-select not focus out after changing 

### ISSUE THREAD

**Issue by arunparkcse** [angular/material#10877]
**Actual Behavior**:
 -  `What is the issue? *`
     In the form one particular value is selected next input box to be focus  "But md-select not reliving there focus after selected it self" 
 -  `What is the expected behavior?`
      In My form i need to change the selected drop down value next input to be focus 
**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which includes a require CodePen reproduction demo. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
