### ISSUE TITLE
how to make md-toolbar fixed?

### ISSUE THREAD

**Issue by AkbarAlam** [angular/material#10887]
I need to make md-toolbar fixed. I have written exrtra CSS rules for it. did not worked. how can i do that?

**Comment by AkhilNaidu09** [comment]
share me the codepen or jsfiddle link.

**Comment by DollarAkshay** [comment]
Can you post a minimalist code pen demo ?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
