### ISSUE TITLE
select: throws exception on keyboard interaction when an option is hidden

### ISSUE THREAD

**Issue by a300600st** [angular/material#10880]
**Actual Behavior**:
 -  `What is the issue? *`
When you hide an `md-option` inside an `md-select` interaction with the select using the arrow keys causes an exception.
 -  `What is the expected behavior?`
Arrow key navigation should work normally with no uncaught exceptions.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
https://codepen.io/a300600st/pen/rzPNjq
 -  `Details:`
Steps to trigger the exception:
1.  Open the debugging console.
2.  Click the placeholder text to open the select menu.
3.  Press the down arrow to attempt to select an option.
4.  See `Possibly unhandled rejection...` exception is output to the console.

**AngularJS Versions**: *
 -  `AngularJS Version:`
1.6.6
 -  `AngularJS Material Version:`
1.1.4

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
60.0.3112.113
 -  `OS: *` Windows
10
 -  `Stack Traces:`

Hiding the first option is a common workaround for preventing the first visible option from being highlighted when the select is opened for the first time.

I've also encountered the same exception when hiding the entire `md-select` options popup with css. I did this in order to reposition the popup after it had been positioned by angular-material because it wasn't placing my popup correctly (I had used custom styling to display the select options in three columns).

**Comment by Splaktar** [comment]
It looks like this has been fixed. I was able to verify that the issue exists in your demo using `1.1.4`, but after [updating to](https://codepen.io/Splaktar/pen/OJXBWjR?editors=1010) `1.2.1`, there is no longer an exception thrown here.
