### ISSUE TITLE
ripple: incorrect positioning behaviour

### ISSUE THREAD

**Issue by artch** [angular/material#1088]
I investigated some weird cases in ripple behavior and found [this piece of code](https://github.com/angular/material/blob/master/src/core/services/ripple/ripple.js#L209) in the ripple service:

```javascript
if (options.outline) {
    elem.css({
      borderWidth: (size * 0.5) + 'px',
      marginLeft: (size * -0.5) + 'px',
      marginTop: (size * -0.5) + 'px'
   });
} else {
  elem.css({ left: '50%', top: '50%' });
}
````

Last statement (line 209, `elem.css({ left: '50%', top: '50%' })`) causes inconsistent behavior of ripple positioning. Here are some examples:

_With line 209 included:_
 ![](http://i.imgur.com/QSBCz8r.gif)

_With line 209 commented:_
![](http://i.imgur.com/l5Tmb2s.gif)

What is that last `elem.css` statement for? It seems to be something not supposed to be there.

**Comment by EladBezalel** [comment]
:+1: seems very odd.. Who wrote this?

**Comment by ThomasBurleson** [comment]
@artch - The commented code seems to yield a much better UX.

**Comment by robertmesserle** [comment]
This was done according to the Material spec, as demonstrated in the first animation on this page:

http://www.google.com/design/spec/animation/responsive-interaction.html#

**Comment by robertmesserle** [comment]
Also, this centering animation is important for the held state; however, I believe that earlier, this part of the animation was slowed down to make it less apparent unless you actually held the click.  In either case, we should look into ways to make it fit better.

**Comment by ThomasBurleson** [comment]
@robertmesserle  - the corner-clicks [with line 209 included] definitely looks odd.

**Comment by robertmesserle** [comment]
Agreed, this is emphasized by the square button and the non-filling ripple.
We should probably add the ability to override the default settings for
situations like this. Not only does the centering effect look weird, but
any held state will look off as well in this example.

**Comment by ThomasBurleson** [comment]
:+1:

**Comment by robertmesserle** [comment]
I added an attribute to allow you to override the ripple sizing based on your use-case:

https://material.angularjs.org/#/api/material.components.button/directive/mdButton

You would want to add `md-ripple-size="full"`

**Comment by ilanbiala** [comment]
@robertmesserle what is the default?

**Comment by robertmesserle** [comment]
So the default functionality is that with md-fab buttons, it fills the available space whereas non-fab buttons will fill 80% of the space.  This is based on the material spec; however, in this example, that looks way off for a square button.

Specifying either 'full' or 'partial' will override the existing logic with your choice.

**Comment by ilanbiala** [comment]
@robertmesserle the ripple code is based off which Material sample? They seem to go more edge-to-edge and a little bit faster, no?

**Comment by robertmesserle** [comment]
If you look here:
http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons

Under the heading of "buttons in motion" they have an animation in which the ripples do not fill the buttons.

There is also an example of this with list items in the first example on this page:

http://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-user-input

Of course, the middle example shows it filling the space, so both are supported in different circumstances.

**Comment by ilanbiala** [comment]
Ok I was thinking of the middle one, so I just wanted to clarify.
