### ISSUE TITLE
virtual-repeat: with md-table - classes in rows not updating properly

### ISSUE THREAD

**Issue by mckinleymedia** [angular/material#10889]
I have rows with conditional classes inside the table cells. These show properly on the initial visible items, but drop some classes when scrolling. I've tried multiple ways of creating the classes: class="{{item.class}}", ng-class="item.class", ng-class="{'text-danger': item.value > 10}". Scrolling up and down, changes which rows have the problem. The data is correct, but the rows aren't updating properly.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
