### ISSUE TITLE
select: opens upward instead of downward

### ISSUE THREAD

**Issue by alexlavriv** [angular/material#10883]
Hello, When I set a defualt value as the last option in the options list, the md-select opens upward instead of downward. I would like it to open only downward.
Here is a example : 
https://jsfiddle.net/AlexLavriv/ya6eu8kz/21/

**Comment by AkhilNaidu09** [comment]
positioning of options list will based of the option that you have select. if you want to open list alway downwards means this is the workaround we have upto now.

open angular-material.js file

change shouldOpenAroundTarget to **True**,

```
function calculateMenuPositions(scope, element, opts) {
      var
        containerNode = element[0],
        targetNode = opts.target[0].children[0], // target the label
        parentNode = $document[0].body,
        selectNode = opts.selectEl[0],
        contentNode = opts.contentEl[0],
        parentRect = parentNode.getBoundingClientRect(),
        targetRect = targetNode.getBoundingClientRect(),
         shouldOpenAroundTarget = true,

```

**Comment by Splaktar** [comment]
It appears that you are using AngularJS Material `1.1.0`. I was able to get the JSFiddle to load in Safari, it crashes in Chrome. I made some changes to it to get it to load in Chrome, [here](https://jsfiddle.net/splaktar/amhwydur/13/).

The above comment is correct that this behavior is intended. It aligns with the Material Design [spec for menus](https://material.io/archive/guidelines/components/menus.html#menus-behavior):

> Menus are positioned over their emitting elements such that the currently selected menu item appears on top of the emitting element.

![Screen Shot 2020-10-24 at 22 51 32](https://user-images.githubusercontent.com/3506071/97097787-7cf94000-164b-11eb-9ed8-d725320d4786.png)
