### ISSUE TITLE
Angular Material CSS helpers?

### ISSUE THREAD

**Issue by Extarys** [angular/material#10893]
Not an issue per se.

I'm comming from jQuery/Bootstrap and I'm now diving in AngularJS with Material.

I was trying to figure out if there is some kind of sass/css library for badges, forms, avatar etc to avoid making all of those classes manually (like bootstrap).

Typing those terms on the internet only  gives me bootstrap themed as Material. Not the Ng material library stuff. Just to but buttons over a md-list which is inside a md-sidenav need css. A css helper would easily take care of many things we need to type in every project.

I also feel that there is still many little things to be added for it to be a complete Material Design. (Like those said above. Don't get me wrong, I love the work that is being done here. I was just wondering if those are planned or if not if there is already a similar scss/css somewhere I didn't find.

Sorry if this is a duplicate or something.

Thanks guys!

Was meant for Material2 - Sorry

**Comment by AkhilNaidu09** [comment]
I think we dont have badges, forms, avatar UI controls in angular material

these are the list of components they planned in material design [List of Material Design Components](https://material.io/guidelines)

May be we should use bootsrap for other components

**Comment by Extarys** [comment]
i understand those aren't directly related to material but it would give concistancy and make lifes easier. a small scss library as an addon could do. im nit familiar enough with the Material guidelines to make something conscistant with the guideline though. it was a general suggestion.

**Comment by Splaktar** [comment]
As you mentioned Material2, I'm going to close this. Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
