### ISSUE TITLE
page positioning  jumps up after closing select or dialog

### ISSUE THREAD

**Issue by desfarik** [angular/material#10897]
**Actual Behavior**:
after upgrading chrome to 61 page positioning jumps up after closing select or dialog.
Expected Result: page positioning does not jump up after closing select or dialog.

**CodePen** 
click to select, and close it
https://codepen.io/anon/pen/xXKvOL?page=2

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.4.3
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: ` CHROME 61, ff 55, ie 11
 -  `OS: `ubuntu 16.4, win 10

**Comment by amritk** [comment]
I just had a client complain about this as well, its horrible on a massive page to have to scroll all the way to the bottom again.

**Comment by amritk** [comment]
Possible dupe 
https://github.com/angular/material/issues/10719

**Comment by amritk** [comment]
Just tested and its fixed in the latest version of angular material 1.1.5

**Comment by Splaktar** [comment]
[CodePen](https://codepen.io/Splaktar/pen/BYJvxL?page=2) that validates the fix is still working in 1.1.7.
