### ISSUE TITLE
md-maxlength incorrect count of the number of characters in a multi-line text.

### ISSUE THREAD

**Issue by crewbeat** [angular/material#10890]
Actual Behavior:

What is the issue? * I have a textarea md-maxlength = "4000" when I enter a multi-line text and fill it up to 4000 characters, then when I try to save the data an error falls, if you copy this text to notepad ++ there will be more than 4000 characters. (As I understand, the problem is that the newline count as one character in js, but we have 2 '\r\n')
What is the expected behavior? When I enter multi-line text, the counter must correctly show the number of characters no matter what line breaks we use.

AngularJS Versions:

AngularJS Version: 1.5.8
AngularJS Material Version: 1.1.4
Additional Information:

Browser Type: *
Browser Version: *
OS: Windows 10

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. A CodePen demo with reproduction steps is required.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
