### ISSUE TITLE
panel: trackedPanels caching issue

### ISSUE THREAD

**Issue by IMM0rtalis** [angular/material#10894]
**Actual Behavior**:
 -  `What is the issue? *`
```
this._trackedPanels[config.id] = panelRef;
```
config.id is 'undefined' for the first run where no config with id is stored yet.
[https://github.com/angular/material/blob/v1.1.5/src/components/panel/panel.js#L1160](https://github.com/angular/material/blob/v1.1.5/src/components/panel/panel.js#L1160 )
 -  `What is the expected behavior?`
The code should use the id in this._config -> this._config.id

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.x
 -  `AngularJS Material Version:` from the beginning till 1.1.5 

Actually this is a bug nobody noticed before and i think it makes no real damage, but it is still a bug.
Before I would make a simple PR I wanted to ask if you see also the problem and if I should make this simple fix the way i described it.

I would like to do my part in stabilizing angularJS material! 

 Best,
Florian

linking @bradrich as creator of this feature
and @ThomasBurleson as active project-lead of this repo :)

**Comment by IMM0rtalis** [comment]
Introduced in https://github.com/angular/material/pull/9379

**Comment by IMM0rtalis** [comment]
@Splaktar can you label this pls? - I'll try to make a PR the next two weeks.

**Comment by Splaktar** [comment]
Please provide a CodePen demo where this exception can be observed.

**Comment by Splaktar** [comment]
@IMM0rtalis is this addressed in https://github.com/angular/material/issues/11133? or is this still an issue?

**Comment by IMM0rtalis** [comment]
Still an issue, but I think I will not fix this in the next two months. But it is one of my all-time-open-tabs in the browser :D

**Comment by Splaktar** [comment]
I tried making this change but it breaks 350 tests.

For common tests the values of `this._config` and `config` are quite different:
For "'should retrieve and apply a preset when the preset name is provided during the create or open method",
config:
```js
{id: 'panel_0', scope: Scope{$id: 2, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null, $$watchers: null, $parent: Scope{$id: ..., $$childTail: ..., $$childHead: ..., $$prevSibling: ..., $$nextSibling: ..., $$watchers: ..., $parent: ..., $$phase: ..., $root: ..., $$destroyed: ..., $$suspended: ..., $$listeners: ..., $$listenerCount: ..., $$watchersCount: ..., $$isolateBindings: ..., $$asyncQueue: ..., $$postDigestQueue: ..., $$applyAsyncQueue: ...}, $$phase: null, $root: Scope{$id: ..., $$childTail: ..., $$childHead: ..., $$prevSibling: ..., $$nextSibling: ..., $$watchers: ..., $parent: ..., $$phase: ..., $root: ..., $$destroyed: ..., $$suspended: ..., $$listeners: ..., $$listenerCount: ..., $$watchersCount: ..., $$isolateBindings: ..., $$asyncQueue: ..., $$postDigestQueue: ..., $$applyAsyncQueue: ...}, $$destroyed: false, $$suspended: false, $$listeners: Object{$destroy: ...}, $$listenerCount: Object{$destroy: ...}, $$watchersCount: 0, $$isolateBindings: null}, attachTo: Object{0: <div ng-app=""></div>, length: 1}, bindToController: true, clickOutsideToClose: false, disableParentScroll: false, escapeToClose: false, focusOnOpen: true, fullscreen: false, hasBackdrop: false, propagateContainerEvents: false, transformTemplate: function() { ... }, trapFocus: false, zIndex: 80, panelClass: 'preset-container', template: '<div>Hello World!</div>'}
```
this._config: `{}`

For "should create and open a basic panel"
config:
```js
{id: 'panel_1', scope: Scope{$id: 4, $$childTail: null, $$childHead: null, $$prevSibling: null, $$nextSibling: null, $$watchers: null, $parent: Scope{$id: ..., $$childTail: ..., $$childHead: ..., $$prevSibling: ..., $$nextSibling: ..., $$watchers: ..., $parent: ..., $$phase: ..., $root: ..., $$destroyed: ..., $$suspended: ..., $$listeners: ..., $$listenerCount: ..., $$watchersCount: ..., $$isolateBindings: ..., $$asyncQueue: ..., $$postDigestQueue: ..., $$applyAsyncQueue: ...}, $$phase: null, $root: Scope{$id: ..., $$childTail: ..., $$childHead: ..., $$prevSibling: ..., $$nextSibling: ..., $$watchers: ..., $parent: ..., $$phase: ..., $root: ..., $$destroyed: ..., $$suspended: ..., $$listeners: ..., $$listenerCount: ..., $$watchersCount: ..., $$isolateBindings: ..., $$asyncQueue: ..., $$postDigestQueue: ..., $$applyAsyncQueue: ...}, $$destroyed: false, $$suspended: false, $$listeners: Object{$destroy: ...}, $$listenerCount: Object{$destroy: ...}, $$watchersCount: 0, $$isolateBindings: null}, attachTo: Object{0: <div ng-app=""></div>, length: 1}, bindToController: true, clickOutsideToClose: false, disableParentScroll: false, escapeToClose: false, focusOnOpen: true, fullscreen: false, hasBackdrop: false, propagateContainerEvents: false, transformTemplate: function() { ... }, trapFocus: false, zIndex: 80, template: '<div>Hello World!</div>'}
```
this._config: `{template: '<div>Hello World!</div>'}`

**Comment by Splaktar** [comment]
There is certainly something funky here.

```
'this._config.id: panel_2'
'config.id: undefined'

'this._config.id: panel_0'
'config.id: undefined'

'this._config.id: panel_26'
'config.id: undefined'
```
`this._trackedPanels[undefined] = panelRef;` seems to be passing the tests but something like `this._trackedPanels['panel_0'] = panelRef;` causes failures.

**Comment by Splaktar** [comment]
Ugh, it looks like my build or browser cache got broken somehow. I cleared and restarted things and now this change isn't causing failures. 😕

**Comment by Splaktar** [comment]
It looks like this caching was working for tooltips (`config.id === md-tooltip-1746`), but not panels (`config.id === undefinfed`).
