### ISSUE TITLE
md-tooltip: Text doesn't expand from small circle like background

### ISSUE THREAD

**Issue by epelc** [angular/material#1090]
When an `md-tooltip` is shown the text will appear first then you can see the gray background expand from a circle in the center. This leaves you with the text looking weird outside the circle while it expands at first.

I don't think it's to high of priority but I did want to mention it here so we could track it's progress. Let me know if you need a video/gif to show this you have to look closely to see it. Also note it's easiest to see with a longer tooltip message.

**Comment by robertmesserle** [comment]
Let's delay the text fade-in so that it is not visible until after the background is present.

> Will also look into more performant ways to have it masked by the background, but in previous iterations, this was not very smooth.
