### ISSUE TITLE
ng-click on md-list-item not triggered

### ISSUE THREAD

**Issue by lbrevity** [angular/material#10902]
When defining an ng-click on a md-list-item, the action is never triggered in any browser. I'm using angular material js of v1.1.3. But If I change to v1.1.5, it works. But I can't change replace js.

**Comment by eknowles** [comment]
this needs more information. can you replicate it with codepen?

**Comment by DollarAkshay** [comment]
Can you post a code pen demo ?

**Comment by Splaktar** [comment]
I believe that this was fixed some time ago, but PR https://github.com/angular/material/pull/11877 added some additional fixes with list item click handling in `1.1.22`.
