### ISSUE TITLE
Cant close md-select multiple when inside md-dialog

### ISSUE THREAD

**Issue by sam-g-roberts** [angular/material#10903]
**Actual Behavior**:
 -  `What is the issue? *`After opening an "md-select multiple" dropdown within md-dialog. You can not click outside the md-select to close it, therefore there is no method to close the dropdown.
 -  `What is the expected behavior?`When clicking outside the md-select but inside the dialog md-select should close.

**CodePen** (or steps to reproduce the issue): *
 -  `Details:`Add any md-select inside a dialog. Open the md-select dropdown. Click outside the drodown but inside the dialog, it will not close

**AngularJS Versions**: *
 -  `AngularJS Version:` angular#1.5.9
 -  `AngularJS Material Version:` angular-material#1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *`Chrome
 -  `Browser Version: *` 60.0.3112.113
 -  `OS: *` Mac OS 10.12.5

**Comment by gbruins** [comment]
I am not experiencing this issue with angular-material 1.1.1

**Comment by gvorster** [comment]
I'm using 1.1.5 and have the same issue.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. Can you please provide a CodePen demo or a link to a demo that reproduces this issue?

**Comment by Splaktar** [comment]
We need a CodePen demo to be able to debug and investigate this.
