### ISSUE TITLE
gesture: using highcharts on iphone causes taps to be ignored

### ISSUE THREAD

**Issue by tstinku** [angular/material#10905]
**Actual Behavior**: 
 I am using highcharts library for column graph,there is y-axis as population, x-axis as years and one toggle button like village and city which toggle population only village or city. In all platform it ok but in iphone only toggle button not work 
 -  `What is the issue? *`
toggle button not work of highcharts in iphone.
 -  `What is the expected behavior?
toggle button should work as normal all platform.

**CodePen** (or steps to reproduce the issue): * https://codepen.io/tstinku/pen/dVoWjw
open codepen with given demo first in any platform except iphone and try to click on village/city button then it will toggle as expected but in iphone it it will not happen. 
 -  `CodePen Demo which shows your issue:`
 -  Details:

**AngularJS Versions**: * 1.4.5
 -  `AngularJS Version:`1.4.5
 -  `AngularJS Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` any browser in iphone
 -  `Browser Version: *` Updated
 -  `OS: *` iphone
 -  `Stack Traces:`

----
Shortcut to create a [See Demo](https://codepen.io/tstinku/pen/dVoWjw).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by tstinku** [comment]
please resolve this issue if anybody knows

**Comment by tstinku** [comment]
please give solution on it guys.

**Comment by Splaktar** [comment]
[This CodePen](https://codepen.io/Splaktar/pen/KJBKYp?editors=1010#0) demonstrates the fix which is to add:
```js
.config(function($mdGestureProvider) {
  $mdGestureProvider.skipClickHijack();
});
```
This is documented [here](https://material.angularjs.org/1.1.12/api/service/$mdGestureProvider).
