### ISSUE TITLE
angular Material  md-date-filter

### ISSUE THREAD

**Issue by mwj-1992** [angular/material#10906]
**Actual Behavior**:
 -  I need md-date-filter function accepting multiple arguments, is it possible or not ?

 -  `$scope.filter = function (date,array){
return array.indexOf(date.getDay())!=-1
}`
`<md-datepicker md-filter-date=filter(array)></md-datepicker>`
**AngularJS Versions**: *
 -  `1.6`
 -  `1.4`

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
The function passed into `md-date-filter` can only accept one argument, the `Date` object that the `md-datepicker` code passes into it.

You don't explain what you are trying to do or what your use case is, so I can't help you with an alternative solution.
