### ISSUE TITLE
Theme examples

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1091]
Maybe I'm missing something, but the theme section should have some examples to make it really clear how the code works. The primary and accent colors are defined, but the warn isn't and it isn't clear if it should be. Also it is really confusing and it should be more like 1...2...3, done!

**Comment by epelc** [comment]
You can specify all the regular material colors 100-900 iirc and also accent colors using A100-A400. The docs mention this however the example is a bit lacking for creating your own color palette. It explains it all but it doesn't give a 100% copy paste example.

**Comment by ilanbiala** [comment]
Also too much info to really understand what is possible. It should show each possible example complete and separate from another concept.

**Comment by ThomasBurleson** [comment]
@marcysutton  - sounds like opportunity to improve our theming docs.

**Comment by ilanbiala** [comment]
@marcysutton @ThomasBurleson I would be happy to review anything you have in progress and give my 2c if you guys want?

**Comment by marcysutton** [comment]
Thanks @ilanbiala, we might do that!

**Comment by dmackerman** [comment]
I would second this. The library has a really nice/robust theme system, but the docs don't show it's full power. I could help chip in here also.

**Comment by milanart** [comment]
today i was finding solution to get dark backgroundColor in my whole theme, though by default the backgroundColor property gives light color. So, I jumped into the source code to fix the code directly. Though I couldnt find solution to my problem but found many things which might be part of theming but not documented properly. Detailed documentation will surely help.

**Comment by ThomasBurleson** [comment]
@milanart, @ilanbiala  - We are aware of the need to continually improve our documentation and to keep that documentation aligned with our rapidly maturing code base. The team would welcome [for review] any contributions you care to submit regarding documentation or examples.
