### ISSUE TITLE
select: label not reflecting change at runtime

### ISSUE THREAD

**Issue by VijaySankhat** [angular/material#10915]
**Actual Behavior**:
 -  `What is the issue? *`
      I have some app level constants using config in app.js which is accessible globally as label caption.
      when this constant change label for md-select does not change.
      
 -  `What is the expected behavior?`
       Label should reflect changes at runtime

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
    <md-input-container>
          <label>{{APP_LEVEL_CONSTANT}}</label> 
          <md-select ng-model="ctrl.userState">
            <md-option><em>None</em></md-option>
            <md-option ng-repeat="state in ctrl.states" ng-value="state.abbrev" ng-disabled="$index === 1">
              {{state.abbrev}}
            </md-option>
          </md-select>
        </md-input-container>

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:`  1.5.5

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DollarAkshay** [comment]
Can you post a code pen demo ?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template which requires a demo reproduction in CodePen, StackBlitz, or GitHub. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
