### ISSUE TITLE
switch: initial value not working with strings

### ISSUE THREAD

**Issue by danieleparazza** [angular/material#10914]
**Actual Behavior**:
 -  `What is the issue? *`
Setting ng-true-value and ng-false-value to string values (in example "0" and "1") will prevent md-switch to be activated even if model variable equals the true value ("1")
 -  `What is the expected behavior?`
If ng-model equals ng-true-value the toggle should be active

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
https://codepen.io/theBugger/pen/MEeWYa
 -  `Details:`
Activating the switch directly the ng-model is correctly set, but if you press the "toggle" button (which changes ng-model) the switch can only deactivate

**AngularJS Versions**: *
 -  `AngularJS Version:`
1.4.8
 -  `AngularJS Material Version:`
1.0.0

**Comment by Splaktar** [comment]
These values get interpreted as `expression`s as indicated in [the API docs](https://material.angularjs.org/latest/api/directive/mdSwitch). This means that you need to do the following to get them to be recognized as pure strings w/o any expression content ([demo](https://codepen.io/Splaktar/pen/eYzPJqZ?editors=1010)):
```html
<md-switch ng-model="active" ng-true-value="'1'" ng-false-value="'0'">
```
