### ISSUE TITLE
md-theme dosent work with md-colors

### ISSUE THREAD

**Issue by DollarAkshay** [angular/material#10918]
**Actual Behavior :**
 -  `What is the issue ?` using **md-theme** does not allow **md-colors** to access the theme palette
 -  `What is the expected behavior ?` **md-colors** should work even when using dynamic themeing

**CodePen :**
 -  `CodePen Demo :` https://codepen.io/DollarAkshay/pen/zEZRRj
 -  `Details :` This demo shows that **md-colors** dosent work when you use a dynamic theme along with **md-theme**. removing **`md-theme="appTheme"`** from the first line in the demo makes it work as intended

**AngularJS Versions :**
 -  `AngularJS Version :` 1.6.6
 -  `AngularJS Material Version :` 1.1.5

**Additional Information :**
 -  `Browser :` Chrome v61.0.3163.100
 -  `OS :` Windows 10

**Comment by DollarAkshay** [comment]
Some help ? Need it for a client web app

**Comment by prasanthkarukkuvel** [comment]
Here is the working Pen 

[https://codepen.io/prasanthkarukkuvel/pen/mBpeza](https://codepen.io/prasanthkarukkuvel/pen/mBpeza)

**Comment by DollarAkshay** [comment]
WoW i dint know using dashes in theme names wasnt allowed. Thank you so much
changing `my-theme-0` to `myTheme0` was the bug.

Is this intended behaviour by any chance

**Comment by prasanthkarukkuvel** [comment]
Yes, as per documentation
