### ISSUE TITLE
docs(changelog): add md-selected-text not accepting HTML anymore as a breaking change in 1.1.5

### ISSUE THREAD

**Issue by Ardeshir81** [angular/material#10912]
HI! Recently we wanted to migrate from angularjs material 1.1.1 to 1.1.4 (but finally did 1.1.5 as described below), we used the CHANGELOG.md as our migration tour guide : )
But it wasn't helpful in some situations:

- Our website is multi-directional, the first thing we encountered was in 1.1.4, all tooltips in RTL were attached to the right-most of the page instead of element. I'm not sure which version broke it, but I think there should be a breaking change log about this in your changelog file. That's why we decided to move to 1.1.5 instead of 1.1.4 (which later we found was a good thing : ))

- the main reason we decided to update our angularjs material was that `multiple` option of dialog which is added from 1.1.4 to documentation : https://material.angularjs.org/1.1.4/api/service/$mdDialog
But nowhere in changelog it was mentioned (btw, its great, thanks : ))

- There is a big breaking change which annoyed us a lot and took some time to debug and find where the problem is, all our `md-colors` were broke. like this: `md-colors="{background:'green-500'}"` resulted in an error like this : `'-green' couldn't be find in color pallete` (or something like that). That `-` (dash) was added at the beginning of every color we used and broke them all. That was caused in 1.1.2. by this I think :https://github.com/angular/material/commit/7090a1f
The solution was just to add a `md-theme="default"` to our `<body>` tag and to each of our dialogs one by one (even if dialogs were opened inside body), that just solved the problem, I assume it as a bug, because it took away default usage of `md-colors`, but if its not a bug, please add it to breaking changes of 1.1.2
something we found that might be helpful about this one were these few lines:

        `compile: function (tElem, tAttrs) {
        var shouldWatch = shouldColorsWatch(); return function (scope, element, attrs, ctrl) {`
          `var mdThemeController = ctrl[0];`

          `var lastColors = {};`
do you see that `ctrl[0]` ? it was `null` in 1.1.1, but it existed as an object from 1.1.2 

- also a minor thing : in your 1.1.5, there is a long text explaining something about $mdCompile, that breaks the nice flow of your beautiful bullet list changelog, and also its scary, first I thought maybe everything is changed in 1.1.5 : ). I think it would be nicer if a link is provided to somewhere else which explains it.

Thanks ! :) 
Keep up the good work 👍

**Comment by Ardeshir81** [comment]
+ One thing I found recently : 
mdSelectedText used to accept HTML in 1.1.1 but in 1.1.5 it does not accept HTML . 
all of our  usages of md-selected-text are rendered as `<span dir="auto">something</span>` instead of `something`. 

That is a breaking change.

the change is mentioned in documentation
https://material.angularjs.org/1.1.5/api/directive/mdSelect
https://material.angularjs.org/1.1.1/api/directive/mdSelect

Thanks ! :)

**Comment by Splaktar** [comment]
I will try to take a look at this soon. For future reference, it would be helpful to open the separate issues that you ran into as separate GitHub issues. This can avoid critical issues being lost in a list of other issues.

**Comment by Ardeshir81** [comment]
Yes! Of Course!
Sorry and thanks : )

**Comment by Splaktar** [comment]
- Tooltips and RTL, please test with 1.1.7 and if there is a bug still, please open a new issue with a CodePen repro.
- for `multiple` that is because it was first introduced in 1.1.2 where it has a change log entry (mentioning interims instead of dialogs specifically).
- I swear that I saw another open issue that mentioned the dash issue with md-colors, but I can't find it. Can you please try a search through the issues and if you can't find one open for that, can you please open a new issue with a CodePen repro?
- md-selected-text only accepting text and not HTML does seem like a breaking change. I'll update this issue's title to just focus on that one issue of the changelog.

**Comment by Splaktar** [comment]
Tagged this as a good issue for an external contributor, but removed the `good first issue` tag since the OP might confuse a first time contributor as it doesn't follow the issue template and includes multiple issues in a single report.

**Comment by Splaktar** [comment]
For colors, I found the issue and the PR (https://github.com/angular/material/pull/11078) which was just merged and will be in 1.1.8.

**Comment by Splaktar** [comment]
The breaking change for `md-selected-text` was a XSS security fix (https://github.com/angular/material/pull/10023) in 1.1.2. I'm working on a changelog update atm.

For `$mdDialog` and `multiple`, the docs were added in 1.1.2 via PR https://github.com/angular/material/pull/9950. The functionality was added in PR https://github.com/angular/material/pull/9053. Also as mentioned above, it has a changlog entry:
* **interimElement:** properly handle multiple interims. ([#9053](https://github.com/angular/material/issues/9053)) ([421fed4](https://github.com/angular/material/commit/421fed4)), closes [#8624](https://github.com/angular/material/issues/8624) [#8630](https://github.com/angular/material/issues/8630)
