### ISSUE TITLE
Md-tooltip keep open parent tooltip when child is hover

### ISSUE THREAD

**Issue by Oneril** [angular/material#10910]
When I have a md-tooltip in the parent both will be open when I hover the child. 

Have a look to the CodePen : 
https://codepen.io/anon/pen/VMemZW

**Comment by DollarAkshay** [comment]
Just move the tooltip inside of the element you want to show when hovered.

So instead of
```
<md-tooltip>Information about the item</md-tooltip>
<div flex class="text-ellipsis">
    Lorem ipsum dolo
</div>
```

**change it to** 

```
<div flex class="text-ellipsis">
    <md-tooltip>Information about the item</md-tooltip>
    Lorem ipsum dolo
</div>
```

This should solve the problem. Its not a bug but intended behavior

**Comment by Oneril** [comment]
It doesn't change anything
https://codepen.io/anon/pen/NagNYP

**Comment by DollarAkshay** [comment]
@Oneril Its owrking fine for the first one. You havent changed it for all of them.

**Comment by Oneril** [comment]
My bad ;)
