### ISSUE TITLE
two sidenav are overlap

### ISSUE THREAD

**Issue by userAngular** [angular/material#10913]
**Actual Behavior**:
I have to do a app with two sidenav, one principal sidenav an other that is a submenu, in google chrome the app works, ok, but in ie and mozilla the app doesnt work, and the sidenavs overlap

I work angular 1.6.4.
 
![image](https://user-images.githubusercontent.com/32135744/30651003-0a00f688-9dea-11e7-80ce-c9c8c82b20df.png)

I want that when click on the principal sidenav, the second sidenav is hide, or send it to back.
help!!!

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DollarAkshay** [comment]
Could you provide a minimalistic code pen demo ?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
