### ISSUE TITLE
sidenav should be full height

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1092]
The sidenav seems to only be as tall as the tallest container on the page. Is this a bug?

**Comment by epelc** [comment]
@ilanbiala no you have setup your layout incorrectly.

The flex layouts act like how `height:100%;` does when you are trying to make full height elements. Each parent requires you use flex or layout-fill correctly. Try removing some container elements or post a plunker.

**Comment by sclearion** [comment]
I had the same issue until I adjusted the nesting of some containers as suggested by @epelc :)

**Comment by ilanbiala** [comment]
@epelc thanks for the tip. so much isn't clear with the framework. :(

**Comment by epelc** [comment]
@ilanbiala no problem

As I side note I plan on fleshing out my example project([go-material](github.com/epelc/go-material)) into a todo or google keep style app so that new people can have a good example. Also remember that its still an early beta and so much has improved even over the last month that I've been using it.

**Comment by ThomasBurleson** [comment]
@marcysutton  - layout documentation irmpovement or note ?

**Comment by marcysutton** [comment]
@ThomasBurleson totally. I just ran into this creating a Starter App!

**Comment by epelc** [comment]
@marcysutton This might help you https://gist.github.com/epelc/6aa345f4496776569830

Thats what I use in my app minus some account based ng-ifs so it should work for the starter app as I've been busy and my todo app will have to happen another day.

**Comment by marcysutton** [comment]
Awesome, thanks so much for all you've done already @epelc. We love our open source community!

**Comment by epelc** [comment]
@marcysutton No problem I think everyone benefits from it. My app looks awesome now + I learned about aria which is pretty cool.

**Comment by marcysutton** [comment]
Sidenav documentation coming in https://github.com/angular/material/issues/1311.

**Comment by frodefi** [comment]
@epelc, this gist works only if 'layout="column"' is in the body element and not if it is in a div immediately after the body. Is this a behaviour as it is supposed to be, perhaps documented somewhere? Or is this just "accidentally" happening and may not work in a future version?

**Comment by epelc** [comment]
@frodefi I belive it's the correct behavoir. For flex to work you need to tell it which way to flex so `layout="column"` is required. After that it works like the css `height` attribute as I mentioned above.

**Comment by frodefi** [comment]
@epelc Ok. But does this fit in the "component" way of looking at things? Since it seems to be required that the "layout='column'" is body element to have an effect. See [this plnkr](http://plnkr.co/edit/8pAfYq6KlSuFxMRAj8k1?p=preview) where I have moved the "layout='column'" to a div immediately after the body and styled the body to be of 100% height, the sidenav is still not full height...

**Comment by epelc** [comment]
@frodefi You have to tell it how to lay it self out. The `layout` and `flex` attributes are just syntactic sugar on top of flexbox.

It's very hard if not impossible to force full height from an element without styling it's parents. Essentially the same reason full height layouts require `height:100%` on all parent elements.

**Comment by frodefi** [comment]
@epelc Hm, ok. But did I not style the parent (body) correctly (with `height:100%`) in the plnkr? I am a little confused...

**Comment by epelc** [comment]
@frodefi I was comparing how `flex` works to how `height:100%;` works.

To have a full height element with `height:100%;` it needs to be applied to every element up to your element ie body > somediv> yourElement all need the height set. For a full height flex to work you need it on every too otherwise there is nothing to fill up with your flex.

**Comment by frodefi** [comment]
@epelc Ok, Thanks for your input

**Comment by QuantumInformation** [comment]
My md-side-nav adds a md-mackdrop with too much height:

![image](https://cloud.githubusercontent.com/assets/216566/8459474/6a7c28c0-2015-11e5-809b-898dccd5f395.png)

**Comment by MemoLabra** [comment]
i have the same @QuantumInformation issue, the directive `<md-backdrop>` is adding more height than my main body nor his own `<div>`parent.
 `<md-backdrop>` =
![captura de pantalla 2015-07-03 a las 10 32 41](https://cloud.githubusercontent.com/assets/5521345/8500263/cda93c6a-2170-11e5-8184-ee13130e590c.png)
 `<div>` parent =
![captura de pantalla 2015-07-03 a las 10 32 57](https://cloud.githubusercontent.com/assets/5521345/8500242/a86d0fee-2170-11e5-8b60-b8518750aadf.png)
My layout structure is:
```
body column
 div flex column
  div flex column 
   md-toolbar
   div flex row
    md-sidenav
    md-content
   /div
  /div 
 /div
/body
```

**Comment by J-Zeitler** [comment]
@MemoLabra + @QuantumInformation 

My quickfix for this is to add `position: relative;` to my `div flex row`.

**Comment by digita1-Anal0g** [comment]
Is there a way to get the sideNav to be 100% height  of it's parent when it's initially hidden and then toggled to display through through an event handler?  See this [codepen] (http://codepen.io/anon/pen/KdMWqm) to see the issue in action.  

I tried a combination of setting the height of all parent elements to be 100%, layout="column", layout-fill, flex, etc. as per @epelc's guidance and wasn't able to get it to work.
