### ISSUE TITLE
datepicker: How to set year selection?

### ISSUE THREAD

**Issue by adwaer** [angular/material#10920]
How to set year selection? Prev-Next is not pretty good for bithday selection
https://plnkr.co/edit/?p=preview

**Comment by IMM0rtalis** [comment]
Hi @adwaer ,
Could you pls clearify your question and ask it maybe on stackoverflow or here: https://groups.google.com/forum/#!forum/ngmaterial  ?

This place here should be just for bugs etc.

All the best,
Florian
