### ISSUE TITLE
Infinite digest only on md-autocomplete

### ISSUE THREAD

**Issue by Igor16** [angular/material#10921]
I'm making a form using md-autocomplete on AngularJS, it worked the first times, the day after that, I reopened the application and everytime I write a letter it return a lot of errors regarding loops like this:
`ionic.bundle.js:13443 Uncaught Error: [$rootScope:infdig] 10 $digest() iterations reached. Aborting!
Watchers fired in the last 5 iterations: []
http://errors.angularjs.org/1.5.3/$rootScope/infdig?p0=10&p1=%5B%5D
    at ionic.bundle.js:13443
    at Scope.$digest (ionic.bundle.js:30282)
    at Scope.$apply (ionic.bundle.js:30508)
    at ionic.bundle.js:32337
    at completeOutstandingRequest (ionic.bundle.js:19199)
    at ionic.bundle.js:19475`

This is the md-autcomplete that is loaded in a form in a md-dialog (I passed the var message in the dialog on locals):
`<md-autocomplete md-no-cache="true" md-selected-item="message.art.ar_mar" md-items="mar in message.art_mar | filter: searchText" md-search-text="searchText" md-item-text="mar.am_desc" md-floating-label="Mar" ng-disabled="message.disabledform || !message.art_mar"><span>{{mar.am_desc}}</span> </md-autocomplete>`
There isn't code regarding this in JS, so I can't understand the error, I tried a lot of things but nothing, it worked until the day before, Chrome was already up to date to last version, the error is also on Opera, obviously. I tried to delete the "\|filter" part, but nothing, the array of objects is correct. I'm sure the error is in search, because if there is an element selected it works and it read the list.

If I use this code the filter works, the error is only on md-autocomplete:
`<input ng-model="pr"> <div ng-repeat="mar in message.art_mar | filter: pr">{{mar.am_desc}}</div>`

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. Please provide a CodePen demo or GitHub repo where this can be debugged and investigated.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
