### ISSUE TITLE
sidenav: closes and then open up again automatically once it is closed

### ISSUE THREAD

**Issue by biswa1shaw** [angular/material#10934]
**Actual Behavior**:
 -  `What is the issue? *`
On closing md-sidebar, it opens automatically once again, but this time as an overlay 
 -  `What is the expected behavior?`
The sidebar should remain closed and should toggle again only when the toggle event is fired.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://plnkr.co/edit/Baaraj2arrYOlpOEvWsw?p=preview
 -  `Details:` Try to open the preview in a separate window and maximize it before load. Once page load is complete. click the menu button in the top-left corner. The sidebar will close and then slide-in again automatically, this time as an overlay. Will continue to happen on each click of the menu button, unless you click outside of the sidebar (in overlay mode). After that the behaviour is normal.

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 61.0.3163.100 (Official Build) (64-bit)
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This is due to defective application behavior (having `!hide()` in the `md-is-locked-open` expression).

Here's [an example](https://plnkr.co/edit/R4O3qgpwjdFFMoQ3?preview) where this doesn't happen. It also hides the button to toggle the sidenav in `gt-xs` mode since you can't toggle it when it's locked open.
