### ISSUE TITLE
Can't use either *show* or *hide* words as bindings

### ISSUE THREAD

**Issue by samithaf** [angular/material#10935]
**Actual Behavior**:
 -  `What is the issue? *` Can't use either *show* or *hide* words as bindings if i use material 1.1.4 + and throws a runtime error in Angular AST compiler
 -  `What is the expected behavior?` should be able to use any word as bindings and valid angular expressions

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/samithaf/pen/eGjOWg
 -  `Details:`See the simple component my-alert. This component has a binding *show* and passing a valid angular expression. During the compilation time angular throws an error. However if I use any other word like for an example, *display* as the binding application works fine. Also if I downgrade Material version to 1.1.3 application works fine as well. I am pleased to use the newer version since it has some bug fixes for date picker. But this problem stops me from upgrading.

**AngularJS Versions**: *
 -  `AngularJS Version:`1.5.5
 -  `AngularJS Material Version:`1.1.5

**Additional Information**:
 -  `Browser Type: *` All browsers
 -  `Browser Version: *`All versions
 -  `OS: *`
 -  `Stack Traces:` 
```js
console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js:1 
Error: [$parse:syntax] 
Syntax Error: Token '&&' not a primary expression at column 17 of the expression 
[$ctrl.pineapple-&&-$ctrl.apple] starting at [&&-$ctrl.apple].
```

I wonder what are the other keywords *Material* restricts since this issue kills the application completely. ( Probably Material is reregistering directives in the global scope without any namespaces which is the root cause to the problem )

**Comment by AkhilNaidu09** [comment]
I did small changes to your codepen its working fine here : [codepen](https://codepen.io/anon/pen/RLqEza)
I hope that this is what your issue, if not let me know i will try to fix the issue once again.

**Comment by samithaf** [comment]
@AkhilNaidu09 Issue is that since Angular Material has introduced global level directive without any namespaces. So when I want to pass a valid angular expression, Angular material show directive comes to the picture and breaks the application. E.g. `$ctrl.payeeList.length === 0`

**Comment by Splaktar** [comment]
Verified that this is still an issue with `1.1.22` in [updated CodePen](https://codepen.io/Splaktar/pen/LYGbpvP?editors=1010).

This was introduced in `1.1.4` based on [this CodePen](https://codepen.io/Splaktar/pen/JjGbYVQ?editors=1010) even though the OP's CodePen is based on `1.1.5`.

Here's [a CodePen](https://codepen.io/Splaktar/pen/dyGOYBo?editors=1010) with `1.1.3` where this exception does not occur.

**Comment by Splaktar** [comment]
As documented in the AngularJS [$compile:scope docs](https://docs.angularjs.org/api/ng/service/$compile#-scope-), the `=` binding is used to

> set up a bidirectional binding between a local scope property and an expression passed

The reason that it is complaining about `$ctrl.pineapple-&&-$ctrl.apple` is because it can't write to that model as it doesn't resolve to a single primary field.

Using the `@` binding, can [avoid this error](https://codepen.io/Splaktar/pen/eYJBJdX?editors=1010)
```js
.component('myAlert', {
    bindings: {
    show: '@',
  },
  controller: function() {}
})
```
because it is used to

> bind a local scope property to the value of DOM attribute. The result is always a string since DOM attributes are strings.

It does not try to do two-way binding and check if it can write the the model in the `expression`.

Now why did the way that these directives are evaluated change in AngularJS Material `1.1.4` in such a way that it now throws an exception?

**Comment by Splaktar** [comment]
OK, this is caused by PR https://github.com/angular/material/pull/10462 which was trying to deal with [this change](https://github.com/angular/angular.js/commit/97bbf86) to AngularJS `1.6.0`.
