### ISSUE TITLE
md-table progress

### ISSUE THREAD

**Issue by nickvorie** [angular/material#10936]
According to https://github.com/angular/material/issues/796 md-table was suposed to be implemented in 0.10, but it's currently v1.2, and almost 3 years since the issue was opened. What's with the delay?

**Comment by Splaktar** [comment]
As mentioned in https://github.com/angular/material/issues/796#issuecomment-350538504, there is a `mat-table` in Angular Material (material2). We don't plan to add one to AngularJS Material.
