### ISSUE TITLE
Flex percentage does not work in Safari

### ISSUE THREAD

**Issue by hoanthien92** [angular/material#10931]
I am having the issue when using flex percentage and things are rendered vertically in Safari. So I specify flex="25" but it renders "flex: 1 1 100%" instead of "flex: 1 1 25%". 
Before Angular Material 1.1.1, everything looks fine but after upgrading to latest angular material, we have this issue.
You can see 2 different flex on Angular Material site as well 
https://material.angularjs.org/latest/
This version renders flex correctly.
https://material.angularjs.org/1.1.1/

Is this a known issue and will be fixed in the next release?
Please let me know,
Thank you.

**Comment by Splaktar** [comment]
I am seeing flex percentages working properly with the following versions:
- https://material.angularjs.org/1.1.10/layout/children
- https://material.angularjs.org/1.1.1/layout/children
- https://material.angularjs.org/1.1.2/layout/children
- https://material.angularjs.org/1.1.0/layout/children

If this is still a problem, please file a new issue that uses the issue template and specifies a CodePen demo and reproduction steps.
