### ISSUE TITLE
Sidenav md-highlight

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1093]
The demo site has a sidenav component, but it seems that you guys custom built the highlighting method check for the site. It would be nice if the sidenav service had like an index or something and md-highlight was either really easy to use, or it was just built in when using an `md-list` in an `md-sidenav`.

**Comment by epelc** [comment]
@ilanbiala They use the `md-ink-ripple` and `md-highlight` directives which are currently meant for internal use only and not documented besides what you can find in the docs source.

I used `md-ink-ripple` my self to create a sidenav that is similar to the one on the docs for my app.

**Comment by ilanbiala** [comment]
@ThomasBurleson any plans to bring `md-highlight` or something like `ui-sref-active` to angular/material?

**Comment by EladBezalel** [comment]
@ilanbiala you can use ```ui-sref-active="your-class"```, its working..

**Comment by ilanbiala** [comment]
@EladBezalel right but doesn't that conflict with the ripple?

**Comment by EladBezalel** [comment]
@ilanbiala nop. works great :dancer:
