### ISSUE TITLE
input floating label not to rise too high on focus

### ISSUE THREAD

**Issue by Bartaf83** [angular/material#10932]
i would like to know if there a way to set a given value to the floating label less than its standard value not to rise too high on focus. i don't know whether it's a css top value or other.
i'm using it as in this code chunk:
```
<div class="panel-field" layout="row" ng-if="property.descriptor.type == 'text'" ng-click="editPanel.focusThis($event)">
                    <md-icon style="font-size: 20px;" flex="10">font_download</md-icon>
                    <md-input-container style="width: 100%;">
                        <label>{{ property.name }}</label>
                        <input style="width: 100%;" ng-model="editPanel.rowData.values[property.id].value" type="text" ng-blur="editPanel.updateChange(property, opt, true)" ng-change="editPanel.updateChange(property, opt, false)">
                    </md-input-container>
</div>
```
Best regards.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
