### ISSUE TITLE
datepicker: can't open in dialog

### ISSUE THREAD

**Issue by Chris59160** [angular/material#10940]
**Actual Behavior**:
 -  `What is the issue? *`
The md-datepicker doesn't show and change the background of the main page if inside a modal
 -  `What is the expected behavior?`
The md-datepicker correctly shows up and doesn't screw the background of the main page

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.1
 -  `AngularJS Material Version:` 1.0.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`61.0.3163.100
 -  `OS: *` macOS Sierra
 -  `Stack Traces:`

I have added screenshots. The "valid_behaviour 
![valid_behaviour](https://user-images.githubusercontent.com/5450122/31587089-1316a612-b1d3-11e7-8f23-29b731115adb.png)
shows that it works fine if I am at the top of the main page.
The "invalid_before_opening_md_datepicker" shows the modal and main page before trying to open
The "invalid_after_opening_md_datepicker
![invalid_after_opening_md_datepicker](https://user-images.githubusercontent.com/5450122/31587090-216731c8-b1d3-11e7-8e0f-c8c353d1d6a0.png)
![invalid_before_opening_md_datepicker](https://user-images.githubusercontent.com/5450122/31587091-217bb51c-b1d3-11e7-858a-0e22fdddb994.png)

" shows the modal and main page after having clicked the datepicker...showing the problem

**Comment by Splaktar** [comment]
This appears to be fixed at some point before `1.1.10` as I am not able to reproduce this issue anymore. There was no demo provided, so I can't verify the exact use case, but it seems to be resolved.
