### ISSUE TITLE
missing script: watch

### ISSUE THREAD

**Issue by falco442** [angular/material#10949]
I tried to run the command `npm run watch` (after installing packages with `npm install`) in the `/docs` folder (to have angular material documentation locally), but it gave me this error

```
npm ERR! Linux 4.2.0-040200-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "watch"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10

npm ERR! missing script: watch
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/my-home/www/angular-material/npm-debug.log
```

**Comment by codymikol** [comment]
npm run docs:watch

**Comment by Splaktar** [comment]
@codymikol is correct. @falco442 can you point to the spot in the docs that told you to run that command? We'll get it fixed ASAP.

**Comment by Splaktar** [comment]
Oh this was fixed by https://github.com/angular/material/pull/10965
