### ISSUE TITLE
mat-error *ngIf, custom validator, and FormGroup do not work together 

### ISSUE THREAD

**Issue by codewiseio** [angular/material#10956]
**Actual Behavior**:
 -  When using a custom validator directive with FormGroup and mat-error, errors are not displayed and behavior is unpredictable. Moving between fields may display one or more errors, some are duplicated. Other fields not in the FormGroup are also affected.
 -  Expected behavior: Errors should display below the field upon validation

**CodePen** (or steps to reproduce the issue): 
https://plnkr.co/edit/baoE7esAoqJXLPoBcLEX?p=preview

**AngularJS Versions**: *
 -  `AngularJS Version: 4.4.4
 -  `AngularJS Material Version: 2.0.0-beta12

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: Version 59.0.3071.104 (Official Build) (64-bit)`
 -  `OS: Ubuntu`
![screenshot from 2017-10-27 07-41-17](https://user-images.githubusercontent.com/22958565/32104484-3efe2ece-baea-11e7-8340-a4fd19edd140.png)

**Comment by codewiseio** [comment]
Here is a plunkr showing that this works as expected if not using material:
http://plnkr.co/edit/ZI1mTOFJPkUc7PpjZspC?p=preview

**Comment by amitvchaudhary** [comment]
You are right. It is not working with material. Need to have simple div and apply relevant error class.

**Comment by Chan4077** [comment]
Please report this issue [here](https://github.com/angular/material2/issues/new). This repo is for AngularJS Material.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by mrtabaa** [comment]
Hey guys. 
mat-error still doesn't show with ValidationErrors in **formGroup** level. 
Does anyone has any solution?
