### ISSUE TITLE
what happened to the paper drop-down menus?

### ISSUE THREAD

**Issue by jeffthompson1971** [angular/material#1095]
I recall seeing drop-down paper material menus.  I don't see them anymore.   Did I maybe have a stroke or are they gone now?

**Comment by marcysutton** [comment]
Paper is a different library, maybe you're thinking of this? https://github.com/Polymer/paper-dropdown

**Comment by ilanbiala** [comment]
@jeffthompson1971 I think you are actually referring to the menu component https://github.com/angular/material/issues/78.
