### ISSUE TITLE
Datatable paginator's next page and previous page tooltips breaks when binding to a dynamic table length

### ISSUE THREAD

**Issue by Deon588** [angular/material#10960]
**Actual Behavior**:
 -  `What is the issue? *`
When I bind the paginator to a dynamic length determined by the dataSource when filtering the displayed results based on a search term the tooltips which normally appear when   hovering the mouse over the next/previous page arrows doesn't show up.  Instead the next page/previous page tooltips gets displayed when clicking on the next page oor previous page arrows and the only way to get rid of the tooltip afterwards is by clicking somewhere else on the page.
 -  `What is the expected behavior?`
The tooltips should appear when the mouse is hovered above the next/previous page and then disapear when the mouse moves out of that region

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

my code:

my html template:

my html:

<br /><br /><br />
<div class="noOverflow" fxLayout fxLayoutAlign="start start" fxLayoutWrap>
	<div fxFlex="100%">
		<div fxLayout fxLayoutAlign="start start">
			<div fxFlex="50%">	
				<h1>Customer Master</h1>
			</div>
			<div fxFlex="70%" fxFlexOffset="50%">
				<button color="primary" mat-raised-button><mat-icon class="fa fa-plus"></mat-icon> Add New</button>
				<button mat-raised-button><mat-icon class="fa fa-refresh"></mat-icon> Reload</button>
				<button mat-raised-button><mat-icon class="fa fa-download"></mat-icon> Output</button>
				<button mat-raised-button><mat-icon class="fa fa-print"></mat-icon> Print</button>
				<button mat-raised-button><mat-icon class="fa fa-List"></mat-icon> List</button>
			</div>
		</div>
		<div fxLayout fxLayoutAlign="start start">
		<div fxFlex="100%" fxFlexOffset="80%">
			<mat-form-field floatPlaceholder="never">
				<input matInput #filter placeholder="filter users">
			</mat-form-field>
		</div>
	</div>
	
	<div fxLayout>
		<div fxFlex="100%">
		<div class="mat-elevation-z8">
			  <mat-table #table [dataSource]="dataSource">

    

    
    <ng-container matColumnDef="userId">
      <mat-header-cell *matHeaderCellDef> ID </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.id}} </mat-cell>
    </ng-container>

    
    <ng-container matColumnDef="progress">
      <mat-header-cell *matHeaderCellDef> Progress </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.progress}}% </mat-cell>
    </ng-container>

    
    <ng-container matColumnDef="userName">
      <mat-header-cell *matHeaderCellDef> Name </mat-header-cell>
      <mat-cell *matCellDef="let row"> {{row.name}} </mat-cell>
    </ng-container>

    
    <ng-container matColumnDef="color">
      <mat-header-cell *matHeaderCellDef> Color </mat-header-cell>
      <mat-cell *matCellDef="let row" [style.color]="row.color"> {{row.color}} </mat-cell>
    </ng-container>

    <mat-header-row *matHeaderRowDef="displayedColumns"></mat-header-row>
    <mat-row *matRowDef="let row; columns: displayedColumns;"></mat-row>
	

	
  </mat-table>
  	<mat-paginator #paginator [length]="dataSource.dataLength" [pageIndex]="0" [pageSize]="10" [pageSizeOptions]="[5, 10, 20, 40, 50]"></mat-paginator>
  </div>
		</div>
	</div>
	</div>	
</div>

my component code:

import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import {DataSource} from '@angular/cdk/collections';
import {BehaviorSubject} from 'rxjs/BehaviorSubject';
import {Observable} from 'rxjs/Observable';
import 'rxjs/add/operator/startWith';
import 'rxjs/add/observable/merge';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/observable/fromEvent';
import { MatPaginator } from '@angular/material';

@Component({
  selector: 'app-customer-master',
  templateUrl: './customer-master.component.html',
  styleUrls: ['./customer-master.component.css']
})
export class CustomerMasterComponent implements OnInit {
	
	  @ViewChild('filter') filter: ElementRef;
	   @ViewChild(MatPaginator) paginator: MatPaginator;
	  displayedColumns = ['userId', 'userName', 'progress', 'color'];	  
	    exampleDatabase = new ExampleDatabase();
		  dataSource: ExampleDataSource | null;
		  dataLength: number;
		  
		
  constructor() { }

  ngOnInit() {
	      this.dataSource = new ExampleDataSource(this.exampleDatabase, this.paginator);		  
		  Observable.fromEvent(this.filter.nativeElement, 'keyup')
        .debounceTime(150)
        .distinctUntilChanged()
        .subscribe(() => {
          if (!this.dataSource) { 
			return; 
		  }
          this.dataSource.filter = this.filter.nativeElement.value;
        });
  }
  
}
  
  const COLORS = ['maroon', 'red', 'orange', 'yellow', 'olive', 'green', 'purple', 'fuchsia', 'lime', 'teal', 'aqua', 'blue', 'navy', 'black', 'gray'];
  const NAMES = ['Maia', 'Asher', 'Olivia', 'Atticus', 'Amelia', 'Jack', 'Charlotte', 'Theodore', 'Isla', 'Oliver', 'Isabella', 'Jasper', 'Cora', 'Levi', 'Violet', 'Arthur', 'Mia', 'Thomas', 'Elizabeth'];
  
  export interface UserData {
  id: string;
  name: string;
  progress: string;
  color: string;
}

export class ExampleDatabase {
  /** Stream that emits whenever the data has been modified. */
  dataChange: BehaviorSubject<UserData[]> = new BehaviorSubject<UserData[]>([]);
  get data(): UserData[] { 
	return this.dataChange.value;
}

  constructor() {
    // Fill up the database with 100 users.
		for (let i = 0; i < 100; i++) { 
			this.addUser();
		}
  }

  /** Adds a new user to the database. */
  addUser() {
    const copiedData = this.data.slice();
    copiedData.push(this.createNewUser());
    this.dataChange.next(copiedData);
  }

  /** Builds and returns a new User. */
  private createNewUser() {
    const name =
        NAMES[Math.round(Math.random() * (NAMES.length - 1))] + ' ' +
        NAMES[Math.round(Math.random() * (NAMES.length - 1))].charAt(0) + '.';

    return {
      id: (this.data.length + 1).toString(),
      name: name,
      progress: Math.round(Math.random() * 100).toString(),
      color: COLORS[Math.round(Math.random() * (COLORS.length - 1))]
    };
  }
}

/**
 * Data source to provide what data should be rendered in the table. Note that the data source
 * can retrieve its data in any way. In this case, the data source is provided a reference
 * to a common data base, ExampleDatabase. It is not the data source's responsibility to manage
 * the underlying data. Instead, it only needs to take the data and send the table exactly what
 * should be rendered.
 */
export class ExampleDataSource extends DataSource<any> {
  _filterChange = new BehaviorSubject('');
   dataLength: number = 100;   
  get filter(): string   { 
	return this._filterChange.value; 
}

  set filter(filter: string)  { 
	this._filterChange.next(filter); 
}

  constructor(private _exampleDatabase: ExampleDatabase, private _paginator: MatPaginator) {
    super();
  }

  /** Connect function called by the table to retrieve one stream containing the data to render. */
  connect(): Observable<UserData[]> {
    const displayDataChanges = [
      this._exampleDatabase.dataChange,
      this._filterChange,
	  this._paginator.page,
    ];

    return Observable.merge(...displayDataChanges).map(() => {
	  const data = this._exampleDatabase.data.slice().filter((item: UserData) => {
        let searchStr = (item.name + item.color).toLowerCase();		
        return searchStr.indexOf(this.filter.toLowerCase()) != -1;
	});
	//console.log(data.length);
	this.dataLength = data.length;
	const startIndex = this._paginator.pageIndex * this._paginator.pageSize;
     return data.splice(startIndex, this._paginator.pageSize)
      
    });
  }

  disconnect() {}
}

**AngularJS Versions**: *
 -  `AngularJS Version:`
4.x
 -  `AngularJS Material Version:`
latest
**Additional Information**:
 -  `Browser Type: *`
Google Chrome 

-  `Browser Version: *`
61.0.3163.100
 -  `OS: *`
Windows 10 x64
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by AkhilNaidu09** [comment]
post this issue in [Material2 repo](https://github.com/angular/material2/issues)

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
