### ISSUE TITLE
Angular Material is rendered incorrectly md-backdrop on a specific monitor

### ISSUE THREAD

**Issue by phongca22** [angular/material#10966]
Please review this image https://i.stack.imgur.com/buFDJ.jpg
I found an issue about md-backdrop when opening the Sidenav.
```
md-backdrop.md-opaque.md-customTheme1-theme {
    background-color: rgba(33,33,33,1.0);
}
```
When I changed to this, it works well.
```
md-backdrop.md-opaque.md-customTheme1-theme {
    background-color: rgba(33,33,33,0.99);
}
```
So, what is happening in there?

**Monitor**
 -  HP EliteDisplay E222

**AngularJS Versions**: *
 -  `AngularJS Version: 1.5`
 -  `AngularJS Material Version: 1.1.4`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: v62`
 -  `OS: Window`

**Comment by Splaktar** [comment]
Please contact HP to troubleshoot your specific monitor model.
