### ISSUE TITLE
select: options are always read as "checked" with JAWS

### ISSUE THREAD

**Issue by jelbourn** [angular/material#10969]

**Comment by benjiallen** [comment]
Adding more detail.

* Component with issue
    - `<md-select>`
* Overview of the Issue
    - Select options are always read as "checked" with JAWS
* AngularJS Material Version
    - 1.1.5
* Browsers and Operating System
    - I can reproduce on Windows 7, IE11, JAWS 17.0.2619
* Reproduce the Error
    - Visit https://material.angularjs.org/latest/demo/select and interact with the select menu with JAWS
* Related Issues
    - #10748

**Comment by Splaktar** [comment]
Related to https://github.com/angular/material/issues/10748.

**Comment by Splaktar** [comment]
Closing as a duplicate of https://github.com/angular/material/issues/10748.
