### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1097]
I'm really happy with how angular-material progresses, but I think it would be nice to get a couple more rc's out before a new release. Doing this allows people who are stuck on something that has been fixed to fix their issues in more manageable chunks, rather than all at once when a pretty stable release comes out. Also, it attracts more people to see that the framework is really active and pushes releases really quickly. Something like every ±10 days would be awesome.

This is just a thought, though. If the community likes the idea and you guys have the manpower to do it, then I think it's worth considering.

**Comment by epelc** [comment]
+1 the `0.6.0` releases were timed nicely.

**Comment by EladBezalel** [comment]
:+1:

**Comment by ThomasBurleson** [comment]
@EladBezalel, @epelc, @ilanbiala - 
I agree that we have a significant amount of Issues still remaining for 0.7.0.  I will escalate the request for `additional rc(s)` to the team.  Thx for the nice feedback.
> Our develop progress has slowed **only** because of the recent holidays and will resume *full-force* on January 5.
