### ISSUE TITLE
md-autocomplete should support input type number

### ISSUE THREAD

**Issue by hashina** [angular/material#10974]
**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ninad-d** [comment]
@hashina please provide details. The things above marked as star (*) are compulsory. We cannot help unless and until you provide the necessary details.

**Comment by Splaktar** [comment]
Feature requests must be accompanied by details like a description of the use case, indication of why it cannot be accomplished with existing components, etc. The required fields in the template are required.
