### ISSUE TITLE
Multiple mat-vertical-stepper inside Multiple mat-tab making all mat-step open by default

### ISSUE THREAD

**Issue by sathyakps** [angular/material#10979]
**Actual Behavior**:
 -  `What is the issue? *`
         I have a three mat-tab under one mat-tab-group. inside every mat-tab i am having mat-vertical stepper. First mat-tab and first stepper is working fine. But when it comes to second one all the steps are opening by default. My code will look like.

<mat-tab-group>

       <mat-tab>
             <mat-vertical-stepper>
                        <mat-step></mat-step> //open by default
                       <mat-step></mat-step> //closed
                       <mat-step></mat-step> //closed
             </mat-vertical-stepper>
        </mat-tab>

<mat-tab>
             <mat-vertical-stepper>
                        <mat-step></mat-step> //open by default
                       <mat-step></mat-step> // open by default
                       <mat-step></mat-step> //open by default
             </mat-vertical-stepper>
        </mat-tab>
</mat-tab-group>

First tab is working as per the document where as second tab is not as expected as it is opening all the steps.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.
![1](https://user-images.githubusercontent.com/29043417/32604646-5bb4ee06-c574-11e7-9f4d-ae432bc81e50.PNG)
![2](https://user-images.githubusercontent.com/29043417/32604647-5bec7696-c574-11e7-9653-b8c425be2a33.PNG)

**Comment by Chan4077** [comment]
Please report this issue [here](https://github.com/angular/material2/issues/new). This repo is for AngularJS Material.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
