### ISSUE TITLE
md-tabs inside of ng2-dialog are not displaying md-ink-bar for the selected tab

### ISSUE THREAD

**Issue by vikasj123** [angular/material#10989]
![untitled](https://user-images.githubusercontent.com/12233811/32874250-0982c688-cab7-11e7-98f7-46b19e71aa77.png)

**Comment by eknowles** [comment]
Could you provide a codepen of this? Unsure what you mean by ng2-dialog?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
