### ISSUE TITLE
Issue with BrowserAnimationsModule

### ISSUE THREAD

**Issue by uttahb** [angular/material#10985]
Hi all,

This error is coming up on compilation after importing BrowserAnimationsModule, compilation is failing due to this.

        ERROR in node_modules/@angular/platform-browser/animations/src/module.d.ts(4,1): error TS1128: Declaration or statement expected.

I am using 

Angular CLI: 1.5.0
Node: 9.0.0
OS: linux x64
Angular: 5.0.1

Please light some ideas into this.

Thanks,
Uttahb

**Comment by Chan4077** [comment]
Please report this issue [here](https://github.com/angular/material2/issues/new). This repo is for AngularJS Material.

**Comment by uttahb** [comment]
Thank you

**Comment by Chan4077** [comment]
@uttahb Please also close this issue.
