### ISSUE TITLE
md-step cut off ripple effect

### ISSUE THREAD

**Issue by milanstamenkovic** [angular/material#10983]
**Actual Behavior**:
 -  `What is the issue? ` 
     Md-step cut off ripple effect of checkbox close to edges
 -  `What is the expected behavior?`
     Visible ripple effect in all positions
![image](https://user-images.githubusercontent.com/9901106/32773722-5e1729c0-c92a-11e7-8711-994db023de58.png)

**Angular Versions**: 
 "@angular/animations": "^4.4.4",
    "@angular/cdk": "^2.0.0-beta.11",
    "@angular/common": "^4.4.4",
    "@angular/compiler": "^4.4.4",
    "@angular/core": "^4.4.4"
    "@angular/material": "^2.0.0-beta.10",

**Additional Information**:
 -  `Browser Type: Google Chrome `
 -  `Browser Version: 61.0.3163.100`
 -  `OS: Ubuntu 16.04`

**Comment by Chan4077** [comment]
Please report this issue [here](https://github.com/angular/material2/issues/new). This repo is for AngularJS Material.
