### ISSUE TITLE
md-button(fab): Raises up for toasts on the opitsite side even if the screen is big

### ISSUE THREAD

**Issue by epelc** [angular/material#1098]
If you have an `md-button` with `md-fab` and `md-fab-bottom-left` or right and you show a toast on the opposite side it will move up to make room for the toast even when there is enough space that it doesn't have too.

![bad toast](https://cloud.githubusercontent.com/assets/5204642/5604027/2bd474a0-9371-11e4-928c-113d6e45bdfd.png)

**Comment by EladBezalel** [comment]
Same [here](https://material.angularjs.org/#/demo/material.components.toast), just select left and top and click a button..

**Comment by epelc** [comment]
@EladBezalel thanks for pointing out you can see it in the docs should help with testing it.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by umutesen** [comment]
I would really like to know to solution to this..

**Comment by EladBezalel** [comment]
@umutesen if you have an issue, please provide a codepen so we could investigate.
