### ISSUE TITLE
$mdToast: Not showing when called on page load(with ui-view on <body>)

### ISSUE THREAD

**Issue by epelc** [angular/material#1099]
If you try to show a toast right after page load it is only halfway working. The `md-toast-open-bottom` is added to the body and removed correctly however the toast is not added. Also this only happens if you have `ui-view` on your `body` element instead of a child div. 

A temporary fix is to move your `ui-view` down to a child element but it makes your html a bit more dirty and I was wondering if it'd be possible to fix this. Also would this be better off reported to `ui-router` instead?

**Comment by ilanbiala** [comment]
Having `ui-view` on the body is nice, can we get a different fix?

**Comment by epelc** [comment]
I still don't know if it should be reported to ui-router or if we can delay the toast until the first template loads. Or maybe just get the toast to persist on state changes.

I haven't tested but this might also apply to dialogs if you show them right onow page load.

**Comment by ThomasBurleson** [comment]
@rschmukler - Thoughts ?

**Comment by rschmukler** [comment]
The issue here is that the toast is added as a child to the `body` node, while `ui-view` swaps that out with the appropriate template when a route matches. The solution is to have a child div in the body that has the `ui-view`. I'm open to hearing suggestions on how we could improve this, but it seems like a problem at the most fundamental level (router swapping out the body's content with the appropriate template).

Closing for now, but feel free to re-open with discussion.

**Comment by epelc** [comment]
@rschmukler Can we add a line about this to the toast docs? It seems common for people to put a `ui-view` directly on their body.

**Comment by ThomasBurleson** [comment]
@epelc - It seems very unusual to use  `<body ui-view>`. Most often you will see usages as suggested by @rschmukler. See [AngularJS-Zza](https://github.com/ThomasBurleson/angularjs-Zza-BMEAN/blob/master/client/index.html#L28-34) as an example.  

> We cannot account for any other directive that clear child DOM content... especially on the `<body>`

**Comment by epelc** [comment]
@ThomasBurleson Maybe my want for `<body ui-view>` is a little unusual but I do have good reason.

I have it this way so I can have a different template for app routes then the one I use for my landing/aboutus/legal/etc pages without having to prefix my app routes. However creating a child div to put my `ui-view` on is fine.

**Comment by kai23** [comment]
I have the same issue here. ui-view in body.
