### ISSUE TITLE
Major Menu

### ISSUE THREAD

**Issue by KevinQuispe** [angular/material#10993]
**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by eknowles** [comment]
wat

**Comment by eknowles** [comment]
please close this or add some context :)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
