### ISSUE TITLE
md-slider not working property when zoom apply

### ISSUE THREAD

**Issue by jazztong** [angular/material#10998]
**Actual Behavior**:
 -  `What is the issue? *`
when the zoom apply to slider or parent of slider, it will not slider properly
 -  `What is the expected behavior?`
it should slider with correct value rather then a sudden change of value when you try to move the slider
**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
https://plnkr.co/edit/s8qsKgazCJ1umAUk9hhY?p=preview
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
angular 5.0.0-rc0
 -  `AngularJS Material Version:`
angular material 5.0.0-rc0
**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This repository is for AngularJS Material and not for Angular Material (for use with Angular v5). Please search for an issue at https://github.com/angular/material2/issues and submit a new issue if you cannot find a matching issue.
