### ISSUE TITLE
docs(datepicker): does not follow Material Design guidelines for messages

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11007]
**Actual Behavior**:
 -  `What is the issue? *`
The tone in the [date picker validations](https://material.angularjs.org/latest/demo/datepicker) example does not fit within the Material Design guidelines.
 -  `What is the expected behavior?`
It should follow the [Writing Tone Guidelines](https://material.io/guidelines/style/writing.html#writing-tone) as people are likely to reproduce this example in their apps.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://codepen.io/Splaktar/pen/zPVwEM
 -  `Details:` Messages like "Date is too early!" don't follow the Material Design guidelines

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.6.6
 -  `AngularJS Material Version:` 1.1.5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 62
 -  `OS: *` macOS 10.13.2
 -  `Stack Traces:` N/A

I just ran into a client today who pointed out that they were just using similar messages to those found in the Material Design examples.

**Comment by TorzuoliH** [comment]
Hi @Splaktar! 

What would you imagine for `min` & `max` date that could follow MD guidelines?

**Comment by Splaktar** [comment]
@TorzuoliH "Choose a date on or after `<min>`" and "Choose a date on or before `<max>`".
