### ISSUE TITLE
Add content to container element by transition

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#1100]
I had this [discussion](https://groups.google.com/forum/#!topic/ngmaterial/vNPDGy0ZcLQ) in the forum..

I want any element (div, md-content, etc..) to have transition when a content is added,
like mentioned in the [spec](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B0NGgBg38lWWWFFOVGp2UFVNZzg/whatismaterial-materialprop-transformingmaterial-020202_PaperShapeLinear_xhdpi_004.webm) the material needs to grow. (Also [related](http://www.google.com/design/spec/patterns/navigational-transitions.html#navigational-transitions-parent-to-child))

Here's an [example](http://embed.plnkr.co/NMvyXBL3FYf2b2XsAlz9/)

I did this kind of expanded list item as seen in Inbox,
The only problem is that there's ```max-height``` transition because there's no way to do it otherwise..
I think it should be included somewhere.. 

Please if you know a better way edit this plunkr
what do you think?

**Comment by epelc** [comment]
@EladBezalel I believe there was an issue about this before. The consensus was that a future version of ng-animate will make it a lot easier to have material design style animations and transitions.

I don't know if you can currently achieve them but I'd look into the above more because you will probably need to overhaul whatever it is you do end up doing.

**Comment by ThomasBurleson** [comment]
@matsko - Any thoughts on this issue/feature?

**Comment by EladBezalel** [comment]
Btw - I updated the example you can review [here](http://embed.plnkr.co/NMvyXBL3FYf2b2XsAlz9)

**Comment by matsko** [comment]
@EladBezalel @ThomasBurleson it's tricky to do this stuff with how CSS and ngAnimate behave. There are plans to improve this with an additional module called ngAnimateLayout, but that's still being developed. For now I think the max-height method is your best bet.

**Comment by CedricDumont** [comment]
is there a milestone for nganimatelayout or can we already have a beta release somewhere ? i need such an animation for mid march. . . if not ready, i will try to implement sthg . . . if its planned, i ll wait a bit. regards

**Comment by david-gang** [comment]
Great issue. Waiting for it.

:+1:

**Comment by noamamit92** [comment]
waiting too :+1:

**Comment by dohomi** [comment]
+1
