### ISSUE TITLE
virtual-repeat: scroll bug when inside of md-tabs

### ISSUE THREAD

**Issue by TudorIoanMarin** [angular/material#11002]
**Actual Behavior**:
 -  `What is the issue? *`
     The md-virtual-repeat's scroll is bugged when it gets hidden and the visible again. I use it inside a tabbed side-menu. When I change the tab and then back to the one that contains the md-virtual-repeat the md-virtual-repeat-offsetter is missplaced. Seems like the translateY is not calculated properly but I think this is a side effect of what the issue is.
 -  `What is the expected behavior?`
   The md-virtual-repeat should work even after hidden/destroyed and reinitialised.

**CodePen** (or steps to reproduce the issue): *
 -  `Steps to reproduce:` 
1. Create virtual repeat with large set of data.
2. Take it out of the view and then insert it again
( issue parrtially applies if you display:none, better  use ng-if)

**AngularJS Versions**: *
 -  `AngularJS Version:` 1.5.5
 -  `AngularJS Material Version:` 1.1.4

**Additional Information**:
 -  `Browser Type: *` -
 -  `Browser Version: *` Chrome, IE
 -  `OS: *` Windows 7
 -  `Stack Traces:` -

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This could be related to https://github.com/angular/material/issues/4336.

But as you say that you have your md-virtual-repeat in a tab, it could also be similar to the issue with [SideNavs](https://github.com/angular/material/issues/7309). Can you please try [the fix that was used there](https://github.com/angular/material/pull/9512/files) in your app to verify that solves this issue? 

This code would need to be run when your tab containing the md-virtual-repeat is shown:
```javascript
var ngWindow = angular.element($window);
ngWindow.triggerHandler('resize');
```

It would be great if you could provide a CodePen that demonstrates the issue as well.

**Comment by Splaktar** [comment]
No demo provided. Assuming that the fix/workaround above worked. If you are still seeing this, please provide a CodePen reproduction.
