### ISSUE TITLE
md-tabs rtl next/previous button

### ISSUE THREAD

**Issue by Oneril** [angular/material#11005]
I got an issue with the md-tabs with direction RTL. When the list of tabs is to long and the next/previous button appear you can't access navigate correctly.
Here is a codepen sample to reproduce the issue.
https://codepen.io/anon/pen/BmegyY

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template and includes screenshots that demonstrate the issue in detail. AngularJS Material and browser versions are also very important. This gives the team the information needed to investigate the bug or prioritize the feature.
