### ISSUE TITLE
md-tooltip doesn't work inside of md-radio-group

### ISSUE THREAD

**Issue by BobbieBarker** [angular/material#1101]
Always, the small chance that I wrote the html wrong or missed something, but as it is it doesn't look like md-tooltip works inside of md-radio-group.

```html
    <md-radio-group layout="row" ng-model="order.by">
      <md-radio-button ng-click="sort('title')" value="title">
        Title
        <md-tooltip>
          Order By Title
        </md-tooltip>
      </md-radio-button>
      <md-radio-button ng-click="sort('created_at')" value="created_at">
        Created
        <md-tooltip>
          Order By Created At
        </md-tooltip>
      </md-radio-button>
      <md-radio-button ng-click="sort('assignee')" value="assignee">
        Assignee
        <md-tooltip>
          Order By Assignee
        </md-tooltip>
      </md-radio-button>
    </md-radio-group>
```

**Comment by BobbieBarker** [comment]
May need to be linked to #1232.

**Comment by rrharvey** [comment]
I believe this is being caused the by the transclude element of the mdCheckbox and mdRadioButton directive templates. This div becomes the parent of the tooltip and is the one registering for the mouseenter event. The md-label style on this element has the pointer-events property set to none which prevents the mouseenter event from being raised. I don't know that the original intent of the property was so I didn't create a pull request that just removed it although that does fix the problem.

**Comment by rschmukler** [comment]
@rrharvey you're spot on. Fantastic help in debugging. I'll take a look and see if we can remove it...
