### ISSUE TITLE
Example of how to apply mask in md-datepicker

### ISSUE THREAD

**Issue by jefferson-william** [angular/material#11014]
**Actual Behavior**:
 -  `What is the issue?` Apply mask in md-datepicker.
 -  `What is the expected behavior?` Date mask in md-datepicker input.

[CodePen Demo](https://codepen.io/jefferson-william-machado/pen/PEYXPQ/)

**AngularJS Versions**:
 -  `AngularJS Version:` 1.6.x
 -  `AngularJS Material Version:` 1.1.5

I needed to change some lines of the Date Picker directive to perfectly work the md-datepicker ng-model value. [Here](https://github.com/jefferson-william/bower-material/commit/d73581ac0d77b6e48689ebeb0572905e61e326ef) is the commit of my changes. 

I needed to mask in md-datepicker on a project and solved it this way. I hope it helps someone.

**Comment by Splaktar** [comment]
This would be a great post for our [forums](https://groups.google.com/forum/#!forum/ngmaterial). Closing it here though as this is for issues/bugs.

**Comment by jefferson-william** [comment]
Perfect! Follow the forum post link [here](https://groups.google.com/forum/#!topic/ngmaterial/wlPiTlzbZnA)
