### ISSUE TITLE
Angular 5 mat-error dose not work with a custom validator

### ISSUE THREAD

**Issue by orenAzuz** [angular/material#11017]
I'm trying to use a custom validator in mat-stepper and it's acting weird for example when it gets an error from the custom validator it won't block the form from continuing although it can be blocked if I use  [disabled]="titlePattern.invalid" but I'm not getting any error message in another scenario
that the user makes another invalid input with the custom one I get the error message from the mat-error - the custom validator error.
I saw an issue very similar to this hear in git hub and they had no solution. I want to know if there is a way to go around this problem or fix it somehow?
thanks

angular 5

**Comment by graingert** [comment]
@orenAzuz this is the angularjs version of material.

**Comment by orenAzuz** [comment]
ok, so where is the angular 5 material?

**Comment by graingert** [comment]
@orenAzuz https://github.com/angular/material2

**Comment by graingert** [comment]
@orenAzuz please close this issue
