### ISSUE TITLE
  tn = new FormControl('', [Validators.required,forbiddenNameValidator(/title/i),]

### ISSUE THREAD

**Issue by orenAzuz** [angular/material#11010]
tn = new FormControl('', [Validators.required,forbiddenNameValidator(/title/i),]
 I have a question is there any way to change the /title/ value dynamically so it can be used in more than one
case? 
I really hope so 
thanks Oren

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. This gives the team the information needed to investigate the bug or prioritize the feature.

Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
