### ISSUE TITLE
Change plunker codepen and jsfiddle links to "hello worlds"

### ISSUE THREAD

**Issue by epelc** [angular/material#1102]
It would be nice if the various links from the github page, docs, and google groups pages to plunker codepen and jsfiddle were to hello worlds instead of blank ones. I think it'd make submitting issues with demos a lot easier.

**Comment by ThomasBurleson** [comment]
@epelc - That is a **great** idea; essentially an Angular Material starter shell...

**Comment by epelc** [comment]
@ThomasBurleson I think it'd really improve the chances of getting working demos instead of code snippets in issues. At Least for me the biggest barrier to giving a working example is I don't have one of these laying around and I think others would say the same.

**Comment by marcysutton** [comment]
Great idea! We have a new Getting Started page coming that will link to more resources. We'll keep this in mind for sure.

**Comment by ajoslin** [comment]
Doc changes including hello world codepens have now landed in master! v
