### ISSUE TITLE
docs(panel): this._relativeToEl[0] is undefined on Firefox 

### ISSUE THREAD

**Issue by Ardeshir81** [angular/material#11035]
**Actual Behavior**:
 -  `What is the issue? *` Panel is throwing error in official site (and is not working)
![image](https://user-images.githubusercontent.com/5755214/34338833-b1922be6-e981-11e7-96c0-60f8cc57c759.png)
[https://material.angularjs.org/1.1.5/demo/panel](https://material.angularjs.org/1.1.5/demo/panel)

 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**AngularJS Versions**: *
 -  `AngularJS Version:`
 -  `AngularJS Material Version:`

**Additional Information**:
 -  `Browser Type: *` FireFox Developer Edition
 -  `Browser Version: *` 58.0b12
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by feloy** [comment]
Here is a CodePen demo reproducing the problem: https://codepen.io/feloy/pen/yKdQVW

**Comment by feloy** [comment]
The problem comes from the use of $event.srcElement which is not supported by Firefox. $event.target should be used instead: https://developer.mozilla.org/fr/docs/Web/API/Event/srcElement
