### ISSUE TITLE
after mdBottomSheet hide its prevent another click on button

### ISSUE THREAD

**Issue by kfir91** [angular/material#11046]
i insert in my code mdBottomSheet show and button that open it.

this is my mdBottomSheet code:
```
$scope.selectPhoto = function () {
  var options = {
    templateUrl: 'student-details/camera-buttons.tpl.html',
    scope: $scope
  };
  $mdBottomSheet.show(options);
}
```

this is my button:
```
<div layout="row" class="imageUpload" ng-hide="fileUri == undefined" ng-click="selectPhoto()">
  <div class="image" flex="15"><img src="images/photo-icon.png"/></div>
</div>
```

after hide mdBottomSheet the button not click any more... actually its do nothing when i click again.
its not fire selectPhoto().

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
