### ISSUE TITLE
Why name elevation shadows "whiteframe"?

### ISSUE THREAD

**Issue by jaminroe** [angular/material#11040]
### Bug, feature request, or proposal:
Why were elevation shadows named `whiteframe`? This doesn't sound very semantic to me. I would've preferred `elevation` or `shadow`.

If there's a new version released, maybe take this into consideration? Thanks!

**Comment by Splaktar** [comment]
Please see the whiteframe demos here: https://material.angularjs.org/latest/demo/whiteframe. I believe that the naming was to indicate that they were a white "card" frame w/ shadows w/o being an actual card (i.e. action buttons, image, etc). 

We cannot make a breaking API change to rename whiteframe at this point in the AngularJS Material project. 

Good news though! The team has already taken action on this feedback and implemented `.mat-elevation` classes in Angular Material: https://material.angular.io/guide/elevation. There are no more whiteframes in that library. 😃

**Comment by jaminroe** [comment]
Cool, no worries!
