### ISSUE TITLE
mdPanel: controllerAs has no effect

### ISSUE THREAD

**Issue by tyler-austin** [angular/material#11048]
### Bug, feature request, or proposal:

$mdPanel controllerAs has no effect when controller is referenced as a string

### What is the expected behavior?

controllerAs so create an alias for the controller

controller: 'ExampleController',
controllerAs: '$ctrl',

### What is the current behavior?

the controller alias remains the name of the controller
console.log('Ctrl Name', this.constructor.name);

### What is the use-case or motivation for changing an existing behavior?

to keep controllers in separate files

### Which versions of AngularJS, Material, OS, and browsers are affected?

angularjs = 1.6.6
Material = 1.1.5
os = windows 10
browser = firefox

### Is there anything else we should know? Stack Traces, Screenshots, etc.

from controller:
console.log('Ctrl Name', this.constructor.name);

**Comment by mckenzielong** [comment]
I could be mistaken, but I believe this is resolved by: https://github.com/angular/material/commit/f4b19febd79b6ca6a8c95a57a5e2787187df3e3d

**Comment by Splaktar** [comment]
Please test with HEAD and verify that this is still an issue. If it is still a problem for you, please provide a CodePen demo so that we can debug the issue.
