### ISSUE TITLE
ripple color of FAB with a link

### ISSUE THREAD

**Issue by ben04** [angular/material#1104]
Hi,

I just added the ng-href to my fab and now the ink ripple color is red. If there is no ng-href attribute it's grey.

The red doesn't fit for me, so I have to change that. I already found the md-ink-ripple attribute for the button element in the html, but if I do that, it seems as if the ripple effect is in front of the fab icon, usually it seemed to be behind it, the icon stayed clearly visible.

Can someone either tell me how to deactivate the color change with the ng-href attribute or how to change the ripple color without it coming to the foreground?

Greetz Ben

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
