### ISSUE TITLE
play button of video tag on android firefox doesn't work

### ISSUE THREAD

**Issue by gnn06** [angular/material#11056]
### Bug, feature request, or proposal:
bug

### What is the expected behavior?
when using VIDEO tag, on android firefox, when click on play button, video should start

### What is the current behavior?
video doesn't playing. 

##### Detailed Reproduction Steps: 
https://codepen.io/gnn06/pen/YYYdQa

### Which versions of AngularJS, Material, OS, and browsers are affected?
angularjs 1.5.5,
material angularjs 1.1.0
android firefox 57.0.4

### Is there anything else we should know? Stack Traces, Screenshots, etc.
no error into console
if I remove ngMaterial from the dependencies, play button works
works well with android chrome
works well with desktop firefox

**Comment by Splaktar** [comment]
I was able to reproduce the problem with your CodePen using AngularJS Material 1.1.0.

I updated the [CodePen](https://codepen.io/Splaktar/pen/NXzzde) to AngularJS Material 1.1.5 and then ran it in Debug view on Firefox Beta for Android and it worked fine.
