### ISSUE TITLE
Bottom-Sheet backdrop not animating in/out

### ISSUE THREAD

**Issue by ttvd94** [angular/material#11053]
I'm using _Angular (1.6.7)_ and _Angular Material (1.1.5)_ along with _jQuery (3.2.1)_ in my web-app.
**The problem is** when the bottom-sheet is showing up, backdrop just jumps in and by leaving, it won't get any `ng-leave`, `ng-leave-active` or similar class. It just gets deleted immediately (traced and it was done by a jQuery function).

Found ZERO similar problem by googling the issue.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. We'll need a CodePen that demonstrates this issue to be able to debug and isolate the issue that you're seeing.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
