### ISSUE TITLE
Datepicker for birthday input

### ISSUE THREAD

**Issue by burka** [angular/material#11057]
The current version of the date picker is unusable for birthday input. 

It would be great to have a version that allows entering a pre 2000 date without excessive scrolling or clicking.

#4251 is closed, but with that solution you need to scroll sooo long if you where born before 2000.
#4216 is closed.
#5971 is closed because some internal UX Team has some changes in the pipe.

The [React Date Picker](http://www.material-ui.com/#/components/date-picker) has at least some (not intuitive) way to scroll years via clicking the years. Does that one not comply to the UX-Guidelines?

**Comment by Splaktar** [comment]
Can you please take a look at this [CodePen](https://codepen.io/Splaktar/pen/zpygNK) and see if this does what you would like? It is a subset of what's in the demo page: https://material.angularjs.org/latest/demo/datepicker

The first example is not new in 1.1.6, but it seems perfect for picking a birthday. You can select the year and month first, then the date. The scrolling to pick the year does not seem excessive to me.

**Comment by burka** [comment]
That looks a way more usable! Thanks :-)

for the Month datepicker, I can [add a formatter](https://codepen.io/floh/pen/rpbLXP) to just print out month/year :+1:  

Is it possible to set the default Date to something way more in the past? 
It would be great to have another starting point than today if we expect people at an average age of 40 or 50 to enter their date without pre-filling the field.

**Comment by Splaktar** [comment]
It seems like that may be possible via a custom implementation of `parseDate`. From the [docs](https://material.angularjs.org/HEAD/api/service/$mdDateLocaleProvider):
```javascript
    // Example uses moment.js to parse and format dates.
    $mdDateLocaleProvider.parseDate = function(dateString) {
      var m = moment(dateString, 'L', true);
      return m.isValid() ? m.toDate() : new Date(NaN);
    };
```
I haven't had time to test it, but does changing `new Date(NaN)` to something like `new Date("1970-01-01")` do what you want?

**Comment by burka** [comment]
Great, thanks! That should solve it :+1:
