### ISSUE TITLE
Angular Materials md-select does not function with new version of Chrome!

### ISSUE THREAD

**Issue by mishatsvelik** [angular/material#11065]
### Bug, feature request, or proposal:
MD-select drop-down simply not working with new version of Chome? Also there is no error in the console.

### What is the expected behavior?
You can see what the expected behaviour is here, it behaves fine with the Edge browser, normal MD-select behaviour https://www.screencast.com/t/06fxR5yPzapJ

### What is the current behavior?
Again same video (beginning): https://www.screencast.com/t/06fxR5yPzapJ 

### What is the use-case or motivation for changing an existing behavior?
MD-select to display options, which it is not at the moment

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS 
Chrome

### Is there anything else we should know? Stack Traces, Screenshots, etc.
See video above

**Comment by mishatsvelik** [comment]
Apologies, this was to do with one of my browser extensions which I uninstalled

**Comment by Splaktar** [comment]
OK, thank you for letting us know! Extensions can certainly cause issues like that unfortunately.
