### ISSUE TITLE
ripple: ink ripple not always removed when animation is complete on iOS

### ISSUE THREAD

**Issue by vbraun** [angular/material#11069]
### Bug, feature request, or proposal:

The ink ripple is not always removed on mobile browsers

Note: this is different from the simulated hover on mobile browsers; The simulated hover is also present but that can be overridden in css if one doesn't want it. But the stale ink ripple is a real bug.

This seems to be related to synthesized mousedown events; When I add 

    if (!event.$material) return;

to InkRippleCtrl.prototype.handleMousedown then I cannot reproduce it any more. Though that alone is probably too simple a fix since $mdGesture.isHijackingClicks need not be turned on.

### What is the expected behavior?

Ink ripples disappear eventually.

### What is the current behavior?

Sometimes, an ink ripple remains. Not initially, but eventually when combining long and short clicks.

##### Detailed Reproduction Steps: 

* Open codepen in chrome mobile emulator
* Long-click on button (>1s)
* Wait (>1s)
* Short-click on button
* Wait
* Short-click on button 

Now there is a 
````
<div class="md-ripple-container" style="background-color: rgba(33, 33, 33, 0.1);"><div class="md-ripple md-ripple-placed md-ripple-scaled md-ripple-active" style="left: 29px; top: 30px; background: rgb(33, 33, 33); width: 132.378px; height: 132.378px; border-color: rgb(33, 33, 33);"></div></div>
````
in the dom that does not go away

### Which versions of AngularJS, Material, OS, and browsers are affected?

AngularJS material 1.1.5
Android chrome
iOS Safari
Chrome mobile emulator

**Comment by jpike88** [comment]
It seems to be reproduced on a quick tap, but taps longer than ~1 second allow it to disappear correctly

**Comment by jpike88** [comment]
I think this is also related to a bug where md-tooltips stay shown after a tap. There should be some sort of timed 'complete' signal that's guaranteed to fire

**Comment by jpike88** [comment]
@Splaktar just want to thank you for your efforts, glad to see this project is getting the love it deserves. I'll happily contribute when I get a moment

**Comment by vbraun** [comment]
My workaround is to override $mdInkRipple with my own provider that essentially adds 
~~~~
        if (this.$mdGesture.isHijackingClicks && !event.$material) return;
~~~~
to the beginning of handleMousedown. I also rewrote it in typescript, so I don't have a simple patch...

**Comment by jpike88** [comment]
I’m using typescript too!

**Comment by jpike88** [comment]
I made a workaround fyi

```
$provide.decorator("$mdInkRipple", function ($delegate) {

            var methodHandle = $delegate.attach;

            function decorateInk() {

                const rippleController = methodHandle(arguments[0], arguments[1], arguments[2]);

                if (window.isiOS) {

                }
                rippleController.handleMousedown = function (event) {
                    if (this.$mdGesture.isHijackingClicks && !event.$material) return;
                    if (this.mousedown) return;

                    // When jQuery is loaded, we have to get the original event
                    if (event.hasOwnProperty('originalEvent')) event = event.originalEvent;
                    this.mousedown = true;
                    if (this.options.center) {
                        this.createRipple(this.container.prop('clientWidth') / 2, this.container.prop('clientWidth') / 2);
                    } else {

                        // We need to calculate the relative coordinates if the target is a sublayer of the ripple element
                        if (event.srcElement !== this.$element[0]) {
                            var layerRect = this.$element[0].getBoundingClientRect();
                            var layerX = event.clientX - layerRect.left;
                            var layerY = event.clientY - layerRect.top;

                            this.createRipple(layerX, layerY);
                        } else {
                            this.createRipple(event.offsetX, event.offsetY);
                        }
                    }
                };

                return rippleController;

            }

            $delegate.attach = decorateInk;
            return $delegate;

        });
```

**Comment by jpike88** [comment]
This actually didn't fix my issue. I'm now investigating to see if auto cleanup needs improvement, I think the issue lies after a 'touchend' event is fired (or should be fired)

**Comment by jpike88** [comment]
Found the problem. md-tab-item intercepts all 'touchend' events, so they never get registered by the ripple controller. Not sure what to do with it though... I guess I need md-tab-item to pass that event to the ripple controller too

**Comment by jpike88** [comment]
http://streaka.testing.videos.s3.amazonaws.com/screencast_2018-05-29_14-38-08.mp4
