### ISSUE TITLE
mat-icon issue styling with color

### ISSUE THREAD

**Issue by patricklim75** [angular/material#11063]
### Bug, feature request, or proposal:
Color doesn't apply on mat-icon

### What is the expected behavior?
color applied to the svg mat-icon component

### What is the current behavior?
either styling ddirectly the color in the component or in css file using attribute color or fill doesn't work

### Which versions of AngularJS, Material, OS, and browsers are affected?
angular: 5.0.0
mozilla: 57.0.4
angular/material: 5.0.4

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
