### ISSUE TITLE
 add a way to give class to inner component

### ISSUE THREAD

**Issue by Linton-Samuel-Dawson** [angular/material#11075]
### Bug, feature request, or proposal:
request: add a way to give class to inner component and not override all of element in css

### What is the expected behavior?
inner component also can get a class
### What is the current behavior?
for example in md-select there or md-tab there are no way to add style to inner components

**Comment by Splaktar** [comment]
`md-container-class` can be used for `md-select` as described in https://material.angularjs.org/latest/api/directive/mdSelect.

Can you please provide more information on your use case related to styling of tabs? are you wanting to style the tab body, label, etc? A CodePen that demonstrates the issue would be really helpful.

**Comment by Splaktar** [comment]
Demo and feedback not provided.
