### ISSUE TITLE
Add A Filter To Material Table HTTP Datasource? Calling/Canceling HTTP endpoint multiple times?

### ISSUE THREAD

**Issue by jtmgio** [angular/material#11072]
### Bug, feature request, or proposal:
Bug?

### What is the expected behavior?
To not call/cancel multiple HTTP requests. Should only call HTTP request once on load

### What is the current behavior?
I have added a filter to the HTTP Datasource (used the example in the material docs). When adding this in, the Datasource calls the same http service multiple times (cancels these). The table "still works" but i want to prevent extra calls to my server. 

## CodePen and steps to reproduce the issue:
https://codepen.io/anon/pen/JMaqKP

##### Detailed Reproduction Steps: 
Use the material http table service in their example and add in more observables to the displayDataChanges array. I am adding in filtering and an special queryString 

### What is the use-case or motivation for changing an existing behavior?
Be able to update the GET HTTP call with a filter/querystring parameter 

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular 5, Material 5 all browsers 

### Is there anything else we should know? Stack Traces, Screenshots, etc.
I am not sure if this is the correct way to implement this.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
