### ISSUE TITLE
mdTabs inside ng-repeat not working properly

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#1107]
Well i tried to put some tabs inside ng-repeat, i tried many combinations and finally understood this is a bug.
I can't point where the problem occurs but here's an [example](http://embed.plnkr.co/xfCQCUL4tNSJo8axaPfg/) of whats happening.

thanks ahead :)

**Comment by ThomasBurleson** [comment]
@EladBezalel  - You should **not** put Tabs inside a ng-repeat. That is not a Material aesthetic. Tabs are primary navigation or content controls.  With that said, this still sounds like a bug.

**Comment by EladBezalel** [comment]
I do agree with you @ThomasBurleson , but in my situation I have expanding items (#) and inside them I want to use tabs because in mobile the item expands to full-screen and the tabs are used as primary navigation there.

**Comment by cgat** [comment]
It's worth mentioning that that the angular material documentation (the demo for tabs) uses an example with ng-repeat. If this is not meant to be the case, this example should be removed.

**Comment by ThomasBurleson** [comment]
@cgat - you missed the point. Tabs can be used in repeaters. Tabs should **not** be nested within Tabs

**Comment by cgat** [comment]
@ThomasBurleson Ahh, yes. Sorry for the confusion

**Comment by EladBezalel** [comment]
The tabs is not nested within tabs, it's nested in a repeater, I want tabs for each item in the list.. Is this fixed?

**Comment by ThomasBurleson** [comment]
@EladBezalel - no this has not yet been resolved. Currently we only support using `<md-tab>`with a ng-repeat (not `<md-tabs>`).

**Comment by EladBezalel** [comment]
Thanks for reopen

**Comment by ratscrew** [comment]
+1

**Comment by jlubin1** [comment]
+1

**Comment by verdverm** [comment]
+1

**Comment by fourpixels** [comment]
Hey guys, what's up with this issue? Just spent a few hours to figure out that the problem is not in me :) Is it resolved, or what? (as I see ready label has been removed?)

**Comment by robertmesserle** [comment]
This is resolved in master, and will be in the 0.9.0 release
