### ISSUE TITLE
fab-toolbar: links in FAB toolbar disappear and main icon becomes unresponsive when we open site in two tabs

### ISSUE THREAD

**Issue by sandeepmhaske** [angular/material#11071]
### What is the expected behavior?
The links in FAB toolbar should not disappear when we open site in two tabs of same browser.

### What is the current behavior?
The links in FAB toolbar are disappearing when we open site in two tabs of same browser.

##### Detailed Reproduction Steps: 
1) Open the site in two tabs of same browser.
2) Click on fab toolbar icon of site opened in first tab.
3) Click on fab toolbar icon of site opened in second tab.
4) Go back to first tab and you will observed that links in fab toolbar are disappeared.
5) Go back to second tab and will observed same issue.
6) Also the fab icon will be observed unresponsive at the end.

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS 1.x 
Material 1.x
OS - Windows 8
Browser - Chrome

Please refer below link to reproduce the issue:
https://material.angularjs.org/latest/demo/fabToolbar

### Is there anything else we should know? Stack Traces, Screenshots, etc.
PFB screenshots:

Before switching between two tabs:
![fabtoolbar_beforetabswitch](https://user-images.githubusercontent.com/32016266/34986644-36262fe8-fade-11e7-99e5-828a9e59f278.jpg)

After switching between two tabs: 
![fabtoolbar_aftertabswitch](https://user-images.githubusercontent.com/32016266/34986643-35fbdfd6-fade-11e7-8f01-f7e056c4f3b9.jpg)

**Comment by Splaktar** [comment]
I can't reproduce this with `1.1.12` using https://material.angularjs.org/1.1.12/demo/fabToolbar.

**Comment by dredlich** [comment]
I can reproduce it, when opening the fab-toolbar via the the fab-trigger, then minimizing the browser window and then restoring / maximizing the browser window. Already opened new issue here: https://github.com/angular/material/issues/11760

**Comment by sandeepmhaske** [comment]
Hello,

I am able to reproduce this issue when I go to another tab and then come back. The fab-trigger stop working and also links on fab-toolbar got disappeared.

It will be a great help if someone can suggest a fix for the same.

Thank you in advance.

**Comment by Splaktar** [comment]
@sandeepmhaske I believe that is the same issue as https://github.com/angular/material/issues/11760. This issue is about using two simultaneous tabs.
