### ISSUE TITLE
md-button: bolder font

### ISSUE THREAD

**Issue by eckyputrady** [angular/material#1108]
Hi,

according to http://www.google.com/design/spec/style/typography.html#typography-standard-styles

> Button style (Medium 14sp, all caps) is used for **all** buttons, whether they are ink or material.

(Emphasis on ALL)

However, current implementation of md-button's font is not as bold as the examples from the page.

Do you think the style for the font should be bold by default? I find `font-weight: 500` looks very similar with the examples.

Thanks

**Comment by marcysutton** [comment]
I agree, Medium equals `font-weight: 500` in our codebase. Updated to reflect the spec.

**Comment by viztastic** [comment]
Hi, when I implement md-button I still seem to have the issue where it appears as a very light weight font relative to what appears in the doc, my code is below:


|   <md-content class="md-padding" layout="row" layout-sm="column">
|        <form name="signin">
 |           <md-input-container>
 |               <label>Email</label>
  |              <input type="email">
   |         </md-input-container>
    |        <md-input-container>
     |           <label>Password</label>
   |             <input type="password">
    |        </md-input-container>
   |         <md-button>Sign in</md-button>
   |         <md-button>Sign up</md-button>
   |     </form>
  |  </md-content>

**Comment by viztastic** [comment]
(For what it's worth, I am running on latest version of chrome... and running of the 0.8.3 branch) @marcysutton

**Comment by Soulcyber** [comment]
Same problem as viztastic

**Comment by SamarRizvi** [comment]
Use `<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,**500**,700,400italic">` in the head of your index.html
