### ISSUE TITLE
mdSidenav: inconsistent use of transform property

### ISSUE THREAD

**Issue by free-easy** [angular/material#11086]
### Bug, feature request, or proposal:
Why do you use `translate3d` for `.sidenav-left` and `translate` for `.sidenav-right`?
Is this a bug or there is some reason behind?

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular Material 1.1.6

**Comment by Splaktar** [comment]
This is due to a [previous bug fix](https://github.com/angular/material/issues/6007#issuecomment-216092509). If you are seeing a problem with the sidenav-left, please create a CodePen that demonstrates the issue.

**Comment by free-easy** [comment]
I was just looking around into the angular material's source code in order to learn something.
For now I'm not noticing bugs with `md-sidenav-left`.
Close this issue for now. If I can reproduce the mentioned bug I'll reopen.
