### ISSUE TITLE
Autoselected button on opening sidenav

### ISSUE THREAD

**Issue by rutgervd** [angular/material#11089]
### Bug

When opening a sidenav (toggle) with a button, the button in the sidenav gets selected and visa versa

### What is the expected behavior?

The button should not be selected when the sidenav opens or closes

## CodePen and steps to reproduce the issue:

https://angular-zzab5i.stackblitz.io

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
