### ISSUE TITLE
md-datepicker does not open/close when leaving to another tab

### ISSUE THREAD

**Issue by yonatankrug** [angular/material#11099]
### Bug, feature request, or proposal:
The date picker does not open/close when leaving current tab.
It worked fine until I was leaving to another tab and came back.

### What is the expected behavior?
The date picker should open/close when returning to current tab

### What is the current behavior?
the date picker is not showing

##### Detailed Reproduction Steps: 
use the datepicker and than move to another tab or window
### What is the use-case or motivation for changing an existing behavior?
UX issue

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular 1.4.11
Material 1.1.5
mac OS high sierra
Chrome version 63.0.3239.132

**Comment by Splaktar** [comment]
Are you talking about another browser tab? or an `md-tab`? or an `md-nav-item`?

Testing this out on the https://material.angularjs.org/HEAD/demo/datepicker seems to give the expected behavior.

Please provide a CodePen that demonstrates the issue.
