### ISSUE TITLE
themes folder should be deleted from the bower repository

### ISSUE THREAD

**Issue by PaulMougel** [angular/material#1110]
Since 47f0d09e9ebd87891703fa2b7e81355ce3952a86:

> Themes are no longer defined by linked CSS files.
> Themes are now defined through Javascript only.
> The `default` theme is still shipped with angular-material.

And indeed, the `themes` folder in the [bower-material repository](https://github.com/angular/bower-material) hasn't been updated since 0.6.1-c62b970. But it is still included in the repository. Shouldn't it be deleted?

**Comment by ajoslin** [comment]
Done in https://github.com/angular/bower-material/commit/65380adcd64feb1ea5b4fe276564bfaae648e740, thanks.
