### ISSUE TITLE
md-button not working on IE9

### ISSUE THREAD

**Issue by mauricionr** [angular/material#1111]
md-button animations and events not working on IE9

![mdbuttonnotworkingie9](https://cloud.githubusercontent.com/assets/2263551/5612553/0b43bf5e-94be-11e4-9a69-fee33ccedfd4.png)

**Comment by ferc** [comment]
*Readme*:
Please note that using Angular Material requires the use of Angular 1.3.x or higher. *Angular Material is targeted for all browsers with versions n-1; where n is the current browser version.*

Current version of IE is 11, so, Angular Material supports IE11 and IE10, not IE9.

**Comment by mauricionr** [comment]
Right @ferc  ,but test md-button in IE10, only with double click it's work's.

tks in advance.

**Comment by marcysutton** [comment]
So is this issue occurring in IE10? Can you provide a Codepen or Plunker so we can verify? Thank you!

**Comment by mauricionr** [comment]
I'm trying to reproduce on codepen, because i've got this issue in my project.
Tks in advance!
