### ISSUE TITLE
Calling typescript function after html rendering

### ISSUE THREAD

**Issue by learn44** [angular/material#11114]
H @Splaktar ,
I have a modal where html is rendered first and then i need to create ckeditor instance. I am using below code currently to achieve this:

```
//where editor instance will be created.
 <input type="text" formControlName="data" style="height: 320px; width: 603px;" id="editor-{{policyData}}" />
<span *ngIf="generate">
{{generateEditors()}}//calling type script function to create a instance on above

.ts:
generateEditors() {
debugger;
this.ckEditor = new CkEditor();
this.ckEditor.create('purpose-editor');
this.generate = false;
}
```
The problem in this function is it is calling again and again infinite calling and my app gets hang.

Secondly I have installed ng-onload package but I dont know how to import and use that in //where editor instance will be created.

So quick help in this either case will be appreciated.

**Comment by learn44** [comment]
Hi,
I am waiting for reply on this.
Thanks

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by learn44** [comment]
Hi @Splaktar,
                      Posted in both mentioned links. I am waiting for reply there on this to proceed further.
