### ISSUE TITLE
md-radio-button & button don't remove the focus styles from DOM after navigating away from the element

### ISSUE THREAD

**Issue by smucleopatra** [angular/material#11119]
### Bug, feature request, or proposal:
md-radio-button & button in Edge, IE, and Firefox keeps the style for a selected button after clicking the button then navigating away from the button using the keyboard. This gives a false indication that the button is still in focus, and the user can be confused seeing multiple items in focus on the same page.
These are the styles that don't get cleaned up (cdk-focused cdk-keyboard-focused).

### What is the expected behavior?
The styles should be removed after navigating away from the button using the keyboard.

### What is the current behavior?
The button stays selected

##### Detailed Reproduction Steps: 
Add a material button in a page
Navigate to the button using keyboard on Edge browser
Press Enter
Use tab on the keyboard to navigate away from the button to the next element
Observe the style on the button

### What is the use-case or motivation for changing an existing behavior?
This is a Ay11 bug as it affects accessibility users, and it's also a usability issue. The user need to see/hear only one item is in focus at a time.

### Which versions of AngularJS, Material, OS, and browsers are affected?
Windows 10, Edge, IE, Firefox and "@angular/material": "2.0.0-beta.8"

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
