### ISSUE TITLE
Ng-transclude error in md-radio-button

### ISSUE THREAD

**Issue by rainnaren** [angular/material#11113]
### Bug, feature request, or proposal:
Error: [ngTransclude:orphan] Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found. Element: <div ng-transclude="" class="md-label ng-scope">

### What is the current behavior?
i implement the md-radio-group button in the mDDataTable Custom Cell it seems to be working good but iam getting ng-transclude error in console

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
