### ISSUE TITLE
mdSelect: doesn't handle promise rejection

### ISSUE THREAD

**Issue by free-easy** [angular/material#11118]
### Bug, feature request, or proposal:
mdOnOpen handles promises. But if the promise is rejected the spinner is never hidden.
`$$loadingAsyncDone` is never set to true. 

### What is the expected behavior?
The spinner should be hidden when promise is rejected.

### What is the current behavior?
The spinner is not hidden.

##

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
