### ISSUE TITLE
mdAutocomplete: doesn't handle promise rejection

### ISSUE THREAD

**Issue by free-easy** [angular/material#11117]
### Bug, feature request, or proposal:
`md-items` supports promise and in that case a loading bar is shown. But when a promise gets rejected the loading is never hidden.

### What is the expected behavior?
If the promise is rejected the loading bar is hidden or becomes red (or maybe the warn color of the theme) for a while and then disappears.

### What is the current behavior?
The loading bar is not hidden.

##

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. The CodePen demo/reproduction is not optional.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
