### ISSUE TITLE
menu: should close when pressing tab

### ISSUE THREAD

**Issue by jelbourn** [angular/material#11123]
Currently, when you tab from an open menu it moves through the items and then escapes the panel into the rest of the page. The menu should actually just close upon pressing tab and the focus should move to the next focusable element (the menu items shouldn't be tab stops). `MatMenu` does the right thing for this and can be an example.

**Comment by Splaktar** [comment]
I've created a simple [CodePen](https://codepen.io/Splaktar/pen/vdWevR?editors=1010) that demonstrates the issue.

**Comment by Splaktar** [comment]
Also the examples for menuBar in the docs have the same problem. Just to confirm, this change would not disable keyboard interaction with the menus (which can still be done with the arrow keys). It would just close the menu on `TAB` in addition to `ESCAPE`.

**Comment by Splaktar** [comment]
PR is posted.

**Comment by jelbourn** [comment]
Yes, and tab should also still advance to the next element in the tab order.
