### ISSUE TITLE
radioButton: integer values are not working because of strict comparison

### ISSUE THREAD

**Issue by artch** [angular/material#1112]
If the `md-radio-group` model is defined as integer, it doesn't display checked status (`md-checked` class) because of the strict `===` value comparison [here](https://github.com/angular/material/blob/master/src/components/radioButton/radioButton.js#L237):
```javascript
var checked = (rgCtrl.getViewValue() === attr.value);
```

Bug reproduce suite: http://codepen.io/artch/pen/jEVKYe?editors=101

**Comment by marcysutton** [comment]
After looking at this [JavaScript equality table](http://dorey.github.io/JavaScript-Equality-Table/), it looks like we can get away with `==` in this instance.

**Comment by gkalpak** [comment]
I haven't looked properly into it, but using `==` should be avoided if possible.
Why not convert the `viewValue` to string ?

**Comment by marcysutton** [comment]
Good question–that does seem like a wise idea given that `==` is basically the `!important` of JavaScript
