### ISSUE TITLE
md-button ink ripple triggers on new button shown in place of old button on iOS / Android

### ISSUE THREAD

**Issue by ryanoberleitner** [angular/material#11128]
### Bug, feature request, or proposal:
Clicking an md-button that has ink enabled, hiding that button, then showing a md-list (which inherently have md-buttons) in its place, the ripple effect is triggered on whatever list item appears where the previous button was clicked.

### What is the expected behavior?
Ripple should not appear on new md-button / md-list-item

### What is the current behavior?
Ripple can appear on an item that was not clicked

##### [CodePen Demo](https://codepen.io/roberleitner/full/KQQpze/) which shows your issue: 
https://codepen.io/roberleitner/full/KQQpze/

##### Detailed Reproduction Steps: 
Set Chrome Dev tools to iOS or Android device
Open code pen
Click "Show List" button - button hides itself, shows list
List appears, list item that is displayed where button was clicked shows ripple effect
Click a list item - list hides itself, shows button. if it was the item in the center of the screen, the button will trigger its ripple effect
Ripple effect only goes away if focus is given to another element

### What is the use-case or motivation for changing an existing behavior?
Would like to have a button that shows a full screen md-dialog containing an md-list of clickable items and not have the ripple effect bleed into the dialog.

### Which versions of AngularJS, Material, OS, and browsers are affected?
angularjs 1.6.8
angular material 1.1.7
Android emulator for KitKat and Oreo
Nexus 6p Oreo
iOS 8 Simulator 11.2

### Is there anything else we should know? Stack Traces, Screenshots, etc.
![Screen recording from Android Oreo Emulator](https://user-images.githubusercontent.com/3179319/36356184-aa5d1608-14b3-11e8-931f-2669f25f069b.gif)

**Comment by Splaktar** [comment]
I have seen similar issues in the past. Ideally, for buttons that have animations like this and involve some navigation/dialog, you don't want to navigate/change the UI on ng-click immediately, but instead after the animation has completed.

It looks like the current default ripple duration is 450ms.

Here's your [CodePen](https://codepen.io/Splaktar/pen/XZxdOg) updated to used this delay to let the animation complete. It seems to resolve the behavior in both the show and hide list cases.

I'm going to close this for now, but please feel free to respond if this doesn't fully resolve your issue.
