### ISSUE TITLE
mdSelect: ng-show added to all md-options

### ISSUE THREAD

**Issue by free-easy** [angular/material#11121]
### Bug, feature request, or proposal:
Wouldn't it be better to have a `div` wrapping the `md-option`s and have a unique `ng-show='$$loadingAsyncDone'` on the `div`?

`md-select` is very slow when having thousand options.
Could this improve a little bit?

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. A CodePen demo is required.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

Note that you should never put thousands of options in a `select` or `md-select`. No user can actually deal with that many options. An `md-autocomplete` is an option to use in cases where there are 50+ options. The [docs](https://material.angularjs.org/latest/demo/autocomplete) demonstrate most of how to do this, you just need to hook it up to your own API for returning search results to match the autocomplete input.
