### ISSUE TITLE
md-tabs: md-dynamic-height causing bug on chrome mobile

### ISSUE THREAD

**Issue by rosostolato** [angular/material#11130]
![bug](https://user-images.githubusercontent.com/27731641/36485087-080cf19a-16fa-11e8-8032-538f67993cbb.jpg)

This table should fill the intire page, but at this point, it's hiding all its content.

When I was debugging, I realized that removing `overflow: hidden` fixes the bug, but it causes poor effect while tabs are changing. To fix it, I had to disable tabs animation on css.

This is the solution I found but not that great, I lose tabs animation or I lose dynamic height.

I tried on firefox mobile and there was no bug, only on chrome.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. The CodePen demo of the issue is required.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
