### ISSUE TITLE
Issue with the github cdn

### ISSUE THREAD

**Issue by soulr3aver** [angular/material#11141]
### Bug, feature request, or proposal:
The github cdn have been blacklisted and they don't work at all

### What is the current behavior?
They don't work

## CodePen and steps to reproduce the issue:
https://gitcdn.link/repo/angular/bower-material/master/angular-material.js

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS 1.x

**Comment by Splaktar** [comment]
https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.7/angular-material.js and https://cdn.gitcdn.link/cdn/angular/bower-material/master/angular-material.css work.

I'll update the README.

**Comment by Splaktar** [comment]
Opened https://github.com/angular/material/pull/11143 to fix this.
