### ISSUE TITLE
$mdPanel.newPanelAnimation(...).targetEvent is not a function

### ISSUE THREAD

**Issue by sebakerckhof** [angular/material#11146]
### What is the expected behavior?
Working as explained here: https://material.angularjs.org/1.1.7/api/service/$mdPanel

### What is the current behavior?
Not working. Error: `$mdPanel.newPanelAnimation(...).targetEvent is not a function`

## CodePen and steps to reproduce the issue:
https://codepen.io/anon/pen/KQExaV

Click the 'show panel' and look at the console logs.

### Which versions of AngularJS, Material, OS, and browsers are affected?
1.1.7

**Comment by Splaktar** [comment]
Sorry, those docs are wrong. I'll put up a PR to improve them, thank you for pointing this out!

https://material.angularjs.org/latest/api/type/MdPanelAnimation has the details that you're looking for.

I updated your [CodePen](https://codepen.io/Splaktar/pen/aqxJmw?editors=1010#0) to use this and it now works.
