### ISSUE TITLE
bottom-sheet: touch-action not reverted on cleanup

### ISSUE THREAD

**Issue by jonaszuberbuehler** [angular/material#11147]
### Bug
After mdBottomSheet is hidden `touch-action: pan-x;` is not removed from parent element (ie body) preventing vertical scrolling on mobile devices.

### What is the expected behavior?
Any added touch-action should be reset to initial state.

### What is the current behavior?
The added touch-action ist not removed on https://github.com/angular/material/blob/290c72a5ddc21edbcd0980320e0be2f4059f3c24/src/core/services/gesture/gesture.js#L252-L255.

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS 1.6.6, Material 1.1.7, Android, Chrome

**Comment by Splaktar** [comment]
https://github.com/angular/material/pull/9179 does a little bit with the bottom-sheet cleanup, but it doesn't appear to fix this issue in the gesture.js `onCleanup` function.

**Comment by Splaktar** [comment]
I am able to reproduce this on https://material.angularjs.org/latest/demo/bottomSheet where it doesn't clean up the style on 
```html
<div class="demo-content bottomSheetDemo1 ng-scope" style="touch-action: pan-x;">
```

**Comment by Sayene** [comment]
onCleanup does not remove touch-action - it only restores its previous value (if was set) - that is apparently a bug. As a work-around: style="touch-action:auto;" can be set to parent element - so it gets restored by onCleanup - allowing to scroll after bottom-sheet was closed.

**Comment by mebibou** [comment]
We have a very similar (if not the same) issue now on iOS 13 where pages do not scroll at all anymore after the first click on the navbar bottom-sheet, preventing any user from scrolling on any pages in our production website! by debugging what I saw was a `touch-action: pan-x` added directly on the **body** element! This needs fixing ASAP as I imagine many people finding the same issue now (FYI, this did not happen on iOS 12)

This is a critical issue

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11845 fixes this.
