### ISSUE TITLE
md-switch ng-true-value doesn't support $resource instances

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1115]
If I have a `User` $resource, then I want to set the true value to a user, it sets it to a copy of the object instead of the original. This changes the prototype.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr of this issue.

**Comment by ilanbiala** [comment]
@ThomasBurleson can you guys add Material as a library on CodePen or Plunkr? I can't get loading the scripts myself working.

**Comment by ilanbiala** [comment]
It only works when you do `{{user}}` where `$scope.user` is a $resource instance. Then you lose the $resource class around it, though...so that is not useful.

**Comment by PaulMougel** [comment]
@ilanbiala Here's my Plunker template: http://plnkr.co/edit/G0CCmRfi9CHxCPkwkiND . Just fork it
