### ISSUE TITLE
mat-grid-list is not working as expected.

### ISSUE THREAD

**Issue by goutty11** [angular/material#11167]
My grid-list has 3 columns and 3 tiles.
What I'm trying to do:
-> When I mouse over the first tile i'm changing the colspan to 2 and rowspan to 2 for my first tile in first column and the remaining tiles col and row span stays at 1.
-> When I mouse over the second tile i'm changing the colspan and rowspan to 2 for my second tile in first column and remaining tiles col and row span stays at 1. 
Actual Behavior:
When I mouse over the first tile
At this time first tile occupies 2 columns and 2 rows. The remaining two tiles, each occupy 1 column in row 1 and 1 column in row 2.
The expected result is shown when I mouse over second tile  in column 2.
But when I mouse over the third tile i'm not getting the same behavior. My tile occupies a 2nd row and 3rd row instead of occupying 1st and 2nd row.

##### Detailed Reproduction Steps: 

I'm trying the move the tile's height in a grid `

with` in a specified row and column

Angular 5, Angular Material 5.2.4, Chrome Browser

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
