### ISSUE TITLE
feat(chips): add support for ng-change

### ISSUE THREAD

**Issue by free-easy** [angular/material#11161]
### Bug, feature request, or proposal:
`ng-change` is not triggered when I add a chip or remove it.

### What is the expected behavior?
`ng-change` should be triggered.

### What is the current behavior?
`ng-change` is not triggered.

##### Detailed Reproduction Steps: 

Try to insert some chip and you'll notice that ng-change is not triggered.

### What is the use-case or motivation for changing an existing behavior?
Well, I think that any component using ng-model, should also support ng-change, since
internally it should call `ngModelController.$setViewValue`.

Sure, `md-chips` supplies `md-on-add` and `md-on-remove`, which should suffice, but in my case
I'm using the `ngModelOptions` `getterSetter: true` and the setter, just as ng-change, seems to not be called.

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJs: 1.5.5 (the default one of the CodePen that you supply
Angular Material: 1.1.7

**Comment by Splaktar** [comment]
This is related to https://github.com/angular/material/issues/3857. In both cases, `ng-change` is not supported with `md-chips`. We would be willing to consider a PR from the community that added this support.
