### ISSUE TITLE
select: can't set selected item value after clear

### ISSUE THREAD

**Issue by FlamesoFF** [angular/material#11168]
If set `md-search-text` and `md-selected-item` parameters to `undefined`, in accordance with your documentation, and then instantly set `md-selected-item` to some value - then at first nothing will happen, and at second if will set as expected, but then it will disappear again and so on.

Example: https://codepen.io/FlamesoFF/pen/OvXxNe?editors=0010

How to reproduce: At first press "clear" and then press "set value" several times.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

**Comment by FlamesoFF** [comment]
@Splaktar fuck you
