### ISSUE TITLE
feat(layout): add support for responsive breakpoints with layout-fill, layout-margin, etc.

### ISSUE THREAD

**Issue by free-easy** [angular/material#11175]
### Bug, feature request, or proposal
It would be nice to have `layout-fill-gt-sm`, `layout-margin-gt-xs`, etc.

### What is the use-case or motivation for changing an existing behavior?
Sometime I would like to use layout-fill only for mobile.

**Comment by Splaktar** [comment]
I just wanted to mention that enhancements like this cause AngularJS Material's CSS size to expand significantly. It's already at a point now where it's unacceptably large. 

So we are not willing to take PRs that add features to the layout system at the expense of increasing the unminified CSS size by more than a few KBs. In some cases, we've seen features like this increase the CSS size by 20-80 KBs.

**Comment by free-easy** [comment]
Huh, I wasn't aware of this.
This feature is not so important for me, it was just something to have for convenience.
Since it might introduce such a bloat, then feel free to close it.

**Comment by Splaktar** [comment]
OK, thank you for the feedback. You are of course free to add the classes and mixins to support this to your own app's styles. Looking at our `layouts.scss` should give you a good idea on how to do this.
