### ISSUE TITLE
Typescript newPanelGroup not defined

### ISSUE THREAD

**Issue by waratah** [angular/material#11170]
The following code fails to compile under typescript as the newPanelGroup is not defined. 

```javascript
$mdPanel.newPanelGroup('mouseOver', {
            maxOpen: 3
          });
```

**newPanelGroup should appear in @types.**
  (Needs to be validated by expert!)

```typescript
interface IPanelMaxOpenConfig {
maxOpen: number;
}

interface IPanelGroup {
      panels: IPanelRef[],
      openPanels: IPanelRef[],
      maxOpen: number;
    };

interface IPanelService {
...
newPanelGroup(groupName : string , config?: IPanelMaxOpenConfig): IPanelGroup;

interface IPanelConfig {
....
 groupName?: (string|Array<string>);
}
```
**Work around:**
````typescript
interface IPanelMaxOpenConfig {
    maxOpen: number;
}
    
interface IPanelGroup {
    panels: angular.material.IPanelRef[],
    openPanels: angular.material.IPanelRef[],
    maxOpen: number;
}
    
interface myPanelService extends  angular.material.IPanelService {
    newPanelGroup(groupName : string , config?: IPanelMaxOpenConfig): IPanelGroup;
    setGroupMaxOpen(groupName: string, maxOpen: number): boolean;
}

export class TeacherBookingMouseService {
    static $inject = ['$mdPanel'];
    constructor(private $mdPanel: myPanelService) {
        $mdPanel.newPanelGroup('mouseOver', {
            maxOpen: 3
          });
    }

interface myPanelConfig extends angular.material.IPanelConfig {
    groupName: (string|Array<string>);
}
```

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. This gives the team the information needed to investigate the bug or prioritize the feature.

### Which versions of AngularJS, Material, OS, and browsers are affected?
### Do you have any kind of demo repository?

Are you using the types from https://www.npmjs.com/package/@types/angular-material?
Issues with those types (and PRs to fix them), should be submitted [here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+angular+material).

The AngularJS Material team does not officially support any TypeScript types for the project at this time (though it would be nice to do someday... however, we're focused on many critical a11y issues atm).

**Comment by waratah** [comment]
"@types/angular-material": "^1.1.58",
"angular-material": "^1.1.7",

This is a compile time issue. 
- compile time - angular js is no relevant . 1.6 for the record
- Browser is not relevant. chrome but it never get there.
- Operating system is not relevant.  Windows or Mac.  

Demo repository is not appropriate as it would not compile.  Work around is specified and would be a good starting point for the change.

It would appear that the type are defined in the project not in definively typed as indicated.  note the github reference.

from the top of @Types:

  // Type definitions for angular-material 1.1
  // Project: https://github.com/angular/material
  // Definitions by: Blake Bigelow <https://github.com/blbigelow>, Peter Hajdu 
  <https://github.com/PeterHajdu>, Davide Donadello <https://github.com/Dona278>, Geert Jansen 
  <https://github.com/geertjansen>, Edward Knowles <https://github.com/eknowles>
  // Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
  // TypeScript Version: 2.3

**Comment by Splaktar** [comment]
As indicated by the types information that you provided and the link that I previously gave, these type definitions come from DefinitelyTyped. So please open an issue there and thank @eknowles and team for their support!
