### ISSUE TITLE
MdDialog not opening on iOS Safari 

### ISSUE THREAD

**Issue by insanehong** [angular/material#11183]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
The dialog should Open

### What is the current behavior?
The dialog doesn't open and stop progress when reopen dialog
https://material.angular.io/components/dialog/examples had same problem now.

##### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which shows your issue: 

https://stackblitz.com/angular/pxglmmxpyejr?file=app%2Fdialog-overview-example.ts

##### Detailed Reproduction Steps: 

on Safari or Chrome with iOS

Step1. click Pick one button  
Step2 . close dialog
Step3. click Pick one button  

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular: 5.2.7
- Material: 5.2.4
- OS: iOS 10.3
-  Browser: Safari and Chrome

**Comment by jagabs** [comment]
also experiencing this issue

**Comment by Splaktar** [comment]
@jagabs Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
