### ISSUE TITLE
Meta issue: CodePen template from issue template is outdated

### ISSUE THREAD

**Issue by papb** [angular/material#11187]
The issue template (which opens when creating an issue here) contains a link to the [template CodePen](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which is outdated in several aspects:

* The included AngularJS is 1.5.5 (while the most recent is 1.6.9).

* The included Angular Material is 1.1.0 (while the most recent is 1.1.8).

* The comments in HTML and JS sections say `Copyright 2016 Google Inc` (instead of 2018). There is also a typo in there: `[...] that can be in foundin the LICENSE [...]` where `in foundin` should be replaced with `found in`.

**Comment by Splaktar** [comment]
Excellent timing! I actually just got access to the Angular Material team CodePen today. So I am finally able to start updating things there.

**Comment by Splaktar** [comment]
Fixed all of those, thanks for the detailed report!

I found one that you missed though ;) https://material.angularjs.org/license isn't a valid URL, updated to https://material.angularjs.org/latest/license.

**Comment by Splaktar** [comment]
It should be all set now. Hopefully I can find time later to update more of the CodePen examples to the latest.

For now I'm going to update the [Blank CodePen](https://codepen.io/team/AngularMaterial/pen/RrbXyW) from https://material.angularjs.org/latest/getting-started as well.

**Comment by papb** [comment]
That was fast! Nice! :grin:

It seems though that the "double in" is still there: `in found in` should be simply `found in`.

**Comment by Splaktar** [comment]
Oh yes, good catch, updated! Thank you.
