### ISSUE TITLE
dialog: fails silently when resolve has invalid import and errorOnUnhandledRejections is disabled

### ISSUE THREAD

**Issue by codymikol** [angular/material#11181]
### Bug, feature request, or proposal:

Bug

### What is the expected behavior?

If a dialog has a resolve property set that doesn't exist for some reason, an error should be thrown letting the user know what has gone wrong.

### What is the current behavior?

The dialog silently fails and creates a queue of unresolved dialogs that cannot be resolved.

##### [CodePen Demo](https://codepen.io/anon/pen/ZxKKPg?editors=1111) which shows your issue:

https://codepen.io/anon/pen/ZxKKPg?editors=1111
 
##### Detailed Reproduction Steps: 

Press the button and the dialog will fail silently. You can remove the resolve and it will work fine.

### What is the use-case or motivation for changing an existing behavior?

I drove myself crazy trying to figure out why nothing was working and it turned out to be a typo.

### Which versions of AngularJS, Material, OS, and browsers are affected?

1.1.8

### Is there anything else we should know? Stack Traces, Screenshots, etc.

Nope

**Comment by Splaktar** [comment]
Using AngularJS 1.6.0, you should see a short error like this:
```
Possibly unhandled rejection: {}
```

Using AngularJS 1.6.1+, you should see something like this:
```
console_runner-ce3034e6bde3912cc25f83cccb7caa2b0f976196f2f2d52303a462c826d54a73.js:1 Error: [$injector:unpr] Unknown provider: testProvider <- test
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=testProvider%20%3C-%20test
    at angular.js:116
    at angular.js:4887
    at Object.getService [as get] (angular.js:5047)
    at angular.js:4892
    at getService (angular.js:5047)
    at injectionArgs (angular.js:5072)
    at Object.invoke (angular.js:5098)
    at angular-material.min.js:7
    at Object.forEach (angular.js:422)
    at o._compileTemplate (angular-material.min.js:7) "Possibly unhandled rejection: {}"
```
Updated the [CodePen demo](https://codepen.io/Splaktar/pen/zWdVzO?editors=1010) with this version.

The docs do vaguely mention this in the [bottom-sheet docs](https://material.angularjs.org/latest/api/service/$mdBottomSheet#mdbottomsheet-show-options). We should probably improve those docs and then include them on the [dialog docs](https://material.angularjs.org/latest/api/service/$mdDialog) as well.

**Comment by codymikol** [comment]
It looks like there is an interesting edge case where I have the errorOnUnhandledRejections flag set to false. It would be fine if the error were returned in the catch, but that is not the case. See my updated demo.

https://codepen.io/anon/pen/aYLZVz?editors=1010

**Comment by Splaktar** [comment]
OK, that would certainly hide those promise rejection errors... if you want to add an exception for this case, then I would be happy to take a look and test it out.

**Comment by codymikol** [comment]
Should the errors come back in the catch on the dialog promise?

**Comment by Splaktar** [comment]
I think so, since any kind of rejection of the Promise will be ignored with `errorOnUnhandledRejections` set to `false` right?

**Comment by codymikol** [comment]
I'm closing this as I know better understand this is just a quirk of errorOnUnhandledRejections and is more related to angularJS itself. All thrown errors inside promises are ignored when this is set to false.
