### ISSUE TITLE
docs($mdGesture): add documentation for $mdGesture

### ISSUE THREAD

**Issue by free-easy** [angular/material#11196]
### Bug, feature request, or proposal:
Since #1546 was closed, I'm opening this issue.
It would be really nice to have the usage of $mdGesture documented.
I'm thinking to use $mdGesture to improve the mobile user-friendliness of my app, but looking around I didn't find any documentation about it.

**Comment by Splaktar** [comment]
https://github.com/angular/material/pull/11197 posted. The docs are still pretty minimal, but hopefully helpful. I would welcome someone making a PR to add more detail to the docs.

**Comment by free-easy** [comment]
Thanks. If I have time to delve more into $mdGesture I'll gladly make pull requests.
