### ISSUE TITLE
"Popover" support?

### ISSUE THREAD

**Issue by stevenh77** [angular/material#1120]
Any plans to support popovers or do you recommend using bootstrap?

http://getbootstrap.com/javascript/#popovers-examples

**Comment by ThomasBurleson** [comment]
Currently Material Design does not seem to have PopOvers (rich tooltip content with directional indicators) as a consideration; the [Tooltip specification](http://www.google.com/design/spec/components/tooltips.html#) explicitly excludes such features.

You want to use our mdTooltip approach, implement a mdPopup component, and submit a PR that would be wonderful. 

> Meanwhile I will put this component in our roadmap for consideration; at least for desktop applications this is an often used feature.
