### ISSUE TITLE
autocomplete(chips): deleting chips breaks ability to add or render new chips

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11218]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
Deleting chips should not break the ability to add or render other chips.

### What is the current behavior?
We support multi value with separator comma, enter, space and tab.
It works good as long as we don't delete any chip. As soon as we delete the chip, nothing works. 
We made sure model looks good even after deleting but somehow `md-item-template` doesn't get rendered.

##### CodePen Demo which shows your issue: TBD
```html
<md-chips
      flex="100"
      md-autocomplete-snap
      class="..."
      readonly="..."
      ng-model="..."
      ng-if="..."
      md-transform-chip="..."
      md-on-remove="...">
</md-chips>
```
### What is the use-case or motivation for changing an existing behavior?
It worked as expected in 1.1.7.

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS Material 1.1.7
Others TBD

### Is there anything else we should know? Stack Traces, Screenshots, etc.
Verified that this is fixed by reverting https://github.com/angular/material/pull/11166 in https://github.com/angular/material/pull/11214.

**Comment by Splaktar** [comment]
@jelbourn the issue mentions `md-item-template`, but I assume that it means `md-chip-template`?
Do you have any details on what that template looks like?

It also appears that the custom logic within the `md-transform-chip` and `md-on-remove` expressions could be causing the problem here.

I tested this on the [1.1.8 docs](https://material.angularjs.org/latest/demo/chips) and I cannot reproduce any problems related to deleting and adding more chips.

**Comment by Splaktar** [comment]
@jelbourn Here is a [Demo](https://codepen.io/Splaktar/pen/oqmNdr?editors=1010) where `md-on-remove` can cause `md-transform-chip` to start returning `null` and blocking chip creation. Is this what is happening? Is this behavior (chip being removed when it should be added) what the team is seeing?

**Comment by hetal0713** [comment]
Hi Splaktar,

@jelbourn reported issue on behalf of me. See my comments below

@jelbourn the issue mentions md-item-template, but I assume that it means md-chip-template?
Do you have any details on what that template looks like?
>> yes its chip template. Below is template (some info changed from original template)

<md-chip-template
        username-chip
        class="xyz"
        ng-class="{'invalidTag': $chip.invalid}">
      <span>
         {{$chip.name}}
      </span>
      <md-tooltip>
        {{$chip.name}}
        <span ng-if="$chip.xyz">({{$chip.xyz}})</span>
        <span ng-if="$chip.abc">({{$chip.abc}})</span>
      </md-tooltip>
    </md-chip-template>

@jelbourn Here is a Demo where md-on-remove can cause md-transform-chip to start returning null and blocking chip creation. Is this what is happening? Is this behavior (chip being removed when it should be added) what the team is seeing?
>> Yes we are seeing issue on chip removal. As soon as we remove the chip, it starts creating new chips. I wasn't able to add chips in the demo link you gave. if i enter "abc xyz" and press tab.. it doesn't create chips. It doesn't even create for single ouptut.

**Comment by hetal0713** [comment]
Sorry code from earlier comment was not in code tag.. here it is `<md-chip-template
        username-chip
        class="chip-xyz"
        ng-class="{'invalidTag': $chip.invalid}">
      <span>
        
        {{$chip.name}}
      </span>
      <md-tooltip>
        {{$chip.name}}
        <span ng-if="$chip.abc">({{$chip.abc}})</span>
        <span ng-if="$chip.xyz">({{$chip.xyz}})</span>
      </md-tooltip>
    </md-chip-template>`

**Comment by Splaktar** [comment]
@hetal0713 I posted two demos. I assume that you weren't able to create chips when using the [Broken Demo](https://codepen.io/Splaktar/pen/oqmNdr?editors=1010)? That would be expected.

If you look at the code for this demo, you can see how the `onRemove` function is changing some state that causes the `transformChip` function to return null. Is something like this possible in your code? If so, do you have more details or can you fix it in your custom code?

**Comment by Splaktar** [comment]
@hetal0713 If you remove `md-transform-chip` is it still possible to reproduce the bug in your app?

We don't yet have enough information to reproduce a bug here. All indications so far are that this is due to a bug in application code and not AngularJS Material. 

If there is still a feeling that this is an AngularJS Material bug, then we need more information in order to reproduce it. An updated CodePen demo would be idea, but if that can't be provided, then it would be especially helpful to understand what expressions are related to `md-on-remove` and `md-transform-chip`.

**Comment by hetal0713** [comment]
Hi Splaktar,

I no longer can reproduce the issue after syncing with latest version of angular material. Just for the reference, here is the md-transform-chip function

createChip(input) {
    const tmpUrls = input.split(' ');
    for (const url of tmpUrls) {
      this.addUrl_(url);
    }
    return null;
  }

**Comment by Splaktar** [comment]
Right, it would not be reproducible after the latest sync because the changes that triggered this were backed out. However, we are planning to put those changes back in. We just need to identify and reproduce the issue so that we don't break your app when we put the changes back in.

It looks like your `md-transform-chip` function is always returning `null`? Based on [the md-chips docs](https://material.angularjs.org/latest/api/directive/mdChips) returning null indicates "to prevent the chip from being appended".

`md-transform-chip` | `expression` | An expression of form `myFunction($chip)` that when called expects one of the following return values:
* an `object` representing the $chip input string
* `undefined` to simply add the $chip input string, or 
* `null` to prevent the chip from being appended

Hopefully this helps you diagnose the problem. Please let me know if you have any questions. 

I'll post a PR soon to bring these changes from PR https://github.com/angular/material/pull/11166 back into `master`.

**Comment by hetal0713** [comment]
Since changes are backed out from the head version, i dont know how to reproduce it. Can you engage us when this changes back in git and google3 so we can retest it?

**Comment by Splaktar** [comment]
OK, I've opened PR https://github.com/angular/material/pull/11237 to put this functionality back in.

**Comment by Splaktar** [comment]
@hetal0713 OK, these changes are back in `master` via PR https://github.com/angular/material/pull/11237 which was merged today. It looks like the `g3_v0_x` branch might be a few commits behind this, but I'm not 100% sure if Google is syncing with that or with `master`.

**Comment by hetal0713** [comment]
Thanks Michael. Jeremy, when will these changes be available in Google3?

Hetal

**Comment by mmalerba** [comment]
@hetal0713 I'll sync the changes today

**Comment by hetal0713** [comment]
+ my eng team.

**Comment by mmalerba** [comment]
@hetal0713 changes have been synced to g3

**Comment by hetal0713** [comment]
Thank you. We will test it out.

**Comment by hetal0713** [comment]
This has again broken our code.
Here is the [demo](https://codepen.io/hetalpatel/pen/MGKGPB?editors=1111). Basically we want a simple md-chips (for now lets just say without even autocomplete) which accepts input with seperator keys and creates chips based on keys. In the demo i tried with md-seperator-keys and also with md-transform-chip function to break the chips myself. None of the approach works.

Seperator keys doesnt work at all and md-transform-chip works as long as i don't delete chip. Once i delete the chip, it stops working.

**Comment by hetal0713** [comment]
Also for transform function, if i try to return chip object, it creates extra chip. i.e. veg1 veg2 should create only two chips but it creates three veg1 veg2 and "veg1 veg2".

If i return null, it works fine until i delete any chips. Once i delete the chip, it stops working.

**Comment by hetal0713** [comment]
Thanks Splaktar, Let us know if you need anything else from us.

**Comment by hetal0713** [comment]
Thanks Michael!! I tried it and it still doesn't work. I updated the demo
<https://codepen.io/hetalpatel/pen/MGKGPB> with what you suggested. It
works for first time but doesn't work as soon as i delete one chip.
I tried "abc xyz" as input

**Comment by hetal0713** [comment]
+disco-eng <disco-eng@google.com>

**Comment by Splaktar** [comment]
@hetal0713 Oh wow, sorry, I forgot to add the link to the fixed CodePen that I created: https://codepen.io/Splaktar/pen/mLPgBb.

In both of our CodePens, I am able to add "abc xyz" and press space/comma/semicolon to see both chips added. Then delete both chips. Paste "abc xyz" again and press space/comma/semicolon and again I see both chips added properly. 

Do these steps not match up with what you are doing? Did I miss something?

**Comment by hetal0713** [comment]
Then delete both chips.
>> Just delete one chip and try pasting the same string again.

Exact steps.

   - Paste "abc xyz"
   - it should create two chips abc xyz
   - remove xyz
   - paste "abc xyz" again
   - it should create "xyz" chip again

**Comment by hetal0713** [comment]
+disco-eng <disco-eng@google.com>

**Comment by Splaktar** [comment]
@hetal0713 unfortunately that's another side effect of using `md-transform-chip` in a way that it wasn't designed for. In this case, we're using the MdChipCtrl's `items` array to update the view model, but since this workaround avoids updating the `items` array and modifies the chipBuffer  directly (via the ng-model), things get out of sync.

I've added the following code to the [CodePen Demo](https://codepen.io/Splaktar/pen/mLPgBb?editors=1010) to force the view model to update and get things back in sync:
```js
      // We're missing out on MdChipsCtrl.updateNgModel()'s setting of the model's view value
      // (and chipBuffer) based on the MdChipsCtrl's items array. So we have to manually force
      // the ng-model's view value to update MdChipCtrl's chipBuffer here to keep in sync.
      self.selectedVegetables = self.selectedVegetables.slice(0);
```
By cloning the `selectedVegetables` array here, we're forcing its reference to change so that change detection is triggered. There are likely alternative ways of accomplishing this as well.

**Comment by hetal0713** [comment]
Hi Michael, looks like you have backed out the code on 4/24 and now i can't
apply this fix in our code to see if it works. Is it possible to put the
changes back in?

**Comment by mmalerba** [comment]
@hetal0713 are you working in g3? why not just sync to the CL that brought this into g3 and add your changes on top of that?

**Comment by Splaktar** [comment]
@hetal0713 AngularJS Material actually hasn't backed out the change that caused this. We just released 1.1.9 with that change included.

It looks like the `g3_v0_x` sync branch is based on a commit from 4/10. @josephperrott is there a need to sync g3 now?

**Comment by hetal0713** [comment]
I was able to sync to CL which introduced this bug in our code. I applied
your fix which fixed issue in one page but in other page it is still an
issue. It is due to the fact that we are using inter-component
communication using bindings. See here
<https://screenshot.googleplex.com/sjJYyK9f8Kw>.
We have a component1 where component2 is used as directive and we bind the
model from component1 to component2 using ngbinding. After applying the
fix, md-chips are working fine but component 1 doesn't receive the model
values as reference of that is changed using cloning.

Here is the code for component1
<https://cs.corp.google.com/piper///depot/google3/corp/legal/discovery/dots/frontend/components/add-holds/add-holds.html?l=23>
.
Here is the code for component2
<https://cs.corp.google.com/piper///depot/google3/corp/legal/discovery/dots/frontend/components/username-autocomplete/username-autocomplete.js?l=191>
.

Since latest changes are backed out from angular branch, we will go ahead
with our deployment. Please let us know before this changes are put back in
so our Legal users are not impacted.
Hetal

**Comment by Splaktar** [comment]
Please note that as part of the fix that introduced this problem for you, we have enabled the use of AngularJS' `ng-change`. This can be used to trigger synchronization between components as you describe above. However, as I can't see your internal code, I can't judge whether that is the right solution or not.

**Comment by Splaktar** [comment]
I just posted PR https://github.com/angular/material/pull/11310 which may possibly help with this. We'll probably want to re-test this against the internal app once that PR gets merged into `master`.

**Comment by Splaktar** [comment]
It looks like this is solved with https://github.com/angular/material/pull/11310#issuecomment-395595523.
