### ISSUE TITLE
Angular Material Datepicker not working! Other material components working fine.

### ISSUE THREAD

**Issue by sriharigr** [angular/material#11213]
### Bug, feature request, or proposal:
I have tried all that I know, I don't know if its a bug. I am new to JS, Angular..

### What is the expected behavior?

Normal functioning of mat-datepicker. All other components of Material library is working as expected. Even the ones with animations.

### What is the current behavior?

Only a input box. nothing else.

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular CLI: 1.7.2
Node: 9.4.0
OS: linux x64
Latest versions of Chrome and Firefox

**package.json**

"dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.4",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "material-design-icons": "^3.0.1",
    "ngx-tooltip": "0.0.9",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.2",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "font-awesome": "^4.7.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
**app.module.ts**

import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BrowserModule } from 	'@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MatNativeDateModule} from '@angular/material';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatDatepickerModule} from '@angular/material/datepicker';
import {MatProgressSpinnerModule} from '@angular/material/progress-spinner';
import {MatSelectModule} from '@angular/material/select';

import { HttpModule } from '@angular/http';
import {TooltipModule} from "ngx-tooltip";
import { AppRoutingModule } from './app-routing.module';
import { HttpClientModule } from '@angular/common/http';

import { AppComponent } from './app.component';

import 'hammerjs';

@NgModule({
  declarations: [
    AppComponent,

  ],
  imports: [
    FormsModule,
    HttpModule,
    TooltipModule,
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    MatNativeDateModule,
    MatDatepickerModule,
    MatProgressSpinnerModule,
    MatSelectModule,
    MatFormFieldModule

  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

**app.component.html**
 <input  [matDatepicker]="picker" placeholder="Choose a date">
   <mat-datepicker #picker>
</mat-datepicker>

### Is there anything else we should know? Stack Traces, Screenshots, etc.
 

![matdatepicker](https://user-images.githubusercontent.com/37204574/38416685-2a560ec2-39b3-11e8-985f-dc180b5e319a.png)

**Comment by sriharigr** [comment]
I solved this by adding the "<mat-datepicker-toggle [for]="myDatepicker"></mat-datepicker-toggle>" element. But the docs says its optional. I wasted the whole days doing so many things.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
