### ISSUE TITLE
chips: adding chip on blur no longer working when required is also used

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11217]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
Clicking outside of the chips with input in the chips should create a new chip.
Adding chips and removing chips and adding more chips should work.

### What is the current behavior?
We have multi value supported with separator keys of enter, space and tab. 
It works good when we have input like (url1 url2) and hit tab to move out of the field
It doesn't transform into chips when we have input like (url1 url2) and click anywhere outside of the field (this used to work before this sync)
After adding chips, if we remove the chips and retry with any input, it doesn't work. Somehow it makes the model as "undefined"

### What is the use-case or motivation for changing an existing behavior?
It used to work in 1.1.7.

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS Material 1.1.7
Others TBD

### Is there anything else we should know? Stack Traces, Screenshots, etc.
Verified that this is fixed by reverting https://github.com/angular/material/pull/11125 in https://github.com/angular/material/pull/11215.

**Comment by Splaktar** [comment]
@jelbourn can you confirm that they have `md-add-on-blur="true"` on the `md-chips`?
Are they using `ng-required`?

**Comment by IMM0rtalis** [comment]
I‘ll try to find a fix/solution the next 48hours

**Comment by Splaktar** [comment]
@jelbourn It seems like the custom logic in the `md-transform-chip` expression may be causing this issue. If it starts returning `null`, this will block chips from being created.

**Comment by Splaktar** [comment]
I tested on the [docs for HEAD](https://material.angularjs.org/HEAD/demo/chips) and I could not reproduce these issues there. But those docs don't have an example of using `md-add-on-blur` with `required`.

So I created a [demo](https://codepen.io/Splaktar/pen/NYoWEv?editors=1010#0) that uses `md-add-on-blur` with `required` and there does appear to be an issue. Add on blur does not work for the first chip either with the tab key or a mouse click.

**Comment by Splaktar** [comment]
@hetal0713 we were able to isolate and reproduce this issue. We're working on a test and a fix atm. In the meantime, the code that caused this has been reverted from `master`.

**Comment by hetal0713** [comment]
Ok great. Thank you for the update

**Comment by Splaktar** [comment]
@IMM0rtalis Google doesn't use any version tag of AngularJS Material. They are based on `HEAD`. That's why it's critical that we do thorough code reviews and add tests for bugs and new features. This is also why some people's requests to "just merge my PR and clean it up yourself afterwards" cannot be accomodated.

Yes, please make a new PR targeted at `master` that includes the changes from your previous PR, plus a test that reproduces this failure, and a fix that makes that test pass.

We don't yet have a reproduction for the issue with autocomplete and the `ng-change` changes, so for now, I would avoid including those changes into your branch (I know that they weren't your original changes).

**Comment by Splaktar** [comment]
@IMM0rtalis any progress on this? I am going to work on writing a test that reproduces the problem.

**Comment by Splaktar** [comment]
Verified that both `required` and `ng-required="true"` cause this failure. 

This test reproduces the issue:
```javascript
it('should allow adding the first chip on blur when required exists', function() {
  scope.items = [];
  var template =
      '<form name="form">' +
      ' <md-chips name="chips" ng-required="true" ng-model="items" md-add-on-blur="true"></md-chips>' +
      '</form>';

  var element = buildChips(template);
  var ctrl = element.find('md-chips').controller('mdChips');

  element.scope().$apply(function() {
    ctrl.chipBuffer = 'Test';
  });
  element.find('input').triggerHandler('blur');

  expect(scope.form.chips.$error['required']).toBeUndefined();
  expect(scope.items).toEqual(['Test']);
});
```

**Comment by Splaktar** [comment]
Opened PR https://github.com/angular/material/pull/11225 to add this functionality back in and fix the regression.

**Comment by IMM0rtalis** [comment]
Started yesterday before going home; will look into yours when i am at work in 2-3h

**Comment by IMM0rtalis** [comment]
Yesterday we just found out that we were also affected by this blur-problem :see_no_evil:  

Is there a date-guess for releasing 1.1.10 ? - Any feedback of google-teams regarding the problem (is it fixed for them?) @Splaktar

**Comment by Splaktar** [comment]
This should be in 1.1.9. I am planning to start moving issues and getting prepared for a 1.1.9 release tomorrow. I expect that to take a few days, with a release next week.
