### ISSUE TITLE
select: causes backdrop and extra scrollbar on IE

### ISSUE THREAD

**Issue by hseleiro** [angular/material#11227]
### Bug, feature request, or proposal:

Bug

### What is the expected behavior?

The expected behavior is the select box to open without overlay everything 

### What is the current behavior?

When the select box opens, a gray background appear and the box overlay everything and creates a scroll. I notice it creates a position fixed in the body and a width of 100%.

## CodePen and steps to reproduce the issue:

I don't have a codepen example , but your website if open on IE11 reproduces the same issue when we try to open the select box, i will leave a screenshot

![untitled](https://user-images.githubusercontent.com/16728226/38628627-bdeb57a6-3da9-11e8-8356-1afe00b5b7fa.jpg)

https://material.angularjs.org/latest/demo/select , when it opens on IE11 it got the wrong behavior 

### Which versions of AngularJS, Material, OS, and browsers are affected?

IE11, angular-material": "^1.1.6",

### Is there anything else we should know? Stack Traces, Screenshots, etc.
This is a screenshot of my page when i open the selectbox to choose an option, the background is filled whit a color and the select box is all deformed.

![_ie11](https://user-images.githubusercontent.com/16728226/38627065-f5b691ae-3da5-11e8-9e88-edf40266d174.jpg)

Thank you !

**Comment by Splaktar** [comment]
This appears to be caused by `-ms-overflow-y: scroll;` being applied to the `html` element when `md-select` is open.

This is set in [disableBodyScroll()](https://github.com/angular/material/blob/v1.1.10/src/core/util/util.js#L277-L322).

**Comment by Splaktar** [comment]
There is an incredibly long history behind this, but https://github.com/angular/material/commit/ddfe5230bbc9d06a2439da9dbfef8feee2a6f572 is the commit back in 0.10.1 that changed this from `overflow-y: hidden` to `overflow-y: scroll`.
