### ISSUE TITLE
Material 1.1.8 will not load in AngularJS 1.2.20

### ISSUE THREAD

**Issue by BamiGorengo** [angular/material#11223]
### Bug, feature request, or proposal:
Bug

### Which versions of AngularJS, Material, OS, and browsers are affected?
AngularJS 1.2.20
Angular Material 1.1.8

### Is there anything else we should know? Stack Traces, Screenshots, etc.
More informations here: https://stackoverflow.com/questions/49750126/how-to-angular-material-with-angular-1-2-20

I Think the problem is that Angular Material is not Compatible with AngularJS 1.2.20. Is this correct? of i just do something wrong?

**Comment by codymikol** [comment]
Looking at that SO you need to load angular material before you're own controllers / modules in your index.html.

**Comment by BamiGorengo** [comment]
But is the Version compatible with Angular 1.2.20? Because i tryed to load it before allready but still got same error...

**Comment by Splaktar** [comment]
As indicated in [bower.json](https://github.com/angular/bower-material/blob/master/bower.json) and [package.json](https://github.com/angular/bower-material/blob/master/package.json) AngularJS 1.4 is the oldest version that we support with our latest releases. We'll be moving to 1.5 soon. 

I highly recommend upgrading to the latest AngularJS 1.6 as 1.7 is coming out this summer and will include LTS. You'll want your active projects to be on the LTS moving forward as critical fixes and security patches will only be applied to AngularJS 1.7.x.
