### ISSUE TITLE
md-slider events aren't propagated

### ISSUE THREAD

**Issue by corzar71** [angular/material#11236]
### Proposal:
Propagate $md.XXX events of md-slider

### What is the expected behavior?
It should be possible to be notified when the $md.XXX events are emitted

### What is the current behavior?
In the md-slider component there are some events managed internally:

**'keydown', 'mousedown', 'focus', 'blur', '$md.pressdown', '$md.pressup', '$md.dragstart', '$md.drag', '$md.dragend'**

In particular the **$md.xxx** ones are interesting to be used for personal customization.
The problem is that I can't have awareness of the dragging event because the **onDrag** function, bound to the _$md.drag_ event, stops the propagation of the event. Only _$md.pressdown_ and _$md.pressup_ are propagated.
Is it possible to remove the **ev.stopPropagation();** statement in all such events in order to propagate all of them?

### What is the use-case or motivation for changing an existing behavior?
I want to change the class while dragging if some values aren't allowed (graying out the denied values in the thumb).

### Which versions of AngularJS, Material, OS, and browsers are affected?
I'm using angular material v1.1.5

**Comment by Splaktar** [comment]
This proposal seems to be asking for functionality that is outside of the Material Design spec. It may be best to build your own custom slider component if you need to support features like disable certain values. In some cases, it is possible to use a directive to modify the behavior of a component like `md-slider`, however I am not sure that will be sufficient in this case.

I am going to close this as it seems to be outside of the spec and something that does not make sense in the AngularJS Material core. Additionally, the priority on a request like this would be so low that it is unlikely to ever be looked at. I would rather let you get started working on your own custom component than keep you waiting in the hopes that we can support this special case.
