### ISSUE TITLE
feat(slider): add option to hide thumbLabel when a drag ends

### ISSUE THREAD

**Issue by fttriquet** [angular/material#11232]
### Bug, feature request, or proposal:
Proposal

### What is the expected behavior?
Material slider ThumbLabel should have more options

### What is the current behavior?
ThumbLabel can only be displayed or not

### What is the use-case or motivation for changing an existing behavior?
right now the only possibility with the thumbLabel is to display it, and the only way to hide it after moving it is to click somewhere else, it should be possible to hide it when the modification is done.

### Which versions of AngularJS, Material, OS, and browsers are affected?
All

**Comment by Splaktar** [comment]
Are you talking about a discrete slider or continuous slider in this proposal? I am going to assume discrete.

https://material.io/guidelines/components/sliders.html#sliders-discrete-slider demonstrates how the thumbLabel should behave on click & drag. In this instance, [our discrete slider](https://material.angularjs.org/HEAD/demo/slider) currently follows the Material Design spec. There are specific usability and accessibility factors that went into this behavior.

We have no plans to make this behavior, that does not align with the Material Design spec, part of the AngularJS Material core. However, you may be able to create a directive that allows you to modify the component's behavior to meet your requirements.
