### ISSUE TITLE
Mat-typography doesn’t work when I build my angular app

### ISSUE THREAD

**Issue by LeonardoGastonRossi** [angular/material#11239]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
The app should show the proper font family and font sizes.

### What is the current behavior?
The font family and font sizes don't match with my configuration in mat-typography-config:

$raam-typography: mat-typography-config(
$font-family: 'Open Sans',
$headline: mat-typography-level(24px, 1.33, 400),
$body-1: mat-typography-level(16px, 24px, 500),
$button: mat-typography-level(16px, 1.0, 600)
);
@include angular-material-typography($raam-typography);

It's showing the default mat-typography-configuration for material.

##### Detailed Reproduction Steps: 
- Generate build for some environment (dev, prod).
- Push app in that environment.

### What is the use-case or motivation for changing an existing behavior?
Because mat-typography was working when I generated a build but now It seems it is not working.

### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular CLI: 1.7.4 
Angular: 5.2.10
 Material: 5.1.1

### Is there anything else we should know? Stack Traces, Screenshots, etc.
This starts to happen after updating my package.json and updating angular CLI and Angular version. (material version didn't change).

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
