### ISSUE TITLE
How to change color on selected index change of dropdown inside angular material table

### ISSUE THREAD

**Issue by postmeback** [angular/material#11241]
### Bug, feature request, or proposal:
Bug.

### What is the expected behavior?
It should change the color

### What is the current behavior?
It is not changing.

###Scenario
I have an angular material table, which has 2 dropdown columns. Now, if both columns are selected as NO, then i want to change the selected text color to RED.

###Approach
This is the below html code :-
`<ng-container matColumnDef="Eligible To Vote?"><mat-header-cell *matHeaderCellDef mat-sort-header> Eligible To Vote? </mat-header-cell><mat-cell *matCellDef="let element" ><mat-form-field [class.app-input-no-underline]="true"><mat-select id="eligind" placeholder="Select" (ngModelChange)="EligOnChange($event)"  [(value)]="element?.detail.Elig_Indc"
 [(ngModel)]="element?.detail.Elig_Indc" name="elig-voting" class = "{{styleClass}}">
<mat-option>Select</mat-option><mat-option value="1">Yes</mat-option><mat-option value="0">No</mat-option></mat-select>
</mat-form-field> </mat-cell></ng-container><ng-container matColumnDef="Voting?" >
<mat-header-cell *matHeaderCellDef mat-sort-header> Voting? </mat-header-cell>
<mat-cell *matCellDef="let row; let element" [ngClass]="{'mat-cell-no': element == 0}" >
<mat-form-field [class.app-input-no-underline]="true"><mat-select id="voting" placeholder="Select" (ngModelChange)="VoteOnChange($event)" [(value)]="element?.detail.Voting_Indc " [(ngModel)]="element?.detail.Voting_Indc"  name="voting" class = "{{styleClass}}"><mat-option>Select</mat-option><mat-option value="1" >Yes</mat-option><mat-option value="0" >No</mat-option> </mat-select> </mat-form-field> </mat-cell></ng-container>`

In both the dropdowns the `ngModelChange` is the listener. Below is the respective typescript:

`EligOnChange($event) {
     if ($event !== '0') {
      } else {
        alert('a');
         this.EligibilityToVote = false;
         if (this.IsVoting === false) {
          this.styleClass = 'vote-same-red mat-select-text-value';
        } else { alert('sdgf'); }
      }
 }`

`VoteOnChange($event, element) {
  if ($event !== '0') {
  } else {
    alert('a');
     this.IsVoting = false;
     if (this.EligibilityToVote === false) {
      this.styleClass = 'vote-same-red mat-select-text-value';
    } else { alert('sdgf'); }
  }
}`

And below the CSS
`.vote-same-red .mat-select-text-value {
  color:red !important;
    }`

There are multiple problem i am facing -

1. I am having a hard time to detect the two statuses on **ngModelChange** for multiple value. 
2. The class is not getting reflected, most of the cases the class is getting dynamically generated, so it is not possible to add respective class.

### Is there anything else we should know? Stack Traces, Screenshots, etc.

![dropdownarrow](https://user-images.githubusercontent.com/14862687/38938845-2e64cb1c-4344-11e8-905f-0776233cc09c.png)

When, the last columns selected index is NO, then the color should change....but it is not changing.
### Which versions of AngularJS, Material, OS, and browsers are affected?
Angular 5, Material2, Windows, Chrome (not checked on other)

**Comment by postmeback** [comment]
Please feel free to ask any question...Thanks in advance :)

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
