### ISSUE TITLE
Provide convenient way to download minified files on a per-version basis.

### ISSUE THREAD

**Issue by garretwilson** [angular/material#11243]
### Bug, feature request, or proposal:

I want to be able to download a Zip archive with the minified distributables for a particular version.

### What is the expected behavior?

I click on some link and download a Zip file with the distributables.

### What is the current behavior?

Either:

* I am forced to use npm or Bower, even if my project doesn't use them.
* I have to go to https://material.angularjs.org/latest/ and use curl to get the latest files hosted for the public site, crossing my fingers they have been updated for the latest version. (This only works for the current version.)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial) are a better location for asking questions about the project. Please limit GitHub issues to bug reports.

You can find all of the releases [here](https://github.com/angular/bower-material/releases). This includes a build for every single merge to master in addition to the final release builds. The `1.1.8` release and ZIP file can be found [here](https://github.com/angular/bower-material/releases/tag/v1.1.8).
