### ISSUE TITLE
md-track-ticks should visible always in md-slider

### ISSUE THREAD

**Issue by iyyappan13391** [angular/material#11254]
Team,Need to visible dotted line in md-slider,I tried different kind of ways but it coming from canvas tag.Please help for it.

Ques: Need to show dotted line always in md-slider

**Comment by Splaktar** [comment]
Thank you for your submission. However the suggested modification does not align with the [Material Design spec for Sliders](https://material.io/guidelines/components/sliders.html#sliders-discrete-slider). You may be able to use a directive to modify the behavior of the `md-slider`, but it may also be desirable to write your own custom slider component based on `md-slider`.

**Comment by sree296** [comment]
@iyyappan13391 Did you find any way to achieve this? I also have the same requirement now but not able to achieve this.
Thanks.
