### ISSUE TITLE
Pressing Enter in text box without an item selected submits a parent form

### ISSUE THREAD

**Issue by wozzo** [angular/material#11251]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
Pressing Enter when no item is selected should stop event propagation so no action is taken

### What is the current behavior?
The enter event is propagated to a parent form and submits it

##### Detailed Reproduction Steps: 
[CodePen Demo](https://codepen.io/wozzo/pen/LmGjyo)
Type anything into the text box and press enter. The parent form submits

### What is the use-case or motivation for changing an existing behavior?
Users incorrectly pressing Enter when they haven't selected anything on this element.

### Which versions of AngularJS, Material, OS, and browsers are affected?
All that I've tried

**Comment by Splaktar** [comment]
Please review the [AngularJS Form Docs](https://docs.angularjs.org/api/ng/directive/form). They explain why using `action` on a form is not ideal for a SPA. They also present some alternatives via `ng-submit` and `ng-click`.
