### ISSUE TITLE
Impossible to have nested $mdDialog

### ISSUE THREAD

**Issue by MarcosPortugal** [angular/material#1125]
If I open a custom mdDialog, and then open another one through a button click inside it, it just closes as if the user had clicked outside the dialog. This makes it impossible to have "nested" dialogs, which is a feature I really need to use.

 Can you let me know if this is a bug and if you're planning to make it possible to have more than one dialog open at the same time, or if I should move on and come up with a solution of my own?

 Thanks in advance!

**Comment by marcysutton** [comment]
Sounds like this existing issue, which requests layered dialogs: https://github.com/angular/material/issues/698

Is that similar to your situation?

**Comment by MarcosPortugal** [comment]
Exactly that :) Sorry for forgetting to use search! :+1:

**Comment by marcysutton** [comment]
No worries, thanks for using Angular Material!

**Comment by SalmanZafar214** [comment]
can we get a Fix for this . as i m trying to use dateTime picker in dialog

**Comment by wembernard** [comment]
Would love to see this feature :+1:

**Comment by jpike88** [comment]
Me too, not sure why it's in deprecated considering that I can't fire up a date picker that uses md-dialog from an md-dialog. It's quite limiting.

**Comment by jpike88** [comment]
Nevermind

https://github.com/hayloft/material

That repo has it, works like a charm
