### ISSUE TITLE
mat-icons as a matSuffix or matPrefix in a mat-form-field do not match the material spec

### ISSUE THREAD

**Issue by adamdport** [angular/material#11261]
### Bug, feature request, or proposal:
bug

### What is the expected behavior?
`mat-icon`s used as a `matPrefix` or `matSuffix` should vertically align with the input text/placeholder

### What is the current behavior?
icons are positioned too high

![current](https://user-images.githubusercontent.com/3020987/39326632-a4bd2690-4963-11e8-8ca1-9083e3ed5f2f.PNG)
![currentMarkedUp](https://user-images.githubusercontent.com/3020987/39326773-08c33dd2-4964-11e8-8cfc-edcbf82d771c.PNG)

## CodePen and steps to reproduce the issue:
https://stackblitz.com/edit/angular-material2-issue-jrwkpg

### What is the use-case or motivation for changing an existing behavior?
It doesn't look good

### Which versions of AngularJS, Material, OS, and browsers are affected?
    "@angular/core": "5.2.10",
    "@angular/material": "5.2.5",

### Is there anything else we should know? Stack Traces, Screenshots, etc.
[The specs show that icons should be vertically aligned with the text](https://material.io/guidelines/components/text-fields.html)

![materialspec](https://user-images.githubusercontent.com/3020987/39326577-7b7f80de-4963-11e8-8225-77f84cfe9386.PNG)

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
