### ISSUE TITLE
Sidenav not closing on redirect

### ISSUE THREAD

**Issue by adamelevate** [angular/material#1126]
I'm using the sidenav as a mobile menu, but when I click a link it doesn't close the sidenav on redirect. Am I doing something wrong?

**Comment by marcysutton** [comment]
I actually experienced this same issue...but if you think about it, the child links inside of the menu don't have any knowledge of the menu toggle. To close it at the appropriate time, you can simply call `$mdSidenav.close()` when users click on a link in the menu.

**Comment by ThomasBurleson** [comment]
agreed.

**Comment by ilanbiala** [comment]
@marcysutton this should be made clear on the docs as a note or something like that.

**Comment by rahulrajeevan** [comment]
I too experience the same issue . Below code work for me
 $scope.$on('$stateChangeSuccess', function () {
    $mdSidenav('left').toggle();
 });
