### ISSUE TITLE
datepicker: when using date format as MM/YYYY not able to change ng-model value on keyboard input

### ISSUE THREAD

**Issue by BineetKumar94** [angular/material#11271]
well my requirement is to set up a date which only allows the user to choose month and year and not the exact date. So I changed the format to MM/YYYY in config and also the parseDate function to parse the date on user input through keyboard.

On user input through pop up calendar, the ng-model value is getting updated but that's not the case through keyboard input. 
Did look into the response parseDate function is returning and the response looks perfectly fine. 
cant figure out the exact issue.

find the demo here --> https://codepen.io/anon/pen/GdOZNN?editors=1010

**Comment by Splaktar** [comment]
Please take a look at the solution in https://github.com/angular/material/issues/11292. The same sort of solution is required in this case as well.

This documentation is fixed in https://github.com/angular/material/pull/11296.
