### ISSUE TITLE
layout: Media Query issue when browser zoomed in

### ISSUE THREAD

**Issue by BMartinos** [angular/material#11274]
#### Detailed Reproduction Steps: 
1. Set you chrome browser zoom level to 145% (You need to go to chrome settings, edit the zoom level HTML to add option for 145%). 
2. Open you dev tools to be able to resize the screen. 
3. Resize the screen to 869px / 870px
4. On those resolutions, the media query is not applied and all the boxes are shown.

### What is the expected behavior?
To apply the media query as expected

### What is the current behavior?
At certain browser zoom levels, and certain resolution sizes, the appropriate media queries does not seem to get applied. and multiple elements are visible when they shouldnt be.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.5
- AngularJS Material: 1.1.8
- OS: Linux Ubuntu 16.04
- Browsers: Chrome Version 65.0.3325.181
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
![yrpnoz](https://user-images.githubusercontent.com/7311421/39808910-948948ae-5380-11e8-8420-88e94d1108f9.gif)

**Comment by Splaktar** [comment]
Can you please test with 1.1.9? We did fix some layout issues in that release.

**Comment by Splaktar** [comment]
No response to my request to test on a recent version of the library.
