### ISSUE TITLE
Site not working in safari..

### ISSUE THREAD

**Issue by Shany1992** [angular/material#11275]
I am facing issues at the time of open site in safari browser.
Currently i am using -  
angular 5.
angular material theme.
page not load -- 
Getting Error - ReferenceError: Can't find variable: EventTarget

![image](https://user-images.githubusercontent.com/26872557/39908236-c4e98e6a-550a-11e8-8725-1d100d80d388.png)

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
