### ISSUE TITLE
Central listing of CSS classes available with angular material components

### ISSUE THREAD

**Issue by trazek** [angular/material#1127]
Is there a listing or documentation of all the css classes available to us? As of now, I look through the demo source and actual CSS files to see what is available.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:45374 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (UNKNOWN:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.82)
	(envelope-from <noreply@github.com>)
	id 1Y8c8j-000Cqs-VM
	for greg@biomassiv.es; Tue, 06 Jan 2015 15:58:15 -0600
Date: Tue, 06 Jan 2015 13:58:14 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1420581494;
	bh=xC7LpHD6/ZWZnqKydYF5Y1NnNdS2Su7RkQp1YQYV3Lo=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=jbxrRJZ8vxtmoTRX2ee/FWqC23QCBrbsAJLyHkwhV2DF8BwaYn7KnCb9GU8vYi2GT
	 +0lReJ56/4KO69qLpnWyyrdaocO3qzrLc8O6WXh52tkwn8Ky1iVdJhjrLkldY4eqPa
	 TMFibgf3OSp7t6qGy1NbK1lKmaZJMNpvYhTA07zQ=

**Comment by epelc** [comment]
+1 I also end up looking through the demo's source and project's source a lot to find hidden things. It'd be nice if you were told about them and guided a bit.

**Comment by ThomasBurleson** [comment]
@epelc, @trazek  - Perhaps you could start a gist/markdown doc with your initial research/ideas?
