### ISSUE TITLE
mdMenuOpen emits before DOM elements are created.

### ISSUE THREAD

**Issue by alucardu** [angular/material#11277]
## Bug, enhancement request, or proposal:
I want to remove a class in the created md--open-menu-container class element. The mdMenuOpen listner emits that the menu is open before the actual DOM element is created.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Click a button
2. Check the console 

### What is the expected behavior?
That the mdMenuOpen is emited after the DOM element has been created and the menu is available in the DOM.

### What is the current behavior?
The mdMenuOpen emits before the DOM element is created

### What is the use-case or motivation for changing an existing behavior?
Removing a class inside the created DOM menu element

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.5
- AngularJS Material: 1.1.9
- OS: Windows 10
- Browsers: Chrome latest

**Comment by Splaktar** [comment]
This looks like it's related to https://github.com/angular/material/issues/11273. It looks like you managed to solve this in https://github.com/angular/material/issues/11273#issuecomment-387774239 for your specific app requirement. Added support for disabling the auto focus behavior is likely the best solution here.

The `$mdMenuOpen` event is not documented and is not designed for this use case.
