### ISSUE TITLE
mdDateLocale: formatDate method is not being called onBlur and onFocus of input element of Date picker

### ISSUE THREAD

**Issue by vsinghal01** [angular/material#11282]
Description:
I want to have two different format while editing and viewing the date. I used mdDateLocale to add format on blur and focus event but it is not calling formatDate method.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Select any date from the picker e.g. 17 May 2018.
2.  Now focus again in the input element. It should be in the format similar to  **05/17/2018**
3.  Now click on other location to have a blur event. Date should look like  **May 17, 2018**
 
But it is not getting change onFocus and onBlur event. It seems like formatDate() is only being called while changing the value from the picker and not when we focus or change value directly in the input element manually.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.5.5
- AngularJS Material: 1.1.5
- OS:  Windows 10
- Browsers:  Chrome v68

**Comment by Splaktar** [comment]
There seem to be some misunderstandings here:
- You should only set the `formatDate` function in your app's `config()` function as described in https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider
- `$mdDateLocale` is not a public API that you should be modifying directly, especially dynamically at runtime.
- The `formatDate` function is only called when "external" changes are detected. This means when the `md-calendar-change` event is fired or the `ng-model` changes.

That said, it appears that you are trying to find a workaround that allows you to implement input masking on the datepicker's input element. This is not currently supported, but it is being tracked in https://github.com/angular/material/issues/9976.

**Comment by Splaktar** [comment]
Note that in your CodePen, you aren't 'calling' the `formatDate` functions, you are actually overriding them. I updated the [CodePen](https://codepen.io/Splaktar/pen/vjQgVa?editors=1010) to actually call the `formatDate` functions and it does seem to do what you want. This isn't really something that we support, but on initial testing in CodePen, this seems to work.
