### ISSUE TITLE
back event is fired twice on mobile when injecting NgMaterial. Using browser there is no issue.

### ISSUE THREAD

**Issue by mahmoudhsein** [angular/material#11288]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. 
1. 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 
- AngularJS Material: 
- OS: 
- Browsers:

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
