### ISSUE TITLE
Upgrade peer dependency to angular 1.7.0

### ISSUE THREAD

**Issue by enderdickerson** [angular/material#11281]
## Bug, enhancement request, or proposal:
Enhancement request

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
install angular 1.7.0

#### Detailed Reproduction Steps: 
1.  npm install angular@1.7.0

### What is the expected behavior?
No warnings from angular material

### What is the current behavior?
npm WARN angular-material@1.1.9 requires a peer of angular@>=1.4 <1.7 but none is installed.
etc...

### What is the use-case or motivation for changing an existing behavior?
Final 1.x major release from angular is 1.7.x.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.0
- AngularJS Material:  1.1.9
- OS: Windows 10
- Browsers:  N/A

**Comment by Splaktar** [comment]
Thank you for opening this. We were expecting 1.7 to come out in June, so we haven't yet done the proper level of testing for compatibility with AngularJS 1.7. We plan to address this in 1.1.10.

**Comment by jpike88** [comment]
Everyone works fine for me, have been using it as soon as it available.

**Comment by Splaktar** [comment]
I am going to update https://github.com/angular/bower-material today to support AngularJS 1.7.0 in the `peerDependencies` of NPM. 

I am also going to make the latest versions of AngularJS `^1.6.0` the dependencies for JSPM (updated from `^1.5.3`) and Bower (updated from `^1.4.8`). These can't be `^1.7.0` due to the issue below.

However, we can't support AngularJS 1.7.1 due to https://github.com/angular/material/issues/11319. PR https://github.com/angular/material/pull/11320 should fix that in AngularJS Material 1.1.10.

**Comment by Splaktar** [comment]
This will be available as part of the releases generated for each PR next week when a PR gets merged. Then it will also be part of AngularJS Material 1.1.10.

**Comment by endisway** [comment]
Since this will only ship as part of 1.1.10, the docs at https://github.com/angular/bower-material/#installing-angularjs-material were updated a little too soon and they now state that 1.1.9 supports AngularJS 1.7.0.

**Comment by Splaktar** [comment]
@endisway 1.1.9 does support AngularJS 1.7.0, but it doesn't support 1.7.1 until 1.1.10. 

Using 1.1.9 with AngularJS 1.7.0 will generate a peer dependency warning in NPM, but it's safe to ignore for 1.7.0 (not 1.7.1!).

**Comment by Splaktar** [comment]
### Update on this

- [bower-material](https://github.com/angular/bower-material/) which hooks into NPM, Bower, JSPM has been [updated to support AngularJS 1.7.x](https://github.com/angular/bower-material/commit/af93207efd58280fead949d2eff0175871b8ab69)
- AngularJS Material does not support AngularJS 1.7.1
- We're planning to release 1.1.10 this week which will have the above updates to [bower-material](https://github.com/angular/bower-material/) dependencies
