### ISSUE TITLE
datepicker: doesn't update model value when mdDateLocaleProvider.parseDate returns a invalid date

### ISSUE THREAD

**Issue by merorafael** [angular/material#11289]
## Bug, enhancement request, or proposal:

When the  `$mdDateLocaleProvider.parseDate` method return `null`or `new Date(NaN)`, is need change this data on your attribute associated. 

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Select an valid date using manual input or calendar;
2. Change date on input to invalid date.

### What is the expected behavior?
The selected date change to a null or invalid date.

### What is the current behavior?
The select date is not changed to null or invalid date if `$mdDateLocaleProvider.parseDate` method return `new Date(NaN)` or `null`;

### What is the use-case or motivation for changing an existing behavior?

The user can change datepicker input for a invalid date, but this component not change variable value for `null` or `new Date(NaN)`, expected when Angular need send this information for an API.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.5~1.6
- AngularJS Material: 1.1.8 
- OS: Arch Linux
- Browsers: Chrome

**Comment by Splaktar** [comment]
If you take a look at the [code here](https://github.com/angular/material/blob/master/src/components/datepicker/js/datepickerDirective.js#L636-L660), you will see that the datepicker does not update the model value unless the input is a valid `Date`.

> The datepicker's model is only updated when there is a valid input.

You can update your `parseDate` function to return something other than `new Date(NaN)` which seems to return the `string` `"Invalid Date"`. Returning empty string (`''`) is a valid option in this case (it would clear the input).
