### ISSUE TITLE
Card layouts inside advertisement slider in angularjs

### ISSUE THREAD

**Issue by chenchuraviteja** [angular/material#11284]
I have array of institutes. institutes is showing into the card layout based on system width (for example system - 4 cards, mac pro - 3 cards, tab - 2 cards, phone - 1 card). inside ng-repeat entire row i placed into one advertisement slider based on below i attached screen shot
![screenshot from 2018-05-17 18-16-35](https://user-images.githubusercontent.com/33121914/40178446-1c795b12-59ff-11e8-969c-a44409022077.png)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
