### ISSUE TITLE
$mdThemingProvider Failed to instantiate 

### ISSUE THREAD

**Issue by saffabook** [angular/material#1129]
Hi I am new to angular and giving material a go. Looks awesome. 
I however am stuck and have installed material#master via bower. 
I have followed the instructions in theme section but for some reason I get an error. 
I have added this. 
  
```js
    angular.module('myApp', ['ngMaterial', 'ui.router'])
        .config(function($urlRouterProvider, $stateProvider, $mdThemingProvider) {
           $mdThemingProvider.theme('default')
             .primaryColor('pink')
             .accentColor('orange');
          });
```
and the error is 
   
```console 
    Error: [$injector:modulerr] Failed to instantiate module myApp due to:
    TypeError: undefined is not a function
         at http://127.0.0.1:9000/scripts/app.js:23:20 ... 
```

Am I missing something?

**Comment by ajoslin** [comment]
1) Are you sure you installed angular-material#master from bower? I just did the same and  it works.
2) Are you sure your error is actually $mdThemingProvider.theme not working, and not an error somewhere else?

**Comment by saffabook** [comment]
Hi, thanks for your reply. I originally installed angular-material from bower, but did a reinstall of angular-material#master and still had the error. The theme() function was undefined, which was the error. I restarted the process from scratch, deleted everything and happy to report that everything works fine now. I think I didnt have the --save on the original install. An error on my part. Again thank you for the reply and great work. Much appreciated.
