### ISSUE TITLE
dateLocaleProvider: M/D date format is not triggering ng-change nor reflecting on model

### ISSUE THREAD

**Issue by SamerAlRawi** [angular/material#11292]
## Bug, enhancement request, or proposal:
Bug

# CodePen and steps to reproduce the issue:
#### CodePen Repro which demonstrates the issue: 
https://codepen.io/anon/pen/KRErLr?editors=101

#### Detailed Reproduction Steps: 
1. use keyboard to enter a date using M/D or MM/DD format, 
1. the date is shown as valid entry

### What is the expected behavior?
the entered date is bound to ng-model and triggers ng-change

### What is the current behavior?
entry is parsed but the date result is not bound to model nor ng-change is triggered

### What is the use-case or motivation for changing an existing behavior?
make it work like any other format

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.x
- AngularJS Material: latest
- OS: Windows
- Browsers: all

**Comment by Splaktar** [comment]
Here's a [fixed CodePen](https://codepen.io/Splaktar/pen/KRLMpW?editors=101).

They key element is using an undocumented override in `$mdDateLocaleProvider` for the `isDateComplete` function.

```js
  // Allow only a day and month to be specified.
  $mdDateLocaleProvider.isDateComplete = function(dateString) {
    dateString = dateString.trim();
    // Looks for two chunks of content (either numbers or text) separated by delimiters.
    var re = /^(([a-zA-Z]{3,}|[0-9]{1,4})([ .,]+|[/-]))([a-zA-Z]{3,}|[0-9]{1,4})/;
    return re.test(dateString);
  };
```

I'm going to add an example to the docs and document this `isDateComplete` function in a new PR, coming soon.

**Comment by SamerAlRawi** [comment]
Thanks @Splaktar that did the trick for now.
