### ISSUE TITLE
chips: when the model(array) is modified the chips view is not updated

### ISSUE THREAD

**Issue by hexadecy** [angular/material#11304]
## Bug, enhancement request, or proposal:

When using `md-on-add` in Angular Material 1.1.9 to remove a chip with a JS function, the view is not updated but the model is.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Open the CodePen and enter brocoli in fruit chips list.
2. The brocoli is supposed to go in vegetable chips list.
3. If you change the version to Angular Material 1.1.8 it will work properly.

### What is the expected behavior?
To update the chips view when the chip is removed programmatically.

### What is the current behavior?
The chips view is not updated and does not match the model.

### What is the use-case or motivation for changing an existing behaviour?
Was working with AM 1.1.8 and below.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.9
- AngularJS Material: 1.1.9
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
I think is caused by #11237

**Comment by Splaktar** [comment]
@free-easy heads up that this appears to be triggered by your changes from https://github.com/angular/material/pull/11166.

**Comment by Splaktar** [comment]
I've reproduced this in a unit test. It's hard to image how we don't have a unit test that covers changing the model Array, but we didn't until now...

**Comment by Splaktar** [comment]
I wasn't able to come up with an acceptable fix so far. I will keep looking into it. If anyone has any ideas, please let me know.

**Comment by hexadecy** [comment]
I'm sure the modelValue and the viewValue must be synchronize here. This is too stupid to be true, but maybe it could help to see the problem otherwise. As this workaround fix my issue.
```
MdChipsCtrl.prototype.updateNgModel = function() {
  this.ngModelCtrl.$setViewValue(this.ngModelCtrl.$modelValue);
  // TODO add the md-max-chips validator to this.ngModelCtrl.validators so that
  // the validation will be performed automatically on $viewValue change
  this.validateModel();
};
```

**Comment by Splaktar** [comment]
@hexadecy thank you for taking a look. Unfortunately that doesn't solve this either. I am continuing to investigate.

**Comment by Splaktar** [comment]
From what I can tell, @free-easy was following the guidance of the [AngularJS Docs for `$setViewValue`](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$setViewValue):
> Custom controls might also pass objects to this method. In this case, we should make a copy of the object before passing it to `$setViewValue`. This is because `ngModel` does not perform a deep watch of objects, it only looks for a change of identity. If you only change the property of the object then `ngModel` will not realize that the object has changed and will not invoke the `$parsers` and `$validators` pipelines.

But replacing the model with a copy (of the Array in this case), causes the problems seen in this issue and #11301.

It looks like we may just want to manually call the `ng-change` expression in `MdChipsCtrl.updateNgModel()` instead of trying to force it to be triggered by setting the model to a copy of the Array. But is this possible? Investigating...

**Comment by Splaktar** [comment]
That appears to be working well. PR https://github.com/angular/material/pull/11310 posted that should resolve this.
