### ISSUE TITLE
chips: ng-change with read-only array-model causes problems

### ISSUE THREAD

**Issue by IMM0rtalis** [angular/material#11301]
## Bug, enhancement request, or proposal:
ng-change introduced new assignment to model-value instead of just adding/removing the elements of the array. Therefore model-values which just have a getter and no setter are not working anymore.

_In some cases it is just wanted to have a property with no setter to not touch the reference to the array but let the values be changed._

# CodePen and steps to reproduce the issue:
[CodePen Demo 1.1.8](https://codepen.io/anon/pen/yEBoWE) where it still works. 
[CodePen Demo 1.1.9](https://codepen.io/anon/pen/gKYxVg) where it broke. 

#### Detailed Reproduction Steps: 
See codepen + look at [The codeline which broke the working code](https://github.com/angular/material/commit/0563f241e3b4b9916e5a572c863178ec201f8f70#diff-441d4815c4f57bf9fcf5e56ca16b5801R587).

### What is the expected behavior?
Code does still work after updating to 1.1.9. 

### What is the current behavior?
Completely dies, latets after removing a chip.

### What is the use-case or motivation for changing an existing behavior?
Make it work again without changing the application logic because of a material update

### Which versions of AngularJS, Material, OS, and browsers are affected?
- AngularJS Material: 1.1.9
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
Introduced with #11237

**Comment by Splaktar** [comment]
> Completely dies, latets after removing a chip.

I'm not seeing this. I'm seeing the chip added, but the text being left in the input. 
I.e.
![screen shot 2018-05-29 at 8 47 41 pm](https://user-images.githubusercontent.com/3506071/40692741-8f5e546c-6381-11e8-93ed-038e2c3615dd.png)
This is obviously not desirable though.

I'm a little hazy on all of the fine details of using objects with `get` and `set` in `ng-model`. Can you please point me to some documentation where it says that providing the `get` and not the `set` in such a configuration is acceptable/advised?

**Comment by Splaktar** [comment]
@free-easy heads up that this appears to be triggered by your changes from https://github.com/angular/material/pull/11166.

**Comment by IMM0rtalis** [comment]
@Splaktar when you remove the chip and try to add another one: nothing happens for me anymore. 

A quick google research did not find some article if it is good or bad.
We do this in some cases to not loose the reference to the array itself -> having some kind of caching. 
Nevertheless it is a breaking change of how chips deal with the model: with this change it is the first time they change the model-object itself instead of just manipulating the items.

**Comment by Splaktar** [comment]
This seems to be related to https://github.com/angular/material/issues/11304 which I am working on atm. My guess is that fixing that issue will resolve this as well.

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11310 posted that should resolve this.

**Comment by IMM0rtalis** [comment]
Yes, this resolves it. Thanks.
