### ISSUE TITLE
feat(chips, autocomplete): enable creating duplicate chips

### ISSUE THREAD

**Issue by GlauberF** [angular/material#11300]
## scenario:
I need to be able to select more than once the same item inside the (md-chips), but I noticed that in the code of the directive you validate so that you can not select repeated values

is there any way to allow appending an identical string or an exact object ??

**Comment by codymikol** [comment]
What is your use case for this kind of behavior?

**Comment by GlauberF** [comment]
I need to create a field for the client to assemble a calculation rule, then inside the object, has the fields that it can use and has two more positions (that is sum) and (subtract)

exemple:

**my object**
```
list: [{
                    'name': 'Valor do produto',
                    'value': 'vProd'
                },
                {
                    'name': 'Valor do desconto',
                    'value': 'vDesc'
                },
                {
                    'name': 'Outros valores',
                    'value': 'vOutro'
                },
                {
                    'name': 'Valor do frete',
                    'value': 'vFrete'
                },
                {
                    'name': 'Valor do seguro',
                    'value': 'vSeg'
                },
                {
                    'name': 'sum',
                    'value': '+'
                },
                {
                    'name': 'subtract',
                    'value': '-'
                }
            ]
```

**my front:**
![captura de tela de 2018-05-25 17-12-51](https://user-images.githubusercontent.com/11314585/40564124-e47db1aa-603d-11e8-8d4f-d724c246cfcc.png)


**riding the formula**
![captura de tela de 2018-05-25 17-15-32](https://user-images.githubusercontent.com/11314585/40564230-42f222de-603e-11e8-9d87-63d9f001168d.png)


you can see that the (sum) and (subtraction) has already been selected, but I would have to continue mounting my calculation formula, but I can no longer select the sum and (subtraction)


and in the backend, it should receive a json in the following format:
```
[
	{
       'name': 'Product value',
       'value': 'vProd'
    },
	{
        'name': 'sum',
        'value': '+'
    },
    {
       'name': 'Discount amount',
       'value': 'vDesc'
    },
	{
       'name': 'subtract',
       'value': '-'
    },
    {
       'name': 'Other values',
       'value': 'vOutro'
    },
    {...}
]
```

then I loop it in my back and concatenate the values, in the position that is in the object.
the formula being as follows:

**vProd+vDesc-vOutro**

Of course this is an example, but my use case would be more or less that and I have to be doing with **md-chips**

**Comment by Splaktar** [comment]
I like the idea of what you are building there. It looks pretty nice! However, `md-chips` is not written to support this use case and we can't easily add this. We have too many major bugs open against chips atm that need our attention. So we're going to focus our efforts on fixing those bugs rather than adding more features to `md-chips`.

**Comment by GlauberF** [comment]
ok, but to work I would just have to remove the validation that was imploded by you (appendChip disallows identical objects).
How could I circumvent this validation?

**Comment by GlauberF** [comment]
ok, but to work I would just have to remove the validation that was imploded by you (appendChip disallows identical objects).
How could I circumvent this validation?

**Comment by Splaktar** [comment]
@GlauberF you should be able to override the `appendChip` prototype in `MdChipsCtrl` with your own implementation.

**Comment by GlauberF** [comment]
@Splaktar can I do this directly in my controller or will I have to change directly in the component, inside the material lib?

**Comment by Splaktar** [comment]
I believe that a separate decorator is what you want. Here's an example of one: https://github.com/angular/material/issues/7230#issuecomment-299847481.

The [AngularJS Decorator Docs](https://docs.angularjs.org/guide/decorators) are pretty detailed and helpful as well.

I believe that you would want to target the `mdChipsDirective` and then from the link function's `controllers`, you would want to find the `MdChipsCtrl` and then replace the `appendChip` prototype with your own implementation that allows duplicates.
