### ISSUE TITLE
compiler: refactor to support AngularJS 1.7.1

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11319]
## Bug, enhancement request, or proposal:
Proposal

# CodePen and steps to reproduce the issue:
#### Demo which demonstrates the issue: 
https://travis-ci.org/angular/material/jobs/388688438 is just one of many CI unit test jobs which have failed for the AngularJS `SNAPSHOT` view since https://github.com/angular/angular.js/pull/16580 was merged.

### What is the expected behavior?
AngularJS Material unit tests in `master` pass against the AngularJS `SNAPSHOT` version.

### What is the current behavior?
54 failing tests can be seen in all recent jobs like https://travis-ci.org/angular/material/jobs/388688438.

### What is the use-case or motivation for changing an existing behavior?
We were fairly well prepared for the changes in https://github.com/angular/angular.js/pull/15782 that went into AngularJS 1.7.0, but the follow on breaking changes in https://github.com/angular/angular.js/pull/16580 that are part of the unreleased AngularJS 1.7.1 remove some private and undocumented APIs that AngularJS Material depended upon.

One example is the use of the third and fourth arguments in `$controller` which were added to fix [an issue with ES6](https://github.com/angular/material/pull/10977) that we resolved in 1.1.5. You can see some of the comments that explain this here: https://github.com/angular/material/blob/0046467372a309414a6de5ac51d8ae99604ea49e/src/core/services/compiler/compiler.js#L452-L477.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.1
- AngularJS Material: All
- OS: All
- Browsers: All
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
We cover some of the details of `$compileProvider.preAssignBindingsEnabled()` in our updated docs for 1.1.9 here: https://material.angularjs.org/latest/api/service/$mdCompilerProvider#mdcompilerprovider-respectpreassignbindingsenabled-respected

**Comment by Splaktar** [comment]
@gkalpak provided this guidance:
> So, this method needs to be refactored so that it doesn't pass the 3rd argument to `$controller()` if AngularJS is at v1.7.1 or higher :grin: https://github.com/angular/material/blob/0046467372a309414a6de5ac51d8ae99604ea49e/src/core/services/compiler/compiler.js#L452-L477

This appears to just be one step of many towards fixing this. Making this change alone causes the failing tests to increase from `54` to `108`. 

If I make some changes to `respectPreAssignBindingsEnabled` in `compiler.js` and `compiler.spec.js`, I can get the failures down to 96. Most of them are expected and come from InterimElements like Dialog, Toast, Panel, but I'm still seeing `6` `mdCompiler` errors that all look like this:
```
	TypeError: invokeCtrl is not a function
	    at MdCompilerService.MdCompilerProvider.MdCompilerService._createController (src/core/services/compiler/compiler.js:477:16)
	    at Object.linkFn [as link] (src/core/services/compiler/compiler.js:432:25)
	    at UserContext.<anonymous> (src/core/services/compiler/compiler.spec.js:131:14)
	    at Object.invoke (node_modules/angular/angular.js:5090:17)
	    at UserContext.WorkFn (node_modules/angular-mocks/angular-mocks.js:3261:20)
	Error: Declaration Location
	    at window.inject.angular.mock.inject (node_modules/angular-mocks/angular-mocks.js:3224:25)
	    at Suite.<anonymous> (src/core/services/compiler/compiler.spec.js:120:53)
	    at Suite.<anonymous> (src/core/services/compiler/compiler.spec.js:109:5)
	    at Suite.<anonymous> (src/core/services/compiler/compiler.spec.js:16:3)
```

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11320 is open and appears to fix all of the tests for AngularJS `SNAPSHOT` while not breaking any of the tests against AngularJS 1.5 and 1.6.

**Comment by gkalpak** [comment]
> this method needs to be refactored so that it doesn't pass the 3rd argument to $controller() if AngularJS is at v1.7.1 or higher 

To be clear, by "refactored" I meant making it so that it doesn't rely on the removed AngularJS feature (3rd argument) in addition to not passing the argument :grin:
