### ISSUE TITLE
$mdDateLocaleProvider.formatDate is not called when date is manually entered

### ISSUE THREAD

**Issue by borisovmarija** [angular/material#11311]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. 
1. 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 
- AngularJS Material: 
- OS: 
- Browsers:

**Comment by borisovmarija** [comment]
This are the functions that are not using moment.js:
      $mdDateLocaleProvider.parseDate = function(dateString) {
        var ds = dateString.split('/');
        var date=new Date(ds[2],ds[1]-1,ds[0]);
        if(isNaN(date.getTime())) return new Date(NaN);
        else return date;
      };

      $mdDateLocaleProvider.formatDate = function(dateString) {
        var date=new Date(dateString);
        function pad(n) {return n < 10 ? "0"+n : n;}
        if(isNaN(date.getTime())) return null;
        else
          return pad(date.getDate())+"/"+pad(date.getMonth()+1)+"/"+date.getFullYear();
      };

When date in right format is entered, everything works perfectly. But if format of date is wrong, it is behaving like nothing is entered, if old value exists, it stays the same, like ng-model is not changed.

**Comment by borisovmarija** [comment]
This behavior is for angularjs and angular-material 1.1.8.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. A CodePen reproduction is required.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

This is a duplicate. You can find details about how this works and why you are seeing problems here: https://github.com/angular/material/issues/11289#issuecomment-390429386
