### ISSUE TITLE
chips(autocomplete): dropdown scrolls off screen

### ISSUE THREAD

**Issue by sujinecho18** [angular/material#11324]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
https://codepen.io/anon/pen/aKJYqZ

#### Detailed Reproduction Steps: 
1.  Resize browser to a much smaller size (both horizontally and vertically), start to add items and notice the dropdown (md-virtual-repeat-container) jumps to the top of the screen
2. Keep adding items until the md-content panel starts to scroll, notice the dropdown starts to scroll off the screen. 

### What is the expected behavior?
Dropdown sticks to the current input field

### What is the current behavior?
Dropdown scrolls off screen

### What is the use-case or motivation for changing an existing behavior?
User can not click on the items in auto complete dropdown.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6 
- AngularJS Material: 1.1.9 
- OS: Windows, MAC
- Browsers: Chorme, IE, Firefox.
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
![image](https://user-images.githubusercontent.com/37938146/41244921-9a6598e6-6d74-11e8-84fb-e9786ff830c3.png)

![image](https://user-images.githubusercontent.com/37938146/41244972-b7741ec6-6d74-11e8-8226-94261525ad48.png)

**Comment by Splaktar** [comment]
What screen size and resolution are you seeing this problem at? Down to an iPhone 5 still has plenty of room and displays the dropdown properly for me.

**Comment by sujinecho18** [comment]
The issues start to appear when there's not enough space on the bottom to display the dropdown. I didn't test on phone but in Chrome on PC, if you open the example and resize the browser to 356*621, the drop down jumps to the top of the screen. If you add 3 or 4 items, the drop down starts to scroll off the screen. 

356*621 is just to demonstrate the problem, most web app minimum size is bigger that that. Regardless of the screen size, if you have many items you'll get the issues at some point.

**Comment by Splaktar** [comment]
Ah OK, yes, thank you for the extra detail. This is a known issue tracked in https://github.com/angular/material/issues/10631.
