### ISSUE TITLE
picker components (md-datetime, md-color)

### ISSUE THREAD

**Issue by olakara** [angular/material#1133]
I couldn't find any form components for picking date, time and color. I was looking for a date and time picker for my application as show here: http://www.google.com/design/spec/components/pickers.html

**Comment by mpfisterUniBE** [comment]
It's not built-in yet but planned for the release in Q1 2015:
=> https://github.com/angular/material/issues/648

**Comment by marcysutton** [comment]
Please help us reduce duplicates by checking the issues list and [ngMaterial forum](https://groups.google.com/forum/#!forum/ngmaterial) before posting. Thank you!!

**Comment by Remigius2011** [comment]
How about a color picker? No mention of a color picker neither in the issues nor in the forum (nor in the spec).

**Comment by ThomasBurleson** [comment]
@Remigius2011 - this is a closed thread.

**Comment by marcysutton** [comment]
Also there is one built into Chrome.

**Comment by Remigius2011** [comment]
@ThomasBurleson sorry, but comminting was not disabled, so instead of opening a new thread I allowed myself to add a comment here.

@marcysutton Chrome is not my only target - and is the Chrome one compliant with md spec?

**Comment by marcysutton** [comment]
There isn't a color picker in the Material Design spec, potentially because in addition to the Chrome browser color picker, there are OS-level color pickers and extensions for other browsers. It would be a duplicative effort that wouldn't be a priority among the other features we need to support. http://www.google.com/design/spec/components/pickers.html

**Comment by jmuharsky** [comment]
Considering the Material Design spec isn't just "have color", but is about specific themed groups of colors, it seems like a MD color picker would be a domain-specific component, rather than just a duplicative effort of an OS color picker.

https://www.google.com/design/spec/style/color.html

**Comment by innerpeace0** [comment]
A color picker limited to MD colors would be a great tool.

**Comment by ThomasBurleson** [comment]
A color picker is not currently planned a component within Angular Material.
A TimePicker will be published sometime after v1.0 is released.
