### ISSUE TITLE
progress-circular: wrong circle arc when changing from indeterminate to determinate mode

### ISSUE THREAD

**Issue by aprat84** [angular/material#11334]
## Bug, enhancement request, or proposal:
Bug

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](https://codepen.io/anon/pen/zaWYXE?editors=1010) which demonstrates the issue: 
Progress arc does not match actual value.

#### Detailed Reproduction Steps: 
1. Show a circular progress in `indeterminate` mode (ie: waiting for first progress value from ajax upload)
2. Change mode to `determinate`
3. Set `value` to any number between range (optionally, keep increasing it until 100)

### What is the expected behavior?
Progress arc in determinate mode should match value, starting at "north" (0 degrees)

### What is the current behavior?
Looks like progress has an offset of +90 deg approx.

### What is the use-case or motivation for changing an existing behavior?
Seems a bug. Progress should reset its internal runtime settings when changing modes.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.5.1 and 1.7.2
- AngularJS Material: 1.1.4 and 1.1.9
- OS: Ubuntu 18.04
- Browsers: Chrome 67.0.3396.87 (Official Build) (64-bit)
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
Codepen is pretty self-explanatory.

**Comment by Splaktar** [comment]
Thank you for reporting this.

I assume that using an `ng-if` and having a second progress circular used for determinate values would be a valid workaround for the time being?

**Comment by aprat84** [comment]
Yes, that's exactly what we are doing.
Thank you.

**Comment by marosoft** [comment]
Please check this [CodePen](https://codepen.io/marosoft/pen/aazwvX?editors=1010).
I will create PR soon.

**Comment by Splaktar** [comment]
@marosoft I'd love to see a PR for this 😄
