### ISSUE TITLE
chips: model changes are not reflected in view

### ISSUE THREAD

**Issue by oliversalzburg** [angular/material#11333]
## Bug, enhancement request, or proposal:
Bug.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Click any of the contacts listed below the chips control.
1. Remove one of the chips from the chips control.
1. Try to add any other chip by clicking one of the contacts in the list.

### What is the expected behavior?
The contact is added as a chip.

### What is the current behavior?
No chips are added. The only way to add chips is by using the chips control's search function.

### What is the use-case or motivation for changing an existing behavior?
This is obviously a bug and needs to be fixed :D

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.9
- AngularJS Material: 1.1.9
- OS: Windows 10
- Browsers: Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
I also noticed that the `onModelChange` handler is not invoked when the chips model is manipulated.

**Comment by oliversalzburg** [comment]
Possible duplicate of #11218

**Comment by Splaktar** [comment]
Please test against `master` as it should be fixed there as part of 1.1.10.

**Comment by oliversalzburg** [comment]
I can't easily integrate unpublished dependency code. Are there any pre-build versions available somewhere?

**Comment by oliversalzburg** [comment]
@Splaktar I adjusted the CodePen to use https://material.angularjs.org/HEAD/angular-material.min.js and that resolved the issue.

**Comment by Splaktar** [comment]
Each commit (merge) to master gets a release via [bower-material](https://github.com/angular/bower-material/commits/master). You should be able to install the latest via npm using `1.1.9-master-5e37b63`.

But yeah, using `HEAD` with CodePen is easier.

Thank you for verifying. I'll close this.
