### ISSUE TITLE
md-autocomplete jumps in iOs (keyboard quickly opened and hid)

### ISSUE THREAD

**Issue by rantiev** [angular/material#11336]
See problem demo here.
http://output.jsbin.com/zaroqo/1

Sometime when you try to tap on or example 5th md-autocomplete it doesn't work. You will be able to reproduce it playing couple of minutes on iphone 10.1.1 or ipad 11.2.2

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
