### ISSUE TITLE
mdTabs: Deleting a tab makes no tab being selected

### ISSUE THREAD

**Issue by eckyputrady** [angular/material#1134]
Hi, I found this bug when working with angular.material and I can reproduce it using the Tabs demo:

1. Open the Dynamic Tabs demo (https://material.angularjs.org/#/demo/material.components.tabs)
2. Delete every tab until only 2 tabs left
3. Select the first (left-most) tab
4. Press 'Remove Tab'
5. Expected: The last tab should be automatically selected. Actual: No tab is selected.

Thanks

**Comment by robertmesserle** [comment]
Screenshot demonstrating the issue on demo page:

![screen shot 2015-01-12 at 10 23 28 am](https://cloud.githubusercontent.com/assets/571363/5708368/28030190-9a45-11e4-80bb-01a1d036297b.png)

**Comment by ThomasBurleson** [comment]
The single-tab looks VERY odd here because we do not color differentiate between the tab and tab container background. 

> If we did, then the tab buttons would be clear and a single tab would not look disconnected.

**Comment by ThomasBurleson** [comment]
Let's hold off until Weds AM.

**Comment by ThomasBurleson** [comment]
Per talks with JoeyE, we also need specifications on UX with ALL tabs have been removed.

**Comment by naomiblack** [comment]
Guidance from UX: when no tabs remain, remove the tab pane. OR disallow removing the last tab.

**Comment by robertmesserle** [comment]
There is another issue for the empty tab state, closing issue
