### ISSUE TITLE
First option highlighted

### ISSUE THREAD

**Issue by amankhanna24** [angular/material#11347]
Using angular select material in angularJS. First option always highlighted. 
1. How to remove first highlight option.
2. When used this https://codepen.io/anon/pen/dKwGEp#anon-login on keyUp dropdown flickers.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

**Comment by Splaktar** [comment]
Since this issue seems pretty serious, I opened https://github.com/angular/material/issues/11357 to track this.
