### ISSUE TITLE
Material FormField with Outline border styling issue on hover

### ISSUE THREAD

**Issue by Deezlar** [angular/material#11359]
## enhancement request

# CodePen and steps to reproduce the issue:
#### Viewable on the Material Demo at 
https://material.angular.io/components/form-field/overview

issue: 
When using appearance="outline" on FormFields, the default mouseover thick border color is black, with no documented way to change this. On selection, the color is correctly reflected as the theme primary/accent/warn color

#### Detailed Reproduction Steps: 
1. Navigate to https://material.angular.io/components/form-field/overview
2. Scroll to "Form field appearance variants"
3. Note that the example for appearance="outline" has a black mouseover border

### What is the expected behavior?
We should have the option to modify the color of the thick mouseover border, either through theme or direct styling. Defaulting to black is not ideal for many color palettes

### What is the current behavior?
On mouseover of a FormField with appearance="outline" the border is thick solid black with no clear way to style it

### What is the use-case or motivation for changing an existing behavior?
Styling and theming

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular: Angular 5/6 
- Angular Material: 5/6 (current 6.3.2)
- OS: Windows (not tested others)
- Browsers: IE, Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

![image](https://user-images.githubusercontent.com/35882393/42350884-4f07fb8e-80aa-11e8-85d4-525aacb7e30e.png)

**Comment by Deezlar** [comment]
Wrong version to raise this issue against

**Comment by chetanbirajdar** [comment]
I have worked this out by css :  .mat-form-field-appearance-outline:not(.mat-form-field-disabled) .mat-form-field-flex:hover .mat-form-field-outline {
     border: 0.2px solid #666;
     opacity: 1;

     .mat-form-field-outline-start,
     .mat-form-field-outline-gap,
     .mat-form-field-outline-end {
         border: none;
     }
 }

**Comment by chetanbirajdar** [comment]
> I have worked this out by css : .mat-form-field-appearance-outline:not(.mat-form-field-disabled) .mat-form-field-flex:hover .mat-form-field-outline {
> border: 0.2px solid #666;
> opacity: 1;
> 
> ```
>  .mat-form-field-outline-start,
>  .mat-form-field-outline-gap,
>  .mat-form-field-outline-end {
>      border: none;
>  }
> ```
> 
> }

let me know if this is required!

**Comment by waynon** [comment]
I think this issue should not be closed. We need a not so tricky way to remove the visual effect when hovering.

**Comment by Splaktar** [comment]
> I think this issue should not be closed. We need a not so tricky way to remove the visual effect when hovering.

This is the wrong repo. This repo is for AngularJS Material.
