### ISSUE TITLE
Error in subheader

### ISSUE THREAD

**Issue by svzosorio** [angular/material#1135]
subheader isn't in corect position.

![captura de pantalla 2015-01-07 a las 10 25 27 a m](https://cloud.githubusercontent.com/assets/5873627/5647849/a90c1bce-9657-11e4-8c07-0508242d41cf.png)

**Comment by mzbyszynski** [comment]
@svzosorio  are you talking about this issue: #580 ?

**Comment by svzosorio** [comment]
@mzbyszynski, yes but the subheader doesnt show into a second md-content

**Comment by mzbyszynski** [comment]
@svzosorio Here is a plunkr I made a while ago that demonstrates the bug from #580. I haven't tried nested `md-content` but feel free to fork this and modify it to demonstrate the problem you are experiencing 

http://plnkr.co/edit/cIYP7m?p=preview

Also what browser are you using? The way the sticky subheader is handled is different in Firefox & Chrome, and I've only seen this bug happen in Chrome.

**Comment by rschmukler** [comment]
As per this [fiddle](http://jsfiddle.net/rschmukler/g8z57Lvz/), the subheaders appear to render properly. The sticky effect does get screwed up, but you likely shouldn't be nesting the contents with subheaders - if you have a use case let me know and I can take a look. Please submit a plunker in a new issue.
