### ISSUE TITLE
md-autocompl

### ISSUE THREAD

**Issue by bushuyev** [angular/material#11354]
## Bug, enhancement request, or proposal:
bug

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](https://codepen.io/anon/pen/YvgprG?editors=1111) which demonstrates the issue: 

https://codepen.io/anon/pen/YvgprG?editors=1111

#### Detailed Reproduction Steps: 
1. click inot autocomplete's input field
2. type aaa

### What is the expected behavior?
there is single 'x' button

### What is the current behavior?
there are two 'x' buttons

### What is the use-case or motivation for changing an existing behavior?
desire for perfection

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.5.11
- AngularJS Material:  1.1.10
- OS: windows
- Browsers: IE11, not reproducible in Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

![2018-07-02 18-28-40](https://user-images.githubusercontent.com/9256781/42175815-1a49482e-7e27-11e8-881a-6c8381625fd8.png)

**Comment by bersLucas** [comment]
The black X on the left is inserted by the browser, not material.

Use this to globally remove them from your site:

```css
::-ms-clear {
    display: none;
}
```

**Comment by bushuyev** [comment]
thank you!
