### ISSUE TITLE
md-text-float issue when using ionic framework

### ISSUE THREAD

**Issue by atentis** [angular/material#1136]
Hello,

I have found an issue where I am guessing the style sheets for ngmaterial and ionic are conflicting. When you use both the text on the md-text-float shrinks and you lose the bottom line completely. 

Here is a plunk. Just delete the cdn for the ionic stylesheet to see the difference (line 6).
http://plnkr.co/edit/Mz4oNpObDSp2fmznQAgv?p=preview

Great work on everything so far! I have been spreading the word.

-Adam

**Comment by Frank3K** [comment]
`md-text-float` has just been deprecated, see 60fcd6f.
