### ISSUE TITLE
md-tabs: text turns to dots on small screen on IE11

### ISSUE THREAD

**Issue by Oneril** [angular/material#11366]
__Actual Behavior:__
When number of tabs exceeds the horizontal space tabs label are cut and dots appear.

__CodePen (or steps to reproduce the issue):__
* https://codepen.io/anon/pen/LBYrWL
* Resize your browser and see when the the dots appear

__AngularJS Versions:__
* AngularJS Version: 1.6.7
* AngularJS Material Version: 1.1.10

__Additional Information:__
* Browser Type: IE
* Browser Version: 11

**Comment by Splaktar** [comment]
Dupe of https://github.com/angular/material/issues/10406.

**Comment by Oneril** [comment]
Weird I couldn't find it yesterday... Sorry for that ;)
