### ISSUE TITLE
tabs: elements variable in MdTabsController is no longer referenced

### ISSUE THREAD

**Issue by NgMomentum** [angular/material#11377]
## Bug, enhancement request, or proposal:

Small correction or update to MdTabsController controller.

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
Not applicable.

#### Detailed Reproduction Steps: 
1. 
1. 

### What is the expected behavior?
Variable not needed.

### What is the current behavior?

Variable is defined and no longer used.

### What is the use-case or motivation for changing an existing behavior?

Clarification of code or to minimize ambiguity.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS:  all
- AngularJS Material: v1.1.10
- OS: any
- Browsers: any
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
Not applicable

The variable "elements" as written "elements  = getElements()," in the MdTabsController is no longer needed. That is, it is defined, initialized and updated in the MdTabsController controller, but is no longer used because each subroutine function calls its own "elements" variable anyway. Looks to be leftover code, but of coarse, that is for you guys to decide. This is just a heads up that there is a confusing use of "elements" here, nothing more.

**Comment by Splaktar** [comment]
A GitHub link to the source where that variable is defined would be very helpful.

**Comment by Splaktar** [comment]
It looks like the variable in question is https://github.com/angular/material/blob/v1.1.10/src/components/tabs/js/tabsController.js#L14.

It does look like all of the references are now using [getElements()](https://github.com/angular/material/blob/v1.1.10/src/components/tabs/js/tabsController.js#L470-L491) instead of using the controller scoped `elements` variable.

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11379 submitted to address this.
