### ISSUE TITLE
Cannot use md-warn, md-primary, md-accent with md-input-container

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1137]
I want to be able to use md-warn,md-accent in the new md-input-container to reflect validity.

I would expect to be able to set ng-class="{'md-warn':!frm.input.$valid}" type of thing but this is not having any effect. If I apply a md-warn directly to any element within the md-input-container it doesn't seem to do anything?

**Comment by ajoslin** [comment]
Fixed, thanks for the issue.

**Comment by hodeyp** [comment]
Hi - thanks for the fix. My only observation would be that md-warn colour is only applied when the control has focus. As such it is not immediately obvious which inputs are in error unless the control happens to have focus. Would be good to be able to have the md-warn color applied when it doesn't have focus instead of reverting to the grey colour scheme.
