### ISSUE TITLE
Dynamically selecting tabs

### ISSUE THREAD

**Issue by m3rolam** [angular/material#11383]
Bug:
Tab group does not select tab dynamically.

# CodePen and steps to reproduce the issue:
https://stackblitz.com/angular/eardvdpkrkgy?file=app%2Ftab-group-dynamic-example.html

issue: 

#### Detailed Reproduction Steps: 
1. Go to tab example. 
2. Check 'Select tab after adding'
2. Click 'Add New Tab'

### What is the expected behavior?
The added tab is selected.

### What is the current behavior?
The added tab is not selected.

### What is the use-case or motivation for changing an existing behavior?
Need the ability to dynamically add a new tab and selected it after adding.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 6.0.9
- AngularJS Material: ^6.4.0
- OS: Windows
- Browsers: Chrome 67.0.3396.99

**Comment by codymikol** [comment]
This github is actually for the angularJS (Angular 1.x) version of angular material, you should check over [here](https://github.com/angular/material2 ) for the Angular version of material.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
