### ISSUE TITLE
Contact list with search filter

### ISSUE THREAD

**Issue by shankargurutarikere** [angular/material#11394]
How can i make contact list with search filter in angular 6 using material,I have not found any resources in material website.
This is the thing i want to achieve
![capture](https://user-images.githubusercontent.com/31584520/43566945-ca3aa5aa-964d-11e8-81a6-de08d2c78283.PNG)

**Comment by codymikol** [comment]
This is actually for the angular 1.x version of material, any non feature / bug related discussion of material2 can be discussed over at the [google group](https://groups.google.com/forum/#!forum/angular-material2)

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
