### ISSUE TITLE
layout: rendering problems with items in a column layout overlapping

### ISSUE THREAD

**Issue by filipe-carvalho** [angular/material#11401]
Hello Dear Comunity,
I am facing a problem using angularjs material with google chrome

Appears that google chrome doesnt render very well some functionality of angularjs material
For example:
  I am tryng to emulate the column layout of material based on documentation example

```
<div layout="column">
  <div flex>First item in column</div>
  <div flex>Second item in column</div>
</div>
```
This code should make 2 rows (one after the another) like this example:

![screenshot_2018-08-08 angularjs material - layout layout containers](https://user-images.githubusercontent.com/37399888/43844062-caaf70b0-9b20-11e8-87ff-0c5e9791b83e.png)

However using this [PLUNKER](https://plnkr.co/edit/FCrPiam5tHTpIWxMUuMi) in Google chrome (For reproduce use google chorme) i am obtaining the following output:

![22](https://user-images.githubusercontent.com/37399888/43844324-57e492a8-9b21-11e8-8f69-72bee6c483fd.png)

Like you see the 2 rows are mixed up together in only 1 row and text is in top of eacher when they should in 2 rows.

Folowing the same logic i am also experimenting problems based on the render of the calendarcomponent of the angularjs material (See also [PLUNKER](https://plnkr.co/edit/FCrPiam5tHTpIWxMUuMi) example in google chrome for the problem reprodution):

The calendar component should be render like this example:
![33](https://user-images.githubusercontent.com/37399888/43844550-ee798d4a-9b21-11e8-9638-273b33f7e2c7.png)

However the some problems in chrome( for example part of the blue circle that exist in day 3 of august is inside the calendar header) 

![44](https://user-images.githubusercontent.com/37399888/43844567-f6d9b6b8-9b21-11e8-8970-e400993c862b.png)

### STEPS TO REPRODUCE

USE ONLY THIS LINK (PLUNKER) IN CHROME:

https://plnkr.co/edit/FCrPiam5tHTpIWxMUuMi

-----

What i am doing wrong, is there something i can do, or this is some bug of the angularjs ? There something i can do do correct this ?

Thank you in advance

**Comment by codymikol** [comment]
You have three divs with no height / width. So what you're seeing is expected, it's a 0x0 container that holds two 0x0 container so the text just overlaps. If you give them height and with you get the results you'd expect.

 Check out this [plunker](https://next.plnkr.co/edit/4hqNBT7QN3xPySt2)

**Comment by codymikol** [comment]
I understand why you'd be confused by the docs though, it isn't at all obvious where that styling is coming from. I think it would make sense that the layout docs include the css styling as well in their examples so people don't assume that the styling is a side effect of the layout directives.

**Comment by Splaktar** [comment]
Right, column layouts need the items to have some kind of known width.

You can accomplish something similar with `layout="row" layout-wrap` on the container and `flex="100"` when you want the items to flow and aren't sure of their height. Here's an [example of that](https://next.plnkr.co/edit/IuoNRqwn7VGczt7G).

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. This gives the team the information needed to investigate the bug or prioritize the feature.

What OS are you running? If it's Ubuntu, then the calendar concern is being tracked in https://github.com/angular/material/issues/11397. If you aren't on Ubuntu, please add some of your OS details to that issue so that we can track it down.

**Comment by filipe-carvalho** [comment]
Splaktar  can you give a solution without using layout-row ? Only using layout-column ? how can accomplish the same result with layout-colum feature 
As you can see in mine plunker i dont have width and height defines, but as my div as text inside the height is determined by the text (but is giving 0px) hoevwer the width is 100%

Can you explain me why in Firefox i obtain good results and in chrome not with my [PLUNKER](https://plnkr.co/edit/FCrPiam5tHTpIWxMUuMi?p=preview) ? why firefox know the height and chrome dont determinate the height of my text ?

**Comment by Splaktar** [comment]
Firefox and Webkit (Chrome and Safari) don't handle flex columns the same.

These should help you find a column based solution:
https://stackoverflow.com/a/35869387/633107
https://stackoverflow.com/a/20959601/633107

https://github.com/philipwalton/flexbugs describes a lot of different bugs and behaviors with flexbox, but I don't see this specific issue there.
