### ISSUE TITLE
mat-table does not display the dataSource data

### ISSUE THREAD

**Issue by marcelolav** [angular/material#11406]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
Github:  https://github.com/marcelolav/proyecto0

#### Detailed Reproduction Steps: 
1. 
98/5000
the mat-table is constructed according to the example, with the data of a firestore base
1. 

### What is the expected behavior?
That shows the data contained in the dataSource, which according to the chrome console meets the data.

### What is the current behavior?

does not show any data

### What is the use-case or motivation for changing an existing behavior?

A firestore is used, which with a conventional table shows the data, according to the Chrome console and FireFox the data are in the dataSource but they are not shown by means of interpolation. I reiterate that if I perform the deployment with a conventional table it works.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 6.3.0
- AngularJS Material: 6.4.3
- OS: Microsoft Windows [Versión 6.1.7601]
- Browsers: Google Chrome,  Mozilla Firefox.
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
I leave screenshots of the problem, console and code of my application
![salidapantalla](https://user-images.githubusercontent.com/27835471/44008308-79e05928-9e78-11e8-99f5-77180771806f.jpg)
![codigo_html](https://user-images.githubusercontent.com/27835471/44008309-7a03725a-9e78-11e8-81f6-56edc4c94f87.jpg)
![codigo_ts](https://user-images.githubusercontent.com/27835471/44008310-7a3922ce-9e78-11e8-9c07-d401963434bb.jpg)
![consola](https://user-images.githubusercontent.com/27835471/44008311-7a5def0a-9e78-11e8-9f01-6017008739e4.jpg)

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by marcelolav** [comment]
Apologies but I estimate that this is a failure behavior, it is not a query but rather a warning of what is happening in this case. Anyway, I will enter the problem where it indicates. I also comment that I think it's a failure because with the same code in three components it has different behaviors (in one component it works correctly) and I already check these codes several times. Thank you very much and best regards.
