### ISSUE TITLE
Is https://material.angular.io down?

### ISSUE THREAD

**Issue by wluijk** [angular/material#11408]
#### Detailed Reproduction Steps: 
1. Go with your mouse to your browser and click the icon
2. Wait till the app is up and running
3. Go to the address bar
4. Type the address: https://material.angular.io/ 

### What is the expected behavior?
To get a full blown website

### What is the current behavior?
You get a blanco page with a centered message ERR_FAILED

### What is the use-case or motivation for changing an existing behavior?
The use case is to visit the material angular docs...

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Browsers: any
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
- We tried this from the Netherlands and with proxies from all around the world.

**Comment by codymikol** [comment]
This is for the angular 1.x version of material, check out https://github.com/angular/material2

**Comment by bersLucas** [comment]
It is not down. [reference](https://downforeveryoneorjustme.com/material.angular.io).

Also, material.angular.io is for Material2, found here: https://github.com/angular/material2

This repository is for angular material for Angular.js

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
