### ISSUE TITLE
TypeError on ng-radio-group

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1141]
Hi, i have a radio-group bound to a boolean value.

When the page is loaded I am getting..
TypeError: Cannot read property '$viewValue' of undefined

this is related to line 4484 of the latest master build..

      getViewValue: function() {
        return this._ngModelCtrl.$viewValue;
      },

Once loaded the model is working correctly, but the init seems to be running before the model is ready.
not sure of this is a bug in my code (its bound to an angularFire object), but looks like there should be a check in this function to confirm _ngModelCtrl is defined?

**Comment by marcysutton** [comment]
Which version of the code? We pushed an update to radio buttons yesterday: https://github.com/angular/material/pull/1123#event-215933865

**Comment by hodeyp** [comment]
this is from today's buid.. v0.7.0-rc2-master-9a0b3c3

**Comment by ThomasBurleson** [comment]
@hodeyp - do you have a Plunkr or CodePen that demonstrates this issue?

**Comment by hodeyp** [comment]
have a demo at http://run.plnkr.co/plunks/tlWEJK/

**Comment by ThomasBurleson** [comment]
@hodeyp - excellent. thx

**Comment by ThomasBurleson** [comment]
@hodeyp - I am unable to access that Plunkr in edit mode. http://run.plnkr.co/plunks/tlWEJK/

**Comment by marcysutton** [comment]
+1 to that, I had the same issue and I'm not familiar with Plunker's URL patterns.

**Comment by hodeyp** [comment]
ok - never shared before - reading the docs now!!

**Comment by hodeyp** [comment]
does this work? http://plnkr.co/edit/tlWEJK?p=info

**Comment by ThomasBurleson** [comment]
:+1:
