### ISSUE TITLE
input(required): remove space before asterisks (required text indicator)

### ISSUE THREAD

**Issue by fmax32** [angular/material#11418]
## Bug, enhancement request, or proposal: 
Based on Material Design guidelines, there should be no space after plceholder. Guidelines here: https://material.io/design/components/text-fields.html#anatomy

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
https://stackblitz.com/edit/angular-v6uj63

#### Detailed Reproduction Steps: 
1. for an input field (like email) set "required" attribute.
2. open in browser to see that there is a space after "email" and before "`*`": "`email *`"

### What is the expected behavior?
Expected to not have space between "email" and the asterisk "`*`", like this: "`email*`"

### What is the current behavior?
There is a space after placeholder and before asterisk 

### What is the use-case or motivation for changing an existing behavior?
Following Material Design guidelines: https://material.io/design/components/text-fields.html#anatomy

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: any
- AngularJS Material: 1.1.10
- OS: any
- Browsers: any
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
N/A

**Comment by codymikol** [comment]
Just put in a PR for you 🐔

**Comment by Splaktar** [comment]
AngularJS Material currently follows the [2017 Material Design spec](https://material.io/archive/guidelines/components/text-fields.html#text-fields-layout) and not the spec that came out in 2018. 

The 2018 spec has major changes and does not specify guidelines for the full set of components that AngularJS Material supports (datepickers, etc).

The team needs to discuss and come up with a more comprehensive strategy for how we are going to handle these kinds of issues (especially when the two spec's contradict each other).

**Comment by Splaktar** [comment]
The provided Stackblitz actually references Angular Material rather than AngularJS Material. We've discussed this and we'll be sticking to the 2014-2017 MD spec for AngularJS Material, so the current implementation with a space is correct.

This does appear to be an issue with Angular Material, as seen in [this example](https://stackblitz.com/edit/angular-jehzqs?file=app/input-errors-example.html), but that issue needs to be opened at https://github.com/angular/material2/issues.
