### ISSUE TITLE
mat-slide-toggle all toggles flash on changing one

### ISSUE THREAD

**Issue by javahaxxor** [angular/material#11416]
## Bug, enhancement request, or proposal:
Bug

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
https://stackblitz.com/edit/angular-1jhujs?file=app%2Fslide-toggle-overview-example.ts

#### Detailed Reproduction Steps: 
1. create slide toggles in a loop
2. the elements that feed the loop come from firebase
3. on slide toggle, update items in firebase
4. the items that feed the loop are updated on snapshotChanges()
5. the toggled sliders flash

### What is the expected behavior?
only the slide that is toggled should move

### What is the current behavior?
all the toggled sliders reset to 'off' then to their current value
I also have a short video of it if someone is interested

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular: 6.1.2
- Angular Material: 6.4.3
- OS: 
- Browsers: Chrome

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by javahaxxor** [comment]
Oh, sorry about that

**Comment by rahulbroadview** [comment]
I am also facing same issue regarding mat-slide-toggle
