### ISSUE TITLE
Consider using Chrome headless inside of Travis

### ISSUE THREAD

**Issue by DevVersion** [angular/material#11410]
Currently this repository uses the Saucelabs license that is also being used by `angular/angular`, `angular/material2` and `angular/flex-layout`.

Since we seem to have a rate limit for Saucelabs, we should spend the resources thoroughly. AngularJS Material currently runs _three_ times on Saucelabs with just Chrome on Windows and it would be good if just Chrome Headless is being used.

That way, the tests would run more stable (we do that in Material _2_ as well), and we would have potentially less flakes for Saucelab instances that really test browsers that cannot run inside of Travis or a docker.

Also, AngularJS Material could be tested against Firefox headless.

**Comment by Splaktar** [comment]
I'm not at all familiar with how AngularJS Material is using Saucelabs. I've looked at the various config files, scripts, etc. 

It looks like our TravisCI is setup to run on Linux machines, but then it delegates to Saucelabs for all test runs to execute on Windows 10 with Chrome. This doesn't make much sense to me at all.

That said, I'm not 100% clear on what you are suggesting here. 

Are you suggesting the following?
- disable all Saucelabs usage by AngularJS Material
- configure TravisCI to run against Chrome headless on Linux
- configure TravisCI to run against Firefox headless on Linux

It looks like we previously ran IE11 via Saucelabs (`SL_IE11`) and that appears to be the only reason to keep Saucelabs around in this repo. However, we would need to re-enable IE11 and figure out what issues may need to be resolved. As we do have to support IE11, we should really have it as part of our CI if possible.

Perhaps we should look into doing the following:
- disable all Saucelabs runs of Chrome on Windows
- re-enable IE11 on Saucelabs
- configure TravisCI to run against Chrome headless on Linux
- configure TravisCI to run against Firefox headless on Linux

What do you think?

**Comment by DevVersion** [comment]
I'm suggesting that you remove Saucelabs completely and just run against Chrome headless and Firefox headless for now.

In Angular Material, we've already had to remove browsers like IE11 from Saucelabs because those no longer run stable at all. If you want to continue testing against "flaky" IE11, then that's reasonable, but I think it would be good to request a new Sauclabs license specifically for AngularJS Material.

This benefits _this_ project (more stable builds), and all other projects that currently use the Saucelabs license from Angular core (less flaky tunnels; longer queues)
