### ISSUE TITLE
autocomplete and $pristine

### ISSUE THREAD

**Issue by GlauberF** [angular/material#11423]
I'm having trouble returning $ pristine to false, when I clicked clear input ($ mdAutocompleteCtrl.clear ()), my form that has the $ pristine validation still remains true, as if nothing has changed at all.

I need some way, when I click on clear input, make my form that has the $ pristine validation, understand that it has changed the value.

I thought about getting the $ mdAutocompleteCtrl.clear () event on my controller, but I do not know how to do that.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
