### ISSUE TITLE
md-datepicker allows to enter alpha numeric characters

### ISSUE THREAD

**Issue by arun-yadav87** [angular/material#11436]
Angular material 5 date picker control is accepting special character . To resolve this I tried regex form validation but it didn't work.

I observe that  form control value doesn't accept special character and that is the reason regex validation is not working. 

please suggest any workaround . 

**Component Code** 
```ts
createForm() {
    this.clientLicenseForm = this._formBuilder.group({
      propertyId: new FormControl({ value: this.clientLicenseDetails.propertyId }, [Validators.required]),
      vendorId: new FormControl({ value: this.clientLicenseDetails.vendorId }, Validators.required),
      applicationId: new FormControl({ value: this.clientLicenseDetails.vendorApplicationId }, Validators.required),
      roles: new FormControl(''),
      expiry: new FormControl(this.clientLicenseDetails.expireDateTime, [Validators.pattern('')]),
      description: new FormControl(this.clientLicenseDetails.description, [this._commonService.noWhitespaceValidator]),
      isTestBed: new FormControl(this.clientLicenseDetails.isTestBed)
    });
```
**Html code** 
```html
 <div layout="row" class="push-top-md push-bottom-md">
            <mat-form-field flex-xs="100" flex-sm="50" flex="40" [ngClass]="!isExpiryDateValid ? 'mat-form-field-invalid':''" >
              <input matInput [matDatepicker]="picker" [min]="mindate"  placeholder="Expires" formControlName="expiry"  [(ngModel)]="clientLicenseDetails.expireDateTime">
              <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
              <mat-datepicker #picker></mat-datepicker>
            </mat-form-field>
          </div>
```
UI

![image](https://user-images.githubusercontent.com/25659893/45215549-6650cd00-b2bb-11e8-867e-426ebb842b7e.png)

**Comment by bersLucas** [comment]
md-datepicker has validation on inputs and will not update ng-model with invalid dates.

Did you mean to post this in the repo for Angular's Material?

https://github.com/angular/material2/releases

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
