### ISSUE TITLE
nav-bar: md-nav-sref renders as an href but does not update

### ISSUE THREAD

**Issue by elincognito** [angular/material#11433]
## Bug, enhancement request, or proposal: Bug

# CodePen and steps to reproduce the issue:
#### CodePen demonstrating issue 
https://codepen.io/forcewill/pen/NLgKzP

#### Detailed Reproduction Steps: 
1. 
1. 

### What is the current behavior?
This:

```html
    <md-nav-item md-nav-sref="oam.curricular-units.duc({id: {{$ctrl.selectedCurricularUnit.academicYearsCurricularUnitId}} } )"
                     name="oam.curricular-units.duc">
            <span translate>Duc</span>
        </md-nav-item>
```

renders as 
```html
<li class="md-nav-item ng-scope ng-isolate-scope" role="option" aria-selected="true" md-nav-sref="oam.curricular-units.duc({id: 725 } )" name="oam.curricular-units.duc" aria-label="Duc">
  <a class="_md-nav-button md-accent md-button md-ink-ripple md-active md-primary" ng-transclude="" ng-class="ctrl.getNgClassMap()" ng-blur="ctrl.setFocused(false)" ng-disabled="ctrl.disabled" tabindex="0" ui-sref="oam.curricular-units.duc({id: 725 } )" href="#!/39/22/curricular-units/duc/728" aria-disabled="false" style="">
    <span ng-transclude="" class="_md-nav-button-text ng-scope">
      <span translate="" class="ng-scope">Duc</span>
    </span>
    <div class="md-ripple-container" style="">
    </div>
  </a>
</li>
```

But as we can see as `$ctrl.selectedCurricularUnit.academicYearsCurricularUnitId` changes the rendered href is not updated.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.9
- AngularJS Material: 1.1.10
- AngularJS UI Router: 1.0.20
- OS: 
- Browsers:

**Comment by Splaktar** [comment]
I reformatted some of the code above to make it a little more readable. I also added the versions from the CodePen demo.

However, a number of the required questions from the issue template were left blank. Can you please fill out at least the reproduction steps and expected behavior sections?

**Comment by Splaktar** [comment]
I investigated this a bit more and I can see the following:
```html
<a class="_md-nav-button md-accent md-button md-ink-ripple md-unselected" ng-transclude="" ng-class="ctrl.getNgClassMap()" ng-blur="ctrl.setFocused(false)" ng-disabled="ctrl.disabled" tabindex="0" role="tab" aria-selected="false" ui-sref="view2({id: 11 } )" href="#!/view2/10" aria-label="View 2"><span ng-transclude="" class="_md-nav-button-text ng-scope">
      <span class="ng-scope">View 2</span>
    </span><div class="md-ripple-container" style=""></div></a>
```
In this case, the `md-nav-bar` updates to `ui-sref="view2({id: 11 } )"`. `md-nav-bar` doesn't touch the `href` attribute in this case as that is up to ui-router. 

I updated the [CodePen](https://codepen.io/Splaktar/pen/XOPwaq?editors=1010#0) to the latest ui-router and AngularJS Material `1.1.12` and this behavior remains. Please open an issue with ui-router.
