### ISSUE TITLE
material design is getting applied to the html markup with the roboto font and toolbar effect but no color to the toolbar's background.  Any answers???

### ISSUE THREAD

**Issue by prajwal78** [angular/material#1143]
![code](https://cloud.githubusercontent.com/assets/10049692/5668113/f93c2c88-9792-11e4-9b07-100f91be2e04.JPG)
![issue1](https://cloud.githubusercontent.com/assets/10049692/5668114/f93d5518-9792-11e4-940f-fadfac11222d.JPG)

**Comment by PaulMougel** [comment]
Can you provide a Plunkr or a CodePen? It will be easier for us to help you.

**Comment by prajwal78** [comment]
The code works on plnkr but no5 on my local machine. ???

**Comment by marcysutton** [comment]
Do you have any errors? A CodePen or other demo would help to diagnose your issue.

**Comment by PaulMougel** [comment]
Does the web inspector show any error in the console or in the network tab?

In case you're not familiar with development and debugging tools for browsers, here's the help for [Chrome](https://developer.chrome.com/devtools), [Firefox](https://developer.mozilla.org/en-US/docs/Tools) and [IE](http://msdn.microsoft.com/en-us/library/ie/gg589507%28v=vs.85%29.aspx).

**Comment by epelc** [comment]
Did you set a default theme? Take a look at the theme docs.

**Comment by prajwal78** [comment]
I get 404 error stating resource not loaded.

**Comment by prajwal78** [comment]
Yes I referenced a theme from angular-material/themes/blue-theme.css

**Comment by PaulMougel** [comment]
@prajwal78 Helping you this way is kinda hard. Which URL yields a 404? Again, a Plunker/CodePen will help us help you. If your code works on Plunker but not on your local machine, then you'll have to investigate your directory tree and how your server serves static files.

**Comment by marcysutton** [comment]
This is a better discussion for the [ngMaterial Forum](https://groups.google.com/forum/#!forum/ngmaterial). Please continue the discussion there. Thank you!
