### ISSUE TITLE
gesture: click events stop working on firefox mobile after calling a time intensive function

### ISSUE THREAD

**Issue by Quesstor** [angular/material#11444]
## Bug

# CodePen and steps to reproduce the issue:
Its hard to test on codepen because codepen will stop the loop execution.
#### [CodePen Demo](https://codepen.io/anon/pen/xaawQm) which demonstrates the issue: 

Here is some minimal code, please adjust the load variable, such that the loop takes at least 5 seconds to finish:

    <html lang="en">

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.8/angular-material.min.css">
    </head>

    <body ng-app="BlankApp" ng-controller="heavywork" ng-cloak>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular-animate.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular-aria.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular-messages.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.7.2/angular-route.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.1.8/angular-material.min.js"></script>

        <script type="text/javascript">
            document.body.addEventListener("click", function () { console.log("clicked"); });
            document.body.addEventListener("touchend", function () { console.log("touchend"); });

            var app = angular.module('BlankApp', ["ngRoute", "ngMaterial", "ngMessages"]);
            app.controller("heavywork", function ($scope) {
                $scope.count = 0;
                $scope.calculate = function () {
                    $scope.count += 1;
                    //Edit load here such that it takes at least 5 seconds to finish
                    var load = 1000000000;
                    for (i = 0; i < load; i++) var x = Math.sqrt(10000);
                }
            })
        </script>

        {{count}}
        <h1 ng-click="calculate()">calculate</h1>
    </body>

    </html>

#### Detailed Reproduction Steps: 
1. Adjust the load in the example code such that firefox needs at least 5 seconds to finish the loop.
2. Just click "Calculate" with firefox mobile in the example. It works once but then no ng-click (or the click eventListener) will work anymore.
Please see https://stackoverflow.com/questions/52343269/click-events-randomly-stop-working-on-firefox-mobile for more info.

### What is the expected behavior?
Some calculation (or rendering a lot of directives) should not break all ng-click functions. In fact it even breaks click events bound with plain js via `addEventListener` (see console output).

### What is the current behavior?
After calling some time intensivce function all ng-click functions are not working anymore

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.9
- AngularJS Material: 1.1.8
- OS: Android
- Browsers: Firefox
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
This bug does not occur on major browsers in desktop version. It definitly does not work on firefox mobile and i think other touche devices/browsers are affected, too.

This is the console output:
![grafik](https://user-images.githubusercontent.com/13381247/45590645-5bdaa700-b93d-11e8-8f06-b64c9717e600.png)

As you can see, first it logs "clicked" and "touchend" event. After the bug snaps in, only "touchend" event is registered.
Remove`, "ngMaterial", "ngMessages"` from the dependencies or reduce the load and the bug will not occur.
Please see https://stackoverflow.com/questions/52343269/click-events-randomly-stop-working-on-firefox-mobile for more info.

**Comment by Splaktar** [comment]
Your CodePen didn't include the AngularJS Material CSS and it mixed versions of AngularJS. So I created a new [CodePen](https://codepen.io/Splaktar/pen/vzVzJE?editors=1010#0) without those issues.

[This link](https://codepen.io/Splaktar/debug/vzVzJE) can be used for mobile testing.

**Comment by Splaktar** [comment]
I see the same thing on Chrome for Android.

You will want to disable click hijacking if you run into problems like this. 
```js
app.config(function($mdGestureProvider) {
  $mdGestureProvider.skipClickHijack();
});
```
Here's a fixed [CodePen](https://codepen.io/Splaktar/pen/Pdydxp?editors=1010#0). It can be tested on mobile [here](https://codepen.io/Splaktar/debug/Pdydxp). 

The documentation for this can be found [here](https://material.angularjs.org/1.1.10/api/service/$mdGestureProvider).
