### ISSUE TITLE
Toast Queuing 

### ISSUE THREAD

**Issue by rschmukler** [angular/material#1144]
When a toast is already showing, and another one is called to be displayed, should the existing toast be immediately dismissed, or should it stay there until the timeout, and then show the next one?

Should this be configurable?

**Comment by epelc** [comment]
I haven't seen this in android but we could also stack the notifications as they come in and dismiss them from the top with their regular timers.

**Comment by rschmukler** [comment]
Talked to the UX team on this one, the preferred behavior is:

A second toast causes the existing one to immediately start animating out.
Once the existing one has animated out, the new one animates in.

**Comment by epelc** [comment]
@rschmukler Just as a note the current behavior is the new toasts begin animating in while the old ones are animating out which makes them overlap.

**Comment by rschmukler** [comment]
@epelc yup, just fixed :+1:
