### ISSUE TITLE
Rendering multiple mat-select with any EVENT on the page when using the function in option (text section).

### ISSUE THREAD

**Issue by hassan-haghi** [angular/material#11456]
## Bug, enhancement request, or proposal:
Bug

### What is the current behavior?
When defined function  in option text, with each EVENT on the page, Select is rendered again..

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 6.1.6
- AngularJS Material:  6.4.6
- OS: Windows
- Browsers: Chrome 69.0.3497.100 (Official Build) (64-bit)
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

please run this code and look the console;

[https://stackblitz.com/edit/show-text-in-mat-option-with-function](https://stackblitz.com/edit/show-text-in-mat-option-with-function)

This problem exists in mat-table too.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by hassan-haghi** [comment]
OK, I submitted in Angular Material.
thank you
