### ISSUE TITLE
Dialog Queuing 

### ISSUE THREAD

**Issue by rschmukler** [angular/material#1145]
When a dialog is already showing, and another one is called to be displayed, should the dialogs stack, or should the showing dialog slide down and the new one slide in?

**Comment by PaulMougel** [comment]
See #698 for previous discussion.

**Comment by ThomasBurleson** [comment]
@rschmukler - do you have a URL/demo of the shrink/slideDown effect ?

**Comment by rschmukler** [comment]
Using #698 as discussion platform. Closing as duplicate.
