### ISSUE TITLE
feat(virtual-repeat-container): support horizontal scrollbar in vertical orientation

### ISSUE THREAD

**Issue by JSitjaNCR** [angular/material#11461]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Open Code Pen
1. Click button 'Go to End'

### What is the expected behavior?
Last lines rendered

### What is the current behavior?
Blank lines

### What is the use-case or motivation for changing an existing behavior?
Fix it

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.6.7
- AngularJS Material: 1.1.10 and HEAD
- OS: Windows 7, Windows 10, Ubuntu
- Browsers: Chrome 69, Firefox 62, IE, and Edge
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
This occurs when needed to add a horizontal scrollbar in md-virtual-repeat-scroller.

Fixing : **virtualRepeat.js** 
Function : **VirtualRepeatContainerController.prototype.handleScroll_**
Change line :

> if (offset === this.scrollOffset || offset > this.scrollSize - this.size) return;

To : 

> **if (offset > this.scrollSize - this.size) offset = this.scrollSize - this.size;
> if (offset === this.scrollOffset) return;**

**Comment by codymikol** [comment]
This is happening because you overwrote the angular-material classes. 

```
.md-virtual-repeat-container .md-virtual-repeat-scroller {
  overflow-x: auto;
}
```

When that css is removed everything works fine.

[Here is a working demo](https://codepen.io/codymikol/pen/rZXJPW?editors=1111)

**Comment by JSitjaNCR** [comment]
I notice that but i need to add the horizontal scrollbar in md-virtual-repeat-scroller. With the fix in VirtualRepeat.js this work fine with and without scrollbar.

**Comment by Splaktar** [comment]
I get the same behavior on both CodePens (from OP and from @codymikol) above.
<img width="331" alt="screen shot 2018-09-29 at 2 26 58 pm" src="https://user-images.githubusercontent.com/3506071/46249238-c38bfa00-c3f3-11e8-9d91-c8f8824000b0.png">

I don't see any blank lines as stated in the OP.
Is the problem that 1998 and 1999 aren't shown in the viewport?

Can you explain more about what you are trying to do with your fix?

**Comment by codymikol** [comment]
It does fail to render the virtual-scroll with that extra CSS

Ubuntu - Chrome 69

![before](https://user-images.githubusercontent.com/13606342/46249490-efa97a00-c3f7-11e8-8fc1-9dd5806db1a8.png)

If you scroll a little bit everything pops into view

![after](https://user-images.githubusercontent.com/13606342/46249500-2aabad80-c3f8-11e8-8098-f4fcf3655326.png)

**Comment by davidpolberger** [comment]
For what it's worth, this bug also manifests itself when the stylesheet is unchanged and the browser zoom is set to a value other than 100%, like 110%. (`this.scroller.scrollTop` is larger than `this.scrollSize - this.size` in `VirtualRepeatContainerController.prototype.handleScroll_` when scrolling quickly to the end, which prevents the last items from showing. Specifically, `this.scroller.scrollTop` is a fractional value slightly larger than the supposed maximum value.) This patch fixes that issue too.

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material/commit/3cf4d7440289187ff57f1f341ec78c15941141d4.
