### ISSUE TITLE
docs(pull-requests): add link to GitHub's Amending older or multiple commit messages Guide

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11473]
## Bug, enhancement request, or proposal:
Proposal

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
https://github.com/angular/material/blob/master/docs/guides/PULL_REQUESTS.md#submitting-a-pull-request

### What is the expected behavior?
We should let contributors know about the [Git amend](https://help.github.com/articles/changing-a-commit-message/#amending-older-or-multiple-commit-messages) feature for updating a commit and doing a force push to the branch. This process is much smoother than interactive rebase.

### What is the current behavior?
Going through the current steps requires contributors to deal with Git Interactive Rebase which is confusing and may be error prone for first time contributors.

### What is the use-case or motivation for changing an existing behavior?
Easier onboarding of new contributors.
Reduced maintainer support load.
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
N/A

**Comment by anabellaspinelli** [comment]
Hi @Splaktar! I think I could do this one.

Do you mean changing the section in `PULL_REQUESTS.md` about adding suggested changes to something like
```
$ git commit --amend
$ git push -f
```
?

Thanks!

**Comment by Splaktar** [comment]
Yes, that would be helpful. I guess we may want to keep the existing `-a` flag as well. So perhaps `git commit -a --amend`?

I also wanted to link to that guide from GitHub. That may also be a GitHub guide on squashing commits or interactive rebase that we could link to as well.

**Comment by Splaktar** [comment]
@jagmeetb thank you, please let me know if you have any questions.
