### ISSUE TITLE
0.7.0-rc2 build docs : Module 'angularytics' is not available!

### ISSUE THREAD

**Issue by randallmeeker** [angular/material#1147]
getting error after building docs. Seems its missing the angularytics script?

On further inspection, I can't get docs build to work at all. Its one issue after another. Assuming the new version isn't ready?

**Comment by PaulMougel** [comment]
Just run `bower install && gulp docs` and you'll be all set.

**Comment by randallmeeker** [comment]
@PaulMougel Fyi not mentioned https://github.com/angular/material#-building, but I did that initially before submitting the issue and it was not working. It worked by the end of the day.

**Comment by PaulMougel** [comment]
I see. The build instructions in the main README do not cover building the project for a development setup (i.e. reading the docs or running the unit tests).

cc @ThomasBurleson maybe that should be clear? Or should we simply make `bower install`  part of the standard set up?
