### ISSUE TITLE
When opening two dialog one after another  cdk-global-scrollblock is not getting applied

### ISSUE THREAD

**Issue by learner972** [angular/material#11476]
In the application we have three dialog to open one after another.
The issue is If we add dialogRef.close() cdk-global-scrollblock class is removed from html  for second dialog whereas if don't add dialogRef.close()  cdk-global-scrollblock  is getting applied but it causing other problems for back button handling of Dialog.

Need some help for this issue.
- Angular:  6
- AngularJS Material: 6.2.1
- OS: Windows 10
- Browsers: Chrome 69

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
