### ISSUE TITLE
dialog(multiple): backdrop problem with multiple dialogs

### ISSUE THREAD

**Issue by KZRepository** [angular/material#11470]
## Bug, enhancement request, or proposal: BUG

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Open the first dialog
2. Then open the second dialog

### What is the expected behavior?
In a nutshell, the dialog has a backdrop (a transparent white background layer) that is one z-index below the dialog.

The first dialog opens with a z-index of 50 and a backdrop of 49. The second dialog on top of it opens with a z-index of 80 and a backdrop of 79.

### What is the current behavior?
The problem is that then changes the first dialog to a z-index of 80 and a backdrop of 79. In effect, no backdrop for the second dialog.

### What is the use-case or motivation for changing an existing behavior?
Showing one dialog on top of another. The top dialog is lost on the bottom without the backdrop.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.4
- AngularJS Material: 1.1.10
- OS: Windows 10
- Browsers: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
Firefox: 62.0.2 (64-bit)
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
The md-dialog tag has an ID. The .md-dialog-container and the md-backdrop do not.

**Comment by codymikol** [comment]
Hello, You can get the behavior you'd like by specifying the parent on your dialog. Working example [here](https://codepen.io/codymikol/pen/WaQyGGl)

I like to use

` parent: document.getElementsByClassName('md-dialog-container')[0]`

Works well on double nested dialogs, not sure about triple nested.

**Comment by StretchKids** [comment]
Thanks...that w

> Hello, You can get the behavior you'd like by specifying the parent on your dialog. Working example [here](https://codepen.io/codymikol/pen/WaQyGGl)
> 
> I like to use
> 
> `parent: document.getElementsByClassName('md-dialog-container')[0]`
> 
> Works well on double nested dialogs, not sure about triple nested.

Thanks! That works.

The result is a bit bizarre internally. The md-backdrop and md-dialog-container of the second dialog are under the md-dialog-container of the first dialog. The z-indexes are still changed erroneously. both backdrops are at 79, both containers at 80.

Another workaround I was considering was at the onCompleted event cycling through the md-backdrops and md-dialog-containers and set their z-indexes starting at 49 and 50 and incrementing each by 30. It just seemed a bit of a hack. The equivalent of replacing a fork a guest dropped on the floor.

This need for using parent doesn't seem to be documented. I wonder if it was what 'parent' was created for. The designers seem to have intended incrementing z-index to solve this...but have something broken in the code that changes all the md-dialog-containers and all the md-backdrops, not just the new dialog.

**Comment by Splaktar** [comment]
I believe that this is related to https://github.com/angular/material/issues/11308 as well.

**Comment by codymikol** [comment]
@StretchKids did you ever have time to debug this issue?

**Comment by Splaktar** [comment]
Can you please test this again now that PR https://github.com/angular/material/issues/11308 got merged and released in `1.1.14`?

**Comment by Splaktar** [comment]
No response to the request to test this in a release after `1.1.14`. Assuming this is resolved in recent releases.
