### ISSUE TITLE
datepicker: support displaying a week number column 

### ISSUE THREAD

**Issue by kivnek69** [angular/material#11484]
Hello everybody, 

Is there a way to display the column of weeks numbers?
an attribute to add?
an update ?
a complete implementation ?

![image](https://user-images.githubusercontent.com/8983612/46861913-0b5b4a00-ce14-11e8-884d-df34c5337674.png)

Note : I use angular-material V1.1.9 with angularJS V1.5.9

thank's in advance

**Comment by Splaktar** [comment]
This is a duplicate of https://github.com/angular/material/issues/10003#issuecomment-364730323 which has an explanation and some ideas for implementing this in your app.
