### ISSUE TITLE
gestures: GestureStart gets stuck on android when loading complex pages, app becomes unresponsive

### ISSUE THREAD

**Issue by jpike88** [angular/material#11482]
My problem is that on more complex pages where loading times can differ, gesturestart gets permanently stuck because of whatever reason. 

The ```if``` check for a pointer keeps evaluating to true, and screw it all up.

There should be a debounce or timeout which clears the pointer, and allows normal usage to continue.

https://github.com/angular/material/blob/9be3821c57765e9a7bbcd5ace5504bc0ac1a5ea3/src/core/services/gesture/gesture.js#L654

**Comment by jpike88** [comment]
Proposed solution is to bake in a timer that counts down from 2000ms, and set the pointer to null if nothing happens.

This means if you hold on one spot without moving for more than 2000ms, the touched event won't fire. Works for me, but if you can think of a more elegant solution let me know

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template.  This gives the team the information needed to investigate the bug.

Please provide the versions of AngularJS and AngularJS Material. Also we'll need a reproducion, which I can understand may be difficult in this case. If a reproduction on CodePen or a GitHub repo is not possible, then please create a branch in your fork that includes a unit test that reproduces the issue. This will allow us to investigate.
