### ISSUE TITLE
$interimElement with $rootElement html

### ISSUE THREAD

**Issue by rschmukler** [angular/material#1148]
as mentioned by @epelc we should make sure that `$rootElement` isn't an `html` node or it will likely fail miserably

**Comment by rschmukler** [comment]
This is actually already done. Woot.

**Comment by ThomasBurleson** [comment]
@rschmukler - is should be a BODY node or a child of body right? So HEAD is also excluded.

**Comment by rschmukler** [comment]
Yes, but the code as it exists currently will catch all of this
