### ISSUE TITLE
select(multiple): adding to a form causes the form to be marked pristine

### ISSUE THREAD

**Issue by cstephe** [angular/material#11490]
## Bug, enhancement request, or proposal:
Bug

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
The codepen creates a dynamic form which uses a ng-repeat with a filter tied to an input.   Inside the ng-repeat is a list of multi select elements, which will be added and removed as the filter changes.

1) Make a change to one of the selects in the form
2) NOTICE, is dirty is set to true
3) Type into the filter to reduce the number of controls shown
4) NOTICE, is dirty is still true
5) clear the filter causing selects to be added
6) NOTICE, is dirty is set to false

### What is the expected behavior?
The form should remain dirty if it was already dirty and vice versa,
added or removing elements should not change the form state

### What is the current behavior?
Adding a md-select with the multiple option causes a side effect on the form setting it to pristine

### What is the use-case or motivation for changing an existing behavior?
Forms which are used to manage list of items typically use some type of filter to easily find and make modifications.  The issue prevents the use of these controls within a ng-repeat that uses a filter, or any other use that dynamically adds fields to a form.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.5
- AngularJS Material:  1.1.10
- OS: tested on a mac
- Browsers: tested on Chrome, 69
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

From my understanding of this reading some comments and tracing around commits and issues.  It seems that at one point a related issue was created where a form would be marked dirty  when a md-select/multiple  was added.  It looks like Instead of fixing the root cause a hack was added to modify the form to set pristine on creation of this element. After that, similar issues like mine have been reported however instead of correcting the issue they built on top of the other hack to try to limit its, using the assumption that if a model was set on it it already that it must be a clean form (obviously a very bad assumption).    
see issue: https://github.com/angular/material/issues/6556

I currently have a fix for this which delays the initial render for the multiple variant.  Which allows the element to be created without triggering a dirty change on the form.  I still consider my update a hack but its a hack without side effects.

**Comment by cstephe** [comment]
Found issue https://github.com/angular/material/issues/3933 which also relates

**Comment by Splaktar** [comment]
OK, it looks like https://github.com/angular/material/commit/09bd5a3b52f29dfe530192099d2c405f204ec3ad is the cause of this since `0.11.1`. Numerous people commented on https://github.com/angular/material/issues/3933 that this caused problems with form state side effects, but the issue was already closed. Finally, someone opened up a new issue https://github.com/angular/material/issues/6556 to track this regression.

Then PR https://github.com/angular/material/pull/6782 tried to address this problem in `1.1.0`, but it appears to have just limited the impact to `md-select` with `multiple`.

**Comment by Splaktar** [comment]
Btw, Thank you for the well researched and formulated bug report!
