### ISSUE TITLE
Sidenav css errors

### ISSUE THREAD

**Issue by mackelito** [angular/material#1149]
The sidenav should have fixed position and not absolut as it has right now.
1. Visit http://plnkr.co/edit/WO0ajt?p=preview
2. Open a sidenav
3. Scroll down

(Also the backdrop should have position fixed!) :)

**Comment by PaulMougel** [comment]
This should fix your issue: https://github.com/angular/material/issues/1092#issuecomment-68935017 and in particular [this gist](https://gist.github.com/epelc/6aa345f4496776569830).

**Comment by mackelito** [comment]
Ah.. I see.. the sidenav must be in a specific layout!
The docs on the layout needs a bit more work I guess ;)
