### ISSUE TITLE
toast: 'bindToController' set to true does not work as expected

### ISSUE THREAD

**Issue by ChaitanyaBabar** [angular/material#11499]
## Bug: 'bindToController' not working as expected.
1. Not able to access properties from parent controller in md-toast  template even if `bindToController : true`  is set.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
-  Open the Toast by Clicking on 'Show Custom Toast' , button.
- Toast will open and no message would be displayed under title 'Message Passed from Another Controller'

### What is the expected behavior?
1. When `bindToController : true`  is set , properties from the parent controller should be accessible directly with scope of md-toast.

### What is the current behavior?
1. Not able to access properties from parent controller in md-toast  template even if `bindToController : true`  is set.

### What is the use-case or motivation for changing an existing behavior?
1. Had Error in implementation  as it did not worked as mentioned in docs [here](https://material.angularjs.org/latest/api/service/$mdToast).

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: v1.6.7
- AngularJS Material: v1.1.10
- OS: Windows (N/A)
- Browsers: Chrome (N/A)
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

- ## N/A

**Comment by Splaktar** [comment]
It gets bound to the Controller, so in the Controller function it would be `this.customMessage`, it isn't bound to the `$scope`. You need to do `$scope.customMessage = this.customMessage;` to use it on the `$scope` as you are doing. [Example of this](https://codepen.io/Splaktar/pen/eQYJrY?editors=1011)

A better solution is to get rid of `$scope` completely via `controllerAs: 'ctrl'`. Here's an [example of that](https://codepen.io/Splaktar/pen/RqwRGw?editors=1010).

**Comment by ChaitanyaBabar** [comment]
@Splaktar 
Apologies for getting it wrong from the documentation  :(
Thanks for the explanation , well now understood meaning of **bound to the Controller** means '**_bound to scope of the controller_**' i.e. `this` or  the name space used in `controllerAs`.

**_Just a Thought._**
We can add the example mentioned by you [here ](https://codepen.io/Splaktar/pen/RqwRGw?editors=1010) in the docs of md-toast , that would of help for others too.

**Comment by Splaktar** [comment]
@ChaitanyaBabar OK, I'll add the use of `locals` and `bindToController` to the Custom Toast demo.
