### ISSUE TITLE
md-switch adds text selection and focus border to label by default

### ISSUE THREAD

**Issue by jadrake75** [angular/material#1150]
from skimming the material spec I didn't see anything in there that suggested that when selecting a checkbox or radio button (or md-switch) that any label text should be selected/focused.  The act of the control "turning on" or "becoming checked" indicates the status and providing focus border to label text does not seem to add value (and is annoying).

The selection of text can be removed by using

md-switch .md-label {
    user-select: none;
    -webkit-user-select: none;
}

To remove the focus box, this is a bit trickier.  Since the focus border is added via the theme, the specifity of the selector requires you to override it for any themes you are using:

md-switch.md-default-theme:focus .md-label:not(:empty) {
    border-style:none;
}

or use the dreadful !important but not have to worry about the deployed theme.

md-switch:focus .md-label:not(:empty) {
    border-style:none !important;
}

What was the reasoning for defining this focus highlight anyhow?

**Comment by marcysutton** [comment]
The reasoning is for accessibility. The focus styles in Material Design are pretty thin and not very well indicated in the spec. The decision to outline the label was made intentionally to show keyboard users where they are on the page.
