### ISSUE TITLE
datepicker: November 3rd shows up twice on Safari 12

### ISSUE THREAD

**Issue by warnerribeiro** [angular/material#11506]
## Bug:

There has been discussion in [Google Groups](https://groups.google.com/forum/#!topic/ngmaterial/cymNGOtaNro)

Specifically in the month of November 2018 the 04/11/2018 does not appear in the calendar and the 03/11/2018 is duplicated.

This problem of rederización happens in the own site of angularjs material in the link [AngularJS Material DatePicker](https://material.angularjs.org/1.1.10/demo/datepicker).

The execution took place in the safari of an iphone 7 with IOS 12.1 and mac mini with MacOs Hight Sierra Safari 12.0.1.

#### Detailed Reproduction Steps: 
1. On an iphone with IOS 12.1 or mac with High Sierra MacOs.
2. Open the site [AngularJS Material DatePicker](https://material.angularjs.org/1.1.10/demo/datepicker) in Safari browser
3. Click to view the calendar.

### What is the expected behavior?

The calendar should display on 04/11/2018 and not duplicate on 03/11/2018.

### What is the current behavior?

The calendar does not present the 04/11/2018 and the 03/11/2018 is being duplicated.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.x
- AngularJS Material: 1.1.10
- OS: MAC OS or IOS
- Browsers: Safari
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

[IOS 12.1 Safari](https://16868006707349359997.googlegroups.com/attach/53dab3b3ba05d/89ce8743-bdc6-4c82-bb02-043223dd4ad2.jpg?part=0.1&view=1&vt=ANaJVrF49Pz4TwlXmY9khGxgLMfV_RolyDw8kNIvZnAgAgmKScYDbKYJmG0IV5Chknwl3HSnn-Rv9km5MPLoDLeY3B2J80y20uT8snYdFst-pd24WZGW6UA)

[MacOs High Sierra Safari](https://16868006707349359997.googlegroups.com/attach/54775f9a8af40/Captura%20de%20Tela%202018-11-07%20a%CC%80s%2017.28.09.png?part=0.1&view=1&vt=ANaJVrEJtgTEeESAFNDfYVhqiPaOlOf4IEZ09juK9krYSmUANdtmNEv_F3YFrCS6ajlB661urz23Vpy_BcxP-WkbfS68boCm0Ww62Y9On1hS9Mo7sNq5od4)

**Comment by Splaktar** [comment]
What language and locale are you in? BR Portuguese?

I'm just using US English and here's what I see on iPhone XR with iOS 12.1:
![simulator screen shot - iphone xr - 2018-11-12 at 00 27 01](https://user-images.githubusercontent.com/3506071/48328404-b88ed100-e611-11e8-8d52-fa34a006af2c.png)

It really looks like this could be a Safari bug related to your specific locale.

**Comment by Splaktar** [comment]
Actually, this also looks like it could be an issue with Brazil DST: https://www.timeanddate.com/news/time/brazil-postpones-dst-2018.html

First it says
> The Brazilian authorities have moved the beginning of Daylight Saving Time (DST) from November 4 to November 18, 2018 to avoid interference with a nationwide university exam.

Then
> ### Update: DST Not Postponed after All
> The Brazilian authorities announced on October 15, 2018 that the beginning of Daylight Saving Time (DST) will not be postponed after all. Clocks will be advanced by 1 hour at 00:00 (12:00 midnight) on November 4, 2018, as previously planned.

**Comment by Splaktar** [comment]
Can you confirm that this doesn't happen in Chrome and/or Firefox on macOS?

**Comment by warnerribeiro** [comment]
I'm using it in Portuguese - Brazilian. This problem does not occur in chrome and firefox on mac os.

**Comment by warnerribeiro** [comment]
Do you have an answer about my problem?

**Comment by Splaktar** [comment]
[This issue](https://bugs.chromium.org/p/v8/issues/detail?id=3116) was fixed in Chromium in 2014.
But it is still an open bug for Safari. You can track it [here](https://bugs.webkit.org/show_bug.cgi?id=188001).
