### ISSUE TITLE
modeless popup in md angular

### ISSUE THREAD

**Issue by vibindaskv** [angular/material#11504]
Hi Team,

I'm currently using md-dialog to show as popup in our application.But now there has been a requirement change from buisness and they want the popup to be modeless, so that the user can minimise , drag or refer the parent window for data. Does the current version of md angular support modeless popup or any work around available for me to achieve this functionality in the current version.

Regards,
Vibin

**Comment by Splaktar** [comment]
This isn't supported with `md-dialog` at this time. However, you could implement a custom popup using your requirements via `md-panel`. `md-tooltip` is built on `md-panel` and serves as a good example of how to extend it.

Implementing the drag and drop and minimize functionality would be up to you.

In the future, please post questions to the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial).

Please limit GitHub issues to bug reports.
