### ISSUE TITLE
No nav bar with dropdown as sub bar

### ISSUE THREAD

**Issue by pengleichen** [angular/material#11514]
## Bug, enhancement request, or proposal:
enhancement request

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Can't create a Nav Bar with dropdown as sub nav bar

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.5
- AngularJS Material: 1.1.8
- OS: Window
- Browsers: Chrome

**Comment by Splaktar** [comment]
@pengleichen please provide more information. Are you asking for an enhancement to [Toolbars](https://material.io/archive/guidelines/components/toolbars.html) or our `md-nav-bar` which is based on [Tabs](https://material.io/archive/guidelines/components/tabs.html)?

Can you please link to where this behavior is demonstrated in the [Material Design spec for 2017](https://material.io/archive/guidelines/components/)?

If this isn't part of the Material Design spec, can you please provide a CodePen or drawing of what this would look like?
