### ISSUE TITLE
mat-expansion-panel not working in popover

### ISSUE THREAD

**Issue by flatbeats** [angular/material#11524]
## Bug, enhancement request, or proposal:
When using an expansion panel that is opened by a popover it doesn't work. 

# Stackblitz demo:
https://stackblitz.com/edit/angular-j2mhuc

#### Detailed Reproduction Steps: 
1. Using Angular 7, ng-bootstrap 4.0, and material 7.1
2. Create a button with a [ngbPopover] that opens a ng-template
3. Inside that template put a mat-expansion-panel

### What is the expected behavior?
Mat-expansion opens to show its content

### What is the current behavior?
If the popoverbutton is pressed the mat-expansion is opened (open emitter is triggered) but then it is immediately discarded (discard event is triggered)

### What is the use-case or motivation for changing an existing behavior?
Create an inplace form depending on different options.

### Which versions of AngularJS, Material, OS, and browsers are affected?
It seems to work when using Angular 6.1 / 7 and ng-bootstrap 2.x (Chrome / Firefox / Edge). But not with ng-bootstrap 3.x or 4.x and Angular 6.1 / 7). The Material Version seems not to matter (tried 6.1 / 7.1) so i'm not sure it is a materials bug. 
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
There are no errors in the browser

**Comment by flatbeats** [comment]
It seems to work when you use  [autoClose]="'outside'" on the button that opens the popover. I'm not sure if this is intended or not. So feel free to close the bug i think i can't do it myself.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
