### ISSUE TITLE
datepicker: filter only affects validation in month mode

### ISSUE THREAD

**Issue by Garviell** [angular/material#11525]
## Bug, enhancement request, or proposal:
Bug or enhancement i suppose.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1.  Make a datepicker 
2.  Set it to month mode
3.  Try to filter it.

### What is the expected behavior?
Filtered months become disabled

### What is the current behavior?
Filtered months just register as error states when selected

### What is the use-case or motivation for changing an existing behavior?
You have a sparse dataset of dates you want your users to select from.

Them needing to use trial and error to figure out which months are selectable by trying every one makes this feature useless for any case where not every single month is selectable.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: I've tried it on 1.5.11 and the one you guys are running on your demos.
- AngularJS Material:  1.1.^6
- OS: Any i'd guess
- Browsers: At least chrome

**Comment by Splaktar** [comment]
I updated the [CodePen](https://codepen.io/Splaktar/pen/QJBxJo?editors=1010#0) to remove some unused datepicker elements.

PR https://github.com/angular/material/pull/11526 opened to add this functionality.

**Comment by schliffer** [comment]
This fix has created another issue where at the "year" current view, months that start on days that don't pass validation are not clickable. For example, in the Datepicker demo where only weekends are selectable (https://material.angularjs.org/latest/demo/datepicker) if you go back to the "year" view, only months that start with a weekend are selectable. 

![weekends](https://user-images.githubusercontent.com/1257587/55658825-eb4d8780-57b3-11e9-90fa-581691d560bb.png)

**Comment by texperts** [comment]
yes i am also facing same issue @schliffer how did you fixed it. PLease share

**Comment by Splaktar** [comment]
@texperts it's being tracked in https://github.com/angular/material/issues/11703.
