### ISSUE TITLE
mat-table row navigation using keyboard arrow keys in angular 7.0.3

### ISSUE THREAD

**Issue by prythms** [angular/material#11523]
Is there any solution available in the latest release of Angular 7 for the below issue in mat-table.
**mat-table row navigation using keyboard arrow keys in angular 7.0.3**

eg; While pressing up arrow, mat-table should scroll one row up.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
