### ISSUE TITLE
Proper way to change input label style

### ISSUE THREAD

**Issue by demisx** [angular/material#1152]
I have this text field:

```html
<div id="email">
  <md-input-container>
    <label>Email</label>
     <input ng-model="post.email"></textarea>
   </md-input-container>
</div>
```

my app theme defined as:

```js
.config(function($mdThemingProvider) {
  $mdThemingProvider.setDefaultTheme('grey');
  $mdThemingProvider.theme('grey')
    .primaryColor('grey', {
      'hue-1': '200',
      'hue-2': '400',
      'hue-3': '800'
    })
    .accentColor('light-blue');
})
```

Everything looks great, except the floating labels. The opacity is set too low and it's making it hard to read. What would be the angular material way to change the opacity (or appearance in general) of the input text labels? Thank you.

**Comment by kloy** [comment]
@demisx you can't without writing CSS. In my opinion not having flexibility to change colors for components is a flaw in the theme system.

**Comment by demisx** [comment]
Looks like this is something that's on the roadmap already. Will use CSS for now.

**Comment by ThomasBurleson** [comment]
@demisx - Current developers are responsible for any opacity, border, or padding customizations. While full-theming support is desired, that feature will not be available until Q2.

**Comment by rschmukler** [comment]
@demisx are you referring to the color of the label when the input is focused?

@kloy regarding your statement, what sort of API do you envision that is more succinct than CSS? If we can save you time, we'd love to help. That being said, if we are just re-implementing all of the CSS selectors in JS, then I'd say that CSS is your better option.

If you want to change the color of an individual component, you can do so by defining a different theme during config, and then using that theme on the component, declaratively.

```js
app.config(function($mdThemingProvider) {
  $mdThemingProvider.theme('default')
    .primaryPalette('indigo')
    .accentPalette('pink');

  $mdThemingProvider.theme('alt')
     .primaryPalette('orange')
     .accentPalette('green');
});
```

```html
<div id="email">
  <md-input-container md-theme="alt">
    <label>Email</label>
     <input ng-model="post.email"></textarea>
   </md-input-container>
</div>
```

**Comment by demisx** [comment]
> @demisx are you referring to the color of the label when the input is focused?

@rschmukler Yes, I was referring to that and to input elements styling in general. I know I can do it currently via CSS, but then it kind of goes against the theme concept. IMHO, the styles should be tied in to themes, so if I change one, then the input styles follow along. If you could point me in the right direction to do this, I would really appreciate it. Thank you.

**Comment by rschmukler** [comment]
@demisx when you say that you change one, what do you mean?

**Comment by demisx** [comment]
@rschmukler I mean that I want my app to support multiple themes. Each theme may have different  input element styles associated with it. When I change from one theme to another, I want the input element styles to follow accordingly.

**Comment by kloy** [comment]
@demisx I am not necessarily advocating for utilizing CSS or JS for this use case. What I am advocating for is allow for default color palettes to be defined for individual components. I understand that this may deviate from the material spec where a theme is defined as a set of colors. This is however restricting when it makes sense for all inputs per say to default to the accent palette in a given app. If arbitrary color palettes could be utilized on a per component basis this would allow for more colors to be used in a given theme as well. 

When designing for multiple brands, material themes do not always work do to the restriction of a set of fixed color palettes. While I understand why Google may make this restriction for their brand, it is not a good universal rule. We run into this at my work where we white label our products and have to adapt the design to many style guides provided by partners. While we can embrace most of the material philosophy, we consistently run into barriers around color.

An alternative approach would be to leave themes how they currently work and introduce a higher level concept or potentially "brand" or "experience". This would allow combining themes to meet the goals of finer control over an experience.

**Comment by demisx** [comment]
@kloy Sounds good to me as long as all colors can be encapsulated within a theme. Working with brand teams, we also have strict guidelines on what colors to use.

**Comment by rschmukler** [comment]
At face value it seems like you might be able to achieve your desired results using multiple themes (ie. `brand-primary`, `brand-secondary` and then using `md-theme` to apply different themes to specific components).

Regarding making more things themable... In general the [Material Design Specs](google.com/design/spec/material-design/introduction.html) are pretty defined on what colors/opacities should be used things like fonts. Because the spec is opinionated, we don't make it easy for developers to overwrite those things.

If you **need** to overwrite them, we would recommend using custom CSS / SASS to overwrite the variables.

**Comment by wingoku** [comment]
@rschmukler Great solutions. However I wanna know, how can I change the default GREY color to Material Blue for example for md-input-container in unfocused state?

**Comment by rodusa** [comment]
input .mat-input-element, .ng-dirty, ng-invalid, .ng-touched label {
    color: green;
}
