### ISSUE TITLE
<audio> is not exactly site in it's flex container

### ISSUE THREAD

**Issue by zbrong** [angular/material#11533]
When setting an `<audio>` element in a flex container:`div` with `layout="column"` the `<audio>` is not rendered in the `div`. When you check the `div`'s dimension, its `height` is `0` .

I test it with angularjs material v1.1.10 and angularjs 1.7.5.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. A CodePen reproduction is **required**.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
