### ISSUE TITLE
$mdThemingProvider.theme is undefined 

### ISSUE THREAD

**Issue by aviadhahami** [angular/material#1155]
Hey ! 
This is very basic, yet I couldn't find the cause for this issue.
I'm getting :
Uncaught Error: [$injector:modulerr] Failed to instantiate module classAssign due to:
TypeError: undefined is not a function
for these lines:
"var app = angular.module("classAssign", ['ngRoute','ngMaterial']);
app.config(function ($routeProvider, $mdThemingProvider) {
    
    $mdThemingProvider.theme('default')
             .primaryColor('pink')
             .accentColor('orange');
    $routeProvider.when('/',
    {
        controller: 'landingCtrlr',
        templateUrl: 'partials/landing.html'
    }).when('/showClass',
    {
        controller: 'classCtrlr',
        templateUrl: 'partials/showClass.html'
    }).otherwise({
        redirectTo: '/'
    });
});"

what am I missing here ?

these are my dependencies :
<script src="//cdn.jsdelivr.net/hammerjs/2.0.4/hammer.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-aria.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0rc1/angular-route.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angular_material/0.6.1/angular-material.min.js"></script>

**Comment by mzbyszynski** [comment]
Try using a newer version of angular-material, like 0.7.0.rc2 or 0.7.0.rc1. I don't think themeing was implemented differently 0.6.1.

**Comment by mzbyszynski** [comment]
Whoops, sorry I had the version tags wrong. Should be 0.7.0-rc2

**Comment by fundon** [comment]
Upgrade angular-material to 0.7.0-rc2

**Comment by aviadhahami** [comment]
@fundon , @mzbyszynski  -> can I do that via CDN too ?

**Comment by fundon** [comment]
It's not released. https://developers.google.com/speed/libraries/devguide#angularmaterial

I'm also wating. :)

**Comment by epelc** [comment]
I'd suggest getting it from bower for now. The cdns are a bit behind with the releases I don't think they are automated.

**Comment by gkalpak** [comment]
@aviadhahami, not directly related to the question, but you should **always** use matching versions of angular core and "core modules" (i.e. modules maintained on the angular.js repo), e.g. `angular-animate`, `angular-aria`, `angular-route` etc.

--
<sub>`angular-1.3.8` with `angular-route-1.2.0` ? Seriously ? :stuck_out_tongue:</sub>

**Comment by aviadhahami** [comment]
@gkalpak I understood there's only this ver. for the route module :fearful:

**Comment by gkalpak** [comment]
@aviadhahami: Where is there only this ver. for the route module ?

**Comment by rschmukler** [comment]
You should use the route module that matches your version of angular, i.e. `1.3.8`. Indeed, use the bower install if you want to preview stuff before it's officially released.
