### ISSUE TITLE
autocomplete: ADA issue - screen reader reads 'Status' for value changes

### ISSUE THREAD

**Issue by jaindivya0707** [angular/material#11569]
## Bug, enhancement request, or proposal: Bug

# CodePen and steps to reproduce the issue: 
#### Detailed Reproduction Steps: 
1. Start a screen reader and tab into any autocomplete list
2. After every value in the list, 'Status' is read out.

### What is the expected behavior?
The screen reader should read the field value in the autocomplete list

### What is the current behavior?
The screen reader reads out 'status' at the end of every value in the autocomplete list

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.5.11
- AngularJS Material: 1.1.3
- Browsers: All

**Comment by jaindivya0707** [comment]
@Splaktar I am using ChromeVox version: 53.0.2784.5
I have tested with v1.1.11 on my application and I am still facing the same issue. Also I have checked it on the demo site: https://material.angularjs.org/latest/demo/autocomplete
The demo site as well reads out 'status'.

**Comment by Splaktar** [comment]
@jaindivya0707 ah yes, you will need ChromeVox 70 to have this working. It was fixed in https://crbug.com/873466 which we submitted in August.

**Comment by jaindivya0707** [comment]
@Splaktar ChromeVox latest version is 53.0.2784.5
I think you are talking about Chrome OS 70. I am using the Google Chrome Version 71.0.3578.98

With reference to the earlier ticket related to a similar issue, https://github.com/angular/material/issues/10896#issuecomment-419014210
In the above comment, it is mentioned that "It will now read the message, followed by Status on Chrome 70 with ChromeVox on a Chromebook." This is my original bug that it should not read out 'status' at the end of every value.
Please check.

**Comment by Splaktar** [comment]
Ah OK, thank you for pointing that out. I wasn't aware that ChromeVox was versioned separately from Chrome OS now that it is only fully supported on Chrome OS.

You would need to submit a bug against ChromeVox via crbug.com. As far as I know, they purposely include the "status" part at the end of all `role="status"` announcements. I believe that they also read out `alert` for `role="alert"` announcements.
