### ISSUE TITLE
select(multiple): label doesn't float and overlaps model value when control has initial values

### ISSUE THREAD

**Issue by rudzikdawid** [angular/material#11571]
## Bug 
1.1.11 https://codepen.io/anon/pen/oJooMa  
![](https://i.imgur.com/Liatjy9.png)  

1.1.10 https://codepen.io/anon/pen/zyPPMR  
![](https://i.imgur.com/oF4sSSO.png)  

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
open https://codepen.io/anon/pen/oJooMa  

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.5
- AngularJS Material: 1.1.11
- OS: Fedora 29
- Browsers: Chrome 70

**Comment by codymikol** [comment]
The specific line that seems to cause this is

 `ngModel.$render = delayedRender;`

Changing this back to 

`ngModel.$render = renderMultiple;`

Seems to fix the issue. I don't fully understand the purpose of this change yet so I'll do a little more digging.

**Comment by codymikol** [comment]
Looks like the delay prevents the class md-input-has-value from being added to the md-input-container

**Comment by codymikol** [comment]
And this can be fixed by adjusting where the md-input-has-value is evaluated within the inputCheckValue and waiting until next tick so it is in sync with the delayed render. I'll make a PR momentarily.

**Comment by codymikol** [comment]
I've fixed this with tests @Splaktar 🐔 Putting in a PR now.

**Comment by rudzikdawid** [comment]
> @rudzikdawid what is different about your CodePen as compared to the pizza example in [the docs](https://material.angularjs.org/1.1.11/demo/select) that seems to be working fine? Is it just having multiple values selected on load that causes this?

Main difference is the value of the model when component is initialized.
In docs model is empty, in my codePen i've passed model of `md-select`
```
$scope.selectedToppings = [
   'Pepperoni',
   'Mushrooms'
];
```
And then with initialized model inside controller... we can see bug in 1.1.11 release
