### ISSUE TITLE
md-checkbox: required attribute doesn't work

### ISSUE THREAD

**Issue by epelc** [angular/material#1159]
`required` and `ng-required` do not work with `md-checkbox`.

Also as a side note should we report issues that will be fixed by something else or just comment on the other issue? Ie its extremely likely #1006 will resolve this.

**Comment by marcysutton** [comment]
If there is already an open issue, to me it makes sense to add it as a comment.

**Comment by epelc** [comment]
@marcysutton Thanks I'll report it there. I don't see much of a need for this as the other issue will definitely fix this.
