### ISSUE TITLE
icon: SVG icons disappear in IE11 when reused from internal cache

### ISSUE THREAD

**Issue by rreitmann** [angular/material#11603]
## Bug, enhancement request, or proposal:
Since commit https://github.com/angular/material/commit/47527f245acc8382a69a42a07989fd5f646e9744 SVG icons which are reused from the cache (md-icons internal one) are not displayed anymore in IE11 because `transformClone` removes the `<svg>`-element and adds only the children to the dom (see https://github.com/angular/material/commit/47527f245acc8382a69a42a07989fd5f646e9744#diff-8a475bebd83d2830320cb84bceeade2cR505)

# CodePen and steps to reproduce the issue:
Just go to the docs (https://material.angularjs.org/latest/demo/icon) with IE11. Initially the SVG on the "Edit on Codepen"- and "View Source"-buttons will be visible. Click on a different demo and they will be invisible. 

### Which versions of AngularJS, Material, OS, and browsers are affected?
- AngularJS: 1.7.6 
- AngularJS Material: 1.1.11 and 1.1.12
- OS: Windows
- Browsers: IE11

**Comment by Splaktar** [comment]
It looks like you guys have a fix in https://github.com/dzhw/material/commit/c8582ea259695e5b4719d0c6e73b3294994bb6c9. Would you mind submitting a PR for it please?

**Comment by rreitmann** [comment]
PR is on the way. One signed CLA is missing...

**Comment by Splaktar** [comment]
@rreitmann thank you. I'll comment over on the PR regarding the CLA.

**Comment by Splaktar** [comment]
Just a note to say that I reproduced this on IE11 with Windows 10. I'm not sure yet why it only effects the CodePen/Code icons and not the other SVG icons on the page.
