### ISSUE TITLE
$mdToast: Do not show new toast if the content is the same

### ISSUE THREAD

**Issue by epelc** [angular/material#1160]
If there is already a toast shown with the message `xyz` we shouldn't show another toast until it is dismiss if it also has the same content(`xyz`). It creates a flickering/rapid updown animation which is very ugly.

I ran into this problem with my auth system. Since it is based on jwt I notify my app to logout by return `401 unauthorized` on any api calls. Which makes it remove my jwt from localstorage and send the user to the login page. However whenever I load my app I have to make a few api calls quickly which results in several toasts popping up all saying please relogin etc if your session has expired.

I'm looking for better ways to handle the auth check myself however It does make sense to not show a million toasts if they all have the same content as the one that is currently shown. Perhaps we should either ignore new ones or simply extend how long the current one will show.

Possibly related #1144

**Comment by gkalpak** [comment]
IMO, it is an app design matter and not something angular-material should handle. If I want to show a bunch of identical toasts, the library should let me do it (although I probably shouldn't do that "UX-wise").
Having one long-lived toast vs having several identical short-lived ones, conveys a tottally difference message to the user and the library should allow the developers to do both (and not force either upon them).

**Comment by epelc** [comment]
That makesounds sense thanks.
