### ISSUE TITLE
layout: duplicated flex styles

### ISSUE THREAD

**Issue by DigitalFuturePT** [angular/material#11609]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Open file: https://ajax.googleapis.com/ajax/libs/angular_material/1.1.12/angular-material.css
2. We can check that there is 2x the same css code for .layout-row > .flex-50 and .layout-column > .flex-50 for all flex-XX

### What is the expected behavior?
N/A

### What is the current behavior?
N/A

### What is the use-case or motivation for changing an existing behavior?
N/A

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: N/A
- AngularJS Material: At least from 1.1.9 till 1.1.12
- OS: N/A
- Browsers: N/A
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
N/A

**Comment by Splaktar** [comment]
Introduced in this PR in `1.1.9`: https://github.com/angular/material/pull/11247
Related to this PR which reverted most of the previous PR in `1.1.10`: https://github.com/angular/material/pull/11331

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11613 fixed this. Thank you for the report!
