### ISSUE TITLE
autocomplete floatingLabel should be expression

### ISSUE THREAD

**Issue by fayzaan** [angular/material#11612]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. see the floatingLabel value is not used, instead just the string 'floatingLabel' is displayed for Floating Label

### What is the expected behavior?
Should be an expression so people can pass in dynamic text, 1 good use is for internationalization.

### What is the current behavior?
its just rendering the string, so you cannot pass in a dynamic text based on language selected or something else

### What is the use-case or motivation for changing an existing behavior?
to support internationalization and to allow for a standard design throughout all input fields. 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: all
- AngularJS Material: all
- OS: all
- Browsers: all
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
that is all

**Comment by codymikol** [comment]
You're pen was invalid, this is what you're looking for: https://codepen.io/codymikol/pen/xMRbbN

**Comment by Splaktar** [comment]
Thank you @codymikol!
