### ISSUE TITLE
Set tooltip options to object

### ISSUE THREAD

**Issue by vitarunaeva** [angular/material#11611]
- AngularJS: 4
- AngularJS Material: 2.0.0-beta.10

How can I set the options of the tooltip in one place (for example, in an object and get the object when import MdTooltipModule or you can suggest another way) in this version of the package 'angular-material'.

`import {MdTooltipModule.forRoot(tooltipOptions)} from '@angular/material';
const tooltipOptions: TooltipComponent  = [
{ message="help", tooltipClass='tooltip-style'}
`

**Comment by codymikol** [comment]
It looks like you're working with angular/material2, this version of angular material is for angularjs 1.x versions.

 This is more of a general question and you'll probably find help over at [The Material2 Gitter Chat](https://gitter.im/angular/material2), if you post this as a github issue in material2, it will likely be closed as github issues are reserved for bug reports and feature requests only.

 Good luck!

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2). This repo is for AngularJS Material.
