### ISSUE TITLE
mdAutocomplete ng-required does not work with AngularJS 1.7.6

### ISSUE THREAD

**Issue by dohomi** [angular/material#11621]
#### Detailed Reproduction Steps: 
AngularJS 1.7.6 breaks the ng-required handling - the value always is true as soon ng-required="false" is set

### What is the expected behavior?
Should work like it was working with 1.7.5

### What is the current behavior?
ng-required on mdAutocomplete does not work

- AngularJS: 1.7.6
- AngularJS Material: 1.1.12
- OS: all
- Browsers: all

**Comment by dohomi** [comment]
I just found an issue which might be connected: https://github.com/angular/angular.js/issues/16814 So I will for now wait for AngularJS 1.7.7

**Comment by codymikol** [comment]
Yeah, I'd recommenced staying on 1.7.5 unless you really benefit from something in the 1.7.6 release.

**Comment by rudzikdawid** [comment]
angular@1.7.7 was released with bug fix
> ngRequired: set error correctly when inside ngRepeat and false by default (5ad4f5, #16814, #16820)
