### ISSUE TITLE
How to create Angular Material fixed column data table using Angular 5.2.5?? Are there any external Libraries to create fixed column tables. I need to get angular material 7 look and feel using angular material 5

### ISSUE THREAD

**Issue by suriyat** [angular/material#11628]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. 
1. 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular 5: 
- Angular Material 5.2: 
- OS: Windows
- Browsers:

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
