### ISSUE TITLE
What happened to the themes dir in bower-material

### ISSUE THREAD

**Issue by ricardogomes** [angular/material#1162]
Hi

Just noticed that themes are no longer available in bower-material#master.

Is there any particular reason, will they be back soon? Or is theming under major changes?

Thanks

**Comment by PaulMougel** [comment]
Related: #1110
Themes CSS files were deleted by 47f0d09e9ebd87891703fa2b7e81355ce3952a86 and are now declared programmatically.

You can also read the [theming documentation](https://material.angularjs.org/#/Theming/03_configuring_a_theme).

**Comment by ricardogomes** [comment]
@PaulMougel  cool thanks, I'm already declaring themes programmatically, but this was a new project and I was confused about the lack of the css files.
