### ISSUE TITLE
bindToController does not work in $mdPanel

### ISSUE THREAD

**Issue by EhsanKia** [angular/material#11627]
## Bug:
The `bindToController` option on mdPanel does not seem to be working. The value is properly passed as a provider, but the controller binding never happens.

# CodePen and steps to reproduce the issue:
https://codepen.io/EhsanKia/pen/bzqEew

#### Detailed Reproduction Steps: 
1. Create a panel using mdPanel
2. Set `bindToController` to true
3. Add `locals` to the config
4. Check the values on the controller after the panel is created

### What is the expected behavior?
The values are replaced by the values in `locals`

### What is the current behavior?
The values are all undefined.

### What is the use-case or motivation for changing an existing behavior?
The current behavior doesn't match the documentation.

### Which versions of AngularJS, Material, OS, and browsers are affected?
- AngularJS: 1.6.4
- AngularJS Material: 1.1.12
- OS: Debian
- Browsers: Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
This feature seems to have been added in https://github.com/angular/material/issues/7044 and there are tests verifying it here: https://github.com/angular/material/blob/master/src/components/panel/panel.spec.js#L1706

Sadly, it doesn't seem to work on my end, and I'm not sure if there's something I'm doing wrong.

**Comment by jakubmank** [comment]
I am using version 1.2.4 and it looks like this issue has returned.
