### ISSUE TITLE
md-nav-bar bug .md-focused applied to wrong button 

### ISSUE THREAD

**Issue by rudzikdawid** [angular/material#11631]
## Bug

1. https://material.angularjs.org/latest/demo/navBar
2. Click nav button  `PAGE THREE`
3. Click nav button `PAGE ONE`
4. Click nav button `PAGE TWO`
5. Click nav button  `PAGE THREE`

`<md-nav-ink-bar>` is on the correct position but class `.md-focused` is applied to wrong `button` element
```
.md-button.md-default-theme:not([disabled]).md-focused, .md-button:not([disabled]).md-focused, .md-button.md-default-theme:not([disabled]):hover, .md-button:not([disabled]):hover {
    background-color: rgba(158,158,158,0.2);
}
```
these rule should be apply to `PAGE THREE` button but it isn't
![](https://i.imgur.com/OCv0gIE.png)

**latest release where everything works fine was `1.1.10`**
https://codepen.io/anon/pen/QYqbOp?&editable=true

### What is the expected behavior?
`.md-focused` class assigned to the appropriate button

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.7
- AngularJS Material: 1.1.12 and 1.1.11
- OS: Fedora 29
- Browsers: Chrome 72, Firefox 65

**Comment by codymikol** [comment]
This has been addressed already [here](https://github.com/angular/material/pull/11600)

Original Issue [here](https://github.com/angular/material/issues/11591)
