### ISSUE TITLE
tabs: tabbing into component now takes one extra tab key press

### ISSUE THREAD

**Issue by VAK314** [angular/material#11632]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. use keyboard (tab key)

### What is the expected behavior?
The focus should be set on first tab 

### What is the current behavior?
A user navigates the page using keyboard tab key, the focus moves to "md-tabs-canvas" first and then moves to first tab element. 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: v1.6
- AngularJS Material: v1.1.12
- OS: Linux Debian
- Browsers: Google Chrome Version 72.0.3626.81 (Official Build) (64-bit) 

### Is there anything else we should know? Stack Traces, Screenshots, etc.

https://github.com/angular/material/blob/c68e7f0abf1f71ac2732725ec481b217db3ed0ac/src/components/tabs/js/tabsController.js#L705
may be condition should be ctrl.focusIndex>=0?

**Comment by codymikol** [comment]
You're going to have to elaborate a bit more on what the issue is. Your reproduction steps could apply to anything.

**Comment by VAK314** [comment]
Detailed Reproduction Steps:
1. use tab key for set focus on first TAB (md-tab)
2. Push tab key first time then focus is set on all tabs (md-tabs-canvas)
3. Push tab key second time then focus is set on first TAB. 

What is the expected behavior?

When you push tab key first time focus should be set on first TAB not on all tabs.

**Comment by Splaktar** [comment]
I cannot reproduce this on the [Tabs demo](https://material.angularjs.org/1.1.12/demo/tabs) page. The first tab key stroke goes to the first tab. Right/left arrow keys allow changing tab selection and the enter or space keys activate the selected tab.

On macOS `10.14.2 (18C54)` and Chrome `Version 71.0.3578.98 (Official Build) (64-bit)` and `Version 74.0.3694.0 (Official Build) canary (64-bit)`.

Is this only an issue on Debian Linux? Is there a different OS behavior on that platform?

**Comment by VAK314** [comment]
Because in this demo was used https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.12/angular-material.js (line 37425, function redirectFocus) 
But if you can see on this https://github.com/angular/material/blob/c68e7f0abf1f71ac2732725ec481b217db3ed0ac/src/components/tabs/js/tabsController.js#L705 (I should use this one)

function redirectFocus () has different implementation.

**Comment by VAK314** [comment]
I mean this
https://github.com/angular/material/commit/9c079aa779734cddac036b7524d5fd644ac9ad3a#diff-6abc5f5dfc7791c07e58ae9d12975621

**Comment by Splaktar** [comment]
I also tested on Chrome OS (Linux) 72.3.32 and I was not able to reproduce this issue on the docs site.

Ah OK, this isn't an issue with `1.1.12`, this is in `master`. I am able to reproduce it on https://material.angularjs.org/HEAD/demo/tabs.

**Comment by Splaktar** [comment]
OK, yep, this is a regression caused by PR https://github.com/angular/material/pull/11520. Thank you for reporting this before we released `1.1.13`!
