### ISSUE TITLE
backgroundColor attribute from mat-tab-group tag disable default ripple effect of mat-buttons inside mat-tabs tags

### ISSUE THREAD

**Issue by viniciusgouveia** [angular/material#11647]
## Bug, enhancement request, or proposal: Bug

backgroundColor attribute from mat-tab-group tag disable default ripple effect of mat-buttons inside mat-tabs tags

# Stackblitz
### What is the expected behavior?
Ripple effect is activated on button click

### What is the current behavior?
Rippe effect is not activated on button click

### What is the use-case or motivation for changing an existing behavior?
Button look disabled because he's doesn't give the visual feedback on click.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular: 7.0.2
- Angular Material: 7.3.1
- OS: Ubuntu 18.04
- Browsers: Chrome 71
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
When open stackblitz, find tab-group-basic-example.html file on /app directory

**Comment by codymikol** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by viniciusgouveia** [comment]
Sorry.
