### ISSUE TITLE
Click-event not fired from button in mat-tab

### ISSUE THREAD

**Issue by Hypenate** [angular/material#11642]
## Bug, enhancement request, or proposal:
Bug (or maybe an enhancement)

# CodePen and steps to reproduce the issue:

#### Detailed Reproduction Steps: 
I tried creating a tab that I can close by a button:
```
<ng-container *ngFor="let tab of tabs; let index = index">
      <mat-tab>
        <ng-template mat-tab-label>
          <div class="container-fluid" style="padding: 0;margin-left: 20px;">
            <div class="row">
              <div class="col" style="margin-left: 20px;">{{tab.displayName}}</div>
              <div class="col-auto" style="padding-right: 0;">
                <button style="color:black" mat-icon-button (click)="closeTab(1)">
                  <fa-icon icon="times" size="lg"></fa-icon>
                </button>
              </div>
            </div>
          </div>
        </ng-template>
        <span [ngSwitch]="tab.type">
          <div *ngSwitchCase="0" style="height: calc(100% - 30px);">
            <CSI-grid [dataSource]=" tab.dataSource" [columns]="tab.columns">
            </CSI-grid>
          </div>
          <div *ngSwitchCase="1" style="height: calc(100% - 8px);">
            <dx-dashboard></dx-dashboard>
          </div>
          <div *ngSwitchDefault>
            {{tab.type}} - This is default, should never be hit
          </div>
        </span>
      </mat-tab>
    </ng-container>
```

### What is the expected behavior?
If I click on the tab, the tab is shown (works)
If I click on the button inside the tab, the click event is thrown (doesn't work)

### What is the current behavior?
If you click the button, the tab is selected but the click-event on the button is never fired.

### What is the use-case or motivation for changing an existing behavior?
The animated is displayed correct as you can see in the screenshot.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 7.3.2
- AngularJS Material: 7.3.2
- OS: /
- Browsers: All
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

![image](https://user-images.githubusercontent.com/7478681/53010150-6c87cf80-343d-11e9-9229-e15894b0e69f.png)

**Comment by codymikol** [comment]
This is for angularjs 1.x you should check https://github.com/angular/material2/issues for issues relating to material for angular 2+

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
