### ISSUE TITLE
autocomplete: dropdown opens to the top after upgrade to 1.1.13

### ISSUE THREAD

**Issue by rreitmann** [angular/material#11656]
## Bug:
After upgrading from 1.1.12 to 1.1.13 all autocompletes open to the top instead of to the bottom.

# Steps to reproduce the issue:

#### Detailed Reproduction Steps: 
Open https://material.angularjs.org/1.1.12/demo/autocomplete and https://material.angularjs.org/1.1.13/demo/autocomplete and compare the position of the dropdown of the first autocomplete.
 
### What is the expected behavior?
Without specifying `md-dropdown-position` I expect the dropdown to open to the bottom and only if there is not enough space in the viewport open to the top...

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.7
- AngularJS Material: 1.1.13
- OS: Ubuntu
- Browsers: Chrome

**Comment by Splaktar** [comment]
The check has always defaulted to the top if there was room:

In `v1.1.12`:
https://github.com/angular/material/blob/e01f340d3e3266d1623f1ff9755ab840156be6c4/src/components/autocomplete/js/autocompleteController.js#L141-L144

In `v1.1.13`:
https://github.com/angular/material/blob/38fb9912be67c2b46d1733be00108b41c8874c00/src/components/autocomplete/js/autocompleteController.js#L144-L147

It's just that the calculation was updated as part of the fix from @marosoft for dropdowns showing up on top even when there was no room (https://github.com/angular/material/issues/10859).

We weren't able to find anything in the Material Design and HTML specs that specified this. There was some discussion of this in PR https://github.com/angular/material/pull/11629.

As you are the second person to report this, we should consider changing the default to `bottom` now that this new calculation is in place.

**Comment by rreitmann** [comment]
@Splaktar IMHO people expect a drop**down** not a "dropup" and furthermore they got used that behavior in the former versions...

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11670 is posted to address this. Please take a look and try out the CodePen or the associated js file hosted in Google Drive to verify that this solves things for you.

**Comment by rreitmann** [comment]
@Splaktar I have tested our app with the material version hosted on your Google Drive. Looks good to me :+1:
