### ISSUE TITLE
icon(svg): large icon from cache causes 100% CPU during RegEx replacement

### ISSUE THREAD

**Issue by korengal** [angular/material#11651]
## Bug

Since AngularJS Material version 1.1.11,
The site is stuck after the second opening of the dialog with the SVG icons

# CodePen and steps to reproduce the issue:
[CodePen](https://codepen.io/gal-koren/pen/WPVbgr?editors=1010)
1)Click on "CUSTOM DIALOG" button.
2)Close the dialog
3)Click again on the  "CUSTOM DIALOG" button.
4)Chrome stuck.

When I debug it I saw that the code is stuck on this function "transformClone".

issue: Chrome 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.7
- AngularJS Material:  1.1.13 , 1.1.12 , 1.1.11 
- OS: Windows
- Browsers: all

Thanks :)

**Comment by codymikol** [comment]
Not an expert with Regex, bit that's definitely causing the perf issues.

specifically

`/(.*xlink:href="#)(\w*)(".*)/g`

and

`/(.*url\(#)(\w*)(\).*)/g`

**Comment by Splaktar** [comment]
That would seem to indicate that it does eventually complete and display the dialog? I didn't wait long enough to see that. I assumed that it was causing some kind of infinite loop.

**Comment by codymikol** [comment]
I believe it would show up eventually, however I have no idea how long the RegEx would take to complete.

The ReEx it gets stuck on is 497405 characters

The related code is 

```javascript
// Inject the cacheSuffix into all instances of url(id) and xlink:href="#id".
// This use of innerHTML should be safe from XSS attack since we are only injecting the
// cacheSuffix with content from $mdUtil.nextUid which we verify is a finite number above.
clone.innerHTML = clone.innerHTML.replace(/(.*url\(#)(\w*)(\).*)/g, addCacheSuffixToId);
clone.innerHTML = clone.innerHTML.replace(/(.*xlink:href="#)(\w*)(".*)/g, addCacheSuffixToId);
```

I'm wondering if this could accomplished via querySelectorAll, but I'm thinking this had to be be some kind of IE workaround.

**Comment by codymikol** [comment]
[It's definitely quite the large SVG ](https://media.kavanu.co/appointmentTypes/1/beard-design.svg) 😛

**Comment by codymikol** [comment]
It takes longer than 250ms in Regexr and times out given the same scenario

<img width="1263" alt="screen shot 2019-02-24 at 1 19 00 pm" src="https://user-images.githubusercontent.com/13606342/53303320-0339ff00-3837-11e9-8602-80fc432d3eda.png">

**Comment by Splaktar** [comment]
Yeah, I can't reproduce this using a standard material icon like `close` ([CodePen](https://codepen.io/Splaktar/pen/wNVaeg?editors=1010)).

**Comment by codymikol** [comment]
What specifically are those RegExs doing? is that not something that querySelector is capable of?

**Comment by Splaktar** [comment]
https://github.com/angular/material/blob/7cde443325ecc7bb7370a06766d0c98a8f5981b3/src/components/icon/js/iconService.js#L504-L516

The first block is run on IE11. The second on everything else.

We need to update parts of the SVG to add the cache suffix to the `id` so that it will match the image's actual `id`, otherwise the image will be broken. It has to be string replacement of some type, I'm not aware of a `querySelector` mode that allows for DOM modification via string replacement.

**Comment by Splaktar** [comment]
https://github.com/angular/material/issues/8689 is the original issue that needed to be fixed where `id`s were getting mangled and breaking references within SVGs.

It was fixed by PR https://github.com/angular/material/pull/11342. But that caused regression https://github.com/angular/material/issues/11603 in IE11.

IE11 was fixed via PR https://github.com/angular/material/pull/11635.

**Comment by codymikol** [comment]
Why does it need to be done with a string replacement? Is it not possible to get all elements with ids and just modify them?

![image](https://user-images.githubusercontent.com/13606342/53309136-233be380-3874-11e9-8c0e-1a9d19ebd9fe.png)

**Comment by Splaktar** [comment]
In the [originally proposed fix](https://github.com/angular/material/pull/11342/commits/0959fc47f1f974f6a33891028ca9a788693e1804#diff-8a475bebd83d2830320cb84bceeade2cR475), there was more usage of `querySelectorAll`, including an incomplete set of many different queries. It only matched `url` references, but not `xlink:href` references.

**Comment by Splaktar** [comment]
Here's an example:
```html
<svg><g id="angular"></g><defs><filter id="shadow"></filter></defs><path filter="url(#shadow)"></path></svg>
```
Our caching would change `shadow` to something like `shadow_cache1`. The replacement we need to do is changing `url(#shadow)` to `url(#shadow_cache1)`. 

So it's not just a matter of querying for `[id]` attributes. You need to query for every attribute that can contain a `url` or `xlink:href` (`filter`, `stroke`, `mask`, `animate`, etc) and then do a replacement on the values of those attributes.

**Comment by Splaktar** [comment]
I wonder if we can make `replace(/(.*url\(#)(\w*)(\).*)/g, addCacheSuffixToId)` more efficient and what impact that might have. It does look like `replace("url(#" + item.id + ")", "url(#" + item.id + cacheSuffix + ")")` would be considerably more efficient. So it may be worth going back to the more verbose format (adding in a second set of queries for `xlink:href`) which is likely to offload more of the work to the browser (with better performance).

**Comment by codymikol** [comment]
I agree with that. You should be able to iterate over all ids and then all relevant svg properties within those ids, replacing the attribute value as necessary.

**Comment by Splaktar** [comment]
It looks like this handles the `id`s:
https://github.com/angular/material/blob/7cde443325ecc7bb7370a06766d0c98a8f5981b3/src/components/icon/js/iconService.js#L501-L503

Are SVG nodes limited to referring to `id`s within parent nodes?

**Comment by codymikol** [comment]
I thought that was the case, but it looks like not. 

[in this w3schools example this is not the case](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_svg_logo)

**Comment by Splaktar** [comment]
I've got a local reproduction of this set up finally. The first load does take some time (~300ms). I think that captures any normal performance delay of a larger SVG. The second opening of the dialog taking 100% CPU for 10+ minutes does not strike me as something that 'slow RegEx' would be responsible for.

**Comment by codymikol** [comment]
Set a breakpoint on the first regex, when you hit it the second time it will hang.

**Comment by Splaktar** [comment]
Yeah, it's certainly those lines that is causing the issue, commenting out both of these lines does fix the hang:
https://github.com/angular/material/blob/7cde443325ecc7bb7370a06766d0c98a8f5981b3/src/components/icon/js/iconService.js#L514-L515

I feel like there is still some kind of infinite replacement being triggered here, not just an inefficient RegEx.

**Comment by codymikol** [comment]
Hmmm, I'm going to try just running that regex by itself on the same string locally and see if I get a similar outcome.

**Comment by codymikol** [comment]
I'm fairly certain that's the issue, check out this repo [here](https://github.com/codymikol/regex-material-demol)

**Comment by Splaktar** [comment]
Yeah, that's very helpful.

I tested with the change from PR https://github.com/angular/material/pull/11465 (which changes the `id`s even the first time a SVG is used) and it does indeed cause this same issue on the first time the dialog opens.

So the first time the RegEx is triggered is when it hangs. The first time it loads, the cache replacements aren't triggered and the RegEx isn't run.

**Comment by Splaktar** [comment]
It looks like `xlink:href` is an attribute, so that should simplify that lookup to a single query, it could probably be combined with the `[id]` query. `url` is the tricky/verbose bit.

**Comment by codymikol** [comment]
I'm looking for docs on what attributes support url()

**Comment by codymikol** [comment]
[I believe this is what I'm looking for](https://www.w3.org/TR/SVG2/linking.html#processingURL-validity)

**Comment by Splaktar** [comment]
This seems to work for the `xlink:href`:
```js
    angular.forEach(clone.querySelectorAll('[*|href]:not([href])'), function(descendantElem) {
      if (descendantElem.getAttribute('xlink:href')) {
        descendantElem.setAttribute('xlink:href',
          descendantElem.getAttribute('xlink:href') + cacheSuffix);
      }
    });
```

**Comment by Splaktar** [comment]
@codymikol did you notice that anything was missing from the `url` query [here](https://github.com/angular/material/pull/11342/commits/0959fc47f1f974f6a33891028ca9a788693e1804#diff-8a475bebd83d2830320cb84bceeade2cR475)?

**Comment by codymikol** [comment]
Hmmm I'm looking at the docs and I think that list may have too much. I think the following will get all possible attributes

`angular.forEach(clone.querySelectorAll('[fill][marker][marker-start][marker-end][shape-inside][shape-subtract][stroke]');`

**Comment by codymikol** [comment]
For example can linearGradient be an attribute? From what I can tell that is an element

**Comment by codymikol** [comment]
I do see some I don't see in the docs though, like marker-smart. I need to do a little more reading.

**Comment by Splaktar** [comment]
I'm seeing another issue as well. SVG's can have a `<style>` with CSS in it. These styles can use `url()` like the one here:
```css
    .cls-17 {
      fill: url(#linear-gradient);
    }
    .cls-18 {
      fill: url(#linear-gradient-2);
    }
```
We'll need to RegEx these as I don't think that we can use `querySelectorAll` on them, plus there isn't strict formatting on the CSS, so I don't see how that could work anyway.

**Comment by Splaktar** [comment]
Yeah, here's a `linearGradient` example from this problematic SVG:
```xml
    <linearGradient id="linear-gradient_cache40" x1="70.8" y1="86.05" x2="70.91" y2="82.32"
                    gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#301010" stop-opacity="0"></stop>
      <stop offset="0.31" stop-color="#301010" stop-opacity="0.1"></stop>
      <stop offset="0.67" stop-color="#301010" stop-opacity="0.4"></stop>
      <stop offset="1" stop-color="#301010" stop-opacity="0.8"></stop>
    </linearGradient>
    <linearGradient id="linear-gradient-2_cache40" x1="33.94" y1="85.6" x2="34.04" y2="82.35"
                    xlink:href="#linear-gradient_cache40"></linearGradient>
```

**Comment by codymikol** [comment]
Yeah, but that is an element, the above example `[linearGradient="url(#' + descendantElem.id + ')"]` specifies an attribute.

**Comment by Splaktar** [comment]
Yeah, it looks like both [linearGradient](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient) and [radialGradient](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/radialGradient) can only be elements.

**Comment by codymikol** [comment]
```javascript
      urlSelector =
        '[clip-path="url(#' + descendantElem.id + ')"], ' +
        '[color-profile="url(#' + descendantElem.id + ')"], ' +
        '[src="url(#' + descendantElem.id + ')"], ' +
        '[cursor="url(#' + descendantElem.id + ')"], ' +
        '[fill="url(#' + descendantElem.id + ')"], ' +
        '[filter="url(#' + descendantElem.id + ')"], ' +
        '[image="url(#' + descendantElem.id + ')"], ' +
        '[marker="url(#' + descendantElem.id + ')"], ' +
        '[marker-smart="url(#' + descendantElem.id + ')"], ' +
        '[marker-mid="url(#' + descendantElem.id + ')"], ' +
        '[marker-end="url(#' + descendantElem.id + ')"], ' +
        '[mask="url(#' + descendantElem.id + ')"], ' +
        '[pattern="url(#' + descendantElem.id + ')"], ' +
        '[script="url(#' + descendantElem.id + ')"], ' +
        '[stroke="url(#' + descendantElem.id + ')"], ' +
        '[tref="url(#' + descendantElem.id + ')"], ' +
        '[set="url(#' + descendantElem.id + ')"], ' +
        '[use="url(#' + descendantElem.id + ')"]';
```

Anything camelCase is not going to be an attribute so I've filtered those out of that list.

**Comment by codymikol** [comment]
[This is a reference to all SVG attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute)

**Comment by Splaktar** [comment]
`marker-smart` apparently should have been `marker-start` 😁

**Comment by codymikol** [comment]
> `marker-smart` apparently should have been `marker-start` 😁

I've added it and a link to marker-smart above

**Comment by Splaktar** [comment]
These seem fairly reasonable other than `src` which I can't find any reference for:
```js
      urlSelector = '[clip-path="url(#' + descendantElem.id + ')"], ' +
        '[color-profile="url(#' + descendantElem.id + ')"], ' +
        '[cursor="url(#' + descendantElem.id + ')"], ' +
        '[fill="url(#' + descendantElem.id + ')"], ' +
        '[filter="url(#' + descendantElem.id + ')"], ' +
        '[marker-start="url(#' + descendantElem.id + ')"], ' +
        '[marker-mid="url(#' + descendantElem.id + ')"], ' +
        '[marker-end="url(#' + descendantElem.id + ')"], ' +
        '[mask="url(#' + descendantElem.id + ')"], ' +
        '[src="url(#' + descendantElem.id + ')"], ' +
        '[stroke="url(#' + descendantElem.id + ')"], ';
```

**Comment by codymikol** [comment]
Looking good to me and of course some silly method to make that easier to maintain

```javascript
var query ='color-profile,cursor,fill,filter,marker-start,marker-end,marker-mid,mask,stroke'
.split(',).reduce(function(collection, attribute) {
  return '[' + attribute + '="url(#' + descendantElem.id + ')"];
});
```

**Comment by Splaktar** [comment]
It looks like we may need to add [href](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href).

**Comment by codymikol** [comment]
> It looks like we may need to add [href](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/href).

I'm having trouble finding an example of that other than xlink:href

**Comment by Splaktar** [comment]
It mentions that `xlink:href` is deprecated in SVG2 in favor of `href`, so anywhere that `xlink:href` is used, we could also see `href`.

`flood-color` and [lighting-color](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/lighting-color) are questionable. I don't think that `iccolor` can refer to an `id` reference, but it's not 100% clear.

**Comment by codymikol** [comment]
It looks like I was wrong before about all camelCase items being elements, apparently some are definitely valid attributes [This for example](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/maskContentUnits)

**Comment by Splaktar** [comment]
I'm almost done going through them all and I just found out that a `<paint>` can be a reference (i.e. `url()`). So I think that I'll have to take one more pass.

**Comment by Splaktar** [comment]
Looks like we need to add [vector-effect](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect).

**Comment by codymikol** [comment]
I've been looking around at existing SVG libraries seeing if there are any existing FOSS solutions to this kind of search that can be "borrowed" 😉 No such luck thus far

**Comment by Splaktar** [comment]
The following seems to give us decent queries:
```js
    var svgUrlAttributes = [
      'clip-path', 'color-profile', 'cursor', 'fill', 'filter', 'href', 'marker-start',
      'marker-mid', 'marker-end', 'mask', 'stroke', 'vector-effect'
    ];

      var urlQuerySelector = '';
      for (i = 0; i < svgUrlAttributes.length; i++) {
        urlQuerySelector += '[' + svgUrlAttributes[i] + '="url(#' + descendantElem.id + ')"]';
        if (i + 1 < svgUrlAttributes.length) {
          urlQuerySelector += ', ';
        }
      }
```
Output:
```
[clip-path="url(#linear-gradient)"], [color-profile="url(#linear-gradient)"], [cursor="url(#linear-gradient)"], [fill="url(#linear-gradient)"], [filter="url(#linear-gradient)"], [href="url(#linear-gradient)"], [marker-start="url(#linear-gradient)"], [marker-mid="url(#linear-gradient)"], [marker-end="url(#linear-gradient)"], [mask="url(#linear-gradient)"], [stroke="url(#linear-gradient)"], [vector-effect="url(#linear-gradient)"]
```
```
[clip-path="url(#Layer_39)"], [color-profile="url(#Layer_39)"], [cursor="url(#Layer_39)"], [fill="url(#Layer_39)"], [filter="url(#Layer_39)"], [href="url(#Layer_39)"], [marker-start="url(#Layer_39)"], [marker-mid="url(#Layer_39)"], [marker-end="url(#Layer_39)"], [mask="url(#Layer_39)"], [stroke="url(#Layer_39)"], [vector-effect="url(#Layer_39)"]
```

**Comment by Splaktar** [comment]
Need to add [style](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/style) as well.

Then that leaves the last issue, needing to change the stylesheet mentioned in https://github.com/angular/material/issues/11651#issuecomment-466861501.

**Comment by codymikol** [comment]
It looks like the only way is going to be using a regex on each stylesheet, there seems to be no API for modifying the inner styles of the tag according to [this](https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement)

**Comment by Splaktar** [comment]
I can't find anywhere that says that there can only be one `<style>` element, so I will have to assume that there may be multiple.

**Comment by codymikol** [comment]
There can be multiple as per [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style#Multiple_style_elements)

**Comment by Splaktar** [comment]
Hooray, it works! `url()` references in `<style>` element updated as well:
```css
    .cls-17 {
      fill: url(#linear-gradient_cache40);
    }
    .cls-18 {
      fill: url(#linear-gradient-2_cache40);
    }
```

**Comment by Splaktar** [comment]
@codymikol many thanks for your help with this complex issue! I think that we both learned a lot about SVGs 😁 

PR https://github.com/angular/material/pull/11653 has been posted. I will try to do some IE11 testing tomorrow.

**Comment by korengal** [comment]
Hi,
thanks alot :)

I tried the new version (PR #11653 has been posted.)

Some SVG icons not loading on the second time (not cached correctly?)

The error is : net::ERR_INVALID_URL

For example,
this SVG:

https://media.kavanu.co/appointmentTypes/1/48788ed2c4c044b49972fa0f69fda4ba.svg

I will add some other icons for you to check:

https://media.kavanu.co/appointmentTypes/1/hair-straightener-japan.svg
https://media.kavanu.co/appointmentTypes/1/hair-straightener-brazilian.svg
https://media.kavanu.co/appointmentTypes/1/hair-straightener-organic.svg
https://media.kavanu.co/appointmentTypes/1/hair-straightener-classic.svg
https://media.kavanu.co/appointmentTypes/1/haircut-men.svg
https://media.kavanu.co/appointmentTypes/1/haircut-women.svg
https://media.kavanu.co/appointmentTypes/1/shades.svg
https://media.kavanu.co/appointmentTypes/1/shades-half-head.svg
https://media.kavanu.co/appointmentTypes/1/shades-quarter-head.svg
https://media.kavanu.co/appointmentTypes/1/7f5932767f7e40b4ae10a5a9cc6fd279.svg
https://media.kavanu.co/appointmentTypes/1/fan.svg
https://media.kavanu.co/appointmentTypes/1/hairdo.svg
https://media.kavanu.co/appointmentTypes/1/ombre.svg
https://media.kavanu.co/appointmentTypes/1/root-wash.svg
https://media.kavanu.co/appointmentTypes/1/hair-straightener-france.svg
https://media.kavanu.co/appointmentTypes/1/haircut-kids.svg
https://media.kavanu.co/appointmentTypes/1/long-fan.svg
https://media.kavanu.co/appointmentTypes/1/9c3310a9e822448692fefb08ac7a34ad.svg
https://media.kavanu.co/appointmentTypes/1/custom.svg
https://media.kavanu.co/appointmentTypes/1/beard-design.svg
https://media.kavanu.co/appointmentTypes/1/01e978b6857e46698c92c3ad9fc8baf0.svg
https://media.kavanu.co/appointmentTypes/1/14516ea90b4245a2845c353751e60b00.svg
https://media.kavanu.co/appointmentTypes/1/e123f326413d4de4a947a90627e254c5.svg
https://media.kavanu.co/appointmentTypes/1/09d25607a1f9488fb9f06cc63c698e41.svg
https://media.kavanu.co/appointmentTypes/1/47d189521d4540bfbfd8adf7d60dc19e.svg
https://media.kavanu.co/appointmentTypes/1/5ab4104dc067419c88e1e8b8425b3c9c.svg
https://media.kavanu.co/appointmentTypes/1/0262c6c180f04df7baf7e96627a80e0c.svg
https://media.kavanu.co/appointmentTypes/1/ae8ff78ec2904e408a0c738f902d13c8.svg
https://media.kavanu.co/appointmentTypes/1/ab0bea58ddcd4677bd7a0d087cb4865e.svg
https://media.kavanu.co/appointmentTypes/1/fe16f840a6364c4e960e7e17cf4043f8.svg
https://media.kavanu.co/appointmentTypes/1/07e43b152a184ec9821854cb0841f60d.svg
https://media.kavanu.co/appointmentTypes/1/ed50704e0ee343ee8789c4af476732a7.svg
https://media.kavanu.co/appointmentTypes/1/9e2155b9c25e49c484356fa4f66e6130.svg
https://media.kavanu.co/appointmentTypes/1/419b3b8fb67641faa046b3601c284369.svg
https://media.kavanu.co/appointmentTypes/1/08a5370f251143689e0bb35fd8202692.svg
https://media.kavanu.co/appointmentTypes/1/2174f3f224ff4568934f2dcf2b7b2f23.svg
https://media.kavanu.co/appointmentTypes/1/2eef45648838480baa2d78c6f971dde9.svg
https://media.kavanu.co/appointmentTypes/1/2886a94577ff4fe19e811b56bbc5f86a.svg
https://media.kavanu.co/appointmentTypes/1/3c097049deba4c3aaf9ce5f871ae812b.svg
https://media.kavanu.co/appointmentTypes/1/33a1ba59a8b040a7a606b460fbcee404.svg
https://media.kavanu.co/appointmentTypes/1/a35e701da13941439f396f8d76c41b99.svg
https://media.kavanu.co/appointmentTypes/1/e7606dc2d8c24ebeb090218debacdf8f.svg
https://media.kavanu.co/appointmentTypes/1/a75910bbcb3c43de9c6e2567701445d1.svg
https://media.kavanu.co/appointmentTypes/2/4271555322874ef4bc8a384a5b1c3a9a.svg
https://media.kavanu.co/appointmentTypes/1/10d26d935ace4c4fb68d89de7d4b9a66.svg
https://media.kavanu.co/appointmentTypes/1/30aed178bb1148b29dc6da38b5490f08.svg
https://media.kavanu.co/appointmentTypes/1/28ab72a27d8249e4929a68d27d372ae0.svg
https://media.kavanu.co/appointmentTypes/1/6478d461ea81417fa66579f23c05c605.svg
https://media.kavanu.co/appointmentTypes/1/4b4d62c6e30e4ce9b55ff24961d58888.svg
https://media.kavanu.co/appointmentTypes/1/37394875056e493a91377cdb11a9a30d.svg
https://media.kavanu.co/appointmentTypes/1/c88ec60165784feb88b4a257818dd5c3.svg
https://media.kavanu.co/appointmentTypes/1/92a20844273344809de6687f2fd05ddc.svg
https://media.kavanu.co/appointmentTypes/1/87f5ea94f0da4cc2a2e7007ceb8d922d.svg
https://media.kavanu.co/appointmentTypes/1/dcb25fe74ea74140bdc640c3108366d1.svg
https://media.kavanu.co/appointmentTypes/1/7351968e46bf495da13443793769febc.svg
https://media.kavanu.co/appointmentTypes/1/d89462dc194541d7a26ec53c239ca222.svg
https://media.kavanu.co/appointmentTypes/1/48788ed2c4c044b49972fa0f69fda4ba.svg
https://media.kavanu.co/appointmentTypes/1/0873fea4ed214bc38bb579ccd4eda5d1.svg
https://media.kavanu.co/appointmentTypes/1/fbb332475def4082b7a916e518d4dc2a.svg
https://media.kavanu.co/appointmentTypes/1/2d28fa7459e349f7bd24de4665ca90b0.svg
https://media.kavanu.co/appointmentTypes/1/6eae0f353bc64501af913b058458ebae.svg
https://media.kavanu.co/appointmentTypes/1/c9a9155a39504e0c9bb42d3940d35d29.svg
https://media.kavanu.co/appointmentTypes/1/0d7bcc093ef84d219177c2f3e1f6148c.svg
https://media.kavanu.co/appointmentTypes/1/b8d53041167741308b24309df45318be.svg
https://media.kavanu.co/appointmentTypes/1/871787cff4714d8ea3312985d6df2e1a.svg
https://media.kavanu.co/appointmentTypes/1/43673c1cb0ab4e6293babdb84aefac34.svg
https://media.kavanu.co/appointmentTypes/1/f5ceade0f1d34871a3fecc3452b93404.svg
https://media.kavanu.co/appointmentTypes/1/e2f19cd382e34ea98b49d9a6b280c6cd.svg
https://media.kavanu.co/appointmentTypes/1/9166c7af6911471a92c0b6483fb42284.svg
https://media.kavanu.co/appointmentTypes/1/028fed1f14194d9ab59a4bf4015b1d3d.svg
https://media.kavanu.co/appointmentTypes/2/92696fceb82a416c8e91a6dbb3100f8b.svg
https://media.kavanu.co/appointmentTypes/2/4b1e5360759a44108863926877d7b694.svg
https://media.kavanu.co/appointmentTypes/2/db52a82dfc8e4c56aa475da2af6193b4.svg
https://media.kavanu.co/appointmentTypes/2/f81e12b339c04696bf5e65fc53ef5c21.svg
https://media.kavanu.co/appointmentTypes/2/a5fda1658efc4ca89757faea1709a6ca.svg
https://media.kavanu.co/appointmentTypes/2/ec0aaa603a2347ddba3bb5820d55e625.svg
https://media.kavanu.co/appointmentTypes/2/46d35829eda84a03946a147f55656bfd.svg
https://media.kavanu.co/appointmentTypes/2/f1c21b135b8a4e3388b9d159ea1fc210.svg
https://media.kavanu.co/appointmentTypes/2/be675be09f484b1bb7691188efae7f66.svg
https://media.kavanu.co/appointmentTypes/2/b360591233c2430e8fb212cc1e0f91dd.svg
https://media.kavanu.co/appointmentTypes/2/a6b54e528d734b7bb566e2249804266a.svg
https://media.kavanu.co/appointmentTypes/2/fd70eae727b54376aeae6355fa9e68c4.svg
https://media.kavanu.co/appointmentTypes/2/539e65c8c92a4c4db79959c1cb8bb44d.svg
https://media.kavanu.co/appointmentTypes/2/f1640ffa2e574828946ea9356d66370b.svg
https://media.kavanu.co/appointmentTypes/2/6cad85d537ae4fb9acf8c6b4ca5cd765.svg
https://media.kavanu.co/appointmentTypes/1/c5fca4ffe1034af7b5270ed4186bc956.svg
https://media.kavanu.co/appointmentTypes/1/fb8d47f1bd7647ef845a21e8bcfdcd0d.svg
https://media.kavanu.co/appointmentTypes/1/9be15058badd48428868286ab9b923c5.svg
https://media.kavanu.co/appointmentTypes/1/33813364fad348078e7b1c89abdce4cc.svg
https://media.kavanu.co/appointmentTypes/2/d2e07815b40e4f3cacc463a4a9ccc2f0.svg
https://media.kavanu.co/appointmentTypes/2/3c2c1fe64a914063a9a16e704f875874.svg
https://media.kavanu.co/appointmentTypes/2/d2bf9fcc0d65486fb1c3384d7506e018.svg
https://media.kavanu.co/appointmentTypes/2/b874b2a6a2c6495ea74771714eb2845f.svg
https://media.kavanu.co/appointmentTypes/2/83b68149c8874ec98733f4c7b907c268.svg
https://media.kavanu.co/appointmentTypes/2/a5fcd66117854e5ba2ee3128b0cca0c9.svg
https://media.kavanu.co/appointmentTypes/2/74523da2e6d14e429482218e75584592.svg
https://media.kavanu.co/appointmentTypes/2/7c20a7eeb5fd4c668b35683f03adb6d3.svg
https://media.kavanu.co/appointmentTypes/2/92e2e4a231ee49528e620cdd595b2b68.svg
https://media.kavanu.co/appointmentTypes/2/4f346a8bf4f6460c87b72952c014a1e6.svg
https://media.kavanu.co/appointmentTypes/2/7b9614f5ded7408f9941e24416852596.svg
https://media.kavanu.co/appointmentTypes/2/aa1322edeef9435fb2eab47c80d3eb58.svg
https://media.kavanu.co/appointmentTypes/2/c9300c51cab24982acb694c25d6d60dd.svg
https://media.kavanu.co/appointmentTypes/2/d38c994c8aa6422e8aac123c0e499c7a.svg
https://media.kavanu.co/appointmentTypes/2/8ee1c949ac5545539baac133427a1499.svg
https://media.kavanu.co/appointmentTypes/1/b83df9392a1e4fd983a133ef51b47f08.svg
https://media.kavanu.co/appointmentTypes/1/a2e462cfb3c647248c4e8e47f5eccb12.svg
https://media.kavanu.co/appointmentTypes/1/8326023b1588432bb803bda842244dd0.svg
https://media.kavanu.co/appointmentTypes/2/beb974161788481698cc806cfb69980e.svg
https://media.kavanu.co/appointmentTypes/2/54eeac25e19c450b9188517b404eaf70.svg
https://media.kavanu.co/appointmentTypes/2/e362c91239e9425a9d8adf47201317f5.svg
https://media.kavanu.co/appointmentTypes/2/a5870ffadd1843fd8f6807fe934c68b8.svg
https://media.kavanu.co/appointmentTypes/2/4f41bbdfb3ce4d12a0dcfcecf4dfa2fc.svg
https://media.kavanu.co/appointmentTypes/2/93fcfe7639694bc5bbbe074c2c73076f.svg
https://media.kavanu.co/appointmentTypes/2/9fd102bec0ae4ad3a8ef14cc7f09461a.svg
https://media.kavanu.co/appointmentTypes/2/01d092226ac040dd84d73916f07215dd.svg
https://media.kavanu.co/appointmentTypes/2/f6f3dbbd101d486a841aeae8964eac50.svg
https://media.kavanu.co/appointmentTypes/2/a33a86829765498fa73a76bb4ad3f403.svg
https://media.kavanu.co/appointmentTypes/2/514901266d7b4e6a9bd6992419cad590.svg
https://media.kavanu.co/appointmentTypes/2/ce8033d0d95e4aab8ab65c3e07e7ec95.svg
https://media.kavanu.co/appointmentTypes/2/4718b95a4acd41ad89954bcdda90ac12.svg
https://media.kavanu.co/appointmentTypes/1/bdf0a92789094d688d4f11bb215c4869.svg
https://media.kavanu.co/appointmentTypes/1/f9b9c28d39ac4775a2b7c3a8cb779070.svg
https://media.kavanu.co/appointmentTypes/1/593ad8f599374c0f9abfc3d898a3e3cd.svg
https://media.kavanu.co/appointmentTypes/1/1e32ff06c0454fa9bda5262798078577.svg
https://media.kavanu.co/appointmentTypes/1/1769e026df794613b7a2066918ecbe9e.svg
https://media.kavanu.co/appointmentTypes/1/50c400a6e90c40f3bd75f720fdb28d95.svg



Thanks :))

**Comment by codymikol** [comment]
@Splaktar No problem, learned quite a bit!

**Comment by codymikol** [comment]
I was talking to someone with a lot more experience with RegEx than me and they said the issue is that the expressions are matching everything before and after  the match itself. We worked on a solution to the first regular expression and came up with

/url\(#[^\s]+?\)/gi

This seemed to work against the example I posted earlier for finding url(#someid) within the document.

**Comment by Splaktar** [comment]
The issue with the SVG from  is that it does `xlink:href="data:img/png;base64,<data>"`.

In this case, we're taking the base64 image data and corrupting it by adding `_cache48` to the end of the string. We need to only change the contents if it refers to an `id`. I've made that change and verified the fix.

**Comment by Splaktar** [comment]
Here's the [CodePen full of SVGs in a dialog](https://codepen.io/Splaktar/pen/EMPgwG?editors=1010) updated for the latest push of PR https://github.com/angular/material/pull/11653. Everything seems to be working well.
