### ISSUE TITLE
not able to create dynamic drag and drop zones

### ISSUE THREAD

**Issue by venkatesh707** [angular/material#11655]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. 
1. 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 
- AngularJS Material: 
- OS: 
- Browsers:

**Comment by venkatesh707** [comment]
Angular 7 material ,not able to create [connectedToList] value.for e.g we are not able to that #listname

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
