### ISSUE TITLE
autocomplete: calculating space for options panel

### ISSUE THREAD

**Issue by nathanael-bice** [angular/material#11661]
https://github.com/angular/material/blob/e6f4057bb5e4a50c4d3aeffffd38518ff393e1ba/src/components/autocomplete/js/autocompleteController.js#L164

When calculating the space needed for the autocomplete options, the calculation is not taking into account the shifted body positioning, when in the context of an mdDialog. This results in either the options going the wrong direction or the container being too narrow.

https://codepen.io/anon/pen/QoKOPP

**Comment by Splaktar** [comment]
This seems to be related to https://github.com/angular/material/issues/11656, possibly a duplicate.
