### ISSUE TITLE
docs: content pane should scroll to top when left menu item is clicked

### ISSUE THREAD

**Issue by gaurav5430** [angular/material#11669]
## Bug, enhancement request, or proposal:
This is a bug on the docs website.
https://material.angularjs.org

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
There is no code pen, as this issue is reproducible in the docs website.

#### Detailed Reproduction Steps: 
1.  Go to https://material.angularjs.org
2. Open the Theming panel.
3. Click on "Introduction and Terms"
4. Scroll content to bottom on the right panel.
5. Click on "Declarative Syntax" on the sidebar menu.
6. The scrollbar in the content panel stays at the bottom.

### What is the expected behavior?
The scroll bar should reset to 0.

### What is the current behavior?
The scroll bar stays at the same place as it was before selecting the new menu item

### What is the use-case or motivation for changing an existing behavior?
It is frustrating to scroll to top every time I select a new menu item.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: The docs seem to use AngularJS v1.7.6
- AngularJS Material: Latest docs: https://material.angularjs.org/latest/Theming/02_declarative_syntax
- OS: Windows
- Browsers: Chrome 72

**Comment by Splaktar** [comment]
Thank you for reporting this! It is indeed quite annoying.

It looks like this has been an issue for quite some time. This works well for our demo pages, but not for our Services, Directives, or Guides. It should be a pretty simple fix.

**Comment by gaurav5430** [comment]
Great that it is open for external contributors, I have started investigating and seem to have found an easy fix.
Hoping to submit a PR soon.
