### ISSUE TITLE
tabs: md-next-button not getting disabled in mobile devices

### ISSUE THREAD

**Issue by gauravlodha** [angular/material#11666]
**md-next-button in md-tabs is not getting disabled after navigating to last tab in mobile devices**

## Bug, enhancement request, or proposal:
Bug

# steps to reproduce the issue:
https://drive.google.com/file/d/12TNVGuELEg3gzxtvst_kFazP1AEJZ3i3/view

### What is the expected behavior?
md-next-button should get disabled when it reach to last tab

### What is the current behavior?
md-next-button not getting disabled when it reach to last tab, after clicking on last tab it getting diabled

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.7
- AngularJS Material: 1.1.13
- OS: Samsung Galaxy S9 (Android version 9 pie)
- Browsers: Chrome 72.0.3626.121

### Is there anything else we should know? Stack Traces, Screenshots, etc.
issue exist on demo itself
https://material.angularjs.org/latest/demo/tabs

**Comment by Splaktar** [comment]
I'm not able to reproduce this on my Pixel 3 with Android 9 on
- the latest Chrome stable (`73.0.3683.75`)
- Chrome Dev (`74.0.3729.11`)
- Firefox Beta 66.0b13

I'll give it a try on an iPad as well.

**Comment by gauravlodha** [comment]
@Splaktar 

I have checked on iPad and android tablet devises, it's working fine for me. I think issue is in specific mobile devices. I will try to debug the problem and will let you if I found something

**Comment by Splaktar** [comment]
No feedback provided on how to reproduce this and my previous attempts at reproducing these were unsuccessful, so I'm going to close this.
