### ISSUE TITLE
cdk-virtual-scroll-viewport: `this.viewPort._scrollStrategy._viewPort` is null

### ISSUE THREAD

**Issue by supdegrave** [angular/material#11665]
## Bug, enhancement request, or proposal:
Bug 

# CodePen and steps to reproduce the issue:
https://stackblitz.com/edit/cdk-virtual-scroll-viewport-null

#### Detailed Reproduction Steps: 
1. click "view lesson list", navigate to "/lessons"
2. scroll list so that initial items are not in view
3. click an item, navigate to "/lesson;lessonId=xxxxx"
4. click "Greetings from lesson xxxxx", navigate to "/lessons;lessonId=xxxxx"

### What is the expected behavior?
The item clicked in step 3 should smooth-scroll into view, and be displayed with a different background color. 

### What is the current behavior?
The item clicked in step 3 does not scroll into view. Manually scrolling to it shows that it is displayed with a different background color.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular: 7
- Angular Material: 7
- OS: macOS Sierra
- Browsers: Chrome Canary (74.0.3720.5), Chrome (72.0.3626.121),  Safari (12.0.3 (12606.4.5.3.1)), 
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

Step into the following call in ./src/app/lesson-list/lesson-list.component.ts (in `LessonListComponent.prototype.scrollToLessonById`): 

`this.viewPort.scrollToIndex(lessonIndex, 'smooth');`

`this.viewPort._scrollStrategy._viewPort` is null, causing the underlying `this._viewport.scrollToOffset` to not be called.

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by supdegrave** [comment]
Thanks @Splaktar. I didn't notice the references to AngularJS in the issue template. 

I don't know if this sort of mistake happens often. If so, it might be useful to update the issue template to clearly state that this repo is for AngularJS, not Angular. It would've been helpful to me to have a message that was harder to miss.

**Comment by Splaktar** [comment]
@supdegrave thank you for the feedback. PR https://github.com/angular/material/pull/11683 has been submitted to implement this.
