### ISSUE TITLE
Themes disappeared

### ISSUE THREAD

**Issue by jamm** [angular/material#1166]
In commit e90e55a931ee87ae398bb06face983b95580c343 (rc-0.7.3) all themes were removed, so now almost all of my tabs are ugly...
As a workaround, I'll try to find them in VCS history, but please restore themes or write some documentation about installing them with bower.

**Comment by jamm** [comment]
Oh, sorry, found explanation in changelog.

**Comment by PaulMougel** [comment]
For future readers: explanation can be found in this commit: 47f0d09e9ebd87891703fa2b7e81355ce3952a86; More information is also available [in the docs](https://material.angularjs.org/#/Theming/03_configuring_a_theme).
