### ISSUE TITLE
md-subheader: Broken in firefox when used with $mdDialog

### ISSUE THREAD

**Issue by epelc** [angular/material#1167]
The header has space above it on firefox. It's been like this for the last couple of versions I just forgot to report it. It appears to be some problem with how firefox handles padding.

https://material.angularjs.org/#/demo/material.components.dialog
Click on custom dialog
![dialog](https://cloud.githubusercontent.com/assets/5204642/5709053/61b99fb0-9a64-11e4-9128-0155b93d3f7a.PNG)

If you move the header above the `md-content` and disable the following selector it works in firefox.
```
.dialogdemoBasicUsage h2.md-subheader {
    margin: -24px -24px 0px;
}
```
However it doesn't work very well in chrome so we need something else. Another possible problem with this fix is that it puts the header above the scroll bar instead of next to it which may or may not be good.

**Comment by rschmukler** [comment]
This is now fixed. The scroll bar is a different issue and one that we don't have a great solution for yet... Sadly it's not a properly styleable element in most browsers...
