### ISSUE TITLE
tabs: wrong tab position when a new tab is added

### ISSUE THREAD

**Issue by Axeldorf** [angular/material#11689]
## Bug, enhancement request, or proposal:

There is an error with tabs position when you add a new tab and it does not fit and needs to be horizontally scrolled.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Go to https://material.angularjs.org/HEAD/demo/tabs
2. Go to "Dyanmic tabs" block.
3. Add a new tab with any label and any content.

### What is the expected behavior?
A new tab is created and tabs are scrolled to it. Then you can go back with the left arrow until first tab.

### What is the current behavior?
A new tab is created and tabs are scrolled to it. You cannot see any tab until you click on left arrow, then you see some tabs and you cannot go to previous tabs.

### What is the use-case or motivation for changing an existing behavior?
I want to create new tabs dynamically and I want to be able to go to first tab.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.5
- AngularJS Material: 1.1.14
- OS: Ubuntu 18.04
- Browsers: Chome v72.0.3626.119
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
This bug occurs since AngularJS Material v1.1.11, with v1.1.10 it is working correctly.

**Comment by Splaktar** [comment]
This is caused by this line in `1.1.11`
https://github.com/angular/material/blob/2b2f441c75a9abc0fb5526f6df55d6efd8db8d25/src/components/tabs/tabs.scss#L169

and this block in `1.1.12`
https://github.com/angular/material/blob/a49043d4ade6ab6a8291b245c5b4c2cfddb43c03/src/components/tabs/js/tabsController.js#L575-L580

**Comment by Splaktar** [comment]
These are both (PR https://github.com/angular/material/pull/11432 and PR https://github.com/angular/material/pull/11567) a result of the need to fix [this regression](https://github.com/angular/material/issues/10406) in IE with pagination.

**Comment by Splaktar** [comment]
OK, https://github.com/angular/material/commit/f2dbe07d8673257b1767a09f1966ac817673702e will fix this for browsers other than IE11. IE11 still needs this `999999px` hack to make pagination usable (avoid all labels being truncated to 1 character and ...).

- [ ] Investigate how to fix/disable animations on IE11 while keeping pagination working
