### ISSUE TITLE
How to replicate ink ripple effect on a custom element

### ISSUE THREAD

**Issue by MarcosPortugal** [angular/material#1169]
I would like to know how it would be possible to replicate the ink effect present on the buttons :) I also think it would be useful to have some class we could add to an element to make it have that effect, and other classes for other material properties as well. What do you think?

**Comment by marcysutton** [comment]
My only concern with opening this up would be for accessibility--it would be too easy to misuse the ink ripple on non-interactive elements (such as divs).

**Comment by epelc** [comment]
@marcysutton I also was thinking about this the other day. Currently my only need for it is on my side nav however I think you are working on refactoring the sidenav on the docs to use `md-button` and `ul` instead. So I wouldn't need this anymore.

Related #809 #842

**Comment by marcysutton** [comment]
Closing as duplicate https://github.com/angular/material/issues/809
