### ISSUE TITLE
menu-bar: md-prevent-menu-close ineffective on checkbox items

### ISSUE THREAD

**Issue by oliversalzburg** [angular/material#11707]
## Bug
`md-prevent-menu-close` can not be used if the `md-menu-item` is of `type="checkbox"`.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Open the menu
1. Check the item

### What is the expected behavior?
The menu stays open.

### What is the current behavior?
The menu closes.

### What is the use-case or motivation for changing an existing behavior?
`md-prevent-menu-close` should work consistently across menu items and it should be possible to construct a menu that doesn't close by itself, without requiring deep replication of existing functionality.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7
- AngularJS Material: 1.1.18
- OS: Windows
- Browsers: Chrome

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11710 adds this capability.

**Comment by oliversalzburg** [comment]
Awesome!
