### ISSUE TITLE
select: not refreshing selected value after ajax call

### ISSUE THREAD

**Issue by jacekg88** [angular/material#11702]
## Bug, enhancement request, or proposal:
Md-select not refreshing its selected value after ajax call (using trackBy).

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
https://codepen.io/jacekg88/pen/MRbYXG

### What is the expected behavior?
Md-select shows new selected value.

### What is the current behavior?
Md-select shows old value.

### What is the use-case or motivation for changing an existing behavior?
Updating md-selects programmatically after ajax calls.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.8
- AngularJS Material: 1.1.18
- OS: Win8.1
- Browsers: Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
-

**Comment by Splaktar** [comment]
Here's a [fixed CodePen](https://codepen.io/Splaktar/pen/vMZJYZ?editors=1010#0). It was just a matter of changing this
```js
    $scope.selected = {
      Id: result[0].Id,
      Name: result[0].Name,
    };
```

to this
```js
$scope.selectedItem = $scope.items[0];
```
