### ISSUE TITLE
Demo Docs don't appear to match code implentation

### ISSUE THREAD

**Issue by gilazo** [angular/material#1170]
First of all...  I'm new here and apologize if what I'm about to say has already been covered.  I attempted to do a search in issues to see if any results were returned that were similar to what I'm about to say.

I'm attempting to line up two text fields horizontally.  The documentation on the website shows to med-text-float elements being wrapped in a div where class="row".  When it is rendered in my browser the text fields are stacked vertically instead.

I've created a plnkr for demo purposes.

http://plnkr.co/edit/BD3Zla6NFcMALRU44Nev?p=preview

And here is the source documentation on the website.

https://material.angularjs.org/#/demo/material.components.textField

    <div ng-controller="DemoController" layout="column">
      <md-content md-theme="docs-dark">
        <form style="padding: 20px;">
          <div class="row">
            <md-text-float label="Title" ng-model="user.title"></md-text-float>
            <md-text-float label="eMail" ng-model="user.email" type="email"></md-text-float>
          </div>
        </form>
      </md-content>
    </div>
Is the documentation out of sync with the current code implementation?

**Comment by marcysutton** [comment]
Yes, this is a known issue. If you look at the landing page of the [docs](https://material.angularjs.org/#/), you can see the last-published date was 2014-12-19. We are working to resolve this as soon as possible.

**Comment by ilanbiala** [comment]
@marcysutton you guys should have Travis CI deploy a new build of the website at the last successful test run of the day or something like that? Or if you can, on every git release tag (probably better).

**Comment by gilazo** [comment]
Thanks for the follow up.  I went ahead and downloaded the 0.7.0rc and also built the github's repo for docs and followed that implementation.

That version appears to work correctly :)
