### ISSUE TITLE
icon: symbol SVG icon set doesn't work since v1.1.11

### ISSUE THREAD

**Issue by tuannguyensw** [angular/material#11705]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. The CodePen is taken directly from the official Svg Icon Sets demo at https://material.angularjs.org/latest/demo/icon#svg-icon-sets

### What is the expected behavior?
`symbol:spinner` and `symbol:angular` icons are shown, so that it shows 5 icons.
The demo for 1.1.10 works. https://material.angularjs.org/1.1.10/demo/icon#svg-icon-sets

### What is the current behavior?
Only `alarm`, `social:cake` and `social:people` are shown. There are `symbol:spinner` and `symbol:angular` in HTML result, but they are shown as blank.

### What is the use-case or motivation for changing an existing behavior?
This doesn't change existing behavior. It's a bug.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 
- AngularJS Material:  1.1.11 and above
- OS: 
- Browsers:

**Comment by Splaktar** [comment]
There do not appear to be any differences with the DOM structure and there don't appear to be any changes to the styles that cause this issue. 

After investigating some more, the root cause appears to be using `.append()` instead of `.html()`.
