### ISSUE TITLE
button stays hovered after clicking on it on mobile

### ISSUE THREAD

**Issue by UmutAkkaya** [angular/material#11715]
## Bug, enhancement request, or proposal: Bug

# CodePen and steps to reproduce the issue: https://stackblitz.com/edit/angular-wjvkkw
#### Detailed Reproduction Steps: 
1.  Go to https://stackblitz.com/edit/angular-wjvkkw
1.  Press F12 to open dev console and press the mobile view button
1. Press the button and move your cursor off the button
1. Button stays hovered over

### What is the expected behavior?
Button should turn to its original state same as in desktop view.

### What is the current behavior?
Button stays in :hover state

### What is the use-case or motivation for changing an existing behavior?
N/A

### Which versions of AngularJS, Material, OS, and browsers are affected?
Problem also happens in Angular/Material 6

- AngularJS: 7 @latest
- AngularJS Material: 7.3.7
- OS: iOS or Android (same behaviour)
- Browsers: tested in Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
N/A

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
