### ISSUE TITLE
Angular material tree freezes huge set of records, how to add virtual scroll in grand child level

### ISSUE THREAD

**Issue by sambsa** [angular/material#11717]
I have an angular mat-tree with parent child and grand child level. On clicking of child I am adding grandchild in it. But grandchild having huge data upto 4k records. Which is making tree very slow because it is extremely slow

Please note what I have tried in stackblitz:[](https://stackblitz.com/edit/angular-fkxgao?file=app/tree-flat-overview-example.ts)

I have noted virtual scroll will be the best solution in this case. And I have saw a code: [](https://stackblitz.com/edit/simplified-material-tree-with-virtual-scroll?file=app%2Ftree-flat-overview-example.ts)

But it is having virtual-scroll in whole tree level with full dataSource.
How Can add Virtual scroll in grandchild level with 10 elements at a time. Is there any way possible?

**Comment by Splaktar** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
