### ISSUE TITLE
docs(ie): Configure your theme as explained here link not working

### ISSUE THREAD

**Issue by gauravlodha** [angular/material#11713]
## Bug, enhancement request, or proposal:
Bug

# CodePen and steps to reproduce the issue:
#### [Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
Issue exist on angularjs material demo itself

https://material.angularjs.org/latest/performance/internet-explorer

#### Detailed Reproduction Steps: 
1. Go to https://material.angularjs.org/latest/performance/internet-explorer
1. Click on Configure your theme as explained here link

### What is the expected behaviour?
It should navigate to Configuring a Theme section

![image](https://user-images.githubusercontent.com/26317446/56895035-60efff00-6aa5-11e9-8f9f-f1c620df67c1.png)

### What is the current behaviour?
It gives error 404 Page Not Found

![image](https://user-images.githubusercontent.com/26317446/56895079-811fbe00-6aa5-11e9-8c07-4dd2cf50d161.png)

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.7
- AngularJS Material: 1.1.18
- OS: Window 10
- Browsers: Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
The link is not working after version 1.1.9

**Comment by Splaktar** [comment]
Verified working on [HEAD](https://material.angularjs.org/HEAD/performance/internet-explorer).
