### ISSUE TITLE
class body.md-dialog-is-showing remove when closing multiple md-dialog

### ISSUE THREAD

**Issue by viney91** [angular/material#11714]
with multiple md-dialog, class body.md-dialog-is-showing is removed even if a another md-dialog is still opened

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.

**Comment by viney91** [comment]
Can't you read ?
This issue take in one sentence.
YOU HAVE TO SPENT TIME TO RESOLVE ISSUE. USERS ARE NOT YOUR EMPLOYEES AND DONT HAVE TO SPENT TIME TO TEST YOUR PRODUCT AND SEND A "REQUIRED ISSUE".
SO GO HELL PETIT CON

**Comment by Splaktar** [comment]
@viney91 your comment is in violation of the [Angular Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md). 

Additionally, GitHub now highlights the [Contributor Guide](https://github.com/angular/material/blob/master/.github/CONTRIBUTING.md#-issue-guidelines) for all users. This guide details the process for submitting issues and using the issue template. Additionally, the guide requests that you check for duplicates before submitting an issue.

This issue appears to be related to https://github.com/angular/material/issues/11308 and https://github.com/angular/material/issues/11470.

This issue appears to be a duplicate of https://github.com/angular/material/issues/10548.

**Comment by ThomasBurleson** [comment]
@Splaktar - Thank you for your incredibly reasonable response. And thank you for your continued support for this amazing OSS: AngularJS Material.
