### ISSUE TITLE
Remove $mdMedia watch listener

### ISSUE THREAD

**Issue by rschmukler** [angular/material#1172]
$mdMedia uses the window `resize` event. This isn't necessary with media queries apparently! Who knew? ( @shyndman knew )

**Comment by shyndman** [comment]
:+1:

**Comment by shyndman** [comment]
Ref: https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList#addListener()

**Comment by epelc** [comment]
+1 I use this for my sidenav

**Comment by ajoslin** [comment]
Oh nice!

**Comment by ajoslin** [comment]
Closed via 8a0411fd431384eaf8aa898ea1c83252cd1c3533
