### ISSUE TITLE
Limited tooltip's width truncates a part of long text without spaces

### ISSUE THREAD

**Issue by jewelsmu** [angular/material#11734]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Create e.g. a string input with very long name and without spaces (e.g., "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
2. Hover at entered string input to raise a tooltip

### What is the expected behavior?
Tooltip shouldn't truncate a part of text input, and value should be fully visible in the tooltip (max width of a tooltip shouldn't be limited or should be increased to bigger width)

### What is the current behavior?
Tooltip truncates a part of text input, and value isn't fully visible in the tooltip (max width of a tooltip is about 268 px) - http://prntscr.com/nutdt9

### What is the use-case or motivation for changing an existing behavior?
This should help users of applications, that have long texts without spaces with tooltips, to see full names of texts in the tooltip (now it's not possible)

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.
- AngularJS Material: 1.
- OS: 
- Browsers: 
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
http://prntscr.com/nutdt9

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. A CodePen demo is required along with specifying the versions of AngularJS and AngularJS Material that you are using.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
