### ISSUE TITLE
chips: disabled property is not working with mat-chip item

### ISSUE THREAD

**Issue by MosALs** [angular/material#11738]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. when putting disabled property on mat-chip , it should be disabled . 

### What is the expected behavior?
disable the chip item if disabled = true

### What is the current behavior?
disabled = true is not working  

### What is the use-case or motivation for changing an existing behavior?
need to use chips instead of buttons as it has a nice shape , we want to be able to control the chip item as we want .

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular 7: 1.
- Angular Material: 1.
- OS: windows 10 
- Browsers: google chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
no

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. A CodePen reproduction is required for all new issue reports.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
