### ISSUE TITLE
@input panelClass not working on mat-menu in angular material.

### ISSUE THREAD

**Issue by AmyeeTechnology** [angular/material#11732]
## Bug, enhancement request, or proposal:
Bug

#panelClass attribute property of <mat-menu> not working issue:

**demonstrates the issue:** 
I have a requirement where i want to apply custom class next to cdk-overlay-pane class when i open mat-menu for that i also read the official documents of angular material menu. but i'm not able to apply custom class next to dynamic cdk-overlay-pane even though there is mention [https://material.angular.io/components/menu/api](url) that we can override @panelClass attribute but it does't work for.

#### Detailed Reproduction Steps: 
1. Take mat-menu in component.
2. Create Custom css class in component.
3. and use panelClass Property on mat-menu and assign your custom class to it.

### What is the expected behavior?
        it should apply my custom class next to cdk-overlay-pane when i open <mat-menu></mat-menu>

### What is the current behavior?
       right now i'm not able to apply custom class next to cdk-overlay-pane class  when i open <mat-menu></mat-menu>

### Which versions of AngularJS, Material, OS, and browsers are affected?

- Angular: 7.1.
- Angular Material: 7.3.
- OS: Win10
- Browsers: Chrome
 
### please check out below screen short
![panelClassBug](https://user-images.githubusercontent.com/45948207/58334688-b974ab00-7e5d-11e9-8f54-b6b3e329badd.PNG)
hots, etc.

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
