### ISSUE TITLE
Croatian letters

### ISSUE THREAD

**Issue by nstepan** [angular/material#11731]
Uppercase croatian letters are cropped in Google Chrome.

![image](https://user-images.githubusercontent.com/8127849/58306656-76362000-7dfc-11e9-8ab1-31788e01d683.png)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
