### ISSUE TITLE
mdButton: Add mini fab

### ISSUE THREAD

**Issue by mzbyszynski** [angular/material#1173]
It would be great to support the mini floating action button specified in the [material spec](http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button)
![minifab](https://cloud.githubusercontent.com/assets/2288896/5715309/199bb10a-9aa5-11e4-952b-17cfa155aeab.png)

**Comment by ilanbiala** [comment]
should probably just be `class="md-mini"`, no?
