### ISSUE TITLE
Looks like there is an issue in md-select with Checkboxes.

### ISSUE THREAD

**Issue by rahimnagori** [angular/material#11730]
Hi,
There is an UI issue in material select input. See the screenshot attached. I want the width to be fixed. Currently the width gets increased if select more checkboxes.
Can be generated at official URL.
https://material.angularjs.org/latest/demo/select
![image](https://user-images.githubusercontent.com/42448371/58305421-a938dd80-7e15-11e9-8b41-2c2d5059c3ef.png)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
