### ISSUE TITLE
nav-bar: clicking tab when focused tab isn't visible on the page scrolls to focused tab

### ISSUE THREAD

**Issue by KaeMoNee** [angular/material#11747]
## Bug, enhancement request, or proposal:

Bug

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Small window size with which it is impossible to view the first and the last element in mdNavBar
2. Move scroll bar to the last element
3. Click on the last element

### What is the expected behavior?
It will redirect to desired place.

### What is the current behavior?
Triggered focus for the first element and scroll bar goes back to the first one. User cannot click on the last element.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.8
- AngularJS Material: 1.1.18
- OS: Windows 10
- Browsers: Chrome, Firefox. (Might be others as well)
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
I could make a workaround for my case via 2 ways:
1) without mdNavBar modification and with condition that after it will refresh page
```javascript
  function removeBlur() {
    var navItem = document.querySelector('li.md-nav-item[name="' + $scope.currentNavItem + '"] a');
    if (navItem) {
      var elItem = angular.element(navItem);
      elItem.blur();
      $timeout(function() {
        elItem.focus();
        elItem.off('blur');
      })
    } else {
      $timeout(removeBlur);
    }
  }
  $timeout(removeBlur);
```
2) with mdNavBar modification via directive
```javascript
directive('navbarOverflowed', function() {
  return {
    restrict: 'A',
    require: ['^mdNavBar'],
    link: {
      post: function(scope, element, attrs, controllers) {
        var mdNavBar = controllers[0];
        if (mdNavBar) {
          // Copied from 1.1.18 angular-material
          mdNavBar._moveFocus = function(oldTab, newTab) {
            if (oldTab) { // !!! was without controlling oldTab as it has to be defined. To fix issue I had to place additional check here
              oldTab.setFocused(false);
            }
            newTab.setFocused(true);
          };

          // Copied from 1.1.18 angular-material
          mdNavBar._updateTabs = function(newValue, oldValue) {
            var self = this;
            var tabs = this._getTabs();
            var sameTab = newValue === oldValue;
          
            if (!tabs) {
              return;
            }
          
            var oldIndex = -1;
            var newIndex = -1;
            var newTab = this._getTabByName(newValue);
            var oldTab = this._getTabByName(oldValue);
          
            if (oldTab) {
              oldTab.setSelected(false);
              oldIndex = tabs.indexOf(oldTab);
            }
          
            if (newTab) {
              newTab.setSelected(true);
              newIndex = tabs.indexOf(newTab);
            }
          
            this._$timeout(function() {
              self._updateInkBarStyles(newTab, newIndex, oldIndex);
              if (newTab && !sameTab) { // !!! was if (newTab && oldTab && !sameTab)
                self._moveFocus(oldTab, newTab);
              }
            });
          };

          mdNavBar._$timeout(function () {
            mdNavBar._getTabs().forEach(function (mdNavItemController) {
              angular.element(mdNavItemController.getButtonEl()).off('blur');
            });
          });
        }
      }
    }
  }
});
```

Is it needed to have ng-blur on element?
Why should it not run moveFocus if bar has been initialized with given selected tab? mdNavItem has _selected true while _focused false after initialization because of it.

P.S. My first issue, I'm ready to be criticized \o/

**Comment by Splaktar** [comment]
It looked like this was regression from PR https://github.com/angular/material/pull/11600 in `1.1.13`, but [this `1.1.12` CodePen](https://codepen.io/Splaktar/pen/ZdBZZK) shows that this was an issue prior to that.

Digging deeper, this appears to be a regression in `1.1.11` due to PR https://github.com/angular/material/pull/11494.

**Comment by Splaktar** [comment]
Many thanks for the detailed report and efforts towards a workaround/solution!

**Comment by Splaktar** [comment]
[This CodePen](https://codepen.io/Splaktar/pen/KKPbvQK) demonstrates that this is a problem even when `md-content` is not present.

**Comment by Splaktar** [comment]
This is caused by
https://github.com/angular/material/blob/ec9aa25be2c0bd462a49a1e593075ed6ca19c8ea/src/components/navBar/navBar.js#L597-L601
which is also critical to allowing left/right/up/down keyboard navigation of nav items after tabbing into the component. Without this, if there is a horizontal scrollbar, tabbing in and pressing left/right/up/down will scroll the scrollbar and not move to different nav items.

There doesn't appear to be a way to differentiate a `FocusEvent` from tabbing into the component or clicking on a nav item.

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11798 fixes this.

In the meantime, the workaround is to use the keyboard to select the nav item (up/down/left/right arrows to move and space/enter to select).
