### ISSUE TITLE
tooltip: $mdGestureProvider.disableAll() throws error In IE11 when tooltips try to open

### ISSUE THREAD

**Issue by gauravlodha** [angular/material#11745]
#### Detailed Reproduction Steps: 
1.  Disable mdGestureProvider in IE
1.  It throws error  TypeError: Object doesn't support property or method 'contains'

### What is the expected behaviour?
It should not throw an error in IE11

### What is the current behaviour?
TypeError: Object doesn't support property or method 'contains'

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.8
- AngularJS Material: 1.1.19
- OS: Windows 10
- Browsers: IE11
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

![image](https://user-images.githubusercontent.com/26317446/59491475-7332ca80-8ea4-11e9-88c9-640a08c064a6.png)

**Comment by Splaktar** [comment]
Can you please provide a CodePen reproduction? I know that IE can't use normal CodePen, but it can view the debug/fullscreen view of CodePen for testing.

**Comment by gauravlodha** [comment]
@Splaktar 
CodePen link:  https://s.codepen.io/gauravlodha/debug/VJjXqd/jVApoyBjpYRr

**Comment by Splaktar** [comment]
The debug view in CodePen can apparently expire. I tracked down the actual [CodePen here](https://codepen.io/gauravlodha/pen/VJjXqd) and created [a fork](https://codepen.io/Splaktar/pen/xogmER) and new [debug view](https://s.codepen.io/Splaktar/debug/xogmER/bZrQWNPpvmVk).

There is an extra reproduction step that isn't mentioned in the OP:
- you need to hover over the button before the errors are generated

This is due to the error being triggered by the tooltip.

Here's the full set of errors that I see
```js
TypeError: Object doesn't support property or method 'contains'
   at d.prototype._fetchContentElement (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:8227)
   at d.prototype._prepareContentElement (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:6722)
   at d.prototype.compile (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:6594)
   at s.prototype._compile (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:287676)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:288240)
   at q (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.8/angular.min.js:142:60)
   at s.prototype._createPanel (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:288171)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.
Possibly unhandled rejection: mdPanel: Panel does not exist yet. Call open() or attach().
```

**Comment by Splaktar** [comment]
This was introduced in `1.1.2` via PR https://github.com/angular/material/pull/9551.

The problematic line is https://github.com/angular/material/commit/dfe1a006cc57f94cfcbb8de0b419049e158b62a4#diff-badbc38934ba287f41f88d2e2276e98bR295.

[MDN's Docs](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains) on `Node.contains()` seem to indicate that this should be supported. But in the IE11 debugger, `document.contains` is clearly undefined. However, `document.body.contains` appears to be defined and appears to function properly.

**Comment by gauravlodha** [comment]
> The debug view in CodePen can apparently expire. I tracked down the actual [CodePen here](https://codepen.io/gauravlodha/pen/VJjXqd) and created [a fork](https://codepen.io/Splaktar/pen/xogmER) and new [debug view](https://s.codepen.io/Splaktar/debug/xogmER/bZrQWNPpvmVk).
> 
> There is an extra reproduction step that isn't mentioned in the OP:
> 
> * you need to hover over the button before the errors are generated
> 
> This is due to the error being triggered by the tooltip.
> 
> Here's the full set of errors that I see
> 
> ```js
> TypeError: Object doesn't support property or method 'contains'
>    at d.prototype._fetchContentElement (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:8227)
>    at d.prototype._prepareContentElement (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:6722)
>    at d.prototype.compile (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:6594)
>    at s.prototype._compile (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:287676)
>    at Anonymous function (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:288240)
>    at q (https://ajax.googleapis.com/ajax/libs/angularjs/1.7.8/angular.min.js:142:60)
>    at s.prototype._createPanel (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.js:7:288171)
>    at Anonymous function (https://ajax.googleapis.com/ajax/libs/angular_material/1.1.19/angular-material.min.
> Possibly unhandled rejection: mdPanel: Panel does not exist yet. Call open() or attach().
> ```

My bad, I thought it was on click, I didn't debug well I guess :(

**Comment by Splaktar** [comment]
No problem, many thanks for the report!

**Comment by codymikol** [comment]
It looks like there is a polyfill within mdGestureHandler that doesn't get instantiated when gestures are disabled because of an early return.

Either we can move the polyfill above the early return, or put it somewhere that makes more sense. It looks like there is a TODO stating this should be moved into $mdUtil.

If that's the way to go I'd be happy to make a PR replacing instances of document.contains with something along the lines of $mdUtil.documentContains if that works for you @Splaktar

**Comment by Splaktar** [comment]
@codymikol good catch! Let me see if I can update my PR to take advantage of this information.

**Comment by Splaktar** [comment]
@codymikol OK, I've updated PR https://github.com/angular/material/pull/11749. Please take a look.

**Comment by codymikol** [comment]
LGTM 🐔
