### ISSUE TITLE
demo website is gone

### ISSUE THREAD

**Issue by Jame0527** [angular/material#11741]
![image](https://user-images.githubusercontent.com/17266789/59015015-8de7bc80-8870-11e9-84ba-d82f77d7d252.png)

**Comment by Splaktar** [comment]
https://material.angularjs.org/latest/ is working fine for me. Are you in China?

What browser are you using?
Is this still an issue?

**Comment by Splaktar** [comment]
It seems to be working, there are no other reports of this issue, and there hasn't been a response to my questions.
