### ISSUE TITLE
autocomplete: md-autoselect not setting ngModel value when input blurred by click

### ISSUE THREAD

**Issue by p3pp8** [angular/material#11748]
Hello, i'm experiencing an issue with the `mdAutocomplete` component using `md-autoselect` attribute. When i fill the input with a string that matches an item(or a part of an item) and then i click with the mouse to give focus to another input, the first matched item is not auto-selected and the `ngModel` remains undefined but this is not happening when i give focus to another input component using the `TAB` key or by selecting one of the matched items, in these cases the `ngModel` is filled correctly.

Angular 1.7.8, AngularJS Material 1.1.19, Chrome  75.0.3770.90 64bit on Mac OS X 10.13.6.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Thank you for adding reproduction steps, but can you please add a CodePen that demonstrates this issue?

**Comment by Splaktar** [comment]
No CodePen or other debuggable reproduction demo provided.
