### ISSUE TITLE
select(multiple): checkboxes do not appear when using ng-multiple="true"

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11759]
## Bug

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
https://codepen.io/Splaktar/pen/YoOEMm?editors=1010#0

#### Detailed Reproduction Steps: 
1. Open the select menu
1. Note that there are no checkboxes, but you can select multiple options

### What is the expected behavior?
Checkboxes appear for multiple select options.

### What is the current behavior?
PR https://github.com/angular/material/pull/7455 added checkboxes for options in a multiple select, but it did not account for the `ng-multiple` case which is undocumented and has no tests.

### What is the use-case or motivation for changing an existing behavior?
Consistency. If you use `multiple` you get checkboxes, if you use `ng-multiple="true"` or some other truthy expression, you get no checkboxes.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.5.5+
- AngularJS Material: 1.1.0-1.1.19
- OS: macOS
- Browsers: Chrome 75
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

`multiple`:

![Screen Shot 2019-07-05 at 18 07 53](https://user-images.githubusercontent.com/3506071/60746924-df5a9880-9f4f-11e9-9aae-09c9eff09e0f.png)

`ng-multiple="true"`:

![Screen Shot 2019-07-05 at 18 07 27](https://user-images.githubusercontent.com/3506071/60746925-dff32f00-9f4f-11e9-8287-e861f4446e18.png)

I ran into this inconsistency while working on a11y issues: https://github.com/angular/material/issues/10967 and https://github.com/angular/material/issues/10748.

**Comment by marosoft** [comment]
@Splaktar isn't it related to #9705?

**Comment by Splaktar** [comment]
@marosoft yes, I forgot about that one, thank you! I'll close this one out as that issue lays out why `ng-multiple` support is not documented or tested (it was removed from AngularJS in `1.2.0`). It makes sense to leave that one planned for `1.2.0` of AngularJS Material since it's a breaking change.
