### ISSUE TITLE
Broken building with material-tools

### ISSUE THREAD

**Issue by norkunas** [angular/material#11751]
## Bug, enhancement request, or proposal:

Bug

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
None

#### Detailed Reproduction Steps: 
1. Use https://github.com/angular/material-tools

### What is the expected behavior?
Should build properly.

### What is the current behavior?
When building distribution files with material-tools builder it throws `ReferenceError: navigator is not defined`.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.8
- AngularJS Material: 1.1.19.
- OS: Any
- Browsers: -
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
Navigator check was updated in https://github.com/angular/material/commit/244619a

**Comment by Splaktar** [comment]
Thank you for the report.

Does something like the following fix it for you locally?
```js
if (navigator) {
  var userAgent = navigator.userAgent || navigator.vendor || window.opera;
  var isIos = userAgent.match(/ipad|iphone|ipod/i);
  var isAndroid = userAgent.match(/android/i);
}
```

**Comment by norkunas** [comment]
With your sample it still throws, but this works:
```js
if (window.navigator) {
  var userAgent = window.navigator.userAgent || window.navigator.vendor || window.opera;
  var isIos = userAgent.match(/ipad|iphone|ipod/i);
  var isAndroid = userAgent.match(/android/i);
}
```
