### ISSUE TITLE
Elements inside elements

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1176]
When a user makes a request that should disable the form, I'd also like to but a progress bar inside the button in addition to disabling it. It seems however that the styles and positioning do not support elements inside md-button. Is there any way around this?

**Comment by epelc** [comment]
Not an exact fix for what you want but you could make use of [ngProgress](https://github.com/rstacruz/nprogress) and just disable the button. It gives you a youtube style loading bar at the top of your screen that auto hides when it isn't active.

**Comment by robertmesserle** [comment]
I created a quick example for this: http://codepen.io/robertmesserle/pen/08aeedfefa14b9d535ac46716ff65aa9?editors=110

Is this what you had in mind?

**Comment by ilanbiala** [comment]
@robertmesserle yep that's pretty much what I'm looking for. Is having md-element in another md-element possible across the board?

**Comment by robertmesserle** [comment]
It should be fine in most cases.  When styling some md-elements (ie. md-button), you have to look at the generated code, though. (For example, we generate a `<button>` tag with a class of `md-button` in place of the original `md-button` element.)
