### ISSUE TITLE
autocomplete: change md-escape-options default to 'clear'

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11767]
## Proposal

# CodePen and steps to reproduce the issue:
#### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which demonstrates the issue: 
https://material.angularjs.org/1.1.19/demo/autocomplete

#### Detailed Reproduction Steps: 
1. Click the first autocomplete
1. type `a`
1. press the down arrow
1. press the Escape key

### What is the expected behavior?
The pop-up is closed and the input is cleared. Focus remains on the autocomplete's input.

This maps to using `md-escape-options="clear"`, but this isn't currently the default behavior.

### What is the current behavior?
The pop-up is closed and the input is cleared. The autocomplete's input is blurred resulting in focus being sent to the `body` in Chrome.

This is related to our API `md-escape-options`:
> Override escape key logic. Default is `blur clear`. Options: `blur, clear, none`.

### What is the use-case or motivation for changing an existing behavior?
Align with the [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html)

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.8
- AngularJS Material: 1.1.19
- OS: macOS
- Browsers: Chrome 75
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
We would like feedback from users and developers on whether this change in the default `Escape` key behavior would be problematic.

We plan to create a PR for this and base our decision to move forward with it on the results of the g3 presubmit and user/developer feedback.

**Comment by marosoft** [comment]
@Splaktar Just FYI. I just checked this in the latest version and it looks like the behavior has already changed in [HEAD](https://material.angularjs.org/HEAD/demo/autocomplete).

[v1.1.20](https://material.angularjs.org/1.1.20/demo/autocomplete) is still the same as v1.1.19

**Comment by Splaktar** [comment]
@marosoft in `HEAD`, we set `md-escape-options="clear"` in the demo.

What do you think of this behavior? Should what you see in `HEAD` (`clear`) be the default or should the `1.1.20` behavior (`blur clear`) be the default?

**Comment by marosoft** [comment]
@Splaktar to me the bahavior in `HEAD` is more consistent and I prefer it over the previous one. Whenever you interact with the autocomplete input field it shows you the list. This is when you: click on the field, use tab to focus the field and when you press Esc key.

In `1.1.20` the list does not appear when you click on the input field but it does when you use tab to focus the field. As we know, the list disappears after pressing Esc key.
