### ISSUE TITLE
erro compile angularCompilerOptions

### ISSUE THREAD

**Issue by GlauberF** [angular/material#11764]
![Captura de Tela_selecionar área_20190723150659](https://user-images.githubusercontent.com/11314585/61736542-b3675180-ad5c-11e9-8a9a-a1ddd4f84e08.png)

![Captura de Tela_selecionar área_20190723151433](https://user-images.githubusercontent.com/11314585/61736550-b8c49c00-ad5c-11e9-8180-feff097f60ae.png)

![Captura de Tela_selecionar área_20190723151415](https://user-images.githubusercontent.com/11314585/61736564-bf531380-ad5c-11e9-8a5f-74e0a12c3e8d.png)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
