### ISSUE TITLE
mat-chip :: Can not set tabindex of angular material chips

### ISSUE THREAD

**Issue by CharlieUPB** [angular/material#11773]
## Bug, feature request, or proposal:

It appears there is no way to set the tabindex attribute on Angular Material chips

### What is the expected behavior?
Setting the tabindex attribute on an Angular Material chip with tabindex="0" should stick.

### What is the current behavior?
The tabindex attribute is overridden by the Angular Material chip component to be "-1" always.

### What is the use-case or motivation for changing an existing behavior?
I have the use case for a list of chips to be navigated with tab instead of arrow keys.

### Which versions of AngularJS, Material, OS, and browsers are affected?

ALL
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

No.

**Comment by codymikol** [comment]
Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
