### ISSUE TITLE
theme: colors not available outside of framework components

### ISSUE THREAD

**Issue by oliversalzburg** [angular/material#11772]
## Bug, enhancement request, or proposal:

Theme classes, like `md-warn` should be applicable to any element.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Create an arbitrary element, like a `span` and apply any of the theme color classes.

### What is the expected behavior?
The element is colored according to the theme.

### What is the current behavior?
It isn't.

### What is the use-case or motivation for changing an existing behavior?
The declared theme should affect all areas of the application that the developer sees fit. The current behavior forces them to duplicate functionality, by creating additional styles which aren't under control of the AngularJS Material theming support.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7
- AngularJS Material: 1.19
- OS: All
- Browsers: All

**Comment by Splaktar** [comment]
You can use [md-colors](https://material.angularjs.org/latest/demo/colors) to do this. Here's a [demo](https://codepen.io/Splaktar/pen/YmOgWP?editors=1100).

Also note how the theme changes to the dark background contrast color (white) instead of the light background contrast color (black) on the darker backgrounds:
![Screen Shot 2019-08-09 at 13 42 27](https://user-images.githubusercontent.com/3506071/62798195-b461e800-baab-11e9-8d21-276183f0e595.png)

**Comment by oliversalzburg** [comment]
Seems like it gets complicated when trying to apply a style conditionally. 🤔

In my current approach (with custom CSS), I was simply using `ng-class="{'md-warn': vm.shouldWarn}"`. I replaced that with `md-colors="{'color' : '{{vm.shouldWarn ? 'warn' : ''}}'}"`. But now I get an error `mdColors: couldn't find '' in the palettes.` in the case where the style shouldn't be applied.

**Comment by Splaktar** [comment]
Here's [a demo](https://codepen.io/Splaktar/pen/mNNRBR?editors=1010#0) where there are two examples
- `md-colors` is used
- `$mdColors.getThemeColor('warn')` is used

Which style to pick depends upon how much logic you want in your template.

**Comment by oliversalzburg** [comment]
Awesome. Thank you so much for your effort.
