### ISSUE TITLE
autocomplete: clicking the scrollbar in IE closes the suggestions pop-up

### ISSUE THREAD

**Issue by nathanael-bice** [angular/material#11776]
## Bug

# CodePen and steps to reproduce the issue:
#### CodePen Demo which demonstrates the issue:
https://codepen.io/nathanaelbice/pen/OJLRWOx

#### Detailed Reproduction Steps: 
1. Click into the autocomplete
2. Search if needed
3. Try to click on the scrollbar for the results, either the bar or the arrows 

### What is the expected behavior?
The results will scroll

### What is the current behavior?
When clicking the scrollbar of the results for the `mdAutocomplete`, the results should not close immediately.

### What is the use-case or motivation for changing an existing behavior?
Users cannot scroll without the mouse unless they use the mouse wheel

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.8
- AngularJS Material: 1.1.18
- OS: Windows
- Browsers: IE

**Comment by Splaktar** [comment]
I tested this on Windows 10. Edge, Edge Chromium, Chrome, and Firefox all worked as expected. I only saw this issue with IE11.

![ie11-version](https://user-images.githubusercontent.com/3506071/68074298-ed8abb00-fd6f-11e9-90d5-d54f124f03e6.png)
