### ISSUE TITLE
slider: unable to drag slider after grunt upgrade from 0.4.5 to 1.0.4

### ISSUE THREAD

**Issue by kslo88** [angular/material#11788]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
Dev-dependencies in package.json before upgrading.
"grunt": "~0.4.4",
    "grunt-angular-templates": "^0.5.4",
    "grunt-autoprefixer": "~0.7.2",
    "grunt-build-control": "~0.4.0",
    "grunt-concurrent": "~0.5.0",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-concat": "~0.4.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-htmlmin": "~0.2.0",
    "grunt-contrib-imagemin": "~0.7.1",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-uglify-es": "git://github.com/gruntjs/grunt-contrib-uglify.git#harmony",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-dom-munger": "^3.4.0",
    "grunt-env": "~0.4.1",
    "grunt-express-server": "~0.4.17",
    "grunt-google-cdn": "~0.4.0",
    "grunt-include-source": "^1.0.0",
    "grunt-injector": "~0.5.4",
    "grunt-karma": "~0.8.2",
    "grunt-mocha-test": "~0.10.2",
    "grunt-newer": "~0.7.0",
    "grunt-ng-annotate": "^0.2.3",
    "grunt-node-inspector": "~0.1.5",
    "grunt-nodemon": "~0.2.0",
    "grunt-open": "~0.2.3",
    "grunt-protractor-runner": "^1.1.0",
    "grunt-rev": "~0.1.0",
    "grunt-shell": "^1.3.0",
    "grunt-svgmin": "~0.4.0",
    "grunt-usemin": "~2.1.1",
    "grunt-wiredep": "~1.8.0",
    "jit-grunt": "^0.5.0",
    "jshint-stylish": "~0.1.5"

Dev-dependencies in package.json after upgrade.
"grunt": "^1.0.4",
    "grunt-angular-templates": "^1.1.0",
    "grunt-autoprefixer": "^3.0.4",
    "grunt-build-control": "^0.7.1",
    "grunt-concurrent": "^3.0.0",
    "grunt-contrib-clean": "^2.0.0",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-cssmin": "^3.0.0",
    "grunt-contrib-htmlmin": "^3.1.0",
    "grunt-contrib-imagemin": "^3.1.0",
    "grunt-contrib-jshint": "^2.1.0",
    "grunt-contrib-uglify-es": "^3.3.0",
    "grunt-contrib-watch": "^1.1.0",
    "grunt-dom-munger": "^3.4.0",
    "grunt-env": "^1.0.1",
    "grunt-express-server": "^0.5.4",
    "grunt-include-source": "^1.0.0",
    "grunt-injector": "^1.1.0",
    "grunt-newer": "^1.3.0",
    "grunt-ng-annotate": "^3.0.0",
    "grunt-nodemon": "^0.4.2",
    "grunt-open": "^0.2.4",
    "grunt-rev": "^0.1.0",
    "grunt-shell": "^3.0.1",
    "grunt-svgmin": "^6.0.0",
    "grunt-usemin": "^3.1.1",
    "grunt-wiredep": "^3.0.1",
    "jit-grunt": "^0.10.0",
    "jshint-stylish": "~0.1.5",
    "load-grunt-tasks": "^3.5.0",
    "open": "^6.4.0",
    "requirejs": "^2.3.6",
    "should": "^13.2.3",
    "time-grunt": "^2.0.0"

No version changes in angular and angularjs-material.
angular: 1.5.8
angular-material: 1.1.0-rc5

### What is the expected behavior?
Should be able to use md-slider without issues.

### What is the current behavior?
Unable to drag the slider after upgrading grunt from 0.4.5 to 1.0.4

### What is the use-case or motivation for changing an existing behavior?
Node upgrade required dev-dependencies to be upgraded.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.5.8
- AngularJS Material: 1.1.0-rc5
- OS: Centos7
- Browsers: Chrome.Safari, Firefox
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
Tried upgrading angularjs to 1.7.8 and angularjs material to 1.1.20. Yet with the upgraded version of node and grunt, unable to drag md-slider.

**Comment by Splaktar** [comment]
This really looks like an application-specific problem and not a bug with AngularJS Material.

Can you please provide a CodePen reproduction or a link to an AngularJS Material docs page where this can be reproduced and debugged?

Can you reproduce this on any other OS apart from Centos7?
You mention the Safari browser, but that browser doesn't run on Centos.

Can you try downgrading each dev dependency one at a time to isolate which one is causing this?

**Comment by kslo88** [comment]
The server runs in centos7. Tested this by accessing the app outside of Centos7. Accessed the app via MacOS - Chrome/Firefox/Safari and was able to see the problem

If I downgrade grunt to 0.4.4, md-slider starts to work. But I need to downgrade all the grunt prefixed dependencies as well eg:grunt-angular-templates, grunt-build-control, etc.

I'm finding it difficult to narrow down on the dependency which is causing this because higher version of the grunt prefixed dependencies don't work with grunt 0.4.4. The app starts up only if I upgrade all/downgrade all grunt packages.

Will try to provide a Codepen demo.

**Comment by Splaktar** [comment]
So your project was likely actually running `grunt@0.4.5`. It doesn't look like the point releases after Grunt `1.0.0` are likely to have caused any issues.

It's most likely related to one of the plugins that you are using.

Can you try disabling each of the tasks in your pipeline one at a time to see if you can isolate the issue? i.e. disable just `htmlmin`, then just `uglify-es`, etc.

**Comment by Splaktar** [comment]
No further feedback nor demo has been provided.
