### ISSUE TITLE
How to show highlight error in md-input-container when click submit

### ISSUE THREAD

**Issue by hengsokly** [angular/material#1178]
- Now I have updated material then I update my code like that
```
<md-input-container>
    <label>Last Name</label>
    <input name="lastName" ng-model="lastName" required>
    <div ng-messages="userForm.lastName.$error" ng-show="userForm.lastName.$dirty">
      <div ng-message="required">This is required!</div>
    </div>
  </md-input-container>
```
- It will highlight on the input when I dirty the field; however, I want to click on submit button and show highlight on the input even I don't dirty that required field.

**Comment by EladBezalel** [comment]
Can you provide plunker please?

**Comment by hengsokly** [comment]
This is my plunker 
http://plnkr.co/edit/oAWaFr8OtBusRli4v8MS?p=preview
I want to click on Save button and then show input validation.

**Comment by EladBezalel** [comment]
This question should be asked in the [forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by eduardoroyer** [comment]
You can use this:  || userForm.$submitted

**Comment by hengsokly** [comment]
Thank @eduardoroyer for your answer; however, if I use "|| userForm.$submitted", it affects only the  error message but not the <input> control at all. Actually, I want the <input> control to be highlighted in red color when there is no value and I click submit button.

**Comment by rschmukler** [comment]
You can manually achieve this my applying the `md-input-invalid` class to the container using the `ng-class` directive. [Here is an example](http://plnkr.co/edit/zO3NjeQeiAas0mfI2je5?p=preview) of how this can be done.

**Comment by ajoslin** [comment]
Added md-is-error for full power over it.

**Comment by maryisdead** [comment]
Sorry for digging this up again but do I really have to explicitly set `md-is-error` on each and every `md-input-container` to achieve this? Sounds like a thing that should be done by default.

**Comment by ferc** [comment]
+1 @maryisdead 

I am trying to change the ```field.$touched && field.$invalid``` by default to ```(form.$submitted || field.$touched) && field.$invalid``` but to do this, I need to change every ```md-input-container``` adding ```md-is-error```

Do you have any cleaner solution?

**Comment by maryisdead** [comment]
Nope, currently doing the same repetitive thing for all `md-input-container`, just like you.

This is what I'm using at the moment (for each and every field):

```html
<md-input-container md-is-error="characterform.name.$invalid && characterform.$submitted" flex="15">
    <label>ID</label>
    <input ng-model="character.id" name="id" type="number" required>
</md-input-container>
```

Don't have enough experience with the source code to come up with something better. Guess the problem is that `md-input-container` doesn't know about the model that the contained `input` is using. A custom directive should solve that though.

Still, I think this should be default behaviour.

**Comment by amritk** [comment]
+1

**Comment by vbraun** [comment]
For the record, you can monkey patch the container with a directive to DRY:
~~~~
const immediateErrorDirective: ng.IDirectiveFactory = function(): ng.IDirective {
    return {
        priority: -1000,
        restrict: 'A',
        require: ['^^mdInputContainer', 'ngModel'],
        link: function(scope, element, attr, ctrls) {
            const containerCtrl = ctrls[0];
            const ngModelCtrl = ctrls[1];
            containerCtrl.isErrorGetter = function() {
                return ngModelCtrl.$invalid;
            };
        }
    };
}

angular.module('immediateErrorModule', []).directive(
    'immediateError', immediateErrorDirective
)
~~~~
and then use 
~~~~
<md-input-container>
    <input ng-model="$ctrl.text" immediate-error>
</md-input-container>
~~~~
