### ISSUE TITLE
mat-tree cannot assign (my) unique id to node

### ISSUE THREAD

**Issue by JohnTranstel** [angular/material#11790]
I create a (flat) mat-tree from my own database. I can add the nodename as a string but this is not unique in my database. How do I add the uniqueID associated with my database record to the tree node as an invisible property?
When I do something to change that node and want to save the changes back to the database, I need to know the uniqueID.

many thanks
John

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
