### ISSUE TITLE
Max characters in input

### ISSUE THREAD

**Issue by highfredo** [angular/material#1180]
If the max characters is set, it shows the error when it reaches the maximum, not when it exceeds

![captura](https://cloud.githubusercontent.com/assets/5951524/5719656/a44b4368-9b1a-11e4-8cea-1d4ac952b209.PNG)
(this should be a valid input)

Also trailing whitespaces count as characters but do not show an error

![image](https://cloud.githubusercontent.com/assets/5951524/5719760/c6d492b2-9b1b-11e4-9a9d-417956a282ba.png)
![image](https://cloud.githubusercontent.com/assets/5951524/5719792/0ac81836-9b1c-11e4-8fe8-05ef1b08e940.png)

**Comment by epelc** [comment]
I ran into this on my last project. Essentially you need to trim whitespace off the end because if there isn't a letter number etc. This is because the max character attribute doesn't count it however the naive way to get a character count in js does.
