### ISSUE TITLE
Documentation broken link

### ISSUE THREAD

**Issue by WillsB3** [angular/material#1181]
In the [breaking changes section](https://github.com/angular/material/blob/master/CHANGELOG.md#breaking-changes) there is a broken link. See the text:

"md-textfloat has been deprecated due to flaws (explanation in #547."

The link to ticket #547 doesn't work.

**Comment by PaulMougel** [comment]
Duplicate of #1146

**Comment by WillsB3** [comment]
That was fast!

Sorry, should have searched better :+1:
