### ISSUE TITLE
dialog: screen freezes while calling $mdDialog.show() multiple times

### ISSUE THREAD

**Issue by GTarifshabbir** [angular/material#11814]
Library : https://material.angularjs.org/1.0.3/api/service/$mdDialog
Version: 1.0.3

**Can I disable opening multiple dialogs while calling `$mdDialog.show()` multiple times ?**

Working on `$mdDialog` on my application. I am facing the screen freezing issue when I try to open `$mdDialog` on clicking multiple time on button at a time. `$mdDialog` opens multiple and overlaps each other and freezes the screen. I need to reload page to perform any action after that.I could not found any service or directive from angular material site, kindly let me know if is there any proper way to resolve such issue.

Example Code:
```js
                     $mdDialog.show({
                        controller: exampleController,
                        templateUrl: example.html',
                        controllerAs: 'vmc',
                        parent: angular.element(document.body),
                        targetEvent: $event,
                        clickOutsideToClose: true
                    });
```

![image](https://user-images.githubusercontent.com/16715741/67579065-308bd380-f75d-11e9-80eb-a9dfc54fbd2f.png)

**Comment by Splaktar** [comment]
Showing multiple dialogs at the same time wasn't supported until AngularJS Material `1.1.2`, but it is recommended that you update to the latest version (`1.1.20`) when submitting bug reports. 

> Can I disable opening multiple dialogs while calling `$mdDialog.show()` multiple times ?

Yes, you should keep track of when the button is clicked and disable the button when a dialog is open. You can find some details on how to use `finally()` in the [`$mdDialog` docs](https://material.angularjs.org/latest/api/service/$mdDialog). This will allow you to re-enable the button after the dialog closes.
