### ISSUE TITLE
Datepicker throws exception when reaching years lesser than 0

### ISSUE THREAD

**Issue by jesus-soria** [angular/material#11810]
#### Detailed Reproduction Steps: 
1. Pressing the arrow to the left of the calendar, when you reach dates less than 0, an exception occurs. 

### Which versions of AngularJS, Material, OS, and browsers are affected?

- angular/cli: 6.0.8
- angular/material: 6.4.7
- angular/core: 6.0.7
- OS: Windows 7 Enterprise SP1
- Browsers: Internet Explorer 11.0.135

 
### Is there anything else we should know? Stack Traces, Screenshots, etc.

![Capture 1](https://user-images.githubusercontent.com/56622865/66893130-a1105300-efed-11e9-8ec1-8593c7207619.PNG)

Invalid procedure call or argument.
TypeError: Invalid procedure call or argument at NativeDateAdapter.prototype._format (http://localhost:4200/XXX/vendor.js:96061:9) at NativeDateAdapter.prototype.getYearName (http://localhost:4200/XXX/vendor.js:95740:13) at periodButtonText.get (http://localhost:4200/XXX/vendor.js:99013:13) at Anonymous function (Function code:67:5) at debugUpdateRenderer (http://localhost:4200/XXX/vendor.js:63639:5) at checkAndUpdateView (http://localhost:4200/XXX/vendor.js:63015:5) at callViewAction (http://localhost:4200/XXX/vendor.js:63251:21) at execComponentViewsAction (http://localhost:4200/XXX/vendor.js:63193:13) at checkAndUpdateView (http://localhost:4200/XXX/vendor.js:63016:5) at callViewAction (http://localhost:4200/XXX/vendor.js:63251:21) 

HTML
```
<mat-form-field fxFlex="30%">
	<input matInput placeholder="Año" autocomplete="off" maxlength="{{ctes_html.YEAR_LENGTH}}"
		  [formControl]="precertFormControl.get('anioDesdeFormControl')" required
		  class="cursor_default">
		  <mat-error *ngIf="precertFormControl.get('anioDesdeFormControl').hasError('pattern') ||
							precertFormControl.get('anioDesdeFormControl').hasError('min') ||
							precertFormControl.get('anioDesdeFormControl').hasError('max') ||
							precertFormControl.get('anioDesdeFormControl').hasError('required')">Debe introducir un valor numérico entre {{ctes_html.MIN_YEAR_PICK}} y {{ctes_html.MAX_YEAR_PICK}}</mat-error>
	<input matInput [matDatepicker]="yearPicker" [hidden]= true [matDatepickerFilter]="yearDatepickerFilter"> 
	<mat-datepicker-toggle matSuffix [for]="yearPicker"><span class="xxx-icon-fecha-formulario" matDatepickerToggleIcon></span></mat-datepicker-toggle>
	<mat-datepicker #yearPicker (yearSelected)="dateSelected($event)"
					startView='multi-year' [panelClass]="'mat-datepicker-centered'"></mat-datepicker>
	<mat-icon *ngIf="precertFormControl.get('anioDesdeFormControl').value" matSuffix class="mat-icon-clickable" 
			  color="primary" mat-icon-button arial-label="Limpiar" 
			  (click)="precertFormControl.get('anioDesdeFormControl').setValue(null); applyFilter()">
			  close
	</mat-icon>
</mat-form-field>
```

TS
```
    yearDatepickerFilter = (date: Date): boolean =>{
        const year = date.getFullYear();
        return year <= constantes.MAX_YEAR_PICK && year >= constantes.MIN_YEAR_PICK;
    }
```

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

I have transferred this issue to the correct repository for you.
