### ISSUE TITLE
slider: changing model value programmatically does not trigger ng-change

### ISSUE THREAD

**Issue by sviams** [angular/material#11824]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Update max and the `ng-model` binding to a higher value than before
2. Observe the value updated but `ng-change` not changing as it should

### What is the expected behavior?
Any observers of changes (`ngModelCtrl.$viewChangeListeners`) should be triggered.

### What is the current behavior?
No update is triggered, because the original updating of max failed to commit the view value in the `ngModelCtrl`.

### What is the use-case or motivation for changing an existing behavior?
In use cases where the scale/max value is dynamic, it has a fairly large impact on the usability.

### Which versions of AngularJS, Material, OS, and browsers are affected?

- AngularJS: 1.7.8
- AngularJS Material: 1.1.20
- OS: Ubuntu 19.10
- Browsers: Chrome, Firefox

**Comment by Splaktar** [comment]
The [ngChange docs](https://docs.angularjs.org/api/ng/directive/ngChange) state:
> It will not be evaluated:
>
>1. if the value returned from the $parsers transformation pipeline has not changed
>1. if the input has continued to be invalid since the model will stay null
>1. if the model is changed programmatically and not by a change to the input value

In this case, we're changing both the model and the `max` values programmatically. Based on that, it seems like the existing behavior is "correct"?

**Comment by Splaktar** [comment]
I'm going to close this due to no response to the feedback requested in my previous comment. I'm happy to re-open it should that be appropriate after the feedback is provided.
