### ISSUE TITLE
autocomplete: add auto styling of ng-messages when not using md-floating-label

### ISSUE THREAD

**Issue by nlenoire** [angular/material#11830]
## Bug:
The use of standard label and not md-floating-label cause the autocomplete component not to show validation error (using md-messages and $error).

# CodePen and steps to reproduce the issue:
https://codepen.io/nlenoire/pen/LYEyXpR?editors=1010

#### Detailed Reproduction Steps: 
Enter more than 5 characteres into the autocomplete field

### What is the expected behavior?
A validation error message should appear

### What is the current behavior?
No error message appears

### What is the use-case or motivation for changing an existing behavior?
We should be able to display validation error message even if the component doesn't use md-floating-label directive

### Which versions of AngularJS, Material, OS, and browsers are affected?
- AngularJS: 1.7.8
- AngularJS Material: 1.1.20
- OS: Windows 10
- Browsers: Chrome  79.0.3945.88

**Comment by Splaktar** [comment]
The `md-floating-label` mode of `md-autocomplete` is built for use with forms with validation. The other form of autocomplete is more geared towards search box type behavior. Thus when using `md-floating-label`, you get the Autocomplete's `input` wrapped by an `md-input-container` which is what gives the automatic styling and display of `ng-messages`.

There are currently no plans to use `md-input-container` without `md-floating-label` in `md-autocomplete`.

I think that the current recommendation for this would be to use `ng-messages` outside of the `md-autocomplete` tags and then apply the desired styling for your app.
