### ISSUE TITLE
Label goes over input text when value is dynamically loaded

### ISSUE THREAD

**Issue by elazarza** [angular/material#11835]
## Bug, enhancement request, or proposal:

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. settting the input's value attribute to a variable or let it be loaded dynamically with the form group

### What is the expected behavior?
the value is in the input and the label is above it

### What is the current behavior?
label and value overlapping

### Which versions of AngularJS, Material, OS, and browsers are affected?

Tested on latest angular and material @ Chrome
 
### Is there anything else we should know? Stack Traces, Screenshots, etc.
![image](https://user-images.githubusercontent.com/44997619/71898214-625be600-3161-11ea-94ea-2c38fcf0b632.png)

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
