### ISSUE TITLE
Unexpected popup for the Form Input component

### ISSUE THREAD

**Issue by KulikovDO** [angular/material#11866]
Hello,

I would like to report a strange behavior of the matInput / Form Field component. 
When I go to the page https://material.angular.io/components/form-field/examples and click on the first form field example, there is a popup with the text "1" on it. I use Google Chrome.
[
![image](https://user-images.githubusercontent.com/33626780/75960353-de24a580-5efa-11ea-84b0-1b9b8a0def6b.png)
](url)

From my observations, it happens only for the first matInput on the page.

Kind regards,
Denis Kulikov

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

I would have transferred this issue to the correct repository for you, but it does not follow our **required** issue template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
