### ISSUE TITLE
Unable to run tests in container

### ISSUE THREAD

**Issue by oliversalzburg** [angular/material#11878]
## Bug, enhancement request, or proposal:
It is unclear how to run the test suite in certain environments.

# CodePen and steps to reproduce the issue:
#### Detailed Reproduction Steps: 
1. Run `npm run test:full`.

### What is the expected behavior?
The test suite is being run and, ideally, passes.

### What is the current behavior?
The process results in errors, never completes and also does not run any tests:
```shell
node@cd2b6e6d925b:/workspaces/material$ npm run test:full

> angular-material-source@1.1.21 test:full /workspaces/material
> gulp karma

[11:51:53] Using gulpfile /workspaces/material/gulpfile.js
[11:51:53] Starting 'build-scss'...
[11:51:53] Building css files...
[11:51:53] Starting 'build-js'...
[11:51:53] building js files...
[11:52:19] Finished 'build-scss' after 26 s
[11:52:24] Finished 'build-js' after 31 s
[11:52:24] Starting 'build'...
[11:52:24] Finished 'build' after 38 μs
[11:52:24] Starting 'karma'...
[11:52:24] Running unit tests on unminified source.
13 03 2020 11:52:25.709:WARN [filelist]: All files matched by "/workspaces/material/src/**/*.spec.js" were excluded or matched by prior matchers.
13 03 2020 11:52:25.823:WARN [karma]: No captured browser, open http://localhost:9876/
13 03 2020 11:52:25.956:ERROR [launcher]: No binary for Chrome browser on your platform.
  Please, set "CHROME_BIN" env variable.
13 03 2020 11:52:35.937:WARN [launcher]: Firefox have not captured in 10000 ms, killing.
13 03 2020 11:52:37.938:WARN [launcher]: Firefox was not killed in 2000 ms, sending SIGKILL.
13 03 2020 11:52:39.938:WARN [launcher]: Firefox was not killed by SIGKILL in 2000 ms, continuing.
```

### What is the use-case or motivation for changing an existing behavior?
Being able to run the test suite to validate code changes.

### Which versions of AngularJS, Material, OS, and browsers are affected?
- AngularJS: 1.7
- AngularJS Material: 1.1.22
- OS: Windows
- Browsers: 
 
I commonly observe this when trying to run tests in a DevContainer, per #11844

**Comment by Splaktar** [comment]
Just from looking at the errors, it seems to indicate that Chrome isn't installed in the container, so that's one thing to address. It may require using another container if the author of that container doesn't want to add Chrome.

For Firefox, it would be interesting to know what version ships in the container. It looks like this might just be failing due to a lack of resources allocated to the container or a lack of available resources on the local machine.

**Comment by oliversalzburg** [comment]
I can make any modifications to the container that I want. Which Chrome could I use? Is this documented somewhere or could I use some CI configuration file as guidance?

I doubt Firefox is installed in the container. Maybe the output is misleading.

**Comment by Splaktar** [comment]
Here's the container that we use for CI:
https://github.com/angular/material/blob/0b83a2cbfd527a171fef2d0ffef038ff8a8dd674/.circleci/config.yml#L9

**Comment by oliversalzburg** [comment]
That seems to be built from https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/node/images/10.18.0-stretch/browsers/Dockerfile

I will look into it.

**Comment by Splaktar** [comment]
It may be useful to use the `karma-circleci.conf.js` as well or at minimum both headless versions of Chrome and Firefox:
https://github.com/angular/material/blob/8fc62a4d383ffe2ad6c1eff2d6e1956b89cf6ed4/config/karma-circleci.conf.js#L11

**Comment by Splaktar** [comment]
And here's the command for using that config file:
https://github.com/angular/material/blob/8fc62a4d383ffe2ad6c1eff2d6e1956b89cf6ed4/scripts/circleci/run-tests.sh#L17

**Comment by Splaktar** [comment]
Any luck with that new container that you added in PR https://github.com/angular/material/pull/11844?

**Comment by oliversalzburg** [comment]
Pushed a new container. Full test suite passes in that one. Ultimately, this ticket is invalid, because you just have to provide _everything_ that you need to run browser tests headless and then you can run the tests in a container just fine.

**Comment by Splaktar** [comment]
Glad to hear that this is resolved. We've also made headless testing the default for all of our Karma tests.
