### ISSUE TITLE
Disable pagination on md-tabs

### ISSUE THREAD

**Issue by lievenjanssen** [angular/material#1189]
Is it possible to disable pagination on tabs?

I have small tabs that just show an icon and I want to display them next to eachother even if the screen width is small.

**Comment by robertmesserle** [comment]
@lievenjanssen It sounds like you are looking to disable the tab-stretching, not pagination.  Is this accurate?

**Comment by robertmesserle** [comment]
I'll paste my (paraphrased) reply from the ngMaterial group:

> You can disable stretching by adding the following attribute to your <md-tabs> element: md-tab-stretching="never"
>
> This is documented here: https://material.angularjs.org/#/api/material.components.tabs/directive/mdTabs
>
> If you really do want to disable pagination, there is no current way to disable it; however, it should only occur when your content stretches beyond the available space within your tab bar.  You could effectively disable it by expanding your tab-bar through CSS to fit its contents - otherwise, tabs would just be hidden and inaccessible.

**Comment by ThomasBurleson** [comment]
Or you could use a separate Tabs (without content) data bound to external content using an `ng-switch`: Then large tab content areas will not affect the sizing of the tab buttons and container.

> @see [Static Tabs Demo](https://material.angularjs.org/#/demo/material.components.tabs).

**Comment by lievenjanssen** [comment]
@robertmesserle setting md-stretch-tabs (documentation) or md-tab-stretching (your suggestion) to "never" doesn't work for me.

This is what I see:

Width large enough:
![image](https://cloud.githubusercontent.com/assets/958643/5860359/2b61214a-a261-11e4-9b1c-ad5f4d9c090c.png)

Width too small:
![image](https://cloud.githubusercontent.com/assets/958643/5860386/4f2f6c1c-a261-11e4-86d9-57677a94b911.png)

@ThomasBurleson I don't really understand what you mean.

**Comment by robertmesserle** [comment]
Can you include a codepen or plunker for this example?  I suspect that the issue could be a large amount of padding throwing off the pagination logic.  If that's the case, it should be very easy to fix.

**Comment by lievenjanssen** [comment]
Apparently version rc 7.0 fixes this issue. I plan to upgrade to this version once it's released so this issue can be closed.

**Comment by yccteam** [comment]
Hi,
I'm now trying to do the same on version 0.8.2, but it doesn't work for me.
Here's a code pen:
http://codepen.io/yccteam/pen/jEpYXE
I don't want pagination whatsoever, but still keep the menu as is (if something needs to be hidden because of it, then let it be hidden).

**Comment by Bizarrus** [comment]
Im using `v0.8.3-master-019a8d6` but i have the same problem:
i want to disable the "pagination/responsive" function - but how? Found nothing on Docs.
