### ISSUE TITLE
controller calls twice when ngMaterial added app

### ISSUE THREAD

**Issue by PalakjainJain** [angular/material#11897]
## Bug, enhancement request, or proposal

# Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  

#### Detailed Reproduction Steps
1. 
1. 

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.
- AngularJS Material: 1.
- OS: 
- Browsers: 
 
#### Stack Trace
```

```

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
