### ISSUE TITLE
autocomplete: SyntaxError: Invalid regular expression when typing (

### ISSUE THREAD

**Issue by Nickproger** [angular/material#11908]
## Bug, enhancement request, or proposal
**Bug**

# Demo and steps to reproduce the issue

**Demo URL (required)***:  
https://material.angularjs.org/latest/demo/autocomplete

#### Detailed Reproduction Steps
1. input into Autocomplete the char `(`
2. check browser console

### Explain the expected behavior
No errors is Browser Console.

### Explain the current behavior
Error in Browser Console:

```js
SyntaxError: Invalid regular expression: /^test (/: Unterminated group
    at new RegExp (<anonymous>)
    at ee.createRegex (angular-material.min.js:7)
    at ee.onRender (angular-material.min.js:7)
    at m.$digest (angular.js:19143)
    at b.$apply (angular.js:19503)
    at Object.$$debounceViewValueCommit (angular.js:30903)
    at Object.$setViewValue (angular.js:30877)
    at HTMLInputElement.l (angular.js:26518)
    at sg (angular.js:3826)
    at HTMLInputElement.d (angular.js:3814)
```

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.7.9
- AngularJS Material: 1.1.22 (1.1.21 - no bug)
- OS: Windows 10
- Browsers: Chrome
 
### Add anything else we should know
This bug appeared after upgrade from v1.1.21 to v1.1.22

#### Screenshots
![image](https://user-images.githubusercontent.com/1409078/81806144-bd915100-9524-11ea-8aad-9a9a2bfa9e51.png)

**Comment by Splaktar** [comment]
Thank you for this report! I can reproduce this on the docs and locally. The regression was caused by PR https://github.com/angular/material/pull/11855.

Investigating...

**Comment by Splaktar** [comment]
Opened PR https://github.com/angular/material/pull/11911 to fix tihs.
