### ISSUE TITLE
select: trackby does not accept &quot; instead of '

### ISSUE THREAD

**Issue by Mike-Bauer** [angular/material#11910]
## Bug, enhancement request, or proposal

# Demo and steps to reproduce the issue

**Demo URL (required)***:  
https://stackblitz.com/edit/angularjs-material-blank-zlbjsx?file=app%2Fapp.template.html

#### Detailed Reproduction Steps
1. Use an md-select with trackby element like the following:

```
<md-select ng-model="selectedItem" ng-model-options="{trackBy:&quot;$value.id&quot;}">
```

Note our build process replaces ' with &quot

2. Selecting the element produces the run time error:

[$parse:ueoe] Unexpected end of expression: {trackBy:
https://errors.angularjs.org/1.7.9/$parse/ueoe?p0=%7BtrackBy%3A

This was introduced with v1.1.22, was not a problem in previous versions.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.7.9
- AngularJS Material: 1.1.22
- OS: 
- Browsers: 
 
#### Stack Trace
```

```

**Comment by Splaktar** [comment]
Using single quotes [works fine](https://stackblitz.com/edit/angularjs-material-blank-hdbuqk?file=app/app.template.html). Also using HTML single quote entity `&apos;` [works fine](https://stackblitz.com/edit/angularjs-material-blank-vhnvzt?file=app/app.template.html).

But you can't nest double quotes (`"` or `&quot;`) like `"{trackBy:"$value.id"}"` or `"{trackBy:&quot;$value.id&quot;}"` as demonstrated [here](https://stackblitz.com/edit/angularjs-material-blank-rntygg?file=app/app.template.html).

It looks like your build system needs to be updated to replace single quotes with single quote entities (`&apos;`) and not double quote entities (`&quot;`).

**Comment by Splaktar** [comment]
In `1.1.21`, you didn't get an error, but the `trackBy` didn't work if you used nested `"`s as you can see [here](https://stackblitz.com/edit/angularjs-material-blank-qaduxw?file=app/app.template.html).

But it does appear that it worked when using `&quot;` within `"`s as seen [here](https://stackblitz.com/edit/angularjs-material-blank-3cqt9t?file=app/app.template.html). This behavior seems a bit inconsistent and suspect.
