### ISSUE TITLE
select: md-focused not removed from options on panel close

### ISSUE THREAD

**Issue by ccn974** [angular/material#11927]
## Bug, enhancement request, or proposal
"md-focused" class is not cleanup after select close. So when reopen select all previously selected options are highlighted

# Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  https://material.angularjs.org/latest/demo/select

#### Detailed Reproduction Steps
1. Open "State" select ("Basic usage" section) : "None" (first) option is highlighted(md-selected class)
2. Select "AL" option
3. Reopen "State" select : "None" and "AL" options are highlighted (md-selected class)
4. Select "AZ" option
5. Reopen "State" select : "None", "AL", "AZ" options are highlighted (md-selected class)

### Explain the expected behavior

Only last selected option (first option if none) is highlighted

### Explain the current behavior

All previously selected options are highlighted

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.7.9
- AngularJS Material: 1.1.22
- OS: All
- Browsers: All
 
### Add anything else we should know

Commit 928c71d6ee87bc03ce383bfa555f67e1d373fe13 : fix(select): overhaul screen reader support

#### Stack Trace
```

```

#### Screenshots
![image](https://user-images.githubusercontent.com/10272478/83743928-75b9a180-a66c-11ea-8457-74e032653cbc.png)

**Comment by Splaktar** [comment]
Opened PR https://github.com/angular/material/pull/11937 to fix this.
