### ISSUE TITLE
$mdToast: Action button padding issue

### ISSUE THREAD

**Issue by epelc** [angular/material#1193]
The action button has too much padding on the left side
![image](https://cloud.githubusercontent.com/assets/5204642/5748120/68326180-9c0b-11e4-83d0-dc1f5daed182.png)

Built with
```
$mdToast.show($mdToast.simple()
        .position('bottom right')
        .content('There is an update available')
        .action('UPGRADE')
        .highlightAction(true))
    .then(function() {
       //update the app...
    })
```

This appears to be only in `0.7.0-rc2` as the docs which are currently running `0.7.0-rc1` work fine.

**Comment by gustavohenke** [comment]
See my reporting in #1199, I think it's more detailed.

**Comment by mckenzielong** [comment]
md-action has padding-left:24px... does setting highlightAction actually do anything?
```javascript
          template: [
            '<md-toast ng-class="{\'md-capsule\': toast.capsule}">',
              '<span flex>{{ toast.content }}</span>',
              '<md-button ng-if="toast.action" ng-click="toast.resolve()" ng-class="{\'md-action\': toast.highlightAction}">',
                '{{ toast.action }}',
              '</md-button>',
            '</md-toast>'
          ]
```

**Comment by epelc** [comment]
@mckenzielong I don't think it does. I expected it to make it to make the text colored but that didn't work.
