### ISSUE TITLE
datepicker: cut off on small displays

### ISSUE THREAD

**Issue by angelvk83** [angular/material#11943]
Hi everybody. 

We are having some problem showing the entire datepicker when the screen is too small. We cann't access to some parts of the datepicker as you could see in this image:

![image](https://user-images.githubusercontent.com/67093703/84990503-80346a80-b145-11ea-8c40-51e02a003ddc.png)

I have tried to use the scroll strategies but I have not found enough info about how to use it, and anythings happens when I use it.

I have also tried some solutions with css but no positive results :( 

Is there any solution for that issue?

Thanks in advance!

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

Please file a new issue in the Angular Components repo that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
