### ISSUE TITLE
panel: sometimes doesn't appear in 1.1.23

### ISSUE THREAD

**Issue by Splaktar** [angular/material#11946]
## Bug

# Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  https://material.angularjs.org/HEAD/demo/panel#panel-animations

#### Detailed Reproduction Steps
1. Open dialog on panel animations demo
1. Open dialog twice in reuse demo

### Explain the expected behavior
Demos should still work

### Explain the current behavior
Panel Animations and Reuse demos are broken.

### Discuss the use-case or motivation for changing the existing behavior
Correctness

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.8.0
- AngularJS Material: 1.1.23
- OS: macOS
- Browsers: Chrome
 
### Add anything else we should know
![Screen Shot 2020-06-22 at 14 00 33](https://user-images.githubusercontent.com/3506071/85320237-c6186800-b490-11ea-8f49-7d1824c0253a.png)
![Screen Shot 2020-06-22 at 14 00 19](https://user-images.githubusercontent.com/3506071/85320239-c7499500-b490-11ea-9448-01bba85114f4.png)

**Comment by oliversalzburg** [comment]
It seems like only the Slide and Scale animation are broken. Seems like there are leftover inline styles from the end of the previous animation that cause problems on the second run.

**Comment by Splaktar** [comment]
For the first issue of panel animations breaking, that's caused by PR https://github.com/angular/material/pull/11942 needing to also `this.innerWrapper.removeClass('_md-panel-offscreen');` in `_updatePosition()`. I've got this fix ready.

For the second issue of re-use of panels causing the reused panel to not remove all of the inline styles after animating closed, that was caused by PR https://github.com/angular/material/pull/11390. I'm investigating the right way to eliminate these styles being left around.

**Comment by Splaktar** [comment]
OK, PR https://github.com/angular/material/pull/11390 does not appear to be at fault here.

It appears that PR https://github.com/angular/material/pull/11856 made panels more re-usable, but it didn't account for the transforms on the `md-panel` needing to be cleared after the close animation completes.

I've got a solution for this as well and will post a PR to resolve both of these issues soon.

**Comment by Splaktar** [comment]
This is fixed in `master`. Please try out the fix (before we release it) via `npm install http://github.com/angular/bower-material#master --save` or updating your `package.json` with `"angular-material": "git+ssh://git@github.com/angular/bower-material.git#master",`.

If you find any issues, please report them via GitHub issues ASAP.
