### ISSUE TITLE
mdSubheader: md-sticky-clone z-index incorrect

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#1195]
#### Overview of the Issue 
during the transition when the floating sub header appears, the text in the original md-subheader will scroll up along with all the other content.  Seems like this text should be hidden / underneath the floating sub header.

![Weird subheader text](http://i.imgur.com/2PKOPJE.png)
#### Angular Material Version
v0.7.0-rc3 - SHA 1cabb62
#### Browsers and Operating System 
Chrome 39 on Windows 7
#### Reproduce the Error 
reproducible on the material.angularjs.org docs site.
#### Related Issues 
search for subheader in closed and open didn't bring up anything...
#### Suggest a Fix
Bump the z-index value of md-sticky-clone to something greater than 1.

**Comment by PaulMougel** [comment]
May be related to #580.

**Comment by GoulwenBZH** [comment]
I have a problem with the z-index fix, now my fab button on my toolbar is under the  subheader.

Any ideas to solve that?

![bug](https://cloud.githubusercontent.com/assets/9105669/5965498/aef9cade-a7fc-11e4-99a2-6575eca2e5f9.png)

**Comment by rschmukler** [comment]
@GoulwenBZH Check out [this fiddle](http://jsfiddle.net/rschmukler/e5txs3pd/). Note that I put the FAB positioned absolutely within the `md-toolbar`.

**Comment by ThomasBurleson** [comment]
@rschmukler - what was the fix?

**Comment by GoulwenBZH** [comment]
@rschmukler Ok with FAB positioned absolutely, thanks for the suggestion.

**Comment by ChrisoCloete** [comment]
@GoulwenBZH does the FAB display over the sub-header now?

**Comment by smartxp** [comment]
you might want to add the z-index to the parent element "md-toolbar". Check it out here: https://jsfiddle.net/e5txs3pd/6/

**Comment by tim93422** [comment]
Would it be possible to increment the z-index rather than hard-code it to 2? The code would look something like this I'd think:

    if (browserStickySupport) {
      var originalZ = parseInt(element.css('z-index'));
      if (isNaN(originalZ)) {
        originalZ = 0;
      }

      element.css({
        position: browserStickySupport,
        top: 0,
        'z-index': Math.max(2, originalZ + 1)
      });
    } else {

I've got an element appearing to side above a toolbar with md-sticky because both the md-sticky toolbar and the element in question have a z-index of 2.
