### ISSUE TITLE
select(header): closes when filter input is focused

### ISSUE THREAD

**Issue by Axeldorf** [angular/material#11969]
## Bug

# Demo and steps to reproduce the issue

**Demo URL (required)***:  
With AngularJS Material Design v1.1.21: https://codepen.io/Axeldorf/pen/ExPGOpM
With AngularJS Material Design v1.1.24: https://codepen.io/Axeldorf/pen/yLeGQez

#### Detailed Reproduction Steps
1. Open selector.
1. Click on filter input

### Explain the expected behavior
On focusing filter input, select element is not closed and user can write any filter.

### Explain the current behavior
On focusing filter input, select element is closed and user can't write any filter.

### Discuss the use-case or motivation for changing the existing behavior
User wants to filter options in select, so when user clicks on input to write select must be opened.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.7.8
- AngularJS Material: 1.1.21 (works), 1.1.22+ (doesn't work)
- OS: Ubuntu 18.04
- Browsers: Chrome.

**Comment by Splaktar** [comment]
Thank you for this report.

This doesn't happen in the [select header demo](https://material.angularjs.org/latest/demo/select#select-header) because it uses `multiple`.

I've identified the issue and will open a PR soon.
