### ISSUE TITLE
Option to disable tab paging

### ISSUE THREAD

**Issue by djdmbrwsk** [angular/material#1197]
Imagine 3 tabs, each with a short title.  Even on a small screen like the iPhone 5 (320px) there is enough room for all 3 tabs to show.  Ex. http://run.plnkr.co/VgWSLvRc1Ev2Y37c/

It doesn't look like there is currently a way to disable paging on md-tabs, but it might make sense to give users that option via an attribute.  Thoughts?

**Comment by PaulMougel** [comment]
May be related to #1005.

**Comment by ThomasBurleson** [comment]
Duplicate #1189
