### ISSUE TITLE
md-input-container: 'md-input-has-value' stays even if no text in input

### ISSUE THREAD

**Issue by yarl** [angular/material#1198]
Class `md-input-has-value` is not removed when `md-input-container` focus lost and `input` inside is empty. To reproduce, use [your demo form](https://material.angularjs.org/#/demo/material.components.input), write something in `Last Name` field, remove all text and change focus to other element.

Result (red border):
![Img](http://i.imgur.com/w9Dp3wW.png)

Tested on Chrome and IE10. Lates version (`0.7.0-rc3-master-1cabb62`).

**Comment by yarl** [comment]
minor fix

**Comment by eduardoroyer** [comment]
The same here

**Comment by nekronhuang** [comment]
I think the reason is because the new verison missed something.
on angular-material.js(0.7.0) line 4360:
```
element.on('blur', function(ev) {
  containerCtrl.setFocused(false);
})
```
containerCtrl should check "hasValue" too.

**Comment by ajoslin** [comment]
The blur fix, as @nekronhuang mentioned, was implemented a few days ago into master.
