### ISSUE TITLE
md-datepicker select date again error

### ISSUE THREAD

**Issue by AndreasHo** [angular/material#11984]
Hello,

i think you have an bug in the directive "md-datepicker" for angularjs...
When you select an date again, the day before get selected but not shown in the displayed value.

This error we found, because we want to add a datepicker which minDate is today and the init value is today, too.
After init this, we have an invalid-mindate on the input => our save is not available.

You can watch this on your own website: https://material.angularjs.org/latest/demo/datepicker

Have a nice day!
Andreas Holleber

**Comment by Splaktar** [comment]
Yes, there is a regression with GMT+x timezones, where I think that GMT-x timezones work. Thank you for your report, but this is already being tracked in https://github.com/angular/material/issues/11963.
