### ISSUE TITLE
Accessibility issue in mat-paginator because of Mat-select field

### ISSUE THREAD

**Issue by Jagan494** [angular/material#11998]
## Bug, enhancement request, or proposal

The mat-select which is used in Paginator can’t be read by screen readers as the user changes the number which focus on the extended dropdown.

### Explain the expected behavior

The screen reader to be able to read the value of select field.  

Mat-paginator should have provision to use native select component inside paginator component. 

### Explain the current behavior
There is accessibility issue on Mat-Paginator because of mat-select field.

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

**Comment by Jagan494** [comment]
Hi Team,

I have raised the same concern again.

https://guthub.com/angular/components/issues/20333


Please help with this issue.

Regards,
Jagan
