### ISSUE TITLE
Simple toast action button has too much padding-left

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#1199]
I created a toast using the `$mdToast.simple()` API:

```javascript
let toast = this.$mdToast.simple();
toast.content( errorMsg )
     .action( retry )
     .highlightAction( true )
     .hideDelay( 0 );
```

This resulted in the action button having too much padding-left:

![](http://i.imgur.com/I7Hihi9.png)

This happens because of the `.md-action` class, applied to toast created using that API:
![](http://i.imgur.com/WRBajDQ.png)

If I create it using a template, the problem will not happen.

**Comment by PaulMougel** [comment]
Duplicate of #1193.

**Comment by gustavohenke** [comment]
Didn't see that!
