### ISSUE TITLE
Slider is not sliding anymore after the version 9.2.0 with Capacitor

### ISSUE THREAD

**Issue by tototares** [angular/material#11990]
The mat-slider is not working with Capacitor anymore after the Material version 9.2.0. I guess this commit caused the issue: https://github.com/angular/components/commit/ca3c68f

Before this update everything works fine, so I'am not able to update to newest Angular Material version right now.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
