### ISSUE TITLE
button(fab): icon color is changed to black from white in 1.2.0

### ISSUE THREAD

**Issue by shyambhiogade** [angular/material#11997]
lib updated to 1.2.0 icon color is changed to black from white and horizontal scroll bar displaying.

# Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  

#### Detailed Reproduction Steps
after using the angular material library 1.2.0 my default fab icon color changed to black check in below pne
https://codepen.io/shyambhiogade/pen/VwaePvd
![image](https://user-images.githubusercontent.com/10468130/90098146-6d28bb80-dcec-11ea-805a-27c7b11bc902.png)

also started seeing horizontal scrollbar in my application as below earlier it was not showing scrollbar
![image](https://user-images.githubusercontent.com/10468130/90098334-d7416080-dcec-11ea-9a0f-1aec1ed17ae5.png)

if i use previous version of angular material library 1.1.24-default fab icon color is white-check in below pen
https://codepen.io/shyambhiogade/pen/dyMGNoe
![image](https://user-images.githubusercontent.com/10468130/90098175-7a45aa80-dcec-11ea-889e-7b337d801afd.png)

also my application looks good without scrollbar.

![image](https://user-images.githubusercontent.com/10468130/90098368-f5a75c00-dcec-11ea-8011-f3db06fe2055.png)

 

### Explain the expected behavior
default icon color should be white

### Explain the current behavior
icon color is black

### List the affected versions of AngularJS, Material, OS, and browsers

details are available in provided pen
 
#### Stack Trace
```

```

**Comment by Splaktar** [comment]
This is 2 issues in one. 

For the button theme question, please see [this response](https://github.com/angular/material/issues/11996#issuecomment-670233367).

**Comment by Splaktar** [comment]
For the scrollbar issue, that is likely a result of the breaking changes listed in [the release](https://github.com/angular/material/releases/tag/v1.2.0). A number of components had their layout/padding/margins changed to match the latest version of the [Material Design 2017 spec](https://material.io/archive/guidelines/).

I can't really provide more guidance on this with the information provided. If you would like me to look into this further, please open a new issue with a CodePen/StackBlitz reproduction.
