### ISSUE TITLE
Mat Datepicket min date validation not working

### ISSUE THREAD

**Issue by rajithsam** [angular/material#12008]
Hi team!

I have used mat-datepicker with reactive forms & facing an issue when I tried to set the datepicker's value dynamically.

I have reproduced the issue in the below URL,
https://stackblitz.com/edit/angular-mxqsdy-7bfebs?file=app%2Fdatepicker-min-max-example.ts
Kindly check & let me know your valuable suggestions.

Thanks in advance

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
