### ISSUE TITLE
material/input: matTextareaAutosize causes jumping to the bottom when editing

### ISSUE THREAD

**Issue by saurabhsingh1003** [angular/material#12005]
When i'm try to edit my textarea in material input and i have used `matTextareaAutosize` for automatic height so when i'm trying to edit its jumping to bottom.

Do you guys have any solution to stop this? thanks for your support.

checkout the code attached below:
- browser-chrome
```html
<mat-form-field class="example-full-width">
    <mat-label>Leave a comment</mat-label>
    <textarea matInput matTextareaAutosize placeholder="Ex. It makes me feel..."></textarea>
  </mat-form-field>
</form>
```

Reproduction: https://stackblitz.com/angular/lvynqyajxdj?file=src%2Fapp%2Finput-overview-example.html

**Comment by saurabhsingh1003** [comment]
@mlynch @wesalvaro @gmoothart Abraham White

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue, your first ever! However it does not follow our **required** issue template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Additionally, your StackBlitz doesn't appear to be forked or updated. You need to fork the original StackBlitz and then add the `matTextareaAutosize` directive to it along with any other code needed to reproduce your issue.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

Please open a new issue in https://github.com/angular/components/issues that follows the issue template (which includes step by step reproduction steps) and includes a forked and updated StackBlitz which reproduces the issue.

**Comment by saurabhsingh1003** [comment]
@ereztison
