### ISSUE TITLE
md-input-container: Label stays floating if required and empty when you change focus

### ISSUE THREAD

**Issue by epelc** [angular/material#1201]
![image](https://cloud.githubusercontent.com/assets/5204642/5760912/c5aa1e76-9ca5-11e4-81da-7542cfa141c6.png)
If you have an input that is required and you fill something in then delete it the label will stay floating no matter what you do.

Example markup
```
<md-input-container flex>
    <label>Zip Code</label>
    <input ng-model="Address.Zipcode" required>
</md-input-container>
```

Version: `0.7.0-rc3`

**Comment by itajaja** [comment]
even when it's not required actually. Same `0.7.0-rc3` version

**Comment by epelc** [comment]
O I just noticed that too

**Comment by epelc** [comment]
Also its just in chrome ie11 and firefox dont have this issue. Can anyone confirm this on a mac? Mine is at home.

**Comment by mckenzielong** [comment]
Seems like there should be a check for value on blur?

```javascript
      .on('blur', function(ev) {
        containerCtrl.setFocused(false);
        containerCtrl.setHasValue(checkHasValue())
      });
```

**Comment by ajoslin** [comment]
I'll add the blur check.
