### ISSUE TITLE
layout: unexpected behaviour when nesting flex-gt-x inside of layout-gt-y

### ISSUE THREAD

**Issue by LabN36** [angular/material#12029]
## Unpredicted behaviour of layout API

# Demo and steps to reproduce the issue
this [codepen](https://codepen.io/labn36/pen/NWrWXZg) has two examples(ie. div1 and div2) where div2 is not working, please read below section to know what should be the expected behaviour.

**Demo URL (required)***:  [codepen](https://codepen.io/labn36/pen/NWrWXZg)

#### Detailed Reproduction Steps
1. this codepen has two `divs` here the second div doesn't seems producing expected behaviour.
2. put small flex inside larger flex values ie. _(layout-gt-sm as parent and layout-gt-xs as child )_

### Explain the expected behavior
All the child div should occupy it's parent width according to the `flex` value

### Explain the current behavior
All the childs `div` does not takes proper width as defined in it's `flex` value 

### Discuss the use-case or motivation for changing the existing behavior

**Note**: this is what my understanding towards flex and layout API, so please if i'm wrong at some point please try to help me understand what's wrong I'm thinking.

let's say if i define a div as `layout-gt-xs="row"` so that means all it's child will be aligned/floating  horizontally for all width >=600px 
same for the `layout-gt-sm="row"` having width >=960px. **correct ?**

Now considering the above statement i have defined a parent `div` with `layout-gt-xs="row"` and it has 3 children having `flex-gt-xs=33 `for each of three. so here all the children takes 1/3rd of it's parent's width properly provided the browser should have width >=600 px for it to work. - This is working as expected.
   
 ```html
//working fine
   <div layout-gt-xs="row" flex style="background-color: brown;">
        <div flex-gt-xs=33 style="background-color: aqua;">this is  </div>
        <div flex-gt-xs=33  style="background-color: aquamarine;">taking</div>
        <div flex-gt-xs=33  style="background-color: blue;">full width</div>
   </div>
```

**_Now here comes the issue._**
in the similar way if i define a parent `div`  with `layout-gt-sm="row"` that means all it's child will be aligned /floating horizontally for all width >= 960px
now this parent div has 3 childrens with values `flex-gt-xs=33` that means this childs will takes 1/3 of it's parent widhth for all the width >=600px. but these childs are not taking 1/3 of it's parents width. 
```html
//not working as expected   
    <div layout-gt-sm="row" flex style="background-color: brown;">
        <div flex-gt-xs=33 style="background-color: aqua;">why this </div>
        <div flex-gt-xs=33  style="background-color: aquamarine;">is not </div>
        <div flex-gt-xs=33  style="background-color: blue;">taking full width</div>
    </div>
```

**Note:** i really wanted to know why it's not working, I would request experts like to help me understand why it's not working or what is the thought process behind this in very simple term, I'd really appreciate if someone can explain this in well manner.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.8.0
- AngularJS Material: 1.2.1
- OS: MacOS
- Browsers: Chrome
- Screen Readers: 
 
#### Stack Trace
```

```

#### Screenshots
![image](https://user-images.githubusercontent.com/10628287/95373018-fe399e80-08f9-11eb-9e34-f116b6cdf369.png)

**Comment by noahcooper** [comment]
You should change the flex attribute on your child elements to `flex-gt-sm`, or simply `flex`.

**Comment by Splaktar** [comment]
For the first `div`, you can see the following style applied:
```css
@media (min-width: 600px)
.layout-gt-xs-row > .flex-gt-xs-33 {
```

For the second `div`, you can see that none of our Layout APIs are applied.

We try to explain this in the [docs here](https://material.angularjs.org/HEAD/layout/children#incorrect-use-of-flex-directives-within-responsive-layouts).

Part of the reason for this limitation is to keep the logic manageable and an even bigger part is to keep the size of the generated CSS from exploding.
