### ISSUE TITLE
datepicker: modifies time

### ISSUE THREAD

**Issue by Miqueliu** [angular/material#12026]
## Bug

# Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  
[Here](https://jsfiddle.net/frcoeb4n/) is a live demo.

#### Detailed Reproduction Steps
1. Notice the date strings have some time values
1. Click or focus the datepicker
1. Notice that the date strings have all of their time values set to midnight

### Explain the expected behavior

The `ng-model` value must to remain the predefined time as far as possible.

However, regarding the limits (`md-min-date` and `md-max-date`), they have to be treat as read-only data, not altered.

### Explain the current behavior

In the last updates, when date picker is interacted (clicked, calendar showed, focused...), time of scope values are changed. It happens both to `ng-model` and to limits (`md-min-date` and `md-max-date`). It is very traumatic when you are using these values to control datetime by another time input.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.7.2
- AngularJS Material: 1.2.1
- OS: macOS
- Browsers: Chrome 85
- Screen Readers: 
 
#### Stack Trace

N/A

**Comment by Splaktar** [comment]
I guess that you missed this warning in the issue template?

> Filling out this template is required! Do not delete it when submitting your issue!
> Without this information, your issue may be auto-closed.

**Comment by Splaktar** [comment]
Yes, the times are set to midnight as the datepicker only works with dates and not times. 

I can see that your demo shows the times being set to midnight when an interaction with the datepicker happens. But can you explain the impact of this in a wider use case?

**Comment by Miqueliu** [comment]
The impact of this? I already said: "It is very traumatic when you are using these values to control datetime by another time input". Test a library to insert time using the same datetime limits and check that this "expected behavior" turns something simple into a headache.
