### ISSUE TITLE
md-input-container: Label still floats when you click it if input has "readonly" attribute

### ISSUE THREAD

**Issue by epelc** [angular/material#1203]
Now that we have `md-input-container` and can access the inner `input` element we should support the `readonly` and `ng-readonly` attributes. Currently if an input is read only the label will still float up and the whole element changes colors like normal however this shouldn't happen.

Also if your input has some text in it and then it becomes read only you can still click on it and it will change color without letting you edit it.

**Comment by Splaktar** [comment]
I am seeing this as well.

Here is a plunker than can be used to test this with only a minor change: http://plnkr.co/edit/cV2xejsabJIhM70IC6Zg?p=preview

**Comment by chriseyhorn** [comment]
This only appears to be fixed with "readonly" and not "ng-readonly".

**Comment by baelter** [comment]
The label show float when you set the value programatically. Now the label is behind the value.

**Comment by bobwah** [comment]
I am still seeing this with ng-readonly

**Comment by fguillotpro** [comment]
Yes, the issue is still there using v1.1.1 and ng-readonly. Any plan for a fix?

**Comment by Splaktar** [comment]
This issue is closed. Please open a new issue for v1.1.1.
