### ISSUE TITLE
FAB Speed Dial: keyboard navigation with tab key gives unexpected results

### ISSUE THREAD

**Issue by sharonlevyex** [angular/material#12043]
## Bug Report
When navigating through md-fab-actions with both tab and keyboard the focus is not in order. 

### Example
If I use tab to navigate and I reach the third action:
![image](https://user-images.githubusercontent.com/73985320/98462713-eab27980-21be-11eb-889b-a084f84a2ae0.png)
and then I use keyborad (left) to navigate back to the previous action, the focus goes to the first action:
![image](https://user-images.githubusercontent.com/73985320/98462847-d3c05700-21bf-11eb-94fc-633d9202e112.png)

### Actual behavior
The focus starts from the first element when using keyboard, even after navigating with tab.

### Expected behavior
For keyboard to continue navigation from current button focused.

## Demo and steps to reproduce the issue
It reproduces in the Material demo.

**Demo URL (required)***:  https://material.angularjs.org/1.2.1/demo/fabSpeedDial

#### Detailed Reproduction Steps
1. Use tab to navigate through the actions.
2. Continue to navigate  with keyboard.

**Comment by Splaktar** [comment]
It looks like tab navigation is broken for this component. It just seems to go to the last option and hitting tab again closes the speed dial instead of going to the next option. Thank you for this report.
