### ISSUE TITLE
checkbox: wrong positioning with ng-click directive and md-secondary class in md-list-item

### ISSUE THREAD

**Issue by Tadas1987** [angular/material#12044]
## Bug Report
Checkbox position is wrong, when it has ng-click directive and md-secondary class inside md-list-item component.

**Demo URL (required)***:  [Demo URL](https://codepen.io/tadas-kalinauskas/pen/pobxeXo)

#### Detailed Reproduction Steps
1. Add md-secondary class to checkbox;
1. Add ng-click directive to checkbox;

### Explain the expected behavior
1. Checkbox should be align in md-list-item like secondary item;
1. md-list-item should be clickable;

### Explain the current behavior
1. Checkbox position is out of md-list-item component;
1. md-list-item is not clickable;

#### Screenshots
![Screenshot from 2020-11-09 10-04-37](https://user-images.githubusercontent.com/27301681/98514999-0bd4a200-2273-11eb-930d-b354c4c6b38e.png)

**Comment by Splaktar** [comment]
You can use the `md-checkbox` like a [proxy item](https://material.angularjs.org/latest/api/directive/mdListItem#proxy-item) in `md-list-item` ([example](https://codepen.io/Splaktar/pen/rNLPqZa)) or you can use the `md-checkbox` as a secondary interaction element ([example](https://codepen.io/Splaktar/pen/vYKbVQW)), but you can't do both at the same time.
