### ISSUE TITLE
Directives for select, datepicker, dropdowns

### ISSUE THREAD

**Issue by denisvolokh** [angular/material#1205]
Hi,

Do you have in plans create directive for elements and components like select, datepicker, dropdowns?

Thanks

**Comment by yarl** [comment]
- select/dropdown: #276 
- timepicker: #648

**Comment by marcysutton** [comment]
Yep, there is an [issue open for select](https://github.com/angular/material/issues/276), which is in progress. Date/time-picker is slated for milestone 0.9.0. https://github.com/angular/material/milestones
