### ISSUE TITLE
Multiple Chip Input Issue

### ISSUE THREAD

**Issue by Go-kul-S** [angular/material#12056]
When the chip input is being used multiple times, only the lowermost chip input appears with the placeholder. It seems to not work for the other chip input boxes.

This is when only one chip input component is used.
![image](https://user-images.githubusercontent.com/32187183/101876414-5f0f7c80-3bb2-11eb-8f7d-918feda608cc.png)

This is when multiple chip inputs are used.
![image](https://user-images.githubusercontent.com/32187183/101876553-8e25ee00-3bb2-11eb-8904-8058d32008ac.png)

When a third one is added, the issue seems to persist, making only the placeholder for the last one visible.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
