### ISSUE TITLE
Dialog Positioning and Persistence

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1206]
For some scenarios users want to manually drag and adjust the position of a dialog; perhaps to review obscured content without dismissing the dialog.

Enhanced features for Dialogs include:
-  Support open dialog positioned relative-to and offset-from an existing DOM element
-  Support dragging to be re-positioned; perhaps with a disableDrag flag
-  Support position auto-save and restore; 
-  Support optional position bounds to constrain drag
-  Support position overrides back to default when responsive layout intersects bounds

**Comment by epelc** [comment]
@ThomasBurleson Is there any way we can make it general enough to work with cards too?

Imagine a dashboard with several cards that you could move around and possibly resize.

**Comment by levbrie** [comment]
+1

**Comment by cah-alexsukhodolsky** [comment]
+1

**Comment by plato-cambrian** [comment]
+1 for directives to do dragging, snapping, etc on cards as well as dialogs (guess it might as well be any element :smile: )

**Comment by ThomasBurleson** [comment]
Resources: 

*  https://github.com/bevacqua/dragula

**Comment by goranobradovic** [comment]
+1

**Comment by marioharper** [comment]
+1

**Comment by aberenyi** [comment]
+1

**Comment by dneukirchen** [comment]
+1

**Comment by manbearwiz** [comment]
@DallanQ check out [Angular Gridster](https://github.com/ManifestWebDesign/angular-gridster) [(Demo)](https://rawgit.com/ManifestWebDesign/angular-gridster/master/index.html#/main) or [Dragula](https://github.com/bevacqua/dragula) [(Demo)](http://bevacqua.github.io/dragula/)

**Comment by DallanQ** [comment]
Thank you @manbearwiz I'm also looking at [ngDraggable](https://github.com/fatlinesofcode/ngDraggable) and [Dragabilly](https://github.com/desandro/draggabilly).

**Comment by fleahy** [comment]
+1

**Comment by rootscity** [comment]
FWIW, I ended up writing my own directive to make modals draggable: https://gist.github.com/rootscity/fcf909f5820407a67c8e

**Comment by DallanQ** [comment]
FWIW, I ended up writing a directive to make modals draggable: https://gist.github.com/rootscity/fcf909f5820407a67c8e

**Comment by tztztztztz** [comment]
+1

**Comment by jwmapana** [comment]
+1

**Comment by FlamesoFF** [comment]
+1

**Comment by katak** [comment]
+1

**Comment by DanielCaspers** [comment]
+1

**Comment by raynigon** [comment]
+1

**Comment by thorvx** [comment]
+1
When?

**Comment by teuf22** [comment]
+1

**Comment by CodeGains** [comment]
+1

**Comment by vhugo92** [comment]
+1

**Comment by edouardsouan** [comment]
+1

**Comment by Splaktar** [comment]
There is no clear guidance on drag and drop or positioning of dialogs in the Material Design spec. It's been 3 years since this issue was opened and that guidance still does not exist.

At this time, I don't believe that drag and drop support for dialogs is viable for this project. 

This may be something that is coming to Angular Material at some point in the future. You can track draggable dialogs in https://github.com/angular/material2/issues/2640. And if you have general drag and drop feature requests or feedback, the team is currently looking for uses cases and feedback while working on the drag and drop design document in https://github.com/angular/material2/issues/8963.

**Comment by cmark11** [comment]
Is there a solution for mat-dialog? The gist is only for md-dialog... need this or have to switch away from angular-material2...

**Comment by Splaktar** [comment]
@cmark11 Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
