### ISSUE TITLE
mat-autocomplete problem with formControl binding in reactive forms

### ISSUE THREAD

**Issue by Ric-01** [angular/material#12072]
Hi all,

I face the following issue when using material autocomplete version 11.0.3 together with Angular 11.0.9:
If coding the formControl property binding into the the connected input element like described on the documentation page (https://material.angular.io/components/autocomplete/overview) together with reactive forms approach, the posted object is always null.
I changed it by doing like follows:

Instead of
<input type="text" matInput [formControl]="myFormControlName" [matAutocomplete]="auto" />
I did the following:
<input type="text" matInput formControlName="myFormControlName" [matAutocomplete]="auto" />
Only the latter one works in that sense, that the object posted from the input is not null in onSubmit event.

Is it just an error in this documentation page I mentioned above? Thanks for your help!

**Comment by marosoft** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
