### ISSUE TITLE
How to limit selection via first letter of the option in mat select

### ISSUE THREAD

**Issue by manumohananmkm** [angular/material#12077]
I have a mat-select select box which has options as below [{   label: Excellent, keyCode:A, id:1 }, { label:Very Good, keyCode:B, id:2 }, { label:Bad, keyCode:C id:3 }, ]

The selection of the options should be based on only the keyCode. The problem is that the interface seems to allow both the short cut key and the first letter of the option labels as short cut options. Currently, the selection is implemented by a function call onKeyPressed on (keydown) of the mat-select. Is there anything possible to stop the selection via the first letter of the option labels. Thanks in advance.

material version : @angular/material": "^9.2.4", angular : 9

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
