### ISSUE TITLE
navbar: position: fixed causes issues with this library

### ISSUE THREAD

**Issue by ewahner** [angular/material#12088]
## Demo and steps to reproduce the issue
[This blank StackBlitz demo](https://stackblitz.com/edit/angularjs-material-blank?file=app%2Fapp.template.html) can be used to create a reproduction that demonstrates your issue.

**Demo URL (required)***:  

#### Detailed Reproduction Steps
1. Using navbar with a fixed position seems to throw off all of your components by the number of pixels that the fixed position is.  Meaning if my navbar is 60 pixels high all of your components open 60 pixels to high.  

### Explain the expected behavior
All of the components should take into account the fixed navbar and adjust their top calculations so the components open in the right place.

### Explain the current behavior
All components with a dynamic positioning behavior, like md-autocomplete, md-datepicker open up too high covering the input box.

### List the affected versions of AngularJS, Material, OS, and browsers

- AngularJS: 1.8
- AngularJS Material: 1.2.2
- OS: 
- Browsers: 
- Screen Readers: 
 
#### Stack Trace
```

```

**Comment by Splaktar** [comment]
Can you please provide the **required** reproduction of this issue either via StackBlitz or CodePen? 

Is this a regression? If so, in which version did it last work properly?
