### ISSUE TITLE
Dialog: Not working in IE11 - console error

### ISSUE THREAD

**Issue by pgarge** [angular/material#12081]
![image](https://user-images.githubusercontent.com/10064646/109151734-8b11b700-7738-11eb-9d7a-230b2d0edfe9.png)

I am using systemjs and the dialog works in other browsers.

Any help would be appreciated!!

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
