### ISSUE TITLE
md-input-container: growTextarea should be optional and should be possible to set max height

### ISSUE THREAD

**Issue by yarl** [angular/material#1209]
1. `md-input-container` needs parameter that disables autogrow of `<textarea>`.
2. There should be possible to set maximum height of `<textarea>` inside `md-input-container` if autogrow is enabled. If text height inside is bigger than `<textarea>` height, overflow scrollbar should appear.

**Comment by DmitryEfimenko** [comment]
+1

**Comment by eckyputrady** [comment]
+1!

**Comment by no-more** [comment]
+1

**Comment by rahul18gupta** [comment]
+1

**Comment by sazonenka** [comment]
+1

**Comment by peterpisljar** [comment]
+1

**Comment by ereztison** [comment]
A possible workaround though not perfect is to wrap the md-input-container containing the textarea with the following div:
<div style="height: 7rem; overflow-y: auto;" scroll-glue>
</div>

I used scroll-glue directive to keep the containing div scroll stick to the bottom while its height is growing:
https://github.com/Luegg/angularjs-scroll-glue

**Comment by sazonenka** [comment]
@ereztison Unfortunately, your "div" was cut off. Could you, please, provide it once again?

**Comment by SummerWish** [comment]
+1

**Comment by ereztison** [comment]
@sazonenka: I updated my comment, you're welcome to take a look.

**Comment by sazonenka** [comment]
@ereztison Thanks!

**Comment by crrrazymind** [comment]
+1
