### ISSUE TITLE
Need utility css classes included in angular material

### ISSUE THREAD

**Issue by lakinmohapatra** [angular/material#12090]
We need css utility classes included in angular material themes. 
It will help us in custimizations like tailwind.css or w3.css

**Comment by codymikol** [comment]
Why not just use tailwind alongside angular material?

**Comment by Splaktar** [comment]
Are you referring to Angular Material themes? This repo is for AngularJS Material. Are you using AngularJS with Tailwind?

**Comment by Splaktar** [comment]
The requested feedback was not provided. There is nothing actionable here.
