### ISSUE TITLE
Dropdowns don't actually drop down, they drop OVER

### ISSUE THREAD

**Issue by cfoxy17** [angular/material#12108]
Just because I don't have a stackblitz for each of every 500 issues there are with angular material doesn't mean it's not an issue and also doesn't mean the issue isn't easily replicable without a stackblitz. 

`

                                    <mat-form-field>

						

						<mat-select matNativeControl placeholder="Monthly">

							<mat-option value="monthly">Monthly</mat-option>

							<mat-option value="quarterly">Quarterly</mat-option>

							<mat-option value="biannually">Biannually</mat-option>

							<mat-option value="yearly">Yearly</mat-option>

						</mat-select>

                                   </mat-form-field>

`

Before clicking:

![image](https://user-images.githubusercontent.com/50955085/121754577-fc585880-cae2-11eb-8ec4-7f0941f68d41.png)

After clicking:

![image](https://user-images.githubusercontent.com/50955085/121754549-e77bc500-cae2-11eb-9f85-f91e7f6047a0.png)

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
