### ISSUE TITLE
Ripple Effect Still Present After Click, Despite disableRipple Being Set

### ISSUE THREAD

**Issue by cfoxy17** [angular/material#12104]
Steps to reproduce:

1. Click the calendar icon
2. Click away from the calendar icon
3. See that the ripple effect is still there after

https://stackblitz.com/edit/angular-material-disable-ripple-animation-taekj8?file=app%2Fapp.component.html

![image](https://user-images.githubusercontent.com/50955085/121748935-d2e5ff80-cad7-11eb-9e00-b45bc1b31bb2.png)

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
