### ISSUE TITLE
Angular Date Picker Calendar Icon Size, Padding, Background color, are all not easily customizable

### ISSUE THREAD

**Issue by cfoxy17** [angular/material#12105]
The default size of Angular Material's Date Picker is massive. Angular Material components are hardly visually customizable and should be able to be changed with simple CSS/SCSS.

There is little to no documentation on how to change the height, width, color, padding, etc. in the documentation at
https://material.angular.io/components/datepicker

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
