### ISSUE TITLE
floatLabel=never + appearance="outline" causes selected option to not be centered if no mat label is provided

### ISSUE THREAD

**Issue by cfoxy17** [angular/material#12106]
![image](https://user-images.githubusercontent.com/50955085/121753301-1d6b7a00-cae0-11eb-9219-f9f0349a83d0.png)

The default size is also way too big.

I tried to make a stack blitz of this issue but for some reason "appearance = outline" is not supported by stackblitz as it is still showing the default appearance type.

Code to replicate since the stackblitz I added doesn't show the appearance as outline for some reason: 

`

                                         <mat-form-field appearance="outline" floatLabel=never>

						

						<mat-select matNativeControl placeholder="Monthly">

							<mat-option value="monthly" selected>Monthly</mat-option>

							<mat-option value="quarterly">Quarterly</mat-option>

							<mat-option value="biannually">Biannually</mat-option>

							<mat-option value="yearly">Yearly</mat-option>

						</mat-select>

					</mat-form-field>
`

https://stackblitz.com/edit/angular-material-disable-ripple-animation-taekj8?file=app%2Fapp.component.html

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
