### ISSUE TITLE
Unable to have both a placeholder and a floating label

### ISSUE THREAD

**Issue by cfoxy17** [angular/material#12107]
I would attach a stackblitz for this issue but for some reason stackblitz does not support appearance="outline" mat-form-fields. 

As you can see in the below code I am trying to make the text "frequency" appear as a floating label above the default value / placeholder value "Monthly". This works for appearance "fill" but not "outline".

UPDATE: this is also not working for the default appearance type / no appearance specified.

Example code: 
`

					<mat-form-field appearance="outline">
						<mat-label>Frequency</mat-label>
						<mat-select matNativeControl placeholder="Monthly">
							<mat-option value="monthly" selected>Monthly</mat-option>
							<mat-option value="quarterly">Quarterly</mat-option>
							<mat-option value="biannually">Biannually</mat-option>
							<mat-option value="yearly">Yearly</mat-option>
						</mat-select>
					</mat-form-field>

`

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
