### ISSUE TITLE
was angular material a last minute project?

### ISSUE THREAD

**Issue by cfoxy17** [angular/material#12109]
`

                                       <mat-form-field appearance="fill" floatLabel=never>

						

						<mat-select matNativeControl placeholder="Monthly">

							<mat-option value="monthly">Monthly</mat-option>

							<mat-option value="quarterly">Quarterly</mat-option>

							<mat-option value="biannually">Biannually</mat-option>

							<mat-option value="yearly">Yearly</mat-option>

						</mat-select>

					</mat-form-field>

`

![image](https://user-images.githubusercontent.com/50955085/121754986-ff077d80-cae3-11eb-99af-33ed68f3c0f3.png)

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
