### ISSUE TITLE
There is a problem with the example

### ISSUE THREAD

**Issue by rodavid5** [angular/material#12116]
https://material.angular.io/components/table/examples#table-generated-columns

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
