### ISSUE TITLE
hide-sm and hide-gt-sm issues 

### ISSUE THREAD

**Issue by raghavmac** [angular/material#1212]
I was trying to hide some elements according to the device pixels and noticed somethings.

    hide-sm

It actually shown on mobile and hidden on larger devices. But what in the documentation mentioned is inverse - **I'm hidden on mobile and shown on larger devices.**

    hide-gt-sm

The above doesn't work for me. And not only this, all the hide attributes that uses **gt** doesn't work.

I'm using v0.5.0

**Comment by ruiaraujo** [comment]
0.7.0-rc3 is out.

You should test again with this version.

**Comment by PaulMougel** [comment]
As you can see on the landing page of the documentation:
![image](https://cloud.githubusercontent.com/assets/1788596/5788832/18839268-9e4e-11e4-9032-6f40e5f3f665.png)
the docs are built for a specific commit, in this case [v0.7.0-rc3 - SHA ec53d1a](https://github.com/angular/material/commit/ec53d1a). You're reading a newer version of the docs, which explains why these attributes don't work as expected.

Previously, `hide-sm` meant "hidden on any greater than small", which meant that the content was displayed on a phone, but hidden on anything else. This has proven to be difficult to grasp, so the behavior was changed in later versions.

You can either upgrade angular-material to the latest version; or [build the documentation for your particular version](https://github.com/angular/material/blob/master/docs/README.md).

**Comment by ranbuch** [comment]
Hi,
I'm using angular-material version: 1.0.0-rc7-master-2ab3075
When using hide-sm the element is shown on a 599px screen and smaller.
Replacing hide-sm with hide-phone doesn't work either.

How should I install angular-material latest version? I'm using:
npm install http://github.com/angular/bower-material/tarball/master

Thank you.
