### ISSUE TITLE
card actions- add center alignment in card.d.ts

### ISSUE THREAD

**Issue by chakrachi** [angular/material#12127]
please allow for center keyword in alignment for card actions

export declare class MatCardActions {
    /** Position of the actions inside the card. */
    align: 'start' | 'end' | 'center';
}

it works fine when added

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
