### ISSUE TITLE
Md-Dialog Box is not draggable and Movable so there should be option for  drag and drop. If there is already supported please give me coed

### ISSUE THREAD

**Issue by mcq-test** [angular/material#12133]
# AngularJS Material is in LTS mode

We are no longer accepting changes that are not critical bug fixes into this project.
See [Long Term Support](https://material.angularjs.org/latest/#long-term-support) for more detail.

## Documentation Feedback

**Affected documentation page URL:**

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the enhancement.
