### ISSUE TITLE
Problem using Content-Security-Policy with Print Syle

### ISSUE THREAD

**Issue by jenskelkel** [angular/material#12140]
I set the Content-Security-Policy in Webserver
Then I got the folling error in Browser:

_Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present._

The Problem is the following Line in the index-html
```html
<link rel="stylesheet" href="styles.d65f2e5b705f26f2.css" media="print" onload="this.media='all'">
```

Angular generate this Line automatically.

How can I fix this problem. I don't want use unsafe-inline or so

Thanks for help

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our **required** issue template. 

Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

Additionally, you may want to read through https://github.com/angular/angular/issues/37631.
