### ISSUE TITLE
Radio button (mat-radio) Click effect not disappear until focus lost

### ISSUE THREAD

**Issue by carbdias** [angular/material#12148]
Is there any way of changing the css of the various states of the mat-radio-button?
I cannot find info anywhere.

Similar issue with no explanation: 14290#

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
