### ISSUE TITLE
error An unexpected error occurred: "https://registry.npmjs.org/@angular%2fanimations: unable to get local issuer certificate".

### ISSUE THREAD

**Issue by luansevla** [angular/material#12144]
**error An unexpected error occurred: "https://registry.npmjs.org/@angular%2fanimations: unable to get local issuer certificate** on install `npm @angular/material`

![image](https://user-images.githubusercontent.com/22417175/149817171-58c05f60-63e6-4377-afaa-b1cb3119bf1f.png)

## Bug Report

![image](https://user-images.githubusercontent.com/22417175/149817106-678ace8b-2dbb-4563-9c3f-480e5e0554ad.png)

![image](https://user-images.githubusercontent.com/22417175/149817317-bc1ed7ef-3662-43ef-9ecf-98c6954f0b09.png)

![image](https://user-images.githubusercontent.com/22417175/149817362-6db25233-ea74-4723-aef9-df7efbb4cb8f.png)

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.

This appears to be a local configuration issue. You mention `npm @angular/material` which I assume you meant to be `npm i @angular/material`, but then the output mentions `(yarn)`.
