### ISSUE TITLE
MatDatePicker implementation issue: Cannot read properties of undefined (reading 'subscribe') for MatDatepickerInputBase

### ISSUE THREAD

**Issue by carbdias** [angular/material#12157]
Hello, I'm trying to implement a basic DatePicker.
I have already tried several alternatives from the documentation, but I always receive this error.
Any idea why it is ocurrying and how to solve it?

core.js:6498 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'subscribe')
TypeError: Cannot read properties of undefined (reading 'subscribe')
    at new MatDatepickerInputBase (datepicker.js:3041:1)
    at new MatDatepickerInput (datepicker.js:3286:1)
    at NodeInjectorFactory.MatDatepickerInput_Factory [as factory]
  ...
    

Thank you,
    
Carlota

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
