### ISSUE TITLE
mdTooltip strange error

### ISSUE THREAD

**Issue by coolsebz** [angular/material#1219]
I'm trying to create some kind of progression and I'm showing certain tooltips (one at a time) in a specific order. This is what i get when i hover over the buttons after the tooltip sequence has been completed

```
 Error: [$compile:nonassign] Expression 'tooltipNumber === 2' used with directive 'mdTooltip' is non-assignable!
http://errors.angularjs.org/1.3.8/$compile/nonassign?p0=tooltipNumber%20%3D%3D%3D%202&p1=mdTooltip
    at http://localhost:3000/bower_components/angular/angular.js:63:12
    at parentSet (http://localhost:3000/bower_components/angular/angular.js:7654:25)
    at parentValueWatch (http://localhost:3000/bower_components/angular/angular.js:7667:23)
    at Object.regularInterceptedExpression (http://localhost:3000/bower_components/angular/angular.js:12833:16)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:14217:40)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:14488:24)
    at http://localhost:3000/bower_components/angular/angular.js:16214:36
    at completeOutstandingRequest (http://localhost:3000/bower_components/angular/angular.js:4902:10)
    at http://localhost:3000/bower_components/angular/angular.js:5282:7
```

Does anybody have any ideas / tips on how do avoid this happening?
(I'm sorry if it's a repost, i've searched for md-tooltip on all the issues and couldn't find something similar to my issue)

**Comment by coolsebz** [comment]
just an information for anybody that might stumble onto somewhat of a similar issue, what i did is a lot like a cheap trick but it gets the job done, here it is:

- created an additional boolean flag to tell whether it's tooltip showing time or not 
- duplicated the buttons that were having the tooltips shown
- removed tooltips on the duplicated buttons
- used the new flag to ng-show the 'real' buttons when not in tooltip mode
so this basically gives me normal, good ol' buttons when not in tooltip mode and avoids creating the specified error

**Comment by ajoslin** [comment]
The `md-visible` attribute has to be an assignable/bindable expression. Think of it like an ng-model.

**Comment by fgborja** [comment]
So, is possible to disable the tooltip without using the trick of duplicated buttons?

**Comment by Alevale** [comment]
Worked with me if instead of using `md-visible="campaignCtrl.createCampaign && voucherForm.$invalid"` I use `md-show="campaignCtrl.createCampaign && voucherForm.$invalid"`

Seems like the md-visible looks for a variable and it can't evaluate an expression...
