### ISSUE TITLE
mdTooltip - allow tooltip to be positioned top/bottom/left/right

### ISSUE THREAD

**Issue by cmjacques** [angular/material#1220]
I noticed that this functionality was considered in issue [354](https://github.com/angular/material/issues/354).

Looking at the [spec](http://www.google.com/design/spec/components/tooltips.html) it seems that tooltips are not limited to opening from top or bottom.

Being able to position tooltips left and right (as long as there is enough space) would come in very handy in my latest project.

Thanks and keep up the good work.

**Comment by mzbyszynski** [comment]
:+1: 

One example of this are the fab buttons fixed to the lower right portion of the screen in Google Inbox. They each have tooltips that float to the left of each button.

**Comment by epelc** [comment]
+1 Would be nice to override the default behavior but can it still be smart and move itself if its near the edge of your screen.

**Comment by cmjacques** [comment]
I'm very new to git, but I managed to fork the code and make the following changes -

* Tooltips can now be opened 'top', 'bottom', 'left' or 'right' by setting the md-direction attribute. The default direction is 'bottom'.

* If the requested direction would cause the tooltip to open outside the viewport (or too close to the edge) then it will open in the opposite direction.

I'm not quite game to create a pull request (just yet), but you can check out my changes [here](https://github.com/cmjacques/material/tree/master/src/components/tooltip)

**Comment by ejbaker** [comment]
Would it be possible to do md-direction "top right", "top center", "top left"...? The default of having it always be centered is really throwing off some lengthy objects I want to add a tooltip to.

**Comment by Splaktar** [comment]
@ejbaker that would be a good question for the ngMaterial forums, but not for a closed issue. You could link this issue to your forum post though. A CodePen demo would also be helpful.
