### ISSUE TITLE
md-slider: Add vertical sliders

### ISSUE THREAD

**Issue by maxee** [angular/material#1221]

**Comment by ilanbiala** [comment]
+1.

**Comment by Snap974** [comment]
+1

**Comment by ThomasBurleson** [comment]
@maxee, @ilanbiala - you are welcome to submit a PR for this feature request.

**Comment by axelson** [comment]
+1

**Comment by dementorpasha** [comment]
+1

**Comment by ThomasBurleson** [comment]
Per the UX Design Team:

> This feature does seem like a possible use-case. It doesn't scale well when things have labels, which would take up horizontal space.

**Comment by 12kb** [comment]
+1

**Comment by nshahpazov** [comment]
+1

**Comment by AleksueiR** [comment]
+1

**Comment by ThomasBurleson** [comment]
The AM core team is focused on critical features for v1.0 release. We would, however, welcome a PR to enhance Sliders with vertical orientations.

**Comment by royjavelosa** [comment]
Hi I went here also looking for a vertical slider feature from Angular Material.  Is there an alternative way of achieving this while waiting for the official feature to be added? I mean to make the existing sliders to render vertically?

**Comment by ceoaliongroo** [comment]
@CarmenPopoviciu I like  to contribute in this issue, do you have a PR already?

**Comment by CarmenPopoviciu** [comment]
@ceoaliongroo no, I don't have one yet. Do you have something in the working?

**Comment by ceoaliongroo** [comment]
Nothing concrete yet, but i could give some shape and open a PR, from there we could see... 
@CarmenPopoviciu, Sounds good?

**Comment by CarmenPopoviciu** [comment]
@ceoaliongroo definitely. If I can help with anything just ping me :)

**Comment by ThomasBurleson** [comment]
Fixed with SHA e0abeb4dc46a1753616a911fe54f14d8f1148a25
