### ISSUE TITLE
position absolute / fixed

### ISSUE THREAD

**Issue by Martodox** [angular/material#1222]
Hi there.
I am using material for some time now and I've noticed some unexpected behavior with many elements that should be visible everywhere.
mdDialog, mdSidenav, mdToast are the ones I am sure of, and rest of elements that should be in view could be effected as well too.

They all use position absolute, top:0 which is fine for content not bigger than screen's height. If you go over that and use mdDialog on a long list then it becomes invisible and unasable. It stays on the top of the content along with md-backdrop.

Is that an issue or was that intended. If it is an issue let me know and I'll PR a fix.

**Comment by rschmukler** [comment]
The dialogs have been fixed in `0.7.1`. Follow the progress on toasts in #1106 and #826
