### ISSUE TITLE
FAB looks really bad  inside a  toolbar

### ISSUE THREAD

**Issue by margielm** [angular/material#1223]
Hello,

trying to use FAB inside toolbar but it just looks really bad (I mean the opacity). 
![image](https://cloud.githubusercontent.com/assets/684828/5793437/af10bdfa-9f43-11e4-97d0-4cc7681dac82.png)
```html
<md-toolbar>
        <h2 class="md-toolbar-tools md-toolbar-tools-bottom">
            <md-button class="md-fab md-button md-fab-bottom-right">Save</md-button>
        </h2>
    </md-toolbar>
```

Granted.. I don't know If this is how I should be using that but the documentation is extreamlly poor about FABs in general.

**Comment by epelc** [comment]
@margielm I think you need to add the `md-primary` or `md-warn` classes to give it some color. But it may be a bug that the background doesn't default to white.

**Comment by rschmukler** [comment]
@epelc is spot on, try adding `md-accent`, `md-primary` or `md-warn` to make the FAB have some contrast.

I agree that we should default it to white (I'll fix this). Not sure why the alignment is screwed up. Check out [this jsfiddle](http://jsfiddle.net/rschmukler/k6xqufpo/) for an example of getting alignment to work properly.

**Comment by margielm** [comment]
I think that alignment is ok, FAB should be n the edge of the toolbar - not in the middle of it.

My complain was only about the background color. As you have said, it should be white (or some other color).

**Comment by mckenzielong** [comment]
> I think that alignment is ok, FAB should be n the edge of the toolbar - not in the middle of it.

While it seems like it should be 'snapping' to the edge of a toolbar when given the proper class, it certainly does not seem like md-fab-_**top**_-right is the way to do so in a toolbar -- css defaults reverse end up reversing this behavior in the calculation for bottom and top since the containing element isn't very large...

**Comment by margielm** [comment]
thanks
