### ISSUE TITLE
Font type is different

### ISSUE THREAD

**Issue by raghavmac** [angular/material#1224]
I'm using 0.6.1

**font-type** on previous version was looking same as in the website but in the above version, the font is different. 

> Font on 0.5.0 - 

![1](https://cloud.githubusercontent.com/assets/3517242/5793446/d272eef0-9f69-11e4-9a77-a413a34f6de2.JPG)

> Font on 0.6.1 - 

![2](https://cloud.githubusercontent.com/assets/3517242/5793447/d9e4ad4a-9f69-11e4-8346-dedcc28329c6.JPG)

**Comment by marcysutton** [comment]
Hello! A little more information will help us with this issue, it's hard to tell from the small screenshots what exactly is happening. 

Which typeface is showing in each screenshot, and can you compare it to the [latest tag](https://github.com/angular/material/tree/v0.7.0-rc3)? The 0.7.1 release should be out next week.

If that doesn't shake out any answers, which browser/OS are you using?

**Comment by marcysutton** [comment]
Closing issue as I believe this is not a problem. If it shows up again, let us know and we can reopen.

**Comment by raghavmac** [comment]
I mean, how to have the font-type that is used on the official site(i.e on the Card)?
