### ISSUE TITLE
Please consider lumX, Polymer paper elements, and Material UI

### ISSUE THREAD

**Issue by antitoxic** [angular/material#1225]
Implementing Google material design is an awesome thing! I adore that fact that people are doing it.

It puzzed me though that there's another Angularjs implementation of Google Material Design:
https://github.com/lumapps/lumX

Which is my first question: 1) **Is it possible to negotiate some sort of merging the two?**

2) **The second thing** is that I've also digged into [Polymer paper elements](https://www.polymer-project.org/components/paper-elements/demo.html). There are some work done there as well. It's interesting for me because **both Anguarjs and Polymer are powerd by Google**. Is it possible to unify the two in some way? At least making Polymer components and Anguar share the same animations and styling? Polymer components can use stylesheets, so if Anguar Material allows compilation of per-component styling and some selector name customisations they can both benefit?

**And the last thing** 3) - There's a facebook reactjs implementation of material design called [Material UI[(http://callemall.github.io/material-ui/). In my opinion it has the best dropdown animations and some other very carefully crafted details. Perhaps it could of use to share some styling and animation, may be contact the developers?

**Comment by gustavohenke** [comment]
I believe some collaborator will close the issue and say that it's more appropriate for [the forums](https://groups.google.com/forum/#!forum/ngmaterial).
But, about question 1, [this is already happening](https://groups.google.com/forum/#!msg/ngmaterial/DzaafF64Ek4/B0M9EOsHYbsJ).

**Comment by marcysutton** [comment]
Hi, yes this is a better discussion for the forums. But I can add some insights I do know. Firstly, yes, there is more than one implementation of Material Design. The nice thing is that developers can pick one that fits in with their front-end stack. Which ones shake out, remains to be seen. But options are good for all of us. That said:

1) We've started working with LumX on a few efforts, as you can see in the forum. A few things that set Angular Material apart: accessibility was a first-class citizen very early on, as well as mobile performance and test coverage. We can learn from each others' efforts, but Angular Material will continue on as an official Google project.

2) Angular Material and Polymer's Paper are currently separate efforts, using different web technologies. I'm not aware of any plan to merge the projects right now. But I personally would like to see accessibility improve in those components before I could endorse them. 

3) Same thing with the React/Material-UI version–there may be things we can learn from the creation of that demo library. But it was released without care for accessibility, which in my opinion limits its use. Hopefully we'll see improvements to it in the future.

**Comment by antitoxic** [comment]
Discussion continues: https://groups.google.com/forum/#!topic/ngmaterial/BGUMxqpA42k
