### ISSUE TITLE
Dynamic Theming of md-slider and md-progress-<bar-type>

### ISSUE THREAD

**Issue by Darwesh27** [angular/material#1228]
I want to theme my md-slider and md-progress bar based on ng-value/value. i.e if value < 3 theme = red, if value > 7 theme = green, else theme = primary. I tried doing it by passing in string values in md-theme="{{theme()}}", where theme is a function which will return a string. But it has no effect. These directives adapt the theme passed to them on the start and then never change it..

**Comment by mzbyszynski** [comment]
Are you using the `md-theme-watch` directive? Take a look at https://material.angularjs.org/#/Theming/04_multiple_themes and scroll down to the section on Dynamic Themes.
If you still can't get it to work you should post a plunkr that demonstrates the issue to the [ngmaterial forum](https://groups.google.com/forum/#!forum/ngmaterial) and someone should help you get it sorted out.

Hope that helps!

**Comment by Darwesh27** [comment]
Ahh. Thats great. Sorry I didn't see the updated documentation. Thanks
