### ISSUE TITLE
md-tooltip: Doesn't work inside md-checkbox

### ISSUE THREAD

**Issue by epelc** [angular/material#1232]
If you try to put a tooltip inside of a checkbox it doesn't work. It ends up removing the tooltip from the generated html.

```
 <md-checkbox ng-model="quote.Options.Other.SingleShipment">Single Shipment
        <md-tooltip>Some description about this</md-tooltip>
    </md-checkbox>
```

![image](https://cloud.githubusercontent.com/assets/5204642/5806768/64344f70-9fea-11e4-9955-115ecc12897c.png)

**Comment by BobbieBarker** [comment]
This issue and #1101 maybe linked.

**Comment by guilhermecvm** [comment]
+1

**Comment by Anujndls** [comment]
![image](https://user-images.githubusercontent.com/11572866/26921607-3e993b62-4c5a-11e7-85c8-9f8098191070.png)
Its fine with tooltip but the events are not working, please help along ng-model because I am trying to toggle container along checkbox checked.
