### ISSUE TITLE
Using themes from 0.6.1

### ISSUE THREAD

**Issue by ehajredini** [angular/material#1233]
I've updated to 0.7.0-rc3, and I have problems with components using themes from previous version. How to fix this  ? Can I use themes with this version >

**Comment by tiny-dancer** [comment]
https://github.com/angular/material/issues/1162

**Comment by tiny-dancer** [comment]
ran into the same issue lol

**Comment by naomiblack** [comment]
Can you provide an example with plunkr or codepen so we can see what the issue is? It is hard to tell from this report.

**Comment by marcysutton** [comment]
Closing old issues. If the original problem persists, let us know and we can revisit it.
