### ISSUE TITLE
Object element inside md-icon not rendering properly on Chrome Windows

### ISSUE THREAD

**Issue by aksharpatel47** [angular/material#1234]
I'm running Chrome 64 bit on Windows 7. The Object element inside md-icon is showing image of a blocked element. I have tried re-installing chrome and deleting all the data just to make sure that some extension is not causing that. The bug occurs with both stable and beta chrome.

On the Chrome on my Mac, however, the icons are rendered properly.

![capture](https://cloud.githubusercontent.com/assets/8004533/5811770/fc6e78f0-a081-11e4-85f7-b30e6b20d166.PNG)
![capture1](https://cloud.githubusercontent.com/assets/8004533/5811790/3afbcaf0-a082-11e4-91e7-7958fc88ea54.PNG)

**Comment by marcysutton** [comment]
Hi, mdIcon is currently being worked on, so this behavior will go away very soon. https://github.com/angular/material/issues/1042
