### ISSUE TITLE
md-slider: changes to min and max don't get noticed during runtime

### ISSUE THREAD

**Issue by maxee** [angular/material#1237]
If I create a slider with the initial values of lets say min="0" and max="100" and change the min- and max values during runtime, the slider does not update its range according to the new values. Instead it uses still the old ones (0 and 100).

This is reproduceable in the demos. Just change the values of min/max and aria-valuemin/aria-valuemax.

**Comment by PaulMougel** [comment]
Seems to be working for me?
http://plnkr.co/edit/QfnTmLB5wusalwbelQXq?p=preview

**Comment by maxee** [comment]
@PaulMougel strange, your plunker works for me, too. I'll check if there's something wrong with my setup.

**Comment by maxee** [comment]
@PaulMougel yep, my mistake.

**Comment by PaulMougel** [comment]
@maxee Awesome :smile: Can you describe what was your error? It can be helpful for future readers.

**Comment by maxee** [comment]
The Problem was, that my bound value was null/undefined at the beginning. It changed only to something valid after some time. 
```
max="{{(value) || defaultValue}}"
```
does the trick.

**Comment by ilanbiala** [comment]
@maxee what about `ng-attr-max`?
