### ISSUE TITLE
mdInputContainer: Label should be enforced

### ISSUE THREAD

**Issue by marcysutton** [angular/material#1242]
The new `<md-input-container>` requires developers to include native elements in their markup. This change was made to account for the many attributes and race conditions that made transclusion impossible. As a result, developers are able to implement `mdInputContainer` without a `<label>` element or `aria-label` attribute on the input, resulting in inaccessible forms. To encourage developers to create accessible inputs, Angular Material should run the `$mdAria.expect()` utility. This first checks for text to use for an [accessible name](http://www.w3.org/TR/wai-aria/roles#namecalculation_header) for the input (which is required for assistive technologies), and if no text is found, it logs a warning to the console about a missing label. 

**Prerequisites: `$mdAria` needs refactoring to work inside of `ng-repeat` and `ng-if`.**
 * Refactor to use `compile`: https://github.com/angular/material/issues/608
 * `ng-if`: https://github.com/angular/material/issues/1094
 * `ng-repeat`: https://github.com/angular/material/issues/507

**Comment by matthewrfindley** [comment]
Merged and fixed in https://github.com/angular/material/pull/2397
