### ISSUE TITLE
firefox performance issues

### ISSUE THREAD

**Issue by seiyria** [angular/material#1245]
Hey all,

I'm getting some pretty bad performance in firefox with my app. I've tried using firefox-batarang as well as the firefox profiler to narrow it down as far as I can, but my application is still mostly unusable. I've been trying on firefox latest.

Here's my app live: http://webfe.idle.land (you can use TestCharacter / test to get past the auth screen).

I've gone through and removed mostly every `$scope.$watch` statement, changed a lot of my bindings to use the `::` bindonce syntax, and changed all of my `ng-repeat` statements to use `quick-ng-repeat` instead. It's gotten a lot better, but it's still a ways away.

That said, I'm not really sure if it's a problem with angular/material, or firefox, or something else I'm doing, because http://material.angularjs.org seems to work fine in firefox.

Any ideas what I can do to improve performance, if any?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by hmillet** [comment]
I meet exactly the same problem. And I'm not using material.

My app is a little "loud", several ng-repeat and watchers.

I can use and navigate through my app with a very  good usability on all navigators (Chrome, Opera, IE, Safari) except Firefox. At each click, my app is frozen for 1.5 seconds...

Lokking at the performance profiler, I can see, for a same scenario and the same click, that $digest took :
* On Opera (29.0), 28 ms
* On Firefox (38.0.1), 1401 ms

@seiyria : Did you find a way to solve your trouble ?
