### ISSUE TITLE
Can not click focus input inside mdBottomSheet on mobile devises

### ISSUE THREAD

**Issue by FUT** [angular/material#1248]
My previous issue #553 was closed but in fact it is not fixed. I did not find a way to reopen it so here is a new one (sorry if I am wrong). 

I upgraded the angular material to 0.7.0-rc3 (also tested on 0.5.1) but the bug is still there. Here is the detailed explanation and my workaround: http://stackoverflow.com/questions/27328271/use-inputs-in-angularjs-material-bottom-sheet

Could you please take a look?

**Comment by ThomasBurleson** [comment]
md-text-float has been deprecated; please use `md-input-contiainer` @ https://material.angularjs.org/#/demo/material.components.input

**Comment by ThomasBurleson** [comment]
[Bower-material Readme](https://github.com/angular/bower-material) has full details on CDN and using files directly from the repository.
Also you can fork the [Angular Materail CodePen](http://codepen.io/ThomasBurleson/pen/LEZvWw) as an easy way to build a **issue demo** using latest source from the master branch.
