### ISSUE TITLE
$mdDialog: onRemove() doesn't check if the dialog was loaded

### ISSUE THREAD

**Issue by epelc** [angular/material#1249]
Perhaps the title should be different but if you try to open a dialog which is loaded via a url and you do not have a connection it you will get an exception in the dialogs [onRemove()](https://github.com/angular/material/blob/01bbc4c1f56033113a34a66b36e2f30cf1ca661a/src/components/dialog/dialog.js#L390)

**Comment by ThomasBurleson** [comment]
Sounds like a great case for a unit test.

**Comment by epelc** [comment]
I also found some issues with `$mdToast`s `onRemove()` when you throw an error but I haven't been able to pinpoint it yet.
