### ISSUE TITLE
md-tabs: Invert color(or white background)

### ISSUE THREAD

**Issue by epelc** [angular/material#1250]
It would be nice if there was perhaps an `md-inverted` class for `md-tabs` so that we can invert(not sure if it should be called this) the color to have a white background. Sort of like google+'s tabs on your profile page.

![image](https://cloud.githubusercontent.com/assets/5204642/5841943/f357f8b6-a16e-11e4-8287-dca09019c850.png)

**Comment by epelc** [comment]
I forgot we arent supposed to ask for things in the issues I'll move this to the forums.

**Comment by ThomasBurleson** [comment]
Actually @epelc this is a feature enhancement; appropriate for here.

**Comment by ThomasBurleson** [comment]
@robertmesserle - I think this highlights the need to provide better styling/theme options to Tab.

**Comment by epelc** [comment]
@ThomasBurleson Thanks I just noticed I read the readme backwards and though I couldn't post feature requests here.

**Comment by ThomasBurleson** [comment]
Specific component "feature requests" and "bug reports" are encouraged here.
Discussions of usages, applications, integration, how-tos.... all are best presented on the Forum.

**Comment by robertmesserle** [comment]
@ThomasBurleson What do you think of something like `md-light` or `md-dark` to specify white and black background versions?

**Comment by jamm** [comment]
"thanks", @epelc, now I can't use md-tabs.

**Comment by epelc** [comment]
@jamm Why not? I think you have to add `md-primary` now for them to not be white.

**Comment by jamm** [comment]
@epelc because ugliness of white tabs if unacceptable. Not sure, where I can add `md-primary` to remove this so-much-awaited beauty.

**Comment by epelc** [comment]
@jamm Add `class="md-primary"` to your `<md-tabs>`

**Comment by jamm** [comment]
yes, just figured it out. Thanks for advice. Although I still hate you for this change.

**Comment by gustavohenke** [comment]
Hm, this feature is kinda weird, but I can live with it, even though I preferred the previous behavior...

**Comment by pved** [comment]
is there a way to show all the borders of the tabs, to make them look like traditional tabs. There is a requirement for this to make it easy for people using screen readers. Any thoughts?
