### ISSUE TITLE
$mdToast: detachSwipe undefined exception

### ISSUE THREAD

**Issue by epelc** [angular/material#1251]
Sometimes when I create a toast I get an error caused by `detachSwipe()` being undefined. The line can be found [here](https://github.com/angular/material/blob/08ebff4405f75d305c24eca3549668bbc84d7ce8/src/components/toast/toast.js#L214). The toast then freezes and stays their forever sometimes the background also becomes completely black too.

I can't reliably reproduce this it just seems to happen more often from toasts that come from my exception catch all. However it's only a small percentage of them and happens more often when several exceptions happen at once. Maybe it's from my use of `$injector`.
```
asc.factory('$exceptionHandler', function($injector) {
    return function(exception, cause) {
        var $mdToast = $injector.get("$mdToast")
        $mdToast.show($mdToast.simple()
            .position('bottom right')
            .content('Error: ' + exception))
        console.log('got a new exception:', exception, cause)
    }
})
```

Is anyone else having a similar problem? I seen a few people had issues with toasts staying open forever.

**Comment by gkalpak** [comment]
Not directly related to this issue, but why would you use the injector, let alone call `get` twice ?

**Comment by epelc** [comment]
@gkalpak My bad for calling get twice. But I used `$inject` because `$mdToast` caused a circular dependency error.

**Comment by ajoslin** [comment]
This is out-of-date with the newest version of Angular Material.
