### ISSUE TITLE
md-button: Set background color to white when using "md-raised"

### ISSUE THREAD

**Issue by epelc** [angular/material#1256]
I think the `md-raised` class should set the button background to white. If your using `md-raised` without `md-primary` or `md-accent` etc then you button has no background color set and just appears with an ugly/hard to read shadow. However adding the white background makes any raised button easy to read no matter where it is.

Note this is not an issue if your using `md-raised` with `md-primary` or another class which sets the color.

**Comment by epelc** [comment]
I didn't notice at first but apparently there it has a very transparent background. Is this too spec or can we make it stand out more?

**Comment by gkalpak** [comment]
Didn't look into the spec, bur shouldn't the theme provide a default color for raised buttons ?
