### ISSUE TITLE
I can get the input example to work

### ISSUE THREAD

**Issue by capaj** [angular/material#1258]
I think I am a fairly seasoned developer. I usually don't have a problem running any piece of frontend/backend code or using 3rd party libraries. But for the love of god, how do I make angular-material inputs to look like the ones I see https://material.angularjs.org/#/demo/material.components.input. In my desperation, I created an empty html with just the needed dependencies and nothing else. Then I copied the html from the example and it still doesn't work. What am I missing??

https://gist.github.com/capaj/6541cb88cba5e9e604e9

**Comment by capaj** [comment]
of course, it works when I get the latest version. I just did not expect that when you already have it in the docs. I know it is pain to have versioned documentation like Angular...but sometimes it is worth it.

**Comment by PaulMougel** [comment]
Documentation versionning is indeeded planned: #918

**Comment by capaj** [comment]
@PaulMougel good to know
