### ISSUE TITLE
Trying to do a md-toolbar with md-scroll-shrink and a fixed Tab/Search Box below of md-toolbar.

### ISSUE THREAD

**Issue by ekaitzht** [angular/material#1259]
Hi, I am trying to do [this](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B0NGgBg38lWWU0RhQy1ab3FWOWM/patterns-scrollingtech-scrolling-070801_TabBar_xhdpi_003.mp4), which  is not the same like [this](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B0NGgBg38lWWcFhaV1hiSlB4aFU/patterns-scrollingtech-scrolling-070801_Flexible_Space_xhdpi_003.webm) because the content is not scrollable, about this feature people are discusssing here https://github.com/angular/material/issues/1053.

Should be this open for a new enhancement? or is possible to do with the current state of angular-material.

Thanks!

**Comment by EladBezalel** [comment]
Can you explain why its not the same? 
i opened an issue about it #1054

**Comment by ekaitzht** [comment]
If you see the Navigation Bar disappears and the Tab Bar goes to the top but in the second case the Navigation Bar is fixed. [here](http://www.google.es/design/spec/patterns/scrolling-techniques.html#scrolling-techniques-scrolling) are both examples and I think that behaviours are different.

**Comment by EladBezalel** [comment]
This is pretty much the same.. I will edit my issue just to be clear with it. thanks

**Comment by infacq** [comment]
hi has it been implemented?

**Comment by marminthibaut** [comment]
:+1:

**Comment by ismarslomic** [comment]
See this example: http://codepen.io/infacq/pen/ZGabYq

**Comment by Zephyr07** [comment]
Thanks ismarslomic it's work for me
