### ISSUE TITLE
Checkbox won't load as selected

### ISSUE THREAD

**Issue by bogdandjukic** [angular/material#1262]
I have an md-checkbox in a ng-repeat. It works fine, but when loading the page again, with some presets saved, it won't load checkbox as selected for the options that were selected and saved previously (ng check doesn't work on it).

Anybody have an idea what to try out in order to fix it?

**Comment by bogdandjukic** [comment]
Found a solution!
Added a ng-class with "md-checked" class instead of adding ng-checked.

**Comment by ThomasBurleson** [comment]
Currently `md-checkbox` only recognizes `ng-model` and does not recognize/acknowledge the `ng-checked`. This should be fixed.

**Comment by dhyegofernando** [comment]
:+1:

**Comment by ThomasBurleson** [comment]
@bogdandjukic - that is not the right fix to the issue. Simply use ng-model - http://codepen.io/ThomasBurleson/pen/MYvdNv

**Comment by cesarvega** [comment]
But this do not work inside a repeater how to you know what are your models if you have a repeater ?

`  <md-card-content>
      <div class="col-md-8 col-md-offset-4 col-xs-12" >
        <md-radio-group layout="row"
            ng-repeat="option in CheckListCtrl.OptionList track by $index">
          <md-checkbox  md-no-ink
              class="reponsive-display-list md-primary"
              data-fieldtypeid="{{CheckListCtrl.FieldTypeId}}"
              data-projectId=" {{CheckListCtrl.ProjectId}}"
              ng-click="CheckListCtrl.selectedCheckBoxValue($event)"
              ng-model="myModel">
              <div ng-attr-style="width: {{CheckListCtrl.labelSize}} !important">
                 {{option}}
              </div>
          </md-checkbox>
        </md-radio-group>
      </div>
  </md-card-content>`
