### ISSUE TITLE
mdForm mdInputContainer showing errorsmsgs before entering form

### ISSUE THREAD

**Issue by SanderElias** [angular/material#1266]
I created [this sample on plunker](http://plnkr.co/edit/M22sy0AI7Bax3Cop3OmI?p=preview) to demonstrate a few issues I'm having with forms. 

This is the first one, if I enter the page, before doing anything, the error-messages are displayed as you can see in the below picture. 
![image showing issue](https://lh3.googleusercontent.com/-xm6YrKw-6T8/VMCTDuQI0JI/AAAAAAABCIo/cmxy2rYyT9Y/s1600/errorlabels.PNG)

In my eyes this is wrong on multiple levels.
 1. Error's should only be visible after user interaction
 2. they should not appear in different formats (black/red)

**Comment by Frank3K** [comment]
Isn't (1) standard behavior? I always wrap ng-messages in an ng-if $dirty check. See: http://stackoverflow.com/questions/25634394

**Comment by ajoslin** [comment]
1) Customize your ng-messages as you see fit.
2) c3cad666368cc238644b6c9b1aaf1260cd763187

**Comment by SanderElias** [comment]
@ajoslin If you open my plunk, You will see that the error messages are still off. I can add an 
`ng-show='form.field.$dirty'` to hide the errors, to take care of this. 
However, they still are appearing in 2 different styles, although now I seem to be able to control when the styling takes place, I can not easily prevent them appearing them in different styles.
