### ISSUE TITLE
mdForm mdInputContainer should show error after user touching a field

### ISSUE THREAD

**Issue by SanderElias** [angular/material#1267]
I created [this sample on plunker](http://plnkr.co/edit/M22sy0AI7Bax3Cop3OmI?p=preview) to demonstrate a few issues I'm having with forms. 

When you enter the form, and tab through the fields, without actually changing anything, errors should be thrown. Now the errors are only shown after a user changes a field. Validations should be verified on blur.

**Comment by EladBezalel** [comment]
@ThomasBurleson I think 0.7.1 is the milestone you should label this, the error validation is assigned there..

**Comment by ajoslin** [comment]
Yeah, this is a big question. I arbitrarily decided that the errors should appear red after the form is invalid and dirty. 
Making it red after the form is touched & invalid sounds better.

We should provide a way to customize this, though.  Thoughts on an API?

```html
<md-input-container md-errored="myInput.$invalid">
  <input name="myInput">
</md-input-container>
```

`md-errored` would default to `myInput.$invalid && myInput.$touched`.

**Comment by SanderElias** [comment]
@ajoslin Well, the color should be the alert color for the theme right? And an error should be in that color, so there is no issue there. (I have an issue with them appearing before the users touched a field, but I separated that one out #1266)

I think the md-errored api is a good idea, as long as indeed the default is $invalid && $touched. If an field is invalid, and a user has touched the field, the error should be visible. In the current situation, an user can tab trough the entire form without getting a clue something is off. I don't think that is a good idea.

**Comment by gkalpak** [comment]
IMO, errors should always be displayed as errors (i.e. red or whatever color indicates an error). The developer should decide when to show the errors (e.g. `ngIf="myInput.$touched"`).

Providing a sensible default for that and allowing the developer to customize it, would be ideal. E.g.:

    <md-input-container md-show-errors="myInput.$dirty">...</md-input-container>
