### ISSUE TITLE
md-button single click

### ISSUE THREAD

**Issue by groupsvkg** [angular/material#1270]
Hi Team,

I have two page(A and B). Each page has one md-button in exactly same position.

md-button click on page A routes to page B

When i click md-button on page A then md-button on page B also gets clicked.

Also when i click md-button on page A for longer duration things work fine.

Looks like issue with md-button.

bower.json below
{
  "name": "i-collab",
  "version": "0.0.0",
  "dependencies": {
    "angular": ">=1.2.*",
    "json3": "~3.3.1",
    "es5-shim": "~3.0.1",
    "jquery": "~1.11.0",
    "angular-animate": "~1.2.0",
    "angular-resource": ">=1.2.*",
    "angular-cookies": ">=1.2.*",
    "angular-sanitize": ">=1.2.*",
    "font-awesome": ">=4.1.0",
    "lodash": "~2.4.1",
    "angular-socket-io": "~0.6.0",
    "angular-ui-router": "~0.2.10",
    "famous": "master",
    "famous-angular": "master",
    "angular-material": "master",
    "angular-messages": "~1.3.9"
  },
  "devDependencies": {
    "angular-mocks": ">=1.2.*",
    "angular-scenario": ">=1.2.*"
  },
  "resolutions": {
    "angular-animate": "1.3.x",
    "angular": "1.3.x",
    "angular-material": "master",
    "famous": "0.3.4"
  }
}

**Comment by PaulMougel** [comment]
Can you provide a Plunker that shows your issue? It will be easier for us to help you.
