### ISSUE TITLE
menu-item css

### ISSUE THREAD

**Issue by aryanbaghi** [angular/material#1271]
When using material v0.7.0-rc3-master (I think latest) there is no css about menu-item but in https://material.angularjs.org we saw it! I install it with bower, I think there is a mistake!

**Comment by PaulMougel** [comment]
As (sort-of) mentioned in #996, this class is only available for the Material docs; it not intended to be distributed in angular-material.

If you want to copy the CSS in your app, here are [the sources](https://github.com/angular/material/blob/74fe3eb19b097611ed17f2f1459a5682b043387a/docs/app/css/style.css#L97-L143).

**Comment by marcysutton** [comment]
@PaulMougel is correct! That CSS is for the docs only. You can read more about it in #996.
