### ISSUE TITLE
$mdToast.simple() with parent, it is supported? 

### ISSUE THREAD

**Issue by xavadu** [angular/material#1272]
Hello,

I want to display a $mdToast.simple() but append it to a parent,
it is possible?

Some example? If not, it should be an enhancement.

Thanks

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by xavadu** [comment]
Oh, true! sorry :) I confuse

**Comment by xavadu** [comment]
Ok! thanks
