### ISSUE TITLE
implementing a chat interface inside sidenav

### ISSUE THREAD

**Issue by koraytaylan** [angular/material#1273]
I am trying to implement a messaging interface inside sidenav.

I kind of managed to do it using column layout and flex but it gets messy when message count increase and overflow the flex container.

I wanted to ask some ideas on what would be a reliable way of doing it.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by koraytaylan** [comment]
oh yea sorry could you please delete this ticket all together
