### ISSUE TITLE
NuGet package request

### ISSUE THREAD

**Issue by Asesjix** [angular/material#1274]
Can a NuGet package please of "angular material" create and make available?
I develop in Visual Studio and would like to use for my Cordova project :)

Delighted, I would be happy!

**Comment by olakara** [comment]
I don't think that is a good idea.. Microsoft itself is moving to bower for client libraries. Have a look at this article from [Hanselman](http://www.hanselman.com/blog/IntroducingGulpGruntBowerAndNpmSupportForVisualStudio.aspx) .

**Comment by m4cx** [comment]
@olakara Agreed. Right tools for the features needed. Bower is the better place I think
