### ISSUE TITLE
Home page links not visible in IE10

### ISSUE THREAD

**Issue by HandsTest** [angular/material#1276]
Is IE 10 really supported ? 

The links in the home page for demos are not even visible in IE 10

![capture](https://cloud.githubusercontent.com/assets/10513809/5886649/5462749e-a3cf-11e4-88a1-89cd35b9897b.PNG)

**Comment by naomiblack** [comment]
It will be supported in 1.0. We're still working through a number of polish issues (including an update to the docs, coming soon). Thanks for the ping. Please do file bugs for issues you are seeing in IE 10 and 11.

**Comment by marcysutton** [comment]
That's odd. I'll be sure to check the docs redesign in IE10, which I'm hoping will get merged this week.

**Comment by csvan** [comment]
Since IE10 now that Edge has been released effectively falls outside the N-1 range, is it still going to be supported?
