### ISSUE TITLE
md-button and ng-switch multidir transclusion error

### ISSUE THREAD

**Issue by matteocrippa** [angular/material#1280]
I'm facing this issue that you can see [here](http://plnkr.co/edit/4YyGQiSupOlsnI04g6nn?p=preview).

Managing two md-buttons using an ng-switch raises a multidir transclusion [error](https://docs.angularjs.org/error/$compile/multidir?p0=ngSwitchWhen&p1=mdButton&p2=transclusion&p3=%3Cmd-button%20ng-switch-when%3D%22false%22%20class%3D%22md-fab%20md-primary%22%20md-theme%3D%22cyan%22%20aria-label%3D%22False%22%3E)

Using ng-if instead works fine.

**Comment by ThomasBurleson** [comment]
Unable to reproduce with Angular 1.3.11 and Angular Material 0.7.1.

**Comment by rishabhmhjn** [comment]
The following code results in the same error:

```html
<md-dialog-actions ng-switch
  on="step"
  layout>
  <md-button ng-switch-when="0">
    button 0
  </md-button>
  <md-button ng-switch-when="1">
    button 1
  </md-button>
</md-dialog-actions>
```

**Error**:
```
Error: [$compile:multidir] Multiple directives [ngSwitchWhen, mdButton (module: material.components.button)] asking for transclusion on: <md-button ng-switch-when="0">
```

**Reproduced with:**
ngMaterial: **1.1.0-rc4**
angular: **1.5.6**

**Comment by faisalferoz** [comment]
Was having the same issue - wrapped up md-button inside a div and used the ng-switch-when on the div instead to get the same effect.
