### ISSUE TITLE
Input: ng-messages not implemented as a dependency

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#1284]
I installed the last version and tried the errors and i was surprised to see that the same code works at the docs and not in my project, i realized that ng-messages is a [dev dependency](https://github.com/angular/material/blob/master/bower.json#L18) and not included in the main module like you can see [here](https://docs.angularjs.org/api/ngMessages)

after manually installing ng-messages and added to the main module it worked :)

**Comment by ThomasBurleson** [comment]
@EladBezalel - very good. We will fix immediately.

**Comment by ajoslin** [comment]
This was intentional. I didn't want to force developers to include ngMessages.

**Comment by ThomasBurleson** [comment]
Andrew, - so you recommend with update the docs to mention usages of **ng-messages** requires an application dependency upon the module 'ngMessages' ?

**Comment by EladBezalel** [comment]
Couldn't find any alternatives for ng-messages
why not include it?

if your'e still don't want to make it a dependency, you should update the docs to tell developers to install ng-messsages.

@ajoslin great work btw!

**Comment by ajoslin** [comment]
Yes.

**Comment by ajoslin** [comment]
Didn't see your last response Elad - I was saying yes, we should be more explicit about the  ngMessages module it in the documentation. 

As long as there's only one component using ngMessages, I don't want to bundle it with all of angular material.

**Comment by ilanbiala** [comment]
@ajoslin I agree with your thoughts on bundling.

**Comment by EladBezalel** [comment]
Well your'e right..
