### ISSUE TITLE
Error when using placeholder on input without md-input-container

### ISSUE THREAD

**Issue by pcassis** [angular/material#1290]
Placeholder require mdInputContainer so when input is not wrapped with md-input-container it gives:

Error: [$compile:ctreq] Controller 'mdInputContainer', required by directive 'placeholder', can't be found!

Preview (check console or remove placeholder):
http://plnkr.co/edit/TB7XDPRkyvAez0MrUpC3?p=preview

**Comment by DefunctExodus** [comment]
Having the same issue.

**Comment by marcysutton** [comment]
Maybe related: https://github.com/angular/material/issues/1279

**Comment by DefunctExodus** [comment]
This looks to be fixed with the latest push this evening.

**Comment by vertazzar** [comment]
it's because the "placeholder" is now a angular directive

<anything placeholder="foobar"></anything> will throw an error without wrapping it in the md-input-container directive

**Comment by DefunctExodus** [comment]
@vertazzar Exactly the issue.

**Comment by pcassis** [comment]
If it's impossible to overwrite default behavior only when it's wrapped with md-input-container then maybe it would be better to prefix (md-) these directives? Sometimes you need to use default html behavior and now it's impossible.

**Comment by ajoslin** [comment]
Oh, good call. I didn't realize it would break in other cases.

**Comment by ajoslin** [comment]
Fixed.
