### ISSUE TITLE
Prevent md-button for submit action

### ISSUE THREAD

**Issue by masseuro** [angular/material#1292]
If a md-button is inside a form, its action will submit the form

To prevent this, add this in the template button :
```
type="button"
```
http://www.w3.org/TR/html-markup/button.html

**Comment by masseuro** [comment]
http://jsfiddle.net/3ojbauoa/1/

**Comment by yarl** [comment]
#1291 related

**Comment by marcysutton** [comment]
This has already been discussed and was determined not to be an issue: https://github.com/angular/material/issues/710
