### ISSUE TITLE
Disabled input should have disabled cursor

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1297]
Since the disabled button has a disabled cursor, shouldn't inputs be consistent and have a disabled cursor?

**Comment by marcysutton** [comment]
It does have one. It's a native button with the `disabled` attribute.

**Comment by ilanbiala** [comment]
I'm referring to the input, not the button.

**Comment by marcysutton** [comment]
Ahh! You're right. Except it's still a native input with the `disabled` attribute, which has the default cursor. If you want a different cursor, you could override it in your own CSS.

**Comment by ilanbiala** [comment]
Ok, I guess it just isn't clear enough that the input is disabled right now. Any ideas on how to make that clearer by default in Material?

**Comment by marcysutton** [comment]
It currently matches the Material Design spec: http://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field

For now, you could either add a text label to it indicating it's disabled or add the cursor in your stylesheet..but that is only relevant to mouse/desktop users. I'll see if I can get an answer from the UX team about other approaches.

**Comment by ilanbiala** [comment]
Sounds good, hopfeully they have some suggestions too.
