### ISSUE TITLE
$mdThemingProvider.theme('<sometheme>').primaryPallete('<somePallete>') raises undefined error.

### ISSUE THREAD

**Issue by Darwesh27** [angular/material#1298]
The error says that the function primaryPalleter is undefined.  I looked deep into the angular code and there is not even a function defined as primaryPalette. Rather there is a function named priamaryColor that is used in MdCoreConfigure on line 36. Has ng-material's team made a blunder while writing the documentation or am I being foolish.

**Comment by marcysutton** [comment]
Hi, you must be using an old version of the code. `primaryPalette` is used now. We have a version picker for the docs coming that will make this easier to sort out. But here is a related thread you can read up on: https://github.com/angular/material/issues/1289

**Comment by Darwesh27** [comment]
Here is the configurartion of my bower.json file

   "angular-material": "~0.7.0",

and I have just bower installed my components.. But the error still remains there..

**Comment by PaulMougel** [comment]
Please provide a Plunker so that we can help you debug this issue.

**Comment by marcysutton** [comment]
Also make sure you're spelling `primaryPalette` correctly. If you're seeing `primaryColor`, though, that sounds like an old version of the code. A Codpen or Plunker will help though. :)

**Comment by Darwesh27** [comment]
I have the latest version of angular-material i.e 0.7.0. Has the change from primaryColor to primaryPallete occured after this..??

**Comment by PaulMougel** [comment]
As Marcy mentioned, make sure that it is spelled `primaryPalette` in your code (and not `primaryPallete` with two two the letter `L`).
