### ISSUE TITLE
md-checkbox: Styles/animations broken in chrome 40

### ISSUE THREAD

**Issue by epelc** [angular/material#1301]
Chrome just updated and the styles for `md-checkbox` seem to be a bit messed up. You have to click through the checkboxes a bit but sometimes checkboxes are left slightly colored when they are unchecked and some of the animations are going blank/glitching sometimes. Also long clicking is causing the check to not show but the box to be colored sometimes.

https://material.angularjs.org/#/demo/material.components.checkbox

Angular-material version: `0.7.0`

**Comment by marcysutton** [comment]
I can't repro this in Chrome Version 40.0.2214.93 (64-bit).

**Comment by epelc** [comment]
@marcysutton I think this may only be on windows 7. But here is a gif to demonstrate the problems.

![bad-check](https://cloud.githubusercontent.com/assets/5204642/5924379/41030574-a629-11e4-9065-2c6aac854a1e.gif)
Windows 7 64bit, Chrome 40.0.2214.93

**Comment by yarl** [comment]
Windows 7, Chrome 40.0.2214.91 here, [this demo](https://material.angularjs.org/#/demo/material.components.checkbox) looks completely fine on my computer.

**Comment by epelc** [comment]
I just tested this on a second computer with Windows 7 64bit, Chrome 40.0.2214.93 and it works fine. I think it may be a graphics driver issue or something else just on that computer.
