### ISSUE TITLE
Ripple animations not playing in chrome 40

### ISSUE THREAD

**Issue by epelc** [angular/material#1302]
This is most prominent with buttons but ripples do not seem to be animating anywhere. ie when you click a button it instantly shows the ripple taking up half of the button.

See it here https://material.angularjs.org/#/demo/material.components.button

**Comment by marcysutton** [comment]
I'm not seeing this issue in Chrome 40.

**Comment by gustavohenke** [comment]
Me neither.

**Comment by ilanbiala** [comment]
Me neither.

**Comment by ajoslin** [comment]
What OS are you on?

**Comment by epelc** [comment]
@ajoslin I'm on windows 7 64bit with chrome 40.0.2214.93

Can anyone else confirm this on windows? I assume most of you are os x. Also just to be clear you still see the ripple however it does not grow it simply pops in at about half the width of the button then pops out.

#1301 #1303 may also be windows only

**Comment by gustavohenke** [comment]
Windows 8.1, Chrome 40.0.2214.93 m (64-bit):
![](http://i.imgur.com/QwfWWb7.gif)

**Comment by epelc** [comment]
See how the ripple doesn't grow it just pops in already big.

![bad button2](https://cloud.githubusercontent.com/assets/5204642/5924313/bcdc95da-a628-11e4-9a2e-41296b393822.gif)

Windows 7 64bit, Chrome 40.0.2214.93

**Comment by vertazzar** [comment]
works fine on mac os x 10.8 and Version 40.0.2214.91 (64-bit)

maybe its related to your hardware? check the https://www.polymer-project.org/components/paper-elements/demo.html#paper-button and if it's behaving the same

**Comment by epelc** [comment]
@vertazzar Paper elements work fine.
Also they were working in chrome 39 but I just updated to chrome 40 this morning and they broke(both in my app and on the docs). I also think this might just be windows 7 as I've also tested on android 4.4 with chrome 40 and it worked as expected.

**Comment by epelc** [comment]
I just tested this on a second computer with Windows 7 64bit, Chrome 40.0.2214.93 and it works fine. I think it may be a graphics driver issue or something else just on that computer.
