### ISSUE TITLE
$mdToast: Animation stops at the edge of screen for several seconds in Chrome 40

### ISSUE THREAD

**Issue by epelc** [angular/material#1303]
The toast animation is getting stuck at the edge of the screen for several seconds and its very jagged.

https://material.angularjs.org/#/demo/material.components.toast

**Comment by marcysutton** [comment]
Can't repro in Chrome Version 40.0.2214.93 (64-bit).

**Comment by epelc** [comment]
It appears to move down to its regular position after you move your mouse off the button that fired it. Notice how you can move anywhere on the button but as soon as you go off the toast drops down to its regular position.
![bad toast](https://cloud.githubusercontent.com/assets/5204642/5924492/4438a70c-a62a-11e4-868f-e622e9897796.gif)

Windows 7 64bit, Chrome 40.0.2214.93

**Comment by epelc** [comment]
I just tested this on a second computer with Windows 7 64bit, Chrome 40.0.2214.93 and it works fine. I think it may be a graphics driver issue or something else just on that computer.
