### ISSUE TITLE
md-radio-group: required doesn't work

### ISSUE THREAD

**Issue by epelc** [angular/material#1305]
The `required` and `ng-required` attributes do not seem to work with `md-radio-group`

**Comment by ajoslin** [comment]
Put the attributes on each individual `<md-radio>` element.

**Comment by epelc** [comment]
@ajoslin Can you take a look at this [example](http://codepen.io/anon/pen/ZYJeZQ) I've shown both ways and neither one seems to work. Maybe I'm doing something wrong otherwise can we reopen this.

**Comment by iamgurdip** [comment]
use ng-required="true" instead of HTML 5 required on the md-radio-group.

**Comment by demisx** [comment]
Adding `ng-required="true"` to `md-radio-group` indeed works, though not clear how to show the error message for it, since `ng-messages` aren't triggered until a user interacts with the input field and once he/she does, it's no longer invalid. Any clues are appreciated.

**Comment by epelc** [comment]
@ajoslin Can you reopen this it doesn't work in `0.8.3` I've just tried @demisx suggestion and I retried what I did in my examples and none of them work.

Also #1456 is related

**Comment by mackelito** [comment]
This seems to be broken again... required nor ng-required is working.. Please reopen

**Comment by harpritt** [comment]
This seems broken again.

**Comment by harpritt** [comment]
Sorry, forgot the [Pen](http://codepen.io/harpskal/pen/pyKxyG?editors=1111) showing required + ng-required on group and button.

**Comment by rochapablo** [comment]
+1

**Comment by ehannum** [comment]
+1
See the above codepen by harpritt.

**Comment by MilkyC** [comment]
+1

**Comment by makkart** [comment]
Im pretty sure you are talking about the browsers built in form validation. But it can easily be solved with Angulars form validation*. The problem with the ng-messages not triggering still remains and browser validation will still not work. But it keeps the form from being submitted. 

Demo: [Codepen](http://codepen.io/anon/pen/YGNrGm?editors=1111)
* ng-required on each button will still not work but the rest do.

**Comment by DouglasWaltricke** [comment]
+1

**Comment by Asvarduil** [comment]
+1

**Comment by VitaliyDemchuk** [comment]
+1

**Comment by eladh** [comment]
+1

**Comment by snapcount** [comment]
+1

**Comment by vsilva472** [comment]
+1

**Comment by jackdclick** [comment]
+1

**Comment by daton89** [comment]
+1

**Comment by etovian** [comment]
+1

**Comment by youvtr** [comment]
+1

**Comment by Buggyy** [comment]
+1

**Comment by simone127** [comment]
+1

**Comment by lindsey-tonn** [comment]
+1

**Comment by cladley** [comment]
+1

**Comment by SensationSama** [comment]
+1

**Comment by aissaghouti** [comment]
+1

**Comment by Splaktar** [comment]
Please open a new issue with a CodePen demo of the problem that you are seeing. Also please use the 👍 reactions and avoid posting `+1` in comments.
