### ISSUE TITLE
$mdSidenav: change to promise-based API, add documentation

### ISSUE THREAD

**Issue by ajoslin** [angular/material#1311]
```js
$mdSidenav('left').then(function(leftNav) { leftNav.close(); });
```

**Comment by rschmukler** [comment]
@ajoslin what's the thought on a promise based API here? There's nothing async about the get operation, so perhaps this is just extra abstraction?

**Comment by ThomasBurleson** [comment]
@rschmukler - just like the $componentRegistry, there are use cases were a user is querying for the component BEFORE it is ready/registered. A the promise-based API keeps the API consistent with $mdDialog, $componentRegistry, etc. Should we discuss this offline?

**Comment by dmackerman** [comment]
This would be super useful. In our app, we load a lot of "detail" information in a Sidenav, and we utilize ui-router's onEnter and onExit callbacks to hide/show sidenavs. This would ensure that the Sidenav is available before we show anything. :+1:

**Comment by AllenSH12** [comment]
+1 for at least the docs, my guess is a lot of people (myself included) primarily want to use the sidenav as it works in mobile apps, click an option and it goes away. It's possible to figure out from the repo but takes some work.

@rschmukler @ThomasBurleson @ajoslin if I can be of any assistance documenting or being a guinea pig please ask.

**Comment by QuantumInformation** [comment]
What is the correct way to inject this $mdsideNav? For some reason I'm getting

`Uncaught TypeError: $mdSidenav is not a function.` When attempting ```    $scope.toggleMenu = function () {
            $mdSidenav('left')
              .toggle()
              .then(function () {
              });
          };```

**Comment by iamryandrake** [comment]
I'm getting the same issue as QuantumInformation above. Any other comments?

**Comment by ThomasBurleson** [comment]
@QuantumInformation 

Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/ThomasBurleson/pen/zvorxN
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.
