### ISSUE TITLE
Link style seems inconistent with Material style guide

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1313]
The Material style guide seems to suggest using the accent color for links with no underline. Is there a reason ngMaterial doesn't follow this?

**Comment by marcysutton** [comment]
The reason was for accessibility–underlines are shown on hover/focus in the docs only. We deviated from the Material Design spec because relying on color alone is not enough to discern links from text.

**Comment by ilanbiala** [comment]
@marcysutton oh that's fine, but it seems like ngMaterial doesn't even provide default styles for links. In Chrome, I'm getting an underline and weird color (`-webkit-color`) because of the UA stylesheet. A consistent default using the accent color should be provided, no?

**Comment by marcysutton** [comment]
Already on our roadmap https://github.com/angular/material/issues/1128

**Comment by ilanbiala** [comment]
Great, I'll follow there.
