### ISSUE TITLE
Why is the rippling effect not extending to the edge of buttons?

### ISSUE THREAD

**Issue by uuns** [angular/material#1314]
Is there a reason the ripple doesn't extend to the very far edge of the button? I really like the ripple effects on Material-UI buttons.

relevant links:
http://material-ui.com/#/components/buttons
https://github.com/callemall/material-ui/tree/master/src/js/ripples

**Comment by ilanbiala** [comment]
@uuns take a look at the https://material.angularjs.org/#/api/material.components.button/directive/mdButton md-ripple-size.

**Comment by robertmesserle** [comment]
@uuns The buttons are based on the examples given in the Material Design spec here http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons

However, earlier today, we added a method for manually overriding this to fill the button with this syntax: `md-ripple-size="full"`

This will be released in version 0.7.1.
