### ISSUE TITLE
Progress Circular shows trash on mobile chrome 40.0.22214.89

### ISSUE THREAD

**Issue by amedeomar** [angular/material#1316]
![sscircular](https://cloud.githubusercontent.com/assets/10732836/5929526/d8b55100-a684-11e4-86ec-eb736b7ed145.png)

**Comment by marcysutton** [comment]
Can you also provide device details?

**Comment by amedeomar** [comment]
Sure, this is a Samsung Note 2 (N7100)

**Comment by amedeomar** [comment]
Any news about this?

**Comment by marcysutton** [comment]
@amedeomar, which version of Android? I'm not seeing the issue in Chrome on Android 4.4.4.

**Comment by amedeomar** [comment]
Android Version 5.0.2, the problem is still here

**Comment by marcysutton** [comment]
@robertmesserle were you able to find a Samsung Note device?

**Comment by naomiblack** [comment]
I just tried on a Samsung Galaxy Note 10.1 running Android 4.1.2 and can't reproduce. Will see if I can find a device running 5 on Monday.

**Comment by krassx** [comment]
I definitely can reproduce that. I am using Samsung Galaxy Note 10.1 and here is what I see:
https://docs.google.com/file/d/0B1BjYG2HkGIkRlhNMDI4Y1d0SE0

Here is my device specs:
Samsung Galaxy Note 10.1, Android 4.4.2 (Firmware: N8000XXUDNH2)

**Comment by ThomasBurleson** [comment]
@krassx - have you tried testing with the latest from `/angular/material/#master` ?

**Comment by krassx** [comment]
Will give it a try. Will respond on results.

**Comment by ThomasBurleson** [comment]
@krassx - We just released v0.11.0-rc2: which has major improvements to ProgressCircular and ProgressLinear. Can you retest. 

> I will close for now. Please reopen if still not fixed.

**Comment by krasssss** [comment]
Tried latest release. Works like a charm. Thank you.
