### ISSUE TITLE
mdInputContainer: "md-input-has-value" class is always applied when "input" event triggers

### ISSUE THREAD

**Issue by Chryssie** [angular/material#1318]
The "inputTextareaDirective" binds the "checkHasValue" function to the "input" event of the element, however, the first argument passed when the event is triggered is the event reference, not the value causing it to always set HasValue to true when the event is triggered.

**Comment by gustavohenke** [comment]
See #1198

**Comment by ajoslin** [comment]
Hey Chryssie, thanks for the issue.

However, the latest version in master's fixed this.
