### ISSUE TITLE
Cannot set md-hue-* on md-content background

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1321]
I have setup a theme as...

    $mdThemingProvider.theme('default')
        .primaryPalette('blue')
        .accentPalette('green')
        .warnPalette('red')
        .backgroundPalette('yellow',{
            'default' : '50',
            'hue-1'   : '100',
            'hue-2'   : '200',
            'hue-3'   : '300',
        }); 

However when looking at the css the md-hue-1, md-hue-2, md-hue-3 all have the same background color...

    md-content.md-default-theme {
        background-color: rgb(255,241,118);
    }

    md-content.md-default-theme.md-hue-1 {
        background-color: rgb(255,241,118);
    }

    md-content.md-default-theme.md-hue-2 {
        background-color: rgb(255,241,118);
    }

    md-content.md-default-theme.md-hue-3 {
        background-color: rgb(255,241,118);
    }

Is this expected behaviour? I want to be able to set a master md-content with a pale grey background and then child content containers to have a white background. It does not seem possible to achieve this at present without inserting my own css?

**Comment by hodeyp** [comment]
I've researched this some more and have discovered that the md-content css background color is always set to md-hue-3, irrespective of which md-hue-* is defined in the html or in fact if a hue is not specified. This does not seem right?

**Comment by robertmain** [comment]
Weighing in on this issue to say that I'm having the same problem

**Comment by arshabh** [comment]
+1
