### ISSUE TITLE
md-button with ng-click - Behavior when invoked from keyboard 

### ISSUE THREAD

**Issue by braintapper** [angular/material#1326]
http://plnkr.co/edit/aNsDEC4BH42x9uay8ICJ?p=preview

Experiencing some strange behavior when using the keyboard to fire an md-button with an ng-click event. I only tested in Windows.

In Chrome/Windows
If you use the keyboard to tab to the button and hit the space bar to press the button, the ng-click event fires twice. 

In Firefox/Windows
If you use the keyboard to tab to the button and hit the space bar to press the button, nothing happens (expected?). If you hit Return, nothing happens. But if you click the button after hitting Return, the ng-click event fires for every time you hit Return as though the event was being queued up. 

In Internet Explorer/Windows
Similar to firefox, if you hit space, you see the button press but nothing happens until you click the button. Any previous button presses using the space bar appear.

**Comment by marcysutton** [comment]
Multiple click events fired on native buttons are due to a known issue related to ngAria: https://github.com/angular/angular.js/pull/10766 We're hoping to get the bugfix resolved next week to get in to the Angular 1.4 release.

That is super weird about Firefox. I can repro it on a Mac. Legit issue.

**Comment by marcysutton** [comment]
Firefox issue fixed with 79196c3df13906c0221a9f0b4e2bab9c0c25825e. ngAria bug is tracked in https://github.com/angular/material/issues/991.

**Comment by jpdesigndev** [comment]
@marcysutton Is there a workaround you can suggest in the meantime? We've got a demo coming up soon for a product, and I'm blanking on how to fix this cleanly.

**Comment by marcysutton** [comment]
@jpdesigndev for the ngAria bug I've been using an older version of angular-aria. The bug was introduced in Angular 1.3.6. In your HTML, you an just reference the previous version, 1.3.5. Here is a Codepen I created to track it and test fixes:

http://codepen.io/marcysutton/pen/YPxrLd

**Comment by jpdesigndev** [comment]
Awesome. Thanks for the help!
