### ISSUE TITLE
md-sidenav: md-is-locked-open="$media('gt-lg')" does not collapse on resize - Safari & Firefox

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1329]
When md-is-locked-open="$media('gt-lg')" is used to lock open the sidenav on larger displays it should automatically collapse on window resize to < lg. This works as expected on Chrome but does not work on Firefox or Safari.

**Comment by mzbyszynski** [comment]
I'm seeing this too. Here's a fork of the Material Angular SideNav Demo Codepen that shows this behavior. 

http://codepen.io/anon/pen/XJaqXv?editors=101

The sidenav doesn't show/hide in Firefox (v35.0.1 on linux is what I tested) when you resize the browser window. If you reload the page it works, just not on window resize. Also appears to be a general issue related to browser resize. I saw the same behavior with `gt-md` as well (so I guess I really didn't need to fork the codepen :\ ).

**Comment by rschmukler** [comment]
@ajoslin any ideas on this?

**Comment by gkalpak** [comment]
Could it be that `matchMedia#addListener` (as introduced in 8a0411f) isn't so widely/consistently supported ?

**Comment by ajoslin** [comment]
According to caniuse.com, it is. Requires further testing.

**Comment by rschmukler** [comment]
The issue was that only chrome as the query as the context set for `this`. All browsers pass it in as an argument
