### ISSUE TITLE
md-input-container: $setValidity() is working only when input is touched

### ISSUE THREAD

**Issue by yarl** [angular/material#1330]
When using form, `$setDirty()` should add `md-input-invalid` class for `<md-input-container>`.

In version `v0.7.0-rc3-master-1c97333` it was working fine, now (`v0.7.0-master-22040c7`) it's not.

**Comment by ThomasBurleson** [comment]
@yarl - Can you check with the latest code from `master`; or provide a CodePen/Plunkr for the team to confirm our recent fixes.

**Comment by yarl** [comment]
OK, so probably this is working good, but I'll change topic to similar problem. On [this fiddle](http://jsfiddle.net/hmdpszvb/1/) you can see, that `$setValidity()` is working only when input is touched. I don't know if it's angular core issue or angular-material.

**Comment by gkalpak** [comment]
It is not an issue (neither with angular core nor with angular-material); it is working as expected.
By default, the error state is shown (i.e. `md-input-ivalid` class is added) if the input is `$invalid` **and** `$touched`.

If you want to override this default behaviour, you can specify a different condition using the `md-is-error` attribute. ([Demo fiddle][1])

[1]: http://jsfiddle.net/ExpertSystem/hmdpszvb/2/

**Comment by yarl** [comment]
Thanks for clarification @gkalpak. In this case I'm closing issue.
