### ISSUE TITLE
Allow themes to affect non-material components

### ISSUE THREAD

**Issue by sjlynch** [angular/material#1331]
It would be nice if you could use md-primary/hue/etc on html elements that are not part of the materials library to set some of their css properties. For example, I wish I could have set the background color of an input to md-primary, but I had to set it in a css file. So now if I switch themes in the theme provider I will have to go back and edit the css for those kinds of elements. Not a big deal really, but it would be really cool to change the theme of your entire app with just a tiny edit in the themeprovider.

**Comment by ThomasBurleson** [comment]
@sjlynch - best thing to do is use a CodePen or Plunkr to showcase your requirements.

**Comment by kloy** [comment]
You could override the CSS in the angular constant that material uses to apply the theme... This will give you access to the variables used. Take a look at the bower build of angular-material.js at the bottom of the file to get an idea.

**Comment by sstorie** [comment]
At the risk of sounding dumb...I have a custom directive that I want to live inside a material toolbar (e.g., a search textbox like that inbox.google.com uses) and would like it to respect the theme. Essentially I want it to take on a a lighter color from the current theme, and then become white when the user clicks inside. The interaction isn't an issue, but I want the initial color to respect the theme. Do I need to somehow add my own CSS to the $MD_THEME_CSS constant so it includes markup specific to my directive? I am not sure how to modify an existing constant, so would that mean I need to copy the constant string from and angular-material.js file and completely redefine it with my own content appended?

...or am I thinking about this all wrong?
