### ISSUE TITLE
themes mia ?

### ISSUE THREAD

**Issue by jmls** [angular/material#1332]
I've just tried looking for the theme css files, but can't find any. There was a change that says  

move 'themes' into 'src/themes' (https://github.com/angular/material/commit/18f673c92c6d47c1d3b5227bd55acbbfe676228b) 

but I can't see the src/themes folder

am I being dumb ?

**Comment by soutlink** [comment]
There is no more themes/css files

https://github.com/angular/material/commit/47f0d09e9ebd87891703fa2b7e81355ce3952a86

**Comment by jmls** [comment]
now I know that I am dumb. So how would I use the "deep-orange" theme as my default, or would I now have to define my own ?

**Comment by ThomasBurleson** [comment]
@jmls - you are **not** being dumb. We changed the way themes work and they way they are configured. You may want to read  https://material.angularjs.org/#/Theming/04_multiple_themes.
