### ISSUE TITLE
Directive for material dropdown, select and date-picker ?

### ISSUE THREAD

**Issue by sunnyshah01** [angular/material#1335]
material dropdown and select is main component which is mostly used in form and you guys are doing amaizing job, when can we see dropdown in angular-material ?

**Comment by EladBezalel** [comment]
Do you mean something like #276?

**Comment by marcysutton** [comment]
You can find this information in our milestones and open issues: https://github.com/angular/material/milestones 
https://github.com/angular/material/issues
