### ISSUE TITLE
style(subheader): width styling with scrolling 

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1339]
Demo with [Subheader](https://material.angularjs.org/#/demo/material.components.subheader) shows subheader not full-width when elevated due to scrolling.

**Comment by rschmukler** [comment]
This is a byproduct of achieving a mobile-performant sticky subheader.

**Comment by robertmesserle** [comment]
I believe a wrapper div that does not scroll should handle this.

    <md-content>
      <div class="content-inner">
        
      </div>
    </md-content>
