### ISSUE TITLE
md-slider width increases when slide to right

### ISSUE THREAD

**Issue by sunnyshah01** [angular/material#1343]
<b>md-slider</b> width increases when sliding

and this <b>problem</b> is started from the <b>version 0.7.1-rc1</b>

check problem - <b><a href="http://plnkr.co/edit/hDPPg1UQZk7veyvPvNbJ?p=preview">http://plnkr.co/edit/hDPPg1UQZk7veyvPvNbJ?p=preview </a></b>

Same behavior is seen on angular material slider demo page.

**Comment by DBGTTECHJAM** [comment]
+1

**Comment by ThomasBurleson** [comment]
wrap the md-slide in a container:

```html
<body>
    <div style="width:400px;padding:40px;">
      <md-slider name="slider" aria-label="slider" min="0" max="100" step="1"></md-slider>
    </div>     
</body>
```

**Comment by sunnyshah01** [comment]
Nope, that does not fix the issue. For screen size smaller than width will still have that issue.

**Comment by ThomasBurleson** [comment]
@sunnyshah01 - you did not give that particular, important detail in your original issue report.
It appears that:

```css
md-slider {
overflow: hidden;
}
``` 

should resolve this issue.

**Comment by sunnyshah01** [comment]
Slider thumb is cut off now. 
http://plnkr.co/edit/hDPPg1UQZk7veyvPvNbJ?p=preview

**Comment by ThomasBurleson** [comment]
@robertmesserle - the `hack` below seems to work. Let's review the best approach.

```html
<div style="overflow:hidden;padding:20px">
      <md-slider style="" name="slider" aria-label="slider" min="0" max="100" step="1"></md-slider>
</div>
```

**Comment by robertmesserle** [comment]
@ThomasBurleson That makes sense, but we should probably include the padding on our end by default.

**Comment by sunnyshah01** [comment]
@robertmesserle This is not the right fix. size of slider became smaller because of padding.
