### ISSUE TITLE
Option show doesn't work

### ISSUE THREAD

**Issue by TheBay0r** [angular/material#1344]
For example when using:
> \<element hide show-gt-lg\> \</element\>

It should show the element on screens bigger than 1200px. In the documentation it says:
> show-gt-lg	Negates hide on devices greater than 1200px wide.

But acutally show doesn't do anything. No matter what combination I tried the element was not visible

**Comment by epelc** [comment]
@TheBay0r You used `show-lg-gt` instead of `show-gt-lg`

**Comment by TheBay0r** [comment]
Sorry, just  mistyped it in this Issue. Checked my code, there i used show-gt-lg... But also show-lg and all other show didn't work

**Comment by miguelchico** [comment]
+1

**Comment by matthewrfindley** [comment]
@TheBay0r, @miguelchico 

With versions prior to 0.8.3, the issue is reproducible.  See ->
http://codepen.io/matthewrfindley/pen/wBbVzR

As of 0.8.3 I believe your bug is fixed.  See ->
http://codepen.io/matthewrfindley/pen/VYOoKr
