### ISSUE TITLE
Option hide-gt- is including one pixel of the smaller size

### ISSUE THREAD

**Issue by TheBay0r** [angular/material#1345]
E.g. 
It says for hide-gt-lg 
> display: none on devices greater than 1200px wide

But actually it sets display to none on devices greater than and equals to 1200px wide

**Comment by cstephe** [comment]
posted the same bug https://github.com/angular/material/issues/1361 I'll close mine.

**Comment by yjaaidi** [comment]
Same here. I'm trying to display a different element when '<= 600px' and when '> 600px' but at 600px none of them is display because the rule below takes precedence when using 'hide show-gt-sm'

[hide-sm]:not([show-sm]):not([show]), [hide]:not([show-sm]):not([show]) {
    display: none; 
}

**Comment by rschmukler** [comment]
This is fixed in 0.8Rc2 (shipping later today)
