### ISSUE TITLE
Push 0.7.1-rc2 to bower?

### ISSUE THREAD

**Issue by epelc** [angular/material#1346]
It seems like `0.7.1-rc2` and several other recent builds haven't been pushed to bower.

**Comment by Splaktar** [comment]
I'm seeing this today as well.

**Comment by epelc** [comment]
It appears `0.7.1` also hasn't been pushed to bower.

@marcysutton Do you know if the build system is broken? I don't know if your recent docs fix was just due to project code.

**Comment by Splaktar** [comment]
0.7.1 has been released and is visible from bower. This can be closed?
