### ISSUE TITLE
Input field overlapped with the phone keyboard

### ISSUE THREAD

**Issue by dioklecijan** [angular/material#1349]
When I touch text input field to edit, the phone keyboard popups and covers focused input field. Expected behavior is that view is automatically scrolled to ensure that input field is visible.
I am using angular-material 0.7.0 on LG3 with Lollipop.

**Comment by marcysutton** [comment]
It's a native input, so that sounds like a bug in Lollipop to me.

**Comment by dioklecijan** [comment]
The problem appears in Google Chrome and Android browser.
However, if I use angularjs without material it works fine. 
Also, I just tried in Safari on iPhone (iOS 7.1.2. Safari) and it works fine.
Could be a problem with animations?

**Comment by marcysutton** [comment]
It's a problem with Flex layout. When I put the input into a [test file](http://codepen.io/marcysutton/pen/GgxboO) without the rest of the layout stuff, it doesn't suffer from that problem. When I add it to a basic [Angular Material app](http://codepen.io/marcysutton/pen/QwPXjB?editors=101), it doesn't scroll the input into view. This sounds like a Chrome flexbox bug to me.
