### ISSUE TITLE
Is there a way to make md-content scroll to bottom as content is added to it?

### ISSUE THREAD

**Issue by MadMatt04** [angular/material#1351]
I have a use case where I'm continuously adding entries to the bottom of md-content. I would like md-content to automatically scroll so that the last entry is visible. Is it possible to achieve that?

**Comment by ratscrew** [comment]
here is a small directive I use to keep the content of the page from shifting down as new items are added to the top.

i place `<cm-kepp-on-page watch="processes.length" ></cm-kepp-on-page>` at the bottom of the page and watch the array length.  As items are added the page scrolls to keep the content in the same place on the screen for the end user.  this should get you close to what you are looking for and you can modify it there.  good luck

    <cm-kepp-on-page watch="processes.length" ></cm-kepp-on-page>

    myApp.directive('cmKeppOnPage', cmKeppOnPageDirective);
    function cmKeppOnPageDirective() {
        return {compile: function () {
                return {
                    post: function (scope, element, attr) {
                        var object = $(element), parten = object.parent();
                        var curOffset = object.offset().top - parten.scrollTop();
                        parten.on('scroll', function () {
                            curOffset = object.offset().top - parten.scrollTop();
                        })
                        scope.$watch(attr.watch, function (value, old) {
                            curOffset = object.offset().top - parten.scrollTop();
                            if (old != undefined && old != 0 && value != old) {
                                scope.$evalAsync(function () {
                                    var t = object.offset().top, setP = t - curOffset;
                                    parten.scrollTop(object.offset().top - curOffset);
                               })
                           }
                        
                       })
                   }
               }
           }
       }
    };

**Comment by marcysutton** [comment]
Please post these kinds of issues in the [ngMaterial Forum](https://groups.google.com/forum/#!forum/ngmaterial). Thank you!

**Comment by MadMatt04** [comment]
My apologies, will do. Just thought I'd post the solution I devised thanks to how ratscrew's post above got me thinking. 

```javascript
$scope.$watch(function () {
                    return $scope.entries.length;
                }, function(newValue, oldValue) {
                    if (newValue !== oldValue) {
                        $timeout(function() {
                            var lastEc = angular.element($document[0].querySelector("md-content.console-content"));
                            lastEc[0].scrollTop = lastEc[0].scrollHeight;
                        });
                    }
                });
```

**Comment by ThomasBurleson** [comment]
@MadMatt04, @ratscrew - Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial).

Meanwhile, this is **not** a good idea since you are query for the first md-content in the document. Instead of the querying for any specify **md-content**.

**Comment by MadMatt04** [comment]
Well, I'm querying for the md-content that has the console-content class, there's only one. Anyway, the query is not the gist here, it can be easily fixed, the scrolling logic is.
