### ISSUE TITLE
md-slider dragging broken when jQuery loaded in 0.7.1

### ISSUE THREAD

**Issue by jelbourn** [angular/material#1352]
When jQuery is loaded on the page, dragging the slider with the mouse is broken.

http://jsbin.com/recepu/5/edit

**Comment by maxee** [comment]
+1, Same problem here

**Comment by ThomasBurleson** [comment]
@maxee 
*  what is the browser/OS [and their versions] that you are using.
*  what version of the Angular Material library are you using.

**Comment by maxee** [comment]
@ThomasBurleson 
Chrome 40 (Desktop) on Win7 (64) and 0.7.1

**Comment by TheHippo** [comment]
It does work for me - Chrome 40, Linux. Using commit f1a4bcc3d1cbd89b72f2eca120ffa6523f0f8c27.

**Comment by jelbourn** [comment]
Update: the issue only occurs when jQuery is loaded on the page.

**Comment by jelbourn** [comment]
Looks like this has to do with the dispatchEvent function in gesture.js. One of the users found that they could fix the issue by triggering the event to the jQuery-wrapped event target:

```javascript
if (window['jQuery']) {
  window['jQuery'](eventPointer.target).trigger(eventObj);
}
```

**Comment by ajoslin** [comment]
There's a pull request open to fix this.

**Comment by ThomasBurleson** [comment]
@ajoslin - that PR looks good (with some tweaks). Are you planning on merging it or should I do that ?

**Comment by Ronani** [comment]
Hi, I still have this problem with jQuery 2.0.2 and the latest version - 1.0.0-rc2. any ideas?

**Comment by jelbourn** [comment]
@Ronani could you open a new issue with a reproduction?
