### ISSUE TITLE
Automate NPM registry updates

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1355]
Update build scripts to deploy/register release updates for NPM installs.

**Comment by gustavohenke** [comment]
[I like using Travis for this task](http://docs.travis-ci.com/user/deployment/npm/).

**Comment by jgoux** [comment]
Could you publish the 0.8.0-rc1 to npm ?

**Comment by shprink** [comment]
Can't wait to get the new select component via NPM! The lastest version is still 0.7.1

**Comment by jsmylnycky** [comment]
:+1: 

Can we at least get 0.9.0 published to NPM for now please?

**Comment by jgoux** [comment]
@jsmylnycky If you don't want to wait, you can still fetch it from the release tag on bower-material  (in your package.json) : 
```
"angular-material": "git://github.com/angular/bower-material.git#v0.9.0",
```

**Comment by robertmesserle** [comment]
Publishing right now

**Comment by robertmesserle** [comment]
And it's up!

https://www.npmjs.com/package/angular-material

**Comment by jsmylnycky** [comment]
Thanks so much :)

**Comment by shprink** [comment]
@robertmesserle  Did not work, still 0.8.3.  

https://www.npmjs.com/package/angular-material

**Comment by robertmesserle** [comment]
Yea, there were some issues with the original release, but they were
addressed.  It's listed in NPM as 0.9.2 now, but it's actually 0.9.0.  It
took too tries to fix the issue. =p

**Comment by ThomasBurleson** [comment]
@shprink - can you confirm `npm i angular-material` now installs 0.9.x  for you?

**Comment by shprink** [comment]
~0.9.0 install: 0.9.0-master-61b6240 which seems to be 0.9.0 @ThomasBurleson it is ok for me thanks :)

**Comment by ThomasBurleson** [comment]
Excellent. Closing Issue.
