### ISSUE TITLE
md-input-container with initially hidden <textarea> is permanently set to height = 0

### ISSUE THREAD

**Issue by jelbourn** [angular/material#1356]
http://jsbin.com/kabozo/2/edit?html,output

When the `setupTextarea()` function in `input.js` runs on a `<textarea>` that is hidden, the height calculation results in zero and is not run again until some text is entered into the input.

**Comment by mckenzielong** [comment]
would it be good enough to just add check for height at the end of growTextarea?  
```javascript
if (height > 0) 
   node.style.height = height + 'px';
```

http://plnkr.co/edit/xjZxyBPUi0jp54uclHdX?p=preview

**Comment by wuv1982** [comment]
i have the same problem.
but the reason i think is that i used `$mdModal` , it may directive the `<textarea>` before it shows.
so both of the `offsetHeight` and `scrollHeight` are `0`.

**Comment by WhiteAbeLincoln** [comment]
I am also getting this problem. It occurs when the textarea is on an md-tab. The text area size is fixed once text is entered.
