### ISSUE TITLE
mdGestures breaks Ripple effect when using JQuery

### ISSUE THREAD

**Issue by Toilal** [angular/material#1359]
Only when using JQuery, ripple effect is broken. It only occurs using `angular-material>=0.7.1`.

[plunkr with JQuery](http://plnkr.co/edit/ZWhlHe9rzwP7eFzkObPd)
[plunkr without JQuery](http://plnkr.co/edit/4fOuM3UfFgdcN5PqOmhb)

Both jquery 2.x and 1.x cause the issue.

**Comment by EladBezalel** [comment]
The easiest solution is not to use jQuery,
angular and jQuery not supposed to work together.. 
angular uses jqLite and you can do most things with it.

**Comment by Toilal** [comment]
I know, but my final project requires JQuery for some components.

Is it possible to include JQuery in my webapp, but still use jqLite for `angular.element` ?

**Comment by Toilal** [comment]
That beeing said, JQuery is still [officially supported](https://docs.angularjs.org/misc/faq#does-angular-use-the-jquery-library-), and ripple effect was working properly in angular-material 0.7.0 with JQuery.

**Comment by Toilal** [comment]
For some reason,  `GestureHandler` service seems to not work properly when JQuery is loaded. I've tried to run karma tests with JQuery loaded, and there's 14 tests failing, all related to GestureHandler.

I've debug this particular use case (Ripple Effect). This [part of code](https://github.com/angular/material/blob/c435409bfdcda51c5ba164c9013a3da1e5a03ce6/src/core/services/ripple/ripple.js#L98-L99) is called, so the callback should be registered. But [onPressDown/onPressUp](https://github.com/angular/material/blob/c435409bfdcda51c5ba164c9013a3da1e5a03ce6/src/core/services/ripple/ripple.js#L347-L357) are never called.

When pressing the button, [this callback](https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js#L160) is called, so we are entering in [GestureHandler#dispatchMethod](https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js#L367-L388). This method behave exactly the same with or without JQuery.

But, the final call to native [dispatchEvent](https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js#L387) seems to have no effect when JQuery is loaded, and the `onPressDown` method from ripple.js is never called.

My idea: I doubt calling `element.on` works properly with custom events and JQuery.

**Comment by Toilal** [comment]
I think it's related to this issue: http://bugs.jquery.com/ticket/11047

**Comment by Toilal** [comment]
I've written a fix, and will open a PR

**Comment by Toilal** [comment]
For those who may be interested, while waiting PRs related to JQuery to be merged, i've created a temporary fork with some issues fixed for projects using JQuery. It's available at https://github.com/Toilal/material, or using bower `bower install https://github.com/Toilal/material`.

**Comment by Splaktar** [comment]
This was mentioned on the forums (https://groups.google.com/forum/#!topic/ngmaterial/vZyVE9OsNmA and https://groups.google.com/forum/#!topic/ngmaterial/PopJOthVSLs). 

Thanks for the great detail and investigation already done here! I'm seeing it in my project as well.
