### ISSUE TITLE
Production ready

### ISSUE THREAD

**Issue by kostonstyle** [angular/material#1362]
Hi

I want to use material design and want to ask, if it is production ready?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by ilanbiala** [comment]
@ThomasBurleson quite honestly this Google Group is pretty annoying as it separates a lot of the chatter into 2 places and increases the number of duplicate discussions. Also, Google Groups is blocked by many corporate firewalls, and GH isn't...everything should just be here..
