### ISSUE TITLE
mdTab flickers on tab change when using cordova/phonegap

### ISSUE THREAD

**Issue by jaderabbit** [angular/material#1366]
Using 3.6.3 of phonegap, the ios build on a an ios 8.1 ipad: When selecting or swiping to another tab, the next tab will render correctly during the animation, but will rerender after the animation is complete causing a flicker.  This occurs even if the contents of the tab is not an angular variable

**Comment by robertmesserle** [comment]
This is likely resolved in master, will need to retest after 0.9.0 is released.
