### ISSUE TITLE
Add floating action button component

### ISSUE THREAD

**Issue by jgoux** [angular/material#1368]
Hello,
this is an extension from the md-fab button, useful for displaying multiple actions in the same context.
Example here : http://nobitagit.github.io/ng-material-floating-button/
Specifications : http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button

**Comment by carab** [comment]
Your implementation looks really nice !

This is indeed currently missing in Angular Material, but I'd love to have it.
I didn't see any issue on this subject yet, not sure if there is one...

**Comment by jgoux** [comment]
@carab This is not my implementation. I just found it on github. ;)

**Comment by marcysutton** [comment]
The floating action button already exists in md-button, although I agree it's pretty limited in regards to positioning. 

Side note: I sure wish demos like the one you posted were accessible.

**Comment by jgoux** [comment]
So the "dial" menus won't be in Angular Material at all ?

**Comment by EladBezalel** [comment]
I'm not sure why this is closed.. 

As you can see in the spec, there's an option for listed items in the floating button
![spec](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7cFRkZzVNWDZUbzQ/patterns_actions_fab_actions14.png)

**Comment by ThomasBurleson** [comment]
@marcysutton - I think we missed this feature in the [Floating Action Specifications](http://www.google.com/design/spec/components/buttons.html#buttons-floating-action-button).  Perhaps we should reopen or make a new issue to work on this component ?

**Comment by marcysutton** [comment]
I shouldn't have closed it so soon, my apologies. 

@ThomasBurleson the "speed dialer" from Inbox is definitely a new component. It's pretty mobile-focused, but has a significant wow-factor that people will want to use (noted from this issue). Let's create a new issue with more spec'd detail. Similar to Bottom Sheets, which are supposed to be mobile-only, we should probably write some language in the docs about usage.

**Comment by ubugnu** [comment]
any news?

**Comment by Splaktar** [comment]
@ubugnu this is supported. You can find the docs [here](https://material.angularjs.org/latest/demo/fabSpeedDial).
