### ISSUE TITLE
gulp karma releaseMode option has no effect

### ISSUE THREAD

**Issue by Toilal** [angular/material#1370]
I've noticed that gulp karma task should execute tests against minified files, but it doesn't work because `releaseMode` parameter is always undefined in [karma.conf.js](https://github.com/angular/material/blob/master/config/karma.conf.js#L26).

`releaseMode` is set properly in [gulpfile.js](https://github.com/angular/material/blob/master/gulpfile.js#L158), but is not passed to karma.conf.js

It could be fixed using an [environment variable](http://stackoverflow.com/questions/20034256/big-js-app-testing-avoiding-multiple-karma-conf-js-files) instead.

**Comment by ThomasBurleson** [comment]
Fixed in SHA 532e1533cdb93526bbe08ab62fb5fd3d40bff2a8
