### ISSUE TITLE
mdSidenav: broadcast events

### ISSUE THREAD

**Issue by tameraydin** [angular/material#1374]
Do you intend to implement any event broadcasting on md-sidenav? With current implementation, -i think- the only way to is understand if a sidenav is opened/closed is to watch a function that returns .isOpen() result. And once you have multiple sidenavs with possible locked states, it is getting difficult to obtain communication with other components. 

What would be pros/cons of adding $rootScope.$broadcast that provides sidebar state information whenever an action is taken?

**Comment by pepperlk** [comment]
Work Around:
```javascript
    $provide.decorator('mdSidenavDirective', ['$delegate', '$controller', '$rootScope',
        function ($delegate, $controller, $rootScope) {
            var directive = $delegate[0];

            var compile = directive.compile;

            directive.compile = function (tElement, tAttrs) {
                var link = compile.apply(this, arguments);
                return function (scope, elem, attrs) {

                    scope.$watch('isOpen', function (val) {
                        if (val) {
                            $rootScope.$broadcast('$mdSideNavOpen_' + scope.$$mdHandle);
                        }
                        else {
                            $rootScope.$broadcast('$mdSideNavClose_' + scope.$$mdHandle);
                        }

                    });

                    link.apply(this, arguments);
                };
            };

            return $delegate;
        }]);
```

**Comment by ThomasBurleson** [comment]
The Angular Material team has tried to be very careful regarding the use of events and broadcasting. Often our recommended approach is a watch or introspection of a component property or state.

> @pepperlk suggested an innovative solution to this feature request.

@pepperlk, @tameraydin - Please post your notes in an [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) post.
