### ISSUE TITLE
Failed to call click() due to ev.$material

### ISSUE THREAD

**Issue by beny78** [angular/material#1375]
I need to call click function on hidden input file.
But the click event is filtered by thise code in angular-material

document.addEventListener('click', function(ev) {
  // Prevent clicks unless they're sent by material
  if (!ev.$material) {
    ev.preventDefault();
    ev.stopPropagation();
  }
}, true);

here is an extract of my directive

link: function (scope, element, attrs, ctrl) {
            var el = $compile('<input type="file" style="display:none">')(scope);
            angular.element(element).append(el);
            
           element.on("click", function (event) {
               el[0].click() //FAILED because ev.$material is not setted
           });
}

How can I set ev.$material.

thanks.

**Comment by ThomasBurleson** [comment]
Clone the event, set the `$material` property and redispatch. 
Here is another example used in [Gestures.js](https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js#L362)
