### ISSUE TITLE
Responsive Layout on IPad

### ISSUE THREAD

**Issue by amedeomar** [angular/material#1377]
I tried the material.angualjs.org on the iPad 3 (aka "new iPad), the layout does not fit properly in width neither in landscape nor in portrait, so it is necessary to scroll horizontally to see the whole content.

This happens both on Chrome and Safari.
![ipadl](https://cloud.githubusercontent.com/assets/10732836/6016717/3dea2cac-ab86-11e4-95e1-2f18341ec61d.jpg)
![ipadp](https://cloud.githubusercontent.com/assets/10732836/6016718/3dece514-ab86-11e4-9c20-d206a4c46fc7.jpg)

**Comment by gkalpak** [comment]
Something is broken for sure (pun intended :stuck_out_tongue:)

**Comment by ThomasBurleson** [comment]
@amedeomar - which OS version are you using ? Safari browser I assume... ?

**Comment by Frank3K** [comment]
Looks like Chrome for iOS.

**Comment by amedeomar** [comment]
yes It is chrome.. but it happens with safari too

**Comment by rschmukler** [comment]
@amedeomar which version of iOS are you running? Just tested in both chrome dev tools and on the iOS simulator and both seem to render correctly. It also renders correctly on my iPad mini, which theoretically should have the same responsive break points (only difference being the 2x device pixel ratio, which shouldn't matter with our rules).

**Comment by amedeomar** [comment]
iOS version 6.1.3

**Comment by rschmukler** [comment]
iOS 6 isn't supported at the moment. The layout does work in iOS 8
