### ISSUE TITLE
Swipe should begin off screen

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#1378]
I want to suggest that the swipe events begin off screen, or, in other words, at point 0 left/right (with some tolerance), for example:

![](https://s3.amazonaws.com/pushbullet-uploads/ujv8hIgQpvE-T2yyApoWl7YmJTfrHm2p2KbL25mtoZEP/Screenshot_2015-02-03-13-52-18.png)
_This one is from Inbox._

I tested this behavior in a few Android apps:

* Gmail
* Drive
* Inbox
* Hangouts
* Photos
* YouTube
* Google Now

All of them will either dismiss or change active tab if you try to swipe anywhere else.

**Comment by gustavohenke** [comment]
It would be nice to add some tolerance also, ~10px for example.

**Comment by ThomasBurleson** [comment]
What do you mean "begin at left:0 or right:100%" ?

**Comment by gustavohenke** [comment]
I'm unable to record a video from my Android phone, so I hope this screenshot is able to sane your question:

![](https://s3.amazonaws.com/pushbullet-uploads/ujv8hIgQpvE-T2yyApoWl7YmJTfrHm2p2KbL25mtoZEP/Screenshot_2015-02-03-13-52-18.png)

Also added it to the initial comment on this issue.

**Comment by robertmesserle** [comment]
Just to note: the swipe gesture absolutely should not require starting off screen.  This would have to be a new gesture.

**Comment by gustavohenke** [comment]
Reading the specs is easier than trying to describe the expected behavior by myself:

> # Edge swipe
>
> A swipe that originates outside of the screen and reveals off-screen content. Invokes out-of-context content, that is, content separate and distinct from the current view.
>
> If no edge swipe action is defined, an Edge swipe gesture can default to a Paging swipe.
>
> The Edge swipe gesture is committed based on crossing a threshold.

_from "Edge swipe" in [Gestures](http://www.google.com/design/spec/patterns/gestures.html#gestures-drag-swipe-or-fling-details) specs_

**Comment by DmitryEfimenko** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
