### ISSUE TITLE
Layout and Navigation elements?

### ISSUE THREAD

**Issue by DavidSouther** [angular/material#1379]
Angular Material as of 0.7 has some great utility components, but no large-scale layout components (eg an entire menu). In the Docs app, there are menu-link, menu-toggle, and a couple others that make very nice one level deep menus with accessibility, etc. Is there any thought of expanding those to be more generic and usable by client code?

**Comment by ThomasBurleson** [comment]
For v1.0, we are focused on components clearly articulated in the [Material Design specification](ww.google.com/design/spec/components).
