### ISSUE TITLE
Input with no label, placeholder only

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#1381]
It's not possible to have a input with no label, placeholder only.
What I want to achieve is the following, taken from the [text fields spec](http://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field):

![](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7bEdJLWVEZjcwQjA/components_textfields_single2.png)

I _think_ I'm able to fix this by writing some CSS, while keeping label + placeholder (I'm not sure how the animation will behave):

```css
md-input-container.md-input-focused label {
  display: none
}
```

...but it would be much cooler if this was built-in.

**Comment by marcysutton** [comment]
Agreed. If we build it in, we can enforce labeling for accessibility purposes with `aria-label`.

**Comment by ilanbiala** [comment]
@marcysutton visually once you click into the field, it isn't clear what goes into the input unless you have an icon next to the input or click out to see the placeholder again.

**Comment by marcysutton** [comment]
Well, it's in the design spec. Frankly, that's a decision for each implementer to make.

**Comment by gustavohenke** [comment]
From the demos, I think this has already been fixed: https://material.angularjs.org/#/demo/material.components.input
