### ISSUE TITLE
Fix NPM Install

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1382]
The current npm Using `npm install angular-material`:

1.  Incorrectly installs globally (for me in `~/node_modules`)
2.  Does not install in a hidden `.node_modules` directory
3.  Does not install the library dependencies 
```json
"dependencies": {
    "angular": "1.3.x",
    "angular-animate": "1.3.x",
    "angular-aria": "1.3.x"
  },
```
4. Consider creating an **npm-material** repository similar to **bower-material**.
5. Update the npm readme to discuss how jspm.io can be used to load Angular Material
6. Update the readme to discuss how require("angular-material") can be shimmed.

**Comment by ThomasBurleson** [comment]
Per comments from @kentcdodds:
I would recommend using `peerDependencies` rather than `dependencies` and be as loose as you can about it. For more info see: http://blog.nodejs.org/2013/02/07/peer-dependencies/ It will save consumers a great deal of headache when trying to use your package.

**Comment by gustavohenke** [comment]
Well.. looks like [there's no package.json in the repository](https://github.com/angular/bower-material/tree/e195ae3480fe7744ceae17341bbadc68a241da26), but this is the resolved package.json from NPM:

```json
{
  "name": "angular-material",
  "version": "0.7.1",
  "main": "angular-material.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/angular/material.git"
  },
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/material/blob/master/LICENSE"
    }
  ],
  "keywords": [
    "angular",
    "material",
    "browser",
    "client-side"
  ],
  "bugs": {
    "url": "https://github.com/angular/material/issues"
  },
  "homepage": "https://material.angularjs.org",
  "readme": "## bower-material\n\nThis repository contains...",
  "readmeFilename": "README.md",
  "description": "This repository contains the Bower release of [angular-material](https://github.com/angular/material).",
  "_id": "angular-material@0.7.1",
  "dist": {
    "shasum": "c2851b70f0ba508cbb5097dba608660709cfd309"
  },
  "_from": "angular-material@",
  "_resolved": "https://registry.npmjs.org/angular-material/-/angular-material-0.7.1.tgz"
}
```

**Comment by robertmesserle** [comment]
This is now resolved: https://github.com/angular/bower-material/commit/da2f9f48709f626e19a127fee74f6c8463cccbd7

However, we will not see the results until we do a new release to NPM.

**Comment by robertbaker** [comment]
@robertmesserle Update the NPM package!
