### ISSUE TITLE
mdDialog docs missing object setup documentation alongside chainable methods

### ISSUE THREAD

**Issue by MarcosPortugal** [angular/material#1383]
Why do we have to chain function calls on dialogs to set their parameters? As in:

```javascript
 var confirm = $mdDialog.confirm()
      .title('Would you like to delete your debt?')
      .content('All of the banks have agreed to forgive you your debts.')
      .ariaLabel('Lucky day')
      .ok('Please do it!')
      .cancel('Sounds like a scam')
      .targetEvent(ev);
```

 I feel like it would be much cleaner to just pass an object with all the parameters to $mdDialog, as is done with most API's in javascript. As in:

```javascript
$mdDialog.confirm({
	title: 'Would you like to delete your debt?',
	content: 'All of the banks have agreed to forgive you your debts.',
	ariaLabel: 'Lucky day',
	ok: 'Please do it!',
	cancel: 'Sounds like a scam',
	targetEvent: ev
}).then(function() {
    $scope.alert = 'You decided to get rid of your debt.';
}, function() {
    $scope.alert = 'You decided to keep your debt.';
});
```

 I really think the current way is counterintuitive. Can anyone explain to me why this is the way it is? Or maybe if it can be changed?

**Comment by marcysutton** [comment]
You don't have to use chainable methods to set up a dialog. You can also provide an object. This is really an issue with the docs. Check this out:

```js
var alert = $mdDialog.alert({
    title: 'Attention',
    content: 'This is an example of how easy dialogs can be!',
    ok: 'Close'
});
    
$mdDialog
    .show( alert )
    .finally(function() {
        alert = undefined;
    });
```

**Comment by MarcosPortugal** [comment]
Oh that's awesome then! Then why is the worse (in my humble oppinion :) ) method the one documented?

**Comment by marcysutton** [comment]
Some people like jQuery-style chainable methods, some prefer objects. It's just a matter of documenting both.

**Comment by MarcosPortugal** [comment]
I agree! Hopefully the docs can be updated :smile: And just as a side note, the jQuery way of creating components and things like that is by passing an object as a parameter. The methods are for actions taken on an already existing element. Take, for example, the jQuery UI components! :+1:

**Comment by marcysutton** [comment]
It's actually a promise API, which is why it looks different than that type of setup. But the chaining style looks similar.
