### ISSUE TITLE
Subheader on mobile device

### ISSUE THREAD

**Issue by franzsilva** [angular/material#1385]
Hi, Ill try to explane myself, im attaching 2 screenshots, the first is my chrome inspector to my mobile device, the subheader has a white overlay that dosent cover all the width, i notice the error was on the 6050 line of docs.css file where it states a margin-right of 16px, when i deactivated it (screenshot 2) it seems to solve the problem, of course on the desktop browser this fix creates the overlay over the scrolbar, 

well hope this helps

Thank you

Regards,

Franz
![screen1](https://cloud.githubusercontent.com/assets/5158380/6034324/a8c064d4-abf3-11e4-8041-469f138bac58.png)
![screen2](https://cloud.githubusercontent.com/assets/5158380/6034325/a8c2aee2-abf3-11e4-86a5-ef27f6a21b3a.png)

**Comment by robertmesserle** [comment]
@franzsilva Is this still an issue for you in 0.10.0-rc2?  I believe this has been addressed, but please confirm.  (Closing issue for now, will re-open if it is still an issue.)
