### ISSUE TITLE
tabs scroll with content

### ISSUE THREAD

**Issue by hkgrani** [angular/material#1387]
See plunker http://plnkr.co/edit/gpawIEjFSx8AeaBA3KyU?p=preview 

For the two fist cards there are tabs above scrolling lists. For both cards the tabs scroll away

Expected behaviour is shown in the bottom card where both toolbar and subheader stays put

**Comment by hkgrani** [comment]
Some more info on this on #1388 and the updated plunk

**Comment by robertmesserle** [comment]
This is by design.  If you want the tabs header to be sticky, you should be putting your content in the tab content and setting that to `overflow: auto;`
