### ISSUE TITLE
Config to control shadow on toolbar needed?

### ISSUE THREAD

**Issue by hkgrani** [angular/material#1388]
Have a look at http://plnkr.co/edit/gpawIEjFSx8AeaBA3KyU?p=preview that was created for another issue.

I have stacked a toolbar on top of tabs in the first cards (seems to be a common use case in material design) - http://www.google.com/design/spec/components/tabs.html

It seems there should be an option to turn shadow off for this use case.

**Comment by gustavohenke** [comment]
I noted this when migrated from 0.7.0 to 0.7.1.
For me, it was an easy fix, I just moved the tabs to `<md-toolbar>`, but this is because I don't want them to scroll with the content.

**Comment by hkgrani** [comment]
Hi
I updated the plunk the fix from @gustavohenke (second card). It works to remove the shadow. You seem to loose the animation though. Thanks for the input. I will use this workaround for now and leave it to the md-team to decide if it is an issue or not (and what ware the "supported" ways to combine these components

**Comment by marcysutton** [comment]
Hi @hkgrani, which animation are you saying is gone? Just checking up on this issue.

**Comment by hkgrani** [comment]
Hi @marcysutton - thanks for the follow up. Have a look at the plunker : http://plnkr.co/edit/gpawIEjFSx8AeaBA3KyU?p=preview On the top of the page the tab content will slide in and out like you would expect from a mobile app. In the middle of the page the "tab content" are changed without animation. The example in the middle uses an ng-if workaround. I guess you could add ng-if to the animation if needed.

The issue witth the subheader on the bottom part of the page is still an issue though, but I think there is a separate issue for that (scroll the bottom list and see the subheader move to the left when it "raises" (at least on chrome-osx)

**Comment by lwcincr93** [comment]
add .md-whiteframe-z1 class to toolbar
