### ISSUE TITLE
infinite scroll with angular material

### ISSUE THREAD

**Issue by david-gang** [angular/material#1390]
Hi,

Is it intended to provide an infinite scroll directive for angular material.
I look for an equivalent for http://ionicframework.com/docs/api/directive/ionInfiniteScroll/

Thanks,
David

**Comment by SiddharthaRRamesh** [comment]
Did you find anything for this. As it sits, Ionics infinite scroll directive does not work along with angular material

**Comment by PaulMougel** [comment]
I'm using https://github.com/sroze/ngInfiniteScroll which does work

**Comment by emps** [comment]
can u up an example cause here its not working some how ? thanks
