### ISSUE TITLE
IE10 Placeholder blocking input focus

### ISSUE THREAD

**Issue by Mutmatt** [angular/material#1394]
With the placeholder value set it seems to be blocking the clickability of the input field. This can be seen in the demo as well [First Name](https://material.angularjs.org/#/demo/material.components.input#input_008).  I don't like the fix i have locally but i added a z-index: 0; to my placeholder as a work around.  I attempted to bind a click event to the placeholder but it seems that it was being caught somewhere on the chain.  Not sure if IE9 is a worry but similar issue is occurring with the label click, this i solved with a
```javascript
element.bind('click', function(ev) {
  containerCtrl.setFocus(true);
  containerCtrl.input.focus();
  //any other existing code
});
```

**Comment by marcysutton** [comment]
Note: We don't support IE9, only n-1 browsers (and IE11 is the latest).

**Comment by Mutmatt** [comment]
Good to note for the label blocking focus, however, as the original bug still seems to stand and be a real hindrance on usability

**Comment by ThomasBurleson** [comment]
@Mutmatt - Is this an IE9 or IE10 issue?

**Comment by Mutmatt** [comment]
@ThomasBurleson **IE10** placeholder blocks input focus.  IE9 had a different issue but due to not being supported (and IE10?) this is a non-issue

**Comment by marcysutton** [comment]
@Mutmatt can you confirm whether this is still happening? The input demos on http://material.angularjs.org do not have any focus problems that I can find. First name has a placeholder and it can take focus and a value without any issues.

**Comment by Mutmatt** [comment]
This is indeed still broken in IE10.  See First Name: https://material.angularjs.org/#/demo/material.components.input

**Comment by marcysutton** [comment]
Yeah, I looked at it in IE10 and it worked fine. Can you describe the issue in more detail, and try another machine? Thanks.

**Comment by Mutmatt** [comment]
I will give it another shot on a different machine.  This one is currently Win 8.1.  The behavior i am seeing is clicking on the area where the placeholder is (albeit not visible) does not trigger the float label to float.  I will check back in after testing on a second/third machine.

**Comment by Mutmatt** [comment]
I retested this in IE10 and it is behaving this way still on the demo page.  Clicking the region where the placeholder text *would* be does not trigger the label float and input focus.  It does work if you click to the right of the location where the text would be.

In this example i click the area a few times to show what i am seeing.
![](http://g.recordit.co/XX13Gl3Ndl.gif)

**Comment by marcysutton** [comment]
Ok, I see it now. It takes a few clicks to register.
