### ISSUE TITLE
material.angular.org is under attack?

### ISSUE THREAD

**Issue by BobbieBarker** [angular/material#1395]
Picture explains it all. Also had other people from the #angularJS room verify this is a problem

![angular-material-not-good](https://cloud.githubusercontent.com/assets/4307099/6053068/100708ec-ac98-11e4-9e37-b353885376a0.png)

**Comment by gflarity** [comment]
Looks like the cert expired today.

**Comment by BobbieBarker** [comment]
it happens, I just wanted to bring this to some one's attention asap.

**Comment by marcysutton** [comment]
We're on it!

**Comment by ilanbiala** [comment]
For me it looks fine in Chrome, no errors/warnings or issues with HTTPS encryption.

**Comment by BobbieBarker** [comment]
Thanks for your timely response on this issue.
