### ISSUE TITLE
$mdThemeProvider not minsafe?

### ISSUE THREAD

**Issue by BobbieBarker** [angular/material#1397]
I am working on a project and I switched from 0.6.0 to 0.7.1, started using the theme provider and everything was awesome in local development. However, when I minified and concat the code I am getting this wonderful combination of errors:

attempted to use unregistered theme 'purple'
Attempted to use unregistered theme 'purple'. Register it with $mdThemingProvider.theme().

**Comment by rschmukler** [comment]
@BobbieBarker what are you using to minimize your code?

**Comment by rschmukler** [comment]
Theming should be min-safe, so I suspect that the warnings are coming from old `md-theme="purple"` declarations in your HTML instead. Feel free to continue discussion in here if I'm wrong and I'll re-open.

**Comment by ThomasBurleson** [comment]
@BobbieBarker - This [CodePen](http://codepen.io/ThomasBurleson/pen/gCrKt) shows use of minified CSS with multiple themes.

**Comment by BobbieBarker** [comment]
There where no left over md-theme="purple" in my code base. I think the problem most definitely was in my build tools some where. I couldn't pin it down, so what I did was basically spin up a new project, upgraded my gulp-angular generator and dropped the code base into it. Problem resolved. Sorry I couldn't provide more helpful feed back.
