### ISSUE TITLE
Click multiple times on sidebar

### ISSUE THREAD

**Issue by nhduc296** [angular/material#1398]
After click multiple time on sidebar, I got this issue:

![bug](https://cloud.githubusercontent.com/assets/4246176/6056240/4ca99cbc-ad40-11e4-8077-2d6cd7107674.png)

Infomation:

Browser: Firefox version 34.0
OS: Windows 7

**Comment by ThomasBurleson** [comment]
As reported by @Blackhole16
---
 When clicking very fast and intensely on buttons, one of the animation-circles will stay on the button until reloading the page.

How to redo:
- Open any page with an angular-material button
- click that button very fast and a lot, until one of the circles stays and doesn't vanish

**Comment by ThomasBurleson** [comment]
The best resolution to these issues is a re-architecture effort for mdRipples. Planned for 0.10.

**Comment by ThomasBurleson** [comment]
Pending fixes with #3952.
