### ISSUE TITLE
Button animation shade doesn't vanish

### ISSUE THREAD

**Issue by Blackhole16** [angular/material#1400]
When clicking very fast and intensely on buttons, one of the animation-circles will stay on the button until reloading the page.

How to redo:
- Open any page with an angular-material button
- click that button very fast and a lot, until one of the circles stays and doesn't vanish

Kind Regards,
BH16

**Comment by yarl** [comment]
Probably copy of #1398

**Comment by ThomasBurleson** [comment]
Duplicate
