### ISSUE TITLE
mdDialog: md-dialog-container problem on IE10

### ISSUE THREAD

**Issue by yarl** [angular/material#1401]
Normally, dialog container has CSS `top` parameter when you scroll down page, eg.:

    <div class="md-dialog-container ng-scope" style="top: 390px;">

On IE10, `top` is always set to `0`, so when you scroll page, you cannot see dialog window. After quick search, it looks problem is [here](https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L332).  `$("body").prop("scrollTop");` returns `0` on IE10.

**Comment by rschmukler** [comment]
@yarl this should, theoretically, be fixed in 0.8.0 RC2 (shipping later today). If it's not, please create a new issue.

**Comment by yarl** [comment]
@rschmukler: It's not working now, but I've added comment in your commit, that fix problem for me.
