### ISSUE TITLE
md-tabs Does not work on mobile using touch, works on desktop

### ISSUE THREAD

**Issue by dberube** [angular/material#1403]
Nothing I do can get md-tabs to work on mobile, works fine in browser.

I can't remember what the last version I used where it works on mobile, I'd like to say it was 0.7.0-rc2...

**Comment by dberube** [comment]
0.7.0-rc3 is last version where md-tabs work on mobile for me.

md-list also doesn't work on mobile touch of an item with link after this version either...

**Comment by marcysutton** [comment]
@dberube can you provide more details about your mobile platform and browser, as well as a Plunker or Codepen with your exact code? Tabs work fine on iOS 8/Safari.

Regarding links within md-list, can you file a separate issue with a Plunker or Codepen as well?

**Comment by justingrayston** [comment]
Tab Demos at v0.7.1 - SHA cd5f91d run ok for me on Android 5.0.1 Chrome

**Comment by dberube** [comment]
Don't have code on me right now, but I forgot to mention that this is in an Ionic Framework app on Android, if that is relevant.

OS: Mac OS X Yosemite
Node Version: v0.10.33
Cordova CLI: 4.2.0
Ionic CLI Version: 1.3.8
Xcode version: Xcode 6.1.1 Build version 6A2008a 
ios-sim version: Not installed

**Comment by beny78** [comment]
When I selecting a tab and my finger slide down outside the tab, the ripple effect start but event is cancelled. On mobile is it difficult to click on tab because tab are small.

**Comment by mikkokam** [comment]
@dberube - Combo **Ionic** +  **0.7.1** will not work on mobile / touch devices or Chrome emulation of a touch device. Might be an issue with the new built-in hammer.js
See also:
#1406

**Comment by ThomasBurleson** [comment]
@mikkokam , @dberube - Angular Material 0.7.1 no longer depends/uses HammerJS. Instead we use a custom $mdGesture service.

**Comment by dongmingliy** [comment]
+1. Same problem for me. I'm also using Ionic Framework.

**Comment by simonh1000** [comment]
I think I have a related problem. I was switching my app to material design and found that none of the 'touch' events on the google map markers are firing. They do work when 'clicked' though.
You can see an example at http://afmnew.herokuapp.com/

**Comment by dberube** [comment]
Yeah, definitely appears to be an issue when used with ionic or cordova (phonegap).

**Comment by mydearxym** [comment]
some issue as @beny78  describe

**Comment by infomofo** [comment]
The conflict is specifically with fastclick, which is bundled native with ionic and many cordova forks. I've described the issue in more detail [here](https://github.com/angular/material/issues/1448).  It seems to affect a few of the core material-design directives.
