### ISSUE TITLE
Displays a white blank screen after building in Cordova

### ISSUE THREAD

**Issue by rougin** [angular/material#1404]
Hello! After I did everything in the [Getting Started](https://material.angularjs.org/#/getting-started) section and build the app using [Cordova](http://cordova.apache.org/) (4.1.2), it only displays a blank screen on my mobile phone. Next is I try it with a ```viewport``` attribute in the ```<meta>``` element but still it produces the same result. I'm currently using the version 0.7.1.

**Comment by gustavohenke** [comment]
What OS and version?
I had many problems while running Angular Material in Android devices older than 4.4.0. That's why I started using [Crosswalk](http://crosswalk-project.org).

**Comment by rougin** [comment]
@gustavohenke I am using Android 4.2.2. Can I merge Cordova with Crosswalk?

**Comment by gustavohenke** [comment]
There you go: https://crosswalk-project.org/documentation/cordova/migrate_an_application.html

**Comment by rougin** [comment]
What version will I use? x86 or ARM? I confused about this. :smile:
