### ISSUE TITLE
Active animations from md-button on initial load

### ISSUE THREAD

**Issue by YurikoEX** [angular/material#1405]
This is a timeline from an ng-click that changes state, renders 20ish md-buttons. They are all marked as "Has an active accelerated animation or transition". I'm not sure if by "active" it means currently animating or just "enabled". I didnt expect to see all the buttons active as if they have been animated on the initial load of the view. I'm looking at about 1 second load time.

![material design jank](https://cloud.githubusercontent.com/assets/1495192/6068874/d30fd494-ad4d-11e4-9dc0-94f6a3f76457.PNG)

**Comment by YurikoEX** [comment]
oh, using build 0.7.0-rc3-master-1c97333

**Comment by marcysutton** [comment]
Can you upgrade to 0.7.1?

**Comment by ThomasBurleson** [comment]
@YurikoEX - Can you provide a Plunkr or CodePen that demonstrates the problem?

**Comment by robertmesserle** [comment]
@YurikoEX Is this still an issue in 0.10.0-rc1?  Closing this issue for now, but please reply and I will re-open if it is still an issue.
