### ISSUE TITLE
Selecting <label> no longer selects associated radio button on mobile

### ISSUE THREAD

**Issue by bdonham** [angular/material#1408]
I have to use some custom radio buttons (HTML + CSS) for a rating system and their labels are styled and the actual radio button is hidden. It is not material but I use material for everything else in the app.

0.7.1-f1a4bcc3d1 is the last material commit that this works. The recent commits have disabled this function on mobile devices, but works on desktop (chrome). Not sure why.

example:
````
<label><input type="radio" ng-model="data.response[question.QuestionID]" ng-value="0">0</label>
````

**Comment by marcysutton** [comment]
Hi @bdonham, can you provide a Plunker or Codepen showing how you're hiding the "actual radio button"? That will help in the debugging process. Thanks!

**Comment by marcysutton** [comment]
@bdonham can you please provide a demo?

**Comment by bdonham** [comment]
Sorry for the delay @marcysutton, Im am working on providing you a demo.

**Comment by bdonham** [comment]
@marcysutton - Here is the Plunker of what I have going on, a bit messy i know. I had to remove some backend stuff for it to work on plunker. The horizontal radio buttons work fine on a desktop browser, but the radio buttons only work correctly on a mobile device if running material 0.7.1, nothing newer.

Its currently running the latest release, I added in 0.7.1, its commented out in the index.

http://plnkr.co/edit/wp2WSTow9bxXPiIBL8tI?p=preview

Maybe you guys could add a feature for horizontal radio buttons?

**Comment by marcysutton** [comment]
Sorry to say this is outside of the scope of Angular Material. Radio buttons don't have numbers inside of them, and there aren't horizontal options. I think rolling your own solution without `mdRadioButton` will be the best option here (meaning it will get done faster), as a new feature would have to be added to the backlog.

**Comment by topherfangio** [comment]
@bdonham I cannot seem to get the Plunkr to load and based on @marcysutton's response above, I believe we should close this.

However, if you can provide a concise [Codepen](http://codepen.io) demonstrating the exact issue, we will definitely take a look.

You can use the [radio button demo](https://material.angularjs.org/HEAD/#/demo/material.components.radioButton) as a starting point by clicking the "Edit on Codepen" button in the top right of the demo and stripping out everything but the simple radio button that is failing.

**Comment by topherfangio** [comment]
Since no feedback has been provided, I am going to close this issue. If you can provide a Codepen that shows the exact issue, we will reopen and take a look.
