### ISSUE TITLE
Make an `<img>` in a card not 100% width

### ISSUE THREAD

**Issue by donpinkus** [angular/material#1412]
Is it possible to make an `<img>` in a card not 100% width?

By default `<img>`s maintain their aspect ratio if only the "height" or "width" attribute is set.  I can't achieve this behavior when an `<img>` is inside a card. 

Cards automatically add `width: 100%` to all images. I tried removing this, but the image is still 100%.

**Comment by EladBezalel** [comment]
I think its might be related to #1230, are you on the latest build?

**Comment by marcysutton** [comment]
@donpinkus can you check whether the fixes in #1230 solved your issue?

**Comment by marcysutton** [comment]
Quoting the [forum](https://groups.google.com/forum/#!topic/ngmaterial/EV9NTxLWrAM): 

>It aligns with the spec for cards, where images go all the way to the edge. In its current state, you can put an image into md-card-content if you don't want it to fill. Otherwise, limit the width of the card by wrapping it. 

>That said, I think there are a few other card layouts that could be added (such as a floated portrait-orientation image). But that would have to be put into the feature request queue.
