### ISSUE TITLE
How to pass an angular-material list to an angular-material dialog?

### ISSUE THREAD

**Issue by darylyu** [angular/material#1413]
I'm following this as my guide: https://material.angularjs.org/#/demo/material.components.dialog

I've got a $scope.items inside AppCtrl, but I don't know how to make DialogController display it in dialog1.tmpl.html.

**Comment by PaulMougel** [comment]
```js
angular
.module('yourApp')
.controller('AppCtrl', function ($scope) {
  $scope.items = [0, 1, 2, 3];
  $mdDialog.show({
      controller: 'DialogController'
      templateUrl: 'Dialog.html'
      locals:
        items: $scope.items
  });
});

angular
.module('yourApp')
.controller('DialogController', function ($scope, items) {
  // items is injected in the controller, not its scope!
  $scope.items = items;
});
```

**Comment by darylyu** [comment]
Got it to work. Thanks for pointing me in the right direction.

**Comment by ajoslin** [comment]
If you use controllerAs, you can make it shorter too.

```js
myApp.controller('AppCtrl', function($scope, $mdDialog) {
  $scope.items = [1,2,3];
  $mdDialog.show({
    controller: function Ctrl() {},
    controllerAs: 'ctrl',
    templateUrl: 'dialog1.tmpl.html',
    locals: {
      items: $scope.items
    }
  });
});
```

Then you can just reference `ng-repeat="items in ctrl.items"` in your template.

**Comment by ThomasBurleson** [comment]
@darylyu - in the future, these types of questions should be posted in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by ThomasBurleson** [comment]
Reopen - need to update Dialog docs.

**Comment by marcysutton** [comment]
@ThomasBurleson I have a PR open for dialog dogs: #1411

**Comment by marcysutton** [comment]
Closing as more detail was added to the mdDialog docs. Feature request discussion is still open in #1531.

**Comment by parmalatinter** [comment]
$scope.showImageDialog = function (ev, imageUrl) {
                $mdDialog.show({
                    controller: 'DialogCtrl',
                    controllerAs: 'ctrl',
                    templateUrl: ''templates/image-dialog-template.html",
                    parent: angular.element(document.body),
                    targetEvent: ev,
                    clickOutsideToClose: true,
                    locals:{
                        imageUrl: imageUrl
                    }
                })
            };

        .controller('DialogCtrl', function ($scope, $mdDialog, locals) {
            $scope = locals;
        })

then you can use {{imageUrl}}

**Comment by codigoalvo** [comment]
Thank you very much for point me in the right direction.

**Comment by HemanthkumarHJ** [comment]
$scope.composeDialog = function (ev)
        {
			vm.res=vm.result[ev];
			console.log(vm.res);
			$mdDialog.show({
				controller         : 'ManageProductController',
				controllerAs       : 'vm',	
				locals             : {
                    item: vm.res
                },
				templateUrl        : 'app/main/apps/manage-product/compose-dialog.html',
				parent             : angular.element($document.body),
				targetEvent        : ev,
				//clickOutsideToClose: true
			});		
        }
I couldn't get the values in page using this code. Is here any wrong?

**Comment by HemanthkumarHJ** [comment]
`$scope.composeDialog = function (ev)
        {
			vm.res=vm.result[ev];
			console.log(vm.res);
			$mdDialog.show({
				controller         : 'ManageProductController',
				controllerAs       : 'vm',	
				locals             : {
                    item: vm.res
                },
				templateUrl        : 'app/main/apps/manage-product/compose-dialog.html',
				parent             : angular.element($document.body),
				targetEvent        : ev,
				//clickOutsideToClose: true
			});		
        }`
I couldn't get values using this code, is here any wrong?

**Comment by parmalatinter** [comment]
Did You inject locals to ManageProductController args?

Example

controller('DialogCtrl', function ($scope, $mdDialog, locals) {
        $scope.locals = locals;
    })

**Comment by sagarrajak** [comment]
no  pls this type of question is helpful for me  becaus https://groups.google.com/forum/#!forum/ngmaterial  can't be searched by google

**Comment by shafeeqthayyil** [comment]
nice , its helped me

**Comment by florin05** [comment]
I struggled to make @ajoslin 's version work since it is the simplest, but couldn't. I had to use this method for controller definition (parameter injection)

```
myApp.controller('AppCtrl', function($scope, $mdDialog) {
  $scope.items = [1,2,3];
  $mdDialog.show({
    controller: ['items', function (items) {this.items = items;}],
    controllerAs: 'ctrl',
    templateUrl: 'dialog1.tmpl.html',
    locals: {
      items: $scope.items
    }
  });
});
```
