### ISSUE TITLE
md-whiteframe only allowing <span> elements.

### ISSUE THREAD

**Issue by ethanmick** [angular/material#1417]
Hey everyone, great job on this.

On my site, I have this HTML:

```
<p>
  <md-whiteframe class="md-whiteframe-z2" layout="row" layout-align="center center">
    <h2>Note</h2>
    <span>
      In this example, the query is not URL-encoded for improved readability. All URL parameters should be encoded before being sent.
    </span>
  </md-whiteframe>
</p>
```

But for some reason, this is rendering to: (using chrome's inspector):
```
<p class="ng-scope">
  <md-whiteframe class="md-whiteframe-z2" layout="row" layout-align="center center">
    </md-whiteframe>
</p>
<h2 class="ng-scope">Note</h2>
<span class="ng-scope">
      In this example, the query is not URL-encoded for improved readability. All URL parameters should be encoded before being sent.
</span>
```

Which gives this appearance:
![bug](http://cl.ly/image/051X0n0O2A0l/Screen%20Shot%202015-02-06%20at%204.33.25%20PM.png)

If I refresh with this HTML:

```
<p>
  <md-whiteframe class="md-whiteframe-z2" layout="row" layout-align="center center">
    <span>
      In this example, the query is not URL-encoded for improved readability. All URL parameters should be encoded before being sent.
    </span>
  </md-whiteframe>
</p>
```

The resulting HTML is:
```
<p class="ng-scope">
  <md-whiteframe class="md-whiteframe-z2" layout="row" layout-align="center center">
    <span>
      In this example, the query is not URL-encoded for improved readability. All URL parameters should be encoded before being sent.
    </span>
  </md-whiteframe>
</p>
```

It works correctly:
![no-bug](http://cl.ly/image/2g442F3t2n2O/Screen%20Shot%202015-02-06%20at%204.34.33%20PM.png)

From what I can see, by putting any other element (`<h2>` or `<p>`), it breaks the whiteframe. Am I doing something silly?

Using Angular 0.7.1.

**Comment by marcysutton** [comment]
It's because you can't wrap `<h2>`s in `<p>` tags. Try putting the paragraph and heading tags inside of `<md-whiteframe-content>`.

**Comment by marcysutton** [comment]
Also, this is a great question for the [ngMaterial Forums](https://groups.google.com/forum/#!forum/ngmaterial)!

**Comment by ethanmick** [comment]
Awesome, thanks! Didn't realize my markup was messing things up. :+1:

**Comment by marcysutton** [comment]
That's Chrome "helping" you to create correct markup. It's actually pretty amazing how complex browsers are!

**Comment by ThomasBurleson** [comment]
@ethanmick - great question. Just a follow-up to @marcysutton's comment. Questions should be posted on the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
