### ISSUE TITLE
Input with long placeholder doesn't get cut off

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1419]
With regular inputs that have a placeholder that doesn't fit in the input, the placeholder gets chopped off. With ngMaterial, the placeholder continues to wander outside of the input.

![screen shot 2015-02-06 at 7 20 48 pm](https://cloud.githubusercontent.com/assets/3695164/6089719/4bcc1f04-ae35-11e4-9df1-22380aa50701.png)

**Comment by marcysutton** [comment]
We'd love to see PRs that fix these kinds of issues.

**Comment by ilanbiala** [comment]
@marcysutton can you point me to the HTML code for the `md-input-container` and I'll try to see what's the issue.

**Comment by ilanbiala** [comment]
@marcysutton I took a look at the JS, HTML, and CSS, and it seems that adding `overflow-x: hidden` to the `md-input-container` fixes it and doesn't cause other issues. You may want to do more testing to see if it causes any issues I didn't notice.

**Comment by marcysutton** [comment]
@ilanbiala seems easy enough for a PR, want to take a crack at it?

**Comment by ilanbiala** [comment]
@marcysutton not really sure what else there is to it, but at least the PR is a start.

**Comment by ilanbiala** [comment]
@marcysutton have you had a chance to look at the PR? It's just the fix I suggested above. I don't think it breaks any compatibility with other parts of the component.
