### ISSUE TITLE
Buttons require a visual focus state

### ISSUE THREAD

**Issue by marcysutton** [angular/material#142]
To make flat and raised buttons accessible from the keyboard, they should have visual contrast upon user interaction. In the [Material Design](http://www.google.com/design/spec/components/buttons.html#buttons-main-buttons) spec, focus states are illustrated with a ripple effect: 

![Flat button states](https://cloud.githubusercontent.com/assets/1045233/3960549/63f99d06-2742-11e4-93e9-5959e48ce9ef.png)
![Raised Button states](https://cloud.githubusercontent.com/assets/1045233/3960518/c1e58e08-2741-11e4-9369-d127feec41ea.png)

A similar ripple effect is needed to add focus states to all buttons.

**Comment by sambryant** [comment]
It seems like some of you are suggesting that the problem is that the element is remaining in a focus state. I think it's supposed to do that: http://jsfiddle.net/nv3rvru1/8/

**Comment by albertboada** [comment]
:+1:

**Comment by skribbz14** [comment]
Don't you think there could be some sort of option applied to the <md-button> that would choose whether we want the :focus to stay on or be removed after clicking? This seems to be a personal preference that not everyone agrees on, so allowing the developer to choose would make everyone happy.

**Comment by marcysutton** [comment]
Buttons actually have a focus state now, so I'm closing this issue.

@skribbz14 to answer your question, consistency is more important in this case. Supporting both of those options would add a lot of complexity to maintain, and in my opinion would fragment the Material Design user experience. I have a question out to the UX team about how controls should handle visual focus in a way that works with the browser and looks intentional. Work on that can be tracked here: https://github.com/angular/material/pull/1594

There is also a separate issue open for the button pressed state: #2089

**Comment by chanakaDe** [comment]
Yeah all the buttons are ok with now.
