### ISSUE TITLE
<md-button> creating error

### ISSUE THREAD

**Issue by zebMcCorkle** [angular/material#1421]
I really don't know what to say other than this:

https://gist.github.com/zebMcCorkle/c7ba6175b0c3f510c001

creates this:

https://docs.angularjs.org/error/$compile/multidir?p0=mdButton&p1=mdButton&p2=transclusion&p3=%3Cbutton%20class%3D%22md-raised%20md-primary%20md-button%22%20ng-transclude%3D%22%22%3E

**Comment by EladBezalel** [comment]
Can you please put this on plunker? It's seems fine to me but i want to play with it a little and see what's the problem..

**Comment by robertmesserle** [comment]
What browser are you seeing this in?  I created a Plunker with this code and it seems to work fine.

http://plnkr.co/edit/kdF3JLrZXr1vri5OAhUk?p=preview

**Comment by robertmesserle** [comment]
Closing for now, please re-open with more details on how to recreate.
