### ISSUE TITLE
Sliders defaults to primary color and cannot be set using md-accent

### ISSUE THREAD

**Issue by Luminess** [angular/material#1422]
As mentioned [here](https://material.angularjs.org/#/api/material.components.slider/directive/mdSlider), 
"the slider is in the accent color by default". You can see the issue [here](https://material.angularjs.org/#/demo/material.components.slider).

**Comment by ThomasBurleson** [comment]
Per the [Material Design Spec](http://www.google.com/design/spec/style/color.html#color-ui-color-application):  "Use the accent color for your primary action button and components like switches or sliders."
