### ISSUE TITLE
Proper way for creating qwerty keyboard

### ISSUE THREAD

**Issue by AskarovBeknar** [angular/material#1424]
I am creating kiosk app for vending machines with chromium os inside, where inputs are made using virtual keyboard; 
I am considering to use "Bottom sheets" for creating Lollipop android qwerty keyboard.
By characteristics it fits for this task., but it feels like it breaks the semantics and ideology of material design.
I would be wondering if you could suggest a proper way for accomplishing this task.

**Comment by epelc** [comment]
@ITBeka chrome os and I imagine chromium os have an on screen keyboard along with most other operating systems. I think this would work much better than trying to make your own keyboard.

https://support.google.com/chromebook/answer/177893?hl=en

**Comment by ITBeka** [comment]
I think default app is not in material look. but. Actually its very good
idea i can even create seperate materialish keyboard app. thank you.
