### ISSUE TITLE
Conflict! When programmatically setting input's placeholder using angular-translate service

### ISSUE THREAD

**Issue by askbeka** [angular/material#1427]
my jade looks like this

md-input-container
......label {{'trans_label' | translate}}
......input (ng-model="model" placeholder="{{'trans_placeholder' | translate}}")

when window loads placeholder is visible and when I focus on input element input placeholder and 'md-placeholder' appear on top of each other.

no focus:
![screenshot from 2015-02-08 16 44 41](https://cloud.githubusercontent.com/assets/3000474/6096280/22fc5146-afb3-11e4-8f15-76af4156fcaa.png)

after focus: 
![screenshot from 2015-02-08 16 46 56](https://cloud.githubusercontent.com/assets/3000474/6096281/2d3085ba-afb3-11e4-893c-f0a42506c511.png)

**Comment by CharlSparksNZ** [comment]
@AskarovBeknar - You really shouldn't be setting a placeholder if you want to use the floating label. Material design uses the label to do that for you hence they are "conflicting". Either use just a placeholder or just a label but using both defeats the purpose of using a labeled input field.

**Comment by AskarovBeknar** [comment]
Thank you for your reply. But I dont agree. Cause label for input signifies what to enter,and placeholder show how to enter it. For example
it makes sense when input field is used for searching the multiple kinds if items like cross roads, bus stations, bus routes. Where some format should be used in order for search propram to perform well. And user won't struggle not knowing what and how to enter

**Comment by ThomasBurleson** [comment]
@AskarovBeknar - please provide a CodePen or Plunkr that manifests this issue.

**Comment by ilanbiala** [comment]
@ThomasBurleson @AskarovBeknar I find that the case made here is valid that a label is what the input is and the placeholder is the formatting of the input.

**Comment by ThomasBurleson** [comment]
@ilanbiala - Perhaps that is true... how do you propose that the UX handle such concerns?

**Comment by ilanbiala** [comment]
When the input isn't focused the label is shown, when it is the label is floated and the placeholder is shown until a character is typed. If there is no placeholder, then the label is sufficient in cases like "First name" and that is subject to the package consumer's disgression. Things like "dates to skip" requires some hint as to the format, though, and in that case a placeholder would probably be a good idea to show the format when someone focuses on that input.

**Comment by AskarovBeknar** [comment]
@ilanbiala  Yes, exactly, you are right.  
[Here is a sample showing issue](http://codepen.io/AskarovBeknar/pen/XJzoeO)

**Comment by CharlSparksNZ** [comment]
@ilanbiala @AskarovBeknar - You both have very valid cases and I understand where you are coming from. The main UX problem with placeholders (or as the Material Design spec refers to them "hint text") is that they are hidden from the user when they type. This might be ok for small pieces of information but we are expecting the user to remember exactly what is required of them. If you are dealing with edge cases where user inputs become complicated it would be best if you added assistive features be it autocomplete or a popup datepicker allowing them to select "dates to skip" to ease the learning process. 

If you had to go with placeholders I think having something similiar to the character counter on text fields would be more helpful. You could specify something like md-input-warn-text="..." and md-input-help-text="..." that would show on focus and change on blur if the user was still unsuccessful. This means you are never hiding info from the user and only providing feedback when necessary. This can conflict with the character counter though... Any thoughts @ThomasBurleson ?

**Comment by zeeshanjan82** [comment]
Any Idea how to fix this issue, I am also experiencing the same issue with placeholders when using translate filter.

**Comment by ngraef** [comment]
Support for input having both a label and placeholder was removed in `0.9.0-rc3` via d931c0d237777c0197464277a5d8096bc3cbd698.

Personally, I would like to see this functionality restored. I think the floating label and hint text have different uses and can be used simultaneously to assist a user while filling out a form.

**Comment by thanuzz** [comment]
See #1742 for a workaround I've created by extending the Angular Material Placeholder directive. #

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by RicardoPaixao** [comment]
simple, functional workaround:
execute
`$('#inputId').parent().parent().addClass('not-empty-state');
`right after programatically injection the placeholder or input value.

**Comment by RicardoPaixao** [comment]
simple, functionl workaround:
execute
`$('#yourInput').parent().parent().addClass('not-empty-state');`
after programatically setting the placeholder or value of the input
