### ISSUE TITLE
mdTooltip - Allow forcing visibility

### ISSUE THREAD

**Issue by yjaaidi** [angular/material#1428]
Hi,

We have some use cases where we want multiple button tooltips to be displayed unconditionally. We are using md-visible but when the user focuses on one of the buttons for example other tooltips disappear due to this listener:

    parent.on('blur mouseleave touchend touchcancel', function() {
      // Don't hide the tooltip if the parent is still focused.
      if ($document[0].activeElement === parent[0]) return;
      setVisible(false);
    });

Wouldn't it be nice to a have some 'md-visible-force="true"' attribute to disable these listeners in order to fully control the tooltip's visibility using 'md-visible'?

**Comment by marcysutton** [comment]
I'm pretty sure you should only use one tooltip per element. Are you saying the content of the tooltip changes conditionally?

**Comment by yjaaidi** [comment]
The text doesn't change and we are only using one tooltip per element.

But we are implementing a fixed floating button that triggers a vertical floating menu. On desktop, showing one tooltip at a time is fine as the tooltip will be displayed on focus.
But on touch screens, the user will touch the menu button that will display other buttons and then we want to show all the tooltips for all the buttons simultaneously, otherwise the user has no way to understand the use of the button.

By using, md-visible="true", it works but when the user touches one of the buttons, this triggers a focus event on the touched button and a blur event on other buttons which hides the tooltip of other buttons so the next time when the user triggers the menu again, the tooltip will only be displayed on the last clicked button.
![float_menu_button](https://cloud.githubusercontent.com/assets/2674658/6124603/1a650476-b10f-11e4-8510-b374b12521f6.png)
![float_menu_focus](https://cloud.githubusercontent.com/assets/2674658/6124604/1a673fde-b10f-11e4-8386-feeb332dbec1.png)

**Comment by evoker** [comment]
I am on the same boat. I would like to show tooltips using md-visible but the way that focus events are handled is a bit confusing (to my relatively non-javascript savvy eyes).

I am talking about this: 
`($document[0].activeElement !== parent[0])`

I am trying to implement a speed dial fab menu and I am showing the tooltip 0.3s after the trigger button is hovered. But when I hover over each of the buttons, the above code is true and the tooltips get hidden for a millisecond.

Hope this is related to the issue mentioned here.
