### ISSUE TITLE
Disable md-sidenav auto close on content click

### ISSUE THREAD

**Issue by jeremytrawls** [angular/material#1429]
Currently there's no configuration option to enable/disable the side nav from closing when the main content area is clicked on.  

I have a couple of business cases where I need to change my application state based on the 'isOpened' attribute of the md-sidenav directive and the only way that I'm currently able to do that now is using $scope.Watch, which seems very hackish to me.

**Comment by ThomasBurleson** [comment]
@jeremytrawls:

```html
<md-component-id="stateTest" md-is-open="shouldOpen" md-is-locked-open="shouldLockOpen" />
```

```
$mdSidenav("stateTest").isLockedOpen();
$mdSidenav("stateTest").isOpen();


For your other question(s):  Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by sorin7486** [comment]
@ThomasBurleson I'm having the same problem and your answer, unfortunately, doesn't solve it. If i use md-is-locked-open the behavior changes and the sidenav does not open over the content anymore. Also clicking on buttons in the content is not disabled.

What I would need, and I presume what the initial post was about, is for md-sidenav to behave like a modal dialog. 

Could you reopen this issue or should I create a new one?
