### ISSUE TITLE
md-discrete sliders often does not snap to nearest step

### ISSUE THREAD

**Issue by Luminess** [angular/material#1431]
This issue has appeared in the last 2-3 days. An example of this issue can be found [here](https://material.angularjs.org/#/demo/material.components.slider).

**Comment by ThomasBurleson** [comment]
@robertmesserle - something is messed up... is mdGestures interfering?

**Comment by mckenzielong** [comment]
In slider.js, the slider position is never being updated after the drag / event.  The slider position is set in onPressDown at the beginning of the event, but as I mentioned, not after the event.  Add setSliderPercentage call after the model is updated?
```javascript
    function onPressUp(ev) {
      if (isDisabledGetter()) return;

      element.removeClass('dragging active');

      var exactVal = percentToValue( positionToPercent( ev.pointer.x ));
      var closestVal = minMaxValidator( stepValidator(exactVal) );
      scope.$apply(function() {
        setModelValue(closestVal);
        setSliderPercent( valueToPercent(closestVal));
      });
    }
```

**Comment by ThomasBurleson** [comment]
@robertmesserle - is this an issue with `$mdGesture` ?

**Comment by robertmesserle** [comment]
@ThomasBurleson I haven't had a chance to look into it yet, but that's what I suspect.

**Comment by mckenzielong** [comment]
This was introduced by this change: https://github.com/angular/material/commit/7028a75058338533696d75d532e7f13f6d6f1fff

Adding this back into onDragEnd also resolves the issue -- either way there was a missing call to setSliderPercent.
```javascript
var exactVal = percentToValue( positionToPercent( ev.pointer.x ));
var closestVal = minMaxValidator( stepValidator(exactVal) );
setSliderPercent( valueToPercent(closestVal));
```
