### ISSUE TITLE
md-slider should have a option to update the model after the user has stopped sliding it.

### ISSUE THREAD

**Issue by Darwesh27** [angular/material#1435]
Right now when we slide the slider, the model value changes. But if that model value is bind to some variable on backend, then sliding it will cause a lot of server calls. I want the slider to update the server only when the user has set its value, and mouse has left.

**Comment by Darwesh27** [comment]
This works for discrete slider. But for linear slider there should be an option like that..

**Comment by Flertz** [comment]
+1
Seiyria bootstrap-slider is a nice example (see events).

**Comment by ThomasBurleson** [comment]
@Darwesh27 - I do not understand. If I use:

```html
<md-slider 
          md-discrete 
          ng-model="rating" 
          step="1" min="1" max="5" 
          aria-label="rating" flex >
</md-slider>
```
Then the **rating** model value will be updated as the slider changes.

**Comment by Flertz** [comment]
@ThomasBurleson you are right: the rating model value will be updated. But if you want to update some back-end variable ONLY when the user stops to dragging, you should have some events fired from the slider.

**Comment by ThomasBurleson** [comment]
@Flertz, @Darwesh27 - the team made specific decisions to minimize the use of custom change events. Instead Angular Material expects developers to use standard AngularJS practices to `$watch` for specific model changes and respond accordingly.

Closed - No change expected.

**Comment by dbtek** [comment]
@Flertz, @Darwesh27 sure it's a little late however; there might be ones still encountering this case.

[ngMouseUp](https://docs.angularjs.org/api/ng/directive/ngMouseup) directive perfectly solves the problem here. Bind some model to slider and do stuff with that model on `mouseup` event.

Hope it'll help. Thanks.

**Comment by zverevalexei** [comment]
@dbtek ngMouseUp does not work properly it when you start dragging the slider, but end up releasing mouse button out if its zone. However, if your cursor is still over the slider, I will surely be able to catch the event...

**Comment by qoshi** [comment]
@dbtek 
This a very ugly implement for resolve this issue. I tried to using ng-change to resolve this issue, but I failed.
1. ng-mouseup should be added at md-slider-container. This will expand the event to the whole slider area. When click other part inner slider container but not on slider itsself it will call the api and wast of some resource.
2. When we want to type something into the input to modify the value, The stupid ng-mouseup won't fire.
3. $watch is not the best practice for this issue.

**Comment by aj-r** [comment]
You could use lodash's [`_.debounce()`](https://lodash.com/docs/4.16.4#debounce) or a similar method. It might not be perfect, but it would at least cut down on your server calls dramatically.

**Comment by SergeyKurdyukov** [comment]
@qoshi 

> ng-mouseup should be added at md-slider-container.

Thank you for suggestion! It helps me.

**Comment by pyroflies** [comment]
This is still an issue as alwye and qoshi have outlined.
md-discrete seems to catch the mouseup event, but comes with its own set of problems (and different UI you may not want)

**Comment by mk4yukkalab** [comment]
You really did not provide an event drop or mouse up on this slider?
I need to navigate to a specific value only when the user selects the right value in the slider its mean on mouse up or drop. Pls, provide this event. Thanks.

**Comment by Splaktar** [comment]
@mk4yukkalab I would be open to a community PR that adds some custom events (and tests) to the slider. The first step would be to open a new enhancement request with the proposed approach and APIs.
