### ISSUE TITLE
Theming primaryPalette is an unresolved function.

### ISSUE THREAD

**Issue by glynjackson** [angular/material#1436]
Using  the latest version ``0.7.0`` as stated on GitHub. The docs state to change theme use the following...

```
angular.module('myApp', ['ngMaterial'])
.config(function($mdThemingProvider) {
  $mdThemingProvider.theme('default')
    .primaryPalette('pink');
});
```

However ``primaryPalette`` is an unresolved function. Where ``primaryColor`` does work. Which should we be using?

**Comment by epelc** [comment]
@glynjackson I think this has been fixed in `0.7.1`

**Comment by ThomasBurleson** [comment]
Fixed.

**Comment by glynjackson** [comment]
@tbosch Thank you for the fast reply, much appreciated.
