### ISSUE TITLE
slidding slider adds width

### ISSUE THREAD

**Issue by tolysz** [angular/material#1437]
https://material.angularjs.org/#/demo/material.components.slider

There will be horizontal scroll bar for high scroll values

**Comment by ksidpen** [comment]
+1 confirm

**Comment by ThomasBurleson** [comment]
@robertmesserle  - related to #1343

**Comment by tolysz** [comment]
Ok, I guess will close it as a duplicate ( https://github.com/angular/material/issues/1343 )
