### ISSUE TITLE
mdToast Circular dependency

### ISSUE THREAD

**Issue by maximilianmikus** [angular/material#1439]
I would like to use the $mdToast provider in an $httpProvider.interceptors function to show server response messages as toasts.

``` javascript
    // Intercepts 401s and redirects user to login
    $httpProvider.interceptors.push(['$q', '$location', '$mdToast', function($q, $location, $mdToast) {
      return {
        'responseError': function(response) {
          if(response.status === 401) {
            $mdToast.showSimple('Access denied');
            return $q.reject(response);
          }
          else {
            var message = response.status + ': ' + response.statusText;
            $mdToast.showSimple(message);
            return $q.reject(response);
          }
        }
      };
    }]);
```

This generates the following error:

    Uncaught Error: [$injector:cdep] Circular dependency found: $http <- $templateRequest <- $animate <- $$interimElement <- $mdBottomSheet <- $http <- $resource <- Session <- Auth

What would be the best way to make this work, or is there already a way to make this work?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by mannava** [comment]
Hey Maxi, 

Did You get the solution for issue ? I am also having same issue.
Let me know , If You have any solution for that.

Thanks,
Mannava.

**Comment by maximilianmikus** [comment]
Hi Mannava, 

please see the post in the Angular Material Forum as mentioned above: 

https://groups.google.com/forum/#!searchin/ngmaterial/mdToast/ngmaterial/-HkfCIufBfo/oBISx2_-4WMJ

**Comment by valmirphp** [comment]
Descobri uma forma de resolver isso:

```js
    // Intercepts 401s and redirects user to login
    $httpProvider.interceptors.push(['$q', '$location', '$injector', function($q, $location, $injector) {

   var toastr;

    function getToaster() {
      if (!toastr) {
        toastr = $injector.get("$mdToast");
      }
      return toastr;
    }

      return {
        'responseError': function(response) {
          if(response.status === 401) {
            getToaster().showSimple('Access denied');
            return $q.reject(response);
          }
          else {
            var message = response.status + ': ' + response.statusText;
            getToaster().showSimple(message);
            return $q.reject(response);
          }
        }
      };
    }]);
```

**Comment by khrisnet** [comment]
Olá @valmirphp estou tendo problemas ao estender $mdToast retornando a mesma mensagem de erro relatada nessa issue.

Quanto digo estender me refiro que tenho uma factory por exemplo "ToasterService" que implemento alguma particularidades ao $mdToast até mesmo para não ficar dependente dessa biblioteca em todo o meu projeto.

Por acaso já passou por algo semelhante?

**Comment by valmirphp** [comment]
Eu sempre usei direto o $mdToast, mais caso vc queira abstrai para dentro de um serviço seu, basta injetar ele (passar como dependência na construção do seu service.

Pode postar o código do seu service?
De preferencia o erro junto.

**Comment by khrisnet** [comment]
Primeiramente obrigado ai pelo apoio.

Realmente estou fazendo isso, como pode perceber no meu código abaixo:

https://gist.github.com/khrisnet/82654ff2627afe236558

Obs: no meu "app.services" estou carregando o modulo "ngMaterial" normalmente.

**Comment by valmirphp** [comment]
Vou te responder pelo gist, pois essa issues é de outro assunto.

**Comment by khrisnet** [comment]
Perfeito!
