### ISSUE TITLE
md-tooltip: Show from svg

### ISSUE THREAD

**Issue by epelc** [angular/material#1440]
I'm currently adding some graphs to my app with d3.js and I just started looking into tooltips. I've found this nice tooltip plugin which works perfectly however it's essentially duplicating most of the `md-tooltip` code. It works the same way as in it adds an element to the parent which contains your tooltip.

It'd be nice if we could use `md-tooltip` from an svg programmatically somehow by calling show/hide and perhaps passing some sort of position or using the various mouse over events. I tried just putting a regular `md-tooltip` element inside an svg but I don't think the spec allows this. Perhaps a better solution would be to support setting the tooltip for an element with an attribute.

Anyways ideas are welcome.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
