### ISSUE TITLE
Touch events not working on Google Map Markers

### ISSUE THREAD

**Issue by simonh1000** [angular/material#1441]
I am trying to switch my angular app to material design and found that none of the 'touch' events on the google map markers are firing (tested on phone, devtools and iOS simulator). They do work when 'clicked' though, and touch works on other parts of the app. You can see an example at http://afmnew.herokuapp.com/

**Comment by simonh1000** [comment]
For what it is worth I could solve the issue by using a `mousedown` event handler. Hitherto - with bootstrap - I had been using `click` events

**Comment by manuelfc1** [comment]
The same happens to me.
The problem is that the mousedown event does not work like click, especially with the info window

**Comment by simonh1000** [comment]
I think this is fixed in 0.8.2

**Comment by manuelfc1** [comment]
Not working yet in mobile devices and with angular-google-maps

**Comment by simonh1000** [comment]
Ah yes, you are right - was using desktop chrome

**Comment by myellepeddy** [comment]
We have the same issue. May be a conflict with $mdGestures ? Is there a way to disable $mdGestures for a <div> ?

**Comment by ThomasBurleson** [comment]
Fixed for most cases. 
For mobile solutions that are also using jQuery, you can now use $mdGestureProvider in 
```js
   app = angular.module('MyApp', ['ngMaterial'])
      .config(function( $mdGestureProvider ) {
          $mdGestureProvider.skipClickHijack();
      });
```
This will configure $mdGesture to **not** intercept clicks (stop propagation and prevent defaults).
