### ISSUE TITLE
Broad style rules in structure.scss can cause conflicts

### ISSUE THREAD

**Issue by jelbourn** [angular/material#1442]
The very broad rules in structure.scss (example below) can cause issues when used alongside another component library. We should explore ways to apply these styles more selectively.  

```
*,
*:before,
*:after {
  box-sizing: border-box;
}
```

**Comment by PrashantAshok** [comment]
Hey @marcysutton , sorry if i am missing something, aren't the [default h tags](https://github.com/angular/material/blob/6af1546da48aa335ca65ff32f09e2d3b69d0a2d9/src/core/style/typography.scss#L80) still too broad? 

````
h1 {
  @extend .md-display-1;
  font-weight: 400;
  margin: $h1-margin-base;
}
````

I am trying to use material in my app, and because of the above defaults, i am being forced to use `!important` in my scss file. 

`
h4 { font-size: 35px !important;
`

**Comment by marcysutton** [comment]
That is good feedback. But if we don't provide defaults, then you'd ALWAYS have to provide a CSS class for headings, which would be a pain. Do you really need `!important` if your font size comes after that definition?

**Comment by PrashantAshok** [comment]
Thanks. Yes I don't need `!important` - didn't realize my files were being loaded before material files.  

[btw, sorry i accidentally deleted my comment, re-posting here again]
aren't the [default h tags] (https://github.com/angular/material/blob/6af1546da48aa335ca65ff32f09e2d3b69d0a2d9/src/core/style/typography.scss#L80) still too broad?

````
h1 {
  @extend .md-display-1;
  font-weight: 400;
  margin: $h1-margin-base;
}
````

**Comment by marcysutton** [comment]
@PrashantAshok wouldn't you already have to override the browser's default font size anyway? I am definitely thinking hard on whether they are in fact too broad, but I want to consider all angles. Libraries like Bootstrap *do* define default font sizes for headings. I think as long as they are easy to override, that is the key.

**Comment by PrashantAshok** [comment]
Yep. Libraries like bootstrap are easy to override, but I am thinking maybe material leaves it to bootstrap/others to define defaults and just has material specific styles?

**Comment by marcysutton** [comment]
Great feedback from @jelbourn:

>If you just want to use the datepicker, you shouldn't have to change the style of your `<h1>` tags, etc.

Based on that and your concerns @PrashantAshok, I'm thinking the base `h` tags should cascade off of a CSS class on the body or other parent element. Would that help?

**Comment by PrashantAshok** [comment]
I think that should work, something like `.md-body {}`?

**Comment by marcysutton** [comment]
`.md-body` is already very similar to one of the style classes based on the Material Design spec, I was thinking `.md-typography` since it is very limited to typographical defaults. But I'm open to other suggestions!

**Comment by marcysutton** [comment]
@PrashantAshok have a look at #2042, it should sort everything out.

**Comment by PrashantAshok** [comment]
Looks great @marcysutton . Thanks.
