### ISSUE TITLE
md-slider not draggable in 0.7.1

### ISSUE THREAD

**Issue by holmesal** [angular/material#1445]
In `0.7.1-master-ef4aff0` (bower) and earlier, the slider works great for me.
In `0.7.1-master-f1a4bcc` onwards (including `0.7.1`), the slider isn't draggable. The "grow" animation on the control occurs, but it's not possible to move the slider around.

Chrome Version 40.0.2214.111 (64-bit) on Ubuntu

**Comment by Luminess** [comment]
Had this issue before when I've minified the already minified js and css. I've fixed this issue by using the css and js straight from the rawgit build.

**Comment by hardywu** [comment]
same here.

**Comment by Luminess** [comment]
If this issue does not appear [here](https://material.angularjs.org/#/demo/material.components.slider), then it's most likely on your end.

**Comment by holmesal** [comment]
Interesting - I'll double-check that I'm not double-minifying.



- alonso

**Comment by gabrielmancini** [comment]
same here in cordova android

**Comment by marcysutton** [comment]
@holmesal can you verify whether this is still an issue?

**Comment by ThomasBurleson** [comment]
Unable to reproduce.

**Comment by sstorie** [comment]
FWIW, I'm sure this is a problem on my end, but it's not clear to me what I've done to create it. I've got a relatively simple app, and I've tried to use md-slider but the handle isn't being displayed on my sliders. The line itself displays with the appropriate fill, and it's binding to my backing model fine, but there's just no handle shown (so dragging doesn't work). Here's a screen capture of what's going on for me when I dump just the "red" slider from the md-slider demo into my app:

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3630784/11187614/bb833bd4-8c4c-11e5-8e8e-1ae7200f3639.gif)

I'm just using the CDN versions of material 1.0.0-rc3, but I'm including several other libraries via webpack. Just wanted to add this incase someone has run into this and discovered a cause other than re-minifying the material libraries.

**Comment by ibsenleo** [comment]
Something similar was happening to me. I was including from CDN jquery 1.12.3.min.js and this library was causing this issue for me. I just remember Angular has its own version of jquery lite or something alike, and this was enough for me. So i remove jquery and the slider works back again!
Hope helps

**Comment by ashish-padakannaya** [comment]
@ibsenleo 's solution worked for me. I was declaring jquery twice.
