### ISSUE TITLE
md-tabs and md-sidenav are incompatible with fastclick

### ISSUE THREAD

**Issue by infomofo** [angular/material#1448]
I tried integrating fastclick into my material-angular application, to deal with the [bug](https://github.com/angular/angular.js/issues/6251) described on the angular issue tracker where ng-click events can fire twice on mobile applications.  However, when I turned fastclick on, I found a few issues with some of the core angular material directives on mobile devices.  For example, tabs stopped responding to touch events (the ink ripples would fire, but they wouldn't switch tabs).  Also, the sidenav would no longer dismiss from a touch event outside the nav.

**Comment by roidayan** [comment]
I got different behavior from described. the sidenav do dismiss here on touch outside but ripple effects are not shown anymore.

**Comment by dantaylor** [comment]
was there any updates on that @roidayan ? I am getting the same behavior. Basically all elements that had ripples no longer show the ripples after fastclick, I wish there was a way to remove the 300ms delay and still preserve the ripple ink effect.  I wonder if the ripple directive is tied to a subsequent click event or bubble that is getting canceled by fast click?
For the time being it seems more valuable to have a snappier ux than it is to have ripples :-/

**Comment by roidayan** [comment]
not really tracking. checking my project i see i still use fastclick. i dont see ripple effect on sidenav click but it's fine. as you said snappier ux is better and I really don't think about the ripples.
