### ISSUE TITLE
$mdDialog documentation is out of date

### ISSUE THREAD

**Issue by depoll** [angular/material#1449]
The documentation for $mdDialog is painfully out of date, suggesting things like the existence of $hideDialog being injected into controllers (removed in 0.4).  Can someone take a pass on the documentation there?

**Comment by ThomasBurleson** [comment]
@depoll - I agree that our documentation needs some extra attention. While @marcysutton has done a superlative job with the latest docs in 0.7.1, we still have more changes. Would you consider providing a markdown document with your ideas/words for the $mdDialog docs?  We will incorporate those into our jsDocs...

**Comment by marcysutton** [comment]
The documentation currently says:

>`controller - {string=}`: The controller to associate with the dialog. The controller will be injected with the local `$hideDialog`, which is a function used to hide the dialog.

Should that say `$mdDialog`?  (You still have to pass it through to the controller as a parameter.)

I'll see if I can find anything else in here that's outdated.
