### ISSUE TITLE
material-checkbox data-binding doesn't work outside

### ISSUE THREAD

**Issue by jackzhu2012** [angular/material#145]
HI, it seems data-binding works only inside <material-checkbox>.  For example, when click on 'cb2', 'cb1' updates correctly.  But once click on 'cb1', not only 'cb2' doesn't response, also the data-binding stop working when click on 'cb2'.  

is there any way to work around this?

```javascript
<material-checkbox>
    <input id="cb1" type="checkbox" ng-model="test">
   test= {{test}}
</material-checkbox>
test= {{test}}
<input id="cb2" type="checkbox" ng-model="test">
```

**Comment by ajoslin** [comment]
This is a scoping problem. See https://egghead.io/lessons/angularjs-the-dot
