### ISSUE TITLE
placeholder doesn't work properly

### ISSUE THREAD

**Issue by gitawego** [angular/material#1451]
with this code
```html
 <md-input-container>
                <label>{{ 'COUNTRIES' | translate }}</label>
                <input ng-model="newUser.countries" placeholder="{{ 'SEPARATE_WITH_COMMAS' | translate }}">
            </md-input-container>
```
it renders like this:
![1](https://cloud.githubusercontent.com/assets/438120/6125786/355e2a40-b11a-11e4-9e57-006187353ee2.jpg)

I've to hard code placeholder to get it work correctly
```html
 <md-input-container>
                <label>{{ 'COUNTRIES' | translate }}</label>
                <input ng-model="newUser.countries" placeholder="separate with commas">
            </md-input-container>
```

**Comment by gustavohenke** [comment]
I think this is a duplicate from #1427

**Comment by marcysutton** [comment]
Yep, this is a duplicate, please use #1427. Thank you!

**Comment by zeeshanjan82** [comment]
Any Idea how to fix this issue, I am also experiencing the same issue with placeholders when using translate filter.
