### ISSUE TITLE
md-ink-ripple - can it trigger click after transition end to ensure animation is completed?

### ISSUE THREAD

**Issue by vertazzar** [angular/material#1453]
I have situation where when you click (ng-click) a button with ripple, a lot of items will begin to render using ng-repeat, which in turn starts consuming some cpu in order to make all computations and append them to the dom.

That is expected, but what I would like to do is prevent ripple from behaving like it is on the provided example. Is there any way that you can accomplish this so that ripple animation ends before the ng-click fires $scope.$apply() and begins taking up the cpu that will "block" the animation sequence.

This happens on chrome Version 40.0.2214.94 (64-bit) mac os x 10.8

http://plnkr.co/edit/tSdIlGEUxYc7u70gRB1h?p=preview

**Comment by vertazzar** [comment]
well it appears that only way is to use `$timeout` service in the ng-click callback, like so
http://plnkr.co/edit/tSdIlGEUxYc7u70gRB1h?p=preview

**Comment by recursionbane** [comment]
I ran into this exact issue today and my solution was also to use a timeout.
It's hacky, especially when you have cascading events (like an md-dialog load triggered after a click with ripple).

I wish there was a global variable that we could query to see if any animations are currently active (i.e., if the application UI is "at rest").
