### ISSUE TITLE
Documentation references $mdThemingProvider.theme()'s primaryPalette, accentPalette, warnPalette, and backgroundPalette, which don't exist

### ISSUE THREAD

**Issue by gtelljohann** [angular/material#1454]
The actual setter methods seem to now be called primaryColor, accentColor, warnColor, and backgroundColor

**Comment by epelc** [comment]
Wasn't everything just renamed to *Palette in 0.7.1

**Comment by jaderabbit** [comment]
Yea, I just changed everything to Palette
