### ISSUE TITLE
feat(autocomplete): add support for floating labels

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#1457]

**Comment by r0b-** [comment]
+1 
Would be cool to have autocomplete look/behave like other inputs to have a consistent style across common form elements.
IMO this should be done before https://github.com/angular/material/issues/1524

**Comment by kylemantesso** [comment]
This seems to be available according to the docs, but as of 0.8.3 it doesn't seem to work out of the box?

**Comment by robertmesserle** [comment]
This is added in master and will be in 0.9.0
