### ISSUE TITLE
Select extra scrollbar

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1462]
`md-select-menu` has `overflow-y: scroll;` which adds an extra scrollbar.
With:
![screen shot 2015-02-10 at 10 57 49 pm](https://cloud.githubusercontent.com/assets/3695164/6141769/4128e9ce-b178-11e4-946e-711a8eb62eeb.png)

Without:
![screen shot 2015-02-10 at 10 57 05 pm](https://cloud.githubusercontent.com/assets/3695164/6141763/28de5f8e-b178-11e4-8ffa-03819f6a7510.png)

You can see it also adds a horizontal scrollbar because there isn't enough space.

**Comment by marcysutton** [comment]
@ilanbiala I'd hold off on creating PRs for this, select is very much still a work-in-progress.

**Comment by ThomasBurleson** [comment]
@ilanbiala - Good catch. We are removing the Select from **master** while we improve the quality and features of that component.

**Comment by ilanbiala** [comment]
Ah okay, I just created a PR because I noticed it got merged in and so I checked the demos to see what it looks like.

**Comment by ThomasBurleson** [comment]
@ilanbiala - your report was great. Thank you. We decided - after some internal talks - to remove it for this week. It should be available next week.
