### ISSUE TITLE
mdTabs pagination arrows have dissapeared

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [angular/material#1464]
Just as the title says, with the latest commit (bbbec18e5a) the ui changed, and actually uses the accent color now, but the pagination arrows have disappeared, which is a very bad thing.

![mdtabs issue](https://cloud.githubusercontent.com/assets/7330103/6141770/418e5eee-b178-11e4-90a3-105f29831b2e.png)

As you can see in the picture, there are no pagination arrows, which on smaller screens, leads the user to think there are only 5 tabs, when in fact there are 10. The buttons are still there, and can be clicked, but there is no icon to indicate that. Occurs on Firefox 35.0.1, Chrome 41 beta, and Chrome Mobile version 40, which makes me think it isn't a browser thing.

**Comment by WhiteAbeLincoln** [comment]
It looks like the issue is that the css rule for `.md-paginator.md-next` and `.md-paginator.md-prev` (line 6067 in angular-material.css) both use a svg background image that is white, so on a white background, it is not visible.

**Comment by ThomasBurleson** [comment]
@WhiteAbeLincoln - We are aware of this and fixing it right now.

**Comment by PaulMougel** [comment]
This is still an issue when using `class="md-primary"` for tabs. The arrows are using the primary color, and become invisible. See for instance this pen: http://codepen.io/PaulMougel/pen/PwRbgQ

**Comment by matheusdavidson** [comment]
This is still an issue, it shows on desktop but now on iphone:
https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpf1/v/t34.0-12/11136952_10203715756749885_1045656023_n.jpg?oh=6ce6ebe4c47c5854109c1d01fdacb14c&oe=5522C1D5&__gda__=1428345284_1f2b355a5c2fdbf0d9d2716975158f19

![seta](https://cloud.githubusercontent.com/assets/2229994/6995531/87d6c208-db24-11e4-80db-3d46f5cf9f47.png)

**Comment by chrisryer** [comment]
md-no-pagination="false"

You're welcome.
