### ISSUE TITLE
mdInput: Option to disable character counter

### ISSUE THREAD

**Issue by mrtaikandi** [angular/material#1467]
When using md-maxlength in a mdInput, a character counter will be shown underneath the input which is really great. But sometimes it is useful to have an option for not displaying it. 
For example in an email box usually users have about 100 to 200 character limit. It is good practice (IMHO) to apply maxlength to that input but it isn't necessary to show the character counter; because the user in most cases will not reach that limit.

**Comment by gkalpak** [comment]
The purpose of `mdMaxlength` is exactly to show that counter. If you don't want the counter and only need "plain" validation, you can use the "simple" `ngMaxlength` or `maxlength`.

**Comment by mrtaikandi** [comment]
Now that you mentioned ngMaxlength it seems that I made a rookie mistake :)
