### ISSUE TITLE
!DOCTYPE breaks column layout flex 

### ISSUE THREAD

**Issue by vlio20** [angular/material#1470]
It seems that !DOCTYPE breaks the functionality of flex="X". 
Here is a plunker with !DOCTYPE: http://plnkr.co/edit/0SrUp25FvT2PAsJDEwF3?p=preview

Here is a plunker without !DOCTYPE: http://plnkr.co/edit/mHwbc3EvB4Gyd3ixdKJl?p=preview

Few things to note: when there is no value provided (flex instead of flex="X") it works fine.

**Comment by marcysutton** [comment]
That sounds like something to do with Plunker, not Angular Material. A doctype is required for HTML files. But in Plunker, there probably already is one on the page. I know on Codepen you are not supposed to include a doctype.

**Comment by vlio20** [comment]
@marcysutton, I am getting the same thing on my local machine, I can upload it to git and share it with you.

**Comment by marcysutton** [comment]
Weird! If you can share more detail outside of Plunker/Codepen that will help narrow down the cause. We use flex in our docs website with a doctype (obviously, it's required) and in other demos and I haven't this problem.

**Comment by vlio20** [comment]
@marcysutton, I have created this repository, which contains a very simple project. It was built with angular yeoman.  
https://github.com/vlio20/flexerror

Try to remove the !doctype from index.js and you will see how every thing works.

**Comment by marcysutton** [comment]
Is there any way you can create a simpler repo? I couldn't get this thing running with `npm install`, `bower install` and `grunt serve` and I have limited time to spend on it.

**Comment by vlio20** [comment]
Yes there is a simple way, download the zipped files (2 files from plunker's example) from this link: 
http://www.filedropper.com/plunk-0srup25fvt2pasjdewf3

Run it on some web server (I did with python: python -m SimpleHTTPServer 8000)

**Comment by vlio20** [comment]
I have also created this simple and cleaner plunker, without routes and comments.
http://plnkr.co/edit/po2IUwFVDTqpWM3Usk5w?p=info

**Comment by marcysutton** [comment]
Ok. This is not due to the doctype (which puts your browser into standards mode). It's because the Angular Material flex attributes have to be used in a specific way. I changed your markup to look more like this Hello World (minus the sidebar) and the issue was resolved: http://codepen.io/marcysutton/pen/OPbpKm

**Comment by vlio20** [comment]
@marcysutton, can you please give a link to the markup you changed for my example?

**Comment by marcysutton** [comment]
Yep, here you go! http://plnkr.co/edit/JYZFyEQ48rW3Fw0oxAak

**Comment by vlio20** [comment]
Thanks @marcysutton , but it looks like it is not working :( 
If you have set flex="33" and flex="66" they suppose to fill the height of the screen (both the input and the button are placed at the top of the screen without any space between them. Here is a screen shot:
![screen shot 2015-02-11 at 11 19 21 pm](https://cloud.githubusercontent.com/assets/4542641/6156654/88ee33e6-b244-11e4-82fc-60a0b20aac9d.png)

Here is how it suppose to look with flex="33" and flex="66":
![screen shot 2015-02-11 at 11 18 30 pm](https://cloud.githubusercontent.com/assets/4542641/6156664/9d4d1d52-b244-11e4-81b4-090a1b97f160.png)


I have looked in devtools to see the height of the first element after the body tag (the one with the ng-app attribute) and it didn't fill its parent so I have set its height to 100%. Here is what I am getting (http://plnkr.co/edit/5ysTBAGrDqkF1jhURipS?p=preview): 
![screen shot 2015-02-11 at 11 21 14 pm](https://cloud.githubusercontent.com/assets/4542641/6156686/cb4e91cc-b244-11e4-80bb-43b938ecb697.png)

Sorry for not letting this go...

**Comment by CreativityKills** [comment]
I am also getting this particular problem! If i remove the doctype, it loads properly, adding it again makes the layout-fill not fill

**Comment by marcysutton** [comment]
For more help with this, please post on the [Angular Material forum](https://groups.google.com/forum/#!forum/ngmaterial). This issue is closed. Thank you!
