### ISSUE TITLE
theme generation: hue-1 styling cannot be applied to md-progress-circular on Safari (tried 7.1.3 with angular-material 0.7.0) 

### ISSUE THREAD

**Issue by tangm** [angular/material#1483]
This caused a fair bit of pain and frustration.

In `Safari 7.1.3 OSX` + `angular-material 0.7.0`, 
`<md-progress-circular md-mode="indeterminate" class="md-primary md-hue-1" md-diameter="24" ></md-progress-circular>` 
does not have the `hue-1` styling applied, only the primary theme. It works fine in Chrome. Surprisingly, `hue-2` styling works.

It turns out that the styles added to the Dom in:
````
  if (!generationIsDone) {
    var style = document.createElement('style');
    style.innerHTML = styleString;
    var head = document.getElementsByTagName('head')[0];
    head.insertBefore(style, head.firstElementChild);
    generationIsDone = true;
  }
````
has 4 occurrences of `}'`, e.g.
```
...
md-toolbar.md-default-theme.md-hue-1 .md-button {    color: rgb(0,0,0);}'}md-bottom-sheet.md-default-theme.md-hue-2.md-list md-item {    color: rgba(0,0,0,0.87);}
```

which correspond to the `hue-1` theme. This only seems to happen on Safari/iOS and not on Chrome. I suspect other directives in Safari will also not be able to use `hue-1`

**Comment by demisx** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
