### ISSUE TITLE
md-input-container: ng-touched added on page load

### ISSUE THREAD

**Issue by epelc** [angular/material#1485]
I think [this](https://github.com/angular/material/commit/e0f53ddda7d080e80c08d5106b5586b697ea8e87) commit has broken the styles for `md-input-container`. It's adding the invalid styles when the page is loaded instead of after the user first touches the input. Also I believe `ng-touched` is not supposed to be added on page load.

**Comment by epelc** [comment]
I should mention this is for inputs with `required` and possible the min/max length attributes.

**Comment by ThomasBurleson** [comment]
@epelc - here is the issue. If the input field is invalid during page load/initialization, the previous solution does not indicate such. As soon as you touch it and defocus it shows the error style. This is a horrible UX: if the value is invalid show the style immediately. Hence the change(s).

**Comment by epelc** [comment]
@ThomasBurleson What about for required fields? It makes your form look terrible if half your inputs are red when they load especially for a sign in page. Also the user has a general idea that most things are required why do we have to scream it to them when they show up? Wouldn't it be better to guide them as they fill out the form instead?

As a side note this is also how most forms already work so it breaks what the user has already learned. Ie google's sign up page only warns you about an invalid input after you have touched it or input something invalid.
https://accounts.google.com/SignUp

**Comment by grabbou** [comment]
@ThomasBurleson I believe it should show the error as soon as you touch it. For now - even simple login form is completely red as "required" & "email" are obviously wrong on first page load. 

Also - on initial page load, my ng-messages are showing ng-message="required" by default.

**Comment by AllenSH12** [comment]
FWIW here's what the Material spec says on the topic:
http://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors

**Comment by grabbou** [comment]
+1 @AllenSH12

**Comment by ThomasBurleson** [comment]
@AllenSH12 - Thank you for the link. I did not realize that Material Design is explicit. Very nice... now I will queue this issues as a definite bug. Thx again.

**Comment by AllenSH12** [comment]
@ThomasBurleson no problem!

**Comment by AllenSH12** [comment]
In the meantime I tweaked the Error demo to demo the behavior more explicitly, PR here: https://github.com/angular/material/pull/1491

**Comment by ThomasBurleson** [comment]
@grabbou - can you provide a CodePen or Plunkr that I can use to verify changes ?

**Comment by grabbou** [comment]
Can do, will update this tomorrow.

**Comment by ThomasBurleson** [comment]
@AllenSH12 , @epelc - can you check with latest in master to confirm that this issue has been resolved ? Thank you.

**Comment by epelc** [comment]
@ThomasBurleson It seems be to fixed on the latest master. But I also think it's odd how it immediately becomes invalid when you touch it(before you type anything). I think a delay or some other sort of logic to wait until after you type something would be better.

I also noticed on google stripe and github they don't even show validation errors on their signin page.

**Comment by ThomasBurleson** [comment]
@epelc - I followed the Material Design spec which states:

> Error text should not appear before user interaction with the field.

For me this means that a click or focus on the element is a "user interaction". Thus the immediate indication that the error condition exists.

**Comment by epelc** [comment]
@ThomasBurleson I think you did it right. It seems correct on every other form I have besides the login page. Perhaps because so many sites don't validate your input on login pages I've been tricked into expecting this.

**Comment by AllenSH12** [comment]
@ThomasBurleson looks good thank you again

**Comment by AllenSH12** [comment]
(sorry accidentally submitted last comment before ready, continuing...)

@ThomasBurleson is there anything I can do to have my PRs merged instead of included indirectly in the future?

**Comment by ThomasBurleson** [comment]
@AllenSH12 - I asked you in your PR if you had signed the CLA. You did not reply. So I copied your changes. I will only merge valid changes from contributors **if** a the required CLA has been signed.

**Comment by AllenSH12** [comment]
@ThomasBurleson that makes sense, thank you for clarifying.

**Comment by fuhlig** [comment]
The error stil exists (as shown below on the demo site). Seems like `.md-input-invalid` is not toggled correctly on `<md-input-container>`
![md-input_error](https://cloud.githubusercontent.com/assets/1364116/6212276/74cd7b90-b5e3-11e4-870b-9cc264caceed.gif)

**Comment by ThomasBurleson** [comment]
@fuhlig - re-opening to fix.

**Comment by grabbou** [comment]
Yep, can confirm that @fuhlig issue appears in mine project as well. Weird, as material demo seems to handle that properly.

**Comment by mbellezi** [comment]
I think this problem is related: If you use the browser memorized values for common fields (Name, city, etc.), the fields are filled with the values but the md-input-container does not update properly. Using a e-mail validated field, for example, you have to type several times for the update int the container takes place. You can test here:

http://codepen.io/mbellezi/pen/ByxdJB

**Comment by ThomasBurleson** [comment]
Fixed, Closed with SHA 747eb9c
