### ISSUE TITLE
md-button: href ripple color

### ISSUE THREAD

**Issue by epelc** [angular/material#1486]
If you have a button with an href the ripple color is red. Shouldn't it default to light grey if you don't add any classes to the button?

```
<md-button href="http://www.google.com/" target="_blank">Google</md-button>
```

**Comment by marcysutton** [comment]
I'm actually seeing the default blue/purple colors for links that get added in place of `<md-button>`. @epelc, are you using a theme?

**Comment by marcysutton** [comment]
Ahh, I am noticing it's the *ripple* color, not the foreground color. It seems related to the default color issue I mentioned above.

**Comment by epelc** [comment]
I tried it in my app which uses a modified green theme and on the docs.

**Comment by marcysutton** [comment]
I don't see red ripples anywhere in the docs, although I did see them on Codepen (which has a default stylesheet). The "Go to Google" link button in Demos > Button inherits a blue text color from our docs.css, which highlights that a default color is missing from the component itself. I am updating `md-button` to use `color: currentColor` in the absence of a theme class. That way it will update based on the body color.

Something to keep in mind is we're adding basic typography support in 0.9.0. So if we want to make changes to this behavior, we can revisit it then. https://github.com/angular/material/issues/1128
