### ISSUE TITLE
md-grid-list not working for me

### ISSUE THREAD

**Issue by calidion** [angular/material#1487]
i copied code from:

https://material.angularjs.org/#/demo/material.components.gridList

but it has no effect.

do you have a codepen example?

**Comment by epelc** [comment]
@calidion Are you importing the latest version of angular-material this component was just released.

**Comment by calidion** [comment]
@epelc 
I am using angular-material#0.7.1, is this version right?

**Comment by epelc** [comment]
@calidion It was released in `0.8.0-rc1`

Also take a look at the changelog it lists everything they update.
https://github.com/angular/material/blob/master/CHANGELOG.md

**Comment by calidion** [comment]
@epelc 
thanks. It's working.

**Comment by epelc** [comment]
@calidion No problem. Would you mind closing this issue?

**Comment by calidion** [comment]
ok.

**Comment by ThomasBurleson** [comment]
md-gridlist with Avatars: http://codepen.io/ThomasBurleson/pen/xbYxrX 
md-Icon with FontAwesome: http://codepen.io/ThomasBurleson/pen/JopjjN

**Comment by epelc** [comment]
@ThomasBurleson Is the responsive demo supposed to just resize the grid tiles or collapse into a more vertical layout?
https://material.angularjs.org/#/demo/material.components.gridList

**Comment by shyndman** [comment]
Funny, I was just looking at the same thing. They should collapse. I'm trying to figure out why right now.

**Comment by calidion** [comment]
it is great to use md-icon inside md-gridlist, especially using md-font-icon with fontawesome;)

**Comment by calidion** [comment]
md-row-height is a bit confusing, hope the document will have more details.

**Comment by shyndman** [comment]
#1488 fixes the responsive issue

**Comment by padmashreebhat** [comment]
md-grid-list
is not working and i was using 0.7.1 . When i changed to 0.8.0 other features like button left nav stopped working. Is there anything that i have missed?

**Comment by ThomasBurleson** [comment]
@padmashreebhat - 
1) You are asking a question on a **closed** issue; plz do not do that.
2) How can the team adequately respond when you have not provided any details, Plunkr, or CodePen.
3) Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
