### ISSUE TITLE
Allow demos to be modified

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1489]
It would be awesome to just modify the demos instead of having to work through CodePen or Plunker and play with the really simple code.

**Comment by ThomasBurleson** [comment]
@ilanbiala - Perhaps you could help us make CodePens corresponding to each of our demos... ?

**Comment by ilanbiala** [comment]
@ThomasBurleson instead of keeping CodePens and docs up-to-date, why not just have the code sample be modify-able or just make the demos use a CodePen. Minimize the amount of work necessary to keep docs up-to-date.

**Comment by marcysutton** [comment]
We do plan to have "runnable examples" like on docs.angularjs.org. I agree that making them dynamic somehow will help keep things up to date. But planning & implementing that is not an easy task.

**Comment by ilanbiala** [comment]
@marcysutton if you guys want, I can work on a PR for that.

**Comment by marcysutton** [comment]
By all means, go ahead and work on a PR for the demos. Please just keep the docs information architecture/navigation structure intact.

**Comment by gkalpak** [comment]
BTW, the runnable examples in docs.angularjs.org (that @marcysutton mentioned above) are creating a new plunkr on the fly (when you click the "Edit in plunkr" button).
If anyone is interested in taking a look at how this is accomplished, the relevant code is [here][1].
(Not sure if CodePen supports something similar.)

[1]: https://github.com/angular/angular.js/blob/master/docs/app/src/examples.js

**Comment by marcysutton** [comment]
We chose Codepen primarily because it's more accessible. Looks like you can prefill using their API: http://blog.codepen.io/documentation/api/prefill/

**Comment by gkalpak** [comment]
All good then :)
:+1: on using CodePen (I don't know about accessiblity, but it has the most mobile-friendly design) !

**Comment by marcysutton** [comment]
@ilanbiala are you still working on a PR for this?

**Comment by ilanbiala** [comment]
@marcysutton I actually have an instant HTML + CSS + JS editor already on another site that I can port into a PR that renders the results. Is that something you guys are interested in?

**Comment by marcysutton** [comment]
The request is for automated Codepen demos so that they can be easily forked. Similar to how docs.angularjs.org will allow you to create a Plunker right from the docs, except Codepen has better accessibility and platform features.

**Comment by matthewrfindley** [comment]
Examples on the documentation site are now editable via codepen.  As of 5c37dc8c54ddd0e6ca3bd138665c4997c8189b52, users will be able to click the 'Edit on Codepen' button to create a copy of the example on Codepen.

**Comment by marcysutton** [comment]
YAY! Hi-five!
