### ISSUE TITLE
Input size attribute isn't supported

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1490]
It seems that the input size attribute isn't supported. Ordinarily I would just work with the flex attribute, but it's easier to size the input based on the number of characters rather than the percentage width.

**Comment by marcysutton** [comment]
Can't you put native attributes on the `<input>` inside of `<md-input-group>`? Is CSS getting in the way? A Codepen or Plunker would help us take a closer look at this issue. Thanks.

**Comment by epelc** [comment]
I also noticed this today when I started using stripe. `size` currently appears to not affect inputs in any way.

**Comment by ilanbiala** [comment]
@marcysutton take a look at this Pen: http://codepen.io/ilanbiala/pen/dPdXpd. I'm using it inside an `md-list`, but I would think the styles should still apply especially when it's a browser feature and not an ngMaterial one.

**Comment by ilanbiala** [comment]
@marcysutton I updated the Pen with another input inside only the form and still it isn't size 4.

**Comment by marcysutton** [comment]
I see what you're talking about, but widths are handled by the flex layout system. There is a fundamental conflict between supporting widths as native attributes and providing a layout system in CSS. Bootstrap inputs don't respond to this attribute either. Recommending you use CSS and validate input lengths with JS instead.
