### ISSUE TITLE
including dependency 'hammer.js' in the CDN instructions

### ISSUE THREAD

**Issue by davidtmnolan** [angular/material#1492]
Curious as to why you did not include hammer.js in the CDN section of using material as it is a dependency.

Using angular-material 0.7.0.

**Comment by rschmukler** [comment]
I presume you mean angular-material 0.7.0, otherwise, please upgrade your angular ;)

Hammer was removed in 0.7.1. It's no longer a dependency.

**Comment by davidtmnolan** [comment]
Yes, i meant angular-material.  But the CDN instructions say to use 0.7.0, so shouldn't that be updated to say 0.7.1?
