### ISSUE TITLE
ng-if delayed for button hiding

### ISSUE THREAD

**Issue by maddogawl** [angular/material#1496]
<md-button ng-if="!player.editing" class="md-raised md-primary" data-ng-click="EditPlayer($index)">Quick Edit</md-button>
          <md-button ng-if="player.editing" class="md-raised md-primary" data-ng-click="SavePlayer($index)">Save</md-button>

I have those two lines, without using md-button it switches perfectly, but once I switch over there is a brief period where both buttons show.  This could be related to the css animation upon clicking since I switch that flag (player.editing) upon ng-click firing.  It seems to take about a second or so before it removes the one that should be invisible.

Maybe there is a better way to do this, but I still feel like this is possibly a bug?

**Comment by epelc** [comment]
Ppossibly a duplicate of #936

**Comment by maddogawl** [comment]
Definitely a duplicate of that issue, sorry I missed that!

**Comment by epelc** [comment]
@maddogawl Can you please close this. 9aedd74 has fixed #936

**Comment by maddogawl** [comment]
Thank you!

**Comment by dwilt** [comment]
@maddogawl Just want to say thanks for well described bug as I'm having this exact issue (but not an `md-button` but a regular old `button` element) and came across this issue in Google. <3
