### ISSUE TITLE
mdThemingProvider

### ISSUE THREAD

**Issue by amedeomar** [angular/material#1497]
Hi I need to know if it is possibile to change the default theme after the app.config phase.

I discover the customer ui customization after a call to the server in the app.run

thank you

P.S.
If i could change default theme in css it would be great too

**Comment by epelc** [comment]
@amedeomar For now to get around this you can add `md-theme="{{userTheme}}"` to your `body` so it can be updated after you load the users theme.

**Comment by ThomasBurleson** [comment]
@amedeomar - this also means that you must use the $mdThemingProvider to register/configure your custom theme(s).

*  [Custom Themes](https://material.angularjs.org/#/Theming/03_configuring_a_theme)
*  [Configure Themes](https://material.angularjs.org/#/Theming/04_multiple_themes)

**Comment by amedeomar** [comment]
Thomas the problem is that i know the theme to configure after a server call made in app.run.

**Comment by ThomasBurleson** [comment]
@amedeomar - This appears to be a special use case and hence a low-priority. I will reopen for the Backlog.
