### ISSUE TITLE
Ng-class does not work on md-grid-tile

### ISSUE THREAD

**Issue by JohnAReid** [angular/material#1498]
I am attempting to change the background color on a tile by using ng-class but it only works if the tile is not already assigned a class. The following example shows the issue: http://codepen.io/anon/pen/KwQggm
the first two tiles uses ng-class to set the background color to gray - but the first title remains red due to class="red" being used. The second tile has the gray background because no class is set before hand.

**Comment by shyndman** [comment]
This is a CSS specificity issue. `.gray` won't override `.red` because it appears earlier in the CSS file.

Here's your example, with `.gray` moved after `.red`: 
http://codepen.io/anon/pen/wBydKP

**Comment by shyndman** [comment]
Here's some information on specificity if you'd like to learn more: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

Mind closing the issue?

**Comment by JohnAReid** [comment]
@shyndman Many thanks.
