### ISSUE TITLE
input validation

### ISSUE THREAD

**Issue by fant0m** [angular/material#1499]
Hello,
current input form validation is just weird. When an input is required and an user loads a page, this input is already red(showing error), but the user hasen't typped anything yet. Isn't it weird?

Edit: CSS should be changed with ng-dirty like this:
// input border-color
md-input-container.md-default-theme.md-input-invalid .md-input .ng-dirty {
    border-color: rgb(244,67,54);
}
// but don't know how to style label, because label doesn't have ng-dirty,ng-pristine classes

I think this is very important because current input is not usable for validation.

**Comment by lboekhorst** [comment]
I agree, I believe this did not use to be the case in the previous version. Is it possible to have the old behaviour back?

**Comment by ThomasBurleson** [comment]
Duplicate
