### ISSUE TITLE
$mdToast enter animation ignored in app.run

### ISSUE THREAD

**Issue by amitport** [angular/material#1502]
this doesn't use enter animation:
```js
app.run(function($mdToast) {
  $mdToast.showSimple('Welcome back!');
});
```

while this does:
```js
app.run(function($timeout, $mdToast) {
  $timeout(function() {
    $mdToast.showSimple('Welcome back!');
  });
});
```

**Comment by rschmukler** [comment]
Investigating this. Might be an issue with angular-core.

**Comment by rschmukler** [comment]
After checking with the angular team, this is indeed intended. Animations are disabled on bootstrap as the default behavior by `ngAnimate`. Closing.
