### ISSUE TITLE
md-icon inside FAB is offset from the center

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#1504]
If using the new `<md-icon>` directive inside of a FAB, the icon will appear offset from the center:

![image](https://cloud.githubusercontent.com/assets/826553/6194026/808e2bb6-b3a7-11e4-9802-265179b653b3.png)

Demo plunkr:
http://plnkr.co/edit/pSz90Fs1T8VxUnYNF5nq?p=preview

I noted however that if we remove `line-height` [here](https://github.com/angular/material/blob/c19cd433eb75fb3b6a9507f8eb36e6e9916f50d3/src/components/button/button.scss#L111), the problem does not occur.

**Comment by ThomasBurleson** [comment]
@gustavohenke - The line-height was an artifact of the previous versions of including SVGs. Now with **md-icon**, we should resolve this.
