### ISSUE TITLE
md-tabs: Scrollbar after making window small

### ISSUE THREAD

**Issue by epelc** [angular/material#1506]
If you load the page with a wide window then resize it down to a small window the tabs are showing a scroll bar.

![image](https://cloud.githubusercontent.com/assets/5204642/6195117/f24eed58-b398-11e4-8976-b80fa550d618.png)

Tested on the docs demo and in my app with `0.8.0-rc1`
https://material.angularjs.org/#/demo/material.components.tabs

**Comment by katiepeters** [comment]
It might be a negative right margin on the arrow button. Try checking for that, and if that's the case, override it in your CSS.

**Comment by zamamohammed** [comment]
Same stuff but in video format :)

http://screencast.com/t/GOg5v1mTg

**Comment by RickBlom** [comment]
It seems not happening when the last Tab is selected. All other Tabs gave above behavior..
