### ISSUE TITLE
md-grid-tile mixed usage (ng-repeat and html)

### ISSUE THREAD

**Issue by davyde** [angular/material#1510]
having issues with mixed ng-repeat and explicitly defined ng-grid-tiles in the same list.

the ng-repeat seems to zonk the col/row-spans of the subsequent tiles. 

has anyone encountered this?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
