### ISSUE TITLE
md-icon md-svg-src should generate viewbox based on height and width if missing

### ISSUE THREAD

**Issue by marshfire** [angular/material#1512]
With the rewrite of md-icon in 0.8.0 rc1 a viewbox of 0 0 24 24 is hardcoded as a default if there is no viewbox in the svg. This leads to wrong icon presentations. It would be better to base the missing viewbox on the width and height of the svg, so for a 64 x 64 icon it should be 0 0 64 64.

**Comment by ThomasBurleson** [comment]
You can easily configure the sizes:

```js
app.config(function($mdIconProvider) {
    $mdIconProvider
      .icon("homepage", "img/icons/custom/homepage.svg", 64)
      .iconSet('social', 'img/icons/sets/social-icons.svg', 24)
      .defaultIconSet('img/icons/sets/core-icons.svg', 24);
});
```
```html
 <md-icon md-svg-icon="alarm"         style="color: #0F0;" alt="Alarm Icon"></md-icon>
<md-icon md-svg-icon="social:cake"   style="color: #f00;" alt="Cake Icon"></md-icon>
<md-icon md-svg-icon="social:people" style="color: #00F;" alt="People Icon"></md-icon>
```

See the [Icon Demos](https://material.angularjs.org/#/demo/material.components.icon).

**Comment by gmadajczak** [comment]
Setting up icon size in $mdIconProvider does not have an effect. Icon always is the same size, but the view-box data is correct.

**Comment by ThomasBurleson** [comment]
@gmadajczak - Thank you for the correction. 

Our demo [Load SVGs from URL](https://material.angularjs.org/#/demo/material.components.icon) shows how the viewBox is configured and **then** the height/width are set on the `md-icon`. (Notice that the SVG itself has a `height = width = 100%`)  

![screen shot 2015-02-15 at 6 46 19 am](https://cloud.githubusercontent.com/assets/210413/6203272/622146ee-b4de-11e4-8ba5-1846a97d030e.png)

To adjust the size of the icon to a size different than that specified in the viewBox, developers must set explicit alternate `width` and `height` styles on the **md-icon**.

```html
<md-icon md-svg-src="img/icons/addShoppingCart.svg">
   <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" height="100%" width="100%" />
</md-icon>
```

Now if you change the viewBox size, the result is opposite of the desired effect. eg. 

```html
<svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 64 64" fit="" height="100%" width="100%" />
```

![svgbadsizing](https://cloud.githubusercontent.com/assets/210413/6203270/3c9e54e8-b4de-11e4-80a0-7d81bcae00df.png)

**Comment by marshfire** [comment]
The problem that I had was with a SVG file that I generated with Inkscape.
Inkscape does not automatically write the viewbox into the svg file, only
width and heigth.

Since I designed the page to have 32px width and height and the viewbox is
not written into the SVG,  the hard coded 0 0 24 24 viewbox was added to it
leading to the effect that only a part of the icon was visible.

Check
https://github.com/marshfire/BudgetMonitor/blob/159df20578f737a6e21f74f1a1c462af773fb051/client/assets/images/login.svg
for  that or
https://github.com/marshfire/BudgetMonitor/blob/159df20578f737a6e21f74f1a1c462af773fb051/client/assets/images/gas.svg
for a file that was designed to be 128x128, no containing a viewbox.

As a workaround I added a viewbox with the xml editor of inkscape, however,
it would be more convenient for most to have it autocreated to 100% if
missing.

I did not use the icon-provider, only the url for loading, since this is
what the demo suggested.

Cheers,
Ronny

**Comment by nantunes** [comment]
I have exactly the same problem that @marshfire (algo using inkscape).

For course I can simply add the viewbox to the svg file, but the "0 0 24 24" seems arbitrary. Why not simply omit the atribute? Wouldn't that be the expected behavior?

**Comment by omouse** [comment]
Not sure what the workaround is, but this is still an issue. I have an SVG icon set and every single time I load one of the icons, it appears cut-off because of the default viewbox that is inserted (`viewBox="0 0 24 24"). As soon as I remove that attribute, which seems to be added by md-icon to the inserted `svg` element, the icon appears correctly.

It seems there's a way to override the viewBox that is set through the icon service: https://github.com/angular/material/blob/e06284aa4745dd7323a872a0a9290fd026747e30/src/components/icon/js/iconService.js#L120
