### ISSUE TITLE
mdIcon doesn't support using ttf/woff/eot font-faces

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1517]
mdIcon doesn't seem to support using other font-faces, which is an issue in Chrome because svg font-face support has been deprecated.

**Comment by gustavohenke** [comment]
All that `<md-icon>` does is place an element inside it.
In the case of `<md-icon md-font-icon="icon-foo">`, it's just `<span class="md-font-icon icon-foo">`, so yes, it's supported.

**Comment by ilanbiala** [comment]
It seems that iconSets only support SVG though. What's the point of that?
