### ISSUE TITLE
md-tabs are colorless

### ISSUE THREAD

**Issue by jamm** [angular/material#1519]
Background is white despite of theme color.
Reproduced in docs:
![screenshot 2015-02-15 05 44 31](https://cloud.githubusercontent.com/assets/526352/6201897/c6e99756-b4d5-11e4-993e-ea4d07438f2a.png)

**Comment by PaulMougel** [comment]
Looks like it's intentional, see 732cbc9c3abc1b001e0c425272ab49aa4f4e2d44

**Comment by jamm** [comment]
I glad I can use old versions of ng-material. Transparent themes are too ugly to be acceptable.
Thanks for clarification, @PaulMougel.

**Comment by PaulMougel** [comment]
Unfortunately for you, that comes right from [the spec](http://www.google.com/design/spec/components/tabs.html#tabs-usage):

![](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7Y2phU2tETzJPcEk/components_tabs_usage_mobile4.png)

Also, just add `class="md-primary"` or `class="md-accent"` as shown in [the demo](https://material.angularjs.org/#/demo/material.components.tabs) to have the colors back.

**Comment by jamm** [comment]
Thanks, @PaulMougel . Yes, reminds old Google design with 0 design :)

**Comment by jamm** [comment]
@PaulMougel actually this picture is from specs too:
![screenshot 2015-02-15 23 29 14](https://cloud.githubusercontent.com/assets/526352/6204871/8c7683a0-b56a-11e4-8ffa-d3a3cbe2d8a8.png)
And almost in all examples tabs have background color of main theme. So.. Now I not only think it's ugly decision, but it's also against specs.

**Comment by robertmesserle** [comment]
This is for a few reasons:
1. The spec typically shows the tabs inheriting the background color of their container (ie. transparent).
2. The color-configuration follows the conventions used for `md-button` elements
3. It's typically easier to adopt an opt-in convention over an opt-out - default is transparent, `md-primary` is used for a specific background color.
