### ISSUE TITLE
Mobile toolbar height

### ISSUE THREAD

**Issue by meetshawn** [angular/material#1520]
Why is the default toolbar height always 64 pixels? Isn't it supposed to be 56dp on mobile? If you compare the height of the toolbar to other material apps (Play Store, Play Music, Inbox, Gmail) it's obvious the angular material toolbar is taller.

https://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing

**Comment by marcysutton** [comment]
The spec actually differentiates toolbars from App bars. There are no Metrics listed for the generic toolbar, only the App bar. So we'll have to use those for all toolbars, I assume. Also, in responsive designs, where does the "mobile" breakpoint actually start? cc @ThomasBurleson

**Comment by meetshawn** [comment]
Just eyeballing it, it seems like toolbar and app bar do have the same metrics. 56dp on mobile, 64dp everywhere else. As for mobile vs other not sure if this is up to date: http://developer.android.com/design/style/metrics-grids.html
