### ISSUE TITLE
md-content background

### ISSUE THREAD

**Issue by mprokopowicz** [angular/material#1522]
I've got question about md-content. 

Documention says only about scrollable content, so I'm using it inside layout elements to make content of layout segment scrollable.

F.e. take something like the details view in google drive (Right panel).
When I'm using md-content to achive simillar effect I have white background (Using default theme).

What are the design principles of md-content?

Also how should I design/structure app part like details view in google drive (Use layout elements or sidenav?)

**Comment by marcysutton** [comment]
@mprokopowicz these are more of general questions than bugs or feature requests, so I think they would be better discussed in the [ngmaterial forum](https://groups.google.com/forum/#!forum/ngmaterial). 

That said, the Material Design spec is the best place to look for general layout and design principles. I don't think `md-content` maps to anything specific, but the Structure section might be a good place to start: http://www.google.com/design/spec/layout/structure.html
