### ISSUE TITLE
Autocomplete not updated after selection is made

### ISSUE THREAD

**Issue by kyleledbetter** [angular/material#1523]
The input doesn't seem to be updating when you make a selection from the dropdown:
![autocomplete-select-bug](https://cloud.githubusercontent.com/assets/867883/6205363/0d14ab66-b531-11e4-939d-2abb4a92f60b.gif)

tested Chrome 40.0.2214.111 & Safari 8.0.3 (10600.3.18)

**Comment by rrharvey** [comment]
This looks like a duplicate of [#1513](https://github.com/angular/material/issues/1513).

**Comment by kyleledbetter** [comment]
yup, sorry i missed that open issue, closing dup. Thx @rrharvey
