### ISSUE TITLE
$mdDialog passing the current $scope as option

### ISSUE THREAD

**Issue by mohammedpascal** [angular/material#1531]
There is no option to pass the current scope to dialog, in some cases there is no need to create controller for a dialog.

I would like to do something like this:

$mdDialog.show({
      scope: $scope, //this $scope will be the scope of the enclosing controller
      templateUrl: 'dialog1.tmpl.html',
      targetEvent: ev,
    })

**Comment by PaulMougel** [comment]
Would #1413 do what you want?

**Comment by mohammedpascal** [comment]
Unfortunately no, checkout my code:

```javascript
angular.module('xnotApp')
 .controller('MainCtrl', function ($scope, $mdDialog) {
 	$scope.showAdvanced = function(ev) {
 		$mdDialog.show({
 			controller: function($scope, theScope){
 				$scope.theScope = theScope;
 			},
 			templateUrl: 'views/dialog.html',
 			targetEvent: ev,
 			locals: {
		            theScope: $scope
		        }
 		})
 		.then(function(answer) {
 			$scope.alert = 'You said the information was "' + answer + '".';
 		}, function() {
 			$scope.alert = 'You cancelled the dialog.';
 		});
 	};

 	$scope.answer = function(answer) {
 		$scope.alert('nice');
		//$mdDialog.hide(answer);
	};
 });
```
All I want is to access MainCtrl $scope from the dialog template and I don't want to create controller just for the dialog

**Comment by PaulMougel** [comment]
I see what you mean. That feature would be similar to the `scope` option of [UI-Bootrstrap's modal](http://angular-ui.github.io/bootstrap/#/modal).

**Comment by gkalpak** [comment]
#### Option 1:
I seems like you can specify a `scope` property, passing in the scope to be used, but this option is not documented, so it might break in the future (e.g. if it is not intended as a public API).
<sub>(Although not necessary, if you chose to use Scope inheritance to access the parent scope's properties, make sure you understand [how prototypal inheritance affects Scopes][4].)</sub>

E.g.:

```js
$mdDialog.show({
  targetEvent: evt,
  scope: $scope.$new(),   // Uses prototypal inheritance to gain access to parent scope
  template: '<md-dialog>...{{ someValue }}...</md-dialog>'
});
```
[Demo fiddle 1][1]

---
#### Option 2:
A more verbose (but certainly supported) approach is to use `controller` along with `controllerAs`, `bindToController` and `locals` (in order to automatically bind the necessary values to the controller instance).
Since you don't need any logic for the controller, you can use an empty function (e.g. `angular.noop`).

E.g.:

```js
$mdDialog.show({
  targetEvent: evt,
  locals: {parent: $scope},
  controller: angular.noop,
  controllerAs: 'ctrl',
  bindToController: true,
  template: '<md-dialog>...{{ ctrl.parent.someValue }}...</md-dialog>' +
```
[Demo fiddle 2][2]

---
#### Option 3:
If you want to avoid the `locals` + `bindToController` boilerplate, you can create a minimal controller function that has access to `$scope`.

E.g.:

```js
$mdDialog.show({
  targetEvent: evt,
  controller: function () { this.parent = $scope; },
  controllerAs: 'ctrl',
  template: '<md-dialog>...{{ ctrl.parent.someValue }}...</md-dialog>' +
```
[Demo fiddle 3][3]

[1]: http://jsfiddle.net/ExpertSystem/0ky16g6g/3/
[2]: http://jsfiddle.net/ExpertSystem/0ky16g6g/4/
[3]: http://jsfiddle.net/ExpertSystem/0ky16g6g/5/
[4]: https://github.com/angular/angular.js/wiki/Understanding-Scopes

**Comment by rschmukler** [comment]
The docs should specify the `scope` option. That is an officially supported way. You just pass it into the `show` object. As @gkalpak mentioned, there are also other (supported) ways to achieve what you want. Fantastic answer from @gkalpak. Either way, I'll update the docs.

**Comment by gkalpak** [comment]
@rschmukler, while you are at it (updating the docs), it is probably a good idea to explicitly mention that the scope will be destroyed upon hiding the dialog (so people shouldn't pass a controller's `$scope` directly).

**Comment by mohammedpascal** [comment]
Thanks @gkalpak for the options!
@rschmukler I think the good idea is not to destroy the $scope if you get it as parameter.

@PaulMougel thanks! this is exactly where the need came from, I wanted to migrate my app from ui-bootstrap to angular-material.

**Comment by gkalpak** [comment]
Besides the overhead of keeping track of whether a scope was supplied by the user or created by MD, not destroying the scope can easily lead to memory leaks and performance degradation.
IMO, automatically destorying the scope is safer.

Most importantly, either approach should be clearly documented so the user knows what they need to do.

**Comment by aeroxy** [comment]
@mohammedpascal agreed. Currently while using `scope: $scope` will destroy the $scope of parent controller. This makes the dynamic dialog only usable once.

**Comment by aeroxy** [comment]
@gkalpak you are the man.

**Comment by mattiLeBlanc** [comment]
When I use `scope: this` in my event handler, it seems to merge the scope of the controller and the scope within the event handler.
```
DialogController = ($scope, $mdDialog) ->
      console.log($scope)
      $scope.hide = ->
        $mdDialog.hide()
        return

      $scope.cancel = ->
        $mdDialog.cancel()
        return

      $scope.answer = (answer) ->
        $mdDialog.hide answer
        return
      return
    
 $scope.addToPlayList = ( event ) ->
     event.stopPropagation()
     $mdDialog.show(
        controller: DialogController
        templateUrl: 'client/modules/dialogs/addToPlaylist/addToPlaylist.html'
        parent: angular.element(document.body)
        scope: this         targetEvent: event
        clickOutsideToClose:true
      )
```

Is this acceptable? If I do `scope:this.$new()` the scope of the event handler is accessible in the $parent attribute, but if I leave $new out, it merges both scopes.
I have my episode info that I have within the addToPlayList scope (this) and I have the functions defined in the controller.
Works for me, as long as I am not doing something illegal?

**Comment by idoo** [comment]
@madhur i have same problem. When i use `templateUrl` — it's not work

**Comment by madhur** [comment]
@idoo not sure why you tagged me

**Comment by idoo** [comment]
@madhur Sorry, it's my mistake

**Comment by mattiLeBlanc** [comment]
@idoo  It works fine for me with templateUrl.

**Comment by guillenz100** [comment]
thanks @gkalpak, option 2 works for me !

**Comment by shirazSalpo** [comment]
![1 jpg](https://cloud.githubusercontent.com/assets/24871819/25703721/62fd503c-30f4-11e7-975a-6396bdee9270.jpg)

**Comment by NilsAtGoogle** [comment]
The source code seems to indicate that a supplied scope is ignored

From https://github.com/angular/material/blob/a169f6fa2ffb71db252e4d022cdb83b483742aa2/src/components/panel/panel.js

`  this._config = angular.extend({
    // If no ID is set within the passed-in config, then create an arbitrary ID.
    id: config.id || 'panel_' + this._$mdUtil.nextUid(),
    scope: this._$rootScope.$new(true),
    attachTo: this._$rootElement
  }, this._defaultConfigOptions, config, preset);
`

**Comment by parvindersingh42** [comment]
how to define $scope in factory in case of when we access the method from the factory
