### ISSUE TITLE
Web Starter Kit for Angular Dart - Material style

### ISSUE THREAD

**Issue by MikeMitterer** [angular/material#1532]
Hi Guys, I just want you to inform that I've finished my basic version of WSK for Angular-Dart Material style.
Sample: http://wsk.angular.mikemitterer.at/
Source: https://github.com/MikeMitterer/dart-wsk-angular

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
