### ISSUE TITLE
Polymer core-pages

### ISSUE THREAD

**Issue by OliverTr54** [angular/material#1533]
Hello @ all,

Does the angular material also offer this possibility?
https://www.polymer-project.org/docs/elements/core-elements.html#core-pages

Or how would you suggest to implement for example an email inbox for mobile devices?

First you click the imap folder - following page would be the subject - click on subject would bring you to the email content. All subpages with back links... so that you could switch easily, how they do it currently for the Iphone for example.

And secondly: Is there an implementation of the "cover" style (panel), watch this: https://www.polymer-project.org/docs/elements/core-elements.html#core-header-panel

-> "cover: The panel covers the whole core-header-panel including the header. This allows user to style the panel in such a way that the panel is partially covering the header."

Thanks,
Oliver

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
