### ISSUE TITLE
.md-input-invalid not set when form loads

### ISSUE THREAD

**Issue by demisx** [angular/material#1537]
I've noticed that in the current build `v0.8.0-rc1-master-f704dda` the `.md-input-invalid` class is no longer set on the `<md-input-container>` until the field is focused on. Before, it would be set when the form loads. Not sure if it is a bug or not, but I would like to have `.md-input-invalid` to be set upon load again, so all required fields are red upon load and not until I interact with them. What's the right way to do this now?

**Comment by ThomasBurleson** [comment]
@demisx - This is a duplicate issue. A precheck before new-issue submission will help us better manage issue submissions and the queue.

**Comment by demisx** [comment]
@ThomasBurleson I aways do, but I didn't see a duplicate issue for this. Perhaps I've missed it. Can you reference it please?

**Comment by ThomasBurleson** [comment]
https://github.com/angular/material/issues/1485
