### ISSUE TITLE
Input labels on direction right to left

### ISSUE THREAD

**Issue by stavpardo** [angular/material#1538]
Hi,

I got an issue, if I change the direction of the body to rtl the inputs doesn't behave well...
When I click on the input the label gets smaller and moves left and you would expect it to move right (only on direction: rtl of course).
I hope someone can fix it, thanks!

**Comment by ThomasBurleson** [comment]
@stavpardo - please see these [Duplicates](https://github.com/angular/material/issues?q=is%3Aissue+is%3Aopen+rtl)
