### ISSUE TITLE
Using custom DOM events with angular-material

### ISSUE THREAD

**Issue by mprokopowicz** [angular/material#1539]
After updating to 0.8 (From 0.7 with hammerjs) my custom implementation of drag'n'drop stopped working.

I'm binding mousedown on different elements to make them draggable.
If such element contains f.e. md-slider, the slider didn't work.

It was not the case while using older angular-material with hammerjs.

Where can I read more about assumptions of the new gesture service?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
