### ISSUE TITLE
The error animation in an input text is not triggered

### ISSUE THREAD

**Issue by mvidailhet** [angular/material#1541]
In the doc, the error text slides down when an error is triggered. When using the latests version, this animation does not work. Here is a codepen showing the problem: http://codepen.io/mvidailhet/details/ByYgaO/

Actually The error message does not even disappear.

**Comment by alexhidalgo** [comment]
+1

**Comment by mckenzielong** [comment]
Based on that codepen, it looks like you're missing a reference to angular-messages, and haven't set up a dependency for it.  

Here is a working codepen based on your codepen: http://codepen.io/anon/pen/YPaybJ.  

Note the inclusion of angular-messages.min.js and the dependency set in angular.module.

**Comment by mvidailhet** [comment]
@mckenzielong Thanks a lot ! I was using an old tutorial where ng-messages was in angular I guess. It works now !
There is still the problem of the error message shown at page load, but it's referenced by this issue : #1485

I'm closing the issue then.
