### ISSUE TITLE
$mdDialog behaves incorrectly in IE 11

### ISSUE THREAD

**Issue by amedeomar** [angular/material#1547]
As you can see in the attached image there is no vertical scrollbar and even the subheader is not visible

![image](https://cloud.githubusercontent.com/assets/10732836/6232592/52adaec8-b6cd-11e4-8c05-a9667fdd94ca.png)

**Comment by adrianandreias** [comment]
Duplicate: #1415

**Comment by marcysutton** [comment]
Fixed with 0b0ed2339e1ec32e34d20daa18cadd4ef89d5f86.

**Comment by lexyfeito** [comment]
@marcysutton  So, i am having the issue where the md-dialog-container is being set to 1px, i did some digging and on this line `var scrollTop = body ? body.scrollTop + body.parentElement.scrollTop : 0;` where is getting the scrollTop, the `body.parentElement.scrollTop` is retunring 1,  which is causing my problem. Any idea why this could be happening? Thank you.

**Comment by DevVersion** [comment]
@lexyfeito We recently changed that `scrollTop` function, can you retry within `master`?

**Comment by lexyfeito** [comment]
ok @marcysutton i will try it and let you know thank you.

**Comment by lexyfeito** [comment]
Hey @DevVersion it seems to be working fine now, thank you.

**Comment by DevVersion** [comment]
@lexyfeito Cool, glad to hear that!
