### ISSUE TITLE
theme: support theming text elements

### ISSUE THREAD

**Issue by ngraef** [angular/material#1551]
Add theme support to `span` element to allow for theme-colored text. I would be happy with just css support for `span.md-primary`, but a full implementation would support the `md-theme` directive, `md-primary`, `md-accent`, `md-warn`, and `md-hue-*` classes, and potentially other text elements.

Example use case: themed headers
``` html
<h2><span class="md-primary">Section Title</span></h2>
```

**Comment by erslater** [comment]
+1

I am finding I want to use the theme colors in many more places other than within the components.

**Comment by ngraef** [comment]
This would be addressed by the work being done for #1269, yes?

**Comment by erslater** [comment]
Yes, I think you are correct and this issue can be closed.  Unfortunately, I wasted a little time starting to duplicate that work that was already completed.  At least now I can stop.
