### ISSUE TITLE
md-bottom-sheet enhancement suggestions

### ISSUE THREAD

**Issue by YossiH** [angular/material#1553]
1. Add an md-top-sheet. Use cases for a top/down slideout are not uncommon, in my experience, for widgets, user utilities, etc. Perhaps it can be called md-slider-sheet, or md-slideout, and top/bottom can be an attribute. As I write this, it occurred to me that left and right can also be relevant.

2. A pin-it feature, there are use cases wherein a user infrequently uses some widget, service, or tool, but whenever they do, it is for an extended period of time, think of a timer/stop-watch, etc. A pin-it feature (either visually, or via API), would reduce customization time.

**Comment by YossiH** [comment]
Just gave this some more thought, right, and left can get accomplished with side nav.

**Comment by ThomasBurleson** [comment]
These features are not defined as part of Material Design. 
BottomSheets are transient so a pin-it feature would obviate that feature.

**Comment by filip-tegetdot** [comment]
Maybe clickOutsideToClose?

**Comment by nikfrank** [comment]
how about a top-sheet for when I have a text input hence keyboard popup?
