### ISSUE TITLE
Pagination Buttons submit form

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [angular/material#1555]
I have a long form split over multiple tabs. The issue is when the pagination arrows are pressed, the form is submitted with incomplete data. I know it is related to #1536, but if these buttons are going to be part of the ui, they should have a default type of button so they don't interact with forms and cause unexpected behavior.

**Comment by epelc** [comment]
Add `type="button"` if you don't want them to submit a form.

**Comment by vivekimsit** [comment]
I have sent a PR: #1554 that will fix this issue.

**Comment by rschmukler** [comment]
This is "standard" behavior for browsers. As such, it doesn't make sense for our framework to deviate from what standards are in place.

**Comment by vivekimsit** [comment]
Agree, but we are already adding a layer over existing standards. I assume we will see more issues like these in future because user now expects much to be done magically :wink:
