### ISSUE TITLE
mdGridList does not reflow when filtering with animations

### ISSUE THREAD

**Issue by jonnysamps** [angular/material#1559]
mdGridList works just fine with a combination of ng-repeat and a text filter.  Everything reflows just fine. When you add an animation to the tile then the animations occur but the elements in the grid list don't reflow as they do without the animation.

I tried to create an example with Plunkr but the 0.8.0-rc1 release is not available in the CDN.

# Markup
```
<md-grid-list md-gutter="1em" md-row-height="120px" md-cols="3">
        <md-grid-tile ng-repeat="site in sites | filter:searchText" class="repeated-item">
            <md-grid-tile-header><h3>{{site.name}}</h3></md-grid-tile-header>
                <div flex layout="row" layout-align="space-between end" style="height:100%" >
                    <div>
                        <md-button ng-click="delete(site, event)" class="md-primary">Delete</md-button>
                    </div>
                    <div flex>{{site.urls.length | number}}</div>
                </div>
        </md-grid-tile>
    </md-grid-list>
```

# SCSS (the example animation from ngAnimate docs)
```
.repeated-item {

  /*
  We're using CSS transitions for when
  the enter and move events are triggered
  for the element that has the .repeated-item
  class
  */
  &.ng-enter, &.ng-move {
    -webkit-transition: 0.5s linear all;
    -moz-transition: 0.5s linear all;
    -o-transition: 0.5s linear all;
    transition: 0.5s linear all;
    opacity: 0;
  }

  /*
   The ng-enter-active and ng-move-active
   are where the transition destination properties
   are set so that the animation knows what to
   animate.
  */
  &.ng-enter.ng-enter-active, &.ng-move.ng-move-active {
    opacity: 1;
  }

  /*
    We're using CSS keyframe animations for when
    the leave event is triggered for the element
    that has the .repeated-item class
  */
  &.ng-leave {
    -webkit-animation:0.5s my_animation;
    -moz-animation:0.5s my_animation;
    -o-animation:0.5s my_animation;
    animation:0.5s my_animation;
  }
}

@keyframes my_animation {
  from { opacity:1; }
  to { opacity:0; }
}
/*
  Unfortunately each browser vendor requires
  its own definition of keyframe animation code...
*/
@-webkit-keyframes my_animation {
  from { opacity:1; }
  to { opacity:0; }
}

@-moz-keyframes my_animation {
  from { opacity:1; }
  to { opacity:0; }
}

@-o-keyframes my_animation {
  from { opacity:1; }
  to { opacity:0; }
}
```

**Comment by gkalpak** [comment]
Unrelated to the question, but you can use the latest version using [rawgit][1] (as described in [README.md][2]).

[1]: https://rawgit.com
[2]: https://github.com/angular/material/blob/master/README.md#cdn

**Comment by shyndman** [comment]
Hey Jonathan,

Thanks for the report. I'd be happy to help you out. Mind creating the plunkr with the instructions above?

**Comment by jonnysamps** [comment]
Ok, here we go:  also, it looks like it reflows properly when items come back into the grid but not when they are removed.

http://plnkr.co/edit/4hkZrM5pNSmb5r8E3c9S?p=preview

**Comment by shyndman** [comment]
ok, I think I've nailed it down. working on a fix.

**Comment by ThomasBurleson** [comment]
@jonnysamps - great bug report. Thx.

**Comment by jonnysamps** [comment]
@ThomasBurleson you guys made quick work of that!  Thanks for the fix!

**Comment by ThomasBurleson** [comment]
@jonnysamps - @shyndman is the wizard here.

**Comment by Badisi** [comment]
Thanks guys but it seems a regression was introduced in v0.9.0-rc3
(see the [plunker](http://plnkr.co/edit/eLd5uAg5Fj01jpATvxO4?p=preview))

**Comment by shyndman** [comment]
Ugh, sorry about this. This got a little bit more tricky because of some recent "enhancements" I made.

I have an idea though. Let me think about it for a bit.

**Comment by Splaktar** [comment]
This seems to be related to https://github.com/angular/material/issues/2702

**Comment by Seiifer** [comment]
> Ok, here we go: also, it looks like it reflows properly when items come back into the grid but not when they are removed.

> http://plnkr.co/edit/4hkZrM5pNSmb5r8E3c9S?p=preview

Has the issue sowed in this plunker been fixed ? Because I'm meeting the exact same issue : http://stackoverflow.com/questions/31053433/css-transition-making-tile-position-wrong-angular-material

**Comment by obarcelonap** [comment]
Selfier, Facing same problem here. I think isn't fixed right now.

**Comment by virkt** [comment]
Definitely not fixed yet ... Tried 0.10.0 and 0.10.1-rc1 builds.

**Comment by okpatil4u** [comment]
Bump

**Comment by obie** [comment]
Bump

**Comment by Badisi** [comment]
I have updated the plunker with latest angularjs #1.4.6 dependencies and angular-material #master but still the reflow is not working.
http://plnkr.co/edit/fFIFFrG7AO63CZeDT4kz?p=preview

**Comment by shyndman** [comment]
Ah, got it. I'm putting together a pull request now.

**Comment by shyndman** [comment]
There you go. Should be in soon.

**Comment by Splaktar** [comment]
Are others seeing this working on Firefox? It doesn't seem to be working on one of my sites with 0.11.3 or 0.11.4.

**Comment by roidayan** [comment]
works for me in firefox.
