### ISSUE TITLE
Problem with md-row-height="fit"

### ISSUE THREAD

**Issue by gmadajczak** [angular/material#1565]
I tried to play with md-grid-list, basing on example from demo, especially with md-row-height value. It seems, that md-row-height="fit" doesn't work. When I use this value, grid doesn't show. My md-grid-list is in the md-content with dynamic height - basing on $window height. Maybe this is a problem.

**Comment by shyndman** [comment]
Have a plunkr?

**Comment by gmadajczak** [comment]
I do not have, but example is simple. I checked, that event if I set md-content for fixed height, md-row-height="fit" doesn't work. Have you other experieence?

**Comment by shyndman** [comment]
I think that the issue is that you aren't giving the grid list a height. Try something like this:

```css
md-grid-list {
  height: 500px;
}

/* or */

md-grid-list {
  height: 100%;
}

I might have to be a little more specific in the docs, or set a better default.

**Comment by gmadajczak** [comment]
Thanks a lot for answer and advice, but it doesn't work. As I wrote at the beginning I have dynamic height of md-grid-list. But even if I try to use fixed value as in your example - it doesn't work also. The problem is in "fit" value. 
Here you are pastebin. http://pastebin.com/V1e9cSCi
I am warning you - it is in jade...

**Comment by shyndman** [comment]
I just wrote this Plunker. http://embed.plnkr.co/q6MllgVlU910hRUn3nB5/preview

Take a look at the code, get it working locally, then build from there.

**Comment by doray10000** [comment]
shyndman   is right make it 100%

 md-grid-list {
  height: 100%;
}

here is the plunker  sir http://embed.plnkr.co/atNbtuFpK8BXm6VVn67f/preview

**Comment by omayhemo** [comment]
Doesn't work for me.  I set the height style to 100% on the grid list and I get no tiles when set md-row-height fit
