### ISSUE TITLE
mdAutocomplete: list is not visible inside mdInputContainer

### ISSUE THREAD

**Issue by tsdaemon** [angular/material#1567]
![1](https://cloud.githubusercontent.com/assets/1999518/6269135/fe6c21ee-b859-11e4-92a7-8255a14cb83d.PNG)
mdInputContainer overflow is set to hidden so autocomplete list is not visible when it inside of the input contatiner.

**Comment by robertmesserle** [comment]
As far as I know, this is not an intended use-case.  There is an issue open for adding this functionality: #1457
