### ISSUE TITLE
feat(md-tooltip): add ability to disable hover events

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#1568]

**Comment by marcysutton** [comment]
Does this mean the tooltip wouldn't show until you clicked, or just make it show conditionally? Would this affect focus?

**Comment by robertmesserle** [comment]
This was brought up in a specific case where the user wanted to control the tooltip display manually.  This makes sense since we provide a visible attribute to allow the user to control its visibility.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by innovaat** [comment]
As a workaround you can add md-delay="999999" and the tooltip will not show on hover. Then use the md-visible="variable" to control the visibility.
