### ISSUE TITLE
Text inside a switch

### ISSUE THREAD

**Issue by yccteam** [angular/material#1569]
Hi,
Is there some API'ish way to get text into the switch circle?
For instance - I want to write "ON" and "OFF" when the value is "TRUE" and "FALSE" respectively.
Thanks

**Comment by marcysutton** [comment]
That doesn't align with the Material Design spec, so it wouldn't be supported in our API. The switch and checkbox both have equal width and height...I don't see how "TRUE" or "FALSE" could be readable without distorting the proportions of the switches.

**Comment by yccteam** [comment]
You are correct. Designer changed the design accordingly :)
