### ISSUE TITLE
Ink animation radius on radio button is inconsistent

### ISSUE THREAD

**Issue by naomiblack** [angular/material#157]
When clicking inside the radio button circle, buttons 2, 4, 5, and 6 behave differently from buttons 1 and 3 in the radio button demo. Buttons 1 and 3 have a big circle animation that overflows the button edge. However, if you click the label instead of inside the circle, all the radio buttons behave the same way. All buttons should behave the same way whether the user clicks in the circle or on the text label.

**Comment by ajoslin** [comment]
This is no longer an issue.
