### ISSUE TITLE
md-select doesn't work

### ISSUE THREAD

**Issue by ask007java** [angular/material#1572]
I see md-select in the demos today but it doesn't work for me. My app is pointing to Angular material 0.8.0-rc1. Am I missing something ?

![image](https://cloud.githubusercontent.com/assets/6759476/6272728/92115cfa-b82f-11e4-9016-1d78acd4e8f8.png)

**Comment by marcysutton** [comment]
Hi, select wasn't in the rc1 release but it will be in the rc2 coming today or tomorrow. It is available on our master branch, just not in a release quite yet.
