### ISSUE TITLE
md-select: Placeholder should be a expression, ng-change etc.

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1573]
a) In multi-lingual environment the placeholder should be set by an expression like {{'LABEL' | translate}}.
b) the angular select offers an ng-change method to react on selection changes. How can I leverage this in md-select ?
c) How to pre-select an initial value ?

**Comment by Frank3K** [comment]
>  c) How to pre-select an initial value ?

Set the `ng-model` in your controller. For me this works (only tested without placeholder).

**Comment by marcysutton** [comment]
Please consider using the [ngMaterial forums](https://groups.google.com/forum/#!forum/ngmaterial) for discussions about using mdSelect. Github should be used for issues and feature requests only. Thank you!

**Comment by Frank3K** [comment]
Whereas (c) is indeed a question, (a) and (b) look like justified issues.

**Comment by marcysutton** [comment]
Okay, cool. Separate issues would be helpful for tracking purposes.

**Comment by Frank3K** [comment]
@kschwidder: I have create a [Plunker](http://plnkr.co/edit/m4PMSuVnkhwxrFijcOsb?p=preview) to showcase issue (b). If you want you can use this to create a separate issue.

**Comment by kschwidder** [comment]
great!
