### ISSUE TITLE
Safari Mobile Performance

### ISSUE THREAD

**Issue by evanshortiss** [angular/material#1575]
Hi Guys,

I'm working on a mobile application and when it's run on a desktop browser performance is perfect. Running on Mobile Safari is a different story as I'm seeing some odd behaviours. For example I have a login screen that is structured like so:

```html
<my-toolbar ng-show="isLoggedIn()">
<div>
  <div ng-show="!loginInProgress">
    <div><!-- LOGIN FORM IS HERE --></div>
    <button ng-click="doLogin()">Login</button>
  </div>

  <div ng-show="loginInProgress">
    <div><!-- MATERIAL LOADING SPINNER IS HERE --></div>
  </div>
</div>
```

Pretty straightforward (slightly simplified for the sake of this example) structure, but the issue I'm having is that when I click the login button the element containing the login form and button takes a short period of time to disappear. The loading spinner appears almost instantly and animates smoothly. 

It seems as though the CSS applied to hide elements is taking a period of time to be applied despite the fact that my JavaScript code has run and updated the variables such as _loginInProgress_. Similarly when I log out of my app and hide the toolbar there's a significant delay, I can almost see each element be removed / hidden in sequence.

Do you have any idea why this might be the case?

Material Design v0.7.1 and v0.7.0
AngularJS v1.3.13

**Comment by evanshortiss** [comment]
Thanks @ajoslin. Could you elaborate a little? I'm familiar with Angular but not particularly familiar with ng-animate. The only element I can think of that is animated is the loading spinner that is an _md_progress-circular_.

**Comment by evanshortiss** [comment]
The some of my divs in the example HTML above are also _md-content_ elements, not plain _div_.

**Comment by marcysutton** [comment]
@evanshortiss can you do two things: 
 * Check your code again using the latest from `master`
 * Post a Codepen or Plunker that we can load up in Safari

Thank you!

**Comment by evanshortiss** [comment]
@marcysutton, I'll try master and see how it goes. I've updated to version 0.8.X though and things have gotten a little better. 

I also found that when I forced HW acceleration using a _translate3d_ things got much better too. Long story short - I was using _webkit-filter: blur_ and it isn't HW accelerated by default, adding that translate3d "tricks" Safari mobile into HW accelerating it and that really helped, but there's still a slightly noticeable lag where the login UI disappears and the spinner shows below it then jumps up to where it should be (where the login was beforehand).

I think it may also be the fact that this is running in a Cordova application which gets the UIWebView rather than the shiny new WKWebView.

Overall conclusion is that this probably isn't a Angular Material issue but rather a UIWebView one. 

Here's a plunkr: http://plnkr.co/edit/IpaZJOqRGXbJRvtMCzPb?p=preview

**Comment by evanshortiss** [comment]
The plunk should be version 12. On my iPad here it's opening as version 8. Not idea why.

**Comment by marcysutton** [comment]
@evanshortiss is there anything left to debug here? Also, have you tried using the Angular Material input component?

**Comment by marcysutton** [comment]
Closing as this sounds like a UIWebView issue. If it persists and there is anything specific we can do to help, let us know.
