### ISSUE TITLE
Clicking inside dialog and then releasing the mouse outside will close it

### ISSUE THREAD

**Issue by MarcosPortugal** [angular/material#1580]
This is happening on version 0.7, not sure if it is still present in 0.8.

 Ideally, the dialog should only close if the user clicks down outside the dialog. So, for example. if the user is dragging a slider in a dialog and releases it when the mouse pointer is outside, the dialog doesn't close (as happens now).

**Comment by ThomasBurleson** [comment]
Cannot reproduce.
