### ISSUE TITLE
Required attribute for select

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#1581]
The docs currently don't show a way to require an option to be selected when using `mdSelect` in a form. Is this possible?

**Comment by epelc** [comment]
+1 It seems required doesn't work with `md-select` in `0.8.2`

**Comment by ngraef** [comment]
Not sure if this is new in 0.8.3, but `required` and `ngRequired` on an `mdSelect` element [both work](http://codepen.io/anon/pen/pvxvqX?editors=101).

**Comment by rschmukler** [comment]
Closing. See #1843 for discussion on styling. Will be resolving that issue soon.
