### ISSUE TITLE
md-select : placeholder should be an expression

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1585]
Placeholder of md-select is currently a String. This inhibits multilanguage Apps like {{LABEL | translate}}.

Please Set placeholder to an Expression

**Comment by EladBezalel** [comment]
Duplicate? #1573

**Comment by ngraef** [comment]
You can use [`<md-select-label>`](https://material.angularjs.org/#/api/material.components.select/directive/mdSelect) for this.

``` html
<md-select-label>{{ label | translate }}</md-select-label>
```

**Comment by rschmukler** [comment]
For more complex expressions, `md-select-label` is the recommended method

**Comment by ilanbiala** [comment]
@rschmukler what is the visual difference?

**Comment by karlhorky** [comment]
@ngraef @rschmukler I believe this is with 0.10.0 and newer now broken. Maybe because it was removed in 5d9874fbfe3f80616d8c0cd948738d2865908b3e ? I guess the correct markup looks like this now:

```html
<md-input-container>
  <label>State</label>
  <md-select ng-model="selectedState">
    <md-option value="{{state}}" ng-repeat="state in states">
  </md-select>
</md-input-container>
```

**Comment by S8nsick66** [comment]
I did some testing, maybe the next googler will save some time with this info.

Doesn't work (the label is not translated):

```javascript
<label translate>My label</label>
<label><translate>My label</translate></label>
<label>{{ 'My label' | translate }}</label>
```

Works but is deprecated and doesn't look as nice:
```javascript
<md-select-label>{{ 'My label' | translate }}</md-select-label>
```

Works and looks nice but is without a label element:
```javascript
<md-input-container>
  <md-select ng-model="selectedState" placeholder="{{ 'My label' | translate }}">
```

Plunker: https://embed.plnkr.co/aRD0aTljBc7846suJNGC/

**Comment by ThomasBurleson** [comment]
@S8nsick66 - please open a new issue with ^^. Thx.
