### ISSUE TITLE
md-subheader don't allow clicks when md-button wrapped with another element

### ISSUE THREAD

**Issue by borisirota** [angular/material#1589]
this is the [plunk](http://plnkr.co/edit/bAi8vH).  
Setting
```css
#button {
  z-index: 1;
}
```
in the css fixing it but its not a real solution.

I'm using the version in the master (0.8.0-rc1) but it happens in 0.7.1 as well (as used in the plunk).

I posted this in #554 as well.

**Comment by mhchen** [comment]
Hi @borisirota this seems to have been fixed at some point already. Would you mind checking if this is still an issue with later version of Angular Material? For instance, here's [a fork of your plunkr](http://plnkr.co/edit/8RkLhSRoS4XLAegQ66n8?p=preview) updated to v0.11.0

**Comment by jelbourn** [comment]
Closing as fixed. Feel free to re-open if there is still some outstanding issue.
