### ISSUE TITLE
md-select placeholder doesn't allow for custom interpolation symbols

### ISSUE THREAD

**Issue by jamesspencer** [angular/material#1590]
https://github.com/angular/material/blob/master/src/components/select/select.js#L86

I reckon this'll be solved by #1573 but will happily produce a PR if you don't think so.

**Comment by PaulMougel** [comment]
I believe something similar to what #887 introduced should be implemented; see the [relevant code](https://github.com/angular/material/blob/efbd414a4d5af7b5144f1d08522e46cc043b627d/src/core/services/interimElement/interimElement.js#L398-L410).
