### ISSUE TITLE
md-ripple-container not present

### ISSUE THREAD

**Issue by gkaimakas** [angular/material#1595]
I have installed angular-material using bower and I am trying to create a button with a rippling effect, just like in the demos.

My code looks like this

    <md-content layout layout-fill>
            <md-button>
                submitLogin
            </md-button>
    </md-content>

When I've inspected the elements from the demos and my element, I saw that there exists a div in the demos

    <div class="md-ripple-container"></div>

that is not present in my button.

Could this be a bug or am I missing something here?

**Comment by ajoslin** [comment]
It gets lazily created the first time you touch/mousedown the button.

**Comment by gkaimakas** [comment]
Well, it isn't created for me no matter what I do and I get no ripple effect. The only thing I get is this piece of code

    <button class="md-button md-default-theme" ng-transclude="" tabindex="0">
        <span class="ng-binding ng-scope">
            submitLogin
        </span>
    </button>

**Comment by gkaimakas** [comment]
Well I found what was wrong with my setup,

I was referencing jQuery and bootstrap's js files prior to angular's and angular material's files so something was breaking.

This has to be a bug I guess

**Comment by ajoslin** [comment]
That shouldn't be a problem... Reopening

**Comment by JayKan** [comment]
I was having a similar issue with the <md-radio-button></md-raido-button> where <div class="md-ripple-container"></div> wasn't generated when radio button is selected or not...I've also tried to rearrange my jQuery and Boostrap's js files and no good luck here. Can somebody post the solution where rippling effect works for checkbox or radio buttons? Thanks a lot!

**Comment by bhouser** [comment]
From the Angular documentation here: https://docs.angularjs.org/api/ng/function/angular.element
> If jQuery is available, angular.element is an alias for the jQuery function. If jQuery is not available, angular.element delegates to Angular's built-in subset of jQuery, called "jQuery lite" or "jqLite."

Is it possible that some parts of angular-material only work with jqLite?  Because changing the order of the files as described, determines whether angular uses jqLite or full jQuery

**Comment by gkaimakas** [comment]
Hello, just wondering if there is any progress regarding that bug

**Comment by Tyrannmisu** [comment]
This Bug is still persistent in 0.9.7 , just experienced it and had a hard time figuring it out :D

**Comment by sethx** [comment]
Still experiencing this as well.
Please find a solution to it.

**Comment by ciaranj** [comment]
Mostly to save others when googling (so apologies, for the 'me too'), but mdDialog buttons do not appear for me if I a) Do not include jquery or b) Include jquery in the page, but *after* I include angular.js.

If I include angular.js first, then jquery then my application appears as expected, however in the console I see the warning: 'WARNING: Tried to load angular more than once.'

**Comment by gkaimakas** [comment]
Thanks for fixing it! Any insight on what caused the problem?

**Comment by robertmesserle** [comment]
@gkaimakas Not entirely sure of the original cause, but this is a full rewrite of the tabs functionality.  If this reappears for you, please let me know and I will look into it.
