### ISSUE TITLE
Multi Select when many options are selected does not have correct spacing..

### ISSUE THREAD

**Issue by zamamohammed** [angular/material#1596]
![screenshot_2015-02-20-19-23-46](https://cloud.githubusercontent.com/assets/2327532/6312229/7ac8c1ce-b937-11e4-8a72-6fdc50be3ad5.png)

This looks UI issue to me where two lines are very close to each other.

I would also like to see a feature wherein you can restrict the number of selected options to be shown, (eg.) if more than five options are selected then show text "6 Players selected".

**Comment by DefunctExodus** [comment]
:+1:

**Comment by Splaktar** [comment]
Still seeing this in 0.8.0. Also the demo needs to be updated to keep some minimal padding around the multi-select.

**Comment by rschmukler** [comment]
The recommended way to do this is to do a custom `multi-select-label`.

**Comment by my9074** [comment]
I would also like to see a feature wherein you can restrict the number of selected options to be shown, (eg.) if more than five options are selected then show text "6 Players selected".


+1  This requirement is very need
