### ISSUE TITLE
md-ripple don't delete itself when multiples click

### ISSUE THREAD

**Issue by drtobal** [angular/material#1597]
Hello,

I noticed that when you press the buttons too many times consecutively, the ripple it is don't removed, it hapens on the md-list and md-checkbox too, and I think in general with the directive md-ripple.

Atached a photo of this.

![material-design-angularjs](https://cloud.githubusercontent.com/assets/3515447/6312289/332321dc-b952-11e4-9c85-18e06a70cc1f.png)

**Comment by Frank3K** [comment]
Can confirm this issue on Firefox 35.0.1.

**Comment by ernestoalejo** [comment]
If it's only the sidebar there's a duplicated issue here. #1398

**Comment by Frank3K** [comment]
It's (at least) on any `md-button`, not only those in the sidebar. But I think this is a duplicate issue indeed.
