### ISSUE TITLE
md-select disappear when 0 is selected and floating label issue

### ISSUE THREAD

**Issue by ask007java** [angular/material#1602]
I have two issues with md-select that can be viewed at http://plnkr.co/edit/0OKK4qf9SEBOzQcw7zh4?p=preview

1) md-select disappears when 0 is selected.
2) How can I achieve floating label for md-select ?

**Comment by Frank3K** [comment]
2) See discussion in #1586 .

**Comment by Frank3K** [comment]
1) I think [this line from select.js](https://github.com/angular/material/blob/3cbd3e0e11777547bb47176942a7a69e6f47bfed/src/components/select/select.js#L86) should be changed:

``` js
 labelEl = angular.element('<md-select-label>').html('<span>{{' + attr.ngModel + ' ? ' + attr.ngModel + ': \'' + attr.placeholder + '\'}}</span>');
```

I would guess it would have to be:

``` js
 labelEl = angular.element('<md-select-label>').html('<span>{{' + angular.isDefined(attr.ngModel) + ' ? ' + attr.ngModel + ': \'' + attr.placeholder + '\'}}</span>');
```

**Comment by rschmukler** [comment]
Nice catch. The discussion for a floating label can be handled in #1586, but I will keep this issue open as a reference to your first bug.
