### ISSUE TITLE
md-select : What am I doing wrong

### ISSUE THREAD

**Issue by HiloCoder** [angular/material#1603]
Basically duplicated the demo from the angular material website but the list of options always display as a single line.   http://plnkr.co/edit/3sXK8BDMB7WaOTeZSNUM?p=preview

**Comment by ask007java** [comment]
You are using older version of angular material. Point it to master if you want to use md-select. See demo http://plnkr.co/edit/WTSUAd4IcVZb2krUMr9M?p=preview

**Comment by HiloCoder** [comment]
Thank you.  I assumed (obviously incorrectly) that google would host the current version.

**Comment by IDontEatSoap** [comment]
Is it supported in 0.8.0-rc1?

Linking to raw-git isn't going to fly to redistribute apps...

**Comment by marcysutton** [comment]
`mdSelect` will be out in 0.8.0-rc2–you can see the linked Angular Material source in your demo is 0.7.1. Additionally, Google and npm host major releases only (0.8.0, as opposed to the release candidate). 

Raw-git/master is only meant for development and low-traffic demo purposes.
