### ISSUE TITLE
How to use grid system in the right way?

### ISSUE THREAD

**Issue by kostonstyle** [angular/material#1604]
Hi

I am pretty new in the material design world and stuck on, how to create my layout in the right way. I created my angular material application with https://github.com/angular/material and try to change the toolbar. I change my tool like this

```html
<md-toolbar layout="row" layout-align="start center" ng-controller="NavbarCtrl" layout-wrap>

 <div flex="35">

 </div>

 <div flex="25">
 <md-button href="https://github.com/Swiip/generator-gulp-angular"><b>Gulp</b></md-button>
 </div>

 <section layout="row">
 <md-button ng-href="http://google.com" target="_blank">Sign In</md-button>
 <md-button ng-href="http://google.com" target="_blank">Sign Up</md-button>
 </section>

</md-toolbar>
```

My question is, is this the right way how to use layout?

I try to understand the usage of grid system on the angular material website, but do not get it. It is so difficult, cuz less docs about everything? What is the best to learn grid system?

**Comment by Frank3K** [comment]
Questions can be asked in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial). You have a better change for an answer there. 

The issue tracker is for issues only.

**Comment by kostonstyle** [comment]
I asked few times and my post is going to delete automatically why?

**Comment by Splaktar** [comment]
What post is getting deleted? where?
