### ISSUE TITLE
md-button fab with ng-href change icon position

### ISSUE THREAD

**Issue by luclanet** [angular/material#1607]
![image](https://cloud.githubusercontent.com/assets/3264432/6316611/2506f1a6-ba2d-11e4-8f3c-85fc114d9ed9.png)
First with "ng-href", second one without.

**Comment by marcysutton** [comment]
That means anchors and buttons inside of `md-button` have slightly different styles...`ng-href` creates an child `<a>` element instead of `<button>`. Should be an easy fix, want to create a PR?

**Comment by luclanet** [comment]
What's a PR?

**Comment by ruiaraujo** [comment]
@luclanet pull request, ie, fix it. ;)

**Comment by iainmcgin** [comment]
I've been playing with this in codepen (http://codepen.io/iainmcgin/pen/wBjqyB), I have a proposed fix using absolute positioning for the icon within fabs, but it's kind of ugly and I hope someone finds a better way. Will create a pull request and let everyone discuss it there.

**Comment by iainmcgin** [comment]
The fix from @ruiaraujo looks good, and is included in my codepen for comparison.
