### ISSUE TITLE
Multi Select after selecting many options, and then opening

### ISSUE THREAD

**Issue by zamamohammed** [angular/material#1608]
![defect](https://cloud.githubusercontent.com/assets/2327532/6317867/d3dc8404-ba35-11e4-8f86-dbf1cd0ee17a.png)

This is how you get the big select dropdown, which does not even look like a dropdown to me.

**Comment by Splaktar** [comment]
How is this working in 0.8.0?

**Comment by rschmukler** [comment]
Fixed in 1a81f0c6c98a2fe217f089c3457af5ee99ba61f5
