### ISSUE TITLE
Responsive issues with layout classes

### ISSUE THREAD

**Issue by davechisholm** [angular/material#1609]
Lets say you have a wrapper with layout="column" and then another attribute layout-gt-md="row", with two child elements flex=33 and flex=67. On a large screen (where the layout should be 'row'), the child elements are still matching the selector [layout=column]>[flex="33"] - when the layout=column should have been overridden by layout-gt-md=row. This results in a max height of the child of 33% on a large screen, when the max height should only apply on medium/small screens where the layout is column.

Related issue - when I tried to fix this by omitting layout="column" and replacing it with layout-sm="column" and layout-md="column" (in addition to layout-gt-md="row") - the child flex percentage widths no longer applied, and both the children were 50% width instead of 33/67. This is happening because all the flex width definitions are scoped to [layout=column]>[flex="33"] etc.

**Comment by Splaktar** [comment]
There are certainly some issues here that I have run into lately. It would be great to have a concise Plunker (http://plnkr.co/) to demonstrate the issues though as I haven't been able to isolate the problem myself.

**Comment by mateeyow** [comment]
I don't think flex percentage supports 67.
>The flex attribute value is restricted to 33, 66, and multiples of five. 
>For example: flex="5", flex="20", "flex="33", flex="50", flex="66", flex="75", ....

**Comment by gkalpak** [comment]
It does (secretly) support 34 and 67 as well :)

**Comment by mateeyow** [comment]
Oh, didn't know about that. Now I feel that I'm a part of a 'secret organization' >:)

**Comment by davechisholm** [comment]
Is there a plunker template for angular material (ideally with latest material version)? Would make it a lot quicker if you could just link to a template that could be forked. But anyway, problem isn't limited to the 67% size, that was just an example. Haha secret organisation alright - spent ages figuring out how to use media queries in my controllers then turns out you have $mdMedia available - need to get this stuff documented as it's really handy!

**Comment by MilosStanic** [comment]
wow, @davechisholm I just asked about being able to media query from controllers on Gitter, but nobody answered. This $mdMedia really needs to get into docs asap!

**Comment by ThomasBurleson** [comment]
@MilosStanic - see [$mdMedia in Docs](https://material.angularjs.org/#/api/material.core/service/$mdMedia)

**Comment by ThomasBurleson** [comment]
Fixed with SHA 84e45040a57f301512b0e9dda58e81d8ccf3c18d
