### ISSUE TITLE
md-icon md-svg-src not working

### ISSUE THREAD

**Issue by alexhuot1** [angular/material#1610]
Hi, I'm new to angular materials and i'm trying to use md-icon with md-svg-src and it doesn't work.

```html
	<md-icon md-svg-src="/views/images/ic_account_box_24px.svg" alt="account" style="color:#0F0;"></md-icon>
```

Is there any issues with md-icon? Any idea why it doesn't work?

Thanks a lot.

**Comment by iamrahil** [comment]
This is what I have in my code
```
<md-icon md-svg-src="bower_components/material-design-icons/editor/svg/production/ic_merge_type_24px.svg"></md-icon>
```
Works on the latest master commit. What version are you using? is the path to the image correct?

**Comment by alexhuot1** [comment]
I'm using version 0.7.1
https://ajax.googleapis.com/ajax/libs/angular_material/0.7.1/angular-material.min.js

The path should be good. I can reach the image when i put it in my browser.

Do i need to add something in my js files?

These are my includes
```html
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular-route.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angular_material/0.7.1/angular-material.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-aria.min.js"></script>
```

And i added ngMaterial to my app. ( I already use button, toolbar... etc. So it works)

Thanks for your time.

**Comment by alexhuot1** [comment]
Seems to be a version problem. It works on version 0.8.0

Thanks for your time.
