### ISSUE TITLE
Call method when bottom sheet or dialog is dismissed

### ISSUE THREAD

**Issue by 6matko** [angular/material#1612]
It would be very usefull if you could add this feature so i there would be an opportunity to call custom method, when user dismisses bottom sheet or dialog window. It is very handy, when there are situations with selection.

**Comment by Awk34** [comment]
You can do this. For example, `$mdDialog.show({ ... })` returns a promise. You can use as such:

```javascript
$mdDialog.show({ ... })
    .then(function(result) {
      console.log('resolved');
    }, function() {
      console.log('rejected');
    });
```

**Comment by 6matko** [comment]
@Awk34 ow! Thanks, completely forgot about rejected promise. You helped me a lot :)

**Comment by Awk34** [comment]
You're welcome ;D
