### ISSUE TITLE
md-sidenav's md-backgrop displays across entire screen

### ISSUE THREAD

**Issue by nkoterba** [angular/material#1614]
Hello -

So we've been using MD since ~0.6.  However, in the latest version 0.8, we've noticed the md-sidenav behaves differently.  In the past, the md-backdrop created when the sidenav was opened covered **only** the container where the sidenav was set in the dom.  This was **GREAT** behavior and allowed us to implement sliding side menus, etc.

Starting in 0.8, the md-backgrop now covers the entire screen irregardless of which "div" the sidenav was embedded in.

This issue is visible on the angular demo page for [md-sidenav](https://material.angularjs.org/#/demo/material.components.sidenav):
1) Hover over the `Source` button with mouse. Notice the nice focus effect.
2) Click the `Toggle Right` button and watch the right sidenav appear.
3) Now move the mouse over the `Source` button again.  Notice no focus effect appears b/c the entire right side of the demo app is being "covered" by the md-backdrop.  In previous versions of MD, only the content area (where both sidenavs and the Toggle Right button) were covered with an md-backdrop.

You can also see how the area outside the "demo" box shows an opacity change as the md-backdrop obscures everything.

See pic below:
![image](https://cloud.githubusercontent.com/assets/2508944/6321614/e9e69d58-bacf-11e4-9520-c575588b75c0.png)

**Comment by aeroxy** [comment]
I've noticed the same issue. Also once the sidenav is triggered, the ripple effect on the same page (elements in the area covered by the backdrop) will become very slow unless the page is refreshed.

**Comment by ThomasBurleson** [comment]
Fixed in SHA 690aa87a6cc757366ddcdfbfbf2eba5421ad8e4c
