### ISSUE TITLE
When textarea is created in hidden mode and shown, height is 0px

### ISSUE THREAD

**Issue by akommareddi** [angular/material#1616]
A text area is created in hidden mode and later shown on an user action. The height of the text area is 0px. If the text area is brought into focus and tabbed out, the text area then renders correctly.

Please see http://codepen.io/akommareddi/pen/NPMRor for a demo of the issue

**Comment by mckenzielong** [comment]
This was recently fixed in efbd414a4d5af7b5144f1d08522e46cc043b627d
