### ISSUE TITLE
autocomplete add minLength attribute 

### ISSUE THREAD

**Issue by david-gang** [angular/material#1621]
It is sometimes useful to add a minLength attribute so that searches will be made just above this value.

This is already available in typeahead: http://tosbourn.com/setting-a-minimum-length-for-your-search-in-typeahead-js/

I tried a workaround in the code where in the function which get the md-items i add 

```javascript
if(searchText.length<3) {
                return [];
            }
```
but this does not play nice because the autocomplete starts the animation so it gives the user the feeling that an autocomplete search is done, which is not true.

**Comment by robertmesserle** [comment]
@david-gang Good call, I had considered this early on, but it never made its way into the code.  I'm working on adding this now.

I'm curious if you are still seeing the animation with the latest code (0.8.0) that was released yesterday.  I added some logic that SHOULD have prevented the animation from showing up as you described, but I wanted to know if you were still experiencing this.
