### ISSUE TITLE
Input validation not working

### ISSUE THREAD

**Issue by pidompa** [angular/material#1622]
I've implented the basic form and md-input-container element but I've noticed that there's a strange behaviour when I set my input as required and model update after blur. If I fill the field correctly and leave the focus the input itself results correct but the md-input-container still maintains "md-input-invalid" class even if the input only has "md-input ng-valid-email ng-touched ng-dirty ng-valid ng-valid-required".

This is my code:

<div style="background-color: #ddd">
&lt;md-input-container flex&gt;
     &lt;input name="username" type="email" data-ng-model="credentials.username" required ng-model-options="{ updateOn: 'blur'}"&gt;
     &lt;label&gt;{{ 'VIEWS.LOGIN.USERNAME_LABEL' | translate }}&lt;/label&gt;
     &lt;ng-messages for="loginForm.username.$error" data-ng-if="loginForm.username.$dirty" data-ng-messages-include="{{error_messages_page}}"&gt;&lt;/ng-messages&gt;
&lt;/md-input-container&gt;
</div>

**Comment by pablodenadai** [comment]
Hi there, just a suggestion - You might want to create a small self-contained example to show the issue. [JSFiddle](http://jsfiddle.net/) or [JSBin](http://jsbin.com/) are good tools for that.

Also; I've formatted your HTML code so it's easier to read.

```html
<md-input-container flex>
  <input 
    name="username" 
    type="email" 
    data-ng-model="credentials.username" 
    ng-model-options="{ updateOn: 'blur' }"
    required>

  <label>{{ 'VIEWS.LOGIN.USERNAME_LABEL' | translate }}</label>
  
  <ng-messages 
    for="loginForm.username.$error" 
    data-ng-if="loginForm.username.$dirty" 
    data-ng-messages-include="{{ error_messages_page }}">
  </ng-messages>
</md-input-container>
```

**Comment by pidompa** [comment]
Thanks ;)

**Comment by DefunctExodus** [comment]
sounds like the same problem as  #1606

**Comment by marcysutton** [comment]
Yes, closing as this is a duplicate. Please refer to #1606 and check for open issues before reporting. Thanks!
