### ISSUE TITLE
md-autocomplete inside div

### ISSUE THREAD

**Issue by cyberlake** [angular/material#1623]
When I'm trying to give `layout-align` or `layout="column"` attributes to the `div` that contains `md-autocomplete`, it's not showing the element. When attributes are removed everything is okay. What can be the issue?

**Comment by robertmesserle** [comment]
I created a quick CodePen sample of this, and it looks to be working fine with 0.8.0.  If you can fork this CodePen and get it to break, I will look into it.

http://codepen.io/robertmesserle/pen/gbzGZm?editors=101

Closing for now - please re-open if it is still an issue and include an updated CodePen link.

**Comment by cyberlake** [comment]
http://codepen.io/anon/pen/azGqXe
I had it like this. Seems like it works with `md-layout` but not with `layout`
