### ISSUE TITLE
Error with md-tab and ng-hide

### ISSUE THREAD

**Issue by Akaryatrh** [angular/material#1625]
Hey all,

I just encountered a bug when the first `md-tab` is hidden by a `ng-hide`. The following error can be read in console
```
angular-material.js:7856   Uncaught TypeError: Cannot set property 'lastTabIndex' of undefined
```
Here's a plunkr that demonstrates the bug :
http://plnkr.co/edit/ZCjyxDmhJYpVTAf0MfEq?p=preview

PS : BTW, I'm now using a filter instead of ng-hide.

**Comment by robertmesserle** [comment]
This shouldn't be an issue anymore; however, I don't think that `ng-hide` should be used on tabs due to the complexity of the transclusion that is going on.  Using a filter is a much better approach (as you are doing now).

**Comment by gladsonrobinson** [comment]
@Akaryatrh  Please let me know how to use the filter here. Having same issue and am using angular-material": "~0.9.4"

**Comment by TheRockman** [comment]
I also have this issue, please share your solution

**Comment by nitin7dc** [comment]
ng-hide not working on md-tab (angular-material 0.10.0)
Plnk : http://plnkr.co/edit/G3Ajcm?p=preview

**Comment by l0rn** [comment]
+1

**Comment by scottbergeron** [comment]
What's the current work around for this? @Akaryatrh mentioned he used filters instead of ng-hide. Does anyone have an example of that?

**Comment by robertmesserle** [comment]
@scottbergeron You could use a filter to remove elements that should be hidden, or you could also use `ng-if` in place of `ng-hide` for an easier solution.
