### ISSUE TITLE
md-select does not constrain overflow w/ scroll, and throws exception when using up/down keys to select option, in IE11

### ISSUE THREAD

**Issue by tafs7** [angular/material#1628]
Using IE11:
The list container is not constrained with overflow:scroll, and extends beyond page with no scrollability.

When using the keyboard and up/down keys to select options in the md-select, exceptions are thrown from the `focusNextOption()` and `focusPrevOption()`.

**Comment by yarl** [comment]
Similar behavior on IE10.

**Comment by ngraef** [comment]
@rschmukler the overflow fix added a persistent disabled scroll bar to all `md-select`s in Chrome. Check [the select docs](https://material.angularjs.org/#/demo/material.components.select) to see it.
