### ISSUE TITLE
input validation doesn't play nice with ng-model-options updateOn

### ISSUE THREAD

**Issue by kentcdodds** [angular/material#1634]
See [this example](http://jsbin.com/sawugi/1/edit?html,js,output). If you remove the `updateOn` property or set it to `'default'` then everything seems to work fine. But if you have it set to `'blur'` then the field shows red even when it's valid.

**Comment by dmackerman** [comment]
Yep, seeing this also.

**Comment by ThomasBurleson** [comment]
Fixed with SHA c818da75c89043a81de6234120315d7d48abc782
