### ISSUE TITLE
require('angular-material') fails with NPM install

### ISSUE THREAD

**Issue by jgoux** [angular/material#1635]
Hi,
the NPM installation is weird, it takes the angular/material repository + an internal bower-material folder.
We end up with the sources + the build.
As the build is not in the root folder, doing ```require('angular-material')``` fails.

The current solution I've find is to use the git address directly : 
```
"angular-material": "git://github.com/angular/bower-material",
```

**Comment by ThomasBurleson** [comment]
`npm install angular-material` now working as expected; fixed with 

* https://github.com/angular/bower-material/commit/614726c25351d2a8ee7a4f72ebff02e106b3b781
* https://github.com/angular/bower-material/commit/9a9b47d6674bcd023ad805ca3b05c0976f11e5f7
