### ISSUE TITLE
Input doesn't render correctly on iOS safari

### ISSUE THREAD

**Issue by borey** [angular/material#1636]
This happens on safari running on iOS 8.1.2 (iphone 5s)

![start typing](https://cloud.githubusercontent.com/assets/704991/6345475/146af758-bc39-11e4-9d5e-ef6eee49750b.PNG)

Here's what happens after After clicking on autocomplete word
![click auto complete](https://cloud.githubusercontent.com/assets/704991/6345483/24bb0f12-bc39-11e4-9cf1-1deb40f8fd00.PNG)

**Comment by sapytech** [comment]
+1.
It is just not iOS safari. I have same issue in chrome. For some reason ng-prestine doesn't get fired up when user enters a value in a required field for the first time. Users have to clear entered value before ng-pristine is called.

**Comment by varunis** [comment]
I think this is realated to open bug in input https://github.com/angular/material/issues/1485

**Comment by borey** [comment]
Seem it's not related. bug https://github.com/angular/material/issues/1485 has been closed, but this bug  still exists. 

I'm testing with https://material.angularjs.org/ at commit v0.8.2 - SHA fbe8c62.

**Comment by depoll** [comment]
+1 -- encountering this with a simple email address field.

```html
<md-input-container class="login-input-container">
    <label>Email or Phone</label>
    <input name="identifier"
            type="email"
            autocapitalize="off"
            ng-model="credentials.identifier"
            ng-minlength="3"
            ng-trim="true"
            required />
    <ng-messages for="authForm.identifier.$error" ng-show="authForm.identifier.$dirty">
        <ng-message when="required">You must provide an email or phone number</ng-message>
        <ng-message when="minlength">Invalid email address or phone number</ng-message>
    </ng-messages>
</md-input-container>
```

**Comment by mpiasta-ca** [comment]
+1 Just tested in iPhone 6 Plus and text appears hidden/invisible when typing. I was going to convert our mobile app to ngMaterial but will have to wait until this bug is fixed. Pretty critical if a user can't see input as 99% of our app is forms.

**Comment by depoll** [comment]
FYI, the following CSS seems to have fixed the issue for me:

```css
input, button, textarea, select {
    -webkit-transform: translate3d(0,0,0);
}
```

**Comment by depoll** [comment]
(note, there are a couple of other elements that disappear on screen rotation, hence my inclusion of more than input/textarea here -- those are probably sufficient to fix this specific bug)

**Comment by marcysutton** [comment]
I'm not seeing the same issues any longer–there is no indent in the text input and it scrolls into view when I start typing. I'm going to close this as I'm pretty sure it is fixed, but let us know if it persists after 0.9.0 is out (very soon).

**Comment by jpike88** [comment]
This issue has returned, please reopen it as it needs urgent attention before this framework can be considered ready for production use.

**Comment by mnlekarev** [comment]
+

**Comment by rodrigopedra** [comment]
same issue here with 1.5.0. I am using @depoll css to fix it. Only happens with inputs using ng-model

**Comment by jkruse** [comment]
Might have nothing to do with material: http://stackoverflow.com/questions/28730103/ios-textarea-text-hidden-when-using-webkit-overflow-scrolling-touch (I'm having the same issue without using material, just stumbled on this issue)
