### ISSUE TITLE
ng-click no longer working at all across my mobile app

### ISSUE THREAD

**Issue by jeffthompson1971** [angular/material#1640]
Just moved to the latest-greatest material, and now my whole app is broken.   ng-click is never fired for any of my controls on any of my webviews.   FYI I'm building an appgyver supersonic app.    I've been using ng-click with angular-material for the past 6 months with no issues at all.   But now it's broken with 100% consistency. 

Is this a know issue?  should I be using some other events other than ng-click in my angular app?

**Comment by gustavohenke** [comment]
I've been using `v0.8.0-rc1` for a week, and have no issues.
You should probably post a plunkr/codepen/<insert snippet site here> so guys can help you debug the problem.

**Comment by jeffthompson1971** [comment]
my app is a bit to large/complicated to try to put a code-pen together.. needs to be run in a simulator or real device.   not sure of any way to share it easily.

So you are also using appgyver/supersonic with angular-material for the UI?  If so are you just using ng-click ?

**Comment by gustavohenke** [comment]
Hmmm, I spoke too soon.
In my own app, I activated the touch emulation in Chrome DevTools and found that some clicks are never fired.

The following issues may be related to this one: #1406, #1528 

And no, I don't use Appgyver, I'm using plain Cordova,

**Comment by gustavohenke** [comment]
In my case, I just found that I depended upon ngTouch module, which conflicted with ngMaterial.
_For now_, my clicks are working back again.

**Comment by jeffthompson1971** [comment]
are you saying I need to use ngTouch? I just veriried that going back to the older version of material works fine so clearly this is new breakage across the board.   I was reading about their removing hammer so guessing that's the breakage.   

when can we expect a fix?  is ngTouch a work-around or a proper dependency?

**Comment by marcysutton** [comment]
`$mdGestures` is still causing problems. This is indeed a related issue: https://github.com/angular/material/issues/1406

**Comment by gustavohenke** [comment]
> are you saying I need to use ngTouch?

No, with ngTouch I had problems. Without it = all green.

**Comment by jeffthompson1971** [comment]
Not for me.   Is there  a fix on the way?

**Comment by jeffthompson1971** [comment]
I really need to know if the angular-material team recognizes the breakage from 7 to 8 is indeed there and if there is a fix planned.   If the answer is 'go away we don't care about your issue' that's valid, I'd just like to know so I can move onto another UI solution.    

I just did a final test to make it quite clear there is breakage on ng-click... 

Starting from my broken build that pulls in the latest v8 angular-material what i did was:
1)  git checkout 69462fef4820d8a9f837bac814dd5019484e7add // commit id for one of the v7 builds
2) gulp build
3) reload my app 

and everything is perfect again.   i know that hammer was pulled out etc. so clearly there was code churn around touch events right?    clearly there is an issue and my question is if it will be addressed or not.   I can move on I just need to know what the plan is.   appreciate a quick comment letting me know the status...

**Comment by ThomasBurleson** [comment]
@jeffthompson1971 - we definitely care about this issue. Improving $mdGestures is a priority for us. Please expect some fixes/traction on this in the near future.

**Comment by Trimud** [comment]
Hello,

I'm also having this issue using ngmaterial with Ionic framework.
Adding data-tap-disabled="true" fixes the issue on some places but breaks other things like page scrolling.
Thank you for adding it to the next milestone. I'll be waiting impatiently.

**Comment by jeffthompson1971** [comment]
thanks! ... I'm gonna hold out then. .for now I'm just using v7 for my
mobile app and latest/greatest works fine for my web site (web app).
 Look forward to the fix so I can reference one library across my stuff :)

**Comment by rlucian** [comment]
If this was working in 0.7.0 (so far I can confirm too) , could we see a fix in the current git code so we can use it (with the related risks) from rawgit.com?

**Comment by yarl** [comment]
+1 for @rlucian's statement, definitely some fix for now will be really handy.

**Comment by rlucian** [comment]
unfortunately it appears this has been moved to milestone 0.10.0, probably because there's no easy fix, so it might not get fixed too soon.

**Comment by naomiblack** [comment]
We have made a number of improvements to gestures as of 0.10.1.  
If there are specific issues (excluding Ionic, which we already track in another bug #2758) please file a new issue with a codepen repro case.
