### ISSUE TITLE
Date input with required and min visually invalid in Chome for Android

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#1645]
Open the following plunkr in Chrome for Android:
http://embed.plnkr.co/Yi0NdGdJih67RaieXeu9/preview

The input has the `required` and `min` attributes. When both are set, the `<md-input-container>` will always have the `.md-input-invalid` class, even if you select a date after the `min` attribute.

However, I found that selecting a date, cleaning the input, and then selecting another date will remove that class. I verified this behavior in my own phone and in a teammate's phone.

This behavior doesn't occur in Chrome desktop.

**Comment by ruant** [comment]
I had this issue in Chrome desktop as well.
But the commit 747eb9c3f493dfc338901f66108042ca78b5936e solved the issue for me.

**Comment by gustavohenke** [comment]
As of v0.8.3, this is no longer happening :+1:
