### ISSUE TITLE
md-subheader sticky bug in chrome

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1647]
When using md-subheader on a flex="x" container (i.e. not full width) the sticky class is causing the header to transform into 100% of the window width...

![screenshot](https://cloud.githubusercontent.com/assets/1916471/6360340/4c141a12-bc71-11e4-9a3e-21d86ade6d36.png)

![screenshot](https://cloud.githubusercontent.com/assets/1916471/6360346/520b138a-bc71-11e4-91eb-978234e8f11d.png)

Seems to work ok on Safari, but on Chrome it is not behaving as expected. Look to be something to do with the .md-sticky-clone class adding positon:absolute with a left/right of 0 but my css ability is woeful so can't suggest a solution.

**Comment by PaulMougel** [comment]
Example: http://codepen.io/anon/pen/GgdzEo

**Comment by jasonrig** [comment]
http://codepen.io/anon/pen/zxyzYZ

Adding the "position: relative" style to the container element seems to fix the problem.

**Comment by deltaepsilon** [comment]
+1. The postion: relative hack works fine... but it would be much nicer if the sticky header were somehow placed inside of the md-content element, which is already relative and already necessary for proper scrolling.

**Comment by topherfangio** [comment]
I think this may be fixed by #4276 when it gets merged. I will let you know when it's merged and see if you can re-test.

**Comment by Xorok** [comment]
Hello, I'm experiencing a bug similar to this one on the newest version. I'm trying to create a website that uses ngRoute with a simple templateurl to load the different subpages into the main view. The sticky subheader works more or less like it should on all browsers when the subpage-code is pasted directly in the main site (so as one document), but as soon as you put it into a different file and load it with ng-route, Chrome enters derp-mode.

Here is a screenshot comparing Firefox and Chrome when all the HTML code is in one file and ngRoute is not being used:
https://i.imgur.com/VUOxala.png

Aside from the fact that the shadow below the bar doesn't show up on Firefox and that the sticky bar appears too soon on Chrome resulting in two bars at once on the screen, everything looks fine.

But as soon as you switch back to the main-view concept with ngRoute, this happens on Chrome:
https://i.imgur.com/1BRZ55h.png

This is the structure of the index.html-file (with main-view):
```
<body>
<div layout="row" id="wrapper" ng-controller="AppCtrl" layout="column" ng-cloak>
    <md-sidenav class="md-sidenav-left" md-component-id="left" md-disable-backdrop md-whiteframe="4">
	  ...
    </md-sidenav>
	
    <div layout="column" flex>
	  <md-toolbar ng-controller="HeaderController">
	    ...
	  </md-toolbar>
	  
	  <md-content class="main-insert-view" ng-view>
	</div>
</div>
</body>
```

And this is the subpage I'm trying to insert:
```
<div ng-controller="LabelController">
  <h2>Labels</h2>
  <md-list id="label-list" ng-cloak>
	<md-subheader class="subheader">General</md-subheader>
	<md-list-item class="secondary-button-padding" ng-repeat="label in labels">
	  <md-icon aria-hidden="true" md-svg-src="images/color.svg" ng-style=" {'fill': label.color}"></md-icon>
      <p>{{label.name}}</p>
      <md-button class="md-secondary" ng-click="remove_label(label.id)">Remove</md-button>
	</md-list-item>
  </md-list>
</div>
```

Am I doing something wrong with the containers or is this a bug?

Regards
Xorok

**Comment by topherfangio** [comment]
@Xorok Since this issue is already closed, could you paste this info into a new issue and just reference this one?

Also, if you can provide a Codepen that demonstrates it, it would be super-helpful in us tracking it down. Feel free to ping me in the issue and I'll take a look at it.

**Comment by z3ntu** [comment]
@topherfangio I am working with @Xorok on this project and the complete code is available here: https://github.com/MadeInSpengergasse/Honeypot/tree/master/static

**Comment by Xorok** [comment]
@topherfangio Ok, you can find the new issue here: https://github.com/angular/material/issues/7983
