### ISSUE TITLE
md-input: textarea keeps showing as invalid when the input is valid

### ISSUE THREAD

**Issue by dinoboff** [angular/material#1651]
If a `md-input` textarea is required and it gets focus via a click, the input will keep showing as invalid (its input container will keep having the `md-input-invalid` class) when the input becomes valid (has `ng-valid` class, `ngModel.$valid == true`).

Tested on Google Chrome 40.0.2214.115 (64-bit, OS X 10.9.5) with angular material 0.8.0:

1. visit http://codepen.io/anon/pen/yyjQdy
2. click Address input
3. type "foo"

The input will be valid but the UI will show it has invalid.

Note: If you focus the textarea by tab'ing to it first, it works properly.

**Comment by gustavohenke** [comment]
See also: #1645 and #1606

**Comment by dinoboff** [comment]
oops, it's a duplicate of #1606. It not just textarea, but any `md-input` that get get focus with a click first.
