### ISSUE TITLE
mdSelect: positioning feature

### ISSUE THREAD

**Issue by mateeyow** [angular/material#1652]
I think the new mdSelect is greate but I am having toubles when the button for mdSelect is on the right-most side of the screen. When I click the mdSelect the overflow-x starts coming out. 
![screenshot from 2015-02-25 10 40 25](https://cloud.githubusercontent.com/assets/6420838/6364009/4fb7afc0-bcdb-11e4-9fae-eeea7fab6383.png)

**Comment by ThomasBurleson** [comment]
@mateeyow - plz provide a CodePen or Plunkr that demonstrates this issue.

**Comment by mateeyow** [comment]
Here's my [codepen] (http://codepen.io/mateeyow/pen/YPvzeQ)
