### ISSUE TITLE
md-select is getting double scrollbars with many items

### ISSUE THREAD

**Issue by jadrake75** [angular/material#1653]
When you have many items in the md-select, the select drop-down menu is getting double scrollbars.

It seems adding

md-select-menu {
    overflow-y: hidden;
}

instead of auto fixes the issue.  This is using v0.8.1 which has overflow-y: auto.  However the md-content inside the md-select-menu already has the overflow-y: auto; css

line 5593
https://github.com/angular/bower-material/blob/v0.8.1-master-fee482d/angular-material.css

**Comment by seiyria** [comment]
Seems this was taken care of here: 4d722ecf9f8240f47e6e8989afcc5388c99669b4

**Comment by jadrake75** [comment]
yeah.... this would be correct.  I can confirm it is fixed.
