### ISSUE TITLE
md-select not binding to model on init

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1654]
md-select does not seem to be looking at the initial value of ng-model to set the label to the correct value. Instead it just displays the placeholder.

**Comment by bennet093** [comment]
if you use an extra <md-select-label> tag in the <md-select> tag and use the model value it will work. Could be a quick fix for you

**Comment by rschmukler** [comment]
@hodeyp this should be working in 0.8.1. Please let me know if it's not, and I'll take a look.

**Comment by hodeyp** [comment]
sorted, thanks!
