### ISSUE TITLE
md-divider do not work well in md-card outsite the md-card-content

### ISSUE THREAD

**Issue by scarletsky** [angular/material#1656]
Here is a demo.
http://codepen.io/scarletsky/pen/OPZdQb

----------

One more question:  

Can a `md-card` have multi `md-card-content` ? I can't find more infomation in the docs.

**Comment by Mathem8tic** [comment]
Seems to be something related to the flex-order of the <md-divider>

Try putting the flex-order="1" attribute inside the <md-divider>

**Comment by scarletsky** [comment]
I am using v0.9.0-rc2.
It seems that this issue has been fixed.
