### ISSUE TITLE
md-select: displays three times an md-option item with 0.8.1 !

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1657]
After upgrading to 0.8.1 the md-select displays three times an md-option element.
This behaviour was not within 0.8.0.

                <md-input-container>
                    <md-select ng-model="status.filterState" placeholder="Filter">
                        <md-select-label>{{ status.filterState.name | translate }}</md-select-label>
                        <md-option ng-value="opt" ng-repeat="opt in filterSel_States">{{ opt.name | translate }}
                        </md-option>
                    </md-select>
                </md-input-container>

                $scope.filterSel_States = [
                    {name: 'LEAD_STATE_ALL', value: 'all'},
                    {name: 'LEAD_STATE_CONFLICT', value: 'conflict'},
                    {name: 'LEAD_STATE_OPEN', value: 'open'}
                ];

                $scope.status = {
                    isFilterOpen: true,
                    filterState: $scope.filterSel_States[0]
                };

![md-select](https://cloud.githubusercontent.com/assets/3265624/6368326/ed5d2318-bcdb-11e4-983a-4ded7ace8cb5.png)

**Comment by Toilal** [comment]
Hi @kschwidder :)

Same here, duplicates #1643

**Comment by rschmukler** [comment]
Closing as duplicate.
