### ISSUE TITLE
flex layout issue with undefined values on Firefox & IE

### ISSUE THREAD

**Issue by Toilal** [angular/material#1660]
```html
<div layout="row">
  <div flex/>
  <div flex/>
</div>
```

```html
<div layout="row">
  <div flex="50"/>
  <div flex="50"/>
</div>
```

Should give the same rendering. But it is not the case for some browsers (Firefox & IE), where it can vary dependening on children div width (computed, or specified by CSS). It works as expected on Chrome and Safari.

See the plunkr, that behaves differently from Chrome to Firefox

http://plnkr.co/edit/W8OcRbqll0BzqKywiExv?p=preview

i'm not sure if it's really related to angular-material, or if it's the flexbox browser implementation that cause the issue ...

**Comment by germanferrero** [comment]
Why is this issue closed?, still having problem with this.

**Comment by EladBezalel** [comment]
This plunker is not available please fix it..

**Comment by ThomasBurleson** [comment]
With the SHA 843d63ec5520d313eb327d2d99606e9f6177912e on master, You should be able to verify that the follow works as expected:

```html
<div layout="row" class="layout-content" >
    <div flex >
      [flex]
    </div>
    <div flex hide show-gt-md >
      [flex]
    </div>
    <div flex hide-sm>
      [flex]
    </div>
  </div>
```

Here is the [CodePen Demo](http://codepen.io/ThomasBurleson/pen/pjbpdw?editors=100)

**Comment by ThomasBurleson** [comment]
And here is another demo that show [Layout changes with media Breakpoints](http://codepen.io/team/AngularMaterial/pen/gabQVx?editors=010)
