### ISSUE TITLE
Allow items to be created with Attributes or Elements

### ISSUE THREAD

**Issue by alexwolfe** [angular/material#1661]
Currently the material design components must be elements which creates problems for accessibility. 
`<md-button href="https://google.com">Google</md-button>` 
If javascript is not enabled or until the transformation takes place, this code currently has not meaning. The problem is easily solved by allowing for the A (attribute) in the directive along with the element. This allows the link to be progressively enhanced. 
`<a  href="https://google.com" md-button>Google</a>`

**Comment by gustavohenke** [comment]
Most directives are too complex to be HTML and CSS only. If they're not, you're very likely to not be able to make them adhere to Material Design without lots of markup (for example, the ripple effect).

Also, it's worth noting that Firefox does no longer allow you to disable JS without going deep into `about: config`.

**Comment by ThomasBurleson** [comment]
Will not fix.

**Comment by ThomasBurleson** [comment]
@alexwolfe - Sorry I mis-interpreted the enhancement request. @jelbourn provided extra clarity and will work on this. Thx.

**Comment by marcysutton** [comment]
It's worth noting that `<md-button>` is being replaced with `<button>` or `<a>`, providing adequate accessibility after transclusion. But supporting progressive enhancement wherever possible is definitely a good idea.
