### ISSUE TITLE
md-grid-tile and ng-repeat

### ISSUE THREAD

**Issue by GistCode** [angular/material#1663]
Hi devs, thanks a lot for the gridList directive, I understand that it is really new I wish I could help more

I'm encountering an issue as of now, it doesn't seem to watch changes on its source array

as for now I'm splicing and unshifting arrays for the grid list with a timeout but I cannot use something as simple as this

````Javascript

$scope.tabs[parentIndex].characters = ionic.Utils.arrayMove($scope.tabs[parentIndex].characters,index,0);

```

**Comment by shyndman** [comment]
Mind creating a Plunkr?

**Comment by shyndman** [comment]
You can use link against `https://rawgit.com/angular/bower-material/master/angular-material.js` for the latest angular-material.
