### ISSUE TITLE
mdTooltip: md-direction not applied

### ISSUE THREAD

**Issue by dozingcat** [angular/material#1673]
See http://codepen.io/anon/pen/KwePQZ . The tooltip should appear above. the text, but is instead below it.

**Comment by dozingcat** [comment]
Looks like the direction check was removed in https://github.com/angular/material/commit/2fc53b98fefb1f3bdb810ca746188cfd65ca5e15?diff=unified#diff-0732597cd96cb9d201490dfa8fe61b4b

**Comment by tamer1an** [comment]
Yes, i confirm same behavior +1 for fixing it
