### ISSUE TITLE
mdWindowBar: directive for window bar

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#1677]
As described [here](http://www.google.com/design/spec/layout/structure.html#structure-system-bars) in the spec i think you should add the window bar:
![window bar](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7Tkh3MGZVVktoOTQ/layout_structure_system_status2.png)
![2](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7OFZxQTM5SmxHQjA/layout_structure_system_status4.png)

Tthe top bar contains the window controls: minimize, full screen, and close. 
The top bar can disappear, and the window controls are then brought into the app bar.

in the app bar 
![appbar](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7cHV2LWpmTnRUbm8/layout_structure_system_status5.png)

any thoughts about this?

**Comment by ThomasBurleson** [comment]
Is this not a Toolbar with child components and appropriate layouts?
This is something developers can easily do... why should Angular Material create such an application-specific component?

**Comment by EladBezalel** [comment]
@ThomasBurleson as you can see in the second picture it's a separate component..  This is not an application-specific component, this is for desktop users who wants to build desktop apps with node-webkit and use the angular material library, I agree it's not that complicated to create this alone but it's mentioned in the spec so I figured that it should be a part of this library

**Comment by EladBezalel** [comment]
More to say that the window bar should have the primary dark color, which for now as much as I know is not possible.

**Comment by Furqankhanzada** [comment]
@EladBezalel :+1: 

It will be great. i am building Chrome App and missing this directive. specially top right dropdown.

**Comment by EladBezalel** [comment]
FYI this can be easily done with the new `mdColors` directive
