### ISSUE TITLE
Input errors

### ISSUE THREAD

**Issue by Virviil** [angular/material#1686]
It's hard to search in so many issues, probably already ticketed, but on your demo page:
https://material.angularjs.org/#/demo/material.components.input
In section "Top Secret Project"
When typing in Client name field it's marked as "errored" even when you type something in it.
It's marked as normal only after you delete all text from input, and then retype something again. Probably bug with "required" attribure.
Chrome version 40.0.2214.115 m, win 7/x64

**Comment by gustavohenke** [comment]
Yet another related issue to #1606, #1645 and #1651

**Comment by marcysutton** [comment]
Closing as duplicate.
