### ISSUE TITLE
md-fab button in md-toolbar has white background

### ISSUE THREAD

**Issue by Toilal** [angular/material#1687]
I thing there's a problem with styling in [button-theme.scss](https://github.com/angular/material/blob/04feeb836ae5508d4c0349f125d13b75dd63b7b3/src/components/button/button-theme.scss#L4-L6). It cause md-fab button embeded in md-toolbar to have white background, regardless the theme.

[Plunkr showing the issue](http://plnkr.co/edit/2Jj73NUPERrih2siCuwM?p=preview)

**Comment by Toilal** [comment]
It's related to #1223, but I don't think simply setting the background to white was the best solution ...

It's not consistent with colors applied when moving mouse over the button, or clicking it.

**Comment by birdcw** [comment]
I've noticed white fabs like this in iOS, but not in anything else that I've tried. They only get their color when clicked.

**Comment by marcysutton** [comment]
Hi, can you repost your Plunker? The link is no longer working.
