### ISSUE TITLE
‘Select all’ functionality on select that uses multiple selection

### ISSUE THREAD

**Issue by qorsmond** [angular/material#1691]
When a user wants to select all items in a select list he needs to select all the items throughout the list. This works but when the list is long it is a burden. A ‘select all’ option in the list will help allot or something that can help the user to select all the items more easily. I did not see anything regarding ‘select all’ functionality on the material design spec or maybe I missed it so not sure how this should be implemented.

The way I implemented it for now is to populate my ng-module with all the data available in the list with a button in the list to select all the items, here is a plunk:  http://plnkr.co/edit/ceYU5R?p=preview

**Comment by marcysutton** [comment]
Your implementation makes sense to me, I don't think it should be the responsibility of the mdSelect component itself to provide that functionality.

**Comment by rschmukler** [comment]
As @marcysutton said, that's more on your implementation. The point of `md-select` is to provide a material design alternative to the native `select` element.
