### ISSUE TITLE
md-input handles disabled nicely with ng-model, but not with ng-value.

### ISSUE THREAD

**Issue by michaelkrog** [angular/material#1693]
If I do this:
```
<md-input-container>
    <label>Input 1</label>
    <input ng-model="input1" disabled>
</md-input-container>
```
...then it looks like this:
![skaermbillede 2015-02-26 kl 17 23 04](https://cloud.githubusercontent.com/assets/681472/6396008/3d348c18-bddc-11e4-904b-0756e443b3bd.png)

But if I change ng-model to ng-value like this:
```
<md-input-container>
    <label>Input 1</label>
    <input ng-value="input1" disabled>
</md-input-container>
```
....then it looks like this:
![skaermbillede 2015-02-26 kl 17 23 26](https://cloud.githubusercontent.com/assets/681472/6396018/600a676c-bddc-11e4-8c05-56eb773f2070.png)

Codepen: http://codepen.io/anon/pen/raKePQ

**Comment by ThomasBurleson** [comment]
ngValue: Binds the given expression to the value of <option> or input[radio], so that when the element is selected, the ngModel of that element is set to the bound value.

mdInput does not support input[radio] as we have mdRadioButton. mdCheckbox components for those.

Will not fix.

**Comment by DmitryEfimenko** [comment]
@ThomasBurleson nevermind the `ng-value`. Even if you use just a `value` attribute (to give some visible un-editable value) it also becomes messed up.

In my case I just want to display a value that cannot be edited within the form so that it looks similar to the other inputs.

This needs to be addressed.

**Comment by robertmesserle** [comment]
@ThomasBurleson Did you mean to re-open this after moving to backlog?

**Comment by davideicardi** [comment]
This now (v 0.10.1) seems to be nearly fixed...
The only problem is that label value is not displayed.

Codepen fork: http://codepen.io/anon/pen/vOwqKR

**Comment by zilions** [comment]
Is this going to be fixed? In my opinion, it's quite important.

What if we had `ng-value="myModel1 + myModel2"1.

**Comment by Miklecc** [comment]
+1
