### ISSUE TITLE
md-select prevents clicks globally under specific conditions

### ISSUE THREAD

**Issue by sjlynch** [angular/material#1694]
Update: Reproduced the issue here: http://plnkr.co/edit/2OZyNNNMWkjoumC3TAWg?p=preview

Hey all,

Great work with the md-select so far and good work on the library in general. I am really enjoying working with it and it looks very visually impressive. This is exciting stuff!

So I believe I found a bug. This was only tested in Chrome Version 40.0.2214.111 m. Might be related to #1665

Bug:
As a user, when I click on an md-select with an empty options list and then resize the browser window, the empty list stays open and clicks no longer register within the browser.

Should be:
As a user, when I click on an md-select with an empty options list and then resize the browser window, the empty list should close and click events should register as normal.

I hope that is enough to reproduce the bug.

The select looks like below, if it helps. The user can no longer hide the options and click events do not trigger elsewhere in the browser.

![image](https://cloud.githubusercontent.com/assets/5000496/6396545/0717fff4-bdad-11e4-94a6-4e25eb4cfee7.png)

**Comment by sjlynch** [comment]
Added a plnkr example.

**Comment by rschmukler** [comment]
@sjlynch thanks for the kind words and the detailed bug report. It seems that the commits from 0fe35cc8 and  0fe35cc resolve this. Thanks!
