### ISSUE TITLE
feat(autocomplete): I18n support for screen reader messages

### ISSUE THREAD

**Issue by marcysutton** [angular/material#1696]
In `$mdAutocomplete`, the number of matches and the currently highlighted item on arrow key press are announced using an `aria-live`-enabled element. This works pretty well except the strings are currently embedded into the HTML [without internationalization support](https://github.com/angular/material/commit/0bd7afb81755ea2815c8af646d692e045509f014#commitcomment-9928469). We could include an interface like [ngPluralize](https://docs.angularjs.org/api/ng/directive/ngPluralize) to handle "There is 1 match available" vs. "There are X matches available", but we are hesitant to add that much logic onto autocomplete element itself (which is the API exposed to developers). 

The ideal approach for these kinds of translations would be to consolidate them into a single file that would then interface with each component that needed it (like md-button, brought up in https://github.com/angular/material/issues/1639).

**Comment by jelbourn** [comment]
`md-list` also has an instance of a hard-coded English message.

**Comment by marcysutton** [comment]
We should consolidate announcements into a single `<aria-status>` directive so users don't end up with duplicate ARIA Live Regions in a given app.
