### ISSUE TITLE
bug(tabs): disconnect causing issues

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#1698]
As posted by @mxdubois:

>This causes a problem for me where the scope is disconnected after it is reconnected by onSelect during the initial load. The bug results in ng-model bindings in the initially selected tab not working until the user switches to another tab and switches back.

>In what case is the $timeout necessary? If we need to keep the $timeout, we should save the promise returned by $timeout and cancel it in onSelect where we call reconnectScope. If that sounds good, I can submit a PR.

Link: https://github.com/angular/material/commit/78ba497e443ca31e8a8c97f11db281f743f6aca0#commitcomment-9946067

**Comment by jamie-pate** [comment]
I noticed that on('$destroy') is no longer called also? (maybe?) wouldn't this be a potential leak?
