### ISSUE TITLE
mdSelect: No Longer displaying initial value of ngModel

### ISSUE THREAD

**Issue by mzbyszynski** [angular/material#1699]
It looks like something in this commit: 6baed64 is preventing the `mdSelect` from rendering the correct value if the `ngModel` is already defined.

Here is an example of this working from the last build yesterday using v0.8.1-master-e2148f1:
http://codepen.io/mzbyszynski/pen/MYXbzX

Here is an example from the next build: v0.8.1-master-6baed64:
http://codepen.io/mzbyszynski/pen/NPzbma

Notice how in the first example the name "Bill" is already selected, but in the next release the select is blank? Or if this change is intentional could you describe the correct way to pre-initialize an mdSelect with a selected value?

Oh, and here is the same codepen using the master branch (just to show that this issue hasn't been fixed since 6baed64):
http://codepen.io/mzbyszynski/pen/dPKOBo

Apologies if I missed something here or if someone else already reported this problem and I missed it.

Thank you for your help and all your hard work so far!

**Comment by umidbekkarimov** [comment]
Just noticed same problem

**Comment by seiyria** [comment]
Thanks for the temp fix @umidbekkarimov

**Comment by aksakalli** [comment]
I have the same problem for 0.8.2-master-7950588, 
thanks @umidbekkarimov , it saved the day.

**Comment by matthieuh** [comment]
Same problem but fix can't work if label different from value...

**Comment by umidbekkarimov** [comment]
@matthieuh Is your label depend on value?

```html
<md-select-label>{{ makeLabel(value) }}</md-select-label>
```

**Comment by vlopez5** [comment]
Please fix this.
I have the same issue here.
