### ISSUE TITLE
$mdMedia: document and publish the API for this service.

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1700]

**Comment by gmadajczak** [comment]
Yes. I would like to ask for the same!

**Comment by marcysutton** [comment]
@ThomasBurleson does https://material.angularjs.org/#/api/material.core/service/$mdMedia cover it?

**Comment by ThomasBurleson** [comment]
Fixed in 6861bad04b557c8189ce35190f4f4b71c21ee3ea
