### ISSUE TITLE
No docs and demos for making a sidenav completely

### ISSUE THREAD

**Issue by AMAID** [angular/material#1702]
I find no way to make a sidenav just like the main navbar of material.angular.org,
such as toggle menus, no border-radius buttons.

**Comment by carab** [comment]
If I'm correct, the doc is using a non-published version of mdListItem which allows this.
It's planned for the 0.9 milestone, as described in #985.

**Comment by ThomasBurleson** [comment]
We are working on a mdList enhancement to support features that you see in our Docs sideNav area:
*  complex row content, 
*  row selections, and 
*  expando-rows. 

Closing this issues as **duplicate** of #985
