### ISSUE TITLE
<a> links not working on Android versions

### ISSUE THREAD

**Issue by buu700** [angular/material#1704]
Versions tested: master, 0.8.1, 0.8.1-rc1

Browsers tested in: Android/Firefox, Android/Chrome, OS X/Chrome (mobile simulator)

Clicking `<a>` tags has no effect in these versions. Works fine when I pin to version 0.7.1.

**Comment by Toilal** [comment]
:+1: 

I could not believe this, but after testing on Android it's true :)

**Comment by gustavohenke** [comment]
What about 0.8.0?

**Comment by ThomasBurleson** [comment]
@robertmesserle, @rschmukler - I think should be resolved before the 0.8.2 release.

**Comment by robertmesserle** [comment]
@buu700 I just tested on multiple Android devices as well as OS X/Chrome (Mobile Simulator), and have been unable to recreate this bug.  Can you provide a Plunker or CodePen to demonstrate?

**Comment by ThomasBurleson** [comment]
@buu700 - what version of Android and what version of your browser. We also need a CodePen or Plunkr.

**Comment by buu700** [comment]
Cool, I'll set up an isolated test now and post a link when it's ready.

Android version is 4.4.4 (2013 Moto X, so basically stock), with Chrome 40.0.2214.109.

**Comment by buu700** [comment]
Okay, got it. You can test it with master [here](https://sandbox-dot-cyph-im-dot-cyphme.appspot.com) ([CodePen version](http://codepen.io/anon/pen/MYXrXj)).

I can consistently reproduce it; maybe it's just an issue with the bower package?

**Comment by gustavohenke** [comment]
Yep, touch emulation in Chrome can't access that link.

**Comment by robertmesserle** [comment]
Update: This seems to be related to jQuery and Angular Material causing some sort of conflict.

**Comment by robertmesserle** [comment]
Should be resolved by 7950588882557a6d1670e2029ddda76d12027c45

**Comment by buu700** [comment]
Working now for me, thanks!

**Comment by buu700** [comment]
As mentioned in #1972, I can reproduce this again in the latest master.
