### ISSUE TITLE
md-autocomplete - formatting of display property 

### ISSUE THREAD

**Issue by Anton2012** [angular/material#1706]
formatting of the display property works in selection mode

![image](https://cloud.githubusercontent.com/assets/3371863/6414122/723f9ede-be95-11e4-9bf4-4098706110b1.png)

but showing the selected item it doesn't

![image](https://cloud.githubusercontent.com/assets/3371863/6414146/9d3d7be2-be95-11e4-8578-8133646f10d4.png)

**Comment by r0b-** [comment]
+1

Additionally it would be nice to have support for multiple lines in the item text.

Thanks
