### ISSUE TITLE
md-search-text-change is not working in md-autocomplete

### ISSUE THREAD

**Issue by saurabh-p** [angular/material#1708]
?

**Comment by marcysutton** [comment]
Hi, can you please provide more details and a Codepen or Plunker showing your issue?

**Comment by nirving** [comment]
Hi I have created one @ http://codepen.io/anon/pen/WbgMOv which show another issue I am facing, but highlights that 

    md-search-text-change="console.log('here')" 
    md-selected-item-change="console.log('here')"'''

Does not appear to work with 0.8.3

The reason I want this to work is so that I can cancel the second lookup when selecting an item. Will report that issue seperately.

**Comment by robertmesserle** [comment]
That link is not working for me. Closing for now, please re-open with an updated link if the problem still exists in master.
