### ISSUE TITLE
mdAutocomplete: ng-disabled retains the cancel search button

### ISSUE THREAD

**Issue by zlovin** [angular/material#1710]
The cancel button on md-autocomplete is still present when the autocomplete is disabled. When clicked, the search clears and no text can be entered.

Should the cancel button be hidden when the autocomplete is ng-disabed? 

The demo on https://material.angularjs.org/#/demo/material.components.autocomplete demonstrates the issue.

**Comment by magister94** [comment]
+1

**Comment by rhautefeuille** [comment]
Hi there,
seems like the issue is still present in 1.1.8.
Again the demo can be used to reproduce.

**Comment by Splaktar** [comment]
I opened PR https://github.com/angular/material/pull/11248 to clarify the documentation in regards to this change in `1.1.5`.
