### ISSUE TITLE
$mdIconProvider cannot be injected

### ISSUE THREAD

**Issue by davidshen84** [angular/material#1712]
Please check [this](http://codepen.io/davidshen84/pen/yyEKVQ) code sample. The `$mdIconProvider` just won't get injected.

I got

    [$injector:modulerr]

in the console

**Comment by MilosStanic** [comment]
I think you forgot to include the angular-material script in your codepen. 

Here's a fork of your sample with angular-material 8.2 added via CDN. 

http://codepen.io/anon/pen/xbzjQp

**Comment by davidshen84** [comment]
Yes, your fork works. But I have

    <script src="//ajax.googleapis.com/ajax/libs/angular_material/0.7.1/angular-material.min.js"></script>

at my bottom of my HTML file. And I think mine HTML file looks the same as yours. Can you please kindly point out where I did wrong?

**Comment by davidshen84** [comment]
I think we should close this issue. And open another issue against the document.
