### ISSUE TITLE
mdSelect/mdOption: Should Set value to contents when ng-value and value arent set

### ISSUE THREAD

**Issue by epelc** [angular/material#1713]
`md-option` should set the value to the contents of the element if neither `ng-value` nor `value` are specified. This is similar behavior to the native html5 `select` and `option` elements.

For example:
```
<md-select ng-model="Stats.time"  placeholder="Select a time period">
            <md-option>3h</md-option>
            <md-option>1h</md-option>
            <md-option>30m</md-option>
            <md-option>15m</md-option>
        </md-select>
```
Returns Error: Expected either ngValue or value attr {stack: (...), message: "Expected either ngValue or value attr"} <md-option tabindex="0">

**Comment by JoeyHoutenbos** [comment]
+1
