### ISSUE TITLE
mdSelect: support group-by programmatically

### ISSUE THREAD

**Issue by leeyeh** [angular/material#1715]
I'v got a `select` with a bunch of grouped options, wrote in vanilla angular: http://plnkr.co/edit/ZcXQDAXMB7RQqyp7HiCp?p=preview
```html
<select ng-model="status" 
        ng-options="key as (key+' '+value) group by (key[0]+'xx') for (key, value) in HTTP_STATUS_CODE"></select>
```
Angular support this feature with a comprehension-expression-typed attribute called [ngOptions](https://docs.angularjs.org/api/ng/directive/ngOptions).

It seems that mdSelect does not support such comprehension expression. In the [mdSelect demo](https://material.angularjs.org/#/demo/material.components.select)#Option_Groups, `md-optgroup`s are declared manually with hard-coded values, which mixed up data and UI.

Please consider to support group-by in a programmatic way.

**Comment by andreabadesso** [comment]
+ 1

**Comment by srdone** [comment]
This can currently be accomplished less elegantly by something similar to the following:

```
<md-select ng-model="selectedRequirement" placeholder="Select Requirement to Add">
    <md-optgroup label="{{requirementCategory}}" ng-repeat="requirementCategory in requirementCategories">
        <md-option ng-value="requirement" ng-repeat="requirement in requirements | filter: {category: requirementCategory}">{{requirement.name}}</md-option>
    </md-optgroup>
</md-select>
```

I'm new to Angular, but if I can figure out how to add this to the directive in an elegant way, I'll submit a pull request.

**Comment by leeyeh** [comment]
Thanks for your solution, @srdone. It helps.

**Comment by srdone** [comment]
@leeyeh Good, I'm glad.

**Comment by rschmukler** [comment]
Not supporting for now. Open to the PR but since `ng-repeat` can be used to achieve the same thing, we are prioritizing other issues
