### ISSUE TITLE
mdSidenav/mdList/mdToolbar: the whole sidenav scrolls

### ISSUE THREAD

**Issue by vitoller** [angular/material#1717]
when having a mdSidenav with a mdToolbar and mdList, the whole sidenav scrolls.

When implemented without the sidenav, the toolbar stays at the top, and only the list scrolls. This behaviour is expected, and I assum that the mdSidenav/mdList/mdToolbar behaviour is not intended.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr demonstrating this issue.

**Comment by vitoller** [comment]
OK, here is plunkr example:

http://plnkr.co/edit/Q0COh2rWMmZmOS8fOvqv

**Comment by ThomasBurleson** [comment]
@vitoller - Here is a [SideNav Plunkr](http://plnkr.co/edit/AGE0JeZtHGcqLt3bp4Nq) that shows how the SideNav works. Your version had many issues:

*  You never loaded the angular.js, angular-animate.js, angular-aria.js libraries
*  You never created and instance of the Angular Material app (@see `<body>`).

> With the libraries and App, the `md-sidenav` directive will not work. And the sideNav will not layout properly.

**Comment by vitoller** [comment]
sorry for not setting up the project correctly.

I forked the plunkr example and added a list to the main content and the sidenav.
In the main content the toolbar is not in the scroll region. If the size is expanded to show the sidenav however, the toolbar is in the scroll region and disappears when scrolling down.

**Comment by ThomasBurleson** [comment]
Remove the `<md-content flex>` in line 22 in http://plnkr.co/edit/2IMErUnUxmyqSCAjHtpt.

In the future, please post these types of questoins to the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial). This issues is for **bug reports** and **feature requests**.
