### ISSUE TITLE
md-option container not positioned in mozilla

### ISSUE THREAD

**Issue by ryangittens** [angular/material#1719]
when using md-select, the options container is not being positioned below the md-select in mozilla. It works in chrome though. 
![image](https://cloud.githubusercontent.com/assets/9895968/6427053/db28c710-bf42-11e4-972d-a7eceb75d7a6.png)

**Comment by ryangittens** [comment]
md-select sorry

**Comment by rschmukler** [comment]
This was fixed in 67618dc8fb5a81b23ed33879b062a6e316477a4a
