### ISSUE TITLE
md-select is not working 

### ISSUE THREAD

**Issue by ask007java** [angular/material#1725]
See the example: http://plnkr.co/edit/0OKK4qf9SEBOzQcw7zh4?p=preview
it was working before but not anymore.

**Comment by jadrake75** [comment]
You are using it in an md-input-container.  Don't.  It is not meant to.  There is already discussions around the label, but for now it doesn't work "correctly" in that container

**Comment by ask007java** [comment]
I removed md-input-container and is working now. Thanks

**Comment by rschmukler** [comment]
Closing. Issue with `md-input-container` is already open.

**Comment by jasonwatt** [comment]
Just ran across this issue. you should really conciser updating the documentation to remove md-input-container from the example

https://material.angularjs.org/latest/api/directive/mdSelect
