### ISSUE TITLE
#bug Subheader position is wrong when the toolbar is md-scroll-shrink in Chrome

### ISSUE THREAD

**Issue by yxh10** [angular/material#1726]
When you put a subheader under content and having a md-scroll-shrtink toolbar on the same page, the postions of subheader is wrong if you scroll down in Chrome. This might be related to #1647 

```<div layout="column" layout-fill>```
```      <md-toolbar md-scroll-shrink>``` 
     ``` </md-toolbar>```
     ``` <md-content style="height: 100vh;">```
        ``` <md-subheader>test</md-subheader>```
         ```<p>blah bla which is long enough cause scrolling</p>```
      ```</md-content>```
```</div>```

**Comment by cbellino** [comment]
I am also seeing this issue in Chrome 41.0.2272.118 (MACOSX)
It is working fine in Firefox 35.0.1.

I created a pen to demonstrate the problem: http://codepen.io/anon/pen/qEGZzB

**Comment by ThomasBurleson** [comment]
You were not properly including `angular-material.css`. Fixed - http://codepen.io/team/AngularMaterial/pen/QjwxLW
