### ISSUE TITLE
md-select doesn't respect RTL

### ISSUE THREAD

**Issue by gnitzan** [angular/material#1728]
Hi,

md-select is expected to align the down arrow to the left when direction:rtl is applied.

This is not the case the issue can be viewed on plnkr: http://plnkr.co/edit/aoAz9m

Thanks,

Gal.

**Comment by ajoslin** [comment]
If flexbox is used to position the caret, RTL will work as expected.

**Comment by ttvd94** [comment]
@ajoslin could you provide a code example, please?

**Comment by Splaktar** [comment]
@ttvd94 Andrew isn't on the team anymore. Please ask for this kind of help in the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial) or on StackOverflow.
