### ISSUE TITLE
md-input-container stay invalid when input become valid (with django-angular)

### ISSUE THREAD

**Issue by Grmiade** [angular/material#1730]
md-input-container stay invalid when input become valid (with django-angular)

    <md-input-container flex="" class="md-default-theme md-input-invalid md-input-has-value">
        <label for="id_username">Utilisateur</label>
        <input id="id_username" maxlength="20" name="username" ng-maxlength="20" ng-model="username" ng-required="true" type="text" class="md-input ng-valid-maxlength ng-touched ng-dirty ng-valid-parse ng-valid ng-valid-required" tabindex="0" required="required" aria-required="false" aria-invalid="false">
    </md-input-container>

**Comment by dinoboff** [comment]
It should be fixed in 0.8.2

**Comment by Grmiade** [comment]
Thanks !
