### ISSUE TITLE
md-autocomplete: New search is triggered after selection

### ISSUE THREAD

**Issue by r0b-** [angular/material#1732]
After selection the search is triggered again... you only see this if there are items that start with another item's name like "foo" and "foobar".

I extended the states with another Alabama to show the effect... type 'a' and select first Alabama
http://codepen.io/anon/pen/ByVvxe?editors=101

IMO the search should be triggered if I focus the search field again to select other possible values for the current query.

**Comment by DefunctExodus** [comment]
I have been having this problem as well.

**Comment by rosscdh** [comment]
+1

**Comment by jojoyuji** [comment]
+1

**Comment by ducva** [comment]
+1
