### ISSUE TITLE
md-autocomplete: httpPromise for md-items

### ISSUE THREAD

**Issue by r0b-** [angular/material#1733]
I'm having a hard time returning a httpPromise in my items-getter like

    $http.get(...).success(...).error(...);

It only works if I use then() 

    $http.get(...).then(successCallback, errorCallback);

The first expression should be working or did I miss sth?

Thanks

**Comment by ThomasBurleson** [comment]
@r0b-  Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
