### ISSUE TITLE
Firefox Mobile: ng-click registering two clicks isntead of one

### ISSUE THREAD

**Issue by borgdylan** [angular/material#1734]
Tapping an md-button is registering twice not once as expected. A double tap is registering as a triple tap.

**Comment by borgdylan** [comment]
This info was obtained thru console logs using the Firefox adb debugging window.

**Comment by bitoverflow** [comment]
This is also happening on iOS. Safari and Chrome

**Comment by spacenick** [comment]
I confirm this behavior when moving from 0.8.2 to 0.8.3. Can be reproduced using the Chrome mobile simulator

**Comment by ivamluz** [comment]
Confirmed when moving from 0.8.2 to 0.8.3 as well. Reproduced here: http://plnkr.co/edit/0hNwPMzrKd3LpvzXDknL, using Chrome mobile simulator (tested using iPhone 6).

Thanks to @fabito for generating the Plunker.

**Comment by ThomasBurleson** [comment]
Dup of #2090 ?

**Comment by ThomasBurleson** [comment]
Here is a version of that same plunker using the latest from Master:  http://plnkr.co/edit/LNqDMfYI6Qko40d5tU46?p=preview

@spacenick, @ivamluz, @borgdylan - can you confirm that this issue no longer occurs ?

**Comment by ivamluz** [comment]
@ThomasBurleson, tested on Chrome mobile simulator (emulating iPhone 6) again and it works as expected. Thanks for getting back.

**Comment by ThomasBurleson** [comment]
Fixed in 2de0cf26a4e7fc985b6247039537311a7e7861c1
