### ISSUE TITLE
md-search: search filter in the toolbar

### ISSUE THREAD

**Issue by sondreb** [angular/material#1735]
Is there a way I can do something similar to search filter in LumX?

http://ui.lumapps.com/directives/search-filter

My app is now out on the Chrome Web Store, and it relies on both Angular Md and LumX, I'm hoping I eventually can drop the latter. I'm happy to see the md-select is out, so I'm working to use that soon.

The app have a search input on the toolbar on the top, to see how it works and what I want to replicate, have a look here: https://chrome.google.com/webstore/detail/flickr-downloadr/fpmonoglnknhfnfgeopdjmhpilpejedj

**Comment by marcysutton** [comment]
How is this different than the `mdAutocomplete` in a toolbar? There are toolbar icon demos coming shortly in #2106 which should get you part of the way there. Just trying to figure out if there's a component missing or rather a demo showing the styling.

**Comment by Nosthertus** [comment]
+1

**Comment by dongorous** [comment]
+1
