### ISSUE TITLE
md-select is not consistent to input containers in form

### ISSUE THREAD

**Issue by marshfire** [angular/material#1738]
Hi,

  I'm trying to use the md-select in a form in a dialog and I can't get any consistent layout for it. See the result below. I would expect the line of the interval select to be the same position as of the input and it would be more consistent to have the label on top also.

Any hints on how to reach that? Browser is Chrome.

![image](https://cloud.githubusercontent.com/assets/681471/6433434/1f458726-c06f-11e4-9e41-e1fad5838e4c.png)

it is generated with the following code (jade):

```jade
md-input-container
  label Name
  input(ng-model="budget.name")
md-input-container
  label Description
  input(ng-model="budget.info")
div(layout, layout-sm="column")
  md-input-container(flex)
    label Start date
    input(type="date", ng-model="budget.startdate")
  md-select(ng-model="budget.interval", placeholder="Interval", flex)
    md-option(ng-value="opt", ng-repeat="opt in intervals") {{ opt }}
md-input-container
  label Icon
  input(ng-model="budget.icon")
md-input-container
  label Amount
  input(ng-model="budget.budget", ng-currency, currency-symbol="{{budget.currencySymbol}}")
```

**Comment by fabioginzel** [comment]
In my application still does not work

![captura de tela de 2015-03-06 09 45 37](https://cloud.githubusercontent.com/assets/7377511/6525565/9c8d5618-c3e5-11e4-85aa-8fa59d46e0d5.png)

**Comment by marshfire** [comment]
Same here, it is better, but not perfect:

![image](https://cloud.githubusercontent.com/assets/681471/6527152/cc1755b8-c418-11e4-912a-a52c7ec56a07.png)

![image](https://cloud.githubusercontent.com/assets/681471/6527114/6b3ab5dc-c418-11e4-8e73-6968a3a22b5e.png)
![image](https://cloud.githubusercontent.com/assets/681471/6527134/99f8d584-c418-11e4-9783-d5025bb1a748.png)

**Comment by fabioginzel** [comment]
+1

**Comment by shannonmpoole** [comment]
Yea mine is still a pixel or two off as well. I imagine https://github.com/angular/material/issues/1586 might makes some changes to the layout anyways so we'll have to see how that plays out.

**Comment by richardlt** [comment]
I had the same problem as @marshfire (the arrow not aligned on the right), resolved with the css hack : 

    .md-select-icon{
        display: flex !important;
        flex: 1 !important;
        align-items: initial !important;
        text-align: right !important;
        flex-flow: row-reverse wrap !important;
    }

Not so pretty but it works...

**Comment by ThomasBurleson** [comment]
Reopening because it appears to still be displaced.
@marshfire - can you provide a CodePen or Plunkr that demonstrates this issue.

**Comment by richardlt** [comment]
Just did it.

The copy/paste from the angular website example http://plnkr.co/edit/OM5miUro4j8W81jEC6uS?p=preview

First remove the md-input-container and you will see the select http://plnkr.co/edit/bTZrWGIcFKj5Pp3ewOBw?p=preview

If you tried to resize the select the arrow is not on the right http://plnkr.co/edit/eEm7Yv0Dg6B5CQAS8ing?p=preview

Finally, resized with the css hack http://plnkr.co/edit/eD0HCZPywSRmbV5YTZJ6?p=preview

**Comment by ThomasBurleson** [comment]
@richardlt - thank you.

**Comment by marshfire** [comment]
I modified the plunker to be able to check against input

http://plnkr.co/edit/dmWy8ejNgqtOPQsFo4Tw?p=preview

**Comment by richardlt** [comment]
http://plnkr.co/edit/a3bPX0qs6Y7X5Dmb9Jzl?p=preview ;)
Pending the correction.

**Comment by isvaljek** [comment]
The selects are not aligned with inputs
![image](https://cloud.githubusercontent.com/assets/2500267/15418234/f28f45ac-1e5d-11e6-85ff-c8fe732e2eb9.png)
