### ISSUE TITLE
md-select: Typing option name doesnt work

### ISSUE THREAD

**Issue by epelc** [angular/material#1740]
With the html5 `select` you can type an options name to quickly select it. An example where this is useful is selecting states since there are alot to scroll through. But it's generally helpful anyways. 

Perhaps this could be implemented and possibly a search bar. But I'd much rather get the regular select style typing to work asap.

**Comment by DavidSouther** [comment]
This is actually what I initially thought "Options With Async Search" was going to be.

**Comment by Splaktar** [comment]
We need this for our app as well. We need to be able to filter options by typing and have this work with multi-select.

**Comment by pietschy** [comment]
We're also using ui-select and need this functionality before we can use md-select.  In particular we're using the dropdown filtering and customised rendering of both the choices and the selected value.  

We're also using it as part of a specialised widgets so it would be useful if the the ngModel requirement was specified as ^ngModel if that's feasible.

**Comment by weisk** [comment]
+1

**Comment by dohomi** [comment]
+1 for multiselect with seachfield lookup.The look and feel of this component is nice: http://ui.lumapps.com/directives/selects

**Comment by rryter** [comment]
+1 for http://ui.lumapps.com/directives/selects

**Comment by wenbolovesnz** [comment]
+1

**Comment by epelc** [comment]
Thanks @wenbolovesnz  and @rschmukler this really makes selecting states a lot easier.
