### ISSUE TITLE
md-select: Overflows outside md-content

### ISSUE THREAD

**Issue by epelc** [angular/material#1743]
If you open an `md-select` near the bottom of a page it will extend pass your `md-content` and create double scroll bars.

**Comment by rschmukler** [comment]
@epelc can you try with latest commit off of master? I think this is fixed. If not, can you provide a plunker/fiddle/pen with the issue.

**Comment by epelc** [comment]
@rschmukler Just checked and it is fixed on master.

But I found another issue. If your window is really short and you open a select with several options there is no scroll bar and the top of the select gets cut off. Note the top of the green bar is the top of the window.
![image](https://cloud.githubusercontent.com/assets/5204642/6450229/4d317bec-c0db-11e4-9088-0e29f14bd64a.png)

**Comment by epelc** [comment]
@rschmukler It's also really glitchy if you open the select then resize the height of the window. The select pop out seems to be fixed in a virtual position of where you opened it. But there's also the background popping thing like in my original problem. You also end up with double scroll bars if your using `md-content`.

![image](https://cloud.githubusercontent.com/assets/5204642/6450431/9e07d0e2-c0dc-11e4-8a20-cfb529a36186.png)

**Comment by rschmukler** [comment]
@epelc #1665 will address the resize stuff. I'll open another issue for the other issue you reported.

**Comment by epelc** [comment]
@rschmukler Thank you
