### ISSUE TITLE
subheader inside md-content while scrolling overlaps the scrollbar

### ISSUE THREAD

**Issue by borisirota** [angular/material#1744]
The subheader's width when the md-content in scrollable mode (which is the sticky clone element) is different than in static mode (the original element).

In static mode:
![screen shot 2015-03-02 at 5 03 43 pm](https://cloud.githubusercontent.com/assets/5683472/6443341/f003499a-c0fe-11e4-8d9d-caad974628ab.png)

In scrollable mode:
![screen shot 2015-03-02 at 5 04 05 pm](https://cloud.githubusercontent.com/assets/5683472/6443347/f8ffd7f2-c0fe-11e4-9c8f-506318e4595f.png)

As you can see in static mode the width is 833px and in scrollable mode the width is 848px.

When placing several elements in the subheader with center or right alignment, the element's placement is changing when going from static to scrollable state and the opposite way because the parent's element width is changing.

I'm guessing that the width should be same in both modes and not causing elements to jump when switching modes.

**Comment by borisirota** [comment]
Today (day after posting the issue) it seems that it was fixed.

**Comment by borisirota** [comment]
One of the changes on monday 03.02.2015 fixed it but something has changed today (tuesday 03.03.2015) and this issue is happening again.

**Comment by xbenjii** [comment]
Also getting this.

Reproduced at http://jsfiddle.net/ffw4ck5d/2/

**Comment by ThomasBurleson** [comment]
Fixed
