### ISSUE TITLE
Setting the class to md-primary in md-radio-group does not influence the md-radio-buttons

### ISSUE THREAD

**Issue by pmdusso** [angular/material#1746]
I'm not sure if this is a bug or if it's the expected behavior. When we have a **md-radio-group**,  setting its class to md-primary (for example) does not change the color of the radio buttons. In order to do so, we have to add md-primary for each **md-radio-button** inside the group.

Here is a plunker for it: http://plnkr.co/edit/XNFnAxpD8V0foKhqEsNv?p=preview 

This is suppose to work like that?

**Comment by marcysutton** [comment]
For that control, it definitely makes sense to allow `md-primary` on the radio group.

**Comment by pmdusso** [comment]
Thanks :) :+1:
