### ISSUE TITLE
Provide documentation for links in sidnav

### ISSUE THREAD

**Issue by Pajn** [angular/material#1748]
I can't seem to find any documentation on how to make links in sidenav appear correct according to specification. On the documentation homepage <menu-item> seems to be used that is not provided by the package.

**Comment by ThomasBurleson** [comment]
You can check [Angular Material - Starter App](https://github.com/angular/material-start).
*  [HTML](https://github.com/angular/material-start)
*  [JS](https://github.com/angular/material-start/blob/master/app/src/users/UsersListController.js#L51-L52) 

> please note that this is work still in-progress.
