### ISSUE TITLE
md-select: angular-material hangs if ng-repeat uses non existing variable

### ISSUE THREAD

**Issue by marshfire** [angular/material#1749]
If in the following code intervals is not defined in the scope, then select tries to open the option list, showing a rectangle, and then hangs until the page gets reloaded:

```jade
md-select(ng-model="budget.interval", placeholder="Interval", flex)
      md-option(ng-value="opt", ng-repeat="opt in intervals") {{ opt }}
```

**Comment by gustavohenke** [comment]
It's always good to provide a demo snippet (Codepen, plunkr, JsFiddle, etc)
