### ISSUE TITLE
Can i apply an error message inside an md-input container if i am using normal post (not ajax)

### ISSUE THREAD

**Issue by ysfjwd** [angular/material#1751]
I am doing a normal post, and I want to apply normal post error message that i get when I do a post via form action='.' method, can i manually iterate over it.

I am using django framework, and here is my code

```html
      <md-input-container>
        <label>{{ form.email.label }}</label>
        {% render_field form.email placeholder=form.email.label ng-model="reg.email" md-maxlength="128" %}
        {% if form.email.errors %}
          {% for error in form.email.errors %}
          <p>{{ error | escape }}</p>
          {% endfor %}
        {% endif %}
      </md-input-container>
```

it does display the error message .. but it is bad and ugly and come before the box. What class you i apply here?

**Comment by marcysutton** [comment]
Hi, please ask these kinds of questions on the [ngMaterial forums](https://groups.google.com/forum/#!forum/ngmaterial). Thank you!
