### ISSUE TITLE
md-select: placeholder and md-select-label should have different roles

### ISSUE THREAD

**Issue by jgoux** [angular/material#1754]
Hi,
at the moment, if we set a `placeholder` on a `md-select` **and** we set a `md-select-label`, the `md-select-label` overwrite the placeholder, even if there is nothing selected.
For example : 
```html
<md-select ng-model="selectedSize" placeholder="Select a size...">
    <md-select-label>{{selectedSize}} px</md-select-label>
    <md-option>...</md-option>
</md-select>
```
This will display " px" by default instead of "Select a size...".
Here is a plunker showing the issue : http://plnkr.co/edit/L9Vqhaml5lJV94pSEDNs?p=preview

In my opinion the `md-select-label` should be used to redefine how the selected option is displayed, and the `placeholder` should be... a placeholder. :P

**Comment by rschmukler** [comment]
Select with no explicit `md-select-label` specified now renders the text value of the selected option as it's value. This should cover 99% of use cases, and is true to how a native `select` element behaves. Placeholder now is just use as a placeholder.

**Comment by rishabhmhjn** [comment]
Has `md-select-label` been deprecated?
I am not able to use it, neither is the above mentioned plunkr (http://plnkr.co/edit/L9Vqhaml5lJV94pSEDNs?p=preview) working!

this one works: http://plnkr.co/edit/m3Ll0A

**Comment by tomrainedotcom** [comment]
@rishabhmhjn I am having the same problem using material 0.11.x have you worked this out yet?

**Comment by rishabhmhjn** [comment]
@tomrainedotcom I haven't fixed it yet!

**Comment by aleccool213** [comment]
@tomrainedotcom @rishabhmhjn https://github.com/angular/material/commit/5d9874fbfe3f80616d8c0cd948738d2865908b3e
