### ISSUE TITLE
mdDialog: positioning is misplaced in Firefox / IE

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1761]
Version : All versions, tested with 0.8.2 and master
Context:
An mdList contains items which will not fit in browsers window.
You scroll to the item and click on it. The click event open an mdDialog.

Problem:
When opening the mdDialog in Firefox/IE the dialog disappears from the screen and is partly of even not visible. It seems that the position of the dialog is not the calculated properly.

This a major bug.

**Comment by kschwidder** [comment]
see #1593

**Comment by yarl** [comment]
Should be fixed by #1759

**Comment by ThomasBurleson** [comment]
@yarl - The team will test the PR after ng-conf.

**Comment by marcysutton** [comment]
@kschwidder can you provide a Codepen or Plunker with your dialog markup? I am not able to repro the issue in IE10 or Firefox with the existing demos. I'm doing some work on dialogs, so I can work in the fix...I just want to make sure I'm seeing the issue first.

**Comment by kschwidder** [comment]
Fixed with #1759

**Comment by marcysutton** [comment]
Yes but #1759 has not been merged. To merge it, we need to be able to repro the bug. Can you or @yarl post a Codepen or Plunker showing the issue?

**Comment by kschwidder** [comment]
Will provide one tomorrow.
