### ISSUE TITLE
Dynamically select a tab

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [angular/material#1763]
Is there any option to programmatically select a tab. As of now only clicks on a particular tab activates it. Could not find any that in documentation, or have I missed it?

**Comment by cgx** [comment]
Use the [md-selected](https://material.angularjs.org/#/api/material.components.tabs/directive/mdTabs) attribute.

**Comment by SiddharthaRRamesh** [comment]
```<md-tabs md-selected="2">
...
</md-tabs>```

This does not work. I am left in in initial tab itself

**Comment by SiddharthaRRamesh** [comment]
Damn! Sorry it works. Actually gulp had crashed. So there was no watch on any of my template files.

**Comment by monetteContensive** [comment]
Is it possible to dynamically insert the number in the controller?
i.e. $scope.tabNumber = 3;

html : md-selected="{{tabNumber}}"

It doesn't seem to be letting me do this.  I've tried without the {{}} as well and it doesn't work.

**Comment by Yogeshwar1992** [comment]
any update on this?

**Comment by Splaktar** [comment]
@Yogeshwar1992 yes, it is working as expected. If you have questions about how to use the API, please post in the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial).
