### ISSUE TITLE
md-autocomplete autofocus

### ISSUE THREAD

**Issue by RomainFleury** [angular/material#1764]
Hi,

I am using md-autocomplete in a md-dialog, to show only a button to launch a search.

BTW, I'd like to set focus on autocomplete > input right when it is available.

Is it possible to pass a param into autocompleteDirective ?
>  \<md-autocomplete md-autofocus="true" ></md-autocomplete>

Then set it to true when building the input ?
> scope:        {
        searchText:   '=mdSearchText',
        autofocus: '=mdAutofocus',

> function MdAutocomplete () {
    return {
      template:     '\
        <md-autocomplete-wrap role="listbox">\
          <input type="text"\
              ng-disabled="isDisabled"\
~~autofocus="autofocus"\~~

Do you want me to make a plunkr to explain ?

**Comment by RomainFleury** [comment]
My html tag is wrong... It isn't possible to set autofocus to false...

But maybe another way by building attributes and set them in an input attributes string instead of writing directly the directive ?

**Comment by marcysutton** [comment]
The dialog currently handles focus on open for accessibility, so would definitely be part of the problem. I'm about to push a fix that will allow `focusOnOpen` in `$mdDialog` to be set to `false` (only to be used when something else is focused).
