### ISSUE TITLE
mdBackgroundSideNav: implement feature specified in the Material

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1765]
![2015-03-03_0802](https://cloud.githubusercontent.com/assets/2002141/6465120/2cee30cc-c17c-11e4-8558-ca0f0770dd3f.png)

The Material design [whiteframes template](http://www.google.com/design/spec/resources/layout-templates.html#layout-templates-tablet) has a layout that looks similar to this idea in the fourth set of layouts. There is a close X in the top corner. It doesn't really match the description of the navigation drawer in the spec though.

**Comment by karray** [comment]
You can add `md-is-locked-open="$mdMedia('sm')"` and `flex-sm="100"` to sidenav. Besides you should add close button.
