### ISSUE TITLE
testing locals in karma/jasmine -> unknown provider

### ISSUE THREAD

**Issue by mertenhanisch** [angular/material#1769]
If you try to test a controller of a bottomSheet and you are using locals - how should one test them?
If I inject them in the beforeEach part, like a service etc, karma/jasmine throws an error:
    Error: [$injector:unpr] Unknown provider

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
