### ISSUE TITLE
is there any example implementation on list view ?

### ISSUE THREAD

**Issue by calidion** [angular/material#1774]
list view like
http://demos.jquerymobile.com/1.4.5/listview/

**Comment by ThomasBurleson** [comment]
@rschmukler - can you comment on this?

**Comment by francismakes** [comment]
@calidion With regard to the example implementation of the list view provided, there is a working example up under [Demos > List](https://material.angularjs.org/#/demo/material.components.list). Are you looking for the different ways to compose different `md-components` onto the List like the ones shown on the referenced link to jQuery mobile demos?

**Comment by EladBezalel** [comment]
#1100 you can take a look here and play with it a bit..

**Comment by calidion** [comment]
@francismakes it lacks examples like right arrows to indicate that items of list views can be clicked and users will be led to a new page.

**Comment by marcysutton** [comment]
We haven't built in support yet. The new list controls out in 0.9.0 kick off support of clickable list controls and inline switches. Expand/collapse is another feature that is targeted for 0.10.0 (see #985). A linked listview is a new component we will have to build; it definitely won't be in 0.9.0.

**Comment by ThomasBurleson** [comment]
Duplicate request of #985.
