### ISSUE TITLE
<md-toolbar> not working in android 4.2 and below versions

### ISSUE THREAD

**Issue by ravinderreddygit** [angular/material#1775]
<md-toolbar> not working in android 4.2 and below versions

**Comment by gustavohenke** [comment]
That's a too brief description of your issue.
You should at least post a reproducible snippet, and maybe some screenshot.

**Comment by ravinderreddygit** [comment]
Angularjs Material design <md-toolbar> Not working in Phone-Gap android4.2 and 4.4 , but working 5.0 please help me anyone if know the answer

"<md-toolbar style="height: 64px;">
        <h2 class="md-toolbar-tools">
            <span>Sign In</span>
        </h2>
    </md-toolbar>"

**Comment by milanart** [comment]
there is problem with layout of toolbar for android 4.3-. but one can not say its not working.

**Comment by mckenzielong** [comment]
I think you're going to hit problems with the built in webview.  It is a pretty old version of webkit, and a lot of the flex-box based features (like layout/ grid system) won't work.  

I recommend giving crosswalk a shot.  It replaces the default webview with a chromium based version, and can be used with cordova. See https://crosswalk-project.org.

**Comment by marcysutton** [comment]
We are not supporting Android 4.2. Can you repro it on Android 4.4 (the farthest back we are targeting)?

**Comment by marcoocram** [comment]
no plans for support old browsers like Android < 4.4 stock? thanks!

**Comment by marcysutton** [comment]
I would also recommend crosswalk, as @mckenzielong mentioned above since we aren't supporting Android versions below 4.4.
