### ISSUE TITLE
md-select opening arrow is not at the "end" of the select area 

### ISSUE THREAD

**Issue by bOOm-X** [angular/material#1776]
The opening arrow of the md-select is not correctly placed.
![image](https://cloud.githubusercontent.com/assets/1289120/6481497/3c119322-c25e-11e4-8f10-1bd779df2b14.png)

 Adding a flex attribute to the span included in the md-select-label fix this issue:
![image](https://cloud.githubusercontent.com/assets/1289120/6481527/868de996-c25e-11e4-815c-cf49122bf300.png)
However, I am not sure that it is the appropriate fix.

Thx

**Comment by myagoo** [comment]
+1

**Comment by pradeepkumarrawat** [comment]
+1

**Comment by adonix** [comment]
+1

**Comment by epegzz** [comment]
+1

**Comment by epelc** [comment]
In `0.8.2` it was on the end but `0.8.3` broke it. I assume a `flex` or layout attribute got removed.

**Comment by marcysutton** [comment]
This looks fixed now. Let us know if you still see the issue!
![Assign to User select demo](https://cloud.githubusercontent.com/assets/1045233/6932146/25356670-d7ca-11e4-8e01-cbb0c70e157d.png)

**Comment by chr0x** [comment]
This problem still occurs here. I'm having to use the fix that bOOm-X had mentioned. My code is:

								<md-input-container flex-sm layout-padding>
									<label>Identificação</label>
									<md-select ng-model="model_here">
										<md-select-label><span flex>{{ model_item_label_here }}</span></md-select-label>
									</md-select>
								</md-input-container>

Any idea?

**Comment by marcysutton** [comment]
Which browser? Can you create a Codepen with your code to show it actually failing? The `<span flex>` element shouldn't be necessary. The docs site currently shows the arrow aligned correctly.

**Comment by chr0x** [comment]
The browser is Chrome (ver. 42). 

I updated my angular-material from version 0.8.3 to 0.9.0 and the problem didn't occured (sadly the version 0.9.0 has broken all of my layout, so I can't migrate now) @marcysutton , the test you made was in version 0.8.3?

The problem can be saw here: http://codepen.io/chr0x/pen/bdppww .As @epelc suggested, I think it is a bug of version 0.8.3.

**Comment by epelc** [comment]
@chr0x It is fixed in `0.9.0` and I'd suggest updating along with taking the time to fix your layout. I've been using angular-material for a while now(since around 0.5) and I find it best to fix whatever issues you have with every release rather then let it grow into a bigger problem. As unless it's a bug it's probably going to stay that way for a while.
