### ISSUE TITLE
md-autocomplete pre-selected value

### ISSUE THREAD

**Issue by oli107** [angular/material#1779]
I want to pre-fill the autocomplete value (use cases = editing an existing value or retaining state on refresh). However, simply changing the model to the pre-selected item does not work as it leaves the dropdown of options visible even if the autocomplete is not in focus. Is there a way to disable the dropdown if a valid entry is already selected and the input is not focused?

**Comment by jojoyuji** [comment]
+1

**Comment by jsguce** [comment]
+1

**Comment by ACDN** [comment]
+1

**Comment by matthieuh** [comment]
+1

**Comment by ACDN** [comment]
A quick review of the controller source reveals a watcher on searchText 

```javascript
 $scope.$watch('searchText', wait
          ? $mdUtil.debounce(handleSearchText, wait)
          : handleSearchText);
}
```
This allows us to set the search text in our controller while loading the state.  
```javascript
 //Populate the searchText property on the object bound to the md-search-text attribute in md-autocomplete
 vm.autoComplete.searchText = preSelectedText;
```
And just like that, you can set a pre-selected value;

**Comment by oli107** [comment]
Whilst that is correct to set the text-field to the selected text, it does perform the same function as selecting an item from the list. Specifically it still leaves the selection box open.

**Comment by ACDN** [comment]
It shouldn't if there is only one result.  It is working perfectly for me.

**Comment by oli107** [comment]
See this codepen:
http://codepen.io/anon/pen/XJxmmE
It appears to be related to two problems, first that it is case sensitive (as can be seen in this example), and secondly issue [1781](https://github.com/angular/material/issues/1781) that it will not select if there is another value with additional characters.

**Comment by ericodes** [comment]
What if the you wanted to tab and then pre-fill the autocomplete with a specific value? Would you want to populate the searchText property on the object bound to the md-search-text attribute in md-autocomplete or the selectedItem property?

**Comment by jsguce** [comment]
doing an ng-init for the preselected value works for me.

```
<md-autocomplete
        ng-disabled="ctrl.isDisabled"
        md-no-cache="ctrl.noCache"
        md-selected-item="ctrl.selectedItem"
        md-search-text="ctrl.searchText"
        md-items="item in ctrl.querySearch(ctrl.searchText)"
        md-item-text="item.display"
        placeholder="What is your favorite US state?"
        ng-init="ctrl.selectedItem.display=ctrl.searchText">
      <span md-highlight-text="ctrl.searchText">{{item.display}}</span>
    </md-autocomplete>
```

**Comment by oli107** [comment]
I do not understand this as a solution, it seems no different to
pre-filling the searchText within the controller? Can you fork the codepen
to demonstrate?

On 12 March 2015 at 14:28, Jethro Guce <notifications@github.com> wrote:

> doing an ng-init for the preselected value works for me.
>
> <md-autocomplete
>         ng-disabled="ctrl.isDisabled"
>         md-no-cache="ctrl.noCache"
>         md-selected-item="ctrl.selectedItem"
>         md-search-text="ctrl.searchText"
>         md-items="item in ctrl.querySearch(ctrl.searchText)"
>         md-item-text="item.display"
>         placeholder="What is your favorite US state?"
>         ng-init="ctrl.selectedItem.display=ctrl.searchText">
>       <span md-highlight-text="ctrl.searchText">{{item.display}}</span>
>     </md-autocomplete>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/1779#issuecomment-78489630>.
>

-- 


*## **Email confidentiality notice **##*

*This message is private and confidential. If you have received this 
message in error, please notify us and remove it from your 
system. Blythwood Vets & The Well Animal Clinic may monitor email traffic 
data and also the content of email for the purposes of security.*

*Blythwood Vets is the name under which the surgeries at Bushey, Northwood, 
Stanmore & Hatch End trade but the surgeries are owned by Blythwood 
Veterinary Ltd, a Limited Liability Company registered in England with 
Company No. 07153623, registered office 500 Uxbridge Road, Pinner, Middx, 
HA5 4SL or; in the case of the Bushey surgery, Blythwood Veterinary 
(Bushey) LLP, a Limited Liability Partnership registered in England with 
No. oc368295, registered office 2 High Street, Bushey, Herts WD23 3DN.*

*Well Animal Clinic is the trading name of Well Animal Clinic LLP, a 
Limited Liability Partnership registered in England with No. oc317137, 
registered office 292 West End Lane, London NW6 1LN.*

*A list of members each LLP is open to inspection at their respective 
registered offices.*

*BLYTHWOOD VETS& THE WELL ANIMAL CLINIC*

*“A COMPLETE CARING SERVICE FOR YOUR PET”*

*Visit us at: **www.blythwood.com* <http://www.blythwood.com/>* & **www.wellanimalclinic.com 
<http://www.wellanimalclinic.com/>*

**Comment by jsguce** [comment]
like @ACDN, mine has only single result.

**Comment by david-gang** [comment]
:+1:

**Comment by brandonwbrown** [comment]
this works for me, but only if i then manually click on the field after page load does the selectedItemChange fire and the preset fills. any ideas on how to trigger it without the click?
