### ISSUE TITLE
validation errors in md-autocomplete

### ISSUE THREAD

**Issue by javierpavon2000** [angular/material#1780]
I want to configure a md-autocomplete input as required and show a message if not filled, but it's not working

```
<md-autocomplete name="autocompleteName" ...      >
</md-autocomplete>
<div ng-messages="form.autompleteName.$error">
     <div ng-message="required">This is required!</div>
</div>
```

if I inspect the formController object for the form, there isn't any object for autocompleteName

any hint? any help?
I just want to validate the md-autocomplete following as the same way of the inputs, is it possible?

**Comment by hitigon** [comment]
made my own autocomplete component, which links ng-messages into it

**Comment by javierpavon2000** [comment]
Just, I can do it too, but I would prefer to follow the "standard" way like the others inputs

**Comment by hitigon** [comment]
@javierpavon2000 I prefer that too, but the md-autocomplete is inconsistent with md-input, that's I really don't like.

**Comment by bfelda** [comment]
@hitigon Agreed on it's inconsistency with md-input.  Seems like it is currently designed to resemble a md-select instead of a md-input.  It looks really odd with other md-input elements around it.

**Comment by robertmesserle** [comment]
@hitigon @javierpavon2000 @bfelda I just added a styling option for use in standard forms: f487248a70c9bfd749953e98e3412240112f39a3

I will be adding validation support as well.

**Comment by robertmesserle** [comment]
A demo of the new styles can be seen here: https://material.angularjs.org/#/demo/material.components.autocomplete

**Comment by hitigon** [comment]
@robertmesserle awesome job!

**Comment by robertmesserle** [comment]
Proposed syntax for messages:

```html
<md-autocomplete md-search-text="searchText" required>
  <md-item-template>...</md-item-template>
  <div ng-messages="searchText.$error">
    <div ng-message="required">This field is required</div>
  </div>
</md-autocomplete>
```

**Comment by 111crb111** [comment]
Pleaes, can you make some example with validations ? And what is md-item-template ?

**Comment by datak1d** [comment]
+1 for md-autocomplete validation example with md-item-template

**Comment by gpopovic** [comment]
+1 with validation example

**Comment by lillylykho** [comment]
+1

**Comment by bfelda** [comment]
@robertmesserle This looks great!  Thanks for implementing it.

**Comment by gpopovic** [comment]
@bfelda this is going to be solved in 0.9.0?

**Comment by robertmesserle** [comment]
@gpopovic This is not going to be in 0.9.0, but I submitted a Pull Request for this feature:

https://github.com/angular/material/pull/2664

**Comment by bopm** [comment]
:+1:

**Comment by fabiusss** [comment]
+1

**Comment by pencilcheck** [comment]
At master, still no validation for md-autocomplete. The example doesn't work.

**Comment by MetalHexx** [comment]
Opened a new issue for this bug since it still appears to be broken: #3401

**Comment by caok2709** [comment]
Not working!!!! I just test it.
        <md-autocomplete required
                md-no-cache="false"
                md-delay="1000"
                md-input-name="PI"
                md-selected-item="property.Value"
                md-search-text="searchText"
                md-items="user in query_user_Search(searchText)"
                md-item-text="user"
                md-floating-label="Investigator *" >
            <md-item-template>
                <span md-highlight-text="searchText">{{user}}</span>
            </md-item-template>
            <md-not-found>
                No matches found for "{{searchText}}".
            </md-not-found>
            <div ng-messages="detailForm.labPI.$error" ng-if="detailForm.PI.$touched">
                <div ng-message="required">This is required.</div>
            </div>
        </md-autocomplete>
![screen shot 2015-06-22 at 6 02 38 pm](https://cloud.githubusercontent.com/assets/7703592/8294220/e6d7a160-1908-11e5-9f7e-8b780c1f72c0.png)

**Comment by caok2709** [comment]
Not working for validation.
        <md-autocomplete 
                required
                md-no-cache="false"
                md-delay="1000"
                md-input-name="labPI"
                md-selected-item="property.value.Refs[0].Value"
                md-search-text="searchText"
                md-items="user in query_user_Search(searchText)"
                md-item-text="user"
                md-floating-label="Principal Investigator *" >
            <md-item-template>
                <span md-highlight-text="searchText">{{user}}</span>
            </md-item-template>
            <md-not-found>
                No matches found for "{{searchText}}".
            </md-not-found>
            <div ng-messages="detailForm.labPI.$error" ng-if="detailForm.labPI.$touched">
                <div ng-message="required">This is required.</div>
            </div>
        </md-autocomplete>
![screen shot 2015-06-22 at 6 02 38 pm](https://cloud.githubusercontent.com/assets/7703592/8294233/0f8ff09e-1909-11e5-90e0-d8a3157175af.png)

**Comment by caok2709** [comment]
Yes that's it. It's not working for md-autocomplete validation:
![screen shot 2015-06-22 at 6 02 38 pm](https://cloud.githubusercontent.com/assets/7703592/8294258/40f4b7d2-1909-11e5-94c5-1f8f46e8b186.png)
![screen shot 2015-06-22 at 6 04 52 pm](https://cloud.githubusercontent.com/assets/7703592/8294261/42fb0dd8-1909-11e5-9b5b-7d6f935d34a2.png)

**Comment by caok2709** [comment]
Even if you said it's required.... $error will always be empty.

**Comment by SergeyBukhman** [comment]
There's a bug with the documentation and example. Instead of 'md-input-name' the documentation says 'name' and the example says 'input-name'.

**Comment by MetalHexx** [comment]
@SergeyBukhman - to be clear, "name", "md-input-name", and "input-name" all do not work.

**Comment by Luxiyalu** [comment]
@MetalHexx +1

**Comment by MetalHexx** [comment]
Md-input-name does not work for me.  Anyone have a plunk or codepen showing it working?

**Comment by deckikwok** [comment]
+1. not working on 0.10.0.

**Comment by MetalHexx** [comment]
He's resolving it off issue #3401

**Comment by danieladz** [comment]
md-input-name="autocompleteInputName" worked for me, you should attach the error to the input inside de md-autocomplete.
now my problem is that the field is shown in red from the start, because is not $pristine u_u

**Comment by evoker** [comment]
This doesn't seem to be working in RC5 for 0.10.1

**Comment by chrisguerrero** [comment]
+1

`md-input-name` and `required` don't work for me either with 0.10.0

**Comment by alo** [comment]
+1

**Comment by jibiabraham** [comment]
@MetalHexx `md-input-name` is the right attribute to use. 
Additionally, for usage along with `ng-messages`  (when `ng-messages` are added within the autocomplete), you need to use `floating labels` via `md-floating-label`

**Comment by getuliojr** [comment]
I haven´t got this to work and the one that is present in the DEMO page is also not working for the required field. I appreciate if anyone has an idea about it.

**Comment by GustavSt** [comment]
Indeed, When seemingly doing everything right, the error message is shown from start, like @danieladz stated

**Comment by GustavSt** [comment]
I realized I get more weird behavior when trying to have validations when the md-autocomplete is not inside a form. the example of having validation on the md-autocomplete, and using floating label, it is used inside a form. And they are using the name of the form when using ng-messages eg `ng-messages="formName.autoCompleteName.$error"`. I am not able to get it working with a stand alone md-autocomplete without form.

**Comment by 91K00** [comment]
For me it's not working with version 1.0.1, am I the only one ?

http://codepen.io/anon/pen/obWZqP

**Comment by Wykks** [comment]
@91K00 
See #6393

**Comment by Sajan129** [comment]
it seems working if u put     required='true', 

I found the bug is from the line

`$attrs.$observe('required', function (value) { ctrl.isRequired = !!value; });`

it is checking whether the value of required is present or not, but not whethere the required tag is present or not.. thats why there is a bug :)

**Comment by bakhlov** [comment]
not working with version 1.0.6

**Comment by haenig** [comment]
It seems, the $dirty state does not work properly. Instead of just clicking into the input field, you need type something and remove it again. This is inconsistent comparing to other input fields (and wrong as well). In addition, I have to add a sepearte ng-show directive (which is different for default input fields).

```
<div ng-messages="emptyingForm.myInput.$error" ng-show="emptyingForm.myInput.$dirty">
<div ng-message="required">Error message</div>
</div>
```
Hans

**Comment by ThomasBurleson** [comment]
@haenig - please do not comment on closed issues. Please open a new issue.
