### ISSUE TITLE
autocomplete select pop ups when one word is contained in other

### ISSUE THREAD

**Issue by david-gang** [angular/material#1781]
Please look at this plunkr:

http://plnkr.co/edit/F7ljHYFj0AJIzOf6PnZy

I added an imaginary state alabama.
When writing ala and selecting alabama, the select pop ups again which is annoying

**Comment by ktapsoba** [comment]
I believe the createFilterFor function is looking for any options having "indexOf" the searchText. This is why you sill have alabama and alabamabama as options. You could first try to find an exact match and if nothing comes back then find any options with "indexOf". 
That could work for now.

**Comment by gkalpak** [comment]
He he ! Tricky one !

**Comment by umidbekkarimov** [comment]
+1 very annoying, need something to close popup after click/enter

**Comment by r0b-** [comment]
+1
(I already added an issue some days ago https://github.com/angular/material/issues/1732)
