### ISSUE TITLE
Disable pagination - #1189 related issue

### ISSUE THREAD

**Issue by yccteam** [angular/material#1782]
Hi,
I've read #1189 after confronting with this issue (disabling pagination).
I'm now trying to do the same on version 0.8.2, but it doesn't work for me.
Here's a code pen:
http://codepen.io/yccteam/pen/jEpYXE
I don't want pagination whatsoever, but still keep the menu as is (if something needs to be hidden because of it, then let it be hidden).

**Comment by jasonpearson** [comment]
+1
