### ISSUE TITLE
Any way to dynamically change $mdDialog options in its controller?

### ISSUE THREAD

**Issue by hitigon** [angular/material#1786]
need some way to change options after showing a dialog. Looked into the source code, not sure how to access the options of $mdDialog.

Thanks

**Comment by dmackerman** [comment]
Which options were you looking to change?

**Comment by hitigon** [comment]
Like clickOutsideToClose and escapeToClose

**Comment by marcysutton** [comment]
Are you saying the behavior should change after the dialog is open? Why can't those be set before it opens? Just trying to understand your request.

**Comment by hitigon** [comment]
@marcysutton yes. i am trying to disable some behaviors of the dialog (like close the dialog by the escape key) when the dialog is handling an asynchronous call, and enable it after the http request's done.

**Comment by thunghan** [comment]
+1

**Comment by hannesAxiell** [comment]
+1
I specifically look for this to be able to _change the closeTo node_ when cancelling a dialog. In my case I'd like to use the same node as openFrom.
Thx

**Comment by kabalage** [comment]
+1
I'd like my dialog to create a new component in the dom, and closeTo that new element. Part of the problem is changing the closeTo after the dialog opened. (the other is to obtain the newly created element after a digest)

**Comment by jmcpeak** [comment]
+1
My example - a dialog that adds something new to the page:
openFrom - from the button the user clicked (and if user cancels dialog it goes back there)
closeTo - the new element on the page (It the user visibly see to what they just added)

**Comment by nicmae** [comment]
@kabalage @jmcpeak Did you find a trick to close on a newly added DOM element?

**Comment by fbricenho** [comment]
+1, really need this.

**Comment by fbricenho** [comment]
@ThomasBurleson  I still having faith for this to be implemented...

**Comment by kylekatarnls** [comment]
Here is the principle of the work-around I used:

```js
var dialogCloseEnabled = true;

function wrapMethod(method) {
  return function () {
    return dialogCloseEnabled ? method.apply($mdDialog, arguments) : false;
  };
}

$mdDialog.hide = wrapMethod($mdDialog.hide);
$mdDialog.cancel = wrapMethod($mdDialog.cancel);

dialogCloseEnabled = false;
// Escape/click on close/click outside has no effect
dialogCloseEnabled = true;
// Escape/click on close/click outside work again
```

Caution, this is a global approach, all modals will be linked to the globally set dialogCloseEnabled, so reset the setting on each modal destroy.
