### ISSUE TITLE
md-tabs fail when used with ng-include

### ISSUE THREAD

**Issue by hodeyp** [angular/material#1788]
I have a page that adds a number of templates using ng-include. One of the templates includes an md-tabs component.

The tabs are not switching correctly, when selecting the second tab, the first tab remains visible. I have tried the template outside of an ng-include and it works as to should do.

**Comment by bkeil** [comment]
I am having a similar issue, which may be related:

I also have an <md-tabs/> included by an <ng-include/>.  The first tab looks fine.  When I switch to the second tab, however, none of the {{ }} templates have been evaluated.  They appear raw, curly braces and all.

**Comment by robertmesserle** [comment]
@hodeyp @bkeil I suspect this may be resolved by #1944.  Can one of you provide some sort of online sample demonstrating the issue so that I can confirm?

**Comment by hodeyp** [comment]
http://plnkr.co/edit/I85YVVW1Oik5Cwu8ii5z?p=info

**Comment by bkeil** [comment]
Here's a nice simple example with my problem: http://plnkr.co/edit/A7UaSk1vvIo9svw9JkIt

All of the tabs are working except for "Outer B » Inner B".

**Comment by robertmesserle** [comment]
This is resolved in the latest tabs rewrite - should be in master sometime next week.

**Comment by hodeyp** [comment]
awesome, thanks!
