### ISSUE TITLE
Material Tab external content ones is fit which version of angulars.Js?

### ISSUE THREAD

**Issue by tesshsu** [angular/material#1789]
Hi Experts:
              I had try use Material Tab (external content one) in the App I had write with AngularJS v1.3.14, and I download material with Bower: bower install angular-material#master (to get the most recent version). Then:
1. the other data write with angulars.js are working well
2. but the Material Tab is not working...

Is anyone knowing that which material version I had to download in order to fix this problem?
Appreciate your kindly help!!

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.
