### ISSUE TITLE
mdGesture service shouldHijackClicks block is not atomic with registering click event handlers

### ISSUE THREAD

**Issue by alexbr** [angular/material#1791]
### Steps
* Use a mobile device or spoof the user-agent header as a mobile device
* Load the angular material script and supporting scripts
* *Do not* load the angular material (ngMaterial) module

### Description
As soon as the angular-material script is loaded, it hijacks clicks for mobile devices. But it doesn't register the handlers for clicks (and other gestures) until the angular material module is loaded.

This causes problems when, for instance, an application preloads the angular material scripts but doesn't load the angular material module.

These two items should be atomic. Click events should not be intercepted until the handlers have been setup.

See this plunker I setup to show this and another bug I'm reporting: #1792. Test instructions are in the plunker.

http://plnkr.co/edit/RtuCcILOWvlQIWs89U6n?p=preview

**Comment by ThomasBurleson** [comment]
@alexbr - totally agree. In fact I think the gesture code should only be configured in the `angular.module('ngMaterial').runs( function(){ .... });` phase.
