### ISSUE TITLE
mdGesture hijacked link click events don't work with plain old anchor tags

### ISSUE THREAD

**Issue by alexbr** [angular/material#1792]
### Preconditions
* Use a mobile device (or sending a mobile user-agent header)
* jQuery is loaded

### Bug
When mdGesture hijacks a link click event and [decides the event should continue propagating](https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js#L27), it passes the event to jQueryDispatchEvent which [calls jQuery's trigger method](https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js#L380). This ultimately fails because [jQuery does not fire native click events](https://github.com/jquery/jquery/blob/master/src/event.js#L586). This ultimately means that clicking on simple anchor links like ```<a href="http://some.site.com">Link</a>``` doesn't work at all.

See my plunker example here to reproduce: http://plnkr.co/edit/RtuCcILOWvlQIWs89U6n?p=preview

**Comment by sime** [comment]
I can replicate this without jQuery: http://codepen.io/anon/pen/zxejXe

**Comment by ThomasBurleson** [comment]
Still present in latest code from master. See [CodePen](http://codepen.io/ThomasBurleson/pen/MYRvwy?editors=100)

**Comment by NorikDavtian** [comment]
+1

Disabling `shouldHijackClicks` event fixes this as a temporary fix..

**Comment by kennethcachia** [comment]
This should be fixed.

Demo with jQuery: http://codepen.io/kennethcachia/pen/azgwWg
Demo without jQuery: http://codepen.io/kennethcachia/pen/EaBQwL

**Comment by ThomasBurleson** [comment]
Fixed with 2c57a8289f73265ca41fc8b2fbbe173a80073caa

**Comment by sime** [comment]
Works for me on Chrome DevTools device mode and Safari in iOS Simulator.

Cheers!
