### ISSUE TITLE
Material design on ng-message-exp

### ISSUE THREAD

**Issue by jolafrite** [angular/material#1793]
Hi

Since I think v1.4 of angular js ngMessage as been improve with the new directive "ng-message-exp"
It works great and does what is expected
Problem, this new directive is not included in angular material and will not add any style.
Would be good if it can be corrected in the new version

Thanks

**Comment by jolafrite** [comment]
Great thanks

**Comment by bopm** [comment]
:+1:

**Comment by forcewill** [comment]
![image](https://cloud.githubusercontent.com/assets/759006/8573520/ec4cb2f6-2589-11e5-8256-aa228496b2cb.png)

**Comment by prasannapattam** [comment]
+1
When is this getting released?
