### ISSUE TITLE
toolbar examples

### ISSUE THREAD

**Issue by calidion** [angular/material#1796]
on how to add buttons and actions, like 
http://demos.jquerymobile.com/1.4.5/toolbar/

**Comment by erslater** [comment]
From the demos at https://material.angularjs.org/#/api/material.components.toolbar/directive/mdToolbar
    <md-toolbar>
        <div class="md-toolbar-tools">
            <span>My App's Title</span>
            
            <span flex></span>
            <md-button>
              Right Bar Button
            </md-button>
        </div>
    </md-toolbar>

**Comment by calidion** [comment]
how to add back button like this?
http://demos.jquerymobile.com/1.4.5/toolbar-fixed-fullscreen/

**Comment by calidion** [comment]
this kind would be very appealing:
 http://ui.lumapps.com/css/toolbars

**Comment by calidion** [comment]
@erslater thanks, i managed to come up one, but it's far from good:)
