### ISSUE TITLE
i need to create view with 3 cards in large devices

### ISSUE THREAD

**Issue by janarthananrajan** [angular/material#1797]
i need to create view with 3 cards in large devices and it has to wrap . Please can any one help me

**Comment by erslater** [comment]
I have been playing around with this and I dont think it currently supports Cards in a list.  At least I couldnt get them to display correctly.  I have used md-grid-list with md-grid-tile and then added my own styles to get the content to appear as a Card.

Check the demos at: https://material.angularjs.org/#/api/material.components.gridList/directive/mdGridList

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
