### ISSUE TITLE
Box sizing for border-box

### ISSUE THREAD

**Issue by mikehaas763** [angular/material#180]
In at least 'demo1', bootstrap 3 is included. So there is a style on every element of

``` css
* { box-sizing: border-box; }
```

I'm just trying to collect more information on what's going to happen with Angular Material as far as related styling goes and any conflicts that may come out of having border-box on every element.

Does anyone have any related input?

**Comment by mgol** [comment]
This was related to Bootstrap but I'd still be interested if Angular Material works fine with `* { box-sizing: border-box; }` as I tend to use it in my projects (and I'm not the only one with such a habit).

**Comment by Akaryatrh** [comment]
@mgol Well it doesn't, at least for the date-picker: http://codepen.io/anon/pen/KzEoQy
(click on any datepicker arrow, calendar component must have enough space to be fully displayed in order to see the bug).  

Should I open an issue for this case ? It looks quite critical while a lot of people use the global `border-box` rule.

**Comment by mgol** [comment]
@Akaryatrh Yes, please open a new issue, I think it's a bug.

**Comment by Akaryatrh** [comment]
@mgol Issue opened here: https://github.com/angular/material/issues/8547

**Comment by kayvij** [comment]
md-select has the same issue (displays weird backgrounds) when border-box is used on *

e.g.
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

Therefore, using bootstrap along with angular-material causes this issue. 

The following fixes it but screws up bootstrap styling.
* {
    -webkit-box-sizing: unset;
    -moz-box-sizing: unset;
    box-sizing: unset;
}

**Comment by stnor** [comment]
If one has a global box-sizing rule, coming from botostrap or otherwise, consider changing it to this: https://stackoverflow.com/questions/63237057/css-apply-css-style-to-everything-except-material-angular
