### ISSUE TITLE
md-switch looks different when using ng-bind attribute

### ISSUE THREAD

**Issue by birdcw** [angular/material#1800]
When using ng-bind instead of double curly braces, md-switch appears as plain text. It functions correctly when clicked, but is missing all the switch styling. I've tested this in Chrome. Would be a nice feature to be able to use ng-bind in place of curlies.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by birdcw** [comment]
http://embed.plnkr.co/BVor32/preview

@ThomasBuleson the switches are definitely cool, but one of these looks so much better than the other!

**Comment by marcysutton** [comment]
Hi, you can use ng-bind on a child span and it works fine:
```html
<md-switch ng-model="truthyA">
    <span ng-bind="truthyA ? 'TRUE' : 'FALSE'"></span>
</md-switch>
```
