### ISSUE TITLE
Layout-align-small

### ISSUE THREAD

**Issue by alifarahani** [angular/material#1802]
Hi I'm new to Angular material design and have this issue:

When my parent div has a layout-align-sm the inner md-auto-complete disappears in small screens....

here is the code:

div         class="tweek" layout="row" layout-sm="column" layout-margin layout-align-sm="start center">
    md-autocomplete md-no-cache="false" md-selected-item="entityId" md-search-text="ctrl.searchTextId" md-items="item in querySearchId(ctrl.searchTextId)" md-item-text="item.display" placeholder="Enter Entity Name" flex="20" md-selected-item-change="showEntity(entityId)" layout-margin flex-sm="100">
        span          md-highlight-text="ctrl.searchText">{{item.display}}         /span>
    </md-autocomplete>
/div

if I remove the layout-align-small then everything works fine . . .

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.
