### ISSUE TITLE
Why $mdDialog.content() don't support html code?

### ISSUE THREAD

**Issue by luozhihua** [angular/material#1805]
If I only want to show a image using $mdDialog, I think the best way to do this is pass a piece of html code into $mdDialog.content(), Instead of using a separate template files

**Comment by carab** [comment]
Hi,

I didn't try, but can't you use this to provide an inline template ?

```javascript
$mdDialog.show({
      controller: DialogController,
      template: '<img src="" alt="">'
    })
```

**Comment by ThomasBurleson** [comment]
See [$mdDialog Docs](https://material.angularjs.org/#/api/material.components.dialog/service/$mdDialog)

*  `$mdDialog.show().template = '<img src="" alt="">'`
*  `$mdDialog.show({template : '<img src="" alt="">'})`
*  `$mdDialog.show(). templateUrl = '/templates/myAlert.html'>'`
*  `$mdDialog.show({templateUrl : '/templates/myAlert.html'})`

**Comment by luozhihua** [comment]
@ThomasBurleson Thanks!
