### ISSUE TITLE
Google maps marker click doesn't show info window after mdGestures is added (version >= 0.7.1). Is there a way to disable mdGestures for a <div> ?

### ISSUE THREAD

**Issue by myellepeddy** [angular/material#1808]

**Comment by iaaguilera** [comment]
I also am having this problem with an Esri map and an info window.

**Comment by ThomasBurleson** [comment]
For mobile solutions that are also using jQuery, you can now use $mdGestureProvider in 
```js
   app = angular.module('MyApp', ['ngMaterial'])
      .config(function( $mdGestureProvider ) {
          $mdGestureProvider.skipClickHijack();
      });
```
This will configure $mdGesture to **not** intercept clicks (stop propagation and prevent defaults).

**Comment by adam-back** [comment]
Is this documented? This seriously just saved my @$$.
