### ISSUE TITLE
mdSelect : scroll not working on touch device when fixed to bottom 

### ISSUE THREAD

**Issue by Furqankhanzada** [angular/material#1810]
I can't scroll on touch device to see hidden options. select box is fixed with bottom and opens from bottom to top.

```
        <md-select ng-model="selected.stats" placeholder="Select Stats">
          <md-option ng-value="0">Select Stats</md-option>
          <md-option ng-value="1">Select Stats</md-option>
          <md-option ng-value="2">Select Stats</md-option>
          <md-option ng-value="3">Select Stats</md-option>
          <md-option ng-value="4">Select Stats</md-option>
          <md-option ng-value="5">Select Stats</md-option>
          <md-option ng-value="6">Select Stats</md-option>
          <md-option ng-value="7">Select Stats</md-option>
          <md-option ng-value="8">Select Stats</md-option>
        </md-select>

```

**Comment by mib4fun** [comment]
Hi, can u provide a plunker for this ?

**Comment by Furqankhanzada** [comment]
I am building hybrid app using Cordova. i can provide you .apk through email so you see the problem or repo access if you need.

there is 2 issues :

1) Not scrolling 
2) can't select last item (when we try to select last item select box close and reopen)

as a quick solution i removed ```max-height``` form ```md-select-menu``` and ```md-select-menu md-content``` for avoiding scroll.

but second issue is serious. let me know your thought.

**Comment by rschmukler** [comment]
Can you clarify what you mean by "select box is fixed with bottom"? Could you re-create an example in a plunker or codepen?

**Comment by rschmukler** [comment]
Punting to 0.10.0 until a demo is provided.

**Comment by rschmukler** [comment]
Closing. Feel free to open a new issue if it persists.
