### ISSUE TITLE
Way to change input label height

### ISSUE THREAD

**Issue by lblyweert** [angular/material#1811]
Hi,

I'm building a custom angular-material build thanks to gulp in order to display a custom md-input-container.

So basically I've created a custom .scss file in src/components/input.
I can override default scss variables this way : 

``` $input-error-height:0px; ```

Problem is I'm unable to customize md-input-container height.

Below are related scss variables.

```
$input-container-padding: 2px !default;

$input-label-default-offset: 24px !default;
$input-label-default-scale: 1.0 !default;
$input-label-float-offset: 4px !default;
$input-label-float-scale: 0.75 !default;

$input-placeholder-offset: $input-label-default-offset !default;

$input-border-width-default: 1px !default;
$input-border-width-focused: 2px !default;
$input-line-height: 26px !default;
$input-padding-top: 2px !default;

$input-error-font-size: 12px !default;
$input-error-height: 24px !default;
```

How can I achieve this?
Thank you.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
