### ISSUE TITLE
md-input-container textarea height

### ISSUE THREAD

**Issue by PDSBGreg** [angular/material#1812]
This is likely already reported (or a known bug), but I can't find it with my poor searching abilities.

In IE11 and Firefox 36.0.1, the textarea in md-input-container does not resize to fit the content. I haven't tried in Safari or mobile browsers, but Chrome and Opera (PC Windows 7) work fine.

See the "Biography" input on
https://material.angularjs.org/#/demo/material.components.input

**Comment by sime** [comment]
I have just come upon this issue as well on Firefox on OS X.

Not an issue on Safari or iOS Safari.

**Comment by sime** [comment]
Actually this looks like a duplicate of #1812

**Comment by sime** [comment]
Whoops I mean #1156

**Comment by PDSBGreg** [comment]
Sure is. Thanks for finding that for me.

**Comment by sime** [comment]
Best to close this issue then! :)

**Comment by PDSBGreg** [comment]
Ah, sorry about that.
