### ISSUE TITLE
layout-margin causes scrollbar when using flex values

### ISSUE THREAD

**Issue by erslater** [angular/material#1814]
If I set flex values that total to 100 and use layout-margin it causes a scrollbar to appear.  Ideally the width should take the margin into account.

    <div layout="row" layout-margin>
        <div flex="50" style="border:1px solid black">Flex 50</div>
        <div flex="25" style="border:1px solid black">Flex 25</div>
        <div flex="25" style="border:1px solid black">Flex 25</div>
    </div>

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by chr22** [comment]
It seems that it is the margin between the elements that isn't considered in the final width, as seen on this CodePen: http://codepen.io/chr22/pen/vEvbKx

The first row has margin between the elements, and here is the problem. The second row hasn't any margin and here the final width is correct.

**Comment by adamduren** [comment]
We're encountering this in our own project.

[Here's](http://codepen.io/anon/pen/vOEPyz) a CodePen demonstrating the issue using borders to show the overflow.

**Comment by ninety7** [comment]
I think the two Demos on CodePen show the demo. I'm also having issues when setting the container with layout-wrap. Will we have a fix for this?

**Comment by adamduren** [comment]
@ThomasBurleson If the demos are sufficient can we update the "Demo Needed" label?

**Comment by Asoseil** [comment]
+1

**Comment by ThomasBurleson** [comment]
@adamduren - These CodePens are helpful. And with the recent changes to Layout (@see SHA 5e6aa6893ec77582268d4e74e828f34dbab8b954), layout performance and usages are faster and easier.

I do not, however, see the team fixing this issue; as a fix is dependent upon the number of sibling elements and their possible flex values.  A PR to enhance Layouts (to support/fix this issue) would be a welcomed addition.

**Comment by helmuthva** [comment]
@ThomasBurleson: despite you having closed this - is there a known workaround for the margin produced by layout-margin not considered in the final width thus pushing a child out of the envelope?

**Comment by ferchoman09** [comment]
I have the same Problem, Any solution?
