### ISSUE TITLE
mdSelect - md-select-icon is not flush with the end of md-select

### ISSUE THREAD

**Issue by mtraynham** [angular/material#1815]
Likely caused by https://github.com/angular/material/commit/59e30a392ed7f0dc43ec71db22b60fcaa800ba7e

![screenshot from 2015-03-06 15 13 12](https://cloud.githubusercontent.com/assets/5741321/6535489/63c1fd9c-c413-11e4-80ec-37364f45c167.png)
![screenshot from 2015-03-06 15 13 20](https://cloud.githubusercontent.com/assets/5741321/6535495/666b41e8-c413-11e4-9643-3017f38a9280.png)

**Comment by chenzhenxi** [comment]
+1

**Comment by marcramser** [comment]
Workaround: 

.md-select-label .md-select-icon {
   position: absolute;
   right: 10px;
}

**Comment by mtraynham** [comment]
@marcramser From the commit, it looks like this broke to add the *right to left* feature.  I'm not sure if *always* right with `right: 10px` is desired.

**Comment by mtraynham** [comment]
Lgtm thanks!
