### ISSUE TITLE
How to apply tab-like ripple effect?

### ISSUE THREAD

**Issue by aeroxy** [angular/material#1819]
Is there an attribute allow us to apply tab-like ripple effect?

https://material.angularjs.org/#/demo/material.components.tabs

**Comment by carab** [comment]
I used `md-ink-ripple` directive as an attribute on the element on which I want an ink ripple effect.
It works like a charm :)

**Comment by aeroxy** [comment]
@carab I am familiar with `md-ink-ripple`. Did you take a look at the **tab-like** ripple effect in the link?

**Comment by carab** [comment]
Do you mean the animation between each tab pane ?

**Comment by aeroxy** [comment]
@carab No, I don't mean ink bar. If you watch the animation of the ink ripple on tabs you will notice the ripple comes out and then break down from the center. Similar to those of double ripple only the second ripple makes the first ripple transparent from inside.

**Comment by carab** [comment]
Okay I see it, but indeed I don't know how to replicate this...

**Comment by aeroxy** [comment]
@carab It's hard I literally broke my head over this. XD
