### ISSUE TITLE
Is there a way to select a tab programatically?

### ISSUE THREAD

**Issue by nikhildev** [angular/material#182]
Hi,

This is how I have implemented tab in my application

&lt;material-tabs selected="selectedTab" center&gt;<br />
    &lt;material-tab label="first"&gt;&lt;/material-tab&gt;<br />
    &lt;material-tab label="second"&gt;&lt;/material-tab&gt;<br />
&lt;/material-tabs&gt;<br />
&lt;div class="animate-switch-container" ng-switch on="selectedTab"&gt;<br />
<br />
    &lt;div class="animate-switch" ng-switch-when="0"&gt;<br />
    Some content<br />
    &lt;/div&gt;<br />
<br />
    <br />
    &lt;div class="animate-switch" ng-switch-when="1"&gt;<br />
    Some content<br />
    &lt;/div&gt;

When I try to set the selectedTab variable in my controller, the tab does not move to the one selected. Is this the intended behaviour or am I missing something?

**Comment by warpdesign** [comment]
If somewhere stumbles upon this one, that's `md-selected` and not `selected`.
