### ISSUE TITLE
mdBottomSheet:  getting "TypeError: undefined is not a function" when trying to $mdBottomSheet.show 

### ISSUE THREAD

**Issue by johnlim5847** [angular/material#1821]
hey guys I have follow exactly what the demo page shows however i still getting this error when i try to open a bottom sheet. i'm using angularjs 1.3.14 and i have try on 1.3.6 as well.besides, i have follow the instruction on Getting started page to Including Angular Material and its dependencies 
```javascript
angular.module('app').controller('MasterCtrl', [
  '$http',
  '$scope',
  '$location',
  '$rootScope',
  '$timeout',
  '$mdBottomSheet',
  function ($http, $scope, $location, $rootScope, $mdBottomSheet, $timeout) {
      $scope.alert = '';
  $scope.showGridBottomSheet = function($event) {
    $scope.alert = '';
    $mdBottomSheet.show({ <-- line 37
      templateUrl: 'bottom-sheet-grid-template.html',
      controller: 'GridBottomSheetCtrl',
      targetEvent: $event
    }).then(function(clickedItem) {
      $scope.alert = clickedItem.name + ' clicked!';
    });
  };
  }
]);
```
and this is the error
![selection_002](https://cloud.githubusercontent.com/assets/3675946/6540524/1648090c-c4dc-11e4-8a42-e0fd73bf4e0a.png)

your help is appreciated, thanks !

**Comment by danwkennedy** [comment]
You've switched $timeout and $mdBottomSheet between your injector definition and your function definition.

**Comment by johnlim5847** [comment]
@danwkennedy  thank for pointing that out however i'm having different error now when i try to open the bottomsheet

![selection_003](https://cloud.githubusercontent.com/assets/3675946/6541993/cd73c0f0-c525-11e4-8317-aca6a3277bae.png)

can you teach me how to debug the error above ? 

```javascript 
angular.module('app').controller('MasterCtrl', [
  '$http',
  '$scope',
  '$location',
  '$rootScope',
  '$timeout',
  '$mdBottomSheet',
  function ($http, $scope, $location, $rootScope, $timeout, $mdBottomSheet) {
      $scope.alert = '';
  $scope.showGridBottomSheet = function($event) {
    $scope.alert = '';
    $mdBottomSheet.show({
      templateUrl: 'bottom-sheet-grid-template.html',
      controller: 'GridBottomSheetCtrl',
      targetEvent: $event
    }).then(function(clickedItem) {
      $scope.alert = clickedItem.name + ' clicked!';
    });
  };
  }
]);
angular.module('app').controller('GridBottomSheetCtrl', [
  '$scope',
  '$mdBottomSheet',
  function ($scope,$mdBottomSheet) {
    $scope.items = [
    { name: 'Hangout', icon: 'hangout' },
    { name: 'Mail', icon: 'mail' },
    { name: 'Message', icon: 'message' },
    { name: 'Copy', icon: 'copy' },
    { name: 'Facebook', icon: 'facebook' },
    { name: 'Twitter', icon: 'twitter' },
  ];
  $scope.listItemClick = function($index) {
    var clickedItem = $scope.items[$index];
    $mdBottomSheet.hide(clickedItem);
  };
  }
]);
```

**Comment by ilanbiala** [comment]
Is this all the code?

**Comment by danwkennedy** [comment]
I can't see anything off hand. Maybe switch to the non minified version of material to see where it's failing in the library. You could name each of your anonymous functions to see which one is failing.

**Comment by johnlim5847** [comment]
@ilanbiala   here's my full code 

<b> HTML(master.html this is the master page contain all the js and css library ) </b>
```html 
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/angular_material/0.8.2/angular-material.min.css">
<div ng-controller="MasterCtrl">
<body>
<div class="bottom-sheet-demo inset" layout="column" layout-sm="row" layout-align="center">
    <md-button class="md-primary" ng-click="showGridBottomSheet($event)">
      Show as Grid
    </md-button>
  </div>
  <br/>
  <b layout="row" layout-align="center center" layout-margin>
    {{alert}}
  </b>
  <div ng-view=""></div>
</body>
</div>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-animate.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-aria.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-route.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-cookies.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-sanitize.min.js"></script>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-messages.min.js"></script>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/angular_material/0.8.2/angular-material.js"></script>
<script type="text/javascript" src="/static/javascripts/app.js"></script>
<script type="text/javascript" src="/static/javascripts/controllers.js"></script>
```
<b>app.js</b>

```javascript
var app = angular.module('app',['ngMaterial','ngRoute','ngSanitize','ngCookies','ngAnimate']).
 config(['$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
    $routeProvider.
      when('/', {
        templateUrl: '/static/views/main.html',
        controller: 'IndexCtrl'
      }).
      when('/signin',{
      	templateUrl: '/static/views/signin.html',
        controller: 'SignInCtrl'
      }).
      when('/signup',{
      	templateUrl: '/static/views/signup.html',
        controller: 'SignUpCtrl'
      }).
      otherwise({
        templateUrl: '/static/views/error.html'
      });
    $locationProvider.html5Mode({
      enabled: true,
      requireBase: false
    });
    
  }]);
```
<b> controller.js </b>
```javascript
angular.module('app').controller('MasterCtrl', [
  '$http',
  '$scope',
  '$location',
  '$rootScope',
  '$timeout',
  '$mdBottomSheet',
  function ($http, $scope, $location, $rootScope, $timeout, $mdBottomSheet) {
      $scope.alert = '';
  $scope.showGridBottomSheet = function($event) {
    $scope.alert = '';
    $mdBottomSheet.show({
      templateUrl: 'bottom-sheet-grid-template.html',
      controller: 'GridBottomSheetCtrl',
      targetEvent: $event
    }).then(function(clickedItem) {
      $scope.alert = clickedItem.name + ' clicked!';
    });
  };
  }
]);
angular.module('app').controller('GridBottomSheetCtrl', [
  '$scope',
  '$mdBottomSheet',
  function ($scope,$mdBottomSheet) {
    $scope.items = [
    { name: 'Hangout', icon: 'hangout' },
    { name: 'Mail', icon: 'mail' },
    { name: 'Message', icon: 'message' },
    { name: 'Copy', icon: 'copy' },
    { name: 'Facebook', icon: 'facebook' },
    { name: 'Twitter', icon: 'twitter' },
  ];
  $scope.listItemClick = function($index) {
    var clickedItem = $scope.items[$index];
    $mdBottomSheet.hide(clickedItem);
  };
  }
]);
```

**Comment by johnlim5847** [comment]
@danwkennedy  here's what i got from non minified version of material, i don't really get it though . what's wrong with the 'button' ? 

![selection_004](https://cloud.githubusercontent.com/assets/3675946/6545653/3546a8ae-c5cc-11e4-9d0a-379c846e4892.png)
![selection_005](https://cloud.githubusercontent.com/assets/3675946/6545654/38bad4ce-c5cc-11e4-8b18-9b5c11d6f574.png)

**Comment by ThomasBurleson** [comment]
@johnlim5847 - Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by srdone** [comment]
I'm seeing this issue in my code as well. For some reason the `element` object in the `onshow` function doesn't have the expected method: `element[0].query selector`. I'm trying to figure out why in my own code, and if I can put together a plunk that demonstrates this I will place it here.

**Comment by srdone** [comment]
I am completely baffled. I don't know why it doesn't work in my code, but it works just fine in this plunk:

http://plnkr.co/edit/kEK1v5?p=preview

**Comment by srdone** [comment]
So it turns out you can't put a comment at the top of the template file, because `element.[0]` grabs the root element of the template, and apparently a comment is recognized as such. I removed the comment from the top of my template and it worked.

Is this how it is supposed to work? Or should we be able to add comments at the top of the template file?

Contents of `element` on the working plunk (which didn't have a comment):
![screenshot 2015-03-18 11 21 59](https://cloud.githubusercontent.com/assets/2849953/6715065/b22d4642-cd61-11e4-9412-678f3a8c19ce.png)

Contents of element in my broken app (which did):
![screenshot 2015-03-18 11 22 36](https://cloud.githubusercontent.com/assets/2849953/6715068/b65ac816-cd61-11e4-8c20-4a015e6f64c7.png)

My original code (once I removed the comment at the top, it worked):
![screenshot 2015-03-18 11 22 55](https://cloud.githubusercontent.com/assets/2849953/6715072/ba1be5f2-cd61-11e4-9dca-8796a4d30cf4.png)

**Comment by srdone** [comment]
@johnlim5847 What does your `bottom-sheet-grid-template.html` file look like?

**Comment by ftaljaard** [comment]
Im stuck with same issue, no comments in my template.

**Comment by srdone** [comment]
@ftaljaard: what does your template look like?  Is md-bottom sheet the root element?

**Comment by ftaljaard** [comment]
![capture](https://cloud.githubusercontent.com/assets/8086774/6730523/246be88c-ce46-11e4-9330-e75c53247614.PNG)

**Comment by srdone** [comment]
@ftaljaard Can you provide a plunk or codepen that reproduces the error?

**Comment by schnogz** [comment]
I am having the same issue, but i am trying to set options.scope when calling $mdBottomSheet.show() According to the [documentation](https://material.angularjs.org/#/api/material.components.bottomSheet/service/$mdBottomSheet) i can just pass an object: 

>scope - {object=}: the scope to link the template / controller to. If none is specified, it will create a new >child scope. This scope will be destroyed when the bottom sheet is removed unless preserveScope is >set to true.

Please take a look at the following plunkr: http://plnkr.co/edit/J97X5a7l6tpiEItlY2g2?p=preview

**Comment by johnlim5847** [comment]
Guys, I resolved this issue by correcting my bottom-sheet-template route at
the templateUrl. Sorry for the late reply

**Comment by ftaljaard** [comment]
Hallo, solve my problem. The "item list" was created dynamically by the controller this same controller "open" the list and uses the same controller. When you assign the controller a new instance gets created so my "item list" was lost. Resolved it by shared service.
