### ISSUE TITLE
mdSelect does not fire ng-change when md-on-open is set

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1822]
When the md-on-open attribute is set the md-select does not call the ng-change if it set.

ng-change is called properly otherwise.

<md-select ng-model="selection" md-on-open="loadData()" ng-change="changeSelection()">

**Comment by rschmukler** [comment]
This lead me to find a bug where non async md-on-shows resulted in the spinner to not hide. But, the events are firing fine in [this demo](https://jsfiddle.net/rschmukler/tynf7r9f/)

**Comment by SushantKadam008** [comment]
@rschmukler : I am facing similar issue.
ng-change is fired every time I open the dropdown.
