### ISSUE TITLE
Grid List rendering issue on Android webview & various browsers

### ISSUE THREAD

**Issue by TheMangoTrain** [angular/material#1824]
Using the Material demo as a sample, Grid List doesn't seem to render fully on first-load in Android webview & various Android browsers, when the device is held in standard portrait way. 

Reproduce:
1 - Visit https://material.angularjs.org/#/demo/material.components.gridList on an Android using Firefox (36), Chrome (40) or recent Opera, holding the device in portrait state. FYI  I only have access to a Samsung Galaxy S4 Mini.

2 - Notice the first two variants for the Grid List demo ("Basic Usage" and "Dynamic Tiles") appear empty. Keep scrolling and you'll see the third variant ("Responsive Usage") seems to appear normally.
Turn the device to landscape (which triggers the left sidebar menu) and the first two Grid List variants become visible. Turn the device back to portrait and the changes hold.

Additionally: Using grid list in my hybrid app, simply going to landscape didn't work for me because my left sidebar is set to not automatically fly out when going to landscape. I have to rotate the device to landscape and manually trigger my left sidebar menu. Doing either step alone isn't enough. Furthermore, if I load the app in portrait mode, and simply trigger the left sidebar (ie never go to landscape), this isn't enough either.

Bottomline: Rotating the device to landscape + triggering the left sidebar makes the grid list fully render.

**Comment by ThomasBurleson** [comment]
@TheMangoTrain - Can you test with latest 33049cff96cd643e76159fc2d72cbd9fb911245c

**Comment by shyndman** [comment]
I think this is related to some bugs in the demo code. I'm taking a look.
