### ISSUE TITLE
Coloring non-md elements

### ISSUE THREAD

**Issue by ppallesws** [angular/material#1825]
Is this something that will ever happen?

https://stackoverflow.com/questions/28487327/how-to-set-text-color-in-angular-material

Or is there any easy way to implement this using sass I'm overlooking.

Thanks!

**Comment by Frank3K** [comment]
Possibly related: #1269

**Comment by marcysutton** [comment]
Yep, the work being done in #1269 will cover this, so I'm closing as a duplicate.
