### ISSUE TITLE
md-autocomplete placeholder should be an expression too

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1828]
The placeholder should be an expression to dynamically set the name with an angular expression.
placeholder="{{'LABEL_NAME' | translate}}" 
Currently this feature inhibits the use in multi-language environments.

**Comment by david-gang** [comment]
:+1:

**Comment by robertmesserle** [comment]
Isn't this already supported?

http://codepen.io/robertmesserle/pen/72185ea178757d282e5862fcc22399dd

**Comment by robertmesserle** [comment]
@kschwidder Closing for now, please re-open with a CodePen sample if you have a specific use-case that I have missed.
