### ISSUE TITLE
md-backdrop not properly painted when browser content is scrolled

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1830]
When the browser content has been scrolled and a dialog is displayed the backdrop is not properly painted in firefox/ie/chrome/safari

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by kschwidder** [comment]
Content is a md-list with 20 items. When you begin to scroll down the backdrop is not reflecting the scroll position too. This seems to be the same case as what has been fixed with the md-dialog positioning.

![backdrop ok when not scolled](https://cloud.githubusercontent.com/assets/3265624/6601440/ff13a858-c815-11e4-8d22-cec3e8696fa8.png)

![backdrop wrong after scrolling](https://cloud.githubusercontent.com/assets/3265624/6601442/03d76f1e-c816-11e4-8dc9-4f4a8f4a05e9.png)

**Comment by kschwidder** [comment]
Tried to compile a demo plnkr.co/edit/CoSue6p4tlAGZgQPRE2s but it does not work properly with dialog alignment in Firefox and IE. 
When is the fix for the alignment committed ?? After that I will check again with the backdrop painting.
On my life-site you can see behaviour if you would like to see it.

**Comment by marcysutton** [comment]
@kschwidder there should be fixes in for dialog alignment in Firefox and IE now, can you see if scrolling is still affected (and post a demo)? Thanks.

**Comment by david-gang** [comment]
The same happens also with sidenavs and scrolled content

**Comment by ivanhtp** [comment]
This is easily solvable changing the md-backdrop from absolute to fixed and the body class .md-dialog-is-showing from overflow hidden to visible.
