### ISSUE TITLE
md-sidenav: main content flickers when opening in Windows Phone 8.1 (WP8.1)

### ISSUE THREAD

**Issue by rdesimone** [angular/material#1831]
When opening the sidenav, the main content (not sidenav content) flickers. You can check this plunk:

http://plnkr.co/edit/mCGnFKisaCslRmB0Y6SW?p=preview

Additionally the menu button remains activated (this I noticed also in Chrome and iOS).

AM: 0.8.3
WP 8.10.14219.341
Nokia 820
Cordova "windows" platform and IE

**Comment by marcysutton** [comment]
We would really appreciate any help the community can provide on WP issues. You can read about our position on Windows Phone here: https://github.com/angular/material/issues/1905#issuecomment-81849531

Regarding the buttons, this is a known issue: https://github.com/angular/material/pull/1594

**Comment by rdesimone** [comment]
@marcysutton #1594 (button stays highlighted) is closed but the issue still exists. I downloaded 0.9 RC1 and checked also the plunk.

**Comment by jelbourn** [comment]
@rdesimone are you still seeing this issue?

**Comment by topherfangio** [comment]
I am currently downloading the Windows Phone emulator to see if I can debug this. I will update if I find any new information or if I can find an easy fix.
