### ISSUE TITLE
md-button: md-raised's "hover" status should not raise higher ("pressed" should)

### ISSUE THREAD

**Issue by albertboada** [angular/material#1832]
Right now (https://material.angularjs.org/#/demo/material.components.button), raised *md-button*s raise higher when *hovered*.
However, according to the public Material Design guidelines, raising only happens when you *press* the button (or when it is *focused*), not when you *hover* it: 

http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B08MbvYZK1iNelZlNW13UVRzUnc/components-buttons-mainbuttons-buttons-motionraised_large_xhdpi.mp4

Sorry if this has been already informed or already scheduled for development, could not find anything about it.

**Comment by marcysutton** [comment]
I don't see a hover state at all in that video. I think we should get clarification from the UX team on this one, as I have seen internal design docs that show additional raising on focus to differentiate from hover. cc @ThomasBurleson

**Comment by albertboada** [comment]
Exactly, *hover* state has no special style at all anywhere in the spec. Not sure this is intended, so you better internally confirm this!

**Comment by marcysutton** [comment]
Actually it turns out there is no hover state for buttons per the design spec. Shadow raising should only occur on the focus and press actions, with the latter showing more of a shadow.

**Comment by albertboada** [comment]
So the video is trustworthy 100%, right? Because that *focused* state style would solve all the current confusion if implemented (#556, #142), even if it is always activated (not only through keyboard) (#1594).

In the meantime, being able to distinguish *hover* from *focused* status will help a lot, too.

**Comment by marcysutton** [comment]
That issue again....it's a really tough one to solve unfortunately, as the "fix" is pretty hacky. It's a larger issue in browser focus support, IMO. That PR should make it better, but it's not perfect.

There is work to be done on focus/pressed states, so I'll work that in as part of this issue.

**Comment by albertboada** [comment]
Yeah, but I meant... even if #1594 never landed, with these new (and very distinguishable) *hover*/*focused*/*pressed* styles there will be no confusion anymore, so it will not matter if the button stays focused when pressed :)
