### ISSUE TITLE
How to disable ripple (ink) on a parent element without disabling ripple on its children elements?

### ISSUE THREAD

**Issue by aeroxy** [angular/material#1833]
Hi folks,

I use md-no-ink to disable ripple on a parent element and add md-ink-ripple on its children element, but they both lose ripple effects. Is there a method I can only disable the parent element's ripple effect?

**Comment by EladBezalel** [comment]
Can you provide a plunker with your problem?

**Comment by miclaus** [comment]
+1 

Having the same issue, when setting `md-ink-ripple` on `md-list-item`, the parent element `md-list` adopts the same ripple setting.

**Comment by EladBezalel** [comment]
Can you please check if it's happening on HEAD?
[Couldn't](http://codepen.io/EladBezalel/pen/gaBRjN) reproduce

**Comment by EladBezalel** [comment]
Closing for now, if it's still happening please ping and i'll reopen this issue.

**Comment by jgknott** [comment]
+1
```
<md-list md-no-ink>
        <md-list-item md-ink-ripple ng-repeat="item in items">
          <p> {{item}} </p>
        </md-list-item>
</md-list>
```
results in no ink ripple

**Comment by LeoLozes** [comment]
+1 

Besides, I have found no way to add a md-menu to a md-list-item without all the list-item becoming clickable (and with added ripple). 

In the directive documentation it's stated that "The md-list-item component automatically detects if the list item should be clickable.". This is nice, but it would be great if it could be controlled manually. I want the md-menu to deploy when the user clicks on the menu icon on the right, not all the list-item:

![image](https://cloud.githubusercontent.com/assets/11133817/18643043/959c05f0-7ea3-11e6-9312-1a4d13bebcc3.png)

Besides, in the md-list demo, there's a demo (clicking the button to the right will fire the secondary action) showing that it's possible to do with a button, but unfortunately it doesn't seem to work with anything else.
