### ISSUE TITLE
select: ng-options not supported

### ISSUE THREAD

**Issue by leibale** [angular/material#1837]
``` javascript
$scope.options = [1,2,3];
```

``` html
<!-- Working -->
<select ng-options="option in options"></select>
<!-- Not working -->
<md-select ng-options="option in options"></md-select>
```

**Comment by prestonvanloon** [comment]
Try:
```html
<md-select ng-model="thing">
  <md-option ng-repeat="option in options"></md-option>
</md-select>

```

**Comment by leibale** [comment]
i know this option, but i like the second option

**Comment by rschmukler** [comment]
For now this isn't supported.

**Comment by ilanbiala** [comment]
@rschmukler why not just use the ng-options model?

**Comment by rschmukler** [comment]
@ilanbiala I'd accept a PR with it, otherwise `ng-repeat` works and there are higher priorities.

**Comment by rschmukler** [comment]
Reopening, as it is a valid issue for the backlog.

**Comment by faustomorales** [comment]
I see that md-select now uses whatever is supplied in the text node for the md-option as the view value. However, what if I want to preselect an option (say, from the server or a cookie?). An example use case is when we have previously set options that the user may want to change later.

**Comment by skosno** [comment]
Would you target just a "copy" of current "ng-options" directive to support md-select? I assume we would need "md-options" for this as "ng-options" is tightly connected to "select" directive?

**Comment by sherrim** [comment]
By supporting `ng-options`, would this fix the problem with not being about to set the value to null?  Currently, with the following code, choosing the first option will update the model with an empty string instead of null.

```
<md-select ng-model="vm.leaderId">
  <md-option value="">Unknown</md-option>
  <md-option ng-value="leader.id" ng-repeat="leader in vm.leaders">{{leader.name}}</md-option>
</md-select>
```

The AngularJS docs say:
_Optionally, a single hard-coded `<option>` element, with the value set to an empty string, can be nested into the `<select>` element. This element will then represent the null or "not selected" option._

So, using angular's `<select>`, I can select a null value by providing this option:
`<option value="">Unknown</option>`

I would assume that I should be able to do the same with `<md-select><md-option>`

**Comment by sspatrudu** [comment]
+1. 

<md-select> with ng-repeat doesn't update model, whereas ng-options updates the model. Need ng-options for md-select

**Comment by blxstar** [comment]
+1

**Comment by mfjohansson** [comment]
+1

**Comment by chalgoman** [comment]
+1

**Comment by chrislewispac** [comment]
+1

**Comment by frikkievb** [comment]
+1

**Comment by Wingie** [comment]
+1

**Comment by kwypchlo** [comment]
+1

**Comment by yodiyo** [comment]
+1

Yes, I need this! I want the model to update so I can work with the selected option in the controller.

**Comment by Lorthirk** [comment]
+1

**Comment by SKMan** [comment]
+1

**Comment by jml6m** [comment]
+1

**Comment by skosno** [comment]
@sherrim Would it work for you to use ng-value and either just "" to get undefined or ng-value="null" to get null?
http://codepen.io/anon/pen/bVLeQz
(this example is based on codepen from https://github.com/angular/material/issues/3233)

@sspatrudu and @yodiyo - could you guys describe what do you mean by model update? In the above codepen example we can see "ctrl.number" being updated with selected option. Not sure what is not updating?

Generally if anyone has any particular use case that cannot be achieved with ng-repeat and "ng-options" is the only way for you, please contact me. I am trying to gather all information after the talk with @jelbourn to see if we have any real reasons to ask for it.

**Comment by mrdannael** [comment]
Then how should i create one md-select which depends on other md-select without "ng-options", Any idea?

+1

**Comment by skosno** [comment]
@mrdannael Could you give a bit more details? If you have one select that on change updates model that is ng-repeat'ed in second select then it should work fine. Do you have a codepen maybe with your example?

**Comment by mrdannael** [comment]
@skosno I prepared codepen for giving more detailed description of my problem.

[Second dropdown depends on first dropdown](https://codepen.io/anon/pen/JYLQXQ)

I've got table with some values like "Number, Name, Status and Something". And i want to filter for example column "Status" by value "Sleep". So i need to choose Status in first select and then second select model fills with available options for this column "Unknown, Sleep, Car". Second select should be inactive when first is empty. In the future i want to store Filters in database for adding new filters etc. But for now it's not so important for me. I'll deal with that feature later. For now i need selecting and filtering.

**Comment by skosno** [comment]
@mrdannael Do you mean something like this?

https://codepen.io/anon/pen/xwjbwO

**Comment by mrdannael** [comment]
@skosno brilliant! That's what i need! 

Funny thing because i tried something similar with ng-model like you did but i don't know where i made a mistake then.

Thank you.

**Comment by Kriyo** [comment]
@skosno you cured my massive headache thank you!

**Comment by adibas03** [comment]
+1

**Comment by bouwaccount** [comment]
+1

**Comment by sunnee5150** [comment]
+1.  Need to bind my stylish select to a model!

**Comment by pjwalmsley** [comment]
+1

This is a performance issue and an issue when pre-populating data (I believe).

**Comment by johannds** [comment]
+1

**Comment by netoramalho** [comment]
+1

**Comment by dapids** [comment]
+1

**Comment by S8nsick66** [comment]
+1

**Comment by kevin-barrientos** [comment]
+1

**Comment by giacomocariello** [comment]
+1

**Comment by hsiri** [comment]
so no ng-options for md-select? having some performance issue when using md-select in a nested ng-repeat :D

**Comment by Marchrius** [comment]
+1

**Comment by vishnumenon** [comment]
+1

**Comment by arjundevarajan** [comment]
+1

**Comment by TorranceYang** [comment]
+1

**Comment by arjundevarajan** [comment]
+1

**Comment by tayste5000** [comment]
+1

**Comment by Loxos** [comment]
+1

**Comment by davidalekna** [comment]
+1

**Comment by IvanProdaiko94** [comment]
+1

**Comment by maghidini** [comment]
+1

**Comment by ixdcoza** [comment]
+1

**Comment by rodrigodefigueiredo** [comment]
+1

**Comment by nadavhury** [comment]
+1

**Comment by IvanProdaiko94** [comment]
I solved problem like this, maybe it would be helpful for someone)
```
<md-select name="x"
                   ng-model="vm.selectedCoutnry"
                   ng-model-options="{trackBy: '$value.value'}"
                   ng-required>
            <md-option ng-repeat="(index, type) in vm.coutries"
                       ng-value="type"
                       ng-selected="index == 0">
                {{ type.display }}
            </md-option>
</md-select>
```

**Comment by leibale** [comment]
@IvanProdaiko94 https://github.com/angular/material/issues/1837#issuecomment-77941496

**Comment by tom94zoe** [comment]
+1

**Comment by rajiff** [comment]
+1

**Comment by bsliran** [comment]
+1

**Comment by harishkumarchellappa** [comment]
+1

**Comment by naveennavi2106** [comment]
+1

**Comment by mikelbrierly** [comment]
+1

**Comment by tonydolony** [comment]
Yes indeed for example:
```
      <md-select name="country" ng-model="delivery.country">
                                            <md-optgroup label="Countries">
                                                <md-option ng-selected="" ng-value="countyListName.name"
                                                           ng-repeat="countyListName in countryList">                   {{countyListName.name}}
                                                </md-option>
                                            </md-optgroup>
       </md-select>
```
ng-repeat insteed of ng-option pass to ng-model of md-select string , not value - if you will add action to your form and submit it you will see realy strange format in output of country. If there would be ng-option insteed of ng-repeat - than there is no more issue;)

**Comment by SylvainBigonneau** [comment]
+1

[This issue](http://stackoverflow.com/questions/39982002/invalid-not-working-in-ng-if-condition) is fixed when I use a `select` with `ng-options`. I might have to ditch md-select in my app...

**Comment by ayman-alkom** [comment]
-1 ;)

**Comment by lencialam** [comment]
+1

**Comment by yiannakpavy** [comment]
This isn't necessarily a fix (more of a hack), but if you want to retain md-select UI behavior, simply add a <select> element using the appropriate ng-options expression (equivalent to your <md-select> element with ng-repeat expression), and give the <select> element the inline style, "display:none".  In my case, I was deleting a value from the model used to pre-populate md-options. My model would update, but the <md-select> elements with option:selected = deleted value would not update to null (or '').  Adding the <select> element resolved this issue.  Hopefully this works for you all, too.  See example below:

`<select ng-model="facility" class="input-sm form-control" style="width:auto;display:none" ng-options="item.ID as item.Name for item in items"></select>
<md-select ng-model="facility" class="input-sm form-control">
     <md-option ng-bind="item.Name" ng-value="item.ID" ng-repeat="item in items"></md-option>
</md-select>`

**Comment by brandondtran** [comment]
@yiannakpavy Thanks for the work around :)

I hate that this isn't going to be fixed.

**Comment by martinfarrellaptarus** [comment]
+1

**Comment by LuqmanParavetty** [comment]
+1

**Comment by vecernik87** [comment]
+2

**Comment by juanarbol** [comment]
+1

**Comment by stayce** [comment]
+1

**Comment by bbrez1** [comment]
+1

**Comment by ghachey** [comment]
+1

**Comment by luisbello30** [comment]
+1

**Comment by mcdonagj** [comment]
**Doesn't work:**
`<md-select ng-model="thing">
        <md-option ng-repeat="rate in available_rates">{{rate}}</md-option>
</md-select>`

**Works:**
`<select ng-model="thing" ng-options="rate for rate in available_rates"></select>`

Any input on this issue would be greatly appreciated.
As it stands, I can't use `md-select` in my project, which is bothersome.

**Comment by DarkSiderOC** [comment]
The main reason this should be fixed is that rendering a lot of options using ng-repeat causes performance issues, while ng-options woule be optimal. e.g I have to render a list of 20 items each with 2 md sleect both containing 15 options. Needless to say it is very slow.

**Comment by Splaktar** [comment]
I am going to reopen this issue to indicate that we're open to considering PRs from the community that implement this. We will certainly need to be careful that we don't introduce any breaking changes if it needs to go into 1.1.x. But it's possible to do some minor breaking changes for 1.2.0.

Hopefully with the large number of 👍 and comments, someone in this issue will be able to submit a quality PR for this 😄

**Comment by librien** [comment]
+1

**Comment by Splaktar** [comment]
It's been almost a year w/o a community PR to add this. I'm going to close it since we are no longer accepting new features.
