### ISSUE TITLE
mdInputContainer: Class `md-input-has-value` is not persisted with ngModel

### ISSUE THREAD

**Issue by ghpabs** [angular/material#1840]
The `mdInputContainer` directive is checking if the input has a value using [onChange](https://github.com/angular/material/blob/master/src/components/input/input.js#L182) and [onBlur](https://github.com/angular/material/blob/master/src/components/input/input.js#L193) events.

IMHO I think such check should be done when the model changes - perhaps using `.$watch()`.

Thanks

**Comment by ThomasBurleson** [comment]
Since the views are using 2-way databinding, perhaps the checks should accommodate **both** directions (outgoing based on user interactions and incoming based on model changes).

Can you provide a use case with CodePen or Plunkr?

**Comment by jfbenckhuijsen** [comment]
Just created a plunk for this issue (if I understand the issue correctly). AFAICS, this works correctly alread?

http://plnkr.co/edit/MoOXkMmw18559FXJRdDk?p=preview

It does show however, that a disabled input -ate-field still has a placeholder for the date format (mm/dd/yyyy). Most can be hidden by the supplied CSS, however, the slashes remain..

**Comment by jfbenckhuijsen** [comment]
Updated plunk: fix added in CSS to hide the placeholder
