### ISSUE TITLE
toggle side nav closing is not working in ionic framework build in android

### ISSUE THREAD

**Issue by dgrene** [angular/material#1841]
toggle side nav closing is not working in ionic framework build in android. but in browser its working fine.
and also when click it many time then its working only one time. then again i have to click many time

**Comment by atentis** [comment]
You have run into the exact same issue I am having. It is not just side navs but any clicks as far as I can see. Here is my issue on it. 

https://github.com/angular/material/issues/1826

**Comment by MilosStanic** [comment]
I don't know if it's the same thing you guys have, but since upgraded to 0.8.3 my sidenav opens for a moment and automatically closes, both on desktop and in mobile. 
So my app is unusable. :/

**Comment by MilosStanic** [comment]
I solved my problem by using `.open()` instead of `.toggle` to open a sidenav.

**Comment by ThomasBurleson** [comment]
@MilosStanic - Thanks. That should help us identify the issue(s).

**Comment by MilosStanic** [comment]
I don't know how and why, but now I have the same problem even when using `.open()`. Also same problem appears on mobile when using mdBottomSheet. It opens and closes immediately.

**Comment by ThomasBurleson** [comment]
@MilosStanic I will need a CodePen or Plunkr that demonstrates this issue.

**Comment by MilosStanic** [comment]
@ThomasBurleson 
You can see it in action at http://mcalc.net  
Open it in android and try touching hamburger menu on the top left to open the mdSidenav. Also you can touch the bottom right corner fab to see how it opens and closes twice when you touch it. 
Also, you can try touching the date at the bottom of the screen to see Lumx date picker and try touching left/right arrows to change month and see it skip months. 

All the code is currently available in the console inspector, because it's still in dev phase. 


Thanks, I hope it helps.

**Comment by HriBB** [comment]
I have similar problem with ionic and angular material. Clicking on backdrop works in desktop Chrome, but not on Android 5.0. I'm using Crosswalk web view btw ... not really sure how to debug this one, will need some help.

**Comment by HriBB** [comment]
Huh ... if I add <script src="lib/angular-material/angular-material.js"></script> to the project, google map marker click stops working on android. I bet this is related to the backdrop problem.

**Comment by FlexiTime** [comment]
ngClick event firing twice on iOS and toggle opening and closing sidenav are completely breaking our app.

Note http://mcalc.net above works okay if running in Chrome but when opening the dev tools and setting to mobile view it has the open and close issue.

**Comment by phoenixgao** [comment]
Same issue here

**Comment by mathiasmoeller** [comment]
+1

**Comment by gharel** [comment]
+1

**Comment by ThomasBurleson** [comment]
@kennethcachia - another click event issue (firing 2x).

**Comment by phoenixgao** [comment]
updated to 0.9.0-rc1, still not working

**Comment by xyboox** [comment]
Confirm: 0.9.0-rc1 not working

**Comment by ThomasBurleson** [comment]
Please read Ionic Gesture conflicts: #2365.

Developers may also try disabling Angular Material click-hijacks with our new special **provider**:

```js
app.config(function($mdGestureProvider) {
  // For mobile devices without jQuery loaded, do not
  // intercept click events during the capture phase.
  $mdGestureProvider.skipClickHijack();
});
```

**Comment by xyboox** [comment]
Thanks @ThomasBurleson , it works!
