### ISSUE TITLE
mdSelect and mdInputContainer for ngMessages

### ISSUE THREAD

**Issue by breandr** [angular/material#1843]
In order to group ngMessages with mdSelect, there needs to be a container element. Should mdInputContainer be used for this? It seems to display fine, but the docs do not use it as an example.

**Comment by rschmukler** [comment]
@breandr could you give a demo of this with a plunker? Depending on how it looks we might add it to the docs as a good example?

**Comment by breandr** [comment]
http://plnkr.co/edit/dTanrH7Qf4SBNYRKJQHM?p=preview

Unfortunately there is no css for the invalid color

**Comment by robertmesserle** [comment]
@rschmukler Please add a demo for validation along with this.

**Comment by breandr** [comment]
My plunker includes validation

**Comment by ngraef** [comment]
Thanks for the fix, @rschmukler. However, the "invalid and dirty" requirement seems inconsistent with the handling of `input`, for which the invalid style is applied on blur, regardless of a value change (`ng-dirty`). For example, tabbing through a form without changing any values results in error-styled inputs but not mdSelects.

**Comment by kevinlbatchelor** [comment]
The problem here is that an invalid ie, un-select box doesn't prevent form submission.

**Comment by lexyfeito** [comment]
Hello @ngraef i am currently having the same issue, i have a md-select field the is is required and is using an ng-message, if i select an option in the select it triggers the error styling. Any suggestion on this? Thanks
