### ISSUE TITLE
mdSelect :'multiple' is specified as a boolean option, but behaves as flag

### ISSUE THREAD

**Issue by ggranum** [angular/material#1845]
Technically this could be fixed by updating the docs to indicate that multiple is a flag. However, so far as I know, there is no spiffy flag-attribute shortcut for Angular like there is in Polymer, so leaving it as a flag would be a pain. 

I added a note to the relevant commit line. Well, probably the relevant line:
https://github.com/angular/material/commit/786cb3b1642be623b21551e4c8aff9c11d53ca13#commitcomment-10108925

**Comment by rschmukler** [comment]
@ggranum this is consistent with how a native select behaves, so I would be in favor of documenting it as a flag as opposed to making it just be a boolean.

**Comment by ggranum** [comment]
While I despise flag attributes, I wouldn't argue with maintaining consistency between specs - if it works in Angular 1.x.  :~)

My understanding is that Angular had to modify the behavior of disabled (ng-disabled) and selected for similar reasons:
https://docs.angularjs.org/api/ng/directive/ngDisabled
https://docs.angularjs.org/api/ng/directive/ngSelected
 
My interpretation of the main paragraph of that first link is that, if there were a short, HTML valid way to deal with flag options in Angular 1.4, it would have been used in place of creating the ngDisabled directive.

best,

If you can demonstrate how to create a mdSelect that can toggle between multiple and single select with boolean parameter, great!
