### ISSUE TITLE
md-card does not have a background color

### ISSUE THREAD

**Issue by hansede** [angular/material#1846]
md-card does not have a background color, which results in the card showing through the color of whatever is behind it:

![screenshot from 2015-03-09 16 28 52](https://cloud.githubusercontent.com/assets/728164/6565947/0b1898e0-c67a-11e4-9e4a-1a20691fd150.png)

**Comment by wniehof** [comment]
I believe this is also true for the dialog

**Comment by BirdInTheCity** [comment]
I'm seeing this, too.  Plus, if you assign it one, the card loses the rounded edges.
