### ISSUE TITLE
md-tooltip does not default to 400ms delay

### ISSUE THREAD

**Issue by Splaktar** [angular/material#1847]
The docs [here](https://material.angularjs.org/#/api/material.components.tooltip/directive/mdTooltip) indicate that the default tooltip delay is 400ms: "How many milliseconds to wait to show the tooltip after the user focuses, hovers, or touches the parent. Defaults to 400ms."

The problem is that there does not appear to be any default delay. The tooltips are displayed instantly.

Notice the difference in the code pen. The 'working' tooltips have manually set `md-delay="400"` but the non working tooltips are just using the default. They should be showing the same delay, but you can see that the non working tooltips are much faster (instant).

http://codepen.io/Splaktar/pen/emLbQN

Codepen example is using 0.8.3 with Angular 1.3.14.

**Comment by aggied** [comment]
Also experience the directive not defaulting to the 400ms delay. Without the md-delay attribute it displays immediately. Using Chrome Version 41.0.2272.118 (64-bit)

**Comment by EladBezalel** [comment]
There's no delay described in the Material Spec.

**Comment by Splaktar** [comment]
This issue doesn't mention the material spec. It's an inconsistency with the docs. The latest doc says 300 ms.

**Comment by EladBezalel** [comment]
Yep you right, we should update it to 0
