### ISSUE TITLE
Grid List doesn't work on smaller break-point when refresh browser.

### ISSUE THREAD

**Issue by kzima** [angular/material#1859]
Reloading this url
https://material.angularjs.org/#/demo/material.components.gridList
cause error:
md-grid-list: Tile at position 0 has a colspan (2) that exceeds the column count (1)
in Chrome Version 40.0.2214.115 m

See screenshot:
![image](https://cloud.githubusercontent.com/assets/5113125/6585921/48ec1a96-c7c1-11e4-8127-b7db28b444b8.png)

**Comment by cfergus** [comment]
Confirming the behavior - I am viewing the same demo on a Galaxy S3, and it shows the same result (empty panel)

**Comment by shyndman** [comment]
Thanks guys. I'll take a look.
