### ISSUE TITLE
Material Accordion

### ISSUE THREAD

**Issue by ask007java** [angular/material#1861]
How about adding accordion feature to Angularjs material. See example  

![screen shot 2015-03-25 at 3 16 52 pm](https://cloud.githubusercontent.com/assets/210413/6834417/08542162-d302-11e4-9387-cab544e043b4.png)

http://codepen.io/LukaszWatroba/pen/pvEOBZ

**Comment by tapas4java** [comment]
+1

**Comment by ThomasBurleson** [comment]
@ask007java - This is very nicely done. We are working on enhancements to md-list with 'expando' features. 
@rschmukler - I think we should review @ask007java's solution(s) to make sure we accommodate all features and perf tricks.

**Comment by marcysutton** [comment]
It also needs a few accessibility things, although it is in really good shape already! Given that accordions are not part of the Material Design spec, should this be deprioritized to happen after our current estimated feature set?

**Comment by mobelio** [comment]
+1

**Comment by brownish** [comment]
+1

**Comment by nglehien** [comment]
+1

**Comment by danawhite** [comment]
+1

**Comment by kai23** [comment]
+1

**Comment by lee-40square** [comment]
+1 

It's such a fundamental feature in most web-apps, particularly using sidebar menus. Looking desperately forward to this. What's the timeline look like with 'expando'?

**Comment by ladyborg** [comment]
:+1:

**Comment by alanpurple** [comment]
+1

**Comment by mbukosky** [comment]
+1

**Comment by ThomasBurleson** [comment]
@lee-40square  - The list expando feature is for **nested** items; while the accordion feature is for **collapsed** items.

**Comment by miguelchico** [comment]
+1

**Comment by marlonmleite** [comment]
+1

**Comment by anyong** [comment]
+1

**Comment by sachinny21** [comment]
I actually like the left side nav accordion style that you are using on your own Material website.  Exposing that would not be as difficult since you are already using it yourself! :-)

**Comment by robob4him** [comment]
Question: If "Material Design" is all about modeling design after physical materials how does this spec fit? I agree that accordions are used everywhere (and have their use) but I hesitate to put them into an angular-material repository if they aren't part of the spec. I would be more inclined to put them into a non-spec repo specifically for these things.

Not to rain gloom on everyone's parade. Cheers!

**Comment by anyong** [comment]
Well surely the accordion folder or cabinet (think big drawer of legal
documents) is a good analogy. You flip through based on the labels and see
the contents by opening it up. Not perfect, but there is certainly a
parallel between the accordion folder and accordion navigation... not part
of the spec, sure, but I agree with above comment that the one used on the
angular material website nav is pretty ideal for a lot of use cases
(especially for nav), and no reason not to include it or at least repackage
it as a standalone component.

**Comment by robob4him** [comment]
@anyong I'm not lost on the analogy of the accordion, I'm lost on it's purpose in material design. I'm entirely on point with @sachinny21 but this request is for content accordions, yes? A list view that can expand for content just sounds like a problem directly suited for navigational elements. (eg http://www.google.com/design/spec/layout/structure.html#structure-side-nav). Accordions in material design just don't seem to fit anywhere in the spec. Can someone point me to a section in the spec that gives this idea room to live?

**Comment by marcysutton** [comment]
Also note that expand/collapse list controls like the ones in the Angular Material docs sidenav are a different component than accordions (which are indeed not in the spec, unlike list controls). That issue can be tracked in #985.

**Comment by anyong** [comment]
Must be I'm thinking of list controls then, not content accordions. But
there are no expandable/collapsable list controls in angular material yet
either, correct? At least I haven't found it in the docs.

**Comment by sachinny21** [comment]
@robob4him, correct, I was looking for expandable content list view.  Both the Google Material Site and your site have the same side naves with expandable content.  Figured that is something a lot of people would want to use/see and really shouldn't have to recreate for every single app.

**Comment by marcysutton** [comment]
Hi, you're talking about expandable list controls, which are in issue #985. Those controls, which *are* in the spec and have a custom implementation in the Angular Material docs sidenav, have different requirements. The component for those is forthcoming (and should be tracked in #985).

Please reserve this issue for accordions, which aren't in the Material Design spec. Accordions have the distinction of being *expandable content panels*, similar to the HTML5 details and summary elements. Because there are a ton of things we need to prioritize, we have slated Accordions for after our 1.0 release. Thank you!

**Comment by EladBezalel** [comment]
I think that the discussion here is not focused, there are expandable side nav list control that @marcysutton mentioned in #985,
And an expanding list/cards that I've talked about in #1100. 
The accordion suggested at the beginning of the discussion is some where in the middle..

**Comment by robob4him** [comment]
Alright then perhaps my point is better suited for @marcysutton and the angular-material group.

As the angular-material project as a whole stands, what purpose do non-spec features have? README.md specifically states "Our goal is to deliver a lean, lightweight set of AngularJS-native UI elements that implement the material design specification" which would lead me to :-1: this feature. Yet also a bit lower README.md states "Angular Material is both a reference implementation of Material Design and a complementary effort to the Polymer project's Paper Elements collection." The Polymer project explicitly includes a core-collapse demo as an accordion/panel. The ideas feel contradicting and I'd just like some idea what to expect from this project. Should angular-material focus on spec-compliance and have a separate repo for non-spec features or work toward Bootstrap and be a single-include toolkit for web apps?

Personally I'm going to work around the lack of accordions with navigation elements so I have no need for the additional weight of non-spec features. That said, some may, and I'm sure accordions are just the start of non-spec ideas.

**Comment by christianmenz** [comment]
+1

**Comment by ismarslomic** [comment]
+1

**Comment by nestorneto** [comment]
+1

**Comment by rosscdh** [comment]
+1

**Comment by cleever** [comment]
+1

**Comment by beebase** [comment]
+1

**Comment by msaliot** [comment]
+1

**Comment by luthur** [comment]
+1

**Comment by milad-kh** [comment]
this would be a very useful component

**Comment by piotrjaw** [comment]
It can be easily worked around with something like:

<div ng-click="showChildren = !showChildren">
    <div ng-show="showChildren">I toggle!</div>
</div>

It also works inside ng-repeat, and it only allows multiple selections open. Single selection variant could be achieved with a controller.

**Comment by kranthitech** [comment]
+1

@plotrjaw - I don't see md-item in the list of directives in the documentation here - https://material.angularjs.org/latest/#/api/material.components.list/directive/mdListItem . Are there directives which are not documented yet? - Thanks.

**Comment by piotrjaw** [comment]
@kranthitech I'd guess it's a replacement for a div - I got it from one of @marcysutton codepen examples: http://codepen.io/marcysutton/pen/azpmpY.

**Comment by ThomasBurleson** [comment]
We are currently hyper-focused on  a summer release for Angular Material v1.0; which will include Menu and DateTimePicker components, performance enhancements, bug fixes, and improved documentation.

The Expando and Accordion features are definitely on our roadmap but not critical to a v1.0 Beta candidate. Time-permitting, a demo of this feature will be posted on CodePen. 

> We are locking this issue for now... it will remain an **open** issue, but locked to future discussions. Please future discussions in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
