### ISSUE TITLE
md-select option groups documentation

### ISSUE THREAD

**Issue by Stexxen** [angular/material#1862]
![image](https://cloud.githubusercontent.com/assets/4494301/6587273/1c0aa5fc-c77a-11e4-80a8-f0fc961fe657.png)

This is a pic of the demo source code for the md-select atribute
Note the start tag is ```<md-optgroup>```
and the end tag is ```</md-option-group>```

**Comment by epelc** [comment]
It's the second demo on [this](https://material.angularjs.org/#/demo/material.components.select) page if you need the link.

**Comment by Stexxen** [comment]
yes, if you click on the source icon in the top right corner of that second section
![image](https://cloud.githubusercontent.com/assets/4494301/6597506/0996158e-c7f5-11e4-9748-51e4350fc2e8.png)

then you see my original screenshot, where I am demonstrating that the start and end tag are different. but shouldn't be.

Its not my code, I'm just pointing out a problem with the documentation

**Comment by Stexxen** [comment]
Not 100% sure if I've done it right, as its been quite a while but created a tiny pull request.

**Comment by rschmukler** [comment]
closing, thanks!
