### ISSUE TITLE
Reference app for using Material Design with Angular 2

### ISSUE THREAD

**Issue by tapas4java** [angular/material#1865]
Is there any reference application available for using Angular2 with Material Design?

**Comment by kylecordes** [comment]
The question of angular material with A2 came up at the conference last week. The answer was something along the lines of: that they would address this after they ship the finished angular material for the current 1.x.

**Comment by marcysutton** [comment]
That is correct, it will happen after Angular Material hits 1.0. The [ngMaterial forum](https://groups.google.com/forum/#!forum/ngmaterial) is a better place for questions like these, btw.

**Comment by urish** [comment]
I created a really simple demo app showing how to use the new angular material alpha with Angular2:

http://plnkr.co/edit/QtOsjtDvUGuTYmDTmm6f?p=preview

**Comment by mattiLeBlanc** [comment]
@urish The example in plunker is not showing anything beside a header. Due to changes in Angular2?

**Comment by tapas4java** [comment]
@mattiLeBlanc,

You can check below working Plunker. The problem is it only works with Angular alpha-23.

[Working Plunk](http://plnkr.co/edit/nYKpBlmIIHCIWhnXCdze?p=preview)

**Comment by mattiLeBlanc** [comment]
Yes I can confirm that it works.
I moved back to Angular 1 for now, because I can't go in production with Angular 2 with Meteor and Material design being under development.
Thanks for sharing the working Plunker

**Comment by storytime** [comment]
Maybe, you can provide, for example material button example.
Because Im trying to use
```
<md-content>
    <md-button class="md-raised md-primary">Primary</md-button>
</md-content>
```
and no luck :(

**Comment by neilyoung** [comment]
Doesn't work anymore :)

**Comment by webknjaz** [comment]
@storytime any success with this?

**Comment by osi-bhushankumar** [comment]
Anyone have workable demo ?

**Comment by webknjaz** [comment]
@osi-bhushankumar I've fixed @tapas4java's example, so it works now, but `<md-button>` still doesn't work.
http://plnkr.co/edit/0Rh5sYVeqFZIDoLgIXSw?p=preview

**Comment by osi-bhushankumar** [comment]
@webknjaz , You have used https://github.com/urish/angular2-material-build this library. But, 'this is no longer maintained'. 

See this, https://github.com/urish/angular2-material-build/issues/7 .

**Comment by webknjaz** [comment]
Guys, I've found ng2 fork: https://github.com/justindujardin/ng2-material

**Comment by jelbourn** [comment]
You can follow the development of the Angular 2 Material components on our repo: https://github.com/angular/material2

**Comment by StretchKids** [comment]
Given the overlap between early adopters of Angular Material and early adopters of Angular 2 the lack of Angular 2 support is a problem and should be given a higher priority. 

We would like to consider Angular 2 for a project scheduled for a May release, but are blocked by an earlier commitment to Angular Material.

**Comment by loul42** [comment]
+1 StrechKids

**Comment by natcohen** [comment]
It seems the team is putting all its effort on Angular Material 1.x. 

Many other options are available for angularjs 1.x (which are at a later stage and far more stable). The time the team will reach the stability needed for a production system, more people will be using angularjs 2.x than angularjs 1.x.

IMHO it is a waste of time to focus on 1.x!

**Comment by StretchKids** [comment]
> Many other options are available for angularjs 1.x (which are at a later stage and far more stable than Angular Material 1.x). The time the team will reach the stability needed for a production system, more people will be using angularjs 2.x than angularjs 1.x.

>IMHO it is a waste of time to focus on 1.x!

I don't agree. There aren't enough Angular 2 users yet to vet  Angular Material and there were none at the time of the beta and RC releases. It needs to be more of a parallel track. But an Angular 2 release for May-August would probably need a beta Angular Material for Angular 2 release now.

**Comment by jaichandra** [comment]
We are in the same boat. Starting a new project and want to go with Angular2 to be future ready, but lack of angular material support is holding us back.

**Comment by ajtowf** [comment]
Hope this helps, a first look at the ng2 material components integrated into a demo app https://youtu.be/ngkVXUCBozc

**Comment by ChuckkNorris** [comment]
@ajtowf Thanks a ton for making that video! I finally feel like I have a decent grasp of the SystemJS loader after watching you figure it out.
