### ISSUE TITLE
Update peerDependencies to include angular 1.4

### ISSUE THREAD

**Issue by jgoux** [angular/material#1872]
Hello,
I'd like to use the new `bindToController: {}` syntax introduced in angular 1.4, but the package.json is locked to angular 1.3.
Would it be possible to include 1.4 as well ?
I think it could be easily fixed by changing `1.3.x` to `^1.3.0`

**Comment by ThomasBurleson** [comment]
BTW - Bower will use `^1.3.0` to install 1.4 only when it has been released (not a `-build...` version).

**Comment by jgoux** [comment]
Thanks @ThomasBurleson , but by peerDependencies I was refering to NPM install instead of bower. :P

**Comment by maxdow** [comment]
I think you can already use bindToController in ddo with angular 1.3 no ?
