### ISSUE TITLE
(md-subheader) (md-toolbar) multiple issues on chrome and firefox

### ISSUE THREAD

**Issue by marshfire** [angular/material#1873]
I was trying to limit the maximum width of a list to prevent ugly stretching of content on large devices. I was using md-subheader and md-toolbar with the scroll-shrink option. 

It gives lots of unexpected results, here is a jsfiddle to play with: https://jsfiddle.net/8hL90jyg/1/

The things I found:

1. the sticky subheader will start correctly but will always extend to the end of the screen, expected behavior is to have the same size as the non sticky subheader and to not paint a shadow on the scrollbar.
![image](https://cloud.githubusercontent.com/assets/681471/6603201/ce5b0264-c820-11e4-83e9-96d26b1a46ae.png)

2. when combined with a toolbar that is shrinking away on scroll the position of the sticky header is wrong.

3.  when scrolling a bit the sticky header jumps to the right (looks like when the new subheader tries to move the old one away)

4. The scrollbars jump in a weired way

![image](https://cloud.githubusercontent.com/assets/681471/6603241/0fe245c6-c821-11e4-8849-1ed915b71915.png)

1 and 3 also happen without a toolbar

Browser is chrome 40. 

On Firefox the situation is way better (probably because it has a native support for sticky positioning), however 2 smaller things happen:

1. The sticky header is a bit too short:
![image](https://cloud.githubusercontent.com/assets/681471/6603314/85cf900e-c821-11e4-9120-88d6060ab041.png)

2. When scrolling down so the toolbar is gone, the scrollbar ends too early (might be a firefox thing)
![image](https://cloud.githubusercontent.com/assets/681471/6603331/b04384c6-c821-11e4-9c40-09d300a5cba0.png)

**Comment by ThomasBurleson** [comment]
Fixed
