### ISSUE TITLE
mdGridList support for alternative interpolation symbols

### ISSUE THREAD

**Issue by Arth95** [angular/material#1874]
Hi!
It seems like Grid List doesn't like custom interpolation symbols. I'm working with my friend who is coding in Python, so he needs {{ }}. I changed my interpolation symbols to [[ ]] and Grid List doesn't work at all.
Is it possible to make it working?

**Comment by ThomasBurleson** [comment]
@shyndman - we does this with tempates in [InterimElement](https://github.com/angular/material/blob/master/src/core/services/interimElement/interimElement.js#L225-L228)

**Comment by shyndman** [comment]
Awesome. Thanks.
