### ISSUE TITLE
Extending with custom modules

### ISSUE THREAD

**Issue by grimor** [angular/material#1875]
Hello,

I'm trying to write my own directives to add new custom elements. I'm able to inject $mdTheming provider or $mdInkRipple factory like:
```javascript
function MdMenuItemDirective($mdInkRipple, $mdTheming) {

    return {
      restrict: 'E',
      link: function(scope, element) {
        $mdTheming(element);
        $mdInkRipple.attachButtonBehavior(scope, element);
      }
    };

  }

  MdMenuItemDirective.$inject = ['$mdInkRipple', '$mdTheming'];
```
And that's working fine. But I'm wondering if there's any way to integrate theming support, like in pre-built modules.

**Comment by ThomasBurleson** [comment]
@grimor - I do not understand your question. Can you elaborate?

**Comment by grimor** [comment]
Sorry, I'll try explain that more clearly. Generally I want to make my own directives for example: 
**md-menu-list** and **md-menu-item** for making custom menu.

I wanted to **md-menu-item** have Ink Ripple so I incjected **$mdInkRipple** factory and called in directive (I looked at button element in source code) and It's working fine. I also added **$mdTheming** provider and after calling in in directive It's also working.

And my problem is CSS styling. I saw there's theme styling for each component https://github.com/angular/material/blob/master/src/components/button/button-theme.scss which contains some (angular?)variables and THEME_NAME constant which I believe is preprocessed and injected into <head> depending on the theme selected by $mdThemeProvider.

My question is there's any way to use same CSS syntax to write theme specific styles for own custom element.

**Comment by richshaw** [comment]
I came across the same problem today while working on the development of a custom component. I threw together a quick service converts tokenized css, like that generated by the ```-theme.scss``` files,  to themed CSS and adds it to  ```<HEAD>```.

[Angular Material Component Theming](https://github.com/richshaw/md-component-theme)

It needs some TLC but seems to do the job.
