### ISSUE TITLE
Tooltip is placed incorrectly when it is inside an element with its zoom changed

### ISSUE THREAD

**Issue by DFernandez9** [angular/material#1876]
When  I change the zoom css attribute on a div then the Tooltips inside it are popping up in the wrong place.

http://codepen.io/dfernandez9/pen/ZYqKgy

**Comment by robertmesserle** [comment]
You should not be using `zoom` in this way: https://css-tricks.com/almanac/properties/z/zoom/

Instead, you would want to use `transform: scale(2);`
