### ISSUE TITLE
Sidenav will block esc key actions, should be able to disable

### ISSUE THREAD

**Issue by aeroxy** [angular/material#1877]
When sidenav is triggered, the esc key will be blocked. There should be an option to allow esc key to be disable for sidenav.

**Comment by aeroxy** [comment]
Also the esc key only runs `$mdSidenav('left/right').toggle();`. This is a problem if there is are other actions need to be completed within the toggle function.

**Comment by ThomasBurleson** [comment]
@aeroxy  does toggle() not return a promise? for 

```js
$mdSidenav( navID )
   .toggle()
   .then(function(response) {
    // other actions.
   });

**Comment by aeroxy** [comment]
@ThomasBurleson my point is, when sidenav is open, the esc key is blocked because it is assigned to close the sidenav. I think there should be an option to disable this feature so I can assign esc key to do other things regardless if sidenav is open.

**Comment by ThomasBurleson** [comment]
That makes sense if the side av is **not** locked open.

On Wednesday, March 11, 2015, aeroxy <notifications@github.com> wrote:

> @ThomasBurleson <https://github.com/ThomasBurleson> my point is, when
> sidenav is open, the esc key is blocked because it is assigned to close the
> sidenav. I think there should be an option to disable this feature so I can
> assign esc key to do other things regardless if sidenav is open.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/1877#issuecomment-78422516>.
>


-- 
*Thomas Burleson*
Mindspace LLC

http://www.gridlinked.info
http://www.linkedin/in/ThomasBurleson
https://github.com/ThomasBurleson

**Comment by aeroxy** [comment]
@ThomasBurleson Correct. Perhaps a `md-hotkey` attribute that will determine if the element will bind with hotkeys. Currently I just make my custom javascript by removing the hotkey from angular-material.js.

**Comment by max-SS** [comment]
Someone solved this problem. In my case, I need the mdSidenav, do not close when pressing esc. But I don't know how to solve it.

**Comment by MauricioC31** [comment]
Hi max-SS you can solved this problem? I have the same problem. Thank you for advance
