### ISSUE TITLE
Scrollbar of other content disappear when md-select is opened

### ISSUE THREAD

**Issue by cwtsui** [angular/material#1880]
When I open md-select, the scrollbar of other places disappeared.

I can reproduce the error in Firefox on Mac OS but not in safari and Chrome.

Steps to reproduce:
1. Go to https://material.angularjs.org/#/demo/material.components.select
2. Click on the select element

Observation
![screen shot 2015-03-12 at 10 45 50 am](https://cloud.githubusercontent.com/assets/184519/6611377/6f26e566-c8a6-11e4-80c3-127c03b42384.png)
![screen shot 2015-03-12 at 10 46 00 am](https://cloud.githubusercontent.com/assets/184519/6611376/6f22f0d2-c8a6-11e4-9bd5-5bdf0977039a.png)

**Comment by ThomasBurleson** [comment]
@rschmukler - Select current disables parent scrolling on md-content. Would the above be a unwanted side affect ?

**Comment by rschmukler** [comment]
Opening a select disables scrolling by applying overflow hidden to the container. Disabling scrolling when a select menu is open is consistent with the native behavior, and overflow: hidden is the only cross-browser/mobile way that I know to disable scrolling. I'm definitely open to other ideas if people have them!

You might think to do them on scroll events, but sadly you can't prevent them. Next you might think to go to mouse wheel events, but then what about touch start, tabbing to focus elements further down on the page, spacebar or arrow keys being used to scroll, etc? We can't preventDefault on all of those events as it could cause lots of unintended behavior... For example, on a select up and down also get used to cycle options, tab to close, etc.

If anyone has ideas, I'd love to hear them as this issue also exists for dialog.

**Comment by cwtsui** [comment]
I am OK with the style "overflow: hidden".

However, the width of the element change (because of the scrollbar) when
md-select is open/close. The content of the container will be moved
slightly. I believed that you can see it using Firefox.
