### ISSUE TITLE
The sidenav buttons on demo page is not documented

### ISSUE THREAD

**Issue by aeroxy** [angular/material#1881]
![screen shot 2015-03-11 at 11 04 39 pm](https://cloud.githubusercontent.com/assets/2761307/6611487/25aa9b3e-c843-11e4-83c2-49ec0c041d83.png)

Hi, I've notice these nice looking buttons are not documented in demo.

**Comment by ThomasBurleson** [comment]
This is simply md-buttons used inside md-list-item(s).

**Comment by MilosStanic** [comment]
+1, would also love to see these buttons with icons, too.

**Comment by ThomasBurleson** [comment]
:+1:

**Comment by marcysutton** [comment]
The actual feature is being worked on, the list item control: https://github.com/angular/material/issues/985

The version in the docs was a temporary, custom implementation while that issue was being worked on. Recommend we close this issue in favor of the real component, which is forthcoming.

**Comment by ThomasBurleson** [comment]
We you can currently see exactly how to do this in the Material Start [SideNav Usage](https://github.com/angular/material-start/blob/master/app/index.html#L27-L36). Meanwhile, we can easily create another online demo for the "list" component.

**Comment by marcysutton** [comment]
@ThomasBurleson this will be covered under #985.

**Comment by marcysutton** [comment]
Closing this as it is covered by list controls, which will be out in 0.9.0.
