### ISSUE TITLE
cannot load https://material.angularjs.org on ipod safari and bad render on chrome Tablet

### ISSUE THREAD

**Issue by jfpwork** [angular/material#1885]
Hello all,

try to see https://material.angularjs.org on ipod safari but JS error 
- line2 on docs.js (parseError)
- line 4054 of angularjs ($injector:modulerr)

so try it on a Listo tablet  with chrome but feel the render it's not the same as desktop chrome ( cannot scroll the menu and input render not fill the screen)

Not sure it's a good place to say ot, it is my first issue

**Comment by rschmukler** [comment]
@jfpwork what version of safari / chrome are you running?

**Comment by jfpwork** [comment]
It seems to be an old one, try it with ipod 4.3.5 ( dont know safari version can't find it) 
For Listo Tablet with Chrome : it is 18.0.1025308
I'm an Old Man ?

**Comment by marcysutton** [comment]
We support n-1 browsers, so I believe those are too far behind to be supported.
