### ISSUE TITLE
Improve Documentation to include sections Events, Methods, and Properties

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#1888]
For many of our components we document the Attribute API, but do not present any information on public methods or events. Perhaps an documentation approach like this would work:

![screen shot 2015-03-12 at 11 31 56 am](https://cloud.githubusercontent.com/assets/210413/6622636/d123df44-c8ab-11e4-9074-5934cbf166ae.png)

**Comment by ThomasBurleson** [comment]
@mhevery - Just an FYI that we are starting:

*  to think about events vs dirty watchers 
*  to consider docs useful for both Angular Material 1.x and 2.x.

**Comment by gkalpak** [comment]
:+1: :+1: :+1: for reducing watchers. There's **too** much watching going around in `ngMaterial` :smiley:
