### ISSUE TITLE
mdList - Add swipe animation for items

### ISSUE THREAD

**Issue by leonzinger** [angular/material#1890]
i would like to make a list and add a functionality like in gmail app/ mailbox/ inbox. to swipe left/right with animation.

I would love to see something like that implemented in angular material like here:
https://poly-mail.appspot.com/

**Comment by ThomasBurleson** [comment]
The SideNav currently has animated open and close features. You can use the mdList within the mdSideNav... much like our [Online Docs](http://material.angularjs.org)

**Comment by leonzinger** [comment]
I did not mean that. i meant swipe left/right to mark as checked or delete an email.

**Comment by gustavohenke** [comment]
I think the example you originally mentioned in the issue is the best example possible for the swipe gesture.
@ThomasBurleson, please reconsider. The current swipe gesture doesn't match the Android behavior.

**Comment by ThomasBurleson** [comment]
My apologies; I misunderstood.  A list item swipe Sounds like a great feature. That demo helped... thank you.

**Comment by leonzinger** [comment]
+1 thanks a lot guys

**Comment by mismith** [comment]
+1

**Comment by adarshmuthappa** [comment]
+1
