### ISSUE TITLE
.md-dialog-container top is calculated incorrectly on firefox

### ISSUE THREAD

**Issue by dguralnick** [angular/material#1892]
I'm seeing style="top: 0px;" when scrolled down in the body which results in the dialog showing up mostly off screen.  I saw this issue in firefox on a linux machine.

Demo: http://codepen.io/anon/pen/XJxBdZ

**Comment by marcysutton** [comment]
I'm debugging this right NOW! good timing. :)

**Comment by marcysutton** [comment]
Can you test again with the code on master?

**Comment by dguralnick** [comment]
Seems to work now in the codepen using src="//ajax.googleapis.com/ajax/libs/angular_material/0.8.2/angular-material.min.js"

**Comment by marcysutton** [comment]
Rad! Thanks for the update.
