### ISSUE TITLE
Multiple theme changing not working

### ISSUE THREAD

**Issue by Xeoncross** [angular/material#1894]
I forked the 'Muppet' demo and added a selector to change theme's - but while the `md-theme` is being updated after you make a selection - the class is remaining the same `md-default-theme`.

I'm using `... ng-theme="{{theme}}" md-theme-watch>` and `$mdThemingProvider.alwaysWatchTheme(true);`

http://codepen.io/Xeoncross/pen/ByqObP?editors=101

**Comment by rschmukler** [comment]
You want to use `md-theme`, instead of `ng-theme`.

**Comment by SimeonC** [comment]
Hey, just come across this, updated plunkr: http://codepen.io/SimeonC/pen/vONeON. (We also have this issue on the 0.9.0-rc3 version).

As you can see that the md-theme works on the element it's created on, but it does not cascade to all child elements that already exist - the old md-xxxx-theme classes are not replaced. This kinda defeats the purpose of theming.
