### ISSUE TITLE
Flex layout issue on Chrome using percentage flex-basis

### ISSUE THREAD

**Issue by kostonstyle** [angular/material#1895]
Hi all
I have the following layout based on material layout:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Angular Material - Starter App</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no"/>

    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:400,700'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/angular-material/0.8.3/angular-material.css"/>
    <link rel="stylesheet" href="./style.css"/>

</head>

<body ng-app="starterApp" layout="column">

	<div flex="20" flex-gt-md="25" flex-lg="25" flex-gt-lg="25" layout="column">
		<div flex="30" layout="row" layout-align="center">
			<div flex flex-gt-md="40" flex-lg="40" flex-gt-lg="40" layout="row">
				<md-toolbar flex="20" id="home" layout="row">
					<h1>Navi1</h1>
				</md-toolbar>
				<md-toolbar flex layout="row">
					<h1>Navi1</h1>
				</md-toolbar>
			</div>
		</div>
		<div flex layout="row" layout-align="center">
			<md-toolbar flex-gt-md="40" flex-lg="40" flex-gt-lg="40" layout="row">
				<h1>Navi2</h1>
			</md-toolbar>
		</div>
	</div>
	
	<div flex style="background-color:green">
	
	</div>

	

<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular-animate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular-aria.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular-material/0.8.3/angular-material.js"></script>

<script type="text/javascript">

    angular
            .module('starterApp', ['ngMaterial'])
            .run(function ($log) {
                $log.debug("starterApp + ngMaterial running...");
            });

</script>

</body>
</html>
```
Please try it on firefox and chrome, and you will see it works not the same.

Thanks.

**Comment by marcysutton** [comment]
Can you put this in a Plunker or Codepen? Thank you.

**Comment by kostonstyle** [comment]
Here we go
http://plnkr.co/edit/CZcLimYSXloCJvOPMi4m?p=preview
Thanks

**Comment by kostonstyle** [comment]
I have an another sample to http://plnkr.co/edit/hXjGh1supopA8RGLs8is?p=preview that does not work.

**Comment by kostonstyle** [comment]
I have an another example with very simple layout design.
http://plnkr.co/edit/eg1JDom0Mu3dQWvg71YQ?p=preview

On firefox works like I am imaging but on chrome horrible. Which browser can I trust?

**Comment by ngraef** [comment]
Pretty sure this is [Chromium bug 346275](https://code.google.com/p/chromium/issues/detail?id=346275). It's been killing my layouts lately. Unfortunately, the team doesn't seem to be in a hurry to fix it.

**Comment by jelbourn** [comment]
@kostonstyle Looking at your simple example, we found that you can fix this by giving the flex container an explicit height (such as `height: 100%`). Can you try this out and see if that works for you?

**Comment by ThomasBurleson** [comment]
To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by CLGitDev** [comment]
@ThomasBurleson Seems like I'm still getting the same problem with Chromium (version: 45.0.2454.0, branch: 338387) by using the latest versions you mentioned. Please find example in the plnkr below:

http://plnkr.co/edit/SfjrycR9BABVhrYiOnaU?p=preview

![image](https://cloud.githubusercontent.com/assets/14813922/10095650/ebcd762e-639d-11e5-9173-6ed55a62ab5b.png)

![image](https://cloud.githubusercontent.com/assets/14813922/10095666/0822ad08-639e-11e5-9266-711112313406.png)

**Comment by kildareflare** [comment]
Don't have a plunker yet, but I am also seeing this with latest versions (0.11.2 & 1.4.5).

**Comment by vinaynb** [comment]
facing the same issue with latest version of angular-material 0.11.4.
Any workarounds till it gets a permanent solution ?

**Comment by ThomasBurleson** [comment]
I am now seeing the same layouts on FireFox and Chrome and Safari... based on latest from Master.

> If you are still having issues either:
* Please post your issue in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
* Create a new issue
