### ISSUE TITLE
Grid-List on Ios Devices (Ipad , Iphone etc.) complete breakdown since new version 11/3/

### ISSUE THREAD

**Issue by ibrainventures** [angular/material#1896]
If you try to look on your original demo site on a ios-device:

https://material.angularjs.org/#/demo/material.components.gridList

all demos are complete smallsized / not working.

with the last version it was okay.

**Comment by ibrainventures** [comment]
a screenshot
![iosbug1](https://cloud.githubusercontent.com/assets/8803626/6637850/bb1598b2-c97f-11e4-95ec-8cf610fd75c8.png)

**Comment by ibrainventures** [comment]
upps ..  #1834

**Comment by ibrainventures** [comment]
any news for the right syntax for a functional grid-list ?

**Comment by bijoux** [comment]
Can confirm. Seems fine in 0.8.2 while broken in current master.
I'm using the responsive gridlist and it only shows 1 'tile' in mobile (iphone 4 & galaxy s4)

**Comment by ThomasBurleson** [comment]
Fixed with 33049cff96cd643e76159fc2d72cbd9fb911245c
