### ISSUE TITLE
Card Actions

### ISSUE THREAD

**Issue by ask007java** [angular/material#1900]
The Card actions feature is pretty cool. It has not been implemented and/or documented.

![image](https://cloud.githubusercontent.com/assets/6759476/6640185/93d1f8f2-c963-11e4-88ce-4f0b3aee43a0.png)

**Comment by EladBezalel** [comment]
It can be easily done like that:

```html
<md-card>
    <div class="content" flex>
        ...
    </div>
    <md-divider></md-divider>
    <div layout="row" layout-align="space-between">
        <div class="left">
            ...
        </div>
        <div class="right">
            <md-button>Action</md-button>
            <md-button>Action</md-button>
        </div>
    </div>
</md-card>
```

I didn't tested it but it should work..

**Comment by naomiblack** [comment]
This should be looked at before 1.0 as it may require a breaking change. Hey @EladBezalel would you be interested in contributing to core? We would love to pair with you on it if you have time in early September to build it.

**Comment by EladBezalel** [comment]
@naomiblack i'd love to help at any time!

**Comment by ThomasBurleson** [comment]
@EladBezalel - notice that Dialog has `dialog-actions`:

```html
 <md-dialog-actions layout="row">
      <md-button href="http://en.wikipedia.org/wiki/Mango" target="_blank" md-autofocus>
        More on Wikipedia
      </md-button>
      <span flex></span>
      <md-button ng-click="answer('not useful')">Not Useful</md-button>
      <md-button ng-click="answer('useful')" style="margin-right:20px;">Useful</md-button>
    </md-dialog-actions>
```

with associated **md-dialog-actions** css.
