### ISSUE TITLE
Non-empty first position on slider

### ISSUE THREAD

**Issue by axelson** [angular/material#1902]
Is it possible to set the `<md-slider>` to not show an empty circle on the left-most position. Since my slider has '1' as the first position (using discrete) I don't think it makes sense, but if the first-position was a '0' I could see it making sense.

I don't see any controls for it in the docs:
https://material.angularjs.org/#/api/material.components.slider/directive/mdSlider

I have a work-around that I'm using for now but I'm having to hard-code the theme color, is there a way to access the theme color in my css?

    md-slider.md-default-theme.md-min .md-thumb:after {
      // TODO: Don't set this manually here
      background-color: rgb(255,64,129);
    }

**Comment by ThomasBurleson** [comment]
Not part of the Material Design specification.

**Comment by nealedj** [comment]
FYI it appears that this is part of the spec for discrete sliders but this has been fixed in 1.1.0: https://github.com/angular/material/commit/e0abeb4d

See https://material.angularjs.org/latest/demo/slider
