### ISSUE TITLE
Firefox md-scroll-y doesn't work correctly in <md-content>

### ISSUE THREAD

**Issue by madvas** [angular/material#1906]
Please see following [plunker](http://plnkr.co/edit/P2wbZgPbcR4H7gGMy2zJ?p=preview)
In chrome it creates correctly scroll-bar in `<md-content>` element. Whereas in firefox it doesn't. Although there is scroll-bar, but it belongs to parent `<iframe>` not to `<md-content>` and therefore a scrolling behavior is different - not desired.

Tested on Linux & Windows Firefox 36.0

**Comment by hdnebat** [comment]
is there any update on this?

**Comment by kuhnroyal** [comment]
Workaround http://plnkr.co/edit/HlewnhGlClDjAqp6Za17?p=preview
Replace the outer div with md-content.
Also removed a flex and a layout-fill which didn't seem to have any effect.

**Comment by kuhnroyal** [comment]
Also see http://stackoverflow.com/questions/29108922/how-to-make-content-scrollable

**Comment by SvitlanaShepitsena** [comment]
Thank you very much!!!
Replacing div with md-content really helps, no issues with home page content scroll on Mozilla anymore.
https://svet.firebaseapp.com/#/home
https://gist.github.com/SvitlanaShepitsena/748656b9dcbbdba9dab3
