### ISSUE TITLE
md-button: Incorrect styles for disabled raised buttons

### ISSUE THREAD

**Issue by epelc** [angular/material#1907]
The styles for disabled buttons with `md-raised` appear to be wrong. There is no background when they should have a slight grey background.

The spec is here
http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons
![image](https://cloud.githubusercontent.com/assets/5204642/6653560/449eede2-ca6e-11e4-9a30-b1600205bc76.png)

Also the spec has a video for buttons in motion just below the above link and the styles seem to be much nicer for disabled raised buttons there.
![screen shot 2015-03-14 at 5 18 09 pm](https://cloud.githubusercontent.com/assets/5204642/6653561/4d641560-ca6e-11e4-975c-e7d50bbe5c4a.png)

**Comment by ilanbiala** [comment]
@epelc I think @marcysutton created an issue for this, I can't remember the exact one though.

**Comment by epelc** [comment]
@ilanbiala I think its #142 but it seems to be quite old

**Comment by ilanbiala** [comment]
Yes #142 is the one I was looking for, and the latest commit referring to that is from 24 days ago, so it should still be happening.
