### ISSUE TITLE
md-swipe-left/right: Docs "view demo" link sends you to docs home page

### ISSUE THREAD

**Issue by epelc** [angular/material#1911]
The view demo link sends you to the docs home page for `md-swipe-left` and `md-swipe-left`

https://material.angularjs.org/#/api/material.components.swipe/directive/mdSwipeRight

**Comment by marcysutton** [comment]
Hiding the link for now.

**Comment by matthewrfindley** [comment]
@epelc We decided to add a basic demo.  In the future this page will be the home of any additional demos for md-swipe-{left | right}
