### ISSUE TITLE
feat(mdCheckbox): Add indeterminate state

### ISSUE THREAD

**Issue by breandr** [angular/material#1912]
I just replaced a native checkbox with mdCheckbox and realised it doesn't have an indeterminate state.

**Comment by epelc** [comment]
If anyone doesn't know what this is have a look below

https://css-tricks.com/indeterminate-checkboxes/
![image](https://cloud.githubusercontent.com/assets/5204642/6666869/9bb8f78e-cbbe-11e4-88ea-86a9090ee93b.png)

**Comment by marcysutton** [comment]
We have passed this question along to the UX team and will report back.

**Comment by marcysutton** [comment]
I'm still unclear what the use-case for this would be, and the native versions can only be added with JavaScript (not HTML attributes). That said, I think a line icon just like the Chrome version would communicate effectively.

**Comment by breandr** [comment]
Use-case: a select-all check box which is checked whem all children are
checked; unchecked when all children are unchecked; and intermediate when
at least 1 but not all children are selected.

**Comment by epelc** [comment]
@marcysutton My use case would be for user specific permissions. Specifically for overriding defaults from a users role. The indeterminate state would be used to default to the parent role for each permission.

**Comment by marcysutton** [comment]
Cool! thanks for your replies, those help.

**Comment by ThomasBurleson** [comment]
The UX Material team is adding this feature to the specification.

**Comment by breandr** [comment]
Thanks!

**Comment by rscafi** [comment]
+1
Use case: Row selection in tables determine state of "select all" checkbox.

http://www.google.com/design/spec/components/data-tables.html#data-tables-interaction

**Comment by YuriyVlasenko** [comment]
+1

**Comment by langdonx** [comment]
PRs welcome?

	md-checkbox.md-indeterminate .md-icon:after {
		box-sizing: border-box;
		transform: rotate(45deg);
		position: absolute;
		left: $checkbox-width / 3;
		top: $checkbox-width / 9;
		display: table;
		width: $checkbox-width / 3;
		height: $checkbox-width * 2 / 3;
		border-width: $checkbox-border-width;
		border-style: solid;
		border-top: 0;
		border-left: 0;
		content: '';
		transform: rotate(0deg);
		border-right: 0;
		top: -2px;
		width: 10px;
		left: 4px;
	}

I know HTML only has `indeterminate` as a property, but it would make good sense to have it as an attribute here (or a class at the very least).  It shouldn't manipulate the model either since `input.checked` doesn't change when `input.indeterminate` changes (if `indeterminate` is true, it will always show the checkbox as indeterminate regardless of the `checked` property).

**Comment by smurugavel** [comment]
+1

**Comment by begemott** [comment]
+1

**Comment by DevVersion** [comment]
SHA 2776ad29a3323bc7f8da7309d2bf6e1014b462cb
