### ISSUE TITLE
When using `layout-wrap` on `md-content > md-card`, could we avoid having the cards at the same height on the same row?

### ISSUE THREAD

**Issue by aeroxy** [angular/material#1913]
When using `layout-wrap` on `md-content > md-card`, the cards will have the same height property on the same row. This is an undesirable behavior in some cases (eg. if we want to have a pinterest like layout). Could we add an option to `layout-wrap`, eg. `layout-wrap="flex"` and `layout-wrap="inline"`.

**Comment by aeroxy** [comment]
Perhaps `layout-wrap="absolute"` and `layout-wrap="column"` are more accurate names since those are two ways to get pinterest like layout.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
