### ISSUE TITLE
CRITICIAL BLOCKER: md-Select within md-Dialog

### ISSUE THREAD

**Issue by kschwidder** [angular/material#1914]
Szenario:

In the following demo http://plnkr.co/edit/Bs7vTflGrI7H9dkmk0z4?p=preview a list of entries is generated.
Each item has a dialog attached. Within the dialog a md-select item is provided.

Issue:

a) Scroll through the list and open a dialog.
b) Open the select box : The dialog gets re-positioned and drops of the visible area and can not be closed anymore
c) Press ESC which triggers to close the unseen selectbox. Now the Dialog appears again on the screen.
d) Select the md-select and the dialog stays on the screen

What I have observed is that the md-select component does not proper recognize the scrollTo position. This behaviour does not occur with the autocomplete component !

**Comment by marcysutton** [comment]
This issue will be fixed with https://github.com/angular/material/pull/1350.

**Comment by kschwidder** [comment]
Great. Do you have any dates when it will be committed to the master ? This bug is inhibiting our tests with the customers. Thx for the update.

**Comment by marcysutton** [comment]
It's currently being reviewed, so it will be in very soon. Most likely today or tomorrow.

**Comment by kschwidder** [comment]
Great. Thx a lot !

**Comment by marcysutton** [comment]
Closed with 0b0ed2339e1ec32e34d20daa18cadd4ef89d5f86

**Comment by kruny1001** [comment]
This is not really fixed yet. 
I update 0.8.3 but I have still same issue

**Comment by PaulMougel** [comment]
0.8.3 was released before 0b0ed23 was merged into master, that's why you still have the bug. You will need to install the `master` version of angular-material, or at least `v0.8.3-master-0b0ed23` to have it fixed.
