### ISSUE TITLE
Invalid height during tab switch animation

### ISSUE THREAD

**Issue by Toilal** [angular/material#1919]
If tabs have different height, when switching from tab X to tab Y, the Y tab is displayed using X height during animation, and it truncates the content. Height is properly set after animation, but UX is weird during the animation.

See this plunker : http://plnkr.co/edit/5THPBT?p=preview

**Comment by Toilal** [comment]
Maybe it's related to https://github.com/angular/material/issues/1008

**Comment by robertmesserle** [comment]
This is a duplicate of #1008 - Closing.
