### ISSUE TITLE
Input fields disapear or inaccessable on IE11 / layout-sm

### ISSUE THREAD

**Issue by wlodekf** [angular/material#1923]
On Internet Explorer (11) if there are at least 2 input fields in a row sized with flex and layout-sm is set to "column" then the fields disappear or are inaccessable on narrow browser window. This can be seen in docs/demo app. See Company/Submission, First name/Last name and City/State/Postal Code rows of fields in Demos > Input.

If the fields are not sized with flex (like Title/Email) or if there is just one field in a row it's OK.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by wlodekf** [comment]
It's just the angular material demo / input [Codepen] (http://codepen.io/anon/pen/QjwZzG)
When the window is less than 600px wide I get something like on the attached picture, where
on the left you have inaccessable fields (submission date, first and last name, city, state, postal code).

![am-input--ie11](https://cloud.githubusercontent.com/assets/1101563/9698533/e5e8367e-53ba-11e5-91b7-b34b97ff6379.png)

**Comment by ThomasBurleson** [comment]
@wlodekf - excellent information. Thx.

**Comment by ThomasBurleson** [comment]
![screen shot 2015-09-05 at 7 04 29 am](https://cloud.githubusercontent.com/assets/210413/9699126/cbb8042e-539b-11e5-8daf-d982c4305fe1.png)

**Comment by wlodekf** [comment]
Updated the code base but that didn't help.
Your screen shot shows how it is expected to work and how it looks on other browsers, the problem is on Windows 8.1/IE 11 (11.0.9600.17031)
