### ISSUE TITLE
md-autocomplete should have HTML results

### ISSUE THREAD

**Issue by atvilelas** [angular/material#1924]
md-autocomplete should have HTML results for better theming.

I found that replacing the line:

text = $interpolate($element.text())($scope),

with 

text = $interpolate($element.html())($scope),

does the trick.

**Comment by chrisguerrero** [comment]
+1

I'd like to see support for html content inside autocomplete results as well

**Comment by dmackerman** [comment]
+1, this would be very useful.

**Comment by robertmesserle** [comment]
I do not think this is in line with what `md-autocomplete` is setting out to do.  I am going to backlog this for now, as I think more thought would have to be given to a) whether or not this is something that we want and b) does it belong in `md-autocomplete`?

**Comment by robertmesserle** [comment]
@atvilelas @chrisguerrero @dmackerman This should already be supported.  You can put whatever HTML you want in the results; however, the code you referred to was in the text highlighting directive, which needs to be applied to the element whose contents need to be highlighted.  The fix that you proposed would appear to work; however, if the query text also existed as an attribute name or the user typed something like `div` into `autocomplete`, it would cause the HTML to become invalid.

What I would recommend is that you only attach the `md-highlight-text` directive to individual tags within your results.  Example:

```html
<md-autocomplete
    md-selected-item="ctrl.selectedItem"
    md-search-text="ctrl.searchText"
    md-items="item in ctrl.querySearch(ctrl.searchText)"
    md-item-text="item.display"
    placeholder="What is your favorite US state?">
  <img src="{{item.image}}" alt="{{item.display}}" />
  <span md-highlight-text="ctrl.searchText" md-highlight-flags="^i">{{item.display}}</span>
</md-autocomplete>
```
