### ISSUE TITLE
md-input placeholder should not turn red when field is invalid per material design spec

### ISSUE THREAD

**Issue by bfelda** [angular/material#1928]
The material design error page linked below shows error fields but the placeholder is not red.  The red placeholder/label in md-input has been flagged during our usability testing as it doesn't appear to be a placeholder any longer.  Also, with the red line and red error text, we don't need that much screaming.

![image](https://cloud.githubusercontent.com/assets/3695667/6676084/376bfa9e-cbf3-11e4-9dde-4111e8d933be.png)

http://www.google.com/design/spec/patterns/errors.html#errors-user-input-errors

**Comment by GuilhermeGoncalves** [comment]
I'm getting same error with angular-material 1.0.7.
In the screenshot, I copied an pasted the code in documentation and got it..
![screenshot](https://cloud.githubusercontent.com/assets/5985312/14440850/470ec41e-0008-11e6-8318-1509c6a71764.png)

**Comment by krystyna-lyn** [comment]
tttt
