### ISSUE TITLE
mdSticky in complex dialog demo causes content overflow problems in IE11

### ISSUE THREAD

**Issue by marcysutton** [angular/material#1929]
With the newest dialog fixes [on master](0b0ed2339e1ec32e34d20daa18cadd4ef89d5f86), the complex dialog now loads correctly in IE11, Safari and Firefox. In IE11, however, after you click on the dialog, the content overflows so much that you can no longer get to the action buttons at the bottom. 

**Complex dialog on show:**
![Complex dialog on show](https://cloud.githubusercontent.com/assets/1045233/6677109/429696e4-cbea-11e4-8b86-9aa053f7782d.png)

**Complex dialog after click:**
![Complex dialog after click](https://cloud.githubusercontent.com/assets/1045233/6677108/4295afd6-cbea-11e4-8cfa-e563bcceb657.png)

We can simplify the demo so that it doesn't have this problem, but it seems like we should fix the issues with mdSticky since they will undoubtedly come up again.

**Comment by mtraynham** [comment]
Looks like #1167 is back as well.
![screen shot 2015-03-16 at 7 10 49 pm](https://cloud.githubusercontent.com/assets/5741321/6678370/381f22f0-cc10-11e4-95e6-cb6917e912a9.png)

**Comment by marcysutton** [comment]
I see that on the docs website, but not in my local build. I'll try and figure out what the differences are.

**Comment by mtraynham** [comment]
@marcysutton Thanks!  It would be nice if these changes were added as default styling to the md-dialog component.  It looks like there is already some handling for `md-content`.
https://github.com/angular/material/blob/master/src/components/dialog/dialog.scss#L36

**Comment by marcysutton** [comment]
Looks like the latest code actually wasn't deployed, and the build is failing for a seemingly unreleated reason. Looking into it.

**Comment by jlubin1** [comment]
@marcysutton Thank you for looking into this.  The application we are developing makes heavy use of the complex dialog component and, unfortunately, the majority of our users will be in IE11.  Were you able to resolve this?
