### ISSUE TITLE
Closurize default-theme.js

### ISSUE THREAD

**Issue by jelbourn** [angular/material#1930]
The generated file [`default-theme.js`](https://github.com/angular/bower-material/blob/master/modules/closure/core/default-theme.js) does not have any `goog.provide` / `goog.require`. Since the content is part of `material.core`, the file should be appended to `core.js` (at  least for the Closure deployment).

**Comment by epelc** [comment]
@jelbourn does the rest of angular-material work with closure? I wanted to try it out soon.

Also what does the `G` label mean I've seen you added it to a few issues. Is it for google?

**Comment by jelbourn** [comment]
The build process generates components that are "closurized" by adding `goog.provide` and `goog.require` so that the Closure compiler can be used to manage them as dependencies and concatenate the files correctly. The can see the output in the `bower/material` repo. The material library can be minified by the Closure compiler in simple mode; the output is a little smaller than uglify, but it requires a Java runtime so we keep Uglify as the default for ease-of-use.

The `G` label is so I can keep track of issues that come from inside Google.

**Comment by epelc** [comment]
@jelbourn Thanks for the info
