### ISSUE TITLE
Fix sticky header in complex dialog

### ISSUE THREAD

**Issue by mtraynham** [angular/material#1932]
Honestly, the base dialog is pretty bland, even if it does follow the [spec design](http://www.google.com/design/spec/components/dialogs.html#dialogs-specs).  The one shown in the docs is much nicer looking, but kind of a pain to get set up.

I suggest adding a css class to md-dialog, say, `<md-dialog class="md-complex-dialog"`, would be much more useful than multiple users trying to recreate the look and feel of the demo.

I was able to re-create that look and feel with the following css:
```
md-dialog.md-complex-dialog .md-subheader {
  margin: 0;
}
md-dialog.md-complex-dialog .md-subheader.md-sticky-clone {
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.16);
}
md-dialog.md-complex-dialog > md-content {
  padding: 0;
}
md-dialog.md-complex-dialog > md-content > :not(.md-subheader) {
  padding-left: 24px;
  padding-right: 24px;
}
md-dialog.md-complex-dialog > md-content > :not(.md-subheader):first-of-type {
  padding-top: 24px;
}
md-dialog.md-complex-dialog > md-content > :not(.md-subheader):last-of-type {
  padding-bottom: 24px;
}
```

And usage in a dialog would look like:
```
<md-dialog class="md-complex-dialog" aria-label="Test Header">
    <md-content>
        <md-subheader class="md-primary">Test Header</md-subheader>
        <p>Message</p>
    </md-content>
</md-dialog>
```

**Comment by epelc** [comment]
+1

**Comment by marcysutton** [comment]
I'm not clear on what this is trying to solve that the framework doesn't do already. I cleaned up some of the CSS in https://github.com/angular/material/pull/2662, but before adding a CSS class I need to understand the problem. Sticky headers in dialogs are a known issue.

**Comment by epelc** [comment]
I just wanted the sticky header like in the custom dialog demo.

**Comment by marcysutton** [comment]
The sticky header doesn't currently work in the custom dialog demo–that feature is due for a refactor. If it did work though, it should be accomplishable without adding extra CSS.

**Comment by mtraynham** [comment]
@marcysutton I created this issue because I wanted to replicate the complex dialog in the documentation.  After seeing the demo, I can guarantee that I'm not the only one trying to replicate that look and feel.  The out-of-box dialog is stark with color and really bland, which does not do well for things like forms with headers.

My original post show's what is necessary to get that to look properly, just as the docs work.  Not only does the sticky clone not work, but the padding of an `md-content` is exacerbated by the `md-dialog` padding.

**Comment by marcysutton** [comment]
Note the dialog HTML API changed in 0.9.0–md-content is no longer the correct element to use inside of a dialog. 

Sounds like this issue is completely dependent on sticky headers working.

**Comment by mtraynham** [comment]
@marcysutton Probably true.  Feel free to rename.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
