### ISSUE TITLE
md-list within card works great in Firefox but not in chrome

### ISSUE THREAD

**Issue by kai23** [angular/material#1938]
Here is the codepen to reproduce the error :

http://codepen.io/anon/pen/jEQzzy

Basically, I have three cards, the third one having the list and as you can see in the codepen, it doesn't seems to work great on chrome

**Comment by kai23** [comment]
it works if I add 

```
<style>
	html {
		height: inherit;
	}
</style>
```

into my page

**Comment by rschmukler** [comment]
This was a bug in chrome < 34 (see [this stackoverflow](http://stackoverflow.com/questions/19450503/viewport-height-inheritance-with-flexbox-inconsistency-in-chrome)). Now resolved.
