### ISSUE TITLE
The example template of side navigation fails miserably when you open in safari.

### ISSUE THREAD

**Issue by Nirupam007** [angular/material#1945]
Any idea how to fix this issue, or the template is useless for mac and IOS users as well.

**Comment by rishighan** [comment]
I have it running perfectly in Safari 8.0.3. Not sure what you mean by "failing miserably." Can you please clarify the nature of failure?

**Comment by marcysutton** [comment]
I'm also seeing the side navigation work fine in Safari. Can you point us to a Codepen or Plunker showing the issue? Which version of Safari?

**Comment by Nirupam007** [comment]
Ok, i am testing on safari 5.1.7 only for the codepen example.
But surprisingly when i include the docs.css from the viewsource of the same page it works in Safari 5.1.7 v.

I suggest the codepen example should also contain the docs.css included.Hope you test the same.

**Comment by ilanbiala** [comment]
@Nirupam007 Safari 5.1.7 on Windows isn't supported as far as I know.

**Comment by marcysutton** [comment]
Angular Material supports n-1 browsers, so Safari 5x is indeed too far back to be supported.
