### ISSUE TITLE
2+ lines of text in ng-message

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#1952]
Hey,
I've been noting that `<md-input-container>` is not friendly to `ng-messages` that are too long. In other words, "it's not responsive enough". An image is worth a thousand words:

![](http://i.imgur.com/cVG9Q1Z.png)

[Example plunkr](http://plnkr.co/edit/5jtZyC?p=preview)

**Comment by mateeyow** [comment]
Maybe it's because you are putting width on `md-input-container`

**Comment by gustavohenke** [comment]
I did that to represent a small width. You can remove the width and resize your browser window, same will apply.

**Comment by brianfeister** [comment]
:+1:

**Comment by petarsubotic** [comment]
As partial solution I am styling md-input-invalid class with overflow:hidden and adding a md-tooltip in ng-message wherever a long message is warranted.

**Comment by gustavohenke** [comment]
Closing this since it has been fixed in 1.0.0, as stated in #3766
