### ISSUE TITLE
bower-material bower.json is missing newlines

### ISSUE THREAD

**Issue by lookfirst** [angular/material#1954]
It used to have them, now it doesn't. Makes it hard to read. =)

https://github.com/angular/bower-material/blob/master/bower.json

**Comment by lookfirst** [comment]
I just looked at the above mentioned file and it seems like there is still no newlines? Why was this closed?

**Comment by ThomasBurleson** [comment]
Closed because it was not considered an issue.

**Comment by lookfirst** [comment]
Every other bower.json file in bower-* has newlines. It would be nice to be able to read this file. How is that not a valid issue?

**Comment by lookfirst** [comment]
What generates this file?

**Comment by lookfirst** [comment]
Enjoy. https://github.com/angular/bower-material/pull/24
