### ISSUE TITLE
For md-sidenav - use sticky header and footer and let content in the middle fill the height of remaining space seems not to work

### ISSUE THREAD

**Issue by smitty02001** [angular/material#1955]
All,

I am using md-sidenav which contains content. I want the content to include a sticky header and footer and the content in the middle will fill the space in between the header and footer.

Example:

```
<md-sidenav class="md-sidenav-right md-whiteframe-z2 right-nav-slider" md-component-id="tabs" style="min-width:800px">
  <div layout="row">
    <div layout="column" layout-fill>
      <md-toolbar style="background-color:green;height:50px"> <span>Fixed to Top</span> </md-toolbar>
      <md-content style="background-color:red" flex> 
        Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor  enough content here to force a scrollbar.
      </md-content>
      <div style="height:50px;background-color: yellow"> Fixed to the bottom</div>
    </div>
  </div>
</md-sidenav>
```

The issue is the md-sidenav is scrolling but I want the md-content which contains the overflowing content to scroll instead.

Any fixes or suggestions would be greatly appreciated.

**Comment by RobJacobs** [comment]
In the md-content element, try setting the styles: min-height: 0; overflow: auto;

**Comment by smitty02001** [comment]
RobJacobs,

Thank you for the quick response and for your idea to try.   Unfortunately, the material design version did't work but the native version you provided worked.  My only concern is I have to support IE 10 and your native solution does not work but I believe this is do to IE 10 only partially supporting flex box.

Do you think it is a material design bug?

Thanks,

Smitty

**Comment by RobJacobs** [comment]
IE 10 requires the ms prefix for flex support, IE 9 does not support flex at all.
