### ISSUE TITLE
md-button: ng-class slow to update

### ISSUE THREAD

**Issue by Sam-Davis** [angular/material#1956]
If you use an ng-class directly on an md-button then the class is not added until either the button is clicked a second time or some other change is made to the model. 

I am trying to add a class 'selected' when the button is selected.

**Comment by bonatoc** [comment]
I was able to change the button class with ng-class.

Can you show some code?

**Comment by Sam-Davis** [comment]
Apologies, I was updating this in a $watch statement. I didn't realise that watch statements were outside the digest cycle, so I need to do a $scope.apply() for this to work
