### ISSUE TITLE
md-input-container(firefox): input type="number" doesn't fill width

### ISSUE THREAD

**Issue by epelc** [angular/material#1957]
The discount rate input has `type="number"` which doesnt fill it's parents width in firefox as you can see below.
![image](https://cloud.githubusercontent.com/assets/5204642/6715731/c0e04346-cd76-11e4-8cc7-ec90e67fa1da.png)

Note input `type="text"` or not specifiying a type works as expected which you can see for the `name` field. I did a dif between the input with `type="number"` and without a type and the only added style was `-moz-apperance: none;` on the one with `type="number". I also tried adding `flex` to the input but that didn't work. Also the `md-input-container` still takes up the full width so it's a problem with the `input` styles.

**Comment by ivan7237d** [comment]
Setting `width` to `auto` fixed it in my case.

**Comment by topherfangio** [comment]
Need to do more formal testing, but it looks like adding `width: auto` to the `.md-input` class in `input.scss` will fix the issue.

**Comment by Gaurav9969351313** [comment]
not working mdinput in IE10
type=number side arrow event 

<input mdInput type="number" onkeypress="return event.code !='NumpadDecimal'  && event.code!='Period'" [step]="10" [max]="100" [min]="0">

in chrome m getting the desired output as we press up down arrows it inputfield text jumps to 10 ( as step is=10 ) 

but same is not working in IE10 and IE11
Thank You in Advance...:)

**Comment by Gaurav9969351313** [comment]
do i need to update my polyfills...
if yes then please suggest for the same....
