### ISSUE TITLE
Stop using `text-transform: uppercase`

### ISSUE THREAD

**Issue by jelbourn** [angular/material#1958]
Button, select, tabs, and toast all use `text-transform: uppercase` to force upper case characters to match the Material Design spec. However, this is fraught with i18n problems; in some locales, changing the capitalization of a word can change its meaning.

Some examples:
[Dotted and dotless I in Turkish](http://en.wikipedia.org/wiki/Dotted_and_dotless_I)
[The German ẞ has no canonical upper-case](http://en.wikipedia.org/wiki/Capital_%E1%BA%9E)
[The Greek Sigma has more than one lower-case form](http://en.wikipedia.org/wiki/Sigma)

**Comment by gkalpak** [comment]
Angular handles lowercasing/uppercasing specially when the user's locale is Turkish.
Not sure if this is sufficient for other locales, though. (If it were, we could somehow replace `text-transform: uppercase` with a call to `angular.uppersace(...)`.)

Shouldn't browsers handle similar locale-specific issues themselves ? Grrr...

<sub>As a sidenote, capitalizing the Greek sigma should not be an issue (it is handled properly in the supported browsers).</sub>

**Comment by epelc** [comment]
Maybe an i18n override class you could add to the body would be a good idea for languages that browsers have trouble with.

**Comment by ThomasBurleson** [comment]
Due to international concerns, we are removing the presumptive transform `text-transform: uppercase`.
A workaround will be posted in the release notes.

> All Angular Material demos will be updated; where the labels are specifically and manually updated.

**Comment by innerpeace0** [comment]
@ThomasBurleson, this is great how you and your team are paying attention to i18n. There are so many great things about both Angularjs, MD. What you folks are doing to make them work together is great, too. Keep up the good work.

**Comment by atul221282** [comment]
This issue is still pending
