### ISSUE TITLE
chore: use npm to install angular-* packages + remove bower dependency

### ISSUE THREAD

**Issue by btford** [angular/material#1962]
This will make CI faster and deploying to material.angularjs.org a bit more sane.

**Comment by epelc** [comment]
@btford How would this make it faster? Is bower slow or are they just duplicate deps?

**Comment by btford** [comment]
It'll be faster because CI won't have to install bower.

**Comment by EladBezalel** [comment]
Just to be clear.. There is still bower support at [bower-material](https://github.com/angular/bower-material)?

**Comment by ThomasBurleson** [comment]
@EladBezalel - yes, absolutely. You can install the deployed builds of Angular Material (from bower-material) using either **npm** or **bower**.
