### ISSUE TITLE
mdCheckboxGroup: allow md-checkbox to iterate over an array of elements (somewhat like to md-radio-group/button)

### ISSUE THREAD

**Issue by balteo** [angular/material#1964]
This is a suggested enhancement to **md-checkbox**:

Allow md-checkbox to iterate over array of elements as follows:
```
<md-checkbox ng-repeat="option in options" ng-model="model.chosenOptions">
     {{option}}
</md-checkbox>
```
and populate model with a list of selected values such as http://vitalets.github.io/checklist-model/

Feedback appreciated...

**Comment by jadrake75** [comment]
+1

**Comment by sazonenka** [comment]
+1
`md-checkbox-group` makes sense

**Comment by germanferrero** [comment]
+1

**Comment by sahil87** [comment]
+1

**Comment by timc13** [comment]
+1

**Comment by Otgontugs** [comment]
+1

**Comment by rochdev** [comment]
+1

**Comment by dohomi** [comment]
+1

**Comment by ozayolkan** [comment]
+1

**Comment by tnf3251** [comment]
+1!!!

**Comment by Otgontugs** [comment]
+1

**Comment by Karvel** [comment]
+1

**Comment by ptesser** [comment]
+1

**Comment by Luburic** [comment]
+1

**Comment by tejasatara** [comment]
+1. There are surely other ways of doing this. But a common feature like this has to be a part of core. 
Cheers :)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by venkatesan-94** [comment]
+1

**Comment by samphree** [comment]
+1

**Comment by foreverzmy** [comment]
+1

**Comment by alexnoise79** [comment]
+2
