### ISSUE TITLE
Show Default Selection in auto-complete

### ISSUE THREAD

**Issue by CxRes** [angular/material#1966]
It would be nice to have the possibility to display text corresponding to a default selection instead of placeholder text.

For example: when using the auto-complete as a an address bar it should display the address of the current page by default.

**Comment by robertmesserle** [comment]
Why wouldn't you just set that as the placeholder text?  This doesn't seem like something that should be built into the API:

http://codepen.io/robertmesserle/pen/zxXJow

**Comment by CxRes** [comment]
Dear Robert,

Maybe I was not clear enough on what I was after. If you have the current
selection as a placeholder, on clicking it it vanishes. However, a URL on
your browser merely gets selected. So your solution while elegant does not
meet the circumstance of navigation. For Example, in my use case I want to
load selection options dynamically based the current selection. (In my
paticular usecase I am browsing a sandboxed location on a server, so if I
am at /x I would be presented the options in the dropdown to go to /x/foo
and /x/bar but not /y)

Please look into the request again with this in mind. I would make another
ticket if you like.

**Comment by robertmesserle** [comment]
@CxRes It sounds like you just want an initial value, rather than a placeholder.

**Comment by CxRes** [comment]
I guess an initial value with md-search-text-change (which wasn't probably there when I made the ticket) should do the job. 

I would keep the placeholder though or some switch which tells what to do when the autocomplete is clicked (remove or select text). I can appreciate that the api is getting pretty complex and you would like to keep it as simple as possible.
