### ISSUE TITLE
Access colors inside my theme sass files

### ISSUE THREAD

**Issue by joaogarin** [angular/material#1970]
Hello,

I am probably missing the point on how theming works with angular-material but here is my question. I have the theme in my $mdThemingProvider and that works nicely for all the md-* directives from angular material.

But what about my own directives and other general things in my app where I want to apply my color pallete scheme? How can I either provide an attribute or class to the element so that it gets themed correctly or access the color palette in my scss files? (I guess the second one is not possible)

I dont want of course to have to set my color palette both in $mdThemingProvider and in my sass files..

Thanks for the help, any links to some documentation on this would be appreciated as well as in the docs from https://material.angularjs.org/#/Theming/01_introduction did not help me very much..

**Comment by marcysutton** [comment]
I think what you're looking for is covered in https://github.com/angular/material/issues/1269.

**Comment by joaogarin** [comment]
=) Many thanks! Its exactly that

**Comment by marcysutton** [comment]
Ok cool! I'm going to close this issue to minimize duplicates. You can keep an eye on PR #1599 for implementation, it's under review right now.
