### ISSUE TITLE
Option to set delay on $mdToast.hide

### ISSUE THREAD

**Issue by jturmel** [angular/material#1971]
Something like:

    var options = {delay: 2000};
    $mdToast.hide([response], options);

**Comment by rschmukler** [comment]
@jturmel You can use the `hideDelay` option on the `show` method to achieve a similar effect.

For example:

`$mdToast.show($mdToast.simple('Hello world').hideDelay(2000))`. If you need specific granularity beyond that, the recommended way would be to use `$timeout`. If these won't work let me know and we can explore the use case further.

**Comment by jturmel** [comment]
Yeah this is more of a, okay we know we need to close it now but we still would like a delay so that we don't get on/off as a flicker scenarios.

For example:

We show a toast when something is saving and then hide the toast once it's saved (on a promise success), for the most part our APIs are so fast that the toast just flickers unless we put a delay on the hide event. That way the user isn't wondering "hey what was did I just see/miss there that flickered?"

**Comment by rschmukler** [comment]
I'm going to move this out of `0.9.0` but take it as a feature enhancement request for a `minDisplayTime` for a toast to avoid the flicker you mentioned.

**Comment by jturmel** [comment]
Sounds good, thanks!

**Comment by jturmel** [comment]
What was this deprecated by?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
> For details, see our post [Deprecation Policy](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
