### ISSUE TITLE
How to make a custom modal

### ISSUE THREAD

**Issue by VictorQueiroz** [angular/material#1973]
Well, I have a custom modal at a project made with bootstrap, which shows a modal which inside of it there is some options that change a scope inside of my template. This modal is a resuable component, how can I reproduce that using Angular Material API?

**Comment by marcysutton** [comment]
Please ask questions on the [ngMaterial forum](https://groups.google.com/forum/#!forum/ngmaterial), Github is reserved for bug reports and feature requests. Thank you!
