### ISSUE TITLE
Autocomplete - dropdown list reappears after selection is made

### ISSUE THREAD

**Issue by kendrickw** [angular/material#1974]
If I modify the data source in the autocomplete demo on the Angular Material site to:
Alabama, Alabama1, Alabama2, Alaska, Arizona, Arkansa,...

Upon entering 'Ala' in the text input, it will list the first 4 names as expected:
![screen shot 2015-03-19 at mar 19 10 34 00 pm](https://cloud.githubusercontent.com/assets/3593963/6745071/2489d058-ce88-11e4-88c0-00b4ccfa7fe1.png)

But if I select 'Alabama' from the dropdown list, I would expect the dropdown list to hide. However, it would reappear with the following list:
![screen shot 2015-03-19 at mar 19 10 34 19 pm](https://cloud.githubusercontent.com/assets/3593963/6745080/45de09cc-ce88-11e4-8434-b66f1950441f.png)

My guess is that the new search term produces multiple hits, and therefore triggers the dropdown list again, but I don't think this is the correct behavior.

**Comment by ilanbiala** [comment]
I have this issue as well.

**Comment by robertmesserle** [comment]
Seems to be resolved in master - most-likely by this commit: 5f14126954fa10911e00a8c18bf8a070133ae5de

**Comment by ilanbiala** [comment]
@robertmesserle is a patch release (0.8.4) going to be released with all these bug fixes for autocomplete and other new features in 0.8?
