### ISSUE TITLE
List tile align on md-item-content

### ISSUE THREAD

**Issue by Bent10** [angular/material#1975]
seems the tiles align is not on center in google spec

<img align="top" src="http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7bE92OEZmTk5OMW8/components_lists_keylines5.png" alt="tiles align" width="45%" height:"auto"> <img src="http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7WFlXMWVNV0h2QW8/components_lists_keylines6.png" alt="tiles align" width="45%" height:"auto">

**Comment by rschmukler** [comment]
Closing for now, as #2021 features a complete re-write that should bring it back into spec. If not, please re-open.

Thanks!
