### ISSUE TITLE
<datalist> like element in material?

### ISSUE THREAD

**Issue by SummerWish** [angular/material#1976]
HTML5 datalist is a inputable dropdown. `<autocomplete>` in angularMaterial cannot replace it (`<autocomplete>` doesn't have a initial dropdown).

any plans of this element?

**Comment by ThomasBurleson** [comment]
AutoComplete now supports an auto0pen feature when focused... set md-min-length=0.

**Comment by icenold** [comment]
Is there a way to put a dropdown arrow on autocomplete?
