### ISSUE TITLE
md-tab/md-active incorrectly disconnects scope on tabsload

### ISSUE THREAD

**Issue by nkoterba** [angular/material#1982]
Spent a few hours tracking this one down. Using angular 1.3.15 and Material Design 0.8.3.

Appears there is an issue with `md-tab's` **md-active** property incorrectly disconnecting the scope of the loaded tab when `md-tabs` is first displayed.

Issue is best seen here in code pen: http://codepen.io/anon/pen/gbZoNR?editors=101

To see issue:
1) Load codepen above
2) Click the **Press Me** `md-button`.  This button's click handler should change the displayed *file2* to *UPDATED FILE* as its changing the scope variable `$scope.file`, which in turn is bound to the directive's template `{{file}}`.
3) Notice how clicking the button repeatedly has no affect on the md-tab content.  *file2* is always displayed because the scope has been disconnected from this tab so the digest cycle is not updating the DOM.
4) Now Click the 'File 1' tab.
5) Now Click the 'File 2' tab again and notice how now that the scope has been re-applied, the digest cycle correctly displays the updated file, e.g. `UPDATED FILE`.

A few comments:
1) This behavior does **NOT** occur when using `md-selected` on the `<md-tabs>` element.  It only seems to affect the `md-active` attribute on the `<md-tab>` element.

2) I believe the 'logic' bug is located here:
https://github.com/angular/material/blob/master/src/components/tabs/js/tabsController.js#L59

In the add method for tab:
```javascript
if (!angular.isDefined(tab.element.attr('md-active')) && ($scope.selectedIndex === -1 || !angular.isNumber($scope.selectedIndex) ||
        $scope.selectedIndex === self.indexOf(tab))) {
      tab.onAdd(self.contentArea, false);
      self.select(tab);
    } else {
      tab.onAdd(self.contentArea, true);
    }
```

Quickly looking at this code, it appears that the fist check for md-active attribute will always cause any tab with the `md-active` attribute to be disconnected initially from scope since `true` is being passed to the onAdd method and the second parameter dictates whether scope should be disconnected or not.

I'm not sure if the **!** should be removed or the entire `if` statement updated to correctly handle all the logic cases but this appears to be what causes this issue.

**Comment by robertmesserle** [comment]
This is not a valid bug.  I have updated your codepen to support the new syntax for tabs:

http://codepen.io/robertmesserle/pen/pvBvQw

Things that needed to change:
- You were pointing to an old CSS file, so the styles did not match the code in master
- `md-tab-label` now requires your content template to live within `md-tab-template`
- `md-active` is no longer supported as this creates the possibility for multiple tabs to be simultaneously selected

**Comment by nkoterba** [comment]
@robertmesserle Thanks for the updated code-pen and change suggestions.

I noticed md-tabs was getting some major updates for version 0.9.0.  Looks like 0.9.0 will fix several issues I saw with md-tabs in version 0.8.x.
