### ISSUE TITLE
md-maxlength character count doesn't update when changed in controller

### ISSUE THREAD

**Issue by DevVex** [angular/material#1983]
If an input field has a md-maxlength showing the character count of the field, (ex. 34/40). And the form is submitted, and I clear the field in the controller (vm.task.field = ''). The counter will remain at 34/40 with no text in the field. 

Related to #1870

**Comment by gkalpak** [comment]
This is an actual issues. Has been also mentioned in #1903.

**Comment by breeze4** [comment]
The key line of code seems to be right here:

https://github.com/angular/material/blob/master/src/components/input/input.js#L323

Instead of using element.val() to get the latest value of the input field, why not use ngModelCtrl? 
Current: <code> charCountEl.text( ( element.val() || value || '' ).length + '/' + maxlength );</code> 
Proposed: <code>charCountEl.text( ( ngModelCtrl.$modelValue || '' ).length + '/' + maxlength );</code>

Is it okay to reference ngModelCtrl.$modelValue in this context?

If that seems like a valid change, I'd like to try my hand at a PR fixing it with a corresponding test.

**Comment by batressc** [comment]
I modified the code line indicated by @breeze4 in unminified file "angular-material.js" and the counter was reset correctly.

Please consider include this change and make the respective test framework

**Comment by zargold** [comment]
@batressc nice codeine but the problem with this is once you go over the md-maxlength (when I just tried doing that it says you are persistently at 0/150 or whatever rather than 159/150) so it gives incorrect information the length measurement became off.

**Comment by gkalpak** [comment]
Indeed, using the `$modelValue` won't show correct info when the input value is invalid, since (by default) in that case the `$modelValue` is set to undefined.

**Comment by julienpa** [comment]
Since it has been moved to the backlog, does it mean it won't be fixed anytime soon?

**Comment by smurugavel** [comment]
+1. 
I see another workaround suggested in here but I haven't tried it [1870](https://github.com/angular/material/issues/1870)

**Comment by corentin-gautier** [comment]
+1

**Comment by nestabur** [comment]
+1

**Comment by pablozandona** [comment]
+1

**Comment by ogaihtorecic** [comment]
In your clearForm function:

`$timeout(function() {
   model.field = "";
}, 30);`

Worked for me.

**Comment by MadJlzz** [comment]
+1

**Comment by DevinWatson** [comment]
+1

**Comment by smurugavel** [comment]
Hello @ThomasBurleson. A resolution on closing this item will be much appreciated. This and most other items that were closed are missing resolution.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

> Which other closed, deprecated issues are missing the ^^ comment ?

**Comment by DevVersion** [comment]
Referencing #8351

**Comment by TiboQc** [comment]
I manage to find a workaround based on what @ogaihtorecic said (which didn't work for me), using Angular 1.3.20 and Angular-Material 1.0.5:

    $scope.model.field = '';
    $timeout(function() {
        $scope.form.fieldName.$setViewValue(''); // resets the <input> value which updates the counter
        $scope.form.fieldName.$setUntouched(); // resets validation on the field
    },0);

**Comment by besharati-behzad** [comment]
I wrote a simple code that could solve this problem

**in your view:**
md-maxlength="vmCtrl.getMaxLen(30)"

**in your controller:**

var fakeMaxLen;
vmCtrl.getMaxLen = function (value) {
      if (fakeMaxLen)
            return fakeMaxLen;
      return value;
 };

// call this function after your data model was changed and you need to update char counter
function callMeWhenYouNeedToResetCharCounter(){
        fakeMaxLen = 100000;
        $timeout(function(){
              fakeMaxLen =undefined;
              vmCtrl.form.$setPristine();
              vmCtrl.form.$setUntouched();
        });
}

// you can disable animation of .md-errors-spacer class and set visibility to hidden, when process started
// and return back to original state after the process finalized (in timeout function)
// it's just for smoother working and prevent char counter flickering

**Comment by himvins** [comment]
[http://tinyurl.com/ngfhxcu] given by @batressc is working fine for the issue but it has one issue mentioned by @zargold  By just modifying the codepen with one condition It is working fine for me. 

`function renderCharCount(value) {
                            //Original code commented
                            //debugger;
                            if(ngModelCtrl.$modelValue !== "")
                                {
                                    charCountEl.text( ( element.val() || value || '' ).length + '/' + maxlength );        
                                }
                            else
                                {
                                     charCountEl.text((ngModelCtrl.$modelValue || '').length + '/' + maxlength);
                                }
                            
                            //CHANGE PROPOSED BY @breeze4 (MATT BAILEY): http://tinyurl.com/pxnnvxb
                            
                           
                            return value;
                        }`

**Comment by tgelu** [comment]
+1
