### ISSUE TITLE
layout-margin/padding: Add gt-* varients

### ISSUE THREAD

**Issue by epelc** [angular/material#1984]
It would be nice if we had `layout-margin-gt-md` etc. Some things end up with to much margin/padding on smaller devices.

**Comment by gustavohenke** [comment]
Related: #1281 #1322

**Comment by marcysutton** [comment]
@epelc do you mean you want the amount of margin to change depending on the width of the device? Will the fix in this PR cover your use case? https://github.com/angular/material/pull/1322

Side note: the spec has specific metrics for margins independent of device width, so I don't think they should really change cross-device. If there is an actual bug with the margin/padding attributes, though, like the flex variant one...that should be fixed.

**Comment by epelc** [comment]
@marcysutton I meant only setting the margin for specific media queries but I think it changing automatically is a better system. For example you probably don't need as much margin on a small device as you do a large one.

**Comment by marcysutton** [comment]
I definitely think specific margin/padding values should be handled inside the framework CSS so they align with the Material Design metrics. The only cross-device adjustment I could find from looking at the [spec](http://www.google.com/design/spec/layout/metrics-keylines.html#metrics-keylines-keylines-spacing) was that margins are `16px` on mobile, `24px` on tablet, and nothing is specified for desktop.
