### ISSUE TITLE
mdButton: Style to match spec

### ISSUE THREAD

**Issue by marcysutton** [angular/material#1987]
In addition to the work being done for #1907 and #1832, feedback from the Material Design UX team has pointed out some inconsistencies with buttons as they relate to the design spec:

- [x] Buttons shouldn't move in Y axis, only the shadow should move
- [x] Buttons are too wide

Also needed:
- [ ] Keyboard pressed state should work similarly to mouse click

**Comment by jlmagee** [comment]
Please investigate difference in vertical alignment when using href=" " in the element. The element becomes an anchor and renders vertically at the top of the element enclosing it. This is especially annoying in a navbar.

**Comment by tapas4java** [comment]
I also noticed a problem when using md-button as an anchor. The width and height is not respecting css values. You can simulate this by adding href or ng-href attribute to md-button in material sample application menu.

Using md-button as an anchor is a common scenario in favour of routing.
