### ISSUE TITLE
CSS text-rendering style causes severe performance issues with long strings

### ISSUE THREAD

**Issue by mbpatel82** [angular/material#1989]
https://github.com/angular/material/blob/master/src/core/style/structure.scss#L39

The text-rendering:optimizeLegibility CSS style is applied globally to html and body tags, resulting in severe performance issues on pages that try to render SVGs with large text content. If you need this CSS style, it should only be applied to the elements that need it, not globally.

To see the performance issue, you can reproduce at https://jsfiddle.net/saLmfxza/. Remove the text-rendering CSS style to see the (30x) difference.

**Comment by jelbourn** [comment]
Related #1442

**Comment by ACDN** [comment]
Taking out that CSS makes a huge difference in performance. Looking forward to when all the CSS is optimized!

**Comment by mpiasta-ca** [comment]
Good find :+1:
