### ISSUE TITLE
md-select does not close with data-multiple="true"

### ISSUE THREAD

**Issue by baolocdo** [angular/material#1990]
I moved the md-select out of the dialog that we are having and it did cancel the menu when I clicked outside of the menu. It seems like there is a problem with the menu on the dialog. 
It only happens with data-multiple="true". If it is false, the menu is closed automatically after I choose one of the options, but it still doesn't close when clicking outside when md-select on a dialog

**Comment by rschmukler** [comment]
This seems to be fixed on master. Was likely resolved by #1350

**Comment by internetti** [comment]
I am still having that same issue. I tried various versions of angular material that came after this was closed.
