### ISSUE TITLE
md-select does not appear to work inside md-input-container

### ISSUE THREAD

**Issue by billfranklin** [angular/material#1994]
Would seem to make sense to make setting up form inputs consistently (i.e. not excluding md-select from the md-input-container)

**Comment by sclearion** [comment]
Same issue here. driving me nuts. Might have to do a css hack and post

**Comment by sclearion** [comment]
Temporary hack. I had change the md-input-container surrounding the md-select from:
<md-input-container flex>

to

<div flex>

and the add this style to my css:

md-select {
    display: inline-block;
    margin-top: 2px;
    width: 100%;
}

The final HTML block should look like this:

<div flex>
                    <label>Appointment With</label><br/>
                    <md-select ng-model="favoriteTopping" placeholder="Favorite Topping">
                        <md-optgroup label="Meats">
                            <md-option ng-value="topping.name" ng-repeat="topping in toppings| filter: {category: 'meat' }">{{topping.name}}</md-option>
                        </md-optgroup>
                        <md-optgroup label="Veggies">
                            <md-option ng-value="topping.name" ng-repeat="topping in toppings| filter: {category: 'veg' }">{{topping.name}}</md-option>
                        </md-optgroup>
                    </md-select>
                </div>

**Comment by patrickmichalina** [comment]
Thanks for the temporary fix!
