### ISSUE TITLE
md-subheader goes behind the menu when using a md-sidenav locked open

### ISSUE THREAD

**Issue by peluprvi** [angular/material#1998]
In Chrome:
![image](https://cloud.githubusercontent.com/assets/1561360/6768223/8a12f358-d03d-11e4-8602-266f6fa49720.png)

Complete example code:
http://plnkr.co/edit/zm3lHjPYH7p5mRxmCqLo?p=preview

The right behavior, but not in the right way:
http://plnkr.co/edit/0rJGD4XD6bTGocyrMsKU?p=preview

**Comment by WhiteAbeLincoln** [comment]
I am having the same issue. I also have a [plunker](http://plnkr.co/edit/tpl:08SJCM3cRHaRisyy385Z?p=preview) to show. It would be nice if someone would look at this issue, since it's been open for over 25 days, and no one has commented until now.

ping @rschmukler @ThomasBurleson

**Comment by ThomasBurleson** [comment]
This will be investigated tomorrow. 

> Please note that when an issue is in the backlog for some time, that means that other issues are considered higher priorities.

**Comment by WhiteAbeLincoln** [comment]
I know that you have a lot of issues to take care of, so thanks for this!

**Comment by SandroDV** [comment]
Hello, I noticed that this issue appears in Chrome but not in FF

**Comment by EladBezalel** [comment]
@peluprvi it seems to be [fixed on HEAD](http://codepen.io/EladBezalel/pen/GpaOer), closing. 
if it's still happening please comment here and i will reopen and investigate
