### ISSUE TITLE
ng-model not working in md-select

### ISSUE THREAD

**Issue by hartwm** [angular/material#2001]
I tested this in a few different environments but using md-select doesn't update ng-model when the value is non numerical. It appears to work with a numerical value.

**Comment by stefan-schweiger** [comment]
Are you sure you are using it the right way? Because with the ways below it totally works for me.

View:
```XML
<md-select ng-model="item">
    <md-option ng-value="it" ng-repeat="it in items">{{it.name}}</option>
</md-select>
```
Controller:
```JS
$scope.item = null;
$scope.items = [{
    id: 1,
    name: 'Test'
}, {
    id: 2,
    name: 'Asdf'
}];
```

http://codepen.io/anon/pen/myaZmQ

**Comment by Hexacters** [comment]
but not update On <md-select Multiple> </md-select>
