### ISSUE TITLE
ng-checkbox Disable or enable dinamically

### ISSUE THREAD

**Issue by luclanet** [angular/material#2003]
It's impossible to disable or enable a checkbox dinamically.

http://codepen.io/anon/pen/zxyXva

**Comment by yanivefraim** [comment]
@luclanet This is not a bug. Please look at this codepen:
http://codepen.io/yanivefraim/pen/EarVKW

You have to change the ng-disabled="{{disable}}" to ng-disabled="disable"

Hope that helps...
