### ISSUE TITLE
Bug: md-input-container textarea max-height/rows limitation problem

### ISSUE THREAD

**Issue by Nickproger** [angular/material#2006]
Is there a way to limit a size of textarea with help "rows" attribute or similar?

```
<md-input-container>
  <label>Text</label>
  <textarea ng-model="feedback" rows="3"></textarea>
</md-input-container>
```

**Comment by kikhtenko** [comment]
+1

**Comment by andreykostenko** [comment]
+1

**Comment by vovashevchenko** [comment]
+1

**Comment by Kourkis** [comment]
+1

**Comment by ivanhtp** [comment]
Besides that, when the textarea is too height, when your text is down the page, it autoscroll to top, being impossible to see what you are writing. Don't know if it will be acomplished in the same scope.

**Comment by almothafar** [comment]
I have code something like this: 

```
<md-input-container id="message" class="md-block" flex-gt-sm>
              <label>Message</label>
                  <textarea required
                            rows="10"
                            placeholder="Your message to support here"
                            ng-model="vm.email.message"
                            name="message"></textarea>
              <div ng-messages="emailSendForm.message.$error">
                <div ng-message="required">This is required.</div>
              </div>
            </md-input-container>
```

But still, render `rows ="1"` in the source ! my version: `"angular-material": "1.0.9"`

**Comment by bialesdaniel** [comment]
+1

**Comment by marconi1992** [comment]
@almothafar I reproduced your problem, I found this line that is executed after the textarea initialization, 
https://github.com/angular/material/blob/master/src/components/input/input.js#L471
It's weird, But I added the md-no-autogrow to avoid call the grow function and it's works for me.

**Comment by beatgrabe** [comment]
+1

**Comment by nni123** [comment]
<div style="height: 10rem; overflow-y: auto;" scroll-glue> 
      <md-input-container class="example-fuller-width" >
        <textarea mdInput
                  #characterCountTextareaHintExample
                  placeholder="Description max 500"
                  maxLength="500"></textarea>
        <md-hint align="end" aria-live="polite">
          {{characterCountTextareaHintExample.value.length}} / 500
        </md-hint>
        
      </md-input-container>
</div>

**Comment by nucleardreamer** [comment]
That directive is documented here at the bottom, it's disabled by default for performance reasons: [https://material.angularjs.org/latest/api/directive/mdInput#attributes](https://material.angularjs.org/latest/api/directive/mdInput#attributes)
