### ISSUE TITLE
Bug: md-input-container textarea bug if inside of block with overflow: scroll

### ISSUE THREAD

**Issue by Nickproger** [angular/material#2007]
Example here: http://codepen.io/anon/pen/emxYjW

Try input text with more then 10 lines.
Textarea jumps and i can't see text in the end.
Very strange behaviour.

**Comment by RyanMullins** [comment]
+1

**Comment by kikhtenko** [comment]
+1

**Comment by andreykostenko** [comment]
+1

**Comment by vovashevchenko** [comment]
+1

**Comment by alexthewilde** [comment]
+1

**Comment by chrisguerrero** [comment]
+1

**Comment by ratscrew** [comment]
+1

**Comment by Kourkis** [comment]
+1

**Comment by sreevisakh** [comment]
+1

**Comment by flaviolivolsi** [comment]
:+1:

**Comment by slash13** [comment]
i love nantunes fix!!! also md-select wrapped in md-input-container makes absolute sense. 
+1

**Comment by GustavSt** [comment]
This issue seems to be back

**Comment by jalajc** [comment]
GustavSt +1,
Bug is even in 1.06
1. scroll-bar is not appearing
2. when in md-no-autogrow just one line of text appears (even if rows= 5, and one has 3 lines of text)
3. md-select-on-focus: just flashes the select and then select disappears.
