### ISSUE TITLE
Spacing between md-button buttons inside md-card

### ISSUE THREAD

**Issue by asans** [angular/material#2009]
Per Material Design guidelines, there should be spacing (8px) between the two text based buttons.  This is similar to how md-dialog is designed to space out the buttons.  However, md-card does not contain styles to do this.

It's possible (and probably easier) to just copy the md-dialog styles over.  Something like below would work out.

```
<md-card>
<div class="md-actions">
<md-button>Text</md-button>
<md-button>Text 2</md-button>
</div>
</md-card>
```

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by marcysutton** [comment]
`mdCard` does have button styles specified, see the design spec: http://www.google.com/design/spec/components/cards.html#cards-content

I'm actually in the middle of working on button styles that will add margins to our buttons to match the design spec. Going to reopen this issue to capture that work.

**Comment by ThomasBurleson** [comment]
I think we need to add  css for

```css
md-card  md-button  {

}
```
