### ISSUE TITLE
Text field with fixed label; no animation when the input field on focus

### ISSUE THREAD

**Issue by scarletsky** [angular/material#201]
In fact, what I want is like this:
![material text field](http://material-design.storage.googleapis.com/images/components-textfields-singlelinetextfields-textfields_single_06_large_mdpi.png)

It seems that I can not use `<label>` tag because of the animation. I can just work around with other tag like `<p>`, `<div>`.

```html
<material-input-group class="material-input-group-theme-light" layout="horizontal">
    <p flex="30">123123</p>
    <material-input type="text" 
                    ng-model="user.fullName"
                    flex="70"
                    style="display: inline-block;"
                    placeholder="please input something"></material-input>
</material-input-group>
```

For the semantic of HTML, I think it will be better if we support a way to remove the label animation.

**Comment by ethanlmovio** [comment]
nice fix. I upgraded to master and this works like a charm.
