### ISSUE TITLE
md-slider: Discrete step indicators not shown when slider is not on the initially visible md-tab

### ISSUE THREAD

**Issue by axelson** [angular/material#2010]
If you have an `<md-tab>` that is not visible and contains an `<md-slider>` with discrete steps, the discrete steps indicators will not be visible. This may be related to issue #1210. Here is a [plunker]( http://plnkr.co/edit/78YFSbFrqGh1MBh9Xd5B?p=preview) (Adapted from the issue as well).

**Comment by axelson** [comment]
An ugly work-around that seems to work is to call `window.dispatchEvent(new Event('resize'))` when displaying the second tab.

**Comment by kennethcachia** [comment]
Hey,

This appears to be fixed in v0.9.0. Here is a [plunker](http://plnkr.co/edit/YHiKiZJudKYeiG0Bez1J?p=preview) forked from your original demo. Can you confirm it?

Thanks!

**Comment by axelson** [comment]
Sorry it took me a while to get back to this, but obviously the plunker works. And I can now confirm that it works fine in my app as well! I'm going to go ahead and close the issue.

**Comment by kennethcachia** [comment]
Np, thanks!
