### ISSUE TITLE
Allow mdGridList to flex to fit the available area

### ISSUE THREAD

**Issue by Splaktar** [angular/material#2012]
This comes from the discussion here: https://groups.google.com/forum/#!topic/ngmaterial/Rq22sOFJOco

I wrote up a quick and dirty prototype for how it should behave here:
http://codepen.io/Splaktar/pen/zxyWYN
Full screen: http://codepen.io/Splaktar/full/zxyWYN/

The basic idea is to allow the mdGridList to fill up the available space, but not exceed it. I set the md-row-height ratio dynamically to make this happen.

**Comment by marcysutton** [comment]
I love that this idea was vetted on the forum. Thanks for providing prototypes! :+1:

**Comment by bonatoc** [comment]
@Splaktar 

Sadly, 

     md-row-height="fit"

does not appear to work in v0.9.0-rc1-master (worked like a charm in 0.8.3).

What would be the best way to retrigger your directive upon screen resize?

**Comment by helzgate** [comment]
The "fit" option is still listed in their help topics too:  [Directives for mdGridList](https://material.angularjs.org/latest/#/api/material.components.gridList/directive/mdGridList)
