### ISSUE TITLE
mdAutocomplete and mdSubheader overlap

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [angular/material#2013]
As the title says, when an mdSubheader moves over a raised mdAutocomplete, the subheader is transparent, and you can see the autocomplete element beneath. This does not occur on any other elements as far as I have noticed. 

Also, the bottom border for the subheader seems to extend further to the right -- to the end of containing element -- vs the left side, which has padding.

Example ('Create Download' is the subheader, and 'Forms' is the text in the autocomplete)
![overlap - mdautocomplete](https://cloud.githubusercontent.com/assets/7330103/6795162/851f0370-d1b2-11e4-8912-25033828c9ef.png)

**Comment by robertmesserle** [comment]
@WhiteAbeLincoln This should be fixed in master, can you please confirm?

**Comment by WhiteAbeLincoln** [comment]
Yes it is fixed. Thanks!
