### ISSUE TITLE
Bottom Sheet broke shrink in IOS

### ISSUE THREAD

**Issue by marco64bit** [angular/material#2018]
I have 2 toolbar and i have a shrink effect on toolbar 1 and a bottom sheet that i open with an ng-click.
<pre>
__________________
|  [ toolbar 1 ] |
|  [ toolbar 2 ] |
|                |
</pre>
after i close my bottom sheet ( in IPHONE 5) if i scroll the page up, the toolbar 1 remains hidden  and i cant see it any more
<pre>
__________________
|  [ toolbar 2 ] |
|                |
|                |
</pre>

**Comment by robertmesserle** [comment]
@marco64bit Can you provide a codepen demo or code sample for this?
