### ISSUE TITLE
md-select: initial scroll position isn't at the top

### ISSUE THREAD

**Issue by epelc** [angular/material#2019]
If you have a lot of options in an `md-select` the initial scroll position is torwards the bottom instead of being at the top.

![image](https://cloud.githubusercontent.com/assets/5204642/6812906/556f02e2-d248-11e4-8e6d-a8bb219c962d.png)

**Comment by rschmukler** [comment]
@epelc as per [this demo](https://jsfiddle.net/rschmukler/hntmna58/) it seems to be working for me. Punting to 0.10.0 so we can see a demo. Otherwise, close? Let me know browser info so I can track it down.

**Comment by epelc** [comment]
@rschmukler I just checked your demo and my app on master and it's fixed.

**Comment by rschmukler** [comment]
@epelc thanks for confirming!

**Comment by epelc** [comment]
@rschmukler No problem btw check your email :)
