### ISSUE TITLE
Documenting various classes, like md-tile-left and md-tile-content

### ISSUE THREAD

**Issue by frodefi** [angular/material#2025]
I cannot find any documentation of several classes, like `md-tile-left` and `md-tile-content`, and I am sure there are many more. Perhaps there are others that would appreciate such documentation too...

**Comment by marcysutton** [comment]
CSS Documentation is on the roadmap in #594, currently in progress.

**Comment by frodefi** [comment]
Oh, sorry, did not see that. Thanks, Marcy!
