### ISSUE TITLE
Material hijacking touch events for href links.

### ISSUE THREAD

**Issue by sime** [angular/material#2026]
When the Angular Material library is fetched, regardless if the ngMaterial module is loaded: Links with hrefs cannot be touched.

In the follow codepen, try touching the links in Chrome DevTools device mode or iOS Simulator Safari.

http://codepen.io/anon/pen/zxejXe

**Comment by marcysutton** [comment]
This is a known issue and duplicate of https://github.com/angular/material/issues/2027.

**Comment by sime** [comment]
@marcysutton I cannot see the relation to the mentioned issue?

**Comment by marcysutton** [comment]
Hijacking of clicks is a known issue. In what scenario would a developer fetch Angular Material but not include it as a dependency?

**Comment by sime** [comment]
Also happens to when the module is included as a dependency.

I was just trying to demonstrate the scope of the problem.

**Comment by sime** [comment]
Again, hijacking of clicks and #2027 are not related.

**Comment by marcysutton** [comment]
Ha! I totally linked the wrong Github issue. Computers, how do they work? Sorry for the confusion, here is the right one: https://github.com/angular/material/issues/1792
