### ISSUE TITLE
Add mdInput config params

### ISSUE THREAD

**Issue by cssensei** [angular/material#2027]
We should have a directive parameter that will allow default behaviour for placeholder by removing the animation of the placeholder and keeping the placeholder text inside the input elements. 

ps: In general the angular material design directives lack advanced configuration parameters and while it's good to have one way of doing things it's also cool to have that way customisable.

**Comment by epelc** [comment]
@cssensei Use `md-no-float` also look at the last demo [here](https://material.angularjs.org/#/demo/material.components.input)

![image](https://cloud.githubusercontent.com/assets/5204642/6829892/bed10998-d2ec-11e4-880b-d315abcd9f54.png)

**Comment by ThomasBurleson** [comment]
See above solution by @epelc
