### ISSUE TITLE
mdCalendar component on Material Design presentation video

### ISSUE THREAD

**Issue by gduprez** [angular/material#2032]
Hi, Not sure this is the right place for this question... 
at second 27 on Materiel Design presentation video, there's an agenda. Is there any chance this component already exists or might be available later?

**Comment by ThomasBurleson** [comment]
AFAIK the CalendarAgenda component is not part the base set of Material Design components:

![screen shot 2015-03-25 at 4 04 15 pm](https://cloud.githubusercontent.com/assets/210413/6835439/c7a31fb8-d308-11e4-82bf-e1ffd845f139.png)

**Comment by gduprez** [comment]
Thanks

**Comment by dohomi** [comment]
+1 would love to see this feature sometimes in the future

**Comment by jelbourn** [comment]
We currently have no intention of implementing anything like this and I don't see that changing for quite some time.
