### ISSUE TITLE
Scroll momentum is not respected under iOS

### ISSUE THREAD

**Issue by kawazoe** [angular/material#2033]
The demo site's menu do not use inertia / momentum scrolling using an iPhone 6 under iOS 8.2 (Safari and Chrome).

**Comment by ThomasBurleson** [comment]
Agreed, it will be a great feature.

**Comment by numerized** [comment]
+1 guys, I love your projects, working well with Ionic so far

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
