### ISSUE TITLE
Calling $mdBottomSheet.show() and $mdDialog.show() results in undefined is not a function

### ISSUE THREAD

**Issue by schnogz** [angular/material#2034]
Please take a look at the following Plunker which shows an example of both errors:  http://plnkr.co/oWP17BCpzCym4zmhKfvq

**Comment by rschmukler** [comment]
In the first one it is because `alert` does not allow you to specify a parent on the preset.

On the second one it is because your scope is a plain object, and so when the bottom sheet closes `$scope.$destroy` doesn't exist. Please make your scope by calling `$rootScope.$new()`

**Comment by schnogz** [comment]
Thanks for the explanations @rschmukler!
