### ISSUE TITLE
"Using a CDN" instructions link to version 0.7.0 which has a broken mdSelect directive

### ISSUE THREAD

**Issue by bvaughn** [angular/material#2035]
The `mdSelect` directive is not working correctly for me. I feel like I must be missing something, but I've even tried using the example snippet (below):

```html
<md-select ng-model="someModel">
  <md-select-label>But this does not</md-select-label>
  <md-option ng-value="opt" ng-repeat="opt in neighborhoods2">{{ opt }}</md-option>
</md-select>
```

And still the options render inline (e.g. "Label Option One Option Two").

Here's a Codepen illustrating the problem: http://codepen.io/bvaughn/pen/OPddPm

**Comment by Novashock** [comment]
@bvaughn use material 0.8.3. that works. change 0.7.1 to 0.8.3

**Comment by bvaughn** [comment]
Update on this issue: I installed the latest Bower version (0.8.3) and `mdSelect` works.

I was initially following the guide on your website ([Using a CDN](https://github.com/angular/material#cdn)) which links to 0.7.0. I also tried forking one of your example Codepens (which apparently also linked to an older, broken build.)

Perhaps this ticket should be re-purposed to update that guide.

**Comment by epelc** [comment]
@bvaughn It's documented that the link isn't kept up to date and you need to manually change it.
> Note that the above sample references the 0.7.0 CDN release. Your version will change based on the latest stable release version.

**Comment by bvaughn** [comment]
It's one thing to not have the latest version, another still to point to a
broken version. Either way, I thought you might care that this causes an
end user (me) about a half hour of confusion and wasted time. If you
don't... you don't.

**Comment by marcysutton** [comment]
@bvaughn which Codepen was outdated?

**Comment by bvaughn** [comment]
On the [Getting Started](https://material.angularjs.org/#/getting-started) page under the **How do I start?** header there's a link that says [Fork a Codepen](http://codepen.io/collection/AxKKgY/). I just selected one of these at random.

Going back now, I tried pasting the below component into a randomly selected one.

```html
  <md-select placeholder="Pick" ng-model="someVal">
    <md-option value="1">One</md-option>
    <md-option value="2">Two</md-option>
  </md-select>
```

Looks like the following Codepens aren't new enough to work with that sample:
* http://codepen.io/marcysutton/pen/PwJrrG
* http://codepen.io/marcysutton/pen/yyzdxp
* http://codepen.io/ThomasBurleson/pen/RNRBNq
* http://codepen.io/ThomasBurleson/pen/qEBJME

PS. Thanks for updating the doc! :)

**Comment by marcysutton** [comment]
Alright, I updated the first two. Given that they have to be updated manually, it's still on developers to check which version is being included. That's why the resources are included inline in the HTML as opposed to as "Codepen assets"–that would completely abstract away which version is being used.

**Comment by marcysutton** [comment]
The "Hello World" example on the Getting Started page is the one that gets updated the fastest, in the future.

**Comment by bvaughn** [comment]
Yeah, that's fine. It was just unfortunate that the second thing I tried
also happened to fail :)
