### ISSUE TITLE
mdTooltip: Positioned out of view if near edge of container

### ISSUE THREAD

**Issue by john-p-g** [angular/material#2037]
The tooltip will not correctly detect the edge of the container when adjusting it's position. You can see an example at the following codepen. 

[Example](http://codepen.io/anon/pen/KwJLXG?editors=101)

The screenshot below shows the tooltip positioned offscreen.

![image](https://cloud.githubusercontent.com/assets/5156460/6847811/9d6fa882-d39f-11e4-8a2c-846372d70156.png)

There are two related problems:
1. `fitInParent` is not called unless a tooltip direction is specified (or if the tooltip is off the bottom)
2. the width of the parent is measured *after* the tooltip element has been appended. This causes the calculation to be incorrect because the tooltip can change the width of the parent. If the `scrollwidth` from before appending the tooltip element is used, it positions correctly.

**Environment Info:**
Angular Material Version - 0.8.3
Browsers - Chrome, Firefox, IE, (Safari not tested)

**Comment by epelc** [comment]
I don't think it's hidden. If you look at the bottom of your picture you can see a scrollbar which I presume was created by the tooltip. However there's probably no way to scroll over to see the rest of it and it shouldn't make a scrollbar anyways.

**Comment by john-p-g** [comment]
@epelc The title might be unclear. It's not  hidden, it's just positioned offscreen (and this causes the container element to show a scrollbar as you mentioned.)

**Comment by epelc** [comment]
@john-p-g I just wanted to make it clear the title wasn't clear. I didn't know if you overlooked the scrollbar.

**Comment by john-p-g** [comment]
@epelc Thanks for the feedback. I have updated the title.

**Comment by robertbaker** [comment]
Same issue. I can't use layout-padding because of the fab buttons.  On a larger height screen I want the tool-tip to be on the bottom, but on the smallest screen, it can't, so it should be displayed on the top

**Comment by uriva** [comment]
+1
Also for long texts perhaps the tooltip should break rows?

**Comment by wlingke** [comment]
+1

**Comment by borey** [comment]
+1

**Comment by oli107** [comment]
+1

**Comment by websirnik** [comment]
+1

**Comment by lievenjanssen** [comment]
Any idea why this is put in the backlog? Seems like a small fix and a lot of people request it. (+1 for me as well)

**Comment by WuDo** [comment]
+1 (and another +1 from #4043 )

**Comment by christrude** [comment]
+1

**Comment by andrea-vega** [comment]
+1

**Comment by verkestk** [comment]
+1

**Comment by webley** [comment]
+1

**Comment by dohomi** [comment]
+1

**Comment by michaelkrog** [comment]
It seems to be that even though md-direction is 'bottom' by default, specifically setting it fixes the issue to some extend (at least in Chrome).

Check out this codepen:
http://codepen.io/anon/pen/dGYaMQ

**Comment by shyambhiogade** [comment]
thanks this works.

**Comment by dohomi** [comment]
@michaelkrog your fix doesn't work in my case. Tooltips inside of ```md-content``` are not visible on the edge, even if I set the ```md-direction="bottom"```

**Comment by ccstevenson** [comment]
I just wanted to comment that we encountered this issue.

![tooltip](https://cloud.githubusercontent.com/assets/4258816/13540927/889409d6-e216-11e5-8012-6cde34871d4f.gif)

[Codepen here.](http://codepen.io/Toph/pen/QNjaKd)

In our case (and in this demo), removing `layout="row"` from the `<body>` avoids the issue. We were using `md-direction="bottom"` tooltips with icons toward left and right edges of the screen. This CodePen is meant to display the worst-case scenario.

**Comment by epelc** [comment]
@ccstevenson not using `layout` on `body` fixes at least 1 other issue btw.

**Comment by drkhannah** [comment]
so is there a fix for this? I have the same issue, Setting a max-width:100px works, but its far from elegant or a real solution
