### ISSUE TITLE
md-grid-list inside ui-view compile error

### ISSUE THREAD

**Issue by ioanes** [angular/material#2038]
I think there is a bug when md-grid-list is nested inside ui-view. When I route to another view, md-grid-list is destroyed in bad order.

 First it destroy md-grid-list and then md-grid-tiles and it throws compile error, that grid-tile directive has dependency on grid-list directive, witch doesnt exist anymore.

I created a plunker to simulate the problem, open console and click on link.

http://embed.plnkr.co/ZdEP5pBwXRQxXtYbsHSe/preview

If I am using it somehow wrong, please put me in the right direction.

thanks

**Comment by ThomasBurleson** [comment]
Interesting...
@shyndman - any thoughts?

**Comment by epelc** [comment]
I just ran into this same problem earlier today with `md-radio-group` and `md-radio-button`. I think it's because the directives use `required` to get the parent directives controller but it breaks in certain layouts.

I had to mess with it a bit but I think I ended up using ui-routers views with an unnamed view to get around it.

**Comment by ioanes** [comment]
@epelc you are right, it's working. Good fix for now. Thanks

.state('home.item', {
     url: "item",
     views: {
          "@" : {
               templateUrl: "item.html",
           }
       }
});

**Comment by shyndman** [comment]
Closing this for now. Doesn't seem related to the md-grid-list itself.

**Comment by trainerbill** [comment]
I am running into this issue as well.  I am guessing that you can't use ui-view on md-grid-tile?

![image](https://cloud.githubusercontent.com/assets/3578259/14266831/d73100de-fa90-11e5-875e-fdefde0d1769.png)

```html
<md-content layout-padding>
  <md-grid-list
        md-cols-gt-md="12" md-cols="3" md-cols-md="8"
        md-row-height-gt-md="1:1" md-row-height="4:3"
        md-gutter-gt-md="16px" md-gutter-md="8px" md-gutter="4px">

    <md-grid-tile ui-view="profile" md-rowspan="3" md-colspan="2" md-colspan-sm="1" md-colspan-xs="1"></md-grid-tile>
    <md-grid-tile class="green" md-rowspan="3" md-colspan="2" md-colspan-sm="1" md-colspan-xs="1"></md-grid-tile>
  </md-grid-list>
</md-content>

```
