### ISSUE TITLE
Vertical scroll bar broken in textarea

### ISSUE THREAD

**Issue by ChristinaElaine** [angular/material#2039]
The scroll bar doesn't work correctly in textarea. Using your Basic Usage input demo (https://material.angularjs.org/#/demo/material.components.input) I added the following style on the textarea:

style="max-height: 25vh; overflow-y: auto;"

This works to show the vertical scroll bar when the text lines exceed the max height, but the scroll bar does nothing and you can never see the text that is below the visible height.

**Comment by marcysutton** [comment]
Looks like the textarea component dynamically sets a height for some reason. After looking at the [spec for multi-line textfields](http://www.google.com/design/spec/components/text-fields.html#text-fields-multi-line-text-field), there is no mention of limiting the height. However, it could be a confusing user interaction to have internal scrolling when there is a character counter on the bottom, which should always be visible.

Are you intending to limit scroll with the character counter? Perhaps we need to make a distinction and only set an inline height when `md-maxlength` is present.

**Comment by ChristinaElaine** [comment]
I want to be able to limit the size of the text area while still being able to see the character counter. At the moment since the scrollbar doesn't work on the textarea I have to set a scrollbar on a div containing the textarea, which is ugly, doesn't function properly, and hides the counter.

We have a modal dialog that is somewhat narrow but has a textarea with a max length of 500. The dialog itself has a maximum height but we need to limit the height of the textarea so that a scrollbar doesn't appear for the entire dialog. Here is the dialog when we haven't reached the max height, which looks as it should:

![dialognoscroll](https://cloud.githubusercontent.com/assets/7013389/7594249/ed3acd04-f8a4-11e4-9ed2-e16ccf4e1966.png)

Here is the dialog when we have reached the max height, which adds a scrollbar on the div because the scrollbar on the textarea is broken, which also hides the counter:

![dialogscroll](https://cloud.githubusercontent.com/assets/7013389/7594519/c5631b9a-f8a6-11e4-9cb6-292aab0c913f.png)

And here is what we would ideally like to see, which does actually display correctly when we set ```style="max-height: 25vh; overflow-y: auto;"``` on the textarea, but the scrollbar is not movable so you can never see the text that is below the max height cutoff:

![dialogscrolldesired](https://cloud.githubusercontent.com/assets/7013389/7594543/fed6fba8-f8a6-11e4-9962-4ef681ed63dc.png)

**Comment by chauduc** [comment]
Yes!!! i have the same problem like ChristinaElaine.
I think we need an option for scrolling or auto increase height textarea.
Because increasing height of textarea is cause of push submit button to bottom.
Sorry for my bad english

**Comment by zhulduz** [comment]
+1

**Comment by alexey-shaposhnikov** [comment]
hope you can fix this miserable bug. 
![3000397](https://cloud.githubusercontent.com/assets/2097562/7746393/545dd71a-ffcb-11e4-9816-880043582c4c.png)

**Comment by PDSBGreg** [comment]
+1. Expanding textareas are great everywhere, except for inside of a mdDialog, where the scrolling in the textarea breaks the scrolling in the mdDialog..

**Comment by MaximShoustin** [comment]
+1

**Comment by thebigredgeek** [comment]
Any update on this?  Seems to still be broken...

**Comment by petarsubotic** [comment]
I (sort of) addressed this by wrapping the textarea / input-container in a div styled with overflow and max-height.

Prior to doing that i tried stopping propagation and giving the the md-no-autogrow directive a whirl without success.

**Comment by csotomon** [comment]
+1

**Comment by vssystemluba** [comment]
+1 on fixing this issue!!!

**Comment by betcn** [comment]
RAWR!!! TRIPLE BUMP

**Comment by rriemann** [comment]
Have you found a workaround for production?

**Comment by BenniG82** [comment]
With material 1.0.1 the following works for me:
Style:
```css
md-input-container textarea[md-no-autogrow].md-input {
    height: inherit;
    overflow-y: auto;
}
```

```html
<md-input-container>
	<label>MyLabel</label>
	<textarea rows="5" ng-model="ctrl.model"
		md-no-autogrow/>
</md-input-container>
```

**Comment by uriva** [comment]
+1

**Comment by lukengda** [comment]
+1
Solution from @BenniG82 works fine. Should be the default behaviour if autogrow is disabled!

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (622/500 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:57983 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdM-000Lmv-P9
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:34:00 -0500
Date: Thu, 28 Apr 2016 13:32:28 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875548;
	bh=BFMEuIXW0nrRbP6dGoU7KqYrSymA7j+Kaws/XlBpXTM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=T3JFSSDaoQLJDW/D+5PChWf9zNRHjQcjlTdRQLe3NbPEyFL3BB/LGrceKcHPWDkUv
	 HMKVhM3dk5Qg+N1kSc14g8irqDzD6bGffu9k7hZjcalSXxe5hjBFG7uDBMO6NX/sw4
	 dL9I4fnVDDWy9Afc3RFncqY5Q7mVR9I7IovQuSwE=
