### ISSUE TITLE
Subheader: sticky without setting a height?

### ISSUE THREAD

**Issue by robertbaker** [angular/material#2041]
In the demo, https://material.angularjs.org/#/demo/material.components.subheader
height is set and it works, but viewports can change, different devices have different widths.

How can I get this to work without setting a constant height?

**Comment by CreativityKills** [comment]
I was also wondering the same. Spent hours trying to figure this one out and NOTHING!

**Comment by marcysutton** [comment]
Sounds related to https://github.com/angular/material/issues/2047.

**Comment by guiporto** [comment]
Same here. I spent quite some time trying to figure it out with no success...

**Comment by guiporto** [comment]
BTW the title of this issue should mention md-subheader instead of md-header. That makes it even harder to find through GH search

**Comment by mackelito** [comment]
Kind of works if you use eg. height: 100vh; but that can bring other issues..

**Comment by mackelito** [comment]
Could this please be reopened?
The requirement to have a fixed height is really not a good one :)

**Comment by jayeshanandani** [comment]
Refer: [Spring Cleaning 2016.](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk)

**Comment by mackelito** [comment]
@jayeshanandani yeah I did read that one but I´m not sure that any of those points really apply to this ticket.. or does it? :)

I guess te same issue apply on the toolbar directive..
Not even the demo is working properly: https://material.angularjs.org/latest/demo/toolbar

Often when reloading the demo it shrink stopps working (On mac/chrome at least).

(But perhaps that should be a different issue..)

**Comment by jayeshanandani** [comment]
@mackelito You can reopen the issue by filing a new one, giving steps to reproduce and pointing to this bug. They have said you can file new issues by referencing old ones with proper and description and template the one that is there on their discussion link.

**Comment by kvindasAB** [comment]
+1 It does not make much sense for subheaders to work only on fixed height containers.

**Comment by whittssg** [comment]
Did anyone figure this out? Thanks
