### ISSUE TITLE
tabs: content does not fill container height

### ISSUE THREAD

**Issue by ngraef** [angular/material#2043]
After the f34eb800212b6daa11d3a23c14a5a173d9691cf3 refactor, tab content has a 200px height. Expected behavior is to fill the height of the `md-tabs` element. You can see the issue on any of the demo pages:
![image](https://cloud.githubusercontent.com/assets/1031317/6859607/d0192e90-d3e8-11e4-9134-3a6af2a2d8bd.png)

There are a couple other minor issues here that get corrected after any interaction with the tab bar:
1. Accent at the bottom of tabs is the full width of the tab bar
2. Tab scroll arrows display even though they're not needed.

**Comment by JesseBuesking** [comment]
Might be https://github.com/angular/material/commit/f34eb800212b6daa11d3a23c14a5a173d9691cf3#diff-c6c4ddbc06f571d9917ab9376705098bR168. I was just using the docs and disabled the overflow so it would expand :smile:
