### ISSUE TITLE
md-autocomplete always select the first result

### ISSUE THREAD

**Issue by ptgamr** [angular/material#2044]
Hi everybody, 

Currently, width `md-autocomplete` directive, when you type something and have suggestions, it always force you to select the first option when pressing enter.

This is not a really good ux experience though. Let take youtube search box as example, when you have suggestion, you have choice to not choose the suggestion, and search with only your search text.

I think I'll give it a fork. How do you think?

**Comment by robertmesserle** [comment]
This should be a configurable option - should be pretty easy to add.

**Comment by ptgamr** [comment]
Thanks guy :+1:
