### ISSUE TITLE
Input placeholder not showing up on IE11

### ISSUE THREAD

**Issue by RobAikins** [angular/material#2045]
When you have an input with no label, IE11 isn't showing the placeholder.
![screenshot 2015-03-26 20 34 09](https://cloud.githubusercontent.com/assets/3433231/6861703/c0309f04-d3f7-11e4-919d-e1a29791a4db.png)

**Comment by scisci** [comment]
This might work, I had the same problem in firefox:

md-input-container:not(.md-input-has-value) input:not(:focus) {
  color: inherit;
}

The error was because of an angular css:

md-input-container:not(.md-input-has-value) input:not(:focus) {
  color: transparent;
}

**Comment by Splaktar** [comment]
This might be fixed by #3582. I'll have to setup a Windows dev environment to test this. Hopefully tomorrow...

**Comment by Splaktar** [comment]
Verified that #3582 fixes this on IE as well as Firefox.
