### ISSUE TITLE
Toolbar should resize height based on media

### ISSUE THREAD

**Issue by asans** [angular/material#2047]
According to [Material Designs Guides for Layout Structure of App Bar](http://www.google.com/design/spec/layout/structure.html#structure-app-bar):

Metrics

Default height:
Mobile Landscape: 48dp
Mobile Portrait: 56dp
Tablet/Desktop: 64dp

For extended app bars, the height is equal to the default height plus content increment(s).

Under desktop resolution, the toolbar is 64dp.  However, as I resize to smaller resolution, the toolbar height does not change and continues to stay at 64dp when it should resize appropriately to the correct height.

**Comment by marcysutton** [comment]
@ThomasBurleson the new Typography styles use `rem` units as "scaleable pixels" based off the body but we don't actually change the font size when the resolution changes. If we did, other rem units such as heights and margins would automatically change. Something to think about when reviewing this issue. It would be an easy thing to do now that we're using rems.

**Comment by asans** [comment]
In addition to the toolbar resizing, the app bar buttons to the right should also have the margins/padding adjusted.

For smaller media screens:

![layout_structure_appbar_metrics1](https://cloud.githubusercontent.com/assets/17964/7620445/ca004dca-f974-11e4-87c6-bdbca2625ba9.png)

For larger media screens:

![layout_structure_appbar_metrics7](https://cloud.githubusercontent.com/assets/17964/7620448/cfd4638a-f974-11e4-957d-2a88a61f7363.png)


__NOTE:__ The spacing on the right is calculated from the right edge of the toolbar to the button image's right edge (without the padding), _not_ to the edge of the 48x48 button size with padding.

**Comment by Davidriquelme** [comment]
are we expecting this in 1.0 ?
