### ISSUE TITLE
md-on-select for tab not triggered

### ISSUE THREAD

**Issue by kschwidder** [angular/material#2049]
md-on-select is not triggered on latest master commit when tab is selected

**Comment by ThomasBurleson** [comment]
@kschwidder - re-adding event support to Tabs is in-progress.

**Comment by dmackerman** [comment]
Can confirm.

**Comment by robertmesserle** [comment]
Closed by c84899df1036804db1b435ca4c6f92e01c7e12e6

**Comment by ismarslomic** [comment]
+1
