### ISSUE TITLE
mdTabs md-tabs-content-wrapper min-height issue

### ISSUE THREAD

**Issue by rem4ik4ever** [angular/material#2052]
Recent mdTabs change affected height. Class "md-tabs-content-wrapper" sets height to 200px and hides the rest of the content

![tabs-issu](https://cloud.githubusercontent.com/assets/3874496/6870467/e57fe688-d461-11e4-989b-a86b7eba092a.png)

**Comment by ThomasBurleson** [comment]
dup #2043
