### ISSUE TITLE
autocomplete - cant bind to model

### ISSUE THREAD

**Issue by TomPenn** [angular/material#2053]
I think this boils down to two separate but linked issues. [I say can't, but this maybe because I don't know how]

1) You can't bind an md-autocomplete to the model. 
Say I have a form I want to complete, the form may have some data already populated from the model, this may include the autocomplete field. I can't figure out a way to show this value in the auto complete. I want to show it because they may want to change it and I want to show the current value using the autocomplete.

2) With ui-angular you can specify the value aswell as the name for the typeahead control. ie
typeahead="item.ID as item.Name for item in getPeople($viewValue)" This is handy because I can now directly use the ID if I bind the typeahead with ng-model. I cant find a sytax that works the same for md-autocomplete I'm always ending up with the entire item object in my model.

**Comment by bvaughn** [comment]
+1

**Comment by robertmesserle** [comment]
@TomPenn Can you provide an example of what you are asking for in the 2nd one?

**Comment by tic2000** [comment]
I'm not TomPenn, but I imagine he wants this:

http://plnkr.co/edit/q1ircjbSXzesaysfN7tp?p=preview

Even if the input displays only the state name, ng-model stores the whole state object (name and flag).

**Comment by robertmesserle** [comment]
@tic2000 This is already how `md-autocomplete` works:

http://plnkr.co/edit/bvSJMw5vIpQVtOQVIWDx?p=preview

However, we do have the goal of supporting a more complete subset of the `md-repeat` syntax, as in your original example.

**Comment by robertmesserle** [comment]
Closing for now, but there will be a new issue addressing the `ng-repeat` syntax.

**Comment by nshahpazov** [comment]
>I cant find a sytax that works the same for md-autocomplete I'm always ending up with the entire item >object in my model.

I also can't find a way to point to which property the selected item points to. When I use:
``` html
<md-selected-item="someObject.code">
```
My code property becomes the entire object which is selected and I want it to point to a particular property in that selected object. The way it is in ng-options
``` html
< select ng-options="obj.code as code.name for obj in objects">
</select>
```

If the syntax doesn't support such functionality, is there any other way of achieving the same results?
Thanks
