### ISSUE TITLE
toolbar scroll shrink doesn't play nice in mobile safari

### ISSUE THREAD

**Issue by ianqueue** [angular/material#2055]
Simply look at the example page for it on an iphone6, start scrolling fast to bottom and back up, it kind of sticks at times.  The documentation is also a little confusing especially around the md-content height.  I assume it has to equal the height of the viewport if you are trying to make this a primary navigation.  Would be nice if you didn't have to specify.

https://material.angularjs.org/#/demo/material.components.toolbar

**Comment by NickBolles** [comment]
I have a fix for this in my PR #3735 which includes a fade scroll header. But is not ready to be merged yet.
