### ISSUE TITLE
Nested layout-fill working in Firefox, not Chrome

### ISSUE THREAD

**Issue by jonahbron** [angular/material#2058]
It seems that the top-level `layout-fill` works in Chrome, but if you nest more `layout-fill` within it, it breaks in Chrome.  Simple Codepen here to demonstrate problem:

http://codepen.io/jonahbron/pen/PwLbRJ

If you view it in Firefox, the entire page background should be gray.  if you open it in Chrome, you'll see a gray bar at the top, with the rest of the page a bright red.

**Comment by jonahbron** [comment]
Interestingly enough, if you look at the element in the inspector, FF shows a `height: inherit` style, but Chrome doesn't.  If you explicitly add it in Chrome, suddenly it works.  But if you look at the source file in Chrome, the style declaration is there.

![Wat](http://i.imgur.com/y04FN5N.gif)

**Comment by ngraef** [comment]
Related to #1895 and [Chromium bug 346275](https://code.google.com/p/chromium/issues/detail?id=346275).

**Comment by jonahbron** [comment]
@ngraef Thanks for the workaround.  Looks like this one is pretty much a duplicate of the other one, you can close this one if you so choose.

**Comment by marcysutton** [comment]
This issue is 100% better due to the amazing animated GIF, but I am going to close as a duplicate.

**Comment by jonahbron** [comment]
Thank you @marcysutton.
