### ISSUE TITLE
md-search-text-change in md-autocomplete doesn't work when delete select text

### ISSUE THREAD

**Issue by caok2709** [angular/material#2061]
Hello guys!
I think I found a bug for md-search-test-change.
This directive can't detect search text is empty if user do this :
<md-autocomplete ng-class="{'md-autocomplete-has-value': experiment_searchText}"
       ng-disabled="false"
       md-no-cache="false"
      md-selected-item="selectItem"
      md-selected-item-change="checkSelectItemStatus(selectItem);"
      md-search-text-change="selectItemTextChange();"
      md-search-text="selectItem_searchText"
      md-items="item in querySearchExperimentList(selectItem_searchText)"
      md-item-text="item">
 </md-autocomplete>

If user first type: "abc", the md-search-text-change do will be called. There is no problem.
However, if the user firstly input a word "abc"  in the input box and then delete them together or just press delete on the keyboard ,the md-search-text-change won't get a chance to call.....
Which means: there is no way to determine if the search text  is empty or not. 

I know there is a button at the end for input box. If we press that clean button, the search text will gone. and    the model bind to md-selected-item will gone....
Question is:   you can't force user to press that button to clean the selectItem model ...

Anyone know , how to tell if the search text is empty when user clean them by the way I gave?

**Comment by caok2709** [comment]
I checkout the source code of angular-material.js
on line: 10181  function  handleSearchText may need to fix.
if the searchText is empty and length is less than the minLength, it will return the function . 
The last two lines: 
 if ($scope.textChange && searchText !== previousSearchText)
        $scope.textChange(getItemScope($scope.selectedItem));  won't even got called.

So we can't just return the function  we still need to check the searchText and previousSearchText. 
if previousSearchText is no undefined (which means it do have a value). .... then we need to run another logic. Otherwise, any function in md-search-text-change won't get called.

 function handleSearchText (searchText, previousSearchText) {
      self.index = -1;
      //if ($scope.textChange && searchText !== previousSearchText)
       // $scope.textChange(getItemScope($scope.selectedItem));
      if (!searchText || searchText.length < Math.max(parseInt($scope.minLength, 10), 1)) {
        self.loading = false;
        self.matches = [];
        self.hidden = shouldHide();
        updateMessages();
        return;
      }
      var term = searchText.toLowerCase();
      if (promise && promise.cancel) {
        promise.cancel();
        promise = null;
      }
      if (!$scope.noCache && cache[term]) {
        self.matches = cache[term];
        updateMessages();
      } else {
        self.fetch(searchText);
      }
      self.hidden = shouldHide();
      if ($scope.textChange && searchText !== previousSearchText)
        $scope.textChange(getItemScope($scope.selectedItem));
    }

**Comment by piyushchauhan2011** [comment]
Not working for me in 0.10 release :disappointed:
md-search-text-change is not getting called!

**Comment by piyushchauhan2011** [comment]
Sorry working fine now.!
