### ISSUE TITLE
md-swipe-left demo

### ISSUE THREAD

**Issue by dvisockas** [angular/material#2063]
Hello guys,

Didn't know where else I should write this. But in your directives documentation of md-swipe-left (or right) you have a button in a header that should point to the demo. I can see the link pointing to /demo/material.components.swipe, but every time I click that I get redirected to the main page. IMHO it shouldn't be there (the link) if there is no demo.

**Comment by marcysutton** [comment]
Thanks! This is a known issue. Closing as duplicate: https://github.com/angular/material/issues/1911

**Comment by marcysutton** [comment]
Hiding the link until the demo is created. That is tracked in #1911.

**Comment by matthewrfindley** [comment]
@dvisockas  We decided to add a basic demo.  In the future this page will be the home of any additional demos for md-swipe-{left | right}

**Comment by dvisockas** [comment]
:heart: :heart: :heart:
