### ISSUE TITLE
subheader broken, there is a way to use it? 

### ISSUE THREAD

**Issue by marco64bit** [angular/material#2064]
subheader" layout direction"

![screenshot_2015-03-27-21-37-17](https://cloud.githubusercontent.com/assets/5896864/6880690/6d730af6-d53f-11e4-9c61-35833dc36061.png)

![screenshot_2015-03-27-21-37-37](https://cloud.githubusercontent.com/assets/5896864/6880685/2602cee0-d53f-11e4-8008-b74f2e5dd875.png)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by naomiblack** [comment]
This does not seem to be an issue with the current site. Please do file a new issue if you see it again on HEAD.
