### ISSUE TITLE
"Basic Usage" and "Dynamic Tiles" are blank on small window

### ISSUE THREAD

**Issue by casertap** [angular/material#2070]
If you go to:
https://material.angularjs.org/#/demo/material.components.gridList

resize your browser widow in small and refresh the page, you will see that  "Basic Usage" and "Dynamic Tiles" are blank.
The same thing happen when I try the exemple code locally.

But if you resize the browser window, you will see that the grid appear.

**Comment by ThomasBurleson** [comment]
Definitely reproducable (when the sidenav is not open) and the page is refreshed.

**Comment by ThomasBurleson** [comment]
Fixed in f037b8cb9e4db8b
