### ISSUE TITLE
wechat browser support

### ISSUE THREAD

**Issue by calidion** [angular/material#2075]
wechat browser is the most popular browser in china.
currently material design are not compatible with the wechat browser.

**Comment by vanntian** [comment]
微信内置浏览器不也是webkit的核么

**Comment by sindrenm** [comment]
@calidion Is Eric also the most popular name in China? :trollface:

**Comment by gustavohenke** [comment]
@sindrenm probably not :)
But what if he lives in China/works for a chinese company?

**Comment by calidion** [comment]
@vanntian 
wechat derived from webkit and rename/modified as X5 which is not an open source project.
@sindrenm 
Eric is very poplar in all over the world:)
@gustavohenke
yes. i am from china.
and works for chinese company:)

**Comment by yinhm** [comment]
wechat browser is a browser core embed in wechat application(may differ in iOS and Android version), and it is not open, and it is not respect standard neither. I don't think material angular should waste time on such closed platform.

**Comment by calidion** [comment]
The decision should be made by the materail angular team, the request should be filed by those need this support. It is not a battle between open source and closed source. let business be business.

**Comment by yinhm** [comment]
Agree the decision should be made by the material angular team. I was merely point out the fact: it is not that angular material not support wechat browser, it is because wechat was not a standard browser(and probably not intented to).

**Comment by calidion** [comment]
Material design even don't support standard compatible browsers produced today. Standards are changing.  Standard support may not be that strict like you think. And the supports are mutual.

**Comment by yinhm** [comment]
I can't help myself to wonder, follow the perspective you pictured, we must support IE6 too. How could we not support it and let it dying in the dust.

**Comment by calidion** [comment]
You mispictured. As too the way you picturing, we also need to support HTML 3.X

**Comment by calidion** [comment]
Before you start criticizing you need to investigate what is standard and how it evolves. Thanks.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
