### ISSUE TITLE
Overlapping child element

### ISSUE THREAD

**Issue by remicastaing** [angular/material#2077]
By using ``layout="column" layout-align="space-between center"`` inside small space (small screen), child element  are overlapping.

**Comment by remicastaing** [comment]
Here is an exemple on [codepen](http://codepen.io/remicastaing/pen/MYNadx).

![capture d ecran 2015-04-13 23 30 26](https://cloud.githubusercontent.com/assets/1715952/7125889/23d79788-e235-11e4-8e51-51122250aabe.jpg)

**Comment by DmitryEfimenko** [comment]
+1
Here is another [codepen](http://codepen.io/anon/pen/VLwGLw) example (this time using whiteframes) showing the same issue.
![overlappingimgs](https://cloud.githubusercontent.com/assets/2098175/7306423/f5e3b6cc-e9b9-11e4-8d1e-cd832c68e97a.jpg)

**Comment by alexcriss** [comment]
It seems that the issue is not really caused by layout-align="start center", if I remove it in both codepens I still see overlapping children.

Could it be related to #681?

This is rather annoying, if I put two long lists in <code>md-content</code> the two lists will overlap instead of being one below the other.

**Comment by mpfisterUniBE** [comment]
I can confirm this issue for Google Chrome on Android 4.4.4 and 5.0.2 and the Internet Explorer 11

However, in Chrome and Firefox for Windows as well as in Edge it works perfectly well (the first codepen example)

**Comment by ThomasBurleson** [comment]
Can you reproduce this issue with the lastest code in master (^ v0.11.0-rc2)?

**Comment by DmitryEfimenko** [comment]
I can't. Looks good!

**Comment by ThomasBurleson** [comment]
Also here is another sample:  http://plnkr.co/edit/gzgnhrcep2csk9vuHyeY?p=preview
