### ISSUE TITLE
Text does not appear in bubble of chip

### ISSUE THREAD

**Issue by futurechan** [angular/material#2080]
![image](https://cloud.githubusercontent.com/assets/3921584/6889274/94c5d8e4-d658-11e4-8521-5b2c5430bc7f.png)

**Comment by MilosStanic** [comment]
Same for me here. Plus the 'X' button is huge!

**Comment by ThomasBurleson** [comment]
Which os, browser, and version?

**Comment by futurechan** [comment]
Windows 7, Chrome, latest?

**Comment by marcysutton** [comment]
This is a duplicate of https://github.com/angular/material/issues/2081, which has more details.
