### ISSUE TITLE
Chips are broken in chrome on OSX

### ISSUE THREAD

**Issue by amay0048** [angular/material#2081]
The labels are not aligned correctly and the inputs will not let me type anything
![screen shot 2015-03-30 at 1 58 07 pm](https://cloud.githubusercontent.com/assets/6089717/6889584/0a616d70-d6e5-11e4-9dd3-6107ad27a93c.png)

We're forking this and fixing today. Check back with the master @ themeans/material tomrrow

**Comment by micrum** [comment]
Reproduced in Chrome 39.0 on Ubuntu 14.04
![selection_039](https://cloud.githubusercontent.com/assets/3502654/6895881/85b15b72-d6ed-11e4-9ab1-7add26ba9d85.png)

**Comment by danwkennedy** [comment]
Chrome on my Nexus 7 (2013) does the same

**Comment by dmackerman** [comment]
Broken on Chrome Canary as well.

**Comment by styx** [comment]
Same here

**Comment by ilanbiala** [comment]
@amay0048 fixed yet?

**Comment by typotter** [comment]
These chips buttons will be broken everywhere. https://github.com/angular/material/commit/a936e1edc964b69ffe5bf96905e348fc6f4c6b4d introduced a min-width for buttons and is the culprit here. Issue was not caught during the merge. Should be an easy fix.
