### ISSUE TITLE
Click events fire multiple times per click on mobile

### ISSUE THREAD

**Issue by buu700** [angular/material#2090]
http://codepen.io/anon/pen/qEvvGV

In a normal Chrome window this works as expected, but in my mobile simulator it logs "clicked" at least twice every time I click the button.

**Comment by dmonllao** [comment]
Yeah, same issue here with a cordova app; all good in 0.8.2 IIRC

**Comment by ThomasBurleson** [comment]
@dmonllao, @buu700  - can you retest with this [CodePen fork](http://codepen.io/ThomasBurleson/pen/xbedWo) that uses the latest from master?

> I only see 1 click logged each time.

**Comment by dmonllao** [comment]
Yep, I've just pulled master HEAD and all good, thanks.

**Comment by buu700** [comment]
Awesome, thanks! This works for me now (tested both your codepen and [a version with md-checkbox](http://codepen.io/anon/pen/dPLzgw)), though I'll note that the possibly-related #1704/#1972 is [still reproducible in master](http://codepen.io/anon/pen/yyroxb) (but [works with the latest stable code](http://codepen.io/anon/pen/RNOZYm)).

**Comment by ThomasBurleson** [comment]
Fixed in 2de0cf26a4e7fc985b6247039537311a7e7861c1
