### ISSUE TITLE
mdButton: default min-width excessive for small buttons

### ISSUE THREAD

**Issue by ngraef** [angular/material#2091]
A button's `min-width` added in a936e1edc964b69ffe5bf96905e348fc6f4c6b4d is too wide in certain use cases, including:

1. A  non-fab icon button ([demo](http://codepen.io/anon/pen/KwEEEw)):
![image](https://cloud.githubusercontent.com/assets/1031317/6909488/3fd5321c-d70c-11e4-81cd-93d259f6fbd6.png)

2. A short text button in an action toast ([demo](https://material.angularjs.org/#/demo/material.components.toast)):
![image](https://cloud.githubusercontent.com/assets/1031317/6907800/fb97f042-d6fe-11e4-9a19-764335fecb06.png)

**Comment by marcysutton** [comment]
I think small or icon buttons will need a special class, since there is nothing differentiating them from flat and raised buttons (which require the `min-width`).

**Comment by marcysutton** [comment]
This can be outlined in Toolbar + icon demos https://github.com/angular/material/issues/1796
