### ISSUE TITLE
mdSubheader: theme not applied to sticky clones

### ISSUE THREAD

**Issue by ngraef** [angular/material#2093]
If a non-default theme is applied, the inline subheaders are styled properly, but the sticky clones still have the `md-default-theme` class.

![image](https://cloud.githubusercontent.com/assets/1031317/6910256/66e5939c-d716-11e4-9c40-37ff7a5cac24.png)

[Demo](http://codepen.io/anon/pen/qEvwjy?editors=101)

**Comment by PaulMougel** [comment]
Copying the theme name to the `md-subheader` element seems to work for now:

```html
<md-subheader class="md-primary" md-theme="yourTheme">Header 1</md-subheader>
```

**Comment by whittssg** [comment]
I am still having this issue on the latest version (1.1.0 RC1). I am using dynamic themes like this  
```
$mdThemingProvider.theme('teal')
        .primaryPalette('teal', {
            'default': '500',
            'hue-1': '100', // use shade 100 for the <code>md-hue-1</code> class
            'hue-2': '600', // use shade 600 for the <code>md-hue-2</code> class
            'hue-3': 'A100' // use shade A100 for the <code>md-hue-3</code> class
        })
        .accentPalette('red', {
            'default': '500'
        })
        .backgroundPalette('grey');
    $mdThemingProvider.alwaysWatchTheme(true);

```
The sub header has the correct color until it becomes sticky then it takes the color of what i think is materials default color scheme (a purple color).

My sub headers are setup like this :

```
<md-subheader class="md-primary">
                                <div class="fa fa-file-o card-toolbar-icon"></div>General</md-subheader>
```

Sample: 
![image](https://cloud.githubusercontent.com/assets/6453857/13819714/d49b3080-eb70-11e5-82e4-21acc764f1d0.png)
