### ISSUE TITLE
Linear progress bar in indeterminate mode is moving too fast when width is large

### ISSUE THREAD

**Issue by rahul18gupta** [angular/material#2094]
Linear progress bar in indeterminate mode should change the animation speed based on width of progress bar Or we should be able to configure the speed of progress bar.

**Comment by nathanmarks** [comment]
@ThomasBurleson I've got some large indeterminate progress indicators in my app and was wondering about this. Do we know what the official UX method (google made apps, etc) is for determining the speed of the animation of linear indeterminate progress indicators?

I couldn't seem to find any numbers, just stuff regarding "authentic motion" which isn't really my expertise!
