### ISSUE TITLE
md-checkbox with no label adds "extra margin"

### ISSUE THREAD

**Issue by ValYouW** [angular/material#2096]
Hi,

When there is an md-checkbox with no label (`<md-checkbox type="checkbox" />`) the checkbox's label is getting rendered with its style (`margin-left: 10px`), that adds an unwanted space of 10 pixels.
It is easily solved by applying a style:
```CSS
md-checkbox div.md-label {
    display: none
}
```
Example on [jsFiddle](http://jsfiddle.net/r2uzeboy/3/)
Question is whether this is the intended behavior? I prefer not to define styles that are dependent on the controls inner structure...
Thx.

**Comment by marcysutton** [comment]
This was fixed in ab26480780677fae4dd9b5a6238fa531b50bed6e.

**Comment by ValYouW** [comment]
Thanks!
