### ISSUE TITLE
Tooltip on md-switch

### ISSUE THREAD

**Issue by JohnAReid** [angular/material#2097]
md-tooptip works on the label of the md-switch. 
Is it possible for the tooltip to work on the switch itself, as I tend to hide the label when in sm mode?

**Comment by supadupdip** [comment]
I did it by wrapping the entire switch code with the tooltip. If you're looking at the example for the tooltip you would remove the btn class to make sure it doesn't change the style of your switch.

**Comment by JohnAReid** [comment]
Yes thanks that worked - I put the switch and tooltip into a span - only problem was that the tooltip appears further down than before.

**Comment by marcysutton** [comment]
Can you provide a Codepen or Plunker showing your issue, along with any solutions you landed on? Wrapping the tooltip around a switch may cause accessibility problems, but without a demo it's hard to tell.

Thanks!

**Comment by JohnAReid** [comment]
Sorry for delay - here is an example:  http://codepen.io/anon/pen/JoVJXG
Out  of interest is there any reason why the tooltip will only allow a limited numbers of characters?

**Comment by marcysutton** [comment]
I'm not sure. There isn't anything in the spec about it, but I imagine there had to be some kind of limit (and definitely not two lines). Let's have that discussion over in https://github.com/angular/material/issues/656.

**Comment by rodrigotm** [comment]
+1

**Comment by george3447** [comment]
+1

**Comment by rschmukler** [comment]
Closing as the method described in the replies is the preferred approach.

**Comment by Nektro** [comment]
Is there any way this would make it's way to the docs over at
https://material.angularjs.org/latest/demo/switch ?
