### ISSUE TITLE
md-scroll-shrink: blank space shows up when you scroll down

### ISSUE THREAD

**Issue by DeGuitard** [angular/material#2100]
Versions: from 0.7.1 to 0.8.3
Browsers: tested on Firefox / Chrome on OSX, Windows and Android
Demo: [plnk.co](http://plnkr.co/edit/2JONrmCBHiZKqw0SjVPq?p=preview)

If you scroll down, you will se something like this:
![issue](https://cloud.githubusercontent.com/assets/5683287/6922758/c98e42f2-d7cd-11e4-9225-2bc9a0c5a02e.png)

We shouldn't see this white block when we scroll down.

From what I understand, if the toolbar has a height of 64px, the following settings will be applied to the md-content: ```margin-top: -32px;``` and ```-webkit-transform: translate3d(0px, -32px, 0px);```. I haven't been able to find a workaround.

**Comment by kyleledbetter** [comment]
dup of #449 right?

**Comment by DeGuitard** [comment]
Yes! My bad, I did a search, but with "md-scroll-shrink" term.
