### ISSUE TITLE
md-checkbox no check visible

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2101]
md-checkbox does not show an actual check when embedded into a table. So for instance:

<table class="table table-condensed table-stripped">
                                                <thead>
                                                    <tr>
                                                        <th></th>
                                                        <th></th>
                                                        <th>Clinic Name</th>
                                                        <th>spi</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr ng-repeat="spi in user.data.spis">
                                                        <td><md-checkbox layout-align="start start" ng-model="spi.isSelected" ></md-checkbox></td>
                                                        <td><a ng-click="editSpi(this)">Edit</a></td>
                                                        <td>{{spi.clinicName}}</td>
                                                        <td>{{spi.spi}}</td>
                                                    </tr>
                                                </tbody>
                                            </table>

![image](https://cloud.githubusercontent.com/assets/798281/6924579/81484176-d7a7-11e4-88d3-7e3122a50f9a.png)

**Comment by daw451-duplicate** [comment]
sorry on this one... looks like we blended bootstrap with this class: table-condensed

as a result it caused border-collapse: separate  which removes the actual check....

not sure if issue or not.....

**Comment by marcysutton** [comment]
We aren't supporting conflict issues with Bootstrap, sorry.
