### ISSUE TITLE
md-checkbox layout

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2102]
no playing nice when embedded into a table in terms of alignment. skewed down... tried series of layout settings but nothing seemed to work

![image](https://cloud.githubusercontent.com/assets/798281/6924848/5a9d13ce-d7a9-11e4-961b-1303d76dab48.png)

Seems that the display: block is what is throwing it off in the css....

**Comment by marcysutton** [comment]
It should probably be `display: inline-block`. The demos have it floated left, which would be an easy fix in the meantime.

**Comment by marcysutton** [comment]
@daw451-duplicate can you verify if this is still an issue, and/or provide a Codepen or Plunker we can use to debug? Thanks.
