### ISSUE TITLE
bower: latest components/modules 8.3 aren't received

### ISSUE THREAD

**Issue by ianqueue** [angular/material#2104]
When I do a 

```
bower install angular-material#0.8.3
```
I would expect to get the individual components of that version as well, instead I'm getting 0.7.0-rc3 for core/core.js, haven't checked the others.

**Comment by ThomasBurleson** [comment]
@ianqueue - yes the release is not properly rebuilding the `/modules/**/*.js` components

**Comment by ThomasBurleson** [comment]
Fixed in ffa46d5a9e978df6d99db536002fac8c6a22e6b3

**Comment by ianqueue** [comment]
Thanks Thomas, excited to be using this at LivingSocial. Also enjoyed your talk on angular and requires at my-conf last year. Excited to get my team to contribute more to this project.

**Comment by ianqueue** [comment]
Autocorrect :) requireJS at ng-conf

**Comment by ThomasBurleson** [comment]
@ianqueue - thanks for your support. Contributions are welcome. I think you will like the 0.9 release coming soon. And 0.10 will have new components: Menu, DateTimePicker, and more.
