### ISSUE TITLE
Button focus goes to nearby element when it's removed from the dom

### ISSUE THREAD

**Issue by calebegg** [angular/material#2105]
On Chrome for Android, when tapping on an md-button causes it to be removed from the dom (because of ng-if or similar), focus goes to a nearby element instead of going up a level to the body.

Here's an example:

http://codepen.io/calebegg/pen/QwPbxm

Clicking on Chrome on a desktop works correctly; after clicking, the button is removed and the focus is not visible. But on mobile, tapping on a button causes another one nearby to get focus.

**Comment by marcysutton** [comment]
That sounds like an issue with Chrome for Android, not `mdButton`.  I think if you want the focus to go to the body, you'll have to handle that manually.

**Comment by calebegg** [comment]
It doesn't happen with native <button>s though, only with <md-button>.

Why should the focus behavior be different from desktop or different from normal buttons?

**Comment by marcysutton** [comment]
Have you tested native buttons in a repeater like that, just to rule out other directives? `mdButton` itself isn't doing anything to trap or blur focus. It gets transcluded into a native `button` element, as well.

**Comment by calebegg** [comment]
Here's a test with native buttons that does not demonstrate the issue:

http://codepen.io/calebegg/full/LEvGNd/
