### ISSUE TITLE
div layout col column on IE11

### ISSUE THREAD

**Issue by mdelgadov** [angular/material#2107]
In IE11, when using layout-sm and other versions, column as layout works well:
i.e.: <div layout-gt-sm="column" layout-align="center center" 

but in a single div without any other markup in the div:
                div layout="colum"
                    md-input-container flex
                        label City /label
                        input ng-model="wizBr.address.city" required
                    /md-input-container
                /div

the row becomes collapsed and with very small font size (1px, maybe) pretty

but when I change div layout="col" instead, it shows properly...

div layout="col"...

In the image, you can see that the side of the input field has up-down arrows and don't have label (it has but it;s so small it doesn't show)
also, you can see that the first has layout = column whilst the other two have col and show correctly.

Thanks for your support.

![angularmaterial](https://cloud.githubusercontent.com/assets/1537551/6927453/88f2a01a-d7bb-11e4-9d1e-818a548e0bb3.png)

**Comment by marcysutton** [comment]
Hi, can you provide a Codepen or Plunker showing your issue? Thanks.

**Comment by ThomasBurleson** [comment]
Fixed with Layout changes in ^ v0.11.0-rc1
