### ISSUE TITLE
Grid List on Safari looks odd...

### ISSUE THREAD

**Issue by jyn** [angular/material#2111]
In safari, the grid list looks like this:

![safariscreensnapz001](https://cloud.githubusercontent.com/assets/83088/6934181/600ab2d4-d87c-11e4-9b65-8d5a4f1a5a6c.jpg)

It really should look like this:
![google chromescreensnapz001](https://cloud.githubusercontent.com/assets/83088/6934183/66777d50-d87c-11e4-94b3-3fdfd36db307.jpg)

I'm running OSX 10.9.5 on Safari 7.1.3

**Comment by ecunal** [comment]
Already reported at #1927
