### ISSUE TITLE
md-toolbar height

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2112]
small question why was the height of the toolbar made so tall? Most often its a waste of real estate... anyone else agree???

**Comment by marcysutton** [comment]
Which toolbar, and on what device/screen size? They follow the design spec for toolbars. That said, work has to be done to make sizes adapt to smaller screens. That issue is being tracked in #2047.

**Comment by daw451-duplicate** [comment]
marcy not so much on the top of page... i think those are appropriate but there is a need to have a smaller toolbar that is embedded in md-content. They tend so soak up too much space. I propose maybe a md-short class that is 20-30% reduced in height.

**Comment by marcysutton** [comment]
@daw451-duplicate We are going off of the Material Design spec, which has specific dimensions for toolbars (see http://www.google.com/design/spec/layout/structure.html#structure-toolbars). We are going to stick with the official recommended sizes for now (which need to be adjusted for smaller screens, as I mentioned), but you could opt to do your own custom implementation not tied to the spec.

**Comment by flick36** [comment]
Hi, sorry to revive this issue, but in that link it says that the toolbar should be 56px: wich is what i want, but the default in angular material is 64px, so... i think that's wrong?
