### ISSUE TITLE
can not set value as select n md-select

### ISSUE THREAD

**Issue by deshpandehrishikesh** [angular/material#2114]
I am trying to set 15 as default in my md-option using selected, it gets set but when I select other option from drop down it come as comma seperated value  instead of only selected value which I selected.
ex. I have set 15 as default value on initial load , but when I select 30 from  md-select it gives value as 15,30 instead only 30.
 
following code I am using

Can you please give me some input on that? is it kind of bug in md-slelect

![code](https://cloud.githubusercontent.com/assets/11226309/6938640/9a606342-d882-11e4-8343-be796d371c5c.JPG)
![demo](https://cloud.githubusercontent.com/assets/11226309/6938663/d7d48a96-d882-11e4-92fc-0aaf3f727b0c.JPG)

**Comment by deshpandehrishikesh** [comment]
every time I click on <md-select>, the page  scroll's up.  I removed the extra css and JS (except angular material js and css) files , this but still issue continues. kindly give your inputs on same.

**Comment by rschmukler** [comment]
Good find. Also it appears that this is not setting the initial model value either. Will take a look

**Comment by stewones** [comment]
+1

**Comment by tsuberi** [comment]
add attr placeholder="defualt value"
<md-select placeholder="defualt value"  ...
