### ISSUE TITLE
CSS Typography

### ISSUE THREAD

**Issue by shawnljj** [angular/material#2115]
I tried using some of the css typography classes, but no change was seen on my text. I then went to search through angular-material.min.css and found no matching classes for those shown on the website. Any ideas?

**Comment by ngraef** [comment]
I suspect you're using the 0.8.3 release. The typography styles were recently added to master (I believe last week) so they're only in the rawgit development version until the 0.9 release.

**Comment by marcysutton** [comment]
Yep, that's exactly right. The typography feature is only available on master, but it will be out in 9.0.0. We really need to make the docs site only build on a tag. Something like #988.
