### ISSUE TITLE
(Nitpicking) Chips demo allows empty string

### ISSUE THREAD

**Issue by danwkennedy** [angular/material#2116]
![demochips](https://cloud.githubusercontent.com/assets/501989/6941201/a5555ac8-d84b-11e4-9c33-0b003043424a.png)

Notice how we have an empty chip (after kumquat). This mostly just looks janky (especially if you turn read-only on since the 'x' goes away)

**Comment by Frank3K** [comment]
Fixed in f5cde80?

**Comment by danwkennedy** [comment]
Looks like it's still happening in the docs

**Comment by typotter** [comment]
PR 2120 will fix this
