### ISSUE TITLE
Hammer.js dependency

### ISSUE THREAD

**Issue by smashercosmo** [angular/material#2117]
Hammer.js dependency is still presented in bower package in modules/js/core/core.js

**Comment by ThomasBurleson** [comment]
This is because the components in `/modules` are not rebuilding during formal release.
If you run `gulp build-all-modules` you will see the `/dist/modules` no longer has any hammer references.

**Comment by ThomasBurleson** [comment]
Related to #2104.

**Comment by ThomasBurleson** [comment]
Fixed in ffa46d5a9e978df6d99db536002fac8c6a22e6b3
