### ISSUE TITLE
Theory question: location of the `Save` button for a form

### ISSUE THREAD

**Issue by mpiasta-ca** [angular/material#2121]
Let's say I have an `Account Settings` form where a user can go to update his details. And presume there needs to be a `Save` button the user can click to submit the form.

What is the material design standard for where we put that button?

I notice that right now, if I just put a button under an `md-input-container` element, at times it seems there isn't of a gap between that input container and the button (ie. if that input container has an error message). So if I wrap the button in an `md-input-container` of its own, that button becomes full-width (which is not desired).

So then I get to thinking, should I even be placing a button here at all? And in the material design standard, it looks like the `Save` button would be in the `md-toolbar-tools` section of the layout header.

If that's the case, what is the standard for that on a desktop (or larger) view? Is it still 

Second, does this mean my templates/views now need to also carry the `md-toolbar-tools` bit? In my previous builds, I've been able to use one static header/menu. But this would mean altering how the header functions as well, right? How did the angular.material team structure the views for material.angularjs.org, basically everything expect for the sidebar is being loaded with each page?

**Comment by marcysutton** [comment]
The [ngmaterial forum](https://groups.google.com/forum/#!forum/ngmaterial) would be a better place for this. Please reserve Github for issues or feature requests. Thank you!
