### ISSUE TITLE
Chips input inconsistent style

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#2123]
Take a look at this screenshot, the input is very different from something like autocomplete.

![screen shot 2015-04-01 at 6 05 21 pm](https://cloud.githubusercontent.com/assets/3695164/6953881/73c1649e-d89a-11e4-9720-720146d0c4cf.png)

**Comment by typotter** [comment]
Thanks for the look. Chips does not support autocomplete yet. I am working on just such a change :)

**Comment by ilanbiala** [comment]
@typotter I wasn't referring to it supporting autocomplete, but it should have styles similar to that of autocomplete especially with the input box. mdAutocomplete doesn't expose an outline, so why should mdChips?

**Comment by ThomasBurleson** [comment]
@typotter  - does the spec define focus state for Chips ?

**Comment by typotter** [comment]
@ilanbiala thanks for the clarification. I've adjusted the colours to match autocomplete.
@ThomasBurleson The spec does have a focus state, but I have conflicting specs (ACUX vs. Global) that I am also following up on.
