### ISSUE TITLE
md-autocomplete - scrollbar is flickering if results set differs significantly 

### ISSUE THREAD

**Issue by TalPasi** [angular/material#2124]
Assume the following list: A, AA, AAA, AAAA, AB, ABB, ABBB, ABBBB

With the filter limited to 4 results, if you would to enter 'AB' as the search string 
you will first get A, AA, AAA, AAAA, as than AB, ABB, ABBB, ABBBB as matching results.

The problem is that because of the animation duration, there is a brief moment in time, where both result sets are hosted by the ul, making it to occupy more space and triggering the scroll bar to appear.

With the animation turned off,there is no flickering effect.

I have forked 2 Codepens where one demonsrates the problem and the other is the same but with animation turned off.

[With animation] (http://codepen.io/anon/pen/azxWjg)
[Without animation] (http://codepen.io/anon/pen/VYNMKZ)

I wish there was an option to control if the animation is turn on or not, for these kind of situation which I am facing now.

Thank you,

Tal

**Comment by robertmesserle** [comment]
This is likely related to a bug that was addressed some time last week.  Currently, animations are disabled for autocomplete, so it should be a non-issue; however, we are working on getting them re-enabled, so I will confirm this issue once animations are working again.  (Requires a new feature just added to ngAnimate)
