### ISSUE TITLE
mdDivider: broken after list refactor

### ISSUE THREAD

**Issue by ngraef** [angular/material#2125]
There is a [`$compile:ctreq`](https://docs.angularjs.org/error/$compile/ctreq?p0=mdDivider&p1=mdDivider) error on the [divider demo page](https://material.angularjs.org/#/demo/material.components.divider). I couldn't find a cause after a quick look at the diff, but this is broken in every build after (and including) abb807d0dcb77b92132b5ab73d61f97aa953f461.

EDIT: It seems to only be broken for dividers in `md-list`s.

**Comment by sp4ke** [comment]
I tracked down the line of the commit that introduced the bug, checkout my line note
