### ISSUE TITLE
Docs: Homepage routing broken after Angular upgrade

### ISSUE THREAD

**Issue by marcysutton** [angular/material#2127]
For some reason the Angular logo linking to the homepage no longer routes correctly. I was able to isolate it to the Angular upgrade in 652b60c04d88d0a3c21e5f62c7ad3edc473c6f58.

In app.js, the route looks like this:
```js
$routeProvider
    .when('/', {
      templateUrl: 'partials/home.tmpl.html'
    })
```

Our HTML looks like this:
```html
 <a ng-href="/" layout="row" flex class="docs-logo">
          <md-icon md-svg-src="menu"></md-icon>
          <div class="docs-logotype">Material Design</div>
        </a>
```

When you click on the logo to go home, it now shows a blank view. I looked into it but wasn't able to quickly find a fix, so I'm opening this issue to capture it.

**Comment by jesselpalmer** [comment]
@marcysutton Are you still seeing this issue? I tried to replicate the issue, but things appear to be working ok as far as I can tell.

**Comment by ThomasBurleson** [comment]
Not able to reproduce.
