### ISSUE TITLE
refactored md-list no longer supports ui-sref

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2131]
```
<md-item ui-sref="newroute">
</md-item>
```

this should honour the ui-route routing as well as add the md-clickable class

**Comment by hodeyp** [comment]
update...

```
<md-item class="md-3-line">
    <div class="md-item-text" ui-sref="newroute">
        <h3>Some text</h3>
    </div>
</md-item>
```

...does work. Not sure if this is a bug or a design decision?

**Comment by rschmukler** [comment]
@hodeyp the issue is that `md-list` now ignores clicks itself, and requires them to go in nested items. With `ng-click`, this is done for you (automatically). Perhaps we should extend this to `href`, `ng-href`, `ui-sref`, and `ng-attr-ui-sref`.

This is because (from an accessibility standpoint) the `md-item` is already of `role="listitem"`. To be truly accessible, the inner element should have a `role="button"`.

**Comment by marcysutton** [comment]
:+1:  thanks @rschmukler 

Agreed that it should probably support `href` variants.

**Comment by Frank3K** [comment]
+1

I used this functionality before and was wondering why this wasn't working anymore.

**Comment by johnwebbcole** [comment]
+1 I added a workaround using ng-click to a function that used $scope.go

**Comment by bradmartin** [comment]
+1

**Comment by psaunders** [comment]
+1

**Comment by rafriki** [comment]
+1

**Comment by robinbolton** [comment]
+1 - I'd rather not have to call $state.go manually just to workaround this.

**Comment by lievenjanssen** [comment]
+1

**Comment by Izcalli** [comment]
+1

**Comment by datoulei** [comment]
+1

**Comment by weisk** [comment]
+1

my workaround was wrapping the item inside a div that holds the `ui-sref`...

```html
<md-list>
  <div ng-repeat="obj in col" ui-sref="route.any")
    <md-list-item>
    ...
```

**Comment by ehlerskon** [comment]
+1

**Comment by ejohansson** [comment]
+1

**Comment by felipest9** [comment]
+1

**Comment by rothanachoun** [comment]
+1

**Comment by antonwestman** [comment]
+1

**Comment by apinnecke** [comment]
+1

**Comment by guiporto** [comment]
+1

**Comment by navneet35371** [comment]
+1

**Comment by valera33** [comment]
+1

**Comment by ThomasBurleson** [comment]
@rschmukler - can you look into this ?

**Comment by super-coder** [comment]
@rschmukler   if i do what you suggests, add ui-sref attributes on md-item-content then i will have a dead space if items are uneven width. It will have a ripple but not work for changing URL

**Comment by anupdhabarde** [comment]
We can use $state.href() to create a link in controller and use it in the template
```javascript
expect($state.href("about.person", { person: "bob" })).toEqual("/about/bob");
```
