### ISSUE TITLE
md-switch with icon

### ISSUE THREAD

**Issue by JohnAReid** [angular/material#2132]
Are there any plans to implement an md-switch with an icon inside - such as the example taken from Youtube? Also noticed that Youtube places the label on the left, should this be an option? 

![image](https://cloud.githubusercontent.com/assets/7714810/6960932/b00df938-d91e-11e4-9193-7512fda72a7e.png)

**Comment by ThomasBurleson** [comment]
No, but you can easily use a label, mdIcon, and mdSwitch together.

**Comment by nausn97** [comment]
<img width="71" alt="screen shot 2016-05-17 at 3 57 25 pm" src="https://cloud.githubusercontent.com/assets/8539007/15320324/81a6d916-1c4d-11e6-8759-e1dc8896ede8.png">
<img width="80" alt="screen shot 2016-05-17 at 4 02 06 pm" src="https://cloud.githubusercontent.com/assets/8539007/15320323/819126d4-1c4d-11e6-8f0f-feac9493ebde.png">
How can I create this one.. example taken from inbox.google.com.
