### ISSUE TITLE
Date Input is not working in Firefox

### ISSUE THREAD

**Issue by neilhanekom** [angular/material#2133]
The date input does not render optional date picker in Mozilla Firefox. 

What is the workaround for this?

**Comment by gustavohenke** [comment]
I think this has not been implemented _yet_ by the Firefox team...

**Comment by marcysutton** [comment]
That is correct, it has not yet been implemented in Firefox. The Angular Material datepicker should help alleviate this, but it isn't yet available. That issue can be tracked in #648.
