### ISSUE TITLE
mi-icon-button alignment issue

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2134]
![screenshot](https://cloud.githubusercontent.com/assets/1916471/6961672/32fe9dc4-d925-11e4-9d3b-168809f0d86d.png)

I have an alignment issue with the new md-icon-button class as per the image. The print icon is slightly higher. The print `<md-button>` uses ng-href and the others are links to routes using ui-sref or ng-click attributes. As such the rendered directive for the `<md-button>` element is `<button>` for the ui-sref and `<a>` for the mg-href. Assume there is a css problem between the two elements? I tried to work it out but my css abilities are pretty weak i'm afraid.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
> Also recommend you provide a CodePen or Plunkr that demonstrates this issue.

**Comment by hodeyp** [comment]
@ThomasBurleson happy to put this into the forum but I thought that as this was core code with no modification from myself that this is a bug? I am only using the newly provided md-icon-button class pushed in the last couple of builds - surely the core platform should be handling alignment, hence me raising it as an issue instead of a question in the forum.
