### ISSUE TITLE
Latest master CSS : can't reference some elements directly anymore. Inconsistency?

### ISSUE THREAD

**Issue by bonatoc** [angular/material#2136]
md-tab {
      // some styling...
    }

is working on 
a15347c
, 
but in 
4e3a25b
, you have to reference like this, if a theme or a hue is applied : 

    md-tabs.md-default-theme.md-hue-1 .md-tab{
      // some styling...
    }

**Comment by marcysutton** [comment]
https://github.com/angular/material/commit/4e3a25b24dfccbcbbf7e1ded2fc686018925cba0 makes no changes to CSS. Can you clarify your question?

**Comment by bonatoc** [comment]
I think I'm confusing Angular versions with commits IDs.
The numbers I am talking about, are the ones found at the top of the released angular files : 
v.0.8.3 a15347c
 vs. 
v.0.8.3 4e3a25b

![capture d ecran 2015-04-04 a 22 28 19](https://cloud.githubusercontent.com/assets/956531/6994434/fb40eee0-db19-11e4-9369-46d56841b086.png)

![capture d ecran 2015-04-04 a 22 28 31](https://cloud.githubusercontent.com/assets/956531/6994435/07a9636a-db1a-11e4-925b-de8dad95a4ab.png)

**Comment by bonatoc** [comment]
I guess that 's just normal in the collaborative dev world, 
but I was surprised with so much changes in the CSS structure : 

![capture d ecran 2015-04-04 a 22 32 39](https://cloud.githubusercontent.com/assets/956531/6994466/eef5ad00-db1a-11e4-89c6-198f4a013266.png)

Do we have to expect major overhauls like this? Design got broken on an app because of the changes, and refactoring was needed.

I was assuming the project had some strict CSS guidelines/rules, so iterative developments don't break what's in place.

**Comment by marcysutton** [comment]
We definitely try to minimize breaking changes, but tabs were refactored to align closer to the spec. Any necessary breaking changes must be made before the 1.0 release, so it had to be done sooner than later. It was also discussed beforehand. See @naomiblack's comment on this in the [ngMaterial Forum](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ngmaterial/0mxRU9sBQRA/EtHKYvGPjdMJ):

>The "official" answer from me is: if you are prepared to test and verify that what we have built so far works well for your application, you can go ahead and work with the components that are available today, with two caveats:
> * We have some CSS changes coming in 0.9 that affect Tabs especially, so we suggest using a specific version (e.g. via CDN) and testing between releases if you use our components in production. There may be other CSS changes coming between now and our 1.0 release.
> * We will not be maintaining older release branches. What you see on the CDN is what you get. To get an idea of known issues, take a look at what is open on github.
>As for release dates -- please consider dates in our Milestones as "won't be complete before". These are working dates that we use to plan out what is and isn't feasible with our current team resources.

>For an actual release date for a stable 1.0 -- my official answer is "this summer, although we are working to get something out sooner".

**Comment by ThomasBurleson** [comment]
@bonatoc - please note that our CSS is generated from the *.scss (Sass) files. We adjust those settings/styles as we refactor improvements and identify bug fixes.

**Comment by bonatoc** [comment]
@ThomasBurleson 

I use Sass to extend the components for my needs. 
You're right, I should have mentioned the differences in the src/components/.scss files instead of the final css output. 

Anyway, I can perfectly understand the refactorings that can happen. 
Especially on the tabs component : it sure doesn't look like an easy one.
