### ISSUE TITLE
Android Stock Browser support

### ISSUE THREAD

**Issue by lukicdarkoo** [angular/material#2137]
I am building Cordova application with angular-material. Since version 4.4 Android's default WebView is built on top of Chromium and on these devices angular-material works fine. Cordova apps built with angular-material on Android with version below 4.4 is completely mess.

Is there any chance to support these devices? I would like support for Stock Browser on Android 4.0 and higher.

Based on 
https://developer.android.com/about/dashboards/index.html
48.5% of Android mobile devices running on Android 4.0 to Android 4.3.

material.angularjs.org on Android Stock Browser (Android version 4.2.2):
http://i.imgur.com/K2Rf1Ii.png
http://i.imgur.com/N1q9TRA.png
http://i.imgur.com/a0QJoYA.png

angular.io works fine, but they uses different versions of .css and .js file, angular-material.css (v0.7.1) and angular-material.js (v0.8.2).

**Comment by gustavohenke** [comment]
Hey @lukicdarkoo, that's something of my interest as well.
But so far I have been using Crosswalk - if it's an option for you, I recommend using it until Android 5 becomes the standard: https://crosswalk-project.org/

**Comment by lukicdarkoo** [comment]
From ~400KB to ~20MB. It doesn't look like good solution but for now it's only one. Thanks.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by aldo-roman** [comment]
Any update on this issue? I'm experiencing the same problem.
