### ISSUE TITLE
Icon color incorrect for background colors

### ISSUE THREAD

**Issue by robertbaker** [angular/material#2138]
Referencing: 6fc26fabfc97ea1d677eefec912ed1b5a8bbaca0

It seems icons that should be light on backgrounds are actually dark and vise-versa.

You also need to take into account md-warn, md-accent, md-hue, and the current background-color used in the parent element.

```md-fab md-warn md-hue-2 md-button md-default-theme``` 
using "blue" makes a dark icon on a dark red background.

icons need css overrides similar to what buttons and other elements have. Those elements change the foreground color based on the background color. For example, navbar vs navbar with md-accent.

Having just black as the icon color would be an issue for elements that changes color based on ui-state, theme used, md-warn, md-accent, and md-primary.

**Comment by robertbaker** [comment]
@rschmukler please implement proper icon coloring based on theme.

**Comment by marcysutton** [comment]
@robertbaker can you provide a demo that shows what you're trying to accomplish? It's hard to know what to change without having something to react to.

**Comment by robertbaker** [comment]
See Issue: https://github.com/angular/material/issues/2707

**Comment by marcysutton** [comment]
ok, I'm closing this as a duplicate. Thanks!
