### ISSUE TITLE
md-sidenav dont follow my finger.

### ISSUE THREAD

**Issue by marco64bit** [angular/material#2139]
can you make it draggable to open and close it (like Gmail, indbox, YouTube, Drive,  etc.. for mobike) ? now i can put and md-swipe on it but the swipe event is triggered only at the end of my touch movement.

**Comment by marcysutton** [comment]
Great idea! There are some issues for this open, it has been on the radar for a long time: https://github.com/angular/material/issues/35, https://github.com/angular/material/issues/1591. So I'm closing this issue as a duplicate.
