### ISSUE TITLE
md-autocomplete: Selection Hidden Under Other UI Elements

### ISSUE THREAD

**Issue by jimgibbs** [angular/material#2140]
This is for v0.8.3

I have several items placed on the page that create a form. I am using autocomplete to help with user input. The basic structure of the page is as follows:
```
<md-content>
   <div layout>
      <md-input-container/>
      <md-input-container/>
      <md-input-container/>
      <md-autocomplete/>
   </div>
   <div layout>
      <md-input-container/>
      <md-input-container/>
      <md-input-container/>
      <md-input-container/>
   </div>
</md-content>
```
The autocomplete will be hidden below the second row of input items.

**Comment by robertmesserle** [comment]
I believe this has already been resolved in master.  Closing.
