### ISSUE TITLE
Document available color classes in CSS section

### ISSUE THREAD

**Issue by marcysutton** [angular/material#2143]
It would be very helpful to list available color classes in our CSS documentation. Whether they are generated from the existing Theming service, an extended version of the mdColors service or scraping colors directly from the design spec is TBD.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
