### ISSUE TITLE
Chips accessibility improvements

### ISSUE THREAD

**Issue by marcysutton** [angular/material#2145]
Here are some things we can do to improve chips:

 * Put `tabindex="-1"` on `md-chips`, which is getting `tabindex="0"` from ngAria and ngModel.
 * The `role=presentation` on `md-chips-wrap > div` is unnecessary.
 * Make the chip one tab stop and wire up the DEL key to delete.
 * Put ng-click on the X with `tabIndex="-1"` to remove it from the tab order but allow clicks to remove.
 * The text in it can say something like "Apple delete" with the unique part coming first.
 * Removing a chip: Focus should be sent back to the parent `md-chips` element, so that focus is not dropped.
 * Input fields need `aria-label` values (or `<label for="">`, either on- or off-screen).

Question:
 * Should readonly chips have `tabindex`? 

Kudos for the existing keyboard support, this is shaping up to be an awesome component!

**Comment by ThomasBurleson** [comment]
@typotter - @marcysutton is our Aria Enforcer; she does a great job.
