### ISSUE TITLE
Two md-buttons side-by-side have incorrectly set margin in this case...

### ISSUE THREAD

**Issue by jturmel** [angular/material#2146]
Inside a toolbar we have two buttons, one has an ng-click the other a ui-sref (href), so both end up getting hit with the :first-of-type pseudo selector and then run right up next to each other.

Ideally whether the md-button ends up being a "button" tag or an "a" tag shouldn't matter in how they sit next to each other.

**Comment by marcysutton** [comment]
Closed with 1c19272a70e7690a5689bbd5f33a338c078a795c
