### ISSUE TITLE
Occasionally, rapidly clicking a checkbox will result in the wave effect not fading away

### ISSUE THREAD

**Issue by Luminess** [angular/material#2149]
Using Chrome Version 41.0.2272.118 m (64-bit)

It gets stuck like this:
![capture](https://cloud.githubusercontent.com/assets/6457338/6981636/f2c9b280-d9b9-11e4-8b3f-a7f7362d237c.PNG)

Tested here: https://material.angularjs.org/#/demo/material.components.checkbox

**Comment by ngraef** [comment]
Duplicated. Clicking doesn't make it go away.

![image](https://cloud.githubusercontent.com/assets/1031317/6984377/dc9d1644-d9ed-11e4-9180-a2bb4db62b2c.png)

**Comment by mleanos** [comment]
I've had this happen to me when rapidly clicking an md-tab-label using Firefox. Just in case this helps y'all.
