### ISSUE TITLE
Add Auto-Complete for Text Fields

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#215]
Specification: [Auto-Complete for Text Fields](http://www.google.com/design/spec/components/text-fields.html#text-fields-text-field-with-character-counter)

![image](https://cloud.githubusercontent.com/assets/210413/4077390/ad12bb80-2ec2-11e4-9c7f-47e4e2bd6643.png)

Includes:

*  Full-width
*  Inset
*  Full-width In-line
*  In-line

**Comment by mackelito** [comment]
Is this to be in version 0.0.7 or in 0.8.0?

**Comment by robertmesserle** [comment]
This is scheduled for 0.8, but you can preview by checking the wip-autocomplete branch.

**Comment by marcysutton** [comment]
This is a duplicate: https://github.com/angular/material/issues/956

**Comment by robertmesserle** [comment]
Closing - duplicate.
