### ISSUE TITLE
mdButton enhance to support input types.

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2151]
mbButton and FABs should be enhanced to support type="file" for built-in default triggers. 

### Current Solution:

Currently this is the only way to use mdButton to support `<input type="file">`:

To get `<input type="file">` to work with mdButton, you must use a `<label for="<link id>" />`. See below for working sample:

```html
<html>
  <head>
    <link rel="stylesheet" href="https://rawgit.com/angular/bower-material/master/angular-material.css">
    <style>
      #file-input { display: none; }
    </style>
    
    <script src="https://code.angularjs.org/1.4.0-beta.6/angular.js"></script>
    <script src="https://code.angularjs.org/1.4.0-beta.6/angular-animate.js"></script>
    <script src="https://code.angularjs.org/1.4.0-beta.6/angular-aria.js"></script>
    
    <script src="https://rawgit.com/angular/bower-material/master/angular-material.min.js"></script>
  </head>

  <body ng-app="app" >
    
    <div>
      <h2>File Upload with Material:</h2>
  
      <md-button>
        <label for="file-input">Select</label>  
      </md-button>
      <input id="file-input" type="file">
      
    </div>

    <script>
      angular.module('app', ['ngMaterial']);
    </script>
  
  </body>
</html>
```

@see [Plunkr](http://plnkr.co/edit/tX1BkAYEgdvRCWib0ZA0?p=preview)

**Comment by ThomasBurleson** [comment]
Also need way to support this using FAB icon buttons.

**Comment by marcysutton** [comment]
Nice one @ThomasBurleson!

**Comment by cmoiccool** [comment]
I tried a modified version with <code>md-fab</code> and <code>md-svg-icon</code> and it only worked when the icon inside the button was clicked, if you click on the button outside the icon, it doesn't work, you only see the ripple effect. (on Chrome for Macos)

You can see here http://plnkr.co/edit/41Z5QWoc2JfZuuDVSOfB?p=preview

**Comment by ThomasBurleson** [comment]
@cmoiccool - Try it again with the latest from #master. The SVG styles now use:

```css
md-icon {
  svg {
    pointer-events: none;
  }
}
```
Which then means that clicks are no longer captured by the svg.

**Comment by marcysutton** [comment]
It could also be that the label isn't filling the button because it's an inline element. `display: block;` in CSS may help.

**Comment by ThomasBurleson** [comment]
@marcysutton - you are right. This is a bug. 
```css
label {
display:block;
}
```
works. Perhaps we should some CSS to compensate.

**Comment by ThomasBurleson** [comment]
Perhaps:

```css
.md-fab label:[for] {
display:block;
}
```

**Comment by cmoiccool** [comment]
@ThomasBurleson - The example on plnkr should already use #master through
```
<link rel="stylesheet" href="https://rawgit.com/angular/bower-material/master/angular-material.css">
<script src="https://code.angularjs.org/1.4.0-beta.6/angular.js"></script>
<script src="https://code.angularjs.org/1.4.0-beta.6/angular-animate.js"></script>
<script src="https://code.angularjs.org/1.4.0-beta.6/angular-aria.js"></script>
<script src="https://rawgit.com/angular/bower-material/master/angular-material.min.js"></script>
```
@marcysutton - I tried to add ```display: block;``` to the ```<label>``` and/or to the ```<md-button>``` but it did not have any effect, it continues to get triggered only when the icon is clicked. Maybe I am not using the ```display: block``` the way you are suggesting

**Comment by cmoiccool** [comment]
I also tried ```label {
display:block;
}``` and it is better now, only the right and left edges (probably because of some padding or margin) continue to only show the ripple effect

**Comment by epelc** [comment]
@ThomasBurleson The buttons work well if you open the file upload with js.

Also if anyone is interested in making a file upload [ng-file-upload](https://github.com/danialfarid/ng-file-upload) works very well.

![image](https://cloud.githubusercontent.com/assets/5204642/7260367/85cc7cee-e837-11e4-91b6-2ea27d1479f3.png)

**Comment by daw451-duplicate** [comment]
ng-file-upload +1

**Comment by rgolea** [comment]
Hey! I've been searching a way to fix once and for all this fix:
```
<md-button class="md-fab" ng-disabled="progress">
        <label for="upload_photo">
            Upload
        </label>
</md-button>
<input type="file" id="upload_photo">
```
I think I found it but I don't really know the actual structure of material-design and I don't have the time to teach myself. I found that this is a better way to put it once and for all in an `<md-button type="file"></md-button>` or an `<md-file><md-file>`.

Please take a look at this codepen and maybe try to adapt it if possible.
http://codepen.io/chriscoyier/pen/cvnCt

**Comment by kuhnroyal** [comment]
@ThomasBurleson I couldn't get your solution to work in Firefox. Somehow the label inside the button doesn't seem to work there.

I adapted your Plunkr and added `class="md-primary md-raised md-button"` directly on the label. This works and looks ok but the ripple is not working.

http://plnkr.co/edit/pp5KMp2JtTvnnM5p9nfp?p=preview

**Comment by infacq** [comment]
@kuhnroyal thanks for this temporary solution. I use it for now. Hope there will be a solution for this

**Comment by kuhnroyal** [comment]
@infacq I ended up writing a small directive, which fires a click event into the input element. This worked on all browsers I testet. 

```javascript
  function click() {
    $element.find('input')[0].click();
  }
```

```jade
md-button.md-primary.md-raised(type="button" ng-click="click()" aria-label="Upload")
  md-icon(md-svg-icon="editor:attach_file")
  span Upload
input(type="file" multiple accept="application/pdf" style="visibility:hidden")
```

**Comment by kuhnroyal** [comment]
I updated the plunkr with `md-ink-ripple` on the label. Now the ripple is working.

However it always uses the default theme, this would need some CSS enhancements to support themes.

**Comment by renanfranca** [comment]
@kuhnroyal Could you update the plunkr with the directive solution? 

And thank you very very much!!!!!

http://plnkr.co/edit/pp5KMp2JtTvnnM5p9nfp?p=preview

**Comment by kuhnroyal** [comment]
What I finally ended up with is in that plunkr.

```html
      <label class="md-primary md-raised md-button" md-ink-ripple for="file-input">
        <span>Select</span>
      </label>
        
      <label for="file-input">Select</label>
```

The only issues was the missing ink-ripple, which works now after adding the `md-ink-ripple` directive to the label. I am using this across Chrome/IE/Firefox now.

**Comment by MaximShoustin** [comment]
I wrote this directive that works in CHrome/Safari/Firefox:
```
 angular.module('app', ['ngMaterial'])
 .directive('chooseFileButton', function() {
  return {
    restrict: 'A',
    link: function (scope, elem, attrs) {
        elem.bind('click', function() {
              angular.element(document.querySelector('#' + attrs.chooseFileButton))[0].click();
              });
            }
      };
    });
```

and html:

    <md-button choose-file-button="file-input" aria-label="xxx"
                class="md-fab" ng-click="">
        <md-icon md-svg-icon="photo.svg"></md-icon>
     </md-button>
       
      <input id="file-input" type="file">

---

http://plnkr.co/edit/5blQ8fJIhJV0hYM96PB2?p=preview

**Comment by faustomorales** [comment]
Thanks, MaximShoustin! I built off of your directive but tried to compartmentalize (i.e., avoid searching the entire document for the input element).

````
.directive('chooseFileButton', function() {
    return {
        restrict: 'E',
        link: function (scope, elem, attrs) {
            var button = elem.find('button');
            var input = elem.find('input');
            input.css({ display:'none' });
            button.bind('click', function() {
                input[0].click();
            });
        }
    };
});
````
Then you can use the directive this way (the requirement is to include a button and a file input inside the element).
````
<choose-file-button>
    <md-button aria-label="Upload a file" class="md-fab">
        <md-icon class="fa" md-font-icon="fa-cloud-upload"></md-icon>
    </md-button>
    <input type="file">
</choose-file-button>
````

**Comment by ThomasBurleson** [comment]
The **File Picker** feature has been deferred/bumped to a post-1.0 milestone.

**Comment by davemerwin** [comment]
@faustomorales thanks for that update! The code you provided works well and the isolation provided by the directive structure is great. 

There is only one thing, I can't figure out how to then show the selected file. I'm thinking something with a change event but I can't figure it out. Any thoughts?

**Comment by faustomorales** [comment]
Happy it helped you! If all you really need is to show the file name, then yes, a change event will be sufficient. You can bind to changes on the input and use `changeEvent.target.files[]` to access the file information. More details are available in [this StackOverflow post.](http://stackoverflow.com/questions/17063000/ng-model-for-input-type-file)

If you need to upload the file, I highly recommend using something like danialfarid/ng-file-upload, which is what I usually use and will take care of getting the files for you (making the above unnecessary).

**Comment by infacq** [comment]
file upload should have feature like on this (article)[http://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/]

**Comment by frapontillo** [comment]
@faustomorales your snippet doesn't work on Chrome, as it prevents selecting file from hidden inputs.

**Comment by faustomorales** [comment]
What version of Google Chrome? It works on 45.0.2454.85.

**Comment by frapontillo** [comment]
Mine is 45.0.2454.93.
Setting width and height to very small values, as suggested by @infacq, makes it work.

**Comment by Nosthertus** [comment]
+1

**Comment by rockmacaca** [comment]
My current solution to this is just allowing the template for md-button be a \<label\> if you specify the button is of type="file", using an angular decorator. I've tested it in recent versions of Firefox and Chrome.
```
$provide.decorator('mdButtonDirective', ['$delegate',
  function ($delegate) {
    var getTemplate = $delegate[0].template;
    $delegate[0].template = function ($element, $attrs) {
      if ($attrs.type === 'file') {
        return '<label class="md-button" ng-transclude></label>';
      } else {
        return getTemplate($element, $attrs);
      }
    };
    return $delegate;
  }
]);
```
And the markup is as simple as
```
<md-button type="file">
    Select a file
    <input type="file" nv-file-select uploader="$ctrl.uploader">
</md-button>
```
Lastly, you'll need css to hide the \<input\> element, I just use
```
.md-button[type="file"] > input[type="file"] {
  display: none;
}
```

**Comment by elekzalan** [comment]
+1
This **File Picker** feature is really needed.

**Comment by mikegoodstadt** [comment]
Why is has this been closed?

**Comment by JonasT** [comment]
Any update on this? People want it, and it has unexpectedly been closed out of the blue...
At least an explanation would be nice.

**Comment by Nosthertus** [comment]
@JonasT their explanation is that they are focusing on angular material 2, that uses angular 2.. so they decided to stop their development on this project.. just bug fixes will be done in here now

**Comment by Nosthertus** [comment]
sometimes i think they shouldn't have done that as they are starting over again a material design project for angular, so to have the features that were being worked on, we are forced to go on other modules, other libraries that might not just work as good as angular material is, on the other side.. angular 2 is way too faster than angular 1, but is bad to leave a project that does not have all the features

**Comment by ScottRFrost** [comment]
Ran in to this same issue styling input type=file, so I hacked together a quick solution without having to make extra directives / etc..  Basically, render the regular HTML dialog, but with the ugly browse button BEHIND the cute material button.  This is better than hiding the input control all together because you still can see the file name to let the user know which file they picked.  Only using position:relative and z-index, so it should work on even the oldest browsers supported by angularjs 1.x.

HTML:

     <label class="md-secondary md-raised md-button bring-forward" md-ink-ripple for="xFile">
          <span>Select File</span>
     </label>
     <input type="file" ngf-select ng-model="xFile" name="xFile" id="xFile" class="file-input-hide">

CSS:

     .file-input-hide {
         position: relative;
         left: -6em;
     }
     .bring-forward {
         z-index:10;
     }

**Comment by jimmykane** [comment]
Why is this closed? Please @ThomasBurleson  reopen
