### ISSUE TITLE
textarea initial height too tall

### ISSUE THREAD

**Issue by calebegg** [angular/material#2154]
In Chrome, the initial height of a `<textarea>` in an `<md-input-container>` is set to the height of two lines of text, but according to the Material spec, it should start out at the height of a normal text field and expand as the user types more

http://www.google.com/design/spec/components/text-fields.html#text-fields-multi-line-text-field

This can be demonstrated on the angular material site demo page:

https://material.angularjs.org/#/demo/material.components.input

(just delete all the content from "Biography", for example).

**Comment by lkaragol** [comment]
It's not just a Chrome issue. Same think on Safari and Firefox also like below. There is one extra line.

![screen shot 2015-04-10 at 12 02 32](https://cloud.githubusercontent.com/assets/7867743/7084798/8b1ad572-df79-11e4-800f-9979b1491506.png)

**Comment by maelfrize** [comment]
:+1:
