### ISSUE TITLE
md-bottomsheet displays above the view on top of page (using nested views ui-router)

### ISSUE THREAD

**Issue by robertbaker** [angular/material#2155]
using ui-router and a nested view with a parent abstract view.

```
.state('transaction', {
                  abstract: true,
                  // Note: abstract still needs a ui-view for its children to populate.
                  // You can simply add it inline here.
                  template: '<ui-view/>',
                  'controller': 'TransactionCtrl',
                  'controllerAs': 'transaction',
                  'url': '/transaction'
                })

                .state('transaction.new', {
                  'url': '/new',
                  'templateUrl': 'app/transaction/new/transaction-new.html',
                })
```

I have a input with ng-click that opens my 10-key bottom sheet.
```
 $mdBottomSheet.show({
        templateUrl: '/components/10-key/10-key.template.html',
        targetEvent: $event
      });
```

**Comment by marcysutton** [comment]
What is the parent of the view? Can you supply a `parent` to append it to the correct element?

**Comment by ThomasBurleson** [comment]
@robertbaker - you can specify a parent for the BottomSheet, otherwise the body is used.

**Comment by robertbaker** [comment]
Apologies for not looking at the directive doc more closely. Closing for now, can't test until monday, if it is a bug, I'll re-open.

**Comment by robertbaker** [comment]
A nice feature for the bottom sheet would be to scroll or push the parent element to the visible top and have the bottom sheet take up the rest of the space (still displaying the calling element).

I'm thinking of using a bottom sheet to show a 10key pad, but still display the input box for input entry. I realize this may be more trouble than what's it's worth and might just use ng-show instead.
