### ISSUE TITLE
angular-material.css adding a "margin" bottom in <html>

### ISSUE THREAD

**Issue by oswaldomilet** [angular/material#2159]
Please, see this example in Plunker: http://plnkr.co/edit/5ZpaOFF6YhjzTA6g69Wy?p=preview

When added the material css a scrollbar appears in Chrome (but not in IE :worried:)

**Comment by oswaldomilet** [comment]
I tried to take some parts of css and found that the problem is in:

```
html, body {
    height: 100%;
}
```

why?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
