### ISSUE TITLE
mdAutocomplete's "ng-disabled" attribute should support expressions

### ISSUE THREAD

**Issue by bvaughn** [angular/material#2160]
Perhaps I'm missing something, but why does `mdAutocomplete` specify a bi-directional binding for its [`isDisabled` / `ng-disabled` attribute](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteDirective.js#L57)? Angular's [`ngDisabled`](https://docs.angularjs.org/api/ng/directive/ngDisabled) directive supports expressions and it would be nice if the autocomplete directive did too. For example:

```html
<md-autocomplete ng-disabled="conditionFoo || conditionBar">...</md-autocomplete>
```

Looking at the autocomplete directive, I don't see where the 2-way binding is being used for anything. Would you consider replacing it with an "@" binding and an `attr.$observe`? I'd be willing to submit a pull request but I thought I'd ask first. :)

**Comment by lucasmartinez** [comment]
+1

**Comment by robertmesserle** [comment]
@bvaughn Definitely submit a PR for this.  There are definitely still clean-up tasks needed for `md-autocomplete`, so one less task is always welcome. =)

**Comment by robertmesserle** [comment]
@bvaughn scratch that, submitted a fix. =p

**Comment by bvaughn** [comment]
Haha, thanks Robert. I should have submitted one when I filed the ticket. Sorry! :)
