### ISSUE TITLE
mdBottomSheet does not stay open on mobile.

### ISSUE THREAD

**Issue by DonaldZhong** [angular/material#2161]
Hi,

When using mdBottomSheet on the desktop, it functions perfectly.
However, when on mobile, clicking the button to open the bottom sheet works, but it rapidly closes on the user. 

Here is the repo https://github.com/DonaldZhong/IAT381-Final

Controller
![capture](https://cloud.githubusercontent.com/assets/10424158/6991400/923c456c-da46-11e4-8745-574f8d3de2ee.JPG)

Button
![capture2](https://cloud.githubusercontent.com/assets/10424158/6991401/923c5732-da46-11e4-9cdf-57a2c7526de4.JPG)

SheetTemplate
![capture3](https://cloud.githubusercontent.com/assets/10424158/6991423/7b0d1bb2-da48-11e4-81af-7fc54045fb07.JPG)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by DonaldZhong** [comment]
I found out that this issue is caused by adding in jquery.
Heres a plunkr of the bottomsheet example i found online with jquery added in.

http://plnkr.co/edit/17HL9qVVKllBFIgx3CC4?p=preview

**Comment by ThomasBurleson** [comment]
@DonaldZhong - This provides a reproducible bug. Thx.

**Comment by Mutmatt** [comment]
I also posted about this in the forums thinking that this was a bug in my layout.  Came to the same conclusion. 

[Forum Link](https://groups.google.com/d/msg/ngmaterial/4iuO1hJ8n6c/HyTQ7WyslMIJ)

**Comment by ThomasBurleson** [comment]
@DonaldZhong - use the latest code from #master and it works:

http://plnkr.co/edit/VX0kPNMF4eBNc8gobC8J?p=preview
