### ISSUE TITLE
Firefox placeholder hidden for inputs without label

### ISSUE THREAD

**Issue by scisci** [angular/material#2162]
Placeholder for inputs without a label is hidden. The offending css is this:

md-input-container:not(.md-input-has-value) input:not(:focus) {
  color: transparent;
}

Apparently Firefox honors the transparent color (which should be illegal). So if the input is not focused the color becomes transparent. I was able to get around it by adding this css:

md-input-container:not(.md-input-has-value) input:not(:focus) {
  color: inherit;
}

**Comment by Splaktar** [comment]
Changing input.scss (114-116):

    &:not( .md-input-has-value ) input:not( :focus ) {
      color: transparent;
    }

to:

    &:not( .md-input-has-value ) input:not( :focus ) {
      color: inherit;
    }

Somewhat fixes this, but the colors/alpha of the placeholders aren't consistent in the demo. Firebug says that they are, but visually the difference is obvious.

**Comment by Splaktar** [comment]
It looks like the color/alpha differences that I saw were caused by differences in the styling between using floating labels and `placeholder`.
