### ISSUE TITLE
Typography.scss doesn't seem to be in the compiled CSS

### ISSUE THREAD

**Issue by Mutmatt** [angular/material#2169]
I'm not entirely sure if this is a bug/issue or just my misunderstanding how the framework is intended to work but the typography.scss does not appear to end up in the outputted [CSS](https://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.css) I added the class .md-display-4 (sans '.' of course) expecting styling based on the [docs](https://material.angularjs.org/#/CSS/typography).  

Could you please provide some clarification on how this is supposed to work or maybe change the documentation if it is working as expected "Angular Material provides typography CSS classes you can use to create visual consistency across your application."

**Comment by marcysutton** [comment]
Hi, the typography feature won't be available until the 0.9.0 release. This is definitely confusing with our current docs setup, which we are working to fix. Sorry for the confusion!
