### ISSUE TITLE
md-tab / md-dynamic height not refreshing when child content height changes

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2177]
md-tab needs to watch content to automatically resize when new content is added.

**Comment by WhiteAbeLincoln** [comment]
I have the same issue with a long list of items that gets dynamically updated. Unfortunately, the height only refreshes on a tab index change or if the window has been resized, so the content gets cut off, and on mobile, you cannot  resize a browser window. Watching the content would be nice, or making `updateHeightFromContent()` available so a manual refresh could be done in a controller.

**Comment by DefunctExodus** [comment]
Same issue here

**Comment by gbruins** [comment]
This is a showstopper for me, as most of my tabs are loading data asynchronously.  Looking forward to this fix, hopefully soon.

**Comment by robertmesserle** [comment]
@gbruins Agreed, this is definitely an important issue.  Worry not, I will try to address this today!

**Comment by gbruins** [comment]
It works!  I'm impressed with the fast resolution of this issue.  Awesome job Robert!!

**Comment by gbruins** [comment]
It looks like this issue has re-appeared in version 0.9.0   :(

I believe this ticket should be reopened.

**Comment by ngraef** [comment]
@gbruins It works for me: http://codepen.io/anon/pen/azrRgx?editors=101. You should open a new issue with a demo of the broken functionality you're seeing.

**Comment by gbruins** [comment]
Ah, I was missing the "md-dynamic-height" attribute on <md-tabs>.

Sorry about that.

**Comment by accilies** [comment]
Just if someone is looking for this answer, when using with ng-repeater in JADE files, I had to defined md-tabs as for it to work

md-tabs(md-dynamic-height="true", md-border-bottom)

**Comment by zixia** [comment]
I still have this issue when I inside google spreadsheet sidebar. the case is I use ng-repeat inside a tab of md-tabs, with md-dynamic-height , but it always have the same height. 

Is there anybody are using md-dynamic-height successfully inside google spreadsheet sidebar?

**Comment by fjrd84** [comment]
I was experiencing the same problem. This workaround does the trick for me:

`md-tabs-canvas{
  overflow: inherit;
}`
