### ISSUE TITLE
Layout attribute overrides not working with on element with .md-toolbar-tools class

### ISSUE THREAD

**Issue by daniel-nagy** [angular/material#2178]
Using layout attributes on an element with the `.md-toolbar-tools` class have no effect. For example,

    <div class="md-toolbar-tools" layout-sm="column" layout-align="start start">

will not respect the layout attributes. I suspect the issue is the layout attributes are being applied and then the `.md-toolbar-tools` class is overriding it. A solution would be to define the layout styles at higher priority (lower than the `.md-toolbar-tools` class) in the stylesheet or to hit them with `!important`.

**Comment by marcysutton** [comment]
`md-toolbar-tools` has its own layout attributes: `align-items: center` and `flex-direction: row`. What layout are you trying to accomplish? I think adding a wrapper to put your own attributes on is a better way to go.

**Comment by daniel-nagy** [comment]
Using a wrapper is ultimately the solution I went with. Layout attributes should override existing styles in my opinion. An extra element isn't much of a burden, but should't be necessary.
