### ISSUE TITLE
md-tabs: static tabs + dynamic (ngRepeat) tabs doesnt work together in one md-tabs

### ISSUE THREAD

**Issue by jzelenka** [angular/material#2181]
Combination of static tabs + dynamic (ngRepeat) tabs doesnt work together when used in one md-tabs directive:

    <md-tabs>
       <md-tab label="static tab 1">static tab 1</md-tab>
       <md-tab ng-repeat="tab in ctrl.tabs" label="dynamic tab {{tab}}">dynamic tab {{tab}}</md-tab>
    </md-tabs>

where
     `ctrl.tabs = [0,1,2];`

**Comment by ThomasBurleson** [comment]
@robertmesserle - LOL... seems valid while albeit an odd implementation.

**Comment by robertmesserle** [comment]
Pretty sure this is against the old tabs code, but I will confirm that it
is fixed in master before closing

**Comment by robertmesserle** [comment]
Confirmed that this works perfectly with the latest tabs code in master, closing.

**Comment by gigablox** [comment]
This is still an issue as of 1.0.8
