### ISSUE TITLE
theme: non-default themes broken

### ISSUE THREAD

**Issue by ngraef** [angular/material#2187]
Looks like 33049cff96cd643e76159fc2d72cbd9fb911245c broke the ability to style components with alternate themes.

[Broken demo](http://codepen.io/anon/pen/azrLpa?editors=101)
![image](https://cloud.githubusercontent.com/assets/1031317/7014936/63cbcac0-dc91-11e4-8c03-1854de733f7c.png)

[Working demo from previous commit](http://codepen.io/anon/pen/qEGPqL?editors=101)
![image](https://cloud.githubusercontent.com/assets/1031317/7014945/7944a430-dc91-11e4-86ef-4d90f753bee6.png)

**Comment by ThomasBurleson** [comment]
@ngraef  - Thx for the alert.

**Comment by ThomasBurleson** [comment]
@rschmukler - fyi since this may impact theming.
