### ISSUE TITLE
Featuer Request: md-toolbar height responsive

### ISSUE THREAD

**Issue by SiddharthaRRamesh** [angular/material#2191]
Type: Feature request

On: `md-toolbar` height

Description: `md-toolbar` height should be auto-responsive. According to material spec, height varies on desktops, tablets and mobile. Is there any disadvantage in doing this in the framework itself?

**Comment by ThomasBurleson** [comment]
Please check current issues for duplicates before creating a new issue.
Duplicate of #2047.

**Comment by SiddharthaRRamesh** [comment]
Sorry!
