### ISSUE TITLE
md-autocomplete, truncate text if too long

### ISSUE THREAD

**Issue by jgoux** [angular/material#2193]
Hello,
would it be possible to apply the same truncate function from md-select (https://github.com/angular/material/commit/1a81f0c6c98a2fe217f089c3457af5ee99ba61f5) to md-autocomplete ? So the text isn't expanding behind the "clean input" button.

**Comment by vishwa-** [comment]
How would I not truncate text if too long and instead wrap in the next line?

**Comment by ramlraml** [comment]
+1

**Comment by ramlraml** [comment]
+1
