### ISSUE TITLE
Dropdown-button with icon in menu

### ISSUE THREAD

**Issue by digitalcraftsman** [angular/material#2196]
I'm not asking the [first time](https://github.com/angular/material/issues/445) for this feature but in the linked issue it's mentioned, that `md-select` will be implemented with the released milestone 0.8.0. 

Does the state of the art of angular-material provide a possiblity to create a drop-down as button with an icon? 

If not, when could this be expected in future releases?

**Comment by nschloe** [comment]
Dup of #78?

**Comment by digitalcraftsman** [comment]
You're right. This issue would allow me to track the changes with this feature.
