### ISSUE TITLE
md-sidenav: scope and other props

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material#2197]
As of right now `md-sidenav` can only have some static content (unless it digs into `$rootScope` or services). Would not it make sense to make it work similar to [`md-dialog`](https://material.angularjs.org/#/api/material.components.dialog/service/$mdDialog) and [`md-bottom-sheet`](https://material.angularjs.org/#/api/material.components.bottomSheet/service/$mdBottomSheet), which can be opened with `options: {}` provided?

**Comment by DmitryEfimenko** [comment]
Congratulations with the RC1! Really great news.

[The talk](https://youtu.be/363o4i0rdvU?t=3m56s) by @ThomasBurleson at AngularConnect inspired me to attempt to revisit this issue.
Thomas mentioned that material team would like to "confirm or validate the release" to make sure that "material components work well together in the real world applications".

I strongly believe this is not the case with the `md-sidenav` component. I think that `md-sidenav` should behave very similar to the `md-dialog` and `md-bottom-sheet` where it can be opened with a set of options and return a promise:
```
$mdSidenav.show({
      templateUrl: 'sidenav-template.html',
      controller: 'MySideNavCtrl',
      controllerAs: 'ctrl',
      bindToController: true,
      hasBackdrop: true,
      [...and others...]
    }).then(function(returnedValue) {
      $scope.alert = 'returnedValue is ' + returnedValue;
    });
```
If this is not changed now, later it will be a bigger breaking change.

**Comment by ThomasBurleson** [comment]
@DmitryEfimenko - LOL. I love your persistence and you have a valid point. Let me discuss this with the team. Would you care to submit a PR with this feature (tested and with specs)?

**Comment by DmitryEfimenko** [comment]
I can certainly give it a shot.

It'd probably be almost a straight copy from BottomSheet code. The only real difference between these components is where the component slides from (bottom vs side).

As a matter off fact, maybe sidenav could be completely retired given we add an an option to the BottomSheet to specify where it should come from. In this case we'd have to probably also rename it to something like "SlideSheet".

I can take any route. Let me know what the team thinks.

**Comment by darioken** [comment]
This is want i need, plz make this. Thx

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
