### ISSUE TITLE
Hello World CodePen - Error: $injector:modulerr Module Error

### ISSUE THREAD

**Issue by pixelwiz** [angular/material#2198]
I'm just getting started with AngularJS Material.  Tried to just copy/paste a very basic codepen
http://codepen.io/marcysutton/pen/OPbpKm

But I'm getting an error in both Chrome and Firefox:
Error: $injector:modulerr
Module Error

Failed to instantiate module {0} due to:
{1}

https://docs.angularjs.org/error/$injector/modulerr?p0=StarterApp&p1=[$injector:nomod]%20http:%2F%2Ferrors.angularjs.org%2F1.3.15%2F$injector%2Fnomod%3Fp0%3DStarterApp%0AR%2F%3C@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:6:417%0AOd%2F%3C%2F%3C%2F%3C@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:21:412%0Aa@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:21:53%0AOd%2F%3C%2F%3C@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:21:1%0Ag%2F%3C@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:35:46%0Ar@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:7:300%0Ag@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:34:399%0Aab@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:38:135%0Auc%2Fd@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:17:381%0Auc@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:18:179%0AJd@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:17:1%0A@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:250:429%0Aa@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:164:283%0Alf%2Fc@http:%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.15%2Fangular.min.js:32:384%0A

But it works totally fine in CodePen.

Any idea?
Thanks you!

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
