### ISSUE TITLE
<md-list-item-text> multi-line text is squashed

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2199]
![screenshot](https://cloud.githubusercontent.com/assets/1916471/7033437/f0ced65c-dd71-11e4-99fd-6c90ee69f483.png)

**Comment by ThomasBurleson** [comment]
Reopen due to https://github.com/angular/material/commit/84b04cad4c45f4c8e31eccd662cde0cbdfb99308#commitcomment-13350711
