### ISSUE TITLE
[docs] md-bottom-sheet - targetEvent

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material#2201]
Obviously documentation for `md-bottom-sheet` was copy-pasted from `md-dialog` since this is what it says for the option `targetEvent`:
> A click's event object. When passed in as an option, the location of the click will be used as the starting point for the opening animation of the the dialog.

Perhaps this needs to be fixed.
Also looking at how `md-bottom-sheet` is animated, it just comes from the bottom of the screen instead of how it's described in the docs. Perhaps option `targetEvent` could be removed all  together from `md-bottom-sheet`?

**Comment by EladBezalel** [comment]
I agree that it's unnecessary 

@ThomasBurleson what's your opinion?

**Comment by ThomasBurleson** [comment]
agreed :+1:
