### ISSUE TITLE
tabs: md-dynamic-height doesn't resize on content change

### ISSUE THREAD

**Issue by ngraef** [angular/material#2203]
Tabs with `md-dynamic-height` aren't resized when the tab content changes, e.g. the model is loaded via async web request or content is added via UI interaction. The overflowing content is hidden until a window resize or tab switch.

[Demo](http://codepen.io/anon/pen/azrRgx?editors=101)

**Comment by ngraef** [comment]
Oops. Duplicate of #2177.

**Comment by daredkar** [comment]
same here
