### ISSUE TITLE
md-fab isn't fixed when scrolling

### ISSUE THREAD

**Issue by jgoux** [angular/material#2205]
Hello,
shouldn't a md-button with "md-fab md-fab-bottom-right" be fixed at its position 
even when the parent container is scrollable ?
I'm on the master branch, and at the moment the button doesn't stay at its position when I scroll : 
![mdfab](https://cloud.githubusercontent.com/assets/1443499/7040285/90b64dc0-ddcd-11e4-997b-f9b1605b4684.jpg)

For the markup, it's just a md-button inside a md-content : 
```html
<md-content>
    <!-- other divs -->
    <md-button class="md-fab md-fab-bottom-right">
        <md-icon md-font-icon="mdi mdi-check"></md-icon>
    </md-button>
</md-content>
```

**Comment by gustavohenke** [comment]
I think you shouldn't place the FAB inside `md-content` in order for this to work.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by jgoux** [comment]
I still think that md-fab should be fixed and not positioned using "absolute". :smile: 
Here is an example I made : http://codepen.io/jgx/full/jPqyYX/
You can resize to see how the md-fab is moving (bottom right on mobile)
Maybe you could provide template example like the one I made to show how can we use the md-fab positions (or more generally starter templates) ?
I do agree that with the fixed position, it's hard to make a solution for everyone, it really depends on the global layout.

**Comment by VesperDev** [comment]
.md-button.md-fab.md-fab-bottom-right {
    top: auto;
    right: 20px;
    bottom: 20px;
    left: auto;
    position: fixed;
}

I put the fixed attribute and working properly

**Comment by mr-cpp** [comment]
thank you, @VesperDev

**Comment by abinthomasonline** [comment]
md-fab-speed-dial.md-fab-bottom-right {
	position: fixed !important;
}

this works....

**Comment by gbergamo** [comment]
To not change all md-fab-bottom-right, or add <style> tag in all pages, my suggestion is:
`<md-button class="md-fab md-primary md-fab-bottom-right" aria-label="New" ng-click="insert()" style="position:fixed !important;">
        <md-tooltip md-direction="top">New</md-tooltip>
        <ng-md-icon icon="add"></ng-md-icon>
    </md-button>`

**Comment by chey** [comment]
+1

**Comment by majew7** [comment]
Position Fixed Not Enough

For me `position: fixed` helped. But it wasn't the full solution for Safari on iOS.  The `position: fixed` was causing interesting issues on iPhone iOS 9.3.

My unfortunate workaround was to move the FAB button to a much higher place within the HTML hierarchy.

**Comment by LeoLozes** [comment]
If you have a right sidenav and you want the FAB button in the md-content so it's positioned correctly (and not behind the sidenav when it's open), then none of the above solutions work. 
I don't understand why this issue is closed when it's clearly not working.
