### ISSUE TITLE
why not use   <!doctype html>

### ISSUE THREAD

**Issue by liuning108** [angular/material#2207]
I add   <!doctype html> tag  ,but  css layout is not   in chrome browser abnormal

**Comment by ThomasBurleson** [comment]
@liuning108 - I do not understand your issue here.

**Comment by marcysutton** [comment]
Including a doctype triggers Standards mode. So if you see issues when you include it, it indicates something is wrong with your layout. Please include a live demo that shows your complete source code.

**Comment by marcysutton** [comment]
Closing as duplicate of https://github.com/angular/material/issues/1470.
