### ISSUE TITLE
Generated styles different in Safari

### ISSUE THREAD

**Issue by scisci** [angular/material#2209]
There is a discrepancy with the auto-generated styles in chrome and safari on OSX. I have html similar to this:

    <body class="md-default-theme">
      <md-toolbar class="md-hue-1">...</md-toolbar>
      ...
    </body>

In chrome, ngmaterial generates a rule as follows:

    md-toolbar.md-default-theme.md-hue-1 {
      background-color: rgb(255,255,255);
      color: rgba(0,0,0,0.87);
    }

which is correct, however, in safari, it generates an empty rule as follows:
    md-toolbar.md-hue-1.md-default-theme {}

I'm not sure why safari rule order is different or if that relates to the definition being empty. This results in a huge inconsistency that I had to patch by adding explicit color rules to the css.

Here is a plunkr that demonstrates the issue (notice in safari the toolbar background is black, but in chrome it is white):
http://embed.plnkr.co/OlIhHapqoBEg27dmuPJG/preview

**Comment by ThomasBurleson** [comment]
@robertmesserle - I worry that this is a generator issue that we need to fix before 0.10.

**Comment by robertmesserle** [comment]
@rschmukler This would be a theming issue, wouldn't it?  Any ideas?

**Comment by marcysutton** [comment]
Sounds related to https://github.com/angular/material/issues/2011.

**Comment by ThomasBurleson** [comment]
@rschmukler - let's talk offline about 1ebc42e.
