### ISSUE TITLE
Lists with not clickable items and icons

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#2210]
Hey,
I tried the development version of ngMaterial and found that I can't have a list with:

* No clickable items (data presentation only)
* Icons as the primary tile of an item
* Padding for the primary tile _in some items_

Example (taken from [the specs](http://www.google.com/design/spec/components/lists.html#lists-specs)):

![](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7WHgwei1jRTdkc1k/components_lists_keylines_two12.png)

As of `v0.8.3`, the following was possible:

```html
<md-item ng-repeat="...">
    <md-item-content layout-align="start start">
        <div class="md-tile-left">
            <md-icon md-font-icon="icon-local-phone" ng-if=":: $index === 0"></md-icon>
        </div>
        <div class="md-tile-content">
            <h3>{{:: $profile.phone[ type ] }}</h3>
            <p>{{:: type }}</p>
        </div>
    </md-item-content>
</md-item>
```

Rendered example for `v0.8.3`:
![](http://i.imgur.com/TASJSJz.png)

Code for the development version:
```html
<md-list-item class="md-2-line" ng-repeat="...">
    <div class="md-avatar">
        <md-icon md-font-icon="icon-local-phone" ng-if=":: $index === 0"></md-icon>
    </div>
    <div class="md-list-item-text">
        <h3>{{:: $profile.phone[ type ] }}</h3>
        <p>{{:: type }}</p>
    </div>
</md-list-item>
```

Rendered example for development version:
![](http://i.imgur.com/ccmP04h.png)

_What's problematic here?_
1. The icon is not correctly aligned with the text;
2. It's not semantic to use `.md-avatar` for an icon;

If I did have an `ng-click` and an icon, maybe I could follow the [list control demo](https://material.angularjs.org/#/demo/material.components.list), but that would not allow to skip the icon for some items.

Thanks in advance.

**Comment by rschmukler** [comment]
@gustavohenke thanks for bringing this to our attention (and playing with the dev version)!

I just added support and a demo, but the new html looks like:

```html
<md-list-item class="md-2-line" ng-repeat="phone in phones">
  <md-icon md-svg-icon="communication:phone" ng-if="$index === 0"></md-icon>
  <div class="md-list-item-text" ng-class="{'md-offset': $index != 0 }">
    <h3> {{ phone.number }} </h3>
    <p> {{ phone.type }} </p>
   </div>
</md-list-item>
```

**Comment by gustavohenke** [comment]
Oh, thanks! Nice improvement!
