### ISSUE TITLE
Feat(autocomplete): Tab to select first result

### ISSUE THREAD

**Issue by prestonvanloon** [angular/material#2211]
Allow option for selecting the first result when leaving focus of the field.

Thanks!

**Comment by ThomasBurleson** [comment]
@robertmesserle - I cannot recall why we do not support this along with arrow keys?

**Comment by robertmesserle** [comment]
It sounds like what you want is `md-autoselect` which will make the first item highlighted by default.

I also just added a related fix that allows TAB or ENTER to select the highlighted item.  Both of these things together should give you the results that you want.

**Comment by prestonvanloon** [comment]
Sounds perfect! Thank you!
