### ISSUE TITLE
Autocomplete: Remove delete button from tab order

### ISSUE THREAD

**Issue by jcarroll2007** [angular/material#2212]
Currently, if the user tabs out of the autocomplete, the icon to delete the autocomplete text will be selected. I don't think it is necessary to be able to tab to the button.

Delete Button
![image](https://cloud.githubusercontent.com/assets/8485105/7054382/1fca52a4-de0a-11e4-8e7f-dc20bc75ea4c.png)

**Comment by marcysutton** [comment]
The delete button is required for keyboard accessibility. Hitting the delete key on the autocomplete will only remove a single letter.

**Comment by jcarroll2007** [comment]
It doesn't only remove a single letter. I'm not referring to the keyboard key, but the icon button that is circled in the screenshot above.

**Comment by marcysutton** [comment]
If we remove the "remove" button, all that will be left for keyboard access is using DEL key on the autocomplete–which removes one letter at a time (there is also ESC, but that is a separate feature). The remove button is in the design spec, and it has to be accessible from the keyboard.

**Comment by jcarroll2007** [comment]
Oh, I didn't understand what you meant now. Well, allowing someone to set a flag to change that might be a good idea. I find it quite annoying when the autocomplete is used in a form. I wouldn't say that the work flow is very intuitive.

Thanks.

**Comment by jcarroll2007** [comment]
Oh, and I wasn't suggesting that you remove the button either. Just allow developers to set the tab index attribute on the element.

**Comment by marcysutton** [comment]
So only mouse users get to use the remove button? Removing the button from the tab order would make the autocomplete difficult to clear for keyboard users. I'm sorry, but it's not something we are going to support.

**Comment by jcarroll2007** [comment]
It would be just as difficult to clear as other inputs are, correct? No need to apologize, I just don't quite agree with that. And I definitely don't agree with not giving developers an option to decide for themselves.

Thanks anyway.

**Comment by marcysutton** [comment]
That is a good point that other text fields don't have the same affordance. It was also pointed out to me that keyboard users have other ways of clearing a field (select all + delete, for example). If we do remove the button from the tab order, it would have to be done everywhere. Making it configurable would create a mess in terms of user intuition when the same component is presented on different sites.

This sounds like a good question for user testing. I will escalate to the UX team. Thanks for working through this.

**Comment by jcarroll2007** [comment]
I agree that the correct solution isn't as straight forward as I originally thought it was, but thank you for considering my opinion. I look forward to seeing the result.
