### ISSUE TITLE
md-select ▼ displaying underneath text in IE10

### ISSUE THREAD

**Issue by jerturner** [angular/material#2213]
For IE10, the arrow, ▼, that appears to the right in browsers other than IE10 for md-select appears under the text in IE10.  This can be seen at https://material.angularjs.org/#/demo/material.components.select.

**Comment by PrashantAshok** [comment]
Hey @jerturner , a temp fix that worked for me was 

```
@media screen and (min-width:0\0) {
    md-select .md-select-icon {
        float: right;
}
```

**Comment by arubio-solset** [comment]
Just to share my solution, as I had a slightly different set up.
I tested and this works in Win 7: IE9-IE11, Chrome 44, Safari 5.1.

		.md-select-label {
			width: 100%;
			.md-select-icon {
				float: right;
			}
			> span:first-child {
				display: inline-block;
				width: 85%;
			}
		}
