### ISSUE TITLE
md-input-container date input type conflicts with Chrome when disabled

### ISSUE THREAD

**Issue by Blood-Saint** [angular/material#2216]
When the input type is set to 'date' and is disabled, the Chrome placeholder for date types is not hidden:
![chrome conflict](https://cloud.githubusercontent.com/assets/5942361/7056401/291d456e-de00-11e4-8598-e9b2d4f8b14a.PNG)

**Comment by loykianos** [comment]
Was about to report the same thing. Created a plunker already, in case you need it. 

http://plnkr.co/edit/GZB5XAHqc3oSvETlSh5j?p=preview

**Comment by ThomasBurleson** [comment]
Use DatePicker which was released in ^v0.11.0-rc1.
