### ISSUE TITLE
md-toolbar shrinking issue in IE11

### ISSUE THREAD

**Issue by BobKlaas** [angular/material#2218]
I have an application that uses md-tabs on a md-toolbar. It is working great in Chrome. However, in IE Edge, the toolbar shrinks after the page loads. I've attached an animated GIF to illustrate what is happening. The toolbar has a min and max height of 48px and has two child divs. First div uses flex 20 and second div uses flex.

1. Page is loading and toolbar appears normally.
2. Page fully loads and toolbar shrinks.
3. Click on toolbar and it re-sizes back to normal.

![materialnavbarissue](https://cloud.githubusercontent.com/assets/5191616/7056289/5bf6fda0-ddff-11e4-8f10-9d6e0b6ed825.gif)

![code](https://cloud.githubusercontent.com/assets/5191616/7056964/b6d82a0e-de05-11e4-89de-a59297ef7560.PNG)

**Comment by marcysutton** [comment]
Which version of Angular Material? There was a rewrite to tabs recently...can you verify whether this is an issue, and if it is, can you also provide a Codepen or Plunker showing the issue? Thanks.

**Comment by BobKlaas** [comment]
Hey Marcy,

We re designed the layout. I can't seem to reduplicate the issue. Maybe the
rewrite on tabs fixed the issue?

Anyways, I'd just close this one out.

Thanks
-Bob
