### ISSUE TITLE
md-select: Incorrectly applying margin to md-content?

### ISSUE THREAD

**Issue by nickclaw** [angular/material#2219]
I think [this line](https://github.com/angular/material/blob/9af45d37d635b31ae9fa1117db3edfd2e07f15ab/src/components/select/select.js#L734) should be changed to `if (!$mdUtil.floatingScrollbars()) {`

The current behavior adds a margin-right of 16px to all the `md-content` tags on my page when a `md-select` is selected. It appears this is to fill the space that goes away when solid scroll bars are removed, but it incorrectly(?) applies to floating scroll bars instead.

**Comment by nickclaw** [comment]
Pinging @rschmukler, you added the line so you probably know best if that's the correct behavior.

**Comment by rschmukler** [comment]
Closing since the code referenced is no longer in place.
