### ISSUE TITLE
mdGridList: Arrow key navigation

### ISSUE THREAD

**Issue by anupbelambe** [angular/material#2224]
In Angular Material Design, how can we enable 4 way arrow key navigation to grid list? If we have grid of select-able images the user should be able to navigate through the grid using arrow keys and select the image using enter key. 
for e.g. you can navigate through folder items using arrow keys in google drive. https://drive.google.com/drive/my-drive.

**Comment by ThomasBurleson** [comment]
@shyndman  - this question is if Gridlist is a read-only, presentation view or more interactive like a Grid or Table view?

**Comment by ThomasBurleson** [comment]
Gridlist should support navigation through the tiles with tab-key only; not arrow keys.
Enter-key event should be supported to trigger an expression for the selected/active tile.

**Comment by anupbelambe** [comment]
Aria design pattern guidelines suggest following keyboard interaction for grid in navigation mode which seems like what most applications implementing grid would be looking for  e.g. https://drive.google.com/drive/my-drive

Refer http://www.w3.org/WAI/PF/aria-practices/#grid
- The first Tab into the grid moves focus to the first cell of the first row.
- The second Tab leaves the grid and moves focus to the next tabbable item on the page.
- Subsequent Tab: Once focus has been moved inside the grid, subsequent tab presses that re-enter the grid shall return focus to the cell that last held focus.
- Right/Left arrow keys navigate through the columns. There is no wrap at the end or beginning of columns.
- Up/Down arrow keys navigate through the rows. There is no wrap at the first or last rows.

Per ARIA, Tabbing is mainly used for navigating through widgets. Refer http://www.w3.org/WAI/PF/aria-practices/#aria_ex
Widgets within Widgets: The general navigation model is for a user to tab to a widget, interact with the controls in that widget and then tab to move focus to the next widget in the tab order. By extension, when the construct of a widget contains another widget, tab will move focus to the contained widget because it is the next item in the tab order. This continues down the layers of widgets until the last widget is reached. For example: We have two widgets A and B on a page. Widget A contains within it Widget C and Widget C contains within it Widget D. When tabbing, focus would land on Widget A, then another tab would focus on C and then another tab would focus on widget D. Because D is the last widget in C and C is the last widget in A one more tab would move focus to B.

**Comment by shyndman** [comment]
@ThomasBurleson,

Who did you have that review with? 

Marcy's suggestion seems a lot stronger, and more aligned with how you'd expect grids to act.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
