### ISSUE TITLE
mdGridList: unexpected tile ordering

### ISSUE THREAD

**Issue by VilemP** [angular/material#2225]
Hi,

we have a case where we would like to add tiles into the grid in two ways:
a) the first tile is always fixed and basically plays the role of "add new" button for the list items
b) any number of other tiles added via ng-repeat

Unfortunately it is not possible to achieve that as tiles added via ng-repeat have the scope.$parent.$index defined (unlike the others) and as a consequence, they are always put in front of the other tiles.

See this plunkr: http://plnkr.co/edit/uFFmoZMaWallf8M3PHRi?p=preview

I would suggest to allow an "order" attribute for a tile (similar to flexbox) to be able to specify desired order of the tile in the list.

BTW, we have run into similar issue with tabs (a mixture of fixed tabs + tabs created via ng-repeat)

**Comment by VilemP** [comment]
Hi again... actually, the tab behaviour is different (still problematic). I have created another issue and plunkr for it #2226 
Sorry for mixing the two together.

**Comment by ThomasBurleson** [comment]
mdGridList has been improved for 0.9; which closed many issues.
Please update your Plunkr with latest from #master and retest:

*  `//rawgit.com/angular/bower-material/master/angular-material.css`
*  `//rawgit.com/angular/bower-material/master/angular-material.js`

**Comment by VilemP** [comment]
Hi, I have updated the plunkr, yet the order still seems to be wrong...

**Comment by ThomasBurleson** [comment]
@shyndman - FYI

**Comment by Stamy** [comment]
I have the same problem as well.

**Comment by tkrotoff** [comment]
+1

**Comment by shyndman** [comment]
This one is kind of tricky. I have to think about it for a bit.
