### ISSUE TITLE
mdTab: improper behavior with ng-repeat + non ng-repeat tab elements

### ISSUE THREAD

**Issue by VilemP** [angular/material#2226]
Hi, 

when mdTab is used the way, that some tabs are generated with ng-repeat and other tabs are "static", the tabs exhibit improper behaviour such:
a) content of tab 1 is not replaced when switching the tab
b) highlighting of selected tab is misplaced 
etc.

See plunkr: http://plnkr.co/edit/bR9ilyigVvcjJGX76dPK?p=preview

**Comment by ThomasBurleson** [comment]
Tabs has been rewritten/re-architected in 0.9; which closed many issues.
Please update your Plunkr with latest from #master and retest:

*  `//rawgit.com/angular/bower-material/master/angular-material.css`
*  `//rawgit.com/angular/bower-material/master/angular-material.js`

**Comment by VilemP** [comment]
hi, 
thanks...  referencing the master helped indeed. See the plunkr
