### ISSUE TITLE
mdGridList: md-grid-tile elements are gone when the grid list is re-created

### ISSUE THREAD

**Issue by ecunal** [angular/material#2227]
First of all, I am using the latest builds from: http://rawgit.com/angular/bower-material/master/angular-material.js and this issue was observed on Chrome v41.

We are dynamically creating mdGridList tiles, and refreshing those tiles from script was working as expected before. However today, when we try to refresh them as before, tiles cannot be seen anymore. I am not sure when this was broken, but I am certain that it was okay on April 7th.

Codepen for the issue: http://codepen.io/ecem/pen/myZVgv, normally it's looking good, but when we click refresh the tiles are gone.

**Comment by ThomasBurleson** [comment]
@ecunal - Excellent bug report, Thx.
@shyndman - the grid is empty until a reflow is triggered (for me, by a window resize).

**Comment by shyndman** [comment]
I'll take a look tonight. Thanks Ecunal.
