### ISSUE TITLE
md-divider(enhancement): add `vertical` option

### ISSUE THREAD

**Issue by jossef** [angular/material#2228]
The `md-divider` directive works great for horizontal use cases ( :+1:) . However, i would like to use it as a vertical divider as well.

This can be added as an option for `md-divider` directive:

```html
<md-divider vertical></md-divider>
```

**Comment by ThomasBurleson** [comment]
The Material Design does not provide a specification for Vertical Dividers. Can you provide a mockup of your needs [and we will escalate to the UX Design team]?

**Comment by Jossef** [comment]
@ThomasBurleson Thanks :smile: 

![image](https://cloud.githubusercontent.com/assets/1287098/7086908/bdeb5fca-df8e-11e4-9fa5-105e3f4c6f77.png)

**Comment by ThomasBurleson** [comment]
@Jossef - What is the URL for that image ?

**Comment by ThomasBurleson** [comment]
Specification at http://www.google.com/design/spec/layout/structure.html#structure-ui-regions

**Comment by cdonohue** [comment]
Would it make sense to base this off of the container that the `<md-divider></md-divider>` is located in?
```
[layout=row] > md-divider {
  border-top: 0;
  border-left: 1px solid;  
  border-left-color: rgba(0, 0, 0, 0.12);
}
```

**Comment by JobaDiniz** [comment]
+1

**Comment by jossef** [comment]
תודה אלעד, יא זלמה (Thanks Elad, my hero)
:+1:

**Comment by EladBezalel** [comment]
:heart: באהבה אחי (No problem)

**Comment by Tallyb** [comment]
Was the vertical divider added? How is it used?

**Comment by EladBezalel** [comment]
@Tallyb when the divider is in layout-row it will automatically be vertical

**Comment by Tallyb** [comment]
Seems to be a problem with a selector. It does not work on a toolbar.

**Comment by EladBezalel** [comment]
Can you provide a codepen please?

**Comment by Tallyb** [comment]
http://codepen.io/Tallyb/pen/adpObe

Your divider is between the arrow icons. mine to the right of it. It is the same css as yours, just explicitly added. As noted - it is some selector issue.

**Comment by EladBezalel** [comment]
@Tallyb thanks, toolbar defines `align-items: center` which make the divider shrink, do you mind making a PR adding `height: 100%` to the vertical divider?

**Comment by arron21** [comment]
Hey don't forget to add support for
 `layout-gt-sm="row"`

etc etc

**Comment by smurugavel** [comment]
yes, for me `layout-gt-sm="row"` hides the divider. Please add support for `layout-gt-sm="row"`

**Comment by EladBezalel** [comment]
@arron21 @smurugavel, can one of you please create a new issue so we can track it down?

**Comment by Pablodotnet** [comment]
So what happened with vertical divider? How it's usage?

**Comment by EladBezalel** [comment]
@Pablodotnet when you define `layout=row` on the container element, `md-divider` will automatically adjust itself

**Comment by ORESoftware** [comment]
so someone write out the html please, is this right

```html
<div fxLayout="row">
  <mat-divider></mat-divider>  // will be a vertical divider?
<div>
```

**Comment by kabb5** [comment]
@ORESoftware this is an issue related to Material for AngularJS (v1.x), I think you're asking about Angular Material for Angular (v2+), see [https://github.com/angular/material2](https://github.com/angular/material2)
