### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by BobbieBarker** [angular/material#2229]
I'm getting 403 forbidden error's from:
https://material.angularjs.org/#

**Comment by MilosStanic** [comment]
+1

**Comment by ThomasBurleson** [comment]
I am not seeing that. Can you capture the console log and paste the image here?

**Comment by BobbieBarker** [comment]
Now I'm not getting it anymore... sorry for the false alarm?

**Comment by MilosStanic** [comment]
yes, works for me too
