### ISSUE TITLE
Tooltips on dark theme should not have white foreground and shadow

### ISSUE THREAD

**Issue by asans** [angular/material#2231]
When setting a theme to be dark by using the dark() method, this causes the background to be dark, which is intended and expected.  However, tooltips background are changed as well.

For example, the following code below:

```
    $mdThemingProvider.theme('mailPagesTheme')
      .primaryPalette('cyan')
      .dark()
```

The above code will cause the tooltip to use a white foreground and white/light shadow.

If we look at all the tooltips out there, it should _always_ be a dark shadow with contrast foreground colors.  The purpose of the dark shadow is to make the foreground text visible when the tooltip overlays any image or color.  Just as one should not make a dialog scrim white, neither should the tooltip scrim be white.

Material Design Tooltips section also does not showcase that the scrim should be white.

Tooltips, by design, should always have a black scrim.

Attached is a screenshot of what a dark() theme tooltip looks like, which is illegible.

![dark theme tooltip](https://cloud.githubusercontent.com/assets/17964/7072309/157b3976-dea0-11e4-91e2-b14ce08febe5.jpg)

**Comment by marcysutton** [comment]
@asans can you provide a Codepen or Plunker showing your code? It will help speed things up. Thanks!

**Comment by asans** [comment]
@marcysutton Here's a codepen code for reproducing the issue:

http://codepen.io/asans/pen/WvwrWw

If you hover over the button and look at the tooltip, you'll see it.

**Comment by alphatwit** [comment]
+1

**Comment by alphatwit** [comment]
I think the intent may have been, when the theme is dark, to put dark text on a light background. It's doing the background part properly, but still picking up the wrong text colour.

In most cases, and especially in yours where the tooltip hangs outside the dark element, it's much nicer to display white on dark.
