### ISSUE TITLE
md-switch occasionally does not ink

### ISSUE THREAD

**Issue by Luminess** [angular/material#2232]
Occasionally does not ink on one state or both states. The non-inking for one or both states persist until refreshing the page in which, in a seemingly random manner, changes which state it does not ink on. Rapid clicking results in inking for every click but slow clicking results in the issue described.

Tested here: https://material.angularjs.org/#/demo/material.components.switch

Google Chrome Version 41.0.2272.118 m

**Comment by ThomasBurleson** [comment]
Fixed with ^ v0.11.0-rc2.
