### ISSUE TITLE
mdChips: Focus state is not defined

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2233]
What are the UX specifications for clean focus states and transition effects for Chips (especially contact chips)?

**Comment by ThomasBurleson** [comment]
* Tab key to change focus between chip items
* Delete/Backspace should remove the selected/focused chip item
* Active/Focused state may inherit a ink or custom color (specification is pending)

>  Edit existing chips will be a future feature. Arrow and Enter/SpaceBar key support may be included for editing.

**Comment by typotter** [comment]
- I chatted w/@robertmesserle and he explained arrow keys only should move focus between chips, while tab moves focus between input controls.
- delete/backspace removes the focused/selected chip
- active state is currently using the accent color: good contrast and consistency.

Should be able to close this issue now.

**Comment by ilanbiala** [comment]
@typotter @ThomasBurleson can this be closed?

**Comment by matthiasg** [comment]
should `Enter`/`Return` while browsing chips in the drop down behave identical to pressing `Tab` ? Right now it enters an empty chip, in the demo at least.
