### ISSUE TITLE
Customization Link on front page of the Docs has misleading href

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [angular/material#2234]
The md-button that says 'Customization' on the index page of the docs site leads to `#/layout`, which is not in the Customization category on the sidebar navigation. 
This isn't a big issue, but it is misleading, and I think the link should lead to `#/Theming/01_introduction` instead, since that is the kind of customization that a developer might be doing. Layout doesn't really have anything to do with customization.

**Comment by marcysutton** [comment]
Layout was originally under Customization, so it was correct at one time. I'll change it. Thanks for the tip!
