### ISSUE TITLE
Placeholders not visible in inputs with icon label on Firefox

### ISSUE THREAD

**Issue by jgoux** [angular/material#2235]
Hi,
placeholders aren't visible in Firefox v37 (windows 8.1 x64) for inputs with icon labels. They are visible on focus only.

![doc](https://cloud.githubusercontent.com/assets/1443499/7075255/bc914d12-df00-11e4-95db-bf931f0d22ed.jpg)

**Comment by scisci** [comment]
I think this is the same problem described here: https://github.com/angular/material/issues/2162

**Comment by ThomasBurleson** [comment]
Closing as dup for #2162
