### ISSUE TITLE
Applying an alternate theme with md-theme doesn't work.

### ISSUE THREAD

**Issue by mrmeku** [angular/material#2236]
Whatever theme I apply with md-theme="theme-name" only makes the background of buttons transparent. This leads me to believe that md-theme is broken.

**Comment by ThomasBurleson** [comment]
@rschmukler - thoughts/questions?

**Comment by rschmukler** [comment]
I suspect that you might not be registering the alternative theme you are attempting to use. Here is a demo showing it [currently working](https://jsfiddle.net/rschmukler/kx9o1e27/). Please open an issue with a demo if it is an actual issue.
