### ISSUE TITLE
Is this code logic wrong in autoCompleteController.js?

### ISSUE THREAD

**Issue by ptgamr** [angular/material#2241]
Please take a look at:
https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L193

I think it should be `if (!searchText || searchText === previousSearchText) return;`

**Comment by ThomasBurleson** [comment]
//-- do nothing on init if there is no initial value

**Comment by ptgamr** [comment]
So the condition  `searchText === previousSearchText` will never be evaluated when there are search text. I think this to prevent doing more work when `searchText` is unchange.

`||` condition make more sense for me than `&&`

**Comment by robertmesserle** [comment]
When the user deletes characters, we want to continue through the function's logic.  Changing that to `||` would prevent this from happening.

**Comment by ptgamr** [comment]
@robertmesserle 
With `||`:  when the user deletes characters, the condition `!searchText || searchText === previousSearchText` still return false because `searchText` is different with `previousSearchText`. Then the function logic is still happened.

The problem with `&&` is, in addition to the comment above, when `searchText` is empty & `previousSearchText =  some value`, then the function is still execute

**Comment by robertmesserle** [comment]
@ptgamr You are describing how `&&` works: http://jsbin.com/virugiromu/1/edit?js,console

We **want** it to execute when `searchText` is empty but `previousSearchText` is not - that means the user changed `searchText`.  The only time that we don't want this logic to run is when there is no **initial** value.

**Comment by ptgamr** [comment]
Ok. I'm good now :+1: Thanks for your explanation!
