### ISSUE TITLE
Ion-nav-view with material side-nav clipping view content

### ISSUE THREAD

**Issue by atentis** [angular/material#2245]
When I place an ion-nav-view on my layout page (side menu) it does not display its views correctly. Every single view has the very bottom of the content clipped off on its scroll-able and static views .

When I look at the elements in dev tools it looks as if the ion-nav-view element overflows pasts the bottom of the screen on the phone emulator. If I swap the md-side-nav with an ion-side-nav the issue goes away.

Here is a code examle. The ion-nav-view is declared on the bottom of the md-sidenav.

Layout / Side Nav
-----------------------------------------------------
```
<div ng-controller="AppCtrl">
    <md-content>
        <md-toolbar class="md-accent" layout="row">
            <section class="material-design-hamburger">
                <button class="md-toolbar-tools material-design-hamburger__icon"
                        ng-click="toggleLeft()">
                    <span class="material-design-hamburger__layer"></span>
                    <span class="material-design-hamburger__layer"></span>
                    <span class="material-design-hamburger__layer"></span>
                </button>
            </section>
            <h2 class="md-toolbar-tools">
                <span>Title</span>
            </h2>
        </md-toolbar>
    </md-content>

    <div layout="column">
        <section layout="row" flex>
            <md-sidenav class="md-sidenav-left md-whiteframe-z2" md-component-id="left">
                <md-content ng-controller="LeftCtrl">
                    <md-content md-swipe-right="close()">
                        <md-toolbar class="md-theme-light">
                            <h1 class="md-toolbar-tools">Title</h1>
                        </md-toolbar>
                    </md-content>
                </md-content>
                <md-content ng-controller="LeftCtrl" layout="column" class="md-padding">
                    <md-button class="md-primary" ng-click="close2('layout.makePayment')">
                        Make Payment
                    </md-button>
                    <md-button ng-click="close2('layout.displayPayments')">
                        Payment History
                    </md-button>
                </md-content>
            </md-sidenav>

           ***This Ion-nav-view clips the other views***
           <ion-nav-view name="mainContent"></ion-nav-view>
        
       </section>
    </div>
</div>
```

View (layout.makePayment / layout.displayPayments)  
-----------------------------------------------------
```
    <ion-view>
       <h2>View TItle</h2>
        <ion-content>
         
            Angular Material Content.....
            .........................................
         
          ***Content clipped off here***
        </ion-content>
    </ion-view>


```
Index
---------------------------------------------------------
```
<body ng-app="app">
   <ion-nav-view></ion-nav-view>
</body>
```

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by atentis** [comment]
@ThomasBurleson Can you confirm it is just me doing something wrong and not a conflict with the frameworks?

**Comment by atentis** [comment]
Here is a plunker. If someone could please advice me that would be great.

http://plnkr.co/edit/hnIIN0BUCFSrUC9l6tkp?p=preview

**Comment by marcysutton** [comment]
@atentis one thing that would help narrow it down would be to try your layout without Ionic to see if the sidenav is still cut off.

**Comment by atentis** [comment]
@marcysutton Thanks for responding. The only Ionic I have in the side-nav is the ion-nav-view. If I take that out and use ui-router then the opposite happens and the top of the view is clipped off. 

If I take the ion-content out of the view in addition to using ui-view instead of ion-nav-view (on the side nav) it looks like the view could potentially be correct. Except I dont have the scrolling effect I get with Ion-content so I cant scroll down to see all the content.

**Comment by ThomasBurleson** [comment]
Layout issues with Ionic and Angular Material should be posted in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by atentis** [comment]
@ThomasBurleson https://groups.google.com/forum/#!topic/ngmaterial/UivPJVm5YY4
