### ISSUE TITLE
Tiny CSS changes to be compatible with node-sass

### ISSUE THREAD

**Issue by jgoux** [angular/material#2246]
Hello,
in order to include angular-material.css in my Sass workflow, I have to rename it to angular-material.scss.
Since I updated node-sass to the upcoming v3.0.0, I have two issues with angular-material.css : 
- https://github.com/angular/bower-material/blob/master/angular-material.css#L7 has to be between quotes
- https://github.com/angular/bower-material/blob/master/angular-material.css#L3742 has to be between quotes as well

It would be much easier if the .scss files were included in the distribution. Every time I update angular-material, I have to rename the css file.

**Comment by ThomasBurleson** [comment]
@jgoux - our those lines still correct. For clarity, plz provide examples of the desired corrections.

**Comment by jgoux** [comment]
Sorry, as the CSS changed, the line changed too.
Basically, node-sass v3.0.0 fails on unquoted strings in `url()`, so both make the build failed when I rename the angular-material.css to angular-material.scss (so I can import the file in my own styles) : 
- https://github.com/angular/bower-material/blob/master/angular-material.css#L7
- https://github.com/angular/bower-material/blob/master/angular-material.css#L3312

**Comment by ThomasBurleson** [comment]
@jgoux  - Will fix per [http://www.w3.org/TR/CSS2/syndata.html#value-def-uri](http://www.w3.org/TR/CSS2/syndata.html#value-def-uri)

**Comment by saper** [comment]
This is sass/libsass#1087, already hot-fixed in [libsass](http://github.com/sass/libsass) `master`
