### ISSUE TITLE
Don't include Roboto fonts by default

### ISSUE THREAD

**Issue by jgoux** [angular/material#2247]
Hi,
would it be possible to remove the `@import url(https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic);` from the build by default ?
I don't want to rely on external resources and this forces the user to do so.
I prefer to use something like https://www.npmjs.com/package/webfont-dl to have them locally : 
`webfont-dl \"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic\" -o ./src/styles/vendors/_fonts.scss --font-out=./src/assets/fonts --css-rel=assets/fonts`

**Comment by grizzm0** [comment]
This was changed in 2d2d960 via #1009. And I agree with you. I don't think the lib should force me to load assets from a remote source.

What if I'm creating an offline application?

Ping @marcysutton

**Comment by marcysutton** [comment]
Great points. We have reopened #1009 as we have a discussion happening with the Material Design UX team about the best way to handle this. We will keep you posted!

**Comment by ThomasBurleson** [comment]
FYI -
![screen shot 2015-04-11 at 8 11 07 am](https://cloud.githubusercontent.com/assets/210413/7101507/4f27d084-e022-11e4-9ead-fae7121acf50.png)
