### ISSUE TITLE
sidenav on cordova

### ISSUE THREAD

**Issue by amille44420** [angular/material#2249]
Hi everyone,

I'm using AngularJS with Cordova, everything is working fine except one component.

I've a sidenav on the right (closed by default) then I've a toolbar with a button to open that sidenav.
The basis are working well but sometimes the sidenav is been closed by itself. I mean, I lick on my button then the sidenav is opening, once the sidenav is fulled opened, it's being close. (without any actions outside).

I don't have this issue on Google Chrome with the same code, only on Cordova.

**Comment by ThomasBurleson** [comment]
Are you by chance also using the Ionic framework ?

**Comment by amille44420** [comment]
No I do not. I'm only using AngularJS, AngularJS Material and Modernizr.

**Comment by Alexandre-io** [comment]
Hi, I fix the same issue by applying the commit 81bcf7fd15fd76f054814b34d8a877168fc6225c to the release 0.8.2.

**Comment by ThomasBurleson** [comment]
@amille44420, @Alexandre-io - please try with the latest from /bower-material/#master. See Changes in SHA 2c57a8289f73265ca41fc8b2fbbe173a80073caa

**Comment by Alexandre-io** [comment]
Hi @ThomasBurleson, no more issue with the master branch. Thanks!
