### ISSUE TITLE
md-select on sidenav problem

### ISSUE THREAD

**Issue by trimox** [angular/material#2251]
![image](https://cloud.githubusercontent.com/assets/11887843/7089331/15b0656e-df69-11e4-8d1c-203b82eade44.png)

Reporting an issue using an md-select on a Sidenav. You get the "..." instead of the selection. If I take the same md-select and drop it outside of the Sidenav, it works as intended.

**Comment by ThomasBurleson** [comment]
@rschmukler - any thoughts?

**Comment by sokolandia** [comment]
this issue has returned in rc-3 and rc-4, didn't check further. please look into it
