### ISSUE TITLE
md-select adding a white border when selecting

### ISSUE THREAD

**Issue by mtt87** [angular/material#2253]
https://material.angularjs.org/#/demo/material.components.select

Demo:
![demo](http://f.cl.ly/items/403v3T22031a360e0b2e/Screen%20Recording%202015-04-10%20at%2002.59%20pm.gif)

The cause is that when you open the select all the `<md-content>` elements in the page will have 
`margin-right:16px`

The problem in the code is here:
https://github.com/angular/material/blob/master/src/components/select/select.js#L734-L736
and here:
https://github.com/angular/material/blob/master/src/components/select/select.js#L898

I don't really know what you want to achieve with the check for floatingScrollbars but if you remove that piece of code the page looks fine.

EDIT: I forgot to add these important info, MBP retina 13, Chrome 41.
I think this problem was happening also with Bootstrap CSS and probably the cause is that Chrome doesn't show by default the scrolling bar but if you connect a mouse to your laptop I remember the scrolling bar is being shown.

**Comment by jgoux** [comment]
I have this issue too, but only in firefox (v37, windows 8.1 x64), not in Chrome : 
![select](https://cloud.githubusercontent.com/assets/1443499/7093176/382c406a-dfb7-11e4-8129-d7f10df26406.gif)

You can even see that the right-border of the md-content containing the big pink button at the bottom is bugged after the selection/deselection.

**Comment by mtt87** [comment]
It's not happening anymore I think we can close this.
