### ISSUE TITLE
mdList: arrow keys to select next/previous rows

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2255]
For the [List Controls](https://material.angularjs.org/#/demo/material.components.list) demo, the up and down arrow keys do not select/highlight the previous and next rows [respectively]. For me this is an expected functionality for a list.

**Comment by ThomasBurleson** [comment]
The List control is not a Table or DataGrid component, it is a visual, row-based layout component with primary and secondary actions possible for each row. As such:

*  No click row highlight (that persists)... no selected row indicator.
*  No arrow key navigation
*  Click generates row ripple and focus on primary action (if any)
*  Tab from primary focus will go to secondary (if any) or next primary
*  Spacebar for action trigger also generates row ripple effect

**Comment by ThomasBurleson** [comment]
Reopen after review with JoeyE @ Material UX

**Comment by rschmukler** [comment]
@ThomasBurleson what is the status on this?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
