### ISSUE TITLE
md-checkbox: shows ghost dot inside label tag

### ISSUE THREAD

**Issue by ivanhtp** [angular/material#2257]
I'm using a md-checkbox inside a md-list like this way:
   - md-list > md-list-item > div > md-checkbox. 

No custom css written at all. 

When I check the md-checkbox, a very small dot appears beside it. Inspecting I discovered that if you select (ctrl+a) and remove via inspector the content inside the <label> generated by the directive, the dot goes away. Curiously, there is no dot even in the inspector. 

I'm not sure, but could say its a lost invisible unicode character or a lost dot in the code.

I'm attaching the process.
![screenshot 2015-04-10 16 36 02](https://dl.dropboxusercontent.com/u/1568348/Screenshot%202015-04-10%2016.36.02.png)

**Comment by marcysutton** [comment]
Can you check this again against the code in master or in 0.9.0-rc1?

**Comment by ivanhtp** [comment]
Hey Marcy,

I just tested and seems it works. Well, 0.9.0 broke a lot of other things in my project to be honest but I will give it a way.

Thanks and case closed :)

**Comment by marcysutton** [comment]
Yeah there are some breaking changes in 0.9, we are trying to strengthen and stabilize the API ahead of 1.0. Let us know in the forum or in separate issues if there is anything you can't figure out. Thanks!
