### ISSUE TITLE
mdList: CSSLint failures with build of CSS

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2258]
CSSLint issues with /bower-material/angular-material.css for the md-list items.

![screen shot 2015-04-10 at 3 04 50 pm](https://cloud.githubusercontent.com/assets/210413/7095875/9d5695f4-df93-11e4-942e-d8c153788fe6.png)

**Comment by ThomasBurleson** [comment]
Fixed with 2f9eef70b5503b4fcb5c7cbe09712700403cc5a3

**Comment by ThomasBurleson** [comment]
Reopening to address some of the warnings still present.

**Comment by rschmukler** [comment]
@ThomasBurleson just ran the latest code through it and we only have the `@-moz-document url-prefix() {}` warning. I presume the others have been solved. Feel free to re-open if I missed something.
