### ISSUE TITLE
Input value from Cache is turning Yellow & blurry

### ISSUE THREAD

**Issue by KSanthanam** [angular/material#2260]
I have the email address input inside md-container. If the input is selected from the cache then the field is turning Yellow & blurry. If I add a character or remove a character and re add the yellow goes away.
My html & signin.modelOptions = {updateOn: 'default blur'};
      &lt;md-input-container layout-fill&gt;
               &lt;label&gt;Email&lt;/label&gt;
               &lt;input  name="emailAddress"
                      form-name="signinForm"
                       required 
                       ng-model="signin.credentials.email"
                         ng-model-option="signin.modelOptions" 
                        placeholder="Email" type="email"&gt;
             &lt;span layout-fill
                  ng-messages="signinForm.emailAddress.$error"&gt;
                  &lt;span layout-fill ng-message="required"&gt;Email is required&lt;/span&gt;
                  &lt;span layout-fill ng-message="email"&gt;Must be a valid Email address</span&gt;
             &lt;/span&gt;
         &lt;/md-input-container&gt;

1. Select from the history
![screen shot 2015-04-11 at 11 07 35 am](https://cloud.githubusercontent.com/assets/11584231/7099649/566ce244-e03b-11e4-8f75-93ed2bb6faca.png)

2. Selected
![screen shot 2015-04-11 at 11 07 47 am](https://cloud.githubusercontent.com/assets/11584231/7099650/5e8471f4-e03b-11e4-92f0-d15a7980e4b8.png)

3. add a character.

![screen shot 2015-04-11 at 11 07 55 am](https://cloud.githubusercontent.com/assets/11584231/7099651/67ffec68-e03b-11e4-9154-51f2cd8880e7.png)

**Comment by ThomasBurleson** [comment]
@KSanthanam - Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by Mutmatt** [comment]
This is most likely due to the autofill from chrome.  It is a bug in how chrome deals with populating fields with stored data.  I could find the bug if you need

**Comment by KSanthanam** [comment]
@ThomasBurleson. Sorry my code is reorganised into components. I am not able to replicate on Plunker without the folder structure needed for the components. Can I give you the components code, would it help. I reckon it is the angular-material/angular-animate issue.  If you need I can send you the component code.

@Mutmatt There are two issues. 1) The blur & 2) the yellow background.

**Comment by Antariano** [comment]
The problem is chrome's autofill having, by default, a yellow background.
There's to parts here to fix:

1) Yellow background. You can fix this with 
```
input:-webkit-autofill {
    -webkit-box-shadow: 0 0 0px 1000px <your-bg-color> inset;
}
```
2) Shadow (which appears as a blur)
```
input:-webkit-autofill {
   text-shadow: none;
}
```

However there's also accessability to consider. The yellow background is a universally recognized style for chrome users and overwriting it should only be done for very valid reasons. :)

**Comment by naomiblack** [comment]
dup of #1376
