### ISSUE TITLE
$mdAutocompleteCtrl Duplicates in a repeater are not allowed.

### ISSUE THREAD

**Issue by rhelenagh** [angular/material#2262]
After select one item from the list in the $mdAutocompleteCtr  

Angular report a Duplicates key.

Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: (index, item) in $mdAutocompleteCtr.matches, Duplicate key: string:ACT, Duplicate value: ACT

I made the change in: (angular-material.js) as workaround
...
<li ng-repeat="(index, item) in $mdAutocompleteCtrl.matches track by $index"\

But the result are not the appropriated. 

the list is like:
...
Test ACT code
Code ACT
ACT
Another ACT code 2
...

**Comment by rhelenagh** [comment]
I changed to:
 <li ng-repeat="(index, item) in $mdAutocompleteCtrl.matches track by index"\

Not Error are reported but the performance is extreme poor, slow. :-(

**Comment by robertmesserle** [comment]
@rhelenagh Why would you want to allow duplicates in a list of suggestions?

**Comment by rhelenagh** [comment]
@robertmesserle Of course, the list doesn't have any duplicate ítem.


Here some of the code, for reference only.

<md-autocomplete
          md-no-cache="false"
          md-selected-item="selectedItem"
          md-search-text="searchUntersuchung"
		  md-selected-item-change="selectedItemChange(item)"
          md-items="item in querySearch(searchUntersuchung)"
          md-item-text="item"
<md-autocomplete
          md-no-cache="false"
          md-selected-item="selectedItem"
          md-search-text="searchTitle"
		  md-selected-item-change="selectedItemChange(item)"
          md-items="item in querySearch(searchTitle)"
          md-item-text="item"
		  placeholder="Title">
..

		  
function querySearch (query) {
	var lwcQuery = angular.lowercase(query);
	var lwcSelected = angular.lowercase($scope.selectedItem);
     if (lwcQuery === lwcSelected) {return [];}
	  var results = query ?  FilterTitle(query)  : [], deferred;
	  return results;      
    }


function FilterTitle(query) {
	 deferred = $q.defer();
	 $scope.titles = [];
     $http({ url: '/api/titles',  method: "GET", params: {title: query}, cache:true}).success(function(data){	
	      angular.forEach(data, function(result){
	          $scope.titles.push(result.Title);
			})
		  deferred.resolve( $scope.titles);
		 })
		return deferred.promise;
	  };
	
  function selectedItemChange(item) {
      // Extra: reset the list, is not necessary. 
      $scope.titles = [];
    }

**Comment by robertmesserle** [comment]
@rhelenagh It's hard to tell exactly what's going on without being able to debug the code, but my first step would be to make absolutely sure that there were no duplicates in `$scope.titles` by adding this:

```
angular.forEach(data, function(result){
//-- add a check to make sure the item doesn't exist already
if ($scope.titles.indexOf(result.Title) < 0) $scope.titles.push(result.Title);
})
```

Since you are only passing an array of strings (or so it seems), it's unlikely that any of the other common `ng-repeat` issues would be occurring.

**Comment by rhelenagh** [comment]
@robertmesserle In theory should not exist duplicates in the list. I have reviewed the Ali that generates the list and included an option of "distinc", to ensure unity. Now works properly without adding track by ...
Thank you very much for your time and information.
