### ISSUE TITLE
md-card should have an md-card-image directive 

### ISSUE THREAD

**Issue by programming-kid** [angular/material#2266]
According to Google design spec a cad has following components
An image, a title text inside image, card content and card-footer
i md-card should have following structure 
[example](http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7Qkl1T0YzeHpFNzA/components_cards1.png)
```html
<md-card>
    <md-card-image src="img.png">
        <md-card-title>
            this is card title
        </md-card-title>
    </md-card-image>
    <md-card-content>
        this is card content
    </md-card-content>
    </md-card-footer>
        cta-button | cta-button
    </md-card-footer>
</md-card>
```

this would make life of a mobile app designer very easy 

thanks

**Comment by vacarsu** [comment]
This is a good idea, I actually designed my own card header for images for this purpose, 
![screen shot 2015-04-11 at 12 36 51 pm](https://cloud.githubusercontent.com/assets/11384972/7102947/837a91bc-e047-11e4-849e-27bf51f38974.png)

**Comment by epelc** [comment]
@programming-kid You just put your image above `md-card-content`

Example
```
<md-card>
    <img src="somepic.png" />
    <md-card-content>
        ...
    </md-card-content>
</md-card>
```

**Comment by vacarsu** [comment]
I think he is asking for something that is more declarative and styled by default to material specifications for momentum.

**Comment by programming-kid** [comment]
@epelc yes i know we can do that , but as @vacarsu am looking for a more standard way to build cards. :+1:

**Comment by epelc** [comment]
I think it'd be good if there was an `md-card-header` much like `md-card-footer`. It'd be declarative and you wouldn't need to remember that cards don't have a header element. Then you could just put the `img` inside of the header and either have a special class to style it this way or more likely just default it to this.

**Comment by WhiteAbeLincoln** [comment]
I agree that there should be a md-card-header. That would help it match the [specification](http://www.google.com/design/spec/components/cards.html#cards-actions) a little more, allowing for an Avatar, Title and Subtitle area as shown in the example, and making the card a little more versatile out of the box
![mdcard](https://cloud.githubusercontent.com/assets/7330103/7242145/daca0158-e78d-11e4-9cb0-525146e4b04b.png)
Right now, you have to provide your own custom styling to achieve this, and that just gets messy.

Ideally, there would be an element for every one of these content blocks (header, Media area, Supporting text, Actions), and we could configure their view order by the order we define them in the html (or using layout-align). Allowing for a layout like this 
![image](https://cloud.githubusercontent.com/assets/7330103/7242202/5dd164a6-e78e-11e4-9647-2997df8ea60e.png) but still using the same components.

To further follow the specification, there could be an option (md-aspect-ratio) on the Media element to make the Media section 1:1 vs 16:9 to match the different layouts in the specification.
![image](https://cloud.githubusercontent.com/assets/7330103/7242271/d5a3f8e0-e78e-11e4-81d1-17bdb36aa4ff.png)

Here are all of the content blocks, that can be used in different orders to make a variety of card layouts
![image](https://cloud.githubusercontent.com/assets/7330103/7242326/736962a4-e78f-11e4-8ad2-370a7cc4ff46.png)

**Comment by ThomasBurleson** [comment]
Love these idea. Let's make something happen in 0.10.

**Comment by programming-kid** [comment]
:+1: @WhiteAbeLincoln excellent points

**Comment by robertbaker** [comment]
I would also like to see md-card-header which can have a ng-click and supports md-secondary.
Inbox style, collapsed card showing header that's clickable.

**Comment by viztastic** [comment]
Would be great to have an md-card-image support SVGs and not just standard <img > tags.... would be great to have SVGs that span the full width of the md-card-image.

**Comment by programming-kid** [comment]
excellent point @viztastic

**Comment by jelbourn** [comment]
@EladBezalel what's the relation of this issue to your recent card changes?

**Comment by EladBezalel** [comment]
@jelbourn most of it is implemented
