### ISSUE TITLE
switch theme on md-toolbar doesn't work unless alwaysWatchTheme enabled

### ISSUE THREAD

**Issue by freshsun** [angular/material#2269]
i write it accoding to the document, but theme won't change unless i set alwaysWatchTheme to true
see http://plnkr.co/edit/JZIorUvX57jhuGKGsBxg?p=preview
both 0.8.3 and master tested

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
