### ISSUE TITLE
md-select scroll to top of the page on first use

### ISSUE THREAD

**Issue by mathieurivest** [angular/material#2270]
Whenever I use md-select dropdown, whether on mobile or desktop, the page get scrolled to top on first use (subsequent uses are fine).

Everything works fine if I disable _focusedNode.focus()_ in md-select's _animateSelect_ method:
```javascript
    if (focusedNode) {
        opts.focusedNode = focusedNode;
        focusedNode.focus();      // <-------- Culprit!
    }
```

Obviously by "everything" works fine, I mean everything except keyboard focus which I've just disabled.

**Comment by rschmukler** [comment]
Are you running `0.8.3`? If so, this bug was fixed (see #1721 and #1648) and will be in `0.9.0`.

**Comment by mathieurivest** [comment]
Yes, I am. I will be looking at 0.9 then. Thank you for the help!

**Comment by ilanbiala** [comment]
@rschmukler if it's going to be in 0.9.0, shouldn't the milestone be 0.9.0?
