### ISSUE TITLE
using material with ionic break the ionic app

### ISSUE THREAD

**Issue by programming-kid** [angular/material#2272]
i am confused, using material with ionic app breaks ionic app without error. Everything seems working but routes don't change at all.
It works on chrome on desktop but not as ionic app on mobile , so i opened same ionic app through chrome browser on mobile it dosen't run there either but if i ```Request deslktop site``` it works again.  I am not sure what's wrong with ```angular-material``` just  having this  ```angular-material.min.js``` in index.html breaks the app, i didn't even inject ```ngMaterial``` in angular app

i have create a demo https://github.com/programming-kid/ionic-material-app-demo for review 

i am using latest versions of ionic and angular-material

pls help
thanks

**Comment by ThomasBurleson** [comment]
@programming-kid - we encourage all developers to search our known issues before posting new issues. There are known conflicts with Ionic and Angular Material on Mobile.

**Comment by programming-kid** [comment]
@ThomasBurleson thanks for quick response but, i think this issue should be open but can be postponed until all issues in material are resolved , i believe ```ionic + material``` are gonna be awesome together & many developers are looking forward for it .

I think this is a minor issue as i have narrowed it down to browser level as it works fine in  desktop browser and not in mobile devices  , i was even able to replicate it on chrome emulator.

I think you should have a look at it and i am sure you may be able to fix it real quick

**Comment by ThomasBurleson** [comment]
@programming-kid - I closed this issue because it is essential a duplicate. Nevertheless with your feedback, I will leave open and close with the other 'dups'.

**Comment by programming-kid** [comment]
thanks @ThomasBurleson   for considering my request its really appreciated :+1:

**Comment by jobsamuel** [comment]
Hey @programming-kid, did Angular Material **v0.10.0** solve your issue? I'm looking forward to create something similar but I'm worried about this :pensive:

**Comment by programming-kid** [comment]
i haven't tried material v0.10.0 yet , but will soon give it a try meanwhile u can clone my above repo and replace angular material with v 0.10.0 and see if it works

**Comment by mackelito** [comment]
@programming-kid did you ever try and updated angular material? I´m about to start a ionic project and would love to use this as a base :)

**Comment by programming-kid** [comment]
@mackelito i have moved on from that project i may not able to help sorry.
