### ISSUE TITLE
Body font size increased a lot

### ISSUE THREAD

**Issue by sondreb** [angular/material#2276]
Recently it appears that the font-size on the body was increased a lot, here is the css below:

body {
  font-size: 1.6rem; }

This change made my whole app act up, so I had to override the body font-size with !important and set it to 1.0em for proper sizing again. Is this going to be 1.6rem moving forward?

**Comment by grizzm0** [comment]
This was done in #2042 to move from em to rem for easier and more consistent sizing. I suggest you use the typography classes in the future to avoid such an issue again.

Yes, it's going to be 1.6rem from now on.

**Comment by TalPasi** [comment]
This happens to me as well, 
When running the app with CEF, the html font-size is computed as 10px (62.5%) and the body is 26px (1.6 rem) instead of 16px.

Do note that when running it with Chrome it works just fine.

This is a very recent problem
