### ISSUE TITLE
Roboto Cyrillic

### ISSUE THREAD

**Issue by turboraccoon** [angular/material#2277]
Is it possible to make roboto font for cyrillic ?
![default](https://cloud.githubusercontent.com/assets/10269841/7107116/4b2b1892-e162-11e4-98f1-93dc2f1f7fac.PNG)
![default](https://cloud.githubusercontent.com/assets/10269841/7107117/532d111c-e162-11e4-8cda-b2f75b1ec888.PNG)

**Comment by ThomasBurleson** [comment]
@turboraccoon - this request does not involve Angular Material. 
Perhaps you can ping [Christian Robertson](https://plus.google.com/110879635926653430880/about) with this request.
