### ISSUE TITLE
Slider handlers

### ISSUE THREAD

**Issue by adyba** [angular/material#2279]
Is it just me or inactive slider handles on sample "Rating: - demo of theming classes" at lower resolutions 12XX*7XX are not rounded? 
It looks like another (same color) circle popping one or two pixels on 10th o'clock (left upper quadrant) of the inactive handler. Is it possible that the popup with the current value/number is not hidden properly?

**Comment by ThomasBurleson** [comment]
![screen shot 2015-04-13 at 1 52 29 pm](https://cloud.githubusercontent.com/assets/210413/7122934/4bd436fc-e1e4-11e4-82ba-aa7342a2b15c.png)

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (538/500 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:21090)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avscF-000L6z-DJ
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:51 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=BkarQ7Uzfgf8bnOhAd1mH16RCLY=; b=jP1Ek19iLTLzaymd
	OjMPfYau1uu8292qrDKgKRrk02nPO5z8l0wKUef+N/bsmwrb2dJF7UIiQfnnTGI5
	X6OCZqaF92NiF12fp3ev7kyTO4ITyyKJbRm0OBQd6f9Z17yz8AmORYxI1ZO8jUFQ
	B2by7iQnjPCIHa6BNMSV1lzxmfg=
Received: by filter0420p1mdw1.sendgrid.net with SMTP id filter0420p1mdw1.32638.572273506A
        2016-04-28 20:32:16.958625207 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id CQoBgpikTJ2DMF0F7WFHdg
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:16.967 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:16 -0700
