### ISSUE TITLE
md-progress-linear not working in md-radio-button

### ISSUE THREAD

**Issue by tbuyle** [angular/material#2284]
I am using a radio buttons list to display available files.

When uploading a file, I'd like to directly show progress inside a new md-radio-button with a md-progress-linear.

But the progress bar is now showing, even when "forcing" the width of the content.

See http://jsfiddle.net/93x4h05z/

**Comment by ThomasBurleson** [comment]
You should **not** nest a progressbar within a radioButton; that is not semantically correct.
Here is a revised jsFiddle "[RadioGroup with ProgressBar](https://jsfiddle.net/ThomasBurleson/zgqrqwc0/1/)"

**Comment by tbuyle** [comment]
How could I align the progressbar with a given radio button ?

**Comment by ThomasBurleson** [comment]
@tbuyle  - These are great questions that are best posted in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
