### ISSUE TITLE
md-tab: Support ng-if & ng-show/hide better

### ISSUE THREAD

**Issue by epelc** [angular/material#2291]
I just ran into a couple of issues with tabs and `ng-if`/`ng-show/ng-show`.

ng-if
- `md-on-select` doesn't work if you tab has an `ng-if` that is initially falsy but becomes true

ng-show/ng-hide
- `ng-show` causes the following error if used with `md-selected`
![image](https://cloud.githubusercontent.com/assets/5204642/7122270/58742eb8-e1e8-11e4-8bb5-fd410c9026c8.png)  
This also stops `md-stretch-tabs="always"` from working because of the exception.

I tested theses with `0.8.3`. I wanted to record them because I wasn't sure if `0.9.0` was revamping tabs or not. I tested a little bit on master but there seemed to be other problems. Either way I think it'd be nice to support using `ng-if` or `ng-show/ng-hide` with tabs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
