### ISSUE TITLE
mdAutoComplete: backspace deletes previous chip

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2295]
When I have 1 contact chip and preparing to select another chip, I select all of the current filter text:

![screen shot 2015-04-13 at 1 43 17 pm](https://cloud.githubusercontent.com/assets/210413/7122762/268e6d64-e1e3-11e4-8a7e-dac24052d272.png)

When I hit the `backspace` key (to delete the selected text), this happens:

![screen shot 2015-04-13 at 1 45 07 pm](https://cloud.githubusercontent.com/assets/210413/7122794/40455aa6-e1e3-11e4-9f4e-d444e0517eef.png)

**Comment by typotter** [comment]
This appears to be fixed already. Backspace will clear then input. A subsequent backspace selects the last item in the list.

**Comment by ThomasBurleson** [comment]
@typotter - can you find the SHA for this fix, paste here and close?

**Comment by typotter** [comment]
Fixed by [b65236b](https://github.com/angular/material/commit/b65236b70ae3d6eb86d3d78631144fe65848d4ca)
