### ISSUE TITLE
mdAutocomplete: dropdown list and scrolling

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2296]
When I have a dropdown open:

![screen shot 2015-04-13 at 1 45 59 pm](https://cloud.githubusercontent.com/assets/210413/7122819/6ad844ae-e1e3-11e4-8712-9c7ba40593ae.png)

And then I scroll the window, the dropdown gets disconnected:

![screen shot 2015-04-13 at 1 46 57 pm](https://cloud.githubusercontent.com/assets/210413/7122830/830caf60-e1e3-11e4-9edb-9c97ec5a311c.png)

> Perhaps scrolling should simply auto-close the dropdown.

**Comment by typotter** [comment]
@robertmesserle md-autocomplete should re-snap on window scroll.

**Comment by ThomasBurleson** [comment]
@rschmukler - resposition or scroll-lock like we do with md-select. 
>I think we need to be consistent.

**Comment by ThomasBurleson** [comment]
@robertmesserle - (discussed this with @rschmukler) Let's make the `mdAutoComplete` and the `mdSelect` consistent and both use the **disable scroll** (aka scrollLock) feature. 

> But before we do this let's see how the `mdSelect` use of scroll lock works in the wild during 0.10.

**Comment by robertmesserle** [comment]
I definitely think it would be better to update the position on scroll
rather than disable scrolling.

**Comment by ramanathan92** [comment]
It is better to have it as a configuration.Because there is a jerk in Page when u click on md-autocomplete box.It tries to disable scroll even scroll is not their in the page.

**Comment by pencilcheck** [comment]
Disable scroll confuses users. Got a lot of angry emails and feedback when they just can't scroll out of the dropdown. Please remove the scrollLock feature.

**Comment by joaovieira** [comment]
Also having problems with this on a sticky header and a scrollable content (@v1.0.0-rc2):

![screen shot 2015-11-02 at 16 24 51](https://cloud.githubusercontent.com/assets/474603/10887304/4eef440a-817e-11e5-9f28-743b3986bf6b.png)

**Comment by spillevink** [comment]
@robertmesserle: Was this fixed or just closed? I could not find a commit which referenced this issue.

**Comment by bvsbharat** [comment]
screen lock on md-select still there, clients are confused with this feature.

**Comment by ravikajain** [comment]
This issue still appearing if you use md-autocomplete in md-dialog.

**Comment by perpetualtraveler** [comment]
Any solution for this issue?

**Comment by Splaktar** [comment]
@perpetualtraveler please open a new issue with a reproduction.
