### ISSUE TITLE
md-chips with auto complete : autocomplete menu is not placed where it should

### ISSUE THREAD

**Issue by TalPasi** [angular/material#2298]
It seems that the auto-complete menu is opening the position that it was last used, when you are modifying the content of the Chips by either clicking the remove button or using the backspace

this can be seen from the screenshot I took while playing with the [Chips demo page](https://material.angularjs.org/#/demo/material.components.chips)

![image](https://cloud.githubusercontent.com/assets/1816536/7125079/12c02da4-e1fc-11e4-9803-4af1737a3715.png)

**Comment by chrisguerrero** [comment]
I'm experiencing the same issue. It appears as though the menu opens in a position relative to the previous chip. If you then clear the input out and start typing again, the menu is re-positioned correctly.
