### ISSUE TITLE
mdDialog: positioning is misplaced in Firefox / IE 

### ISSUE THREAD

**Issue by altaihero** [angular/material#2306]
mdDialog: positioning is misplaced in Firefox / IE 

i am using 8.0.3 but error same 
 
when use on long scroll app

**Comment by marcysutton** [comment]
Hi, can you provide a Codepen or Plunker showing your "long scroll app"? Also, it might be worth waiting to check again until 0.9.0 is out, which will be *very* soon.

**Comment by altaihero** [comment]
Thank you.
 i am waiting 0.9.0
