### ISSUE TITLE
Please add a search form on the website

### ISSUE THREAD

**Issue by richardlt** [angular/material#2311]
This is a suggestion, I think the website need a search form to find quickly what you want. It's very difficult now to find something specific without knowing all the Angular-Material stuff.

Thanks.

**Comment by dmackerman** [comment]
+1 from me.

**Comment by ThomasBurleson** [comment]
@richardlt - Similar to what you see on Angular site, we are planning a to provide online doc features such as 
* Version Picker, 
* Search,
and more... stay tuned.

**Comment by marcysutton** [comment]
This can be tracked in #917.
