### ISSUE TITLE
md-list styles not available in Google CDN 0.8.3 CSS file

### ISSUE THREAD

**Issue by prodonjs** [angular/material#2312]
The CDN-hosted CSS file at https://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.css (and the minified version) do not contain styles for <md-list> and its subcomponents.

Is this due to issue [2258](https://github.com/angular/material/issues/2258), or is there another reason why those styles would not be available?

**Comment by dmackerman** [comment]
Yeah, saw this as well. I think that the new list component snuck into `0.8.3` accidentally, as some of the builds contain CSS and some don't. This particular build seems to contain the CSS:

`angular/bower-material@0.8.3-master-ebcd7f0` which is what we're using until 0.9 drops.

**Comment by marcysutton** [comment]
I'm pretty sure md-list was already in there, do you mean the new list controls with checkboxes and switches? Those will be available in 0.9.0, which will be released *very* soon.
