### ISSUE TITLE
mdBottomSheet: add md-bottomsheet-focus directive

### ISSUE THREAD

**Issue by dmackerman** [angular/material#2313]
It would be wonderful if `$mdBottomSheet` had an open to set focus upon opening, just like `$mdDialog`. I'm aware that this breaks screen readers, but we would like to set focus manually versus not having the choice.

FWIW: the `focusOnOpen` docs from `mdDialog`:

> `focusOnOpen` - {boolean=}: An option to override focus behavior on open. Only disable if focusing some other way, as focus management is required for dialogs to be accessible. Defaults to true.

**Comment by ThomasBurleson** [comment]
Recently we added a `md-sidenav-focus` directive to specify which element in the SideNav area should receive focus when the SideNav element is opened.

I think something similar for dialogs and bottomsheet would be very useful.

**Comment by marcysutton** [comment]
That would be a good addition. It already does set focus on the first item in the bottom sheet, FWIW.

**Comment by ThomasBurleson** [comment]
@marcysutton - true. With `md-dialog-focus` and `md-bottomsheet-focus` these would allow specific customized element focuses.

**Comment by juanpujol** [comment]
+1

**Comment by dmackerman** [comment]
Going to submit a pretty simple PR for this.

**Comment by ThomasBurleson** [comment]
Fixed.
