### ISSUE TITLE
md-select allow free text entry

### ISSUE THREAD

**Issue by rich-glow** [angular/material#2316]
It would be great if we could optionally allow free text entry in md-select.

The use case is if we want to allow user to select one of a few pre-determined value, or allow them to specify their own.

It *could* look something like this:
```html
<md-select force-selection="false">
```

**Comment by Tyrannmisu** [comment]
Maybe use <md-autocomplete>?
But it would be great if the autocomplete component would have the optional function to show all its options, this should cover the use-case here as-well.

**Comment by rich-glow** [comment]
@Tyrannmisu good idea :)

**Comment by rich-glow** [comment]
Based on the docs, it looks like this is resolved.

**Comment by singhsays** [comment]
Which docs? Can you point to a commit or the docs, where this is resolved? I have a similar use case where I am using md-autocomplete but that seems to restrict to forces selection from the suggestions. I would like to have free text input there as well.

**Comment by randallmeeker** [comment]
Looking for guidance to see if this was figured out. I can't see a way to do this with mdSelect or mdAutocomplete
