### ISSUE TITLE
md-icon-button: add support for md-mini and rounded container

### ISSUE THREAD

**Issue by robertbaker** [angular/material#2317]
I like the new md-icon-button.

It would be nice if md-mini would work that could limit the size of the button to be about 6px bigger than the icon.

It would also be nice to support either md-fab or have a md-icon-button-round. So it allows a square or round container.

![capture](https://cloud.githubusercontent.com/assets/907301/7148094/e0785646-e2b4-11e4-9d9c-80c64fd98b1f.PNG)

I propose:

```
.md-icon-button md-icon {
  height:auto; // or 80%-90%
  width:auto; // or 80%-90%
}
.md-button.md-icon-button.md-mini {
  margin: 0 0.3rem;
  height: 2.8rem;
  line-height: 2.8rem;
  width: 2.8rem;
}
```

ToDo: Rounded ripple container.

**Comment by marcysutton** [comment]
Related to #2373
