### ISSUE TITLE
md-list-item hijacks enter and space keypress events

### ISSUE THREAD

**Issue by beezz** [angular/material#2318]
Hi,

md-list-item adds keypress listener on its first child for enter and space, causing e.g. form not submitting by pressing enter and weird behavior of inputs in chrome.

Where it happens:
https://github.com/angular/material/blob/master/src/components/list/list.js#L188

e.g.
http://codepen.io/anon/pen/OPKjjE?editors=101

Can you guys suggest me some workaround, or is it bad idea to have form inside of list item and it'll be better to restructure it?

**Comment by fabiusss** [comment]
Hi,
I have same problem, 

space keypress  not work.

    <list>
      <md-list-item>
          <md-input-container >
              <label>Nome</label>
              <input ng-model="menuItem.name">
          </md-input-container>
       </md-list-item>
    </list>

**Comment by mindmelting** [comment]
+1
