### ISSUE TITLE
mdChips: editing existing chip

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2320]
*  Enter/Spacebar key on active chip should start edit mode on that chip item.
*  Double click on chip should auto-edit `unlocked` chip item

> UX specification details is still pending from the UX Material team.

**Comment by jill8668** [comment]
It would be nice to have this feature, and it is especially useful when the editing works with autocomplete.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
