### ISSUE TITLE
Tool Tips aligned differntly when first displayed in toolbar on right aligned md-button items

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#2324]
Setting up a simple toolbar with buttons on the right and adding tool tips results in the tool tips displaying differently the first time they are displayed 

HTML, and animation below, using 0.8.3 ( master ) no js code being used in controlled, it's just a stub

NOTES: 
* This only happen on right aligned buttons in the toolbar not left aligned
* After the first display the tool tip properly aligns itself 

```html
<md-toolbar ng-controller="MainToolbar">
  <div class="md-toolbar-tools">
    <span flex></span>
      <md-button class="md-icon-button" aria-label="Account">
        <md-icon md-svg-icon="img/account_circle.svg"></md-icon>
        <md-tooltip ng-cloak>Account</md-tooltip>
      </md-button>
      <md-button class="md-icon-button" aria-label="More">
        <md-icon md-svg-icon="img/more_vert.svg"></md-icon>
        <md-tooltip ng-cloak>More</md-tooltip>
        </md-button>
  </div>
</md-toolbar>
```
![tool tip glitch](https://cloud.githubusercontent.com/assets/5982829/7150904/fdd9c946-e2d6-11e4-9ac1-a21c20ad2278.gif)

**Comment by Todd-Werelius** [comment]
NOTE: This was caused by using AngularJS 1.4 which was included because of a bad gulp pattern, seems like animations in 1.4 cause a lot of problems with many directives, so I will close until 1.4 is officially supported

**Comment by ThomasBurleson** [comment]
@Todd-Werelius - **bad gulp pattern** ? Can you elaborate ?

**Comment by Todd-Werelius** [comment]
Not your issue, our gulp build system was generating references to 1.4
