### ISSUE TITLE
mdTabs: tabs with dynamic content

### ISSUE THREAD

**Issue by ferc** [angular/material#2326]
If I change the tab content dynamically (using an id), these changes do not show in the tab content, only change the node in md-tabs > md-tabs-wrapper > md-tab-data (because angular material copies the tabs I guess),

```html
<md-tab label="three">
  <md-content class="md-padding">
    <h1 class="md-display-2">Tab Three</h1>
    <p id="three-content-node">Some content</p>
  </md-content>
</md-tab>
```

```javascript
function TabsController($timeout) {
  $timeout(function() {
    var node = document.getElementById('three-content-node');
    
    node.textContent = 'another text';
  });
}
```

This bug only happens with 0.9.0-rc1 tag, with 0.8.3 tag works perfectly.

I wrote a minimalist Plnkr, in my case I am using a Google Maps inside a tab and I am trying to migrate from 0.8.3 to 0.9.0-rc1.

[Plnkr](http://plnkr.co/edit/T91EzVCvT30Wb5l4byap?p=preview)

**Comment by asthomasdk** [comment]
I am seeing an issue like this in 0.11.0. 

As soon as I place anything inside <md-tabs>, then I cannot access the elements using getElementById. 

If I move the same element outside <md-tabs>, getElementById works as it should.
