### ISSUE TITLE
Click Hijack doesn't work when jQuery is loaded

### ISSUE THREAD

**Issue by oliverzy** [angular/material#2328]
Hi,

In recent 0.9 release, I noticed that `md-button` ripple effect's behavior has changed.

**0.9**: the attached ng-click handler will be fired after the ripple animation ends
**0.8**: the attached ng-click handler will be fired when the ripple animation begin
Currently this behavior can only happen on IOS (Android Not Tested), desktop browser is fine.

**Comment by oliverzy** [comment]
This issue seems related to jQuery. If I remove jQuery, even in IOS, it's also fine.

**Comment by oliverzy** [comment]
The further investigation shows it seems related to click hijack. angular material will stop hijack click when jQuery is used. As a result, click delay will happen. It might not be directly related to ripple effect.

**Comment by oliverzy** [comment]
Looks like click delay is a hard problem. fastclick (https://github.com/ftlabs/fastclick) is most popular library to solve this problem across different kinds of touch devices.

Maybe it doesn't make sense that angular material will repeat these efforts.

**Comment by dougestey** [comment]
In my testing, this only happens when jQuery is loaded before Angular & Angular Material. When loaded afterward, the 300ms delay is gone and things appear to function as normal.
