### ISSUE TITLE
new typography feature causes issue on Chrome which default minimum font size is set to 12 rather than 10 (e.g. CJK)

### ISSUE THREAD

**Issue by oliverzy** [angular/material#2329]
In 0.9, line height is set to 3.6rem, in spec, it should be 3rem (36px)

**Comment by marcysutton** [comment]
3.6rem is 36px on a 10px scale. This was introduced with the [typography feature](https://material.angularjs.org/#/CSS/typography).

**Comment by oliverzy** [comment]
But if you looked at the demo page, the button height is actually 43px, not 36px

**Comment by oliverzy** [comment]
Hi Sutton,

I have tried to look at this issue via chrome developer tools, the problem is related to chrome `minimum font size` setting. For Chinese Locale (my case), the browser minimum font size is default set to 12. (See this article for more details: https://www.fyianlai.com/2012/01/google-chrome-minimum-font-size-issue/).

The new typography feature set html font-size to 10px scale. This is not allowed and chrome forces it to 12px. This leads to an issue I mentioned above.

Maybe it's better to use 12px as a basis. What do you think?

Best wishes,
Oliver

**Comment by marcysutton** [comment]
Buttons are showing as `height: 36px` in our demos, and I was unaware of the minimum font size issue you reported. We will discuss as a team about the best way to handle it. Thank you!

**Comment by oliverzy** [comment]
Hi Sutton,

Thanks for reopening the issue. I think it's not only an i10n issue, but also it will affect all the users that the `minimal font settings` is larger than 10. And to make things worse, the default value of `minimal font settings` for CJK users is **12** meaning the layout will completely broken for those users unless they change the browser default settings.

**Comment by ThomasBurleson** [comment]
@marcysutton - let's talk about this offline.

**Comment by marcysutton** [comment]
@oliverzy font size is set to 62.5% on the `html` element, and then overridden to 1.6rem on the `body`. So the font size of all pages is effectively 16px. So the resize issue happens off of the html element? Do you have tips on how to repro it so I can do some debugging?

**Comment by oliverzy** [comment]
@marcysutton To change the minimum font size in Chrome go to: settings > advanced settings > web content > font size > customise fonts then scroll down to the bottom and you will see the 'minimum font size' slider.

Then you can change it to 12 and see the result.

**Comment by marcysutton** [comment]
@oliverzy how common is it for users to change that setting? Just trying to gauge how many users will be impacted.

**Comment by marcysutton** [comment]
@oliverzy I'm seeing a very minimal impact when I change my browser's minimum font setting to 12. Can you elaborate more on what is breaking in the layout? This would be a major change, so we'd want to do it sooner than later. But as of right now, I'm not seeing enough of an impact to warrant changing it.

**Comment by oliverzy** [comment]
@marcysutton please checkout the button example (https://material.angularjs.org/#/demo/material.components.button).

You can see that although font-size is correct (1.4rem = 14px), the padding/margin/line-height are wrong. They are calculated relative to 12 (minimal font size) rather than 10 (defined on html).

And regarding the impact, I think most of the time user will not change this setting and tend to use default value. However, the problem is for CJK locale, the default value is 12.

**Comment by ThomasBurleson** [comment]
We are moving this to Milestone 0.10 to assess feedback from community at large.

**Comment by oliverzy** [comment]
@marcysutton  @ThomasBurleson I can workaround this issue by converting all rem to px.

This can be done automatically by using https://github.com/robwierzbowski/node-pixrem.

I can survive with it, you are free to let this issue open and focus on other important things.

Thanks for the attention.

**Comment by oliverzy** [comment]
This one has been fixed in 0.9.0, I think we can close this one.
