### ISSUE TITLE
md-select with div wrap content with fixed position and 100% width

### ISSUE THREAD

**Issue by jakubweber** [angular/material#2330]
![md-select](https://cloud.githubusercontent.com/assets/5078760/7157522/c25428f4-e370-11e4-9c05-fe241d4b7acf.png)

When md-select is open and layout has sidenav, wrap div with position: fixed;. width: 100%; exceeds from viewport.. 
When md-content contains elements with relative width it is problem.

![md-select2](https://cloud.githubusercontent.com/assets/5078760/7157578/4eebde1a-e371-11e4-9d1f-45acec5f880f.png)
md-content is 1243px wide, the div with position fixed has full width of viewport, but it needs full width of vp - sidebar width to solve this issue.

Maybe it's same issue like #2307

**Comment by FDIM** [comment]
Could anyone shed some light why position:fixed is set to some parent element?

**Comment by jakubweber** [comment]
I think reason is when md-select is open, it disables  unwanted scrolling on background.

**Comment by FDIM** [comment]
I think that whatever original problem is, different solution is needed. Atleast for desktops, 1900px wide overlay is not feasible in any scenario

**Comment by jakubweber** [comment]
I agree with different solution.

**Comment by FDIM** [comment]
For anyone else looking for solution for this, you can use my fork where this behavior is removed.
"angular-material": "https://github.com/FDIM/bower-material.git#master",

**Comment by jakubweber** [comment]
I'm using the master branch, but the issue still remained. @rschmukler

**Comment by vasanthB5** [comment]
How to increase the width of the md-select for some particular elements in the appalication.
