### ISSUE TITLE
mdTabs: disable swipe to navigate

### ISSUE THREAD

**Issue by dmackerman** [angular/material#2331]
By default it seems like this is enabled, even on desktop browsers where the interaction doesn't make a whole lot of sense. Would be nice if this was more of an opt-in situation, as there are issues with the desktop implementation right now.

**Comment by epelc** [comment]
Please be aware a lot of desktops/laptops have touch screens now. Perhaps the mouse shouldn't trigger it though.

**Comment by ThomasBurleson** [comment]
@dmackerman - since some components have a `md-no-ink` directive, I think it makes sense to have a n **opt-out** using the `md-no-swipe` directive.

**Comment by dmackerman** [comment]
@ThomasBurleson: makes total sense. I'd be down with either solution. :+1: 
@epelc: yeah, that's what I mean. Desktop really just means "mouse" in my scenario. :smile:

**Comment by PRiSMiWi** [comment]
I am facing the same problems, sometimes I only want to select text from a textbox and it swipes to the next tab... Would be nice to have a new directive "md-no-swipe"

**Comment by cleever** [comment]
Indeed this feature is very annoying on desktop. Maybe a "md-swipe" with a bool parameter is better.

**Comment by felipemeirelles** [comment]
Is there any workaround at this time? My app uses a map inside a md-tabs, you can imagine the problem :stuck_out_tongue:

**Comment by epelc** [comment]
@felipemeirelles Render the map outside of the tabs template. You have to manage the active tab and add some logic to activate it depending on the state on reload though.

Side note what are you using for maps? I had to roll my own google maps.

**Comment by felipemeirelles** [comment]
I use google maps for a long time, since the start of the v2 api, I think its arround 5 years now. But the google maps is just the bigger problem, if I try to select some text on text inputs its also triggers the swipe event.

**Comment by kiley0** [comment]
We're building a Tinder-like experience in which users swipe an `<md-card>` left to dismiss, right to save.  But we're doing this inside an `<md-tab>`, so the swipe is (not surprisingly) causing the tabs to switch.  Would be awesome to have a built-in `md-no-swipe` just like the existing `md-no-bar` and `md-no-pagination`, any updates?  Thanks!

**Comment by kiley0** [comment]
thanks!!
