### ISSUE TITLE
$mdBottomSheet scope undefined 

### ISSUE THREAD

**Issue by amille44420** [angular/material#2332]
Hi All,

Maybe I'm just wrong somewhere. I'm trying to open a bottom sheet (template from file & controller).

But, my controller gets successfully the scope is undefined unlike my template.

I've the same result with a template from string.

http://plnkr.co/edit/ceQBtLn1dbjLJWHOK3i8?p=preview

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
