### ISSUE TITLE
contact chips search box is not display 

### ISSUE THREAD

**Issue by johnlim5847** [angular/material#2333]
![screen shot 2015-04-15 at 10 33 29 pm](https://cloud.githubusercontent.com/assets/3675946/7161054/8cb7abf4-e3bf-11e4-8fbf-c73046696f02.png)

this is what i got 
![screen shot 2015-04-15 at 10 33 41 pm](https://cloud.githubusercontent.com/assets/3675946/7161066/97b14290-e3bf-11e4-9601-15c341f1749e.png)

may i know why the contact chips search box is not displayed on my app ? i have follow exactly what the demo site show but i still not able to get the search box display.Do i need to include an autocomplete directive to get it done ?  here's my code

```javascript
angular.module('app').controller('IndexCtrl', [
  '$scope',
  '$http',
  '$rootScope',
  '$auth',
  'Account',
  '$timeout',
  '$q',
  function ($scope, $http, $rootScope,$auth,Account,$timeout, $q) {

    $scope.querySearch = querySearch;
    $scope.allContacts = loadContacts();
    $scope.contacts = [$scope.allContacts[0]];
    $scope.filterSelected = true;
    /**
     * Search for contacts.
     */
    function querySearch (query) {
      var results = query ?
          $scope.allContacts.filter(createFilterFor(query)) : [];
      return results;
    }
    /**
     * Create filter function for a query string
     */
    function createFilterFor(query) {
      var lowercaseQuery = angular.lowercase(query);
      return function filterFn(contact) {
        return (contact._lowername.indexOf(lowercaseQuery) != -1);;
      };
    }
    function loadContacts() {
      var contacts = [
        'Marina Augustine',
        'Oddr Sarno',
        'Nick Giannopoulos',
        'Narayana Garner',
        'Anita Gros',
        'Megan Smith',
        'Tsvetko Metzger',
        'Hector Šimek',
        'Some-guy withalongalastaname'
      ];
      return contacts.map(function (c, index) {
        var cParts = c.split(' ');
        var contact = {
          name: c,
          email: cParts[0][0].toLowerCase() + '.' + cParts[1].toLowerCase() + '@example.com',
          image: 'http://lorempixel.com/50/50/people?' + index
        };
        contact._lowername = contact.name.toLowerCase();
        return contact;
      });
    }
    });
  }
]);
```

in my index.html 

```html
<div layout="row" layout-margin layout-fill layout-padding>
	
	<div flex>
	  <h2 class="text-center black">Tagged yourself</h2>
  <md-content class="md-padding autocomplete" layout="column">
    <p>
      Contact Chips.
    </p>
    <md-contact-chips
        ng-model="contacts"
        md-contacts="querySearch($query)"
        md-contact-name="name"
        md-contact-image="image"
        md-contact-email="email"
        filter-selected="filterSelected"
        placeholder="To">

    </md-contact-chips>
    <md-checkbox ng-model="filterSelected">Filter selected contacts from options</md-checkbox>
  </md-content>

	</div>
</div>
```

i got no error on console, however the searchbox is not appear on my app. your help is appreciated

**Comment by johnlim5847** [comment]
hmm i still can't get it running after 5 days. ahh this is frustrating

**Comment by sysupbda** [comment]
Hi @johnlim5847,

   Could you create a plunkr or something like this? Have you checked the resulting html? If the <md-contact-chips>..</md-contact-chips> were not expanded, could it be that you forgot to add the dependency to ngMaterial in your module's dependency?

Yours,
Ben

**Comment by johnlim5847** [comment]
@sysupbda  hi thanks for your reply, here's a plunkr(http://codepen.io/anon/pen/YXKjGb?editors=101)  i created just now. i pretty sure i have added ngMaterial in my module in my app.js 

```javascript
var app = angular.module('app',['ngMaterial','ngSanitize','ngAnimate','satellizer','ngResource','ui.router','ngMessages','angular-loading-bar','uiGmapgoogle-maps']).
 config(['$stateProvider','$urlRouterProvider','$authProvider','$locationProvider','$mdThemingProvider','cfpLoadingBarProvider','uiGmapGoogleMapApiProvider', function($stateProvider,$urlRouterProvider,$authProvider,$locationProvider,$mdThemingProvider, cfpLoadingBarProvider, uiGmapGoogleMapApiProvider) {
     uiGmapGoogleMapApiProvider.configure({
        //    key: 'your api key',
        v: '3.17',
        libraries: 'weather,geometry,visualization'
    });
  . . . .  . 
. . . . . . . 
. . . . . . . . 
```

**Comment by sysupbda** [comment]
Hi! What has happened is you are looking at the last version while looking at the demos and documentation (you can see at the top right that the documentation presents v0.9.0-rc), however in your codepen at least you are using https://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.min.js which is version 0.8.3 which has no md-chips or md-contact-chips support yet. The beauty and evilness of HTML5 supporting browsers is that they allow you to use tags that it does not recognize without complaining. In this case, even your ngMaterial version does not do anything with it.

You could try with https://rawgit.com/angular/bower-material/master/angular-material.js until there is a CDN for this latest version of ngMaterial like I do with http://codepen.io/anon/pen/vOBaQO to continue your development with md-contact-chips

**Comment by johnlim5847** [comment]
@sysupbda OMG, well at least i learned it the hard way, anyway thanks !

**Comment by johnlim5847** [comment]
@sysupbda  one more question, why is everything look so big in v0.9.0 ? i change the css(https://cdn.rawgit.com/angular/bower-material/master/angular-material.min.css) as well but everything just look big

**Comment by sysupbda** [comment]
I know. I noticed that too :) I can't comment on this. I am just a user of the amazing library myself, not one of its developers. https://github.com/angular/material/blob/master/CHANGELOG.md shows a number of CSS changes which is to be expected I guess. I think in general there was an effort to make some objects seem bigger specially when running on mobile screens.

**Comment by sysupbda** [comment]
I think we could close this issue, would you not agree?

**Comment by johnlim5847** [comment]
@sabrinaluo  yea sure, thank again !

**Comment by marcysutton** [comment]
Can you elaborate on what you mean by "everything just look[s] big"? The CSS is generally modeled after the spec. If it doesn't align for a particular component, a new issue should be opened.

**Comment by johnlim5847** [comment]
@marcysutton i think it might be my problem. 
so when i'm using this css(https://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.min.css) my web page look like this 
![screen shot 2015-04-21 at 9 11 46 am](https://cloud.githubusercontent.com/assets/3675946/7243926/8851bdfc-e806-11e4-80f4-3410cdeeadbb.png)

the contact chips look funny because 0.8.3 didn't included contact chips. 

and then when i'm using this css(https://cdn.rawgit.com/angular/bower-material/master/angular-material.min.css) it looks like this 
![screen shot 2015-04-21 at 9 08 24 am](https://cloud.githubusercontent.com/assets/3675946/7243941/c25d3e7c-e806-11e4-8e34-c75b36773783.png)

**Comment by rioll** [comment]
how long we have to wait until material design put the 0.9 version available ?

Do you have a solution to create the contact chips thanks to firebase (or another database) ? ( I mean, to get the contact from the database and to generate all chips with)

**Comment by ThomasBurleson** [comment]
@all - please do not comment on closed threads unless you wish to reopen the thread - due to a incomplete fix.
@rioll - Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial). And I will reply for all.
