### ISSUE TITLE
mdSwitch click and drag

### ISSUE THREAD

**Issue by GavinPalmer1984** [angular/material#2338]
Clicking the switch or text works great!  But if you attempt to click and slide the switch you can experience some problems.  I hate to admit that this is what I tried to do with the mouse when using the switch for the first time.

Low priority in my opinion.

**Comment by VilemP** [comment]
+1

Actually, most of the users who were facing this attempted to "slide" the switch to the "on" position. I think it is something you can expect on the desktop.
Unfortunately, sliding it from OFF to ON doesn't work, the switch returns back to OFF position and it is frustrating for the users.

**Comment by troch** [comment]
I am also getting issues with md-switch on a desktop. For me the drag and drop is working perfectly fine, however the click event is being triggered after a `dragend`:
- If dragged not over halfway -> model changes
- if dragged over halfway -> model changes twice

The click event listener comes from MdCheckbox directive (its link function is invoked by MdSwitch).

**Comment by uriva** [comment]
+1

**Comment by fergusg** [comment]
The cursor is also inconsistent - it's "move" over the switch itself, "pointer" in the surroundings, incl. any label.  A "move" cursor does suggest a slide action should work.

**Comment by chester1000** [comment]
+1

**Comment by oskarwrobel** [comment]
![md-switch-drag-issue](https://cloud.githubusercontent.com/assets/1057056/9970779/ac449564-5e57-11e5-9063-7c8953853f1a.gif)

Looks like drag isn't working properly when mouseup event is triggered over md-switch element..

**Comment by paullang** [comment]
+1

**Comment by farid00** [comment]
Did some looking into this and found the issue to be with the mdcheckbox click function like @troch did.  Basically the click feature triggers a flip of the model value.  Material copes with this by having mdswitch dragend event only flip the value if it shouldn't be flipped.  Effectively canceling the flip made by mdcheckbox when the cursor is not moved enough and allowing mdcheckbox to flip it when it has.  Going to tinker with both of them and see if I can get it to work without any magic numbers or such.

**Comment by DevVersion** [comment]
This drag experience should be clearly better in #6715.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
