### ISSUE TITLE
Not hiding ng-hide="$mdMedia('gt-md')"

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2341]
Not sure if others are experiencing this... following statement performs the media query correctly and returns TRUE when above md but does not actually hide the element.

ng-hide="$mdMedia('gt-md')"

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by daw451-duplicate** [comment]
http://plnkr.co/edit/5OnnM7jUghBtRRLiY6LL?p=preview

Here is an example tom

**Comment by gkalpak** [comment]
@daw451-duplicate: There are a lot of issues with your plnkr. 

1. You are trying to use Angular 2.x which is quit different from Angular 1.x  (e.g. does not have `ng-hide` directive).
2. You are not even referencing the 'angular2.js' correctly, so basically you don't have Angular on your page.
3. You are not including other modules that `ngMaterial` depends on (e.g. `ngAnimate`, `ngAria`).
4. You are neither creating nor bootstrapping an actual angular module/app.

--
If you fix those issues then you are pretty close:
`$mdMedia` is a service, so it is not available in the view unless you explicitly make it available on a scope or controller. E.g. `$rootScope.$mdMedia = $mdMedia;`

--
That said, `ngMaterial` provides a shortcut that doesn't need `$mdMedia` for using the predefined media queries: The `hide/show-[gt-]sm/md/lg` ([docs][1]).
So, in your case, you could just use `<h1 hide-gt-md>...</h1>`.

[Updated plnkr][2]

[1]: https://material.angularjs.org/#/layout/options
[2]: http://plnkr.co/edit/bY7Y2KKHSmSYAEST7tID?p=preview

**Comment by ThomasBurleson** [comment]
@gkalpak - nicely said.
@daw451-duplicate - I recommend you post any subsequent question (on this issue) in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

> Closing as not-an issue.
