### ISSUE TITLE
mdTabs md-selected mdTab md-on-select

### ISSUE THREAD

**Issue by sachinny21** [angular/material#2342]
Using md-selected on mdTabs with md-on-select on mdTab is causing the whole Tabs control  to not behave as expected.  The selected tab is lost and after selecting each tab, the md-on-select listener also stops working.  Either directive on its own works fine though.

**Comment by ThomasBurleson** [comment]
@robertmesserle - side affect ?

**Comment by robertmesserle** [comment]
@sachinny21 Can you provide a CodePen to demonstrate this?

**Comment by robertmesserle** [comment]
I created a CodePen to attempt to recreate this with no luck:

http://codepen.io/robertmesserle/pen/QweZmy

**Comment by robertmesserle** [comment]
Closing for now, will re-open when demo or further steps to recreate are provided.
