### ISSUE TITLE
Bottom sheet parent not defaulting to the root element

### ISSUE THREAD

**Issue by mrmeku** [angular/material#2343]
When I try to use $mdBottomSheet.show without specifying a parent in the options it crashes because the parent is undefined but the overflow property of the parent is trying to be read. You should check if the parent is undefined sooner

**Comment by ThomasBurleson** [comment]
@rschmukler - thoughts ?

**Comment by ThomasBurleson** [comment]
@mrmeku - Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by mrmeku** [comment]
Here is a demonstration of the issue. I think it has something to do with me defining a function on the prototype of my constructor. https://jsfiddle.net/kx9o1e27/3/

**Comment by mrmeku** [comment]
So I diagnosed the issue. When you make the body a ui-view (using ui-router) the issue comes up. A work around is to simply not do this.

**Comment by mrmeku** [comment]
Here is a plunkr demonstrating the bug: http://plnkr.co/edit/Xb0u0coTXVnHBrtg6tVO?p=preview
Please note that this bug did not exist with version 0.8.3

**Comment by ThomasBurleson** [comment]
@mrmeku - great research and bug find. Thank you.
