### ISSUE TITLE
docs: API/Demo/Github buttons in toolbar should use mdMenu

### ISSUE THREAD

**Issue by marcysutton** [angular/material#2348]
The toolbar in the Angular Material docs sometimes has up to 4 buttons in it (mdChips demo). There is logic in place to show and hide these dependent on demo availability, whether the current page is an API doc or a demo, and hiding on small screens. 

To make good use of space and better align with the Material Design spec, these buttons would work best in an mdMenu component (#78). This issue depends on that component to be completed.

**Existing Chips demo page header:**

![Chips demo page header](https://cloud.githubusercontent.com/assets/1045233/7171428/29a16672-e38d-11e4-93b6-b500c8dedd6a.png)

**Toolbar demo with icon buttons, including a menu. A search icon could replace the heart, with API buttons collapsed into the menu:** 

![Toolbar with icons demo](https://cloud.githubusercontent.com/assets/1045233/7171442/59e8f4bc-e38d-11e4-84a6-6960e8b60638.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
