### ISSUE TITLE
md-tabs not working with angular 1.4.0-rc.0

### ISSUE THREAD

**Issue by Alexandre-io** [angular/material#2352]
Unable to select an other tab after the first selection.

Here is the demo:
http://codepen.io/Alexandre-io/pen/OPKGQE

Working fine with angular 1.3.15 and seems to be related to md-dynamic-height.

**Comment by robertmesserle** [comment]
@Alexandre-io good find!  This was a bug in ngAnimate and a fix has been committed:

https://github.com/matsko/angular.js/commit/b9093ad8b22f611a2d4b27c097a5b8c011ecd92f
