### ISSUE TITLE
New Data Tables

### ISSUE THREAD

**Issue by calebeaires** [angular/material#2353]
Google has release Data Tables to its android sdk. Will it be supported on Material Angular?

Reference: http://www.google.com/design/spec/components/data-tables.html#

**Comment by dmackerman** [comment]
I'd think maybe at a base level they would in terms of styles and whatnot, but adding in complex sorting / filtering is probably out of scope. I could be wrong though. :smile:

**Comment by Angularjschile** [comment]
+1

**Comment by victormacae** [comment]
+1

**Comment by skolade** [comment]
+1

**Comment by dongmingliy** [comment]
+1

**Comment by ask007java** [comment]
+1

**Comment by lothargrieb** [comment]
+1

**Comment by ThomasBurleson** [comment]
Duplicate of #796

**Comment by davidpp** [comment]
Trying to figure out if tables are supported.  This issue has been closed because it's a duplicate of #796, but #796 is closed because of #2353 (this issue).  Catch 22? :)

**Comment by rudzikdawid** [comment]
+1

**Comment by 4z8397qju3k7** [comment]
+1

**Comment by pbaris** [comment]
+1
