### ISSUE TITLE
layout crunch

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2356]
having some issues with the layout. here is an example. The issue is i cant replicate in plunkr:

![image](https://cloud.githubusercontent.com/assets/798281/7182331/a161ddae-e41e-11e4-8b06-d0a590285648.png)

The issue seems to be here:

![image](https://cloud.githubusercontent.com/assets/798281/7182341/b19bf4ca-e41e-11e4-9064-8c20a7cc4652.png)

If i uncheck:

![image](https://cloud.githubusercontent.com/assets/798281/7182352/c279bd9a-e41e-11e4-8299-102a449b0cc0.png)

![image](https://cloud.githubusercontent.com/assets/798281/7182372/da1778ac-e41e-11e4-9f20-da886e7c9772.png)

Here is the HTML:

![image](https://cloud.githubusercontent.com/assets/798281/7182396/fa222f02-e41e-11e4-96fa-e6f0b5be8613.png)

has anyone seen this???

**Comment by marcysutton** [comment]
Can you put your code in a Codepen or Plunker so it can be debugged in a browser? Also, which version of IE is this?

One thing I have noticed is that elements can collapse if they are the first child of a flex container. You might try wrapping them in a div without flexbox on it.

**Comment by daw451-duplicate** [comment]
marcy you are right on this... when i took out the FLEX on the main div in another example it seem to fix the issue. I tried to port the same exact code to plunker but i cant get it to replicate. I got a little frustrated with the sample above so i switched over to the md-input-container and it seems to be working better. BUT there are major issues with the md-select. I believe some of the issues have been reported. Going to look through and see if i see anything else.

Here are some screen shots of another example that i still cant get plunker to replicate

<div layout-margin  class="md-whiteframe-z2">
                                <md-toolbar><label class="md-toolbar-tools md-subhead">Other</label></md-toolbar>
                                <div layout="column" >
                                    <div layout="row" layout-sm="column" flex>

                                        <md-input-container flex>
                                            <label>Added</label>
                                            <input value="{{practice.data.practice.DateAdded | date: 'MM/dd/yyyy h:mma'}}" />
                                        </md-input-container>

                                        <md-input-container flex>
                                            <label>Updated</label>
                                            <input value="{{practice.data.practice.DateUpdated | date: 'MM/dd/yyyy h:mma'}}" />
                                        </md-input-container>
                                    </div>
                                    <div layout="row">
                                        <md-input-container flex>
                                            <label>Note</label>
                                            <textarea type="text" rows="4" ng-model="practice.data.practice.Note"></textarea>
                                        </md-input-container>
                                    </div> 
                                </div>
                            </div>

![image](https://cloud.githubusercontent.com/assets/798281/7203162/ac512ecc-e4e6-11e4-8e77-7b49f0ae583c.png)

You can see the scrollbars for the dates. When i take out the FLEX on the main div i get this:

![image](https://cloud.githubusercontent.com/assets/798281/7203178/d0d39af0-e4e6-11e4-9a42-0ac741b00d64.png)

There is just one major issue with this one. Layout is better but the dates do not appear when value attribute is used on the input tag. I submitted this is another case that has a plunker.

I will continue to work to see if i can get this plunker to fail.

**Comment by daw451-duplicate** [comment]
So in the following plunker i get similiar issues but now it is caused by layout-sm="column"...

Not sure if you want me to open separate case???? I still cant get that flex issue to replicate... but you were right....

http://plnkr.co/edit/IOf9STVtJLLwPmG8CZT9?p=preview

This plunker sort of demonstrates it with the md-input-container approach. It works in chrome but not in IE 11. You must shrink the page... I get the following:

![image](https://cloud.githubusercontent.com/assets/798281/7203675/3978732a-e4ea-11e4-8e5f-75981e89d42f.png)

**Comment by daw451-duplicate** [comment]
OK FINALLY A DECENT EXAMPLE. Having a TON of issues in IE11 with the layout.  

http://plnkr.co/edit/mz3414wWTQfJPt6mHHDG?p=preview

If you run in IE it looks like this:

![image](https://cloud.githubusercontent.com/assets/798281/7235458/4fba5ada-e75c-11e4-846f-0989490bc65e.png)


if you run in chrome looks great:

![image](https://cloud.githubusercontent.com/assets/798281/7235466/61860fa2-e75c-11e4-9ac4-4bac8c8a4337.png)


There are persistent issues using FLEX with IE.

**Comment by daw451-duplicate** [comment]
Marcy any progress with this one??

**Comment by richshaw** [comment]
I had a similar problem today. Not fully tested but changing CSS from:

```css
[flex] {
  flex: 1;
  -ms-flex: 1;
}
```
To:
```css
[flex] {
  flex: 1 0 auto;
  -ms-flex: 1 0 auto;
}
```
Seems to fix the problem: http://plnkr.co/edit/GuKQubSuhOY2yllgP8Ld?p=preview

I think IE is setting flex-basis/-ms-preferred-size to 0 when we want auto.

**Comment by ThomasBurleson** [comment]
@richshaw The Angualr Material v0.11.2 fixes the layout **without** your css mods: 

http://plnkr.co/edit/3HpbxrcfnPlnYixwjftU?p=preview

To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
