### ISSUE TITLE
md-toolbar + md-content nested in another element rather than <body>?

### ISSUE THREAD

**Issue by brianfeister** [angular/material#2358]
Apologies if this is repeat, but I couldn't find it, so if nothing else, adding an extra link to the correct answer seems helpful.

In my application, I setup my `md-sidenav`'s, my main `md-toolbar`, and my main `md-content` in special directive that manages their controller, data, etc. called `<main-wrap>`.  The problem I'm having is that I find that `<md-toolbar>` and `<md-content>` must be direct children of the `<body>` element in order for their sticky behavior to function.  Is there a way I can do specific setup to wire up the functionality to behave correctly while still inside of my `<main-wrap>` directive?

**Comment by brianfeister** [comment]
In order to achieve my goal, I had a bit more nesting of elements than I would like.  As it turns out

```
<div ng-controller="AppCtrl" layout="column" style="padding-bottom: 15px;">

  <div><-- disrupts scroll behavior -->

  <md-toolbar>
    <div class="md-toolbar-tools">
      <h2 class="md-flex">Toolbar: md-warn</h2>
    </div>
  </md-toolbar>
  <md-content>
    <p>Lorem ipsum dolor sit amet, ne quod novum mei.</p>
  </md-content>

  </div>

</div>
```

and is fixed by adding `layout="column"` as many times as you have intermediate elements before getting to the `<md-toolbar>` and `<md-content>` elements:

```
<div ng-controller="AppCtrl" layout="column" style="padding-bottom: 15px;">

  <div layout="column"><-- preserves toolbar scroll behavior -->
  <div layout="column"><-- preserves toolbar scroll behavior -->

  <md-toolbar>
    <div class="md-toolbar-tools">
      <h2 class="md-flex">Toolbar: md-warn</h2>
    </div>
  </md-toolbar>
  <md-content>
    <p>Lorem ipsum dolor sit amet, ne quod novum mei.</p>
  </md-content>

  </div>
  </div>

</div>
```

**Comment by keymarkstuart** [comment]
@brianfeister thank you for the layout="column" in every element observation.  i could not get to the bottom of that one.
