### ISSUE TITLE
md-highlight-text does not work with Hindi

### ISSUE THREAD

**Issue by lothargrieb** [angular/material#2359]
Hi, I know it sounds very exotic, but md-highlight-text does not work with language hindi (hi).

**Comment by naomiblack** [comment]
We would love to get to this, but cannot before the beta. However, a PR would be very welcome if you (or anyone else) have expertise.

**Comment by DevVersion** [comment]
@lothargrieb Sorry for the late response, I'm trying to take a look at your issue.

![image](https://cloud.githubusercontent.com/assets/4987015/13570935/c46005a2-e471-11e5-9abc-994796680521.png)

But for now I'm not getting the actual problem, so it would be great if you provide a bit more information, and maybe a demo / screenshot.
