### ISSUE TITLE
Resolve Gesture conflicts with Ionic Framework

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2365]
Angular Material and the Ionic Framework (1.x) have both implemented internal Gesture systems; created to optimize click, tap, drag, and swipe features on Mobile and Desktop devices. And these considerations become even more complex with the introduction of jQuery to such hybrid (Ionic/Angular Material) solutions.

The Ionic and Angular Material gestures systems are not currently compatible. And simply disabling either of the Gesture systems would impact the components for that particular framework. 

For example, Angular Material could implement a solution that provides runtime detection of the Ionic Gesture system and dynamically disable the Material $mdGesture accordingly. That would, unfortunately, also disable Angular Material features that support dragging on Mobile devices.

A viable solution for version 1.x has not yet been identified. We will continue to work closely with the Ionic team to implement a common Gesture system for post-1.x versions of Ionic and Angular Material. And solutions and recommendations from the Angular Material community are welcome.

**Comment by GistCode** [comment]
Goodluck! I'm really excited in using angular material with ionic framework,

I have done a lot of workarounds with the components with data-tap-disabled="true" directive but I quit midway when I cannot make the ion-content scroll that occurs just by installing angular material

**Comment by dougestey** [comment]
+1. Exact same scenario as @GistCode. Good luck.

**Comment by GistCode** [comment]
Is using this code a recommended fix?

`$mdGestureProvider.skipClickHijack();`

I have done some limited testing and found it to be an ideal solution.

**Comment by ThomasBurleson** [comment]
@GistCode - we recently committed an auto-detection of Ionic to ignore Ionic events:  https://github.com/angular/material/commit/05788d242412f7b7d3babfab3931c0ee5a03aca2
This should work automatically and negate the need for a manual call to `.skipClickHijack()`.
