### ISSUE TITLE
.md-2-line list item font is too small

### ISSUE THREAD

**Issue by calebegg** [angular/material#2366]
[According to the Material spec](http://www.google.com/design/spec/components/lists.html#lists-specs), for a two line list item, the primary text should be 16px and the secondary should be 14px. In angular-material, the primary is set to 1em and the secondary is .75em. Secondary should be .875em, assuming the base font size is 16px.

Also, for our app, the base font size is 13px (the default desktop body text size for Material), so the list items are far too small unless we set the list's font size to 16px.

**Comment by marcysutton** [comment]
We have changed to `rem` units and the base font size is currently 10px. So it would be 1.6rem and 1.4rem, respectively.
