### ISSUE TITLE
Input Control

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2367]
http://plnkr.co/edit/bsgAfNwGjvqEaM2xnw9D?p=preview

Ok so there is some strange behavior happening when i go outside the norm... Have a couple of date fields that are readonly, so i placed the date in curl's to the <input> value property. AND set it to readonly.

This example shows the following:
1. The date only appears after clicking into the input
2. The date fields are sizing themselves the same size as the textarea. Not sure if this is correct or not. I assume this is correct but looks funny... the readonly sample shows the textarea on a new row so the dates do go back to the correct size. 
3. On the readonly set of controls the label does not animate nor set the text to the right typography. Also the input appears over the label when you click into the input. then disappears after you leave.
4. On the non-read only it does animate but the value only appears after you click into the input.

i would have expected the label to be at top, small, and the date visible but read only....

**Comment by ThomasBurleson** [comment]
Use new DatePicker.
