### ISSUE TITLE
md-select label doesn't get updated when md-option are rendered dynamically

### ISSUE THREAD

**Issue by rahul18gupta** [angular/material#2368]
When ng-model value is set and md-option are rendered dynamically, md-select label doesn't get updated automatically. Label value changes only after one clicks on select box. 

Please find demo at:  http://codepen.io/anon/pen/BNBBVB

Short term hack for this: http://codepen.io/anon/pen/YXKKJd

**Comment by rschmukler** [comment]
This has been fixed. Thanks!
