### ISSUE TITLE
TypeError: Cannot read property 'offsetHeight' of undefined

### ISSUE THREAD

**Issue by vacarsu** [angular/material#2370]
Just updated to 0.9RC and get this error on pages with md-tabs. Seems to only throw the error on tabs with dynamic height.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by vacarsu** [comment]
Here it is. http://plnkr.co/edit/zLgk8O9WhbavKi3iEpUd?p=preview

**Comment by vacarsu** [comment]
Ah it seems adding md-tab-body has fixed the problem, didn't realize this was required.
