### ISSUE TITLE
mdButton: icon buttons should have circular focus state

### ISSUE THREAD

**Issue by marcysutton** [angular/material#2373]
Currently, `md-button` icon buttons have a rectangular focus and pressed state. They should instead have a circular shape that grows out from the center, similar to `md-checkbox`. This also applies to secondary `md-icon` buttons in `md-list`.

**Current:**

![rectangular icon buttons](https://cloud.githubusercontent.com/assets/1045233/7194109/50d8c6aa-e45e-11e4-8f43-118ecd109293.png)

**Updated:**

![toolbar icon buttons with rounded focus state](https://cloud.githubusercontent.com/assets/1045233/7194126/9f2d11a8-e45e-11e4-8dbe-6be397bae730.png)

**Comment by ThomasBurleson** [comment]
Pending https://github.com/angular/material/pull/2460 PR fix.
