### ISSUE TITLE
unable to put md-tooltip inside md-icon (without a button)

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material#2375]
I have a simple use case where I show a [warning icon](http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/) to warn user about something. For that I use the following code:
```html
<md-icon md-font-icon="fa fa-exclamation-triangle" class="md-warn"></md-icon>
```
I do not have much real-estate on the page, which is why I'd like to display the message for the warning as a tooltip. However, the following code does not work:
```html
<md-icon md-font-icon="fa fa-exclamation-triangle" class="md-warn">
    <md-tooltip>
        {{message}}
    </md-tooltip>
</md-icon>
```

**Comment by marcysutton** [comment]
I swear we've had this discussion before. The problem is that then you are then only showing tooltips for mouse users, which is an accessibility and usability problem. For this reason we can't support tooltips on elements that don't receive focus.

**Comment by DmitryEfimenko** [comment]
I usually search for existing issues prior to creating one, but this time I could not find anything like that. My apologies if I repeated somebody else.
Your reasoning makes perfect sense though.
