### ISSUE TITLE
mdSelect: label not being replaced with the value selected

### ISSUE THREAD

**Issue by VilemP** [angular/material#2377]
**Issue:** 
When mdLabel is being used within the mdSelect, the label value is shown as current selection. Choosing any value from the option does not change anything - still the label is displayed as current selection, although the model gets updated.
See Plunkr: http://plnkr.co/edit/E1V6T40yXdTzJOBAb0wn?p=preview

The behaviour is the same whether or not the model has value or is null.

__Angular Material Version:__
master

__Browsers:__
Chrome  41.0.2272.118 m
FF 36.0.3  (in FF, the content following the mdSelect is not aligned the same way as in Chrome)

__Guidelines__
Generally, I fail to understand why the label should be rendered within the select (as current selection). I thought that is a role for the placeholder.

From http://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field it seems to be clear, that there is a need for a label behaving just similarly as with the normal text field, i.e. describing what the selected value means. Eg. _From_ and _To_ labels in the first screenshot (although I admit in that case these were the pickers). But the _Folder_ in the third screenshot shows it well.

**Comment by Anthropic** [comment]
They are shown together in the simple menu screen shots:
http://www.google.com/design/spec/components/menus.html#menus-simple-menus

**Comment by rschmukler** [comment]
@Anthropic `md-select-label` is likely going to be deprecated in the future, while the floating label will be added shortly.

Regarding the value not being updated, you have to specify the interpolated value into the `md-select-label` -- eg: `<md-select-label>{{pieces}} pieces ordered</md-select-label>`.
