### ISSUE TITLE
md-button(not raised): No background color on hover?

### ISSUE THREAD

**Issue by epelc** [angular/material#2382]
It seems that the slight grey background for non raised buttons has been removed. However this doesn't conform with the spec.

http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons

In `0.9.0-rc1` it currently looks like normal when it should look like hover with a slight grey background.
![image](https://cloud.githubusercontent.com/assets/5204642/7202783/64094dc8-e4e3-11e4-8045-d1acb4f1b4f9.png)

**Comment by epelc** [comment]
It also isn't showing when using `md-noink` as you can see in the buttons demo. I would think it's the same cause though.

https://material.angularjs.org/#/demo/material.components.button

**Comment by marcysutton** [comment]
We were actually going off of internal feedback that said "Buttons: we don't have hover states." I have followed up to clarify.

**Comment by epelc** [comment]
@marcysutton As a user it seems confusing when there isn't a hover state. The only visual cue I get that something is a button then is that the text is all caps. Also not having a hover state seems to go against having a focused state.

**Comment by marcysutton** [comment]
After looking closer at it, I totally agree. It's less clear with flat buttons that they are indeed buttons without some sort of visual feedback.

**Comment by epelc** [comment]
@marcysutton Thanks for the fix!

**Comment by ThomasBurleson** [comment]
@marcysutton - :+1:
