### ISSUE TITLE
md-chips look and feel doesn't match the "Underline" material look and feel

### ISSUE THREAD

**Issue by TalPasi** [angular/material#2383]
Consider the look and feel presented below 
![image](https://cloud.githubusercontent.com/assets/1816536/7203181/d39efaf4-e4e6-11e4-9e14-d826a67ec34b.png)

which matches the look and feel of material input controls

please check the [codepen](http://codepen.io/anon/pen/vEowvP) for a demo

**Comment by ThomasBurleson** [comment]
@TalPasi - I do not understand your issue here. Can you be more elaborate with more detail or a specific question?

**Comment by PDSBGreg** [comment]
I'm guessing he's referring to the border bottom color.  rgba(0,0,0,0.12) on the input field vs rgba(0,0,0,0.1) on the chip.

**Comment by TalPasi** [comment]
The main problem is that the default look and feel for the md-chips has a box-shadow, so if I try to place it within a form, it will look completely different from the other md-input-containers in the form.

![image](https://cloud.githubusercontent.com/assets/1816536/7205900/b272ad76-e4fa-11e4-8d5f-e0383b58ca9e.png)

vs

![image](https://cloud.githubusercontent.com/assets/1816536/7203181/d39efaf4-e4e6-11e4-9e14-d826a67ec34b.png)

**Comment by ThomasBurleson** [comment]
@TalPasi - Now I understand and agree that the whiteframe around the chips is not appealing.

**Comment by TalPasi** [comment]
Removing the box-shadow is a step in the right direction, however the overall look and feel is still different from the other input containers, as the background color is rgb(250, 250, 250) and there is no bottom border that will get the primary color once the control is in focus.

Placing this control next to other input containers, still doesn't look as good as the other containers

I will try to find the time to push a PR to address this.

Thank you,

**Comment by ThomasBurleson** [comment]
@TalPasi - excellent point. Reopening for now...

**Comment by robertmesserle** [comment]
Basic styles have been applied - opening a new issue for floating label support.
