### ISSUE TITLE
Enable required attribute for autocomplete for form validation

### ISSUE THREAD

**Issue by mindmelting** [angular/material#2384]
Would be nice to be able to specify an autocomplete field to be required so it can satisfy form validation techniques.

Even better if it could satisfy the nested ng-messages styling in the md-input-containers

**Comment by epelc** [comment]
+1 for autocomplete having a required attribute. I'm switching over my address forms to using autocomplete with the google places api and this would be really helpful.

**Comment by datak1d** [comment]
+1 for autocomplete required validation

**Comment by marcysutton** [comment]
Required style needed for autocomplete.
