### ISSUE TITLE
How to create a dropdown in the sidebar?

### ISSUE THREAD

**Issue by digitalcraftsman** [angular/material#2385]
I want to create similar dropdowns like those in the [docs of Angular Material](https://material.angularjs.org/#/) (see Services or Directives), but I can't find a proper example?

**Comment by marcysutton** [comment]
Hi, this is a custom implementation for the docs only...what you're looking for is the expand/collapse list control, forthcoming in #985. Going to close this as a duplicate, please refer to that issue. Thanks!

**Comment by WhiteAbeLincoln** [comment]
Just check the [source](https://github.com/angular/material/tree/master/docs/) for the docs on github. The relevant html code for the dropdown toggles and the link buttons are contained in `app/partials/menu-link.tmpl.html` and `app/partials/menu-toggle.tmpl.html`. The javascript logic for these components is contained in the `menuToggle` and `menuLink` directives in `app/js/app.js`. Also check the `menu` factory, which should be just above those directives, for the logic for defining links and toggles.

**Comment by digitalcraftsman** [comment]
Thanks for the quick response. 

@WhiteAbeLincoln I could extract the necessary code from your given references, but I my own implementation would seem a bit hacky. Meanwhile I'll wait until the component will be officially released.

**Comment by leocaseiro** [comment]
It's clear that the Docs has a very mature collapse/expand, why don't use same code to become a component? If you guys need for Docs it means everybody else would need also, right?

I'm not really happy to hack or create my own directive <menu-toggle>

The issue #985 is locked as Backlog and all topics on [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) seems inactive.

* [Expand/Collapse list control](https://groups.google.com/forum/#!searchin/ngmaterial/expand/ngmaterial/qL-6yH87tTU/wt_BYmi_yysJ)
* [RFC md-list-tile Directive](https://groups.google.com/forum/#!msg/ngmaterial/8A-UGPftGfA/_-DI4MNwFukJ)
* [How to create side nav's items look like the documentation's side nav?](https://groups.google.com/forum/#!searchin/ngmaterial/expand$20md-list/ngmaterial/hOMa3hQnef4/KtgmfKL2spYJ)

Every nice component I'm looking forward to use are backlog...not cool.

It's missing some contribution? PR? Why is backlog?

Thanks

**Comment by eqbalsajadi** [comment]
+

**Comment by mtushar091** [comment]
Here is One That Might help..
https://github.com/mtushar091/angularjs_sideMenu
