### ISSUE TITLE
docs: .md-subheader misnamed

### ISSUE THREAD

**Issue by jacktho** [angular/material#2387]
The docs reference .md-subhead but I only find .md-subheader in the CSS.

![image](https://cloud.githubusercontent.com/assets/8503272/7204131/d7afafa6-e4ed-11e4-87ac-764bfdd02461.png)

**Comment by marcysutton** [comment]
Look in `typography.scss`. This class is named `.md-subhead` and consumed as a typography class, based on the spec.
