### ISSUE TITLE
mdButton and mdTooltip

### ISSUE THREAD

**Issue by GavinPalmer1984** [angular/material#2388]
I love the tooltip on desktop with mouse.  I tried to use mdButton with mdTooltip hoping the md directives would solve the tooltip problem developers face when using tooltips for touchscreens.  It doesn't work as I was hoping.

suggestion:
When a tooltip and a clickable directive are used in combination the functionality should change from the default behavior.
pseudocode:
```
function onClick() {
    if (usingTooltip() && tooltipHidden()) {
        showTooltip();
    } else {
        doClick();
    }
}
```

**Comment by ThomasBurleson** [comment]
@GavinPalmer1984 - this would mean users would have to click 2x simply to get the action would expect with a single click.

**Comment by GavinPalmer1984** [comment]
@ThomasBurleson  - I guess I Just need to disable mdTooltip in some cases when I am on a touchscreen since hovering isn't really an option.

I try to conserve space on small screens by putting text in a tip and using an icon... a high priority for conserving space might warrant situations where a double click for the action is desirable.

I actually like the idea of allowing users to toggle the ability to see "helpful tips with double click" or "disable helpful tips with single click".  New users need tips.  Seasoned users probably don't.

Thank you for your work.
