### ISSUE TITLE
md-select and md-backdrop render

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2390]
In ie11 the md-backdrop is causing the screen to destroy and sometimes split the page in half.

http://plnkr.co/edit/qQ3zGWvTZmvCaR6h5sGc?p=preview

The plunker will show different behavior in ie11 vs chrome when the STATE md-select is clicked.

In chrome the scroll shows then disappears after close

in ie 11 the md-backdrop takes over the entire page..

**Comment by daw451-duplicate** [comment]
@rschmukler this is a perfect example of the page shift that i have been referring to with the md-select... so if you click the STATE md-select... The page shifts down and to the right (i.e. Run the Plunker in chrome)... I believe the backdrop issue though you have solved...??? Did you want me to open another issue for the shift??

**Comment by ThomasBurleson** [comment]
@daw451-duplicate - do you still see any issues with the latest code in #master?
If yes. plese create new issues. Thanks.

**Comment by jeffklassen** [comment]
I'm having the exact same problem in chrome.

**Comment by bahaaldine** [comment]
+1
