### ISSUE TITLE
Closure goog.require style should define some symbol for module name

### ISSUE THREAD

**Issue by mprobst** [angular/material#2393]
Code consuming the Closure modules should be able to reference some symbol from the library, so you don't get unused imports warnings, and you can properly establish the dependency structure of the code.

E.g.
```
goog.provide('ng.material.components.button');

ng.material.components.button.MODULE_NAME = 'material.components.button';
```

(It's a bit odd that the `goog.provide` has a `ng.` prefix unlike the component. I'm sure that'll bite people. Maybe we could fix that, too?)

Then we could write:

```
var button = goog.require('ng.material.components.button');

angular.module('myapp', [button.MODULE_NAME]);
```

@naomiblack @jelbourn @robertmesserle FYI.

**Comment by ThomasBurleson** [comment]
@mprobst - What are your recommendations or next steps for this?

**Comment by mprobst** [comment]
I think we have to take a step back and figure out what we think is possible here. In my testing, if you compile the Angular Material sources together with your app, you can very easily end up with a host of problems as the assumptions about optimization levels can be wrong. E.g. Closure compiler kills `.$inject` arrays and strips `$get` method definitions.

I'll chat with @robertmesserle about this next week, or maybe a bit later (next week is a bit busy). It might be easier to just ship Angular Material to Closure users like we do for Angular itself, as one big, precompiled binary, separate from the app.
