### ISSUE TITLE
md-tabs: border-radius creates a small gap if used as an expansion of a toolbar

### ISSUE THREAD

**Issue by TalPasi** [angular/material#2394]
With the risk of sounding t0o picky, the md-tabs has a border-radius of 2px, this in turn causes a small gap to be visible, once the md-tabs is placed immediately under an md-toolbar that share the same background color (in my case "md-primary")

The arrow in the following image points to the gap 

![image](https://cloud.githubusercontent.com/assets/1816536/7209922/39e28bc6-e51b-11e4-8217-3981ad73abfc.png)

**Comment by marcysutton** [comment]
PRs are welcome :)

**Comment by robertmesserle** [comment]
I coded for this use-case initially assuming the tabs would live within the toolbar; however, that makes it difficult to include content in your tabs.  Added a fix to master, but here's a codepen that includes the new CSS:

http://codepen.io/robertmesserle/pen/655834dc87053dded67734219ed1595d/

(Bower should be updated within the next hour or so, allowing the removal of the custom CSS in this CodePen).
