### ISSUE TITLE
(docs) Need md-sidenav example with md-toolbar, similar to docs site.

### ISSUE THREAD

**Issue by robertbaker** [angular/material#2396]
The sidenav example needs to be enhanced, showing an example using a md-toolbar with md-sidenav (like on the docs page).

**Comment by ThomasBurleson** [comment]
@robertbaker - These types of requests/questions are best posted on the Forum. 

> Check out http://codepen.io/ThomasBurleson/pen/ZYjpgL

**Comment by robertbaker** [comment]
Thanks for the codepen. It's a common use-case and we can get it wrong. I think it's common enough to be listed in the docs. Maybe under a new section that just lists codepen examples?

I had the toolbar first, then the side nav. Which broke scrolling on a recent master build. I didn't have anything to go on besides looking at the docs source.
