### ISSUE TITLE
md-tabs not showing content when one of the tabs is empty

### ISSUE THREAD

**Issue by gidomanders** [angular/material#2398]
While working on tabs I already prepared for a few more tabs but without content because I didn't have any content for the tabs yet. Since the update to 0.9rc the tabs didn't show any of the tabs. When viewing the code in Chrome Developers tool there is a ng-repeat in the md-tabs-content-wrapper but none of the tabs were in there.

So I tried a lot of things, did some research, tried some more things and finally found out the problem was that tabs without content make none of the tabs show. So whenever one of the tabs has nothing to show, I can imagine you want that when it's disabled and load the content when it gets enabled, none of the tabs show their content.

I'd love to have that fixed soon, so I won't have this problem again when I'm further in development of my project. To me it seems like a bug, but it could be working like this on purpose since 0.9rc.

**Comment by ThomasBurleson** [comment]
@robertmesserle - thoughts/comments?

**Comment by Frank3K** [comment]
I faced the same issue. As a workaround I used the following:

``` html
<md-tab ng-disabled="true">
	<md-tab-label>Some label</md-tab-label>
	<md-tab-body>&nbsp;</md-tab-body>
</md-tab>
```

Note that `disabled` used to work, but `ng-disabled` is only supported now. Furthermore, when changing `md-tab-body` to an element without contents (i.e. `<md-tab-body></md-tab-body>`), the problem you describe still persists.
