### ISSUE TITLE
md-tabs: Cannot read property 'offsetHeight' of undefined at updateHeightFromContent()

### ISSUE THREAD

**Issue by jbrown0** [angular/material#2402]
I saw [this](https://github.com/angular/material/issues/2370) issue from earlier today, but the resolution for that issue did not work for me.  See my plunkr below.  I'm assuming I'm doing something wrong.

My tabs are not drawn until there is data and that will come in through a rest call.  I simulated that by a $timeout in the plunkr and was able to recreate.  I think that is part of the problem, at the time of updateHeightFromContent() on line 13089 of 0.9RC1 the elements.contents is empty.

Any suggestions are welcome.  Sorry if I'm missing something obvious.

[http://plnkr.co/edit/Cmh46zfdn7zgWJlWbczo?p=preview](http://plnkr.co/edit/Cmh46zfdn7zgWJlWbczo?p=preview)

**Comment by vacarsu** [comment]
You're using a repeater to dynamically load the tabs in, adding a time out will cause the tabs to not load because their is nothing to load until the timeout finishes. This seems normal?

**Comment by jbrown0** [comment]
vacarsu, I think this is a valid usage scenario.  If you open the console you'll see the js errors that are generated.  They match the title of this issue.

**Comment by jbrown0** [comment]
I'm assuming by the assignment this appears to be a defect.  Is there any suggested workaround until this is implemented?

**Comment by robertmesserle** [comment]
@jbrown0 I agree, this is a completely valid use-case.  Adding a fix right now.
