### ISSUE TITLE
md-chip: md-chip-remove misaligned on Safari/Firefox 

### ISSUE THREAD

**Issue by websirnik** [angular/material#2410]
Currently in 0.9.0-rc1 on Safari/Firefox. Test here: https://material.angularjs.org/#/demo/material.components.chips

![screen shot 2015-04-19 at 11 53 01](https://cloud.githubusercontent.com/assets/282871/7219175/17abe3e2-e68b-11e4-97a5-1193f790beb7.png)

**Comment by Frank3K** [comment]
The first (black `x`) can be fixed by adding `vertical-align: bottom` [here](https://github.com/angular/material/blob/7d86788f607947774d247d5eef5e459fd8ecc616/src/components/chips/chips.scss#L82-L91). I did not test the latter (white `x`).

**Comment by toddpress** [comment]
thanks @Frank3K! Tested code from a [pull-request](https://github.com/angular/material/pull/3043) and it also fixes this in all tested browsers. Tested in Firefox 35.0.1 and 38.0, Firefox Developer ed 40.0a2, and safari 8.0.6.
