### ISSUE TITLE
what is tile.background class in Grid List demo?

### ISSUE THREAD

**Issue by david-gang** [angular/material#2411]
Hi,

I came accross the following code

```html
 <md-grid-tile ng-repeat="tile in vm.tiles"
                  md-rowspan="{{tile.span.row}}"
                  md-colspan="{{tile.span.col}}"
                  md-colspan-sm="1"
                  ng-class="tile.background" >
```

I don't find anywhere a documentation for the class tile.background and why ng-class instead of class is used.

Thanks,
David

**Comment by ThomasBurleson** [comment]
@shyndman - any feedback for David? 

> BTW, @david-gang is helping the Angular Material team with CSS documentation. #woot.

**Comment by epelc** [comment]
@david-gang If you look at the js it seems to be like it is a dynamic property which is set to apply different color backgrounds. It's used in the dynamic tile demo to color the backgrounds. You should also find several different color classes on the css tab of the demo which correspond to the js. It seems to set a different color depending on the position(in the array) of the tile.

**Comment by david-gang** [comment]
Hi @epelc,

I did not find the usage of the class.
What i see in the javascript is that the background property is set dynamically, but not an use of the css class.

Thanks,
David

**Comment by epelc** [comment]
@david-gang It is being used. Thats how `ng-class` works you dynamicly set it to a class name and it applies the class. If you look in the js you can see tile.background is set in the switch statement.

![image](https://cloud.githubusercontent.com/assets/5204642/7232901/272e572a-e74c-11e4-8fa4-045a22c19897.png)

**Comment by shyndman** [comment]
@epelc is correct

**Comment by david-gang** [comment]
Connecting it to #2425 This should be documented.

**Comment by shyndman** [comment]
I'm not sure it should be. ng-class is already well documented here: https://docs.angularjs.org/api/ng/directive/ngClass

**Comment by shyndman** [comment]
David, I think the confusion may be that you think tile.background is part of the component, when it's actually part of the demo. Take a look at the demo's accompanying JavaScript and you should see where these tile objects are coming from.

**Comment by david-gang** [comment]
@shyndman . You are right. Now i understand. So no need to document anything :-)
