### ISSUE TITLE
md-button with ng-link

### ISSUE THREAD

**Issue by RBleyenberg** [angular/material#2413]
Is it maybe possible to implement ng-link, within md-button. same as done for ui-router. So we can navigate through md-button with angular new router. for now i just use <a but sad panda :P 

Best regards,

**Comment by epelc** [comment]
+1 I think it's just a matter of time before the new router is supported.

**Comment by Spadavecchia** [comment]
feat(button): support angular-new-router ng-link #2478

**Comment by DevVersion** [comment]
This should be closed.
