### ISSUE TITLE
aria-label: Logging warnings even when labels are set

### ISSUE THREAD

**Issue by epelc** [angular/material#2415]
I just started getting `aria-label` warnings when my labels are set. I tried it in `0.9.0-rc1` and master.

![image](https://cloud.githubusercontent.com/assets/5204642/7221652/c5f0bb28-e6c0-11e4-93bb-35a1f0ec623e.png)

**Comment by ThomasBurleson** [comment]
epelc - To be safe can you provide a CodePen or Plunkr that demonstrates this issue.

**Comment by marcysutton** [comment]
I'm not seeing them on the checkbox demos on the docs website, are you instantiating them in ng-repeat? Agreed that a Codepen or Plunker would help us debug.

**Comment by epelc** [comment]
I just noticed it was only with one of my directives that wraps a checkbox. I'll make a plunkr to demonstrate it but essentially it isn't waiting for my `aria-label` to fill in my bindings.

**Comment by marcysutton** [comment]
That would be very helpful. I don't think anything changed with $mdAria in 0.9.0, so I'd be surprised if it didn't exist before. Sounds like a race condition.

**Comment by epelc** [comment]
@marcysutton I think it is. I'm having trouble reproducing it on plunkr but I got it working decently if you can do the following.

Here is a plunkr but to get the warning to show(without me setting up states and ui-router) you need to edit the js(I suggest adding random letters to `scope.currentLabel` on line 52) and then save the plunkr. Note you need to use a different string for each save as I think plunkr does some caching which causes the warning not to show.
http://plnkr.co/edit/vS9VUQVhKdVwKRfjT1nB?p=preview

Please let me know if your having issues getting it to show and I'll work on getting a better example.

**Comment by marcysutton** [comment]
@epelc I'd love to see this issue isolated from Plunker. There are too many variables to know what is causing it.

**Comment by epelc** [comment]
This has been annoying me for a while now(I was getting about 20 of these on half my pages). But I finally realized if you add any static character or anything before your binding it will suppress these messages. I think an underscore does the least damage to what screen readers see as a space doesn't work.

Example
`<div aria-label="_{{someVar}}"></div>`
Instead of
`<div aria-label="{{someVar}}"></div>`

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
