### ISSUE TITLE
Components not disabled when fieldset is disabled

### ISSUE THREAD

**Issue by josephma93** [angular/material#2417]
Hi guys,

This is the first time that I log a bug so I’ll try to do my best job.
I´ve notice that this components:
•	Checkbox
•	Radio
•	Select
Not behave as expected when you wrap all of them inside the fieldset tag and then set that tag as disabled.
Here is a Plunker URL for your reference: http://plnkr.co/edit/BgBsa5eOj4chzLbU1IJZ?p=preview

**Comment by mmiszy** [comment]
Moreover according to the HTML spec, `disabled` attribute is allowed not only on `<select>` but also on `<option>` tag. Currently none of `disabled`, `ng-disabled` or `ng-attr-disabled` is respected on the `<md-option>` element.

**Comment by jmls** [comment]
i've also noticed the same problem if you add the disabled attribute to the radio-group

http://codepen.io/anon/pen/rVvgQx

**Comment by marcysutton** [comment]
You need to use `ng-disabled` so Angular can properly disable that element. `disabled` only works on native inputs.

**Comment by jmls** [comment]
well, I tried ng-disabled, same issue ... see http://codepen.io/anon/pen/xGzxqP

**Comment by jepetko** [comment]
this issue seems still to appear in the version 0.10.0. ng-disabled evaluates false but disabled attribute remains "disabled".

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
