### ISSUE TITLE
md-select doesn't work in md-dialog

### ISSUE THREAD

**Issue by sheaujye** [angular/material#2419]
Happens in latest 0.9.0rc1
- Click on select element
- Whole dialog become blank
- Select menu dropdown appeared on the right of the dialog

Workaround: 
- Comment out line 8543: "disableParentScroll: true," in function selectDefaultOptions() of SelectProvider

Works fine in 0.8.3

**Comment by Tyrannmisu** [comment]
This is a duplicate of: 
https://github.com/angular/material/issues/2379

**Comment by rschmukler** [comment]
Closing as duplicate
