### ISSUE TITLE
Docs: $mdToast.simple() methods incomplete

### ISSUE THREAD

**Issue by michaelbromley** [angular/material#2420]
In the docs for the [$mdToast service](https://material.angularjs.org/#/api/material.components.toast/service/$mdToast), the API reference for the `$mdToast.simple()` method lists a bunch of chainable methods exposed by the return object:

* `content()`
* `action()`
* `highlightAction()`
* `capsule()`
* `theme()`

However, the [example source](https://material.angularjs.org/#/demo/material.components.toast) shows use of additional undocumented methods:

```JavaScript
$mdToast.simple()
        .content('Simple Toast!')
        .position($scope.getToastPosition())
        .hideDelay(3000)
```

In addition there are also the event-handling methods `onHide()`, `onRemove()` & `onShow()` available to chain.

**Comment by topherfangio** [comment]
I have updated the docs in PR #5550, however, I wanted to point out that the `onShow`, `onHide` and `onCancel` methods should be considered private as they are what actually show/hide/cancel the toast. If you override these, the component will not work correctly unless you re-implement the same functionality.
