### ISSUE TITLE
md-slider readonly mode

### ISSUE THREAD

**Issue by dohomi** [angular/material#2421]
Hello,
I couldn't find the possibility for having a ```md-slider```as readonly. Currently I only found an example for ```ng-disabled```but I guess a ```md-discrete```in combination with ```ng-readonly``` would be very useful for displaying a property in a detail view. Thanks

**Comment by kennethcachia** [comment]
Hi!

Readonly states for sliders are not [specified](http://www.google.com/design/spec/components/sliders.html#) and it’s also not implemented on [Polymer’s paper sliders](https://www.polymer-project.org/0.5/docs/elements/paper-slider.html).

I discussed this with someone on the Material Design team and we agree that we shouldn’t present a slider that can’t be changed.

Can you provide additional details on why you need a readonly state for a slider?

Thanks!

**Comment by dohomi** [comment]
Hi @kennethcachia 

Thanks for your reply. I try to solve a star rating which works very nice with this component. In the end there should be a view of the form where I would like to show the star rating result.

For sure I could write a displaying component which renders ```md-icon```stars. My previous component was similar to this one: http://plugins.krajee.com/star-rating

Thanks for the answer, I will write a small directive for display the rating.

**Comment by ThomasBurleson** [comment]
@kennethcachia - this is a interesting and viable (IMO) use case for slider: discrete steps skinned to render stars as the discrete steps.  Should this be reconsidered as a valid driver for `read only` sliders?

**Comment by kennethcachia** [comment]
Thanks @dohomi!

@ThomasBurleson I agree, but I'm inclining towards implementing this as a new component with the appropriate attributes. I spoke to someone on the Material team and they don't have any plans for star rating widgets yet. Should we get back to this later?

**Comment by dohomi** [comment]
We came up with following directive:

```
stars.html
<div layout>
    <md-icon md-svg-icon="toggle:ic_star_24px"
             ng-repeat="i in range(value)"></md-icon>
    <md-icon md-svg-icon="toggle:ic_star_outline_24px"
             ng-repeat="i in range(max-value)"></md-icon>
</div>


stars.js
angular.module('ptUtil')
    .directive('ptStars', starDir);

function starDir() {
    return {
        restrict: 'E',
        replace: true,
        scope: {
            max: '=',
            value: '='
        },
        templateUrl: 'stars.ng.html',
        link: link
    };
    function link(scope, element, attrs) {

        scope.range = _.range;
    }
}

```

Cheers

**Comment by ThomasBurleson** [comment]
Fixed with SHA e0abeb4dc46a1753616a911fe54f14d8f1148a25

**Comment by narendrasinghrathore** [comment]
Adding disabled to mat-slide using reactive form, it remove the control when you get form.value

**Comment by Splaktar** [comment]
@narendrasinghrathore Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
