### ISSUE TITLE
ng-click is not working as expected.

### ISSUE THREAD

**Issue by uxdesignz** [angular/material#2422]
ng-click is not working for all toggle button on mobile and iPad. I am using AngularJS v1.4.0-beta.6.

**Comment by epelc** [comment]
@uxdesignz Can you try updating angular to `1.4.0-rc0`. Also I'm not 100% if angular 1.4 is supported yet as it just became a release candidate but I'm sure it's in the works. Also I think the version of your browser/ios would help.

**Comment by ThomasBurleson** [comment]
@uxdesignz - Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by ariesxje** [comment]
I am using version 1.4.0, not beta or rc.
Any clickable element is weird on mobile.
1. clickable area of some elements(select, link, etc.) is bigger than the boundary of the element.
2. Incompatible to pure bootstrap collapse (sometimes works, sometimes not work at all)
3. Single tap on a clickable label or a select, but treated as tapping twice.

All of the above do not happen on 1.3.14.

**Comment by ThomasBurleson** [comment]
Insufficient information:

*  Angular 1.4.x is now supported. 
*  Known jQuery and touch issues; see `$mdGestureProvider.skipClickHijack();` for solution.
