### ISSUE TITLE
md-contact-chips show list on focus

### ISSUE THREAD

**Issue by dstudzinski** [angular/material#2423]
Hi,

Is there any possibility to show contact list on search box focus (before typing)?
I'd like to use contact chips to choose tags (from short list of tags - instead of multiselect solutions) and I like to show this list on focus on the search box (before user type anything).

Is it possible?

**Comment by maelfrize** [comment]
:+1:

**Comment by maku** [comment]
+1

**Comment by AdriVanHoudt** [comment]
This should be a general md-autocomplete feature

**Comment by smashercosmo** [comment]
It is easily achieved by using md-min-length="0"

**Comment by alphatwit** [comment]
+1

**Comment by suryaiiit** [comment]
+1
