### ISSUE TITLE
Not responsive on mobile

### ISSUE THREAD

**Issue by thejourneydude** [angular/material#2426]
I've developed my site using Angular Material. The desktop version is perfect. However, when viewed on mobile the entire site looks broken and misplaced. I'm wondering if this is because I have not set the cols size for every element on my site? Any help on how to fix this on mobile would be appreciated. Below I attached my meta tags in case that might be the issue. The site is [here][1] along with the [source code][2].

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="viewport" content="width=device-width">

  [1]: http://jasontanner.me
  [2]: https://github.com/thejourneydude/me

**Comment by epelc** [comment]
@thejourneydude I think you need to look into using the oposite layout on smaller devices.

For example if your site looks good on desktop with several cards in a row you should add the following to make them appear as a column on smaller devices/windows.
```
<div layout="column" layout-gt-md="row">
//Your cards
</div>
```

You can find the relevant docs for `layout-*` [here](https://material.angularjs.org/#/layout/alignment). Also note the `flex-*` variants may also be useful if your using `flex`.

**Comment by marcysutton** [comment]
I think the [Angular Material forum](https://groups.google.com/forum/#!forum/ngmaterial) would be a better place for this conversation.
