### ISSUE TITLE
md-slider: Ripple positioned slightly off and Outer circle background color not set

### ISSUE THREAD

**Issue by epelc** [angular/material#2427]
It seems that `md-slider`'s ripple is positioned slightly off to the top left.

You can see this on the slider [demo](https://material.angularjs.org/#/demo/material.components.slider) if you click on one of the slider lines. It's very fast but I managed to get a screenshot. I tried clicking on the slider in multiple places as I thought the ripple origin had to do with my mouse position but it didn't affect it. I think it should either ripple from the center or from the position of the mouse relative to the sliders dot. 
![image](https://cloud.githubusercontent.com/assets/5204642/7234442/28d0f4d0-e755-11e4-827c-64a311dfad9b.png)
Note that right now the ripple never reaches the bottom right corner and it appears to be created slightly off center.

It also seems the spec doesn't mention the outer grey circle seen below when you click and drag. 
edit - I think it is supposed to be colored the same as the ripple so it can look like the ripple doesnt go away until you release it. But the background color was never set.
![image](https://cloud.githubusercontent.com/assets/5204642/7234590/207c955e-e756-11e4-8131-754f6ee6350f.png)
Slider spec - http://www.google.com/design/spec/components/sliders.html#

**Comment by topherfangio** [comment]
There are a few issues design with the slider that we will need to fix. I can't seem to reproduce (or even see) the ripple issue, but I have fixed the grey circle.

Ideally, the focus ring would only appear on focus, not on click too, but that will require quite a bit of code changes to accomplish, and we wanted to get this CSS fix in to 0.11, so we'll try to fix the other issues before 1.0.
