### ISSUE TITLE
md-input-container using md-select puts label under select

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2428]
here is an example of the md-item-container putting the label after the md-select tag:

http://plnkr.co/edit/mz3414wWTQfJPt6mHHDG?p=preview

![image](https://cloud.githubusercontent.com/assets/798281/7235719/f9df708a-e75d-11e4-8c28-97be2e349604.png)

**Comment by rschmukler** [comment]
Please use the following syntax for your select:

```js
<md-input-container>
  <md-select placeholder="State">
    <md-option   ng-repeat="item in ctrl.states">{{item}}</md-option>
  </md-select>
</md-input-container>
```

We will likely extend `md-input-container` to do this for you automatically, but for now please use that syntax.
