### ISSUE TITLE
Is it possible to have an md-dialog expand downward with new content instead of re-centered?

### ISSUE THREAD

**Issue by shawn-simon** [angular/material#2431]
Is it possible to have an md-dialog expand downward with new content instead of re-centered? When I change tabs in my dialog, the window grows vertically, which recenters the dialog and looks bad. I could do this possibly by adding a class and making the dialog wrapper flex-start, but I don't see any way of attaching the class.

**Comment by marcysutton** [comment]
No, dialogs in Angular Material are modal dialogs...meaning they should cover content and prevent interaction behind it. You might want to look at `$mdToast` and specify a `parent`.

**Comment by shawn-simon** [comment]
Ok you completely misread my question then...

**Comment by marcysutton** [comment]
Gotcha. I saw a similar question on the forum earlier, sorry if I misunderstood. Dialogs also have a parent element, can you attach them to something that positions them correctly?

If that still doesn't answer the question, perhaps a wireframe illustrating what you're trying to do would help.
