### ISSUE TITLE
md-button icons disabled status does not "grey/dim" as it should

### ISSUE THREAD

**Issue by asans** [angular/material#2434]
This affects v0.9.0-rc1-master-aff50d5 (but probably all current master versions).

When a md-button is disabled, the icon itself is not dimmed.  Only the text is dimmed.

This causes the issue where md-icon-buttons (buttons with only icons) to show an inactive icon button the same as an active one.  

From Material Design Specs, the icon itself should also be dimmed down to show inactive status.

**Comment by epelc** [comment]
+1 Here is a picture to illustrate this. Also has the same behavior in `0.9.0-rc2`

![image](https://cloud.githubusercontent.com/assets/5204642/7301052/264f66fa-e9ae-11e4-9de8-2edc423fbf19.png)

**Comment by marcysutton** [comment]
Hi, can you provide a Codepen or Plunker showing this issue? Thanks.

**Comment by asans** [comment]
I'm not sure if there's a template or something to use for codepen/plunker (never used it before), but if you add a new disabled icon button to the demo, you will see that it looks exactly the same as an active button.  Nothing changes.  It might be a good way to use it to run functional tests.

I just tried it using chrome developer console to add a ng-disabled="true" to one of the icon buttons in the demo and nothing changed.

**Comment by epelc** [comment]
@marcysutton Here you go. Sorry it took a bit plunker was down for a minute and I got side tracked.

http://plnkr.co/edit/QCJp93rYMizbMd4U1UrB?p=preview
