### ISSUE TITLE
md-select in fullscreen mode forces the browser out of fullscreen

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2435]
if you are running your app using html5 fullscreen mode, clicking a select forces the browser out of fullscreen mode.

using chrome 42 on OS X 10.10.4

**Comment by rschmukler** [comment]
@hodeyp can you provide some demo code? I can't seem to reproduce?

**Comment by hodeyp** [comment]
quick hack... http://run.plnkr.co/vIEBdbLkhfylF3KD/

click the full screen button to put the element into fullscreen then click the select...

only runs in chrome as an example

**Comment by hodeyp** [comment]
sorry - use http://plnkr.co/edit/6e8QVH?p=preview

you need to click 'run the preview in a separate window' as plunker seems to be conflicting with the fullscreen api

**Comment by rschmukler** [comment]
@hodeyp thanks, I'll take a look

**Comment by rschmukler** [comment]
@hodeyp sorry on the massive delay on this. The plunker linked above doesn't seem to trigger full screen anymore. Any chance on a fix?

**Comment by rschmukler** [comment]
Closing until we can reproduce. Feel free to submit a new issue if it persists.
