### ISSUE TITLE
md-list-item with ng-click causes font size to be smaller (and other oddities)

### ISSUE THREAD

**Issue by hanthomas** [angular/material#2438]
The following Plunkr demonstrates the problem in 0.9rc1:  http://plnkr.co/edit/QrWRRWzXteZ1XynXRS7c?p=preview

It seems that the underlying issue is that the content of md-list-item is inheriting the styles from md-button class that wraps the content.  This only happens where there's an ng-click directive on the list item  Besides font size, it seem that other potentially undesirable styles such as line-height and white-space also affect the appearance and behavior.

**Comment by marcysutton** [comment]
A clickable list item with a button needs a larger hit area than a list item, so the line height should stay as-is. But the font-size is an easy fix with `font-size: inherit;`

**Comment by hanthomas** [comment]
Thanks for the workaround.  Regarding line-height + white-space, I understand your reasoning.  The only problem is that when the text is too long, because white-space is set to nowrap, it goes past the edge, ignoring padding and margin.  Looks ugly.  I tried a couple of ideas such as removing the nowrap, which results in weird wrapping issues (hence my complaint about line-height).  Perhaps md-list-item can be made so that it either truncates the text or shows ellipses.

**Comment by ThomasBurleson** [comment]
@hanthomas - please provide snapshot or CodePen or Plunkr that demonstrates this issue.

**Comment by hanthomas** [comment]
@ThomasBurleson - I made a change to my original plunkr which demonstrates the problem:

http://plnkr.co/edit/QrWRRWzXteZ1XynXRS7c?p=preview

**Comment by ThomasBurleson** [comment]
@hanthomas - Thank you.

**Comment by marcysutton** [comment]
@hanthomas I'm adjusting the font size and adding `white-space: normal` to make list buttons behave differently than regular buttons. Can you open a separate issue about the text truncation?

**Comment by hanthomas** [comment]
@marcysutton - Thanks for the fix.  As you suggest, I will make a separate issue about text truncation.
