### ISSUE TITLE
My app unit tests 20x times slower when upgrading to 0.9.0-rc1 

### ISSUE THREAD

**Issue by demisx** [angular/material#2439]
I am running my app unit test in karma `0.12.31` and phantomJS `1.9.16`. I am seeing a weird issue when upgrading to the latest ng material `0.9.0-rc1`: my app unit tests drastically slow down and some tests even start timing out after 2 seconds due to the `done` callback not being called. What used to take 3 seconds to execute all app unit tests under `0.8.3`, now it takes 60 seconds to execute less than 50% of the tests with `0.9.0-rc1`. Rolling back angular material to `0.8.3` brings everything back to normal. Please let me know if you guys have any idea what may be going on.

**Comment by ThomasBurleson** [comment]
@demisx - Have you run `npm cache clean; npm update` ?
Afterwards, what versions of node, npm, karma, and gulp are you using?

**Comment by demisx** [comment]
@ThomasBurleson Please see below. I just wanted to clarify, that I am seeing this behavior with my app own unit tests, not the ng material project unit tests.

> Have you run npm cache clean; npm update?

Yes. I've also tried checking out the branch clean on another laptop. Same issue

> Afterwards, what versions of node, npm, karma, and gulp are you using?
Also please check your /node_modules/angular and determine which version of Angular has been installed.

node = 0.12.2
karma = 0.12.31
gulp = v4
angular = 1.4.0-rc1

**Comment by cognitronic** [comment]
I'm experiencing the same issue

**Comment by ThomasBurleson** [comment]
@demisx - Where did you find Angular **1.4.0-rc1**; that does not exist.

**Comment by demisx** [comment]
@ThomasBurleson  I have my sources. :) Sorry, I meant `1.4.0-rc0`, of course. I'll update the comment.

**Comment by demisx** [comment]
@demisx Regarding gulp, v4 has been in alpha for a while now and runs fine. The gulp tasking kicking off tests is pretty standard, though:

```js
gulp.task('unit', function () {
  karma.start({
    configFile: __dirname + '/specs/unit/karma.config.js',
    singleRun: true
  });
});
```

**Comment by nsdcss** [comment]
Same problem here. To make it clear: my own unit test are not running any more (timeout on phantomJS) or are incredibly slow (chrome) with the 0.9.x release.

**Comment by ThomasBurleson** [comment]
@all - This will be investigated today.

**Comment by demisx** [comment]
If you guys can't replicate the issue, I can show it on my desktop via online meeting or something. I think creating a plunker maybe somewhat challenging here.

**Comment by tutufranca** [comment]
Same issue here on our app after upgrading to 0.9.0-rc3

**Comment by ThomasBurleson** [comment]
@demisx - I think a Hangout would be the best venue to pair-investigate this issue; as we are not seeing this issue with our core team development. Can you email me.

**Comment by demisx** [comment]
@ThomasBurleson Hi Thomas. I've sent you the email a couple of days ago. Just wanted to make sure you got it. It was sent to gmail shown on your GH profile page.

**Comment by ThomasBurleson** [comment]
Hey Dmitri,
Yes, I did receive your email(s). The team and I have been very busy trying
to get the final release of 0.9.0 resolved and published. Can you and I
have a hangout next Tuesday afternoon (CST)? What GST/Timezone are you in?

I look forward to our hangout and [hopefully] resolve this testing issue.
Thanks again.

Thomas

**Comment by demetriusnunes** [comment]
Same issue here.

**Comment by gngeorgiev** [comment]
Why don't you guys just load the tests in chrome and inspect what is causing these slowdowns?

**Comment by jaredcacurak** [comment]
I'm seeing the same problem after upgrading angular-material to v0.9.0

node v0.12.2
angular v1.3.15
angular-material v0.9.0
gulp v3.8.11
karma v0.12.32
jasmine-core v2.3.0
karma-jasmine v0.3.5
karma-phantomjs-launcher v0.1.4

**Comment by toboid** [comment]
Me too, the time taken to run my tests on phantomjs has increased by about 20 times. phantomjs memory usage increases progressively throughout the test run, as does the time taken for each test to complete.

Running my tests against Chrome is taking approximately twice as long as it was with angular-material 0.8.3.

Angular 1.3.15
PhatomJS: 1.9.16
Karma: 0.12.31
Node: 0.10.35

**Comment by gngeorgiev** [comment]
And still no metrics guys? Use the `Timeline` tab or the profiler in developer tools to see what is taking so long. Just saying that it is slow does not help the ng-material team much.

**Comment by ThomasBurleson** [comment]
@everyone - We are aware of this issue which originates [in part] from Theming changes and mocks. We plan to have a fix for this within the next 1-2 days.

**Comment by AdamMcCormick** [comment]
Don't know if it's helpful, but running with a progress indicator, karma tests get slower linearly on PhantomJS, but not on Chrome or Firefox. PhantomJS also doesn't have the garbage collection spikes that the other browser versions have. This would suggest, to me at least, that there's a memory leak at fault. No worries if you already know this.
![md 0 9 slow](https://cloud.githubusercontent.com/assets/3970813/7530728/90d49b94-f502-11e4-878e-5b08322dd227.png)

**Comment by ThomasBurleson** [comment]
The most significant perpetrators to the performance degradation (or karma timeouts) was:

*  Dynamic generation and injection of Material Theme CSS rules.
*  Improper configuration of mocks
*  Unsupported use of `Function.bind()` in PhantomJS

Today's commit should [fix all testing performance issues](https://github.com/angular/material/commit/786b0ed3652b7460c2c802efa1aa79972bd96f5d):   Each browser test set is now completing within < 3secs.

> Please read [Testing with Angular Material](https://github.com/angular/bower-material/#jasmine-testing-with-angular-material) for additional information.

**Comment by demisx** [comment]
I can confirm that this issue is gone on my end using latest master (v0.9.0-master-a179ce8) and PhantomJS. Even better -- my unit tests are 25% faster now! That was worth the wait. Thank you @ThomasBurleson and the material team for the excellent patch.

**Comment by ThomasBurleson** [comment]
@demisx needs a 'shout-out' also... his help offline to research was fundamental to better understanding the issues. Thank you.
