### ISSUE TITLE
md-button: adding ng-href/ui-sref to md-button icon makes the icon placement higher

### ISSUE THREAD

**Issue by junereycasuga** [angular/material#2440]
I'm trying to use md-button with icons to navigate through pages. I tried using both ng-href and ui-sref to give link to it, but by doing that, it makes the position of the icon higher than expected

Example code:
```
<md-button class="md-icon-button" ui-sref="profile">
    <ng-md-icon icon="profile"></ng-md-icon>
</md-button>
```

Best regards

**Comment by marcysutton** [comment]
Hi @junereycasuga, can you provide a Codepen or Plunker showing your code running? What is `ng-md-icon`?

**Comment by uriva** [comment]
+1
Plunker: http://plnkr.co/edit/ea0fjAZoODuJK905MDC6?p=preview

**Comment by ThomasBurleson** [comment]
@uriva - I am confused with your Plunkr. There is no `md-icon` in use.

**Comment by uriva** [comment]
The text is raised in my example, similarly to the icon. I thought these two examples might be the same issue.

**Comment by trevor-sonic** [comment]
I have the same issue;
I changed Angular Seed startup application view1 link  with md-button.
If I remove  href="#/view1" inside md-button; button is lined well, after adding the href (or ng-href) Button rising about 10px

EX: 
    <ul class="menu">
        <li><md-button href="#/view1">TAB1</md-button></li>
        <li><a href="#/view2">view2</a></li>
    </ul>

**Comment by anderskristian** [comment]
I have the same problem.
I have made a class and add 

padding-top: 8px;

Then It works. But it would be nicer to have it "solved" inside the framework.

**Comment by robertmesserle** [comment]
Agreed, this will definitely be solved inside the framework.

**Comment by cadilhac** [comment]
I'm linking to 1.0 rc4 and I still see this issue.

**Comment by mlenser** [comment]
Still seeing the issue with ui-sref on 1.0 rc7

**Comment by nurp** [comment]
With v1.0-rc7, my icons in md-button are misaligned regardless a href, ng-href, ui-sref or without anchor. same, when I use ng-md-icon or md-icon or <i> tag

```javascript
<md-list>
      <md-list-item ng-repeat="item in admin.tabs track by $index">
          <md-button>
            <i class="material-icons">{{item.icon}}</i>
            {{item.title}}
          </md-button>
        </md-item-content>
    </md-item>
</md-list>
```

**Comment by johannesjo** [comment]
Yap doesn't work with 1.0.2 neither.

**Comment by james89** [comment]
+1

**Comment by MarkTroutfetter** [comment]
+1

**Comment by martineckardt** [comment]
+1

**Comment by mikila85** [comment]
+1

**Comment by Matt-Dionis** [comment]
+1

**Comment by AndrewSamokhvalov** [comment]
+1

**Comment by smbowler** [comment]
+1 any update?

**Comment by lgrousset** [comment]
+1

**Comment by jalsamn** [comment]
+1

**Comment by ThomasBurleson** [comment]
@DevVersion - reopening as this appears to be broken.

**Comment by Schlesiger** [comment]
+1

**Comment by ssamakar** [comment]
+1

**Comment by xxmicloxx** [comment]
+1

**Comment by salahaldin** [comment]
+1

**Comment by anymos** [comment]
+1

**Comment by gizmochief7** [comment]
+1
