### ISSUE TITLE
md-subheader overlaps cards when there are lots of md-card objects 

### ISSUE THREAD

**Issue by hanthomas** [angular/material#2441]
The following plunkr demonstrates the problem:  http://plnkr.co/edit/EUAOLNfrlaoZHnIRCaQ7?p=preview

The pattern seems to be that the longer the list, the more the subheader height shrinks.

**Comment by matthewrfindley** [comment]
@hanthomas  This appears to be an issue when combining ```flex layout="column"``` and ```md-subheader```.  Until the problem is identified and fixed, a workaround would be to wrap the elements contained inside the md-content with a div.

```
<md-content flex layout="column">
  <div>
    <md-subheader>...</md-subheader>
    <div layout="row" layout-wrap>...</div>
  </div>
</md-content>
```

**Comment by matthewrfindley** [comment]
@hanthomas Subheaders are implemented using absolute positioning.  In your example you are trying to use an absolute positioned element as a direct child of a flex element.  The proposed solution can be found here (http://www.w3.org/Style/CSS/Tracker/issues/138), which is the same solution proposed above.

The subheader and additional content needs to be wrapped with a div.  I don't believe making subheader modify surrounding elements is going to be very maintainable.  I would suggest following the proposed solution in this case.

**Comment by ThomasBurleson** [comment]
See solution by @matthewrfindley.
