### ISSUE TITLE
mdAutoComplete: add option to to auto-oepn dropdown during focus on empty search input

### ISSUE THREAD

**Issue by ginader** [angular/material#2442]
open Select Box
---
![screen shot 2015-04-20 at 8 31 05 pm](https://cloud.githubusercontent.com/assets/2269/7245219/2a10572c-e79c-11e4-8da5-65c1a214ee5b.png)

type in searchbox to filter or scroll through all options
---
![screen shot 2015-04-20 at 8 30 54 pm](https://cloud.githubusercontent.com/assets/2269/7245218/2a0ff584-e79c-11e4-9468-ad700b468836.png)

The correct behavior is shown here:
http://plnkr.co/edit/uHFSq9G9WA54adWAEupf?p=preview

**Comment by ThomasBurleson** [comment]
So this is essentially an mdAutoComplete with an additional feature to "auto open on focus":

![screen shot 2015-04-21 at 11 37 23 am](https://cloud.githubusercontent.com/assets/210413/7257367/ceb29e9c-e81a-11e4-9904-168084ee7f38.png)

I think we can add a `md-auto-open` attribute and then developers can easily style for other visual aspects.

**Comment by ginader** [comment]
:+1:

**Comment by Panchitoboy** [comment]
is there a problem if you use md-min-length= 0?

**Comment by robertmesserle** [comment]
@Panchitoboy @ginader @ThomasBurleson  This **should** have worked with `md-min-length="0"`; however, there was a very minor bug that prevented it from working properly.  I committed a fix for this just now.

**Comment by ginader** [comment]
that's great! thanks a lot @robertmesserle @ThomasBurleson and @Panchitoboy :-)

**Comment by ThomasBurleson** [comment]
Fixed with SHA da0a4f06c54248c6d73eba7767cdf06bc0225f57; see [Basic Usage Demo](https://material.angularjs.org/#/demo/material.components.autocomplete)
