### ISSUE TITLE
Unsupported URL Type with NPM install

### ISSUE THREAD

**Issue by jgoux** [angular/material#2444]
Hello,
I can't install angular-material with NPM anymore.
I've got these errors : 
```
Unsupported URL Type: github:angular/bower-angular-animate@^1.3.15
```

It seems that the package.json in bower-material is invalid : https://github.com/angular/bower-material/blob/master/package.json#L24

I think this commit introduced the bug : https://github.com/angular/bower-material/commit/9fcc01aa19e942bb5b81ab6b6f4129d9436cd842

**Comment by ThomasBurleson** [comment]
@jgoux  - Recent changes to `package.json` were made to better support JSPM installs without package overrides. I will revert those for now while I consult with the JSPM team.

To install from master:

```console
> npm install angular/bower-material --save-dev

angular-aria@1.3.15 node_modules/angular-aria
angular-animate@1.3.15 node_modules/angular-animate
angular@1.3.15 node_modules/angular
angular-material@0.9.0-rc1-master-55fa76a node_modules/angular-material

> node --version; npm --version; 

v0.12.2
2.7.4
``` 

```console

```

**Comment by ThomasBurleson** [comment]
Can you confirm this works for you now?

**Comment by jgoux** [comment]
Hello Thomas, it works partially. You removed the `|| >1.4.0-beta.0` so I'm unable to use this version anymore. :P

**Comment by ThomasBurleson** [comment]
@jgoux - thx for review and alert. I have updated [package.json](https://github.com/angular/bower-material/commit/37a4d1d11d049a5ece32d97a00671625f7d3e177#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) with the corrections.
