### ISSUE TITLE
Demos > Sticky Subheader has right gap

### ISSUE THREAD

**Issue by amay0048** [angular/material#2445]
![screen shot 2015-04-21 at 4 49 42 pm](https://cloud.githubusercontent.com/assets/6089717/7246909/b33ef63e-e846-11e4-8a2e-f6983f1cbdd0.png)

This is how it currently displays for me in Chrome on OSX Yosemite

**Comment by elrabelo** [comment]
I think this was corrected here: https://github.com/angular/material/issues/708, but it wasn't merged, I suppose. @krassx https://github.com/angular/material/issues/2056 made the same comment.

**Comment by amay0048** [comment]
I don't think #708 is a fix. This wasn't an issue in ~0.8 but has popped up again very recently.

**Comment by ThomasBurleson** [comment]
Gap only occurs when scrolling.
