### ISSUE TITLE
Drag and drop support?

### ISSUE THREAD

**Issue by ashleydavis** [angular/material#2446]
Is there a plan to implement drag and drop reorder for grids and lists? 

Is there a plan to implement drag and drop from one list/grid to another?

**Comment by ThomasBurleson** [comment]
@ashleydavis Drag 'n Drop features will be expored post 1.0.

**Comment by mikehaas763** [comment]
:+1:

**Comment by epelc** [comment]
+1 this would be really cool

**Comment by leon0517** [comment]
+1

**Comment by kamarouski** [comment]
+1

**Comment by dmackerman** [comment]
There are a slew of other plugins out there that make this pretty easy. We've used https://github.com/kamilkp/angular-sortable-view in many applications with list type drag/re-orders.

**Comment by mikehaas763** [comment]
@dmackerman that's pretty cool I haven't seen that plugin yet. I'm fairly certain it's not quite the functionality that we're talking about though. That's basically just a list that can be floated to one side. What we're looking for I believe is more like http://troolee.github.io/gridstack.js/

**Comment by epelc** [comment]
@mikehaas763 Did you look at the [grid with handles demo](http://kamilkp.github.io/angular-sortable-view/#?tab=3)? That plus the placeholder demo might work.

Also cool link @dmackerman

**Comment by mikehaas763** [comment]
@epelc Yep. That's what I meant by "...just a list that can be floated to one side". I'm sure it would work for many cases but not sure it's really what most people have in mind. Could be wrong. I :+1:'d this issue because it would be really nice to have the material grid be a draggable component grid but I also don't think that the functionality should be coupled to the grid. It would be better as a separate directive(s).

**Comment by epelc** [comment]
@mikehaas763 I get what you mean. It wouldn't work with elements being different dimensions.

**Comment by amergin** [comment]
@mikehaas763: Have you looked at [angular-gridster](https://github.com/ManifestWebDesign/angular-gridster)?

**Comment by mikehaas763** [comment]
Yep I looked at that one too and actually am using it in a project until I
can get something with better browser support going

**Comment by epelc** [comment]
I just looked at angular-gridster and it seems really buggy in ie11. Resizing and dragging is hit or miss.

**Comment by hulyav** [comment]
I love the grid-list but without drag/drop support - we cannot use it :(

**Comment by adaojunior** [comment]
@hulyav why dont you implement your own drag/drop?

**Comment by ThomasBurleson** [comment]
Take a look at https://github.com/bevacqua/dragula...
Drag-n-Drop (with persistence) is definitely a wishlist feature for Dialogs (#1206); but that effort will not start before the v1.0 release.

**Comment by rudzikdawid** [comment]
angular-gridster is based on a gridster.net, that is no longer supported
http://hootsuite.github.io/grid/

Resizing will be another fantastic features

**Comment by ismarslomic** [comment]
+1

**Comment by alexzaporozhets** [comment]
+1

**Comment by trinet-jieli** [comment]
+1

**Comment by kumaro** [comment]
+1

**Comment by timmyrosen** [comment]
+1

**Comment by TeemoWan** [comment]
+1

**Comment by pijyster** [comment]
+1

**Comment by peio72** [comment]
Did someone finally manage to create a sortable gridlist ? Which framework ? I'm trying with several but having issues with placeholders because of the absolute positionning of the grid-tiles. Thanx for a help if possible.

**Comment by impavidum** [comment]
For anyone still look for drag and drop this is the best I have found: https://github.com/marceljuenemann/angular-drag-and-drop-lists

**Comment by peio72** [comment]
Is it working with angular material grid list component ?

**Comment by TobiasVdb** [comment]
+1

**Comment by heyanctil** [comment]
@dmackerman thanks it works fine with [https://github.com/kamilkp/angular-sortable-view](url).
