### ISSUE TITLE
md-dialog's buttons should use accent color

### ISSUE THREAD

**Issue by agustinus-kristiadi** [angular/material#2448]
Considering the spec: http://www.google.com/design/spec/components/dialogs.html#dialogs-content,
md-dialog should use accent color for all of its buttons.
Currently md-dialog uses primary color for main button, and non-colored button for the secondary (cancel) button

![screenshot from 2015-04-21 17 04 03](https://cloud.githubusercontent.com/assets/4121870/7249957/6edcc69a-e848-11e4-99d1-d55a29eb58fc.png)

**Comment by matthieusieben** [comment]
You closed the issue but you set the class on the buttons to `md-primary` instead of `md-accent`.

**Comment by marcysutton** [comment]
@matthieusieben the CSS has probably changed since then, but I don't work on this project anymore.

**Comment by matthieusieben** [comment]
Nope, still `md-primary` on both buttons.
