### ISSUE TITLE
md-tabs not center corret

### ISSUE THREAD

**Issue by gimox** [angular/material#2450]
md-tabs not center correct if  md-center-tabs="true" and change browser windows size.

**Comment by gimox** [comment]
thanks!

**Comment by gimox** [comment]
more precise...

it happend when:

- it's present ng-show in md-tabs directive
- you have a many tabs (it must scroll)
- resize page at minimun width size
- reload the page.

if you resize page it work correctly.

**Comment by robertmesserle** [comment]
This should be resolved - please confirm.  Closing for now, will re-open if issue still exists.

**Comment by gimox** [comment]
ok thanks i try it..
