### ISSUE TITLE
How can I download updated source for client side?

### ISSUE THREAD

**Issue by xavikortes** [angular/material#2451]
Hi, first of all congratulations for your job, you are developing a great library.

I'm using the library in client Javascript, I want to get the most updated version but I'm not familiarized with Server side Javascript. There is any way to do it without npm o bower? Nowadays I'm getting from the demo page but I think it isn't updated.

Thank you for your response.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
