### ISSUE TITLE
mdInput: bug by adding label and icon?

### ISSUE THREAD

**Issue by xavikortes** [angular/material#2452]
Is impossible to add into a md-input-container an icon and a float label at the same time?
Google specification permit it?
Data superpose the icon at this moment.

Thanks for your response.

**Comment by ThomasBurleson** [comment]
See https://material.angularjs.org/#/demo/material.components.input

![screen shot 2015-04-21 at 7 08 47 am](https://cloud.githubusercontent.com/assets/210413/7251915/4f05c860-e7f5-11e4-9740-9f276a0db738.png)

**Comment by xavikortes** [comment]
None of them has a floating label. Not a good example.
And the placeholder is hidden by default. I need to know in every moment what fields are placed, not only when they are focused.

**Comment by ThomasBurleson** [comment]
@xavikortes - Now I see what the this issue identifies:

![screen shot 2015-04-21 at 8 40 54 am](https://cloud.githubusercontent.com/assets/210413/7253445/60afc6bc-e802-11e4-92ab-5623065c065c.png)


>  For future issues, if you submit a picture/snapshot or CodePen with the issue, that will help with our understanding. To quote Fred Barnard:  "A picture is worth a thousand words..."

**Comment by forcewill** [comment]
Sry in advance i don't know if i should open a new issue or comment on this.
2dbe6a9 does seem to fix this issue but if you notice carefully in the demo for input with a label and icon,
https://material.angularjs.org/#/demo/material.components.input (the name input) when the input gain focus the container height grows to accommodate the label, that is not consistent with a regular input with a label and no icon

**Comment by xavikortes** [comment]
I think that it needs to be fixed too.

**Comment by ThomasBurleson** [comment]
@xavikortes - open a new bug for milestone 0.10 plz.

**Comment by rochapablo** [comment]
+1
