### ISSUE TITLE
md-list changes height of previous elements in container to ~1px on Chrom/Safari

### ISSUE THREAD

**Issue by johnwebbcole** [angular/material#2453]
Here is a [codepen](http://codepen.io/johnwebbcole/pen/aOoXRL) example.  Notice that the `md-list` element sets the height of the `<div>Foo</div>` elements to a very small number (~1-3px).  On Firefox, this appears as expected.

There doesn't appear to be anyway to prevent the `md-list` from 'crushing' the previous elements.

**Comment by rschmukler** [comment]
That's actually an issue with flexbox (on the parent sidenav with `layout="column"`) shrinking the divs.

[Here](http://codepen.io/anon/pen/wapPVy) is a demo of adding a class that disabled flexbox from being allowed to shrink those items.
