### ISSUE TITLE
md-fab-top-center and md-fab-bottom-center

### ISSUE THREAD

**Issue by soutlink** [angular/material#2455]
Shoud be a .md -fab -top -center and .md -fab -bottom -center class ?

I mean , here (http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior) is a fab button centered at bottom ( like in lollipop dialer )

This behavior its not possible at this moment (I think)

**Comment by mprentic-harris** [comment]
Yes, this would be nice.

**Comment by danieladz** [comment]
yeah, I would like this too

**Comment by barraq** [comment]
:+1:

**Comment by topherfangio** [comment]
The team is focused on getting things ready for v1.0, so this is a little bit low on the priority list.

If anyone is interested in submitting a PR to help us get this out sooner, it would certainly be welcomed :-)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
