### ISSUE TITLE
md-select moves DOM elements and puts them back in the wrong position

### ISSUE THREAD

**Issue by guzza** [angular/material#2456]
When `md-select` gets opened it rearranges the DOM and the layout goes crazy.
The layout of the site is `<body layout="row">` with 2 main children one being `<md-sidenav>` and second being the main `<div layout="column" layout-fill role="main" ui-view="main"></div>` where the Angular injects the view. `md-select` is located inside the `<div ui-view="main"`.

First screenshot is before `md-select` is opened
![screen shot 2015-04-21 at 16 51 44](https://cloud.githubusercontent.com/assets/188076/7255250/540e2ce6-e848-11e4-9c3c-e63ff4e32e5d.png)

This screenshots is while its open
![screen shot 2015-04-21 at 16 52 06](https://cloud.githubusercontent.com/assets/188076/7255132/b0687ff6-e847-11e4-90f3-d1aa79cef482.png)

And finally when `md-select` is closed we can see the action moved the `<div ui-view="main">` to the top effectively moving the `<md-sidenav>` from left to right because of the flex layout ordering.
![screen shot 2015-04-21 at 16 52 18](https://cloud.githubusercontent.com/assets/188076/7255245/4ff60ae8-e848-11e4-9919-50b512b807aa.png)

**Comment by rhnatiuk** [comment]
Is it linked to #2447 ? There is clearly something fishy going with `md-select` in last builds.

**Comment by guzza** [comment]
Issue #2447 is about the delay while opening, this one is more that it moves elements in the main DOM after `md-select` has been opened and then closed and puts them back in the wrong place thereby changing the layout that uses flexbox and in my case `md-sidenav` gets moved to the right side from left.

**Comment by rhnatiuk** [comment]
I understand it. What I meant is that the delay can also be caused by DOM rebuilding back and forth (and also there is displacement of selector text). At least it sounds plausible.

**Comment by daw451-duplicate** [comment]
Having similar issue with #2390.

**Comment by guzza** [comment]
The issue is probably inside `$mdSelect` provider in the functions `.show()` and `.hide()` that is defined [here](https://github.com/angular/material/blob/v0.9.0-rc2/src/components/select/select.js#L672). Specifically I see that when `$mdSelect.show()` is called the `parent` property is not passed in and later on in `$mdSelect` the parent is set by default to `<body>`. After that it is used as `opts.parent` in multiple places but my insight of the code is not good enough and I don't have time to get more into it to find where exactly it goes haywire.

**Comment by rschmukler** [comment]
@guzza can you provide a code pen demoing this? I tried re-creating it and it doesn't appear to still be happening. Is it resolved now? If not, could you provide some browser/OS details so I can explore further?

**Comment by fredrikbonander** [comment]
I have a similar problem with this. I have a Google Map with markers that drops in on render. 

So when md-select moves content the Google Map runs all the animations again. Could we have a option for not have a backdrop for the select list?

**Comment by gustavohenke** [comment]
:+1: for this issue.
I noted that the `<!-- uiView: ... -->` comment is the responsible for moving stuff into the wrong places, as it's the only thing that's not wrapper when the select is opened.

**Comment by gustavohenke** [comment]
Submitted a PR to fix this: #2571

**Comment by guzza** [comment]
I just pulled the fresh version with @gustavohenke fix and its fine now puts back elements properly.

**Comment by vapits** [comment]
I have exactly the same problem with version 1.0.1 & master also.
