### ISSUE TITLE
md-autocomplete: Prevent browser autofill dialog

### ISSUE THREAD

**Issue by epelc** [angular/material#2457]
It seems in some cases at least in chrome you will see both the material auto complete and the browsers autofill.

![image](https://cloud.githubusercontent.com/assets/5204642/7256340/80e3dc60-e81c-11e4-8363-efb27564b32a.png)

This [SO question](http://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tag) has some nice suggestions. Also chrome seemed to be showing it because my label contained `address`.

Chrome 42.0.2311.90 m windows 10 preview 64bit with angular-material 0.9.0-rc2

**Comment by robertmesserle** [comment]
Sadly, there is no real way to disable this for certain autofill fields (ie. address).

Depending on your use-case, one hack that should work would be to wrap your field in a form tag.  From what I gathered from the Chrome team, this will only happen if there are 2 or more address-related fields in the same form.

**Comment by epelc** [comment]
@robertmesserle thanks for the info

**Comment by simkessy** [comment]
Can you give an example for the fix? I'm getting the same issue

**Comment by vishwajeetv** [comment]
@robertmesserle : If you remove `md-input-name` attribute from `<md-autocomplete>` , chrome will not try to autofill the auto-complete input.
