### ISSUE TITLE
md-chips md-autocomplete error

### ISSUE THREAD

**Issue by Panchitoboy** [angular/material#2458]
In the demo page, every time that you make a change in the md-autocomplete example in the md-chips section, you get this error:

Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.15/$rootScope/inprog?p0=%24apply
    at angular.js:63
    at beginPhase (angular.js:14820)
    at Scope.$apply (angular.js:14564)
    at e.<anonymous> (docs.js:4)
    at HTMLInputElement.eventHandler (angular.js:3032)
    at e.R.mouseUp (docs.js:4)
    at $parseFunctionCall (angular.js:12404)
    at callback (angular.js:21566)
    at Scope.$eval (angular.js:14466)
    at Scope.$apply (angular.js:14565)

Tested with Chrome

**Comment by karin-n** [comment]
This happens in Firefox as well - here is the actual cause in case it helps: MdAutocompleteCtrl/self.mouseUp@http://localhost:3000/jspm_packages/github/angular/bower-material@0.9.0-rc2/angular-material.js:11153:36

**Comment by Alexandre-io** [comment]
Same issue with the Contact Chips demo:

https://material.angularjs.org/#/demo/material.components.chips

**Comment by stewones** [comment]
+1

**Comment by tmack8001** [comment]
Would this error make it so that the changed data array won't be successfully bound to its ngModel? I'm seeing that behavior in my application while testing against 0.9.0-RC2 and the mdContactChips directive.

**Comment by scarletsky** [comment]
+1
In my case, it happens when you click on the suggestion list item with mouse, not keyboard.

**Comment by tmack8001** [comment]
The error I mentioned above I still need to piece together a barebones example to show this as there could be a bug in my minimal set of JavaScript when setting this up.

**Comment by chrisguerrero** [comment]
+1

I'm seeing the `Error: [$rootScope:inprog] $apply already in progress` as well

**Comment by ThomasBurleson** [comment]
To be fixed with Pull Request #2591
