### ISSUE TITLE
WebVeiw draw/redraw problem with 4.4.2 Android

### ISSUE THREAD

**Issue by Ichka** [angular/material#2459]
I have the following problems the with draw/redraw using webview on Andorid 4.4.2:
- case 1: The view is loaded and there are two buttons on it. The both are displayed correctly. When refresh of the view is performed the second button exists but with no color and no text.
- case 2: When the view is loaded checkbox stays invisible, until any tap.
- case 3: again view with two buttons. On the loading the second button has no color or text, until tap.

I do some hacks like adding style="-webkit-transform: translate3d(0,0,0);" and for the first case it succeeded, but with no results with the rest of the cases.

These problems doesn't exist on Android 4.4.4

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.
