### ISSUE TITLE
md-tab ignores ng-show completely

### ISSUE THREAD

**Issue by jamm** [angular/material#2465]
I don't know how you did it, but currently ng-show/ng-hide are ignored by md-tabs. At least ng-if works, last resort.

**Comment by jamm** [comment]
still 100% reproducable

**Comment by jamm** [comment]
have no time to create full plunker, sorry, but code is dead-simple:
```
<md-tab ng-if="!Session.email" label="Login" md-on-select="cNav.go('login')"></md-tab>
```
it's from working project.

**Comment by robertmesserle** [comment]
This is a known case. I believe you would want to use ng-if for now.

**Comment by robertmesserle** [comment]
This is a duplicate, closing.

**Comment by jamm** [comment]
lol, that issue was created later and about another problem (even bunch of them) and ng-show there is just side-effect. But ok, I understand the reason :)

**Comment by robertmesserle** [comment]
Yea, there were actually 4 issues for this.  I just left one open to make sure it doesn't fall through the cracks. =p

**Comment by kart1618** [comment]
Thanks e-oz. I ended up using ng-if as well.
