### ISSUE TITLE
Please don't forget to write about breaking changes

### ISSUE THREAD

**Issue by jamm** [angular/material#2466]
Commit b0c9f9f19fc6fdfa7c585e1a7431f6f2ce5d1573:
![screenshot 2015-04-21 21 32 04](https://cloud.githubusercontent.com/assets/526352/7259717/fceed606-e86d-11e4-8441-8589b4472a1b.png)

Commit 77c9cc37f6ddc56df4ea94600fb39ed7abc68131:
![screenshot 2015-04-21 21 34 15](https://cloud.githubusercontent.com/assets/526352/7259746/32fc50a2-e86e-11e4-97a1-1637fa4047c4.png)

Markup was made with md-list, md-content, md-item.
But 0 breaking changes, related to md-list or md-item between these commits... So what has been changed? Will take a shovel and dig, step by step, to find it...

**Comment by demisx** [comment]
+1. Looks like there will need to do a major rework after upgrading to 0.9. All my UI gets messed up when upgrading to 0.9.0-rc1.

**Comment by ThomasBurleson** [comment]
@demis - what **specifically** has broken in your UI?
@jamm - Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by jamm** [comment]
@ThomasBurleson I already wasted 2 hours on rework and work is still in progress - trying to figure out wtf is wrong with layout=row and flex inside, so I'm not sure I'm motivated to spend some time to build plunkr. It's not a bug, so you don't really need plunker (there is nothing to reproduce and fix) and I don't understand why you asked for it. Maybe to waste little bit more of my time. I understand you need breaking changes, I just ask you to document them - it helps to save time significantly.

**Comment by demisx** [comment]
@ThomasBurleson Like everything where ng-material is currently used - tabs, lists, margins, paddings, alignment etc. It was my understanding that 0.9.0-rc1 refactored existing and maybe introduced new directives, new styles and we'd need to sync up when upgrading. I've never had this much of an issue upgrading before (prior to 0.8.3) - the adjustments would usually be minimum. However, I understand none of these releases are stable yet, so I am sort of was ready for something like that. I can take some screenshots before and after, but not sure if they'd have any value to you. Let me know.

**Comment by jamm** [comment]
to help you:  
* `md-item` renamed to `md-list-item`  
* `md-item-content` element converted into `.md-list-item-text` class  
* h1-h4 changed significantly
* flex without value + flex with value gives different size, than 2 elements where flex has value (flex+flex65 != flex35+flex65)

**Comment by kyleledbetter** [comment]
I can also attest to the pain in the fairly significant rebuild of md-list in 0.9 from 0.8.3

Everything @jamm just listed, along with the .md-no-proxy and .md-no-style stuff that's needed for the proper padding in md-list-item.

Some of these things need to be demystified like how/when those classes get added.

**Comment by axelson** [comment]
Thanks for that list @jamm. Those look like some very important breaking changes.

**Comment by marcysutton** [comment]
List controls were noted as breaking changes: 77ed2f57c27bd316e2816692782b68d9d47eed47

**Comment by jamm** [comment]
They weren't noted in list of breaking changes in CHANGELOG.md

**Comment by ThomasBurleson** [comment]
@all - Community involvement and feedback is critical to a great product. And these items mentioned are very helpful. This is great feedback and the core team appreciates everyone's help. These will be added to the changelog.

**Comment by ThomasBurleson** [comment]
This thread also prompts me to post a notice about our published [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md). 

The Angular Material team is working very hard to publish an open-source framework. Our requests for demos or samples are **never** intended to waste time. Sometimes we do not understand or mis-interpret the posted issue... to err is human. Thank you.

**Comment by kyleledbetter** [comment]
@ThomasBurleson was someone in this thread outside the CoCo? I certainly wasn't trying to offend anyone, I think there were just a few of us that were surprised by the change in md-lists and trying to find a fix

**Comment by ThomasBurleson** [comment]
@kyleledbetter - I removed a comment (in this issue) that was not constructive.

I cannot emphasize that the Angular Team really appreciates everyone's help to use, test, and quality improve Angular Material. Thank you.

> Coming soon [planned for the 0.10.0 Milestone] will be documentation on CSS for each component.

**Comment by kyleledbetter** [comment]
ah cool gotcha, well fwiw my team appreciates every line of code you guys are committing (and changes are expected) :)

**Comment by demisx** [comment]
@ThomasBurleson Your team's hard work is greatly appreciated. The amount of progress made since not such a long time ago ngMaterial first introduction is amazing and unbelievable at the same time. 

@all Everyone hang in there. Things will get smoother in the future as the code base gets stabilized. In the meantime, we need to make sure that we make the material team's job is as simple as possible while troubleshooting project issues. And if demos, plunkers, whatever are requested, then there is a good reason for it.

**Comment by jamm** [comment]
Why didn't you ask me to delete or edit my comment? You even left unedited your own comment with "error". I don't accept any set of rules which leads to silent censorship, so feel free to wipe out all my issues and comments completely.
World is not only about ponies and roses, and I think my criticism was constructive.

**Comment by ThomasBurleson** [comment]
@demisx - Just note that sometimes we may not understand the issue and simply request a Plunkr so we can see the code and issue directly. In some cases, better description of the issue will obviate the need for a Plunkr. But thank you sir.

**Comment by jamm** [comment]
@demisx to provide requested plunkr, I had to fork two commits of repo, build and host files somewhere  (you can have only one fork of repo in github), simplify code of working app, generate sets of test data (to make things render) and all this work just see same result I provided in first message by screenshots. I don't think it's "for a good reason" and we should silently provide everything requested.  
I hate this kind of discussions, but both censorship and your comment makes me mean and angry. I'm sorry it turned this way, but still think my initial intent was legit. Bye.

**Comment by ThomasBurleson** [comment]
I am reopening this issue since we have a Pull Request https://github.com/angular/material/pull/2504 in process

**Comment by Demis** [comment]
Thomas can you remove me from this email thread, you are using the wrong
email address. I think you are trying to reach someone else.
thanks

**Comment by demisx** [comment]
@jamm Instead of getting mad, maybe try to explain the difficulties you are facing when creating a particular plunker. I am sure the team will understand. I also have hard time creating plunkers in certain cases and I tell the owners about that. They usually work with me to get the information they need in a different way.  Sometimes I create a copy of my project and give them readonly access to it. After all,  I don't think anyone's goal here is to make your ng-material experience miserable.  I am not trying to say you should only praise this project and suck it up when things go south. Just try communicating your feedback in a slightly positive manner and you'll get much further with it. I am sure you are an awesome coder and a great person, so please take it the right way.

**Comment by ThomasBurleson** [comment]
Re the question:

*  flex without value + flex with value gives different size, than 2 elements where flex has value (flex+flex65 != flex35+flex65)

@rschmukler tested with https://jsfiddle.net/rschmukler/6exo552a/ does not show any issue.

**Comment by jamm** [comment]
I'll create separate issue for this bug (with code sample). Reproducible
with today's commits.
