### ISSUE TITLE
md-select: Up/down arrows don't work in dialog

### ISSUE THREAD

**Issue by epelc** [angular/material#2467]
If you open an `md-select` in a dialog the up down arrows do not work even after you manually click on an element to force focus on the select.

**Comment by red010b37** [comment]
same issue as - https://github.com/angular/material/issues/2443

**Comment by epelc** [comment]
I'll close this then. I didn't see that. @red010b37 they are called dialogs instead of modal in angular material though. It might be easier to search if you rename your issue.
