### ISSUE TITLE
Material-card too wide for usage in flex grid system

### ISSUE THREAD

**Issue by Frank3K** [angular/material#247]
I would expect that three `<material-card flex=33>`'s could be stacked horizontally in a `<material-content layout="horizontal">`-container. Unfortunately this makes the page too wide (i.e. wider than the window width). 

As far as I can see this is the result of the rule `margin: $card-margin;` for `material-card` (in [_card.scss](material/src/components/card/_card.scss)), where `$card-margin` is currently `10px` (in [_variables.scss](src/theme/_variables.scss )). Setting the `margin` to `0` is no option layout-wise; the card is hardly recognizable then.

Example plunkr: http://plnkr.co/edit/vHckwcMApTIcRev5KF9e

**Comment by Frank3K** [comment]
@ajoslin: This isssue was reintroduced in a2bc3c68551b4915c40a4eca9ec48fa9ec61f6b7. Should I open a new issue for that (since I can not re-open this one). [Updated plunkr](http://plnkr.co/edit/oQnom333gije5bmqPyWs?p=preview).

**Comment by marcysutton** [comment]
`md-card` needs to maintain margins no matter how many items there are or what it is inside of. To solve the issue of cards being too wide, you can wrap them in another element with `flex`. Like this:

```html
<div flex=33>
      <md-card>
        <img class="md-card-image" src="http://placehold.it/350x150" />
        <md-card-content>
          <span>Card 1</span>
        </md-card-content>
      </md-card>
    </div>
```
Here is an updated Plunker updated to use the latest markup: http://plnkr.co/edit/nE7kMhFoObJdQyEdFSjF?p=preview

**Comment by mavillar** [comment]
@marcysutton running your script, the result is md-card is 100% width, not 33%

**Comment by marcysutton** [comment]
The API may have changed. If there is still a problem with it, please open a new issue. (Also note: I no longer work full-time on Angular Material)
