### ISSUE TITLE
Multi-select component could have some improvements.

### ISSUE THREAD

**Issue by cabbageleafhead** [angular/material#2473]
It seems like the mutli select component doesn't have any visual cues that indicates that users can select multiple items. The only difference between the select and multiple select is that one stays open until you click outside (the multiple one).

Any chance this component can add a visual cue? for it? Perhaps add check boxes or something before each item.

http://www.google.com/design/spec/components/menus.html#menus-menu-items
http://www.google.com/design/spec/components/lists-controls.html#lists-controls-types-of-list-controls

**Comment by rschmukler** [comment]
@ThomasBurleson could perhaps check with the UX team on this?

**Comment by ThomasBurleson** [comment]
Fixed. See [Demo List Controls](https://material.angularjs.org/#/demo/material.components.list)

**Comment by cabbageleafhead** [comment]
Sorry if it was not clear. I was specifically talking about the <md-select> directive with the multiple attribute.

It needs a visual cue that it is a multi select.

**Comment by cabbageleafhead** [comment]
@ThomasBurleson, @rschmukler

This issue should not be closed AFAICT. Please address the actual issue with the mdSelect multiple directive.
