### ISSUE TITLE
mdInput: placeholder bug in firefox

### ISSUE THREAD

**Issue by xavikortes** [angular/material#2480]
Input placeholder is working only when it is focused in firefox.
Examples from official demos

This is in Chrome
![chrome](https://cloud.githubusercontent.com/assets/9928629/7268760/fd797cd4-e8cc-11e4-919d-0015396051d0.png)

And this in FF
![ff](https://cloud.githubusercontent.com/assets/9928629/7268776/19fe659a-e8cd-11e4-9ea2-f3338c5fc33d.png)

**Comment by Splaktar** [comment]
@xavikortes Is this a duplicate of #2162?
