### ISSUE TITLE
mdSelect: "Failed to execute 'removeChild' on 'Node'" when moving to new route.

### ISSUE THREAD

**Issue by michaelbromley** [angular/material#2481]
When there is an mdSelect, and one of the options triggers a route change (i.e. the select is used to navigate to new routes), the following error results:

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

Here is a Plunker demo of the issue: http://plnkr.co/edit/hAcv29c5gusO2SjP3ZF1?p=preview
This example uses ngRoute as the router, but the issue also exists when using ui-router.

The error is caused by [this line](https://github.com/angular/material/blob/v0.8.3/src/components/select/select.js#L722), which is attempting to remove the `md-select-menu-container` div upon selection. However in the case of a route change, the route change happens first, meaning the intended div is no longer there, resulting in the error.

It could potentially be a simple fix involving doing a check for existence before attempting to removeChild. I made the following change to my local copy which seems to have fixed it:

```JavaScript
if (element[0].parentNode === opts.parent[0]) { // added this if statement
   opts.parent[0].removeChild(element[0]); // use browser to avoid $destroy event
}
```

**Comment by sazonenka** [comment]
+1

**Comment by rschmukler** [comment]
Thanks!

**Comment by michaelbromley** [comment]
Boom! Speedy service :+1: I can now consider myself a contributor to Angular Material in spirit at least ;)

**Comment by rschmukler** [comment]
Haha if you'd opened a PR I'd have given you the authorship credit :P Next time. Wasn't sure if you had a CLA signed or I would have done it as well.
