### ISSUE TITLE
NgSwitch Display Wrong When Using True Value 

### ISSUE THREAD

**Issue by jayss** [angular/material#2485]
Hi Team,
The NgSwitch function is awesome, but if I add a true value with ngmodel, it just displays false value initially.
For example:
$scope.test = 1
[ngswitch ng-true-value="1" ng-model="test"]
In this case, the switch just shows the false status.

Is it clear?
Thanks

**Comment by george3447** [comment]
+1

**Comment by topherfangio** [comment]
Cannot reproduce in latest version: http://codepen.io/topherfangio/pen/wKagVP

If you are still experiencing problems, please fork the above Codepen to show the issue and repost it here and we will re-open/investigate.
