### ISSUE TITLE
md-autocomplete gets messed up when in md-input-container

### ISSUE THREAD

**Issue by loykianos** [angular/material#2486]
There is an issue with md-autocomplete when used inside a md-input-container where the placeholder doesn't show and the border is shown inside the autocomplete element as shown bellow.

![before](https://cloud.githubusercontent.com/assets/4227423/7275326/a0f008d4-e903-11e4-9a0c-13474fc740d1.JPG)
with no focus

![after](https://cloud.githubusercontent.com/assets/4227423/7275417/2feb741a-e904-11e4-9317-ccd58f8fab3a.jpg)
with focus

Works as intended if I move it out of the md-input-container.
![afterfixed](https://cloud.githubusercontent.com/assets/4227423/7275466/7b6a6c52-e904-11e4-93d2-00adf37555da.jpg)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue.

**Comment by loykianos** [comment]
@ThomasBurleson http://plnkr.co/edit/dlr39HQ7H3BXD04Kf9vD?p=preview

**Comment by robertmesserle** [comment]
Yea, `md-autocomplete` is not meant to live within `md-input-container` -
the second demo on the demo site shows proper use if you want to include it
within an input container (for floating label).  There is an issue set to
be resolved in 0.10.0 to add full support of other `md-input-container`
features such as validation, which will likely be among the first items
addressed in 0.10.
