### ISSUE TITLE
Suggestion: Use npm shrinkwrap to lock in build dependencies

### ISSUE THREAD

**Issue by epelc** [angular/material#2487]
I'd like to suggest the use of `npm shrinkwrap` as I was burned a few weeks ago by a seemingly harmless `npm update` which broke everything. Luckily I had a copy on my laptop which I didn't run `npm update` on yet. Either way it's very easy to use just make sure you check in the shrinkwrap file.

If your interested the docs can be found here
https://docs.npmjs.com/cli/shrinkwrap

**Comment by ThomasBurleson** [comment]
Will not fix.
