### ISSUE TITLE
Best way to change Tab Height and Animations

### ISSUE THREAD

**Issue by ACDN** [angular/material#2491]
Hey everyone,

The md-tabs is a fantastic directive.  I've got two questions to ask.

I'd like to know what would be the best way to adjust the height of the area where the tab names are displayed.  I've attempted messing around with some CSS but that doesn't seem to be the best solution.

Second, I'd like to know how to disable the slide in / out animation that occurs when the selected tab changes.

ACDN

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by ACDN** [comment]
You got it.
