### ISSUE TITLE
md-select: Breaks window resize event listeners after open

### ISSUE THREAD

**Issue by epelc** [angular/material#2499]
If you have an element that uses something like `$window.on('resize',...)` and you open a select the listener stops receiving resize events. @Tyrannmisu also mentioned having this issue.

@rschmukler I just tested this in master(97d4a73c89) It's also been an issue since `0.9.0-rc1` but I think it got lost in #2379

**Comment by Tyrannmisu** [comment]
Just in case somebody else needs it:
md-select does not break window.events that are done in pure JS, for example :

```JavaScript

window.addEventListener('resize', function(event){
    yourResizeFunction();
});

```

This works, even though it's not the angular way, but at least a workaround until this issue is fixed.

**Comment by epelc** [comment]
@Tyrannmisu Thanks for the workaround. This was breaking my graph resize events.

**Comment by Tyrannmisu** [comment]
@rschmukler works fine now, thanks! :)

**Comment by ThomasBurleson** [comment]
@rschmukler - FTW #woot.
