### ISSUE TITLE
md-select: Hiding/disabling scrollbar causes md-content jitter on open/close

### ISSUE THREAD

**Issue by epelc** [angular/material#2500]
It only seems to happen if the select is within md-content as my select on my toolbar doesn't have this issue however it also doesn't ever have a scrollbar.

![736381d8-e751-11e4-80d9-abc76a307cbe](https://cloud.githubusercontent.com/assets/5204642/7285089/0d34d9c8-e910-11e4-98f3-9f50fad4d6af.png)

@rschmukler This is happening in `0.9.0-rc2` and on your latest commit to master

**Comment by rschmukler** [comment]
@epelc is this still an issue with the latest on master? I can't recreate it. Please let me know what the DOM structure is so I can reproduce.

**Comment by epelc** [comment]
@rschmukler Just checked and it's fixed on master!

**Comment by rschmukler** [comment]
@epelc Fantastic. Thanks for the lighting fast response time.

**Comment by daw451-duplicate** [comment]
@rschmukler hey i am still seeing this in an application build that i am doing and also on the demo site https://material.angularjs.org/#/demo/material.components.select. BUT IT IS VERY WEIRD...

Go into IE11.... scroll down to the option groups such that the drop down in that section appears midway down the vertical scrollbar. When you click it to open you see a slight jitter. If you scroll the page such that the drop down is nearly at the bottom of the page it essentially whites out a portion of the bottom of the section element.

In my application i am seeing about a 1/4 inch shift to the right when i open an md-select.

**Comment by epelc** [comment]
@daw451-duplicate I'm not seeing it on windows 10 with ie11 11.0.10011.0

Are you on windows 8 or 8.1? An update a few days ago trashed ie's flexbox and completely broke layout-fill/flex on my laptop.

**Comment by gerbil** [comment]
I can see this on chrome Version 44.0.2403.155 m
