### ISSUE TITLE
In IE11, md-dialog with flex causes the entire page to shift left until the dialog is closed

### ISSUE THREAD

**Issue by hanthomas** [angular/material#2501]
Here's the plunkr that demonstrates the problem:

http://plnkr.co/edit/6DuZiWl1ZFoZQARitXXP?p=preview

This happens only in IE.  Chrome and Webview on iOS and Android work just fine.  In the meantime, the workaround is to simply use flex="100" instead of just flex.  But, it would be nice to have this fixed.

**Comment by albertosantini** [comment]
Is it the same issue?

With IE 11

![image](https://cloud.githubusercontent.com/assets/328179/7303531/aa0f7924-e9f1-11e4-8d60-729655744c03.png)

With Chrome 42

![image](https://cloud.githubusercontent.com/assets/328179/7303598/1d29bc1c-e9f2-11e4-8a1a-aeeb89a358e7.png)

**Comment by Splaktar** [comment]
I can reproduce this in IE11. It works fine in Edge and Chrome.

**Comment by Splaktar** [comment]
Here's a [description](https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored) of a related bug from [caniuse](http://caniuse.com/#feat=flexbox).

**Comment by Splaktar** [comment]
Here's the current flex CSS for material. I think that many people expect `flex` and `flex-100` to be identical. However, they are not. 

`flex` is `flex: 1` which is `flex: 1 1 0%`.
`flex-100` is `flex: 0 0 100%`.

Note: It's flex: flex-grow flex-shrink flex-basis.

```
.flex {
  box-sizing: border-box;
  -webkit-flex: 1;
      -ms-flex: 1;
          flex: 1; }

.flex-0 {
  -webkit-flex: 0 0 0%;
      -ms-flex: 0 0 0%;
          flex: 0 0 0%; }

.flex-5 {
  -webkit-flex: 0 0 5%;
      -ms-flex: 0 0 5%;
          flex: 0 0 5%; }

.flex-10 {
  -webkit-flex: 0 0 10%;
      -ms-flex: 0 0 10%;
          flex: 0 0 10%; }

.flex-15 {
  -webkit-flex: 0 0 15%;
      -ms-flex: 0 0 15%;
          flex: 0 0 15%; }

.flex-20 {
  -webkit-flex: 0 0 20%;
      -ms-flex: 0 0 20%;
          flex: 0 0 20%; }

.flex-25 {
  -webkit-flex: 0 0 25%;
      -ms-flex: 0 0 25%;
          flex: 0 0 25%; }

.flex-30 {
  -webkit-flex: 0 0 30%;
      -ms-flex: 0 0 30%;
          flex: 0 0 30%; }

.flex-35 {
  -webkit-flex: 0 0 35%;
      -ms-flex: 0 0 35%;
          flex: 0 0 35%; }

.flex-40 {
  -webkit-flex: 0 0 40%;
      -ms-flex: 0 0 40%;
          flex: 0 0 40%; }

.flex-45 {
  -webkit-flex: 0 0 45%;
      -ms-flex: 0 0 45%;
          flex: 0 0 45%; }

.flex-50 {
  -webkit-flex: 0 0 50%;
      -ms-flex: 0 0 50%;
          flex: 0 0 50%; }

.flex-55 {
  -webkit-flex: 0 0 55%;
      -ms-flex: 0 0 55%;
          flex: 0 0 55%; }

.flex-60 {
  -webkit-flex: 0 0 60%;
      -ms-flex: 0 0 60%;
          flex: 0 0 60%; }

.flex-65 {
  -webkit-flex: 0 0 65%;
      -ms-flex: 0 0 65%;
          flex: 0 0 65%; }

.flex-70 {
  -webkit-flex: 0 0 70%;
      -ms-flex: 0 0 70%;
          flex: 0 0 70%; }

.flex-75 {
  -webkit-flex: 0 0 75%;
      -ms-flex: 0 0 75%;
          flex: 0 0 75%; }

.flex-80 {
  -webkit-flex: 0 0 80%;
      -ms-flex: 0 0 80%;
          flex: 0 0 80%; }

.flex-85 {
  -webkit-flex: 0 0 85%;
      -ms-flex: 0 0 85%;
          flex: 0 0 85%; }

.flex-90 {
  -webkit-flex: 0 0 90%;
      -ms-flex: 0 0 90%;
          flex: 0 0 90%; }

.flex-95 {
  -webkit-flex: 0 0 95%;
      -ms-flex: 0 0 95%;
          flex: 0 0 95%; }

.flex-100 {
  -webkit-flex: 0 0 100%;
      -ms-flex: 0 0 100%;
          flex: 0 0 100%; }

.flex-33, .flex-34 {
  -webkit-flex: 0 0 34%;
      -ms-flex: 0 0 34%;
          flex: 0 0 34%; }

.flex-66, .flex-67 {
  -webkit-flex: 0 0 66%;
      -ms-flex: 0 0 66%;
          flex: 0 0 66%; }
```

**Comment by Splaktar** [comment]
@ThomasBurleson I think that most developers expect the `flex` layout attribute to be identical to `flex=“100”`. This is a bit of a UX issue, but are there some pragmatic reasons why these need to be different? 

Should we make them identical (`flex: 0 0 100%`) and then add another attribute, like `flex-grow` for `flex: 1 1 0%`? 

Or should we just update the docs to call out and clarify this specific misconception?

**Comment by ThomasBurleson** [comment]
@Splaktar - The ngMaterial Layout definitions are improving [from the current]. Here is what we plan:

```scss
[flex] { 
  box-sizing: border-box;
 }

[flex]           { flex: 0 1 auto;  }
[flex="initial"] { flex: 0 1 auto;  }
[flex="auto"]    { flex: 1 1 auto;  }
[flex="none"]    { flex: 0 0 auto;  }
[flex="0"]       { flex: 1 1 0%;    }
[flex="1"]       { flex: 1 1 1%;    }
[flex="100"]     { flex: 1 1 100%;  }
```

**Comment by ThomasBurleson** [comment]
Fixed in `master`
