### ISSUE TITLE
swipe: $injector error

### ISSUE THREAD

**Issue by ngraef** [angular/material#2503]
[Recent refactor](https://github.com/angular/material/commit/977a495e7d3de27bebabdebaaf5611c9d06a1e22#diff-b1acf91642f2c6f68a3770b4b3b7f813R46) caused an [unknown provider error](https://docs.angularjs.org/error/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20mdSwipeRightDirective) because of a missing injector annotation for `$parse`. Reproducible on the [tabs demo page](https://material.angularjs.org/#/demo/material.components.tabs).

cc: @robertmesserle

**Comment by ThomasBurleson** [comment]
@robertmesserle - I think the build changes broke Swipe provider. Looks like nothing includes `material.components.swipe`
