### ISSUE TITLE
mdAutocomplete: provide another demo using more complex templates

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2505]
The mdContactChip directive uses autoComplete with a nice template; but this is rather hidden from public view. It would be nice to demonstrate how mdAutoComplete supports more sophisticated templates for **cool** list rendering.

**Comment by ginader** [comment]
:+1:

**Comment by hhietanen** [comment]
I would also appreciate a demo which uses for example Google geolocation api to autocomplete address data.

**Comment by rhelenagh** [comment]
Cool

**Comment by ThomasBurleson** [comment]
@ginader, @hhietanen,  - please provide a description, mockup, and (if available) code samples, etc. of you thoughts for **complex templates**. The more existing code and templates that you provide, the easier it is for us to integration into our demo suite(s).

**Comment by yarl** [comment]
Here are some examples will be great to see in docs:

![example](http://i.imgur.com/TTN9mp3.png)
via maps.google.com

![example](http://i.imgur.com/P4TT9dS.png)
via [selectize.js docs](http://brianreavis.github.io/selectize.js/)
