### ISSUE TITLE
md-select causes md-whiteframe to disappear while open

### ISSUE THREAD

**Issue by AaronBuxbaum** [angular/material#2509]
Hi all,

I'm seeing a strange bug where an `md-select` within an `md-whiteframe` causes the whiteframe styling to disappear while the select is open.

To illustrate this, I have some pretty minimal code:
```
<body layout>
  <md-whiteframe class="md-whiteframe-z1">
    <md-select ng-model="test">
      <md-option>1</md-option>
    </md-select>
  </md-whiteframe>
```

Here's what it looks like before (correct behavior):
![select-correct](https://cloud.githubusercontent.com/assets/5578581/7289361/fa598196-e93c-11e4-9a2a-b01813b7fe1f.PNG)

Then, I click the `md-select`. Notice how the whiteframe is gone -- this pretty bad in a larger application use:
![select-incorrect](https://cloud.githubusercontent.com/assets/5578581/7289365/10d7fea2-e93d-11e4-9068-1e84d0c64335.PNG)

On select or click off (select is not open state), it again looks fine:
![select-correct-again](https://cloud.githubusercontent.com/assets/5578581/7289368/210351dc-e93d-11e4-9b66-748096de8fdb.PNG)

**Comment by rhnatiuk** [comment]
Linked to #2447 and  #2456, I guess.

**Comment by AaronBuxbaum** [comment]
I don't think it's the former, but the latter definitely does seem similar-ish. It also might be potentially related to #2390?

**Comment by ngraef** [comment]
Do you have a codepen or plunkr for this? Potentially the same issue as #2507.

**Comment by AaronBuxbaum** [comment]
@ngraef That seems likely. Here's a codepen: http://codepen.io/anon/pen/LVYJbP
