### ISSUE TITLE
md-tabs option to disable swipe

### ISSUE THREAD

**Issue by Rouby** [angular/material#2511]
Is it possible / planned to include an option to disable the swipe on md-tabs?

Or is there a way to prevent swipe when other elements have the focus? e.g. a slider.

**Comment by ThomasBurleson** [comment]
Duplicate

**Comment by stewones** [comment]
duplicate where?
+1

**Comment by mrmarktyy** [comment]
+1 

wondering in what version was this feature released ?

**Comment by Fangmingdu** [comment]
It is here. #2331
