### ISSUE TITLE
md-list: bad position of secondary action (button)

### ISSUE THREAD

**Issue by jakubweber** [angular/material#2512]
There is bug when secondary actions has bad position, should be with vertical align to middle. But that button has position: absolute; with top: 0;.

So when the md-list-item's height is shorter or higher the position of the secondary action button isn't properly aligned.

This is screenshot from demo page. (Chrome 42.0.2311.90 m, Windows 7)
![md-list-icon](https://cloud.githubusercontent.com/assets/5078760/7292576/87ba6e6e-e99d-11e4-85b5-83a6af22c563.png)

But I'm using master branch, and there also isn't good and easy way wrote correct markup for good alignment for all items in md-list-item.

**Comment by martinbrylski** [comment]
Would this suffice?

```
md-list-item>md-icon.md-secondary {
    position: absolute;
    top: 0;
    bottom: 0;
    margin-top: 0;
    margin-bottom: 0;
    height: 100%;
}
```

**Comment by marcysutton** [comment]
@robertmesserle worked on this today, is nearly fixed except for the click-highlight color doesn't go full height. I'm looking into that.

**Comment by marcysutton** [comment]
The "fix" was to put inline height styles into the list controls demo, which then puts the burden on every developer who uses the component. I think line-heights or min-heights need to be worked into the list controls component instead. 

The challenge is making clickable controls that aren't using `.md-button` like "Single Action Checkboxes" at least `4.8rem` tall *and* have the checkbox vertically aligned in the center. Going to punt on this for now.

**Comment by marcysutton** [comment]
Closed with 4b045b5860cc5bebe6e7e17ca4c723a71a6abbfa.

**Comment by hanthomas** [comment]
While this is a welcome fix, it's causing any md-list-item that's hidden with ng-show or ng-hide to retain its height, resulting in huge gaps between list items.

**Comment by marcysutton** [comment]
@hanthomas can you provide a Codepen or Plunker showing that issue? It's odd that a hidden item would retain its height.

**Comment by robertmesserle** [comment]
I created a CodePen and am not seeing this: http://codepen.io/robertmesserle/pen/3fc39e8e503ff71d39dbd493740cab34?editors=101

**Comment by hanthomas** [comment]
My bad.  You're correct @robertmesserle.  I noticed that in my code, the ng-show was applied to the DIV inside the md-list-item, instead of on the md-list-item itself.  Once I applied that ng-show properly, everything worked as expected.  Sorry for the false alarm.

**Comment by Asoseil** [comment]
How can i define a type for button with md-secondary class?  This is my code

<md-button type="button" class="md-icon-button" aria-label="More">
	    	<md-icon class="md-secondary" ng-click="dialog()" md-svg-icon="ic_description_48px.svg"></md-icon></md-button>

the tag type is ignored

**Comment by marcysutton** [comment]
@Asoseil that sounds like a separate issue.
