### ISSUE TITLE
master: md-dialog layout off when wrapping md-content & md-actions with form

### ISSUE THREAD

**Issue by sheaujye** [angular/material#2514]
Guys, this is what I have been doing, it was working until rc1, because my dialog acts like a form, i will need to put form submission buttons in md-actions.

    <md-dialog class="dialog login" aria-label="Login" style="width: 400px" ng-controller="loginController">
        <form name="loginForm" ng-submit="submitForm()" novalidate>
            <md-content>
                <h2 class="md-title">
                    <span translate>Login</span>
                </h2>
            </md-content>
                    ...
            <div class="md-actions">
                <md-button type="button" ng-click="showDialog('request-pin')">
                    <translate>Forgot Password</translate>
                </md-button>
                <md-button class="md-primary" ng-disabled="loginForm.$invalid">
                    <translate>Login</translate>
                </md-button>
            </div>
        </form>
    </md-dialog>

Removing form fixes the problem but I will need that for my app to work.

**Comment by sheaujye** [comment]
![financio](https://cloud.githubusercontent.com/assets/4597400/7293953/e229a87c-e9db-11e4-837d-641c38fd5bdb.png)

**Comment by epelc** [comment]
+1 I also use this for my dialogs. I noticed it in a recent master from yesterday but I reverted to `0.9.0-rc2` after some other tests.

**Comment by marcysutton** [comment]
Hi there, this was caused by a change to the CSS where `md-content` was too general and it affected nested components. To fix this, `md-dialog` now requires `md-dialog-content` as a child element instead of `md-content`. This is more consistent with `md-card,` which uses `md-card-content`.

**Comment by sheaujye** [comment]
Hi @marcysutton ,

Sorry it is still not working, please refer to the original post and replace md-content with md-dialog-content, when we have another element in between, be it "form" or "div", "display: block" is being applied to that element while "md-dialog-content" became an inline elem, causing layout off.

**Comment by 4rlekin** [comment]
This really should be reopened, just ran into exact same problem.
