### ISSUE TITLE
md-autocomplete displays "true" if model is undefined

### ISSUE THREAD

**Issue by uriva** [angular/material#2515]
Example: http://plnkr.co/edit/SyWrnP4dn57JuPxbVoJm?p=preview

In ng-repeats and such it is common for me to use local variables which are un-initialized. This requires me to initialize each and every one of them.

~~Using ng-init is an option, but I think it would be better to let the directive initialize them with empty string.~~
I have a usecase where ng-init does not work for some reason. Not sure why.

**Comment by epelc** [comment]
+1 I was wonder why my tests with address auto completion started out as true.

**Comment by ekaitzht** [comment]
+1 I am trying to reproduce the demo and it's displaying 'true' instead the exaple.

**Comment by ThomasBurleson** [comment]
This can be reproduced in the [Basic Usage](https://material.angularjs.org/#/demo/material.components.autocomplete) online demo if these two lines are commented out:

```js
//    self.selectedItem  = null;
//    self.searchText    = null;
```

This will be fixed shortly.
