### ISSUE TITLE
md-tabs animations slow in cordova app

### ISSUE THREAD

**Issue by Alex-Sessler** [angular/material#2516]
I'm trying to use md-tabs in a Angular/Cordova Mobile App. 
The animations are slow and shaky, even with the demo content of the MD Homepage:
https://www.youtube.com/watch?v=7gciUz6bF8s
They become slower with more content.

Is there any fix for that or any chance to override the animations with hardware accelerated animations? I'm saying that because i use different (hardware accelerated) animations at some other point in the app and they are much smoother.

Thanks a lot

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
