### ISSUE TITLE
Grid system elements need integers for width, otherwise the grid is imperfect

### ISSUE THREAD

**Issue by cristi-miclea** [angular/material#2521]
Seeing that it's a grid, it should be able to maintain a step. Due to different browsers rendering in different ways float values, I think the grid elements need to have integers for dimensions / paddings, etc.

![screen shot 2015-04-23 at 15 52 37](https://cloud.githubusercontent.com/assets/1105473/7297367/c9b59cc0-e9d0-11e4-855f-7a80906a3ad7.png)

Eg. if 1x1 element width is 155.3px, the grid should be 155.3px x 155.3px, if you try to move that element by 155.3px in any direction it will be inconsistent.

**Comment by ThomasBurleson** [comment]
@cristi-miclea - I am not sure I understand your request. Are you saying you do **not** want floating number values ?

**Comment by cristi-miclea** [comment]
Hi Thomas, yes.. I'm trying to do some drag & drop and when trying to get elements to snap into place by determining the grid size... for a 12 column layout we can have a 1x1 square be equal to 157.33px. This doesn't matter originally, but when I try snapping an element to the right by 157.33px that's not going to happen in any browsers as most of them have limitations..

![screen shot 2015-04-23 at 17 56 14](https://cloud.githubusercontent.com/assets/1105473/7300063/705748a6-e9e2-11e4-8109-03430c99b5a9.png)

![screen shot 2015-04-23 at 17 58 55](https://cloud.githubusercontent.com/assets/1105473/7300067/765e526c-e9e2-11e4-9a2e-f35184b9bdc0.png)

![screen shot 2015-04-23 at 17 58 40](https://cloud.githubusercontent.com/assets/1105473/7300066/7358b684-e9e2-11e4-9070-5a1a5b116bb8.png)

With these type of values for elements, there's no way that I can see to maintain a grid system.
these .5, .25 propagate when trying to shift elements as you can see below.

![screen shot 2015-04-23 at 17 59 42](https://cloud.githubusercontent.com/assets/1105473/7300083/9f4bd334-e9e2-11e4-84ba-b0339dc31239.png)

![screen shot 2015-04-23 at 17 59 59](https://cloud.githubusercontent.com/assets/1105473/7300085/a2c6c122-e9e2-11e4-84ef-ecbe53b168cd.png)

![screen shot 2015-04-23 at 17 59 49](https://cloud.githubusercontent.com/assets/1105473/7300092/b7967aa2-e9e2-11e4-8cc4-920a4a0eefca.png)

Having integers as widths will leave some spacing on the side, I agree, but will improve the grid system

**Comment by orion538** [comment]
Excuse my asking a question on your question, but how did you do all this? Can I see how you implemented your drag and drop and how you get the values for the calc function?
