### ISSUE TITLE
md-select: ng-change firing when you select the same item you have selected

### ISSUE THREAD

**Issue by epelc** [angular/material#2524]
If you use `ng-change` with `md-select` and you open the select but click on the same item that is already selected the change function is still called.

**Comment by rschmukler** [comment]
@epelc as per [this demo](https://jsfiddle.net/rschmukler/puma43uo/) this appears to be working fine. Can you give me a demo?

**Comment by epelc** [comment]
@rschmukler Sorry I overlooked this. It appears to be a non related problem with stripe. It was requesting the favicon for every click and I thought it was reloading data instead.
