### ISSUE TITLE
$mdToast: is there a way to specify parent when using simple()

### ISSUE THREAD

**Issue by warpdesign** [angular/material#2526]
I'm using $mdToast.show($mdToast.simple().content('foo')) to insert toast in my app.

The problem is that by default I guess toast is inserted into the body of the document. Since I'm using SVG (that can several body elements), this messes up with $mdToast: several toasts are displayed, some with default {{ toast.content }} and they are not removed.

Is there a way to easily change the parent when using simple so that the toast only gets inserted into document.body ?

**Comment by warpdesign** [comment]
I found the problem:
in `core/services/interimElement/interimElement.js` line 370, there is:
    if (!(options.parent || {}).length) {
                    options.parent = $rootElement.find('body');
                    if (!options.parent.length) options.parent = $rootElement;
                    if (options.parent[0].nodeName == '#comment') {
                      options.parent = $document.find('body');
                    }
                  }
Problem is that if ng-app is defined on the body, and the page contains some svg elements with body tags inside, parent will be set to the collection of body element found in svg elements.

This then messes up since most methods will expect only one element (for eg. toast).

**Comment by ngraef** [comment]
It's not documented on [the `$mdToast` service page](https://material.angularjs.org/#/api/material.components.toast/service/$mdToast), but you can use the `parent(element)` configuration method:

```javascript
var toast = $mdToast.simple()
    .content(message)
    .action('OK')
    .highlightAction(true)
    .hideDelay(0)
    .position('bottom right')
    .parent(el);

$mdToast.show(toast);
```

[Demo](http://codepen.io/anon/pen/doyjvQ)

**Comment by warpdesign** [comment]
Oh, I remember tried out parent() but that didn't work, now I see why :)

**Comment by bluebirdtech** [comment]
I didn't seem to get the parent property to do anything, even when applying to md-content/md-dialog-content elements.  The toast was always placed relative to the screen.

Reading the material design spec though, it only mentions positioning relative to the screen.  Is this the only available positioning?  If so, I'm not sure what the parent property is for.

For reference, I was trying to add a toast to a dialog, which I've now decided against. I'll just use the bottom of the screen and hope users spot it.  What I really want is #698 so I can show an alert over a dialog that the user cannot miss.

**Comment by ThomasBurleson** [comment]
Toasts are global and intended for the SPA body viewport; you cannot
specify a `parent` .

**Comment by bluebirdtech** [comment]
Thanks, I'm fine with that.  Not sure what the parent property listed in the API reference is for then? https://material.angularjs.org/HEAD/#/api/material.components.toast/service/$mdToast

**Comment by ThomasBurleson** [comment]
@bluebirdtech - My apologies. The API is correct that you **should** be able to specify a `parent` to be used with `$animate.enter(toast, parent)`. While the toast should be displayed in the $rootElement/body, you should be able to specify a custom parent. You have discovered a bug; I will submit a PR for the fix(es).

> Note:
*  that the parent will default to the `$rootElement` if not specified.
*  the parent should have a `position:relative` for the toast to position *absolute* properly.

**Comment by Prasinooo** [comment]
the parent area should be the child of an md-content,like this:
<md-content>
  <div id="parent">

........
  </div>
</md-content>

**Comment by badcoder28** [comment]
`parent()` of `$mdToast` works well in v1.1.1

**Comment by Padraig-O-Cuinn** [comment]
.simple() for me isn't getting recognized? does anyone know why?

**Comment by iposton** [comment]
@Padraig-O-Cuinn this worked for me. Make sure that you injected $mdToast into your controller. Credit to @ngraef for having the correct solution.

```js

var parentEl = angular.element(document.body);
$mdToast.show(
       $mdToast.simple()
        .textContent('this is a toast with action')
        .action('OK')
        .highlightAction(true)
        .hideDelay(0)
        .position('bottom right')
        .parent(parentEl)
     );

```
