### ISSUE TITLE
md-input-container data entry consistency

### ISSUE THREAD

**Issue by daw451-duplicate** [angular/material#2528]
md-input-container is great works well, very responsive... but when you start to introduce other components such as the md-select, the input consistency within a page begins to have issues. The md-select, for instance, cant be used in the md-input-container so it makes it difficult to get the same user experience as compared to an input element. 

Could the md-input-container be changed to include all the other possible elements or take an approach that the second child under the md-input-container, meaning the element just after the label, behave the same regardless of its implementation? The requirement would just specify that the elements would need to be laid out in a specific order..

**Comment by sazonenka** [comment]
+1

**Comment by Sriram143** [comment]
+1

**Comment by jelbourn** [comment]
@daw451-duplicate md-select now uses md-input container. Closing this for now, re-open if you have other specific examples of where md-input-container would be used.
