### ISSUE TITLE
material.angularjs.org is broken in IE11

### ISSUE THREAD

**Issue by uxder** [angular/material#2532]
## Visit https://material.angularjs.org/in IE11

![screen shot 2015-04-24 at 5 06 50 am](https://cloud.githubusercontent.com/assets/7152/7306363/c2102214-ea3f-11e4-871d-dd907bd522ac.png)

**Comment by epelc** [comment]
@uxder What os/browser version are you using? Click the little cog in the top right then `About internet explorer` for the ie version.

If your using windows 8 or 8.1 I think their recent security update(KB 3038314) majorly broke flexbox. It completely screwed my site up. But it works fine in a newer ie version on windows 10.

**Comment by uxder** [comment]
Yeah window 8.  I should also note that this is via a VM so I haven't verified it on an actual window machine.

**Comment by rschmukler** [comment]
Just tested it on (Microsoft's RemoteIE)[https://remote.modern.ie/] and it appears to be working...

**Comment by uxder** [comment]
Okay. I'm using virtualbox, IE11.  Also try searching your site on bing.  I also noticed your search results on bing are messed up with broken angular tags (not sure if its a related issue).
![screen shot 2015-04-24 at 6 21 04 am](https://cloud.githubusercontent.com/assets/7152/7307841/5649980c-ea4a-11e4-9993-d6f7812c1a7f.png)

**Comment by ilanbiala** [comment]
@ThomasBurleson doesn't sound like the issue was resolved because someone is seeing it broken somehow.
