### ISSUE TITLE
md-content: Not scrolling to top on state change

### ISSUE THREAD

**Issue by epelc** [angular/material#2533]
Hello please let me know if the app/ui-router should handle this instead but it appears in `0.9.0-rc1` or in `0.9.0-rc2` `md-content` no longer scrolls to the top if you change states. It keeps the current scroll position which isn't very helpful.

My html is layed out like the following
```
<md-content>
// The md-content isn't replaced the ui-view inside it loads different templates
<div ui-view></div>
</md-content>
```

Again please let me know if this should be handled in my app code. I just thought I'd file an issue as it used to work perfectly in `0.8.3`.

**Comment by rschmukler** [comment]
@epelc is this issue at all dependent on whether a select has been opened prior to the route change, or does it happen either way? Just narrowing down where this might have come from...

**Comment by epelc** [comment]
@rschmukler It may. I'm pretty sure no. Id bet its more likely to do with the original select changes in 0.9.0rc1. But I just left the office so I'll confirm later on tonight.

**Comment by epelc** [comment]
@rschmukler It doesn't seem to be associated with `md-select`. I even tested on pages(fresh loads) where I didn't even show any `md-select`'s between the pages I changed between.

**Comment by cranesandcaff** [comment]
Confirming issue. Has anyone found a solution?

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (520/500 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:18692)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avsc9-000L4Q-49
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:45 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=ERi4OEMywUhrX0V4hqYSdX0DCug=; b=tTIzvFy1G+zEeRYv
	1RD6XQsJf+bx12uYmuvh5ECf2hEh9EpnqXsYnhYbDql1rtjWmI+NwRGtFGwM/gH9
	Ls8VqRJVDx3A+ptf7OxuGjfYnbcb3fZYxSdF4XLCe+jPC8byDw86dReGK9rhxMjV
	rg4FRvIxJ/LSDdG2B17+i97eTsE=
Received: by filter0452p1mdw1.sendgrid.net with SMTP id filter0452p1mdw1.29670.572273501C
        2016-04-28 20:32:16.478265918 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id wIMUcihMTO6_VDFLKJ9_3Q
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:16.565 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:16 -0700
