### ISSUE TITLE
Provide a sandbox to easily show issues (codepen/plunkr...)

### ISSUE THREAD

**Issue by jgoux** [angular/material#2534]
Hi,
we often ask for demo in issue and a lot of people don't provide one because they don't want to take time to create a codepen/plunkr, set up the html/js, and then show their issue.

I made a basic codepen so they just have to start coding without thinking about including angular-material, angular and so on. Maybe you can include it in the README ?

It's tiny, but I'm sure it can convince some folks to include a demo with their issues (no more excuse :smile: )

I use rawgit to always be up-to-date with the master : http://codepen.io/jgx/pen/JogKrQ

Just fork it !

EDIT : I hid external resources so now there just a single `<div>` to start coding.

**Comment by epelc** [comment]
+1
Here is a basic plunker with everything ready to go. I had an issue about this before but I think just empty plunker/codepen/jsfiddle's got added to the readme/docs/google groups page.

http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview

**Comment by DmitryEfimenko** [comment]
+1

**Comment by ThomasBurleson** [comment]
Excellent work guys. I will add these links to the verbiage when we ask for a demo.
Do you think these should be in doc/readme somewhere?

**Comment by jgoux** [comment]
@ThomasBurleson Maybe in the https://github.com/angular/material#-contributing section ?

**Comment by epelc** [comment]
@ThomasBurleson I was also thinking under the cdn section in the readme

![image](https://cloud.githubusercontent.com/assets/5204642/7321001/ca83c09e-ea6d-11e4-857a-970ce575ca65.png)

And perhaps to be really good on the google groups page there are afew links which I would expect to be demo ready
![image](https://cloud.githubusercontent.com/assets/5204642/7321047/fadc6e26-ea6d-11e4-8624-122f00433dae.png)
https://groups.google.com/forum/#!forum/ngmaterial

**Comment by ThomasBurleson** [comment]
@jgoux - can you send me (via email) your email? Thx.

**Comment by epelc** [comment]
@ThomasBurleson Can you update the plunkr link I accidentally used it for a different issue without forking. But it won't let me change the original one now.

Anyways here is an empty one just importing angular-material with a toolbar and `md-content`
http://plnkr.co/edit/8l3Qw0BmxKHFs60KUd2V?p=preview
