### ISSUE TITLE
angular select ng-model not binded when use inside md-tabs

### ISSUE THREAD

**Issue by Fangmingdu** [angular/material#2537]
I have a normal select inside a md-tab with a ng-model itself.

In the ng-change event, I cannot get the ng-model, which is undefined.

Please see the plunkr below:
http://plnkr.co/edit/6TC5LnDI8aAnLGTqMw8M?p=preview

**Comment by rschmukler** [comment]
This bug seems to be fixed in `0.9.0`. As demoed by [this plunker](http://plnkr.co/edit/cZJzINM6yKM82vHQkgH7?p=preview). Feel free to open a new issue if you run into it again.
