### ISSUE TITLE
FAB buttons exhibit strange color issues on iOS

### ISSUE THREAD

**Issue by hanthomas** [angular/material#2538]
This one is very difficult to demonstrate since we have only noticed it on iOS.  A page containing one or more FABs doesn't apply colors until the page is refreshed.  In some case, the FAB is white, while in other cases the FAB remains as the accent color even though we explicitly apply md-primary or a custom background-color style to it.  Then, when I tap on any icon or button the page, the FAB magically has the correct color.  Here's the plunkr that demonstrates the problem:

http://plnkr.co/edit/BZLr1UgfWb1wF3OBOXsn?p=preview

However, in order to reproduce it, you have to 1) run the plunkr on an iOS device, and 2) run the plunkr full-screen by clicking on the icon for "Launch preview in a separate window".

The way to reproduce it is by tapping on the Next Page button, and then returning to the original page by tapping on the Return to Previous Page button.  This problem happens consistently on iOS.

**Comment by marcysutton** [comment]
That full-screen URL is a 404. Can you update it with the correct URL?

**Comment by hanthomas** [comment]
@marcysutton - I updated the issue.  Apparently, the URL for full-screen plunkr isn't reliable between sessions.

**Comment by hanthomas** [comment]
You can also reproduce this problem by simply going to the ngMaterial demo site on your iPad and going to the Toast demo _after tapping on another demo_, like Toolbar.  It might take a couple tries to make the problem happen.  The results seem to indicate that there's a general problem with application of themes, not just for the FAB, but also for checkboxes, etc.

**Comment by topherfangio** [comment]
@hanthomas Do you know if this is still an issue? I've been attempting to reproduce but cannot seem to make it happen.

**Comment by hanthomas** [comment]
@topherfangio - This problem is no longer an issue.  It must have gotten fixed in one of the previous updates.

**Comment by topherfangio** [comment]
@hanthomas Awesome, thanks!
