### ISSUE TITLE
While typing in an input inside an md-input-container , the text is not visible (disappears intermittently) on iphone browser and iphone webview

### ISSUE THREAD

**Issue by myellepeddy** [angular/material#2539]
User can't see what he/she is typing.

It happens on my iphone 6 . In the browser and in the webview. Particularly when the input has ng-messages (errors) associated with it. And as I scroll the page the text appears or disappears.

I attached two screen shots of the demo page as I typed something. The text was not visible. And I scrolled the page up and down it appeared ( third screen shot)

I really want to release my app based on 0.9.0. This issue is holding up the release. I would like this to be included in 0.9.0 release.

Thank you
Murali
![img_4621](https://cloud.githubusercontent.com/assets/134486/7310570/4e6ec470-e9fc-11e4-9533-3bb49c65e8d9.PNG)
![img_4622](https://cloud.githubusercontent.com/assets/134486/7310571/4e701d02-e9fc-11e4-8ff3-b312b029b8e9.PNG)
![img_4623](https://cloud.githubusercontent.com/assets/134486/7310572/4e706e9c-e9fc-11e4-97d6-31c7b7258928.PNG)

**Comment by myellepeddy** [comment]
Do you think this issue will be addressed as part of 0.9.0 release?

**Comment by jpike88** [comment]
This issue is still present. Testing with iOS9, text inputs are barely usable.

**Comment by jpike88** [comment]
Can someone please reopen this? The issue has not been resolved.

**Comment by jpike88** [comment]
#7078 

I have attached a video with the latest angular build

**Comment by psaunders** [comment]
Yeah, still happening

**Comment by ThomasPe** [comment]
Still.

**Comment by jpike88** [comment]
No chance this will be fixed.

Do what I did and just avoid using the text inputs altogether

**Comment by ThomasPe** [comment]
Interesting observation: I can't reproduce this issue when the input controls are being used inside a [material dialog](https://material.angular.io/components/dialog/overview)... not sure yet why that is though.

**Comment by Splaktar** [comment]
If you are still experiencing a similar issue, please open a new issue with a CodePen reproduction and details about the iOS device and browser being used.
