### ISSUE TITLE
0.9.0 RC1: md-select blanks out view when clicked

### ISSUE THREAD

**Issue by atentis** [angular/material#2541]
Using 0.9.0 RC1 there is a bug when you click the md-select the view blanks out white except for the md-select/md-options. After you have selected an option the view comes back. Prior to this on 8.3 the md-select operated the same way as a regular html one in that the rest of the html page does not disappear.  

This is using the ripple emulator with visual studio 2013 Cordova Tools. 
```
<div ng-controller="mrCreateRequestCtrl">
       <div layout="column" layout-align="center center">
                <section layout="row">
                    <md-select ng-model="request.room" placeholder="Select Room:">
                        <md-option value="Living Room">Living Room</md-option>
                        <md-option value="Dining Room" ng-selected="selected">Dining Room</md-option>
                        <md-option value="Kitchen">Kitchen</md-option>
                    </md-select>
                </section>
      </div>
</div>
```

**Comment by daw451-duplicate** [comment]
have you tried updating to rc2. Those issues have been corrected. But there still as of today some slight page jitter when it opens. And depending how close the drop down is to the bottom of the vertical scrollbar end, the bottom of the page gets a slight white out. For example:

![image](https://cloud.githubusercontent.com/assets/798281/7320665/0506efa4-ea6c-11e4-8132-25341bdab5b6.png)

Shot from the demo site you can see how the word 'validation' gets over layed by that white strip...

**Comment by dmackerman** [comment]
This is fixed in RC2.

**Comment by atentis** [comment]
@dmackerman  My apologies. I just tried rc2 and it the ripple emulator it seems to work again. 

@daw451-duplicate  I do not see the jitter mentioned. What environment is this happening to you in? I am not able to try on a mobile device right now.

**Comment by rschmukler** [comment]
Select has been heavily worked on since RC1, and even RC2. Please try the code off of master to see if issues persist. Closing for now, but feel free to open a new issue if you have problems with the latest code.

**Comment by atentis** [comment]
thanks @rschmukler

**Comment by mariohmol** [comment]
I'm having this issue .. in version "angular-material": "^1.1.0-rc.5" .. all screen get blanks..  this happens just when select is close to the end of the page

**Comment by bahaaldine** [comment]
+1

**Comment by sharabingit** [comment]
I am having this issue in version "angular-material": "v1.1.0-rc4" . The screen gets blank, if we click on <md-select>

**Comment by ThomasBurleson** [comment]
We only support the latest release (attached: v1.1.1) or HEAD

**Comment by danitedy** [comment]
I am having the same on version  v1.1.1. The screen blanks out , when md-select is opened at the bottom of the page
