### ISSUE TITLE
md-pagination-wrapper has fixed width of 999999px which causes problems with tabs on Firefox

### ISSUE THREAD

**Issue by iLiviu** [angular/material#2543]
Because of the fixed width, all tabs and parent elements will have a huge width in Firefox (tested on v. 37)

The problem can be noticed in the tab demo: https://material.angularjs.org/#/demo/material.components.tabs (the width of all tab containers is affected and in the first example you can see how text is clipped because of this)

**Comment by ThomasBurleson** [comment]
:+1:

**Comment by epelc** [comment]
@robertmesserle Thanks for fixing this!. I think it was causing my unresponsive script errors(from google maps) when I used tabs on the same page as google maps. Took me forever to figure out it was the tabs but it makes sense that a huge width would slow firefox to a halt.
