### ISSUE TITLE
md-chip-remove makes a duplicate DOM-element

### ISSUE THREAD

**Issue by hkjels** [angular/material#2545]
A container is created when using the `md-chip-remove` attribute, but the transclude is not set to replace, so the remove-template results in being duplicated.

**Comment by typotter** [comment]
Can you link a jsfiddle or other demonstration of this? I'm not seeing extra elements when passing an md-chip-remove template to the chips component.

**Comment by hkjels** [comment]
Here's a [fiddle](https://jsfiddle.net/8y85nbgz/) using code from the material-design website directly.

**Comment by typotter** [comment]
Thanks for the fiddle.
The element marked with md-chip-remove must be a child of md-chips, not md-chip-template.
I have added a warning to the code and modified the selector reflect this restriction.

**Comment by hkjels** [comment]
OK. Thank you!
The doc says otherwise, that's what was misleading.
[mdChipRemove](https://material.angularjs.org/#/api/material.components.chips/directive/mdChipRemove)

**Comment by typotter** [comment]
You are correct! (The docs are not). I checked the demo HTML, but did not check the docs. I've updated them in my PR to fix this bug.
Thank you for your feedback!
