### ISSUE TITLE
mdDialog on ios safari has space in bottom after scrolling

### ISSUE THREAD

**Issue by omida86** [angular/material#2547]
$mdDialog.show(
      $mdDialog.alert()
        .title('This is an alert title')
        .content('You can specify some description text in here.')
        .ariaLabel('Alert Dialog Demo')
        .ok('Got it!')
        .targetEvent($event)
    );

After scrolling down a bit, the dialog and md-backdrop does not reach all the way down on ios safari. It does however work correctly on Chrome/Android.

**Comment by omida86** [comment]
I kind of found out when this happens. It's because the bottom bar in safari gets hidden when you scroll  down and the $mdDialog doesn't stretch all the way down to the bottom.

**Comment by ThomasBurleson** [comment]
I think the ScrollLock needs to listen for window resize events.

**Comment by rschmukler** [comment]
This is fixed on master (resolved by scrolling being blocked by `$mdUtils`).
