### ISSUE TITLE
md-icon inside md-button doesn't get text color

### ISSUE THREAD

**Issue by davide-quix** [angular/material#2551]
When inserting an md-icon inside and md-button without md-raised class, to make a button with icon and text, the md-icon doesn't take the same color as text. Causing a very fuzzy button to display.

http://plnkr.co/edit/lbvK84KZHYYzLshoRxiB?p=preview

In the previous version (0.8.x) this worked.

**Comment by ThomasBurleson** [comment]
Just use `<md-icon md-svg-src="icon.svg" style="  color: rgb(244,67,54)"></md-icon>`

**Comment by davide-quix** [comment]
Why I should put inline style for color when the work should be done by the theme?
Using the md-raised or md-fab class the md-icon color work is manageb by theme as I intend.
http://plnkr.co/edit/rEW16IwZpHRL4ChoYtem?p=preview
 Then why without it should not in a normal button, forcing me to write inline style rules?

**Comment by ThomasBurleson** [comment]
@davide-quix - Thanks for the follow-up question. While you can easily override and set the color, I agree that the icon should **inherit** the parent's color (unless explicitly overridden at the Icon or SVG levels).

**Comment by FrederickE** [comment]
Please how can I change both `md-icon` inside `md-button` with the button text to have the same color when I hove over it. Please see example on [plunker](http://plnkr.co/edit/mQiuHgYD21J9lWzyCAnL?p=preview)

**Comment by MustafaASK** [comment]
I also am seeing the same issue, but looks like there is no solution to it, yet.

**Comment by MustafaASK** [comment]
Hi FrederickE, Did you find solution for your problem? We are facing the same issue and have no solution as yet. :(.

**Comment by FrederickE** [comment]
@MustafaASK, yes I later figured it out and updated the CSS. Check the [plunker](http://plnkr.co/edit/mQiuHgYD21J9lWzyCAnL?p=preview)

**Comment by MustafaASK** [comment]
Thanks a ton, FrederickE. This made my day!
