### ISSUE TITLE
md-autocomplete: Horizontal scrollbar if opened near window edge and results update fast

### ISSUE THREAD

**Issue by epelc** [angular/material#2554]
`md-autocomplete` is creating a scrollbar if you open it near the edge of a window. But it only happens if you type something in very fast. For example in the picture below I typed in `34202` but the problem only happens if I rapidly type in the zipcode however it's fine if I type it in one by one with a brief pause in between keystrokes.

![image](https://cloud.githubusercontent.com/assets/5204642/7325551/01d00cb4-ea8d-11e4-977c-3012d0c63736.png)

I think it has to do with the long address at the end of the list. But I also think it isn't recalculating the position correctly.

As a side note setting `overflow-x: hidden;` on `body` removes the horizontal scrollbar however the autocomplete popup still needs to be positioned correctly. This may be a nice attribute to set when your in production as the horizontal scrollbars help to find issues like this with autocomplete tooltips etc. But It'd be nicer to not see them in production.

**Comment by robertmesserle** [comment]
This should have been resolved earlier.  I'm not currently able to reproduce it - please re-open with CodePen if it is still occurring.
