### ISSUE TITLE
md-autocomplete(md-floating-label): Missing padding

### ISSUE THREAD

**Issue by epelc** [angular/material#2555]
`md-autocomplete` is missing the following padding rules when your using `md-floating-label`

These are the same rules used in `md-input-container` which I think should be applied to `md-autocomplete` when it's used with `md-floating-label` so that they can look the same.
```
  padding: 2px;
  padding-bottom: 26px;
```

**Comment by robertmesserle** [comment]
This was being overridden by custom styles within autocomplete.  Those styles have been removed, so it will now inherit the padding from the `md-input-container` used within autocomplete for floating labels.
