### ISSUE TITLE
update(docs): md-input typo correction

### ISSUE THREAD

**Issue by robertbaker** [angular/material#2556]
In the md-input error demo:

$5,000 an hour? That's a little ridiculous. I doubt **event** Bill Clinton could afford that

Should be `even`

**Comment by marcysutton** [comment]
You are welcome to submit a PR :)

**Comment by robertbaker** [comment]
I will be glad to, just need help finding the file.

>

**Comment by topherfangio** [comment]
@robertbaker Sorry for the delay; if you're still willing to submit a PR, the file is located in `src/components/input/demoErrors/index.html`.

You should be able to just search for the word `event` and remove the `t`.

Please let me know if you have questions or no longer have time for this and I'll take care of it :-)
