### ISSUE TITLE
md-dialog preserveScope does not work

### ISSUE THREAD

**Issue by yoooee** [angular/material#2557]
According to the documentation, a new isolate scope is created on $mdDialog.show() if a scope is not specified.  When the dialog is closed, the isolate scope is destroyed.  If I set the scope for the dialog to be $scope and close the dialog, then the $scope of the page is completely destroyed.  Setting preserveScope to true seems to have no affect.  Has anyone else experienced this issue?

Thank you.

**Comment by omida86** [comment]
+1 same issue

**Comment by omida86** [comment]
Actually it is preserved, it's just that a new scope gets created.

**Comment by janmohammadi** [comment]
Same issue!

**Comment by rschmukler** [comment]
This should be fixed on master. If it's not, please create a new issue. Thanks!
