### ISSUE TITLE
md-slider: handle stays active after it is released

### ISSUE THREAD

**Issue by dbbert** [angular/material#2560]
I see this behaviour in Chrome both on desktop and mobile for the continuous version of the slider. The handle doesn't return to its normal state when it is released.

![sliderbug](https://cloud.githubusercontent.com/assets/3367974/7334097/603b6e96-eb88-11e4-8834-3e800fc27331.png)

**Comment by marcysutton** [comment]
It's probably still focused, which is the browser default behavior in Chrome. We'll have to use a similar approach to buttons or checkboxes, where `.md-focused` is only added for true focus events (no `mousedown`).

**Comment by reubenmoes** [comment]
I like that they can be `:focus`ed for accessibility.  I would expect that it would go smaller after you stopped dragging it though.  The polymer paper slider is a good example, although it isn't accessible, so I'm not too sure if this is possible to have both. https://www.polymer-project.org/0.5/components/paper-slider/demo.html

**Comment by marcysutton** [comment]
It is still focused when you stop dragging, so that is why the handle is still larger. Either it could be larger on `:active` only, or some kind of mouse/keyboard hack would have to be applied like in `md-button`. That's the whole idea behind this proposal: http://radar.oreilly.com/2015/08/proposing-css-input-modailty.html

**Comment by ivan7237d** [comment]
+1, it would be nice if behavior was consistent with other types of inputs. If anything, of all controls, that's the one for which the issue is the most critical, because focused state is so prominent.
