### ISSUE TITLE
md-checkbox triggers ng-click even when it is disabled

### ISSUE THREAD

**Issue by amerimi** [angular/material#2561]
Hello,

When md-checkbox is disabled but has an ng-click, the ng-click code gets called when the md-checkbox is clicked.

This is not the case with a normal input checkbox.

```html
<md-checkbox ng-disabled="true" ng-click="update(!item)" aria-label="Disabled checkbox" ng-model="item">
      md-checkbox: Disabled with ng-click
</md-checkbox>

<input type="checkbox" ng-disabled="true" ng-click="update(!item)" ng-model="item" />
```

Here is a test that shows the issue: http://plnkr.co/edit/t9XO0TGIA5u6m2dym1Fd?p=preview

Thanks in advance

**Comment by vishalkrv** [comment]
Same here. Even we are facing the exactly same issue.

**Comment by lorezzed** [comment]
workaround - add a parent div around the checkbox and disable that http://plnkr.co/edit/nbwsJfe5xBkBGhgoTarE?p=preview

**Comment by vishalkrv** [comment]
Thanks..

**Comment by mjhasbach** [comment]
+1

**Comment by deepikat** [comment]
+1

**Comment by belluccifranco** [comment]
+1

**Comment by DevVersion** [comment]
That issue no longer exists - should be closed. 
Solved issue in Codepen as example: http://codepen.io/DevVersion/pen/qbPQgW

**Comment by madhavanks26** [comment]
I have this isssue when i create checkbox dynamically using ng-repeat 

[(http://codepen.io/madhavansekar/pen/ZQVzLb)]

kindly suggest some ideas to overcome this issue

**Comment by AnirudhaGohokar** [comment]
Same case with radio buttons using ng-repeat... :-(

http://codepen.io/anon/pen/qbLOwG

**Comment by AnirudhaGohokar** [comment]
Facing the same issue for radio buttons without using ng-repeat

**Comment by AnirudhaGohokar** [comment]
@madhavanks26 I have got it working somehow.

Surprisingly its working only when values are set to true or false..lol

http://codepen.io/anon/pen/yeGjBv

**Comment by DavidSouther** [comment]
Cleanest approach: the ng-click should only execute a single method on the controller, which as its first action does the same check as the ng-disabled and returns immediately if so. Yes, you've duplicated some code, but your controller is no longer depending on the template to do its data sanitization.

**Comment by huangjun604** [comment]
+1
