### ISSUE TITLE
Chips - md-on-append is called twice

### ISSUE THREAD

**Issue by rbatukaev** [angular/material#2562]
Here is how I defined the chip:

```
<md-chips ng-model="tags" md-on-append="addTag($chip)">
        <md-chip-template>{{$chip}}</md-chip-template>
        <button md-chip-remove class="md-chip-remove ng-scope" ng-click="removeTag($chip)">
            <md-icon md-svg-icon="close"></md-icon>
        </button>
</md-chips>
```

However, both `addTag($chip)` and `removeTag($chip)` are called more than once. 

![screen shot 2015-04-25 at 23 44 03](https://cloud.githubusercontent.com/assets/4622415/7334757/07b3b284-eba5-11e4-84ef-22269a55a274.png)

P.S. I am on v0.9.0-rc2-master-fdcceb5

**Comment by tonyawad88** [comment]
I have the same problem. Is this a duplicate of another issue?  Why was it closed ? @rbatukaev
