### ISSUE TITLE
mdAutocomplete: Menu opening above input when using floating label

### ISSUE THREAD

**Issue by reillydavis** [angular/material#2563]
The issue can be seen on the demo page and appears to happen on all browsers: https://material.angularjs.org/#/demo/material.components.autocomplete

![image](https://cloud.githubusercontent.com/assets/4644614/7334917/0ae3bf4c-eb57-11e4-96db-ac57ce318fb7.png)

**Comment by uriva** [comment]
+1

**Comment by johnferro** [comment]
+1

**Comment by mckenzielong** [comment]
I assumed this was intended.  Codepen here: http://codepen.io/mckenzielong/pen/MwWKRM shows that it opens down if there is enough space.  Shrink your screen and it will position itself above.

**Comment by robertmesserle** [comment]
This is not an issue - it will happen when there is not enough space to display the menu below the field.

**Comment by anderslyman** [comment]
@robertmesserle this is *definitely* an issue. I have a control with 275 pixels between it and the bottom of the viewport, and list with a height of 96px, and it has decided there is not enough room so it is placed about the input. If I increase the distance from the control and the bottom of the viewport to 277 pixels, suddenly it decides there is enough.

**Comment by robertmesserle** [comment]
@anderslyman It may be an issue in your case, but not the case as reported - open a new issue with details to reproduce if you can

**Comment by anderslyman** [comment]
@robertmesserle no problem, I've posted here: https://github.com/angular/material/issues/8167
