### ISSUE TITLE
md-select resets page scroll position.

### ISSUE THREAD

**Issue by grantopher** [angular/material#2564]
I'm on: v0.9.0-rc2-master-fdcceb5
When the user clickes on the select element, the scroll position of its containing element is forced to the top of its scroll position. The panel of select options are then displayed at the bottom of the screen. Tested in firefox and chrome.

**Comment by DBGTTECHJAM** [comment]
+1

**Comment by imdpk** [comment]
+1

**Comment by adamelevate** [comment]
+1

**Comment by danielzev** [comment]
+1

**Comment by rschmukler** [comment]
Could someone submit a codepen demoing this? I'm not seeing it, as demoed [here](http://codepen.io/rschmukler/pen/XbbQmV)

**Comment by BrunoAMSilva** [comment]
Made a few changes to your demo: http://codepen.io/anon/pen/BNoQaW

I'm also having this issue in my app as well as the show/hide animations being triggered for every dom element.

**Comment by chrisguerrero** [comment]
+1
