### ISSUE TITLE
md-select and ng-messages - latest build shows floating label twice

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2572]
the latest build has broken the md-select floating label to display the floating text twice, once in its correct location and once about 20px below hidden by a scrollbar...

![screenshot](https://cloud.githubusercontent.com/assets/1916471/7342269/22c1c6a6-eca9-11e4-990e-d2d980e39601.png)

**Comment by luisfontes** [comment]
:+1:

**Comment by ngraef** [comment]
This is an issue with `md-input-container` adding a `label` for child `md-select`s that use `placeholder`. Presumably, this will be fixed by #1586, but as a workaround you can add `md-no-float` attribute to the input container or use `md-select-label` instead of `placeholder`.
