### ISSUE TITLE
mdInput: md-minlength is not triggering

### ISSUE THREAD

**Issue by suryaiiit** [angular/material#2573]
md-minlength is not triggering the MinLength error when the input is less than the minLength.
example is there in the below link:
http://codepen.io/anon/pen/waBdeE

**Comment by georgebarbarosie** [comment]
If you use ng-minlength and ng-maxlength (as well as "minlength" and "maxlength" in the ng-message directive) your example works fine. See my codepen fork: http://codepen.io/anon/pen/NqPvKb

The docs don't say anything about an md-minlength directive, as for the md-maxlength directive the purpose of that is not validation, see this quote from https://material.angularjs.org/#/api/material.components.input/directive/mdInput 

> The purpose of md-maxlength is exactly to show the max length counter text. If you don't want the counter text and only need "plain" validation, you can use the "simple" ng-maxlength or maxlength attributes.

**Comment by suryaiiit** [comment]
Thanks George, my bad. As md-maxlength is there I thought md-minlength might have been there too, I should have checked the docs.
Anyways, looks like they are going to add it in 0.10.

**Comment by amanuel2** [comment]
Is this added still? Because i still cant use md-minlength..

**Comment by amanuel2** [comment]
Is this still added? Because i still cant use md-minlength @ThomasBurleson  @robertmesserle  @suryaiiit  @georgebarbarosie
