### ISSUE TITLE
md-autocomplete: not found matches

### ISSUE THREAD

**Issue by lillylykho** [angular/material#2574]
Hello everyone!

I use md-autocomplete and it work perfect! But if I don't have a searched items I want to display message, something like: "Items not found". Is it possible to do that? 

It might to be great to use directive with message value, like this: 

    md-items-not-found="Not found!"

Thanks!

**Comment by lillylykho** [comment]
@robertmesserle, @ThomasBurleson  Thanks!

**Comment by gabguy** [comment]
In Release 0.10.1-RC4 the <md-not-found> directive is not working anymore!
I tried it in codepen with your own demo from angular-material site, still not displaying the "No matches found for..." Message

http://codepen.io/anon/pen/gpQEWg?editors=101

Please fix it,
Thanks gabguy

**Comment by evoker** [comment]
I can confirm this as well with RC5, it's not working either.

**Comment by shusain** [comment]
+1
