### ISSUE TITLE
mdSelect: View value not updated by external model updates

### ISSUE THREAD

**Issue by rjaimel** [angular/material#2575]
Maybe I'm doing something wrong but I think that the problem persists. I'm changing the model with an external event (clicking "change" label)  but the displayed item disappears and only changes if I show the list of elements. Here is the code:

HTML:

&lt;div ng-controller="MyCtrl"&gt;
&lt;md-select ng-model="select.neighborhood" placeholder="Select Stats"&gt;
          &lt;md-option ng-value="opt" ng-repeat="opt in neighborhoods"&gt;{{ opt }}&lt;/md-option&gt;
&lt;/md-select&gt;
    &lt;span ng-click="change()"&gt; change &lt/span&gt;
&lt;/div&gt;

Javascript:
angular.module('MyApp', ['ngMaterial'])
.controller('MyCtrl', function($scope,$timeout) {
    $scope.select = {neighborhood : ""};
    $scope.neighborhoods = [
        "Flatiron", "Chelsea", "West Village"
    ];
    $scope.change = function() {
        $timeout( function() { 
        $scope.select.neighborhood="C";
        $scope.neighborhoods = [
            "A", "C", "B"
        ];
        }, 150 );
    }
});

The expected result will show a "C"

**Comment by ngraef** [comment]
FYI, changing the selected value was fixed for #1675. The issue here is changing the list of options.

[Demo](http://codepen.io/anon/pen/XbJZBX?editors=101): shows changing the options and changing the selected option to a value in the new list but not in the original list.

**Comment by rjaimel** [comment]
Hi ngraef,

Test with this javascript:

angular.module('MyApp', ['ngMaterial'])
  .controller('MyCtrl', function($scope, $timeout) {
    $scope.select = {
      neighborhood: ""
    };
    $scope.neighborhoods = [
      "Flatiron", "Chelsea", "West Village"
    ];
    $scope.change = function() {
        $scope.neighborhoods = [
          "A", "B", "C", "D"
        ];
        $scope.select.neighborhood = "C";
    };
  });

If you first select "Flatiron" and then press change you'll notice that showing value disappears. If you open the list you'll see that "C" is selected and then value also change to "C".

**Comment by ngraef** [comment]
@rjaimel Right. The displayed value disappears because `change()` assigns a new selected value, but that value isn't yet an option in the `md-select` control so it isn't displayed. And therein lies the root issue: changes to `md-option` aren't immediately recognized by `md-select`.
