### ISSUE TITLE
md-autocomplete: Should create an ellipsis before the x icon

### ISSUE THREAD

**Issue by epelc** [angular/material#2578]
`md-autocomplete` should handle longer text better. Right now it just keeps showing it behind the x icon. Perhaps it could create an ellipsis before the x icon or at least no go behind the icon.

![image](https://cloud.githubusercontent.com/assets/5204642/7350942/3771a5cc-ecd0-11e4-8294-e7106a27506e.png)

**Comment by jgoux** [comment]
I think it's a duplicate of this issue : https://github.com/angular/material/issues/2193

**Comment by epelc** [comment]
@jgoux They are very similar but I'll keep this open to document the text going behind the x.
