### ISSUE TITLE
Wrapping the content of an md-list-item with an md-button brokes the item style

### ISSUE THREAD

**Issue by forcewill** [angular/material#2580]
When wrapping the content of an `md-list-item` with an `md-button` the height of the item seems to be miscalculated, previously it worked fine.

Check

0.8.3: http://jsfiddle.net/forcewill/4Lmk4ejk/   works as expected
master branch: http://jsfiddle.net/forcewill/3f3jd33s/  height seems brokens

**Comment by marcysutton** [comment]
You have to add a custom style to have flexible button heights. Just add `height: auto;` to your buttons and it will work.

**Comment by marcysutton** [comment]
Actually, I think we can change `height: 3.6rem` to `min-height: 3.6rem` and that should sort you out. I'm first looking to see if it has any negative impact.
