### ISSUE TITLE
Material design back button behaviour for dialogs

### ISSUE THREAD

**Issue by ekaitzht** [angular/material#2582]
Hi!

I was reading the material design documentation for diaolog behaviours and I have read this. 

> Dialogs can be dismissed by touching/clicking outside of the dialog or by using the system back button (Android). [behaviour](http://www.google.com/design/spec/components/dialogs.html#dialogs-behavior)

Is this behaviour schedule for a specific milestone?  and as well full screen dialog for mobile?  [full-screen dialogs] (http://www.google.com/design/spec/components/dialogs.html#dialogs-full-screen-dialogs)

Thanks

**Comment by marcysutton** [comment]
There is already a `clickOutsideToClose` option in dialogs that you can set to get this behavior, but it is set to false by default.

**Comment by ekaitzht** [comment]
@marcysutton I don't know if am not understanding properly, but I know that we have clickOutsideToClose in dialog. The problem is on mobile I am using the full-screen size and if I click to the back button we go to the last history page, instead to close the dialog that is the default behaviour in the Material Design specification.

**Comment by epelc** [comment]
Related #1978

I'm not sure what the final decision is but I agree with @gkalpak that it should be handled in the app since there are several different routers. See my answer on the other issue for how you do this using `ui-router`. Perhaps a note should be added to the docs though.

**Comment by gkalpak** [comment]
@epelc, you obviously meant to mention @gustavohenke, I guess ;)

**Comment by epelc** [comment]
@gkalpak Probably I think I wrote that on my phone it likes to auto correct @ mentions.

**Comment by jpdesigndev** [comment]
@marcysutton 

@ekaitzht Is talking primarily about the browser back button here. I think it should be implemented, per spec, here (browser back button is intercepted and the dialog is closed). If everyone agrees, I think we should steer this discussion in that direction.

**Comment by marcysutton** [comment]
Totally agree, the back button should be supported!

**Comment by ekaitzht** [comment]
@marcysutton any roadmap to implement this enhancement?

**Comment by marcysutton** [comment]
@ekaitzht it's in the backlog, I'm sure a PR would be welcome :)
