### ISSUE TITLE
md-button : md-warn and md-accent classes are not correct when ng-disabled

### ISSUE THREAD

**Issue by birdcw** [angular/material#2586]
The text isn't turning grey as with the default and primary classes:
![capture](https://cloud.githubusercontent.com/assets/8897798/7356558/2cc0d808-ece6-11e4-9fa4-63506f02b038.PNG)

http://embed.plnkr.co/Ifd916iJUKzy1JBZkuMW/preview

**Comment by ThomasBurleson** [comment]
@marcysutton - This still appears to be an unresolved bug (see Plunkr using RawGit).
