### ISSUE TITLE
[md-select] [iOS] Ink ripple animation on md-option conflicts with -webkit-overflow-scrolling: touch;

### ISSUE THREAD

**Issue by mjw56** [angular/material#2587]
Hi,

I am using the 0.8.3 mdSelect element on an iOS 8.2 simulator/device. This issue is not replicable in chrome browser.

I am noticing that the ink ripple animation that is on the md-option seems to conflict with the -webkit-overflow-scrolling: touch; CSS property. When you scroll past end of the list, it starts the bouncing but immediately the list will start to glitch and stutter. 

When I put a ```md-no-ink``` attribute on the element however, it removes the ripple effect, but the overflow-scrolling is much smoother with no stuttering.

```html
<md-select placeholder="Pick" ng-model="test">
  <md-option md-no-ink value="1">One</md-option>
  <md-option md-no-ink value="2">Two</md-option>
</md-select>
```

Thanks

**Comment by ThomasBurleson** [comment]
Ripples were fixed in ^ v.0.11.0-rc1
