### ISSUE TITLE
md-list 3-line list item should have icon top align with the text

### ISSUE THREAD

**Issue by asans** [angular/material#2589]
According to [Material List Specs](http://www.google.com/design/spec/components/lists.html#lists-specs), the icon/avatar icon should top-align with the text.

Currently, the demo shows the following:

![current design](https://cloud.githubusercontent.com/assets/17964/7359222/e7443076-ecf0-11e4-9300-7db92ea2818b.jpg)

The specs shown:

![specs](https://cloud.githubusercontent.com/assets/17964/7359223/eec85322-ecf0-11e4-9808-f6373588ddc3.jpg)

Specs specifically states that:

> Top-align icon with primary text.

**Comment by asans** [comment]
To give a better idea, here's a screenshot of what it looks like when using a 3-line item text:

![screenshot 1](https://cloud.githubusercontent.com/assets/17964/7359329/f22cde56-ecf1-11e4-9d82-19b0a77fb0c7.jpg)

The secondary button looks to be top-aligned, but the primary icon (left one) is centered instead of top aligned.

**Comment by marcysutton** [comment]
@asans what markup are you using for that second demo? Did you change `md-2-line` to `md-3-line`?

**Comment by asans** [comment]
@marcysutton I noticed that md-2-line is now top-aligned as well, which should not be the case based on the Material design specs.  

Only md-3-line should be top-aligned.  md-2-line should continue to be center-aligned vertically.
