### ISSUE TITLE
Open Dialog on iPhone simulator crashes mobile Safari

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#259]
And the dialog is not shown.

![image](https://cloud.githubusercontent.com/assets/210413/4221401/83609dba-3909-11e4-971a-7d2b07d6e4da.png)

**Comment by Purushothama-VS** [comment]
Hello team,

am loading a website(uses ng-material dialogs) in QT browser control, it crashes everywhere when i try to load any dialogs. In firefox and IE it works fine. Need help in this regard.
