### ISSUE TITLE
layout of md-autocomplete with floating label broken

### ISSUE THREAD

**Issue by jgoux** [angular/material#2593]
Hi,
on the master, the layout of md-autocomplete seems broken with a floating label.
The "clean" button is misplaced and there is a padding/margin between the bottom line of the input and the list of suggestions.
Here is a codepen demonstrating the issue : http://codepen.io/jgx/pen/pJvKQz
You can also see the issue on the doc (last example) : https://material.angularjs.org/#/demo/material.components.autocomplete

**Comment by TalPasi** [comment]
+1
