### ISSUE TITLE
md-switch on md-list-item toggles all the switches in the list items

### ISSUE THREAD

**Issue by DEVI-GHAYATHRI** [angular/material#2594]
When a switch is toggled in any item on md-list-item, the change reflects in all the switches of items on md-list-item

**Comment by marcysutton** [comment]
Hi, can you provide a Codepen or Plunker showing your issue?

**Comment by TylerDixon** [comment]
I've encountered this same problem, [here's a quick Codepen](http://codepen.io/anon/pen/Xbmwdy).

**Comment by alcfeoh** [comment]
+1, that issue is annoying

**Comment by joeyperson** [comment]
Switches should work independently on click in a similar way as they do currently with keyboard.
