### ISSUE TITLE
md-list feature request : multiple secondary items

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2595]
I have a need to display multiple checkboxes per item in an md-list. At present the checkboxes remove the text and align them all to sit on top of each other. Please allow for multiple checkboxes

**Comment by rschmukler** [comment]
@ThomasBurleson can you coordinate with the UX team on this? Pseudo-duplicate of part of #2819, specifically the multiple checkboxes in a list item. Would be good to get clarification on UX's stance.

**Comment by hodeyp** [comment]
an example of this feature in action using google inbox, I think this would be a super useful feature to add...

![screen shot 2015-06-04 at 19 29 38](https://cloud.githubusercontent.com/assets/1916471/7991470/3b0fff56-0af0-11e5-98e1-918795e9267f.png)

**Comment by miclaus** [comment]
+1

**Comment by offminded** [comment]
+1

**Comment by JuHwon** [comment]
+1

**Comment by AleksueiR** [comment]
+1

**Comment by eXaminator** [comment]
+1

**Comment by george3447** [comment]
+1

**Comment by tiago3613** [comment]
+1

**Comment by asm0dey** [comment]
:+1:

**Comment by douwevdijk** [comment]
+1

**Comment by srikrishnacj** [comment]
+1

**Comment by iskuda** [comment]
+1

**Comment by colinskow** [comment]
+1

**Comment by ThomasBurleson** [comment]
We recognize that this enhancement is an important feature improvement. With our push for a v1.0 MVP, this simply must wait until a post 1.0 release. Thank you.

**Comment by miclaus** [comment]
In the meantime one could position the buttons right to the list items and style accordingly and maybe use `md-ink-ripple` for more fancy .

**Comment by sisu4u** [comment]
+1

**Comment by miclaus** [comment]
#5958 seems good, but isn't this solved already ?

**Comment by 8cells** [comment]
+1

**Comment by fincha** [comment]
+1

**Comment by 7ebra** [comment]
+1

**Comment by darkmavis1980** [comment]
+1

**Comment by jaggedsoft** [comment]
+1

**Comment by timmyrosen** [comment]
+1
