### ISSUE TITLE
mdGridItem ngRepeat animations not consistent.  

### ISSUE THREAD

**Issue by acbenny** [angular/material#2598]
Hi,

I was trying out animations with md-grid-list with a ng-repeat on the grid item. Just trying out some basic transition to avoid abrupt updates to the grid.

But the animations are very inconsistent. sometime removing a middle tile triggers a move animation but if I put that tile back and remove it again, the animation no longer works.

Can someone please explain this behavior. Apologies if i'm missing something basic.

Plunkr: http://plnkr.co/edit/DUSqqOhxM0PgZpuv9Bie?p=preview

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
