### ISSUE TITLE
mdInput: focusing floating label makes mdInputContainer grow (only with icon)

### ISSUE THREAD

**Issue by xavikortes** [angular/material#2599]
Hi,
at focusing on a mdInput with floating lable and icon, mdInputContainer height grow. It is not happening with the input without icon.

You can see an example of this bug at input demo, in the last container (inputs for name and email)
https://material.angularjs.org/#/demo/material.components.input

No screenshoots attached because bug is imperceptible at images.

Thanks.

**Comment by ThomasBurleson** [comment]
This feature was provided to allow the vertical spacing between multiple rows of md-input-container to adjust and maintain gaps correctly. You can easily disable this with css to stop the transitions.
