### ISSUE TITLE
mdTooltip: tooltip is not hidden after md-button becomes disabled

### ISSUE THREAD

**Issue by Frank3K** [angular/material#2602]
In Firefox 37.0.2 (Ubuntu 15.04 and Windows 8.1) and Internet Explorer 11 (Windows 8.1) tooltips are not hidden after the button on which the tooltip is defined gets disabled. The tooltip persists even when other elements get focused (e.g. by user clicks). 

In Chrome 41 this issue does not occur.

Demo using [v0.9.0-rc2-master-02a4af5](https://rawgit.com/angular/bower-material/c370de75d59b3f40a015a7afdb5ba28c794e2d48/angular-material.js) (current latest) on [plunker](http://plnkr.co/edit/ssdDVwCVYWEJNPacvGJm?p=preview).

**Comment by anish274** [comment]
same issue I am facing

**Comment by SanderElias** [comment]
[Confirmed this an issue](http://codepen.io/SanderElias/pen/qOyYrE?editors=101) on FF40 windows
the above codepen fails on FF.

**Comment by ryan0122** [comment]
I am facing this issue on OSX 10.11 using Chrome 46.0.2490.80

**Comment by princemaple** [comment]
Same issue.

**Comment by SanderElias** [comment]
I have just tested this against https://github.com/angular/material/commit/87ad6dcd982e6bf5254e991b0287c39923c5e42e and the issue does not apear anymore. I will retest once this pr has landed.
