### ISSUE TITLE
Chip - run code on select

### ISSUE THREAD

**Issue by JohnAReid** [angular/material#2605]
I am having a problem with the chip display when a chip is selected -  basically I want to run some code when the chip is selected - so I assumed I have to use ng-click but if I use that the text in the chip is selected instead of the whole chip.
![chip](https://cloud.githubusercontent.com/assets/7714810/7380753/950c6ad4-edf5-11e4-817c-64e7ed251036.png)
![chip1](https://cloud.githubusercontent.com/assets/7714810/7380754/9511559e-edf5-11e4-88ec-891dfc99dad6.png)
I can select the chip by clicking outside the text area - but this is less than ideal.

Plunker used is: http://plnkr.co/edit/dCUEvDf1R8Y6xLKx1FaI

**Comment by ThomasBurleson** [comment]
Related to #2577

**Comment by typotter** [comment]
the reason that only the text is selected is because adding ng-click to the chip template steals the click from going higher to the chip element proper. adding an on-select event/expression seems reasonable.
