### ISSUE TITLE
Overflow-x:hidden in md-input-container creates scrollbars for long validation messages

### ISSUE THREAD

**Issue by wlingke** [angular/material#2606]
What is the purpose of the overflow-x:hidden? If you write any long validation messages and they go over the container length, it looks odd like so:

![capture](https://cloud.githubusercontent.com/assets/3145536/7382433/9ede7020-edc3-11e4-8dc8-739cdde06845.PNG)

**Comment by marcysutton** [comment]
This was removed with f1df6dc09c20635d42ffaada32ae2f036666a5ba, though I'm not sure why it was there to begin with.
