### ISSUE TITLE
md-chips: Focus state is triggered incorrectly

### ISSUE THREAD

**Issue by chrisguerrero** [angular/material#2607]
I just updated to v0.9.0rc3 and noticed that the `.md-focused` class is applied to the wrong element.

The focus state is applied properly if I press ctrl or cmd while focussed on the element.

**Comment by marcysutton** [comment]
Can you provide some more details? Which browser, and which demo? The `.md-focused` class is applied to `md-chip` when I click on it or use TAB + arrow keys. It looks correct.

**Comment by chrisguerrero** [comment]
I'm using Chrome Version 42.0.2311.135 (64-bit)

It's the Custom Inputs section of the demo

**Comment by marcysutton** [comment]
I'm still not seeing it. Some screenshots of the focused state and the Element inspector open would help narrow it down.

**Comment by chrisguerrero** [comment]
I'm not able to take a screenshot because pressing the command key while focused in the input sets the .md-focused class correctly.  I'll outline the steps to reproduce below:

1. Click first md-chips element in the "Custom Inputs" section (<input> is now focused, but .md-focused class is not added to <md-chips-wrap> element)
2. Press <kbd>Tab</kbd> to move to next md-chips element in the "Custom Inputs" section (second <input> is now focused, but .md-focused class is added to the first <md-chips-wrap> element)
3. Press <kbd>Tab</kbd> again to move to third md-chips element in the "Custom Inputs" section (third <input> is now focused, and no <md-chips-wrap> elements have .md-focused class)

I am seeing this behavior in Firefox as well.

**Comment by marcysutton** [comment]
Ok, I see what you mean now–it's the `<input>` element that doesn't focus correctly. In fact, it's actually quite buggy. Thanks for the details, they helped a lot.

**Comment by topherfangio** [comment]
@chrisguerrero A lot has changed with the chips recently, and I can't seem to reproduce this issue in [0.10.1](https://material.angularjs.org/0.10.1/#/demo/material.components.chips) or [master](https://material.angularjs.org/HEAD/#/demo/material.components.chips).

Can you verify if this has been fixed or if it's still an issue?

If it is still an issue, can you provide the instructions again? I don't see any existing chips in the Custom Inputs demo, so I think the demo itself may have changed.

Thanks!

**Comment by chrisguerrero** [comment]
@topherfangio I do still see the issue in 0.10.1 and master, and the "Custon Inputs" demo is still there. It's one of the top level sections with a blue header, alongside "Basic Usage", "Contact Chips" and "Static Chips". The "md-focused" class is still being applied incorrectly, and the steps to reproduce are the same as my comment from 4/29.

**Comment by topherfangio** [comment]
@chrisguerrero My apologies for making you comment again, I think I misread your instructions; I thought you were saying to click an existing chip, not the input, which is why I was confused.

I definitely see the issue now and will look into it :-)
