### ISSUE TITLE
MD-Chips

### ISSUE THREAD

**Issue by JohnAReid** [angular/material#2610]
I like the new chips - but I found it is only just usable on a touch screen -  could there be an option to make the chips bigger (i.e. extra height or padding).  Also could the space between each chip be made larger so that it is easier for people with larger fingers to tap the intended chip.

**Comment by ThomasBurleson** [comment]
You can modify the CSS per your needs.

**Comment by JohnAReid** [comment]
@ThomasBurleson Thanks for the reply but I am finding hard to change the style  for example height to 5rem - I am not sure where it needs changing I assumed the md-chip-template but this has not affect.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr with your issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/jgx/pen/JogKrQ. 
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by JohnAReid** [comment]
Here is an example of trying to change the height of the chip to make it larger - but to be honest it just shows I do not know what I am changing as none of the styles used has any effect.  

http://plnkr.co/edit/wqfmwaMt0RgOFYO5YGDj

**Comment by janesconference** [comment]
Hi, @JohnAReid, does this forked plunkr do what you want? http://plnkr.co/edit/1Ct3I5mH6P7wn0OWwaLP?p=preview

I just added the `.height-chips` to your chips and these rules to the css:

```
.height-chips .md-chips .md-chip {
  height: 60px;
  line-height: 60px;
  border-radius: 30px;
}

.height-chips .md-chips .md-chip .md-chip-remove {
  height: 60px;
}
```

Feel free to play with the values until you get your optimal size.

**Comment by JohnAReid** [comment]
Thanks @janesconference that works well!

**Comment by milad-kh** [comment]
hi @ThomasBurleson,
is it possible to drag and re-arrange mdchip in a row ? like the one in jquery UI
sorry for my week english
