### ISSUE TITLE
md-select in md-input-container is displayed before the label, not after

### ISSUE THREAD

**Issue by jfbenckhuijsen** [angular/material#2611]
When i put a md-select inside an md-input-container, the label is put below the md-select, not after as expected. The cause is by md-select not having an `order:2` as is the case for regular md-input fields. See the screenshot below for the situation, I manually adapted the style of md-select to include `order: 2` to fix this issues

Test code:
```html
<md-content md-theme="docs-dark" layout-padding layout="row" layout-sm="column"> 
		<md-input-container> 
			<label>Title</label>
			<md-select placeholder="Pick" ng-model="someVal">
				<md-option value="1">One</md-option>
				<md-option value="2">Two</md-option>
			</md-select>
		</md-input-container> 
	</md-content>
```

Potential fix (works for me by adding this to my custom CSS)
```css
md-input-container md-select {
	order: 2;
}
```

![image](https://cloud.githubusercontent.com/assets/6218066/7388299/4f2a6858-ee64-11e4-807e-4c89de6810ec.png)

**Comment by jfbenckhuijsen** [comment]
Hmm, issue seems to be a little more complex. When I put an md-select in an md-input-container, the resulting DOM tree differs from the "normal" case.

(both HTMLs are copied from the DOM tree in Chrome)

Inside an input-container:
```html
<md-input-container class="md-docs-dark-theme"> 
     <label>Title</label>
    <md-select ng-model="someVal" class="ng-pristine ng-untouched ng-valid md-default-theme" tabindex="0" role="combobox" id="select_006" aria-haspopup="true" aria-expanded="false" aria-labelledby="select_label_001" aria-invalid="false">
        <md-select-label class="md-select-label md-placeholder" id="select_label_001">    
            <span>Pick</span><span class="md-select-icon" aria-hidden="true"></span>
        </md-select-label>
    </md-select>
    <div class="md-placeholder">Pick</div>
</md-input-container>
```

Outside the input-container
```html
<md-select placeholder="Pick" ng-model="someVal" class="ng-pristine ng-valid md-default-theme ng-touched" tabindex="0" role="combobox" id="select_00A" aria-haspopup="true" aria-expanded="false" aria-labelledby="select_label_002" aria-invalid="false" aria-owns="select_menu_007">
    <md-select-label class="md-select-label md-placeholder" id="select_label_002">
        <span>Pick</span><span class="md-select-icon" aria-hidden="true"></span>
    </md-select-label>
</md-select>
```

Differences:
* Inside version lost it's placeholder attribute
* Inside version gains a ```<div class="md-placeholder">```
* Resulting styling is way off

It looks like the md-input-container interprets the placeholder attribute of the md-select as the placeholder attribute on an md-input.

**Comment by ThomasBurleson** [comment]
The `md-select` is currently **not** supported within `md-input-container`.
What is the goal: And md-select with floating label? If that is the case, perhaps we should enhance md-select.

**Comment by jfbenckhuijsen** [comment]
Ok, disregard the last comment (just delete it, was still on 0.8.3... behind a corporate proxy, so bower update isn't easily doable :S). The order issue remains, and there are some styling issues in the placement of the floating-label.

The main goal is to use the md-select in and md-input-container, so it has the same styling as a regular other part of the input-form. The same goes btw for md-checkbox, for which the styling seems a bit off.

**Comment by ThomasBurleson** [comment]
You should use:

* md-input-container  for **text input** controls,  with placeholders and/or floating labels.
* md-select for **select** controls
* md-autocomplete for **search & select** controls
