### ISSUE TITLE
md-list pushes wrapper div to top as it grows

### ISSUE THREAD

**Issue by ivanhtp** [angular/material#2612]
I tried my best to identify the source of the problem but it was hard.
I have a list inside a md-conteiner inside a div. Something like div wrapper>md-content>md-list> n md-list-items.
If the list is empty, with no list items, the papers behave ok, but as the list grows, my div wrapper pushes all the content to top.

The problem is easy to understand with the image below.
![angular](https://cloud.githubusercontent.com/assets/126082/7391250/ec9bc6a4-ee55-11e4-8416-7ca43aa17996.jpg)

The real screenshots:

1. List full (pushing and sticking to top toolbar)
![1- list full pushed to top](https://cloud.githubusercontent.com/assets/126082/7391329/bffff2ea-ee56-11e4-9521-f74e4e935aa7.png)

2. Some items removed, a little bit better
![2- list with less items](https://cloud.githubusercontent.com/assets/126082/7391327/bff5be1a-ee56-11e4-9445-4b77391ce950.png)

3. Just one item. Looks good
![3-just one item](https://cloud.githubusercontent.com/assets/126082/7391328/bff667d4-ee56-11e4-9fb0-ec5381fa687f.png)

**Comment by ThomasBurleson** [comment]
@ivanhtp - **great** bug report. Thank you.

**Comment by rschmukler** [comment]
@ivanhtp Please submit a codepen / jsfiddle with some example markup so I can help you.

Here is an example [codepen](http://codepen.io/rschmukler/pen/bddZZG) that seems to do what you want.

**Comment by ivanhtp** [comment]
@rschmukler here it goes
http://codepen.io/anon/pen/WvQZzJ

The good news, reproducing the problem on your codepen helped me find it origin.
Bad news, I don't know if what I am doing is wrong.

The problem is: in my application I the md-toolbar is wrapped by 2 divs. This is because I have a very clean main.html containing ng-includes to external partials and the toolbar is one of these.

I could remove one of these divs declaring my controller on the include page (main), but it doesn't solve the problem, and anyway, should the md-toolbar behave this way in such situation?

![Situation](https://cloud.githubusercontent.com/assets/126082/7486881/06a9244c-f383-11e4-9e72-5bc59f8b62d8.jpg)

**Comment by rschmukler** [comment]
@ivanhtp sorry on the delay. Check out [this codepen](http://codepen.io/rschmukler/pen/eNdZqM). I applied a `flex` attribute to `<div  layout="row" layout-align="center start" layout-margin flex >`. The issue was that flexbox was shrinking the toolbar div to make them both poorly fit. By specifying flex on this element, we give the toolbar the full height it needs, and then shrinking this container as needed.

Let me know if this will work for your use case.

**Comment by ivanhtp** [comment]
Oh man,

So the problem was in my case only. Just tested and worked well. With this I think is not framework problem at all. 

Thank you and I'm reaally sorry to take your time on this, Ryan!

**Comment by rschmukler** [comment]
@ivanhtp no problem! Good luck!
