### ISSUE TITLE
md-chips: Enter key removes first index from model when <md-chips> is wrapped by <form> element

### ISSUE THREAD

**Issue by chrisguerrero** [angular/material#2617]
When nested inside a form element, the md-chips directive is removing the first index from its model when the <kbd>Enter</kbd> key is pressed.

To replicate, using the first example from the "Custom Inputs" section of the docs:

```html
<pre>{{ctrl.numberChips|json}}</pre>
<form>
    <md-chips ng-model="ctrl.numberChips">
      <input type="number" placeholder="Enter a number">
    </md-chips>
</form>
```

When multiple md-chips elements are present, pressing <kbd>Enter</kbd> affects the models of other md-chips elements as well.

I was banging my head against the desk for a while on this one, any help is appreciated!

**Comment by marcysutton** [comment]
One possibility is the nested remove button is missing `type="button"`, so it thinks it should submit on enter. Which actual submit buttons should do, but not the chip delete button.
