### ISSUE TITLE
mdGridList - Should support the secondary action and the text truncate

### ISSUE THREAD

**Issue by carab** [angular/material#2620]
Hello everyone,

First, thanks again for this great UI framework which improves at every release !

So, according to the [Material Design Specs](http://www.google.com/design/spec/components/grid-lists.html#grid-lists-specs), the Grid List component should allow us to add an icon (or maybe a small text such as a number) used to trigger a secondary action.

I didn't find it in the current implementation, but maybe it is planned ? 

Also, the specs say that the text should be truncated if too long (both lines), but it is currently not the case.
It's possible by adding the following to the h3/h4, but maybe it should be native in Angular Material ?

```
text-overflow: ellipsis;
white-space: nowrap;
overflow: hidden;
```

Thank you for your consideration ;)

**Comment by carab** [comment]
I also forgot to say that the header/footer have a different heigh based on the number of lines (1 or 2).

Thanks ;)

**Comment by Splaktar** [comment]
The styles above do help achieve this a little on Chrome, but the behavior is vastly different on Firefox (everything gets gigantic). That said, even on Chrome the behavior of adding a horizontal scrollbar seems more desirable. 

Unfortunately, Firefox does not add a horizontal scrollbar for something like an md-content that has really long URLs in it. This causes certain items with a flex="45" to explode their width way beyond that 45% screen size.

Now is this an issue with `md-content` not doing the right things on Firefox or is this just an issue with Firefox? I haven't had time to investigate that yet.
