### ISSUE TITLE
Toolbar icons (SVG) not the right color

### ISSUE THREAD

**Issue by wcjr** [angular/material#2622]
http://plnkr.co/edit/mtuOQb?p=preview

md-icon's, within a toolbar, should rely on the foreground color defined by md-toolbar instead of the primary black being used in the plunkr.

**Comment by wcjr** [comment]
Thanks Robert!  Can I assume this will be in the next 0.9.0-rc?

**Comment by robertmesserle** [comment]
Yep, should be very soon

**Comment by wcjr** [comment]
@robertmesserle thanks again for the fix, the icons look great in the app bar's tool bar after today's release.  I noticed an icon in a sidenav's toolbar did not benefit from your fix...should your fix have also worked for toolbars in the sidenav's?

**Comment by ThomasBurleson** [comment]
Issue reopened with #2707
