### ISSUE TITLE
mdChips: Problem with mdAutocomplete and md-min-length="0"

### ISSUE THREAD

**Issue by umidbekkarimov** [angular/material#2623]
I wanted to open chips autocomplete on focus, so the only way i found is was to set `md-min-length` to `0`, that solved one problem but created another.

If i pick result from autocomplete while input is empty, it fills with result text.

[Codepen](http://codepen.io/umidbekkarimov/pen/zGGqjG?editors=101) example.

![screencast](https://cloud.githubusercontent.com/assets/4734297/7406118/d9b24c22-ef16-11e4-911b-8c358f57846f.gif)

**Comment by brtnshrdr** [comment]
+1

**Comment by shtaked** [comment]
+1

**Comment by vprenner** [comment]
A solution that worked for me was adding this to md-autocomplete:
md-selected-item-change="vm.searchText = ''"
vm.searchText is the thing set in md-search-text

**Comment by Mctalian** [comment]
+1

**Comment by Mctalian** [comment]
@vprenner that solution didn't seem to work for me :disappointed:

**Comment by nestorneto** [comment]
+1

**Comment by rgolea** [comment]
+1

**Comment by inetfuture** [comment]
+1

**Comment by typotter** [comment]
Hi Folks, 
I am unable to reproduce this bug. There have been some changes in chips and md-autocomplete which may have fixed this.
@umidbekkarimov, could you please confirm?

**Comment by jelbourn** [comment]
Status: need to check if this still exists

**Comment by umidbekkarimov** [comment]
Hi, @typotter issue fixed, 

Angular 1.3.17  [codepen](http://codepen.io/umidbekkarimov/pen/zGGqjG?editors=101)
Angular 1.4.4 [codepen](http://codepen.io/umidbekkarimov/pen/JdVQqm?editors=101)

P.S. sorry for delay
