### ISSUE TITLE
mdAutocomplete: Creates a lot of empty ul.md-autocomplete-suggestions tags

### ISSUE THREAD

**Issue by umidbekkarimov** [angular/material#2624]
`mdAutocomplete` doesn't remove child suggestions dropdown on `$destroy`. 

![screenshot](https://cloud.githubusercontent.com/assets/4734297/7406295/9b2dfb9c-ef19-11e4-9c6e-10efa831b43d.PNG)

And also this will fix problem when `autocomplete dropdown` keeps being visible after`autcomoplete` removed from DOM, (Can`t dublicate it in codepen, but this problem occures in my project)

**Comment by uriva** [comment]
+1

**Comment by Londovir** [comment]
Possibly related to this is that autocomplete can pile up numerous duplicated entries in the `aria-status` element as well. Use the demo site, go to the "Basic Usage" demo, and type in 'a', backspace, 'a' again, backspace, etc, multiple times, then look at the developer console. There will be a number of `<p>` children that keep piling up.

They appear to get destroyed if you attempt to make an autocomplete entry which has no match, as this probably resets the collection $mdAutocompleteCtrl.messages, but I would expect that every time you type (or delete) a character into the autocomplete linked box it would clear that collection to only contain the most recent appropriate message.

**Comment by Londovir** [comment]
Followup: I might have duplicated something similar to what you are describing, at least in terms of `ul` element still on the screen. Under IE11, a basic autocomplete is, for me, breaking badly as opposed to Chrome. I am baffled at what IE11 is doing to it at the moment. See this CodePen: http://codepen.io/londovir/pen/GJpmmr

When viewing that CodePen in Chrome, the autocomplete essentially works as I'd expect: Type or click in the box and it expands the list, click on an item and it selects that item into the input box. Although you have to click out to move the focus off and then click back in to pop open the list a second time, I'm okay with that for now and it works.

In IE11, though, it's broken beyond measure. If you click within the box, the list appears, but clicking an item does an odd flash, redraws the list again farther to the left, and nothing is selected. If you double click the item, it appears to get selected as expected.

Furthermore, at random times (but happening often), even when the list appears to disappear, if I click in the empty whitespace below the input box, the list will open once again. It's as though the list is still there in the rendered page (albeit invisible) and accepting mouse events. Not sure. It does seem as though the layout height in IE11 is coming up at -1, which perhaps is causing the problem.

If I use the Material demo page for mdautocomplete with IE11, go to the "Basic Usage" demo, click once in the box to expand the list of states, and then click to the right in empty whitespace on the page, the list of options empties of all text, but expands in height to cover everything below it. See picture below:
![image](https://cloud.githubusercontent.com/assets/11982575/7480278/7c7b07e2-f335-11e4-8c81-0ffc9bc8d5ef.png)

I feel like this is all related to the `ul` issue(s) you noted above in some way.
