### ISSUE TITLE
md-autocomplete : Duplicates in a repeater are not allowed

### ISSUE THREAD

**Issue by lillylykho** [angular/material#2625]
Hi! 
In my application I got an error on ng-repeat of autocomplete:

    Error: [ngRepeat:dupes]: Duplicates in a repeater are not allowed.

I wanted to use `track by` expression, but it not supported (if I'm not fault).
How about to implement this?

 And Big Thanks for your work guys!

**Comment by lillylykho** [comment]
Hi! 
What's happening with this? Anybody?
@robertmesserle

**Comment by robertmesserle** [comment]
@lillylykho Can you provide more explanation for your use-case?

@jelbourn We should discuss this once we have a use-case.

**Comment by lillylykho** [comment]
Sometimes, in list of searched results I receive two identical objects and I get this error: 

    Error: [ngRepeat:dupes]: Duplicates in a repeater are not allowed.

So, I need the ability to control `ngRepeat` via `track by`

Thanks

**Comment by robertmesserle** [comment]
Out of curiosity, do you WANT the same result to appear twice?  In either
case, I do plan to look into this, just curious.

**Comment by lillylykho** [comment]
it is strange and curious, but in some cases - yes I need it

**Comment by lillylykho** [comment]
And, thanks for response!
