### ISSUE TITLE
Cannot read property 'offsetHeight' of undefined when using an empty mdSelectLabel

### ISSUE THREAD

**Issue by Ugoku** [angular/material#2627]
My HTML:
```
<md-select ng-model="someVar.users" multiple placeholder="Select one or more user(s)">
	<md-select-label ng-bind="getUserNames()"></md-select-label>
	<md-option ng-repeat="user in users" ng-value="user.ID">{{user.name}}</md-option>
</md-select>
```
The `mdSelectLabel` is empty, so it takes the `placeholder` value from the `mdSelect` by default. I use `ngBind` to get a comma-separated list of selected `user.name`s.
This gives the following error: `TypeError: Cannot read property 'offsetHeight' of undefined` on line 7828 of `angular-material.js` (`SelectDirective.mdSelectCtrl.setLabelText`)

Removing the `placeholder` value from the `mdSelect` and using that as `mdSelectLabel` text works (i.e. gives the same result without an error), but then the placeholder text is black instead of light gray.
This worked fine in 0.8.3 but broke in 0.9.0 RC1, so this not related to d931c0d237777c0197464277a5d8096bc3cbd698. The error still occurs in RC2 and RC3.

Changing the code on that line from `if (target[0].offsetHeight > lineHeight) {` to `if (target.offsetHeight > lineHeight) {` seems to solve the problem (`target[0]` occurs on line 7821 as well)
I could submit a PR, but you probably know better if this really is the proper fix or not.

**Comment by Ugoku** [comment]
Update: the error has been replaced with a different error in 0.9.0 : `Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null` on line 8571

**Comment by Ugoku** [comment]
Update: in the current master branch (7aff8ffef66c33e74db14a0d75a7f1c8d8b5d501) the later error is present but on a different line: `Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null` on line 8629 (`animateSelect` function).

**Comment by Ugoku** [comment]
I've been able to fix this by changing line 8762 in the latest master (926ca29f1c00b65e2d269ce363ab8b6a96acb215) from:
`targetNode = opts.target[0].firstElementChild.firstElementChild, // target the first span, functioning as the label`
to
`targetNode = opts.target[0].firstElementChild.firstElementChild || opts.target[0].firstElementChild, // target the first span, functioning as the label`
I'd be happy to submit a PR, but I'm not sure if this is a proper fix in all cases, or just in my case.

**Comment by Ugoku** [comment]
Still present in latest master (4623a9df5e1c388dae35b78fe9d7d02b165433b0), fix mentioned above still works for me, now on line 10143.

**Comment by rschmukler** [comment]
@Ugoku `md-select-label` has been removed and the joining you are talking about is handled automatically. Let me know if this resolved your issue

**Comment by Ugoku** [comment]
Haha, hmm, as of last Friday I'm actually not using it in this way anymore... I'll see if I can revert my changes to confirm that it works now.
