### ISSUE TITLE
md-select does not inherit custom theme

### ISSUE THREAD

**Issue by haneev** [angular/material#2628]
Using a `md-select` in a `md-theme` section, does not inherit the theme. For example, using a dark theme based on light-green, `md-select` is using the default theme (blue) instead of the light-green.

See this codepen: http://codepen.io/anon/pen/RPPoZg

The inputs are using the correct theme, however md-select is using the default theme. This is not expected.

**Comment by mprentic-harris** [comment]
Looks like a dup of #2483?
