### ISSUE TITLE
Pseudo-element selector de-styling

### ISSUE THREAD

**Issue by denjello** [angular/material#2633]
For an example of what I mean, there is the annoying dotted border (`::-moz-focus-inner`) on the `button.md-button` element that appears on click / focus of buttons in Firefox.

Here is a CSS fix that I use to "de-style" the pseudo-element:

```
button.md-button::-moz-focus-inner
{
  border: 1px dotted transparent!important;
}
```

Unfortunately the list of pseudo elements that are browser specific are quite long... Is there an effort underway to quelch them in ngMaterial, at Google or anywhere?

(btw. here is a nice resource list > https://gist.github.com/afabbro/3759334 )

**Comment by marcysutton** [comment]
It's only annoying to some users, but it does conflict with the Material Design style. The one you show is related to keyboard focus so it can easily be handled. Other pseudo styles would have to be considered on a case-by-case basis.

**Comment by denjello** [comment]
I found another button class where this happens:
`button.md-chip-remove::-moz-focus-inner`

which could be reduced to `button::-moz-focus-inner`

**Comment by marcysutton** [comment]
It is possible to change this behavior, but until focus styles are resolved/enhanced for colored & raised buttons I am going to wait as it effectively removes the only visible focus style many users will depend on.
