### ISSUE TITLE
mdTooltip - layout issue on dynamic tooltip text while it's visible

### ISSUE THREAD

**Issue by theunexpected1** [angular/material#2639]
Dynamic tooltips don't re-position themselves if they are already visible while changing text. Would be essential for them to re-render, instead of hide & show again as a hack.

![gif](http://zippy.gfycat.com/RegularSecondhandHornet.gif)

**Comment by marcysutton** [comment]
Not totally related to tooltips, but what is the interaction to update the text in the tooltip in your screencast? This looks potentially confusing as a user.

**Comment by theunexpected1** [comment]
Let me add a snippet, for illustrative purpose, to show change in tooltip content

	<md-button ng-click="isCreatingPost = !isCreatingPost">
		<md-tooltip md-direction="left">
			{{isCreatingPost ? 'Cancel' : 'Create a meeting'}}
		</md-tooltip>
		Create or cancel
	</md-button>

So, clicking the button will toggle new-post / cancel-new-post and in that case tooltip will change, and vice-versa. Is this an ideal scenario, or is there another recommended way to have a dynamic tooltip?

**Comment by redyyu** [comment]
md-tooltip show incorrect position if md-button fab is in side ng-include 



![screen shot 2015-05-21 at 6 31 47 pm](https://cloud.githubusercontent.com/assets/724821/7747198/02afa784-ffeb-11e4-81a7-5b8a69df84c9.png)


==========

I have a common button include by ng-include

Button Template

```javascript
md-button.md-warn.md-hue-2.md-fab.md-fab-bottom-right.fixed(
  aria-label="{{_('Delete')}}"
  ng-click="trash()"
  )
    md-tooltip(
    md-direction="top"
    md-autohide="true"
    )
      | {{ _('* Select from list then click trash to delete.') }}
    md-icon(
    md-svg-icon="action:ic_delete_24px"
    )
```

ng-include

```javascript
ng-include(
  src="'blueprints/common/views/trashbar.tmpl.html'"
  )
```

**Comment by redyyu** [comment]
tooltips show wrong position while windows resized. (big -> small)

![screen shot 2015-05-21 at 7 08 33 pm](https://cloud.githubusercontent.com/assets/724821/7747479/7460ab38-ffed-11e4-879f-e7650516b340.png)

**Comment by Darksoulsong** [comment]
So, this was deprecated. Is this going to be fixed? Is there a workaround?
