### ISSUE TITLE
mdInput with icons: fields disappear on scroll in iOS Safari

### ISSUE THREAD

**Issue by marcysutton** [angular/material#2640]
Similar to https://github.com/angular/material/issues/2539 but only on inputs with icons. When scrolling the page on https://material.angularjs.org/#/demo/material.components.input in mobile Safari, the icon inputs at the bottom disappear on scroll and sometimes stay that way. It could be related to absolute positioning inside of `display: flex`, but I was unable to find a fix after an initial round of debugging.

Tested in iPhone 5 with iOS 8.0.2.

![material icon inputs hidden](https://cloud.githubusercontent.com/assets/1045233/7420168/2447cbb4-ef2f-11e4-85d2-058b378cac44.png)

**Comment by ThomasBurleson** [comment]
Issue appears to be md-contents styles of `-webkit-overflow-scrolling: touch;`. A simple override to `-webkit-overflow-scrolling: auto;` resolves this issue. I suggest that this is a custom usage only not applied globally to md-content

**Comment by hughred22** [comment]
This also fix some screen flicking when there is absolute overlay on top of flex element when the scroll shrink header bar pass by. But it just feel stick when disable the iOs momentum scrolling. Is there a way to have the best of both world?
