### ISSUE TITLE
mdCheckbox: does not wrap text correctly...

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2642]
Checkbox and radio text don't wrap correctly. 
The left-padding should remain on subsequent lines:

![0](https://cloud.githubusercontent.com/assets/210413/7421686/6262a348-ef4c-11e4-8496-79c68983105f.png)

**Comment by erwinmombay** [comment]
@ThomasBurleson can you clarify the part where you mentioned "radio", i don't see this same problem with radio buttons. Thanks.

![screen shot 2015-05-08 at 4 16 36 pm](https://cloud.githubusercontent.com/assets/354746/7547223/bdf458f8-f59d-11e4-9445-2b0e2036056a.png)

**Comment by ThomasBurleson** [comment]
So both the RadioButton 'square' and Checkbox 'square' should be TOP-LEFT aligned (instead of the CENTER-LEFT) aligned.

**Comment by clshortfuse** [comment]
This breaks the ability to center a checkbox with no text.

Here's the proper fix:

md-checkbox {
  padding-left: 0px; //was 18px
}

md-checkbox .md-label {
  margin-left: 28px; //was 10px
}

**Comment by ThomasBurleson** [comment]
@clshortfuse - please open a new issue with a demo. Thx
