### ISSUE TITLE
mdIcon no longer defaults to $mdTheme's foreground color.

### ISSUE THREAD

**Issue by gndn** [angular/material#2646]
In Angular Material 0.8, a mdIcon, using md-svg-icon for its image which did not have a color set for its path, set the color of the generated image to match the text foreground color of the active theme.  In 0.9, all svg icons default to filling with black if no color is specified.  Is this an intentional change?

**Comment by ThomasBurleson** [comment]
@marcysutton - It appears that md-icon has opposing settings:

#### icon.scss
```css
md-icon {
  fill: currentColor;
}
```

####icon-theme.scss
```css
md-icon.md-THEME_NAME-theme {
  color: '{{foreground-2}}';

  &.md-primary {
    color: '{{primary-color}}';
  }

  &.md-accent {
    color: '{{accent-color}}';
  }

  &.md-warn {
    color: '{{warn-color}}';
  }
}
```

**Comment by marcysutton** [comment]
What may have triggered a change was `fill: currentcolor` was changed to `fill: currentColor`. The former version in the CSS wasn't actually being used because of the incorrect casing of the word. When corrected, it introduced a conflict with `color`.

**Comment by ThomasBurleson** [comment]
As @marcysutton  indicated, the 0.8 version [icon.scss](https://github.com/angular/material/blob/v0.8.0/src/components/icon/icon.scss#L6) had an incorrect setting that was not used properly to identify the current fill color:

```
md-icon {
  fill: currentcolor;
}
```

> the above `currentcolor` is not recognized. @marcysutton fixed this in https://github.com/angular/material/commit/860d1f67db2be427aff149cbd0c13f0f3d39e4ca
