### ISSUE TITLE
md-dialog title should be sticky for a dialog in a scrolled state

### ISSUE THREAD

**Issue by asans** [angular/material#2647]
According to [Material Specs](http://www.google.com/design/spec/components/dialogs.html#dialogs-specs), when a dialog contains scrolled content, both the title and the actions bar should be fixed, like the screenshot below (taken from the specs):

![screenshot](https://cloud.githubusercontent.com/assets/17964/7423258/819bd58a-ef48-11e4-95de-12239c1e8506.jpg)

The actions-bar works as expected as styles have been added to support this (md-dialog.md-content-overflow ...).  However, there is currently no styles created to deal with titles.

From the demo and the material source code, the dialog title is currently set inside md-dialog-content (see the alert and confirm dialog html in the js file), which is really not correct.  Rather, this title should really be under md-dialog, outside and above md-dialog-content:

```
<md-dialog>
<h2>Title</h2>
<md-dialog-content>
   ...
</md-dialog-content>
</md-dialog>
```

By changing it to the above, one can then easily style the h2 and h3 elements to properly handle the scrolled state.

**Comment by asans** [comment]
After working deeper into this, the issue is more complicated than it appears. 

### md-dialog-content and title padding

Currently, `md-dialog-content` has a set padding of 24px, which is perfect for normal dialogs without scrolling titles and goes according to the specs.  However, once we introduce a dialog in a scrolled state with a header title, the padding space between the title and the scrolled content should only be 20px.

This means that when a dialog has a title, whether in scrolled state or not, the md-dialog-content cannot have the padding-top to be 24px.  That will end up with 20px padding from the title plus the 24px from the md-dialog-content padding at the beginning.  

### title may need to be inside a div

There may be situations where the title needs to reside inside a div for layout purposes, ie:

```
<md-dialog>
<div layout="row">
  <h3 flex>Title</h3>
  <md-icon ....[svg close icon]...></md-icon>
</div>
<md-dialog-content>
...
</md-dialog-content>
</md-dialog>
```

In the above situation, css style should be able to accommodate this type of situation.  

### Possible suggestions to answers

1. We can introduce a new dialog style class to deal with the issue of padding.

2. We can introduce a new title style, ie. md-header, to deal with the header styling, similar to how md-actions style is used to style the actions footer bar.  This may be a better idea, but the question remains on how to resolve the padding between the header and the md-dialog-content's padding.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (523/500 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:32984)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avscA-000L54-43
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:46 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=giUmQe5oDFUQlaKV5v/6KXukyjM=; b=Tv3fcqOxBea6DUH2
	nx5QF+oFWUmkQbpcxCxn0VUn0Nvtk/AV0QrcVomI5U2lmNI7bA1Gwhw3PcRYxjB1
	txggZVWQx01ipKMC+DJ+Wyd3YpVtSmpqddyC+BsYa0o4urf1ObuuULLthyJPUfzM
	F2ZwIka2GRYskjefzpVJg8vPgmg=
Received: by filter0578p1mdw1.sendgrid.net with SMTP id filter0578p1mdw1.3020.5722734F22
        2016-04-28 20:32:15.529071806 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id pJxSZvOiR0KsKvS9U0KexQ
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:15.545 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:15 -0700
