### ISSUE TITLE
ng-messages with multiple flag not working correctly inside md-input-container

### ISSUE THREAD

**Issue by redyyu** [angular/material#2648]
Multiple message will show in one line, message will mass with each other.
test on Chrome.

![screen shot 2015-05-01 at 6 07 53 am](https://cloud.githubusercontent.com/assets/724821/7423664/0eb7c600-efca-11e4-9cd4-47b065a2092a.png)
![screen shot 2015-05-01 at 6 08 52 am](https://cloud.githubusercontent.com/assets/724821/7423690/400d3190-efca-11e4-8092-898dfbb27d5a.png)

**Comment by smehrbrodt** [comment]
Same here, tested in Firefox.
Might be worth a 0.9.1 release.

**Comment by m19** [comment]
Just wanted to confirm this error still exists with Angular 1.4.2 and latest master branch.
