### ISSUE TITLE
Add separate content element for material-card

### ISSUE THREAD

**Issue by Frank3K** [angular/material#265]
In the current build (d5d7e8d53ffcdec0ce995e707d187ebc7edcf1ed) there is a white margin around the image in a `material-card`. This margin is not conform [the design spec](http://www.google.com/design/spec/components/cards.html).

Previously, this white margin was not present; it is a result of the changes in f33185ff9f7e7cc500b4cc75e26e2659f845c418.

See also #247.

**Comment by mzbyszynski** [comment]
:+1:

**Comment by mzbyszynski** [comment]
HI @ajoslin, Not sure if you saw [these comments](https://github.com/angular/material/commit/28a4f8ff4d3b1d7b123152a01ef71e767fc315ff#commitcomment-9177971), but I wanted to make sure you are aware that this last commit  removed the outer margin and hence paper effect from `md-card`, which I don't think was your intent. Here's a [plunkr](http://plnkr.co/edit/bDYV66?p=preview) that shows the problem. Should be an easy enough fix...

**Comment by ajoslin** [comment]
Ah, right. I'll put it back.

**Comment by Frank3K** [comment]
The fix unfortunately introduced an old probleem, see #247.
