### ISSUE TITLE
md-button loses ripple effect in md-card

### ISSUE THREAD

**Issue by zzeng4** [angular/material#2651]
md-button loses ripple effect when used in md-card.

its ok if don't add image in the md-card, everything's fine.

but when I add image to it, md-button loses its ripple effect, include those i use outside md-card.

can anyone fix it?

**Comment by marcysutton** [comment]
Hi, can you provide a Codepen or Plunker showing your issue? Thanks.

**Comment by zzeng4** [comment]
i just figured it out,  its ui router's problem, not ngMaterial. thx.

**Comment by ThomasBurleson** [comment]
@zzeng4 - How does UI-Router create a problem that interferes with a button ripple ?
