### ISSUE TITLE
layout row with layout wrap and flex 33 does not work

### ISSUE THREAD

**Issue by pjain11** [angular/material#2653]
Please take a look at this example - http://plnkr.co/edit/ljBVqYN8Ng1pkVFm0em3?p=preview
I expect three cards to show up in first row, why is it moving third card to second row? I tried setting flex to 30 and see cards on one row but puts big gap in the end which looks ugly from layout perspective. The sample example is with v0.8.3 and I tried the same thing on master code and seeing same results.

**Comment by offminded** [comment]
With the latest master release (0.11.0) flex="33" item with layout-wrap container is pushing third flex33 item to second row: 
http://codepen.io/offminded/pen/yYNWXY/

https://github.com/angular/material/blob/master/src/core/services/layout/layout.scss#L165 outputs the following:
``` css
flex-33, flex-34 {
  flex: 0 0 0 34.00%;
}
```
If flex width was 33.33% like it is with the offset flex (https://github.com/angular/material/blob/master/src/core/services/layout/layout.scss#L135) then layout-wrap would not push it down to second row. 

What is the reason for 34% width for flex-33 items? Why not 33.33%?

**Comment by davide-quix** [comment]
Also if you add padding or border the layout breaks!
The `box-sizing: border-box` rule seems to be missing for this class.
(http://codepen.io/anon/pen/OymjLj)

**Comment by ThomasBurleson** [comment]
To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by ThomasBurleson** [comment]
@pjain11 - Here is an updated, working [Plunkr:](http://plnkr.co/edit/6Zukc643TubLkAM6KC3P?p=preview). With ngMaterial v0.11.2 (or higher), you must now do include the ngMaterial module dependency:

```js
angular.module("MyApp",['ngMaterial']);
```

```html 
<body ng-app="MyApp">
....
</body>
```

**Comment by ThomasBurleson** [comment]
@offminded - The issue you are referring to has definitely caused some confusion.
How about this as a solution:

*  **flex="33"**  becomes **`flex: 0 0 33%`**
*  **flex="34"**  becomes **`flex: 0 0 34%`**
*  **flex="66"**  becomes **`flex: 0 0 66%`**
*  **flex="67"**  becomes **`flex: 0 0 67%`**

This will then allow developers **full** control over their choice.

**Comment by wearska** [comment]
flex="33" needs to remain 0 0 33.33%.

Yes, you can use an expression to make each third element flex="34", but what about if you are working with ratio sized elements? The third element will always be a bit taller than the first 2.
Material design makes use of aspect ratios when it comes to cards or images and this is quite an issue.

**Comment by offminded** [comment]
@ThomasBurleson that solution looks good.
