### ISSUE TITLE
when reduce chrome's height ,md-fab and md-tabs overflow its container

### ISSUE THREAD

**Issue by vanntian** [angular/material#2655]
![qq 20150501200006](https://cloud.githubusercontent.com/assets/10600430/7429937/5c2671a2-f03d-11e4-8c98-2f0ec20a0948.png)
![qq 20150501200207](https://cloud.githubusercontent.com/assets/10600430/7429942/648fc3ac-f03d-11e4-984f-97e5abc4a558.png)
![qq 20150501200348](https://cloud.githubusercontent.com/assets/10600430/7429945/695fd386-f03d-11e4-95d9-73a8e7b51fe0.png)

**Comment by ThomasBurleson** [comment]
@vanntian - can you provide a CodePen or Plunkr that demonstrates this issue; this will help us test and quickly resolve this issue. 

Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/jgx/pen/JogKrQ. 
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by vanntian** [comment]
@ThomasBurleson 
http://plnkr.co/edit/onf8FxUIOVlT7G9YjV9L?p=preview

**Comment by ThomasBurleson** [comment]
@vanntian - superb. We will investigate. Thank you.

**Comment by vanntian** [comment]
@ThomasBurleson Thank you for creating such a sense of the UI,let we have a new choice.

**Comment by marcysutton** [comment]
@vanntian in your demo, height is being reduced to `500px` and overflow is not handled. I don't think this is the fault of tabs, because every piece in the component UI already has `overflow: hidden`. 

To fix your issue, see your custom CSS class on `md-whiteframe`:
```css
.register {
  width: 776px;
  margin-top: 32px;
  height: 500px;
}
```
Adding `overflow: auto;` to that CSS declaration fixes the overflow problems.

**Comment by vanntian** [comment]
@marcysutton if add overflow:auto,it's ugly,My English not so good, I guess you didn't understand what I mean,I hope you can look at when you reduce the height of the browser, chrome and other browsers different.
