### ISSUE TITLE
md-radio-button with ng-disabled and ng-click

### ISSUE THREAD

**Issue by PDSBGreg** [angular/material#2658]
When using md-radio-button with ng-disabled="true" and an ng-click method, the buttons appear disabled, but are still clickable.

See the last two radio buttons at http://plnkr.co/edit/Bjr58GKg6tqN7RhiDJbK?p=preview

This bug occurs in 0.8.3 and the latest from rawgit (I haven't tested other versions).

**Comment by amerimi** [comment]
I think it is the same as https://github.com/angular/material/issues/2561

**Comment by PDSBGreg** [comment]
Yup, except this md-radio-button. Should I keep this open , or close it?

**Comment by ThomasBurleson** [comment]
Duplicate.
