### ISSUE TITLE
md-dialog(md-actions): 'layout-align' doesn't work

### ISSUE THREAD

**Issue by epelc** [angular/material#2659]
If you use `.md-actions` with your dialog you can't overide the alignment.

For example the following doesn't work
```
<md-dialog flex>
    <md-dialog-content layout="column">
        ...
    </md-dialog-content>
    <div class="md-actions" layout="row" layout-align="space-between">
        <md-checkbox ng-model="updates.Show">Let me know about future updates</md-checkbox>
        <md-button ng-click="answer('useful')" class="md-primary">Done</md-button>
    </div>
</md-dialog>
```
Instead you need to use an element with `flex` on it as a hack.
```
<md-dialog flex>
    <md-dialog-content layout="column">
        ...
    </md-dialog-content>
    <div class="md-actions" layout="row">
        <md-checkbox ng-model="updates.Show">Let me know about future updates</md-checkbox>
        <span flex></span> <---- Hacky workaround
        <md-button ng-click="answer('useful')" class="md-primary">Done</md-button>
    </div>
</md-dialog>
```

Also are there any plans to add an `md-dialog-footer`. I think it'd be much more semantic then a div with a class.

**Comment by marcysutton** [comment]
@epelc what is the use case for positioning dialog actions differently? I don't see anywhere in the spec where actions are aligned anywhere but in the bottom right. It would be good to hear more about what you're asking for specifically.

In regards to a dialog footer, when I just made changes to card and dialog (which have similarities) I opted to keep `<div class="md-actions">` for consistency. Our naming patterns would necessitate two separate "semantic" elements: `<md-dialog-footer>` and `<md-card-footer>`, which seem like overkill. So we opted to stick with the CSS class.

**Comment by epelc** [comment]
@marcysutton I was adding a fancy What's new dialog to my app and I wanted to have quick place to change a "Show me this dialog in the future" option but it required `<span flex/>` instead of `layout-align="space-between center"`. I thought it was a bit hacky and I didn't like it.
![image](https://cloud.githubusercontent.com/assets/5204642/7460946/bd2fd662-f274-11e4-990d-e7401481dede.png)

As for the `md-dialog-footer` I think it would make the dialogs more consistent with cards. I also didn't think a random div with `.md-actions` was very semantic. I think making `md-actions` a directive might be better since it's not really a footer but more like an action bar. Either way I think it'd be nicer if it was an element.

**Comment by marcysutton** [comment]
We can easily add `<md-actions>` to allow either usage for the footer, I'll work on that.

That said, I think your use case is atypical. It is way more likely that `md-actions` will need `justify-content: flex-end` than to have one left-aligned item, since it goes against the spec. Recommending we leave the action bar alignment as-is.

**Comment by marcysutton** [comment]
There is no easy way to do that–the `<span flex>` example already in our docs is the only way I know of. The `align-self` flex position override is only for the Y axis, not the X axis.

**Comment by epelc** [comment]
Maybe only apply the right alignment when it doesn't have a layout attribute.

Perhaps something like `md-actions:not ([layout])`  and just put the alignment css in there. then there are no defaults when you explitly set a layout which is required for layout align. Not 100% if the selector will work but I'm pretty sure. I'll see if I can try it out tonight.

**Comment by marcysutton** [comment]
Honestly, this seems like overkill. The spec does not even show an action bar with anything left aligned. `<span flex>` is really easy to add.

**Comment by epelc** [comment]
True I think this is pretty much a one time thing for me anyways.
