### ISSUE TITLE
md-toolbar has a delay when used with ng-hide or ng-if

### ISSUE THREAD

**Issue by jelbourn** [angular/material#2663]
See http://jsbin.com/kixicas/1/edit

Removing the `transition` CSS property on `md-toolbar` fixes this, but it is not clear why a transition specifically targeting `box-shadow` would impact this.

**Comment by ThomasBurleson** [comment]
I think @robertmesserle recently added this shadow transition... not sure why it impacts performance.

**Comment by calebegg** [comment]
I was actually just debugging a similar problem in our app, and I think the best solution is either to only use transitions that you want ngAnimate to care about (and then only use them in the special classes ng-animate makes) or to use a prefix for ngAnimate:

https://docs.angularjs.org/api/ngAnimate#preventing-collisions-with-third-party-libraries

Though I don't know if it's possible to do that without enforcing it for all angular-material users as well.

**Comment by robertmesserle** [comment]
I well add a fix for this later. I've had to fix this on other components.

**Comment by robertmesserle** [comment]
The easy fix is to add transition: none for md-toolbar.ng-animate
