### ISSUE TITLE
mdSideNav - animation on iphone /android browsers - changes height during animation

### ISSUE THREAD

**Issue by myellepeddy** [angular/material#2665]
The animation during the right sidenav opening and closing particularly the closing, changes the height of the page.
This happens in android browser but not on a desktop browser or iphone browser.

I created a plunker for this. The way to test is to emulate in the chrome browser and pick any of the Apple or android devices.
http://plnkr.co/edit/V0SKDbHjiQzYdTgmWUhF?p=preview

It would be great if you can include this in 0.9.0 release.

Thank you

**Comment by ThomasBurleson** [comment]
@myellepeddy - the mdSideNav opens with the height of the <body> element; which in your case the size of the browser window. Yet your `<div ng-controller="MainCtrl">` is constrained to 250px height.

> The sideNav is working as designed. It is your other layout that is the issue. Here is a modified Plunkr that shows the desired sideNav height (250px):  http://plnkr.co/edit/a9NUHRJrO0rs8oqJKgyo?p=preview
