### ISSUE TITLE
mdListItem: spaces are ignored in descendant textarea

### ISSUE THREAD

**Issue by Frank3K** [angular/material#2668]
When using a `textarea` element inside an `md-list-item` (no proxy) all spaces are ignored. This behaviour can be observed in Chrome 42 (Windows, Ubuntu) and Internet Explorer. Due to another bug in the `mdListItemDirective`, the problem does not appear in Firefox.

The culprit is inside the [following lines](https://github.com/angular/material/blob/f66e4718451b90cd27f393a2bbc46e3e6891a61e/src/components/list/list.js#L206-L216) of the `mdListItemDirective`:

``` js
        if (!hasClick && !proxies.length) {
          firstChild.addEventListener('keypress', function(e) {
            if (e.target.nodeName != 'INPUT') {
              if (e.keyCode == $mdConstant.KEY_CODE.SPACE) {
                firstChild.click();
                e.preventDefault();
                e.stopPropagation();
              }
            }
          });
        }
```

All spaces, except those on `input` elements, are prevented. I think this should be changed to:

``` js
if (e.keyCode == $mdConstant.KEY_CODE.SPACE) {
  if (e.target.nodeName != 'INPUT' && e.target.nodeName != 'TEXTAREA') {
    ...
  }
}
```

In Firefox, the above code does not trigger since `e.keyCode` returns 0. This can be fixed by also checking `e.which`, which is also done in (for example) the [radioGroupDirective](https://github.com/angular/material/blob/977a495e7d3de27bebabdebaaf5611c9d06a1e22/src/components/radioButton/radioButton.js#L72).

**Comment by opadillaintegrify** [comment]
There's still something not quite right about this.   I have and md-list with an md-list-items that contains a textAngular directive.   textAngular sticks its own text area tag into the html and I'm not getting any spaces when I use the space bar.
It works just fine when I comment out the md-list and md-list-item tags.

**Comment by opadillaintegrify** [comment]
The problem is still there in 0.9.5.

**Comment by opadillaintegrify** [comment]
The problem is still there in 0.9.6.

**Comment by thecas** [comment]
Problem still exist in 1.0.0-rc1.
I have a textAngular in a md-list-item where spaces are not working.

**Comment by thecas** [comment]
@opadillaintegrify textAngular uses an editable div instead of a textarea so this bug is indeed solved.
I opened a new bug #5406 with a patch that solves the problem with textAngular.
