### ISSUE TITLE
ng-class is not working when 'class' has two expressions

### ISSUE THREAD

**Issue by todorenko** [angular/material#2669]
`ng-class` below is not working:
```
<li ng-repeat="fruit in mc.myFruit"
class="class1-{{fruit}} class2-{{fruit}}" 
ng-class="{'my-orange-class': fruit == 'orange'}">{{fruit}}</li>
```
It works if I disable material. 
It also works if I remove `class2-{{fruit}}`. 

It looks like `ng-class` stops working if there is more than one `{{expression}}` inside the `class` attribute.

http://plnkr.co/edit/jGVCai4XGZVLoeHpT3qU?p=preview

**Comment by ThomasBurleson** [comment]
This is not an Angular Material component issue. You are welcome, however, to post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by todorenko** [comment]
If it's not a material issue then what would be the issue?
It works with plain angularjs. It's not working when material dependency is injected into the app.

**Comment by ThomasBurleson** [comment]
@todorenko - these two approaches work:

```html
<li ng-repeat="fruit in mc.myFruit" class="class1-{{fruit}} my-orange" ng-class="{'my-orange-class': fruit == 'orange'}">

<li ng-repeat="fruit in mc.myFruit" class="class1-{{fruit}} class2-orange" ng-class="{'my-orange-class': fruit == 'orange'}">
```

It is highly unlikely that there is an issue with **ng-class** and Angular Material. But I will reopen to investigate later.

**Comment by rschmukler** [comment]
@ThomasBurleson oddly enough, this does look like it's our issue. I played around with a few permutations and it does seem to be dependent on loading `ngMaterial`. But I have no idea why or where... Could be a bug in angular somewhere but  it *seems* that we might be triggering it.
