### ISSUE TITLE
mdDialog: button sizing does not match specification

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2671]
Buttons have side-padding of 8dp and 64dp min-width. See "Dialog button container" (even though the name, the specs applies to flat and raised buttons)

![Dialog Buttons](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0Bx4BSt6jniD7a2pSRnZTaDRBbFU/components_buttons_usage_dialogs1.png)

![Button Details](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0Bx4BSt6jniD7SVdWa0o3WW8yLXc/components_buttons_keyline1.png)

@see http://www.google.com/design/spec/components/buttons.html#buttons-usage

**Comment by marcysutton** [comment]
There are conflicting specs for dialog buttons. Dialog shows 8px to the right of a button, not 16px:

[dialog buttons](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B6Okdz75tqQscVhjY2hBcVFvTFE/components_dialogs_updates1.png)

Cards also show 8px. http://www.google.com/design/spec/components/cards.html#cards-actions

Our demos conform to this–the only change I can see is needed is side-by-side buttons should be separated by 8 pixels, not 4.
