### ISSUE TITLE
md-tabs md-dynamic height should not be 2 way binding

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2678]
I want to use a media query to decide if md-tabs should be dynamic height...

`<md-tabs flex-gt-sm md-dynamic-height="$mdMedia('gt-sm')">`

I am getting a nonassignable error when running, I believe the md-dynamic-height should be an @ not = in the isolate scope?

**Comment by robertmesserle** [comment]
@hodeyp Yea, I'm currently doing a pass on `md-tabs` and `md-autocomplete` to remove a lot of the unnecessary 2-way bindings.

**Comment by robertmesserle** [comment]
This should be resolved in master and will be in the 0.10.1 release.
