### ISSUE TITLE
0.9.0-rc3 md-grid-list forces md-grid-tile to be immediate child

### ISSUE THREAD

**Issue by sysupbda** [angular/material#2679]
Until 0.9.0-rc2 **md-grid-list** accepted contents that "contained" **md-grid-tile**s somewhere in them. This was useful so we could use other directives that could therefore decide themselves how many tiles they want to span.

I have made an example at http://plnkr.co/2UDIAC
The first tile is defined within a **div** and gets a **0** height even though the tag is processed and expanded by its directive.

**Comment by ThomasBurleson** [comment]
`mdGridList` now requires only `mdGridTile` items.

**Comment by sysupbda** [comment]
Hi @ThomasBurleson, thank you for your kind reply. Can we please mention this in the "breaking changes" for RC3 in the CHANGELOG.md? Thank you.
