### ISSUE TITLE
md-input-container with wrong label positioning when inside scrollable md-card-content

### ISSUE THREAD

**Issue by uriva** [angular/material#2682]
http://plnkr.co/edit/nXXIMr6yDaag2lhzwHH3?p=preview

I think this has something to do with `layout="column"`

**Comment by grizzm0** [comment]
While the spec doesn't say anything about allowing or disallowing buttons on the same row as a text field I feel like this is not something you're supposed to do.

**Comment by uriva** [comment]
seems fixed now.
