### ISSUE TITLE
Inputs that are created using ng-if do not bind to their model

### ISSUE THREAD

**Issue by uriva** [angular/material#2683]
plunkr: http://plnkr.co/edit/4e5XUAbgmhagZqnSazvB?p=preview

**Comment by grizzm0** [comment]
This is not related to angular/material. Please see angular/angular.js#6038

@ThomasBurleson Could you please close?

**Comment by rschmukler** [comment]
@uriva indeed, `ng-if` makes a new isolate scope. That issue is a good reference. Closing

**Comment by uriva** [comment]
Thanks. Sorry for the spam.
