### ISSUE TITLE
md-sidenav/md-dialog: You can scroll md-content(outside the sidenav) while the sidenav/dialog is open

### ISSUE THREAD

**Issue by epelc** [angular/material#2685]
In ios 8 on an iphone I can scroll the regular content while the sidenav is open. You can see this on the docs. I also noticed in my own app. Note this doesn't happen in the latest chrome on android.

**Comment by epelc** [comment]
I forgot to mention you can also scroll the background content while a dialog is open.

**Comment by catsass19** [comment]
I'm having the same issue. My sidebar content should be scrolling but it doesn't. The main page is scrolling instead. This issue can be reproduced on iOS Safari and iOS Chrome. Desktop browsers are fine.

**Comment by catsass19** [comment]
My workaround for this issue is to add this following CSS to <md-sidenav>:
-webkit-overflow-scrolling: touch;

**Comment by heoseok** [comment]
+1

**Comment by EladBezalel** [comment]
@all it's still happening? 

@catsass19 i can't figure why `-webkit-overflow-scrolling: touch;` worked for you as it's just affects the scrolling behavior.. weird..

**Comment by EladBezalel** [comment]
closed due to inactivity
