### ISSUE TITLE
md-content does not give a hint for additional content

### ISSUE THREAD

**Issue by hhietanen** [angular/material#2689]
The md-content enables setting a scrollable content area. Current CSS does not give visual cue that there is more content below the visible area. Because of the lack of visual cue, the user is more likely to miss the scrollable area.

Fix: fade the bottom edge to give a visual cue. 
Example here
![image](https://cloud.githubusercontent.com/assets/1021873/7451120/903f73d4-f255-11e4-9706-45d867e4e000.png)
http://ux.stackexchange.com/questions/24707/is-there-a-good-visual-cue-to-replace-scrollbar

**Comment by epelc** [comment]
I think the fading makes the information at the bottom less usable. Also hasn't everyone been trained already that most things scroll? Besides `md-content` shows a scroll bar so there is no need to add this.

**Comment by hhietanen** [comment]
The scroll bar is not visible before you scroll the content.

I ran tests with my users who had hard time finding the content which had to be scrolled.

I do realise that the material specs does not include the bottom fade: http://www.google.com/design/spec/patterns/scrolling-techniques.html#
and the fade is not as relevant for mobile view, but it is relevant when you gracefully enhance the UI for larger devices.

**Comment by epelc** [comment]
The scrollbar is visible without scrolling on a desktop. On android/ios it's not. But realistically I don't think any modern ui does this it just waist space and especially so on an already small phone screen.

![image](https://cloud.githubusercontent.com/assets/5204642/7454183/55b8db26-f23f-11e4-8a3e-4a1f6b1a3c3b.png)

I think if you really need this for your users it'd be better to put in your apps custom css.

**Comment by hhietanen** [comment]
The scrollbar is not visible on desktop:

![nayttokuva 2015-05-04 kello 16 32 41](https://cloud.githubusercontent.com/assets/1021873/7454333/5c5e4042-f27b-11e4-8242-0a0015b60750.png)

**Comment by epelc** [comment]
Browser? I'm seeing it in the latest ie11, chrome, and firefox on windows 10 preview. But even so I still think if you want this it should be app specific css.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
