### ISSUE TITLE
md-select md-virtual-scroll-container breaks layout

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#2692]
The virtual scroll container that gets inserted into the DOM when the select box is clicked changes the DOM hierarchy, possibly breaking declared CSS rules.

When using SASS/Stylus etc. a lot of hierarchical CSS is used - like this:

``` css
.main {
  > div {
     > .content {
       ...
     }
   }
}
```

This breaks when DOM nodes are inserted in between.
I know it is possible to work around this by not using `>`, it might even be considered bad practice by some but I see a lot of people running into this problem.

Plunkr: http://plnkr.co/edit/XqY8NttC0euzMHkllULe?p=preview

**Comment by kuhnroyal** [comment]
Possibly related to #2379

**Comment by myagoo** [comment]
That's a dealbreaker ladies 
![dealbreaker](http://thebacklot.mtvnimages.com/uploads/2013/10/dealbreaker_zps8a250d60.gif)
