### ISSUE TITLE
0.9RC3 md-tabs no longer function in a layout=row flex

### ISSUE THREAD

**Issue by sysupbda** [angular/material#2693]
Not sure whether or not to book this as an issue. I just spent lots of time finding the solution to this issue I had after upgrading from 0.9RC2 to RC3, so I thought it might help others to find it documented and the source of the problem. Specially as I could not find anything in the CHANGELOG.md that would indicate such a change.

In 0.9RC2, using md-tabs within a `<section layout=row flex>` worked. In RC3 it only displays the pagination arrows.

http://plnkr.co/sVF4UJ1iYzB6yCw9aFNz

That being said, I don't feel it is unreasonable. Just that it was harder than I wish to upgrade without knowing about such a breaking change.

**Comment by ThomasBurleson** [comment]
The issue is `layout="row"` if you change to this:

```html
<section layout="column">
    <md-tabs md-selected="values.selected">
       <md-tab label="{{value.title}}" ng-repeat="value in values.tabs"></md-tab>
    </md-tabs>
</section>
```

Then all works correctly.

**Comment by ThomasBurleson** [comment]
@robertmesserle - With the incorrect `layout="row"` , the tabs width is too small. But why did it work in RC2 etc? Any idea why the RC3 changes make the incorrect obviously not display properly?

**Comment by robertmesserle** [comment]
@ThomasBurleson Not sure why it worked in RC2, but I did make some layout fixes to Tabs in RC3 to address some other issues.

**Comment by robertmesserle** [comment]
@sysupbda You can also resolve this by adding `flex` to `md-tabs`

**Comment by Geono** [comment]
@robertmesserle Thank you it really helped!
