### ISSUE TITLE
md-aria warnings md-list-item

### ISSUE THREAD

**Issue by david-gang** [angular/material#2698]
I have the following html
```javascript
<md-list-item class="md-3-line "

			ng-repeat="item in ctrl.results"
            ng-click="ctrl.makeSomething(item)"
			>
```

The md-list-item directives hosts a button.

When the html is rendered i get warning
> ARIA: Attribute " aria-label ", required for accessibility, is missing on node

```javascript
<button class="md-no-style md-button" ng-transclude="" ng-click="ctrl.makeSomething(item)" tabindex="0">
...
</button>
```

I am not sure if the aria warning is on the button or in some html nested in the button. If the former is the case, it is an issue. If not it would be nice to have a more specific warning on the exact node.
I could not reproduce this issue with a plunkr. It could be that console.logs are not shown there, but i am not sure.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
