### ISSUE TITLE
md-autocomplete type="search" (Chrome autofill behavior)

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#2699]
I have a `md-autocomplete` which retrieves zip codes. The `autocomplete="off"` does not prevent the Chrome autofill settings for adresses etc. thus rendering the box pretty much useless since one can not select the results.

Also see https://code.google.com/p/chromium/issues/detail?id=468153

Chrome seems to detect that by means of the `label`and `name` attribute, so this happens when a `md-floating-label` with address-type name is used e.g. Zip/Street etc.

I have been reading a little bit in the HTML spec and maybe the input fields in `md-autocomplete` should have the `type="search"`. This would as far as I can tell prevent the chrome autofill popup.

If for some reason the is not generally wanted, `md-autocomplete` should at least allow to override the `type` attribute and maybe even the `autocomplete` attribute.

https://html.spec.whatwg.org/multipage/forms.html#autofill
https://html.spec.whatwg.org/multipage/forms.html#text-(type=text)-state-and-search-state-(type=search)

**Comment by epelc** [comment]
@kuhnroyal See #2457 @robertmesserle gave a good work around from the chrome team.

**Comment by kuhnroyal** [comment]
Thanks, must have missed that issue.
My search field is wrapped in a form and the form also has `autocomplete="off"`.

Setting `type="search"` suppresses the autofill and it should be allowed to at least override it if not even be the default.

**Comment by epelc** [comment]
@kuhnroyal I just realized that `type="search"` is essentially a working `autocomplete="off"`.

This should definitly be the default. I can't think of any situation where someone would want an autocomplete to be autofilled with the browsers ui. @ThomasBurleson what do you think?

**Comment by kuhnroyal** [comment]
Yea that's what I was trying to communicate :)

**Comment by ThomasBurleson** [comment]
@epelc - totally agree. In fact see https://github.com/angular/material/issues/2802#issuecomment-101766662 for agreement.

**Comment by gkalpak** [comment]
Everyone seems to think otherwise, but setting `type="search"` is quite arbitrary imo and at least unexpected :confused:

**Comment by robertmesserle** [comment]
@gkalpak It is, but it sounds like it is the only real workaround for Chrome's aggressive autofill feature.  It also seems somewhat fitting for autocomplete, since it is essentially searching for matches.
