### ISSUE TITLE
md-checkbox: Text alignment is off on the second line

### ISSUE THREAD

**Issue by epelc** [angular/material#2700]
If your checkboxs text overflows to a second line the text alignment is slightly off.

Here is a demo http://plnkr.co/edit/WyOJ76MVReOUt6LrPk3q?p=preview
![image](https://cloud.githubusercontent.com/assets/5204642/7455846/8c093cee-f24d-11e4-8956-f9a359dfe770.png)

Note it works fine if you use a `br` but it's broken if your text naturally breaks onto a second line.

**Comment by ThomasBurleson** [comment]
duplicate #2642
