### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by warpdesign** [angular/material#2701]
I'm working on a small angular-material app. Right now there are only a few Angular directives.

After some research I found out that when I disable angular-material, CPU usage drops to 1% while it is at up to 30% when the directive is loaded and used.

This is without manipulating the app. Any idea what could cause this high cpu usage ?

This is with Chrome 42/Win/64bit.

**Comment by warpdesign** [comment]
After some more investigation, I noticed that if I do not include material css file, cpu is fine: around 1%. If I include it it jumps to 30%.

**Comment by epelc** [comment]
Are you using any specific directives? Whats your layout? Can we get an example? I doubt it's angular-material in it's entirety it's probably an issue with just one or a couple of things.

Also if you have a lot of text there was an issue with it causing high resource usage because all text was set to use anti aliasing or something. I'm not sure if the fix made it into `0.9.0-rc3` or if it's coming in `0.9.0`.

**Comment by cleever** [comment]
We can use a main angular material demo site running on a good phone like Moto X 2nd Generation to see that performance is not good enough.
The application is very laggy every time I activate a sidebar and use sub menu for example.
Tabs demo is very laggy too.

In a real world application on desktop, the CPU usage is too high even running in Google Chrome.

**Comment by ThomasBurleson** [comment]
@cleever - which version of AngularJS are you using? which version of Angular Material ?

**Comment by cleever** [comment]
Now I'm using #master with Angular 1.4.1.

This version is faster than a old version that I tried 11 days ago.

The demo site is faster too. But still slow when I use Tabs Demo.

**Comment by ThomasBurleson** [comment]
@cleever - can you re-try with the lastest changes in #master (SHA a9bc534)

**Comment by cleever** [comment]
@ThomasBurleson, thanks for the attentions, but I'm still having performance issues.

**Comment by ThomasBurleson** [comment]
@cleever - Angular 1.4.x $$rAF apparently has some performance issues with Angular Material... we are investigating.

**Comment by paambaati** [comment]
For anyone facing performance issues, I'd recommend you guys switch to Angular 1.3.x till a fix lands for this. Performance is way better and I no longer face stutters or lags after downgrading from 1.4.x.

**Comment by ThomasBurleson** [comment]
@paambaati - Thanks for the feedback. As soon as v0.10.1 is released, we will commit to master (to be published with 0.11) these fixes for the ngAnimate compatibility issues: https://github.com/angular/material/pull/3949

**Comment by ThomasBurleson** [comment]
*  Ripple/Ink performances have been significantly improved. 
*  Animations improved use ngAnimate and $animateCss. 

Closing this general issue for 0.11. 

> For any other specific component performance issues, please open new issue.
