### ISSUE TITLE
Request: Add white toolbar styles

### ISSUE THREAD

**Issue by epelc** [angular/material#2703]
I think it'd be a good idea to add a class for white tool bars. Possibly with primary color text.

I really want the above but if the team is up for it I think tool bars could be more like buttons with their styling. ie having primary and raised styles instead of always using what one could call a primary and raised style. What I mean by this is that toolbar could default to being white with the grey text like buttons but a primary or accent/warn etc could make the text said color. While a raised class combined with one of the color classes would achieve what we have now with the color being the background and using white/black for the text.

Let me know what you think. This might be to specific but I think having classes like md-button would really improve toolbars.

**Comment by dmackerman** [comment]
We just override the CSS.

**Comment by Koslun** [comment]
In case you haven't solved it other than overriding the CSS:

So right now the color defaults to white or black depending on how light or dark the theme is considered. If you dislike whatever color you can change md-buttons in toolbars through explicit theming already, see the docs [here](https://material.angularjs.org/latest/#/Theming/03_configuring_a_theme). 

To summarize it you can either set the material design number of a color or hue to be the whitest of a particular color. Or just straight up set a color or hue to have a particular RGB color in hex.

We do it using a material design color number on our accent color:
```bash
$mdThemingProvider.theme('default')
      .primaryPalette('green')
      .accentPalette('deep-purple', {
        'hue-1': '50'
    });
```

Then in the toolbar simply adding "md-accent md-hue-1" to any md-button that we want to have that color.

Though we did just override the CSS prior to that changing the theme is the easiest imo.

I think if you have any other suggestion that is not about tweaking the color you should rather split that up into a different issue. Either way this issue should be closed imo.

**Comment by nicooga** [comment]
For future reference -as I coming to this post for the 1e26 time- this can be solved using the default `grey` palette:

~~~js
$mdThemingProvider
  .theme('grey')
  .primaryPalette('grey');
~~~

~~~jade
md-toolbar.md-hue-3.md-whiteframe-z1(md-theme='grey')
  .md-toolbar-tools(layout='row')
    // ...
~~~

**Comment by angrylala** [comment]
Adding a white palette, then using md-colors directive works for me:

`var whiteMap = $mdThemingProvider.extendPalette('grey', {
        '500': '#ffffff',
        'contrastDefaultColor': 'dark'
});
`
`$mdThemingProvider.definePalette('white', whiteMap);`


md-colors directive usage
`    <md-toolbar md-colors="::{background: 'white'}">`
