### ISSUE TITLE
md-autocomplete: Add a cache lifetime attribute

### ISSUE THREAD

**Issue by epelc** [angular/material#2705]
`md-autocomplete` has an `md-no-cache` option to completely disable the cache. But it'd be nice to meet in the middle and let users specify a cache lifetime for results.

A use case would be searching through items which a team of people can create/edit. Caching for 30s or even a few minutes is a lot better then no cache because while searching a cache is helpful. But things aren't likely to change within 5 seconds depending on your team size. Also if we cache for ever then you would have to refresh the page to see new items from the search.

**Comment by DevVersion** [comment]
@epelc - That's a really good idea IMO, I'm up to implement that feature :). But I want to have a few more information. You talking about a lifetime cache for every cached element or better (IMO) to clear the entire cache every `lifetime` milliseconds. Thoughts?

**Comment by epelc** [comment]
@devversion I was thinking it should clear the cache for a specific search term after the lifetime. This way you don't just lose the whole cache every x seconds. As that would be bad if say I searched something 5 min ago and then I just search something 1 min ago. It shouldn't delete both if the lifetime is 6 min. It should delete the first search when it reaches 6 min then delete the other search when that reaches 6min. 

Also thanks for taking the time to work on this!

**Comment by ThomasBurleson** [comment]
Feature is too specific and not central to ngMaterial. Rejecting and closing.

**Comment by epelc** [comment]
@ThomasBurleson I protest.

Think of any app which is open for more then 5 minutes. Your forcing that app to choose between having old results for anything they previously searched(and basically a memory leak) or have no caching of search results. 

A good example is gmail as it's typically open all day long on the desktop. However I think most enterprise apps also fit the bill as they are typically also kept open and actively used through out the day. An example of my use case is I have a shipping/logistics app which users are running quotes and creating shipments on all day. Many users also search for old shipments through out the day so they can print bill of ladings.

It may not have to be configurable but I think at the very least the cache should be purged every few minutes. As otherwise it's a memory leak.

**Comment by bluebirdtech** [comment]
How about providing the ability to clear/invalidate the cache on md-autocomplete and letting the application decide when?  Like this #7411

**Comment by stefan-leye** [comment]
+1

**Comment by Ulrikop** [comment]
+1
I want do to clear the cache after the user seletected an item

**Comment by jayellsbrg** [comment]
Alternatively, you could let the user set a cache for md-autocomplete: `md-cache="myCache"`. That way, the user may setup caching as appropriate for them (e.g. LRU, memory v. localStorage)

On the contrary, md-autocomplete shouldn't even offer caching. That should be a separate concern. If you're passing results from an http request, you ought to cache the responses then, and not rely on md-autocomplete.
