### ISSUE TITLE
Icon color toolbar is contrastLight instead of contrastDark

### ISSUE THREAD

**Issue by robertbaker** [angular/material#2707]
Using 0.9.0

![capture](https://cloud.githubusercontent.com/assets/907301/7460988/e36e97f0-f25b-11e4-83a4-b38fd2efc714.PNG)

```
            .primaryPalette('indigo')
            .accentPalette('green');

```

Toolbar has md-accent and contains md-button > md-icon using material icons svg.

http://plnkr.co/edit/JNXuFxkckkDilzGrqMVI?p=preview

**Comment by ThomasBurleson** [comment]
Thanks. Same issue is present for `.md-warn`

**Comment by epelc** [comment]
+1 it's also wrong for raised buttons. It's showing up as white on whiter
![image](https://cloud.githubusercontent.com/assets/5204642/7477713/9b52601e-f323-11e4-8f8d-064615a49ca3.png)
It also seems to be generating two styles
![image](https://cloud.githubusercontent.com/assets/5204642/7477766/eb0d1216-f323-11e4-9ec8-dea4c0f339f3.png)
I'm using `0.9.0`

**Comment by ThomasBurleson** [comment]
Fixed in master. 

![screen shot 2015-11-05 at 2 50 19 pm](https://cloud.githubusercontent.com/assets/210413/10981300/934b9ab8-83cc-11e5-83ea-eb80b1455d14.png)

**Comment by epelc** [comment]
@ThomasBurleson Does it work with raised buttons?
