### ISSUE TITLE
md-input-container md-input-focused not respecting md-accent/md-hue/md-warn

### ISSUE THREAD

**Issue by robertbaker** [angular/material#2709]
```
md-input-container.md-default-theme:not(.md-input-invalid).md-input-focused md-icon
and
md-input-container.md-default-theme:not(.md-input-invalid).md-input-focused
```

Needs modifiers for md-accent,  md-hue, and md-warn. Using an md-accent (green) on a toolbar with an input shows blue. Expected it to be a shade of green, both for the icon and the input underline.

http://plnkr.co/edit/JNXuFxkckkDilzGrqMVI?p=preview

**Comment by ThomasBurleson** [comment]
@robertbaker - you are the component-theme "patrol officer". Thank you for these.

**Comment by jb29** [comment]
If you change the default hue of your color, it doesn't get applied to the focused input.
See http://codepen.io/anon/pen/KpRXeO

**Comment by jwuliger** [comment]
Hello, I am facing this issue also. Right now I am overriding the class names. Any timeline for this fix? Thanks!!

**Comment by snarayanank2** [comment]
I *think* this is the same as the issue I'm facing. I'm new to angular-material, so please bear with me.

My requirement: I want a search input in the toolbar. I'm using the pink theme. The HTML snippet looks like this:
```
       <div layout="row">
           <i class="material-icons">attach_file</i>
          <h1 class="md-headline no-margin"> My Transactions </h1>
        </div>

          <md-input-container class="md-primary">
            <label>Search</label>
            <input type="text" ng-model="search.keyword">
          </md-input-container>
```

When not focused, this shows up like this:
![screen shot 2016-02-06 at 2 01 46 pm](https://cloud.githubusercontent.com/assets/5491710/12865734/e5d3d05a-ccda-11e5-983f-726dab7231b3.png)

When input is focused and I start typing, it shows up like this:
![screen shot 2016-02-06 at 2 02 03 pm](https://cloud.githubusercontent.com/assets/5491710/12865736/ef31d0f2-ccda-11e5-988a-ff0879442a55.png)

I'd expect the search label and text to be white.. am I missing something? Is there a workaround for this?

**Comment by langdonx** [comment]
@snarayanank2 I think your override is probably necessarily.  An input's label is meant to be is contrasted differently from inout's text, or other text on the screen.

See:

https://www.google.com/design/spec/components/text-fields.html#text-fields-labels
https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

You  may be able to create a specific theme for the `md-input-container`, but I think there will always (and probably should always) be a contrast difference between the label and the text.

If your label and text were white and the user typed "Search" into the search box, it wouldn't be visually clear what happened.

**Comment by snarayanank2** [comment]
@langdonx thanks for the link. Makes sense that label and border color shouldn't be white as I originally thought. However, current behavior doesn't seem right.

1. The bottom border basically disappears when I start typing in the search box and so does the label (both of them are colored pink so can't see them)
2. Text in the input area is black

**Comment by alansutherland** [comment]
I think this issue should be re-opened, this is something so simple with plain HTML and CSS and isn't material design all about simplicity?
