### ISSUE TITLE
docs : The number generated styles tags in the head in growing indefinitely 

### ISSUE THREAD

**Issue by TalPasi** [angular/material#2711]
The number of the generated theme styles is constantly growing when clicking the different navigation buttons of the sidebar 

![image](https://cloud.githubusercontent.com/assets/1816536/7461745/2d27396a-f27a-11e4-8108-88c3acee33fc.png)

**Comment by smashercosmo** [comment]
That's not only in the docs. We have the same issue in our app.

**Comment by ThomasBurleson** [comment]
This should not longer be an issue with v0.10.0 or later.

**Comment by smashercosmo** [comment]
@ThomasBurleson mmm... I'm using 0.10.0 and I have 32 style tags injected by angular-material
