### ISSUE TITLE
mdInput: copy and paste keys do not work in input control

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2713]
cmd-x/ctrl-x and cmd-v/ctrl-v keys are ignored in the input field within md-input-container.

**Comment by marcysutton** [comment]
@ThomasBurleson which browser/platform, and any specific demo? I can cut and paste just fine in Chrome, Firefox and Safari from the keyboard on OSX (⌘+x, ⌘+v) and on Windows including IE (Ctrl+x, Ctrl+v).

**Comment by ThomasBurleson** [comment]
Unable to reproduce issue... all appears normal currently
