### ISSUE TITLE
md-select's option label truncated

### ISSUE THREAD

**Issue by jgoux** [angular/material#2719]
Hello,
on the master, we can see that md-select's option label are truncated at the bottom : 
![md-select](https://cloud.githubusercontent.com/assets/1443499/7468377/104aaaaa-f308-11e4-8170-ee1cc7232bcc.jpg)

You can see it in the doc : https://material.angularjs.org/#/demo/material.components.select

**Comment by jakubweber** [comment]
+1
We're using this master version http://rawgit.com/angular/bower-material/master/angular-material.css for devs purposes.

**Comment by rschmukler** [comment]
This appears to be resolved on master now. If not, what browser are you seeing it on?

**Comment by jakubweber** [comment]
Yes, it looks resolved.

**Comment by jgoux** [comment]
Yes it is ! :+1:
