### ISSUE TITLE
md-autocomplete: Style inconsistencies between autocomplete and other inputs

### ISSUE THREAD

**Issue by jgoux** [angular/material#2720]
Hi,
on the master, if you put side by side a md-select with other inputs (md-autocomplete for example), you can see that md-select isn't aligned with the others.
You can also notice that the padding-bottom of md-select's option label is higher than the other inputs.
Example here : http://codepen.io/jgx/pen/JdYKjR

**Comment by uriva** [comment]
+1

**Comment by jelbourn** [comment]
Related #3234
