### ISSUE TITLE
Famous-angular + Angular-material(ngMaterial) issues

### ISSUE THREAD

**Issue by ArthurianX** [angular/material#2721]
I will post this issue on both repositories (https://github.com/Famous/famous-angular + https://github.com/angular/material)

I am using famo.us and ngMaterial on a MeteorJS Project (and Meteor to top it all off, but there's no conflicts there) and I have had several issues, depending on which library gets to load first.

Use case:

1. ngMaterial loads before famo.us, so famo.us overwrites some of ngMaterial's functionality
Result: 
a) implementing ngMaterial tabs will crash the whole application
b) animations generally won't find necessary methods and will crash the application

2. ngMaterial loads after famo.us thus overwriting event listeners put in place by famo.us
Result: famo.us directives aren't working (all of them imply animation, and what I tried didn't work)

I think the common denominator is the event listeners for touch (in my case) and how they handle animations on event firing.

What would we need in this case? An external angular plugin/service which will merge the event listeners, or work on both libraries to create compatibility ?

I know that there's probably no one's business to support both libraries in a project (or that's how I see it), but what could be done on this subject.

I am willing to help.

**Comment by ArthurianX** [comment]
Reference: https://github.com/Famous/famous-angular/issues/367

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (623/500 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:57955 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdM-000Lmj-PH
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:34:00 -0500
Date: Thu, 28 Apr 2016 13:32:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875547;
	bh=BGYmXxyxyhYSFI9Fd0Z3Zu/C2bUg5dxHD7BrugaUYpI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=K2UHJLWlZhtk/py9i0sEVfADRouHtwW+P5VU39ab7/obm1sGD2ZuTDNx5hYL+2hgt
	 H/6XIHFpCtDH6nj/+etSo1cBobHePzvqGH0MEcWEB7O16/8skRyl335wJt/kWOwBZF
	 emat2FPDur6jDkHaq40MMOsN/N5zqv9uw0RXKpNk=
