### ISSUE TITLE
$mdUtil not documented

### ISSUE THREAD

**Issue by david-gang** [angular/material#2722]
There should be a subsection on the $mdUtil service in the services section which explains the functions of this service. Now it is missing
![capture](https://cloud.githubusercontent.com/assets/1292882/7474211/859c730c-f348-11e4-93a0-466a3494cc75.PNG)

**Comment by ThomasBurleson** [comment]
The utils are intended for internal use. No documentation is planned.

**Comment by david-gang** [comment]
But they are used in the side nav demo so they should be either documented or removed entirely

**Comment by david-gang** [comment]
Removed entirely from the demo.

**Comment by epelc** [comment]
I think the plan was to switch the docs to a new collapse directive which would be public. I think that's the only thing the demo uses it for(not 100% I copied the demo's dropdown around 0.6.0).

**Comment by ThomasBurleson** [comment]
That usage of $mdUtil was specific to a use case where the user clicks needed to be debounced.
There are no current plans to document this utility module.

**Comment by chillyspoon** [comment]
This is still in the demo:

```
    function buildToggler(navID) {
      var debounceFn =  $mdUtil.debounce(function(){
            $mdSidenav(navID)
              .toggle()
              .then(function () {
                $log.debug("toggle " + navID + " is done");
              });
          },200);
      return debounceFn;
    }
```

Are you saying that we should remove the reference to $mdUtil from our code?

**Comment by ThomasBurleson** [comment]
@chillyspoon - you may use $mdUtil, but we will not document that module until later.

**Comment by chillyspoon** [comment]
Ok, cool - thanks.

**Comment by michelank** [comment]
@david-gang you can toggle() the sidebar without it, something like it (in ts):

buildToggler(navID: string): void {
            this.$mdSidenav(navID).toggle()
                .then(() => {
                    console.log("toggle " + navID + " is done");
                });
        }

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
