### ISSUE TITLE
CDN 403 Error

### ISSUE THREAD

**Issue by skolade** [angular/material#2726]
the CDN link on (https://ajax.googleapis.com/ajax/libs/angular_material/0.9.0/angular-material.min.js) on https://developers.google.com/speed/libraries/ is throwing a 404-Error! Thanks for all your hard work Angular team!

**Comment by naomiblack** [comment]
This seems to be working ok now -- I think it may have been a brief glitch with the server. It seems to be fine now. Please file another issue if you're still seeing this.

**Comment by skolade** [comment]
@naomiblack thanks. This work alright now!
