### ISSUE TITLE
Select(md-select-label): Should have bottom border width of 2px to match md-input-container

### ISSUE THREAD

**Issue by epelc** [angular/material#2732]
`md-select`'s `md-select-label` should have a bottom border width of 2px instead of 1px so that it matches inputs within `md-input-container`.

As it is in 0.9.0
![image](https://cloud.githubusercontent.com/assets/5204642/7480198/f2b2dbe8-f334-11e4-8bac-3db7d54bb2e6.png)

With an override fix
![image](https://cloud.githubusercontent.com/assets/5204642/7480209/0eb1fd1a-f335-11e4-89c9-09eaf432db88.png)

**Comment by marcysutton** [comment]
Related to https://github.com/angular/material/issues/2720

**Comment by epelc** [comment]
@marcysutton I also notice after a select loses focus if you selected something the text and dropdown caret stay black instead of going back to light grey like the line on the bottom. Is it supposed to be like this or should I open a new issue? It looks sorta werid but I couldn't find the spec for selects.

![image](https://cloud.githubusercontent.com/assets/5204642/7480332/ed07b398-f335-11e4-8930-832d65aeae1f.png)

**Comment by rschmukler** [comment]
As per this image:

![material design spec reference image](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B_udO5B8pzrzM19KYkRJakpqNVE/components_menus_behavior2.png)

It looks like the input should have a width of `1px`, and that the select is correct.

@epelc the color should be dark if there is a value selected. See the reference above

**Comment by rschmukler** [comment]
@epelc looking at the css / labels as they are currently, it appears that they also only have a border width of 1px? Can you submit a demo... Sorry

**Comment by epelc** [comment]
@rschmukler I just looked at it again and it turns out I forgot to remove a couple of fixes for old css bugs.
