### ISSUE TITLE
MdSelect is not respecting id attribute

### ISSUE THREAD

**Issue by Sriram143** [angular/material#2733]
<md-select

 ng-model="vm.selectedOption" class="form-control material-input ng-pristine ng-untouched ng-valid md-default-theme ng-valid-required" name="Option" id="select_005" required="" ng-change="vm.selectedOptionChanged(vm.selectedOption)" aria-label="Select Option" tabindex="0" aria-disabled="false" role="combobox" aria-expanded="false" aria-required="false" aria-invalid="false"><md-select-label class="md-select-label" id="select_label_001"><span>Employee</span>

<span class="md-select-icon" aria-hidden="true"></span></md-select-label>

</md-select>

its generating random id select_005

how to stop this behavior.

**Comment by rschmukler** [comment]
@Sriram143 thanks, fixed!

**Comment by Sriram143** [comment]
Awesome. now i really love this framework
