### ISSUE TITLE
ng-message text line-height too large for message that spans multiple lines

### ISSUE THREAD

**Issue by asans** [angular/material#2734]
When an error message (or ng-message) is shown for a input field that is too long to fit on one line and spans across multiple lines, the line spacing between the lines is too large.

Here's a screen shot:

![screenshot](https://cloud.githubusercontent.com/assets/17964/7480441/60f9728c-f31d-11e4-8dfa-44473d41bece.jpg)

Notice the "value must be declared" line.  This is caused by the style:

```
md-input-container ng-message, md-input-container data-ng-message, md-input-container x-ng-message, md-input-container [ng-message], md-input-container [data-ng-message], md-input-container [x-ng-message], md-input-container .md-char-counter {
  ...
  line-height: 24px;
}
```

It might be better to set the line-height to 1rem or something that conforms to material style and adjust the top margin/padding so that the spacing is proper.

**Comment by marcysutton** [comment]
Part of the complication is the line-height of the input container affects placement of the character counter. Those two items have to be reworked at the same time.

**Comment by topherfangio** [comment]
I believe this was fixed a while ago with some other updates to the ng-messages.

<img width="258" alt="screen shot 2015-11-03 at 12 34 01 pm" src="https://cloud.githubusercontent.com/assets/54370/10919282/2d1f4eca-8227-11e5-84f7-52f6265b9dd7.png">

If you are still seeing issues after upgrading, can you please provide a Codepen which demonstrates the problem and we will reopen?
