### ISSUE TITLE
ng-binding style tag being applied onload

### ISSUE THREAD

**Issue by skribbz14** [angular/material#2736]
I'm seeing <style> being generated within my <head> that is overwriting my css. Can anyone shed light on why this is happening and any possible solutions for preventing this?

**Comment by erem-ifg** [comment]
Any updates on this? @robertmesserle?

**Comment by naomiblack** [comment]
Not clear from this issue what the problem is or how to reproduce. @erem-ifg if this is a concern for you, could you please provide a demo that we can repro in a new issue? thanks!
