### ISSUE TITLE
(bug) Ripple effect in md-list directive

### ISSUE THREAD

**Issue by thiagofront** [angular/material#2737]
I have a problem
I am using angular material for making a mobile app with Cordova
only the ripple effect in lists is very annoying when I give scroll

**Comment by mckenzielong** [comment]
dupe of https://github.com/angular/material/issues/2430?

**Comment by thiagofront** [comment]
there she spoke only `md-button` directive. But the problem is in all directives that somehow use the ripple effect

**Comment by marcysutton** [comment]
List controls use `md-buttons` under the hood, pretty sure this is still a duplicate.
