### ISSUE TITLE
mdSelect should support ngChange attribute

### ISSUE THREAD

**Issue by dozingcat** [angular/material#2740]
Other components like checkboxes and radio buttons allow specifying a handler when the value changes using an ng-change attribute, but md-select doesn't. A workaround is to manually set up a watch on the model value, but it would be more convenient to set it directly.

**Comment by rschmukler** [comment]
It [does](http://codepen.io/rschmukler/pen/bddZZG). Feel free to open a new issue with a demo if this isn't working for you.
