### ISSUE TITLE
md-chips with an input don't work when readonly becomes false.

### ISSUE THREAD

**Issue by ddimitrop** [angular/material#2742]
Example
http://codepen.io/ddimitrop/pen/MwaoBy

There are 2 mdchips, the first with a builtin input and the second with a custom input.

Initially they both work fine, but try to change their readonly mode to true and then back to false (using the checkbox in the example).

After doing that, the first still works fine but the second does not - pressing enter does not do anything

**Comment by topherfangio** [comment]
Hi @ddimitrop,

I am sorry for the delay, but I am now looking into this issue. I'm unfortunately having a bit of trouble getting your codepen to work.

Are you still experiencing this issue? If so, do you think you could update the pen so that I can see it and begin to debug?

Thanks!

**Comment by ThomasBurleson** [comment]
Determine if already fixed.

**Comment by ddimitrop** [comment]
Yes its fixed.
This is the new codepen using 0.10.1
http://codepen.io/ddimitrop/pen/gpyqMX

Thanks
