### ISSUE TITLE
disable browser autocomplete in md-autocomplete

### ISSUE THREAD

**Issue by rosinghal** [angular/material#2746]
Not able to disable browser autocomplete in md-autocomplete even after giving autocomplete="off"
![screen shot 2015-05-06 at 11 23 56 am](https://cloud.githubusercontent.com/assets/3481438/7488103/6f320ac4-f3e2-11e4-99c8-b22d1fcaff5e.png)

**Comment by DennisVis** [comment]
The directive should add autocomplete="false" instead of autocomplete="off".

**Comment by robertmesserle** [comment]
@rosinghal This is a Chrome limitation where address fields do not listen to the `autocomplete` attribute; however, we may have found a workaround which should be in master already.
