### ISSUE TITLE
md-chips checks for duplicates before md-on-append is called

### ISSUE THREAD

**Issue by webley** [angular/material#2748]
The appendChip function in chipsController.js does some duplicate-checking to prevent adding the same chip multiple times.  Unfortunately, it checks for matches before md-on-append is called.  If md-on-append converts a string input into an object, for instance, the duplicate checking will always fail.  

Presumably it should either check for duplicates after md-on-append has been called, or keep a separate collection of unmodified chips to check against.

**Comment by leejinhuey** [comment]
+1
