### ISSUE TITLE
incorrect font color with dark background

### ISSUE THREAD

**Issue by bOOm-X** [angular/material#2750]
When the theme is set to dark: 
$mdThemingProvider.theme('default')
            .backgroundPalette('blue-grey')
            .primaryPalette('light-green')
            .accentPalette('deep-orange')
            .warnPalette('red');
$mdThemingProvider.theme('altTheme', 'default').dark()
The font color for the dark theheme remains black and so the text is almost invisible. does it have to be switch to white ? The "dark" does not affect "the primary color" (no change in the toolbar)

When the dark theme is define as followed:
$mdThemingProvider.theme('altTheme')
            .backgroundPalette('blue-grey')
            .primaryPalette('light-green').dark()
            .accentPalette('deep-orange')
            .warnPalette('red');

The primary is "darked" and the font color is well switch to white for the toolbar but not for the rest.

**Comment by marcysutton** [comment]
@bOOm-X can you provide a Codepen or Plunker that demonstrates this issue? Thanks :)

**Comment by asans** [comment]
See my issue #2952 for inconsistent dark theme styles.
