### ISSUE TITLE
Toolbar in directive, scroll-shrink not working

### ISSUE THREAD

**Issue by nesler** [angular/material#2751]
Hi,

I've created a directive for a global nav-bar for my app, which creates a toolbar with some default stuff, and then transcludes page-specific content (actions etc).

Having the `md-toolbar` with `md-scroll-shrink=""` does not work, though.
As far as I can see, it never catches the `$mdContentLoaded` event, because the event is broadcast before my directive has loaded.

Is this a fault in my design, or is this an error in the way `md-toolbar` works?

**Comment by dondoco7** [comment]
mdToolbar md-scroll-shrink is not working with ng-if
ng-if create new scope.
cannot catch $mdContentLoaded

**Comment by topherfangio** [comment]
Any chance you guys could provide a demo of the exact issue so we can track it down more easily?

Thanks!

**Comment by dondoco7** [comment]
http://codepen.io/anon/pen/jPgxqb

```
<md-toolbar md-scroll-shrink="" ng-if="true">
   ...   
</md-toolbar>
<md-content flex="">
  ...
</md-content>
```

**Comment by topherfangio** [comment]
Confirmed; I have a decent idea of what the issue is and will look into it. Thanks!
