### ISSUE TITLE
Background Color Black

### ISSUE THREAD

**Issue by jakedx6** [angular/material#2752]
I was able to get the background color black by adding a new color to the palette, but shouldn't I be able to do something like the following?

`.backgroundPalette('black');`

I am getting this error

`Uncaught TypeError: Cannot read property '600' of undefined`

**Comment by rschmukler** [comment]
@jakedx6 are you defining the palette `black`? Can we see the rest of your theming code?

**Comment by jakedx6** [comment]
Here is my theme config. To make it work, I used the var black and set it to 'A100'. I first tried adding the black palette to backgroundPalette would work but it seems it looks for the 600 inside of the palette but per the color specs black and white don't have hues.

Good chance I am doing something wrong, just seems odd that black palette doesn't work like the others because it doesn't have hues.


```javascript
.config(['$routeProvider', '$mdThemingProvider', function ($routeProvider, $mdThemingProvider) {
    $routeProvider.otherwise({ redirectTo: '/home' });

    // add Orange to the color palette
    var orangeMap = $mdThemingProvider.extendPalette('orange', {
        '800': 'FFA300'
    });
    $mdThemingProvider.definePalette('orangeEncirca', orangeMap);

    //black background color
    var black = $mdThemingProvider.extendPalette('grey', {
        'A100': '000000'
    });
    $mdThemingProvider.definePalette('black', black);

    // Default Theme
    $mdThemingProvider.theme('default')
   .accentPalette('grey', {
       'default': '800',
   })
   .primaryPalette('orangeTheme', {
       'default': '800',
   });

    // Encirca Dark Theme
    $mdThemingProvider.theme('darkTheme')
    .dark()
    .accentPalette('grey', {
        'default': '200',
    })
   .primaryPalette('orangeEncirca', {
       'default': '800',
   })
    .backgroundPalette('black');

}])
```

**Comment by jakedx6** [comment]
Here is what I was expecting to work...

```javascript
.config(['$routeProvider', '$mdThemingProvider', function ($routeProvider, $mdThemingProvider) {
    $routeProvider.otherwise({ redirectTo: '/home' });

    // add Orange to the color palette
    var orangeMap = $mdThemingProvider.extendPalette('orange', {
        '800': 'FFA300'
    });
    $mdThemingProvider.definePalette('orange', orangeMap);

//not adding black to replace grey A100

    // Default Theme
    $mdThemingProvider.theme('default')
   .accentPalette('grey', {
       'default': '800',
   })
   .primaryPalette('orangeTheme', {
       'default': '800',
   });

    // Dark Theme
    $mdThemingProvider.theme('darkTheme')
    .dark()
    .accentPalette('grey', {
        'default': '200',
    })
   .primaryPalette('orange', {
       'default': '800',
   })
    .backgroundPalette('black'); // black is defined by palette alone

}])
```

**Comment by rschmukler** [comment]
@jakedx6 this is behaving as expected.

The problem with the second example is that the theme tries to look for a palette named black, which it can't find. A palette defines a bunch of colors for hues (`50`, `100`, `200`, etc.).

By defining the palette as dark, it will automatically try and use hue `800` of whatever palette is used for background (see [the source here](https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L101)). By default this is the `grey` palette, which is [defined here](https://github.com/angular/material/blob/master/src/core/services/theming/theme.palette.js#L322).

So, by calling `.dark()` you switch to the hue map linked above and it tries to use `800` in the `grey` palette.

If you want to use pure black, you can override it to use 'A200' and *not* call `.dark()`.

ie.

```js
myTheme.
  backgroundPalette('grey', {
    'default': 'A200',
    'hue-1': '300',
    'hue-2': '600',
    'hue-3': '900'
 });
```
