### ISSUE TITLE
Form doesn't become dirty when we select a value in an empty autocomplete

### ISSUE THREAD

**Issue by Izcalli** [angular/material#2753]
Hi guys,

Thank you for your work on angular material. It's amazing !
I'm trying the `md-autocomplete` [website's example](https://material.angularjs.org/#/demo/material.components.autocomplete)

When we type something in the input, the form's `dirty` flag is set to `true`.
But when the form is not dirty and we just click on the input, if we select an element, the model binded changes but the form remains clean.
Shouldn't the `dirty` flag be set to `true` ?

You can see an example on this [plunker link](http://embed.plnkr.co/PGYiAgWBkOozZUQidLef/preview)

Thanks,

Izcalli

**Comment by Izcalli** [comment]
Actually, the `md-autocomplete` is not set dirty when we select an item but when we type something in the text input. What if it was set dirty on select change ?

**Comment by Izcalli** [comment]
Sorry but it's still the same with master version.
With `md-min-length = 0`, when we select without typing anything, the form isn't set to dirty.
Here is the same [example](http://embed.plnkr.co/dMAIkHnaTSEAPOzvxzSw/preview) with angular material master version

**Comment by jalchr** [comment]
@NicolasVargas  Any luck with this issue ?
I'm facing the same problem.
