### ISSUE TITLE
Long md-list-item text goes through secondary button

### ISSUE THREAD

**Issue by wlingke** [angular/material#2759]
If the text is long, it overflows into the secondary button.

![capture](https://cloud.githubusercontent.com/assets/3145536/7499794/bb2521fe-f3de-11e4-8046-ea85672fe2dc.PNG)

**Comment by rschmukler** [comment]
@wlingke what is the html for your `md-list-item`. This seems to be working for me. Could you submit some demo code / the html for your example.

**Comment by wlingke** [comment]
```
    <md-list>
        <md-list-item class="md-1-line md-whiteframe-z1">
            <div class="md-list-item-text">
                <p>lskxdfjlksjdfjs lksdjf lksdjf lkj lkjsdf kljsdlkfjklsdjfkljsd lfkjs dlkfj skldfj lkjsdf sdlfkj sdlkfj lksdjf lksdjf lksdjf lksjdflkjsd flkjsd flkjs dflkj sldkfj lk</p>
                <md-button class="md-primary md-secondary">
                    Button
                </md-button>
            </div>
        </md-list-item>
    </md-list>
```

**Comment by rschmukler** [comment]
@wlingke try the following instead:

```html
<md-list>
    <md-list-item class="md-1-line md-whiteframe-z1">
        <div class="md-list-item-text">
            <p>lskxdfjlksjdfjs lksdjf lksdjf lkj lkjsdf kljsdlkfjklsdjfkljsd lfkjs dlkfj skldfj lkjsdf sdlfkj sdlkfj lksdjf lksdjf lksdjf lksjdflkjsd flkjsd flkjs dflkj sldkfj lk</p>
        </div>
        <md-button class="md-secondary">
            Button
        </md-button>
    </md-list-item>
</md-list>
```

**Comment by wlingke** [comment]
Just tried that, it has the same problem

**Comment by rschmukler** [comment]
@robertmesserle is refactoring the ink code which will enable us to fix this. Just a reminder for `md-ink-for` and `md-emits-ink-for` directives

**Comment by Kalix86** [comment]
Is there any quick fix for this?

happening for me but with md-icon instead of md-button

**Comment by Kalix86** [comment]
Adding a 'padding-right' to <p></p> tags seems to work. Where the padding is the width of the button/icon.
