### ISSUE TITLE
md-toolbar's md-scroll-shrink show strange behavior while inside md-sidenav

### ISSUE THREAD

**Issue by redyyu** [angular/material#2760]
### double scroll bar show up while a md-toolbar with md-scroll-shrink in side md-sidenav.

![screen shot 2015-05-07 at 2 25 35 am](https://cloud.githubusercontent.com/assets/724821/7500582/13184ae4-f461-11e4-9361-afb66acd2b07.png)

### It will be ok after add  overflow:hidden for md-sidenav, but it must wait a while
I have take look the source code. it's force to wait 5s, if it is designed then it's not a problem.
``` 
var debouncedUpdateHeight = $mdUtil.debounce(updateToolbarHeight, 5 * 1000);
```

![screen shot 2015-05-07 at 2 04 49 am](https://cloud.githubusercontent.com/assets/724821/7500624/3fb1ff28-f461-11e4-8f7b-3c4e85f3c4fd.png)

========================

If I remove the layout="column" from md-sidenav
the toolbar can't never sticky on top. It's happened on http://material.angularjs.org too.
but It's seems not problem at all, is it? 

![screen shot 2015-05-07 at 2 30 30 am](https://cloud.githubusercontent.com/assets/724821/7500679/b8395b94-f461-11e4-9eeb-0b83fbb3f1f1.png)

When I set no 'layout' and set css overflow:hidden,
sidenav's scrollbar only show up 1s at beginning, then disappear.
if the layout is required attrs, then it's not problem too.

![screen shot 2015-05-07 at 2 38 17 am](https://cloud.githubusercontent.com/assets/724821/7500864/21b5352e-f463-11e4-81fe-2a4059666e5a.png)

**Comment by redyyu** [comment]
I find the md-content scrollbar is not fit the height.

![screen shot 2015-05-07 at 9 04 12 pm](https://cloud.githubusercontent.com/assets/724821/7515861/5075af98-f4fd-11e4-99aa-cf5745aa5503.png)

I feel so strange should have 5s to wait the toolbar height set for shrink.
What's that for?
Can we get some attributes set that up? or some way to override it?

code again
```javascript
var debouncedUpdateHeight = $mdUtil.debounce(updateToolbarHeight, 5 * 1000);
```

**Comment by naomiblack** [comment]
@topherfangio can you repro?

**Comment by topherfangio** [comment]
I believe many of these issues have been fixed with recent updates to toolbar/scroll-shrink as can be seen in the following demo: http://codepen.io/topherfangio/pen/dYoNBG?editors=101

Please post a new issue if you are still experiencing any issues.
