### ISSUE TITLE
Jumpy indeterminate progress bar animation

### ISSUE THREAD

**Issue by tehshane** [angular/material#2762]
The animation of the indeterminate progress bar seems jumpy and haphazard, with the indicator stuttering and jumping back and forth instead of moving smoothly forward.

Angular-Material version:
![Jumpy animation](http://i.imgur.com/cHM42s7.gif)

Smooth:
![Smooth animation](https://raw.githubusercontent.com/lightningtgc/MProgress.js/gh-pages/styles/images/indeterminate.gif)

```Browser: Chrome 42.0.2311.135 on OSX 10.10.3```

**Comment by robertmesserle** [comment]
Yes! I have a fix for this already, will implement when I'm at a computer.
