### ISSUE TITLE
Tab movement breaks after clicking on last tab

### ISSUE THREAD

**Issue by djvs** [angular/material#2765]
Angular 1.4.0 rc2, CDN copies of Material at time of writing.  Not sure how easy to replicate.  Tab nav buttons still do the red "radiating" thing, but won't change tab.  Copy and pasted the code right from the demo.

**Comment by djvs** [comment]
It's this "locked" thing in MdTabsController.  WTF?

**Comment by robertmesserle** [comment]
@djvs Is this still an issue?  I believe this may have been related to issues in 1.4.0 rc2 that were resolved already.

**Comment by djvs** [comment]
Will check later

**Comment by robertmesserle** [comment]
Just confirmed that this issue was present in RC2 but is resolved now.  Closing for now - please let me know if it is still occurring and I will reopen.
