### ISSUE TITLE
why without Carousel

### ISSUE THREAD

**Issue by zhanyouwei** [angular/material#2766]
please tell me

**Comment by foucist** [comment]
http://shouldiuseacarousel.com/

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](
https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by marcysutton** [comment]
Haha, actually please don't post that on the Forum, but your sentiment is correct. The Carousel is a bad user interface pattern for multiple reasons.
