### ISSUE TITLE
mdSelect cuts off label text in IE

### ISSUE THREAD

**Issue by dozingcat** [angular/material#2769]
Open https://material.angularjs.org/#/demo/material.components.select in IE (I used IE 11 under Windows 8.1). The mdSelect labels are truncated to just the first few characters, as shown in the attached screenshot.

Setting min-width on the md-select element is a possible workaround, but inconvenient if you don't know the width in advance.

![ie-mdselect](https://cloud.githubusercontent.com/assets/489398/7516080/97f3c8ea-f49a-11e4-8835-ed6824d0a4a3.png)

**Comment by tinusn** [comment]
another workaround is to place it in an md-input-container

**Comment by dozingcat** [comment]
md-input-container doesn't seem to have any effect for me: http://codepen.io/anon/pen/LVGGBX (displays as expected in Chrome and Firefox, truncated in IE). Do you have an example?

**Comment by tinusn** [comment]
It had an affect on a problem I had, but I see now that it was because of the layout surrounding the select box. Mine was fixed because it flexed to the surrounding box - and as you said, that could be solved by having a min-width, but I agree that it is not the best solution.

Anyone else have a solution for this?

**Comment by Londovir** [comment]
Looks like multiple culprits in IE11 could be to blame. After some quick tinkering, I seem to have narrowed it down to some CSS being applied as a result of the `.md-select-label :first-child` selector, and I can restore reasonable behavior by applying these two CSS styles:

    flex-basis: auto;
    overflow: visible;

It seems to make it behave correctly in IE11, but I imagine there's got to be some issues with that I'm not seeing right now. Again, this is just a rapid check on my end as I'm plowing through other IE11 issues.

**Comment by robertmesserle** [comment]
@dozingcat Is this still an issue in 0.10.0?  I believe it should have been resolved.  Closing for now, will reopen if it is still valid.

**Comment by Londovir** [comment]
Still an issue, at least based upon the demo site https://material.angularjs.org/HEAD/#/demo/material.components.select

**Chrome Examples**
![image](https://cloud.githubusercontent.com/assets/11982575/8214273/232787c8-14f6-11e5-86c8-76db1fa9c5bc.png)

![image](https://cloud.githubusercontent.com/assets/11982575/8214278/2cce1648-14f6-11e5-87c9-2afd6a80be8c.png)

![image](https://cloud.githubusercontent.com/assets/11982575/8214284/34d73d1a-14f6-11e5-8061-37805fdb1f8d.png)

**IE 11 Examples**
![image](https://cloud.githubusercontent.com/assets/11982575/8214294/4289c9c8-14f6-11e5-9626-e445d17efae2.png)

![image](https://cloud.githubusercontent.com/assets/11982575/8214298/4a5f8a8e-14f6-11e5-9f5d-22b0c72f909f.png)

![image](https://cloud.githubusercontent.com/assets/11982575/8214307/532312bc-14f6-11e5-985b-37cb17459dc5.png)

**Comment by sitic** [comment]
Yes, this is still an issue with 0.10.0. 
I'm using
```
.md-select-label :first-child{
  flex-basis: auto;
  max-width: 100%;
  overflow: hidden;
}
```
to have the same behavior as in Chrome.

**Comment by barryvdh** [comment]
I also have this issue. Remove `display:flex` seems to fix it.

**Comment by dozingcat** [comment]
I'm still seeing this in IE as well. The demo page select components are still truncated, and you can also see a simple example at http://codepen.io/anon/pen/LEmgvE

**Comment by ThomasBurleson** [comment]
@rschmukler - reopened.

**Comment by wlingke** [comment]
In IE 10 - the arrow is below the text

![capture](https://cloud.githubusercontent.com/assets/3145536/8534211/0c89098a-23ef-11e5-877b-afadb9902c3c.PNG)

**Comment by sitic** [comment]
@wlingke that is issue #2213

**Comment by kikhtenko** [comment]
+1

**Comment by pradeep330** [comment]
Add this for ie 10 fix..

@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .md-select-value *:first-child { display:block }
}

**Comment by pradeep330** [comment]
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .md-select-value .md-select-icon::after { float: right; }
    md-select .md-select-value { height: 25px; }
    .md-select-value *:first-child { display:block }
}

**Comment by rschmukler** [comment]
This is fixed on master. Closing.
