### ISSUE TITLE
The grey color palette has a shade '0' which isn't a valid hue value.

### ISSUE THREAD

**Issue by TylerDixon** [angular/material#2771]
In [theme.palette.js](https://github.com/angular/material/blob/master/src/core/services/theming/theme.palette.js#L326) there is a grey theme listed with a shade of value '0', which isn't defined as a valid value [here](https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L120). So the following code:
```js
$mdThemingProvider.theme('default')
            .backgroundPalette('grey', {
              'default': '0',
              'hue-1': '50'
            });
```

Yields the error:
`Invalid hue value '0' in theme default's background color grey. Available hue values: 50, 100, 200, 300, 400, 500, 600, 700, 800, 900, A100, A200, A400, A700`.

**Comment by rschmukler** [comment]
Good catch. You can get `#fff` by using `A100` if you need it.
