### ISSUE TITLE
npm version number does not match angular material release version

### ISSUE THREAD

**Issue by weikinhuang** [angular/material#2775]
The version on npm is 0.9.2, but the current latest version is 0.9.0. This is an issue for me because in my templates I do:
```html
{{#if is_cdn}}
<script src="//ajax.googleapis.com/ajax/libs/angular_material/{{pkg.dependencies.angular-material}}/angular-material.min.js"></script>
{{else}}
<script src="node_modules/angular-material/angular-material.js"></script>
{{/if}}
```

**Comment by ThomasBurleson** [comment]
We discussed the reasoning for this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial). This will be resolved in the next formal release.
