### ISSUE TITLE
Plans for custom builds?

### ISSUE THREAD

**Issue by cgat** [angular/material#2777]
I'm wondering if there is anything in the pipeline for custom builds, in a similar manner to bootstrap(http://getbootstrap.com/customize/). More specifically, if someone wants to only use certain components, will you support a feature that builds a version of angular-material that with only those components and their dependencies?

What's your best advice to achieve this at the moment? Just download the source files for the desired directives as well as all the angular-material css?

Thanks

**Comment by epelc** [comment]
Yes they are planning to let you pick and choose which components you get. I believe it's planned for `0.10.0` check the milestones page for more info.

**Comment by richtier** [comment]
I wish I saw this before [I created my own solution](http://richardtier.com/2015/06/28/angular-material-design-custom-build-include-only-the-parts-you-need/) :)

**Comment by fant0m** [comment]
+1 it's really important for people who are trying to speed up app as much as possible

**Comment by vdclouis** [comment]
any news on this? would be awesome!

**Comment by kasajian** [comment]
:+1:

**Comment by kasajian** [comment]
What if I just want to use the DatePicker.   Do I have to load a 430KB css and 287KB js file?  (minified not gzipped)

**Comment by richtier** [comment]
@kasajian [see here](https://richardtier.com/2015/06/28/angular-material-design-custom-build-include-only-the-parts-you-need/)

**Comment by kasajian** [comment]
That's very nice.   Thank you so much for doing that.

**Comment by ThomasBurleson** [comment]
Check out the [modules](https://github.com/angular/bower-material/tree/master/modules) which has
`layouts`, `scss`, `compiled css`, and individual components.
