### ISSUE TITLE
row.selected not working with md-checkbox

### ISSUE THREAD

**Issue by sudeshnaDatta** [angular/material#2780]
How to use row.selected to select an entire row data of a grid if the md-checkbox is being used to select an entire row of a grid

**Comment by marcysutton** [comment]
Please provide a Codepen or Plunker that demonstrates this issue. Thank you.

**Comment by sudeshnaDatta** [comment]
<md-checkbox  tabindex="-1" class="ngSelectionCheckbox" aria-label="&nbsp" ng-model="row.selected" ng-change="row.selected" ></md-checkbox>

when used in the checkboxCellTemplate og ng-grid does not select the row data

**Comment by sudeshnaDatta** [comment]
when used in the checkboxCellTemplate of ng-grid does not select the row
data

md-checkbox tabindex="-1" class="ngSelectionCheckbox" aria-label="&nbsp"
ng-model="row.selected" ng-change="row.selected" ></md-checkbox

On Fri, May 8, 2015 at 10:54 PM, Marcy Sutton <notifications@github.com>
wrote:

> Please provide a Codepen or Plunker that demonstrates this issue. Thank
> you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/2780#issuecomment-100303661>.
>



-- 
Regards,
Sudeshna Datta
Zaloni Technologies India Pvt. Ltd.
Guwahati
sudeshna@zaloni.com
Mob: +91 9678072070
 www.zaloni.com



This e-mail, including attachments, may include confidential
and/or proprietary information, and may be used only by the person or
entity to which it is addressed. If the reader of this e-mail is not the
intended recipient or his or her authorized agent, the reader is hereby
notified that any dissemination, distribution or copying of this e-mail
is prohibited. If you have received this e-mail in error, please notify
the sender by replying to this message and delete this e-mail immediately.

**Comment by dmackerman** [comment]
To be clear, this involves 3rd party code?

**Comment by sudeshnaDatta** [comment]
This involves embedding md-checkbox within *angular-grid* inorder to be
able to select a row

On Wed, May 13, 2015 at 2:01 AM, Dave Ackerman <notifications@github.com>
wrote:

> To be clear, this involves 3rd party code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/2780#issuecomment-101411458>.
>



-- 
Regards,
Sudeshna Datta
Zaloni Technologies India Pvt. Ltd.
Guwahati
sudeshna@zaloni.com
Mob: +91 9678072070
 www.zaloni.com



This e-mail, including attachments, may include confidential
and/or proprietary information, and may be used only by the person or
entity to which it is addressed. If the reader of this e-mail is not the
intended recipient or his or her authorized agent, the reader is hereby
notified that any dissemination, distribution or copying of this e-mail
is prohibited. If you have received this e-mail in error, please notify
the sender by replying to this message and delete this e-mail immediately.

**Comment by rschmukler** [comment]
Kicking to backlog until we see a demo.
