### ISSUE TITLE
md-tabs does not inherit md-theme from outer definition

### ISSUE THREAD

**Issue by kschwidder** [angular/material#2782]
The md-tabs is surrounded by an md-toolbar. The md-toolbar defines md-theme="light-blue" but the md-tabs are still using the default theme (purple, etc.).
In version 0.8.x the md-tabs inherited the style from above. What is missing to override the md-tabs theme ? (I also added an md-theme to the tabs which also does not change the coloring at all)

    <md-toolbar md-theme="light-blue" layout="row" layout-align="start center">
        <div flex="5" flex-sm="15">
        </div>
        <div flex="5" flex-sm="15" layout-align="start center">
            <md-button layout-align="start center" aria-label="Leads" ng-click="goBack()">
                <img src="template/icons/view/ic_arrow_back_white_24dp.png">
            </md-button>
        </div>
        <div flex="25" flex-sm="20" layout="row" layout-align="start center" flex="25" layout-padding>
            {{getNickName().length ? getNickName() : getName()}}
        </div>
        <md-tabs flex="60" flex-sm="50" layout-padding layout-align="end center" md-selected="tabs.componentIndex">
            <md-tab md-active="tabs.componentIndex === 0">
                <md-tab-label>
                    <span ui-sref="index.project.engage({id:getId()})">{{'PROJECT_PLAN' | translate}}</span>
                </md-tab-label>
            </md-tab>
            <md-tab md-active="tabs.componentIndex === 1">
                <md-tab-label>
                    <span ui-sref="index.project.detail({id:getId()})">{{'PROJECT_DETAILS' | translate}}</span>
                </md-tab-label>
            </md-tab>
        </md-tabs>
        <div flex="5" hide-sm layout-padding layout-align="end center">
        </div>
    </md-toolbar>

Thx in advance for the great efforts.

**Comment by dohomi** [comment]
Hi Guys,
Would be great if tabs inside of toolbars would be supported or a how-to documented inside the docs. According to the specs http://www.google.com/design/spec/components/tabs.html#tabs-types-of-tabs it seems to be quite heavily used. I've seen this behavior now on several apps. Thanks!

**Comment by kschwidder** [comment]
+1

**Comment by robertmesserle** [comment]
As far as I can tell from my local testing, this is working properly.

@kschwidder In your example, it looks like you gave `palette` examples which is no longer how theming works.

http://codepen.io/robertmesserle/pen/LVxzNW?editors=101

@dohomi Does the above example help?

**Comment by kschwidder** [comment]
Thx a lot. I missed that.

**Comment by dohomi** [comment]
@robertmesserle thanks for the example, but how do you display the ```md-tab-body```content? Would be great if you guys would show an example in your docs how to make use of this feature. All your example shows the content of the tab wraps inside of ```md-tab```but this breaks the whole design. Thanks!

**Comment by robertmesserle** [comment]
@dohomi Sure, I've updated the example to include tab-content.

http://codepen.io/robertmesserle/pen/LVxzNW?editors=101

For this use-case, the tabs can't actually live inside of the toolbar; however, putting them immediately after the toolbar should be visually the same.

**Comment by dohomi** [comment]
@robertmesserle I was too blind that simply ```class=primary```is giving me the same look as the toolbar. Thanks!

**Comment by Seiifer** [comment]
Is there also any way to center the label ("One", "two", "Center") in the tab 'header' ?
