### ISSUE TITLE
md-autocomplete: multiple items focused

### ISSUE THREAD

**Issue by RaphaelYanis** [angular/material#2784]
If I go through the items in an autocomplete list, I am able to have more than one item focused, like the image suggests:
![autocompl](https://cloud.githubusercontent.com/assets/12083337/7542935/97087c22-f5b8-11e4-9a32-76a02cbcee1f.png)

**Comment by marcysutton** [comment]
Only one item is actually focused. That looks like the multi-select feature, not a bug.
