### ISSUE TITLE
md-tooltip does not position correctly with vertical scroll

### ISSUE THREAD

**Issue by dragonflypl** [angular/material#2791]
Hi,

in my app my md-content has vertical scroll. When I hover over button to show tooltip and scroll has position 0, then tooltip appears in correct place. But when I scroll down, tooltip does not follow the scroll. Is appears over the button. Is it a bug or do I have something wrong with my layout? (I use flexbox...). Or maybe you could help me with telling how tooltip positions itself?

Thanks,
Paweł

**Comment by edoardocavazza** [comment]
I have the same behaviour too :(

**Comment by dragonflypl** [comment]
It exists on current version of documentation, eg. https://material.angularjs.org/latest/#/layout/grid on Chrome 39, when accessing tooltips for "View Source"

**Comment by dohomi** [comment]
+1. Is there anything possible for a workaround? I use tooltips for a database scroll and the tooltips doesn't work at all currently in ```rc3```. Thanks

**Comment by SanderElias** [comment]
I have looked into this briefly. I suspect #5654 might help here.

**Comment by jschlieber** [comment]
Same Problem here (rc3)... happens when scrolling inside md-content

**Comment by breity** [comment]
+1

**Comment by r0b-** [comment]
+1 (rc4)

**Comment by SanderElias** [comment]
@r0b- Can you check if #5809 works for you too? If so, you can close your PR please?

**Comment by r0b-** [comment]
Looks good - Thanks!

**Comment by vovafeldman** [comment]
When do you plan to merge it with the master?

**Comment by mkyukov** [comment]
So is this solved? I'm still getting that alignment problem and can't seem to find a workaround for it.

**Comment by mawaheb-seraj-devtech** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by Darksoulsong** [comment]
Still happening on 1.0.9. Tooltip is showing, but the position is incorrect. It's out of the visible portion of the page, close to the top.

**Comment by dohomi** [comment]
+1 again...

**Comment by lolptdr** [comment]
Had same issue and modified the ns-tooltip's position from "absolute" to "fixed" and it looks fixed. Got the idea from the closed #5809, which actually uses this same logic but the use case seems narrow.

Using version 1.1.0-rc2.

**Comment by michahell** [comment]
Kudo's to you, @lolptdr, for coming up with a solution for something that seems pretty trivial but still got the annoying 'blanket wontfix' answer.
