### ISSUE TITLE
Align button to the bottom of the sidenav menu

### ISSUE THREAD

**Issue by rtubio** [angular/material#2792]
In the following JSFiddle (https://jsfiddle.net/rtubio/svt4ga38/) I am trying to align the "About" button to the bottom of the menu. I have tried using a <div> element with several variations (flex, layout="vertical" and flex, width:100%) but nothing seems to work. I have gone through the layout alignment examples within the documentation at the Angular Material website (https://material.angularjs.org/#/layout/alignment), but the closest I could find was how to align all the buttons close to the top or close to the bottom.

In my case, I am trying to align all the buttons at the start (column-wise) and only one of them at the botton. Is this possible with the current implementation of Angular Material?

**Comment by george3447** [comment]
+1

**Comment by omeid** [comment]
Use two `md-list` for top and bottom elements and set `layout-align` on `md-sidenav` to `space-between center`.
