### ISSUE TITLE
md list item and in line styles

### ISSUE THREAD

**Issue by JohnAReid** [angular/material#2795]
I have been trying to change without success the background of the md list item using ng-class (using md-primary for selected list item) - but this seems to be getting really difficult - is this by design?

**Comment by rschmukler** [comment]
@JohnAReid to clarify, you want a way to simulate the focus color on a `md-list-item` using `ng-class`? Currently `md-list-item` doesn't respond to `md-primary`, but we could add it if it's a needed use case.

**Comment by JohnAReid** [comment]
I really was after the ability to change the background color of a list item to indicate which of the list items was currently selected  (I do not think the md-list has a selected property but perhaps this is something which will come with time).

I currently use ng-class to change the border of the selected list item - which works but will not change the background color, I would prefer to be able to use md-primary or md-accent as  the class name used within the ng-class code simply to keep it in line with material design ideal.
Example of use:

![image](https://cloud.githubusercontent.com/assets/7714810/7731116/245db158-ff16-11e4-8ff0-a7de5331eeb2.png)

**Comment by rschmukler** [comment]
@JohnAReid will discuss at next meeting to see if this is functionality that `md-list-item`s should provide

**Comment by rschmukler** [comment]
Escalating to the UX team to talk about it.

**Comment by faustomorales** [comment]
I assume you're attaching an ng-click to your md-list-item. If so, I realized the reason this doesn't work is because the md-list-item directive is creating a child button within the md-list item. So, assuming you're applying the "selected" class on your md-list-item, you would write your CSS selector as .md-list-item.selected button { background-color: red }. Doesn't get you md-primary, I know, but thought this would be useful to you.

**Comment by JohnAReid** [comment]
@faustomorales Thanks - but could not get  CSS selector.

**Comment by JohnAReid** [comment]
@faustomorales You are a star - whilst the css  .md-list-item.selected button { background-color: red }. did not work, removing the ng-click  did work and I can now set the backgrund colour using ng class.

**Comment by chinnichaitanya** [comment]
@faustomorales Thanks for the point. It gave me some clarity.
 
In my case, I have ```ng-click``` to the ```md-list-item``` and I want to change the ```color``` on hovering similar to how Google sheets does. But I'm not able to change the color of the child-button using CSS selectors.
Can anyone please help me in this regard.

**Comment by JohnAReid** [comment]
@faustomorales I assign the class 'pathitem' to the  md-list-item element and use the following:

.pathitem{
    margin-bottom: 6px;
    border: silver thin solid;
    margin-top: 2px;

}

.pathitem:hover{
    color: blue;
    box-shadow: 4px 4px 4px darkgray !important;
}


What I also did was to insert the md-list-item element inside a <a href> and move the ng-click into there - which meant I could change the background colour.

**Comment by chinnichaitanya** [comment]
@JohnAReid  Inserting ```md-list-item``` inside ```<a></a>``` tags ? Is it not adding the hyperlink to all the content in the list-item ?

**Comment by JohnAReid** [comment]
@faustomorales - I am very lucky my list items are just a single item, I had to use the a tags to get ui-router to call the state correctly.  I think my main point is surround the  md-list-item element with something like div and put the ng- click into there -  that way the directive is not creating a child button within the md-list item.

**Comment by chinnichaitanya** [comment]
@JohnAReid I've already tried that. If I move ```ng-click``` to the parent element lets say ```<div>```, I'm losing the *ripple* effect created on clicking the *list-item*. 
That is why I'm trying to get do it through CSS alone.

**Comment by JavierCVilla** [comment]
I've been trying to modify the color of the *ripple effect* of the button generated and I've found with this trouble too. To modify that, I need to add the `md-primary md-hue-1` classes (the color it's defined by *mdProviderTheme*) to the button generated by the `md-list-item` with the `ng-click` attribute, but I can't. This button is generated with `md-no-style md-default-theme` and it's not possible to add any css class. Certainly, I have other possibility to do that, but it means to modify all the current structure of my `md-list-item`. I think it would be a great functionality that `md-list-items` could provide the options to custumize the element auto-generated.

**Comment by code-tree** [comment]
I noticed this issue was closed by the author, however, it seems like this is something that should be provided. i.e. the ability to add a 'selected' class to a list item that auto-adds the appropriate styling from the active theme.

I noticed two different examples of selected item styling in the [Material Design spec](https://www.google.com/design/spec/layout/structure.html#structure-side-nav).

**Comment by ido567** [comment]
I'v faced a similar issue, I managed to track the active item by myself and add the _md-accent_ class to it.
But the class is not changing anything when the _md-list-item_ has ng-click attribute (because of the button wrapper).

There is a way to fix that?

**Comment by CabuxaMapache** [comment]
@faustomorales please remove the first "." of ".md-list-item.selected button". Apart from that, your answer is working very well, thanks!

**Comment by haenig** [comment]
There is still no way to add theming classes to the auto-generated md-button within md-list-item. I do not understand why the option is not available so far. Without it, no proper theming is possible!

**Comment by zilberas** [comment]
I was able got achieve a desired efffect using inner shadow. Works with ng-class on md-list-item
.selected {
  color: white;
  -webkit-box-shadow:inset 0px 0px 0px 25px #b0b0b0;
  -moz-box-shadow:inset 0px 0px 0px 25px #b0b0b0;
  box-shadow:inset 0px 0px 0px 25px #b0b0b0;
}

**Comment by fabio-vitali** [comment]
@zilberas: It not solves the requirement expressed by @haenig (and mine, I'm working with multiple themes)
