### ISSUE TITLE
mdCheckbox: support values with 0,1

### ISSUE THREAD

**Issue by fant0m** [angular/material#2796]
Current checkbox value works only with true, false. Wouldn't it be better if it works with 1,0 either? Because mostly when you get data from database you get 1,0 instead of true, false.
```
// current approach
$scope.data.cb4 = false;
$scope.data.cb5 = true;

// new approach
$scope.data.cb2 = 0;
$scope.data.cb3 = 1;
```

**Comment by dmackerman** [comment]
You can use `ng-value` and set them to whatever you want.

**Comment by fant0m** [comment]
and? It's not solving anything. Md-checkbox is working only with true, false and I think it should also work with 0,1.

**Comment by ThomasBurleson** [comment]
@dmackerman - sounds reasonable... want to enhance and submit a PR?

**Comment by ilanbiala** [comment]
Or any truth value really, no?

**Comment by DevVersion** [comment]
@topherfangio said:
> I think since we have the ng-true-value and ng-false-value parameters, this is not actually necessary. However, it is a very nice convenience. If we're going to add this and make this the default, though, then I think we should expand this PR to support any truthy/falsy values, not just true/false and '0'/'1'.

> Also, looking into the future, what number/value would we use to represent a mixed-state checkbox? The first thought that comes to mind is -1, but if we don't currently implement that functionality, then it will start out where that value is truthy, and we'd have to change it later to be mixed...

In addition to Tophers thoughts, we should for #7643.

**Comment by ajsb85** [comment]
Example to use:
```HTML
      <md-checkbox ng-true-value="1" ng-false-value="0"/>
```
