### ISSUE TITLE
md-fab gets squashed upon resize

### ISSUE THREAD

**Issue by uriva** [angular/material#2797]
codepen: http://codepen.io/uriva/pen/doGVMx

**Comment by ThomasBurleson** [comment]
md-fab {
  min-width:56px;
}

**Comment by uriva** [comment]
Hi, I'm not sure this is fixed (still broken in the attached codepen)

**Comment by uriva** [comment]
@robertmesserle 
@ThomasBurleson

**Comment by calebegg** [comment]
The fix was removed in e1c3d33

**Comment by robertmesserle** [comment]
@calebegg Good catch!
@ThomasBurleson Any reason we can't re-add the removed code?

**Comment by jelbourn** [comment]
The button should be `display: inline-block` on the outermost element, but it should also not be squashed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
