### ISSUE TITLE
$mdToast is supported multiple 'toast' at same time?

### ISSUE THREAD

**Issue by redyyu** [angular/material#2799]
Which mean is multiple toast showing up same time 

etc., top left

[TOAST#1]
[TOAST#2...]
[TOAST#2........]

just like 
http://ui.lumapps.com/directives/dialogs

try click the button 'OPEN DIALOG' couple times, see the toast bottom right. it's follow a line

**Comment by Rouby** [comment]
Toasts are per design specs limited to one.

"They should not be persistent or be stacked, as they are above other elements on screen."
http://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage

**Comment by piyushchauhan2011** [comment]
@Rouby I don't understand why this is a bad UI, many websites use many toasts as suggested by @redyyu

**Comment by redyyu** [comment]
If the Specs said that, we should follow it.

**Comment by ThomasBurleson** [comment]
Stacked dialogs, toasts, snackbars, bottomsheets, etc. will not be available until post v1.0 releases.

**Comment by ThomasBurleson** [comment]
Stacked Toasts are not supported/recommended by Google's UX team. As such this will not be feature within the `angular/material` repositories.

**Comment by aminahmedkhan** [comment]
i need this thing ! +1

**Comment by Lorelei** [comment]
+1

**Comment by Lord27** [comment]
+1

**Comment by RuslanaGRA** [comment]
+1

**Comment by pteyssedre** [comment]
+1

**Comment by steffanboodhoo** [comment]
+1

**Comment by Narretz** [comment]
Interesting. Should subsequent toasts / messages be queued and then displayed one-by-one?

**Comment by bradrich** [comment]
Please see the documentation for **Consecutive Snackbars** located here: https://material.google.com/components/snackbars-toasts.html#snackbars-toasts-usage.

**Comment by almgwary** [comment]
+1

**Comment by eniniz** [comment]
+1

**Comment by jhlee8804** [comment]
+1

**Comment by kikocastro** [comment]
+1

**Comment by piyushchauhan2011** [comment]
I don't know why it's not supported but many websites do this, even twitter and facebook. Sample of screenshot is added below.

A Tweet in popup and then clicking retweet open another popup.
![screen shot 2016-10-10 at 4 38 36 pm](https://cloud.githubusercontent.com/assets/693487/19227642/1a18abb6-8f08-11e6-8a6e-8ad7669b24d7.png)

**Comment by jchoca** [comment]
They do this in Google Keep. Maybe web apps are an exception?

![stacked_toasts](https://cloud.githubusercontent.com/assets/5007965/19447988/a9d8258c-9454-11e6-9fae-4fc886275998.png)

**Comment by manish2535** [comment]
This is a great feature to have. If I am calling multiple methods to do multiple things, I could display Success or Unsuccessful messages simultaneously. Right now I have to accumulate the two responses and then display a single toast. While this works, it pretty annoying to wait to every method call to complete to show messages.

**Comment by bradrich** [comment]
I am currently working on this feature for toasts. It is a part of the conversion of this component to the panel API. I will keep this thread updated.

**Comment by hanu18** [comment]
We need multiple toasts for multiple events one by one. it is very basic and useful feature requirement.
Please update for this ASAP.
 @ThomasBurleson  any update on this ?

Please help

**Comment by JCherryhomes** [comment]
Instead of showing multiple toasts simultaneously could you create a queue that would display the toasts as soon as the previous one disappears?

**Comment by hanu18** [comment]
@JCherryhomes  I can't wait until previous disappear in that case next will loose its significance.
I need to show all on priority.

**Comment by mmumshad** [comment]
+1 Need this!

**Comment by bobwah** [comment]
+1

**Comment by swizzmagik** [comment]
+1

**Comment by DOCbrink** [comment]
+1

**Comment by eugene-belkovich** [comment]
+1

**Comment by juanenrisley** [comment]
+1

**Comment by bluematches** [comment]
+1

**Comment by nnmrts** [comment]
+1

**Comment by vladb95** [comment]
+1

**Comment by NijsTom** [comment]
+1

**Comment by ashvinmay** [comment]
+1

**Comment by matewilk** [comment]
+1 😄

**Comment by Tryforce** [comment]
+1

**Comment by th3n3rd** [comment]
+1

**Comment by rafaeldev** [comment]
+1

**Comment by andrewsaad** [comment]
+1

**Comment by rochejul** [comment]
+1

**Comment by Dhanani** [comment]
+1

**Comment by Jack-Works** [comment]
+1 Need this, In my environment, I can not send user notification in any way, (like HTML5 Notification API), I have to use multiple toasts to store some short information to the user.

**Comment by mtrzos** [comment]
+1

**Comment by pierrecheron** [comment]
+1

**Comment by jayagl** [comment]
+1

**Comment by flookami** [comment]
+1

**Comment by gabguy** [comment]
+1

**Comment by annnguyen** [comment]
+1

**Comment by AdrianZielonka** [comment]
+1

**Comment by angelshurikan** [comment]
Astuce

#toasters {
    position : fixed;
    top      : 0;
    right    : 0;
    left     : 0;
    z-index  : 199999;
}

#toasters > * {
    position : static;
    bottom   : auto;
}

**Comment by bennekrouf** [comment]
We understand that it is not recommended by UX team. But it could be an option, not the default one.

**Comment by omidgharib** [comment]
+1 need this

**Comment by trivett** [comment]
+1 would love to have this, but will find a different way of doing it for now.

**Comment by Possardt** [comment]
+1 would like moar than one piece of toast at a time.

**Comment by nicu-chiciuc** [comment]
2 years and still not a clear solution.

**Comment by xandorxicay** [comment]
+1

**Comment by chunkydigits** [comment]
For those that aren't really bothered about Google telling you what to do and aren't worried about showing duplicates, there is a way to do this in CSS if you have SASS (or you can include the transpiled CSS). 

```
#appRoot {
  $var: 0;
  @for $i from 1 through 5 {
    md-toast:nth-child(#{$i}) {
      top: #{$var}px;
      $var: $var + 55;
    }
  }
}

```
it's rudimental and could do with some other functionality (i.e. removing dupes) but I suspect that most of it can be done in JS world. In the example, anything over 5 will be hidden behind the first. Could add a > 5 case too if you wanted it to appear behind the 5th. 

Hope this helps.

**Comment by xenohunter** [comment]
+1

**Comment by marcelagraz** [comment]
+1

**Comment by Splaktar** [comment]
There are no resources available to work on these kinds of nice to have, non-core, features that don't align with the Material Design spec. We are already too far behind on tasks that are needed to align with the spec.

Our current recommendation is to use the workarounds above or to find/create a new third party toast library that has the robust feature set that you require.
