### ISSUE TITLE
md-tabs gesture to switch tab is severely broken.

### ISSUE THREAD

**Issue by wesalvaro** [angular/material#2801]
Consider disabling by default.

Two major issues:

1. If an input box is in the tab, selecting the text at a normal speed causes tab switch.
1. Similarly, any control (like a map) causes false positive gestures.
1. Using the gesture selects text in the tab. Creates a non-polished experience.

1 and 2 are extremely annoying and make me consider this behavior broken.

Alternatively, how can I disable gestures globally (as I do not want them)?

**Comment by wesalvaro** [comment]
I found the $mdGesture service in the source, but there is no option to disable it?

I have hacked a disable by providing the following in my application module:
```javascript
.constant('$mdGesture', {})
```

**Comment by wesalvaro** [comment]
[Example codepen](http://codepen.io/anon/pen/PqZRWQ)

**Comment by robertmesserle** [comment]
@marcysutton @ThomasBurleson I'd be fine with removing gesture support from the content area - thoughts?

**Comment by marcysutton** [comment]
I'm not having any trouble selecting the text field by first tapping inside to select in iOS. Are you normally able to select text within a form field without bringing up the keyboard first?

**Comment by ThomasBurleson** [comment]
@robertmesserle - let's have a conf call to discuss the tradeoffs. Thx

**Comment by wesalvaro** [comment]
I'm talking about selecting the text on a PC.

Text selection on Mobile is completely different and gestures on a PC are almost completely useless.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (400/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:56420 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZA-001Ywh-Cm
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:42 +0200
Date: Thu, 28 Apr 2016 13:27:42 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875262;
	bh=I3TjgT8hn9fzg0lPed0RmLhDi8SyzK/AMq4WujeEjRI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=MDmiu4w+4pX5hbDW6WdR2oPfcZjUIZZz0ZcjxsjIDZfDmqjdr0hgP+s06UaIj+2PK
	 F+99/4SpC7x0Y+H16TiMNsU4wvbPAZoew0zry/H9pTfxc4oKX8CIz3dkla86em1KVL
	 Ptk7TTxI86B8qv2pN0kSqMuJZ0PzWV0pYA+fUjFY=
