### ISSUE TITLE
md-tabs changing slow after 0.9 upgrade

### ISSUE THREAD

**Issue by deel77** [angular/material#2805]
I am using md-tabs with lot of inputs inside and it was all right in 0.8.x version, but after upgrade to 0.9 it is significantly slow. Don't know what is the issue. I was forced to downgrade for now.

**Comment by bonatoc** [comment]
There has been major breaking changes between 0.8.x and 0.9.
It's not clear in CHANGELOG.md, perhaps the angular material team should have communicate more, but you can find it in several replies to issues. 

md-tabs has been rewritten, and the corresponding angular material css as well.

I suggest you rewrite your tabs implementation markup according to the current docs, if you decide to use 0.9.

**Comment by marcysutton** [comment]
Hi, are you noticing an actual performance issue or just confusion around the tabs API change? A Codepen or Plunker would help debug.

**Comment by robertmesserle** [comment]
This should be resolved now - scopes are once again disconnecting when tabs are out of view.

**Comment by ThomasBurleson** [comment]
@deel77 - can you confirm that the latest in master has resolve the performance issue(s) with tab changes?

**Comment by parshotam** [comment]
Hi, I am also using md-tabs with lot of selects and inputs inside  and it is very slow. When i remove the selects and inputs  inside the md-tabs then it works fine.But issue(s) that i have used lot of inputs and selects in md-tabs so how to fix it.

**Comment by bonatoc** [comment]
@parshotam — I myself found puzzled with some behaviours, but look at this : you can fill the page up, it's stil reactive.

http://codepen.io/bonatoc/pen/QNNwrK

http://vlio20.github.io/angular-material-form-builder/

Most of the times, we're asking too much of our controllers / directives, and you should optimize something at a controller/directive level : less data at once, deferring, etc. ...

We tend to think as AM and Angular as some kind of a Bootstrap 3 equivalent, but we can't just throw "a lot of inputs". Why? Aside from performance reasons, it surely means your UI is wrong, and that you should fragment your form in steps.

Think users first. No one likes "a lot" of inputs at once.
