### ISSUE TITLE
Display bug with single md-input and md-radio-button or md-select 

### ISSUE THREAD

**Issue by Tetraib** [angular/material#2806]
Having a single md-input on the page with md-radio-button or md-select cause a small display bug when md-input has focus (move up for few pixels) .
Exemple here : 
http://plnkr.co/edit/lP7o8Fjc2A4tyPW1PFTe?p=preview

**Comment by rschmukler** [comment]
@Tetraib what browser are you using? The demo you linked seems to be working for me on `Chrome@42` on OS X.

**Comment by Tetraib** [comment]
Using Chrome 43 on Windows. On entering the input everything else move up of let's say 2 or 3 pixels but enough to see it moving.

**Comment by rschmukler** [comment]
We'll take a look!
