### ISSUE TITLE
md-autocomplete - validations

### ISSUE THREAD

**Issue by DevVex** [angular/material#2808]
Are md-autocomplete fields going to get validation? 

Currently have the use case where I want to mark them as required and use md-autocomplete in a form, but would like the ability to use this with ng-messages.

**Comment by vinaygopinath** [comment]
Refer #1780
Looks like it's set to be in the next release.

**Comment by tomaszbrudzinski** [comment]
simple ability to make the input required would have saved my day...

**Comment by fabiusss** [comment]
+1

**Comment by cnjsstong2** [comment]
+1

**Comment by Kratos-SA** [comment]
+1

**Comment by eniniz** [comment]
+1
