### ISSUE TITLE
Opening material dialog crashes browser on iOS

### ISSUE THREAD

**Issue by marcysutton** [angular/material#281]
When a user tries to open a dialog in the `material-dialog` demo, both Chrome and Safari on iOS7 crash. I tested with version 7.1.2.

To repro:
1. [Open dialog demo](https://material.angularjs.org/#/material.components.dialog/readme/overview)
2. Tap button to open dialog
3. Watch browser crash

**Comment by Purushothama-VS** [comment]
Hello team,

am loading a website(uses ng-material dialogs) in  QT browser control, it crashes everywhere when i try to load any dialogs. In firefox and IE it works fine. Need help in this regard.

**Comment by marcysutton** [comment]
@Purushothama-VS you should open a new issue rather than comment on old closed ones.
