### ISSUE TITLE
layout-align*="start end" doesn't apply justify-content

### ISSUE THREAD

**Issue by epelc** [angular/material#2810]
If you use `layout-align="center center"` with `layout-align-gt-sm="start end"` on an element with `layout="column"` you end up with what looks like `layout-align="center end"` on screens above the sm breakpoint. Please take a look at the demo

Demo(Inspect the div to see the justify-content not being set by any "start end" alignment)
http://plnkr.co/edit/XJsYP6vfnMv4WoSuZvHZ?p=preview

After look into it I think it's broken because `justify-content` isn't set with `layout-align*="start end"`(Note the * is with or with any -gt-*). I think this will pop up in other situations too but I haven't looked at the full source to check yet.

**Comment by ThomasBurleson** [comment]
Fixed with ^ v0.11.0-rc1
