### ISSUE TITLE
md-list has user-facing, hard-coded English (i18n)

### ISSUE THREAD

**Issue by jelbourn** [angular/material#2811]
https://github.com/angular/material/blob/master/src/components/list/list.js#L107

The component sets an `aria-label` to "Toggle " + some content. This is not i18n friendly.

**Comment by marcysutton** [comment]
Sounds like a duplicate issue of https://github.com/angular/material/issues/1696.

**Comment by jelbourn** [comment]
Yeah, it can be tracked in the same issue.
