### ISSUE TITLE
tab content issues

### ISSUE THREAD

**Issue by mbeckenbach** [angular/material#2816]
When several controls are placed inside a autogrow tab content there are issues with ng-show when using ie11

Place a select inside the tab content and below place some additional input controls. Now place a ng-show on the first additional selects to show those controls only when a specific value is selected by the select control. 

As long as all controls are visible from the beginning autogrow works fine. But when you add the ng-show, autogrow works only when the select drop down is open. As soon as it closes the tab content becomes to small.

**Comment by robertmesserle** [comment]
I am not able to recreate this issue.  Closing for now, please reopen if it is still an issue.
