### ISSUE TITLE
RTL Layout 

### ISSUE THREAD

**Issue by EMIN3M1986** [angular/material#2817]
Hi.
how can I change the whole layout of the angularjs material component to RTL ?

**Comment by ThomasBurleson** [comment]
We will be using the [HTML attribute 'dir'](https://github.com/angular/material/blob/master/src/core/style/mixins.scss#L45-L51) to determine RTL support see:

```scss
/* mixin definition ; sets LTR and RTL within the same style call */
@mixin rtl($prop, $value, $rtl-value) {
  #{$prop}: $value;
  html[dir=rtl] & {
    #{$prop}: $rtl-value;
  }
}
```

We have only recently started to add RTL support. Many of our components will be updated with improved support for the 0.10 release.

**Comment by EMIN3M1986** [comment]
Thanks Thomas for you answer.
When is the time of next release ?

**Comment by ThomasBurleson** [comment]
See https://github.com/angular/material/milestones for details. Please note
this are `targeted` dates; not guaranteed dates.

**Comment by behiunforgiven** [comment]
How can I use rtl mixin to change the layout?

**Comment by ErinCoughlan** [comment]
Duplicate of #1080, which adds RTL support for all components.

**Comment by ThomasBurleson** [comment]
Duplicate.
