### ISSUE TITLE
Input validation with ng-message does not work correctly inside of a md-dialog

### ISSUE THREAD

**Issue by mrmeku** [angular/material#2820]
Basically anything with the ng-message directive is shown no matter what is inside the input field. See attached code pen: http://codepen.io/anon/pen/oXbKrJ

**Comment by ligeek** [comment]
Have you tried with [angular-message](https://docs.angularjs.org/api/ngMessages)? Basically, this is not contained  in angular. So, you have to add [this](http://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-messages.js) for using this module like as `angular-aria.js` and `angular-animate.js`. and should add `ngMessages` into module dependencies.

Here is modified codepen:
http://codepen.io/ligeek/pen/XbPwZo

**Comment by mrmeku** [comment]
Oh, I guess I assumed that angular material would have listed it as a
dependency since it was used in an example within the docs. Maybe the docs
should be updated so people don't make my assumption again? Anyway, thanks!
