### ISSUE TITLE
md-tabs: animation performance improvements

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#2821]
- [x] 1. Look for animations that are not using `transform: translate3d(...)` and convert when possible.
- [ ] 2. \(Possibly\) Add a way to disable animations via attribute or check animation speed to see if the browser can handle it.  (It would be nice to have a generic tool to disable animations on slower browsers.)

**Comment by ThomasBurleson** [comment]
@robertmesserle - (2) would require a browser detection and a class injection to *disable* animations for all Material components... right?

**Comment by robertmesserle** [comment]
Ideally, we wouldn't want to do browser detection but a performance test.
It wouldn't disable all animations globally, but may add a class to the
body so that each component could use that information.  (ie. heavy
animations could be made optional)
