### ISSUE TITLE
Docs: directives should be grouped by module

### ISSUE THREAD

**Issue by marcysutton** [angular/material#2830]
In the docs sidenav, it would be really helpful to group child directives by their module. This just tripped me up on Autocomplete: `<md-highlight-text>` is listed as a directive but it can only be used with `<md-autocomplete>`.

Some others that could be grouped together:
* `md-chip`, `md-chip-remove`, `md-chips`, `md-contact-chips`
* `md-grid-list`, `md-grid-tile`
* `md-highlight-text`, `md-autocomplete`
* `md-list`, `md-list-item`
* `md-radio-button`, `md-radio-group`
* `md-sidenav`, `md-sidenav-focus`
* `md-swipe-left`, `md-swipe-right`
* `md-tab`, `md-tabs`

We'll have to figure out what to display...perhaps the module name could become a nested toggle with child directives exposed under it? This would reduce the length of the directives list significantly.

**Comment by epelc** [comment]
Perhaps the `demo` and `directive` section could be combined to group things by module. Then maybe each module would have a nested dropdown with options for demos and each directive(possibly a second group if there are several). This would put everything you need to use a feature in one place which would be nice.

**Comment by marcysutton** [comment]
No, they are separated to provide less technical folks like project stakeholders a path and API seekers a clear path as well...this was discussed in our UX planning a while back. Recommend those stay separate, especially so close to 1.0.

**Comment by epelc** [comment]
That does make more sense now that I think about it. I remember sending a link to the demos list for foundation to someone so they'd have an idea of what could easily be done.
