### ISSUE TITLE
Is it possible to re-size an <md-checkbox>

### ISSUE THREAD

**Issue by axelson** [angular/material#2832]
Is it possible to re-size an md-checkbox gracefully? I could reach in and change the CSS width and height of `md-checkbox .md-icon` but that seems hacky.

**Comment by ThomasBurleson** [comment]
Why is that hacky? What other approach would do you consider [standard for HTML]?

**Comment by axelson** [comment]
It would be hacky because I was hoping to avoid depending on the fact that `md-checkbox` creates an internal `md-icon`. If that's the best approach then that is okay though :+1:

**Comment by ThomasBurleson** [comment]
@axelson Actually md-checkbox creates a `<div class='md-icon' />` which defaults to an unchecked box area.

**Comment by Seiifer** [comment]
How should we change the color of checked `md-checkbox`es ?

I tried to play with `md-checkbox .md-icon` css but didn't manage to do what I wanted to.

**Comment by mDibyo** [comment]
@Seiifer Check out the first example here: https://material.angularjs.org/latest/demo/checkbox

**Comment by Muneem** [comment]
I have also adjusted height and with of check box. But now i want to adjust check mar when check box is checked. i got stuck in that how to adjust this checkmark

**Comment by scraymer** [comment]
Simple CodePen example with the css `transform: scale(x)` suggesting by @ThomasBurleson : [http://codepen.io/anon/pen/Wxqydv](http://codepen.io/anon/pen/Wxqydv)

**Comment by gthomas3** [comment]
Pretty easily done.. The key is to maintain the ratio for the checkmark-to-checkbox, which you can find in the angular-material.scss. I put this `.form-checkbox-lg` on the `md-checkbox` and increased the size to 40x40:

```
.form-checkbox-lg {
	$width: 40px;
	$height: 40px;
	.md-icon {
		width: $width;
		height: $height;
		&:after {
			left: $width / 3 !important;
			top: $width / 9 !important;
			width: $width / 3 !important;
			height: $width * 2 / 3 !important;			
		}

	}
}
```

**Comment by javadhemati** [comment]
md-checkbox .md-icon {transform: scale(.7);}
