### ISSUE TITLE
Nested layout-fill does not fill container

### ISSUE THREAD

**Issue by wlingke** [angular/material#2834]
Suppose we have a structure like the following. `body` is set to be 100% of the screen height.
`#div1` has the height equal to `body` less `md-toolbar` which is correct since the outter-most div's `layout-fill` works as expected and takes up 100%.. However, I would expect `md-content` to have the same height as `#div1` because it has a `layout-fill` but it does not.

```
<body>
  <div layout="column" layout-fill>
    <md-toolbar>
      <h1 class="md-toolbar-tools" layout-align-gt-sm="center">Hello World</h1>
    </md-toolbar>
    <div flex id="div1">
      <md-content layout="row" layout-align="center center" layout-fill>
        This container is not filling the parent height
      </md-content>
    </div>
  </div>
</body>
```

Example:
http://codepen.io/anon/pen/qdZbNP

**Comment by wlingke** [comment]
I noticed one solution is to add `layout` to `#div1`, however, this is not ideal..

**Comment by DaveWM** [comment]
@wlingke You could also get rid of `div1`, and add the `flex` attribute to `md-content` (http://codepen.io/anon/pen/oXYOdz)

**Comment by wlingke** [comment]
Yes, I understand that. However, it's necessary to have `div1`. Is it possible to make that work?

**Comment by DaveWM** [comment]
Ah ok, I'm not sure, only just started using angular-material myself actually. If you're going to add more elements into `div1`, surely you need the `layout` attribute on it anyway though?

**Comment by jeffstahlin** [comment]
I know it's a little late but if anyone still runs into this issue. the solution is to add the attribute <code>layout="row"</code> to div1.

So it would look like:
<code><div flex id="div1" layout="row"></code>

Codepen here: http://codepen.io/psychedelus/pen/admorV

**Comment by dguieb** [comment]
question is why doesn't layout-fill work on layout="column"? which is what he has

**Comment by jeffstahlin** [comment]
I cannot quite remember why this works exactly (at the time I had researched and found out why), but you can check out all of the pens above to play with this. If on the div with id "div1" you add layout="row" the layout fill works.

This is something that wlingke had missed out on. Judging from your comment I think you've misunderstood what element this attribute has to be added to, its the div with id "div1"  on which was no layout attribute in his example.

I've had a quick look around but cannot find the explanation as to why layout fill works on layout row but not column. If anyone can explain the exact reason this would be greatly appreciated.

**Comment by apmeena** [comment]
@jeffstahlin i have written the same code but why it's not working for me? my code is 

```
<html lang="en" ng-app="firstApplication">

<head>
    <meta name="viewport" content="initial-scale=1" />
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-aria.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-messages.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.js"></script>
    <script type="text/javascript">    
         angular.module('firstApplication', ['ngMaterial'])
         .config(function($mdThemingProvider) {
          $mdThemingProvider.theme('default')
          .primaryPalette('green')
          .accentPalette('red')
          .warnPalette('blue');
       });
      </script>
    <style type="text/css">
             #div1 {
                background-color: yellow
              }
            #mdContent {
               background-color: red
             }
    </style>
</head>

<body ng-cloak ng-controller="myCtrl">
    <div layout="column" layout-fill>
    <md-toolbar>
      <h1 class="md-toolbar-tools" layout-align-gt-sm="center">Hello World</h1>
    </md-toolbar>
    <div flex id="div1" layout="row">
      <md-content layout="row" layout-align="center center" layout-fill id="mdContent">
        This container is not filling the parent height
      </md-content>
    </div>
  </div>
</body>

</html>
```

It is giving a unwanted scrollbar because it is taking <body> tag as parent and taking it's height as 100%. What should i do?
