### ISSUE TITLE
Few issues with tabs

### ISSUE THREAD

**Issue by gio82** [angular/material#2837]
I'm dealing with few issues with tabs.  
Here below a brief description:

- Removing a tab do not call `md-on-select`
- Dynamically changing the tab label does not update the DOM
- When async loading some tabs the ink bar does not update his length 

Plus I think that you should add a method that allows to change tab via javascript.

**Comment by epelc** [comment]
@gio82 on the last note if you set ` md-selected="selectedIndex"` on `md-tabs` you can change `selectedIndex` to switch between tabs.

I think the last bullet has to do with tabs not playing well with ng-if`s or dynamically adding/remove tabs see #2291

**Comment by gio82** [comment]
Thanks for your help @epelc !

**Comment by patriknyd** [comment]
+1

/ med vänlig hälsning
Patrik Nydensten

----- Reply message -----
