### ISSUE TITLE
md-tabs not scrolling to md-selected on load

### ISSUE THREAD

**Issue by azza85** [angular/material#2838]
If I load the dynamic tabs example on this link https://material.angularjs.org/#/demo/material.components.tabs
on a smaller screen width eg less than 600px w, I would expect the tabs to scroll to the highlighted index.  It appears ok on the above link, but if I change the selectedIndex to 7 it loads the content of 7 but the tabs don't scroll to the active tab, which I think causes confusion for the user as they don't know what tab they are on until they click the arrow to scroll accross.  Is this working as intended or should it work as I have suggested?

See updated codepen (make window less than 600px) for example
$scope.selectedIndex = 7;

http://codepen.io/anon/pen/aONBKM

**Comment by patriknyd** [comment]
+1

/ med vänlig hälsning
Patrik Nydensten

----- Reply message -----

**Comment by mprentic-harris** [comment]
Thank you!
