### ISSUE TITLE
Can't add aria-controls to list item buttons

### ISSUE THREAD

**Issue by calebegg** [angular/material#2839]
I'd like to have aria-controls on an md-list-item with an ng-click directive go to the button instead of staying on the md-list-item, since aria-controls really makes more sense on the button than on the list-item.

Alternately, since there's potentially a long list of such attributes that need to be moved to the button, I'd really like for this to work:

    <md-list>
      <md-list-item>
        <md-button class="md-no-style" ng-click="" aria-controls=""></md-button>
      </md-list-item>
    <md-list>

But it doesn't currently work correctly, at least in terms of styling (might be other problems, I haven't checked thoroughly):

http://codepen.io/calebegg/pen/mJPmVb

**Comment by rschmukler** [comment]
Thanks for the suggestion of @calebegg!
