### ISSUE TITLE
md-tabs : pagination wrapper should translate position when tab is swiped

### ISSUE THREAD

**Issue by bonatoc** [angular/material#2840]
I have several tabs, more than the **md-tabs-wrapper** can display horizontally, so pagination is triggered.

When tabs are swiped, the md-pagination wrapper should not allow for the md-active/md-focused tab item to remain out of the viewport.

Currently, if you swipe through the tabs, the pagination wrapper does not reflect the current active tab if it is paginated. 
Say the viewport allows for 3 **md-tab-items** (the 4th being paginated to the following "page"), when the user swipes to tab 4, he has no longer visual feedback, in the pagination wrapper, about which tab he's currently on. 

Would it be possible to trigger the "page change" in the wrapper, as the previous and next arrows do?
So to always have (if possible) the currently active tab in sight in the pagination wrapper?

**Comment by robertmesserle** [comment]
This is as designed.

**Comment by bonatoc** [comment]
@robertmesserle — Sorry, I dont understand your answer. Do you mean the MD specs state that the end user should be confused about what tab he's on? I don't mean to sound harsh, but it seems to me like an important UI topic.

**Comment by robertmesserle** [comment]
@bonatoc Actually, I think I misunderstood swiping the tabs as in the tab-bar.  If that is the case, it is as designed.

I will add a fix for the case of swiping the tab content, which is a valid request.

**Comment by bonatoc** [comment]
@robertmesserle Yep, it is the latter. I tried to describe the problem using the actual elements names, so to have a clue of what we're talking about.

**md-tab-items** is an ambiguous name for the pagination elements, and therefore I totally understand your misinterpretation.

Thank you.
