### ISSUE TITLE
md-chips that include an autocomplete throw an exception when they are readonly.

### ISSUE THREAD

**Issue by ddimitrop** [angular/material#2841]
Codepen example

http://codepen.io/ddimitrop/pen/OVNjbd

There is an exception in dev console

TypeError: Cannot read property 'registerSelectedItemWatcher' of undefined
    at MdChipsCtrl.configureAutocomplete (angular-material.js:11978)
    at angular-material.js:12242
    at angular.js:16299
    at completeOutstandingRequest (angular.js:4924)
    at angular.js:5312

in line

https://github.com/angular/material/blob/786b0ed3652b7460c2c802efa1aa79972bd96f5d/src/components/chips/js/chipsDirective.js#L255

there is no guarantee that the compiled chipInputTemplate will include an actual auto-complete just because it was in the source

**Comment by cognitronic** [comment]
I'm having this issue all of a sudden and I'm not exactly clear as to why.  Is there a way to get around this for the time being?

**Comment by stewones** [comment]
+1

**Comment by Millen31** [comment]
+1

**Comment by ryanovas** [comment]
anyone have a temporary workaround until this is fixed?

**Comment by cwkochan** [comment]
+1

**Comment by charliewynn** [comment]
+1 but I have a workaround for now..

1) ditch the readonly property for md-chips
2) use your readonly var for the autocomplete's ng-disabled
3) use a custom md-chip template
4) add an ng-hide to the md-chip-remove button with your readonly var

**Comment by yochayme** [comment]
+1

**Comment by rafidka** [comment]
+1

**Comment by topherfangio** [comment]
@rafidka Are you still seeing this in 0.11? We pushed a fix in https://github.com/angular/material/commit/3e8c99455832a3e457a1de00afd1601c11d55c5e.

**Comment by rafidka** [comment]
@topherfangio I think I am still on 0.10, I will try the new one and let you know.

**Comment by rafidka** [comment]
@topherfangio sorry for the late response. I tried Angular 0.11 and it indeed solved it. Thanks!.

**Comment by waratah** [comment]
For those that end up here searching only...

TypeError: Cannot read property 'some' of undefined
    at MdChipsCtrl.appendChip

This is caused by an undefined in ng-model
