### ISSUE TITLE
No way to layer bottom sheets

### ISSUE THREAD

**Issue by mrmeku** [angular/material#2845]
If you take a look at the android phone app and pull up a contact you'll notice that the contact comes up as a bottom sheet. Then, if you press the edit icon in the toolbar, another bottom sheet comes up and covers the contact and allows you to edit the contact. Currently, this flow is impossible with the current $mdBottomSheet service.

**Comment by ThomasBurleson** [comment]
@rschmukler - this is related to feature request to stack dialogs, bottomsheets, and toasts.

**Comment by ThomasBurleson** [comment]
Stacked dialogs, toasts, snackbars, etc. will not be available until a post v1.0 release.
