### ISSUE TITLE
Angular 2 support?

### ISSUE THREAD

**Issue by jasokant** [angular/material#2847]

**Comment by mchmielarski** [comment]
https://github.com/angular/angular/tree/master/modules/angular2_material

**Comment by ThomasBurleson** [comment]
@mchmielarski - that repository link is experimental only. A more formal repository with formal development will be published this summer after Angular Material 1.0 is released.

**Comment by flyingmutant** [comment]
Is there any timeline for the Angular 2 support?

**Comment by ThomasBurleson** [comment]
@flyingmutant - ask the Angular.JS repository team
