### ISSUE TITLE
md-list-item secondary button disabled/hidden mdprimary

### ISSUE THREAD

**Issue by rgolea** [angular/material#2849]
Hi there!

I have been dealing with a set of problems or questions about the md-list-item secondary button feature. First of all, how can you change color? if you use `class="md-warn"` the button breaks.

Secondly, how do you disable the button on a condition? I have a list and I don't want them to have the delete option based on a condition. I tried to use `ng-if` but it just hides the icon. The button is still there.

Thanks.

[Example here](http://codepen.io/anon/pen/bdpvzm)

**Comment by Izcalli** [comment]
+1

**Comment by sckoh** [comment]
+1

**Comment by topherfangio** [comment]
I believe this will be fixed by #5716. I will re-test after it is merged to verify. If not, we'll dig deeper.

**Comment by gligoran** [comment]
@topherfangio It doesn't seem so. I forked @rgolea's pen and updated it to master [here](http://codepen.io/gligoran/pen/xwvOyQ), but it seems the button is still there. The ```ng-if``` itself stays on the ```md-icon``` and just hides/shows it.
