### ISSUE TITLE
The md-select placeholder doesn't have the right opacity

### ISSUE THREAD

**Issue by nmichaud2** [angular/material#2855]
The opacity of the md-select placeholder is at 54%:
https://material.angularjs.org/#/demo/material.components.select

Shouldn't it be 26% for hint texts:
http://www.google.com/design/spec/style/color.html#color-ui-color-application

I would expect the placeholder to have the same color as the labels in input containers.

**Comment by rschmukler** [comment]
The issue, then, is discerning a disabled select from a non-disabled one. Ie. if two selects are next to each other you would expect the disabled one to be lighter. For that reason we went with the 54%. I'm open to opinions to the contrary, but this seems reasonable to me.

**Comment by joeyperson** [comment]
@nmichaud2 has a good point that they should match. @rschmukler, to help discern disabled selects, they should get the same dotted line treatment that inputs get.

**Comment by websirnik** [comment]
Just to visualise the problem with opacity(there are other issues with placeholders in general):
![screen shot 2015-06-18 at 20 03 40](https://cloud.githubusercontent.com/assets/282871/8239696/6b0752da-15f5-11e5-937c-d61a98fedc73.png)

**Comment by ThomasBurleson** [comment]
@websirnik - can you submit your sample as a CodePen demo? I will validate fixes with that...

**Comment by rschmukler** [comment]
@ThomasBurleson I brought these into line in e9f5a997abcf9cc8f3c6a311320aa9bf0ed7c56c. Sorry I missed closing this issue.
