### ISSUE TITLE
select option items truncate when scrollbar present

### ISSUE THREAD

**Issue by joeyperson** [angular/material#2856]
The box that unfolds in a select menu truncates items when a scrollbar is present. The scrollbar shouldn't obscure the list text unless a specific width is given.

Example:
![screen shot 2015-05-14 at 1 50 00 pm](https://cloud.githubusercontent.com/assets/12143949/7642188/02c29a9e-fa44-11e4-9282-96e2b3dc6d1d.png)
![screen shot 2015-05-14 at 1 50 18 pm](https://cloud.githubusercontent.com/assets/12143949/7642189/02c3081c-fa44-11e4-81ad-b3b8fd531da6.png)

**Comment by rschmukler** [comment]
The width should have been based off of the `md-select` that the box came from, but this wasn't working since the latest changes to select (the floating label support) - it is now restored and working. See [a demo here](http://codepen.io/rschmukler/pen/MwVyKW)
