### ISSUE TITLE
goog is not defined

### ISSUE THREAD

**Issue by reidlai** [angular/material#2858]
Just update release v0.9.3.  When I start my app, it keeps on to say "goog is not defined at line 7 of angular-material.js"

**Comment by jaytula** [comment]
Looks like goog.provide and goog.require lines should simply be removed.

**Comment by YogurtShen** [comment]
got the same problem
I removed line7~line43
`
goog.provide('ng.ngMaterial');
goog.require('ng.material.components.autocomplete');
goog.require('ng.material.components.backdrop');
goog.require('ng.material.components.bottomSheet');
goog.require('ng.material.components.button');
goog.require('ng.material.components.card');
goog.require('ng.material.components.checkbox');
goog.require('ng.material.components.chips');
goog.require('ng.material.components.content');
goog.require('ng.material.components.dialog');
goog.require('ng.material.components.divider');
goog.require('ng.material.components.gridList');
goog.require('ng.material.components.icon');
goog.require('ng.material.components.input');
goog.require('ng.material.components.list');
goog.require('ng.material.components.progressCircular');
goog.require('ng.material.components.progressLinear');
goog.require('ng.material.components.radioButton');
goog.require('ng.material.components.select');
goog.require('ng.material.components.sidenav');
goog.require('ng.material.components.slider');
goog.require('ng.material.components.sticky');
goog.require('ng.material.components.subheader');
goog.require('ng.material.components.swipe');
goog.require('ng.material.components.switch');
goog.require('ng.material.components.tabs');
goog.require('ng.material.components.toast');
goog.require('ng.material.components.toolbar');
goog.require('ng.material.components.tooltip');
goog.require('ng.material.components.whiteframe');
goog.require('ng.material.core');
goog.require('ng.material.core.gestures');
goog.require('ng.material.core.theming');
goog.require('ng.material.core.theming.palette');
goog.require('ng.ng');
goog.require('ng.ngAnimate');
goog.require('ng.ngAria');
`
and the last line 
`ng.ngMaterial = angular.module("ngMaterial");`

which looks working fine then
Is that correct?

**Comment by gitawego** [comment]
same here, why do we need goog as lib ??

**Comment by Polyethylene** [comment]
+1

**Comment by suancarloj** [comment]
+1

**Comment by eupathy** [comment]
+1

**Comment by 07Gond** [comment]
+1

**Comment by mathiasmoeller** [comment]
+1

**Comment by jozsi** [comment]
+1

**Comment by josephpage** [comment]
+1

**Comment by sebay00** [comment]
+1

**Comment by wil93** [comment]
:+1:

**Comment by ThomasBurleson** [comment]
@all - We recently enhanced the scripting and automation of our build and
release processes. It appears that part of that process published Angular
Material with the Google Closure Library and namespaces with
`goog.provide()`. We are investigating right now...

- Angular Material

**Comment by ThomasBurleson** [comment]
We have updated our release script(s) and release version 0.9.4 with fixes to our deployed files.
Please see the [ChangeLog](https://github.com/angular/bower-material/blob/master/CHANGELOG.md) for details.

**Comment by Polyethylene** [comment]
Hi @ThomasBurleson, thanks a lot for such a quick response. Keep up the good work !

**Comment by ThomasBurleson** [comment]
@everyone - Check out the amazing work that @robertmesserle did with our [Release Script](https://github.com/angular/material/blob/master/release.js)

> This will give you a hint of all the steps and complexity we address in order to release great, quality versions of Angular Material.

**Comment by eupathy** [comment]
Thank you very much

**Comment by gilazo** [comment]
I was getting this same error, then I added ngMaterial to my main module and it went away.

```javascript
angular
    .module('app', [
        'ngMaterial'
    ]);
```

**Comment by SivaPrasanna45** [comment]
@gilazo What about same error in angular4? Do you any idea about it.
