### ISSUE TITLE
docs: Readme and getting started should mention npm install

### ISSUE THREAD

**Issue by btford** [angular/material#2861]
I actually think `npm install angular-material` should be the preferred way of consuming this lib, but it should be at least mentioned in the README and Getting started guide.

- [ ] https://material.angularjs.org/#/getting-started
- [ ] https://github.com/angular/material#-installing-build-distribution-files

**Comment by epelc** [comment]
I think we should keep the option to use either npm or bower but document both.

I like to use npm for build tools and bower for js/libs which I use in my app. It's nice to keep them separate but I'm sure others have a different setup(maybe using npm's devDependencies?).

**Comment by ThomasBurleson** [comment]
This is all documented on our [/bower-material/README](https://github.com/angular/bower-material/blob/master/README.md).

@btford - we will update those other resources to include the same information.

> NPM is the preferred way... but we support NPM, JSPM, and Bower; versatility for all needs.

**Comment by gkalpak** [comment]
Talking about it mentions [/bower-material/README][1] `npm install angular-material --save-dev`.
Shouldn't it be `--save` (instead of `--save-dev`) ?

[1]: https://github.com/angular/bower-material/blob/master/README.md

**Comment by ThomasBurleson** [comment]
@gkalpak - re HammerJS: yikes.
