### ISSUE TITLE
md-select doesn't higlight default option when ng-model is an object

### ISSUE THREAD

**Issue by davide-quix** [angular/material#2862]
Using md-select with a presetted ng-model the relative md-option is not highlighted nor marked as selected if the model referes to an object. But when the user select an option then this is marked as selected and is highlighted correctly.
The problem is more markable when the default value is not the first in the list, because the first element gets an highlight effect (different from the select one).

If the model refers to a primitive type, such as a number, it works as expected.

See http://codepen.io/anon/pen/pJyBzX

**Comment by myagoo** [comment]
You can use ng-model-options in order to tell how to keep track of your object

**Comment by davide-quix** [comment]
But "trackBy" is not documented to be a valid key for ng-model-options, https://code.angularjs.org/1.3.15/docs/api/ng/directive/ngModelOptions

So, the fact that it works is a bug or a not documented feature?

**Comment by myagoo** [comment]
Undocumented
https://github.com/angular/material/blob/master/src/components/select/select.js

**Comment by davide-quix** [comment]
Very good... thx @myagoo.

**Comment by 1kohei1** [comment]
Hello. 
I tried track by, but it did not work as I expected. Also in the codepen, does not allow to change the value.
So I wrote a program which does the same thing with md-select-label and selected option. 
Hope it helps you.
http://codepen.io/1kohei1/pen/gpXdjQ?editors=101

**Comment by bsandrow** [comment]
+1

This feature seems to be currently broken, even the codepen example is broken (as @1kohei1 says). I realize that fixing an undocumented feature isn't top-priority, but the code itself *does* have a TODO of documenting said feature. Hopefully the feature is fixed before the documentation happens. :^)

**Comment by rschmukler** [comment]
@bsandrow the feature works with `trackBy`. See [this demo](http://codepen.io/anon/pen/yYYgmj). We do need to document it though

**Comment by mohitadwani** [comment]
+1

**Comment by r2coding** [comment]
I'm using this in order to highlight the data:

ng-model-options="{ trackBy: '$value.id' }"
