### ISSUE TITLE
Document 0.9.3 changes(the changelog is empty)

### ISSUE THREAD

**Issue by epelc** [angular/material#2864]
The changelog for 0.9.3 is empty. I'm not entirely sure how the release process works but I think was forgotten.

@robertmesserle I see you did the release. Should we start testing this yet? I seen a few issues about missing `goog` imports.

**Comment by ThomasBurleson** [comment]
*  The Changelogs has been updated with details for 0.9.3 and 0.9.4.
*  We are updating our build scripts to automatically resolve this for future releases.

> Please see the [ChangeLog](https://github.com/angular/bower-material/blob/master/CHANGELOG.md) for details.

**Comment by epelc** [comment]
@ThomasBurleson Thanks

I was also going to recommend adding it to the build scripts but you beat me too it. I saw blog post about making a gulp task to release updates(I guess you can use git from gulp).

**Comment by ThomasBurleson** [comment]
@epelc - check out the amazing work that @robertmesserle did with our [Release Script](https://github.com/angular/material/blob/master/release.js)

**Comment by epelc** [comment]
@ThomasBurleson @robertmesserle Great job! That's a really nice release script.

I bet those git commands were fun debugging.
