### ISSUE TITLE
md-select shows in all weird places for some time now…

### ISSUE THREAD

**Issue by mmiszy** [angular/material#2867]
For some time now `<md-select>` usually shows up at a completely incorrect position eg. off-screen. `<md-backdrop>` is off the screen as well. I did some quick research and found out it's broken for me since 0cebafba47a6409cc41c64d4b18783f45131c1c1.
Is this a bug or is my application structured _incorrectly_?

**Comment by marcysutton** [comment]
Can you please provide a Codepen or Plunker showing your code? That will help debug.

**Comment by prdn** [comment]
Happens also to me

**Comment by mmiszy** [comment]
@prdn can you easily reproduce it in a Codepen?
I'm having a hard time with that now so I guess it must be our application's structure that interferes with `<md-select>`. But then again, it used to work before that commit so definitely something is off. I'll try to provide more useful information later.

**Comment by mmiszy** [comment]
@marcysutton It's really simple to reproduce now, there you go: http://codepen.io/mmiszy/pen/LVZGRL
It's angular-material `v0.9.4-master-5488909` and all angular-* libs `1.4.0-rc.2`
