### ISSUE TITLE
md-tab's label has only one-time binding

### ISSUE THREAD

**Issue by gitawego** [angular/material#2868]
with this code:
```html
<md-tab label="{{ 'WEAK_POINTS' | translate }}">
```
tab title is converted to (without ng-binding):
```html
<span class="ng-scope">Weak points</span>
```
if I change the language, tab title doesn't change the translation.

**Comment by bonatoc** [comment]
I think you mean has a scope isolation (one way binding)?

**Comment by gitawego** [comment]
yes It's one way binding, I just checked the code (line 62):
```
scope: {
      label:    '@',
      active:   '=?mdActive',
      disabled: '=?ngDisabled',
      select:   '&?mdOnSelect',
      deselect: '&?mdOnDeselect'
    },
```
and line 76:
```
 data = ctrl.insertTab({
          scope:    scope,
          parent:   scope.$parent,
          index:    index,
          template: getTemplate(),
          label:    getLabel()
        }, index);
```

label doesn't have two way binding, nor $scope.$watch for label (only for 'active','disabled' and tab item)

**Comment by bonatoc** [comment]
The way I do it :

    <md-tab-label>
        <span ng-bind-html="str_Name | translate"></span>
    </md-tab-label>

you may want to alter the span or div inside the md-tab-label, so it covers all surface. You can hack the label to be a flexbox, remove all paddings/margins and stretch the span inside.

**Comment by gitawego** [comment]
thanks for the hint, didn't know we should use <md-tab-label> ^^
but it's still a bug IMO.

**Comment by bonatoc** [comment]
Not a bug : You're not supposed to tie **angular-translate** to the angular-material directive, which is a module that has nothing to do with angular-material. 

I think that's why they built the encapsulated system, so we could fill the md-tab-items and the md-tab-contents with whatever html we want (filter and directives included).

**Comment by qorsmond** [comment]
In my use case i am using tabs to open files and the names can/will change so really need 2 way binding on the label. I tried @bonatoc suggestion with ng-bind-html but could not get 2 way binding going.

**Comment by rickli1989** [comment]
@bonatoc <md-tab-label> won't get run time translated, but md-tab-body does.

**Comment by franciscopuyo** [comment]
I think it's a bug. Fix it please
