### ISSUE TITLE
md-list.md-default-theme md-list-item button {   background-color: should be transparent; }

### ISSUE THREAD

**Issue by kkksparky** [angular/material#2871]
md-list.md-default-theme md-list-item button {   background-color: should be transparent; }
otherwise setting a background color of item list is not taken into account

**Comment by topherfangio** [comment]
@kkksparky Can you explain the issue a bit more and provide a [Codepen](http://codepen.io) which demonstrates it?

**Comment by topherfangio** [comment]
@kkksparky Since you have not responded, we are going to close this issue. If you can provide a Codepen, we will reopen.
