### ISSUE TITLE
md-autocomplete dropdown suggestions gets stuck when open and transitioning ui-router states

### ISSUE THREAD

**Issue by nvanbenschoten** [angular/material#2872]
When an md-autocomplete's dropdown suggestions are open and an event such as a form submission causes a ui-router state transition, the dropdown gets stuck open and cannot be removed. This can be reproduced here http://codepen.io/anon/pen/pJboGB.

**Comment by hmlb** [comment]
+1

**Comment by nvanbenschoten** [comment]
I've looked into a lot of hacky ways to try to get around this issue, but haven't been successful thus far :(

**Comment by robertmesserle** [comment]
I am not able to recreate the problem - what version were you using when you were experiencing this?  Closing for now, please reply if it needs to be re-opened.
