### ISSUE TITLE
CodePen does not correctly render <code> tags

### ISSUE THREAD

**Issue by nvanbenschoten** [angular/material#2873]
This can be seen when opening the "Basic Usage" example of the md-autocomplete directive in CodePen seen here https://material.angularjs.org/#/demo/material.components.autocomplete.

**Comment by matthewrfindley** [comment]
We have an open support ticket with Codepen about this issue.  It appears a release on 5/12 caused this issue and we are working with them to find a solution.  Thanks for your patience.

**Comment by naomiblack** [comment]
@marcysutton do you happen to have a link to the support ticket with Codepen so we can follow up on this...?

**Comment by marcysutton** [comment]
@matthewrfindley had that info–Matt, do you still have the Codepen support ticket? I could also reach out to folks at Codepen if we can't find it.

**Comment by marcysutton** [comment]
The last I heard, correspondence was forwarded over email. Going to reassign to you @naomiblack!

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (440/400 (110%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:33947 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZp-001ZA5-5z
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:24 +0200
Date: Thu, 28 Apr 2016 13:29:32 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875372;
	bh=R+hr+Y00I34F97gTw1SJWYAHIEgWlJISsL3gA3Az1/c=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ftii3+m0UAQtTZU3GYF6L376m2CHZyAldGJsq6OcSboG0yPAozIadxtrIYL7ymPMK
	 Sfe21wFegw/PK6uc/H53lniwdEHJDkRd7xJgLLu7PombaRgCy22+Vo/QxEZokfITeF
	 iZLgHlkjQiSFX2eNynS+ZBHUQdEj2RhaPioQaUPs=
