### ISSUE TITLE
Flex not working if html is included via something like ng-include

### ISSUE THREAD

**Issue by frodefi** [angular/material#2876]
See [this plnkr](http://plnkr.co/edit/966lLjaDBiAgMHqTYDxP?p=preview). The running code must be viewed in separate window mode (full screen).

Click the toggle. The same code for both forms, but one of them is included with ng-include (the same is if it is included by other means, like router). Using layout-fill does not change anything either...

For me this looks like a bug of some sort, but maybe it is meant to be?

**Comment by EladBezalel** [comment]
This happens because ng-include is an element, add flex attribute 
```html
<ng-include ng-if="!app.toggle" src="'some-other-form.html'" flex></ng-include>
```

**Comment by frodefi** [comment]
Oh, sorry, and thanks!

**Comment by frodefi** [comment]
Oh, bummer, thanks!

**Comment by jmls** [comment]
um, I just hit this with 1.0.5 -- and the "flex" solution, well, doesn't solve it ;)

**Comment by geri777** [comment]
The flex solution didn't help me either, but adding class="flexbox" to it helped. Of course the flexbox class has to be defined in your css as display:flex
