### ISSUE TITLE
mdToast: improve UX to support theme colors and multi-toasts to show

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2878]
See [Oh Snap!](http://justindomingue.github.io/ohSnap/) for comparative UX:

![screen shot 2015-05-16 at 10 40 57 pm](https://cloud.githubusercontent.com/assets/210413/7668927/c43dd3b2-fc1c-11e4-93f5-01871ba2da87.png)

**Comment by ThomasBurleson** [comment]
@joeyperson - This seems like an entirely reasonable and useful UX; especially for desktop experiences.

**Comment by aniforprez** [comment]
This is what I wondered when reading the material design specs. A single toast popping up and being replaced by another is perfectly valid UX on mobile because the user doesn't want to be overwhelmed by a line of toasts blocking their view.

But on desktops with ample space and screen real estate, to restrict the developer to a single toast whose information is hidden by another isn't really necessary.

**Comment by joeyperson** [comment]
Having a distinct color makes total sense, especially as dark designs would not work well with a dark toast with little contrast. 

Re: multi-toasts, I think the idea is to keep toasts to a single event at a time, as there may be actions that are available for them, and could fade out of view before reading them all. If many messages are needed, I'd imagine using a different pattern that could include a list of alerts.

**Comment by adrianandreias** [comment]
Yup, otherwise every project would define the red error message and the green success message.

**Comment by jelbourn** [comment]
Word from UX: it's okay to allow (we're not going to be the bad ui police)

**Comment by innerpeace0** [comment]
+1
Looks great!

**Comment by DmitryEfimenko** [comment]
+1

**Comment by guilhermecvm** [comment]
+1

**Comment by guilhermecvm** [comment]
+1

**Comment by pdore-netfore** [comment]
Any progress on this issue?

**Comment by pdore-netfore** [comment]
+1

**Comment by smurugavel** [comment]
+1

**Comment by MauF** [comment]
+1

**Comment by darkmavis1980** [comment]
+1

**Comment by Slavery** [comment]
+1

**Comment by ThomasBurleson** [comment]
@EladBezalel 

In `src/components/toast/demoBasicUsage/script.js`, if I add this:

```js
.config(function($mdThemingProvider){
    $mdThemingProvider.theme('splashRed')
        .backgroundPalette('red');
  });
```

And then use this:

```js
var toast = $mdToast.simple()
        .textContent('Marked as read')
        .action('UNDO')
        .theme('splashRed');
```

Then `splashRed` theme is not used... nor is it contained in the THEMES internal registry. Seems like a major bug.

**Comment by trainerbill** [comment]
@ThomasBurleson I was trying the exact procedure to switch the the theme on mdToast and its not working for me either.  Using 1.0.6.  The theme I am using is "success" and its registered:

![image](https://cloud.githubusercontent.com/assets/3578259/14217170/14131bda-f812-11e5-9471-eb1ede104fd7.png)

The docs seem to say that it should work.  Will this be fixed in 1.0.6 or 1.1.0?

**Comment by EladBezalel** [comment]
After inner conflicts about this issue i came to those resolutions:
- Toast shouldn't support background and foreground color change by the theme.
- Toast shouldn't support background and foreground color via a public api
- Toast should (and supports) any style changes by overriding material classes

You can see a demo [here](http://codepen.io/EladBezalel/pen/oLxxap)

@ThomasBurleson thoughts?

**Comment by DmitryEfimenko** [comment]
@EladBezalel codepen fails due to wrong ngMaterial reference: `http://localhost:8080/angular-material.js`

**Comment by EladBezalel** [comment]
@DmitryEfimenko [fixed](http://codepen.io/EladBezalel/pen/oLxxap) thanks :)

**Comment by DmitryEfimenko** [comment]
if you care for my opinion - @EladBezalel's resolutions sound great to me.
Style changes are very easy. This just needs to be documented.

**Comment by DmitryEfimenko** [comment]
Actually, creating a separate template for each toast you want to show is painful. Just let developers apply whatever class they want to the `<md-taast>`. Then they'll be able to style things that way.
```javascript
let message = this.$mdToast.simple();
message.toastClass('my-error')
```
```css
md-toast.my-error .md-toast-content {
    background-color: red;
}
```

**Comment by EladBezalel** [comment]
@DmitryEfimenko sounds reasonable.
