### ISSUE TITLE
Routing a class from a parent directive to md-button

### ISSUE THREAD

**Issue by cebor** [angular/material#2880]
I want to route a class from a parent directive into the `md-button` directive, like this:

```html
<!-- myDirective -->
<my-directive button-class="md-primary"><my-directive>

<!-- myDirective: template -->
<md-button class="md-fab {{buttonClass}}"><md-button>
```

But it does not work as expected. The result is, that also the default color class gets removed from the button, even when `button-class` is not defined.

**Comment by ThomasBurleson** [comment]
use the `ng-class` directive
