### ISSUE TITLE
Build-in responsive styles 'brink' at first time. there is event could tell the ng-material styles (added by js) is loaded?

### ISSUE THREAD

**Issue by redyyu** [angular/material#2884]
I guess because most of material css is generate by js.
so the page will show different at first sec if it's loaded.

Example:
if I use 'flex' and 'flex-gt-md'
When I refresh the page, will showing 'flex' first sec(maybe 1/4 sec...), then turn to 'flex-gt-md'
looks like the container has strange scale when loaded.

So I am thinking, if have some event can tell me the style is fully loaded, then I can put a mask by self to cover those 'brink'.

**Comment by ThomasBurleson** [comment]
The only CSS that is generated by JS is the Theme Color CSS rules. 
Please provide a Plunkr or CodePen that demonstrates this issue.
