### ISSUE TITLE
Feature Request: Input Field Masking & Accessibility

### ISSUE THREAD

**Issue by duncanleckie** [angular/material#2886]
It would be great if Material could introduce Masks into input fields with an accessibility focus.

Unless this is a conscious design decision not to ?

We current have hacked jquery input mask however it's not great for accessibility for instance one of the number fields reads out load underline 9 times for one of them ;(

eg Date of birth format or ID numbers with specific formats

![masks](https://cloud.githubusercontent.com/assets/12453200/7674340/c8892cbc-fd68-11e4-9973-e02b370db3ef.jpg)
![masks2](https://cloud.githubusercontent.com/assets/12453200/7674341/c88d99e6-fd68-11e4-9e87-0891526c459c.jpg)

**Comment by MichhDiego** [comment]
+1

**Comment by LesNovell** [comment]
absolutely I need this too! +1

**Comment by mwymann** [comment]
would be great! +1

**Comment by felansu** [comment]
i need ! +1

**Comment by kdubel** [comment]
+1

**Comment by rwestonbutler** [comment]
+1 this is a much needed feature!

**Comment by sspatrudu** [comment]
+1

**Comment by gaboAcosta** [comment]
+1

**Comment by cleydsonjr** [comment]
+1

**Comment by kaiomagalhaes** [comment]
+1

**Comment by daniel-oliveiravas** [comment]
+1

**Comment by marcusvoltolim** [comment]
+1

**Comment by jpozorio** [comment]
+1

**Comment by mavirroco** [comment]
+1 is really good for phone numbers, postal code, email

**Comment by fabriciocs** [comment]
+1

**Comment by ecunado** [comment]
+1

**Comment by alexliubj** [comment]
+1

**Comment by Denfie** [comment]
+1

**Comment by cleever** [comment]
I'm currently using ui-mask from this repo:
https://github.com/angular-ui/ui-mask

Works fine, but material input label overrides the mask when value is empty. =/

**Comment by MichhDiego** [comment]
Yes, the same is happening to me @cleever, I had to make a workaround for that...

**Comment by gaboAcosta** [comment]
@MichhDiego can you share the workaround?

**Comment by MichhDiego** [comment]
@gaboAcosta Oh yeah, I used angular-ui-mask and angular-material input together, something like this:

![screenshot from 2015-09-11 18 41 19](https://cloud.githubusercontent.com/assets/6419886/9827004/bb8a0ce6-58b4-11e5-9717-814f222f8894.png)

**Comment by bluebirdtech** [comment]
+1

**Comment by hugomelendez** [comment]
+1

**Comment by raprav** [comment]
+1

**Comment by bluebirdtech** [comment]
Noticed how Stripe checkout does masking on the expiry date recently.  It's very nice.  All invalid keys are ignored, including spaces.  If you enter eg. 616, it would enter it as 06/16 given that 6 is not a valid value for the first digit.

**Comment by HarryBurns** [comment]
+1

**Comment by StretchKids** [comment]
+1

**Comment by skyworx** [comment]
+1

**Comment by anibalardid** [comment]
+1

**Comment by mattdanna** [comment]
+:100:

**Comment by tucq88** [comment]
perfect for manually enter date, phone or custom format data +1

**Comment by roy46** [comment]
+1

**Comment by marcincichocki** [comment]
+1

**Comment by 4zuko** [comment]
Check [this](http://codepen.io/_4zuko/pen/dMRXmj) out. Thanks.

**Comment by ali4ever4** [comment]
+1

**Comment by scriptsure** [comment]
+1

**Comment by gaboAcosta** [comment]
So this means this is implemented or just plain and simple abandoned?

**Comment by MichhDiego** [comment]
Agreed with @gaboAcosta, @ThomasBurleson what is going on?

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category defined in our Deprecation Policy.  For details, see our post [Deprecation Policy 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
