### ISSUE TITLE
performance: Repaints on scroll

### ISSUE THREAD

**Issue by krassx** [angular/material#2887]
Take a look at this screenshot: http://gyazo.com/079dd1b123eb9824e37ec396e1039c3e

"Repaints on scroll" occurs for each md-content tag. probably there is a solution to fix that.

Also, there is a scrolling glitches (content blinking) in Safari on iPad mini (iOS 8.3). Overal performance in mobile Safari is really poor. Even when working with your official website (https://material.angularjs.org).

**Comment by ThomasBurleson** [comment]
Are you seeing the same `content blinking` on https://material.angularjs.org ?

**Comment by krassx** [comment]
My bad. Content blinking was caused by 'transform: translateZ(0)' on md-content (attempt to force GPU).

However, I see blinking of shadow under this part http://gyazo.com/5ed296b1da018cb63d8c30f97bd9d6ff when expand/collapse groups in left panel. Not sure how it's related.

And perfomance is still an issue. When I expand/collaps groups in left panel on https://material.angularjs.org, it reacts with annoying delay. And animations are not smooth too. But be aware that it happens on iPad mini. On Android devices (my smartphone and another tablet) and desktop PC everything works perfectly.

If you need a video or kind of screen cast let me know. I will post it here.

**Comment by kschwidder** [comment]
With 0.9.4 I have seen an significant improvement of the performance again. Thx !

**Comment by paulirish** [comment]
I'm seeing this same issue on Google internal moderator app. Googlers should be able to access it, turn on show scrolling bottlenecks, and verify.  :)

**Comment by ThomasBurleson** [comment]
@paulirish - thx for the alert.

**Comment by SeeeD** [comment]
I can confirm this issue. On devices with low CPU this is a show stopper because you can't scroll smoothily. I fixed it with a hack: 
>md-content {
>    overflow: initial!important;
>}

**Comment by ThomasBurleson** [comment]
Pair with @robertmesserle

**Comment by hughred22** [comment]
+1 for this issue. 

@SeeeD 
md-content {
overflow: initial!important;
}
fix the issue. But it break md-scroll-shrink toolbar. No idea what else it is break as well.

**Comment by ThomasBurleson** [comment]
@topherfangio - see the md-content solution ^.
