### ISSUE TITLE
md-input-container wrong label with dynamic placeholder and wrong position in md-no-float layout="row" and wrong color in md-toolbar

### ISSUE THREAD

**Issue by redyyu** [angular/material#2888]
ver: 0.9.4 

#### That's what happened while both have dynamic placeholder and label

If placeholder is not dynamic the label will eat (replace) the placeholder
but if dynamic with angular value or function. will show duplicate.

see the screenshot

![screen shot 2015-05-18 at 4 43 37 pm](https://cloud.githubusercontent.com/assets/724821/7677458/ca082082-fd7e-11e4-9c4f-8d388da18552.png)

![screen shot 2015-05-18 at 4 43 49 pm](https://cloud.githubusercontent.com/assets/724821/7677467/dbf72766-fd7e-11e4-859d-992b37274ffd.png)

================================

#### Wrong position in md-no-float layout="row"

That's what happened when using md-no-float to hidden the float label.
ps: Strange thing is If I put another input beside it, and not using 'md-no-float', both input will go right.

![screen shot 2015-05-18 at 4 44 21 pm](https://cloud.githubusercontent.com/assets/724821/7677529/5f633950-fd7f-11e4-837b-27dfba5c0492.png)

Put two input first one don't have md-no-float

![screen shot 2015-05-18 at 4 43 49 pm](https://cloud.githubusercontent.com/assets/724821/7677576/c4ebd1ec-fd7f-11e4-8aa9-e8cdcfb4d2d6.png)

================================

#### Wrong color while input in md-toolbar

Put a input intro md-toolbar, they both are primary color as default.

that's what happened.

![2015-05-18 4 49 59](https://cloud.githubusercontent.com/assets/724821/7677602/13f73bd2-fd80-11e4-84be-c97789943008.png)

![2015-05-18 4 50 26](https://cloud.githubusercontent.com/assets/724821/7677603/155500b8-fd80-11e4-97ae-ea167892aed3.png)

change the background to orange by force, show more clear.
the input is not disappear, it's just turn to same color with toolbar's background.

![2015-05-18 4 49 44](https://cloud.githubusercontent.com/assets/724821/7677601/12f9cf24-fd80-11e4-89d0-5815f663f60b.png)

**Comment by Splaktar** [comment]
@redyyu there were a number of fixes in this area in 0.9.8 and 0.10.0. Can you please provide some feedback on whether or not this is resolved in 0.10.0?

**Comment by redyyu** [comment]
I think This issue is no longer problem, I think this topic can be closed.
I have another Topics I put a codepen sample for 0.10.0 problems. I believe someone is working on it.

But I can't find the other issue link now.

**Comment by Splaktar** [comment]
@redyyu that's great to hear! Thank you for confirming this!
