### ISSUE TITLE
md-list's md-subheader show wrong line-height?

### ISSUE THREAD

**Issue by redyyu** [angular/material#2891]
line height maybe too small?

![screen shot 2015-05-18 at 6 26 30 pm](https://cloud.githubusercontent.com/assets/724821/7679358/7c46c56e-fd8e-11e4-9eb9-d85f6a305fe6.png)

there is screen from google design
looks like should have little bit padding at bottom.

![screen shot 2015-05-18 at 6 26 30 pm](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0Bx4BSt6jniD7OWVYZFY4N3lGRGs/components_subheaders3.png)

**Comment by topherfangio** [comment]
I believe this has already been fixed as the line-height in the demos is `1.2em`.

If you're still seeing this issue, please provide a Codepen showing the issue and we will reopen.
