### ISSUE TITLE
mdBottomSheet: add ability to disable clickOutsideToClose option

### ISSUE THREAD

**Issue by yccteam** [angular/material#2895]
The bottom sheet gives the site a quick and beautiful "bottom popup". Is it possible to add a ```clickOutsideToClose``` feature to it? Much like the dialog box?

**Comment by ThomasBurleson** [comment]
The bottomSheet already supports a clickOutside (on the mask area) to close:

*  https://github.com/angular/material-start
*  https://material.angularjs.org/#/demo/material.components.bottomSheet

**Comment by yccteam** [comment]
Sorry - I was not clear. What I meant is - I want to set it to ```false```, but there is no such option.

**Comment by marcysutton** [comment]
The naming should probably be updated to `tapOutsideToClose` because it's intended to be a mobile-only component.

**Comment by dmackerman** [comment]
I agree with @yccteam in that this is not "necessarily" a mobile only component, because we're allowing custom templates.  On desktop, there are some very interesting options for bottom sheets (or bottom dialogs) as alternatives to full screen modal dialogs.

**Comment by marcysutton** [comment]
That was according to the MD UX team. But so far there has been no discussion about what a bottom sheet should morph into in a responsive app, so that's why it's important that it have focus management (sending focus into the bottom sheet on open, and back to triggering button on close).

**Comment by ThomasBurleson** [comment]
I think the `md-is-locked-open="<expression>"` should work for SideNav, BottomSheet, and Dialogs.
