### ISSUE TITLE
$mdTabs service? Select tab from controller

### ISSUE THREAD

**Issue by juanpujol** [angular/material#2896]
Is there a way to select an md-tab from the Controller? Thank you.

**Comment by ferc** [comment]
In **md-tabs** directive, you can add the *md-selected* attribute, for example:

```HTML
<md-tabs md-selected="selectedIndex">
```

```javascript
$scope.selectedIndex = newTabIndex;
```

**Comment by juanpujol** [comment]
thanks @ferc, thats exactly what I needed.

**Comment by PeaFull** [comment]
@ferc hello ,do u know how to select an md-tab from the other controller
