### ISSUE TITLE
mdAutocomplete: XSS vulnerability

### ISSUE THREAD

**Issue by chr22** [angular/material#2901]
You generate HTML from a string to highlight the matching part of the search string in the result.

https://github.com/angular/material/blob/master/src/components/autocomplete/js/highlightController.js#L11

If the search result is this as a string:
![capture](https://cloud.githubusercontent.com/assets/3649594/7702593/a2286488-fe31-11e4-8250-d93cd098b193.JPG)

and you search for "x" then the resulting output is this, with a real script-tag that gets executed:
![capture1](https://cloud.githubusercontent.com/assets/3649594/7702571/7a7e69dc-fe31-11e4-855f-130920a983a9.JPG)

I cant create a CodePen because it won't let me insert a script tag in a javascript string.

I can see that you have some sort of sanitizing with a RegEx, that i cant decipher.

**Comment by ThomasBurleson** [comment]
@robertmesserle, @gkalpak - With the https://github.com/angular/material/commit/33ac259d66c90e96489d0512ac762f969458f5bd, should this be closed now?

**Comment by robertmesserle** [comment]
@ThomasBurleson Leave this open, I pushed this fix without any unit tests, so I'd like to leave it open to make sure I don't forget to add that.

**Comment by gkalpak** [comment]
(BTW, I am not even sure the fix actually fixes the issue. @robertmesserle, did you test it "manually" ?)

**Comment by robertmesserle** [comment]
@gkalpak Added unit test, confirmed new fix.  I had tested it earlier, but I was rushed and it turns out my test wasn't very good. =p  This is why I left this open so I could have a non-rushed look at it.

**Comment by gkalpak** [comment]
:+1: @robertmesserle

**Comment by gkalpak** [comment]
And :+1: @chr22 for reporting this :smiley:

**Comment by chr22** [comment]
:+1:

**Comment by ThomasBurleson** [comment]
@chr22 - can you contact via email: ThomasBurleson@Gmail.com. Thx
