### ISSUE TITLE
(0.9.4) mdSelect causes page to jump to top in firefox 

### ISSUE THREAD

**Issue by butaixianran** [angular/material#2903]
This is an old issue as #1648 

It has been fixed in 0.9.0, but some how it comes back in 0.9.4
check this:
http://codepen.io/butaixianran/pen/waWRmN

Plz fix it again...

**Comment by ThomasBurleson** [comment]
@rschmukler - can you investigate ?

**Comment by butaixianran** [comment]
This issue hasn't been fixed yet, it comes back even with the latest anuglar material.

check this on firefox:
http://codepen.io/butaixianran/pen/waWRmN

I think I have to open a new issue for this again.
