### ISSUE TITLE
md-select-label must works with label

### ISSUE THREAD

**Issue by alexnaldo** [angular/material#2904]
Using <label> with md-select-label must works like any others input control.

```                            <md-input-container>
                                <label>"Genre"</label>
                                <md-select ng-model="ctrl.model.tipoSalario">
                                    <md-option value="0">Male</md-option>
                                    <md-option value="1">Famale</md-option>
                                </md-select>
                            </md-input-container>
```

**Comment by prasannapattam** [comment]
I also vote to this feature. md-select is also an input control similar to textboxes. In a form we will have select along with textboxes. So to be symmetric md-select should behave similar to textboxes inside the md-input-container. 
https://material.angularjs.org/latest/#/demo/material.components.input

**Comment by naomiblack** [comment]
This would be a nice addition, but unfortunately out of scope for our 1.0

**Comment by ThomasBurleson** [comment]
@alexnaldo - A Pull Request with this feature (and perhaps md-floating-label) would be welcomed.

**Comment by DevVersion** [comment]
@ThomasBurleson This seems to be added already?
