### ISSUE TITLE
mdRipple lag/delay

### ISSUE THREAD

**Issue by norkunas** [angular/material#2905]
This is from the https://material.angularjs.org/#/demo/material.components.button
![orig](https://cloud.githubusercontent.com/assets/2722872/7707920/1b7a60ce-fe5b-11e4-8a92-f2c681c60002.gif)

And this is from it's demo in CodePen 
![demo](https://cloud.githubusercontent.com/assets/2722872/7707922/1f396782-fe5b-11e4-909a-dbe35dd5e2b8.gif)

As you can see in the second gif the ripple effect starts with some delay and is not that bright as in first example.
I'm using Chrome 43.0.2357.65 m (64-bit). Also i should mention that this happens only with buttons in that section and with others below. Above buttons works good. And with themed buttons below i can barely see the effect.
![themed](https://cloud.githubusercontent.com/assets/2722872/7708196/cfc3bb56-fe5c-11e4-86b1-684df8dba3f9.gif)

Also i have this problem in my layout when i have included the button after two of md-content blocks, the button works as in third example, but after i delete those two it works as expected.

**Comment by dbo35** [comment]
I'm experiencing this as well - wanted to point out that it starts to lag as soon as I scroll down.  Scrolled all the way to the top, the ripple acts as it should, and gets increasingly delayed the further the page is scrolled down.  

<md-content>
<div><div>
<md-card>
<md-card-content>
<div><div>
<md-button>
