### ISSUE TITLE
(>= 0.9.0) md-list-item using ng-repeat doubles in size briefly when updating items

### ISSUE THREAD

**Issue by adamduren** [angular/material#2906]
[Codepen Demo](http://codepen.io/anon/pen/rVLKNm)

This is a regression from 0.8.3.

When updating a list of objects bound with `ng-repeat` to `md-list-item` the `md-list` briefly shows what I believe is a combination of the old list and the new list for the repeater.

There are two lists in the codepen demo. The first is an array of objects and the second is an array of integers. Only the array of objects is experiencing this behavior.

**Comment by zacharytamas** [comment]
:+1:

**Comment by zlovin** [comment]
@rschmukler I forked the codepen @adamduren provided and updated the version of material to 0.10.0, the original problem is present again.
http://codepen.io/anon/pen/gpXgqo?editors=101
