### ISSUE TITLE
Slider: allow dynamic change of max value for slider

### ISSUE THREAD

**Issue by HenrikBechmann** [angular/material#2909]
currently, changing max at runtime has no effect on slider layout

use case: 
- slider represents number of records in recordset. 
- user applies search filter, changing the number of records in the recordset
- slider max should change to reflect the new size of the recordset

Similar use cases would pertain for any dynamically-sized recordset represented by the slider.

**Comment by EladBezalel** [comment]
@HenrikBechmann seems to be [fixed](http://codepen.io/EladBezalel/pen/qbBJPd) since 0729587
