### ISSUE TITLE
$mdDialog not finding template with <script type="text/ng-template">

### ISSUE THREAD

**Issue by diogodomanski** [angular/material#2912]
I'm trying to show a dialog whose content come from a `<script type="text/ng-template">` tag, but it's not working.

In index.html file I have the following code inside `<body>`

```html
<script type="text/ng-template" id="save-dialog.tmpl.html">
   my dialog template content
</script>
```

In index.js file have the following code

```javascript
             $scope.submitData = function ($event) {
			$mdDialog.show({
				controller: 'SaveDataController',
				targetEvent: $event,
				templateUrl: 'save-dialog.tmpl.html'	
			})
			.then(function (answer) {
				console.log(answer);
			}, function () {
				console.log('failure');
			});
		};
```
Whenever I call `$scope.submitData()`, `$mdDialog` is trying to use `http://my.domain/save-dialog.tmpl.html` url instead of the one defined with `ng-template`. What am I doing wrong?

Thanks

**Comment by rschmukler** [comment]
@diogodomanski the `#save-dialog.tmpl.html` must be a child of the `$rootElement` (ie. where you have the `ng-app`. You mentioned putting it in the `body` element. Is your `ng-app` a sibling / child of your template?

See [this pen](http://codepen.io/rschmukler/pen/ZGONaJ) for an example of it working.

**Comment by diogodomanski** [comment]
Thanks @rschmukler. I was placing the template outside the tag with ng-app.

**Comment by rschmukler** [comment]
Awesome! Closing
