### ISSUE TITLE
md-select option list badly positioned when page is scrolled

### ISSUE THREAD

**Issue by HenrikBechmann** [angular/material#2913]
when page is partially scrolled, md-select option list is rendered such that part of the option list overflows (is hidden) at the top of the browser window. moreover page scrolling is disabled when the list is shown, making it impossible to view the options. In some circumstances the entire list is hidden, and with the page scrolling disabled, the user perceives herself to be in a trap. (solution is to click anywhere to dismiss the hidden option list).

The following screenshots show the list when the page is scrolled (partly hidden), and the list not hidden (when the page is not scrolled because the prose has been hidden with the 'toggle overview' button).

note that the screenshots are from my local vm. I'll update the code behind this shortly at http://mustertools.net/demos/listdemo/

![2015-05-19 04 35 43 pm](https://cloud.githubusercontent.com/assets/4584381/7713537/61c28576-fe46-11e4-87a3-a33bb404041c.png)

![2015-05-19 04 38 07 pm](https://cloud.githubusercontent.com/assets/4584381/7713544/695dfa22-fe46-11e4-8b6b-f2b16f0ad69a.png)

**Comment by HenrikBechmann** [comment]
behaviour can now be viewed at http://mustertools.net/demos/listdemo/ ('filter by record type' and 'sort by name or code fields'). To see behaviour, scroll the page down to the field (ish) before invoking one of the option lists.

**Comment by rschmukler** [comment]
This is fixed by 87a6d16501c50e3029ea531f90f45be8e3381518
