### ISSUE TITLE
md-input border-bottom hardly visible in Firefox

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#2914]
Compared to md-select, the bottom border on md-input is hardly visible in Firefox. The CSS is missing a `border-style: solid`.

See http://plnkr.co/edit/GpQAhsV81agCaZpsZZoL?p=preview

**Comment by gligoran** [comment]
+1 It seems the default ```border-style``` in Firefox is ```inset```, which make the coloring of md-input and select inconsistent.

**Comment by xtiggerk** [comment]
+1 still exist on 0.10.1
