### ISSUE TITLE
md-autocomplete direcive - positioning of results is wrong

### ISSUE THREAD

**Issue by jahtalab** [angular/material#2918]
I'm using md-autocomplete in my application, I have a watch on selectedItem and when ever it is null or undefined i change the layout of the page which affects the md-autocomplete tag, but the issue is that the results are displayed in the old position of md-autocomplete,

i fixed this issue by changing one line in handleResults function in MdAutocompleteCtrl 
```javascript
    function handleResults (matches) {
      cache[term] = matches;
      self.loading = false;
      if (searchText !== $scope.searchText) return; //-- just cache the results if old request
      promise = null;
      self.matches = matches;
      self.hidden = shouldHide();
      updateMessages();
        setTimeout(function() { positionDropdown(); }); /// I added this setTimeout.
    }
```
I know it's a bad solution, could you suggest a better one.
maybe adding an event to md-autocomplete, to reposition it's results.

also i'm willing to contribute.

**Comment by jelbourn** [comment]
@jahtalab Can you provide a demo?
