### ISSUE TITLE
sidenav animation complete event

### ISSUE THREAD

**Issue by jahtalab** [angular/material#2919]
I'm using sidenav in my application, when ever my window resizes i need to reposition some of my elements but if i do that immediately on window.resize, because the animation of sidenav is not complete yet my elements end up in wrong position. 
right now i solved this issue by setting a timeout for 600 ms before repositioning, but it would be useful if sidenav or ng animate could accept a handler to call when the animation is done,

**Comment by stijnvn** [comment]
@ThomasBurleson, is there already any solution or workaround for this?
