### ISSUE TITLE
md-chips : remove buttons not properly centered on Safari Mac OS X

### ISSUE THREAD

**Issue by kschwidder** [angular/material#2920]
When running the demos under Safari on Mac OS X the remove button of a chip is not properly centered.

**Comment by toddpress** [comment]
submitted a [pull request](https://github.com/angular/material/pull/3043) to offer a fix for this.

**Comment by toddpress** [comment]
Also fixes issue [#2410] (https://github.com/angular/material/issues/2410). Confirmed to work in Firefox 35.0.1 and 38.0, Firefox Developer ed 40.0a2, and Safari 8.0.6.

**Comment by ThomasBurleson** [comment]
Fixed with merge of #2410.
