### ISSUE TITLE
clear ng-model on md-select does not work when multiple

### ISSUE THREAD

**Issue by myagoo** [angular/material#2921]
mdSelect does not refresh view value when multiple is true and value is set to undefined.

Here is an example pen forked from validation demo of mdSelect directive
http://codepen.io/myagoo/pen/jPMOwZ

**Comment by ByJC** [comment]
+1

**Comment by whoknows** [comment]
+1

**Comment by myagoo** [comment]
Any workaround while waiting for this to be fixed ? This bug is really annoying, we use md-select to build a generic selector abstraction in our application and we are unable to reset them ><

**Comment by sckoh** [comment]
i use ng-if to recreate the md-select when i click on the reset button as a temporary workaround

**Comment by Masadow** [comment]
@sckoh Good workaround ! I prefer to use a timeout 0 to avoid the blink effect.

**Comment by anjroo** [comment]
@sckoh Thank you! Exactly the problem I was facing. Great solution.

**Comment by naresh8t7** [comment]
When the fix will be available for this issue ?
