### ISSUE TITLE
flat md-button no hover effect inside md-list

### ISSUE THREAD

**Issue by redyyu** [angular/material#2922]
md-button flat style has hover effect in the official demo
https://material.angularjs.org/#/demo/material.components.button

but is not show up while inside md-list (background is while)

**Comment by KReden** [comment]
As a workaround to this i put:
```
md-list md-list-item button.md-button:not([disabled]):hover {
    background-color: rgba(158, 158, 158, 0.2);
}
```
in my css. It seems that when in a list md-button's hover rule gets over written with this one:
```
md-list md-list-item button.md-button:not([disabled]):hover {
  background-color: #FFF;
}
```

**Comment by almgwary** [comment]
it is hover in parts not the full item

**Comment by VenkataRamanaT** [comment]
if i hover on fabToolbar button (md angular js), then it should work (expand) without click button.

**Comment by VenkataRamanaT** [comment]
i want to know
