### ISSUE TITLE
Theming not working correctly in md-slider in release 0.8.3

### ISSUE THREAD

**Issue by Darwesh27** [angular/material#2923]
I have a custom theme called 'bad'. When I apply this theme on `md-progress-bar` it works properly while it is not working on `md-slider`. Here is how I configured the theme..

```
$mdThemingProvider.theme('bad')
		    .primaryPalette('red')
		    .accentPalette('green')
		    .warnPalette('blue')
		    .backgroundPalette('grey');
```

and here is how I apply that on slider. 

```
<md-slider md-theme = "bad"  ng-model="rating" min="1" max="10" aria-label = "rating"></md-slider>
```

and here is how it looks.
![screenshot from 2015-05-20 15 18 41](https://cloud.githubusercontent.com/assets/4861876/7723627/896c0602-ff03-11e4-9851-80036243cf95.png)

**Comment by marcysutton** [comment]
Hi, please update to the newest version. I don't think changes have been made to slider, but we are only debugging the newest release.

**Comment by Darwesh27** [comment]
I've updated to version 0.9.0 but still it is the same problem..

**Comment by Darwesh27** [comment]
@marcysutton . Will you please have a look at it..?
