### ISSUE TITLE
Tab control do not allow to click on arrow

### ISSUE THREAD

**Issue by renato04** [angular/material#2924]
Hi!

If the tab's label is large the click to navigate between tabs do not works, is this normal?
You can see in the image bellow, i put the label 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' for test.

![image](https://cloud.githubusercontent.com/assets/5497267/7725488/81453ba6-fed1-11e4-8f12-1fe1c3eb213e.png)

Thank you!

**Comment by robertmesserle** [comment]
This should have been resolved - can you confirm?

(Closing for now)
