### ISSUE TITLE
Are there documented functions of `md-list`?

### ISSUE THREAD

**Issue by dmitriz** [angular/material#2925]
What exactly are the functions of `md-list`?

- The [documentation of `md-list`](https://material.angularjs.org/#/api/material.components.list/directive/mdList)
is impressively terse.

- The demo example does not seem to change at all when removing `md-list`
(http://codepen.io/dmitriz/pen/rVMVLm?editors=101)

- Yet the tests show quite a few things going behind the curtain: https://github.com/angular/material/blob/master/src/components/list/list.spec.js
with not a single comment explaining the intention.

Is this mystery uncovered somewhere or any plans to?

**Comment by rschmukler** [comment]
The tests you linked are for `mdListItem`. Most of `md-list-item`'s functionality is providing (ie. syntax to make things look like standard material list items) and accessibility (eg. automatically delegating click events to the appropriate child target if an `ng-click` is on a parent `md-list-item`.

The code for the `md-list` is as follows:

```js
function mdListDirective($mdTheming) {
  return {
    restrict: 'E',
    compile: function(tEl) {
      tEl[0].setAttribute('role', 'list');
      return $mdTheming;
    }
  };
}
```

So, it implements theming, and that's about it.

**Comment by dmitriz** [comment]
Many thanks, I see, the file is called `list` but the tests are for the `list-item`, sorry for the confusion :)

Any reason to use `.querySelector('div')` with `div` here (rather than another tag):
https://github.com/angular/material/blob/master/src/components/list/list.spec.js#L15

About `md-list` implementing theming - is there any explanation how this works? Is the theming working differently inside and outside the directive?

**Comment by rschmukler** [comment]
The query selector is in response to how the directive compiles itself. Specifically, it will, in that case, create a wrapper div. So we are just grabbing it.

As for the theming stuff, check out the [docs on theming](https://material.angularjs.org/#/Theming/01_introduction) which explains how theming could be used. Basically that line of code enables the component to alternate themes (for example one where your foreground palette used white text and a dark background). Check out the section on multiple themes for more information.

**Comment by dmitriz** [comment]
So am I right in understanding that any click on `<md-list-item>` is forwarded to all enclosed `<md-checkbox>` elements simultaneously? Even if I have several checkboxes, every one will be clicked?

About themes, am I right that `<md-list>` applies the default theme to anything inside it?
But then wouldn't `<md-checkbox>` or any other md- directive get the same default theme even without it?

This will apply a custom theme to anything inside:
```
  <div md-theme="altTheme">...</div>
```
But then again, wouldn't the same theme apply regardless of the `md-list` directive hanging around? 

Sorry for the confusion. 
Maybe it would be made clear by example, where `md-list` directive would change the behavior?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (421/400 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:54726)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZl-001Z7Q-Iu
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:18 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Qbj6b4H2H990O81wAbLom9Z+ok4=; b=MjpS+BACdO5XUGRl
	M3rKT0mIUYulaYuZeSxa7pTo20AHzo5Jf2mQoE8G7/PD8rBgzun5892Uj/ZAXYDn
	4IYTRlK2kcdI8fALaQbZhd0/T9Y7za3cE1utJ2tov+Otx8Gx/KtgkQSLzgnRjqa+
	3fhSKye1doVfTRyCKKVhV9Ov2xI=
Received: by filter0690p1mdw1.sendgrid.net with SMTP id filter0690p1mdw1.16926.572272AC3E
        2016-04-28 20:29:32.790214616 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id wrf9p1foQRGbe4vQ2RO71w
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:32.764 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:32 -0700
