### ISSUE TITLE
md-tabs: with position fixed element inside tabs

### ISSUE THREAD

**Issue by jakubweber** [angular/material#2927]
For example, you have page with tabs, on one tab you have floating fab button at right down corner of the screen. 

You can't set position fixed for element in md-tab-content. When I turn off css rule transform (on md-tab-content) element which has position fixed is correctly positioned to the browser viewport.

I think it is related to this behavior
https://code.google.com/p/chromium/issues/detail?id=20574
http://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform

When child has "position fixed", and parent has "transform" you can't position child to the viewport via css "position: fixed". The child is positioned to the parent.

Tested on Window's Chrome browser and Firefox. Both wrong.

Btw. Is it good idea add fab button into tabs at all? One tab has fab button, another not.

**Comment by mckenzielong** [comment]
> Btw. Is it good idea add fab button into tabs at all? One tab has fab button, another not.

Seems like this is fine.  The material design spec has a nice example of using a fab with tabs: http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-behavior

> If there is a floating action button on multiple lateral screens (such as on tabs), upon entering each screen, the button should show and hide if the action contained on each is different. If the action is the same, the button should stay on screen (and translate to a new position, if necessary.)

**Comment by jakubweber** [comment]
I mean in code placing fab button into tab's content.

**Comment by bonatoc** [comment]
Maybe can put your fab button outside the tabs, but under the same controller, watch for the selectedIndex, and show/hide the button accordingly. I assume your fab button depends on the same controller/directive, since you want it to be inside a tab?

**Comment by bonatoc** [comment]
From an app point of view, I would make use of the FAB button only for the primary layer in the app actions hierarchy.

You want to use it in a tab, but not the others, I think that goes a bit against the implied rules the the FAB button should be perceived as a "main actions" button by the user.

What is your rationale behind using a FAB button in a tab? Do use md-tabs as entire pages/screens?

**Comment by RizwanAslam** [comment]
I am also facing the same problem to fix fab always on the screen in md-tab-content ..... but due to its viewport set to that container i am unable to fix its position on the screen.
I use fab to create some contents in the tab container but when number of elements increase in the container the fab button goes below the screen and user have to scroll to get it back on screen.
Please fix it soon.
