### ISSUE TITLE
Support releasing forks on bower

### ISSUE THREAD

**Issue by epelc** [angular/material#2928]
It would be really nice if the new release script let people outside google release/build forks for bower. This would make it a lot easier to use forks in prod while your waiting for them to be merged. You could just update your bower dependencies instead of jumping through hoops trying to build/publish it manually.

Also it might be good to support releasing npm forks. But I'm not sure of how the npm release works as I don't use it.

**Comment by ThomasBurleson** [comment]
@epelc - I am not sure I understand. You can fork the `angular/material` repo can do a build with any changes using `gulp build`. Is this not sufficient?

**Comment by epelc** [comment]
@ThomasBurleson I think I confused myself thinking `gulp build` wasn't giving me everything I need. I can just copy everything from `gulp build` to a bower-material fork and it works perfectly.
