### ISSUE TITLE
Clicking Input label should cause focus to the field

### ISSUE THREAD

**Issue by joeyperson** [angular/material#2933]
Currently inputs can only be clicked in the area below the floating label. The hit target should also include the area where the label sits when a value is present (whether the label is present or not).

**Comment by arlowhite** [comment]
Also, how about clicks on a md-icon within md-input-container focusing the field by default?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
