### ISSUE TITLE
Custom Dialog Issue in IE on dialog content height change

### ISSUE THREAD

**Issue by WonSong** [angular/material#2934]
Only happening in IE.

Happens sometimes on dialog open, but happens every time when I scroll:

![image](https://cloud.githubusercontent.com/assets/5981331/7740856/5bf08170-ff2c-11e4-9ab0-feafd65ae1f9.png)

Once I turn ```overflow: auto``` off and on using developer tools, it starts working again. 

![image](https://cloud.githubusercontent.com/assets/5981331/7740892/cd682650-ff2c-11e4-85cc-16917d37ea31.png)

Then if I remove a dialog content using develop tools, scroll goes away and the action bar on the bottom goes away

![image](https://cloud.githubusercontent.com/assets/5981331/7740906/ffe1947c-ff2c-11e4-895b-25705de76f42.png)

I can make it start working again by turn ```overflow: auto``` off and on again.

**Comment by ivanhtp** [comment]
+1

**Comment by Splaktar** [comment]
Closed by 621bdf7069c0eacc27f655a11ddb89e3e3526476.
