### ISSUE TITLE
md-toast makes scroll bar appear during animation when positionned bottom

### ISSUE THREAD

**Issue by NicolasVargas** [angular/material#2936]
Hi guys,

Thanks for your constant enhancement of angular material design.

As you can see on [CodePen](http://codepen.io/anon/pen/YXGZQx) where i reused the [doc demo](https://material.angularjs.org/#/demo/material.components.toast), the scroll bar appears during the appear/disappear animation of a `md-toast` component positioned at bottom.
It is certainly caused by the fact that the `md-toast` component is first created at position *documents' height + its own height* and then it goes up a position *documents' height*.
On the other hand, this event doesn't appear when the toast is positioned top even if it's animation shows him appearing from a higher position.

Thank you, 

Izcalli

**Comment by TalPasi** [comment]
+1

**Comment by lasdjs** [comment]
+1

**Comment by mpelts** [comment]
+1

**Comment by webley** [comment]
+1

**Comment by gpopovic** [comment]
+1

**Comment by ricardobfa** [comment]
+1

**Comment by EinArzt** [comment]
+1

**Comment by mattblang** [comment]
+1

**Comment by vigneshdv** [comment]
+1

**Comment by sh0uzama** [comment]
+1

**Comment by karthikcsridhar** [comment]
+1

**Comment by Soulcyber** [comment]
+1

**Comment by kitensei** [comment]
+1

**Comment by thomasbertet** [comment]
+1

**Comment by gpopovic** [comment]
to get rid of scrollbar, just put overflow:hidden to body.

**Comment by Soulcyber** [comment]
In my case i've solved attaching the controller which control the toast to the body element.

**Comment by YashdalfTheGray** [comment]
+1

**Comment by ThomasBurleson** [comment]
Works fine on online Docs.

**Comment by rscottfree** [comment]
It works in the demo page because the demo's container has ```overflow: hidden``` which is added as part of the ```.demo-content``` class. Look at the codepen posted in the first comment here; it's broken there because it's container does not have ```overflow: hidden```.

If this isn't going to be fixed, then it should be documented that to use mdToast you have to set its container to have ```overflow: hidden```.

**Comment by HartgerV** [comment]
+1

**Comment by ThomasBurleson** [comment]
@rscottfree - Excellent point: doc change or component improvement.

**Comment by twrk** [comment]
+1 to temporary workaround of adding overflow: hidden to the body tag :)

**Comment by DmitryEfimenko** [comment]
+1. I think it should be a component improvement.

**Comment by marquinhoalm** [comment]
+1

**Comment by stefan--** [comment]
+1

**Comment by gfviegas** [comment]
+1

**Comment by cleydsonjr** [comment]
+1

**Comment by spudowiar** [comment]
+∞

**Comment by topherfangio** [comment]
Bumping priority; will try to get it done in RC4.

**Comment by tkonya** [comment]
@twrk It looks like somebody at Google took your advice. They put overflow:hidden on the body tag on the material.angularjs.org and basically broke the whole site. Now I can't see all of the options in the menu or read any more than 1 page or content, at least until I open dev tools and remove that attribute...

**Comment by TheJesper** [comment]
In my case the scroll-bar is hidden shortly during the animation. This creates a "flickering" user experience every time the toast is displayed, especially when many toasts are "queued up" and the scroll-bar shows and hides multiple times.

The CSS causing this should definitely be eliminated from the angular/material code.

**From angular-material.css:**
`md-toast-animating{
overflow:hidden!important
}`

**So, depending on what you want to achieve you could always override this:**
`body.md-toast-animating {
    overflow: auto !important;
}`

Hope this helps someone! /Jesper Wilfing

**Comment by chris-carrington** [comment]
@TheJesper Thank you for existing!

**Comment by DmitryEfimenko** [comment]
in latest version they prefixed this class with an underscore. So:
```css
body._md-toast-animating { overflow: auto !important; }
```

**Comment by bobwah** [comment]
sorry for my lack of understanding, why is:

md-toast-animating{ overflow:hidden!important }

needed in the first place?

**Comment by topherfangio** [comment]
@bobwah That code was added to fix this bug (#2936) of the scrollbars appearing during animations. We have a better fix in mind and I had a working prototype at one point. I will track that down and see what it wasn't merged.

**Comment by bobwah** [comment]
sounds good! thanks

**Comment by RyanHayden** [comment]
I was having the same issue, fixed by wrapping my root component in md-content with flex set to 100.  This also fixed the issue of the toast appearing mid screen when I scrolled.  If you look at the html the body was not growing appropriately with the component content, unless this was added.

<md-content flex="100">
    <menu></menu>
    <div style="padding: 5px;">
        <page></page>
    </div>
</md-content>

**Comment by eranshapira** [comment]
i have to say that the fix of overflow: hidden !important; is probably the worst possible fix to that error. breaks pages.

**Comment by jjhesk** [comment]
+∞

**Comment by dcarrask** [comment]
Thanks @RyanHayden!!
After few day investing some time without getting any solution FINALLY I got it thank to your tip!
Cheers, mate!

**Comment by Anujndls** [comment]
+1
