### ISSUE TITLE
md-select prevent focus on close

### ISSUE THREAD

**Issue by evoker** [angular/material#2937]
Hi,

is it possible to stop the focus event for md-select after it closes?

My problem lies with this line here:

    if (opts.restoreFocus) opts.target.focus();

The select box in question is at the bottom of the page and since it's focused after it closes, it messes with my page refresh.

I have attempted to prevent the event from firing altogether but I had no luck so far.

Thanks in advance for any comments/input.

**Comment by marcysutton** [comment]
This focus event is necessary for accessibility, because the list items are separated from the actual select. Can you provide a Codepen or Plunker showing your code?

**Comment by nyxtom** [comment]
This makes it difficult to support a simple editor which relies on this not happening :|
