### ISSUE TITLE
changing md-checkbox background color dynamically

### ISSUE THREAD

**Issue by loykianos** [angular/material#2939]
I need a way to dynamically change an md-checkbox's color depending on a value returned by a service. I tried ng-style but it doesn't seem to work. It changes the background-color of the md-checkbox element, but not of the actual checkbox container.

**Comment by loykianos** [comment]
I managed to do it, by adding an ng-style on the main element and a background-color: inherit on the md-checkbox icon.

**Comment by jaimegarcia** [comment]
I did it using in the html `<md-checkbox class="dynamic-color-checkbox" md-colors="::{background: checboxColor}"`, 

js:

`$scope.checboxColor='red' `

 and then in the css:
```
.dynamic-color-checkbox ._md-icon{
  background-color:white!important;
}
.dynamic-color-checkbox.md-checked ._md-icon{
  background-color:inherit!important;
}
```

**Comment by sjlynch** [comment]
Worked well, but I had to add the following css to remove an artifact where a small rectangle of the color was showing to the right on the checkbox whether it was checked or unchecked. Css below:
```
md-checkbox.dynamic-color-checkbox {
	width:0px;
}
```
