### ISSUE TITLE
Text flows outside of toolbar

### ISSUE THREAD

**Issue by matthewrfindley** [angular/material#2941]
The breadcrumb on the right side of the menu overflows the toolbar between 400px - 960px wide.

![screen shot 2015-05-21 at 9 22 22 am](https://cloud.githubusercontent.com/assets/483058/7753570/219201ba-ff9b-11e4-923a-e1e3911741dd.png)

**Comment by marcysutton** [comment]
Suggested fix relies on mdMenu, which is still forthcoming: https://github.com/angular/material/issues/2348
