### ISSUE TITLE
Font size issues when md-select is on a md-toolbar (0.9.0)

### ISSUE THREAD

**Issue by butaixianran** [angular/material#2944]
There are 2 issues here:

1. When a md-button and a md-select both on a md-toolbar:
md-button's font size won't be effected by md-toolbar's style, but md-select-label does. So, on this toolbar, the font size of md-button is small, but font size of md-select-label is very big.

2. md-toolbar's font size is set to 20px in CSS of 0.9.0, and md-select-label's line-height is set to 1.2rem. So, when a md-select is on a md-toolbar, the text of md-select-label gonna be cut from top and bottom.

**Comment by marcysutton** [comment]
Please check the latest on master. There are no more `rem` units.
