### ISSUE TITLE
md-select options are nowhere near the selector

### ISSUE THREAD

**Issue by wlingke** [angular/material#2945]
Click on the first one and it will be fine. Afterwards scroll down a little, the options selection box will be WAY above the select (sometimes out of screen so it looks like it doesnt show up)

http://codepen.io/anon/pen/VLKMgN

![screenshot 2015-05-21 10 30 39](https://cloud.githubusercontent.com/assets/3145536/7754883/cfb7901c-ffa4-11e4-8fc4-7c2e30087792.png)
.

**Comment by chauduc** [comment]
Yeah! i have the same problem 
https://github.com/angular/material/issues/2935
Hope it will be fixed.

**Comment by rschmukler** [comment]
This is fixed on master - the codepen you submitted now works.

**Comment by wlingke** [comment]
Great thanks
