### ISSUE TITLE
Error handle if docs.json is not present

### ISSUE THREAD

**Issue by gatormike** [angular/material#2946]
Currently throwing 404 if docs.json is not available.
![5-21-2015 2-05-52 pm](https://cloud.githubusercontent.com/assets/2046826/7755509/89d5872a-ffc2-11e4-881b-c1f70d5245dc.png)

Perhaps add check line 272 app.js:

    $http.get("/docs.json")
    .success(function(response) {...})
    .error(function(err){...}

Or create empty docs.json on build?  
Thanks.

**Comment by marcysutton** [comment]
Once the DNS changes over to our new system this should go away.
