### ISSUE TITLE
Horizontal scroll bar shows up when placing a md-list md-subheader inside md-tabs

### ISSUE THREAD

**Issue by asans** [angular/material#2947]
Inside a dialog (md-dialog-content), when one places a md-list within a md-tab, the horizontal scroll bar shows up.

Upon investigation and debugging, it appears that the casue for the horizontal scroll bar is caused by the new `margin: 0` property specified for `md-dialog-content .md-subheader`.    With margins at 0, the scroll bar shows up.  

If I were to set the margin-right to 16px, then the horizontal scroll bar disappears.

I've made a plunkr to reproduce this issue.

http://plnkr.co/edit/octvrE?p=info

This happens in v0.9.4-master-c7ea4a7

**Comment by pmdusso** [comment]
+1 I'm having this issue also, but in my case I'm using a `ng-include` inside a `md-tab`.
