### ISSUE TITLE
When opening a 2nd dialog on top of a first, $mdDialog.show cancels the promise from the 1st dialog 

### ISSUE THREAD

**Issue by demetriusnunes** [angular/material#2950]
If I have a dialog that launches a smaller second dialog on top of it, $mdDialog.show automatically cancels the promise returned by the original dialog, which breaks the UI flow.

The funny part, is that after the 2nd dialog is hidden, the original dialog re-appears, but its promise is already rejected.

**Comment by ThomasBurleson** [comment]
Dialog stacking, multiple dialogs, etc. will not be supported until post 1.0 releases.

**Comment by jaymanned** [comment]
Any workaround or alternative to dialog stacking?

**Comment by swalters** [comment]
This is a big deal for desktop apps.  A complex dialog frequently needs to present an "are you sure" dialog.  Any chance of raising the priority?

**Comment by foote-Greg** [comment]
+1  Desktop apps desperately need this functionality...
