### ISSUE TITLE
Dark themes have inconsistent styling for components

### ISSUE THREAD

**Issue by asans** [angular/material#2952]
Currently, when a theme is set to a dark theme, only affected components has its foreground color changed to the light hues.  These components ends up working correctly.

However, I am thinking that if the entire theme has been made dark, then there should be some way to make sure that the foreground color is set to light hues by default.  Currently, body has a default color set to `rgba(0, 0, 0, 0.87)`.  So what ends up happening is that non-component based colors are still black.

I understand that this may be intentional since these theme colors should only affect themed components, but let's say that we switch md-card to a dark theme.  Shouldn't the card content text also be light hues, not the default body black color?  

I have a plunker to showcase these inconsistent theme issues:

http://plnkr.co/edit/FE7q9g?p=info

Additionally, if I wanted the ENTIRE app to be dark themed, I think the default body color should be set to light hue.  Otherwise, I'd end up having to create a separate css style for this.  Shouldn't ngmaterial be able to either (1) set the default color hue in body or (2) give me a class style so that I can use it for my own text?  Otherwise, if I were to work with dynamic themes, we'd end up with inconsistent theme colors when themes switch.

**Comment by naomiblack** [comment]
We are deliberately leaving dark themes for post-1.0. They're nice to have, but complex to get right across the entire API surface.
