### ISSUE TITLE
flex=number within layout-fill does not work

### ISSUE THREAD

**Issue by wlingke** [angular/material#2954]
In the codepen below, you should be seeing a rectangle block of 30%, but the div ends up taking on no value.

http://codepen.io/anon/pen/yNaKbK

**Comment by gkalpak** [comment]
Not sure if this is a Flexbox issue or a browser issue (or both), as it behaves differently on each browser:

* It seems to work as expected on FF.
* It doesn't work on IE, but it does work if you add `[layout]` to `<body>`.
* It doesn't work on Chrome, but it does work if you add an explicit `height` (even `0`) on the _outer_ div. This also makes it work on IE (without putting `[layout]` on `<body>`. (Note that `height` is ignored on Chrome and IE, but not on FF.) 

Looking for a cross-browser (i.e. latest Chrome, FF, IE) work-around:
Currently, `[layout-fill]` sets `min-height: 100%` but nothing for height, which is supposedly for allowing the element to grow beyond that height. Although this **does** _theoretically_ sound reasonable, in practice I couldn't see any difference to the _outer_ div's height neither with nor without an explicit `height: 100%` (tried on Chrome, FF, IE).
_@all: Could it be a good idea to add a `height` style to `[layout-fill]` (at least on `[layout="column"]`) ?_

--
@wlingke, since FF **does** pay attention to `height`, setting an explicit value of `100%` for `height` on the _outer_ element gets the _inner_ element properly sized at 30% (while still having the _outer_ element fill its parent). E.g.:

```html
  <div class="outer" layout="column" layout-fill style="height:100%;">
    <span class="inner" flex="30"></span>
  </div>
```

[Demo CodePen][1]

If you want to apply this globally, you can add the following rule:

```css
[layout="column"][layout-fill] {
  height: 100%;
}
```

_**NOTE:** I couldn't find any unwanted side-effects on latest Chrome/FF/IE, but this might not be a full-proof solution across all supported browsers._
<sub>That said, I can't think of any usecase where setting `height: 100%` would be undesirable, but you never know...</sub>

[1]: http://codepen.io/ExpertSystem/pen/MwjGGW

**Comment by epelc** [comment]
@gkalpak Switching to `height:100%;` should also fix my layout issue with ie11. However I think there were some side affects in firefox so I suggested only applying it to ie11(and possibly lower versions but I didn't test any other versions).

This is also a problem in project spartan/edge

See #1766

**Comment by gkalpak** [comment]
@epelc, do you have a specific issue caused on FF (or any other browser) by using `height: 100%` with `layout-fill` ?

**Comment by epelc** [comment]
@gkalpak I just checked and it didn't break my app in firefox or chrome

**Comment by gkalpak** [comment]
I just realized why it works on FF: There is a special style for `[layout-fill]` on FF that sets `min-height: auto; height: inherit;`

This seems like a bug though; it should be `height: 100%` (if not for all browsers).

`height: inherit` will not work as expected in a situation like this:

```html
<div style="height: 50%">
  <div layout-fill></div>
</div>
```

(The inner div will have half the height of the outer in FF, not 100%.)

---
I feel more and more like `[layout-fill]` should have `height: 100%`. Any idea why this was decided against initially ?

**Comment by epelc** [comment]
@gkalpak I looked at that when I first filed my other issue. I could of swore I tried switching that override to `height: 100%;` in FF and it broke. I think something changed between then and now but I tried removing that override and using `height: 100%;` instead and it worked fine in FF.

**Comment by gkalpak** [comment]
Based on #497 it was supposed to cause some issues on FF (and IE?).
<sub>(I really don't get how #824 is fixing anything, but what ever...)</sub>

--
I might have been a bug in FF/IE that has been fixed now, so `[layout-fill]` could be reverted back to the previous `height: 100%`.

That said, I think we first need to decide (and clearly document) what `layout-fill`'s purpose is. Is it supposed to fill its parent both horizontally and vertically ? Or is it supposed to fill its parent on the main axis (i.e. depending on `flex-direction`) ?
Right now this is very unclear to me :confused:

**Comment by epelc** [comment]
Keep in mind that FF may have changed something over the past few months. I know I've updated it several times since then.

**Comment by wlingke** [comment]
Setting height to 100% may work in some solutions. The problem is then you can't have the effect of `min-height:100%` - ie if children elements grow beyond the height:100% size of the container, you can't expand your height.

**Comment by gkalpak** [comment]
@wlingke, could you provide a specific example (code or CodePen demo) where `height: 100%` imposes the limitation you mention ?
It is not very clear to me.

**Comment by epelc** [comment]
Just wanted to mention i've added an override to my `layout-fill` and it's been working very well. It also fixed several issues I was having in ie.

**Comment by wlingke** [comment]
Notice in this codepen, if you shrink the screen, the text overflows the `flex` section http://codepen.io/anon/pen/MwpOLE

The ideal scenario would be below (without height=100, but I am forced to use `flex` instead of `flex=number`). Here, as the child expand beyond the section, the section grows to accommodate it.

http://codepen.io/anon/pen/RPpjvX

**Comment by Schweigi** [comment]
Adding `height: 100%;` does lead to side effects when a page contains footers on Chrome & Safari. See the following Plunkr: http://plnkr.co/edit/j5fR7YpCYvfUiquiX7QL?p=preview (the footer is not on the bottom if the window needs scrollbars)

**Comment by gkalpak** [comment]
@wlingke, I don't get the example (and the the 2 pens seems identical). Could you elaborate ?

@Schweigi, your usecase seems to be using `layout-fill` incorrectly (imo). If you want to allow the element to overflow its parent, you just don't need to use `layout-fill`. Leave it out and let Flexbox do it's thing ([updated plnkr][1]).
But again it boils down to what is `layout-fill` supposed to do (which is kind of blurry atm).

[1]: http://plnkr.co/edit/vOylhd9JXuhNrZzZEXzQ?p=preview

**Comment by Schweigi** [comment]
@gkalpak But when `layout-fill` is removed then the footer isn't sticky anymore.

**Comment by wlingke** [comment]
@Schweigi Here is an update with better explanation:

The ideal behavior is:
- In small views where children content overflows parent, the parent should expand to the children
- In large views where children content is smaller than parent, the parent size should be determined by `flex=number` When the parent is a child of a full-page `layout-fill`, then the parent should be number% of the full page

There is no combination that achieves this currently. Here are the options:

http://codepen.io/anon/pen/MwpOLE - 2) is satisfied, however in small views the text overflows the black area due to height=100%

http://codepen.io/anon/pen/RPpjvX - 1) satisfied however, flex=number doesn't work in 2) as seen by this codepen: http://codepen.io/anon/pen/MwvBda - in large views where text does not overflow the black area, the black area is not 75% of the height as specified by `flex=75` (instead the black area covers as much as the text is covering)

**Comment by gkalpak** [comment]
> But when `layout-fill` is removed then the footer isn't sticky anymore.

@Schweigi, not sure what you mean by sticky. I don't see any difference between `layout-fill` and no `layout-fill`.

--
@wlingke, as you said, this doesn't work currently either (so it can't be an argument neither pro nor con `height: 100%`).

I seemed to have a hard time achieving what you want with flexbox (`ngMaterial` aside). Do you have a setup that achieves this with Flexbox (outside of `ngMaterial`) ?

**Comment by Schweigi** [comment]
@gkalpak With sticky footer I meant that the footer stays on the bottom of the browser window when the child content is not big enough.

@wlingke wrote in his last post the ideal behavior. My use case with the sticky footer is covered by this behavior.

**Comment by wlingke** [comment]
I honesty don't have enough experience with Flexbox to be able to set up something that emulates the ideal behavior, but this is what I think one should expect in terms of behavior.
