### ISSUE TITLE
md-tabs does not work on iOS

### ISSUE THREAD

**Issue by mfdev1** [angular/material#2955]
contents of md-tabs does not appear on iOS(my iPhone iOS8.1.1)

like this

![img_0018](https://cloud.githubusercontent.com/assets/11344789/7768899/917f3202-00ba-11e5-8694-2108f6eda636.PNG)

(https://material.angularjs.org/#/demo/material.components.tabs)

**Comment by bonatoc** [comment]
Be careful with when you give a title to an issue.

I think this is only related to the online demo. 
What about when you use md-tabs in your app?

**Comment by mfdev1** [comment]
this plunker is part of my app.

http://plnkr.co/edit/4eSH8qaLTQGJ8vM97lza?p=preview

**Comment by philmerrell** [comment]
I'm seeing this issue as well. Tab content reappears for a split second when transitioning from one tab to another, then promptly disappears. I can scroll the entire height of the would be tab content but it is visually blank.

**Comment by naomiblack** [comment]
This issue refers to an old version of Tabs. Latest version seems to be working. Please file a new issue with a screenshot if there are other problems.

**Comment by tamsler** [comment]
This issue still occurs. Created: https://github.com/angular/material/issues/4477
