### ISSUE TITLE
Default chip templates break after using interpolateProvider.startSymbol

### ISSUE THREAD

**Issue by rkennedy** [angular/material#2958]
If I change Angular's interpolation symbols to something other than the default `{{` and `}}`, then chips using the default template aren't displayed correctly. Instead of showing the chip label, the chip appears with the literal text `{{$chip}}`.

This seems to be a recurrence of issue #877.

For example, I have changed the symbols in my `angular.config` function:

```javascript
$interpolateProvider.startSymbol('{[{').endSymbol('}]}');
```

To work around the problem, I provide a custom chip template inside each use of `md-chips`, even though it's the same as the default, modulo the interpolation symbols:

```html
<md-chips ng-model="...">
  <md-chip-template><span>{[{ $chip }]}</span></md-chip-template>
</md-chips>
```

**Comment by websirnik** [comment]
+1. Placeholders also have hardcoded interpolation.
![screen shot 2015-06-18 at 19 46 31](https://cloud.githubusercontent.com/assets/282871/8239359/342ddc2c-15f3-11e5-8082-5d4391600baa.png)

**Comment by julbr** [comment]
Same issue for md-highlight-text

**Comment by GautierThiriez** [comment]
+1 for placeholders
