### ISSUE TITLE
ionic 1.0.0-beta.6 spinner, popover does not function

### ISSUE THREAD

**Issue by dracula359** [angular/material#2962]
I have a serious problem in my Ionic project when I use the version 1.0.0-beta.6 the application works well but (spinner, popover) does not function and when I switch to version 1.0.0 (spinner, popover) works but I have a list when I selected an item the controller not charge

**Comment by ThomasBurleson** [comment]
I assume that you mean you are using Ionic and Angular Material together?  Please see https://github.com/angular/material/issues/2365 for conflict details.
