### ISSUE TITLE
mdIcon support for PNG

### ISSUE THREAD

**Issue by zishanj** [angular/material#2963]
I am using latest 0.9.4 and I have seen that `mdIcon` is still not supporting PNG or other image files. It would be great if it support these regular image files also.

**Comment by ThomasBurleson** [comment]
Let's assume that `<md-icon ng-href="myLogo.png" />`, this raises several questions:

*  How is this any better than `<img ng-href="myLogo.png" />` ?
*  Would you still specify sizing, aspect ratio, etc with the CSS ?

**Comment by zishanj** [comment]
hmm... thanks for the reply. Btw, I have tried it with `mdButton` using `mdIcon` as it's class and then using `img` inside it:

    <md-button class="md-icon my-icon-button" aria-label="Bookmark">
     <img src="assets/images/bookmark.png" alt="Bookmark">
    </md-button>

It although works, but I have to do some extra CSS work like this:

    .my-icon-button {
      padding: 7px !important;
      min-width: 0;
      min-height: 0;
      line-height: normal;
    }

**Comment by ThomasBurleson** [comment]
You can also see how we used class names for the button and the icon/img here:  https://material.angularjs.org/HEAD/#/demo/material.components.bottomSheet

```html
<md-button class="md-grid-item-content" ng-click="listItemClick($index)">
        <md-icon md-svg-src="{{item.icon}}"></md-icon>
        <div class="md-grid-text"> {{ item.name }} </div>
</md-button>
```

Notice the button is style based on its use within a parent container, and the md-icon type provides styles for the icon. In your case you may want to do this:

```html
<md-button class="my-list-buttons" aria-label="Bookmark">
     <img src="assets/images/bookmark.png" style="my-img-button" alt="Bookmark">
</md-button>
```
