### ISSUE TITLE
Most paper elements wont load

### ISSUE THREAD

**Issue by dhdguysg** [angular/material#2964]
I have been trying to use it, AngularJS' default framework will work (and i have it on my site) but most of the paper elements will NOT load, but some elemets work like whiteframe etc.
(and by the way i have all elements i need downloaded and added onto the page)

For example, if i had this code:
(some html thingys are not put there due to markdown stuff)
md-button Button md-button
it would show as:
Button (with no paper)

ISSUE UPDATE:
I have removed the minified version. i am now using local files installed by bower, and i now am using a md-button tag with the class md-button, but the ripple will not appear, but the button will, i will still need a bit of help

**Comment by ThomasBurleson** [comment]
What is the issue you are encountering? Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNNqWm
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by dhdguysg** [comment]
The issue i am encountering is that some of the paper elements (pretty much only the action ones, havent tested all of them yet.)  CodePen Link: http://codepen.io/anon/pen/VLKOYX

**Comment by mchmielarski** [comment]
You have to bootstrap app. check it: http://codepen.io/mchmielarski/pen/vOXwyz

**Comment by dhdguysg** [comment]
I couldnt understand your english well enough, and i added your code but it wont work. I dont know if its my firefox or anything.

**Comment by dhdguysg** [comment]
ISSUE UPDATE:
I have removed the minified version. i am now using local files installed by bower, and i now am using a div tag, but the ripple will not appear, but the button will, i will still need a bit of help

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by dhdguysg** [comment]
Okay

**Comment by dhdguysg** [comment]
I have moved it, i will need help though
