### ISSUE TITLE
$mdThemingProvider - registering a theme on the fly

### ISSUE THREAD

**Issue by rgolea** [angular/material#2965]
Hi there!
First of all, I love Angular Material. I think you guys are doing an excellent job. Keep it up.

Secondly, and the reason I'm starting this issue is because I want my users to be able to register a new theme by adding 3 colour palletes together. I would like to search that in the database... so I will have active just one theme but I would need it to work with an ajax function...
The question is... is there a way to do that? Will it? Could you add a resolve method just like the routes?

If you want to see what I would be using it for... just check this out... https://github.com/rgolea/angular-deployd-admin/commit/3dd2a6f922eda5b1ec3befa30d3852fd4bc91756

I'm making an angular-material dashboard (free and open source for anyone who may need it). But in order to take full advantage of the angular-material capabilities I would need to do that option.

Thank you very much.

**Comment by ThomasBurleson** [comment]
@rgolea - I recommend add a snapshot of the [expected] UX to your the [Angular-DepolyD-Admin](https://github.com/rgolea/angular-deployd-admin) README.

> Meanwhile, let me discuss this with the team.

**Comment by rgolea** [comment]
Here is a snapshot... My users will change the different palletes and then set that setting as active. That will be the colour the app will have for all the users. Imagine the case scenarios where your users want to change colours in christmas, on birthdays or who knows... and you want them to get really creative and to choose the different palletes to make the theme they want. I don't think for this case scenario watching the theme would be a good idea but if you can adapt it... it would be way better.

Thank you for answering.

![screen shot 2015-05-25 at 16 58 56](https://cloud.githubusercontent.com/assets/8843202/7798828/77e1a914-02ff-11e5-8a7c-470aa1975e7c.png)

**Comment by websirnik** [comment]
I'm looking into similar functionality or best practice to achieve that. For us it's user's corporate colors that needs to be changed on a fly.

**Comment by rgolea** [comment]
The thing is that I was trying to change the theme in the `.run()` method and use `$mdThemingProvider` like a service. I found out later that you can't because you can't inject a provider in the `.run()` function. :(

**Comment by ThomasBurleson** [comment]
So the feature request is to be use post-initialization processes [such as .run() or $timeout callbacks] to be able to call an API similar to  `$mdTheming.theme('default').primaryPalette('pink')`

**Comment by rgolea** [comment]
Yes. But not with $timeout callbacks. Only on run because on `.config()` you can't use `$http` nor a factory. We need to do something like this:

```
$http.get([url_of_the_setting]).success(function(data){
     $mdTheming.theme([custom_name]).primaryPalette(data.primaryPalette); //with secondaryPalette, warnPalette and backgroundPalette too.
})
```

**Comment by ThomasBurleson** [comment]
@rgolea - my point is that developers my need it not only at .run( ) times but also at other times during the app lifetime.

**Comment by rgolea** [comment]
Oh yeah! For sure! Thank you a lot @ThomasBurleson . Keep up the good work! I really think you guys are making this project be the new bootstrap for everyone. Thanks a lot!

**Comment by Frank3K** [comment]
+1

There was previously also some discussion around this functionality in another issue, see https://github.com/angular/material/issues/1269#issuecomment-91597869.

**Comment by nolazybits** [comment]
+1
We need this functionality too...

**Comment by remcohaszing** [comment]
+1

**Comment by guilhermecvm** [comment]
+1

**Comment by chester1000** [comment]
+1

**Comment by joaogarin** [comment]
Any ideas on how to get his working?

**Comment by Frank3K** [comment]
@joaogarin: there is currently a PR for this: #5074.

**Comment by joaogarin** [comment]
Cool;)

**Comment by thanuzz** [comment]
+1

**Comment by gforster1993** [comment]
+1

**Comment by CodyMorris** [comment]
+1

I too am looking to build palettes based on hex values returned from a backend service.  I'm thinking the only other way to accomplish this would be to manually bootstrap your angular app, and fetch any required information before you config the app

**Comment by thanuzz** [comment]
+1

Also needed palette generation based on API/server values. 

For now fixed it a little bit dirty. After succesful login in the app I immediately fetch the palette values from the API and save them in local storage, Then I apply a `$window.location.reload(true);`. The app gets reloaded and at this point I can access the local storage in the $mdThemingProvider config and generate the palette. Reload is ofcourse not the most charming solution but it happens on an acceptable point in the user flow (after succesful login get's redirected to the home screen) and won't bother the user much.

**Comment by CodyMorris** [comment]
@thanuzz I exposed my palette values in an unauth'd endpoint, and then used a blocking ajax call to request it within the config.  Might want to give that a shot instead, assuming your backend is fast enough to return that response without harming ux

**Comment by thanuzz** [comment]
Thanks Cody the thought crossed my mind to use a vanilla sync XHR call but unfortunately my palette values are part of the user profile which I can only get after login through a auth. api call.

**Comment by fean** [comment]
+1

**Comment by LRPalacios** [comment]
+1

**Comment by timlevett** [comment]
:+1: We ran into a performance issue (loading time on safari) due to the theme creation. Our app has about 16 themes, but after we figure out who the user is we just use one of those themes. Seems like wasted cycles to generate all the other themes however we are not sure who the user is during the config phase. 

Generation of themes: https://github.com/UW-Madison-DoIT/uw-frame/blob/master/uw-frame-components/portal/main.js#L87

Theme config values: https://github.com/UW-Madison-DoIT/uw-frame/blob/master/uw-frame-components/js/frame-config.js#L5

**Comment by clshortfuse** [comment]
@EladBezalel I think we can close this one

**Comment by jazdw** [comment]
This should be re-opened, the 1.1.1 release notes say that this feature was merged but the commit was reverted before 1.1.1 was released.

**Comment by ThomasBurleson** [comment]
@EladBezalel - can you investigate and ensure the PR is either committed to master on pending as "presubmit" for 1.1.2?

**Comment by ThomasBurleson** [comment]
Fixed with SHA https://github.com/angular/material/commit/7090a1f1c024fc7d2b5a0506d2fc8d554d82fd6d

**Comment by akash-int** [comment]
I'm getting data in this format from API calling can anyone please help me out that how to apply this values to theme palate color

**Comment by akash-int** [comment]
{"primary":{"name":"fuse-paleblue","hues":{"default":"700","hue-1":"500","hue-2":"600","hue-3":"400"}},"accent":{"name":"light-blue","hues":{"default":"600","hue-1":"400","hue-2":"700","hue-3":"A100"}},"warn":{"name":"red","hues":{"default":"500","hue-1":"300","hue-2":"800","hue-3":"A100"}},"background":{"name":"grey","hues":{"default":"A100","hue-1":"A100","hue-2":"100","hue-3":"300"}}  - I'm getting data in this format from API calling. Can anyone please help me that how to apply this values to my theme & change color of my theme

**Comment by clshortfuse** [comment]
@Arns you should be able to use md-colors:

https://material.angularjs.org/1.1.4/api/directive/mdColors

**Comment by Arns** [comment]
@clshortfuse I might need some more details, I've read all docs and a lot of source code and it doesn't seem like any of this supports creating a theme on the fly - assigning one, yes - but not creating one with raw colors.

**Comment by clshortfuse** [comment]
@Arns You're talking about a custom palette. A palette is a list of colors. A theme is a list of palettes.

Creating a custom palette and assigning it as the accent palette: https://github.com/angular/material/blob/master/src/core/services/theming/theming.spec.js#L26

Creating a custom theme: https://github.com/angular/material/blob/master/src/core/services/theming/theming.spec.js#L755

**Comment by Arns** [comment]
@clshortfuse Ahh, yes! That is an enlightening distinction. Thank you!

**Comment by Splaktar** [comment]
@Arns Not at this time. Please file a feature request against `$mdTheming`.
