### ISSUE TITLE
0.9.4 is not found in the CDN.

### ISSUE THREAD

**Issue by Splaktar** [angular/material#2966]
https://ajax.googleapis.com/ajax/libs/angular_material/0.9.4/angular-material.min.js gives a 404.

**Comment by ThomasBurleson** [comment]
@robertmesserle - is our release process also updating the CDN?

**Comment by robertmesserle** [comment]
Nope, that can't be tied to our current release file.  That's still manual,
but will be added soon.

For now, I should include a reminder in the last message.

**Comment by ThomasBurleson** [comment]
@Splaktar - can you email me for offline chat ?

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you arrange for the 0.9.4 to be pushed to the CDN ?
@Splaktar - for development, we recommend that you use NPM to install locally...

**Comment by Splaktar** [comment]
@ThomasBurleson Yep, using bower for local development. I tested locally and everything seemed to be in good shape. Just looking for the CDN to be there before pushing this out to production since our production app pulls from the CDN. Giving a presentation about our app and it's use of angular-material at the Computer History Museum in MTV on Wednesday.
