### ISSUE TITLE
MD-Slider inside a carousel

### ISSUE THREAD

**Issue by anteksiler** [angular/material#2969]
Is there anyway that I can detect swiping over md-slider so that it does not affect the parent carousel?

**Comment by marcysutton** [comment]
Please ask this question in the [Angular Material forum](https://groups.google.com/forum/#!forum/ngmaterial) along with a Codepen or Plunker. Note that we don't really support carousels as they aren't in the Material Design spec (for good reason–they are ineffective as a design pattern).

**Comment by agianikas** [comment]
@marcysutton I'd love to hear more about why they are ineffective as a design pattern. :-)  I'd like to learn more about the thought process behind that idea.

**Comment by marcysutton** [comment]
@agianikas here you go: http://shouldiuseacarousel.com/
