### ISSUE TITLE
Cannot import angular-material-mocks.js using JSPM install of bower-material

### ISSUE THREAD

**Issue by jannisg** [angular/material#2971]
I'm trying to use the `angular-material-mocks.js` file as located in the `bower-material` [repo](https://github.com/angular/bower-material) which I am installing using `jspm install angular-material`.

The odd thing is that after running the `jspm install angular-material`, the `angular-material-mocks.js` file is not in the `jspm_packages/angular/bower-material/` folder.

What is the correct way of unit testing using angular material mocks with JSPM?

**Comment by ThomasBurleson** [comment]
Please note that jspm will install angular-material in the `jspm_packages/github/angular/bower-material` folder:

![screen shot 2015-05-25 at 8 31 29 am](https://cloud.githubusercontent.com/assets/210413/7797923/7d659a54-02b8-11e5-998b-3f9e82266963.png)

> And the `angular-material-mocks.js` is included in that install.

**Comment by jannisg** [comment]
Thanks, had to uninstall then reinstall with JSPM to get the file but there now. :smile: 

@ThomasBurleson: Running JSPM 0.15.6, what is the correct way of actually importing this file into the unit test js file?

I can't really say a way to say `import 'angular-material-mocks;' or anything since there is no explicit path defined for that file.

**Comment by ThomasBurleson** [comment]
Please open an issue on [Material-Start](https://github.com/angular/material-start/issues) and I can provide some documentation on using **JSPM** to unit test application code with `angular-material-mocks.js`
