### ISSUE TITLE
Autocomplete suggestions remain at same position onScroll

### ISSUE THREAD

**Issue by asaharan** [angular/material#2973]
While typing if we scroll position of suggestion remain fixed
See the gap between input box and suggestion box
![screenshot from 2015-05-25 17 41 55](https://cloud.githubusercontent.com/assets/11248242/7797111/680f3582-0305-11e5-94f7-4263c31e2771.png)

**Comment by matthieuh** [comment]
+1

**Comment by krassx** [comment]
Same here. Tried with 0.9.8.

**Comment by cnpal** [comment]
+1

**Comment by Sriram143** [comment]
+1

**Comment by epelc** [comment]
@robertmesserle How does this work if the input isn't visible when it gains focus? For example if you tab to an auto complete while you are scrolled past it. This sounds like it'd lock the view and be very hard to understand for the user.

**Comment by robertmesserle** [comment]
@epelc This is modeled after the way that select components work in Chrome on Mac.  The screen is only locked when the select menu is showing.  The browser *should* move the input into view when the user focuses it, but I'm going to spend some time today trying to break this and see if I can find any edge cases that need to be addressed.  If you find any examples where this breaks, please send a CodePen my way.

**Comment by epelc** [comment]
@robertmesserle Thanks. I was just going off the changelog info I didn't get to test it in my app yet. I'm waiting for a good time to update #2710 so I can get it merged soon. I've been running a fork for several weeks with that pr so I haven't been able to easily update and test the later 0.9.X and 0.10.X releases. I'll let you know if I find anything though.

**Comment by robertmesserle** [comment]
@epelc Interestingly, my description of how the browser would handle it worked in 0.9.8, but when tested against master just now, doesn't seem to move as expected.  Might need to add a delay before locking scrolling to account for the browser's build-in functionality.

**Comment by robertmesserle** [comment]
Confirmed, that fixed it.  Committing to master now. =p
