### ISSUE TITLE
md-card-content padding not applied to sides in IE10

### ISSUE THREAD

**Issue by chr22** [angular/material#2974]
Padding is not being applied to left and right in IE10 in md-card-content, as seen in screenshot below from Angular Material docs.

![capture](https://cloud.githubusercontent.com/assets/3649594/7797552/02c604a6-02ee-11e5-953d-b30b35e500cb.JPG)

**Comment by topherfangio** [comment]
I have worked a bit on this and believe I have a solution. Will update/push code soon.
