### ISSUE TITLE
Setting md-slider max programatically always sets to 100

### ISSUE THREAD

**Issue by x01440** [angular/material#2975]
I'm using md-slider and attempting to include it in a directive template.  I want the max set to a controller value, which can change based on a user triggered event:

`
 <md-slider ng-model="ctrl.pointer" min="0" max="{{ctrl.size}}">
 </md-slider>
`

Max is always 100, regardless of the value of size (usually more than 100)

Here's the HTML that's compiled in the page:
`
<md-slider ng-model="ctrl.pointer" min="0" max="251" class="ng-valid ng-isolate-scope md-default-theme ng-dirty ng-touched" tabindex="0" role="slider" aria-valuemax="100" aria-valuenow="100" aria-valuemin="0" aria-invalid="false"><div class="md-slider-wrapper">        <div class="md-track-container">          <div class="md-track"></div>          <div class="md-track md-track-fill" style="width: 100%;"></div>          <div class="md-track-ticks"></div>        </div>        <div class="md-thumb-container" style="left: 100%;">          <div class="md-thumb"></div>          <div class="md-focus-thumb"></div>          <div class="md-focus-ring"></div>          <div class="md-sign">            <span class="md-thumb-text">100</span>          </div>          <div class="md-disabled-thumb"></div>        </div>      </div></md-slider>
`

**Comment by DaveWM** [comment]
@x01440 is `ctrl.size` null/undefined when the directive is created by any chance? The slider only listens for changes to the `max` attribute if it's value is initially truthy. See this codepen: http://codepen.io/anon/pen/WvoWLY

**Comment by x01440** [comment]
It is null/undefined when the directive is created.  I just tried it when defining the ctrl.size value in the controller constructor and the slider resizes as expected.

Is this intended behavior or is this a bug?

For my purposes, this works.
