### ISSUE TITLE
Upgrading to Angular 2.0

### ISSUE THREAD

**Issue by sanketsahusoft** [angular/material#2978]
Since Angular 2.0 Developers Preview is officially launched. Do you have any roadmap of upgrading to Angular 2.0?

**Comment by ThomasBurleson** [comment]
No.

**Comment by avindra** [comment]
My team is considering adopting this framework. My concern is all the BC between Angular 1.0 and 2.0. Is there any plan to eventually provide an Angular 2.0 compatible release?

**Comment by ThomasBurleson** [comment]
Angular Material will be published with implementations for both Angular
1.x and 2.x..
Our first goal is too release v 1.x... Meanwhile parallel efforts are pro
typing implementations with Angular 2.x.
Angular Material 1.0 has a planned release for this summer 2015. We are not
ready, however, to discuss Angular Material timelines.

**Comment by chrismbeckett** [comment]
Just wondering with rumors of Angular 2 hitting beta soon and the current release pace of Angular Material if there is any update on this status?

**Comment by ThomasBurleson** [comment]
We will be announcing some information at Angular Connect next week.

**Comment by aholbreich** [comment]
So any updates now?
Angular Material is 1.0  and AngularJS 2.0 is beta...

**Comment by AlphaHinex** [comment]
+1

**Comment by zoechi** [comment]
Follow https://github.com/angular/material2
