### ISSUE TITLE
md-button does not respect ng-attr-href

### ISSUE THREAD

**Issue by glebm** [angular/material#2981]
The button checks for whether an (ng-)href attribute `isDefined` and not whether it is present. 

This means the following template:

```html
<md-button ng-attr-href="{{undefined}}"></md-button>
```

compiles to an invalid `<a>` tag without an `href`, instead of a `<button>`.

**Comment by glebm** [comment]
I've added a failing test case above. Looks like it may be necessary to delay element creation until the first run of `attr.$observe('href', callback)`.

**Comment by topherfangio** [comment]
I'm a bit confused. Can you explain why you want it to be a button if the link is invalid? It seems like a better solution would be to use `ng-if` to show/hide the button if the link isn't valid.

I think we need a bit more info (and perhaps a Codepen) before we investigate this further.

**Comment by glebm** [comment]
In Angular it is a standard practice to consider attributes that are `undefined` as if they were not defined (this simplifies controller code significantly).
