### ISSUE TITLE
md-chips: md-require-match has no effect on md-chips behaviour

### ISSUE THREAD

**Issue by smashercosmo** [angular/material#2982]
md-require-match attribute doesn't do anything because it is used in chips controller as "this.$scope.requireMatch", but should be used as "this.requireMatch".

**Comment by Belicosus** [comment]
Also, md-require-match should be used with a true|false parameter:
`md-require-match="true"`

**Comment by jahtalab** [comment]
+1
when this will be resolved?

**Comment by houmark** [comment]
Has become somewhat related with #3833

**Comment by smashercosmo** [comment]
Closed because of 86db4db9fd6e61314c1ce08cbffdffd52eae787f
