### ISSUE TITLE
Text color inheritance from md-theme

### ISSUE THREAD

**Issue by brianfeister** [angular/material#2983]
#1152 is related but I didn't want to piggyback on the wrong thing, we can close if it's better discussed there.  At a high level, it seems strange that doing this in my app's config block

```javascript
  $mdThemingProvider.theme('primary')
    .backgroundPalette('blue', {
      'default': '300'
    })
    .dark();
```

and this in my template

```html
    <md-content layout="row" flex="50" layout-padding="lg">
      <div md-theme="primary">
        <h3 class="md-headline">{{ contentCtrl.selectedNode.name || 'My Content' }}</h3>
      </div>
    </md-content>
```
does not result in light text.  Seems to violate the entire concept of pushing the role of theming to an Angular (read: javascript) service if my config for the theme is now split between my app's `.config()` block and a global CSS style particular to my theme.

This plunkr's text "Color is default body black. Shouldn't this be white too?" illustrates the problem well: http://plnkr.co/edit/FE7q9g?p=preview

**Comment by bitencode** [comment]
Is there a plan for this?  Seems like a big gap in theming.  I've essentially got the same problem - I'm defining a dark "panel" theme that is simply specified as follows. The panel background is dark as expected (putting all the md-content inside a div with md-theme='panelTheme'), but the icons are a dirty light-grey color and the text is charcoal and barely readable).
```
$mdThemingProvider.theme('panelTheme')
  .primaryPalette('blue-grey')
  .backgroundPalette('blue-grey')
  .dark();
```

In fact, it seems all you really need to do to expose the problem is this:
```
$mdThemingProvider.theme('default').dark();
```
And you (or at least I) see my entire site with a medium dark grey background and charcoal text, which is almost unreadable.

**Comment by Gregoirevda** [comment]
If we could at least set it manually like that, it would be great : 
```
$mdThemingProvider.theme('panelTheme')
  .primaryPalette('white')
  .backgroundPalette('indigo')
  .dark();
```

But `white` isn't accepted as primary color. 

It means, if I want a black background on a md-content. Like the example on material.angular website : 
```
<md-content md-theme="docs-dark">
    <div>
      <md-input-container>
        <label>Title</label>
        <input ng-model="user.title">
      </md-input-container>
    </div>
  </md-content>
```

And theme configuration :

**Comment by Gregoirevda** [comment]
In fact there is a solution : 

Create a white palette 

```
$mdThemingProvider.definePalette('white', {
        '50': '#fff',
        '100': '#fff',
        '200': '#fff',
        '300': '#fff',
        '400': '#fff',
        '500': '#fff',
        '600': '#fff',
        '700': '#fff',
        '800': '#fff',
        '900': '#fff',
        'A100': '#fff',
        'A200': '#fff',
        'A400': '#fff',
        'A700': '#fff',
        'contrastDefaultColor': 'light',    // whether, by default, text (contrast)
                                            // on this palette should be dark or light
        'contrastDarkColors': ['50', '100', //hues which contrast should be 'dark' by default
            '200', '300', '400', 'A100'],
        'contrastLightColors': undefined    // could also specify this if default was 'dark'
    });
```

and use it : 

```
.config(function($mdThemingProvider) {
    // Configure a dark theme with primary foreground yellow
    $mdThemingProvider.theme('docs-dark', 'default')
      .primaryPalette('white')
      .dark();
  });
```
