### ISSUE TITLE
Contact Chips Showing Empty Dropdown 

### ISSUE THREAD

**Issue by Sriram143** [angular/material#2984]
Contact Chips is showing empty drop down and not at all closing after a contact for the drop-down.
![contact chips](https://cloud.githubusercontent.com/assets/4466654/7816944/6c7fe46e-039f-11e5-94c3-7d14e5258858.png)

Please See the Marked Area and Broken in Ie 11

**Comment by ramr0m** [comment]
It seems this is the same issue as https://github.com/angular/material/issues/3008

**Comment by qjlee** [comment]
It seems to be fixed in the 0.10.0 release.

**Comment by Sriram143** [comment]
Drop down is not staying but its showing and automatically closing and i think its a glitch.
