### ISSUE TITLE
md-select do not handle multiple keypress like native select element

### ISSUE THREAD

**Issue by jqlio18** [angular/material#2985]
Let's say we have a simple `md-select` element.

    <md-select ng-model="test">
        <md-option ng-value="A1">A1</md-option>
        <md-option ng-value="A2">A2</md-option>
        <md-option ng-value="A3">A3</md-option>
        <md-option ng-value="A4">A4</md-option>
    </md/select>

In native `select` element, if I press "A" two times, it will select "A1" then "A2" and after if I press "A4" fast, it will select "A4". Angular Material does not do it that way, if I press "A" multiple times it will select the first option with the "A" letter same thing for "A4".

It's easy to test it with the demo here : https://material.angularjs.org/latest/#/demo/material.components.select

**Comment by JerrodLong** [comment]
@rschmukler can you review? I think we have a fix. Feedback appreciated. Thanks!

https://github.com/JerrodLong/material/commit/931badd88679735cccc1df116eb6cedfcf39f8d8

**Comment by topherfangio** [comment]
Apologies for the random references/tags; I swapped the last two digits of the issue I was working on when referencing it in my PR :/
