### ISSUE TITLE
mdInput: layout issues with multiple inputs on small screens in IE11

### ISSUE THREAD

**Issue by Sriram143** [angular/material#2986]
The alignment was broken in ie 11 and it looks ugly see the reference screenshot
![alignment broken](https://cloud.githubusercontent.com/assets/4466654/7816998/c12e4f64-039f-11e5-9908-8469433b6fa2.png)

**Comment by Splaktar** [comment]
This only happens on small screens. This demo has `layout layout-sm="column"` but the inputs do not have sufficient height/padding/margin to function properly. The other two demos on the page use a `min-height: 48px;` to keep their layout functional on small screens.

Chrome and Firefox seem to handle this by adding extra spacing which results in a nice layout on mobile. IE doesn't appear to add any such spacing.
