### ISSUE TITLE
md-select inside directive doesn't update selected value in directive Unit Tests

### ISSUE THREAD

**Issue by jmuharsky** [angular/material#2989]
REPRO STEPS
============
1. Create a directive that uses an md-select in the template.
2. Create a unit test that compiles the directive you created in step #1.
3. Modify the model at runtime, scope.$digest() it, and evaluate the contents of the md-select.

CURRENT BEHAVIOR
==================
The <md-select> box remains in "unselected" mode, and any attempts to interrogate its HTML structure show only the placeholder text as the selected text.  Note that this directive works as expected in "production" mode; it only exhibits this behavior in unit tests.

EXPECTED BEHAVIOR
===================
Ideally, md-select would expose a value attribute or something that can be used to easily determine the selected value.  But in general, md-select should update based on bound model changes inside unit tests.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
