### ISSUE TITLE
Ink Ripple color should be synced to correspond element color

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#299]
For tabs, the Ink color should the same InkBar... this synchronization is manually. 
The tabs Ink ripple should auto-detect the inkBar color and self-adjust.

Similarly the other components (lists, buttons, etc) should use ink ripple color-synced to the element text color.
### Questions for UX Team:

InkRipples have hardcoded opacity and color values. Should the inkRipple auto-detect the parent text color when not constrained otherwise. For example tab ripples are constrained to the color of the inkBar. But what about list item, button, and checkbox ripples. 
-  Which colors are used? 
-  What element should be the controlling `coloringElement`?

**Comment by bonatoc** [comment]
I want to customize the color of the tab ripples. 
I need the inkbar color to be black, but the greyed-out ripple it produces is not suitable.
Can I intercept via JS, or override through CSS the tab ripple's color, to customize it?
