### ISSUE TITLE
margin problem when using md-input-container with md-icon and md-label together

### ISSUE THREAD

**Issue by alexpozzani** [angular/material#2991]
This issue can be viewed in the input demo page (https://material.angularjs.org/latest/#/demo/material.components.input).

When the field Email is not focused and is empty, the property margin-top is set to -16px.
But when it receive focus or a value, the margin-top is set to -8px.

It's look like a strange behavior because  it resize the container.

In my case, changing the value of margin-top of the class below (located in line 3889) to -16px solved the problem.

  md-input-container.md-icon-float.md-input-focused, md-input-container.md-icon-float.md-input-has-value {
    margin-top: -16px; }

**Comment by ThomasBurleson** [comment]
That margin-top setting was deliberate; used to keep the spacing between the row fields consistent.

**Comment by alexpozzani** [comment]
I understand, but this problem causes the space between the fields increase or decrease depending on the state of the field.
See this screens of the demo page:
![8px](https://cloud.githubusercontent.com/assets/3027167/7822849/b19f0d70-03ce-11e5-95e3-9e04f673e30e.png)
![16px](https://cloud.githubusercontent.com/assets/3027167/7822894/e7929e60-03ce-11e5-9328-26c7240fc954.png)

**Comment by Sijan117** [comment]
I know this is an old post, but i've also had this problem, recently in making a login dialog, the margin transition was causing all elements below the input to get pushed down. I resorted to manually setting the margin to 0. 

Not sure I follow the reasoning behind having it become -16px, at least no in my case. 

![image](https://cloud.githubusercontent.com/assets/13831460/16155754/29f18974-34b1-11e6-9f74-03f5a8be5d14.png)

**Comment by galibimtiaz** [comment]
I am having the same problem , its taking too much space.
