### ISSUE TITLE
Icon size changed from 24px to 28px.

### ISSUE THREAD

**Issue by mikol** [angular/material#2992]
Starting with 860d1f67db2be427aff149cbd0c13f0f3d39e4ca, as noted in the pull request discussion, the icon size changed from 24px to 28px. It should be 24px, which is the natural size of the SVG icon files.

**Comment by ThomasBurleson** [comment]
Fix per [Material Icon Size](http://www.google.com/design/spec/style/icons.html#icons-system-icons) specs.
