### ISSUE TITLE
Morphable icons for SpeedDial

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#2993]
![Idle - State 1](https://cloud.githubusercontent.com/assets/210413/7821937/c67de11a-03b7-11e5-989b-397af42206e4.png)

![Hover - State 2](https://cloud.githubusercontent.com/assets/210413/7821952/ded980de-03b7-11e5-9cf5-23b5c09c9190.png)

**Comment by ThomasBurleson** [comment]
```html
<md-button md-fab>
  <md-icon state="">
     <md-icon-state name="" md-svg-src="" />
     <md-icon-state name="hover" md-svg-src="" />
  </md-icon>
<md-button>
```

##### Notes: 
1) mdIcon is not interactive since we use `pointer-events:none;`

##### Questions:
1) How to trigger a state change in the icon state set during a mouse hover?
2) How to trigger a state change during mousedowns?

**Comment by epelc** [comment]
I found this the other day it might be helpful. It morphs one svg into another. Take a look at the [demo](http://alexk111.github.io/SVG-Morpheus/).

https://github.com/alexk111/SVG-Morpheus

**Comment by ThomasBurleson** [comment]
@epelc - yes, that resource was in our list of research items.

**Comment by marcysutton** [comment]
Keep in mind the button label will have to update along with the icon, so that a user knows what the button does at all times.

**Comment by kuhnroyal** [comment]
At the moment I am using an ungly modified mdIcon directive (at [iconDirective.js#L185](https://github.com/angular/material/blob/master/src/components/icon/iconDirective.js#L185)) which uses SVGMorpheus.
Requires `md-morph` attribute on `md-icon`.

```javascript
    var currentSvgIcon;
    if (attrName) {
      // Use either pre-configured SVG or URL source, respectively.
      attr.$observe(attrName, function (attrVal) {
        element.empty();
        if (attrVal) {
          if (angular.isDefined(attr.mdMorph)) {
            if (currentSvgIcon) {
              var old = currentSvgIcon;
              var oldIcon = $mdIcon(old);
              var newIcon = $mdIcon(attrVal);
              $q.all([newIcon, oldIcon]).then(function (icons) {
                icons[0].firstChild.style.display = 'none';
                icons[0].firstChild.id = attrVal;
                icons[1].firstChild.style.display = 'none';
                icons[1].firstChild.id = old;
                icons[0].appendChild(icons[1].firstChild);
                element.append(icons[0]);
                new SVGMorpheus(element.children()[0]).to(attrVal, JSON.parse(attr.options || null)); // jshint ignore:line
              });
            } else {
              $mdIcon(attrVal).then(function (svg) {
                element.append(svg);
              });
            }
            currentSvgIcon = attrVal;
          } else {
            $mdIcon(attrVal).then(function (svg) {
              element.append(svg);
            });
          }
        }
      });
    }
```

**Comment by noamamit92** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
