### ISSUE TITLE
Click on md-list-item with md-checkbox in

### ISSUE THREAD

**Issue by fndmiranda** [angular/material#2997]
How do I md-checkbox in a md-list-item is not checked when you click the md-list-item?
md-checkbox stay checked only when you click on it.

**Comment by rgolea** [comment]
You need to specify a primary action for the mdListItem and define a different model for the mdCheckbox
```
<md-list-item ng-click="doSomething()">
    <p> Hello world!</p>
    <md-checkbox class="md-secondary" ng-model="something.else"></md-checkbox>
  </md-list-item>
```

**Comment by ThomasBurleson** [comment]
The documentation needs more details.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (531/500 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:33917 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avscB-000L5y-Dn
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:47 -0500
Date: Thu, 28 Apr 2016 13:32:14 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875534;
	bh=yWHYypQVS16cX+SyJm1UiPdJ8bwiQ1OkXkAhWPT9GSo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=oESDKr8guoPuYqEjxHiVC7P+8vviJknBNtnAH/4Ek3LPxt0hmB78qqyXx2trReMRd
	 FS0JUpuz8o4GkIxOLRhR2MxxYKGBnE3P7NAvKz1WYFPkj+6JjGz0S4Fvq9O+/JLgon
	 xhnSPjikT+AZJtODVR+NUgit7zLlf/6pqk8aCK4A=
