### ISSUE TITLE
md-list performance with/without ng-click

### ISSUE THREAD

**Issue by lothargrieb** [angular/material#2998]
I created a list with 240 entries and text search filtering. Without attaching a `ng-click` handler the component is very slow! After adding the `ng-click`, the performance is much better again. There must be some difference in the list role mode. (Version 0.9.4)

```html
<md-list>
  <md-list-item class="md-2-line" ng-repeat="c in $data.countries | filter:{search:searchText} track by c.index" ng-click="$data.select(c)">
    <div class="md-list-item-text">
      <h3>{{::c.id}}</h3>
      <h4>{{::c.code}} / {{::c.iso3}} / {{::c.iso3166}}</h4>
    </div>
  </md-list-item>
</md-list>
```

**Comment by ThomasBurleson** [comment]
@lothargrieb - This is very interesting. 

*  Did you see this on Mobile or Desktop?
*  OS ?
*  Browser and Version ?
*  Do you have a demo to easily reproduce this (just in case the above snippet is not the issue) ?

**Comment by mhchen** [comment]
@lothargrieb are you still seeing this issue? If so, could you please provide a demo illustrating it? I attempted to reproduce the issue here: http://codepen.io/anon/pen/aOgNVb based on the markup you provided but the performance seems to be okay.

**Comment by jelbourn** [comment]
Closing as "Cannot reproduce" for now. Please re-open if you have more info.
