### ISSUE TITLE
backdrop bug with $state.go (ui-router)

### ISSUE THREAD

**Issue by CanKattwinkel** [angular/material#2999]
**sidenav** > **md-list-item** with a **ng-click** action which calls a **$state.go('foo')** works well until you re-navigate to a state. Already visited States will be blocked by backdrop.

**Comment by mxab** [comment]
I have issue with ui-sref="foo" as well (1.4.3 / 0.10.1-rc5)

**Comment by mxab** [comment]
actually it seems that it does already occur when I change the state once, does not need to be an already visited state

**Comment by mxab** [comment]
Ok I managed to workaround this issue, I cannot say what exactly I did but I had an ui-view on the sidenav and also some ng-hide stuff on it, after I removed this it seems to work again

**Comment by ThomasBurleson** [comment]
Navigation may trigger $destroy events for ngMaterial components. SHA 77a34bd8f122814527159d08536d5776b314f527 fixes this for interim elements.
