### ISSUE TITLE
Add md-tab-focus directive

### ISSUE THREAD

**Issue by websirnik** [angular/material#3001]
`$mdTabFocus` would provide a way to specify the focused element when user selects a tab.
Similar behaviour to [`$mdSidenavFocus`](https://material.angularjs.org/latest/#/api/material.components.sidenav/directive/mdSidenavFocus).

**Comment by marcysutton** [comment]
Can you provide more of a use case? The tab control is not similar to sidenav, in that focus stays on the tab controls when you interact. The controls make up one tab stop as a whole (using arrows/space to activate), and their associated content panels are not focusable by default. There is no focus management in the tabs pattern.

**Comment by websirnik** [comment]
I see your reasoning.
I have a couple elements that would benefit from this directive.

---
![2015-05-28 21_40_27](https://cloud.githubusercontent.com/assets/282871/7870580/3ed1a37e-0582-11e5-8516-e34376c64bb4.gif)
---
![2015-05-28 21_44_07](https://cloud.githubusercontent.com/assets/282871/7870657/b21ff3ee-0582-11e5-8ac9-235cf8424259.gif)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (525/500 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:10698)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avscA-000L51-5U
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:46 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=eY6i5WbmW+I9hTc+XD10wjNIzyU=; b=JnJYxtxE65Q22NLu
	UhzIVMXl1NyNoxZSaXb+PsbJhvgj8jOoQ4kP5G1UvIMQdC+CoGdWmDJymMBRXyxZ
	ZwVWuikw2EywFflrnWT8kGvFZWsRCoSv9rUMl5dJVWu0HgWAErg125s5DYrzo9Jj
	fQLCkJPJTcZ/M09MO164VkdOJyA=
Received: by filter0530p1mdw1.sendgrid.net with SMTP id filter0530p1mdw1.20439.572273501A
        2016-04-28 20:32:16.800962882 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id QxmE8OiqSOCffYMeOS4wjQ
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:16.946 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:16 -0700

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (617/500 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:54167 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdJ-000Lkc-Oo
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:57 -0500
Date: Thu, 28 Apr 2016 13:32:42 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875562;
	bh=8lAe9X3EuwfeKRxAT5j5Y5RAVP5OiIorV4X8AmTWcIA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Bq3I640geq30UcJgSJLDmkHioADRugQGCAv9tQw7yIVxSq27jOMiGDwVXlHQP20Dm
	 Wy7uLl9+zzPWLSa+LLlsnV+C3oGIBPrVPgsScW6nPEljuMgvo8Xe8qNPwhlWgEptvS
	 SccnGYQjMw3+Tj1XL/sn1EY60hmEM3x0KZmbnBmo=
