### ISSUE TITLE
md-sidenav-right locked open ?

### ISSUE THREAD

**Issue by warpdesign** [angular/material#3002]
I'm trying to have a sidenav-right that stays opened. I took the example found here: https://material.angularjs.org/latest/#/demo/material.components.sidenav

The problem is that if I add the attribute md-is-locked-open="$mdMedia('gt-md')" to my md-sidenav-right element, it is then left-aligned. Looking at the CSS, I don't see why, as it has left: 100%.

Is it possible to have a right navbar that is locked open ?

**Comment by mckenzielong** [comment]
Seems to work fine on chrome. Example: http://codepen.io/mckenzielong/pen/yNVGWm

**Comment by warpdesign** [comment]
Seems like there was something wrong with my CSS.

**Comment by jonathanwoahn** [comment]
@warpdesign Were you able to figure this one out? I'm having the same issue

**Comment by kanesee** [comment]
I had the issue. For me, the fix was simply moving the <md-sidenav> below my main content if I wanted it to lock on the right

**Comment by peterrakmanyi** [comment]
@ThomasBurleson  @warpdesign @jonathanwoahn The locked-open md-sidenavs have `position:static;`, not absolute, so their position  within the containing element matters (being first/last child that is visible). An md-sidenav-left should be the first-child and and md-sidenav-right the last-child to make the layout work.
Example: https://codepen.io/anon/pen/MvQOZP
