### ISSUE TITLE
$mdDialog on IE 11 - scroll bars disappear

### ISSUE THREAD

**Issue by JDGoldman** [angular/material#3005]
On IE 11, the scroll bars disappear on the Dialog control.  See screen shot below.  This is related to, but different from, issue  https://github.com/angular/material/issues/1547

![materialdialogscreenshot](https://cloud.githubusercontent.com/assets/5783708/7838893/0cb5ebee-0455-11e5-847c-e4d8ac16fa0b.jpg)

**Comment by marcysutton** [comment]
I can confirm dialogs in IE10/IE11 still have flexbox issues.

**Comment by chrisguerrero** [comment]
+1

**Comment by gkohen** [comment]
@marcysutton can you elaborate on these issues and let the community know if there will be some sort of a polyfill to overcome it?

**Comment by naomiblack** [comment]
@gkohen we're working on a number of IE11 issues that don't yet have a formal resolution. This is an area where PRs are especially welcome, as the current core team is less familiar with issues on IE than we are with FF/Chrome/Safari. 

(As a side note, Marcy is starting a new full-time role on another project -- she'll still be commenting, but won't be owning issues in the 1.0 release.)

**Comment by jenniferjirka** [comment]
Following.  I hit this problem as well.
