### ISSUE TITLE
md-autocomplete: IE11 doesn't close div after "ESC" or "BACKSPACE"

### ISSUE THREAD

**Issue by ramr0m** [angular/material#3008]
Like issue: https://github.com/angular/material/issues/2188 IE11 acts something different with md-autocomplete.
In this case when you hit "ESC" or remove text from input by typing "BACKSPACE".

first open https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete in IE11 and Chrome
Now the following paths can be used to reproduce. 
1. Press "ESC" while cursor is active in input marked with "What is your favorite US state?". IE11 shows a empty div that doesn't dissapear. Chrome acts like expected.
-or-
2. Type character "d" in active input marked with "What is your favorite US state?". Press "BACKSPACE" and click somewhere next to input. Behaviour of IE11 and Chrome are described in 1.

Possible cause: style attributes min-height / max-height / min-width are used in "angular-material.min.js" v0.9.4 and below. I don't know for sure which of these attributes are supported on what browser type and version.
My local modified version where I removed these attributes (not fully tested) does show the expected behaviour in IE11 as in Chrome. It doesn't 'fix' issue  https://github.com/angular/material/issues/2188

**Comment by ramr0m** [comment]
Issue is closed, but this behaviour still exists in release 0.9.8-RC1 !

**Comment by Sriram143** [comment]
![image](https://cloud.githubusercontent.com/assets/4466654/8071465/3580dbe6-0ed8-11e5-9919-cca05462330a.png)


Still not fixed. please look into this

**Comment by robertmesserle** [comment]
@Sriram143 I think you are replying to the wrong issue.  This is separate from your issue #2984 - that one is still open.

**Comment by Sriram143** [comment]
thanks got it @robertmesserle
