### ISSUE TITLE
md-content-overflow property should be set if md-dialog-content grows to overflow

### ISSUE THREAD

**Issue by asans** [angular/material#3009]
Currently, md-dialog adds the md-content-overflow class during the initial phase when dialog is created.

If, for example, we add dynamic content (ie. textarea input) that expands the md-dialog-content pane, this resizing is not detected and md-dialog does not add md-content-overflow class.  

Although this is more of an edge case, but it sure would be nice that  the md-content-overflow is added when this is detected.  This allows the border lines to be shown for md-actions and also for headers.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by peffreycollins** [comment]
@asans I am hitting this edge case now.  Were you able to work around this?
