### ISSUE TITLE
Issues triggering ink ripples on Chromebook Pixel

### ISSUE THREAD

**Issue by meaplet** [angular/material#301]
I'm seeing issues with ink ripples on my Chromebook Pixel, which is currently up-to-date at v37.0.2062.120

Ink ripples aren't triggering all from pointer events. They are also not triggering from touch events too close to the edge of the element. This is particularly notable on checkboxes and radio buttons, where I need to touch the center of the element to trigger an ink ripple.

Thanks!

**Comment by ajoslin** [comment]
Fixed in master.
