### ISSUE TITLE
md-subheader fills width of viewport when inside md-content

### ISSUE THREAD

**Issue by rwestonbutler** [angular/material#3010]
The title pretty much explains it. I have two md-contents on a page, one flex 33 and one flex 66. I expect the md-subheader to be contained within it's parent div. You can observe in this plunkr: http://plnkr.co/edit/HbKw4zJQhFzbo6Aa7qYn?p=preview

**Comment by viztastic** [comment]
I can confirm this issue too. Also the quirk below, it seems to pop out unusually (in addition to what @rwestonbutler described:

![quirk](https://cloud.githubusercontent.com/assets/8556736/8099715/97b8255e-1044-11e5-9ab8-c996d603c084.png)

Implementation below:

'''  <md-section flex class="demo-container">
      
            <md-toolbar class="demo-toolbar">
          <div class="md-toolbar-tools">
            <h3>
              <span>My Tasks</span>
            </h3>
          </div>
      </md-toolbar>
      
      <md-content style="height:300px">
        <md-section>
            <md-subheader class="md-primary">Need Marking</md-subheader>
        
              <md-list>
        
              <md-list-item class="md-3-line" ng-repeat="item in todos">
                <md-icon md-svg-icon="{{item.ico}}" alt="{{item.who}}" class="md-avatar">
                </md-icon>
                <div class="md-list-item-text">
                  <h3>{{item.title}}</h3>
                  <h4>{{item.publisher}}</h4>
                  <p>
                    {{item.description}}
                  </p>
                </div>
                <md-divider inset=""></md-divider>
              </md-list-item>
        
            </md-list>
      
        </md-section>
        
        
                <md-section>
            <md-subheader class="md-primary">Tests to go</md-subheader>
        
              <md-list>
        
              <md-list-item class="md-3-line" ng-repeat="item in todos">
                <md-icon md-svg-icon="{{item.ico}}" alt="{{item.who}}" class="md-avatar">
                </md-icon>
                <div class="md-list-item-text">
                  <h3>{{item.title}}</h3>
                  <h4>{{item.publisher}}</h4>
                  <p>
                    {{item.description}}
                  </p>
                </div>
                <md-divider inset=""></md-divider>
              </md-list-item>
        
            </md-list>
      
        </md-section>
        
      </md-content>
      
    </md-section>
    


    <md-section flex class="demo-container">
      
      <md-toolbar class="demo-toolbar">
          <div class="md-toolbar-tools">
            <h3>
              <span>My Tasks</span>
            </h3>
          </div>
      </md-toolbar>
      
      <md-content style="height:300px">
        
        <md-section>
            <md-subheader class="md-primary">Teaching</md-subheader>
        
              <md-list>
        
              <md-list-item class="md-3-line" ng-repeat="item in todos">
                <md-icon md-svg-icon="{{item.ico}}" alt="{{item.who}}" class="md-avatar">
                </md-icon>
                <div class="md-list-item-text">
                  <h3>{{item.title}}</h3>
                  <h4>{{item.publisher}}</h4>
                  <p>
                    {{item.description}}
                  </p>
                </div>
                <md-divider inset=""></md-divider>
              </md-list-item>
        
            </md-list>
      
        </md-section>
  
      
        <md-section>
            <md-subheader class="md-primary">Learning</md-subheader>
        
              <md-list>
        
              <md-list-item class="md-3-line" ng-repeat="item in todos">
                <md-icon md-svg-icon="{{item.ico}}" alt="{{item.who}}" class="md-avatar">
                </md-icon>
                <div class="md-list-item-text">
                  <h3>{{item.title}}</h3>
                  <h4>{{item.publisher}}</h4>
                  <p>
                    {{item.description}}
                  </p>
                </div>
                <md-divider inset=""></md-divider>
              </md-list-item>
        
            </md-list>
      
        </md-section>
      
      </md-content>
      
    </md-section>
'''

**Comment by ricardobfa** [comment]
+1

**Comment by joshdmiller** [comment]
By design, a sticky component like mdSubheader will be placed with absolute positioning *outside* the closest parent mdContent. The behaviour you're describing is counter-intuitive and confusing, but (I believe) to spec.

The solution is to wrap the mdContent in a relatively positioned container.

**Comment by TitForTat** [comment]
To me it doesn't matter if I position:-relative all the way up to the html tag.. still behaves like that on chrome..

**Comment by topherfangio** [comment]
@joshdmiller is correct; simply surrounding your `<md-content>` with a `<div style="position: relative">` will fix this issue. With such a simple workaround, I'm not sure we can provide a better/cleaner solution. @ThomasBurleson can you chime in?

@viztastic Can you elaborate on your phrase "pop out unusually" and perhaps provide a demo? :-)

**Comment by topherfangio** [comment]
I just pushed a PR  (#4276) which I think might fix this. I will update once it hits master and see if you can retest.

**Comment by topherfangio** [comment]
@rwestonbutler @viztastic The original plunkr now seems to be working correctly (it loads material's master branch from bower).

Can one of you two please confirm and we will close?

**Comment by ThomasBurleson** [comment]
LGTM - http://plnkr.co/edit/1hpQBs9xQPQNjjpE1iYo?p=preview

**Comment by rwestonbutler** [comment]
looks good. Thanks guys!
