### ISSUE TITLE
mdSelect: not displaying the initial value of ngModel when it's an object

### ISSUE THREAD

**Issue by VictorRicha** [angular/material#3012]
Hi,

I'm having a problem with mdSelect + ngRepeat with objects in the value. 
When i initialize the ngModel value while loading the page (like i would if i was, for example, editing some object i get from the server). 
The mdSelect doesn't match my object and have it selected as it does when i use something as simple as an array of strings.

example:
http://codepen.io/VictorRicha/pen/BNQezv

**Comment by JerrodLong** [comment]
try <md-option ng-repeat="val in vals" ng-value="val.value">{{val.desc}}</md-option>

**Comment by JerrodLong** [comment]
try ng-value="val.value" on the md-option.

**Comment by VictorRicha** [comment]
@JerrodLong Didnt work for me. Also tried your way using track by val.value in the ngRepeat with no success :disappointed:

**Comment by VictorRicha** [comment]
Problem solved! 
Turns out i had to use ng-model-options="{trackBy: 'someVal.value'}"
It would be nice to see this in the documentation

**Comment by VictorRicha** [comment]
Problem solved! 
Turns out i had to use ng-model-options="{trackBy: 'someVal.value'}"
It would be nice to see this in the documentation

**Comment by joehoeller** [comment]
Or just do this: ng-disabled="$index === 1"

**Comment by daciot** [comment]
Hi @VictorRicha, i tried to use  ng-model-options="{trackBy: 'someVal.value'}" in your example http://codepen.io/VictorRicha/pen/BNQezv, but doens't work. Can you help me?

**Comment by daciot** [comment]
@VictorRicha when I use your example, the md-select dont display any option. In my application I am the same problem. :(
