### ISSUE TITLE
GridList ordering explained

### ISSUE THREAD

**Issue by matthiasg** [angular/material#3013]
When looking at the 'Basic Usage' demo on 
https://material.angularjs.org/latest/#/demo/material.components.gridList i do not quite understand with element#6 is not top aligned. Also when changing the rowspan to 1 i would have expected it to either move under element#4 or element#4 to move under 2 and 3 and 5 and 6 next to those...

Is there an explanation somewhere what the general layout rules are supposed to be ?

I did find https://github.com/angular/material/pull/2568 which seems to have impacted that but i am already looking at 0.9.4 on the angular page.

**Comment by shyndman** [comment]
Sure. It's pretty simple. The algo looks left to right, row by row, until it finds enough horizontal space to fit a tile, then it puts it there. My intention was for people to pick tile span combinations that would always produce complete grids.

The algorithm could be changed to fill gaps, but the current implementation has the advantage of being simple and lightweight -- very little record keeping.

That demo could use some work though. It does seem a little odd to have that gap.

**Comment by matthiasg** [comment]
Thanks for the info.. that explains the gap for 6 of course since its already in row 2 when it tries to place that... of course that kind of algorithm will  make it hard to do drag and drop, unless you provided a way to override positions for certain boxes (like 1 up etc).

but the example should be fixed, since its a weird start :)
