### ISSUE TITLE
inconsistent space between md-input-container when using md-icon and md-label together

### ISSUE THREAD

**Issue by alexpozzani** [angular/material#3014]
The space between some md-input-container become inconsistent when a input receive focus in these conditions.
This issue can be viewed in the input demo page.

Without focus
![8px](https://cloud.githubusercontent.com/assets/3027167/7862064/1682818e-052a-11e5-9be5-60b1fec24cbb.png)

Focused
![16px](https://cloud.githubusercontent.com/assets/3027167/7862066/169978ee-052a-11e5-9686-10e7eefc8f1e.png)

**Comment by rictorres** [comment]
I can also confirm this one.

**Comment by alexpozzani** [comment]
Hi, this issue is solved in 1.0.0-rc4!

Nice job!
