### ISSUE TITLE
Compiling material directives on the fly: md-input-has-value attribute not set

### ISSUE THREAD

**Issue by warpdesign** [angular/material#3017]
I'm trying to dynamically compile material directives. It works, but for some reason, <md-input-container> doesn't get the `md-input-has-value` attribute set, even though my inputs have a value set.

Maybe I'm doing something wrong ?

Here is an example:

    $('<div id="foo"><md-input-container><label for="myInput">Plop</label><input id="myInput" name="myInput" value="48" type="text"/></md-input-container></div>').appendTo('body');

    scope = $rootScope.$new();
    $compile($('#foo').contents())(scope);

My input correctly gets the material styles, but since the `md-input-has-value attribute` isn't set, the value isn't displayed unless the input gets the focus.

Maybe I am missing something ?

**Comment by warpdesign** [comment]
I'll answer to my own question: it seems it will only work if the input valued is binded to some value (ie: has ng-model set). Is it intended ?

**Comment by mmiszy** [comment]
I think this is a bug. :+1:

**Comment by Splaktar** [comment]
@warpdesign This looks very similar to #2162 which effects both IE and Firefox. Which browser were you seeing this problem in? Does #3582 fix it for you?

**Comment by Anthropic** [comment]
I'm adding an md-input-container with an input inside, then dynamically adding the ng-model reference and while the data then works I've had to add the following to get it to detect the init state:
```javascript
ng-class="{'md-input-has-value': model['{{form.key.join('\'][\'')}}']}"
```
