### ISSUE TITLE
mdSelect causes page to jump to top in firefox(again and again!)

### ISSUE THREAD

**Issue by butaixianran** [angular/material#3020]
mdSelect causes page to jump to top in firefox:
Check this on firefox:
http://codepen.io/butaixianran/pen/waWRmN
Click the mdSelect at the bottom, you will jump back to the top, please fix this issue, it is a big thing to the users of a website.

FYI:
This is an old issue as #1648 It has been fixed in 0.9.0. Then, some how it comes back in 0.9.4 as #2903.  

Now, this issue is stll there! Even with the latest angular material.

**Comment by robertmesserle** [comment]
Fixed by https://github.com/angular/material/commit/7b8efe21244e32613358bb6b22d19df5513a573f

**Comment by butaixianran** [comment]
Hi, this fix doesn't work very well. If you click an item of the md-selection, it will be fine. 

But, if you open the md-selection, then don't select any item, just click somewhere else, it will jump back to top again!

**Comment by xtiggerk** [comment]
Hi, i confirm this issues on Firefox, when you open a md-select and click an item in the list, it jumps like 400px up. If you open a md-select, and click outside to close it, it jumps up to top. :/

**Comment by rschmukler** [comment]
Please see #3479
