### ISSUE TITLE
md-divider not render properlly

### ISSUE THREAD

**Issue by sweetim** [angular/material#3021]
Updated to v0.9.6 and my list view item using the divider is not render properly

<md-divider></md-divider>

All my dividers are render to a fixed position

**Comment by atanis** [comment]
I have this issue as well for dividers within <md-list-item> (may have to do with this md-no-proxy class) - it started v0.9.5 and exists through 0.9.8rc1

**Comment by kimmoah** [comment]
I am having the same problem. The position of the divider is fixed as the window height.
I can see it when scroll down.

**Comment by tolemac** [comment]
+1 the same here

**Comment by ultamatt** [comment]
I'm also having this issue.

**Comment by vectorderivative** [comment]
Wrap your list on a div container and use the md-divider outside the md-list-item as tolemac pointed out.

```
<md-list>
        <div ng-repeat="filter in listFilters.filters">
            <md-list-item class="md-3-line" layout-margin>
                <md-button class="md-fab md-mini" aria-label="Edit">
                    <md-icon md-font-library="material-icons">mode_edit</md-icon>
                </md-button>
                <div class="md-list-item-text" layout="column">
                    {{filter.content}}
                </div>
            </md-list-item>
            <md-divider></md-divider>
        </div>
</md-list>
```
There's a css rule making md-list-item md-divider absolute positioned.

**Comment by Yimiprod** [comment]
Same with version 0.10.1

**Comment by topherfangio** [comment]
Is this still an issue in 0.11? If so, can someone please provide a [Codepen](http://codepen.io) which demonstrates the issue so we can debug it further?

**Comment by tsenying** [comment]
Adding the md-button directive inside md-list-item will reproduce the problem:

    http://codepen.io/tsenying/pen/meEXKw
