### ISSUE TITLE
Bug: textarea scroll up while typing when its height bigger than the screen's height

### ISSUE THREAD

**Issue by kuyseng** [angular/material#3024]
Let try typing more at the end of text in the textarea, then it always scroll up.
http://codepen.io/kuyseng/pen/aOpmRO?editors=101

I have checked the source code. it happens with `node.style.height = "auto";` but that code is used to make the textarea's height smaller depend on its text.
https://github.com/angular/material/blob/master/src/components/input/input.js#L254

**Comment by fabito** [comment]
:+1:

**Comment by orange-buffalo** [comment]
:+1: , also facing this issue and looking forward to official fix

**Comment by kamarouski** [comment]
:+1: have the same issue in my project as well. Looking forward to the official fix.

**Comment by EladBezalel** [comment]
@kuyseng it seems to be fixed in HEAD, closing for now. if it's still happening please write here and i will reopen this issue.
