### ISSUE TITLE
md-toolbar md-scroll-shrink breaks with minor changes

### ISSUE THREAD

**Issue by loljoho** [angular/material#3025]
The [demo](https://material.angularjs.org/0.9.6/#/demo/material.components.toolbar) for `md-toolbar` with `md-scroll-shrink` in v0.9.6 seems to work fine on the page as well as the CodePen.

However, either of the following changes will break the functionality:
 1. Removing, or otherwise changing the `height: 600px;` on the `style` attribute for the subsequent `<md-content>`
 2. Removing, or replacing the `<md-list>` child within the aforementioned `<md-content>` with anything

From what it looks like, minor changes to the `<md-content>` following the `md-scroll-shrink`-designed toolbar cause issues, even in when adhering to the [directive documentation](https://material.angularjs.org/0.9.6/#/api/material.components.toolbar/directive/mdToolbar).

Kindly let me know if I should provide any additional details, or I have made some silly mistake.  Cheers :)

**Comment by loljoho** [comment]
CodePen links for clarification:

 * [Unchanged from Documentation Demo](http://codepen.io/anon/pen/XbpNrb)
 * [Removed `style` attribute from `md-content`](http://codepen.io/anon/pen/LVxbPx)

**Comment by loljoho** [comment]
Although I seem to have noticed that, while attempting to replicate the replacement of the `<md-list>`, an `<md-card>` didn't break the functionality.

[CodePen](http://codepen.io/anon/pen/OVWbLE)

**Comment by NickBolles** [comment]
have you tried following this example from #3424? Your problem sounds similar. 
It looks like you just have to add the `layout` attribute to the body tag and `layout-fill` to the `md-content`

**Comment by ThomasBurleson** [comment]
Not an issue with proper use of Layout.
