### ISSUE TITLE
Select multiple lines

### ISSUE THREAD

**Issue by gpopovic** [angular/material#3026]
It's possible to write multiple lines into md-option and that works like a charm, but the problem is, all spans get combined and written when option is selected.

Is it possible to somehow force select to write short version only?

Example:

`<md-option>
<span>TITLE</span><br>
<span>Details</span>
</md-option>`

This works inside a list, but when selected..it will output "TITLE Details" instead of Title only

**Comment by marcysutton** [comment]
You can currently use custom templates with mdAutocomplete, but not mdSelect. See #2835.
