### ISSUE TITLE
feat(tab): support applying classes to md-tab and reflecting them on the md-tab-item

### ISSUE THREAD

**Issue by evamichalcak** [angular/material#3028]
I need some tabs to be a different color than the rest. I assigned a class to the md-tab element in my markup, but it doesn't get assigned to the final md-tab-item and the styles don't apply to the tab.
Shouldn't that class get passed on?

**Comment by tony0918** [comment]
I am facing the same problem. Although there is a unique ID attribute on every `md-tab-content`, developers still lose the control on these elements. Is there a way to add custom class values to `md-tab-content` tag?

**Comment by robertmesserle** [comment]
@evamichalcak @tony0918 The way I was thinking of solving this issue would be that when using the `md-tab-label` and `md-tab-body` tags, all attributes would be transferred to their respective `md-tab-item` and `md-tab-content` tags.  Thoughts?

**Comment by tony0918** [comment]
@robertmesserle That's perfect. But Also from version 0.9.8, there is an additional div which wrap up tab contents. It's hard to add custom class to that div tag as well. Do you have any plan to that?
Thanks.

**Comment by robertmesserle** [comment]
@tony0918 This extra div MAY be temporary - I'd like to remove it, but the alternative solution is much uglier and would take a bit more time to fine tune.  In the meantime, while you can't add a custom class to that DIV, is there any reason that you explicitly need a class on that DIV and not on the parent element?

**Comment by tony0918** [comment]
@robertmesserle That's wonderful. In order to make the content in the tab content to take the rest space of the container, I need to add `flex` and `layout` attributes on that element. It's my requirement.

**Comment by robertmesserle** [comment]
@tony0918 Ah, okay, that makes sense.

**Comment by osuritz** [comment]
Where are we with this? We'd like to write web driver tests for our pages and not being able to set a class or an ID on a tab that we "click" on makes things very difficult and/or fragile (e.g. having to write a selector that includes the child offset of the tab).

**Comment by nicbon** [comment]
Much related to #2254. The solution proposed here by @robertmesserle would close both issues.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by mcblum** [comment]
@osuritz did you ever figure out a solution for this? We're in exactly the same spot. Trying to write Protractor tests and can't assign a class or ID.

**Comment by osuritz** [comment]
I've moved on to a different project since, but I think at the time we
ended up using an offset number in the CSS selector.

**Comment by oemmes** [comment]
I once wrote a directive which watches the class names of the original ``<md-tab>`` element and applies it to the actual item and dummy:
[md-tab-class](https://gist.github.com/oemmes/133d266d8abe45f8d5296abcf6c1b56d)

Maybe this helps someone.

Usage example:
```html
<md-tabs>
	<md-tab
		ng-repeat="group in ctrl.groups"
		md-active="ctrl.activeGroup === group"
		ng-class="{
			undone: group.$undone,
			valid: group.$valid,
			invalid: !group.$valid,
			active: ctrl.activeGroup === group
		}"
		md-tab-class
	>
		<md-tab-label>{{group.title}}</md-tab-label>
	</md-tab>
</md-tabs>
```

**Comment by creativehamlet** [comment]
Thanks @oemmes this directive works like a charm.

**Comment by Splaktar** [comment]
Re-opening this as it effects testability of AngularJS Material applications which is important. We would welcome a PR that resolved this.

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material/commit/aa30ada04bbd04c2e5fec99dd0b9357098d291db.

**Comment by izerozlu** [comment]
@Splaktar Documentation needs update about this feature.

**Comment by Splaktar** [comment]
I opened https://github.com/angular/material/issues/11451 to track this docs deployment issue.

**Comment by Splaktar** [comment]
@izerozlu thanks for the heads up. The [mdTab docs](https://material.angularjs.org/HEAD/api/directive/mdTab) have been updated.
