### ISSUE TITLE
How to force a reflow / redraw of md-grid?

### ISSUE THREAD

**Issue by ArthurianX** [angular/material#3029]
I have a dynamical grid and I am trying to change some settings on the fly, but settings like gutter won't trigger a reflow/redraw/recompile (like adding or removing and element). 

How could I trigger a redraw ?

Sorry for posting here but I have found no google group for angular material :(

**Comment by epelc** [comment]
From the docs no methods seem to be exposed to do this. I think it'd be better for the gutter options to just support watching for changes instead of having to manually call a reflow function.

The group is [here](https://groups.google.com/forum/#!forum/ngmaterial)
