### ISSUE TITLE
Animated Pages

### ISSUE THREAD

**Issue by ntenisOT** [angular/material#303]
Hello and thanks for this awesome repo,

I would like to ask if there are any examples related to **Polymer's animated pages** ( http://www.polymer-project.org/docs/elements/core-elements.html#core-animated-pages ) and how we can build a similar demo using the resources provided in this repo.

I would like to achieve **http://www.polymer-project.org/components/core-animated-pages/demos/music.html** but I don't want to use Polymer since I would like to use Angular.

Can you please provide me some directions in order to start? I will also try to contribute the demo back since I finish it as I think it will be advantageous for a lot of people.

**Comment by danzatt** [comment]
Are there any news ?

**Comment by ThomasBurleson** [comment]
The Animation team is working on features to support complex choreographies and meaningful transitions. Here is another example of some of the UX we want to support:  [Meaningful Transitions for Visual Continuity](http://www.google.com/design/spec/animation/meaningful-transitions.html#meaningful-transitions-visual-continuity).

> We do not expect to announce anything on this until late Q1 2015.

**Comment by brianfeister** [comment]
@ThomasBurleson I know this is not really available for public preview yet, but in terms of architecture, I'm building with Angular Material and wanted to know if the feature we're discussing here (Animated State Transitions) would support arbitrary UI routing?  In other words, should I just build separate pages without transitions now and then later be able to add transitions via a not-yet-final API your team is working on?
