### ISSUE TITLE
md-subheader in container with flex display is very laggy

### ISSUE THREAD

**Issue by karolkochan** [angular/material#3030]
With 1.4.0 update, scrolling container with md-subheader placed inside container with display: flex is very laggy. 

http://codepen.io/anon/pen/BNppyB

Windows 8.1 + Chrome 43.0.2357.81

**Comment by jgoux** [comment]
I noticed the same problem, I tried to use the bindonce syntax everywhere at first to solve this but it made no difference.
+1

**Comment by gustavohenke** [comment]
:+1:, I have the same setup - Chrome with Windows 8. Firefox is fine.

**Comment by tommy8694** [comment]
+1
firefox and safari work normally in my mac.
chrome is very laggy

**Comment by Frank3K** [comment]
+1

**Comment by ThomasBurleson** [comment]
Angular ngAnimate 1.4.3 and 1.4.4 both had some issues with `requestAnimationFrame` buffering.  Please retry with the latest Angular Material and Angular 1.4.5.

**Comment by Frank3K** [comment]
Will try soon, currently using the 1.3.x branch for AngularJS.

**Comment by ThomasBurleson** [comment]
This should be fixed with Layout fixes released in v0.11.0-rc2.
