### ISSUE TITLE
UI Issue in Angular Material

### ISSUE THREAD

**Issue by zeeshanjan82** [angular/material#3031]
Today I tried to start using Cordova and AngularJS Material Design and have just started with a single page by following the tutorial but I am surprised with the results.

When I tested the app this I am doing using the command cordova serve or ionic serve and view the application in the browser then it looks as expected (I have attached the screenshot)

When I tested the app on the android emulator it works like it was working in the browser as expected.

Till now everything seems OK, but when I deploy the app using ionic run android or cordova run android I see that the UI is distorted and looks not that good(I have attached the screenshot)

I am not sure about whats causing the issue in the android phone when it is working as expected in the browser and emulator. 

Please suggest.
![screen shot 2015-05-29 at 6 21 57 pm](https://cloud.githubusercontent.com/assets/8342604/7882961/3c3303ac-0630-11e5-9647-3030b0530ac4.png)
![screenshot_2015-05-29-18-19-25](https://cloud.githubusercontent.com/assets/8342604/7882964/42c15e30-0630-11e5-8a2d-bbab77c979cc.png)

**Comment by florent1933** [comment]
Hi,

What is your Android version? 

It works fine in Android 5 but not in older versions because angular material is based on flexbox. 

To use a flexbox layout in Android 4, you have to integrate the crosswalk project.
