### ISSUE TITLE
md-option doesn't respect disabled

### ISSUE THREAD

**Issue by mmiszy** [angular/material#3032]
According to the HTML spec, `disabled` attribute is allowed not only on `<select>` but also on `<option>` tag. Currently none of `disabled`, `ng-disabled` or `ng-attr-disabled` is respected on the `<md-option>` element.

**Comment by marcysutton** [comment]
Add this to #2299.

**Comment by marcysutton** [comment]
Actually I meant https://github.com/angular/material/issues/2417, sorry. Closing this one as a duplicate.

**Comment by mmiszy** [comment]
I added a comment on #2417. Is that correct? Thanks.

**Comment by marcysutton** [comment]
Yep, you're good!
