### ISSUE TITLE
Have problem with Left Slide bar. its not fit with the screen

### ISSUE THREAD

**Issue by PrateekDave** [angular/material#3033]
![image](https://cloud.githubusercontent.com/assets/11866529/7886162/cecd5b9e-0645-11e5-865f-a3500cddbe0f.png)

Please have a look bottom lots of white space is coming, when expand the left nav. 

please resolve this issue thanks

**Comment by marcysutton** [comment]
Can you provide a Codepen or JSfiddle that demonstrates this issue? Thanks.

**Comment by jhogg41** [comment]
I've got the same problem. Looks to be linked to having a toolbar outside the sidenav.

A trivial modification to the sidenav example codepen shows this:
http://codepen.io/anon/pen/doNdae

**Comment by jhogg41** [comment]
Looks likely to be linked to issue #2995

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
