### ISSUE TITLE
Inconsistent spacing around md-actions

### ISSUE THREAD

**Issue by calebegg** [angular/material#3034]
Buttons in .md-actions have a different amount of space to the left/right than below. This is especially noticeable when using them with md-raised.

![spacing](https://cloud.githubusercontent.com/assets/782920/7886814/88c23a70-05fa-11e5-86f6-32e3d22db85f.png)

**Comment by peluprvi** [comment]
+1

It's wrong on md-dialog and md-card.

Material Design Spec:
![Material Doc](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3U1dNVWpiSjJUaEk/components_dialogs_updates3.png)

**Comment by peluprvi** [comment]
There is also a problem with the margins of the md-icon-button inside a md-actions.

Material Design Spec for that situation:
![Material Design](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B-Ef4kCjUzkPZkk0Z2xYLW5PRTQ/components_cards20.png)

**Comment by peluprvi** [comment]
The same with a md-menu inside a .md-actions:

```html
<div class="md-actions">
  <md-menu md-position-mode="target-right target">
    <md-button class="md-icon-button" aria-label="Open Menu" ng-click="$mdOpenMenu()" layout="row" layout-align="center center">
      <i class="material-icons">&#xE5D4;</i>
    </md-button>
    <md-menu-content width="3">
      <md-menu-item>
        <md-button ng-click="">
          <div layout="row" flex layout-align="center center">
            <p>Action</p>
          </div>
        </md-button>
      </md-menu-item>
    </md-menu-content>
  </md-menu>
</div>
```
