### ISSUE TITLE
md-tooltip with md-autohide displays on window re-focus

### ISSUE THREAD

**Issue by jmuharsky** [angular/material#3035]
REPRO STEPS
* For easy repro, there is an example at http://codepen.io/anon/pen/doNWNV, where all of the tooltips have had md-autohide enabled.
1. Add an md-tooltip to a focusable element, and set md-autohide on it.  Ex:
   <md-tooltip md-autohide>Click here to learn more!</md-tooltip>
2. Click on the focusable element, and move the mouse away from the element.  As expected, the tooltip disappears.
3. Switch tabs in your browser, or windows in your O/S.
4. Switch back to the tab/window with your focusable element.

CURRENT BEHAVIOR
The tooltip will appear for the focused element, and remain until moused over or another element is focused.

EXPECTED BEHAVIOR
The tooltip should not appear until mouseover.

**Comment by mhchen** [comment]
Note that I think it makes sense to apply this same treatment to md-button. It has a similar display issue on refocusing the browser window

**Comment by ThomasBurleson** [comment]
@mhchen - how so? Can you elaborate with a new issue ?

**Comment by jimmyorr** [comment]
@ThomasBurleson go to https://material.angularjs.org/latest/#/demo/material.components.button and click any button, switch to a second different browser tab, then switch back to the first tab.

Expected: page looks like it did when you left it
Actual: button you clicked is now highlighted

The intention is to indicate focus is on the button, but I think this can be confusing for users.  

In my application I currently blur the button in its callback to avoid this behavior:

    $timeout(function() {
      angular.element(document.activeElement).triggerHandler('blur');
    });

**Comment by joddy23** [comment]
Jimmy

Why am I getting these....


Joseph Friedmann www.readybid.net
<http://demopage.asia/Ready_Bid/home/index.html> 5872 Owens Ave Suite 200
Carlsbad, Ca 92008 *office * 619 378 1325 *Cell * 858 245 1013
joseph@readybid.net

*The Worlds First Totally Free Hotel, Air, Car RFP tool *
