### ISSUE TITLE
md-icon: Support the new official Material Icon font

### ISSUE THREAD

**Issue by shyndman** [angular/material#3038]
Use is described here:
http://google.github.io/material-design-icons/#icon-font-for-the-web

It would be good to support the self-hosting option alongside Google Fonts (although the use of Google Fonts is definitely preferred).

It's worth noting that there are still a few little issues with FOUC and ligatures (you'll actually see the latin characters for a short time), but our team will be exploring options there.

**Comment by marcysutton** [comment]
Just to collect some thoughts here: in my initial testing, ligatures are exposed to the accessibility tree just fine (eliminating the need for `aria-label`) BUT if we are supporting fonts that do not contain such ligatures, we will still need labeling for accessibility. Unless there's some way to detect either ligatures or the presence of the Material Design icon font, we'll have to keep requiring `aria-label` on `<md-icon>`.

**Comment by shyndman** [comment]
Unfortunately, there is no reliable way to detect ligatures from JS. If there was one ligature you could rely on across all icon fonts (a marker), then it should be doable...but that seems unlikely.

**Comment by ThomasBurleson** [comment]
@marcysutton - I am reactivating the aria-label injection for Font-Icon usages.

**Comment by ThomasBurleson** [comment]
Fixed.
