### ISSUE TITLE
webkit-margin-before not being normalized

### ISSUE THREAD

**Issue by wlingke** [angular/material#3039]
I noticed that the user agent styles from `h1`-`h6` are not being removed. Specifically -webitkit-margin-before and -webkit-margin-after.

This results in `<h1 class="md-display-4">` for instance, having huge margins.

**Comment by ThomasBurleson** [comment]
@wlingke - Where do you see that in the [angular-material.css](https://github.com/angular/bower-material/blob/master/angular-material.css) file?

**Comment by wlingke** [comment]
It's not. That's the point. The browser is attaching on some styles that I think it should be normalized by angular-material.css
