### ISSUE TITLE
mdToast persistency to next state

### ISSUE THREAD

**Issue by adrianandreias** [angular/material#3044]
Out of the box mdToast hides when user moves to another state (we're using ui-router but that's probably unimportant). Which is perfect most of the time: i.e. error is shown and if user clicks on a link and goes to another state it makes sense to hide the error.

But if user is filling a form to add, let's say, a contact person and on successful submit app redirects to contacts list would be useful to have a "successfully added" mdToast on this new state.

Is this something that makes sense to be implemented in mdToast?

Or can we configure the event(s) that trigger hiding mdToast?

**Comment by RolandHeath** [comment]
In the specific case of a ui-router state change, triggering the toast in a parent state doesn't seem to cause an issue with this (for me). 
Hope that helps anyone else bumping into this issue.
