### ISSUE TITLE
md-button: how to use md-focused?

### ISSUE THREAD

**Issue by exoticknight** [angular/material#3045]
cannot see any 'md-focused' samples or visual effect in Demo > button,
but the 'refresh' button in Demo > tooltip does has ?
can anyone please help me?

**Comment by marcysutton** [comment]
`md-focused` is added dynamically with JavaScript, to deal with the persistent focus style caused on click in Chrome. You could potentially override the .md-focused style, but you shouldn't be doing anything with it in HTML.

**Comment by l-lin** [comment]
Just for information, I noticed if you add jQuery, the `md-focused` class is not added when you hover the button.
