### ISSUE TITLE
$mdDialogProvider, $mdToastProvider, ... 

### ISSUE THREAD

**Issue by alirezamirian** [angular/material#3046]
Having a configurer method for setting defaults for services like $mdDialog or $mdToast is a great yet simple missing feature. Setting `hideDelay` or `position` on each `toast.show()` invocation is a pain!

**Comment by mchmielarski** [comment]
Hi,
You have two options.
1. create service which has predefined all options for you toast and expose only options which you want - small example http://codepen.io/mchmielarski/pen/eNgVrz
2. use decorators

**Comment by alirezamirian** [comment]
Yes, exactly.
But I think creating a wrapper service for each one or using decoration is not a nice solution compared to having a global configurer.

**Comment by nicgirault** [comment]
:+1:

**Comment by joaovieira** [comment]
:+1:
