### ISSUE TITLE
mdTooltip is broken in Firefox when checking 'pointer-events' to not be 'none'

### ISSUE THREAD

**Issue by alirezamirian** [angular/material#3047]
@ThomasBurleson :
In [this commit](https://github.com/angular/material/commit/667e4c244ccd9a1dfef6894a64b6df0c5e2f6305) you've added a an if statement which checks `pointer-events` of the `md-tooltip` itself to not be `none`! First of all I don't understand why, and secondly
it's not gonna work for obvious reason! In the styles `pointer-events` is set to `none` for `md-tooltip`!
However the computedStyle for `pointer-events` is not `none` in chrome for some reason!

**Comment by jakubweber** [comment]
+1

**Comment by bennet093** [comment]
+1

**Comment by evertonrobertoauler** [comment]
+1

**Comment by djfishe** [comment]
+1

**Comment by ricardobfa** [comment]
+1

**Comment by krunalsheth3** [comment]
This brings another problem. 
I added a css property to one of the parent div tags 
pointer-events : none
This shows up every tooltip present in its child elements 
Is there a work around for that ?
