### ISSUE TITLE
md-select in a form doesn't reset

### ISSUE THREAD

**Issue by patouche7519** [angular/material#3048]
I have a md-select in a form. When I reset it after submit, md-select keep his value and doesn't reset.

**Comment by dmcbcc** [comment]
This is also happening to me.  Setting the model to an empty array does not reset the selections that were made to the md-select.

**Comment by rschmukler** [comment]
This issue has been resolved on master. See [this demo](http://codepen.io/rschmukler/pen/JYVbYL?editors=101). Closing
