### ISSUE TITLE
md-list-item shows yellow border when list item selected

### ISSUE THREAD

**Issue by jeffthompson1971** [angular/material#3049]
I just today moved to latest/greatest on master.   Took a while to re-work my code (i was back on v7).    One thing I notice with the basic 'list' examples is that there is no example where a list is used for a 'selectable' list that goes to a detail view when a list-item is selected.    I find that odd as that is the most common use of a list I can think of.    Why is there no functioning example of basic list-view to detail-view ?  Or am I just missing something somehow? (quite possible! :) )

Anyway, I put the ng-select on the md-list-item where i also have the ng-repeat.    I can get the selection to work, but the list item that is selected will show a yellow border around it which clearly i don't want.   I can only assume this is a but as it looks terrible.   I just want to go back to what it looked like and behaved like back in v7.0.    I was able to select items in the list and they would never have some ugly border applied to them.   

Can you help?
 
my basic code that will show ugly border on selected list item:

```html
  <md-list>
      <md-list-item class="md-3-line" ng-repeat="item in listings" ng-click="select(item)"> 
          <img src="/icons/map32.png" class="md-avatar" alt="map"/> 
             <div class="md-list-item-text" >
              <h3>{{item.StreetNumber}} {{item.StreetName}}</h3>
              <h4> {{item.City | lowercase | capitalize}}, {{item.State}} {{item.ZipCode}} </h4>
              <p>
                {{item.NotesToStaff}}
              </p>
            </div>   
      </md-list-item>
   </md-list>
```

**Comment by marcysutton** [comment]
Can you put this into a Codepen or Plunker showing the issue?

**Comment by jeffthompson1971** [comment]
i'll try to get a screen shot.   I don't see this isuse at all on a browser, but I see it in my mobile app that uses appgyver.   I use angular-material for both mobile app and web site which has been working great.  only now am I seeing this yellow highlight of selected list items.. i'll post a screen shot if there is a way to attach images.    can't really package a while functioning app up in a plunker.

**Comment by kuhnroyal** [comment]
You can use ng-click to go to some detail view, look at the example at the bottom: https://material.angularjs.org/latest/#/demo/material.components.list 

The border might be some tap-highlighting/outline CSS issues on mobile.
Try something like this:
```CSS
outline: none;
-webkit-tap-highlight-color: rgba(0,0,0,0);
-webkit-tap-highlight-color: transparent; /* For some Androids */
```

**Comment by topherfangio** [comment]
Definitely try @kuhnroyal's answer above. If you're still having issues, can you please provide a Codepen showing a very minimal example that causes the issue?

**Comment by topherfangio** [comment]
@jeffthompson1971 Since we have not received a response, we are going to close this. If you can respond with a Codepen, we will reopen.
