### ISSUE TITLE
md-buttons act strange when they are used to open a md-sidenav

### ISSUE THREAD

**Issue by mattblang** [angular/material#3050]
The [sidenav demo](https://material.angularjs.org/latest/#/demo/material.components.sidenav) has a button that remains highlighted after closing the right sidenav.  I personally used a `md-icon-button` and it gains a glow (the initial ripple effect, I believe), after the sidenav is closed, that goes away when hovering, but comes back again when not hovering.

**Edit:** It looks like this is because when the sidenav closes and the other content is in focus again, `md-focused` is added to buttons.

**Comment by marcysutton** [comment]
That is focus management at work. Not a bug–what you're seeing is the triggering button is focused when the sidenav opens and closes.
