### ISSUE TITLE
[BUG] Select component not binding to model when focused

### ISSUE THREAD

**Issue by yccteam** [angular/material#3053]
Might be related to #3052.
Here's the code: http://codepen.io/yccteam/pen/pJRZbN
Reproduce:
1) If you don't touch anything, the first value to be chosen if "Two" according to the model.
2) After 10 seconds, the ```$timeout``` triggers and changes the selection (I've raised an alert to notify on the change).
3) Refresh, and before 10 seconds pass, select "Two" from the selection, and make sure it is still in focus.
4) Now when the model changes, the selection remains.

**Comment by rschmukler** [comment]
This demo now works using the code from master. Thanks.
