### ISSUE TITLE
md-3-line should align icons to the top IF ng-click is added

### ISSUE THREAD

**Issue by asans** [angular/material#3054]
The fix for #2589 does not fully fix the issue of top-aligning icons.  The current fix only addresses the issue when the md-list-item is not clickable.  

If and when one adds ng-click or ng-href to create a clickable list item, the style is no longer applied.

This is due to the following code:

https://github.com/angular/material/commit/a2b88beae24127251c5844747b69f48ebeb120fa#diff-c3e997633bc56157521f1305098d447aL199

The selector:

```
   > md-icon:first-child {
```

Which only selects the immediate child of md-list-item.  When ng-click is applied to md-list-item, there's an intermediate button injected into the system, causing the new style not to be selected.

**Comment by topherfangio** [comment]
Is there any chance you could provide a demo using the latest code so we can see if this is still an issue?

**Comment by topherfangio** [comment]
We really need a demo to investigate this further. Please provide a Codepen and we will reopen.
