### ISSUE TITLE
Tabs: When paging is in effect, the chosen tab's label should be visible after initialization

### ISSUE THREAD

**Issue by itamarro** [angular/material#3057]
When paging is in effect and the loaded initial tab is not in the first group of visible tabs, paging should automatically (and smoothly) be done so that the selected tab's label is visible.

Alternatively, some way to cause this paging to occur should be supported.

Example - let's say we have a tab control with 10 tabs, the labels of the first 4 fit on the device's screen, and paging is in effect. We then have 4 tab labels and 2 arrows. Let's further say that the initially chosen tab (specified via 'md-selected') is tab number 8. 

After loading, the user will see content from tab number 8 - with only the labels of tabs 1..4 visible above it, none of them being selected. This makes it hard for the user to understand what's going on.

In my specific usage, the tabs represents days, and the initially chosen one is the one for today. So if the current day's tab label is not visible on the screen, it's hard for the user to understand what she's initially seeing.

**Comment by Stexxen** [comment]
Sounds similar to issue #3139. Which has a pull request fix.
