### ISSUE TITLE
Ripple animation position incorrect when scrolled (if not using md-content)

### ISSUE THREAD

**Issue by DaveRevay2** [angular/material#3058]
The position of the ripple animation is wrong when the content is in a container with position:fixed or NOT in a md-content container.

Has anyone figured out a solution to this?

An example can be seen here:
http://codepen.io/anon/pen/MwJGJq
Scroll down and click a button at the bottom of the page and you will see that the ripple position is wrong.

I'm not using md-content in my project because it is not compatible with many 3rd party directives which use the body scroll position (popups, smooth anchor scroll etc).

**Comment by mdekrey** [comment]
Your codepen appears to be missing a `})` from the end, but I see the issue you're describing.

Fixed: http://codepen.io/anon/pen/RPZZrq

**Comment by DaveRevay2** [comment]
I had actually used the pen for another purpose and was not aware the the change this one also.
Here is a copy of the original pen:
http://codepen.io/anon/pen/ZGJJwa

**Comment by robertmesserle** [comment]
This is resolved in the latest code tested against Angular 1.3.15.  This CodePen is using a release candidate, and not a stable release.
