### ISSUE TITLE
Switching select options switches also md-tab index

### ISSUE THREAD

**Issue by glothriel** [angular/material#3061]
I have multiple md-tabs. On the first tab I have a form with select fields. Upon clicking on option, often (but not always) i get transferred to second tab.

**Comment by robertmesserle** [comment]
@glothriel Can you provide a CodePen demonstrating this behavior?  I am not able to recreate this nor have I seen it, but it sounds like it could be an issue with the same data being bound to both elements.

Closing for now, will re-open when a demo is available.
