### ISSUE TITLE
placeholder not shown for date input

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#3065]
<md-input-container md-no-float flex>
        <input type="date" placeholder="Date" ng-model="date">
    </md-input-container>
    <md-input-container md-no-float flex>
        <input type="text" placeholder="Start Time" ng-model="startTime">
    </md-input-container>
    <md-input-container md-no-float flex>
        <input type="text" placeholder="End Time" ng-model="endTime">
    </md-input-container>

![md-date-input-placeholder](https://cloud.githubusercontent.com/assets/3141867/7914036/250266a8-086c-11e5-8711-95bdc6198b2e.png)

**Comment by Splaktar** [comment]
What browser was this occurring on? Does #3582 resolve this? Is this a dup of #2162?

**Comment by Splaktar** [comment]
Fixed by 621bdf7069c0eacc27f655a11ddb89e3e3526476. Please reopen and provide browser in use and CodePen if this persists.
