### ISSUE TITLE
md-no-bar hides the bar regardless of what boolean is provided

### ISSUE THREAD

**Issue by mayankdixit** [angular/material#3067]
md-no-bar hides the bar for both `TRUE` and `FALSE`  boolean provided
**This code**:
![screen shot 2015-06-01 at 7 35 23 pm](https://cloud.githubusercontent.com/assets/8286079/7914970/0ce45f8c-0898-11e5-9043-bcca0d315815.png)

**gives this o/p:**
![screen shot 2015-06-01 at 7 35 28 pm](https://cloud.githubusercontent.com/assets/8286079/7914977/1ad41362-0898-11e5-83bf-8e0151b3e843.png)
see [plunkr](http://plnkr.co/edit/Tf1gUKryA41Xw72QH5vD?p=preview)
it should follow provided boolean, shouldn't it?

**Comment by mchmielarski** [comment]
from docs: "md-no-bar If present, disables the selection ink bar."

so value doesn't matter

**Comment by mayankdixit** [comment]
That's what I thought in beginning. But [THIS LINK](https://material.angularjs.org/latest/#/api/material.components.tabs/directive/mdTabs) said it's a `boolean`, explanation is confusing with boolean written along with it.

even if it works like @mchmielarski said, shouldn't it be customisable dynamically (like i'm expecting it in bug description)?
