### ISSUE TITLE
select: multiple attribute only checks for existence but docs indicate that it evaluates true/false

### ISSUE THREAD

**Issue by myagoo** [angular/material#3068]
If I want to tell wether a md-select should be multiple from a scope key, I must do this : 

```
<md-select ng-if="multiple" multiple .../>
<md-select ng-if="!multiple" .../>
```

Because all those lines have the same behavior, they set initialize the select as multiple : 

```
<md-select multiple="true" .../>
<md-select multiple="false" .../>
<md-select multiple="{{true}}" .../>
<md-select multiple="{{false}}" .../>
```

In the source code of md-select directive, I can see this LoC :
https://github.com/angular/material/blob/master/src/components/select/select.js#L387
I can understand why all 4 lines have the same behavior.

So I tried to use ng-multiple and the select started to work correctly... in appearance only : the model is now all messed up.

Here is a codepen where you can see select behavior and the associated model : http://codepen.io/myagoo/pen/OVWGqz

**Comment by dharitdesai** [comment]
+1

**Comment by pdore-netfore** [comment]
+1

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (502/500 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:44678 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsbW-000KpS-Ki
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:06 -0500
Date: Thu, 28 Apr 2016 13:26:07 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875167;
	bh=h9SDYSisC5Flod3ZK/Xij2OaG7Fl1P+PF3S5qLzLVLM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZW6VrOyea/QEgNsJJhCq+ZdyAry72a9D5s3PQXKI9dctfvzhttIePU4eSHk/6MwnQ
	 L4gSgNS0giacxgO+qZ7UpnZfmkoyCq+MFWD5YSCtBDeMmNP8pPl2Pe5RiJ8e4efGu8
	 5ynUhD77z1srFovs5wWwJGht0PRUHkfUC2hQMnyM=

**Comment by nextsoftpl** [comment]
+1

**Comment by danicomas** [comment]
No news?

**Comment by Splaktar** [comment]
@danicomas please open a new issue with a reproduction.

**Comment by Splaktar** [comment]
Re-opening this one as the CodePen is still valid and this issue still exists.

**Comment by Splaktar** [comment]
This seems to be partially related to https://github.com/angular/angular.js/commit/d87fa0042375b025b98c40bff05e5f42c00af114 where binding to `multiple` on `select` elements was disabled in AngularJS 1.2.0.

**Comment by Splaktar** [comment]
There is a lot more discussion related to that in:
https://github.com/angular/angular.js/pull/3230
https://github.com/angular/angular.js/pull/3337

**Comment by Splaktar** [comment]
As mentioned in those issues and https://github.com/angular/material/issues/9705, `ng-multiple` was also removed in AngularJS 1.2.0.

We need to remove it from AngularJS Material as well. This removal is being tracked in https://github.com/angular/material/issues/9705.
