### ISSUE TITLE
md-select: css styling within md-input-container uses too much space

### ISSUE THREAD

**Issue by asans** [angular/material#3071]
with the newest master release (HEAD), the md-select wrapped inside md-input-container is now grossly padded.  You can see this in the DEMO, select section (look at the Validations portion). You'll notice that error messages and and the spacing between the buttons and the select component is extremely large.

Upon checking, the primary culprit is the new padding added to md-select:

https://github.com/angular/material/blob/master/src/components/select/select.scss#L55

This new padding property, when placed within md-input-container, causes double the amount of padding because md-input-containers add padding-bottom and md-select now also has padding as well.

One of them needs to go.

**Comment by ngraef** [comment]
Included in #3055

**Comment by ngraef** [comment]
This is fixed and should be closed.
