### ISSUE TITLE
md-dialog: One should be able to open multiple "full screen" dialogs

### ISSUE THREAD

**Issue by asans** [angular/material#3072]
#### Feature Enhancement Request

Considering that Material Design specs allows the use of multiple dialogs to be open on top of one another, I believe this should really be supported.  One use for this is when one wants to open up a full screen dialog and still show some dialog alerts or confirmations.  The other use is the way one can open one full screen dialog on top of another on top of another.  Canceling/closing the dialog will take you back to the previous one without having to reload the view, which will force one to lose context and lose track of where we were before. 

A great example would be the list-to-detail view.  You load a list of items and as you scroll down and see one you like to view more details of (ie. an order), you click on it to open up a full screen dialog to view the details of the order.  After you view it, you will want to go back to where you were before and continue.  This is also the case with reading news stories or even cards.  If we had to go back by refreshing, we'd have to first load all the entries up to that point and then scroll to where we were.  This is far less efficient than just allowing multiple dialog screens.

The above scenarios are frequently encountered and well implemented in the android UI (see settings and even some of the android apps like Facebook or Google+).

**Comment by dg1202** [comment]
this sounds like two request.  
1. support fullscreen dialog, which there is already an issue for #2148  
2. support layering dialogs? not 100% sure on whats being described.

**Comment by asans** [comment]
#2148 covers the full screen dialogs, which is used to describe the scenario here.   Since my example is a bit confusing, let me copy verbatim the text from Material Design Specs about Full Screen Dialogs.

The bits that I want to emphasize is in bold below:

---
Usage

Full-screen dialogs group complex tasks that require explicit action, such as save or create, before changes are committed or discarded, as in a calendar entry.

__Full-screen dialogs enable complex layouts, minimize the appearance of stacked sheets of material (dialogs above dialogs) and increase the app’s perceived z-depth. They enable individual tasks to launch simple menus or simple dialogs as part of the complex operation.__

Consider using a full-screen dialog when the content or process meets any of the following criteria:

The dialog includes components like pickers or form fields requiring an input method editor (IME), such as a keyboard.
When changes are not saved in real time
When there is no draft capability in the app
When performing batch operations or queuing changes prior to submitting them
No modifications and selections made in the full-screen dialog are saved until “Save” is touched. Touching the “X” will discard all changes and exit the dialog. 

---

So better to say that it's "dialog above dialogs" should be a supported feature in the future instead of just allowing only one single dialog to always be open at any one time.

**Comment by dg1202** [comment]
Gotcha. Sounds useful indeed. 

So, I am not sure what the status is on stacking dialogs, but it does appear to be mentioned in #698. That issue appears  to be more about multiple dialogs open at once, but some of the team members touch on the stacking of dialogs.  
  
If you check the [forums](https://groups.google.com/forum/#!searchin/ngmaterial/md-dialog/ngmaterial/p2508ISSdj4/fj5fKI0b7l0J) , @ThomasBurleson stated:  
 
>The team is already planning on supporting a stack of dialogs (instead of the current singleton view solution). 
This is schedule for Milestone 0.8  
  
Angular Material is currently at 0.9.8-rc1 without this feature.

**Comment by naomiblack** [comment]
We agree this needs discussion, but unfortunately, we will not be able to add it before beta.

**Comment by prasannapattam** [comment]
Is there a timelines when this will be implemented (1.0-beta1)

**Comment by blmcquillan** [comment]
+1

**Comment by thunghan** [comment]
+1

**Comment by dannyadrizer** [comment]
+1

**Comment by hnirvana** [comment]
+1

**Comment by reduardo7** [comment]
+1

**Comment by knizhnikov** [comment]
+1

**Comment by B3nCr** [comment]
@ThomasBurleson Sorry to be a pain but why are these being marked as Deprecated? Is there some guidance about an alternative pattern than using multiple dialogs? 
Thanks

**Comment by ThomasBurleson** [comment]
Material1 will only support singleton diaologs. Material2 will support multiple dialogs.

**Comment by jaymanned** [comment]
@Thomas Sorry to get back on this. What you are saying is that material for angular 1.x apps will never support dialog stacking? It's easy to see that dialog stacking is one of the most popular feature requests in this repo. For a reason, it is a very well established interaction pattern for web apps (e.g. confirm action taken on main dialog). 

May I kindly ask the ng-material team to reconsider? If not possible, at least you could provide some workable alternative as suggested by @B3nCr ?

Thanx

**Comment by niveo** [comment]
http://www.codeproject.com/Articles/992699/An-Advanced-and-Easy-use-AngularJS-Modal-Dialog

**Comment by B3nCr** [comment]
@niveo I meant a pattern that follows the Material design spec.

**Comment by vassagus** [comment]
@ThomasBurleson I really need this issue for an Agular 1.5 app I have, I can't just migrate the app to Angular 2 just because this basic feature is not available. Please let me add this functionality as a pull request, I'll wait for your answer.

**Comment by DevVersion** [comment]
@vassagus See #8630

**Comment by vassagus** [comment]
@DevVersion thanks.

**Comment by olingern** [comment]
Unsure why this isn't documented by using `skipHide` on the child dialog will allow this. 

[Here's a plunker](http://plnkr.co/edit/Ga027OYU5nrkua3JxNRy?p=preview)

And [here's the line of code](https://github.com/angular/material/blob/e898d228dc6dd186b5b71cb1ea3d7cf2165528d5/src/core/services/interimElement/interimElement.js#L292) that "skips" hiding the parent dialog.

**Comment by jaymanned** [comment]
@olingern Great finding!

Can anyone please confirm if we can use this undocumented option safely

**Comment by jaymanned** [comment]
@olingern I've [styled slightly your plunker](http://plnkr.co/edit/yy82kcBM5kMjlRohhOcb) so the stacking effect is more evident

**Comment by olingern** [comment]
@jaymanned I believe there are some issues with earlier Angular version support. The plunkr isn't actually mine. I stumbled across it [here](http://stackoverflow.com/questions/30724239/mddialog-stacked-nested-dialogs-is-it-possible);

Here's how I'm currently using this:

**Parent Setup:**

```javascript
$mdDialog.show({
        controller: 'MyCtrl',
        controllerAs: 'vm'
      }).then(function(res){
        _manageChildDialogAction(res);
      });
```

**Child setup**
```javascript
  $mdDialog.show($mdDialog.confirm({
        title: 'Delete?',
        textContent: 'You will not be able to undo this. Are you sure?',
        ok: 'Delete',
        cancel: 'Cancel',
        skipHide: true
      })).then(function(del){
        $mdDialog.hide({
         customObject: _customObject,
         action : 'DELETE'
         });
      },function(cancel){

      })
```

For completeness, here's my child modal resolution handler
```javascript
function _manageChildDialogAction(modalRes){
  var action = modalRes.action;

  if (action === 'SAVE') {

  } else if(action === 'DELETE') {    

  }
}
```
