### ISSUE TITLE
Ui Problem with Android browser older than 4.4

### ISSUE THREAD

**Issue by STDGA** [angular/material#3073]
Hello,
first of all thanks, the library is amazing.

I have got many problems with the Android default(stock) browser. I have tested it with version 4.1,till 4.4. The simplest way is to open your website with one of these versions.

Here you can see some screen shots from BlueStacks(android 4.04) (I also tested them with actual device):
![input1](https://cloud.githubusercontent.com/assets/8609390/7927406/bdd651e6-08df-11e5-9a9b-d54e6f6c6fbd.JPG)

As you can see the sidebar wont show up and the inputs are dispositioned. For select component, it wont show the dropdown at all:
![select](https://cloud.githubusercontent.com/assets/8609390/7927444/6b616116-08e0-11e5-925c-3dc1d4f815d1.JPG)

I think you got the picture, most of the components wont work with the default browser of Android older than 4.4.

I want to know if you have a plan for support this. It would be really nice if there was a documentation about browser support.

Thanks

**Comment by PDSBGreg** [comment]
If you're developing your site as an app using the WebView, like my team is, the solution we are using is to use the CrossWalk web view (XWalkView) instead of the default Android WebView. It increases the APK file size greatly because you're including Chrome in your app, but you'll get support for Android back to 2.2.

For more, see https://crosswalk-project.org/ 

This, unfortunately won't help if you're simply developing as a website.

**Comment by rafasegat** [comment]
Crosswalk fit very well in my project.

BTW is there a way to reduce the increase of size crosswalk to APK file?

Cheers
Raf

**Comment by PDSBGreg** [comment]
Check out shared mode as described at https://crosswalk-project.org/documentation/shared_mode.html

**Comment by rafasegat** [comment]
Cool but its a lil bit dangerous.

Imagine many users first time download the app waiting for a download 20mb

Do you use Shared Mode on your projects PDSBGreg?

Thanks for your help.

**Comment by PDSBGreg** [comment]
No. Not at the moment anyway. Our apps are internal and some run on pretty old Android devices. I think Shared mode requires a higher SDK than our min spec.  So my users have a big download for my app.
