### ISSUE TITLE
[master] Error messages won't show with form.field.$dirty added to ng-messages.

### ISSUE THREAD

**Issue by sheaujye** [angular/material#3076]
The following won't show the error message, the objective is to prevent showing the error message for the first time (on load).

                <md-input-container>
                    <label translate>Email Address *</label>
                    <input type="email" name="email" ng-model="user.email" placeholder="john@example.com" required autocomplete="off">
                    <div ng-messages="loginForm.email.$error && loginForm.email.$dirty">
                        <div ng-message="required">
                            <translate>Email address is required.</translate>
                        </div>
                        <div ng-message="email">
                            <translate>Invalid email address.</translate>
                        </div>
                    </div>
                </md-input-container>

**Comment by PrashantAshok** [comment]
I think you can't use both $error and $dirty inside [ng-messages](https://docs.angularjs.org/api/ngMessages/directive/ngMessages). 
Please change it to can you try 
```<div ng-messages="loginForm.email.$error" ng-if="loginFrom.email.$touched">```

**Comment by sheaujye** [comment]
ok thanks, that works for me.
