### ISSUE TITLE
IDs missing in md-Tabs

### ISSUE THREAD

**Issue by bennet093** [angular/material#3077]
The IDs for every md-Tab is missing in the markup. Cannot switch Tabs with protractor anymore now. Issue was not there in V 0.8.3.

**Comment by marcysutton** [comment]
@robertmesserle should we recommend selecting in Protractor by something other than ID or add them back in if not already present?

**Comment by robertmesserle** [comment]
Hm. I'll have to give this some thought. I was considering having
md-tab-label and md-tab-body transfer all of their attributes.

**Comment by Charlie-Ng** [comment]
I temporarily use element.all(by.tagName('md-tab-item')).get(0).click() to click the first tab, and get(1) to second tab, and so on.

**Comment by bennet093** [comment]
+1

Charlie-Ng <notifications@github.com> schrieb am Do., 16. Juli 2015 20:39:

**Comment by Ivor** [comment]
Relying on the order of tabs seems quite brittle. It would be great to have an alternative to this.

**Comment by dallincoons** [comment]
+1

**Comment by manchurocas** [comment]
Is there an alternative available yet?  The method by @Charlie-Ng works if there is just one set of tabs on the page, but there are several different sets of tabs on my particular page, and I can't distinguish between one set of tabs or another by using tag name.

**Comment by ssj3sunny** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
