### ISSUE TITLE
md-tab md-tab-label does not support ui-sref

### ISSUE THREAD

**Issue by rosscdh** [angular/material#3078]
HI there, a small problem with md-tabs in     "angular-material": "0.9.4", and     "angular-material": "0.9.6",

The tabs no longer work nicely using ui-sref="xxx" and you en up with the attached ugly user experience.

Thoughts? any feedback is welcome. 

Thanks for your time and efforts!

![weird-bug](https://cloud.githubusercontent.com/assets/397106/7933524/ef69248c-091f-11e5-8373-47871883cd28.gif)

**Comment by robertmesserle** [comment]
This should be supported now as of 0.9.7.
