### ISSUE TITLE
md-dialog parent scroll on touch device (Safari Mobile v8.0)

### ISSUE THREAD

**Issue by mwymann** [angular/material#3079]
Parent scroll isn't disabled when scrolling on touch device.
I tested this with iPad 2 and iPhone 6 and the actual demo (release 0.9.7).

**Comment by chrisguerrero** [comment]
+ 1

**Comment by cnpal** [comment]
+1

**Comment by muneer-khan-10p** [comment]
Not sure if this is the right solution for the problem but this actually fixed the issue for me on iPhone-6

.md-dialog-container{
  position: fixed;
    top: 0 !important;
    height: 100%;
    md-dialog{
      max-height: 100%;
    }
}

**Comment by jjf1** [comment]
+1.  With successful **javascript workaround**.

Issue occurs in any iOS `webview` based container (Chrome on iOS, Cordova App on iOS).  Not tested on Android.

Debugging (briefly) led to the the `disableParentScroll` feature. Noticed it is being applied to a `<div>` that is a sibling, and not a direct parent of the dialog. But rather than try to wrangle with all the implications of a deeper investigation of that, opted for **the following javascript workaround...**
* In **controller**, set `disableParentScroll` false on invocation...
```
$mdDialog.show({
   templateUrl: 'views/my-dialog.html',
   disableParentScroll: false
});
```
* Attach **custom directive** to `views/my-dialog.html`...
```
<md-dialog my-workaround>
.
.
.
</md-dialog>
```
* In **custom `my-workaround` directive**, invoke a `touchmove` handler to achieve desired functionality...
(disclaimer: presumes `jQuery` is loaded, but could be rewritten without it of course).
```
angular.module('myApp')
  .directive('myWorkaround',
    function ($timeout, $mdDialog) {
      return {
        restrict: 'A',
        link: function (scope, element, attrs) {

           $.fn.isVScrollable = function () {
              return this[0].scrollHeight > this[0].clientHeight;
           };

          var dialogContent = $(element).find('md-dialog-content');

          var touchFix = function(evt) {
            if ($(evt.target).hasClass('md-dialog-container') || ! dialogContent.isVScrollable()) {
                // preventDefault when gesture occurred inside the container OR my dialog does not scroll.
            	evt.preventDefault();
            } else {
                // consume gesture when it occurs inside my (scrollable) dialog.
                evt.stopPropagation();            	
            }
          };

          $timeout(function() {
             // Mobile gesture(s) patch. Prevent iOS scroll of elements underneath the dialog...
             $('.md-dialog-container').on('touchmove', touchFix);

             element.on('$destroy', function () { 
               $('.md-dialog-container').off('touchmove', touchFix);
            });
          });

        }
     };
   });
```

**Comment by matewilk** [comment]
+1 on this one

**Comment by Jinshichi** [comment]
This issue still exist in my iPhone 5S (iOS 9.3.1). I have tested with v1.0.8 [demo page](https://material.angularjs.org/latest/demo/dialog).
Why this issue marked as deprecated?

**Comment by sarantist** [comment]
Directive works well for custom dialogs, any possible solution for alert or confirm dialogs?

**Comment by reanq** [comment]
How jjf1's code as an angular config would look like:
 
`/**
 * md-dialog config
 */

MdDialogConfig.$inject = [
  "$provide"
];

function MdDialogConfig($provide: ng.auto.IProvideService) {

  $provide.decorator("$mdDialog", ["$delegate", "$timeout", ($delegate, $timeout) => {

    let show = $delegate.show;

    $delegate.show = function extend(tElement) {
      show.apply(this, arguments);

      let dialogContent;
      let dialogContainer;

      console.log(tElement);

      let touchFix = function(event) {
        let target = event.target;
        // console.log(target);
        // console.log(dialogContent.contains(target));
        if (!dialogContent.contains(target)) {
          // preventDefault when gesture occurred outside the dialog
          event.preventDefault();
        } else {
          // consume gesture when it occurs inside the dialog
          event.stopPropagation();
        }
      };

      $timeout(() => {
        dialogContainer = document.getElementsByClassName("md-dialog-container")[0];
        dialogContent = document.getElementsByTagName("md-dialog")[0];
        // console.log(dialogContainer);
        // console.log(dialogContent);
        dialogContainer.addEventListener("touchmove", touchFix);
      });

    };

    return $delegate;
  }]);
}

export default MdDialogConfig;`

But if you just want to disable the scroll of the parent element just add css style to it. In our project we have a md-content container below our header in which every view is loaded. The container got an id, so our css looks like this:
`
body.md-dialog-is-showing #md-content-id {
  overflow: hidden;
}
`
