### ISSUE TITLE
Icons dont work in modal

### ISSUE THREAD

**Issue by joshribakoff** [angular/material#3081]
If inside a `md-dialog` modal, the following does not work:
```
<i class="material-icons">file_upload</i>
```
![selection_075](https://cloud.githubusercontent.com/assets/4021306/7934492/eed8be44-08dc-11e5-8f26-934c6139c7a3.png)

Changing to this does work:
```
<i class="material-icons">&#xE2C6;</i>
```
![selection_076](https://cloud.githubusercontent.com/assets/4021306/7934497/f22cbf8c-08dc-11e5-8fff-e027e1efd97d.png)

(chrome 42.0, using angular/material from CDN.)

Both examples work fine when not in a modal.

**Comment by EladBezalel** [comment]
Working with latest [Codepen](https://codepen.io/EladBezalel/pen/VvbopK)

**Comment by ThomasBurleson** [comment]
@EladBezalel - what did you change to get this to work ?

**Comment by EladBezalel** [comment]
Nothing.. It's 4 months old so maybe we fixed it already
