### ISSUE TITLE
md-contact-chips: Duplicate selections happend with remote queries

### ISSUE THREAD

**Issue by NicolasVargas** [angular/material#3082]
Hi,

Here is a [Codepen example](http://codepen.io/anon/pen/WvpvOP?editors=101) i forked from the [Angular Material Demo](https://material.angularjs.org/latest/#/demo/material.components.chips).
It performs an $http request to retrieve a list of contacts when we type something in the input.
Here, even if the filter-selected attribute is set to true, we can select more than one time a contact. So it creates duplicates.

Is this behavior usual ? 

Izcalli

**Comment by typotter** [comment]
The duplication check uses identity matching (==) versus semantic comparison (compare all the members).
In order to work around this, you would have to cache the suggestion objects. I've updated your codepen here: http://codepen.io/anon/pen/aOMGKb to do this.
