### ISSUE TITLE
element height causes various rendering issues

### ISSUE THREAD

**Issue by jlmagee** [angular/material#3083]
The issues may be caused by material or browsers or both. The referenced plnkr renders differently in chrome43 (overlays content of prior div) and firefox38 (puts scroller in entire window). Various height setting changes create different undesirable results. The only way to get consistent results that make all the content visible is to specify absolute height values that render within the current window. This is undesirable because watchers on resize may interfere with the watchers in the material javascript.

http://plnkr.co/edit/ezYWOW24y2Vh3BL5egfU

Some documentation on best practices with height would be extremely helpful.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (498/400 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:43486 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsbh-001a4e-CT
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:32:18 +0200
Date: Thu, 28 Apr 2016 13:25:36 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875136;
	bh=KIVjg3ormuzqqic5CaDM1/1k7MpGyCpdBv4+Ka5TL2c=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=VBq1ufjV0nKDQuuQtrYY/H22Fkn4b7QkMWBkNbTEq4Sn+EqgaMQpSjfCcdX3ccNit
	 njs1jaVgwzB2IytJGXGkiw//nmN8kBp7ZnLknubUsCYncPhDrcFOz6/66EmFyR2xHv
	 cAmCzcwqOqkIGOP0rfFi4Eona6aJ9qz1L4ud5vZo=
