### ISSUE TITLE
[md-autocomplete] Unable to reset the input

### ISSUE THREAD

**Issue by jgoux** [angular/material#3084]
Hi,
on the master, I'm unable to reset the selected input from md-autocomplete by setting the model to *null*
Here is the demo : http://codepen.io/jgx/pen/XbMmxE

**Comment by CxRes** [comment]
Well, you need to set the md-search-text variable to null as well. See the modified demo: http://codepen.io/anon/pen/oXZmVG

**Comment by stefan-schweiger** [comment]
@CxRes this works but if you have set `md-min-length="0"` it will open the popup again.

Anyways I think it should work the same ways as with `md-select` by just setting the selected item to `null`.

**Comment by robertmesserle** [comment]
This is as designed and would require you to set both the searchText and the selectedItem.  I believe resetting just searchText would also clear selectedItem.

**Comment by stefan-schweiger** [comment]
@robertmesserle 

![why don't we have both?](http://i.imgur.com/sp8v92J.gif?1)

it would be more in line with `md-select` as you also just set the `ng-model` to `null` (and in the context of `autocomplete` `selectedItem` is the model in my opinion)

btw setting searchText to `null` actually results in an exception, setting it to `''` works as far as I can tell in a codepen with the current master (but I had problems with a master from last week, so I will recheck this tomorrow at my actual project)

**Comment by robertmesserle** [comment]
@stefan-schweiger The problem is that we have two models that we need to track for Autocomplete.  The problem is that an empty `searchText` always means that there is no `selectedItem`, but the opposite is not always true.

**Comment by stefan-schweiger** [comment]
@robertmesserle ok I see. Also now I remember what the problem was, when you have set `md-min-length="0"` the popup comes back open when you set `md-search-text` to `''` and as it has no focus it behaves kind of weird.

http://codepen.io/anon/pen/waEzgv

What's even worse in my case is that I hide the `md-autocomplete` after selection to display the item, when you clear it again you have the popup in the upper left corner nowhere near the `md-autocomplete`.

![](http://i.imgur.com/AWhf65B.png)

**Comment by tolemac** [comment]
The same here, I understand that autocomplete can have no model value but searchText has it.
Just need that popup dont back open.

**Comment by stefan-schweiger** [comment]
As a workaround, you can disable the `md-autocomplete` before resetting and enable it again afterwards, which is stupid as hell, but at least it works...

**Comment by technotomahi** [comment]
It looks like if we go by triggering the dom element it works. 

[plunker](https://codepen.io/londovir/pen/GJpdGR) here

**Comment by DevVersion** [comment]
Actually this should be fixed within `v1.1.0` with commit https://github.com/angular/material/commit/dadbcf21ff95764ddcc678a0821e1fa02beaf12d.

**Comment by asirigada** [comment]
Hi..having a problem with md-autocomplete.
1) when item is searched and selected. After the selection, it is not closing the dropdown.
2) when you clear the text after written something in input field, there is a empty dropdown. 
![empty_dropdown](https://cloud.githubusercontent.com/assets/18682024/18932880/4bb75f4e-85a0-11e6-9ed7-482f0f8a92f3.PNG)

**Comment by johndshea** [comment]
I'm having the same issue as @asirigada - when an item is selected, the completion suggest does not close. Any ideas, folks?

**Comment by asirigada** [comment]
add ng-hide class in your css..
ng-hide{
   display: none;
 }

**Comment by asirigada** [comment]
Hope that works. It worked for me

**Comment by johndshea** [comment]
No good, unfortunately. I wonder whether it has to do with the fact that I'm working on a chrome extension.

**Comment by asirigada** [comment]
I m also working on extensions... After adding the class it works..!!

**Comment by johndshea** [comment]
This appears to be a broader issue with angular-material and chrome extensions. Ng-show doesn't work at all in chrome extensions in my experience. Adding the .ng-hide class to your CSS appears to fix that issue as well.

**Comment by asirigada** [comment]
Yes angular-material and chrome extensions has lots of issues to solve. No working with md-virtual-repeat  too. when tabs are shown, md-virtual is hidden in the dialog content.
