### ISSUE TITLE
md-button ng-click performance inconsistent

### ISSUE THREAD

**Issue by llehn** [angular/material#3085]
md-button inconsistently produces a delay when ng-click is run:

http://codepen.io/anon/pen/bdgzKJ

open chrome profiling tools, start CPU profiling and click Test1 button, stop profiling.

in most cases there are 2 spikes: 
1. eventhandler calling gestureStart
~80-100ms delay
2. eventhandler calling gestureEnd, calling scope.apply, finally calling the callback in ng-click

sometimes, I get just a single spike, i.e. ng-click code is executed immediately.

I want the code on ng-click to run immediately, without the 80-100ms delay.
![2015-06-02 16_15_07-a pen by captain anonymous](https://cloud.githubusercontent.com/assets/10240910/7937866/9d992490-0942-11e5-832d-32db83a396c1.jpg)

**Comment by rosscdh** [comment]
+1 this appears to be causing the click event to fire twice in my case..

**Comment by Praggie** [comment]
seems the issue issue in my case as well as ng-click is firing twice.

**Comment by rosscdh** [comment]
Have to manually pass $event into the clock function and call
stopimmediatepropagation in it. #veryrough

**Comment by llehn** [comment]
Is the issue going to be addressed in some of the next releases?
