### ISSUE TITLE
md-select: openSelect() called twice

### ISSUE THREAD

**Issue by warpdesign** [angular/material#3086]
In my application, for some reason, when clicking on the select element, the select is first opened, closed, and then opened again quickly, which produces an ugly flash.

Digging into the source code it seems that the click event is bounded twice to the select, so the openSelect function is called twice.

Unfortunately I haven't been able to reproduce it on a simple example.

Here is the code: (md-select component)

    postLink(scope, element, attr, ctrls) {
    // ....
      attr.$observe('disabled', function(disabled) {
        if (typeof disabled == "string") {
          disabled = true;
        }
        if (disabled) {
          element.attr('tabindex', -1);
          element.off('click', openSelect);
          element.off('keydown', openOnKeypress);
        } else {
          element.attr('tabindex', 0);
          // element.on('click', openSelect);
          element.on('keydown', openOnKeypress);
        }
      });

      if (!attr.disabled && !attr.ngDisabled) {
        console.log('postLink');
        element.attr('tabindex', 0);
        element.on('click', openSelect);
        element.on('keydown', openOnKeypress);
      }
    // ...
With my code, postLink is called with attrDisabled not set, so click event is bound a first time there. Then disabled attr $observe is called (with disabled === undefined), so the click event is bounded twice.

I have no idea why this happens. My element is not disabled.

**Comment by cah-danielmullins** [comment]
+1 For this issue, I am seeing this as well.

**Comment by shyvy88** [comment]
+1 here as well

**Comment by Sennahoi** [comment]
+1

**Comment by rkotenko** [comment]
The select works fine on the Material site.  I copied down both the first example (with the states) and the version of material that the site is using (just in case mine was different).  The blinking still occurs.  I don't understand why it happens in my local version but not on the Material site, but it definitely happens for me too.

**Comment by warpdesign** [comment]
Since there is no easy way to reproduce it and it may not be obvious what happens, I recorded a little video showing the problem: https://youtu.be/8S7ucr6HO7U

**Comment by warpdesign** [comment]
After more research it seems problem only happens with *Angular version 1.3.0* (and maybe previous version). Updating to version 1.3.1 fixes the problem.

What version are you using @cah-danielmullins @shyvy88 ?

**Comment by shyvy88** [comment]
Using 1.3.17 although I've been off the project for a while so not sure if this is still an issue.

**Comment by rschmukler** [comment]
Can someone confirm that this still exists on angular `1.4.x` and 0.10+

**Comment by warpdesign** [comment]
@rschmukler tested with angular 1.4.0 and angular-material 0.11.0: isn't reproducible.

I think this only happens with 1.3.0

**Comment by rschmukler** [comment]
Closing then. Thanks @warpdesign
