### ISSUE TITLE
Linear progress bar has glitchy animation

### ISSUE THREAD

**Issue by keithguerin** [angular/material#3091]
The animation is very erratic. Here is a video comparing the [demo](https://material.angularjs.org/latest/#/demo/material.components.progressLinear) to the video on the [Material spec](https://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators).

https://drive.google.com/a/google.com/file/d/0BzSLg0vNFVUwQ0pVRk01bUFrZjQ/view

**Comment by shyndman** [comment]
My coworker is working on the spec-compliant animation for Android. I'll talk to him about getting these timing curves right.

**Comment by ngraef** [comment]
See #2762. This was greatly improved by 1d478ebd6e5c6ddb6453cc1a708064459075a75e and is included in the 0.9.7 release.

**Comment by shyndman** [comment]
Cool. I'm closing this for now.
