### ISSUE TITLE
Refactoring the grid system

### ISSUE THREAD

**Issue by Evanion** [angular/material#3095]
The current implementation of the grid system is based on how Bootstrap does it.
I say that's a flawed implementation.

How can anything that bases it's markup on how it should look in desktop, be truly 'mobile first'?
I would much more recommend following how [UIKit does it](http://getuikit.com/docs/grid.html).
Where the only wrapper div you have, is the one that encompasses the entire grid.

**Comment by shyndman** [comment]
@ThomasBurleson I think this is related to the CSS grid, not grid-list
