### ISSUE TITLE
md-tab keeps non-rendered templates as node in the DOM

### ISSUE THREAD

**Issue by gitawego** [angular/material#3098]
for exemple:
```
<md-tabs>
<md-tab label="tb1">
<input id="date" list='dateLimit'/>
<datalist id="dateLimit">
          <option ng-repeat="item in appConfig.auditActionPlanDateLimit track by $index" value="{{item}}"
                  label="{{item | translate}}"></option>
</datalist>
</md-tab>
</md-tabs
```
it will generate:
```
<md-tabs>
  <md-tabs-wrapper>
    <md-tab-data>
       //inside, it contains non-rendered template as node in the DOM
<md-tabs-content-wrapper>
    //contains the rendered content
```

firstly ,it introduces unwanted dom nodes (imagine if the template is huge, this will make the DOM pretty heavy.), secondly, it makes my input#date find always the first non-rendered datalist as list, so the page could never show the right data list.
```js
//try querySelector, you will find two datalist
var els = document.querySelectorAll('datalist#dateLimit');
console.log(els.length); // == 2
```

for now, I have to create another directive by wrapping the md-tabs, and remove the first datalist in link function..... which is not good at all....

**Comment by robertmesserle** [comment]
There are two options right now in the latest version for how hidden tabs are handled.

Option 1: By default, the DOM nodes are left in the DOM, but their scopes are disconnected to prevent Angular from doing anything with them for performance reasons.  Leaving the items in the DOM saves us the performance hit of having to re-render the content later.

Option 2:  If you do not want to use this method, you can specify `md-no-disconnect` which will switch to `ng-if` instead.  The first method tends to offer the best performance, but has some down sides associated with it (such as events not being picked up within your hidden tabs).  (Note that only the content is removed when using this method, but a placeholder will remain for each hidden tab.)

It's likely that the default option will end up changing as I think `ng-if` is the safer option.
