### ISSUE TITLE
md-toast: Overriding toast is closed by hideDelay of original toast if in same handler

### ISSUE THREAD

**Issue by Londovir** [angular/material#3103]
Codepen: http://codepen.io/londovir/pen/KpWyYm

If you have a single event action, such as an `md-button` click event, which generates an `md-toast` with a determinate `hideDelay`, and then that same event handler generates another `md-toast` with a `hideDelay` value of 0/false or a longer period of time, the second toast is dismissed according to the timeout of the first one.

It appears that when the second toast appears on the screen, which forces the first toast to dismiss away, that the timer for dismissing the first toast does not get disabled/revoked, but rather stays in place. When that timer fires later, even though the second toast is set to stay open, it will get dismissed, since presently `mdToast` does not appear to support multiple simultaneous toasts.

I have debugged it to what appears to be a race condition in angular-material v0.9.7-master-afec091, in lines 2135, 2141, and 2147:

1) The `remove` method for the 1st toast is getting executed first because the 2nd toast has caused the 1st toast to be dismissed. However, by that point the handle `hideTimeout` has not been initialized yet and is `undefined`. (Line 2147)

2) The `cancelTimeout` method is run for the 1st toast. Since `hideTimeout` is `undefined`, this method exits with no result. (Line 2141)

3) The `startHideTimeout` method is run for the 1st toast. This sets `hideTimeout` for the timeout duration specified for the 1st toast. (Line 2135)

4) The `remove` method is called for the 2nd toast, even though it is not specified to timeout close. (Line 2147)

I imagine it could be helpful to set a flag within the `self` upon the `remove` call which would prevent a timeout from being set after that element was removed. My current workaround is to put in code into `remove` which sets a value in `self` that signals the element has been removed, which is then checked for in `startHideTimeout` before registering a timeout handle. This simply prevents that timeout from being registered for an element that was already hidden.

**Comment by Wsiegenthaler** [comment]
+1

**Comment by baelter** [comment]
+1
