### ISSUE TITLE
md-autocomplete does not remove the dropdown on destroy

### ISSUE THREAD

**Issue by ddimitrop** [angular/material#3104]
This may be a duplicate of https://github.com/angular/material/issues/2872 (not sure)

If the dropdown of an autocomplete becomes visible, it does not get removed when the element is destroyed.

See:  http://codepen.io/anon/pen/xGqpXN
Just type 'Ala' in the autocomplete box.

Since there is a lag for the resolution of an autocomplete promise, I have even seen cases where normal user interaction (say clicking quickly after typing on another tab - an action that would remove the autocomplete) results in the dropdown poping up in completely irrelevant context without a way to get rid of it (clicking on the page does not remove it anymore).

**Comment by Tyrannmisu** [comment]
Also happens for me, as i'm using autocomplete in a dialogue this happens fairly often.

**Comment by ddimitrop** [comment]
OK this was fixed in 0.98.
Same codepen with 0.98

http://codepen.io/anon/pen/WvOYme
