### ISSUE TITLE
md-list font size inconsistencies

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3107]
When an md-list-item includes a link, the font size is set to 14px, but when there is no link the font size is 16px.

Material Design specs have 16dp for all primary font sizes within lists.

**Comment by topherfangio** [comment]
Can you please provide a Codepen showing the exact issue? I'm not seeing the link change the font size in this codepen: http://codepen.io/topherfangio/pen/XmBxej?editors=100 (it does seem to always be 14px though).

**Comment by hodeyp** [comment]
@topherfangio apols this was raised some time ago, it has been fixed some time ago. closing

**Comment by topherfangio** [comment]
@hodeyp No need to apologize! Thanks for the info!
