### ISSUE TITLE
Toolbar theme colour doesn't extend all the way down.

### ISSUE THREAD

**Issue by justingrayston** [angular/material#3111]
Tested on here on Nokia Lumia 735 where it was really noticeable.

![wp_ss_20150603_0003](https://cloud.githubusercontent.com/assets/5277488/7973254/81f30a08-0a4b-11e5-9b9e-cb8f91ef3b06.png)

Not so bad on my Nexus 5 but you can just see it.

![screenshot_2015-06-03-23-51-19](https://cloud.githubusercontent.com/assets/5277488/7973327/135de260-0a4c-11e5-82e7-9363c4ee4b21.png)

Is it just word-wrap? Seems to break on the hyphen though.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by justingrayston** [comment]
Does this really need a plunker/codepen? It happens on the demo site (currently 0.11.2).

[Here](https://codepen.io/justingrayston/details/RWVXvj/) is the codepen from the md-toolbar demo itself. I can replicate in the code pen, but it is easier to do using the Chrome emulator.
Select Nexus 5, load the toolbar demo, scroll down in the basic tool bar, notice the pink stops short.

![screen shot 2015-10-07 at 19 58 37](https://cloud.githubusercontent.com/assets/5277488/10347935/4bb6c9fc-6d2e-11e5-8f2d-c71087059bc1.png)
