### ISSUE TITLE
Nested Layout CSS Styles breaks Scrolling on Latest Firefox (38.0.5)

### ISSUE THREAD

**Issue by nkoterba** [angular/material#3113]
**RANT ON** I do not know what the &##^()@#@#$^ the people over at Firefox did, but I live for the future where there's only one browser.  Writing web apps nowadays is like writing for 4 different operating systems that are ~~breaking working apps~~ updating every week.  It's downright insane. **RANT OFF**

Ok, back to the issue at hand.

Simple Code Pen shows the issue the best: http://codepen.io/anon/pen/pJeVWL

Open Link in Chrome, Scroll the text in the blue box on left. Notice how red area/text does **NOT** scroll.

Now open Link in Firefox, Scroll the text in blue box on left.  Notice how red area/text **DOES** scroll and that the scroll bar is way on the right-side of HTML body/window.

This is on Mac OSX.

The oddest thing, is if I remove the `="column"` setting on the first `div`'s layout attribute it works in both FF and Chrome.

Anybody got any idea what's going on here?

(P.S. We have to support ESR versions of Firefox and I can confirm that ESR 31 **works** as expected...haven't looked into ESR 38...but something in Firefox obviously changed).

**Comment by nkoterba** [comment]
As a follow-up, I was using a `DIV` with `overflow: auto` in my previous CodePen.  However, since Material Design would suggest using an `md-content` for scrollable content, I have such updated the CodePen to use `md-content` nested inside several **flexed** divs.

The behavior is the same.  It works on current Chrome versions.

On Current FF versions, the md-content behavior fails: http://codepen.io/anon/pen/XbRYZr

**Comment by sunnyshah01** [comment]
+1

**Comment by topherfangio** [comment]
I've updated your Codepen to use the latest RC2 version and use the `layout-fill` property to fix this. Basically, the height needs to be properly set: http://codepen.io/topherfangio/pen/WQKajB?editors=100

Please post a comment if this doesn't resolve your issue and we will reopen. Thanks!
