### ISSUE TITLE
Meaningful transition for md-list-item

### ISSUE THREAD

**Issue by dohomi** [angular/material#3114]
Hi Guys,

I was looking for the recommended list->detail transition handling for ```md-list-item```

http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFbWM2UGR1SGM2S3M/animation_meaninfultransitions_considerations_do.webm

Is there any thoughts on how to handle this kind of transition? I could add similar behavior with ```md-dialog```but not sure if this would be the right way to go. Thanks

**Comment by dmackerman** [comment]
This would be tricky, and it seems like it's very specific to mobile, right?

**Comment by dohomi** [comment]
Its not mobile only, if you check out inbox.google.com there it look-alike similar to an ```accordion``` or ```expand```. Here is another issue which might be related, with a different usecase / behavior
https://github.com/angular/material/issues/985

**Comment by EladBezalel** [comment]
#110 I think its related
