### ISSUE TITLE
md-autocomplete break style when remote query

### ISSUE THREAD

**Issue by monyprak** [angular/material#3115]
When I enter new keyword the style was broken when waiting reponse data from remote server.
I was facing this problem with latest version 0.9.7

![selection_065](https://cloud.githubusercontent.com/assets/3676934/7976813/4839e0e2-0aab-11e5-8e8a-4bfe4602fb34.png)

**Comment by r0b-** [comment]
+1
same for chips with autocomplete

**Comment by nvanbenschoten** [comment]
+1
