### ISSUE TITLE
md-select add custom classname to md-select-menu-container

### ISSUE THREAD

**Issue by mrmarktyy** [angular/material#3116]
Can we add the ability to add bespoke classname to md-select-menu-container element so that we can customise the style/css of the select dropdown menu ? thanks

**Comment by houmark** [comment]
+1

**Comment by Glinduff** [comment]
+1

**Comment by mrmarktyy** [comment]
grand! thanks

**Comment by sankhadeeproy007** [comment]
Any idea as to how to make this work? Help will be appreciated. Thanks!
