### ISSUE TITLE
md-autocomplete: md-no-cache causes problems when md-items promise resolves immediately

### ISSUE THREAD

**Issue by webley** [angular/material#3117]
I've got an md-autocomplete that has md-no-cache turned on.  If the md-items promise resolves immediately, trying to select an item with the mouse fails, but selecting with the keyboard works.  Resolving the promise inside a $timeout fixes it.  Only a very minor issue but unusual.

Codepen at http://codepen.io/davidwolsey/pen/eNvLQb

**Comment by gustavoaalves** [comment]
+1
