### ISSUE TITLE
md-button: button height and text alignment

### ISSUE THREAD

**Issue by tzachov** [angular/material#3118]
This bug was fixed in 0.9.0 and I've noticed it again in 0.9.7: https://github.com/angular/material/issues/2380

**Comment by topherfangio** [comment]
@tzachov Can you please verify if this is still an issue in master and if so provide a [Codepen](http://codepen.io) demonstrating the problem?

**Comment by tzachov** [comment]
Yes, this issue is still present.
http://codepen.io/tzach/pen/QjbxLR

**Comment by topherfangio** [comment]
When using the `layout` directive, it is also ideal to use the `layout-align` directive to ensure that the children are laid out properly.

Try changing your first `div` to `<div layout="row" layout-align="start center">` and that should fix it.

We'll see if we can update the documentation to make note of this.
