### ISSUE TITLE
md-chips: Can't interpolate: {{$mdChipsCtrl.getPlaceholder()}}

### ISSUE THREAD

**Issue by yelqandili1** [angular/material#3119]
Hi,

I'm trying to use md-chips on my project, but it's not working. I am using the default template from the docs : 
```
   <md-chips ng-model="tags"></md-chips>
```
and on the controller side I have defined tag as an array with two elements :

```
var tags = ['test', 'test2'];
```

Here's the error I'm getting: 
![capture d ecran 2015-06-04 a 12 34 22](https://cloud.githubusercontent.com/assets/2115744/7983229/e7bceab0-0ab5-11e5-939b-103ca8b9dfdb.png)

and here's the result I'm getting :

![capture d ecran 2015-06-04 a 12 39 24](https://cloud.githubusercontent.com/assets/2115744/7983256/4c88498a-0ab6-11e5-971a-a5e8e6947431.png)

I have tried to add a placeholder, updated to master branch and then back to 0.9.4, nothing is working.

Any ideas ?

**Comment by JackForbes** [comment]
I'm running into the same problem and can't figure out why. Modules I am pulling in, in case it helps:   'ui.router', 'ngMessages', 'ngMaterial', 'ngMaterialDropmenu', 'flow', 'ui.date', 'config', 'xeditable', 'ui.calendar', 'ui.date', 'base64', 'config', 'ui.bootstrap', 'restangular', 'angularFileUpload'

**Comment by yelqandili1** [comment]
It seems that It was my mistake, I wasn't assigning tags to the scope ! @JackForbes can you check if you are doing the same thing ?

**Comment by JackForbes** [comment]
Thanks @yelqandili1 it is odd to me that the model has to be instantiated beforehand because that isn't the case for any other input types. Working now nonetheless!

**Comment by ionescho** [comment]
I initiated the tags but it still doesn't work for me... same error

**Comment by yelqandili1** [comment]
Did you check that you have an ng-model on your md-chips  + that your ng-model is instantiated and that it is an array ?

**Comment by ionescho** [comment]
@yelqandili1 Hi. I finally managed to make it work. 
I instantiated the ng-model in my parent controller but that didn't matter as the compile and link function of the md-chip directive is run before the containing controller so my ng-model is undefined anyway. 
The way I managed to fix it was by manually $compile-ing the md-chip directive inside my parent controller after the ng-model was instantiated.
Hope this answer might help another poor soul seeking a solution :P

**Comment by longsangstan** [comment]
I had the same problem but after I put 
``$scope.tags = '';`` 
inside my controller and it works

**Comment by jpolo** [comment]
Same error for me. Concretely, I have an async operation that fetch the model. The md-chips keep crashing until the model is fetched...

**Comment by yelqandili1** [comment]
Exactly you have to initialize your array so that it works properly !

**Comment by timruffles** [comment]
This isn't an ideal error tho!

**Comment by jbrizio** [comment]
To fix this, you can use ``ng-init`` directive to instantiate with an empty value:
```
<md-chips ng-init="tags = []" ng-model="tags"></md-chips>
```
See: https://docs.angularjs.org/api/ng/directive/ngInit

**Comment by unknownguy** [comment]
Might be a little complicated when you have something like: $scope.someObject.Tags

**Comment by christopher-ustb** [comment]
my md-chips can work, but these red error logs in console really make me crazy.
(my ng-model get from server)
any advice?

**Comment by yelqandili1** [comment]
I think initializing you're ng-model with an empty array would work (don't
override it if what comes from the server isn't an array)


Cordialement,

Yassine ELQANDILI
Consultant en Systèmes d'information
http://ma.linkedin.com/in/yassineelqandili

2016-09-27 11:54 GMT+01:00 Christopher.Wang <notifications@github.com>:
