### ISSUE TITLE
md-autocomplete:clear (x on the right margin) should be able to revert to a default value for search-text instead of an empty string

### ISSUE THREAD

**Issue by CxRes** [angular/material#3125]
It should be possible to clear the search field using the cancel button on the right or the Esc key and revert to a default value of search-text instead of a blank field. 

This is needed to simulate the behaviour such as in address bar in web-browsers or the search bar in google.com. The behaviour works as follow:

1. Make a search on google.com/ Open a url in a browser.
2. Append/Alter text on the Search Bar / Address Bar.
3. Press the escape key.

You will find that the original search/URL remain on the bar - we do not get a blank field.

**Comment by marcysutton** [comment]
I agree that the ESC key should clear the field. 

Note that the X button was removed from the tab order on purpose (see https://github.com/angular/material/issues/2212). The thought was that keyboard users have the necessary affordance to select all and delete the contents of the field without the button being reachable.
