### ISSUE TITLE
mdIcon: change alt="" to aria-label=""

### ISSUE THREAD

**Issue by marcysutton** [angular/material#3131]
mdIcon was built to use `alt=""` for text alternatives which seems intuitive since icons are a kind of image, except the `alt` attribute is only effective on the `<img>` element. To properly describe content in a custom tag like `<md-icon>` in the accessibility tree, we must use `aria-label`. This is also more consistent with other text alternatives in Angular Material components.

This depends on @ThomasBurleson's changes to mdIcon to still rely on `aria-label` even with font ligatures, since we can't guarantee 3rd-party font icons will contain readable text.

**Comment by ThomasBurleson** [comment]
`alt` attributes are converted to `aria-label` attributes (unless already present).
If neither are present, then the `element.text()` or `mdSvgIcon`  or `mdFontIcon` are used.
See SHA 525158a5a614e
