### ISSUE TITLE
md-dialog : Two scroll bars are appearing

### ISSUE THREAD

**Issue by chinnichaitanya** [angular/material#3135]
I'm facing the issue of having two vertical scroll bars for a dialog inside which I have a form.
Here is the [codepen](http://codepen.io/anon/pen/BNWgeo).

This is seen in chromium-browser (version - 41.0.2272.76) along with the latest release of angular-material (version 0.9.7).
There is no issue with firefox (version - 38.0) though.

**Comment by stefan-schweiger** [comment]
+1 Still happens in 0.10.0 you can even see in in the md-dialog demo, just open, close and reopen the custom dialog and you will have two vertical scrollbars

**Comment by stefan-schweiger** [comment]
```
md-dialog > form {
    overflow: visible;
}
```

this fixed it for me.

**Comment by jb29** [comment]
I'm having the same issue in `0.10.1-rc1` when I use `md-icon-button` inside `md-actions` div.
Removing the top and bottom margin from the icon button fixes the issue.
```css
md-dialog .md-actions .md-button.md-icon-button {
    margin-top: 0;
    margin-bottom: 0;
}
```
![2015-07-08_13h53_20](https://cloud.githubusercontent.com/assets/13062631/8569684/4b6173a4-257a-11e5-8b03-7666e1642aec.png)

**Comment by pencilcheck** [comment]
This is still happening on 0.10.1

**Comment by ThomasBurleson** [comment]
Using the latest build from [Bower-Master](https://rawgit.com/angular/bower-material/master/angular-material.js), the [CodePen](http://codepen.io/ThomasBurleson/pen/OyJjZq) no longer manifests this issue.
