### ISSUE TITLE
md-dialog does not close clicking outside it

### ISSUE THREAD

**Issue by mighe** [angular/material#3136]
The description says that it is possible to close the dialog clicking outside it; that was the behaviour until 0.8.x. Now it is broken under 0.9.x.

https://material.angularjs.org/latest/#/demo/material.components.dialog

It seems to be browser independent, since it happens either with desktop or mobile environment

**Comment by bhamon** [comment]
Had the same impression at first, but by reading the $mdDialog service doc (https://material.angularjs.org/latest/#/api/material.components.dialog/service/$mdDialog) it seems that this feature is now disabled by default:

```
clickOutsideToClose - {boolean=}: Whether the user can click outside the dialog to close it. Default false.
```

The demo page is not in tune with the default values anymore.

**Comment by mighe** [comment]
@bhamon Thank you! I did not notice that changed default.
The issue is just in the doc in the demo :+1:

**Comment by epelc** [comment]
@mighe Can you close this? It's documented and it was in the [change log](https://github.com/angular/material/blob/master/CHANGELOG.md) several versions ago when they made the change.

**Comment by mighe** [comment]
The [demo](https://material.angularjs.org/latest/#/demo/material.components.dialog) has not been corrected yet
