### ISSUE TITLE
md-tabs programmatic selection of tab not updating pagination

### ISSUE THREAD

**Issue by Stexxen** [angular/material#3139]
When selectedIndex is changed programmatically, the tab is correctly selected and the correct tab content is shown.
But if the tabs are currently paginated and the newly selected tab is on a different page to the one currently shown, then the pagination is not updated, so you have no visibility of the selected tab header.

![bug_before](https://cloud.githubusercontent.com/assets/4494301/8016533/5d61c50c-0bdc-11e5-8e0c-344b5785e064.gif)

**Comment by Stexxen** [comment]
Created Pull to resolve https://github.com/angular/material/pull/3143

**Comment by Stexxen** [comment]
@robertmesserle Could you confirm what version this is fixed in? I've just used bower material commit angular/bower-material@d0bf101a0c6d44ac56047a128c6e2e2249041cef which I believe is 0.10.rc4 and the issue is still present. 
You had previously mentioned it was fixed in the comments of my pull request. #3143

**Comment by robertmesserle** [comment]
Re-opening.  This was fixed in a previous version, but seems to be broken again.  I am working on a proper fix right now for this as well as some other pagination issues.

**Comment by robertmesserle** [comment]
@Stexxen This should be resolved now as well as a few other pagination-related issues.  (ie. resizing the window and adding tabs will also adjust for this.)

**Comment by Stexxen** [comment]
@robertmesserle Confirmed as working in angular/bower-material@1d78f35a17c2acdddd9e3a0bd4f8b797c987f17e

Cheers!
