### ISSUE TITLE
md-autocomplete : clear button (x) is not available on floating label inputs

### ISSUE THREAD

**Issue by ashamnx** [angular/material#3147]
The x button that clears the autocomplete input value is not available when autocomplete is used with floating label inputs.
![screenshot from 2015-06-06 10 45 50](https://cloud.githubusercontent.com/assets/3396812/8018513/735f78ba-0c39-11e5-8300-197739b835fd.png)

**Comment by jlmagee** [comment]
Seems this is intentional. See https://github.com/angular/material/issues/2727

**Comment by mikila85** [comment]
+1

**Comment by vinujosef** [comment]
this will be useful if implemented

**Comment by che85** [comment]
+1

**Comment by GeorgianaSc** [comment]
+1

**Comment by skylee91** [comment]
+1

**Comment by jainpiyush111** [comment]
+1
