### ISSUE TITLE
Tabs data binding

### ISSUE THREAD

**Issue by CosminPOP** [angular/material#3148]
http://codepen.io/anon/pen/mJmELo

How can I access my 'test' outside the tabs directive ?

Cheers

**Comment by Stexxen** [comment]
This may help - http://stackoverflow.com/questions/15305900/angularjs-ng-model-input-type-number-to-rootscope-not-updating.

It also refers to this - https://github.com/angular/angular.js/wiki/Understanding-Scopes

**Comment by CosminPOP** [comment]
Response from stackoverflow helped.

Thanks a lot.
