### ISSUE TITLE
Tabs - next/prev broken

### ISSUE THREAD

**Issue by skeenan** [angular/material#3152]
Tabs Next/prev functionality is broken in 0.9.5 onwards.

**Comment by robertmesserle** [comment]
@skeenan Can you provide more details as well as a codepen?  Closing for now, will reopen when more details are provided.

**Comment by skeenan** [comment]
Fine to close this as is now fixed in master. For the record, to replicate:-

[0.9.8 tabs](https://material.angularjs.org/0.9.8/#/demo/material.components.tabs) 

dynamics tabs box->add tab - left/right arrows appear, but do not function when clicked.

**Comment by chinnichaitanya** [comment]
@skeenan It is working fine. The left-right arrows are functioning properly in 0.9.8

**Comment by skeenan** [comment]
Confirmed once again for myself and absolutely definitely not working for
me. Did you follow my instructions above? Using the link given and adding a
new tab to the dynamic tabs demo?

**Comment by chinnichaitanya** [comment]
@skeenan I've made a screen recording. Please check [here](https://www.youtube.com/watch?v=ORJc8mbDc0Q&feature=youtu.be) and let me know if I did a mistake.

**Comment by robertmesserle** [comment]
There were some pagination issues that were addressed  yesterday that could have been causing this depending on screen size.  Smaller screens were not paginating properly.

**Comment by skeenan** [comment]
Thanks @chinnichaitanya - clearly working for you there. Not me though.

@robertmesserle thanks for the follow-up. Seems to be working in master. This issue is closed.
