### ISSUE TITLE
Font Icons With Ligatures - Sizing example not working in 0.9.8rc1

### ISSUE THREAD

**Issue by skeenan** [angular/material#3153]
In the docs, the sizing example in Font Icons With Ligatures is showing the icons all the same size. 

0.9.7 demonstrated in 5 diff sizes.

**Comment by cebor** [comment]
http://google.github.io/material-design-icons/#icon-font-for-the-web

you have to setup some css rules, to get this working.

**Comment by skeenan** [comment]
Thanks I know this. My point is that, in the docs, it is not working in 0.9.8rc1 when it was was demonstrated as working in 0.9.7.
