### ISSUE TITLE
impossible to create radio repeater

### ISSUE THREAD

**Issue by z3v0k0d3** [angular/material#3155]
Impossible to create radio repeater is required a container group, please go to http://plnkr.co/edit/MagR0nQLjNpXQYRAfaGm?p=preview

**Comment by marcysutton** [comment]
Hi, you need to put `md-radio-group` outside of the repeater. There should only be one per radio group, that is why they aren't linked. You have two separate radio groups.

**Comment by Z3V0K0D3** [comment]
Error: http://errors.angularjs.org/1.3.15/$compile/ctreq?p0=mdRadioGroup&p1=mdRadioButton

code: http://pastie.org/10230556

help me, where insert the mdRadioGroup ??

**Comment by dyapasrikanth** [comment]
Yes, I am also getting same error, why we should tightly bind these two (radioGroup & radioButton) directives together. Unable to place them in table. Please help me.

**Comment by ThomasBurleson** [comment]
Here is a working Plunker: http://plnkr.co/edit/A5jHTO722PgjiTp3bboU?p=preview

> Currently the RadioButton directive (mdRadioButton) tries to locate the required controller by searching only the element and its parents. With ngRepeat between the RadioButtonGroup and RadioButton, this throws an error.

**Comment by dyapasrikanth** [comment]
I want to place radio button in each row of table & want to select anyone of them. This is not working. No idea about isolated scope....

**Comment by ThomasBurleson** [comment]
@dyapasrikanth - you want a **single** radio button in each row? So the entire table is a group?

**Comment by ThomasBurleson** [comment]
![mdradiogroup as table](https://cloud.githubusercontent.com/assets/210413/9721134/5425538c-555b-11e5-9235-6bc4627d83e3.png)

```html
  <h1>Contact List</h1>
  <md-divider></md-divider>
  
  <md-radio-group ng-model="cc.selectedIndex" >
    <div ng-repeat='person in cc.contacts' class="row">
      <div flex layout='row' layout-padding layout-align="start center" >        
        <div flex style="max-width:200px;">
          {{person.title}}
        </div>
        <md-radio-button  ng-value="person.id" class="md-primary" >          
          {{person.fullName}}          
        </md-radio-button>        
      </div>
    </div>
  </md-radio-group>

  <md-divider></md-divider>
```
> Live Demo and Source Code on [Plunkr](http://plnkr.co/edit/gzgnhrcep2csk9vuHyeY?p=preview)

**Comment by JoeKahl** [comment]
Has material design radio button group and radio button been enhanced to support going across rows of a table?  I want to attempt this and my experiments are not working.
