### ISSUE TITLE
dropdown menu of online docs not working

### ISSUE THREAD

**Issue by vineey** [angular/material#3157]
using latest chrome in android jellybean 4.4.2, clicking the dropdown buttons in the side menu of the online docs is not showing the dropdown menu down. thus cant navigate easily.

**Comment by WhiteAbeLincoln** [comment]
I'm also seeing this on chrome and firefox, android 4.4.4. I already opened an issue (#3146) 2 days ago, so this is a duplicate.

**Comment by WhiteAbeLincoln** [comment]
This is fixed in 0.9.8, issue was in 0.9.8-RC1. This issue can probably be closed
