### ISSUE TITLE
md-slider is not working. It renders on page but doesnt slide.

### ISSUE THREAD

**Issue by Priyankad19** [angular/material#3159]
Using md-slider but its not working. It renders on page but does not slide. You can check the issue on plunker http://plnkr.co/edit/PZ92UHvFwwj72Y4PMHR6?p=preview  

Can you please help me in resolving this?

**Comment by mukilane** [comment]
You must enclose the 'quiz.max' and 'quiz.min' within double braces. 
Here is the corrected example. 
http://plnkr.co/edit/aTHsiWk6sZBGpwbkQpEZ?p=preview

**Comment by Priyankad19** [comment]
Thanks Mukil, its working now.
