### ISSUE TITLE
[master] md-autocomplete progress bar doesn't turn off after selecting an item

### ISSUE THREAD

**Issue by sheaujye** [angular/material#3162]
When "item in items" return promise.

**Comment by sheaujye** [comment]
Can be replicated on demo @ https://material.angularjs.org/latest/#/demo/material.components.autocomplete

**Comment by vlopez5** [comment]
I have the same issue here. But if I use the keyboard to select an item, then works great.

I think there is an issue with the mouse event.

**Comment by vlopez5** [comment]
Actually, i realize that has something to do with the .focus() event that is fired when the mouseup.

I think that the focus event should be revised.

**Comment by mikedobrin** [comment]
I experience the same problem. My items are comming from the server and the progress bar never stops even though I selected something with my mouse. Works like a charm with a keyboard thou.

**Comment by rodrigotm** [comment]
+1

**Comment by leonardomonteiro01** [comment]
+1

**Comment by marcosdocanto** [comment]
+1

**Comment by allbto2** [comment]
+1

**Comment by robertmesserle** [comment]
Closed by 7314e12dc7ba73406aafc09aa5d8455f1de4495c
