### ISSUE TITLE
Enhancement Request - md-input-container styling in toolbar / fullwidth text input

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3163]
I'd love to be able to use the md-input-container directive in the toolbar and get a similar effect to that shown in google inbox...

![screen shot 2015-06-08 at 05 50 42](https://cloud.githubusercontent.com/assets/1916471/8028309/55fa6f04-0da2-11e5-8f66-dddf25e3ffea.png)

**Comment by topherfangio** [comment]
@hodeyp Are you just wanting the styling to be available, or is there some additional functionality too?

**Comment by hodeyp** [comment]
@topherfangio I think the styling is the most important thing to get out there, if an md-input-container is put into a toolbar the current floating label styling really doesn't work. I think at a minimum the styling should be similar to that of google inbox as shown above. Longer term I think there is mileage in looking at expanding buttons similar to what I have seen before where only the icon is visible, then when clicked the input is displayed, maybe with an animated width from 0 to container width.

**Comment by dohomi** [comment]
+1 I think a search input field inside of ```md-toolbar```should be available inside of the docs. Its mainly just stylesheets, no additional logic is needed.

**Comment by JA44** [comment]
+1

**Comment by EloB** [comment]
+1

**Comment by dcarrask** [comment]
+1

**Comment by redcomethk** [comment]
+1

**Comment by leocaseiro** [comment]
+1

**Comment by clrech** [comment]
+1

**Comment by topherfangio** [comment]
Rather than posting `+1`s, can you please use the new [GitHub reactions feature](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) :-)

**Comment by Xeoncross** [comment]
Why was this issue closed?

**Comment by leocaseiro** [comment]
Probably, the same as the [8330](https://github.com/angular/material/issues/8330#issuecomment-223210019)

> This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
> For details, see our forum posting @ http://bit.ly/1UhZyWs.
