### ISSUE TITLE
inputs. md-no-float, placeholder is not displayed in IE11 or Firefox

### ISSUE THREAD

**Issue by kamarouski** [angular/material#3164]
When using md-input-container with md-no-float and without a label input placeholder is not displayed in IE11 or Firefox.

To reproduce open input demo page in IE11 or Firefox. In icons section Phone Number placeholder is not displayed in IE11 or Firefox

https://material.angularjs.org/latest/#/demo/material.components.input

**Comment by Splaktar** [comment]
Dup of #2162
