### ISSUE TITLE
md-select with explicit label doesn't show selected value

### ISSUE THREAD

**Issue by stevenmiles** [angular/material#3168]
md-select with an explicit label using md-select-label doesn't show the selected value. It only ever displays the text in the label regardless of the selected value. I was trying to work around #3167 by defining an explicit label and putting flex on it when I discovered this issue.

http://codepen.io/stevenmiles/pen/ZGKoyr

**Comment by Sennahoi** [comment]
I saw this workaround:
http://codepen.io/anon/pen/BNRbBq

**Comment by stevenmiles** [comment]
@Sennahoi thanks for the work around. Was very helpful.

**Comment by Anthropic** [comment]
With an explicit label I feel it should show both the label and the value, there is an option for that layout in the Material design spec under [simple menus](http://www.google.com/design/spec/components/menus.html#menus-simple-menus) such as the "When device is locked" example showing both that text and "show all notification content".

Alternatively it would work for an attribute for an always displayed title to be provided.

**Comment by stevenmiles** [comment]
Closing this task as md-select-label has been removed and replaced with the ability to put an md-select inside and md-input-container to show an external label.
