### ISSUE TITLE
First md-on-select not called after load

### ISSUE THREAD

**Issue by jo-me** [angular/material#3169]
As described in a comment in #2730, the md-on-select is not called when the tabs are initially displayed. 

Can be reproduced in my plnkr that i created for #2730 :  http://plnkr.co/edit/DorMcJAmkuFpVG6wTBaj?p=preview

The "Last log" row at the bottom should display "Last Log: One selected" because the first tab is automatically selected. 

It may be related to the tabs being created by ng-repeat.

**Comment by jo-me** [comment]
The event is still not coming if the tabs are created asynchronously.

http://plnkr.co/edit/qpAPFBFOPBs6pnaiR1nH?p=preview

Probably related to #3264 .

**Comment by jamm** [comment]
Please create separate event, don't fire on-select when user doesn't select anything.

**Comment by jo-me** [comment]
If a tab is automatically selected, some event is necessaray to allow dynamically creating/loading the tab content.

**Comment by ramirezd42** [comment]
This is still an issue for me. Angular Material does the job of changing the state of my tabs by selecting the first one. I don't see why that state change should be any different than one initiated by a user.
