### ISSUE TITLE
Use ngTouch instead of Hammer.js

### ISSUE THREAD

**Issue by iasandcb** [angular/material#317]
I suggested Hammer.js first, but found that ngTouch seems like an "official" one.

https://docs.angularjs.org/api/ngTouch

Currently Hammer.js is used to support swiping in angular material, so ngTouch could do. Is there any reason to adopt Hammer.js over ngTouch?

**Comment by gitarno** [comment]
@iasandcb  Complementing, as if studying this new implementations of gestures like swipes and drags the Hammer of more support. Correct @ThomasBurleson !?

**Comment by ThomasBurleson** [comment]
Fixed with $mdGestures. 6e3ddb855de249196bfdf7244f8937d9dd9f5b5e
