### ISSUE TITLE
md-tabs in md-dialog causes lots of errors in ie11

### ISSUE THREAD

**Issue by hanthomas** [angular/material#3178]
This problem occurs in IE11.  You have to have the debug tools open to see the errors generated in the console.  The following plunkr demonstrates the problem:

http://plnkr.co/edit/Ilxgqv?p=preview

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
