### ISSUE TITLE
Sidenav : Is there a way to call a callback on escape or backdrop close ?

### ISSUE THREAD

**Issue by mfilotto** [angular/material#3179]
Hi,
I have an ui-view in my sidenav and I'd like to reset the router path when the user click outside the sidenav (on the backdrop) or press escape.
Is there a way to do so ?
Thanks for your help

**Comment by sylviefiat** [comment]
+1
Any idea ?

**Comment by jameswyse** [comment]
:+1: I need to save changes when the sidenav is closed and I don't see any way of doing that? Currently i'm using `ngClick` on the close icon - but it doesn't work for esc/backdrop close :/

**Comment by sylviefiat** [comment]
Here is the workaround we use for now: You can use [#974](https://github.com/angular/material/issues/974) and bind a function to your sidenav component in your controller
```javascript
this.isOpen = function() { return false };
// Register bindnig function
$mdComponentRegistry
            .when("yoursidenav")
            .then( (sideNav)=>{
                this.isOpen = angular.bind(sideNav, sideNav.isOpen );
 });
```
And then add a watch on this function:
```javascript
$scope.$watch("myController.isOpen()",(newValue,oldValue)=>{
	    // save your changes here
},true);
```

**Comment by jameswyse** [comment]
Thanks for the workaround @sylviefiat!

**Comment by george3447** [comment]
+1

**Comment by ThomsC** [comment]
Or

```javascript
$scope.$watch(
            function() { return $mdSidenav('yourSide').isOpen(); },
            function(newValue, oldValue) {
                console.log(newValue);
            }
        );
```

**Comment by mathiasmoeller** [comment]
+1

**Comment by mfilotto** [comment]
@EladBezalel Hi any update on this one ?

**Comment by EladBezalel** [comment]
@mfilotto waiting for merge .. :)

**Comment by peffreycollins** [comment]
+1

**Comment by shivalthaker** [comment]
Was just wondering, how can we use this fix when we want to capture whenever we click on backdrop or press esc key. I know how to use the $scope.$watch but still feel like using this fix somehow for the project. (y)
