### ISSUE TITLE
Drag-panning for tab views (and others) 

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#318]
Similar to the Mobile UX, tabs needs to support drag-panning of views. 

While dragging the tab view area, the previous or next view needs to be seamlessly connected (on left or right side respectively). And partial views of the next/previous view will be available until the drag/pan is released; at which point the appropriate view will snap into place (current or next for panleft, current or previous for panright). The selected tab will not switch until the pan is released.

This UX (and feature) should be applicable to other view scenarios outside of Tab usages.

**Comment by matthiasg** [comment]
i assume this is meant to behave similar to how the android store implements its tab strip on the top (the categories filters) ? 

i.e tabs are listed as one line .. overflow out-of-canvas and can be dragged left/right BEFORE clicking ?

**Comment by matthiasg** [comment]
similar to this the md-tabs should live scroll and not scroll after the touch gesture is completed. this is really unintuitive since the latency involved makes people not understand what actually happened
