### ISSUE TITLE
My site based on Angular Material design is corrupted in PhantomJS

### ISSUE THREAD

**Issue by morozserg** [angular/material#3180]
If try to make a screenshot of official Angular Material site (as well as mine) visualization is corrupted (see attached). 
Phantomjs version: 1.9.8

```js
var page = require('webpage').create();
page.viewportSize = { width: 1280, height: 900 };

page.open('https://material.angularjs.org/latest/#/demo/material.components.button', function() {
	 window.setTimeout(function () {
           page.render('AngularMaterial.png');
            phantom.exit();
        }, 1000);
});
```
Errors: Side navigation is not visible, toolbar panel is not visible etc.
Result:
![angularmaterial](https://cloud.githubusercontent.com/assets/10244619/8055569/254f64b0-0ea9-11e5-8cc4-a6c756f84b0a.png)

Expected: 
![angularmaterialorigin](https://cloud.githubusercontent.com/assets/10244619/8055675/ef814884-0ea9-11e5-867c-2e91ca7e020b.jpg)

**Comment by qrpike** [comment]
Any updates on this?

**Comment by schwimmfuzzi** [comment]
sill, any news?

**Comment by faisalAvizia** [comment]
Any updates on this??
