### ISSUE TITLE
md-contact-chips add md-highlight-flags

### ISSUE THREAD

**Issue by schmkr** [angular/material#3182]
When the search function bound to the `md-contacts` attribute is case insensitive (like the example in the documentation), the `md-highlight-text` in `MD_CONTACT_CHIPS_TEMPLATE` is still case sensitive. It would be great if it was possible to define the `md-highlight-flags`.

**Comment by Frank3K** [comment]
+1

**Comment by leocaseiro** [comment]
I took a while to find out how works, set **md-highlight-flags="i"**

Eq:
    <span md-highlight-flags="i" md-highlight-text="searchText">{{label}}</span>

**Comment by adminarun** [comment]
<h1>How to use the multiple md-autocomplete </h1>
<p>With a json data example</p>
