### ISSUE TITLE
Changing route does not change the selected md-tab

### ISSUE THREAD

**Issue by bastienJS** [angular/material#3183]
plunker for repro: http://run.plnkr.co/UTQdFYz1a3erJ7JC/#/tabs/tab1

Your latest 0.10.RC1 is used.

Change the route to /tab2 

and you will see that only the content changes but not the selected tab.

From an enduser perspective I expect this case to work correctly.

**Comment by bastienJS** [comment]
I found a workaround with the md-acitve directive:

http://plnkr.co/edit/k5eObdPwmi9UkAnjo7Tp?p=preview

**Comment by epelc** [comment]
You need to manually handle this in your application logic.

**Comment by robertmesserle** [comment]
As @epelc said, you would have to handle this in your application logic.
