### ISSUE TITLE
md-list-item: 'md-2-line' and 'md-3-line' long paragraph deviate from material design spec

### ISSUE THREAD

**Issue by CxRes** [angular/material#3185]
According to the material design spec http://www.google.com/design/spec/components/lists.html#lists-specs:

'md-2-line' should have a height of 72px. Currently, this is 75px (tested with codepen demo example on chrome 43);
'md-3-line' when the long paragraph collapses should be 88px. Currently this is 96px;

Also, the alignment with respect to the avatar seems a bit off, because the padding for text deviates from the spec.

**Comment by marcysutton** [comment]
PRs are welcome!

**Comment by topherfangio** [comment]
I believe these have both been fixed in master.

If you still see the issue after upgrading; please comment and I will reopen.
