### ISSUE TITLE
Please support md-icon inside md-avatar

### ISSUE THREAD

**Issue by CxRes** [angular/material#3186]
Currently, if I want to have an icon inside an avatar, I have to align it manually.

I believe this should be supported within angular material because this example is defined in the material design spec. See section Tile Content in  http://www.google.com/design/spec/components/lists.html#lists-content

**Comment by ajd394** [comment]
I ran into this issue too!

**Comment by ThomasBurleson** [comment]
A Pull Request to submit this feature would be welcomed.

**Comment by CxRes** [comment]
Thanks!!! Just in time for me to use...

**Comment by EladBezalel** [comment]
@CxRes np :)
