### ISSUE TITLE
$mdDialog bug using template vs. templateURL

### ISSUE THREAD

**Issue by nikkwong** [angular/material#3191]
I have two, almost identical scripts calling a ```mdDialog``` via ```mdDialog.show```. One of which, uses an inline template, the other, which references a templateUrl. The one that uses the inline template, throws a ```i.hasAttribute is not a function``` error—while the other one works just fine.

Not working (inline template)

http://plnkr.co/edit/m6HDhrgcVlXumwDhyQYu?p=preview

Working (templateUrl)

http://plnkr.co/edit/955VxMkBjPy5DvmQjIg0?p=preview

Known bug? 

Just to note—this bug isn't plnkr specific, it's happening to me locally as well. Thanks!

**Comment by GuyShaanan** [comment]
+1
Also having the same problem with $mdDIalog and templateUrl:
The following lines (22-26) from material/src/core/services/aria/aria.js in tag 0.10.1 might shed some light:
```
function expect(element, attrName, defaultValue) {
    var node = element[0] || element;

    // if node exists and neither it nor its children have the attribute
    if (node &&
       ((!node.hasAttribute(attrName) ||
        node.getAttribute(attrName).length === 0) &&
        !childHasAttribute(node, attrName))) {
````
In my case, `element` is an empty array ([]), so after
```
 var node = element[0] || element;
```
node is an *empty array itself*, and the expression `if(node)`, where `node` is an empty array, evaluates to **true**.

**Comment by smashercosmo** [comment]
Just faced the same issue. Dialogs with inlined templates simply don't open, because of js error. 
@ThomasBurleson why it's in the backlog? Seems pretty critical to me.

**Comment by ThomasBurleson** [comment]
@GuyShaanan - your comment is helpful. 
@smashercosmo  - some items are in the backlog because the team is simply work at maximum capacity with other issues. Nevertheless, with the above information, I think this can be quickly resolved.

**Comment by jrgleason** [comment]
I seem to still have an issue when I am using a templateUrl to an item in the template cache vs a physical file. Is there a separate process?

**Comment by Splaktar** [comment]
@jessekoconnor no, this was fixed in https://github.com/angular/material/commit/22c34badbcac032543210218d6caaacfb96de1f6 as part of `0.11.0`. Please take a look at the restrictions section of this doc: https://material.angularjs.org/latest/api/service/$mdDialog.
