### ISSUE TITLE
Menu not working in 0.10.0-RC2

### ISSUE THREAD

**Issue by mukilane** [angular/material#3197]
The menu is not opening in the 0.10.0-RC2 version. It worked in the RC1 though.

**Comment by jgoux** [comment]
+1
The error is : 
`Uncaught TypeError: Cannot read property 'firstElementChild' of undefined` when I click on the button.
See here : https://material.angularjs.org/HEAD/#/demo/material.components.menu

**Comment by kschwidder** [comment]
+1

**Comment by roblav96** [comment]
+1

**Comment by patapron** [comment]
+1

**Comment by jozsi** [comment]
+1

**Comment by idoco** [comment]
+1

**Comment by opadillaintegrify** [comment]
+1

**Comment by Alexandre-io** [comment]
+1

**Comment by roblav96** [comment]
barhaleacct commented 12 hours ago
function positionMenu(scope,el, opts) {
Just add scope back in as above, it is missing in the RC2 release, but in the RC1 release, works as intended once done
