### ISSUE TITLE
Tabs are not centered

### ISSUE THREAD

**Issue by florent1933** [angular/material#3198]
Hi,

Tabs are not centered with **md-center-tabs** since 0.9.6 though.

http://codepen.io/anon/pen/doRPLb

**Comment by yarl** [comment]
You should provide more information about OS and browser. It looks good on latest Chrome and Firefox on Windows. IE10 however displays tabs on the left.

**Comment by florent1933** [comment]
Sorry,

I use Safari Version 8.0.6 and I have OS X Yosemite Version 10.10.3
