### ISSUE TITLE
Navbar fixed at the top

### ISSUE THREAD

**Issue by infacq** [angular/material#3202]
Need a navbar like this website 

http://www.materialup.com

and a FAB on the right. and also how do I get the nice shadow appear when scrolldown the page like this

https://www.polymer-project.org/1.0/

**Comment by cebor** [comment]
This should fix the toolbar:

```html
<div layout="column">
  <md-toolbar>
    ...
  </md-toolbar>
  <md-content flex>
    ...
  </md-content>
</div>
```

**Comment by himanshushankhala** [comment]
@cebor  Thanks for the solution it worked!

**Comment by cbdtn** [comment]
http://codepen.io/kpgarrod/pen/vEOLBd/

**Comment by dyutibarma** [comment]
All these solutions seem to make the mobile browser's address bar also sticky. (verified on chrome/opera on android). Anyone else facing these issues? Any workarounds?

**Comment by BrunoGiubilei** [comment]
@dhamothy its so hard to copy and paste... can u share a link, or documentation for this?

**Comment by dhamothy** [comment]
@BrunoGiubilei Codepen demo I made for you. http://codepen.io/dtn/pen/eBvbWo . Let me know if any. Have a good day.

**Comment by BrunoGiubilei** [comment]
thanks man! you save me

**Comment by Rogerkael** [comment]
It works on webkit browsers, but it doesn't on firefox.

**Comment by giulioprinaricotti** [comment]
@Rogerkael the codepen works for me on Firefox 54.0 (64bit) for OSX
