### ISSUE TITLE
md-menu: saves position on first opening and does not position according to target item on windows resize

### ISSUE THREAD

**Issue by kschwidder** [angular/material#3204]
Problem:
It seems that md-menu is saving the internal absolute position from the first opening instead of the current item. Therefore on resizing the window the menu is misaligned with the target.

Scenario:
1) Open md-menu and close it again.
2) Resize window to min or max.
3) Open md-menu again. It will show up according to the first absolute position and not according to the given target

**Comment by jozsi** [comment]
+1

**Comment by DaveRevay2** [comment]
Additionally, if you scroll the menu stays fixed on the screen and does not scroll:
http://i.imgur.com/1JxnbVu.png - view when not scrolled
http://i.imgur.com/OcT5A6l.png - after scrolling

The position of the 'md-open-menu-container' should be changed to absolute?
