### ISSUE TITLE
multiple md-tabs not working since v0.9.7

### ISSUE THREAD

**Issue by GautierThiriez** [angular/material#3206]
Hi, since v0.9.7 i have some weird issue with md-tabs.
Works perfectly with v0.9.6.

v0.9.7 -> master
![capture d ecran 2015-06-10 a 16 37 22](https://cloud.githubusercontent.com/assets/6089653/8085223/4e44f466-0f8f-11e5-980a-0b865c88a466.png)

v0.9.6
![capture d ecran 2015-06-10 a 16 37 12](https://cloud.githubusercontent.com/assets/6089653/8085248/69550142-0f8f-11e5-9a67-45b91f7162a0.png)

**Comment by chinnichaitanya** [comment]
A codepen might be helpful.

**Comment by GautierThiriez** [comment]
here is it : https://github.com/angular/material/issues/3166

v0.9.6 (working) : http://codepen.io/GautierThiriez/pen/GJEEdY
v0.9.7 (not working) : http://codepen.io/GautierThiriez/pen/VLWWxX
master (not working but different behavior) : http://codepen.io/GautierThiriez/pen/oXwwdp

**Comment by robertmesserle** [comment]
@GautierThiriez Excellent find, I am adding a fix for this right now.
