### ISSUE TITLE
mdContent: don't get 100% of height

### ISSUE THREAD

**Issue by aderbas** [angular/material#3207]
I have a problem at the height of the md-content. My app has ng-view and it is 100% of the page, but the md-content don't get 100% of parent. Look that result:

```html
<ng-view flex class="md-padding">
     <md-content flex> foo </md-content>
</ng-view>
```
I try put style="height: 100%" but not work.

![problem-md-height](https://cloud.githubusercontent.com/assets/12519019/8085911/1bdcff6c-0f69-11e5-9af8-d2e362ff10ac.jpg)

I've tried the issues but found that solved my problem.

**Comment by cebor** [comment]
try this, and i think you using `ng-view` wrong
```
<ng-view layout="column">
     <md-content flex layout-padding> foo </md-content>
</ng-view>
```

**Comment by aderbas** [comment]
I'm using this in index.html

```html
<body layout="column" ng-controller="IndexController">
    <div layout="row" flex> 
        <md-sidenav>...</md-sidenav>
        <ng-view flex class="md-padding"></ng-view>
    </div>
</body>
```
I'm using ngRouter and my "main.html" like this:
```html
<md-content flex> foo </md-content>
```
I think it was not so clear before, sorry

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. 

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by ThomasBurleson** [comment]
@aderbas - you must specify the `height` of the mdContent:

![screen shot 2015-09-07 at 8 35 57 pm](https://cloud.githubusercontent.com/assets/210413/9724572/109888c4-55a0-11e5-8301-7e9d3c642c95.png)


> Demo and Source: http://codepen.io/team/AngularMaterial/pen/BNYppz

**Comment by akomm** [comment]
Someone set the angular-material links/scripts to be fetched from localhost:8080/*, rendering the demo non-functioning. You have to lookup for a CDN for both CSS and JS of angular-material to make the demo work again.

**Comment by Mg-Yaya** [comment]
Test this trick : 
```html
        <div layout="row">
	  		<div layout="column">
	  			<div flex> Content1 </div>
	  			<div flex> Content2 </div>
	  		</div>
	  	</div>
```

**Comment by ThomasBurleson** [comment]
@Mg-Yaya - Your sample has several issues that you must address:

*  You must include 'ngMaterial' as a module dependency
*  You must set the height of the outer-most `layout`
*  You must `flex` the nest layout

![screen shot 2015-12-05 at 9 33 58 am](https://cloud.githubusercontent.com/assets/210413/11608600/7c521778-9b33-11e5-8bbc-301f78ba4dda.png)

[CodePen Demo](http://codepen.io/team/AngularMaterial/pen/xZxzvO?editors=101)

**Comment by ThomasBurleson** [comment]
Here is the [Layout Collection](http://codepen.io/collection/XExqGz/) @ our Angular Material CodePen Community

**Comment by Mg-Yaya** [comment]
@ThomasBurleson  - I want to make tabs and a menu side by side, is it possible without using position proprety in css.
![sc1](https://cloud.githubusercontent.com/assets/14295330/11613049/2c477b34-9c13-11e5-8586-94aa719e3358.png)

**Comment by guillaume250** [comment]
Solution: 
You're using Angular-material, all you have to do is adding the **layout-fill** attribute to all parents of the elements you want to fill vertically, starting from <ng-view>.

<ng-view layout-fill>
     <md-content layout-fill> foo </md-content>
</ng-view>

jfyi: ng-view will in henrit the the full height of your page's body.
