### ISSUE TITLE
Feature Request - md-tall toolbar resizing into normal height on scroll

### ISSUE THREAD

**Issue by mukilane** [angular/material#3208]
A md-tall toolbar (with text at bottom) on scrolling will shrink into a normal toolbar (with text moving to the top).
This is a well know feature in material design. 
Here is an example : www.google.com/design/spec/material-design/introduction.html

**Comment by piyushchauhan2011** [comment]
Yep we want this feature too.

**Comment by dondoco7** [comment]
+1

**Comment by EladBezalel** [comment]
#1054 Dup.

**Comment by PawelOwczarekFalcon** [comment]
I need this feature

 :+1:
