### ISSUE TITLE
md-tabs: feature request for unselected Mode

### ISSUE THREAD

**Issue by kschwidder** [angular/material#3212]
Problem:
md-tabs can not have an unselected state which is desired when navigation via a sidenav element i.e.

Scenario:
At the top a main navigation is available via tabs with 3 tab items.
A left md-sidenav contains links which are linking to additional pages.
When the user selects the md-sidenav item he will get into specific page which is not aligned with the proposed md-tabs elements. Therefore it should be visually possible to unselect the md-tabs. Otherwise the user gets the impression that his selection is part of the selected tab ! 
This is not a desired UX.

**Comment by vlasenko** [comment]
+1

**Comment by jo-me** [comment]
I've realized something like that using just the md-list component with one special ng-class for the selected item.

**Comment by robertmesserle** [comment]
This should be resolved here: https://github.com/angular/material/commit/27783df93e0ebc27ef20df72d240a3b4cb762d77

Setting an initial value for `md-selected` of `-1` will result in no tab being selected.
