### ISSUE TITLE
Angular Material and ngMock/ngMaterial-mock breaks Angular digest loop

### ISSUE THREAD

**Issue by gerhardboer** [angular/material#3215]
When trying to test an angular-material app with protractor, i came across a problem where the  Angular digest loop breaks when importing the ngMock module.

I've created a small project using npm, bower and grunt to demonstrate the problem:
https://github.com/gerhardboer/material-mock-problem

As soon as the ngMock module is used as a dependency, angular stops after 1 digest loop.
When the ngMock module is not injected, the digest loop runs as expected and the controller values are parsed.

**Comment by ThomasBurleson** [comment]
Protractor support will be implemented in post 1.0 releases.
