### ISSUE TITLE
md-menu positioning problem

### ISSUE THREAD

**Issue by rtpm** [angular/material#3218]
Not sure if anyone can reproduce this problem.
I have a simple website with md-toolbar (with 'fixed' positon).
Clicking the last  (icon-more_vert) button in each row works fine only for rows that are seen on initial page load. It goes wrong for rows at the bottom appearing after scrolling down the page.

![3](https://cloud.githubusercontent.com/assets/146247/8103641/4ee7ddb6-102a-11e5-9083-c7ae909f14fc.png)

![2](https://cloud.githubusercontent.com/assets/146247/8103501/3d060fe2-1029-11e5-8ee0-acb8fc5a202e.png)

Angularjs 1.4.0 & angular-material 1.0.0-rc1 (in rc2 menus do not work).

This may be related to issue  #3204

**Comment by rschmukler** [comment]
@rtpm can you try using `HEAD`. I suspect that the commit above (94b03b0) will fix this issue, but if not let me know!

**Comment by rtpm** [comment]
Using the latest master I see no change (Tested on latest chrome). Checked again on firefox where clicking the first from the bottom of the page button (page scrolled down) scrolls the page up showing the menu at the bottom.

**Comment by plato-cambrian** [comment]
We saw this with ng-tooltip on a chatlog history, and worked around it with a jquery plugin...

**Comment by houmark** [comment]
I'm seeing the same issue when scrolled down a page, the menu will break when click (and prevent the page from allowing scroll until you click anywhere on the page again).

**Comment by DaveRevay2** [comment]
Still not working in 10.0 master
See example here:
http://codepen.io/anon/pen/waqrao

**Comment by rgolea** [comment]
+1

**Comment by peluprvi** [comment]
I have some error here which can be related to that.
When I opening some menu for a second time, the top distance is added with the new calcs. So, every click the menu goes down until the limit of the window.

I tried to reproduce that error on Plunker, but I have no success.
That is my current layout: http://plnkr.co/edit/emNIILRuID1D4Ri6ai7C?p=info

Maybe is something in my app...

**Comment by animesh1987** [comment]
+1

**Comment by rschmukler** [comment]
Fixed the situation that @DaveRevay2 provided a codepen for. Not sure if that's the same issue that @rtpm is experiencing. @rtpm if you give me a code pen to work off of I can make sure this is working for you

**Comment by DaveRevay2** [comment]
Thanks @rschmukler.
Seems to work well. There is one little bug I noticed...
I was using the following styles on the body (I do not use md-content) to force a scrollbar in the y-directions.
```
body{
  overflow-y: scroll;
  overflow-x: hidden;
}
```
These had to me removed to make use of your fix, otherwise the content does not overflow correctly.

See the pen of this behavior here. http://codepen.io/anon/pen/BNJJEM

**Comment by adriendomoison** [comment]
The probleme for me come from the "height 100%" property of body in angular-material.css, when I disable it, it works correctly, if I don't, I have this bug too.

**Comment by atinder90** [comment]
@adriendomoison thanks. this resolves it for now.

**Comment by vivekimsit** [comment]
Hi, there should be some way to give alternate parent element to the directive at present it assumes `body` to be the default parent.

PS: I am experiencing the same issue when I scroll down and open the menu.

**Comment by vivekimsit** [comment]
Seems the issue is resolved after this commit. 044dbdc358069586bb19e2b2b07de5d56f8ce35b

**Comment by rtpm** [comment]
Yup. Thanks for the fix!
