### ISSUE TITLE
mdFabSpeedDial - Missing the "md-fab-bottom-right" to put it in the bottom right corner

### ISSUE THREAD

**Issue by carab** [angular/material#3220]
Hello everyone,

Using a simple md-fab button, we are able to place it in the bottom right corner by using "md-fab-bottom-right" class.

It would be nice if it was also possible for the mdFabSpeedDial component without writing custom CSS.

Thank you,
Carab.

**Comment by EladBezalel** [comment]
:+1:

**Comment by robertbaker** [comment]
It needs to support all of the position classes.

**Comment by ajd394** [comment]
does anyone have a good workaround for this in the mean time?

**Comment by topherfangio** [comment]
You should be able to use absolute positioning to put it anywhere on the page that you want. Something like this should work:

```html
<style>
#my-speed-dial {
  position: absolute;
  bottom: 20px;
  right: 20px;
}
</style>

<md-fab-speed-dial id="my-speed-dial" class="md-fling">
  ...
</md-fab-speed-dial>
```

**Comment by ajd394** [comment]
you were right! 
this link describes it in detail 
https://groups.google.com/d/msg/ngmaterial/j-Jovmag2NA/aSce1Sp-CAkJ

**Comment by robertbaker** [comment]
Should be straight forward, is there a reason why this isn't done yet? @topherfangio 

```
md-fab-speed-dial.md-fab-bottom-right {
    top: auto;
    right: 20px;
    bottom: 20px;
    left: auto;
    position: absolute;
}

md-fab-speed-dial.md-fab-bottom-left {
    top: auto;
    right: auto;
    bottom: 20px;
    left: 20px;
    position: absolute;
}
```

**Comment by topherfangio** [comment]
@robertbaker Honestly, just been a bit busy as one of my contracts is coming to a close :-)

Also wanted to check if there were any top positions I needed to support, and I haven't had a chance to look. Will do so tonight.

**Comment by topherfangio** [comment]
I have a PR (#3693) to fix this that should be merged soon.

**Comment by carab** [comment]
Glad to hear that ;)

**Comment by listepo** [comment]
+1

**Comment by topherfangio** [comment]
@listepo This is now available in master.
