### ISSUE TITLE
where's date time picker ?  and some issue with  <md-icon> 

### ISSUE THREAD

**Issue by minhdh52** [angular/material#3222]
1. I can't find date time picker in angularness material.
2. I create an input form(like attach image) with md-icon and md-select , md-autocompete in md-input-container,
![input-form](https://cloud.githubusercontent.com/assets/12843531/8104534/b08d90d4-105b-11e5-8a21-84395f3f54d3.png)
my code:  

                <md-input-container>
                    <label>{{class.label.class_name}}</label>
                    <md-icon md-svg-src="assets/common/svg/ic_phone_24px.svg" class="name"></md-icon>
                    <md-autocomplete flex
                                     data-ng-model="class.parent_class_id"
                                     md-selected-item="class.parent_class_id"

                                     md-search-text-change="searchClass(keyword)"
                                     md-search-text="keyword"

                                     md-items="item in classArray"

                                     md-item-text="item.class_name">
                        <md-item-template>
                            <span>{{item.class_name}}</span>
                        </md-item-template>
                        <md-not-found>
                            No matches found for "{{keyword}}".
                        </md-not-found>
                    </md-autocomplete>
                </md-input-container>
                

 but its not working
![screen shot 2015-06-11 at 17 15 21](https://cloud.githubusercontent.com/assets/12843531/8104766/85aebb20-105d-11e5-88fc-b6ac2716ce95.png)

help me, please.

**Comment by ivanhtp** [comment]
[1] There is not date/time picker on the project yet. The closest thing you can find for now is http://simeonc.github.io/md-date-time/ made by @SimeonC 

[2] By your code I couldn't find anything wrong, although 'md-autocomplete' has most of its logic on the javascript, on the item change and md-items query. Post your controller and maybe we can help you.

**Comment by minhdh52** [comment]
@ivanhtp thank you for md-date-time,
here is my controller, 



Organization.controller('OrganizationController', ['$rootScope', '$scope', '$modal', 'AuthService',
        function ($rootScope, $scope, $modal, AuthService) {

            $scope.classArray = {};
            $scope.option = {};
            $scope.getClass = function ($class_id) {
                AuthService.callAJAX("GET", "organize/class/gets", {
                    'class_id': $class_id
                }, function (data) {
                    if (data.success) {
                        $scope.classArray = data.data;
                    }
                })
            };

            $scope.openModalOrganization = function ($class_id) {
                var modalInstance = $modal.open({
                    templateUrl: '/modules/smodule/organization/views/organization/modal_organization.html',
                    controller: ['$scope', '$rootScope', '$modalInstance', 'AuthService', 'class_id',
                        function ($scope, $rootScope, $modalInstance, AuthService, class_id) {
                            $scope.class = {};
                            $scope.classArray = [];
                            //$scope.label = {};
                            // load detail info class: organize/class/get [class_id]
                            AuthService.callAJAX("GET", "organize/class/form", {
                                'class_id': class_id
                            }, function (data) {
                                if (data.success) {
                                    $scope.class = data.data;
                                    $scope.class.parent_class_id = data.data.parent;
                                    $scope.classArray = [data.data.parent];
                                    $scope.option = data.select_option;

                                    // get staff in class
                                    $scope.getStaff(class_id);
                                }
                            });

                            $scope.close = function () {
                                $modalInstance.dismiss('close');
                            };

                            //parent department ng-select
                            $scope.searchClass = function (keyword) {
                                console.log(keyword);
                                // to call API search organization
                                AuthService.callAJAX("GET", "organize/class/search", {
                                    'class_name': keyword
                                }, function (data) {
                                    if (data.success) {
                                        $scope.classArray = [];
                                        angular.forEach(data.data, function (value, key) {
                                            if (value.class_id != $scope.class.class_id) {
                                                $scope.classArray.push(value);
                                            }
                                        });
                                    }
                                })

                            };

                            // created_by | modified_by | logs
                            $scope.save = function (isClose) {
                                AuthService.callAJAX("POST", "organize/class/save", {
                                    'parent_class_id': ($scope.class.parent_class_id != null) ? $scope.class.parent_class_id.class_id : null,
                                    'class_id': $scope.class.class_id,
                                    'class_type': $scope.class.class_type,
                                    'class_name': $scope.class.class_name,
                                    'class_description': $scope.class.class_description
                                }, function (data) {
                                    if (data.success) {
                                        if (isClose) {
                                            $modalInstance.close($scope.class);
                                        }
                                    }
                                })
                            };

                            $scope.staffArray = [];
                            //search staff
                            $scope.searchStaff = function (keyword) {
                                AuthService.callAJAX("GET", "organize/staff/search", {
                                    'keyword': keyword
                                }, function (data) {
                                    if (data.success) {
                                        $scope.staffArray = data.data;
                                    }
                                })
                            };

                            //add staff to org
                            $scope.addStaff = function () {
                                var data = {
                                    'class_id': $scope.class.class_id,
                                    'staff_id': $scope.staffArray.staffSelected.staff_id
                                    //'staff_description' : $scope.staff.staff_description
                                };
                                console.log(data);
                                AuthService.callAJAX("GET", "organize/class/addstaff", data, function (data) {
                                    if (data.success) {
                                        $scope.getStaff(class_id);
                                    }
                                })
                            };

                            // get staff
                            $scope.getStaff = function (class_id) {
                                AuthService.callAJAX("GET", "organize/class/getstaff", {
                                    'class_id': class_id
                                }, function (data) {
                                    if (data.success) {
                                        $scope.class.staffs = data.data;
                                    }
                                })
                            };

                            // remove staff
                            $scope.removeStaff = function (class_id, staff_id) {
                                console.log(class_id, staff_id);
                                AuthService.callAJAX("GET", "organize/class/removestaff", {
                                    'class_id': class_id,
                                    'staff_id': staff_id
                                }, function (data) {
                                    if (data.success) {
                                        $scope.getStaff(class_id);
                                    }
                                })
                            };
                        }],
                    size: 'lg',
                    resolve: {
                        'class_id': function () {
                            return $class_id;
                        }
                    }
                });

                modalInstance.result.then(function ($class) {
                    // close -> reload
                    console.log($class);
                    $scope.getClass(null);
                }, function () {
                    // dismiss -> do nothing
                });
            };

            $scope.$on('$viewContentLoaded', function () {
                // initialize core components
                Metronic.initAjax();

                $scope.getClass(null);
            });
        }]
);



but i think i have something wrong in UI,
my task is making an input like this : 

![input-form](https://cloud.githubusercontent.com/assets/12843531/8143027/b687c240-11c1-11e5-8e87-244a1da9cc03.png)

with icon inline and all input fields are md-autocomplete or md-select

**Comment by ThomasBurleson** [comment]
DatePicker is now available (^ v0.11.0-rc1)
