### ISSUE TITLE
md-fab-toolbar assumes a md-icon is inside the trigger button.

### ISSUE THREAD

**Issue by yellowiscool** [angular/material#3223]
Hi,

I played with the new ```<md-fab-toolbar>``` directive. I don't have an icon in my trigger button (only text) and I encountered this problem : 
The result of ```var iconElement = el.querySelector('md-fab-trigger button md-icon');``` is null. It triggers an exception in the runAnimation function (cannot read property style of null).

Otherwise it looks very good :-)

**Comment by topherfangio** [comment]
Thanks for the comment! I'll take a look and get this fixed.
