### ISSUE TITLE
md-theme doesn't work for A tag

### ISSUE THREAD

**Issue by jamm** [angular/material#3226]
Codepen to reproduce:
http://codepen.io/evgeniyoz/pen/yNXPXL?editors=101

Screenshot of how it looks currently:
![screenshot 2015-06-11 17 45 34](https://cloud.githubusercontent.com/assets/526352/8109854/b72a785c-1061-11e5-8a30-71a87f6cd861.png)

Code (in case if codepen will be removed):
```html
<md-content>
      <table class="crm-wide-table">
        <thead>
          <tr>
            <th>Update</th>
            <th>Facility Name</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td md-theme="green"><a class="md-button md-raised md-primary">Update</a></td>
            <td>Test Testword</td>
          </tr>
          <tr>
            <td md-theme="green"><md-button class="md-raised md-primary">Update</md-button></td>
            <td>Test Testword</td>
          </tr>
        </tbody>
      </table>
    </md-content>
```
JS
```js
app.config(function($mdThemingProvider) {

  $mdThemingProvider.theme('default')
        .primaryPalette('blue');
  $mdThemingProvider.theme('green')
        .primaryPalette('green');
});
```

versions affected: 0.9.8, 0.10-rc2.

**Comment by chinnichaitanya** [comment]
There is an error also in the console for the codepen above. Here is the screenshot.

![2015-06-11-202530_1366x768_scrot](https://cloud.githubusercontent.com/assets/6941024/8110099/177e0762-1078-11e5-8f4f-9f82cf1059d7.png)

**Comment by jamm** [comment]
thanks, @chinnichaitanya 
but as theme works for md-button, looks like this message is wrong.

**Comment by jamm** [comment]
@chinnichaitanya my console is clean:
![screenshot 2015-06-11 18 13 51](https://cloud.githubusercontent.com/assets/526352/8110561/ad895468-1065-11e5-9b0d-ff4722685cd2.png)

**Comment by chinnichaitanya** [comment]
@jamm I don't know how I got that error. As of now my console is also clean. Thanks for pointing out that.

**Comment by marcysutton** [comment]
You also need to use `<md-button href="">` to create an anchor button, not a bare `<a>` tag.

**Comment by jamm** [comment]
@marcysutton it's not obvious. I saw in documentation md-button can understand href/ng-href, but I didn't know it's requirement. Ok, then it's not a bug :) Please consider to add info into documentation - maybe it's not obvious for somebody else.

**Comment by marcysutton** [comment]
@jamm it's pretty obvious if you look at the mdButton directive API and demos, every example uses `<md-button>`. If you have suggestions for a graceful way to make this even more obvious, the team would be open to it.

**Comment by jamm** [comment]
@marcysutton I've read documentation and examples and it's not obvious for me. I see it as handy feature, but not as requirement and only way to get correct md-button styling. 

My suggestion is just to declare it in documentation. I'm sure you'll find graceful way to describe it ;) I don't think my level of English is enough to edit your documentation.

**Comment by jamm** [comment]
I found it when I applied md-theme to <a> tag and saw that nothing changed. I spent some time to understand why it doesn't work when documentation of md-theme explicitly saying it should. Let's see if somebody else will open same issue.
