### ISSUE TITLE
a.md-button and button.md-button are displayed differently

### ISSUE THREAD

**Issue by e-oz** [angular/material#3227]
a.md-button has display: inline-table
button.md-button has display: inline-block

affected version: 0.10-rc2,
does **not** exist in 0.9.8

**Comment by jamm** [comment]
codepen:
http://codepen.io/evgeniyoz/pen/YXQjvL?editors=101

Code:
```html
<div layout layout-fill>
    <md-content>
      <table>
        <thead>
          <tr>
            <th>Update</th>
            <th>Facility Name</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td md-theme="green"><a class="md-button md-raised md-primary">Update</a></td>
            <td>Test Testword</td>
          </tr>
          <tr>
            <td md-theme="green"><md-button class="md-raised md-primary">Update</md-button></td>
            <td>Test Testword</td>
          </tr>
        </tbody>
      </table>
    </md-content>
  </div>
```

Screenshots:
![screenshot 2015-06-12 10 42 43](https://cloud.githubusercontent.com/assets/526352/8125636/018db470-10f0-11e5-8eab-deceaa1bdfea.png)
![screenshot 2015-06-12 10 42 34](https://cloud.githubusercontent.com/assets/526352/8125638/0a2cc4fe-10f0-11e5-8e0b-b64b583602b3.png)

**Comment by topherfangio** [comment]
@e-oz Based on the codepen you provided (which uses the latest master branch), I see both with `display: inline-block`. Is this issue resolved for you?

**Comment by e-oz** [comment]
@topherfangio yes, thanks.
