### ISSUE TITLE
return a promise from $mddialog without hide or cancel

### ISSUE THREAD

**Issue by mahermahouachi** [angular/material#3228]
Hello all,

i'm new with angular Material i want to ask if it's possible to return a promise (a value) from mddialog without hiden or closing the mddialog.

i need this to return many time mddialog values then when user finish he click on close and then i hide the mddialog

**Comment by EladBezalel** [comment]
Why won't you just use angular service?

**Comment by mahermahouachi** [comment]
the problem is that i did a mistake by merging many functions together here's my code

// main file js :
$scope.showProjectForm = function(action, item) {

 		$scope.selectedTabIndex = 4;

	    $mdDialog.show({
	      templateUrl: 'views/template/dialogCreateUpdate.tmpl.html',
	      controller: 'ModalCreateUpdateCtrl',
          locals: { 
          	'myItem':          item,
          	'myAction':        action,
          	'listDomainUsers': $scope.listDomainUsers
          },

          bindToController: true
	    })

	    .then(function (project) {
 			if (action == "create"){
 				createProject(project);
 			}else if (action == "update"){
 				updateProject(project);
 			}
 		}, function () {});
  	}; 

// template file js :
$scope.addItem = function () {

    if ( !$scope.newEmployee.email || !$scope.newEmployee.role) {
      sandbox.simpleToast('Specify a valid user credentials', 3000, 'warning');
      return;
    }

    if (!(/.+\@.+\..+/).test($scope.newEmployee.email)) {
      //ADD A TEST TO CHECK IF USER EXIST OR NOT
      sandbox.simpleToast('Specify a valid email', 3000, 'warning');
      return;
    }

    $mdDialog.hide($scope.newEmployee);
  };

  $scope.cancel = function() {
    $mdDialog.cancel();
  }
})

.controller('ModalCreateUpdateCtrl', function ($scope, $mdDialog, sandbox, listDomainUsers, myAction, myItem) {

  $scope.listDomainUsers = listDomainUsers
  $scope.dialogTitle =     'Create';

  $scope.newproject = {
    businessOwner: []
  };

  if (myAction == "update"){
     $scope.newproject = myItem;   
     $scope.dialogTitle = 'Update';
  }

**Comment by EladBezalel** [comment]
I really couldn't realize why would you like to return data from the dialog when it's not done yet.. 
Service or events will do the work for you.. 

Besides that, these kind of questions should be in the forum..

**Comment by mahermahouachi** [comment]
i want to let user add many hierarchies at once when he finish adding he close the modal that's it

**Comment by EladBezalel** [comment]
Can you please put this on plunkr and show what are you trying to achieve?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
