### ISSUE TITLE
md-checkbox ripple text issue

### ISSUE THREAD

**Issue by noahkeitel** [angular/material#3229]
When the check box is directly clicked, toggling the ripple, the text associated with md-checkbox is cut off  when there are letters that are below the line. Letters such as y,j,g. This issue is happening in Chrome: Version 43.0.2357.81 (64-bit).

see recording here: https://www.dropbox.com/s/lo7g6yof55hqsja/md-checkbox_issue.mp4?dl=0

**Comment by noahkeitel** [comment]
md-checkbox .md-label { min-height: 18px; } fixes this but I'm not sure if that creates issues anywhere else.

**Comment by EladBezalel** [comment]
@noahkeitel Hey i think it's not happening anymore on [HEAD](http://codepen.io/EladBezalel/pen/epjXYW) can you confirm?
closing for now, please provide a codepen if this issue isn't solved.
