### ISSUE TITLE
Support use of $animateProvider.classNameFilter(expr)

### ISSUE THREAD

**Issue by dguralnick** [angular/material#323]
Hi All, thanks for your work on these components, we're really grateful to have them available!

By default, ng-animate tries to animate all of our ng-repeats which can cause performance degredation.  

Would it be possible for material lib to include a class on all components that dep on ng-animate so that we could apply it more selectively with $animateProvider.classNameFilter()?  See: https://docs.angularjs.org/api/ng/provider/$animateProvider

As is, one would need to explicitly blacklist elements from having ng-animate applied via $animate.enabled(false, element) calls.

Here is an example ng-animate lengthening our already slow digest cycle by close to 100ms:
![image](https://cloud.githubusercontent.com/assets/8662178/4408998/34cb4070-44d9-11e4-94e8-e7406765b229.png)

**Comment by ThomasBurleson** [comment]
@dguralnick - this sounds reasonable. I shifted the milestone for this one due to existing 0.9 and 0.10 efforts.

**Comment by jordan-thoms** [comment]
This is a major problem. Including angular-material in our app broke a bunch of things, because it includes ng-animate which jumps in and affects the behavior of directives all across the app.

Including a new dependency into a codebase should not have effects on code which doesn't reference said dependency - that follows from the basic tenents of encapsulation.

The screwup here is really on the ng-animate and $animateProvider side, but making this change will at least let us contain the damage from this horribleness.

**Comment by Hengjie** [comment]
Following up from @jordan-thoms, here is some CoffeeScript to completely disable ng-animate unless they are material elements:

```
# Prevent ng-animate negatively affecting existing elements (e.g. ng-switch)
# by disabling animate unless it comes from material design elements
ng.config ($provide) ->
  $provide.decorator '$$animateQueue', ($delegate) ->
    original = {
      push: $delegate.push
    }
    $delegate.push = (element, event, options, domOperation) ->
      node = (if element instanceof angular.element then element[0] else element)
      element_name = node?.nodeName.toLowerCase()

      # If element's tag does not begin with "md" for "material design"
      # then don't use ng-Animate
      if element_name?.indexOf("md") isnt 0
        node?.classList.add 'ng-animate-disabled'

      original.push arguments...
    $delegate
  return
```

**Comment by jamesmfriedman** [comment]
Super easy way. Use $animateProvider.classNameFilter to only allow ngAnimate to run on ngMaterial, and a classname of your own choosing. This assumes that everything that animates in ngMaterial has a classname that starts with md-. Been using it for a bit, seems to work as expected.

```javascript
$animateProvider.classNameFilter(/(your-class-name|md-)/);
```
