### ISSUE TITLE
md-input: HTML5 validation loses focus and error message on form submit android

### ISSUE THREAD

**Issue by amritk** [angular/material#3232]
I'm not sure if anyone has come across this yet, but when you try to submit a form with required inputs using HTML5 validation, the input gets focussed then immediately loses focus on submit. You can see it flash for a second where the keyboard pops up and the error message is displayed. Then it immediately loses focus.

I grabbed this codepen from the angular material demos and just added a form around the inputs. To replicate just touch the submit button on an android phone. The email is required so leave it blank.

http://codepen.io/anon/pen/MwoQdd

**Comment by askucher** [comment]
+1 I can see it in browser
