### ISSUE TITLE
Components should have sensible CSS display on the outermost element.

### ISSUE THREAD

**Issue by jelbourn** [angular/material#3234]
Right now, every component looks great when you're just using that component. However, if you try to start combining them, it quickly turns into a huge CSS pain.

As an example, let's look at something I tried to do: putting an `<md-button>` next to an `<md-input-container>`. If I were to do this with native elements, it would look like this:
```html
<button>Hello</button>
<input>
```
![Button and input](https://dl.dropboxusercontent.com/u/18203969/github-images/btn-input.png)

Great. What happens if I put an `md-button` next to an `md-input-container`?
![md-button and md-input](https://dl.dropboxusercontent.com/u/18203969/github-images/md-btn-input.png)

Okay, looks like the input container is display block. Let's just change that to inline-block:
![md-button and md-input inline-block](https://dl.dropboxusercontent.com/u/18203969/github-images/md-btn-input-inlineblock.png). 

That's closer, but now the label is all messed up. I guess I'll just inspect the element and see what's going on... and discover that the input container display is actually _flex_. So, maybe we can fix the original problem by making in `inline-flex`:
![md-button and md-input inline-flex](https://dl.dropboxusercontent.com/u/18203969/github-images/md-btn-input-inlineflex.png)

An hour later, I'm reading the [spec](http://www.w3.org/TR/css-flexbox/#flex-baselines) for how baselines are computed for flex containers. Turns out that the baseline for the label is computed based on the its _raised_ position, rather than its down position, and the baseline for the flex-container as a whole is computed based on its first flex-item.
![md-button and md-input showing baseline](https://dl.dropboxusercontent.com/u/18203969/github-images/md-btn-input-baseline.png)

This issue isn't about this problem with the input; it's about making sure _all_ of the components are doing something sensible and will mostly "just work" with other Material and native elements. Users should be able to interact with MD components as closely as possible to their native counterparts.

**Comment by tapas4java** [comment]
Are we on track for delevering this on 0.11.0 release?

**Comment by jelbourn** [comment]
Components to look at: 
button, input, autocomplete, datepicker, select, menu, checkbox, radio-button, chips, icon, switch, slider

**Comment by mattdanna** [comment]
@robertmesserle Has this been resolved?

**Comment by mallowigi** [comment]
So this is why my input container are all messed up...

**Comment by devotis** [comment]
If you arrived here because you discovered that the layout of an `md-autocomplete` is pretty different from an `md-select` in an `md-input-container`. The `md-floating-label` attribute comes to the rescue. Check out the Floating label example on https://material.angularjs.org/1.0.1/demo/autocomplete
