### ISSUE TITLE
Unable to Type in Autocomplete

### ISSUE THREAD

**Issue by Sriram143** [angular/material#3235]
![image](https://cloud.githubusercontent.com/assets/4466654/8117487/6fe5c77c-1056-11e5-82ba-602e0dfabea9.png)

its now allowing to type any thing in auto complete after first letter

**Comment by bengadbois** [comment]
On chromium 41.0, I'm not having the issue

**Comment by ACDN** [comment]
Seeing the same behaviour in Chrome 43.0.2357.124 m and Firefox 38.0.5.

To add further detail.  I am only able to type one letter, then the drop down appears with selections.  At this point I can no longer type or select anything from the drop down.  If you press the ESC key you can alter a single letter.  Either adding a new one or removing one. When there are no characters left in the field you can navigate away.

**Comment by mckenzielong** [comment]
Appears like typing in the other autocompletes is broken as well (not even one letter.)  You are also unable to scroll the results as well.

**Comment by ACDN** [comment]
Auto complete is working as expected in 0.10.0 RC4

**Comment by jiriletak** [comment]
+ 1
