### ISSUE TITLE
How to use $mdTheming

### ISSUE THREAD

**Issue by pavankumarkatakam** [angular/material#3239]
Im just exploring the Material angular design, and noticed that themes can be applied to only few components as mentioned in this [link](https://material.angularjs.org/latest/#/Theming/02_declarative_syntax) . So i dig into deep and got to know the theming is implemented to that components and then i found a service $mdTheming in source code. 

I have spent time to know how it work and apply to my custom element in a page, I injected $mdTheming in to my controller and style is done in the way look like in source code. my example app is here
Code in my page Home.html
```
<style>
    .something {
        color: '{{primary-color}}';
    }
</style>
<div>
    {{ some }}<br>
    This is start.html page

    <span class="something" id="some">pavan</span>
</div>
``` 

and my route with controller is (here im using ui-router)
```
.state('main', {
                url: '/',
                templateUrl: 'start.html',
                controller: function ($scope, $mdTheming, $log) {
                    $mdTheming(angular.element(document.querySelector('#some')));
                    $scope.some = "some value";
                }
            })
```

But the css is compiling to (by inspecting in the browser)

```
<div class="view ng-scope" ui-view=""><style class="ng-binding ng-scope">
    .something {
        color: '0';
    }
</style>
<div class="ng-binding ng-scope">
    some value<br/>
    This is start.html page

    <span class="something md-default-theme" id="some">pavan</span>
    </div>
</div>
```

here why the css color property is compiling to '0' as mentioned in above code.
so please tell me if i'm missing something or there is bug in service $mdTheming.

**Comment by plato-cambrian** [comment]
See also #1269
