### ISSUE TITLE
FAB Speed Dial: using md-mini and normal buttons together

### ISSUE THREAD

**Issue by cebor** [angular/material#3240]
Hi, when using normal buttons and `md-mini` together in the FAB Speed Dial, the mini buttons have offset to the left:

http://codepen.io/anon/pen/JdJBYR

**Comment by topherfangio** [comment]
Yup, we should be able to fix this by adding some flex positioning to the `.md-fab-action-item` class. It should be pretty simple. Would you be interested in providing a Pull Request to fix this?

**Comment by cebor** [comment]
done :)

**Comment by topherfangio** [comment]
Awesome, thanks!
