### ISSUE TITLE
bug: md-tabs pagination does not init on small screens

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3242]
line 385 of tabsController.js returns false if !loaded. However the shouldPaginate() call in init() occurs before loaded==true so it always returns false.

**Comment by tyler8691** [comment]
I am also seeing this. The tabs appear jumbled when the page first loads.

**Comment by robertmesserle** [comment]
I believe this is resolved in master.  If not, please reply with a CodePen demonstrating this issue against the latest code.

**Comment by hodeyp** [comment]
@robertmesserle all fixed, thanks
