### ISSUE TITLE
md-tab: md-on-select called on init

### ISSUE THREAD

**Issue by jozsi** [angular/material#3243]
Since about yesterday (0.10.0-rc4 ~ master branch), the `md-on-select` of an `md-tab` gets 
during the initialization of `md-tabs`. Previously it has been called only when a tab was explicitly selected.

[Example](http://codepen.io/anon/pen/PqjyNb) - see console log

**Comment by jamm** [comment]
this bug affects one of my apps also. I have routing events assigned to on-select, so now users can't open desired page by URL and I can't use $state.go, because right after that on-select will trigger another one redirect.

**Comment by jo-me** [comment]
This is probably due to this: #3169 .
The events are incomplete if the tab-select-event is not being fired in all cases when a tab is selected (automatically).
Your solution would probably be to start in an unselected state (not sure whether thats possible, I think I saw an issue regarding that recently). 

There is, however, still a bug in the latest version as the event is not coming when the tabs are loaded asynchronously.

**Comment by jamm** [comment]
@jo-me funny thing is I completely disagree with you and don't think on-select should be fired when tab is initially displayed :)

**Comment by jo-me** [comment]
Nothing wrong with disagreeing :) 

IMO, as long as the md-tabs component automatically displays the first tab, the md-select event should get fired. 
If you use it for navigation purposes, doesn't it show tab 1 as being active without showing the correct route?

**Comment by jamm** [comment]
@jo-me no, it triggers chaotic routing and ends up with "/#/" URL with default page rendered, so app is completely unusable. I think separate even can satisfy both sides.

**Comment by jo-me** [comment]
I'm not familiar with your use case, but how about using the ng-click event instead?  
This sounds like a closer match for your needs than md-select.

**Comment by jamm** [comment]
@jo-me good idea, thanks, but currently (with angular-material 0.10.0 and with 0.9.8, both) it gives exception about $apply:
![screenshot 2015-06-15 22 34 51](https://cloud.githubusercontent.com/assets/526352/8168915/e84419b6-13ae-11e5-99d9-102af3353f9d.png)

But I will glad to switch to ng-click, if this bug will be fixed. Especially when 0.10 is new stable :)

**Comment by jamm** [comment]
I found solution: I just ignore first event and all works as expected. But I still hope ng-click bug will be fixed.

**Comment by robertmesserle** [comment]
@e-oz I believe ng-click should work, but I am not 100% sure what your use-case looks like.

As for whether or not to fire the `md-on-select` event, it would make sense to me to fire the event if/when our code provides a value.  But if you pre-populate the variable with a value of 0, it will not fire.  If this makes sense to you, I will make sure that this functionality works.  (I haven't tested, but logically, this seems like how I would expect it to work.)

**Comment by e-oz** [comment]
@robertmesserle I've created codepen with my use-case and with instruction how to reproduce bug:
http://codepen.io/evgeniyoz/pen/BNOmKx?editors=101
(copied as [gist](https://gist.github.com/e-oz/94bbffdf115187272dd3) also)

**Comment by robertmesserle** [comment]
Ah, this is a separate issue, but I am committing a fix right now.

**Comment by robertmesserle** [comment]
@e-oz Fix here https://github.com/angular/material/commit/1b984ed6b708b5acba42194b66699aae1d243fe2

**Comment by e-oz** [comment]
@robertmesserle thank you!

**Comment by jozsi** [comment]
Using ng-click and @robertmesserle 's did indeed achieve the desired result. Thank you!
