### ISSUE TITLE
md-divider not showing in column layout, aligned center center

### ISSUE THREAD

**Issue by lixapopescu** [angular/material#3249]
When trying to show this, centered, the md-divider doesn't get displayed
1
----
2

I'm using the master branch available at this moment, 0.10.0-rc4

See code here: http://codepen.io/anon/pen/zGzbvG
To test, remove the 'layout-align="center center"' and the divider is then displayed.

**Comment by shairez** [comment]
+1 
For me it happens when layout-align is present with 2 values, the actual align values don't matter (it can also be "start start" or "end end"

**Comment by smkamranqadri** [comment]
same issue i am facing and if i only give one value the alignment get out.

**Comment by dmcbcc** [comment]
This bug is still present in version 1.0.8.

**Comment by DevVersion** [comment]
@dmcbcc This is fixed in the latest major release. (`v.1.1.0-rc4`)
