### ISSUE TITLE
mdTooltip broken in Firefox since 0.9.8

### ISSUE THREAD

**Issue by gpothier** [angular/material#3250]
Tooltips do not appear in Firefox (v38). This problem occurs even in the Tooltip demo on the Angular Material page:

https://material.angularjs.org/latest/#/demo/material.components.tooltip

I don't think it is related to #3047, as I checked the pointer-events style in the button's hierarchy in the demo page, and nothing turned up.

**Comment by alirezamirian** [comment]
Actually it is related to #3047 and the issue will be resolved if you comment out the lines 132 and 134 which calls `setVisible(true)` only if `pointer-events` is 'none'
