### ISSUE TITLE
md-font-icon attribute not updating icon based on expression

### ISSUE THREAD

**Issue by naveednazarali** [angular/material#3251]
md-font-icon is not updating icon when ternary expression is used. It evaluates that expression only once.

Here is the code to demonstrate the issue:

http://codepen.io/anon/pen/Kpqogj

**Comment by george3447** [comment]
+1

**Comment by Splaktar** [comment]
The codepen is using an old RC version of AngularJS (1.3.0_rc.4)and and hammer.js. Updating to AngularJS 1.4.6 seems to resolve this issue.

**Comment by ThomasBurleson** [comment]
@programmist - can you confirm your recent improvements still support this ?

**Comment by programmist** [comment]
@ThomasBurleson - Yes, it works.  Here is a demo that uses the version of Angular Material built from my "icon-fix-default-fontset" branch.  http://codepen.io/programmist/pen/WQoGdv
