### ISSUE TITLE
Static chips should not have cursor `text`

### ISSUE THREAD

**Issue by RomFouq** [angular/material#3253]
Since they are static, they can't be edited or even selected, so they should have cursor `default`, not `text`.
This can be seen here:
https://material.angularjs.org/latest/#/demo/material.components.chips
When hovering between chips, a `text` cursor appears.

**Comment by chinnichaitanya** [comment]
@RomFouq The cursor is `default` for me in the above link. I'm using chromium-browser 43.0

**Comment by RomFouq** [comment]
*On* chips, I agree, but not *between* chips and elsewhere on the `md-chips` element. I've tested this on Chromium and Firefox. This style is explicitly added by the `.md-chips` class, according to the inspector.

**Comment by typotter** [comment]
I would argue that in fact a static chip should have cursor:text since the text can be edited. But yes, the background/container element should not have cursor:text.
