### ISSUE TITLE
Autocomplete template not working on plunker

### ISSUE THREAD

**Issue by gpopovic** [angular/material#3254]
Autocomplete demo, is broken (everything item is in one line, instead of in several)

Codepen is the same as the demo (https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete)

http://codepen.io/anon/pen/VLWJdQ

**Comment by robertmesserle** [comment]
I suspect this is related to the introduction of the virtual repeater into autocomplete.

**Comment by topherfangio** [comment]
I believe this was actually a scoping issue that was solved the the "parent scope" directive we fixed. I am not seeing this issue on master anymore so I am closing. Please comment if you are still seeing the issue.
