### ISSUE TITLE
$mdDialog not scrolling in Chrome

### ISSUE THREAD

**Issue by MrPilotSir** [angular/material#3255]
I did a mockup of a dialog box with 4 md-input-container's with inputs which are stacked vertically and when the vertical space shrinks the inputs start acting all weird in chrome for desktop and android.

In firefox it works just find and allows you to scroll up and down to view all the inputs but on chrome it just squashes the md-dialog-content area.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. 

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.
