### ISSUE TITLE
$mdDialog templateUrl is not working properly

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#3256]
this is my code
```javascript
app.controller('site', function($scope, $mdDialog)
{
	$mdDialog.show({
		template: 'site/login',
	});
});
```

for now i am just trying to show a dialog that will contain elements from an url on my server, but when i check the page, the dialog is not shown and it just shows the content in the middle of the page.

I even tried to use 'template' only, but it does the same

**Comment by Antariano** [comment]
Make sure the template exists. 
Also, I'm fairly certain it should be "/site/login".

**Comment by Nosthertus** [comment]
i found the problem, it seems like i was using an old angular-material version which was not working properly with another version api

**Comment by PravienSk** [comment]
Can i know what is the version of angular you are using ?
