### ISSUE TITLE
$mdToast doesn't work properly in nested ui-view

### ISSUE THREAD

**Issue by johnlim5847** [angular/material#3257]
hi im getting some strange behaviour from $mdToast in nested ui-view when i call the toast this is what i got 
 **before call**
![screen shot 2015-06-14 at 6 08 33 pm](https://cloud.githubusercontent.com/assets/3675946/8148153/6e543ab2-12c0-11e5-9d4f-5299c7c54cff.png)

**after call**
![screen shot 2015-06-14 at 6 08 07 pm](https://cloud.githubusercontent.com/assets/3675946/8148156/7a4908a2-12c0-11e5-81d6-fb2bc81b6fec.png)

this gone after 3 seconds which is the time i set in my mdToast. may i know is there any way to make it works ?

**Comment by johnlim5847** [comment]
anyone of you experience this kind of issue ?

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. 
*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.
