### ISSUE TITLE
Cannot read property 'setAttribute' of null when clicking on 'menu' when using `data-ng-click="$mdOpenMenu()"`

### ISSUE THREAD

**Issue by DBassel** [angular/material#3258]
`TypeError: Cannot read property 'setAttribute' of null`, when click event is marked by:
`data-ng-click="$mdOpenMenu()"`
when is marked: 
`ng-click="$mdOpenMenu()"`
the issue disappears.

Thanks!

**Comment by Frank3K** [comment]
I don't think this issue is completely fixed, compared to what I expected earlier in #3252.

The file [_menu.js](https://github.com/angular/material/blob/4a6cd566d2768d1b36c16c82cfec832b2101b4e8/src/components/menu/_menu.js) contains the following references to `ng-click` only:

[Lines 150-152](https://github.com/angular/material/blob/4a6cd566d2768d1b36c16c82cfec832b2101b4e8/src/components/menu/_menu.js#L150-L152)

```js
    if (!triggerElement.hasAttribute('ng-click')) {
      triggerElement = triggerElement.querySelector('[ng-click]');
    }
```

[Lines 187-190](https://github.com/angular/material/blob/4a6cd566d2768d1b36c16c82cfec832b2101b4e8/src/components/menu/_menu.js#L187-L190):

```js
  this.init = function(setMenuContainer) {
    menuContainer = setMenuContainer;
    triggerElement = $element[0].querySelector('[ng-click]');
  };
```

Can someone reopen this issue?

**Comment by amobiz** [comment]
> Cannot read property 'setAttribute' of null

in __material/src/components/menu/js/menuController.js__

[Lines 26-27:](https://github.com/angular/material/blob/b58343c20ac4bd3418629c29abddfe3ac3840eb5/src/components/menu/js/menuController.js#L26-L27)
```js
triggerElement = $element[0].querySelector('[ng-click],[ng-mouseenter]');
triggerElement.setAttribute('aria-expanded', 'false');
```

Where `triggerElement` is null.

**Comment by cmacdonnacha** [comment]
+1

**Comment by homerjam** [comment]
+1

**Comment by kaldebert** [comment]
+1

**Comment by patrickPatterson** [comment]
+1

**Comment by jacobuk** [comment]
+1

**Comment by manoharnv** [comment]
+1

**Comment by Karvel** [comment]
+1

**Comment by kanpinar** [comment]
+1

**Comment by farantesrodrigues** [comment]
ng-dblclick raises this error. ng-click does not.

**Comment by Prajwal8** [comment]
Can anyone help us , we stuck at below mentioned issue..thank you in advance


TypeError: Cannot read property 'setAttribute' of null at e.init

**Comment by DevVersion** [comment]
@Prajwal8 A pull request, which automatically adds the prefix is pending.

**Comment by Prajwal8** [comment]
TypeError: Cannot read property 'setAttribute' of null at e.init...this issue did not solved yet, this is causing delay in completion of the project...Can anyone help us ??

**Comment by DevVersion** [comment]
@Prajwal8 Did you properly create a menu with an element to open the menu (~ `trigger element`)

Also the new prefixer is available in the new `v1.1.0` release.

**Comment by Prajwal8** [comment]
Ya...but am still facing this issue!

**Comment by Prajwal8** [comment]
@DevVersion  am posting my code, write now i have hard coded the data...please do replay back

index.html
        <md-menu class="persondropdown">
                  <md-button href="" class="md-icon-button"
                           ng-click="headerObj.openMenu($mdOpenMenu, $event)"
                         aria-label="Personal Profile     Dropdown Menu">
             <span><img class="personimage" src="assets/images/person.png"></span> 
                	<span class="hidden-xs">{{loggedInUser}}</span> 
                	<span>
                  <md-icon md-font-icon="zmdi zmdi-caret-down"></md-icon>
                  <md-tooltip>Personal Profile</md-tooltip>
                  </span> 
				  
	    </md-button>
                <md-menu-content class="userflyout" width="4">
                  <md-subheader class="font-medium">Switch to:</md-subheader>
                  <md-menu-item>
                    <md-button ui-sref="home" aria-label="home"> <i class="profile-myprofile-icon"></i> 
                          home </md-button>
                  </md-menu-item>
                  <md-menu-item>
                    <md-button ui-sref="myprofile" aria-label="myprofile"> <i class="myprofile-icon"></i> myprofile </md-button>
                  </md-menu-item>
                  <md-menu-item>
                    <md-button ui-sref="date" aria-label="date"> <i class="profile-date-icon"></i> date </md-button>
                  </md-menu-item>
                 
                  <md-menu-item>
                    <md-button ui-sref="changePassword" aria-label="Change Password"> 
                          Change Password   </md-button>
                  </md-menu-item>
                  
                </md-menu-content>
              </md-menu>


ctrl.js

this.openMenu = function ($mdOpenMenu, ev) {
     
        $mdOpenMenu(ev);
    };

**Comment by Prajwal8** [comment]
index.html

         <md-menu class="persondropdown">
                <md-button href="" class="md-icon-button" ng-click="headerObj.openMenu($mdOpenMenu, $event)" aria-label="Personal Profile Dropdown Menu"> <span><img class="personimage" src="assets/images/person.png"></span> 
                	<span class="hidden-xs">{{loggedInUser}}</span> 
                	<span>
                  <md-icon md-font-icon="zmdi zmdi-caret-down"></md-icon>
                  <md-tooltip>Personal Profile</md-tooltip>
                  </span> 
				  
				 </md-button>
                <md-menu-content class="userflyout" width="4">
                  <md-subheader class="font-medium">Switch to:</md-subheader>
                  <md-menu-item>
                    <md-button ui-sref="home" aria-label="home"> <i class="profile-myprofile-icon"></i> home </md-button>
                  </md-menu-item>
                  <md-menu-item>
                    <md-button ui-sref="myprofile" aria-label="myprofile"> <i class="myprofile-icon"></i> myprofile </md-button>
                  </md-menu-item>
                  <md-menu-item>
                    <md-button ui-sref="date" aria-label="date"> <i class="profile-date-icon"></i> date </md-button>
                  </md-menu-item>
                  <md-divider></md-divider>
                  <md-menu-item>
                    <md-button ui-sref="account" aria-label="account"> account </md-button>
                  </md-menu-item>
                  <md-menu-item>
                    <md-button ui-sref="changePassword" aria-label="Change Password"> Change Password </md-button>
                  </md-menu-item>
                  <md-menu-item>
                    <md-button ng-click="headerObj.logOut()" aria-label="Sign out"> Sign out </md-button>
                  </md-menu-item>
                </md-menu-content>
              </md-menu>

ctrl.js
this.openMenu = function ($mdOpenMenu, ev) {
        originatorEv = ev;
        $mdOpenMenu(ev);
    };

**Comment by DevVersion** [comment]
I cannot see any issues with that code. Tested in a codepen, and works like a charm without any errors.

> http://codepen.io/DevVersion/pen/pEzxzG?editors=1000

**Comment by Prajwal8** [comment]
Thanks for the replay...am using the same code ,but some how am getting the error....please do suggest .what might possibly went wrong????

**Comment by DevVersion** [comment]
As previous mentioned, I assume you still use an older version than `v1.1.0`.

Also this is not the right place to discuss those things - Questions like this are normally for the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by Prajwal8** [comment]
Thank you...

**Comment by imPRAGMA** [comment]
Just feed it `ng-click="null"` aswell as your custom way to open the menu (ng-right-click e.t.c). It will not do any errors, and will work. 👍
