### ISSUE TITLE
md-slider does not work with too small float values in v0.10.1

### ISSUE THREAD

**Issue by Tooa** [angular/material#3259]
Hi,

See [this](http://plnkr.co/edit/XMJfgcWCvFR5sKm2JUD6?p=preview) for the problem. Dragging the slider will move it instantly to the right. In version 0.9.4 the slider works as expected. It seems that it is not working if the float values are too small.

Best Uli

**Comment by Tooa** [comment]
I traced down the introduced problem to these two 072958796a64c2175de9e4cb0de10a8025f0dc7c https://github.com/angular/material/commit/476d068c6f6e204d2c0797be08346076154a9029 commits. Because in version https://github.com/angular/bower-material/commit/3d223b0e63da2a8813b904db3e5373e2e5399731 it is working and the above commit were the only new changes made since then.

**Comment by Tooa** [comment]
Hi, 

I just wanted to ask what the status on this report is. The problem **still exists** in the current master branch (See: [1]).  I also wonder why the label `Backlog` is assigned to this ticket: 
> Grouping for issues that have been reviewed and require further information before assignment to milestone is possible.

Which information is missing? 

[1] http://plnkr.co/edit/RklobRPrAuehot9JevLm?p=preview

**Comment by EladBezalel** [comment]
@Tooa the commit you've talked about made the steps value 3 digits after the decimal point, i made it 6 digits after the decimal point,after 6 digits the numbers are too small.

**Comment by ThomasBurleson** [comment]
Fixed with SHA e0abeb4dc46a1753616a911fe54f14d8f1148a25
