### ISSUE TITLE
Form labels inside a dialog are blurry in chrome

### ISSUE THREAD

**Issue by Antariano** [angular/material#3260]
One can "hotfix" the issue by switching to 2d transforms

```
md-input-container.md-input-focused label:not(.md-no-float), md-input-container.md-input-has-value label:not(.md-no-float) {
    transform: translateY(6px) scale(.75);
}
```
Normal state: Blurry inside a dialog
![](http://i.antariano.com/2015-09-05_12-53-19-Rx5tQPPU3mc5jdHW.png)

By replacing 3d transform with 2d transform
![](http://i.antariano.com/2015-09-05_12-54-24-unO7YNUZFq01Rdaj.png)

**Comment by ThomasBurleson** [comment]
@Antariano - those image links are no longer valid. Can you drag-n-drop them onto a new comment box in this issue?

**Comment by Antariano** [comment]
Will do.

**Comment by Antariano** [comment]
I fixed it in the first post.
Sorry about the broken links - I had a little bit of a fallout earlier this month with my image server!
