### ISSUE TITLE
when associated with ionic ion-nav-buttons are handled twice (on mobile devices)

### ISSUE THREAD

**Issue by WirthAware** [angular/material#3261]
If i click on a ion-nav-buttons it is called twice. 
I created a plunker for that issue:
http://embed.plnkr.co/bS6Ge7

Click on the "doSomething" button top right.
It produce a console log.

Note: on browsers it works fine but when i toggle to device mode in chrome and emulate a mobile device and touch, the ng-click is called twice and the log is printed twice. 

This issue occures as well for the nav "back" button and influence my ionicHistory.

**Comment by marcysutton** [comment]
Have you checked it on an actual mobile device?

**Comment by ThomasBurleson** [comment]
Please refer to [these issues](https://github.com/angular/material/issues?utf8=%E2%9C%93&q=label%3Aconflict+) to understand the Ionic conflicts on Mobile:

**Comment by WirthAware** [comment]
of course i checked it on a real android device. ok thx for the advise
