### ISSUE TITLE
List: api to trigger animation on list item?

### ISSUE THREAD

**Issue by ilazarte** [angular/material#3263]
When a list item is clicked that contains a secondary element (like a checkbox) a nifty wave animation is triggered.  A user can trigger this by hiding a checkbox inside the list item with display:none, but ideally I would like to simple invoke the animation on the item - for example in the case of a user creating something that already exists, so simply highlighting the item is enough.

**Comment by ThomasBurleson** [comment]
You want ink-effects on listItems without actions?

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.
