### ISSUE TITLE
md-tabs: Too many md-select events when changing tab data via binding

### ISSUE THREAD

**Issue by jo-me** [angular/material#3265]
There are too many md-on-select events fired if a set of tabs is switched out agains a different set of tabs (via ng-repeat on some model).

See here:
http://plnkr.co/edit/vxypBgKP5Wyveb8vp1pB?p=preview

Click the 2 buttons at the top to display tabs  1-10  and  1\*-10\*.  
When switching the tab sets you can see the logs in the chrome console, e.g.

when changing to the second set of tabs from the first tab of the first set:
```javascript 
Two selected
Three selected
Four selected
Five selected
Six selected
Seven selected
Eight selected
Nine selected
Ten selected 
```

and when switching back to the first set:
```javascript 
Two* selected
Three* selected
Four* selected
Five* selected
Six* selected
Seven* selected
Eight* selected
Nine* selected
Ten* selected
```

It seems that as Angular updates the databinding the mdtabs is directly reacting to every operation on the array.

The fact that the first tab of the new set is not logged as expected is due to a different issue ( #3169 ).

**Comment by robertmesserle** [comment]
This looks to be resolved in master.
