### ISSUE TITLE
mdSelect: Maximum call stack exceeded when used in combintaion with breeze.js

### ISSUE THREAD

**Issue by waegen** [angular/material#3268]
I'm currently facing an issue where the mdSelect component raises a "MaximumCallStackExceeded" exception. This is new with the latest version(s). In v0.9.0 the code was working properly.

Please check out the following plunker where the issue is reproducable.
http://plnkr.co/edit/b6FnACqFXe3uczPYeIwb?p=preview

**Comment by rschmukler** [comment]
Likely related to #5330.

**Comment by rschmukler** [comment]
@waegen I realize this is likely long past when you needed it but can you see if this is resolved?

**Comment by waegen** [comment]
Hi,

thanks you for your response.

Using the current master branch with my isolated test case works like expected now. I will give you a heads up of my test results in our real-life project in the near future.

Thanks again.

**Comment by rschmukler** [comment]
Awesome. Closing.
