### ISSUE TITLE
can't click outside of menu to close in firefox.  

### ISSUE THREAD

**Issue by opadillaintegrify** [angular/material#3269]
This happens in rc4.
https://material.angularjs.org/0.10.0-rc4/#/demo/material.components.menu

I can open the menu in firefox but I'm forced to pick an option.  I can't click outside the menu to close in the event that I don't want to pick an option.

Also, the image icons don't show up on the same line as the text.

**Comment by ntatic** [comment]
It also happens with mdSelect

Workaround i use for it:

```javascript
app.run(function () {
    // md-scroll-mask z-index bug
    jQuery('body').on('click', '.md-scroll-mask', function () {
        jQuery('.md-select-backdrop').trigger('click');
    });
});
```

**Comment by Abrissirba** [comment]
Caused by 6911506712a9ef71ebefbcd63f427e4325d82001. Firefox and IE11 return "auto" when no z-index is set while chrome returns "". Firefox and IE11 will therefore be NaN and set the z-index to 99 while chrome will set the scrollmask to -1.
