### ISSUE TITLE
md-checkbox within an md-list-item on IE 11 does not align correctly

### ISSUE THREAD

**Issue by malwoden** [angular/material#3282]
Can be seen on the angular material list demo page:

Firefox (correct):
![ff_checkbox_list](https://cloud.githubusercontent.com/assets/153354/8179721/69289e56-1410-11e5-99ec-797435b33611.png)

IE11: 
![ie_checkbox_list](https://cloud.githubusercontent.com/assets/153354/8179740/89ef1002-1410-11e5-900f-cbaa47c68847.png)

Text seems to be out of line too. Not checked under IE10.

**Comment by topherfangio** [comment]
This appears to be fixed on master.

If you are still experiencing issues after upgrading; please comment and I will reopen.
