### ISSUE TITLE
icon-button + z-indexes + transform = invisible (masked out) ripple effect

### ISSUE THREAD

**Issue by karolkochan** [angular/material#3285]
Hello, 
my application has some problems with **`icon-button`** ripple effect. Unfortunately i can't reproduce it in codepen/jsfiddle, all i know is that the problem is probably caused in specific circumstances of elements styled with `transform` and `z-index`. 
`ripple-container` div is present after first click and ripple divs are correctly appended inside, but ripple is not visible (it is clipped out). But when I change `z-index` on 'some divs' it is working as supposed. So, I have 2 questions: 

1. Does anybody also have this kind of problem? 
2. Currently, ripple in `icon-button` is always created from button center and match parent size, so dedicated styles for `icon-button > ripple-container` are redundant (`border-radius`, `background-clip`, `overflow`, `-webkit-mask-image`). Do you (material team) going to stay with this styles or rather get rid of them?

Cheers

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (611/500 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:53851 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdI-000Lji-Pl
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:56 -0500
Date: Thu, 28 Apr 2016 13:32:25 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875545;
	bh=4K506NsQ4jx6qDnw9K65wti4DyxRGh9KLkuojC+E6Ao=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=QkXwgndRr3uBve+/9RWjaeCadW/KKhn8wU9GYw5NFQmoSO19prMCtZlceJVwWedOb
	 BfS6aA9TZBWFDVX3lQ45x+7YmDgtKXuN2VG3A349vszAzgVSNoPqMgyEmsm4HIxgVk
	 /HKppRlZ4KWZvx9JNz4M9CAJO/s4Nk9oCmDKyVFs=
