### ISSUE TITLE
mdTabs - IE11/Firefox Won't Scroll Paginated Tabs Into View

### ISSUE THREAD

**Issue by Londovir** [angular/material#3286]
Don't have a separate CodePen, but Material Demo site illustrates the problem: https://material.angularjs.org/latest/#/demo/material.components.tabs

If you have a narrow viewport which triggers pagination of multiple tabs, under Chrome you can click the right arrow and the list of tabs completely scrolls to the left to bring the next set into view. For example, using the MD demo "Dynamic Tabs" example with a window resized down to a small enough width that you only originally see "FOU" displayed (for tab FOUR), a single click on the right arrow will scroll the default active tab of THREE clean off the left edge of the window, bringing FOUR to SEVEN into view:

![Original Setup](https://cloud.githubusercontent.com/assets/11982575/8183699/dae1837c-1407-11e5-9c39-8923d2fe47f9.png)
**Original Setup**

![Chrome](https://cloud.githubusercontent.com/assets/11982575/8183710/e8cf02b6-1407-11e5-9d8a-bfa2ff95c2ee.png)
**Chrome Right-Scroll Result**

However, in IE11/Firefox a single click on the right arrow scrolls the active tab to the left edge of the viewport and refuses to go any further to the right, regardless of how much clicking you do. For instance, this is how it looks:

![IE11/Firefox](https://cloud.githubusercontent.com/assets/11982575/8183722/fcf6a6a4-1407-11e5-907b-98f02be39ff8.png)
**IE11/Firefox Right-Scroll Result**

Only by clicking the tab SIX tab to make it active can I then click on the right arrow to advance the tabs, and again, only up to the point where SIX becomes parked on the left side.

From debugging, it looks like IE11, at least, is getting caught into essentially an infinite loop of DOMSubtreeModified events, which is causing updatePagination() to be called repeatedly, which in turn calls adjustOffset(), which I think is ultimately causing the currently selected tab to be forced into the viewport, essentially preventing the scrolling action. I can't figure out what's causing IE11/Firefox to trip these infinite events, though...

I believe this is caused by the commit (6d45f104e98736e4af80bb20ec7897675ca1fb15) that was put in 5 days ago which was intended to resolve #3139.

I have removed the code in updatePagination() that was added and this has restored the functionality that was there in 0.9.8. I'm guessing the $timeout call to adjustOffset() is the culprit.

**Comment by robertmesserle** [comment]
This appears to be resolved in master.  Please re-open with a CodePen if this issue still exists.
