### ISSUE TITLE
theming of md-button is slow

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#3290]
This issue can be noticed when a custom theme is added alongside the default theme. Buttons that are used with the custom theme appear/flicker with the default styles for a moment and then get the custom theme applied. The impact depends on the length of the digest cycle I guess.

This Plunkr shows the problem, u might need a slower machine or add more buttons: http://plnkr.co/edit/yHKeHduEITGKcl0mPBeR?p=preview

The delay seems to be caused due to the ripple-container being added to the button at [L87](https://github.com/angular/material/blob/master/src/components/button/button.js#L87)

Potential fix
```javascript
    $timeout(function () {
      $mdButtonInkRipple.attach(scope, element);
    });
```

**Comment by ThomasBurleson** [comment]
Should be fixed with latest 0.11.0-rc2.

**Comment by topherfangio** [comment]
@kuhnroyal I am no longer seeing an issue in your Plunkr. Can you verify that this is fixed?

**Comment by kuhnroyal** [comment]
Looking good, seems to be fixed!
