### ISSUE TITLE
inconsistent md-button heights in Firefox

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#3291]
This has bugged me for a while, finally got around to look into it. Button heights are not consistent in Firefox. `button` is 38px and `a` is 36px as it is supposed to. This can be fixed by removing the line-height: 36px from `.md-button` and setting it only for `a.md-button`.

Plunkr: http://plnkr.co/edit/b2oUoms67DYjsJYOEVBw?p=preview

Uncomment the css to fix.

**Comment by topherfangio** [comment]
Appears to have some issues in Chrome as well. Will investigate.
