### ISSUE TITLE
md-autocomplete: validation not working anymore in 0.10.0

### ISSUE THREAD

**Issue by r0b-** [angular/material#3293]
https://material.angularjs.org/0.10.0/#/demo/material.components.autocomplete, floating label demo should have validation & messages.

Thanks
Rob

**Comment by monyprak** [comment]
+1

**Comment by mikedobrin** [comment]
+1

**Comment by rockclimber90** [comment]
+1

**Comment by ninety7** [comment]
+1

**Comment by Sriram143** [comment]
To fix for this is change template isRequired to @mdAutocompleteCtrl.isRequired

  template: function (element, attr) {
                    var noItemsTemplate = getNoItemsTemplate(),
                        itemTemplate = getItemTemplate(),
                        leftover = element.html();
                    return '\
        <md-autocomplete-wrap\
            layout="row"\
            ng-class="{ \'md-whiteframe-z1\': !floatingLabel }"\
            role="listbox">\
          ' + getInputElement() + '\
          <md-progress-linear\
              ng-if="$mdAutocompleteCtrl.loading"\
              md-mode="indeterminate"></md-progress-linear>\
          <ul role="presentation"\
              class="md-autocomplete-suggestions md-whiteframe-z1 {{menuClass || \'\'}}"\
              id="ul-{{$mdAutocompleteCtrl.id}}"\
              ng-hide="$mdAutocompleteCtrl.hidden"\
              ng-mouseenter="$mdAutocompleteCtrl.listEnter()"\
              ng-mouseleave="$mdAutocompleteCtrl.listLeave()"\
              ng-mouseup="$mdAutocompleteCtrl.mouseUp()">\
            <li ng-repeat="(index, item) in $mdAutocompleteCtrl.matches"\
                ng-class="{ selected: index === $mdAutocompleteCtrl.index }"\
                ng-click="$mdAutocompleteCtrl.select(index)"\
                md-autocomplete-list-item="$mdAutocompleteCtrl.itemName">\
                ' + itemTemplate + '\
            </li>\
            ' + noItemsTemplate + '\
          </ul>\
        </md-autocomplete-wrap>\
        <aria-status\
            class="md-visually-hidden"\
            role="status"\
            aria-live="assertive">\
          <p ng-repeat="message in $mdAutocompleteCtrl.messages" ng-if="message">{{message}}</p>\
        </aria-status>';

                    function getItemTemplate() {
                        var templateTag = element.find('md-item-template').remove(),
                            html = templateTag.length ? templateTag.html() : element.html();
                        if (!templateTag.length) element.empty();
                        return html;
                    }

                    function getNoItemsTemplate() {
                        var templateTag = element.find('md-not-found').remove(),
                            template = templateTag.length ? templateTag.html() : '';
                        return template
                            ? '<li ng-if="!$mdAutocompleteCtrl.matches.length && !$mdAutocompleteCtrl.loading\
                         && !$mdAutocompleteCtrl.hidden"\
                         ng-hide="$mdAutocompleteCtrl.hidden"\
                         md-autocomplete-parent-scope>' + template + '</li>'
                            : '';

                    }

                    function getInputElement() {
                        if (attr.mdFloatingLabel) {
                            return '\
            <md-input-container flex ng-if="floatingLabel">\
              <label>{{floatingLabel}}</label>\
              <input type="search"\
                  id="fl-input-{{$mdAutocompleteCtrl.id}}"\
                  name="{{inputName}}"\
                  autocomplete="off"\
                  ng-required="$mdAutocompleteCtrl.isRequired"\
                  ng-minlength="inputMinlength"\
                  ng-maxlength="inputMaxlength"\
                  ng-disabled="$mdAutocompleteCtrl.isDisabled"\
                  ng-model="$mdAutocompleteCtrl.scope.searchText"\
                  ng-keydown="$mdAutocompleteCtrl.keydown($event)"\
                  ng-blur="$mdAutocompleteCtrl.blur()"\
                  ng-focus="$mdAutocompleteCtrl.focus()"\
                  aria-owns="ul-{{$mdAutocompleteCtrl.id}}"\
                  aria-label="{{floatingLabel}}"\
                  aria-autocomplete="list"\
                  aria-haspopup="true"\
                  aria-activedescendant=""\
                  aria-expanded="{{!$mdAutocompleteCtrl.hidden}}"/>\
              <div md-autocomplete-parent-scope md-autocomplete-replace>' + leftover + '</div>\
            </md-input-container>';
                        } else {
                            return '\
            <input flex type="search"\
                id="input-{{$mdAutocompleteCtrl.id}}"\
                name="{{inputName}}"\
                ng-if="!floatingLabel"\
                autocomplete="off"\
                ng-required="$mdAutocompleteCtrl.isRequired"\
                ng-disabled="$mdAutocompleteCtrl.isDisabled"\
                ng-model="$mdAutocompleteCtrl.scope.searchText"\
                ng-keydown="$mdAutocompleteCtrl.keydown($event)"\
                ng-blur="$mdAutocompleteCtrl.blur()"\
                ng-focus="$mdAutocompleteCtrl.focus()"\
                placeholder="{{placeholder}}"\
                aria-owns="ul-{{$mdAutocompleteCtrl.id}}"\
                aria-label="{{placeholder}}"\
                aria-autocomplete="list"\
                aria-haspopup="true"\
                aria-activedescendant=""\
                aria-expanded="{{!$mdAutocompleteCtrl.hidden}}"/>\
            <button\
                type="button"\
                tabindex="-1"\
                ng-if="$mdAutocompleteCtrl.scope.searchText && !$mdAutocompleteCtrl.isDisabled"\
                ng-click="$mdAutocompleteCtrl.clear()">\
              <md-icon md-svg-icon="md-close"></md-icon>\
              <span class="md-visually-hidden">Clear</span>\
            </button>\
                ';
                        }
                    }
                }
            };

**Comment by Clan-Utility** [comment]
+1
And how to set max-length constraint on md-autocomplete?

**Comment by wcjr** [comment]
fyi, looks like there's a PR in process https://github.com/angular/material/pull/3366

**Comment by mikedobrin** [comment]
I solved it like this:
.directive('isRequired', ['$compile', function($compile) { return { restrict: 'A', terminal: true, priority: 1000, link: function(scope, element) { element.removeAttr('is-required'); if (scope.isRequired) { element.attr('required', 'required'); } $compile(element)(scope); } }; }])

**Comment by mikedobrin** [comment]
and isRequired on the scope is set by the parent  directive      From: billy clark <notifications@github.com>
 To: angular/material <material@noreply.github.com> 
Cc: Mike Dobrin <inter4_44094@yahoo.com> 
 Sent: Thursday, July 2, 2015 3:54 PM
 Subject: Re: [material] md-autocomplete: validation not working anymore in 0.10.0 (#3293)
   
fyi, looks like there's a PR in process #3366—

**Comment by robertmesserle** [comment]
This is resolved in master and will in the 0.10.1 release.

**Comment by evoker** [comment]
This doesn't seem to be working still.

he's my code:

````
<md-autocomplete required md-input-id="input_boundBallot" class="md-primary"
		ng-disabled="ac.isDisabled"
		md-input-name="boundStuff"
		md-no-cache="ac.noCache"
		md-autoselect="ac.autoSelect"
		md-select-on-match="ac.selectOnMatch"
		md-selected-item="ac.selectedStuff"
		md-search-text-change="searchTextChange(ac.searchText)"
		md-search-text="ac.searchText"
		md-selected-item-change="selectedItemChange(item)"
		md-items="item in searchStuff(ac.searchText)"
		md-item-text="item.display"
		placeholder="Select an item"
		ng-value="ac.searchText"
		md-min-length="0">
	<md-item-template>
		<span md-highlight-text="ac.searchText" md-highlight-flags="^i">{{item.display}}</span>
	</md-item-template>
	<md-not-found>
		No matches found for "{{ac.searchText}}".
	</md-not-found>
	<div ng-messages="aform.boundStuff.$error">
		<div ng-message="required">This field is required</div>
	</div>
</md-autocomplete>
````

I don't think there's anything wrong with the code.

Trying with latest master 5722449b372604fc2231f73140a44094c3a94cf8

**Comment by pencilcheck** [comment]
You might want to check if your aform is actually there. Print it out {{ aform.boundStuff }}
