### ISSUE TITLE
Update CDN to version 0.10.0 please

### ISSUE THREAD

**Issue by skolade** [angular/material#3294]
Thanks for all your hardwork!

**Comment by ramr0m** [comment]
+1 * <i>n</i>

**Comment by mukilane** [comment]
They are already available.
https://ajax.googleapis.com/ajax/libs/angular_material/0.10.0/angular-material.min.js
https://ajax.googleapis.com/ajax/libs/angular_material/0.10.0/angular-material.min.css

**Comment by skolade** [comment]
Thank @mukilane before I posted the issue it was not available!
