### ISSUE TITLE
Select: arrow keys (Up/Down) navigation do not work

### ISSUE THREAD

**Issue by ramr0m** [angular/material#3295]
Like issue #2443 arrow keys do not work (in IE11). This behaviour also occur without usage of md-dialog. See https://material.angularjs.org/latest/#/demo/material.components.select in Chrome and IE11. The sample "pick your pizza below" shows different behaviour on up/down. Typing a suggestion letter like "I" or "L" works like a charm in both browsers.

**Comment by sreekumarp** [comment]
any work around for this ? or is this fixed in some fork ?
