### ISSUE TITLE
mdMenu: add option to stop propagation when opening menu

### ISSUE THREAD

**Issue by Frank3K** [angular/material#3296]
Currently, an `md-menu` can be opened by setting `ng-click="$mdOpenMenu()"` on the button opener element. If one of the parents of the `md-menu` element also has a click-handler that handler is also triggered, which is not always the desired behaviour. 

It would be nice if the `$mdOpenMenu` method could be configured such that it does stop the propagation of the click event, e.g. by calling `$mdOpenMenu($event, true)`. For now, I have manually added a method `stopPropagation` on each scope in which I am using a menu. By using `ng-click="stopPropagation(); $mdOpenMenu()"`the same effect then can be reached.

**Comment by ThomasBurleson** [comment]
I think the click to open the menu should **never** propogate; since it is used to trigger the menu open only.
