### ISSUE TITLE
Background of button isn't disappearing after some clicks

### ISSUE THREAD

**Issue by lcasferreira** [angular/material#3297]
When are made consecutive clicks in a button, the background is not disappearing before the last click. The impression is that button stays focused.
The same result it's possible clickin in the browser with the left button and after right button. The button clicked stays with the focus.

**Comment by marcysutton** [comment]
How fast are you clicking? The browser natively focuses buttons on click, and we hack around that by only showing the focus style under certain conditions. It could be that your user interaction is too fast for the delay.

**Comment by lcasferreira** [comment]
The multiple clicks are fast and many times (on device), I think the same "user interaction is too fast for the delay". But in case of click with left and next with the right button is not necessary be fast.

**Comment by ThomasBurleson** [comment]
Fixed with lastest Ripple features (v0.11.0-rc2).
