### ISSUE TITLE
What about the DateTimepicker component was an feature component for the version 0.10 

### ISSUE THREAD

**Issue by rhelenagh** [angular/material#3298]
Hello Team, 

I would like to know what about the DateTimepicker component, that component was one of the key feature to the version 0.10. By the way congratulation to all the team for the version 0.10.0.

Regards

**Comment by ThomasBurleson** [comment]
The DateTimePicker was rescheduled for 0.11; but the Milestone had not been updated.

Here is *some* of the tasks for Milestone 0.11:

- DateTimepicker
- SpeedDial (cont)
- Menu (menubar, cascaded menus, hotkeys)
- Chips (cont.)
- textfields
  *  `<md-text-search>`
- bi-directional support (cont.)
- Slider range
- Performance improvements with ripples and ink

**Comment by rhelenagh** [comment]
Thanks!!
