### ISSUE TITLE
md-tabs: scope inside tabs is not the same as outside

### ISSUE THREAD

**Issue by gpothier** [angular/material#3300]
It seems the md-tabs tag establishes a new scope. Consider this html example:

	Data: {{ data }}
	<md-tabs flex md-border-bottom md-selected="selectedTab" >

		<md-tab label="A">
			<md-tab-body class="md-padding">
				Data: {{ data }}
				<md-button ng-click="data = 'bye'">Bye</md-button>
			</md-tab-body>
		</md-tab>
	
		<md-tab label="B">
		</md-tab>
	</md-tabs>

The "data" scope attribute can have an initial value:

	angular.module("docflow").controller("BooksListCtrl", 
	["$scope", "$rootScope", 
	function($scope, $rootScope){
		$scope.data = "hello";
	}]);

When the page is loaded, the initial value is displayed both inside and outside the tab. However, when clicking the button that changes the value, the new value appears only inside the tab; outside the tab it remains unchanged.

This violates the principle of least astonishment IMHO.

Please see this example Meteor app:

https://github.com/gpothier/mdTabIssues

**Comment by jeroenvheel** [comment]
i have the same problem !

**Comment by luclanet** [comment]
I still had the same problem even with rc5.

<div md-template="::tab.template" md-scope="::tab.parent" ng-if="tab.shouldRender()" class="ng-scope ng-isolate-scope">

**Comment by blockjon** [comment]
Same problem here.. cant figure out how to do data binding to input elements inside a tab.

**Comment by bonatoc** [comment]
@blockjon - I am able to data binding inside a tab. Are your tabs in a controller?

**Comment by manish2535** [comment]
I am getting this same issue and I am on RC 1.0.5

**Comment by and1gio** [comment]
i have same problem... i'm using tabs in dialog and can't bind variable to scope from md-tab content

**Comment by wilker7ribeiro** [comment]
+1
