### ISSUE TITLE
Issue closing md-dialog in IE10 overflow hidden stays behind

### ISSUE THREAD

**Issue by ragndahl** [angular/material#3308]
When a md-dialog is closed in IE10 the inline style attribute "overflow: hidden" is not removed.

**Comment by EladBezalel** [comment]
@ragndahl Can you please check if it's still occurring on HEAD and if it does create a codepen with the bug?

**Comment by EladBezalel** [comment]
closed due to inactivity, if it's still happening please say so and i'll open this issue.
