### ISSUE TITLE
Unknown provider: $mdBiDirectionalProvider

### ISSUE THREAD

**Issue by alijmlzd** [angular/material#3309]
when i use $mdBiDirectionalProvider like this:
```js
App.config(['$mdThemingProvider', '$mdBiDirectionalProvider', function($mdThemingProvider, $mdBiDirectionalProvider) {
   ...
}]);
```

it says:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module App due to:
Error: [$injector:unpr] Unknown provider: $mdBiDirectionalProvider
```

angular version: ~1.3.16
material version: ~0.9.8

**Comment by alijmlzd** [comment]
Any idea?

**Comment by sina-mirhejazi** [comment]
I have the same problem but error message is a little different
```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=vidad&p1=Error%3A%2…%2Fscripts%2Flibs%2Fbower_components%2Fangular%2Fangular.min.js%3A40%3A503)
```

any help?

**Comment by norkunas** [comment]
@sina-mirhejazi include non minified version of angular and then you'll see the problem

**Comment by sina-mirhejazi** [comment]
@norkunas so it's the same error
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:unpr] Unknown provider: $mdBiDirectionalProvider
```

**Comment by ThomasBurleson** [comment]
A pending Pull Request with this feature has **not yet** been merged.

**Comment by zehavibarak** [comment]
still missing mdBiDirectionalProvider...

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (608/500 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:53847 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdI-000Lje-PF
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:56 -0500
Date: Thu, 28 Apr 2016 13:32:23 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875543;
	bh=IcTXVXo0RouVDA591sMmqNm8RPfr3/nPpXUBSz+nrwk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=gkCQhBY3MhHzH9QRyytx17C7mp8dIwmTsUeuVIKJn5BOFKy6VfJcM4FFORoMfr+s3
	 NvJSZhVMwtRq/3fy2SkP/CsTHETN6EK1VkIf2tXSSchK7R4wej0ZmLZ5coeTlFxf/N
	 iZL5+2Yz7hvckVjiCaLHySViDHwZdh4hq1Q/Brmk=

**Comment by sajjad-shirazy** [comment]
waiting ...
