### ISSUE TITLE
docs : stay on the same page when switching the version

### ISSUE THREAD

**Issue by jgoux** [angular/material#3311]
Hello,
would it be possible to stay on the same page when switching the documentation version ?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (425/400 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:39490 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZm-001Z82-Fc
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:20 +0200
Date: Thu, 28 Apr 2016 13:27:43 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875263;
	bh=ZeP6/Ki8Zf+EfYRuM9tPZnJrzdfQ2TNQ1OT4g5NsDRI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=fXMDkpZLEBmZ5t9/qhzcJtta90PM+LxUzSrw6Rf6asqVGlr9RpPRHOhqDdHI7Ire5
	 wv4mOkVxvCLpFYu8IugnePl3x3PoB+yvlOfq+JbdEYCsi0qi/CB7U+Kvbc/TQrPspH
	 pm88N6nl1ikTdk2jVgZ2mzhysvvfHY1MUPpr8yy4=
