### ISSUE TITLE
fab speed dial cannot be hided using ng-hide

### ISSUE THREAD

**Issue by xforceco** [angular/material#3313]
When the dial is in open state, I trigger a variable to make expression in  ng-hide = true,  in an attempt to hide it but fails.
![pr2](https://cloud.githubusercontent.com/assets/12808889/8201728/1f9122b2-1506-11e5-88a0-9fa282b51e38.png)

**Comment by jameswyse** [comment]
Looks like the `ng-hide-animate` class isn't being removed after the animation.

**Comment by topherfangio** [comment]
Thanks guys, I'll take a look :-)
