### ISSUE TITLE
SideNav:  md-is-locked-open expected behavior 

### ISSUE THREAD

**Issue by xforceco** [angular/material#3317]
Recently I am trying md-is-locked-open in tutorial, with sth like this 

    <md-sidenav  class="md-sidenav-right md-whiteframe-z2" md-component-id="L1-right-nav" md-is-locked-open="$mdMedia('gt-md')"></md-sidenav>

When screen is large enough, it is locked and push everything on the left to the right.

![p1](https://cloud.githubusercontent.com/assets/12808889/8206030/742e7e6a-1528-11e5-8e4f-5d2cda10b69c.png)

When screen is small, i.e. $mdMedia('gt-md')==false, and when I manually toggle the SAME sidenav, it becomes full height.

![p2](https://cloud.githubusercontent.com/assets/12808889/8206032/77b0fd38-1528-11e5-804c-5091aeee0089.png)

Is it an intended expected behaviour? If it is, it is too strange, as I want to keep consistent, either full height or the other but not both when it comes to different screen sizes.

**Comment by Londovir** [comment]
It's extremely vague if you read the official Google Material Design specs: http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-behavior

The bottom line is "it depends on your use scenario". In some instances, this behavior (the default one in angular-material project) for md-is-locked-open is to have the sidenav docked into the page flow content. This is what Google refers to as a "permanent, clipped drawer" (if, that is, you layout the sidenav "below" the toolbar level in your markup).

If you disable lock open, the sidenav will float over the content at full height, referred to by Google as "temporary drawer" (more or less). However, if you read that page of the design specs, pretty much every combination of in-content, over-content, full-height, etc is an allowable use case, depending on the content of the page, the semantic need for the sidenav, etc.

In my projects, if I felt the need to keep a consistent layout design, I would usually end up combining logic to watch the value of $mdMedia along with a user preference, and bind the sidenav's lock open attribute to the combination of those two. That way even on smaller screen sizes, if the user opts to open it, you merely trigger the sidenav to be locked open as though it was a widescreen size, and you gain the benefit of the same visual appearance.

Whether that use case is appropriate per Material Design, though, is up to the reader...

**Comment by xforceco** [comment]
@Londovir Recently I would like to bind a variable to md-is-locked-open like md-is-locked-open="{{var1}}", but when var1 changes, it has not effect. Can you provide some hints on how to provoke the change?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
