### ISSUE TITLE
md-list-item preventing click event of elements which it contains in Firefox 38, IE10

### ISSUE THREAD

**Issue by bshir** [angular/material#3318]
An md-list-item containing a button is not recognizing the click event of the button.  

http://codepen.io/anon/pen/XbaOYO

Expected behavior:
Click anywhere on the list item outside of the button and only list count will increment.  Click the button and both button count and list count will increment.  

Actual behavior:  In Firefox 38 & IE10 clicking the button does not increment the button count; only the list count.

The button click is working in Chrome 43, Safari, and IE Edge

Related post from March discussing the topic of clickable list items combined with clickable child elements.  It looks like implementation has changed a bit since then with the md-list-item directive and wrapping contents in an md-button.  Still found this relevant though.
https://groups.google.com/forum/#!searchin/ngmaterial/md-list-item$20expand/ngmaterial/8A-UGPftGfA/fZk-2HEB3xoJ

**Comment by webpartisan** [comment]
Hello, you should add __class="md-secondary"__ attribut to md-button, without this you calling primary action (md-list-item ng-click) and then button click (md-button ng-click)

**Comment by bshir** [comment]
Thank you for that info!  I did not see it in the documentation previously.  I now see it in the demo with the list items containing checkboxes.  Thanks much!

Date: Thu, 18 Jun 2015 02:48:48 -0700

**Comment by webpartisan** [comment]
Oh, I deleted this answer, because I think you have another problem ) . Anyway it's bad that we have different behavior in different browsers. And I have problems with primary and secondary action in md-list-item

**Comment by bshir** [comment]
I agree...  after further testing I'm still having issues with more complex items.  Where each item is an editable ng-form with buttons.

**Comment by topherfangio** [comment]
Appears to still be broken in FF40. Will investigate IE10 too.

**Comment by topherfangio** [comment]
Appears to still be broken in RC2: http://codepen.io/topherfangio/pen/mejzbp

Will prioritize for RC4 (RC3 is coming too soon to get it in).

**Comment by topherfangio** [comment]
Interesting note for me later: you can actually tab to the inner button and press enter and it behaves exactly as expected. So it must be something specifically with the actual mouse click.

**Comment by EladBezalel** [comment]
@bshir can you please check if it's still happening on HEAD?

**Comment by kuhnroyal** [comment]
I can't click `.md-secondary` items in IE 10/11 and Firefox 44 with 1.0.5

**Comment by manish2535** [comment]
+1

**Comment by DevVersion** [comment]
@kuhnroyal Can you recheck your issue in `HEAD` again? I've changed a few things in the list, and now the button is separated from the content.

**Comment by AntonKL** [comment]
+1. We face the same problem

**Comment by ACDN** [comment]
There is a work around I've found for this issue.

If you use an md-icon as the md-secondary you can click it in Firefox. 

`<md-icon md-svg-icon="content:add" ng-click="ctrl.select(item)" class="md-secondary" >`                                
`</md-icon>`

**Comment by DevVersion** [comment]
@ACDN Did you recheck with `master` yet?

It seems to be fixed with the latest changes.
- http://codepen.io/DevVersion/pen/eZKgrG

**Comment by ACDN** [comment]
It does appear to be working.  Strange I just downloaded the latest files before testing.  Of well. Good to know that it is fixed.

**Comment by DevVersion** [comment]
@ACDN Awesome, thanks for the quick response.
