### ISSUE TITLE
md-select: Properly navigation between items with keyboards.

### ISSUE THREAD

**Issue by mbarakaja** [angular/material#3320]
Hello.

Right now, I am using the material design `v0.10.0`

With the `md-select` open, pressing a keyboard letter on it, takes me to the first matched item, that is correct. Then if I press the down or up arrow key, the selection does not go to the next or previous item, it goes to the last selected item again.

I think that is a unexpected and confusing behavior to the user.

Filtering the items with the keyboard, even just by the first letter, is really useful when you have a lot of options, like a list of countries.

I hope I have expressed properly.

**Comment by mramanauskas** [comment]
:+1: Also this md-select functionality completely doesn't work in dialogs, here is codepen: http://codepen.io/anon/pen/yNowJw?editors=101

**Comment by weisk** [comment]
Confirming. Using md-select on md-dialogs kills the keyboard navigation.

**Comment by mbarakaja** [comment]
This issue is fixed in the version `v0.10.1-rc1-master-861167a.`
