### ISSUE TITLE
md-tabs: centered by default

### ISSUE THREAD

**Issue by csvan** [angular/material#3321]
As of 0.10, it seems like the default alignment for md-tabs is now centered, and devs need to *md-center-tabs="false"* in order to avoid this. In 0.9, they aligned left by default.

**Comment by nkoterba** [comment]
@csvan Did you ever resolve this?

Both the Angular Material Design code-pen and demos when using 0.10, `md-tabs` are **not** centered by default.  However, in my webapp they are...and I can't figure out why they are "defaulting" to centered.

I've traced the scope and code and `$scope.centerTabs` is getting set to True but I never set the directive attribute so I'm not sure how it's going from `undefined` --> `true`

**Comment by csvan** [comment]
@nkoterba no, at the time we had to set them manually to get the desired behaviour. I am not aware what the status is in newer releases since we do not use md-tabs anymore.

**Comment by nkoterba** [comment]
@csvan I figured it what was happening.

Using 0.10 + Ang 1.4.3 => 'broke' tabs.

Ang 1.4.3 changed how optional directive attributes are passed to the Angular `$attrs` service.  Starting in Ang 1.4.3, it looks like angular will pass any optional directive attributes as `undefined`.  However, MD 0.10 was assuming that any attributes on the `$attrs` service, if present, should be set to true.

With the current MD release (0.10-RC5 at time of this post) + Ang 1.4.3 => Everything works again.

I could go into more details but don't think it's worth it.
