### ISSUE TITLE
md-button : The layout is now column based and aligned to center, causing Menu items to be centered instead of left aligned

### ISSUE THREAD

**Issue by TalPasi** [angular/material#3322]
As the following image shows, the items the menu items are centered and each of the item has a column layout instead of a row layout.

![image](https://cloud.githubusercontent.com/assets/1816536/8207095/e45d097e-14cc-11e5-86cb-acf500b18d52.png)

And when using a fab-button the icons is aligned to the top of the button

![image](https://cloud.githubusercontent.com/assets/1816536/8207152/4e04a724-14cd-11e5-8540-7786b4b1bdd1.png)

**Comment by asans** [comment]
This affect the current master version.  I am also experiencing similar issues to the "top down" button layout when it should be "left right" based.

It seems like the primary culprit is the display style for md-button has been set to inline-flex and flex direction is set to column.  

Setting this md-button back to inline-table as before did fix the issue, but not sure if it breaks any other component layouts.

**Comment by kuhnroyal** [comment]
See: https://github.com/angular/material/commit/b1046bc08f5e57674bf85c04c8c980d0b6e36c67

**Comment by Frank3K** [comment]
+1
