### ISSUE TITLE
md-tabs: md-tab-body does not scroll

### ISSUE THREAD

**Issue by csvan** [angular/material#3323]
As of 0.10, content inside md-tab-body no longer scrolls if it overflows the viewport. Wrapping the content itself and/or the md-tab directive does not resolve this.

**Comment by rhodul** [comment]
Has this been resolved? I'm still having the problem. Thanks.

**Comment by csvan** [comment]
I closed it only because I could not find a link to 0.10, which was the original premise of the issue. I still do have problems with scrolling in tabs at times, and the only way I have gotten it to work is CSS hacks.

**Comment by rhodul** [comment]
Google hosted js api's now have 0.10

-- Rastio
