### ISSUE TITLE
md-autocomplete compels you to click on dropdown item even typing the full word

### ISSUE THREAD

**Issue by ivanhtp** [angular/material#3324]
When typing on autocomplete, lets say "Alabama", the dropdown shows "Alabama", but if you don't click the dropdown item and just leave the focus, no object is selected.

I think if if you fully write an item, the directive should match with the object without require you to click it.

It could be bypassed in many ways, for example, when you blur the field, it automatically selects the first object of the list. Or if you type "Alaba.." and hit Enter, also selects the first item.

I tested this behavior with 11 people and 9 of them typed the full word without selecting the dropdown item. =/

**Comment by alexzielenski** [comment]
Have you tried the `md-autoselect="true"` attribute?

**Comment by ivanhtp** [comment]
Yeap. And it doesn't work as well.
I think md-autoselect is supposed to bring the first item by default on load, not on blur. But neither this  way the attribute does :/

http://codepen.io/ivan_htp/pen/eNVvxN

**Comment by alexzielenski** [comment]
http://codepen.io/anon/pen/rVJyRO

It's working by selecting the first attribute when I hit enter, but it would be bad UX to do so on blur.

**Comment by ivanhtp** [comment]
Its hard to say. Is a bad UX if you write just some characters, but if you
write the full word (eg. Alabama) and blur the field, it should select your
option.

**Comment by robertmesserle** [comment]
@ivanhtp I believe this is how it originally functioned, but was changed upon user request.  I'm going to add a way to opt in/out for this behavior.

**Comment by ivanhtp** [comment]
Good to know @robertmesserle, thanks for your feedback!
