### ISSUE TITLE
Angular-material not compatible with Angular 1.4.1

### ISSUE THREAD

**Issue by sethx** [angular/material#3325]
After upgrading angular and angular-animate to 1.4.1 i get a lot of errors in my console, and things behave quite oddly.

http://postimg.org/image/vpvt98jjf/ for a screenshot of my console.

**Comment by nomack84** [comment]
Well, the `$animate` service was completely refactored, so this is normal.

**Comment by sethx** [comment]
And that's why i want to open an issue about this.

**Comment by gkalpak** [comment]
Possible duplicate of #3280.

**Comment by jlmagee** [comment]
@nomack84 There are no commits to indicate significant changes in $animate in 1.4.1

**Comment by csvan** [comment]
Confirming this. md-tabs among other things have gone completely bonkers after upgrading to 1.4.1 (content not scrolling, dead animations etc).

**Comment by ShahZafrani** [comment]
@csvan I am having the same problem. Only 2 out of 3 tabs on my md-tabs element are showing. My md-select has also gone bonkers.

**Comment by ThomasBurleson** [comment]
@matsko - FYI, it appears that 1.4.1 is causing issues with Angular Material.

**Comment by mprokopowicz** [comment]
Guys, I think it can be related to #3315

**Comment by ThomasBurleson** [comment]
Thx to @mprokopowicz  for the code fixes in mdUtils.
> BTW, @mprokopowicz what process did you use to track the issue source back to `initOptionalProperties()`?
