### ISSUE TITLE
Outline border on click

### ISSUE THREAD

**Issue by davidedellai** [angular/material#3327]
Hi, using firefox i found a problem; you can see here for example:

https://material.angularjs.org/latest/#/demo/material.components.sidenav

when you click the toggle to open the slide. The button shows a outline dotted border. This happens for every component i use that needs a click. Also when i click in a cell of a table. It highlights the cell with this horrible outline border... Is there a workaround to remove it?

**Comment by ThomasBurleson** [comment]
Unable to reproduce with FireFox 38.0.5.  Please provide more specific details.

**Comment by pavelhoral** [comment]
It is this issue - http://stackoverflow.com/a/199319/865403 . Workaround (copied from SO):

    button::-moz-focus-inner {
      border: 0;
    }
