### ISSUE TITLE
Add ability to set max width in $mdDialog.confirm()

### ISSUE THREAD

**Issue by rtrix** [angular/material#3335]
When using $mdDialog.confirm(), a long content string will result in an extremely wide dialog. We'd like the ability to set a max width for the dialog.

**Comment by jelbourn** [comment]
I think this could potentially be solved by letting users specify one or more CSS classes to be applied to a dialog when it's opened.

**Comment by ThomasBurleson** [comment]
:+1: on the **add CSS classes** idea.
For now you can use the `.content( )` API to specify HTML content with breaks and spans and classes...
