### ISSUE TITLE
fap speed dial tooltip not positioned correctly

### ISSUE THREAD

**Issue by xforceco** [angular/material#3338]
Each time after a FRESH load of the page, when I hover the button I get this

![pr2](https://cloud.githubusercontent.com/assets/12808889/8223446/526ef16a-15aa-11e5-86fb-64bfee794ca3.png)

But when I move away the mouse and hover again, I get this

![pr3](https://cloud.githubusercontent.com/assets/12808889/8223450/55ded9be-15aa-11e5-9a1a-fe47bfb5d53f.png)

**Comment by topherfangio** [comment]
Thanks @xforceco! There are a couple of other issues with tooltips. I will try to get these all resolved at the same time.
