### ISSUE TITLE
Can't programmatically click file input element after resolving $mdDialog or $mdBottomSheet promise

### ISSUE THREAD

**Issue by remcohaszing** [angular/material#3340]
The following code promts the user to select a file:
```js
var input = document.createElement('input');
input.type = 'file';
input.click();
```
However, if this code is called after resolving the promise of an `$mdDialog` or `$mdBottomSheet`, the click function doesn't work.

I have tried using `$timeout` functions and indirectly calling promises of newly created deferred objects, but it simply doesn't work.

I have created a [plunkr](http://plnkr.co/edit/8dHRqwFOLxVtqsSq29pA?p=preview) to demonstrate this issue.

**Comment by kuhnroyal** [comment]
You can only issues click events as a direct result of user input, not in promises. Try this: (quick copy+paste) http://plnkr.co/edit/MC7bseMh0SksNwWbzE6m?p=preview
