### ISSUE TITLE
md-autocomplete opens a blank suggestion box in ie.

### ISSUE THREAD

**Issue by prashant1587** [angular/material#3341]
In IE all versions 11,10 and 9, the sugggestions box for md-autocomplete opens up with no values after i have successfully updated a value from the suggestion box. it does not close even after clicking outside.

![image](https://cloud.githubusercontent.com/assets/8696800/8229755/53a25040-15d7-11e5-949e-4a0db9de26da.png).

This empty suggestion box go a long way down in the view port.

here is the code 
here is the code i am using:

                                              <md-autocomplete ng-required="isRegYearVisible"
                                            md-input-name="registraionDetails" 
                                            ng-disabled="isRegionDisabled"
                                            md-no-cache=true
                                            md-selected-item="selectedCityItem"
                                            md-search-text-change="searchRegionTextChange(regionSearchText)"
                                            md-search-text="regionSearchText"
                                            md-selected-item-change="selectedRegionItemChange(regionItem)"
                                            md-items="regionItem in region | filter: {display: regionSearchText}"
                                            md-item-text="regionItem.value" 
                                            md-min-length="2"
                                            placeholder="Select City">
                                        <md-item-template>
                                            <span md-highlight-text="regionSearchText" md-highlight-flags="^i">                  {{regionItem.display}}</span>
                                        </md-item-template>
                                        <md-not-found>
                                            No matches found for "{{regionSearchText}}".
                                        </md-not-found>
                                    </md-autocomplete>

**Comment by tolemac** [comment]
+1

**Comment by AhmedReda89** [comment]
+1

**Comment by jelbourn** [comment]
@prashant1587 can you provide a demo?

**Comment by robertmesserle** [comment]
@topherfangio Could this be related to the issue you resolved recently related to virtual repeater?

**Comment by topherfangio** [comment]
@robertmesserle It's possible, but I think this may have been a separate issue because the virtual repeat bug still allowed you to select items/close using the keyboard/mouse.

I can take a look at it on my IE machine tomorrow morning and see if I can reproduce.

**Comment by topherfangio** [comment]
@robertmesserle I am not immediately able to reproduce this on my IE machine in Edge or 11/10/9 in emulation mode. I think we'll definitely need a demo to investigate further.

**Comment by prashant1587** [comment]
After I upgraded to material 0.10.0 the issue stopped so now I not able to reproduce the issue
