### ISSUE TITLE
Inactive tabs are removed from DOM since rc4. Persistent flag possible?

### ISSUE THREAD

**Issue by jo-me** [angular/material#3342]
Commit https://github.com/angular/material/commit/8dcaea8af19a6dcc2d9cafdd2ebb4277e66e89ae for 0.10rc4 introduced a new behavior for tabs that removes inactive tab pages from the dom using a ng-if.

In my use case I have Google Maps on one tab and some detail info on a second tab. 
In this scenario, the commit has the effect that the map (along with everything else that is on the tab) is removed from the DOM and has to be recreated each time the user switches back and forth. 

While I realize that removing invisible elements from the DOM can be beneficial for memory & performance reasons this might not be the case for complex elements such as a preinitialized map that has a certain state. In my situation I can restore the map with the information on it but I don't keep track of the user's current viewport (selected element , zoom, etc.).

What do you think of the concept of "persistent" vs. "transient" tabs? 
That way you could control whether certain tabs can be destroyed while some remain in memory.

**Comment by zlovin** [comment]
I have a use case where I use an ng-include to render partials into the tab's content, and it does some odd flashing when I switch between tabs because it has to be re-rendered each time.

+1

**Comment by robertmesserle** [comment]
This should be closed now, as this is now opt-in behavior.
