### ISSUE TITLE
mdDataTable: multi-column table component

### ISSUE THREAD

**Issue by mukilane** [angular/material#3343]
![DataTable](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3mOPoJlxiFhV25CdGNXYzA4cXM/components_datatables_structure_basictable.png)

> See Material Design [DataTable](http://www.google.com/design/spec/components/data-tables.html) specification.

**Comment by ThomasBurleson** [comment]
@mukilane - This is a very important component for Angular Material and any UI Component library. 

With the current schedule and goals for v1.0, however, the mdDataTable will be implemented after the v1.0 release of Angular Material.

**Comment by mukilane** [comment]
+1 @ThomasBurleson

**Comment by mbarakaja** [comment]
+1 for this component.

**Comment by emanuelvictor** [comment]
+1 @ThomasBurleson

**Comment by EladBezalel** [comment]
a dup #796 ?

**Comment by ThomasBurleson** [comment]
Yes. Thx @EladBezalel - closing this one and reopening 796 for m post-1.0

**Comment by tuchk4** [comment]
+1

**Comment by AleksueiR** [comment]
:+1:

**Comment by rudzikdawid** [comment]
+1

**Comment by dmaslov** [comment]
+1

**Comment by balkonsmoke** [comment]
+1

**Comment by mvolodin** [comment]
+

**Comment by WolfMessing** [comment]
+1

**Comment by jakubweber** [comment]
+1

**Comment by VikramTiwari** [comment]
@ThomasBurleson When should we expect this to be implemented?

**Comment by VikramTiwari** [comment]
:+1:

**Comment by marcoriesco** [comment]
+1

**Comment by tuchk4** [comment]
With the current schedule and goals for v1.0, however, the mdDataTable will be implemented after the v1.0 release of Angular Material.

@ThomasBurleson Could you please provide rude estimate for v1.0 and md-data-table component? This is very important component and a lot of teams and developers are waiting for it.

**Comment by josh256** [comment]
+1

**Comment by Greynight** [comment]
+1

**Comment by hmiguel** [comment]
+1

**Comment by FlipOneDev** [comment]
+1
