### ISSUE TITLE
Weird validation css classes for input[type=email] when ngMaterial is included in the app

### ISSUE THREAD

**Issue by lucassus** [angular/material#3348]
For some reason when ngMaterial is included in the app css classes like `ng-valid`, `ng-invalid` are not being correctly set on the input[type=email].

Here's an example http://plnkr.co/edit/a7nxMr1CPq6vdZF83Rna?p=preview
It was tested with ngMaterial 0.10.0 and AngularJs 1.4.1

![gif](http://g.recordit.co/X60hSLY52e.gif)

**Comment by gkalpak** [comment]
This might be related to `ngAnimate` (not `ngMaterial` itself). There is a similar issue open on the angular.js repo.

**Comment by gkalpak** [comment]
This is the issue I was referrign to: https://github.com/angular/angular.js/issues/12007
Most probably, it is an `ngAnimate` issue and happens with `ngMaterial` too, because the latter depends on the former.
