### ISSUE TITLE
tab demo does not work on angular 1.4.1

### ISSUE THREAD

**Issue by amitport** [angular/material#3353]
[tab demos](https://material.angularjs.org/latest/#/demo/material.components.tabs) does not work properly on angular 1.4.1 (animation flicker + tabs are aligned to center instead of left)

(everything works fine when I revert to 1.3.16)

**Comment by sitic** [comment]
angular 1.4.0 also works, seems specific to angular 1.4.1.

**Comment by robertmesserle** [comment]
Tracking by #3434 because it includes CodePen demo.
