### ISSUE TITLE
ng-disabled on md-icon in md-list-item does not work

### ISSUE THREAD

**Issue by shalabhaggarwal** [angular/material#3356]
When ng-disabled is applied on md-icon acting as a secondary on md-list-item, it does not have any effect on the dynamically generated button which still fires.

Here is a codepen: http://codepen.io/anon/pen/bdoqLb

**Comment by mukilane** [comment]
Duplicate of #3176 
Pls close.

**Comment by shalabhaggarwal** [comment]
I dont think #3176 covers the case for ng-disabled.

**Comment by topherfangio** [comment]
Appears to still be an issue in 1.0.0-rc2: http://codepen.io/topherfangio/pen/EVpeBV

Prioritizing for RC4 (don't think we can get it into RC3).

**Comment by topherfangio** [comment]
This has a PR waiting, but it looks like I need to rebase it before we merge. Will definitely get this merged into RC6.
