### ISSUE TITLE
Setting width on select has to use label

### ISSUE THREAD

**Issue by Sam-Davis** [angular/material#3358]
This issue occurred after I went to version 0.10.0. 

See: http://codepen.io/anon/pen/MwEmOV

If I use a label with a width on the label, then the label will always display and the selected option does not display. See 'select' with 'setting width issue'. 

There seems to be a need for css on the label and not the select tag in order to set the width. Thus, I was only able to set the width by adding the following css: 

md-select-label {
  min-width:500px !important;
}

adding this to the select tag does not do anything and the !important is required to set the width.

**Comment by ngraef** [comment]
Related: #3055

**Comment by rschmukler** [comment]
This is fixed on master. Closing.
