### ISSUE TITLE
Angular Material Without Angular

### ISSUE THREAD

**Issue by athmangude** [angular/material#3359]
How can I use Angular Material in a normal barebones html, css and JavaScript app without Angular?

**Comment by ivanzvakoms** [comment]
It is not possible at all. You can try polymer version

**Comment by stunaz** [comment]
I think that those kind of questions should better be asked in the angular material forum https://groups.google.com/forum/#!forum/ngmaterial

**Comment by jelbourn** [comment]
All of the component are built on top of AngularJS.
