### ISSUE TITLE
Allow responsive breakpoint to be modified on bower component via variables.scss

### ISSUE THREAD

**Issue by ivanzvakoms** [angular/material#3360]
It is great that I can decorate $mdConstant, but I also want to redefine default  media breakpoint in css. For now it is possible by some workaround like some gulp task to simple replace values, but It would be great to expose this possibility in bower component via scss.

Actually I don't understand reasons why this possibility isn't presented yet.

**Comment by ThomasBurleson** [comment]
@ivanzvakoms - If you offered a Pull Request for this enhancement, it would be welcomed.

**Comment by mackelito** [comment]
@ivanzvakoms Hey! I'm looking to do similar things so I was wondering how you decorat the $mdConstant?

**Comment by ivanzvakoms** [comment]
This is already done, because as I see in angular-material folder expose their breakpoints in "angular-material.scss". Because earlier it was possible only via gulp task.

Decaorating it easy:
```
$provide.decorator('$mdConstant', mdConstantDecorator);
function mdConstantDecorator($delegate) {
      $delegate.MEDIA = {
        'sm': '(max-width: 320px)',
        'gt-sm': '(min-width: 320px)',
        'md': '(min-width: 320px) and (max-width: 710px)',
        'gt-md': '(min-width: 710px)',
        'lg': '(min-width: 710px) and (max-width: 1025px)',
        'gt-lg': '(min-width: 1025px)'
      };

      return $delegate;
    }
```
