### ISSUE TITLE
md-icon does not respond to changes in md-font-icon

### ISSUE THREAD

**Issue by DaveWM** [angular/material#3361]
In 0.10.0, when you change the value of the `md-font-icon` property of an `md-icon`, the icon doesn't actually change. It was working in 0.9.8. See [this codepen](http://codepen.io/anon/pen/doVWLo) for a demonstration. I'll submit a PR for this if I get time.

**Comment by stalinb87** [comment]
+1

**Comment by ThomasBurleson** [comment]
@DaveWM - your PR would be welcome. Thx.

**Comment by DaveWM** [comment]
looks like this has already been fixed in master, should be working in the next release

**Comment by ThomasBurleson** [comment]
@DaveWM - please not that `md-font-icon` is considered a **static** value. Runtime databinding changes to that attribute are not currently supported.
