### ISSUE TITLE
layout-align: Reseting align-items to 'stretch'

### ISSUE THREAD

**Issue by jamesbrobb** [angular/material#3362]
I have a layout that only changes once it hits the breakpoint for `layout-gt-lg`. So it's primary layout is for smaller screens and it only needs to change to the secondary layout if it's displayed on anything larger than 1200px.

So my strategy for this is to use `layout` to define the standard layout and `layout-gt-lg` for anything above 1200px.

The issue i've come across using this strategy, is that if you have any element that needs both values of `layout-align` to be set - i.e `layout-align="space-between center"` - but you only need `justify-content` to be set in  `layout-align-gt-lg` - i.e `layout-align-gt-lg="space-between"` - it's not possible to supply a second value to set `align-items` back to its default value of `stretch`.

So this is my mark up:

```
<div layout="row"
     layout-gt-lg="column"
     layout-align="space-between center"
     layout-align-gt-lg="space-between">

    <div></div>
    <div></div>

</div>
```

So because `align-items` has been set to `center` for `layout`, it's also then used for `align-items` of `layout-gt-lg`. As i can't supply a second value to `layout-align-gt-lg` to set `align-items` back to the default value of `stretch`.

So what i need is:

```
<div layout="row"
     layout-gt-lg="column"
     layout-align="space-between center"
     layout-align-gt-lg="space-between stretch">

    <div></div>
    <div></div>

</div>
```

I'm not sure if i'm missing something, but it seems strange that all values for `justify-content` are available for `layout-align`, but there are values missing for `align-items`?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
