### ISSUE TITLE
mdSelect - require attribute in 'multiple' mode

### ISSUE THREAD

**Issue by slnowak** [angular/material#3363]
Hi,

I'm trying to achieve the following:
Given md-select directive within a form and a submit button, I'd like to keep submit button enabled as long as there is at least one option selected, disabled otherwise. 
I'm also using ngMessage to show error message indicating that field is required. 

Here's the snippet:

       <md-input-container>
          <md-select required multiple id="publishers" ng-model="announcement.publishers"
                   placeholder="Choose publishers" name="publishers">
           <md-option ng-repeat="publisher in availablePublishers" ng-value="publisher.value">
              {{ publisher.name }}
           </md-option>
         </md-select>

        <div ng-messages="announcementForm.publishers.$error" role="alert">
          <div ng-message="required">
            At least one publisher should be specified!
          </div>
        </div>
      </md-input-container>

      ...
      <button type="submit" ng-disabled="announcementForm.$invalid">Publish!</button>

Now, the are two issues with that:
1) to make 'required' attribute work, I need to set publisher's initial value to an empty string instead of an empty array
2) If I select a few options within md-select and then deselect them, md-select sets publishers field on my model to an empty array, which kind of makes sense. The thing is, 'required' attribute expects empty string again, so I need to hack this around by invoking 
md-on-close="setEmptyIfNoPublisherSelected()"
which basically checks if publishers array is empty and if it is, it substitutes it with an empty string again...

Am I missing something? Is it a correct behaviour?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by tniezurawski** [comment]
Hi,
How can I ask for reopen?

I believe the bug still exists. I've prepared plunker for you guys with two examples to show that select with multiple and required attributes works in Angular but it does not work with md-select:
http://plnkr.co/edit/fSU1VK1dyQUmSCwUzCMz?p=preview

Tested on versions: 0.11.0 (plunker) and 0.10.1 (within my team's work).
