### ISSUE TITLE
feat(chips, contact-chips): support md-separator-keys

### ISSUE THREAD

**Issue by websirnik** [angular/material#3365]
Currently, the trigger to add a chip is ENTER keydown event. I think it's a good idea to add custom keycodes that would trigger a new chip. For email chips - "," " " are useful triggers.
Here is the use-case:
![2015-06-19 12_02_57](https://cloud.githubusercontent.com/assets/282871/8252183/2628da0e-167b-11e5-9414-33c7d73c30d1.gif)

**Comment by mukilane** [comment]
+1

**Comment by mdekrey** [comment]
:+1:

**Comment by jproby** [comment]
:+1:

**Comment by Frank3K** [comment]
+1

**Comment by typotter** [comment]
This is a fair proposal.

**Comment by alexbooker** [comment]
I would very much like this, too.

**Comment by hnpatel20091** [comment]
+1

**Comment by Frank3K** [comment]
For regular chips this can be done using `md-separator-keys`. For contact chips, there is an active PR (#8142).

**Comment by ThomasBurleson** [comment]
Pull Requests would be welcomed.

**Comment by Frank3K** [comment]
There is already an active pull request for `md-contact-chips`. For `md-chips` it's already implemented.

**Comment by ThomasBurleson** [comment]
@Frank3K - PR #?

**Comment by Frank3K** [comment]
#8142

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by Splaktar** [comment]
This is only open to track the support in contact-chips which has an open PR https://github.com/angular/material/pull/8142.

Support for this feature already exists in regular chips.

**Comment by Splaktar** [comment]
Contact-chips support PR merged in https://github.com/angular/material/commit/eb10b56cbc29e59c669076142cf0a91e1d84d175.
