### ISSUE TITLE
Bug: md-autocomplete does not remove div.md-scroll-mask after losing focus.

### ISSUE THREAD

**Issue by mbarakaja** [angular/material#3371]
**md-autocomplete** when focused, adds a **div.md-scroll-mask**  element on top of other elements.

But randomly, it does not remove the mask element after losing the focus. Blocking any interaction with the other components under the mask, leaving the application unusable.

This happening to me in Google Chrome with the version **0.10.0** of Angular Material. I see this same bug in the Angular Material demo [demo](https://material.angularjs.org/latest/#/demo/material.components.autocomplete) page.

**Comment by gustavoaalves** [comment]
I'm also with this same problem

**Comment by jgoux** [comment]
This is related to : https://github.com/angular/material/issues/3287
This is a major bug because the entire app is unusable.

**Comment by mbarakaja** [comment]
+1

**Comment by tolemac** [comment]
is it solved? why is closed?

**Comment by jgoux** [comment]
@tolemac I think it is closed because it's a duplicate of https://github.com/angular/material/issues/3287

**Comment by tolemac** [comment]
oh! yes @jgoux, I thought you had closed your topic because of this, it's the opposite.
Sorry and thanks ;)

**Comment by cnjsstong2** [comment]
+1

**Comment by hitigon** [comment]
+1

**Comment by matheusamaral** [comment]
+1

**Comment by jmcpeak** [comment]
+1

**Comment by DaHaiz** [comment]
+1

**Comment by neonko** [comment]
+1

**Comment by idiron** [comment]
+1

**Comment by bastianwegge** [comment]
+1

**Comment by berkyl** [comment]
+1

**Comment by alexkb** [comment]
+1

**Comment by arne-s** [comment]
+1

**Comment by gbaj** [comment]
+1

**Comment by alzalabany** [comment]
+1

**Comment by Kratos-SA** [comment]
+1

**Comment by qrpike** [comment]
+1

**Comment by mschering** [comment]
This has not been fixed in 1.10-rc5.

**Comment by DevVersion** [comment]
@mschering This issue is closed. Please submit a new issue, if you're able to reproduce the issue in the latest version.

Please notice, that a Codepen is desired.

**Comment by nicolac18** [comment]
+1

**Comment by RooTooZ** [comment]
+1

**Comment by ravzski** [comment]
+1

**Comment by rolintoucour** [comment]
+1

**Comment by mzaarour** [comment]
+1
Please solve it, the whole app is unusable

**Comment by TomSeldon** [comment]
Not sure why this issue has been closed, it's still very much a problem.

**Comment by DevVersion** [comment]
@TomSeldon This issue is was closed because it seems to be fixed within 0.10.1 (https://github.com/angular/material/issues/3287#issuecomment-118993333).

I'm also not able to reproduce that issue anymore. Please **submit** a new issue by following the issue template. Including a proper demo.

**Comment by orenagiv** [comment]
Doesn't seem like this is resolved.
Continued here:
https://github.com/angular/material/issues/3287#issuecomment-118993333
