### ISSUE TITLE
Sidenav: will scroll to outside of page, if there's any tag outside Sidenav's container

### ISSUE THREAD

**Issue by butaixianran** [angular/material#3372]
## Here is an example about this issue:

```` html
<body ng-controller="AppCtrl">

    <div>If there is anything here, the Sidenav will have a scroll bar and scroll to outside of the page</div>

<!-- This is the container of sidenav -->
<div layout="row">
   <md-sidenav md-component-id="left" class="md-sidenav-left">
        This is a sidenav
    </md-sidenav>
</div>
</body>
````

## Check this image:
![sidenav issue](https://cloud.githubusercontent.com/assets/5558722/8265922/823c4278-1742-11e5-98b5-d126fa3e10cb.jpg)

## Check following show cases:
1. Modified from official example, just put a button at top, then this issue shows:
http://codepen.io/butaixianran/pen/EjwQqz

2. A very simple show case, make this issue even more clear:
http://codepen.io/butaixianran/pen/EjwQBJ

3. A more complex and more real case with sidenav at both side:
http://codepen.io/butaixianran/pen/LVzQXw

## Both left and right sidenav have this issue.

Need a work around for now.
In my case, I have to put the right sidenav in a route template. So the right sidenav always scrolls to the outside of the page....

Thanks

**Comment by dohomi** [comment]
Hi, quick feedback how I solved it currently: I assigned the wrapping div container with '''position:relative'''. This fixed it in my usecase.

**Comment by butaixianran** [comment]
hi, thanks for your solution, but it doesn't work at all, even with the simplest case:
http://codepen.io/butaixianran/pen/EjwQBJ

With style="position:relative", the sidenav just won't show up anymore.

**Comment by QuantumInformation** [comment]
I also have this issue.

**Comment by robertmesserle** [comment]
Appears to be fixed in master
