### ISSUE TITLE
How good md-select works in dialog?

### ISSUE THREAD

**Issue by asinha123** [angular/material#3378]
Hi,
I found an issue with md-select. When I try to open options for md-select in a form which I have opened in a dialog, I am not able to see that. Is this something with the z-index issue?

Also I have concern for the floating label for md-select which is not there but the feature is available for the input box. Any update on this.

Thanks in advance

**Comment by rschmukler** [comment]
Per [this demo](http://codepen.io/rschmukler/pen/WQgKBR) this issue is resolved. Please open a new issue with a demo if this is not true.
