### ISSUE TITLE
md-grid-list Horizontally align items and scroll items

### ISSUE THREAD

**Issue by rdefeo** [angular/material#3380]
Although typically vertical scrolling is used the spec does mention that horizontal scrolling is correct in some cases.
http://www.google.com/design/spec/components/grid-lists.html#grid-lists-behavior

What would be required to implement this in the project? Any guidance would help a lot.

Thanks

**Comment by shyndman** [comment]
Hey @rdefeo,

Nothing is preventing you from placing a gridlist in a horizontally scrollable container. Take a look: http://plnkr.co/edit/lIVXCXufSwE6jkeoj4Pz?p=preview

Create a container with `overflow-x: auto`, and give the gridlist a width. Simple as that.
