### ISSUE TITLE
md-radio-button doesn't support attribute bindings

### ISSUE THREAD

**Issue by pjr0009** [angular/material#3381]
I prefer to use `ng-bind` over `{{}}`, and noticed that md-radio-button doesn't support this usage. For example 

```
%md-radio-button.md-primary{ng-repeat: "network in networks", ng-value: "network.id"} {{network.name}}

```

works, however

```
%md-radio-button.md-primary{ng-repeat: "network in networks", ng-value: "network.id", ng-bind: "network.name"} 

```

doesn't. 

It only displays the text value, and the radio buttons are missing, i.e. 
![screen shot 2015-06-21 at 12 58 05 pm](https://cloud.githubusercontent.com/assets/2034412/8272765/cf656f7e-1815-11e5-8a19-dad049c66357.png)

when it should be:

![screen shot 2015-06-21 at 1 03 08 pm](https://cloud.githubusercontent.com/assets/2034412/8272766/e765bea8-1815-11e5-9d4e-a0deafaa76df.png)

**Comment by cshin-netfore** [comment]
+1

**Comment by SylvainBigonneau** [comment]
Happens also with `md-checkbox` apparently. Same workaround can apply.
