### ISSUE TITLE
Complete api docs in official site

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#3386]
Is there any place where i could find any complete API of this framework?.. it lacks on docs, specially the dialog, i mostly have to see the examples rather than checking the api

**Comment by thvd** [comment]
Did you see:  https://material.angularjs.org/latest/#/api/material.components.dialog/service/$mdDialog#alert?

**Comment by Nosthertus** [comment]
yes, but what i mean, is that it seems the api does not explain everything, an example would be on $mdDialog.show(); where the template must have <md-dialog> and <md-dialog-content>
