### ISSUE TITLE
Speed Dial doesn't animate when using ng-class.

### ISSUE THREAD

**Issue by mukilane** [angular/material#3389]
The Speed Dial doesn't animate when I specify the animation mode (md-scale or md-fling) in a ng-class attribute.
```    
<md-fab-speed-dial md-direction="left" ng-class="md-scale" >
```
But, upon adding it to the class attribute, it animates.

```    
<md-fab-speed-dial  md-direction="left" ng-class="md-scale" class='md-scale'>
```

**Comment by Frank3K** [comment]
I also encountered this issue while working with the speed dial. Since I only needed a static class moving from `ng-class` to `class` solved the issue for me, but there are situations where this is not possible.

**Comment by topherfangio** [comment]
Thanks guys, I will take a look and see why it fails with `ng-class`.

**Comment by topherfangio** [comment]
@mukilane @Frank3K It just struck me that the [demo](http://localhost:8080/dist/docs/index.html#/demo/material.components.fabSpeedDial) uses `ng-class`, so I'm a bit curious as to why it's not working for you.

Could either of you provide some example code that fails?

Just looking at your snippet above, I'm not sure you're using `ng-class` the proper way as you usually pass an expression, not a simple string. Can you double-check the [ngClass docs](https://docs.angularjs.org/api/ng/directive/ngClass) and make sure it isn't an issue with your code?

**Comment by mukilane** [comment]
@topherfangio Here's a codepen with two Speed Dials, one(second) with class='md-scale' and the other(first) without.
http://codepen.io/anon/pen/KpyoKZ

**Comment by topherfangio** [comment]
Unfortunately, you cannot pass a simple string to ngClass, you must use one of the documented methods.

Here is a quick example modified from your pen: http://codepen.io/topherfangio/pen/YXEaxW

**Comment by mukilane** [comment]
+1 @topherfangio 
I must have read the AngularJS Doc first.
Yet, the class='md-scale'  makes it work.  And, it's more simpler to implement. 
Are there any drawbacks when using this method. Or should I use only ng-class ?

**Comment by topherfangio** [comment]
You should feel free to use either method.

The only thing to consider is that if you need/want to change the class dynamically, you should definitely use the ngClass approach as it will notify the speed dial using [$animate](https://docs.angularjs.org/api/ngAnimate) rather than just swapping the CSS class. Honestly, I'm not sure this will make a difference now, but later I'd like to have smooth transitions between the animation types :-)

**Comment by mukilane** [comment]
+1

**Comment by dadoadk** [comment]
+1
I used also ng-class="{ 'md-scale': true }" and it worked.
