### ISSUE TITLE
md-dialog not closing on android

### ISSUE THREAD

**Issue by fant0m** [angular/material#3392]
Hello,
closing the dialog is not working for me on android(4.0). Dialog opens normally but when I press "OK" just nothing happens. Has anyone else noticed that or it's problem at my website?

**Comment by mckenzielong** [comment]
Which browser are you talking about? the default browser? On 4.0, this is an old version of webkit, and most likely isn't supported:

>Angular Material is targeted for all browsers with versions n-1; where n is the current browser version.

If you are talking specifically about the webview, then a project like [Crosswalk](https://crosswalk-project.org/) (which replaces the webview with a version of Chromium, giving you all kinds of enhancements over the ICS webview) will give you a webview that can run the project.

**Comment by fant0m** [comment]
I'm talking about doplhin browser. I know about browser support but that's a lot of android phones using version 4. Everything else is working ok for me. I don't think it would be hard to fix that, it's just a button and removing that md-dialog :+1:

**Comment by naomiblack** [comment]
Sorry, Android 4.0 is below our minimum support.
