### ISSUE TITLE
md-button with href and icons

### ISSUE THREAD

**Issue by tuchk4** [angular/material#3393]
Hello

Here is example http://codepen.io/anon/pen/pJWXXX

As you can see - if we add href to <md-button> - icons and text will be with wrong vertical alignment.

But seems all is ok if use without <menu> - http://codepen.io/anon/pen/XbevRj 

Any ideas to fix this? Or this is a bug?

**Comment by ThomasBurleson** [comment]
The CodePen using the latest source (from Master) works correctly:

http://codepen.io/team/AngularMaterial/pen/jPGgvb
