### ISSUE TITLE
events and directives not working on md-tab

### ISSUE THREAD

**Issue by andela-omesanni** [angular/material#3395]
Hi,
I am currently working on a project and a couple of angular events aren't triggering when those events take place. 

```
md-tabs(md-selected="selectedIndex" md-theme="makerSourceTheme" md-center-tabs="false")
  md-tab(ng-repeat="section in phase.sections | orderBy:'position'"
      label="{{section.name}}"
      ng-dblclick='editItem'
      dnd-dragover="aboutToDrop($index)"
      dnd-list='section.cards' )
```

From above, the ng-dbclick doesn't trigger when I double click. Also ng-mouseover and ng-mouseenter directive do not work at all. As a matter of fact, any directive i place on the md-tab doesn't work. I am using a drag and drop plugin and from above the dnd-dragover and dnd-list directives do not work.

Everything was working fine when i was using version 0.8.3 but since I updated to 0.10, my code no longer works. Please i need solution to my problem very quickly and I have a deadline to complete my project else my client would be very unhappy. Thanks for your anticipated assistance

**Comment by markfarrall** [comment]
Also looking for the md-tab directive to support ng-dblclick to support users renaming the tab. Not urgent for me as I'm giving them a button at the bottom of the tab to rename.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (616/500 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:54168 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdJ-000Lkb-OI
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:57 -0500
Date: Thu, 28 Apr 2016 13:32:37 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875557;
	bh=4Dq+ifAW33hsm2pA9ZzmBOpcNz7ymlnbKesyGis51cc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=T9WfG9lbg0Ttg5JYBaGRtheqtZ59FVQLsu10ZbhUSU44jk5z/zb6nnrEowsitTGg8
	 gYD2w3Xm2rrLLFGe023hunnxS7djk8ifG/C50AzMd71eKqLOBzXmX21ZJPNDsXD7CD
	 nvX0+EPYERF5pnDBneDxPMMDPzcgacyu4klLZZKQ=
