### ISSUE TITLE
<md-menu> only close with md-button with ng-click, need to be same with ng-href

### ISSUE THREAD

**Issue by alanpurple** [angular/material#3397]
md-menu-item
                        md-button ng-href="/user-info">Edit User Info</md-button
 /md-menu-item>

====================

currently this needs to be 

====================

 md-menu-item>
                        md-button ng-click="" ng-href="/user-info">Edit User Info</md-button
 /md-menu-item>

=====================

make ng-href works same as ng-click, doesn't this look natural?

**Comment by epelc** [comment]
If this is a problem I'd suspect `ui-sref` has the same issue.

**Comment by hthetiot** [comment]
The current <md-menu> implementation can also lead to following JS error.
> Uncaught TypeError: target.hasAttribute is not a function
Caused by the function that is trigger when you close the menu.

```javascript
 do {
- 	if (target && target.hasAttribute('ng-click')) {
+ 	if (target && target.nodeType == 1 && target.hasAttribute('ng-click')) {
 	  if (!target.hasAttribute('disabled')) {
 	    close();
 	  }
 	  break;
 	}
- } while ((target = target.parentNode) && target != opts.menuContentEl)
+ } while ((target = target.parentNode) && target != opts.menuContentEl[0])
```

**Comment by arusakov** [comment]
@hthetiot
Faced with the same problem! Create PR. Why "target.nodeType == 1" there?

**Comment by thomasbertet** [comment]
:+1:  Faced this issue. I'm using ui-sref / ng-href.

Maybe a copepen could help  : http://codepen.io/anon/pen/yNPOBV

-> Click on the first "Redial" menu item, and see the error thrown.

**Comment by xtiggerk** [comment]
There is also a problem using 'data-ng-click' instead of 'ng-click'. Actually it doesn't work with 'data' prefix (FF and Chrome), works fine with ng-click.

**Comment by lrondanini** [comment]
+1

**Comment by bvolders** [comment]
same problem here, can this be fixed ?

**Comment by dani3l** [comment]
+1 with ui-router

**Comment by diegolaciar** [comment]
+1 with ui-router   ui-sref

**Comment by spock123** [comment]
Hey guys, you need to put the "ng-click" on the <md-menu-item> , not on the icon itself. The code inside Angular-material looks for a ng-click attribute of the <menu-menu-item>

So in short: just move your link from the <md-button> to the <md-menu-item> and you're good to go. 

I just had the same problem, found this page using a Google search. Hope this helps
