### ISSUE TITLE
Md-chips: support copy-pasting of content

### ISSUE THREAD

**Issue by amergin** [angular/material#3399]
Say that selecting strings 'variable1', 'variable2' and 'variable3' in a md-chips dropdown could be used to identify and select three chips. Is it possible to have the `md-chips` directive function in a way that would automatically select those variables with the copy-pasted string of 'variable1, variable2, variable3' into the search field?

**Comment by typotter** [comment]
Hi @amergin,
We will have to review and discuss this feature request to see how it might fit the spec and determine the complexity involved in implementation.
We would happily review a PR for it :)

**Comment by amergin** [comment]
[ngTagsInput](https://github.com/mbenford/ngTagsInput) implements this by allowing to set a split pattern (that defaults to `,`) and `addOnComma` when set to true creates a new tag. In addition, [`onTagAdding`](http://mbenford.github.io/ngTagsInput/documentation/api) is an expression that is evaluated whenever a tag is being added to determine if it is legal or not and will it therefore be added to results. 

I think the above method could be implemented in angular-material as well. Just provide a validation function for adding tags and a pattern that controls the splitting.

**Comment by typotter** [comment]
related to #3365?

**Comment by amergin** [comment]
Partially yes.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (515/500 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:61924)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avsc7-000L2g-ST
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:44 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=vFZtK8Oz2k4rwsn0b1k0/NAqptY=; b=FGjuVzn8HTi7fN7A
	vSXHzG9s2leyI6G8rlBYqRALdjhdq/w8NicYynlWEWBdq7Hhp1S7CnkXudT1vwUT
	2LL8gzVwSN75PmofZL4dPrmhbHUQXfHI+As6U3uKXUY5hunnTBAQmvKciaNypOO3
	zvtQPfVkTu4zfNnuY30jhyEZ/CI=
Received: by filter0805p1mdw1.sendgrid.net with SMTP id filter0805p1mdw1.2001.5722734A40
        2016-04-28 20:32:10.367989438 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id 3JnvW8keT1CgomEfzFV_5w
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:10.354 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:10 -0700

**Comment by vishwajeetv** [comment]
I've solved this problem with this technique -- 
http://stackoverflow.com/questions/42835551/angular-material-how-to-add-multiple-chips-when-comma-separated-string-is-adde

Apparently the solution is very simple - something like following ---

In the controller, write a method to be used on md-transform-chip, and manipulate the array containing chips in the scope, using the method.

Then, return null so that no new chip will be created.

```
 $scope.addMultipleChips = function (chip, model) {
        var seperatedString = angular.copy(chip);
        seperatedString = seperatedString.toString();
        var chipsArray = seperatedString.split();
        angular.forEach(chipsArray, function (chipToAdd) {
            $scope[model].push(chipToAdd);
        });
        return null;
    };
```
And declare it in the template like this -

```
<md-chips ng-model="someModel" md-separator-keys="seperatorKeys"
md-transform-chip="addMultipleChips($chip, 'someModel')">
                                <md-chip-template >
                                    <span>{{$chip}}</span>
                                </md-chip-template>
                            </md-chips>
```

Here's the JSFiddle for the same. http://jsfiddle.net/vishwajeetv/2f6qscrp/255/

**Comment by Splaktar** [comment]
@vishwajeetv as I mentioned in SO: You may need to check that the model isn't `undefined` before calling `model.push()`. If it's undefined, you'll need to set it to an empty array first. If all the chips are deleted and the md-chips has `required`, the model value will be `undefined` and your code would throw an exception.
