### ISSUE TITLE
md-autocomplete does not work with ng-messages validation

### ISSUE THREAD

**Issue by MetalHexx** [angular/material#3401]
As per issue #1780, ng-messages still fails to fire on md-autocomplete directives.

I've tried using the "name", "input-name", and "md-input-name" attribute on the md-autocomplete element and of course added a required attribute.

After trying to submit the form to save, the md-autocomplete form element does not show up as member on the $scope.form object.  Oddly enough, the $scope.form.$valid == false if you check it.  It just doesn't render the ng-message.  

The code pen linked off the autocomplete demo site also does not work.  I had to save it to share it:
http://codepen.io/MetalHexx/pen/qdVBLa

**Comment by MetalHexx** [comment]
For those who still want to use the autocomplete control bundled with angular-material, You can add an input element below the autocomplete and add an ng-hide="true" to hide the control.  The ng-message will still render and appear to refer to the md-autocomplete control.

**Comment by caok2709** [comment]
+1

**Comment by vicky-gonsalves** [comment]
+1

**Comment by robertmesserle** [comment]
Sorry guys, this was broken right before I was out for a little over a week and went entirely too long without being addressed.  Fixing this now.

**Comment by MetalHexx** [comment]
Thanks for the quick turnaround, robert!  When will this fix be live?

**Comment by vicky-gonsalves** [comment]
@robertmesserle Thanks for the quick fix. Hoping to get it live soon.

**Comment by prxg22** [comment]
Hey @robertmesserle, any idea when this feature will be live?? thanks (:

**Comment by iamryandrake** [comment]
Hey @robertmesserle , when will this be live?

**Comment by czery** [comment]
Hey there, also would love to see this live. Any assumption? @robertmesserle

**Comment by SelmanAY** [comment]
+1

**Comment by eniniz** [comment]
+1

**Comment by alois-wever** [comment]
+1

**Comment by jojogeyer** [comment]
+1

**Comment by bakhlov** [comment]
+1

**Comment by shrutiaggarwal3012** [comment]
+1

**Comment by piyushchauhan2011** [comment]
Using `ng-form` instead of `form`, `ng-messages` with autocomplete doesn't work

**Comment by alois-wever** [comment]
Hi @piyushchauhan2011 ,  

The `ng-form` directive is not a replacement for the `form` tag. In the docs they say:
> The purpose of ngForm is to group controls, but not to be a replacement for the <form> tag with all of its capabilities (e.g. posting to the server, ...).

So use your `ng-form` nested into a form tag, and everything should works as expected.

**Comment by iamryandrake** [comment]
This is still an issue where validations do not fire.

**Comment by sebasecheverry** [comment]
The issue still presents in the actual version, I'm using  version v1.0.6, but it does'nt work correctly for md-select as it doesn't shows the redline. But actual version does show it for md-select.

however is not working correctly for autocomplete

**Comment by stephengardner** [comment]
+1

**Comment by tom94zoe** [comment]
+1

**Comment by che85** [comment]
+1

**Comment by vinhnghi223** [comment]
+1

**Comment by alegadpen** [comment]
+1

**Comment by Jpatrick2zo** [comment]
+1

**Comment by ThomasBurleson** [comment]
Based on community votes: re-opening.

**Comment by topherfangio** [comment]
Closing as duplicate of https://github.com/angular/material/issues/9468. Discussing with @crisbeto on who will own.

**Comment by mohitangiras** [comment]
<div layout="row" layout-align="space-between"
                     	class="myContainer" ng-init="$watch('innerIndex=$index')">

then use innerIndex inside the container. This works for me
