### ISSUE TITLE
md-dialog: There is no easy way to get notified when dialog is closing (animation started)

### ISSUE THREAD

**Issue by blixt** [angular/material#3403]
The promise only resolves once the transformation of the dialog is complete, but I want to run a callback the moment the dialog starts closing. In cases where user presses escape or taps outside the dialog, there is no easy way to find out.

**Comment by dmackerman** [comment]
You could use a custom template, and custom controller and do the events there? Probably the only way with the promise based API.

**Comment by blixt** [comment]
Would a pull request to add an `onClosing` option be accepted? It'd be called from within [the `onRemove` function](https://github.com/angular/material/blob/fb7b9b3977f61528f7dc42756b2f2b87257e5ce0/src/components/dialog/dialog.js#L545-L557).
