### ISSUE TITLE
mdToast simple() has misaligned action button

### ISSUE THREAD

**Issue by asans** [angular/material#3408]
In the demo, if you click on the button Show With Action, the toast's OK button is misaligned. 

Interestingly, the custom toast shows the OK action button properly, although it's also taking up just a bit too much space as well and needs to be reset properly.

See Toast on the Angular Demo site.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (422/400 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:39489 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZm-001Z83-Fp
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:19 +0200
Date: Thu, 28 Apr 2016 13:27:44 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875265;
	bh=715AzqUN4D1Uyqv71RvK3Xlv2RAmPVNxDUZortszgSU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=NgHsvOlA3wBYo4wYLDnToeQIi0hpTSDn01FUTXlvE/MB/TvDFsGm40K/YQcP1qoNE
	 M5r6huQn4QwoY/BExM4um4hpP6Y1LFhFQ3MBanN2AzltcagZG3J1z7QiXkvVVTslew
	 c0/siGGVzOOsF5wLy39vF9/gl0lXwcAn+kxshoIg=
