### ISSUE TITLE
md-menu: Body scrollbar flickers on menu open / close

### ISSUE THREAD

**Issue by sanketsaurav** [angular/material#3410]
## Demo

![Imgur](http://i.imgur.com/h8jq1Fy.gif)

You can see the scroll-bar flickering on the right. It happens with menu of all widths.

EDIT:

Looks like whenever md-menu is opened, it sets `overflow-y: scroll` on `body`.

**Comment by heoseok** [comment]
+1

**Comment by kamarouski** [comment]
+1

**Comment by kevindstanley1988** [comment]
+1

**Comment by TBxy** [comment]
+1
I tried to include it in a navbar and saw this behavior:
http://codepen.io/anon/pen/PqOXLL

**Comment by janesconference** [comment]
+1

**Comment by rschmukler** [comment]
@sanketsaurav can you try with the latest master and see if the issue still persists?

**Comment by andreialecu** [comment]
Seems to work fine in latest master.

**Comment by ThomasBurleson** [comment]
Here is a CodePen with the latest from master. Notice that the menu is now right-aligned when opening (i.e. it opens from the top right).

http://codepen.io/team/AngularMaterial/pen/xGWgzQ
