### ISSUE TITLE
Closing md-menu with a click or tap outside (+Bug)

### ISSUE THREAD

**Issue by jproby** [angular/material#3411]
I don't know if it's the desired behavior but my md-menu only close when selecting an item or pressing Esc key. It would be great to be able to close it when clicking outside.
I think there is a bug (FF, Chrome) because if you click outside the menu then you're stuck and it won't listen to Esc events anymore.
You can reproduce with the online demo.

**Comment by mukilane** [comment]
+1 in FireFox

**Comment by imjoeybrennan** [comment]
I don't see this in Chrome 43.0.2357.130. What is your Chrome version?

**Comment by jelbourn** [comment]
@rschmukler I see this problem in IE (10 & 11) as well.

**Comment by sitic** [comment]
This seems to be a duplicate of #3283, is already fixed in master. Possible hotfix is
```
.md-scroll-mask {
  z-index: 0 !important;
}
```

**Comment by jproby** [comment]
From what I can see in FF, the md-dialog-container is not removed when I call $mdDialog.hide().
It's still true with latest master.

**Comment by jproby** [comment]
This pb is indeed resolved in master.
