### ISSUE TITLE
add endless scroll to Virtual Repeat

### ISSUE THREAD

**Issue by david-gang** [angular/material#3416]
Hi all,

We have now the excellent Virtual Repeat. It would be really great to combine it with an endless scroll, meaning that when we get to the end of the collection, we will get more data from the server with an ajax call.

Thanks,
David

**Comment by kseamon** [comment]
I had some thoughts about this WRT DataGrid, which would apply here.

Really there's two approaches to this, and we may want to do both:

1) As requested by @david-gang, size the repeater based on its initial data and load more when we get near the bottom.

2) Like we do in the Croc Omnigrid, use a model that is aware of the total count, size the scroller based on that count, and load in pages as we scroll near to their location in the repeat container.

#2 is better UX in most cases I think, but is not viable when the total count can't be known.

In both cases, we'll want to define an interface for a model object that the repeater can repeat over in place of an array. Implementations of this model will know how to fetch additional data.

**Comment by gpopovic** [comment]
+1

**Comment by ThomasBurleson** [comment]
@kseamon - (2) seems like a great first solution for most situations; in some cases, however, the total datasize is not known, so something like (1) may be the fallback/alternative.

**Comment by dopgm** [comment]
+1

**Comment by michaelkrog** [comment]
+1

**Comment by kseamon** [comment]
https://github.com/angular/material/pull/4002
