### ISSUE TITLE
transitionEndPromise is not always resolved for $mdDialog

### ISSUE THREAD

**Issue by antoster** [angular/material#3417]
Which results in `dialogPopIn` and `showDone` not resolving, so $mdDialog instance can't be closed.

My case (MacOS X Yosemite, Chrome 43.0.2357.124): 
`transitionEndPromise` was not resolving due to `finished` function was never called. 
`finished` was not called because `transitionend` event did not fire in case `window` was out of focus prior to clicking a button that was calling $mdDialog's `show` (This can be achieved by: open browser's console, focus it, refresh the page, click the button which calls `$mdDialog.show` in its `ng-click` handler).  

https://github.com/angular/material/blob/master/src/core/util/util.js#L175-L189
```
transitionEndPromise: function (element, opts) {
        opts = opts || {};
        var deferred = $q.defer();
        element.on($mdConstant.CSS.TRANSITIONEND, finished);
        function finished(ev) {
          // Make sure this transitionend didn't bubble up from a child
          if (!ev || ev.target === element[0]) {
            element.off($mdConstant.CSS.TRANSITIONEND, finished);
            deferred.resolve();
          }
        }

        if (opts.timeout) $timeout(finished, opts.timeout);
        return deferred.promise;
      },

```

Possible quickfix is to pass a default opts.timeout from `dialogPopIn` (and `dialogPopOut` possibly), so that `finished` gets called for granted:
https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L656
```
 return $mdUtil.transitionEndPromise(dialogEl, {timeout: 500});
```

Thank you.

**Comment by ThomasBurleson** [comment]
Fixed in SHA d31ffd9185d687eee80c6297ef42c064eb7a8d66
