### ISSUE TITLE
md-radio-button : is ngChange attribute working ?

### ISSUE THREAD

**Issue by NicolasVargas** [angular/material#3419]
Hi,

[Here on codepen](http://codepen.io/anon/pen/BNmLqe), you can see a radio button group where the radio buttons have an ngChange attribute that fires an alert. Nothing appends when whe switch radio buttons. Did I do something wrong ?

**Comment by mckenzielong** [comment]
Here is a working fork of your pen: http://codepen.io/mckenzielong/pen/BNmpbx.  

First, the usage was incorrect (ngChange -> ng-change.)  Also, ng-change relies on ng-model. In this case we will stick the change event on the <md-radio-group>

This might have been a better question for the [official forums](https://groups.google.com/forum/#!forum/ngmaterial) :+1:

**Comment by Izcalli** [comment]
@mckenzielong : Thank you for the quick answer.
I used ngChange as an md-radio-button attribute because the Angular Material site was documenting it : https://material.angularjs.org/HEAD/#/api/material.components.radioButton/directive/mdRadioButton

Maybe it should be fixed.

**Comment by EladBezalel** [comment]
`ngChange` is documented in [`md-radio-button`](https://material.angularjs.org/HEAD/api/directive/mdRadioButton)
