### ISSUE TITLE
Palette contrast ratios don't match Material spec

### ISSUE THREAD

**Issue by calebegg** [angular/material#3426]
https://github.com/angular/material/blob/master/src/core/services/theming/theme.palette.js

For instance, 'light-blue' has 500 under `contrastLightColor`, but it should have black text according to the spec:

http://www.google.com/design/spec/style/color.html#color-color-palette

**Comment by jelbourn** [comment]
Looks like the spec has been updated since those swatches were pulled. I have a separate list of the color / contrast color that I pulled a while ago with a script and it has `white` for light-blue-500.

**Comment by jelbourn** [comment]
I think this should be fixed now. Chime in if you notice any new mismatches.
