### ISSUE TITLE
md-border-bottom attribute on md-tabs does not support data- prefix.

### ISSUE THREAD

**Issue by HashKP** [angular/material#3428]
```<md-tabs md-border-bottom></md-tabs>``` works while
```<md-tabs data-md-border-bottom></md-tabs>``` does not. 

Since most other attributes on md-tabs work with data- prefix this should be consistent and fixed.

**Comment by mkalpana** [comment]
I am facing the same issue. It would be nice to have support for data- prefix for md-border-bottom.
