### ISSUE TITLE
inconsistent look and feel of <select> and <md-input-container md-no-float>

### ISSUE THREAD

**Issue by sajmons** [angular/material#3431]
There is inconsistent look and feel when using <md-input-container md-no-float> and select in row layout. Placeholder labels are too high.

See this CodePen here: http://codepen.io/anon/pen/oXoeaq

Fix: margin-top: 22px;

**Comment by xforceco** [comment]
My fix: 
    <md-select placeholder="State" ng-model="ctrl.userState" style="padding-top:0">

**Comment by sajmons** [comment]
xforceco: much better suggestion than mine! Thnx!

**Comment by rschmukler** [comment]
This is fixed in master.
