### ISSUE TITLE
mdAutocomplete, mdSelect, mdMenu: cause extra scrollbar on body element

### ISSUE THREAD

**Issue by michaelbromley** [angular/material#3432]
When the md-autocomplete suggestions list and the md-select options are displayed, an extra scrollbar appear on the `<body>` element. Example:

![second-scroll-bar](https://cloud.githubusercontent.com/assets/6275952/8325588/1bf5e0a2-1a5b-11e5-8a21-bde4e3c25d6f.jpg)

I believe this is being caused by each of these components making a call to `$mdUtil.disableScrollAround()`, which in turn is [setting `overflow-y: scroll` on the `<body>` element](https://github.com/angular/material/blob/b4eac137de9ccca5ad60cf028882fb0c0d87523a/src/core/util/util.js#L117).

Not got time to test & do a PR right now, but perhaps this could be fixed by using `overflow-y: auto` instead?

**Comment by evoker** [comment]
The same issue occurs with md-select it seems.

How would you go about implementing this workaround you mentioned?

**Comment by michaelbromley** [comment]
@evoker I created a pull request, it is super simple - you can see what it involves here: https://github.com/angular/material/pull/3457

**Comment by marino-oneshoe** [comment]
same happens with md-menu

**Comment by marino-oneshoe** [comment]
There is a update in HEAD and seems to work now:
checked:
mdAutocomplete
mdMenu
mdSelect

https://material.angularjs.org/HEAD/#/demo/material.components.menu

**Comment by evoker** [comment]
Unfortunately, in IE11, the issue with the double scrollbars for md-select hasn't been resolved.

**Comment by naomiblack** [comment]
This is fixed in HEAD.

**Comment by dhavaldvl00** [comment]
add below css:
html {
    overflow: initial !important;
}
