### ISSUE TITLE
Invisible placeholder input[text] when using <md-input-container md-no-float>

### ISSUE THREAD

**Issue by sajmons** [angular/material#3433]
Placeholder is invisible in FireFox 38.0.5.

`<md-input-container md-no-float>
        <input type="text" placeholder="Street name">
</md-input-container>`

CodePen example:
http://codepen.io/anon/pen/vOWevY

CSS that causes it:

md-input-container:not(.md-input-has-value) input:not(:focus) {
    color: transparent;
}

**Comment by Splaktar** [comment]
Dup of #2162
