### ISSUE TITLE
md-chips: autocomplete with md-min-length="0" shows search text after selection

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/material#3435]
To reproduce simply click in the autocomplete field and select a item without typing anything.
http://codepen.io/anon/pen/WvXXNZ

The result looks like this:
![](http://i.imgur.com/I30KaYp.png)

This does only happen when selecting anything without filtering it first.

**Comment by nestorneto** [comment]
its a know bug. #2623

**Comment by stefan-schweiger** [comment]
oh thanks I search for issues but must have overlooked it!

**Comment by rgolea** [comment]
+1
