### ISSUE TITLE
IE11 md-select shows both md-content and body scrollbars

### ISSUE THREAD

**Issue by evoker** [angular/material#3442]
Check the demo page in IE11 to see the issue: https://material.angularjs.org/latest/#/demo/material.components.select

When opening a select box, an additional scrollbar (from the body or html tags presumably) appears.

I have not been able to find a workaround for this sadly.

Any thoughts?

**Comment by Londovir** [comment]
Possibly a duplicate of #3432? Seems like the suggested fix in that one might address this also.

**Comment by evoker** [comment]
They do look a bit similar but not sure what's been suggested would work as a fix. I can't really hack material to add this and not sure how I would go about adding this as CSS.

**Comment by rschmukler** [comment]
closing as duplicate of #3432
