### ISSUE TITLE
Add left and right orientation options for tabs

### ISSUE THREAD

**Issue by JunedS** [angular/material#3445]
Hi,

I think we should have vertical tabs too in addition with current tabs with md-align-tabs="left" and md-align-tabs="right".

Thanks,
Juned S

**Comment by LiorArbel** [comment]
Hey, will it be fixed anytime soon? This is pretty important for me, I need the tabs to be from right to left. 

Maybe someone has a css patch or something for the meantime?

**Comment by shinoymm** [comment]
Isn't vertically stacked tabs pretty required one ?.
Is this going to be implemented any time soon ?

**Comment by jsmylnycky** [comment]
+1 for md-align-tabs="left" and md-align-tabs="right".

**Comment by JunedS** [comment]
Why is it under deprecated?

**Comment by caneraydinbey** [comment]
What is alternative?

**Comment by arnellebalane** [comment]
In case anyone these days still faces this issue, here's a solution that works for me. This achieves the same alignment as @LiorArbel 's above, while not breaking pagination.

```css
.my-container md-tabs-wrapper,
.my-container .md-tab {
    transform: rotateY(180deg);
}
```
