### ISSUE TITLE
md-select with scroll bar issue on Firefox

### ISSUE THREAD

**Issue by butaixianran** [angular/material#3448]
This is a new issue with latest angular material. 0.9.0 doesn't have this issue.

Scroll down a page, then click a md-select, a blank white area will raise up from bottom and block everything on the page.

Check this:
http://codepen.io/butaixianran/pen/PqJdMY

This is an issue with Firefox. Chrome is fine.

**Comment by cebor** [comment]
I have the same issue with chrome.

**Comment by Jarema** [comment]
Same issue here, in Chrome.

Chrome version: 43.0.2357.130 (64-bit)
angular material version: 0.9.4

**Comment by butaixianran** [comment]
This issue is in firefox with latest angular material version.

**Comment by ayastreb** [comment]
+1
this is reproduced in latets chrome every time there is a scroll on the page - select's backdrop element covers the page.

**Comment by rschmukler** [comment]
This is fixed on master. Thanks for reporting!
