### ISSUE TITLE
md-select typing option is not working in a modal

### ISSUE THREAD

**Issue by jeromemmiranda** [angular/material#3449]
https://github.com/angular/material/issues/1884

md-select typing option is working all over my page. However, when I tried to put it in a modal. It's not anymore working.

Need your help on this one.

**Comment by Gullfaxi171** [comment]
Same issue here, the md-select options appear behind the dialog & behind the backdrop

**Comment by jeromemmiranda** [comment]
@Gullfaxi171 I have already applied that, but have you tried to type while the list is open. I mean it's like in the default select tag. When you type, words with that characters in the beginning will be selected.

**Comment by rschmukler** [comment]
This is working on master.
