### ISSUE TITLE
Opions of md-select will be block when there are a lot md-tab on page.

### ISSUE THREAD

**Issue by butaixianran** [angular/material#3450]
#### When there are many tabs in one or more md-tabs, you have to wait a very very long time before you can  click any opion of a md-select.

check this out:
http://codepen.io/butaixianran/pen/yNPRag

#### Check the same page with 0.9.4, which works fine:
http://codepen.io/butaixianran/pen/EjbdwL

#### This issue shows up since 0.9.5, then keeps that way to 0.9.8, and became even slow, even worse since 0.10.0.

Please fix this one or give us any work around.

As you can see, I have more than 5 md-tabs on my page, and each one with more than 40 tabs in it.

Which means I have total 200 tabs on my page...so I really need this one to be fixed.

Thanks!

**Comment by rschmukler** [comment]
@butaixianran I just tried your demo and performance seemed to be fine - something might have gotten pushed into master that resolves this. Could you check it again and confirm that it is working as expected? If it is not, could you give us browser / OS information to dig further?

**Comment by rschmukler** [comment]
@butaixianran actually never mind, I recreated your issue. Investigating

**Comment by rschmukler** [comment]
Just as a note that it seems to only be the first click that takes a while, and then performance is back to normal
