### ISSUE TITLE
md-autocomplete not showing when searchText empty in 0.9.8

### ISSUE THREAD

**Issue by asaharan** [angular/material#3454]
md-autocomplete not showing when search text empty in 0.9.8

This is screenshot from 0.9.8
![screenshot from 2015-06-25 17 19 47](https://cloud.githubusercontent.com/assets/11248242/8353755/e7802558-1b5e-11e5-82bb-3e11d89914c2.png)

and this from 0.9.7
![screenshot from 2015-06-25 17 19 59](https://cloud.githubusercontent.com/assets/11248242/8356052/76ad6964-1b70-11e5-8ce0-7e7c3869f41d.png)

**Comment by stefan-schweiger** [comment]
Both of those screenshots are from 0.9.8 as you can see from the URL, maybe you want to edit this again?

**Comment by asaharan** [comment]
thanks @stefan-schweiger 
now it is correct

**Comment by stefan-schweiger** [comment]
but as far as I can tell this bug has already been fixed in 0.10.0

**Comment by robertmesserle** [comment]
This is fixed in more recent versions.
