### ISSUE TITLE
Select option group not showing the whole text 

### ISSUE THREAD

**Issue by natcohen** [angular/material#3459]
When showing in grouping mode, it is impossible to make the selection box wider. In the demo, you can see that Ground Beef is only half displayed...

![image](https://cloud.githubusercontent.com/assets/7813574/8360748/b870d66c-1b3c-11e5-8d56-e923ffe749a6.png)

**Comment by rschmukler** [comment]
The select menu pop up is dependent of the origin select. Ultimately we might add a `[width]` attribute ala `md-menu`

**Comment by greenify** [comment]
I encountered a similar problem when having a long text as option and used this simple hack to allow the options box to adapt its width.

```
md-option .md-text {
    padding-right: 10px;
    overflow: inherit;
}
```

Would be great to see a more sophisticated solution for this problem :)
