### ISSUE TITLE
ng-disabled doesn't disable md-chips

### ISSUE THREAD

**Issue by tamsler** [angular/material#3464]
```javascript
<md-chips
    ng-model="formData.labels"
    placeholder="+Label"
    readonly="false"
    delete-button-label="Remove label"
    ng-disabled="!formData.source"
    secondary-placeholder="Press Enter to create a label">
</md-chips>
```

**Comment by mohitadwani** [comment]
+1

**Comment by davidmillercode** [comment]
+1

**Comment by sharananiapurapu** [comment]
Hi,
Is there any solution for the issue, I am also waiting for the solution.

**Comment by RolandHeath** [comment]
@sharananiapurapu 
One workaround would be to use chips with a custom input - for example, if you're using it with an md-autocomplete, you can disable the md-autocomplete. This should work for other custom inputs as well, but I have only used it with autocomplete elements. The docs should have an example with custom inputs.

**Comment by sharananiapurapu** [comment]
@RolandHeath 
Thank you for quick response. I tried this
<md-input-container class="md-block"> 
	<label>Role(s)</label>
	<md-select ng-model="data.selectedRoleId" ng-change="control.doSelectRole(data.selectedRoleId)" ng-disabled="data.isMyProfile">
		<md-option ng-repeat="role in data.roles" value="{{role.id}}">{{role.name}}</md-option>
	</md-select>
	<div ng-disabled="data.isMyProfile"> 
		<md-chips class="select-chips" ng-model="data.user.roles">  
		   	<md-chip-template ng-disabled="data.isMyProfile"> 
			       <span class="md-caption">{{$chip.name}}</span>
			</md-chip-template>
		</md-chips>  				
	</div>	   		
</md-input-container>	

It did not work out. Effective What I want is user should not be able to close the chip. The select box gets disabled but not the chip.

**Comment by RolandHeath** [comment]
@sharananiapurapu 
Well, I'm not part of the team, just like to help out. I can think of two main ideas for a workaround. 

The first would be using a custom chip template, like the 3rd "basic usage" example in the docs, but putting ng-disabled, ng-hide, or ng-if on the button element.

The second idea would be using the using md-on-remove, and re-adding the chip as soon as it's removed (might have some other issues though...)

Sneaky option 3 would be to create a pull request with your own solution to the problem, but that's obviously more complicated.

**Comment by sharananiapurapu** [comment]
@RolandHeath 
Like your approaches. Thank you so much for your suggestions.

**Comment by dwanderton** [comment]
+1 this was a bit surprising. Please fix :+1:

**Comment by Kasahs** [comment]
A temporary hack for this if you just want to disable the input element:
```.your-container .md-chips .md-chip-input-container > input {
        display: none;
    }```
```.your-container``` is for specificity and to make sure it doesn't happen to all chips.

**Comment by piyushchauhan2011** [comment]
@Kasahs yep works perfectly. Use `.your-container` to identify in which case you want to disable

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by kondalraodurgam** [comment]
ng-disabled in angularjs not working on angular material md-chips

**Comment by kondalraodurgam** [comment]
Its working or not???.

**Comment by RudolfFrederiksen** [comment]
https://material.angularjs.org/1.1.1/api/directive/mdChips
there is a `readonly` parameter on md-chips directive that does just the same thing.

**Comment by kondalraodurgam** [comment]
Thank you#rudoifFrederiksen

**Comment by Syedgit** [comment]
is there any feasable solution yet to make it wokr with angular ng-disabled , i tried readonly attribute but does not work me. 
```
<div layout="row" layout-margin>
          <md-input-container flex="100" class="notifyUser-chips">
            <label>Bcc</label>
            <br>
            <md-chips flex="100"
                      ng-model="notifyCtrl.bcc"
                      name="email"
                      readonly="true">
            </md-chips>
            <p style="color:red" ng-show="patternError">An email must contain a-z, A-Z, 0-9, or _ characters</p>
          </md-input-container>
        </div>
```
