### ISSUE TITLE
md-icon not working when adding md-warn or md-accent

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3465]
I've just moved to master from 0.10.0 and all of my md-icon elements with md-warn or md-accent classes now look like this...

![screen shot 2015-06-25 at 22 11 33](https://cloud.githubusercontent.com/assets/1916471/8365749/41425124-1b87-11e5-81d9-6368a8dbd014.png)

with the class removed...

![screen shot 2015-06-25 at 22 12 12](https://cloud.githubusercontent.com/assets/1916471/8365751/46e1b3a4-1b87-11e5-8d75-2d034ab037bc.png)

I am using `<md-icon class="md-warn">error</md-icon>` style

**Comment by rscottfree** [comment]
Possibly related to https://github.com/angular/material/issues/4031 (Includes codepen). This also happens when you have an mdIcon inside an mdListItem.

**Comment by programmist** [comment]
@hodeyp: This appears to have been fixed in 0.11.0.  I've created [a codepen](http://codepen.io/programmist/pen/avNzyX?editors=101) from issue #4031 to demonstrate.  

Please verify this works for you.

**Comment by hodeyp** [comment]
it looks to be resolved, thanks.
