### ISSUE TITLE
<md-card-content> and <md-card-footer> don't exist?!

### ISSUE THREAD

**Issue by lewis-walker** [angular/material#3466]
I almost doubt myself as I write this because it seems ridiculous.
I made an &lt;md-card&gt; with an &lt;md-footer&gt; and got frustrated that the footer didn't stick to the bottom.

But then I looked deeper and was puzzled when my Webstorm IDE refused to recognise the validity of the &lt;md-content&gt; and &lt;md-footer&gt; directives.

So I dug deeper still and searched angular-material.js and the directives simply aren't declared at all. There's mdCard, but that's it!

Here are my dependencies:

    "angular": "^1.4.1",
    "angular-animate": "^1.4.1",
    "angular-aria": "^1.4.1",
    "angular-material": "^0.10.0",
    "angular-material-icons": "^0.5.0"

As an act of desperation I searched the entire node_modules folder where everything is, and mdCardFooter doesn't appear anywhere.

**Comment by george3447** [comment]
+1

**Comment by ThomasBurleson** [comment]
These are not directives. These are CSS class types:  https://github.com/angular/material/blob/master/src/components/card/card.scss#L17-L32

**Comment by lewis-walker** [comment]
But.... https://material.angularjs.org/latest/#/api/material.components.card/directive/mdCard

Your own demo documentation clearly shows them as directives:

<md-card>
 <img src="card-image.png" class="md-card-image" alt="image caption">
 <md-card-content>
   <h2>Card headline</h2>
   <p>Card content</p>
 </md-card-content>
 <md-card-footer>
   Card footer
 </md-card-footer>
</md-card>
