### ISSUE TITLE
$mdSidenav no instance found for handle "id"

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#3470]
cannot open sidenav, it throws me error by using `toggle` or `open` method.
```Html
<body ng-app="hidrolab" ng-controller="MainController as main">
		<div layout="column" layout-fill>
			<md-toolbar>
				...
			</md-toolbar>
			<md-sidenav class="md-sidenav-left md-whiteframe-z2" md-component-id="left">
				<md-toolbar class="md-theme-indigo">
					<h1 class="md-toolbar-tools">Operaciones</h1>
				</md-toolbar>
				<md-content layout-padding>
					This is a sidenav
				</md-content>
			</md-sidenav>
			<md-content ng-view>

			</md-content>
		</div>
```

```Javascript
(function(angular)
{
	var app = angular.module('hidrolab');

	app.controller('MainController', function($mdSidenav)
	{
		$mdSidenav('left').open();
	});
})(angular)
```

error: `"No instance found for handle" "left"`

**Comment by tuhoojabotti** [comment]
The problem is that angular initializes the controller before the DOM is fully ready. A workaround is to use  $timeout, that way the function won't be called until the next event loop cycle and the by then the DOM will be processed.

```javascript
$timeout(function () { $mdSidenav('left').open(); }, false);
```

**Comment by Nosthertus** [comment]
@tuhoojabotti i would use `md-is-locked-open` but this sidenav would be displayed after some point, and not at the point where the document loads

**Comment by tuhoojabotti** [comment]
@Nosthertus Did the timeout trick work for you?

**Comment by Nosthertus** [comment]
@tuhoojabotti yes, it works, thanks. just one last question, is there a way to make the `sidenav` not to hide a part of the content is being displayed? i wouldn't like the toolbar to be behind of the `sidenav`, if not, then i could just put the `sidenav` somewhere it wouldn't affect the toolbar, i'm just curious

**Comment by tuhoojabotti** [comment]
@Nosthertus That is the function of `md-is-locked-open`, when it is true, the sidenav is locked open and does not overlap with the content. You can use databinding to control the attribute instead of using  ` $mdSidenav('left').open()`. Add a variable to your scope to control `md-is-locked-open` instead.

**Comment by Nosthertus** [comment]
oh thanks, i will try that
