### ISSUE TITLE
$mdUtil sevice api not found

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#3471]
I was looking at the demos and i have seen some controllers use `$mdUtil` and i wanted to know what it really does, but i don't find where is that api

**Comment by NetvisionBenjamin** [comment]
You can see $mdUtil source here : https://github.com/angular/material/blob/master/src/core/util/util.js

**Comment by ThomasBurleson** [comment]
$mdUtil is an internal service and will not be documented; at least until late v1.0 beta.
