### ISSUE TITLE
Layout css issues

### ISSUE THREAD

**Issue by norkunas** [angular/material#3473]
I have a problem when using: ```layout="column" layout-gt-md="row"```, i know that using layout="column" and for child element providing flex="number", max-height css applies, but why the ```layout-gt-md="row"``` is not respected?
```
@media (min-width: 1200px) {
  [layout=column]>[flex-gt-lg="50"] {
    max-height: 50%;
  }
}
```

http://codepen.io/anon/pen/MwrWxx

**Comment by norkunas** [comment]
ping

**Comment by EladBezalel** [comment]
It's supported, your problem was that your main element didn't filled the body,

take a look [here](http://codepen.io/EladBezalel/pen/eNyvYw)

**Comment by norkunas** [comment]
No, the problem is not that. ```[layout=column]>[flex-gt-lg="50"] { max-height: 50% }``` still left applied.

**Comment by epelc** [comment]
Here's some more info and a demo #2695
