### ISSUE TITLE
md-autocomplete causes browser stuck

### ISSUE THREAD

**Issue by meassinal** [angular/material#3474]
In my scenario I was trying to create a new item that is not in the collection returned from server by clicking <b>Create</b> or Enter. I use form submit to save the item. But while autocomplete is in progress and user try to hit <b>Enter</b> or <b>Create</b> quite fast. Then the browser becomes stuck. I have tried to abort the request before sending post request to server but still it caused browser stuck.

![screen shot 2015-06-26 at 3 41 14 pm](https://cloud.githubusercontent.com/assets/2950432/8373834/6bda9516-1c1a-11e5-8e6f-013c1514fd70.png)

**Comment by rschmukler** [comment]
@meassinal I notice that you have a dialog open while doing this. Can you try again on the latest master? I recently fixed similar issues in 1a15d997fd51157f170d7b5c16ec3d6536ec4f7f. Let me know

**Comment by meassinal** [comment]
Ok I will try again and let you know how I am going through it. Thanks.

**Comment by uriva** [comment]
I'm experiencing the same thing. For me the browser doesn't actually get stuck - only the mouse actions are ignored, but using the keyboard you can tab between controls and interact with them.

**Comment by robertmesserle** [comment]
I believe this is resolved - please reply with a CodePen if this issue still exists.
