### ISSUE TITLE
Chips have blank template when search text not found in items collection

### ISSUE THREAD

**Issue by meassinal** [angular/material#3475]
When I check Chips in the demode, Chips work quite well when search text not found in collection. And I don't have any idea why I am having this problem. I am using Angularjs 1.4.0 and other dependencies. 

![screen shot 2015-06-26 at 3 48 57 pm](https://cloud.githubusercontent.com/assets/2950432/8373929/5a49d9c8-1c1b-11e5-9f11-226fb4dff2e2.png)

**Comment by metamatt** [comment]
@typotter do you also want to resolve #3900 and #4087 as dupes of this?

**Comment by jherman** [comment]
Still seeing this issue:
https://codepen.io/anon/pen/KdQJpW?editors=101

Type in "ca", cabbage will pop up and be auto selected. Hit 'enter'. You'll see two chips get added - what you searched for and the cabbage chip. Expecting only the cabbage chip.

**Comment by robertmesserle** [comment]
Definitely seeing an issue in your codepen - reopening.

**Comment by jherman** [comment]
In the mean time I've added the following line to fix the issue:
```
 if (angular.element(document.querySelectorAll("md-virtual-repeat-container:not(.ng-hide) li[md-virtual-repeat].selected")).length) return;
```
To:
```
MdChipsCtrl.prototype.appendChip = function (newChip) {
  if (angular.element(document.querySelectorAll("md-virtual-repeat-container:not(.ng-hide) li[md-virtual-repeat].selected")).length) return;
  if (this.useOnAppend && this.onAppend) {
    newChip = this.onAppend({'$chip': newChip});
  }
  if (this.items.indexOf(newChip) + 1) return;
  this.items.push(newChip);
};
```
There is probably a better way to handle this, but this get's me moving.

**Comment by danielgranat** [comment]
@jherman I'm facing the same issue, and I'm probably missing something, but adding the above line prevents from any of the chips from being added.

What do you think about the following suggestion to your line?
```javascript
var selectedChip = angular.element(document.querySelectorAll("md-virtual-repeat-container:not(.ng-hide) li[md-virtual-repeat].selected"));
if (selectedChip.length && selectedChip.scope().item != newChip) return;
```

**Comment by jherman** [comment]
That's strange that it's not working for you.  I'm using v0.11.4 in case you are using something different.  Regardless, since this is just a bandage for the time being, I would just do that if that fixes it for you.  I imagine @robertmesserle is on the case now, and it'll be fixed relatively soon; which means I'll just be updating to the latest when it does get released.

**Comment by topherfangio** [comment]
@robertmesserle PR #5497 may fix this as well.

**Comment by robertmesserle** [comment]
@topherfangio Can you let me know when that's merged in?  I'll re-test once that's in.

**Comment by jelbourn** [comment]
@topherfangio can you check if this is still an issue?

**Comment by topherfangio** [comment]
@robertmesserle @jelbourn The Codepen above is no longer showing the issue (it uses HEAD), so I think this can be closed. Let me know if you think otherwise and we can reopen.
