### ISSUE TITLE
md-fab-toolbar <span flex> </span> is not working

### ISSUE THREAD

**Issue by johnlim5847** [angular/material#3477]
is there any method to get the element in md-fab-toolbar to space out like the one in md-toolbar ?

**Comment by topherfangio** [comment]
Hi there!

Could you please provide a http://codepen.io showing what you're trying to do? It would help me understand the issue better and give you feedback :-)

**Comment by topherfangio** [comment]
@johnlim5847 Any chance you could provide a Codepen to help me better understand this issue? Thanks!

**Comment by topherfangio** [comment]
Since we haven't received any updates on this, I'm going to go ahead and close this issue. Please re-open if you can provide a codepen/example or better describe what you're trying to do.
