### ISSUE TITLE
md-dialog has no scroll bar in IE11

### ISSUE THREAD

**Issue by evoker** [angular/material#3480]
As the title says, in IE, when the dialog's content has larger height than the dialog itself, no scrollbar appears. Clicking inside the window or pressing a button on the keyboard seems to wake the dialog up and it behaves properly till you click again.

This is also noticable in the demo page: https://material.angularjs.org/latest/#/demo/material.components.dialog for the custom dialog.

I have tried to set md-dialog-content's overflow-y to scroll but it has very weird behavior in IE.

Any ideas on a workaround at least until this is resolved?

Thanks in advance,

**Comment by evoker** [comment]
Bump!

**Comment by stefan-schweiger** [comment]
+1 This control is so buggy in IE11
