### ISSUE TITLE
`md-chips` not working inside `ng-repeat`

### ISSUE THREAD

**Issue by cnjsstong2** [angular/material#3482]
Example here:
http://codepen.io/anon/pen/PqEZpa

If a `md-chips` is inside of any `ng-repeat`, it will not work properly. Only the last repeated item has its `md-chips` shown normally.

This makes `md-chips` barely useful...

**Comment by ahmadhsalim** [comment]
I'm having the same trouble. The following code doesn't work.
```
<md-chips>
      <md-chip ng-repeat="i in [1, 2, 3]">Normal Static Chip</md-chip>
</md-chips>
```
But weird thing is that, I have the below code in a page and the ng-repeat is populated from an array in scope. No chips are shown. Then I navigate to another page and press the browsers back button. Suddenly all the chips are displayed properly.

**Comment by dmackerman** [comment]
You can bind `md-chips` to an `ng-model` array and it will populate, but yeah - it's totally broken with `ngRepeat.  :(

**Comment by cnjsstong2** [comment]
@dmackerman Thanks.

Actually, @ahmadhsalim 's issue can have a workaround with `ng-model`. 

However, my example is also quite common but can not be achieved now.

**Comment by ahmadhsalim** [comment]
How can I use a workaround? What I want is static chips that cannot be edited. With ng-model bound to an array, it's not giving me static chips.

**Comment by cnjsstong2** [comment]
@ahmadhsalim Just make the chips `readonly` in addition. Please go to #2829 which is the correct issue for you.
