### ISSUE TITLE
Customize textarea's minHeight so it can be aligned with normal input

### ISSUE THREAD

**Issue by natcohen** [angular/material#3485]
It is currently impossible to align a textarea with an input because the textarea has a minimum height of at least two rows while the input has one row. We should be able to specify the minHeight... It will look like an input so in order to avoid confusion, a 'differentiator' should be used (like the current bottom right corner in chrome)

**Comment by dmackerman** [comment]
Yeah, I've just manually overrode mine with CSS for now.

**Comment by topherfangio** [comment]
Regarding the `min-height`, is this still an issue? Our own demos show our text-areas the same as the text fields.

Regarding the differentiator, this is not currently in the specification (http://www.google.com/design/spec/components/text-fields.html#text-fields-multi-line-text-field) which we utilize in designing our components.

**Comment by natcohen** [comment]
Minheight is not an issue anymore but the differentiator should be a must have...when you have forms, the behavior of a textarea is different when you press enter! This is very confusing.

**Comment by natcohen** [comment]
@topherfangio Also the link you provided refers to a virtual keyboard where the enter key can change appearance. On a physical keyboard there is no way to distinguish a textarea from a textfield.
