### ISSUE TITLE
Best practice for button inside input

### ISSUE THREAD

**Issue by natcohen** [angular/material#3486]
Bootstrap has a nice way to integrate a graphicon/text and button to the right/left of a button (aka input-group). Any best practice for Angular Material?

**Comment by EladBezalel** [comment]
These kind of questions should be asked in the [forum](https://groups.google.com/forum/#!forum/ngmaterial),
meanwhile you should look [here](https://material.angularjs.org/HEAD/#/demo/material.components.input) in the last section,

**Comment by natcohen** [comment]
It works for the left side but not for the right side...

**Comment by EladBezalel** [comment]
An rtl support is assigned to 0.11.0 #1080
