### ISSUE TITLE
md-autocomplete adds $$hashKey to objects because track by is not used in md-items

### ISSUE THREAD

**Issue by amergin** [angular/material#3487]
When iterating over an array of objects, the autocomplete adds `$$hashKey` to objects. Normally, I'd just add `track by` expression to the `ng-repeat` statement, but here I cannot do that without modifying the source. This is slightly annoying when trying to match objects later on and find out that there's no match because of that key-value pair.

**Comment by robertmesserle** [comment]
This should be resolved by https://github.com/angular/material/commit/7430e68722f0a788b0710bb8ea9f3cf3b68b2a9b#diff-dfc7d490c731a45e66ad22d8efb7456dL161
