### ISSUE TITLE
Animations not working in Angular#1.4.1

### ISSUE THREAD

**Issue by Wheately** [angular/material#3494]
Animations seem to not be working properly when using Angular 1.4.1

Here is an example using Angular 1.3.15 - Animations Work
http://codepen.io/wheately/pen/bdaReq

Here is the same example, but using Angular 1.4.1 - Animations Not Working
http://codepen.io/wheately/pen/JdMJRV

In Angular 1.4.1, the Opacity transition seems to work, but the scaling out from the left does not.

**Comment by lucasmartinez** [comment]
in version 1.3.16 it doesn't work

**Comment by Wheately** [comment]
@lucasmartinez Yep, they seem to not work in any version above Angular 1.3.15

**Comment by ThomasBurleson** [comment]
@Wheately, @lucasmartinez - this support for Angular 1.4.1 was fixed after the 0.10.0 release; commited to master in 62f5c7b80001a56e63fe3df226ef7f466e6f06eb
