### ISSUE TITLE
required validations  not working for md-autocomplete 

### ISSUE THREAD

**Issue by prashant1587** [angular/material#3496]
required validations  not working for md-autocomplete  for the version 0.10.0.
Though its working fine for 0.9.7

**Comment by prashant1587** [comment]
<input type="search"\
                  id="fl-input-{{$mdAutocompleteCtrl.id}}"\
                  name="{{inputName}}"\
                  autocomplete="off"\
                  ng-required="isRequired"\
                  ng-minlength="inputMinlength"\
                  ng-maxlength="inputMaxlength"\
                  ng-disabled="$mdAutocompleteCtrl.isDisabled"\
                  ng-model="$mdAutocompleteCtrl.scope.searchText"\
                  ng-keydown="$mdAutocompleteCtrl.keydown($event)"\
                  ng-blur="$mdAutocompleteCtrl.blur()"\
                  ng-focus="$mdAutocompleteCtrl.focus()"\
                  aria-owns="ul-{{$mdAutocompleteCtrl.id}}"\
                  aria-label="{{floatingLabel}}"\
                  aria-autocomplete="list"\
                  aria-haspopup="true"\
                  aria-activedescendant=""\
                  aria-expanded="{{!$mdAutocompleteCtrl.hidden}}"/>\

in this piece of code for angular material we see that for the attribute ng-required only isRequired is passed.

I went through the code and found that if we pass
                    ng-required="$mdAutocompleteCtrl.isRequired" 
then the required works fine.

Thanks

**Comment by epelc** [comment]
@prashant1587 Was this ever fixed? It doesn't seem to work in `0.10.1-rc3` or `rc4`.

**Comment by kamarouski** [comment]
Upgrade to 0.10.1-rc4 fixed it for me. I'm using angular 1.4.3

**Comment by epelc** [comment]
@kamarouski are you sure? I was using `0.10.1-rc4` with angular `1.3.15`. I also just checked with angular `1.4.3` and it's still not working.

It's also broken on master with angular `1.4.3` here's a [demo](http://codepen.io/anon/pen/qdQJqy). However it worked with angular-material `0.10.0` but I think that was when they still used `$scope` instead of `object.defineProperty()`.

**Comment by prashant1587** [comment]
@epelc this issue still persists in 0.10 so u need to add the fix urself. I am not sure about the version 0.11.   I ll look into it and reply
