### ISSUE TITLE
md-autocomplete dosen't working when I clicked clear icon on it.

### ISSUE THREAD

**Issue by tsdragon0404** [angular/material#3498]
https://material.angularjs.org/latest/#/demo/material.components.autocomplete
Angular Material 0.10.0
You choose one item, then click [X] on the right.
The page was locked. The element  [div class="md-scroll-mask" style="z-index: 99">  div class="md-scroll-mask-bar"></div</div] doesn't disappear.
It's not occur in previous version.

**Comment by navneet35371** [comment]
+1

**Comment by clalag** [comment]
+1

**Comment by lucasmartinez** [comment]
same issue!

**Comment by cozyazure** [comment]
+1

**Comment by jgoux** [comment]
Duplicate of https://github.com/angular/material/issues/3287

**Comment by robertmesserle** [comment]
This is resolved in master and will be fixed when 0.10.1 is released.

**Comment by venki-kratos** [comment]
well looks like not working even in 0.11.1 - may be related to some issue in query which returns a promise - loading the auto-complete results

**Comment by tchornyi** [comment]
Still reproduces on v1.1.4
