### ISSUE TITLE
Troubles with md-icon

### ISSUE THREAD

**Issue by warpdesign** [angular/material#3499]
I can't make `<md-icon>` work. Following the [documentation](https://material.angularjs.org/latest/#/api/material.components.icon/directive/mdIcon), here is what I have:

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    ...
    <md-icon> face </md-icon>
    <md-icon class="md-light md-48"> face </md-icon>
    <md-icon md-font-set="material-icons"> face </md-icon>
    <md-icon> #xE87C; </md-icon>

None of the above `<md-icon>` work. What am I missing ?

**Comment by LukaszWiktor** [comment]
@warpdesign What version of angular-material are you using? I had the same problem in 0.9.4. It started to work when I updated to 0.10.0.

**Comment by warpdesign** [comment]
I am using 0.8.3. I'll see if I can update to a newer version.

**Comment by ThomasBurleson** [comment]
@warpdesign - If you encounter a bug with Angular Material, you should always try the latest in master **before** you report the issue.
