### ISSUE TITLE
Nothing showing on Android 2.3 (Gingerbread) in native browser.

### ISSUE THREAD

**Issue by evamichalcak** [angular/material#3500]
The page stays simply blank. 
Are old versions of Android not supported? Where can I find info about supported browsers and OS?
Thanks!

**Comment by fant0m** [comment]
"Angular Material is targeted for all browsers with versions n-1; where n is the current browser version."

**Comment by rschmukler** [comment]
Indeed, ngMaterial only officially supports 4.4+ (with older versions being best effort). Sorry!
