### ISSUE TITLE
Opened md-select list won't close when click outsite/blur on firefox

### ISSUE THREAD

**Issue by ivanhtp** [angular/material#3501]
How to reproduce:
1.Open it on firefox http://codepen.io/anon/pen/qdpLdb
2.Open a select to show the items
3.Don't select any item and click outside the item list intending to close.

Only happens on firefox. Chrome and IE closes it correctly.

**Comment by iamdade** [comment]
There's no such pen.

**Comment by ivanhtp** [comment]
Sorry! just edited the 1st post.
