### ISSUE TITLE
Responsive Font Sizes for Body 1, Body 2, and Subhead

### ISSUE THREAD

**Issue by asans** [angular/material#3505]
According to Material Design Typography, the font sizes for body 1, body 2, and Subhead styles are different for desktop vs device media.

Currently, the styles are set to desktop styles and not device styles.  The font sizes should update upon device change.

![style_typography_style3](https://cloud.githubusercontent.com/assets/17964/8421086/cd70de3c-1e7e-11e5-96c7-7748b35677a2.png)

**Comment by jelbourn** [comment]
Need to check with Material UX for what they consider to be "device" vs. "desktop" for typography.

**Comment by jelbourn** [comment]
@joeyperson Do you have any info on this?

**Comment by jelbourn** [comment]
Lowing the priority on this since people can easily to their own media queries to tweak the font size.

**Comment by marisaoliva** [comment]
any update on this issue? Ux team? I need to use it and I have to decide what to do.

**Comment by patrickmichalina** [comment]
Issues like this make me think it was a mistake to incorporate the entire MD layout system in my markup. Better off just sticking to CSS.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
