### ISSUE TITLE
md-button padding should really be 8px and min-width of 64px

### ISSUE THREAD

**Issue by asans** [angular/material#3506]
Looking at md-button left and right padding, it is set at 6px when it should really be set 8px.  The min-width should be 64px, not 88px.

The following is shown in the Material Design Button Component specs:

![components_buttons_keyline1](https://cloud.githubusercontent.com/assets/17964/8421242/cc02ae34-1e80-11e5-96bd-2cb29096a196.png)

The above button dimensions ends up causing misalignment of buttons with other content in dialogs and cards.

**Comment by jlmagee** [comment]
Whatever may be done with "text" buttons need to be compatible with icon buttons

**Comment by asans** [comment]
updating the following css properties did not appear to create issues with icon buttons since icon buttons overrides certain properties.

```
  min-width: 64px;
  padding: 0 8px;
```

The above did fix the issue properly.

**Comment by marcysutton** [comment]
I think the spec must have changed, so md-button just needs to be updated.
