### ISSUE TITLE
mdTabs: md-input-container leaks watchers

### ISSUE THREAD

**Issue by jmcpeak** [angular/material#3508]
Watch count increases every time you change a tab with a md-input-container - tabs 1 and 2

This behaviour is not seen if you use a md-button - tabs 3 and 4

http://codepen.io/jmcpeak/pen/mJpvXg

```<md-content>
    <md-tabs>
      <md-tab label="1">
        <md-content>
          <md-input-container>
            <label>1</label>
            <input>
          </md-input-container>
        </md-content>
      </md-tab>
      <md-tab label="2">
        <md-content>
          <md-input-container>
            <label>2</label>
            <input>
          </md-input-container>
        </md-content>
      </md-tab>
    </md-tabs>
  </md-content>
```

**Comment by jmcpeak** [comment]
md-chips leaks 7 watches

http://codepen.io/jmcpeak/pen/LVeqaX

**Comment by jmcpeak** [comment]
If you add a ng-model it leaks 2 more...

**Comment by andreialecu** [comment]
+1, this results in huge memory leaks in only moderately complex forms, when the workflow consists of switching semi-often between tabs.

**Comment by rgolea** [comment]
+1

**Comment by piyushchauhan2011** [comment]
:+1:
