### ISSUE TITLE
md-dialog will not close on master

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3509]
Latest master, you cannot close dialog, error...

TypeError: Cannot read property 'removeChild' of null

**Comment by kugler** [comment]
We have the same exception when you have an mdDialog with mdAutoComplete inside - which calls the restoreScroll twice, while the second time the scrollMask was already removed.
I think that $mdUtil's restoreScroll should just verify that the mask exists before trying to remove it.

**Comment by rschmukler** [comment]
Fixed! Thanks @kugler for the quick tip on restore scroll being the source.
