### ISSUE TITLE
md-tooltip  Need delay before showing after mouseenter

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#3510]
Expected tooltip behaviour is that the delay only counts down when the mouse is stationary, and the delay is reset when the mouse moves.

The current behaviour means tooltips show too often and can be distracting to the user.

Observed using 0.10.0

**Comment by SanderElias** [comment]
@bluebirdtech Currently the tooltip is shown on the mouseenter event. You would prefer some timeout in there so it does not pop when a user is just 'passing' an element. I thinks that's a good idea, but I need some more people to confirm this idea

**Comment by bluebirdtech** [comment]
Thanks Sander, getting more feedback would be good.  I'm used to this behaviour from Windows, but there's a risk of less discoverability if the mouse is required to remain stationary.

Also, a quick check on Mac, tooltips do not seem to require the mouse to be stationary, but do have a long delay before showing, perhaps to minimise the 'just passing' problem.  This was observed in finder if hovering over one of the toolbar buttons.

**Comment by topherfangio** [comment]
There is also normally a ~3s delay on standard HTML tooltips to alleviate this problem:

<a href="#" title="I was delayed by about a second.">Hover Here</a>

If we do add a delay, we should ensure that the delay is only on mouse motions, not focus events from the keyboard.

That said, you can already use the `md-delay` attribute and I think it will do what you want:

```html
<md-tooltip md-direction="left" md-delay="1000">
  Refresh
</md-tooltip>
```

@bluebirdtech Does this cause issues/not work for you?

**Comment by bluebirdtech** [comment]
I recall the delayed worked fine. When I added the issue I was assuming the Windows style "start the delay timer when the mouse is stationary" behaviour was preferable.

I still feel it may be better, but having thought more about it and observed behaviour on OS X and other websites, I'm less certain.

Maybe just leave the issue open to see if anyone else wants this behaviour?

**Comment by SanderElias** [comment]
I moved the issue to the backlog milestone. We can leave it as is, and if more people want this, we can have another look at this.

**Comment by hansede** [comment]
I want this. This is useful for menu items and buttons that users will click fairly often, but usually after the first use they don't need to see the tooltip. Adding a small delay to the tooltip is a good compromise. This is a feature I have come to expect from plain HTML tooltips and from other UI frameworks.

**Comment by topherfangio** [comment]
@hansede Does the existing `md-delay="3000"` attribute not work for you? Or are you asking for us to change the default to not be `0` for all tooltips?

**Comment by hansede** [comment]
That works. I was looking for a delay in the tooltip demo and didn't see it:

[Angular Material Toolip Demo](https://material.angularjs.org/latest/demo/tooltip)

I should have been looking in the tooltip documentation:

[Angular Material Tooltip Documentation](https://material.angularjs.org/latest/api/directive/mdTooltip)

Thanks for your help @topherfangio.
