### ISSUE TITLE
mdAutocomplete: white screen when focused

### ISSUE THREAD

**Issue by iamisti** [angular/material#3514]
*Angular Material Version:* master branch
*Browsers and Operating System:* checked only on Chrome

Happens when mdAutocomplete got focused. The entirely screen has a white overlay, e.g. you don't see nothing just a white screen in your browser.

It does the following with the body element:
![screen shot 2015-06-30 at 16 50 52](https://cloud.githubusercontent.com/assets/4672916/8433925/e4b5c038-1f48-11e5-8767-486cbc53b73f.png)

**Comment by rschmukler** [comment]
@iamisti can you give us a demo? Looking at the [docs site](https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete) it seems to be working fine?

**Comment by rumbad** [comment]
it works until you clear the value using the 'x'

I think it is the following causing the issue. It gets added once you click the clear icon preventing any interaction with the page:

<div class="md-scroll-mask" style="z-index: 99">
<div class="md-scroll-mask-bar"></div>
</div>

**Comment by robertmesserle** [comment]
I believe this is resolved in master.  If not, please provide a CodePen demonstrating the issue as I am unable to recreate it.

**Comment by matjames007** [comment]
@iamisti I am having the issue mentioned... same behaviour.  This is happening with angular 1.4.4 and angular-material 0.10.1.  Did you solve the issue?

**Comment by robert07ravikumar** [comment]
I too have the same issue in md datepicker . The screen becomes white when the datepicker is openend .

**Comment by robert07ravikumar** [comment]
![capture](https://cloud.githubusercontent.com/assets/18375703/21855721/d06c7bf8-d838-11e6-8d50-4f1bc73291ef.PNG)
![capture](https://cloud.githubusercontent.com/assets/18375703/21855725/d737c898-d838-11e6-9897-d658f9c1ccbf.PNG)
