### ISSUE TITLE
md-autocomplete placeholder versus md-floating-label

### ISSUE THREAD

**Issue by jlmagee** [angular/material#3515]
Is it acceptable to use either placeholder or md-floating-label in md-autocomplete or is there a preference for one or the other?  Please advise.

**Comment by robertmesserle** [comment]
It depends on which visual treatment you are going for.  If it is being used as a form field within another form, floating label would be preferred; however, if it is a standalone item, you probably want placeholder.

**Comment by tom94zoe** [comment]
Is there a possibility to use both and choose one of them depending on a attribute? 
something like, use -placeholder-as-lable
