### ISSUE TITLE
md-option selected not working properly

### ISSUE THREAD

**Issue by cybrcodr** [angular/material#3519]
Not sure if selected is meant to work with md-option or not.  While it is not documented, there seems to be code that handles this attribute.  I think this is on version 0.10.0.

http://codepen.io/anon/pen/QbaoBQ?editors=101
```
<div ng-controller="SelectController" ng-app="MyApp">
    <md-select ng-model="user">
      <md-option ng-value="user" ng-repeat="user in users" selected="{{$first}}">
        {{user.name}}
      </md-option>
    </md-select>
</div>

angular.module('MyApp')
.controller('SelectController', function($scope) {
  $scope.users = [
    { id: 1, name: 'Scooby Doo' },
    { id: 2, name: 'Shaggy Rodgers' },
    { id: 3, name: 'Fred Jones' },
    { id: 4, name: 'Daphne Blake' },
    { id: 5, name: 'Velma Dinkley'},
  ];
});
```

**Comment by jelbourn** [comment]
I took a cursory look at this: the `attr.$observe('selected', ...)` does not seem to be triggering when the expression is `{{$first}}`, not exactly sure why without getting more into Angular's internals. I can check with someone on the team if we decide the `selected` attribute is supposed to be part of the public API (it currently is not documented).

**Comment by rschmukler** [comment]
FWIW `ng-selected` does work. [demo](http://codepen.io/rschmukler/pen/NqyKex)

**Comment by rschmukler** [comment]
As per the [angular docs on ngSelected](https://docs.angularjs.org/api/ng/directive/ngSelected) it looks like `ng-selected` is the preferred / only way to do this. Closing.
