### ISSUE TITLE
SideBar Navigation and content masks

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#352]
When Side Navigation components are shown an accompanying edge-shadow is displayed. And a transparent mask is used (underneath) the SideNav to detect mouse clicks on areas off the SideNav. These clicks are used to auto-close the SideNav.

Since the mask element is not visible (currently), clicks on the  content items are intercepted by the mask and mislead the user experience. 

### Question(s):

- Should an semi-opaque mask be shown to the user?
- What opacity and color should be the default vlaues ?
- The mask usage should be optional under what conditions ?
- The mask usage should be required under what conditions ?

**Comment by ajoslin** [comment]
@Nowis I agree that the sidenav's backdrop shouldn't be faded on desktop.

However, I also don't want a magical CSS rule that applies on desktop, I want consistency in the framework.

And since I can't think of a good API, I'm going to encourage you to use CSS:

```
@media (min-width: 960px) {
  md-backdrop.md-opaque.md-sidenav-backdrop {
    background-color: transparent;
  }
}
```

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (102/100 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:52537 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (UNKNOWN:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.82)
	(envelope-from <noreply@github.com>)
	id 1Y8c9T-000GES-FC
	for greg@biomassiv.es; Tue, 06 Jan 2015 15:59:00 -0600
Date: Tue, 06 Jan 2015 13:59:00 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1420581540;
	bh=dBF3aD1397pXGpq9bPJPuZMJN5rFQWNV/NsaUfEV2Hc=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=mgVoNozRzZ5OS3hQn76JMUzZBO8tf0AAx8MZWyVC5amqDIj0ESGnVMwtULAYrPZC8
	 VcmCKF6Ph+TaA5ncV6cuEDqeSwOnzPwHUnEGE6m+VVHPoa7n9QzYfL6FetrTgf3kMI
	 ddPmfMkhT1fvm9DEf7QIixN2yuoEs2aR/qVmzyI4=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (103/100 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:41114 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by server23.websitehostserver.net with esmtps (UNKNOWN:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.82)
	(envelope-from <noreply@github.com>)
	id 1Y8c9U-000GIn-O3
	for greg@biomassiv.es; Tue, 06 Jan 2015 15:59:01 -0600
Date: Tue, 06 Jan 2015 13:59:01 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1420581541;
	bh=1Id/wqmr420CifDOZW4DLz+PlUgqRMlyxb/QkrHhSOM=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=uUq6yR07HjIjq7lH+D6qz8Z56NgS+W8OGHRiNdsiCyojVpWv2qDzcwdwuWWv10HCZ
	 XBek9HGyezO6a9JoQW26t9W65/Z5CLgLXmH6wGiLXfMH72CM3axv3g14g9C8/dfx29
	 nSY/Y3kbtT3nv+a0T9t+yNnWN1tmyntEvr/rfuR0=
