### ISSUE TITLE
Add API to allow programmatically opening/closing menu and select.

### ISSUE THREAD

**Issue by jelbourn** [angular/material#3520]
There are situations where it is useful to programmatically open or close an input. Some use cases:
- Running a tour / guided help that opens a menu to show the content.
- Having an application keyboard shortcut that opens something or navigates somewhere such that any open menus should be closed. 
- Application listens for dance music and starts opening and closing all of the menus to the beat.

**Comment by gkalpak** [comment]
:+1:

<sub>(Especially the third is a very common usecase (and still gaining popularity by the day). Ideally, there should be a built-in service doing just that !)</sub>

**Comment by JobaDiniz** [comment]
+1 :)

**Comment by Splaktar** [comment]
`$mdMenu.open()` and `$mdMenu.close()` seem to handle this for menus.

`$mdPanel.open()`  and `MdPanelRef.close()` could possibly be leveraged by md-select, but that is unlikely to be done as it would likely be a breaking change.

I'm going to close this as the OP mostly discusses use cases for menus, which are supported now. Also there haven't been requests here or upvotes for this functionality in select.
