### ISSUE TITLE
md-auto-complete makes page unresponsive

### ISSUE THREAD

**Issue by lllpsi** [angular/material#3522]
Given the example http://codepen.io/anon/pen/QbQwwx

Simulate query for results : False
Disable caching of queries: True
Disable the input : False

When a user selects an item, selects it, presses the X button and clicks somewhere on the page, then the page becomes unresponsive. 

It works fine if the simulate query for results is true.

**Comment by robertmesserle** [comment]
This is resolved in master and will be in the 0.10.1 release.
