### ISSUE TITLE
md-tabs with md-icons

### ISSUE THREAD

**Issue by amritk** [angular/material#3524]
Is  it possible to use md-icons within md-tabs as shown in the material design components:

https://www.google.com/design/spec/components/tabs.html#tabs-usage

![components_tabs_usage_mobile7](https://cloud.githubusercontent.com/assets/2039539/8441618/5246ba5a-1f2e-11e5-8727-1859a25d5a13.png)

**Comment by MattKetmo** [comment]
You can simply put a `md-icon` inside a `md-tab-panel`:

```html
<md-tabs>
  <md-tab>
    <md-tab-label>
      <md-icon md-svg-icon="img/icons/icon.svg"></md-icon>
    </md-tab-label>
    <md-tab-body>
      Lorem
    </md-tab-body>
  </md-tab>
</md-tabs>
```

Example: http://codepen.io/anon/pen/bdKdwM

![image](https://cloud.githubusercontent.com/assets/334996/8649134/79bd03ee-2967-11e5-931b-a4cb2f4b8362.png)


However if you want an icon + a label below you may need to customise the css to enlarge the height of the tab.

**Comment by robertmesserle** [comment]
This isn't supported out of the box right now; however, I forked the CodePen that @MattKetmo posted above and added these tweaks:

http://codepen.io/robertmesserle/pen/PqaGrm

**Comment by amritk** [comment]
Many thanks!

**Comment by websirnik** [comment]
Atm md-icon inside the active tab does not change color. In my case it does not look great.
![screen shot 2015-08-31 at 23 07 09](https://cloud.githubusercontent.com/assets/282871/9591711/4dd43230-5035-11e5-9175-3e6dc4e3a5c1.png)

**Comment by george3447** [comment]
+1

**Comment by Pelu2k12** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
