### ISSUE TITLE
Angular 1.4.* & 1.3.16 breaks md-menu enter animation

### ISSUE THREAD

**Issue by dani3l** [angular/material#3527]
Since angular 1.4 and 1.3.16 md-menu grow animation does not work. I've checked the change log and found that commit:
https://github.com/angular/angular.js/commit/0adc0364265b06c567ccc8e90a7f09cc46f235b2

Hope that someone can look at it.

**Comment by dani3l** [comment]
Another component that don't behave well since 1.3.16 (and 1.4) is the md-tabs auto height animation

**Comment by ThomasBurleson** [comment]
@dani3l - Please provide more information regarding the issue that **you** are having. 

* What version of Angular Material are you using?
* Do you have a screen capture of the issue?
* [BEST] Do you have a CodePen demo to easily reproduce this issue?

> Note that that latest versions of Angular Material (master) should be fully compatible with Angular 1.4.x and animations.

---

Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by dani3l** [comment]
Hi @ThomasBurleson, thanks for the codepen starter.
I'm using v0.10.0 of angular material (latest on bower)

With angular.js 1.4.1: http://codepen.io/anon/pen/aOqpwQ
With angular.js 1.3.16: http://codepen.io/anon/pen/gpvgxP
As you can see the menu just fading in

With angular.js 1.3.15: http://codepen.io/anon/pen/XbZpeP
Works beautifully, as it should

**Comment by fxck** [comment]
seems to be broken still in 1.4.2 for me

**Comment by ThomasBurleson** [comment]
@rschmukler - can you confirm this is (a) an issue with Menu, and (b) related to $$rAF. Thx... more importantly, it would be nice to confirm this is not a Angular Material issue but an AngularJS issue.
