### ISSUE TITLE
md-menu-item - incorrect vertical alignment icon and text in IE

### ISSUE THREAD

**Issue by cornelos** [angular/material#3528]
In IE (I tested with IE11) the icon and the text of a menu item are not properly aligned. The text is placed too high. In Chrome the alignment is correct.

This can be reproduced on the Angular Material demo site: https://material.angularjs.org/latest/#/demo/material.components.menu

Screenshot IE:
![menu-item-ie](https://cloud.githubusercontent.com/assets/12172674/8450596/a73cc47e-1fdc-11e5-9500-78969f35e4d8.png)

Screenshot Chrome:
![menu-item-chrome](https://cloud.githubusercontent.com/assets/12172674/8450597/ab3f0b04-1fdc-11e5-8ee0-14fc5f7cc6b0.png)

**Comment by epelc** [comment]
They aren't vertically centered in chrome on the latest master(5fdcf905b4355c0385a02f59d2875b93e7a18ce4). Not as bad of an offset but it's still noticeable and looks bad.

![image](https://cloud.githubusercontent.com/assets/5204642/8480760/90b89576-20ad-11e5-97bb-25e05bd40293.png)

**Comment by JuHwon** [comment]
I found out that the vertical textalignment will work if you specify a height. By default there is only a min-height set (on the md-list-item-inner class), which is breaking the align-items: center in IE. http://jsfiddle.net/e93Lho0q/

Though this is only a hack i guess?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
