### ISSUE TITLE
layout="column" : Columns overlaps each other on safari

### ISSUE THREAD

**Issue by GautierThiriez** [angular/material#3530]
On Safari 8.0.6 very weird comportement of classic layout="row" layout-sm="column"

http://codepen.io/GautierThiriez/pen/BNYzed?editors=101

**Comment by kruny1001** [comment]
<div ng-controller="AppCtrl" ng-app="MyApp">

    
<div layout="row" layout-sm="column">
  <div flex>
    I flex to one-third of the space on mobile, and two-thirds on other devices.
  </div>
  <div  flex-gt-sm="66">
    I flex to two-thirds of the space on mobile, and one-third on other devices.
  </div>
</div>

try this code

**Comment by GautierThiriez** [comment]
Okay,
Now i think safari failed to calculate the height of the first <div flex>. Safari set the height to 250px.
![capture d ecran 2015-07-02 a 10 39 07](https://cloud.githubusercontent.com/assets/6089653/8473065/d2ba5286-20a6-11e5-983e-c94bc4c51fd9.png)
Left : Chrome, Right : Safari.

**Comment by chaitu87** [comment]
Faced the same issue.. Fixed it with 

<code>
[layout-sm=column] {
display: block;
}
</code>

**Comment by ThomasBurleson** [comment]
You must set an explicit height

```css
md-content #content {  height: 400px; }
```
on 

```html
<div ng-controller="AppCtrl" ng-app="MyApp">
  <md-content >
    <div id="content" layout="row" layout-sm="column">      
      <div flex="75" flex-sm="33">
        I flex to one-third of the space on mobile, and two-thirds on other devices.
      </div>
      <div flex="25" flex-sm="66">
        I flex to two-thirds of the space on mobile, and one-third on other devices.
      </div>
    </div>
  </md-content>
</div>
```

**Comment by ThomasBurleson** [comment]
Fixed in SHA e8b60de997fc06e1471d9e30a2e0f300bc18869f

**Comment by ThomasBurleson** [comment]
@robertmesserle - am i missing anything with my CodePen? Can you see anyway to avoid explicitly setting the  height of the mdContent?

**Comment by robertmesserle** [comment]
If your container doesn't have a fixed height, why would you want to use flexbox at all for stacking elements?  I'm not sure what the expected outcome is.

**Comment by ThomasBurleson** [comment]
Here is another sample with much better UX. It **does not** use a `<table>`; instead flexbox and ngMaterial Layouts are used:

![mdradiogroup as table](https://cloud.githubusercontent.com/assets/210413/9721134/5425538c-555b-11e5-9235-6bc4627d83e3.png)

> Live Demo and Source Code on [Plunkr](http://plnkr.co/edit/gzgnhrcep2csk9vuHyeY?p=preview)

**Comment by jdmorales92** [comment]
https://github.com/philipwalton/flexbugs#flexbugs
