### ISSUE TITLE
mdSubheader: High CPU usage with AngularJS 1.4.x

### ISSUE THREAD

**Issue by izstas** [angular/material#3531]
I was trying to use a sticky `<md-subheader>` and found out that on my page it appears to cause a high CPU usage when I try to scroll a container with subheaders. The subheader example at https://material.angularjs.org/latest/#/demo/material.components.subheader works just fine.

Here is the output of Chrome's CPU profiler:
![CPU profile](https://cloud.githubusercontent.com/assets/436789/8455794/dfdaf1ec-200f-11e5-8131-5d8d961f8064.png)
[.cpuprofile file](https://gist.github.com/izstas/5db0405feed0c3093091/raw/31eecf8655821325997192e5de07b34699542555/md-subheader.cpuprofile)

I am able to reproduce the problem with [this CodePen](https://codepen.io/izstas/full/xGYEbx/) on Chrome 43.0.2357.130, 45.0.2438.3, Microsoft Edge 20.10158.0.0. The page uses AngularJS 1.4.1 and Angular Material 0.10.0.

Is this a bug or am I trying to use the `<md-subheader>` in a wrong way?

**Comment by izstas** [comment]
It appears to work just fine with AngularJS 1.3.16. Still reproducible with AngularJS 1.4.2-build.4089+sha.d193c3a.

**Comment by izstas** [comment]
After further research, it appears that the issue is introduced by angular/angular.js@0adc0364265b06c567ccc8e90a7f09cc46f235b2. The problem is reproducible with this version (https://codepen.io/izstas/full/rVJYMd/) and not reproducible with the previous one (angular/angular.js@1ee58612a261f070f3d20594550f71bc4b8b0229 - https://codepen.io/izstas/full/KpQyGQ/)

**Comment by ThomasBurleson** [comment]
@matsko, @jeffbcross, @jelbourn - The latest comment from @izstas seems to spotlight a `raf.js` issue.
How should we more accurately report apparent AngularJS issues seen from Angular Material component usages ?

**Comment by jeffbcross** [comment]
@ThomasBurleson the issue should be opened on the angular.js repository with a reference to the original issue on angular/material. There should probably be some kind of "Material" label on angular/angular.js that could be applied to these kinds of issues to help track them. @petebacondarwin is that reasonable?

It'd probably be worth bringing up material-related issues in the internal angular-1 channel as well.

**Comment by petebacondarwin** [comment]
Yes, an issue should be created in Angular.js. I created a label called "hotlist: material" for this sort of thing.

**Comment by ThomasBurleson** [comment]
@petebacondarwin: I created https://github.com/angular/angular.js/issues/12280. I could not assign a label, however, since I am not a contributor to that repos. Would it be possible to add me as a contributor so I can manage issues from Angular Material - to - AngularJS ?

**Comment by nestorneto** [comment]
+1

**Comment by cah-alexsukhodolsky** [comment]
+1

**Comment by clshortfuse** [comment]
Will be fixed in Angular 1.4.5

Already fixed in master

**Comment by izstas** [comment]
Yep, seems to be fixed by angular/angular.js@dc48aadd26bbf1797c1c408f63ffde99d67414a9. Thank you!
