### ISSUE TITLE
Readonly elements

### ISSUE THREAD

**Issue by MigFerreira** [angular/material#3533]
Hi, 

Would it be possible to add read-only functionality to angular-material elements?

I see you have the slider  as a milestone for 0.10.0 but what about checkbox, select, radio button... ?
Any plans?

This is not urgent in any way, can easily be avoided using disable and styling.

Regards,
Miguel Ferreira.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
