### ISSUE TITLE
md-subheader / sticky discussion

### ISSUE THREAD

**Issue by robertbaker** [angular/material#3535]
I don't like how md-subheader wraps whatever I put into it an h2. There also doesn't seem to be any other option to make something sticky.
I wanted to make a card sticky (customer summary header), but no way to do it.

If you have 2 md-contents side by side with a md-subheader, this happens:

http://codepen.io/robertbaker/pen/bdLgmr

**Comment by dmackerman** [comment]
Yeah. `md-subheader` should be unique per `md-content`, but it appears not.

**Comment by ThomasBurleson** [comment]
@robertbaker - 

1) The `$mdSticky` service prepends the subheader clone to the parent of the mdContent container. Since the sticky subheader is positioned absolute, I think we could prepend it instead to the mdContent itself... which would then support side-by-side mdContent containers.

> It would awesome if you would submit a PR for this feature.

2) If you want to make something else sticky, you may need to create a `md-sticky` attribute directive; but I do not believe that is part of the Material specs.

@rschmukler - sounds like (1) above is a bug?

**Comment by naomiblack** [comment]
@topherfangio can you look at (1) and see if it's a bug?

**Comment by topherfangio** [comment]
0) I need to dig in a bit further, but I don't currently see any reason to use an `<h2>` tag. I will try to switch this to a `<div>`.

1) I will play around to see if we can attach it to a different place. A quick workaround we found in another issue was to wrap the `<md-content>` tags with `<div style='position: relative'>`. If it's truly as simple as this, we should be able to create a better fix.

**Comment by topherfangio** [comment]
0) I have switch to a `<div>` and all tests pass, and everything looks good from a visual inspection. The SCSS also doesn't target the H2, so I see no reason not to swap it.

1) I have attached it directly to the md-content, but this causes a side-effect: In the current version, as you scroll, the sticky header appears on top of the content, so the scrollbar actually disappears underneath it (at least in Chrome; in Firefox it looks like the picture below). With the updates, it appends inside the scrollable area, so you see the scrollbar to the right of the floating header:

<img width="499" alt="subheader-scrollbar-issue" src="https://cloud.githubusercontent.com/assets/54370/9311269/bcfe2366-44da-11e5-809b-ffd22661e905.png">

This is almost certainly the reason it appends to the parent. Which one do you feel is better behavior?

**Comment by clshortfuse** [comment]
now md-content most be at the top of the page:

https://github.com/angular/material/issues/4420
