### ISSUE TITLE
No rtl support for mdTabs

### ISSUE THREAD

**Issue by dani3l** [angular/material#3538]
Hi guys
I've noticed that there's no rtl support for mdTabs

As you can see in [this codepen](http://codepen.io/dani3l/pen/PqQpoj) the tab-items are aligned to the left. This was [easily fixed with some css](http://codepen.io/dani3l/pen/eNVgab)

Another issue is when you have alot of tabs and [the pagination don't know how to handle rtl](http://codepen.io/dani3l/pen/eNVvOx)

And last issue is that the tab-content transition should be reversed when page is rtl. Meaning that when user clicks tab "TWO" the content should come from the left-to-right and when going back to tab "ONE"  content should come from right-to-left

I found that pull request: https://github.com/angular/material/pull/1711 but I guess its related to a really early version so I don't know if it can help.

**Comment by DevVersion** [comment]
Fixed with SHA 08bf4f93763d2aea9901d697f8cc3786d242725f

**Comment by anilk533** [comment]
**RTL direction for material tabs not working.**
here is the issue.
https://codepen.io/djidel/pen/NpMpmY

please let me know how to solve

thank you
