### ISSUE TITLE
mdToast displays in incorrect position if page is scrolled

### ISSUE THREAD

**Issue by dozingcat** [angular/material#3539]
Demo: http://codepen.io/anon/pen/zGRZav . Scroll down a bit and click the "Show toast" link. The toast appears in what would be the bottom left if the page had not been scrolled, but is now the middle or top of the window. Observed in both Chrome and Firefox.

**Comment by dani3l** [comment]
1. Move `ng-app` to head
2. Apply `layout="column"` to body
3. Wrap content with `<md-content></md-content>`
4. Add `overflow-y: hidden !important` to body css to avoid double scrollbars when toast is being shown (and other material components)
5. Drink beer.

http://codepen.io/dani3l/pen/PqQpgB

**Comment by ilanbiala** [comment]
@dozingcat @dani3l there is an open issue for this at #1106.

**Comment by antonio-rodrigues** [comment]
Had to use this approach:

1) Apply layout="column" to body (this must exist at least at ng-controller level)
2) Wrap my content with <md-content>...</md-content>
3) Prevented double-scroll-bars flickering issue during the toast animation with: 
```
body.md-toast-animating {
  overflow: auto !important;
}
// Using v.1.1.0-xxx? Change to body.**_**md-toast-animating

```
