### ISSUE TITLE
$mdDialog scroll issues in IE10

### ISSUE THREAD

**Issue by smaye81** [angular/material#3540]
I am having issues with scrolling `md-dialog-content` in IE10.  Seems to work fine in IE11 and other browsers, but for some reason, the content is unscrollable in IE10.

I've even tried viewing the Material Design site and looking at the Dialogs demo and it doesn't seem to be working there either:

![image](https://cloud.githubusercontent.com/assets/911455/8464319/2943e31c-200f-11e5-9d57-cf2f55b36cf5.png)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

> Closing for now.
