### ISSUE TITLE
Remove unnecessary `transition: all`

### ISSUE THREAD

**Issue by jacksonrayhamilton** [angular/material#3543]
In as many places as possible, please remove instances of this property from your stylesheets, replacing `all` with the names of the specific properties that should be transitioned.

`transition: all` often causes unexpected properties to be transitioned. Overriding it is particularly difficult because I don't know (and don't want to have to figure out) which properties the author originally hoped to transition.

If the amount of elements that should be transitioned is finite, you should invest the time to specify those properties specifically. The time will be paid back to your users.

**Comment by ThomasBurleson** [comment]
@jacksonrayhamilton - Agreed. Recently we enhanced Progress Indicators and address this issue as part of that work.

**Comment by jacksonrayhamilton** [comment]
I did not even consider the performance implications. I was actually referring to avoiding `transition: all` as a *developer* optimization, as it saves us from having to hunt down the reasons for unexpected transitions (which are often caused by `transition: all`). But it might also have a performance benefit.
