### ISSUE TITLE
md-chips with md-autocomplete causes weird visual state

### ISSUE THREAD

**Issue by lllpsi** [angular/material#3545]
In the demo under **Use md-autocomplete to build an ordered set of chips.** click on the chips and click somewhere else. You'll notice that the border brush is messed up.

https://material.angularjs.org/latest/#/demo/material.components.chips

**Comment by typotter** [comment]
Hi @lllpsi,
Can you please provide a screenshot of what you're describing here? I've not been able to reproduce, but I'm not entirely clear on the repro specifics. Please include your browser, and specific instructions to reproduce (i.e. when you say "click on chips", do you mean click on a chip (that's been added)? Click on the input? etc.
Thanks
