### ISSUE TITLE
autocomplete: locks scroll after switching windows(requires page refresh)

### ISSUE THREAD

**Issue by epelc** [angular/material#3546]
I just found a bad bug. If you search for something in auto complete and leave the drop down open then switch windows, then come back to your browser the scroll is locked and the drop down hidden.

I think it's because `mdUtils.enableScrolling()` isn't called everywhere `ctrl.hidden = true` is set.

Try it on the demo here
https://material.angularjs.org/latest/#/demo/material.components.autocomplete

**Comment by barryvdh** [comment]
I also have the issue of freezing up other inputs.

On `Use md-autocomplete to build an ordered set of chips.` I can reproduce it on the latest Chrome (windows):

1. Start typing Brocoli, select first match
2. Start typing something that doesn't exist ( `asdf`)
3. Try to click a different input.

It will freeze and disable all scripts/inputs.. Only hard refresh will fix it. Both on 0.10.0. and HEAD

**Comment by rschmukler** [comment]
@robertmesserle I have fixed @epelc's issue. @barryvdh's issue is caused by the `hidden` watcher calling `$mdUtils.disableScrollAround` more times than it is calling `$mdUtill.enableScrolling()` - will chat with you tomorrow on ideas on how we could fix.

**Comment by andreialecu** [comment]
Also seeing the issue reported by @barryvdh when using `md-chips` + `md-autocomplete` with `md-min-length="0"`. 

After filling in the first chip, the autocomplete won't open unless you type a character, which seems like a bug in itself. However, the mask will be applied over the entire page, resulting in the same issue described here when you click away.
