### ISSUE TITLE
md-stretch-tabs="always" not working

### ISSUE THREAD

**Issue by jasonke** [angular/material#3547]
This codepen example http://codepen.io/anon/pen/NqyvWy is identical to the first example in https://material.angularjs.org/HEAD/#/demo/material.components.tabs
except that I added md-stretch-tabs="always" to the md-tabs.
It is not stretched to fit the width of its container.

**Comment by epelc** [comment]
+1 same issue with master

**Comment by brunoksato** [comment]
+1 no working for me.

**Comment by simran-k** [comment]
+1 same issue
