### ISSUE TITLE
autocomplete  with 'Simulate query for results' will show loading

### ISSUE THREAD

**Issue by liyatang** [angular/material#3551]
still loading ... 

![autocomplete](https://cloud.githubusercontent.com/assets/1010130/8475326/dc51f37e-20e9-11e5-94ee-5384ffb79ad4.gif)

**Comment by robertmesserle** [comment]
This is resolved in master and will be fixed when 0.10.1 is released.

**Comment by liyatang** [comment]
Thanks a lot!
