### ISSUE TITLE
Add license field to package.json

### ISSUE THREAD

**Issue by epelc** [angular/material#3552]
I noticed a build warning that there's no license field in package.json.

See [this](https://travis-ci.org/angular/material/builds/69292268) or any other build on travis under `npm install`.

`npm WARN package.json angular-material-source@0.10.0 No license field.`

**Comment by Splaktar** [comment]
Just opened a PR for this: #4741

**Comment by Splaktar** [comment]
Closed by https://github.com/angular/material/commit/885162b5c45acba04a44bad42f74c273e2a27a6e.
