### ISSUE TITLE
Documentation markdown needs to be fixed

### ISSUE THREAD

**Issue by Aaron-Hartwig** [angular/material#3553]
The markdown in the theming and css sections of the docs is not properly formatting the code, so it just looks like text.

Example:
https://github.com/angular/material/blob/master/docs/content/CSS/button.md
https://github.com/angular/material/blob/master/docs/content/Theming/03_configuring_a_theme.md

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
