### ISSUE TITLE
Focus is automatically set to last of multiple md-autocompletes

### ISSUE THREAD

**Issue by karlhorky** [angular/material#3554]
With multiple `md-autocomplete`s with the `md-autofocus` attribute set to true, the last element will receive the focus.
http://codepen.io/karlhorky/pen/MwQVeE

**Comment by matthieuh** [comment]
I have the same problem !

**Comment by robertmesserle** [comment]
Only one form element in a document is supposed to have the autofocus attribute.  We implemented this manually to simulate the expected browser behavior, per the spec.

http://www.w3.org/wiki/HTML5_form_additions#autofocus
