### ISSUE TITLE
Md-Chips and its embedded Md-Autocomplete - Non-matched tags 

### ISSUE THREAD

**Issue by tonyawad88** [angular/material#3557]
Hello,

I have a question regarding the **md-chips** directive with a **md-autocomplete** snap. I removed the **md-require-match**, thinking that now that the directive will accept both, matches and non-matches. The non-matches show as empty tags, I modified the HTML and JS to display both tags but now when you hit the keyboard **Enter key** on a non-matched tag, the tag doesn't get added as a JSON object. It simply get added as a string.

Any idea how to make sure both items are added as JSON object?

**JSON** (showcasing the item that I selected from the list is a JSON object, the other item is simply a string)
```JSON
[
  {"name":"Item selected from list","type":"Brassica","_lowername":"cabbage","_lowertype":"brassica"},
  "I pressed enter to add this item"] 
```
**HTML**
```HTML
    <md-chips ng-model="selectedTags" md-autocomplete-snap>
        <md-autocomplete
                md-selected-item="selectedItem"
                md-search-text="searchText"
                md-items="item in querySearch(searchText)"
                md-item-text="item.name"
                placeholder="What are you looking for ?">
            <span md-highlight-text="searchText">{{item.name}}</span>
        </md-autocomplete>
        <md-chip-template>
        <span>
          {{$chip.name || $chip}}
        </span>
        </md-chip-template>
    </md-chips>
```

**JS**
```javascript
    $scope.selectedItem = null;
    $scope.searchText = null;
    $scope.selectedTags = [];
    /**
     * Search for vegetables.
     */
    $scope.querySearch = function(query) {
        var results = query ? $scope.hashtags.filter($scope.createFilterFor(query)) : query;
        return results;
    }
    /**
     * Create filter function for a query string
     */
    $scope.createFilterFor = function (query) {
        var lowercaseQuery = angular.lowercase(query);
        return function filterFn(hashtag) {
            return (hashtag._lowername.indexOf(lowercaseQuery) === 0) ||
                (hashtag._lowertype.indexOf(lowercaseQuery) === 0);
        };
    }
    $scope.loadHashtags = function() {
        var hashtags = [
            {
                'name': 'Broccoli',
                'type': 'Brassica'
            },
            {
                'name': 'Cabbage',
                'type': 'Brassica'
            },
            {
                'name': 'Carrot',
                'type': 'Umbelliferous'
            },
            {
                'name': 'Lettuce',
                'type': 'Composite'
            },
            {
                'name': 'Spinach',
                'type': 'Goosefoot'
            }
        ];
        return hashtags.map(function (hash) {
            hash._lowername = hash.name.toLowerCase();
            hash._lowertype = hash.type.toLowerCase();
            return hash;
        });
    };
    //zz. Init
    var init = function () {$scope.hashtags = $scope.loadHashtags();};
    $timeout(function () {init();}, 300);
```

**Comment by typotter** [comment]
To achieve this, you need to provide an md-on-append expression to convert the input text into a chip/JSON object:

_template:_

    md-on-append="createChip($chip)"

_code:_

    function createChip(text) {
      return {
        foo: text,
        bar: 'my other field'
      };
    }

**Comment by tonyawad88** [comment]
Thank you @typotter @ThomasBurleson

**Comment by MaximShoustin** [comment]
Hello,

I have a bit different issue with this scenario:

If I choose chip with keyboard arrows from dropdown list and press 'Enter', **both chips are added to selected chips.**

Consider I want to add `Broccoli

`. So I type later `b`, therefore in auto-complite I see `Broccoli`. So i choose `Broccoli` and press Enter. Added `b` chip and `Broccoli`

![screen shot 2015-10-14 at 2 48 11 pm](https://cloud.githubusercontent.com/assets/5389177/10482673/a80f92ac-7282-11e5-8df6-338eedfe7f21.png)

Example in Codepan: http://codepen.io/anon/pen/jbGqZJ
