### ISSUE TITLE
Back button in FireFox inside md-chips and md-autocomplete causes weird issues

### ISSUE THREAD

**Issue by lllpsi** [angular/material#3562]
When I type something and add one chip in the md-autocomplete and hit enter and press backspace/delete, FireFox triggers the back button of the actual browser. Sometimes, when pressing backspace too doesn't delete the actual chip. It looks like the escape is being reroute to the back button of the browser.

**Comment by blakecannell** [comment]
+1

**Comment by stevenmiles** [comment]
Having the same problem with backspace and md-chips in FF 40.0.2

Can be reproduced by using docs while using FF https://material.angularjs.org/HEAD/#/demo/material.components.chips
