### ISSUE TITLE
$mdDialog - .md-actions are opening keyboard on Android (Ionic app)

### ISSUE THREAD

**Issue by bradmartin** [angular/material#3565]
Not sure what the potential conflict is, I don't have time to investigate if the ionic keyboard plugin is causing the conflict or if their is an action on the md-buttons within the $mdDialog.

The markup is copied from the demos. Both action md-buttons are causing the effect. The keyboard opens briefly then closes after the dialog hide() function is called. 
 
          <div class="md-actions" layout="row">
            <span flex></span>
            <md-button ng-click="hide()">
                Close
            </md-button>
            <md-button ng-click="sendQuickMessage()" class="md-primary" aria-label="Send Message">
                Send
            </md-button>
        </div>

Don't have any special directives or code running on the page, all very basic ng-material/ionic app code. Can't reproduce the keyboard issue anywhere else in the app, only within $mdDialog.

**Comment by bradmartin** [comment]
The app is packaged with Crosswalk and running on a 4.1 device. I haven't tested on a 4.4 device that I have, I will do that and report back with findings.

**Comment by MilosStanic** [comment]
@bradmartin I have three unrelated questions for you: 
1. Are you just using angular-material within your ionic app? Just inserting angular-material elements into ionic view containers?
2. How do you compile your ionic app to crosswalk? Are there any articles/howtos?
3. What are you using for backend? 

You can contact me via e-mail in my GitHub profile so we don't spam here. 
Thanks!

**Comment by bradmartin** [comment]
Same issue on 4.4 device.

**Comment by bradmartin** [comment]
All ng-click events cause the keyboard to open and close with $mdDialog.

**Comment by bradmartin** [comment]
I've done some quick debugging and it is an issue with an empty value in the textarea in the dialog. If I enter a value in the dialog,  hiding the dialog via all options works fine.

**Comment by bradmartin** [comment]
Removing the textarea from the dialog prevents the issue from occurring.

**Comment by bradmartin** [comment]
@ThomasBurleson @rschmukler - should/does $mdDialog support inputs and/or textareas? Not sure where to look into helping track down the bug here but glad to help if you gents can tell me what you need to help out.

**Comment by bradmartin** [comment]
Current master - 70c0c6e80391026c09785c4703becb34a690ba7b update

When viewing the app via Ionic's "Ionic View" app running through the WebView the issue is no longer present. However, the built .apk still has the issue. I'll spend some time trying to find why the event is triggered and see if I can find a fix.

**Comment by bradmartin** [comment]
Ehhh... forgot to use 'novalidate' on the FORM which was the root cause.
