### ISSUE TITLE
SideNav: how to programatically lock open

### ISSUE THREAD

**Issue by ggitau** [angular/material#3570]
Is there a way to open and lock the side nav from javascript? When i call open, it opens but there's an overlay and clicking elsewhere causes the sidnav to close.

**Comment by ThomasBurleson** [comment]
Related to API discussion on using `md-is-locked-open="<expression>"`

**Comment by EladBezalel** [comment]
rel #4973

**Comment by EladBezalel** [comment]
closing cause #4973 is the main issue for mdIsLockedOpen.
