### ISSUE TITLE
How to have a textarea with scroll?

### ISSUE THREAD

**Issue by lcpereira** [angular/material#3571]
Hello,

I could put a max-height and enable the scroll in a textarea, that it is necessary in a modal, space is smaller and a scroll would help me a lot. Would like?

Thank you.

**Comment by dwanderton** [comment]
+1 :+1:

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by lcpereira** [comment]
Thanks, 

For future reference, the link of the post is: https://groups.google.com/forum/#!topic/ngmaterial/1-Olj75tPZg
