### ISSUE TITLE
Vertical Scrollbar is Shown for <body> When a Menu is Opened

### ISSUE THREAD

**Issue by khatamnejad** [angular/material#3574]
This issue can be seen in then [Menu Demo Page](https://material.angularjs.org/latest/#/demo/material.components.menu). Every time a menu gets opened a vertical scrollbar is shown for the page; This issue can be seen on other places where a menu/pop-up is shown, for example the [Select Demo Page](https://material.angularjs.org/latest/#/demo/material.components.select). 

However, I think this issue is fixed looking at the [code](https://github.com/angular/material/blob/44fda3d71fcd59bf8efd15b201ef8904cda8ad5d/src/core/util/util.js#L127) but maybe the demo site is not updated yet.

**Comment by danieladz** [comment]
same problem here, would be great if it's solved!

**Comment by rschmukler** [comment]
I believe this is resolved in master - Can you guys check [this page](https://material.angularjs.org/HEAD/#/demo/material.components.select) and ensure that it is behaving as expected.

**Comment by khatamnejad** [comment]
Yes it is fixed.

**Comment by rschmukler** [comment]
Thanks @khatamnejad
