### ISSUE TITLE
md-autocomplete with chips, example puts text double

### ISSUE THREAD

**Issue by barryvdh** [angular/material#3575]
Using the HEAD on the demo for chips, when I autocomplete the first set, the text is added after the chip.

![image](https://cloud.githubusercontent.com/assets/973269/8504002/48cea094-21c9-11e5-97b2-3e1233a685b6.png)

This wasn't the issue a few days ago with the HEAD version.

**Comment by barryvdh** [comment]
I tested the releases, the last working release from Bower is: v0.10.0-master-5fdcf90
That means the behaviour is broken in https://github.com/angular/material/commit/9990e6186677c40f53a6248361a0ceb1c77ecdb5 or https://github.com/angular/material/commit/7430e68722f0a788b0710bb8ea9f3cf3b68b2a9b

**Comment by barryvdh** [comment]
And before that release, the text was remember, so it autocompleted the previous value, without typing.

**Comment by barryvdh** [comment]
See http://codepen.io/anon/pen/EjELNJ
Adding `md-selected-item-change="ctrl.selectedItemChange()"` and:

    self.selectedItemChange = function(){
        self.searchText = null;
    }

Does fix it, so I guess that should be a relatively small fix?

**Comment by markscholtz** [comment]
I've just run into this too with v0.10.0 and it seems to be caused when setting the "md-item-text" property of the md-autocomplete. This only seems to happen when selecting an item from the dropdown list with the mouse. Selecting an item using keyboard shortcuts doesn't appear to cause the issue.
