### ISSUE TITLE
md-chips and ng-change

### ISSUE THREAD

**Issue by xeor** [angular/material#3580]
It looks like `md-chips` currently does not support `ng-change`, and it only have an attribute (`md-on-append`), to do something when a new item is added.

Either, `md-chips` needs support for `ng-change`, or it needs an `md-on-delete` attribute.
Now, it looks like the best way is to use `scope.$watchCollection` on the md-chip ng-model attribute to trigger what you want to do.

Old issue that kinda asks the same question: https://github.com/angular/material/issues/2259
Forumpost about the same: https://groups.google.com/forum/#!searchin/ngmaterial/ng-change/ngmaterial/AHB3LEMgudI/6TARclcvjYMJ

**Comment by chinnichaitanya** [comment]
+1

**Comment by maku** [comment]
+1

**Comment by victoryancn** [comment]
+10086

**Comment by dmackerman** [comment]
`md-on-append` works for when new chips are added, so seemingly just using a generic ngChange would make sense.

**Comment by coty-crg** [comment]
+1, would make our lives a lot easier

**Comment by advancedits** [comment]
+1

**Comment by typotter** [comment]
duplicate of #3857

**Comment by vishal41190** [comment]
+1

**Comment by erinjanae** [comment]
+1

**Comment by Liam-Williams** [comment]
+1

**Comment by omarjcamo** [comment]
+1

**Comment by peter-imrich** [comment]
+1

**Comment by vrgakos** [comment]
+1

**Comment by VladimirMishyn** [comment]
+1

**Comment by tejasrivastav** [comment]
+1

**Comment by ycy233** [comment]
+1

**Comment by bolau** [comment]
md-on-add and md-on-remove work for me:
```
<md-chips ng-model="currentItem.tags" md-on-add="updateTags()" md-on-remove="updateTags()">
</md-chips>
```

**Comment by ibnYusrat** [comment]
@bolau  That actually worked! :+1:  Thank you! :1st_place_medal:
