### ISSUE TITLE
md-autocomplete: press Enter to search by text (not choosing a suggestion)

### ISSUE THREAD

**Issue by ptgamr** [angular/material#3583]
There is a need to just search for the text when pressing enter instead of forcing to choose a suggestion.
Currently, if set `,md-autoselect="false"`, when I press enter, there is no way for me to handle that.

**Comment by ptgamr** [comment]
anyone?

**Comment by bitoverflow** [comment]
+1

**Comment by ranc** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
