### ISSUE TITLE
md-fab-speed-dial: Feature request overlay

### ISSUE THREAD

**Issue by kschwidder** [angular/material#3585]
The md-fab-speed-dial calculates its height according to the fab-actions and allocates the appropriate height on the page where being applied.

md-fab-speed-dial should show the actions as an overlay like md-select or md-autocomplete such that it is visible on top of the underlying structure.

**Comment by kschwidder** [comment]
We have played with flex-order which solves our requirement. However might be of interest for others.

**Comment by topherfangio** [comment]
@kschwidder Thanks for the thoughts! I have already been asked to review the speed dial/toolbar and see if we can make it more in-line with how the menu works. We will likely do this after 0.11.0 but it should come soon.

I'm going to go ahead and re-open this so I can track it as I'm refactoring the component.

Thanks!

**Comment by deckikwok** [comment]
+1. had to do one outside of the directive. not clean.

**Comment by EricBichara** [comment]
+1 a fix for this would be greatly appreciated

**Comment by topherfangio** [comment]
@deckikwok @EricBichara @kschwidder I think I may have mis-understood the exact issue here. Can one of you describe it in a bit more detail?

**Comment by topherfangio** [comment]
After thinking about it, I believe I better understand this request. Most of the other components have been transitioned to use a new `$interimElement` service. Once the fab components are updated to use this same service, I believe it will fulfill this request.

This may or may not happen before 1.0, I will discuss with the team and update this issue with any new info.

**Comment by helmuthva** [comment]
@kschwidder: how did you solve this using flex-order? would be nice to share your workaround.

**Comment by xenit-raven** [comment]
+1 to both the initial request and helmuthva's request to share your workaround @kschwidder

I started implementing this feature expecting it would only take up the space of the initial visible icon, allowing the other icons to hover over the page.

**Comment by topherfangio** [comment]
Some of you may be interested in #4259 which may help alleviate this issue.

**Comment by stefanlorenz85** [comment]
Setting width to 0px works fine for me.
`<md-fab-actions style="width:0px;">`

[see example gif](http://fs5.directupload.net/images/160211/2hivmcmv.gif)

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (420/400 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:39350)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZl-001Z7P-DQ
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:19 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=tgbqrVJy+eGmOc0U0APZv0tFZOI=; b=roeLe94IDuuhZA8E
	WBYNPFa1ppVp0n6yJNYX2kyRM0Yw9X216BNjDrJ8WSb1amwsbpV0Ykzog3TVpfjS
	V2cYBqBgDC9gDjoWBH4S9RoIkuvxwINhItfFnbuKnydbiRcGP8ikkGjwMmYG+2Mr
	rV2htwYTmv+gTD79YoPj70BZO40=
Received: by filter0527p1mdw1.sendgrid.net with SMTP id filter0527p1mdw1.7979.572272AD50
        2016-04-28 20:29:33.975147987 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id 2a2_R-S9QU6E_v60ecpsRQ
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:34.022 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:33 -0700
