### ISSUE TITLE
md-menu appears to ignore margins above it when calculating the vertical position

### ISSUE THREAD

**Issue by richtier** [angular/material#3591]
When the md-menu opens the vertical position appears to be calculated incorrectly when there are elements above the directive that have margins.

This is such a basic problem and no one else has reported it that at this point I think I must be doing something wrong here :)

## demo
bad: menu position when there is a "element with margin of 300px" above directive. Notice the menu is not positioned on top of the black trigger button. (note I have selected the icon in the dev tools)

![image](https://cloud.githubusercontent.com/assets/5485798/8513805/2c140738-2371-11e5-8199-ca44dc8b3ece.png)

good: menu position when there are no "elements with margins" above directive. The menu is positioned on top of the black trigger button. (note I have selected the icon in the dev tools):

![image](https://cloud.githubusercontent.com/assets/5485798/8513795/0586c100-2371-11e5-9cab-08519746fdfc.png)

## html:

```html
<h3>hello</h3>
<md-menu
  md-position-mode="target-right target">
    <md-button
      class="md-icon-button"
      ng-click="$mdOpenMenu($event)">
        <md-icon
          md-menu-origin
          class="icon-navigation-black icon-navigation-black-ic_more_vert_black_24dp">
        </md-icon>
    </md-button>
    <md-menu-content
      width="2"
      style="padding: 0;">
        <md-menu-item>
            <md-button
              ng-click="item.onClick($event)">
                <md-icon
                  class="icon-edit">
                </md-icon>
                <p md-menu-align-target>Edit</p>
            </md-button>
        </md-menu-item>
        <md-menu-item>
            <md-button
              ng-click="item.onClick($event)">
                <md-icon
                  class="icon-delete">
                </md-icon>
                <p md-menu-align-target>Delete</p>
            </md-button>
        </md-menu-item>
    </md-menu-content>
</md-menu>
```

Am I doing anything obviously wrong?

I'm using `md v0.10.0` on `Chrome 39.0.2171.65 (64-bit)`

**Comment by rschmukler** [comment]
@richtier can you try using the latest from [our bower repo](https://github.com/angular/bower-material) and see if the issue persists? mdMenu had positioning logic improved since v0.10

**Comment by richtier** [comment]
thanks for response. Yep, issue persists - I installed v0.10. package.json shows `"version": "0.10.0"`

**Comment by ThomasBurleson** [comment]
@richtier - try using the lastest from #master.

**Comment by richtier** [comment]
fixed in master. thanks.
