### ISSUE TITLE
readonly md-input without a ng-model

### ISSUE THREAD

**Issue by cgx** [angular/material#3599]
If you set a value on an input field without a ng-model, the value only appears after you click on the input field:

http://plnkr.co/edit/b90ENPhrAagfejN4AuMN?p=preview

I understand that having a md-input without a ng-model is useless, but I can see cases where having a readonly md-input with a (static) value would be convenient.

**Comment by jelbourn** [comment]
Fixed via f98e8514b613a887fe513622e8bf32af99ed2085
