### ISSUE TITLE
Autocomplete block focus, and entire page from click

### ISSUE THREAD

**Issue by calebeaires** [angular/material#3602]
After choose some item, them touch on X button, then touch outside Autocomplete box, the directive stop working. The pointer cursor goes black when I put it on autocomplete box. With md-min-length bigger then 0, there is no problem.

Maybe the problem is with "aria-expanded" item.
Material version: 0.10.0

**Comment by calebeaires** [comment]
If I set css .md-scroll-mask to "initial" (or none), it solve the problem

```
.md-scroll-mask {
    top: initial;
}
```

**Comment by robertmesserle** [comment]
This is resolved in master, will be in 0.10.1 release.
