### ISSUE TITLE
md-dialog should not highlight the OK button in the dialog

### ISSUE THREAD

**Issue by dongmingliy** [angular/material#3609]
In the demo it's highlighting the OK button by default. 
This is not the case in the spec. 
https://www.google.com/design/spec/components/dialogs.html#dialogs-alerts

![image](https://cloud.githubusercontent.com/assets/6826615/8533415/e7ac8696-2402-11e5-9ddf-d883f3b4276a.png)

![image](https://cloud.githubusercontent.com/assets/6826615/8533436/15284d94-2403-11e5-95ad-273952730931.png)
![image](https://cloud.githubusercontent.com/assets/6826615/8533442/1ad121e4-2403-11e5-8243-0a03e3edc6fc.png)

**Comment by marcysutton** [comment]
The dialog spec doesn't take accessibility into account. The affirmative button is focused so that keyboard and screen reader users will be in the right location when the dialog is opened, and then focus is returned on close. This is a feature, not a bug.
