### ISSUE TITLE
bottomSheet: Implement long Bottomsheet 

### ISSUE THREAD

**Issue by rschmukler** [angular/material#361]
As per the [Bottom Sheet Specs](http://www.google.com/design/spec/components/bottom-sheets.html#bottom-sheets-behavior), I would like some clarification regarding bottom sheet

> When displaying a bottom sheet, it should animate upwards from the bottom edge of the screen. The previous content dims to give the user context of where they were previously and the modal nature of the choice. Tapping on the dimmed area dismisses the sheet, as does swiping down on the sheet. If the sheet contains more actions that can fit in the initial display, the sheet is scrollable. Scrolling should also pull up the sheet container and eventually cover the entire screen. When the action sheet covers the entire screen, add a dismiss button to the header, on the left hand side of the title.

Regarding the positioning of the close button, and the "header" - does the header refer to the title on the bottom sheet? If so, what if it doesn't have a title, such as these:

![no-header](http://material-design.storage.googleapis.com/images/components-bottomsheets-content-actionsheet_08b_large_xhdpi.png)

![icon-based](http://material-design.storage.googleapis.com/images/components-bottomsheets-content-bottomsheet_10b_large_xhdpi.png)

> When the action sheet covers the entire screen, add a dismiss button to the header, on the left hand side of the title.

What should the dismiss button look like? Does "go to the left of the title" that mean that it should push the title in more? There are only 16du to the left of the header.

> Scrolling should also pull up the sheet container and eventually cover the entire screen.

This implies that it shouldn't cover the screen when it comes in initially - what height should the bottom sheet initially be? Is it fixed, or a percentage of the screen height?

**Comment by manish2535** [comment]
Is this issue still being worked on? Another thing, the bottom sheet does not animate upwards, it just display at a certain position.

**Comment by DevVersion** [comment]
There is already a fix present for that. See #6484
