### ISSUE TITLE
md-select: UI when multiple is true

### ISSUE THREAD

**Issue by phynweb** [angular/material#3610]
A few ideas for enhancing the md-select directive when multiple is true. All use-cases derived from the Option Groups select demo. Codepen with multiple set to true on toppings: http://codepen.io/anon/pen/rVdzzb

1. While the current selection is quite clear for single selections since the dropdown closes on select and populates the select text with the selection, this is not the case for multiple selections. The color difference between selected and unselected items is a bit too subtle if we contemplate a large list (e.g. 100+ items). A check icon or some other visual cue would be helpful while the user scrolls through the list.

2.  The current functionality adds the name of all selected items to the select text. This works well if we're selecting a few items. For a large list, it might be more useful have an multiple-placeholder option that says "100 Items selected", or simply retains the placeholder "Select items..." instead of listing every item which would create a very wide select area that ends up getting cut off i.e. losing the usefulness of listing the items anyway

**Comment by phynweb** [comment]
Regarding item 2 above, i see it was discussed earlier here: https://github.com/angular/material/issues/2684#issue-72878132 and i agree with that logic for single md-select mode. I do think that enabling the multiple option presents a different problem of potentially confusing the user if we only display the first few options out of a large number, giving no cues as more items are selected and added to the end of `option.textContent` being used as the display value.

**Comment by ThomasBurleson** [comment]
Please post these comments in #3244
