### ISSUE TITLE
Google/Material Design Lite integration

### ISSUE THREAD

**Issue by vertex** [angular/material#3611]
Would it make sense to implement Google's Material Design Lite library instead of duplicating effort?

https://github.com/google/material-design-lite

**Comment by gvamsikris** [comment]
To use material design, Google provides 3 alternatives material.angular, material design lite and polymer paper components, which has better future and which one should we use.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
