### ISSUE TITLE
md-select does not update when model and items are set async simultaneously

### ISSUE THREAD

**Issue by jelbourn** [angular/material#3613]
Running example: http://codepen.io/jelbourn/pen/zGWEGr

It seems that when the options and the selected value are both set at the same time asynchronously that the the displayed item in `md-select` is not updated.

**Comment by rschmukler** [comment]
@jelbourn on my machine that example works [video link](http://files.slingingcode.com/401U2U0w3i35) what's it look like for you?

**Comment by jelbourn** [comment]
For me the `md-select` is blank when the loading is done.

![md-select is empty](https://dl.dropboxusercontent.com/u/18203969/github-images/select-empty.png)

**Comment by rschmukler** [comment]
@jelbourn just tested in Chrome, Safair and Firefox on OS X and all work as expected. Which browser / OS are you seeing this on?

**Comment by jelbourn** [comment]
I'm seeing it on the following platforms (using that CodePen): 
- Linux desktop in Chrome stable (43) and Firefox 38.
- Surface tablet (Windows 8) in IE11, Firefox 39, and Chrome (43).
- iPad in mobile Safari
- Android phone (Galaxy S6) in Chrome

I don't have a Mac myself; I'll have Rob try it out when he gets in.

**Comment by rschmukler** [comment]
Fixed in master
