### ISSUE TITLE
$mdSidenav throws error on check if exists

### ISSUE THREAD

**Issue by dohomi** [angular/material#3615]
Hi Guys,

I have a template where on some cases I use sidenav and on some I don't. But 

```
if($mdSidenav('left')){
...
}

//
No instance found for handle left
```
fails. Would be great if a condition exists to see if a sidenav ID exists. Thanks!

**Comment by sanketsaurav** [comment]
+1

**Comment by ThomasBurleson** [comment]
Use `$mdComponentRegistry.get( <id> )`... see https://github.com/angular/material/issues/1311

**Comment by ThomasBurleson** [comment]
Use the `$mdComponentRegistry.get( <id> )`.... see https://github.com/angular/material/issues/1311
