### ISSUE TITLE
mdTabs: refreshes the input fields and selects from one tab to another.

### ISSUE THREAD

**Issue by piyushchauhan2011** [angular/material#3617]
I used mdTabs to build a behaviour of form steps with first tab showing the first step of the form, second form showing the second step. I noticed that mdTabs refresh the input fields and selects and doesn't preserve them, i.e. users have to fill them out again.

What's going on here ?

![screen shot 2015-07-07 at 5 22 44 pm](https://cloud.githubusercontent.com/assets/693487/8540866/cfc7dbfa-24cc-11e5-8661-1ba87f75db08.png)

![screen shot 2015-07-07 at 5 23 30 pm](https://cloud.githubusercontent.com/assets/693487/8540881/eba33df6-24cc-11e5-9e1f-909d8644d607.png)

**Comment by schmkr** [comment]
Seems to be related to #3508 / #3692.

**Comment by piyushchauhan2011** [comment]
:+1:
