### ISSUE TITLE
Uncaught TypeError: Cannot set property top of #<ClientRect> which has only a getter

### ISSUE THREAD

**Issue by BannedForLife** [angular/material#3619]
Any one know how to fix this issue or what might be causing it?

**Comment by ThomasBurleson** [comment]
@BannedForLife - You will need to provide more information:

*  Steps to reproduce this issue (or a CodePen/Plunkr demo)
*  Version of Angular and Angular Material used
*  Browswer and version used
* Snapshot of console output 
* etc.

**Comment by BannedForLife** [comment]
OK. Here is my HTML:

<md-button >
                <md-tooltip>Move This Option Node</md-tooltip>
                <i class="fa fa-arrow-left"></i><br>
                <span>Move</span>
</md-button>

Here is my console screenshot:

![screenshot from 2015-07-13 15 04 13](https://cloud.githubusercontent.com/assets/7082410/8651430/aa62e654-2970-11e5-99db-38912ca0c667.png)


I am using google chrome version 43.0.2357.81

Angular version is 1.3.18

Angular-material version is 0.6.*

It is possible that an update to angular-material could resolve this issue. I will also try that, but if you have seen anything amiss here could you please let me know?

**Comment by ThomasBurleson** [comment]
Please upgrade to at least Angular Material v0.10.0
