### ISSUE TITLE
The menu this creating scroll when it is open

### ISSUE THREAD

**Issue by lcpereira** [angular/material#3620]
Hello,

You could check a problem in using the menu? When the menu is open, it is created a scroll, in the example you can check this problem.

Thanks.
![angular](https://cloud.githubusercontent.com/assets/10385917/8544670/afa477f6-247d-11e5-8d7d-b41c1798dc74.gif)

**Comment by ThomasBurleson** [comment]
Have you tested with the latest code from the  #master repository branch?

https://material.angularjs.org/HEAD/#/demo/material.components.menu

**Comment by lcpereira** [comment]
Perfect, with the #master, the scroll is not displayed. 

Thank you
