### ISSUE TITLE
Progress Circular - larger sizes look awful

### ISSUE THREAD

**Issue by jascination** [angular/material#3621]
At present, trying to get a bigger "progress circular" bar using `md-diameter` looks pretty awful. As far as I can tell all that's happening is that `-webkit-transform: scale(whatevervalue);`is being applied directly to the element, and in turn you get a blocky pixellated bar like this:

![Angular Material Progress Circular Large Size](http://i.imgur.com/9j3P9lF.png)

Surely there are some better ways of doing this that scale properly?

**Comment by GustavoCostaW** [comment]
+1

**Comment by ThomasBurleson** [comment]
ProgressCircular has been designed with default size of 50px. Shrinking (scaling down) should not be a problem, increasing/scaling does unfortunately show aliasing effects. 

If you want to increase the size of the loader:
* recompile the progressCircular.scss: set the `$progress-border-width` and `transform:scale(1.0)`
* or use a vector-based [animated SVG ProgressCircular](http://codepen.io/saadeghi/pen/IBhfJ)

**Comment by ThomasBurleson** [comment]
@jascination, @GustavoCostaW - ProgressCircular has been updated with SHA 9ea03625394de1e71bb8a26fc1082ab93b2a6f80. The default size is now 96px with a 0.5 scaling applied; unless overridden by an `md-diameter` value.

**Comment by GustavoCostaW** [comment]
@ThomasBurleson Thank you!
