### ISSUE TITLE
md-toast, use auto height

### ISSUE THREAD

**Issue by barryvdh** [angular/material#3622]
Instead of using a set height (based on the baseline), why not set the height to auto, remove the max-height and set the min-height to the variable `$toast-height`?

**Comment by Londovir** [comment]
This code change breaks IE11 vertical centering of the md-toast contents. This can be seen in the HEAD demo page, and is a known IE11 flexbox bug as discussed at http://philipwalton.com/articles/normalizing-cross-browser-flexbox-bugs/

Once you drop the height from being specifically set to a min-height setting instead, IE11 cannot determine the height for its align-items CSS, and therefore everything gets anchored to the top of the box.

This crops up in #3764, #3528, and I believe #946, as well as probably some other issues for the exact same reason.

**Comment by ThomasBurleson** [comment]
@Londovir - I think simply removing `min-height:: 2*$toast-height;` will solve this problem. What are your thoughts ?
