### ISSUE TITLE
md-tab problem when press native button

### ISSUE THREAD

**Issue by rawatsandeep670** [angular/material#3624]
I working with md-tab. but when i click back and forward native button of browser. it not update selected tab...

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (409/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:55411 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZV-001Z3f-3P
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:03 +0200
Date: Thu, 28 Apr 2016 13:29:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875359;
	bh=zREZeoeP1KL/yU4WFPoyI9Vv7eTvA5IuIdxtHky0pDs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=he6AOgMIwPGLKgbyxfaYyOHU/JpFB496d8R3ThCcatLwhipDzySGeTHF6OHuk0a69
	 UudSnDWYhEf4sul1+PK8dh9oE+F1fDd9+/9Voe5eBAhDsKEYTEhL5u4iEui7THEi8S
	 pb3sqXvfIh+FHPwSgWHMev3RD7vVdfoCo8EEn8Cw=
