### ISSUE TITLE
md-select isn't populating selected from model

### ISSUE THREAD

**Issue by prestonvanloon** [angular/material#3625]
When using md-select with existing selected data, the directive does not display selected properties. Properties that are selected again are duplicated in the model. 

Example: http://codepen.io/anon/pen/XbEYbb

**Comment by prestonvanloon** [comment]
When using ng-selected on the options, it duplicates the property in the model. As a work around, a copy must be used.

http://codepen.io/anon/pen/zGWaqr

**Comment by gkalpak** [comment]
This happens because the items are checked by reference (by default).
There are 2 ways to fix this:

1. Use the actual objects from the `users` list (not copies of the objects):

```js
$scope.users = [
  {id: 1, name: 'Scooby Doo'},
  {id: 2, name: 'Shaggy Rodgers'},
  {id: 3, name: 'Fred Jones'},
  {id: 4, name: 'Daphne Blake'},
  {id: 5, name: 'Velma Dinkley'},
];
$scope.selectedUsers = [
  $scope.users[3],
  $scope.users[4]
];
```

2. Use `ng-model-options#trackBy` to specify how to _recognize_ items:

```html
<md-select ng-model="selectedUsers" ng-model-options="{trackBy: '$value.id'}" ...
```

**Comment by prestonvanloon** [comment]
Gotcha, maybe this could be better documented for angular material. I see it on the TODO for md-select, so I will voluntarily close this issue. Thanks!

https://github.com/angular/material/blob/master/src/components/select/select.js#L12
