### ISSUE TITLE
md-select page jump in IE10/11

### ISSUE THREAD

**Issue by wlingke** [angular/material#3627]
http://codepen.io/anon/pen/EjERWg

I've wrapped the form area in between two long pieces of text so it's easier to see the issue. Here are the two behaviors I've observed:

1) If you click on the select then click outside to exit, it jumps to top of page
2) if you click on the select and select an item, pages to focus on bottom of select

**Comment by wlingke** [comment]
Probably related to #3479  and #3020

**Comment by rschmukler** [comment]
@wlingke can you try the demo I just posted in #3479

**Comment by wlingke** [comment]
The demo didn't work. The select still jumps to bottom of select element and auto complete jumps to top of page.

**Comment by rschmukler** [comment]
Thanks @wlingke
