### ISSUE TITLE
md-input-container for autocomplete/select/checkbox

### ISSUE THREAD

**Issue by barryvdh** [angular/material#3630]
The `md-input-container` doesn't work consistently across all inputs, it that supposed to be?

For example, adding errors (and `md-is-error`) to autocomplete or a group of checkboxes would probably be easier if it would always be a md-input-container, right?

**Comment by Frank3K** [comment]
+1

For `md-checkbox` some CSS selectors do apply when the checkbox is wrapped inside an `md-input-container`. Some other rules do not apply; the error message does not display is red for example. 

The current [checkbox directive](https://github.com/angular/material/blob/6dd783f3cfdc580a0ca0eb1e10646fb3d3f1544c/src/components/checkbox/checkbox.js) is not linked to the `md-input-container` as the [input directive](https://github.com/angular/material/blob/1d71928ee7480464d34749284cb326d3ad127f93/src/components/input/input.js) is.

**Comment by pdore-netfore** [comment]
+1

**Comment by haenig** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (613/500 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:54015 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdJ-000LkB-8o
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:57 -0500
Date: Thu, 28 Apr 2016 13:32:28 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875548;
	bh=Lfh5J+Hl0jSo4MWrTlYaFumv7fWAiR1d094u2DUE/jQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Nt6yqy1biJSbi/jZFV3uMaCF/gVLhx3OWSOSBP8pXT/QgmifzMDk0uXmj1SJ1vEgl
	 nNRWpQ0qaUst8ddAiwCf+uwWix3J4jgFi/U+ekDEkZOJyn+1DJBYOSHm5P/ezkfKOk
	 KY0IhN1J9wsZWCyPyfK3qlFM7pWI5QqbB4IkTbH4=
