### ISSUE TITLE
md-list : iterating the list using the keyboard up and down arrows

### ISSUE THREAD

**Issue by TalPasi** [angular/material#3631]
The only way we have today to iterate the list items using the keyboard, is by pressing the 'Tab' key,

This is not intuitive when it comes to iterating a list of items, it gets even worse when you have a secondary action associated with the items. 

Please provide up and down navigation using the keyboard arrow keys

Thank you

**Comment by ThomasBurleson** [comment]
Duplicate of #2255

**Comment by demiro** [comment]
this is def. not duplicate to the other ticket.
we need this functionality in mat-nav-lists

**Comment by Splaktar** [comment]
@demiro Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
