### ISSUE TITLE
mdFabSpeedDial: add support for data- and x-prefixes when using ng-repeat

### ISSUE THREAD

**Issue by Frank3K** [angular/material#3632]
On the current master (e6c757c) the `md-fab-speed-dial` is missing support for the `data-` and `x-` prefixes for `ng-repeat`. The directive does work, however the animations are incorrect: the animation for a 'down'-speed-dial goes both down *and* up (i.e. it is shown *above* the fab-trigger).

Demo (regular demo with `data-` added): http://codepen.io/anon/pen/xGWabe

I think the issue comes from the following [part of the code](https://github.com/angular/material/blob/5e3a651f4429b827a567e5d3a4da85cca11e6364/src/components/fabActions/fabActions.js#L33-L39):

```js
        if (children.attr('ng-repeat')) {
          children.addClass('md-fab-action-item');
        } else {
          // After setting up the listeners, wrap every child in a new div and add a class that we can
          // scale/fling independently
          children.wrap('<div class="md-fab-action-item">');
        }
```

**Comment by topherfangio** [comment]
Indeed, thanks for catching this.

**Comment by topherfangio** [comment]
Still working on this, should have code merged this week.
