### ISSUE TITLE
md-menu position  on target-right after 0.10.1-rc1 issue

### ISSUE THREAD

**Issue by dohomi** [angular/material#3634]
Hi Guys,

I think its a step backwards on ```md-menu```that on ```md-position-mode="target-right target"``` the alignment of the ```md-icon```is not on the right corner any more. In the docs I've seen that you included ```style="width:190px"```on the ```<p>```tag, before in ```0.10.0```this alignment worked without the CSS style.

I read the CHANGELOG but couldn't find anything related, so I guess it is because of the change what you made on ```md-button```? Is there a possibility of changing the behaviour inside of ```md-menu-item``` for all ```md-button``` elements?

**Comment by ThomasBurleson** [comment]
`buttons` are not allowed to use `display:flex`; hence the change to `display:inline-block`.
If you wish to use flex box within the button content, use a wrapper `div`:

```html
<md-menu-item ng-repeat="item in [1, 2, 3]">
  <md-button ng-click="ctrl.announceClick($index)">
    <div layout="row">
      <p flex>Option {{item}}</p>
      <md-icon md-menu-align-target md-svg-icon="call:portable-wifi-off" style="margin: auto 3px auto 0;"></md-icon>
    </div>
  </md-button>
</md-menu-item>
```

**Comment by dohomi** [comment]
@ThomasBurleson thanks for your quick response :+1: The change is very convenient.
