### ISSUE TITLE
md-chips : close button alignment on firefox

### ISSUE THREAD

**Issue by xtiggerk** [angular/material#3636]
Actually, close buton on chip is not properly align in Firefox (works fine in Chrome Angular V0.10 and 0.10.1 rc-1) 
Can see it on the demo : https://material.angularjs.org/0.10.1-rc1/#/demo/material.components.chips

**Comment by naomiblack** [comment]
<img width="935" alt="screen shot 2015-07-30 at 5 29 11 pm" src="https://cloud.githubusercontent.com/assets/2286589/8998345/8ed00c82-36e0-11e5-81c9-bb6038218ed0.png">

**Comment by topherfangio** [comment]
Fixed by af3ef52228155b83b196ebd6376a8a868863d29f; should be available in 0.11 and is currently available in master.
