### ISSUE TITLE
mdSelect doesn't display a scrollbar with more than 5 elements

### ISSUE THREAD

**Issue by ctomoiaga** [angular/material#3638]
I think the scrollbar should be visible with more than 5 elements. Otherwise people may be inclined to believe that only 5 options are present.
This can be seen in the angular material demo (HEAD or LATEST).

**Comment by rschmukler** [comment]
@ctomoiaga this appears to be working fine for me on master. Please reopen with a demo and browser info if this isn't the case for you.
