### ISSUE TITLE
Unable to select paginated-to tab after paging with arrow buttons < >

### ISSUE THREAD

**Issue by jimmyorr** [angular/material#3639]
Unable to select paginated tab after paging with arrow buttons < >

To reproduce:

1) have md-tabs with enough tabs that arrow buttons < > for pagination are visible
2) click right arrow button > to see more tabs
3) click one of the more tabs that weren't previously visible before clicking right arrow button

Expected: tab is selected
Actual: tab view resets back to initial tab

Able to reproduce on Chrome Version 43.0.2357.132 (Linux), but not on Chrome Version 43.0.2357.130 (Chrome OS).

http://codepen.io/anon/pen/MwVdZK
http://gfycat.com/SpryEnragedJaeger

**Comment by llwt** [comment]
I'm running into this same issue.

@jimmyorr  did you find a fix/workaround by any chance?

**Comment by jimmyorr** [comment]
@llwt no, but I can no longer reproduce it on Chrome v44.  Are you still seeing it on v44?

**Comment by llwt** [comment]
@jimmyorr Yeah, still having  issues with `Version 44.0.2403.125 (64-bit)` on OSX with angular-material `v0.10.0`.

It works as expected maybe 25% of the time, I haven't been able to determine why it works some of the time and not others.

**Comment by jimmyorr** [comment]
@llwt sorry, you're right, I'm still seeing it with 44.0.2403.125 on Linux (using http://codepen.io/anon/pen/MwVdZK to test).

**Comment by mmatheson1** [comment]
Just tried with the next release (v0.10.1-rc5) and this bug seems to be resolved there.
