### ISSUE TITLE
md-toast no longer animating with angular-animate 1.4.x

### ISSUE THREAD

**Issue by ryanespin** [angular/material#3640]
When using angular-animate 1.4.x, the animation of the toast moving is no longer happening.

Here's an example of it work with 1.3.15:
http://codepen.io/ryanespin/pen/mJxZNJ

Here's one of it not working with 1.4.2:
http://codepen.io/ryanespin/pen/domBaE

**Comment by rscottfree** [comment]
The codepen example you give for it not working in 1.4.2 is working fine for me.
