### ISSUE TITLE
Serious issue with md-dialog in latest master

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3642]
I am unable to diagnose what is causing the issue but whenever objects are passed in via locals there is a 20-30 second delay in opening the form. It also looks as if the object passed in is being mutated in some way if it is passed back on the close event. 

I'm not sure how best to demonstrate in codepen. Has anything of note been changed in the past few builds?

**Comment by ThomasBurleson** [comment]
@hodeyp - If you provide a Demo that shows the 30sec delay; we can debug.

**Comment by hodeyp** [comment]
Yep, working on a demo as we speak.

**Comment by bradmartin** [comment]
I noticed a delay in a previous version, but I just pulled the master with @ThomasBurleson  dialog/menu fix and it's back to normal behavior for my project which passes locals in the dialog.

**Comment by hodeyp** [comment]
yep, i'm not experiencing large delays on opening anymore. There is still something odd happening on the promise resolution, am trying to replicate in a demo now

**Comment by hodeyp** [comment]
@ThomasBurleson - I have not managed to recreate the delay, I'm going to discount that as transient issue.

However, the mutation of the locals is most definitely an issue. In 0.10.0, the if I pass an object as a local into a dialog, and then return the object in the hide() promise it returns the same object. In master, it is returning a copy of the object, this is a major issue for me as the data persistence library (angularfire) cannot save a copy of the object, it has to be the original object.

**Comment by hodeyp** [comment]
closing issue, reopening with new & more specific detail
