### ISSUE TITLE
No focus style for md-radio-group when no button is selected

### ISSUE THREAD

**Issue by calebegg** [angular/material#3643]
Focus is shown on a radio group with at least one selected item (as an ink ripple around the selected item), but not on a radio group with no selected items. This is contrary to the spec:

https://www.google.com/design/spec/components/selection-controls.html#selection-controls-radio-button

To reproduce:

0. Go to the [radio button demo page](https://material.angularjs.org/latest/#/demo/material.components.radioButton)
0. Remove all the radio buttons from the second demo using the "remove" button
0. Add back some items using the "add" button.
0. Tab into the radio group and notice that there's no way to tell it's focused.

**Comment by tccBen** [comment]
I found one way to handle this issue by styling the radio buttons to all highlight with the focus background when none are selected. Behavior is normal once one of the radio buttons is selected.

```
md-radio-group.md-focused.ng-pristine md-radio-button .md-container:before {
    background-color: '{{background-color}}';
    left:-8px;
    top:-8px;
    right:-8px;
    bottom:-8px;
    }
```

**Comment by michahell** [comment]
Elaborating on @tccBen 's answer, here is something that looks similar to how checkboxes are focused in chrome:

```
md-radio-group.md-focused.ng-pristine md-radio-button:first-child .md-container:before {
	background-color: rgba(0, 0, 0, 0.15);
	left: -8px;
	top: -8px;
	right: -8px;
	bottom: -8px;
}
```
