### ISSUE TITLE
How to use custom Date format?

### ISSUE THREAD

**Issue by stefan-niedermann** [angular/material#3644]
Hi there,

i live in Germany and our Date Format ist dd.mm.yyyy.

It does not seem to be possible to use our Date Format instead of the american yyyy-mm-dd. Are there any best practices to use our Date Format?

If not, please feel free to interpret this issue as a feature request for an attribute md-date-format="dd.mm.yyyy". :)

Best Regards

**Comment by lyrl** [comment]
same problem

**Comment by lyrl** [comment]
i just want get date`2015-07-20`, not need UTC date  `2015-07-19T16:00:00.000Z`.

**Comment by xtiggerk** [comment]
You can add filter : something like : {{ yourdate | date:"dd:MM:yyyy" }}
 See angularjs doc : https://docs.angularjs.org/api/ng/filter/date?PHPSESSID=cae8e98e7ca559b4605d75c813b358ee

**Comment by ThomasBurleson** [comment]
use DatePicker and $mdDateLocaleProvider.
