### ISSUE TITLE
md-dialog can no longer receive references to objects via locals or resolve

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3651]
the change committed in bee05239014e5eb8a0ae1b9e842f32c9caa9474b that fixes issue #2676 has broken 'md-dialog' ability to inject objects into the dialog.

I believe that locals & resolve functions that return an object should pass that object to the 'md-dialog' instead of a copy of that object. This is exactly how router libraries works with resolve/data functions. Also, I believe that the whole concept of angular injection is to pass the original reference into scope, not a copy.

In my use case, using angularfire for server synchronisation. If a user needs to change a record a dialog is shown with a form, user makes the change and then clicks save. The save returns a promise that then allows the object to be saved back to the firebase location. Because the promise is now returning a copy of the object instead of the original object the save method fails.

Please consider removing this commit from material.

**Comment by ThomasBurleson** [comment]
See comments - https://github.com/angular/material/commit/bee05239014e5eb8a0ae1b9e842f32c9caa9474b#commitcomment-12078518

**Comment by no-more** [comment]
+1

I don't understand why the behavior was changed. Please rollback to the previous version.
I'm also not sure to understand why we have resolve & locals. they seems to behave exactly the same way. Can't we use a single parameter for both?

Thanks.

**Comment by Frank3K** [comment]
+1

Some objects cannot be properly copied using JavaScript, e.g. [File objects](https://developer.mozilla.org/en-US/docs/Web/API/File).

**Comment by stefan-schweiger** [comment]
+1

It makes life so much harder when not being able to work with references via locals in the dialog
