### ISSUE TITLE
(md-dialog) focusOnOpen enhancement request

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3652]
feature request, if an input on a dialog has autofocus attribute set, do not call autoFocus(). If you do not set focusOnOpen : false on the dialog constructor it prevents the input getting focus. 

I know you can set the focusOnOpen but having to remember to do it each time is prone to error. It makes sense that the focusOnOpen first looks to see if any input would get focus and not set focus to the dialog in this situation.

**Comment by stunaz** [comment]
This can be closed, you can use `md-autofocus`

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
