### ISSUE TITLE
<md-tabs>  no longer animating with angular-animate 1.4.x

### ISSUE THREAD

**Issue by tuchk4** [angular/material#3653]
Here's an example of it work with 1.3.15:
http://codepen.io/anon/pen/wajGgE

Here's one of it not working with 1.4.2:
http://codepen.io/anon/pen/bdMpgm

Something like with **md-toast** animatig https://github.com/angular/material/issues/3640

**Comment by z3v0k0d3** [comment]
fixed v0.10.1-rc1

**Comment by dmackerman** [comment]
This isn't working in `0.10.1-rc3`.
