### ISSUE TITLE
md-autocomplete with md-highlight-text on a custom directive

### ISSUE THREAD

**Issue by PDSBGreg** [angular/material#3656]
With an md-autocomplete that uses a custom directive as it's item-template and md-highlight-text to show the highlighted lettering, the directive appears to be converted to a string (as oppose to its native HTML parts). See the following codepen.

http://codepen.io/anon/pen/YXLGmN

Removing the md-highlight-text attribute on the custom directive results in the directive's template being displayed correctly.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
