### ISSUE TITLE
403 forbidden on bower-material/master/angular-material.js

### ISSUE THREAD

**Issue by wezley98** [angular/material#3657]
src="https://gitcdn.xyz/repo/angular/bower-material/master/angular-material.js

getting 403 forbidden on this url.

**Comment by xplodwild** [comment]
Works fine for me

**Comment by wezley98** [comment]
Getting this error msg from gitcdn when hitting that url above:

Error 1000 Ray ID: 20351ff7d6960a6c • 2015-07-09 15:40:00 UTC
DNS points to prohibited IP

**Comment by xplodwild** [comment]
It seems like your IP address is blacklisted, by what seems to be CloudFlare. You might want to get in touch with them to check why.

**Comment by wezley98** [comment]
![screenshot from 2015-07-09 16 43 49](https://cloud.githubusercontent.com/assets/1488209/8599661/c12885de-2659-11e5-95d9-a8f0177d828d.png)

Not sure why it would be blocked its a private ISP IP address from Virgin in the UK.

**Comment by wezley98** [comment]
hmmm, just went through a proxy and you are correct its working.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
