### ISSUE TITLE
Hierarchical Timing Animation Directive

### ISSUE THREAD

**Issue by cozyazure** [angular/material#3660]
Hi,

I have done up a directive on <a href="https://www.google.com/design/spec/animation/meaningful-transitions.html#meaningful-transitions-hierarchical-timing">Hierachical Timing</a>. I wonder if this directive would be useful enough to serve the use cases of displaying a list of items.

Here is the link to the codepen: http://codepen.io/cozyazure/pen/ZGoBZW

Feature / Usage:
For any items that you want to have hierarchical timing animation, just wrap it with ```hierachy-display```. Works with ```ng-repeat```.

Possible improvements to be done on this directive:
1. Probably need to implement a new child directive, say ```hierachy-display-item```. Write now I am animating every single dom elements that goes under the ```hierachy-display```.
2. Exponential time functions for the animation to delay instead of linear ones. Current delay function is ```index``` divide by ```10```.
3. As of point 1, have a child directive that listens to parent ```hierachy-display```. Remove ```$timeout```. I am using ```$timeout``` for a workaround to ensure ```ng-repeat``` is rendered before the animations kicks in.

I apologize as I am relatively very new to Github and big-scale open source project. Let me know if this has been a duplicated issue /new feature request. I searched through the issue list and only found <a href="https://github.com/angular/material/issues/206">#206</a>

Also let me know if I can submit a pull request and contribute to this awesome project.

**Comment by Frank3K** [comment]
The animation looks nice! 

I see you are doing the animation 'by hand'. Have you looked into the [$animate service](https://docs.angularjs.org/api/ng/service/$animate)? Although I haven't use that service myself, I think that's the way to go with animation in AngularJS; this project also uses it for several animations.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
