### ISSUE TITLE
[enhancement] : md-card with flex-direction = row

### ISSUE THREAD

**Issue by patouche7519** [angular/material#3661]
Hi,

it would be great if we had a md-card with flex-direction = row responsive (flex-direction = column for small screen) and a parameter x for the width of the image  (where x can vary from 0 to 100 % of the initial width of the image. Not sure that 0 is a good idea :) ). The height could adjust automatically to keep the initial ratio.

you make a great job, keep going...

Thks

**Comment by stefan-schweiger** [comment]
Couldn't you simply use this as shown in the [documentation](https://material.angularjs.org/latest/#/layout/options)?

```HTML
<md-card layout="column" layout-sm="row"></md-card>
```

**Comment by patouche7519** [comment]
I already use it and it works good. But sometimes I need a card with image on the left and the text near it (right side). Actually I have to specify some css for the image because in a flex direction = row, the md-card-image class doesn't work properly, the resize is uggly.
I will try something tonight (GMT) . Perhaps I missed something.

**Comment by stefan-schweiger** [comment]
How about something like this? The image gets streched a bit before shifting, but I guess this too can be fixed with some css.

http://codepen.io/anon/pen/aOGYjG

**Comment by patouche7519** [comment]
Indeed I missed some flex o_O... Your Codepen seems perfect for my need

Closing issue

Thks
