### ISSUE TITLE
<md-input-container> Behaves as if There is an Icon in It

### ISSUE THREAD

**Issue by khatamnejad** [angular/material#3663]
If we put an `<input>` tag with a `placeholder` attribute (label) in a `md-input-container` tag - which does not have any attributes like `flex` or `md-no-float`, we can see that the container assumes there is an icon before the `<input>` so moves the label forward (adds padding to it). This can be seen [here](http://codepen.io/anon/pen/jPxmPQ). 

The HTML code that can produce this problem:
```HTML
<md-input-container>
    <input ng-model="user.email" type="email" placeholder="Email (required)" ng-required="true">
</md-input-container>
```

**Comment by khatamnejad** [comment]
Hello!

**Comment by topherfangio** [comment]
Sorry for the delay. I believe this is no longer an issue. Here is your exact Codepen updated to use master.

If you are still seeing this issue after upgrading, please comment and we will reopen.
