### ISSUE TITLE
Sometimes on the first load fonts are broken

### ISSUE THREAD

**Issue by THPubs** [angular/material#3668]
Sometimes on the first load the fonts are broken like this. But when I reload things work fine. This is the first time I encounter a problem like this in my projects and this is the first time Im using angular. Please help.

![angular-fonts](https://cloud.githubusercontent.com/assets/1212023/8612790/0a9b5058-26f4-11e5-9f88-6898120a271d.png)

**Comment by rakeshashetty** [comment]
I am facing the same issue. I am facing this issue only in Mac.  Did u find any solution to it ?
