### ISSUE TITLE
Displaying md-checkbox horizontal next to other elements fails

### ISSUE THREAD

**Issue by stefan-niedermann** [angular/material#3669]
If i have an input or select on the left side and a checkbox on the right side (via flex), the checkbox label seems to be misplaced, because there is no padding:

![display horizontally with flex](https://cloud.githubusercontent.com/assets/4741199/8613898/772cf3b2-26e4-11e5-8501-43404878dcc1.png)

**Comment by topherfangio** [comment]
@stefan-niedermann Any chance you could provide a [Codepen](http://codepen.io) that demonstrates this so we can see an exact scenario?

**Comment by stefan-niedermann** [comment]
problem solved by wrapping md-checkbox with an md-input-container.
