### ISSUE TITLE
Bug: md-contact-chips add [object Object] when autocomplete

### ISSUE THREAD

**Issue by Alexandre-io** [angular/material#3670]
Here is the example from master:

![capture](https://cloud.githubusercontent.com/assets/8135542/8615734/c499eea0-26f5-11e5-8394-524ce1f33864.PNG)

**Comment by pencilcheck** [comment]
Same thing for normal autocomplete chips, the searchText is not cleared when autocomplete.

**Comment by julian-iFactory** [comment]
[Object Object]  Issue also after updating from a 0.9.x to v0.10.1-rc1. I have two chained md-autocomplete. When the first md-autocomplete is set it triggers values for the second. E.g. Country > Region. the second md-autocomplete then shows [Object Object] - This does not seem to stop it working though you can proceed to pick the region.



![image](https://cloud.githubusercontent.com/assets/4917381/8668339/6cb36440-2a4d-11e5-851b-a3d5837453d9.png)

**Comment by webley** [comment]
+1

**Comment by petrogad** [comment]
+1

**Comment by yigaldviri** [comment]
+1

**Comment by jozsi** [comment]
+1

**Comment by ambusreedharanxad** [comment]
+1 I am using version 0.11.4 and the issue still exists. 
![screen shot 2015-10-20 at 4 37 28 pm](https://cloud.githubusercontent.com/assets/8421007/10623966/e97a6878-7748-11e5-9acf-be7ab10fb15f.png)

**Comment by AllaanR** [comment]
+1

**Comment by brunoflegler** [comment]
You can not instantiate the variable used in the ng-model, however the variable md-highlight-text should be excluded from the $scope. Example delete $scope.searchText;
