### ISSUE TITLE
'Hangs' when eg. interacting with e.g Autocomplete Custom Template

### ISSUE THREAD

**Issue by matthiasg** [angular/material#3672]
To reproduce:

1) Goto: https://material.angularjs.org/latest/#/demo/material.components.autocomplete
2) Select an angular repository from the Custom Template example
3) Press the X

-> Chrome 43.0.2357.132 m (64bit) hangs on Mac OS X 10.9 Mavericks and Windows 10

**Comment by no-more** [comment]
Hi,

This is not only on autocomplete. I have just retrieve the last master version, and I have this issue on menu and select too. It seems related to the backdrop being in front and there's no way to close it.

**Comment by matthiasg** [comment]
this seems fixed in 0.10.1. sadly pressing TAB does not select the top item in the drop down .. you have to make two keypresses (cursor down and enter)...

**Comment by robertmesserle** [comment]
@matthiasg There is an option for this: `md-autoselect` will make it so that the first match starts out focused.

**Comment by matthiasg** [comment]
@robertmesserle thanks
