### ISSUE TITLE
Styling issue ie10

### ISSUE THREAD

**Issue by blxstar** [angular/material#3673]
Hey,

there are a few styling issue with the ie 10.

Toolbar -> flex layout = icons (buttons) are on the left instead of the right side. see https://material.angularjs.org/latest/#/demo/material.components.toolbar    (first example)

Card -> Padding not working. 
https://material.angularjs.org/latest/#/demo/material.components.card

Dialog -> same padding issue here
https://material.angularjs.org/latest/#/demo/material.components.dialog

greetings

**Comment by naomiblack** [comment]
Sorry, IE10 is out of scope for this project. You might want to check out http://www.getmdl.io/
