### ISSUE TITLE
[Enhancement] Autocomplete option to allow search put in input when no selection found.

### ISSUE THREAD

**Issue by robgrimball** [angular/material#3674]
An option of some sort (md-search-when-not-selected?) that would allow whatever is in the search field to be put into the input specified would be very nice.  While I understand many people would not want to enable this option, I imagine many would find it useful for allowing both selection from the list and the option of adding your own data.

Ie, say the select list is ['testA', 'testB', 'testC']

And say the person types in 'xyz' into the search box.  None of the options will display of course, and the xyz will be left there in the search box, but the input will be empty.  This is good in that if you don't want the user giving you their own suggestion outside the select list, then it doesn't populate the input and you can get the error that an option isn't selected.  It is bad however if you want the user to be able to give input of his own outside of the select list.  

So all you really have to do if this option was enabled would be to always copy the search to the input as it is changed.  If an option is selected, then of course that gets copied into the input as the last thing that happens.

I do realize I could have the search field copied into my model with the md-selected-item-change option function, and in fact that is what I am doing to effect this.  However it is not immediately obvious that this is how you would do this, and as well it still seems like an easy thing to bake into the directive as an option so people don't have to do this for what seems like should be an option to the directive.

**Comment by dmackerman** [comment]
I think it would be possible to use the `md-not-found` directive here, and then implement some of your own logic. It's currently broken, but I'd like this type of functionality as well.

**Comment by gligoran** [comment]
**+1**

In my case I have a generate a list of descriptions previously used when creating my object, so you can reuse old descriptions quickly. However you must be able to input completely new descriptions as well. I tried using the same variable for search text and selected item, but in that case the list is not even shown.

For now, I'm working around this by checking if selected is null and assigning the search text.

**Comment by cah-ricksuggs** [comment]
+1

I'm using the exact same scenario as @gligoran and trying to implement it somehow with the `onBlur` event.

**Comment by donmccurdy** [comment]
@epelc could you show an example? That approach sounds like it would have unwanted side effects. For example, in the process of typing "Aardvark" I would unintentionally create autocomplete entries for: `A`, `Aa`, `Aar`, `Aard` ...

I think the ideal outcome would not necessarily be adding a new autocomplete entry, but simply treating the input as valid even when it doesn't match anything from the list. Whereas now, the input state is considered null if it doesn't match.

**Comment by epelc** [comment]
@donmccurdy you do not add extra entries you update the search value the autocomplete is bonded to manually in the change handler.

**Comment by donmccurdy** [comment]
Oh! In that case I can just do:

```html
<md-autocomplete md-search-text="foo" md-items="item in ['one', 'two', 'three']">
  <md-item-template>{{ item }}</md-item-template>
</md-autocomplete>
```

Binding `foo` with `md-search-text` rather than `md-selected-item`. That is easier than I'd thought, thanks.
