### ISSUE TITLE
md-select incorrectly handles element name

### ISSUE THREAD

**Issue by olegccc** [angular/material#3675]
For example, if I use the following logic:

    <md-select name="{{name}}">...

it fails here:

    if (attr.name && formCtrl) {
        var selectEl = element.parent()[0].querySelector('select[name=".' +  attr.name + '"]');
            formCtrl.$removeControl(angular.element(selectEl).controller());
    }

(selectEl will be null)

**Comment by rschmukler** [comment]
This was fixed in ed6b45c7f3b6c9cd48be8adb7ff76613f80ed368
