### ISSUE TITLE
transcluding directive within md-menu-item for iPhone 5; iPad 2; iPad Retina

### ISSUE THREAD

**Issue by mlom** [angular/material#3677]
md-switch labels are not properly transcluding when used inside of the md-menu-item for certain devices (testing on iOS Simulator). Devices where the label is not rendering include: iPhone 5; iPad 2; and iPad Retina. Confirmed on actual iPhone5 device. Please see code snippet and images below:

#code snippet:
```
<md-menu md-position-mode="target-right target">
          <md-button ng-click="$mdOpenMenu()" class="md-icon-button">
            <md-icon md-menu-origin>&#xE5D4;</md-icon>
          </md-button>
          <md-menu-content width="4">
            <md-menu-item>
              <md-switch class="Expand" ng-model="sliders.expand" aria-label="Expand">Expand<br/><span class="switch-sub-text">Acquire more agencies</span></md-switch>
            </md-menu-item>
            <md-menu-item>
              <md-switch class="Grow" ng-model="sliders.grow" aria-label="Grow">Grow<br/><span class="switch-sub-text">Make agencies better</span></md-switch>
            </md-menu-item>
            <md-menu-item>
              <md-switch class="Develop" ng-model="sliders.develop" aria-label="Develop">Develop<br/><span class="switch-sub-text">Help existing agencies</span></md-switch>
            </md-menu-item>
          </md-menu-content>
</md-menu>
```
#images:

image of labels working on iPhone6:
![screen shot 2015-07-09 at 6 58 21 pm](https://cloud.githubusercontent.com/assets/8382048/8625122/90426db6-26f1-11e5-962f-95a0839ed6e7.png)

image of labels not working on iPhone5:
![screen shot 2015-07-09 at 6 57 57 pm](https://cloud.githubusercontent.com/assets/8382048/8625123/90454e32-26f1-11e5-9094-495b0ec2769c.png)

**Comment by mlom** [comment]
a more general explanation of issue:

repeating multiple md-menu elements with only text within the md-menu-item results in no issues (ie. works as expected).
```
<md-menu>
  <md-button ng-click="$mdOpenMenu()">
    <md-icon md-menu-origin>&#xE5D4;</md-icon>
  </md-button>
  <md-menu-content>
    <md-menu-item>
        hello world
    </md-menu-item>
  </md-menu-content>
</md-menu>
```

However, if the md-menu-item content involves another directive that requires transclusion, such as md-button or md-switch, this directive's transclusion fails at some point.

```
<md-menu>
  <md-button ng-click="$mdOpenMenu()">
    <md-icon md-menu-origin>&#xE5D4;</md-icon>
  </md-button>
  <md-menu-content>
    <md-menu-item>
      <md-button>
        hello world
      </md-button>
    </md-menu-item>
  </md-menu-content>
</md-menu>
<md-menu>
```
If the above md-menu element (with a single md-menu-item and md-button) is repeated, the md-button's transclusion fails at some nth occurrence - when I tested the transclusion faild at the 10th occurrence.

If the number of md-menu-items (and thus md-button) elements increases, then the transclusion fails sooner. Testing with two (2) md-menu-items containing an md-button resulted in the transclusion failing at the 8th occurence.

This issue is still relevant to only those specified devices - not sure why.

**Comment by rschmukler** [comment]
@mlom apologies on the delay. I've [created this demo](http://codepen.io/rschmukler/pen/jbQodQ?editors=101) This appears to be resolved in iOS 9.1. Take a look and let me know!

**Comment by rschmukler** [comment]
Punting to RC6 to see if we can verify this still exists. If not, will close.

**Comment by jelbourn** [comment]
Closing this for now. Let us know if this is still an issue.
