### ISSUE TITLE
md-select placeholder text is a different color

### ISSUE THREAD

**Issue by calebegg** [angular/material#3678]
See the difference in color between 'City' and 'State' in the first demo here:

https://material.angularjs.org/latest/#/demo/material.components.select

![screenshot from 2015-07-10 15 37 06](https://cloud.githubusercontent.com/assets/782920/8627505/8d2f96f8-2719-11e5-9a59-854713158519.png)

**Comment by rschmukler** [comment]
This is fixed on master - see [here](https://material.angularjs.org/HEAD/#/demo/material.components.select)

**Comment by hastingsw** [comment]
How can I make the text color darker for SELECT to match all other text color ?  Thanks !
![textcolor](https://cloud.githubusercontent.com/assets/14204904/10320529/e2a455de-6c41-11e5-9955-46ca8d21c8d7.png)
