### ISSUE TITLE
(suggestion)(md-chips)make $index available with md-chip-remove

### ISSUE THREAD

**Issue by alanpurple** [angular/material#3679]
I need $index when I manipulate with chip remove.

Make $index in md-chip-remove won't cause any trouble, right? :)

**Comment by typotter** [comment]
hi alanpurple, could you please provide an example of where you would use this code? Can you use indexOf instead, similar to #3710?

**Comment by alanpurple** [comment]
@typotter  yeah that would work, even though that's just search and match. thanks

**Comment by typotter** [comment]
I had another look at the code, and exposing $index should not be too hard (it would be nice if we had a custom template option for ng-repeat, but that's not available in ng1, afaict).

Using indexOf is problematic in some cases where there are duplicate objects in the collection of chips, and adds a list-search operation needlessly reducing performance.
