### ISSUE TITLE
md-selected-item-change behavior

### ISSUE THREAD

**Issue by arjunAnand05** [angular/material#3680]
I'm trying $location.url(newUrl) in the function that handles md-selected-item-change.

However, this causes an error because the autocomplete.js - select(index) function is called AFTER the function bound to the md-selected-item-change directive.

The error thrown is attached. The specific line that throws an error is -
     elements.$.input.controller('ngModel').$setViewValue(getDisplayValue($scope.selectedItem) ||
          $scope.searchText);

![screenshot 2015-07-10 at 3 55 20 pm](https://cloud.githubusercontent.com/assets/8718464/8630555/1d9c0800-271c-11e5-9df7-4388e8e9a899.png)

**Comment by robertmesserle** [comment]
@arjunAnand05 Can you create a CodePen or Plunker demonstrating this?

**Comment by robertmesserle** [comment]
This should be resolved already in 0.10.1-rc1, closing for now.
