### ISSUE TITLE
Validate fields after a user has left field

### ISSUE THREAD

**Issue by mattdanna** [angular/material#3681]
When a user enters a field like e-mail or phone, they will always get an error thrown until they've completed typing out their full e-mail, which is not an optimal user experience.

Input fields should wait till `ngBlur` before triggering error state.

**Comment by gkalpak** [comment]
When using an `mdInputContainer` you can specify when the error appears via the `md-is-error` attributes ([docs][1]). By default, it shows the errors only when the field has been `$touched`, i.e. blurred once.

If you see a different behaviour, please provide a demo (e.g. using CodePen etc).

[1]: https://material.angularjs.org/latest/#/api/material.components.input/directive/mdInputContainer
