### ISSUE TITLE
md-button  with ng-switch-default will cause an error

### ISSUE THREAD

**Issue by luxp** [angular/material#3682]
Error: [$compile:multidir] Multiple directives [ngSwitchDefault, mdButton (module: material.components.button)] asking for transclusion on: <md-button ng-switch-default="">
http://errors.angularjs.org/1.4.2/$compile/multidir?p0=ngSwitchDefault&p1=&…ts.button)&p4=transclusion&p5=%3Cmd-button%20ng-switch-default%3D%22%22%3E

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.
