### ISSUE TITLE
md-sidenav not working with md-include

### ISSUE THREAD

**Issue by shakhrillo** [angular/material#3684]
I'm trying to add the md-include inside of md-sidenav
![capture_2](https://cloud.githubusercontent.com/assets/3455633/8633663/d81838a0-27dc-11e5-9139-a142d76bf708.PNG)
But it giving me any error just commenting it out and not displaying it
![capture](https://cloud.githubusercontent.com/assets/3455633/8633665/ef5ec42a-27dc-11e5-8caf-11e160e18e56.PNG)
Why it is happening or md-include not supported in md-sidenav?

**Comment by norkunas** [comment]
https://docs.angularjs.org/api/ng/directive/ngInclude

> If the source is a string constant, make sure you wrap it in single quotes, e.g. src="'myPartialTemplate.html'".

**Comment by shakhrillo** [comment]
I found my mistake if I add the url as a $scope.module it worked
