### ISSUE TITLE
md-select error ng-change

### ISSUE THREAD

**Issue by z3v0k0d3** [angular/material#3685]
Error ng-change: TypeError: Cannot read property 'deferred' of undefined

Angular 1.4.2, material 0.10.0 [OK]
http://codepen.io/Z3V0K0D3/pen/YXLJRY

Angular 1.4.2, material 0.10.1-rc1 [ERROR]
http://codepen.io/Z3V0K0D3/pen/WvJaYW

![1](https://cloud.githubusercontent.com/assets/7059212/8633950/e675f58a-27ba-11e5-87bd-b6a62d3b7214.PNG)

**Comment by rschmukler** [comment]
This is fixed in master!
