### ISSUE TITLE
Layout and Flex Issues in Demos > Button

### ISSUE THREAD

**Issue by loljoho** [angular/material#3687]
I do not believe this issue has been reported, but I may simply be using the wrong queries.

The demo for `md-button` reacts strangely at a number of flex viewport widths.  I initially stumbled upon this when the DevTools panel was on the right, but that makes no difference:

![docs-buttons](https://cloud.githubusercontent.com/assets/8849837/8634769/158a51e0-27d4-11e5-8946-f0ab46c39bd5.png)

Actually. as I write this I am beginning to realise that throughout the entirety of this project's development, I have noticed a pattern in which even the simplest implementations of `layout` and `flex` attributes will cause unpredictable behaviour in other components--from my personal observations I believe this to be the cause of decimals in viewport adjustment, i.e. flexing to a non-integer.

This issue is easily recreated with `flex` values of 33 or 66 on main page elements, and moreso when collapsible `md-sidenav` is involved.  I clearly recall encountering problems of a similar nature with other components (can't recall which ones at the moment) affecting more than just sizes and dimensions.

Also, I'd like to apologise for my significantly impaired insomnia-induced cognition and I hope that this issue makes sense and is an actual issue to report.

Perhaps the use of integer casting and/or some sort of modulus implementation would help resolve flexbox issues?

Again, I apologise for writing what I now am believing to be an unnecessary issue, but I would be glad to help out in any way (after a good night's rest of course).

**Comment by ThomasBurleson** [comment]
The `<section>` containers need a `layout-wrap` attribute.
