### ISSUE TITLE
md-progress-linear: buffer mode doesn't work with md-primary color

### ISSUE THREAD

**Issue by florent1933** [angular/material#3690]
It doesn't work on firefox, chrome and safari.

![md-p-l](https://cloud.githubusercontent.com/assets/3958123/8638412/ff4a29a4-28ba-11e5-90d1-8df09f8a5601.jpg)

```
<md-progress-linear class="md-warn" md-mode="buffer" value="20" md-buffer-value="50">
  </md-progress-linear>
  
  <md-progress-linear class="md-primary" md-mode="buffer" value="20" md-buffer-value="50">
  </md-progress-linear>
```

See the codepen:
http://codepen.io/anon/pen/qdYwgB

Use of: 
- angular.js 1.3.15
- angular-material v0.10.0

**Comment by 4z8397qju3k7** [comment]
+1

**Comment by BigEgg** [comment]
+1

**Comment by hsstan** [comment]
+1

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (414/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:6755)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZY-001Z48-7y
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:06 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=h3OEyOrX+PQTTYxj0KJeZx2WtmQ=; b=wGzBWawSEkfKXNyS
	+1eDIuVWmbdBnutiGHf6RLm0An6/zM4uskGzgA4c8AYqTQUsfagN75zlOf/hV91c
	neFrF24/AXo38HaQkHqKNTeeQE+5hNhLKEBEpkmGwf1H2a2jqWLuVDt17xz4pI17
	jUqrdZoWyFPdmIu0PsXleOtJeIk=
Received: by filter0529p1mdw1.sendgrid.net with SMTP id filter0529p1mdw1.18815.5722729F7A
        2016-04-28 20:29:19.806104976 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id GTdKyMupTbqNwJGqaKZP2w
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:19.748 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:19 -0700

**Comment by jonahbron** [comment]
I'm not sure why this issue was closed, it's still a problem.

http://codepen.io/anon/pen/MbrVrR

Angular Material version 1.1.1, Codepen forked from the demo in the official documentation.
