### ISSUE TITLE
new feature(md-morph): Proposal to refactor FabSpeedDial & FabToolbar

### ISSUE THREAD

**Issue by topherfangio** [angular/material#3694]
After seeing some of the updates to the [Material Spec for FABs](http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions), I think a major refactoring of the FabSpeedDial and FabToolbar is in order if we want to be able to truly support what has been designed.

While we finish the first implementation of the SD & Toolbar, I would like to start a discussion on a potential refactoring to a new component called `md-morph` which I think may make things drastically easier moving forward (as I was looking through the new specs, every animation was a morph from the fab into something else).

Below is some example code that we can discuss/modify and some notes about potential usage/options:

1. I'm showing some options listed out that could certainly be turned into defaults:
    * `md-animate` would probably default to morph
    * `md-morph-position` would probably default to `center center`
    * Ideally, the speed dial would be smart enough that if it was used inside of a morph, you wouldn't need to tie the `md-is-active` property together
    * etc.
1. The speed dial overrides the default morph animation so that it can provide a custom one
1. `md-morph-position` helps tell the morph where the final resting place of the FAB is after the morph into the content
1. All of this is open for change/thoughts; just wanted a starting point and to get my thoughts out of my head :-)

```xml
<!-- Generic Usage //-->
<md-morph md-animate="morph">
  <!-- Use a standard button, md-morph will auto-activate on click //-->
  <md-button class="md-fab">Trigger</md-button>

  <md-morph-content>
    <md-content>
       A bunch of code/elements here...
    </md-content>
  </md-morph-content>
</md-morph>

<!-- Toolbar Usage //-->
<md-morph>
  <!-- Use something custom, tell md-morph when to activate //-->
  <md-autocomplete md-morph-activate="focus">Trigger</md-autocomplete>

  <md-morph-content>
    <md-toolbar md-morph-position="end center">
      <md-button>Action 1</md-button>
      <md-button>Action 2</md-button>
      <md-button>Action 3</md-button>
    </md-toolbar>
  </md-morph-content>
</md-morph>

<!-- Speed Dial Usage //-->
<md-morph md-is-active="demo.isActive" md-animate="none">
  <!-- Use a standard button, md-morph will auto-activate on click //-->
  <md-button class="md-fab">Trigger</md-button>

  <md-morph-content>
    <md-speed-dial md-morph-activate="hover" md-animate="fling" md-is-active="demo.isActive">
      <md-button>Action 1</md-button>
      <md-button>Action 2</md-button>
      <md-button>Action 3</md-button>
    </md-speed-dial>
  </md-morph-content>
</md-morph>
```

This could even potentially allow for other types of morphs like the following:

```xml
<md-button class="md-fab">
    <md-morph md-animate="scale fade rotate90">
        <md-icon path="plus.svg" />
        <md-morph-content>
            <md-icon path="minus.svg" />
        </md-morph-content>
    </md-morph>
</md-button>
```

Again, would love feedback/thoughts on if this is the right approach.

**Comment by topherfangio** [comment]
Another side-benefit, we could move all of this code into a single directory called `md-morph` instead of the 4 we have right now (and I may be about to add a fifth...):

 * fabAction
 * fabSpeedDial
 * fabToolbar
 * fabTrigger

**Comment by ThomasBurleson** [comment]
@topherfangio - we already have [post v1.0] plans to allow icons to morph between states. Also ngAnimate is working on states, animations, and timelines. These are advanced features that will be integrated into Angular Material upon ngAnimation release.

**Comment by topherfangio** [comment]
Okay, awesome. I will take a look at the work being done and rethink this a bit. Thanks!

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (432/400 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:38708)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZn-001Z7d-T1
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:22 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=KJURUKKK57NKncaShterxJf0oms=; b=IyVx8gDp+XrAe84f
	8RrfrhMaqPwizUgCOnLCMQZ/TkQglYC3NeM9PnjKgimDbKaxOIIdzoIlDgqAZZaU
	0P7K+N/BFF5MbDJTgzgka+SG7eqQwaeiU+o8HnsJf01xxqXVa/CLKAIMlSs6Q1TR
	qW6bDCd///RPzpaTQaZUMTew52U=
Received: by filter0461p1mdw1.sendgrid.net with SMTP id filter0461p1mdw1.29129.572272AF11
        2016-04-28 20:29:35.266375091 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id IARfHeZ4Rwm59vlMKJ8w6w
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:35.320 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:35 -0700
