### ISSUE TITLE
Select and input error in Firefox

### ISSUE THREAD

**Issue by salem-chinsu** [angular/material#3695]
Hi.

Please see 2 links bellow in firefox: 
- https://material.angularjs.org/latest/#/demo/material.components.select
- https://material.angularjs.org/latest/#/demo/material.components.input

Link 1 : Open the select box, if not choose the value, can't close it

Link 2 : The input "Address 2" is not display the placeholder if not focus

Please fix them asap.

Thanks :)

**Comment by topherfangio** [comment]
@salem-chinsu I can't seem to reproduce either of these in Firefox 40.0.2.

If this is still valid, can you please let me know what version of FF you are using?

**Comment by salem-chinsu** [comment]
@topherfangio i updated my firefox to the latest version and now it's working fine :)

Thank you :+1:

**Comment by topherfangio** [comment]
Awesome! Glad it's fixed :-)
