### ISSUE TITLE
transclude error on ng-switch

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3698]
I'm trying to use ng-switch directive with one of the 'when' being a checkbox, when doing so I get the following error...

```
Error: [$compile:multidir] Multiple directives [ngSwitchWhen, mdCheckbox (module: material.components.checkbox)] asking for transclusion on: <md-checkbox ng-switch-when="checkBox"  aria-label="Toggle {{task.longName}}">
```

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
