### ISSUE TITLE
Using md-chip-remove in md-chip-template does not override the 'x'

### ISSUE THREAD

**Issue by robinsving** [angular/material#3702]
Expected result: 
Upon adding md-chip-remove on an item in the md-chip-template it should override the default 'x'.

[Plunker available here](http://codepen.io/anon/pen/Kpeweo)
Simple adjustment of the plunker available on the [DEMO page](https://material.angularjs.org/latest/#/demo/material.components.chips)

Edit: Found after looking a bit further that the md-chip-remove should be placed *outside* of the md-chip-template

Suggestion it to clarify this a bit in the documentation, and change the log.warning in https://github.com/angular/material/blob/release/0.10.0/src/components/chips/js/chipsDirective.js#L214 to say 
<code>
if (userTemplate[0].querySelector('md-chip-template *[md-chip-remove]')) 
</code>
I.e. remove the direct child ('>') to give a warning if you place the button anywhere inside <md-chip-template>

**Comment by rkotenko** [comment]
To expand on this, the template actually cannot be overriding even if is outside the template.  Consider:

    <md-chips ng=model="test">
        <md-chip-remove><button>test</button></md-chip-remove>
        <md-chip-template>{{$chip.name}}</md-chip-template>
    </md-chips>

Now, in angular-material:

    var chipRemoveTemplate   = getTemplateByQuery('md-chips>*[md-chip-remove]') || CHIP_REMOVE_TEMPLATE...
     
    function getTemplateByQuery (query) {
        if (!attr.ngModel) return;
        var element = userTemplate[0].querySelector(query);
    return element && element.outerHTML;
 }

In getTemplateByQuery, userTemplate is md-chips as that is what set in the template.  So the selector is trying to find md-chips>md-chip-remove INSIDE of md-chips.  If the selector is changed to just be md-chip-remove, it should find it fine.

You can see an example here: http://codepen.io/rkotenko/pen/Ejrmbv
