### ISSUE TITLE
md-tabs: setting class on nested tabs

### ISSUE THREAD

**Issue by MigFerreira** [angular/material#3703]
Classes on nested md-tabs are overwritten.

http://codepen.io/MigFerreira/pen/KpewBo

As you can see higher level tabs have class md-accent and nested has md-primary. Last one is overwritten.

**Comment by ThomasBurleson** [comment]
@robertmesserle - do we support **nested tabs**?

**Comment by naomiblack** [comment]
This is explicitly not supported in Material Design as a pattern that should be approached differently in the user interface. Apologies, out of scope to Angular Material.
