### ISSUE TITLE
md-select doesn't line up with adjacent md-input-container

### ISSUE THREAD

**Issue by calebegg** [angular/material#3705]
See screenshot, taken of https://material.angularjs.org/HEAD/#/demo/material.components.select

![screen shot 2015-07-13 at 9 14 55 am](https://cloud.githubusercontent.com/assets/782920/8650346/16b2bffe-2940-11e5-933b-5a96ceb07cb5.png)

**Comment by calebegg** [comment]
Ah, I just realized/forgot to mention: this is only in Safari.

**Comment by rschmukler** [comment]
Fixed on HEAD
