### ISSUE TITLE
Menu: Remove focus on first element

### ISSUE THREAD

**Issue by Masadow** [angular/material#3707]
Hi,

I'm setting a dropdown menu from my header using the new menu component. However, every time I open the menu, the first element is focused which is really confusing for my users who think they have selected it.

**Comment by marcysutton** [comment]
I'm guessing that is because the list of options is in a separate area of the DOM than the triggering element, so focus has to be sent to it for accessibility. Internally in the component, focus could be sent to an element wrapping the options instead (using `tabindex="-1"`).

**Comment by george3447** [comment]
+1

**Comment by maelfrize** [comment]
:+1:

**Comment by Masadow** [comment]
This might be a duplicate of #3352
