### ISSUE TITLE
$index in md-chip-template is not accessible

### ISSUE THREAD

**Issue by suryaiiit** [angular/material#3710]
As given at the link: https://material.angularjs.org/latest/#/api/material.components.chips/directive/mdChips $index is not accessible, please refer to the below link for an example:
http://codepen.io/anon/pen/gpKree

**Comment by typotter** [comment]
Can you use indexOf in place of injecting this value in the template: ex: http://codepen.io/anon/pen/rVRzbN?

**Comment by ThomasBurleson** [comment]
`indexOf` workaround available for now.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (407/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:15053)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZN-001Z1h-0r
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:54 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=zHmFaYbj+zOb9bGyc63/Glao2zs=; b=Fg9VqLQE8qwYKHuS
	/VBBKOyPVk7iYWkxg4/0Lq3LhayBlIJBu+1dF9+M+cT8GD1baMrQ8BWuOlxu03b4
	JERybRQPrubVEExiJRJ6rpAoc+HBf3rgH7Djkwf4Qmea4XX713Uq/K8NHeV3NanL
	6akoGZwo8ZJ4E5NK1GX1rcjWHyg=
Received: by filter0797p1mdw1.sendgrid.net with SMTP id filter0797p1mdw1.23209.572272948
        2016-04-28 20:29:08.158281494 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id Uf9SA3T1TBCY8BXqjsK7zw
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:08.207 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:08 -0700
