### ISSUE TITLE
Add support for file picker

### ISSUE THREAD

**Issue by kskoropada** [angular/material#3713]
It will be nice to have support for input of type file. Any ETA for this?

**Comment by gustavohenke** [comment]
I don't think this is in the specs.

Anyway, I did this previously by using a `<label class="md-button">` wrapping the input.

**Comment by no-more** [comment]
+1

It would be great

**Comment by naomiblack** [comment]
We're unlikely to add this before 1.0, but I agree, it would be nice to have. We'd need more guidance from our UX folks.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
