### ISSUE TITLE
menu: Document how to close the menu after a state change

### ISSUE THREAD

**Issue by epelc** [angular/material#3714]
If you use `ui-sref` inside of `md-menu` the scrollbar remains locked when you change states. `md-menu` should either handle this seamlessly or should document `$mdMenu.hide()`. 

There was a similar issue for dialogs a while ago and we came to the conclusion it's up to the app to handle closing the dialog from state changes. But the menu `hide()` function isn't documented so most people would miss this.

The following works with ui-router but there's usaully similar state/view change events for other routers.
```
// Make sure you inject $mdMenu before you use this.
$rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
    $mdMenu.hide()
})
```

**Comment by epelc** [comment]
`$mdMenu.hide()` doesn't seem to work in the state change start or success event.

@rschmukler Do you know if we need to do something else to close menu's(or just unlock the scrolling) after a state change?

**Comment by luclanet** [comment]
Sometimes a div with a class called "click-catcher" will stay forever even if menu page was changed.

**Comment by stefan-schweiger** [comment]
+1 also seems to happen sometimes when a ng-click triggers some DOM manipulation. #3741

**Comment by ThomasBurleson** [comment]
@epelc - can you provide a small demo so we can debug and fix?

**Comment by epelc** [comment]
@ThomasBurleson I think d31ffd9 fixed this as it's working fine in the latest master even without calling `$mdMenu.hide()` in the state change event.

**Comment by ThomasBurleson** [comment]
@epelc :+1:

**Comment by tamer1an** [comment]
I find that when md-menu is placed inside the md-dialog 

when we in opened dialog and open menu that is inside dialog and then press Escape 

some times it close dialog and the menu but page stays blocked 

example:
(pressing Escape will block the web-page)
`md-menu
    md-button.md-raised.md-hue-2(aria-label='Open demo menu' ng-click='$mdOpenMenu($event)') Time of day
    md-menu-content(width='1').md-padding
        md-menu-item FORM:
            md-input-container
                input(aria-label='input destination', ng-model='new', type='number', min=0)
        md-menu-item TO:
            md-input-container
                input(aria-label='input destination', ng-model='new', type='number', min=0)`

(escape is working correctly)
`md-menu
    md-button.md-raised.md-hue-2(aria-label='Open demo menu' ng-click='$mdOpenMenu($event)') Time of day
    md-menu-content(width='1').md-padding
        md-menu-item FORM:
            md-input-container**(ng-click='test()') //not-existing test function helps** 
                input(aria-label='input destination', ng-model='new', type='number', min=0)
        md-menu-item TO:
            md-input-container
                input(aria-label='input destination', ng-model='new', type='number', min=0)`


ver is: Angular Material Design v1.0.1
