### ISSUE TITLE
md-backdrop class "md-click-catcher" freezes md-dialog (MASTER)

### ISSUE THREAD

**Issue by kschwidder** [angular/material#3715]
In some cases the md-dialog can not be closed anymore after it is shown.
The standard confirm dialog seems to be ok. If showing a customized one from a menu it can hang the whole screen.

Have been reproduced also with the demo. However I have not recorded the sequence.

**Comment by kschwidder** [comment]
I have figured out that the md-click-catcher of the md-backdrop hangs the interaction. if I remove it from the browser the dialog runs again. 

Please provide a fix for this soon.

**Comment by ThomasBurleson** [comment]
@kschwidder - the `md-click-catcher` class is used within the menu display processes. The issue is the dialog either originates from the menu trigger button OR display in screen center. This is a known bug that has been fixed (commit pending).

**Comment by kschwidder** [comment]
@ThomasBurleson Thx for your prompt comment ! This port is awesome and thx to all contributors as well for fixing issues which is not an easy task. I am looking forward for R 1.0 soon :-)

**Comment by kschwidder** [comment]
@ThomasBurleson Is your fix already available in the master ? I have downloaded the latest version and I still got the catch ...
Kind regards
Kai

**Comment by ThomasBurleson** [comment]
@kschwidder - yes, the changes are in mater. Can you provide a Demo so I can debug your specific issue?

**Comment by kschwidder** [comment]
can not reproduce it right now. I close it and will inform you later if I get the same behaviour.
