### ISSUE TITLE
md-menu doesn't when out of focus on firefox

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#3716]
Hey, i have a problem about trying to close the menu, there should be a rule to close this menu when user clicks out of the menu, or atleast some directive to make it close instead of being forced to click an item just to close

**Comment by Bodom78** [comment]
Yes, I had this issue while evaluating the demos. Switching to 0.10.1-rc1 demos clicking outside a menu seems to dismiss it now.

**Comment by Nosthertus** [comment]
@Bodom78 yes, i have checked that, i rather wait until developers finish that branch so i can make sure i would have less possibilities to get a bug on somewhere
