### ISSUE TITLE
Event closing "Bottom Sheet"

### ISSUE THREAD

**Issue by lcpereira** [angular/material#3717]
Hi,

I would like to know how I can control when the Bottom Sheet is closed, and the ESC key or with the mouse by dragging down.

Thanks.

**Comment by dhalturin** [comment]
Working example for use:
                    $mdBottomSheet
                        .show({
                            templateUrl: '_TEMPLATE_FILE_',
                            onRemove: function (scope, element, options) {
                                var scrollmask = document.getElementsByClassName('md-scroll-mask');
                                var backdrop = document.getElementsByTagName('md-backdrop');
                                angular.element(scrollmask).remove();
                                angular.element(backdrop).remove();
                                angular.element(element).remove();
                                $mdUtil.enableScrolling();
                            }
                        });

**Comment by lcpereira** [comment]
:+1:
