### ISSUE TITLE
Text field input validation and errors support needed

### ISSUE THREAD

**Issue by miguelchico** [angular/material#372]
Hi,

First of all, excelent library.

I have a question about form validation.

How could I add an input text styles when validation fails ?

**Comment by demisx** [comment]
+1

**Comment by ziaukhan** [comment]
+1

**Comment by ajoslin** [comment]
Not actually done yet, we don't support the error styles seen in the spec.

**Comment by dasmith** [comment]
With the new `md-input-container` format introduced in `v0.7.0-rc2`, the following class will put a red line under invalid inputs:

```
input.md-input.ng-invalid.ng-dirty {
  outline: none;
  border-bottom:2px solid #DC4A3D;
  width:100%;
}
```
But to fully realize [Google's input error spec](http://www.google.com/design/spec/components/text-fields.html#text-fields-full-width-text-field), another error label must appear below the text input with an error message.

**Comment by EladBezalel** [comment]
@dasmith The error below can be easily appear when the model of the input has error and can be accessed via ```$error``` and with the right classes or maybe a directive it can be beautiful and elegant code :smile:

**Comment by ajoslin** [comment]
I'm writing this now.  If you include the ngMessages module in angular 1.3, it will all be handled and look good for you. https://docs.angularjs.org/api/ngMessages

```html
<form name="userForm">
  <md-input-container flex>
    <label>First Name</label>
    <input ng-model="user.firstName" name="firstName" minlength="5" required>
    <div ng-messages="userForm.firstName.$error" ng-if="userForm.firstName.$dirty">
      <div ng-message="required">That's required!</div>
      <div ng-message="minlength">Too short...</div>
    </div>
  </md-input-container>
</form>
```

Video: http://ajoslin.co/1437s

**Comment by EladBezalel** [comment]
@ajoslin This is awesome!

**Comment by tarex** [comment]
@ajoslin awesome , just tried , its working really great but the in my end the css of the error message is not as like your video , is possible to share the code ?

**Comment by demisx** [comment]
@ajoslin Awesome! Please share CSS for the video as well.

**Comment by PaulMougel** [comment]
Looks awesome :+1: Congrats for the great job.

**Comment by ajoslin** [comment]
There's still some polish and documentation left to do before its ready to
commit. It'll be up within the next few days.

**Comment by demisx** [comment]
@ajoslin I will name my next son Andrew.

**Comment by EladBezalel** [comment]
@ajoslin waiting for it! @desmisx lol :smile:

**Comment by ajoslin** [comment]
Lol @demisx, I'm honored!

More teasers...

![image](https://cloud.githubusercontent.com/assets/1265995/5672452/a0e13884-974d-11e4-8071-bea20e2fda43.png)

![screen shot 2015-01-08 at 3 51 36 pm](https://cloud.githubusercontent.com/assets/1265995/5672526/495417d4-974e-11e4-815b-4ee3a905ea25.png)

**Comment by demisx** [comment]
Sweet and exciting. :+1:

**Comment by dongmingliy** [comment]
Awesome!

**Comment by demisx** [comment]
@ajoslin If I want to make `<label>`s appear differently for the required fields, do I need to do it the old CSS way, i.e. 

```html
<label class="required">Some required label</label>
```
or is there a better material way?

**Comment by ajoslin** [comment]
There's no way at the moment, and nothing in the spec.

If you come up with some great CSS I'd love to see it though, and maybe we'll implement it.

**Comment by ajoslin** [comment]
Also, landed in master.

**Comment by trufrgs** [comment]
Hi, there is a way to avoid the need to write the same validation message dozen of times for different inputs? I mean, is possible to create default messages that are used for all the required fields, for example, with no need to write the same ng-message for every single one?

Anyway the current input validation is great, just asking if its possible to improve it :).

**Comment by Frank3K** [comment]
@trufrgs: see this [yearofmoo post](http://www.yearofmoo.com/2014/05/how-to-use-ngmessages-in-angularjs.html#reusing-and-overriding-error-messages).

**Comment by trufrgs** [comment]
Thanks a lot @Frank3K

**Comment by ThomasBurleson** [comment]
@matsko writes excellent code **and** blog tutorials. [Using ng-Messages](http://www.yearofmoo.com/2014/05/how-to-use-ngmessages-in-angularjs.html#reusing-and-overriding-error-messages) is a great resource.

**Comment by PascalPrecht** [comment]
@ThomasBurleson <3

**Comment by breandr** [comment]
So awesome. Can't wait :D

**Comment by demisx** [comment]
+1 for @pascalprecht blogs. One of the best written angular resources.
