### ISSUE TITLE
ngTouch in angular-material project

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/material#3720]
This project already removes 300ms on touch devices? I added the ngTouch module and had some problems with touch in some elements, I wonder if I have to add some module that removes or material itself already implements it, thank you.

about 300ms: 

http://blog.ionic.io/hybrid-apps-and-the-curse-of-the-300ms-delay/

**Comment by barryvdh** [comment]
ng-touch should probably work.
But on my Android, disabling the ripple effect makes the buttons a lot faster. Otherwise they seem to be loading longer.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
