### ISSUE TITLE
md-sidenav transition not good as polymer paper-drawer panel

### ISSUE THREAD

**Issue by kiranps** [angular/material#3721]
i loaded both side nav in google chrome in mobile. the css transition of the md-sidenav has less perfomance than that of polymer

https://material.angularjs.org/latest/#/demo/material.components.sidenav

https://elements.polymer-project.org/elements/paper-drawer-panel?view=demo:demo/index.html&active=paper-drawer-panel

**Comment by nabiltntn** [comment]
I had the same issue, i tried it for a mobile app with cordova on Nexus 5 and and it's pretty slow

**Comment by ThomasBurleson** [comment]
@kiranps @nabiltntn  - To clarify:

*  are you saying the delay between triggering [to show the SideNav] and the animation start [of the SideNav] is slow?
*  are you saying the actual animation is slow ?
*  are you saying the actual performance of the animation thrashing the CPU?

**Comment by nabiltntn** [comment]
Yeah it's basically about the delay to display the SIdeNav

**Comment by ThomasBurleson** [comment]
@nabiltntn - ok, that is an easy enough fix.

**Comment by roidayan** [comment]
hi, I'm also having a performance problem with cordova and nexus5. clicking the sidebar icon shows the sidebar but the animation to gray out the outer view is slow.
same when clicking the gray area to close the sidebar. the sidebar closes while the entire view is still grayed out and takes a second or two to animate out.

**Comment by perminder-klair** [comment]
Hello,
Actually same issue here, with cordova and nexus5, nexus6, oneplus one. Slide navigation is slow and laggy.
Any solution?

**Comment by roidayan** [comment]
also very noticeable with lg g4.  checked also without cordova just using chrome to go to the docs. sidenav is very slow.
I disabled the backdrop animation and using fastclick.

```css
.md-sidenav-backdrop,
.md-sidenav-backdrop.md-opaque.ng-leave {
  opacity: 1 !important;
  transition: none !important;
}
```

**Comment by perminder-klair** [comment]
@roidayan many thanks! fastclick really fixed the issue!

**Comment by EladBezalel** [comment]
@all can you please check if it's still happening on HEAD?

I tested this on my LG G3 and our sidenav worked better!
http://codepen.io/EladBezalel/pen/avweab - removed the 200ms wait

**Comment by roidayan** [comment]
I checked it also last week. I think since 0.11 it works much better. Anyway I don't use the css workaround I posted anymore.
