### ISSUE TITLE
Allow the use of $mdBottomSheet within an $mdDialog

### ISSUE THREAD

**Issue by pietschy** [angular/material#3722]
I'm opening this issue as I couldn't find one specifically for this case except for the now closed #397 and I wanted to make sure it was captured as part of the discussion for #698.

Ideally I like to specify the dialog as the parent element of the bottom sheet however the call to `$mdBottomSheet.show(..)` hides the current dialog and the bottom sheet attaches to the document root.

**Comment by chaitanya-searce** [comment]
Try to use the parent property of bottom sheet.
https://material.angularjs.org/latest/#/api/material.components.bottomSheet/service/$mdBottomSheet

$scope.alert = '';
$mdBottomSheet.show({
templateUrl: 'urlOfBottomSheetTemplate',
parent:angular.element('#abc')
});

#abc should be given as the id of the Dialog Box template

**Comment by pietschy** [comment]
Hi @chaitanya-searce, 

I did try that, the problem is that the interim element service cancels any existing dialog during the show method (at about line 1979 in angular-material.js).

```
function show(options) {
        if (stack.length) {
          // *** This closes my dialog
          return service.cancel().then(function() {
            return show(options);
          });
        } else {
          var interimElement = new InterimElement(options);
          stack.push(interimElement);
          return interimElement.show().then(function() {
            return interimElement.deferred.promise;
          });
        }
      }
```
So by the time the bottom sheet is opened, the parent dialog has been cancelled.

Cheers

**Comment by DmitryEfimenko** [comment]
+1

**Comment by JobaDiniz** [comment]
+1

**Comment by ruisebastiao** [comment]
+1

**Comment by morwin10** [comment]
+1
