### ISSUE TITLE
md-chip standalone

### ISSUE THREAD

**Issue by AdriVanHoudt** [angular/material#3723]
Normally the `md-chips` component is very useful and the thing you need but we have a special case where we want to build the `md-chip's` ourselves. The problem is that the individual chip is not styled. All the css is aplied under `md-chips` as you can see (here)[https://github.com/angular/material/blob/master/src/components/chips/chips.scss#L51].
It would be very handy (and not a lot of work I think) to not put the css unde `md-chips` so we can use the `md-chip` component ourselves.

**Comment by shakhrillo** [comment]
Just add every md-chips single style

**Comment by AdriVanHoudt** [comment]
right now I am doing a `md-chip` with `ng-repeat` on it, with the custom stuff. And I have to copy the style from `md-chips` otherwise there is no styling at all

**Comment by bitoverflow** [comment]
+1

**Comment by naomiblack** [comment]
This looks interesting but unfortunately, we will not be able to add as a feature before beta. (PRs always welcome...)

**Comment by AdriVanHoudt** [comment]
Would this include more then putting the CSS under md-chip directly instead of md-chips.md-chip¿

**Comment by cydney-caa** [comment]
Not sure if this is a viable solution - but in terms of styling each chip individually inside an ng-repeat the way might be to apply a class to md-chip on a chip by chip basis.

So adding a new expression inside ng-class inside the MD_CHIPS_TEMPLATE variable.

    <md-chip 
	    ng-repeat="$chip in $mdChipsCtrl.items"\
        index="{{$index}}"\
        ng-class="{
	        \'md-focused\': $mdChipsCtrl.selectedChip == $index,
	        \'md-readonly\': $mdChipsCtrl.readonly, 
	        \'{{$chip.class}}\': $chip.class}"
	 > 


Expression:  `\'{{$chip.class}}\': $chip.class`
By adding this if a chip object has the key class then it will apply the value as a class to md-chip. So you could end up with the below image.

Utilizing the ng-class was the first answer that came to mind.  Feedback welcome. Or if this seems like a reasonable solution, I'd be happy to pull request the change.


![screenshot-material angularjs org 2015-09-14 10-58-30](https://cloud.githubusercontent.com/assets/8962970/9857469/940087be-5acf-11e5-8794-9de6aff3d563.png)

**Comment by rkalita** [comment]
I may prefer to use custom directive, which add special class to your chip

`.directive('myChip', function(){
    return {
        restrict: 'EA',
        link: function(scope, elem, attrs) {
            var myChip = elem.parent().parent();
            myChip.addClass(scope.$chip.class);
        }
    }
})`

`<md-chip-template my-chip>`

**Comment by ilovett** [comment]
I agree the md-chip styles should not be contained underneath `.md-chips` only ...

My use case is showing md-chip as filters.  Right now I have a table with a filter object and works very well with the out of box `filter` directive

The problem is that `md-chips` expects an array for `ng-model`, but my filter object is an object with properties and doesn't translate.

I also may want my chips be inline instead of a block, as well as eliminate the input field.
