### ISSUE TITLE
md-icon-float causes too much spaces in a row layout

### ISSUE THREAD

**Issue by dinu88** [angular/material#3725]
![selection_016](https://cloud.githubusercontent.com/assets/731068/8674500/33a64440-2a36-11e5-82ae-97792a9e7c85.png)

caused by:
md-input-container.md-icon-float.md-input-focused, md-input-container.md-icon-float.md-input-has-value {
  margin-top: -8px;
}

-8 px is fine for column layout not for rows.

**Comment by caok2709** [comment]
Yeah. Same here....is there a way to shut it down?
