### ISSUE TITLE
$watch on selectedIndex does not fire, if inside ng-if

### ISSUE THREAD

**Issue by Stexxen** [angular/material#3726]
Simple Controller
```
    angular.module('testApp').controller('TestCtrl', function ($scope) {
        $scope.$watch('selectedIndex', function () {
            console.log("change!");
        });
    });
```

html
```
<md-content ng-if="true">
    <md-tabs md-selected="selectedIndex">
        <md-tab>
            Tab1
        </md-tab>
        <md-tab>
            Tab2
        </md-tab>
    </md-tabs>
</md-content>
```

The $watch does **not** fire when ```ng-if``` is present. Remove it and the $watch fires as expected.

```ng-show``` does not have the same problem, so something specific with ng-if?

**Comment by gkalpak** [comment]
This is not `ngMaterial` specific, but rather related to Angular core.

Basically, `ngIf` creates an new scope, so `selectedIndex` is set on that new scope, while the watch is registered on its parent scope (where there is no `selectedIndex`, thus no change is detected).

Actually, the root of the observed behaviour lies on how JavaScript's prototypal inheritance works - the [Understanding Scopes][1] section of the Angular wiki is a must-read :)

--
As will be clear after reading the aforementioned section, you should either use `controllerAs` or set the `selectedIndex` on an object (both approaches have the exact same effect).

E.g.:

Approach 1 (preferred nowadays):

```js
angular.
  module('testApp').
  controller('TabsCtrl', function TabsCtrl($scope) {
    var self = this;
    $scope.$watch(
      function watch() { return self.selectedIndex; },
      function watchAction() {...}
    );
  });
```

```html
<div ng-controller="TabsCtrl as tabs">
  <md-content ng-if="true">
    <md-tabs md-selected="tabs.selectedIndex">
      ...
```

Approach 2:

```js
angular.
  module('testApp').
  controller('TabsCtrl', function TabsCtrl($scope) {
    $scope.tabs = {};
    $scope.$watch('tabs.selectedIndex', function watchAction() {...});
  });
```

```html
<div ng-controller="TabsCtrl">
  <md-content ng-if="true">
    <md-tabs md-selected="tabs.selectedIndex">
      ...
```
[1]: https://github.com/angular/angular.js/wiki/Understanding-Scopes

**Comment by Stexxen** [comment]
Thanks. You explained it well, and I now understand why ng-show doesn't have the same effect.
