### ISSUE TITLE
Autocomplete md-min-length not always working

### ISSUE THREAD

**Issue by robgrimball** [angular/material#3727]
This is going to sadly be a pretty vague issue, so I apologize in advance.  I have not been able to figure out how to reliably reproduce it, but it seems to happen semi-frequently.

I have a list of items (ldap distinct names) which I am using with a search in an Autocomplete line.  Below is the html I am using.

                <md-input-container>
                    <md-autocomplete required md-selected-item="dn" md-input-name="dn" md-search-text="searchText" md-item-text="item" md-items="item in querySearch(searchText)" md-min-length="3" md-floating-label="Select a LDAP Group">
                        <md-item-template>
                            <span md-highlight-text="searchText" md-highlight-flags="^i">{{item}}</span>
                        </md-item-template>
                    </md-autocomplete>
                </md-input-container>

It appears that on odd occasion, the querySearch is not called when 3 characters are put into the input.  Sometimes it runs the search at 4 characters, sometimes more, sometimes I can't get it to search at all.  It seems to work more often than it doesn't, but this strange behavior is vexing me.

I am opening the issue mostly so that the team is aware there might be a problem with this.  Wish I could provide more details and I will if I can narrow it down more or get an example which reliably reproduces it.

**Comment by rscottfree** [comment]
@robgrimball What does your querySearch() function look like? I have had strange behavior when I was chaining the promise returned by querySearch(). I had my md-min-length=3 but results would not show up until I had entered the fourth character. I got around it by not chaining any .then()s off of my promise, but I still don't understand the problem since .then() should return a promise.

**Comment by robgrimball** [comment]
@rscottfree : Sorry about the delay in reply, I moved on to other things since posting that initial issue.  My querySearch is a very simple function, just going through an array of data more or less and returning the list of those that match : 

    $scope.querySearch = function(searchText) {
        var searchedList = [];
        for (var i=0; i<$scope.dataList.length; i++) {
            if ($scope.dataList[i].dn.toLowerCase().indexOf(searchText) >= 0) {
                searchedList.push($scope.dataList[i].dn);
            }
        }
        return searchedList;
    };

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by naomiblack** [comment]
bumping to post-1.0 as we can't reproduce from the info provided. (sorry!)
