### ISSUE TITLE
$mdDialog- add option to change transition target

### ISSUE THREAD

**Issue by leibale** [angular/material#3729]
i pop dialog with two buttons, if the user click on "cancel' i want the regular transition (to the bottom), but if the user click on the "ok" i want to change the transition target to other element.

now i only can send targetEvent when i call to $mdDialog.show, but can't change after.

**Comment by ThomasBurleson** [comment]
With the latest code in #master, you should now be able to do this:

If you specify an `options` block when showing the Dialog, you can modify the `options.origin.element` reference to point to any element you want. This reference will be used to determine the bounds for the zoom-close path.

```
var options;
$mdDialog.show(options = {
  controller: DialogController,
  templateUrl: 'dialog1.tmpl.html',
  parent: angular.element(document.body),
  targetEvent: ev,
  clickOutsideToClose:true

});

// Sometime before closing the dialog
options.origin.element = angular.element(myOtherElement);
$mdDialog.hide();
```
