### ISSUE TITLE
textarea growTextArea() uses non-existent function

### ISSUE THREAD

**Issue by asans** [angular/material#3730]
The following code generates an javascript exception:

https://github.com/angular/material/blob/master/src/components/input/input.js#L294

```
lineHeight = element.height();
```

height() function does not exist in jqLite and thus throws an exception.

This should probably be updated to 

```
lineHeight = element[0].offsetHeight;
```

**Comment by denjello** [comment]
I can confirm that this fix stops throwing errors.
