### ISSUE TITLE
md-tooltip not working on firefox

### ISSUE THREAD

**Issue by leonn** [angular/material#3731]
md-tooltip not working on firefox ( tested  on versions 38, 39 & nightly)

link below
https://www.browserling.com/browse/win/vista/firefox/38/https%3A%2F%2Fmaterial.angularjs.org%2Flatest%2F%23%2Fdemo%2Fmaterial.components.tooltip

**Comment by mualki** [comment]
This issue was fixed in the 0.10.1-rc1 release. 6fc9212c
