### ISSUE TITLE
md-autocomplete not working properly with $http.

### ISSUE THREAD

**Issue by pavankumarkatakam** [angular/material#3734]
I'm just checking the `md-autocomplete` the demo provided in codepen is working fine. But when i changed a few things to make it real time with `Github Users API` it's not working fine and the problem is when i selected a item which is populated by a query the loading progress design is not hiding and shows infinitly

here is the codepen [link](http://codepen.io/pavankumar0440/pen/rVvLWw?editors=101) im working on, please tell me if im doing wrong.

**Comment by rscottfree** [comment]
@pavankumarkatakam I'm not sure what the exact issue here is, but try setting your md-min-length to something other than 0, like 1. It looks to have something to do with this combination of md-min-length=0 and selecting an item in the list. If you can live with having a md-min-length of 1 or more, that is a workaround. It is working for me in this codepen (using a test API, not GitHub though): 
http://codepen.io/anon/pen/LVrqBR?editors=101

**Comment by pavankumarkatakam** [comment]
Thanks @rscottfree for that its working fine when we keep `md-min-length` to `1 or more`. but can somebody explains why is is not working for `0`.

**Comment by robertmesserle** [comment]
I believe this is resolved.  Closing for now, please respond if I should reopen.
