### ISSUE TITLE
md-secondary not working on mobile devices (android, ios)

### ISSUE THREAD

**Issue by sckoh** [angular/material#3736]
I am using ionic with angular material
md-secondary is not working on mobile devices but working on desktop browser

	<md-list-item class="md-3-line" ng-click="action1()">

		<div class="md-list-item-text" layout="column" style="margin-right:40px;">
		    <h3>title</h3>
		    <h4>subtitle1</h4>
		    <p>subtitle2</p>
		</div>
		<md-checkbox class="md-secondary" ng-change='doSomething()'
		             ng-model="data"></md-checkbox>
	</md-list-item>

and I have already put 

    $mdGestureProvider.skipClickHijack();

in my app.js .config(function() {});

**Comment by topherfangio** [comment]
@sckoh Can you please explain exactly what isn't working and if you're still seeing the issue with the latest master code?

If so, a [Codepen](http://codepen.io) demonstrating the issue would be super-helpful.

Thanks!

**Comment by topherfangio** [comment]
We really need a Codepen to be able to work on this issue. If you can provide one, we will reopen.
