### ISSUE TITLE
md-select: moving between options is not working user friendly

### ISSUE THREAD

**Issue by elementh69** [angular/material#3738]
I got an md-select field with countries. When I click on it, it opens options list (as I expect), but now i want to press "P" button on my keyboard several times to find my Country (it's normal behavior of select field type) but nothing happend.

Example is on the documentation:
https://material.angularjs.org/latest/#/demo/material.components.select

Click on the "State" and try to move between options for example by typing "A" few times.

I am using 0.10.0 version of Angular material.

**Comment by cleever** [comment]
A autocomplete option would be perfect with md-select.
