### ISSUE TITLE
fabSpeedDial doesn't work on Safari

### ISSUE THREAD

**Issue by rgolea** [angular/material#3739]
Please take a look at it in Safari. I've tested with `Safari Version 8.0.7 (10600.7.12)` on my Mac. Animation doesn't work. Thank you!

**Comment by topherfangio** [comment]
Hey @rgolea!

Can you tell me what version you are using? I know I fixed a webkit bug recently with the animations. If possible, can you try the latest master and see if that fixes it?

Thanks!

**Comment by topherfangio** [comment]
@rgolea Any chance you could test out the latest master version and see if this is fixed? Thanks!

**Comment by rgolea** [comment]
Works on master. Thanks!

**Comment by topherfangio** [comment]
@rgolea Glad it worked!

**Comment by rgolea** [comment]
Can you put the latest one on npm so I can install it with the latest master?
`npm install http://github.com/angular/bower-material/tarball/master` I have some other stuff that I'm working on and would be nice to have the latest features

**Comment by topherfangio** [comment]
I'm not quite sure how often things get pushed to bower-material.

@ThomasBurleson Can you chime in on this topic real fast?

**Comment by ThomasBurleson** [comment]
We only publish to NPM during releases (@see `release.js`). 

You should, however, be able to install directly from master:

```terminal
npm install git+https://github.com/angular/bower-material.git
```

or for those without git

```terminal
 npm install http://github.com/angular/bower-material//tarball/master
```
