### ISSUE TITLE
sidebar inside ui-view layout issue

### ISSUE THREAD

**Issue by blxstar** [angular/material#3740]
Hello,

i have the following issue when using ui-view and sidebar/toolbar from the examples:

![image](https://cloud.githubusercontent.com/assets/5336985/8698502/1f92ebba-2aff-11e5-9bf9-10d12ecf1dba.png)

no content

![image](https://cloud.githubusercontent.com/assets/5336985/8698514/3a203ed8-2aff-11e5-9b51-eaf7bf426f9d.png)

code:
![image](https://cloud.githubusercontent.com/assets/5336985/8699720/e1b712f4-2b07-11e5-829e-1b2c4b5c96de.png)

i hope someone can help me...

thanks!

**Comment by mckenzielong** [comment]
I think this is an issue better suited for the [forums](groups.google.com/forum/#!forum/ngmaterial).  

Adding layout-fill to your ui-view div should resolve this.  If not, setting layout-fill on your body certainly will.  I believe flex elements need a height set to properly flex. Setting your containing div to the entire viewport height will cause the elements inside to properly flex.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
