### ISSUE TITLE
md-tabs do not appear in IE11 starting with material 0.10.0

### ISSUE THREAD

**Issue by Mctalian** [angular/material#3742]
I've created a [Pen](http://codepen.io/anon/pen/LVrMVg) that uses the Angular Material Basic App as a starting point, opening it in IE11 and performing the following step will reproduce the issue:

On line 4, change `0.9.4` of `angular-material.min.css` to `0.10.0`.

You will notice the words tabs "Test1" and "Test2" no longer appear on the screen.

**Comment by PDSBGreg** [comment]
I think this has to do with the Angular version. The demo pages for material work in IE11. They use Angular 1.3.15, while your pen is using 1.4.2. The site that I'm working on with Angular 1.4.0 still works. I think there were animation changes in 1.4.1 that have broken some material things.

**Comment by Mctalian** [comment]
I think it has to do with both the angular version and the Material version, no? Why else would it work on 0.9.4 but not 0.10.0?

I think there are multiple incompatibilities because rolling back the angular versions for the Pen above still causes odd behavior.

[Angular, Animate, Aria 1.4.2; Material 0.10.0](http://codepen.io/Mctalian/pen/oXyRaB) Tabs do not display in IE11
[Angular, Animate, Aria 1.4.2; Material 0.9.4](http://codepen.io/Mctalian/pen/GJGaYy) Works as expected in IE11
[Angular, Animate, Aria 1.4.0; Material 0.10.0](http://codepen.io/Mctalian/pen/WvyBaY) Tabs appear but the line underneath does not animate properly in IE11

**Comment by ThomasBurleson** [comment]
Can you confirm this issue is still valid with lastest code in master (v0.11.0-rc2)?

**Comment by Mctalian** [comment]
I will attempt to confirm tomorrow.

**Comment by PDSBGreg** [comment]
Here's a fork of one of the pens from above with Angular 1.4.4 and Material 0.11.0-rc2
http://codepen.io/anon/pen/ZbYvNW
It's working in IE 11 (at least it is for me). The tabs appear and the underline animates.

I also tried with Angular 1.4.0 and 1.3.15 and the tabs function the same in all versions.

**Comment by Mctalian** [comment]
The pen that @PDSBGreg linked works for me on IE11.

FWIW It appeared to be resolved in 0.10.1: [http://codepen.io/anon/pen/MaYQJb](Angular, Animate, Aria 1.4.4; Material 0.10.1). I tried Angular 1.4.2 and 1.4.4 and both seem to work with Material 0.10.1.

Thank you for following up.
