### ISSUE TITLE
Error in documentation about md-item-text in md-autocomplete

### ISSUE THREAD

**Issue by smileapplications** [angular/material#3743]
![error-angular](https://cloud.githubusercontent.com/assets/2022691/8704176/bba4ec8e-2b21-11e5-8a2a-582b6e0692a3.PNG)

Hello everybody,
I find this a little strange... Is a string or an expression ?

It should be something like this right ?

![error-angular-2](https://cloud.githubusercontent.com/assets/2022691/8704220/fe6fd1f0-2b21-11e5-841b-bf6d16c1b3ca.PNG)

**Comment by ilanbiala** [comment]
@ThomasBurleson @robertmesserle @rschmukler @marcysutton any update on this? The docs seem to be quite confusing with all the rapid changes.
