### ISSUE TITLE
md-list with more then one md-secondary

### ISSUE THREAD

**Issue by ricardobfa** [angular/material#3744]
In my list of objects, i can active/inactive an object. So, a icon make a active action and the other one make the inactive action, and both are in the same `md-list`. 

[This is what i'm tring to do][1]

code:

    <md-list ng-app="MyApp" class="listdemoListControls" ng-controller="ListCtrl">
      <md-list-item ng-repeat="message in messages" ng-click='actionOne("action one")'>
        <p>{{message.title}}</p>
    
        <md-button class="md-secondary md-icon-button" ng-if="!showActionThree" ng-click="actionTwo('action two')" >
          Two // secondary action
        </md-button>
    
        <md-button class="md-secondary md-icon-button" ng-if="showActionThree" ng-click="actionThree('action three')">
          Three // third action
        </md-button>
     </md-list-item>
    </md-list>

The problem is that my `actionThree` function dos not fire.

Sounds like when i use `md-secondary` class he creates a wraper receiving my `actionTwo` function, and this function dos not change.

Is there any way of making this work?

  [1]: http://codepen.io/anon/pen/QbxJaw?editors=101

**Comment by qvazzler** [comment]
+1

**Comment by mzbyszynski** [comment]
Duplicate of #2595?

**Comment by qvazzler** [comment]
@mzbyszynski looks about right. Did not find it at first so hopped onto this one.

Once again, would love to have the feature..

**Comment by miclaus** [comment]
+1

**Comment by JuHwon** [comment]
+1

**Comment by AleksueiR** [comment]
+1

**Comment by topherfangio** [comment]
Closing as duplicate of #2595, however, it looks like some support has been added as the `actionThree` is now firing; it just also appears to be firing `actionOne` on click.

**Comment by tychay** [comment]
I think this should be re-opened. In 1.0.7 (tested), the above code, clicking on "Three" will execute action three AND action one, while clicking on "Two" will execute action two only.

**Comment by topherfangio** [comment]
@tychay Since these are both closed as either "duplicate" or "fixed"; can you please open a new ticket with a Codepen that shows the issue and reference this one?

**Comment by DevVersion** [comment]
@tychay Also please confirm your issue with the latest major release - `v.1.1.0-rc2`, there were a few changes to the secondary items.
