### ISSUE TITLE
mdToast: success callback fired on toast timeout

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#3745]
##### Overview of the Issue
Action toasts are firing the success call back when they are dismissed due to the timeout being reached / auto dismissing.  This wasn't the case in 0.10, 0.9.8, etc.

##### Browsers and Operating System
Windows 7, Chrome 43.0.2357.132

##### Reproduce the error
Reproducible on the toast demo: https://material.angularjs.org/HEAD/#/demo/material.components.toast -- click the 'show with action' toast and wait for the toast to auto hide.  The callback if fired and you are alerted that you clicked 'OK'

##### Related Issues
Might be related to https://github.com/angular/material/issues/3704?

**Comment by gkalpak** [comment]
This was an intentional change #3558.
The demo should probably be changed to say something else.

But, I think it might be useful to be able to differentiate between clicking the button and timing out.
Maybe resolving with a value of true vs false ?

**Comment by mckenzielong** [comment]
> But, I think it might be useful to be able to differentiate between clicking the button and timing out.
Maybe resolving with a value of true vs false ?

:+1: 

The action button being clicked seems like a pretty common use case, which was more or less broken by #3558.  Out of curiosity, was there a reason why it was changed from cancel to hide? Couldn't the promise's finally been used for the timeout?

**Comment by ThomasBurleson** [comment]
@mckenzielong - The reason for this change is that a `hide-action !== reject === cancel`. I will be fixing this issue to be included with the pending 0.10.1-rc2.

**Comment by ThomasBurleson** [comment]
Internally all menu, dialog, and toast elements now resolve with 'true' for hide or timeout responses; unless overridden in the `.hide(value)` call.  Toast click actions now resolve with 'ok'; see demo.
