### ISSUE TITLE
Display Issue in Controller/Directive

### ISSUE THREAD

**Issue by davidlmiller21** [angular/material#3746]
I've used the following in a controller and directive:

$mdToast.show(
            $mdToast.simple()
                .content('Simple Toast!')
                .position('top right')
                .hideDelay(3000)
        );

When I do not set the parent, I get a black box, and when a set the parent I get a blank line; does anyone know what's likely going on with this?

**Comment by ThomasBurleson** [comment]
* What version of Angular Material
* What version of Angular
* What browser and OS

Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by davidlmiller21** [comment]
I forgot to add the CSS file, which caused the issue. Is there any way to do a custom build of angular-material and only use the $mdToast service? I don't want to alter the styling of other components and change the typography that I currently have.
