### ISSUE TITLE
Toolbar shadow v.0.10.1-rc1

### ISSUE THREAD

**Issue by stefan--** [angular/material#3747]
Hi there, 

following the spec for the toolbar (https://www.google.de/design/spec/components/toolbars.html#) shouldn't it come with a shadow?

I am using `0.10.1-rc1` and used the code from the demo.

Thanks for your help.

Stefan

**Comment by epelc** [comment]
@stefan-- You can add the whiteframe classes to do this.

https://material.angularjs.org/latest/#/demo/material.components.whiteframe

**Comment by stefan--** [comment]
@epelc thanks mate

**Comment by epelc** [comment]
@stefan-- Your welcome.

Can you close the issue please.
