### ISSUE TITLE
SideNav: Rendering issue in Firefox for Android

### ISSUE THREAD

**Issue by lkarthee** [angular/material#375]
Side navigation of demo renders differently : 
 1. menu items appear like buttons.
 2. menu button (hamburger icon button) also looks different with gradient.

Firefox version : 32.0.3

![screenshot_2014-10-07-09-58-34](https://cloud.githubusercontent.com/assets/2712395/4537474/22f6418a-4ddd-11e4-9bdc-08729f0df66c.png)

![screenshot_2014-10-07-10-00-03](https://cloud.githubusercontent.com/assets/2712395/4537436/26488966-4ddc-11e4-914a-00e734665dbc.png)

**Comment by ThomasBurleson** [comment]
Fixed.
