### ISSUE TITLE
md-tabs slow in in IE11 

### ISSUE THREAD

**Issue by byunru** [angular/material#3750]
In demo site https://material.angularjs.org/latest, md-tabs is super slow in IE 11

**Comment by david-gang** [comment]
I also experienced  this problem:
After profiling it, i found that the functions:

* offsetHeight
* getBoundingClientRect
* clientWidth

are very slow in ie.

This is a problem as these are built in functions.

Would be interesting to know what the direction of the solution would be

**Comment by djleonskennedy** [comment]
+1

**Comment by ThomasBurleson** [comment]
Pull Requests are welcomed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
