### ISSUE TITLE
Clicking inside md-menu gives an error

### ISSUE THREAD

**Issue by sergonius** [angular/material#3752]
The same error as in this issue: https://github.com/angular/material/issues/3397
Uncaught TypeError: target.hasAttribute is not a function

I am not using md-menu-item in this menu, I have custom content there. Where ever inside the menu I click though, it triggers the error.

**Comment by diegolaciar** [comment]
+1 -    Uncaught TypeError: target.hasAttribute is not a function
Using ui-sref

**Comment by rschmukler** [comment]
@diegolaciar are you running off of master?

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by rschmukler** [comment]
Additionally, tests were added with dc0114916beb8442ca44972c88affa9210b0f75e to ensure that this behavior worked. Likely resolved

**Comment by rschmukler** [comment]
Closing. If issue persists, please open a new one.
