### ISSUE TITLE
Small ripple for md-icon-button on touch devices, possibly a bug with md-ripple-size

### ISSUE THREAD

**Issue by bl5eebryce** [angular/material#3757]
The touch ripple size for icon buttons is very small compared to other apps. White is from Google Calendar, blue is from an angular material app.
![2015_07_15_22 35 32 1](https://cloud.githubusercontent.com/assets/12262695/8715697/41f71340-2b43-11e5-9c9f-598280c5461e.png) ![2015_07_15_22 37 29 1](https://cloud.githubusercontent.com/assets/12262695/8715702/50cecce6-2b43-11e5-85ec-fbbfeaf53c87.png)
It seemed that changing md-ripple-size="full" would change this, however md-ripple-size did nothing, even when I set it to "partial" or "auto".

This was only a problem for icon buttons, normal buttons worked just fine.

**Comment by runethh** [comment]
How to reproduce: 
1. Select "Button" in the demo area
2. Navigate to the "Icon Buttons" area
3. Tap the various buttons a few times. Observe that the buttons only produce a very small, nearly invisible, ripple response on every tap. 


Tested on two smartphones:

Model: Iphone 6 (MG4F2QN/A) 
Operating System: iOS 9.1 (13b143) 
Browser: Safari 9.0 mobile

And 

Model: Nexus 6 (Shamu)
Operating System: Android Lollipop 5.11 (LMY47Z)
Browser: Chrome (46.0.2490.76)

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (415/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:56270 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZY-001Z4H-4m
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:07 +0200
Date: Thu, 28 Apr 2016 13:29:22 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875362;
	bh=e0MrsqufEHG1TLr3MwCRoK4C7DecQIleqL1/Q/yN8/Q=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=w+EJG/5OxxvHWbnniCb1va0iNTl0kaHaEJ8wZGiWvFGxzaKijBqn00AMumvNtuzSc
	 jNZXsmqn0ljOnc+Q8fnxBPl8FpDRnvqvWX1gHjQMG7qql7V5uSiVAZWl0Qa4j3eWDh
	 8Kg5g5QxcH/lPylj+7CDQLIw/gcXP4OzF8JzxMqQ=
