### ISSUE TITLE
autocomplete icon as placeholder

### ISSUE THREAD

**Issue by antoba** [angular/material#3763]
Is there a way to put an icon in md-autocomplete as placeholder (search icon for example) or on the left (like in input text) ?

Thank you in advance
Antonio

**Comment by bathos** [comment]
I was trying to figure this out too. The material design spec docs have a page on search inputs which shows them with icons both in the input field and the autocomplete list. As far as I could tell, we can't currently provide a template for the input itself; there are just two fixed options.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
