### ISSUE TITLE
md-list-item: wrong align and word wrapping behavior in IE

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/material#3764]
These are acutally two bugs that only occur in IE (I've only tested it in IE11 but I guess it's the same for earlier version):

1) (non-clickable) md-list-items only containing text align the text at the top
2) clickable md-list-items with a long text get a weird word wrap

[CODEPEN](http://codepen.io/anon/pen/pJZogz?editors=110)

**IE11:**
![IE](http://i.imgur.com/eClwerp.png)
**Chrome:**
![Chrome](http://i.imgur.com/5EBAWv8.png)

```HTML
<body ng-controller="AppCtrl" ng-app="MyApp" layout="row">
    <md-list class="md-whiteframe-z2">
        <md-list-item style="background: blue;">
            <span>Test 1</span>
        </md-list-item>
        <md-list-item ng-click="console.log('click')"  style="background: green;">
            <span>Test longlong button button button</span>
        </md-list-item>

        <md-list-item style="background: red;">
            <span>Test longlong text text text text</span>
        </md-list-item>
    </md-list>
    
    <div flex style="background: #CCC"></div>
</body>
```

**Comment by JuHwon** [comment]
+1

**Comment by JuHwon** [comment]
The reason of strange word wrap with an ng-click is because of the generated button with the class `md-no-wrap` which has a flex property set. If you do `flex:none` on these elements the word wrap is gone. The text align on top still remains though.

**Comment by JuHwon** [comment]
I found out that the vertical textalignment will work if you specify a height. By default there is only a `min-height` set (on the `md-list-item-inner` class), which is breaking the `align-items: center` in IE. http://jsfiddle.net/e93Lho0q/

**Comment by topherfangio** [comment]
Both of these issues appear to be fixed in master.

If you are still experiencing issues after upgrading; please comment and I will reopen.

**Comment by ashraftm** [comment]
Yes, it is still appears in chrome. try same link above or (http://codepen.io/anon/pen/pJZogz?editors=110). Now shrink the browser as closest as possible you will see gap between lines.
