### ISSUE TITLE
md-menu: location of menu is incorrect

### ISSUE THREAD

**Issue by sinujohn** [angular/material#3768]
When the number of menus is high menu appears at the wrong position. Its especially true, if the menu is not yet visible and you have to scroll to that menu, and when you click on it, the menu appears somewhere else. Here is the codepen(I just modified the original example in the angular material site): http://codepen.io/anon/pen/GJBJZr
Screenshot:
![menu](https://cloud.githubusercontent.com/assets/866225/8726350/45606108-2bf7-11e5-80c4-48b10647ec86.PNG)

**Comment by stefan-schweiger** [comment]
This was already fixed in the master current master I think: http://codepen.io/anon/pen/PqBqmK

**Comment by sinujohn** [comment]
Thanks for the info! Its fixed!
