### ISSUE TITLE
Indeterminate Progress - Circular Animation Issue in Firefox for Android

### ISSUE THREAD

**Issue by lkarthee** [angular/material#377]
Indeterminate Progress - Circular does not render animation correctly in Firefox for Android - 

Firefox version : 32.0.3

![screenshot_2014-10-07-09-59-12](https://cloud.githubusercontent.com/assets/2712395/4537508/1d2b3a98-4dde-11e4-8159-585dd6fd3e1b.png)

**Comment by kylemeier** [comment]
In Firefox 39/38 determinate has some white spaces and a bit of clipping while indeterminate has massive clipping issues.

![screen shot 2015-07-07 at 11 31 41 am](https://cloud.githubusercontent.com/assets/4296445/8553976/f07630e4-249b-11e5-9d57-fe8031202ed9.png)

**Comment by EladBezalel** [comment]
@crisbeto is this solved after your PR?

**Comment by ThomasBurleson** [comment]
Appears to be resolved/fixed.
