### ISSUE TITLE
feat(chips): add directive for dynamically resizing input to content

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#3771]

**Comment by typotter** [comment]
Is this related to Chips? Not sure what the context is here, Rob.

**Comment by robertmesserle** [comment]
@typotter It's related to chips, but in terms of implementation, I'm not sure where it would live.  Basically, while you are typing, I wanted the text field to expand/contract to fit your text - that way, wrapping would be accurate while typing and your text wouldn't be cut off for longer chips.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
