### ISSUE TITLE
md-tabs inside of md-dialog are not displaying md-ink-bar for the selected tab in IE10

### ISSUE THREAD

**Issue by bshir** [angular/material#3772]
When displaying an md-dialog containing md-tabs, the ink bar is not displaying below the selected tab in IE10.
I took the demos for the dialog and md-tabs and combined them to reproduce the issue.
http://codepen.io/anon/pen/EjpVGw

**Comment by HBO2** [comment]
+1 Will this be fixed in the next release?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
