### ISSUE TITLE
master#6bc6f0796f breaks chip size

### ISSUE THREAD

**Issue by oharlem** [angular/material#3777]
Hi,

After checking out master#6bc6f0796f, chips are not showing full titles any more, just first letters and an ellipsis.
Please check the screenshot attached.

Thanks,
D.

<img width="343" alt="screen shot 2015-07-16 at 11 39 12 pm" src="https://cloud.githubusercontent.com/assets/7634675/8740254/36667b5c-2c14-11e5-9799-6ce190c99fcd.png">

**Comment by typotter** [comment]
Hi oharlem. Is this issue still happening at HEAD? I see a commit [7fed14e](https://github.com/angular/material/commit/7fed14ebac76e136059b4fb2a890ddae470d19ef), which prevents unnecessary ellipses.
