### ISSUE TITLE
md-input: One-way binding issue

### ISSUE THREAD

**Issue by tolemac** [angular/material#3779]
I'm trying to show a formated date.

(All examples in this CodePen: http://codepen.io/jros/pen/WvKoJK?editors=101)

Case 1: Using ng-model

        <md-input-container>
          <label>Date ReadOnly ngModel </label>
          <input readonly type="text" ng-model="user.submissionDate | date:'dd-MM-yyyy'">
        </md-input-container>

Shows correctly but I get `[ngModel:nonassign] Expression 'user.submissionDate | date:'dd-MM-yyyy'' is non-assignable`, of course ... I agree, I cant use filters in the ngModel expression.

Case 2: Try to use ngBind

        <md-input-container>
          <label>Date ReadOnly ngBind </label>
          <input readonly type="text" ng-bind="user.submissionDate | date:'dd-MM-yyyy'">
        </md-input-container>

Dont show anything, I can see it in the Element Inspector:

    <input readonly="" type="text" ng-bind="user.submissionDate | date:'dd-MM-yyyy'" class="ng-binding md-input" id="input_1">17-07-2015</input>

And I understand that ngBind set the innerhtml.

Case 3; Try value with moustache syntax

        <md-input-container>
          <label>Date Moustache on Value </label>
          <input readonly type="text" value="{{user.submissionDate | date:'dd-MM-yyyy'}}">
        </md-input-container>

The input not show any value but if you put the focus on it the value shows but over the floating text (that not do animation)

The last try put the final value on value attribute:

        <md-input-container>
          <label>Text Readonly Moustache on Value </label>
          <input readonly type="text" value="Hola AMIGO!!">
        </md-input-container>

The same thing ...

I thing the issue is on case 3, the first issue is normal, and the ngBind option too.

The same behavior occurs when chrome automatically fill the inputs on the page, on user name and password for example, you have to enter on the input for see the value, on not read only input, for example:

        <md-input-container>
          <label>Text Moustache on Value </label>
          <input type="text" value="Hola AMIGO!!">
        </md-input-container>

the value is not show until you focus the input.

Only tested on chrome, I dont know how works in others.

Related: #1693

**Comment by robertmesserle** [comment]
This is more of an Angular question than Angular Material, but I want to look into it when I get a chance.

**Comment by robertmesserle** [comment]
As previously stated, this is an Angular issue.  I wanted to look into it anyway, but due to bandwidth issues, I will not be able to.

**Comment by tolemac** [comment]
I have created a new codepen: http://codepen.io/jros/pen/EVpMNE?editors=101

This have the same examples, this time using md-input-container and without using it.
If is an Angular issue, why the behavior is not the same?

Thanks in advance.

**Comment by robertmesserle** [comment]
@tolemac Thanks, re-opening.
