### ISSUE TITLE
Can we provide isolated scope to md-dialog

### ISSUE THREAD

**Issue by arshdefoamed** [angular/material#3781]
Can we give any javascript object as the isolated scope to md-dialog. I tried this on a plunker but seems like it doesnt accept anything other than the $scope object. So can we add this as the functionality just like a directive.Here is the link to plunkr 
http://plnkr.co/edit/Ur4rvcVp0A6n458NNqWw?p=preview

**Comment by gkalpak** [comment]
Not sure if this is what you mean, but you can pass any scope (normal or isolate).
Here is an example with two dialogs: one with a normal scope (inheriting a greeting from its parent scope) and the other with an isolate scope (that doesn't inherit :disappointed:).

[1]: http://codepen.io/ExpertSystem/pen/VLBprO?editors=101

**Comment by arshdefoamed** [comment]
Apologies for not being able to make my thoughts clear :( . What I really meant that when we are providing scope to md-dialog it should be either a $scope object or something like $scope.$new(). What I really wanted was to be able to simply provide any javascript object as the scope just like we define it when we are creating a directive.

**Comment by ThomasBurleson** [comment]
The only solution we have is to pass `locals`: an object with values and references that will be injected or bound to the dialog controller.
