### ISSUE TITLE
$mdDialog does not remove dialog-container in Firefox

### ISSUE THREAD

**Issue by Tyrannmisu** [angular/material#3782]
Since 0.10.1-rc2 the dialog-container 
```
<div style="top: 0px;" class="md-dialog-container ng-scope">
```

is not removed after closing the dialog, which results in an unusable website because all elements are behind this invisible div.

Pretty sure that this is caused by the following change:
"switch dialog to use disableScroll, fix focus trap ([862444a8](https://github.com/angular/material/commit/862444a8), closes [#2443](https://github.com/angular/material/issues/2443))"

Because "disableParentScroll: false" fixes/circumvents the issue.
This happens in both Firefox 31 & Firefox 40 on the official demo-page when opening and closing the custom dialog

**Comment by mattiarigo-humus** [comment]
+1
Same issue also in 0.9.8 with Firefox 38

**Comment by ThomasBurleson** [comment]
https://material.angularjs.org/0.10.1-rc2/#/demo/material.components.dialog with FireFox 31 works fine and removes the `md-dialog-container`

**Comment by ThomasBurleson** [comment]
Fixed wth SHA 7bbfd1f8e7eabb3cecc383347

**Comment by Tyrannmisu** [comment]
Thanks for the fix!

**Comment by Tyrannmisu** [comment]
I get the "InterimElement.cancel() error: false" - message pretty regulary now when closing dialogues. It works nonetheless, but maybe this should be looked into.

**Comment by Londovir** [comment]
Agreed - it is happening also on the Demo site when using the "Looks like a scam" (cancel) button on a Confirmation Dialog sample. Can't track down the origin, but based on commits looks like it would have begun around commit eaa3324407799a600353b4f9bbc7ccf4ef2e2b37.

**Comment by musahaidari** [comment]
I am having this issue with "angular-material": "^1.0.5" too.

**Comment by musahaidari** [comment]
<div class="md-scroll-mask" style="z-index: 50;" aria-hidden="false">  <div class="md-scroll-mask-bar"></div></div>

This element in my case will remain

**Comment by musahaidari** [comment]
/**
       * Detach the element
       */
      function detachAndClean() {
        angular.element($document[0].body).removeClass('md-dialog-is-showing');
        element.remove();
        angular.element('.md-scroll-mask').remove(); // Adding this line solved my issue, on line 747

        if (!options.$destroy) options.origin.focus();
      }
