### ISSUE TITLE
Layout not working properly in Android 4.2.2

### ISSUE THREAD

**Issue by pavankumarkatakam** [angular/material#3783]
I just created an web app it works fine in browser and small screens, when i make it an app using ionic build, the layout crashes in android mobile (v 4.2.2). Im attaching the screen shots for reference

![android](https://cloud.githubusercontent.com/assets/6078669/8744335/088d145e-2c94-11e5-9046-aab27e574ff8.png)
In Android mobile

![chrome browser](https://cloud.githubusercontent.com/assets/6078669/8744334/08892c7c-2c94-11e5-94d2-e3406568ee40.png)
In normal desktop browser chrome.

and i want to know browsers support by this framework.

**Comment by david-gang** [comment]
This is connected to #3073

**Comment by naomiblack** [comment]
dup of #3073 for the general case, but also, this is specifically an issue with Ionic which should be reported to that project.
