### ISSUE TITLE
md-tooltip loses styles with ng-bind

### ISSUE THREAD

**Issue by jmmayoh** [angular/material#3786]
md-tooltip style is changed when you use ng-bind instead {{ }} notation.

i just created an example with four buttons in codepen. http://codepen.io/anon/pen/XbBMMZ

**Comment by gkalpak** [comment]
This is probably because tooltip uses transclusion, so the `ngBind` doesn't play nice with transclusion.
Maybe you have to stick with `{{...}}` instead (using `ngCloak` if appropriate)...
