### ISSUE TITLE
md-menu inside md-sidenav click to close issue

### ISSUE THREAD

**Issue by martinbrylski** [angular/material#3787]
Using a md-menu inside a md-sidenav all clicks on the sidenav will be ignored. The intended behavior should be, that the menu closes if clicked outside of the menu.

I think the problem is the z-index (50 for md-menu, 60 for md-sidenav).

**Comment by anjroo** [comment]
Same issue over here!

**Comment by ThomasBurleson** [comment]
```css
$z-index-menu: 99 !default;
$z-index-dialog: 80 !default;
$z-index-toast: 90 !default;
$z-index-bottom-sheet: 70 !default;
$z-index-scroll-mask: 65 !default;
$z-index-sidenav: 60 !default;
$z-index-backdrop: 50 !default;
```
mdMenu has a z-index == 99; while mdSideNav z-index == 60. The issue, I believe, is that **both** the mdSideNav and mdMenu use a backdrop element.

**Comment by ThomasBurleson** [comment]
Have you tried this with the latest code in bower-material/master?

* Which version of Angular Material are you using?
* Which version of Angular are you using?

Please provide a CodePen or Plunkr to help us investigate and debug this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by EladBezalel** [comment]
Couldn't reproduce, here's a [codepen](http://codepen.io/EladBezalel/pen/KdabdL)
