### ISSUE TITLE
md-subheader not refreshing its bindings

### ISSUE THREAD

**Issue by dragonflypl** [angular/material#3790]
I have this piece of code:

       <md-subheader class="md-no-sticky">
            Activities ({{vm.selectedActivities.length || 0}} selected)
        </md-subheader>

```vm.selectedActivities``` changes. But ```{{vm.selectedActivities.length}}``` is not refreshed, unless I do something else on the page, for instance resize it. I also put ```{{vm.selectedActivities.length || 0}}```outside ```md-subheader``` and it gets properly refreshed. Is there a way to fix it?

**Comment by fals** [comment]
@dragonflypl Which angular material version are you using? Did you checked this with the lastest version v0.10.1-rc2?

**Comment by dragonflypl** [comment]
0.10

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

> Please make sure you are using the lastest code from master (v0.11.0-rc2)

**Comment by ThomasBurleson** [comment]
This appears to be a `$scope.$apply( <function>) ` issue. If you determine that this is not an $apply() problem, please submit a new issue.
