### ISSUE TITLE
md-menu items overlap each other after rc1->rc2 with many items

### ISSUE THREAD

**Issue by alanpurple** [angular/material#3791]
md-menu-items overlap each other after updating rc2 from 0.10.1-rc1; when items are more than 6

**Comment by jameswyse** [comment]
:+1: As a temp fix I set `min-height: 48px` on `md-menu-item`

**Comment by alanpurple** [comment]
@jameswyse  thanks for workaround tip!

**Comment by ThomasBurleson** [comment]
@alanpurple - Do you have a CodePen/Plunkr demo to show this?
@jameswyse - :+1:

**Comment by jameswyse** [comment]
Here's a quick codepen demo showing the issue in RC3

http://codepen.io/jameswyse/pen/NqLMVR
