### ISSUE TITLE
md-FAB-speed dial children buttons are all positioned on the same coordinate.

### ISSUE THREAD

**Issue by deckikwok** [angular/material#3796]
in Safari (both iOS and mac) the buttons in the menu are positioned incorrectly - see image. I do not know if anyone has encountered this issue; I've fix positioned the menu button to a parent container.

Upon inspection, the class "md-fab-speed-dial md-fab-actions" height is not calculated. 

Currently the fix I've employed is to add position:fixed, height:auto; bottom: 0 (or x%) and it works on Chrome and Safari. But this is really hackish.

![safari bug md speed dial](https://cloud.githubusercontent.com/assets/1747820/8760085/83cc07ae-2d3b-11e5-923e-7f0f84165070.png)

**Comment by LexFrench** [comment]
Yeah, I'm seeing the same issue as well. Had to follow similar steps as deckikwok explained to get it working.

**Comment by daftfox** [comment]
this is fixed by setting the height for .md-fab-actions to 'auto'

**Comment by topherfangio** [comment]
Hey guys, sorry for the delayed response. Is this an issue you are seeing in the latest master? I know I fixed something like this recently, so I want to see if that is causing issues.

**Comment by deckikwok** [comment]
@topherfangio yes im on 0.10.0
@daftfox you are right; it works when I set the class's height attr to auto.

**Comment by topherfangio** [comment]
I've got some commits coming soon which will use `height: auto` so this should be fixed soon. I'll keep it open and post an update when fixed.
