### ISSUE TITLE
Inconsistent behavior with disabled and ng-disabled

### ISSUE THREAD

**Issue by OlsonDev** [angular/material#3797]
If I add the `disabled` attribute to `md-switch`, `md-select`, & `md-slider` the behavior is weird.

- `md-switch` looks enabled, can be focused (but doesn't change appearance), doesn't respond to spacebar or clicks
- `md-select` looks disabled, doesn't respond to clicks, can't be focused
- `md-slider` looks disabled, can be focused, responds to clicks, does not open its thumb

If I change `disabled` to `ng-disabled="true"`:

- `md-switch` behaves the same (as if it had the disabled attribute)
- `md-select` behaves the same (as if it had the disabled attribute)
- `md-slider` no longer responds to clicks but can be focused

I wouldn't doubt if other controls exhibit poor behaviors but these are the ones I have in my app and have tested.

**Comment by bengadbois** [comment]
I see the same behavior on with md-switch

**Comment by Masadow** [comment]
I'm not sure what does `md-select behaves the same` means for you (is it like `disabled` or is it like if there were nothing ?)

But for me, when I add `ng-disabled="true"` to `md-select`, then it does not respond to click and can't be focused, but it does not look like disabled.

**Comment by OlsonDev** [comment]
I edited the OP for clarity: `md-select` behaves the same (as if it had the disabled attribute)

That is, it looks disabled, doesn't respond to clicks, can't be focused. I just double-checked this with the latest update (angular 1.4.3, angular/material 0.10.1). Odd that we're getting different behavior.

**Comment by bengadbois** [comment]
I just noticed if you add the "md-primary" class to md-switch, it'll override the disabled grayed out appearance, so it'll look enabled, but acts disabled (ie the first bullet point in the OP).

**Comment by Masadow** [comment]
@OlsonDev I was using 0.10.1-rc5, just upgraded to 0.10.1 and still get the same behaviour.

What is looking disabled for you ? Can you provider a screenshot ?

![disabled](https://cloud.githubusercontent.com/assets/2227736/9246425/c46f3112-41ab-11e5-8980-ac22d8245369.png)

In the provided example, only the last two fields are disabled for me, it works as expected aside from the design that looks like other enabled fields.

According to disabled inputs, I guess there should be a dotted border at the bottom of the select ?

**Comment by OlsonDev** [comment]
Enabled, `ng-disabled="true"`, `disabled="disabled"`:

```html
<md-select flex="10" class="md-primary" ng-model="options.selectedDisplayNumber" aria-label="Display number">
    <md-option ng-repeat="displayNumber in availableDisplayNumbers" ng-value="{{options.displayNumber}}">{{displayNumber}}</md-option>
</md-select>
...
<md-select flex="10" class="md-primary" ng-model="options.selectedDisplayNumber" aria-label="Display number" ng-disabled="true">
    <md-option ng-repeat="displayNumber in availableDisplayNumbers" ng-value="{{options.displayNumber}}">{{displayNumber}}</md-option>
</md-select>
...
<md-select flex="10" class="md-primary" ng-model="options.selectedDisplayNumber" aria-label="Display number" disabled="disabled">
    <md-option ng-repeat="displayNumber in availableDisplayNumbers" ng-value="{{options.displayNumber}}">{{displayNumber}}</md-option>
</md-select>
```
No focus, focus 1st `<md-select>`, activate 1st `<md-select>` (cannot focus/activate 2nd/3rd):
![1](https://cloud.githubusercontent.com/assets/308072/9246817/d5976686-4173-11e5-91e8-c212f53dd2e3.png) ![2](https://cloud.githubusercontent.com/assets/308072/9246818/d5979bd8-4173-11e5-9edd-0c3c6e399ba5.png) ![3](https://cloud.githubusercontent.com/assets/308072/9246819/d598d0de-4173-11e5-8404-4d983924d589.png)

**Comment by Masadow** [comment]
Oh, then there's an issue when using placeholder on top of that. In my examples, I'm using placeholder.

Just try to add a placeholder in a fourth column and you'll see that he looks like the disabled input

    <md-select flex="10" class="md-primary" ng-model="options.selectedDisplayNumber" aria-label="Display number" placeholder="Number">
        <md-option ng-repeat="displayNumber in availableDisplayNumbers" ng-value="{{options.displayNumber}}">{{displayNumber}}</md-option>
    </md-select>

**Comment by OlsonDev** [comment]
`placeholder="Number"` did nothing.

Do you mean something like this?
```html
<md-input-container>
    <label>Number</label>
    <md-select flex="10" class="md-primary" ng-model="options.selectedDisplayNumber" aria-label="Display number">
        <md-option ng-repeat="displayNumber in availableDisplayNumbers" ng-value="{{options.displayNumber}}">{{displayNumber}}</md-option>
    </md-select>
 </md-input-container>
```

**Comment by Masadow** [comment]
Oh it changed again, your syntax is right. This is weird that placeholders are working for me then

**Comment by Masadow** [comment]
@OlsonDev Did you try to put a placeholder with `md-input-container` ? For me, it works as if I were using `placeholder="Placeholder"`. So it looks disabled all the time

**Comment by OlsonDev** [comment]
`<md-input-container placeholder="Test">` does nothing even if I remove `<label>Number</label>`. However, with the `<label>` in place, it looks greyed out because it's getting this CSS applied to it:

```css
md-select .md-select-value.md-select-placeholder {
  color: rgba(0,0,0,0.26);
}
```

**Comment by Masadow** [comment]
The placeholder attribute should be placed on the md-select tag

I know that there is a gray color applied to it through css, still, it's a mistake to use the same gray as disabled

**Comment by OlsonDev** [comment]
Ah, `placeholder` on `<md-select>` behaved the same. Grey/disabled looking text.
