### ISSUE TITLE
Disabled md-slider thumb opacity

### ISSUE THREAD

**Issue by OlsonDev** [angular/material#3798]
According to the [design guidelines](https://www.google.com/design/spec/components/sliders.html#sliders-continuous-slider), the thumb should be solid (not transparent) even in the disabled state.

Their screenshot:
![components_sliders_continuous1](https://cloud.githubusercontent.com/assets/308072/8760218/38e4e3ca-2cd5-11e5-841e-ee5dc4389f16.png)

What I'm seeing (@ 4X zoom):
![md-slider-disabled](https://cloud.githubusercontent.com/assets/308072/8760220/472d0df4-2cd5-11e5-90fe-81c38045a92b.png)

**Comment by EladBezalel** [comment]
already working

**Comment by OlsonDev** [comment]
I just looked at the [demo page](https://material.angularjs.org/latest/demo/slider) and it's not "working".
