### ISSUE TITLE
md-content doesn't render on Internet Explorer

### ISSUE THREAD

**Issue by ttruongatl** [angular/material#3799]
Dear,

I have seen a problem on Internet Explorer 11 about md-content. All elements in md-content did not render on IE 11 because overflow attribute in md-content has been set auto (in this case, it means hidden). I changed this attribute to visible, it's good on IE 11 now.
```css
md-content{
    overflow: visible;
}
```
Is this bug on IE11? Please tell me your ideas. 
Thank you,

**Comment by maku** [comment]
I have the same behaviour - md-content does not work on IE 11

**Comment by NickBolles** [comment]
https://material.angularjs.org/latest/#/demo/material.components.toolbar
the content there works fine for me in IE 11. Are you sure there isnt something messed up with the layout of your page? issues with the `layout` and `flex` attributes seem to be common in these issues.

**Comment by vagabondtt1503** [comment]
I saw my problem. I added flex in md-content directive and I saw the problem as the same above.

<md-content flex>
</md-content flex>

I removed flex and It works now.

Thanks for your suggestion.

**Comment by shanecarmody** [comment]
Even removing the `flex` directive didn't work for me. I had to apply the `layout-fill` directive to `<md-content>` in order for it to work in IE11. For the moment, it works...

**Comment by doddanagouda** [comment]
hi 
i removed flex on md0content but it's not working in IE11 
and also i added layout-fill to md-content it's also not working 

is this bug or any others have idea please let me know

**Comment by doddanagouda** [comment]
hi 
i removed flex on md0content but it's not working in IE11 
and also i added layout-fill to md-content it's also not working 

is this bug or any others have idea please let me know

**Comment by amonsot890** [comment]
good day,

 md-content is not working in IE11, i followed your answers and got no good results after. can anyone help me and all the others who currently have problem with md-content in IE11? please let us know. 

thanks in advance.

**Comment by codymikol** [comment]
We use md-content a lot in our application and test frequently in IE 11 and have never had this issue.

Here is a screenshot of the md-content demo working in the current version in IE 11.

![image](https://user-images.githubusercontent.com/13606342/43496608-3c0b0e92-950c-11e8-878b-4f0d7f23aec4.png)

**Comment by Splaktar** [comment]
Thanks @codymikol. I'm going to close this old issue. If anyone is still having problems with `md-content` in IE 11, please submit a new issue with a CodePen reproduction.
