### ISSUE TITLE
md-autocomplete ng-messages bug

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3801]
md-autocomplete with ng-messages no longer seems to be working. looking at the generated html, the name attribute is not being placed onto the input element.

**Comment by gpopovic** [comment]
+1

Also duplicate, #5896

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
