### ISSUE TITLE
md-autocomplete 'searching' progress bar not displaying

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3802]
I am using an`md-autocomplete` to search for data that is returned from a promise. Looking at the demo a progress bar is displayed during the search but this is not appearing on master.

**Comment by yigaldviri** [comment]
+1.
The behavior isn't consistent. sometime I see the progress-bar and sometime don't.

**Comment by mikedobrin** [comment]
+1 same for me here, I have noticed that once I hide and then autocomplete again, then focus on the value I have typed - I get this loading indicator.

I'm using 0.10.1-rc4 but the issue is reproduced on rc3 as well

**Comment by gabguy** [comment]
+1 Md-autocomplete progressbar (the linear one) not animating on the first character when the search is an async request. On the rest of the characters the loading animation does appear

**Comment by lillylykho** [comment]
+ 1 
I have the same behavior on my autocomplete

**Comment by macdasi** [comment]
+1
I have the same behavior on my autocomplete

**Comment by r0b-** [comment]
+1 
(0.10.1-rc5)
