### ISSUE TITLE
md-fab-actions display without hovering on md-fab-trigger

### ISSUE THREAD

**Issue by andela-omesanni** [angular/material#3803]
I noticed that without hovering on the md-fab-trigger button, if hover my cursor on the area where the md-fab-actions are positioned, they unhide themselves. This causes issues, because if say i have an md-menu icon i want to click, if my md-fab-actions extend to the region of my md-menu, as soon as i want to try to click on the menu, the md-fab-actions appear and so i cannot click on the md-menu icon.

**Comment by bdteo** [comment]
I confirm that hovering on md-fab-speed-dial makes elements visible even if there is no md-fab-trigger element.

**Comment by silverprize** [comment]
I have experienced the same problem.
Checkout please.
- [video](https://drive.google.com/open?id=0BxDXoXCevyJKZnBKMlJjQy1kUzA)
- [site](http://silverprize.github.io/materialdrive)

**Comment by topherfangio** [comment]
This was the intended behavior as Google Inbox does the same thing (if you hover the area of the speed dial, the actions appear). However, it has been requested by many to make this configurable and will be added soon.

Please track this issue and add comments to #3214 as it has more info/thoughts.
