### ISSUE TITLE
md-select Enhancement for Touch Screens

### ISSUE THREAD

**Issue by Stexxen** [angular/material#3806]
http://codepen.io/Stexxen/pen/QbBmRb

Once the Dropdown is open, and the finger is touched to the screen, the current item is highlighted, and when the finger is lifted the highlighted item is selected.

But any vertical or horizontal finger movement, even if just a few pixels, (just rolling the finger slightly will trigger it) will cause the element to not select the item when the finger is lifted.

ideally it should have some fuzzyness, to check if it was a real move/drag, or just an involuntary movement.

**Comment by rschmukler** [comment]
On mobile we might want to have a native select element that we hide but focus when the user clicks on our select. Then, when you click on the select the native OS implementation appears which may be a better UX than trying to adapt the select to mobile.
