### ISSUE TITLE
SideNav: toggle() issue dont open, only over 3/4 clicks

### ISSUE THREAD

**Issue by marcoriesco** [angular/material#3808]
I am developing with angular an admin, and resources I'm using Angular Material sidenav.

I could make the menu work 50%, can not do the toggle function normally.

Test case, click several times on the toggle menu it opens :D

Follows a problem Plunker:

http://embed.plnkr.co/fq3tonZoddSSZkyAaWD8/preview

Editable Plunker:

http://plnkr.co/edit/FQcZrwYlh4LPKuje9mLI?p=preview

**Comment by marcoriesco** [comment]
**UPDATED and RESOLVED:**

In template menu-toggle.tpl.html, change this:

    <ul ng-show="isOpen()" id="menu-{{sectionmenu.title | nospace}}" class="menu-toggle-list">
    	<li ng-repeat="page in sectionmenu.pages">
        	<menu-link sectionmenu="page"></menu-link>
      	</li>
    </ul>

for this:

    <ul id="menu-{{sectionmenu.title | nospace}}" class="menu-toggle-list">
    	<li ng-repeat="page in sectionmenu.pages">
        	<menu-link sectionmenu="page"></menu-link>
      	</li>
    </ul>

**Comment by EladBezalel** [comment]
What's your browser, version and os.
Couldn't reproduce on Chrome, Version 45.0.2454.101 m, Windows 10
