### ISSUE TITLE
Question: How I connect a menu to the toolbar?

### ISSUE THREAD

**Issue by blockjon** [angular/material#3809]
Looking for an example of how I can open some kind of navigation when the users clicks on a toolbar drawer icon. 

In other words, when the user clicks the 3 horizontal lines in the top of the toolbar:
https://material.angularjs.org/latest/#/demo/material.components.toolbar

I would like to open some kind of navigational element. I haven't found an example of how to do this in the guides.

**Comment by Poorchop** [comment]
There are a few examples of how to do this, most notably in the starter project and some Codepens.

In your template, add your click handler to your md-button element:
```html
<md-button ng-click="app.toggleSidenav('left')" aria-label="Menu">
  <md-icon md-svg-icon="menu"></md-icon>
</md-button>
```
In your controller, add the function to handle the click event:
```javascript
(function () {
  "use strict";

  angular.module("myApp")
  .controller("AppCtrl", ["$mdSidenav", function ($mdSidenav) {
    this.toggleSidenav = function (menuId) {
      $mdSidenav(menuId).toggle();
    };
  }]);
})();
```
Don't forget to add `ng-controller="AppCtrl as app"` where it's needed.

**Comment by NickBolles** [comment]
I made a directive to do this. You use it like so `<md-button toggle-side-nav="SideNavId"></md-button>`

For my project I have it defaulting to 'sideNav' for the id. Makes life simpler.

```
.directive('toggleSideNav', ['$mdSidenav', function ($mdSidenav) {
        return {
            restrict: 'A',
            link: function ($scope, element, attrs, ctrl) {
                element.on('click', function(e){
                    var id = attrs.toggleSideNav || 'sideNav';
                    $mdSidenav(id).toggle();
                });
            }
        };
    }
```
