### ISSUE TITLE
md-autocomplete shows uknown error (e.textChange is not a function)

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#3810]
this error shows on the log when i open the view that contains the `autocomplete`, also when i type text on the input.

this is how i have configured `autocomplete`
```html
<md-autocomplete md-selected-item="task.temp.user" md-search-text="task.temp.searchText" md-items="user in task.users" md-item-text="user.username">
	<span md-highlight-text="task.temp.searchText">{{user.username}}</span>
</md-autocomplete>
```

the controller only has 2 vars. one is the temporal data that i am not going to use for now (i don't know if autocomplete really depends on `md-search-text`) and users is a query from `$resource`

**Comment by mrichar1** [comment]
See https://github.com/angular/material/issues/3388
