### ISSUE TITLE
md-scroll-shrink scroll height problem

### ISSUE THREAD

**Issue by vncnz** [angular/material#3811]
if the height of the container is greater than the height of the list but it is less than the height of the list more height of the toolbar last element is partially or totally hidden. I tested with Safari 8.0.7 and Firefox 39 (OSX Yosemite, 10.10.4) and Chrome 43.0.2357.134m (Windows 7).

[HERE](http://codepen.io/vncnz/pen/bdjjpQ) a codepen.

**Comment by ianchenguo** [comment]
+1

**Comment by Todd-Werelius** [comment]
+1 --- Look at the bottom scroll thumb

![scrollbar-shrink-problem](https://cloud.githubusercontent.com/assets/5982829/11250469/707627fa-8de1-11e5-8fc0-6c71a661bd38.gif)

**Comment by mackelito** [comment]
+1
