### ISSUE TITLE
md-select is broken in firefox in v0.10.1-rc2

### ISSUE THREAD

**Issue by alirezamirian** [angular/material#3812]
When select menus gets open, it's not possible to select any item, and even it's not possible to close the menu by clicking outside. 
It seems to be a kind of z-index issue and I haven't investigated the possible cause yet, but the issue exist in [documentation](https://material.angularjs.org/0.10.1-rc2/#/demo/material.components.select).

**Comment by ThomasBurleson** [comment]
Duplicate https://github.com/angular/material/issues/3780
