### ISSUE TITLE
When using md-select with model and the initial model value is an integer - causes form model to be dirty

### ISSUE THREAD

**Issue by dani3l** [angular/material#3814]
Hi guys
I noticed that when I use md-select inside a form with integer value it causes both the select and form to be dirty.
This doesn't happend if the value is a string.

Not sure it it's an angular or material bug but I have no time to check it, so I $timeout(form.$setPristine) for now.

I'm using [ngMaterial v0.10.1-rc2-master-d6a938e], [angular v1.4.4-build.4117+sha.1cb6bd4]

**Comment by rschmukler** [comment]
Could reference #3933

**Comment by rschmukler** [comment]
Per [this demo](http://codepen.io/rschmukler/pen/yYGgam/) this appears to be working on master. Please open a new issue with a demo if this is not the case.
