### ISSUE TITLE
$mdMedia as a directive wrapper

### ISSUE THREAD

**Issue by wlingke** [angular/material#3815]
There are many cases where I'd like to specify a certain class based on the screen size. It would be super convenient if we could do something like:

`<div md-class-sm="small-class" md-class-gt-sm="gt-sm-class">stuff</div>`

And yes, I know that I can do this with ng-class or write my own directive, but I thought it was a common enough use case that it should be supported out of the box.

**Comment by ThomasBurleson** [comment]
A Pull Request for this feature would be welcomed.

**Comment by STOpandthink** [comment]
I really wanted this too, but then realized that in most cases you'll have multiple identical checks for "gt-sm", for example, but really you should have a variable, e.g. isSingleColumn, that you set, and then check that variable. It actually leads to better code and readability.
But yes, for prototype development, this would be nice to have.

**Comment by ThomasBurleson** [comment]
Thx to @DevVersion for reminding me this feature was already available. See [CodePen](http://codepen.io/team/AngularMaterial/pen/YweVWZ)

```html
<md-card ng-repeat="it in products.catalog" flex="22" flex-sm="46" flex-xs="80" ng-class="{shaded:$mdMedia('xs') }">
```

```js
angular.controller('ProductController', function( $scope, $products, $mdMedia) {
    $scope.$mdMedia           = $mdMedia;
}
```
