### ISSUE TITLE
Documentation Attribute Table on Mobile

### ISSUE THREAD

**Issue by NickBolles** [angular/material#3817]
The documentation websites attribute table doesn't display well on mobile browsers (well at least not chrome 43 on Android 5.02) 
You can't read the attribute descriptions on mobile.

This is a screenshot of 
https://material.angularjs.org/latest/#/api/material.components.slider/directive/mdSlider

![quickmemo _2015-07-19-20-05-06](https://cloud.githubusercontent.com/assets/7891759/8768817/8bfb9ed6-2e52-11e5-8282-886d27c1210f.png)

**Comment by naomiblack** [comment]
This would be nice to do, but probably will not happen before 1.0.

**Comment by NickBolles** [comment]
For now would it be possible to remove the `md-scroll-y` attribute on the `<md-content ng-view...>` element so that mobile users can scroll over to see the rest of the table? currently `md-scroll-x` sets `overflow-x` to `hidden`.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (411/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:55155)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZW-001Z3e-Jc
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:04 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=exevJ+beDvB+wxS5ku6d08lLuSs=; b=Z5GwYsGQ7nv7iFg+
	RktMMZAM0MyKdJEKkp4gjSSsgIfPzgDCkY5LgLO/CRfllu9wX8TgWLGAd2v2PlTA
	2bw7OpWBzKtfa618mPy+46lZ+NmHJ2mwLoeOzH72MZ0yGmbnC8DC88v4m3a+hfnT
	mwmAP571i2lKsy6AC08j99ar/xg=
Received: by filter0650p1mdw1.sendgrid.net with SMTP id filter0650p1mdw1.21662.5722729D37
        2016-04-28 20:29:17.956035941 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id jZqa8X6hSBiokVaQkz-txg
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:18.021 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:17 -0700
