### ISSUE TITLE
Issue with md-menu inside md-dialog

### ISSUE THREAD

**Issue by no-more** [angular/material#3821]
Hi,

I have a strange issue, when putting a md-menu inside a md-dialog element it will close the dialog when I open the menu, the menu shows briefly and then is closed too.

I have this issue for some time now, but not always, this may be related to the master version I'm using. I currently have this with the last master release.

Thanks.

**Comment by no-more** [comment]
I may have found something about this issue, it seems to be related to the form. if I put the menu element out of the form I don't have the issue any more.

**Comment by Smolations** [comment]
Thanks for posting back your solutions, @no-more. I _just_ encountered the same issue and was getting frustrated.  :+1:
