### ISSUE TITLE
Error in the console when you close the md-bottom-sheet with ESC

### ISSUE THREAD

**Issue by lcpereira** [angular/material#3822]
Hi,

When you press the ESC key when the md-bottom-sheet is open, it is closed, however, generates an error in the log as print. What's the impact?

Thanks.
![print](https://cloud.githubusercontent.com/assets/10385917/8774737/ab794cda-2eb7-11e5-95ec-26deb869d248.png)

**Comment by dani3l** [comment]
happens also in dialogs

and when using md-select i get:
TypeError: Cannot read property 'remove' of undefined

`interim.remove(reason || true, false).catch(function( reason ) { $log.error("InterimElement.hide() error: " + reason ); });`
