### ISSUE TITLE
Cannot read property 'tagName' of undefined in Autocomplete

### ISSUE THREAD

**Issue by wlingke** [angular/material#3824]
In 10.0.1-rc2 (and previous versions), when I first enter a character, I get the error "Cannot read property 'tagName' of undefined" caused by the Icon class in line 7998 (and later 8003). I think you can just check for the existence of `el` to avoid this issue.

**Comment by robertmesserle** [comment]
@wlingke Is this still an issue?  If so, can you please create a CodePen demonstrating how to recreate?

The only instance of `el.tagName` I found was in `md-icon`

**Comment by robertmesserle** [comment]
Added a check for `el` before checking `el.tagName` - closing.  Please reply if this issue still exists.
