### ISSUE TITLE
md-select in md-dialog - unable to navigate with keyboard

### ISSUE THREAD

**Issue by NeoRyu777** [angular/material#3827]
When I have an md-select within an md-dialog, the md-select does open the list of options, and I can click on them and otherwise operate the md-select with the mouse....

But oddly, I can't seem to use the keyboard to select from the list of options. This only seems to happen within an md-dialog.

**Comment by rschmukler** [comment]
This now works properly, although escape was causing it to close both the dialog and the select. That is now also fixed.
