### ISSUE TITLE
$mdDialog backdrop not filling screen in HEAD

### ISSUE THREAD

**Issue by wlingke** [angular/material#3829]
See example:

http://plnkr.co/edit/UiFCBSoKFYfsrBLjCaLS?p=preview

**Comment by mckenzielong** [comment]
If you use md-content along with layout tags, this problem doesn't happen (in Chrome at least.)  See: http://plnkr.co/edit/wfmFpveM1G7IKNeQ7uNf?p=preview

Related / dupe: https://github.com/angular/material/issues/3774

**Comment by wlingke** [comment]
Perfect. I'll let the contributors decide if they want to close this or leave it as an issue.

**Comment by naomiblack** [comment]
This is fixed in master
