### ISSUE TITLE
Cannot find $mdToast element in tests

### ISSUE THREAD

**Issue by davidlmiller21** [angular/material#3830]
I have some interactions with $mdToast that I need to test, but I can't seem to find the `<md-toast>` on the body element. I get the body by doing `var body = angular.element(document).find('body');`, but I don't think that is where the $mdToast is placed, because I cannot find it when I do `body.find('span');`. Any suggestions?

**Comment by ajoslin** [comment]
It's placed on the $rootElement. Try `$rootElement.find('md-toast')`

**Comment by davidlmiller21** [comment]
Thanks!

**Comment by ThomasBurleson** [comment]
@davidlmiller21 - Per @ajoslin's comment, see https://github.com/angular/material/blob/master/src/components/toast/toast.spec.js#L142
