### ISSUE TITLE
figcaption tag in md-grid-tile-footer should be full width

### ISSUE THREAD

**Issue by tony0918** [angular/material#3832]
Do you guys have any plan to add the default style to `figcaption` tag?

Thanks.

**Comment by ThomasBurleson** [comment]
Can you elaborate with more details and a use case please.

**Comment by tony0918** [comment]
Sure. I am looking at the Codepen here http://codepen.io/ThomasBurleson/pen/xbYxrX
I got the CSS definition for figcaption tag.

```
md-grid-tile-footer figcaption  {
  width:100%;
}
```

Is it possible to put this definition into Angular MD CSS as the default style for figcation tag?

Thanks.

**Comment by akanimh** [comment]
+1

Been adding this manually.

**Comment by guilhermecvm** [comment]
+1, need this for aligning an icon on the left and another one on the right

**Comment by NetEvolutions** [comment]
+1, need to nicely truncate text (with ellipsis) in tile header / footer and without this it is not possible.

```css
md-grid-tile-header fig caption, 
md-grid-tile-footer fig caption { 
    width:100%
}
```
For now i am adding this manually.

**Comment by Todd-Werelius** [comment]
+1 on this

**Comment by yuanstanley** [comment]
+1

On a sidenote, is there an easy way to aligning one icon on the left and one on the right? I've just resorted to flexing each of them to small percentages. (Have just started using angular md and not sure if I'm missing something). @guilhermecvm maybe?

**Comment by Todd-Werelius** [comment]
You pretty much have to provide some custom CSS to make these spec compliant, so no simple way. 

I hacked something together awhile ago (Pen)[http://codepen.io/Mopholo/pen/KdrJyx?editors=100], it works but it could be optimized a bit.
