### ISSUE TITLE
flexbox layout doesn't work in IE10

### ISSUE THREAD

**Issue by simoneb** [angular/material#3834]
It seems that flexbox layout doesn't work in IE 10, is this a known issue? Basically, elements don't expand to take up as much space as they should.

**Comment by pavankumarkatakam** [comment]
Im also wondering about that, so i just googled that is flexbox support in IE 10, then i came up this [site](http://caniuse.com/#feat=flexbox) , IE10 has only partial support of flexbox. You can see the supported browsers list in abouve mentioned site.

**Comment by csvan** [comment]
If this is true it is extremely serious. We recently ran cross-browser testing of an angular-material app under development, and were surprised to see how much it broke under IE (there were not nearly as many issues in any other browser). Are there any known ways to work around this?

**Comment by simoneb** [comment]
It's a serious issue indeed. angular-material is supposed to support browser versions n-1, which is a strict requirement already, but this means it currently supports IE version n, being 11 the latest (for now)

**Comment by robertbaker** [comment]
Edge is considered the latest (it will be released July 29th with W10), so IE 11 is n-1.

That sucks you guys need to support IE10 (IE11 isn't fun either). I rather see the team focus on features and fixes w/o worrying about IE 10 which is 3 years old and has ~5% market share.

It's only a serious issue if your forced to support it. Best workaround is having your client update to a better browser. No good reason someone must use IE.

**Comment by simoneb** [comment]
@robertbaker Couldn't agree more, but it's not my call unluckily

**Comment by kymdusting** [comment]
If you still need to support IE10 with angular-material I've had a little bit of success by targeting IE9 and IE10 with the following:

/* IE9 and IE10 rule sets go here, although IE9 is dead to angular material because no flexbox */
// http://www.impressivewebs.com/ie10-css-hacks/
@media screen and (min-width:0\0) {
	// Seems to fix flexbox type layout issues in IE10
	span[flex], md-card-content, md-dialog-content {
		display: block;
	}
}

**Comment by ThomasBurleson** [comment]
@kymdusting - Angular Material is not supported in IE9.  [Layout improvements](https://github.com/angular/material/blob/master/src/core/services/layout/layout.js) (to be released today with 0.11) should resolve many IE performance and rendering issues

**Comment by itamark** [comment]
@ThomasBurleson awesome - do you know when today it's being released?

**Comment by gflarity** [comment]
Thanks @kymdusting this hack saved me a bunch of time.

FYI, I upgraded to v0.11.0 I still see issues with padding et showing up unless I use @kymdusting's hack.

**Comment by hectorgr** [comment]
thanks @kymdusting I fixed it!
1. I added a conditional comment for add a class
<script>if (/*@cc_on!@*/false) {document.documentElement.className+=' ie10';}</script>

2. Then I did classes to fix the problem
.ie10 span[flex] { display: block; }
.ie10 md-dialog { padding: 0px 20px;}
.ie10 .ie10FixDivWithSidenav {
	display: inline-block;
	width: calc(100% - 280px);
}
.......
