### ISSUE TITLE
md-menu: completly broken in IE (current HEAD + 0.10.1-rc2)

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/material#3837]
After you open the menu in IE (11 + win8) you can't do anything else, the whole site gets blocked by a div and you can't select anything.

Also the alignment is completely messed up.

(You can see it on your [demo page](https://material.angularjs.org/HEAD/#/demo/material.components.menu))

![menu](http://i.imgur.com/rIXFUFz.png)

EDIT: Hit enter a bit prematurely

**Comment by jameswyse** [comment]
I tried the master branch this morning and saw the same thing in Chrome.. I thought it was a backdrop/z-index issue because my menu was inside a sidenav, but i also noticed `md-clickable` was missing from the buttons.

**Comment by stefan-schweiger** [comment]
Also does not work with 0.10.1-rc3.

Weirdly enough I can't reproduce this in a codepen, but on the demo page and also in my own project it's broken.

**Comment by clshortfuse** [comment]
Same issue as https://github.com/angular/material/issues/3892

The reason why it's hard to reproduce is because it only happens if the animation takes longer than 370ms, which isn't always. IE's JS engine is probably too slow to animate in 370ms on your machine.

**Comment by sheepsheerin** [comment]
Hi, I know this issue is closed, but just wanted to check if the alignment part of the issue is being tracked somewhere? It is still happening with the latest release on the demo site in IE11 https://material.angularjs.org/latest/demo/menu
