### ISSUE TITLE
Horizental Scrollbar for Moments when Left Navbar Toggles

### ISSUE THREAD

**Issue by khatamnejad** [angular/material#3838]
The problem can be seen [here](http://codepen.io/pen). When the "Toggle Right" link is clicked, the horizontal scrollbar can be seen at the bottom of the screen for a moment.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.
