### ISSUE TITLE
build: Publish version # for Material

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#3842]
Angular provides `angular.version` and `angular.version.minor` features to easily determine/introspect the loaded version of Angular.JS.

Angular Material should provide a similar feature and inject that into angular; accessiable via `angular.material.version`.

**Comment by ThomasBurleson** [comment]
@petebacondarwin - your thoughts on the above ?

**Comment by jelbourn** [comment]
I've actually considered this before, and was planning on doing this for the Angular 2. If @petebacondarwin and @IgorMinar are okay with us appending the the `angular` object, I'm all for it.

**Comment by petebacondarwin** [comment]
Alternatively you could have a `$materialVersion` "const" injectable?
That way we are not polluting the `angular` namespace.

**Comment by petebacondarwin** [comment]
Or perhaps we should have a cleaner API provided by angular. For instance if we had a way of accessing metadata about a module that was loaded then we could get it from there:

```
angular.info('ngMaterial').version;
```

**Comment by robertmesserle** [comment]
I like that suggestion about `angular.info`.  I don't think an injectable
would be nearly as valuable as a way that anybody could jump into the
console and check the versions.

On Tue, Jul 21, 2015 at 9:36 AM, Pete Bacon Darwin <notifications@github.com

**Comment by petebacondarwin** [comment]
I would be happy to merge a PR for `angular.info(moduleName)` or some similar better name. @IgorMinar what do you think?

**Comment by jelbourn** [comment]
A small problem with something like an `angular.info` for ng-material is that users may not always be using the entire library, and instead using individual components (`material.core` with `material.components.button`, etc.). The info could be on the core, but then people have to know there _is_ a core.

**Comment by ThomasBurleson** [comment]
@petebacondarwin: :+1:  for  `angular.info('ngMaterial').version;`

**Comment by petebacondarwin** [comment]
@jelbourn - we could put the version in all the modules (and at least in `material.core`)

**Comment by robertmesserle** [comment]
@petebacondarwin @IgorMinar Would it make sense to provide an API for components to add their version info to the `angular.version` object?  It would be nice if you could log out `angular.version` and see a full listing of components that choose to register their version info somewhere in that object.

**Comment by ThomasBurleson** [comment]
Since every component requires material.core; I think a single module version # is sufficient.
How can different components have different versions? That would be a nightmare...

**Comment by petebacondarwin** [comment]
I created a PR for the `angular.info` idea at https://github.com/angular/angular.js/pull/12465. Please go and comment.

**Comment by jelbourn** [comment]
Closed via 17f4bf49b268b473619b2253b009e721b13cd797
