### ISSUE TITLE
md-tabs produce overlapping labels on small screens until a user clicks a tab

### ISSUE THREAD

**Issue by heavysixer** [angular/material#3843]
Here is a codepen forked from your default demo:
http://codepen.io/heavysixer/full/oXPWaj/

If you resize the browser to a small window and reload you'll see the labels overlap one another. If you click the default tab they will align correctly:

![screen shot 2015-07-21 at 11 53 08 am](https://cloud.githubusercontent.com/assets/123/8806985/16bda2d8-2f9f-11e5-9368-647dd07ae2f3.png)

**Comment by newmanw** [comment]
+1, exact same problem

**Comment by mtdegoes** [comment]
+1, same issue

**Comment by robertmesserle** [comment]
This is resolved in 0.11.2
