### ISSUE TITLE
mdChips mdAutocomplete demo uses custom filter instead of angular search

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#3849]
https://material.angularjs.org/0.10.1-rc2/#/demo/material.components.chips has a demo of custom inputs, specifically one where mdChips has mdAutocomplete built into it. When I look into the mdAutocomplete "filter" code, I notice that it uses a custom filter function. Is it not possible to use AngularJS's search filter by doing `item in items | search:searchText`?

**Comment by typotter** [comment]
The "custom filter function" exists so that search results are cached. Can you please explain your motivation for wanting to use search:searchText?
