### ISSUE TITLE
Versioning and breaking changes

### ISSUE THREAD

**Issue by e-oz** [angular/material#3852]
I like breaking changes as much as you like them, trust me.
But in next "PATCH" number upgrade (0.10.0 - 0.10.1) you are going to include so many breaking changes... I kindly ask you to consider increase at least second version number (0.11).
http://semver.org/

**Comment by ilanbiala** [comment]
@ThomasBurleson why was this closed with no comment? This is a completely valid concern and it has been happening almost every release.
