### ISSUE TITLE
md-tabs don't paginate on window resize. 

### ISSUE THREAD

**Issue by giriprashaad** [angular/material#3854]
Using angular 1.4.3 with angular material 0.10.0, the md-tabs does not paginate with arrows when the number of the tabs are more than the available space. Reverting Angular version to 1.3.15 as per the demo website works again.

Codepen
http://codepen.io/anon/pen/XbPZNx

Try changing the version of angular.min.js to 1.3.15 and resize the window, we should be able to see the arrows on paginating tabs.

**Comment by andreialecu** [comment]
If you add `md-no-pagination="false"` it will work, I'm not sure why the default changed.

**Comment by giriprashaad** [comment]
Thanks @andreialecu. That works.

**Comment by deltaepsilon** [comment]
@giriprashaad This drove me crazy for a while too. The changed default feels like more of a bug, but this one should probably be closed.

**Comment by giriprashaad** [comment]
as @andreialecusaid above, this has needs to be documented and isn't a bug anymore. Closing the issue.

**Comment by ThomasBurleson** [comment]
Re-opening to either document this change **or** re-establish the original default intent.

**Comment by robertmesserle** [comment]
This appears to be resolved - closing.
