### ISSUE TITLE
mdChips $dirty state

### ISSUE THREAD

**Issue by rgolea** [angular/material#3855]
Found a small bug and quite easy to fix, I think. mdChips should set the field and the form dirty whenever you click on the remove button. Check that out. Thank you!

P.D.: Keep up the good work!

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (410/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:13139)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZW-001Z3O-F5
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:04 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=JL1gFYIR8nwg1TT27cx01xUVQnc=; b=TZj/ScEoJ5Jd65lW
	tqyNptNDZu+hH0GZqfEYLeqOW9FaCD260OPPu0rqjSPYMPccpZNTTRGiGfVvGez1
	zN33eTwUed2BxI3qUb4qRi8ItgzynKXSkQNmICs1mGlQnNq2r2nylr8jkY6AVW4t
	+IETAXFb18AV2S4Cl0suEGWhPj4=
Received: by filter0556p1mdw1.sendgrid.net with SMTP id filter0556p1mdw1.5210.5722729C51
        2016-04-28 20:29:16.891440296 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id cIOFvERTSeGNmf-Qjh2b-g
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:16.913 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:16 -0700
