### ISSUE TITLE
content of md-tabs always has a massive right margin.

### ISSUE THREAD

**Issue by BannedForLife** [angular/material#3856]
Md-tabs cause any divs sitting in it to have a massive right margin. I am trying to display 3 items on one line within md-tab but this is currently not possible.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by naomiblack** [comment]
I believe this is fixed. If you are still seeing in HEAD, please open a new issue with a repro case in CodePen or Plunkr.
