### ISSUE TITLE
md-autocomplete wrong position if centered

### ISSUE THREAD

**Issue by SnakeME** [angular/material#3862]
Hi,

If you center the md-autocomplete input and set md-min-length to 1 then the first time the results container is opening it has the wrong position.

http://codepen.io/anon/pen/OVoajE

Make sure that if you try to reproduce the bug, you have no scrollbar on the right. The issue appears only if you have no scrollbar on the page.

![screen](https://cloud.githubusercontent.com/assets/1651752/8835598/cd2c345e-30bb-11e5-962b-288fa9244a66.jpg)

**Comment by rgolea** [comment]
What browser are you using and which version? On mac or windows? (I see it fine)

**Comment by rscottfree** [comment]
I see this on Chrome 43, Windows 8.

Probably related to https://github.com/angular/material/issues/3432. I see a scrollbar appear and `overflow-y: scroll` added to the `<body>`.

**Comment by SnakeME** [comment]
I've tested the following browsers:
Firefox 38.0.5, Internet Explorer 11.0.9600, Opera 30.0, Chrome 44.0

Please keep in mind that it only happens if there is no scrollbar on the right side of the page.

**Comment by cgatian** [comment]
Fixed?
