### ISSUE TITLE
1.4.x compatibility problem

### ISSUE THREAD

**Issue by dbwhddn10** [angular/material#3869]
initOptionalProperties method is still problem in 1.4.x with bindTocontroller: true directive option

the difference is scope.$$isolateBindings is empty in 1.4.x with bindToController: true

1.3.x http://plnkr.co/edit/Tuobbl
1.4.x http://plnkr.co/edit/7Y9ZsI

**Comment by ThomasBurleson** [comment]
@dbwhddn10 - This does not appear to be related to Angular Material. Please open a new issue on the Angular.JS Github:  **[New Issue](https://github.com/angular/angular.js/issues/new)**

> I will reopen if this issue originates from Angular Material.
