### ISSUE TITLE
circular-progress does not play well with ng-shown and / or ng-if (IE11)

### ISSUE THREAD

**Issue by janesconference** [angular/material#387]
I'm trying to show a circular progress indicator only when needed, but it seems to show only a white circle if using ng-show on the element:

This *does not* work, shows only a white circle (instead of the progress indicator) when the ng-show condition is true:

`<material-circular-progress diameter="64" style="margin: auto; position: absolute; top: 0; left: 0; bottom: 0; right: 0;" mode="determinate" ng-value="progress.getProgressPercentage()" ng-show="progress.getProgressVisibility()"></material-circular-progress>`

This *does* work, alway shows the circular progress correctly:

`<material-circular-progress diameter="64" style="margin: auto; position: absolute; top: 0; left: 0; bottom: 0; right: 0;" mode="determinate" ng-value="progress.getProgressPercentage()" ng-show="true || progress.getProgressVisibility()"></material-circular-progress>`

Also, the same thing on a *linear* progress indicator works both ways.

**Comment by amedeomar** [comment]
I tried
http://codepen.io/robertmesserle/pen/219ced023f77dd43b22bc5220d4dc093
on IE 11 but if you hide and show again the spinners you will see that the indeterminate animation become different!!

**Comment by robertmesserle** [comment]
Re-opening and tagging as IE11 bug.
