### ISSUE TITLE
md-input-container + ng-messages + animate issue

### ISSUE THREAD

**Issue by agniadzik** [angular/material#3872]
There is an issue when using ng-messages with md-input-container and ngAnimate:
when changing input quite fast, the validation error message tends to disappear forever.
The example code is here:
http://plnkr.co/edit/GtuaHsiDJ88CZZ1foha5?p=preview

just change input field value 2-3 times (enter and delete char) to make the validation pass/fail.

This does not occur when using ng-messages outside the md-input-container

**Comment by Eden-Sun** [comment]
+1
even demo page can see this issue on the  "Client Name" input validation https://material.angularjs.org/0.10.1/#/demo/material.components.input

**Comment by naomiblack** [comment]
@matsko can you have a look and assess?

**Comment by matsko** [comment]
Sure thing.

**Comment by raeffs** [comment]
this is fixed in angular: https://github.com/angular/angular.js/pull/12903

**Comment by ThomasBurleson** [comment]
Please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.7 (or greater).
