### ISSUE TITLE
md-select: md-option: cant disable?

### ISSUE THREAD

**Issue by johnSowingo** [angular/material#3874]
How do I disable an md-option but still have it visible? disable attribute does not work.

**Comment by mckenzielong** [comment]
I believe these folks want these kind of questions on [the forum](https://groups.google.com/forum/#!forum/ngmaterial).  You can use `ng-disabled` to disable options.  See this [codepen for an example](http://codepen.io/mckenzielong/pen/VLEvpP).

**Comment by johnSowingo** [comment]
I think the issue was that it does not work in 10.0. See this code pen: http://codepen.io/anon/pen/LVgbjo

Thanks for the response and tip to use the newest version via git cdn.

**Comment by rschmukler** [comment]
Closing since this is fixed on master.
