### ISSUE TITLE
Issue md-menu doesn't work after md-dialog.hide()

### ISSUE THREAD

**Issue by javadevil** [angular/material#3877]
Hi
I have problem with md-menu. it won't pop-up the menu after md-dialog hide.

ngMaterial = 0.10.0
thank you

**Comment by stefan-schweiger** [comment]
Please always try out if the bug has already been fixed in the current master (easiest way if you don't want to upgrade is to "fork" a code pen on the [demo page](https://material.angularjs.org/HEAD/#/demo/material.components.menu) by simply click on the icon on the right)

**Comment by javadevil** [comment]
Thank for your help!
I has been fixed the problem. cause of I assign $scope to md-dialog after it hide it remove $scope then md-menu won't work. my solution is using ' preserveScope:true ' at md-dialog config
