### ISSUE TITLE
ui-sref does not add href to md-tabs | Tab content uncrawlable

### ISSUE THREAD

**Issue by DaveRevay2** [angular/material#3878]
For the most part, ui-sref works with the md-tabs directive.

Unfortunately it does not add a href to the <md-tab-item> so search engines cannot crawl the tabbed content.

**Comment by blubaugha** [comment]
+1

**Comment by gpopovic** [comment]
+1 ..this is actually a big problem...because users are unable to open tab in a new window

**Comment by verkestk** [comment]
+1 ditto about opening in ctrl/cmd+click or right click to open in new tab/window. Big problem for our project too.

**Comment by verkestk** [comment]
Our current workaround is this:

```
    <md-tabs md-selected="currentTab">
      <md-tab ui-sref="root.reports.reportA">
        <md-tab-label>
          <a ui-sref="root.reports.reportA">Report A</a>
        </md-tab-label>
        <md-tab-body><div ui-view="reportA"></div></md-tab-body>
      </md-tab>
      <md-tab ui-sref="root.reports.reportB">
        <md-tab-label>
          <a ui-sref="root.reports.reportB">Report B</a>
        </md-tab-label>
        <md-tab-body><div ui-view="reportB"></div></md-tab-body>
      </md-tab>
    </md-tabs>
```

It's not perfect, but it does allow right click to open in new tab/window.
Cmd/ctrl+click opens in a new tab, but it also changes the state in the current tab. Not perfect, but better than nothing.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
