### ISSUE TITLE
putting mdMenu inside mdListItem 

### ISSUE THREAD

**Issue by vlio20** [angular/material#3880]
when putting mdMenu directive inside mdList item, the icon/button is appended below the list and not inside of the listItem.  
Here is a codepan link http://codepen.io/anon/pen/RPeGNJ?editors=100

**Comment by innerpeace0** [comment]
Bottom of text on menu items is cut off, too. Screenshot below.
![capture25892](https://cloud.githubusercontent.com/assets/12842048/8872202/eeea54e6-31c8-11e5-832e-fb4c8da41a1b.png)

**Comment by vlio20** [comment]
in what commit I can see the fix?

**Comment by ThomasBurleson** [comment]
This is a feature that must be discussed with the UX team and may be added in a post v1.0 release.

**Comment by DevVersion** [comment]
@vlio20 This is now available in `1.1.0-rc5`.

I've updated your demo to use `1.1.0-rc5`.
- http://codepen.io/DevVersion/pen/MewZKR?editors=100
