### ISSUE TITLE
Material angular 0.10.1-rc2 breaks my css layout in production Safari

### ISSUE THREAD

**Issue by ekaitzht** [angular/material#3881]
Hi,

This is very weird if I update angular-material to 0.10.1-rc2 in my heroku production enviroment in Safari but is not working.

Development version executed with "foreman start"(enviroment/development.rb config file): http://screencast.com/t/e5HOtjgdPPb
Staging server (enviroment/production.rb config file): http://screencast.com/t/FblbkPLJ

I know that this can be related with heroku. However this happen only when updated Material Angular from 0.10.1 to 0.10.1-rc2. If return to the 0.10.1 version it works! :open_mouth: 

What can be happening? Is this a bug?

Thanks

**Comment by rgolea** [comment]
sometimes it happens on `flex="100"`. Just use `flex` and use `layout="column"`

**Comment by ekaitzht** [comment]
@rgolea I am not using flex="100".

**Comment by naomiblack** [comment]
are you still seeing this with RC4?

**Comment by ekaitzht** [comment]
@naomiblack is still happening with v0.10.1-rc5.

**Comment by robertmesserle** [comment]
@ekaitzht Without being able to see the site breaking, I'm not sure I'm going to be able to help find the cause.  Is this visible somewhere so that I can debug it?

**Comment by ekaitzht** [comment]
@robertmesserle here you have http://bit.ly/1K18Xx0.

**Comment by robertmesserle** [comment]
Can you try the latest version?

https://github.com/angular/material/commit/778af934ffd0cb331660581a26446e635d898f28

I think this should take care of it for you.

**Comment by ekaitzht** [comment]
@robertmesserle  is fixed but there is a small issue. The title "murnow" is not centering. As well this is not happening in development and is not happening in firefox and chrome.

**Comment by ekaitzht** [comment]
@robertmesserle I have seen that this problem it doesn't happen if I set config.assets.debug to 'true'.(This option concatenates and minify the code in rails 4)

However if I remove  config.assets.debug to 'true' I have other problems with Safari with the layout="column" and flex="100", but not with Chrome and Firefox.

All tested with v0.10.1-rc5-master-17676e6

**Comment by kugler** [comment]
@ekaitzht Try downloading the build from the cdn - worked for me.
https://ajax.googleapis.com/ajax/libs/angular_material/0.10.1/angular-material.min.css
https://ajax.googleapis.com/ajax/libs/angular_material/0.10.1/angular-material.min.js

**Comment by ekaitzht** [comment]
@kugler I don't have any problem with 0.10.1, my problem is 0.10.1-rc versions.

**Comment by ekaitzht** [comment]
I could fix this problem it was related with rails pipeline, sorry about this. require it doesn't work properly with sass and his mixins. You must change to @import instead require

**Comment by ekaitzht** [comment]
I could fix this problem is not related with angular-material. It's related with the rails asset pipeline that doesn't work properly with require and I changed to @import.
