### ISSUE TITLE
MAJOR ISSUE: $md-dialog misplaced when window content is scrolled

### ISSUE THREAD

**Issue by kschwidder** [angular/material#3884]
The old bug of misplaced $md-dialog is back again.
We have a list of items where each item has a menu. The list is longer than the view of the window.
When scrolling the window and activating the menu which shows a dialog it is misplaced and does not reflect the scroll-position.

This bug has been fixed in earlier releases but seems to be back again.

Please provide a fix ASAP.

Great work so far !!

**Comment by vlasenko** [comment]
Work around for now:

    vm.mdDialog.show({
      parent: angular.element(document.getElementsByClassName('main')[0])

where main is the class of some element inside body, and a bit of CSS:

.md-dialog-container {
  position: fixed;
  top: 50%;
}

This is not solution of course, just a work around while waiting for the fix...

**Comment by alarrosa14** [comment]
I could fix this with a variant of the @vlasenko workaround. I added the `md-backdrop` element to the css rule to show the opaque background properly:

```
.md-dialog-container, md-backdrop {
    position: fixed;
    top: 0;
}
```

I left `parent` attribute as `angular.element(document.body)` with no issues.

**Comment by ThomasBurleson** [comment]
Fixed.
