### ISSUE TITLE
md-autocomplete: unable to select item from dropdown if minLength is 0

### ISSUE THREAD

**Issue by stephen-james** [angular/material#3885]
**Applies to:** v0.10.1-rc1, v0.10.1-rc3, others?...

**Problem:**
Given I have an autocomplete configured with a min length of 0 `md-min-length="0"`
When I focus on the input
And the dropdown list appears with all items
When I click on a suggestion item
Then the autocomplete does not select the item I just clicked.

Note: Keyboard selection works.

**Expected:**
Given I have an autocomplete configured with a min length of 0 `md-min-length="0"`
When I focus on the input
And the dropdown list appears with all items
When I click on a suggestion item
Then the autocomplete selects the item I just clicked.

**Notes:**
Investigation showed that MdAutocompleteCtrl.select was not firing

**Comment by clshortfuse** [comment]
If you need a workaround, this is what I use:

searchTextChange: function (text) {
            if (!text) {
                //force query
                $scope.mySearchElement.searchText = '';
                return;
            }
            //do work
}

on the html: 

md-search-text-change="mySearchElement.searchTextChange(mySearchElement.searchText)"
md-search-text="mySearchElement.searchText"

**Comment by stephen-james** [comment]
hey folks, please let me know if I can help by providing better example cases or more information

**Comment by topherfangio** [comment]
I'm not seeing this issue on HEAD anymore. Can you please provide a Codepen showing the problem?

You can use the [Basic Usage Demo](https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete) as a template; just click the "Edit on Codepen" button in the top right.

**Comment by robertmesserle** [comment]
Closing for now - please respond with a CodePen demo if this issue still exists.
