### ISSUE TITLE
md-menu no longer works properly on Android Chrome 

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#3888]
When you press on a menu item, the popup doesn't have focus and doesn't give the first item focus. In fact, it locks out the whole page and no mouse/touch inputs are accepted (you can still press Tab with a keyboard). You have to refresh to get touch inputs to work.

https://material.angularjs.org/0.10.1-rc3/#/demo/material.components.menu

It works fine on v0.10.0

What is interesting is using keyboard navigation on Android works fine. I tested with my bluetooth keyboard. Tabbing to the menu and pressing spacebar triggers the menu and you can use up and down to navigate and enter to select.

This is probably related to the touch/mouse event. I don't have a bluetooth mouse to test with Android, but touch doesn't work.

**Comment by sousa22** [comment]
+1

**Comment by clshortfuse** [comment]
Bigger than just Android. See https://github.com/angular/material/issues/3892
