### ISSUE TITLE
Toast too small

### ISSUE THREAD

**Issue by innerpeace0** [angular/material#3890]
In the [demo] (https://material.angularjs.org/latest/#/demo/material.components.toast), there isn't enough room in the toast so see all the text. I can't screen capture it because it vanishes too fast. 

Works fine in the codepen demo.

**Comment by naomiblack** [comment]
I'm sorry -- this isn't specific enough for me to address. It seems to work fine for me on both desktop and on mobile (small screen). Please file another issue if you are able to provide more detail.

**Comment by innerpeace0** [comment]
Got a capture.
![capture28068](https://cloud.githubusercontent.com/assets/12842048/8999942/03907114-370f-11e5-9e2d-ffe76ed886ea.png)

The others are similar.

**Comment by ThomasBurleson** [comment]
To reopen - please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by innerpeace0** [comment]
> Works fine in the codepen demo.
