### ISSUE TITLE
mdMenu sometimes blocks the entire screen

### ISSUE THREAD

**Issue by vprenner** [angular/material#3892]
I managed to reproduce this on the Angular Material demo site as well (see screenshot). 

When clicking on the menu sometimes it creates a md-backdrop element upon opening. This element covers everything and you cannot click anything anymore.

I saw this bug was reported a few times ago as well. Seems it's still there.

I manage to reproduce it in the rc3 version as well as the head version.

Steps to reproduce: just keep clicking an icon (i was clicking on the width="4" one on the bottom of the demo page). Once the menu opens, close it by clicking outside the menu. Do this a few times and the UI will be blocked by the md-menu-backdrop.

On the Angular Material demo site it happens rarely. On the site I'm working on it happens quite often (in 50% of cases cca).

Testing was done on Chrome v44.

![md-menu-bug](https://cloud.githubusercontent.com/assets/2089751/8882214/8fc92e6a-3245-11e5-9b21-4b5718ee2ad3.png)

**Comment by luclanet** [comment]
+1 Same problem for me

**Comment by clshortfuse** [comment]
Does it have focus? If it doesn't, then it's the same issue as this one I posted. I thought it was Android specific, but it might just occur often on Android?

https://github.com/angular/material/issues/3888

There were recent changes with dealing with the open animation. Maybe it's getting stuck.

**Comment by lcpereira** [comment]
Hello,

I'm having the same problem, the fix is already in the master?

Thank you.

![bug](https://cloud.githubusercontent.com/assets/10385917/8904820/112d5a0e-3439-11e5-89af-c8e2c8a5f3d0.gif)

**Comment by stevenmiles** [comment]
Having the same issue with 0.10.1-rc3 with angular 1.4.3 in my application. Just tried it in the in the documentation app and manage to reproduce it. I find much it easier to reproduce it with IE11.

**Comment by stefan-schweiger** [comment]
Relevant #3837

**Comment by KReden** [comment]
Relevant - See my update to my closed issue https://github.com/angular/material/issues/3773

**Comment by jozsi** [comment]
Still happening in 0.10.1-rc4

**Comment by ThomasBurleson** [comment]
This will be fixed within the today and committed to master.

**Comment by stefan-schweiger** [comment]
@ThomasBurleson but now everything with a ng-click on it (including md-menu) does not work in IE anymore #3943

**Comment by vprenner** [comment]
@stefan-schweiger I don't think that's it because it is broken in RC4 as well.
https://material.angularjs.org/0.10.1-rc4/#/demo/material.components.menu

Works in Microsoft Edge though :)

**Comment by ThomasBurleson** [comment]
@stefan-schweiger, @vprenner - can you confirm that this SHA af05235
 fix resolves your IE issues ?

**Comment by vprenner** [comment]
i can confirm that ng-click now works in ie11 with the build from master.
also the original issue seems to be alright.

**Comment by ThomasBurleson** [comment]
:+1:
