### ISSUE TITLE
checkbox, select: add support for ng-readonly

### ISSUE THREAD

**Issue by robertbaker** [angular/material#3895]
I would like to use ng-readonly which sets the md-select and md-checkbox to readonly but does not have the disabled styling.

**Comment by robertbaker** [comment]
@ThomasBurleson Simple enough to get it into the 0.12 milestone?

**Comment by matthiasg** [comment]
when is 1.0 expected ?

**Comment by robertbaker** [comment]
@robertmesserle since you did the disabled styling, mind taking care of this quick task :)
or
@topherfangio

**Comment by hulyav** [comment]
+ 1
the fix date?

**Comment by hulyav** [comment]
+1
What is the fix date?

**Comment by hulyav** [comment]
+1
What is the expected fix date?

**Comment by chriseyhorn** [comment]
+1

**Comment by aider** [comment]
+1

**Comment by buzzeante** [comment]
+1

**Comment by dmytroyarmak** [comment]
+1

**Comment by smurugavel** [comment]
+1

**Comment by LeoLozes** [comment]
+1

**Comment by dhruvdutt** [comment]
+1

**Comment by wtk300** [comment]
+100

**Comment by swoofer** [comment]
+1

**Comment by kievsash** [comment]
+1

**Comment by a2ron** [comment]
+1

**Comment by ThomasBurleson** [comment]
Pull Request welcome. Currently this is a low priority for our team.

**Comment by f-mon** [comment]
+1

**Comment by ruisebastiao** [comment]
+1
(i think that ng-readonly could be also applied in the md-switch )

**Comment by jamfrig** [comment]
+1000

**Comment by LeoLozes** [comment]
Any possibility of this coming back to the table? It's a pretty basic use case and doesn't seem too hard to fix (speaking from ignorance).

**Comment by tipodisimmia** [comment]
+100000

**Comment by jefferson-william** [comment]
+1

**Comment by maxrandolph** [comment]
+1

**Comment by Gietson** [comment]
+1

**Comment by Splaktar** [comment]
A pull request from the community that adds this enhancement would be welcome. This likely won't be implemented otherwise.

**Comment by codymikol** [comment]
I have a PR in the works for this.

**Comment by Splaktar** [comment]
Note that the [`ng-readonly` docs[(https://docs.angularjs.org/api/ng/directive/ngReadonly) specifically state that it is only supported for certain types of inputs. It also links to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-readonly) which state that the `readonly` attribute isn't valid for inputs of type `checkbox`. So this behavior is not supported in pure AngularJS with non-Material checkboxes.

That said, I suppose this isn't a big deal to add to Material if you simply don't want the disabled styling. However, it seems like this might be a UX problem as you could have non-interactive components on the page that look fully interactive.

Can anyone be more specific on what aspects of the 'disabled' styling they want to avoid? Is it limited to the grayed out color or also the `cursor: pointer`?

**Comment by Splaktar** [comment]
Closing as feedback has not been provided.
