### ISSUE TITLE
mdVirtualRepeat with md-start-index 0 repeats the first item multiple times

### ISSUE THREAD

**Issue by mhchen** [angular/material#3896]
Discovered when working on datepicker. When md-start-index is 0, the the first few months render as the first renderable month. When you scroll down a few months, the issue corrects itself.

Repro steps:

1. Check out branch wip/calendar and start datepicker demo.
2. Enter 3/1/1932 (first month rendered as of today July 2015. Would have to adjust if attempting to repro at a later month) into the input box.
3. Click on the calendar icon to open the calendar.

See screenshot with multiple "Mar 1932"
![unset](https://cloud.githubusercontent.com/assets/1325549/8887412/e98f633e-3235-11e5-8ddd-972f766276d7.png)

**Comment by mhchen** [comment]
@kseamon @jelbourn Please review when you're able.

**Comment by kseamon** [comment]
Is it possible to reproduce outside of the date picker? I tried by modifying the virtual repeat vertical demo and it seems to work fine. I suspect this might be an issue with the month directive.

**Comment by jelbourn** [comment]
Was a bug in the month directive. Closed via 3598e6d98fed46e2dd804ee91fe2c7a47be912c2
