### ISSUE TITLE
md-dialog and directives

### ISSUE THREAD

**Issue by lrondanini** [angular/material#3897]
Hi all,

I apologize if this is an old question but I cannot find a solution. I'm trying to include the code for a dialog inside a directive. In other words:

`$mdDialog.show({
    .....
    template: '<my-directive></my-directive>', 
   .....
})` 

and, of course, "my directive" would be

`<md-dialog>.....</md-dialog>`

The problem is that with this approach I get an error from angular-material.js at runtime (I believe it's trying to access the root node for the dialog finding the directive). The only solution is to have the full skeleton of the dialog outside "my-directive" and directly imported in $mdDialog.show(). FYI, I tried transclude=true but it's not working either.

In case you are wondering the reason for this mess, I'm trying to avoid controllers. Any suggestion? 

Thanks!

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by darlanalves** [comment]
The solution I found so far, if someone lands here from Google or Google Groups:

https://stackoverflow.com/questions/31962534/using-a-directive-as-the-md-dialog/34816085#34816085
