### ISSUE TITLE
$mdColorPalette doesn't contain costume defined palettes

### ISSUE THREAD

**Issue by dh94** [angular/material#3898]
When using
<code>
$mdThemingProvider.definePalette('awesomePalette', {....});
</code>

I had expected 'awesomePalette' to be found in  <code>$mdColorPalette</code>,
but it only contains the default color palettes

**Comment by rgolea** [comment]
You're misunderstanding the docs. You can define an `awsomePalette` and you can define whatever palette you would like. Please read the docs carefully.

**Comment by dh94** [comment]
@rgolea  ofcourse you can define any palette you want, it's just that i needed a way to access 
my costume defined palette when declaring a directive, and i thought i could use <code>$mdColorPalette</code> but now i see it's a constant.. anyways sorry for the false issue
