### ISSUE TITLE
md-content no longer scrolls correctly in Chrome 44

### ISSUE THREAD

**Issue by hodeyp** [angular/material#3901]
The latest version of Chrome (44.0.2403.107) on the mac no longer supports `md-content` overflow scrolling.

In previous versions, (as well as Safari) the `md-content` element would expand to fill the available space and overflow would scroll. In the latest version of Chrome, the `md-content` section grows to fit the child elements instead.

**Comment by hodeyp** [comment]
take a look at https://code.google.com/p/chromium/issues/detail?id=506893

This explains the new default behaviour in Chrome, it suggests adding `* {min-height:0}' to css

**Comment by dg1202** [comment]
I woke up to this same behavoir. I eventually found it was due to my use with nested ui-views with ui-router, so exactly what hodeyp links to as nested flex columns.

**Comment by goncaloneves** [comment]
@hodeyp Thanks for this !

I have changed only the flex attribute on my custom css file:
```css
[flex] {
	min-height: 0;
    min-width: 0;
}
```

**Comment by nkoterba** [comment]
@goncaloneves Thanks for the fix...working for now.

Seems related to: #4022

**Comment by topherfangio** [comment]
Do any of you have a specific example/codepen you can provide that shows exactly how it's failing in material? I'd like to make sure we get a good/performant fix in.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 303ab0dc0e695f
