### ISSUE TITLE
IE Tab Header not showing

### ISSUE THREAD

**Issue by Synturas** [angular/material#3905]
Hi,

i got a problem with md-tabs in internet explorer 11 (and maybe below). The tabs headings don't show up.

![parallels picture 1](https://cloud.githubusercontent.com/assets/8062692/8901941/3ff98d62-344d-11e5-8a0c-60212a58207b.png)

I use the sample code from the official angular material site: https://material.angularjs.org/latest/#/demo/material.components.tabs

Can anyone help me with this issue ?

**Comment by Londovir** [comment]
Can you provide a CodePen or Plnkr showing your code? I'm not having that sort of issue in IE11.

**Comment by Synturas** [comment]
I cannot provide a plnkr, because i dont even understand, what libraries are included in the example codepen.

http://codepen.io/anon/pen/doQYGY

What is angular-messages/assets-cache ?

And where is the javascript for the module ?

**Comment by cafenroy** [comment]
I have the same issue. Tabs are hiden when the screen is maximized. But they appear when the screen is smaller. I had to add (md-stretch-tabs='always') on the md-tabs element. If I add (md-center-tabs=false), the tabs show up, but the red line at the bottom is not working properly. Work on Chrome and Firefox.

I am using version 0.10.0

**Comment by ThomasBurleson** [comment]
@Splaktar - can you reproduce this with 0.11.0-rc2 or higher.

**Comment by Splaktar** [comment]
@cafenroy @Synturas can you confirm that you are seeing this problem in the CodePen [here](http://codepen.io/Splaktar/full/KdNaBL/)? This is the same CodePen linked above, just forked so that I could run it fullscreen.

It only happens when in fullscreen? What resolution are you in when this happens? What version of Windows are you running?

I'm not seeing this on Windows 10 with IE11 or Edge using a resolution 1600 x 1200 or 1152 x 864 using that CodePen in [full screen mode](http://codepen.io/Splaktar/full/KdNaBL/).

**Comment by Splaktar** [comment]
Also not seeing this on a second Windows 10 machine with 1920 x 1080 resolution.

Was this only happening for tabs? I do see that the Tab CodePen for 0.10.0 was using HTTP whereas the Tab CodePen for 0.11.0 is using HTTPS. 

With the 0.10.0 version, IE is blocking insecure content and breaking the tabs (and most of Angular Material) unless I clicked on a button to allow insecure content.

**Comment by Splaktar** [comment]
Cannot reproduce with angular 1.3.15, 1.4.6, 1.5.0-beta.1 and angular-material 0.10.0, 0.11.1, 0.11.2.

**Comment by nassoman** [comment]
mdDialog with tabs does not work with IE (<=v11) with the latest Material v0.11.4. It works with version 0.11.2.
More closely: tab labels are not visible at all and only first tab can be selected. You and see first tab label (on toolbar), if you select it with mouse.

With version 0.11.3 you can see first tab, but no others.

**Comment by Londovir** [comment]
Could possibly be related to #5593 which I just reported. I'm seeing an extra space in the mdTabs directive style binding which is completely messing up tabs for me in IE11 and Chrome, at least on a first page load. If you do things in the area with the mouse, it looks like a different set of JS kicks in and eventually updates the styles appropriately, but in the initial template the spaces are causing the tabs/labels to not appear.

**Comment by Splaktar** [comment]
@nassoman this issue is not related to tabs in a mdDialog. There is an issue related to tabs in dialogs. Your comment would be more helpful there, but also please make sure to explain the behavior that you are seeing in 1.0.0-rc2 and master, not just 0.11.x. 1.0.0-rc2 includes a ton of IE fixes.

**Comment by nassoman** [comment]
Sorry, I didn't check 1.0.0-rc2 from master - it seems to work right. Thanks
