### ISSUE TITLE
Reverse flex-direction support

### ISSUE THREAD

**Issue by WebTechnolog** [angular/material#3907]
Current flex-direction for layout is ``row`` or ``column``.
It would be great to add ``row-reverse``, ``column-reverse`` and also the same for adaptive layouts such as ``layout-sm``.
It is necessary for something like ``<div layout="row" layout-sm="row-reverse"></div>``

**Comment by mismith** [comment]
+1

**Comment by alexilyaev** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
