### ISSUE TITLE
Scrollbar created on md-select open

### ISSUE THREAD

**Issue by EricBichara** [angular/material#3908]
When viewing the options inside an <md-select/> an extra disabled vertical scrollbar is created causing content to "jump" to the left. same occurs when closing the options

**Comment by felansu** [comment]
+1 same problem

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by EricBichara** [comment]
The issue can be seen on the demo page

https://material.angularjs.org/latest/#/demo/material.components.select

Ill try to create a plunk tonight

**Comment by innerpeace0** [comment]
Additionally, clicking on one select on the [demo page] (https://material.angularjs.org/latest/#/demo/material.components.select) freezes just about everything else.

**Comment by rhnatiuk** [comment]
Seems to be fixed in HEAD (master) already.

**Comment by felansu** [comment]
thanks @rhnatiuk

**Comment by innerpeace0** [comment]
Still happening on the demo page, even after a reload, on Pale Moon (a firefox derivitive) on Linux.

**Comment by rhnatiuk** [comment]
@felansu For nothing: I have not fixed it - just interested in getting it fixed! :)
