### ISSUE TITLE
md-select label does not update on option change

### ISSUE THREAD

**Issue by no-more** [angular/material#3909]
Hi,

I have an issue with the new version of md-select. If I change the label of the current selected option (stored in a array), the change is not reflected on the already selected label. I have to open the select, in the select list the option label is correct, I can then just close the select (no need to change my selection) and I'll see the new label.

I suspect this is because the change does not trigger the label generation as it might only be done when opening the select list. But I really need this for dynamics selects.

Thanks.

**Comment by rschmukler** [comment]
@no-more can you please submit a codepen/demo of the issue that you're seeing?

**Comment by no-more** [comment]
Hi,

You can try on : http://codepen.io/anon/pen/oXJRqP

If you select a label then change the corresponding the selected label does not update until you open the select dialog.

Thanks.

**Comment by bjansen** [comment]
I have the same kind of problem: I need to show a part of the label based on a condition, like this:

```html
<md-option>Sample text <span ng-show="value > 0">({{value}})</span></md-option>
```

If I initialize my scope with `value = 0`, the condition is not applied and the resulting label is `Sample text (0)`. When I click on the select, the options are shown correctly (i.e. it hides `(0)`), but as soon as I close the menu it shows the wrong value again.
Changing `value` results in the select box not being updated unless I click on it. Here's a sample app that shows my problem: http://codepen.io/anon/pen/jbEogB

**Comment by ivan7237d** [comment]
+1

Another example: http://codepen.io/anon/pen/BojGYa?editors=101

**Comment by vapits** [comment]
This issue is actual still there in the latest stable 1.0.5 version.

**Comment by elir-copyleaks** [comment]
One possible solution is to display the select inside a directive setting the directive label from it's scope. Then ng-if'ing the directive with a different input for the label.
