### ISSUE TITLE
md-select first option has different background color even when not selected

### ISSUE THREAD

**Issue by Winsehr** [angular/material#3910]
Hello!
I don't know if it's bug or not but I have an md-select with options (it's an order by list) and when I use the tablet, the first option in the dropdown list has always a slightly different background color that the other options (the whole dropdown list has background color white but first option is light grey).
I had same problem on PC but I fixed it by having an option as default option that is selected (used ng-init for ng-model). However, this doesn't fix the problem on the tablet. I've tried to disable hovering effects but it didn't seem to solve the problem. It doesn't disappear even when you select other options in the list (I only allow one option at the time to be selected) and it looks like two options are selected. 

If you look at the example "Options with Async search" in https://material.angularjs.org/latest/#/demo/material.components.select, you see that option "Scooby Doo" looks like it's always selected.  Is there a way do delete this selection?

**Comment by rhnatiuk** [comment]
Reproduces in all PC browsers (IE11, FF, Chrome) on master (HEAD). Worse, the selected item will be reset to empty when the drop-down is open.

**Comment by rschmukler** [comment]
Per the UX teams feedback this has been resolved by switching the selected color to primary theme color while keeping the background to indicate keyboard focus.
