### ISSUE TITLE
md-autocomplete component freezes the brower when remove selected value

### ISSUE THREAD

**Issue by marcdelalonde** [angular/material#3911]
Hi,
It seems that the **md-autocomplete** component does not like when we want to remove its selected value and try to choose another one. It freezes my Chrome Brower (v. 44.0.2403.107 m).
There's no error in the console.
Thanks

**Comment by kamarouski** [comment]
+1. Have the same issue. When trying to change selected value browser is locked. 

I use angular 1.4.3, Angular Material 0.10.0

The problem here is that md-scroll-mask is not removed and rendered on top of the whole page.

**Comment by Damakus** [comment]
+1, 
Hi, 
I have same or similar issue: when I try to type text and I click the "Back button" in my browser then browser is locked.
I use angular 1.3.14, Angular Material 0.10.0, Chrome Browser (44.0.2403.89 m) or FF (39.0).
Thanks

**Comment by kamarouski** [comment]
Just updated to 0.10.1-rc4. Looks like it's fixed there.

**Comment by pavellob** [comment]
Hi,
md-autocomplete component crashed browser when I want to remove its selected value and click to another one. 
It so in Chrome Brower (v. 43.0.2357.130).
angular-material 0.10.0
angular 1.4.3
There's no error in console.
Thanks

**Comment by nishahariii** [comment]
I am using angular material version 0.11.4, and this issue still exists.
