### ISSUE TITLE
md-autocomplete locks page scroll on navigation

### ISSUE THREAD

**Issue by 4storia** [angular/material#3912]
When utilizing the ```md-selected-item-change``` attribute in ```md-autocomplete``` to trigger page navigation (a user clicks an item in the autocomplete dropdown and is navigated to another page), the scroll mask and body styles (position:fixed, etc) are never removed.

**Comment by pencilcheck** [comment]
Same thing happens to md-select as well, can't scroll sometimes even after the md-select disappears

**Comment by julbr** [comment]
+1

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.
To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by macdasi** [comment]
+1

**Comment by gabguy** [comment]
+1

**Comment by lillylykho** [comment]
I have the same problem 
+1
