### ISSUE TITLE
$mdDialog: weird bug if dialog pops when browser tab is not focused, cannot close the dialog

### ISSUE THREAD

**Issue by dani3l** [angular/material#3916]
Hi guys

I found out a weird bug - sometimes, I cannot close the dialog with .cancel() / .hide()
I noticed it happened when dialog pops when browser tab is not focused, but it doesn't happend everytime.

In addition - when the bug happens, the dialog onComplete function is not fired.

I'm using 0.10.1-rc3 and latest angular 1.4.4 (bug happens also with angular1.4.3)

---
Update:
I downgraded to 0.10.0 (and 0.10.1-rc1) and it behaves ok.
so rc2 and rc3 are buggy

---
Another issue is the dialog animation in rc3 is choppy

**Comment by Tyrannmisu** [comment]
I also experienced this issue, but i could not figure out when it occurs.
Sometimes i just cant close/hide a dialog.

**Comment by ramanathan92** [comment]
I had a problem like when i open md-dialog and close it,afterwards click event is not triggering in my page(simply nothing is working after i close dialog,again if i tries to open it is not opening)

**Comment by ThomasBurleson** [comment]
@Tyrannmisu, @ramanathan92 - please retry with the latest code base from master. Please provide a CodePen if this persists. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by ramanathan92** [comment]
Thanks @ThomasBurleson .It is my fault(my bad).Actually, I  added scope: $scope when calling dialog but forgot to add preserveScope: true.That is the reason, it is not allowing me to open dialog.

**Comment by Tyrannmisu** [comment]
I did not experience this issue in 0.10.1-rc4 and rc5 for a long time now. :)
But i will have a look on master.

**Comment by Tyrannmisu** [comment]
May be related to : https://github.com/angular/material/issues/4118

**Comment by EladBezalel** [comment]
@Tyrannmisu Can you please check it on HEAD to see if the problem still occurs?

**Comment by Tyrannmisu** [comment]
Sry i totaly forgot to post here. :see_no_evil: 
I did not experience this issue since 0.10.1-rc4 nether on HEAD nor on the official releases.
I would say its fixed.

**Comment by lexyfeito** [comment]
Good morning i am having the same exact issue right now, doesnt anyone have a fix?

**Comment by EladBezalel** [comment]
@lexyfeito please check on head, if it's still happening please post a codepen and I will reopen

**Comment by lexyfeito** [comment]
So i finally figure out the problem, event was being sent undefiened. Stupid me :)
