### ISSUE TITLE
Support side-by-side md-sidenav

### ISSUE THREAD

**Issue by calebegg** [angular/material#3917]
We'd like to use md-sidenav in our app similar to how the sidenav works on Google Inbox; it's shown next to the content on large screens, but can still be toggled on and off. This isn't currently possible with md-locked-open.

For now, we're hiding the md-backdrop on large screens and moving content aside with CSS, but it's not ideal. The sidenav tries to take focus when the page loads and we have to take it back, and various minor CSS changes could break our setup. It would be great to have first-class support for this use case (perhaps with something like md-show-as-overlay="false")

**Comment by jaitaiwan** [comment]
Was just looking for this very thing...

**Comment by nabiltntn** [comment]
what about performance ? I tried sidenav on mobile app with cordova on Nexus5 and it's kind of slow

**Comment by Nowis** [comment]
+1 , I'm looking too for a sidenav that would work the Google Inbox way.
Is this going to be implemented or do you have some solution to remplace the actual sidenav?
The md-show-as-overlay="false" is a good idea.

**Comment by mackelito** [comment]
+1

**Comment by mpeula** [comment]
+1
