### ISSUE TITLE
[Bug] Sticky sub header overlaps the layout if contained within two column layout

### ISSUE THREAD

**Issue by raftalks** [angular/material#3918]
I am working on a layout left side and right side are two columns and each one needs to have sub headers while it scrolls and gets sticked to the container. This is the expected behavior however, it seems that when scrolling, the sticky header crosses over its container and overlaps or in other words it gets fully stretched across the main container of the layout.

Here is a demonstration of the issue on this link:
http://codepen.io/anon/pen/pJQorQ?editors=100

Note that which ever left or right side I scroll, the sub header crosses over the other side.

**Comment by clshortfuse** [comment]
This happens because the subheader is using position:absolute.

Any element with position:absolute will traverse through every parent until it finds a position:relative style.

So you can do this:

http://codepen.io/anon/pen/GJwgrX?editors=100

And it'll work properly.

**Comment by raftalks** [comment]
Thanks @clshortfuse
