### ISSUE TITLE
md-dialog no longer works with $q.all()

### ISSUE THREAD

**Issue by JDGoldman** [angular/material#3919]
I have created a Dialog service which basically pops-up a "processing" md-dialog while a data service (or other promise or promises) runs.  As soon as the promise (or promises) returns, the processing dialog is supposed to hide automatically.  The Dialog service works fine with Material v 0.10.  It breaks with Material v 0.10.1-rc3 and beyond.

A Codepen of my Dialog service with methods to invoke the main functions is located here: http://codepen.io/JDGoldman/pen/ZGqjdY

The Codepen uses Material v0.10. If I try to change this to v0.10.1-rc4, there is a problem with the dialog controller when using a $q.all() syntax (you can tell because the {{ }} show up instead of text).  If you have only one promise/function, the dialog service appears to work normally.  If I pass my DialogService in to the $q.all() call as one of the parameters, the dialog service finds the controller, but the dialog never closes (since, of course, it is now waiting for itself to close).  

I assume that the newer versions of Material were not supposed to break my Dialog service.  I'm not sure exactly where this problem cropped up, but it definitely occurred after v0.10.  If I had to guess, perhaps it is caused by eliminating the dialogTransitionEnd function and $mdUtil.transitionEndPromise(dialogEl) calls, all of which returned a promise.   

Thanks for reading.  Great work on this project.  Angular Material is incredible.

**Comment by lucasmartinez** [comment]
+1
I have the same problem
