### ISSUE TITLE
Modal is not available

### ISSUE THREAD

**Issue by jeromemmiranda** [angular/material#3922]
Hi,

I am looking for a modal feature for this but I can't find any. I even checked it to https://material.angularjs.org/latest/#/.

I think dialog is different from modal. I have also checked http://materializecss.com/ and dialog and modal are different.

Thanks and Regards,
Jerome

**Comment by chinnichaitanya** [comment]
@jeromemmiranda *Dialogs* in http://materializecss.com/ are basically *Toasts* in https://material.angularjs.org/latest/#/ and similarly *Modals* in **materializecss** are *Dialogs* in **angular-material**.

**Comment by jeromemmiranda** [comment]
@chinnichaitanya oh now i got it, thank you so much for clarifying.
