### ISSUE TITLE
FAB Speed Dial iOS issue

### ISSUE THREAD

**Issue by davidedellai** [angular/material#3925]
I'm trying to use the FAB Speed Dial (here the references: https://material.angularjs.org/0.10.1-rc4/#/demo/material.components.fabSpeedDial) but i found a issue using an ipad. In every Android device works well and in every web browser too. When i try with iOS the FAB open but not close. I can't close it until tap on an action of one of the mini-fab. Is it possible solve it?

**Comment by topherfangio** [comment]
@davidedellai I'm updating the FAB speed dial with some more improvements, I'll make sure to include this too. Ideally, clicking the initial fab would toggle speed dial so that it can open/close.
