### ISSUE TITLE
mdIcon in mdListItem gets not wrapped with a button when mdListItem does not have a ngClick

### ISSUE THREAD

**Issue by JuHwon** [angular/material#3928]
If you build a `mdListItem` without a `ng-click` attribute the containing `mdIcons` with a `ng-click` attribute will not be wrapped with a `md-button` element. I think this is a strange behaviour. 

``` 
  <md-list-item ng-repeat="person in people">
    <p>{{ person.name }}</p>
    <md-icon md-svg-icon="communication:messenger" ng-click="doSecondaryAction($event)" aria-label="Open Chat" class="md-secondary md-hue-3" ng-class="{'md-primary': person.newMessage}"></md-icon>
  </md-list-item>
``` 

I would blame the if statement at line 80 in the [list.js](https://github.com/angular/material/blob/master/src/components/list/list.js)

[Here](http://codepen.io/anon/pen/EjOyVJ) is a codepen example.

**Comment by marcysutton** [comment]
Yep, that's a bug. That icon needs to be made into a button to be actionable.

**Comment by gligoran** [comment]
+1 and don't limit it to ```ngClick```. ```ngHref```, ```href```, and probably some others would be welcome additions.
