### ISSUE TITLE
md-autocomplete. ng-pattern support

### ISSUE THREAD

**Issue by kamarouski** [angular/material#3929]
Is ng-pattern supported for md-autocomplete? I'm trying to use it the same way as required, but only required works. 

I want to add a feature for users to add emails using autocomplete or enter new email. However, it's seems not possible to validate if user entered valid email at the moment.

v0.10.1-rc4

**Comment by alexilyaev** [comment]
+1

**Comment by bernizt** [comment]
+1

**Comment by alexilyaev** [comment]
@ThomasBurleson If we add `ng-pattern="$mdAutocompleteCtrl.scope.ngPattern"` under [getInputElement](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteDirective.js#L229) and the same prop in the scope bindings, wouldn't that be enough?

**Comment by chey** [comment]
What happened with this?

**Comment by Splaktar** [comment]
@chey it was closed as part of one of the old issue deprecation waves. I believe that you need to open a new issue if you need a feature like this.
