### ISSUE TITLE
md-tooltip: Animation UX

### ISSUE THREAD

**Issue by websirnik** [angular/material#3931]
This is might be an edge case, but still striving towards perfection :) I have a few icon-buttons close to each other, all have tooltips. Previously they were made via Angular-Strap. After I've migrated them to Angular Material, the experience has gotten worse a bit. When user quickly hovers through the buttons, Angular Material finishes animation early and that does not feel pleasant. Tooltip delay might partially solve the problem, but I'm curious what other people think about this case.

Letting animation finish and then fade out feels good. 

Angular-Strap
![2015-07-28 15_23_12](https://cloud.githubusercontent.com/assets/282871/8933918/08a03bae-353d-11e5-8ea9-775287f3bcf0.gif)
Angular Material
![2015-07-28 15_24_29](https://cloud.githubusercontent.com/assets/282871/8933920/0a12ad64-353d-11e5-90a4-a738981dc9c2.gif)

**Comment by clshortfuse** [comment]
I have ChromeOS and can say that the tooltips on windows that have material design do not have a ripple effect.

If I could figure out how to record my screen in ChromeOS, I'll post the animation.

**Comment by clshortfuse** [comment]
Animation: http://i.imgur.com/QUx4SgD.gif

Sorry for the slow framerate. I'll try on getting another one.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (436/400 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:56256)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZn-001Z7e-LA
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:21 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=PxEJniHFzhMshOlIVo6h/0RFZKg=; b=Cp7F8HBkoZ9RRrer
	cwV48k4nEPOzYyFq0O+qdPbcLSLGGGhn4RJDDJslxxmpLK375/iGLwI77I4UULVK
	l0Cmxeny73FOxip4ROXOgu6P/xBrSKMzYv59Olc5EbUriWPnPQjgkyGskDwXwWMp
	0zxCChAu8hl0exzd4AmCwcADNAE=
Received: by filter0556p1mdw1.sendgrid.net with SMTP id filter0556p1mdw1.5210.572272A742
        2016-04-28 20:29:27.904332417 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 2iXZzgVQTzSV_19ZUtbZHQ
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:27.934 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:27 -0700
