### ISSUE TITLE
Using 'multiple' in md-select sets form.$pristine to false by default

### ISSUE THREAD

**Issue by malaykeshav** [angular/material#3933]
Steps to recreate:
1. Create a form with md-select.
2. Add 'multiple' directive to md-select.
3. Add multiple default values to md-select's model.
When the form is loaded, its $pristine is set to false.

Example code:
http://codepen.io/anon/pen/RPqPeP

**Comment by lcortese-truelogic** [comment]
Hi guys, I thinkt that it was no correctly solved.
I found other related bug:

Develop steps:
1. add some common field (input text, etc)
2. add a md-select with multiple directive into a ng-if condition.
3. watch $dirty propertie of the current form

Test steps:
1. Populate the firsts field, it should change $dirty as true
2. enable some condition that enable the ng-if condition
3. when the md-select with multiple directive appears, the $dirty form properties is set as false

I think that this is not a correct behavior

**Comment by jmcpeak** [comment]
Having the same problem with 1.1.3

**Comment by skharel** [comment]
I am having the same problem too. Angular version 1.1.3

**Comment by cstephe** [comment]
FYI I have a fix a real fix, looking into going through a PR

https://github.com/angular/material/issues/11490

little preview
![screen shot 2018-10-17 at 12 01 12 pm](https://user-images.githubusercontent.com/311854/47109915-602c0580-d204-11e8-875d-b2c4f1e54c74.png)

**Comment by cstephe** [comment]
@rschmukler hey I'm not sure what I did that unassigned you from https://github.com/angular/material/issues/3933, not sure if that is normal

**Comment by Splaktar** [comment]
@cstephe GitHub just does that automatically when an issue is modified and the person is no longer on the team. It's certainly confusing that it gets attributed to the person who posts a comment though.
