### ISSUE TITLE
md-toolbar scroll the complete screen on android

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [angular/material#3936]
I'm running angular material on apache cordova web view and when I add the md-toolbar and the content is bigger, the complete screen scroll up. This only happens on android apache cordova web view, the same code runs ok on chrome web browser.
Cordova 5.0.0
Angular 1.3.15
Angular Material 0.9.0
I just use the sample code from website and make the content big so I can scroll. If the conent is inside `<ui-view> ` I have this problem, I test with `<ion-nav-view> ` and works fine.

```html
<html>
<body>
<md-toolbar>
  <div class="md-toolbar-tools">
    <span>My App's Title</span>
    <!-- fill up the space between left and right area -->
    <span flex></span>
    <md-button>
      Right Bar Button
    </md-button>
  </div>
</md-toolbar>
<md-content>
  <label>asdsdadasdjasjdajdanflsdnfjbaodafajdaufjafjajskjajsdf</label>
  <label>asdsdadasdjasjdajdanflsdnfjbaodafajdaufjafjajskjajsdf</label>
</md-content>
</body>
</html>
```

**Comment by ThomasBurleson** [comment]
Does this issue still exist with Angular 1.4.4 and Angular Material v0.11.0-rc2 ?

**Comment by cesar-oyarzun-m** [comment]
I updated the angular to 1.5.0 and and Angular Material v0.11.0-rc2 , the same problem is present
