### ISSUE TITLE
md-content subheading leaks to the next column

### ISSUE THREAD

**Issue by hhietanen** [angular/material#3938]
If there are two columns side bys side and the first one has a md-content with subheaders the subheader boxes hide the second column too. The subheader box should cover only the first column where the subheader is

<img width="678" alt="screenshot 2015-07-29 09 57 16" src="https://cloud.githubusercontent.com/assets/1021873/8951662/4657720a-35d8-11e5-8ffa-0cd0d4059320.png">

Here is a code pen:
http://codepen.io/anon/pen/ZGmXyX
to see the issue, scroll the first column to reveal the subheaders.

**Comment by rschmukler** [comment]
This appears fixed on master. Please re-open if this isn't the case.
