### ISSUE TITLE
Clear Button On AutoComplete

### ISSUE THREAD

**Issue by Sriram143** [angular/material#3939]
Hi There is No Clear Button if we are using Float Label in Auto Complete. it should be there in float label or normal case 

I found the button snippet in missing in autocomplete template in case of float label. please add clear button 

it should be like this

 function getInputElement() {
                        if (attr.mdFloatingLabel) {
                            return '\
            <md-input-container flex ng-if="floatingLabel">\
              <label>{{floatingLabel}}</label>\
              <input float type="search"\
                  id="{{ inputId || \'fl-input-\' + $mdAutocompleteCtrl.id }}"\
                  name="{{inputName}}"\
                  style="padding-right:26px;"\
                  autocomplete="off"\
                  ng-required="$mdAutocompleteCtrl.isRequired"\
                  ng-minlength="inputMinlength"\
                  ng-maxlength="inputMaxlength"\
                  ng-disabled="$mdAutocompleteCtrl.isDisabled"\
                  ng-model="$mdAutocompleteCtrl.scope.searchText"\
                  ng-keydown="$mdAutocompleteCtrl.keydown($event)"\
                  ng-blur="$mdAutocompleteCtrl.blur()"\
                  ng-focus="$mdAutocompleteCtrl.focus()"\
                  aria-owns="ul-{{$mdAutocompleteCtrl.id}}"\
                  aria-label="{{floatingLabel}}"\
                  aria-autocomplete="list"\
                  aria-haspopup="true"\
                  aria-activedescendant=""\
                  aria-expanded="{{!$mdAutocompleteCtrl.hidden}}"/>\
                  <button\
                        type="button"\
                        tabindex="-1"\
                        ng-if="$mdAutocompleteCtrl.scope.searchText && !$mdAutocompleteCtrl.isDisabled"\
                        ng-click="$mdAutocompleteCtrl.clear()">\
                      <md-icon md-svg-icon="md-close"></md-icon>\
                      <span class="md-visually-hidden">Clear</span>\
                  </button>\
              <div md-autocomplete-parent-scope md-autocomplete-replace>' + leftover + '</div>\
            </md-input-container>';
                        } else {
                            return '\
            <input flex type="search"\
                id="{{ inputId || \'input-\' + $mdAutocompleteCtrl.id }}"\
                name="{{inputName}}"\
                ng-if="!floatingLabel"\
                autocomplete="off"\
                ng-required="$mdAutocompleteCtrl.isRequired"\
                ng-disabled="$mdAutocompleteCtrl.isDisabled"\
                ng-model="$mdAutocompleteCtrl.scope.searchText"\
                ng-keydown="$mdAutocompleteCtrl.keydown($event)"\
                ng-blur="$mdAutocompleteCtrl.blur()"\
                ng-focus="$mdAutocompleteCtrl.focus()"\
                placeholder="{{placeholder}}"\
                aria-owns="ul-{{$mdAutocompleteCtrl.id}}"\
                aria-label="{{placeholder}}"\
                aria-autocomplete="list"\
                aria-haspopup="true"\
                aria-activedescendant=""\
                aria-expanded="{{!$mdAutocompleteCtrl.hidden}}"/>\
            <button\
                type="button"\
                tabindex="-1"\
                ng-if="$mdAutocompleteCtrl.scope.searchText && !$mdAutocompleteCtrl.isDisabled"\
                ng-click="$mdAutocompleteCtrl.clear()">\
              <md-icon md-svg-icon="md-close"></md-icon>\
              <span class="md-visually-hidden">Clear</span>\
            </button>\
                ';
                        }
                    }
                }
            };

**Comment by marcysutton** [comment]
Please put your code in a Plunker or Codepen to demonstrate the issue.

**Comment by Sriram143** [comment]
Its Simple

Floating Label Doesn't Have Clear Button and Custom Template and Basic Usage has Clear Button.

https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete


![image](https://cloud.githubusercontent.com/assets/4466654/8988323/15b43814-3703-11e5-87fa-755b2d88c460.png)

**Comment by bluebirdtech** [comment]
+1 Seems like the autocomplete should have the clear button feature, regardless of the presentation

**Comment by 91K00** [comment]
+1
Fully agree with bluebirdtech.
Clear must be present like in select.

Thanks

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (416/400 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:10642)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZf-001Z5X-NR
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:12 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=31qFBVzoSRSaxAbj01WAK9Pc4po=; b=mMxV1jeWHUGqJ224
	E2Nu2rWrv6mcJbVFWJUBZAoiZwgeIoRY8VwCFBIQIacstBm/dc405+yx5snnh1YQ
	iWU5SynqVr2Qv/bYJkFoWHNRaW4GmHU+FpHA4B+w6/DX1aBMG+VS1RJgf5b7Hi7g
	ZbkJddaVNfWhWf2B81YreSk55+o=
Received: by filter0463p1mdw1.sendgrid.net with SMTP id filter0463p1mdw1.21062.572272A631
        2016-04-28 20:29:26.511995772 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id oV4vC4EjRKyLTNP2w46fYQ
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:26.537 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:26 -0700

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (500/500 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:4460)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avsaa-000IgB-7B
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:31:08 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=e3kRv+HgVVEBVdkFYucd2eRQ/zw=; b=Xjrn6s2ZCzFDo7OP
	rdefGylDLiIA/qbIJMuImvA9VwHizluY2Ty4tSOHBamy9du+jyLXWLaCzcxmlDs9
	IdzEqueHfmHvEsE3LhWrkDVQ4L5z29Kp73eQg6Qn7hUVoXI8AxecEh6EGHEa+PbJ
	Gp2w+WH/rU+007iR/lxeN5HN8UI=
Received: by filter0837p1mdw1.sendgrid.net with SMTP id filter0837p1mdw1.16833.572272C79
        2016-04-28 20:29:59.090581869 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id btgUNUXHRp2B3zLELDW6cA
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:29:59.157 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:58 -0700
