### ISSUE TITLE
md-select breaks when used with ng-if

### ISSUE THREAD

**Issue by warpdesign** [angular/material#3940]
It seems that md-select directive doesn't work properly when `ng-if` is used on the directive: the ng-model doesn't get set in this case.

Example:
```html
    <form>
      <span>***{{selectedOption}}***</span>
      <md-select ng-model="selectedOption" placeholder="Select an element" ng-if="!hidden">
        <md-option ng-value="val" ng-repeat="val in [1,2,3]">Value: {{val}}</md-option>
      </md-select>
    </form>
```

If I remove the `ng-if` attribute, it works as expected.

This happens with 0.10.0 as well as latest version 0.10.1-rc4.

**Comment by andreaskaltenbach** [comment]
I have the same problem with ng-if on an element around the `md-select`
```xml
<div ng-if="visible">
  <md-select ng-model="lg" ng-change="changeLanguage()">
    <md-option ng-repeat="l in availableLanguages" value="{{l.locale}}"> {{l.name}}
    </md-option>
  </md-select>
</div>
```

I am running angular-material 0.11.3

**Comment by iamryandrake** [comment]
I have the same issue. Is anyone else getting this problem?

**Comment by piyushchauhan2011** [comment]
I think because `ng-if` will remove elements from DOM, it's better idea to use `ng-show` as it doesn't remove the element from DOM. 
Here is the discussion about the differences http://stackoverflow.com/questions/21869283/when-to-favor-ng-if-vs-ng-show-ng-hide

**Comment by rawbeans** [comment]
Why is this issue considered deprecated? This is a really annoying issue.

**Comment by marcelKroll** [comment]
I agree with rawbeans, why has this been closed. As far as I can tell this is still an issue in the latest version of angular material.

**Comment by tiaoshi** [comment]
My md-select, which had a ng-if at the same time, did not "open" when I triggered a click handler on it in a unit test. But after I opted to ng-show, it works fine.
