### ISSUE TITLE
angular-material breaks our app by just being included as a dependency

### ISSUE THREAD

**Issue by smashercosmo** [angular/material#3941]
Here is a simple [plunker](http://plnkr.co/edit/hJkcqYQDHySxGVOk5fxn) that illustrates an issue. We have a transcluded form with ng-repeat inside and custom validation directive on inputs. Form has an ng-show directive, but as you will see it is always hidden.

1. If you remove ngMaterial dependency everything will work.
2. If you remove transclusion directive everything will work.
3. If you remove ng-repeat directive everything will work
4. If you remove any of the custom validation directives... everything will work.

Only combination of these four causes the form to not show up.

**Comment by robertbaker** [comment]
@smashercosmo It's an issue with your directives. There is a name confict. Rename your directives that are affected and it works.

**Comment by smashercosmo** [comment]
@robertbaker no, it's not. I updated plunker with renamed (namespaced) directives. still not working.

**Comment by bolerodan** [comment]
@smashercosmo  I believe it's an issue with Angular 1.4 and angular-material specifically. I changed versions of angular 1.3.10 and it seems to work. I recall this library also having an issue with 1.4 animation and if I recall, they rolled back to require an older version of angular? Maybe someone else can chime in here.

**Comment by ThomasBurleson** [comment]
The issues that ngMaterial has with ngAnimate should all be solved once the PR https://github.com/angular/material/pull/3949 has been merged into master. 

> These fixes are scheduled for formal release with v0.11; but, of course, will be available in master... planned for merging into master next week.

**Comment by smashercosmo** [comment]
@ThomasBurleson just want you to know, I've just tested with latest master, that includes #3949, but issue is still not resolved :(

**Comment by ThomasBurleson** [comment]
@smashercosmo - this appears to be an edge-case issue with $animate and ngMaterial. See [Plunkr Demo](http://plnkr.co/edit/PpyyYMcqiD65u1ysq3ZA) and the `script.js`. 

> An has been reported to the Angular.JS team:  [$animate with ngShow is not working with Angular Material](https://github.com/angular/angular.js/issues/12519)

**Comment by ThomasBurleson** [comment]
Fixed with recent Angular.JS master build/snapshot: http://plnkr.co/edit/hQ2Q6y5Qi72fePI1VrUl?p=preview
