### ISSUE TITLE
"Assignment to read-only properties is not allowed in strict mode" on ng-click in IE since latest HEAD

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/material#3943]
The latest master (f984c29 bower-material) broke `ng-click`s in IE (11 + win8).

You can see it in the [`md-list` example](https://material.angularjs.org/HEAD/#/demo/material.components.list) when you click on the message button at the end (you will see the error in the console) and also in the [`md-menu` demo](https://material.angularjs.org/HEAD/#/demo/material.components.menu) by simply clicking on the menu

**Comment by KReden** [comment]
Related? https://github.com/angular/material/issues/3927

**Comment by ThomasBurleson** [comment]
@stefan-schweiger - can you confirm that this SHA af05235 fix resolves your IE issues ?

**Comment by stefan-schweiger** [comment]
@ThomasBurleson fixed, thank you!

**Comment by ThomasBurleson** [comment]
@stefan-schweiger :+1:
