### ISSUE TITLE
need of md-submenu

### ISSUE THREAD

**Issue by suman28** [angular/material#3944]
md-menu needs a submenu like mentioned in http://www.google.co.in/design/spec/components/menus.html#menus-menu-items.
![md-submenu](https://cloud.githubusercontent.com/assets/5011484/8958452/8f880b70-3622-11e5-8bab-6ba845fc6d0d.PNG)

**Comment by innerpeace0** [comment]
+1

**Comment by Cayan** [comment]
+1

**Comment by ThomasBurleson** [comment]
Duplicate
