### ISSUE TITLE
md-sidenav overflow hidden on parent instead of body

### ISSUE THREAD

**Issue by dmarg** [angular/material#3945]
So md-sidenav only applies "overflow: hidden" to the parent element of the md-sidenav. However, when creating a directive or nesting the side nav into another element this will not properly lock the screen when the sidenav is opened because to do that the overflow needs to be placed on the body.

Was this the initial intent? Could we possible put an option in it that could take in a parameter (ex: nested) and then the body would be locked instead of the parent?

**Comment by ThomasBurleson** [comment]
@dmarg - would you mind providing a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by dmarg** [comment]
Hi Thomas,

I made a plunker. However to get what I am talking about you will have to go to this run link because if you try to preview it, plnkr puts it in an iframe which has overflow hidden on it.  

Anyway, go to the run link (http://run.plnkr.co/plunks/9rz5D30BTyP5ujWzL68h/#/) and hit the hamburger. You will see that when the menu pops out you can still scroll on the whole page.

Then, go here to see the plnkr code (http://plnkr.co/edit/9rz5D30BTyP5ujWzL68h) and click on home.view.html and add body-lock as an attribute to the md-sidenav on line 2. Once that is done then go back to the run link (http://run.plnkr.co/plunks/9rz5D30BTyP5ujWzL68h/#/) and refresh. You will now see that the body locks properly where as it did not before.

Let me know if you have any more questions.

**Comment by dmarg** [comment]
@ThomasBurleson You may have to fork to edit the code. If so then go to the run.plnkr.co link with your plnkr tag otherwise the iframe will block the demo.

**Comment by dmarg** [comment]
@ThomasBurleson I have forked the plunker so you don't have to change it. Now one has the body-lock and one doesn't so you can see the difference.

With out body-lock: http://plnkr.co/edit/9rz5D30BTyP5ujWzL68h?p=info and see it in action here http://run.plnkr.co/plunks/9rz5D30BTyP5ujWzL68h/#/

With body-lock: http://plnkr.co/edit/3bBrC1lZP60XHVeA1kCK and see it in action here http://run.plnkr.co/plunks/3bBrC1lZP60XHVeA1kCK/#/

**Comment by dmarg** [comment]
@matsko @ThomasBurleson I have a fix for this in my plunker which is the body-lock directive I made that uses an attribute. Do you want me to submit the directive that fixes this with a body-lock attribute or do you want this to be fixed in a different way?
