### ISSUE TITLE
md-button ng-click not passing variables correctly

### ISSUE THREAD

**Issue by erslater** [angular/material#3947]
I have the following button:
```
    <md-button aria-label="Add" class="md-icon-button" ng-click="vm.add($event, '{{vm.activeSection.id}}')">
        <md-icon md-menu-origin md-font-icon="mdi mdi-plus"></md-icon>
    </md-button>
```
The function in the controller is receiving '{{vm.activeSection.id}}' as the value however looking at the element in chrome developer tools shows:
ng-click="vm.add($event, 'agencies')"

**Comment by LionC** [comment]
Note that the `ng-click` attribute is applied to the resulting `<button>`/`<a>`-element and is not modified by the `md-button`-directive. You should face the same problem when applying your `ng-click` to a simple `<button>` instead of an `<md-button>`, which would mean that this is not an angular-material problem

Passing `vm.activeSection.id` as a normal parameter seems to be the intuitive solution in your case, making it a String with `.toString()` instead of trying to evaluate it with single quotes around - is there a special reason why you want to do it this way?

**Comment by erslater** [comment]
I actually found a work around however it was a very odd situation.  Looking at the source in Chrome showed the correct markup but somehow it was passing the literal.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (412/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:56644 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZZ-001Z4Z-5p
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:07 +0200
Date: Thu, 28 Apr 2016 13:29:23 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875363;
	bh=H8n1hiioOw30J8IfpLop217TengSyMbE7m3huEyt4kQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vGnUmN01iiUb1Zt0QubY7/QaW8VE4+x18Qo3rUIKliuDBUkiehNebow3h5wJCw9OT
	 RLd0yT2u54DskN5mW50Y1A06CkoX0bR56n1BYthTA/VsNQT0QKu+B0GiTw1Z/btMBC
	 TpsFizaVkwwWm7+xSu/DMOTo4iLTl7K4nFNjgUpg=
