### ISSUE TITLE
Differences between Google Material colors definition and Angular Material themes implementation.

### ISSUE THREAD

**Issue by langley-agm** [angular/material#3948]
I've been comparing several implementations of angular material and I've had problems understanding the way angular material implements the colors definition.

http://www.google.com.mx/design/spec/style/color.html#color-color-palette

The Spec shows that each color has two different palettes, one of them is meant to be used when using that color as the primary color, the other one ( the one prefixed with A) is to be used when you want to use that color as the accent color (hence the A prefix). We can even see that darker colors don't even have an accent palette ( brown, grey, blue-grey), because darker colors are not meant to be used as accent colors.

Discrepancies I see on angular material:

1- The spec says you should only choose 3 shadows from your primary palette, one of them will be the primary shade, and the other two will be a darker and a lighter version of the same color. In angular material we have the primary color and 3 more hues, one of those hues default to an accent shade, (A100), not even a primary color shade (more on this in the next point).

2- In the same example they choose 1 accent color from the A prefixed palette (which is the shades meant as accent colors) and a lighter version of it, which in the implementation should only be same color but with an opacity (or that's what I got from the explanation as they say you should only choose one shade for the accent palette). In angular material we default these accent colors with shades from the primary palette, not the accent palette.

Another references we can compare to:

http://www.getmdl.io/customize/index.html

Material Design Lite's Theme Builder won't allow you to choose brown, grey or blue-grey colors as your accent palette, only as your primary palette.

https://www.materialpalette.com/blue-grey/pink

These other guys give you a generated palette whenever you choose two values and we can see that they only choose 3 shades from the primary value and one from the accent color.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (405/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:60089)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZJ-001Z15-Sf
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:50 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=3R9EmVoqsd/amNrVRz+R07CbHZg=; b=gf19QRyHVZcFyrK8
	r9GSSHXgfTm9DivFX+0ZqVcAYXR0af1Dkq1oNxOP0kCZMddhrl413OSdI40I2mS7
	zbz/TAfOG5QcRtFKK5OoT3iz6HTNpTL+u82tjM6c7ki9roXnWZg3rAfit/ajxcq1
	HaNvohZfFM26goF2bV1QS8oJm1g=
Received: by filter0504p1mdw1.sendgrid.net with SMTP id filter0504p1mdw1.21639.5722729166
        2016-04-28 20:29:05.934087913 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id IGujTvWxQ6exb8Ru7gCXxQ
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:06.074 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:05 -0700
