### ISSUE TITLE
Ripple effect animation inconsistent with polymer

### ISSUE THREAD

**Issue by acondiff** [angular/material#3952]
The ripple effect seems a little off when compared to polymer and buttons found across other google sites and apps. It feels a little slow and it doesn't look like the ink starts out at full opacity and fades out as seen in polymer. The button shadow appears a little off as well especially on the active state. 

Compare the buttons here:
https://material.angularjs.org/latest/#/demo/material.components.button

to the button found on this page: 
https://play.google.com/music/listen#/sulp

and in Polymer: 
https://elements.polymer-project.org/elements/paper-button?active=paper-button&view=demo:demo/index.html

This fix would help the ripple to be a little more visible when used in situations where the button parent animates off the screen for example.

**Comment by ThomasBurleson** [comment]
@robertmesserle - This is serendipitous since your are re-architecting Ripple...
