### ISSUE TITLE
Keyboard interaction with md-radio

### ISSUE THREAD

**Issue by denjello** [angular/material#3954]
When tabbing through form elements, I was surprised that I could not select a radio option with enter as I could with the select → option or the checkbox interaction methods.

I was able to use the arrow keys to select a radio option, but I could not tab out of the radio tags (in firefox).

**Comment by marcysutton** [comment]
Radio buttons don't work with tabs–they work with the space bar, because they represent only one form control. This is consistent with native radio inputs.
