### ISSUE TITLE
md-select open blank line on the general window right  

### ISSUE THREAD

**Issue by ljcp** [angular/material#3957]
when the select is opened a blank line is shown in the right of the window this happens in the docs and also in my app.

Checkout gif http://gifmaker.cc/PlayGIFAnimation.php?folder=2015073000y4U3otU1g9OgmwztU9xKeh&file=output_KJanye.gif

If someone know where I can start looking , I can try to fix this and add a pull request

**Comment by naomiblack** [comment]
This is fixed in HEAD. https://material.angularjs.org/HEAD/#/demo/material.components.select
