### ISSUE TITLE
chips: backspace to select broken in Edge

### ISSUE THREAD

**Issue by ngraef** [angular/material#3960]
In Edge browser, backspace navigates back rather than selecting the previous chip.

Not sure if you're in the business of supporting Edge yet, so maybe this can be thrown in the backlog.

**Comment by CoDEmanX** [comment]
I can confirm this happens in Firefox 39 too. If there's text which wasn't yet confirmed (not a chip yet), that text is deleted on backspace. As soon as there's no text left, another backspace hit navigates to previous url and no chip is deleted. If the previous page was another angular ui demo page, then the url changes but it actually stays on the current page, with scrollbar problem from there on:

http://youtu.be/MVUEMJrcbq4

**Comment by topherfangio** [comment]
@ngraef Any chance you could test the PR I submitted yesterday which fixes this issue in Firefox and let us know if this fixes the issue in IE Edge as well?

If so, I'll update the description to ensure this issue gets closed at the same time.

**Comment by ngraef** [comment]
@topherfangio Yup, I'll take a look.
