### ISSUE TITLE
chips: zero-length query with autocomplete (Chrome)

### ISSUE THREAD

**Issue by ngraef** [angular/material#3961]
*On master & 0.10.1-rc4*

[Demo](http://codepen.io/anon/pen/PqXYKY?editors=101): chips with autocomplete input and `md-min-length="0"` to suggest items without typing.

Error occurs in Chrome v45.0.2454.15 dev (64-bit) and v46.0.2469.0 canary (64-bit) on Windows 10 & Windows 8.1. Earlier versions not tested.
Works (except expected behavior 3) in Edge and IE11.
Not tested in Firefox or Safari.

**To reproduce:**
1. Open the demo page in Chrome
2. Focus the chip input
3. Use the mouse to click any item in the autocomplete list
4. Click anywhere on the page

**Observed behavior:**
Page freezes -- the chip that was added can't be focused, and text on the page is no longer selectable.

**Expected behavior:**
1. The selected item is added as a chip
2. Focus moves to the input element
3. The autocomplete dropdown displays again

**Notes:**
Using the keyboard to select the dropdown list item doesn't have the same effect; it works as expected (except behavior 3). This is interesting because keyboard selection of autocomplete elements (with a non-zero-length query) is broken (#3833).

**Comment by typotter** [comment]
Looks like the md-scroll-mask is getting left around after the autocomplete item is selected.

**Comment by RolandHeath** [comment]
In the (recently closed as a duplicate) issue, I noticed that if you can mouse over the autocomplete dropdown, it clears the focus issues - in case that helps in finding the issue.

**Comment by ngraef** [comment]
Not sure if the issue mentioned by @typotter is still a problem, but this seems to be fixed by moving to angular 1.4.4 (from 1.4.3).
[Demo](http://codepen.io/anon/pen/NGPPNE?editors=101)

**Comment by RolandHeath** [comment]
@ngraef - It's actually just reduced to requiring that you mouse over the dropdown before it will free the page. 
Which is good, because it means you don't permanently lock the whole page, but still a bug.
