### ISSUE TITLE
md-dialog: forced padding

### ISSUE THREAD

**Issue by michaelkrog** [angular/material#3963]
I'm a bit unsure about the specs regarding using tabs in dialogs, but I do have an issue with it.

The md-dialog-content tag has a forced padding of 24px. Putting an md-tabs inside that makes it look like this:
![skaermbillede 2015-07-31 kl 08 38 09](https://cloud.githubusercontent.com/assets/681472/9002115/4b491f5a-3760-11e5-8972-c6bb68d80f28.png)

If I set `style:"padding:0px"` on md-dialog-content, then it looks much better:
![skaermbillede 2015-07-31 kl 08 44 21](https://cloud.githubusercontent.com/assets/681472/9002124/600d819c-3760-11e5-8304-efc99dabd7e6.png)

**Comment by EladBezalel** [comment]
@michaelkrog It's still happening?

**Comment by michaelkrog** [comment]
@EladBezalel Yes, it seems so.

http://plnkr.co/edit/2QzUUmtVRvTwjZIX1WxY?p=preview

**Comment by ThomasBurleson** [comment]
*  For the Tabs demo's use `class="md-padding"` which adds `padding:16px;`; I have removed the padding for the first demo (to show how the tabs *snaps* to the parent container).
*  Here is one of our Dialog demos with and without padding:
![screen shot 2015-10-02 at 4 35 47 am](https://cloud.githubusercontent.com/assets/210413/10243548/140063c4-68bf-11e5-98ef-0096df1c555d.png)
![screen shot 2015-10-02 at 4 35 57 am](https://cloud.githubusercontent.com/assets/210413/10243550/18473b60-68bf-11e5-80e0-c1688e820de3.png)

> You can see why we **offer** padding as a default. But it is easy enough to override.

For the Dialog, if you do not want padding just do this in your custom CSS:
```css
md-dialog-content {
  padding : 0;
}
```

**Comment by EladBezalel** [comment]
@ThomasBurleson maybe we should make `.md-dialog-content` class that users can put on their content and not force padding on the element

**Comment by ThomasBurleson** [comment]
@EladBezalel - great idea. Make it so!

**Comment by michaelkrog** [comment]
I like the fact that padding is not forced, but the implementation is a bit confusing.

__HTML example__
```
 <md-dialog-content>
    <div class="md-dialog-content">
     ....
   </div>
 </md-dialog-content>
````

We already have directives that tell whether padding should be added or not. Why introduce another css class? And then a class that carries the same name as a directive?

Would'nt it be more simple to have it like this?
```
<md-dialog-content layout-padding>
</md-dialog-content>
```


Or if 'layout-padding' does not quite fit here, perhaps this:
```
<md-dialog-content padding="true">
</md-dialog-content>
```
