### ISSUE TITLE
Exception in IE11 strict mode

### ISSUE THREAD

**Issue by jb29** [angular/material#3964]
In `angular-material 0.10.1-rc4` **IE11** throws the following error while in **strict mode**:

> Assignment to read-only properties is not allowed in strict mode

Cause is an undeclared variable in **line 2498** (function `findParent()`, variable `parent`)

```javascript
/**
 * Search for parent at insertion time, if not specified
 */
function findParent(element, options) {

  // Search for parent at insertion time, if not specified
  if (angular.isFunction(options.parent)) {
    parent = options.parent(options.scope, element, options);
  } else if (angular.isString(options.parent)) {
    parent = angular.element($document[0].querySelector(options.parent));
  } else {
    parent = angular.element(options.parent);
  }

  // ...
}
```

![image](https://cloud.githubusercontent.com/assets/13062631/9004618/c1a951ee-3777-11e5-9d83-254e6d025e66.png)

**Comment by ThomasBurleson** [comment]
Fixed https://github.com/angular/material/commit/af052358a0f606c7c43aafe34e20a6cdf53975b2
