### ISSUE TITLE
set template in resolve of  $mdDialog service

### ISSUE THREAD

**Issue by pavankumarkatakam** [angular/material#3965]
im using angular material, now i got a situation for setting the template dynamically so im using resolve tho download the template from server and i achieved it, but i want to set the downloadded template to $mdDialog template please tell me how to do that
````
      $mdDialog.show({
                controller: 'TaskShowController',
               // template: module.template,(not working)
                parent: angular.element(document.body),
                targetEvent: event,
                resolve: {
                    task: function () {
                        return task;
                    },
                    module: ['$q', function ($q) {
                        var defer = $q.defer();
                        require([], function () {
                            module = require('source/tasks/task_show');// downloads both controller and template im using webpack
                            angular.module("basic").register(module.controller)
                           
                            defer.resolve(module);
                        });
                        return defer.promise;
                    }]

                }
            })
                .then(function (message) {
                    //success function
                }, function (cancelmessage) {
                    //cancel function
                });
````

Is there any option to set template as shown above?

Thanks in advance

**Comment by ThomasBurleson** [comment]
Not yet. 
*  There is a PR https://github.com/angular/material/pull/3662 that would support this.
*  Dialog service would need to use `$mdCompile` 

Your request may present a good use case. 

Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by pavankumarkatakam** [comment]
I have seen that PR and he used to make the `$mdDialog resolve` same as the `ui.router resolve`, i agree that and it also very help full and of course im suggesting that too that in ui.router we have `templateProvider` which is a function to resolve dynamically return a template, in fact im using ui.router `templateProvider` in my own project also.


But my use case is that , my application is big and controller and html templates want to be downloaded on demand(asynronusly) , In depth when user goes to specific route , then only the respective controller and template is downloaded and register with already running angular module in browser, but here my concern is 2 requests to server , one is by templateUrl and second is by resolve thing, in this case ui.router templateProvider is helpfull that im making the one request to server to download a file which consist of both controller and template as well. I want to implement same type in $mdDialog also, if there is a chance to set the template property by resolved properties it is very helpfull



please check this also [once](https://github.com/angular-ui/ui-router/issues/2129)

**Comment by varshag91** [comment]
I am facing a performance issue with $mdDialog.show. Although my template is being cached and used on UI i have 10 md-automplete templates and other fields as well with 4 level ng-repeat. the object iterated in ng-repeat is not that heavy. $mdDialog.show takes more than a minute to open. Not acceptable Is any way to make it visible within 20 sec ????
