### ISSUE TITLE
md-autocomplete md-floating-label is string, not expression

### ISSUE THREAD

**Issue by mrichar1** [angular/material#3966]
This means that you can't use 'dynamic' labels, e.g.: `<md-autocomplete md-floating-label="ctrl.myLabel">`

**Comment by linkedrank** [comment]
Hello - Is this going to be fixed any time soon? I am trying to do use md-floating-label in my directive using md-autocomplete if a certain variable is true and placeholder if not. I can't get md-floating-label to be removed as a attribute though, so the floating label is included even when I don't want it.

**Comment by shalabhaggarwal** [comment]
+1

**Comment by atinder90** [comment]
+1

**Comment by yangy46** [comment]
I got dynamic labels to work using ng-attr. Should also work for placeholder.

`<md-autocomplete ng-attr-md-floating-label="{{label}}"></md-autocomplete>`

**Comment by RizwanAslam** [comment]
Yes i am working with autocomplete label but i am unable to translate it as it don't accept any expression and will show the expression as a static string.......please fix it soon .......... Thanks

**Comment by admeister** [comment]
+1

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (418/400 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:61710)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZj-001Z6V-43
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:16 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=MGvX5OsT6UFEAoQGm/MuuzcPWis=; b=VWy6hKUvmOjk7L67
	ZUxz3Nvn3NOKPScQkXgFwjEWJSOsLoqeHa3Ze5mqDUwTS+A2s0NEiyC6wsapEdOz
	O8XDq87H72SSAVMBZiisVjzw/1ZYKxDymxrxf4X5Tao7Ha9NukXbNvpC5R/ZPcS+
	A9CFbSTv0ONzTNTy8S/WNAS78eE=
Received: by filter0419p1mdw1.sendgrid.net with SMTP id filter0419p1mdw1.9527.572272A953
        2016-04-28 20:29:29.617930907 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id UPfh_YbITPaS8ghPTcF7Rg
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:29.683 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:29 -0700

**Comment by lironbar** [comment]
Another solution is to add a dynamic class with ng-class to md-autocomplete that will hide the label using css

`<md-autocomplete ng-class="{{'noLabel': disableFloating}}"`

and CSS:

`  .noLabel {
    md-input-container label:not(.md-no-float):not(.md-container-ignore), md-input-container .md-placeholder {
      display: none;
    }
  }`
