### ISSUE TITLE
Submission date time icons are too smal in input field (md-input)

### ISSUE THREAD

**Issue by Winsehr** [angular/material#3967]
Hello!
I'm using Angular md-input in my form where the user must be able to submit a date and I am using the code from this material demo: https://material.angularjs.org/latest/#/demo/material.components.input (Basic usage example, "Submission date" especially). 
It all works fine on tablets and the date time picker pops up. But on PC these icons are way too small and it's really hard to click on them. The picture below shows the input field and those small icons where you can choose between a certain date and time stamp.  I wonder if there is a way to make them bigger somehow?

<img width="329" alt="screen shot 2015-07-31 at 2 02 51 pm" src="https://cloud.githubusercontent.com/assets/12999481/9007035/e190413c-378d-11e5-999b-3a3d4dc2d4c1.png">

**Comment by innerpeace0** [comment]
It was even smaller on my computer. The up/down arrow covered the last digit of the year.

**Comment by no-more** [comment]
Hi,

Correct me if I'm wrong but this is chrome default input date picker. This is absolutely not a material design feature.

The material design component is currently in 'private' testing.
It would be great to have some feedback about it by the way, will we be able to test is soon ?

Thanks.

**Comment by topherfangio** [comment]
Date picker was pushed to master yesterday so you should be able to begin
testing and providing feedback :-)

Major props to@jelbourne for his impressive work on it!

**Comment by no-more** [comment]
Thanks that's a great news, I've been waiting for this feature for months.

Great job!

Thanks.

**Comment by innerpeace0** [comment]
I can change months by scrolling with the scroll keys or typing in new months in the text representation of the date. Changing years was equally easy by typing, but I could not directly scroll years. I could not change months or years via a mouse. I only tested this on a desktop and did not try it on mobile.

**Comment by ThomasBurleson** [comment]
Use the DatePicker component instead of an `<input type="date" />`

**Comment by ThomasBurleson** [comment]
Reopening - the Angular Material team should update the [input demo](https://material.angularjs.org/latest/#/demo/material.components.input) to use the DatePicker.

**Comment by ThomasBurleson** [comment]
Fixed.
