### ISSUE TITLE
placeholder and icon floating with layout row

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#3968]
Hi
When you align 2 inputs thanks to a layout="row", with one having an icon and the other not; the one with the icon is "floating" above the normal level
Example : http://codepen.io/anon/pen/bdOVzv
Version : 0.10

**Comment by EladBezalel** [comment]
[Occurs](http://codepen.io/EladBezalel/pen/PPebgZ) on HEAD but slightly different

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (534/500 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:36662)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avscC-000L5t-7b
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:48 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=IT7fn6PGjuGX4Fi95NLo+y2ZOpc=; b=pKKVAKTH6CVuM6u9
	Mrhgw7PpPoycv13dddpdZFD8JfVpEkfXOCf+HiTeRBxDqUI2OcyG/TxZvzU+4PV8
	fyka3jHSy+zZGXz6oEMEWUH5kdHdo574V9Kv/2mF2JdQOLVCH2h8fSY+FKiprrYB
	xJc6Q1Ts23U2E2mSEOT/6NLmOo0=
Received: by filter0912p1mdw1.sendgrid.net with SMTP id filter0912p1mdw1.8947.5722734F61
        2016-04-28 20:32:15.695501718 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id CBJgKIkGSHeURCph-SmScQ
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:15.709 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:15 -0700
