### ISSUE TITLE
md-autocomplete is not disabling if `disabled` applied to its parent

### ISSUE THREAD

**Issue by Sriram143** [angular/material#3970]
hi

I have a ng form and and inside that i have many md-autocomplete controls if i applied ng-disabled attribute to ng-form its changing the color but autocomplete is not disabling.

**Comment by naomiblack** [comment]
this seems potentially related to #3797. @jelbourn can you have a look at both cases?

**Comment by jelbourn** [comment]
[Disabled is not an inherited property](http://jsbin.com/semisu/edit?html,css,js,output).

I tried adding `disabled` to a form with `md-autocomplete` to see if there _was_  a visual change, but could not reproduce. @Sriram143, you can re-open for the latter if you have a CodePen or similar with a reproduction.
