### ISSUE TITLE
Hello World on Internet Explorer 11

### ISSUE THREAD

**Issue by jocel1G** [angular/material#3971]
From the CodePen http://codepen.io/ThomasBurleson/pen/JopjjN, I make a local Web site. On this site, the text "HELLO WORLD" and the icons are left aligned witn Internet Explorer 11, whereas on Thomas Burleson's CodePen, only the icons are left aligned. Anyway, to have everything center aligned, I have made the following changes, in the file angular-material.css :

* in .md-button, the line display: inline-table; is commented out (for the text "HELLO WORLD" that was previously left-aligned)
* in md-icon[md-font-icon], the line width: auto; is commented out (for the three md-icon that were previously left-aligned)

Now, on Internet Explorer 11, I have the same result with my local Web site as with Firefox and Google Chrome.

I hope there is no regression, elsewhere, with my changes. But, at least, what I can see, is that everything is center aligned on Internet Explorer 11.

**Comment by ThomasBurleson** [comment]
@jocel1G - can you retest with the latest release of 0.11.0-rc2 (in master)

**Comment by ThomasBurleson** [comment]
Closing for now. Create a new issue if this problem still persists with 0.11.0-rc2 or higher.
