### ISSUE TITLE
Font weight is not right

### ISSUE THREAD

**Issue by dongmingliy** [angular/material#3972]
The font weight does not look right when I use  md-button, and I noticed that in the demo and codepen are showing different font weight. It appears the demo is following the MD spec. 

Demo:
![image](https://cloud.githubusercontent.com/assets/6826615/9010820/588e47d2-3777-11e5-8284-f658a265b2f1.png)

https://material.angularjs.org/latest/#/demo/material.components.button
Codepen:
![image](https://cloud.githubusercontent.com/assets/6826615/9010828/648dfbae-3777-11e5-8684-9d1b3e67c8d2.png)

http://codepen.io/anon/pen/RPEaMz

Spec:
https://www.google.com/design/spec/components/buttons.html#

**Comment by ngraef** [comment]
Looks like Roboto isn't being loaded in the pens. Roboto needs to be added as a CSS resource in [`CodepenDataAdapter`](https://github.com/angular/material/blob/master/docs/app/js/codepen.js#L49).

**Comment by ngraef** [comment]
This is resolved and should be closed.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (419/400 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:5536)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZl-001Z73-2d
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:18 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=igqGfe1MdHWg2cFlfkWG/zF6kwg=; b=uYWN/7oNHhMELque
	PLWNYHV7XGiSdo/iCRzjwIiqN3sFVmVDnnJ9qPkucOVCS1i/1nHn1v8AR48zTAvW
	bE34DD1/XQze4sbB4yphgUJC3C85nwU08I7qu3YxN5w3uMklgsN/x592ivSTwX//
	8ETI4yKBF38TEwTSVs+dQ2aZmyc=
Received: by filter0640p1mdw1.sendgrid.net with SMTP id filter0640p1mdw1.1303.572272A82E
        2016-04-28 20:29:28.247202786 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id X1JGeDwBQGi_DSqG_PP2Vw
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:28.346 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:28 -0700
