### ISSUE TITLE
md-tabs: controller leakage (1.4.x compatibility)

### ISSUE THREAD

**Issue by YBogomolov** [angular/material#3975]
With Angular 1.4.x ngIf began to work as expected, and this lead to the following issue with md-tabs.

Consider the following CodePen as an example: http://codepen.io/anon/pen/PqXGKB
When you switch between tabs, you can see that in console many new messages 'I am created!' are written, thus many scopes are created, too. But none of them are destroyed.

The fix is relatively simple: you should change ng-if to ng-show in `/src/components/tabs/js/tabsDirective.js:193`. This will return the old behavior.

**Comment by andreialecu** [comment]
This is fixed in the latest 0.10.1-rc5: http://codepen.io/anon/pen/zGyZVZ

Related: https://github.com/angular/material/issues/3692
