### ISSUE TITLE
Md Autocomplete: Blur on selected element (enhancement)

### ISSUE THREAD

**Issue by tiny-dancer** [angular/material#3976]
Couldn't find this through docs/google.  Unless i am missing something, it would appear to be helpful to allow the input for autocomplete to blur when selecting an item.  In devices this would naturally allow the keyboard to hide from the screen.

Thanks and great work

**Comment by photusenigma** [comment]
+1

**Comment by johnSowingo** [comment]
+1

**Comment by egystr** [comment]
+1

**Comment by ninetwentyone** [comment]
Was this fixed or any update on this?

**Comment by LeoLozes** [comment]
I don't understand how this is not something that is not a bit more documented, it seems to be the natural behaviour on mobile, to close the keyboard when selecting an item. I'm looking for workarounds but haven't found much.

**Comment by tokyoite** [comment]
If anyone was wondering, this worked in Angular v4 for me. 
        setTimeout(function () {
            document.getElementById("input-id").blur();
        },0);
