### ISSUE TITLE
autocomplete is not working inside dialog.

### ISSUE THREAD

**Issue by chungwong** [angular/material#3979]
For some reason, if scope is preserved in a dialog, autocomplete is not functioning well at all.

To produce the problem:
1. open dialog 
2. select anything in autocomplete
3. close the dialog
4. repeat above steps

And you will see an extra autocomplete selection appeared at the top left of the page.

If 
```javascript
        scope: $scope,
        preserveScope: true,
```
are commented out, this will not happen. 

Below is a codepen which is forked from  the demo dialog and I copied the demo autocomplete into it.

<p data-height="268" data-theme-id="0" data-slug-hash="LVMypd" data-default-tab="result" data-user="chungwong" class='codepen'>See the Pen <a href='http://codepen.io/chungwong/pen/LVMypd/'>Basic Usage</a> by CHUNG H WONG (<a href='http://codepen.io/chungwong'>@chungwong</a>) on <a href='http://codepen.io'>CodePen</a>.</p>
<script async src="//assets.codepen.io/assets/embed/ei.js"></script>

**Comment by tirana** [comment]
if the autocomplete has a predefined value, it displays the selected item somewhere and may block the whole ui.
![screenshot from 2015-08-31 11 26 23](https://cloud.githubusercontent.com/assets/5245919/9586730/5e547d66-4fd3-11e5-84b1-76ba27f0a7be.png)

**Comment by EladBezalel** [comment]
@chungwong @tirana I couldn't reproduce on HEAD can you make a codepen with the problem if it's still occurs?

**Comment by chungwong** [comment]
http://codepen.io/anon/pen/Mavgde

I replaced v10.0 to v11.2 and this is the only difference between my original pen and this pen.

I couldn't reproduce the issue because I simply couldn't re-open the dialog once I clicked "NOT USEFUL" or "USEFUL" after selection

**Comment by tirana** [comment]
I think it was fixed partially; no random windows anymore.
however, I also could not re-open it in some cases.
for example, http://codepen.io/anon/pen/BodyRZ
steps:
1. open the dialog
2. click on the autocomplete field
3. click on enter
4. try to open the dialog
expected: the dialog
actual: nothing. (and no js errors)

**Comment by EladBezalel** [comment]
Both cases is about the `md-scroll-mask`, i will take a look later and see what's the problem, thanks.
