### ISSUE TITLE
md-subheader does not update his md-sticky-clone position if an element is hidden via a ng-show="false"

### ISSUE THREAD

**Issue by karamasoff** [angular/material#3980]
I don't know if it's a bug or a misunderstood, but when you display a md-subheader after an element that can be hidden through ng-show directive, the md-subheader sticky-clone never changes his top position.

Please check this codepen for more details: http://codepen.io/anon/pen/ZGVywP

**Comment by topherfangio** [comment]
Appears to be fixed with recent changes to subheader: http://codepen.io/topherfangio/pen/XmJqOj

Please comment if you're still seeing the issue when using master/0.11-rc2.
