### ISSUE TITLE
md-autocomplete property for showing or hiding the cross icon on right.

### ISSUE THREAD

**Issue by piyushchauhan2011** [angular/material#3983]
It would be very useful if there is any property that we can use to enable and disable the cross button present on the right side of autocomplete to clear the text.

e.g. `enableClearButton: true/false`

![screen shot 2015-08-02 at 3 01 42 pm](https://cloud.githubusercontent.com/assets/693487/9024783/68b3c270-3927-11e5-98d1-91ddb0544ba9.png)

**Comment by dmackerman** [comment]
Yes, this should be an option for those using the `md-floating-label` technique as well.
