### ISSUE TITLE
No visual difference between input and textarea 

### ISSUE THREAD

**Issue by natcohen** [angular/material#3985]
It creates a confusion when a user can press the enter key to submit a form while in an input but in a textarea. There should be a visual difference between both in order to indicate to the user if he is in an input or a textarea...

**Comment by gkalpak** [comment]
:+1:

**Comment by epelc** [comment]
Do the little expand lines show up?

![image](https://cloud.githubusercontent.com/assets/5204642/9030950/5d48e748-3978-11e5-8f30-3570ecd41b1c.png)

**Comment by ngraef** [comment]
@epelc The Biography field in the [input demo](https://material.angularjs.org/latest/#/demo/material.components.input) is a textarea. Though I agree, it might be helpful to explicitly highlight it in a new example.
