### ISSUE TITLE
menu items not aligned in Microsft Edge(0.10.1-rc5)

### ISSUE THREAD

**Issue by alanpurple** [angular/material#3987]
md-menu-item is not aligned properly to the start in Microsoft Edge
aligned well in Chrome

**Comment by KReden** [comment]
I am seeing this too. Screencap below: 

![screenshot_080515_015846_pm](https://cloud.githubusercontent.com/assets/1535122/9094906/19dcceee-3b7a-11e5-93b3-c9f515d95e2d.jpg)


Chrome behaves like you would expect and opens the menu offset to the button. 
Microsoft Edge opens it centered over the button.

**Comment by Malusia** [comment]
I used 

```css
md-menu-item > .md-button {
	text-align: left;
}
```

to fix this.
