### ISSUE TITLE
Windows 10 and Microsoft Edge

### ISSUE THREAD

**Issue by calebeaires** [angular/material#3988]
MS has doing some improvements. Will Material Design AngularJS be prepared to it?

**Comment by epelc** [comment]
I've was using the preview build(until it completly crashed my hard drive the day before release) and testing my app along with the docs in Edge every now and then. It works 100x better then ie11. I'd say it's some where between Safari and Firefox on the browser scale.

Also I updated to the real windows 10 after my computer crashed and it seems to work really well.

**Comment by ThomasBurleson** [comment]
@epelc - Can you investigate #3995 also?

**Comment by epelc** [comment]
@ThomasBurleson That was created by my coworker he just started this week.

I was showing him how to submit issues since he found it. It was coming up in `0.10.0` and rc-4/5 in the latest firefox on windows 10. I'm not sure if it happens on windows 7/8 or on macs though.

**Comment by epelc** [comment]
@ThomasBurleson Also I just checked edge and the dialogs work fine.
