### ISSUE TITLE
table component?

### ISSUE THREAD

**Issue by YAmikep** [angular/material#3989]
I could not find a demo of tables on the Angular Material Live Docs website.
I could not find a table component in the source code either: https://github.com/angular/material/tree/master/src/components

That is however something we see in MDL: http://www.getmdl.io/components/index.html#tables-section

It'd be useful to add such a component.

Thanks.

**Comment by Koslun** [comment]
Look at this issue #796 on mdTable and close this as a duplicate.

Other than that, agreed, would be useful. Using https://github.com/daniel-nagy/md-data-table for now.
