### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by btford** [angular/material#399]
now that `angular*` packages are on npm, this should be too!

**Comment by gustavohenke** [comment]
Will this happen? :D

![](http://i.imgur.com/Ke3jYix.png)

**Comment by kentcdodds** [comment]
Please? Want all of my stuff to be from npm. Right now I'm just installing straight from git. Would love to not have to do that :-)

**Comment by shprink** [comment]
+1

**Comment by alejonext** [comment]
+1

**Comment by naomiblack** [comment]
We'll do this with 0.7.1 release

**Comment by shprink** [comment]
OMG!  Thanks @naomiblack  :)

**Comment by colin-ch** [comment]
Thank you @naomiblack :+1:

**Comment by jaawerth** [comment]
Glad to hear it! Now that I'm bundling my dependencies, I'm looking forward to grabbing everything as a module.

**Comment by naomiblack** [comment]
Closing this issue since `npm install angular-material` now works. :) Note, however that I didn't get the readme updated, so the doc at npmjs.org is confusing/incorrect until we push 0.8. In the meantime, look here for instructions: https://github.com/angular/bower-material/blob/master/README.md

**Comment by ThomasBurleson** [comment]
@naomiblack - I am reopening due to issues.  Using `npm install angular-material`:

1.  Incorrectly installs globally (for me in `~/node_modules`)
2.  Does not install in a hidden .node_modules directory
3.  Does not install the dev dependencies 
```json
"dependencies": {
    "angular": "1.3.x",
    "angular-animate": "1.3.x",
    "angular-aria": "1.3.x"
  },
```

**Comment by kentcdodds** [comment]
Note, I would recommend using `peerDependencies` rather than `dependencies` and be as loose as you can about it. For more info see: http://blog.nodejs.org/2013/02/07/peer-dependencies/

**Comment by gustavohenke** [comment]
@ThomasBurleson 
About 3: devDependencies are only installed if you directly run `npm install` inside the package directory. If you don't want this behavior, you should use `npm install -d <package>`.

**Comment by ThomasBurleson** [comment]
@gustavohenke - under what scenarios would you want to install Angular Material but **not** the AngularJS required libraries?

**Comment by gustavohenke** [comment]
I think I didn't understand your problem previously posted:

> 3. Does not install the dev dependencies

The [bower.json located in the bower-material repository](https://github.com/angular/bower-material/blob/master/bower.json) doesn't have any devDependencies; so why would that be a problem?

**Comment by ThomasBurleson** [comment]
@gustavohenke - Now I understand. When NPM installs Angular Material, it should also install the **required** AngularJS libraries. I corrected the verbiage in my earlier comment.

**Comment by robertmesserle** [comment]
Published last night https://www.npmjs.com/package/angular-material

**Comment by robertmesserle** [comment]
Re-opening for discussion - sorry about that

**Comment by ThomasBurleson** [comment]
Created new issue #1382.
