### ISSUE TITLE
md-input-container scroll issue on iPad Safari

### ISSUE THREAD

**Issue by loveapoex** [angular/material#3993]
Typing indicator within md-input-container shows wrong vertical position when scrolling in Safari on iPad.

Can be recreated by visiting https://material.angularjs.org/latest/#/demo/material.components.input on an iPad, focusing an input field and start scrolling.
 
Angular version: 1.4.0
AngularMaterial version: 0.10.0

**Comment by topherfangio** [comment]
Indeed, it looks like the typing indicator doesn't reposition until you stop scrolling. A quick fix might be to hide the typing indicator on scroll, but it would be ideal if it stayed with the input.

Nice catch :-)
