### ISSUE TITLE
need 'dynamic' md-menu creation

### ISSUE THREAD

**Issue by heoseok** [angular/material#3994]
I use a number of 'md-card' and 'conditional' menus on each card.
So I bind all conditions per each card for menus.
It causes too much watcher and bad performace.
So I need an way to create menu on demand by script.

**Comment by NickBolles** [comment]
You could use the bind once syntax in angular 1.3.x and up to avoid any watchers after the first bind
http://swirlycheetah.com/native-bind-once-in-angularjs-1-3/

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
