### ISSUE TITLE
Dialog: Hide/Cancel not working in Firefox

### ISSUE THREAD

**Issue by chadburton** [angular/material#3995]
Firefox v39 on Windows 10. Can't click the hide/cancel buttons. Stuck in dialog box. Tested in `0.10.0` and `0.10.1-rc5`.

https://material.angularjs.org/0.10.1-rc5/#/demo/material.components.dialog

**Comment by gkalpak** [comment]
FWIW, it works fine for me on Firefox 39/Win 10...

**Comment by chadburton** [comment]
Issue was with a Firefox add on by the name of "Print Edit" and should be closed (at least here)
Sorry for the non-issue and thanks for looking into it.
