### ISSUE TITLE
md-input: <input type="date"> placeholder clashes with empty dd/MM/YYYY text (Chrome)

### ISSUE THREAD

**Issue by syjulian** [angular/material#4001]
When I use a dark theme with a date input, the placeholder value can be seen overlapping the input's label. It also looks like the text is doubled. Any help on how to fix this?

http://codepen.io/syjulian/pen/jPXXdg

**Comment by innerpeace0** [comment]
Looks fine on Pale Moon, a Firefox derivitive, on Linux.

**Comment by no-more** [comment]
Hi,

I have same issue on chrome, not FF

**Comment by dmackerman** [comment]
Appears to be a Chrome only issue.

**Comment by lyschoening** [comment]
+1 Not sure if I have exactly the same issue, but something is definitely off.

The `<label>` element (md-placeholder) has a `text-shadow` set to `foreground-shadow`, which is only set in a dark theme. It looks odd because (1) the shadow is darker than the text and (2) `color` itself is transparent so, as you can see by zooming in, the drop shadow is visible below the text and the text itself ends up having a gradient. 

This is not specific to `<input type="date">` for me.

**Comment by syjulian** [comment]
Here is my current workaround for the issue

[md-theme=myTheme] md-input-container .md-input {
    text-shadow: none
}

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (434/400 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:39974 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZn-001Z8w-Q2
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:21 +0200
Date: Thu, 28 Apr 2016 13:28:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875299;
	bh=PDEGULdZ9u/PeTW9Re1j7nXPL8PwOvwKHMJKlt26Mf0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lR6RHhSLU60thbpuv4ntBnSwR6Vlr9r+/dOoBd+OZaYzywijfeB5G2g7d1o+x2JPB
	 LQ3igpFJJiVfIYYfambismIorZR0wIygtk00lrao+Tt5Dbm8pWksizK0Cb5f9rmCFY
	 AwKJK013b+p5io6xJGAXzQZx+JdmNT2wooJnzOD8=
