### ISSUE TITLE
input field in md-input-container doesn't work with label and placeholder at the same time

### ISSUE THREAD

**Issue by thunderboltsid** [angular/material#4003]
An input field inside and md-input-container chooses to display only the label if present or the placeholder in the absence of a label. I'd normally expect placeholder to animate in once the field is focussed and empty but it doesn't. The console log shows a warning saying 'The placeholder='email@web.com' will be ignored since this md-input-container has a child label element.'. I found a reference to the same problem being mentioned as resolved in 0.7.0 milestone but still doesn't seem to work on master. https://github.com/angular/material/issues/1279

Here's the sample code:
```
<md-input-container>
                <label>e-mail id</label>
                <input placeholder="email@web.com" type="email" ng-model="user.email">
</md-input-container>
```

**Comment by khyamay** [comment]
any update on this one ?

**Comment by thunderboltsid** [comment]
Nope, nothing so far.
