### ISSUE TITLE
md-select doesn't close on backdrop click

### ISSUE THREAD

**Issue by cybercyst** [angular/material#4009]
In Firefox and Internet Explorer, you HAVE to click on an option to close md-select, you can't just click on the backdrop to close the md-select element without selecting an option.

**Comment by Londovir** [comment]
I can reproduce this on the HEAD demo website for Firefox, but not in IE11 (Windows 10 build) nor Edge. Need to set up a Win8.1/Win7 IE11 VM to test that, though...

**Comment by ThomasBurleson** [comment]
@cybercyst, @Londovir - you are using which version of:
*  Angular Material?
*  Angular?

**Comment by innerpeace0** [comment]
May be related to freezing and other problems mentioned in [#3908] (https://github.com/angular/material/issues/3908).

**Comment by cybercyst** [comment]
@ThomasBurleson 
I'm currently on:
angular#1.4.3 (1.4.4-build.4148+sha.dc0b856 available)
angular-material#0.10.0 (0.10.1-rc5-master-f5a9101 available)

**Comment by innerpeace0** [comment]
Besides the [demo page] (https://material.angularjs.org/latest/#/demo/material.components.select), it also happens on the codepen.

**Comment by Londovir** [comment]
Oddly enough, I'm not seeing the issue this morning on the HEAD demo page in Firefox like I did yesterday. What's odd is the one main commit that I can see that took place yesterday wouldn't/shouldn't have had anything to do with this issue. Anyway, I can no longer replicate this in FF on my machine.

**Comment by cybercyst** [comment]
It does appear to be working on HEAD for me as well, before I was testing on the 0.10.0 release page, which still doesn't work. So this should have been fixed and will be good in the next release!  Thanks!
