### ISSUE TITLE
on IE11: on mddialog close, body overflow hidden does not reset to overflow:auto

### ISSUE THREAD

**Issue by deckikwok** [angular/material#4012]
related to issue #3005. I've temporarily solved that issue with a specified height since flex is acting up on IE. However, I face another issue: 

When opening a mddialog with disableParentScroll set to true, the body will be assigned an overscroll: hidden. On closing, the overscroll:hidden attribute is not set to auto - which is the intended behavior and is exhibited on Chrome.

My temp fix: called 'finally' on the promise returned by mddialog and use jqlite to  assign overflow : auto to $('body').

p.s. I dislike IE.

**Comment by EladBezalel** [comment]
@deckikwok can you please provide a codepen so i can investigate it?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (408/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:19088)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZN-001Z1P-1j
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:54 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=LhZskSgtjzX/4I5DySL0rxO1ioI=; b=FNfWDWtltOUAKrPF
	YZ6+Lfae1/3GS+qVitW87byW/8CbT3ikRRZUoe0gsQAnq9D8WWEUtn8G2YD2Dfnm
	x4DNxC2aIg5raactcXbnElML2mtarYnOGyrlHtTFDAYWDrRNAMPvT5Mw4DDYH73k
	cQeGDqNhUKCeCT0UavRkJaWyAco=
Received: by filter0436p1mdw1.sendgrid.net with SMTP id filter0436p1mdw1.22411.5722729354
        2016-04-28 20:29:07.616187058 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id sffhwGjNQaehjbg_YYyMQA
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:29:07.643 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:29:07 -0700
