### ISSUE TITLE
md-toolbar too tall on mobile

### ISSUE THREAD

**Issue by calebegg** [angular/material#4016]
App bars should be 56px tall on mobile, but md-toolbar stays 64px tall.

**Comment by mckenzielong** [comment]
:+1: Also from the [spec](https://www.google.com/design/spec/layout/structure.html#structure-app-bar): 
> Mobile Landscape: 48dp

**Comment by cesar-oyarzun-m** [comment]
hi @calebegg are u using cordova web view for your app???

**Comment by topherfangio** [comment]
@calebegg Have you tested this against the master branch? I believe it was fixed in b6e109893f3e8f71d4ce2ced7429c8844dd487fa.

**Comment by calebegg** [comment]
Yep, looks fixed to me. Thanks!
