### ISSUE TITLE
md-menu-divider not visible if menu is scrollable (chrome)

### ISSUE THREAD

**Issue by alexitooi** [angular/material#4017]
hi there,

currently (v10.rc5) the md-menu-divider is not visible, but in the DOM, if there are more than 5 items in md-menu-content which is scrollable. if md-menu-content is small enough, md-menu-divider are shown.
is this a desired behaviour? in latest stable chrome was not working, IE11 works as expected :+1: 

best regards
![bildschirmfoto 2015-08-04 um 18 09 23](https://cloud.githubusercontent.com/assets/2962085/9065781/1611e0e8-3ad4-11e5-80f3-d6cf353ba672.png)
![bildschirmfoto 2015-08-04 um 18 09 37](https://cloud.githubusercontent.com/assets/2962085/9065782/1611f510-3ad4-11e5-8c19-e3f2b61cc902.png)

**Comment by john2x** [comment]
I'm getting this issue on latest 0.10.1 release on Chrome and Firefox.

**Comment by tsareg** [comment]
+1

**Comment by tetyanochka** [comment]
+1

**Comment by Dvoikin** [comment]
+1

**Comment by afmmars** [comment]
+1
