### ISSUE TITLE
List view titles look bad with long strings

### ISSUE THREAD

**Issue by calebegg** [angular/material#4018]
See screenshot. The `line-height: .75em` means that the text overlaps. It should probably use `text-overflow: ellipsis`, but that also doesn't work with the `line-height: .75em`.

![long list view](https://cloud.githubusercontent.com/assets/782920/9065792/db5bc87e-3aa1-11e5-8896-295c715957ac.png)

**Comment by fred87lim** [comment]
@calebegg I used the `<p>` tag and it solved the text overlap issue. Further to that, I style the tag as follow  `<p style="font-weight:bold; color:black">....</p>`.

**Comment by topherfangio** [comment]
I believe this has been fixed as the title now has `line-height: 1.2em` and appears to properly use the ellipsis. If you are still experiencing this after upgrading, please add a Codepen so that we can see the exact issue and we will re-open.

Thanks!
