### ISSUE TITLE
material site(HEAD) menu demo totally different in Microsoft Edge

### ISSUE THREAD

**Issue by alanpurple** [angular/material#4021]
very slow and totally different

**Comment by Splaktar** [comment]
@alanpurple can you please give this another shot with the [latest HEAD](https://material.angularjs.org/HEAD/#/demo/material.components.menu)?

The only difference that I am seeing is that in Edge the contents of the wider menus is centered where on Chrome the contents are left justified.

**Comment by Splaktar** [comment]
This issue is unreproducible.
