### ISSUE TITLE
Click other component if md-select is opened

### ISSUE THREAD

**Issue by tuchk4** [angular/material#4027]
http://codepen.io/anon/pen/yNZMjd

Now if one **select** is opened - to open second **select** user should click two times:
 - close current select
 - open second

it would be more convenient when user click second **select** while first **select** is still opened - close first and open second.  Maybe use additional parameter to <md-select>

What do you think?

**Comment by dmaslov** [comment]
It would be very useful! +1

**Comment by ya-s-ya** [comment]
Absolutely agree! Right now it's not convenient for multiselect filters. Would be great to avoid the necessity of closing the previous select before opening the next one
