### ISSUE TITLE
layout in IE10 seems broken

### ISSUE THREAD

**Issue by rolandjitsu** [angular/material#4028]
I am not sure if this is because I may be doing something wrong, but on [this](http://commerceservertraining.com/#!/) website I've built, in IE10 it looks like the layout is messed up (It does not occur in other browsers).

**Comment by csvan** [comment]
https://github.com/angular/material/issues/1276

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by rolandjitsu** [comment]
@ThomasBurleson I am unsure if I can replicate what is happening [here](this). But you can easily debug the live site without the need of creating a plunkr demo. There is nothing else happening that cannot be seen in the source of the website.
