### ISSUE TITLE
http problem

### ISSUE THREAD

**Issue by mhipo1364** [angular/material#4029]
Hi guys

Thanks for this awesome project

I provide data from http://localhost:1337 to my front-end:

I fetch data from server via $http, but I have a problem, when I see my project in browser everything looks fine, but in mobile (chrome browser), my $http request not work( I'm sure about this, because my server never get any request in this mode), I'm so frustrated, would you kindly help me? 

***Note:*** I put log on my controller, just http has problem, before and after that, log works by mobile call

**Comment by peduxe** [comment]
You don't share the same IP, it is unique, when you say `localhost` it means it's your local machine, when accessing from outside your host will attempt to connect to the localhost from where you're accessing. Get your host machine IP instead: `http://{host_ip}:1337`. If you're using bash use the `ifconfig` command in DOS use `ipconfig` it will print among other informations your machine IP.

**Comment by mhipo1364** [comment]
@peduxe: Really thanks :+1:

**Comment by peduxe** [comment]
@mhipo1364 you're welcome

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
