### ISSUE TITLE
Toast locals seems not work.

### ISSUE THREAD

**Issue by miguelchico** [angular/material#403]
Hi.

I'm trying pass parameters to a toast controller using locals parameters as indicated in doc.

Here my code:

$materialToast.show({
        controller: 'ToastCtrl',
        templateUrl: 'toast.tpl.html',
        duration: 6000,
        position: 'top right',
        locals: {p1: 'a', p2: 'b'}
      });

I try to use p1 and p2 in toast.tpl.html but there are empty:
<material-toast>
  <span flex>{{p1}} - {{p2}}</span>
  <material-button ng-click="closeToast()">
    Close
  </material-button>
</material-toast>

I try to use p1 and p2 in ToastCtrl but there are undefined.

**Comment by yarl** [comment]
It will be nice to add example of injection to demos.

**Comment by renannprado** [comment]
Another victim to this here. I still do not find the below pretty clear, though after reading this thread, I clearly understood.

> 
An object containing key/value pairs. The keys will be used as names of values to inject into the controller. For example, locals: {three: 3} would inject three into the controller with the value of 3.

https://material.angularjs.org/latest/api/service/$mdToast

**Comment by mihirparikh** [comment]
Is there anyway to pass parameters to the controller of a custom preset that was created using the 'addPreset' service function? I'm creating presets in a config provider.
