### ISSUE TITLE
md-icon font not working in md-list-item (broken in 0.10.1)

### ISSUE THREAD

**Issue by rscottfree** [angular/material#4031]
Using the material icon font faces in md-icon inside of an md-list-item fails to show the actual icon, showing only the glyph text.

This worked in 0.10.0 but is broken in 0.10.1-rc[1-5]

Here is the md-list example for "Checkbox with secondary action" from the demo page, using 0.10.1-rc5. This is identical to the demo except I'm using the font face in place of the SVG icon. (SVG works fine)

[Broken codepen for md-icon using 0.10.1-rc5](http://codepen.io/rscottfree/pen/OVdgbN?editors=101)

And here is the same code using 0.10.0.

[Working codepen for md-icon using 0.10.0](http://codepen.io/rscottfree/pen/JdxJNx?editors=101)

**Comment by geoffreytran** [comment]
I can confirm I am having this same issue.

**Comment by vasiliy0s** [comment]
+1

**Comment by jbainbridge** [comment]
We are having the same problem.  Is there a work around or is this thing going to be fixed?

**Comment by miclaus** [comment]
+1

**Comment by programmist** [comment]
@rscottfree: This issue seems to have been fixed.  I forked your Codepen and updated it to Angular Material 0.11.0 and the issue disappears:
http://codepen.io/programmist/pen/pjyvPp?editors=101

Please verify this is working for you.

**Comment by rscottfree** [comment]
I can confirm this is now working for me in ```0.11.0-rc2```.
