### ISSUE TITLE
Custom contrast for custom palettes

### ISSUE THREAD

**Issue by Masadow** [angular/material#4032]
Hi,

I use custom palettes for primary, accent and warn color but I can't find a way to configure the contrast color.

Actually, I've set up `contrastDefaultColor` to `light` on my primary palette. The problem is that when I use my primary palette for buttons, text color is `color: rgba(255, 255, 255, 0.870588);` and I would like to have `color: rgb(255, 255, 255);`. Is there a way to configure that values ?

Thanks

**Comment by ThomasBurleson** [comment]
@rschmukler - does an API exists currently? Or should this wait for post-1.0?

**Comment by icdevin** [comment]
Although this late for the issue author, if you want to use plain white (i.e. `rgb(255, 255, 255)`) for your light contrast color, you can specify an array of hues under `contrastStrongLightColors` which uses plain white for the contrast color. This wasn't documented in the API, so it may be worth adding there as well.
