### ISSUE TITLE
(perf)md-tooltip uses angular watcher per item

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#4033]
This isn't a major issue at all, but md-tooltip is using 1 (or maybe 2) watchers per tooltip. While many won't see this as major, I'm currently using a large table that's completely structured to be bind once.

If, for example, I have 200 rows, and each row has a md-tooltip, it would be 200/400 watchers which are called on each digest. It has terrible performance. I am aware of the ability to use virtual-repeat, but for UX reasons, I cannot use it. I have opted to remove the md-tooltip for this reason. It seems a better performance fix would be to use DOM's hover/mouse-over/mouse-enter and then use an $apply when necessary instead of having each tooltip being watched on every digest.

I can construct a codepen to show the performance issues.

**Comment by nestorneto** [comment]
+1

**Comment by mcapu** [comment]
Is there a workaround for having performance problems due to having many md-tooltips right now? My situation is similar, although it's caused by several tooltips in each row.

**Comment by ThomasBurleson** [comment]
What about using a virtual repeater with 10-20 rows visible ?

**Comment by clshortfuse** [comment]
@ThomasBurleson I would if I could, but I've designed a full height single page app, so I can't mix a virtual repeater. At least I couldn't when I tried before.

I have 2 tables in one vertical element. Both tables are of dynamic height, but you scroll through the one parent element. I've solved the performance issue there with bindonce but I had to remove every tooltip.

If virtual repeater had something like ng-repeat-start and ng-repeat-end, then I could probably do it.

**Comment by SanderElias** [comment]
The watch is in there to make it possible to show/hide the tooltip manually. I found no easy(read performant) way to lose the $watch and keep this functionality. If anyone has a good idea how to solve this catch 22?

**Comment by no-more** [comment]
Hi,

I'm not an expert, but in order to keep track can't we use a service (or an optional parent directive) and store the status outside of the component itself ?
I'm not sure if this won't generate other issues or if it will work as well as the current version. But it could be a way to limit the number of watchers. One important point is that only a single tooltip can be visible at time (or at least I think so).

**Comment by skosno** [comment]
Could you consider to not create watcher if one is not passing "md-visible"? In most of my use cases I do not need any manual control on tooltips and as indicated in directive bindings, it is optional (=?). 

Same with direction maybe - if not passed, just skip the watcher?

**Comment by clshortfuse** [comment]
@skosno I make a PR with these changes. If the browser supports MutationObserver, it'll create a watcher for md-visible while md-direction will be changed immediately. The reason is that md-direction is a raw value while md-visible can take a javascript object.
