### ISSUE TITLE
md-tab within md-toolbar : is it possible?

### ISSUE THREAD

**Issue by hanu412** [angular/material#4034]
Hello Team,

I have fallen in love with material design. I want to use the amazing tabs "md-tabs" inside the tool bar. 
I want to use tool-bar to act as my navigation bar and use md-tab as hyperlink to display pages like AboutMe,Contact etc.  

When I use <md-tabs> outside toolbar it works supremely well. But I want to include tabs inside the toolbar and avoid the need of creating separate html pages/partials for my actions. Any suggestion on how I accomplish it? Is there a directive which I'm missing-that is already doing this task?

This is the code :: myController makes an ajax call for the images and i am displaying them using "md-card" . 
	<!DOCTYPE html>
	<html>
	<head>
		 <meta name="viewport" content="initial-scale=1" />
		<title>My WebSite</title>
		<link  rel="stylesheet" href="app/node_modules/angular-material/angular-material.css" />
			</head>

		<body ng-app="myWebsite" ng-controller="mywebController" style="color: green ">

			<div layout="column" layout-fill>
	  <md-toolbar>
		<div class="md-toolbar-tools">
		  <span>Hanuma</span>
		  

		  <span  flex>  </span>
			
		<md-tabs md-dynamic-height md-border-bottom>
			<md-tab >About Me</md-tab>
			<md-tab >Contact</md-tab>
			<md-tab >Misc</md-tab>
	    </md-tabs>
			
		  <md-button>
			Logout
		  </md-button>
		</div>
	  </md-toolbar>
	  <md-content>
		
	  </md-content>
				<div>
	  <md-content class="md-padding">
		<md-tabs md-dynamic-height md-border-bottom>
		  <md-tab label="About Me">
			  <div ng-repeat="image in images" class="flex">

		<md-card>
		  <img ng-src="{{image.imagePath}}" class="cardstyle" alt="Washed Out">
		  <md-card-content>
		  <p>
			 Its me {{image.imageTitle}}
			</p>
		  </md-card-content>
			</md-content>
				</div>
		  </md-tab>
		  <md-tab label="Contact">
			<md-content class="md-padding">
			  <h1 class="md-display-2">Contact</h1>
			 Contact Screen
			</md-content>
		  </md-tab>
		  <md-tab label="Misc">
			<md-content class="md-padding">
			  <h1 class="md-display-2">Miscellaneous</h1>
			 Misc Info
			</md-content>
		  </md-tab>
		</md-tabs>
	  </md-content>
	</div>
	</div>

	<!-java script references-->
			<script src="app/node_modules/angular/angular.js"></script>
			<script src="app/node_modules/angular-animate/angular-animate.js"></script>
			<script src="app/node_modules/angular-aria/angular-aria.js"></script>
			<script src="app/node_modules/angular-material/angular-material.js"></script>
			<script src="app/js/app.js"></script>
		</body>
	</html>

![capture](https://cloud.githubusercontent.com/assets/11040896/9093568/6a8da1e2-3bca-11e5-9583-4e7f11adf9fd.JPG)

**Comment by iBeliever** [comment]
See #1076, especially the last comment. I had a similar requirement, and that example worked perfectly for me, animations included.
