### ISSUE TITLE
md-switch does not revert on external model changes

### ISSUE THREAD

**Issue by TiS** [angular/material#4036]
MD switch directive does not revert, when model change is not a consequence of clicking on switch.

Example:

HTML:
````html
      <md-switch ng-model="post.isAccepted" ng-change="vm.changeAccepted(post)"></md-switch>
````

JS:

````js
function changeAccepted(post) {
    someService.accept(post.objectId)
        .then(null, failureAccept);
            
    function failureAccept() {
        post.isAccepted = post.isAccepted ? 0 : 1;
    }
}
````

The expected outcome is, that on service failure switch is reverted. Unfortunately, this does not happen (although other page elements indicate, that the `post.isAccepted` value **has been** reverted)

**Comment by ThomasBurleson** [comment]
you need to use:

```js
function failureAccept() {
  scope.$apply(function() {
    post.isAccepted = post.isAccepted ? 0 : 1;
  });
}
```
