### ISSUE TITLE
Configurable position for mdDialog

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#4037]
I'm trying to create a custom dialog using mdDialog, but the position is always set to the middle of the screen. I would like to be able to configure it to be above the button that opens the dialog, the same way that mdMenu does.

**Comment by ddimitrop** [comment]
+1 for custom positioning.

We would like to configure dialogs to animate and stay on the right side of the screen.

**Comment by clshortfuse** [comment]
You can supply your own CSS to override the default ones.

This is what I use for one of my apps:

    .md-dialog-container {
      position: absolute;
    }

    md-dialog {
      max-width: 90%;
      max-height: 90%;
    }

This is global, but you can always assign an id to limit the scope.

**Comment by ddimitrop** [comment]
Sure, but this is fragile as it depends on internal implementation. Also animations may look wrong - for example a side dialog would probably animate from that side.
It may be possible to override animations but this becomes ever more fragile.

**Comment by NickBolles** [comment]
I would also like to see an option for full screen dialog https://www.google.com/design/spec/components/dialogs.html#dialogs-full-screen-dialogs
This is pretty easy with a custom dialog template and putting the buttons in the toolbar, but it would be cool if it was baked in

**Comment by erinkidd01** [comment]
I would also like to be able to specify whether the dialog animates in from the left or right corner. Currently, the dialog always animates from the left side regardless of position. This only happens the first time the dialog is opened. All other times, it correctly opens and closes from the clicked icon.

We are using dialog to create complicated custom menus. md-menu does not allow enough flexibility to design the popups the way we want. md-dialog has everything we need except for the positioning control.

**Comment by clshortfuse** [comment]
@erinkidd01 the animation starts based on the event being pass to it. if you pass the click event of a button, then the animation would start from the cursor position.

**Comment by ThomasBurleson** [comment]
@all - After the v1.0 release, we are planning on enhancing Dialog to include:

* Full size
* Drag Repositioning and (persistence of dialog positions)
* Animation options for slideIn (left, top, right bottom)
* Custom positioning
* Multiple Dialog stacking

**Comment by erinkidd01** [comment]
@clshortfuse Yes, it starts from the click event. The problem is that the animation is from the left corner of the dialog, which is fine if you always position the dialog in the center of the screen. However, if you position the dialog near the top right of the screen, you want the animation to be from the top right corner of the dialog (similar to the way mdMenu is implemented). Otherwise, it's very difficult to get a smooth transition.

**Comment by spoco2** [comment]
I'd love to be able to do this too... I'm trying to use mdDialog to create a menu that comes from a button on the top of the screen (a fair bit of content in it).

I can't even get anything to work using css (without affecting ALL dialogs, which I don't want to), because the element that you get to provide within the template is wrapped inside another which actually defines the size and position. So there's no access to applying a custom class to that one to allow for custom placement. 

(Even an ability to pass a className as an option that is applied to the md-dialog element would be superb)

**Comment by erinkidd01** [comment]
@spoco2 I have a hack that works for now to configure positions. The animations are slightly messed up, but at least the dialog is in the correct location.

Before showing the dialog, calculate the position of where you want it to go, pass that value as part of locals, and then in a timeout in your dialog-controller, set the position of the dialog. You can look at the code for mdMenu to see a more sophisticated solution based on whether the element is on the left or right of the screen.

Ctrl:
```javascript
var button = $element.get(0);
var rect = button.getBoundingClientRect();
var position = {top: rect.top, left: rect.left};

var presets = {
  templateUrl: 'my-dialog-template.html',
  locals: { 'position', position },
  controller: DialogCtrl,
  ...
};

$mdDialog.show(presets);
```

DialogController:
```javascript
constructor: function(position) {
  ...
  $timeout(function() {
    var el = $('md-dialog');
    el.css('position', 'fixed');
    el.css('top', position['top']);
    el.css('left', position['left']);
  });
};
```

**Comment by spoco2** [comment]
@erinkidd01 Thanks, I've passed on trying to use mdDialog for my slide down menu, was illfitted.

Have used basic CSS and Angular to get what I wanted :)

**Comment by alexey-shaposhnikov** [comment]
+1 for custom positioning.

We would like to configure dialogs to animate and stay on the right side of the screen.

**Comment by csvan** [comment]
+1

**Comment by scriptsure** [comment]
+1

**Comment by ismarslomic** [comment]
+1

**Comment by alignus-abe** [comment]
+1

**Comment by bluebirdtech** [comment]
+1

**Comment by jpike88** [comment]
This is pretty important for cordova apps where the keyboard doesn't push the page upwards.

Case in point:

![screen shot 2016-02-17 at 1 59 27 pm](https://cloud.githubusercontent.com/assets/9585787/13099517/ad59d18c-d57e-11e5-9d25-1ce7e573a884.png)

**Comment by caribnow** [comment]
+1

**Comment by Warzou** [comment]
+1

**Comment by mutluoskan** [comment]
+1
I also would like to configure dialogs to animate and stay on the bottom side of the screen.

**Comment by smurugavel** [comment]
+1 for custom positioning. 
@daniel-nagy implemented something similar on his data table. I am referring the "comment" table column from the demo. [codepen](http://codepen.io/anon/pen/BjvLVJ?editors=1010).. 
And, here is his source code, if someone needs it.
https://github.com/daniel-nagy/md-data-table/blob/master/src/scripts/mdEditDialog.js

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (615/500 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:54012 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdJ-000Lk8-Iy
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:57 -0500
Date: Thu, 28 Apr 2016 13:32:26 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875546;
	bh=geQuZ1Jw7A5OY75AVkD36SP4s3qpc2MdUNc4N1guZXU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=bvnBpnWEsUvh5R60bpEHB7zK72zLXFnGc00KP2Xd0nTTOwe9uMOC1HQbcKgQBckZf
	 JqKu1TJW2xv9Nqy5L/rdZPxs9Tuu5Hi/BUx8B2ZAiyqaRNiN+i6jhoVqQvk+HgsYkp
	 Elc8rD+Cq5N3DobjVWewKZsZLpJjxVTUdPPWu+Ts=

**Comment by waterplea** [comment]
This is closed as deprecated but what does that mean? How do we position mdDialog?

**Comment by ErinCoughlan** [comment]
@waterplea Use [mdPanel](https://material.angularjs.org/HEAD/demo/panel), which you can position anywhere on the screen and even reposition it once it's open.

**Comment by bluebirdtech** [comment]
@ErinCoughlan Thanks for that info. I'd seen mdPanel mentioned a few times but didn't know what it was or how useful it sounds. :)

**Comment by juan-david-correa** [comment]
In angula 2 

private showInfoAccount(client: Client): void {
          const config = new MdDialogConfig();
          config.position = {
              top: "10"
          }
          config.data = client
          this.dialog.open(ShowInfoAccountComponent, config);
    }

**Comment by WaterBleu** [comment]
@juan-david-correa 
this is not working for me.
all this does it move it to the top of the screen but not actual 10px from top

**Comment by fabiannagel** [comment]
Is there any news on this topic? "position: fixed;" works but it screws up the animations

**Comment by jpduckwo** [comment]
I solved this with:

* Setting a class on the dialog so it can have some specific styles set from CSS
* Using the position option to set the top value to be something I wanted (in px)
* Using a media query to adjust the margin-top for a different screen widths

### Component
```
    this.loginComponentRef = this.dialog.open(LoginComponent, {
      panelClass: 'mylogin',
      position: {
        top: '80px',
      }
    });
```
In the background the dialog takes this top: '80px' and sets a margin-top to the element style at run time. You can then override the margin-top with css.

### Global Styles (or equivalent that isn't cssnext)
```
.mylogin {
  @media (max-width: 600px) {
    margin-top: 20px !important;
  }
}
```

**Comment by bindu24** [comment]
Where can I find all the released versions of @angular/material?

**Comment by Splaktar** [comment]
@bindu24 Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2). This repo is for AngularJS Material.

You can find the `@angular/material` releases [here](https://github.com/angular/components/releases).
