### ISSUE TITLE
layout-fill inconsistencies in Chrome and MS Edge

### ISSUE THREAD

**Issue by qorsmond** [angular/material#4038]
I have this layout working in Chrome 44 using 0.10.0:

![image](https://cloud.githubusercontent.com/assets/4716711/9096008/d9dabbf8-3bba-11e5-9b52-9795e03da21c.png)

Viewing it in MS Edge:

![image](https://cloud.githubusercontent.com/assets/4716711/9096064/2de56d24-3bbb-11e5-99bc-07f1e1cf0fca.png)

Here is a codepen:  http://codepen.io/qorsmond/pen/aOPPPp

Trying to get the layout similar to the Chrome browser I changed the layout-fill style to use a min-height of 0 and now the layout in Edge looks the same as in Chrome.

`div > [layout-fill] {
  min-height: 0;
}`

Pen: http://codepen.io/qorsmond/pen/vObxae

So my question is this the right way to do it? Or is there something else stinking in my code?

**Comment by topherfangio** [comment]
Instead of `min-height: 0`, can you try `height: inherit`? We're looking at adding this in another place and it would be nice to know if it fixes it here.

In fact, could you just try adding `.layout-column { height: inherit }` to your CSS and see if that fixes it?

**Comment by qorsmond** [comment]
I tried `height: inherit` and `.layout-column { height: inherit }` on the codepen as suggested but it is not displaying correct in MS Edge. It seems only `min-height: 0;` is working in this case.

**Comment by topherfangio** [comment]
@qorsmond Interesting, thanks for the update. We'll definitely take a look.

**Comment by qorsmond** [comment]
It seems with the release of 0.11.0 my workaround using `min-height: 0;` is not working any more.

**Comment by qorsmond** [comment]
I tried again with v1.0.0-rc1 and I got the layout to work cross browser.

http://codepen.io/qorsmond/pen/YyLVJo

I applied `min-height: 0;` to the container that houses the 2 panels and it is working.

I think we can close this issue now.
