### ISSUE TITLE
md-backdrop on md-select is open never is removed

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/material#4039]
when open md-select the Angular-Material add in DOM md-backdrop but in Android or iOS when the user click in md-backdrop he not removed and the user is locked in this step, can someone help me?

**Comment by sanketsaurav** [comment]
Which version are you on? This seems to have been fixed in v0.10.1-rc5.

**Comment by GustavoCostaW** [comment]
thx @sanketsaurav
