### ISSUE TITLE
md-slider add option for real time events

### ISSUE THREAD

**Issue by elubin** [angular/material#4040]
Please modify the md-slider to have an option that updates my model in real time as the user is sliding the control, rather than waiting until they let go before updating my model.

**Comment by dustinblad** [comment]
Just remove the **md-discrete** directive from your <md-slider> tag.
**Example with md-discrete**
```html
<md-slider flex class="md-primary" md-discrete  ng-model="query.imgsize"
step="1" min="50" max="90" aria-label="rating"></md-slider
```
