### ISSUE TITLE
md-dialog is receiving duplicated ESCAPE key events

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#4041]
When you press ESCAPE in a dialog, the dialog will get a duplicated key event (I checked by checking event.timestamp). preventDefault/stopPropogation don't work with the dialog because the dialog is getting a different one.

Here's the codepen.

http://codepen.io/anon/pen/pJGdap

At first I thought this was something to do with md-autocomplete, but I added md-select and the issue appears there too. To test, press escape with the autocomplete or select open.

I was searching for the reason why and I couldn't exactly figure it out. It might be related to async events.

Edit: I think I figured it out. md-dialog is watching for keyup while md-autocomplete is preventing keydown

**Comment by clshortfuse** [comment]
@ThomasBurleson I noticed a lot of md-dialog's code looks for keyup instead of keydown. I didn't build a PR because I think there might be something I'm missing.

**Comment by ThomasBurleson** [comment]
@clshortfuse - please retry with the latest changes from master. Dialog, Select, Menu, and Toast all have  improvements.

**Comment by clshortfuse** [comment]
It still persists. 

I made changes in my personal fork and those fixed the issue:

https://github.com/clshortfuse/material/commit/95faaebc6f8c606f8d7462b2ced949dc43d0b0a0

https://github.com/clshortfuse/material/commit/cbb14b88257d53188efc5537cb166f57e06ba7e1

I didn't make a PR for it though. 

I would suspect bottomsheet would have the same issue.

https://github.com/angular/bower-material/search?utf8=%E2%9C%93&q=keyup

vs

https://github.com/angular/bower-material/search?utf8=%E2%9C%93&q=keydown
