### ISSUE TITLE
Tabs Animation Broken with Angular 1.4.1

### ISSUE THREAD

**Issue by weiway** [angular/material#4042]
The animation of tabs seems to be broken with Angular 1.4.1, works fine with Angular 1.3.5

Here is a codepen reproducing the problem:
http://codepen.io/anon/pen/rVPpzX

**Comment by afief** [comment]
thanks, i spend hours to figured it out why my tabs animation is lagging. :)

**Comment by afief** [comment]
it is OK with Angular 1.4.0, but the tabs label are not centered

**Comment by ThomasBurleson** [comment]
This is working with the latest code in Angular Material master and recent fixes to use ngAnimate 1.4.x features. See updated [Demo](http://codepen.io/ThomasBurleson/pen/eNxqbO)

**Comment by weiway** [comment]
Thanks!
