### ISSUE TITLE
Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by jmogollon-tild** [angular/material#4044]
When using md-select inside an md-menu I am getting the following error: "Cannot read property 'removeChild' of null". After debugging the code I concluded that the cause might be that the md-select removes its backdrop when it is closed and, after that, when closing md-menu, it also tries to remove the same backdrop that it is indeed null.

I think that the error may be fixed checking if `scrollMask[0].parentNode` (line 583 angular-material.js) is not null before performing `scrollMask[0].parentNode.removeChild(scrollMask[0])` like so: 

```javascript
if(scrollMask[0].parentNode != null) {
   scrollMask[0].parentNode.removeChild(scrollMask[0]);
}
```

You can reproduce the error in the next [codepen 
](http://codepen.io/anon/pen/JdxLbe)

If am I right, could you fix it? Otherwise,  could you tell me if I am using the directive in a wrong way?

**Comment by ThomasBurleson** [comment]
@jmogollon-tild - can you confirm this problem still exists with the latest code from #master ?

**Comment by ThomasBurleson** [comment]
Nesting of Select and Menu components are not supported.
