### ISSUE TITLE
md-autocomplete focus error

### ISSUE THREAD

**Issue by piyushchauhan2011** [angular/material#4046]
![screen shot 2015-08-06 at 5 55 57 pm](https://cloud.githubusercontent.com/assets/693487/9106559/85b59e94-3c64-11e5-86ff-c682c38e453d.png)

I included the md-autocomplete

![screen shot 2015-08-06 at 5 57 40 pm](https://cloud.githubusercontent.com/assets/693487/9106577/ad1c9352-3c64-11e5-94f4-7958706d69b2.png)

and I'm getting this weird behavior of `focus` and `unfocus` first time and then next time the above error. The autocomplete is rendered inside `mdDialog`.

**Comment by elubin** [comment]
I have a similar issue.  I don't get that error, but focus is getting lost on my page.  TAB fixes is on my desktop browser, but there is no workaround on my phone or ipad.  It can be recreated on an ipad with this fiddle.

http://jsfiddle.net/5m9rpcrn/

**Comment by robertmesserle** [comment]
@piyushchauhan2011 @elubin Can either of you provide steps to recreate this on a Mac or PC?  It will be a lot easier to debug if so.

**Comment by elubin** [comment]
Hi Robert.  Thanks for looking...

Can you see the fiddle?  http://jsfiddle.net/5m9rpcrn/

try that fiddle from an ipad or you should be able to recreate on desktop by clicking 'launch modal', then select something from the list, hit tab a whole bunch of times to remove focus.  You can no longer put back the focus or do anything.

**Comment by robertmesserle** [comment]
@elubin Is this still an issue?  I am unable to recreate this.

**Comment by elubin** [comment]
@robertmesserle focus seems better, however, if you click 'launch' button, pick 'apple', then click 'pick something' to open the drop again, then TAB, the open list stays open.  you can then click anywhere on the screen and the list never goes away.  ( i *think* because i didn't move the mouse over the list, i just clicked 'pick something' and then tab key.

**Comment by elubin** [comment]
@robertmesserle is this is master so i can try it against my full project?
