### ISSUE TITLE
md-select: ng-repeat for md-options - undefined arguments

### ISSUE THREAD

**Issue by tuchk4** [angular/material#4048]
Here is example (run with opened console) http://codepen.io/anon/pen/VLgWeO?editors=101
JS:
```js
 $scope.sizes = [{
        id: 1,
        name: "small",
      }, {
        id: 2,
        name: "medium",
      }, {
        id: 3,
        name: "large",
      }, {
        id: 4,
        name: "insane",
      }];
    
      $scope.showSizeTitle = function(size, index) {
        console.log(size, index);
        return size.name + ' #';
      }
```

Template
```html
 <md-select name="sizes" ng-model="size" placeholder="Size">
  <md-option ng-repeat="size in sizes track" ng-value="{{size}}">
    <p>
      {{ showSizeTitle(size, $index) }}
    </p>
  </md-option>
</md-select>
```

**showSizeTitle** function is inside **ng-repeat="size in sizes"** so when it is called - that means that **$scope.sizes** exists. But in example function is called for a few times and arguments are undefined 
($index is also undefined).

But if remove attr @name from **md-select** - this case will work correctly

**Comment by ThomasBurleson** [comment]
This no longer appears to be an issue with the lastest code [and updated mdSelect] from master.
http://codepen.io/ThomasBurleson/pen/jPddbg
