### ISSUE TITLE
mdSnackbar - full-width, no-margin variation of Toast

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4050]
mdSnackbar - a variation of the existing mdToast should be provided: Snackbars. Use the [Material Design Specification](https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs) for guidance.

**Comment by mckenzielong** [comment]
After looking at the spec, it seems like mdToast is probably closer to an mdSnackbar than it is proper toasts... apparently toasts can't be swiped away, and do not contain actions.

> Android also provides a toast, primarily used for system messaging. Toasts are similar to snackbars but do not contain actions and cannot be swiped off screen

Is this item targeted at swipe-able snackbar? At quick glance, toasts and snackbars seem ridiculously similar.

**Comment by NickBolles** [comment]
Doesn't $mdToast satisfy both parts of the spec, a Snackbar, and a toast? like @mckenzielong said.

Maybe the only thing missing is an option to make the toast non-swipeable?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
