### ISSUE TITLE
Layout-Align fails for <md-button> with <md-icon> and Text

### ISSUE THREAD

**Issue by nkoterba** [angular/material#4051]
Demo shows it best.

Using latest chrome.

Using latest MD source (via CDN).

http://codepen.io/anon/pen/qdgQMG

I have `layout-align="start start"`, but the icon and text are ALWAYS centered in button.

Does `<md-button>` not support children alignment?

**Comment by topherfangio** [comment]
Can you double-check your demo? All I see on it are a bunch of tabs.

**Comment by nkoterba** [comment]
@topherfangio Nevermind.  

1) I obviously used that codepen for another MD test/demo/issue report and overwrite my original issue.

2) With MD 0.11, I was able to get things working the way I want.  See this code pen: http://codepen.io/anon/pen/KddwJY

Since I can't re-create the original codepen and I can do what I want with inner divs, etc. I think this issue can be closed.

Thanks for hte follow-up!
