### ISSUE TITLE
mdInput: issue with textarea height and ngShow

### ISSUE THREAD

**Issue by pdf13** [angular/material#4053]
**Steps to reproduce:**
1. Initialize a variable with a long string
2. Create a textarea with ngModel binding this variable
3. Set textarea hidden using some ngShow condition
4. Change condition to show textarea after controller and view were loaded
5. See that textarea has a default height and only fits text height when input is focused and any key is pressed

**angular-material version:** 0.10.0

**Error reproduced at:** http://codepen.io/anon/pen/yNZQxK

**Comment by innerpeace0** [comment]
Focusing on the textarea does nothing, either. `CTRL + A` and `CTRL + end` both bring the text area to the right size after it has focus. Good catch @pdf13. I'm going to need this fixed for my projects.

**Comment by topherfangio** [comment]
Still appears to be an issue in master (along with some other issues).

http://codepen.io/topherfangio/pen/YyjvJj

Will investigate soon.

**Comment by EladBezalel** [comment]
This is already supported,
You should use `md-detect-hidden` attribute on the `textarea` element
http://codepen.io/EladBezalel/pen/VewYRL

**Comment by pdf13** [comment]
Great @EladBezalel !!!!!
Thank you
=)

**Comment by EladBezalel** [comment]
Np :)

**Comment by mark-langer** [comment]
@EladBezalel Does the md-detect-hidden directive still exist? I couldn't find it in the source code of input.ts or autosize.ts in /src/lib/input/

**Comment by FlavaSava7** [comment]
The solution by @EladBezalel is not working when the text-area is being used inside of a wizard with ng-show on the wizard
