### ISSUE TITLE
md-sliders with input fields had a broken behavior in chrome

### ISSUE THREAD

**Issue by se-panfilov** [angular/material#4055]
Chrome (44.0.2403.130 Ubuntu 14.04 (64-bit) (and same isssue on mac))

Take a look on this
https://material.angularjs.org/latest/#/demo/material.components.slider

![ScreenShot](https://habrastorage.org/files/02c/1d3/aa0/02c1d3aa069449e588ff187647bbe2cd.png)

Sliders covers inputs.

But it's all ok in Chromium (43.0.2357.130 Ubuntu 14.04 (64-bit))

![ScreenShot](https://habrastorage.org/files/112/a59/ea3/112a59ea37234c4aab10b15ef466f5c8.png)

**Comment by ngraef** [comment]
This is actually an issue with the sizing of the input, not the slider. The width of the input is never defined, either by css or flex layout, so it gets defined by the browser. I imagine that calculation is what changed between browser versions.

Here's the code from the demo:
```
<div flex="20" layout layout-align="center center">
    <input type="number" ng-model="color.red" aria-label="red" aria-controls="red-slider">
</div>
```

Adding `flex` to the `input` solves this issue.

**Comment by se-panfilov** [comment]
Thanks, that's nice

**Comment by ngraef** [comment]
This should be reopened, as the docs need to be fixed.

**Comment by ThomasBurleson** [comment]
@ngraef - Good catch.
