### ISSUE TITLE
Cannot select md-tab IE11

### ISSUE THREAD

**Issue by GitOfThomas** [angular/material#4056]
I just tested this code : 

~~~
<md-tabs md-align-tabs="'top'" md-stretch-tabs='always' md-selected="0">
    <md-tab id="tab1">
    	<md-tab-label>View 1</md-tab-label>
    </md-tab>
    <md-tab id="tab2">
    	<md-tab-label>View 2</md-tab-label>
    </md-tab>
    <md-tab id="tab3">
    	<md-tab-label>View 3</md-tab-label>
    </md-tab>
</md-tabs>
~~~

It is working well on Firefox & Chrome. Unfortunately, in IE11, I cannot select any other tab. Indeed, when I click on another tab, there is no animation (with the bottom line moving) and my tab does not appear as selected. Moreover, the tabs don't show up in IE11 if I don't include the "md-stretch-tabs='always'" directive.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by robertmesserle** [comment]
This appears to work fine in IE11 when tested against HEAD.
