### ISSUE TITLE
Elements stay fixed when scroll happens

### ISSUE THREAD

**Issue by francorisso** [angular/material#4057]
Every time I scroll, the options for the md-select element stay in their original position, it should change when I scroll, so it always show on top of the select element.

![captura de pantalla 2015-08-07 a las 9 38 05](https://cloud.githubusercontent.com/assets/7562249/9135879/2d5dc076-3ce8-11e5-841c-1f1569041af6.png)

The same happens with the toast element, that has position absolute instead of fixed. I think this is an error.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.
