### ISSUE TITLE
mdAutocomplete should set mdSelectedItem on blur if a suggestion is highlighted

### ISSUE THREAD

**Issue by 120psi** [angular/material#4058]
I was surprised to discover that tabbing out of an mdAutocomplete didn't set the selected item to the highlighted suggestion.  Tabbing through controls is common user behavior, and needing to press ENTER to select the item is not something users are trained to do for inputs.

**Comment by ngraef** [comment]
Works for me on master, Chrome v46. And [the code looks correct](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L364). Maybe a browser issue?

**Comment by topherfangio** [comment]
I feel like we might want to get some feedback from UX team about this. To me, the autocomplete feels like a fancy select box with a search, so my preference would be that it follows the standard HTML select behavior which requires you to hit enter or spacebar to select.

The HTML select even disables tabbing altogether, which may or may not be a good default. It does ensure that people can't accidentally close it by tabbing, but it might be nice to have two ways to cancel (escape and tab).

@ThomasBurleson @jelbourn @marcysutton Do you guys have thoughts on this?

**Comment by 120psi** [comment]
When mdAutocomplete uses floating label styling, it looks like a text input
which sets user expectations for it to behave more like a text input.

**Comment by matthiasg** [comment]
whatever is decided it should be consistent across different types of autoselect .. in 0.11 rc right now it selects with tab (which i like) and in the text examples it does not ..
