### ISSUE TITLE
md-virtual-repeat does not render items if they are not available on initialization

### ISSUE THREAD

**Issue by josephperrott** [angular/material#4059]
The virtual repeater does not render the items if the list iterated over is empty on initalization of the directive.  I created a codepen to verify and found that if the array items are not available on inital render, they are not rendered until scrolling occurs.

http://codepen.io/josephperrott/pen/ZGPYXZ

**Comment by jelbourn** [comment]
@kseamon was one of your existing PRs something that addressed this?

**Comment by kseamon** [comment]
https://github.com/kseamon/material/commit/016ca6967e981f6edd7fa2b9d880be637f115eb5

**Comment by ThomasBurleson** [comment]
Should be fixed with SHA 016ca696
