### ISSUE TITLE
Just can't use ngMaterial - get inject errors no matter what I try??

### ISSUE THREAD

**Issue by jeffthompson1971** [angular/material#406]
For some reason I can't inject ngMaterial into my controller.   I've looked aroudn on the web, saw some comments that need angular 1.3.. i've  tried every angular version 1.3.x (i.e. rc0, rc1 rc2 etc) but no matter what I try, when I try to inject it as a dependency I get the usual (useless) angular inject error.

Note this is a well architected angular app and works across the board with any other angular directive i've included.  I've tried removing other things like ngAnimate etc. and basically tried removing everything else.  makes no difference. Only fails with ngMaterial, which I _REALLY_ want for my UI :)

Please help!

My app is an angular-on-steroids app....Here are my includes:

<script src="http://localhost/cordova.js"></script>

<script src="/components/steroids-js/steroids.js"></script>

  <script src="/bower_components/jquery/dist/jquery.min.js"></script> 
  <script src="/bower_components/angular/angular.min.js"></script>
  <script src="/bower_components/angular-material/angular-material.js"></script>

  <script src="/bower_components/angular-animate/angular-animate.min.js"></script>

With a very basic controller:
var commonApp = angular.module('commonApp', ['jmdobry.angular-cache', 
    'angularLocalStorage',
     'ionic',
     'ngAnimate',
         'ngMaterial'
     ])

.controller('IndexCtrl', function ($scope, $log,  $ionicSideMenuDelegate) {
   ...
    }
...
The usual useless error here:
"Error: [$injector:modulerr] http://errors.angularjs.org/1.3.0-rc.4/$injector/modulerr?

**Comment by ddatta** [comment]
faced the same issue, added ngAria as a dependency and it worked.
