### ISSUE TITLE
md-icon with class is not using default fontset

### ISSUE THREAD

**Issue by zimyand** [angular/material#4060]
Apparently this CL https://github.com/angular/material/commit/f5a9101a59f5cf51cb204399ecd45425305e14b9 broke us.

It used to add a class that is specified by 

    $mdIconProvider.defaultFontSet('material-icons-extended')

But now it's not adding the class because of this check https://github.com/angular/material/commit/f5a9101a59f5cf51cb204399ecd45425305e14b9#diff-ae311e811f650092284f179738826496R258

    !attr.hasOwnProperty('class') 

So the following code is not working:

    <md-icon class="someClass">close</md-icon>

**Comment by jelbourn** [comment]
@ThomasBurleson

**Comment by jelbourn** [comment]
Fixed via 1daa8bcef7b737ee8a7876414fe1f0b5eef01ce2
