### ISSUE TITLE
Tabs directive md-no-pagination not working

### ISSUE THREAD

**Issue by TimMeissner** [angular/material#4065]
See this CodePen for demonstration: http://codepen.io/TimMeissner/pen/KpEzmK

When using the attribute md-no-pagination on the md-tabs directive, the tabs look very ugly.
Also on the first example (left sidebar) there shouldn't be any pagination (arrows disappear, when selecting a tab).

**Comment by miclaus** [comment]
+1

pagination arrows disappear for me as well after selecting a tab .
