### ISSUE TITLE
flex and offset not working properly in real mobile devices.

### ISSUE THREAD

**Issue by joshilomas** [angular/material#4068]
The below code works fine in laptop browsers but not on mobile.

```
<div layout="row">
	<md-content class="md-padding" flex="100" flex-gt-md="50" offset-gt-md="25">
        </md-content>
</div>
```

flex responsive only working in laptop browsers but not on mobile.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by ThomasBurleson** [comment]
Unable to reproduce.
