### ISSUE TITLE
md-icon does not render when class attribute is present

### ISSUE THREAD

**Issue by sanketsaurav** [angular/material#4069]
When a `class` attribute is present on the `<md-icon>` directive, the icon fails to render. This was working in v10.0.0, but in v0.10.1-rc5, it's broken. When there is no `class` attribute present, the icon renders fine.

Edit: When the class is added using `ng-class`, the icon renders fine.

**Comment by siulung4073** [comment]
I saw in the change log before on one of the RC releases as a breaking change. 
Now it is listed as a Bug Fix: 

icons: improve use of material-icons style (dab30b34, closes #3333)

which says: 

Improve logic to auto-add `.material-icons` style to **md-icon**.
> NOTE: will not auto-add if using any class or ng-class attributes; see demoFontIconsWithLigatures

**Comment by norkunas** [comment]
If this is intended, i think it should work at least only if using md-hue classes.

**Comment by joalcega** [comment]
<md-icon> renders with classes only if it is inside of a <p> element.

**Comment by innerpeace0** [comment]
+1

**Comment by warpdesign** [comment]
+1

Possible workaround: add md-font-set="<yourset>" and it will work without having to remove the class you added.

**Comment by programmist** [comment]
@sanketsaurav I'm unable to reproduce this issue.  The [md-icon demos](https://material.angularjs.org/latest/#/demo/material.components.icon) all use a class attribute and they seem to display properly.  Could you help me reproduce this?

**Comment by programmist** [comment]
I've also tried, unsuccessfully, to reproduce the via codepen using the latest snapshot.
http://codepen.io/programmist/pen/avNzyX

It's been a week since my last message, so I'm closing this issue.  If you continue to experience problems feel free to re-open.
