### ISSUE TITLE
md-menu does not render properly in Firefox

### ISSUE THREAD

**Issue by acondiff** [angular/material#4070]
`<md-menu>` does not render correctly in Firefox. 

![Image of md-menu](https://s3.amazonaws.com/f.cl.ly/items/1L0w223A0V3d3X0p3F38/Screen%20Shot%202015-08-09%20at%202.48.54%20AM.png)

This screenshot was taken [right on the Material Angular website](https://material.angularjs.org/latest/#/demo/material.components.menu).

**Comment by sanketsaurav** [comment]
This seems to be fixed  in v0.10.1-rc5.

**Comment by rschmukler** [comment]
Closing as fixed.

**Comment by martinstolz-ch** [comment]
problem still exists:

![md-menu-firefox](https://cloud.githubusercontent.com/assets/1113611/16419255/4c86af06-3d4d-11e6-85b8-13b8847cac4d.png)
