### ISSUE TITLE
First item in md-menu is selected upon opening

### ISSUE THREAD

**Issue by acondiff** [angular/material#4071]
The first item in md-menu is always selected upon opening the menu. This can lead to some UX concerns as the user may assume it is already selected or disabled.

**Comment by zlovin** [comment]
I've submitted an issue for this already in #3352, it was set to backlog.

**Comment by sunnyshah01** [comment]
+1

**Comment by mattdanna** [comment]
+1

**Comment by ThomasBurleson** [comment]
Duplicate

**Comment by meshrajk** [comment]
This issue is doesn't look like it resolves  #3352. These are two different directive and mdSelect still has that issue. Unless i'm using the wrong version (I'm using v1.1.4)
