### ISSUE TITLE
md-auto-complete not allowing to click outside after clicking close button in it.

### ISSUE THREAD

**Issue by ramanathan92** [angular/material#4075]
Scenario : 
If user clicks auto-complete close button after page loads(when auto-complete having default selected one in box).

Problem : 
After clicking close button click outside the auto-complete box, page will get locked(nothing is working,If you tries to click somewhere is not working). We need to refresh page to make it work again as normal.

**Comment by robertmesserle** [comment]
This seems to be resolved in the latest code.  Please reply if this is still an issue.

**Comment by ramanathan92** [comment]
No it is not resolved in latest code also.Still am facing this problem,after upgrading to 0.11.2

**Comment by topherfangio** [comment]
@ramanathan92 Can you try against 0.11.2 or master? We've made some additional updates to the autocomplete recently.

**Comment by robertmesserle** [comment]
@ramanathan92 Can you provide a CodePen demonstrating the issue?  I have been unable to reproduce.

**Comment by ramanathan92** [comment]
sure am working on it.I will provide you that.
