### ISSUE TITLE
Md-Menu within md-toolbar creates page scroll when clicked 

### ISSUE THREAD

**Issue by viztastic** [angular/material#4076]
This is similar to issue #3818 except that it happens when I include the md-menu in an md-toolbar it appears fine. But when I click on the menu, it creates a page scroll. See before and after images below for reference (running latest version of Google Chrome at time of posting):

Before click (no page scroll-bar)
http://screencast.com/t/zYJsVx7v

After click (page click)
http://screencast.com/t/UHFnmNIs4

Code snippet below fyi:

    <md-toolbar layout-padding class="sls-header" ng-controller="homeNavCtrl">
     <div class="md-toolbar-tools" layout="row" layout-padding layout-margin>
      <h1 class="md-display-2"><span>App</span></h1>
      <span flex></span>

      <md-menu md-position-mode="target-right target" ng-show="isAuthenticated()">
          <md-button aria-label="Open demo menu" class="md-icon-button" ng-click="$mdOpenMenu()">
            <md-icon md-menu-origin md-svg-src="/svg/ic_person_24px.svg" class="sls-person-ico"></md-icon>
          </md-button>
          <md-menu-content width="4">
            <md-menu-item ng-repeat="item in [1, 2, 3]">
              <md-button ng-click="ctrl.announceClick($index)">
                <p>Option {{item}}</p>
                <md-icon md-menu-align-target md-svg-src="/svg/ic_place_24px.svg"></md-icon>
              </md-button>
            </md-menu-item>
          </md-menu-content>
       </md-menu>
      <md-button  ui-sref="home" class="sls-btn-whitebg">
        Home
      </md-button>
      <md-button  class="sls-btn-whitebg" ui-sref="page2">
        Page 2
      </md-button>
      <md-button ng-hide="isAuthenticated()" ui-sref="signin" class="sls-btn-whitebg">
        Sign in
      </md-button>
    </div>
    </md-toolbar>

**Comment by vivek3003** [comment]
This issue occuring for me too. 
Moreover if the toolbar is fixed to the top and the page height is large ( scroll bar is required), the menu position is not set correctly when scrolling down. Please refer this pen,

http://codepen.io/vivek3003/pen/RPdqgm?editors=100

**Comment by rschmukler** [comment]
This appears to be fixed on master. Please re-open if not. Thanks!

**Comment by sumodevelopment** [comment]
I just downloaded and I think there is still an issue here. When I click the md-menu button top open the menu, `overflow-y: scroll` is appended to the body tag. Also, the body scrolls to the top when opening the menu, 

I also have a `md-tall` class on my toolbar, and it is at a fixed position.  Here is a sample of my toolbar

```html

<md-toolbar id="toolbar-dashboard" class="md-tall toolbar-fixed">
<div class="md-toolbar-tools">
<md-button class="md-icon-button" aria-label="Back">
 <md-icon>arrow_back</md-icon>
    </md-button>
    <span flex></span>
    <h2>Choose a product</h2>
    <span flex></span>
    <md-menu md-position-mode="target-right target">
        <md-button aria-label="Open demo menu" class="md-icon-button" ng-click="$mdOpenMenu($event)">
            <md-icon md-menu-origin>more_vert</md-icon>
        </md-button>
        <md-menu-content width="4">
            <md-menu-item>
                <md-button ng-click="goToPage('settings')">
                    <div layout="row">
                        <p flex>Settings</p>
                        <md-icon md-menu-align-target style="margin: auto 3px auto 0;">settings</md-icon>
                    </div>
                </md-button>
            </md-menu-item>
            <md-menu-divider></md-menu-divider>
            <md-menu-item>
                <md-button>
                    <div layout="row">
                        <p flex>Logout</p>
                        <md-icon md-menu-align-target style="margin: auto 3px auto 0;">account_circle</md-icon>
                    </div>
                </md-button>
            </md-menu-item>
        </md-menu-content>
    </md-menu>
</div>
</md-toolbar>

**Comment by RichOren** [comment]
This hasn't been fixed

**Comment by rseigel** [comment]
I was seeing the same issue when using md-menu within a fixed element, but I fixed it by specifying top (bottom) and left (right) attributes on the fixed element.
