### ISSUE TITLE
Chips: way to disable input validation

### ISSUE THREAD

**Issue by Masadow** [angular/material#4077]
In my state, I have an input which when submitted (with enter key), it creates a new chip containing the input value. then the input is cleared.

Problem is that material is adding a ng-valid class to that input with no reason, there is no specific rules enabled and in my case, it does not make any sense to turn the input green when it is emptied.

It should be possible to turn of input validation on a per input basis

**Comment by bakhlov** [comment]
I have 2 fields on the UI.
The second field visibility depends on what I type on the first one.
When I submit the form I expected the following behavior:
- do not see validation errors on the second field if it in the hidden state. 
- to see validation errors on the second field if it in the visible state.

**Comment by topherfangio** [comment]
@bakhlov Please ask your question on our [Forums](https://groups.google.com/forum/#!forum/ngmaterial). GitHub is reserved for bugs/issues only.
