### ISSUE TITLE
md-tooltip background color displaying partially at random times

### ISSUE THREAD

**Issue by smitty02001** [angular/material#4081]
I am using tooltips through out my application and sometimes the background color only displays half way.  My text label is white and the background color is red. When it happens the white text blends into the white background making the tooltip impossible to read.

I can never reproduce it consistently but it does happen. Is this a known issue and/or has other developers experienced this issue?

**Comment by thenextvoz** [comment]
I noticed this issue, too. Will try to capture a screen shot. Problem is it happens randomly without any obvious usage pattern. Hard to reproduce.

**Comment by SanderElias** [comment]
I was not able to reproduce this. If someone can create a demo that exposes this behavior, I will investigate the root cause
