### ISSUE TITLE
md-no-bar not working on md-tabs

### ISSUE THREAD

**Issue by nkoterba** [angular/material#4082]
Demo: Using latest chrome, Angular 1.4.3, and master.

http://codepen.io/anon/pen/eNXMqj

Screenshot:
![image](https://cloud.githubusercontent.com/assets/2508944/9177322/9745961c-3f5e-11e5-866f-d3e8e5a8a2a0.png)

My understanding was that `md-no-bar` would hide the **active** tab bar.

I believe that was the behavior in the past.

**Comment by smashercosmo** [comment]
Yes, that's definitely a bug. It was working in previous versions.

**Comment by chrisguerrero** [comment]
+1

**Comment by sscovil** [comment]
Here is the fix I've used until this issue is resolved:

```css
md-tabs[md-no-bar] md-ink-bar {
    display: none;
}
```

**Comment by axisofentropy** [comment]
+1

**Comment by amritk** [comment]
+1

**Comment by p-mcgowan** [comment]
+1

**Comment by robertmesserle** [comment]
@nkoterba This is a documentation error - this should have been `md-no-ink-bar`

**Comment by ThomasBurleson** [comment]
@here :+1:  Nice catch
