### ISSUE TITLE
mdFabSpeedDial/Toolbar: Refactor to work and behave more like mdMenu

### ISSUE THREAD

**Issue by topherfangio** [angular/material#4083]
We need to refactor the mdFabSpeedDial and mdFabToolbar to work more like mdMenu.

This may include:

1. Having a `md-fab-content` directive instead of two `md-fab-trigger` and `md-fab-actions`
2. Potentially using interimElement service to show speed dial/toolbar actions/content
3. Refactoring into a single `<md-fab>` component?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (401/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:49615 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZA-001YxF-UN
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:42 +0200
Date: Thu, 28 Apr 2016 13:28:00 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875280;
	bh=W5DUglS7hLuBFtV7za9onUGWWc6Dwh7ZvtSwG6JD1r8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ACLO3DlCS4WOiyJCZbYCCk7cCHqie4aDi2NxDC+VMbcCV/cRhWJmupcj9FeDYAQ7N
	 /zZSxYu0qIlgVO3QDE0merGcDHu2f30el6sZqPZFOveSE3RtBA/HEvf1vF7CHxcxg4
	 u6ke+RRpdRQKopnsLSf7ZwuGQ6gyXx1/1tE9NiLY=
