### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4084]
Consistent RTL support should be provided for basic components in Angular Material

**Comment by amitport** [comment]
:+1: 
Many elements work well, I think it will be helpful to list specific issues:

- [ ] __md-list__ - doesn't work with child `md-avatar`, `md-icon`, `md-checkbox`, `md-secondary-container`
- [ ] __md-tabs__ - only works when `md-stretch-tabs="always"` and `md-no-pagination="true"`
- [ ] __md-input-container__ - doesn't work with child `md-icon` and float description text

**Comment by olsynt** [comment]
Any progress ?

**Comment by ThomasBurleson** [comment]
These feature will be improved in **post-1.0** milestones

**Comment by EladBezalel** [comment]
@ThomasBurleson i think this should be closed as a dup of #1080

**Comment by ThomasBurleson** [comment]
Duplicate
