### ISSUE TITLE
$mdDialog doesnt support enter key

### ISSUE THREAD

**Issue by erslater** [angular/material#4085]
The Enter key on the dialog will close the dialog but doesnt raise any events.  I think it should trigger the ok button click at minimum and even better be able to specify what gets triggered on enter.

This issue makes it impossible to use correctly for any form input.

**Comment by hillerstorm** [comment]
+1

**Comment by ukrantv** [comment]
I have the same issue. Here is the demo: [Plunker](http://plnkr.co/edit/cHpsumhOUb0IZpeLGJpj?p=preview). Here is the question with the description: [mdDialog promise is not resolved when I hit Enter](http://stackoverflow.com/questions/33673993/mddialog-promise-is-not-resolved-when-i-hit-enter) Please tel me what am I doing wrong? Thank you

**Comment by charneykaye** [comment]
In my case, I solved this by moving the input field inside a `<form>` with `ng-submit="ctrlTimespan.save()"` where that expression implements `$mdDialog.hide(...)` from the DialogController.

**Comment by Mudin** [comment]
I solved by removing all type='button' in toolbar and removing type='submit' in submit button of mdDialog. instead of the that, I add ng-click="submitSomeForm()" to that button
