### ISSUE TITLE
$mdDialog height not adapting in IE11

### ISSUE THREAD

**Issue by smaye81** [angular/material#4086]
We are having an issue in our app with the height of `$mdDialog` in IE11.  This is able to be recreated on the Angular Material site by the following:

1.  In IE11, navigate to:  https://material.angularjs.org/latest/#/demo/material.components.dialog
2.  Open the Custom Dialog
3.  While open, drag the browser window from the bottom all the way to the top so thats its height is as small as it can go.  Then, drag it back to its original height.  

When dragging back, you will notice that the height of the dialog is still as it was when the browser window height was shrunk to the top.

![ie11dialogbug](https://cloud.githubusercontent.com/assets/911455/9180277/711c30fc-3f6f-11e5-9afb-92a18d88cc6d.png)

**Comment by KReden** [comment]
This looks like a problem that has been fixed is the RCs (it doesnt show up in rc5) so will likely be fixed in 0.10.1. You could update to rc5 or wait until 0.10.1 is released.

**Comment by smaye81** [comment]
Yep, I see that now.  Closing this issue.
