### ISSUE TITLE
Impossible to resolve a dialog with a boolean (always returns true)

### ISSUE THREAD

**Issue by glebm** [angular/material#4094]
This is due to this line in interimElement: https://github.com/angular/material/blob/d9ba0e13a5abca05d6afa3b3b781b0dc7677183f/src/core/services/interimElement/interimElement.js#L314 (and L339):

```js
.remove(reason || SHOW_CLOSED, false)
```

Instead of using `||` this should check for `undefined`.

**Comment by dmackerman** [comment]
Couldn't you just use `.cancel()` on the `mdDialog` instance to return `false`?

**Comment by glebm** [comment]
This is not what cancel does. 

Example: Imagine an unsaved changes dialog that triggers on some action, with three buttons:

> You have unsaved changes.
> * Cancel or click outside the dialog: `cancel()`
> * Exit without saving: `resolve(false)`
> * Save and exit: `resolve(true)`

**Comment by dmackerman** [comment]
Why is "Exit without saving" any different than "Cancel"? Am I missing something?

**Comment by glebm** [comment]
Exit without saving reverts the changes and exits. Cancel does not revert the changes, and does not exit.

**Comment by ThomasBurleson** [comment]
Cancel should resolve the Dialog promise with "false".

**Comment by glebm** [comment]
Cancel should reject the promise.

**Comment by mighe** [comment]
Same issue here.
I agree that most of the times we can use `cancel` to get the desired behaviour, but we also expect that the  every parameter passed to the `$hide` function will be found unchanged in the promise.
At the moment if we pass `false` or `undefined` to `cancel`, in the promise resolution we have `true`
