### ISSUE TITLE
md-input display not correct with textarea and placeholder

### ISSUE THREAD

**Issue by konzuk** [angular/material#4096]
In the picture show the problems: 
1. the placeholder is not display correctly.
2. the textarea , the label is too height from the input

http://plnkr.co/edit/NXVoWVRdPRn2riSmYAGy?p=preview

![untitled](https://cloud.githubusercontent.com/assets/9130742/9202994/bb45a7ac-407e-11e5-91da-e7a66b0ba2ba.png)

**Comment by mckenzielong** [comment]
#2 is fixed in master.
#1 is coming from 'md-icon-float' being added to the input container.  Specifically this bit here:

```javascript
    if ( inputContainer.element.find('label').length == 0 ) {
      if (inputContainer.input && inputContainer.input[0].nodeName != 'MD-SELECT') {
        var placeholder = '<label ng-click="delegateClick()">' + placeholderText + '</label>';

        inputContainer.element.addClass('md-icon-float'); // <--- here
        inputContainer.element.prepend(placeholder);
      }
    }
```

Out of curiosity, should there be a check to see if the container has an md-icon before assigning this class? and does that check have to rely on the label tag being missing?

**Comment by satheesh786** [comment]
<md-input-container >
                    <label>Notes</label>
                    <textarea>.......</textarea>
 </md-input-container>

reduce default min height and height in the concerned css file.

for ex:
default values are:
Minheight=56
height=60

Change them based on your requirement.
