### ISSUE TITLE
Add more toolbar examples

### ISSUE THREAD

**Issue by jsenecal** [angular/material#4097]
The toolbar demo page is missing information on how to achieve the variants that are shown there:
https://www.google.com/design/spec/layout/structure.html#structure-toolbars

Notably, getting the toolbar to have this look is something I am currently struggling with (with the buttons and all):
![Full-width, extended height app bar](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7UnNtdkNxY05oelk/layout_structure_toolbars2.png)

**Comment by NickBolles** [comment]
If your just looking for the buttons isnt the first demo on this ( https://material.angularjs.org/latest/#/demo/material.components.toolbar ) page enough?
possible dupe of #1054 if your looking for something like the title and flexible space
PR in the works here: #3735  for flexible space

**Comment by jsenecal** [comment]
Yes #3735 is what I was looking for that specific example (thanks) but many other toolbar usages are not covered as per the spec.

**Comment by EladBezalel** [comment]
Closing as this is a dup of #1054
