### ISSUE TITLE
How to know the exact CSS code of a certain animations?

### ISSUE THREAD

**Issue by Ian-Y** [angular/material#4099]
I'm unable to include Angular Material's CSS and JS files directly into my webpage because that would affect my other elements. But I need an animation from Angular Material.

The only thing I could do is copy the corresponding Angular Material's CSS code into my CSS code.

Precisely, the animation I need is the dropdown show on [this page](https://material.angularjs.org/latest/#/demo/material.components.select). I need to know its CSS code <code>transition</code> of opening and closing. I had tried inspecting the dropdown element in order to know grab <code>transition</code> code but had no luck.

Is there a way to know the exact <code>transition</code> code?

P.S. I only need CSS and don't need the JS re-position function.

**Comment by KReden** [comment]
You should ask this over on the angular material boards https://groups.google.com/forum/#!forum/ngmaterial

**Comment by Ian-Y** [comment]
@KReden Thank you. I had posted there.
