### ISSUE TITLE
SEO with PhantomJS generated pages and about 500k of styles

### ISSUE THREAD

**Issue by jlmagee** [angular/material#4104]
Finally got to the point of SEO development and testing for a new Material Design-based site. After getting all the infrastructure in place using the https://github.com/steeve/angular-seo approach which I've used for a plain angular site, I was shocked to discover that PhantomJS creates about 500k of Styles which were generated by Material Design. It is not a surprise that no Webmaster tools would handle this and one wouldn't expect search bots to do so either. 

As a crude workaround, I've taken the styles generated by PhantomJS and created a CSS file for use in the project. Then modified the theming code to never generate the style elements. It won't be very flexible but it will work for now.

For both static page generation and for performance, something really needs to be done about this situation. Having an additional 3000 to 5000 styles with just colors can't help rendering performance. It would seem straightforward enough to only create dynamic styles as the page content requires them as a start. 

Solution oriented feedback requested.

**Comment by dmackerman** [comment]
Yeah, I think the theming system as a whole is a bit over the top. We end up overriding a lot of the Material base styles anyway.

**Comment by AleksueiR** [comment]
+1

**Comment by nathanmarks** [comment]
+1, I agree with @dmackerman when he says it is over the top. I wish it were simpler to adjust things and optimize for performance at the same time.

**Comment by ThomasBurleson** [comment]
@jlmagee Please retest with the latest release of v0.11.0-rc1. We reduce the number of injected theme styles, reduced the styles for ProgressCircular, and refactor styles for Layout (flex, layout, etc).

**Comment by jlmagee** [comment]
@ThomasBurleson OK. I'll retest after I get a chance to change the layout and flex selectors from attribute to class selectors. Because most of the dynamically generated styles were simply to add colors to existing css classes, it seems unlikely you've reduced it much with the recent changes.

**Comment by ThomasBurleson** [comment]
@jlmagee - no need for you to do that change. Our latest released code will automatically create the class selectors based on existing attribute selectors... we do all the work for you! 

*  https://github.com/angular/material/blob/master/src/core/services/layout/layout.js

**Comment by jlmagee** [comment]
Thanks for the tip. the change log ought to list the change as a deprecation rather than a breaking change. (This could be drag on performance couldn't it?)

**Comment by jlmagee** [comment]
Finally got this tested. The size of inserted Style elements actually increased from 140KB to 144KB no doubt a result of adding datepicker and other new features. This is with one default theme defined. Bots  just won't process this much generated style when PhantomJS renders the escaped_fragment HTML version of a page.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (403/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:49616 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZA-001YxE-UK
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:43 +0200
Date: Thu, 28 Apr 2016 13:28:09 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875289;
	bh=a7ou0gRqMwKE8We3M56uMj5XoVrg6HBcFfyz+ZBk7Ts=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=iLDnftuBazpu71CZnvx1oTYRyyPwXgOlre3SK2NnyaglAOwkMPFxO9f+o3FCDAWCv
	 dIAfaOrJ3uU79JiYLcUukNgjllahvD6FFBjHmBZg/xgheGOkyF9odgv148F+c3ewAV
	 TYCix48YVzWYiv+jE0/xNwr7L8rATp0v7HunWpfE=

**Comment by jlmagee** [comment]
@bradlygreen @ThomasBurleson I have no idea what is meant by "deprecated"  in the context of closing an issue here.  As implemented, Angular Material Design for Angularjs is not usable for a public facing website that needs SEO.  Perhaps MD2 with Angular Universal will be better but I'm still skeptical because of the huge size of the injected styles.

I've had to abandon the use of Angular Material.

**Comment by perry2of5** [comment]
You can delete the styles out of head before you write the file to disk or serve it. The following code uses page.evaluate in PhantomJS to accomplish this:

```
var page = require('webpage').create();
var fs = require('fs');

page.open(pageURI, function(status) {
  ...
  cleanStyles();
}

function cleanStyles() {
  page.evaluate(function() {

    function removeHeadStyleDefs() {
      for (var i = document.head.children.length - 1; i >= 0; i--) {
        if ('style' === document.head.children[i].tagName.toLowerCase()) {
          document.head.removeChild(document.head.children[i]);
        }
      }
    }
    removeHeadStyleDefs();
  });

  writePageToDisk();
}

function writePageToDisk() {
  fs.write(pageFileName, page.content, 'w');
}
```
