### ISSUE TITLE
mdDialog: focus trap broken, incorrectly allowing keyboard navigation behind the modal

### ISSUE THREAD

**Issue by marcysutton** [angular/material#4105]
Somehow in the latest rewrite of the dialog, it no longer traps keyboard focus inside the modal. You can shift+tab and get to the Alert, Confirm and Custom demo dialog buttons behind the modal (and beyond), or tab to cycle through the whole document. This is incorrect–it should trap focus inside of the dialog in addition to disabling everything in the background with `aria-hidden="true"` (which it still does).

The alert & custom dialog demos were also changed to only cover the embedded demo part of the screen, while the custom one still covers the whole screen...which is confusing for a keyboard user. They should really cover the entire viewport to visually indicate that all other links behind the dialog are disabled.

**Comment by ThomasBurleson** [comment]
@marcysutton - the demos covering the embedded demo only (instead of the whole screen) is intended to visually show how different parents can be used for the dialogs.

**Comment by erinkidd01** [comment]
Do we have a timeline for when this change is expected? As of right now, I'm forcing focus to the dialog when it's opened, capturing all of the TAB keypresses, and controlling the focus manually. It's quite tedious as we have many dialogs on the page.

**Comment by skovalyov** [comment]
Can it be optional to add these focus traps before and after? I've been using the old behavior by purpose for quite a while. To be more specific, I'm using `md-dialog` for data tabel small edit dialogs, described at https://www.google.com/design/spec/components/data-tables.html#data-tables-interaction. And if the user presses Tab key I want to navigate to the next row, i.e. open small edit dialog for it. This worked perfectly with some tweaks before this change.
