### ISSUE TITLE
Angular Material site sidenav: hidden nav items should not be reachable from the keyboard

### ISSUE THREAD

**Issue by marcysutton** [angular/material#4106]
When using a keyboard to navigate through the Angular Material website, child links that are hidden behind an accordion are still reachable from a keyboard. To be accessible for keyboard and screen reader users, "hidden" menus need to be truly hidden with `display: none;` (after completing animation) OR `aria-hidden="true"` on the wrapper and `tabindex="-1"` on each link to remove it from the tab order.

See this screenshot, where Voiceover is kindly pointing out which link we're actually focused on: "HEAD" in the version picker, while visually it looks like we're on "Getting started". The links in the version picker should not be reachable when closed. The demo links suffer from the same problem.

![Angular Material in Chrome](https://cloud.githubusercontent.com/assets/1045233/9210409/ff092ba6-4030-11e5-9487-4ddd84a61f73.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
