### ISSUE TITLE
md-tabs: md-center-tabs does not maintain tabs centering on viewport resize

### ISSUE THREAD

**Issue by sanketsaurav** [angular/material#4107]
When the viewport's size is changed, the tabs go back to being left-aligned. This is in v0.10.1-rc5.

**Comment by Zacharias3690** [comment]
+1, the transform doesn't get removed when going from paginated tabs to non-paginated tabs e.g. mobile portrait to mobile landscape.

Codepen Example: http://codepen.io/Zacharias3690/pen/KVXmKw

To reproduce, shrink screen to where tabs are paginated, click the right arrow to move tabs, unshrink the page. Using v1.0.2

**Comment by Zacharias3690** [comment]
Looking in the tabsController. It appears that shouldPaginate is updated after the offsetLeft, causing fixOffset to return with a value instead of 0.

Line 339 - 345 in tabsController.js
```javascript
 function handleWindowResize () {
    ctrl.lastSelectedIndex = ctrl.selectedIndex;
    ctrl.offsetLeft        = fixOffset(ctrl.offsetLeft);
    $mdUtil.nextTick(function () {
      ctrl.updateInkBarStyles();
      updatePagination();
    });
```

and fixOffset Line 745 - 752

```javascript
function fixOffset (value) {
    if (!elements.tabs.length || !ctrl.shouldPaginate) return 0;
    var lastTab    = elements.tabs[ elements.tabs.length - 1 ],
        totalWidth = lastTab.offsetLeft + lastTab.offsetWidth;
    value          = Math.max(0, value);
    value          = Math.min(totalWidth - elements.canvas.clientWidth, value);
    return value;
  }
```

updating pagination before calling fixOffset should fix the problem.
