### ISSUE TITLE
Click hijacking on mobile disrupting label behavior

### ISSUE THREAD

**Issue by peetahzee** [angular/material#4110]
Mobile users are not able to click on radio / checkbox buttons within a label. Specifically, when the user clicks on the label, the browser automatically fires a click on the input; but [this code](https://github.com/angular/material/blob/249631748be39566e3eeebb5dac24c853fd4188e/src/core/services/gesture/gesture.js#L451) hijacks it and prevents it altogether. 

I made a simple reproduction of the problem [here](http://codepen.io/anon/pen/waOVrr). Visit with Chrome's device mode spoofing as Nexus 5 (remember to refresh after choosing device from the dropdown), and you'll find that clicking on the label does not toggle the radio button. Clicking on the input itself works, but not the label.

**Comment by jelbourn** [comment]
This is happening because the gesture code does not account for the fact that clicking on a `<label>` associated with a native input will fire _two_ `click` events: one for the label and one for the input. The first click event (label) is correctly handled, but the second is not and has `preventDefault` called on the event, stopping the selection from working.

Trying to find a fix.

**Comment by peetahzee** [comment]
Sorry to reopen this issue, but I believe this problem is not completely fixed yet. If there is a span inside a label, then lastLabelClickPos doesn't get set properly.

I tried applying the following fix:

```
// click listener
if (isEventTargetLabelDescendant(ev.target)) {
  lastLabelClickPos = {x: ev.x, y: ev.y};
}

function isEventTargetLabelDescendant(eventTarget) {
    if (!eventTarget) {
      return false;
    }
    return eventTarget.tagName.toLowerCase() == 'label' ||
        isEventTargetLabelDescendant(eventTarget.parentElement);
  }
```

The problem with this quick hack is that if an input is inside that label as well lastLabelClickPos will be updated on the browser-fired input click event.

Any advice?

**Comment by jelbourn** [comment]
Instead of checking for an ancestor label, the `this` on the event handler should be the label element. I'll see if I can get this addressed...

**Comment by peetahzee** [comment]
I tried doing that, but since the hijacker code was fired by a manual `dispatchEvent` call, the context was not set up properly.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by Egorby** [comment]
You have any solution for this bug????? Still click on <label> not works on iOS. 
"angular": "~1.6.4",
"angular-material": "1.1.3"
