### ISSUE TITLE
md-dialog height calculated wrong if page is scrolled

### ISSUE THREAD

**Issue by Lander** [angular/material#4115]
For some reason dialog's max-height depends on md-backdrop height, which is calculated based on parent (in my case body) height. If you open dialog from a not scrolled page, it will scale fine, but if you scroll the page, the dialog will still try to take 80% of md-backdrop. The way md-backdrop height calculated right now is the following: if parent has position fixed, then we are taking body height and adding body top to account the scrolled part. That leads to wrong measure of body height and wrong dialog scale.

Example here: http://codepen.io/anon/pen/YXgbee

**Comment by jelbourn** [comment]
@rschmukler

**Comment by clalag** [comment]
+1

**Comment by leonn** [comment]
+1

**Comment by lbortoli** [comment]
+1

**Comment by pidervazquez** [comment]
+1
