### ISSUE TITLE
Using trackBy causes model to trigger ng-change even when it hasn't changed.

### ISSUE THREAD

**Issue by kikhtenko** [angular/material#4118]
Hi,

when I use md-select with mg-model which has pre-selected value and this value is actually an object but not a string, control doesn't show the selected item.
In previous releases I could use md-select-label but now it's being removed.
The examples are here:
http://plnkr.co/edit/7AzpwHFGVaPt9kiFv6Fv?p=preview - when ng-model value is an object - doesn't work

http://plnkr.co/edit/966Xez4lQ79NWFIIT5tJ?p=preview - when ng-model value is a string - works fine

Regards,

**Comment by vovashevchenko** [comment]
+1

**Comment by asadovnikov** [comment]
+

**Comment by soutlan** [comment]
+++

**Comment by ivorobkalo** [comment]
+1

**Comment by Nickproger** [comment]
+1

**Comment by darknode** [comment]
+1

**Comment by kikhtenko** [comment]
I investigated the code and found that ng-model-options can possibly be used in this case but it doesn't work anyway.
ng-model-options="{trackBy: 'item.id'}" doesn't help much.

**Comment by slash13** [comment]
ng-model-options="{ trackBy: '$value.id' }" should do the trick ;-)

**Comment by kikhtenko** [comment]
nope, I've already tried this. You can check this http://plnkr.co/edit/ykk9IrCbuD1ZpqqLekLg?p=preview

**Comment by bijoux** [comment]
I use ngSelected in cases like this. It's more readable atleast for me.
ng-selected="vm.selectedItem.id === item.id"

**Comment by kikhtenko** [comment]
This doesn't work either.
Check this
http://plnkr.co/edit/dGGXOEBhfNYSRCBIDCuw?p=preview
It works with select tag but not with md-select

**Comment by websirnik** [comment]
+1

**Comment by bshir** [comment]
Modifying the example from the demo page
initialize with object and it does not display the selected value:  http://codepen.io/anon/pen/XbQzbM
initialize with string and selected value is displayed:  http://codepen.io/anon/pen/xGePGX

**Comment by bjoernricks** [comment]
@kikhtenko  bashir is right. ng-value instead of value together with ng-model-options="{ trackBy: '$value.id' }" fixes the issue. See http://plnkr.co/edit/s9roP5sWsZIZUWGakGM9?p=preview

**Comment by Ronani** [comment]
@bshir thanks! still I hope it will be fixed :+1:

**Comment by dmackerman** [comment]
There is a bug with this approach and `ngChange`, it fires immediately when using this.
