### ISSUE TITLE
autocomplete cleanup results in error if there are no elements displayed

### ISSUE THREAD

**Issue by schmkr** [angular/material#4119]
The cleanup method (e3a82c9) for md-autocomplete results in an error when there are no elements being displayed: `Cannot read property '$' of null`.

**Comment by emgolubev** [comment]
+1

**Comment by schmkr** [comment]
Maybe a duplicate of #3593?

**Comment by robertmesserle** [comment]
@schmkr Can you please provide a CodePen demo if this is still an issue?  Closing for now.
