### ISSUE TITLE
Autocomplete not working with remote requests in 0.10.1

### ISSUE THREAD

**Issue by pratyushmittal** [angular/material#4123]
It seems that the promises are no longer working with the version update.

**CodePen Demo:** http://codepen.io/anon/pen/oXObNr?editors=101

Enter anything in the above example. It won't show the results-menu until the results are fetched from cache.

**Comment by nathanpdaniel** [comment]
+1, I'm having the same issue but, I've had this issue with 0.10.0 as well.

**Comment by pogush** [comment]
same issue here, 0.10.1

**Comment by pratyushmittal** [comment]
Found the solution. We need to return `$promise` when using ngResource.

So if md-items is: `md-items='item in getItems()'` then use something like:

    $scope.getItems = function() {
        return SomeResource.get({q: $scope.searchTerm}).$promise;
    }

**Comment by hardsetting** [comment]
@pratyushmittal You're my hero

**Comment by rdkls** [comment]
@pratyushmittal mine too, thanks!

**Comment by DefunctExodus** [comment]
Same here.

**Comment by ricetrac** [comment]
+1
