### ISSUE TITLE
md-select cannot be configured to display options under label

### ISSUE THREAD

**Issue by begemott** [angular/material#4125]
Hi

As I understood now there is no way to configure an md-select component to display its options under the the component when the select is opened (now options are positioned around the select). The current behavior is nice, but I want to have it only on a small screen and on a large screen I need to display it under the select. Are you planning guys to add such an options to the component?

Thanks

**Comment by rschmukler** [comment]
This probably wont be supported but we can kick it to the UX team for review.

**Comment by bsitruk** [comment]
There is the 'shouldOpenAroundTarget' var which is used in the select module.
But it is hard-coded.
Any idea how to use it as a parameter ?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (524/500 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:60005 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avscA-000L5B-Am
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:46 -0500
Date: Thu, 28 Apr 2016 13:32:12 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875532;
	bh=boSO21Th4Cv5vWm/AWLnTwB4J//rMPSzQT4v/A7ZdA4=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=l94ePImMjvr9rEU7pR99czwyyJqURhpZ8caw0jFUC4dHnuE4oQAqcl5uKKyJkoHoz
	 x52FFtJT8H0qwYPdR3BIS5iaIamL7SUeG3+hBlb/YT4QZiSjfvUWef5VDSQTJ3DEfU
	 owDYvfTL01KAU1i1EDtQAMQffiv092PvH3w9kwMc=
