### ISSUE TITLE
md-icon not supporting data urls

### ISSUE THREAD

**Issue by matthiasg** [angular/material#4126]
When binding md-svg-src against a property which returns a data-uri url nothing is being rendered.

```
<md-icon class="s24 thin" md-svg-src="{{command.icon}}" aria-label="{{command.name}}" ></md-icon>
 ```

where `command.icon` returns 

```
data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCg0KDQo8IS0tIFRoZSBpY29uIGNhbiBiZSB1c2VkIGZyZWVseSBpbiBib3RoIHBlcnNvbmFsIGFuZCBjb21tZXJjaWFsIHByb2plY3RzIHdpdGggbm8gYXR0cmlidXRpb24gcmVxdWlyZWQsIGJ1dCBhbHdheXMgYXBwcmVjaWF0ZWQuIA0KWW91IG1heSBOT1Qgc3ViLWxpY2Vuc2UsIHJlc2VsbCwgcmVudCwgcmVkaXN0cmlidXRlIG9yIG90aGVyd2lzZSB0cmFuc2ZlciB0aGUgaWNvbiB3aXRob3V0IGV4cHJlc3Mgd3JpdHRlbiBwZXJtaXNzaW9uIGZyb20gaWNvbm1vbnN0ci5jb20gLS0+DQoNCg0KPCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj4NCg0KPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4Ig0KDQoJIHdpZHRoPSI1MTJweCIgaGVpZ2h0PSI1MTJweCIgdmlld0JveD0iMCAwIDUxMiA1MTIiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDUxMiA1MTIiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KDQo8cG9seWdvbiBpZD0icGx1cy1pY29uIiBwb2ludHM9IjQ2MiwxOTguNjE1IDMxMy4zODUsMTk4LjYxNSAzMTMuMzg1LDUwIDE5OC42MTUsNTAgMTk4LjYxNSwxOTguNjE1IDUwLDE5OC42MTUgNTAsMzEzLjM4NSANCg0KCTE5OC42MTUsMzEzLjM4NSAxOTguNjE1LDQ2MiAzMTMuMzg1LDQ2MiAzMTMuMzg1LDMxMy4zODUgNDYyLDMxMy4zODUgIi8+DQoNCjwvc3ZnPg0KDQo=
```

**Comment by matthiasg** [comment]
ok .. 'getIcon' is not handling data urls and does also not even pass a dataurl to the `loadByUrl` function. But even if it did , the `loadByUrl` function would forward it to the $http service but that would still require an interceptor to decode the dataurl into the raw text since the icon service requires the original svg text and doesnt just hand it of to an img tag etc...

we are using browserify so including a package like `dataurl` to decode is not issue for us, but using `atob` would be quite simple of course too.

does anybody have a preference as to how to proceed ?

**Comment by matthiasg** [comment]
Wow , when i posted this issue and didnt get any feedback i thought it would just remain open .. but there was just no need for any discussion, it was simply done.

Thanks. Great job.

**Comment by ThomasBurleson** [comment]
@matthiasg - for every single issue, we consider the validity and priority of that issue. Then the team determines the best time/milestone to deliver a solution. We love the community contributions (issue and Pull Requests). Thanks for this issue and the chance to make `md-icon` better.

> Kudos to @programmist for his quick turnaround.

**Comment by matthiasg** [comment]
@ThomasBurleson thats what i would expect from a well run project .. sadly it isn't the norm :) You are all doing a pretty good job managing/triaging the issues

**Comment by hanu18** [comment]
Hi @ThomasBurleson  Please help me to implement this.
I am new to angular material trying to migrate my current project to Angular material and facing the same problem. I am still not able to get SVG Icon. My code is:

var html = '<md-icon md-svg-src={{"'+ scope.container.icon + '"}}  class="CIHeaderSettingIcon" draggable="false"></md-icon>';

Icon not appear on page, while inspecting on DOM I am getting:
<md-icon md-svg-src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE2LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHdpZHRoPSIxOHB4IiBoZWlnaHQ9IjE4cHgiIHZpZXdCb3g9IjAgMCAxOCAxOCIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMTggMTgiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8cGF0aCBmaWxsPSJub25lIiBkPSJNOC41NTEsMTAuMDQ3QzguNTA3LDkuOTk2LDguNDYzLDkuOTUsOC40MjksOS44ODRjLTAuMDEzLDAuMDQ1LTAuMDI4LDAuMDgyLTAuMDMsMC4xNDMKCUM4LjQ0OCwxMC4wMzMsOC40OTksMTAuMDQyLDguNTUxLDEwLjA0N3oiLz4KPHBhdGggZmlsbD0iIzI4Mzc1OCIgZD0iTTE1LjkxNywxMi4wNzNjLTAuMTU1LTAuNDQ3LTAuNjY3LTAuNTEyLTEuMDkyLTAuNjkxYy0wLjQ3My0wLjItMC45OTMtMC40MzMtMS40NjUtMC42MjIKCWMtMC4xMzQtMC4wMzUtMC4yNjUtMC4wNzMtMC40LTAuMTA3Yy0wLjE1OC0wLjExMy0wLjMxNC0wLjQ3Ny0wLjQtMC42NTljLTAuMDg1LTAuMDEyLTAuMTczLTAuMDI3LTAuMjU4LTAuMDM3CgljMC4wMTgtMC4yODEsMC4xODgtMC4yOTUsMC4yNTgtMC41MTJjMC4wNi0wLjE4NywwLjAwNS0wLjQzNCwwLjEwMi0wLjYwOGMwLjA2Ny0wLjEyMiwwLjIxNS0wLjEyNCwwLjI4Ny0wLjIyOAoJYzAuMDcxLTAuMDk0LDAuMTE2LTAuMjU5LDAuMTM1LTAuMzc1YzAuMDQtMC4yMTIsMC4wNzUtMC41MDItMC4wMjctMC43MTJjLTAuMDU1LTAuMTIyLTAuMDg3LTAuMTMzLTAuMTA3LTAuMjc4CgljLTAuMDIyLTAuMTgyLDAuMDUxLTAuNzYsMC4wNTMtMC44ODhjMC4wMS0wLjMyNSwwLTAuMzUxLTAuMDgtMC42NjhjMCwwLTAuMDk1LTAuMjg4LTAuMjQ3LTAuMzczbC0wLjI5Ny0wLjA1MWwtMC4xODUtMC4xNwoJYy0wLjU0NC0wLjMzMy0xLjExMy0wLjI1My0xLjU1MS0wLjExOGMwLjA2NywwLjI2MywwLjA3OSwwLjMzNCwwLjA3LDAuNjYxYy0wLjAwNSwwLjEzOS0wLjA4MiwwLjc5Ni0wLjA2MywwLjk5NgoJYzAuMDIsMC4xNjUsMC4wNTgsMC4xNzcsMC4xMjQsMC4zMTVjMC4xMTcsMC4yMzgsMC4wNzgsMC41NjUsMC4wMzEsMC44MDRjLTAuMDIzLDAuMTMyLTAuMDcxLDAuMzE4LTAuMTUsMC40MjcKCWMtMC4wODIsMC4xMTYtMC4yNTIsMC4xMTctMC4zMjcsMC4yNTVjLTAuMTA3LDAuMTk4LTAuMDUsMC40NzUtMC4xMTQsMC42OTFjLTAuMDY1LDAuMTk3LTAuMiwwLjI1Mi0wLjI2LDAuNDM2CgljMC4wMzUsMC4wNjMsMC4wNzgsMC4xMTEsMC4xMjYsMC4xNjJjMC4wNDQsMC4wMDYsMC4wODksMC4wMTMsMC4xMzQsMC4wMmMwLjA5NiwwLjIwNSwwLjI3NCwwLjYxNywwLjQ1NCwwLjczOQoJYzAuMTQ5LDAuMDQzLDAuMzAyLDAuMDg2LDAuNDUyLDAuMTI2YzAuNTMxLDAuMjE1LDEuMTE4LDAuNDc5LDEuNjUyLDAuNzAyYzAuNDgxLDAuMjAyLDEuMDU4LDAuMjc5LDEuMjM1LDAuNzgzCgljMCwwLjMwMywwLjAyNCwxLjE1OCwwLjAyNCwxLjU4OGgxLjkwOUMxNS45NDUsMTMuMjgxLDE1LjkxNywxMi4zNzgsMTUuOTE3LDEyLjA3M3oiLz4KPHBhdGggZmlsbD0iIzI4Mzc1OCIgZD0iTTEyLjQ4LDEyLjQxOGMtMC4xNzktMC41MDctMC43NTUtMC41OC0xLjIzNy0wLjc4NGMtMC41MzEtMC4yMjMtMS4xMjMtMC40ODItMS42NTItMC42OTkKCWMtMC4xNDctMC4wNDItMC4yOTgtMC4wODQtMC40NTItMC4xMjVjLTAuMTgtMC4xMjUtMC4zNTYtMC41MzUtMC40NTMtMC43NDFjLTAuMDQ0LTAuMDA2LTAuMDktMC4wMTMtMC4xMzUtMC4wMTkKCWMtMC4wNTMtMC4wMDgtMC4xMDQtMC4wMTctMC4xNTMtMC4wMjNjMC4wMDItMC4wNTgsMC4wMTctMC4wOTgsMC4wMy0wLjE0M2MwLjA1OS0wLjE4LDAuMTk0LTAuMjM0LDAuMjU4LTAuNDM1CgljMC4wNjgtMC4yMTUsMC4wMDgtMC40OTIsMC4xMTQtMC42OTJDOC44NzUsOC42Miw5LjA0Niw4LjYxOSw5LjEzLDguNTAyYzAuMDc5LTAuMTA2LDAuMTI2LTAuMjkzLDAuMTUxLTAuNDI0CgljMC4wNDItMC4yMzksMC4wODMtMC41NjYtMC4wMzQtMC44MDRDOS4xODMsNy4xMzcsOS4xNDQsNy4xMjMsOS4xMjQsNi45NTljLTAuMDIyLTAuMjAyLDAuMDU5LTAuODU2LDAuMDYxLTEKCWMwLjAwOC0wLjMyNy0wLjAwMi0wLjM5OC0wLjA2Ni0wLjY2MUM5LjExMiw1LjI2OCw5LjEwNiw1LjI0NSw5LjA5Nyw1LjIwNWMwLDAtMC4xMDctMC4zMjQtMC4yNzctMC40MjNMOC40ODQsNC43MjVsLTAuMjEtMC4xOTMKCWMtMC44NC0wLjUxNy0xLjc0MS0wLjE1My0yLjIyMywwLjA0MkM1LjM1Niw0LjgsNC45MTcsNS40OCw1LjIyMyw2LjkzNWMwLjA1NCwwLjI0OC0wLjEzNCwwLjM1OS0wLjEyMiwwLjQ5NQoJYzAuMDI3LDAuMjk3LDAuMDMyLDEuMDA4LDAuMzEyLDEuMTg0QzUuNDM5LDguNjMsNS42MzcsOC42NzksNS42MzYsOC42NjdjMC4wMjgsMC4yODcsMC4wNTUsMC41NzYsMC4wODIsMC44NjcKCWMwLjA3LDAuMTkxLDAuMjM2LDAuMjEyLDAuMjg3LDAuNDgxTDUuNzksMTAuMDY4Yy0wLjA5OCwwLjIwNi0wLjI3MywwLjYxNi0wLjQ1NSwwLjc0MWMtMC4xNDksMC4wNDEtMC4zMDMsMC4wODUtMC40NTIsMC4xMjUKCWMtMC41MzEsMC4yMTUtMS4xMTksMC40NzUtMS42NSwwLjY5OWMtMC40ODMsMC4yMDItMS4wNjEsMC4yNzctMS4yMzYsMC43ODFjMCwwLjM0Ny0wLjAzMiwwLjk5MS0wLjAyNCwxLjQ0aDEwLjUyOQoJYzAuMDAyLTAuMDU1LDAtMC4xMiwwLTAuMTgzQzEyLjUwMiwxMy4yNDUsMTIuNDgsMTIuNzIxLDEyLjQ4LDEyLjQxOHoiLz4KPC9zdmc+Cg==" id="img_innertriangle_8b4b1948-a178-43bf-8caf-33d618c709fe" class="CIHeaderSettingIcon" draggable="false" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" fit="" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" focusable="false"></svg></md-icon>

**Comment by hanu18** [comment]
Hi @programmist  / @ThomasBurleson 

In any base64 image after decode if this contain
<?xml version="1.0" ?><!DOCTYPE svg  PUBLIC '-//W3C//DTD SVG 1.1//EN'  'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
tag present then it is not showing in md-icon.
It only create blank svg tag i.e.
<svg xmlns="http://www.w3.org/2000/svg" fit="" height="100%" width="100%" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" focusable="false"></svg>

**Comment by mingzew** [comment]
I also ran into issue @hanu18 mentioned, manually editing the svg and deleting the xml tag worked for me. I wish I can upvote this more because this took me more time than I'd like to admit to figure out

> In any base64 image after decode if this contain
<?xml version="1.0" ?><!DOCTYPE svg PUBLIC '-//W3C//DTD SVG 1.1//EN' 'http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd'>
tag then it is not showing in md-icon.
