### ISSUE TITLE
Buttons not aligned in official site

### ISSUE THREAD

**Issue by chinnichaitanya** [angular/material#4130]
The `Icon Buttons` are not aligned properly in the official site [here](https://material.angularjs.org/latest/#/demo/material.components.button) in Chrome with Angular-Material version - 0.10.1

Screenshot below:

![screenshot 80](https://cloud.githubusercontent.com/assets/6941024/9231090/df568e7a-4143-11e5-93c2-5a522984f8c9.png)

**Comment by topherfangio** [comment]
Thanks for noticing! We've fixed. Might need to do a hard refresh on the page as we manually fixed the CSS.

**Comment by chinnichaitanya** [comment]
Hey @topherfangio This doesn't seem to be fixed in the latest HEAD. Can you please check it.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 303ab0dc0e695f
