### ISSUE TITLE
Change components to `restrict: 'EA'`

### ISSUE THREAD

**Issue by jelbourn** [angular/material#4134]
As discussed, change most components to allow attribute syntax to better support progressive enhancement and SEO.

This will require any code that is specifically depending on the element syntax to be updated (such as CSS selectors or JS querySelector use).

**Comment by epelc** [comment]
Is this so you can make everything an attribute? I thought google didn't mind custom element names.

**Comment by jelbourn** [comment]
It to give people to option to do it whichever way they want.

**Comment by garukun** [comment]
:+1: Please enable attribute in the restrict.

**Comment by jaichandra** [comment]
+1
