### ISSUE TITLE
two md-dialog same time

### ISSUE THREAD

**Issue by luclanet** [angular/material#4135]
I'd like to open 2 dialog in the same time but it looks not possible as you can see from this example.

http://codepen.io/anon/pen/OVGbgw

When another dialog will be opened the first one is closed. That doesn't work for me.

Is there any fix for that?

**Comment by KReden** [comment]
see this issue https://github.com/angular/material/issues/698 it talks about exactly this.

**Comment by ThomasBurleson** [comment]
Duplicate.
