### ISSUE TITLE
mdMenu: mdButton not vertically centered when its a link instead of a button

### ISSUE THREAD

**Issue by antoinebrault** [angular/material#4142]
Using 0.10.1 with latest Angular and latest Chrome Browser.

When using a md-button with ui-sref inside a mdMenu, a link is generated instead of a button.
The link text is not vertically centered in the mdMenuItem.

See https://jsfiddle.net/uaoqj7e4/2/

**Comment by osuritz** [comment]
I have tried replacing the ````<a>```` tag with a ````<div>```` in the DOM and I get the same result as @antoinebrault. Only by switching to a ````<button>```` is the (vertical) alignment correct. I haven't seen anything obvious as to why this is breaking as the style is defined for ````.md-menu-item>.md-button```` and ````md-menu-item>.md-button span````

**Comment by jelbourn** [comment]
@rschmukler I can confirm that this is happening.

The anchor seems to look correct if it is changed to `display: flex`. I suspect that this is a baseline calculation issue.
