### ISSUE TITLE
MdAutocompleteCtrl.select - add val argument

### ISSUE THREAD

**Issue by dkemper01** [angular/material#4144]
On the Contact Chips demo, a welcome user experience would be to click a contact and have it automatically added to the list of selected contacts.  From what I gather, this may require an additional argument in the select method of the MdAutocompleteCtrl (auto-complete controller, autocompleteController.js).  

The new argument I am proposing would simply be "val", representing a single value in the items list, which currently originates from ```var items = $scope.$parent.$eval(itemExpr)``` (line 517, autocompleteController.js).  The idea being; an ng-click handler could be added to a contact chip md-list-item in the demo such that the auto-complete control would auto-update its collection of items.

**Comment by dkemper01** [comment]
This is easily accomplished by modifying the existing pen for the contact chips demo such that ng-click executes a method in the controller that simply adds the selected contact from the collection of all contacts to the _contacts_ collection of the md-contact-chips.  

In the markup ...

```
<md-list-item class="md-2-line contact-item" ng-repeat="(index, contact) in ctrl.allContacts" ng-if="ctrl.contacts.indexOf(contact) < 0" ng-click="ctrl.selectChip(index)">
```

In the controller ...

```
self.selectChip = selectChip;

 function selectChip(index) {
      console.log(index);
        self.contacts.push(self.allContacts[index]);
    }
```

**Comment by topherfangio** [comment]
Please note: my above commit didn't actually do anything with this issue, I simply transposed the digits in the issue number :/
