### ISSUE TITLE
bower-material is not updating anymore

### ISSUE THREAD

**Issue by Frank3K** [angular/material#4147]
Currently the latest [bower-material](https://github.com/angular/bower-material/) build is [version 0.10.1-master-514927a](https://github.com/angular/bower-material/commit/fe6731d22a568f8a449ef2cc4fe8625515b8736c) as can be seen [here](https://github.com/angular/bower-material/commits/master).

Since 514927a there have been a number of commits which are not auto build into a bower package anymore. The first commit that is not included is f60b5e5a7713af9058f9a29966f6e324cae901b9, which  coincidentally(?) changes some buildscripts.

**Comment by rschmukler** [comment]
Fixed in 1d90ffaad436bd9a078b24e05bdd46a0c8774379
