### ISSUE TITLE
Conflicting suggestions for angular version between readme and the google groups header

### ISSUE THREAD

**Issue by epelc** [angular/material#4149]
Not to nitpick or anything but the readme recommends 1.3.x or higher while the official google groups recommends `1.3` only. I know it's a slight difference but given the problems in the recent `0.10.1-rc`'s with animations in `1.4.x` it'd be nice if they were consistent.

On the [readme](https://github.com/angular/material)
> Please note that using Angular Material requires the use of Angular 1.3.x or higher.

On the [google groups](https://groups.google.com/forum/#!forum/ngmaterial)
![image](https://cloud.githubusercontent.com/assets/5204642/9265308/62b5cff4-41ff-11e5-8752-d4e49615f008.png)

We've been using angular `1.4.3` without any issues in production with angular-material `0.10.1-rc5` and recently `0.10.1`.

**Comment by marcysutton** [comment]
Sounds like the Google group needs to say "Angular 1.3 or higher".
