### ISSUE TITLE
ng disabled still fires when button has an icon and you click on the icon

### ISSUE THREAD

**Issue by 6gsaifulislam** [angular/material#415]
If I use a material button with an icon, then set it to disabled using ng disabled - the buttons appears to be disabled but ng click still fires. 

An plunker example is here: http://plnkr.co/edit/w3mzhnoNUZyfGOBOSoai

**Comment by suchitagarwal** [comment]
Hey, I am still seeing this in 1.1.4. What was the resolution here?
