### ISSUE TITLE
Calling $mdDialog.hide with an empty string resolves to the string 'true'

### ISSUE THREAD

**Issue by ddimitrop** [angular/material#4150]
See codepen

http://codepen.io/anon/pen/oXOyjz

Problem at line:

https://github.com/angular/material/blob/6fd31c9a9fef9a6bda099883fd104a186d9b36dd/src/core/services/interimElement/interimElement.js#L301

If 'reason' (which is the value returned by the dialog) is empty, the expression remove(reason || SHOW_CLOSED, false) passes SHOW_CLOSED (='true') to the caller.

**Comment by jelbourn** [comment]
@ThomasBurleson Looks like this came from your batch of dialog changes.

**Comment by jaymanned** [comment]
It also resolves to boolean true if you call `hide()` with a boolean false as in `$mdDialog.hide(false)`. My current workaround is passing boolean values as strings, e.g. `$mdDialog.hide('false')`.
