### ISSUE TITLE
md-select leaves style and md-backdrop on the screen if closed without selecting an option

### ISSUE THREAD

**Issue by trazek** [angular/material#4151]
1. Open the `md-select` component
2. Instead of clicking an option to close it, click on a custom element on screen to transition away or hide the parent container

Result: 

The style applied to the `<body>` and the generated `<md-backdrop>` will remain in the DOM. The `md-backdrop` doesn't really affect things but the style left on the `<body>` causes unexpected errors with original scrollbar position.

**Comment by rschmukler** [comment]
@trazek can you supply a demo codepen? This is cleaned up correctly in my testing. What browser are you using?
