### ISSUE TITLE
$mdSideNav no longer animates in angular 1.4.4

### ISSUE THREAD

**Issue by hodeyp** [angular/material#4152]

**Comment by julienpa** [comment]
I have the same issue with Angular Material 0.10.1

**Comment by brianfeister** [comment]
:+1:

**Comment by AleksueiR** [comment]
:+1:

**Comment by nestorneto** [comment]
the animations seem more fluid in angular 1.3.x than in 1.4.x. Anyone else feels like this?

**Comment by julienpa** [comment]
@nestorneto although I didn't try with Angular 1.3.x, it's completely possible: ngAnimate was largely re-written in 1.4 and it may have introduced some performance issues for some modules I guess

**Comment by ThomasBurleson** [comment]
The Angular teams are working on improvements to ngAnimate and *request animation frame* optimizations. We hope to have these types of perf issues more fully addressed by start of next week.

**Comment by julienpa** [comment]
Thanks for the update @ThomasBurleson !

**Comment by topherfangio** [comment]
@matsko Per your request, here is a codepen demonstrating the problem: http://codepen.io/topherfangio/pen/OVeNym

**Comment by hallaji** [comment]
@topherfangio :+1:  I have the same issue too.

**Comment by prijindal** [comment]
I think the problem is somewhere in angular-animate 1.4.4
Instead of using 1.4.4 using 1.4.3 resolved my problem

**Comment by topherfangio** [comment]
Yes, I believe the team is investigating some changes in 1.4.4 that might be causing the issue. It looks like there were quite a few updates, though, so it's possible we need to update the material component too.

Hopefully we'll hear back soon about whether or not it's actually an issue in 1.4.4.

**Comment by matsko** [comment]
I'm working on a fix right now.

**Comment by topherfangio** [comment]
Sweet. Thanks @matsko!

**Comment by miclaus** [comment]
Thank you @matsko !

**Comment by matsko** [comment]
1.4.5 will fix the issue: http://codepen.io/yearofmoo/pen/aOeaYY

**Comment by ThomasBurleson** [comment]
@matsko - what was the commit that fixed this ?

**Comment by matsko** [comment]
Not merged into master yet. Waiting for Igor to review https://github.com/angular/angular.js/pull/12669

**Comment by Blackmoonx** [comment]
@matsko Is there any ETA for 1.4.5 release?

**Comment by matsko** [comment]
Later today if all goes smoothly

**Comment by Wsiegenthaler** [comment]
Just updated to 1.4.5 and animation is back
