### ISSUE TITLE
md-menu/md-dialog with auto opened md-autocomplete

### ISSUE THREAD

**Issue by rudzikdawid** [angular/material#4154]
It would be fantastic if md-autocomplete put in md-menu/md-dialog could works like element from github ui.
expected behavior: when you open the md-menu/md-dialog, md-autocomplete is auto opened, without chance to hiding results, only you can hide whole md-menu/md-dialog.
![md-menu_md-autocomplete](https://cloud.githubusercontent.com/assets/7476577/9273272/2e210a92-428b-11e5-840f-6942fa3f9fa7.png)

I tried use md-autofocus="true" but with md-menu it doesn't work properly.
Any ideas?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
