### ISSUE TITLE
How can I use this with CSP?

### ISSUE THREAD

**Issue by oliversalzburg** [angular/material#4155]
We don't allow `unsafe-eval` or `unsafe-inline` in our Content Security Policy. This causes angular-material to not work and many errors being logged in the JS console when attempting to use it.

We're already using `ngCsp`, but it has no noticeable effect on the issue.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by oliversalzburg** [comment]
Done. The topic is at https://groups.google.com/forum/#!topic/ngmaterial/2CccXg20F2c

**Comment by oliversalzburg** [comment]
Might have been solved in part by #7959

**Comment by oliversalzburg** [comment]
One can now use https://material.angularjs.org/latest/api/service/$mdThemingProvider#mdthemingprovider-setnonce-noncevalue apparently.

**Comment by stu-co** [comment]
@oliversalzburg `setNonce();` did not work for me - did you find a solution to this?

**Comment by oliversalzburg** [comment]
@stu-co Sadly, no. It was put on our backlog and priority to solve it is very low.

**Comment by Splaktar** [comment]
You can use https://github.com/angular/material-tools to do custom builds of the CSS. There are some docs on creating static themes [here](https://github.com/angular/material-tools#theming). I haven't tried it with the latest version of AngularJS Material, please open issues in that repo if you run into problems.

I'm not sure that this will solve the CSP issues with unsafe inline styles, but it's worth taking a look at.
