### ISSUE TITLE
md-backdrop: Animate opacity instead of background-color

### ISSUE THREAD

**Issue by websirnik** [angular/material#4156]
I've noticed that animating `opacity` was in plans https://github.com/angular/material/pull/3841#issue-96349832, but then the issue was closed without the necessary commit. 
In 10.1 since backdrop became darker, you can easily see that animation does not perform well. Animating `opacity` instead of `background-color` will improve the performance.

**Comment by ThomasBurleson** [comment]
Fixed in SHA a2cb6cf538f5dee3c089b546d07b3fd75b364933
