### ISSUE TITLE
Review animations in Fab SpeedDial/Toolbar

### ISSUE THREAD

**Issue by topherfangio** [angular/material#4160]
The Fab SpeedDial/Toolbar currently use old-style animation code. Need to review and refactor to use `$animateCss` instead.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (508/500 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:56430 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsbz-000Kzx-SA
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:35 -0500
Date: Thu, 28 Apr 2016 13:32:08 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875528;
	bh=JRFA65ya4Wq0NCSnbBFEBVCpN2eXsFL8yZXlbjekDdo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=hybnzD1ayZUKsXrpCxbNWQILiUik5UaCmpUMv8HhVp+VazZXoB45iFZiW5zJF4Y8j
	 majNSpCO0yF52VZUi1DPV+WNbBSTUzSBX+zrlSys0VDSdvlBKmGkSDti6HjxUi5yH7
	 ZEUgzBTSSkc4o/TWp+qdM5R3Rx1GrLBkAolRJLmw=
