### ISSUE TITLE
md-tooltip: Feature request support of HTML tags

### ISSUE THREAD

**Issue by kschwidder** [angular/material#4164]
It would great if the md-tooltip could handle HTML tags. Currently only Strings are supported.
When generating HTML tags (such as <div> .... </div>) the tooltip is not properly styled.

**Comment by ThomasBurleson** [comment]
@SanderElias - see how we support HTML content in Dialogs

**Comment by SanderElias** [comment]
Related issue: #4464, This seems to move away from [the Google MD definition](https://www.google.com/design/spec/components/tooltips.html#tooltips-usage)? 

> Tooltips don’t display rich information including images and formatted text.

If that's ok I can work towards implementing this.

**Comment by ThomasBurleson** [comment]
Also, we have this **md-popover** planned as a desktop component; post v.10

*  https://github.com/angular/material/issues/1217
