### ISSUE TITLE
layout.scss: Firefox incorrectly calculates flex width when img tag is present

### ISSUE THREAD

**Issue by sscovil** [angular/material#4165]
In my app, I have a fairly typical layout: a header, footer and two-column body. Everything works as expected in Chrome and Safari, but in Firefox the widths of the two flex columns are being incorrectly calculated when an `<img>` tag is present inside one (or both) of the columns. More specifically, the columns are too wide, overflowing and creating a horizontal scrollbar.

### [JSFiddle](http://jsfiddle.net/hcpay1zm/)

I have experimented with this in many ways:

* wrapping the `<img>` tag in different elements (span, div, md-content)
* applying the flex attribute directly to the `<img>` tag, as a child of `<aside>`
* removing the `layout-fill` attribute from the wrapper
* removing and rearranging the various container layouts
* replacing the `<img>` tag with a similarly sized `<div>` tag

When the `<img>` tag is removed, everything works as expected. This issue only occurs when the `<img>` tag is present.

## In Chrome and Safari, it works:

![flex-bug-chrome-works](https://cloud.githubusercontent.com/assets/3105485/9281649/8682fe80-4294-11e5-854f-1ec6831deaab.gif)

## In Firefox 39 & 40 (on Windows 7 and OSX 10), it does not:

![flex-bug-firefox-broken](https://cloud.githubusercontent.com/assets/3105485/9281655/9428022e-4294-11e5-9580-38524d3d0568.gif)

**Comment by sscovil** [comment]
[This code in layout.scss](https://github.com/angular/material/blob/778af934ffd0cb331660581a26446e635d898f28/src/core/style/layout.scss#L81-L88) is the only thing I see that is Mozilla-specific. I'm not sure it is the culprit though, because the problem persists event when I remove `layout-fill` from the wrapper layout.

**Comment by ThomasBurleson** [comment]
Here is what I am seeing with the latest code from Master and AngularJS v1.4.6:  [JsFiddle](http://jsfiddle.net/ThomasBurleson/44feazry/4/)

> To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

**Comment by sscovil** [comment]
@ThomasBurleson thanks for taking a look at this. Using the resource links you provided, I created a greatly [simplified JSFiddle](http://jsfiddle.net/sscovil/nuh5j9r2/) that illustrates the issue more clearly.

As a developer, I expect an `<img>` tag inside of a `flex` container to be constrained to the width of the container. Instead, the `<img>` is maintaining its width -- and as a result, the width of the entire layout is increased.

I am seeing this problem in Chrome (45.0.2454.93) and Firefox (40.0.3) with the latest changes. Haven't tested other browsers.

**Comment by ThomasBurleson** [comment]
@sscovil - This appears to be an issue related to flexbox fundamentals.... not ngMaterial Layout (which uses flexbox). Do you have the exact same difficulties when implementing the layouts manually with flexbox styles (without ngMaterial)?

**Comment by sscovil** [comment]
@ThomasBurleson I played around with a pure flexbox CSS implementation ([JSFiddle](http://jsfiddle.net/sscovil/bevduf4n/)), and was able to get it to behave as expected in Chrome by adding `img { max-width: 100% }`...but the problem still persists in Firefox.

Adding the same CSS to the `img` tag in the ngMaterial version ([JSFiddle](http://jsfiddle.net/sscovil/nuh5j9r2/)) still didn't work quite as expected; the margin causes a horizontal scrollbar.

I'd have to spike on it to offer a solution. I'm no expert on the flexbox spec, but [this article on CSS Tricks](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) has been helpful.

**Comment by ThomasBurleson** [comment]
@sscovil - I am closing this issue as resolved. I think we need to have a technical note regarding use of `max-width:100%` for images in *layout* areas.

> See [CodePen Layout Demo](http://codepen.io/team/AngularMaterial/pen/rxNXWY)
