### ISSUE TITLE
Weird scroll behavior with md-virtual-repeat-container

### ISSUE THREAD

**Issue by matgr1** [angular/material#4169]
it's probably easiest to just demostrate, so here's a codepen: http://codepen.io/matgr1/pen/BNEEmW

and here are the problems:

1.) scroll to the bottom, shrink the output pane to maybe half the height, start scrolling down again - it keeps going forever just repeating the last few items

2.) increase the output pane height (to larger than the original) - the numbers no longer go all the way to the bottom

**Comment by matgr1** [comment]
one more issue I just noticed (and updated the codepen to show it): the items won't fill horizontally all the way to the scrollbar

**Comment by RolandHeath** [comment]
Can definitely confirm this. 
I had a similar issue using an md-list inside a virtual repeat. In some cases the last element(s) can't be viewed because they can't be scrolled to.

**Comment by bluebirdtech** [comment]
+1 seeing the same problems here when the container is resized

**Comment by Kemaletdin** [comment]
Thank you for this sample on codepen.io.

I don't know if this will make sense but.

How would this work with large datasets from a DB and a buffer.
Is it possible to make it do an api call to get the next x number of items while scrolling as it hits the bottom so we don't pull large amount of data at once?

thanks

**Comment by jayj** [comment]
I have the same issue, but only when I use `md-list` and `md-list-item` inside the `md-virtual-repeat-container`. If I switch to using divs it works fine.

Here's a demo:
http://plnkr.co/edit/x4oEH0ye9SSVxlpYcfZN?p=preview

**Comment by RolandHeath** [comment]
Yep - changing your plunk seems to confirm that - if I change either the `md-list` or the `md-list-item` to divs, it scrolls ok.

**Comment by RolandHeath** [comment]
This seems to be caused by a css interaction.
In the plunk, this issue goes away if you switch 
`<md-list>` with 
`<md-list style="padding-top:0;">`

**Comment by arshdefoamed** [comment]
I tried changing the handleScroll_ function to get a work around for the above issue and it seems to be working fine for my case. Sadly, I dont have the kind of skills to test it extensively to make sure that all types of cases are covered. There is a probability that my approach was completely wrong and it was just a fluke for my case. I am sharing my code in case someone is lucky and his/her problem gets solved.

```
VirtualRepeatContainerController.prototype.handleScroll_ = function() {
  var offset = this.isHorizontal() ? this.scroller.scrollLeft : this.scroller.scrollTop;
  if (offset === this.scrollOffset) return;

  var itemSize = this.repeater.getItemSize();
  if (!itemSize) return;

  var num = NUM_EXTRA;
  if(!this.isHorizontal())
  {
	  /**
	   *  Offset should not be greater than differences in height of offsetter and sizer
	   *  Moreover to calculate transform extra count should be set as zero for the bottom of scroll  
	   */
	  var maxOffset  = this.sizer.offsetHeight - this.offsetter.offsetHeight;
	  if(offset >maxOffset )
	  { 
		  offset = maxOffset;
		  var num = 0;
	  }
  }
  var numItems = Math.max(0, Math.floor(offset / itemSize) - num);
  var transform = this.isHorizontal() ? 'translateX(' : 'translateY(';
      transform +=  (numItems * itemSize) + 'px)';

  this.scrollOffset = offset;
  this.offsetter.style.webkitTransform = transform;
  this.offsetter.style.transform = transform;

  this.repeater.containerUpdated();
};
```

**Comment by kseamon** [comment]
Anyone still seeing the misbehavior in 1.0rc4? Updated plunkr here: http://codepen.io/anon/pen/yYdNZV

**Comment by jayj** [comment]
Yes, I do.

Updated my Plunkr to using 1.0rc4: http://plnkr.co/edit/CSxOmi4RxNoB2vRJHR3d?p=preview

**Comment by RolandHeath** [comment]
@jayj The issue in your plunk is that the padding on the md-list is inside the md-virtual-repeat-container, which means (effectively) that not every element is the same height. 

@kseamon This issue seems to have been a fairly common, easily made mistake. It might be worth adding an example to the docs using md-list (outside the md-virtual-repeat-container) and md-list-items.
An alternative might be to allow md-virtual-repeat-container as an attribute, and put up an example of that.

I'm fairly sure that this problem is actually just a miscommunication about md-virtual-repeat's trouble handling variable sized contents. If only that were an easy problem to fix...

**Comment by ccd2008** [comment]
I was having issues with the bottomless scrolling. I added this to mostly fix the problem.

<pre>
VirtualRepeatContainerController.prototype.handleScroll_ = function() {
  var offset = this.isHorizontal() ? this.scroller.scrollLeft : this.scroller.scrollTop;
  if (offset === this.scrollOffset) return;

  <b><i>var itemsLength = this.repeater.itemsLength;</i></b>
  var itemSize = this.repeater.getItemSize();

  if (!itemSize) return;

  var numItems = Math.max(0, Math.floor(offset / itemSize) - NUM_EXTRA);
  <b><i>if(itemsLength > this.repeater.endIndex || offset < this.scrollOffset){</i></b>
    var transform = this.isHorizontal() ? 'translateX(' : 'translateY(';
        transform +=  (numItems * itemSize) + 'px)';
    this.scrollOffset = offset;
    this.offsetter.style.webkitTransform = transform;
    this.offsetter.style.transform = transform;
  <b><i>}</b></i>

  if (this.bindTopIndex) {
    var topIndex = Math.floor(offset / itemSize);
    if (topIndex !== this.topIndex && topIndex < this.repeater.itemsLength) {
      this.topIndex = topIndex;
      this.bindTopIndex.assign(this.$scope, topIndex);
      if (!this.$rootScope.$$phase) this.$scope.$digest();
    }
  }

  this.repeater.containerUpdated();
};
</pre>

**Comment by jaymanned** [comment]
+1 in 1.0-rc5. I've removed padding and margins from the md-virtual-repeat-container but still get the issue in both Safari 8.0.7 (10600.7.12) and Chrome 47.0.2526.106.

**Comment by shobhit-m** [comment]
Try using md-item-size.
