### ISSUE TITLE
mdAutocomplete: Modifies body position

### ISSUE THREAD

**Issue by PseudoCorps** [angular/material#4175]
I'm not sure if this is intended behavior or not, but some of the time when I type in an md-autocomplete box, the element style of the body tag is changed which makes my navbar disappear. The negative top value varies, and I'm not sure how to avoid it.

The navbar is the gray in the first picture with the teal bottom border part (I blocked out most of the content)

Before: 

<img width="940" alt="before" src="https://cloud.githubusercontent.com/assets/2850172/9287368/534be18a-42c6-11e5-93a5-93f52bc8594d.png">

Enter in the md-autocomplete:

![category](https://cloud.githubusercontent.com/assets/2850172/9287376/7b5a374e-42c6-11e5-8141-66ebe856ae05.png)

After:

<img width="943" alt="after" src="https://cloud.githubusercontent.com/assets/2850172/9287370/5f277762-42c6-11e5-8f3a-def8f535df62.png">

Suggestions block and style:

![suggestion-block-style](https://cloud.githubusercontent.com/assets/2850172/9287378/9f878bc6-42c6-11e5-95a4-8afba61213f6.png)

I'm guessing that the since the `<body>` is the parent of the `<ul>` containing the suggestions that it adjusts based on that. Is there a reason the suggestions have to be on the top level? 

I was thinking the suggestions `<ul>` could be injected into the element where the `<md-autocomplete>` is instead of the top level. This might make it easier to format the position of the list as well?

/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v0.10.1 (Also 10.0)
 */

**Comment by PseudoCorps** [comment]
Seems similar to #4151

**Comment by hoffination** [comment]
Might also be similar to #6188
1+

**Comment by baelter** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
