### ISSUE TITLE
md-tooltip: Method to disable all tooltips globally. E.g on small screens/pure touch devices

### ISSUE THREAD

**Issue by matthiasg** [angular/material#4176]
i am having some issues with tooltips appearing on touch devices and often they dont even appear at the right spots but sometimes all potential tooltips appear all at once centered at the top/left/right/bottom border of the screen overlaying each other. 

it would be helpful if there was a way to just disable all tooltips globally. We could simply bind this to mobile detection or small screen sizes.

**Comment by fRzzy** [comment]
+1

**Comment by epelc** [comment]
You should be able to do this with some css and a media query. Just set `display: none;` or something similar.

**Comment by matthiasg** [comment]
@epelc sure thats possible if its only based on size and its what we do. I would have liked not to incur the overhead of tooltips at all for mobile devices, hence a global disable switch.

**Comment by lscordilis** [comment]
+1

**Comment by alphatwit** [comment]
+1

**Comment by SanderElias** [comment]
This needs a global configuration option. As there are probably more things that needs such a global service, we need to discuss on where/how/if this needs to be done.

**Comment by STOpandthink** [comment]
+1 tooltips are very buggy on mobile right now

**Comment by zilions** [comment]
This is a need. Tooltips are quite buggy and not nessesary on touch only devices. Would be great to have a global disable for them.

**Comment by zilions** [comment]
Offered a bounty question on Stackoverflow and received a very good answer for a temp working for this - http://stackoverflow.com/questions/35329388/how-to-dynamically-remove-a-md-tooltip-with-angular-material

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by louiealmeda** [comment]
+ 1
