### ISSUE TITLE
md-tabs: there should be a md-greatest-height property similar to md-dynamic-height

### ISSUE THREAD

**Issue by matthiasg** [angular/material#4177]
Idea would be to calculate the height of all tabs but render them all with the maximum height found, but it would also require a possibility to limit the extend to a maximum height. 

I implemented this would solve the issue of dialogs moving up and down when a dialog contains tabs. as of now the only choice is to only show 200px height per tab or have the entire dialog recenter vertically each time another tab is clicked.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
