### ISSUE TITLE
$mdDialog and $mdBottomSheet - promises do not resolve when testing

### ISSUE THREAD

**Issue by jmcpeak** [angular/material#4181]
When unit testing my code, I ran across this issue. $mdDialog and $mdBottomSheet - promises do not resolve when testing by call hide() or cancel(). I included my test here. Both services use $q so I tested that and it is fine - release: version 0.10.1.

See the codepen here:
http://codepen.io/jmcpeak/pen/OVGKMN

**Comment by ThomasBurleson** [comment]
@jmcpeak - you need to use $timeout.flush() to clear all pending promise queues.

**Comment by jmcpeak** [comment]
I updated my codepen to use ```$timeout.flush()``` - tried before and after ```$rootScope.$apply``` - no luck.
