### ISSUE TITLE
md-select-menu class has "undefined"

### ISSUE THREAD

**Issue by trazek** [angular/material#4184]
The generated tag `md-select-menu` appears to have "undefined" in it. It has the following:

`class="md-select-menu-container undefined ng-scope md-default-theme md-active md-clickable"`

**Comment by Londovir** [comment]
I have seen this as well. Traced it to a line of code which reads as follows in the md-select codebase:

`selectContainer[0].setAttribute('class', selectContainer[0].getAttribute('class') + ' ' + element.attr('md-container-class'));`

The thing is, there's absolutely no other instance of the string `'md-container-class'` anywhere within the source of angular-material.js that is output as part of the build. Therefore, this will always cause an undefined to pop in there.

**Comment by rschmukler** [comment]
@Londovir that's there to allow users to specify their own class for the select container. See the [docs here](https://material.angularjs.org/latest/#/api/material.components.select/directive/mdSelect). But, we should specify `|| ''` so undefined doesn't get in there. Thanks!
