### ISSUE TITLE
Tabs arrows initially show arrows even if not needed.

### ISSUE THREAD

**Issue by demodav** [angular/material#4187]
In v0.10.1, The tabs arrows show initially, however when clicking them, it readjust the layout and removes the arrows. Here, I made a video. http://screencast.com/t/jkaLKgCX

**Comment by topherfangio** [comment]
Can you tell us what browser you are using?

It seems like you are at a very small screen size; does this happen only on small screen sizes, or on large ones also?

**Comment by demodav** [comment]
I shrunk down chrome to be of mobile size my tabs are in the md-sidenav with width: 256px;

**Comment by gpopovic** [comment]
I'm seeing the same thing in chrome on iphone

**Comment by TheRockman** [comment]
I have the same problem
