### ISSUE TITLE
FAB Button doesn't function on website

### ISSUE THREAD

**Issue by demodav** [angular/material#4188]
The FAB Button for angular material doesn't seem to pull out other buttons on the website.
https://material.angularjs.org/latest/#/demo/material.components.button

I'm assuming it is supposed to work like this FAB
http://materializecss.com/buttons.html

Here is my work around to maybe help this get implemented

HTML
-------------------------------------------
    <div class="fixed-action-btn" ng-controller="FABMenuCtrl as ctrl"
      ng-mouseleave="ctrl.close($event)" ng-mouseenter="ctrl.open($event)">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">grade</i>
    </a>
    <ul>
      <li><a ng-class="btnFloating()" class="btn-floating blue"><i class="material-icons">library_add</i></i></a></li>
      <li><a ng-class="btnFloating()" class="btn-floating green"><i class="material-icons">playlist_add</i></a></li>
      <li><a ng-class="btnFloating()" class="btn-floating yellow darken-1"><i class="material-icons">file_download</i></a></li>
      <li><a ng-class="btnFloating()" class="btn-floating red"><i class="material-icons">picture_as_pdf</i></a></li>
    </ul>
     </div>

CSS
------------------------------------------------------
.fixed-action-btn ul a.btn-floating {    
    transform: scaleY(0.4) scaleX(0.4) translateY(0px); opacity: 0;
}

.fixed-action-btn ul a.hideActionBtns {
    transform: scaleY(0.4) scaleX(0.4) translateY(0px); opacity: 0;
}

.fixed-action-btn ul a.showActionBtns {
    transform: scaleY(1) scaleX(1) translateY(25px); opacity: 1;
}

JS
---------------------------
app.controller('FABMenuCtrl', function FABMenuCtrl($scope) {
    this.open = function() {
      var time = 0;
      $scope.btnFloating = function() {
        return "showActionBtns";
      }      
    };
    
    this.close = function() {
        $scope.btnFloating = function() {
        return "hideActionBtns";
      }
    };    
  });

**Comment by topherfangio** [comment]
You're probably looking for the FAB Speed Dial component (
https://material.angularjs.org/latest/#/demo/material.components.fabSpeedDial).
The standard FAB is just a floating button that can take on many different
tasks including, but not limited to, just being a clickable button :-)

**Comment by demodav** [comment]
Yes, that's it. Should I delete this?

**Comment by topherfangio** [comment]
No need to delete, we will just close it. Thanks!
