### ISSUE TITLE
Can type non-digits in numeric input fields and spinner controls shown in desktop browsers

### ISSUE THREAD

**Issue by CoDEmanX** [angular/material#4189]
Hourly Rate (USD) accepts any character:
https://material.angularjs.org/latest/#/demo/material.components.input

It also shows ugly spinner up/down buttons in most browsers, which should be hidden:
https://css-tricks.com/numeric-inputs-a-comparison-of-browser-defaults/

The postal code field accepts any character too and does not show the numeric keyboard in mobile browsers. Leading zeros should remain in the field, but non-digits shouldn't be possible to type and on mobile devices the numeric keyboard should show.

**Comment by innerpeace0** [comment]
> The postal code field accepts any character

Some postal codes, such as Canada, include alpha characters.
