### ISSUE TITLE
mdChips: feature: md-on-append as a simple callback

### ISSUE THREAD

**Issue by emps** [angular/material#4193]
im using md-on-append with md-chips and it works ok except of 'undefined' pushed in ng-model array
so there is no string chip and the chips i add via md append

**Comment by topherfangio** [comment]
I'm not sure I fully understand. Why is your `md-on-append` returning an undefined chip?

**Comment by smashercosmo** [comment]
@topherfangio because I think that md-on-append is used here as a simple callback, like newly added md-on-remove. It is not used to transform chip string to object. May be we need simple md-on-add, that won't force us to return an object value?

**Comment by e-oz** [comment]
Please explain how to use md-on-append. How handler function should decide what to return, if it doesn't receive any arguments?

**Comment by topherfangio** [comment]
@e-oz `md-on-append` is passed the text that the user typed so that you can translate it into an actual object (or just return the string if that's what you want).

Please see the [Basic Usage Demo](https://material.angularjs.org/HEAD/#/demo/material.components.chips) for more information.

**Comment by e-oz** [comment]
@topherfangio please try it with autocomplete and objects instead of text.

**Comment by e-oz** [comment]
@topherfangio thanks for advice - on second I try I found usage in code and I see I should pass ctrl.method($chip) in template to expect it in controller. Unusual but usable :)
Sorry for taking your time and thanks for help.

**Comment by topherfangio** [comment]
@e-oz Not a problem!

**Comment by facuxt** [comment]
For example...
 <md-chips ng-model="selectedVegetables" md-autocomplete-snap="" md-require-match="true" md-on-append="wtf($chip)">

and in controller...

    $scope.wtf = function(chip){
    	//chip.wtf = $scope.contador++;
    	var newChip = {};
    	angular.copy(chip, newChip)
    	return newChip;
    	//return chip;
    }

**Comment by topherfangio** [comment]
@facuxt We have an outstanding PR (#4479) to automatically disallow identical chips.

Do you have a use-case for identical chips? Could you easily add an `id` field or something to make them unique?

**Comment by facuxt** [comment]
Hello topherfangio. im doing a mathematical formula builder... i show you here some screenshots... maybe i can add a unique id or something in order to avoid that new feature... but... i think that a more apropiate approach to this should be to leave a configuration-thingy like md-allow-repeated to solve this issue for all of us.
![screen](https://cloud.githubusercontent.com/assets/7550822/10377320/fbad5b96-6dd8-11e5-891f-1f1fc03617e0.png)

This works like a charm...
