### ISSUE TITLE
md-tabs: tabbing through the tabs

### ISSUE THREAD

**Issue by parky128** [angular/material#4196]
Is there any tab key support to highlight tabs for selection?

**Comment by ThomasBurleson** [comment]
@robertmesserle - I don't think I understand this issue.

**Comment by EladBezalel** [comment]
I think he asks about tab stops of the tab key

**Comment by robertmesserle** [comment]
@parky128 Tabbing will select the entire tab bar.  Once the bar has focus, the arrow keys are used to navigate between tabs rather than the tab key.
