### ISSUE TITLE
layout: Nested layout overflows from container

### ISSUE THREAD

**Issue by sanketsaurav** [angular/material#4198]
I don't know if this is the intended behavior, but a layout like this - http://codepen.io/sanketsaurav/pen/oXRWBL - doesn't work on the latest Chrome / FF. However, it's working on older versions of Chrome / FF.

**Comment by topherfangio** [comment]
Would you mind describing exactly how it doesn't work? Is this a scrolling issue, or were you expecting the widths to be different, etc.

**Comment by sanketsaurav** [comment]
Oh, yes. My bad. :)

So, here's the layout I want:

```
<body layout="row">
    
    <md-sidenav></md-sidenav>
    
    <div layout="column" flex>

        <md-toolbar></md-toolbar>

        <div flex layout="column" id="content">
            ... content ...
        </div>

    </div>

</body>
```

As you can see in the attached CodePen, the contents of the `div` with id `content` are overflowing. Is this expected behavior?

**Comment by ThomasBurleson** [comment]
To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
