### ISSUE TITLE
custom directives and material css

### ISSUE THREAD

**Issue by tirana** [angular/material#4201]
I want to display a simple list, yet my image is a directive.
Unfortunately, material styles declare "md-list-item > md-avatar" so md-avatar should be a direct child
yet the directive add a middlemen, so ck-avatar, in the middle, breaks the style.
Is there a way to ask angular to not add directive tag?
Is it possible to not require direct inheritance in styles?

```
<md-content>
    <md-list>
        <li ng-show="!ctrl.comments.length">No comments</li>
        <md-list-item class="md-3-line" ng-repeat="c in ctrl.comments">
            <ck-avatar username="c.author.username"></ck-avatar>
            <div class="md-list-item-text">
                <h3>
                    <ck-username username="c.author.username"></ck-username>
                </h3>
                <h4>{{c.modifiedOnISO | date:'MM-dd-yyyy hh:mm:ss'}}</h4>
                <p>{{c.content}}</p>
            </div>
        </md-list-item>
    </md-list>
```

--ck-avatar-- directive template:
```
<img ng-if="profile.name"
        ng-src="{{profile.profilePhotoUrl}}"
        err-src="{{profile.securityPhotoUrl}}"
        class="md-avatar"
        title="{{profile.name.fullInLatinCharacters}}">
```

**Comment by epelc** [comment]
@tirana Scroll down to `Directive Types` on this page

https://docs.angularjs.org/guide/directive

Essentially you can use a directive as an element, attribute, class, or comment. Using it as a comment should let you create it without having an element. Another option would be to copy the css.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
