### ISSUE TITLE
menuBar: Make menus smartly limit height

### ISSUE THREAD

**Issue by rschmukler** [angular/material#4204]
Menus in menubars should do detection to see if they are going to overflow and reposition themselves above their parent menubar, and if so, shorten themselves to a min-height to fit.

**Comment by jraadt** [comment]
It seems submenus do smartly change their top to be higher on the screen if needed in hopes that the entire submenu will be shown.  But if the submenu is larger than the screen the bottom portion is still cut off.  When the menuServiceProvider is calculating the menu position and setting the menu styles, it should detect if the menu needs a scroll bar and add a bottom and overflow-y style to the menu as well.
