### ISSUE TITLE
$mdDialog and $mdBottomSheet - promises do not resolve when testing

### ISSUE THREAD

**Issue by jmcpeak** [angular/material#4205]
When unit testing my code, I ran across this issue. $mdDialog and $mdBottomSheet - promises do not resolve when testing by call hide() or cancel(). I included my test here. Both services use $q so I tested that and it is fine - release: version 0.10.1.

See the codepen here:
http://codepen.io/jmcpeak/pen/OVGKMN

ThomasBurleson commented 2 days ago
@jmcpeak - you need to use $timeout.flush() to clear all pending promise queues.

jmcpeak commented 2 days ago
I updated my codepen to use $timeout.flush() - tried before and after $rootScope.$apply - no luck. Where do I put $timeout.flush() to make this work?

**Comment by ThomasBurleson** [comment]
@jmcpeak - please look at the [dialog.spec.js](https://github.com/angular/material/blob/master/src/components/dialog/dialog.spec.js#L18-L24) tests to see how we flush the animation, timeout, and promise queues.
