### ISSUE TITLE
Aria Errors with $mdDialog when using directive in template

### ISSUE THREAD

**Issue by stavro** [angular/material#4206]
I am getting JavaScript console errors related to Aria any time I try to directly include a directive into an $mdDialog template.

Example:
```javascript
   $mdDialog.show({
      template: '<my-test-directive></my-test-directive>'
    });
```

Plunkr: http://codepen.io/anon/pen/rVgYJm

Side note: Is there a way to disable Aria completely in Angular Material?

**Comment by stavro** [comment]
Hmm.. I think this is because the template must start with `<md-dialog>`..... Though if this is required then perhaps the error message should be more clear?

**Comment by gonzofish** [comment]
thanks for throwing this bug up, helped me figure out a lot of confusion. the error message could definitely use some clarification if `<md-dialog />` has to be the first element!

**Comment by ThomasBurleson** [comment]
Reopening as this is related to #3191

**Comment by gonzofish** [comment]
:+1: great!
