### ISSUE TITLE
md-checkbox label margin only applies to first line of wrapping text

### ISSUE THREAD

**Issue by ryangallen** [angular/material#4207]
Screenshot:
<img width="371" alt="screen shot 2015-08-17 at 8 33 20 pm" src="https://cloud.githubusercontent.com/assets/1379681/9319744/ce104d06-451f-11e5-9e55-da86b7c6b8dc.png">

Moving the margin from the span to the enclosing div fixes this issue.
<img width="361" alt="screen shot 2015-08-17 at 8 33 50 pm" src="https://cloud.githubusercontent.com/assets/1379681/9319745/d00923a8-451f-11e5-8f54-6fde1b5f8500.png">

<img width="346" alt="screen shot 2015-08-17 at 8 34 33 pm" src="https://cloud.githubusercontent.com/assets/1379681/9319747/d29868cc-451f-11e5-8428-45598ff8ab10.png">

**Comment by topherfangio** [comment]
Based on master code, I believe this is now fixed.

Please comment if you are still experiencing this issue after upgrading and I will reopen.
