### ISSUE TITLE
md-list-item: min-height is incorrect

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#4208]
min-height should be 48dp and it's set to 64dp (I assume) based on this:

https://github.com/angular/material/blob/f4c91b34e2bcc933bb81399fd133c1bed7ee9531/src/components/list/list.scss#L27

Changing to 48px doesn't break avatars (still 56dp) as seen here:

http://codepen.io/anon/pen/bdyYzd

Here is the Material Design specs: https://www.google.com/design/spec/components/lists.html#lists-specs

**Comment by roidayan** [comment]
also list with icon should be 48px.

http://codepen.io/anon/pen/GpoEMb

**Comment by topherfangio** [comment]
Based on the latest master code; it looks like this has been fixed. If not, please comment and I will reopen.
