### ISSUE TITLE
md-input-container: does not scroll horizontally or go to next line

### ISSUE THREAD

**Issue by lboekhorst** [angular/material#4210]
To reproduce, open up the input example page at https://material.angularjs.org/latest/#/demo/material.components.input. Keep pressing space until you are at the end of the line. The text area will not show horizontal scroll bars nor go to the next line. Note that this only occurs with white space. Regular text will properly wrap to the next line.

This issue occurs with 0.10.1-rc5 on Ubuntu 14.04.03 LTS and Chrome 44. The text area behaves properly in Firefox 40, going to the next line whenever it runs out of horizontal space, even if it is only occupied by white space. It also works properly in Internet Explorer 11 on Windows 7. Other browsers have not been tested.

**Comment by topherfangio** [comment]
Still broken on RC4.
