### ISSUE TITLE
Firefox issue with md-checkbox inside a md-menu

### ISSUE THREAD

**Issue by extrafu** [angular/material#4212]
When a md-checkbox is contained within an md-button in a md-menu, it is impossible to change the checkbox state with Firefox while it works with Chrome and Safari.

The CodePen showing the issue is available here: http://codepen.io/anon/pen/NqVBOq

**Comment by extrafu** [comment]
Any updates on this?

**Comment by rschmukler** [comment]
Given the work around and that this may not be a supported interaction, moving to discussion to see whether this can be closed.
