### ISSUE TITLE
ripple: TypeError on some components

### ISSUE THREAD

**Issue by ngraef** [angular/material#4213]
After the recent refactor (e92dd2632baf1216a89aa8534381fcba2bfcdc35), checkbox, switch, and icon button ripples are broken. Other buttons, tabs, and select/menu item ripples still work.

Interacting with the broken elements gives
> Uncaught TypeError: Cannot read property 'prop' of null

at [ripple.js line 144](https://github.com/angular/material/blob/e92dd2632baf1216a89aa8534381fcba2bfcdc35/src/core/services/ripple/ripple.js#L144).

cc: @robertmesserle

**Comment by stewones** [comment]
+1
here with md-menu

**Comment by sincraianul** [comment]
+1 same as @stewones

**Comment by Reklino** [comment]
Yep. Same issue.

I'm also having an issue where the ripples on other buttons are now out of place. The ripples seem to be originating from below the button and to the right. Not sure if it is related or not, but the issue seemed to start at the same time.

**Comment by ronaldbluethl** [comment]
same issue on (md-icon inside) md-button

**Comment by ngraef** [comment]
Looks like this was fixed by be4311ac7e1795a3c7f9b6ea4953aa9e4c3bb501.
