### ISSUE TITLE
datepicker: Past dates are not correct

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#4215]
Well, i played a little with the new [date picker](https://material.angularjs.org/HEAD/#/demo/material.components.datepicker) and inserted my birthday: ``` 10/20/1992 ``` 
![image](http://i.imgur.com/xWgCUAI.png)
than i opened the date picker and clicked again on 20:
![image2](http://i.imgur.com/OlKR2DW.png)
than it became ``` 10/19/1992 ```
![image3](http://i.imgur.com/xGaXsNt.png)

Don't know why but it seems that the line is between ``` 4/2/1992 ``` to ``` 4/3/1992 ```

**Comment by jelbourn** [comment]
@EladBezalel which browser were you using? I tried it as you described and did not encounter the issue.

**Comment by EladBezalel** [comment]
Chrome latest version

**Comment by jelbourn** [comment]
@EladBezalel I'm using the same. Which OS and OS version?

**Comment by NickBolles** [comment]
I'm seeing this too. That's weird haha.
Chrome 44 on both Win 10 and 8.1
But Not on Edge on Win 10 or IE 11 on 8.1

**Comment by kuhnroyal** [comment]
This could be a timezone issue in your date instance.

**Comment by EladBezalel** [comment]
Win 10, also on Windows 8.1
not happening in Windows 7

**Comment by vectorderivative** [comment]
Same here.
Firefox 40.0.3
Win 8.1

**Comment by matthiasg** [comment]
well at least you got the right year.. when i entered my birthday and opened the dialog it would still show Sep 2015 not the year i entered.

![image](https://cloud.githubusercontent.com/assets/231889/9760940/b51c7fb8-56f9-11e5-82d9-05efa9d464f4.png)

**Comment by topherfangio** [comment]
@matthiasg Looks like you might be using the min/max date demo which has the min/max set to -2/+2 of the current month, so it treats it as an invalid date and doesn't set the date in the datepicker.

That said, you should have noticed that it was invalid by the red underline. Did you see that?

**Comment by jelbourn** [comment]
Can reproduce this by changing to a different timezone (I found that using Eastern Europe works to reproduce). The problem is with the default date formatting, boiling down to:
```js
var d = new Date(1992, 9, 8, 0, 0, 0); // should be midnight
d.toLocaleString();  //  "10/7/1992, 11:00:00 PM"
```

The workaround (and general best practice) is to define your own parsing/formatting with `$mdDateLocaleProvider` using something like [moment.js](http://momentjs.com/).

**Comment by matthiasg** [comment]
@topherfangio i actually didnt see the red line .. it was so small that i just didnt pick up on it.
