### ISSUE TITLE
datepicker: make month and year selectable

### ISSUE THREAD

**Issue by dsbaars** [angular/material#4216]
I want to use the datepicker as a birthdate selector, it is __a lot__ of scrolling when I want to do this with the current widget. Please make both month and year optionally selectable, or discuss another more intuitive way to do this.

Example @ jQuery UI:
http://jqueryui.com/datepicker/#dropdown-month-year

(There was a request to file specific feature requests in the closed #648. In my opinion #4178 is not very specific but it is a similar issue)

**Comment by rochdev** [comment]
Actually the current implementation doesn't look anything like the spec which would solve your problem: https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers

**Comment by jelbourn** [comment]
A month-year selector is on the [TODO list](https://github.com/mhchen/material/blob/d6457e2719cc4dffb6e4f861349f1513002f4535/src/components/datepicker/calendar.js#L18-18), but didn't make it into the initial version.

You can also type the date instead of scrolling.

**Comment by dsbaars** [comment]
In my opinion this issue (and others) should not be closed until it is implemented, because until that is the case it is actually an issue.

**Comment by alo** [comment]
+1

**Comment by DevVersion** [comment]
Reference #5971

**Comment by kunokdev** [comment]
+1

**Comment by jelbourn** [comment]
Follow #4251
