### ISSUE TITLE
datepicker: material spec has not been followed

### ISSUE THREAD

**Issue by rochdev** [angular/material#4217]
I don't know if the current implementation is final but if it is it doesn't look anything like the spec: https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers

**Comment by jelbourn** [comment]
We are following a new spec that has not yet been published to the Material Design site.

**Comment by miguelcobain** [comment]
Is the current datepicker still spec compliant?

It surely doesn't look like the one in material design guidelines.
