### ISSUE TITLE
toast: add `onAction` configuration option

### ISSUE THREAD

**Issue by jelbourn** [angular/material#4219]
Add `onAction` option to toast configuration. This would be a function that is executed when the toast action is clicked. This should be more intuitive than the toast promise resolving to `"ok"`.

**Comment by NickBolles** [comment]
I was just digging into the $mdToast. Kinda along the lines of this. Shouldn't the promise returned by `$mdToast.show()` be resolved when the toast hides no matter what? 
I expected to be able to do a `.then()` off of the `.show()` and have it resolved every time not just when an action is clicked? 

For my use case I am creating a sort of wrapper service for $mdToast that creates a Queue of toasts that show one after the other. This would be simple if i could chain the promises from `$mdToast.show()`, and it is what I would expect. Especially considering the $mdDialog behavior.

It looks like `$mdToast.show().then()` isn't triggered in a custom template with calling `$mdToast.hide()` either. See CodePen
http://codepen.io/anon/pen/YXbBrN

**Comment by jelbourn** [comment]
@NickBolles you've described the current behavior. The toast previously behaved otherwise, but this was changed in 0.10.1. 

Also see #4218

**Comment by NickBolles** [comment]
See my edit :) sorry! And I just realized too that I don't think My app is using 0.10.1. Thanks!
