### ISSUE TITLE
md-ripple issue with md-icon-button in master

### ISSUE THREAD

**Issue by bradmartin** [angular/material#4224]
Current master has ripple issues on md-button with .md-icon-button

Issue present on demo site also.

**Comment by bradmartin** [comment]
Just check the console for the error.

![md-icon-button](https://cloud.githubusercontent.com/assets/6006148/9347855/daa31640-45f4-11e5-959e-5a01704d4a0d.JPG)

**Comment by bradmartin** [comment]
line 2970.

**Comment by sincraianul** [comment]
Possible duplicate of #4213.

**Comment by bradmartin** [comment]
Yes same issue. Didn't see that issue.

**Comment by cilliemalan** [comment]
I'm getting the issue as well. An exception is thrown on [ripple.js:145](https://github.com/angular/material/blob/5d03df8ea38ae8fdc245d7edcac7e3b5fcb3795c/src/core/services/ripple/ripple.js#L145)

**Comment by bradmartin** [comment]
bower install pulls current master so the ripple issue is fixed.
