### ISSUE TITLE
md-button + md-tooltip + jQLite: md-focused Class Erroneously Added to md-button on mouseenter

### ISSUE THREAD

**Issue by mjhasbach** [angular/material#4225]
Angular 1.4.4
Angular Material 0.10.1
Chrome 44.0.2403.155 m

When an `md-button` contains an `md-tooltip`, the `md-focused` class is erroneously added to the `md-button` on mouseenter. Here's an [example](http://codepen.io/anon/pen/xGNeGz).

This issue does not occur:

- On the example site's [tooltip demo](https://material.angularjs.org/latest/#/demo/material.components.tooltip)
- When Angular is using jQuery ([example](http://codepen.io/anon/pen/jPjEyB))

**Comment by topherfangio** [comment]
Closing in favor of #4249 since this is a duplicate and it has more info.
