### ISSUE TITLE
docs: Tests and site broken when built from Windows

### ISSUE THREAD

**Issue by Splaktar** [angular/material#4226]
Issue reported in the [forums](https://groups.google.com/forum/#!topic/ngmaterial/XWqE2nLPS3E):

Building the docs on Windows and running the docs-karma task results in the following error:

    Uncaught SyntaxError: Unexpected token ILLEGAL
    at http://localhost:9877/base/dist/angular-material.js?6d5eb3c7d7db6b24f4d804669dc0db8a772d2c4c:20011

This also occurs when trying to load the docs site after it was built on Windows.

**Comment by ThomasBurleson** [comment]
@Splaktar  - nice work here. Thx.
