### ISSUE TITLE
md-dialog close animation incorrect when opened from md-menu item

### ISSUE THREAD

**Issue by pietschy** [angular/material#4228]
When closing a dialog that's opened from a md-menu it animates back to the top left of the page rather than from the location where it appeared from.

It would also be nice to explicitly set the element to animate out from and back to, as in my case I'd like the animation to emanate and return to the component that had the menu, and not the menu item itself.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by pietschy** [comment]
The issue of animating back to the top left of the page seems to be fixed as of release 0.11.x 

The ability to specify the element to animate from/to would still be nice as with drop down menus it still animates back to the position of menu item and not the element to which the menu belonged (in my case  a chip).  Would you like me to raise a separate issue for this?

**Comment by EladBezalel** [comment]
@pietschy can you please upload your use case so i can understand more deeply?

**Comment by pietschy** [comment]
Thanks @EladBezalel, here it is.  http://plnkr.co/edit/A705BAmFy1hxEqdCEeK6?p=preview
