### ISSUE TITLE
md-datepicker: expose on-change event

### ISSUE THREAD

**Issue by MilosStanic** [angular/material#4231]
It would be very useful to expose an on-change and/or on-click event for the datepicker. 

Real-life example justification: 
When creating a date range picker, and when selecting a date in the first datepicker, it would be useful to set max date or date value on the second datepicker on-change of the first datepicker.

**Comment by DefunctExodus** [comment]
:+1: 
For the exact same use case

**Comment by jelbourn** [comment]
@MilosStanic Just tried this; `ng-change` seems to work fine on the `md-datepicker` element. Does that work for you?

**Comment by MilosStanic** [comment]
@jelbourn, yeah, if it does work, I suppose it will do. I will test it soon.

**Comment by jelbourn** [comment]
Committed 487b9b7d4b7144bd0f7a9969151a6c2901a87070 to add `ng-change` to the docs.
