### ISSUE TITLE
<md-select> add setting to stop handle keydown event

### ISSUE THREAD

**Issue by dmaslov** [angular/material#4239]
Hi!
Is it possible to add a setting to ```<md-select>``` directive to stop handle keydown event?

The issue is that I have a select with search input to filter option items. When I press a button, input loses focus and cursor moves to matched option in the list. 
I want to prevent that behavior. 
Or maybe there is more elegant way to do what I want?
Thanks in advance!

My code:
```html
<md-select multiple ng-model="selectedItems">
  <md-input-container>
    <input type="text" ng-model="search">
  </md-input-container>
  <md-option ng-repeat="item in items | filter:search" ng-value="item.id">{{ item.value }}</md-option>
</md-select>
```

**Comment by holly-weisser** [comment]
@dmaslov  -- Did you find a way to handle this?  I'm running in to the same issue.

**Comment by dmaslov** [comment]
@holly-weisser 

Yes.
The main thing is ```ng-keydown``` with ```stopPropagation``` in handler.
Let me know if you need the full implementation (i am using custom wrapper over Angular and i need to convert my code to common view to make it understandable)

```html 
<md-select>
  <md-input-container>
    <input ng-model="controller.filterQuery" ng-keydown="controller.onSearchChange($event)">
  </md-input-container>
  <md-option ng-repeat="item in controller.items track by item.id" ng-value="item.id">
</md-select>
```
```javascript
controller.onSearchChange = function($event) {
  $event.stopPropagation();
  // Here you could use default Angular filter service, or use your own implementation of filter function
  this.items = functionToFilterItemsByQuery(this.filterQuery);
}
```

**Comment by holly-weisser** [comment]
Awesome, thank you!

**Comment by hsiri** [comment]
hello. i have tried adding $event.stopPropagation(); but still it does not stops the keydown event in the md-select. you have idea on this?

**Comment by kavare** [comment]
@hsiri Same here, event is still bubbling up

**Comment by hsiri** [comment]
@kavare fixed this already. anyways, thanks for informing

**Comment by felipemangalo** [comment]
<input type="text" ng-model="search" ng-keydown="$event.stopPropagation()">

**Comment by felipemangalo** [comment]
ng-keydown="$event.stopPropagation()"
