### ISSUE TITLE
Question: How do I modify the md-menu highlight on tab

### ISSUE THREAD

**Issue by jfarago** [angular/material#4240]
Currently, when you open a menu the first item is highlighted by default. I cannot see any kind of highlight class in the dom and if I toggle focus on the menu item it doesn't reappear. How can I modify this with my own highlighting css?

**Comment by rschmukler** [comment]
The rule in the CSS is `md-select-menu md-option:focus:not([selected])`

**Comment by jfarago** [comment]
Thank you
