### ISSUE TITLE
docs: sideNav is opened and dialog not dismissed when api reference is triggered 

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#4243]
When using the docs on a mobile device / small browser window, clicking the api reference select menu triggers strange behaviour.  It will trigger the sideNav to open when it is clicked, and If clicked when a dialog opened there will be additional visual issues.

[For dialog weirdness](http://i.imgur.com/DQVsO0b.png)

**Version**
Latest master
**Browser**
Latest webkit and Opera 31.
**Reproduce the Error**
Open a dialog and click the api select menu, or just click the api select menu.
**Related Issues**
potentially #4143

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
