### ISSUE TITLE
mdTabs: Cannot Scroll to the End of a Long Tab Label If It is the Last One

### ISSUE THREAD

**Issue by j-meyer** [angular/material#4247]
This is more apparent on mobile devices, but if you have a tab label that is longer than the viewport size, there is no way for the user to see the right edge of the last tab. This may be expected behaviour, but the right arrow will still show as "active" despite the fact that clicking the arrow will not actually do anything.

CodePen: http://codepen.io/anon/pen/rVEeeP

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by valenburm** [comment]
+1
