### ISSUE TITLE
md-datepicker: Validation error doesn't goes even after selecting valid date

### ISSUE THREAD

**Issue by pranav1877** [angular/material#4250]
I entered invalidate date 18/18/2015, this being an invalid date md-datepicker-invalid class is applied.

Open the datepicker and select valid date, even though the date is valid md-datepicker-invalid is still applied.

![image](https://cloud.githubusercontent.com/assets/7945697/9376276/65a2ef52-4728-11e5-81b9-543ca854a52b.png)

**Comment by jelbourn** [comment]
This should be fixed in 18458b740919cf2fabc9a9aec2a4fd63e121e339
