### ISSUE TITLE
SCSS compress error

### ISSUE THREAD

**Issue by vinaybedre** [angular/material#4252]
Hi,
When i try to generate css from scss file, i get error 
Error: Invalid CSS after "&:not(": expected ")", was "'.md-readonly')"
        on line 1781 of angular-material.scss
without me doing any changes yet to scss file. This bug has to be solved or documented in correct place.

**Comment by ThomasBurleson** [comment]
Our CI server and local builds and online docs all show the SCSS->CSS generation working correctly.
