### ISSUE TITLE
Error when click on md-button-icon

### ISSUE THREAD

**Issue by tsdragon0404** [angular/material#4253]
Uncaught TypeError: Cannot read property 'prop' of null
line 2970

step:
- open https://material.angularjs.org/latest/#/demo/material.components.sidenav in codePen
- change button Toggle Right with Icon Button, then click

**Comment by ironnie** [comment]
+1

**Comment by karolkochan** [comment]
+1

**Comment by bradmartin** [comment]
Try updating to the master, this should be fixed now.
