### ISSUE TITLE
md-tab arrow becomes visible after page load and disappears instantly

### ISSUE THREAD

**Issue by ronaldbluethl** [angular/material#4254]
there is enough space on the page so the arrow should not be displayed at all.

attached a short screencast for demonstration purpose
http://recordit.co/lPSxGaWWdA

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
