### ISSUE TITLE
aria-hidden="true" when refresh the page in md-button and img

### ISSUE THREAD

**Issue by ekaitzht** [angular/material#4255]
My md-button is with aria-hidden="true" when I refresh the page (page working with ui-router).

```HTML
	<md-button  ng-href="/edit_profile"  ng-show="user.isProfileAuthenticated" class="md-fab profile-button" aria-label="Edit Profile">
							<md-icon  md-svg-src="/assets/ic_edit_white_36px.svg"></md-icon>
					</md-button>
```

**Comment by marcysutton** [comment]
Can you provide a demo showing this issue? it could be a problem with `ng-show`. A workaround would be to use `ng-if` or to wrap the button in an element that shows/hides instead.
