### ISSUE TITLE
FAB speed dial mouse hit area includes invisible elements.

### ISSUE THREAD

**Issue by lanmower** [angular/material#4259]
For the FAB speed dial, when in hover mode, it also responds to mouse movements over the area defined for the invisible child elements to appear in, meaning that if you hover the mouse over inactive spot where one of the children are set to appear, then the fab activates and shows its children.

What is the expected behavior.

When you move a mouse over the trigger area, it should activate, not when you hover the mouse over the area that is designated for its popup buttons.

This is very important if you want to have fab spinners act as a style of toolbox for a card or something, so that when its closed up all the buttons are hidden and where they were you can still click on the underlying elements, and when its active the buttons appear over other content, right now anything in the area where buttons would appear is inaccessible.

This can be demonstrated on the second demo on the fab spinner demo page, hover the mouse in the white area under the fab.

**Comment by topherfangio** [comment]
We will work on adding support for this mode of operation.

For clarification, though, many people do want the existing behavior so that the speed dial will open when you hover near the trigger. This is the way Google Inbox currently utilizes their speed dial, so we cannot simply disable this feature.

We'll work to get it fixed in 0.12.

**Comment by MilosStanic** [comment]
This is what I refer to in #4257

**Comment by dohomi** [comment]
Hi Guys,
I have a quite difficult to report issue with this component on touch devices and the position combination ```md-fab-bottom-right```. If I add this class attribute the hit region of the button is outside of the ```md-fab-trigger```button. On usual mouse clicks I don't see this effect. The hit-region moves exactly bottom right outside of the element. I tried to set up a codepen but wasn't successful viewing it through my mobile device.

**Comment by topherfangio** [comment]
@dohomi This sounds like the exact same issue as above, and will be fixed in the next release.

**Comment by dohomi** [comment]
@topherfangio Thanks sounds great!

**Comment by topherfangio** [comment]
Just a quick update - I am currently working on a fix and hope to have something pushed to master this week. Will update again if that doesn't happen.

**Comment by dohomi** [comment]
@topherfangio great news, will it be part of 0.11.3?
