### ISSUE TITLE
AutocompleteBug in v 0.10.1

### ISSUE THREAD

**Issue by Anand-Khedkar-Avalara** [angular/material#4261]
If item want to search is not present then 'Not Found' message should appear.

See Image below

![autoselect bug](https://cloud.githubusercontent.com/assets/5468345/9386014/3145ec24-4777-11e5-8631-3d1f11d8ff4a.png)

**Comment by nestorneto** [comment]
yeah, its not working properly..

**Comment by anand-patel** [comment]
Yes, its not working.

**Comment by ngraef** [comment]
Duplicate of #3876

**Comment by hannupekka** [comment]
If you open this same example in CodePen (button next to "View Source" in the header of "Basic Usage") and try to select any suggestion, `<md-not-found>` always stays visible.
