### ISSUE TITLE
Chips bug in v 0.10.1

### ISSUE THREAD

**Issue by Anand-Khedkar-Avalara** [angular/material#4263]
Steps-
1. search for contact which is not present
2. Hit enter. 
    In v 0.10.1 its adding blank clip. 
    Expected should not do anything, unless valid/present item is selected. (working good in v 0.10)

Please screenshots below.
![clip bug](https://cloud.githubusercontent.com/assets/5468345/9387784/ce882ce2-477f-11e5-94d8-95861e1a180a.png)

**Comment by ngraef** [comment]
Already fixed in master

**Comment by Anand-Khedkar-Avalara** [comment]
Cool. Thanks
