### ISSUE TITLE
DatePicker: $compile RTE if ng-model is not specified

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4265]
Using `<md-datepicker md-placeholder="Enter date"></md-datepicker>` 

> where the `ng-model="user.submissionDate"` is not specified

generates an RTE:

<img width="367" alt="datepicker_rte" src="https://cloud.githubusercontent.com/assets/210413/9388511/8ed83992-472b-11e5-94a9-df8b119a8f46.png">

**Comment by jelbourn** [comment]
@ThomasBurleson I talked about this with @robertmesserle and we think the current behavior makes sense. What you're seeing is the standard minified AngularJS error from using a directive where one of the `require` directives is missing. Clicking the link in the error brings you to an explanation.

If the user has AngularJS in unminified mode, they'll get the full error right in the console.

**Comment by ThomasBurleson** [comment]
@jelbourn - conformance to standard directive error reporting SGTM. I will close.
