### ISSUE TITLE
md-autocomplete / powered-by-google logo requiremements

### ISSUE THREAD

**Issue by jtosey** [angular/material#4268]
Google Places suggestions are typically presented using autocomplete.  How do you configure md-autocomplete to append the Powered By Google logo as an unselectable result?

Google Places API requirements states:

*If your application displays Places API data on a page or view that does not also display a Google Map, you must show a "Powered by Google" logo with that data. For example, if your application displays a list of places on one tab, and a Google Map with those places on another tab, the first tab must show the "Powered by Google" logo.*

**Comment by cssensei** [comment]
Maybe this could be an actual feature: ability to append unselectable results to `md-autocomplete`

**Comment by korrix** [comment]
+1

**Comment by raoabishay** [comment]
+1 - Absolutely necessary. Our app uses the Place Web API Service and Angular Material. I don't find a solution to integrate the "Powered by Google" logo with the location md-autocomplete box. I hope putting this logo in the footer still complies with Google's attribution requirements!

**Comment by JackForbes** [comment]
Anyone have a solution to this?

**Comment by Splaktar** [comment]
You just need to have the "Powered by Google" logo on the same tab. It doesn't have to be in the same component (i.e. `md-autocomplete`). 

As far as I read it, you don't need to create an `option` that says "Powered by Google" and has the logo but does nothing. This would be bad UX.

I believe that the requirement is just asking that you add a label and logo nearby (on the same view) for attribution.
