### ISSUE TITLE
md-tabs: Scrolls to top of page when tab is clicked

### ISSUE THREAD

**Issue by SmoshySmosh** [angular/material#4281]
Clicking a new tab while using md-tabs will switch the tab but will also scroll the browser to the top of the page. Is this expected?

Tested on:
- Chrome
- Firefox
- Safari

Replicate:
Codepen: http://codepen.io/anon/pen/pJXYbX
1. Scroll to bottom
2. Press Tab 3
3. Notice it scrolls to the top.

Note: In this example only tab 3 does it. But it consistently happens when clicking any tab in my project.

**Comment by abramz** [comment]
Also encountering this issue.

**Comment by nathanmarks** [comment]
Not happening to me, what browser?

**Comment by nathanmarks** [comment]
@SmoshySmosh It's scrolling me to the top of the tab but not the top of the page

**Comment by SmoshySmosh** [comment]
@nathanmarks Looking at it again, you're right. On my site it looked like it scrolled all the way to the top of the page because you can just barely see the top of the tabs after you click to a new tab.

Still though, the problem remains that this is scrolling is unwanted and problematic for people who are trying to display important content with the md-tabs component.

**Comment by chazzlabs** [comment]
+1

Also seeing this issue on Firefox and Chrome.

**Comment by chris-jana** [comment]
I'm seeing this as well.  For me it only happens when clicking on tabs further to the right.  Clicking on a tab to the left of the active tab does not seem to trigger a scroll to the top.

**Comment by robertmesserle** [comment]
This appears to be resolved now.

**Comment by yarick333** [comment]
Reproduces in 0.11.4

**Comment by ThomasBurleson** [comment]
@yarick333 - CodePen Demo please.

**Comment by yarick333** [comment]
http://codepen.io/anon/pen/ojogER
it only happens when clicking on tabs further to the right. Clicking on a tab to the left of the active tab does not seem to trigger a scroll to the top.

**Comment by ThomasBurleson** [comment]
@robertmesserle - can your review ?

**Comment by yarick333** [comment]
You need to add CSS:
.tabsdemoDynamicHeight md-content md-tabs {
    border: 1px solid #e1e1e1; }
All work then

**Comment by robertmesserle** [comment]
Looking into this now.  This only happens when `md-dynamic-height` is enabled, which makes me think it is due to a brief period where there is no content height while switching tabs.  Looking into a way to make sure the height never flashes to 0 during this time.

**Comment by blmcquillan** [comment]
I agree that it shouldn't scroll to the top of the entire page, but it *should* scroll to the top of the tabs themselves?

referring to my issue #5239

**Comment by manuelagard** [comment]
I have the same "scrolling to the top" problem on v1.0.6 for Safari when md-dynamic-height is enabled. On Chrome, it is working perfectly.
Not very user friendly and quiet problematic for Safari users.
Is there any turn around or fix ?
I tried the fix proposed by @robertmesserle but it doesn't worked for me...
Any idea guys ?

**Comment by manuelagard** [comment]
I opened a new issue #8065  showing the same problem with an animated gif.
Tested on the actual Angular Material Demo website : https://material.angularjs.org/0.11.2/#/demo/material.components.tabs

Version 1.1.0-RC4

**Comment by r0b-** [comment]
Problem still exists but only when tabs are paginated...
Using 1.1.0 RC5 with chrome...

**Comment by immersionfx** [comment]
+1

**Comment by bonatoc** [comment]
Problem seems to gone from Chrome 63, but present in Firefox 57.0.4.

Oddly, it only happens when clicking from the first tab to another. Clicking from any other tab to any other tab doesn't trigger the scroll to top.
