### ISSUE TITLE
ER: mdSlider should be able to have a "maximum" that is not the end of the slider

### ISSUE THREAD

**Issue by AaronBuxbaum** [angular/material#4285]
I have a use-case where I have many sliders. They all should have a maximum value of 100, but the _total_ of all of the sliders has to be <= 100. You can think of it as percentage values for multiple elements, where the percent should not exceed 100%.

While this is currently sort of possible, it causes weird issues where the maximum values are constantly changing, and you never really get to see how much each slider relates to the full 100% value. Having a `limit` attribute (or something like that) that limits how far a slider value can go within the min/max constraints, would be really useful. I can imagine others have similar use cases to mine.

**Comment by innerpeace0** [comment]
I agree. The ideal slider would have two low values, the displayed low and the slider range low, and two high values, the displayed high and the slider range high. The slider range low would be greater than or equal to the displayed low. The slider range high would be less than or equal to the displayed high. The default style on any inaccessible part would be grayed down to some extent to show that it is an inactive zone.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
