### ISSUE TITLE
strange md-tabs stretch always behavior

### ISSUE THREAD

**Issue by djrobotfreak** [angular/material#4286]
My md-tabs are trying to paginate when stretch always is applied, though there are only two of them so there is nowhere to paginate (see picture 1). After clicking either tab they fix themselves and stretch as expected (see picture 2). 

Here is the code I am using for the tabs:
<md-tabs md-selected="menu.selectedIndex" class="md-primary" md-stretch-tabs="always" md-center-tabs="true" md-swipe-content="true" md-theme-watch>

<img width="303" alt="screen shot 2015-08-22 at 9 43 18 am" src="https://cloud.githubusercontent.com/assets/3532811/9424488/d0f3cf7e-48b3-11e5-9b8a-0abf89bef84a.png">
<img width="304" alt="screen shot 2015-08-22 at 9 43 58 am" src="https://cloud.githubusercontent.com/assets/3532811/9424487/d0f3954a-48b3-11e5-8feb-b145754aed51.png">

Am I approaching this incorrectly?

**Comment by gpopovic** [comment]
I have same issue

**Comment by miclaus** [comment]
See also #4749 how it breaks on more tabs.

**Comment by robertmesserle** [comment]
I am not able to recreate this with the latest code.  Closing for now - please add a CodePen demo if this is still an issue.
