### ISSUE TITLE
slow render on IE11 using ng-repeat with ng-if

### ISSUE THREAD

**Issue by calebeaires** [angular/material#4288]
With a "not so big" list of items, using ng-repeat and ng-if, the dom rendering goes very slow on Microsoft Edge/IE11. But on Chrome the rendering goes very fast. 

Take an example: https://jsfiddle.net/hg4mskmc/

**Comment by ThomasBurleson** [comment]
@calebeaires - please test again with these resources:

*  https://material.angularjs.org/HEAD/angular-material.min.css
*  https://material.angularjs.org/HEAD/angular-material.min.js

**Comment by calebeaires** [comment]
Solved: https://github.com/angular/material/issues/1771

**Comment by surigorantla** [comment]
@calebeaires I am also facing similar issue IE 11, the browser is hanging and could not scroll. I am populating data using ng-repeat(around 5). How it got resolved ? Do we have to just include above files in our code or do we have to use some functionality in above Js instead of ng-repeat?

**Comment by ThomasBurleson** [comment]
Please re-post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
