### ISSUE TITLE
Date input field different format

### ISSUE THREAD

**Issue by seemsindie** [angular/material#4290]
This is a question rather then issue. Can i somehow reverse the order then mm and dd in the date field?

So i want to have dd/mm/yyyy instead of mm/dd/yyyy, can i do that?

Thanks.

**Comment by dterbeest** [comment]
You can configure the parsing and formatting of dates using the $mdDateLocaleProvider
https://material.angularjs.org/HEAD/#/api/material.components.datepicker/service/$mdDateLocaleProvider

**Comment by jelbourn** [comment]
@dterbeest is correct. Use ` $mdDateLocaleProvider`
