### ISSUE TITLE
md-fab-speed-dial inside md-toolbar hides trigger button

### ISSUE THREAD

**Issue by amarden** [angular/material#4292]
When trying to use speed dial inside md-toolbar under a div class="md-toolbar-tools" the trigger button seems to be pushed up above the toolbar along with a few options. The trigger action and speed dial open animation still work if one hovers in the area where you would expect the trigger button to be. 

See codepen: http://codepen.io/amarden/pen/JdgPwY. While the example is using an ng-repeat I also tried this without ng-repeat and got the same results.

Occurs in at least Chrome, Mozilla, and IE10. 

Thank you for all your effort so far on the library (it is awesome) and let me know if I can give you any other information.

**Comment by topherfangio** [comment]
I'm having some trouble creating a new codepen to test with (latest master is having some issues), but I think there may be a very easy workaround available in master. I will respond later today or tomorrow when I can get the codepens working again.

**Comment by topherfangio** [comment]
Sorry for the delay; I think you want to add the `md-fab-top-left` class to the speed dial to get it to work like you want.

I forked your codepen to update to the master version of material and show the basic usage: http://codepen.io/topherfangio/pen/VvYwGK?editors=101

Can you let me know if this works for you?

**Comment by amarden** [comment]
Yes this working now. Thank you!
