### ISSUE TITLE
Using `md-<elements>` with React and JSX.

### ISSUE THREAD

**Issue by piyushchauhan2011** [angular/material#4293]
We are a small company and using Ruby on Rails with AngularJS and Angular-Material. The current architecture has `bower` and `npm` integration with `rails 4.2`. We also have `browserify` integration and as a developer I tried to use `React` and `JSX` with Angular Material components but it gives me error as `JSX` is not able to compile them correctly.

Does anybody know how to use these components if we want in JSX and React? If possible please provide example or better a sample github project.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
