### ISSUE TITLE
Auto select chip when pressing enter (instead of just tab) for md-chips & md-autocomplete - enhancement

### ISSUE THREAD

**Issue by apat183** [angular/material#4299]
Hi,

Enhancement recommendation for the md-chips when using with md-autocomplete and the md-autoselect option enabled. 

Currently when you use md-chips and md-autocomplete (as in the veg example here https://material.angularjs.org/latest/#/demo/material.components.chips) and when you enable the autoselect option/tag. If you start typing and click "tab", the first result is added as a chip. However, if you click "enter" on your keyboard if just adds a blank chip. I think it is more natural to click "enter" to select an item. Would be useful to be able to click "tab" or "enter" since "enter" is not being used for anything at the moment when using md-chips & md-autocomplete. 

Here is example, you can try added items using tab (and it works) but when pressing enter it shows blank.

http://codepen.io/anon/pen/gpVRRz?editors=101

Thanks

**Comment by ngraef** [comment]
This is fixed in master.

**Comment by apat183** [comment]
Thanks, so I'm currently using 0.10.1. Are you talking about this commit? https://github.com/angular/material/commit/d16d2b66

I don't seem to be able to get it to work as expected, does it work for md-chips or only inputs with auto-complete?

**Comment by ngraef** [comment]
@apat183 Nope, see #3475 and all the issues linked to it. Fixed by 86db4db9fd6e61314c1ce08cbffdffd52eae787f.

**Comment by topherfangio** [comment]
This does appear to be fixed in master, but I just noticed another small issue that may make it seem like this isn't working:

In the demo, the autocomplete is currently showing contacts that have already been selected, and if you hit tab/enter on one of them, it will hide the autocomplete and make it look like the component does nothing.

You can view the latest docs/version [here](https://material.angularjs.org/HEAD/#/demo/material.components.chips) which shows the fix @ngraef mentioned.

**Comment by apat183** [comment]
Thanks but I'm still not having any luck. I'm testing with head master, added md-autoselect but now it doesn't automatically select first item on tab or enter? I have to manually click item. I added md-select-on-match as well but doesn't help. 

http://codepen.io/anon/pen/QbeYWp

**Comment by topherfangio** [comment]
Can you checkout this demo? http://codepen.io/topherfangio/pen/ZbzzZV?editors=101

It appears to be working perfectly for me with both tab and enter. If it doesn't work for you, perhaps it is a browser issue? I'm using Chrome 44.

**Comment by apat183** [comment]
Thanks, you example is working on my work laptop (Windows and Chrome 44). I was trying last night on my MAC and Chrome (not sure version). 

I figured out what I was doing wrong (face palm moment). For my example I was adding the md-autoselect="true" to the chip tag instead of autocomplete tab. My example works as expected once I move the tag. Thanks. Looking forward to next stable version with the commit :). What is the best way to clost this?

**Comment by topherfangio** [comment]
No problem! 0.11 should be landing pretty soon and will have all of these fixes :-)
