### ISSUE TITLE
Apply ng-click to md-icon won't work on IE 10

### ISSUE THREAD

**Issue by ypwu1** [angular/material#4300]
I use md-icon and apply ng-click to it, but seem it doesn't work,  but works on chrome. I tried use <a> tag to wrap the icon and move the ng-click to wrapper, still not work on IE 10. Is it kind of browser feature?

**Comment by marcysutton** [comment]
Can you provide a Codepen or Plunker showing your issue? `ng-click` should go on an `md-button` element that wraps `md-icon`, so that keyboard users can reach it.

**Comment by ThomasBurleson** [comment]
Clicks are md-icon are not supported. Use md-button with a child md-icon.
