### ISSUE TITLE
md-menu-bar: iOS issues

### ISSUE THREAD

**Issue by kschwidder** [angular/material#4301]
On iOS the behaviour of md-menu-Bar is different as follows:

A) when switching to another Root menu Element in the menu-bar then the current selected menu is not hidden. Therefore all Root menu entries are shown overlapped
B) submenu items are not displayed at all.

Great work so far !

**Comment by rschmukler** [comment]
@kschwidder The `md-menu-bar` is not intended to be a mobile component or work on mobile. Is there a use case?

**Comment by kschwidder** [comment]
If the md-menu-bar is not intended for mobile components it should be explicitly documented. All md-components are available for all devices and therefore md-menu-bar should also be supported on mobile devices.

Especially when you write a responsive SPA application the md-menu-bar could be of use in mobile environments too. A use case is on tablets.

**Comment by ThomasBurleson** [comment]
@kschwidder - Thank you for the reminder @see https://github.com/angular/material/issues/4563

**Comment by ddjonline** [comment]
Just out of curiosity (with a heavy vested interest in the answer as we are about to go to production with an application that uses md-menu-bar and was intending to work on mobile as well) what is the alternative for mobile? I personally do NOT find it acceptable to simply state that something was not intended to work on mobile to avoid fixing the issues. This directive has been in the code for far too long without the mobile caveat documentation clause to let that stand.
