### ISSUE TITLE
Clicking on md-menu inside md-list clicks also the undelaying md-list-item

### ISSUE THREAD

**Issue by iskuda** [angular/material#4303]
When I click button to open md-menu inside md-list, if ng-click is set on md-list-item or md-list-item contains md-checkbox the md-list-item/md-checkbox gets also clicked. See example:

http://codepen.io/anon/pen/WvLvLR 

When I remove ng-click/md-checkbox from list-item, md-divider disappear. See example:

http://codepen.io/anon/pen/KpOgBW

**Comment by marcysutton** [comment]
Your demo isn't showing checkboxes. Can you check to make sure they are working as intended? I wanted to look at the interaction and make sure it wasn't going to cause problems for accessibility.

**Comment by iskuda** [comment]
The first demo (http://codepen.io/anon/pen/WvLvLR) is with checkboxes.

The second demo (http://codepen.io/anon/pen/KpOgBW) is showing md-divider bug.

**Comment by rschmukler** [comment]
The second issue could reference #4017

**Comment by rschmukler** [comment]
Regarding your second demo, the `md-divider` should go *outside* the `md-list-item`.

For example:

```html
<div ng-repeat="...">
  <md-list-item>...</md-list-item>
  <md-divider></md-divider>
</div>
```
