### ISSUE TITLE
Master  v0.10.1-master-814e58b -  'appSvgIconSets' module undefined

### ISSUE THREAD

**Issue by bradmartin** [angular/material#4305]
The current master has an issue with 'appSvgIconSets' module. @ThomasBurleson

**Comment by jbraccini** [comment]
+1

**Comment by DefunctExodus** [comment]
+1

**Comment by cteplovs** [comment]
+1

**Comment by kschwidder** [comment]
+1

**Comment by srikanthnadella** [comment]
+1

**Comment by ThomasBurleson** [comment]
@bradmartin - I am not seeing any issue with https://material.angularjs.org/HEAD/#/demo/material.components.icon. Can you explain ?

**Comment by srikanthnadella** [comment]
Hi,

This is the error log when trying to launch my angular app using bower-material/master:

Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
Error: [$injector:modulerr] Failed to instantiate module appSvgIconSets due to:
Error: [$injector:nomod] Module 'appSvgIconSets' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.13/$injector/nomod?p0=appSvgIconSets

**Comment by bradmartin** [comment]
![appsvg not present](https://cloud.githubusercontent.com/assets/6006148/9446186/d5fef0ea-4a55-11e5-81ef-f4c382e2bd6c.PNG)

Don't think the source is actually the master on the demo site. See image

**Comment by ThomasBurleson** [comment]
![screen shot 2015-08-24 at 11 58 10 am](https://cloud.githubusercontent.com/assets/210413/9446459/739c3816-4a57-11e5-8018-1bce828fcf14.png)

Notice the **Demo - Icon** uses `docs-demo-scripts.js` which is where the demo module `angular.module('appSvgIconSets'...)` is defined.

**Comment by bradmartin** [comment]
Got it. In the angular-material.js file the only refs to 'appSvgIconSets' is in the '@usage' comment block line 17741, and in DI for the module.

**Comment by icchio** [comment]
same problem for me using https://gitcdn.xyz/repo/angular/bower-material/master/angular-material.js....

**Comment by Aaron-Hartwig** [comment]
Also getting this problem on a fiddle demo https://jsfiddle.net/0ju750xo/23/

**Comment by robertbaker** [comment]
+1

**Comment by mjsgreen01** [comment]
+1

**Comment by andresob** [comment]
+1

**Comment by mjsgreen01** [comment]
adding this fixed it for me:
angular.module('appSvgIconSets', ['ngMaterial'])
  .controller('DemoCtrl', function($scope) {})
  .config(function($mdIconProvider) {
    $mdIconProvider
      .iconSet('social', 'img/icons/sets/social-icons.svg', 24)
      .defaultIconSet('img/icons/sets/core-icons.svg', 24);
  });

**Comment by robertbaker** [comment]
Seems like the compiled bower version included a demo script when it shouldn't.

**Comment by robertbaker** [comment]
https://raw.githubusercontent.com/angular/bower-material/master/angular-material.js

Line 13, right in the module definition at the of the dep list, it's including appSvgIconSets. remove that are your good.

**Comment by robertbaker** [comment]
The bug must be in this: https://github.com/angular/material/blob/master/scripts/gulp-utils.js

**Comment by ngraef** [comment]
@ThomasBurleson The build script is picking up `appSvgIconSets` from [the comments in iconDirective.js](https://github.com/angular/material/blob/master/src/components/icon/js/iconDirective.js#L127).
