### ISSUE TITLE
autocomplete regression: persistent scrollbar

### ISSUE THREAD

**Issue by ngraef** [angular/material#4308]
Introduced by f81719363d0445aa6dc393ba42631a3ba7d77071

Scroll arrows are visible even when the list doesn't need to scroll. Caused by `md-virtual-repeat-sizer` being too large or the virtual repeat container being too small. Additionally, there is extra space in the right margin that is noticeable on item hover/focus.

![image](https://cloud.githubusercontent.com/assets/1031317/9454898/5a31f1e8-4a8b-11e5-9576-9b4002a7e0ba.png)

**Comment by gpopovic** [comment]
+1

**Comment by bluebirdtech** [comment]
+1

**Comment by topherfangio** [comment]
@robertmesserle The following comment may be helpful in tracking this down: https://github.com/angular/material/issues/4450#issuecomment-137628385

**Comment by jacksonrayhamilton** [comment]
+1 on this... using `display: none` on `.md-virtual-repeat-sizer` prevents the scrollbar from appearing, and does not appear to break the widget. Am I missing something or is that element even needed?

**Comment by bluebirdtech** [comment]
The sizer is needed when there are virtualized items.

The height of the sizer seems fine in the inspector, and there is no additional padding/margin.  For some reason display: inline-block is causing this.  Using block fixes it.

Workaround:
````.md-virtual-repeat-sizer {
    display: block !important;
}````
