### ISSUE TITLE
autocomplete regression: not-found displayed after item select

### ISSUE THREAD

**Issue by ngraef** [angular/material#4309]
Introduced by f817193

The `md-not-found` message is displayed after selecting an item from the list.

States example:
![image](https://cloud.githubusercontent.com/assets/1031317/9455057/e968f16c-4a8c-11e5-9473-a555b41b830a.png)

Repository example (no `md-not-found`):
![image](https://cloud.githubusercontent.com/assets/1031317/9455156/ebc7c4be-4a8d-11e5-9db7-d78baf3539de.png)

**Comment by Frank3K** [comment]
+1

Contact chips are also broken.

**Comment by topherfangio** [comment]
This appears to be related to the following commit f81719363d0445aa6dc393ba42631a3ba7d77071

**Comment by mohitadwani** [comment]
+1 and it does not close when you go out of focus.

**Comment by mohitadwani** [comment]
if md-min-length is set, md-not-found triggers even after typing one character, but it starts searching after min-length only.

**Comment by mckenzielong** [comment]
This still is happening in master.  Open up the docs site to the autocomplete page, and type 'z' / any not found character into the box.  The empty box will still be displayed. 

Appears to be fixed for the floating label however...

Related (or still opened dupe): #4321

**Comment by steezeburger** [comment]
I'm still having this issue as well.

**Comment by topherfangio** [comment]
Related to #4665 .
