### ISSUE TITLE
Material-Angular on Electron

### ISSUE THREAD

**Issue by VikramTiwari** [angular/material#4311]
Has anyone tried using material angular on electron? I am trying the same but seems like its not coming through. Anything I might be missing?

**Comment by omrilitov** [comment]
I am currently using angular material 0.10.1 with electron. 
So far i don't have any issues

**Comment by topherfangio** [comment]
These types of questions are typically better asked/answered on the (forums)[https://groups.google.com/forum/#!forum/ngmaterial/topics].

**Comment by VikramTiwari** [comment]
Thanks @topherfangio and @omrilitov . Closing this. :+1:
