### ISSUE TITLE
md-datepicker: changing date value on input field remains invalid

### ISSUE THREAD

**Issue by kschwidder** [angular/material#4312]
When you directly edit the input field the date value is not updated accordingly and the field is marked as red.
It would be great if a date parser is attached to the input field based on a given list of patterns to validate the input.

**Comment by jelbourn** [comment]
@kschwidder There's not enough detail here to understand your issue. The datepicker will render the invalid state when the text entered cannot be parsed as a valid date. You can define your own parsing function via `$mdDateLocaleProvider`. 

Re-open this issue with more info if that does not give you what you need.
