### ISSUE TITLE
md-date-picker: Usability scrolling

### ISSUE THREAD

**Issue by kschwidder** [angular/material#4313]
It is not obvious that you can scroll through the dates. 
In addition keyboard interactions are not enabled too.

**Comment by jelbourn** [comment]
@kschwidder Keyboard interaction should be there. Can you file a separate issue with more details for that?

**Comment by jelbourn** [comment]
Committed 1330cb0924b9be31e5262d665660d7c84eaab90f to better cue the scrolling. Closing this issue for now; may re-open if feedback persists.

**Comment by RenaldasK** [comment]
Some clients are still complaining about the usability of the datepicker. Would it be possbile to add a configuration option to show a scrollbar?
