### ISSUE TITLE
md-virtual-repeat at a preset starting point?

### ISSUE THREAD

**Issue by viztastic** [angular/material#4315]
I love md-virtuala-repeat.

I am wondering if there should be an attribute that allows setting the $index at which  the scroll-bar should default to?

This would be helpful in a range of use cases. Bookmarking all the way to allowing users to auto-scroll based on some other input or control they adjust (e.g. a drop-down, or text-input).

**Comment by RolandHeath** [comment]
+1
This would be useful, for example generating a searchable table/list with an md-autocomplete. 
Will probably require existing scrolling issues (#4169) to be resolved.

**Comment by RolandHeath** [comment]
@viztastic Alternatively, you could just use: 
    document.getElementById( 'your_virtual_repeat' ).scrollIntoView();
Maybe this doesn't need to be an attribute built in.

**Comment by kseamon** [comment]
The container's controller has a public method called "scrollTo".

You'd have to get a reference to it with a call to element.controller('mdVirtualRepeatContainer'), which is awkward, but doable. Is that enough or do you need some sort of direct binding?

**Comment by RolandHeath** [comment]
There are ways to solve this which aren't hack-ish.
Can't speak for the OP, but I don't see a need for this. Maybe post-1.0?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
