### ISSUE TITLE
md-datepicker / $mdDateLocaleProvider needs option to set first day of the week

### ISSUE THREAD

**Issue by jb29** [angular/material#4316]
In `md-datepicker` the first day of the week is currently set to Sunday.
In Germany for example, Monday is considered to be the first day of the week.

It would be very useful if we could change this in `$mdDateLocaleProvider`.
Maybe there's already an undocumented option for that?

**Comment by dleitee** [comment]
+1

**Comment by kschwidder** [comment]
+1

**Comment by Patrik-Lundqvist** [comment]
Yeah, this would be great!

**Comment by tolemac** [comment]
+1

**Comment by jelbourn** [comment]
I had originally thought that the `Date.prototype.getDay` method was locale-aware. Turns out that that is [not the case](http://www.ecma-international.org/ecma-262/6.0/#sec-week-day). Will resolve this ASAP.

**Comment by eriksalhus** [comment]
+1

**Comment by tolemac** [comment]
Great, a pity that did not come to version 0.11.0.

Thank you!

**Comment by vasiliy0s** [comment]
I fixed this with the next code:
```js
export default function run($mdDateLocale) {
  'ngInject';
  $mdDateLocale.firstDayOfWeek = 1;
}
```
