### ISSUE TITLE
Use icon to open md-select (or dynamically open it)

### ISSUE THREAD

**Issue by Havock94** [angular/material#4317]
Hi,
I would like to know if it's possible to have an icon that triggers a md-select.

Look at this image, this is the desired effect that I would like to have.
[Select triggered by icon](http://i.stack.imgur.com/JZ1qk.jpg)

Does anyone have some advice on how to achieve it?

It would be nice to have a service like $mdSelect to dynamically open/close the select like how it happens with sidenavs.

Thank you!

**Comment by Havock94** [comment]
If anyone is interested, for the moment I ended up using a md-menu with a (Angular) repeater inside it.

**Comment by rschmukler** [comment]
This is possible. See the [demo page](https://material.angularjs.org/latest/#/demo/material.components.menu) which shows `md-position-mode` and `md-offset`. [The docs](https://material.angularjs.org/latest/#/api/material.components.menu/directive/mdMenu) should also clarify this.
