### ISSUE TITLE
Invalid toasts order and content override

### ISSUE THREAD

**Issue by karolkochan** [angular/material#4318]
Take a look at: 
http://codepen.io/karolkochan/pen/WvVzEP 
and fast click multiple times on 'SHOW SIMPLE' button. There are 3 errors with toast behavior: 
- toasts should raise in ascending order instead of random 
- you can see that multiple toasts, when hiding, have the same content (it is easier to notice if you enable line 7 in js: '$mdToast.hide();')
- toasts sometimes hide faster than desired delay

**Comment by amitport** [comment]
:+1:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
