### ISSUE TITLE
bug: page scroll shows hidden content

### ISSUE THREAD

**Issue by scottnath** [angular/material#432]
Good morning,

I have implemented material into my angular app to try it out. I've noticed on pages which are longer than the browser window that any content outside of the window is not available when you scroll down and appears blank.

Example here:
http://scottnath.github.io/atlas/#/

I have dug through the css with the inspector and I can't find the item which is causing this.

The ghpages version above contains all scripts minified and concatenated. If you would like to test the raw code, then it is here:
https://github.com/scottnath/atlas
The bug is happening with non-converted scripts as well.

Thanks for any help!
Scott

**Comment by ajoslin** [comment]
I don't think this is a problem anymore, I'm going to close it for now.

Back when this issue was posted I played with the height on the body but the results were inconclusive. A lot has changed since then.

Can you reopen if you're still having problems?

Thanks.
