### ISSUE TITLE
Autocomplete - Custom Template demo in master HEAD - Dropdown list not disappearing

### ISSUE THREAD

**Issue by Soulcyber** [angular/material#4321]
try it here:
https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete

using Google Chrome:  44.0.2403.157 m

After selection the dropdown list does not disappear
![image](https://cloud.githubusercontent.com/assets/4432213/9466951/94862adc-4b38-11e5-93a5-d1ace8d65e20.png)

**Comment by alexitooi** [comment]
+1

**Comment by ngraef** [comment]
Duplicate of #4309
