### ISSUE TITLE
Data bound md-autocomplete in md-sidenav produces unwanted <ul> elements 

### ISSUE THREAD

**Issue by lscordilis** [angular/material#4322]
I have a form in a toggle-able sidenav that populates itself with the existing values of a $scope object whenever the form is opened using events bound to the ```$mdComponentRegistry```
 Several of these form elements are ```<md-autocomplete>```. For some reason, ```<ul>``` elements whose contents are the same contents of the form's ```<md-autocomplete>``` elements appear at the top of the page, outside any of my templates, and they disappear on mouseover or on selecting the form element to edit them. I don't know what purpose creating these elements serves but obviously this is not the intended behavior of this implementation.

I tried to capture the problem as best as I could.

Here is the unwanted html:
![image](https://cloud.githubusercontent.com/assets/12753650/9468913/497c8e76-4b12-11e5-9e02-c10eebc5001f.png)

This is what the form element looks like in the sidenav:
![image](https://cloud.githubusercontent.com/assets/12753650/9468959/8335e9fa-4b12-11e5-97b2-b86c3f97f69e.png)

These are what the unwanted elements look like at the top left-hand corner of the page:
![image](https://cloud.githubusercontent.com/assets/12753650/9469069/0ab7a86e-4b13-11e5-9b40-6ef05fd5979b.png)

Thanks in advance :)

**Comment by robertmesserle** [comment]
@lscordilis Can you provide a demo for this?

Also, from the screenshot, it looks like they have the `ng-hide` class - any reason they are not being hidden?

**Comment by robertmesserle** [comment]
I am not able to recreate this.  Closing for now, please reopen with a CodePen demo if this issue still exists.

**Comment by lscordilis** [comment]
This issue is no longer a problem for me because I query the server directly on ```md-search-text-change``` instead of loading the whole collection of items into the client. However, unless anything has changed to address this, I would imagine it still happens. I'll see if I can attach a demo, recreating the problem when I've got some spare time. Thanks anyway :)
