### ISSUE TITLE
md-virtual-repeat with one-way data binding

### ISSUE THREAD

**Issue by extrafu** [angular/material#4323]
Hello.

md-virtual-repeat breaks if you use one-way data binding. If we use the "Vertical Usage" demo from material.angularjs.org and we just enable one-way data binding, it breaks.

See the codepen:

http://codepen.io/anon/pen/YXmvMG

This happens with 0.10.1 and master.

Thanks,

**Comment by bradmartin** [comment]
From my understanding that's not possible @extrafu - I haven't looked into the code much but I have seen other implementations of what the virtual-repeat does. Basically they remove elements from the DOM and then adds it in when it's near the scrolling point. Sorry I can't give you a perfect explanation for now but I don't think that one way binding is possible with what the virtual repeat itself is or what it tries to accomplish. However, you shouldn't need one way binding with a virtual-repeat, at least not from my experience. I've used it with over 1000 items in the collection and never had any problem.

Also, from my experience I find it better to rethink the reason you are using the virtual-repeat and try to handle the UI differently. With the performance improvements in Angular 1.4 along with an infinite scrolling UI for long lists I've had better performance than with virtual-repeat options.

**Comment by kseamon** [comment]
Yes, I need to make this clear in the documentation, but one-way binding is not supported for the reasons @bradmartin outlines above.
