### ISSUE TITLE
Icon misaligned vertically in icon button

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#4324]
Looking at the demo page, if you add background colors and remove border-radius, the icon button will look like this:

<img width="367" alt="screen shot 2015-08-25 at 12 51 07 pm" src="https://cloud.githubusercontent.com/assets/9092817/9473407/a764e928-4b28-11e5-90d3-f09cc65a82cd.png">

The icon is very slightly below where it should be. Here's what it looks like if you correct this, for example by using "vertical-align: top; margin-top: 12px" instead of the current "vertical-align: middle":

<img width="359" alt="screen shot 2015-08-25 at 12 52 11 pm" src="https://cloud.githubusercontent.com/assets/9092817/9473479/0ee15a0a-4b29-11e5-80a1-c2dc09198530.png">

In itself not much of a problem, but I ran into this when in my app I overrode the size of the button to be smaller, and then the misalignment became clearly visible.

**Comment by ivan7237d** [comment]
And the same issue for FAB:

Demo page:
<img width="56" alt="screen shot 2015-08-25 at 2 44 57 pm" src="https://cloud.githubusercontent.com/assets/9092817/9475995/32f6b7fa-4b38-11e5-918b-8e478a675d06.png">

Should be:
<img width="51" alt="screen shot 2015-08-25 at 2 46 46 pm" src="https://cloud.githubusercontent.com/assets/9092817/9476003/3ade1472-4b38-11e5-88b6-183a2412a9d9.png">

**Comment by EladBezalel** [comment]
fixed in #5607
