### ISSUE TITLE
Customize tab ripple's color

### ISSUE THREAD

**Issue by bonatoc** [angular/material#4325]
I want to customize the color of the tab ripples. 

I need the inkbar color to be black, but the greyed-out ripple it produces is not suitable.

Can I intercept via JS, or override through CSS the tab ripple's color, in order to customize it?

**Comment by bonatoc** [comment]
Sorry, it's a matter of a simple override : 

    md-tabs.md-subnav_1-theme md-ink-bar{
    height: 4px;
    color: red;
    background: black;
    }

Feel free to delete the issue.

**Comment by Lasto13** [comment]
botanoc this didnt work for me ... browser didnt accept color property (alough it accepted others) so i had to go through document.getElementsByTagName('md-ink-bar')[0].style.color = '#f00';

**Comment by bonatoc** [comment]
@Lasto13 — Things may have changed, my comment was about pre-1.0.0 version.
Use Chrome Dev Tools, select the ink bar, and see what css is declared.
You should be able to overwrite it in your CSS file by targeting it precisely.

Furthermore, it's not the "color" property, it's "background" (or "background-color").
See this pen, which is a fork of the official AM tabs Codepen demo : http://codepen.io/bonatoc/pen/Qyvvzm

**Comment by murphy85** [comment]
I had struggle with this issue, too. I don't like the solution to overwrite the CSS. So there is a a much more convenient and more straight forward solution:

Just set the default HUE for your palette:

```
    $mdThemingProvider.theme('default')
                .primaryPalette('amber', { 'default': '600'})
                .accentPalette('indigo', { 'default': '400'});
```

The tab ink bar, the FAB speedial, ... will use this color from your palette.
