### ISSUE TITLE
md-autocomplete Problem

### ISSUE THREAD

**Issue by MauricioGuedes** [angular/material#4328]
When i set property md-input-id in directive <md-autocomplete>, does not work.
Inspecting Html file, id of componente is default "fl-input-5".

Other problem, my ng-messages, doest not work in component <md-autocomplete>, but in others, does work perfectly!

My Component Example: https://uploaddeimagens.com.br/imagens/error-jpg--52

**Comment by topherfangio** [comment]
I'm not seeing this issue in the latest master branch. Can you please provide a demo using [codepen.io](http://codepen.io) that shows the issue?

You can do this easily by visiting https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete and clicking on the "Edit on Codepen" button on the top right of the "Basic Usage" demo.

Thanks!

**Comment by robertmesserle** [comment]
Closing for now, will reopen if codepen is provided.
