### ISSUE TITLE
Virtual Repeat dragging issue

### ISSUE THREAD

**Issue by mrfaizanhaider** [angular/material#4330]
how to make drageable Virtual Repeat component.

please help

**Comment by ThomasBurleson** [comment]
@mrfaizanhaider - What do you mean ? Can you elaborate with more details please?

**Comment by mrfaizanhaider** [comment]
On
https://material.angularjs.org/latest/#/demo/material.components.virtualRepeat

for now we can just scroll here, ok?

But there is any soloution , can we make dragable the virtual list.

**Comment by kseamon** [comment]
With a mouse or for touch interfaces?

**Comment by mrfaizanhaider** [comment]
its already working with touch interfaces, just we need to make with mouse..

like this
https://www.google.com.pk/#q=hollywood+movies+list+2015

**Comment by mackelito** [comment]
This might be a long shoot but have you tried using the swipe service?

**Comment by EladBezalel** [comment]
[This](http://codepen.io/JTParrett/pen/rkofB) might help
