### ISSUE TITLE
HEAD revision on layout options, scroll is slower than last versions

### ISSUE THREAD

**Issue by danieltaborda** [angular/material#4332]
HEAD has a bug on scroll content "flex" layout options, scroll is slower than last versions

compare on scroll process:
Slow...
https://material.angularjs.org/HEAD/#/layout/options

nice scroll.
https://material.angularjs.org/0.10.0/#/layout/options

**Comment by stevenmiles** [comment]
It's not just HEAD that is slow, 0.10.1 is slow too. HEAD seems to be missing colours in the documentation as well as being slow.

Ok
https://material.angularjs.org/0.10.0/#/layout/options

Slow
https://material.angularjs.org/0.10.1/#/layout/options

Slow and missing flexbox colours
https://material.angularjs.org/HEAD/#/layout/options

**Comment by stevenmiles** [comment]
Looks like the issue with the flexbox colours were fixed in https://github.com/angular/material/commit/97a8f6d457038e1174fa93e110e80c3508969eaa
