### ISSUE TITLE
Datepicker has issues with resizing and repositioning with varying window sizes

### ISSUE THREAD

**Issue by amogh-talpallikar** [angular/material#4333]
First of all the it won't fit into small screen.
<img width="398" alt="screen shot 2015-08-26 at 3 46 53 pm" src="https://cloud.githubusercontent.com/assets/2959067/9491070/f9ab3f84-4c09-11e5-9699-18bcebb9a4ed.png">
Secondly, if you resize the window back, it stays where it is.
<img width="1236" alt="screen shot 2015-08-26 at 3 47 40 pm" src="https://cloud.githubusercontent.com/assets/2959067/9491095/29f0c47a-4c0a-11e5-98bf-e51a7fee1d2c.png">

**Comment by ngraef** [comment]
Related: #4271

**Comment by amogh-talpallikar** [comment]
@ThomasBurleson  Now that the issue has been pushed to 0.12.0,  Is Datepicker going to be released along with 0.11.0 with this issue as it is?

**Comment by ThomasBurleson** [comment]
We want to release v0.11.0 tomorrow... to allow more people to test the improvements and the new components. We will also be working aggressively to quickly improve the DatePicker.
