### ISSUE TITLE
md-menu closing on every click even with $event.stopPropagation() being called

### ISSUE THREAD

**Issue by ratscrew** [angular/material#4334]
A little background: I needed a month picker so I started with md-menu as seen in this code pen
http://codepen.io/anon/pen/MwBMvW?editors=101

The issue I ran into was the menu closing on every click, I wanted the menu to stay open when the year is changed.  

What would others think of adding an attribute along the lines of "md-menu-disable-close" to prevent a click from closing a menu? 

Changing line 286 in https://github.com/angular/material/blob/master/src/components/menu/js/menuServiceProvider.js would allow for this.

`` if (!target.hasAttribute('disabled') && !target.hasAttribute('md-menu-disable-close') &&(!closestMenu || closestMenu == opts.parent[0])) {
                close();
              }``

Interested to hear others thoughts or if someone else has another solution.

Thanks

**Comment by clshortfuse** [comment]
If you need a quick workaround, don't use ng-click and register an onclick event instead and wrap it in $scope.$apply. Right now, coincidentally, I'm battling with the same issue.

**Comment by ratscrew** [comment]
Thanks clshortfuse, I was able to implement the method you suggested but it required me to use a `setTimeout` to wait for the menu to be built.  Is there an event i could trigger this off of?  I feel as if this may end up being something lost of us hit, is there a case for not having an attribute that disables the close?

```
    $mdOpenMenu(ev);
    setTimeout(function () {
        $("#preYear").bind('click', function (e) {
            scope.$apply(function () {
                scope.year = scope.year - 1 ;
                scope.setSelectedMonth();
            });
            e.stopPropagation()
        });
        $("#nextYear").bind('click', function (e) {
            scope.$apply(function () {
                scope.year++;
                scope.setSelectedMonth();
            });
            e.stopPropagation()
        });
    },500);
```

**Comment by jlubin1** [comment]
+1

**Comment by clshortfuse** [comment]
@ratscrew here's what i did:

    $scope.openMenu = function ($mdOpenMenu, $event) {
        $mdOpenMenu($event);
        $timeout(function () {
            document.getElementById('clearAlerts').addEventListener('click', function () {
                $scope.$apply(function () {
                    sharedData.alerts = [];
                })
            })
            rebuildClearEvents();
        })
    };
    var rebuildClearEvents = function () {
        for (var i = 0; i < sharedData.alerts.length; i++) {
            var closeElement = document.getElementById('alert-clear-' + i);
            closeElement.parentNode.removeAttribute('ng-click'); //cheap hack
            closeElement.onclick = function (event) {
                var index = event.target.id.substring('alert-clear-i'.length);
                $scope.$apply(function () {
                    sharedData.alerts.splice(index, 1);
                });
            };
        }
    }
    $scope.$watch('sharedData.alerts', function (newValue, oldValue) {
        if (newValue === oldValue)
            return;
        rebuildClearEvents();
    });

It's similar to yours, but I used $timeout instead. I had another issue because I NEEDED ng-click to be created because I have a button within a button that gets triggered so I had to clear it.

Here's my html (in jade)

    md-menu(md-offset="0 48")
        md-button.md-icon-button(
        aria-label="Alerts"
        ng-controller='AlertsCtrl' ng-click="openMenu($mdOpenMenu, $event)")
            md-icon.md-accent(ng-if="sharedData.alerts.length !== 0" md-menu-origin) notifications
                md-tooltip Alerts
            md-icon(ng-if="sharedData.alerts.length === 0" md-menu-origin) notifications_none
                md-tooltip Alerts
        md-menu-content(width="4")
            md-list-item
                md-icon notifications_active
                p Desktop Notifications
                md-switch(ng-model="sharedData.settings.desktopNotifications")
            md-divider(ng-repeat-start="alert in sharedData.alerts")
            div(ng-repeat-end)
                md-list-item(ng-click="alert.open($event)" ng-attr-id="{{'alert-' + $index}}")
                    md-icon {{alert.icon}}
                    p {{alert.title}}
                    md-icon.md-secondary(aria-label='Clear' ng-click="" ng-attr-id="{{'alert-clear-' + $index}}") clear
            md-divider
            .md-actions(layout='row')
                span(flex)
                md-button.md-icon-button.md-48(aria-label="Clear All" id="clearAlerts")
                        md-icon clear_all
                            md-tooltip Clear All

And here's what it looks like: ![via imgur](http://imgur.com/TnT2J6J)

**Comment by clshortfuse** [comment]
@ratscrew 

New post because my old one wasn't using master:

http://codepen.io/anon/pen/LpPjBr

You need to intercept the click event on md-menu-content. From there you can handle if the event propagates. I actually replicated md-menu's capture logic. What's interesting is you can do this

    angular.element(target).triggerHandler('click');

and it'll call ng-click but not fire md-menu's click capture

**Comment by ratscrew** [comment]
Thanks @clshortfuse I like your workaround for now

**Comment by brianpkelley** [comment]
@clshortfuse 

Your solutions works great!  One minor issue though. Could you explain the purpose of
` && (!closestMenu || closestMenu == opts.parent[0])` equates to false 100% of time for my usage since it always returns an element as it is in a md-menu and `opts` is undefined.  I've removed this for my usage but just curious.

My structure is similar to md-menu -> md-menu-content -> div/directive -> div -> md-menu-item -> md-button.ng-click

**Comment by clshortfuse** [comment]
@brianpkelley your first element in md-menu-content must be a md-menu-item

So, just add this as your first element:

    <md-menu-item ng-show="false"><p></p></md-menu-item>

**Comment by zargold** [comment]
has anyone already made the `restrict: 'A'` directive which will work as in clshortfuse's ?:
```html
<md-menu-item md-menu-disable-close ng-click="wontBreak()"></md-menu-item>
```

**Comment by webpartisan** [comment]
@clshortfuse Your code is great, but every time you open menu, new click event added to menu items.

**Comment by trevorhreed** [comment]
The [`md-menu` component looks for clicks from elements that have one of these attributes](https://github.com/angular/material/blob/master/src/components/menu/js/menuServiceProvider.js#L294) `['ng-click', 'ng-href', 'ui-sref']`. So, you can work around this issue by creating your own version of `ng-click`, and using that for any click events inside `md-menu`, like so:

```js
app.directive('myClick', function ($parse, $rootScope) {
    return {
        restrict: 'A',
        compile: function ($element, attrs) {
            var fn = $parse(attrs.myClick, null, true);
            return function myClick(scope, element) {
                element.on('click', function (event) {
                    var callback = function () {
                        fn(scope, { $event: event });
                    };
                    scope.$apply(callback);
                })
            }
        }
    }
})
```

...and in your html...

```html
<md-menu>
    <md-button>Open Menu</md-button>
    <md-menu-content>
        <md-button my-click="doSomething()">Click me without closing the menu</button>
    </md-menu-content>
</md-menu>
```

It's not ideal, but it'll get you by for now.

**Comment by maximethebault** [comment]
+1

**Comment by mimani** [comment]
Hi,

So I had a use-case, where I needed md-date-picker in md-menu, but it closes when I click on datepicker. Any workaround for this?

Has the fix gone live with the current release - 1.0.4?

**Comment by trevorhreed** [comment]
That's an interesting edge case. The fix has gone live, but it won't work for `md-date-picker`, since you can't place the `md-prevent-menu-close` attribute on a button inside the `md-select` control.

**Comment by maximethebault** [comment]
I suggested a fix in a separate issue: https://github.com/angular/material/issues/6364

**Comment by ricardometring** [comment]
Solved this with the following: Assign onMouseDown event and add event.stopPropagation() to it.

**Comment by aj-r** [comment]
Solved this using `ngMouseup` instead of `ngClick`. No `stopPropagation()` required.

**Comment by kylekrzeski** [comment]
As an update, you can use the `md-prevent-menu-close` attribute:

`<md-button ng-click="clicked()" md-prevent-menu-close="md-prevent-menu-close"></md-button>`

[Documentation](https://material.angularjs.org/latest/api/directive/mdMenu)
