### ISSUE TITLE
Nesting dialog  

### ISSUE THREAD

**Issue by Vishnuraj910** [angular/material#4337]
How can i use md alert in a md custom popup?

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by ThomasBurleson** [comment]
Neither nestings nor stacking of dialogs will be supported until post 1.0
