### ISSUE TITLE
$mdDialog with inherited scope

### ISSUE THREAD

**Issue by bgoerdt** [angular/material#4338]
Is it possible to have a custom dialog with inherited scope instead of isolate scope? If not, can you explain the reasoning as to why this is not a feature?

**Comment by clshortfuse** [comment]
$mdDialog documentations says this for one of the options.

scope - {object=}: the scope to link the template / controller to. If none is specified, it will create a new isolate scope. This scope will be destroyed when the dialog is removed unless preserveScope is set to true

I use it for my projects and it seems fine.

**Comment by bgoerdt** [comment]
Sorry, I should have been more clear. If I am using the controllerAs syntax for the controller where I am creating the $mdDialog, do I have to inject $scope into my controller for the sole purpose of passing it on to the $mdDialog? Or is there a way have the dialog inherit the scope by default?

**Comment by clshortfuse** [comment]
I'm a little confused by what you're asking, but I'm going to show you how I have done it. Maybe it will help:

        function TestCtrl($scope, $http, $timeout, $q, $mdDialog) {
        console.log("TestCtrl started.");
        
    
        var windowOpenTime = new Date();
        $scope.openWindow = function (ev) {
            windowOpenTime = new Date();
            console.log('Open Window');
            return $mdDialog.show({
                controller: DialogController,
                scope: $scope,
                templateUrl: './testTemplate.html',
                targetEvent: ev,
                focusOnOpen: true,
                clickOutsideToClose: true,
                hasBackdrop: false,
                disableParentScroll: false,
                onComplete: function (scope, element, options) {
    
                }
    
            }).then(onFormComplete, function () {
                console.log('You cancelled the dialog.');
            });
        };
    
        function onFormComplete(response) {
    
        }
    
        function DialogController($scope, $mdDialog) {
            $scope.hide = function () {
                console.log('hide');
                $mdDialog.hide();
            };
            $scope.cancel = function ($event) {
                console.log('cancel');
                if ($event)
                    $event.preventDefault();
                $mdDialog.cancel();
            };
            $scope.ok = function ($event) {
                $mdDialog.hide('ok');
            };
        }
    
    }

Here my Controller is TestCtrl, and it has a function in $scope called openWindow. The DialogController is a simple controller that handles the ok/cancel events. The results are passed up to TestCtrl's $scope on onFormComplete. My testTemplate.html file has this as the first line:

    <html lang='en' ng-controller='TestCtrl'>

I call it open from another controller like this:

        var testCtrl = $scope.$new(true);
        $controller('TestCtrl', {
            $scope: testCtrl
        });
        testCtrl.openWindow($event);

Technically, I mash them all together in one scope, but I do this to keep my files organized.

**Comment by bgoerdt** [comment]
I am using the controllerAs syntax for the controller that is using the $mdDialog service, so I do not have $scope injected in my controller (FYI this is TypeScript). Here is an example:

    export class MyController {

        static $inject: string[] = ["$mdDialog"];

        constructor(private $mdDialog: ng.material.IDialogService) {
        }

        closeDialog(): void {
            this.$mdDialog().hide();
        }

        showDialog(): void {
            this.$mdDialog.show({
                template: `<md-dialog>
                            <md-dialog-content>
                                <my-directive></my-directive>
                            </md-dialog-content>
                            <div class="md-actions">
                                <md-button ng-click="myControllerVm.closeDialog()">
                                    Close
                                </md-button>
                            </div>
                        </md-dialog>`,
                clickOutsideToClose: true
                }
            });
        }
    }

with `controllerAs: "myControllerVm"` in the route. Essentially I just wanted to call the `closeDialog` function on my existing controller instead of having to create another controller, but this doesn't work because a new isolate scope is created for the dialog if a controller is not specified. I thought it would be nice to have the dialog inherit the calling controller's scope by default to allow for easier syntax, but I think I understand why that isn't easy. I think it is because the dialog is appended to the  root element and therefore won't inherit the scope because of it's place in the DOM.

Anyway, I just created an anonymous controller to get what I need, like this:

        showDialog(): void {
            this.$mdDialog.show({
                template: `<md-dialog>
                            <md-dialog-content>
                                <my-directive></my-directive>
                            </md-dialog-content>
                            <div class="md-actions">
                                <md-button ng-click="close()">
                                    Close
                                </md-button>
                            </div>
                        </md-dialog>`,
                clickOutsideToClose: true,
                controller($scope, $mdDialog: ng.material.IDialogService) {
                    $scope.close = () => {
                        $mdDialog.hide();
                    }
                }
            });
        }

**Comment by dryvenn** [comment]
Hi everybody !

I don't know if this is related to what OP was saying, but I might have encountered the same issue:

I wanted to open a dialog with:
```javascript
$mdDialog.show({
			...
			controller: 'FooCtrl',
			controllerAs: 'foo',
			scope: $scope,
			...
			)};
```
So that foo methods are accessible in the dialog html template, as in:
```html
<div ng-click="foo.bar()"></div>
```

But even though the dialog was open, `$scope.foo` wouldn't appear when printing the scope (`console.log($scope)`) and wasn't accessible from the template, unless `preserveScope` was on.

I believe this is an issue since `preserveScope` should matter only when the element is removed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (539/500 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:32773)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avscF-000L77-FB
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:51 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=nE46sGR9E3T3Zpitj7ajVxv6EB4=; b=oZlTfl19odRtutzr
	yG2A/WNwoEMc6qSmCai0vpvhRuvDcnMEproPakj0bjpSla/E+sNfDYG+3Lhnj83A
	1/yBJDB0+rnLzPP2bNA9fw0uMI0qQokrUdcivZh+ACFAuhlVRoRT80qJG/wxnwy6
	Bzp0jE1CQ7xbpnucHMD/LPB8oA8=
Received: by filter0621p1mdw1.sendgrid.net with SMTP id filter0621p1mdw1.24075.5722735730
        2016-04-28 20:32:23.331540709 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 99PV0CM3Qp2nf26vu3Lz_w
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:23.374 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:23 -0700
