### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by cesarvarela** [angular/material#4340]
Hi guys, I can't find anything specific about browser support. 

Can someone shed some light on this?

Looking at the css, I'm guessing it looks like this http://caniuse.com/#search=flex, but I want to be sure.

**Comment by topherfangio** [comment]
Our `README.md` on GitHub has that answer: https://github.com/angular/material#material-design-for-angularjs-apps-

Basically, we intend to support all browsers of version n-1 where n is the current version (so, all current, plus one previous).
