### ISSUE TITLE
tooltip location slightly off on first hover

### ISSUE THREAD

**Issue by cybrcodr** [angular/material#4345]
md-tooltip is slightly not centered when first hovered, but succeeding hover action does correct itself.

After app load, hover over to button with tooltip shows ...

![not-centered](https://cloud.githubusercontent.com/assets/1845151/9513084/05dc37c8-4c40-11e5-9a9c-8e566edd4851.png)

After hovering 2nd time and succeeding times, tooltip centered by itself ...

![centered](https://cloud.githubusercontent.com/assets/1845151/9513087/0b4c5eea-4c40-11e5-9a2b-84aaa6c9193c.png)

**Comment by gpopovic** [comment]
I have the same problem.

**Comment by pavankumarkatakam** [comment]
+1,, I'm using version 0.10.1

**Comment by topherfangio** [comment]
Can you please tell us what browser/version you are using and provide a http://codepen.io demo if possible? It really helps us track down these issues more quickly.

**Comment by akanimh** [comment]
+1 using Chome Version 44.0.2403.157 m

Does NOT occur in FF 40.0.2 however.

**Comment by topherfangio** [comment]
@all Can you please tell me what browser this is in?

**Comment by cybrcodr** [comment]
Following browsers on Mac OSX have the same behavior ...
Chrome 45.0.2454.85.
Firefox 40.0.2.
Safari 8.0.8.

I'm unable to easily come up with a simple demo at the moment.

**Comment by seewes** [comment]
Same problem, on OS X 10.10.3.
Chrome v46.0.2490.80
Firefox v41.0.2
Safari v8.0.6
Tested on Angular 1.0.0-rc2 on the demo page: https://material.angularjs.org/1.0.0-rc2/demo/tooltip

![tooltip](https://cloud.githubusercontent.com/assets/7928977/10899824/9e3e96b4-818d-11e5-8f36-96d918e6d159.gif)

**Comment by lelanophilus** [comment]
The problem occurs with tooltips attached to right aligned elements. What happens is that when the tooltip element is initially created its position is at the bottom of the body element which causes the scrollbar to appear reducing the width of the page and shifting the placement of the tooltip. Once the tooltip is placed the scrollbar disappears moving everything back except for the tooltip.

I'm working on a pull request.

**Comment by DevVersion** [comment]
I provide a working example reference.
-> https://material.angularjs.org/HEAD/demo/tooltip
The Link isn't working anymore

**Comment by gaurav5430** [comment]
i am using v1.0.7 and still facing the issue. 
the issue does not only happen for right-aligned or bottom-aligned element (causeing a scrollbar)
It happens for first hover , even if the element is placed in the center of page.

(I can see that this is closed, but not sure whether this fix is available yet)

**Comment by lelanophilus** [comment]
This change has been merged into the master branch but doesn't look like it has made its way into any of the releases. Not sure what the timeline is for that.

https://github.com/angular/material/blob/master/src/components/tooltip/tooltip.js#L281
