### ISSUE TITLE
md-sidenav (angular-material 0.10.1) transition doesn't work with angular 1.4.X

### ISSUE THREAD

**Issue by buzzo** [angular/material#4348]
WORKING version from demo site with angular 1.3.18 and angular-material 0.10.1
http://codepen.io/anon/pen/xwKgGx

NOT WORKING version with angular 1.4.4 and angular-material 0.10.1
http://codepen.io/anon/pen/epOgYX

Please reduce the size of the browser and check md-sidenav transition

**Comment by topherfangio** [comment]
This is a known bug that has a fix in the works. Please see #4152.

**Comment by buzzo** [comment]
Sorry, I tried to search any related issue before opening this one but could not find it.
Thanks!

**Comment by topherfangio** [comment]
@buzzo No worries; I tried to search too and couldn't find it. Difference between "transition" and "animation" :-)
