### ISSUE TITLE
md-dialog with backdrop doesn't use parent theme on creation

### ISSUE THREAD

**Issue by hnzlmnn** [angular/material#4350]
When using mdDialog with a custom template and a custom theme the backdrop fades from the background-color of the default theme to the wanted color in the custom theme.

For example when I set the default theme to be completely red and my custom theme to be completely blue then the backdrop gets the red background-color at creation and after the backdrop got the class `md-backdrop` it gets the custom theme.

This results in the transition changing the color from red to blue.
See: http://plnkr.co/edit/EBZ15k?p=preview

**Comment by naomiblack** [comment]
Custom themes and dark themes will be considered post-1.0.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
