### ISSUE TITLE
Ripple does not work with jQuery loaded

### ISSUE THREAD

**Issue by bwegrzyn** [angular/material#4352]
Latest master (e26a275) shows no ripple at all, and 0.10.1 shows ripple incorrectly positioned when jQuery is loaded.

This codepen demonstrates the problem with an md-button, but it affects other components as well.

http://codepen.io/bwegrzyn/pen/ojvWjV

**Comment by ThomasBurleson** [comment]
Ripple was rewritten after 0.10.0... with goals to improve ripple/browser performances.

**Comment by robertmesserle** [comment]
This is resolved in 0.11
