### ISSUE TITLE
Monkey patching Array or Object breaks $mdDialog open/close animation

### ISSUE THREAD

**Issue by jmcpeak** [angular/material#4355]
So I finally tracked down what was causing my open/close animations to not work.

Turns out if you monkey patch Array or Object anywhere in the controller or out it basically acts like targetEvent was not set. (If you patch String, it is fine though, weird.)

http://codepen.io/jmcpeak/pen/VvZWYj?editors=101

**Comment by dnadoba** [comment]
the problem is that the $mdUtil.supplant doesn't check with hasOwnProperty while it iteration over the values
https://github.com/angular/material/blob/5d03df8ea38ae8fdc245d7edcac7e3b5fcb3795c/src/core/util/util.js#L268

**Comment by ThomasBurleson** [comment]
Fixed with `hasOwnProperty( )`
