### ISSUE TITLE
Input height in Safari

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#4357]
This CodePen is a copy of the input demo, except a select is added to the same line as an input. The horizontal lines are not aligned in Safari (both desktop 8.0.7 and mobile 8.4). The issue does not occur in Chrome and Firefox.

http://codepen.io/anon/pen/JYPyav

<img width="635" alt="screen shot 2015-08-27 at 4 23 15 pm" src="https://cloud.githubusercontent.com/assets/9092817/9532176/f6851a04-4cd7-11e5-8b70-ae3bf9ea3a7f.png">

**Comment by topherfangio** [comment]
Need to dig in further, there is a definite discrepancy in height in IE. Initial thought is `line-height`, but that doesn't appear to be it.

Will definitely investigate.

**Comment by ivan7237d** [comment]
Might be related: regardless of browser, the text in text inputs and in selects has a slightly different baseline, e.g. the demo page https://material.angularjs.org/0.10.1/#/demo/material.components.select

<img width="478" alt="screen shot 2015-09-14 at 10 49 23 pm" src="https://cloud.githubusercontent.com/assets/9092817/9866712/d8d7e544-5b33-11e5-8bd0-9f9ae254ba8c.png">

**Comment by ivan7237d** [comment]
Related #3234

**Comment by topherfangio** [comment]
This may have already been fixed by some other recent changes to the inputs. Need to double-check and see if this is still valid.

If anyone on the thread has a chance to take a look and test against master/HEAD, that would be greatly appreciated.

**Comment by ivan7237d** [comment]
The issue from my sep 15 comment (probably would have been better to open a separate issue for it) is still there (https://material.angularjs.org/HEAD/demo/select), will take a look at the main one a bit later.

**Comment by ivan7237d** [comment]
Just checked Safari Desktop 9.0.1 and mobile 9.0, the original issue is gone, so I'll close this. The issue from sep 15 comment above still remains, I'll file it as a new issue.
