### ISSUE TITLE
toggle md-autocomplete drop-down template

### ISSUE THREAD

**Issue by zzo** [angular/material#4358]
I would like to hide the drop-down template md-autocomplete uses.  
For my case specifically I want to hide it when a user hits <Enter>.
Suggestions on how to accomplish this are on stackoverflow [here](http://stackoverflow.com/questions/31858787/angular-material-md-autocomplete-how-to-hide-md-autocomplete-suggestions-on-e) but that looks very hacky and is messing with private variable.
Ideally the md-autocomplete directive would supply a way to easily hide/toggle this panel.
thanks!

**Comment by spoco2** [comment]
I think this sounds like what I'm looking for as well. Although I'd like it to hide the results any time there are none. I'm not using auto complete as a way of populating a select box, but rather presenting past searches, and I'd like it to just not show the drop down if what has been typed doesn't match anything.

A directive flag to not show anything if no results would be fantastic. (At the moment it'll either show the md-not-found contents, or an empty list if there's nothing within that tag)

**Comment by ThomasBurleson** [comment]
@zzo - what do you mean "hide the drop-down template" ?

**Comment by zzo** [comment]
I would like to toggle the visibility of the panel with the possible
completions.
Example in a single page app with an md autocomplete search box once the
user types a search and presses 'return' or clicks 'search' without having
selected one of the options I now need to hide the autocomplete panel.
Thanks!

**Comment by topherfangio** [comment]
@ThomasBurleson I believe this is actually a bug. The "no results found" template is currently being displayed even if it is not provided, so it always appears, but will be empty/blank without the template.

**Comment by topherfangio** [comment]
As of PR #4958, the behavior has changed slightly.

@spoco2 The list no longer appears if you do not provide the `md-not-found` template (or if you provide an empty one). Can you retest against master and see if it works as expected?

@zzo I think your use-case is slightly different, but supposing `.` returns no search results, and you do not provide the `md-not-found` template, I think it now supports this. Can you give it a try on master as well and see if it works as expected? The [Custom Template Demo](https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete) should work like this already.

**Comment by spoco2** [comment]
@topherfangio Seems to work, yes :D Excellent.. looks like things are a little different in the way things fit into the page, but that's cool.

Thank you. I look forward to it appearing in the next bower version :)

**Comment by topherfangio** [comment]
@spoco2 Thanks for the update!

@zzo Any chance you have been able to look at my post above and test out the new functionality?

**Comment by zzo** [comment]
what version did this get in to?

**Comment by topherfangio** [comment]
Should be in 11.3 and 11.4

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
