### ISSUE TITLE
Internet Explorer 11 CPU usage high when using Angular Material Design Tabs control

### ISSUE THREAD

**Issue by mostwired** [angular/material#4364]
I have a material design page (simple, no code attached, has a menu bar and tabs, no other controls. When viewed in Chrome, all is peachy; in IE11 CPU stays at about 10-15% constant. When IE is minimized, CPU drops to 7-9%, but still sustained constantly. 

I narrowed it down to the tabs control - even when empty (no content) it still makes CPU surge. Adding  md-no-ink tag to the tab control and the individual tabs does nothing to remedy high CPU usage. I suspect maybe some animation loops are running?

**Comment by stevenmiles** [comment]
@mostwired What exactly was your set up for the tabs and which version of angular material was used? I've monitored IE11 CPU in a codepen from the dynamic hight sample in the documentation, I can see a 4-7% CPU usage for a short time, then it drops to 0. It increases again when changing tabs, but then drops again. I tested this with 0.10.1 and HEAD.

When testing, I did notice that IE11 was using CPU for longer than the animation took to complete. I know there are still some digest issues with tabs that are triggered by initialisation and tab switching. The last digest seems to happen a short time after animation has completed. See https://github.com/angular/material/issues/3299. There was an issue with older versions of angular material where tabs would digest infinitely, causing constant CPU usage.

**Comment by ThomasBurleson** [comment]
@mostwired  - Within the last two (2) weeks, we have significantly improved Layout within Angular Material. The biggest impact is IE performance using Attribute Selectors. We changed the generation and  CSS to use Class Selectors: see [Layout.js](https://github.com/angular/material/blob/master/src/core/services/layout/layout.js).

This is available in master and will be available in 0.11 (scheduled for release today).

> If you continue to see performance issues after retesting with v0.11, then I will re-open this issue. Please submit a CodePen if you wish this issue re-opened.
