### ISSUE TITLE
Impossible to select a portion of input with ligatures icons

### ISSUE THREAD

**Issue by Grmiade** [angular/material#4369]
![filter bug](https://cloud.githubusercontent.com/assets/11244106/9561663/b3f16fa2-4e4f-11e5-9860-7e4564b907ce.gif)

As you can see, it is impossible to select a portion of the input with ligatures icons. As if the ligature was not replaced with its image, we click on the text "search".

```
<md-input-container md-no-float style="padding-bottom: 0;">
      <md-icon>search</md-icon>
      <input ng-model="filterAccount.full_name" placeholder="Filtre" autocomplete="off">
</md-input-container>
```

To resolve this. I have added `z-index:99;` style on input.

```
<md-input-container md-no-float style="padding-bottom: 0;">
      <md-icon>search</md-icon>
      <input style="z-index: 99;" ng-model="filterAccount.full_name" placeholder="Filtre" autocomplete="off">
</md-input-container>
```

**Comment by topherfangio** [comment]
I am having a bit of trouble coming up with a demo based off of your code above. Would you be able to provide a [Codepen](http://codepen.io) which shows the issue?

**Comment by Grmiade** [comment]
Trying to reproduce the problem on Codepen, I found that it was not due to angular material but material design icons. Sorry for that.
