### ISSUE TITLE
md-slider rendering issue in the case of dynamic min/max

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#4371]
The following CodePen illustrates (when value < min, thumb ends up outside the ruler): http://codepen.io/anon/pen/NGKVPN

**Comment by karolkochan** [comment]
+1

**Comment by PeWu** [comment]
A workaround is using $timeout to set the value in a separate digest cycle.
In the above CodePen, replace `$scope.value = 10;` with
`$timeout(function() { $scope.value = 10;  });`
