### ISSUE TITLE
Fab-Speed-Dial doesn't close on mobile

### ISSUE THREAD

**Issue by psaul3** [angular/material#4373]
Can't close Fab-Speed-Dial button on mobile. Re-clicking it doesn't deactivate the actions from hiding again. Clicking outside of the immediate area also does not hide the actions again.

I assume that because the tablet (touch-enabled device) has no mouse events, that clicking on the fab-speed-dial is required to trigger the animation, but what about hiding the actions?

**Comment by topherfangio** [comment]
Can you please tell us what version of material you are using and what mobile device you are testing on?

We recently updated the speed dial with some new code and it specifically checks for touchstart/touchend in addition to the mouseup/mousedown events, so it should be working on mobile.

**Comment by psaul3** [comment]
I was testing in safari on iPad and iPhone. Material version 0.10.1

**Comment by topherfangio** [comment]
Can you possibly test against the master branch? Many updates were made to the speed dial and I know we fixed many issues with mobile.

**Comment by topherfangio** [comment]
@psaul3 Have you had a chance to test against the latest master code? Many updates were made since 0.10.1 to this component.

**Comment by psaul3** [comment]
Yes it does, thank you.
