### ISSUE TITLE
$mdDialog controller doesnt work with controllerAs (vm) only $scope

### ISSUE THREAD

**Issue by kheide** [angular/material#4374]
Hi, 

The controller you instantiate to use with a $mdDialog doesnt seem to work with using vm = this. Only with $scope. Is this because there are no place to set controllerAs on the $mdDialog ? Is it a bug? Or is it working as intended?

**Comment by ThomasBurleson** [comment]
Our [Dialog demo](https://material.angularjs.org/HEAD/#/demo/material.components.dialog) uses:

```js
$scope.showAdvanced = function(ev) {
    $mdDialog.show({
      controller: DialogController,
      templateUrl: 'dialog1.tmpl.html',
      parent: angular.element(document.body),
      targetEvent: ev,
      clickOutsideToClose:true
    })
    .then(function(answer) {
      $scope.status = 'You said the information was "' + answer + '".';
    }, function() {
      $scope.status = 'You cancelled the dialog.';
    });
  };
```

You should be able to add `controllerAs: 'vm',`  and then update your template to use `vm.` prefixes.

**Comment by kheide** [comment]
Yes. That did the trick. Thanks. I should have tried it before posting. Sorry for wasting your time!

**Comment by ThomasBurleson** [comment]
@kheide - No worries. Thanks for being part of the Angular Material community.
