### ISSUE TITLE
Placeholder in md-input-container > input renders as label and placeholder

### ISSUE THREAD

**Issue by ed4becky** [angular/material#4376]
Using the angular-material v0.10.1, In the following code:

                <md-input-container>
                    <input class='authCode' type="text"
                           placeholder='{{lbl.dbEnterAuth}}'
                           ng-model="vm.dropboxAuthCode"
                           ng-blur='captureAuthCode();'/>
                </md-input-container>

The placeholder renders as a label AND a placeholder.  If I replace placeholder='{{lbl.dbEnterAuth}}' with placeholder='Some placeholder text' it renders as expected.

A workaround is to add an empty <label></label> to the md-input cpontainer.  It results in a console error,  "the placeholder will be ignored since this md-input-container has a child label element", but it renders properly (the placeholder is NOT ignored).

**Comment by topherfangio** [comment]
This is the default/designed behavior of the `md-input-container`. Please see the [docs](https://material.angularjs.org/HEAD/#/api/material.components.input/directive/mdInputContainer) and the `md-no-float` property if you wish to disable this.

Please reopen this issue if it doesn't work as stated in the docs.

**Comment by ed4becky** [comment]
The docs say nothing about a difference in behavior when you use placeholder="{{lbl.dbEnterAuth}}" versus placeholder="my placeholder text".  It also doesn't indicate that sometimes you need to use md-no-float for placeholder and sometimes you do not, which is the behavior I see.

**Comment by topherfangio** [comment]
@ed4becky There should not be a difference in using the placeholder with plain text or with a bound expression, thus why there is no mention in the docs. Also, I was unable to reproduce your issue in the latest master code. The only reason to use `md-no-float` is if you want it to render only as a placeholder (i.e. no label).

I have re-opened the issue. Can you provide a [Codepen](http://codepen.io) built against the latest master branch which demonstrates the error?

**Comment by topherfangio** [comment]
@ed4becky Any chance you can provide a Codepen for this so that we can investigate further, or is it working for you now?

Thanks!

**Comment by topherfangio** [comment]
Since we have not heard back from you, we are closing. Please comment and provide a Codepen and we will reopen.
