### ISSUE TITLE
Toolbar: transparent styling

### ISSUE THREAD

**Issue by manmon42** [angular/material#4379]
I want to have the toolbar at the top of my page be transparent. I've tried adding
```css
.transparent{
  background-color: transparent;
}
```
with this HTML
```html
<div layout="column" layout-fill>
      <md-toolbar>
          <div class="md-toolbar-tools transparent">
              <span>Drake Developers Club</span>
              <!-- fill up the space between left and right area -->
              <span flex></span>
              <md-button>
                  Right Bar Button
              </md-button>
          </div>
      </md-toolbar>
      <md-content>
          <ng-view></ng-view>
      </md-content>
  </div>
```
But it seemed to do nothing. Any suggestions would be nice.

**Comment by Thiago-Medeiros** [comment]
...
<md-toolbar class="transparent">
          <div class="md-toolbar-tools">
...

**Comment by Thiago-Medeiros** [comment]
...
`<md-toolbar class="transparent">`
      `<div class="md-toolbar-tools">`
...

**Comment by super-coder** [comment]
@Thiago-Medeiros just to mention that your solution doesn't seem to work
would be nice to have a transparent option

**Comment by gimox** [comment]
this is not the best solution but you can force the css and it work.
```css
.transparent{
  background-color: transparent !important;
}
```

**Comment by domface** [comment]
+1

**Comment by Ouwen** [comment]
This seems to work as well if you don't want to use important

.transparent-background {
  background-color: rgba(0, 0, 0, 0);
}
