### ISSUE TITLE
md-fab-toolbar md-open does not listen to default scope value

### ISSUE THREAD

**Issue by nikkwong** [angular/material#4382]
It seems that although the value of md-open is set to a true value upon being loaded, ```md-fab-toolbar``` remains closed.

http://plnkr.co/edit/10c6V6BpVB3Uh1IW7L6x?p=preview

**Comment by topherfangio** [comment]
This is fixed in master and will be available when 0.11 launches, which should be very soon.

Here is an example using the latest master branch: http://codepen.io/topherfangio/pen/RWwGJe
