### ISSUE TITLE
md-input type=date in Microsoft Edge

### ISSUE THREAD

**Issue by jb29** [angular/material#4386]
When using `md-input type=date` in Microsoft's **Edge Browser**, the placeholder of the native datepicker and the Material Design floating label are displayed at the same time in unfocused state.

![2015-08-31_16h39_57](https://cloud.githubusercontent.com/assets/13062631/9581684/24af6c00-5001-11e5-8aa7-1cc32ac291f6.png)

Tested with `angular-material#master` (pre-0.11.0)

**Comment by ThomasBurleson** [comment]
Use the mdDatePicker component
