### ISSUE TITLE
md-subheader has inappropriate right margin

### ISSUE THREAD

**Issue by scottrodoty** [angular/material#4389]
The md-subheader directive puts an inappropriate 16px right margin in the style.  This is inconsistent with the styling given by the md-divider directive that can be used to separate line items in the list.

Look here for an example: http://codepen.io/scottrodoty/pen/ZbEpGY

In the example, I assigned md-hue-1 to the subheader to make the issue more visible.  It is probably valuable to use a 16px right padding instead.

**Comment by topherfangio** [comment]
We made some recent changes to the subheader and I thought I removed this, but it looks like it is still there. We will investigate; I think it is leftover from some older code which required it for positioning.

**Comment by EladBezalel** [comment]
dup #708
