### ISSUE TITLE
mdChips: Contact Chips autocomplete dropdown is empty.

### ISSUE THREAD

**Issue by topherfangio** [angular/material#4390]
On master branch, on the Contact Chips demo, when you type in some content to search for a user, the autocomplete pops up with suggestions and filters properly, however all of the suggestions are empty.

<img width="886" alt="screen shot 2015-08-31 at 11 15 51 am" src="https://cloud.githubusercontent.com/assets/54370/9583569/cc3fc9ae-4fd1-11e5-80b8-e54759bde53a.png">

**Comment by Frank3K** [comment]
+1
