### ISSUE TITLE
Q: md-toolbar, how to mix generic buttons (menu toggle, back button) with form specific buttons

### ISSUE THREAD

**Issue by beebase** [angular/material#4393]
I'd like to build a top nav bar that displays generic buttons like menu toggle, back button 
together with form specific buttons like create, edit, filter etc.
Ionic has a very convenient directive for this
http://ionicframework.com/docs/api/directive/ionNavButtons/

Are there any plans going in this direction?
Or perhaps alternative ways to accomplish this?

Thanks for any directions.

**Comment by topherfangio** [comment]
I am not sure yet if there is an existing way to accomplish this. I will look into it.

For my own future reference: here is a codepen showing an Ionic implementation: http://codepen.io/calendee/pen/ubzDq
