### ISSUE TITLE
CSS; height as inherit leads to layout issues (Chrome / IE11)

### ISSUE THREAD

**Issue by Londovir** [angular/material#4397]
Ever since the recent commit of code a few days ago that caused `height : inherit` to be bound to the `.layout` class, I've been struggling with layout issues. For instance, the following simple layout causes unnecessary scrolling in Chrome and IE11:

```html
<body>
    <md-toolbar>
    </md-toolbar>
    <div layout="row">
    </div>
</body>
```

See this CodePen: [Example](http://codepen.io/londovir/pen/bdqVZw)

If I use F12 tools, and disable the `height : inherit`, all returns to normal as expected.

I'm not sure if this is as expected/designed and I'm just not designing properly, or if this is an unintended consequence. For instance, I understand in the example above that the `div` will inherit the height of the `body`, which the MD CSS gives a 100% height and min-height. So, in this case, this causes an unnecessary scrolling since the height of the `md-toolbar` is not being subtracted from the page height, and the `div` therefore runs longer than the viewport by that much. I can use more involved flex layouts and designs to account for this, but that leads to other issues.

One such issue is when I use `md-icon`. I've seen cases where an `md-icon` that is nested into some combinations of `layout="row"` or `layout="column"` loses the height of 24px set in the MD CSS because the `.layout` inherit style overrides it.

**Comment by robertbaker** [comment]
+1 broke my layouts.

**Comment by icchio** [comment]
+1

**Comment by topherfangio** [comment]
@Londovir If you add `layout="column"` to the `<body>` tag, it should work as expected. Can you create a codepen of the icon issue so that we can take a look?

@robertbaker @icchio Can you guys add some demos of your specific cases so that we can see the best way to fix it?

The `height: inherit` was added because a lot of other people were having issues getting the layouts to work properly, so I would love to find a solution that makes everyone happy rather than reverting the change.

**Comment by topherfangio** [comment]
@Londovir The main issue we were attempting to solve is #4022. In this case, devs were having the opposite problem in that they had to add height hacks to every ancestor of a nested component to get the column layout working properly.

If you change it from `.layout: inherit` to `.layout-column: inherit`, does that help fix your layouts? I don't think we actually need it for the row layouts, so it may make some changes.

**Comment by topherfangio** [comment]
Just talked with the team, we are trying to push 0.11 out this morning, so we're going to go ahead and revert this change since it is causing more issues than expected and we will reach out to users to try to find a better fix. Revert should be pushed momentarily.

**Comment by Londovir** [comment]
Understood & appreciated. FWIW, it seems like the `.layout-column: inherit` change does appear to help clean up some/most of the situation on my end. I still need to revisit a number of pages in my projects before I signal complete victory at the moment. Thanks!
