### ISSUE TITLE
md-dialog force body to show scrollbar when it is not necessary

### ISSUE THREAD

**Issue by simongcc** [angular/material#4401]
Version: 0.10.1

When default md-dialog is called, say

```
$mdDialog.show(
    $mdDialog.alert()
     .parent(angular.element(document.body))
     .title('Alert')
     .content('There is no such thing.')
     .ok('OK')
);
```
The HTML tag is forced to show scrollbar, the similar problem solved before in md-select, it is now appearing in md-dialog.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by simongcc** [comment]
Understood, let me tore the parts from my working project later. I will examine again and getting you back. Many thanks.

**Comment by EladBezalel** [comment]
@simongcc still happening on HEAD?

**Comment by EladBezalel** [comment]
Closed due to inactivity
