### ISSUE TITLE
md-select inside md-dialog doesn't close if we click outside md-dialog

### ISSUE THREAD

**Issue by sergey-trotsyuk** [angular/material#4402]
I didn't find answer for this:

> Steps to reproduce:
> - Place md-select inside a md-dialog
> - Open dialog
> - Open select
> - Click somewhere outside the dialog to have it removed
> - Observe select is still open in the middle of the screen

https://github.com/angular/material/issues/276#issuecomment-75326098

@ajoslin , could you help with this?

**Comment by satheesh786** [comment]
can you please provide codepen or plunker ?

**Comment by kschwidder** [comment]
look at #4387
I have the same error and I provided a codepen

**Comment by kschwidder** [comment]
Sorry of that. This is another mis behavior which I did not recognize at all.

**Comment by satheesh786** [comment]
This is my pen am working on same field .Once you remove ng-value and write only value

http://codepen.io/anon/pen/WQNLyV?editors=100

**Comment by satheesh786** [comment]
Your pen

http://codepen.io/anon/pen/xwxmaL?editors=100

**Comment by kschwidder** [comment]
Thx for your feedback BUT this does not work. In my code I have change-listener which needs the designated value. If I apply only value than the changeListener is not called !

**Comment by rschmukler** [comment]
Per [this codepen](http://codepen.io/rschmukler/pen/qObQoy?editors=101) the first click will close the select, the second one will close the dialog. Closing. If the issue persists, please submit a new issue with a codepen example
