### ISSUE TITLE
Select: Back action with dropdown open

### ISSUE THREAD

**Issue by liviupogar** [angular/material#4405]
While a dropdown is opened, clicking the `BACK` button in the browser will cause the refreshed page to freeze. Nothing is clickable until a refresh of the page.

> It appears that the md-backdrop is not properly removed during $location change events.

![screen shot 2015-09-01 at 8 59 53 am](https://cloud.githubusercontent.com/assets/210413/9606188/92e56900-5087-11e5-81f1-44fcb2f308d1.png)

![screen shot 2015-09-01 at 9 00 10 am](https://cloud.githubusercontent.com/assets/210413/9606191/97545cd0-5087-11e5-8508-5aa0491556be.png)

**Comment by donedgardo** [comment]
Hi @ThomasBurleson maybe this is relevant #3741
