### ISSUE TITLE
md-tooltip : tooltip is positioned off screen when text is long and button is at the edge of the screen

### ISSUE THREAD

**Issue by TalPasi** [angular/material#4411]
When a tooltip is assigned to a md-button, and the text is longer than the width of the button, the tooltip is positioned off screen

![image](https://cloud.githubusercontent.com/assets/1816536/9608199/37a064fa-509b-11e5-8685-974be3b8ed50.png)

Please see the code pen http://codepen.io/anon/pen/WQNzKK to reproduce this issue

**Comment by topherfangio** [comment]
Duplicate of #2037.

**Comment by SanderElias** [comment]
Closing in favor of #2037. Focus discussion in there please.
