### ISSUE TITLE
chips with mdOnAppend and autocomplete yields append function two times on enter

### ISSUE THREAD

**Issue by mxab** [angular/material#4412]
Hi,

if I use the chips component with mdOnAppend and the autocomplete.
When start typing and then hit enter, the mdOnAppend gets called two times, once with the string value and once with the selected chip.

See this example
http://codepen.io/mxab/pen/PPoRVQ?editors=101

**Comment by langdonx** [comment]
Fix here (event.defaultPrevented): https://github.com/angular/material/issues/4404#issuecomment-136761502

You can get around the issue now using `md-require-match="true"` on `md-chips` (which is probably desirable for your example).

**Comment by mxab** [comment]
thanks, 
the thing is ```md-require-match="true"``` works if I don't want to use the "unkown" string chips

**Comment by swist** [comment]
I have run into the same issue. My spec is:

- when enters the text into the autocomplete field, it should show the list of autocomplete suggestions
- when the user highlights a suggestion and presses enter it should append the highlighted suggestion to the chips (pass the object representation of the chip to mdOnAppend handler)
- when the user presses enter without highlighting an option in the autocomplete dropdown it should pass the string representation of the chip from the autocomplete input field to mdOnAppend handler

Currently the handler first gets called with the string and then the selection. It works fine if there are no suggestions available. I have tried replicating the issue in the test suite with the above specification, but no luck - I am not yet familiar enough with the internal API

**Comment by abutcher-gh** [comment]
The following fixes it for me.  The select event does clear the chipBuffer, but the chip has already been added by the input ENTER key handler.  The patch defers the ENTER key append to the next cycle (by which time the autocomplete select event has added the correct chip and cleared the buffer).  Any ENTER press without an autocomplete item selected (i.e. autoselect false or no matches) inserts the manually entered object as expected.

Note that I'm using the bower-material distribution so this diff is against a concatenated angular-material source (against master c7f2d64).  It should apply trivially to `src/components/chips/js/chipsController.js` though.

```diff
--- client/bower_components/angular-material/angular-material.js  2015-09-15 10:45:10.919402421 +0100
+++ client/bower_components/angular-material/angular-material.js  2015-09-15 10:46:58.722735110 +0100
@@ -17487,12 +17487,11 @@
  * @param $mdConstant
  * @param $log
  * @param $element
+ * @param $timeout
+ * @param $mdUtil
  * @constructor
  */
-function MdChipsCtrl ($scope, $mdConstant, $log, $element, $timeout) {
-  /** @type {$timeout} **/
-  this.$timeout = $timeout;
-
+function MdChipsCtrl ($scope, $mdConstant, $log, $element, $timeout, $mdUtil) {
   /** @type {Object} */
   this.$mdConstant = $mdConstant;

@@ -17508,6 +17507,12 @@
   /** @type {$element} */
   this.$element = $element;

+  /** @type {$timeout} **/
+  this.$timeout = $timeout;
+
+  /** @type {$mdUtil} **/
+  this.$mdUtil = $mdUtil;
+
   /** @type {angular.NgModelController} */
   this.ngModelCtrl = null;

@@ -17559,7 +17564,7 @@
    */
   this.useOnSelect = false;
 }
-MdChipsCtrl.$inject = ["$scope", "$mdConstant", "$log", "$element", "$timeout"];
+MdChipsCtrl.$inject = ["$scope", "$mdConstant", "$log", "$element", "$timeout", "$mdUtil"];

 /**
  * Handles the keydown event on the input element: <enter> appends the
@@ -17574,8 +17579,14 @@
     case this.$mdConstant.KEY_CODE.ENTER:
       if ((this.hasAutocomplete && this.requireMatch) || !chipBuffer) break;
       event.preventDefault();
-      this.appendChip(chipBuffer);
-      this.resetChipBuffer();
+      var self = this;
+      this.$mdUtil.nextTick(function() {
+        var chipBuffer = self.getChipBuffer();
+        if (chipBuffer) {
+          self.appendChip(chipBuffer);
+          self.resetChipBuffer();
+        }
+      });
       break;
     case this.$mdConstant.KEY_CODE.BACKSPACE:
       if (chipBuffer) break;
```

**Comment by langdonx** [comment]
@abutcher-gh surely making use of `defaultPrevented` is more direct approach at resolving the issue, no?

**Comment by abutcher-gh** [comment]
@langdonx, absolutely. That'll teach me for not reading the whole thread (and for not looking up the bug here first before attempting a fix for it).  I read the most recent post when I found this which seemed to state that the issue was still occurring.  Having applied your *much cleaner* fix, all seems to be working fine here.  Though I must confess I was a bit puzzled by it initially; from diagnostics it appeared that the MdChipsCtrl.inputKeydown was getting called prior to the autocomplete select event firing so my assumption was that nothing could be done other than defer the chip addition here.  I guess the default is prevented in the keydown handler for the autocompleter prior to it triggering its selection event, hence allowing it to be short circuited here with defaultPrevented.

**Comment by swist** [comment]
@langdonx many thanks for the fix. In my case, the event passed into the handler was a jQuery event, so had to make a small change:

```
if (event.isDefaultPrevented() || event.defaultPrevented || (this.hasAutocomplete && this.requireMatch) || !chipBuffer) break;
```

**Comment by mschering** [comment]
I'm still struggling with this. I have the same use case as @swist has written here above. I don't want md-require-match=true as I want the user to be able to create new chips but it always adds the match + the string value.

**Comment by jherman** [comment]
Hopefully this gets fixed in the future.  One of the dev's see's the issue now on this case #3475 

My temporary workaround, add:
```
 if (angular.element(document.querySelectorAll("md-virtual-repeat-container:not(.ng-hide) li[md-virtual-repeat].selected")).length) return;
```
To:
```
MdChipsCtrl.prototype.appendChip = function (newChip) {
  if (angular.element(document.querySelectorAll("md-virtual-repeat-container:not(.ng-hide) li[md-virtual-repeat].selected")).length) return;
  if (this.useOnAppend && this.onAppend) {
    newChip = this.onAppend({'$chip': newChip});
  }
  if (this.items.indexOf(newChip) + 1) return;
  this.items.push(newChip);
};
```

**Comment by topherfangio** [comment]
@swist @mschering @jherman - If you have a moment to test out PR #5497, I would love to get some feedback as to whether or not this meets your needs.
