### ISSUE TITLE
mdToolbar: inserted div breaks layout and functionality

### ISSUE THREAD

**Issue by Frank3K** [angular/material#4414]
After commit 9b861fdb7d9de924e6549f4e2b2bf07004462295 the `md-toolbar` creates an extra child `div`. This extra child `div` creates problems when one has specified (for example) `layout` or `layout-align` attributes on the `md-toolbar` element since these styles now apply to different elements.

Furthermore, @daniel-nagy has left a [comment](https://github.com/angular/material/commit/9b861fdb7d9de924e6549f4e2b2bf07004462295#commitcomment-13003688) on the original commit explaining problems with `ng-include` and `ng-contoller`.

**Comment by topherfangio** [comment]
This was fixed by #4423 in commit a09b9ab. I transposed the numbers in my commit message.
