### ISSUE TITLE
md-virtual-repeat can not handle data set change on `md-on-demand` mode.

### ISSUE THREAD

**Issue by cnjsstong** [angular/material#4417]
In 0.11.0-rc1, the new "on demand" mode works great for non-changing dynamic loading. 

However, if something makes the original data set to change, like a filter applied, there is currently no way to notify the directive that the data has changed and it should refresh the whole list. 

Is an Android style `notifyDataSetChanged()` possible?

**Comment by robertbaker** [comment]
+1

**Comment by digital-synapse** [comment]
I've had some results by rebuilding the page array after filters have changed. in most cases this seems to update the list.

**Comment by Janpot** [comment]
In my case there's a dataset that gets items prepended at a relatively fast pace. In my case a 'pagination' with a linked-list-like behavior rather than index makes more sense. Maybe there could be some alternative virtual-repeat model that looks like:

```js
{
  getItem(id),
  getItemAfter(id),
  getItemBefore(id)
}
```

**Comment by TwDrake** [comment]
+1

**Comment by kseamon** [comment]
Mirroring the comment by @digital-synapse, I verified that you can trigger an update by replacing the model reference. I also tested that changing the values returned from getItemAtIndex also results in appropriate updates to the displayed data.

Can you provide a test case of what isn't working? Thanks.

**Comment by kiro64** [comment]
+1

**Comment by HipsterZipster** [comment]
+1
