### ISSUE TITLE
md-menu-bar not displaying correctly

### ISSUE THREAD

**Issue by RolandHeath** [angular/material#4424]
Using Fedora 22, Google Chrome Version 44.0.2403.155 (64-bit)
This appeared to be both in master and 0.11.0-rc1, and might only be an issue in the docs
![image](https://cloud.githubusercontent.com/assets/329209/9620010/6ac53e82-5159-11e5-8aca-c413cbc076a8.png)

**Comment by RolandHeath** [comment]
This appears to be fixed in master. 
Well done!

**Comment by Soulcyber** [comment]
Yes, in master is now working correctly :+1:

**Comment by topherfangio** [comment]
Closed in sha ae1a2fad67bed32242b11fe8becf75ae1cff5266.
