### ISSUE TITLE
Impossible to disable scroll shrink on toolbar

### ISSUE THREAD

**Issue by bwegrzyn** [angular/material#4425]
As of commit 9b861fd, it is now impossible to disable scroll shrink on toolbars.

I've tried no md-scroll-shrink attribute, and md-scroll-shrink="false", but I can't find a way to disable scroll shrink.

The md-content demo for HEAD exhibits this issue. It has no md-scroll-shrink attribute, but still shrinks.

https://material.angularjs.org/HEAD/#/demo/material.components.content

**Comment by paulflo150** [comment]
I noticed this as well today, and until it gets fixed I just added the attribute check back in <code>function mdToolbarDirective</code>:
<code>
if (angular.isDefined(attr.mdScrollShrink)) {
    setupScrollShrink();
}
</code>

A couple of other things I noticed:
- scope.$watch was replaced by attr.$observe which will no longer evaluate to a boolean, unless I missed the $eval.
- <code>if ( shrinkWithScroll )  disableScrollShrink = enableScrollShrink();</code> may need to read
<code>if ( !shrinkWithScroll )  disableScrollShrink();</code>

**Comment by topherfangio** [comment]
I noticed this as well and already submitted a PR yesterday morning, it was merged in 391479b044cd9dc392b2654ed3151597c876b1a9 and should be fixed in master.

Can you double-check against the latest master code?

**Comment by paulflo150** [comment]
Looks good to me, nice work :thumbsup:

**Comment by topherfangio** [comment]
Awesome, thanks for the feedback!
