### ISSUE TITLE
md-content doesn't scroll inside ng-view

### ISSUE THREAD

**Issue by damccull** [angular/material#4426]
When nesting content as follows:
```html
<div layout="row">
  <ng-view flex></ngview>
</div>
```

Then using ng-route to insert templates into ng-view that contain:
```html
<md-toolbar>...</md-toolbar>
<md-content flex>...</md-content>
```

The md-content element does not scroll, but instead expands to fit its contents. I would like it to lock to the remaining height of the window (after toolbar space is taken up) and then scroll within its area.

**Comment by paulflo150** [comment]
Is this what you are looking for: http://codepen.io/anon/pen/RWNNKx
