### ISSUE TITLE
$mdDialog Bugs in 0.11.0-rc1 (Unable to find node '{0}' in element. , Cannot read property 'insertBefore')

### ISSUE THREAD

**Issue by Tyrannmisu** [angular/material#4429]
Using angular 1.4.4 FF38 and chrome 44

If you are using an confirm-dialog and do not include any div or span in the content you will get the warning:
Unable to find node '{0}' in element.

The content will not be replaced,  and "{0}" will be visible instead, i guess that this is a bug and not the desired behaviour :) .

When using my old custom-dialogs with templates, i added the 
```html
<div class="md-dialog-content-body"></div> container
```
 i get the error: 
"TypeError: Cannot read property 'insertBefore' of null."

I'm not really sure if i did something wrong or if this is a bug in angular-material, the demo page seems to work just fine. I will try to reproduce it in a codepen example.

Edit:
I can't get the dialog-example to work in codepen, not even with material 0.10.1

**Comment by chronixlo** [comment]
All of the 0.11.0 md-dialog demos seem to throw errors atm

**Comment by ThomasBurleson** [comment]
@Tyrannmisu - you should never use `<div class="md-dialog-content-body">` in your template. The mdDialogContentBody is used **internally** in the Dialog component.
