### ISSUE TITLE
contact chips adding an empty object / not filtering already selected contacts

### ISSUE THREAD

**Issue by fxck** [angular/material#4431]
So the first problem, when you go to https://material.angularjs.org/latest/#/demo/material.components.chips and enter something like "foo bar" and press enter, this is going to happen

![image](https://cloud.githubusercontent.com/assets/1303561/9629069/44bd6f04-5170-11e5-8b22-a97f285ac918.png)

And the second, when "Marina Augustine" is already as a selected contact chip, you can still see her in the suggestions, you are not able to select her, but still.. I'd expect `filter-selected` to remove her from the list.

Also I'd be nice if you could get the suggestions just by focusing the input, rather than having to input at least one letter..

**Comment by fxck** [comment]
The first problem is not necessarily a duplicate of https://github.com/angular/material/issues/4404 since I don't as much care about selecting an item from suggestion when pressing enter, as about it creating a new item when no suggestion is found..

**Comment by topherfangio** [comment]
Can you test this out a bit against the master demo: https://material.angularjs.org/HEAD/#/demo/material.components.chips

I know that there have been a few changes to chips recently, and when I type "foo bar" and press enter, nothing happens (because it's not found).

If it still doesn't work as expected, can you please tell us what browser you're using?

**Comment by fxck** [comment]
![image](https://cloud.githubusercontent.com/assets/1303561/9651834/dd04ca5a-5215-11e5-91f5-30f6b4070367.png)

this happens on master when I type in "M"

![image](https://cloud.githubusercontent.com/assets/1303561/9651860/044af3aa-5216-11e5-96b8-2bf3772f628c.png)

this when "foo bar", pressing enter then does nothing indeed, but whether it's because it's bugged or because it was fixed, I don't know

and it's mac / chrome 45

**Comment by hkgrani** [comment]
I see this behavour as well. Osx and Chrome. It is working on 0.11.0-rc1 but is broken on head/ master

**Comment by topherfangio** [comment]
@fxck @hkgrani This is a known issue (#4390). The contents of the dropdown are not appearing properly, but the interaction should actually be working (i.e. if you search for `nick` and hit enter, Nick will be added to the list of chips). We're working to get this resolved.

@hkgrani Are you sure it's working in 0.11.0-rc1? I do not see the dropdown appearing properly there either: https://material.angularjs.org/0.11.0-rc1/#/demo/material.components.chips

**Comment by hkgrani** [comment]
@topherfangio Not shure. I may have tested on a wrong build/ release.
Now 0.11.0-rc1 is gone and the link do not longer work.

**Comment by topherfangio** [comment]
Might be partially fixed by #5497. Will re-test when that is merged.

**Comment by topherfangio** [comment]
I believe this is now fixed in HEAD with the exception of the `filter-selected` attribute which simply isn't implemented and is being tracked in #4131.

Please comment if you are still seeing issues and I will reopen.
