### ISSUE TITLE
Angular Material homepage on Edge - MenuBar items not justified correctly

### ISSUE THREAD

**Issue by a8775** [angular/material#4432]
![untitled](https://cloud.githubusercontent.com/assets/14092227/9631314/5b481b4c-5180-11e5-99d0-b1a02c221d4c.png)

**Comment by topherfangio** [comment]
A quick check shows that we are using `text-align: start` which unfortunately appears to not be supported in IE: https://developer.mozilla.org/en-US/docs/Web/CSS/text-align#Browser_compatibility

Are we using this in other places?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
