### ISSUE TITLE
theming documentation

### ISSUE THREAD

**Issue by matthiasg** [angular/material#4438]
i would like to understand how theming works in more detail. specifically how the e.g. textField-default-theme.css etc are being used and when and by whom since we would like to reuse the same colors/themes on our components used in conjuction with material.

the documentation seems to skip over those details .. any pointers ?

**Comment by ThomasBurleson** [comment]
@matthiasg  - general questions should be asked on the Forum. Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial).

> You may also want to review https://github.com/angular/material/issues/980#issuecomment-133977028

**Comment by matthiasg** [comment]
Thanks for the pointers.. Reading through the other issues related to theming my particular issue seems not to be easily possible yet. I will follow up in the forum as suggested

----- Ursprüngliche Nachricht -----
Von: "Thomas Burleson" <notifications@github.com>
Gesendet: ‎02.‎09.‎2015 16:45
An: "angular/material" <material@noreply.github.com>
Cc: "matthiasg" <mgt576@gmail.com>
Betreff: Re: [material] theming documentation (#4438)

@matthiasg - general questions should be asked on the Forum. Please post this in the Angular Material Forum.
You may also want to review #980 (comment)
