### ISSUE TITLE
Home page on Edge - MenuBar menu item not hidden

### ISSUE THREAD

**Issue by a8775** [angular/material#4439]
1. Click on New (in File menu)
2. Click on Format

The point is to make first click on menu item that has submenu.

![untitled2](https://cloud.githubusercontent.com/assets/14092227/9635689/ed9290ce-5197-11e5-9c53-29596f45aeaf.png)

**Comment by rschmukler** [comment]
This no longer appears to be an issue, however the menu item alignment pictured is now fixed in master as well.
