### ISSUE TITLE
chips autocomplete does initially not open with md-min-length="0"

### ISSUE THREAD

**Issue by mxab** [angular/material#4442]
Hi,

if I use the chips with autocomplete with md-min-length="0" the first click does not open the autocomplete dropdown.

if I search something the dropdown appears and then it opens also with no text

see the modified chips / autocomplete / vegetable sample http://codepen.io/mxab/pen/BoyBXQ?editors=101

**Comment by mxab** [comment]
Hmm now the sample doesn't work at all anymore with md-min-length="0"

**Comment by mxab** [comment]
I debugged it a bit, it look the autocomplete ```shouldHide``` method decide that it should not show the drop down 
```if (!isMinLengthMet() || !ctrl.matches.length) return true;``` even if the ```md-items``` would result in matches with an empty search term

**Comment by ngraef** [comment]
Notice in `querySearch` that if the query is empty, no results are returned:
``` javascript
var results = query ? self.vegetables.filter(createFilterFor(query)) : [];
```

You can change that to return all options
``` javascript
var results = query ? self.vegetables.filter(createFilterFor(query)) : self.vegetables;
```

or perhaps better yet depending on your needs, [filter out the items that have already been added](http://codepen.io/anon/pen/pjvvJB?editors=101).

**Comment by mxab** [comment]
Strange, now it works... thx
