### ISSUE TITLE
Docs do not reflect selector changes for layout and flex

### ISSUE THREAD

**Issue by jlmagee** [angular/material#4443]
All appear to still be using the attributes instead of the classes. I needed to look at the css to determine how some things are now specified. While I know the source code is the most accurate documentation, this has gone a bit far.

**Comment by ThomasBurleson** [comment]
Internet Explorer suffers huge performance degradations when using attribute selectors; switching to class selectors is the solution.
Normally this internal change would not be acceptable:
manually specifying class selectors would be very painful, confusing, and error prone
changes to existing applications would be painful and tedious
Fortunately developers do not need to change anything. 

The current attribute selectors are now directives that internal transpose their dom settings to the appropriate class styles... this happens automatically without any intervention needed from the developer.
