### ISSUE TITLE
Dynamic Height Tabs performance issue

### ISSUE THREAD

**Issue by sjlynch** [angular/material#4444]
It appears that dynamic height tabs are very slow on some hardware when switching between tabs. This is noticeable on the demos page at https://material.angularjs.org/latest/#/demo/material.components.tabs

It is still a problem with the latest release candidate https://material.angularjs.org/0.11.0-rc1/#/demo/material.components.tabs. I'm seeing the performance issue on a laptop and on an LG Tribute. The non-dynamic height tabs switch much faster and smoother.

**Comment by corentin-gautier** [comment]
This is due to height animation, as a temporary workaround ( if you wish to keep the height property ) you can set the transition-duration to 0s ( using !important ) in your css.

**Comment by apat183** [comment]
@corentin-gautier are you able to provide an example on what I need to override in my css to disable tab animation but keep dynamic height?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
