### ISSUE TITLE
fab speed dial bug: mobile force closing error

### ISSUE THREAD

**Issue by accetone** [angular/material#4446]
Not closing when try force close speed dial with ng-click handler on md-actions elements

Sample:
http://codepen.io/anon/pen/meydxR

**Comment by topherfangio** [comment]
Could you please update your description with more information about what you are trying to do, and update the demo with proper code? The `md-open` attribute is only valid on the speed dial, not the `<md-button>` elements inside of it.

**Comment by accetone** [comment]
Sorry, my fault.
