### ISSUE TITLE
text input height issue on IE

### ISSUE THREAD

**Issue by JoachimR** [angular/material#4449]
![Image of problem](http://i.imgur.com/pF50sNL.png)

http://codepen.io/JoachimR/pen/vNELdR

When the IE is resized to sm size the input field and the button should be on a second line. This then breaks the height of the input. No problem on Chrome though. 

Did I do something wrong or is this a bug ?

**Comment by topherfangio** [comment]
This appears to be working in IE11 now. Were you testing in a different version of IE?

Can you please upgrade and if you are still experiencing the issue, please let us know and I will reopen.
