### ISSUE TITLE
Question: is it possible to create a dropdown?

### ISSUE THREAD

**Issue by jjalonso** [angular/material#445]
Hi guys,
Great job, i understand that it still early but...

Is possible create a dropdown menu under a button?
Thanks.

**Comment by vko-online** [comment]
`md-menu` exists in source, but docs not updated, how to use it? 
```html
<md-menu>
      <i class="mdi mdi-view-list"></i>Products
 </md-menu>
```

**Comment by ThomasBurleson** [comment]
@vko-online - please do not comment on a closed issue.

**Comment by noddysouthgate** [comment]
@ThomasBurleson Why doesn't it just prevent you from commenting in the first place
