### ISSUE TITLE
Flex Percent Values fails in column layout

### ISSUE THREAD

**Issue by Grmiade** [angular/material#4452]
Flex Percent Values fails in column layout.
A demonstration is available [here](http://codepen.io/Grmiade/pen/zvxYaV).

```
<md-content layout="column" flex>
      <div flex="20">20%</div>
      <div flex="50">50%</div>
      <div flex>30%</div>
</md-content>
```
With this code, we obtains no three lines, but only the last `<div flex>30%</div>` which fills  the `<md-content>`

**Comment by ngraef** [comment]
This is a Chrome bug. See #1895. Nice workaround with the `flex` property though.
