### ISSUE TITLE
md-content scroll broken?

### ISSUE THREAD

**Issue by hkgrani** [angular/material#4453]
The layout systems has been changed/ updated and reverted a bit lately. 

Too me it seems that this has broken the scrolling behavour of md content. I have cleaned up the md-content codepen a bit here : http://codepen.io/hkgrani/pen/NGPRje If you make the window smaller so that the text cannot fit the page you will see the scrolling behaviour. The new behaviour is that the toolbar is scrolling with the content. Earlier the toolbar would stay put and the content would scroll @topherfangio - this may be relevant to your recent work?

**Comment by DmitryEfimenko** [comment]
Apply `style="height: 100%"` to the parent div and you'll get sticky toolbar.
It's not very intuitive, but one could get used to it.

**Comment by topherfangio** [comment]
@hkgrani This is relevant to my recent work, however, my change was a single line of code that was removed in the revert, so I think there may be a separate issue if this used to work and now doesn't.

That said, the fix suggested by @DmitryEfimenko should work, or you could possibly add the following to your global CSS: 

*If you're using master/0.11.1-rc1:*

```css
.layout-column {
  height: inherit;
}
```


*If you're using <= 0.10.1:*

```css
[layout="column"] {
  height: inherit;
}
```

We're still working to see what the other side-effects of this might be before putting it into the material styles though. It would be very helpful if you could add that and let us know if it causes any other problems.

Please see #4022 for more info. If you have any questions/new info, please add it to that discussion.
