### ISSUE TITLE
Toast align middle

### ISSUE THREAD

**Issue by RomainGoncalves** [angular/material#4455]
Hello,

first, great work!

I was wondering how to implement a "middle/center" positioning for toasts? The docs give an example for Desktop usage of toasts with it center at the bottom of the screen. I've tried a couple of things but due to the absolute positioning I need to specify a width to set the proper negative margin-left in order for it to be properly centered.
I also tried making it a flex element, but the absolute positioning takes over no matter what. And when I remove the absolute, then there's no more overlay effect.

Anyway, does anyone know how to do that?

Thanks.

**Comment by RomainGoncalves** [comment]
Hmm ok, duplicate of which issue please? So I can follow. Thanks

**Comment by topherfangio** [comment]
@RomainGoncalves Looks like #1173 is the existing issue/enhancement request.

**Comment by ThomasBurleson** [comment]
@topherfangio - #1173 has been closed. Do you have the right issue #?

**Comment by topherfangio** [comment]
@ThomasBurleson Nope...let me track it down again...must have transposed the numbers somewhere :/

**Comment by topherfangio** [comment]
Sorry, duplicate is #1773.

**Comment by RomainGoncalves** [comment]
Thanks for that.
