### ISSUE TITLE
md-theme creates too many styles in HEAD

### ISSUE THREAD

**Issue by wlingke** [angular/material#4457]
After using the $mdThemingProvider to create multiple themes, I've noticed that my `<head>` is getting clutter with tons of styles.

One of the biggest implications is that it breaks the FB Scraper. There seems to be a max amount of characters that is allowed in `<head>` before it stops registering the page. I am not sure about other scrapers.

After I removed some palette and theme definitions, the scraper worked properly again.

FYI - I use Prerender.io and am 100% sure the pre-rendered page is created correctly and is being delivered to the scraper.

**Comment by Duovili** [comment]
Did you resolve this?

**Comment by wlingke** [comment]
I removed some themes and it works but that doesn't solve the problem. 



—

**Comment by mxab** [comment]
How do you add your meta tags? I do it dynamically and use jquery's prependTo
```
jQuery('<meta>', {
 content: 'Hello World,
 property: 'og:title'
}).prependTo('head');
```

and it works for me as the meta tags are before the theme part

**Comment by ThomasBurleson** [comment]
Please continue this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
