### ISSUE TITLE
md-tab(md-on-select being called too early and/or focus issues)

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#4458]
I've been playing around with md-tab and trying to get things to focus. Here's an example.

http://codepen.io/anon/pen/RWNKdp

What's going on is md-on-select is being called the moment the animation starts. This is causing me issues when trying to externally change the selectedIndex (for example, with keyboard or a button). You can check the console log and see that the tab has focus when selecting with the mouse  and the body element grabs focus when you press Left or Right after 1000ms (external selectedIndex change). 

For comparison, on Android, this event wouldn't fire until the animation is completed (or the horizontal offset matches the tab position).

**Comment by clshortfuse** [comment]
An update: 

http://codepen.io/anon/pen/jbEmBq?editors=101

Apparently, you need to wait between 100ms to 200ms before trying to apply focus to any item inside. This is probably related to this line:

https://github.com/angular/material/blob/master/src/components/tabs/js/tabsController.js#L701

Right now I'm going to set a timeout to 500ms.

**Comment by robertmesserle** [comment]
This is as designed and consistent with the way that Angular approaches animations and state.

**Comment by clshortfuse** [comment]
@robertmesserle  I know you closed the issue, but maybe there should be a callback for when the animation completes?

    angular.element(elements.inkBar).css({ left: left + 'px', right: right + 'px' });

Using a timer as a workaround would be unreliable on slow machines (like tablets and phones). I've read that .animate() does have callback support. 

If there's some reason why you'd rather use .css() instead of .animate(), you can use .promise().done(*function*);

Here's an example of .css() with a callback;

http://codepen.io/anon/pen/LpyoNz

**Comment by robertmesserle** [comment]
@clshortfuse As far as I know, we can't use `.promise()` because that isn't supported by jqLite and we can't assume that all users have included jQuery; however, I'm going to reopen this issue for `post-1.0`

**Comment by clshortfuse** [comment]
@robertmesserle Yeah, I realized that it's jQuery later. I got something working here using angular:

https://github.com/clshortfuse/material/blob/patch-10/src/components/tabs/js/tabsController.js

It's a bit of a hack. I'm going to look into perfecting it, but it's a start.
