### ISSUE TITLE
md-subheader low performance

### ISSUE THREAD

**Issue by jbraccini** [angular/material#4459]
Hello, I went into a possible performance issue when adding md-subheader (i.e: as is in the official demo in the Angular Material website).

It seems to behave properly according to documentation and demo page, but when scrollbar is available to interact, both scrolling and window scaling interactions would result in a remarcable loss of fps.

Also, the current demo seems to have such fps loss > https://material.angularjs.org/latest/#/demo/material.components.subheader

Can someone confirm this?

Chrome Version 44.0.2403.157 m

**Comment by clshortfuse** [comment]
This is an angular 1.4.x issue that was fixed in 1.4.5.  The demo uses 1.4.4
