### ISSUE TITLE
md-input-container label md-icon and ng-click

### ISSUE THREAD

**Issue by f1tech** [angular/material#4461]
I have tried a variety of ways to use a label and an icon in an md-input container and the layout works as expected with the icon within the label tag, however; regardless of where I put the icon, ng-click doesn't fire when the icon is clicked. This applies to when ng-click is used on the label, the icon or both the label and the icon. Below is a simple example that illustrates this:

    <md-input-container>
        <label ng-click="alert('search')"><md-icon ng-click="alert('search')">search</md-icon>Title</label>
        <input ng-model="orderItem.title" size="50">
    </md-input-container>

**Comment by langdonx** [comment]
This happens for the same reason none of the `for` attributes on labels are currently not working -- the `pointer-events` style is set to `none` for all labels under `md-input-container`.  You can get around it by overriding that style though:

http://codepen.io/langdonx/pen/qOdpKq

FWIW, you'll never get a alert traditional `alert` working in an ngClick though, unless you've defined `$scope.alert` as a relay.

It's also interesting to note that this is the reason you can never right click and inspect element on the label (it always takes you to the md-input-container).

**Comment by ThomasBurleson** [comment]
Use wrap the icon in a md-button to get ripples and click support.

> You should never be able to click on an icon - it is a graphical representation only; not an interactive element.

**Comment by langdonx** [comment]
@ThomasBurleson Is the fact that you can't click the label to access the field not an issue (once a value has been typed, obviously)?  It looks like `md-input-container` generates `id` and `for` attributes if you don't provide them, but what other advantages does the `for` attribute provide aside from clicking it?

**Comment by f1tech** [comment]
Really, what I'm trying to do is provide a button that is visually very similar to the standard label with an icon. <md-button> with nested text and a nested <md-icon> are pretty far off from a stylistic standpoint, and you lose the magic effects on the label when you replace it with the button/icon combination. Trying to position a button to the left or right of the textbox seems to be exceedingly painful as well. I'm sure I can do it with CSS, but I'd think this is a common enough need to be build in.

**Comment by ThomasBurleson** [comment]
@langdonx - Perhaps I was premature. IMO, clicking the label (associated with the input field) is reasonable and is similar to the support we offer for RadioButton label-clicks.

Let me reopen. Thx.

**Comment by f1tech** [comment]
Excellent!

**Comment by robertcedwards** [comment]
This is still an issue correct? I know I'm looking for a solution…

**Comment by langdonx** [comment]
@robertcedwards my first reply above describes a solution.

**Comment by robertcedwards** [comment]
@langdonx ok, thanks.
