### ISSUE TITLE
Cannot have a label and placeholder in ng-input-container

### ISSUE THREAD

**Issue by KyleWpppd** [angular/material#4462]
Labels clobber placeholders when `md-input-container` has the `md-no-float` attribute set. Instead of the label should not be clobbering the `placeholder`, the label should remain in label position. 

![angular-material-placeholder-label-bug](https://cloud.githubusercontent.com/assets/597653/9671674/70d9782e-5249-11e5-9a30-456f4e8fdca6.gif)

**See demo:** http://codepen.io/anon/pen/RWNVJz

HTML:
```
<div ng-controller="DemoCtrl" layout="column" class="inputdemoIcons" ng-app="MyApp">
  <br>
  <md-content layout-padding="" class="autoScroll">
    <md-input-container md-no-float>
      <label>Name</label>
      <input ng-model="user.name" type="text" placeholder="Johnny Appleseed">
    </md-input-container>
  </md-content>
</div>
```

JavaScript:
```
angular
  .module('MyApp')
  .controller('DemoCtrl', function($scope) {
    $scope.user = {
      name: '',

    };
  });
```

**Comment by topherfangio** [comment]
Related to #1427.

After discussion with the team, we are planning to allow support for both placeholders and labels within an `<md-input-container>`. If we see both, we will automatically apply the `md-no-float` attribute and ensure that the label always stays in the "elevated" position above the input component.

**Comment by CSHMcLovin** [comment]
You can manually set the class on the label to  md-no-float as a work around for now http://codepen.io/anon/pen/QjypdO
