### ISSUE TITLE
md-tooltip does not support multiple lines of text

### ISSUE THREAD

**Issue by sunocean-sand** [angular/material#4464]
It seems like md-tooltip does not support multiple lines of text. It does not adjust to mobile device screens either. Has anyone figured out how to change this?

**Comment by ThomasBurleson** [comment]
Solution: We need to modify the tooltip API to support simple HTML content.

**Comment by kschwidder** [comment]
+1

**Comment by houmark** [comment]
+1

**Comment by webley** [comment]
+1

**Comment by eloyleonardo** [comment]
+1

**Comment by victor-perez** [comment]
+1

**Comment by SanderElias** [comment]
@ThomasBurleson, Can you define 'simple' HTML? Where do we draw the line?

**Comment by SanderElias** [comment]
The specs hint that a tooltip is a single line of text. As I didn't receive any more feedback on this, I'm now closing this issue as working according to spec.

**Comment by EladBezalel** [comment]
From [material spec](https://www.google.com/design/spec/components/tooltips.html#tooltips-usage):
> Tooltips don’t display rich information including images and formatted text.
>
Tooltips are different than ALT-attributes, which are intended primarily for static images.
>
Tooltips don’t have directional arrows; instead, they rely on motion emanating from the source to convey direction.
