### ISSUE TITLE
fab buttons transparent on hover

### ISSUE THREAD

**Issue by bathos** [angular/material#4465]
Fab icons normally default to md-accent colors -- but not on hover, in which case they turn transparent. Explicitly adding md-accent fixes that, but it seems like the default behavior was probably not intended.

**Comment by topherfangio** [comment]
I am not sure I fully understand the problem. Any chance you could modify the following basic FAB Codepen so that it shows the issue?

http://codepen.io/topherfangio/pen/RWPMyW

**Comment by bathos** [comment]
Sorry, I didn't follow up. I haven't been able to replicate it in the codepen. It must have been something specific to my app, though I'm not sure what -- there is very little custom css & no selectors with :hover. In case this wasn't just something I imagined / caused, I'll note for posterity that the phenomenon occurred when I had a fab button hanging halfway down from an md-toolbar (using 'top: 50%'), on a dark theme.
