### ISSUE TITLE
Md-chips allows duplicate objects

### ISSUE THREAD

**Issue by gpopovic** [angular/material#4466]
Md-chips currently doesn't allow duplicate strings, but will happily allow duplicate objects.

MdChipsCtrl.prototype.appendChip checks for duplicates with indexOf and because of that only duplicate strings and duplicate items referencing the same object are removed.

Because of that I often find myself writing md-on-append function to check for myself if objects are the same. 

Solution would be to check if $chip is an object and use angular.Equals()? or to allow user to specify expression used to check for duplicates.

**Comment by raunakpsingh** [comment]
Is there anyworkaround for this??

**Comment by topherfangio** [comment]
See PR #4479 which should hopefully be merged soon; we're trying to get 0.11 pushed out the door first.

**Comment by Dwiga** [comment]
how to make a count on it?
for example, 
Banana (1), Apple (1), Tomato (1)
----------------------------------
after that, i write on it tomato again
it'll become like this
Banana (1), Apple (1), Tomato (2)...
thank for your help.
dwi.ahmad@protonmail.com
