### ISSUE TITLE
Datepicker UX/UI design

### ISSUE THREAD

**Issue by Soulcyber** [angular/material#4467]
Sorry guys, but i really don't like the new datepicker design, i think it isn't too much material style and seems really boring to me.

i know this is a pre-release of the component and probably the final layout will be different, i followed this discussion here https://github.com/angular/material/issues/648 but i want to show you this one:
http://codepen.io/alenaksu/full/eNzbrZ

![image](https://cloud.githubusercontent.com/assets/4432213/9680696/ee28dd88-52f8-11e5-9ac9-25564e3eac3e.png)
![image](https://cloud.githubusercontent.com/assets/4432213/9680703/020fae30-52f9-11e5-8e5d-97b7ea43c600.png)

i really like this because a lot of similar pickers doesn't allow you an easy selection of the year, while in this one a simple ComboBox do the trick pretty well.
Hope to see the final datepicker similar to this or with the same functionality :)

Obviously all IMHO
Thanks

**Comment by EladBezalel** [comment]
@Soulcyber This is really nice, i think this should be an option of the date picker (dialog or popover),
it's missing few [material animations](http://material-ui.com/#/components/date-picker) but it's a good start.

**Comment by stefan-schweiger** [comment]
Looks great! Even if it doesn't become a dialog, I still would also prefer it for the popover

**Comment by jelbourn** [comment]
We are following a spec for the datepicker that hasn't been published yet to the Material Design site, but should be sometime in the near future. There is definitely going to be some fine tuning to the user experience, especially around the discoverability of the scrolling. Unfortunately, "I don't really like it" and "seems boring" aren't very actionable pieces of feedback. If you have some more specific feedback please feel free to open new issues. 

Being able to change the year quickly is something that is in the spec, but we weren't able to implemented for this initial release. It will be coming in the future.

**Comment by ThomasBurleson** [comment]
@Soulcyber - Using the current DatePicker you should be able to easily build the component below:

![image](https://cloud.githubusercontent.com/assets/4432213/9680703/020fae30-52f9-11e5-8e5d-97b7ea43c600.png)

I could see the psuedo-code as something like:

```html
<md-dialog>
  <md-date-card>  
    <!-- this is your custom component here -->
    <md-date-card-title>
    <md-date-content>
    <!-- this the standard datePicker -->
    <md-datepicker>
  </md-date-card>
<md-dialog>
```

**Comment by Soulcyber** [comment]
i will try it, thank you all :+1:

**Comment by lscordilis** [comment]
+1 I prefer the popover, but the real issue here is the mysterious need to use the scroll wheel to scroll through the dates. Arrow icon buttons to page through the months would be infinitely better.

**Comment by Soulcyber** [comment]
Yes scrolling is not really intuitive
