### ISSUE TITLE
Toolbar background color

### ISSUE THREAD

**Issue by seemsindie** [angular/material#4468]
No matter what theme i select, the background color of the toolbar is always the same, it's black.

I have this in my config:

    $mdThemingProvider.theme('default')
    .primaryPalette('blue')
    .accentPalette('orange');

And my toolbar looks like this:

![](http://i.imgur.com/5dLtp6z.png)

And i tried a bunch of possibilities like md-primary, then with hues...md -primary in all hues is black for me...
But in examples at your website the toolbars are blue. My question is, how do i change the color of toolbars, do i just add my custom css, or there is a better way to do it?

**Comment by EladBezalel** [comment]
Can you post a [plunker](http://plnkr.co/) or a [Codepen](http://codepen.io/) of your problem?

**Comment by seemsindie** [comment]
Guys i am sorry i created mess, i had some css interfering. Tried with clean install worked fine.
