### ISSUE TITLE
Proposal for md-list performance

### ISSUE THREAD

**Issue by Asesjix** [angular/material#4470]
If I want to 1000 entries displayed in an md-list, the browser hangs shortly. 
It would be possible the functionality of md-virtual-repeat in md-list take?

**Comment by EladBezalel** [comment]
@Asesjix something like [this](http://codepen.io/EladBezalel/pen/MaYQJJ)?

**Comment by Asesjix** [comment]
hey thanks that's exactly what I meant ;-) 
I just did not know that an MD-list in an md-virtual-repeat-container is possible :(
