### ISSUE TITLE
hide show-gt-md not working in 0.11.0-rc2

### ISSUE THREAD

**Issue by opadillaintegrify** [angular/material#4471]
```
<md-list-item hide show-gt-md>
```

Before 0.11.0-rc2, the line above would display the list item on devices greater than 600px wide, negating the hide as described in the documentation on https://material.angularjs.org/0.11.0-rc2/#/layout/options.

After I upgraded to 0.11.0-rc2, however, that md-list-item stays hidden.

**Comment by opadillaintegrify** [comment]
BTW I was on 0.10.1 before I upgrade to 0.11.0-rc2

**Comment by ThomasBurleson** [comment]
Show options have precedence. Try:

```html
<md-list-item hide-lt-lg>
```

**Comment by ThomasBurleson** [comment]
This is working in a pending Pull Request that should be committed to master tomorrow.
Here is a CodePen to validate the functionality:  http://codepen.io/ThomasBurleson/pen/pjbpdw?editors=110

**Comment by ThomasBurleson** [comment]
With the SHA 843d63ec5520d313eb327d2d99606e9f6177912e on master, You should be able to verify that the follow works as expected:

```html
<div layout="row" class="layout-content" >
    <div flex >
      [flex]
    </div>
    <div flex hide show-gt-md >
      [flex]
    </div>
    <div flex hide-sm>
      [flex]
    </div>
  </div>
```

Here is the [CodePen Demo](http://codepen.io/ThomasBurleson/pen/pjbpdw?editors=100)
