### ISSUE TITLE
md-chips requires secondary-placeholder to use placeholder

### ISSUE THREAD

**Issue by Emeegeemee** [angular/material#4476]
When using the md-chips directive and setting a placeholder it won't be used unless a secondary-placeholder is set. I would expect that in the secondary-placeholder would just be set to the same value as placeholder if it isn't specified.

Here's a codepen: http://codepen.io/anon/pen/OyPwjW

**Comment by ericgundrum** [comment]
Likely this is an artifact of issue #2770, _secondary and primary placeholders switched in md-chips_. The code is written to prefer the secondary placeholder over the primary. The fix is trivial. (I documented it in #2770.)

**Comment by ericgundrum** [comment]
The pull request @dbwhddn10 associated with #3804 should fix this issue.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
