### ISSUE TITLE
md-datepicker: Feature request change date within input field directly

### ISSUE THREAD

**Issue by kschwidder** [angular/material#4478]
md-datepicker should also provide a way to enter the date directly when an input-field is defined.
The validation should be checked against an array of date formats or as a given regex. 
In case the date is valid and a user opens the calendar than the input date should be shown.

**Comment by jelbourn** [comment]
@kschwidder I don't follow what you mean. The datepicker contains an input element into which the user can type a date. The parsing and formatting of that date can be defined by the user with `$mdDateLocaleProvider.` Re-open this issue if that does not cover what you meant.

**Comment by kschwidder** [comment]
Solved based on your suggestion. Thx

**Comment by maddy2308** [comment]
whenever I use the md-datepicker and if it is near the page margins it doesn't open properly. By not opening properly I mean it is not scrollable and it should by itself know where it needs to show the popup based on its space requirement

**Comment by jelbourn** [comment]
@maddy2308 Please open a new issue instead of commenting on an unrelated, closed issue. The problem you're describing seems like it is something that has been fixed on master and will be included in the 0.11.1 release.

**Comment by maddy2308** [comment]
Oh I didnt realise the issue was closed.

**Comment by maddy2308** [comment]
Oh I didnt realise the issue was closed.
