### ISSUE TITLE
md-select from 0.11.0-RC2 not usable in Safari on iOS and Android native browser

### ISSUE THREAD

**Issue by Sayene** [angular/material#4483]
md-select automatically gets closed just after being opened - leaving no time to make a selection
tested on iOS 7.1, 8.4, Android 5.01 - on Demo page. it works OK in 0.10.1.

**Comment by ThomasBurleson** [comment]
This may be a "2-click" event issue reported early.

**Comment by rschmukler** [comment]
This is fixed on master. Was likely an issue with the `$mdUtils.supplant` method.

**Comment by Sayene** [comment]
Just tested again and fix does not seem to be working - neither on  0.11.1 or master. Testing on iOS safari and demo page selects.

**Comment by topherfangio** [comment]
@Sayene I just tested on my iPhone/iPad and the demos seem to be working. What version of Safari are you using, and which demos did you test?

**Comment by Sayene** [comment]
@topherfangio we got this issue on:
1.  ipad Air with iOS 7.1.2; Safari browser
2.  ipad Air with iOS 8.1.3 Safari browser
3. Samsung Galaxy Tabs S 10.1, Android 5.02 built-in browser
with these demo pages
a) https://material.angularjs.org/latest/#/demo/material.components.select
b) https://material.angularjs.org/0.11.1/#/demo/material.components.select
c) https://material.angularjs.org/0.11.0/#/demo/material.components.select
Select options stay open only if you tap and hold it pressed longer (which in Safari causes text selection), but if only tapped it closes immediately. Versions prior 0.11.0 work ok in these browsers.

**Comment by barryvdh** [comment]
Is fixed with https://github.com/angular/material/commit/7251684315bcc65fcd7599ac88f84dcf51a2a219
