### ISSUE TITLE
md-datepicker: Support empty value/model

### ISSUE THREAD

**Issue by muhlegg** [angular/material#4486]
Will empty models be supported or is it by design that there must be an date object? There are scenarios where it is not convenient to set a default value before the user picks a date.

**Comment by jelbourn** [comment]
This should be supposed already. Re-open if you have encountered an issue with this.

**Comment by muhlegg** [comment]
Okey, it seems like the default 1970 date comes from the $mdDateLocaleProvider, not from datepicker itself. So let's keep this closed.

**Comment by mcblum** [comment]
@muhlegg did you ever figure this out? we've got 1970 dates everywhere that a null date exists :)
