### ISSUE TITLE
AutoComplete: focus events don't fire for md-autocomplete when inside md-dialog

### ISSUE THREAD

**Issue by akdor1154** [angular/material#4489]
md-autocomplete should open suggestions on click if it has the attribute md-min-length="0". This works as normal, unless the md-autocomplete is inside an md-dialog. In that case, the suggestions will not pop up until the user starts to type something. This appears to be because the focusevent is not firing on the autocomplete element.
Tested with 0.10.1 and 0.11-rc2

**Comment by robertmesserle** [comment]
@akdor1154 Can you create a codepen demonstrating this behavior?

**Comment by varshag91** [comment]
Facing same issue. if md-autocomplete is inside md-dialogue and user press backspace on already added value inside md-autocomplete and then scroll down by accident on wheel  event of md-dialog will make variable List invisible and user has to blur and focus the md-autocomplete input again to see the variable list dropdown.
