### ISSUE TITLE
Scroll shrinking toolbar adds whitespace below content

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#449]
Screenshots of the bottom of the demo component (https://material.angularjs.org/#/demo/material.components.toolbar): 

Scroll down, so far behavior is correct:

![screen shot 2014-10-17 at 7 20 56 pm](https://cloud.githubusercontent.com/assets/9092817/4687438/e8325784-5654-11e4-9aea-8f1e4c8af4d4.png)

Then scroll up:
![screen shot 2014-10-17 at 7 20 30 pm](https://cloud.githubusercontent.com/assets/9092817/4687451/2a500652-5655-11e4-9fed-a7a5448fef45.png)

**Comment by flight212121** [comment]
Was able to find a workaround :

- Add layout-fill to md-content
- Remove layout-fill from container (the <div> with ng controller in the demo)
- Put container height: 600px;

![asdfsaf](https://cloud.githubusercontent.com/assets/9644867/7118669/d174dc64-e1ce-11e4-834c-679660e2e547.PNG)

In my app, the container's height is 100vh, toolbar's height is 75px, md-content's height is calc(100vh - 75px), then with the modifications suggested above, it works nicely!
