### ISSUE TITLE
mdSelect handles empty string value incorrectly

### ISSUE THREAD

**Issue by vfeskov** [angular/material#4493]
Consider this code:
```
<div ng-init="themodel=''">
  <md-select ng-model="themodel">
    <md-option value="">None</md-option>
    <md-option>Blue</md-option>
    <md-option>Green</md-option>
  </md-select>
  {{themodel}}
</div>
```
When you run it, select will not have "None" active, and when you select "None" the model value becomes "0" instead of empty string.

Demonstration using address example from the website:
http://codepen.io/anon/pen/rOVdrq

**Comment by timtimmytime** [comment]
I encountered this same problem while using version 0.11.0 but updating to 0.11.3 and 0.11.4 has fixed this issue. 
md-select now return an empty string (as expected) instead of 0

**Comment by rschmukler** [comment]
Marking as fixed.

**Comment by satheesh786** [comment]
is this issue fixed ?

**Comment by rschmukler** [comment]
@satheesh786 per [this demo](http://codepen.io/rschmukler/pen/vNMmyb) it seems to be fixed
