### ISSUE TITLE
v0.11.0 Breaking changes not well documented 

### ISSUE THREAD

**Issue by no-more** [angular/material#4496]
Hi,

I have just checked the new release but it has some breaking changes and no migration guidelines. Also the documentation is not updated accordingly. For example: 
 * Layout (flex, layout, etc) use Class selectors instead of Attribute selectors

Thanks a lot,
Great job.

**Comment by langdonx** [comment]
I upgraded to 0.11.0 this morning and haven't noticed anything with `layout` yet. The layout attributes still work, they just add classes now, because of IE11 performance issues.  Are you seeing issues because you've overridden layout/flex stuff in CSS?

**Comment by epelc** [comment]
@no-more Please see my [question](https://groups.google.com/forum/#!topic/ngmaterial/h5WLFFqth_0) on the forums. @ThomasBurleson answered it nicely. Essentially you should ignore this and continue to use the layout/flex options as you were before. It's an internal change to fix performance issues with IE.

**Comment by no-more** [comment]
Hi,

Thanks for your feedback, I think I've gone to fast on this, I've already updated my code (took me the whole day).

I thought this was going to be the new default requirement.

It there anything wrong keeping the class version? or should I switch back to attribute ? Both should be possible as the class version might be slightly faster (no need to go through directives). 

Thanks.

**Comment by jelbourn** [comment]
The supported public API is using the attributes (nothing changed from 0.10 to 0.11). The internal implementation uses classes for now, but is subject to change at any time in the future.
