### ISSUE TITLE
md-select can not working 

### ISSUE THREAD

**Issue by lhqmcy** [angular/material#4501]
I use the "md-select" directive just like this : 
```html
<section layout="row" layout-align="space-around center" layout-margin>
  <md-select ng-model="current.path" placeholder="appName" flex>
    <md-option ng-value="item.Id" ng-repeat="item in items">{{item.Name}}</md-option>
  </md-select>
<section>
```

when i run the app on a mobile(webkit 41 and android 4.4),it was wrong :angular-material.js:5004 
```
Uncaught TypeError: Cannot read property 'split' of undefined.
```

The material version is v0.11.0-master-d7ffe17。

now, I modify the function "parseMaxTime" just like : 
```js
if (typeof str == 'undefined')
   return 0;
var maxValue = 0;
var values = str.split(/\s*,\s*/);
forEach(values, function (value) {
   // it's always safe to consider only second values and omit `ms` values since
   // getComputedStyle will always handle the conversion for us
   if (value.charAt(value.length - 1) == 's') {
       value = value.substring(0, value.length - 1);
   }
   value = parseFloat(value) || 0;
   maxValue = maxValue ? Math.max(value, maxValue) : value;
});
return maxValue;
```

**Comment by bossesm** [comment]
I get the same error and I don't know how resolve it

**Comment by topherfangio** [comment]
Could one of you possibly provide a [Codepen](http://codepen.io) that shows how to reproduce the issue? It makes it a lot easier for us to test and debug.

**Comment by timdiam** [comment]
Codepen: http://codepen.io/anon/pen/QjyqWZ

It looks to be version conflicts.

**Comment by jelbourn** [comment]
It looks like this was fixed here: https://github.com/angular/material/commit/a5d84c372f87e96469f6c7d72d42d0aea83fe8fd#diff-1070b396d1eb6636d8b11b66a8b9d760L318

Feel free to re-open if the issue is still present.

**Comment by ThomasBurleson** [comment]
@jelbourn - Thank you for triaging this!
