### ISSUE TITLE
md-datepicker in a div with class md-toolbar-tools messes up the view

### ISSUE THREAD

**Issue by VikramTiwari** [angular/material#4502]
Along with that, the popup dialog is not space aware. It tries to pop up on the right always even when there is not enough space on the screen.

**Comment by EladBezalel** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by verkestk** [comment]
I'm seeing this as well with the downloaded versions of the angular material js and css, but not with the CDN version.

**Comment by RichOren** [comment]
Here is a Demo Pen.

http://codepen.io/anon/pen/gazQmw

Also this date picker does not even conform to material design pickers. https://www.google.com/design/spec/components/pickers.html

This one does a great job at conforming to standards. http://codepen.io/anon/pen/RWyeYz

So far I see only one use-case for this - and that is in a form on a white background ONLY. Not much flexibility on this one. I am not sure the not so savvy users would even know to scroll the content with no scrollbars.

**Comment by hkjels** [comment]
I really prefer the one that conforms to the standards. It would work with all the use cases, I have in our current project. Just the ability of using a custom icon-button is a major improvement, cause there's not always room for an input.
