### ISSUE TITLE
md-autocomplete validation messages not displayed

### ISSUE THREAD

**Issue by dexster** [angular/material#4505]
Is validation supposed to be fixed in the 0.11 release? I still can't see required mesages. I've tried copying and pasting the "Example with validation" from the API Reference -> Directives and even this does not show validation.

**Comment by jb29** [comment]
I have the opposite problem. `md-autocomplete` is always marked as required even if `ng-required` is `false`.

**Comment by robertmesserle** [comment]
I believe this is resolved.
