### ISSUE TITLE
The header of sidenav is not visible in cordova

### ISSUE THREAD

**Issue by askanhan** [angular/material#4506]
If i test the app out in my host, it is working without problem. But if i open in using cordova (5.2.0), the header of sidenav is not visible.
(angular(1.3.6), angular-material(0.11.0))
A screenshot:

![aze](https://cloud.githubusercontent.com/assets/5607648/9756836/3937ec5a-56dd-11e5-853d-2f7d4a6065fe.PNG)

**Comment by EladBezalel** [comment]
@askanhan is it still happening on master?

**Comment by EladBezalel** [comment]
Closing due inactivity
