### ISSUE TITLE
md-datepicker feature request "format" attribute to parse date input

### ISSUE THREAD

**Issue by kschwidder** [angular/material#4510]
When switching between multiple languages the date formats are changing too.
Therefore an attribute to pass forward specific parsing options would be highly beneficial. The format should be passed forward to the $mdDateLocaleProvide parser as an additional parameter.

<md-datepicker format="'DD-MM-YY'"> or
<md-datepicker format="['DD-MM-YY','DD-MM-YYYY']">

**Comment by kschwidder** [comment]
Solved via $mdDateLocale Service where I set the parser function each time.

**Comment by julbr** [comment]
Works like that. thanks!
