### ISSUE TITLE
Menu Position Mode link of code pen is notworking

### ISSUE THREAD

**Issue by surajnaikwade143** [angular/material#4514]
Link in Menu Position Mode is not working

**Comment by surajnaikwade143** [comment]
Yet not fixed

**Comment by ThomasBurleson** [comment]
@surajnaikwade143 - Please provide more details and specifics. Our testing on https://material.angularjs.org/HEAD/#/demo/material.components.menu looks good.

**Comment by surajnaikwade143** [comment]
https://material.angularjs.org/latest/#/demo/material.components.menu

Check this link. Menu Position Modes codepen link is not working.

**Comment by ThomasBurleson** [comment]
This has been fixed in the latest codebase; on HEAD.
