### ISSUE TITLE
mdTooltip: md-visible binding not isolated

### ISSUE THREAD

**Issue by treaz** [angular/material#4517]
Hello,

**Overview of the issue**
I'm trying to create a button (md-button) that has a tooltip (md-tooltip) that only appears when the button is clicked and disappears when the button is clicked again.
In order to achieve that, I'm setting a scope variable when the button is clicked and using it as argument for md-visible. Problem is that the md-tooltip directive is changing that variable so I can't achieve the behavior that I want.

**Angular Material Version**
0.11.0

**Reproduce the Error**
https://gist.github.com/treaz/ab4e840847384705e2d2#file-tooltip-js

**Suggested fix**
If md-visible would be isolated (@ instead of =) everything would be fine. I don't understand why it's needed to have bidirectional binding anyway.

Looking forward to see what you think of it

**Comment by lucasbeef** [comment]
I have the same problem when using tooltips on my speed dial buttons.
It seems like md-visible toogles automatically when the speed dial opens/closes (and without delay, so they dont position correctly on speed dial's first opening). 

I am on rc4

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (506/500 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:45979 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsbg-000Kso-H4
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:16 -0500
Date: Thu, 28 Apr 2016 13:26:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875174;
	bh=mPssGWHAr/gkSIUC0okRfU4vYHctU0jIi8W9AQB/lOo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Vyg3SXoax6JtPNfuGWmIp0jKNlHeUgHkmG7nsPku1KjBEapzJCk6mZMysRLz09ZzZ
	 rRl0jn3+w4aTsAAd63LuSErfs6aYqxTU5+C1L5JuX44R7rQ1oo8936fdgcleRQFJwm
	 fz51PoDsVZb2lsTsno/Quq7xJzsgDHs7ZgccwqCA=
