### ISSUE TITLE
closing autocomplete after selection when md-min-length="0"

### ISSUE THREAD

**Issue by mxab** [angular/material#4518]
Hi,

When I use md-min-length="0" in my chips/autocomplete it opens directly and I can select something, but the auto complete pops up again immediately after I select something. I guess because of the focus, but it feels weird.
See this example http://codepen.io/mxab/pen/zvGQeE?editors=101

I think what would be more expected that it opens again after I explicitly click into the input again, like for example in select2's multi select (https://select2.github.io/examples.html#multiple)

**Comment by mwymann** [comment]
+1

**Comment by topherfangio** [comment]
I think this would require some new `md-chips` attributes for what mode of operation it should use, and I think we should put some thought into that if we go that route.

In the meantime, could you dynamically set the `md-min-length` to `0` if there are no selected chips, and `1` if there are? This would force users to type into the input to bring up the list. I guess you could also watch for clicks on the input and reset it `md-min-length` to `0` to get the list to automatically appear.

**Comment by elubin** [comment]
+1

@topherfangio can you provide a code sample to dynamically set md-min-length?  or do you mean straight dom manipulation?
