### ISSUE TITLE
Flex does not fill

### ISSUE THREAD

**Issue by pizzapanther** [angular/material#4520]
From 0.10 to 0.11 flex-grow seemed to have changed. Blocks with `flex` used to grow to fill height when used with column layout.

0.10 Example: http://codepen.io/pizzapanther/pen/VvLJro?editors=100
0.11.0 Example: http://codepen.io/pizzapanther/pen/ojXrER?editors=100

**Comment by ThomasBurleson** [comment]
You must define a ngMaterial module dependency:

```html
  <body ng-app="myApp">
    <div layout="column" style="background-color: blue; height: 250px;">
      <div flex style="background-color: #ccc">
        NARF
      </div>
    </div>
  </body>
```

with  JS

```js
angular.module('myApp', ['ngMaterial']);
```

See these notes on [Google Groups](https://groups.google.com/forum/#!topic/ngmaterial/h5WLFFqth_0):

Developers cannot use angular-material.css with its the Layout features without the 'ngMaterial' module. 
The angular-material.js (or .min.js) must be loaded. And 'ngMaterial' must be a module dependency within your application. 

Otherwise the ngMaterial Layout directives will not [currently] work.
Without ngMaterial, the directives will not compile/link and the Layout classNames will not be attached to the elements.

>  We plan, however, to release [soon] another CSS file with the original layout attribute selectors so the Layout features could be used separate from the UX components and modules.

**Comment by pizzapanther** [comment]
I had the same problem even when ngMaterial is included.  See: https://www.pytexas.org/2015/schedule

This is where I first saw the problem.  I added my own css style with `flex-grow: 1` to fix the problem.

```css
.Schedule .talk {
    padding: 10px;
    margin: 5px;
    background-color: #e2ecf5;
    border-radius: 2px;
    -ms-flex-grow: 1;
    flex-grow: 1;
}
```

**Comment by pizzapanther** [comment]
Here is a screenshot with flex-grow: 1 on and off

on
![screenshot-www pytexas org 2015-09-09 13-09-38](https://cloud.githubusercontent.com/assets/552478/9770163/314e10a2-56f4-11e5-9c77-9bf2e5164ed8.png)

off
![screenshot-www pytexas org 2015-09-09 13-09-51](https://cloud.githubusercontent.com/assets/552478/9770171/39cc8d9e-56f4-11e5-8f68-85b8a4f0e4dc.png)

Previously i didn't need to add my own CSS in 0.10.0

**Comment by carlosafonso** [comment]
Hi,

First of all thank you for developing this awesome project.

I've come across a similar issue here.  Prior to 0.11 this would work as expected:

```html
<div flex="90">Content</div>
```

With the latest version I see that `angular-material.css` no longer applies `max-width: 90%` to the element, which matches what the changelog says. However, unless I am mistaken I would expect the element to have the class `flex-90` applied to it. In fact, if I do so manually the element receives the correct style.

I have double checked and my app is including `ngMaterial` as a module dependency.

**Comment by ThomasBurleson** [comment]
@carlosafonso - this has been fixed and is still in testing. Standby...

**Comment by carlosafonso** [comment]
Thank you.

If there's anything I can do to help testing please let me know.

**Comment by jmls** [comment]
standing by .. any chance of a hotfix or is it coming in the next release ?

**Comment by pizzapanther** [comment]
adding `flex-grow: 1` (with prefixes) gave me a quick patch until this gets resolved.

**Comment by ThomasBurleson** [comment]
This has been fixed and will be committed to master soon. http://codepen.io/ThomasBurleson/pen/JYKOjb?editors=100
