### ISSUE TITLE
layout row and column not working...

### ISSUE THREAD

**Issue by oshko** [angular/material#4521]
I updated to 0.11.0, and my layout all broken. Seemed like layout="row" and layout="column" are all same now. I checked documents but there are nothing tells me breaking changes in layout except some class. Is there something which I missing?

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by topherfangio** [comment]
@oshko This may also be related: https://github.com/angular/material/issues/4520#issuecomment-138987281

Are you including ngMaterial as a dependency?
