### ISSUE TITLE
md-virtual-repeat-sizer should not calculate height based on the .md-autocomplete-suggestions li

### ISSUE THREAD

**Issue by mackelito** [angular/material#4522]
Hi, when working with the new autocomplete I see that virtual-repeater is used.. that's sweet! :)

But the height should not be calculated based on the height set in the css but rather on the actual height of the li.

In other words the li should not need height (or at least set it to auto)

**Comment by nestorneto** [comment]
and when we have li's with different sizes?

**Comment by mackelito** [comment]
My bad.. I meant all li's 😊
So based on the ul

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
