### ISSUE TITLE
Serious performance issues on some demos and doc pages

### ISSUE THREAD

**Issue by mbellezi** [angular/material#4523]
I'm experiencing some serious performance issues when trying to scroll the webpage when accessing the [Subheader Demo](https://material.angularjs.org/latest/#/demo/material.components.subheader) and the docs for [Child Alignment](https://material.angularjs.org/latest/#/layout/alignment).

I'm using Chrome 45 on MacOS.

Can anyone confirm this issue?

**Comment by mckenzielong** [comment]
I am seeing this too.  Seems to have popped up between .10.0 and .10.1.
