### ISSUE TITLE
Button styles broken on 0.11.0

### ISSUE THREAD

**Issue by langley-agm** [angular/material#4529]
After upgrading to the 0.11.0 version buttons seem really different from 0.10.1, the most noticeable change is that the font doesn't look bold anymore. Strangely enough you can't see this issue in the button's demo in the documentation but if you click in the codepen link you'll see they look really different even if they are supposed to be using the same version.

https://material.angularjs.org/0.11.0/#/demo/material.components.button

**Comment by schmkr** [comment]
Same thing for chips. See:

https://material.angularjs.org/0.11.0/#/demo/material.components.chips
vs
https://material.angularjs.org/0.10.1/#/demo/material.components.chips

**Comment by topherfangio** [comment]
Chips were changed in 565b7b46e564d78584cfa33da6a4e6c746cf09a1 to properly match the spec so that they work better with input elements.

However, I'm not seeing a difference between 0.10.1 and 0.11.0. They look identical to me (in Chrome at least). What browser are you using?

**Comment by langley-agm** [comment]
For the buttons I'm using Chrome, just open this link:
https://material.angularjs.org/0.11.0/#/demo/material.components.button
see how the buttons look, then click on the Edit on CodePen button and compare them.

**Comment by langley-agm** [comment]
I believe I found the issues (for the buttons).
1- Either the Button's CodePen example doesn't even have the Roboto font linked into the libraries or it isnt with the correct font name.
2- The button{ font-family } style selector in 0.11.0 changed from "RobotoDraft,Roboto,'Helvetica Neue',sans-serif" to "Roboto, 'Helvetica Neue', sans-serif".

So either change:
`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=RobotoDraft:300,400,500,700,400italic">`
for 
`<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">`
in the Getting Started page or change the selector in the css back to how it was:
```
button, html, input, select, textarea {
    font-family: RobotoDraft,Roboto,'Helvetica Neue',sans-serif;
}
```

**Comment by topherfangio** [comment]
@langley-agm The CodePen demos do not currently have Roboto linked. Since Roboto was released, we removed the draft version which does come with some changes that better follow the spec.

**Comment by langley-agm** [comment]
Might be a good idea to link them so they look the same way they do in the demos page and in the getting started page.

**Comment by langley-agm** [comment]
Might want to update the Getting Started guide as well to declare the font as Roboto and not RobotoDraft with versions over 0.11.0?
