### ISSUE TITLE
Wrong property name for ordering flex items

### ISSUE THREAD

**Issue by Konsi** [angular/material#453]
Please rename the property to just 'order' instead of 'flex-order'. I have stumbled over that by reading and testing the framework documentation under: https://material.angularjs.org/#/layout/grid

Specification: http://www.w3.org/TR/css-flexbox-1/#propdef-order

**Comment by marcysutton** [comment]
It is pretty clearly documented as `flex-order`. To minimize breaking changes at this point, I recommend we keep the attribute as-is.
