### ISSUE TITLE
md-select arrow disappeared in 0.11.0 (in Chrome)

### ISSUE THREAD

**Issue by schmkr** [angular/material#4533]
In the 0.11.0 release, the arrow drop down changed into a strange looking envelope. See:

https://material.angularjs.org/0.11.0/#/demo/material.components.select
vs
https://material.angularjs.org/0.10.1/#/demo/material.components.select

In Chrome that is, in Firefox and Safari, md-select still has the drop down arrow in 0.11.0

**Comment by topherfangio** [comment]
I don't see the strange looking envelope in Chrome; I still see the dropdown.

Can you clear your cache and see if that fixes the issue? If not, could you provide a screenshot? I'm assuming that a codepen won't show the issue, but if it does, it would certainly help us debug it :-)

**Comment by schmkr** [comment]
Emptied cache, still there:

https://dl.dropboxusercontent.com/u/808126/Fullscreen_11_09_15_07_45.png

**Comment by schmkr** [comment]
I also disabled every extension I had installed, to make sure none of them was causing the issue.

**Comment by topherfangio** [comment]
@schmkr Man, I can't seem to reproduce this and I've tried on Chrome, Firefox, Safari and IE Edge across OS X and Windows.

It uses the following character which is the down arrow: `▼`. Does this render as a down arrow in GitHub or are you seeing the envelope here too?

Can you try from another machine? I'm wondering if there might be something weird/different with your machine and/or fonts.

**Comment by schmkr** [comment]
Yes, I do see the down arrow in your comment, as well as on the documentation pages prior to 0.11.0.

**Comment by schmkr** [comment]
One of the differences between 0.10.1 and 0.11.0 I can find by looking in the network pane in Chrome Developer Tools,  is the former is using `RobotoDraft` whereas the later uses `Roboto`.

See also #4529 that references this subtle change, but it might be related.

**Comment by schmkr** [comment]
Okay, so this difference indeed was an issue on my machine, since I also had Roboto installed locally. However, that is (/was) version `2.000980; 2014`, whereas the version served from Google Fonts is `Version 2.001101; 2014`. Apparently my local version was missing this down arrow...

**Comment by topherfangio** [comment]
@schmkr lol! Love it when that happens; glad you got it resolved :-)
