### ISSUE TITLE
"md-button" Ink Effect Messes up When The button is low in the document

### ISSUE THREAD

**Issue by alexbooker** [angular/material#4536]
I am building a [**website**](http://communitycasts.co/) using *material*.

If you click on any button _above_ the social media buttons the button ink effect works fine:

![](https://i.imgur.com/lCGluxH.png)

However, if you click on any buttons _beneath_ the illustrated red line (such as the social media buttons), the ink effect has bugs:

- The ink offset seems off to me; and,
- The animation has a delay 

I am just wondering what the problem could be..?

I am running Chrome 45.0.2454.85 on Windows 10 64bit. The application is online [**here**](http://communitycasts.co) and is [**open source**](https://github.com/alexbooker/communitycasts.co) (in case you want to inspect further).

**Comment by robertmesserle** [comment]
This is resolved in 0.11.

**Comment by alexbooker** [comment]
@robertmesserle _Awesome!_
