### ISSUE TITLE
IE11 & Release 0.11.0: Layout - Demo site - Menu page

### ISSUE THREAD

**Issue by ptrenery** [angular/material#4539]
Basic usage section: text is not contained in the box.
Menu position modes section: content overlaps

![image](https://cloud.githubusercontent.com/assets/5481066/9788208/fc726e08-577c-11e5-859d-22f7402ac4fb.png)

**Comment by stevenmiles** [comment]
Some overlap with #3926

**Comment by ThomasBurleson** [comment]
To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
