### ISSUE TITLE
IE11 & Release 0.11.0: Menu - demo site

### ISSUE THREAD

**Issue by ptrenery** [angular/material#4540]
1. Menu content in center justified
2. Additional scrollbar appears on right when menu is open

![image](https://cloud.githubusercontent.com/assets/5481066/9788314/c265c272-577d-11e5-86d4-caf3bad6a1c8.png)

**Comment by rschmukler** [comment]
These are both fixed on master!

**Comment by ptrenery** [comment]
I tried the menu demo using the Head(Master) version today on the demo site and the scollbar issue is back. The menu alignment issue is fixed. This is in IE11.
