### ISSUE TITLE
md-toast: Parent not being recognized with md-toolbar layout

### ISSUE THREAD

**Issue by Londovir** [angular/material#4542]
Relevant CodePen: http://codepen.io/londovir/pen/QjjKEm

If you use an `$mdToast` where the parent isn't specified and the position of `top right`, it docks to the upper-right corner of the body, which is expected. If I use a `parent` element that is below that point, as you can see in my demo with the `Show Parented Toast` button, it isn't docking to the upper-right corner of that element. If I use a `parent` element that is absolutely positioned in the middle of the page, as you can see in my demo with the `Show Parented Floating Toast` button, it is docking correctly.

It is possible I'm doing something wrong with my layout in flex, but I cannot seem to get the toast to appear at the lower positioned `div` that is below the `md-toolbar`, which I'd like it to do since I don't wish to obscure the welcome message in the upper-right of the body. I have tried numerous combinations of the `parent` attribute to no avail.

Not sure if this is a bug in how `parent` determines the bounds for the element that is specified, or if the interimelement cannot "find" the element correctly, etc. I haven't had luck yet with single stepping the code to determine where my issue is falling once it gets into the interimelement code. This is happening in both Chrome and IE11.

**Comment by hulyav** [comment]
+1

**Comment by EladBezalel** [comment]
two things:
1. You don't need a to find the element yourself you can use the query selector ('#mainbodywindow' for example).
2. It seems that the problem is that the parent element position is not relative.

my suggestion for now is that you add to your css:
``` css 
#mainbodywindow {
  position: relative;
}
```

**Comment by hulyav** [comment]
Many thanks :)

**Comment by hulyav** [comment]
Thanks a lot :)

**Comment by Londovir** [comment]
@EladBezalel  Thanks for the `position: relative` suggestion. That has indeed corrected the behavior for now.

To anyone else reading, I would suggest that the documentation and/or demos be updated to show an example where the query selector string can be used instead of fetching the element. All documentation currently shows only type `element` as acceptable for the `parent` parameter of the dialog options.

**Comment by EladBezalel** [comment]
@ThomasBurleson should i make a PR that makes the parent relative?
