### ISSUE TITLE
Retain old value on focus out if result is not found <md-autocomplete>

### ISSUE THREAD

**Issue by ManiAkasapu** [angular/material#4543]
If the typed keyword did not exists, <autocomplete> is erasing the previous value. This is the major UX issue. It should retain the old value (if pre-selected and no results found for current value) 

Let me know if I am unclear.

**Comment by christrude** [comment]
Similar issue, no way to set the input content to a scope variable in case what you are typing is not found. You should be able to retain the content that is in the input that you typed already.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
