### ISSUE TITLE
md-dialog: IE11 / Edge blurry text and buttons after animating onto screen

### ISSUE THREAD

**Issue by Londovir** [angular/material#4544]
I don't have a ready CodePen for this at the moment, but I do have some screenshots of what I'm describing. When IE11 or Edge finishes animating in an `md-dialog` element, the resulting dialog appears fuzzy and blurred when compared to Chrome and Firefox:

![image](https://cloud.githubusercontent.com/assets/11982575/9791202/df0895b0-57a7-11e5-886c-bd300bcda979.png)
**IE 11 Image**

![image](https://cloud.githubusercontent.com/assets/11982575/9791216/f6400cb8-57a7-11e5-8325-e7827e524e87.png)
**Chome Image**

![image](https://cloud.githubusercontent.com/assets/11982575/9791265/270a9c64-57a8-11e5-8eab-42b9b375f912.png)
**Edge Image**

![image](https://cloud.githubusercontent.com/assets/11982575/9791307/58a99964-57a8-11e5-8018-c3978a87cae7.png)
**Firefox Image**

I imagine this is an artifact of the CSS styling that is done to animate the `md-dialog` into place, and it isn't likely to be something easy to fix or a high priority either. I just wanted to report it because in our limited testing for our apps here, we've been getting users reporting it (along with complaints about how they think their eyesight is going bad until they switch to Firefox or Chrome).

**Comment by teamshultz** [comment]
+1

**Comment by Bodom78** [comment]
Having the same issue on Windows 10 with IE11

**Comment by ryanespin** [comment]
+1

**Comment by Bodom78** [comment]
I'll also add that this issue does not occur for me when using IE11 in Windows 7

**Comment by Belicosus** [comment]
I am having the same problem on Win 8.1 and Win 10, but it also applies to the content of a sidenav directive. I'm currently trying to reproduce this in a codepen, but it's not looking good at the moment.

Problem is, that the demo's on the website doesn't seem to have the same issue.

**Comment by Bodom78** [comment]
Turns out the transform rule from transition in css is the cause.

Using IE's DOM explorer and removing or setting transform clears the bury text.

```
md-dialog.md-transition-in {
    transform: translate3d(0px, 0px, 0px) scale(1);
}
```

**Comment by Bodom78** [comment]
Using translate rather then translate3D also fixes the issue.

https://github.com/Polymer/core-list/pull/71

**Comment by jmrserrano** [comment]
-ms-transform:translateZ(0) scale(1.0, 1.0); not work is fuzzy used -ms-transform:translate(0) scale(1.0, 1.0); is solved
