### ISSUE TITLE
md-select with ng-if does not bind selected value to ng-model

### ISSUE THREAD

**Issue by williamweckl** [angular/material#4545]
If I have a `ng-if` condition on md-select, it does not bind the selected value to ng-model.

To exemplify: 
[with condition](http://codepen.io/anon/pen/qOORpg)

[without condition](http://codepen.io/anon/pen/eppgyM)

**Comment by williamweckl** [comment]
Noted that if `ng-if` is above `md-select` same problem happens.

**Comment by langdonx** [comment]
You should be using `controller as` these days to avoid scoping issues.

http://codepen.io/langdonx/pen/bVVqov

**Comment by williamweckl** [comment]
In my specific case here I have this md-select inside a directive, that's why I can't work with `controller as`. But, with your solution, came to my mind to try with `$parent` and it worked.

For me it's ok, but I still think I could access the parent scope directly, so, will maintain the issue open.

Thanks for the help.

**Comment by langdonx** [comment]
`controller as` works great in directives too.

**Comment by williamweckl** [comment]
Yes but I'm using the directive's controller and inside extending another one. In my case I can't have it on view.

**Comment by Eden-Sun** [comment]
If you dont like ```controller as```
how about this http://codepen.io/anon/pen/WQQEqL?editors=101

**Comment by rschmukler** [comment]
This is a scoping issue caused by `ng-if`. There's not much ngMaterial can do about it, but the suggestions in this issue are all good.
