### ISSUE TITLE
md-chips - unable to set to accent color

### ISSUE THREAD

**Issue by peffreycollins** [angular/material#4546]
There doesn't appear to be a way to have md-chips leverage the md-accent class. Are there any workarounds for applying this or plans to support this in a future version?    

Thanks.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
