### ISSUE TITLE
$mdDialog: locals not working!

### ISSUE THREAD

**Issue by aozora** [angular/material#455]
Hi,
The locals option for $mdDialog service is not working: how to pass objects to the dialog scope?

**Comment by thallukrish** [comment]
Thanks, a bit that can be easily overlooked looking at the example. 

Why do we have such roundabout way of passing parameters to mdDialog.show?

**Comment by christrude** [comment]
This still does't work for me. 
![dialogShow](https://cloud.githubusercontent.com/assets/2306523/7277278/2ce6433e-e8dd-11e4-88f2-98904e822503.png)

![controller code](https://cloud.githubusercontent.com/assets/2306523/7277293/39ca1846-e8dd-11e4-9154-37cba5be5317.png)

![error](https://cloud.githubusercontent.com/assets/2306523/7277310/4a85207c-e8dd-11e4-8b5a-1f2493ce9f5e.png)


Using 0.8.3

**Comment by jadjoubran** [comment]
Because it has an isolated scope.

"The dialog is always given an isolate scope." from https://material.angularjs.org/latest/#/api/material.components.dialog/service/$mdDialog

**Comment by gkalpak** [comment]
This isn't 100% accurate. You can pass your own scope (but if you don't then a new isolate scope will be created and used).

**Comment by assaftenen** [comment]
What about passing scope data from the dialog into the parent one?

**Comment by Vijay1990** [comment]
cool!
Work like a charm!!

**Comment by ViruSzZ** [comment]
Hello,

I'm not sure whether I'm doing something wrong but ``locals`` aren't working for me. I have the following:

    <md-button ng-click='listObjects.viewDetailsDialog($event, object)'>

and also this

    this.viewDetailsDialog = (ev, obj) => {
        $mdDialog.show({
          templateUrl: 'client/objects/list-objects/view-details.dialog.html',
          clickOutsideToClose: true,
          openFrom: {top: -50, width: 30, height: 80},
          closeTo: {left: 500},
          preserveScope: true,
          targetEvent: ev,
          locals: { item: obj }
        });
      }

the ``obj`` object isn't passed to ``view-details.dialog.html``. Any thoughts what I'm doing wrong?

**Comment by christrude** [comment]
3 things:

1. you have to declare a controller for the dialog (not sure if you are doing that from this example
2. you have to have ‘item’ in the controller dependency list ( .controller('CatalogCtrl', function ($scope, $http, $timeout, item){})
3. you have to set ‘item’ into the scope in the controller ( $scope.item = item;)


VR,

Chris Trude

**Comment by ThomasBurleson** [comment]
@ViruSzZ - Please look at  [`$mdDialog` Documentation](https://material.angularjs.org/latest/api/service/$mdDialog) to see how **locals** are used with controllers.
