### ISSUE TITLE
color inheritance depending on theme

### ISSUE THREAD

**Issue by 0101adm** [angular/material#4551]
ang mat 0.11.0

noticed text is either white or black in a toolbar depending on the theme.  is this on purpose?

this is changing the primary palette.

![screen shot 2015-09-10 at 2 06 55 pm](https://cloud.githubusercontent.com/assets/5133412/9799589/627f8724-57c5-11e5-8dd7-7013fd726850.png)
![screen shot 2015-09-10 at 2 05 31 pm](https://cloud.githubusercontent.com/assets/5133412/9799591/628319a2-57c5-11e5-9e9b-8847dc9b9f8f.png)
![screen shot 2015-09-10 at 2 06 05 pm](https://cloud.githubusercontent.com/assets/5133412/9799592/62837208-57c5-11e5-8ea9-4e12d5601c57.png)
![screen shot 2015-09-10 at 2 06 28 pm](https://cloud.githubusercontent.com/assets/5133412/9799590/628178ae-57c5-11e5-9ba9-e4b83b803bbe.png)

**Comment by krijoh92** [comment]
Yeah, this made me either have to change from 'light-blue' to 'blue' as primary in my theme, or do this:
 ```
      var lighterBlue = $mdThemingProvider.extendPalette('light-blue', {
        'contrastDefaultColor': 'light'
      });

      $mdThemingProvider.definePalette('lighter-blue', lighterBlue);

      $mdThemingProvider.theme('default')
        .primaryPalette('lighter-blue')
        .accentPalette('indigo');
```

**Comment by rschmukler** [comment]
@0101adm it is indeed intentional. Check out the [color palette](https://www.google.com/design/spec/style/color.html#color-color-palette) to see when font will be light or dark.
