### ISSUE TITLE
ripple shows for disabled components

### ISSUE THREAD

**Issue by ngraef** [angular/material#4554]
*0.11.0 and master*

Interacting with a disabled [checkbox](https://material.angularjs.org/HEAD/#/demo/material.components.checkbox), [switch](https://material.angularjs.org/HEAD/#/demo/material.components.switch), [radio button](https://material.angularjs.org/HEAD/#/demo/material.components.radioButton), or [icon button](https://material.angularjs.org/HEAD/#/demo/material.components.button) shows ripple.

**Comment by robertmesserle** [comment]
closed by https://github.com/angular/material/commit/313342cfef6ccf77e745252d9ef589dc551f0323

(typo in commit message)
