### ISSUE TITLE
md-center-tabs does not work with md-dynamic-height

### ISSUE THREAD

**Issue by amitport** [angular/material#4555]
using 0.11.0 and angular 1.4.5

**Comment by YasserRabee** [comment]
+1
using 0.11.4 and angular 1.4.7

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
