### ISSUE TITLE
mdMenu and mdMenuBar's menus don't work with ngRepeat menu items

### ISSUE THREAD

**Issue by jztein** [angular/material#4557]
Cascaded menus when just using md-menu, or when using md-menu-bar, do not close sub menus when using ng-repeated menu items.

Reproduction:
Open a sub menu, and try to open another sub menu. The none of the sub menus close until a leaf item is selected.
http://codepen.io/anon/pen/PPPpOJ

Also doesn't work when using ngInclude templates.

**Comment by EladBezalel** [comment]
dup #4484
