### ISSUE TITLE
$mdOpenMenu is undefined

### ISSUE THREAD

**Issue by Ebtessam** [angular/material#4559]
this is my HTML:
<div ng-controller="NavbarController as vm" layout="column" layout-fill>
  <md-toolbar>
    <div class="md-toolbar-tools">
      <span>Le3bKora</span>
      
      <span flex></span>
      <md-menu>
         
         <md-button ng-click="$mdOpenMenu()"aria-label="Open sample menu">
           Profile
         </md-button>
         <md-menu-content>
           <md-menu-item><md-button ng-click="doSomething()">Do Something</md-button></md-menu-item>
         </md-menu-content>
        </md-menu>
    </div>
  </md-toolbar>
</div>

this is my controller currently useless:
(function() {
    'use strict';
    angular
        .module('app.layout.controllers')
        .controller('NavbarController', NavbarController);
    /* @ngInject */
    NavbarController.$inject = ['$scope' ];
    function NavbarController($scope) {
        var vm = this;
        // var originatorEv;
        activate();
        ////////////////
        function activate() {
        }
    }
})();

I am getting an AngularJS error  $mdOpenMenu is undefined

Thanks,

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
