### ISSUE TITLE
Unable to load with AMD approach

### ISSUE THREAD

**Issue by ertrzyiks** [angular/material#456]
I think it would be nice to be able load lib script with AMD loaders. Fact that currently its expected to have `Hammer` defined in global namespace is a blocker, even for requirejs shim feature. This problem may be related to issue #317, since issue will disappear or will change cause after applying Hammer replacement.

To use angual-material with requirejs i ended up with hack like this

```js
    //libs/hammer-proxy.js
    define(['../bower_components/hammerjs/hammer'], function (Hammer) {
        this.Hammer = Hammer;
        return Hammer;
    });

    //main.js
    require.config({
        paths: {
            'hammerjs' : 'libs/hammer-proxy',
```

**Comment by ajoslin** [comment]
We'll be removing HammerJS as a dependency soon; deferring this to 0.7.1.

**Comment by capaj** [comment]
@ajoslin you will? That is great news, because I have simmilar problem when using [jspm](http://jspm.io/)/[systemjs](https://github.com/systemjs/systemjs) and dropping the dependency would solve the issue. Until then I just do window.Hammer = require('hammer.js');

**Comment by ajoslin** [comment]
Hammer's gone now in master!

**Comment by ilanbiala** [comment]
:+1:
