### ISSUE TITLE
Dialog: secondary text opacity improvements

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4566]
*  Secondary text should be 54% opacity. 

![dialog_secondarytextopacity](https://cloud.githubusercontent.com/assets/210413/9816041/faf9ffee-585f-11e5-892d-81eab28737df.png)

*  Alert dialog has the hover state present all the time

![alerthoverstate](https://cloud.githubusercontent.com/assets/210413/9816010/ddc3e548-585f-11e5-8836-b49c0471d74a.png)

**Comment by topherfangio** [comment]
@ThomasBurleson Can you explain the second bullet a little bit more? I'm not sure I understand it.
