### ISSUE TITLE
Ripple effect on card

### ISSUE THREAD

**Issue by vinz243** [angular/material#457]
How to do so? Or is it not respectful of  md specs

**Comment by MarcosPortugal** [comment]
Oh so this is getting documented after all! Awesome :)

**Comment by marcysutton** [comment]
In the spec for Cards, the **primary action is the card itself**. That action has to be accessible from keyboards and screen readers. It's invalid to nest multiple button elements (the browser actually "fixes" them for you), and it doesn't make sense to add `role="button"` to `md-card` when it will have secondary actions inside of it. The best approach is to wrap the card's text content in a button for the primary action, and position a secondary action as a button on top of it. Here is a quick markup demo: http://codepen.io/marcysutton/pen/VYpjQz

**Comment by MarcosPortugal** [comment]
@marcysutton There should be two distinct types of cards then - ones with a primary action, and the ones without it (both of them can have or not secondary actions, that is irrelevant)

**Comment by ThomasBurleson** [comment]
@robertmesserle - have our docs been updated to add an effects section to document ripple and samples?

**Comment by aeroxy** [comment]
How could I apply the ripple similar to ones on the tab? https://material.angularjs.org/#/demo/material.components.tabs
