### ISSUE TITLE
Input - demo tweaks

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4570]
* animated input fields should never move down. the label is the only thing that should move, up. noticed in the Icons section at the bottom. inputs should always be contained within a set row height, when they animate, they should stay within that row height so that nothing else on the page moves.  
* weird how titles animate when you arrive on this page.
* date picker never fits on screen, icon on date picker shouldn't move.

![screen shot 2015-09-11 at 8 43 09 am](https://cloud.githubusercontent.com/assets/210413/9816211/22326cf8-5861-11e5-9ab3-763a07de6957.png)

**Comment by topherfangio** [comment]
Your second bullet is also being tracked in #4258.

**Comment by topherfangio** [comment]
Second bullet is fixed in #4623.

**Comment by topherfangio** [comment]
First bullet looks fixed; PR incoming for bullet 3 (datepicker).
