### ISSUE TITLE
Update the Codepen Demo.

### ISSUE THREAD

**Issue by piyushchauhan2011** [angular/material#4571]
Update the Codepen Demo to use Angular Material `0.11.0`.

![screen shot 2015-09-11 at 11 43 24 pm](https://cloud.githubusercontent.com/assets/693487/9816233/07fd9bfe-58df-11e5-8cfd-04c066cdff1b.png)

**Comment by ThomasBurleson** [comment]
The trick here is for each release to synchronize the CodePen libraries with that release version:
eg

*  Release v0.11.0 will use https://gitcdn.xyz/repo/angular/bower-material/v0.11.0/angular-material.js
*  Head/Master will use https://material.angularjs.org/HEAD/angular-material.js
*  Next Release v0.11.1 will use https://gitcdn.xyz/repo/angular/bower-material/v0.11.1/angular-material.js

This has been fixed.
