### ISSUE TITLE
MenuBar - animation and overlay improvements

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4572]
*  animate out should happen quicker. 
*  menus should not overlay.

![screen shot 2015-09-11 at 8 45 00 am](https://cloud.githubusercontent.com/assets/210413/9816248/693bec14-5861-11e5-85e4-50989b1d1391.png)

**Comment by rschmukler** [comment]
Per the spec menus are allowed to overlay if they run out of space. Animation should be sped up.
