### ISSUE TITLE
Sliders: focus and state improvements

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4576]
MDL implements correct size of normal and click states:  http://www.getmdl.io/components/index.html#sliders-section

- sliders do not need hover.
- sliders only have ripple ring on tab focus
- on release, slider should go back to default static state.
- input field on the right could be material inputs

![screen shot 2015-09-11 at 8 51 59 am](https://cloud.githubusercontent.com/assets/210413/9816399/5ffed570-5862-11e5-8bcb-f61d1949eb35.png)

**Comment by EladBezalel** [comment]
@ThomasBurleson by the spec slider do need hover,
The initial thumb size is 12px, on hover it's 14px

**Comment by ThomasBurleson** [comment]
Fixed with SHA e0abeb4dc46a1753616a911fe54f14d8f1148a25
