### ISSUE TITLE
Select: focus and ink tweaks

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4577]
- after selection, ripple makes animation seems very jittery, recommend removing ripple from this component. Might be ok with better ripple implemntation.
- missing focus state on selected item

![screen shot 2015-09-11 at 8 53 18 am](https://cloud.githubusercontent.com/assets/210413/9816422/90257aa6-5862-11e5-9afb-785fbe2c4ed6.png)

**Comment by rschmukler** [comment]
These are resolved in RC1
