### ISSUE TITLE
SideNav: add missing behaviors

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4578]
- sidenav behaviors are much more diverse than this. [Patterns > Navigation Drawer > Behaviors](https://www.google.com/design/spec/patterns/navigation-drawer.html)

![screen shot 2015-09-11 at 8 55 32 am](https://cloud.githubusercontent.com/assets/210413/9816475/df00d1a2-5862-11e5-8941-70d53eba855c.png)

**Comment by DmitryEfimenko** [comment]
The link should probably be [linking to this](https://www.google.com/design/spec/patterns/navigation-drawer.html).

[This issue](https://github.com/angular/material/issues/2197) is also probably relevant.

**Comment by mackelito** [comment]
A "mini" version of sidenav for desktop would be super! :)

**Comment by ThomasBurleson** [comment]
This is rel https://github.com/angular/material/issues/2197
