### ISSUE TITLE
Ripples: performance improvements needed

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4580]
- ripples throughout seem slow, and too complex.
- ok for now, but Material team will look into ripples on the web in the next few weeks and share a final ripple spec based off of
https://drive.google.com/a/google.com/folderview?id=0B6JAwBNCM1RBNjdMUWlicTNRX2c&usp=asogm-

**Comment by robertmesserle** [comment]
@ThomasBurleson I'm not sure how much more performance we're going to get out of the current ripples, but that doc DID mention removing the background color part of the ripples, which should help.

**Comment by ThomasBurleson** [comment]
Should we update the Ripple code to remove `background-color` ?

**Comment by robertmesserle** [comment]
Definitely

**Comment by ali-alamine** [comment]
I just noticed that the ripple is especially slow when changing views (tested with slow devices). Actually it's the only time when I am noticing any lag with it. So disabling ripples from the navigation menu should solve this in case no more improvements can be made.
