### ISSUE TITLE
Switch: animation speeds

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#4581]
- switch animation feels slow
- Polymer swtich is the right speed.

@see https://elements.polymer-project.org/elements/paper-toggle-button?view=demo:demo/index.html

![screen shot 2015-09-11 at 9 00 20 am](https://cloud.githubusercontent.com/assets/210413/9816583/88f84820-5863-11e5-9182-707ec079d991.png)

**Comment by EladBezalel** [comment]
Also it seems that the shadow of the thumb is not as [polymer](https://elements.polymer-project.org/elements/paper-toggle-button?view=demo:demo/index.html) and [material spec](https://www.google.com/design/spec/components/selection-controls.html#selection-controls-switch)
