### ISSUE TITLE
md-contact-chips demo not showing autocomplete popup correctly

### ISSUE THREAD

**Issue by jasonhenderson** [angular/material#4599]
The items are selectable (with enter working now, too--thank you), however, the item details are missing in the autocomplete popup. See image below. This behavior is reproducible outside the demo.

<img width="982" alt="screen shot 2015-09-11 at 11 12 46 am" src="https://cloud.githubusercontent.com/assets/1524622/9822609/29ecf6d8-5876-11e5-8637-d427b21a086c.png">

**Comment by topherfangio** [comment]
This has been fixed in #4391 and was merged a few minutes ago. You can see the most up-to-date version here: https://material.angularjs.org/HEAD/#/demo/material.components.chips
