### ISSUE TITLE
How to make tabs full width

### ISSUE THREAD

**Issue by zoran119** [angular/material#460]
I have only two tabs in `md-tabs` and want them to take up the whole screen width (half each, see pic2). How can I do that (by default it looks like pic1)?

```
pic1
------------------------------------------------
| ITEM1 | ITEM 2 |
------------------------------------------------

pic 2
------------------------------------------------
|         ITEM1        |          ITEM 2       |
------------------------------------------------
```

**Comment by aeroxy** [comment]
Instead of using `<md-tabs md-stretch-tabs="yes">`, we should now simply use `<md-tabs md-stretch-tabs>`.

**Comment by sagar-ganatra** [comment]
I tried this today and it didn't stretch the tabs with me-stretch-tabs="yes", instead of 'yes' specify the value as 'always'.

**Comment by masaitseweng** [comment]
Thanks guys for your help it works.
