### ISSUE TITLE
0.11.0 md-contact-chips bug

### ISSUE THREAD

**Issue by alphatwit** [angular/material#4601]
The dropdown list of contacts no longer displays any of the contact information. Clicking the empty square still fills the input correctly. There is also an unsightly scrollbar in the list even if there is only one match.

https://material.angularjs.org/0.11.0/#/demo/material.components.chips

**Comment by zevmo** [comment]
<img width="876" alt="screen shot 2015-09-13 at 9 13 27 am" src="https://cloud.githubusercontent.com/assets/2286035/9836866/cf3fa1c6-59f7-11e5-805d-6179ee06cb60.png">

**Comment by topherfangio** [comment]
Closing duplicate. The empty square issue was fixed by #4391 (which will be available in 0.11.1) and the scrollbar is being tracked in #4308.
