### ISSUE TITLE
md-menu rendered with ng-repeat

### ISSUE THREAD

**Issue by f1tech** [angular/material#4602]
I'm using Angularjs with Angular Material and I have an md-menu that's opened when an md-button is clicked. I render the menu with an ng-repeat that looks like this:

            <md-menu-item ng-repeat="item in orderItem.searchItems">
                <md-button ng-click="orderItem.searchMenuHit($event, '{{item.field}}')">
                    {{item.caption}}
                </md-button>
            </md-menu-item>
If I right click on a menu item and inspect it with the debugger, it shows ng-click as orderItem.searchMenuHit($event,'STK_NUM') which is what I expect.

When orderItem.searchMenuHit gets called it receives '{{item.field}}' as a literal string rather than STK_NUM as I'd expect. 

I'm not sure why this is, or how to address it.

**Comment by paulflo150** [comment]
You should use: ng-click="orderItem.searchMenuHit($event, item.field)" - you're essentially passing back a string to your function by including the value in quotes.

**Comment by f1tech** [comment]
Um, no. Angular expressions can be nested in quotes and I need the quotes to be included in the HTML that is generated. I want to pass the contents of item.field as a string to the searchMenuHit method. If the quotes are omitted then JavaScript will look for a variable of that name.

**Comment by jelbourn** [comment]
@paulflo150 is right; you are specifying a string literal `"{{item.field}}"`. See this simplified example: http://jsbin.com/xicona/edit?html,js,output
