### ISSUE TITLE
docs: provide a kitchen sink (all components on one page)

### ISSUE THREAD

**Issue by flowersinthesand** [angular/material#4605]
Now if someone new to Angular Material starts learning it, they will probably visit Introduction page to find out what it is, Getting Started page to try it out and each component page to use it to start their work.

From my experience, before diving into components, figuring out what components are included visually wasn't easy. The 'kitchen sink' page which contains every component can help that for sure as a bridge page between getting started page and each component page, but also it can impress the people who hesitate to introduce Angular Material.

One of good examples of such kitchen sink is Foundation - http://foundation.zurb.com/docs/components/kitchen_sink.html

**Comment by EladBezalel** [comment]
IMHO it's not that necessary you can find any component in the docs.

**Comment by dmackerman** [comment]
More than a kitchen sink, it's more about how to use the components *together*, which is something the docs don't address. Apps aren't just components that live on their own, unfortunately.

**Comment by EladBezalel** [comment]
For that you can see [Material Up](https://www.materialup.com)
Or wait for #4473

**Comment by flowersinthesand** [comment]
Just FYI, I made it using existing demos under my account using GitHub Pages: http://flowersinthesand.github.io/material/#/kitchen-sink

**Comment by DarrylD** [comment]
I see no reason why this can't be put in the docs. Helps to scan through available components to opposed to clicking each.
