### ISSUE TITLE
OSX/Chrome: md-primary color changes when right clicking / putting external app on top of it

### ISSUE THREAD

**Issue by jascination** [angular/material#4606]
Having a bizarre glitch using both v0.10.0 and v0.11.0. 

When I right click on/near anything, or place an external app's window over my Chrome window on Angular Material, the colour glitches.

No need for a demo, I can do this on the Angular Material website, simply by right clicking in the left menu bar in Chrome. You can see the colour of the menu bar changes where the right-click menu was. Unfortunately, screenshotting this doesn't work, but the colour change is coming up on DigitalColourMeter. Here's an example from my website:

![Angular Material UI Color Glitch](http://i.imgur.com/CntS53j.png)

Also happens when I drag the Digital Colour Meter window on top of Chrome, on top of the sidebar block.

I'm on the 2015 Macbook Air if it makes any difference. I can't see this happening on any other websites, only ones with Angular Material.

Very weird one. Can anyone else reproduce this? Hopefully it's not an issue with my laptop's GPU...

**Comment by topherfangio** [comment]
Just tested on my Macbook Pro running El Capitan (beta) and I'm not seeing this. But if the color changes in Digital Color Meter, I have a hard time thinking it's a graphics card glitch...

Perhaps a bug in Chrome? What happens if you reproduce the issue and then scroll/hide the content and bring it back into view? I'm wondering if Chrome is just rendering it funny and if "refreshing" will fix it.

**Comment by jascination** [comment]
Moving my cursor around or clicking on the element makes the colour return to normal. 

Just tested in Firefox on the same computer, and the issue is not happening - so a bug with Chrome. I've never had this happen on any other website, only ones made with Angular Material. Bizarre.

Also, not sure if related - the colours that `md-primary` are rendering are different on Chrome and Firefox:

![Firefox vs Chrome different colour angular material ui](http://i.imgur.com/Xg1jV6n.png)

Something funky's going on....

**Comment by jascination** [comment]
Ok! Found a solution to this. 

Realised it was also happening on [Google's Material Design Colour Page](http://www.google.com/design/spec/style/color.html#color-color-palette) as well. 

From doing a bit of searching around, I realised that the problem went away when I disabled `f.lux` - didn't even realise it was on during the day! Now the problem has resolved. Restarting Chrome might be necessary as there's some colour profile biz it does on OSX.

**Comment by jascination** [comment]
Actually scratch that, after having Chrome open for a couple of minutes the problem returns. Any ideas here?

**Comment by topherfangio** [comment]
Does it happen on any other browser (Firefox/Safari/Etc)? Can you tell us what version of Chrome you're using?

Also, any chance you could try on a different machine? This really sounds like a graphics card issue or a bug in Chrome though.

**Comment by jascination** [comment]
Chrome Version 45.0.2454.101 (64-bit) on Mid-2015 Macbook Air

Doesn't happen in Safari or Firefox.

Just had a friend test on his Macbook Pro in Chrome - Same thing happens. Gonna have a few more friends check tonight.
