### ISSUE TITLE
Theme for headings.

### ISSUE THREAD

**Issue by kimmoah** [angular/material#4607]
Hi.

How can I use md-primary color with `<h1>` tag and md-title class?

I tried something like

    <h1 class="md-title md-primary">TITLE</h1>

But, the color theme is not applied.

Actually, I would like to make similar to https://www.google.com/design/spec/style/typography.html#

Thanks!

Youngjin

**Comment by EladBezalel** [comment]
I suggest you read [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/) and edit your issue so we can understand what you're trying to do.

**Comment by mckenzielong** [comment]
There is a pull request open for themes on other elements.  See this pr: https://github.com/angular/material/pull/1599

**Comment by topherfangio** [comment]
@EladBezalel Updated original question real fast to be readable.
