### ISSUE TITLE
Templates for angular-material?

### ISSUE THREAD

**Issue by vijayrawatsan** [angular/material#4608]
Are there any website/admin templates using angular-material framework. For example templates using bootstrap are available.

**Comment by idpokute** [comment]
If you are not looking for free, there are several admin templates such as following: 
http://themeforest.net/item/materil-angular-material-design-admin-template/11062969

**Comment by vikasprogrammer** [comment]
You can try here as well - https://www.xtendify.com/en/templates/angularjs-material/

**Comment by vijayrawatsan** [comment]
Thanks guys, but these are very few to choose from. Plus the themeforest one includes bootstrap and jquery as well.

**Comment by carlosafonso** [comment]
This one is also built over angular-material. It also comes with some custom components built on top of it:

http://triangular.oxygenna.com/#/dashboards/analytics

**Comment by ThomasBurleson** [comment]
@here - Please continue conversation in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial). 

This is a duplicate of  #4473
