### ISSUE TITLE
md-slider default value not rendered correctly on ng-repeat

### ISSUE THREAD

**Issue by sonnylazuardi** [angular/material#461]
md-slider default value not rendered correctly on ng-repeat, but when I move one of the slider or change from the input text, it will render correctly as the value changed.

![ss](http://i655.photobucket.com/albums/uu275/sonnylazuardi/Capture-4.jpg)

**Comment by Arti3DPlayer** [comment]
Still not works:
```
<md-slider-container flex ng-repeat="n in tpakp track by $index">
                            {{tpakp[$index]}}
                            <md-slider ng-model="tpakp[$index]" ng-change="tpaSliderChange($index)" min="0" max="200" aria-label="{{ 'tpakp'+$index }}" class="md-accent" md-vertical md-range></md-slider>
                        </md-slider-container>```

![screen shot 2017-05-05 at 13 12 17](https://cloud.githubusercontent.com/assets/3278913/25741676/81e171ae-3194-11e7-8d81-e5c96a76b9bc.png)


```
"angular": "1.5.9",
        "angular-animate": "1.5.9",
        "angular-aria": "1.5.9",
        "angular-chart.js": "1.1.1",
        "angular-cookies": "1.5.9",
        "angular-material": "1.1.0",
        "angular-messages": "1.5.9",
        "angular-resource": "1.5.9",
        "angular-route": "1.5.9",
```
