### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by kononenko-a-m** [angular/material#4610]
Hey!

I've checked out date picker in latest release, and can't find any UI controller for changing monthes/years on desktop.

**Comment by csvan** [comment]
+1

**Comment by kononenko-a-m** [comment]
In material design https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers there are present UI controllers for desktop

**Comment by EladBezalel** [comment]
You should take a look at #648, #4467 and #4217
