### ISSUE TITLE
md-menu-bar: md-menu-content wrongly placed inside of md-tab

### ISSUE THREAD

**Issue by frapontillo** [angular/material#4613]
When putting a `md-menu-bar` inside a `md-tab-body` of a `md-tabs`, by clicking on a `md-menu` button, the `md-menu-content` (the menu item sub-list) is wrongly placed at the center of the tab, and not next to the button that triggered it open.

To replicate this, I have forked the [menu bar demo](https://material.angularjs.org/latest/#/demo/material.components.menuBar) at [this codepen](http://codepen.io/frapontillo/pen/JYGjRv) and simply put the whole thing inside a tab, then add some more text on top of the tab.

It looks like the `div.md-open-menu-container` is placed using relative positioning from the triggering element, while it should be based on absolute positioning with regards to the whole document.

This is the outcome:
![screenshot 2015-09-13 18 34 23](https://cloud.githubusercontent.com/assets/1140238/9837640/2beab8b8-5a46-11e5-8071-a3aa04793b7d.png)

This happens with angular-material 0.11.0.

**Comment by brianpkelley** [comment]
+1 can confirm

**Comment by frapontillo** [comment]
I really think it's an issue with the tab system, since my `ui-ace` directive places error tooltip in the same errored way, when the directive is placed inside `md-tabs`.

**Comment by rschmukler** [comment]
Thanks for the fantastic bug report. Fixed!

**Comment by frapontillo** [comment]
Yay for one liners! :bomb:

**Comment by gbruins** [comment]
Found the same issue when using <md-menu-bar> inside a <md-dialog>:
http://codepen.io/anon/pen/zvepRE

**Comment by gbruins** [comment]
@rschmukler  - Hi Ryan - #5765 seems to be related to this ticket.  Do you agree?  Hoping this can get into 1.0.0 RC7.    Thanks!
