### ISSUE TITLE
md-select forces number-like string values to be numbers

### ISSUE THREAD

**Issue by richardszalay** [angular/material#4615]
PR #3560 introduced a breaking change that causes number-like values (eg. "0930") to be parsed as numbers.

The problem is the PR uses `isNaN(value)` to determine whether the value is a string, but `isNaN("0930")` returns true. I propose modifying this to use `typeof value == "number"` instead, as it resolves correctly against the above test values.

**Comment by richardszalay** [comment]
Update: while a breaking change was definitely introduced in 0.11.0, I'm actually repro'ing the problem even without #3560.

I'm going to work around it for now, but if anyone else wants to take a look here's a test:

```
it('should not convert number-like strings to numbers', inject(function($compile, $rootScope) {
    $rootScope.value = 1;
    $compile('<md-select ng-model="value">' +
      '<md-option ng-repeat="value in [\'01\', \'02\', \'03\']" value="{{value}}">{{value}}</md-option>' +
      '</md-select>')($rootScope);
    $rootScope.$digest();
    expect($rootScope.value).toBe('01');
  }));
```

**Comment by bluebirdtech** [comment]
+1 I've just started seeing this as well for eg. 3030.57 after upgrading to 0.11.0

**Comment by mjhasbach** [comment]
+1

@richardszalay You might consider updating the issue description from:

> PR #3560 introduced a breaking change that causes number-like values (eg. "0930") to be parsed as **strings**.

to

> PR #3560 introduced a breaking change that causes number-like values (eg. "0930") to be parsed as **numbers**.

**Comment by richardszalay** [comment]
Well caught @mjhasbach. Corrected!

**Comment by bluebirdtech** [comment]
++1 this just bit me again!

**Comment by rschmukler** [comment]
Demo codepen [here](http://plnkr.co/edit/sJILIrehFcrigQr8ajGF?p=info). 

We should likely revert the change introduced as it is counter to how Angular's native select behaves. With angular's select, the `value` attribute is always a string, and `ng-value` can be used for any non-string value. [Docs here](https://docs.angularjs.org/api/ng/directive/select)

**Comment by richardszalay** [comment]
@rschmukler I wouldn't be so hasty in closing the issue - as I mentioned in my follow up comment, I was able to reproduce the bug even without the changes introduced by #3560.

**Comment by NBurke1** [comment]
Still an issue, I'm currently trying to use a delimited string of numbers as my ng-value and it's giving NaN errors. It appears to be trying to read it as a number instead of a string.
