### ISSUE TITLE
flex-sm="100" causes items to stack on iOS

### ISSUE THREAD

**Issue by nikkwong** [angular/material#4616]
On my iPhone, flex-sm="100" is causing items to stack on top of each other as the flex'ed divs have no height. I can only get it to work if I change the CSS to 

-webkit-flex: 0 1 auto;
    -ms-flex: 0 1 auto;
        flex: 0 1 auto;

**Comment by nikkwong** [comment]
It might be good to note that declaring ```flexbox``` with mobile-first in mind causes flexed items to be displayed correctly on iOS. 

I seem to only have the issue on flexed divs that have images as children, not certain what the cause is—but, for example: 

    <div layout="row">
          <div flex>
               <p>asdf</p>
          </div>
        <div flex-gt-md="25" flex-md="50" flex="100">
             <img src="#">
        </div>
    </div>

works as expected, as ```flex``` only applies to the ```<600px``` viewport. 

But 

    <div layout="row">
          <div flex>
               <p>asdf</p>
          </div>
          <div flex="25" flex-md="50" flex-sm="100">
             <img src="#">
        </div>
    </div>

Does not work, on iOS. It will cause the divs to be collapsed on top of each other. It may be worth noting in the docs that declaring ```flex``` with the mobile viewport in mind and other flex attributes (flex-gt-md or flex-gt) for larger viewports.

**Comment by ThomasBurleson** [comment]
If you provide a CodePen, this would help us easily validate fixes for ngMaterial Layout/Flexbox

**Comment by jascination** [comment]
I'm gonna post this on a bunch of similar issues raised here, as I've searched far and wide for a solution to this - it's still an issue in Safari on IOS, you can see it in "responsive mode" if you're on desktop safari.

The solution is to add `flex: 1 0 auto !important;` to the parent layout elements that are not correctly being filled to their children's heights. The `!important` may not be necessary, up to you.
