### ISSUE TITLE
md-autocomplete open empty drop-down when default searchText exist.

### ISSUE THREAD

**Issue by shyr** [angular/material#4618]
When default value of `selectedItem` exist (not null), every deletion a character of the default value keeps the empty drop-down open.

CODEPEN : http://codepen.io/anon/pen/YywqBv

![image](https://cloud.githubusercontent.com/assets/7446428/9847617/28993c1e-5b15-11e5-843a-2b03af7e8c14.png)

**Comment by julbr** [comment]
+1 
The dropdown is also showing an empty line if the searchText is not found.
