### ISSUE TITLE
Form controls responsive

### ISSUE THREAD

**Issue by douwevdijk** [angular/material#4620]
The form controls directives (e.g. md-switch and / or checkboxes ) are very small on mobile devices, making it impossible for a user to use them ( unless you have small fingers :)). How can I make them larger or bigger.

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

---

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
