### ISSUE TITLE
layout attribute no longer works with ng-attr in 0.11.0 or using a variable

### ISSUE THREAD

**Issue by langan** [angular/material#4622]
When you use the following markup

```HTML
<div ng-attr-layout="{{vm.widgetLayout}}"></div>
```

The div gets assigned the class

```
layout-{{vm.widgetLayout}}
```

I've added some karma tests to look for this, would be happy to fix it if someone can give me some pointers on the best way to evaluate the attribute in layout.js

Pretty sure its line 165 of layout.js that needs to change

```JS
element.addClass(className + "-" + attr[directive].replace(/\s+/g, "-"));
```

attr[directive] needs to be evaluated I think

**Comment by carlosafonso** [comment]
Could this somehow be related to #4520?

**Comment by langdonx** [comment]
All the layout/flex attributes are now directives that just populate classes on the element for you.  This was done to fix performance in IE11 (where it suffered using so many attribute selectors).  Is there some reason you're needing to use ng-attr?  If so, I would switch to using the material layout classes for now.

**Comment by langan** [comment]
We can drop the ng-attr I suppose but shouldn't the layout directive work with a variable.

I made a quick test using a variable to change the layout from row to column and the classes aren't updated

```HTML
<div ng-init="layout = 'column'">
    <div layout="{{layout}}">
        <span>Top</span>
        <span>Bottom</span>
    </div>

    <md-button ng-click="layout='row'">Row</md-button>
    <md-button ng-click="layout='column'">Column</md-button>

    <code>{{ layout }}</code>
</div>
```

**Comment by jelbourn** [comment]
@ThomasBurleson was it ever the intent to support dynamic layouts via data binding?

**Comment by ThomasBurleson** [comment]
@jelbourn - Originally, no... The pending PR, however, has support for dynamic attribute values.

**Comment by langan** [comment]
@jelbourn The comment in layout.js suggests that this was planned to work

```JS
          /**
           * After link-phase, do NOT remove deprecated layout attribute selector.
           * Instead watch the attribute so interpolated data-bindings to layout
           * selectors will continue to be supported.
           *
           * $observe the className and update with new class (after removing the last one)
           *
           * e.g. `layout="{{layoutDemo.direction}}"` will update...
           */
```

**Comment by ThomasBurleson** [comment]
This has been fixed and will be merged into master soon.

**Comment by ThomasBurleson** [comment]
See SHA 7264cab40349
