### ISSUE TITLE
Help with layouts!

### ISSUE THREAD

**Issue by seemsindie** [angular/material#4624]
Hello guys, this is not an issue, but me being stupid. I am having really hard time achieving this layout:
![](http://i.imgur.com/2UOGwYU.png)
I tried:

    <md-content flex="30" class="chat-list">
    </md-content>
    <div flex="70">
        <div layout="column">
            <div flex="80">
                [flex]
            </div>
            <div flex="20">
                [flex]
            </div>
        </div>
    </div>

And some variations of this layout, but with no luck. I can solve this in css with old style techniques, but i want to use these directives, flex, layouts...
Any ideas how i can do this?

**Comment by EladBezalel** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
