### ISSUE TITLE
Unable to use autocomplete scrollbar in IE

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [angular/material#4625]
It's currently not possible to use the scrollbar shown in the autocomplete list when using IE, it loses focus and disappears.

![Screen recording](http://i.imgur.com/73Ao3of.gif)

**Comment by gfribeiro** [comment]
This problem still happens in IE11 with version 1.1.5

**Comment by erikwlarsen** [comment]
+1, still having this issue in IE11 with angular-material 1.1.10

**Comment by Splaktar** [comment]
@erikwlarsen please open a new issue with a CodePen reproduction.
