### ISSUE TITLE
mdSidenav: animation is broken when used inside ng-include

### ISSUE THREAD

**Issue by AleksueiR** [angular/material#4626]
Sidenav no longer animates when loaded using ng-include.

Working plunk: http://plnkr.co/edit/CtHRol?p=preview
Broken plunk (same code with with ng-include): http://plnkr.co/edit/B2UlCu?p=preview

Using
1.4.5/angular
1.4.5/angular-animate
1.4.5/angular-aria
HEAD/angular-material

Thanks.

**Comment by EladBezalel** [comment]
What's your angular version?

**Comment by AleksueiR** [comment]
Turned out this is not an issue with Angular Material. Thank you.

**Comment by jonchenn** [comment]
I got same issue here, what's the solution then?
