### ISSUE TITLE
IE11 right sidenav blank space

### ISSUE THREAD

**Issue by jvmccarthy** [angular/material#4632]
Right sidenav elements in IE11 (and Edge) are leaving space for the element after it is translated.  As a result, a horizontal scroll bar appears, and scrolling to the right reveals a blank space.  Inspecting with dev tools shows that this space is part of the sidenav element and appears related to how IE renders `translate3d` (toggle the `.md-sidenav-right` `transform` property).  

I'm finding this to be reproducible on IE11 and Edge with angular-material 0.11.0 given the [sidenav demo codepen](http://codepen.io/anon/pen/wKMdmR),
![image](https://cloud.githubusercontent.com/assets/1642221/9860222/f4addf90-5ae7-11e5-83af-c4fd26fb523f.png)

The use of `translate3d` also appears to have an interesting effect in Chrome.  On the same demo, I'm seeing a horizontal scroll bar pop up momentarily during the sidenav opening animation.

**Comment by mi5ha** [comment]
This also happens on Mac Safari.

**Comment by EladBezalel** [comment]
@jvmccarthy @mi5ha i couldn't reproduce can you please check if it's still happens on master?

**Comment by jvmccarthy** [comment]
@EladBezalel I'm still seeing this on master (1.0.2-master-74fe691) with [this codepen](http://codepen.io/jvmccarthy/pen/eJevrq) generated from the "Edit on CodePen" button on the HEAD (MASTER) demo on both IE11 and Edge.

After clicking "toggle right", a scrollbar is visible at the bottom and the user can scroll to the right, revealing the empty space from the transform.

Please let me know if I can clarify this further, thanks.

**Comment by EladBezalel** [comment]
@jvmccarthy this is weird, when i build locally i can't re produce it. but i clearly see it on our deployed docs.
After some inspecting, it seems to be a problem on codepen.. mind assemble this demo on plunkr or jsbin?

**Comment by jvmccarthy** [comment]
@EladBezalel I tried to go a bit further and created a very simple skeleton that uses angular-material 1.0.2 without any external scaffolding.  I then tried to reproduce this issue on that skeleton and was not able to (see [angular-material-scratchpad#am4632-sidenav-ie](https://github.com/jvmccarthy/angular-material-scratchpad/tree/am4632-sidenav-ie)).

This is still concerning because I'm continuing to run into this in my application.  So, my app is probably doing something similar to CodePen that is causing this issue.  What do you think CodePen is doing to cause this?

**Comment by EladBezalel** [comment]
Iv'e tried to find the source of the problem and couldn't find it, also i noticed that the close button is not working on the codepen only,

As you can see below i inspected the whole html page (inside the iframe) and it seems that the html is misaligned somehow, iv'e also tried `position: absolute` and more hacks and none yielded any result.
![image](https://cloud.githubusercontent.com/assets/6004537/12491696/2ac3db36-c085-11e5-9477-5a1a2c016080.png)

**Comment by jvmccarthy** [comment]
@EladBezalel thanks for continuing to look at this.  I'm trying to figure out what makes CodePen and my (closed source) app different from the simple app.  I wonder if it is related to where the sidenav is contained or the layout somehow?

This seems similar to [IE leaves white space on div transform scale](http://stackoverflow.com/questions/23587326/ie-leaves-white-space-on-div-transform-scale), but I'm not sure how to adapt that solution in this case.

**Comment by EladBezalel** [comment]
@jvmccarthy after you mentioned transform i remembered that ie doesn't play well with transforms,
what's happening is that the sidenav is animating from -100% of it's size to 0 with transform,
but i guess that the ie DOM engine can't move things from nowhere (out of screen) and must paint every frame on the DOM.
A q

**Comment by EladBezalel** [comment]
@jvmccarthy after you mentioned transform i remembered that ie doesn't play well with transforms,
what's happening is that the sidenav is animating from -100% of it's size to 0 with transform,
but i guess that the ie DOM engine can't move things from nowhere (out of screen) and must paint every frame on the DOM.
A quick fix will be applying `overflow: hidden` on your html element.

**Comment by jvmccarthy** [comment]
I've added `overflow: hidden` on the `body` element, and this seems to be working well.  I still have `md-content` for scrolling content.  Without seeing a negative to this workaround, I'll close this issue.  Thanks!

**Comment by AdriVanHoudt** [comment]
Is there a non quick fix for this? It seems like a repaint fixes it (in devtools modify a property that causes repaint)
