### ISSUE TITLE
mdAutocomplete scroll prevented in ionic

### ISSUE THREAD

**Issue by Alex-iFactory** [angular/material#4634]
WIthin an ionic application, mdAutocomplete suggestions do not scroll at all.

I have enabled data-tap-disabled on md-autocomplete-wrap as well as md-autocomplete-suggestions. I have also ran $mdGestureProvider.skipClickHijack(); neither of which work.

I have also noticed that the focus event is not fired as normal.

Using

* [angular material v0.11](https://github.com/angular/material/releases/tag/v0.11.0)
* Ionic v1.0.0-rc.2

Cheers

**Comment by jpkinkel** [comment]
Hi Alex, 

I 'm running into the same problem now. Could you solve it? If so how? 

Thanks

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (537/500 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:53826)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avscE-000L6y-FE
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:50 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=bcN6VDBtyM0WkI6x0wnDzy5T6RQ=; b=uc+R6Z6EHWzhRvDf
	yMW7XK/Qfp2SaNOnSzHkcksCTvBQcYRFRRmZqoxxOAN3NnC2YLRT6kQ4tQLi3cp5
	XLxIxbYWzS4P0bBG5tVOtUnPNmxp2PYfZix743mZ7X4enSesROIL0aKFl7AZp7cm
	bZjRFcURc6qiIL4rxZ12EA5l7t4=
Received: by filter0490p1mdw1.sendgrid.net with SMTP id filter0490p1mdw1.3536.572273552E
        2016-04-28 20:32:21.272574714 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id ukAdML3OTYSfFgI1Y6zUrg
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:21.238 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:20 -0700
