### ISSUE TITLE
Input with maxlength and value as a number, show undefined/maxlength

### ISSUE THREAD

**Issue by moizhb** [angular/material#4635]
When the value of a text input is given as number the character tracker on the right show undefined/<maxlength>

See attached:
![selection_004](https://cloud.githubusercontent.com/assets/5599736/9868422/1eb7b684-5b3e-11e5-9bd5-3fe58d4547be.png)

**Comment by jelbourn** [comment]
@moizhb can you add a CodePen (or similar) reproduction? Is this in a specific browser? I wasn't able to quickly reproduce this.

**Comment by moizhb** [comment]
@jelbourn here is the codepen depicting the issue.
http://codepen.io/mhb/pen/RWGPrr

I am using Google Chrome Version 45.0.2454.85 (64-bit)

From what I see, it only occurs when model is an external resource.
Thanks!
