### ISSUE TITLE
Unable to find node 'md-dialog' in element

### ISSUE THREAD

**Issue by KSanthanam** [angular/material#4637]
When I use AngularJS 1.4.5 and ngMaterial 0.11.0 I get the above error (Unable to find node 'md-dialog' in element) for $mdDialog. If I revert ngMaterial back to 0.10.0 the error goes away with same md- tags. 
I need to use 0.11.0 for some md-fab-speed-dial as it seems to be not available on 0.10.0. Can someone confirm if this is a known bug please?
Thank you

**Comment by Tyrannmisu** [comment]
Could be the same or at least related to : https://github.com/angular/material/issues/4511
Did you try to use the angular-material version from the #master branch ? If this is related to the same bug it should be fixed there.

**Comment by parky128** [comment]
I had same issue, did a bower install from master today and the errors go away (at least for mdDialog)

**Comment by KSanthanam** [comment]
@Tyrannmisu Thank you.  I did look at that issue. I am using the stable version 0.11.0. I had a bug in my own code. my js was 0.11.0 but the css was still looking at 0.10.0. Once I fixed that the dialog now works but still I get the 'same' warning message. I am happy to close the issue. But if if it helps I shall keep it open.

**Comment by ThomasBurleson** [comment]
This is fixed in master and will be formally available in the 0.11.1 release (coming soon).

**Comment by Soulcyber** [comment]
i'm waiting for the fix too ;)

**Comment by KSanthanam** [comment]
@ThomasBurleson Thank you very much
