### ISSUE TITLE
Controller 'mdGridList', required by directive 'mdGridTile', can't be found!

### ISSUE THREAD

**Issue by Baudin999** [angular/material#4641]
Hi,

I am trying to get the mdGridList directive to work within my application. One thing to note is that I use ngRoute to load this view into my "page". My code looks like:

```
<md-grid-list
        md-cols-sm="1" md-cols-md="2" md-cols-gt-md="6"
        md-row-height-gt-md="1:1" md-row-height="4:3"
        md-gutter="8px" md-gutter-gt-sm="4px" >
    <md-grid-tile ng-repeat="character in characters"
                  md-rowspan="1"
                  md-colspan="1"
                  md-colspan-sm="1"
                  ng-class="gray">
        <md-grid-tile-footer><h3>{{ character.name }}</h3></md-grid-tile-footer>
    </md-grid-tile>
</md-grid-list>
```

And the error I get is:

```
Error: [$compile:ctreq] Controller 'mdGridList', required by directive 'mdGridTile', can't be found!
http://errors.angularjs.org/1.4.5/$compile/ctreq?p0=mdGridList&p1=mdGridTile
    at REGEX_STRING_REGEXP (angular.js:68)
    at getControllers (angular.js:8103)
    at nodeLinkFn (angular.js:8250)
    at compositeLinkFn (angular.js:7637)
    at publicLinkFn (angular.js:7512)
    at name.$get.boundTranscludeFn (angular.js:7656)
    at controllersBoundTransclude (angular.js:8273)
    at ngRepeatAction (angular.js:27260)
    at Object.$watchCollectionAction [as fn] (angular.js:15580)
    at Scope.parent.$get.Scope.$digest (angular.js:15715)
```

I've tried almost everything but can't seem to be able to fix this problem. Anyone have an idea?

EDIT: 
Seems to be a timing issue, when I "reload" my page I get this error. When I navigate from and to this page I do not get the error and the data is shown. I will continue the investigation.

EDIT:
This error was created because I ran the following code on the initial page load:
```
module.run(['$route', function($route)  {
    $route.reload();
}]);
```
This triggered something, I still don't know what, which resulted in my error.

**Comment by EladBezalel** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  [CodePen template](http://codepen.io/team/AngularMaterial/pen/BNYppz)
*  [Plunkr template](http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview)

**Comment by Baudin999** [comment]
As you might expect, this is not simply a "Plunkr ready issue" else I would have supplied it. I will try and set up a Plunkr which mimicks the behavior. Might take me a while...

**Comment by Baudin999** [comment]
I am closing this issue, I can't get the Plunkr to work. If I ever run into this problem again I'll try and get it running. For now it is solved by not calling $route.reload();

**Comment by udayRedI** [comment]
I got same error when I used the directive as attribute, once I changed it as a tag the error was gone.

**Comment by fabiomig** [comment]
I have the same issue...

**Comment by EladBezalel** [comment]
@udayRedI @fabiomig Can you please provide a codepen?

**Comment by candril** [comment]
I have the same error.

I've reproduced it in the following plunk:

[https://plnkr.co/edit/TvIIRVP0OzUKIx6OH6lm](https://plnkr.co/edit/TvIIRVP0OzUKIx6OH6lm)

```html
<div>
  <div ng-transclude="body">
    <!-- if the grid list is the default value of a transclusion slot, the error occurs -->
    <md-content>
      <md-grid-list md-cols="1" md-row-height="50px">
        <md-grid-tile ng-repeat="item in [1,2,3]">
          <!-- ... -->
        </md-grid-tile>
      </md-grid-list>  
    </md-content>
  </div>
</div>
```

```javascript
angular.module('app', [
  'ngMaterial'
  ])
  
  .directive('page', function() {
    return {
      restrict: 'E',
      transclude: {
        body: 'pageBody',
      },
      templateUrl: 'page.html'
    }
```

**Comment by Senthe** [comment]
I am experiencing the same problem. I have my grid list inside md-bottom-sheet. Relevant code (in Jade):

```
md-bottom-sheet
  .options-wrapper
    md-grid-list(md-cols-xs="1", md-cols-sm="2", md-cols-md="3", md-cols-lg="5", md-cols-gt-lg="6", md-row-height="1:1.5", md-gutter="9px")
      md-grid-tile.option(md-rowspan="1", md-colspan="1")
        .option-content
        md-grid-tile-footer.option-details
```

**Comment by EladBezalel** [comment]
@Senthe please open a new issue with a codepen

**Comment by Senthe** [comment]
I tried but can't reproduce this outside of my app. 

Some hints from my investigation:
* I have two `md-bottom-sheets` defined with the same options (besides `templateUrl` and `controller`). One triggers the error, the other doesn't. No idea why since both templates are basically the same. Controllers contain only data requests. The template triggering error contains `md-checkbox` inside `md-grid-tile` and `ng-click` on `md-grid-tile`, but removing them changes nothing.
* Error goes away when I remove `ng-repeat` from `md-grid-tile`.
* Error logs when the `md-bottom-sheet` is opened the second time. Every next time the drawer is closed and opened again, there is one more error logged than the previous time (so it goes 0-1-2-3... errors)
* It has nothing to do with `md-grid-tile` content, error occurs even when it's completely empty.

**Comment by vinnyfs89** [comment]
I had the same issue. 
This error was caused, in my case, by a tag  ```<div>``` between the tags ```<md-content>``` and ```<md-grid>```

Done here.
