### ISSUE TITLE
can't turn off animation in md-menu

### ISSUE THREAD

**Issue by gmoothart** [angular/material#4651]
http://plnkr.co/edit/a4H1yTmT1vW8sjoyNWi5?p=preview

I would expect that turning ng-animate off globally would stop md-menu from animating in/out, but it does not. Clicking on the menu in the plunker shows the animation even though I have 
`angular.element($('html')).injector().get('$animate').enabled(false);`

It looks like md-menu is not using ng-animate? The animation behavior is making my webdriver tests flaky; I would like some way to stop it.

This may apply to other components as well, this is just where I ran into it.

**Comment by EladBezalel** [comment]
@gmoothart  actually this [seems to work ](http://codepen.io/EladBezalel/pen/avxXyq) on HEAD.
closing this, if you still got this issue please bring it up here and i will re open.
