### ISSUE TITLE
Child Alignment (layout-align) not working in v11.0

### ISSUE THREAD

**Issue by mpweed** [angular/material#4652]
This markup results in the content being centered at the top the window in version v10.1 but it is aligned to the left-edge of the top of the window in v11.0.:
```
<md-tabs md-dynamic-height="true" md-center-tabs="true" md-swipe-content="true">
    <md-tab label="Sign In">
        <div layout="column" layout-align="start center">
            <md-input-container style="width: 300px; margin-right: 5px;">
                <label>Email</label>
                <input required ng-model="user.email" type="email">
            </md-input-container>
            <md-input-container style="width: 300px; margin-right: 5px;">
                <label>Password</label>
                <input required ng-model="user.password" type="password">
            </md-input-container>
            <md-button class="md-primary md-display-1" ng-click="login()">Login</md-button>
            <md-button class="md-accent" ng-click="forgotPassword()">Forgot Password?</md-button>
        </div>
    </md-tab>
    <md-tab label="Sign Up">
        <div layout="column" layout-align="start center">
            <md-input-container style="width: 300px; margin-right: 5px;">
                <label>First Name</label>
                <input required ng-model="user.firstName" type="text">
            </md-input-container>
            <md-input-container style="width: 300px; margin-right: 5px;">
                <label>Last Name</label>
                <input ng-model="user.lastName" type="text">
            </md-input-container>
            <md-input-container style="width: 300px; margin-right: 5px;">
                <label>Email</label>
                <input required ng-model="user.email" type="email">
            </md-input-container>
            <md-input-container style="width: 300px; margin-right: 5px;">
                <label>Password</label>
                <input required ng-model="user.password" type="password">
            </md-input-container>            
            <md-button class="md-primary md-display-1" ng-click="register()">Register</md-button>
        </div>
    </md-tab>
</md-tabs>
```

**Comment by topherfangio** [comment]
@mpweed Can you please convert this to a [Codepen](http://codepen.io) and tell us what browser you are using?

**Comment by mpweed** [comment]
@topherfangio Browser is Google Chrome v45 on Windows 7 Enterprise 64-bit. This partial is a view that gets swapped in by ng-view in the main markup. Does Codepen support multple files or am I going to have to change it to all fit in one html file, one css file, and one js file?

**Comment by topherfangio** [comment]
@mpweed Ideally, it would be great if you could make the most simple example possible so that we can more easily see the issue.

You can start with something like this to get started (just click the "Edit on Codepen" button in the top right of the example): https://material.angularjs.org/HEAD/#/demo/material.components.content

**Comment by mpweed** [comment]
Hi @topherfangio Can you access this pen:  http://codepen.io/mpweed/pen/gaPQpq

**Comment by mpweed** [comment]
Hi @topherfangio Here is a pen with the exact same code using version 0.10.1 that does not have the issue:  http://codepen.io/mpweed/pen/VveVrV

**Comment by topherfangio** [comment]
@mpweed Your first pen is using 0.11.0 for the CSS but 0.10.1 for the JS. There were some changes in 0.11.0 that changed the way the layout was handled, so you'll need to make sure these match.

When I change it to 0.11.0 it works. Is this possibly your problem as well?

**Comment by mpweed** [comment]
Ah!. That was it! What a dumb mistake! Thanks again for helping me with this! I appreciate it!

**Comment by topherfangio** [comment]
No problem, glad to help :-)

**Comment by ThomasBurleson** [comment]
We are publishing [soon] an enhancement to Layouts/Flexbox in ngMaterial.
If you do not want to use ngMaterial JS and only include the ngMaterial CSS, simply add:

```html
<body md-css-only>
...
</body>
```

And all the Flexbox settings will work with just CSS.

**Comment by matheusdavidson** [comment]
This is still not working with latest version:
https://codepen.io/anon/pen/Lpbgjv

**Comment by mpweed** [comment]
Hi Matheus,

No, it is working now. I had only updated the CSS file reference, not the JS file. Once I corrected this everything worked as expected.

Thanks!

Mike

Michael Weed | IT Technical Lead
Meter Vision 20/20 | phone: (610) 774-3088 | cell: (484) 632-9068 | mpweed@pplweb.com<mailto:mpweed@pplweb.com>
[cid:image001.png@01D0F9DF.74174650]<http://www.pplweb.com/>

PPL Services
2 N. 9th St.
GENPL3
Allentown, PA 18104
