### ISSUE TITLE
md-datepicker icon bleeds over open datepicker when in close proximity

### ISSUE THREAD

**Issue by TylersDesk** [angular/material#4658]
I have two md-datepickers side by side.

When datepicker one is open the icon for the second datepicker bleeds over the date selection modal.

![md-datepicker-icon-index](https://cloud.githubusercontent.com/assets/5037139/9895334/9045fefc-5beb-11e5-9afa-2e7ab8418606.png)

**Comment by jelbourn** [comment]
@TylersDesk  It would be great if you could provide a CodePen (or similar) demo of this issue.

**Comment by bluebirdtech** [comment]
+1 I modified the styling to match eg. height of md-no-float input elements with md-icon within the md-input-container, and I'm seeing background through.

Expected behaviour: Opaque background behind the date text too.

**Comment by jelbourn** [comment]
@TylersDesk I haven't been able to reproduce this. Can you provide a demo / reproduction?

**Comment by TylersDesk** [comment]
Yes I will throw together a codepen together when I get a moment.

**Comment by jelbourn** [comment]
@TylersDesk are you still seeing this problem?

**Comment by RichOren** [comment]
@jelbourn - unable to reproduce as well.

**Comment by jelbourn** [comment]
Closing this issue for now as non-reproducible.
