### ISSUE TITLE
md-chips/md-contact-chips allow asynchronous search

### ISSUE THREAD

**Issue by jeremysik** [angular/material#4661]
Request for a feature which allows you to return an array or a promise of array when using the search feature in md-chips/md-contact-chips.

E.g.

```
<md-contact-chips
    ...
    md-contacts="MyController.searchUsers($query)"
    ...
</md-contact-chips>
```

```
public searchUsers(query:string) {

    return this.usersService.query(query)
        .then((data) => data.users);

}
```

**Comment by jeremysik** [comment]
It actually looks like it works, minus the issue as outlined in [#4431](https://github.com/angular/material/issues/4431). Perhaps it would be good to add it to the documentation?

**Comment by topherfangio** [comment]
I am bumping this back to a later release (along with a few other doc changes). If someone wants to submit a PR/demo in the meantime, it would be appreciated :-)

**Comment by KalpanaAr** [comment]
+1
