### ISSUE TITLE
autocomplete: virtual repeat is shown even with no matches; sizing incorrect with md-not-found

### ISSUE THREAD

**Issue by topherfangio** [angular/material#4665]
When using the autocomplete, if the user does not supply a `<md-not-found>` template, the virtual repeat popup is still shown and is blank.

If you add the `<md-not-found>` template, it appears but the sizing is incorrect.

http://codepen.io/topherfangio/pen/rOeBdV?editors=100

**Comment by topherfangio** [comment]
This may be related to #4522.

**Comment by mohitadwani** [comment]
+1

**Comment by ddimitrop** [comment]
It consistently happens when md-min-length is reached but then the user deletes one character.
In that case the suggestion list is empty.

https://codepen.io/anon/pen/EVNddr
