### ISSUE TITLE
chips/contactChips: md-on-append and md-require-match need better docs

### ISSUE THREAD

**Issue by topherfangio** [angular/material#4666]
Currently, the docs for `md-on-append` and `md-require-match` do not explain very well how they work alone or when mixed together.

Need to provide some more info/usage snippets and potentially a demo to clarify.

Should wait until PRs #3816 and #4479 are finished/merged so functionality works better (particularly, you should be ale to use both and have `md-on-append` return null to disallow adding a chip, but this doesn't work yet).

**Comment by JordanMajd** [comment]
+1

**Comment by tonyawad88** [comment]
+1

**Comment by e-oz** [comment]
related: #4193

**Comment by Frank3K** [comment]
+1 for future users. Just spent some time debugging until I connected the dots on `md-require-match`.
