### ISSUE TITLE
when typing autocomplete remove the first letter on mobile

### ISSUE THREAD

**Issue by beny78** [angular/material#4669]
You can reproduce the bug in https://material.angularjs.org/latest/#/demo/material.components.autocomplete
Enable "Simulate query for results" and tries to search for US states beginning with "AL"
You will only have states beginning with "L" because the first letter was removed.

**Comment by beny78** [comment]
Tested on chrome with samsung s5

**Comment by robertmesserle** [comment]
I am unable to recreate this with the latest code.  Closing for now, please respond if this is still an issue.
