### ISSUE TITLE
Tooltip in dialog does not hide when dialog is closed

### ISSUE THREAD

**Issue by Kemaletdin** [angular/material#4670]
I have a fab button on a md-dialog with a tooltip. Button is responsible for closing the dialog.
When the user brings the cursor on the button tooltip shows as expected.
When the user clicks the button dialogue is closed but tooltip stays and does not hide until browser is refreshed 

using angular 1.4.5, angular-material 0.9.8

I also tested on codepen and same result

http://codepen.io/anon/pen/avNbpL

**Comment by ThomasBurleson** [comment]
This has been fixed in master and will be available in the next release v0.11.1

**Comment by jayeshanandani** [comment]
This issue still exists in v1.0.4.

**Comment by DevVersion** [comment]
Please check if your issue is fixed with HEAD / master
