### ISSUE TITLE
Update datepicker demo to show i18n with moment.js

### ISSUE THREAD

**Issue by jelbourn** [angular/material#4671]
The main blocker here is that our docs site does not currently have a way to only load the moment.js script for a single demo.

**Comment by stevenmiles** [comment]
>does not currently have a way to only load the moment.js script for a single demo.

is this really a blocker? or just a nice to have?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (610/500 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:53852 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdI-000Ljg-PE
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:56 -0500
Date: Thu, 28 Apr 2016 13:32:25 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875545;
	bh=I9KQ2hwFkfKpw2+ze3OD7B4/n+Ue62GdjeCG191XWGs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=frttJsnV/zgJFKrQrOBXMNyQgdEZ4kFDJV4gZHgKFmU+cXaGdLWLnslWyFf9+uQps
	 0/BAPdtNc+iiQ22/FZTU2gV+MtzDC12nlDnUSXcmvFII+3lir87AbFAdcCVQiT1oth
	 oQnA9gPSoeH5zNl9Zyb+01vGInNFWuVdWppiEFYI=
