### ISSUE TITLE
Support ngMessages with md-datepicker

### ISSUE THREAD

**Issue by Argee88** [angular/material#4672]
Is there a way to attach an form-element-error like "required" to the md-datepicker by default? It would be very nice to catch these errors with ngMessages...
If there isn't: I think md-datepicker should support this, since one (me, well and maybe others too ;) ) will eventually want to use it in form

**Comment by jelbourn** [comment]
This is definitely [on the to-do list](https://github.com/angular/material/blob/master/src/components/datepicker/datePicker.js#L6), it's just something we haven't gotten to yet.

**Comment by Argee88** [comment]
Okay, thanks for the quick reply.

**Comment by Argee88** [comment]
:+1:  Great job :)

**Comment by askucher** [comment]
+1

**Comment by diegolmello** [comment]
+1

**Comment by christele15** [comment]
Can you create ngmessages depending on date picked such as if the date is greater than 27 weeks ....
