### ISSUE TITLE
mdChips: with autocomplete minLength=0 and noCache=true, menu doesn't show if all choices are selected and removed

### ISSUE THREAD

**Issue by antoinebrault** [angular/material#4673]
Using angular 1.4.5 and material 0.11, when all choices are selected, and deselected, menu with choices doesn't show until a caracter is entered and removed.

https://jsfiddle.net/fcngt79d/1/

1. Select both items
2. Remove one of the items
3. ** try to click in the autocomplete field. Menu doesn't appear.
4. Write something in the autocomplete field and remove it.
5. Menu appears.

**Comment by lscordilis** [comment]
Yeah, md-autocomplete directives such as md-min-length and md-no-cache aren't working like they used to. +1

**Comment by topherfangio** [comment]
I just updated your fiddle to use master, and this unfortunately still looks to be an issue. We will investigate.

**Comment by enderdickerson** [comment]
Why was this marked as Depricated? It's still present in 1.1.0-rc4. Is there a known workaround for this then?

**Comment by topherfangio** [comment]
@enderdickerson Please see the following forum post for more information: https://groups.google.com/d/msg/ngmaterial/3Ip9nd68bfk/X448kGtvAQAJ

**Comment by enderdickerson** [comment]
Thanks. I guess I'll open a new issue and cite this one following the spring cleaning effort. I'm assuming this fits the depricated category for one of these two reasons:
- Issue is real, but only affects a very small use case
- Issue is real, but would require significant work to fix, and is less urgent than other needs.

Unfortunately it's an issue I could really use a fix for. Thanks for the quick reply @topherfangio.
