### ISSUE TITLE
$mdUtil.findFocusTarget(...) uses element.scope() which isn't always available

### ISSUE THREAD

**Issue by erikogenvik** [angular/material#4674]
If debug info is disabled for the $compileProvider, through a call to
```
$compileProvider.debugInfoEnabled(false);
```
which is the recommended approach for production sites, the "scope()" method won't be attached to elements.

However, in the method $mdUtil.findFocusTarget.scanForFocusable() the code tries to access the $eval service through a call to the element's scope() method.
The result is that some dialogs, in my case a confirm dialog, will get an error when shown, resulting in the promise never being resolved even though the user clicked on "ok".

Tested with master build from 2015-09-16.

**Comment by ThomasBurleson** [comment]
Fixed.
