### ISSUE TITLE
Configuring md-datepicker for parsing and validating with moment should be easier.

### ISSUE THREAD

**Issue by arlowhite** [angular/material#4679]
0.11 master d6d6b78c3e1545c8d92b0c69edbf0e7420106329

I wanted to use Moment for date parsing. http://momentjs.com/docs/
When moment parses a date string, it returns an object with validity information. This means overriding:
* dateUtil.isValidDate
* dateLocale.isDateComplete - gives false invalid for dates that Moment can parse such as "Oct 15"
* dateLocal.parseDate

Configuring mdDatepicker was a huge pain and hackish.
I wanted to avoid redundant calls to moment. That is, I didn't want to parse the date string again within isValidDate.

So I decided to just monkey patch handleInputEvent:
*This code also reformats the displayed input value on blur. The debounce made this awkward to code; I don't think I did this in the most ideal Angular way, but it works.*
Original function source for reference:
https://github.com/angular/material/blob/416dc4c023da00a78c9779ea9b958c052d44d353/src/components/datepicker/datePicker.js#L338
*(if conditions changed slightly since version I started with)*
```javascript
var momentDateParseFormats = ['MMM-DD-YYYY', 'dddd, MMMM Do'];
angular.module('material.components.datepicker')
/**
 * Override mdDatepicker to use moment's isValid so that
 * bad dates such as "Oct 44" are marked invalid.
 *
 */
  .run(function(mdDatepickerDirective) {
    var ctrlProto = mdDatepickerDirective[0].controller.prototype;
    var INVALID_CLASS = 'md-datepicker-invalid';
    ctrlProto.handleInputEvent = function() {
      var inputString = this.inputElement.value;
      var momentDate = moment(inputString, momentDateParseFormats);
      var parsedDate = momentDate.toDate();
      this.dateUtil.setDateTimeToMidnight(parsedDate);

      if (momentDate.isValid() &&
        this.dateUtil.isDateWithinRange(parsedDate, this.minDate, this.maxDate)) {
        this.ngModelCtrl.$setViewValue(parsedDate);
        this.date = parsedDate;
        this.inputContainer.classList.remove(INVALID_CLASS);

        this._needsRenderOnBlur = this.isFocused;
        if(!this.isFocused){
          // Debounced after blur, Render now
          this.inputElement.value = this.dateLocale.formatDate(this.date);
          this.resizeInputElement();
        }
      } else {
        // If there's an input string, it's an invalid date.
        this.inputContainer.classList.toggle(INVALID_CLASS, inputString);
        this._needsRenderOnBlur = false;
      }
    };
    ctrlProto.setFocused = function(isFocused) {
      this.isFocused = isFocused;
      if(!isFocused && this._needsRenderOnBlur){
        // Blur
        this.inputElement.value = this.dateLocale.formatDate(this.date);
        this.resizeInputElement();
        this._needsRenderOnBlur = false;
      }
    };
  });
```

In addition, I overrode these functions on $mdDateLocalProvider, which is much cleaner as they were intended to be overridden. *I don't think isDateComplete is ever called since I removed the call from handleInputEvent*
```javascript
    $mdDateLocaleProvider.parseDate = function(dateString) {
      return moment(dateString, momentDateParseFormats).toDate();
    };

    // May not be used at all since handleInputEvent overridden above.
    $mdDateLocaleProvider.isDateComplete = function () {
      // moment handles parsing of incomplete dates
      return true;
    };

    $mdDateLocaleProvider.formatDate = function(date) {
      if(!date){
        return '';
      }
      return moment(date).format('dddd, MMMM Do');
    };
```

Please make md-datepicker easier to configure with libraries such as Moment, thanks.

**Comment by arlowhite** [comment]
I think the current date parsing API is too constricting by separating the logic into so many functions. This causes difficulty implementing libraries such as Moment (as described above) and forces inefficiencies.

Instead, a single parse function that returns three bits of information would be more flexible.
```javascript
function parseAndValidateDate(dateString) {
   // parsing code...
   return {
      date: dateObject // Date or null if incomplete
      valid: true
      complete: true
   }
}
```
- complete: false - not enough text to parse into a date.
- valid - always false if !complete, but may be false while complete==true if parser checks date logic. e.g. Moment parses 9/44/2015, but it is invalid as no month has 44 days.

Could return an array instead if that's cheaper. Could also add properties to the Date object, but I'm not sure how frowned upon this is.

Also, you could just re-implement the current code this way without breaking the current public API. And just expose **parseAndValidateDate** to be overriden.

@jelbourn @ThomasBurleson What do you think?
I could make the change and create a PR if you want, but since you guys have been working on datepicker I figured one of you should do it.

**Comment by jelbourn** [comment]
I don't really see how the current setup is difficult or leads to hacky code. With moment you're just defining three simple, one-line functions. 

It's fine to write your own function called `parseAndValidateDate` and then simply call that from the `$mdDateLocale` functions. The API isn't designed to cater exclusively to moment.js, but instead to provide a lot of knobs for individuals to customize the i18n behavior.

**Comment by arlowhite** [comment]
All of this came out of trying to avoid the *extra* parse call to moment. So yes, you can use the current API, but it will result in two Moment parsing calls (one from parseDate and one from isValidDate).

Since input is debounced it's probably not a big performance issue anyway. I'm only concerned about it as I'm working on a mobile app.

**Comment by jelbourn** [comment]
Yeah, it will be multiple calls, but this kind of parsing is generally not going to have a noticeable performance cost.

**Comment by alanent** [comment]
Someone can help me ? https://stackoverflow.com/questions/50947642/angular-material-6-datepicker-reactive-form

**Comment by Splaktar** [comment]
@alanent Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
