### ISSUE TITLE
Material namespace collating with polymer.

### ISSUE THREAD

**Issue by samio80** [angular/material#4680]
Is there anyway to scope material layouts statements like flex** to use something instead like ng-material-flex so then does not interfere with polymer layouts?  I know angular 2 will play nicely with web-components, but still this will be an issue specially CSS related.

**Comment by ThomasBurleson** [comment]
Can you provide some examples where the two conflict with different definitions?

**Comment by samio80** [comment]
This is just to show the conflicts with flex related terms, but I see a lot more of css classes in conflict even the fonts are different.

<img width="753" alt="screen shot 2015-09-17 at 06 27 09" src="https://cloud.githubusercontent.com/assets/4519631/9924973/607b94dc-5d05-11e5-8908-b1164286826f.png">

**Comment by samio80** [comment]
and this one overwrites the angular-material font https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic

**Comment by jelbourn** [comment]
Seems to me that all of the layout CSS needs to have the `md-` prefix.

**Comment by ThomasBurleson** [comment]
:+1:

**Comment by ThomasBurleson** [comment]
We plan to support an optional `md-` prefix with ngMaterial 1 Layout features.
This is planned for ngMaterial 2.

**Comment by ThomasBurleson** [comment]
Track via #6294
