### ISSUE TITLE
fabToolbar not working properly on android

### ISSUE THREAD

**Issue by Alexandre-io** [angular/material#4682]
https://material.angularjs.org/latest/#/demo/material.components.fabToolbar

Since 0.11, I have 2 bugs with android (chrome):

- Double-click to open the fabToolbar prevent it to be closed later.
- Randomly need Double or more click to be opened.

**Comment by topherfangio** [comment]
This is quite possibly fixed in the latest release. Can you please re-test against the latest docs?

If you're still seeing an issue, could you please post the version of Android you are using so that we can investigate further and I will re-open?
