### ISSUE TITLE
md-select, md-dialog: broken on closing, JS error

### ISSUE THREAD

**Issue by alexitooi** [angular/material#4683]
angular-material: master
angular: 1.3.18/1.3.19

md-select: after selecting an item the select does not close
![bildschirmfoto 2015-09-17 um 10 57 48](https://cloud.githubusercontent.com/assets/2962085/9929114/fcdd70c8-5d2a-11e5-89bb-9d5e9c496566.png)

md-dialog: $mdDialog.hide(), $mdDialog.cancel() not working anymore
![bildschirmfoto 2015-09-17 um 10 59 03](https://cloud.githubusercontent.com/assets/2962085/9929144/2692cbfc-5d2b-11e5-8d15-f4615241aaba.png)

introduced by: 77a34bd8f122814527159d08536d5776b314f527 @ThomasBurleson

**Comment by ThomasBurleson** [comment]
Thank you for this alert.

**Comment by alexitooi** [comment]
thank you too!
