### ISSUE TITLE
Writing fast in input breaks ng-messages

### ISSUE THREAD

**Issue by tniezurawski** [angular/material#4685]
Hello,

I've prepared 3 examples in this plunker for you guys:
http://plnkr.co/edit/I2BzzAbGySn1d6wVOK1E?p=preview

If you write fast in input it breaks in showing ng-messages correctly. To show you that this is not connected with ng-pattern I've prepared an example without using angular-material and different approach to resolve the same problem.

I guess it is probably connected with animation and changing the state of input with delay.

**Comment by ThomasBurleson** [comment]
@topherfangio - I think we need to debounce the change trigger for ng-messages and animations.

**Comment by topherfangio** [comment]
@ThomasBurleson The animations are all CSS-based and are kicked off when the error messages appear. I'm not sure we can really control that on our end unless we hack ng-messages. Thoughts?

Also, two quick points:

1. It appears this is reproducible in 0.11.0 and 0.10.1, but not 0.10.0, so it was introduced between then
2. A quick fix is to add `ng-model-options="{debounce: 100}"` to your input

**Comment by tniezurawski** [comment]
Thanks guys for replaying.

@topherfangio:

1. Agree. In fact my team work with version 0.10.1.
2. It kind of works but it is still "hacky". It's harder to reproduce the bug but it still possible.

**Comment by topherfangio** [comment]
I'll see if I can run `git bisect` and track down the commit that actually introduced the issue in 0.10.1 so we can see why it's breaking and if there is something we can do about it.

**Comment by topherfangio** [comment]
@tniezurawski Please see my linked issue in the main Angular repo for an update.

**Comment by petebacondarwin** [comment]
I think I have a fix here https://github.com/angular/angular.js/pull/12903

**Comment by topherfangio** [comment]
@petebacondarwin I just tested the changes and it appears to have solved this issue. Thanks so much!

@ThomasBurleson What is the best way to track this so that we close the issue when we switch to 1.4.7?

**Comment by ThomasBurleson** [comment]
*  Reset Milestone to v0.12, 
*  leave open until we change the `config/build.config.js`.

**Comment by ThomasBurleson** [comment]
This has been fixed and will be available in the next Angular 1.4.7 release.
