### ISSUE TITLE
md-menu async support

### ISSUE THREAD

**Issue by jb29** [angular/material#4687]
Hi,

I want to load `md-menu-items` asynchronously when the user clicks on a button to open a `md-menu`.

Everything works fine if I have **at least 1 item** in my array of menu items before the user opens the menu. See [this codepen](http://codepen.io/anon/pen/ojxBEM) for an example.

But if the array is **empty** when the user opens the menu, I get an invisible `md-backdrop` covering the whole screen which prevents any further user interactions.
Open [this codepen](http://codepen.io/anon/pen/xwVRQR) and click on the button to reproduce this bug.

*Tested with `angular-material` version 0.11.0*

**Comment by EladBezalel** [comment]
I suppose the menu initial rendering occurs only at first, when there's something to render it's behaves as expected..

**Comment by ThomasBurleson** [comment]
@rschmukler - Here is a updated [CodePen Demo](http://codepen.io/ThomasBurleson/pen/vNKMmM) using bower-material/master and ng v1.4.6.

**Comment by ThomasBurleson** [comment]
Here is a updated [CodePen Demo](http://codepen.io/ThomasBurleson/pen/vNKMmM) using bower-material/master and ng v1.4.6.

**Comment by jb29** [comment]
Thanks, works great now.

Maybe in a later version you could add support for a loading animation similar to [md-select](https://material.angularjs.org/latest/#/demo/material.components.select)'s "Options With Async Search"?
