### ISSUE TITLE
md-select placeholder not populated until you click on the select

### ISSUE THREAD

**Issue by wembernard** [angular/material#4689]
As you can see [here](http://codepen.io/wembernard/pen/garLQK), the placeholder won't display unless you open the select. 

My guess is that if `md-option`(s) are not resolved, placeholder won't display.

By the way, it makes `md-on-open` a broken feature if you want to use it to load asynchronously the md-options.

I'm not sure if it's related to #2588 or not.

**Comment by OscarAgreda** [comment]
Thank you for working hard and helping us bring material to life

I was experimenting the same bug when migrated from Material 0.9.8 to 0.11 
i just got the latest : bower install angular-material#master and made sure the fixed shows on my angular-material.js
but is not fixed on my solution , was fine in 0.9.8.

**Comment by ericman93** [comment]
+1
