### ISSUE TITLE
md-toast: content is not centred in IE11 for simple toast

### ISSUE THREAD

**Issue by lmignot** [angular/material#4690]
This is only a problem since 0.11.0, simple toast worked fine on IE11 previously. 
md-toast with action and custom template work fine

The bug can be reproduced in the demo https://material.angularjs.org/HEAD/#/demo/material.components.toast and I've attached a screenshot (Windows 8.1 IE11.0.23)

![md-toast ie11](https://cloud.githubusercontent.com/assets/372523/9932775/69ca900e-5d3e-11e5-99ea-6405bcdc736d.png)

**Comment by prussian-blue** [comment]
Seeing  this too

**Comment by prussian-blue** [comment]
This fixes the problem of IE11.

Seems to work both for Chrome 35 and IE11 - In SASS

Might help you guys to spot the problem

md-toast {
  height: 0px;

  span {
    flex: none;
  }
}

**Comment by lmignot** [comment]
confirming that that works on my end, although I didn't need to set `flex:none` on the `span` element

**Comment by loic** [comment]
I've been using the following fix as to only target IE11:
```
_:-ms-fullscreen,
md-toast {
    height: 0px;
}
```

**Comment by prussian-blue** [comment]
Can also use

    @media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
         md-toast {
            height: 0px;
        }
    }

**Comment by EladBezalel** [comment]
Can't reproduce on HEAD (v1.0.4)
