### ISSUE TITLE
md-autocomplete/ ng-messages not resetting padding-bottom 

### ISSUE THREAD

**Issue by paulflo150** [angular/material#4692]
There was a min-height added to md-input-container [ng-messages] recently, but padding-bottom isn't getting reset - you can see it on the floating label demo:

```
md-autocomplete.md-input-has-messages {
    padding-bottom: 2px; // or 0?
}
```

**Comment by topherfangio** [comment]
I am currently looking into this. We added some code to account for the `min-height`, but it assumes that the input is inside of an `md-input-container`, which the autocomplete isn't. I'll see if we can refactor the code to fix this.
