### ISSUE TITLE
In version 0.11, <md-tabs> inside <md-toolbar> doesnt work any more

### ISSUE THREAD

**Issue by Chidan** [angular/material#4693]
Hi,

In version 0.11, <md-tabs> inside <md-toolbar> doesnt work any more, this was working in version 0.10 but not any more.
Here is the example I have created, please have a look.
http://codepen.io/anon/pen/yYOXYN 

Regards,Chidan

**Comment by EladBezalel** [comment]
It seems to be the new js layout problem, if you delete the layout attributes from ``` <md-toolbar> ``` It will work,
if you'll change it to 
```html 
<md-toolbar layout="column" layout-align="center"> 
```
it will work

**Comment by ThomasBurleson** [comment]
@Chidan - try specifying:

```html
<md-tabs style="min-width:180px">
```

**Comment by Chidan** [comment]
thanks, both solutions solved the issue.
