### ISSUE TITLE
Autocomplete Tab selection

### ISSUE THREAD

**Issue by colbroth** [angular/material#4697]
I am using md-autocomplete to display a list of states as shown in the demo example.

I live in New Hampshire. 

Most websites, I can type "n" and nebraska shows up first. I can then click the "tab" key and it will select the next state that starts with "n" and so on. So to select new hampshire, I type "n", "tab", "tab".

The angular material md-autocomplete code in the demo example does not do this behavior. Is there an option to do this?

**Comment by topherfangio** [comment]
I do not believe there is currently an option for this. The current behavior of the majority of the components is that tabbing gives the component focus, and then the arrow keys allow you to move around. Tabbing again will blur and move focus to the next component.

**Comment by colbroth** [comment]
Could this functionality be added to angular material? It seems like a basic option for most websites online.

**Comment by topherfangio** [comment]
@marcysutton Could you chime in on this topic from an accessibility standpoint? I'd love to hear your thoughts.

**Comment by marcysutton** [comment]
What browser uses TAB to cycle through options? Every select implementation I've seen relies on individual characters to go through options–even hitting the same character cycles through them. TAB should blur the input field, always. Here is a default HTML sandbox I use to test: http://codepen.io/marcysutton/pen/ZYqjPj

**Comment by topherfangio** [comment]
@marcysutton Thanks for the info/link! I agree with you, although strangely, in Chrome, tabbing doesn't blur the select if it's open. It ignores it, which seems odd to me.

In either case, it definitely doesn't cycle through options, so unless something changes, I don't believe we will add this as a feature.

@ThomasBurleson Thoughts?

**Comment by colbroth** [comment]
@marcysutton I was confused, it isn't the tab key. It is when I keep
pressing the letter "n" that I can get to my state of New Hampshire. Does
Angular Material provide this with auto-complete?

On Fri, Sep 18, 2015 at 12:49 PM, Topher Fangio <notifications@github.com>
wrote:

> @marcysutton <https://github.com/marcysutton> Thanks for the info/link! I
> agree with you, although strangely, in Chrome, tabbing doesn't blur the
> select if it's open. It ignores it, which seems odd to me.
>
> In either case, it definitely doesn't cycle through options, so unless
> something changes, I don't believe we will add this as a feature.
>
> @ThomasBurleson <https://github.com/ThomasBurleson> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/4697#issuecomment-141505160>.
>



-- 
* ´¨)
¸.· ´¸.·* ´¨) ¸. ·*¨)
(¸.·´ (¸ Lisa

**Comment by topherfangio** [comment]
@colbroth The autocomplete does not as it it intended to be a text input with an autocomplete dropdown (i.e. it allows the user to type something that is not yet in the list as valid input; think labels/tags).

The `<md-select>` might be a better candidate for this feature, but it does not currently offer that option. The current method is to track the keys you press and see if they match an existing item (so on the demo, I can type `T` and it takes me to `TN` for Tennessee, but if I quickly type `TX`, it will jump there instead).

It also doesn't make sense for every situation (i.e. non-alphabetized lists), so I think if offered, it should definitely be configurable.

I'm going to go ahead and close this. If you would like to see this added to the `<md-select>` please open a new issue with that description.
