### ISSUE TITLE
sidenav: add support for clickOutsideToClose

### ISSUE THREAD

**Issue by nmichaud2** [angular/material#4699]
I was wondering if it would be possible to have a similar parameter as for the dialog to prevent the sidenav from being closed when clicking on the backdrop or pressing the esc key.

**Comment by FjVillar** [comment]
What about this issue, is this feature still wanted by the team/community? I would like to have this 'clickOutsideToClose' to prevent the user from closing the sidenav by clicking outside or pressing 'ESC' button. 

I would like to implement this.

**Comment by Splaktar** [comment]
@FjVillar we would welcome a PR from the community that added this functionality.

**Comment by FjVillar** [comment]
Nice, I will be working on this by the end of this week.

**Comment by Splaktar** [comment]
Closed in https://github.com/angular/material/commit/fae40424d8d9f6ad129b26107fc75fbeaca17a52.
