### ISSUE TITLE
Slider does not work properly with touch events

### ISSUE THREAD

**Issue by raymccoy** [angular/material#470]
When using a md-slider in a touch device, only the inner bar moves. The indicator is not updated properly - it stays to the left. Also the styling is not correct in the discrete indicator, the bottom triangle is displayed as a square. 

To reproduce, open https://material.angularjs.org/#/demo/material.components.slider in a touch device (I tested in Android 4.1.1 native browser).

**Comment by ThomasBurleson** [comment]
Fixed in 0.7.1
