### ISSUE TITLE
md-menu does not close menu content after click on one of the menu items in mobile

### ISSUE THREAD

**Issue by hanhsu** [angular/material#4702]
The md-menu does not close menu content automatically after click on one of the menu items in mobile. It works fine on desktop.

Example:

```html
<md-menu>
  <md-button ng-click="$mdOpenMenu()">
    open menu
  </md-button>
  <md-menu-content>
    <md-menu-item>
      <md-button ng-click="doSomeThing()">
        <span>Do Something</span>
      </md-button>
    </md-menu-item>
  </md-menu-content>
</md-menu>
```

I am using angular-material@0.11.0 and tested on iOS 8 Safari

**Comment by ThomasBurleson** [comment]
Please retest with the lastest source/build on **angular/material/master**; also using Angular v1.4.6 or v1.3.19. If the problem persists, please provide a CodePen and I will reopen this issue.
