### ISSUE TITLE
Radio Group should support horizontal layout (it does not appear to)

### ISSUE THREAD

**Issue by djmarcus1** [angular/material#4703]
I want to get 3 columns (text, text, radio group all in one row).
I define a row layout.

Problem #1: The radio buttons show up vertically (I want horizontal layout for the buttons)

Problem #2: The radio buttons show up a few pixels lower (next row?) than the text columns (columns 1 and 2).

Here's the HTML:

    <div flex layout-margin layout="row" layout-sm="column" layout-fill layout-padding>
        <div flex="20">
            products
        </div>
        
        <div id="productName" flex="10">product name</div>

        <div flex="20">
            <md-radio-group ng-model="settings.selectedBillingOrPricing">
                <md-radio-button class="md-primary" value="billing" aria-label="Billing Algorithms">
                    Algorithms
                </md-radio-button>
                <md-radio-button value="pricing" aria-label="Pricing">
                    Pricing
                </md-radio-button>
            </md-radio-group>
        </div>
    </div>

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr.

**Comment by PDSBGreg** [comment]
On your md-radio-group, just add layout="row" layout-align="start center". I also override the margin-bottom of the group to 4px (I think the default is 8).

I think you can also remove the div with flex="20" that the radio group is in because the radio group behaves like a div container (so you can add flex="20" directly to the group).

**Comment by djmarcus1** [comment]
Thank you so much. Your feedback was spot on... solved both problems.

The usage of layout and layout-align on the md-radio-group actually highlights an issue with the documentation.

The Directives documentation:

    https://material.angularjs.org/latest/#/api/material.components.radioButton/directive/mdRadioGroup

... doesn't mention any of these.

I really think the 'official' API page should document ALL the legal parameters (even if via a link to a default set). If it is there, I missed it.

Again, thank you very much for the quick and accurate reply.

**Comment by ThomasBurleson** [comment]
@djmarcus1 - A PR with the documentation improvements would be welcomed.

**Comment by djmarcus1** [comment]
I am a newbie to this group. What is 'PR'?

I can see helping out... :-)

**Comment by ThomasBurleson** [comment]
If you submit a Pull Request (aka PR) with the documentation improvements...

**Comment by djmarcus1** [comment]
Understood - put my money where my mouth is - good approach to collaboration.

I will study the process and see what I can offer.

-Thanks
David

**Comment by ThomasBurleson** [comment]
@djmarcus1 - In my opinion, Angular Material is a great framework in large part due to the community, the community feedback, and the contributions/PRs. Thank you for your ideas, efforts, and support.
