### ISSUE TITLE
md-autocomplete don't clear all class selected in tag li child

### ISSUE THREAD

**Issue by lungkuteo** [angular/material#4704]
This is my code
```
<md-autocomplete
    flex
    ng-show="hideCartInfo"
    id="inputStockCode"
    md-no-cache="true"
    md-selected-item="stock"
    md-search-text="searchCode"
    md-items="item in FindCode(searchCode);"
    md-item-text="item.code"
    md-search-text-change="stockFound = false;"
    md-selected-item-change="SelectStock(item);">
    <md-item-template>
           <span md-hightlight-text="searchCode"
                   ng-style="{color: item.stockWithBill ? 'red' : 'black'}">{{item.code}} ({{item.quantityString}})</span>
    </md-item-template>
    <md-not-found>
           Not found.
    </md-not-found>
</md-autocomplete>
```

When i type first `searchCode`, select item use keyboard arrow, `li` tags add right class `selected`, background of class `selected` display `pink` . But when i click button clear and i type second `searchCode` same as first again, background of class `selected` still show in `li` tags and third, forth ... still

**Comment by topherfangio** [comment]
@lungkuteo Could you provide a [Codepen](https://codepen.io) that demonstrates this so we can better understand the issue?

**Comment by lungkuteo** [comment]
sorry! i don't have Codepen. Thanks so much!
