### ISSUE TITLE
md-tabs: tab doesn't allow to open in a new tab with middle click

### ISSUE THREAD

**Issue by flowersinthesand** [angular/material#4710]
As you can see from https://material.angularjs.org/0.11.0/#/demo/material.components.tabs, tab doesn't allow to 'open in a new tab with middle click or ctrl + click' unlike [Foundation's tab](http://foundation.zurb.com/docs/components/tabs.html).

In terms of UX, each clickable element should allow to open it in a new tab. That means that while reading some tab's content, users should be able to open other tabs in new tabs to load its contents in background (achieving distraction-free reading experiences).

**Comment by timc13** [comment]
+1
