### ISSUE TITLE
$scope.watch doesnt work for input within md-input-container

### ISSUE THREAD

**Issue by dasAnderl** [angular/material#4712]
<input type="text" name="input" ng-model="watchtext" aria-label="search for channels" />
			Word changed {{counter}} times.

			<md-input-container flex
			                    flex-sm="65"
			                    layout-fill
			                    ng-if="true">
				<label>Search for channels</label>
				<input ng-model="watchtext"
				       name="input"
				       type="text"
				       aria-label="search for channels"/>
			</md-input-container>"

$scope.counter = 0;

			$scope.$watch('watchtext', function(newValue, oldValue) {
				$scope.counter = $scope.counter + 1;
				$scope.lastvalue = oldValue;
				$scope.currentvalue = newValue;
			});

**Comment by dasAnderl** [comment]
also ng-change doesnt work as expected.  the ca

**Comment by dasAnderl** [comment]
it didnt work because an ng-if="true" on the md-input-container

**Comment by topherfangio** [comment]
Can you please provide a [Codepen](https://codepen.io) that shows the issue/issues and update the title of this issue to match the problem?

**Comment by dasAnderl** [comment]
thanks for your quick reply. i already closed the issue. because without the ng-if="true" on the md-input-container everything works

**Comment by mpospelov** [comment]
It can still be reproduced. It seems that `md-input-container` create a new scope when it contains ng-if instruction
here are some cases when issue occurs:
https://plnkr.co/edit/m7yJr4gKVTqND6EfjeG7?p=preview
