### ISSUE TITLE
md-autocomplete incorrectly displays options

### ISSUE THREAD

**Issue by TiagoDevezas** [angular/material#4713]
You can see the issue here: https://material.angularjs.org/HEAD/#/demo/material.components.autocomplete

If you click on the first demo and scroll down, the options keep repeating. If you click on one of the repeated options, the value selected does not correspond to the option clicked.

**Comment by topherfangio** [comment]
Almost certainly related to 8849213ce42fa98169b6fbbb0805feb95a6ba678. Will investigate immediately.
