### ISSUE TITLE
Animation issues with Angular 1.4.x

### ISSUE THREAD

**Issue by dmackerman** [angular/material#4714]
I've noticed that animations essentially stop working, or break when using any version of Angular 1.4.x. I'm guessing it has something to do with the changes in `ngAnimate`. The strange thing is that it tends to happen **after** you trigger one animation. The first animation works as normal, and every subsequent animation seems to act strange.

- button ripples don't seem consistent 
- dialogs won't animate from their respective `targetEl`, they just appear in a fade in immediately.
- toasts appear immediately with no animation
- menu elements fly in from the left before animating properly. The second click of the menu triggers the animation properly.

Using the latest `master` and `1.4.6` versions of all angular libs. I've seen this happen with older Material versions as well, and downgrading to angular `1.3.x` libs seems to fix the problem.

This very well could be something app specific, still working on identifying that.

**Comment by ThomasBurleson** [comment]
@dmackerman Due to improvements with ngAnimate, ngMaterial is supported only on versions `>=1.3.19  && <1.4.0` or `>=1.4.6`. If you find any animation issues with the latest HEAD version of angular-material.js/.css, please open a new issue.

**Comment by dmackerman** [comment]
Ah, thanks for the clarification.

**Comment by baracoder** [comment]
This is not good for angular-animate to change like this. The third number is the patch version and should be backwards compatible. See http://semver.org

**Comment by bradrich** [comment]
@ThomasBurleson Can you give me a little more information concerning the issues with ngMaterial and ngAnimate? None of the ngMaterial animations are working as expected, but the most obvious ones are the mdSidenav and the md-backdrop.

Here is my bower.json:

```
{
  "name": "dashboard",
  "version": "0.0.1",
  "appPath": "src/main/webapp",
  "testPath": "src/test/javascript/spec",
  "dependencies": {
    "angular": "~1.5.0",
    "angular-aria": "~1.5.0",
    "angular-bootstrap": "1.1.2",
    "angular-cache-buster": "0.4.3",
    "angular-cookies": "~1.5.0",
    "angular-dynamic-locale": "0.1.30",
    "angular-i18n": "~1.5.0",
    "angular-local-storage": "0.2.3",
    "angular-loading-bar": "0.8.0",
    "angular-resource": "~1.5.0",
    "angular-sanitize": "~1.5.0",
    "angular-translate": "2.9.0",
    "angular-translate-interpolation-messageformat": "2.9.0",
    "angular-translate-loader-partial": "2.9.0",
    "angular-translate-storage-cookie": "2.9.0",
    "angular-ui-router": "0.2.17",
    "bootstrap-sass": "3.3.6",
    "jquery": "2.2.0",
    "json3": "3.3.2",
    "modernizr": "3.3.1",
    "ng-file-upload": "11.2.3",
    "ngInfiniteScroll": "1.2.2",
    "sockjs-client": "1.0.3",
    "stomp-websocket": "2.3.4",
    "swagger-ui": "2.1.4",
    "angular-nicescroll": "~0.0.9",
    "angular-animate": "~1.5.0",
    "fastclick": "~1.0.6",
    "please-wait": "~0.0.5",
    "animatewithsass": "^3.2.2",
    "angularytics": "^0.4.0",
    "SpinKit": "spinkit#^1.2.5",
    "angular-material": "^1.0.5"
  },
  "devDependencies": {
    "angular-mocks": "~1.5.0",
    "angular-scenario": "~1.5.0"
  }
}
```
