### ISSUE TITLE
Line height in md-checkbox should be the same as body text

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#4716]
Currently is 26px vs 20px for `.md-body-1`. 

Currently:

<img width="370" alt="screen shot 2015-09-18 at 3 23 28 pm" src="https://cloud.githubusercontent.com/assets/9092817/9969190/0da0bf14-5e1b-11e5-8fa7-9df4070b9a42.png">

If corrected:

<img width="378" alt="screen shot 2015-09-18 at 3 25 36 pm" src="https://cloud.githubusercontent.com/assets/9092817/9969192/137dff64-5e1b-11e5-9b6d-6477268fba6c.png">

**Comment by ThomasBurleson** [comment]
The checkbox line-height is a factor of the size of the checkbox..

**Comment by ivan7237d** [comment]
Sure, compensate with padding or margin, should be the same as radio buttons:

<img width="500" alt="screen shot 2015-09-18 at 5 53 57 pm" src="https://cloud.githubusercontent.com/assets/9092817/9971995/6c300004-5e2e-11e5-9581-f52f8f367bda.png">

**Comment by jelbourn** [comment]
Related #3234
