### ISSUE TITLE
md-select with async options works, but does not display spinner

### ISSUE THREAD

**Issue by DaveBagler** [angular/material#4717]
I've run into an issue wit md-select.  I have it on a page and the control works fine.  The on-load method is called and the options are accurately loaded into the controller. 

However the spinner isn't displaying when the on-load method is running. As it does on https://material.angularjs.org/latest/#/demo/material.components.select

The markup is still loading but is set as hidden: 

```html
<md-progress-circular md-mode="" ng-hide="$$loadingAsyncDone" aria-valuemin="0" aria-valuemax="100" role="progressbar" class="ng-scope md-default-theme ng-hide" aria-hidden="true" style="transform: scale(0.5);">
    <div class="md-spinner-wrapper ng-hide">
        <div class="md-inner">
            <div class="md-gap"></div>
            <div class="md-left">
                <div class="md-half-circle"></div>
            </div>
            <div class="md-right">
                <div class="md-half-circle"></div>
            </div>
        </div>
    </div>
</md-progress-circular>
```

I'm using release 0.11.0

**Comment by zerobig** [comment]
Function in you attribute md-on-open must be with return. Sample:
```javascript
$scope.getUsers = function () {
    return $http({ method: "GET" <bla-bla-bla> })
}
```

**Comment by DaveBagler** [comment]
Thanks, yeah, my function was returning however it wasn't working with $resource or Restangular, switching to $http solves the problem. I'm not sure why, and at some point I'll look into it but it works and for now that's enough for me.

**Comment by Kratos-SA** [comment]
is there anyway to override this when you are not using an $HTTP?

**Comment by zoorsaaz** [comment]
@Kratos-SA You can return a [Promise](https://docs.angularjs.org/api/ng/service/$q).

**Comment by Kratos-SA** [comment]
do you have a codepen or fiddler with the promise set up? I have use promises before with odata but not like this.

**Comment by zoorsaaz** [comment]
@Kratos-SA check this out 

https://plnkr.co/edit/XiDx5yY2dY4ZvmqhhPaZ?p=preview

**Comment by Kratos-SA** [comment]
I ran that fiddle and the original code and neither works at all. I am running 1.0.5 or angular material.

**Comment by zoorsaaz** [comment]
Well key is to use md-on-open on md-select, and your method you are calling in md-on-open should return a promise i.e. return deferred.promise. 

If it still doesn't work then you can post a plnkr/fiddler and we can look at the code.

Good luck

**Comment by ogaihtorecic** [comment]
Maybe this can explain:
[https://docs.angularjs.org/api/ngResource/service/$resource](https://docs.angularjs.org/api/ngResource/service/$resource)
> It is important to realize that invoking a $resource object method immediately returns an empty reference (object or array depending on isArray). Once the data is returned from the server the existing reference is populated with the actual data. This is a useful trick since usually the resource is assigned to a model which is then rendered by the view. Having an empty object results in no rendering, once the data arrives from the server then the object is populated with the data and the view automatically re-renders itself showing the new data. This means that in most cases one never has to write a callback function for the action methods.

**Comment by ogaihtorecic** [comment]
This works, but it can be improved:
```
$scope.getUsers = function () {
    var deferred = $q.defer();
    User.get(function(data) {
       $scope.users = $scope.users || data.users;
       deferred.resolve();
    }, function() {
       deferred.reject();
    });
    return deferred.promise;
}
```

**Comment by ogaihtorecic** [comment]
Improved version:
```
$scope.getUsers = function () {
    return User.get(function(data) {
       $scope.users = $scope.users || data.users;
    }).$promise;
};
```
