### ISSUE TITLE
md-menu fails and blocks the page with dynamic menu items

### ISSUE THREAD

**Issue by ddimitrop** [angular/material#4720]
If the menu-items of a md-menu are dynamic (i.e. with ng-repeat) and are completely missing at the time that the menu opens, this does not open at all but instead leaves the scroll overlay and completely blocks the document.

Reason is this line:
https://github.com/angular/material/blob/master/src/components/menu/js/menuServiceProvider.js#L420

To reproduce:
http://codepen.io/anon/pen/yYOwqa

Add a value (i.e.1) in ng-init and everything works fine.
Otherwise its not possible to click the button after attempting to click on the menu, and the menu does not open.

**Comment by jb29** [comment]
Same issue here #4687

**Comment by ThomasBurleson** [comment]
Fixed with SHA 4f841379bdf2.
Here is a updated [CodePen Demo](http://codepen.io/ThomasBurleson/pen/vNKMmM) using bower-material/master and ng v1.4.6.
