### ISSUE TITLE
directive w/ md-sidenav does not properly md-is-locked-open, instead it pushes all content down

### ISSUE THREAD

**Issue by webmandman** [angular/material#4721]
The issue is clear in the screenshot. The md-sidenav is inside my own directive and slides over content just fine from either left or right side. It is only when I use the is-locked-open attribute that it breaks. 

I have tried to use the md-sidenav outside of my own directive and place it right below the body tag. It works fine without the is-locked-open attribute and breaks with that attribute.

Issue can be tested on this codepen: http://codepen.io/webmandman/pen/rOePPV 
If you adjust the screen to less than 1000px the sidenav will change to slide over and it works as it should. 

![2015-09-18 09_54_02-psomas - demo angular app](https://cloud.githubusercontent.com/assets/991677/9965497/78b5ae0c-5deb-11e5-83a0-3c599d1a2ac7.png)

**Comment by topherfangio** [comment]
Please check our [Sidenav Demo](http://localhost:8080/#/demo/material.components.sidenav) to see how it should work. You currently have the sidenav, toolbar and content inside of a container using `layout="column"`, so you've basically told it to render like this.

The sidenav and the content should be in a `layout="row"` container and the content container should have the toolbar and app content.

Here is another demo which has a similar layout: http://codepen.io/topherfangio/pen/LpVWVp

**Comment by webmandman** [comment]
I need to study this grid system. Thank you. I can fix this issue by making the sidenav lock below the main toolbar. But my original intent is to lock the sidenav next to all body content including the main toolbar.

**Comment by topherfangio** [comment]
@webmandman Just put the toolbar inside of the container. We do this on our docs site, so you can probably view the source to see how it's done.

Should be something like this:

```html
<div layout="row">
    <md-sidenav>...</md-sidenav>

    <div layout="column">
        <md-toolbar>...</md-toolbar>
        <md-content>...</md-content>
    </div>
</div>
```

If you need any more help, you might post a question on the [forums](https://groups.google.com/forum/#!forum/ngmaterial). There are a lot of great devs there who are happy to share their solutions ;-)

**Comment by webmandman** [comment]
Thank you for the advice.
