### ISSUE TITLE
mdDialog open/close transitions and viewport change

### ISSUE THREAD

**Issue by saffabook** [angular/material#4725]
Hi there 

There are two queries/suggestions I have. 

First Query. 
I am implementing the mdDialog works perfectly. However I came across this codepen
http://codepen.io/ThomasBurleson/pen/qEBJME
When you close these, the transition goes down. This is a better animation for certain UX situations. 
I tried to mimic this on the below codepen but cant animate it transitioning down on close. 
http://codepen.io/anon/pen/PPNMRN

How would could it be done? Is there a way to add a transition parameter, for example $mdDialog.hide('transitionDown'); // default acting as the second codepen

Second Query. (not sure if its essential but might be of value) 
When opening a dialog on mobile in portrait view, if you change the view to landscape the bottom of the dialog gets cut off and you are unable to get to the buttons below. Its still works as you can just change back to portrait but might be more fluid and easy to use from a clients point of view etc. 
![image](https://cloud.githubusercontent.com/assets/6928921/9976310/e36f7d06-5ee8-11e5-8c52-cef4066152b3.png)

Thank you for the fantastic work btw. Amazing stuff!

Best

**Comment by ThomasBurleson** [comment]
See this for some ideas:  http://codepen.io/ThomasBurleson/pen/qEBJME

> For future reference, please create separate issues for easier resolution and closure.

**Comment by saffabook** [comment]
Thank you for your reply and example. 

I will also bear in mind to keep issues separated.

**Comment by fabiannagel** [comment]
Has this been implemented or why was this issue closed?
