### ISSUE TITLE
md-dialog and md-dialog-content are not documented

### ISSUE THREAD

**Issue by djmarcus1** [angular/material#4728]
The Angular/Material DIRECTIVES sidebar does not show these directives at all.

This is a complex subject that really should have detailed API and a few decent demo examples.

Perhaps someone who is not a newbie (as I am) to Angular/Material could correct this in the next release.

**Comment by ThomasBurleson** [comment]
This is what we have currently: https://material.angularjs.org/HEAD/#/api/material.components.dialog/service/$mdDialog.
Your feedback is useful, however, in that it highlights a confusion point where developers may only search the **Directives** sublist.

**Comment by djmarcus1** [comment]
I had already seen the page (https://material.angularjs.org/HEAD/#/api/material.components.dialog/service/$mdDialog).

In fact, it helped me enough to get me going, but honestly dialogs are a big part of modern user interaction... and they can get fairly complex. Therefore, they should, at the very least, include a formal demo link from that page, and there needs to be a whole discussion with cookbook samples to illustrate how to do top-notch dialogs. I learn fastest by seeing examples. All the progress on my dialogs that I have made have come from seeing CodePen examples.

Don't misunderstand my feedback. I am incredibly impressed with Angular/Materials... its amazing and the best framework I've seen on top of Angular. Yet, the key for its widest adoption is to reduce the learning curve. This can only be achieved by having great documentation and copious examples.

:-)

**Comment by ThomasBurleson** [comment]
The Angular Material Core team completely agrees. Unfortunately, we are focused with 100% capacity on the upcoming v1.0 release: stabilization, polish, and performance are the main focus areas.
Would you be interested in helping with the Dialog docs?

**Comment by djmarcus1** [comment]
For sure.
Is there any information on how to update the docs (and the website pages)?

You can reach me directly at my email of djmarcus with the domain name of m5inc with top level of com.

-David

**Comment by ThomasBurleson** [comment]
@Splaktar - Do you have time to help ramp @djmarcus1 upon the **fork-branch-update-pullrequest** process ?

**Comment by Splaktar** [comment]
Yep, I will contact him in an hour or two.

**Comment by Splaktar** [comment]
Email and Hangouts request sent to @djmarcus1.

In the mean time, please take a look at https://github.com/angular/material/blob/master/docs/guides/CONTRIBUTING.md

**Comment by Splaktar** [comment]
Spoke to him last night and made a lot of progress getting him up and running.

**Comment by topherfangio** [comment]
@Splaktar @djmarcus1 I am pushing this off to the next RC release. Has any progress been made on this yet, or do I need to just start from scratch? :smile:

**Comment by Splaktar** [comment]
From scratch. I got him setup to contribute, but he has been busy with other things. He said that he meant to contribute, but he didn't give an ETA.

**Comment by Splaktar** [comment]
Actually he said that he had some minor updates made locally, but needed to create the PR. That was a month ago though. I will follow up, but I don't think that we should wait longer than another day to improve these docs.
