### ISSUE TITLE
layout='row' alignment issues

### ISSUE THREAD

**Issue by djmarcus1** [angular/material#4729]
I am trying to align on the same row some text followed by an md-select. The results are showing up one row apart.. the md-select seems to force a new line. [CodePen Demo](http://codepen.io/anon/pen/xwObEa)

```htm
    <html>
        <head>
            <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/0.11.0/angular-material.css">

            <script src="script.js"></script>
    
            <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-animate.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-aria.js"></script>

            <script src="https://ajax.googleapis.com/ajax/libs/angular_material/0.11.0/angular-material.js"></script>
        </head>

        <body ng-app="demonstrateProblem">
            <h2>Row alignment issues!</h2>
            <div ng-controller="myController">
      
                <div flex layout-margin layout="row" layout-fill layout-padding>
                    Select:
                    <md-select placeholder="Select a car maker" ng-model="settings.selectedCar">
                        <md-option ng-repeat="carMaker in carMakers" value="{{carMaker}}">{{carMaker}}</md-option>
                    </md-select>
                </div>

            </div>
        </body>
    </html>
```

What I get is:

    Row alignment issues!

    Select:
                 Select a car maker

I am expecting the 'Select:' and the md-select to be on the same row.

While researching this, I noticed that if remove the style import of angular_material.css then the display lines up (but of course I lose the styling).

I have not been able to figure out what causes md-select to start on a new line.

**Comment by mentos1386** [comment]
In latest release attributes aren't used any more. Now you have to use classes instead (documentation us outdated).

You will have to do something like this http://codepen.io/anon/pen/jbrWxL

**Comment by ThomasBurleson** [comment]
@mentos1386 - Allow me to clarify:

Internet Explorer suffers huge performance degradations when using attribute selectors; switching to class selectors is the solution. Normally this internal change would not be acceptable:

*  manually specifying class selectors would be very painful, confusing, and error prone
*  changes to existing applications would be painful and tedious

Fortunately developers **do not need to change anything**.  

The current attribute selectors are **now angularjs directives** that internal transpose their dom settings to the appropriate class styles... this happens **automatically** without any intervention needed from the developer.

Use the attributes AS BEFORE; this is an internal, under-the-hood change only.

**Comment by ThomasBurleson** [comment]
@djmarcus1 - I am investigating a layout issue that your demo reveals. Thank you.

**Comment by djmarcus1** [comment]
Thanks for the quick fix.

At what point can I reference the fix via:

https://ajax.googleapis.com/ajax/libs/angular_material/0.11.1/angular-material.js

**Comment by tuhoojabotti** [comment]
I also have an issue with the layout. I try to use different layout-align based on the viewport, but it doesn't seem to work. Here's a Codepen: http://codepen.io/anon/pen/bVBwvN

**Comment by ThomasBurleson** [comment]
@tuhoojabotti - 

Whenever possible, provide a CodePen demo.
To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by ThomasBurleson** [comment]
@djmarcus1 - we will be releasing v0.11.2 tonight.

**Comment by djmarcus1** [comment]
Quick feedback: I tried the code with the RAWGIT releases. The problem still appears to be there. I will distill my code to a CodePen demo (or plnkr) and keep you posted shortly.

**Comment by ThomasBurleson** [comment]
@djmarcus1 - excellent. A Demo will be very helpful. Thx

**Comment by djmarcus1** [comment]
Here's the CodePen:  http://codepen.io/djmarcus/pen/OypVVe

Just to clarify the issue. I use a layout="row" and have two (text and an md-select) items that I want to appear adjacent to each other on the same row.

The md-select shows up on the next row.

I did try it with version 0.11.1 and it also fails.

**Comment by ThomasBurleson** [comment]
@djmarcus1 - Here is an updated CodePen: http://codepen.io/ThomasBurleson/pen/qOrdmy?editors=110

The Select is not actually on another row... rather it has margins that give it a LARGE row height and the title is aligned top of the row. Using `layout-align="start center" ` gets us to a UX that you want.

> Soon we will be releasing component fixes that allow components to be easily used inline with each other.

**Comment by djmarcus1** [comment]
Dang me. I'm not sure how I could have foreseen this :-(

So, in general, how does one 'debug' these types issue so we can avoid false bug alarms?

**Comment by ThomasBurleson** [comment]
That is the challenge with FlexBox: it can be so hard to track down why it
is not aligning or working.
Ironic that you have to be a Flexbox expert to use Flexbox...

Open the developer tools and inspect the elements. Remember that without
ngMaterial, you could manually add the values and the elements should
layout as desired.
ngMaterial Layout is just sugar that allows you to not worry about the
values; or at least that is the goal.

- Thomas
