### ISSUE TITLE
Dialog error: "Unable to find node 'md-dialog' in element."

### ISSUE THREAD

**Issue by djmarcus1** [angular/material#4735]
My simple dialog is generating the error: "Unable to find node 'md-dialog' in element."

My dialog:

        var val = section.html.valueType.display(section, item.attrValue);
        $mdDialog.show(
            $mdDialog.confirm(
                {
                    ok: 'OK',
                    arialLabel: 'Confirm delete of attribute entry',
                    cancel: 'Cancel',
                    title: 'Confirm delete of attribute entry',
                    content: '<div><bold>Are you sure you want to delete this RBS Affiliate Attribute entry?</bold></div>' +
                             '<br/>' +
                             '<ul>' +
                             '    <li>AttributeValue: <bold>' + section.html.valueType.display(section, item.attrValue) + "</bold></li>" +
                             '    <br/>' +
                             '    <li>AttributeValue: <bold>' + item.effectiveDate + "</bold></li>" +
                             '</ul>'
                }
            )
        ).then(function () {
            $scope.deleteItem(section, item);
        });

My imports are:

    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/0.11.0/angular-material.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=RobotoDraft:300,400,500,700,400italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-animate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.2/angular-aria.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angular_material/0.11.0/angular-material.js"></script>

I set a breakpoint (Chrome) where the error is issued.

Here's the stack trace:

![angular-material-001-2015-09-20_11-16-18](https://cloud.githubusercontent.com/assets/3149616/9981387/a7fa1f0a-5f89-11e5-9d55-26d842e1adff.jpg)

Here's the local variables for function: $mdUtil.extractElementByName

![angular-material 002-2015-09-20_11-23-23](https://cloud.githubusercontent.com/assets/3149616/9981406/1f9684ae-5f8a-11e5-84ad-7a3c4d2a616e.jpg)

![angular-maerial 003-2015-09-20_11-25-22](https://cloud.githubusercontent.com/assets/3149616/9981414/61f6a3a6-5f8a-11e5-91a0-33e50ead430f.jpg)

**Comment by Deadly0** [comment]
The same issue also in demos: https://material.angularjs.org/0.11.0/#/demo/material.components.dialog

**Comment by djmarcus1** [comment]
I followed your link and verified it as well using Chrome.

**Comment by Deadly0** [comment]
@djmarcus1, yes, in 0.11 version you can see bug in demos, but if you choose HEAD (MASTER) version https://material.angularjs.org/HEAD/#/demo/material.components.dialog there is no bug already. Look like it was already fixed and will be released in 0.11.1 soon

**Comment by djmarcus1** [comment]
Is there a way to subscribe to notifications when new releases become available (ex: 0.11.1)?

**Comment by ThomasBurleson** [comment]
@djmarcus1 - please **always** check your bug/request against HEAD before opening a new issue.

**Comment by Splaktar** [comment]
@djmarcus1 there is no way that I know of the subscribe to be notified, but you can check for new releases in the following locations:
https://groups.google.com/forum/#!forum/ngmaterial - new announcement threads like [this](https://groups.google.com/forum/#!topic/ngmaterial/Q7RFKSPde7c)
https://github.com/angular/material - Click branch, then Tags tab
https://material.angularjs.org/HEAD/#/ - Check Latest Release under Documentation Version
https://www.npmjs.com/package/angular-material - Check "0.11.0 is the latest of 17 releases"

**Comment by f1tech** [comment]
Thanks for reporting this. I have the same issue.
