### ISSUE TITLE
md-autofocus is not documented well

### ISSUE THREAD

**Issue by arlowhite** [angular/material#4737]
I wanted the functionality of **md-autofocus**, but never came across a reference to it in the documentation. (It is only mentioned in md-autocomplete) The only way I found out about it was through github issue comments.

Please document md-autofocus in a few more places so developers are more aware of it.
 - Add md-autofocus to the list of attributes in mdInput
 - Mention md-autofocus in mdDialog.

Lower priority (additional ideas)
 - Add reference to it from other containers similar to mdDialog
 - Mention md-autofocus in all input directives that support it: md-contact-chips, md-checkbox, etc. However, this is much more work, and I think if it's in md-input, developers will assume they can use it on these other input components.
 - Add an **Attribute Directives** section in the documentation to document md-autofocus in more detail.

**Comment by amritk** [comment]
+1

**Comment by Splaktar** [comment]
We now have [mdAutofocus docs](https://material.angularjs.org/latest/api/directive/mdAutofocus).
