### ISSUE TITLE
md-tabs doesn't render itself correctly if is used inside md-sidenav. in IE

### ISSUE THREAD

**Issue by kikhtenko** [angular/material#4744]
Hi, I made an example here:
http://codepen.io/anon/pen/xwOrRq

if you use md-tabs in md-sidebar it works fine in Chrome but UI is broken in IE 11.

Regards,

**Comment by ivorobkalo** [comment]
+1

**Comment by kikhtenko** [comment]
This is more about md-sidebar in IE. Any UI will be broken in the right sidenav.

**Comment by kikhtenko** [comment]
http://codepen.io/anon/pen/QjEgYb

**Comment by asadovnikov** [comment]
+

**Comment by medcomcr** [comment]
+1

**Comment by Nickproger** [comment]
+1

**Comment by websirnik** [comment]
The demo above is also broken for me in Chrome. This is related to https://github.com/angular/material/issues/4834
![screen shot 2015-09-26 at 13 20 00](https://cloud.githubusercontent.com/assets/282871/10117512/7af62108-6451-11e5-9b6d-18b8b40b1250.png)

**Comment by jeroenvheel** [comment]
+1

**Comment by kskoropada** [comment]
+1

**Comment by robertmesserle** [comment]
I am not able to recreate this in IE11.  Are there any specific steps needed?  Does screen/browser size matter?

**Comment by robertmesserle** [comment]
Closing for now.  If this issue still exists, please provide steps to recreate against the latest code.

**Comment by austinthedeveloper** [comment]
I did not see this issue when I created my issue: #6420 . My solution will fix that issue.
