### ISSUE TITLE
mdChips should use `ng-readonly` instead of `readonly`

### ISSUE THREAD

**Issue by jjohanning** [angular/material#4746]
user ng-readonly instead of readonly attribute on any component because:

>According to spec, readonly is a boolean attribute, and a boolean attribute is specified as:
>
>The presence of a boolean attribute on an element represents the true value, and the absence of the >attribute represents the false value.
>
>If the attribute is present, its value must either be the empty string or a value that is an ASCII case->insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

https://github.com/kangax/html-minifier/issues/302

**Comment by jelbourn** [comment]
Rewording issue:
Some HTML minifiers will strip the value part of boolean attributes such as `readonly`, `disabled`, and `checked`, which is why there are `ng-disabled`, `ng-readonly`, and `ng-checked`. 

mdChips should follow this pattern.

**Comment by jpolo** [comment]
Same issue for me : it seems that chips are in readonly state only using markup ```readonly="true"```, not ```readonly``` and not ```ng-readonly="true"``` (which actually sets ```readonly="readonly"```)

Angular material version : 1.0.7
