### ISSUE TITLE
MD_FAB_SHARED CRITICAL BUG: md-input ignores SPACE(s)

### ISSUE THREAD

**Issue by kschwidder** [angular/material#4747]
I have investigated a weired situation using ui-router, fab-dial and angular-material:

I am switching between views via a fab-speed-dial 

1) Open a dialog with an input element and enter text including spaces works fine.
2) Switch to another page with fab-speed-dial and ui-router $state.go.
3) Open another dialog with an input element and enter text. THERE YOU CAN NOT ENTER SPACE
ANYMORE
4) Step back to dialog 1) and YOU CAN NOT ENTER SPACE TOO.

I am using angular 1.4.4 and angular material master. Does anyone has experienced the same issues ??

It only applies to spaces therefore I do not know if angular material does something with the keyboard handling.

**Comment by kschwidder** [comment]
I am still investigating and have figured out that ui-sref might be the root-cause.

**Comment by kschwidder** [comment]
I have fixed the error in the following module
 angular.module('material.components.fabShared', ['material.core'])
    .controller('FabController', FabController);

by uncommenting the SPACE preventDefault.

    function keyPressed(event) {
      switch (event.which) {
   ==>>>    // case $mdConstant.KEY_CODE.SPACE: event.preventDefault(); return false;
        case $mdConstant.KEY_CODE.ESCAPE: vm.close(); event.preventDefault(); return false;
        case $mdConstant.KEY_CODE.LEFT_ARROW: doKeyLeft(event); return false;
        case $mdConstant.KEY_CODE.UP_ARROW: doKeyUp(event); return false;
        case $mdConstant.KEY_CODE.RIGHT_ARROW: doKeyRight(event); return false;
        case $mdConstant.KEY_CODE.DOWN_ARROW: doKeyDown(event); return false;
      }
    }


This behaviour occurs in IE, Safari, Firefox and Chrome and is a BUG,

**Comment by topherfangio** [comment]
This should be fixed by PR #4681 which ensures that the component releases keyboard focus on `$destroy`.

@ThomasBurleson Do you think we can get that merged in for 11.1? I did my review, and it looks good to me.

**Comment by topherfangio** [comment]
@kschwidder The PR I mentioned was just merged into master; can you please give it a try and see if that fixes the issue?

**Comment by kschwidder** [comment]
@topherfangio I have tested heavily and it is fixed ! Thx a lot :+1:
