### ISSUE TITLE
md dialog not closing on mobile device

### ISSUE THREAD

**Issue by Duovili** [angular/material#4748]
I can see that the button is being clicked/activated but the modal is not closing. I works fine in chrome and on other devices but on a shitty android it breaks.

**Comment by HendrikWansing** [comment]
md-dialog is not closeable on iPhone6+ and this is a blocker.
With #master it is fixed.
Is there a way to fix it temporarily? I can't include the master version in our project.

**Comment by Duovili** [comment]
I didnt even test it on the iphone yet. I was having the issue on an android device. What is the difference between #master and the normal release?

**Comment by ThomasBurleson** [comment]
Please test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).
Can you confirm the issue still exists with the above versions ?

**Comment by HendrikWansing** [comment]
As I wrote before, it is already fixed on master.
But is there a way to overwrite the breaking change without installing the master version?
