### ISSUE TITLE
md-datepicker required icon is inconsistent with md-input-container and md-icon

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#4756]
When md-datepicker is used, an icon is added by default.

Expected behaviour: User can specify md-icon within an md-input-container if they want one.

Also:
 - The whitespace to the left and right of the icon is different to that added when using an input with md-input-container and md-icon.
 - Why is the icon clickable?  Is that a convention?  I'm not sure our users would discover it if all of the other inputs with icons are not clickable.

Related to: https://github.com/angular/material/issues/4233

**Comment by jelbourn** [comment]
It's a common convention for datepickers to have an adjacent icon that opens the calendar:
[jQuery UI](https://jqueryui.com/datepicker/#icon-trigger)
[Kendo UI](http://demos.telerik.com/kendo-ui/datepicker/index)
[Angular UI bootstrap](https://angular-ui.github.io/bootstrap/#/datepicker)

If you want, you can hide the icon yourself with:
```css
.md-datepicker-button {
  display: none;
}
```

**Comment by bluebirdtech** [comment]
But all of these examples have the button on the right - the same placement as the drop down arrow here.

I don't think users will think to click on the icon, especially when there's the drop down button already, and it's not consistent with md-icons within md-input-container which are for a hint/layout only and not interactive.  Being clickable isn't hurting anything of course.

I'm actually keeping the icon in our app, but it would be so easy for the developer to add md-icon I wondered if it would be worth the user being explicit to keep consistency with how icons are applied to inputs elsewhere.

Final thing; if we're keeping the icon, can the spacing to the left and right match a regular md-input-container with md-icon?  Curious to know why this is different.  We have other elements in the form and need it all to line up neatly, eg:

![md-datepicker-icon-spacing](https://cloud.githubusercontent.com/assets/3141867/10033621/7d888e6e-6182-11e5-8b4d-6fa64599f048.png)

**Comment by jelbourn** [comment]
You can customize that spacing by changing the `margin-left` on `.md-datepicker-input-container`

**Comment by bluebirdtech** [comment]
Thanks, and [that's what I've done](https://github.com/angular/material/issues/4233#issuecomment-142058002) to get the above.  I'm wondering why it's not consistent by default?

**Comment by jelbourn** [comment]
We're following an unpublished spec for the datepicker from the Material Design UX team. Seems like there's some inconsistency there. This might be resolved by the time the spec is published.

**Comment by bluebirdtech** [comment]
@jelbourn Thanks for the clarification.

**Comment by fabiusss** [comment]
+1
