### ISSUE TITLE
md-select broken on Chrome on iPad

### ISSUE THREAD

**Issue by jeffmcardle** [angular/material#4757]
When trying to bring up the dropdown, it just disappears without letting you select an item.

**Comment by barryvdh** [comment]
I have this issue on Cordova on the iPad, with latest version (0.11.0). Not with the regular ipad browser..

**Comment by barryvdh** [comment]
Reverting to 0.10.1 does work, but the 0.11.0/rc1/2 releases have the same problem..

**Comment by jsmylnycky** [comment]
:+1:  Would really like to see a fix for this

**Comment by rschmukler** [comment]
Possible reference to #4296

**Comment by jeffmcardle** [comment]
Yeah, probably the same issue.. The demo page has the issue when I use Chrome. iOS 9, iPad Air 2.

**Comment by mighe** [comment]
It seems the same issue, it happens even with the demo. iOS 9, iPhone 6 or iPad mini 3

**Comment by barryvdh** [comment]
Any workarounds for this? Kind of a blocker for my new app release.

**Comment by barryvdh** [comment]
Thanks! Can confirm this fixes the select issues!
