### ISSUE TITLE
md-datepicker displays date in different format from Chrome to Safari

### ISSUE THREAD

**Issue by julbr** [angular/material#4759]
To reproduce:
1. with Chrome, visit the (demo page for md-datepicker)[https://material.angularjs.org/latest/#/demo/material.components.datepicker]
Dates display as `9/21/2015`
2. with Safari, visit the same page. Dates display as `September 21, 2015`.

Besides fixing this difference of format display between browsers, it would be nice to be able to manually set the desired pattern format for the date display.

**Comment by kschwidder** [comment]
Set the format in $mdDateLocalProvider or via $mdDateLocal directly.

I did it as follows:
$mdDateLocale.formatDate = function (date) {
                        return moment(date).format(dateFormat);
                    };

**Comment by julbr** [comment]
Works like that, thanks!

**Comment by LeonardoGuimaraes** [comment]
How to format the output value (the value that goes to controller)? I tried this code and it just format the input value.

**Comment by Gur-deep** [comment]
How can i format date without moment.js like this `dd-MM-yyyy`
