### ISSUE TITLE
md-virtual-repeat fails to paint correctly after delayed fill

### ISSUE THREAD

**Issue by elubin** [angular/material#4761]
A small fiddle to recreate the example... in my code it's actually Ajax

http://jsfiddle.net/elubin/92b5yzg7/

The virtual scroll doesn't paint correctly until the user starts to interact with it.

**Comment by RolandHeath** [comment]
This may still be an issue, but your fiddle is using angular 1.3.15, and angular-material 0.10.1.
You should probably update those resources first.

**Comment by ThomasBurleson** [comment]
Please test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by elubin** [comment]
this is fixed in master branch.  thank you!

http://jsfiddle.net/elubin/swj2nm1d/
