### ISSUE TITLE
resize on md-tabs broken with AMD 0.10.1 and 0.11.0

### ISSUE THREAD

**Issue by anupbelambe** [angular/material#4765]
Resize the tabs demo page till you get the navigation arrows and navigate to tab three.

https://material.angularjs.org/0.11.0/#/demo/material.components.tabs
![tabs_amd_0 11 0](https://cloud.githubusercontent.com/assets/72758/10011784/71a289d4-611d-11e5-942c-3fb15ff17d42.PNG)

Now maximize the browser and see that the tab one is still hidden and the navigational arrow is disabled.
![tabs_amd_0 11 0_maximized](https://cloud.githubusercontent.com/assets/72758/10011813/ab6ca51e-611d-11e5-8979-466925ee679f.PNG)

The same was working fine in 0.10.0 and seems to be broken in 0.10.1.

Appreciate any help on this.

**Comment by robertmesserle** [comment]
@anupbelambe I believe this is already resolved.  Closing the issue now, but please confirm that you are no longer experiencing this issue.
