### ISSUE TITLE
md-tabs transition - when direction is switched from ltr to rtl, tab transition should switch

### ISSUE THREAD

**Issue by tonyawad88** [angular/material#4768]
Hello,

This might be minor on your list, but it would be great if the tabs slide transitions switched with the direction. 

For example, when the document direction is from left-to-right, the tab transition is slide-left when the tabs-index goes from 0 to 1+ and slide right when it goes from index 1+ to 0. (this is correct)
Now when the document direction is from right-to-left, the tab transition should be slide-right when the tabs-index goes from 0 to 1+ and slide left when it goes from 1+ to 0. 

Thank you !

**Comment by tonyawad88** [comment]
@ThomasBurleson What do we mean by "Deprecated" tag ? (just out of curiosity) It will be fixed in Angular 2 ?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
