### ISSUE TITLE
md-toolbar and md-menu button align issue on small screens

### ISSUE THREAD

**Issue by norkunas** [angular/material#4769]
http://codepen.io/anon/pen/wKWQEb

Desktop:
![image](https://cloud.githubusercontent.com/assets/2722872/10016998/a6b546dc-6133-11e5-9155-a8e4ce261445.png)

Small screen:
![image](https://cloud.githubusercontent.com/assets/2722872/10016988/98926602-6133-11e5-9a8d-9defb30a1b32.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
