### ISSUE TITLE
$mdToast.build() documentation

### ISSUE THREAD

**Issue by Yimiprod** [angular/material#4770]
The documentation for `$mdToast.build()` is unclear on how to use it.
For example the methode `.scope()` doesn't exist even if it's in the `.show()` options (like the build doc said all from show are available)

**Comment by ddjonline** [comment]
+1 please at even a simple example so we can use it as intended (without having to dig through the material source code to guess)

**Comment by kdekooter** [comment]
I am sorry but the documentation for `build()` is still very terse.

> a $mdToastPreset with the chainable configuration methods for shows' options (see below).

But there is nothing to be found below...
