### ISSUE TITLE
md-select on mobile

### ISSUE THREAD

**Issue by jaspersorrio** [angular/material#4771]
Hi guys, md-select seems to break on mobile. I am using iOS 8 and the browser that i am using is safari.
I apologise if this is a duplicate of any post. But i can't seem to find any similar issues on Github or Stackoverflow

I am using:
AngularJs 1.3.15
Angular Material 0.10.0

# Doesn't scale to height
When i click on the select, only the first option appears.
![fullsizerender 2](https://cloud.githubusercontent.com/assets/10573718/10018238/ba17455c-6167-11e5-85dd-7b4f170b9602.jpg)

## Quick Workaround
A quick workaround was to use CSS to increase the height of the md-select container only on media screen

```
md-select-menu{
			height: 500px;
		}
```

## Result of workaround:
![fullsizerender](https://cloud.githubusercontent.com/assets/10573718/10018280/0ce51700-6168-11e5-8f3d-53f1f88a29cd.jpg)

But i feel that all of this should be built into the framework.

# Doesn't have shadows 
md-select-menu is supposed to have a shadow surronding it.

This photo was taken on a desktop of the same code:
<img width="1318" alt="screen shot 2015-09-22 at 8 29 04 pm" src="https://cloud.githubusercontent.com/assets/10573718/10018362/b7f19150-6168-11e5-8d94-3b4f472bc4e6.png">

**Comment by ThomasBurleson** [comment]
To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
