### ISSUE TITLE
datetime-local on chrome desktop gets the native datepicker hidden

### ISSUE THREAD

**Issue by sombriks** [angular/material#4774]
input type="datetime-local" seems to be making his way to the main spec. 

when using this component with angular-material on google chrome, it shows the picker indicator on the right side of the field but the picker itself is shadowed.

http://imgur.com/8K5EMMN (unable to see the datepicker as it can be seen [here](http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_datetime-local_value))

on chrome desktop it is shadowed somehow.

on mobile the picker pops out and seems pretty ok.

**Comment by ThomasBurleson** [comment]
Please use mdDatePicker.
