### ISSUE TITLE
mdDialog renders `<p>` as text

### ISSUE THREAD

**Issue by jelbourn** [angular/material#4775]
When the mdDialog code goes to wrap the content in a `<p>` element, it is instead wrapping the *text* content with `<p>` ... `</p>`

Reproduction: http://codepen.io/anon/pen/gaMeLj

**Comment by ThomasBurleson** [comment]
The issue here is the difference between using

```html 
  <md-dialog-content style="max-width:800px;max-height:810px; ">
        {{ ctrl.content }}
  </md-dialog-content>
```
```js
function DialogController($scope, $mdDialog) {
  this.content = "A paragraph";
}
```

vs the API approach:

```js
$mdDialog.alert().content('A paragraph');
```

**Comment by ThomasBurleson** [comment]
Fixed.
