### ISSUE TITLE
Using an mdTooltip inside an mdSubheader causes Firefox to hang

### ISSUE THREAD

**Issue by alexandrebrasil** [angular/material#4777]
I'm trying to use an mdTooltip to show extra information when a user hovers on the text contained in an mdSubheader, and it works fine on both Chrome and IE but, on Firefox for some reason it stalls until the browser prompts me giving the option to interrupt the script. I've tried to let the script run to completion several times, but it never ends.

The following error is shown on Firefox console when it stalls:
```
"Error: [$rootScope:inprog] $digest already in progress
http://errors.angularjs.org/1.4.5/$rootScope/inprog?p0=%24digest
minErr/<@http://localhost:8080/sgo/js/lib/angular.js:68:12
beginPhase@http://localhost:8080/sgo/js/lib/angular.js:16235:1
$RootScopeProvider/this.$get</Scope.prototype.$apply@http://localhost:8080/sgo/js/lib/angular.js:15976:11
timeout/timeoutId<@http://localhost:8080/sgo/js/lib/angular.js:17753:25
completeOutstandingRequest@http://localhost:8080/sgo/js/lib/angular.js:5490:7
Browser/self.defer/timeoutId<@http://localhost:8080/sgo/js/lib/angular.js:5762:7
```

The following code reproduces the error on my environment (Firefox version 41.0) consistently:
```html
<md-subheader class="md-warn" layout-align="center center">
   Dummy text
   <md-tooltip>* Extra info.</md-tooltip>
</md-subheader>
```

**Comment by topherfangio** [comment]
I am investigating this now.
