### ISSUE TITLE
Latest commit broke md-maxlength

### ISSUE THREAD

**Issue by trimox** [angular/material#4783]
Check demo site with latest commit. Chrome displays correctly; however Firefox and IE display text length above input elements now.

**Comment by ThomasBurleson** [comment]
Which last commit? Can you be more specific ?

**Comment by topherfangio** [comment]
That would be commit 3d0b4181e1b7e58e5a606c9d13b59d97a0ce8b5a which adds support for multiple error messages.

I'll look at it now.

**Comment by edbentinck** [comment]
md-maxlength still appears broken (`v0.11.2`), but not for the reason mentioned above.

md-maxlength incorrectly marks the input field as erroneous even when it's correct. [Here's a demo of the error](https://codepen.io/anon/pen/yYMoJW), copied from the original demo site. [It doesn't happen in 0.11.0](https://material.angularjs.org/0.11.0/#/demo/material.components.input).

**Comment by topherfangio** [comment]
@edbentinck Can you please open a separate issue for this? This issue and my commit specifically dealt with how the messages were displayed/styled, so I don't think it would affect the actual operation of `md-maxlength`.

**Comment by edbentinck** [comment]
@topherfangio Actually I've since submitted a PR for this. It's a nice quick one, so if you could review it that would be great. Cheers

**Comment by topherfangio** [comment]
@edbentinck Can you post a link to the PR? I'm not seeing it in the issue history :-)

**Comment by edbentinck** [comment]
@topherfangio Sorry, should have been clearer. It's PR [`#5011`](https://github.com/angular/material/pull/5011) :)
