### ISSUE TITLE
md-autocomplete: md-not-found flashes up briefly when md-items bound to a promise

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#4788]
Repro:
http://codepen.io/anon/pen/PPGoba

Press a key and you should see the md-not-found template show briefly and disappear before the promise is resolved.

Update: It seems something still flashes up even when there's no md-not-found template specified: http://codepen.io/anon/pen/bVwGqO

**Comment by topherfangio** [comment]
I believe this is a duplicate of #4665. Do you agree?

**Comment by bluebirdtech** [comment]
Hard to say for sure. Looks related, but I don't think it's entirely the same. When bound to a promise it's flashing something immediately on keypress. It's not just the behaviour when there's no data, it's the behaviour when it doesn't know what data there is.

**Comment by topherfangio** [comment]
@bluebirdtech Okay, thanks for reviewing. We will keep these as separate for now.
