### ISSUE TITLE
md-select value unexpected append to previous value

### ISSUE THREAD

**Issue by tommy8694** [angular/material#4793]
in my case, the md-select select item is triggered by other events. If it triggers again, the label of the md-select shown will be 'appended' to previous value. I didn't put the multiple attribute in the md-select tag.  However, the model of the md-select is normal.
the label shown in md-select are as follows:
first time: label1
second time: label2 , label1, label2
third time: label3, label1, label3, label2

**Comment by rschmukler** [comment]
Please submit a demo showing the behavior you are running into and we will take a look!

**Comment by garaboncias** [comment]
http://codepen.io/anon/pen/JYJaKg?editors=101
happens only if a $scope.$watch is bounded after controller constructor. 
If you remove $timeout wrapper is work as expected.
