### ISSUE TITLE
left sidenav width

### ISSUE THREAD

**Issue by no-more** [angular/material#4794]
Hi,

I was looking in the material design spec and it does not seems to fix a specific width for the left sidenav (only a maximum of 400dp).
I think the current sidenav is to wide on most screens, would it be possible to remove the current 304px width in order to fit the content or define a parameter to the sidenav directive ?
On material design doc page you also override this default width.
An other way would be to add in the documentation the way to change the width with css.

What do you think about this ?

Thanks.

**Comment by paulflo150** [comment]
You can look at the docs site:
````
<md-sidenav class="site-sidenav ... 

.site-sidenav, .site-sidenav.md-locked-open-add-active, .site-sidenav.md-locked-open {
    width: 256px;
    min-width: 256px;
    max-width: 256px;
}
````

or override:
````
md-sidenav.md-locked-open {
    width: 304px;
    min-width: 304px;
    max-width: 304px;
}
````

**Comment by ThomasBurleson** [comment]
Would you like to submit a PR with doc improvements documenting the how to change the width of the SideNav?

> I also think we need to provide some responsive sizes for SideNav
```scss
@media screen and (max-width: $layout-breakpoint-sm) { ... }
@media screen and (max-width: $layout-breakpoint-gt-sm) { ... }
@media screen and (max-width: $layout-breakpoint-md) { ... }
```

**Comment by EladBezalel** [comment]
@no-more can you link where did you read that the maximum width is 400dp?

**Comment by no-more** [comment]
Hi,

Yes the material design specification is here : http://www.google.com/design/spec/layout/structure.html#structure-side-nav
It says 400dp for desktop and 320 for mobile.

**Comment by EladBezalel** [comment]
@no-more awesome! A PR will be suggested soon :) thanks!
