### ISSUE TITLE
Angular Material home page – closing custom dialog issue

### ISSUE THREAD

**Issue by a8775** [angular/material#4795]
1.	Open the https://material.angularjs.org/0.11.0/#/
2.	Select “Demos”
3.	Select “Datepicker” or any other demo
4.	Select “Dialog”
5.	Select “Custom Dialog”
6.	Press “back” on browser or backspace on keyboard
7.	It’s not possible to close the dialog

Tested on FF 40.0.3, Edge 20.10240.16384, Chrome 45.0.2454.99

**Comment by ThomasBurleson** [comment]
https://material.angularjs.org/HEAD/#/
