### ISSUE TITLE
More detailed Layout & Flex attribute documentation

### ISSUE THREAD

**Issue by EricBichara** [angular/material#4798]
From reading through many issues on the flex and layout attributes, there seems to be a lot of confusion on how to use them correctly, f.ex 

1) flex vs layout-fill
2) Does flex only stretch the component in the orientation of the layout (ie layout=row flex only horizontally)

Would be great if someone could shed some light on this and update the documentation.

**Comment by ThomasBurleson** [comment]
That is out-of-scope for what Angular Material provides.
