### ISSUE TITLE
Update md-whiteframe-z* to align with Material Elevation spec

### ISSUE THREAD

**Issue by munaf** [angular/material#4803]
Currently, ```md-whiteframe-z*``` only supports 4 levels. The Material Spec includes 24. 

Spec:
https://www.google.com/design/spec/what-is-material/elevation-shadows.html

Code sample from a Google Engineer working on Material:
http://codepen.io/shyndman/pen/MaYoaV

Additional request: can we use a class name that maps to the design spec, such as ```md-elevation-X``` or something similar?

**Comment by soutlink** [comment]
We already have md-whiteframe-dp with 24 levels

https://github.com/angular/material/blob/master/src/components/whiteframe/whiteframe.scss

**Comment by jb29** [comment]
This should be added to the documentation.

**Comment by soutlink** [comment]
It is already on master:

https://github.com/angular/material/blob/master/src/components/whiteframe/demoBasicUsage/index.html
https://material.angularjs.org/HEAD/#/demo/material.components.whiteframe

**Comment by EladBezalel** [comment]
closed with #4706
