### ISSUE TITLE
<md-datepicker> by default extends out of viewport

### ISSUE THREAD

**Issue by lscordilis** [angular/material#4804]
![image](https://cloud.githubusercontent.com/assets/12753650/10055831/521783e6-6206-11e5-8cf6-188df0217d65.png)

If there isn't enough space at the bottom or right edge of the viewport for the element, it should extend in the opposite direction, not run off the screen.

**Comment by lscordilis** [comment]
Maybe give it a position mode option such as ```md-position-mode="target-right target"```
found here: https://material.angularjs.org/latest/#/demo/material.components.menu

**Comment by jelbourn** [comment]
This should be fixed in 0.11.1 for most cases, with additional fix for #4828
