### ISSUE TITLE
md-button: ripple effect not working properly in sideNav

### ISSUE THREAD

**Issue by dmackerman** [angular/material#4807]
This appears to be the case for any button in a sidenav for us.  The "Help" button is not in a sidenav and ripples properly. In this GIF I am "pressing and holding" to make the ripple appear.

See GIF: 

![ripples](https://cloud.githubusercontent.com/assets/289938/10059217/a3e628f6-61fe-11e5-9e52-428d9b891170.gif)

Happens when `href=""` or a regular `button` element is used. Version `0.11`

This can also be seen in the docs.

**Comment by mantissa7** [comment]
I'm having a similar issue in my side nav. The ripple will fire, but only from the bottom centre of the button, and not a full ripple. Holding click has the same effect, but with a stronger ripple, which doesn't disappear until I click away.

**Comment by topherfangio** [comment]
I thought I saw a fix for this in 11.1, but I just tested the [Sidenav demo](https://material.angularjs.org/HEAD/#/demo/material.components.sidenav) and it appears to still be broken.

Just open the right sidenav and click the close button to see the issue.

**Comment by mantissa7** [comment]
Ok it seems I fixed this problem by just removing <code>class="md-icon-button"</code> from the <code>md-button</code> tag.
