### ISSUE TITLE
md-highlight-text doesn't work when bound to anything other that "searchText"

### ISSUE THREAD

**Issue by akdor1154** [angular/material#4812]
```html
<md-autocomplete
	md-search-text="groupSearchText"
	md-items="group in ['aaa', 'bbb', 'ccc', 'ddd'].filter(item => item.indexOf(groupSearchText) > -1)"
	md-item-text="group"
	>
	<span md-highlight-text="groupSearchText" md-highlight-flags="i">{{group}}</span>
</md-autocomplete>
```
^^ this doesn't highlight.

```html
<md-autocomplete
	md-search-text="groupSearchText"
	md-items="group in ['aaa', 'bbb', 'ccc', 'ddd'].filter(item => item.indexOf(groupSearchText) > -1)"
	md-item-text="group"
	>
	<span md-highlight-text="searchText" md-highlight-flags="i">{{group}}</span>
</md-autocomplete>
```
^^ this does highlight, even though I've never bound searchText.
md-items is not what I'm literally using (I'm using normal es5 functions in the controller); I'm just writing it this way for brevity.

**Comment by PDSBGreg** [comment]
Good find. I couldn't figure out why the value I had set for md-search-text on the md-autocomplete was not working in the md-template-item.

The problems looks like it's coming from the line...

if (regex === null || state.term !== prevState.term) {

...in https://github.com/angular/material/blob/v0.11.0/src/components/autocomplete/js/highlightController.js

If any value other than searchText is used as md-highlight-text attribute value in the HTML, both state.term and prevState.term are always undefined, so the regEx is not correctly created.

I can't figure out beyond (or prior to I suppose) that point as to what is happening. It looks like the MDHighlight directive used by MDAutoComplete might have its own scope (or a different scope than the auto complete itself).

**Comment by Pelu2k12** [comment]
+1

**Comment by thomaswdufour** [comment]
Has there been any update on this?

**Comment by Portical** [comment]
+1 can't use multiple autocompletes with this bug.
