### ISSUE TITLE
 <md-backdrop> may not work properly in a scrolled, static-positioned parent container.

### ISSUE THREAD

**Issue by vijj** [angular/material#4813]
md-backdrop{
  position: fixed !important;
}

i tried this but not working still getting warnings if any suggessions please

**Comment by wangxiao** [comment]
+ 1

**Comment by EladBezalel** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  [CodePen template](http://codepen.io/team/AngularMaterial/pen/BNYppz)
*  [Plunkr template](http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview)

**Comment by EladBezalel** [comment]
closed due to inactivity, please check this issue on HEAD, if it's still happening please let me know and i'll reopen this issue.
