### ISSUE TITLE
TemplateUrl not working Properly

### ISSUE THREAD

**Issue by savygandhi** [angular/material#4814]
$scope.newNoteMaterial = function(ev) {
        
        $mdDialog.show({
          controller: DialogController,
          templateUrl: "newNote.tmpl.html",
          parent: angular.element(document.body),
          targetEvent: ev,
          clickOutsideToClose:true
        })
        .then(function(saveNote) {
          $scope.currentNote = 'You said the information was "' + answer + '".';
        
      });
    };

I am using a new Note Template but it is not working properly, A dialog appears with the content of only base.html but eventually I don't want the base file to be extended. I am using ui-router as well for other things. I am not able to figure this out.

**Comment by dmackerman** [comment]
What do you mean by "don't want the base file to be extended"?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
