### ISSUE TITLE
Link button in md-menu layout issue

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#4818]
When a menu item is a link button rather than a regular button, the text gets misaligned vertically (2 bottom menu items in this screenshot):

<img width="177" alt="screen shot 2015-09-24 at 11 51 58 am" src="https://cloud.githubusercontent.com/assets/9092817/10078818/ae9e65fe-62b4-11e5-88a7-cb10ea9506f5.png">

I can't figure out what css rules cause this, but it's the same in Chrome, Firefox and Safari.

**Comment by ivan7237d** [comment]
PS in my own code I fixed this by setting line height to be 48 px instead of 36, but don't know if it's generally the best solution.

**Comment by EladBezalel** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  [CodePen template](http://codepen.io/team/AngularMaterial/pen/BNYppz)
*  [Plunkr template](http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview)

**Comment by ivan7237d** [comment]
Sorry, my mistake, was using an older version, this was fixed in d0e8daf.
