### ISSUE TITLE
Can't close a toast from code

### ISSUE THREAD

**Issue by Sebastien-Meiffren** [angular/material#4824]
Hi,

I'm trying to close automatically a toast based on an event that I'm catching but nothing happens. 

        var toastLoading = null;
        $scope.$on('loadingNotification', function(event) {
            toastLoading = $mdToast.show(
                 $mdToast.simple()
                    .content("Chargement en cours ...")
                    .position("top right")
                    .hideDelay(6000)
            );
        });
        $scope.$on('stopLoadingNotification', function(event) {
           if(toastLoading != null) {
               console.log("stop toast", toastLoading);
               $mdToast.hide(toastLoading);
               $mdToast.cancel(toastLoading);
           }
        });

I'm probably missing something or it doesn't work. Thanks

**Comment by EladBezalel** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  [CodePen template](http://codepen.io/team/AngularMaterial/pen/BNYppz)
*  [Plunkr template](http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview)

BTW.
You can use 
``` js
if (toastLoading) {
 // ...
}
```

**Comment by mckenzielong** [comment]
A poor attempt at reproducing the issue.  Was not able to reproduce, but it could be a good starting point: https://codepen.io/mckenzielong/pen/EVNPrE

```
       if(toastLoading != null) {
           console.log("stop toast", toastLoading);
           $mdToast.hide(toastLoading);
           $mdToast.cancel(toastLoading); //this will possibly do something unintended
       }
```
Your promise will not be rejected, but resolved.  Hide will resolve the promise and pop the element out of the toast service's stack.  Cancel will get called, but the stack in this case is empty.  The cancel will still return a promise that will be resolved, but your fail path on the 'toast' promise won't be used.

**Comment by Sebastien-Meiffren** [comment]
Hi,

Thanks for the feedbacks. I've been trying to reproduce in codepen based on from @mckenzielong 's and I can't :'(
https://codepen.io/anon/pen/LpbNmP

To be honest I'm not sure I understand the promise part (also included in the documentation) => I'm French But from what I understand from my codepen and @mckenzielong is that I can pass to the hide or close the return of the toast or the definition of it and it should be closing it.

What strange, to me, is that in my logged, after adding a "then" function with a log, as shown by @mckenzielong, I can see that it has been called. So is there a way to see if there was an error or something ?

**Comment by Sebastien-Meiffren** [comment]
Oh god, I think I've found my issue. I was trying to close the toast before it was completely loaded.... (no comment)
I've added a timeout for 1s and it "fixed" my problem.

**Comment by topherfangio** [comment]
@Sebastien-Meiffren Since you found the issue, are we good to close this? :-)

**Comment by Sebastien-Meiffren** [comment]
Sorry, forgot to close !
