### ISSUE TITLE
How can I port datepicker from 0.11.0 to 0.10.1?

### ISSUE THREAD

**Issue by vijayrawatsan** [angular/material#4825]
Can anyone point me in the right direction.
I know I should upgrade to 0.11.0 but I have already invested a lot in a theme which is using 0.10.1.

Please help if possible.

**Comment by EladBezalel** [comment]
@vijayrawatsan why won't you upgrade to 0.11.0 and see if anything breaks?
You can take a look at our [CHANGELOG](https://github.com/angular/material/blob/master/CHANGELOG.md) and see breaking changes there,
also these kind of questions are very welcome at our [forum](https://groups.google.com/forum/#!forum/ngmaterial) so please move this question there..
