### ISSUE TITLE
Official demo Content Chips shows blank

### ISSUE THREAD

**Issue by fannheyward** [angular/material#4833]
![chips](https://cloud.githubusercontent.com/assets/345274/10093786/49c6a7aa-638a-11e5-958d-dcf782ac5f27.png)

Official demo: https://material.angularjs.org/latest/#/demo/material.components.chips

Chrome: 47.0.2516.0
Safari: 8.06

**Comment by fannheyward** [comment]
More info:

HEAD code works: https://material.angularjs.org/HEAD/#/demo/material.components.chips
0.10.1 works: https://material.angularjs.org/0.10.1/#/demo/material.components.chips
0.11.0 failed.

**Comment by ferc** [comment]
Duplicated (and fixed): https://github.com/angular/material/issues/4660
Solved in next version
