### ISSUE TITLE
Firefox Subheader/Menu z-index

### ISSUE THREAD

**Issue by pulse14** [angular/material#4835]
The subheader is over the menu in firefox 41.0. It works with z-index 1, strange. 
![n2pyjlyg](https://cloud.githubusercontent.com/assets/8348807/10096419/a079cf8c-6371-11e5-85d6-1995e7dd9527.png)

**Comment by topherfangio** [comment]
All of our zIndexes are based off of variables; we should look at subheader/menu to make sure they are using the proper ones.
