### ISSUE TITLE
Scrollable content on child flex item - row layout

### ISSUE THREAD

**Issue by parky128** [angular/material#4837]
I am trying to get a single child flex item inside a row layout to scroll independently.

I can only get the entire parent container to scroll, see - http://codepen.io/anon/pen/merXpr

What I have is a large list of items in the first container and when clicking an item, content gets shown in the second container.

Is this possible to get the child items to scroll independently?

**Comment by CLGitDev** [comment]
Will something like this work for you?
http://codepen.io/anon/pen/wKowqJ

**Comment by parky128** [comment]
Hi - thanks for the reply, but it still causes both items to scroll together. I can see what you have tried to do but it gives the exact same affect as my original codepen. Does it behave differently for you? Do you see only the first item scroll?

**Comment by CLGitDev** [comment]
@parky128 Please try again.
http://codepen.io/anon/pen/wKowqJ

There's one thing to bare in mind though, according to the API reference:
<i>Cards have constant width and variable heights; where the maximum height is limited to what can fit within a single view on a platform</i>
https://material.angularjs.org/latest/#/api/material.components.card/directive/mdCard

**Comment by parky128** [comment]
That's just what I needed, thank you. I can probably do without using the card too, so shouldn't be a problem for me.

Thanks!

**Comment by parky128** [comment]
Ah - I just realised something, it only works since there's a fixed height.

Take a look at the demo now - http://codepen.io/anon/pen/wKowqJ

Resize the preview pane and now the whole area scrolls. Is there a way to get this to work dynamically?
