### ISSUE TITLE
md-progress-circular component always stretches it's parent block to be minimum 100px by 100px.

### ISSUE THREAD

**Issue by Lander** [angular/material#4839]
See example here: https://codepen.io/anon/pen/xwEmwX

**Comment by ThomasBurleson** [comment]
To support better resolution when scaled larger, the progress Circular indicator is initially rendered to 100x100 px and then scaled down 0.5. You can adjust its bounds with margin offsets or absolute positioning.

https://codepen.io/ThomasBurleson/pen/PPbZKv

**Comment by Lander** [comment]
It sounds like a hacky solution and won't support md-diameter values change.

**Comment by aolu11** [comment]
+1

**Comment by woutderooms** [comment]
+1

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you look into this plz?

**Comment by johnSowingo** [comment]
+1
