### ISSUE TITLE
Unable to find node 'md-dialog' in element. (using templateURL)

### ISSUE THREAD

**Issue by Akxe** [angular/material#4842]
This is dialog set up:
```
$mdDialog.show({
	controller: loginController,
	templateUrl: 'dialog/login.html',
	parent: angular.element(document.body),
	targetEvent: ev,
	clickOutsideToClose: true
})
```
dialog/login.html:
```
<md-dialog aria-label="Login form" class="md-padding">
	<form>...</form>
</md-dialog>
```
I do not do anything with the dialog whatsoever...
angular-material.js : L1004
```
element => [<div class=​"md-dialog-container">
   <md-dialog aria-label=​"Login form" class=​"md-padding md-default-theme">...</md-dialog>
</div>​]
```
Error given (warning) given:
Unable to find node 'md-dialog' in element.

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by Akxe** [comment]
No it does not... sorry was using latest stable...
