### ISSUE TITLE
angular-material.js should not use element.scope() function

### ISSUE THREAD

**Issue by Akxe** [angular/material#4844]
angular-material.js should not use element.scope() function as it is debug feature only. You can try to reimplement it is the feature is off, or at least check for it, so it don't spam with errors.

L651: findFocusTarget
on line 660

L7233: DatePickerCtrl.prototype.installPropertyInterceptors
on line 7239

**Comment by ThomasBurleson** [comment]
`this.$mdUtil.validateScope(this.$element)` checks to see if  `$element.scope( )` method is defined.

> To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by Akxe** [comment]
No as of 0.11.1 it is corrected

**Comment by bampakoa** [comment]
@ThomasBurleson I am using Angular 1.3.19 and Angular Material 1.0.0.rc4 and I get the same warning when showing an alert dialog.

Provided plunker: http://plnkr.co/edit/BjEgAGZ8rxkPLdlayti6?p=info

**Comment by bampakoa** [comment]
Any news on this?

**Comment by bampakoa** [comment]
Any ideas on this?

**Comment by bampakoa** [comment]
Hi,

Just to confirm that the issue is resolved in 1.0.0-rc5.
