### ISSUE TITLE
Raised toolbar button text invisible

### ISSUE THREAD

**Issue by dekpos** [angular/material#4845]
Since Angular Material 0.11, the text in raised buttons inside toolbars is being colored white (thus bleeding into its white background) due to this rule:

    md-toolbar:not(.md-menu-toolbar) .md-button {
      color: rgb(255,255,255);
    }

I think the specifier should include `:not(.md-raised)`.

**Comment by duongtdvn** [comment]
I'm also having the same problem with md-raised button within `md-fab-actions`.

**Comment by topherfangio** [comment]
Demo/reproduction here: http://codepen.io/topherfangio/pen/pjOEQQ

We are working on a fix.
