### ISSUE TITLE
iOS problems with s select

### ISSUE THREAD

**Issue by Akxe** [angular/material#4850]
I was unable to select anything with md-select due to self closing behavior. 
Tested on page:
https://material.angularjs.org/latest/#/demo/material.components.select
Tested 26.9.2015

**Comment by blmcquillan** [comment]
+1 also having this issue,
md-select self closes, tested 28.09.15
device is iPhone 6, iOS 8.4.1

**Comment by GustavoCostaW** [comment]
Tested 28.9.2015

on Android and iOS

**Comment by blmcquillan** [comment]
Anyone come up with a quick fix for this one?
