### ISSUE TITLE
How to adjust divs to make them stack on smaller resolutions?

### ISSUE THREAD

**Issue by mrcel** [angular/material#4852]
I am using the latest Angular MD release 10.0 and I have three divs that are displayed next to each other. If I display them on a smaller resolution/screen like a smartphone, I want them to stack. The left one is the first, the middle one is the second and the right div is the third. How can I accomplish that with md?

    <div layout="row">
      <div flex>
        <md-card>
            <img ng-src="../images/airline.jpg" class="md-card-image" alt="Airlines">
          <md-card-content>
            <h2 class="md-title"><md-button ng-click="go('/#/airline-list')">Airlines</md-button></h2>
          </md-card-content>
        </md-card>
      </div>
      <div flex>
        <md-card>
            <img ng-src="../images/airport.jpg" class="md-card-image" alt="Airports">
          <md-card-content>
            <h2 class="md-title">Airports</h2>
          </md-card-content>
        </md-card>
      </div>
      <div flex>
        <md-card>
            <img ng-src="../images/aircraft.jpg" class="md-card-image" alt="Aircrafts">
          <md-card-content>
            <h2 class="md-title">Aircrafts</h2>
          </md-card-content>
        </md-card>
      </div>
    </div>

**Comment by topherfangio** [comment]
Please see the [Layout Options](https://material.angularjs.org/HEAD/#/layout/options) documentation and use 11.1 which is now the latest.

Additionally, GitHub issues is usually for submitting actual bugs/issues to the team, not for asking general questions. You'll almost always get better help by posting this to the [forum](https://groups.google.com/forum/#!forum/ngmaterial) :-)

**Comment by mrcel** [comment]
OK thank you!
