### ISSUE TITLE
Angular material looks broke on HTC

### ISSUE THREAD

**Issue by AkaOne** [angular/material#4853]
Hello
I'm developing a photo editing app using Cordova + AngularJs and Angular material
I'm using Samsung Galaxy S4 active running android 5 and Htc One X running android 4.1.1
Cordova 5.3.1
Angular 1.4.6
Angular material 0.11.0
So I've just started to learn angular and my ui code look like this
```html
</md-toolbar>
<md-button class="md-fab md-fab-bottom-right">
	//Fab Button
<md-button>
<div layout="column" flex>
<md-content flex="66">
	//Contains 100 images for test purposes
</md-content>
<md-content flex="33">
	//Contains some junk text
</md-content>
</div>
```
![issue_01](https://cloud.githubusercontent.com/assets/14850089/10118579/5299c01a-646b-11e5-83ef-1fdb9d157840.png)

The figure A represents the Samsung and everything work as expected on the other hand the figure B from the Htc looks terrible notice the second md-content is off the screen and everything scrolls even the toolbar

So since I'm pretty new I thought this is something I'm doing wrong so I went and change the code to something very basic as the following 
```html
<md-toolbar>
	<h1 class="md-toolbar-tools">Gallery</h1>
</md-toolbar>
```
Here again the Samsung is all good but turns out the toolbar doesnt even display in this case on the Htc
(C= Samsung and D= Htc)
![issue_02](https://cloud.githubusercontent.com/assets/14850089/10118584/6edfc558-646b-11e5-9c1a-fb457c760f4f.png)

I really like Angular Material, is this a bug or am I doing something wrong?

**Comment by mckenzielong** [comment]
> android 4.1.1

That is the problem right there.  The pre-kitkat webview doesn't support some features used by Angular Material -- like flexbox for example.  There has been a few threads about this on the [forums](https://groups.google.com/forum/#!searchin/ngmaterial/Android/ngmaterial/SvvDgdfHww4/_hTgo80Dcr4J).  

If possible, you could always give the [crosswalk project](https://crosswalk-project.org/) a try.  With Cordova 4+ you can add the crosswalk webview to your project like any other plugin.

**Comment by AkaOne** [comment]
@mckenzielong thanks for your answer but I don't really feel like adding 18Mb to my app and when it got installed  it takes up 50Mb
I really wish there was another way...
