### ISSUE TITLE
Does md-checkbox support indeterminate state?

### ISSUE THREAD

**Issue by linkedrank** [angular/material#4854]
Does md-checkbox support indeterminate state? If so, how to set that value?

**Comment by topherfangio** [comment]
I don't believe we currently support this. I will label this as an enhancement request.

**Comment by EladBezalel** [comment]
dup #1912

**Comment by topherfangio** [comment]
@EladBezalel Thanks; I should have checked for dups first :-)

**Comment by EladBezalel** [comment]
:smile:
