### ISSUE TITLE
ng-change not supported on <md-radio-group> and on <md-datepicker>

### ISSUE THREAD

**Issue by djmarcus1** [angular/material#4857]
ng-change doesn't seem to be propagated to the underlying (internally generated) HTML.

In my custom md-dialog, I want the 'OK' button to be enabled only if the data in the dialog content passes a validation test. If validation fails I want to disable OK button and enable a <div> with the suitable error message(s).

TO do this I tried to add ng-change in my md-content (radio buttons and date picker). Neither of these fire.

My fallback is in the custom dialog (in the OK ng-click method) to do the validation and enable the 'error' div. This is only partially useful since the user has to click the OK to see errors (or reset errors).

**Comment by jelbourn** [comment]
Both the `md-radio-group` and the `md-datepicker` will trigger an ng-change on the element itself, but the `change` event does not propagate. This is working as intended, since we're not mimicking native browser events for the ng-material components.

**Comment by djmarcus1** [comment]
Thanks. With your explanation I am able to rework my code. My apologies for logging this as an error.
