### ISSUE TITLE
Contact chips bugs (elements cut off)

### ISSUE THREAD

**Issue by CoDEmanX** [angular/material#4863]
Chrome 47: content is cut off, there's an ugly scrollbar (on purpose?!) and there's a white gap between entries and the scrollbar:
![ng-material-contact-chips-chrome](https://cloud.githubusercontent.com/assets/1309249/10125251/3d54620c-656d-11e5-92a0-29f8b2613b5d.png)

Firefox 40: same as in Chrome, but additionally a problem with overly long entries in the contacts overview (no truncation)
![ng-material-contact-chips-firefox](https://cloud.githubusercontent.com/assets/1309249/10125252/40ec6a90-656d-11e5-839c-89a6518d8bd4.png)

https://material.angularjs.org/latest/#/demo/material.components.chips

**Comment by topherfangio** [comment]
Duplicate of #4450.

**Comment by jelbourn** [comment]
Closing as duplicate.

**Comment by CoDEmanX** [comment]
The missing truncation of long chips in the overview is not covered by that other report.

**Comment by jelbourn** [comment]
Maybe not a duplicate.

**Comment by topherfangio** [comment]
I have assigned this to myself and will see if I can fix the demo issue next time I am dealing with the chips, but considering this is mainly just a CSS issue with the demo chose to display the list, I have marked it as a lower priority issue.

**Comment by topherfangio** [comment]
Should be fixed by the above PR when merged (#5497).
