### ISSUE TITLE
Number input fields too narrow (placeholder cut off), spinner controls shown

### ISSUE THREAD

**Issue by CoDEmanX** [angular/material#4864]
The placeholder texts are truncated, because the input elements are too narrow. The spinner controls (up/down) are displayed (in Chrome only if focused).

![ng-material-custom-number-input](https://cloud.githubusercontent.com/assets/1309249/10125283/46e5594c-656e-11e5-84a8-e90bd43111b5.png)

It can be fixed like:

    width: auto; /* can we do something better instead? */
    -moz-appearance: textfield;
    -webkit-appearance: textfield;

**Comment by Wardormeur** [comment]
in 1.0rc-4 tehre is '''md-input-container textarea, md-input-container input[type="text"], md-input-container input[type="password"], md-input-container input[type="datetime"], md-input-container input[type="datetime-local"], md-input-container input[type="date"], md-input-container input[type="month"], md-input-container input[type="time"], md-input-container input[type="week"], md-input-container input[type="number"], md-input-container input[type="email"], md-input-container input[type="url"], md-input-container input[type="search"], md-input-container input[type="tel"], md-input-container input[type="color"]'''
 that set to '''    -moz-appearance: none;'''
It seems not to work, and the value of textfield seems to be the valid one.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
