### ISSUE TITLE
Auto-complete widget does not accept first match on enter (UX issue)

### ISSUE THREAD

**Issue by CoDEmanX** [angular/material#4865]
To accept an entry, it is required to either click on the entry, or use down key and then enter. It would be better if enter would pick the first entry without selecting the first entry first (it should probably highlight the first entry by default).

**Comment by topherfangio** [comment]
Have you tried setting `md-autoselect` to true? This should automatically select the first entry. Check out the [docs](https://material.angularjs.org/HEAD/#/api/material.components.autocomplete/directive/mdAutocomplete) for more info. Please provide a codepen if this doesn't work and I will reopen.
