### ISSUE TITLE
Confusing cursor hand for toggle widgets

### ISSUE THREAD

**Issue by CoDEmanX** [angular/material#4866]
The cursor icon is a drag or drop hand for toggles, and it can be dragged, but not actually dropped. It is therefore confusing. It should be a pointing hand, like for regular links.

![ng-material-toggle](https://cloud.githubusercontent.com/assets/1309249/10125417/82cd6c1a-6573-11e5-9e78-97bdf293edd5.gif)

(two tries to drag it, followed by one normal click to actually switch state)

**Comment by ThomasBurleson** [comment]
Fixed.

**Comment by CoDEmanX** [comment]
Why not change?
