### ISSUE TITLE
layout: offset-xx="nn" does not work.

### ISSUE THREAD

**Issue by shinkondo** [angular/material#4867]
Layout attribute with screen size specification, `offset-xx="nn"` (e.g. `offset-sm="15"`) do not work because there is no corresponding class exists in the generated CSS file.

Note that the attribute without screen size specification still works (e.g. `offset="15"`).

It seems like 92710b40a5e8a1cdda6ad702dea847e0d39a5485 removed function calls to the mixin `offset-for-name($name)`, resulting in removal of these classes.

Although I have not checked, I guess that `layout-align-xx="something"` stop working too, because the function calls to the mixin `layout-align-for-name($name)` are removed in the same commit.

I assume that simply adding these function calls back would fix this issues. Any opinion about that?

**Comment by jadjoubran** [comment]
I can confirm that this is also the case here (0.11.1)

**Comment by Soulcyber** [comment]
if you scroll down the commit you linked, you will notice a TB comment about this
![image](https://cloud.githubusercontent.com/assets/4432213/10135872/7da66196-65f1-11e5-864a-a6d56cc70cd7.png)

**Comment by jadjoubran** [comment]
Btw, it works now on master. So I guess this can be closed

**Comment by shinkondo** [comment]
OK. Sorry for not reading the line note.
For just my information (and not to post an issue like this again), could someone explained to me what was going on? it looks like someone already asked this question in the line note, but what was the reason of removing a functionality and adding it back on master?

**Comment by Soulcyber** [comment]
i don't know, maybe they thought it would be better to re-introduce the functionality before the v0.12 to reduce complaints.
IMO but only an official answer can reveal the truth XD

**Comment by ThomasBurleson** [comment]
Both **flex-offset** and **layout-align** Layout features should be fixed now in master/HEAD and in v0.11.2.

To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by Karnith** [comment]
Offset issue again in 11.4

[here](http://plnkr.co/edit/aWhrrVnrM4geqvvdG8Z0?p=preview) is the plunker

in 11.2 offset worked, I needed to upgrade to get the md-card-footer fix and now my original offsets do nothing.

Thx,

Karnith

**Comment by jadjoubran** [comment]
@Karnith look at the [changelog](https://github.com/angular/material/blob/master/CHANGELOG.md)
Material Layout attribute offset should now be flex-offset.

**Comment by ThomasBurleson** [comment]
```html
<div class='md-padding' layout="row" flex-offset-sm="25" flex-offset-md="30" flex-offset-lg="20" flex-offset-gt-lg="40" layout-wrap>
```

**Comment by Karnith** [comment]
my bad. I missed that change... sorry

**Comment by jadjoubran** [comment]
no worries @Karnith 
I follow their changelog by signing up on versioneye or you can find any similar service - this is how you can stay updated
Cheers!
