### ISSUE TITLE
md-checkbox with ng-checked fires multiple time

### ISSUE THREAD

**Issue by rtprakash** [angular/material#4868]
I have used md-checkbox with ng-repeat, ng-checked and ng-click directives. When i click one checkbox ng-click directive fires only once and it adds/removes the selected item from the array. At the same time ng-checked fires multiple times. So sometimes it is not toggle the selection. It not only fires the method associated with this ng-checked and also other methods associated with ng-checked in that form.

https://codepen.io/anon/pen/OybzEK

I have logged the method name thru console.log()

**Comment by jayeshanandani** [comment]
Able to replicate this. Any solution for this?
