### ISSUE TITLE
md-card-content's padding has no effect in IE10

### ISSUE THREAD

**Issue by nihgwu** [angular/material#4869]
![image](https://cloud.githubusercontent.com/assets/2595058/10127304/21d79a7a-65d2-11e5-8423-731bd3523052.png)

**Comment by csvan** [comment]
Since Edge is now in stable, IE10 falls just outside Angular Materials n-1 support rule.

**Comment by topherfangio** [comment]
This is a duplicate of #2974 which I think we are planning to address. Closing in favor of existing issue.
