### ISSUE TITLE
mdSlider: support for range sliders

### ISSUE THREAD

**Issue by tmikoss** [angular/material#487]
Please consider adding a range (second value) option to md-slider. 

Example use case: when searching for a hotel, I want to specify both minimum and maximum price, and have the application show me results that fall between those. Demonstrated in AirBnB search page.

This feature has been previously implemented in 

*  https://github.com/Venturocket/angular-slider
*  http://angular-ui.github.io/ui-slider/demo/demo.html

**Comment by mackelito** [comment]
+1

**Comment by adamduren** [comment]
+1

**Comment by robertogyn19** [comment]
+1

**Comment by kdela** [comment]
+1

**Comment by EdwardCTaylor** [comment]
For those in desperate need, I made this directive that simulates a range slider with two single md-sliders. It works ok, with three minor issues

a) the left slider can override and push the right slider
b) the right slider moves very slightly (not yet noticed by users).
c) minimum value of 1

code here
https://gist.github.com/EdwardCTaylor/31e26e2c804eec78e97e

example (24 hour range filter):
<range-slider max='24' min='1' min-gap='2' step='1' lower-value="lv" upper-value='uv'></range-slider>

min-gap defines minimum value spacing between the two sliders (to prevent awkward overlap). lower-value and upper-value are the outputs.

(you will need to add your own templateUrl for html template). 

Happy to receive any developments anyone has on this, with a little love may become more robust.

**Comment by r0b-** [comment]
+1

**Comment by getangad** [comment]
+1

**Comment by kuitos** [comment]
Thanks to @EdwardCTaylor at first,base on your solution,i have a improved version.
Here https://gist.github.com/kuitos/89e8aa538f0a507bd682

**Comment by randallmeeker** [comment]
+1

**Comment by offminded** [comment]
+1

**Comment by ilanbiala** [comment]
@ThomasBurleson what does the `G` label mean?? It's not intuitively obvious as far as labels go.

**Comment by ThomasBurleson** [comment]
@ilanbiala - G is a label-used internally for core team purposes.

**Comment by bartlomiejborzucki** [comment]
+1

**Comment by bernyfox** [comment]
+1

**Comment by jambrose42** [comment]
+1

**Comment by daveoncode** [comment]
+1

**Comment by tennisgent** [comment]
+1

**Comment by leon0517** [comment]
+1

**Comment by noamamit92** [comment]
+1

**Comment by david-gang** [comment]
+1

**Comment by GautierThiriez** [comment]
+1

**Comment by grantopher** [comment]
+1

**Comment by ioriiod0** [comment]
+1

**Comment by fmaul** [comment]
+1

**Comment by christrude** [comment]
+1

**Comment by ThomasBurleson** [comment]
@all - this is **in-progress**.

**Comment by daveoncode** [comment]
\o/

**Comment by advancedits** [comment]
+1

**Comment by elubin** [comment]
+1

**Comment by alexcriss** [comment]
+1

**Comment by nwestbury** [comment]
+1

**Comment by Wilzi** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
