### ISSUE TITLE
ng-material 0.11.1 not yet uploaded to Google CDN

### ISSUE THREAD

**Issue by Soulcyber** [angular/material#4874]
Link to 0.11.1 not exists yet.
https://developers.google.com/speed/libraries/
Missing:
https://ajax.googleapis.com/ajax/libs/angular_material/0.11.1/angular-material.min.js
https://ajax.googleapis.com/ajax/libs/angular_material/0.11.1/angular-material.min.css

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you update the CDN ?

**Comment by jelbourn** [comment]
[Done.](https://ajax.googleapis.com/ajax/libs/angular_material/0.11.1/angular-material.min.js)
