### ISSUE TITLE
flex styling issue 0.11.1

### ISSUE THREAD

**Issue by norkunas** [angular/material#4875]
```html
<md-content flex="33" flex-gt-lg="50"></md-content>
```

On large screen it shouldn't have flex-33 class or it's style should be overriden.

https://codepen.io/norkunas/pen/QjGBYo

**Comment by MrChoclate** [comment]
Any workaround?

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by Chitzi** [comment]
+1

**Comment by ThomasBurleson** [comment]
Fixed with latest commits to `master`:

https://codepen.io/ThomasBurleson/pen/VvPvbK

**Comment by norkunas** [comment]
@ThomasBurleson then shouldn't it be only half width ? In your example I see full width toolbar.

**Comment by ThomasBurleson** [comment]
@norkunas - Can you recheck with this:  http://codepen.io/ThomasBurleson/pen/dYNXpG

> Don't forget that you must do this `angular.module('MyApp', [ 'ngMaterial' ] )`

**Comment by ThomasBurleson** [comment]
While  `<md-content flex="80" flex-gt-md="50">` works fine, we still have some bugs with combinations like `<md-content flex="33" flex-gt-md="50">`

**Comment by dohomi** [comment]
+1 just bumped into this issue as well

**Comment by ThomasBurleson** [comment]
Appears to be fixed with HEAD/master: http://codepen.io/ThomasBurleson/pen/dYNXpG

**Comment by norkunas** [comment]
:+1:
