### ISSUE TITLE
JSPM support for dev and production imports

### ISSUE THREAD

**Issue by kburson** [angular/material#4878]
I am trying to use JSPM for package management. 

`jspm install angular-material`

this creates the package:
`jspm_packages/github/angular/bower-material@0.11.1/`

so, in my code I `import 'angular-material';`.  

`SystemJS` then looks up the mapping in the `jspm.config.js` :
**`jspm.config.js`**
```
System.config({
  map: {
    "angular-material": "github:angular/bower-material@0.11.1",
    "github:angular/bower-material@0.11.1": {
        "angular": "github:angular/bower-angular@1.4.6",
        "angular-animate": "github:angular/bower-angular-animate@1.4.6",
        "angular-aria": "github:angular/bower-angular-aria@1.4.6",
        "css": "github:systemjs/plugin-css@0.1.18"
    },
```

to identify the package main file location `jspm_packages/github/angular/bower-material@0.11.1.js`.

Which identifies the versioned resource to load:
**`jspm_packages/github/angular/bower-material@0.11.1.js`**
```
module.exports = require("github:angular/bower-material@0.11.1/index");
```

which in turn loads all package dependencies:
**`jspm_packages/github/angular/bower-material@0.11.1/index.js`**
```
require('angular');
require('angular-animate');
require('angular-aria');
require('./angular-material');
module.exports = 'ngMaterial';
```

the loaded dependency `./angular-material` starts with a header
**`jspm_packages/github/angular/bower-material@0.11.1/angular-material.js`**
```
/* */ 
"format global";
"deps ./angular-material.css!";
```

which seems to import the `angular.material.css` file appropriately using the `plugin-css` loader.

GREAT!

----

Now, after building and implementing my app I want to package for distribution, this means I want to use the minified version of dependencies.  

For vendor dependencies I want to use the vendor minified versions rather than process their sources into minified versions.  (I have run into problems doing that and have learned to resort to vendor minified versions when available).

So, how do I change SystemJS to import the minified version for production bundling?

----

I could change the config:map to point to the minified file, 

but then I would not have all the auto-imported dependencies as seen in the `jspm_packages/github/angular/bower-material@0.11.1/index.js`.

Also, looking at `jspm_packages/github/angular/bower-material@0.11.1/angular-material.min.js` it has a different header than the non-minified version:

**`jspm_packages/github/angular/bower-material@0.11.1/angular-material.min.js`**
```
/* */ 
"format cjs";
```
which does not include the `"deps ./angular-material.min.css!";` similarly to the non-minified version.

---

OK,  so help me find a pattern to use SystemJS to load the non-minified version of angular dependencies when doing a dev build (loading dependencies loose leaf as opposed to bundled), then switch to minified versions of these dependencies when I want to bundle for a production distribution file.

Thanks!

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial).

> Also you can look at the [Material Start (ES6 w/ JSPM branch)](https://github.com/angular/material-start/tree/es6) for configuration and usage tips:
