### ISSUE TITLE
md-menu on dark theme, font colors issues

### ISSUE THREAD

**Issue by marcoriesco** [angular/material#4880]
This issue on md-menu when set dark theme.

![captura de tela 2015-09-28 as 15 42 44](https://cloud.githubusercontent.com/assets/13396828/10145123/a829f7c4-65f7-11e5-873f-5fad8757bac3.png)

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by marcoriesco** [comment]
?

**Comment by EladBezalel** [comment]
@marcoriesco sorry about it, he was a spammer

**Comment by ThomasBurleson** [comment]
A fix via Pull Request would we welcomed!

**Comment by EladBezalel** [comment]
dup #5744 will be fixed via #5868
