### ISSUE TITLE
md-select: set a value different from selected option impossible in v0.11.1 

### ISSUE THREAD

**Issue by pitchan** [angular/material#4882]
Hello,

We updated angular material today from 0.10.0 to 0.11.1, performance with IE where improved and it was the goal ^^, but now some of my select box now didn't work correctly ...

So in our md-select we choose for exemple 2px which is the label and we only show 2 the value
Now with angular-material v0.11.1 only the label appear and not my value. :(   

Here is a working plunker with old angular material version and the master commented: 
http://plnkr.co/edit/C7Z2VJddqH0X5vFurZLC?p=preview 

Just uncomment angular from master and comment the other line to see the issue.

Thanks in advance !

**Comment by sazonenka** [comment]
`md-select-label` is no longer used.
See [Breaking Changes for 0.10.1](https://github.com/angular/material/blob/master/CHANGELOG.md#breaking-changes-2)

**Comment by pitchan** [comment]
I changed md-select-label by md-input-container but that is not solving the problem.
Same result in the plunkr.

**Comment by topherfangio** [comment]
This was a purposeful breaking change in https://github.com/angular/material/commit/5d9874fb:

> BREAKING: `md-select-label` is no longer used. The select will now
always display the selected value as the text in the `md-option`. This
makes for a better UX for users, as otherwise it was possible to
confuse them.
