### ISSUE TITLE
md-dialog: ng-show is not evaluated immediately in some cases 0.11.1

### ISSUE THREAD

**Issue by GoulwenBZH** [angular/material#4885]
Hello,

On chrome, I have a strange bug with angular-material v0.11.1 (and Angular 1.4.6):
ng-show is not evaluated immediately when there are several md-select and input with maxlength

An example with many md-select to bring out the problem:
https://codepen.io/GoulwenBZH/pen/bVBXmG

In my tests, no problems when I change one element of them :
- With angular-material v0.11.0 
- With angular < 1.4.5
- Without md-select
- Without maxlength in input

**Comment by topherfangio** [comment]
Can you please let us know if this is still an issue after upgrading to 1.0.1?
