### ISSUE TITLE
Disabled button cursor doesn't match disabled inputs

### ISSUE THREAD

**Issue by joeyperson** [angular/material#4886]
Disabled states should use the default pointer to match other components.

After asking if this special cursor should be added, the word from UX was "I think no cursor change. A visual disabled state to the component is enough of an affordance."

**Comment by chriscalo** [comment]
This is fixed in the [Buttons Demo page](https://material.angularjs.org/latest/demo/button). Seems good to close to me.

**Comment by topherfangio** [comment]
Thanks for the update; I do remember this getting fixed a while back. We'll reopen if it comes up again.
