### ISSUE TITLE
0.11.1 CodePen examples are pointing to HEAD instead.

### ISSUE THREAD

**Issue by langley-agm** [angular/material#4889]
The 0.11.1 CodePen examples are using the HEAD libraries instead of the 0.11.1 ones.

Example:

https://material.angularjs.org/HEAD/angular-material.css

**Comment by topherfangio** [comment]
Just saw this after I pushed a PR that should fix it: #4922.

**Comment by ngraef** [comment]
Dupe of #4447. Thanks for the fix, @topherfangio

**Comment by topherfangio** [comment]
@ngraef Thanks for helping us keep the issues up-to-date! You've had a lot of very helpful comments recently :smile:
