### ISSUE TITLE
md-datepicker strange appeance and behavior 

### ISSUE THREAD

**Issue by sombriks** [angular/material#4892]
so, instead use a regular <input type="date" ng-model="dtini"/>, i gave md-datepicker a try.

however it's pretty much different from the other input fields:

![md-datepicker](http://s4.postimg.org/fruqeemhp/md_datepicker.jpg)

Also, i've set and initial date on ng-model, but the field remains blank until i click on it

Not directly related, but, will this directive support date, time and datetime-local input types?

**Comment by alyskou** [comment]
Same issue for me.

**Comment by jelbourn** [comment]
@sombriks "pretty much different" isn't really enough information for an issue. Closing this for now- feel free to reopen for more specific issues; it really helps if you can provide a CodePen (or similar) demo.

**Comment by sombriks** [comment]
every input is transparent, it's visible in the picture i've added.
when i get some time i'll try to find which css rule makes datepicker behaves different from selects and other inputs.

**Comment by tinusn** [comment]
You can fix the transparent text by adding the following to your styles:
```
.md-datepicker-input.md-input {
color: rgba(0,0,0,0.87);
}
```

**Comment by sombriks** [comment]
@jelbourn i've made some screenshots in order to clarify what i am trying to say. plase take a minute to lay down eyes on it:

http://imgur.com/gallery/rvOB2/

@tinusn i've tried your suggestion, however i had no luck with it.

Also, i tried to track down that background:rgb(255,255,255) css property appearing inside md-datepicker. I've looked into the source (bower_components/angular-material/modules/js/{datepicker.js  datepicker.css}), it's not there, it came from some other place.
