### ISSUE TITLE
Examples on site are very old and wrong for newer version

### ISSUE THREAD

**Issue by VikramTiwari** [angular/material#4895]
The site has a lot of older examples on the landing page which are outdated. Can we please update them?

Site link : https://material.angularjs.org/latest/#/getting-started

**Comment by topherfangio** [comment]
I think we should get this done before the 1.0 release, but there are definitely some higher priority issues we need to address.

If you're interested in contributing, this would be a really helpful update that should be easy to contribute.

**Comment by VikramTiwari** [comment]
@topherfangio I tried to find the source code for site, but was unsuccessful. Can you point me in the rigth direction? I can add make updates.

**Comment by topherfangio** [comment]
@VikramTiwari Absolutely!

You'll need to fork and clone this repository. You can see some info/guidelines [here](https://github.com/angular/material#contributing).

Once you have the project cloned, you'll want to look at the following file:

 * `docs/app/partials/getting-started.tmpl.html`

That has some links to existing Codepens, so you may want to fork them, update them and then update the URLs in the file above to point to your updated Codepen.

Please let me know if you have any more questions!

**Comment by ThomasBurleson** [comment]
Fixes are pending with https://github.com/angular/material/pull/6082/

**Comment by ThomasBurleson** [comment]
Fixed with SHA f6e97a02a9c88b1695094a8a85a11958924e4c61
