### ISSUE TITLE
virtual-repeat reverse infinite scroll support

### ISSUE THREAD

**Issue by lievenjanssen** [angular/material#4899]
I am building a chat like view and would need a virtual-repeat with a reverse infinite scroll. Can this be supported?

As a side note the infinite scroll implementation feels a bit weird. For me the zInfiniteScroll implementation with an attribute pointing to an event handler to load additional data is more logical: https://github.com/LightZam/zInfiniteScroll

**Comment by cranesandcaff** [comment]
I know this is marked as post-1.0, but I need it as well. If some of the planning of this was done I'd love to base my shim on it if possible?

**Comment by lievenjanssen** [comment]
@ThomasBurleson could you comment on why this has been deprecated?
