### ISSUE TITLE
0.11.1: md-chips - form is always pristine when you delete a chip

### ISSUE THREAD

**Issue by florenthemmi** [angular/material#4900]
Hi,

Please see this codepen: https://codepen.io/anon/pen/PPbMyv

![md-chips-before](https://cloud.githubusercontent.com/assets/4488419/10160009/7813348e-669b-11e5-83eb-4cbed833663e.png)
![md-chips-after](https://cloud.githubusercontent.com/assets/4488419/10160011/797ff780-669b-11e5-8a72-0e8620c1946d.png)

The form is never pristine when you delete a chip without editing the input.
You need to type something in the input field to make it pristine.

**Comment by Benew** [comment]
linked to #3855

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (494/400 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:47545 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsbb-001a3R-UT
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:32:12 +0200
Date: Thu, 28 Apr 2016 13:25:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875119;
	bh=Qf2EN0MUZXCKiXjPhqgEkicZpgrkWHgGrrdyWSLZExs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=cbLHVZu8/XyI2xakS4QybyBINgp15MbDgHmH3Jp3XYclWevQrf0DTT3JJbF1Uevx1
	 /GTJErlXkP2vHkVGQhXU95JkJTnwZRWstW7hNRcxi6MPy4xlIXoq2iozviUCzcvxrz
	 prjGuTzWieeJqxKHVWOwZz+R3PJxHNh8LE1F23fQ=
