### ISSUE TITLE
strange flex-order behavior

### ISSUE THREAD

**Issue by no-more** [angular/material#4901]
Hello,

I have a strange issue with flex order since 0.11.1.

As you can see in the included picture, I flex-order-sm which override flex-order-gt-md while on the I have a screen of 1400px (gt-md is over 960px)

![2015-09-29_152232](https://cloud.githubusercontent.com/assets/3856871/10162692/05ba4b84-66be-11e5-9969-d1bdd2426c63.jpg)

I didn't have this before this release.

Thanks a lot.

**Comment by ThomasBurleson** [comment]
This has been fixed in the `master` branch:

Whenever possible, provide a CodePen demo.
To expedite resolution, please always test with the latest versions:

*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by no-more** [comment]
Thanks,

This is fixed in last bower master version. But it seems I have other issues with flexbox. One of them is flex alone does not seems to fill available space anymore. I'm trying to figure out if I have to change something in my code, or if this is a bug.

I will try to produce a codepen demo when I'll find exactly what is the matter.

Thanks.

**Comment by no-more** [comment]
I'm not sure if this is the right place to talk about it but I don't understand some css change in the master release : 
this is what I have in 0.11.1 which is working as I would expect :
```
.flex {
    box-sizing: border-box;
    -webkit-flex: 1;
    -ms-flex: 1;
    flex: 1;
}
.layout-row {
    -ms-flex-direction: row;
    flex-direction: row;
    -webkit-flex-direction: row;
}
```
this is what I have in the master css:
```
.flex, .flex-initial, [flex=initial] {
    -webkit-flex: 0 1 auto;
    -ms-flex: 0 1 auto;
    flex: 0 1 auto;
}
.flex, [flex] {
    box-sizing: border-box;
    -webkit-flex: 1 1 0;
    -ms-flex: 1 1 0;
    flex: 1 1 0;
}
.layout-row, [layout=row] {
    -webkit-flex-direction: row;
    -ms-flex-direction: row;
    flex-direction: row;
    -webkit-flex-wrap: wrap;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
}
```

there's several changes like flex-wrap which is now default, and the issue is due to ".flex, .flex-initial, [flex=initial]" which change "flex:1" to "flex: 0 1 auto".

Could someone tell me if this is the new expected behavior ? If it is how can I achieve old behavior with this new release ?

Thanks a lot.

**Comment by ThomasBurleson** [comment]
The **flex-wrap** is no longer a default within `flex='row'`.

Whenever possible, provide a CodePen demo.
To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
