### ISSUE TITLE
offset attribute conflict (since 0.11.0)

### ISSUE THREAD

**Issue by Sayene** [angular/material#4902]
ng-attr-offset is ignored when using md-material builds 0.11.1 and current master
Here is rendered html example with svg gradient, where other (here: stop-color) ng-attr- are evaluated but ng-attr-offset is ignored:
```
<linearGradient x1="100%" y1="100%" x2="100%" y2="0%" id="hpp-gradient">
            <stop ng-attr-offset="0%" ng-attr-stop-color="{{fill}}" stop-color="#93CE8C"></stop>
            <stop ng-attr-offset="{{(complete)?complete:0}}" ng-attr-stop-color="{{fill2}}" stop-color="white></stop>
</linearGradient>
```
This was working ok in 10.0.1.

**Comment by Sayene** [comment]
UPDATE: actually this is not only ng-attr-offset that is ignored (REMOVED) but all attributes "offset", no matter where used, are now removed...

**Comment by ThomasBurleson** [comment]
@jelbourn, @robertmesserle - what are your thoughts here? 

*  Is this a conflict with a common attribute `offset` ?
*  Should we rename the attribute to be **flex-offset** to be aligned with **flex-order** ?
  *  I think this solution is probably best...

**Comment by jelbourn** [comment]
Perhaps `layout-offset`, since it doesn't actually have anything to do with flex?
