### ISSUE TITLE
md-checkbox and link (a href) in label triggers click-event

### ISSUE THREAD

**Issue by pomm0** [angular/material#4903]
Hey,

the problem I have is that if in the label-text is a link and i click on the link the checkbox will be checked. 

Here a normal behavior of a browser http://jsfiddle.net/xj92mrx2/
To reproduce open your demosite https://material.angularjs.org/latest/#/demo/material.components.checkbox and add a link with target="_blank" in the label-div with the devtools of your browser then you will see after clicking on the link the checkbox will be checked.

If you add a link with target blank like i did in the jsfiddle. It will trigger the checkbox. In my case i've made a signup-site where i linked the terms and conditions, if the user opens the term and conditions the checkbox will automatically be checked, which is not what i want.

Thanks!

**Comment by Fishz** [comment]
You can bind a function that opens the page in a new tab, pass it the $event object and stopPropagation as an interim.
