### ISSUE TITLE
md-fab-speed-dial is just static and does not initialize animation

### ISSUE THREAD

**Issue by Pinsonbavard** [angular/material#4904]
md-fab-speed-dial does not initialize animation at all. It is just static like a dependency is needed or something. I dont know.
![capture](https://cloud.githubusercontent.com/assets/6134716/10164725/1a2a2de2-66b3-11e5-8b95-69eea64d3709.PNG)

**Comment by topherfangio** [comment]
Please provide a codepen which demonstrates the problem; we can't help much based off of an image :-)

Here is a starter template you can use: https://codepen.io/topherfangio/pen/pjRjdq

And here are some additional links.

*  Angular Material HEAD
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
 *  Angular 1.3.19 (or greater)
 *  Angular 1.4.6 (or greater).

If you can provide a codepen, I will reopen.
