### ISSUE TITLE
Layout manager broken in 11.1 release

### ISSUE THREAD

**Issue by britztopher** [angular/material#4905]
For some reason the layout flexbox grid system seems to break with the upgrade to 0.11 from 0.10. It appears that the changes to the layout css properties are the culprit and there is no documentation over these changes or something broke.

This plunker here http://plnkr.co/edit/cXgLWewAPzr7B2hxH9gF?p=preview shows the broken flexbox properties and if you change the css sheet that is added to 0.10.1 from 0.11.1 then you will see that the flexbox grid will work properly.

For Example: 
Change line number 5 from: 
 `<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/0.11.1/angular-material.min.css" />
`
To: 
` <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/0.10.1/angular-material.min.css" />
`

**Comment by ThomasBurleson** [comment]
Please test with the lastest 0.11.2 released just today: See Layout fixes in the [Change Log](https://github.com/angular/material/blob/master/CHANGELOG.md)

**Comment by ThomasBurleson** [comment]
Here is an updated Plunkr that works: http://plnkr.co/edit/vr1ZVnkDkbsL19E0Wo3M?p=preview

!! Important: You **MUST** configure a module dependency for ngMaterial:
```js
angular.module('MyApp', ['ngMaterial']);
```

**Comment by britztopher** [comment]
Looks good. Thanks
