### ISSUE TITLE
md-autocomplete show loading indicator on initial load/focus

### ISSUE THREAD

**Issue by nissoh** [angular/material#4906]
1. [Basic usage] (https://material.angularjs.org/0.11.1/#/demo/material.components.autocomplete)
2. Check "Simulate query for results?"
3. Focus auto-complete field

Expected that initial data fetching(loading either by ajax call or async promise) will show progress indicator until the query is done.

Possible scenarios/dependancies to check
1. [Basic usage with query enabled] (https://material.angularjs.org/0.11.1/#/demo/material.components.autocomplete)
2. auto-complete with [md-floating-label] attr
3. Maybe but not necessary to test... should also work within md-chips with 1,2 cases

**Comment by chiragparmar17** [comment]
Is this fix available in 1.1.5?

**Comment by Splaktar** [comment]
@chiragparmar17 yes, this was fixed in `0.11.3` and should be included in 1.1.5. Please open a separate issue if you have found a bug or ask a question on the [forums](https://groups.google.com/forum/#!forum/ngmaterial) if you need help.
