### ISSUE TITLE
IE Edge, vertical alignment problems on Child alignment page

### ISSUE THREAD

**Issue by Stamy** [angular/material#4907]
I noticed that there is a bug on Child alignment page with IE edge.

So if you go to: https://material.angularjs.org/latest/#/layout/alignment and try to change vertical alignment will be as if it is set to `start` even though it is `center` if you try to change any of those in vertical it will stay the same. Then if you select `column` in the 'Layout Direction' the same thing happens in horizontal alignment.

(In the image items should be in yellow place)
![capture_material](https://cloud.githubusercontent.com/assets/825836/10165447/b5637d98-66bf-11e5-915b-66431155a85f.png)

**Comment by topherfangio** [comment]
I just played with the demo for a bit in Edge and IE11 (via emulation) and I'm not seeing this issue.

Does this happen all of the time for you? According to your screenshot, you are using "latest". Was that 11.0 or 11.1?

Did you do anything else that might help us narrow this down? Perhaps there is a JS error on the page causing the demo to not actually change the underlying model, etc?

**Comment by Stamy** [comment]
I hope that this will answer all of the questions. I am using windows 8.1.
![capture_material](https://cloud.githubusercontent.com/assets/825836/10187136/7e0e63f2-6756-11e5-8859-98ed334f7ee5.png)

**Comment by topherfangio** [comment]
Thanks; I'll take another look at it today when I'm at my IE machine and see if I can reproduce.

**Comment by topherfangio** [comment]
I just got word from @EladBezalel who did some testing that he can see the issue on the 11.1 site, but that it appears to be fixed in [HEAD](https://material.angularjs.org/HEAD/#/layout/alignment).

Can you please test it there and see if it's working for you?

**Comment by Stamy** [comment]
Works fine with the 0.11.2

**Comment by topherfangio** [comment]
@Stamy Awesome; thanks for the update! Closing; please let us know if you see any more issues.
