### ISSUE TITLE
md-datepicker wrong validation

### ISSUE THREAD

**Issue by AzaroQL** [angular/material#4909]
When you enter date by hand it validates as month/day/year instead of day/month/year, when you pick date it works as intended.
You can try to enter 13.09.15 on the [demo page](https://material.angularjs.org/latest/#/demo/material.components.datepicker) and you will get an error, but 12.09.15 will pass it. The opposite goes for month, it allows 0-31 as value.

**Comment by jelbourn** [comment]
The date parsing is customized via [`$mdDateLocaleProvider`](https://material.angularjs.org/latest/#/api/material.components.datepicker/service/$mdDateLocaleProvider). The demo page not using internationalized parsing is tracked in #4671
