### ISSUE TITLE
Images for Docs

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#491]
This issue serves as a registry of uploaded images that can be used within README and documentation:

![screen shot 2014-10-28 at 3 04 49 pm](https://cloud.githubusercontent.com/assets/210413/4816236/bf7783dc-5edd-11e4-88ef-1f8b6e87e1d7.png)

**Comment by ThomasBurleson** [comment]
![mbbutton_css_customizations_flat](https://cloud.githubusercontent.com/assets/210413/7937957/79bd50e4-0908-11e5-8119-32053ccbad23.png)

**Comment by ThomasBurleson** [comment]
![mdbuttonflatdefault](https://cloud.githubusercontent.com/assets/210413/7940899/5d5550d0-0919-11e5-848d-ea417128fec1.png)

**Comment by marcysutton** [comment]
@ThomasBurleson that's a lot of textual detail for images, are you providing adequate alt text?

**Comment by ThomasBurleson** [comment]
![mdbuttonflatdefault_overrides](https://cloud.githubusercontent.com/assets/210413/7941518/6a59a994-091d-11e5-82cb-14a9a278ce31.png)

**Comment by ThomasBurleson** [comment]
![mdbuttonflatdefault3](https://cloud.githubusercontent.com/assets/210413/7945984/bda14884-0939-11e5-9196-131ded20ca77.png)
![mdbuttonflatdefault_overrides2](https://cloud.githubusercontent.com/assets/210413/7945987/c1b1c700-0939-11e5-879c-ba804ca03267.png)
