### ISSUE TITLE
virtual-repeat incorrectly sizes itself inside ng-show

### ISSUE THREAD

**Issue by elubin** [angular/material#4911]
I wrap the md-virtual-repeat-container in a div with ng-show so I can hide the whole block when my list has no elements.  I then fetch my elements with AJAX and fill my list which shows the block.  The control incorrectly gets a height of 0 (and default to NUM_EXTRA height).

updateIndexes_ method
this.container.getSize() evaluates to 0

https://github.com/angular/material/blob/acbf293d3872e25e0900a0a5ba890bab3428971e/src/components/virtualRepeat/virtual-repeater.js#L724-L734

Here is a fiddle to demonstrate the error against master branch
http://jsfiddle.net/elubin/d0wsmLqn/

**Comment by elubin** [comment]
By the way, for anyone that does hit this issue, the workaround is to use ng-if instead of ng-show

**Comment by prerna12** [comment]
@elubin Thanks a lot! Your solution works like a charm. :)

**Comment by danielsig** [comment]
Here's the same problem except I'm trying to animate the height using CSS animations.
using ng-show: http://plnkr.co/edit/3HI7NN4CqdXkOcTERzxX?p=preview
using ng-if: http://plnkr.co/edit/s1MDkHCLu05HjwlMmmkA?p=preview

**Comment by kseamon** [comment]
This is essentially the same bug as #4314. Hoping to fix it this week but we'll see.

**Comment by kseamon** [comment]
...and is a dupe of #4336.
