### ISSUE TITLE
$mdthemingprovider dynamic themes

### ISSUE THREAD

**Issue by marcoriesco** [angular/material#4921]
I'm trying to put dynamic themes, but I can not spend scopes, variables for $mdthemingprovider.

The way that I thought was a provider with my resource, but have no idea how to create one.

I have 2 forms that I use today, which are $rootScope and $cacheFactory, where I keep my global variables to access throughout the app. But at $mdthemingprovider does not accept neither.

**Comment by jelbourn** [comment]
@marcoriesco It is not clear what you are asking about / trying to do.

**Comment by marcoriesco** [comment]
I wanted to spend variables, scopes or rootScopes for $mdthemingprovider.

Example:

.config(['$mdThemingProvider', function ($mdThemingProvider) {
    'use strict';

    $mdThemingProvider.theme('default')
        .dark().primaryPalette($scope.theme_primary).accentPalette($scope.theme_accent);

    $mdThemingProvider.alwaysWatchTheme(true);

}])

**Comment by jelbourn** [comment]
Ah, I see. We aren't supporting dynamic themes like that for now, unfortunately.

**Comment by AntonKL** [comment]
I understand that this is a closed issue and that it might be undiscussable, but I just have to ask if you are aware of any way to make the theming dynamic, even if it's not official.
