### ISSUE TITLE
Nested md-dialog's - ng-click handler issue.

### ISSUE THREAD

**Issue by DerekLouie** [angular/material#4924]
We have a flow in our product where you click a button and it launches a dialog (Let's call this md-dialog A).

In that dialog, there is a button that you can press to open another dialog (Let's call that md-dialog B).

So it goes:

Click Button A -> Open md-dialog A -> Click button B (in md-dialog A) -> Open md-dialog B.

In practice, however, if you load the page right away, and you open md-dialog A, then immediately click button B, md-dialog B does not open.

If you wait a second it does work, and after the initial opening it also does work.

I put a debugger in the function that calls the md-dialog show function and it does not trigger the debugger statement if I click on the button too quickly, or in the karma test (as the click is automated and happens as immediately as possible).

This leads me to believe the ng-click is not fully registered initially when opening md-dialog A and therefore the click does nothing.

This seems to only be an issue with the double dialogs.

In the function that opens the 2nd dialog I also call mdDialog.hide() before calling show() to ensure the cleanup of the previous dialog. 

A contrived example of what is happening here is:

### We begin with a button in the header
```html
<span class="header">
    <md-button ng-click="ctrl.openDialogA($event)">
      <md-icon>
        notifications
      </md-icon>
    </md-button>
  </span>
```
### We click the button to open the notifications. This opens "md-dialog A".

```html
<md-dialog>
  <md-dialog-content>
    <div class="dialogA"> 
      <md-button>
          <md-icon  ng-click="ctrl.openDialogB($event)">
            button
          </md-icon>
      </md-button>
    </div>
  </md-dialog-content>
</md-dialog>
  ```

### We click the button in "md-dialog A" to open "md-dialog B".

```html
<md-dialog>
  <md-dialog-content>
    <div class="dialogB"> 
      STUFF
    </div>
  </md-dialog-content>
</md-dialog>
```

#### Accompanying Javascript.
```javascript
function openDialogA(event) {
    var presets = {
      templateUrl: '..'
      targetEvent: event,
      parent: angular.element(document.body),
      hasBackdrop: true,
      clickOutsideToClose: true,
      bindToController: true,
      controller: dialogACtrl,
      controllerAs: 'ctrl'
    };
    this.mdDialog_.show(presets);
}


function openDialogB(event) {
    // Need to close panel dialog first before opening a new one so
    // previous overlay is destroyed (all dialogs will close when
    // you click anywhere if not).
    this.mdDialog_.hide();

    var presets = {
      templateUrl: '..'
      targetEvent: event,
      parent: angular.element(document.body),
      hasBackdrop: true,
      clickOutsideToClose: true,
      bindToController: true,
      controller: dialogBCtrl,
      controllerAs: 'ctrl'
    };

    this.mdDialog_.show(presets);
}
```
We have "md-dialog B" open now.

Any help would be greatly appreciated! The clicking too fast is an issue, but not being able to write tests for this is an even larger one.

Best,

Derek

**Comment by kimsrung** [comment]
I've got the same problem. For me, the DialogB can't even be closed even if I call $mdDialog.hide() before I show another one.

**Comment by kimsrung** [comment]
I guess I got myself solve. Seem likes I don't need to call $mdDialog.hide() since it will do automatically.

**Comment by DerekLouie** [comment]
I removed the  `this.mdDialog_.hide();` in the openDialogB function, and it helped a bit actually.

I also ended up having to use $$postDigest instead of $timeout, and that seemed to run a function after the click handlers were attached.

Hope that helps for now :+1:

**Comment by jelbourn** [comment]
@ThomasBurleson do you want to take a look at this since you were the most recent person to dive into the dialog code?

**Comment by EladBezalel** [comment]
@DerekLouie Can you please check if it's still happening on HEAD?
If it's still an issue please post a codepen so we can investigate more

**Comment by DerekLouie** [comment]
I do not believe this is an issue anymore, I will close the issue.
