### ISSUE TITLE
md-list with action icon or other items text overlapping

### ISSUE THREAD

**Issue by dohomi** [angular/material#4925]
Hello,

In the demo and in my current project the secondary action icon is overlapping the text, if the text is getting too long. You can see this behavior at the demo:
https://material.angularjs.org/latest/#/demo/material.components.list

Just resize the browser or add a lot of text, then the text is not cut before the button. I think its nothing major, I just add some fixed width to the ```p```tag but maybe it would be good to solve it directly through flex alignment.

**Comment by patrickmichalina** [comment]
I am having a similar issue. When the <p> element is filled with a large amount of content, it will spill onto the next <md-list-item>. I have attached an image to help see the issue.

<img width="594" alt="screen shot 2015-10-11 at 1 50 25 am" src="https://cloud.githubusercontent.com/assets/6701211/10416075/9d99ae54-6fba-11e5-8a91-b73d03a59ad2.png">

**Comment by AleRob90** [comment]
md-list-item.md-3-line{
  height: auto !important;
} 
This solved the same problem

**Comment by vvnc** [comment]
> md-list-item.md-3-line{
> height: auto !important;
> }
> This solved the same problem

worked also for the similar angular material issue: https://stackblitz.com/edit/angular-mat-long-list-item-bug
