### ISSUE TITLE
md-datepicker inside form should throw error if non-valid date format

### ISSUE THREAD

**Issue by dohomi** [angular/material#4926]
Hi,

The md-datepicker seems to enable ```ng-messages```which is great. Is it possible to enable ```ngFormController```somehow, that the whole form is getting correct ```$error``` /```$invalid```states? Currently the error message is directive only and doesn't affect the parent ```form```. 

Thanks!

**Comment by nestorneto** [comment]
+1

**Comment by jelbourn** [comment]
@dohomi Can you give an example of what you mean?

**Comment by dohomi** [comment]
@jelbourn I meant the form should also get ```$valid/$invalid```state because the datepicker is part of the form. If you enter anything non-date specific the form still keeps valid state:
https://codepen.io/anon/pen/XmpyJy
