### ISSUE TITLE
autocomplete: allows scrolling when open and mouse is positioned above input

### ISSUE THREAD

**Issue by a8775** [angular/material#4927]
Chrome 45.0.2454.101 m but also in Edge
(checked with 0.11.1 and HEAD)

1. Set the size of the window that the scroll bar takes about half of the window height
2. Scroll "Custom Template" somewhere in the midle of the window but that popup shows up from the "Pick an Angular repository" input when clicked
3. Keep mouse over the input and scroll down with a wheel

![snip_20150929222633](https://cloud.githubusercontent.com/assets/14092227/10177221/49c76e2a-66f9-11e5-8d8c-7942eda0a61c.png)

**Comment by topherfangio** [comment]
Indeed. Quick guess: it seems that the `disableScrollAround()` code we use might need to be applied to only the virtual repeat container instead of the both it and the input.
