### ISSUE TITLE
what is the problem with angular material performance?

### ISSUE THREAD

**Issue by asiehmokarian** [angular/material#4929]
Hi,
I tried to test Angular Material Starter App(https://github.com/angular/material-start/tree/es5-tutorial) on my phone(Samsung S4). I built its .apk using visual studio 2015 cordova project and then install it on my phone.Upon opening the app, it first shows angular expressions "{{ }}" and unstyled layouts for almost 1 second and then will load other things. I did not have this problem testing other frameworks like Mobile Angular UI.

**Comment by ThomasBurleson** [comment]
I have update the master, es5-tutorial, and es6 branches.
For testing with cordova, please use the master or es6 branches.

> For better support, please post question in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
