### ISSUE TITLE
0.11 md-chips readonly has incorrect padding

### ISSUE THREAD

**Issue by osuritz** [angular/material#4932]
Setting ````<md-chips readonly="true">```` incorrectly adds 22px padding; see [Codepen Demo](https://codepen.io/anon/pen/GprNBp).

This used to work... looks like, previously, the ````md-readonly```` attribute was set on the containing ````<md-chips>```` but it is now set on each individual ````<md-chip>````
The style has not been updated: https://github.com/angular/material/blob/master/src/components/chips/chips.scss#L62

Either that, or maybe fix the binding for ````md-readonly```` on the template: https://github.com/angular/material/blob/master/src/components/chips/js/chipsDirective.js#L93

 ````
\'md-readonly\': !$mdChipsCtrl.ngModelCtrl
````

to

````
\'md-readonly\': !$mdChipsCtrl.readonly
````

**Comment by topherfangio** [comment]
Fixed by #4621. Please comment if you still see issues and I will reopen.
