### ISSUE TITLE
Bug in md-button ink effects when used with CSS multicolumn mode in webkit browsers

### ISSUE THREAD

**Issue by anishbenji** [angular/material#4934]
On Webkit browsers (tested in Mobile & Desktop Chrome 45, Mobile Safari on iOS 8.x) when using CSS multicolumn mode there are issues with ink effects in buttons (Chrome 45, Mobile Safari) and sometimes the button text & icons don't show up either (Mobile Safari).
See the issue in this Codepen: http://codepen.io/anon/pen/meRmMb
Regards,
Anish

Edit: It seems to work properly in Firefox

**Comment by EladBezalel** [comment]
it seems like [`-webkit-column-count`](http://caniuse.com/#search=-webkit-column-count) is not fully supported.
