### ISSUE TITLE
Using chips with ng-repeat causes crash with error

### ISSUE THREAD

**Issue by constantijn** [angular/material#4938]
Using angular-material 0.11.1 and angular 1.4.7 this:

```html
<md-chips ng-init="things = ['Foo', 'Bar', 'Baz']">
  <md-chip ng-repeat="thing in things">{{thing}}</md-chip>
</md-chips>
```

Doesn't work and it crashes with this error:

```
TypeError: Cannot read property 'insertBefore' of null
    at forEach.after (http://localhost:3000/bower_components/angular/angular.js:3453:13)
    at Object.JQLite.(anonymous function) [as after] (http://localhost:3000/bower_components/angular/angular.js:3537:17)
    at domInsert (http://localhost:3000/bower_components/angular/angular.js:5050:35)
    at Object.enter (http://localhost:3000/bower_components/angular/angular.js:5213:9)
    at ngRepeatTransclude (http://localhost:3000/bower_components/angular/angular.js:27466:26)
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:7554:29)
    at boundTranscludeFn (http://localhost:3000/bower_components/angular/angular.js:7699:16)
    at controllersBoundTransclude (http://localhost:3000/bower_components/angular/angular.js:8316:18)
    at ngRepeatAction (http://localhost:3000/bower_components/angular/angular.js:27459:15)
    at Object.$watchCollectionAction [as fn] (http://localhost:3000/bower_components/angular/angular.js:15691:13)
```

And i'm expecting it to do the same as this (which does work):

```html
  <md-chips>
    <md-chip>Foo</md-chip>
    <md-chip>Bar</md-chip>
    <md-chip>Baz</md-chip>
  </md-chips>
```

**Comment by jelbourn** [comment]
@constantijn Check out our [demo page](https://material.angularjs.org/latest/#/demo/material.components.chips) for an example of how to use md-chips. `<md-chip>` isn't used as a child of `<md-chips>`; instead, you set the list as a model for `<md-chips>` and can specify a custom template:

```html
<md-chips ng-model="things">
  <md-chip-template>
    {{$chip}}
 </md-chip-template>
</md-chips>
```

**Comment by constantijn** [comment]
@jelbourn your example replicates the first example on the demo page resulting in an editable set of chips. I'm trying to replicate the fourth example from the demo page you linked to, namely the static chips. (Non editable.)

The fourth example on that exact demo page literally shows the following example:

```html
    <md-chips>
      <md-chip>Hockey</md-chip>
      <md-chip>Lacrosse</md-chip>
      <md-chip>Baseball</md-chip>
      <!-- Static chips are transcluded -->
      <md-chip>{{ctrl.chipText}}</md-chip>
    </md-chips>
```

That does exactly what I want, however I'm looking to get one chip for every string in my array of "things" and using `ng-repeat` gives the error above.

**Comment by topherfangio** [comment]
@constantijn We recently closed a duplicate (#2829) of this issue because there is a [workaround](https://github.com/angular/material/issues/2829#issuecomment-117520534) that should give you the exact functionality you need.

If that doesn't meet your needs, please comment and  we will reopen, but it is likely to be re-opened with a lower priority because of the workaround.

**Comment by mjhasbach** [comment]
My only complaint is the extra right padding on the chips when using `ng-model` and `readonly="true"`.

**Comment by mjhasbach** [comment]
Also, `md-on-select` does not work when using `readonly="true"`. A workaround is to use `ng-click` with `md-chip-template`; however, that is problematic because the event is only fired when clicking directly on the chip text (not on the outer edges).

Based on those observations, I feel that `ng-repeat` should be supported on `md-chip`.

**Comment by constantijn** [comment]
@topherfangio I tested out the `readonly="true"` workaround. This sorta works, but the layout is broken in that there's extra white space in every chip where the "close X" is supposed to be (like @mjhasbach said). I can't use it like this because my designer's going to have an aneurism if I try show this to him.

Also if that layout glitch is fixed the 4th example on the chips demo page might need a comment at least. Because the way it's documented right now it practically screams for an `ng-repeat`

**Comment by mjhasbach** [comment]
See also https://github.com/angular/material/pull/5102

**Comment by mjhasbach** [comment]
> This sorta works, but the layout is broken in that there's extra white space in every chip where the "close X" is supposed to be (like @mjhasbach said).

@constantijn fyi that was fixed by recent commits.
