### ISSUE TITLE
md-themes dynamic, almost there..

### ISSUE THREAD

**Issue by marcoriesco** [angular/material#4941]
I managed to get this code, does anyone have any idea how I select the primary and accent issues.

Click the Apply button and change the theme according to the choice?

Plunker: http://plnkr.co/edit/nVcMHR1v2jTZMQTCK6sI?p=preview

**Comment by EladBezalel** [comment]
This kind of questions are related to our [forum](https://groups.google.com/forum/#!forum/ngmaterial).
Please move this thread and ask for help there :)
