### ISSUE TITLE
layout-align-gt-sm no longer works in 0.11.1

### ISSUE THREAD

**Issue by oste** [angular/material#4942]
none of the layout-align-* classes are working in the latest release

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
