### ISSUE TITLE
md-button that converts to anchor not centered properly in md-menu-item

### ISSUE THREAD

**Issue by oste** [angular/material#4943]
When using the following code, the md-button will be converted to an anchor and the centering will not be aligned in the middle, instead it is slightly aligned to the top.

```
<!-- this directive code -->
<md-menu-item>
    <md-button ui-sref="docs">Docs</md-button>
</md-menu-item>

<!-- converts to -->
<md-menu-item role="menuitem">
    <a class="md-button md-default-theme" ng-transclude="" ui-sref="docs" href="/docs"><span class="ng-scope">Docs</span></a>
</md-menu-item>

<!-- causing the layout alignment issue seen below -->
```

![screen](https://cloud.githubusercontent.com/assets/350275/10205338/a4245b0e-678e-11e5-8a40-af00601a3d5a.jpg)

**Comment by navneet35371** [comment]
+1

**Comment by jordanskole** [comment]
:+1:

**Comment by audiodude** [comment]
+1

See my codepen here: http://codepen.io/audiodude/pen/dGOMNv
