### ISSUE TITLE
IE 11 md-toast needs height defined for auto centering

### ISSUE THREAD

**Issue by jsr6720** [angular/material#4946]
(From the code pen example)
```javascript
$mdToast.show(
                                $mdToast.simple()
                                    .content(translation)
                                    .position('top center')
                                    .parent(container)
                                    .hideDelay(6000)
                            );
```
Center works fine in FF and Chrome. Left aligns in IE 11.
CSS fix for working in IE 11.
```css
md-toast {
    width: 100%;
}
```

**Comment by jsr6720** [comment]
Not sure if this is at all related to #1773

**Comment by Splaktar** [comment]
Correct behavior in Chrome:
![chromesimpletoastlayout](https://cloud.githubusercontent.com/assets/3506071/10265909/5f2868b2-6a11-11e5-98c4-5351c9f24691.PNG)

Bad layout in IE11:
![ie11toastformattingissue](https://cloud.githubusercontent.com/assets/3506071/10265903/01f8873a-6a11-11e5-99fc-452e74a2bd51.PNG)

Reproduction steps:
Click on 'Show Simple' on the following demos:
https://material.angularjs.org/HEAD/#/demo/material.components.toast
https://material.angularjs.org/0.11.2/#/demo/material.components.toast

**Comment by jsr6720** [comment]
Pull request should be posted by EOW pending internal review @Paychex
