### ISSUE TITLE
md-button in md-toast should be smaller to follow MD spec

### ISSUE THREAD

**Issue by anton-rusanov** [angular/material#4951]
The [spec](https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs) for toasts indicates the distances between the button text and the edge of the toast has to be 24px. As seen in [this snippet](https://codepen.io/anon/pen/GprBJj) (forked from the angular material [demo](https://material.angularjs.org/0.11.0/#/demo/material.components.toast) without changes to address possible demo updates) the distance by default is about twice as large for both custom and action toasts. 
If the spec is followed, then the distance between the md-button border when hovered and the toast border will be about 0, which will look ugly. So my suggestion is to make the buttons smaller for toasts or work with the MD design team to update the toast spec. See this [snippet](http://codepen.io/anon/pen/avpKgX).

**Comment by EladBezalel** [comment]
I agree

**Comment by EladBezalel** [comment]
closed via 1efe816
