### ISSUE TITLE
Error in documentation of whiteframe

### ISSUE THREAD

**Issue by maheshnathwani** [angular/material#4952]
<md-whiteframe class="md-whiteframe-1dp" flex="25" layout layout-align="center center">
    <span>.md-whiteframe-1dp</span>
  </md-whiteframe>
 The class name mentioned is md-whiteframe-*dp where as the css has the class name as md-whiteframe-z* and the documentation shows upto 24dp where as the css file has only 5 levels of whiteframes.

**Comment by ThomasBurleson** [comment]
@maheshnathwani - what is the URL that you are using to see this?

**Comment by maheshnathwani** [comment]
@ThomasBurleson - https://material.angularjs.org/latest/#/demo/material.components.whiteframe

**Comment by ThomasBurleson** [comment]
![md-whiteframe-1dp](https://cloud.githubusercontent.com/assets/210413/10217247/36111c90-67f4-11e5-9ddd-2e49ae4e9fe3.png)
