### ISSUE TITLE
mdTooltip inside mdDialog wrong position

### ISSUE THREAD

**Issue by weisk** [angular/material#4954]
mdTooltip position gets messed up when it is inside an $mdDialog, and the body is scrolled.

plunkr provided:
http://plnkr.co/edit/iEmViRI0wYke8onEsaok?p=preview

related to https://github.com/angular/material/issues/1883

**Comment by jelbourn** [comment]
I can confirm that the tooltip is off.

**Comment by SanderElias** [comment]
Duplicate of #2791. Closed to concentrate discussion in there.
