### ISSUE TITLE
md-datepicker default font size wrong

### ISSUE THREAD

**Issue by BrainsoftLtd** [angular/material#4955]
When using regular inputs and selects in a form, you will notice that the inputs show the text with font-size:13px, and the datepicker uses 14px by default.

**Comment by curvedental** [comment]
As the original poster noted, the .md-datepicker-input class hard codes the font-size to 14px.  This means it does not scale according to the Font Size settings in Chrome.  It also doesn't match the font-size: 100% (16px) for input elements.  When the .md-datepicker-input is overridden to 100% then the icon and input text jump when the datepicker calendar appears.

Here's a plunk which shows the inconsistency and jumping of the text that occurs when setting a larger font size.  https://plnkr.co/edit/p7rbgVdjU1SDPmkAAoyH?p=preview
