### ISSUE TITLE
md-datepicker for ng-repeat items won't display properly when inside an md-tab element

### ISSUE THREAD

**Issue by FabVillegas** [angular/material#4957]
This is an example of a correct md-datepicker. It works fine.
But in this same view I have a md-tab element with some cards to display activities of a project.

![image](https://cloud.githubusercontent.com/assets/7811470/10212114/7043f790-67c0-11e5-97ad-f30b3c0b383c.png)

Is this something to do with the properties of the positioning of a datepicker?
![image](https://cloud.githubusercontent.com/assets/7811470/10212140/9d10e4e0-67c0-11e5-91d6-de42ded9fa08.png)

**Comment by FabVillegas** [comment]
Opening any md-datepicker of any card of any item inside the md-tab sets its values as:

element.style {
    left: 733.641px;
    top: 130px;
}

**Comment by jelbourn** [comment]
Very strange. It looks like the logic that keeps the calendar pane on the screen is misbehaving. Is there any way I could debug this in action? A production in something like CodePen or JsBin would be the most useful.

**Comment by FabVillegas** [comment]
I cannot make the md-datepicker work in CodePen, but
http://codepen.io/anon/pen/PPpPOm

**Comment by jelbourn** [comment]
@FabVillegas That CodePen us usig version 0.8.3. The datepicker was added in 0.11.

**Comment by FabVillegas** [comment]
Fixed it.
![image](https://cloud.githubusercontent.com/assets/7811470/10324586/6b1b8b4a-6c50-11e5-9169-ad192a38b886.png)

The problem is adding the md-tab with its own scroll, I guess having that messes up with the place where the datepicker opens.

Fixing the md-tab by adding the attribute md-dynamic-height
