### ISSUE TITLE
[md-icon] bind md-font-icon

### ISSUE THREAD

**Issue by WnP** [angular/material#4961]
Using `md-icon` without binding `md-font-icon` like:

```html
<md-icon md-font-icon="my-icon"></md-icon>
```
works as expected,
but where trying to bind `md-font-icon` like:

```html
<md-icon md-font-icon="{{ model.icon_name }}"></md-icon>
```

doesn't, when inspecting the DOM using browser debug tools I can see the `md-font-icon` value as expected, but the icon is not shown

Tested in a directive using `ng-model`

**Comment by EladBezalel** [comment]
@WnP it seems to be working on the [Demo page](https://material.angularjs.org/HEAD/demo/icon)
Can you please provide a codepen with your problem?

**Comment by WnP** [comment]
@EladBezalel [here it is](http://codepen.io/anon/pen/MaNMRE)

as you can see this issue is present when using directive with ng-model binding, not when using simple or -indeed- direct binding

**Comment by EladBezalel** [comment]
@WnP I can see two icons.. what browser? do you only see 1?

**Comment by WnP** [comment]
@EladBezalel I see two icons too, but wants to see tree

There's 3 "tests" on this codepen:
- directive + ng-model binding (which doesn't work)
- simple binding
- direct binding

simple and direct binding works as expected, what I'm trying to do is to asign `md-font-icon` using ng-model, as you can see on the codepen the icon name is proprely bind -see `icon name is: fa-gear` which prove that

**Comment by EladBezalel** [comment]
This is as far as i understand not our framework issue, you should address this to our [Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by WnP** [comment]
@EladBezalel I've made a simpler example: [here](http://codepen.io/anon/pen/gPYKKe) with no directive nor ng-bind

Clicking on the button should change the icon, it works on inside `b` tags but doesn't change the icon

Is that your framework issue?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
