### ISSUE TITLE
Safari 8 : issue with animation & angular 1.3.x on 0.11.0

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#4964]
It seems that the animation never ends : md-select & dialog are getting stucked & unusable
Step to reproduce : 
 - get a safari 8
 - set angular-s to 1.3.17 or 1.3.20
 - set angular-md to 0.11.0
Sorry not to provide a codepen, but I have serious issues with codepen on safari 8 and the material codepens from the website are down :)
Works fine with angular-s 1.4.x with 0.11.0 and fine with 1.3.20 with 0.11.1, so it's probably already fixed

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

Please always use and test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.7 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
