### ISSUE TITLE
Disabled md-options still ripple and close md-select on click

### ISSUE THREAD

**Issue by keatonboyle** [angular/material#4967]
I'd expect `<md-option>`s that have been disabled (with a `disabled` or  `ng-disabled` attribute) not to ripple or close the select dropdown on click.  However, sometimes disabled options still animate on click, still show a pointer cursor on hover, and still close on click.

It seems that some browsers result in animation/close and some do not.  Though even in browsers that do not animate, the background of disabled options changes.

See: http://codepen.io/anon/pen/bVwOWG

**Comment by jelbourn** [comment]
Using that CodePen, I was able to see the issue on my laptop (Chrome Linux) but not my desktop (also Chrome Linux, oddly enough).
