### ISSUE TITLE
mdVirtualRepeat - DOM Error when using md-checkbox in md-virtual-repeat

### ISSUE THREAD

**Issue by gejustin** [angular/material#4968]
I am attempting to use mdVitualRepeat with the md-on-demand attribute to create an infinite scrolling list of contacts. Each contact has an md-checkbox directive that will be used for batch actions. I've noticed that scrolling the list upward after a checkbox is clicked (sometimes it takes several checkboxes), causes it to bug out and elements start to disappear. I was able to fix the issue by wrapping the offending line of code in a try/catch block, but that didn't seem robust enough to issue a PR.

I've created a [plunkr](http://plnkr.co/edit/QqSjDTtbMQhMMYzBeiEz?p=preview) demonstrating what I'm trying to accomplish.
I've set up some mock data with pagination and a data service to populate the on demand collection and it behaves similarly to my real code.

##### This error is thrown in the console several hundred times:
`Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

This error points to this line of code on line 711 of `virtualRepeat.js`: 
```javascript
    this.parentNode.removeChild(this.blocks[index].element[0]);
```

#### Stack Trace: 
    VirtualRepeatController.poolBlock_ @ angular-material.js:16543
    (anonymous function) @ angular-material.js:16414
    VirtualRepeatController.virtualRepeatUpdate_ @ angular-material.js:16411
    VirtualRepeatController.containerUpdated @ angular-material.js:16358
    VirtualRepeatContainerController.handleScroll_ @ angular-material.js:16124
    c @ angular.js:1187
    c @ angular.js:3296

**Comment by jelbourn** [comment]
@kseamon do you have time to take a look at this?

**Comment by kseamon** [comment]
Tried it out - reproduced the bug in the plunkr as shown. Updated it to 1.0rc4, and it's fixed.
http://plnkr.co/edit/XdLm3bNH8YYF4Zx5Bvkv?p=preview
