### ISSUE TITLE
chips docs: IE/Firefox cannot delete non-number characters

### ISSUE THREAD

**Issue by topherfangio** [angular/material#4971]
In the Custom Inputs mdChips demo, both Firefox and IE allow you to enter non-numeric text in the number fields. However, once typed, you can no longer use the backspace to delete the text, it instead jumps to the previous chip.

<img width="879" alt="screen shot 2015-10-01 at 3 43 37 pm" src="https://cloud.githubusercontent.com/assets/54370/10233509/6582888c-6854-11e5-95ce-f4a433662e99.png">

**Steps to Reproduce**

1. Visit https://material.angularjs.org/0.11.1/#/demo/material.components.chips in Firefox or IE
1. Scroll to the Custom Inputs demo
1. Enter `44` into the first input and hit enter to create a chip
1. Enter `55` and create a second one
1. Enter `asdf` into the input
1. Press backspace

_Expected Result:_ I can delete the invalid `asdf` characters.
_Actual Result:_ The input loses focus and the `55` chip is highlighted.

**Comment by JordanMajd** [comment]
I've tested this issue in Chrome, Safari and Firefox.

Firefox 41.0.2: backspace highlights `55`
Safari 8.0.8 (10600.8.9): backspace highlights `55`
Chrome 46.0.2490.80 (64-bit): input does not accept non-numeric characters, typing `asdf` results in input cursor moving up about a quarter of a line. I've attached a gif of this behavior.

![chrome](https://cloud.githubusercontent.com/assets/1037492/11004168/f1dde084-8473-11e5-8605-1327bdfd0a44.gif)
