### ISSUE TITLE
Upgrade px to em

### ISSUE THREAD

**Issue by srsgores** [angular/material#4974]
One of my biggest pet peeves is ``px`` over ``em`` or ``rem``.  It prevents the design from properly scaling with other elements.  This library uses *some* ``em``, but the rest (for example [things like this](https://github.com/angular/material/blob/master/src/components/card/card.scss#L1)) still need to be migrated to ``em``.

I am willing to make this change, provided it is a welcome one.

Thoughts?

**Comment by ThomasBurleson** [comment]
@srsgores - Interestingly enough, complaints are well received when they are accompanied with **offers to help resolve**. Thank you ;-)

> Let me talk with the team and respond soon.

**Comment by srsgores** [comment]
Any update on this?

**Comment by e-oz** [comment]
I'd like to see this landed too. Thank you @srsgores for proposal.

**Comment by ThomasBurleson** [comment]
@srsgores - I will respond with details on Tuesday, Oct 6.

**Comment by iamfrank** [comment]
Might be able to chip in with some working hours, also. Severely need the em's on a responsive project downstream.
