### ISSUE TITLE
md-datepicker allows to enter alpha numeric characters

### ISSUE THREAD

**Issue by maddy2308** [angular/material#4975]
If i try to add anything other that date it allows to enter the date

**Comment by dmackerman** [comment]
What?

**Comment by maddy2308** [comment]
If you use md-datepicker and start typing alphabets or special characters it will allow us to enter as against the native <input type="date">

**Comment by jelbourn** [comment]
@maddy2308 Sorry, it is really not clear what you are saying. Are you requesting that the text input only allow characters that could be part of a date? If so, that is not feasible, as different locales have far too wide of a character set to practically filter. Closing this issue for now, please comment if you meant something else.
