### ISSUE TITLE
Focus/hover style for buttons uses gray color with opacity

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#4976]
For example, on a standard blue-themed toolbar the the circle around the menu icon is barely visible:

<img width="111" alt="screen shot 2015-10-01 at 8 30 29 pm" src="https://cloud.githubusercontent.com/assets/9092817/10237118/c3877c86-687b-11e5-9a7f-866dd2c421d7.png">

This is because the highlight color is rgba(158,158,158,0.2). It sounds like the best solution would be to have either semitransparent white or black depending on whether the theme is dark or light. Probably the folks who worked on this are aware of the issue, but just wanted to bring it up since it seems like a good thing to address at the polish stage.

**Comment by ThomasBurleson** [comment]
Will not fix.
