### ISSUE TITLE
How to wrap cards across rows?

### ISSUE THREAD

**Issue by kpgarrod** [angular/material#498]
I have an unknown number of cards, with a width of say 300px. If the cards are too wide to fit in a row, I want them to automatically wrap onto the next row. This is my best effort:

    <div layout="horizontal">
      <md-card ng-repeat="resourceType in resourceTypes"
               flex
               layout="vertical"
               ng-click="openDialog(resourceType.type)"
               class="cc-basic-card"> 
        <h2>{{resourceType.name}}</h2>
        <p>{{resourceType.description}}</p>
     </md-card>
    </div>

 It doesn't wrap. Is there a simple way of doing this please?

**Comment by nicolas15000** [comment]
Hello I have this problem, please help :+1: 
https://stackoverflow.com/questions/44589508/angular-material-md-card-paragraph-break-ng-repeat
