### ISSUE TITLE
Autocomplete wrong padding

### ISSUE THREAD

**Issue by Deadly0** [angular/material#4988]
From demos (Head)
![default](https://cloud.githubusercontent.com/assets/4887213/10257217/b16a7e3e-695e-11e5-9d89-2f739ef48b39.png)

**Comment by topherfangio** [comment]
Can you tell us what browser you are using? I think this is related to the floating label, but I'm not sure.

**Comment by Deadly0** [comment]
Yes, this bug happens only with floating label inputs.
Browsers: Chrome, Opera, IE, FF (Windows 8.1)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
