### ISSUE TITLE
Browser Support on Android - 4.2.2 Does not display correctly

### ISSUE THREAD

**Issue by estevo-de** [angular/material#4992]
Hi All, I've started exploring Angular Material after experimenting with Material Design Lite.
One of the most important things in a layout is the grid.
In my opinion it has to be broad based as far as possible in order to maximise customer experience.
Here are the results:
Android 4.2.2 HTC One 1080 x 1920 - Incompatible
Android 4.3 Sony Xperia Z 1080 x 1920 - Incompatible
Android 4.4.4 HTC One 1080 x 1920 - Compatible
Android 4.4.4 Samsung Galaxy S5 - Compatible
Android 5.1.0 Google Nexus - Compatible
![bildschirmfoto 2015-10-03 um 11 13 44](https://cloud.githubusercontent.com/assets/2319882/10262244/f6000b5c-69bf-11e5-81af-188d2ac9a473.png)
![bildschirmfoto 2015-10-03 um 11 12 23](https://cloud.githubusercontent.com/assets/2319882/10262245/f61de230-69bf-11e5-95e4-ec4b01fed7a6.png)
![bildschirmfoto 2015-10-03 um 11 08 51](https://cloud.githubusercontent.com/assets/2319882/10262246/f625d706-69bf-11e5-9d46-21671f6b732c.png)
![bildschirmfoto 2015-10-03 um 11 08 31](https://cloud.githubusercontent.com/assets/2319882/10262247/f62a1834-69bf-11e5-85a2-786b95a80536.png)
![bildschirmfoto 2015-10-03 um 11 08 17](https://cloud.githubusercontent.com/assets/2319882/10262248/f62cc502-69bf-11e5-8ef8-aceb27d44db0.png)

**Comment by chr22** [comment]
There is only support for android 4.4 and up.

Major browser versions n-1
