### ISSUE TITLE
layout: now depends on parent's display mode

### ISSUE THREAD

**Issue by e-oz** [angular/material#4993]
Please compare this:
http://codepen.io/evgeniyoz/pen/JYWOeo?editors=100
and this:
http://codepen.io/evgeniyoz/pen/QjpOxr?editors=100

Only difference is first tag name.

**Comment by ThomasBurleson** [comment]
![screen shot 2015-10-03 at 7 47 20 am](https://cloud.githubusercontent.com/assets/210413/10262950/e09c7d12-69a2-11e5-920d-7e34538e1a77.png)

**Comment by ThomasBurleson** [comment]
It appears that the `<ui-view>` does not define a **display** or **position** mode.

**Comment by e-oz** [comment]
Indeed. And 99% of directives with custom tags.

**Comment by ThomasBurleson** [comment]
I am not sure how to resolve this... as this appears to be a flexbox (not ngMaterial Layout) issue.
Suggestions ?

**Comment by e-oz** [comment]
Just document it :)

**Comment by ThomasBurleson** [comment]
This will be fixed in the new Layout engine after the v1.0 release.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
