### ISSUE TITLE
layout: `flex="flex"` should be replaced to just `flex`

### ISSUE THREAD

**Issue by e-oz** [angular/material#4994]
Please compare:
http://codepen.io/evgeniyoz/pen/ojZoJb?editors=100
http://codepen.io/evgeniyoz/pen/qOrVgO?editors=100
Was not an issue in 0.11.0, but issue in 0.11.2 (easy to fix, but still should be noted in changelog, to save time).

**Comment by mattiLeBlanc** [comment]
probably related: Flex turns into `class="flex-flex`

https://github.com/angular/material/issues/5044
