### ISSUE TITLE
add prompt dialog?

### ISSUE THREAD

**Issue by jimmywarting** [angular/material#4995]
Addition to $mdDialog. just a suggestion.

**Comment by ThomasBurleson** [comment]
What is the difference between a **prompt** dialog and the current **alert** and **confirm** dialogs?
Can you provide a scenario and a code usage?

**Comment by jimmywarting** [comment]
Well, a prompt dialog has an input where you can type some text

**Comment by ThomasBurleson** [comment]
That is easily done with a custom dialog... right?

**Comment by louiealmeda** [comment]
+ 1

With that, alert and confirm can be easily done with custom dialog as well... right? so why do we have them?

**Comment by aslafy-z** [comment]
+1

**Comment by aminahmedkhan** [comment]
+1
