### ISSUE TITLE
Style md-autocomplete input like the labeled one

### ISSUE THREAD

**Issue by ido567** [angular/material#4998]
Hi

As you know, there is a difference between the style of the autocomplete input with or without label.
I want to put an autocomplete input which look like the labeled one, but just without the label.

In my example, there is an autocomplete input with a label of "Favorite state", I need to keep the design of the input and remove the label.

https://codepen.io/anon/pen/VvpxNX

Thanks!

**Comment by topherfangio** [comment]
We'll look into adding an option for this.

In the meantime, you can just add a custom CSS class and set the label's visibility to hidden: https://codepen.io/topherfangio/pen/avLJpQ?editors=110

**Comment by JobaDiniz** [comment]
+1
