### ISSUE TITLE
md-autocomplete clear input value

### ISSUE THREAD

**Issue by Deadly0** [angular/material#5002]
I need to clear input after autocomplete item is selected. [Example](http://plnkr.co/edit/jdsZo4jefADNhxvY03Zi?p=preview)
But to clear the input I need to use `$scope.$$childTail.searchText = '';` instead of simple `$scope.searchText = '';` because the second do not work.
Is it bug or normal behavior?

**Comment by paulflo150** [comment]
Use the "dot notation" or "controller as"

http://plnkr.co/edit/qBGYOUsF67XVPjlwId4f?p=preview

**Comment by Deadly0** [comment]
@paulflo150 thank you.
