### ISSUE TITLE
md-select creating clone with invalid name

### ISSUE THREAD

**Issue by samio80** [angular/material#5005]
When md-select is created with a name xxx then a select child is created with dot prefixed. This causes that it's not possible to query the select from javascript e.g:
<md-select name="xxx"> results in
<md-select> .... <select name=".xxx">
So when I want to validate:

formName..xxx.$error (Invalid javascript) the only way would be something like formName[".xxx"], but it does not make sense because the rest of inputs do not require the dot in front.

**Comment by samio80** [comment]
The clone does not includes any attribute inherited from the parent (so validation is not possible, or at least I don't see how?)

https://github.com/angular/material/blob/b983c0d4575f6701cb327f29c75354dc31447c74/src/components/select/select.js#L116

**Comment by trimox** [comment]
I'm hoping someone can look into this as well. We had issues posting the cloned md-select form values using a regular form post. I ended up adding hidden elements that updated with select value and posting those.

**Comment by rschmukler** [comment]
The autofill clone shouldn't be used for validation - it is just there to set up a two data binding so that auto-form fillers can interact with the component. I'm curious on the use case of needing to validate it instead of its origin `md-select`?

**Comment by rschmukler** [comment]
This clonse has been removed from the form (it was supposed to never be in the `$mdForm` so this should now be a non-issue. Validation should happen on the `$form[select-name]`
