### ISSUE TITLE
md-tooltip does not show up when navigating via keyboard tab

### ISSUE THREAD

**Issue by qjlee** [angular/material#5007]
Issue is reproduced in the codepen:
https://codepen.io/anon/pen/XmMGmB

It is a bit annoying that it does not show up, is it by design or just a missing feature?  By looking into the source code,  I do not get why we use mouseActive here. 

```javascript
 function bindEvents () {
      var mouseActive = false;
      var enterHandler = function() {
        parent.on('blur mouseleave touchend touchcancel', leaveHandler );
        setVisible(true);
      };
      var leaveHandler = function () {
        var autohide = scope.hasOwnProperty('autohide') ? scope.autohide : attr.hasOwnProperty('mdAutohide');
        if (autohide || mouseActive || ($document[0].activeElement !== parent[0]) ) {
          parent.off('blur mouseleave touchend touchcancel', leaveHandler );
          setVisible(false);
        }
        mouseActive = false;
      };

      // to avoid `synthetic clicks` we listen to mousedown instead of `click`
      parent.on('mousedown', function() { mouseActive = true; });
      parent.on('focus mouseenter touchstart', enterHandler );

      angular.element($window).on('resize', debouncedOnResize);
    }

```

**Comment by marcysutton** [comment]
Tooltips aren't supported on Input fields...they already have a label, so technically it's redundant information. It's surprising it even works for the mouse....support would have to be added for it to work with the keyboard, but I'm not sure it really aligns with the Material Design spec.

**Comment by qjlee** [comment]
https://www.google.com/design/spec/components/tooltips.html

Tooltips are labels that appear on hover and focus when the user hovers over an element with the cursor, *focuses on an element using a keyboard (usually through the tab key)*, or upon touch (without releasing) in a touch UI. They contain textual identification for the element in question. They may also contain brief helper text regarding the function of the element. The label itself cannot receive input focus.

**Comment by marcysutton** [comment]
Yes, tooltips have keyboard support for certain elements, like buttons. I am saying it seems redundant and misaligned with the spec to use a tooltip on a text input. The convention is to use labels and placeholders to communicate the purpose of inputs.

**Comment by marcysutton** [comment]
Also the word "label" in that text is referring to the tooltip, not a form `<label>`.

**Comment by SanderElias** [comment]
I agree with @marcysutton. After some investigation an reading through the relevant [ARIA spec](http://www.w3.org/WAI/tutorials/forms/labels/) 
The current implementation works exactly like the title attribute. So this behavior seems to follow the relevant specs
