### ISSUE TITLE
virtualrepeat with md-menu not working

### ISSUE THREAD

**Issue by pavankumarkatakam** [angular/material#5013]
check out the demo [codepen](https://codepen.io/pavankumar0440/pen/LpWoEe?editors=101), i want to keep the virtual-repeat in md-menu and the whole thing at md-toolbar, like facebook notification. but it is not working. please tell me why?

**Comment by pavankumarkatakam** [comment]
Any work arounds to work this now, instead of waiting for the 0.12.0 milestone release.

**Comment by mackelito** [comment]
+1

**Comment by dmaslov** [comment]
+1

**Comment by tuchk4** [comment]
+1

**Comment by Greynight** [comment]
+

**Comment by kseamon** [comment]
Integrating md-menu and md-select with md-virtual-repeat is on my to-do list once we are satisfied that it is working perfectly in autocomplete, which has been slow going but we're most of the way there.

**Comment by bozheville** [comment]
1.0-rc5 released. Is it fixed?

**Comment by eqbalsajadi** [comment]
@pavankumarkatakam you can use dialog instead of menu

**Comment by pavankumarkatakam** [comment]
Hi @eqbalsajadi , please provide a codepen how to use mdDialog instead of mdMenu

**Comment by eqbalsajadi** [comment]
here it is: https://codepen.io/eqbalsajadi/pen/MKyLeK?editors=001

**Comment by pavankumarkatakam** [comment]
Well it ok, Thanks for the pen.

**Comment by eqbalsajadi** [comment]
it is my pleasure

**Comment by Ardrete** [comment]
In version 1.1.0-rc.5 i had the same problem but in my case the directive flex or attribute display: flex weren't the cause of my headaches.
