### ISSUE TITLE
Virtual Repeat  Snap Scroll support 

### ISSUE THREAD

**Issue by jaymanned** [angular/material#5015]
Any plans to make mdVirtualRepeat scroll support horizontal and vertical snap scrolling of the scrolled elements, i.e. scroll does not allow clipped elements in view? Similar demo [here] (http://alvarotrigo.com/fullPage/#secondPage) though this one uses full sized pages as scroll elements

**Comment by gpopovic** [comment]
+1

**Comment by chrisguerrero** [comment]
+1

**Comment by anishbenji** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
