### ISSUE TITLE
md-tabs and ng-if

### ISSUE THREAD

**Issue by hannesAxiell** [angular/material#5016]
Hi!
There seems to be a bug in md-tabs when using ng-if and md-selected. No matter the expression in the ng-if events aren't propagated to a watched variable (like selectedIndex)

I changed [Burlessons tabs example](http://codepen.io/anon/pen/ZbKzmJ?editors=101) to verify it:

    <md-tabs md-stretch-tabs md-selected="selectedIndex" ng-if="1==1" >

(a more realistic expression would be ng-if="tabs.length" but the above prooves that it's just the ng-if)

I use a model to populate the tabs and if i don't have any tabs, all wrappers and canvases shouldn't be created.

This issue could perhaps be connected with [2291](https://github.com/angular/material/issues/2291) but not sure.

**Comment by iamryandrake** [comment]
ng-if seems to not work well in selects either. Any update on progress of this open issue? https://github.com/angular/material/issues/3940
