### ISSUE TITLE
Does scroll shrink toolbar need div height?

### ISSUE THREAD

**Issue by vinkaga** [angular/material#5019]
The demo of the scroll shrink toolbar specifies the div height as follows
```HTML
<div ng-controller="AppCtrl" layout="column" style="height:600px" ng-cloak>
```
It doesn't seem to work at all without having the div height specified. Specifying the div height is very restrictive. Is there a way to make it work without specifying the div height?

**Comment by Varkal** [comment]
Same issue here. Does'nt seems to work without specify a height

**Comment by pavelhoral** [comment]
You can use combination of `layout-fill` and scrollable `md-content` - https://codepen.io/anon/pen/wKdGXB

**Comment by vinkaga** [comment]
@pavelhoral, that works! Thanks.
