### ISSUE TITLE
Inability to add custom layout breakpoints

### ISSUE THREAD

**Issue by pmowrer** [angular/material#5020]
Prior to 0.11.0, it was relatively easy to add custom breakpoints (e.g. `xs` in our case as we're transitioning away from bootstrap) using the [sass mixins that define the defaults](https://github.com/angular/material/blob/cca1955e4133c210a172fda16fd19266ff39ce9d/src/core/style/layout.scss#L286).

As of 0.11.0, this method no longer works as [layouts became directives](https://github.com/angular/material/blob/77c050aef9bbb1d171af2cffc64f80edb48fcb7a/src/core/services/layout/layout.js#L60). I think it'd still be pretty easy to do, only the methods used to create the directives aren't publicly accessible and would have to be copy/pasted.

I can understand if this is not a design goal of Angular Material, but I thought I'd put it out there in case.

**Comment by ThomasBurleson** [comment]
Great suggestion... and interestingly engouh this feature is already in planning ;-)

**Comment by pmowrer** [comment]
Glad to hear that! Thanks for the update and keep up the great work!

**Comment by ThomasBurleson** [comment]
References https://github.com/angular/material/issues/5034

**Comment by ThomasBurleson** [comment]
With SHA a4a5644d23ee5624ea02413a6d09bce01c1dbeda, we now publish the Layout features with Attribute Selectors only in `angular-material:

*  Developers should also use `<body md-layout-css >` to disable attribute selector conversions to classnames.
*  Attribute selectors cause significant performance degradations in IE

> Future releases will allow developers to use the Layout Javascript (without the external SCSS/CSS) engine to configure breakpoints and even attach callbacks for custom notifications when the mediaQuery changes.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
