### ISSUE TITLE
Md-datepicker display issues

### ISSUE THREAD

**Issue by bkarv** [angular/material#5026]
I'm getting a display issue for the md-datepicker pop-up. Half the screen goes dark grey and I get half a box. I'm using the standard demo code as follows.
<md-content>
  <h4>Standard date-picker</h4>
  <md-datepicker ng-model="myDate" md-placeholder="Enter date"></md-datepicker>
</md-content>
					 
Screen shot below:

<img width="1280" alt="screen shot 2015-10-06 at 6 45 17 am" src="https://cloud.githubusercontent.com/assets/10624315/10291910/ff965de4-6bf7-11e5-8782-d037de8213f8.png">
<img width="1280" alt="screen shot 2015-10-06 at 6 45 36 am" src="https://cloud.githubusercontent.com/assets/10624315/10291913/022a9d36-6bf8-11e5-83ea-bf6c42d0d476.png">

**Comment by kmgilbert100** [comment]
+1 We need offset attribute options for the date picker

**Comment by jelbourn** [comment]
@bkarv Are you able to provide a CodePen or similar that reproduces the issue? I'll need more information to figure out what the problem is.

**Comment by bkarv** [comment]
Thanks Jelbourn for responding. i solved the issue. In my framework CSS I had the following which was conflicting with the new version of angular. Obviously the scroll bar hide issue has been fixed with the latest release. I will close the issue now. 

/*Required for angular material hides scroll bar when angular material select dropdown is on*/
        body {
            overflow-y: auto!important;
        }
