### ISSUE TITLE
Feature: Time Picker

### ISSUE THREAD

**Issue by frodefi** [angular/material#5029]
Issue #648, requesting a date time picker, resulted in md-datepicker. I cannot see any open issue for a time picker, so I am therefore requesting it.

Preferably a clock-style like the [React's Material time picker](http://material-ui.com/#/components/time-picker), see image (except that, for 24-hour mode, it would be visually better to have the high hours in the outer ring, like this [bootstrap time picker](http://weareoutman.github.io/clockpicker/)).
![screen shot 2015-10-06 at 01 33 11](https://cloud.githubusercontent.com/assets/993333/10295595/5595d590-6bca-11e5-8f44-125bff29a531.png)

**Comment by ThomasBurleson** [comment]
This feature is planned for implementation after the v1.0 release.

**Comment by piyushchauhan2011** [comment]
:+1:

**Comment by ericodes** [comment]
I added that #5452 bug closed above, but wanted to add a vote for a google maps style timepicker, which allows you to both type in dates and select from a dropdown with selected intervals.

Thank you!

**Comment by csvan** [comment]
+1

**Comment by DongZhang** [comment]
+1

**Comment by Gfirey** [comment]
+1

**Comment by rudzikdawid** [comment]
http://simeonc.github.io/sc-date-time/material.html
![timepicker](https://cloud.githubusercontent.com/assets/7476577/11914562/258b19f0-a685-11e5-9565-3fb82f3f8143.jpg)

timepicker with material style :)

**Comment by phoenisis** [comment]
+1

**Comment by Nosthertus** [comment]
:+1:

**Comment by piyushchauhan2011** [comment]
Date and Time Pickers from another project, looks good. Here is the demo http://codepen.io/alenaksu/full/eNzbrZ

![screen shot 2016-01-27 at 6 25 20 pm](https://cloud.githubusercontent.com/assets/693487/12606670/5780f15c-c523-11e5-8b37-e4ece7e4e005.png)

**Comment by rvarbanov** [comment]
+1

Altho I like the look of that clock, I think that the time picker should be keyboardable. Meaning there should be a way for the user to tab to the time field and enter time without the use of a mouse.

That would be a really good start - http://mgcrea.github.io/angular-strap/##timepickers

**Comment by bartlomiejborzucki** [comment]
+1

**Comment by princemaple** [comment]
:+1: would be great to have this one working together with the date picker and spiting out a date object as a whole.

**Comment by 90lucasgabriel** [comment]
+1

**Comment by jeson114** [comment]
+1

**Comment by leocaseiro** [comment]
As @piyushchauhan2011 mentioned the https://github.com/alenaksu/mdPickers is really good.
It follows the Angular Material Design http://www.google.com/design/spec/components/pickers.html#pickers-time-pickers

**Comment by rvarbanov** [comment]
@leocaseiro I really like those! Please just add an input field so users can enter the time with the keyboard.

**Comment by jeffmcardle** [comment]
+1

**Comment by jpike88** [comment]
Check out this link, it's a pretty good implementation of this and considering it's build on angular material, maybe it can be pulled in

https://github.com/logbon72/angular-material-datetimepicker

**Comment by princemaple** [comment]
Working on one myself

**Comment by greyhwndz** [comment]
+1

**Comment by puranjayjain** [comment]
You can try [https://puranjayjain.github.io/md-date-time-picker/](https://puranjayjain.github.io/md-date-time-picker/) or use it as a starting point, it is absolutely up to spec and written in vanilla js

**Comment by ThomasBurleson** [comment]
A PR would be welcome... but will be subject to team standards.

**Comment by ngraef** [comment]
@ThomasBurleson Was this closed on accident? Or does the team have no intention of implementing it?

**Comment by ThomasBurleson** [comment]
Material1 will not be implementing this... but a PR is welcome if the community wants it implemented before Material2 provides it.

**Comment by leocaseiro** [comment]
@ThomasBurleson thanks for replying that. I was wondering if you have a list of what features won't be implemented. Do you have a Kanban(trello-ish) or any other tool that we could follow up? Thanks

**Comment by KaySchneider** [comment]
Any updates on the time picker ?     @ThomasBurleson Material2, is this related to the Angular2 version or only to the version 2 of md-material ? ;-)  Sorry for the question...

**Comment by abrararies** [comment]
+1

**Comment by hexadecy** [comment]
This is probably the most advanced: https://github.com/beenote/angular-material-datetimepicker
