### ISSUE TITLE
A child dialog opened from a parent dialog won't close.

### ISSUE THREAD

**Issue by du6** [angular/material#5030]
I tried to open a child md-dialog from a parent md-dialog by event broadcasting. But the mddialog.cancel() function does not close the child dialog.

Codepen demo:

http://codepen.io/anon/pen/VvpWXe

**Comment by ThomasBurleson** [comment]
Stacked Dialogs are not supported.

**Comment by du6** [comment]
It is not stacked dialogs. The parent dialog called mddialog.cancel() to close itself before rootScope broadcasting the event to open the child dialog. But somehow the child dialog no longer responses to mddialog service.

**Comment by no-more** [comment]
Hi,

I had the same issue. And 2 solutions for this:
 * Don't close the first dialog manually, mddialog.show will close it for you (but then you can't return a value which is an issue)
 * or use $timeout before opening the second dialog. I had to set 1000ms for this to work all the time (seems to depends on performance)

I think there's some kind on conflict in the chain process.

**Comment by du6** [comment]
Not reproducible with v1.0.1
