### ISSUE TITLE
md-list-item doesn't support more than one secondary element

### ISSUE THREAD

**Issue by zishanj** [angular/material#5033]
`md-list-item` doesn't support more than one secondary element. If I try to use `md-secondary` class on more than one item like for `checkbox` and `md-icon`, it will only work with first item and the secondary items are also misaligned.

**Comment by MadMub** [comment]
+1

**Comment by ThomasBurleson** [comment]
Multiple Secondary elements are not part of the [Material Design](https://www.google.com/design/spec/components/lists-controls.html#lists-controls-usage) specification.
