### ISSUE TITLE
Promise returned from $mdDialog.show() is resolved immediately

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [angular/material#5036]
According to the documentation, `$mdDialog.show()` returns "`A promise that can be resolved with $mdDialog.hide() or rejected with $mdDialog.cancel().`" Contrarily, the promise returned from `$mdDialog.show()` is being resolved immediately, without any call to `$mdDialog.cancel()` or `$mdDialog.hide()`.

**Comment by ThomasBurleson** [comment]
@topherfangio - can you investigate ?

**Comment by SpenceDiNicolantonio** [comment]
My mistake... I'm not sure what I was doing wrong previously, but everything seems to be working properly.
