### ISSUE TITLE
md-dialog overflows on action-click with Microsoft Edge

### ISSUE THREAD

**Issue by mike1o1** [angular/material#5038]
This is a weird bug and seems to be specific to Microsoft Edge. I am unable to duplicate it in Chrome or even IE 11.

If the contents of an `md-dialog` extend past the height of the screen, the dialog initially renders fine with the overflow. However, as soon as the user clicks on one of the buttons in the `md-actions` area, the content expands to be full height and the text and button gets cut off.

Sample codepen: Click the custom dialog button, then click "Useful" and you'll see the content expand to be full height. I've also attached an animated gif, which hopefully helps illustrate the problem.

![dialogerror](https://cloud.githubusercontent.com/assets/837213/10317949/cbe60e62-6c1b-11e5-827a-3869bb552ea7.gif)

**Comment by WuDo** [comment]
+1

**Comment by tclift** [comment]
Workaround for Edge 12:
```css
md-dialog {
  max-height: 80vh !important;
}
```

Tested working on Chrome 47, Firefox 42, Safari 9, Edge 12.

Tested broken on IE 11 (`md-dialog-actions` moves on action click, similar to original Edge issue).

For my case I used browser detection and applied the `80vh` CSS to Edge only.
