### ISSUE TITLE
MenuBar: Unresponsive after launching $mdDialog with shared $scope

### ISSUE THREAD

**Issue by brianppoole** [angular/material#5041]
I might just be missing a step, but if I launch a dialog from the MenuBar it's no longer responsive after the dialog has been dismissed. This only seems to happen if I'm passing the scope to the dialog. (Line 16 in the example.)

Here's a very basic example:
https://codepen.io/brianppoole/pen/XmRYdN

1. Click on File -> Rename
2. Click either action button to dismiss the dialog
3. Try clicking File

It sort of feels like a state is getting stuck somewhere but I'm not sure.

**Comment by grovina** [comment]
+1

**Comment by rschmukler** [comment]
See [this pen](https://codepen.io/anon/pen/BoZRqg) for an example of it working. The trick is passing in `preserveScope: true` to the `$mdDialog.show` so that the scope isn't destroyed when the dialog is closed.

**Comment by ThomasBurleson** [comment]
@rschmukler  - we definitely need to document the above regarding the dependency on `preserveScope` for shared scopes.
