### ISSUE TITLE
md-datepicker readonly

### ISSUE THREAD

**Issue by dpatinor** [angular/material#5043]
You can restrict the entry of the date manually?,  You can use 'readonly'?

... md-min-date="minDate" md-max-date="maxDate" readonly="readonly"></md-datepicker>

For me this is not working.

**Comment by scspijker** [comment]
I also have this problem, it is worsened because the manual input by the user is completely ignored by md-datepicker (model does not update). So I have users that manually enter a date (because faster), and this causes the form to not show validation errors, but still not validate (because md-datepicker is empty, but input is filled). So :+1:

**Comment by bojancai** [comment]
+1

**Comment by dptinor** [comment]
@scspijker Exactly that was the problem I had, the immediate solution was not to use the md-datepicker.

For correct operation, the manual input should not be ignored by the model. 
Also it would be a plus to have the option of restricting the manual input.

**Comment by sam-g-roberts** [comment]
+1 

same issue with users attempting to use manual input and md-datepicker model not updating or validating

**Comment by ashwinputhige** [comment]
Please add a way to disable manual entry of dates.

**Comment by peio72** [comment]
+1

**Comment by scspijker** [comment]
@ThomasBurleson: this is fixed in a new release?

**Comment by jayeshanandani** [comment]
The issue was in backlog or deprecated. Refer this: [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk)

**Comment by mkakkar81** [comment]
Please help me in resolving this issue as we are receiving lots of production issues wherein user inputs any date format or junks in textbox and complaint that data not saved properly.

**Comment by fariasvp** [comment]
Any workaround to do this?

**Comment by zloom** [comment]
+1

**Comment by josepfdc** [comment]
it would be interesting to implement this feature in md-datepicker
+1

2016-09-09 13:41 GMT+02:00 Anton <notifications@github.com>:

**Comment by j-o-d-o** [comment]
You can add  you can do this `<md-datepicker ... onkeydown="return></md-datepicker`. It might confuse users though that nothing happens when they press a key!!

**Comment by julioponce** [comment]
is "readonly" working now on datepicker? :/

**Comment by drej2k** [comment]
In certain scenarios I am using the md-datepicker tag just to display the date. So I just added ng-disabled="true" as no user interaction with the date picker object was required

**Comment by dftrujillo** [comment]
Maybe you can use this option. You can set readonly property to input created by md-datepicker. Just you must validate that page is loaded before set the property.
In my case i'm using angularjs controller, then i wrote something like this

    $scope.$on('$viewContentLoaded', function(event) {
      $("input.md-datepicker-input").prop('readonly', true);
    });

input.md-datepicker-input is the css applied to md-datepicker input. That works for me

**Comment by edoardoVD** [comment]
well well well... 
in my case I ended up implementing

<input **(click)="picker.open()" onkeydown="return false"**

```
<md-input-container class="example-full-width">
        <input (click)="picker.open()" onkeydown="return false" mdInput [mdDatepicker]="picker" [min]="minDate" [mdDatepickerFilter]="excludeWeekEnds" placeholder="Select event date">
        <button mdSuffix [mdDatepickerToggle]="picker"></button>
    </md-input-container>
    <md-datepicker touchUi="true" #picker></md-datepicker>
```

**Comment by ngDevendra** [comment]
I know this post is quite old - and may other have found out their solutions (posting my version of solution)

Solution One :  Created new Directive which will achieve this : 
```
(function () 
{
    angular.module('APPLICATION_NAME').directive('readOnly', readOnly);

    function readOnly() {
        var directive = {
            restrict: 'A',
            link: link
        };
        
		return directive;
       
	    function link(scope, element) {
            element.find("input")[0].setAttribute("readonly","true");
            element.find("input").bind('click', function(){
                element.find("button")[0].click();
            });
        }
    }
})();

```

Solution Two :  Create Decorator for existing md-datepicker directive

```
(function () {
    'use strict';

    angular.module('APPLICATION_NAME').config(['$provide', function($provide) {
        
        $provide.decorator('mdDatepickerDirective', [
            '$delegate',

            function mdDatePickerDecorator($delegate) {
                var directive = $delegate[0];
                var compile = directive.compile;

                directive.compile = function(tElement) {
                    var link = compile.apply(this, arguments);
                    tElement.find("input")[0].setAttribute("readonly","true");
                    tElement.find("input").bind('click', function(){
			      tElement.find("button")[0].click();
                    });
                };

                return $delegate;
            }
        ]);
    }])
})();
```

**Comment by shinde-prasad** [comment]
I have used above code in config block, getting error $touchDelegate null.

Succeed to get it done using onkeydown="return false;".
