### ISSUE TITLE
Icon Button in Dialog box never remove focus after click

### ISSUE THREAD

**Issue by zishanj** [angular/material#5046]
I am using `md-icon` button inside `md-dialog` box. After I click the icon button the dark ripple around the button doesn't remove unless I click somewhere else to lose the focus. Is there any workaround to this?

**Comment by zishanj** [comment]
I have further checked it and it seems like the dark circle surrounding the icon is appearing outside the dialog box also. It remains there until I lose the focus to the icon button.

**Comment by EladBezalel** [comment]
please provide a codepen so we can investigate more

**Comment by EladBezalel** [comment]
Closed due to inactivity, if it's still occurring please write here and i'll open this issue.

**Comment by clvcooke** [comment]
Still seeing this issue as of rc7. Here is a codepen, its an image button (but I couldn't upload an image): http://codepen.io/clvcooke/pen/jWbGmB 

Steps to reproduce:
 - Click the button (above the click text)
 - Left sidenav will appear
 - Unfocus sidenav and autohide it by clicking on the main content area
 - Button still has highlighting

![image](https://cloud.githubusercontent.com/assets/7168476/11765817/220aa5aa-a137-11e5-92e5-aad797db1335.png)

This is also happening on the main angular material website and can be reproduce with the same steps.

**Comment by EladBezalel** [comment]
dup #5434
