### ISSUE TITLE
Documentation markdown headers not properly rendered

### ISSUE THREAD

**Issue by btford** [angular/material#5051]
See: https://material.angularjs.org/0.11.2/#/api/material.components.autocomplete/directive/mdAutocomplete

<img width="367" alt="screen shot 2015-10-07 at 8 37 32 am" src="https://cloud.githubusercontent.com/assets/474988/10342622/c5de776c-6cce-11e5-8509-ae38712ceaa2.png">

I would not expect to see the `###`, but instead a level 3 header.

**Comment by topherfangio** [comment]
If I recall correctly; all that is needed to fix this is putting a space between the hash tags and the text. I'll see if I can do this next time I'm in that file. Thanks!
