### ISSUE TITLE
md-menu vertical padding inside md-toolbar

### ISSUE THREAD

**Issue by goncaloneves** [angular/material#5052]
md-menu component should have similar behavior as md-button inside md-toolbar.

Currently is setting vertical padding and messes vertical alignment on resolutions under 600px:
https://github.com/angular/material/blob/master/src/components/menu/menu.scss#L118

```css
.md-menu {
  padding: 8px 0;
}
```
![md-menu-padding](https://cloud.githubusercontent.com/assets/6536945/10343671/d9ed795e-6d16-11e5-87a7-3bd1815a6e83.jpg)

**Comment by rschmukler** [comment]
Fixed by 125bfe67b874400a1bb21e67ba229141e5f567ff
