### ISSUE TITLE
Can we use?

### ISSUE THREAD

**Issue by mrfaizanhaider** [angular/material#5053]
can we use just single component of ng-md like chips on another project??

**Comment by ThomasBurleson** [comment]
https://github.com/angular/bower-material/tree/master/modules/js/chips

**Comment by mrfaizanhaider** [comment]
yes or not?

**Comment by ThomasBurleson** [comment]
This is not supported yet; as you will need JS code from `material.core`.

**Comment by ThomasBurleson** [comment]
We
