### ISSUE TITLE
md-datepicker only shows initial date when I click into the date input field

### ISSUE THREAD

**Issue by bastienJS** [angular/material#5055]
sample repro: http://plnkr.co/edit/B0xuv5pJyebju0SBb9gY?p=preview

the sample shows a start and end date for current date. But those dates are only then visible in the datepickers if I click into the input field of the datepicker.

Bug1:
This seems to be only a problem with CHROME. I use Version 45.0.2454.101 m.

In Firefox latest the init display of the dates are fine.

Bug2:
There is still another bug in Firefox, I can not close the dialog... in chrome it works!

**Comment by jsmylnycky** [comment]
+1 to getting this fixed

**Comment by bastienJS** [comment]
When the md-datepicker is NOT put inside a md-input container then the validation messages have a wrong font-size and they are not RED!

Could someone official comment this bug report?

**Comment by JobaDiniz** [comment]
> Note: One of our devs informed me that this isn't an issue if the datepicker is used outside of md-input-container....so that might be a hint as to where the bug is occurring.

Exactly
+1

**Comment by jelbourn** [comment]
As of now, `md-datepicker` doesn't go inside of an `md-input-contianer`. For the remaining problems, see #4233.  

See #5504 for a fix to make this less ambiguous.
