### ISSUE TITLE
md-input-container input ng-focus ng-blur fires when page load

### ISSUE THREAD

**Issue by giriprashaad** [angular/material#5060]
`<md-input-container>
<input type="date" ng-focus="focus()" ng-blur="blur()" >
</md-input-container>`

When page loads, ng-focus and ng-blur fire. Is there something i'm not doing correctly?

**Comment by bathos** [comment]
I've encountered a possibly-related issue. I have a focus event on a button, and it fires on hover... I don't think this is an angular issue but I haven't been able to find anything in ng-material to explain it, either.

**Comment by bathos** [comment]
I've found the answer to my issue at least, but it won't help you if the example you gave is complete. In my case, it was caused by md-tooltip. That might make sense if the md-tooltip in the button had actually fired a focus event, but the event that my ng-focus handler received was a mouseover!

**Comment by EladBezalel** [comment]
hey @giriprashaad, can't reproduce [codepen](http://codepen.io/EladBezalel/pen/zrdMEb)
