### ISSUE TITLE
md-autocomplete has problems with mouse action

### ISSUE THREAD

**Issue by anrose** [angular/material#5067]
If the object you're querying does not exist, and you click the next field in the form instead of tabbing, the field's value is not retained.

**Comment by RolandHeath** [comment]
It might help if you could reproduce this in a codepen or similar. I'm not seeing this on the docs page (or my own) in chrome 45. Which browser are you having this problem with?

**Comment by anrose** [comment]
I am also using Chrome 45 (specifically Version 45.0.2454.101 (64-bit) on OSX if it makes a difference). I can show screenshots and describe what fields are bound to where.

This first screenshot shows a dialog box with a form. The md-autocomplete is on that school field which is bound to a School object with fields for the name of the school, its city, and its state. The city and state fields will auto-populate if the school object being queried already exists and is selected. For now, I've cleared the backend database, and started created a new school for Virginia Tech.
![screen 1](https://www.dropbox.com/s/dudo7njddabw8wz/Screenshot%202015-10-13%2009.01.36.png?dl=0)

This second screenshot shows what happens when I tab over to the city field after. Expected behavior, all is well here.
![screen 2](https://www.dropbox.com/s/kwqtp9fqai2vhn9/Screenshot%202015-10-13%2009.02.54.png?dl=0)

This third screenshot shows what happens when I use the mouse to click to the city field instead of tabbing over.
![screen 3](https://www.dropbox.com/s/8g1duu53eb5guut/Screenshot%202015-10-13%2009.03.18.png?dl=0)
