### ISSUE TITLE
How I check $mdDialog is Open?

### ISSUE THREAD

**Issue by GustavoCostaW** [angular/material#5071]
I checked the documentation, but not found any property :(

https://material.angularjs.org/0.11.2/#/api/material.components.dialog/service/$mdDialog

$mdSidenav(componentId).isOpen(); exist and $mdDialog not?

**Comment by romanchak** [comment]
$mdDialog should return the promise which should be resolved in case if dialog is closed.
var myDialog = $mdDialog.show(...).then(function(result) {
  return result;
}, function() {
  return false;
});

$timeout(function() {
  if(!myDialog.$$state.status) { 
   console.log("Dialog is still active");
  }
}, 5000);

**Comment by GustavoCostaW** [comment]
@romanchak  why  $mdSidenav(componentId).isOpen(); and $mdDialog not?

**Comment by bonatoc** [comment]
"why $mdSidenav(componentId).isOpen(); and $mdDialog not?"
+1

**Comment by AaronBuxbaum** [comment]
+1

**Comment by rnybergh** [comment]
+1

**Comment by urrri** [comment]
+1
I need to disable global shortcuts when any dialog is open

**Comment by LuisP89** [comment]
+1

**Comment by kevintc** [comment]
barryvdh provided a workaround in a comment (issue #1978) :
`    if(angular.element(document).find('md-dialog').length > 0) {
     ...
    }`

But a $mdDialog.isOpen() would be really nice

**Comment by ThomasBurleson** [comment]
Agreed that a consistent API is important: `$mdDialog(componentId).isOpen()` will be added.

**Comment by kevintc** [comment]
Is there a way to have a $mdDialog().isOpen() ? (without having to provide any componentId)
I would use it to know if any mdDialog is open...

How do I know the componentId of a $mdDialog ?
I use $mdDialog.show() but never had to provide any ID... (maybe it's just me misunderstanding something).

**Comment by AaronBuxbaum** [comment]
@kevintc Well, it wouldn't make sense to have `$mdDialog().isOpen()`, sine that could be any mdDialog instance. Personally, I'd like to have the option to both use the dialog object (`myDialog.isOpen()`) or access by compnentId (`$mdDialog(componentId).isOpen()`)

**Comment by GustavoCostaW** [comment]
For me  it wouldn't make sense to have $mdDialog(componentId).isOpen() because not exist open more than one $mdDialog at a time.

$mdSidenav(componentId).isOpen(); it's possible exist two or more open at moment.

**Comment by kevintc** [comment]
I use it in a situation where I don't actually know if a modal is open, thus checking $mdDialog().isOpen() would work pretty well for me...
.isAnyOpen() returning a boolean would be nice :)

**Comment by thelordgabo** [comment]
@GustavoCostaW is posible to have more than dialog open, I saw tree open at a time, I know that this does not follow material design guidelines.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by Eliyar** [comment]
When any $mdDialog is opened, a css class "md-dialog-is-showing" is added to <body>, so you could check by: angular.element(document.body).hasClass('md-dialog-is-showing')

**Comment by DallanQ** [comment]
Thanks @Eliyar

**Comment by biruelrick** [comment]
Hi @Eliyar, in my case I need to close any $md-dialog that I not know their componentId and your solution works fine. 

Thanks so much

**Comment by santospatrick** [comment]
An example of how to listen for an event when *any modal opens ou closes*:

```javascript
var element = document.body;
var observer = new MutationObserver(function(mutationsList) {
  for (let mutation of mutationsList) {
    if (mutation.target.classList.contains("md-dialog-is-showing")) {
      console.log("some modal opened");
    } else {
      console.log("some modal closed");
    }
  }
});

observer.observe(element, {
  attributes: true,
  attributeFilter: ["class"],
  childList: false,
  characterData: false
});

// Remember to disconnect this observer after you use it.
// Maybe on route change or something
// observer.disconnect();
```
