### ISSUE TITLE
Checkbox ng-change issue

### ISSUE THREAD

**Issue by anteksiler** [angular/material#5072]
Using this code:
```
<div ng-repeat="option in question.options">
	<md-checkbox class="question-option" data-condition="{{question.condition}}" checklist-model="answers.answer[question.survey_question_id]" checklist-value="option.id" ng-change="check_condition(answers.answer[question.survey_question_id])" aria-label="{{question.question}}">{{option.option}}</md-checkbox>
</div>
```
The function is called with everychange, however, it returns the model that is before the action. 
Lets say there are 2 checkboxes, both unchecked. If you check one of them, the model returns null, but if you uncheck it, it returns the checked value.

**Comment by Soulcyber** [comment]
i think we have the same problem, ng-change doesn't provide the new ng-model value but return the old one

**Comment by anteksiler** [comment]
I solved this by throttling the function. In my case, it was triggering twice.

**Comment by Soulcyber** [comment]
i've solved with this: 
```html
<md-checkbox ng-model="isCovered" ng-change="toggle(isCovered)">Description</md-checkbox>
```
And in the controller function i did this:
```javascript
$scope.toggle = function(value){
    $scope.isCovered = value;
    //use value
}
```

**Comment by EladBezalel** [comment]
@anteksiler can you please provide a codepen of your problem?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
