### ISSUE TITLE
fab-speed-dial, fab-toolbar: react slowly on click

### ISSUE THREAD

**Issue by HendrikWansing** [angular/material#5078]
Hi,

we use md-fab-speed-dial and md-fab-toolbar in combination with a single trigger.
All directives have the same variable as attribute in md-open.

On Desktop-Browser the performace is okay but on iPhone6+ it feels very slow. Like 500ms till animation starts.

Code Snippet:
<md-fab-speed-dial md-open="switch"
                   md-direction="up"
                   class="md-fab-bottom-right md-fling"
                   id="fab-speed-dial-list">
[...]
<md-fab-speed-dial>

**Comment by topherfangio** [comment]
A few things have changed recently with the FABs and buttons. Can you re-test against master and please provide a Codepen demo?

*  Angular Material HEAD
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
 *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
 *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
 *  Angular 1.3.19 (or greater)
 *  Angular 1.4.7 (or greater).

**Comment by topherfangio** [comment]
Bumping this to RC6 since we have not heard from you. Please provide a Codepen so that we can see the exact version displaying this issue and begin creating a fix.

**Comment by topherfangio** [comment]
We really need a Codepen to work on this. If you can provide one, we will reopen.

**Comment by JaySardhara** [comment]
@topherfangio 
Please find codepen http://codepen.io/jaysardhara/pen/jrNEPY

We can see lag in animation when opening fab-toolbar. This lag is more evident in larger screen sizes.

**This issue is currently visible in only Firefox.** 
Version: 48.0
Build ID: 20160726073904
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0

**Comment by topherfangio** [comment]
@JaySardhara Thanks for the demo; I can definitely see the issue. I did a quick test to see if adding `rotate(0.01deg)` helps like a lot of places online say, but it did not seem to make a difference.

I'll dig into this and see if we can get it into the 1.1.2 release.

Thanks!

**Comment by JaySardhara** [comment]
@topherfangio Thanks for prompt reply and update.

**Comment by Splaktar** [comment]
I am not able to reproduce this with AngularJS Material `1.1.22` with Firefox `76.0.1 (64-bit)` in the above CodePen, my [updated CodePen](https://codepen.io/Splaktar/pen/WNQVyVx), or the docs site.
