### ISSUE TITLE
md-no-bar does nothing on md-tabs

### ISSUE THREAD

**Issue by myagoo** [angular/material#5079]
From what I understood from the sources, md-no-bar directive should hide the ink bar from md-tabs... But it does'nt (v0.11.1 and before).

I'm using the npm build of angular-material. There seems to be only one occurence of the "mdNoBar" string in the required file and it is :
```
	angular.module('material.core')
	    .factory('$mdInkRipple', InkRippleService)
	    .directive('mdInkRipple', InkRippleDirective)
	    .directive('mdNoInk', attrNoDirective)
	    .directive('mdNoBar', attrNoDirective)
	    .directive('mdNoStretch', attrNoDirective);
```

**Comment by amritk** [comment]
It should be md-no-ink-bar https://github.com/angular/material/issues/4082
