### ISSUE TITLE
md-menu(icon): Icon squished by md-button's(a href version)  text

### ISSUE THREAD

**Issue by epelc** [angular/material#5082]
If you have a button with an icon in an `md-menu` and the button is a link(using href/ui-sref instead of ng-click) or essentially if the button is using the `a` tag instead of the `button` tag. Then if you have a scrollbar and lots of text in it the icon will shrink down to about 7px wide because the `<a></a>` version uses `display: flex;` instead of `display: inline-block;`.

I'm not sure if one should be doing the other(probably for consistency?) but if that's too much of a hassle to fix then adding `min-width: 24px;` to the icons within the menu also fixes this.

Demo on [codepen](https://codepen.io/anon/pen/WQOKLj)

Example from demo
![image](https://cloud.githubusercontent.com/assets/5204642/10397275/c18804e2-6e74-11e5-825a-c33cee52edec.png)

From a real app
![image](https://cloud.githubusercontent.com/assets/5204642/10397193/62f6cfee-6e74-11e5-996e-e0913e006977.png)

Also note the lots of text part isn't required if your not setting the `width` attribute on `md-menu-content`. So this does affect normal users(like me). For example here is my app without lots of text and without the `width` attribute.
![image](https://cloud.githubusercontent.com/assets/5204642/10397297/e33f4082-6e74-11e5-8564-7c869c67ed1c.png)

**Comment by epelc** [comment]
Also this didn't happen in `0.10.1`. I upgraded to `0.11.2` yesterday and encountered it. It also still happens on the latest master.

**Comment by jordanskole** [comment]
:+1:

**Comment by programmist** [comment]
When checking your demo, it works as expected. The issue appears to have been resolved.  If you can continue to demonstrate this issue please reopen the bug.
