### ISSUE TITLE
IE 11 compatibility?

### ISSUE THREAD

**Issue by dsun29** [angular/material#5084]
When playing with offical MD demo I found that it works well in Chrome but in IE there are a couple of issues. The attached screenshot 1 shows one issue. It is Checkbox demo page. Another issues comes from Subheaders/Late Message. Check screenshot 2. I use Win8.1. 

![image](https://cloud.githubusercontent.com/assets/9710207/10399719/0a22c73c-6e7a-11e5-9c02-f847040c3fca.png)

![image](https://cloud.githubusercontent.com/assets/9710207/10399769/67ce3826-6e7a-11e5-84da-f2185107a3e4.png)

**Comment by enderdickerson** [comment]
+1. Similar formatting issues discovered today

**Comment by valtersboze** [comment]
md-autocomplete is somewhat broken in 11.x , working fine in 10.x
with IE11 you cannot touch the scrollbar in md-autocomplete using IE and theres a weird padding.

**Comment by Patrik-Lundqvist** [comment]
The current IE 11 support is subpar, many of the components has major layout issues and performance becomes very bad as soon as you use a few components on the same page. I truly hope better IE-support will become a priority :)

**Comment by hillerstorm** [comment]
Ever since #8aeb760 IE perf has gone down the drain... any release after that one is unusable for us in IE.
So much for "layout fixes"...

**Comment by websirnik** [comment]
I can confirm that starting 0.11.2 IE performance has become immensely slow  cc: @ThomasBurleson

**Comment by JSOdin** [comment]
+1 on the performance down. esp. on state changes and md-tabs

**Comment by ThomasBurleson** [comment]
The CheckBox demo issue is related to the following IE issue:

https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers

Simply wrapping the `<fieldset>` in a `<div flex>` wrapper solves the issue.
Similarly any use of `<md-button flex>` will need similar wrappers.

**Comment by ThomasBurleson** [comment]
A Pull Request is ready to warn for these situations:   https://github.com/angular/material/pull/6024

**Comment by ThomasBurleson** [comment]
Closed with SHA e82ed42cc3da98052202b9532a999deb30431fd6

**Comment by ThomasBurleson** [comment]
Here is a great resource:

![ngmaterial community](https://cloud.githubusercontent.com/assets/210413/11609737/aa1f50be-9b54-11e5-9bb0-f3068b352d5f.png)

CodePen [Angular Material Layouts](http://codepen.io/collection/XExqGz/) community.

**Comment by scriptsure** [comment]
so are we to assume that it is not really compatible with IE11? in that it requires intervention to get things to lay properly....

**Comment by ThomasBurleson** [comment]
It is compatible with CSS; with some edge-cases [of course] since it is IE. Why are you assuming not compatible ?

**Comment by scriptsure** [comment]
@ThomasBurleson sorry not a blanket statement there is a great deal that renders OK... but i also get MANY rendering issues that i DO NOT get in chrome. It seems like the CONTENT sections in some instances i get HUGE horizontal scroll bars... as an example...

**Comment by ThomasBurleson** [comment]
@scriptsure - best to open a new issue with concise CodePen demo. Thank you.
