### ISSUE TITLE
Can't enter space into input when FAB speed-dial is open by default.

### ISSUE THREAD

**Issue by jelbourn** [angular/material#5085]
http://codepen.io/katolikau/pen/gaRBLj

If there is an `<md-fab-speed-dial>` with  `md-open="true"` on the page, then you can't enter a space character into any `<input>` on the page. This means that there's some overzealous event listener doing `preventDefault` somewhere on the page.

cc @topherfangio

**Comment by epelc** [comment]
We just ran into this issue in prod. We just switched from a fab to the speed dial to add a few options.

I think it's also more likely if you navigate to a child state(which replaces your speed-dial) as it's getting bugged out requiring a refresh. Do you know if there is anything we can call on state change to make sure the speed-dial gets rid of it's event listeners?

**Comment by epelc** [comment]
@jelbourn I think I found the cause.

https://github.com/angular/material/blob/7251684315bcc65fcd7599ac88f84dcf51a2a219/src/components/fabSpeedDial/fabController.js#L169
Also see the `enableKeyboard()` function just above that.

The document event listeners should not listen for space. Space should only be listening on the speed-dial element itself.

**Comment by joshterainsights** [comment]
Has this also been fixed for FAB toolbar? Or does this part of the commit...
> Additionally, all keypress events are now bound to the element itself instead of document.

automatically fix it?

**Comment by topherfangio** [comment]
@joshterainsights The code that was fixed is shared between both the FAB Speed Dial and the FAB Toolbar, so it should be fixed. If not, could you please open a new issue and ping me about it? Thanks!

**Comment by joshterainsights** [comment]
I won't be able to find out. I just forced bower to use 1.0.0-rc4 instead of the master branch, and it's a *lot* more responsive now (yay!) so I can't use an input field without the toolbar closing.
