### ISSUE TITLE
(bug) md-slider - slider has focus animation on open

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5088]
1st slider shows as normal.  slider point not focused (enlarged).

2nd and 3rd slider point show as focused when opened.

![untitled screencast](https://cloud.githubusercontent.com/assets/5133412/10404140/f1ea2c00-6e8d-11e5-954a-5435b17e52f6.gif)

**Comment by EladBezalel** [comment]
@0101adm can you please provide a codepen so we can investigate this more?

**Comment by 0101adm** [comment]
cannot dup.
