### ISSUE TITLE
md-select async does not display md-progress-circular

### ISSUE THREAD

**Issue by julbr** [angular/material#5093]
To keep things simple, I have copy/pasted the demo's code to test md-select in my project:
HTML:

    <div layout="column" layout-align="center center" style="height: 100px;">
        <md-select placeholder="Assign to account" ng-model="user" md-on-open="loadQBOAccounts()"
                                       style="min-width: 200px;">
            <md-option ng-value="qboAccount" ng-repeat="qboAccount in qboAccounts"> <[qboAccount.name]></md-option>
        </md-select>
    </div>

JS:

    $scope.qboAccount = null;
    $scope.qboAccounts = null;
    $scope.loadQBOAccounts = function() {
        return $timeout(function() {
            return $scope.qboAccounts = $scope.qboAccounts || [
                {
                    id: 1,
                    name: 'Scooby Doo'
                }, {
                    id: 2,
                    name: 'Shaggy Rodgers'
                }, {
                    id: 3,
                    name: 'Fred Jones'
                }, {
                    id: 4,
                    name: 'Daphne Blake'
                }, {
                    id: 5,
                    name: 'Velma Dinkley'
                }
            ];
        }, 10000);
    };

The select component works well, but md-progress-circular doesn't show up.
During the async loading, this is the HTML generated inside the select box (ng-hide active..):

    <div class="md-select-menu-container ng-scope md-default-theme md-active md-clickable"
     style="left: 742px; top: 336px; min-width: 200px;">
    <md-select-menu class="md-default-theme" id="select_menu_1" role="listbox"
                    aria-multiselectable="false" style="transform-origin: 100px 82px 0px;">
        <md-content class="md-default-theme">
            <div>
                <md-progress-circular md-mode="{{progressMode}}" ng-hide="$$loadingAsyncDone"
                                      aria-valuemin="0" aria-valuemax="100" role="progressbar"
                                      class="ng-scope md-default-theme" aria-hidden="false"
                                      style="transform: scale(0.5);">
                    <div class="md-spinner-wrapper ng-hide">
                        <div class="md-inner">
                            <div class="md-gap"></div>
                            <div class="md-left">
                                <div class="md-half-circle"></div>
                            </div>
                            <div class="md-right">
                                <div class="md-half-circle"></div>
                            </div>
                        </div>
                    </div>
                </md-progress-circular>
            </div>
            
        </md-content>
    </md-select-menu>
    </div>

I'm using angular 1.4.6 and angular-material v0.11.2-master-b998696
Any ideas of what could cause this?

**Comment by Duovili** [comment]
+1

**Comment by ThomasBurleson** [comment]
Please convert this to a CodePen.

Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
