### ISSUE TITLE
Sticky Footer with Scroll Shrink Header

### ISSUE THREAD

**Issue by vinkaga** [angular/material#5094]
While each of them work fine separately, I can't seem to get the two working together. Any suggestions would be appreciated.

**Comment by EladBezalel** [comment]
Can you please post a codepen?

**Comment by vinkaga** [comment]
Two versions - scroll shrink doesn't work on either of them
1. http://codepen.io/vinkaga/pen/LpLwjE
2. http://codepen.io/vinkaga/pen/epRwyy

**Comment by EladBezalel** [comment]
You're using old versions of ngMaterial, works with head
http://codepen.io/EladBezalel/pen/WQOVdz

**Comment by vinkaga** [comment]
It's footer is always visible - for sticky footer it should show only when the page is scrolled to bottom.

**Comment by EladBezalel** [comment]
Something like this?
http://codepen.io/EladBezalel/pen/vNZovx

**Comment by vinkaga** [comment]
Actually no. In this example (http://codepen.io/vinkaga/pen/LpLwjE), see how the footer scrolls out of the viewport when the page is scrolled up. But when the content is smaller than the viewport height (by deleting some of the 'Bla bla ...'), the footer sticks to the bottom edge. 

In your code pen, the footer does stick to the bottom edge but it is always visible even when content is larger than the viewport and the page is scrolled up.

**Comment by EladBezalel** [comment]
@vinkaga http://codepen.io/EladBezalel/pen/ZbJzNB,
BTW this is not an issue, you should ask these kind of questions in the forum
