### ISSUE TITLE
Virtual repeat should expose an "isLoading" property

### ISSUE THREAD

**Issue by Madd0g** [angular/material#5095]
I think it's pretty cool how the virtual repeater renders rows that don't have data and then populates them with data, I currently use something like this to display a loading message:

     <div md-virtual-repeat="item in items">
             ........
             <span ng-if="!item">loading...</span>
     </div>

I would much prefer a more robust solution like `$isLoading`, like ng-repeat does `$last`.

What do you think?

**Comment by gpopovic** [comment]
I would love that also.

**Comment by mackelito** [comment]
+1
