### ISSUE TITLE
ng-class ignored on <input> when inside <md-input-container>

### ISSUE THREAD

**Issue by djmarcus1** [angular/material#5099]
It appears that an `ng-class` attribute is ignored when the `<input>` is inside `<md-input-container>`.

See codepen: http://codepen.io/djmarcus/pen/qOXbMO

In this example, I use the `ng-class` to show the input in green color if the input ends in an even digit and in red for any other charatcer.

When I use the `<input ng-class=...>` inside `<md-input-container>` the class is ignored. When I use it outside it works.

Here's the relevant HTML snippet:

    <md-input-container layout="row" layout-align="start center">
      <label>MyValue:</label>
      <input type="text" ng-class="{valueValid: isValid, valueInvalid: !isValid}" ng-model="myValue" ng-change="myValueChanged()" placeHolder="Enter even digit ending string">
    </md-input-container>

    <label>my value:</label>
    <input type="text" ng-class="{valueValid: isValid, valueInvalid: !isValid}" ng-model="myValue" ng-change="myValueChanged()" placeHolder="Enter even digit ending string">
  </div>

I am using angularJS version 1.4.6 and Material version 0.11.1

**Comment by EladBezalel** [comment]
Works for me, it's green on even numbers..

**Comment by djmarcus1** [comment]
Look at the first `<input>` value display (which is inside `<md-input-container>`), it shows **no color**.

The second `<input>` which is **not** inside the `<md-input-container>` **does** show color.

I've changes the labels to 'WORKS' and 'FAILS' to make it more obvious.

**Comment by EladBezalel** [comment]
Oh, OK i saw it.. 

a quick override is:
```css
.valueValid {
  color: green!important;
}
.valueInvalid {
  color: red!important;
}
```

We should take a look why your class is not stronger than `.md-input`

**Comment by djmarcus1** [comment]
Toda for the work-around. :-)

**Comment by RolandHeath** [comment]
It's a css specificity issue. An alternative workaround, not using !important is:
```
input .valueValid {
  color: green;
}
input .valueInvalid {
  color: red;
}
```

**Comment by EladBezalel** [comment]
@djmarcus1, i spoke with the team and @RolandHeath solution is our solution as well,
or you can be even more specific with:
```css
md-input-container .md-input.myclass {
  color: red;
}
```

**Comment by djmarcus1** [comment]
I understand the solutions.
 
imho: Since this is a ‘gotcha’, the documentation should mention that an ng-class inside a child element of md-input-container is competing with the one used internally by the md-input-container itself and offer these solutions as options.
 
-Thanks for your help
David

**Comment by EladBezalel** [comment]
@djmarcus1 a PR is always welcome :)

**Comment by imornar** [comment]
@RolandHeath thanks, it worked...
