### ISSUE TITLE
Make md-select always opened like a html select multiple

### ISSUE THREAD

**Issue by bastienJS** [angular/material#5101]
I need a mix of a native multiple select tag but with your material design style. 

![listbox](https://cloud.githubusercontent.com/assets/5945955/10418930/6829f220-7068-11e5-9171-3aaf5bdf3e21.PNG)

I would like to have your md-select component to be always opened.

 Do you plan something like that?

**Comment by rschmukler** [comment]
We will chat with the UX team about a post-1.0 look, but currently it is not in the spec.
