### ISSUE TITLE
Left & right arrow keys do not work inside input fields in an md-menu

### ISSUE THREAD

**Issue by bathos** [angular/material#5103]
Demonstration here:

https://codepen.io/anon/pen/EVvgrx

(not my actual code, just a quick recreation based on one of the demos).

In my case I'm employing md-menu to encapsulate a list of numeric field options that would otherwise add too much noise to the form, and which have an alternative concise representation when the menu is closed.

This may well not be a bug; given the directive's name, it may not have been anticipated that someone would shove an input list in there. If the intended purpose of md-menu was strictly application menus, it would make sense that arrow keys are intercepted for navigating nested submenus. In every other regard this directive is perfect for a case like mine though, and I see no other that makes sense. If this is actually working as intended, is there a means to disable or override the default arrow key handling in md-menu?

### Edit

I was able to disable it with a directive on the input like so:

      elem.on('keydown', event => {
        if (event.keyCode == 37 || event.keyCode == 39)
          event.stopImmediatePropagation();
      });

However I'll leave the issue open for now in case one of the md devs feels that the current md-menu behavior with input elements is incorrect.

**Comment by marcysutton** [comment]
That really doesn't look like a menu anymore. I think a dialog is a better UI pattern for what you're trying to achieve.

**Comment by bathos** [comment]
That's true, I'm really not using it as a menu, which is why I wondered if there was another means to achieve this in ngMaterial without the menu-specific keyboard handling and aria markup. What I needed was a "list of options the drops down from a button", which happens to be -- visually and in terms of click/mouse behavior at least -- identical to md-menu. That it's so close made me wonder if there's a more generic parent directive hidden in the wings, or else options that would allow using  it more generically. Being daunted by the prospect of replicating the sophisticated drop-down positioning behavior of md-menu is what prevents me from trying to roll my own without any menu baggage.

As for replacing it with a different interface ... if it's required that I justify my UX choices before getting information :stuck_out_tongue:, I can say that this not-menu is, despite containing a slightly busy list, nonetheless an essential part of the form and a modal would feel more disruptive in context; and that I tried several other takes, including a modal, previously; and that this is an application which is being designed for a single, specific user whose needs I know precisely.

After I came to understand the issue better, and realized md-menu was very literal about "menuness", I was hoping there might be / could be a way to get the generic behaviors without the menu-specific behaviors. If not though, I suppose the issue should be closed.

**Comment by marcysutton** [comment]
Menus have to be accessible from the keyboard (using the arrow keys), and jamming inputs into them isn't a common pattern. A dialog can take more complex content, but it might not have the animation you're after. I think the team would have to discuss whether menus can and should support more complex content. It would definitely impact the ARIA we have in place for menus, which are sort-of all-or-nothing when it comes to roles (`role=menu` / `role=menuitem` requires only menu items, not a mix of form inputs). We'd have to toss out the ARIA we have now for something else that may not already exist. I still recommend using a dialog for this interaction.

**Comment by bathos** [comment]
Agreed, md-menu is and ought to remain specific to menu's semantic meaning. I think it would be cool if the behavior of "list that expands from another clickable element" were made available more generally, but if the masses aren't clamoring for it...

**Comment by stefan-leye** [comment]
I have the same problem.

**Comment by fadak** [comment]
you can use mdPaned instead of a mdMenu. 
see the first example of this [page](https://material.angularjs.org/latest/demo/panel)
