### ISSUE TITLE
New version causes the height of flex items not fit their contents

### ISSUE THREAD

**Issue by johnnyluu** [angular/material#5104]
I updated Angular Material to the latest version because I wanted to use the new menubar. However, the new implementation of flex layout caused my grid list to not scale property in MOBILE view. The parent elements, which have flex="50" and flex-sm="100", dont seem to fit it's content anymore. More specifically, some of the containers of the md-cards don't have the same height as the md-cards,  resulting in overlapping cards.
THis is how it works now: http://codepen.io/johnnyluu/pen/jbLvge
I've been trying to fix this for more than 5 hours without any luck. Can someone more familiar with flexbox enlighten me on what can be done to fix this? Thank you very much!

**Comment by ThomasBurleson** [comment]
Some thoughts:

*  Trying setting explicit heights on your cards
*  You are using Angular v1.4. Please use Angular 1.3.19 or greater, 1.4.6  or greater 
*  Please retry with the HEAD version of Angular Material
*  Please provide a simplified CodePen

Whenever possible, provide a CodePen demo to report an issue. To expedite resolution, please always test with the latest versions:

*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

**Comment by johnnyluu** [comment]
Hi @ThomasBurleson , Thanks for the comment. I think specifying a explicit height works, but I do need responsive height on this. So the only way I can think of is to update the height with JavaScript every time the window is resized, but that's certainly not ideal. 

I've updated the initial post with a codepen demo: http://codepen.io/johnnyluu/pen/jbLvge with the latest angular and material. Unfortunately the bug is still there. Try making your brower window narrower, and you'll see the cards overlap with each other as in mobile mode, the height of the container is smaller than it's content (I think it ignores the padding on the child element). Found it weird it only happens in mobile view. 

Any idea how I can fix this without setting explicit heights?

**Comment by ThomasBurleson** [comment]
@johnnyluu - We are investigating this... 

> At this point, I think this is an issue with Flexbox (and a missing workaround) instead of an issue with Angular Material.

**Comment by johnnyluu** [comment]
Thanks for that! I guess I'll set explicit heights to work around it until it gets resolved.

**Comment by ThomasBurleson** [comment]
@johnnyluu - Here is a working CodePen:  http://codepen.io/ThomasBurleson/pen/NGaeMg  using latest in master. The trick here is:

```html
 <div layout="row" layout-sm="column" class="cp" style="min-height:100vh" >
    <div ng-repeat="n in [1,2,3,4,5]" class="container" flex="50" flex-sm="100" layout="column">
      <md-card flex >{{n}}</md-card>
    </div>
</div>
```

where 
*  the parent container (outside the repeated divs) has a defined, not-ambiguous height. I used 100vh but you could also specify an px height. 
* I set the `<md-card flex>`

This all seems to work great.

**Comment by johnnyluu** [comment]
@ThomasBurleson Thanks for that. I think what your pen does is trying to fit all the cards in 100vh. However if you give the cards a defined min-height (which is what I need), they once again overlap.
