### ISSUE TITLE
Required md-date-picker with Floating label option like other components have

### ISSUE THREAD

**Issue by sunnyshah01** [angular/material#5106]
- Floating label in date picker is required optionally.
- Currently there is two buttons in md-date-picker. One is date picker icon button and another is drop down button.
- Date picker should look like another components Input, Select and Autocomplete so all components looks same.
- css for date picker validation message is required

**Comment by corentin-gautier** [comment]
+1

**Comment by aviadhahami** [comment]
+1

**Comment by StevenGnt** [comment]
+1

**Comment by hatuan** [comment]
+1

**Comment by barmaley443** [comment]
+1

**Comment by jelbourn** [comment]
Dupe of #4233
