### ISSUE TITLE
Required css for date picker validation message

### ISSUE THREAD

**Issue by sunnyshah01** [angular/material#5107]
- Required CSS and proper position for a validation message of date picker.
- Size of input in date picker is fixed so it should be as per flex size.
- date picker icon button position should be optional, either start position or end.

**Comment by jelbourn** [comment]
@sunnyshah01 

> Required CSS and proper position for a validation message of date picker.
> Size of input in date picker is fixed so it should be as per flex size.

I don't follow what you mean by either of these. Can you elaborate?

**Comment by jelbourn** [comment]
Closing this issue since I'm not certain to what it is referring. Feel free to open a separate issue for the icon-button alignment feature request.
