### ISSUE TITLE
generated calendar grid cell id is  one month too low

### ISSUE THREAD

**Issue by jlmagee** [angular/material#5110]
please note that getMonth() returns 0-11 not 1-12 so the generated grid cell id is off by one month.

 
   * Gets an identifier for a date unique to the calendar instance for internal
   * purposes. Not to be displayed.
   * @param {Date} date
   * @returns {string}
 
  CalendarCtrl.prototype.getDateId = function(date) {
    return [
      'md',
      this.id,
      date.getFullYear(),
      date.getMonth(),
      date.getDate()
    ].join('-');
  };

**Comment by jelbourn** [comment]
@jlmagee these are internal element IDs whose only purpose is to be unique, not to represent the actual date. As the comment says, `Not to be displayed.`.

**Comment by jlmagee** [comment]
@jelbourn  @ThomasBurleson Yes, but it seems likely that someone will want to access those elements to visually indicate something  about the particular date and it would be so much more nice to do with the real date. And it would be so easy to put the +1 next to getMonth()
