### ISSUE TITLE
ng-cloak not working with md-autocomplete

### ISSUE THREAD

**Issue by blootch** [angular/material#5112]
Hi,

ng-cloak doesn't work on md-autocomplete results. Applied with attibute or CSS, both doesn't work. I still see {{value}}.

More informations :

- It only append on the first load.
- Angular material 0.11.2
- Angular 1.4.4
- Angular + angular material loaded in <head> section.
- CSS rule for ng-cloak is added to the app css file.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ?

**Comment by blootch** [comment]
Hi Thomas,

No need CodePen, it happend also on the demo page : https://material.angularjs.org/latest/demo/autocomplete

To reproduce this : 
1) refresh the page
2) Concentrate yourself to see the {{}}
3) Click on the first input (with states)

Note : It only happend with the first click. With second click it is ok. So, to reproduce again, refresh the page.

Do you see it ? It happend also with ng-cloak applied to the element containing the {{value}}

**Comment by blootch** [comment]
The issue is the same with lasted versions from rawgit + angular 1.4.7.

**Comment by ThomasBurleson** [comment]
@blootch - I visited the URL  https://material.angularjs.org/latest/demo/autocomplete, refreshed, and catpured the image below (in which I cannot see any `{{ }}`:

![screen shot 2015-10-13 at 4 04 30 pm](https://cloud.githubusercontent.com/assets/210413/10468341/23636c5e-71c4-11e5-8429-aaa7b4992fd5.png)

**Comment by ThomasBurleson** [comment]
![screen shot 2015-10-13 at 4 09 35 pm](https://cloud.githubusercontent.com/assets/210413/10468468/d2c25778-71c4-11e5-9ca0-1fc6ae10f0e0.png)

**Comment by blootch** [comment]
Do you see it on the gif ?

To reproduce : 
1) refresh the page
2) Click on the input
3) If you don't see at the first click, refresh again and click.

![telechargement](https://cloud.githubusercontent.com/assets/6443098/10471224/2b80c652-7214-11e5-9192-6852de7b56a9.gif)

**Comment by friedolinfoerder** [comment]
Is there any progress or any plans to fix this issue?

**Comment by danielbogart** [comment]
Would also like to know the status/plans regarding this issue.

**Comment by alyrik** [comment]
Faced the same issue (Angular 1.5, Material 1.0.1). Temporary hacked it with the fade-in css animation for the custom template container.

**Comment by alyrik** [comment]
To prevent seeing {{ value }} use ```ng-bind``` in your custom template instead of curly braces notation.
