### ISSUE TITLE
https://material.angularjs.org/latest/ throws exception

### ISSUE THREAD

**Issue by jgr3go** [angular/material#5114]
Current material.angularjs.org redirects to /latest which throws an exception when loading such that the whole page doesn't work. 

Console output:  
`angular.js:11379 Uncaught TypeError: Cannot read property 'replace' of undefined`

https://material.angularjs.org/0.11.3/ works fine.

**Comment by JSlifierz** [comment]
+1

**Comment by ThomasBurleson** [comment]
We have switched to HTML5 mode for our Online Docs... this should be fixed soon.

**Comment by jelbourn** [comment]
This issue is actually already fixed. There's a _different_ issue preventing people from getting to `layout/` pages.
