### ISSUE TITLE
"Page Not Found" In Layout Pages on Website

### ISSUE THREAD

**Issue by FlipOneDev** [angular/material#5117]
Selecting any item under the "Layout" section on the side navigation results in a "Page Not Found" message. See attached screenshot.
![material angularjs org-page-not-found](https://cloud.githubusercontent.com/assets/12635542/10437473/42972c6a-70e2-11e5-944d-20b46a1ce288.png)

**Comment by ThomasBurleson** [comment]
What URL are you visiting and seeing this issue?

> Can you confirm the issue still exists with our doc versions ? I will reopen if needed.
