### ISSUE TITLE
(feat) drop down button

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5118]
https://angular-ui.github.io/bootstrap/#/dropdown

**Comment by 0101adm** [comment]
specifically a split button w/ a menu.

**Comment by houmark** [comment]
@0101adm Did you take a look at https://material.angularjs.org/HEAD/demo/menu which can do most of what the bootstrap dropdown can do.

Alternatively https://material.angularjs.org/HEAD/demo/menuBar can be useful maybe?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
