### ISSUE TITLE
Overlapping cascading menu items

### ISSUE THREAD

**Issue by chrisconover** [angular/material#5119]
I'm attempting to create a cascading dropdown menu using <md-menu-bar>, <md-menu>, <md-menu-content>, and <md-menu-item>. As the user hovers over options, the menus overlap on each other.

<img width="349" alt="screen shot 2015-10-12 at 1 30 40 pm" src="https://cloud.githubusercontent.com/assets/694311/10437950/745b9cce-70e5-11e5-8179-da801b747cab.png">

Screen recording: https://drive.google.com/a/google.com/file/d/0B7VTbsvs9COJRnVCNWZKNjhKd28/view

Example:
http://codepen.io/chrisconover/pen/wKqpKg

**Comment by rschmukler** [comment]
Per this image in the spec, this is the intended behavior:

[!spec image](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7dlkwTUdncmtTTXM/components_menus_usage7.png)

I'd recommend setting the `width` attribute to make them not stack so perfectly.

**Comment by chrisconover** [comment]
The spec image shows a menu item selected and its child selected which reveals more options. I agree, that image looks fine.

If you look at my example, you'll notice child menus of "Foo" and "Bar" (siblings) overlap each other. This is not working as intended. When a user hovers off of a menu selection any of its submenus should close. In my example above, I hover off of "Foo" and onto "Bar", but the child menu of "Foo" doesn't close.

**Comment by chrisconover** [comment]
Any thoughts @rschmukler?

**Comment by EladBezalel** [comment]
@rschmukler i'm seeing this also, Foo and Bar gets both selected and opened.

**Comment by rschmukler** [comment]
Ah sorry, I mis-read the issue. Will take a look

**Comment by chrisconover** [comment]
Thanks @rschmukler. Any thoughts? Happy to do a video call/screen share if it would help clarify things.

**Comment by matthiasg** [comment]
we have the same issue .. the main thing seems to be that the sub menus dont really open on hover as on the demo site and they also dont close when moving on ... thus the sub menus stay open and overlap

**Comment by rschmukler** [comment]
Looking into this now. @chrisconover one thing I notice is the use of `mouseover` and `mouseleave` - those are unnecessary with `md-menu-bar` and likely are causing some of the problems. [Here](http://codepen.io/rschmukler/pen/MaqjOz) is one with `ng-click` instead. The issue still persists, but it's closer to proper behavior. Hope to have a fix in today.

**Comment by DevVersion** [comment]
That's the newest js build with the fix.
But I don't know, I think its still overlapping

http://codepen.io/DevVersion/pen/YyJYKb?editors=101
