### ISSUE TITLE
(bug) fab speed dial

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5121]
might be against spec...

if fab is positioned relative to container, fab action button (even though hidden) width takes up space.  seems they need to be absolutely positioned.

![untitled screencast](https://cloud.githubusercontent.com/assets/5133412/10438532/5d30615e-70f1-11e5-8ba6-c09a5db0f3a7.gif)

**Comment by topherfangio** [comment]
Can you please provide a codepen that shows the issue?

**Comment by 0101adm** [comment]
this seems to have resolved in Rc 2
