### ISSUE TITLE
(feat) md-fab-speed-dial - on open

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5125]
ability to know when fab opens and closes.  probably trigger when animation finishes.

**Comment by topherfangio** [comment]
You can use the `md-is-open` attribute, but it is immediate and not dependent upon animation. Do you need something based on the animation?

**Comment by 0101adm** [comment]
would be nice to time with other animations.

**Comment by topherfangio** [comment]
Bumping to post 1.0 so that we have more time to discuss how this should be done on a component-wide scale.

**Comment by 0101adm** [comment]
:+1:
