### ISSUE TITLE
md-autocomplete: support custom buttons within input

### ISSUE THREAD

**Issue by dg1202** [angular/material#5126]
Understand this would be very low on priority, maybe something for a PR!

I am making a maps application, and using the autocomplete very similar to the implementation on [google maps](https://maps.google.com) as a search. 

It would be great if I could embed a couple of buttons in the actual search, similar to google maps:  

### Google Maps  
<img width="420" alt="screen shot 2015-10-12 at 6 57 07 pm" src="https://cloud.githubusercontent.com/assets/2365581/10442024/8bc36836-7114-11e5-85f4-29645c2da821.png">
   
  
### My App  
<img width="394" alt="screen shot 2015-10-12 at 7 06 50 pm" src="https://cloud.githubusercontent.com/assets/2365581/10442053/95c9dd24-7114-11e5-8d2a-d39df3239be6.png">
  
  
Allowing the search to have configurable buttons could also resolve similar request, like #4841

**Comment by smilovanovic** [comment]
+1

Maybe even custom button in the footer of results dropdown, user should be able to pass button label and function that should be trigger on ng-click

**Comment by dg1202** [comment]
1.0-rc3?! Sick.

**Comment by dg1202** [comment]
post-1.0. 

Still, sick!

**Comment by dg1202** [comment]
for anyone looking for a similar solution, I did a workaround by altering a little css for the border lines and wrapping it in a whiteframe.

<img width="429" alt="screen shot 2016-05-04 at 10 17 23 am" src="https://cloud.githubusercontent.com/assets/2365581/15018967/8b85dbf6-11e1-11e6-8f67-8663c61048d5.png">


<img width="454" alt="screen shot 2016-05-04 at 10 17 36 am" src="https://cloud.githubusercontent.com/assets/2365581/15018974/91473eae-11e1-11e6-9788-9547416a6894.png">
