### ISSUE TITLE
Theming no longer present on Button Demo

### ISSUE THREAD

**Issue by SomethingNew71** [angular/material#5127]
None of the colors are presenting themselves on the demo page for the buttons
<img width="1196" alt="screen shot 2015-10-12 at 9 10 32 pm" src="https://cloud.githubusercontent.com/assets/4572799/10442968/cc9a3932-7125-11e5-902a-fce3b763756f.png">

**Comment by ThomasBurleson** [comment]
Fixed in https://material.angularjs.org/0.11.3/demo/button
