### ISSUE TITLE
Autocomplete doesn't render properly

### ISSUE THREAD

**Issue by halayli** [angular/material#5131]
Using 0.11.3. This is exhibited on Safari 9.0 and Chrome 45

<img width="874" alt="screen shot 2015-10-13 at 12 19 44 am" src="https://cloud.githubusercontent.com/assets/125592/10448216/2c7bdfa8-7140-11e5-86bf-4cfb04dcb394.png">

**Comment by ThomasBurleson** [comment]
If you navigate to https://material.angularjs.org/0.11.3/demo/autocomplete, then everything appears to be working correctly. Currently we have an issue that `https://material.angularjs.org/latest/` !==  `https://material.angularjs.org/0.11.3/`. We are investigating.

**Comment by halayli** [comment]
Ah got it. Yep going directly or selecting latest works. Navigating from root landing to autocomplete is broken. Thanks for the quick response.

**Comment by robertmesserle** [comment]
This is resolved in 0.11.4
