### ISSUE TITLE
md-autocomplete should allow custom result height 

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#5132]
Currently I can't find a way to target a specific `md-autocomplete-suggestions-container`/`md-virtual-repeat-container` in order to set a custom height for the result list.

`md-autocomplete` should set the `md-menu-class` or something else on the container so it can be targeted by CSS rules.

**Comment by cssensei** [comment]
Maybe it would be better to add support for `md-auto-shrink` & `md-auto-shrink-min` parameters directly on `md-autocomplete` directive.

**Comment by elubin** [comment]
FYI, you are correct, I couldn't find a way to set height.... but for reference, this ticket is how you can set WIDTH

https://github.com/angular/material/issues/4772

**Comment by peterkjang** [comment]
Exactly what I'm looking for.  The hardcoded height limit to only show up-to 5 items is really limiting.

**Comment by Unasbj** [comment]
+1

**Comment by sroyqci** [comment]
+1

**Comment by oreyan** [comment]
+1

**Comment by macdasi** [comment]
+1

**Comment by gabguy** [comment]
+1

**Comment by muhengseow** [comment]
As a workaround I am able to resize the suggestion box by overriding the CSS:

```
.md-virtual-repeat-container.md-autocomplete-suggestions-container {
    height: 420px;
    max-height: 420px !important;
}
```

**Comment by kuhnroyal** [comment]
@muhengseow Yes, but that only works if you have just one of those.

**Comment by Fl4m3Ph03n1x** [comment]
+1

**Comment by Gimmeaphatbeat** [comment]
+1

**Comment by Gimmeaphatbeat** [comment]
This makes the solution from @muhengseow slightly more generic, if you want a 'full height' solution.

```
.md-virtual-repeat-container.md-autocomplete-suggestions-container {
    height: calc(100% - 100px);
    max-height: calc(100% - 100px) !important;
}
```

**Comment by maheshk172** [comment]
But this will be applicable for all the autocomplete inside the application.  Can we write some kind of wrapper class on top of this 

e.g. 
.custom-app-wrapper .md-virtual-repeat-container.md-autocomplete-suggestions-container {
    position: fixed;
    bottom: 50px !important;
    height: initial !important;
    max-height: 99999999px !important;
}

I tried it but somehow the generated List is not generated inside the same element, it is a virtual list somewhere at bottom of DOM tree.  

Can anybody suggest any way to achieve this ?

**Comment by celeguzQM** [comment]
+1

**Comment by askucher** [comment]
+1

**Comment by begemott** [comment]
+1

**Comment by ed4becky** [comment]
I was using Gimmeaphatbeat solution, but found that the drop down nop longer displayed if there wasn't enough space at the bottom for the full height.

I would also like a solution like maheshk172's

**Comment by Nickproger** [comment]
+1

**Comment by rodrigo-martins** [comment]
ADD md-dropdown-items
The default is 5. 
md-dropdown-items = "7"
