### ISSUE TITLE
[feature] DOM validator

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#5133]
As bootstrap is having a bootlint, a ngmdlint would definitely be interesting :)

**Comment by ThomasBurleson** [comment]
@Wardormeur - we would welcome a Pull Request for this.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
