### ISSUE TITLE
input/select: Too dark when on dark toolbars

### ISSUE THREAD

**Issue by epelc** [angular/material#5136]
inputs and selects are way too dark when on a dark toolbar. You can hardly see what you are typing and it's very hard to see the bottom line. Perhaps there should be an option to invert the colors of the input/select when it's on a dark toolbar or just make them white.

Example
![image](https://cloud.githubusercontent.com/assets/5204642/10461085/a39bf586-71a5-11e5-9a45-e9ecb39a0dd1.png)

**Comment by ThomasBurleson** [comment]
@rschmukler - is this related to recent theme changes?

**Comment by rschmukler** [comment]
Reference #5868 to confirm this is resolved
