### ISSUE TITLE
Documentation Getting Started Left Menu Bar Link Broken

### ISSUE THREAD

**Issue by bseay** [angular/material#5137]
The "Getting Started" link in the left menu bar of the main documentation website does not work.

*Reproduce:*
- Navigate to https://material.angularjs.org/
- You are redirected to https://material.angularjs.org/latest/
- Click "Getting Started" in the left menu bar

*Result:*
- Url is https://material.angularjs.org/getting-started
- 404 Page Not Found

*Expected:*
- Correct url is https://material.angularjs.org/latest/getting-started

**Comment by ThomasBurleson** [comment]
@robertmesserle - FYI.

**Comment by jelbourn** [comment]
@ThomasBurleson I already fixed this on master. It will get taken care of automatically when we release 0.11.4 for `latest/` and I can manually fix `0.11.3`.

**Comment by ThomasBurleson** [comment]
Fixed with SAH https://github.com/angular/material/tree/v0.11.4
