### ISSUE TITLE
Focused inputs with errors don't highlight label and line in red until the second time receiving focus

### ISSUE THREAD

**Issue by joeyperson** [angular/material#5140]
When using the demo section for [input errors](https://material.angularjs.org/latest/demo/input), the first time I focus on an element, it inherits the "normal" ink color, which is incorrect. The [spec indicates](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3ZjlmVGoyUVJOOVk/patterns_errors_userinput17.png) that when an error appears, both the label and underline are activated with red. So when an error appears, the input would never use the default ink unless the error was resolved. 

In the angular demo, it's only after focusing on an input with error twice does the expected behavior occur.

**Comment by EladBezalel** [comment]
I don't think an error should appear if there's no value and it's not touched.

@joeyperson what your'e asking Is an easy fix, is it the right behavior?
