### ISSUE TITLE
[bug] Datepicker 11.3

### ISSUE THREAD

**Issue by HBO2** [angular/material#5141]
https://github.com/angular/material/issues/5116

Something realy strange is going on. The link mentioned in 5116 is indeed going to a datepicker with a solid background, but pulling the release is not and when switching on the website from demo to demo it's simply a datepicker with a transparant background. 

I hope you don't mind but this issue is not solved on chrome and firefox on the mac. The screenshot is note fake and comming directly from the latest version of website 11.3. And 11.4.
Hope you will take the issue seriously.

**Comment by celrenheit** [comment]
Same thing is happening for me for 0.11.4:
![angular-material-bug](https://cloud.githubusercontent.com/assets/671040/10482922/62751312-727c-11e5-98ab-b1b05acf8d90.png)

For 0.11.3, the version on the website seems to work correctly.

**Comment by ThomasBurleson** [comment]
@jelbourn - ping.
