### ISSUE TITLE
md-select closes automatically when clicked in iOS Simulator

### ISSUE THREAD

**Issue by marceloluissantosit** [angular/material#5143]
Hello, people!

I am having a problem with md-select in a simple project using Cordova and testing in iOS Simulator. When I click to open the md-select, it closes automatically. It appears to be firing the event to select an item when it is opened. I uploaded the sample in the link bellow to the issue and the problem only happen with iOS. I tested in Android and it works nicely.

https://www.dropbox.com/s/ri7hr7f0jp0rfho/TestSpinner.zip?dl=0

Do you have some idea to solve this problem?

Thanks.

Marcelo Santos

**Comment by barryvdh** [comment]
Related: #4757, #4296

**Comment by marceloluissantosit** [comment]
barryvdh thank you by the information. I will subscribe notification about the other issues. I would ask you if you get a solution, post here, please.

Thank you again!

Marcelo Santos

**Comment by barryvdh** [comment]
Shoud be fixed with https://github.com/angular/material/commit/7251684315bcc65fcd7599ac88f84dcf51a2a219

**Comment by rschmukler** [comment]
Indeed this was fixed in the commit referenced above.
