### ISSUE TITLE
md-tabs: Colors are broken on demo site

### ISSUE THREAD

**Issue by amritk** [angular/material#5144]
They are broken in the latest iteration:
https://material.angularjs.org/0.11.4/demo/tabs
And in head:
https://material.angularjs.org/HEAD/demo/tabs
![screen shot 2015-10-13 at 5 40 34 pm](https://cloud.githubusercontent.com/assets/2039539/10472117/b04f06de-71d1-11e5-83bc-8bb8b9b8617e.png)
Tested on OSX chrome 46.0.2490.71 (64-bit)

**Comment by houmark** [comment]
Can confirm this also happens within our app so this seems to be related to some of the theme based changes done recently.

**Comment by Stamy** [comment]
Noticed same issue as well. Chrome OSx.

**Comment by websirnik** [comment]
+1. Introduced in 0.11.4.

**Comment by dohomi** [comment]
+1 after 0.11.4 update

**Comment by ThomasBurleson** [comment]
We are aware of this and will fix today on master.

**Comment by rschmukler** [comment]
Fixed.
