### ISSUE TITLE
failed to load angular-material.min.js in browser

### ISSUE THREAD

**Issue by loganfreeman** [angular/material#5146]
Uncaught SyntaxError: missing ) after argument list

Follow the instructions here:
[Instructions](https://github.com/angular/material/blob/master/docs/README.md#docs)
# Build & deploy docs to `dist/docs`
gulp docs

# Watch source dirs for changes and rebuild
gulp watch

# Use the built-in gulp server with live reload
gulp server

# Alternatively, install httpster globally; if not already installed
npm install -g httpster

# And then launch the webserver
# NOTE: unlike `gulp server` this will not auto-reload the HTML
httpster -p 8080 -d ./dist/docs

**Comment by ThomasBurleson** [comment]
@jelbourn, @robertmesserle - thoughts ?

**Comment by jelbourn** [comment]
@ThomasBurleson Something is off with doing this particular configuration, but doing `gulp watch site` works fine, so I'd say this is a lower priority issue.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
