### ISSUE TITLE
ng-messages animation jump issue

### ISSUE THREAD

**Issue by romanchak** [angular/material#5147]
Take a look at "Top Secret Project" > "Client Email" official example:
https://material.angularjs.org/HEAD/demo/input

Type "thatsmyname@gmail.c", then remove last character.
Error message will appear fully then disappear again and then animation will start.

Issue doesn't reproduce vice versa: in case if you already see the error and then pass the validation.
"thatsmyname@gmail." > "thatsmyname@gmail.c"

**Comment by topherfangio** [comment]
I believe this is a duplicate of https://github.com/angular/angular.js/issues/12969

**Comment by ivanzvakoms** [comment]
confirm it when use ```md-auto-hide="false"```

**Comment by EladBezalel** [comment]
@topherfangio do you mind that this issue? i think you're the most related person to this issue right now

**Comment by ThomasBurleson** [comment]
Duplicate
