### ISSUE TITLE
Tab headers visualization issues in 0.11.4

### ISSUE THREAD

**Issue by Lorthirk** [angular/material#5155]
Hello. It seems that 0.11.4 broke something with tab headers: as you can see even in the demo page for tabs, tab headers are rendered as white on white now:

![](https://files.gitter.im/angular/material/AD8K/angular-0.11.4.png)

while they were correctly shown according to the theme in 0.11.3:

![](https://files.gitter.im/angular/material/LDG5/angular-0.11.3.png)

I am aware of the breaking change in 0.11.4 about md-theme="default" to be added at ng-app level; however, adding this directive not only doesn't fix the issue, but presents a lot of other artifacts.

without explicit md-theme="default":

![without](https://cloud.githubusercontent.com/assets/8140139/10483829/af8f25d4-7281-11e5-9ab6-9d4eb5cd617d.PNG)

with explicit md-theme="default":

![with](https://cloud.githubusercontent.com/assets/8140139/10483845/c653a5ec-7281-11e5-8647-629cfcb967cd.PNG)

**Comment by ThomasBurleson** [comment]
@rschmukler - you loving life ?

**Comment by bvilches** [comment]
It's being a mess for me too XD

+1

**Comment by rschmukler** [comment]
This will be fixed by #5164
