### ISSUE TITLE
Layout child items with flex of specific size no longer have padding

### ISSUE THREAD

**Issue by sbondor** [angular/material#5156]
The child div in the following code no longer has padding. Only layout div has padding.
```
<div layout="row" layout-padding>
        <div flex="95">Parent layout and this element have padding.</div>
</div>
```
Not sure if it's bug or misuse.

**Comment by wsfriday-sfd** [comment]
I am experiencing this as well.

It looks like the flex="95" attribute is being turned into the class flex-95 correctly, but the base class of flex is no longer being applied to the element, and causing the layout-padding and layout-margin options to not apply to the child elements.

A quick fix is either adding the flex class manually to the child elements, or add some extra CSS to apply the padding correctly to the different flex elements.

Example:

.layout-padding > .flex-95 { padding:8px; }

**Comment by ThomasBurleson** [comment]
Fixed.
