### ISSUE TITLE
md-datepicker should have a background-color

### ISSUE THREAD

**Issue by viniciusdacal** [angular/material#5168]
![captura de tela 2015-10-14 as 16 04 04](https://cloud.githubusercontent.com/assets/2660570/10494598/94777d12-728d-11e5-939a-eb48ecd723d1.png)

As you can see in the image above, md-datepicker doesn't have a background-color.
For the user, it seems the interface is broken.

**Comment by ThomasBurleson** [comment]
Fixed with SHA f20a635424d35d9207226a310248492be6975d3c

**Comment by viniciusdacal** [comment]
Thanks @ThomasBurleson :smile:

**Comment by ThomasBurleson** [comment]
We have a better fix also coming soon.
