### ISSUE TITLE
The md-toolbar in a md-dialog still got the "md-default-theme" class in 0.11.4

### ISSUE THREAD

**Issue by dennislaupman** [angular/material#5169]

**Comment by hkjels** [comment]
I can confirm that this is an issue. I've solved it by passing the theme as a local, but it should not be necessary.

**Comment by DevVersion** [comment]
That seems to be a duplicate of #5899 and should be fixed in #7154. Would be great if you close your issue, because it's a duplicate.

**Comment by DevVersion** [comment]
Fixed with SHA a653122cadf5feba15ca6da8fb876098997892dc
