### ISSUE TITLE
mdTooltip problem inside mdFabToolbar

### ISSUE THREAD

**Issue by rafaelgondim** [angular/material#5171]
Same problem described in issue #3277 has reappeared on version 0.11.4
![mdfabtoolbar_mdtooltip](https://cloud.githubusercontent.com/assets/1655457/10497549/d1e842b2-729c-11e5-809d-a1cf585e96de.gif)

**Comment by ThomasBurleson** [comment]
@topher - can you add tooltips to our FAB Toolbar?

**Comment by SanderElias** [comment]
Duplicate/related to #5124. Closed to concentrate discussion over there.
