### ISSUE TITLE
Angular Material and SVG <stop>'s offset attribute are not playing well

### ISSUE THREAD

**Issue by vovafeldman** [angular/material#5174]
I have configured the following mask in SVG element:

```html
<mask id="mask" maskUnits="userSpaceOnUse" maskContentUnits="userSpaceOnUse">
    <linearGradient id="linearGradient" gradientUnits="objectBoundingBox" x2="0" y2="1">
        <stop stop-color="white" stop-opacity="0" offset="0%"/>
        <stop stop-color="white" stop-opacity="1" offset="30%"/>
        <stop stop-color="white" stop-opacity="1" offset="70%"/>
        <stop stop-color="white" stop-opacity="0" offset="100%"/>
    </linearGradient>
    <rect width="100%" height="100%" fill="url(#linearGradient)"/>
</mask>
```
When angular is loaded, I get the following error in Chrome (didn't try other browsers):
`Error: Invalid value for <stop> attribute offset=""`

After some debugging of the stack trace, I found that the method `attributeValueToClass` decided that `offset` is a deprecated attribute of the element, and get rid of the attribute by running:
```javascript
if ( $$mdLayout.removeAttributes ) element.removeAttr(className);
```

And when jQuery removes the attribute the error is thrown.

Here's the stack:
```
jQuery.extend.removeAttr	@	vendor.js?v=2.1.6:7022
(anonymous function)	@	vendor.js?v=2.1.6:6953
jQuery.extend.each	@	vendor.js?v=2.1.6:374
jQuery.fn.jQuery.each	@	vendor.js?v=2.1.6:139
jQuery.fn.extend.removeAttr	@	vendor.js?v=2.1.6:6952
attributeValueToClass	@	vendor.js?v=2.1.6:53436
_$interpolate_.compile	@	vendor.js?v=2.1.6:53411
applyDirectivesToNode	@	vendor.js?v=2.1.6:17271
compileNodes	@	vendor.js?v=2.1.6:16800
compileNodes	@	vendor.js?v=2.1.6:16812
compileNodes	@	vendor.js?v=2.1.6:16812
compileNodes	@	vendor.js?v=2.1.6:16812
compileNodes	@	vendor.js?v=2.1.6:16812
compileNodes	@	vendor.js?v=2.1.6:16812
compileNodes	@	vendor.js?v=2.1.6:16812
compileNodes	@	vendor.js?v=2.1.6:16812
compile	@	vendor.js?v=2.1.6:16707
(anonymous function)	@	vendor.js?v=2.1.6:10873
parent.$get.Scope.$eval	@	vendor.js?v=2.1.6:25133
parent.$get.Scope.$apply	@	vendor.js?v=2.1.6:25233
bootstrapApply	@	vendor.js?v=2.1.6:10871
invoke	@	vendor.js?v=2.1.6:13687
doBootstrap	@	vendor.js?v=2.1.6:10869
bootstrap	@	vendor.js?v=2.1.6:10889
angularInit	@	vendor.js?v=2.1.6:10783
(anonymous function)	@	vendor.js?v=2.1.6:38032
jQuery.Callbacks.fire	@	vendor.js?v=2.1.6:3099
jQuery.Callbacks.self.fireWith	@	vendor.js?v=2.1.6:3211
jQuery.extend.ready	@	vendor.js?v=2.1.6:3417
completed	@	vendor.js?v=2.1.6:3433
```

**Comment by vovafeldman** [comment]
Commenting:
```javascript
.directive('offset'              , attributeWithObserve('offset')              )
```
in `material.core.layout` module resolved the problem, but I guess it will break the `offset` directive.

**Comment by ThomasBurleson** [comment]
https://github.com/angular/material/commit/af45a22d25de1fb8c00e2d16f9070e930a45c8ad

Have you tried with the current code in 0.11.4 or master ?

To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by vovafeldman** [comment]
Just confirming that I tested with the master and it works :+1: Next time I won't make the same mistake. Thanks!

**Comment by ThomasBurleson** [comment]
@vovafeldman - no worries. glad to see you using Angular Material.
