### ISSUE TITLE
Autocomplete with floating-label: incorrect search result window position

### ISSUE THREAD

**Issue by sbondor** [angular/material#5176]
I have an autocomplete component with a floating label. The autocomplete is defined within the template of a angular directive, like this:
```
.directive('someDirectiveName', function () {
      return {
        restrict: 'E',
        controller: Ctroller,
        controllerAs: 'ctrl',
        templateUrl: 'somepath/buggyDirective.html'
      };
```
The space seems to come from the input container bottom padding. 
It works with material 0.10.x.

![autocomplete](https://cloud.githubusercontent.com/assets/7798321/10509209/3a1ca00c-7334-11e5-9180-e3c584605aa0.png)

**Comment by robertmesserle** [comment]
This has been resolved.
