### ISSUE TITLE
Ripple for list items with ng-click often has rounded corners

### ISSUE THREAD

**Issue by lyschoening** [angular/material#5177]
Ripple effects for ng-click on list items now sometimes have rounded corners. They should have straight corners and fill the entire row. You can see this for instance in the [List demo](https://material.angularjs.org/0.11.4/demo/list) under headings "Clickable Items with Secondary Controls" and "Avatar with Secondary Action Icon". 

The issue must have been introduced in 0.11.0 as the 0.10.1 demo still has ripple effects with regular edges for list items under these headings.

![ripple bug](https://cloud.githubusercontent.com/assets/74085/10509733/0eb2f542-732f-11e5-9932-43277c4132a1.png)

**Comment by lyschoening** [comment]
With the fix for #2131, it is now possible to use `ui-sref` again. When using `ui-sref` instead of `ng-click`, the same issue (rounded corners on ripple) occurs, but there is also an 8px margin around the ripple.

**Comment by Supratentorial** [comment]
I don't think a7fc111 fixes the issue with the 8px margin around the ripple when using ui-sref? Should I open a new issue for this?

**Comment by lyschoening** [comment]
@Supratentorial I'd appreciate it.

**Comment by Supratentorial** [comment]
@lyschoening I suspect that #5608 is alluding to this issue, although, lacks detail.
