### ISSUE TITLE
[Information request] - How to close md-sidenav

### ISSUE THREAD

**Issue by murdockcrc** [angular/material#5179]
We are using a `md-sidenav` for navigation, which is opened on wider screen, like this:

```
  <md-sidenav id="sidenav-left" md-component-id="sidenav-left" class="md-sidenav-left navbar-side" md-is-locked-open="$mdMedia('gt-md')">
    {{> sidenav}}
  </md-sidenav>
```

Here are some pages, however, where we want the sidenav to collapse, since we want the content to take complete priority on the screen. On reading the documentation [here](https://material.angularjs.org/latest/api/service/$mdSidenav), it says:

> // Sync check to whether given sidenav is locked open
> // If this is true, the sidenav will be open regardless of close()

Do I understand this correctly, that it is not possible to programmatically collapse an sidenav when it is defined with `md-is-locked-open`? If so, how can we replicate this behaviour?

**Comment by cranesandcaff** [comment]
Try 

      <md-sidenav id="sidenav-left" md-component-id="sidenav-left" class="md-sidenav-left navbar-side" md-is-locked-open="yourViewModel.lockThatSideBar">
        {{> sidenav}}
      </md-sidenav>

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
