### ISSUE TITLE
md-tab doesn't detect bodyless tab

### ISSUE THREAD

**Issue by romanchak** [angular/material#5181]
Its related to the changes in this commit:
https://github.com/angular/material/commit/054c066b74bf3face1a7a3a50068478bd7140e95

In case if element has md-tab-label directive it won't detach transcluded content into md-tab-body anymore. 

Anyway, if you guys decided to change that logic so content now must be wrapped always with md-tab-body, then you should update the docs as well.
https://github.com/angular/material/blob/master/src/components/tabs/js/tabDirective.js#L18

**Comment by robertmesserle** [comment]
Ah, this is a documentation error.  This should have been changed a long time ago.

**Comment by robertmesserle** [comment]
Actually, this is explained in the documentation directly above the part you referenced:

https://github.com/angular/material/blob/master/src/components/tabs/js/tabDirective.js#L15
