### ISSUE TITLE
Feature request: md-autocomplete custom template for items grouped by type

### ISSUE THREAD

**Issue by cssensei** [angular/material#5182]
Is there any way to use custom templates and group the matched results by a specific `type` property (like in the image bellow)? If this is not possible now, can we please add on the feature request list?
![image](https://cloud.githubusercontent.com/assets/1344020/10515337/43695258-7353-11e5-963b-d8d362557641.png)

**Comment by rcastan** [comment]
I am very interested by this feature for my project and
I would like to know if this feature will be quickly taken into account or if it's not priority for the moment.
Thanks

**Comment by alois-wever** [comment]
+1

**Comment by jojogeyer** [comment]
+1

**Comment by nikitakuz** [comment]
+1

**Comment by danpaulsmith** [comment]
+1

**Comment by tleluc** [comment]
+1

**Comment by hscanlan** [comment]
+1

**Comment by samithaf** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by eduardodallmann** [comment]
+1
