### ISSUE TITLE
Some kind of error related to modals opening/closing while other models exist

### ISSUE THREAD

**Issue by uriva** [angular/material#5184]
Since 0.11.2 (or 0.11.1) stumbling the following error while opening and closing modals. End result is that "done" button is clickable but has no effect and the modal remains. Cannot reproduce at this time.

    Uncaught TypeError: Cannot read property '$$ngAnimateParentKey' of null

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by deltaepsilon** [comment]
I found the same issue, but it appeared to be a result of caching during an upgrade from angular-material 10.1. I fixed it by putting a breakpoint on the offending line in angular-animate.js and setting it to be conditional on ```!parentNode```. The act of setting the breakpoint appears to have fixed the issue and my sidenav animations work again.
