### ISSUE TITLE
md-menu hiding on checkbox change

### ISSUE THREAD

**Issue by l-liava-l** [angular/material#5185]
Hi! 
I want to use the 'md-menu' like popup for configuring an elements in graph editor.
But click on checkbox leads to hiding the menu.  Do you can make the *native* option for canceling this behaviour?

![_094](https://cloud.githubusercontent.com/assets/3027593/10518536/97a50170-736a-11e5-95e7-688ca6716c53.png)

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions AND provide a CodePEn?

**Comment by topherfangio** [comment]
We really need a Codepen to work on this issue. If you can provide it, I will reopen.
