### ISSUE TITLE
ng-cloak not working with md-autocomplete

### ISSUE THREAD

**Issue by blootch** [angular/material#5188]
Slow motion gif (it only happens at the first click, to reproduce refresh the page and click again) : 
![ezgif-3858551348](https://cloud.githubusercontent.com/assets/6443098/10520304/cf1e745c-7369-11e5-9077-e2478d1cd9f5.gif)

Normal speed gif : 
![telechargement](https://cloud.githubusercontent.com/assets/6443098/10520337/e84f75fc-7369-11e5-9fdb-d3af5206a2a6.gif)

**Comment by ThomasBurleson** [comment]
Ah HAH!  There it is. Thx @blootch. We will investigate...

**Comment by robertmesserle** [comment]
@kseamon As far as I can tell, this is related to Virtual Repeater.  Can you take a look?

**Comment by kseamon** [comment]
The repeater does some stuff asynchronously at startup. Is this talking about an autocomplete inside of ng-cloak or row item templates containing ng-cloak?

**Comment by robertmesserle** [comment]
So basically what happens on the first focus:
- the DOM element is shown via `ng-show`
- the matches array is populated with a list of items to display

However, we see a flicker of the templates showing `{{item.display}}`

**Comment by robertmesserle** [comment]
@kseamon Assigning to you for now.  Please kick back to me if it isn't fixable within virtual repeater.

**Comment by NicolasBlois** [comment]
This issue will probably give you headache.
One solution is to defered the display of items related to ngCloak directive after the controller has initialized the scope, so in postlink phase.

**Comment by NicolasBlois** [comment]
<code>module.directive("defCloak", function () {
    return {
        restrict: 'A',
        link: function (scope, element, attrs) {       
            attrs.$set("defCloak", undefined);
            element.removeClass("def-cloak");
        }
    };
});</code>
css
<code>[def-cloak], [data-def-cloak], [x-def-cloak], .def-cloak {
    display: none;
}</code>
html
<code><div data-def-cloak>blabla</div></code>

**Comment by kseamon** [comment]
Looks like this issue A) has nothing to do with ng-cloak, and B) only a bit to do with virtual-repeat.

The real problem is MdAutocompleteItemScopeDirective. Thus far, commenting it out fixes the issue. I'll try to fix it, but do we really even need it @robertmesserle ?

**Comment by robertmesserle** [comment]
@kseamon I'll sync up with @topherfangio to figure out what we can do about this - I thought I checked that, but apparently I missed something.  Reassigning to me.

**Comment by kseamon** [comment]
Have a look at #5637

**Comment by NicolasBlois** [comment]
My stupid proposal does not work on this issue :dash:

**Comment by kseamon** [comment]
@robertmesserle Any reason for the milestone delay? My PR that fixes this has been pending for a week or two now.
