### ISSUE TITLE
Scroll the screen and Tabs no longer work

### ISSUE THREAD

**Issue by Valks** [angular/material#519]
Looking at the examples at: https://material.angularjs.org/#/demo/material.components.tabs

The tabs work fine but when I scroll down the screen the mouse pointer no longer shows the hand and you can no longer click on the tabs to activate them (keyboard works). Also no longer works using touch via tablet.

Scroll back to the top of the screen and they work as expected.

Using IE 11 both metro and desktop mode.

Don't have other browsers installed to test further.

**Comment by ajoslin** [comment]
This is no longer a problem.
