### ISSUE TITLE
Problem on Closing $mdDialog 

### ISSUE THREAD

**Issue by deevorak** [angular/material#5192]
After I updated my project to 0.11.4 version I got a problem on trying to hide a modal by clicking on a confirm button inside a $mdToast action. The action is performed but the modal is not hidden as supposed to be. The code works on version 0.11.3

code like this:
```javascript
var toast = $mdToast.simple()
	          .content(mensagem)
	          .theme('info-toast')
	          .action('OK')
	          .highlightAction(false)
	          .position('top right')
	          .hideDelay(false)
	          .parent(angular.element('form[name=enderecoForm]'));
			
$mdToast.show(toast).then(function(response) {
	if (response == 'ok') {
		$mdDialog.hide();
         }
});
```

**Comment by Splaktar** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ?

**Comment by deevorak** [comment]
The issue is still happening on version 1.0.0-RC1 angular material. Tested with angular 1.4.7

Steps:
* Create a modal with shared scope.
```javascript
$mdDialog.show({
				controller: controllerName,
				templateUrl: viewName,
				scope : $scope,
				preserveScope : true,
				targetEvent: ev
			});
```

* Inside modal's controller create a toast action that performs modal closing (fired on close button ng-click - like a confirmation that modal will be closed)

```javascript
var toast = $mdToast.simple()
              .content(mensagem)
              .theme('info-toast')
              .action('OK')
              .highlightAction(false)
              .position('top right')
              .hideDelay(false)
              .parent(angular.element('form[name=enderecoForm]'));

$mdToast.show(toast).then(function(response) {
    if (response == 'ok') {
        $mdDialog.hide();
         }
});
```
* Clicking on Toast action will result:  Modal will remain oppened instead of being hide.

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate more.

**Comment by topherfangio** [comment]
Possibly related to #5195 ?

**Comment by EladBezalel** [comment]
@deevorak can you please check if it's still happening on master after #5195 has resolved
