### ISSUE TITLE
$mdToast increases watchers but does not remove them if multiple toasts are displayed within a digest.

### ISSUE THREAD

**Issue by robertbaker** [angular/material#5193]
This is kind of hard to explain, bare with me.

Using $mdToast, if you click  one of the buttons to display a toast, rapidly enough so the toast does not disappear between clicks (and multiple toasts are created within 1 digest cycle), it will increase the watcher count considerably but will not remove all of the watchers for all of the toasts.

$mdToast only decreases the watchers for the last toast created within a digest cycle.

Demo: http://codepen.io/anon/pen/avLPqP

**Comment by robertbaker** [comment]
@ThomasBurleson please review and Triage.

**Comment by samuelchristopher** [comment]
Hello @robertbaker. If your problem is that the toasts are not leaving then this should solve your problem.

```javascript
 var toast = $mdToast.simple()
            .content(message)
            .action(action)
            .highlightAction(false)
            .position('bottom left');
   setTimeout(function() {
      $mdToast.show(toast);
   }, 99); 
```
`

I encountered this problem before, where two events would trigger a toast and the second one would be left.

**Comment by robertbaker** [comment]
@samuelchristopher No that's not the issue, there is a watcher leak, nothing to do with the UI.

**Comment by nicky-lenaers** [comment]
I encountered this issue when calling this event two times as it gets triggered twice sometimes:
``$rootScope.$broadcast('http-error', res.data.message)``

and listening on it:
``$rootScope.$on('http-error', (event, message) => ToastService.simple(message));``

In this case, the toast simply does not go away.

**Comment by DevVersion** [comment]
This may be related to #6633, since multiple toasts are shown within the same interim element. When this bug is fixed, then the toasts will probably hide.

**Comment by robertbaker** [comment]
This bug is more about unattaching the events, disposing them so the number
of watchers does not increase when you display multiple toasts at the same
time, even if only one is visible.

If you open 5 toasts at the same time, the number of watchers increase but
only the last toast you opened will have the watchers removed once it
dismisses.

**Comment by DevVersion** [comment]
@robertbaker Exactly, and thats the problem of the current interim element stack. Because we are just trashing previous element in the stack. That means, no close execution -> no event cleanup.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by xplodwild** [comment]
Hitting this issue as well, has anyone got a workaround since it seems to be "deprecated"?
