### ISSUE TITLE
Nested md-content height with sidenav

### ISSUE THREAD

**Issue by orangesoup** [angular/material#5197]
Hey!

I made a simple example of my problem: http://codepen.io/anon/pen/qOPLJz
What I want is having `#mdContent2` filling up the whole area. Adding `layout-fill` to its parent would do the trick but then I would have a scrollbar for the whole page which I really don't want.

As I can see the red area fills up the space without the layout-fill tag perfectly. Is there any way to have the green area fill the red one?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
