### ISSUE TITLE
How to place an icon on left side of a button

### ISSUE THREAD

**Issue by diegoaguilar** [angular/material#5198]
I'm trying this way

```jade
md-button(flex='10' ui-sref='communities') Comunidades
	ng-md-icon(icon="people" style="fill:white" size="25")
```

But that places the icon on right side.

**Comment by RolandHeath** [comment]
This question is probably more suited to the [angular material forum](https://groups.google.com/forum/#!forum/ngmaterial). That being said, you could look into the left, right, margin, and padding css attributes.

**Comment by Splaktar** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ?

**Comment by programmist** [comment]
I agree with @RolandHeath.  This is really an question for the [angular material forum](https://groups.google.com/forum/#!forum/ngmaterial).  

If you do find a reproducible issue, please feel free to open a bug and include a codepen.io demo demonstrating the issue.  Thanks.
