### ISSUE TITLE
md-datepicker not showing up

### ISSUE THREAD

**Issue by morriq** [angular/material#5201]
Hi

please, check this out. http://jsfiddle.net/54mh0skf/

I have similar issue on my website, but there's no margin and it's wrong only on firefox.
This example above acts like my website on firefox.

**Comment by jelbourn** [comment]
@morriq I think you grabbed the version where some datepicker CSS was accidentally omitted from the build. Could you try again on the latest version?

**Comment by morriq** [comment]
Sure, I can with latest version.

Here you go: http://jsfiddle.net/54mh0skf/1/

material rc3, angular 1.5 beta 1
