### ISSUE TITLE
<md-menu>  is not opening all inner menu items in a drop down <md-menu-item>

### ISSUE THREAD

**Issue by ahmadalibaloch** [angular/material#5203]
Menu bar is not opening all inner menu items in a drop down menu. http://codepen.io/ahmadalibaloch/pen/avLeVQ
Check "File" menu in the above pen and hover over the "New" inner menus. It opens first "New" menu, not the second, and then third "New" menu. This odd number showing continues.

Its strange to me.

**Comment by rschmukler** [comment]
This has been fixed on master, thanks!
