### ISSUE TITLE
md-virtual-repeat-container can not be inserted inside a table

### ISSUE THREAD

**Issue by Sam-Davis** [angular/material#5204]
More of a feature request than an issue. The new md-virtual-repeat-container looks great, but I would like it to be extended for use with tables. 

I am able to use it with a table as follows: http://codepen.io/anon/pen/KdyPwe

However, if I want to fix the table headers above the scroll bar, then I am not able to do this:
http://codepen.io/anon/pen/bVYbGY

Currently, I find all the table directives for angular to be too slow. If this directive is compatible with table headers, then it would be very powerful.

**Comment by RolandHeath** [comment]
I don't know how to make this work with a table like yours, but working with the tools that angular material gives you can do wonders... Here's a modification of your codepen [example] (http://codepen.io/anon/pen/gaXBWW)

**Comment by Sam-Davis** [comment]
Yes thanks, yes this works nicely.

**Comment by kseamon** [comment]
Looks like this is resolved.

**Comment by jascination** [comment]
This solution doesn't actually work when tables have data with different-lengthed values in them. Codepen example: http://codepen.io/anon/pen/jWLJKK

I'm working with a list of about 4,000 data records, virtual repeat is a godsend for performance (load time goes from about 30s to >1s!) but the styling looks really messy.

Are there any other methods for making `md-virtual-repeat` work with a table? I

**Comment by RolandHeath** [comment]
@jascination
It's an ugly solution, but you might be able to fix those issues using css on your cells, something like this:

    .table-cell {
        height: 64px;
        max-height: 64px;
        max-width: 176.5px; //Your width here... it might be better to set this per column.
        overflow: hidden;
        display: flex;
        align-items: center;
    }

It would be nice to have a directive for all this, though.

**Comment by jascination** [comment]
@RolandHeath That's a good start! Getting the widths right is a bit of an issue becuase I'm using tabular data that is never particularly consistent (sometimes long strings) but I suppose I can truncate them and work it all out from there.

For anyone else coming across this, I've put a class of `.repeated-item` on whatever is being ng-repeated, and the CSS rules I'm using is:

```
.repeated-item md-list md-list-item {
    height: 64px;
    max-height: 64px;
    max-width: 207.5px;
    display: flex;
}
```

Roland is correct above that setting individual max-widths per column is necessary, depending on what data you've got in there. Perhaps taking advantage of `Angular-Material`'s flex breakpoints for different screen sizes will also be of benefit (hiding certain cells for smaller screen widths).

**Comment by RolandHeath** [comment]
@jascination You might be able to do set the css width using javascript, based on the text length and font size. You can get actual element widths as well, but with a virtual-repeat not everything exists in the DOM so I don't think that'd be guaranteed to work. 

I'm not familiar with how the breakpoints work, but I'm sure if we take a look inside the some of the other examples that use them we'll be able to see if there's a css/js solution to that problem. 

I think we might have the beginnings of an md-table starting to form...

**Comment by zbjornson** [comment]
Forked from the examples above (with borders shown to illustrate the technique): http://codepen.io/anon/pen/yePoqr

This handles different sizes of contents using `flex`, and compensates for the different width of the header and body due to scrollbars with a single CSS rule. The flex property also makes it easy to make it responsive (with `flex-sm`, `flex-xs`, etc.)

**Comment by RolandHeath** [comment]
@zbjornson Not bad, although I think it needs overflow:hidden - I found the long text overflowed on my browser (chrome on fedora). It'd be good to detect the scrollbar width of the browser automatically, I've seen examples of this being done using javascript (but haven't tried to replicate it myself).

**Comment by stephengardner** [comment]
So really there's no way to use this feature with a native HTML table?

Really?

**Comment by iamisti** [comment]
Any progress on that?

**Comment by zbjornson** [comment]
@stephengardner @iamisti check out the codepen that I posted above and the variant RolandHeath posted after. We use that technique in production to combine virtual repeaters with native tables.

**Comment by iamisti** [comment]
@zbjornson Thanks but you posted something which basically replacing native tables with md-list-item's. That is not a good solution for me.

**Comment by gerardcarbo** [comment]
Maybe this:
https://codepen.io/enigmatic/pen/bEMQNj/

**Comment by gerardcarbo** [comment]
Maybe this:
https://github.com/daniel-nagy/md-data-table
