### ISSUE TITLE
md-icon issue. unable to load icon

### ISSUE THREAD

**Issue by ashokkumarsand** [angular/material#5205]
I write following code 
<md-button class="md-icon-button" aria-label="Menu" ng-click="openLeftMenu()">
                
                
                <md-icon class="material-icons">face</md-icon>
            </md-button>

and i got in html 

<button class="md-icon-button preview-glyphs md-button md-default-theme" ng-transclude="" aria-label="Menu" ng-click="openLeftMenu()" tabindex="0">
                
                
                <md-icon class="material-icons ng-scope ng-isolate-scope md-default-theme" aria-hidden="true"></md-icon>
            </button>

and ligature is disappeared and icon is not loaded. 
using current latest version of angular  and same issue is got previous version

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by ashokkumarsand** [comment]
check this http://codepen.io/anon/pen/Xmzmap

**Comment by programmist** [comment]
@ashokkumarsand: Your demo has Javascript console errors because you're referencing a controller that was is not defined.

```
ng-controller="ctrl"
```

Removing that fixes the issue for me.  If your issue persists, let me know and I'll re-open.
