### ISSUE TITLE
md-autocomplete only shows one item when far down on the page

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [angular/material#5209]
If an autocomplete is too far down on the page it will only show one item in the list (tested with chrome 46 and IE 11 using resolution 1920x1080). Open [this plunker](http://embed.plnkr.co/D6sAvF/preview) and scroll  down to the very bottom and try to add an item beginning with the letter a. Here is a screen recording showing the issue:

Current (1.0.0-rc3) behavior:
![2015-10-16_17-10-06](https://cloud.githubusercontent.com/assets/5230331/10545601/d61e518a-7429-11e5-9875-ccbf3770526f.gif)

Expected behavior:
![2015-10-16_17-11-26](https://cloud.githubusercontent.com/assets/5230331/10545590/c5d4fcde-7429-11e5-9875-f24fd43c8307.gif)

(Also clicking the small arrows in the scrollbar closes the list which is weird)

**Comment by hillerstorm** [comment]
Bumping this... total blocker

**Comment by Patrik-Lundqvist** [comment]
I updated the plunkr with new layout changes (1.0.0-rc3), problem still remains
