### ISSUE TITLE
md-dynamic-height overflow

### ISSUE THREAD

**Issue by echenley** [angular/material#5211]
This is a relatively small issue. Currently there is no way to add a drop shadow (using [md-card](https://material.angularjs.org/0.11.4/demo/card), for example) to the tab content area, due to the [`overflow: hidden` on the `md-tabs` element](https://github.com/angular/material/blob/master/src/components/tabs/tabs.scss#L25). If possible, transitioning the height of `md-tabs-content-wrapper` rather than `md-tabs` would alleviate this.

**Comment by STOpandthink** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
