### ISSUE TITLE
Error in plugin 'gulp-uglify'

### ISSUE THREAD

**Issue by loganfreeman** [angular/material#5212]
steps to reproduce

```shell
git clone  https://github.com/angular/material.git
npm install
gulp docs
```

Error in plugin 'gulp-uglify'
Message:
    /Users/scheng/Projects/material/dist/angular-material.js: Unexpected token punc «;», expected punc «,»
Details:
    fileName: /Users/scheng/Projects/material/dist/angular-material.js
    lineNumber: 21844

**Comment by jelbourn** [comment]
Should be fixed via 17f4bf49b268b473619b2253b009e721b13cd797
