### ISSUE TITLE
md-autocomplete: Add ability to disable auto-focus when hitting the clear button

### ISSUE THREAD

**Issue by mzbyszynski** [angular/material#5213]
Hi there,

I am trying to use an `md-autocomplete` widget to trigger a route change using the `md-selected-item-change` attribute. The problem I'm having is when a user hits the clear button after a value has been selected, the `md-selected-item` function is called before the menu code is completely cleaned up and `$mdUtil.enableScrolling()` never gets called, so all clicks are blocked on my ngview element, including the `md-autocomplete`, so nothing new can be selected.

I think one way to solve this would be to add a call to `$mdUtil.enableScrolling()` in the `cleanup` method on the [autocompleteController](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L168), which is called on the `$destroy` event. But I'm not too familiar with `$mdUtil` and I do see that it is called in another place in that file with a delay so maybe that is always needed? I'm not sure.

Or is there some other method I should be using instead of `md-selected-item-change` to trigger my ngRoute change via `md-autocomplete`?

Thanks for your help! Keep up the great work...

Marc

**Comment by mzbyszynski** [comment]
After looking at this some more, it appears that the issue for me was the I had `md-min-length=0`, and when you click the close icon, the widget auto focuses on the input, and that was triggering the menu to be shown, which added the scroll-blocking container to the dom. Then my ngRoute parameter change was fired and the menu was destroyed but the scroll-blocking wasn't ever removed from the dom.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
