### ISSUE TITLE
Feature request: md-autocomplete support Secondary Action in custom template

### ISSUE THREAD

**Issue by tsdragon0404** [angular/material#5215]
I have a list item in autocomplete and I want to open a detail card of item by click an icon on the custom template. Please review file attached. Thanks. 
![untitled](https://cloud.githubusercontent.com/assets/11863784/10547958/bb5344b8-7461-11e5-9df7-b8d787c73b80.png)

**Comment by epelc** [comment]
Try changing `ng-click="doSomething();"` on your icon to `ng-click="$event.preventDefault();doSomething();"`.

This should stop the default behavior of selecting the address when you click on the secondary icon.

**Comment by tsdragon0404** [comment]
But after that, when I do anything in new Card (in my case), the suggestion lists is disappear.
