### ISSUE TITLE
Bottom-sheet "Show as grid" demo broken on Android and IE

### ISSUE THREAD

**Issue by jelbourn** [angular/material#5216]
The grid is all messed up. Will post screenshot later.

**Comment by crissdev** [comment]
Screenshot for IE 11 (Version 11.0.9600.18053)

![bottomsheet](https://cloud.githubusercontent.com/assets/822571/10715047/f00071a4-7b0f-11e5-870a-73204ac8a437.gif)

**Comment by EladBezalel** [comment]
@crissdev can you please check on HEAD?

**Comment by crissdev** [comment]
@EladBezalel it works just fine (since 1.0.0) release.

**Comment by EladBezalel** [comment]
@crissdev thank you very much :)
