### ISSUE TITLE
Angular Material + Ionic + touch problems

### ISSUE THREAD

**Issue by rbrandino1** [angular/material#5218]
I'm trying to use the angular material with ionic, and i'm still having problems (as reported here) with touch, where the ripple effects are not being fired.
With 'ng-click', the function is executed, however, when i use touch in chrome emulator or on the real device, it stops working.

This is still occurring or is something I'm leaving to do?

I'am using the last version of both frameworks:
   Ionic, v1.1.0
   AngularJS (angular-aria, angular-animate) v1.4.7
   Angular Material Design: v0.11.4

**Comment by ThomasBurleson** [comment]
Angular Material + Ionic is not supported for v1.0.
