### ISSUE TITLE
Dialog: Document targetEvent

### ISSUE THREAD

**Issue by epelc** [angular/material#5219]
There should be a function on `$mdDialog.confirm()` to let you set the `targetEvent` field.

https://material.angularjs.org/latest/api/service/$mdDialog

**Comment by EladBezalel** [comment]
@epelc there's `targetEvent` field, as i understand this issue is about lacking documentation and not a bug, am i right?

**Comment by epelc** [comment]
There should be a helper function to set it. So you do not need to create a variable first.

I haven't checked the source but there's no docs for a function to set the `targetEvent` field.

**Comment by EladBezalel** [comment]
As you can easily see in the [Dialog Demo](https://material.angularjs.org/HEAD/demo/dialog) (if you open to see the code in the first demo) there is a helper function.

I will document it.

**Comment by epelc** [comment]
Ah I just overlooked that sorry.
