### ISSUE TITLE
mdToolbar: scroll shrink breaks on safari

### ISSUE THREAD

**Issue by nathantn** [angular/material#5220]
When md-content scrollTop is negative or bigger than subtraction between scrollHeight and offsetHeight md-toolbar breaks.

angular-material version: 0.11.2
browser: safari

**Comment by lricoy** [comment]
+1

**Comment by topherfangio** [comment]
Can you please provide a codepen which shows the issue? It would be helpful for us to see exactly what you are doing and how it breaks.

**Comment by nathantn** [comment]
You can reproduce this issue in the library example itself.

**Comment by topherfangio** [comment]
@nathantn Which demo are you using and what are the steps to reproduce? The basic Scroll Shrink example appears to be working correctly for me.

Also, what version of Safari are you using? Is this on Desktop or Mobile?

**Comment by mramanauskas** [comment]
Not creating separate issue, because i think that this is related. Experiencing weird md-toolbar scroll shrink behaviour on iphone devices using Safari, toolbar jumps like crazy when scrolling. Here is screen capture for this:

https://youtu.be/196tJh8p9_s

On Chrome it looks good.

**Comment by topherfangio** [comment]
Thanks for the video, verified that this is happening on desktop and iOS Safari with latest version.

**Comment by FDIM** [comment]
Why is this issue closed? md-toolbar and md-scroll-shrink is still broken on safari (when touch is involved). Simply open toolbar demo on iPad and scroll up (aka force overflow) and you'll see what I mean.

**Comment by topherfangio** [comment]
@FDIM This was closed as part of our deprecation effort. Please see https://groups.google.com/forum/#!topic/ngmaterial/3Ip9nd68bfk for more details.
