### ISSUE TITLE
md-menu suppresses click event bubbling

### ISSUE THREAD

**Issue by brianfeister** [angular/material#5222]
I have an `<md-menu>` and after wrestling with it a bit, I realize the reason I can't integrate it with the `ng-file-upload` directive is that `md-menu` seems to be suppressing click event bubbling. If I copy this code outside of `<md-menu>` it works without issue.  Is this a known issue?  Would it be possible to have an option that allows click events to bubble up?  

```
           <md-menu
              md-offset="24, 57"
              ng-if="!contentCtrl.doingAjax ">
              <md-button md-no-ink
                ng-click="$mdOpenMenu()">
                {{ contentCtrl.selectedNode.name }}
                <md-icon
                  aria-label="(Actions)"
                  size="md"
                  md-svg-icon="chevron-down" alt="Actions">
                </md-icon>
              </md-button>

              <md-menu-content width="4">

                <md-menu-item>
                  <md-button
                    ngf-select
                    ngf-accept="*"
                    ngf-keep="true"
                    ngf-reset-on-click="false"
                    ngf-multiple="true"
                    ng-model="contentCtrl.files"
                    aria-label="Upload">
                    <md-icon md-svg-icon="upload" alt="Upload Files"></md-icon>
                    Upload Files
                  </md-button>
                </md-menu-item>
          </md-menu>
```

**Comment by dmackerman** [comment]
It appears that `mdMenu` is indeed stopping propagation, see here:

https://github.com/angular/material/blob/master/src/components/menu/js/menuController.js#L87-L89

A simple option could be added and have those lines wrapped in a conditional.

**Comment by brianfeister** [comment]
@ThomasBurleson is this something you would be willing to add if I open a PR to address this?

**Comment by brianfeister** [comment]
actually @dmackerman I appreciate you jumping in but that's not quite my problem.  That prevented default event is pertinent only to the opening of the menu, I'm talking about clicking an element that's a child of the menu in the dropdown.

**Comment by rschmukler** [comment]
@brianfeister we would definitely take a PR to allow click propagation on menu child elements... Something like `md-propigate-click` which we check for before stoping propagation. Moving to post-1.0 but feel free to open a PR before.
