### ISSUE TITLE
DatePicker Demo not working right

### ISSUE THREAD

**Issue by radoslavpetranov** [angular/material#5223]
The datepicker demo seems broken ( no background and no selected date color )

https://material.angularjs.org/latest/demo/datepicker

Thought you'd like to know.

Cheers

**Comment by karthik-rp** [comment]
Seems it has been fixed in HEAD.,
https://material.angularjs.org/HEAD/demo/datepicker

**Comment by radoslavpetranov** [comment]
Yup - looks like it's fixed. Thanks guys!

**Comment by meksikann** [comment]
How to update it to working version? I use admintemplate with md-datepicker.
