### ISSUE TITLE
md-datepicker has gone transparent.

### ISSUE THREAD

**Issue by karthik-rp** [angular/material#5225]
I updated my project to lateset version., ie 0.11.4
I'm not sure if it is that was intended or not., but md-datepicker has gone transparent.

https://material.angularjs.org/0.11.4/demo/input

![selection_004](https://cloud.githubusercontent.com/assets/11206941/10557095/417a1d70-74ba-11e5-9032-715a855ba3a7.png)

**Comment by csvan** [comment]
https://github.com/angular/material/issues/5223

**Comment by karthik-rp** [comment]
Closing as duplicate of https://github.com/angular/material/issues/5223
