### ISSUE TITLE
layout-offest not working (0.11.4)

### ISSUE THREAD

**Issue by r0b-** [angular/material#5227]
https://github.com/angular/material/issues/4902 was closed by changing offset to layout-offset but I can't get it working... :-(
http://codepen.io/anon/pen/NGwgwZ?editors=101

Thanks

**Comment by jmmayoh** [comment]
You can see the breaking change note in version 0.11.3:

"Material Layout attribute offset should now be flex-offset."

Change "layout-offset" to "flex-offset". Should work.

**Comment by Splaktar** [comment]
`flex-offset` should be used, not `layout-offset`. See working CodePen [here](http://codepen.io/Splaktar/pen/ojoeMR?editors=101).
