### ISSUE TITLE
mdAutocomplete: Submit form on enter broken

### ISSUE THREAD

**Issue by mitchellwills** [angular/material#5228]
If the autocomplete list is closed then pressing enter when the input is focused should trigger a form submit if it is contained inside a form. This appears to be a regression since this feature was implemented a while back. See https://github.com/angular/material/issues/1530

http://codepen.io/anon/pen/MaOvoE

**Comment by uriva** [comment]
+1

**Comment by VinceOPS** [comment]
+1
