### ISSUE TITLE
md-tab-body + input container

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5229]
either with or without an icon, when label shrinks, input container moves.

```html
md-tab
						md-tab-label
							| Contacts

						md-tab-body
							md-input-container.md-icon-float.md-icon-left
								label
									| Search Contacts
```

![untitled screencast 1](https://cloud.githubusercontent.com/assets/5133412/10560652/b8fc54ee-74ce-11e5-8494-a0e39df563f4.gif)

**Comment by Splaktar** [comment]
Can you fix this with some padding above the input? or setting the min-height on the input?

**Comment by 0101adm** [comment]
.md-icon-float was causing the issue.

**Comment by rochapablo** [comment]
Yep, md-icon-float cause this, but at the demo (https://material.angularjs.org/latest/demo/input) it work. Why is that?

How can I use the icon + field without auto height on focus?
