### ISSUE TITLE
(feat) icon inside input

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5231]
http://codepen.io/jamesbarnett/pen/aBnbL

https://jsfiddle.net/rbsthlm/qE9kJ/

**Comment by EladBezalel** [comment]
This is not aligned with [Material spec](https://www.google.com/design/spec/components/text-fields.html#text-fields-single-line-text-field)
Icon comes before the [input field](https://material.angularjs.org/HEAD/demo/input)

**Comment by cmacdonnacha** [comment]
I know that this isn't aligned with Material spec but is it still possible?

Can something like this be achieved?

![image](https://cloud.githubusercontent.com/assets/9777763/13675153/36c42098-e6d8-11e5-9116-9d7f80598dca.png)

**Comment by EladBezalel** [comment]
You can direct this question to our [Forums](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by cmacdonnacha** [comment]
@EladBezalel Yea I [tried](https://groups.google.com/forum/#!topic/ngmaterial/Irun5vQ3Yx8) but as usual there is no response.
