### ISSUE TITLE
md-select broken on ios when running on chrome/crosswalk 

### ISSUE THREAD

**Issue by sombriks** [angular/material#5232]
Hello all,

i'm using angular/material on my hybrid app because it's awesome. However, i stumbled on this small yet problematic bug. 

in resume, the select options disappear before the user have a chance to choose one option.

In this video you can see the behavior: https://vid.me/S9DM

AFAIK it affects not only google chrome on ios, but crosswalk project too. On my cordova project i'm using crosswalk webview because it's far better than the vanilla ios webview.

**Comment by tourist** [comment]
Hi,

Look here #4296. Probably the same issue marked as fixed recently.

**Comment by sombriks** [comment]
Hello @tourist.

Just tried https://material.angularjs.org/0.12.0-rc1/demo/select

on the same ipad and the problem is gone!
