### ISSUE TITLE
[md-tabs] md-stretch-tabs – new parameter for {mobile: not stretched, desktop: stretched}

### ISSUE THREAD

**Issue by ericodes** [angular/material#5233]
Currently, md-tabs' `md-stretch-tabs` attributes accepts 3 kinds of parameters – `auto`, `always`, and `never`.

Can we add an addition parameter to allow for stretching on desktop only?

md-stretch-tabs	mobile	desktop
auto	                        stretched	---
always	                stretched	stretched
never	                ---	        ---
mobile-only             ---             stretched <<=== PROPOSED

Since mobile is usually much smaller, we didn't want to use the "stretch", which ultimately meant we had multiple tabs squished in just 300px of space.

**Comment by omeid** [comment]
Better yet, support `md-stretch-tabs-$media`, that way users can pick as they want.

**Comment by lwj5** [comment]
+1 for this.

Any news of this enhancement?

**Comment by chenchfort** [comment]
+1

**Comment by oliveris** [comment]
+1

**Comment by MatthiasGwiozda** [comment]
+1
