### ISSUE TITLE
Chips: add validation

### ISSUE THREAD

**Issue by danielzfranklin** [angular/material#5236]
I can't use chips without some sort of validation method. Both a regex pattern the input must conform to and a callback function would work well.

**Comment by LisaTatum** [comment]
@ThomasBurleson 

+1 for this request as I need also validation with md-chips when they are entered.

Especially I need angularjs async validations to a remote endpoint with database access.
Please also add min/max validations with ng-messages :-)

**Comment by gusnips** [comment]
+1
