### ISSUE TITLE
mdSelect: pre-selected values aren't selected

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#5238]
When the model is pre selected from the list, the select not showing it, #1699 was about it and it seemd to be fixed back then.

[codepen from HEAD](http://codepen.io/anon/pen/pjdVoE)

**Comment by unturk** [comment]
+1 to that.

As far as i understand, the problem is only with objects. String values are pre-selected just fine.

Here is an example; http://codepen.io/anon/pen/qOxOja

**Comment by willramos** [comment]
+ 1

**Comment by berkayakdal** [comment]
+1

**Comment by jordanskole** [comment]
+1

**Comment by rschmukler** [comment]
This is a duplicate of #2862 - please see the resolution in there.
