### ISSUE TITLE
md-tabs: Color scheme has gone wonky in 0.11.4 

### ISSUE THREAD

**Issue by CxRes** [angular/material#5240]
Since 0.11.4 in tabs (when using default color scheme) text is pink when unselected and white when selected (on a white background). 

Check the demo out for yourself!!!!

This seems like a regression. Please fix!

**Comment by enkoder** [comment]
I'm also trying to style my tabs but something is being inherited from md-ink-ripple which is also affecting the demo. Obvious bug in the current release.

**Comment by enkoder** [comment]
Oh cool it looks like its fixed in 0.12.0-rc1. Check it out @CxRes.

**Comment by EladBezalel** [comment]
Fixed on [HEAD](https://material.angularjs.org/HEAD/demo/tabs)

**Comment by CxRes** [comment]
Solves that  problem, but now the last of my tab items vanishes on app startup, only to reappear when I click on any of the remaining tabs. Again worked up till 0.11.3.

**Comment by EladBezalel** [comment]
@CxRes please open a separate issue and include a codepen with your problem
