### ISSUE TITLE
Implement mdSteppers component

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#5241]
![Steppers](http://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B7WCemMG6e0Vb2hCdkt3d05DVUE/components_acux_stepper_vertstep.png)

[Material spec](http://www.google.es/design/spec/components/steppers.html)

> References #1064

**Comment by Pelu2k12** [comment]
1+

**Comment by UncleBenjen** [comment]
+1, looking forward to this component!

**Comment by bastienJS** [comment]
cool "wizard" !

**Comment by RodrigoAxel** [comment]
+1

**Comment by RodrigoAxel** [comment]
+1, looking forward to this component!

**Comment by mallowigi** [comment]
+ 1

**Comment by LiberatedAmoeba** [comment]
+1, so useful

**Comment by TheRealBryon** [comment]
+1

**Comment by singhniranjan** [comment]
+1, will be very useful, looking forward

**Comment by jaoued** [comment]
:+1:

**Comment by UncleBenjen** [comment]
uv7pp8p8oo9 8
On Nov 27, 2015 08:52, "Jaoued" <notifications@github.com> wrote:
?

**Comment by stakkit** [comment]
+1

**Comment by climberwoodi** [comment]
+1

**Comment by bohrar** [comment]
very useful component...hope it gets implemented soon.

**Comment by amritk** [comment]
+1

**Comment by zzebastien** [comment]
+1

**Comment by SteveChadaway** [comment]
+1

**Comment by jojogeyer** [comment]
+1

**Comment by smolyakoff** [comment]
+1

**Comment by ipiz** [comment]
I have created a basic implementation of it based on md-tabs please checkout and contribute 
https://github.com/ipiz/md-steppers

**Comment by ainesophaur** [comment]
@ipiz unfortunately there are a lot of things in the spec that aren't implemented in your library. I had the same idea of using the md-tabs as a base. However I realized that steppers are much more than just a linear transition. There are vertical steppers, mobile steppers as well as different progress indication implementations. 

If you were going to add the rest of the spec I would suggest starting with the mobile steppers and then work your way towards the full vertical and horizontal layouts. Keep in mind that the spec from Google is very detailed and the angular-material library does its best to implement the entire spec.

**Comment by ipiz** [comment]
@ainesophaur thanks for the comments and suggestion, this will be just quick workarround while waiting for angular material to releaed the md-steppers. And i will continue to  improve it over time. Its basic at the momment.

**Comment by zzebastien** [comment]
In the same idea of mobile steppers, check out the AdWords iOS app: https://itunes.apple.com/ca/app/adwords/id1037457231?mt=8&ign-mpt=uo%3D4

![img_1728](https://cloud.githubusercontent.com/assets/3905605/12789982/2c370ee6-ca6e-11e5-841c-023a4ef84394.PNG)

**Comment by protactinium** [comment]
+1

**Comment by craigivemy** [comment]
+1

**Comment by AndrinGautschi** [comment]
+1 would be very useful

**Comment by stunaz** [comment]
+1

**Comment by darlanmendonca** [comment]
+1

**Comment by benbeadle** [comment]
+1

**Comment by HtmlMak** [comment]
+1

**Comment by berndvdveen** [comment]
+1

**Comment by geoffbrennan** [comment]
+1

**Comment by VesperDev** [comment]
+1

**Comment by pierrecle** [comment]
+1 here too :)

**Comment by Misiu** [comment]
+1

**Comment by anvial** [comment]
+1

**Comment by saffabook** [comment]
+1

**Comment by mominsamir** [comment]
+1

**Comment by jacobuk** [comment]
+1

**Comment by Yann77** [comment]
+1

**Comment by pradyotghosh000712** [comment]
+1

**Comment by pradyotghosh000712** [comment]
+10000000

**Comment by andrew-cunliffe** [comment]
👍

**Comment by cedrox** [comment]
+1
Any other other interesting source anywhere ?

**Comment by VivekVikranth** [comment]
When it will be available ? At least a beta.

**Comment by siva636** [comment]
As a temporary (or even permanent) workaround, you may use **Material UI Reactive stepper** component:
http://www.material-ui.com/#/components/stepper

**Comment by stunaz** [comment]
@siva636 can you do a codepen to show how you use this react component within an angular application?

**Comment by darlanmendonca** [comment]
why close the issue? WHYYYYYY?

**Comment by paralin** [comment]
??

**Comment by siva636** [comment]
Why this thread is closed?! Please have a habit of writing comments when closing a thread like this.

Does closing this thread mean that steppers will never be implemented in Angular Material 2? (If so how can you call Angular Material 2 as an implementation of material design?!)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by eberlitz** [comment]
I had to use a material steppers in an ongoing project, so I created this component: 

https://github.com/eberlitz/material-steppers

Maybe someone else finds it useful.

**Comment by RootsMJ** [comment]
+1 Would love to see this component implemented.

**Comment by PrajwalGonsalves07** [comment]
Is there any implementation of Stepper for Angular2 ? We are migrating to Angular 2 and we have many use cases where we use the steppers. I see from many chains that Stepper implementation for Angular2 is not started. Can anyone tell me how to proceed forward.

**Comment by PrajwalGonsalves07** [comment]
+1
