### ISSUE TITLE
Angular Material Alpha Toolbar not working on mobile safari...

### ISSUE THREAD

**Issue by hughred22** [angular/material#5242]
I am trying to recreate the design in this Angular Material Alpha Toolbar: 

    http://codepen.io/hughred22/pen/KdyebJ

Everything look great in desktop as you see here: https://actorreels.stamplayapp.com/#/actor-test/matthew-del-negro

But when viewing in mobile safari, if you scroll down and backup, the header is not rendering correctly. It seem to be the iOs address bar show up and disappear mess up the toolbar. Anywho has a clue what is causing this?

**Comment by EladBezalel** [comment]
I'm sorry but this implementation of toolbar is not official and yet been developed under our scope.
You could ask you question on our [forum](https://groups.google.com/forum/#!forum/ngmaterial) or wait for #1054 to be resolved
