### ISSUE TITLE
ALIGNMENT_OPTIONS is missing stretch

### ISSUE THREAD

**Issue by TommyM** [angular/material#5246]
I think with a recent layout refactor 'stretch' is forgotten in the array of possible alignment options.

https://github.com/angular/material/blob/2478f1d2b064d5e06ba57d01b5460fe232f4b270/src/core/services/layout/layout.js#L11

**Comment by ThomasBurleson** [comment]
What do you propose as missing ?

**Comment by TommyM** [comment]
Sorry for the terse issue description. Was in a hurry. 

Basically the 'layout="stretch"' case does not work in 0.11.4 as it adds a layout-align-start-start class to the element. I assume it is because stretch is not listed in that array I linked to as an alignment option. 'class="layout-align-stretch"' still works however.

**Comment by ThomasBurleson** [comment]
Fixed in 1.0-rc5.
