### ISSUE TITLE
ng-messages in md-input-container with md-icon-float css issue

### ISSUE THREAD

**Issue by mohitadwani** [angular/material#5247]
Using ng-messages inside md-input-container with md-icon-float has css issue. 
The error message is show directly under the icon of the input container.
![screenshot from 2015-10-19 17 26 47](https://cloud.githubusercontent.com/assets/13086209/10577205/cc0d522c-7686-11e5-83d9-5cbad2ad4002.png)

I don't know if this is deliberately done this way or not. But in my opinion it should start just under the input border bottom, after the icon. 

codepen for the same : http://codepen.io/mohitadwani/pen/QjOPMG

**Comment by programmist** [comment]
This is the intended behavior.  Please see the Errors demo:
https://material.angularjs.org/latest/demo/input
