### ISSUE TITLE
md-subheader should inherit hue unless provided explicitly

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [angular/material#5248]
`md-subheader` elements are styled separately from their containing `md-content`. This means whenever a hue is specified on an `md-content` the same hue must also be specified on all contained `md-subheader` elements. I think `md-subheader` elements should inherit the hue specified on their parent `md-content` unless overridden explicitly by a hue class on the `md-subheader` itself.

Example:
```HTML
<md-content class="md-hue-1">
    <!-- background color here is hue-1 -->

    <md-subheader>
        <!-- currently, the background color here is reset to default, -->
        <!-- and as a result does not match the content area -->
        <!-- it should inherit the 'md-hue-1' specification from parent -->
    </md-subheader>

</md-content>
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
