### ISSUE TITLE
layout: "flex=`value`" has noticeable "boost" when layout-gt-* used, in 0.12.rc-01

### ISSUE THREAD

**Issue by e-oz** [angular/material#5252]
very frustrating issue (leads to huge visual changes):
http://codepen.io/evgeniyoz/pen/WQXqqb?editors=100

**Comment by e-oz** [comment]
latest (1.0 RC1)
http://codepen.io/evgeniyoz/pen/EVoMJZ?editors=100

**Comment by e-oz** [comment]
Please provide some workaround at least, I can't even test new rc versions because of this bug.

**Comment by ThomasBurleson** [comment]
@e-oz What do you mean by "boost"

**Comment by e-oz** [comment]
@ThomasBurleson I mean lex-gt-md="50" takes much more than 50% of space. Please open link to codepen ("latest").

**Comment by ThomasBurleson** [comment]
@e-oz - I reviewed your codepen again. Try this:

```html
<div layout="column" style="height:200px">
  <div layout-gt-sm="row" layout="column" flex>
    <div flex="50" style="background-color: rgba(255,0,0,0.2)" layout layout-align="center center">
      <div>50%</div>
    </div>
    <div flex="50" style="background-color: rgba(0,255,0,0.2)" layout layout-align="center center">
      <div>50%</div>
    </div>
  </div>
</div>
```

* define height for the outer container (for column layout modes)
* note the `flex` attribute on ` <div layout-gt-sm="row" layout="column" flex>`
* set `flex="50"` or `flex` on the nested divs... both work.

**Comment by e-oz** [comment]
1. It's not always possible to hardcode height for container. Actually it's
almost never possible - I don't know and don't want to know what height
rendered page will take. This point is ridiculous for me.
2. You are missing the point of original markup: one of columns should take
50% on big screens and equivalent split on small (when 3 columns: 33%).

I'm sure you've closed issue with non-fixed bug.
