### ISSUE TITLE
MdTabs - current route is not retaining during browser refresh

### ISSUE THREAD

**Issue by chrisleedavis** [angular/material#5253]
Angular Material Version - **v0.11.4**
Browsers and Operating System - **chrome, firefox, & ie (windows 7)**

This functionality occurs if you use **ngroute or ui-router**.  Within your NG app, navigate to a page other than home and refresh the browser.  Instead of the browser retaining the current route, the app redirects to home page.  

Within **mdTabsTemplate** (link function), $mdUtil.nextTick(handleScope) is called.  Because there is no $timeout present, the processQueue function is executed and redirects the user back to the home page of the application.

Plunker (to download code sample): http://plnkr.co/edit/WIrj5U4NcDSR5W3KxT3m?p=preview

Before browser refresh
![image](https://cloud.githubusercontent.com/assets/6451259/10581871/cf8d4aa8-7652-11e5-95b4-d7f5f7bd9b1c.png)

After browser refresh
![image](https://cloud.githubusercontent.com/assets/6451259/10581892/e5a57018-7652-11e5-8703-5f292f6c9bcc.png)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
