### ISSUE TITLE
md-tooltip + chrome device mode

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5254]
http://codepen.io/0101adm/full/wKpwMd/

without a User Agent override, tooltip closes on either click or mouseover on the trigger element.

with a UA override of "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_2_1 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8C148 Safari/6533.18.5"... tooltip no longer closes.

this was working up to 0.11.4.

**Comment by SanderElias** [comment]
@0101adm, can you provide us with a use case for this scenario? It does not seem to be an issue on a supported Iphone.

**Comment by 0101adm** [comment]
codepen updated to rc1.

http://codepen.io/0101adm/pen/YyjvdO/

go into chromes device mode.

![untitled screencast 4](https://cloud.githubusercontent.com/assets/5133412/10912793/43adcf14-8208-11e5-9348-ef47109a5780.gif)

**Comment by SanderElias** [comment]
@0101adm I do see your issue. However it just seem to fail in a simulated environment, not on a actual phone. So my question was more, what is the scenario where this bug is hampering deployment?

**Comment by 0101adm** [comment]
i have duplicated this on a phones browser.  chrome.

moto x2 / android 5.1

it doesnt necessarily hamper development.  i can refactor later.  it just doesnt close when focus leaves the trigger.

**Comment by SanderElias** [comment]
@0101adm I will take a deeper look at this. I had the impression it was only failing in a simulator, and not on a real device.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
