### ISSUE TITLE
Dialog intermittently triggers validation during openning animation

### ISSUE THREAD

**Issue by dmitry-polubentsev-cp** [angular/material#5263]
A md-dialog element has a form with several containers with text inputs and md-select elements marked as required.

Some of the selects are populated asynchronously.

Sometimes after the dialog opens, one of the select elements has ng-invalid class applied, though the validation rules are passing and the form is valid.

Changing the value for that element does not remove ng-invalid class.

Seems like the elements get focused somehow during the opening dialog animation.

**Comment by topherfangio** [comment]
Can you please provide a Codepen showing the issue. It is very difficult to track down issues without an example of how it is failing :smile:

**Comment by ThomasBurleson** [comment]
Will reopen after CodePenis provided and issue demonstrable.
