### ISSUE TITLE
md-dialog and Bootstrap dropdown-menu

### ISSUE THREAD

**Issue by bampakoa** [angular/material#5268]
Hi,

I am trying to show an alert dialog in a page that contains several **ul** links, styled with Boostrap **dropdown-menu** class.
All components of the page are disabled when the dialog is shown, except the **dropdown-menu** links which remain active.

Available plunker: http://plnkr.co/edit/BjEgAGZ8rxkPLdlayti6

**Comment by bolerodan** [comment]
This is an issue of z-index. The Modal backdrop has a z-index of 80, while the bootstrap dropdown-menu has a z-index of like, what, 1000? Override the bootstrap dropdown-menu so its z-index is less than the modal backdrop.

**Comment by bampakoa** [comment]
@bolerodan Thanks a lot!
