### ISSUE TITLE
md-dialog not closing anymore reference #5195

### ISSUE THREAD

**Issue by kschwidder** [angular/material#5271]
Please reopen 5195. It is still not solved

**Comment by doppio** [comment]
+1, this is affecting my project and is quite frustrating :(

**Comment by makkart** [comment]
+1, when triggered from md-menu-item the dialog is not closed, only the backdrop. If I specify "closeTo" then it works, but i should not have to in my opinion

**Comment by hodeyp** [comment]
+1

**Comment by rscottfree** [comment]
+1

If I explicitly call $mdDialog.hide() before showing another dialog, then that second dialog won't close. If I don't call $mdDialog.hide() then the first dialog will close but the second one will not open (only the overlay is shown).

Previous functionality was that I would not need to call .hide() and opening a second dialog would simply close the first.

**Comment by EladBezalel** [comment]
There's no need for a dup, we are familiar with this issue and a PR has been submitted #5302,
Closing this as #5195 is open
