### ISSUE TITLE
[md-select] it's not styled correctly when has errors

### ISSUE THREAD

**Issue by viniciusdacal** [angular/material#5272]
there is no styles for md-select invalid

**Comment by viniciusdacal** [comment]
That happens inside input-container. When a md-select is inside a input-container which has the class md-input-invalid, the md-select should follow the same behavior of a input, that has a "invalid appearance"

**Comment by viniciusdacal** [comment]
A possible solution, could be add this style to select-theme.scss
```css
md-input-container.md-input-invalid md-select.md-THEME_NAME-theme {
  .md-select-value {
    color: '{{warn-500}}' !important;
    border-bottom-color: '{{warn-500}}' !important;
  }
}
```

**Comment by rschmukler** [comment]
Per the [validation demos](https://material.angularjs.org/latest/demo/select), the styling is working. Select only shows error style if it is `$dirty` and `$invalid`. If this issue actually isn't the issue, please open a new issue and submit a codepen. Thanks!
