### ISSUE TITLE
md-tab does not display content since 0.11.3

### ISSUE THREAD

**Issue by xeroxoid** [angular/material#5273]
I still can't figure out why, but tabs that work fine up to 0.11.2 are broken from 0.11.3 and on. 

I am opening an issue as I did not see any breaking changes in the changelog.

**Comment by 0101adm** [comment]
tabs are working for me in 0.12.0-rc1.

post a codepen.

**Comment by robertmesserle** [comment]
I suspect this is related to the addition of `md-tab-body`, but not enough information is provided here for me to possibly debug your issue.  Closing for now, but please respond with more details and a CodePen and I will reopen.
