### ISSUE TITLE
Weird icon in md-select and md-menu showing up in chrome

### ISSUE THREAD

**Issue by redyyu** [angular/material#5274]
Chrome Version 46.0.2490.71 (64-bit)
There is screen shot.

----------------
![screen shot 2015-10-21 at 1 02 46 am](https://cloud.githubusercontent.com/assets/724821/10615288/8b190b42-7791-11e5-9f27-9e29aa7bfd10.png)
----------------
I may installed some design font, but I think should not cause this.

**Comment by rschmukler** [comment]
This is caused by your font not supporting the `'\25BC'` unicode character used by the select.

To remedy this add a rule to your css like this:

```css
.md-select-icon:after {
  font-family: sans-serif;
}
```
