### ISSUE TITLE
md-datepicker min-max demo STILL doesn't work on Safari

### ISSUE THREAD

**Issue by colinskow** [angular/material#5275]
@ThomasBurleson @kseamon 

I'm opening a new issue because https://github.com/angular/material/issues/4950 was incorrectly closed.

On Safari the datepicker min-max demo infinitely loops the bottom two months. It stops correctly at the maximum date on Chrome. The cause is that a `$watchCollection` on `virtualRepeatController` gets called 3 times on Safari and only 2 times on Chrome, thus inserting repeated elements into the scroller.

This PR https://github.com/angular/material/pull/5009 by @mhchen fixes it. Although it only patches the symptom of the problem because we haven't identified the root cause yet. Further investigation may reveal a better solution, but this works for now.

Ideally this should be fixed for the 0.12.0 release.

**Comment by jelbourn** [comment]
@colinskow looks like that PR should have been merged, but was forgotten.

**Comment by colinskow** [comment]
That's why I've been nudging you ;-)

**Comment by jelbourn** [comment]
That PR was _actually_ merged, so hopefully this should be fixed now. Let me know if that's not the case.
