### ISSUE TITLE
md-autocomplete no way to prefill search

### ISSUE THREAD

**Issue by elubin** [angular/material#5277]
My use case is a button that says 'find other things like this one' and that launches a modal with an md-chips that contains an md-autocomplete.  I want the autocomplete to initialize with my string 'appl' and have it fire off the query immediately.

`<md-autocomplete md-no-cache
                             md-autofocus="true"
                             md-min-length="2"
                             md-delay="300"
                             md-selected-item="selItem"
                             md-search-text="srchItem"
                             md-items="item in queryValues(srchItem)">`

in my controller I tried $scope.srchItem = 'appl';  this DOES prefill the search string, but does not fire the queryValues() method.  (same if i put that in a $timeout)

Can you add a way for me to initialize the control with a search string value, that will fetch items (if my min-length and other criteria is met)

**Comment by elubin** [comment]
similiar to https://github.com/angular/material/issues/1779 I did try the ng-init, and it does show the string, but does not open the autocomplete and start searching.

`ng-init="srchItem='sha'"`

**Comment by topherfangio** [comment]
I believe this is supported out of the box. Please see the following demo for an example: http://codepen.io/topherfangio/pen/qOyrqE?editors=101

Note that the only things I changed were to set `self.searchText = "Tex"` in the controller and add `md-autofocus="true"` to the autocomplete.

If this doesn't work for you, please provide a Codepen (you can fork/edit the one above) to show us what you are doing and we will re-open the issue.

**Comment by elubin** [comment]
I can initialize with self.searchText = 'x' as you stated, but if 'x' is not an exact match, it does NOT fire off my query?

`md-items="item in queryValues(srchItem)"`

I need my queryValues() method to be called and the droplist to open and fill with my results.

(in your case, the text field fills with 'Tex' but doesn't show me the list that includes 'Texas')

**Comment by topherfangio** [comment]
Can you tell me what browser you are using? It is indeed firing the event and opening the list that shows "Texas" on Chrome.

**Comment by elubin** [comment]
my apologies, i tested your codepen on chrome and IE and it does indeed work.

I am on 0.11.4 so that may be part of the problem.... however i also tested 1.0.0rc2 with my code and I do not see it open.  you can close this ticket and i'll try and create a fiddle.  I am using autocomplete inside md-chip on an md-dialog, so i can't tell yet what's adding to the issue.

@topherfangio Thank you!

**Comment by topherfangio** [comment]
Gotcha. Please let us know if you find the exact issue and we'll definitely investigate!

**Comment by fabiusss** [comment]
+1

**Comment by jornncc** [comment]
Did anybody figure out a way to force the md-items="item in queryValues(srchItem)" queryValues to be executed? Our use case is that the list inside the chips change based on user action elsewhere and we must repopulate the list.

**Comment by elubin** [comment]
@jornncc there was never an issue getting queryValues() to execute.  My issue was prefilling before the control is displayed.  Post a fiddle if you want, but the query works as documented.

**Comment by jornncc** [comment]
@elubin thanks for the reply. That makes sense. We were able to figure out our issue as well; all we had to do was to md-no-cache=true to get the list to recreate the md-items.
