### ISSUE TITLE
md-chips: Add support for comma separated entry

### ISSUE THREAD

**Issue by Ignigena** [angular/material#5279]
I have a use case for the Chips component in which a user is entering a list of tags in the field. For most of my users it is not very intuitive to hit the enter key after each input. Rather, they enter a comma and expect the field to update accordingly.

While I can create custom handling for this in my controller, it seems to me this is a rather common use case which could use an opt-in setting on the directive. I'd be more than happy to submit a PR for this feature if it's something that makes sense in the framework.

**Comment by philippeluickx** [comment]
+1

**Comment by topherfangio** [comment]
Just to confirm, you basically want comma to work identically to the enter key correct?

**Comment by Ignigena** [comment]
Correct, so entering a comma would append the buffer to the list and create a new chip. @Frank3K suggested in my PR that semi-colons might also be a good use case for contact chips when typing an e-mail address. I have since modified the original PR to include a more generic approach (although understandable if this approach is not ideal.)

**Comment by satpaltanan** [comment]
The issue is closed for the desktop browser, but in case of mobile devices it is not working

**Comment by topherfangio** [comment]
@satpaltanan If you're having an issue on mobile, can you please open a new issue with a relevant Codepen and ping me on it? Thanks!

**Comment by satpaltanan** [comment]
Please check the codepen link
http://codepen.io/bsrinivasguptha/pen/YwamLm/
It has custom separator keys as Enter and Comma, but only Enter is working in the mobile device, Comma is not working.

**Comment by satpaltanan** [comment]
HI @topherfangio 

Any update on this issue.

**Comment by topherfangio** [comment]
@satpaltanan This seems to work ok on my iPhone. What mobile device are you using? Also, can you verify your CodePen email so that we can look at the example in fullscreen so that we can test on mobile a bit easier?

![screen shot 2017-04-07 at 4 28 54 pm](https://cloud.githubusercontent.com/assets/54370/24820560/52f4dff2-1baf-11e7-9ab5-e93db6aa8758.png)

**Comment by rcasurion** [comment]
Do we have option to disable this feature? Because in my case, we have options that includes ',' then the problem is we ca not write ',' anymore.
