### ISSUE TITLE
md-tab: last item vanishes 

### ISSUE THREAD

**Issue by CxRes** [angular/material#5280]
This seems to be a regression as the code worked until 0.11.3.

In my code the last `<md-tab>` item vanishes on startup. The moment I touch the tab or resize the window , it works correctly again. I am unable to reproduce the bug from my own code exactly in a pen. However, I can reproduce it in a rather contrived manner.

In the pen: http://codepen.io/anon/pen/vNpRKJ you will find five items.

Now, in the CSS, change the font-size in md-icon.tab-icon from 24px to 30px, the fifth item vanishes (in my own code problem occusr with font-size:24px).

I believe this has to do with icon interacting with the tab css. Please note, that I use a different Icon system, may be that is why the lack of reproducibility.

In dev tools I find that the width of `<md-pagination-wrapper>` is calculated incorrectly at startup and this is corrected later, which causes the last item to wrap to the next line.

**Comment by gitawego** [comment]
I got the same bug.....

**Comment by AllaanR** [comment]
I got the same

**Comment by hugorebelo** [comment]
+1

**Comment by PDSBGreg** [comment]
I have the same error with 1.0.0-rc1, but only in IE 11. Resizing the window doesn't fix the problem in my case though as the md-pagination-wrapper size is not updated.

If I have a tab selected and then use the arrow keys to manually select the hidden tab that way, I am still able to select the tab and show its contents (with the tab itself still hidden).

**Comment by bodocabdd** [comment]
Same here. =/

**Comment by fabiosimonetti** [comment]
:( the same error for me :(

**Comment by leonn** [comment]
+1

**Comment by robertmesserle** [comment]
This is being tracked in issue #5439

**Comment by ratikesh9** [comment]
Is this issue solved ?
