### ISSUE TITLE
When input tag under md-input-container contains type="text" or type="password" highlight bar is not showing up

### ISSUE THREAD

**Issue by faraazc** [angular/material#5282]
<md-input-container>
      <ng-md-icon icon="lock" style="fill: blue" size="24"></ng-md-icon> 
      <input ng-model="data.password" type="password" placeholder="Password" ng-required="true">
    </md-input-container>

Please see the attached image
First input does not contain any type. Thats the reason blue highlight bar is visible. Whereas in case of second input it contains type as password therefore highlight bar is hidden

![pass_screenshot from 2015-10-21 08 57 12](https://cloud.githubusercontent.com/assets/3984402/10626991/16f473be-77d2-11e5-9e86-2d3bdb581594.png)

**Comment by faraazc** [comment]
i am using Angular material version 0.11.0

**Comment by faraazc** [comment]
When i update my angular-material libs to latest()
i am seeing as shown below.Though bar appears but not aligned properly. placeholder label appears on top of bar

![new_screenshot from 2015-10-21 09 36 38](https://cloud.githubusercontent.com/assets/3984402/10627455/49d96668-77d7-11e5-9513-312067bda434.png)

**Comment by EladBezalel** [comment]
@faraazc Can you provide a codepen so we can investigate this more?

**Comment by EladBezalel** [comment]
Can't reproduce - [codepen](http://codepen.io/EladBezalel/pen/NxzPjq)

**Comment by CarlosRoig** [comment]
I have the same problem: When using 'md-input-container', if the input has no type, is ok, but when setting `type="password"` or `type="text"` then the bar under the text disappears.
![image](https://cloud.githubusercontent.com/assets/13415522/15141475/760f7a70-16a0-11e6-8fa3-d8a75181d24f.png)

**Comment by jhlee8804** [comment]
@CarlosRoig Here's works fine.

```
    md-input-container {
      input[type="password"] {
        border-bottom-style: solid !important;
        border-bottom-color: rgba(0,0,0,0.12) !important;
      }
    }
    md-input-container.md-input-focused {
      input[type="password"] {
        border-bottom-style: solid !important;
        border-bottom-color: #ec745d !important;
      }
    }
```

**Comment by jazib-bashir** [comment]
This Solution is working for me for all input element containing 'type' attribute.

**AngularJS**:  v1.5.8
**Angular Material**:  v1.1.1
**ionic**: v1.3.1 

```
md-input-container {
  input[type] {
    border-bottom-style: solid !important;
    border-bottom-color: rgba(0,0,0,0.12) !important;
    border-bottom: 1px;
  }
}
md-input-container.md-input-focused {
  input[type] {
    border-bottom: 1px;
    border-bottom-style: solid !important;
    border-bottom-color: #ec745d !important;
  }
}
```
