### ISSUE TITLE
Grid System doesn't shows color as in documentation

### ISSUE THREAD

**Issue by mimani** [angular/material#5287]
Hi, I am using [grid](https://material.angularjs.org/latest/layout/grid) elements in my example, I am testing flex attribute. In the example this shows three different color for three flex elements, but in the [codepen](http://codepen.io/anon/pen/WQdYGY), I am not getting those colors. Please help.

**Comment by gustavohenke** [comment]
These colors are used to help you see where each grid element ends.

**Comment by mimani** [comment]
Than, We should add corresponding CSS also in the documentation, It should be WYSIWYG.

**Comment by Splaktar** [comment]
@mimani The CSS for the coloring is many times larger than the example itself (only 10-15 lines). So it doesn't make a ton of sense to complicate the example with a ton of styling. The colors are hard coded and other than using material design pallet, there isn't anything really special about them.

If you want to see the CSS, just open DevTools and click on the `docs.css` link. Then you can clearly see it. You will want to adjust the selectors to fit your application of course, but as you can see below this should not be too complicated. I.e. in your app, you might not just be using `div` elements in your grid, they might be cards or something else.

```
.colorNested .demo-content > div div  {
  padding: 8px;
  box-shadow: 0px 2px 5px 0 rgba(0,0,0,0.26);
  opacity: 0.9;
  color: white;
  text-align: center;
}

.colorNested-noPad .demo-content > div div  {
  box-shadow: 0px 2px 5px 0 rgba(0,0,0,0.26);
  opacity: 0.9;
  color: white;
  text-align: center;
}

.colorNested .demo-content > div div:nth-child(1),
.colorNested-noPad .demo-content > div div:nth-child(1) {
  background-color: #009688;
}
.colorNested .demo-content > div div:nth-child(2),
.colorNested-noPad .demo-content > div div:nth-child(2) {
  background-color: #3949ab;
}
.colorNested .demo-content > div div:nth-child(3),
.colorNested-noPad .demo-content > div div:nth-child(3) {
  background-color: #9c27b0;
}
.colorNested .demo-content > div div:nth-child(4),
.colorNested-noPad .demo-content > div div:nth-child(4) {
  background-color: #8bc34a;
}
.colorNested .demo-content > div div:nth-child(5),
.colorNested-noPad .demo-content > div div:nth-child(5)  {
  background-color: #deb867;
}
.colorNested .demo-content > div div:nth-child(6),
.colorNested-noPad .demo-content > div div:nth-child(6) {
  background-color: #FF5722;
}
.colorNested .demo-content > div div:nth-child(7),
.colorNested-noPad .demo-content > div div:nth-child(7)  {
  background-color: #03A9F4;
}
```

**Comment by mimani** [comment]
@Splaktar You are absolutely right, Now I see that it is very simple. Just that from that documentation it was looking like, we are getting it out of the box, so got confused.

Thanks for clarification, but still I think that documentation feels incomplete, specifically for someone who may be new to this world.
