### ISSUE TITLE
md-menu: Using md-menu-item[type="checkbox"] with boolean variable directly from scope does not work

### ISSUE THREAD

**Issue by frigus02** [angular/material#5288]
I have some boolean variables directly attached to my scope. Using them for `ng-model` of a `md-menu-item` with `type="checkbox"` does not work correctly. I does correctly read the current state of the variable, but does not write a new value back.

```javascript
function MyController($scope) {
    $scope.myvar = true;
}
```
```html
<md-menu-item type="checkbox" ng-model="myvar">My Var</md-menu-item>
```

Here is a full example: http://codepen.io/anon/pen/yYpQzm?editors=101

It seems like the scope inside md-menu is a new child scope. So reading the variable works because it traverses through the parents. But writing does not work, because it overides the variable in the child scope.

**Comment by rschmukler** [comment]
This is a result of a `md-menu` creating a child scope so that `$mdMenuOpen()` is exposed to the inner button. As you said, it does work if you use an object. Our recommendation would be to use use the `controllerAs` syntax to expose the controller and then set the value on that.
