### ISSUE TITLE
mdDatePicker: cosmetic glitch when having an mdTheme within an mdTheme

### ISSUE THREAD

**Issue by lyschoening** [angular/material#5293]
When there's a theme within a theme, the theme for the background color of the date-picker is sometimes that of the parent theme. This is in v0.12.0-rc1.

http://codepen.io/anon/pen/KdZJLG

![screen shot 2015-10-21 at 16 49 48](https://cloud.githubusercontent.com/assets/74085/10640177/d785006c-7813-11e5-989e-a5041c9a4b2f.png)

**Comment by houmark** [comment]
+1
