### ISSUE TITLE
md-button on mobile devices stays hover/focus

### ISSUE THREAD

**Issue by lukabers** [angular/material#5294]
Hello,
on mobile devices md-button stays hover/focus after passing on it for scrolling.
I'm testing on 1.0.0-rc1

Any solution?
Thanks.

**Comment by mckenzielong** [comment]
Possibly related to #5261?

**Comment by sckoh** [comment]
+1

**Comment by iamdeadman** [comment]
I am also facing this solution. Is there any temporary fix for this now

**Comment by ThomasBurleson** [comment]
No known fix yet. Pull Requests are welcomed.
