### ISSUE TITLE
mdListItem: ripple is attached twice for 'clickable' divs

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#5295]
mdListItem ends up attaching two ripple divs when an attributes: `['ng-click',
            'ui-sref', 'href', 'ng-href', 'ng-attr-ui-sref']` are set.  This can be seen on [the demo](https://material.angularjs.org/HEAD/demo/list) and is inconsistent behaviour (checkbox list item versus one with an ng-click attached.)

mdListItem calls wrapIn('button') ends up registering the first ripple div,  we later then call `computeClickable` then attachs the second ripple div.

**Browser:** Chrome 45, Opera 32
**Version:** 1.0.0 rc-1
**Suggested fix:** when attaching the ripple in computeClickable, something like this: 
```javascript
if (proxies.length || hasClick) {
  $element.addClass('md-clickable');
  if (!hasClick) {
   ctrl.attachRipple($scope, angular.element($element[0].querySelector('.md-no-style')));
  }
 }
```
This would still result in rounded ripples per #5177 (as it uses the button ripple which does not set size as full)

**Comment by EladBezalel** [comment]
A PR is very welcome!
