### ISSUE TITLE
layout-row sets max-height instead of max-width with flex="x"

### ISSUE THREAD

**Issue by orangesoup** [angular/material#5299]
I've made 2 pens, one is with 0.11.4 and the other one is with 1.0 rc.

0.11.4: http://codepen.io/anon/pen/avErag
1.0 rc: http://codepen.io/anon/pen/EVozEJ

In 0.11.4 it works as one would expect (at least I think so), but in 1.0 rc even though the parent is set to layout-row the children divs have max-height set to x% instead of max-width.

**Comment by ThomasBurleson** [comment]
The settings are correct.
