### ISSUE TITLE
Textarea indistinguishable from input, ultimately confusing users

### ISSUE THREAD

**Issue by willramos** [angular/material#5301]
Since it looks visually identical to the input text, the user doesn't know he's dealing with a textarea until he accidentally hits enter. 

Perhaps you can add an option to show or not show an outline?
One that looks "material design-ey," perhaps?

Or just... something to differentiate it more, or make it clear to the user he can hit enter and type a story, etc...

**Comment by daniel-halldorsson** [comment]
+1 ive thought the same thing

**Comment by corentin-gautier** [comment]
https://www.google.com/design/spec/components/text-fields.html#text-fields-multi-line-text-field

**Comment by focomoso** [comment]
I second this. It's confusing my users.

**Comment by cleever** [comment]
Yes, its very confusing. Material design itself has some input issues. The UX with forms are sometimes unpleasant.

**Comment by crisbeto** [comment]
The `textarea` design follows the [Material Design spec](https://material.google.com/components/text-fields.html#text-fields-multi-line-text-field) and we can't deviate from it. Closing.
