### ISSUE TITLE
'required' doesn't work with md-select(1.0.0-rc1)

### ISSUE THREAD

**Issue by alanpurple** [angular/material#5304]
'required' doesn't work with md-select in form
but is in the demo

It works only when some event cause that model to be set to undefined

**Comment by rschmukler** [comment]
Per [this demo](http://codepen.io/rschmukler/pen/meGVwO) it appears to be working. Please submit a demo.

**Comment by rschmukler** [comment]
Closing. Please open a new issue with demo if it is still an issue.
