### ISSUE TITLE
md-select opening animation is sluggish on firefox

### ISSUE THREAD

**Issue by sarod** [angular/material#5307]
md-select animation feels sluggish using firefox.

Here is a screen capture of the animation on firefox 42.0b7 (on ubuntu) using angular material 1.0-rc1

![output](https://cloud.githubusercontent.com/assets/8543138/10661575/3c1e9c18-78af-11e5-89e4-fe36be6cb8e1.gif)

Animation is smoother using chrome

**Comment by corentin-gautier** [comment]
Smoother on chrome, yet very poor performances : 
![image](https://cloud.githubusercontent.com/assets/4660731/10661767/430ab790-78b0-11e5-98bd-528c94d74394.png)

( that's opening and clicking on an item )

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (518/500 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:1238)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avsc8-000L1g-4C
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:44 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=d8pAmt4eWQAIMJ30Z1tq737IWjg=; b=YJN344zvkDg18XZK
	JyVxAJuskxCI5TjapoKPP6NO+ej9Uh0mReRTWygRjje8QzckyNl5W7eFwz91HvwG
	X13J1nnFB1sA7zXWxErjowgIhLmqMpIR1X1OErhkpL/HEKYWrUILonyeJehf6VW2
	ibqHBouWqvVnI61z/v3t3AIsA80=
Received: by filter0815p1mdw1.sendgrid.net with SMTP id filter0815p1mdw1.26142.5722734E8
        2016-04-28 20:32:14.046941434 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id 6Oll4MIJRP22do1Ko9N4YA
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:14.209 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:14 -0700
