### ISSUE TITLE
md-autocomplete ng-click in md-not-found template with promise

### ISSUE THREAD

**Issue by WedgeSama** [angular/material#5308]
If use of a promise to get items, the ng-click in the md-not-found template is not triggered. It can be reproduse with the [HEAD doc example](https://material.angularjs.org/HEAD/demo/autocomplete) by check `Simulate query for result?`.

Do not work on the 1.0.0-rc1 too.

And the solution given in #5215 do not work in this case.

**Comment by epelc** [comment]
Why would you want the `md-not-found` template to show when you click on a button for one of the suggestions? It should just close the suggestions list all together and do whatever your `ng-click` handler wants.

**Comment by WedgeSama** [comment]
It is not that. I want to click on a link in the `md-not-found` template but it did not trigger the ng-click event inside of the template (to create a new item based on the search terms for example).

**Comment by epelc** [comment]
Sorry for the misunderstanding. That makes perfect sense. This is definitely a bug.

Also it might have something to do with the `pointer-events` they tend to break things like this if they aren't set correctly. See https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

**Comment by luke14free** [comment]
+1

**Comment by lekev** [comment]
+1

**Comment by tiagopromob** [comment]
+1

**Comment by chunkai1312** [comment]
+1

**Comment by andrewmcconville** [comment]
+1

**Comment by chunkai1312** [comment]
+1

**Comment by RolandHeath** [comment]
This looks like a more complicated relative of #5526, so might be worth testing after #6103 is merged.

**Comment by mattdowell** [comment]
+1

**Comment by steffi80** [comment]
+1

**Comment by egystr** [comment]
+1

**Comment by phsantiago** [comment]
+1
