### ISSUE TITLE
$mdToast circular dependancy

### ISSUE THREAD

**Issue by Josephdias92** [angular/material#5311]
when i try to inject $mdToast into a custom service it throws circular dependency error.
how to fix this.
and also md-menu doesnt work on ng-repeat when i click on the menu after some clicks this whole screen area becomes unclickable

**Comment by EladBezalel** [comment]
Please provide codepens with your problems so we can investigate more

**Comment by arabsight** [comment]
try to inject $injector instead and then:
```js
var $mdToast = $injector.get('$mdToast');
```

**Comment by DevVersion** [comment]
@Josephdias92 Are you still interested in solving this issue?

**Comment by Josephdias92** [comment]
@DevVersion thanks i already solved the issue by using injector 
can you help me out with timepicker i have been searching for timepicker  plugin for more then 10 days
