### ISSUE TITLE
Card Reveal

### ISSUE THREAD

**Issue by werne2j** [angular/material#5313]
Angular Material should implement the card reveal feature as seen in Materialize CSS.

http://demo.geekslabs.com/materialize/v2.1/layout02/ui-cards.html#card-reveal

**Comment by JobaDiniz** [comment]
+1

**Comment by anthonyvialleton** [comment]
+1

**Comment by ram-you** [comment]
+1

**Comment by aminahmedkhan** [comment]
+1

**Comment by ThomasBurleson** [comment]
Great feature. Is this is defined in the Material Design specifications? 
Pull Request welcome.

**Comment by jeshc** [comment]
+1

**Comment by datenwort** [comment]
+1

**Comment by itsanmax** [comment]
Is this effect available on latest angular material? If possible kindly provide any working example for same. Thanks !
