### ISSUE TITLE
Fab speed dial / Fab toolbar can not be locked open

### ISSUE THREAD

**Issue by sebakerckhof** [angular/material#5314]
Currently, we can not fully control the open/closed state of fab speed dial and fab toolbar, since even when using `md-open`, it will close when a user selects an action.
This kind of makes md-open worthless, since it could be set to a variable that's true, but still be closed...

**Comment by EladBezalel** [comment]
Related to #4973

**Comment by topherfangio** [comment]
I think #4973 is a more elegant solution. Closing this in favor of that one; please add comments there.
