### ISSUE TITLE
Md-tabs in sidenav not working together with change in locked state

### ISSUE THREAD

**Issue by sebakerckhof** [angular/material#5316]
I have a sidenav that can change the locked state ( `md-is-locked-open`). In the sidenav there are tabs. When initially the sidenav is closed and then it is opened, the tabs display incorrectly:
![image](https://cloud.githubusercontent.com/assets/88471/10667743/2bf31858-78d9-11e5-8190-1ce64b980d71.png)
If I click one of the tabs, they are repainted correct.

Reproduction: http://codepen.io/anon/pen/BoYLdX

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by Splaktar** [comment]
Verified fixed in 1.1.5: https://codepen.io/Splaktar/pen/ZvOVyp?editors=1010
