### ISSUE TITLE
SOLVED: weird fix :: inputs are not working with ui-state provider

### ISSUE THREAD

**Issue by Davidx7** [angular/material#5318]
Index ui-view ::
``` <body><md-content ui-view class="ng-scope flex" style="height: 100%;"></md-content></body>```
loads the main content/navigation area with menus and stuff, for this I just left it empty
```<md-content ui-view md-scroll-y="" class="ng-scope flex"></md-content>```
then a simple 
```<md-input-container flex>
        <label>Biography</label>
        <textarea ng-model="_input.user.biography" columns="1" md-maxlength="150"></textarea>
      </md-input-container>```
But it doesn't work. I tried all exercises from the demos, that have inputs in them. 
I remove from my angular all other plugins that might interfere, but still nothing

It simply shows a input without any styles applied to it and no interactivity.

I have also used dev tools to look at the applied CSS to see any conflicts or overwrites. Nothing
----------------------------------------------

It gets even weirder. I triggered an error in the ```index.html``` and all of a sudden the inputs started working. Without that error, they stop working

/////////////////
The solution is very odd
```<md-content ui-view class="ng-scope flex" style="height: 100%;"></md-content>
<md-input-container style="display: none;"><input ng-model="xxxxxxxxx"></md-input-container>```

Adding a hidden input-container under the ui-view in the index, makes all the inputs, everywhere, regardless of loading time, work. 

Probably the reflow trigger.
Any way to do that manually in the controller?

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by vmvini** [comment]
Hi, I'm having the same weird problem with the same md-input-container.
This problem only happened when I adapted my project to webpack and to do lazy load of states with ocLazyLoad and ui-router-extras future state.
And the md-input-container is showing this weird behavior only when is inside some partial template loaded in some state. When I put inside my main index.html, the md-input-container works great. 

I'm using angular and material latest versions, though.

**Comment by vmvini** [comment]
Also, the weird fix proposed by gp187 works!
But I wonder why...
