### ISSUE TITLE
Problem on Closing $mdDialog

### ISSUE THREAD

**Issue by deevorak** [angular/material#5319]
Related to issue  #5192 

The issue is still happening on version 1.0.0-RC1 angular material. Tested with angular 1.4.7

Steps:
* Create a dialog with shared scope.
```javascript
$mdDialog.show({
				controller: controllerName,
				templateUrl: viewName,
				scope : $scope,
				preserveScope : true,
				targetEvent: ev
			});
```

* Inside dialog's controller create a toast action that performs dialog closing (fired on close button ng-click - like a confirmation that dialog will be closed)

```javascript
var toast = $mdToast.simple()
              .content(mensagem)
              .theme('info-toast')
              .action('OK')
              .highlightAction(false)
              .position('top right')
              .hideDelay(false)
              .parent(angular.element('form[name=enderecoForm]'));

$mdToast.show(toast).then(function(response) {
    if (response == 'ok') {
        $mdDialog.hide();
         }
});
```
* Clicking on Toast action will result:  Dialog will remain oppened instead of being hide.

**Comment by EladBezalel** [comment]
Closing for dup. Let's make #5192 the active issue
