### ISSUE TITLE
Keep fab speed dial open?

### ISSUE THREAD

**Issue by morgs32** [angular/material#5320]
Does anyone else see a use case where the speed dial should remain open until closing it with the trigger button? I want to use it for zooming/rotating/adjusting an image, so I can't have it closing after every button push.

**Comment by jwasil** [comment]
I have a very similar use case; I would really like to keep it open when interacting with the the child `<md-fab-actions>` and when the entire speed dial loses focus.  It would be great if it could (optionally) close only when explicitly clicking on the `<md-fab-trigger>`.  Simply trying to always re-set the `md-open` attribute back to `true`, for example when clicking on a child `<md-fab-actions>`, doesn't seem to help here.

**Comment by EladBezalel** [comment]
Dup #5314
