### ISSUE TITLE
Adding -webkit-overflow-scrolling: touch to .md-virtual-repeat-scroller

### ISSUE THREAD

**Issue by RichOren** [angular/material#5322]
I think it would be a good idea to add -webkit-overflow-scrolling: touch; to this code. It would help scrolling content on touch devices.

```
.md-virtual-repeat-container .md-virtual-repeat-scroller {
    bottom: 0;
    box-sizing: border-box;
    left: 0;
    margin: 0;
    overflow-x: hidden;
    padding: 0;
    position: absolute;
    right: 0;
    top: 0;
}
```

**Comment by mckenzielong** [comment]
:+1: I think this would bring some consistency between md-select options (which has touch set) and autocomplete's options (which does not have touch set.)
