### ISSUE TITLE
Icon not aligned when setting non floating input with icon (dynamic label)

### ISSUE THREAD

**Issue by natcohen** [angular/material#5328]
When trying to set an input with an icon and a dynamic label, the icon is not aligned with the input:

    <md-input-container>
       <label>Name</label>
       <md-icon md-svg-src="img/icons/ic_person_24px.svg" class="name"></md-icon>
       <input ng-model="user.name" type="text">
    </md-input-container>

**Comment by programmist** [comment]
I'm unable to reproduce this issue.  Please see the bottom example of the input demo, which appears to be the example you're using. https://material.angularjs.org/latest/demo/input
