### ISSUE TITLE
How to implement breadcrumb using angular-material

### ISSUE THREAD

**Issue by mimani** [angular/material#5329]
Hi,

I am creating a webapp, where I need a breadcrumb(with custom fields, independent of page navigation). I didn't found breadcrumb available in angular-material's documentation. Is there a ways I can make a breadcrumb with existing components or will this be implemented in future release?

**Comment by EladBezalel** [comment]
Breadcrumb is not a part of the material spec (may be in the future) 
You can easily use buttons and icons for creating this, 
Please move this question to the [forum](https://groups.google.com/forum/#!forum/ngmaterial)  as it's not an issue.
