### ISSUE TITLE
md-tabs not working anymore

### ISSUE THREAD

**Issue by marvinosswald** [angular/material#5333]
Does anybody have issues with md-tabs since 1.0.0 ? 

Because I don't now what really happens i'm not able to provide further informations.. will update this issue asap.

Problem seems to be that I'm using 

```javascript
<md-tab-label>
	<span translate>GENERAL</span>
</md-tab-label>
```

instead of `label=""`

[Codepen Demo](http://codepen.io/marvinosswald/pen/avGmPw/?editors=100)

**Comment by EladBezalel** [comment]
Can you please update if it's solved or post a codepen with your issue so we can investigate more?

**Comment by marvinosswald** [comment]
Sure.[Codepen Demo](http://codepen.io/marvinosswald/pen/avGmPw/?editors=100)

**Comment by EladBezalel** [comment]
@marvinosswald you probably missed [this](https://material.angularjs.org/latest/api/directive/mdTab)
quoting: 
> Please note that if you use <md-tab-label>, your content MUST be wrapped in the <md-tab-body> tag.
