### ISSUE TITLE
$mddialog close() methods scrolls page to top on IE11

### ISSUE THREAD

**Issue by prussian-blue** [angular/material#5334]
Hello all:

when calling to the $mdDialog.cancel() or $mdDialog.hide() methods, my page scrolls to the top.

This works well in Chrome though as it closes the dialog and stays where it should. 

However in ie11, you close it and the page scrolls to the top; I have tried to hide the scrollbar and return a promise but seems that is capable of scrolling even with the scrollbar hidden

**Comment by Patrik-Lundqvist** [comment]
This is a problem for all dialogs right now, selectors etc. See: 
angular/material/issues/4640
angular/material/issues/3627
angular/material/issues/3511

**Comment by sharpmachine** [comment]
The same is happening to me but in Chrome. It also happens with `$mdDialog.cancel()`.

**Comment by hillerstorm** [comment]
http://codepen.io/anon/pen/QjBKbm

This is the actual codepen from the docs, just edited to add some page height.
Scroll down to the select in IE, open the select, click outside of the select, it'll scroll to the top.
If you select an item, it'll scroll to the top first and then back down but only to put the select in to view (not where you were before selecting).

**Comment by wolfika** [comment]
See my comment in #4640.

**Comment by imannorouzi** [comment]
Here is a workaround. Just move the scroll from the body element to an inner element like below:

< body>
< div id="container">
< /div>
< body>

// Style
body{
height: 100%;
width: 100%;
overflow: hidden;
}
#container{
height: 100%;
width: 100%;
overflow-y: scroll;
}
