### ISSUE TITLE
Autofocus input elements

### ISSUE THREAD

**Issue by SnakeME** [angular/material#5335]
Is there a solution to set autofocus for input elements which use the md-input-container?

The following example is not working:

```
<md-input-container>
  <label>Username</label>
  <input ng-model="user.name" type="text" autofocus>
</md-input-container>
```

My current workaround is adding focus to the input and the class md-input-focused to md-input-container myself.

**Comment by ivan7237d** [comment]
I also ran into this and like you ended up setting focus manually, with $timeout, but in my experience calling `.focus()` was sufficient, I didn't manually add `md-input-focused` class. If `autofocus` was supported, would be a nice addition.

**Comment by SnakeME** [comment]
When I just call .focus() then the focus is set for the input field, but it doesn't have the angular material design (colored bottom border).

**Comment by ivan7237d** [comment]
Hmm that's strange, because in my case it does get the colored bottom border. As far as I understand, calling focus() should have the same result as for instance tabbing to the input, the focus event should trigger the class change.

**Comment by adrianandreias** [comment]
Isn't this what `md-autofocus` does? If I am not misunderstanding this the issue should be closed.

```javascript
<md-input-container>
  <label>Username</label>
  <input ng-model="user.name" type="text" md-autofocus>
</md-input-container>
```

**Comment by EladBezalel** [comment]
@SnakeME did you got your answer from @adrianandreias (thanks!)

**Comment by SnakeME** [comment]
md-autofocus is not working for me (using v1.0.1).

http://codepen.io/anon/pen/zrdmaW

**Comment by EladBezalel** [comment]
@SnakeME are you trying to use [dialog/autocomplete/bottomsheet/sidenav](https://material.angularjs.org/latest/api/directive/mdAutofocus)?

maybe we should add support for just input container

**Comment by SnakeME** [comment]
My case has nothing to do with dialog/autocomplete/bottomsheet/sidenav. I just want to set autofocus for a standart input container. Like this attribute: http://www.w3schools.com/tags/att_input_autofocus.asp

But wether the HTML attribute nor md-autofocus are working.

<input ng-model="user.title" type="text" autofocus>
<input ng-model="user.title" type="text" md-autofocus>

Both attributes seem to be ignored.

I've updated the codepen http://codepen.io/anon/pen/zrdmaW

**Comment by adrianandreias** [comment]
I can confirm that `md-autofocus` in a simple page, but only in dialogs (as described in #6680).

(Initially you asked if there is a solution: there's is one, just that not working due to a bug :) ).

**Comment by mangrish** [comment]
:+1:

**Comment by RandyDavis** [comment]
I just ran into this issue and was able to get it to work correctly until a proper fix can be implemented by using md-autofocus="autofocus" instead of md-autofocus alone.

**Comment by Kizmar** [comment]
Running into an issue here as well. In my case, I tried md-autofocus and md-autofocus="autofocus" on both the input itself and the md-input-container. None of the combinations worked. 

Currently I have autofocus on the input. If the site is loaded on the sign-in page (for example), it works as intended. If the home page is loaded and I navigate to the sign-in page, it looks like it focuses then immediately blurs, triggering the validation on the field.

I'm using v1.0.5 with Angular v1.5.0.

**Comment by dongorous** [comment]
I want my input field to be focused when i change "md-tab" or md-tab-selected

I tried also md-autofocus and md-autofocus="autofocus" on both the input itself and the md-input-container. None of the combinations worked.

**Comment by francittadini** [comment]
@EladBezalel - I'm having this problem too. I'm trying to focus an input when loading a simple form, and as @Kizmar, I tried all the combinations without success. I updated @SnakeME's [codepen](http://codepen.io/francittadini/pen/wGPZNw) to show that neither autofocus or md-autofocus are working on text inputs or textareas (using Angular 1.4.8 and Angular Material 1.1.0-rc2).

So we are trying to implement a whole form using Angular Material and we keep running into this issues with basic functionality, like we did with https://github.com/angular/material/issues/4233. 

It's very frustrating that these basic behaviors aren't working and are not even considered important. I don't get what needs to be discussed on this issue and how a P1 issue is still in the backlog.

**Comment by angryfatkid** [comment]
+1

**Comment by johnyricalde** [comment]
Having the same issue!

+1

**Comment by LiyinZ** [comment]
having the same issue that by calling .focus() the coloured bottom border doesn't appear. It does set the cursor inside the input and works for typing but no material bottom border.

**Comment by srinivasmangipudi** [comment]
I am neither able to set or remove focus from mddialog input element on mobile browsers. When the dialog is shown it randomly focuses on any one element, during which time the keyboard tries to come up and the dialog repositions,but then the focus goes away and the keyboard disappears and the dialog stays without focus.

So the whole interaction is very jerky currently. is there a fix for either forcing focus on one element so the keyboard stays either open or close?

**Comment by francittadini** [comment]
@srinivasmangipudi - I'm using this workaround for setting the focus upon activation. I haven't tested on mobile browsers though.

```
function setDefaultFocus() {
    if (scope.activated) {
        angular.element('textarea[name=name]').focus();
    } else {
        $timeout(function () {
            setDefaultFocus();
        }, 300);
    }
}
```

**Comment by smbowler** [comment]
I'm having an issue using ng-repeat and md-bottomsheet. I'm repeating a series of cards and each card has a bottom sheet. When I activate the bottomsheet on one card, it only ever pulls open the bottomsheet on the first card. 

I believe the error has to do with my mis-use of md-autofocus. Let me know if I should open a new thread.  Thanks

**Comment by BryceMehring** [comment]
@dongorous, I'm also needing this autofocus behavior on input elements when the current md-tab is switched.

**Comment by adnanrahic** [comment]
Is there any progress regarding this issue? I need to focus a textarea when the current md-tab is switched.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by runninghare** [comment]
It looks like you must trigger the _focus_ event for twice to make it work because Angular Material redefined <input> as its own directive and the original event was intercepted.

As a workaround, you can define a new attribute directive and add following code to the link function: `        link: Function = (
            scope: ng.IScope,
            elem: JQuery,
            attrs: ng.IAttributes,
            controller: {},
            transclude: ng.ITranscludeFunction
        ) => {
            this.$timeout(() => {
                $(elem).trigger("focus");
                $(elem).trigger("focus");
            }, 2500);
        };`

I set the time out to 2.5 seconds because I want to wait for all elements to be fully rendered.

**Comment by cms103** [comment]
I came across the same issue with menus (button at the bottom of a menu of checkboxes taking focus and causing scrolling when the menu is opened).  It's a hack, but the following fixed it for me:

```
index de1daf9..2b31e81 100644
--- a/src/components/menu/js/menuController.js
+++ b/src/components/menu/js/menuController.js
@@ -102,8 +102,8 @@ function MenuController($mdMenu, $attrs, $element, $scope, $mdUtil, $timeout, $r
         nestedMenu && nestedMenu.open();
       }
     }, nestedMenu ? 100 : 250);
-    var focusableTarget = event.currentTarget.querySelector('.md-button:not([disabled])');
-    focusableTarget && focusableTarget.focus();
+    // var focusableTarget = event.currentTarget.querySelector('.md-button:not([disabled])');
+    // focusableTarget && focusableTarget.focus();
   };
 
   this.handleMenuItemMouseLeave = function() {
```

**Comment by kumardippu** [comment]
Kindly user "cdkFocusInitial" attribute in input field where you want to focus.
`<mat-form-field>
        <input matInput placeholder="username" #usernameInput cdkFocusInitial>
</mat-form-field>`

**Comment by Splaktar** [comment]
@kumardippu Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
