### ISSUE TITLE
Draggable md-chip

### ISSUE THREAD

**Issue by davidmillercode** [angular/material#5336]
Are there any plans to implement this feature on md-chip in the near future?  I have been trying to get this to work so that I can drag and drop the chips and reorder their order in an array with different libraries, but there are many collisions which are making it difficult to get the feature to work without serious hacking.  Any suggestions on how to implement this feature on my own / suggested libraries that can complement material?  Any help is seriously appreciated.

**Comment by ivan7237d** [comment]
+1

**Comment by steffi80** [comment]
+1

**Comment by mangrish** [comment]
+1

**Comment by stalinb87** [comment]
+1

**Comment by sridharspeaks** [comment]
Though this is not a 100% solution, the below link is a good library for this purpose.
[](https://github.com/angular-ui/ui-sortable)

**Comment by KaPaHgaIII** [comment]
+1

**Comment by homerjam** [comment]
+1

**Comment by homerjam** [comment]
I made a directive which can be added to the chip template to add drag/drop reordering, it could do with some refining but in case it's useful to anyone [here it is](https://gist.github.com/homerjam/aec5bb1c68a3bfb0ae95c1b83344a4cf).

**Comment by alisonmsmith** [comment]
+1

**Comment by ruisebastiao** [comment]
+1

**Comment by eniniz** [comment]
+1

**Comment by mikewagz** [comment]
+1

**Comment by lmeng-keystone** [comment]
+1

**Comment by albertpeiro** [comment]
+1

**Comment by postmeback** [comment]
+1
