### ISSUE TITLE
md-tooltip: in md-content or element with overflow auto gets cut

### ISSUE THREAD

**Issue by happschinson** [angular/material#5337]
Hi,

Some parts of my md-tooltip are getting cropped by another element. 
I tried:

md-tooltip{
z-index: 99999 !important;
}

but the problem still persists. How can I make sure, the tooltip is always on top layer?

**Comment by EladBezalel** [comment]
Can you please provide a codepen so we can investigate more?

**Comment by jb29** [comment]
I've got the same problem.

When you hover over the icons in the left sidenav in [this codepen](http://codepen.io/anon/pen/MaVNRe) you get some ugly horizontal and vertical scrollbars and the tooltips get clipped.

**Comment by EladBezalel** [comment]
@happschinson is your problem is the same as @jb29?

@jb29 As we can't anticipate any use case, this one is this [user responsibility](http://codepen.io/EladBezalel/pen/pjVEKv).

**Comment by Dimanoid** [comment]
Simple and common use case - vertical toolbar of md-icon-buttons. http://codepen.io/anon/pen/PPdrwV

**Comment by ThomasBurleson** [comment]
I think when the tooltip directive finds a parent ( using `parent        = $mdUtil.getParentWithPointerEvents(element),`, that parent's computed width should be inspected.  If tool narrow, then:

* use the body as the parent
* attach scroll listener to autohide the tooltip upon scroll.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
