### ISSUE TITLE
flex-* attributes do not watch variables

### ISSUE THREAD

**Issue by epelc** [angular/material#5338]
The `flex-*` attributes specifically `flex-order` do not watch variables for changes.

My use case is changing the order of some elements depending on what state you come from. But you can't update the `flex-order` using a variable if you go to a child state then do something which would update the order and come back to the original parent state.

Note `flex-order="{{someVar}}"` works the first time it is binded. But it doesn't get any updates. Also `flex-order="someVar"` just adds a class `flex-order-somevar`.
![image](https://cloud.githubusercontent.com/assets/5204642/10700114/abf8a3f0-7989-11e5-983e-484a7d869681.png)

This probably also affects the `layout-*` attributes but I think it's less likely you would need this for the `layout-*` attributes.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
