### ISSUE TITLE
Updated to 1.0.0-rc, md-dialog has strange behavior, it does not close if there is a popup inside.

### ISSUE THREAD

**Issue by hughred22** [angular/material#5339]
Here is my site updated to 1.0.0-rc: https://actorreels.stamplayapp.com/#/actor-test2/matthew-del-negro

Reproduct the problem: When you first open the page and click on any image of the image slider, the dialog box will popup. When you click the social share button, the share popup will show up. Close the share popup and then try to close the md dialog popup, it does not close the md dialog. The console does log the cancel action is fired and the backdrop is close but not the dialog.

But when I refresh the page and try it again, I can close the dialog. It only happen in the first time. I test this on chrome. This problem only show up after I updated to 1.0.0-rc1. And the behavior seem unpredicable. Something the dialog can be closed, but something (especially for first time load), it will not close. 
BUT, the dialog never close if I test this on mobile safari iOs 9. The bug is consistent there - when click the social share and open a new tag window and go back to the page. The dialog can not be closed.

**Comment by oliverzy** [comment]
I've seen a similar issue like this.

For the first time, the ng-click event will fire twice for some reason, it only happen in the emulator mode.
I think that's root cause
