### ISSUE TITLE
Sidenav scrolling issue

### ISSUE THREAD

**Issue by AgentJohnson** [angular/material#5342]
I've tried numerous variations of designs with my fixed navbar and expandable sidebar and am continually getting the same issue. The issue is when you're viewing on a small screen then open and close the sidenav, the scrolling of the page resets. I've looked at various other issues that are similar but none of the solutions seem to help. Is this a common issue?

**Comment by EladBezalel** [comment]
Can you please provide a codepen so we can investigate more?
