### ISSUE TITLE
md-autocomplete/md-selected-item-change is fired on scrolling md-virtual-repeat

### ISSUE THREAD

**Issue by kylemacfarlane** [angular/material#5344]
Here's a Codepen fork of one of the docs examples: http://codepen.io/anon/pen/KdQYLN Open the console and you will see the change events getting fired whenever the virtual repeat adds new rows.

In my real project I also sometimes get the following traceback when scrolling past md-autocompletes that call a remote service:

    TypeError: Cannot read property 'toLowerCase' of undefined
        at ie (angular-material.min.js:formatted:8628)
        at angular-material.min.js:formatted:8425
        at u (_angular.js:14745)
        at _angular.js:14761
        at p.$eval (_angular.js:15989)
        at p.$digest (_angular.js:15800)
        at i.updateBlock_ (angular-material.min.js:formatted:8211)
        at i.virtualRepeatUpdate_ (angular-material.min.js:formatted:8181)
        at i.containerUpdated (angular-material.min.js:formatted:8138)
        at o.handleScroll_ (angular-material.min.js:formatted:8089)

**Comment by kylemacfarlane** [comment]
As a workaround for this I made up ``updateScope_`` add a variable to the scope and then remove it 50ms later. If that variable is present then I block ``handleSearchText`` and ``selectedItemChange`` from fully firing.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (423/400 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:39500 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZm-001Z85-Fc
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:20 +0200
Date: Thu, 28 Apr 2016 13:27:48 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875268;
	bh=1mPqRGQKNApuMWQz0e2xOel8HLG6yjvfq28UnGyTk9Q=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=BEXD1kZEtzVzuD22RpZe0YY0ZK1bo/nTWEZeGU4fFbOecCBi7xiwZGtlmJ0FJA6+O
	 MOc8H43zC6NqPZLh9/Dm9+MKMT9Oug6H3hFGuU7BI1E/WRKh38hdiSC5habiRO8NCJ
	 AAhzKp5ZZLXWSnckJDmF2XW5mouFZLeIqQE0+gwI=
