### ISSUE TITLE
When I use layout-wrap with flex="33", cell wrapping creates unwanted space at the end of rows in 1.0.0-rc1

### ISSUE THREAD

**Issue by Dotneteer** [angular/material#5346]
Take a look at this code, and render it with a medium screen:

```html
<!DOCTYPE html>
<html lang="en" >
<head>
  <title>Simple Layout</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport"
        content="initial-scale=1, maximum-scale=1, user-scalable=no" />
  <link rel="stylesheet"
        href="./lib/angular-material/angular-material.css"/>
  <link rel="stylesheet"
        href="http://fonts.googleapis.com/css?family=Roboto:400,500,700,400italic">
  <style>
    div.flex, div.flex-25 {
      border: 1px dotted gray;
      background-color: #FFE0B2; /* Orange 100 */
      text-align: center;
      padding: 16px;
    }

    div.layout-row, div.layout-columm {
      background-color: #90CAF9; /* Blue 200 */
    }
  </style>
</head>
<body ng-app="myApp"
  layout="column">
<div layout="row" layout-sm="column">
  <div flex>Cell #1</div>
  <div flex>Cell #2</div>
  <div flex>Cell #3</div>
</div>
<div layout="row" layout-wrap
     style="margin-top:24px;">
  <div flex="25"
       flex-md="33"
       flex-sm="50">Cell #4</div>
  <div flex="25"
       flex-md="33"
       flex-sm="50">Cell #5</div>
  <div flex="25"
       flex-md="33"
       flex-sm="50">Cell #6</div>
  <div flex="25"
       flex-md="33"
       flex-sm="50">Cell #7</div>
  <div flex="25"
       flex-md="33"
       flex-sm="50">Cell #8</div>
  <div flex="25"
       flex-md="33"
       flex-sm="50">Cell #9</div>
</div>

<!-- Angular/Material scripts -->
<script src="./lib/angular/angular.js"></script>
<script src="./lib/angular-animate/angular-animate.js"></script>
<script src="./lib/angular-aria/angular-aria.js"></script>
<script src="./lib/angular-material/angular-material.js"></script>

<!-- App-specific scripts -->
<script type="text/javascript">
  angular
      .module('myApp', ['ngMaterial'])
</script>
</body>
</html>
```

You can see what the issue is:

![simple_layout_-_google_chrome_2015-10-24_10-48-59](https://cloud.githubusercontent.com/assets/4783390/10709844/89e1b5b8-7a3d-11e5-96be-5e59756f55a8.png)

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by Dotneteer** [comment]
I can confirm that this issue still exists. Here is the CodePen: http://codepen.io/Dotneteer/pen/zvWOKj

**Comment by Splaktar** [comment]
This is because 33 x 3 is 99 and not 100. Currently, if you want all 3 elements to share exactly the same space, you can just use `flex` like you did in your first grid, but this requires that you only have 3 elements per row.

Another alternative is using 33, 34, 33 like in this [CodePen](http://codepen.io/Splaktar/pen/zvWxZN). This will look a little off if placed close to another table using 3 `flex` items like the first table in this CodePen.

I think that real solution is for angular-material's CSS to do something like this:

    max-width: calc(100% / 3)

Which you can test in that CodePen by uncommenting out the one line. The SCSS will need to be a little smarter about this to avoid breaking the other media queries, but it should solve this issue and may remove the need for 33/34 and 66/67.

**Comment by Dotneteer** [comment]
Splaktar, I understand what you explain :-). My issue is that the same markup used to work earlier flawlessly (in release 0.10.x). I totally agree with you, the sugested CSS would be a solution. In my approach only 33 and 66 should exists with the meaning of 1/3 and 2/3 of the full size.

**Comment by Splaktar** [comment]
Looks like that works. @ThomasBurleson I put together a quick PR that seems to do the trick. Tested on Chrome, Firefox, and Safari.
