### ISSUE TITLE
bug(md-checkbox): ngChecked directive not working

### ISSUE THREAD

**Issue by breandr** [angular/material#535]
According to the doc:

> The checkbox directive is used like the normal angular checkbox.

But I am unable to get ngChecked working.

**Comment by sudeshnaDatta** [comment]
How to use md-checkbox to select an entire row when used inside a grid

**Comment by Elfayer** [comment]
+1, This is a real big issue. It's a regression from angularJS.

**Comment by DarkMerge** [comment]
+1

**Comment by kamikaze942** [comment]
+1

**Comment by ThomasBurleson** [comment]
@Elfayer - are you saying that this issue has not been fixed with the latest codebase in `master`? If that is the case, please submit a new issue with a codepen demo. thank you.
