### ISSUE TITLE
How do I remove the grey overlay for mdSideNav?

### ISSUE THREAD

**Issue by rcholic** [angular/material#5352]
I found `$mdSidenav` very handy for building a component in my project, but I would like to see how to remove the grey overlay (backdrop ?) when the panel slides in (active). Could someone point me to where I can configure or override the grey overlay? Thanks

**Comment by Splaktar** [comment]
Questions are best handled on the forums: https://groups.google.com/forum/#!forum/ngmaterial

That grey panel is there as an area to click to dismiss the sidenav. You can remove it by always having the sidenav open (best for larger screens) via `md-is-locked-open`. 

More details here: https://material.angularjs.org/latest/api/directive/mdSidenav

**Comment by morokolo** [comment]
In future try this :  `  <md-sidenav  class="md-sidenav-left" md-component-id="left" md-disable-backdrop>`
