### ISSUE TITLE
md-datepicker with key input won't fire a change event

### ISSUE THREAD

**Issue by Thomas-P** [angular/material#5353]
Hi,

in the actual version md-datepicker fires a ng-change event only, if you select a date with the mouse. If you enterred it with the keyboard it won't be updated. That have a side effect on ng-messages, because they will be only updated with a ng-change event. A correct enterred date with keyboard will not be accepted.

**Comment by Thomas-P** [comment]
This problem is also in version 1.0.0-rc2.

**Comment by jelbourn** [comment]
@Thomas-P this should be fixed now, and I added a test to check it in 3c9ba380628e0159bfec01ff1343c1d9c63f42ce

**Comment by Thomas-P** [comment]
thanks, i will test it soon.
