### ISSUE TITLE
The promise returned by $mdToast.show() is resolved to undefined in case of timeout in 1.0.0-rc1

### ISSUE THREAD

**Issue by Dotneteer** [angular/material#5355]
The documentation of `$mdToast.show()` says this about the returned promise:

"`A promise that can be resolved with $mdToast.hide() or rejected with $mdToast.cancel(). $mdToast.hide() will resolve either with a Boolean value == 'true' or the value passed as an argument to $mdToast.hide(). And $mdToast.cancel() will resolve the promise with a Boolean value == 'false'`"

In previous versions it worked as specified above. When the toast was hidden after timeout (no user action, no programmatic dismissal), the response value of the resolved promise was set to `true`:

```javascript
$mdToast.show(toast).then(
  function(response) {
    // response is true in case of timeout
  });
```

In 1.0.0-rc1, response is undefined, as demonstrated by this codepen: http://codepen.io/Dotneteer/pen/zvWpdo

(Click Show, and wait for the 2 seconds timeout to expire)

**Comment by EladBezalel** [comment]
@Dotneteer can you address the specific version it worked?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by achuinard** [comment]
Is it not worth updating the documentation that the promise successfully resolves with `undefined`? As of now, the docs are just off.
