### ISSUE TITLE
1.0.0-rc1 to npm repo please

### ISSUE THREAD

**Issue by kamalpatel125** [angular/material#5357]
Hi,

Could you please put 1.0.0-rc1 to npm repository ? 

Regards,

Kamal.

**Comment by tontonAurel** [comment]
:+1:

**Comment by kamalpatel125** [comment]
Great ! Thanks a lot.

**Comment by kamalpatel125** [comment]
It is still not in npm. Does it take some time to reflect your changes ? 

Thanks 

Kamal.

**Comment by ThomasBurleson** [comment]
The team will look into this today.

**Comment by kamalpatel125** [comment]
Great ! Thanks a lot.

Regards,

Kamal.

**Comment by ThomasBurleson** [comment]
While AngularJS does this, Angular Material has not published RC(s)
versions into NPM.
Angular Material releases often include grid Layout and component CSS
changes. We are concerned that our RC-<xxx> versions could adversely
surprise developers after NPM updates.

> As such, we are not planning on publishing any 1.0-rc-<xxx> releases to
NPM.

On Mon, Oct 26, 2015 at 10:19 AM, kamalpatel125 <notifications@github.com>
wrote:

> Great ! Thanks a lot.
>
> Regards,
>
> Kamal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/5357#issuecomment-151171078>.
>



-- 
*Thomas Burleson*
Mindspace LLC

http://www.gridlinked.info
http://www.linkedin/in/ThomasBurleson
https://github.com/ThomasBurleson
