### ISSUE TITLE
autoWrap in mdDialog

### ISSUE THREAD

**Issue by morriq** [angular/material#5360]
How does it work?

If I do something wrong let me know.

http://jsfiddle.net/4b9smat2/77/

After pressing custom dialog, there is error in console and it won't close anymore.

**Comment by EladBezalel** [comment]
When you're not providing a template with `<md-dialog>` element in it you HAVE to use `autoWrap: true` (or not mention it at all as the default value is true).

mdDialog won't work with out `<md-dialog>` element.

to fix your code, delete `autoWrap` or add containing element `<md-dialog>` to your template.
