### ISSUE TITLE
Default chip template should follow Material Design spec for deletable chips

### ISSUE THREAD

**Issue by sarod** [angular/material#5364]
Default chip template does not follow the [Material Design Spec] (https://material.angularjs.org/HEAD/demo/chips) for "deletable chips".

The demo example with a custom chip template is more inline with the spec but the remove button is of the wrong size.

**Comment by topherfangio** [comment]
I think the spec (http://www.google.com/design/spec/components/chips.html#) may have changed recently as I don't remember seeing some of those styles the last time I looked.

Looks like we just need to make some CSS adjustments to get it back into conformance with the guidelines.
