### ISSUE TITLE
input does not lose focus on button click

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5365]
1.0.0-rc1

in chromes device emulator, focus into input then click button.

input maintains focus.

http://codepen.io/0101adm/full/mexjgq/

**Comment by EladBezalel** [comment]
Can confirm - also on chrome on LG G3.

**Comment by robert-maftei** [comment]
This worked for me without modifying the framework (v1.0.5): disable clickHijack in app config
Example:
https://github.com/angular/code.material.angularjs.org/blob/master/HEAD/partials/api/material.core.gestures/service/$mdGestureProvider.html

**Comment by 0101adm** [comment]
@robert-maftei :+1: works.

**Comment by woodywood997** [comment]
Works

**Comment by stephengardner** [comment]
Is there a fix for this built in yet? I see the temporary fix.

**Comment by jelbourn** [comment]
Also reported by at least one Google team
