### ISSUE TITLE
GridList inside another gridList not working

### ISSUE THREAD

**Issue by mimani** [angular/material#5367]
I am trying to have a GridList inside another gridList, but the inside grids are not showing up. I tried in multiple ways, here is my [codepen](http://codepen.io/anon/pen/pjLZZq).

**Comment by RolandHeath** [comment]
This [codepen](http://codepen.io/RolandHeath/pen/NGMdNv?editors=110) has enough extra css to get it working, but there's still a lot of traps, and a lot of things to be learnt. When this issue gets resolved, it'll probably actually end up breaking my html :P

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
