### ISSUE TITLE
0.11.4 Datepicker background

### ISSUE THREAD

**Issue by denkomanceski** [angular/material#5369]
With 0.11.4 CDN the datepicker's CSS is bugged: http://prntscr.com/8vll55
With 0.11.0 Works fine: http://prntscr.com/8vlldi

Edit: There is a problem with the .js file, the 0.11.4 css files works fine with 0.11.3 js file

**Comment by chr22** [comment]
This is fixed in 1.0rc1

**Comment by topherfangio** [comment]
Closing since it's fixed in 1.0rc1, please comment if you are still seeing it after upgrading and we will reopen.
