### ISSUE TITLE
Differntiate inside single theme.

### ISSUE THREAD

**Issue by SanderElias** [angular/material#537]
I need to build an app that needs to be in one color-scheme. What I mean by this, I can only set the theme once, on the highest level. Inside my app, I need a way to differentiate my elements.

I looked for some styles like this:
  md-warn
  md-danger
  md-primary
  md-secondary 
  md-error
  md-success

But I could not find those! Found quite some nice things while reading trough the material css and scss files, but somehow I seemed to have missed out on these!

Als0 it would be nice to have access to the color palette as defined in the [design spec](http://www.google.com/design/spec/style/color.html#color-color-palette). It would be really handy to have things like this:

  md-color-50, md-color-100 etc,
  where both the color and the background color, would be set as in the color palette.

**Comment by rschmukler** [comment]
JS based theming implemented in 0.7.0 - let us know what you think guys!

**Comment by klaszlo** [comment]
@rschmukler: The theme colors available only within <md-*> element.
Is this expected?

I would expect css rules available which only defines the colors.
Something like this:
.md-THEME_NAME-fg-400 {
color: #29b6f6;
}
.md-THEME_NAME-bg-400 {
background-color: #29b6f6;
}

The same for 400,500,600,700,800,900,A100,A200,A400,A700.

The main usecase would be readily available theme colors *outside* of <md-*> elements.

**Comment by ilanbiala** [comment]
If what @klaszlo is saying is correct, then it would be great to make the necessary changes so it works outside of md elements.

**Comment by SanderElias** [comment]
@rschmukler, as @klaszlo is saying, it only works inside (selected) <md-*> elements. We need a solution so that the colors are available outside those elements too. 
And under a generic name too. 
and example:
```
   <div class='md-hue1'>Hues are for <span class='md-accent'>backgrounds</span> right?</div>
```
This should be colored according to the selected theme! In my tests this does not.

**Comment by slaivyn** [comment]
:+1: I need that too :)
how can I set a div background to "md-primary md-hue1" without hardcoding the value in the CSS file?

**Comment by opraatnitt** [comment]
I am new for Material design. Can anyone explain to me how i will change my default theme to someother.

Thanks in advance

**Comment by epelc** [comment]
@opraatnitt add `md-theme="otherTheme"` to any element to change its theme. It should be mentioned in the theme docs or under directives of you need more info.

**Comment by mbitson** [comment]
I'm a little behind here, but I believe that this is the wrong approach. If you want 'functional' colors, such as one to warn users, don't modify the css for the current theme- just apply a 'warning' theme to that particular element. This allows you to pick any hue of your warning theme to ensure your contrast on the page, as well as chose a secondary palette just in case you need some dark warnings and some light. If creating the themes is taking too long, you could create many angularJS material design themes easily using this tool I created before:
https://github.com/mbitson/mcg

Cheers!
