### ISSUE TITLE
menuContents has zero items

### ISSUE THREAD

**Issue by loganfreeman** [angular/material#5370]
In menuDirective.js, the link function call mdMenuCtrl.init. 

if the md-menu-item is hard coded, like in the case of demoBasicUsage, then in menuController.js this will return items : 'menuContainer[0].querySelectorAll('md-menu-item')'.

if the md-menu-item is not hard coded, like in the case of demoMenuPositionModes and demoMenuWidth, then in menuController.js this will return zero items: 'menuContainer[0].querySelectorAll('md-menu-item')'.

```javascript
  function link(scope, element, attrs, ctrls) {
    var mdMenuCtrl = ctrls[0];
    var isInMenuBar = ctrls[1] != undefined;
    // Move everything into a md-menu-container and pass it to the controller
    var menuContainer = angular.element(
      '<div class="md-open-menu-container md-whiteframe-z2"></div>'
    );
    var menuContents = element.children()[1];
    menuContainer.append(menuContents);
    if (isInMenuBar) {
      element.append(menuContainer);
      menuContainer[0].style.display = 'none';
    }
    mdMenuCtrl.init(menuContainer, { isInMenuBar: isInMenuBar });

    scope.$on('$destroy', function() {
      mdMenuCtrl
        .destroy()
        .finally(function(){
          menuContainer.remove();
        });
    });

  }
```

**Comment by loganfreeman** [comment]
if you look at the demo, the demoBasicUsage works correctly regarding highlighting, but for demoMenuPositionModes and demoMenuWidth , the highlight is wrong. opening a menu and move the mouse around, two menu items are highlighted at the same time, which is not correct.

**Comment by RolandHeath** [comment]
In both master and head, [menu](https://material.angularjs.org/1.0.0-rc1/demo/menu) I can confirm this issue occurs on the docs page. 
The basic demo works normally, but in the second demo, the first item is highlighted even if you mouse over another element. 

I noticed that focussing an element with the arrow keys seemed to work normally, but mouse hover events don't seem to un-highlight correctly.
