### ISSUE TITLE
should have semicolon before self-invoking function

### ISSUE THREAD

**Issue by loganfreeman** [angular/material#5374]
the angular.material.js under bower_components/angular-material has no semicolon before self-invoking function, breaking code when concating libraries.

```javascript
/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v0.11.4
 */
(function( window, angular, undefined ){
```

**Comment by EladBezalel** [comment]
@loganfreeman i spoke with the team and we decided that if you want to concatenate our library with others, then you should concatenate properly.
