### ISSUE TITLE
Ionic click auto-detection doesn't seem to work with android version 4.4.4?

### ISSUE THREAD

**Issue by janejanejane** [angular/material#5375]
I'm using angular-material for the toast service but it interferes with the click event of ionic.
I found: **Resolve Gesture conflicts with Ionic Framework #2365** discussing the auto-detection for ionic events. But it does not work on the phone. When I added **skipClickHijack()** in the config, it resolved the problem. 
Is something wrong with the setup of this project that I had to use the manual call? Please help.
Thanks.

_**Here are the settings:**_
AngularJS v1.4.3
Angular Material Design v0.11.4
Ionic v1.1.0
Android v4.4.4

**Comment by ThomasBurleson** [comment]
Currently, we do not support Angular Material - Ionic hybrids.
