### ISSUE TITLE
md select inside the md dialog, the md-options is at the back of the md dialog.

### ISSUE THREAD

**Issue by aavielmd** [angular/material#5376]
The problem is the when I clicked the md-select inside the md-dialog, the md-options appeared at the back of the md-dialog thus the options for the select could not be seen clearly. Thanks for the help.

**Comment by aavielmd** [comment]
My temporary fix is to increase the z-index for the md-select-menu-container and md-backdrop-select. Is that correct? or any other fix?

**Comment by bastienJS** [comment]
Please create a codepen/plunker to repro the behavior, thanks.

**Comment by rschmukler** [comment]
Based on [this demo](http://codepen.io/rschmukler/pen/WQgKBR) it appears to be working. Please open a new issue with a demo if it persists. Thanks!

**Comment by jbdemonte** [comment]
We also had this problem, but it was our fault, we had this piece of css:

    .md-dialog-container {
          z-index: 1000;
    }

**Comment by Anujndls** [comment]
Please use this piece of code it will work because I have faced this  issue.
  .md-select-menu-container {
            z-index: 99999 !important;
        }

**Comment by gvorster** [comment]
Using

`.md-select-menu-container {
           z-index: 99999 !important;
}`

I can see the select box in the dialog window, but I cannot close it anymore.
This happens for me in FF 57.0 and Chrome 62.0

**Comment by b3hz4d** [comment]
`.cdk-overlay-container{ z-index: 1051 !important; }`

**Comment by Splaktar** [comment]
@b3hz4d Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
