### ISSUE TITLE
iconSets use <g> elements which cannot contain viewBox attributes, suggest switching to <symbol>

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#5378]
When creating an icon set ( merging a group of icon files into one file ) you might take a couple of svg's like this

```
<svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" viewBox="0 0 36 36">
    <path d="M0 0h36v36H0z" fill="none"/>
    <path d="M4 27h28v-3H4v3zm0-8h28v-3H4v3zM4 8v3h28V8H4z"/>
</svg>

<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
    <path d="M0 0h24v24H0z" fill="none"/>
    <path d="M6 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm12">
</svg>
```
Which needs to be converted to something like 
```
<svg>
  <defs>
    <g id="menu">
        <path d="M0 0h36v36H0z" fill="none"/>
       <path d="M4 27h28v-   3H4v3zm0-8h28v-3H4v3zM4 8v3h28V8H4z"/>
    </g>
    <g id="more_horizontal">
      <path d="M0 0h24v24H0z" fill="none"/>
      <path d="M6 10c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm12"/></g>
  </defs>
</svg>
```
Before it can be used with iconSet or defaultIconSet. The problem with using the ```<g>``` container is that it does not recognize the viewBox attribute.

I suggest two changes

1. Extract the viewBox and default width/height properties from the containing ```<svg>``` if present, and assign them to all the svg's in the set as the default. I suggest using the width/height if present because some sets don't scale and it's nice to have that set size show as designed without resorting to css unless necessary

2. Use```<symbol>``` instead of ```<g>``` see: https://css-tricks.com/svg-symbol-good-choice-icons/ which allows the use of viewBox 

This would create less friction in trying to use svg icon sets out of the box without the developer having to figure svg formats and settings in the service etc.

**Comment by Frank3K** [comment]
Related: #1514 and #1548.

**Comment by Todd-Werelius** [comment]
Interestingly enough the svg element IS picked up and can of course use all the attributes that `<g>` or `<symbol>` cannot use, the following format works fine using $mdIconProvider (on the most modern browsers anyway) 

```xml
<svg>
  <defs>
    <svg id="menu" viewBox="0 0 24.00 24.00" width="24" height="24">
      <path ..."/>
   </svg>
   <svg id="more-vert"  viewBox="0 0 24 24" width="24" height="24">
     <path ..."/>    
   </svg>
  </defs>
</svg>
```
At this point I am not sure if `<g>` or `<symbol>` are really necessary at all, this would depend on browser support and if there are any benefits to using the other elements.   

Using [gulp-svg-material](https://github.com/Todd-Werelius/gulp-svg-ngmaterial) to create icon sets from the material design svg's using this format works great as of 1.0.0.rc-1

I swore I tried this format and it didn't work, but apparently I either mucked the test file up or something changed between the 0.11x/1.2.x versions of angular and angular material that I was using and this, and most likely it was the former ;-)

**Comment by programmist** [comment]
@Todd-Werelius:  Based on your last comment I'm going to close this one.  If I've misunderstood, please feel free to re-open.  Thanks for your feedback!

**Comment by Todd-Werelius** [comment]
Yep, works for me!
