### ISSUE TITLE
IE11 : layout-column> flex-100 isn't having any height

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#5382]
http://codepen.io/anon/pen/avGvQz
On latest version, on IE11, with sm-md size, the content of the card is out of the card.
Reason seems to be due to  
`.layout-column > .flex-100, .layout-column > .flex-100{
       flex-basis:100%;
    }`
Going to flex-basis : auto seems to resolve the issue ?

May be duplicate of https://github.com/angular/material/issues/1923

**Comment by Wardormeur** [comment]
Issue seems to be also reproducible with layout-sm="column" instead of layout="column"

**Comment by johnnyluu** [comment]
I had a similar issue. Try avoiding flex-100, worked for me.

**Comment by Wardormeur** [comment]
Issue is also affecting android stock browser and Safari 9(AppleWebkit)

**Comment by ThomasBurleson** [comment]
With RC5, everything appears to be working correctly. If you want all the cards to have the same height (in column mode), then adjust your `md-card {  min-height: 250px; }` CSS.

http://codepen.io/team/AngularMaterial/pen/qOeoQL

**Comment by Wardormeur** [comment]
It's still an issue for IE11, but no more for Android default browser
That's a good start :)
However, by using flex=100 it's still broken (even on Android browser) so that using flex is more likely to be a workaround that should be coupled with some CSS width/height; which defeat a bit the flex logic ;)
It's on the good way, keep it up !

**Comment by ThomasBurleson** [comment]
@EladBezalel - can you help me investigate this on IE11 ?

**Comment by ThomasBurleson** [comment]
While the team is investigating appropriate workarounds for the IE lack of support for flexbox, please review this:

* [Known Issues with flexbox on IE](http://caniuse.com/#feat=flexbox) - Select the "Known Issues" tab at the bottom.
* [Workarounds for IE Flexbox Issues](https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers)

**Comment by ThomasBurleson** [comment]
Fixed: 

![screen shot 2015-12-05 at 12 28 23 pm](https://cloud.githubusercontent.com/assets/210413/11609422/f716fa6a-9b4b-11e5-8a2f-53428ca92117.png)

![screen shot 2015-12-05 at 12 28 12 pm](https://cloud.githubusercontent.com/assets/210413/11609424/f8dc6d44-9b4b-11e5-828e-9e51ed2b54a2.png)


[CodePen Demo](http://codepen.io/team/AngularMaterial/pen/qOeoQL?editors=101)
[CodePen Layout Collection](http://codepen.io/collection/XExqGz/)

**Comment by Wardormeur** [comment]
A bit surprised by the fix, (it seems to work on IE, didn't teste yet on Android). Just for curiosity, was  61bb6c4 the only fix or was there another commit inbetween RC5 and RC6 that fixed it ?
Thanks a lot anyway :)

**Comment by ThomasBurleson** [comment]
*  When using "column" mode, container heights cannot be indeterminant. 
* The `['ngMaterial']` module dependency is now always required for the Material Layout directives to work properly.

**Comment by Wardormeur** [comment]
For those still having difficulties with flex-100 on android default browser, replacing with flex-auto seems to fix it
