### ISSUE TITLE
groups sass into one folder

### ISSUE THREAD

**Issue by Duovili** [angular/material#5385]
why is the sass not grouped into one folder when I bower install I only get one sass file with everything in it. And if I download the zip then I have to pull each file out. Is this done on purpose?

**Comment by EladBezalel** [comment]
@Duovili I think this is more [forum](https://groups.google.com/forum/#!forum/ngmaterial) question than an issue,
the sass is separated and grouped with every component.
I don't want to go through all of my scss file searching for, lets say, tooltip scss.

I hope you got your answer, if not please move it to the forum.
