### ISSUE TITLE
md-menu: destroying any md-menu on the page will close any (other) open md-menu

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#5395]
As the title states, if you have an open md-menu, and you destroy a md-menu item anywhere on the page, this will close your md-menu. This could happen if you have dynamic data with md-menu items (for example in a list).

Here's the codepen:

http://codepen.io/anon/pen/RWyoEb

Just click the button and wait.

Edit: 

Here's a second codepen which has the second md-menu already created:

http://codepen.io/anon/pen/xwjgZe

**Comment by rschmukler** [comment]
@clshortfuse any chance you could submit a PR with your fixes? Otherwise I can add them in myself. Let me know!

**Comment by clshortfuse** [comment]
@rschmukler I probably won't get around to it any time soon. Feel free to use the code in my fork.

**Comment by rschmukler** [comment]
@clshortfuse sounds good, thanks
