### ISSUE TITLE
md-chips should have a callback option for de-select

### ISSUE THREAD

**Issue by codegoblins** [angular/material#5397]
I am working on an application where multiple cards are displayed below chips, and I would like selecting a chip to highlight correlated cards, but so far I have no way of knowing when the chip is deselected so I can reset the highlighted cards back to the default state.

**Comment by topherfangio** [comment]
This sounds like a useful addition, but I'm not sure we have the bandwidth to provide it before the 1.0 release. If you were interested in contributing, a PR would definitely be welcome :smile:
