### ISSUE TITLE
Unexpected token punc

### ISSUE THREAD

**Issue by riapp** [angular/material#5398]
The error happened when trying to `gulp build`

`[12:27:34] Plumber found unhandled error:
 Error in plugin 'gulp-uglify'
Message:
    d:\Projects\GitHub\material\dist\angular-material.js: Unexpected token punc
«;», expected punc «,»
Details:
    fileName: d:\Projects\GitHub\material\dist\angular-material.js
    lineNumber: 22861`

**Comment by topherfangio** [comment]
Can you provide a few more details about this issue? Are you running the `gulp build` command in the material project or your own? What version are you using?

Have you tried updating everything to the latest versions?

**Comment by skovalyov** [comment]
I get the same error when running `gulp build` in the material project. I have to mention though that I had to update _gulp-sass_ to the latest version, because version _1.3.3_ specified in _package.json_ fails to install at least with _Node v4.2.1_ with this error:

```
Can not download file from https://raw.githubusercontent.com/sass/node-sass-binaries/v2.1.1/darwin-x64-node-4.2/binding.node
```

**Comment by skovalyov** [comment]
#5145 is the same?

**Comment by FDIM** [comment]
I just ran into the same issue, applying change that was done here: https://github.com/angular/material/pull/5173 fixes it.

**Comment by riapp** [comment]
git clone git@github.com/angular/material.git
cd material
npm install
gulp docs

**Comment by riapp** [comment]
That did a trick https://github.com/brujo696/material/commit/84bc1292711e477069961143c105be6cd7437c3f
thanks.
