### ISSUE TITLE
md-select with two track by values

### ISSUE THREAD

**Issue by AndreasHo** [angular/material#5403]
Hello,

is there a chance to do a track by with two values?

i have a old select with ng-options:
item.Text for item in items track by (item.Id && item.Adress.Id)

this works fine... but now i want to use angular material :)
Following code doesn't work :/

`<md-input-container>`
     `<label>Item Select</label>`
     `<md-select ng-model="ctrl.SelectedItem" ng-model-options="{ trackBy: '($value.Id &&   
       $value.Adresse.Id)' }">`
           `<md-option ng-repeat="item in items" value="{{item}}">`
                `{{item.Text}}`
           `</md-option>`
     `</md-select>`
`</md-input-container>`

When somebody have a idea how i can solve this problem, please answer :)

Bye

**Comment by tati-li** [comment]
Hi,
for multiple trackBy use object expression
change to:
ng-model-options="{ trackBy: {Id: '$value.Id', Adresse: {Id: '$value.Adresse.Id'}}"

Hope this helps you
