### ISSUE TITLE
$mdDialog put body up when debugger is open

### ISSUE THREAD

**Issue by sina-mirhejazi** [angular/material#5404]
when dialog showed up body get fixed position and a top position that make sense because of scrolling stuff.

but when debugger is open on bottom of the page (tested on chrome) it calculates wrong top position and let bottom of the page to be white!
it's not like this even when debugger is on side of the page.

so i think it's because of the way it measures scroll offset or maybe difference between $document and $window offsets.

**Comment by ThomasBurleson** [comment]
Fixed in latest v1.0.0-rc2 release
