### ISSUE TITLE
Editable divs do not work in a md-list-item

### ISSUE THREAD

**Issue by thecas** [angular/material#5406]
Pressing the spacebar does not result in a space in a editable divs (e.g. TextAngular) in md-list-item nodes.
INPUT and TEXTAREA are already ignored (see #2668) but there is no check for editable divs.

Patch to fix the behaviour:
https://github.com/Pluxbox/material/commit/6cb9a373c90bb437620b86ca05187c8162b25bd9

**Comment by nielslucas** [comment]
+1 This really needs to be fixed

**Comment by dennislaupman** [comment]
+1

**Comment by DevVersion** [comment]
As there was never a demo provided... here is one http://codepen.io/DevVersion/pen/rxRjwW
