### ISSUE TITLE
Grunt build breaks ng-chips readonly?

### ISSUE THREAD

**Issue by johnnyluu** [angular/material#5410]
Not sure if it's a problem with grunt or angular material, when I use grunt build on a project with angular material, it changes all the  'readonly = "true"' on md-chips to just "readonly", which of course doesn't work any more.

I'm using grunt v0.4.5, grunt cli v0.1.13, and angular material v0.11.2.

Can anyone please help me check if you could reproduce the same error? If so, any way to solve it? Thanks!!

**Comment by johnnyluu** [comment]
Actually, never mind. Fixed it right after I posted this. For anyone having the same problem, change collapseBooleanAttributes under htmlmin in your gruntfile to false.

**Comment by MaximShoustin** [comment]
+1

**Comment by fabiusss** [comment]
+1
