### ISSUE TITLE
mobile + md-fab + md-toolbar z-index

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5414]
1.0.0-rc-1

![untitled screencast 3](https://cloud.githubusercontent.com/assets/5133412/10795615/368255e6-7d60-11e5-8643-6e7b6bf3cf45.gif)

**Comment by EladBezalel** [comment]
Can you please provide a codepen so we can investigate it more?

**Comment by 0101adm** [comment]
@EladBezalel 

realized i didnt use md-toolbar.   just a plain div.

that toolbar needs a z-index higher than the fab.  so this is not an issue w/ the framework.
