### ISSUE TITLE
md-select with rtl and small screen width is not displayed right

### ISSUE THREAD

**Issue by roidayan** [angular/material#5415]
ltr:

![screenshot_9](https://cloud.githubusercontent.com/assets/660126/10798277/92f334ae-7daf-11e5-8baa-aec316d3aadb.png)

rtl:
![screenshot_10](https://cloud.githubusercontent.com/assets/660126/10798279/97597508-7daf-11e5-9f22-6f31560f5dde.png)

http://codepen.io/anon/pen/VvxdLB?editors=100

Move the editor separator to ~370px.

**Comment by EladBezalel** [comment]
@roidayan Bi-directional support is milestoned to post 1.0
#1080 is all about that..

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
