### ISSUE TITLE
Flexible-width sticky md-subheader breaks on resize

### ISSUE THREAD

**Issue by seanemmer** [angular/material#5420]
Once scrolling has been initiated, i.e. an md-subheader-wrapper is "active," resizing the window width causes subheader to malfunction.  Specifically the "sticky" subheader is not replaced by the "next" subheader at the appropriate scroll height.

**Comment by topherfangio** [comment]
Any chance you could provide a simple Codepen showing the issue so that we can see it in action and find a proper fix?

**Comment by seanemmer** [comment]
Yes, here you go:

[http://codepen.io/anon/pen/EVRyYp]

If you start with the screen wide and then narrow it, the subheaders start to misbehave due to the changed height of the text content.

**Comment by agepath** [comment]
@topherfangio I posted a demo above - can you please confirm that you are seeing the issue and update the label.

**Comment by seanemmer** [comment]
@topherfangio I posted a demo above - can you please confirm that you are seeing the issue and update the label.

**Comment by topherfangio** [comment]
@seanemmer Indeed; thanks for pining me again.

**Comment by davidimbas** [comment]
hello, I have a similar problem, in my case I can add items into the subheader content, when I do, the subheader gets stuck and I have a similar behavior as described above, I use the code provided by the subheader demo, and add a button in the toolbar to add messages. Here is the pen

http://codepen.io/davidimbas/pen/GZGLQq

**Comment by Kroderia** [comment]
Why is this issue closed? I am still facing this problem with the latest releast v1.1.0-rc.5.

**Comment by craigivemy** [comment]
Seems this has been closed without it actually being fixed - is there any explanation for this? It renders md-subheader totally useless in situations using ng-repeat?
