### ISSUE TITLE
Tabs running ng-tasty table function twice

### ISSUE THREAD

**Issue by kevinlbatchelor** [angular/material#5421]
I can't seem to figure  this out. When i add a ng-tasty table to the material tabs I get my function called twice when the page loads. https://github.com/Zizzamia/ng-tasty/issues/176. I posted the issue in both places because I'm not sure who's issue it is.

http://jsfiddle.net/s46gs95e/

**Comment by ThomasBurleson** [comment]
Will not support.

**Comment by kevinlbatchelor** [comment]
It was fixed by the good people at ngtasty
https://github.com/Zizzamia/ng-tasty/issues/176
