### ISSUE TITLE
md-backdrop does not animate on angular 1.4.x

### ISSUE THREAD

**Issue by mramanauskas** [angular/material#5422]
md-backdrop does not animate on angular 1.4.x when app is bootstraped manually. I have created codepens for this, where animation is used to open dialogs:

manual bootstrap: http://codepen.io/rmarius/pen/MaGLXo (animation does not work)

ng-app attribute bootstrap: http://codepen.io/rmarius/pen/PPeVRY (animation works ok)

**Comment by ThomasBurleson** [comment]
Use:

```js
angular.element(document).ready(function() {
  var body = document.getElementsByTagName("body")[0];
  angular.bootstrap(body, ['myApp']);
});
```

**Comment by d3lm** [comment]
@ThomasBurleson What is the reason for the `md-backdrop` not being animated? I have the same issue when I add the `ng-app` attribute to the html element. It's not animating at all. However, when I add the attribute to the body tag, its working. Do you know why? Haven't had time to dive into the code and would be interested to know why the backdrop is behaving like this.
