### ISSUE TITLE
layout-padding/margin still not work on flex="xx"

### ISSUE THREAD

**Issue by Herobs** [angular/material#5425]
I have tried all versions after 0.11.1, include the newest 1.0.0-rc1, this problem still exists, directive `flex="xx"` generate class `.flex-xx`, not include `.flex`.

Or I use in a wrong way?

http://codepen.io/Herobs/pen/GpdLvQ

#5014 #5156

**Comment by ThomasBurleson** [comment]
**layout-margin** and **layout-padding** were not being applied to child containers unless the *.flex* class was present. This has been fixed.

* layout-margin and layout-padding now affect immediate children
* layout-margin suffixes are supported (-sm, -gt-sm, -md, -gt-md, -lg, -gt-lg)
* layout-padding suffixes are supported (-sm, -gt-sm, -md, -gt-md, -lg, -gt-lg)

> With 'layout-margin', developers may need to override the child container flex sizes. See http://codepen.io/team/AngularMaterial/pen/BoVBaE for details.

**Comment by sbondor** [comment]
@ThomasBurleson 
What about the case where you only want the parent layout container to have margin or padding?
If used to work like this if you didn't add flex to any child, like it's stated in the docs.
