### ISSUE TITLE
Preserve time when selecting a date using the datepicker

### ISSUE THREAD

**Issue by remcohaszing** [angular/material#5426]
The `mdDatepicker` directive resets the time when selected. It would be useful if this would be preserved on a form where a user may select an entire datetime. This is also how an `<input type="date"/>` element works.

The following example allows setting the date and time using the input fields. When the `mdDatepicker` is used, the time is reset.
```html
<md-datepicker ng-model="vm.datetime"></md-datepicker>
<md-input-container md-no-float>
  <md-icon md-font-icon="mdi-clock"></md-icon>
  <input type="date" ng-model="vm.datetime" aria-label="Time"/>
</md-input-container>
<md-input-container md-no-float>
  <md-icon md-font-icon="mdi-clock"></md-icon>
  <input type="time" ng-model="vm.datetime" aria-label="Time"/>
</md-input-container>
{{vm.datetime}}
```

**Comment by Pelu2k12** [comment]
+1

**Comment by byronh1016** [comment]
+1

**Comment by ThomasvLingen** [comment]
+1

**Comment by cleever** [comment]
+1

**Comment by CreativelyMe** [comment]
+1

**Comment by Lacrymology** [comment]
Why was this deprecated? it's clearly bad behavior and makes for a lot of repeated (and annoying) code

**Comment by Lacrymology** [comment]
At least some kind of explanation would be nice
