### ISSUE TITLE
md-menu does not disappear on mobile device when ngTouch is present.

### ISSUE THREAD

**Issue by lucasmartinez** [angular/material#5427]
http://codepen.io/anon/pen/eprwYM

Open this URL in Chrome. Press F12 and select Toggle device mode button. Reload codepen url and press menu button. After that select any menu option.
Alert is shown but manu is not destroyed.

**Comment by 0101adm** [comment]
+1

**Comment by rschmukler** [comment]
ngMaterial includes the much more powerful `$mdGesture`. Is there a reason you need `ngTouch`?

**Comment by lucasmartinez** [comment]
I need to include ngTouch to remove delay on ngClick on mobile devices.

**Comment by lucasmartinez** [comment]
What is this for $mdGesture ? I can't find any doc related to that service.

**Comment by rschmukler** [comment]
`$mdGesture` also takes care of removing the delay on `ngClick`. For now, I'd recommend not using ngTouch while we work on compatibility.
