### ISSUE TITLE
Disable/delay for md-autocomplete md-progress-linear

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#5428]
When using md-autocomplete is used with a remote data source an md-progress-linear is shown while the data is loaded.

This is a nice touch, but in practise I find the progress bar annoying when most queries complete relatively quickly.

I've disabled the progress bar using the following css:
``md-autocomplete > md-autocomplete-wrap > md-progress-linear {
    display: none;
}``

It would be nice to have an option that controlled whether the progress bar was used at all.

Even better would be a delay for it to trigger.  That way, quick queries (<0.3s?) that feel near instant anyway wouldn't bother showing the progress bar and slower queries can give feedback that something really is happening.

**Comment by tucq88** [comment]
+1

**Comment by p-mcgowan** [comment]
+1

**Comment by rguruprakash** [comment]
+1

**Comment by ogz00** [comment]
+1

**Comment by revmischa** [comment]
+1

**Comment by revmischa** [comment]
What was the resolution on this @ThomasBurleson ?
