### ISSUE TITLE
md-virtual-repeat with customized scrollbar

### ISSUE THREAD

**Issue by arshdefoamed** [angular/material#5429]
md-virtual-repeat is turning out to be really useful for managing large lists. As an enhancement can the team add a customizable scroll bar ? I could not find any library which could provides both virtual scroll and a customised scrollbar. The possible inspiration for the requested functionality can be as follows: 
- https://github.com/mattbalmer/mb-scrollbar
This library provides a neat scroll bar but takes too much processing in IE. 
- https://github.com/kamlekar/slim-scroll
This library uses the explorer's default scrollbar for scrolling purpose and hides it by adding a  custom div over it .

**Comment by EladBezalel** [comment]
dup #5064
