### ISSUE TITLE
static input field

### ISSUE THREAD

**Issue by cm0s** [angular/material#5431]
I'm missing a static text field in my forms.

Like the one in bootstrap: 
http://getbootstrap.com/css/#forms-controls-static

Here is another example in a template using material design (look at the bottom of the first two forms) : http://www.codecovers.eu/materialadmin/forms/basic

Unfortunately I didn't find anything in the material design spec. However, I think it's a common use case.

It could be implemented like this :
```html 
<md-input-container>
  <label>Title</label>
  <p>Static text</p>
</md-input-container>
```
Or perhaps putting a static text in an input container isn't really semantic...

What do you think ?

**Comment by Wardormeur** [comment]
Isn't that the goal of input[disabled] ?

**Comment by cm0s** [comment]
I don't think the purpose is the same. Disabled input means the input may be modifiable, but for a  specific reason it's currently not possible to modify it. In contrary, a static content will never be modifiable.
