### ISSUE TITLE
md-select: md-select-menu positioned above control 

### ISSUE THREAD

**Issue by fridolin-koch** [angular/material#5435]
I'm using the async variant of `md-select`. Instead of the menu appearing directly over the `md-select` it appears a few pixels above. The bug only occurs if it contains only a few elements.

![screen shot 2015-10-29 at 18 37 00](https://cloud.githubusercontent.com/assets/1880828/10826875/153ca19a-7e6c-11e5-8700-77fb1cc0c2b5.png)

This bug seems to be related to my layout, am I using the containers wrong or is this a bug?

I've created a codepen http://codepen.io/anon/pen/VvdZYx

**Comment by EladBezalel** [comment]
Did you tried it outside of code pen?
If we change the `body` element in your example to `div` it's [working](http://codepen.io/EladBezalel/pen/ZbRegQ)
If you didn't tried it outside please check, i'm sure it's working.

**Comment by fridolin-koch** [comment]
Yep, the issue comes from the app I'm currently developing. I tried to replicate the problem inside Codepen to make the issue more feasible.

The actual code looks like that:

```html
<body layout="column">
  <stm-navbar></stm-navbar>
  <div layout="row" flex>
    <!-- Sidebar -->
    <stm-sidenav layout="column"></stm-sidenav>
    <!-- Content container -->
    <div layout="column" class="ui-view-container" flex style="overflow: auto">
      <md-progress-linear ng-show="$appLoading" md-mode="indeterminate"></md-progress-linear>
      <stm-breadcrumbs></stm-breadcrumbs>
      <div ui-view></div>
    </div>
  </div>
</body>
```

**Comment by fridolin-koch** [comment]
It seems like the issue is not related to a certain layout or browser:

Chrome:

![chrome_1](https://cloud.githubusercontent.com/assets/1880828/10932660/cc51ab7c-82d2-11e5-84b4-33f0878448d0.png)
![chrome_2](https://cloud.githubusercontent.com/assets/1880828/10932659/cc519f1a-82d2-11e5-9a4b-4ae3fdd18347.png)

Firefox:

![firefox_1](https://cloud.githubusercontent.com/assets/1880828/10932657/cc4f67d6-82d2-11e5-85c5-e8e62238c580.png)
![firefox_2](https://cloud.githubusercontent.com/assets/1880828/10932658/cc507a04-82d2-11e5-8863-23e72f307bfb.png)

Here is the example code used: https://gist.github.com/fridolin-koch/2c9fc5b24a5f558a9ca1

**Comment by EladBezalel** [comment]
It's odd, I had a look on this but nothing formal yet, I'm on it.

**Comment by rschmukler** [comment]
@EladBezalel assigning to you only because you claimed it. Feel free to kick it back to me if you're no longer investigating

**Comment by chayutzee** [comment]
I have this issue too . 
@fridolin-koch like you say it only happen when have few of options in my case is two .
I use md-select in my md-tabs . 

sample image  
![screen shot 2558-11-13 at 1 50 00 pm](https://cloud.githubusercontent.com/assets/1681564/11140512/dbc6b48e-8a0d-11e5-8760-1e60c8024b30.png)

but if i have more options it will render collectly
![screen shot 2558-11-13 at 1 55 53 pm](https://cloud.githubusercontent.com/assets/1681564/11140550/4760403e-8a0e-11e5-8882-55ab542a63cc.png)

**Comment by jschlieber** [comment]
Similar problem here... The options are just floating on top of the page, no matter where the md-select is, no matter how many options, no matter whether async or not...

**Comment by EladBezalel** [comment]
@rschmukler can you take a look at this also?

**Comment by rschmukler** [comment]
I'm having trouble recreating this issue. Using the code from @fridolin-koch I made [this demo](http://codepen.io/rschmukler/pen/XmQMbJ?editors=101) which appears to be working. Can you guys try on master and confirm that this issue still exists? If it does, can someone please supply me with a demo that I can work from

**Comment by EladBezalel** [comment]
@rschmukler when upgrading your codepen to angular 1.4.7 (which is what he uses in his [demo](http://codepen.io/anon/pen/VvdZYx)) it's seems to be broken..

**Comment by fridolin-koch** [comment]
The behaviour slightly changed in *v1.0.0-rc5* using angular.js *1.4.8*. Notice the options are less detached from the control.

v1.0.0-rc5: http://codepen.io/fridolin-koch/pen/QjXOxg
v1.0.0-rc4-master-5e5e6cd: http://codepen.io/fridolin-koch/pen/dYBZKB

**Comment by jlmagee** [comment]
this or some variation of it occurs on the doc site. in Demo of Basic Address select of State
the first selection positions the options correctly
subsequent attempts at selection position the options at various vertical positions relative to top of something depending on how far down the option list is currently selected.

if the md-select element is lower on the page, the behavior is even more bizarre

**Comment by jlmagee** [comment]
in      function calculateMenuPositions(scope, element, opts) {
this calculation
        transformOrigin = (centeredRect.left + targetRect.width / 2) + 'px ' +
          (centeredRect.top + centeredRect.height / 2 - contentNode.scrollTop) + 'px 0px';

uses contentNode.scrollTop which is always zero when selecting (re-opening) the select menu after it has been populated because contentNode is a hidden element appended at the bottom of the body

I haven't figured out what the calculations are trying to do but there is some never dead code in this function which doesn't make it easier.

**Comment by jlmagee** [comment]
@rschmukler @jelbourn 
Well, other code considerations aside, the issue seems to be that isScrollable is not set properly. I moved it and the other line to immediately after all the initial variable settings, as follows

      // give the container some shape befor depending on it
      containerNode.style.display = 'block';
      var isScrollable = contentNode.scrollHeight > contentNode.offsetHeight;

Seems to work as expected now. I'll continue testing in various window sizes and let you know if I find anything else.

**Comment by albertosantini** [comment]
I confirm with 1.0.0 I am getting the same issue (codepen with Scooby Doo above) in my app.

Recap:

- with an horizontal resize causes the option list to be placed where intended
- setting `ng-selected="$index == 0"` the option list is ok

Any workaround?

(my `md-select` snippet seems quite standard, I hope)
```
        <md-input-container>
            <md-select ng-model="vm.selectedGranularity" aria-label="Granularity"
                ng-change="vm.changeChart(vm.selectedInstrument, vm.selectedGranularity)">
                <md-option ng-value="granularity"
                    ng-selected="granularity == vm.selectedGranularity || $index == 0"
                    ng-repeat="granularity in vm.granularities">
                    {{ granularity }}
                </md-option>
            </md-select>
        </md-input-container>
```

**Comment by albertosantini** [comment]
In Material 1.0.1, my use case is fixed. Thanks!

**Comment by fridolin-koch** [comment]
I'cant confirm this, in 1.0.1 the behaviour is still different from "regular" selects:

http://codepen.io/fridolin-koch/pen/ZQOpXN

![untitled](https://cloud.githubusercontent.com/assets/1880828/11929505/ebb242e6-a7db-11e5-959a-998b4b29d8f7.gif)

**Comment by timmyrosen** [comment]
I'm also having this issue, and only on async selects that already have a selected option. I'm using v1.0.4

**Comment by ismarslomic** [comment]
+1

**Comment by Michsior14** [comment]
+1

**Comment by p-mcgowan** [comment]
+1

**Comment by macdasi** [comment]
+1
Why there isn't any property for 'md-select-menu' position ?
My work around for opening below the input is:

$provide.decorator('$mdSelect',['$delegate','$timeout','$interval', function($delegate,$timeout,$interval) {
            var origShow = $delegate.show;
            var stop;
            $delegate.show = function(){
                var onShow = origShow.apply(this, arguments);
                onShow.then(function(){
                    $interval.cancel(stop);
                    stop = undefined;
                });
                var selectInput = arguments[0].target;
                var selectDropDown = arguments[0].element;
                //angular.element(selectDropDown[0]).find('md-select-menu')[0].style.display = 'none';
                $timeout(function(){
                    var boundings = selectInput.getBoundingClientRect();
                    selectDropDown[0].style.left = boundings.left + "px" ;
                    selectDropDown[0].style.top = (boundings.top + boundings.height) + "px";
                    var dropDownBoundings = selectDropDown[0].getBoundingClientRect();
                    if(dropDownBoundings.width < boundings.width){
                        selectDropDown[0].style.width = boundings.width + "px";
                    }
                    //angular.element(selectDropDown[0]).find('md-select-menu')[0].style.display = '';
                    stop = $interval(function(){
                        selectDropDown[0].style.left = boundings.left + "px" ;
                        selectDropDown[0].style.top = (boundings.top + boundings.height) + "px";
                    },13);
                },60);
                return onShow;
            };

            return $delegate;
        }]);

**Comment by macdasi** [comment]
+1
My work around for opening below the input is:


> $provide.decorator('$mdSelect',['$delegate','$timeout','$interval', function($delegate,$timeout,$interval) {
>             var origShow = $delegate.show;
>             var stop;
>             $delegate.show = function(){
>                 var onShow = origShow.apply(this, arguments);
>                 onShow.then(function(){
>                     $interval.cancel(stop);
>                     stop = undefined;
>                 });
>                 var selectInput = arguments[0].target;
>                 var selectDropDown = arguments[0].element;
>                 //angular.element(selectDropDown[0]).find('md-select-menu')[0].style.display = 'none';
>                 $timeout(function(){
>                     var boundings = selectInput.getBoundingClientRect();
>                     selectDropDown[0].style.left = boundings.left + "px" ;
>                     selectDropDown[0].style.top = (boundings.top + boundings.height) + "px";
>                     var dropDownBoundings = selectDropDown[0].getBoundingClientRect();
>                     if(dropDownBoundings.width < boundings.width){
>                         selectDropDown[0].style.width = boundings.width + "px";
>                     }
>                     //angular.element(selectDropDown[0]).find('md-select-menu')[0].style.display = '';
>                     stop = $interval(function(){
>                         selectDropDown[0].style.left = boundings.left + "px" ;
>                         selectDropDown[0].style.top = (boundings.top + boundings.height) + "px";
>                     },13);
>                 },60);
>                 return onShow;
>             };
> 
>             return $delegate;
>         }]);

**Comment by macdasi** [comment]
+1
My work around for opening below the input is:

```
$provide.decorator('$mdSelect',['$delegate','$timeout','$interval',          function($delegate,$timeout,$interval) {
            var origShow = $delegate.show;
            var stop;
            $delegate.show = function(){
                var onShow = origShow.apply(this, arguments);
                onShow.then(function(){
                    $interval.cancel(stop);
                    stop = undefined;
                });
                var selectInput = arguments[0].target;
                var selectDropDown = arguments[0].element;
                //angular.element(selectDropDown[0]).find('md-select-menu')[0].style.display = 'none';
                $timeout(function(){
                    var boundings = selectInput.getBoundingClientRect();
                    selectDropDown[0].style.left = boundings.left + "px" ;
                    selectDropDown[0].style.top = (boundings.top + boundings.height) + "px";
                    var dropDownBoundings = selectDropDown[0].getBoundingClientRect();
                    if(dropDownBoundings.width < boundings.width){
                        selectDropDown[0].style.width = boundings.width + "px";
                    }
                    //angular.element(selectDropDown[0]).find('md-select-menu')[0].style.display = '';
                    stop = $interval(function(){
                        selectDropDown[0].style.left = boundings.left + "px" ;
                        selectDropDown[0].style.top = (boundings.top + boundings.height) + "px";
                    },13);
                },60);
                return onShow;
            };

            return $delegate;
        }]);
```

**Comment by jayeshanandani** [comment]
The issue still seems to be persist in 1.0.5. The dropdowns are pretty inconsistent.

**Comment by shuyye** [comment]
Can confirm this issue, it seems stable when it's about 4-5 items but when it's 10+ it shoots up to the top

**Comment by jayeshanandani** [comment]
Even with 4 items it seems to go up. Attached is the screenshot of the image.

1.) Dropdown opens on top of select.

<img width="1076" alt="screen shot 2016-03-06 at 9 38 16 pm" src="https://cloud.githubusercontent.com/assets/3860787/13555329/fa540534-e3e3-11e5-8d0b-2be7d3b195f9.png">

2.) If below option is selected the first options go inside toolbar due to dropdown issue:

<img width="1119" alt="screen shot 2016-03-06 at 9 38 29 pm" src="https://cloud.githubusercontent.com/assets/3860787/13555339/15c5e0c6-e3e4-11e5-99d4-456c86cfbd1c.png">

<img width="1020" alt="screen shot 2016-03-06 at 9 38 49 pm" src="https://cloud.githubusercontent.com/assets/3860787/13555338/15c54774-e3e4-11e5-81fc-007b50b5d271.png">

**Comment by davidtmnolan** [comment]
Issue exists in 1.0.7 after loading items from async call.  .md-select-menu-container breaks outside of container and spans entire page.

**Comment by jayeshanandani** [comment]
The issue still exists in latest master version. It makes select options unclickable due to the wrong positioning.

**Comment by jayeshanandani** [comment]
@ThomasBurleson Is this issue open to PR?

**Comment by Sacred90** [comment]
In version 1.0.6 i have the same problem, there is way to fix this ? 
![image](https://cloud.githubusercontent.com/assets/8612345/16681665/68b9736a-44f6-11e6-9417-6d5c4b966ff1.png)

**Comment by haneefatel** [comment]
I have the same issue in angular-material v1.1.1, it appears only when I scroll the window to bottom.  suggest any fix.

**Comment by sdawson26** [comment]
Same issue here on v1.1.1 as @haneefatel. If i put a md-menu inside of a dialog box, it jumps out of place if i scroll to the bottom of the list to select something

**Comment by Khomitskyi** [comment]
@haneefatel Had the same issue, Modified macdasi provider so it forces dropdown go upward when it's close to bottom of the page.
`$provide.decorator('$mdSelect',['$delegate','$timeout','$interval', function($delegate,$timeout,$interval) {
            var origShow = $delegate.show;
            var stop;
            $delegate.show = function(){
                var onShow = origShow.apply(this, arguments);
                onShow.then(function(){
                    $interval.cancel(stop);
                    stop = undefined;
                });
                var selectInput = arguments[0].target;
                var selectDropDown = arguments[0].element;
                if($(selectInput).offset().top < ($(window).scrollTop() + $(window).height() - 150)) {
                    return
                }
                //angular.element(selectDropDown[0]).find('md-select-menu')[0].style.display = 'none';
                $timeout(function(){
                    var boundings = selectInput.getBoundingClientRect();
                    selectDropDown[0].style.left = boundings.left + "px" ;
                    selectDropDown[0].style.top = (boundings.top + boundings.height - selectDropDown.height()) + "px";
                    var dropDownBoundings = selectDropDown[0].getBoundingClientRect();
                    if(dropDownBoundings.width < boundings.width){
                        selectDropDown[0].style.width = boundings.width + "px";
                    }
                    //angular.element(selectDropDown[0]).find('md-select-menu')[0].style.display = '';
                    stop = $interval(function(){
                        selectDropDown[0].style.left = boundings.left + "px" ;
                        selectDropDown[0].style.top = (boundings.top + boundings.height - selectDropDown.height()) + "px";
                    },13);
                },60);
                return onShow;
            };

            return $delegate;
        }]);`

**Comment by nicolac18** [comment]
+1

**Comment by sdawson26** [comment]
+1

**Comment by matheushf** [comment]
till the day

**Comment by Splaktar** [comment]
This seems to be working fine in 1.1.7 (and possibly a few versions prior to that). Here's a [CodePen demo](https://codepen.io/Splaktar/pen/Yaqaqw?editors=1010#0) of that.
