### ISSUE TITLE
Container Element doc sample a bit confusing because it hides parents CSS

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#5436]
The [Container Elements](https://material.angularjs.org/latest/layout/container) sample is a bit confusing because it masks the CSS of the parent div which is
```html
<div class="demo-content">demo-content</div>
```
The addition of which affects the layout 

I would suggest just including a parent element in the `source` window with the layout and layout-fill elements, so that developers trying to reproduce the demo don't have to figure out what's different. 

```html
<div layout layout-fill> 
  <div layout="row">
    <div flex>First item in row</div>
    <div flex>Second item in row</div>
  </div>
  <div layout="column">
    <div flex>First item in column</div>
    <div flex>Second item in column</div>
  </div>
</div>
```
Or just change the demo so that rows and columns are shown in separate display areas.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
