### ISSUE TITLE
md-select will not fire any events on change. 

### ISSUE THREAD

**Issue by f1tech** [angular/material#5437]
I have the following md-select within an md-toolbar. 

    <md-input-container>
        <md-select ng-model="order.currentCart" ng-show="order.carts.length>0" class="md-menu" md-on-close="loadCartContents(order.currentCart)">
            <md-option ng-repeat="cart in order.carts" value="{{cart}}">
                {{cart}}
            </md-option>
        </md-select>
        </md-input-container>

I have tried onchange, ng-change, md-selected-item-change and md-on-close and none of them will fire event. 

I've also tried ng-click on each item in the select.

I am working with RC1.

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate more

**Comment by rschmukler** [comment]
Per [this demo](http://codepen.io/rschmukler/pen/avMMRO) it appears to be working. Please open a new issue with a demo if this is not the case.
