### ISSUE TITLE
allow a boolean as value for md-ink-ripple

### ISSUE THREAD

**Issue by ginader** [angular/material#5438]
it would be useful and expected behavior for a property if md-ink-ripple to not only support a hex value but also a boolean that would allow (the until now impossible) disabling of the ripple. I.e.:
`<li md-ink-ripple="options.showRipple">Lorem ipsum</li>`

CodePen - http://codepen.io/ginader/pen/PPaPym

**Comment by DevVersion** [comment]
```
InkRippleCtrl.prototype.isRippleAllowed = function () {
  var element = this.$element[0];
  do {
    if (!element.tagName || element.tagName === 'BODY') break;
    if (element && element.hasAttribute && element.hasAttribute('disabled')) return false;
  } while (element = element.parentNode);
  return true;
};
```

There is currently a watched attribute for disabling the ripple effect ```ng-disable```
I think that's a better solution for disabling the ripple effect than changing the ```color``` attribute.

**Comment by EladBezalel** [comment]
@DevVersion disabled is not good solution cause if you use `md-ink-ripple` on a button and still want it interpolated but you don't wish the button will be disabled.

**Comment by DevVersion** [comment]
Ah right, sorry my bad :).
Thanks for responding
