### ISSUE TITLE
Make material.angularjs.org searchable via search engines

### ISSUE THREAD

**Issue by johnstark** [angular/material#544]
It would be useful for material.angularjs.org to be searchable.  Currently if I run a search for "directive" no results are returned:
https://www.google.com/search?q=site%3Amaterial.angularjs.org%20%22directive%22

As an alternate example, docs.angularjs.com is searchable as shown in this search below:
https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fdocs.angularjs.org%20%22directive%22

**Comment by jelbourn** [comment]
- [ ] Change docs site to use html5Mode routing
- [ ] Change servers (local and production) to do URL-rewriting to support html5Mode
- [ ] Change URLs from entire module name to just component name (e.g., `material.components.button` to just `button`).
- [ ] Generate and upload a `sitemap.xml` file

**Comment by jelbourn** [comment]
Boom: 
![search](https://cloud.githubusercontent.com/assets/838736/10522723/a3e9412e-732b-11e5-8b74-84e530416c0e.png)
