### ISSUE TITLE
Flex column safari issue

### ISSUE THREAD

**Issue by cesar-garay** [angular/material#5441]
Hello guys, before all thanks for the amazing work!.
I have an issue with safari browser on iphone devices. When an element have the layout="column" property and the child have flex parameter, the child element is  displayed without "height" one over other.

Here is I have a codepen example, with the last version of angular-material and 1.3.9 angular version.
http://codepen.io/cesargaray/pen/EVRVje

Here I attached screenshot for an android device. ( v4.1.2 chrome 44.0)
![image](https://cloud.githubusercontent.com/assets/11696040/10833486/06fa8f84-7e71-11e5-9b40-e17d1885f4ae.png)
And here the screenshot for the iphone ( ios 9.0.2 )
![image](https://cloud.githubusercontent.com/assets/11696040/10833571/cade4562-7e71-11e5-83d6-b24cadac1d24.png)

Maybe I'm using the layout and flex property in a wrong way, if is the case please let me know.

For your information, I found a workaround fix, that is to do not put the flex property for layout columns like this.

```
<div layout="column" layout-gt-sm="row">
         <div flex-gt-sm="50"> div 1 content</div>
         <div flex-gt-sm="50"> div 2 content</div>
</div>
```

Thanks in advanced

**Comment by ThomasBurleson** [comment]
Works on desktop Safari:

![screen shot 2015-10-30 at 6 48 45 am](https://cloud.githubusercontent.com/assets/210413/10858061/1b685fdc-7f20-11e5-8cbd-bff170ae833f.png)

**Comment by BirdInTheCity** [comment]
Experiencing this issue, too.  It **doesn't** work on desktop Safari if you create a narrow browser window.




Chrome on left, Safari on right.
![screen shot 2015-11-12 at 4 57 38 pm](https://cloud.githubusercontent.com/assets/814522/11132580/ad69b8ac-895e-11e5-8670-865911f60e64.png)

**Comment by robertmesserle** [comment]
@ThomasBurleson This seems like a misuse of flexbox.  In this case, what we want is NO flexbox and just `display: block` for these elements.  The problem is that the container has no height on its own, which doesn't make sense when used with flexbox.

**Comment by robertmesserle** [comment]
@cesar-garay The correct code for this should be: http://codepen.io/anon/pen/OyrBvg?editors=100

Note that I removed the `flex-100` because what you really want is just simple `display: block` in smaller screens.

**Comment by cesar-garay** [comment]
@robertmesserle Thanks for the reply.
The fix that you propose is the same that I proposed like a workarround in my comment. I'm glad to know  that i'm in the correct way.
Thanks again!

**Comment by tucq88** [comment]
I dont think adding `display:block` to `.layout-column` is a proper fix :(

**Comment by alexilyaev** [comment]
Had a similar issue, been using `flex="50" flex-xs="100"`, fixed it by using only `flex-gt-xs="50"`, that way on the smaller screens it will fall back to normal flow.

**Comment by jascination** [comment]
I'm gonna post this on a bunch of similar issues raised here, as I've searched far and wide for a solution to this - it's still an issue in Safari on IOS, you can see it in "responsive mode" if you're on desktop safari.

The solution is to add `flex: 1 0 auto !important;` to the parent layout elements that are not correctly being filled to their children's heights. The `!important` may not be necessary, up to you.

**Comment by andreyavram** [comment]
Thanks for the solution, @jascination!
 We struggled 3 hours until we found this.

**Comment by kirby81** [comment]
Thanks a lot @jascination !

**Comment by kirby81** [comment]
Thanks a lot @jascination !

**Comment by kirby81** [comment]
Thanks a lot @jascination !
You just save my day.

**Comment by stinaq** [comment]
Yes, thank you. This is a very odd thing, and I still don't understand why it's set to works as expected? I only get it in Safari on ios. But if a container with `layout="column"` has only children that are also flexed, the parent collapses
