### ISSUE TITLE
$anchorScroll not work properly in md-tabs

### ISSUE THREAD

**Issue by Herobs** [angular/material#5446]
Use $anchorScroll goto an anchor in md-tab, the tabs head will be hided.

PS: If the content of tab is tall enough, this will never happen.

http://codepen.io/Herobs/pen/GpdLvQ

**Comment by vigneshnrfs** [comment]
+1 I've got the same issues too.

**Comment by nanchen** [comment]
got the same issue, has there been any solution to this so far?
