### ISSUE TITLE
md-virtual-container - number of row

### ISSUE THREAD

**Issue by vigneshnrfs** [angular/material#5449]
When the virtual repeat container is hidden initially and then shown, the container displays the data in a reduced height. In this codepen, it does not display any data at all. However in my application, it display 3 rows instead of eight.  I hide the content till the data is loaded from the server and then display the content.

http://codepen.io/anon/pen/pjKEvQ

**Comment by kseamon** [comment]
Dupe of #4336. Hoping to fix this week.
