### ISSUE TITLE
layout + sticky header + footer

### ISSUE THREAD

**Issue by stunaz** [angular/material#5450]
Hi all, might no be an issue.
But I having a hard time putting the footer at the bottom  with the sticky header and big content.
Note that I also want the footer to go on the bottom when the content have a little height.

here is a codepen http://codepen.io/anon/pen/gaKwgo with the footer misplaced

**Comment by reppners** [comment]
Try this http://codepen.io/anon/pen/BoVQZX

Basically put `flex` onto your `md-content` causing it to fill the space between header and footer and move the footer markup outside of md-content

**Comment by stunaz** [comment]
Thanks, but I dont want the footer to be sticky with big content

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
