### ISSUE TITLE
mdSelect multiple="false" not working as expected

### ISSUE THREAD

**Issue by willramos** [angular/material#5459]
Adding the multiple attribute works fine (does what it's supposed to do) when it is set to true. 

However, when it is set to false...
it acts as if it were still set to true, allowing the user to choose multiple selections. 

Demonstrated here: http://codepen.io/anon/pen/GpGOEo

**Comment by rschmukler** [comment]
This is because `multiple` is a flag which is assigned to true when anything is present. This keeps it consistent with a native `select`. To bind it to an attribute use `ng-multiple` instead.

**Comment by willramos** [comment]
Thanks for the explanation @rschmukler!!, I'll use ng-multiple
