### ISSUE TITLE
IE11 input padding issue

### ISSUE THREAD

**Issue by trimox** [angular/material#5461]
Commit 17797f0 seems to have broken spacing with IE11 inputs.

<b>Broken on IE11:</b>
![image](https://cloud.githubusercontent.com/assets/11887843/10854301/3c5e97d8-7f11-11e5-8f9b-6e15e2075470.png)

<b>Working on Chrome/Firefox:</b>
![image](https://cloud.githubusercontent.com/assets/11887843/10854331/63b6c67a-7f11-11e5-9d85-092938516be3.png)

**Comment by robertmesserle** [comment]
This has been resolved.
