### ISSUE TITLE
md-input-container height issues in 1.0.0-rc2

### ISSUE THREAD

**Issue by hodeyp** [angular/material#5463]
17797f001533288560854b04de81f53c552d2a80 has broken input alignment - I see there is a new md-block class to make the md-input-container fill the parent element but the ng-messages section is causing height changes when the input changes from valid to error.

**Comment by houmark** [comment]
Related to #5298

**Comment by robertmesserle** [comment]
Can you confirm that this is still broken in master?  I believe this should be fixed but not released yet.

**Comment by robertmesserle** [comment]
Ah, nevermind - just checked against the latest and this is still an issue.

**Comment by robertmesserle** [comment]
Closing as a duplicate of #5462
