### ISSUE TITLE
md-textfloat: Inaccessible <input> element

### ISSUE THREAD

**Issue by ajoslin** [angular/material#547]
When the developer uses md-textfloat, he/she doesn't have access to the input itself in the template.

What does that mean? It means that things like this won't work as expected:

```html
<md-textfloat ng-blur="doSomethingOnBlur()"></md-textfloat>
```

This is because the `ngBlur` directive is listening for the `blur` event on the `md-textfloat` container element, not the inner `input` element itself.  This will be the same for the `input`, `focus`, etc events.  

Then there are input attributes that won't work:

```html
<md-textfloat autocapitalize="off"></md-textfloat>
```

The developer will expect this to put the `autocapitalize="off"` attribute on the input, and stop auto-capitalization on mobile. But again, this attribute will stay on the container.

There are potentially hundreds of directives and attributes that could be put on the `<md-textfloat>` container that the developer will expect to be passed straight to the `<input>`. We can't manually cover them all. 

### Fixing This

The best way to fix this would be to use `replace: true` on the md-textfloat directive, then set the template to be an `<input>`. This would cause all of the attributes to be passed to a real native `<input>`.

Then we could use DOM magic to place the `<label>` element as a sibling, and remove the label when the input is removed.

**Comment by ilanbiala** [comment]
So is there a fix being implemented, or are we left to use a workaround for now?

**Comment by demisx** [comment]
+1

**Comment by shprink** [comment]
Thanks @ajoslin !

**Comment by MarcosPortugal** [comment]
So did you give up on the idea of copying the attributes? I think it would be much better to have a single line for an input rather than 4. You guys seemed to be talking about working around the errors and then a commit that just gives up on that idea comes up? I'm a little confused

**Comment by MarcosPortugal** [comment]
@gkalpak commented this "Copying attributes seems to be the way to go, but there are cases where the user will need some attributes to stay on the original element and some to be copied to the generated input. (E.g. an ngRepeat or class attribute might need to stay on the original element, while ngBlur copied to the input.) So, there should be a way to let the user differentiate between the two categories."

 That makes a lot of sense and seems like a valid reason to keep the inputs as they are right now. The one thing you could do is add this explanation to the docs, so people like me who go there and wonder why they have to add 4 lines for a directive can at least know why that way is better :smile:

**Comment by epelc** [comment]
@MarcosPortugal there are so many edge cases with copying the attributes. It makes it really hard to have good for validation and it further completes working with any third party directives.

I think the container element is a good solution it's fixed most of my problems with form validation and it makes me wish checkboxes and other elements worked this way.

**Comment by demisx** [comment]
I really like the current container approach. Though, more lines, but makes so many things straightforward. :+1:
