### ISSUE TITLE
md-scroll-shrink fails to work if angular ui-router is used

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#5472]
When setting up a tool bar to hide on scroll  adding a ui-view element from the angular ui-router library to the md-content sibling prevents the intended function from working.

For some reason it interferes with the DOM manipulation that allows the hide on-scroll functionality to behave properly.   

Removing the ui-view element allows the intended behavior

```html
  <md-toolbar md-scroll-shrink ng-if="true" class="md-whiteframe-6dp">
  </md-toolbar>

  <!-- Main Content Viewing area -->
  <md-content ui-view class="main-content">
  </md-content>
```

This [Codepen](http://codepen.io/Mopholo/pen/yYEjNQ?editors=100) shows the problem.  

In the codepen you will see that scrolling leaves the toolbar fixed in place, removing the ui-view element from the md-content sibling allows the toolbar to hide as you scroll down, as intended

This can be worked around by using an inner element instead of the md-content element as the ui-view container, at a minimum a note should be put in place in the documentation since ui-router is popular.

**Comment by hkjels** [comment]
Just replace:
```html
<md-content ui-view class="main-content">
</md-content>
```
with:
```html
<md-content class="main-content">
  <ui-view></ui-view>
</md-content>
```
`md-toolbar` requires `md-content` to be a sibling of the same `$scope`. This is a documented limitation.

**Comment by Todd-Werelius** [comment]
Yes I understand that you can work around it by embedding a ui-view within the md-content, as stated in the issue I posted, and I understand the sibling requirement as well

The question is why does adding the ui-view directive make a md-content element not an md-content element any longer? 

Doing a bit of debugging it looks like it's a timing issue, the ui-view clones and replaces the md-content element after AM has already found it

It doesn't seem reasonable that this should be the case from an _observers perspective_ because  the md-content element is still present when inspected, it's just not the element that the tool-bar is watching 

It don't think it can be fixed easily, but I still think it needs to at least be documented so people don't stumble over this, primarily because ui-router is used so widely.

**Comment by Todd-Werelius** [comment]
I also opened an issue with the ui-router team, but it seems like this is one of those edge cases that might not be easily fixed.

**Comment by gambolputty** [comment]
I don't have a solution to this. But thanks so much for pointing this out, @Todd-Werelius. I spent hours investigating why my toolbar wouldn't shrink before I finally found your post here :)

**Comment by topherfangio** [comment]
@Todd-Werelius This is the third or fourth issue we've seen recently with ui-router and Material not interacting well. We'll see if we can add some notes to the docs about this so people have a heads-up.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (402/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:49622 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZA-001YxH-VG
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:43 +0200
Date: Thu, 28 Apr 2016 13:28:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875290;
	bh=8XTPHEKyguURiZe/2z9Xd19rurI1+8LDRD0lWjSOq8g=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=xApB4xVq9QC8+cjyb2+yI8mEnHDoDwxZpTIP/+MBOQ+69xypR4hT4YJx6tiq2cWBD
	 Nk6JQOncFwrwdq5NnK5pYd0N3p/rhCvI81ubqlMVqjTsNTGCAO3jlqZbKhF88RysGr
	 Xyig+3YcymC6MLtcjbEm9vGhhgSKvMJjHQiYXqec=
