### ISSUE TITLE
Md-Fab-Toolbar Bug

### ISSUE THREAD

**Issue by viztastic** [angular/material#5474]
Hi, a couple of bugs with Md-Fab-Toolbar:

1) Doesn't work on Angular 1.3.x
2) With Angular 1.4.7, This is how it seems to behave, before clicking, on clicking, and after clicking:

Default State (Fine) :
![fabtoolbar-state_0_-_before](https://cloud.githubusercontent.com/assets/8556736/10862742/9d205f36-8009-11e5-824e-81a1968f7677.png)

On Click (Fine) :
![mdfabtoolbar-state_2_-_click](https://cloud.githubusercontent.com/assets/8556736/10862743/9e5dcd7a-8009-11e5-9cdd-d55cb3d7bdde.png)

When we click out of the menu, it reverts to a non circle shape:
![state_3_after](https://cloud.githubusercontent.com/assets/8556736/10862744/a0320440-8009-11e5-94f1-f1f70c0faee4.png)

Implementation:

```
<!DOCTYPE html>
<html lang="en" ng-app="myapp">
<head>
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="/bower_components/angular-material/angular-material.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
      
</head>
  
<body>

  <md-fab-toolbar>
      <md-fab-trigger>
        <md-button aria-label="menu" class="md-fab md-primary">
          <md-icon md-svg-src="http://localhost:3900/assets/svg/menu.svg"></md-icon>
        </md-button>
      </md-fab-trigger>
  
      <md-toolbar>
        <md-fab-actions class="md-toolbar-tools">
          <md-button aria-label="comment">
            <md-icon md-svg-src="http://localhost:3900/assets/svg/ic_person_24px.svg"></md-icon>
          </md-button>
          <md-button aria-label="label">
            <md-icon md-svg-src="http://localhost:3900/assets/svg/ic_people_24px.svg"></md-icon>
          </md-button>
        </md-fab-actions>
      </md-toolbar>
  </md-fab-toolbar>


```

Thoughts?

**Comment by kyle-massroots** [comment]
@viztastic The issue seems to be that you aren't specifying an md-direction attribute in the root <md-fab-toolbar> element. In the directive code, the background element's position doesn't seem to properly reset if it doesn't have either of the alignment classes.
```
          if (element.hasClass('md-right')) {
            backgroundElement.style.left = '0';
            backgroundElement.style.right = null;
          }

          if (element.hasClass('md-left')) {
            backgroundElement.style.right = '0';
            backgroundElement.style.left = null;
          }
```

**Comment by kyle-alex-burke** [comment]
@viztastic The issue seems to be that you aren't specifying an md-direction attribute in the root element. In the directive code, the background element's position doesn't seem to properly reset if it doesn't have either of the alignment classes.
```
          if (element.hasClass('md-right')) {
            backgroundElement.style.left = '0';
            backgroundElement.style.right = null;
          }

          if (element.hasClass('md-left')) {
            backgroundElement.style.right = '0';
            backgroundElement.style.left = null;
          }
```

**Comment by topherfangio** [comment]
@viztastic Indeed, you must set a class in order for it to work properly. Also, it looks like you are using an older version as there have been some visual tweaks that you appear to be missing (thus why you have the non-circle shape).

Can you try adding the class and updating to the latest version to see if that fixes the issue?
