### ISSUE TITLE
layout=row quit working

### ISSUE THREAD

**Issue by twomoonsfactory** [angular/material#5477]
Looking through the docs, I cannot see what the difference may be...  What works in this codepen: http://codepen.io/ajlars/pen/LprJYV
does not work in an app I'm working on (where it worked until very recently).  The row layout is not being recognized as such and is being set in a columnar fashion.  Plus if I use layout-fill on the divs that should be displayed in a row, everything outside of the toolbar are the size of the window, and go off of the bottom of the screen successively.  The classes I'm using for both right now are only color.
The only two differences (html and classes are identical) are that where the codepen floats in the "demoApp" div, my app is nested in a view in this index:
```html
<!doctype html>
<html lang="en" ng-app="gameMaster">
<head>
  <meta charset="UTF-8">
  <title>Party Things!</title>
</head>
<body>
	<script src="bundle.js"></script>
  <div ng-view class="slideup" layout-fill>
  </div>
</body>
</html>
```
Nested view that works in the codepen:
```html
<div class="purple" layout="column" layout-fill>
	<md-toolbar class="header md-tall" flex>
	</md-toolbar>
	<div class="green" flex layout="row">
		<div class="purple" flex="30">
			Hi
		</div>
		<div class="green" flex>
			there
		</div>
		<div class="purple" flex="30">
			boss
		</div>
	</div>
</div>
```
Here are the dependencies from my package.json -- versioning doesn't seem to be an issue.
```javascript
"devDependencies": {
    "angular": "^1.4.7",
    "angular-animate": "^1.4.7",
    "angular-aria": "^1.4.6",
    "angular-material": "http://github.com/angular/bower-material/tarball/master",
    "angular-mocks": "^1.3.15",
    "angular-route": "^1.4.2",
    "babel-core": "^5.8.20",
    "babel-loader": "^5.3.2",
    "css-loader": "^0.15.2",
    "file-loader": "^0.8.4",
    "jasmine-core": "^2.3.2",
    "jquery": "^2.1.4",
    "karma": "^0.13.2",
    "karma-chrome-launcher": "^0.1.12",
    "karma-jasmine": "^0.3.5",
    "karma-sourcemap-loader": "^0.3.5",
    "karma-webpack": "^1.5.1",
    "node-libs-browser": "^0.5.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^3.1.1",
    "style-loader": "^0.12.3",
    "underscore": "^1.8.3",
    "url-loader": "^0.5.6",
    "webpack": "^1.9.10",
    "webpack-dev-server": "^1.9.0"
  }
```

Am I missing something simple here?  I'm concerned, because this formatting worked perfectly before, but is broken now...

**Comment by ThomasBurleson** [comment]
This is the layout I am seeing (Chrome with Latest versions from angular/material/master):

![screen shot 2015-10-31 at 9 25 09 pm](https://cloud.githubusercontent.com/assets/210413/10866927/ee133326-8015-11e5-9268-ac62f83b121d.png)


What is wrong ?

**Comment by twomoonsfactory** [comment]
Hmm...  That's odd -- the issue that I was running into wasn't that it wasn't filling the port (I tweaked the height like you mentioned) it's that instead of the three divs in the row showing left to right, they were showing in column.
![image](https://cloud.githubusercontent.com/assets/10999456/10866980/66e61224-8010-11e5-9919-9a1c2649e393.png)

**Comment by twomoonsfactory** [comment]
The repo in question is github.com/twomoonsfactory/partythingsreceiver -- I just had someone check it out fresh, ran 'npm install' and 'npm start', hit the browser, localhost:8080, and it isn't rendering correctly for him either.

The gap between the toolbar and the div w/content should be a flex="30" to the left, mirrored to the right.  Also the content currently within the div should be flexed out space-around center in a column in that div.

![image](https://cloud.githubusercontent.com/assets/10999456/10867043/c96af958-8012-11e5-8a8f-f6122f5a1a41.png)

I'm happy to keep plugging away if this is a rookie mistake.  I just didn't notice any problem until I had to update my packages yesterday.

**Comment by twomoonsfactory** [comment]
I'm going to take down some of the info I left up here -- if you have any questions/are able to look at it more, let me know.  Otherwise, I appreciate your help this far.
