### ISSUE TITLE
Datepicker date format doesn't respect angular locale

### ISSUE THREAD

**Issue by guilhermecvm** [angular/material#5478]
Months and weeks are correctly translated but date format does not respect angular i18n. Doesn't make sense setting $mdDateLocaleProvider if I want to use the same format as angular locale.

**Comment by jelbourn** [comment]
@guilhermecvm I tried to do this originally by ran into some kind of incompatibility, but I don't remember exactly what it was. I'll look again to remember.

**Comment by rkmax** [comment]
is this bug is related to a problem I found?

![captura de pantalla de 2015-11-03 00-28-32](https://cloud.githubusercontent.com/assets/395707/10901721/bd684826-81c1-11e5-851c-dcb45e88f2b9.png)


as you can see tuesday is 3 nov but datepicker show as 2 nov. this is my setup

```js
function configLang($mdDateLocaleProvider) {

  $mdDateLocaleProvider.months = [
    'enero', 'febrero', 'marzo',
    'abril', 'mayo', 'junio',
    'julio', 'agosto', 'septiembre',
    'octubre', 'noviembre', 'diciembre'
  ];

  $mdDateLocaleProvider.shortMonths = [
    'ene', 'feb', 'mar',
    'abr', 'may', 'jun',
    'jul', 'ago', 'sep',
    'oct', 'nov', 'dic'
  ];

  $mdDateLocaleProvider.days = [
    'lunes', 'martes', 'miercoles', 'jueves', 'viernes',
    'sabado', 'domingo'
  ];
  $mdDateLocaleProvider.shortDays = [
    'Lu', 'Ma', 'Mi', 'Je', 'Vi', 'Sa', 'Do'
  ];

  $mdDateLocaleProvider.parseDate = function(dateString) {
    var m = moment(dateString, 'L', true);
    return m.isValid() ? m.toDate() : new Date(NaN);
  };
  $mdDateLocaleProvider.formatDate = function(date) {
    return moment(date).format('L');
  };
  $mdDateLocaleProvider.monthHeaderFormatter = function(date) {
    return $mdDateLocaleProvider.shortMonths[date.getMonth()] + ' ' + date.getFullYear();
  };
  $mdDateLocaleProvider.weekNumberFormatter = function(weekNumber) {
    return 'Semana ' + weekNumber;
  };
  $mdDateLocaleProvider.msgCalendar = 'Calendario';
  $mdDateLocaleProvider.msgOpenCalendar = 'Abrir calendario';
}
```

**Comment by jelbourn** [comment]
@rkmax I think you rproblem has something to do with missing the utc offset. See https://github.com/angular/material/issues/4636#issuecomment-155784355

@guilhermecvm Angular's $locate stuff has _some_ of the info we need for the provider, but not all of it (especially WRT messages needed for accessibility). Since people would have to use `$mdDateLocaleProvider` anyway, I think it's better to require explicit configuration.
