### ISSUE TITLE
<md-input-container> alignment issue with ng-messages

### ISSUE THREAD

**Issue by hodeyp** [angular/material#5479]
If you have multiple `<md-input-container>` elements in the same row and one has ng-messages and one doesn't they no longer align correctly...

<img width="893" alt="screen shot 2015-10-31 at 08 34 07" src="https://cloud.githubusercontent.com/assets/1916471/10868514/6a327ae4-8088-11e5-8bd4-603664f60185.png">

**Comment by no-more** [comment]
Hi,

I'm not sure if this is a bug, or an improvement. I've seen the change recently, md-input-container without message takes less height than those with. In my case this was an improvement as it was taking too much space. The counter part is you can't mix both on same line.

**Comment by gpopovic** [comment]
I hoped difference in height with ng-messages and without was a bug..

**Comment by robertmesserle** [comment]
@hodeyp Can you please provide a CodePen demo?  I believe this has been resolved in master and just hasn't made its way into a release yet.

**Comment by robertmesserle** [comment]
Closing for now, will reopen when demo is provided.

**Comment by sunnyshah01** [comment]
+1
