### ISSUE TITLE
ink ripple is incorrectly positioned depending on the scroll position of the page

### ISSUE THREAD

**Issue by jonathantyates** [angular/material#548]
The ink ripple moves down the page as you scroll down
## Without scrolling

![screenshot 2014-11-05 23 29 00 1](https://cloud.githubusercontent.com/assets/3408947/4930935/b78fb98c-656d-11e4-8def-6dd0490f8e6e.png)
## With scrolling

![screenshot 2014-11-05 23 29 13](https://cloud.githubusercontent.com/assets/3408947/4930942/c8afb60e-656d-11e4-9ae6-7d068dd38af5.png)

**Comment by aeroxy** [comment]
I see this topic as "ready" so I assume there is already a fix. What is the solution? I still observe this problem.
