### ISSUE TITLE
Ripple bug with option-groups

### ISSUE THREAD

**Issue by stavro** [angular/material#5481]
* Angular Material 1.0.0-rc2
* Angular 1.4.6

Having an option group within a div within a menu has odd ripple effects.  The ripple does not go away.

![ripple-bug](https://cloud.githubusercontent.com/assets/2391584/10871071/84934ee6-8091-11e5-9a3f-9196c1ff8420.gif)

Plunker: http://plnkr.co/edit/ETstfvcHV5rlco1sApD8?p=preview

Additionally, adding `md-no-ink` to the option group does not remove the ripple.

**Comment by EladBezalel** [comment]
@stavro This is focus indication that radio button has, menu sets the focus to the clicked element which cause the radio button turn on the focus, i'm not sure if it's the desired beavior

**Comment by stavro** [comment]
@EladBezalel I think I understand what you're saying... but that seems inconsistent with it only showing up when there's that extra `<div>` as shown in the plunkr. If you remove that div and unnest the option elements one level, it looks muchhh better.

**Comment by EladBezalel** [comment]
@stavro oh ok you didn't mentioned it in your issue, it's seems odd, i'll investigate it.

**Comment by EladBezalel** [comment]
@stavro it's seems to be something with radio-button-group not blurring cause `div` is always focused but if you click between the radio buttons the focus is disappear and not returns unless you use the keyboard which gives the focus again.

i don't see this as a big issue.

**Comment by mallowigi** [comment]
+ 1
