### ISSUE TITLE
flex-xx on md-dialog will override max-height

### ISSUE THREAD

**Issue by Herobs** [angular/material#5482]
flex-xx on md-dialog will override max-height.

md-dialog has css property: max-height: 80%; flex-xx has css property: max-height: 100%; flex-xx will md-dialog. If md-dialog-content is tall enough, the head part of dialog will be hided.

**Comment by ThomasBurleson** [comment]
Why are you setting a flex on a Dialog; as it has not apparent layout="xxx" parent ?

**Comment by Herobs** [comment]
> Complex dialogs can be sized with flex="percentage", i.e. flex="66".
Default max-width is 80% of the rootElement or parent.

I hope the dialog be wider on the mobile.

**Comment by ThomasBurleson** [comment]
You can layout the children of the Dialog. Do not use Layout to attempt to adjust the size the dialog itself.
