### ISSUE TITLE
md-autocomplete breaks with native promises

### ISSUE THREAD

**Issue by bathos** [angular/material#5485]
[This code](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L628-L630) in the md-autocomplete controller makes md-autocomplete incompatible with native promises, even though Angular's $q is now compliant. Because real promises have no `finally` method, the loading bar continues displaying indefinitely.

More strangely, sometimes it seems to actually freeze the UI even though it loads the results, though I'm not 100% sure this is caused by the same issue.

Update:

The freeze is unrelated. Even with the native promise monkeypatched to include a finally method (`p.finally = fn => p.then(fn, fn)`), this still sometimes occurs; it is not a real freeze, but rather an md-scroll-mask being left over everything.

**Comment by echenley** [comment]
:+1: Same problem. I'm using algoliasearch, which returns a native promise.

Quick fix is to wrap the native promise with $q:

```js
function search(indexName, query) {
    var index = client.initIndex(indexName);
    var deferred = $q.defer();

    index.search(query, {
        restrictSearchableAttributes: 'name'
    }).then(res => deferred.resolve(res));

    return deferred.promise;
}
```

**Comment by ThomasBurleson** [comment]
> make sure `md-scroll-mask` is being removed properly.
