### ISSUE TITLE
Weird scroll behaviour in md-virtual-scroll for nested ng-repeats

### ISSUE THREAD

**Issue by arshdefoamed** [angular/material#5488]
Hi, 
I am observing a weird behaviour for virtual scroll in case of nested ng-repeats. Scrolling is almost impossible for this scenario. I am not sure whether this is occuring due to complexity of nested repeats or this is the result of https://github.com/angular/material/issues/4169

If nested ng-repeat is not used.The scrolling is working fine.Please refer to the following plunker for details: 
http://plnkr.co/edit/OdqOk0Ijc52p4B0X0FIe?p=preview

**Comment by kseamon** [comment]
virtual-repeat only works with rows that are a consistent height (or width, in horizontal mode).
