### ISSUE TITLE
md-fab-trigger: prevent default click behavior

### ISSUE THREAD

**Issue by happschinson** [angular/material#5490]
Hi!
I tried to prevent the default click behaviour of the md-fab-trigger element.

<code>`<md-fab-trigger ng-click="preventClick($event);">......</md-fab-trigger>`</code>

and in my controller:
<code>
$scope.preventClick = function(e){
            console.log(e);
            e.preventDefault();
        };
</code>

I can log the event properly, but my preventDefault() does not stop the normal click behaviour..

Any ideas how I could solve that?

**Comment by topherfangio** [comment]
I don't think we have support for this in JS at the moment, but, you could dynamically add a CSS class to the trigger which sets `pointer-events: none;` which should stop the click from ever firing.

What exactly is your need? Perhaps there is a better solution?

**Comment by happschinson** [comment]
@topherfangio 
thanks!
I only want the trigger to open the speed dial on hover.
I added a control variable ($scope.fabOpen) which is set to true by 
`<md-fab-trigger ng-mouseenter="fabOpen=true" ng-mouseleave="fabOpen=false">`
But when I click the Trigger, i messes up the opening process, so I want to prevent it.

thank you for your help sir!

**Comment by topherfangio** [comment]
I think for the time being, the `pointer-events: none` CSS is probably your only option. Just bind a class to the trigger using `ng-class` based off of your `fabOpen` variable and when that class is active, turn off the pointer events.

That said, we've been talking about a better approach for multiple directives like `md-locked-open` or something; so I'll bring it up to the team and get some thoughts.

**Comment by happschinson** [comment]
thanks @topherfangio  
adding and removin the class did the trick!

**Comment by topherfangio** [comment]
I talked with the team and we are bumping the `md-locked-open` discussion to Post 1.0 so that we have more time to discuss it and since we have so much on our plate right now.

**Comment by zendu** [comment]
@happschinson Can you please post plunker, jsfiddle, or codepen? I am not able to get this working.
