### ISSUE TITLE
md-select with md-svg-icon label

### ISSUE THREAD

**Issue by alanpurple** [angular/material#5491]
In 1.0.0-rc2
If I make md-select with md-svg-icon(for label)

for svg with <style> tag

when selected, even if ng-value="value in values"

In front of value, the css content in style tag in svg icon appears

for example, instead of value,  <span> tag in angular-material is expanded with css content in style tag in svg file

so when selected, I see css contents in selected

svg file with no style tag is okay

Is it not recommended to use md-svg-icon in md-option?

**Comment by programmist** [comment]
I'm having a difficult time understanding your problem.  Please provide a codepen.io demo using the following versions of Angular/Angular Material.
  
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

Also, please use markdown when including code snippets in comments.  It will make them much easier to understand.
https://guides.github.com/features/mastering-markdown/

**Comment by ThomasBurleson** [comment]
Closed until CodePen is provided. Then we can re-open.

**Comment by alanpurple** [comment]
![material_svg](https://cloud.githubusercontent.com/assets/4515120/10900377/5f957456-8222-11e5-97cd-988ac14a0049.PNG)
![material1](https://cloud.githubusercontent.com/assets/4515120/10900378/5f959440-8222-11e5-82c9-89afc8c3c012.PNG)
![material2](https://cloud.githubusercontent.com/assets/4515120/10900376/5f9381b4-8222-11e5-8ebc-9f6846cc9488.PNG)
![material3](https://cloud.githubusercontent.com/assets/4515120/10900380/5f97402e-8222-11e5-990d-34a0702c9dfd.PNG)
![material4](https://cloud.githubusercontent.com/assets/4515120/10900379/5f970578-8222-11e5-96b2-0d1d018df8c1.PNG)

**Comment by ThomasBurleson** [comment]
@programmist - will this be sufficient or do we need a full CodePen demo.

**Comment by programmist** [comment]
I was able to reproduce it in [this codepen](http://codepen.io/programmist/pen/qOyXRE?editors=101).
The issue only seems to occur after the md-select is clicked and a selection is made.  It appears that the contents of the ```<style>``` element are being concatenated with selected md-option value.  I'll look into it.

**Comment by alanpurple** [comment]
@programmist  Thanks man you are the best!!

**Comment by programmist** [comment]
@alanpurple: In revisiting this issue I can no longer reproduce it.  Please verify that your issue is resolved using the latest Angular and Angular Material.

*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.4.7** (or greater).

**Comment by alanpurple** [comment]
@programmist  Yes, no longer exist
