### ISSUE TITLE
Fill-layout is having no height on Safari & Android webview

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#5492]
On Android default browser and Safari as it's also Webkit, layout-fill is using a `height:100%` which is resulting in a layout not having any height. When using  `height:auto ` it seems to work fine.
http://codepen.io/anon/pen/NGBxeE
In this example, the dialog 's line are overlapping each others because of one of them having layout-fill

**Comment by mmiszy** [comment]
Angular Material 1.0.0 has been released. What does it mean for this issue and for 1.0-rc8 milestone?
I'd say it's quite critical because the framework is basically unusable on iOS now.

**Comment by jimdubbs** [comment]
Any ETA or workaround for this? Its causing me alot of problems.

**Comment by workfel** [comment]
Waiting the issue solved override the class. And its good
```css
  .layout-fill {
    margin: 0 !important;
    width: 100% !important;
    min-height: 100% !important;
    height: auto;
    }`

**Comment by gadzhimari** [comment]
Still not working. I tried to set min-height: auto, min-height: 100%, but won't work. Here the markup https://codeshare.io/1Z3UZ

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by kkulikowski** [comment]
I think I found solution for it. At least in all my cases it was working.

**Comment by eknowles** [comment]
@kkulikowski care to share?

**Comment by kkulikowski** [comment]
Aloha im on vacation now, when ill be  back ill give a sign. I made pull
request

**Comment by eknowles** [comment]
It's okay, I found it attached to the issue, couldn't get your fix to work - will try tomorrow!

**Comment by rbournissent** [comment]
I had a similar issue and fixed it adding `flex` to the element using `layout-fill`

**Comment by Splaktar** [comment]
No longer reproducible in Safari `Version 13.1 (15609.1.20.111.8)`.
