### ISSUE TITLE
md-select directive and shouldOpenAroundTarget

### ISSUE THREAD

**Issue by bsitruk** [angular/material#5493]
Hi,
In the select component code, there is a variable called 'shouldOpenAroundTarget' allowing to position the select-menu under the label, instead of centering it on the selected option.

It's here: https://github.com/angular/material/blob/master/src/components/select/select.js#L1207

Do you have any idea how to use this as a parameter ?
I would like to make a PR for this use case, but can't find the way to do it :(

PR => https://github.com/angular/material/pull/5515

**Comment by rschmukler** [comment]
Closing this and keeping discussion in the PR.
