### ISSUE TITLE
Line 289 in tabsController.js

### ISSUE THREAD

**Issue by Jeffhuang1** [angular/material#5495]
if (!locked) ctrl.focusIndex = ctrl.selectedIndex = index;

What is the purpose of ctrl.focusIndex? I would like to be able to fix tabs to the top of the page, but that function causes the page to keep jumping around since the tabs are no longer "on the viewport of the page".

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

> @robertmesserle - thoughts here?

**Comment by robertmesserle** [comment]
Can you provide a link or codepen demo of the problem you are experiencing?  The focus should be set for accessibility reasons, but I'm not sure why it would jump to the top of the page unless you were visually putting the tabs outside of the viewport.
