### ISSUE TITLE
md-fab-speed-dial displays closing animation when loaded.

### ISSUE THREAD

**Issue by arlowhite** [angular/material#5499]
When I load the demo, the FAB Speed Dial menu starts open and then animates to closed.
https://material.angularjs.org/latest/demo/fabSpeedDial

This behavior started in 1.0.0-RC2

Ubuntu/Linux 15.10
Google Chrome Version 46.0.2490.80 (64-bit)
Also occurs in Firefox 41.0.2

**Comment by j-slvr** [comment]
I have the same issue but in my case it just starts opened and doesnt collapse.

additinally the onclick function does not caollapse it correctly:

![bug](https://cloud.githubusercontent.com/assets/12273306/10936690/78ef6d40-82ee-11e5-8ec9-7a5fe8d7b257.gif)

**Comment by topherfangio** [comment]
@j-slvr Any chance you could provide a demo of your issue? Also, did it start at the same time (1.0.0-RC2) or later?

**Comment by j-slvr** [comment]
yeah it started at 1.0.0-RC2
we now went back to 0.11.3 as in 0.11.4 the datepicker bug affected us as well
ill make a plunkr as soon as i find the time to do...

**Comment by beny78** [comment]
Same issue for me.
I need to 2 click to close the FAB.

**Comment by epelc** [comment]
+1 Just got this when updating from 0.11.2 to 1.0.0-rc4

@topherfangio You can see it if you refresh the page on the speed dial demo
https://material.angularjs.org/latest/demo/fabSpeedDial

Chrome 46.0.2490.86 m (64-bit) Windows 7

**Comment by dohomi** [comment]
@j-slvr can you check if you might have an obsolete class named ```md-fab-actions class="md-toolbar-tools"```inside of your ```html```structure? This caused the collapsing problem for me (I switched between md-fab-speed-dial and md-fab-toolbar). Beside that I have the same issue, that I see the collapsing animation on page load, and on specific pages the initial collapse is not happening.
