### ISSUE TITLE
Tabs: should have lazy-load option

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#5500]
Right now all tabs content is getting loaded when tabs are compiled,
we should add lazyload option to support tab content load only on request.

**Comment by RichOren** [comment]
+1

**Comment by ajones-miovision** [comment]
+1
We're in the process of migrating from bootstrap to material and after changing all our tab panes to material we noticed this. I can believe more people aren't complaining about this. Having lazy load is critical when your tabs make frequent callbacks to the server for updated content on web socket messages. Once a tab is no longer active the controller should be destroyed and only reinitialized when the tab is selected again. I'm going to try playing with the disconnect scope option and see how it works.

**Comment by ajones-miovision** [comment]
Looks like the disconnect options is not working out too well for us. We lose information when scope is 'reconnected'. Would be nice if the entire widget (controller and everything) was reinitialized and destroyed when switching tabs.

**Comment by vijquick** [comment]
+1
Any update on this issue please?
Thanks

**Comment by matthewpull** [comment]
+1
As with @vijquick, any update on this issue?

**Comment by vijquick** [comment]
@matthewpull , I have a temporary solution if you really want to use md-tabs, but to load the content lazy.

**Comment by matthewpull** [comment]
@vijquick What is this solution?

**Comment by vijquick** [comment]
@matthewpull , I have edited my previous post. Sorry by mistake I have submitted and I edited the same

**Comment by matthewpull** [comment]
@vijquick Ah I see. Nice solution, but what I really need the ability to execute code _after_ the content is loaded. I'll wait and see what the official solution provides. Thanks for your help, though!

**Comment by vijquick** [comment]
@matthewpull If you have a controller bound to the partialview.html then that code will be executed when the view content is rendered. In my project I have a case where the tabs are generated dynamically and each tab has lots of data. So what I have done is I created a partial view and a controller for that partial view. Using ng-if I am lazy loading the view.

**Comment by r0b-** [comment]
+1
I had some success with the new transclude lazy loading feature in angular 1.5 in combination with ng-if, md-selected and a directive inside each tab with transclusion. With that the transcluded tab content is only compiled when the tabs gets active and greatly improves performance. 
Unfortunately the dynamic height animation is a bit jumpy right now and introducing transclusion directives for each tab isn't very effective...

**Comment by nikitadmx** [comment]
Thank you so much @matthewpull  ...this code is working for me

**Comment by jsr6720** [comment]
@ThomasBurleson why was this deprecated? Is there no longer a plan to support lazy loading tabs?

**Comment by david-gang** [comment]
Hi @jsr6720 , Here is the link to the spring cleaning rules:
https://groups.google.com/forum/#!topic/ngmaterial/3Ip9nd68bfk

**Comment by vishalsrini** [comment]
I am having this same issue. It takes more time for my **_DOM_** to load if I have two dynamic tabs with dynamic contents. It take 2sec struck (if **loading** then I can use some loading image but it **strucks**). Is there any solution for this?

**Comment by PeaFull** [comment]
+1
Any update on this issue please?
Thanks

**Comment by KimAlexander** [comment]
+1

**Comment by pedru1** [comment]
+1

**Comment by EladBezalel** [comment]
You can use NavBar for lazy loading or the ngIf option

**Comment by rickyk586** [comment]
the md-enable-disconnect md-tabs option helps
