### ISSUE TITLE
Dynamically generated themes

### ISSUE THREAD

**Issue by pdore-netfore** [angular/material#5502]
As it stands, palettes and themes need to be defined before the app has started and cannot change after.
I would like to expose theming capabilities in a UI but can't apply the theme changes at runtime.

```
angular.module('app').provider('$myTheming', function($mdThemingProvider) {
    ...

    this.$get = function() {
        service = {}
            ...
        service.reloadTheme = function() {
            $mdThemingProvider.theme(theme.name).primaryPalette('myPalette');
        };
            ...
        return service;
    };
});
```

This 'seems' to work. The $mdThemingProvider attributes get updated as expected but the UI is not affected.
There needs to be a way to manually re-generate themes after the app has run. (i.e. call generateAllThemes()).

**Comment by pdore-netfore** [comment]
I see https://github.com/angular/material/pull/5399 has made some steps towards this, but is still missing the 'on-demand' palette generation.

**Comment by scottmcnab** [comment]
I agree this is a big limitation that effectively prevents run-time palette generation for themes.

The method `$mdTheming.generateTheme()` introduced in #5399 solves half the problem, but does not work with palettes registered AFTER the application has started.

I think we need to add a similar `$mdTheming.generatePalette()` method to register new palettes. The important part is this method must call the internal `sanitizePalette()` function to validate the palette and convert it into the format used internally (i.e. with `value` and `contrast` keys). (Currently this only happens for palettes defined at startup).

I would also love to see a fix for this!

**Comment by pdore-netfore** [comment]
+1

**Comment by Mylogin-info** [comment]
+1

**Comment by guilhermecvm** [comment]
+1

**Comment by Kratos-SA** [comment]
+1

**Comment by Kratos-SA** [comment]
I tried registering a blank dynamic theme which resolved this problem and I even created the pallets to match the themeProvider once it has sanitized the colors, but the styles in the head section dont reload/update. Is there a function I can use to force this update just until there is a dynamic theme/pallet fix.

**Comment by guilhermecvm** [comment]
We should have an easier and elegant way of doing that, but thats how i managed to make it works.

```javascript
angular.module('app')
.config(['$mdThemingProvider', '$provide', function($mdThemingProvider, $provide) {
    $mdThemingProvider.generateThemesOnDemand(true);
    $provide.value('themeProvider', $mdThemingProvider);
}])

.controller('AppController', ['themeProvider', '$mdTheming', function(themeProvider, $mdTheming) {
    //create new theme
    themeProvider.theme('default')
    .primaryPalette('pink')
    .accentPalette('orange')
    .backgroundPalette('yellow');

    //reload the theme
    $mdTheming.generateTheme('default');

    //optional - set the default to this new theme
    themeProvider.setDefaultTheme('default');
}]);
```

**Comment by Kratos-SA** [comment]
I implemented your code and it works great thank you

**Comment by DevVersion** [comment]
I like the implementation of @guilhermecvm. In my opinion we should provide from the `$mdTheming` service a singleton to its provider.

**Comment by Kratos-SA** [comment]
I am running the code and it does hte job but I keep getting warnings when I use the theme.

attempted to use unregistered theme

Is there a way to fix this?

**Comment by Kratos-SA** [comment]
function registered(themeName) {
        applyTheme.THEMES = angular.extend({}, THEMES);
      if (themeName === undefined || themeName === '') return true;
      return applyTheme.THEMES[themeName] !== undefined;
    }

this is the problem you have to re apply the extend function to add new themes to the current list 
then there is no bugs. Can this be added to the solution?

**Comment by Foonz** [comment]
this solution also does not work with dynamically set colorPaletts. The Paletts you want to use within the APP still need to be defined in the config phase - or did i miss something?
