### ISSUE TITLE
md-autocomplete and ng-readonly

### ISSUE THREAD

**Issue by Demian87** [angular/material#5507]
Is it possible to use ng-readonly with md-autocomplete?
I can still change the value in md-autocomplete with ng-readonly="true"

**Comment by DevVersion** [comment]
As you can see, I referenced a commit on that issue.
I don't advise you, in using this ```ng-readonly``` attribute.

You can see the changes live here: http://codepen.io/DevVersion/pen/LpgGKp

@ThomasBurleson I know this not the complete solutions, that why I didn't create a pull request.
So I want to know how you imagine that?

**Comment by ManojSridhar** [comment]
Still I can click the autocomplete on readonly and when it is without any value the suggestion dropdown appears from which the value can be changed. Is there a way to avoid this?

**Comment by Splaktar** [comment]
@ManojSridhar this is being tracked in https://github.com/angular/material/issues/11231.
