### ISSUE TITLE
layout: alignment options missing "start"

### ISSUE THREAD

**Issue by ngraef** [angular/material#5509]
Currently, [`ALIGNMENT_OPTIONS`](https://github.com/angular/material/blob/master/src/core/services/layout/layout.js#L11) doesn't contain a `"start"` option. Two problems with this:

1. [Attribute validation](https://github.com/angular/material/blob/master/src/core/services/layout/layout.js#L390) defaults to `"start-start"`. To match default CSS styling, it should default to `"start"` (which stretches the cross-axis).
2. Because of this validation, `layout-align="start"` is converted to `.layout-align-start-start`. The developer is expecting `stretch` along the cross axis but gets `flex-start` instead.

**Comment by Todd-Werelius** [comment]
@ThomasBurleson issue is still present in rc4, and @ngraef is correct 

Simply adding 'start' as the first option ( the default option ) takes care of the problem, I would do a pull request but I can't successfully build on windows 10, or my mini-mac [issue 4791](https://github.com/angular/material/issues/4791) 

#### To dix in layout.js, add "start" as the valid and first option
```js
var ALIGNMENT_OPTIONS = [
        "start","start start", "start center", "start end",
        "center", "center center", "center start", "center end",
        "end", "end center", "end start", "end end",
        "space-around", "space-around center", "space-around start", "space-around end",
        "space-between", "space-between center", "space-between start", "space-between end"
      ];
```

As of rc4
![image](https://cloud.githubusercontent.com/assets/5982829/11190397/137313d0-8c4a-11e5-98c3-2eaa9368c6e7.png)

After suggested fix
![image](https://cloud.githubusercontent.com/assets/5982829/11190358/e274df52-8c49-11e5-85ee-cc23b259f252.png)

**Comment by Todd-Werelius** [comment]
@ThomasBurleson 

Hmm, start now works, but end and center don't unless a second attribute is added 

[Codepen](http://codepen.io/Mopholo/pen/LpKJpY)

In the image layout-align is set to 'start', 'end', and 'center' on the respective rows, the last two won't align properly until you supply a second attribute.  

![image](https://cloud.githubusercontent.com/assets/5982829/11437176/71a96dba-94a0-11e5-82da-6de2c7bc633a.png)

**Comment by Todd-Werelius** [comment]
@ThomasBurleson

Okay, seems like the problem is in the sass, since you set the new default to be name-stretch, e.g. `start-stretch` for start, `end-stretch` for end, etc all the main axis classes need to have that class name added to over-ride the default `justify-content` you set higher up so ... 

```css
// Main Axis Center
  .#{$name}-start,
  .#{$name}-start-stretch, /* THE name-stretch IS MISSING ON ALL THE MAIN AXIS PORTIONS*/
  .#{$name}-start-start,
  .#{$name}-start-center,
  .#{$name}-start-end
  {
    justify-content: start;
  }
```
