### ISSUE TITLE
Bottom sheet and sidenav overlapping

### ISSUE THREAD

**Issue by miguelchico** [angular/material#551]
Hi!

I have a problem with the bottom sheet and the sidenav component working together. You can see the example here (http://plnkr.co/edit/vRc9Ex)

If you expand the browser the sidenav appears and when clicked on test button the bottom sheet appears under the sidenav its not blocked (light gray blocking)

If you reduce the page size the sidenav dissapear (that is my intention) and the bottom sheet show ok.

What is my mistake?

![1](https://cloud.githubusercontent.com/assets/6106661/4933264/bdd2adaa-6594-11e4-88fa-52c52f8968ba.PNG)
![2](https://cloud.githubusercontent.com/assets/6106661/4933263/bdd13d08-6594-11e4-8747-c7403dfbb0fc.PNG)

**Comment by robertmesserle** [comment]
@ThomasBurleson So is the issue that the sidebar should be under the blackout and be disabled while the bottomSheet is showing?

**Comment by robertmesserle** [comment]
This issue looks to have been resolved already.
