### ISSUE TITLE
md-select has static width in IE 11

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [angular/material#5516]
The md-select box does not auto size its width in IE 11. See [this codepen](http://codepen.io/anon/pen/wKxpqp)

Current behavior:
![image](https://cloud.githubusercontent.com/assets/5230331/10905060/10656e40-8218-11e5-9c6d-3d4726977eed.png)

Expected behavior:
![image](https://cloud.githubusercontent.com/assets/5230331/10905072/28bc7902-8218-11e5-9d68-b25351dcae16.png)

**Comment by rschmukler** [comment]
Closed by 4306331c65651764f2639b35816d8e305111f5a5
