### ISSUE TITLE
md-progress-circular has wrong animation in IE 11

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [angular/material#5517]
md-progress-circular currently has a weird animation in IE when loaded for a second time. Open [this codepen](http://codepen.io/anon/pen/mejpjM) in IE and click the on/off switch a few times and the animation will go crazy.

Current behavior:
![2015-11-03_11-17-23](https://cloud.githubusercontent.com/assets/5230331/10905716/6c3852f6-821c-11e5-8273-442e94904ae9.gif)

Expected behavior:
![2015-11-03_11-15-57](https://cloud.githubusercontent.com/assets/5230331/10905696/3a930ad4-821c-11e5-9443-f8256578d53d.gif)

**Comment by 0101adm** [comment]
+1 seen randomly on chrome.

**Comment by hesher** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
