### ISSUE TITLE
Progressbar not visible 

### ISSUE THREAD

**Issue by groupsvkg** [angular/material#5518]
Hi Team,

md-progress-linear is not visible inside md-grid-tile-header
```html
<div layout-fill >
    <md-content flex layout-padding>
        <md-grid-list md-cols-gt-md="6" md-cols-sm="3" md-cols-md="4"
        	md-row-height-gt-md="1:1" md-row-height="4:3"
        	md-gutter-gt-md="16px" md-gutter-gt-sm="8px" md-gutter="4px">
            <md-grid-tile ng-repeat="solution in solutions" class="md-whiteframe-7dp">
                <md-grid-tile-header style="background: pink;">
                	<md-progress-linear md-mode="determinate" value="30"></md-progress-linear>
                </md-grid-tile-header>
                   Test Body
                <md-grid-tile-footer style="background: green;">
                    <h3>Test Footer</h3>
                </md-grid-tile-footer>
            </md-grid-tile>
        </md-grid-list>
    </md-content>
</div>
```

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.7** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by groupsvkg** [comment]
Link for codepen --> http://codepen.io/groupsvkg/pen/avjqVW
Problem is stil there.

**Comment by topherfangio** [comment]
It looks like the grid tile header is really only designed to support text in an `<h3>` tag. If you're doing something more custom, you may need additional CSS.

Try uncommenting either of the solutions provided here and see if that works for you: http://codepen.io/topherfangio/pen/bVxpeQ?editors=010

**Comment by groupsvkg** [comment]
:+1: 

@topherfangio  checked codepen and its working fine. 
Thanks a lot!!!
