### ISSUE TITLE
Form layout is broken in 1.0.0-rc2: row layout is used instead of colums.

### ISSUE THREAD

**Issue by Dotneteer** [angular/material#5520]
Take a look at this markup:
```html
...
<body ng-app="myApp" layout="column"
      ng-controller="SimpleFormController">
<md-toolbar class="md-toolbar-tools">
  <h1>Simple form</h1>
</md-toolbar>
<md-content>
  <form name="simple" novalidate
        layout-margin>
    <md-input-container>
      <label>Name</label>
      <input name="name"
             ng-model="user.name"
             required maxlength="32" />
    </md-input-container>
    <md-input-container>
      <label>Email</label>
      <input type="email" name="email"
             ng-model="user.email"
             required maxlength="64" />
    </md-input-container>
    <md-button class="md-raised md-primary"
               ng-click="register(user)"
               ng-disabled="simple.$invalid"  >
      Register
    </md-button>
  </form>
  <md-divider></md-divider>
  <div layout-margin layout-padding>
    <code>
      {{registeredUser | json}}
    </code>
  </div>
</md-content>

<!-- ... -->
</body>
...
```
Rendered in 1.0.0-rc1 (http://codepen.io/Dotneteer/pen/MaBpqd):
<img width="418" alt="sc1" src="https://cloud.githubusercontent.com/assets/4783390/10908017/5fac627c-81e3-11e5-859d-84c743546bc9.png">

Rendered in 1.0.0-rc2 (http://codepen.io/Dotneteer/pen/gajvJJ):
<img width="418" alt="sc2" src="https://cloud.githubusercontent.com/assets/4783390/10908050/9d9f9798-81e3-11e5-900e-9e6604819248.png">

The difference between the codepens are only the links to the Angular Material CSS and JS files.

**Comment by e-oz** [comment]
```html
<form name="simple" novalidate
        layout-margin>
```
here you create new layout and default mode is "row", add layout="column" to form tag to fix it.

**Comment by Dotneteer** [comment]
e-oz, I know that your suggestion works. My problem is that a layout feature has been broken while moving from 1.0.0-rc1 to 1.0.0-rc2.
Actually, not only forms are broken, but control alignment in general:
1.0.0-rc1: http://codepen.io/Dotneteer/pen/vNaaaB
1.0.0-rc2: http://codepen.io/Dotneteer/pen/RWBBqN

**Comment by e-oz** [comment]
@Dotneteer this example looks much more buggy :)

**Comment by mckenzielong** [comment]
@Dotneteer setting `layout="column"` on your md-content (or whatever their container element is) will have output like your 1.0.0-rc1 example.  The inline-bock changes that went into rc2 touched a lot of things.

Interesting though unrelated is checkbox spacing being wrong when `layout="row"` is set: http://codepen.io/mckenzielong/pen/GpBXZN

**Comment by Dotneteer** [comment]
@mckenzielong I also discovered the issue you mention. Again, my problem is that such a feature break in rc2 is not very elegant. It's easy to workaround, but when you have dozens of occurrences like this, it's a nightmare.

**Comment by ThomasBurleson** [comment]
@Dotneteer - are you saying that the default for `layout  === "column"`. If so, I think I agree.

**Comment by Dotneteer** [comment]
@ThomasBurleson - yes, I mean the default for `layout` should be `column` as it was in rc1 and before.

**Comment by e-oz** [comment]
@Dotneteer actually default was "row".

**Comment by Dotneteer** [comment]
@e-oz, @ThomasBurleson - of course, `row` is correct, sorry for the mistake.

**Comment by ThomasBurleson** [comment]
The flexbox default is layout **row**... I wonder if ngMaterial users would expect Layout default of "column"? (which would be contrary to the industry default unfortunately).

**Comment by Dotneteer** [comment]
@ThomasBurleson, @e-oz: according to your opinion, I think `row` should be the default, even if it breaks rc1. However, we should communicate that this is a breaking change from rc1 to rc2. The workaround is to add explicit layout to each field within the form.
I will change my samples of the Unraveling Angular Material book accordingly, and I suggest to close this issue.

**Comment by ThomasBurleson** [comment]
@Dotneteer - don't forget that Angular Material requires Angular 1.3.19 or higher, 1.4.7 or higher, or 1.5.x

http://codepen.io/team/AngularMaterial/pen/rOqELL?editors=101
