### ISSUE TITLE
md-datepicker does not close when inside md-sidenav

### ISSUE THREAD

**Issue by ccstevenson** [angular/material#5522]
md-datepicker does not close when inside an md-sidenav and the user clicks off of the sidenav. It appears that the sidenav is capturing the click event

Codepen adding a datepicker to the official md-sidenav demo: http://codepen.io/anon/pen/KdBmPL Click "Toggle Right". The datepicker is in the right sidenav.

![datepicker-sidenav-interaction](https://cloud.githubusercontent.com/assets/4258816/10912834/6dc71f12-8208-11e5-9a26-f05214a305f2.gif)

**Comment by nascosto** [comment]
:+1:

**Comment by DevVersion** [comment]
Sorry, for that duplicate referencing :-1:, but here is the final fix 
#5528
