### ISSUE TITLE
layout-align not working on md-icon

### ISSUE THREAD

**Issue by helzgate** [angular/material#5523]
If you put an md-icon inside a div that has `layout-align` set to `start start`, it will not work.  The md-icon stays centered no matter what.  I'm posting this in part so that if another developer runs into this they'll see the fix.  The fix is to put the md-icon inside a redundant div.  Plunker [here](http://plnkr.co/7wjWmfHY5u2A3SoxMjV1) shows the problem.

**Comment by helzgate** [comment]
There is a simple fix so i'm closing but wanted this issue posted for others to reference.

**Comment by cmacdonnacha** [comment]
Hi @helzgate , just wondering what the fix for this is?
