### ISSUE TITLE
The text in text inputs and in selects has a slightly different baseline

### ISSUE THREAD

**Issue by ivan7237d** [angular/material#5524]
This is regardless of browser. This screenshot from https://material.angularjs.org/HEAD/demo/select demonstrates: 

<img width="478" alt="screen shot 2015-09-14 at 10 49 23 pm" src="https://cloud.githubusercontent.com/assets/9092817/10917431/b585e1d2-822e-11e5-8611-c7615c5d8887.png">

Originally discussed in #4357.

**Comment by EladBezalel** [comment]
@ivan7237d is it still happening on master?

**Comment by ivan7237d** [comment]
@EladBezalel Yes, I still see this. Sorry for slow response.
