### ISSUE TITLE
bug(autocomplete): ng-click no works inside md-not-found

### ISSUE THREAD

**Issue by stewones** [angular/material#5526]
![materialbug](https://cloud.githubusercontent.com/assets/719763/10923352/ab989708-8267-11e5-9dbe-d66518333ba6.png)

**Comment by snarayanank2** [comment]
+1 I'm running into this as well with version 0.11.4.

```
         <md-not-found>
            "{{searchCategoryTxt}}" not found.
            <a ng-href="#" ng-click="newCategory(searchCategoryTxt)">Add!</a>
          </md-not-found>
```

My controller function never gets called. As @stewones mentions, even the demo one doesn't work - it doesn't show the alert.

**Comment by makkart** [comment]
+1 has been working in RC-1 and maybe RC-2, not working in RC-3

**Comment by dominicgoulet** [comment]
+1 not working since RC1 for me.

**Comment by nestorneto** [comment]
as workout: self.$mdAutocompleteCtrl.mouseUp = function(){}; 

its not good, but for those who need make it to work at any cost!

**Comment by dominicgoulet** [comment]
My current fix is the following: 

    <md-autocomplete md-search-text-change="searchTextChange(searchText)" ...>
      <md-not-found>
        <span ng-click="ok()"></span>
      </md-not-found>
    </md-autocomplete>

    $scope.ok = function() {
      document.querySelector('md-virtual-repeat-container').classList.add('ng-hide');
    };

    $scope.searchTextChange = function() {
      document.querySelector('md-virtual-repeat-container').classList.remove('ng-hide');
    };

**Comment by Tramvai** [comment]
@nestorneto 

Hey. Your hack doesn't seem to be working, or did I interpret it incorrectly?

```
var input = angular.element(document.getElementById('new-task-tag-input')).find('input')[0];
            var el = angular.element(document.getElementById('new-task-tag-input').firstElementChild);
            el.scope().$mdAutocompleteCtrl.mouseUp = function () {
                $timeout(function () { input.focus(); });
            };
```

**Comment by Tramvai** [comment]
@dominicgoulet @nestorneto 
I had to combine both of your solutions to get the hack working. Thanks guys.

Eagerly waiting for a fix.

**Comment by nestorneto** [comment]
Just override the mouseUp funcion of $mdAutocompleteCtrl. This worked for me. In my case I have a custom directive that uses the autocomplete component. So its easer for me to do that.

**Comment by Tramvai** [comment]
@nestorneto How did you go about hiding the list? I tried it in a few different ways, but only dominicgoulet's hack worked.

**Comment by vlopez5** [comment]
+1
@nestorneto and @dominicgoulet 
I tried your solution, but isn`t working for me. Could you provide an example of you implementation?
I really need this feature working in 1.0.

**Comment by dominicgoulet** [comment]
What's your problem with the current workaround @vlopez5 ?

**Comment by vlopez5** [comment]
I tried to do like your demo and still not possible click inside md-not-found.
Also I can`t figure out where to put @nestorneto solution.

**Comment by DevVersion** [comment]
Finally, there is a fix for that issue. #6103

**Comment by vlopez5** [comment]
Thank you @DevVersion !
I hope it gets merged soon...

**Comment by janvandenberg** [comment]
Another workaround that worked for me is to change ng-click with ng-mousedown

**Comment by agarwal-vishal** [comment]
> My current fix is the following:
> 
> ```
> <md-autocomplete md-search-text-change="searchTextChange(searchText)" ...>
>   <md-not-found>
>     <span ng-click="ok()">Click here to create new item</span>
>   </md-not-found>
> </md-autocomplete>
> 
> $scope.ok = function() {
>   document.querySelector('md-virtual-repeat-container').classList.add('ng-hide');
> };
> 
> $scope.searchTextChange = function() {
>   document.querySelector('md-virtual-repeat-container').classList.remove('ng-hide');
> };
> ```

Thank You
