### ISSUE TITLE
Datepicker does not have styles applied

### ISSUE THREAD

**Issue by WeHateNick** [angular/material#5529]
The mdDatepicker directive does not show with proper styles. Every other directive seems to be properly styled.

I made sure to link the CSS and JS files, inject ngMaterial as a dependency and even explicitly set a theme, but the datepicker looks transparent to me. I tried this on CodePen and the datepicker gets styled fine on it.

I installed Angular Material via bower and am using a clean Yeoman scaffold using the Angular generator.

**Comment by WeHateNick** [comment]
This problem went away when I upgraded angular-material to 1.0.0-rc1, but will likely be an issue for anyone that downloads the current version through bower.

**Comment by nicgirault** [comment]
:+1:

**Comment by HenderOrlando** [comment]
I also have this probleme

**Comment by redhurt** [comment]
i also have it

**Comment by dapids** [comment]
+1
