### ISSUE TITLE
md-text-float raises error on click

### ISSUE THREAD

**Issue by FUT** [angular/material#553]
I use `md-bottom-sheet` as a wrapper for the sign in form and `md-text-float` as inputs:
 
![Image of sign in form](http://cl.ly/image/1S1f1D333w2V/Image%202014-11-06%20at%2014.26.26.png)

On some devises (e.g. my tablet & chrome emulation of nexus 7) I see that error when I try to click on the field inside the `md-bottom-sheet` element:

```
Uncaught TypeError: Cannot read property '0' of undefined angular-material-871f3ed9aaf14330ee72bf77479bbd2b.js?body=1:1160
  getY angular-material-871f3ed9aaf14330ee72bf77479bbd2b.js?body=1:1160
  onTouchStart angular-material-871f3ed9aaf14330ee72bf77479bbd2b.js?body=1:1117
  jQuery.event.dispatch jquery-967caacfe1cc2c76f46786a9e8393bf0.js?body=1:4642
  elemData.handle jquery-967caacfe1cc2c76f46786a9e8393bf0.js?body=1:4310
```

Here is the `angular-material-871f3ed9aaf14330ee72bf77479bbd2b.js?body=1:1160`:

```
    /**
     * Helper function to find the Y aspect of various touch events.
     **/
    function getY(e) {
      var touch = e.touches && e.touches.length ? e.touches[0] : e.changedTouches[0];
      return touch.clientY;
    }
```

I have inspected code a bit and see that both `e.touches` and `e.changedTouches` are `null`. Thus the last expression `e.changedTouches[0]` raises the error `Cannot read property '0' of undefined`.

I am not totally sure why does this happen but if I use the same `md-text-float` elements outside the `md-bottom-sheet` they work just well. Am I doing something wrong or is it a bug?

**Comment by FUT** [comment]
Thanks guys!

**Comment by FUT** [comment]
I upgraded the angular material to 0.7.0-rc3 but the bug is still there. Here is the detailed explanation: http://stackoverflow.com/questions/27328271/use-inputs-in-angularjs-material-bottom-sheet

Could you please take a look?

**Comment by FUT** [comment]
Can not reopen - created a new one: https://github.com/angular/material/issues/1248

**Comment by ThomasBurleson** [comment]
@FUT - md-text-float has been deprecated. Use the `md-input-container`; @see https://material.angularjs.org/#/demo/material.components.input

**Comment by FUT** [comment]
the issue is repeatable even for simple input.
