### ISSUE TITLE
Animation is janky when changing states using UI Router

### ISSUE THREAD

**Issue by acondiff** [angular/material#5531]
There is a definite paint/render lag while changing states using UI Router to change states. 

Try for yourself:
http://codepen.io/acondiff/pen/jbpdpE

Here is a timeline snapshot: 
![timeline snapshot](http://files.continuumcreative.com/diTX/Screen%20Shot%202015-11-03%20at%205.53.59%20PM.png)
http://files.continuumcreative.com/diTX

Through my debugging on my app, I took a snapshot in my console timeline and found this issue. I thought it was my app so I tested it on CodePen for a more controlled environment. After testing it on CodePen and finding the same issue, I am concluding that my app isn't the problem. 

This is something that can and will prevent me from launching my product because I do not want a poor/laggy user experience. Please let me know if there is anything I can do to help resolve this issue, or if there might be any workarounds. Thanks.

**Comment by gpopovic** [comment]
I'm having the same problem :/

**Comment by acondiff** [comment]
It could possibly be how Chrome is handling script execution, or UI router itself (see https://github.com/angular-ui/ui-router/issues/2355) and I don't want to just conclude that the cause is UI Router for the time being as I really don't know either way. But there is a noticeable spike in activity. For me the lag lasts a little over 600ms at times. It really varies. In any event, this is a little more difficult to debug when it has a great deal to do with how these dependencies work.
