### ISSUE TITLE
mdContactChips does not display email address

### ISSUE THREAD

**Issue by metamatt** [angular/material#5534]
In 0.10.1, the email address for each contact (if you use md-contact-email) was displayed fine.

Since 0.11, and including up to 1.0-rc2, the email address is not displayed. It's rendered in the DOM, but clipped by the bounding box of the menu popup, so it's invisible onscreen.

It's this snippet of NG-HTML from `MD_CONTACT_CHIPS_TEMPLATE`:

```
              <span class="md-contact-email" >{{item[$mdContactChipsCtrl.contactEmail]}}</span>\
```

**Comment by topherfangio** [comment]
Can you please test this against the latest master branch? This is related to #4450 for which a temporary fix was pushed 5 days ago that is now available in rc3.
