### ISSUE TITLE
Autocomplete height

### ISSUE THREAD

**Issue by gpopovic** [angular/material#5537]
In master, autocomplete ng-messages are displayed(take only space) when there are no errors.

This causes inconsistent spaces between normal inputs and autocomplete fields with ng-messages.

**Comment by mallowigi** [comment]
+1

**Comment by robertmesserle** [comment]
@gpopovic Can you provide a demo for this?

**Comment by chrislambe** [comment]
You can see this on the demo page with floating label autocompletes.

![screen shot 2015-12-16 at 12 27 40 pm](https://cloud.githubusercontent.com/assets/283764/11850013/86efa13a-a3f0-11e5-91a5-98eaf5eb5cc1.png)

**Comment by jakubweber** [comment]
+1, Very annoying

**Comment by mattdanna** [comment]
I'm hoping this spacing issue will be addressed by #6209
