### ISSUE TITLE
mdDialog does not close when click outside

### ISSUE THREAD

**Issue by okaiyong** [angular/material#5540]
I am using angular material v1.0.0. I have reference the sample codes from website to build my mdDialog. It can be pop out but when I clicked close or outside the dialog, the background become not hidden but i cannot click on anything. The dialog does not disappear too. 

The properties "clickTOController" is set to true and the $mdDialog.cancel() is also added in the controller. 

May I seek your advice?

**Comment by DevVersion** [comment]
Can you share your code with us?, this would simplify creating a fix if applicable.

**Comment by mallowigi** [comment]
This is fixed in the latest commit, simply put it is looking for a place to "close to" but could not find it, so it stays on the page.

This was working fine in 0.11, i dont know what you guys have done :(

**Comment by okaiyong** [comment]
Hi, 
Attached a copy of source codes that replicate the issue. It has all the necessary files to run in a webserver.For your advice, pls. 
Thanks.

Date: Wed, 4 Nov 2015 03:23:58 -0800

**Comment by rschmukler** [comment]
Per [this demo](http://codepen.io/rschmukler/pen/PPLLyE) this appears to be working. Please open a new issue with a demo of it not working if you'd like us to take a look!
