### ISSUE TITLE
md-menu requires exactly two child elements

### ISSUE THREAD

**Issue by andrew-cunliffe** [angular/material#5544]
The expected behaviour of md-menu is that we do the following:

```
<md-menu>
    <button ng-click="$mdOpenMenu()">Filters</button>
    <md-menu-content>
        <md-menu-item ng-repeat="field in devices.fieldList"><md-button ng-click="devices.setFilter(field)" ng-bind="field.name"></md-button></md-menu-item>
    </md-menu-content>
</md-menu>
```

However I have a situation when using md-menu-bar that I want a quick access button to refresh some data, this causes an error `Invalid HTML for md-menu: Expected two children elements.` Although I could perhaps look at a different UI it feels like you should be able to have the following functionality wise it works great:

Snippet
```
<md-menu-bar>
    <md-menu>
        <button ng-click="$mdOpenMenu()">Filters</button>
        <md-menu-content>
            <md-menu-item ng-repeat="field in devices.fieldList"><md-button ng-click="devices.setFilter(field)" ng-bind="field.name"></md-button></md-menu-item>
        </md-menu-content>
    </md-menu>
    <md-menu>
        <button ng-click="data.refresh()"><md-icon class="material-icons">refresh</md-icon></button>
    </md-menu>
</md-menu-bar>
```

Is there any reason this should not be done?

**Comment by rschmukler** [comment]
@anderson-arlen can you add an empty `md-menu-content` to the second `md-menu`?

**Comment by mallowigi** [comment]
Why would a menu exists without menu choices? Can't you do a simple md-button instead?

**Comment by andrew-cunliffe** [comment]
Putting md-button in there looks wrong... behaviour of md-button is somewhat different, it is possible as mentioned the UI could change, but the fact it works with my 'hack' that looks like;

```
<md-menu-bar>
    <md-menu>
        <button ng-click="$mdOpenMenu()">Filters</button>
        <md-menu-content>
            <md-menu-item ng-repeat="field in devices.fieldList"><md-button ng-click="devices.setFilter(field)" ng-bind="field.name"></md-button></md-menu-item>
        </md-menu-content>
    </md-menu>
    <md-menu>
        <button ng-click="data.refresh()"><md-icon class="material-icons">refresh</md-icon></button>
        <span></span>
    </md-menu>
</md-menu-bar>
```

Note the empty span tag, this fixes the error message and it all works fine, its just a bit of a hack, and no one likes hacks...

**Comment by mallowigi** [comment]
I understand what you want to do, but it's very uncommon to have a *menu* without *menu items*. Maybe you should include your refresh button inside a refresh menu or something. 



Sent from Mailbird [http://www.getmailbird.com/?utm_source=Mailbird&utm_medium=email&utm_campaign=sent-from-mailbird]
On 10/11/2015 11:42:33, Andrew Cunliffe <notifications@github.com> wrote:
Putting md-button in there looks wrong... behaviour of md-button is somewhat different, it is possible as mentioned the UI could change, but the fact it works with my 'hack' that looks like;
<md-menu-bar> <md-menu> <button ng-click="$mdOpenMenu()">Filters</button> <md-menu-content> <md-menu-item ng-repeat="field in devices.fieldList"><md-button ng-click="devices.setFilter(field)" ng-bind="field.name"></md-button></md-menu-item> </md-menu-content> </md-menu> <md-menu> <button ng-click="data.refresh()"><md-icon class="material-icons">refresh</md-icon></button> <span></span> </md-menu> </md-menu-bar>
Note the empty span tag, this fixes the error message and it all works fine, its just a bit of a hack, and no one likes hacks...

**Comment by andrew-cunliffe** [comment]
That is an option, but this is an example, the real menu has 3 'buttons' that are top level as the requirement is for 'quick access' to some functionality without going through a dropdown, such as all menus that are linked to a list have a 'Create New' at the top, not 'standard' I appreciate, but the bootstrap version had this, and while we are converting the site to angular material (due to complete this week on development to enter final user testing next week) we can't alter feature requirements such as this one :( I could do a few screenshots to story board it more if it really helps, another example is we have device management functionality, and to 'register' a new device there is a QR code you scan, this QR code is a dialog window, triggered from one of these top level buttons too. So there are real world 'wishes' to do this, or we make the UI a bit less pretty in the future, right now looks like we shall have to accept going into testing with this hack, which is ok, just feel as it works, that it should be allowed.

**Comment by andrew-cunliffe** [comment]
Just to add another example, we will be updating another of our portals from bootstrap to angular material in the new year, (assuming all goes as well as currently) this change so far is seen as a good move, this other portal has a 'text editor' for blogs and forum functions with a menu bar for things like bold, italic etc, I expect this will be an issue there too...

**Comment by rschmukler** [comment]
I'm kicking this to a post-1.0 effort where we can reexamine whether this is something the framework should support.

**Comment by amarg26** [comment]
yeh just putting span tag error gone !!!!
