### ISSUE TITLE
md-avatar-icon inside a clickable md-list-item

### ISSUE THREAD

**Issue by tjlav5** [angular/material#5554]
It seems that the css for the md-avatar-icon is a bit too specific.

```css
md-list-item > .md-avatar-icon {
    background-color: '{{foreground-3}}';
    color: '{{background-color}}';
}
```

When adding a click fn to the containing md-list-item, the new structure becomes:

md-list-item
-- button
----.md-list-item-inner
------.md-avatar-icon

Is there any reason to not have an md-avatar-icon inside a clickable list-item? Or is it just an omission? If the later I can submit a quick PR.

Something along these lines would fix my use case:
```css
md-list-item > .md-avatar-icon, .md-list-item-inner > .md-avatar-icon
```
**OR**
```css
md-list-item .md-avatar-icon
```

Cheers

**Comment by programmist** [comment]
@tjlav5  - Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by programmist** [comment]
@tjlav5: I've applied the style change and have a working demo here:
http://codepen.io/programmist/pen/ZQYZay

Please verify that it's working for you.

**Comment by tjlav5** [comment]
@programmist Yep, that did the trick.

**Comment by programmist** [comment]
This has been waiting on PR #6181.
