### ISSUE TITLE
md-button .md-fab icon not centered when using Firefox and minimum-font-size preference >=15

### ISSUE THREAD

**Issue by arlowhite** [angular/material#5557]
Ubuntu/Linux 15.10, Firefox 41.0.2

On the demo, page, in Firefox the icons are not centered.
https://material.angularjs.org/latest/demo/button

![firefoxfabbuttons](https://cloud.githubusercontent.com/assets/444413/10948508/c5676f58-82e2-11e5-9ed9-41df9ceec24e.png)

This does not occur with Google Chrome.

**Comment by DevVersion** [comment]
I installed Firefox 41.0.2 and I'm using it on Windows (but that shouldn't matter).

![](https://i.gyazo.com/6b3fc485dbffae4c5b99bacc81e93366.png)

And my icons are placed correctly.
![](http://i.gyazo.com/7796a12892b56136b9c051434362045a.png)

Thats strange.

**Comment by arlowhite** [comment]
I still have the issue after trying:
* Made sure the cache is clear (disabled cache with dev tools).
* Verified Zoom at 100%
* Safe-mode (addons disabled)
* Upgraded to 42.0

The CSS and DOM look the same between Chrome and Firefox. (both use an SVG in md-icon)

On **md-button**, the line-height value is equal to the height. In Firefox, I found that if I **disable the line-height style**, the icon centers. I don't see a difference when disabling the same style in Chrome.

Just in case this helps, on .md-button.md-fab, the height and line-height is 56px. If I reduce the line-height value, the icon shifts up until 49px, where it stays in place. With .md-button.md-fab.md-mini, the initial value is 40px, at 35px the icon is centered and no longer shifts with a lower value.

I'm not sure why Windows vs Linux Firefox differ. Can anyone else with Linux reproduce this?

**Comment by arlowhite** [comment]
Ahh, just figured it out. I have minimum font-size set in Firefox.
Preferences > Content > [Advanced]
Minimum font size is set to 16.
Lower values (12 & 14) don't cause an issue.

**Comment by DevVersion** [comment]
Good to hear that. I don't think a fix is needed for that anymore.
