### ISSUE TITLE
mdselect with multiple; floating label bug

### ISSUE THREAD

**Issue by aavielmd** [angular/material#5566]
mdselect with ngmultiple to choose multiple options...This happen when the mdselect is empty and does not have option currently selected; when the user select options its floating label stays and does not float  when selection is done this happens when selecting options for the first time. But if you click the mdselect again the animation of floating label gets executed.

http://codepen.io/tenshiAMD/pen/ZbMKzd

**Comment by willramos** [comment]
+ 1

**Comment by opadillaintegrify** [comment]
+1

**Comment by oktay89** [comment]
Still having this issue with material 1.1.4 and angularJS 1.6.5
