### ISSUE TITLE
layout.scss lacks browser-specific prefixes

### ISSUE THREAD

**Issue by andreaskaltenbach** [angular/material#5568]
**layout.scss** contains a lot of layouting rules without any browser-specific prefixes like `-webkit-` and `-ms-`. 

Examples:

```
  // Main Axis Center
  .#{$name}-center,           //stretch
  .#{$name}-center-center,
  .#{$name}-center-start,
  .#{$name}-center-end
  {
    justify-content: center;
  }

  // Cross Axis Start
  .#{$name}-center-start,
  .#{$name}-start-start,
  .#{$name}-end-start,
  .#{$name}-space-between-start,
  .#{$name}-space-around-start
  {
    align-items: flex-start;
  }
```

Adding `-webkit-justify-content` and `-ms-flex-pack` will solve issues with Mobile Safari and Internet Explorer for example. 

By adding those to **layout.scss**, we would be able to import the Angular Material Sass files in our own SASS files. Fallback for now is of course to use the CSS files instead. Those contain the browser-specific prefixes.

**Comment by Frank3K** [comment]
This is by design; the prefixes are automatically added using autoprefixer.

**Comment by DevVersion** [comment]
Frank3K is right, as you can see in the ```package.json```, there is ```gulp-autoprefixer``` installed, which is embedded in the build cycle

**Comment by ThomasBurleson** [comment]
https://github.com/angular/bower-material/blob/master/angular-material.layouts.css#L207-L209
