### ISSUE TITLE
ng-disable wont apply styling if ng-click is present on md-button in md-toolbar

### ISSUE THREAD

**Issue by frikkievb** [angular/material#5569]
Hi

I am having trouble disabling a button.  Even though the click function is disable, will the disabled style not be applied if a ng-click directive is present.  The style only applies when `n use ui-sref.  This is the code for the button:
```
<md-button aria-label="Acknowledge"
                       ng-show="true"
                       ng-disabled="true" ng-click="docViewCtrl.confirmAcknowledgment()">
                <md-icon md-svg-icon="action:ic_done_24px"></md-icon>
                Acknowledge
            </md-button>
```

Please advise!

Regards

**Comment by DevVersion** [comment]
I hope I have understood everything correctly.
Then on my codepen is everything working. (excuse me, if I'm wrong)

http://codepen.io/DevVersion/pen/BoOwJG

**Comment by frikkievb** [comment]
Looks like the problem I am having occurs when the <md-button> is nested within a <md-toolbar>.

http://codepen.io/anon/pen/WQgZaq

**Comment by DevVersion** [comment]
Thanks for your codepen :+1:
I checked the styling classes for the two buttons. At first you should ignore that attribute ```ui-sref```
As you can see in the following screenshot, the style of the disabled button state is injected before the ```toolbar``` style. That's why the toolbar overwrites the color of the disabled button.

![](https://i.gyazo.com/df0fd230c7351a5e2cba2aed69a29447.png)

**Comment by frikkievb** [comment]
Thank you for the feedback.  Is this behaviour by design or should this be looked at?  In the mean time, do you think it would be wise to add the disabled styles manually?

**Comment by DevVersion** [comment]
It's the default behavior of the design, I will look for a fix, which prevents this overwrite.

**Comment by frikkievb** [comment]
Thanks for the assistance!  It's much appreciated.

**Comment by DevVersion** [comment]
I created a possible fix, which solves that problem permanently.

here another codepen to checkout the changes: http://codepen.io/DevVersion/pen/dYqZZw?editors=010

**Comment by frikkievb** [comment]
This looks great!  That is exactly the behaviour I was looking for. :smile:

**Comment by frikkievb** [comment]
Hi

I am referring back to this problem.  Seems like the cursor style is doing the same as the color.

Kind regards

**Comment by DevVersion** [comment]
http://codepen.io/DevVersion/pen/dYqZZw?editors=110
As I can see here, the cursor style is applied? or you mean something else?

**Comment by frikkievb** [comment]
You understood correctly, looks like I was not using a correct version of angular material.  My bad. Thanks for the feedback.

**Comment by DevVersion** [comment]
You still have this issue?

**Comment by frikkievb** [comment]
Looks like I got it sorted.  Sorry, was out of office for a while.  I was
using the incorrect version.  My bad. :P
