### ISSUE TITLE
md-checkbox does't become disabled  via disabled attribute

### ISSUE THREAD

**Issue by begemott** [angular/material#5570]
To disable a md-checkbox one should add the ng-disabled directive to the element. It would be better if the checkbox becomes disabled when the disabled attribute is added. There are some cases when I don't want to add the ng-directive, but want to disable the checkbox by my custom directive which adds the disabled attribute.

By the way the md-select control observes the disabled attribute to find out if the control is disabled. May be it makes sense to use such a mechanism for all your controls.

Thanks

**Comment by DevVersion** [comment]
You mean something like that?
Let me know if I'm wrong :v:

http://codepen.io/DevVersion/pen/XmPBwY

**Comment by begemott** [comment]
I found the following code in checkbox.js 
```javascript
      $$watchExpr('ngDisabled', 'tabindex', {
        true: '-1',
        false: attr.tabindex
      });
```
As I understood It watches the expression specified in the ngDisabled attribute and set the element's tabindex to -1 if the expression becomes true. It would be better to do it by observing the disabled attribute. Because the element can be disabled not via ng-disabled directive, but via disabled attribute.

**Comment by DevVersion** [comment]
Should we watch for both attributes? or you mean only ```disabled```?

**Comment by begemott** [comment]
I think only disabled.

**Comment by marcysutton** [comment]
We watch ngDisabled because `disabled` does not properly disable custom controls like mdCheckbox. ng-disabled handles both `disabled` and `aria-disabled`, so it is preferred for disabling Material components.
