### ISSUE TITLE
Bug: Menu Bar demo dialog boxes are not closed

### ISSUE THREAD

**Issue by Shyiy** [angular/material#5573]
Can be seen on the menu bar demo page of the lastest release (1.0.0 rc2).
If you trigger one of the actions from the menus like "cut", the dialog window correctly comes up,
When you try to press the button to close it or pres esc however, the darker background goes away and the dialog remains open, impossible to close with further clicks or key presses.

**Comment by ThomasBurleson** [comment]
Fixed in master:  https://material.angularjs.org/HEAD/demo/menuBar
