### ISSUE TITLE
No instance found for handle

### ISSUE THREAD

**Issue by nmrt** [angular/material#5577]
When I try to access sidenav instance via `$mdSidenav(componentId)` in a method that is data-bound, there are lots of "No instance found for handle" errors in the console.

Example:

```javascript
VM.prototype.getContainerState = function() {
  return {
    'left-sidenav-open': this.$mdSidenav('left').isOpen()
  };
};
```

```html
<div class="container" ng-class="vm.getContainerState()">
  <!-- ... -->
</div>
```

In this case, it's impossible to defer the return value of `getContainerState`, since `ng-class` doesn't expect promises.

So, I've ended up disabling these errors like this (probably not the best solution):

```javascript
$mdComponentRegistry.notFoundError = $.noop;
```

Am I doing something wrong, is there a better way?
Why do we even need these messages? :smile: 

Thanks for any help!

**Comment by DevVersion** [comment]
How you define the sidenav, I would like to see the html code

**Comment by nmrt** [comment]
```html
<md-sidenav class="md-sidenav-left md-whiteframe-z2" md-component-id="left">
```

Actually, I've found the problem: my sidenav was wrapped in div with `ng-if` directive (hidden behind the flag for staging).
After I've made it public (removed condition), the errors are gone! :sunglasses: 

Sorry for the trouble!

**Comment by DevVersion** [comment]
No problem, I thought you didn't specify the ```md-component-id```
