### ISSUE TITLE
<md-button> hard codes height & width of md-icon to 24px (doesn't honor other icon font sizes)

### ISSUE THREAD

**Issue by watlandc** [angular/material#5585]
Since `<md-button>` hard codes height and width of `<md-icon>` to 24x24, using any other icon font size within buttons throws off the positioning (icons won't be centered within buttons).

Example code:

`<md-button class="md-icon-button">
  <md-icon class="material-icons md-18">comment</md-icon>
</md-button>`

Screen shot below:

<img width="58" alt="screenshot 2015-11-05 18 59 01" src="https://cloud.githubusercontent.com/assets/6117504/10986395/4db60f92-83ef-11e5-83d2-fbc531c34844.png">

**Comment by oddcb** [comment]
Hi. I was researching this myself and found that it was also reported earlier (Seems like the same issue) in #2630 which seems to be scheduled for 1.0 rc6. Don't know if you looked into that issue already.

**Comment by EladBezalel** [comment]
dup of #2630 fixed in #6043
