### ISSUE TITLE
md-grid-list MD spec says it should provide for a single-line grid list 

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#5587]
Reading the [Material Design Spec](http://www.google.com/design/spec/components/grid-lists.html#grid-lists-behavior) suggests a new feature for md-grid-list

"_Horizontally scrolling grid lists are discouraged because the scrolling interferes with typical reading patterns, affecting comprehension._

__One notable exception is a horizontally-scrolling, single-line grid list of images, such as a gallery, which is compatible with typical reading patterns.__"

This could actually be useful in some applications, and it's in the spec! :-0 

UX ADDITION: 
The spec also says that "_Cut off grid tiles in the view’s initial scroll position to communicate the scroll direction for content overflow._"

If the above feature is implemented we might want to take this into consideration since the current implementation fits the cells  perfectly in the row, I would suggest having some markup that allowed this to be 'pushed' n-pixels to the overflow direction if there was overflow ( mobile hates scroll bars! ) 

![image](https://cloud.githubusercontent.com/assets/5982829/10992171/4b9bc96c-8418-11e5-9a7f-2b10b5f3143d.png)

**Comment by ThomasBurleson** [comment]
Will not fix. PR would be welcomed.
