### ISSUE TITLE
md-progress-circular height is 100px despite using md-diameter

### ISSUE THREAD

**Issue by UncleBenjen** [angular/material#5594]
Not 100% sure if this is an issue of not, but when you have an md-progress-circular the height is always 100px regardless of shrinking the spinner using the md-diameter directive... it ends up affecting buttons if they are contained within the same row. I'm not sure if this is a bug, or if I need to be adjusting the height of the md-progress-circular manually.

Here are a couple codepens that demonstrate the issue:
[small spinner, button height is 100px](http://codepen.io/anon/pen/OyoKXR) 
[small spinner, md-mode='', button height is still 100px ](http://codepen.io/anon/pen/MaqNeV)
[no spinner, button/row height displayed correctly](http://codepen.io/anon/pen/RWYXoP)

Anyways, keep up the great work guys, this framework is a lot of fun to work with.
Please let me know if this is not an issue and if I should just set height explicitly for small md-progress-circulars

Cheers,
Ben

**Comment by zckrs** [comment]
@mallowigi why you close your PR :-/ ?

**Comment by mallowigi** [comment]
I lost interest in angular-material
