### ISSUE TITLE
mdIconDirective: race condition sometimes renders multiple icons when the source value changes quickly

### ISSUE THREAD

**Issue by voithos** [angular/material#5598]
There appears to be a subtle [race condition in `mdIconDirective`](https://github.com/angular/material/blob/747ef8264be3ac3f4d47cea4c9dfe7ffbc6d2f40/src/components/icon/js/iconDirective.js#L216) that can cause it to render multiple icons when the source value (in my case, `mdSvgIcon`) quickly changes.

Essentially, I think what happens is that the `attr.$observe` callback gets executed twice, attempting to clear the container element, *before* the [`$mdIcon` service's promise](https://github.com/angular/material/blob/747ef8264be3ac3f4d47cea4c9dfe7ffbc6d2f40/src/components/icon/js/iconDirective.js#L215) gets resolved. This results in 2 SVGs getting appended to the element, without it being cleared.

The fix may be as simple as moving the call to `element.empty()` inside the promise callback, right before `element.append(svg);`.

**Comment by JasperG** [comment]
I have observed this issue as well, and can confirm, moving
[element.empty();](https://github.com/angular/material/blob/747ef8264be3ac3f4d47cea4c9dfe7ffbc6d2f40/src/components/icon/js/iconDirective.js#L213) inside the [promise](https://github.com/angular/material/blob/747ef8264be3ac3f4d47cea4c9dfe7ffbc6d2f40/src/components/icon/js/iconDirective.js#L215) seems to solve the issue.
