### ISSUE TITLE
md-dialog-actions is not required

### ISSUE THREAD

**Issue by Herobs** [angular/material#5605]
If I not provider a `md-dialog-actions`, messages `At least one action button is required for <md-dialog-actions>.` will receive.

md-dialog-actions is not required, for example, I place the close button at the top right corner in the top `md-tool-bar`

**Comment by paambaati** [comment]
@Herobs You can simply wrap your close button inside a `<md-dialog-actions>` and it won't warn you anymore.

**Comment by Herobs** [comment]
@paambaati look like word fine, thx.

But the `md-dialog-actions` have some css rule, maybe cause problems.

**Comment by bampakoa** [comment]
@Herobs I can confirm that it is not required from 1.0.0-rc5 and above.
