### ISSUE TITLE
BUG: getNearestContentElement in $mdUtil always returns root

### ISSUE THREAD

**Issue by hodeyp** [angular/material#5609]
I have a number of tooltips in a nested md-content, the positioning is incorrect when the nearest md-content is scrolled. The offending issue is `getNearestContentElement` in $mdUtil.

```
    getNearestContentElement: function (element) {
      var current = element.parent()[0];
      // Look for the nearest parent md-content, stopping at the rootElement.
      while (current && current !== $rootElement[0] && current !== document.body && current.nodeName !== 'MD-CONTENT {
        current = current.parentNode;
      }
      return current;
    },
```

as `MD-CONTENT` is caps, it never matches the nearest `md-content`

**Comment by Frank3K** [comment]
Isn't [nodeName](https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeName) always in uppercase?

**Comment by hodeyp** [comment]
yes I believe it should be, however it is not working and when I change it in source to lower case it works correctly. Using latest Chrome build.

Looking at http://ejohn.org/blog/nodename-case-sensitivity/ it seems as if custom elements do not always follow the upper case rules.

**Comment by Frank3K** [comment]
Adding a toUpperCase() on the left side should solve that issue.

**Comment by epelc** [comment]
@EladBezalel This isn't working as expected. Replacing `MD-CONTENT` with `md-content` fixes it though. Doing this should also fix #5802 

Tested in 1.0.0-rc5

**Comment by EladBezalel** [comment]
@epelc thanks i will fix it.

**Comment by epelc** [comment]
Thanks

On Mon, Nov 30, 2015 at 4:27 PM, Elad Bezalel <notifications@github.com>
wrote:

> @epelc <https://github.com/epelc> thanks i will fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/5609#issuecomment-160766758>.
>



-- 
Thank you,
Ed Pelc

**Comment by EladBezalel** [comment]
@epelc do you have any idea why `.toUpperCase` didn't made a difference ?

**Comment by epelc** [comment]
@EladBezalel I'm suspecting `.toUpperCase` converts `md-content` to `Md-Content` and does nothing if you input `MD-CONTENT`. Can you go on [gitter](https://gitter.im/angular/material) I'd like to get this resolved.
