### ISSUE TITLE
md-text-float doesn't update the ngModelController properties ($touched, $untouched etc)

### ISSUE THREAD

**Issue by eriktufvesson** [angular/material#561]
When trying to do form validation on forms containing md-text-float elements, I can't use the $touched, $untouched, $dirty or $pristine properties like if I was working with normal input elements.

See example in this plunker:

http://plnkr.co/JjohAu

Regards, Erik

**Comment by ThomasBurleson** [comment]
`md-text-float` has been deprecated. Plz use `md-input-container` @See [Docs](https://material.angularjs.org/#/api/material.components.input/directive/mdInputContainer)
