### ISSUE TITLE
Urgent: latest Angular build breaks md-menu

### ISSUE THREAD

**Issue by jpike88** [angular/material#5614]
md-menu opens ok, but ng-click is broken on menu elements, and this error appears on mouseover of each element.

Error: null is not an object (evaluating 'o.open')
http://10.0.0.31:8100/lib/angular-material/angular-material.js:13:4175
http://10.0.0.31:8100/lib/angular/angular.js:17855:36
completeOutstandingRequest@http://10.0.0.31:8100/lib/angular/angular.js:5507:15
http://10.0.0.31:8100/lib/angular/angular.js:5784:33

Using Angular 1.4.7

**Comment by bigzachattack** [comment]
This also happens with the "Simple dropdown menu" example at https://material.angularjs.org/1.0.0-rc3/demo/menu

**Comment by Frank3K** [comment]
Related: #5604.

**Comment by Tyrannmisu** [comment]
I get "Error: nestedMenu is null" when opening a menu, this is probably related to this issue too.

```
Error: nestedMenu is null
MenuController/this.enableHoverListener/</openMenuTimeout<@http://localhost:9000/bower_components/angular-material/angular-material.js:20515:9
timeout/timeoutId<@http://localhost:9000/bower_components/angular/angular.js:17855:28
completeOutstandingRequest@http://localhost:9000/bower_components/angular/angular.js:5507:7
Browser/self.defer/timeoutId<@http://localhost:9000/bower_components/angular/angular.js:5784:7
setTimeout handler*Browser/self.defer@http://localhost:9000/bower_components/angular/angular.js:5782:17
timeout@http://localhost:9000/bower_components/angular/angular.js:17853:19

...

```

**Comment by jpike88** [comment]
Devs this needs serious attention, please tag it at least

**Comment by gbaj** [comment]
Codepen?

**Comment by jpike88** [comment]
https://material.angularjs.org/latest/demo/menu

Just watch your console while mouseovering the menu items, you'll see errors popping up.

**Comment by Magador** [comment]
Though it does work when using ng-repeat on `<md-menu-item>`

**Comment by Frank3K** [comment]
It's already fixed in master.

**Comment by jpike88** [comment]
Which commit fixed it?

**Comment by Frank3K** [comment]
As discussed in #5604: it's fixed in 6bf98aa.

**Comment by RolandHeath** [comment]
@jpike88 I suspect it's untagged because it's difficult for the team to track so many duplicate issues. If it's fixed, you're able to close your own issue(s).

**Comment by jpike88** [comment]
Ok, closed. Thanks fellas
