### ISSUE TITLE
Is Angular 1.5.0 supported by Angular Material?

### ISSUE THREAD

**Issue by gabguy** [angular/material#5618]
I'm asking because I can see an issue running angular 1.5.0 with angular material in the md-autocomplete - The data bindings are not working when using an item template

**Comment by 0101adm** [comment]
"Please note that the Angular Material project is targeted for  Angular 1.3 only  and is still in an early pre-release state."

**Comment by mckenzielong** [comment]
@0101adm I don't think that is correct.  Quote from #5520 by @ThomasBurleson:
>@Dotneteer - don't forget that Angular Material requires Angular 1.3.19 or higher, 1.4.7 or higher, or 1.5.x
>http://codepen.io/team/AngularMaterial/pen/rOqELL?editors=101

**Comment by gabguy** [comment]
Well, apparently the issue I encountered was angular 1.5.0 related, not angular-material.
