### ISSUE TITLE
Is it possible to use templateUrl for $mdSidenav?

### ISSUE THREAD

**Issue by renatus** [angular/material#5622]
For now it's not that clear, if it's possible to store Sidenav HTML template in a separate file, just like we do with the Dialogs (something like templateUrl: 'templates/dialog.html'). If no, what is a recommended way to create Sidebars we want to use globally throughout application - i.e., are there any better ways to do that, than adding Sidenav HTML code to index.html?

**Comment by EladBezalel** [comment]
you should use [`<ng-include>`](https://docs.angularjs.org/api/ng/directive/ngInclude)
