### ISSUE TITLE
Material icons are working(showing) on MS edge.

### ISSUE THREAD

**Issue by surajnaikwade143** [angular/material#5624]

**Comment by topherfangio** [comment]
We're going to need some more information about this issue. Can you please provide a description and a Codepen using the latest versions to show us what the problem is?

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

---

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).
