### ISSUE TITLE
mdChips with autocomplete incorrectly calculates inner height

### ISSUE THREAD

**Issue by gligoran** [angular/material#5630]
Here's the [pen](http://codepen.io/gligoran/pen/ojamzx) (modified demo) and an image of how the menu for autocomplete is displayed:

![](http://i.imgur.com/VAdWAbj.png)

There are total of 5 choices. When you click on input it displays a list with blank space at the bottom.

I'm pretty certain it's a javascript height calculation bug, as the menu displays correctly if you resize the window.

My example is using mdMinLength= 0, but it works the same with 1 and without the attribute specified at all.

**Comment by hillerstorm** [comment]
Probably related to #5606

**Comment by gabguy** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
