### ISSUE TITLE
md-input-container + ng-messages + error message misalign

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5632]
rc3

http://codepen.io/0101adm/pen/NGOmmw

open dialog, click new tab, focus first name field then blur.

**Comment by ngraef** [comment]
See #5298

**Comment by peio72** [comment]
+1

**Comment by sunnyshah01** [comment]
+1

**Comment by ivanzvakoms** [comment]
```.md-input-container { vertical-align: top; }``` will fix this
