### ISSUE TITLE
md-subheader position isn´t recalculated when using ng-if or ng-show

### ISSUE THREAD

**Issue by celestinoramalho** [angular/material#5634]
If a section has a div  using ng-if/ng-show to be printed, all the subsequent subheaders will stick at the wrong scroll point. They will always keep sticking at the initially calculated position.

This can be seen at http://codepen.io/celestinoramalho/pen/XmxLdj

In this example, if i hide the "trash" content, you can see that "Late messages" subheader doesn´t stick when it was supposed to.

At first i thought it was related to the issue https://github.com/angular/material/issues/3980, but in that case the hidden content is outside of the md-content.

**Comment by topherfangio** [comment]
I can definitely reproduce the issue. Thanks.

**Comment by pdore-netfore** [comment]
+1

**Comment by rosstroha** [comment]
+1

**Comment by kwirke** [comment]
+1

**Comment by sam2x** [comment]
I have the exact same problem when i use md-subheader followed by md-list (md-list have ng-if or ng-show to disclose/hide content). The sticky header isnt calculated correctly.
