### ISSUE TITLE
mdDialog cannot be closed before onComplete is called

### ISSUE THREAD

**Issue by standup75** [angular/material#5635]
Normally, you wouldn't want to close a dialog immediately after you open it, but I am using a loading dialog, so sometimes I have all the data and it should close pretty fast, but it does not always close.

This is due to the fact that I am using templateUrl, so it takes some time to load the template, and during this time $mdDialog.hide call is ignored

http://codepen.io/anon/pen/avRevK

**Comment by bluebirdtech** [comment]
Seeing something similar here. Calling $mdDialog.hide() when it's currently showing causes the dialog not to hide, but to think it is hidden, leaving the dialog stuck on the screen.

**Comment by EladBezalel** [comment]
A fix for that is in the PR queue also :)

**Comment by bluebirdtech** [comment]
Awesome :)

**Comment by arturoaguirre** [comment]
@EladBezalel is your change ever going to make it to a release? If that is not the case, is there a workaround?
