### ISSUE TITLE
Feature request (datepicker): add shortcut to jump to today

### ISSUE THREAD

**Issue by oswaldomilet** [angular/material#5638]
1) Is there a way I can back to current date like a "today" link/button?
2) For several purposes, datepicker could be used to navigate from 2015 to 1990 for example, how can I achieve this instead of scrolling infinitely?

**Comment by Gregoirevda** [comment]
UP. Difficult to use this component to get user birth date. Which is probably most common case.  
Have you found a solution?

**Comment by oswaldomilet** [comment]
I didn't found solution yet

**Comment by stunaz** [comment]
+1
