### ISSUE TITLE
md-ink-ripple: animation not consistent with Polymer

### ISSUE THREAD

**Issue by acondiff** [angular/material#5639]
Compare tabs, buttons, and anything else with an ink ripple effect in to it's comparable element in Polymer and you will see that it is quite a bit different. The effect in Polymer seems much snappier and fast which provides for a much more responsive user experience. It seems quite a bit more sluggish in Angular Material.

**Comment by DevVersion** [comment]
For compare
- Polymer: https://elements.polymer-project.org/elements/paper-button?view=demo:demo/index.html&active=paper-button
- Angular Material: https://material.angularjs.org/latest/demo/button

**Comment by acondiff** [comment]
Thank you @DevVersion.

**Comment by EladBezalel** [comment]
@acondiff We follow the [Material design spec](https://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons) and not Polymer
According to [this video](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B3T7oTWa3HiFSTNhRndpWXBwRDA/components-buttons-flatbuttons.webm) i think our implementation feel a lot more accurate and close to the spec than the Polymer behavior

**Comment by DevVersion** [comment]
@acondiff @EladBezalel -> Elad is definitely right, so I think this issue is waste :+1: 
But you can keep it open to wait for a response from other team members.

**Comment by acondiff** [comment]
@EladBezalel @DevVersion I do agree that Angular Materal's animation is a little more similar to that video, however there may be a larger issue here that may need addressing.

I have seen a fair amount of inconsistency in how material design is implemented across the web, within Google and otherwise. Some aspects of the spec can be somewhat ambiguous and others are not as up-to-date as they could be with current behavior among many apps Google puts out using material design.

Look at this same ink animation across various mobile apps, and Google web apps such as Photos, Music, Maps, etc. If these apps are all consistently different from the spec, maybe the spec itself needs updating? That or at least some internal dialog needs to happen making not only Polymer and Angular Material more consistent, but mobile platforms as well. 

Now I personally prefer Polymer's animation style over Angular Material's simply because it feels quicker and it seems a little more natural when compared to an actual ink droplet dropped into water as I assume it was the original intent of the animation.

**Comment by DevVersion** [comment]
I agree with you, the Polymer Button Effect seems quite better, because it feels quicker as you already said

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
