### ISSUE TITLE
md-tabs: ui-view inside md-tab-body incompatible with md-dynamic-height

### ISSUE THREAD

**Issue by burner-account** [angular/material#5641]
angular-material 0.11.4
angular 1.4.7
angular-ui-router: 0.2.15

If you write tabs like this, md-dynamic-height shows weird behaviour:

```
<md-tabs md-dynamic-height>

  <md-tab ui-sref="some.state.link1">
    <md-tab-label>....</md-tab-label>
    <md-tab-body>
      <div ui-view="someViewTag1"></div>
    </md-tab-body>
  <md-tab>

  <md-tab ui-sref="some.state.link2">
    <md-tab-label>....</md-tab-label>
    <md-tab-body>
      <div ui-view="someViewTag2"></div>
    </md-tab-body>
  <md-tab>
  
</md-tabs>
```

Problem:
On changing tabs, the md-dynamic-height makes the md-tabs fall back to the default min-height (round about 250px). This troubles the tab-change animation: It briefly slides the tab content up to min-height on every change, just to slide down to the correct height afterwards. This flickers, looks bad and has incredibly bad performance.

I am not quite sure if this can be solved from the angular-material side of the equation. What is your opinion?

As a workaround, is there any way to make md-tabs fill the remaining screen height? This would be less work than to measure every tab on every code change in order to use static height.

**Comment by billjohnston** [comment]
I did this, pretty hacky, but looks slightly better:

```
<md-tabs md-dynamic-height>

  <md-tab ui-sref="some.state.link1">
    <md-tab-label>....</md-tab-label>
    <md-tab-body></md-tab-body>
  <md-tab>

  <md-tab ui-sref="some.state.link2">
    <md-tab-label>....</md-tab-label>
    <md-tab-body></md-tab-body>
  <md-tab>

</md-tabs>

<ui-view></ui-view>
```

**Comment by ThomasBurleson** [comment]
Will not fix in ngMaterial1.

**Comment by jonaszuberbuehler** [comment]
@burner-account Did you find any workaround for this?

**Comment by BriceN** [comment]
@burner-account same problem here, can't find a solution and the flicker is really annoying.

**Comment by agent306** [comment]
`<md-tabs layout-fill>

  <md-tab ui-sref="some.state.link1">
    <md-tab-label>....</md-tab-label>
    <md-tab-body>
      <div ui-view="someViewTag1"></div>
    </md-tab-body>
  <md-tab>

  <md-tab ui-sref="some.state.link2">
    <md-tab-label>....</md-tab-label>
    <md-tab-body>
      <div ui-view="someViewTag2"></div>
    </md-tab-body>
  <md-tab>

</md-tabs>`

This worked for me.
