### ISSUE TITLE
mdBottomSheet: add option to disable dragging up

### ISSUE THREAD

**Issue by tumoxep** [angular/material#5642]
I guess it will be usefull to have this as an option.
My own workaround at this moment is to add a separate `onDragLockedUp` callback inside `BottomSheet` in `bottom-sheet.js`

```javascript
function BottomSheet(element, parent, lockedUp) {
  var deregister = $mdGesture.register(parent, 'drag', { horizontal: false });
  parent.on('$md.dragstart', onDragStart)
    .on('$md.dragend', onDragEnd);
  if(lockedUp) {
    parent.on('$md.drag', onDragLockedUp); 
  } else {
    parent.on('$md.drag', onDrag);
  }
  return {
    element: element,
    cleanup: function cleanup() {
      deregister();
      parent.off('$md.dragstart', onDragStart);
      if(lockedUp) {
        parent.off('$md.drag', onDragLockedUp);
      } else {
        parent.off('$md.drag', onDrag);
      }
      parent.off('$md.dragend', onDragEnd);
    }
  };
  ...
  
  function onDragLockedUp(ev) {
    var transform = ev.pointer.distanceY;
    if (transform < 5) { 
      // drags up, ignore  
    } else { 
      element.css($mdConstant.CSS.TRANSFORM, 'translate3d(0,' + (PADDING + transform) + 'px,0)');
    }
  }

  ...
}
```

**Comment by gauravsam** [comment]
sir how to disable bottomsheet close on mouse drag down

**Comment by tumoxep** [comment]
**gauravsam**, modify the source for [bottom-sheet.js](https://github.com/angular/material/blob/master/src/components/bottomSheet/bottom-sheet.js) the way you need (will be enough just to put code from line 244 into `if` block, [here](https://gist.github.com/tumoxep/9f4e6338730cb2bd0bb8/revisions)) and build. But as temporary fix I guess nothing wrong is just include your modified `bottom-sheet.js` into your page after `angular-material`.
