### ISSUE TITLE
md-backdrop is broken when adding custom functions to Array

### ISSUE THREAD

**Issue by SiZiOUS** [angular/material#5644]
Hello,

The `<md-backdrop>` element shown when using `$mdDialog` is broken when adding custom functions to the `Array` object.

Normal `<md-backdrop>` node added to the DOM is:
```html
<md-backdrop class="md-dialog-backdrop md-opaque ng-scope md-default-theme" aria-hidden="true"></md-backdrop>
```

When executing this function:
```javascript
// Add Array.clear() utility if missing (and should be)
if (!Array.prototype.clear) {
    Array.prototype.clear = (function() {
       this.splice(0, this.length);
    });
}
```

The `<md-backdrop>` element becomes:
```html
<md-backdrop class="{0} ng-scope md-default-theme" aria-hidden="true"></md-backdrop>
```

As you can see some CSS classes aren't properly set in the `<md-backdrop>` element. 
The result is, the overlay isn't shown anymore.

I think this is because some stuff in `angular-material` is iterating on an internal `Array` instance (instead of doing a `for` loop using `.length` property), and this seems to be a bad practice.

Thank you for reading my message.

BR,
SiZiOUS.

**Comment by EladBezalel** [comment]
Can you please provide a codepen so we can investigate it more?

**Comment by SiZiOUS** [comment]
Hello,

Here is the [CodePen](http://codepen.io/sizious/pen/yYZZYo).

Please note, I'm using Angular-Material in a legacy project, installed with Bower in VS 2013. I don't know the version for now.
Maybe I need to check if the library is up-to-date.

BR,
SiZiOUS.

**Comment by EladBezalel** [comment]
You should upgrade to our latest release, before every issue you should check if it's still happening on HEAD,

Here's your [Codepen](http://codepen.io/EladBezalel/pen/epxXWw) with latest. it's working :)

**Comment by SiZiOUS** [comment]
Hi,

Sorry about that, I was in hurry so I didn't done the basics, I mean checking with HEAD version, you're right, it's working with the latest release.

Thank you for your feedback anyway!

BR,
SiZiOUS.

**Comment by EladBezalel** [comment]
np happy to help!
