### ISSUE TITLE
(feat) responsive interactions

### ISSUE THREAD

**Issue by 0101adm** [angular/material#5647]
would love to see these responsive interactions added to the lib.

https://elements.polymer-project.org/bower_components/neon-animation/demo/card/index.html

https://elements.polymer-project.org/bower_components/neon-animation/demo/tiles/index.html

https://elements.polymer-project.org/bower_components/neon-animation/demo/load/index.html

https://elements.polymer-project.org/bower_components/neon-animation/demo/list/index.html

https://elements.polymer-project.org/bower_components/neon-animation/demo/grid/index.html

**Comment by Todd-Werelius** [comment]
This looks like a post 1.0 issue - see possible dupe [PR #1054](https://github.com/angular/material/issues/1054)
