### ISSUE TITLE
md-scroll-shrink when scrolling a frame within md-content

### ISSUE THREAD

**Issue by alecperkey** [angular/material#5649]
Hi,

How might I go about making the toolbar shrink when the user scrolls only an iframe within the md-content and not the md-content itself? 

If you might have some advice I made a demo here: 
http://stackoverflow.com/questions/33634756/shrink-toolbar-on-scroll-iframed-content 

Thanks

**Comment by topherfangio** [comment]
I feel like this is a fairly specialized case that will require a custom component or coding and it outside the realm of what we can provide. Please post this to the [forums](https://groups.google.com/forum/#!forum/ngmaterial) where I think you will get a better response.
