### ISSUE TITLE
$mdUtil: disableBodyScroll causes IE rendering bug

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [angular/material#5650]
When using components that hides the scrollbar, IE will not render anything under the body (which  is fixed to the top). Open [this plunker](http://embed.plnkr.co/L5pZtk) in IE and scroll all the way down, try to select an option a few times and you will see a rendering bug at the bottom of the page. IE either displays the html element totally black or a weird duplicate rendering of the body.

Recording of the bug (the black background should not be there)
![2015-11-10_17-42-58](https://cloud.githubusercontent.com/assets/5230331/11068723/05974108-87d3-11e5-9889-d3f0c3494d1e.gif)

**Comment by EladBezalel** [comment]
What IE version your'e using? couldn't reproduce on IE11 WIN10

**Comment by Patrik-Lundqvist** [comment]
IE 11 WIN 10 with resolution 1920x1080 and browser in fullscreen.

You might have to try to change the option in the plunker a couple of times before you see it. Make sure you are scrolled down so that you have space under the option.

**Comment by EladBezalel** [comment]
I'm sorry, I'm with the same configuration and I can't see it. tried to refresh, scrolled down, nothing :sweat_smile:

**Comment by Patrik-Lundqvist** [comment]
Did you try to select it twice? (and scrolling down as it scrolls up when you select). I just tried it on a different setup and got the same problem :)

**Comment by gkalpak** [comment]
FWIW, I wasn't able to reproduce it either (Win10, IE11, 1980x1080, browser in fullscreen, tried to select it multiple times and even _scroll down as it scrolls up when you select it_).

**Comment by SanderElias** [comment]
I can reproduce it too. 
![image](https://cloud.githubusercontent.com/assets/1249083/11231848/b2ed145c-8dac-11e5-8c90-7b39bf212306.png)

Inspected the black area, and it seems to be a md-backdrop. So it seems to be a bug in our code indeed.
