### ISSUE TITLE
md-fab-toolbar: md-fab-*-* positioning classes not appropriate

### ISSUE THREAD

**Issue by topherfangio** [angular/material#5657]
The current documentation for `<md-fab-toolbar>` says that it can use the `md-fab-*-*` classes (i.e. `md-fab-bottom-right`) to position the toolbar, however, this doesn't do exactly what you would expect as it positions the entire toolbar `20px` from the bottom and right side of the screen.

Instead, we should either provide `md-fab-top` and `md-fab-bottom` which simply aligns it to the top or bottom of the screen, or update the docs to discuss using `position: absolute` to position it manually.

Ideally, the user would be able to position the FAB trigger using these classes and the toolbar would accommodate properly, but this is not currently possible.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
