### ISSUE TITLE
Styling of invalid fields inconsistent between md-select and <input>

### ISSUE THREAD

**Issue by calebegg** [angular/material#5661]
`md-select` shows the placeholder text in red, while `<input>` does not:

![download 7](https://cloud.githubusercontent.com/assets/782920/11081233/f5c5d9cc-87e8-11e5-9deb-11d938bcd1e3.png)
![download 8](https://cloud.githubusercontent.com/assets/782920/11081235/f6aa3d42-87e8-11e5-9f6f-934c771a1b8c.png)

**Comment by mallowigi** [comment]
+1

**Comment by deevorak** [comment]
+1
