### ISSUE TITLE
md-chips not leave focus when click on other input.

### ISSUE THREAD

**Issue by phucnv206** [angular/material#5662]
![md-chips-blur](https://cloud.githubusercontent.com/assets/7970972/11082168/7adb3f14-8855-11e5-812e-37c97921e3f8.gif)

http://codepen.io/anon/pen/rOQpgq?editors=100

**Comment by DevVersion** [comment]
I tested it with the current Release Candidate 4 (http://codepen.io/DevVersion/pen/XmGWPJ). Issue still shows up.
