### ISSUE TITLE
md-autocomplete: tap events outside do not dismiss autocomplete 

### ISSUE THREAD

**Issue by chriswait** [angular/material#5663]
### Demo:
Left is Chrome (not emulating mobile) - dismisses as expected
Right is iOS simulator (iPad2 / iOS 9.1) - does not dismiss on taps outside
![autocomplete](https://cloud.githubusercontent.com/assets/2563474/11083378/00519af8-8883-11e5-8a67-eb1e1eac1bbb.gif)

Codepen: http://codepen.io/chriswait91/pen/JYepbj/ (using Angular Material v1.0.0-rc3)
Also reproducible on Autocomplete demo page: https://material.angularjs.org/HEAD/demo/autocomplete

### Reproduction Steps:
1. Tap on the autocomplete input (the system displays the list of matches)
2. Tap outside the autocomplete area i.e outside the input and the list of matches

### Expected Behaviour:
When these steps are followed in desktop browsers, clicking outside the autocomplete area will dismiss the autocomplete. This is presumed to be the expected behaviour on mobile devices.

### Actual Behaviour:
The list of matches is not dismissed.

### Reproduced on:
* iPhone 6 (iOS 9.1, Safari)
* iOS Simulator (iOS 9.1, iPad 2, Safari)
* Android Nexus 7 (Chrome)
* Google Chrome, emulating mobile

**Comment by gpothier** [comment]
+1

**Comment by smithdalec** [comment]
+1
After upgrading to v1.0.0-rc7, I can at least dismiss the the results by tapping on another form element.

**Comment by jsmylnycky** [comment]
+1

**Comment by sroyqci** [comment]
+1

**Comment by tranduytrung** [comment]
I also met this issue. Generally, <input> elements does not lose their focus

**Comment by fernandogomesdf** [comment]
+1

**Comment by korrix** [comment]
+1

**Comment by wgilpin** [comment]
+1. Why is this deprecated?

**Comment by orenagiv** [comment]
Any news about this one...?
Why was this deprecated?
The issue still exists on Safari...

**Comment by RajappaR** [comment]
Anyone got Solution for this issue, I am also facing same problem here...

**Comment by RajappaR** [comment]
@ThomasBurleson why did u closed this issue... still this issue is not resloved....

**Comment by jason-covington** [comment]
+ 1 This should not be closed. Still an issue on the demo page on an iPhoneX: https://material.angularjs.org/HEAD/demo/autocomplete

**Comment by Splaktar** [comment]
This is being tracked in https://github.com/angular/material/issues/9581. Another duplicate issue is https://github.com/angular/material/issues/8996.

**Comment by Splaktar** [comment]
Btw, disabling click hijacking as described [here](https://github.com/angular/material/issues/9581#issuecomment-246305494) is the recommended solution for now.
