### ISSUE TITLE
msSelect: SelectedItem does not reflect  a custom item template.

### ISSUE THREAD

**Issue by waegen** [angular/material#5671]
HI there,

i'm not sure if this is supposed to work but when i have a custom item template in mdSelect (to have some highlighting or styling) the selectedItem does not reflect this. It would be great if the styled content was shown in the selected as well. 

Also ng-show/hide do not work for the SelectedItem.

I have prepared a testcase (http://plnkr.co/edit/GaUSJrn3o3KRYQwzHmbo?p=preview) where you can see that the item text is show twice.

Also if this is not supposed to work in that way how can i accomplish such a request.

**Comment by pmchugh3** [comment]
+1 It seems to strip out the html tags etc and just use the plain text in the selected item, and given the removal of the label override it makes it impossible to customize this component sufficiently.

**Comment by ThomasBurleson** [comment]
This change is related to our focus on components and security issues.
