### ISSUE TITLE
mdInputContainer: Spacing broke in rc2

### ISSUE THREAD

**Issue by Flygenring** [angular/material#5672]
This may be the problem mentioned in this commit: https://github.com/angular/material/commit/17797f001533288560854b04de81f53c552d2a80

As far I have seen it happened after changing the spacing on md-input-container from [rc1](https://github.com/angular/material/blob/v1.0.0-rc1/src/components/input/input.scss#L29) to [rc2](https://github.com/angular/material/blob/v1.0.0-rc2/src/components/input/input.scss#L26)

```
/* in rc1 */
  padding-bottom: $input-container-padding + $input-error-height;

/* in rc2 */
  margin: 18px 0;
```

This is all good and fine, but the way spacing changes for input containers with messages hasn't changed, so it still tries to cancel the bottom padding from the old method:
```
  padding-bottom: $input-container-padding;
```

This effectively means that an input container with an input and messages is 24px taller than one without messages.

**Comment by julienpa** [comment]
This causes many problems to me too, as I recently updated from 0.11.4 to 1.0.0-rc4 and all my vertical forms are now broken with inconsistent spacing between input with and without messages.
Isn't a fix planned?

**Comment by lievenjanssen** [comment]
Any idea when this will be fixed?

**Comment by AdriVanHoudt** [comment]
This causes super spaced out forms. Any thoughts on when/id this will be fixed?

**Comment by EladBezalel** [comment]
@robertmesserle moving this to your plate as you're on the PR that fixes it
