### ISSUE TITLE
md-chips + autocomplete (list length)

### ISSUE THREAD

**Issue by andrew-cunliffe** [angular/material#5673]
When using the autocomplete with md-chips there seems to be an issue with the number of displayed items...

Here is my code

HTML
```
<md-chips ng-model="template.validTimezones"
        md-autocomplete-snap
        md-require-match="true">
    <md-autocomplete md-selected-item="timezoneSelection"
            md-search-text="timezoneSearch"
            md-items="timezone in template.getTimezones(timezoneSearch)"
            md-item-text="timezone.id"
            placeholder="Optional time zone(s)">
        <span>{{ timezone.id }}</span>
        <md-not-found>No time zones "{{ timezoneSearch }}" were found.</md-not-found>
    </md-autocomplete>
    <md-chip-template>
        <span>{{ $chip.id }}</span>
    </md-chip-template>
</md-chips>
```

and the timezone search function

```
var getTimezones = function (search) {
    var regex = new RegExp(search, 'i'), results = [];
    angular.forEach(self.timezoneList, function(timezone) {
        if(regex.test(timezone.id)) {
            results.push(timezone);
        }
    });
    return results;
};
```

Screenshot of the output

<img width="589" alt="screen shot 2015-11-11 at 15 24 15" src="https://cloud.githubusercontent.com/assets/773633/11094566/50148190-8888-11e5-95e3-4ad18dcf7ef3.png">

However there are 4 results that should be showing, and the height of the container looks like it should be able to hold more like 5 entries.

I am not sure where the root cause is, perhaps with the virtual repeater that is trying to auto-size? But the ng-repeat inside the virtual container is only performing 3 repeats from the 4 entries, screenshot of the dom incase it helps...

<img width="899" alt="screen shot 2015-11-11 at 15 27 01" src="https://cloud.githubusercontent.com/assets/773633/11094645/b8b7b42e-8888-11e5-8784-504eedf4c1d9.png">

Note: This is with 1.0.0-rc3

**Comment by hillerstorm** [comment]
duplicate of #5606, #5611 and #5630

**Comment by gabguy** [comment]
+1

**Comment by andrew-cunliffe** [comment]
This appears to be working fine in rc4 again, thanks
