### ISSUE TITLE
Radio buttons don't align with checkboxes

### ISSUE THREAD

**Issue by mschering** [angular/material#5675]
The title and screen say it all.
![alignment radio and checkboxes](https://cloud.githubusercontent.com/assets/1314447/11095488/797df946-8895-11e5-8bd9-d37a3ee2d9aa.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
