### ISSUE TITLE
md-autocomplete ignores md-min-length with md-input-name

### ISSUE THREAD

**Issue by dohomi** [angular/material#5678]
Hi Guys,

the current implementation ignores the ```md-min-length```in combination of an input field with the ```md-input-name```attribute.

Here is a sample codepen, I set ```md-min-length="0"```but the autocomplete-dropdown is only shown after typing into the input.
http://codepen.io/anon/pen/LpXqmG
Any idea how to programmatically open the dropdown, this could solve the issue for now. I tried setting the focus but still no result. Thanks!

**Comment by DmitryEfimenko** [comment]
+1
I don't think this has anything to do with `md-input-name` attribute. Deleting it in the provided plunker does not fix the issue.
The title should be updated.

**Comment by spoco2** [comment]
I certainly seem to be having this exact problem. md-min-length is doing nothing for me setting it to 0. The examples on the demo site all work when you first click in them, showing the full list, but the expression for returning the list never gets called on click for me, only when I type one character.

**Comment by gpopovic** [comment]
I'm also having this problem...Also works when i type something and then delete it

**Comment by spoco2** [comment]
@gpopovic Yes, that's the exact behaviour... clicking does nothing on an empty input... add a character (and it starts working). Delete that character, so be back at blank, and the suggestions will appear too.

**Comment by dohomi** [comment]
Hi guys,

to be honest, I don't see this as deprecated. Its just not working setting up `md-autocomplete`to `md-input-minlength="0"` and here is the codepen to show the behaviour:
http://codepen.io/anon/pen/ONBvgE
It would be nice to get this fixed, I don't understand why internally `md-autocomplete` behaves different as input field.

Would be nice if this could get fixed.
