### ISSUE TITLE
md-grid-tile-footer and header are not even close to Material Design Spec

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#5679]
I know the spec is a moving standard, and you guys are going at a fantastic pace. 

That said, the md-grid-tile-footer and md-grid-tile-header outside of single line height being correct don't really behave at all like the spec says they should 

1 & 2 Line support, Action button on the left or right, proper padding and making sure the text uses ellipsis clipping etc. are all missing

Here is a [codepen] (http://codepen.io/Mopholo/pen/KdrJyx?editors=100) that shows how it works, vs. how it should work ( I think I addressed most of it ) 

Item [3832](https://github.com/angular/material/issues/3832) is included in this 'fix' in styling, I just stuffed the styles in the head section for a quick fix, not optimized, and added some markup to make things work.

While users can of course implement the spec themselves there were quite a few quirks to get it working without inspecting the styles of the current directives.

**Comment by ThomasBurleson** [comment]
See styles in CodePen.

**Comment by Todd-Werelius** [comment]
By the way, the code pen style fixes are now partially broken on action button placement on a few examples after I updated to 1.0.2, haven't figured out why as of yet

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
