### ISSUE TITLE
md-tab content not showing when using md-tab-label

### ISSUE THREAD

**Issue by frikkievb** [angular/material#5689]
Hi,

I noticed unusual behaviour with the md-tabs directive.  When using md-tab-label to define a tabs label, the content will not show up.

Here is a CodePen: http://codepen.io/frikkievb/pen/ojJgXM

Kind regards

**Comment by zoony** [comment]
If you use md-tab-label I think you have to put content in md-tab-body for it to work as expected and not a div.

**Comment by frikkievb** [comment]
Looks like that solve the problem.  Thank you.

**Comment by ThomasBurleson** [comment]
Documentation improvement needed.
