### ISSUE TITLE
Tab is not disabled

### ISSUE THREAD

**Issue by sadiqkhoja** [angular/material#5691]
Tab is not disabled when "disable" attribute is used as mention in the documentation. Here is the codepen where tab2 and tab3 are set disabled="true"

http://codepen.io/sadiqkhoja/pen/MaZYMV

**Comment by DevVersion** [comment]
Hello,
Please don't use the attribute ````disabled```, better use ````ng-disable``` with a given expression.
Here a working example: http://codepen.io/DevVersion/pen/GpPZOW
