### ISSUE TITLE
Ng-message should be optional / using default classes

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#5693]
Hi,
When using another validation library (as of valdr (https://github.com/netceteragroup/valdr)  in my case), ng-messages is created twice, one by valdr and one by md.
We should be able to either integrate both into one or disable md's one &&|| and reuse classes from ng-messages instead of creating classes like md-input-valid.
Haven't find a way to include valdr to a codepen (no cdn and sources only avalaible through bower) so can't provide a demo yet.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
