### ISSUE TITLE
md-tabs

### ISSUE THREAD

**Issue by rafasegat** [angular/material#5695]
Hi

Im using md-tabs in my app project. But it is very slow. I have three tabs 

Tab 1 - Twitter posts with several images and contents
Tab 2 - Almost 15 images
Tab 3 - Google Maps

The the swipe between each tab is very slow. Does someone knows how to make it better?

And im using it with ui-router and sometimes $state.go works and sometimes doesn't work. Grrr

Thanks so much.
Raf

**Comment by EladBezalel** [comment]
These kind of questions is supposed to be in our [Forum](https://groups.google.com/forum/#!forum/ngmaterial),

Please provide a codepen as it might be an issue.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
