### ISSUE TITLE
Ghost tap on md-menu close

### ISSUE THREAD

**Issue by jpike88** [angular/material#5696]
If there is an input underneath an md-menu and I tap the menu, there seems to be a second press that then focuses the input. This is obviously not good and seriously breaks usability.

**Comment by rschmukler** [comment]
What version?

**Comment by jpike88** [comment]
Latest build

**Comment by jpike88** [comment]
I should mention, this only applies to touch devices, happy on both Safari on iOS 9 as well as Crosswalk on Android 4.2.2 (shouldn't matter what android version as it's using recent build of Chromium)

**Comment by ramirezd42** [comment]
This is happening to me as well on with Safari on IOS 9.2., but **not** Chrome iOS 48. Super annoying.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
