### ISSUE TITLE
md-tabs doesn't scroll when width of tab wider than width of md-tabs-canvas tag 

### ISSUE THREAD

**Issue by ildarnm** [angular/material#5697]
For replay, set the window's width less than wide of the second tab.
http://codepen.io/anon/pen/Yydwmz

**Comment by PDSBGreg** [comment]
We can across this the other day as well. You can still swipe or use the mouse wheel to scroll the tabs, which isn't terribly intuitive. We solved it by putting a max width on the tabs to something that would be smaller than our smallest screen size. It does the ellipsis on the overflowing text. That works Ok for our case, but may not for yours.

**Comment by stewones** [comment]
+1 here. thought this had been fixed in rc5, @ThomasBurleson ?

**Comment by stewones** [comment]
my workaround has been adding +1 in updatePagingWidth()
```js
function updatePagingWidth() {
    var width = 1;
    angular.forEach(getElements().dummies, function (element) {
      width += Math.ceil(element.offsetWidth)+1;
    });
    angular.element(elements.paging).css('width', width + 'px');
  }
```

**Comment by danielgranat** [comment]
I encountered the same problem and used the solution proposed by @PDSBGreg of max width. This help in allowing navigation, but visually it doesn't look so good.
Isn't the inability to click the arrow a critical bug for the tabs functionality?

**Comment by EladBezalel** [comment]
dup #4247
