### ISSUE TITLE
Why is md-title size keeping sp unit?

### ISSUE THREAD

**Issue by jkiimm** [angular/material#5700]
Why was `md-title` size [excepted](https://github.com/angular/material/commit/df2ad02d27d28c5ae75ec1034dfaf84c9cc24267#diff-773816d6895941c7bde297bdfbb93179R59)?

It has been still showed up in [typography](https://material.angularjs.org/latest/CSS/typography), is it intended?

**Comment by marcysutton** [comment]
That is a typo.

**Comment by jkiimm** [comment]
Yep, thanks. I'll try that.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
