### ISSUE TITLE
Container for ngMaterial

### ISSUE THREAD

**Issue by AliPoder** [angular/material#5701]
Hello guys,

I have a question about layout system of Material Angular.

As you know we are using "container" class with bootstrap to build our website non-fluid style.

I want to center my web app, how could I done that?

Thanks.

**Comment by PDSBGreg** [comment]
<div layout="column" layout-align="start center"> Is that what you're asking?

**Comment by bastienJS** [comment]
text-align:center HAHA

**Comment by marcysutton** [comment]
This question would be better for the [ngMaterial forum](https://groups.google.com/forum/#!forum/ngmaterial).
