### ISSUE TITLE
smaller, more compact checkboxes and radio buttons

### ISSUE THREAD

**Issue by mg1075** [angular/material#5702]
Overall, the aesthetic of material design is impressive and handles plenty of use cases. 

One area I am finding problematic is the size of checkboxes and radio buttons, or what the material design spec calls [selection controls](http://www.google.com/design/spec/components/selection-controls.html#selection-controls-checkbox).

The checkboxes look decent.
![image](https://cloud.githubusercontent.com/assets/2031435/11122445/e857a714-8920-11e5-9972-db867c6cea09.png)

Yet I think we can all agree the checkboxes and radio buttons are also rather **large** in size, certainly larger than default browser renderings of checkboxes. Some might say they demand more attention than they deserve, and border on being cartoonish. 

Normally, this not a show-stopper, but there is one particular scenario where I think the large size of the checkboxes and radio buttons is **not acceptable**. To illustrate, take this example on the [google public data explorer](https://www.google.com/publicdata/explore?ds=d5bncppjof8f9_&ctype=b&strail=false&nselm=s&met_x=sp_dyn_le00_in&scale_x=lin&ind_x=false&met_y=sp_dyn_tfrt_in&scale_y=lin&ind_y=false&met_s=sp_pop_totl&scale_s=lin&ind_s=false&dimp_c=country:region&ifdim=country&iconSize=0.5&uniSize=0.035#!ctype=b&strail=false&bcs=d&nselm=s&met_x=sp_dyn_le00_in&scale_x=lin&ind_x=false&met_y=sp_dyn_tfrt_in&scale_y=lin&ind_y=false&met_s=sp_pop_totl&scale_s=lin&ind_s=false&dimp_c=country:region&ifdim=country&hl=en_US&dl=en_US&ind=false). 

On the left side of the page is a container displaying a list of checkboxes with countries. As you make your selection, the associated country label appears on the data viz.
![image](https://cloud.githubusercontent.com/assets/2031435/11122772/4bc3938e-8922-11e5-8405-3fe18abca546.png)

Now imagine if this same list of checkboxes and countries used the google material design spec to render the checkboxes. I believe the resulting list would be a usability disaster, because the spacing needed for the checkboxes would mean you could only see a few options at a time, and the size of the checkboxes would take attention away from the primary data viz. The same would be true for radio buttons using the material design spec.

The two issues to sort out are: 
1. Does the google material design spec properly address the scenario above? 
(The lack of evidence points to **no**, or if it implicitly does, then perhaps the design spec is flawed)
2. Most importantly, **what is the optimal way in angular-material to reduce the size of checkboxes and radio buttons for the scenario described above**?
* create custom css classes for checkboxes to override the default classes related to line-height, borders, etc.?
* other? maybe this has been addressed elsewhere?

**Comment by robertbaker** [comment]
Yes override css.

I would argue that the UX design here is the issue and not the material design spec. A bunch of select boxes and checkboxes isn't great.
