### ISSUE TITLE
uiSrefActive should be copied to child elements along with uiSref

### ISSUE THREAD

**Issue by gligoran** [angular/material#5704]
You guys have done a good job including more support for uiRouter lately. I've had to hack this in previously, but with the last few relases, I noticed more and more components copy ```uiSref``` attribute to child elements where applicable. For example on ```mdListItem```.

I'd argue that [```uiSrefActive```](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref-active) should be copied too. In the case of ```mdListItem``` in particular this would allow for styling the ```md-button``` which is created because of the presence of ```uiSref```. A very basic example would be using it like so ```uiSrefActive="md-primary"```.

Same goes for directive [```uiSrefActiveEq```](http://angular-ui.github.io/ui-router/site/#/api/ui.router.state.directive:ui-sref-active-eq).

**Comment by ThomasBurleson** [comment]
@EladBezalel - I think we should maintain an internal whitelist of uiRouter attributes to copy.

**Comment by EladBezalel** [comment]
@ThomasBurleson this is a great idea.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
