### ISSUE TITLE
Feature request - $mdDrawer instead of $mdBottomSheet, which draws from top or bottom

### ISSUE THREAD

**Issue by Chidan** [angular/material#5705]
Hi,
This is not a bug report but a feature request.
Could we have a top drawer similar to md-bottom-sheet?
Ideally it would be great if we could mention in the options of service $mdBottomSheet - "top" or "bottom". And this new component could be named md-drawer instead of md-bottom-sheet
I tried to do some hacks with $mdBottomSheet service but couldnt manage the result.
Any one out there who could suggest a hack before the feature gets accepted and released.
Thanks in advance.

Regards,
Chidan

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
