### ISSUE TITLE
<md-card>, <md-card-content> flex-sm='100' in Safari has computed height of 0

### ISSUE THREAD

**Issue by getglad** [angular/material#5708]
Something is up with <md-card> in Safari on the smallest size. I realize that is not super helpful, but I have not been able to figure out what the diff is yet. I have tested this on iOS Chrome / Safari (most recent) and OSX Safari with the window shrunk down (user agent Safari 9 + 8.1). This is not true for OSX Chrome or Firefox, and everything is fine for Chrome on Android and IE/Chrome/Firefox on Windows.

md/lg/gt-lg all seem to be fine.

iOS/Safari:
![iOS - Chrome](https://cloud.githubusercontent.com/assets/2453555/11132721/3734a478-8957-11e5-850c-953e35b57e95.PNG)

Chrome/Android:
![Android - Chrome](https://cloud.githubusercontent.com/assets/2453555/11132722/373938bc-8957-11e5-975b-45ea4d6a4373.png)

**Comment by getglad** [comment]
So I have looked through the CSS and while I see no difference in the styles, the computed style of <md-card> and <md-card-content> have a height of 0. I tried a few different settings, and found that if flex-sm='100' I get the issue; if flex-sm='99', there is no problem. I am updating the name of the issue now that it is more isolated.

**Comment by Wardormeur** [comment]
Could be related to https://github.com/angular/material/issues/5382

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
