### ISSUE TITLE
md-menu

### ISSUE THREAD

**Issue by shivasingh0101** [angular/material#5710]
MD-menu showing the following error when trying to access the menu-items

'TypeError: Cannot read property 'open' of null'
here is the screen shot of the error.

![error_md-menu](https://cloud.githubusercontent.com/assets/12746995/11139172/10717a8c-89f2-11e5-9ee8-a87c6c6b5217.png)

**Comment by RolandHeath** [comment]
Duplicate of #5659 #5628 #5614 #5604
