### ISSUE TITLE
md-autocomplete and $mdDialog: md-scroll-mask added when dialog closed

### ISSUE THREAD

**Issue by kierenj** [angular/material#5715]
Hi have an `<md-autocomplete>` in a template for `$mdDialog`.

When I close the dialog without first opening the autocomplete box (via a cancel button, but I don't think that's important), an md-scroll-mask div is added over the body, rendering the app unusable from that point.

If I instead open the md-autocomplete first, select an item, then close the dialog, the md-scroll-mask is not added.

I believe this is a bug with md-autocomplete rather than $mdDialog, since it occurs even if I set the disableParentScroll option on the mdDialog options object to false.

**Comment by kierenj** [comment]
(Am working around currently with `$('.md-scroll-mask').remove();`)

**Comment by sousa22** [comment]
+1, md-scroll-mask is in front of the whole page when selecting an item

**Comment by anishbenji** [comment]
+1
I have a use case similar to this, in which I have a button that creates & removes the autocomplete input widget and I run in to the same issue when the widget is removed.

**Comment by danazelniker** [comment]
Having similar issue. I have md-selected-item-change defined to navigate to a new angular state. in this case the md-scroll-mask is added on the body preventing me working with the app.

**Comment by Wingie** [comment]
+1

**Comment by naorz** [comment]
+1
In my case I have ng-if on an auto complete wrapper.
After the selection, the auto complete was closed then I fire an HTTP request.
Afterwards the request arrived I turned ng-if of the auto complete wrapper to Off (false)
and the md-scroll-mask still stay active.

**Comment by leibale** [comment]
+1

**Comment by topherfangio** [comment]
Looks like this was just fixed in PR #7291. Please comment if it does not fix your issue and we will reopen.

**Comment by xtinaco** [comment]
Not fixed

**Comment by Splaktar** [comment]
@xtinaco please open a new issue with a CodePen reproduction and we will investigate.
