### ISSUE TITLE
Dialog "Open From Close To"

### ISSUE THREAD

**Issue by Shyiy** [angular/material#5722]
In the just released 1.0.0rc4 version, the demo page for dialogs, section "Open From Close To" doesn't display any dialog due to errors.

**Comment by DevVersion** [comment]
I created a PR, which fixes this, I think @jelbourn just forgot this ;) can happen

**Comment by Nosthertus** [comment]
This also happens to me on the demo page.. i am using Mozilla Firefox

**Comment by DevVersion** [comment]
As I already said. I fixed the issue, I'm still waiting for merge

**Comment by jelbourn** [comment]
Fixed in b9dae8d1e83bbbdd340b6617e04bc42a321ea3b2
