### ISSUE TITLE
Unable to use md-virtual-repeat="(key,value) in Object"

### ISSUE THREAD

**Issue by vigneshnrfs** [angular/material#5724]
I would like to use key value pairs in md-virtual repeat. But it doesn't seem to be working like it works in ng-repeat.

Is it not implemented yet? or am I doing something wrong

http://codepen.io/anon/pen/JYwwLB

**Comment by kseamon** [comment]
It's not implemented.

**Comment by johndshea** [comment]
I ran into this same issue. For some use cases (including mine), a good workaround is to convert the key-value pairs to a two dimensional array (using, for instance, [Object.entries()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)) and then use md-virtual-repeat to iterate over the resulting array.
