### ISSUE TITLE
1.0.0-RC4 CDN not available

### ISSUE THREAD

**Issue by bastienJS** [angular/material#5730]
https://developers.google.com/speed/libraries/#angular-material

Please make 1.0.0-RC4 available.

**Comment by DevVersion** [comment]
I think this will be done at Monday. Meanwhile you need to wait or use another cdn (http://cdnjs.com/libraries/angular-material)

**Comment by bastienJS** [comment]
Thanks, at the time posting here the cdnjs.com did not offer neither the RC4 version.

**Comment by DevVersion** [comment]
Yes, that's the current Release Candidate 4: http://cdnjs.com/libraries/angular-material/1.0.0-rc4

**Comment by DevVersion** [comment]
The official CDN is now available: <script src="https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc4/angular-material.min.js"></script>
