### ISSUE TITLE
md-virtual-repeat performance to implement infinite scroll

### ISSUE THREAD

**Issue by asiehmokarian** [angular/material#5733]
It is not mentioned in the documents but I wants to ask whether in the implementation of "md-virtual-repeat",  rows that became invisible as they scroll out of the view, are still a part of the page and are still consuming resources? If yes, This will affect the performance of app for large amount of data and it is good to handle this problem like as uiScroll does. Means destroying out of view elements when become out of view an recreating them when coming to view.

**Comment by maximethebault** [comment]
A simple check to the DOM tree with a web developper tool will answer your question: no. When they're going out of view, rows are destroyed.

**Comment by asiehmokarian** [comment]
Thank you, As I am a beginner this test didn't get to my mind. So if they are recreating again, are they receiving from the server again? Is there any caching service available or caching should be handled by developer using angularJS service?
Not providing caching doesn't cause problem for a slow internet speed? Means that when the user gets back to the up of the window rapidly, maybe they see white screen for a moment.
.

**Comment by maximethebault** [comment]
Maybe you'll get more answers on Stackoverflow :)
http://stackoverflow.com/questions/tagged/angular-material

**Comment by kseamon** [comment]
The dom elements are recycled - (not destroyed, just rebound as needed). Your app is responsible for loading or unloading any data it downloads.
