### ISSUE TITLE
Mobile: Input field immediately blurs after focus

### ISSUE THREAD

**Issue by JohannUlbrich** [angular/material#5734]
I want to use a default HTML label and input field on my page to show the virtual keyboard on mobile devices when clicking on the label. But on mobile devices the input field immediately blurs after it gets the focus (tested with iPhone and Nexus 5).

    <div>
      <label for="test1">Test1</label>
      <input ng-model="user.name" type="text" id="test1">
    </div>

http://codepen.io/anon/pen/meaNra

**Comment by EladBezalel** [comment]
What browser? Works on my LG G3 with Chrome latest

**Comment by JohannUlbrich** [comment]
I use the latest Chrome on Nexus 5 and Safari/Chrome on iPhone. 
I think it is a touch event issue, because it also happens with the latest Chrome on Windows with device simulation.

**Comment by EladBezalel** [comment]
I can't reproduce with my touch screen, more than that, i can't seem to find any thing related to our project as your'e not using any of our components, 

You can also see on [line 188](https://github.com/angular/material/blob/master/src/components/input/input.js#L188) on input, if you're not using our input container we leave the input alone.
