### ISSUE TITLE
Can a contenteditable element have the same styling as an md-input textarea?

### ISSUE THREAD

**Issue by begot** [angular/material#5736]
Is there a way I can make a contenteditable div similar to an md-input textarea?

This would be amazing for a project I'm working on, currently all contenteditable elements will be as default.

**Comment by EladBezalel** [comment]
@begot these kind of questions are supposed to be asked at our [Forum[(https://groups.google.com/forum/#!forum/ngmaterial)

For your question, you should copy the css and apply it to your div.
