### ISSUE TITLE
md-autocomplete : items not displayed after that the clear button has been clicked

### ISSUE THREAD

**Issue by NicolasBlois** [angular/material#5737]
To reproduce : 
1) Select an item from the list
2) Click clear button
3) Select "Louisiana" state (need to scroll in the list to reproduce)
4) Clear again

![out-8](https://cloud.githubusercontent.com/assets/6443098/11166676/7d697f46-8b40-11e5-835f-7f6c23b30fb7.gif)

**Comment by pmchugh3** [comment]
+1 Seems like the options re-appear when you scroll.

**Comment by antoinebrault** [comment]
+1 happens to me to when searchText is cleared programmatically.

**Comment by antoinebrault** [comment]
If anyone is looking for a temporary fix:

```javascript
$scope.$watch('vm.searchText', function (newValue, oldValue) {
	if (newValue && oldValue === '') {
		var ctrl = angular.element('md-virtual-repeat-container.md-autocomplete-suggestions-container')
			.controller('mdVirtualRepeatContainer');

		if (ctrl) {
			$timeout(function () {
				ctrl.resetScroll();
			}, vm.debounceSearchText + 125);
		}
	}
});
```

**Comment by ThomasBurleson** [comment]
Already fixed in HEAD.
