### ISSUE TITLE
Themes background color not changing

### ISSUE THREAD

**Issue by okpatil4u** [angular/material#574]
Should background color change with themes ?
It seems that theme [demo](http://plnkr.co/edit/0Ga0BSJgjGIiEMVXgWJd?p=preview) plunker in material.angularjs.org  is broken.
Can someone please confirm this issue ?

**Comment by rschmukler** [comment]
Background colors should not change depending on theme. Right now only light and dark backgrounds are supported. Certain components (such as `md-toolbar`) will have background-colors set by the theme, but for the most part material design does not encourage strongly colored backgrounds.

**Comment by futurechan** [comment]
I'm also looking for a solution to this I saw the [material-ui](http://callemall.github.io/material-ui/#/) site, and the main content on the home page that appears above the fold matches the toolbar. I'd like to achieve the same thing with a theme. Is that possible?
