### ISSUE TITLE
md-tabs-item shrink to zero on page refresh

### ISSUE THREAD

**Issue by agroezinger** [angular/material#5743]
Got some weird behavior of md-tabs. I've built a bottom navbar using tabs. Now, if u do a page refresh using the refresh button of the browser, the tab item gets a max-width: 0px; style attribute. It does not happen every time. I have checked the following szenarios:

- i think it is a problem wit the angular material style sheet as I cannot rebuild this behavior with the rc3 css
- the problem is caused by the rc4 css style sheet as far as I could explore the issue
- the problem is as far as I could explore the problem only happening on mobile browsers. Further only on iOS (currently using an iPhone 6). With an android device I could not see the problem. 
- the tabs get the correct size if Ii rotate into landscape and back  
- the problem on iOS happens in every browser. Tested it with Safari, chrome and firefox.

I have Build two examples at my webspace. The difference between both is just the style sheet. Issue example working with current rc4 css. The non issue version included the rc3 css

Issue: http://issue.agmedia.de/issue.html
No Issue: http://issue.agmedia.de/noissue.html

 
![image](https://cloud.githubusercontent.com/assets/12061647/11169554/d28eb560-8bbb-11e5-812d-89119f4f2551.png)
![image](https://cloud.githubusercontent.com/assets/12061647/11169556/d3217562-8bbb-11e5-9ab7-2218d1fa3afa.png)
![image](https://cloud.githubusercontent.com/assets/12061647/11169580/1fe09bf8-8bbc-11e5-8641-ce7c4df8969f.png)

**Comment by agroezinger** [comment]
After a bit more testing:
Tested on iPhone 6 and 5
Safari on iOS 9 => problem is happening
Safari on iOS 8 => problem NOT happening

Chrome on iPhone 5&6 on iOS 8&9 is happening

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
