### ISSUE TITLE
Dropdowns(menu, select) should be white on black theme

### ISSUE THREAD

**Issue by zeprone** [angular/material#5744]
md-select does not depend on theming.
This codepend shows the issue : http://codepen.io/anon/pen/GpzZro

**Comment by EladBezalel** [comment]
![image](https://cloud.githubusercontent.com/assets/6004537/11171334/2665a312-8bf6-11e5-8e26-25778af4159d.png)
This is taken from [Material Spec](https://www.google.com/design/spec/style/color.html#color-themes)

**Comment by zeprone** [comment]
Any plan on a merging date ? I have an application which is using a dark theme.

**Comment by Jonybang** [comment]
It broke again this PR: #1950
