### ISSUE TITLE
RC4: Rows attribute doesn't resize textarea when no content

### ISSUE THREAD

**Issue by chr22** [angular/material#5751]
Textareas are always rendered with only one row if there isn't any content in it.

See this [CodePen](http://codepen.io/chr22/pen/dYgabY)

It also limits the height of the textarea to the number of rows set.

**Comment by DevVersion** [comment]
Yeah.
- The limit of the textarea is the intentional behavior.

Here is again my second fix for the textarea, this one should work perfectly (100%) it tested it a lot of time

**Comment by Nexxado** [comment]
temporary "hack": 
fill your binded model with '\n' for the amount of rows.

html:
`<textarea required name="message" ng-model="contactDetails.message" rows="5"></textarea>`

js (controller):
```
$scope.contactDetails = {
        ....
        message: "\n\n\n\n\n" //fix for textarea remaining at 1 row.
    };
```

**Comment by alexilyaev** [comment]
+1, very confusing, as you'd expect `rows="5"` to allocate 5 empty rows.  
This is essential since you sometimes want to show a big empty textarea so the user gets that they can put in a long message.

**Comment by EladBezalel** [comment]
@DevVersion take a look

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
