### ISSUE TITLE
[md-select] md-select-menu-container position is wrong.

### ISSUE THREAD

**Issue by Elfayer** [angular/material#5754]
When I open a md-select box, the md-select-menu-container top position is too high. I've tried to reproduce the issue on a JSFiddle, but didn't succeed. Although I always have the issue every first time I open a select box. Every time after it works properly. Any thought ?

I'm in v.0.11.0-rc2, I've tried with different versions, I have the same outcome.
![image](https://cloud.githubusercontent.com/assets/15869149/11179600/dd116b92-8c54-11e5-8dc3-fd88117f6a37.png)

**EDIT:** I'm working on an iframe that is not taking the whole window. Could that be a problem ?

**Comment by Elfayer** [comment]
What is the line number where the top position of the md-select-menu-container is set ?
I'd like to look at it.

**Comment by Elfayer** [comment]
I found a way to correct the view with the following code:

`$timeout(function () { angular.element($window).triggerHandler('resize') }, 15);`

I added this line of code at the end of the promise and it corrects the position. I saw that the resize of the window corrected the position issue, so I simulated one. Although I had to set a timer because without it, it doesn't work every time. I suspect it is because there is a small animation on the box.

Anyway, this isn't a **fix**, I just hope this can help to find a way to correct it in the library. I didn't find the line I was looking for.

**Comment by kiro64** [comment]
this still error and  also happen in demo page. currently 1.0.0-rc6

**Comment by vapits** [comment]
![image](https://cloud.githubusercontent.com/assets/8594758/12781723/632ace12-ca76-11e5-9d38-a72e54075d7f.png)
+1

**Comment by reinos** [comment]
+1

**Comment by MariskaS** [comment]
+1

**Comment by vapits** [comment]
Have you managed guys to replicate the error yourselves?

**Comment by reinos** [comment]
Any update on this issue?

**Comment by jayeshanandani** [comment]
Why are we keeping this as backlog or Deprecated? This is still an issue with latest master version. I believe positioning of select makes options unreadable specially when present below header.

**Comment by vapits** [comment]
@ThomasBurleson an update on this issue. At least we managed to figure out WHEN it happens.
> When you call a function on md-open then the reported issue is happening.

Hope now that you can find out more.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
