### ISSUE TITLE
Virtual repeat in table elem

### ISSUE THREAD

**Issue by marlonmleite** [angular/material#5755]
Hello,

I'm trying to use the Virtual Repeat in one table, but when you turn on the virtual vertical scroll, I have problems when there is native scroll horizontally.
I have performance issues only in the vertical scroll.
I tried doing this:

```
.md-virtual-repeat-container {
   overflow-x: auto;
}
```
My result was that when the scroll movement:
![Image of Yaktocat](http://code2.sankhya.com.br/img/grid.jpg)

Solutions?

**Comment by vandalsvq** [comment]
You can bind to scroll event and set right style-attr in scroller div (class='md-virtual-repeat-scroller').

var table = someElement.find('table');
angular.element(table[0]).on('scroll', function() {
    var table = someElement.find('table');
          left    = table[0].scrollLeft;
          // table.children() - this is scroller div
          angular.element(table.children()[0]).css('right', '-' + left + 'px');
});

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
