### ISSUE TITLE
md-datepicker gets distorted when a header tag is present before directive

### ISSUE THREAD

**Issue by anant-jain** [angular/material#5756]
![image](https://cloud.githubusercontent.com/assets/10812536/11181563/02818bda-8c89-11e5-84a6-fa48cafbaef1.png)

**Comment by jelbourn** [comment]
@anant-jain Is this still happening in the latest release? Can you reproduce this in something like CodePen (or JsBin, etc.)?

**Comment by jelbourn** [comment]
Closing this for lack of ability to reproduce. Can re-open if someone can provide a CodePen or similar.
