### ISSUE TITLE
Datepickers position going wrong if page is scrolled down except on Chrome

### ISSUE THREAD

**Issue by Seiifer** [angular/material#5758]
Datepickers (the calendar where we can select a date, not the input) appear at a wrong position (except the first one) if I'm not using Chrome :

You can try it using this codepen : http://codepen.io/anon/pen/pjGPGZ?editors=101

Just scroll down using firefox and try to use the last datepickers.

The position seems to be correct if all the `<md-datepicker>` are at the top of the page next to each other, but as soon as we need to scroll down a bit, the positioning is failing.

**Comment by Seiifer** [comment]
It looks that this bug might occur only on windows and not on mac.

**Comment by defcronyke** [comment]
This issue is happening to me on Firefox 42.0 on Linux. I can't use any datepickers that are lower down on the page because when I click the icon, the calendar gets displayed much higher up on the page and scrolling gets disabled. It does not happen on Chrome.

**Comment by Seiifer** [comment]
Any label incoming ? I'd like to know to what priority this issue is judged.

**Comment by jelbourn** [comment]
I just tried this out on the latest master, and it seems to be fixed. I suspect it was addressed by d423a65600cb6dc2638c91882b38be2dfea965f8
