### ISSUE TITLE
Bug on device. I need to tap twice out of Autocomplete to change input focus.

### ISSUE THREAD

**Issue by lucasmartinez** [angular/material#5761]
Try this. Open chrome in Device mode view. Open autocomplete demo.
Go to floating label. Write AL to display list options. Select one item (ALABAMA). 
After selecting one input, click Name input. On first click, nothing happens. I need to click twice to change input focus.

**Comment by dnd** [comment]
I'm experiencing the same running on a pull from master as of yesterday.

**Comment by runethh** [comment]
+1

How to reproduce: 

1. Open menu
2. Select Autocomplete
3. Start typing fx Was and select Washington from the autocomplete list. Note that the field remains active (the text marker is still blinking in the field).
4. Scroll down and tap the text field in Custom Template. Observe that the page jumps back to the active field that you've already field.

Tested on:
Model: Nexus 6 (Shamu)
Operating system: Android Lollipop 5.1.1 (LMY47Z)
Browser: Chrome 46.0.2490.76

Note that this is not an issue on this device :
Model: Iphone 6 (MG4F2QN/A)
Operating system: iOS 9.1 (13b143)
Browser: Safari 9.0 mobile

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
