### ISSUE TITLE
Gulp docs command error

### ISSUE THREAD

**Issue by spenoir** [angular/material#5762]
It looks like theres an error in angular-material while building the docs:

$ gulp docs
[18:16:06] Using gulpfile ~/angular-material/gulpfile.js
[18:16:06] Starting 'build-scss'...
[18:16:06] Building css files...
[18:16:06] Starting 'build-js'...
[18:16:06] building js files...
[18:16:08] Plumber found unhandled error:
 Error in plugin 'gulp-uglify'
Message:
    /Users/spenoir/angular-material/dist/angular-material.js: Unexpected token punc «;», expected punc «,»
Details:
    fileName: /Users/spenoir/angular-material/dist/angular-material.js
    lineNumber: 23301
[18:16:08] Finished 'build-js' after 1.84 s
[18:16:08] Finished 'build-scss' after 1.87 s
[18:16:08] Starting 'build'...
[18:16:08] Finished 'build' after 19 μs
...

I'm not sure whether I can just ignore that one or not, in that it still builds the docs

**Comment by DevVersion** [comment]
Its really hard for us, to figure the problem out. 
Because we don't know your current code
Here you can see something interesting
- ```Unexpected token punc «;», expected punc «,»```

Perhaps you can share your ```angular-material.js``` file with us, then we will check at line 23301

**Comment by spenoir** [comment]
I've only just cloned the repo so should be exactly the same but I'm happy to share it anyway if you think it is necessary

**Comment by DevVersion** [comment]
Yeah, then we can investigate more :+1: so its enough if you only share your ```angular-material.js``` file.

**Comment by spenoir** [comment]
but this file is generated by gulp isn't it? I haven't edited it at all. If you could try cloning the repo, npm installing then `gulp docs` and you don't get the error then its probably my stupid fault

**Comment by DevVersion** [comment]
I definitely didn't get the error, I'm compiling angular every day for working, so I know what I do.
So share your code, or we / I can't help you

**Comment by EladBezalel** [comment]
What version of node you're running?

**Comment by spenoir** [comment]
I've tried with 4 and 5 so far. I've found that gulp-sass needs updating to 2.1.0 in packages.json when running node 4+. I still get the Unexpected token punc «;», expected punc «,» error though.

Heres what line 23300 looks like which was extremely long, I've edited due to very long length:

`angular.module("material.core").constant("$MD_THEME_CSS", "md-autocomplete.md-THEME_NAME-theme {  background: '{{background-50}}'; }  md-autocomplete.md-THEME_NAME-theme[disabled] {    background: '{{background-100}}'; }  md-autocomplete.md-THEME_NAME-theme button md-icon path {    fill: '{{background-600}}'; }   ... <edited for brevity> ...   .md-THEME_NAME-theme .md-datepicker-input::-webkit-input-placeholder, .md-THEME_NAME-theme .md-datepicker-input::-moz-placeholder, .md-THEME_NAME-theme .md-datepicker-input:-moz-placeholder, .md-THEME_NAME-theme .md-datepicker-input:-ms-input-placeholder {    color: \"{{foreground-3}}"; })
`
It looks like the last `"` isn't getting escaped for some reason

**Comment by DevVersion** [comment]
So as we can see here: ```gulp-uglify````the problem is related to the uglify task.
So I think it's not a sass error (the theming scss is compiled in js) that's perhaps why the uglify task throws an error.

**Comment by DevVersion** [comment]
Thanks for sharing the compiled source with us.
I think you are right with the unescaped bracket... we should look for the current css selector, in this case the ```.md-THEME_NAME-theme .md-datepicker-input:-ms-input-placeholder```

**Comment by spenoir** [comment]
Had a quick look for that theme string but it only appears in
theming.spec.js and angular-material.js. If the compiled scss always used
single quotes uglify probably wouldn't misbehave. I'm not sure how you'd
achieve this though.

**Comment by DevVersion** [comment]
Please recheck my edited post from before.
I also found a duplicate issue #5145

**Comment by spenoir** [comment]
Yeah I see. I'll just wait for the fix to be released from this issue: https://github.com/angular/material/issues/5145

thanks for listening!

**Comment by DevVersion** [comment]
No problem :smile: 
I'm always up for questions ;)
