### ISSUE TITLE
mdAutocomplete: floating label input padding too large

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#5764]
The padding on md-autocomplete does not match other input sizes.  See an example here: http://codepen.io/mckenzielong/pen/RWvxQv  The text and select boxes have equal spacing, and the md-autocomplete is just slightly larger.

This was introduced after a fix to correct the placement of the progress bar:  https://github.com/angular/material/commit/44d1636b27d2dbd873f3844c1e15f9560d188daf

#### Browser
Opera 33 (Chrome 46) Windows 7, BB10.3.2 webkit

#### Reproduce
See this code pen: http://codepen.io/mckenzielong/pen/RWvxQv

#### Suggested fix
Haven't looked at the scss, but only the generated css file... probably isn't this straight forward: remove the 26px padding-bottom and adjust the bottom to be 16px instead of 40px.

**Comment by DevVersion** [comment]
Yes @epelc.

You are right :+1: What do you think, should we only add the padding if ngMessages is present?

**Comment by pmchugh3** [comment]
+1. Have noticed some inconsistencies in the heights of the autocomplete, select and inputs which means we have had to fiddle with CSS to get the padding correct.

**Comment by DevVersion** [comment]
Yeah the problem is definitely the floating label at the autocomplete.
(```&[md-floating-label] md-input-container```)

I'm currently hanging on the ```$input-error-height```. It was placed by sense, so we can't remove it without thinking

**Comment by mattdanna** [comment]
Probably worth mentioning here that not only is the label positioning off, but also the input text.

black = Material Design [spec](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3dWFoM3V0NldkWFU/components_textfields_labels3.png)
red = current ngMaterial implementation (1.0.0-RC6)
![image](https://cloud.githubusercontent.com/assets/1121110/11641428/12877692-9ced-11e5-849c-0e1139525d43.png)

While aesthetically insignificant on an individual component, when the elements of multiple components' in a form are not aligned, it makes the page look unpolished.
