### ISSUE TITLE
md-menu-bar: md-menu-content wrongly placed inside of md-dialog

### ISSUE THREAD

**Issue by gbruins** [angular/material#5765]
Probably related to this issue:
https://github.com/angular/material/issues/4613

When putting a md-menu-bar inside a md-dialog-content  of a md-dialog, by clicking on a md-menu button, the md-menu-content (the menu item sub-list) is wrongly placed at the center of the tab, and not next to the button that triggered it open.

This codepen duplicates the issue:
http://codepen.io/anon/pen/zvepRE

**Comment by fjbatresv** [comment]
Hello, I have a similar issue.

I have something like this:

` <md-toolbar class="md-menu-toolbar">
                    <div layout="row">
                        <md-toolbar-filler layout layout-align="center center">
                            <a style="color: white; text-decoration: none;" ng-href="#/" href="#/">
                                <img class="app-icon" src="assets/icono-ddc.png">
                            </a>
                        </md-toolbar-filler>
                        <div style="width: 100%;">
                            <h2 class="md-toolbar-tools">Data Dealer Centralizer</h2>
                            <md-menu-bar class="inline">
                                <md-menu>
                                    <button ng-click="$mdOpenMenu()">
                                        <i class="material-icons">library_books</i> Cátalogos
                                    </button>
                                    <md-menu-content>
                                        <md-menu-item>
                                            <md-button ng-href="#/alarmas">
                                                Alarmas
                                            </md-button>
                                        </md-menu-item>
.....`

And when i scroll down on the  page with a menu opened this come down with me.

<img width="513" alt="2016-02-26_10-58-04" src="https://cloud.githubusercontent.com/assets/7740766/13359057/ddabcf2a-dc77-11e5-93a0-768b706e3966.png">

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (620/500 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:57954 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdM-000Lmi-LU
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:34:00 -0500
Date: Thu, 28 Apr 2016 13:32:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875547;
	bh=XbgIy+IxEyfOgV66mqYXyT+WuLrOHKrI+q/LnCVDAnY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=FrtKcjvb4c6qQTlKuEzMUkz7FgY3NDdpr2I2MBrjpwVu6N/q4VEt1tnDkABjXsC+z
	 i/pNTDBB5Fy88XDrJnpptZPV8ALmjxI5aAwHDxGFHQhJOXTWW84IWyJe2O22ZXnB05
	 11rmSACQn8eA5AtZahB1gdqMIvn8YCRBvDZ7SDLg=
