### ISSUE TITLE
Focused radio buttons don't submit form on Enter

### ISSUE THREAD

**Issue by mlibby** [angular/material#577]
To reproduce:
Construct a `<form>` with `md-radio-group` any positive number of `md-radio-button` elements and a submit button.
Use the keyboard to focus the radio button group.
Press Enter.
Notice that the submit button is not activated.

Expected result:
The submit button should be activated.

Rationale:
Typical user agent behavior for forms is that pressing Enter while focused on a form element triggers an "implicit" submit (activate the submit button, if one is available). This is the behavior of the native control in Firefox and Chrome. http://www.w3.org/TR/html5/forms.html#implicit-submission

**Comment by mh03r932** [comment]
I think there is still a problem with md-radio-groups and form submission.

When there is no ng-submit handler configured directly on the form but there is a button with type=submit then the angular specification says that the click handler of the first type="submit" button should be triggered (see https://docs.angularjs.org/api/ng/directive/form section "Submitting a form and preventing the default action"). 

This works for normal input elements but not for md-radio-buttons.

JS Fiddle to demonstrate the issue:
http://jsfiddle.net/hh5xh7gf/

Maybe this issue could be reopend?
