### ISSUE TITLE
layout not working correctly when using layout-gt-*

### ISSUE THREAD

**Issue by epelc** [angular/material#5772]
The `layout` attributes are not working correctly in 1.0.0-rc4. It seems to be swapping height/width percentage attributes when you have a switch between row/column depending on the breakpoint.

I'll get a demo together but I just wanted to report this early as I had to upgrade from 0.11.2 to 1.0.0-rc4 to fix some autocomplete issues.

Tested in chrome  46.0.2490.86 m (64-bit) and firefox 42.0 on windows 7

![image](https://cloud.githubusercontent.com/assets/5204642/11195904/8dffafe0-8c82-11e5-9cbe-1e5f7d74de87.png)

**Comment by epelc** [comment]
Just went back through the versions and it looks like it appeared in 1.0.0-rc1

**Comment by DallanQ** [comment]
Swapping the max-width and max-height (in several places in the css file) fixes the bug for me as well.

**Comment by epelc** [comment]
Be careful. That method will introduce bugs!

The real problem is that the flex attributes aren't respecting 'layout-gt*'. I'm not sure if it can even be fixed with css alone now.

However I found a much better work around.

Instead of something like this
'layout="column" layout-gt-sm="row"'

Get rid of the default layout and explicitly set it for the smal breakpoint.
'layout-sm="column" layout-gt-sm="row"'

**Comment by DallanQ** [comment]
Hmm, that's what I had initially. When the window is large, the css uses the layout-gt-* layout rules, which are swapped as you pointed out. It seems that I have to fix the particular layout-gt-* rules that my app is using.

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

---

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).

**Comment by epelc** [comment]
@ThomasBurleson Here is a [demo](http://codepen.io/anon/pen/eJmvMy?editors=101) showing this still exists in 1.0.0-rc6


This (demo)[http://codepen.io/anon/pen/wMBJXG?editors=101] shows it's also still there in master

Here's a picturing from the demo showing how `max-width` and `max-height` are switched.
![image](https://cloud.githubusercontent.com/assets/5204642/11639701/5aa2f2c6-9cfc-11e5-8cbf-41cad846e017.png)

**Comment by ThomasBurleson** [comment]
This is not a bug:

* Note that the mq breakpoint for `layout-gt-md="row" ` is  >1280px; @see [Material Breakpoints](https://camo.githubusercontent.com/ad81ae92f8b4285747ce4e48007bf3f104dd5630/687474703a2f2f6d6174657269616c2d64657369676e2e73746f726167652e676f6f676c65617069732e636f6d2f7075626c6973682f6d6174657269616c5f765f342f6d6174657269616c5f6578745f7075626c6973682f3042386f6c5631354a3761625053474678656d46695156527462316b2f6c61796f75745f61646170746976655f627265616b706f696e74735f30312e706e67) and [Layout docs](https://material.angularjs.org/HEAD/layout/introduction).
* You second card does not have a flex assigned... with:
```
<div layout="column" layout-gt-sm="row" >
            <md-card flex-gt-sm="60">
                <h2>Card title</h2>
                <md-card-content>
                    <p>Some content</p>
                </md-card-content>
            </md-card>
            <md-card flex >
                <h2>Card title</h2>
                <md-card-content>
                    <p>Some content</p>
                </md-card-content>
            </md-card>
        </div>
```
![screen shot 2015-12-07 at 3 41 02 pm](https://cloud.githubusercontent.com/assets/210413/11640646/493cc992-9cf9-11e5-819e-772695c55a0d.png)

**Comment by ThomasBurleson** [comment]
Okay, I see the issue here. It is a CSS specificity issue:

![screen shot 2015-12-07 at 3 53 32 pm](https://cloud.githubusercontent.com/assets/210413/11640928/f92a900e-9cfa-11e5-8181-80954d104a91.png)

**Comment by epelc** [comment]
@ThomasBurleson what do you mean? Even when you set it to `flex-gt-sm="50"` and add a `flex` to the second card you can see the first card is way over 50% of the width. See [demo](http://codepen.io/anon/pen/rxamOq?editors=101)

As you can see here if you inspect the first card the correct layout row styles are being overriden.
![image](https://cloud.githubusercontent.com/assets/5204642/11640882/0f5b0342-9d03-11e5-925a-7347958da1b9.png)

Also I shouldn't need to put a flex on the second card if the `max-width/height` are fixed then that should make it work without the flex. I get this point might have to budge but still it isn't working even when you do have a flex on the second card.

Also I just wanted to mention that I was never really sure if some of the layout bugs could even be fixed without a lot of js or at least complicated. It may be worth it to just ackownledge this and document it. As the following works correctly `layout-sm="x" layout-gt-sm="y"` while currently `layout="x" layout-gt-sm="y"` doesn't.

**Comment by ThomasBurleson** [comment]
@epelc - Total KUDOS to finding a clear CSS specificity issue with Layouts. As you mentioned, this works:

```html
<div layout="row" layout-sm="column" layout-xs="column" >
  <md-card flex flex-gt-sm="30">...</md-card>
  <md-card flex >...</md-card>
</div>
```

**Comment by ThomasBurleson** [comment]
@epelc - btw, this works great in the next generation of the Layout engine:

![screen shot 2015-12-07 at 4 27 03 pm](https://cloud.githubusercontent.com/assets/210413/11641764/a84c26d4-9cff-11e5-95fe-275af26ff3cc.png)

**Comment by epelc** [comment]
Thanks!

I forgot about the xs breakpoint.

**Comment by epelc** [comment]
@ThomasBurleson What's the next generation layout engine?

**Comment by ThomasBurleson** [comment]
@epelc - Here is a demo on the Layout Collection that demonstrates the normal (failing in sm, xs sizes) and the fixed version:  [Card Layouts Comparison](http://codepen.io/team/AngularMaterial/pen/obgapg)

**Comment by morganRotaStabelli** [comment]
We have loose the all afternoon beacause the responsive layout was not working as expected, then we look inside angular material css and we found that css media query are associated with wrong classes!!!!!!

Example:
In the css we found the following lines:
@media (min-width: 960px) and (max-width: 1199px) {
   .hide-lg:not(.show-lg):not(.show) {
    display: none; } [...]

So from this css lines we understood that the -lg classes is related to breakpoint from 960px to 1199px, but in the official docs there is written this association:
layout-lg	1280px <= width < 1920px

the real behavior we sow  is this:
layout-lg 	960px <= width < 1280px

and so all the break-points seems to be shifted down
so the last break-point is 
layout-sm	width < 600px and not layout-xs	width < 600px

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
