### ISSUE TITLE
Support md-slider with 2 values (range)

### ISSUE THREAD

**Issue by blootch** [angular/material#5773]
I know this issue is a duplicate one but the original discussion has been close, that's why i open this.
I read that this improvement is in progress & assigned to @CarmenPopoviciu but i really need to know if there is a hope to have this improvement soon ? @ThomasBurleson, @kseamon,  Could you please consider this in RC?
Have a nice day.

**Comment by EladBezalel** [comment]
dup #487

**Comment by blootch** [comment]
I know very well that this is a duplicate, thank you. 
Try to ask the right people is precisely what I try to do through this post.

@EladBezalel Anyway, thank you for your help. Mazel Tov ! ;)

**Comment by EladBezalel** [comment]
@blootch np, happy to help anytime. 

> Mazal tov on what? :sweat_smile:

**Comment by blootch** [comment]
Mazel tov for this superb angular material that will soon be born :dancer:
