### ISSUE TITLE
fab-toolbar: polish transitions and add functionality from spec

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#5775]
Right now fab toolbar is not aligned properly and not morphing into a toolbar as seen [here](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-ajMzVHp3VzJ4UkU/components-buttons-fab-transition_toolbar_02.webm)

> From [Material Spec](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions)

* should be able to morph [into a single sheet](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-TjBicTdvQjg4M1E/components-buttons-fab-transition_card_02.webm)
![single sheet](http://goo.gl/5GVhBb)

* should be able to morph [into a part of the app sheet](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8v7jImPsDi-c0UwMFAyQU5Jb1U/components-buttons-fab-transition_morph_02.webm)
![part of sheet](http://goo.gl/SyhJMN)

**Comment by topherfangio** [comment]
I have marked this as a 2.0 consideration because I believe we need to refactor how the speed dial/toolbar work to be more generic. I have some ideas on this, but since it is a large undertaking, we definitely shouldn't do it in a 1.x release (IMO).

**Comment by EladBezalel** [comment]
I do agree with you, on 2.0 we should be able to have versatile animated components, as the animations is a large part of the material design
