### ISSUE TITLE
Cannot build Windows7/Cygwin Node-SASS failing

### ISSUE THREAD

**Issue by jrgleason** [angular/material#5780]
I am trying to build Material locally. When I run `npm install` node-sass fails to build saying...

    Traceback (most recent call last):
      File "C:\Users\user\material\node_modules\gulp-sass\node_modules\node-sass\node_modules\pangyp\gyp\gyp_main.py", line 15, in <module>
      import gyp
      ImportError: No module named gyp
      gyp ERR! configure error

**Comment by EladBezalel** [comment]
What's your Node version?

**Comment by pmchugh3** [comment]
I believe that it doesn't work on Node 4.x.x. I had to downgrade to 0.12.7 to get it to build.

**Comment by EladBezalel** [comment]
There's a PR #5045

**Comment by jrgleason** [comment]
Awesome @EladBezalel thanks I am in fact using

    $ node -v
    v0.12.4
