### ISSUE TITLE
md-select-on-match is case sensitive

### ISSUE THREAD

**Issue by devilking15292** [angular/material#5782]
When typing on autocomplete ,
eg: "chennai" the doropdown shows "Chennai" ('C' is in caps) and it is not selecting the value

![screenshot from 2015-11-17 20 29 28](https://cloud.githubusercontent.com/assets/3378631/11214997/1a3e960a-8d6a-11e5-93b2-81d422bbd031.png)

**Comment by DevVersion** [comment]
What do you mean with selecting the value? Can you provide a codepen... It also doesn't select the value if you provide it with upper ```C```

**Comment by devilking15292** [comment]
it selects value when give with upper C,
but when lower c is typed, the user is is forced to do a mouse click on the option ,

here is a codepen link,
http://codepen.io/anon/pen/epXZLj

try typing Chennai with upper C and then try with Lower c... with upper C when user completes the word the option is selected automatically,but thats not the case with Lower c...

can you guys change it or you guys want me to do a workaround ?

**Comment by jrenee42** [comment]
I agree; it should be case-insensitive.
or, at least  have  an attribute:

md-select-match-case-insensitive="true"

it's a very small change;

code here:
material/src/components/autocomplete/js/autocompleteController.js
 /**
   * If there is only one matching item and the search text matches its display value exactly,
   * automatically select that item.  Note: This function is only called if the user uses the
   * `md-select-on-match` flag.
   */
  function selectItemOnMatch () {
    var searchText = $scope.searchText,
        matches    = ctrl.matches,
        item       = matches[ 0 ];
    if (matches.length === 1) getDisplayValue(item).then(function (displayValue) {
      if (searchText == displayValue) select(0);
    });
  }
