### ISSUE TITLE
ngMaterial home page: Demos > Chips - letters

### ISSUE THREAD

**Issue by a8775** [angular/material#5783]
When entering digits backspace and cursors (left or right) are working correctly.
When you enter some letters backspace and cursors stop responding.

Edge 20.10240.16384.0: 
![snip_20151117161917](https://cloud.githubusercontent.com/assets/14092227/11215530/fc92cbe4-8d46-11e5-9b7b-f63b591c6557.png)

Firefox 42.0:
![snip_20151117162252](https://cloud.githubusercontent.com/assets/14092227/11215613/813c4906-8d47-11e5-907d-5205416d9a80.png)

**Comment by topherfangio** [comment]
Closing as duplicate of #4971. Please comment if you feel it's different and we will reopen.
