### ISSUE TITLE
md-icon: Should have `box-sizing: content-box;` so borders/padding work

### ISSUE THREAD

**Issue by epelc** [angular/material#5787]
`md-icon` should have the following styles added so that you can apply padding and borders to it without the icon shrinking.
```
md-icon {
  box-sizing: content-box;
}
```
The right is how it works now. But with one line it could be much easier to use(See the left).
![image](https://cloud.githubusercontent.com/assets/5204642/11218560/b14de7ae-8d23-11e5-9c7b-ede8fb53cc5c.png)

**Comment by programmist** [comment]
@epelc: I'm not able to reproduce the issue.  Using this Codepen I was able to adjust border and padding on md-icon without the need to change box-sizing. http://codepen.io/programmist/pen/BjyEeK

Could you try again with the latest and see if the problem recurs?  If you are able to reproduce, please post a Codepen example.

**Comment by epelc** [comment]
@programmist I forgot to mention but this is only inside of `md-toolbar`. I was messing with the demo and it seems `md-toolbar` makes everything inside use `box-sizing:border-box;` but it's behaving differently now. The icon seems to grow when you switch to using `content-box` instead of just adding padding around it like it use too.

http://codepen.io/anon/pen/KVwLKv

It still shrinks your icons when you add padding in toolbar but I think adjusting the `width` property instead or simply using `.md-icon-button` works well. I think with this resolution this can be closed as it doesn't seem to affect anyone else. Feel free to reopen this if you think there is a better solution.
