### ISSUE TITLE
Dialog: Add docs for `.md-title` class

### ISSUE THREAD

**Issue by epelc** [angular/material#5788]
The alert/confirm dialog presets add a `md-title` class to the `h2` element. This slightly changes the look of it but the class is mentioned no where in the docs. Should we be using this to conform with preset dialogs?

https://material.angularjs.org/latest/api/service/$mdDialog

**Comment by stunaz** [comment]
it is mentioned here https://material.angularjs.org/latest/CSS/typography

**Comment by epelc** [comment]
@stunaz thanks!

I think some docs for if we should use it for every dialog or not would still be helpful. But at least I know where it's from now.

**Comment by EladBezalel** [comment]
@epelc for best results try to stick to the [Material Design Spec](https://www.google.com/design/spec/components/dialogs.html)
