### ISSUE TITLE
md-fab-speed-dial: opens without hovering over the trigger without md-hover-full added

### ISSUE THREAD

**Issue by webmatze** [angular/material#5789]
The items of the **FAB Speed Dial** can be opened without hovering over the trigger when not adding the ``md-hover-full`` class.

The error can be reproduced on the second example of the demo page for **1.0.0-RC4** (but for also in version 1.0.0-RC2):

https://material.angularjs.org/latest/demo/fabSpeedDial

I made a video to demonstrate the behavior:

http://quick.as/lrqsl7m1

I can reproduce this in Chrome, Firefox and Safari.

**Comment by topherfangio** [comment]
This appears to be caused by the fact that the scale is set to `0.1` instead of `0.0`. I *think* we can revert this back to `0.0` now that another bug has been fixed, but I need to double-check.

**Comment by webmatze** [comment]
Yes, setting **scale** to ``0.0`` seems to fix it.
Could not find any other problems with that.

**Comment by topherfangio** [comment]
The original problem was that using a speed dial action to open a dialog was throwing an error because it couldn't find the proper fab to go back to (because the scale was 0).

I think that has been fixed, but need to check first :smile:
