### ISSUE TITLE
Back compatibility of $mdDialog.confirm().content()

### ISSUE THREAD

**Issue by vovafeldman** [angular/material#5790]
I noticed that all the confirm dialog boxes stopped working. After digging in the commits log, I found that you spliited `content` into `htmlContent` and `textContent`. It's fantastic, but please return `content` for back compatibility as an alias.

I'm using bower+gulp and I don't want to test all my apps functionality on every update. Thanks!

**Comment by vovafeldman** [comment]
You call it deprecated others call it back compatibility. If you disagree, what would be the best way to get notified on deprecated elements?

**Comment by dmackerman** [comment]
A deprecation warning should be provided, similar to `<md-dialog-actions>`. Ripping out features without warnings is bad news. Not everyone reads changelogs, and even then it's not sufficient.

**Comment by EladBezalel** [comment]
@jelbourn thoughts?

**Comment by DevVersion** [comment]
A deprecated method will be a bit more complicated because of the dynamic method generation.

**Comment by jelbourn** [comment]
@EladBezalel  I figured that this change was simple enough (a method rename) that keeping the old method around wasn't critical. I'm okay with adding it back, leaving it out of the documentation, and having it behave like `textContent`. The breaking-ness of the change was intentional, as it forces people to check their code for potential XSS vectors.

**Comment by epelc** [comment]
@jelbourn any reason why the same `.textContent()` and `.htmlContent()` route wasn't taken for toasts?

If they were both the same or at least if toasts had a `.textContent()` a simple(r) find replace could clean it up pretty quickly. At the very least it'd be more consistent.

**Comment by jelbourn** [comment]
@epelc This change was motivated by guarding against XSS, and toast is already text-only.
