### ISSUE TITLE
$mdDialog Docs have dangling nonesense tags

### ISSUE THREAD

**Issue by bsandrow** [angular/material#5797]
In one of the code example for the [$mdDialog](https://material.angularjs.org/HEAD/api/service/$mdDialog) service in the documentation, there is a dangling `</xxx></controller>` that doesn't make any sense.

![screenshot](https://cloud.githubusercontent.com/assets/72231/11227231/cd466c54-8d52-11e5-9f5c-eaba85185adc.png)

([mirror](http://i.imgur.com/q8xWJBJ.png))

It looks like some tool somewhere is inserting them in an attempt to close tags in the examples. This part:

```javascript
    // Dialog #3 - Demonstrate use of ControllerAs and passing $scope to dialog
    //             Here we used ng-controller="GreetingController as vm" and
    //             $scope.vm === <controller instance="">
```

and this part:

```javascript
          // Since GreetingController is instantiated with ControllerAs syntax
          // AND we are passing the parent '$scope' to the dialog, we MUST
          // use 'vm.<xxx>' in the template markup
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (535/500 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:28871)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avscD-000L67-8D
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:49 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=T8PZVLDkuPkot/a3MZsmrzDdlaI=; b=TdSy3epOMe3kJvZa
	nXLMhlg34V8vUIFe55Kl1ZIscv2zt/eIQwQ8h0NKy6Y3abxvwTkje/7Eyu0yYrj0
	D0pTMTggq0fZrIvQ6+vi4w4JBFPWTlFrE2VBvWuLgkB1jvcwfKYYgWZynSwkUaHE
	yB8kNGFVxngFVTRkGG2gzqHUKB8=
Received: by filter0502p1mdw1.sendgrid.net with SMTP id filter0502p1mdw1.23036.5722735362
        2016-04-28 20:32:19.781835147 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id 9EDKfOidQKuELELZGuUA-w
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:19.850 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:19 -0700
