### ISSUE TITLE
md-subheader behind md-toolbar

### ISSUE THREAD

**Issue by eseceve** [angular/material#580]
If I have some like this (code below) the `<md-subheader>` is stuck behind `<md-toolbar>`
```html
<body>
  <md-toolbar></md-toolbar>
  <md-content>
    <md-subheader></md-subheader>
  </md-content>
</body>
```

Here is a plnkr http://plnkr.co/edit/YxhOaZhVQsJkvGD132yh and here is a plnkr without `<md-toolbar>` http://plnkr.co/edit/31kywtXeluaLZioyEezF

**Comment by mzbyszynski** [comment]
This may be an edge case, but the sticky subheader still doesn't seem to work on Chrome if it is inside a sidebar. I'm guessing this is because the offset isn't available when the directive is processed because the element isn't visible yet.

Here's an example: http://plnkr.co/edit/cIYP7m?p=preview
