### ISSUE TITLE
layout="column" children have no height on Android:Chrome

### ISSUE THREAD

**Issue by stheobald** [angular/material#5805]
Using layout="column" with angular-material on android:chrome breaks the layout - containing elements have no height, children overflow.

[Demonstration - run this one in Android:Chrome](https://rawgit.com/Grokling/328c621eda357a71b494/raw/445f8786b3db2b2f93c2bb48f329a3d11aa40937/index.html)
[Plunker Edit](http://plnkr.co/edit/FICWW2WNhuki0uqhSizW?p=preview)
[raw html] (https://gist.githubusercontent.com/Grokling/328c621eda357a71b494/raw/445f8786b3db2b2f93c2bb48f329a3d11aa40937/index.html)

To illustrate the difference in handling between layout-row and layout-column either:
Remove the _angular-material.css_ (demonstrates that it's an angular-material issue)
OR alter `div class="chapter ` **layout-column** ` flex` to `div class="chapter ` **layout-row** ` flex`

Either method will cause the .chapter element to render correctly, and encompass it's children.

This relates to the Chrome implementation of flex-direction:column somehow.

Browser trials are listed in a supplementary below.

## Firefox (Working)
![As anticipated on Firefox](https://cloud.githubusercontent.com/assets/10693305/11268400/67b7a866-8f15-11e5-8a43-b77fbc11c173.png)

## Chrome (Broken)
![Broken on chrome 47](https://cloud.githubusercontent.com/assets/10693305/11268410/7a05affe-8f15-11e5-9084-be46d1963a2b.png)

## Android Chrome (Broken)
![Broken on android chrome 46](https://cloud.githubusercontent.com/assets/10693305/11268524/205522b8-8f16-11e5-8870-98ebb9002b87.png)

This issue breaks my layout and renders my app completely unusable on affected browsers.

**Comment by stheobald** [comment]
Short link to use in emulators etc https://goo.gl/38ilpV

Firefox (Linux) 40.0.3 works as expected.
Android AOSP works (SGS4)
Chromium (win64) Version 48.0.2563.0 (64-bit) works

Chrome (Linux) Version 46.0.2490.86 (64-bit) is broken
Chrome (Android) 46.0.2490.76  is broken (SGS4)
Chrome (Android) 47.0.2526.61 is broken.
Chrome (win64) 47.0.2526.58 beta-m (64-bit) is broken

**Comment by Sriram143** [comment]
try to replace your code


<body>
  <h3>This page reproduces an issue on Android:Chrome whereby elements with layout-column (flex-direction:column) fail to have a height</h3>
  <p> To see the difference, open this page on an android device, use chrome://inspect to connect and change the </p>
  <p> "div class="chapter layout-column flex">" to </p>
  <p> "div class="chapter layout-row flex">"</p>
  <p> Alternately, remove the angular-material.css</p>
  <p> You'll notice that the '.chapter' background below now properly encompasses the two inputs</p>
  <chapters class="flex">
    <div class="chapter layout-column">
      <div class="section layout-column">
        <div class="question layout-row">
          <div class="layout-gt-sm-row flex-100">
            <md-input-container class="md-input-has-value md-block">
              <label for="input_1">Input 1</label>
              <input type="text" class="md-input md-block" id="input_1">
            </md-input-container>
            <button class="wnl md-button md-ink-ripple ng-hide" type="button" aria-hidden="true" aria-disabled="true" disabled="disabled" style="">
              <span>WNL</span>
            </button>
          </div>
        </div>
        <div class="question layout-row">
          <div class="layout-gt-sm-row flex-100">
            <md-input-container class="md-input-has-value md-block">
              <label for="input_2">Input 2</label>
              <input type="text" class="md-input" id="input_2">
            </md-input-container>
            <button class="wnl md-button md-ink-ripple ng-hide" type="button" aria-hidden="true" aria-disabled="true" disabled="disabled" style="">
              <span>WNL</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </chapters>
</body>

with this and see

**Comment by Sayene** [comment]
+1, on android 5.01 and 5.02 native browsers

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
