### ISSUE TITLE
Card Overlay

### ISSUE THREAD

**Issue by pmoelgaard** [angular/material#5806]
I have been trying to put together a Card Overlay, but I can't seem to get the CSS right.
Has anyone done this before and/or is it planned to have such a feature in the future ?

A possible use for this is e.g. to show the overlay on activation of the card (e.g. Mouse-Over, Tap or Long-Press). with e.g. Tools or Options for the Card

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (438/400 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:40537 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZp-001ZAL-FX
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:24 +0200
Date: Thu, 28 Apr 2016 13:29:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875359;
	bh=9q6UGpFPHgnUNPv8OjplK9A/01tAbK9CidEUCXZ9aa8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=DX7SGShnDeIxjZvnNGCTLgUa8YjeigpO9Kg05UqTepojzpyFulq2a5LtOhPv6++a9
	 Ed2eL9KwU0/iNpV5rKeozj9oB63tcTl+Opb/FtZqlxds7sfitHk1jW0Xteyr3+JVlv
	 ZcgSSbl6ORPsl9IbaSXWKKOHeXYiCN6r5hOOLQbM=

**Comment by pmoelgaard** [comment]
@ThomasBurleson thanks for taking the time to look at my post, do you perhaps by any chance have a heads up for me how to achieve this ?
@yanndupuy ??
