### ISSUE TITLE
An easy way of making components more condensed 

### ISSUE THREAD

**Issue by sunabozu** [angular/material#5807]
Hi.

It's a wonderful framework, it perfectly suits for mobile apps, but on desktops the situation is slightly different. Usually desktop applications have much smaller elements and condensed layouts, because mouse pointer is much more precise than finger, and generally we can afford to have more information on our desktop screens.

So I'm wondering, is there a way to make the whole set of components smaller through CSS or maybe `$mdThemingProvider`? Maybe there is some magic class like `md-mini` which can be applied to any component? It would be really great.

**Comment by dterbeest** [comment]
+1
