### ISSUE TITLE
md-switch: inside ng-repeat initial binding does not work

### ISSUE THREAD

**Issue by JobaDiniz** [angular/material#5808]
Neither
```
<md-switch ng-repeat="type in vm.types" ng-model="type.selected">{{type.name}}</md-switch>
```
or
```
<div ng-repeat="type in vm.types">
  <md-switch ng-model="type.selected">{{type.name}}</md-switch>
</div>
```
works... the binding is not working when I set `selected` to **true** in the controller:

```
var types = getTypes();
angular.forEach(types, function(type){
  type.selected = true;
});

vm.types = types;
```

**Comment by lucasribsantos** [comment]
+1

**Comment by DevVersion** [comment]
In a ```ng-repeat``` there is always a child scope, try `$parent.type.selected`

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (406/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:52974 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZM-001Z21-Re
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:53 +0200
Date: Thu, 28 Apr 2016 13:29:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875351;
	bh=3FBtW3LYpISIpp/qYcITZDwFuDMly9JfGHWX748cNiw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=e6leY6wuVeNqdsqvBa6fda5ylm7/1HMXfbUMTWqrf7Jl6uKQcOA5Um1/QdXan7C2W
	 HK2FRItoBPQizrFwfoRykP/g+IiRu2eEJFbeDizi/BRpENWrwxWAqhOSbexg6yb3Hl
	 bnL4EvyXMHWkmGU9I2loNwS8b47Vg7lGfyJsshZs=
