### ISSUE TITLE
md-datepicker needs ^ and v buttons to make it clear how to navigate through the list

### ISSUE THREAD

**Issue by jornncc** [angular/material#5812]
First of all, let me say that we __love what you guys are doing with Angular Material!!!__ It's been a great tool to use in our app. 

__Background__
We just came through sales enablement of our application using Angular Material. From that work we learned that the one widget that (from what I heard) all our go to market engineers had trouble with was the Date Picker. I found this strange, and looked into this more closely. From working with our end users, I personally saw many click the down arrow on the date picker to expose the calendar and sit there - looking at the calendar panel searching for a way to navigate backwards in time. 

When I asked, select July 1st (calendar defaulted to todays date - Nov 18th) and they said out loud _'How? Where are the buttons to do that???'... _

After being a little puzzled by this user experience, I started researching the issue. I found posts on this here and there where people had the same first time experience. I noticed that a change was made to extend the calendar panel to show the next month first row to let the user know that there is 'more stuff there - you just need to scroll to get there...' This was a good improvement for sure, but I believe still not enough. 

__Why did I not experience the same???__
I have struggled with this question for a few days now and I believe I've come to one answer that makes sense to me: I'm a mac user, have been for years. I have been trained to not need buttons or scrollbars to tell me that I can scroll something to navigate... If it looks like I can scroll something, I try it. Windows users on the other hand, they click scrollbars to navigate, they click buttons to navigate. On a mac you use two fingers... scroll up, scroll down. 95% the users on our Go To Market Team are Windows users so this makes sense to me. 

__Finding Alternative xx-datepickers?__
We have been asked (to my horror) to look for a different date picker for our tool. We do have a need for showing a date picker in both a standard form + in a modal ($mdModal) w/o having to deal with the issue of a 2nd modal closing the current modal dialog. Many implementations of a date picker shows the picker in a modal dialog - which will force the current dialog to be closed. I do not have the time in our schedule to implement a tie in back to the original modal from the date picker modal closing... at least not at this time in our schedule. 

__Forcing a Scrollbar?__
We looked briefly into the idea of 'can we force a scrollbar' to show 100% of the time to let the user know that they are in a scrollable area. But this is not an easy thing to do (and we also do not want to do this to be honest) since the md-datepicker is using the Virtual Repeat panel as it's calendar surface. 

__Example__
Would it be possible to support the ability to add up and down arrows like shown in this example to illustrate to the end user that they can click those to navigate up or down? Each click on the up button would scroll the calendar canvas back to the previous full month and place the month at the top of the calendar canvas. A directive toggle such as md-show-navigation-arrows=true|false would be awesome!!!

![calendar_with_chevrons](https://cloud.githubusercontent.com/assets/15808559/11245969/716dfc58-8dca-11e5-84e1-80aee8efa473.png)

If this is a duplicate of another issue, I apologize. I did attempt at searching for similar issues, but were unable to find any. 

Our current version of angular material: 0.11.2-master-8cc6b84

Thanks!!!

**Comment by jornncc** [comment]
Closed & updated main issue.

**Comment by rvarbanov** [comment]
What is the main issue? I am also interested it.

**Comment by jornncc** [comment]
The main issue is that people do not understand that you need to use a mouse scroll wheel to navigate to other months/years... I've seen people say "how do I select an earlier month..." and truly mean it... initially I thought they were joking... but they were not... so this is a real issue.
