### ISSUE TITLE
Use classes instead of style tags

### ISSUE THREAD

**Issue by rflnogueira** [angular/material#5813]
I'm working on an angular material project that needs it's own look and feel, but still want to use the extensive Interface Design Pattern list available in Material, and the big list of angular directives.

After trying to go with clean CSS for the style overwriting, I've noticed, to my despair, that angular-material sets style attributes on HTML elements.

It's a huge pain in the b*** when styling everything purely with CSS, any reasons you guys are not setting classes instead?

**Comment by ThomasBurleson** [comment]
@rflnogueira - where specifically are you seeing this ?
