### ISSUE TITLE
Possible bug in md-select

### ISSUE THREAD

**Issue by baguio2** [angular/material#5814]
I`m work in angular material and I have found a mistake in the last version 1.0.0-rc4, that there wasn't in the version 0.9.8. 
When I try make a md-select and i use a default image in the version 0.9.8 the correct result is it below:
![md-select-ok](https://cloud.githubusercontent.com/assets/10303926/11250913/1c9504aa-8e2f-11e5-8609-da34f85cc87f.jpg)

For another hand,  the current version 1.0.0-rc4 shows the next mistake or bug:
![md-select-bug](https://cloud.githubusercontent.com/assets/10303926/11251043/b12815da-8e2f-11e5-8a1d-ed6c1074b034.jpg)

Do you know anything about it? Could you help me to resolve it?

You Could check the example in http://plnkr.co/edit/m3Ll0A?p=preview.

**Comment by SirLouen** [comment]
I've checked the code and this is definitely a bug.

**Comment by Sriram143** [comment]
i checked the code its working as expected may be the latest build resolved the problem.
