### ISSUE TITLE
Update gulp to latest version

### ISSUE THREAD

**Issue by epelc** [angular/material#5816]
@ThomasBurleson It's outdated causing warnings on the latest master.

![image](https://cloud.githubusercontent.com/assets/5204642/11251689/72dbb8ce-8e00-11e5-913f-32f2474b9257.png)

**Comment by ThomasBurleson** [comment]
Does `npm update` not resolve this issue?

**Comment by epelc** [comment]
Sorry I forgot to confirm this. But I just did and it's up2date now.

https://github.com/angular/material/blob/master/package.json#L31
