### ISSUE TITLE
md-option gets cutoff with ellipses when OS X shows scrollbars

### ISSUE THREAD

**Issue by ianspiro** [angular/material#5818]
Using Chrome and Safari on OS X 10.10.5:

Go to System Preferences > General > Show Scroll Bars. Set to Always.  Or keep the default setting and use a desktop Mac with no trackpad.

In this demo: https://material.angularjs.org/latest/demo/select the Ground Beef option and several others are cut off with ellipsis.

![image](https://cloud.githubusercontent.com/assets/9756028/11254559/3fb1b26e-8df6-11e5-825e-35ed108f9ba1.png)

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (499/400 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:48958 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsbh-001a4h-Jn
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:32:18 +0200
Date: Thu, 28 Apr 2016 13:25:18 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875118;
	bh=4oVDJNaeCj8EL3Oa3v8373jIkI8Yr+mb57F31k1v4oA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=AbUXPQHKvguMSfMbWTiT9PvjNcNe2Pm60/UmMwcxDXE1j/dKvnncbgNSrrJblgYco
	 dW1pgfh44a9tgI4sj2DrHi8OnBZeIXbh0NuJV7J+3m0DcKtpML3CiYfgsrIhdDKcUJ
	 u8GweN9kvF1M+Mo6D5Yn2CUQU53400HswcsRXzp8=
