### ISSUE TITLE
Disabled and hint text should have an opacity of 38% for light backgrounds

### ISSUE THREAD

**Issue by joeyperson** [angular/material#5820]
At some point it was 0.26 previously, and it looks to have been increased, presumably for accessibility reasons.

http://www.google.com/design/spec/style/color.html#color-ui-color-application

**Comment by Splaktar** [comment]
Currently it appears that hint and disabled hint text are the same opacity (~26%). The spec is unclear on whether this is correct or not. Should there be a way to differentiate hint text from disabled hint text or is the dotted line below it the only way other than trying to tap on it to notice the difference between enabled and disabled?
