### ISSUE TITLE
Is there context menu directive that appears on mouse right button click?

### ISSUE THREAD

**Issue by mih-kopylov** [angular/material#5822]
It should use md-menu directive, but triggered by mouse right button click.

**Comment by gpopovic** [comment]
+1

**Comment by akomm** [comment]
There are currently two issues with md-menu regarding the possibilities to make something like a context menu:

1. It is restricted to `E` only. Enabling attribute should work just fine, correct me if I'm wrong.
2. It has a hard-coded behavior to lookup for second child, expecting it to be md-menu-content. This should be configurable (e. G. element or selector or both options).

With 1. or 2. it would be possible to easy make an context menu using md-menu directive.

**Comment by VictorRicha** [comment]
+1

**Comment by ThomasBurleson** [comment]
You are welcome to submit a PR for a contextMenu component.
