### ISSUE TITLE
Menu Bar and ng-mouseenter

### ISSUE THREAD

**Issue by prasannapattam** [angular/material#5824]
When the menu bar is opened using ng-mouseenter instead of ng-click, the previous menu is not closing. I took your example code and changed ng-click="$mdOpenMenu()" to ng-mouseenter="$mdOpenMenu()". Here is the image of the menu bar
![menu-bar-ng-mouseenter](https://cloud.githubusercontent.com/assets/4832935/11269665/56c63932-8ede-11e5-8503-dd3a27c468f4.png)

**Comment by ThomasBurleson** [comment]
will not fix.

**Comment by prasannapattam** [comment]
Without this fix, the mouseenter feature will not be used effectively. I recommend disabling the ng-mouseenter functionality all together.
