### ISSUE TITLE
md-tabs: pagination wrapper rendering issue type:bug

### ISSUE THREAD

**Issue by mobelio** [angular/material#5825]
Hi, please take a look

Block with tabs by default has CSS property 'display: none'. After few manipulations on the page - block gets 'active' class that override CSS property 'display:none' to 'display: block'.

Once block with tabs are displayed, part of paginator is not visible at all. Upon an attempt to hover paginator - everything gets normal

###### Bug:

![Bug](http://i.imgur.com/Z9Yg1jJ.png)

###### Dev tools:

![Dev tools](http://i.imgur.com/fSAAl1E.png)

###### After hover on paginator:

![After hover on paginator](http://i.imgur.com/MN3vKjD.png)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen demo. I will reopen if needed.
