### ISSUE TITLE
md-autocomplete in md-dialog have huge height also with only few values

### ISSUE THREAD

**Issue by mrigo** [angular/material#5826]
Hi,
I'm using md-autocomplete inside md-dialog and the md-virtual-repeat-container that shows the possible choises is too high when I have only one element.
It's the right behaviour?

Thanks
![schermata 2015-11-19 alle 12 50 32](https://cloud.githubusercontent.com/assets/390381/11270619/c5b7b85c-8ec0-11e5-87e8-3af6cefebc92.png)

**Comment by sch4lly** [comment]
+1, having the same "problem".

**Comment by jb29** [comment]
+1, I experienced the same issue on a customer's pc who's using IE11.
But unfortunately I couldn't reproduce the bug on my developer machine so far.

**Comment by elyas-bhy** [comment]
I reproduced this issue on [this codepen](http://codepen.io/anon/pen/OMLgxe?editors=101).
This is basically a fork of the current [demo of md-autcomplete](https://material.angularjs.org/1.0.0-rc5/demo/autocomplete), I just trimmed down the number of states to the first three.

You will also notice that clicking on _Alabama_, clearing the search text and clicking on the search bar again resizes the container height.

**Comment by gbaj** [comment]
Min repo-

click the autocomplete box and type 'q'

http://codepen.io/anon/pen/KVKVjR

**Comment by Rid** [comment]
I've also been having this issue, reversing the changes made to src/components/virtualRepeat/virtual-repeater.js in d6d7b084593467f0325db24b7698bb80f82a52a2 seems to make the issue go away.

**Comment by jelbourn** [comment]
I *think* I fixed this with 1771b29f94057e635e41b1489e0292ce6706a47c. Could someone confim?
