### ISSUE TITLE
md-slider :: cannot set tabindex

### ISSUE THREAD

**Issue by danjarvis** [angular/material#5829]
The md-slider component sets `tabindex` to 0 and it cannot be overridden.

I have a component created that combines the use of a numeric input and a range input. Similar to the one in the [demo](https://material.angularjs.org/latest/demo/slider) but the components are swapped (numeric input on the left, range on the right). When the user is tabbing through the form and they hit the numeric input and change the value there is no need to tab to the slider field.

https://github.com/angular/material/blob/master/src/components/slider/slider.js#L78

**Comment by DevVersion** [comment]
Here is a Pull Request, which allows overwriting for the `tabindex` attribute
