### ISSUE TITLE
npm install for the latest RC versions

### ISSUE THREAD

**Issue by shairez** [angular/material#5832]
I'm trying to `npm install --save angular-materail` and gets only 0.11.4 as the latest version.

Is it a normal behavior? Or is it a matter of republishing it to the npm repository?

how can we npm install the latest version?

Thanks!

**Comment by BernhardRode** [comment]
Having the same issue like shai. 

Any news on this?

**Comment by EladBezalel** [comment]
Kind of dup #5357

> While AngularJS does this, Angular Material has not [to-date] published RC(s) versions into NPM.

>Angular Material releases often include grid Layout and component CSS changes. We are concerned that our RC-<xxx> versions could adversely surprise developers after NPM updates.

> As such, we are not planning on publishing any 1.0-rc-<xxx> releases to NPM.
