### ISSUE TITLE
Formatting issue using md-radio-group inside  md-input-container with label

### ISSUE THREAD

**Issue by jaufgang** [angular/material#5834]
When wrapping a `md-radio-group` inside an `md-input-container` with a `label`, the label overlaps the first radio button.  This should format similarly to other input types in order provide consistent formatting over a form

Here's a codepen to illustrate the problem: http://codepen.io/anon/pen/QjoYKE

**Comment by jaufgang** [comment]
update:  explicitly adding  `class="md-input-has-value"` to the  `md-input-container`  wrapping the `md-radio-group` improves  the formatting significantly by showing the smaller label.   

For a form element such as `md-radio-group` it doesn't make sense to have the label change sizes depending on whether or not it has a value, but it would still be nice to be able to use labels and `md-input-container` for consistent formatting of a form.  Perhaps the `md-input-container` directive should automatically style it's labels with the smaller format if the form element it contains is checkboxes or radios.

**Comment by tonyeung** [comment]
+1 just came across this

**Comment by mattdanna** [comment]
+1 also ran into this issue.

**Comment by pdore-netfore** [comment]
+1

**Comment by siulung4073** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by robert-blankenship** [comment]
+1 Definitely was a tricky one, adding `class="md-input-has-value"` as recommended made a significant improvement

**Comment by matt-snider** [comment]
+1

**Comment by jakobadam** [comment]
You might also want to add the `md-input-invalid` class manually to get errors shown in the container...
```
<md-input-container class="md-input-has-value"
          ng-class="{ 'md-input-invalid' : form.x.$invalid && form.$submitted }">
...
```
Example: https://codepen.io/jakobadam/pen/xqZoBR
