### ISSUE TITLE
autocomplete select on match behavior should be more intuitive

### ISSUE THREAD

**Issue by jrenee42** [angular/material#5839]
right now, autocomplete select on match only autoselects the item if the user types the *entire* text; which is case sensitive.

how I expect/want the interaction to work:

1) case insensitive matching
2) when typing, as soon as the user narrows the field to one item; typing return should add that item  (why make the user type it all out?)

I'm happy to do the coding and submit a pull request for this new interaction.  

could add two attributes: 
case-insensitive-matching = true (false by default; which is the current behavior)
select-on-narrowing-field = true (also false by default; which is the current behavior)

(this feature request/issue also satisfies  issue #5782 )

**Comment by binzma** [comment]
looking forward for this!

**Comment by ThomasBurleson** [comment]
You are encouraged to submit a Pull Request with this enhancement.

**Comment by jrenee42** [comment]
noted!

**Comment by jrenee42** [comment]
pull req here: https://github.com/angular/material/pull/6962
