### ISSUE TITLE
md-scroll-shrink-target

### ISSUE THREAD

**Issue by ilovett** [angular/material#5841]
Rather than forcing the next sibling `md-content` to be the target, give the ability to define the target to watch scrolling on.
```
<md-toolbar md-scroll-shrink md-scroll-shrink-target="my-target">
  ...
</md-toolbar>

<md-content flex layout="column">
  <md-menu-bar>
    // fixed menu bar
  <md-menu-bar>
  <md-content flex data-target-id="my-target">
  </md-content>
</md-content>
```

**Comment by ThomasBurleson** [comment]
Interesting idea. You are encouraged to submit a Pull Request with this enhancement.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
