### ISSUE TITLE
md-grid-list calculates padding for the grid-list container incorrectly when you apply left right margins

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#5844]
[Codepen](http://codepen.io/Mopholo/pen/yYrydJ?editors=100)

Note that right after scrolling past block c there is a large gap.  

This looked to be caused by adding in left or right margins to the md-grid-list, bottom and top margins don't cause this though, something to do with the way the container padding is calculated. 

Remove the left/right margins and it reverts to proper behavior. 

A work around is to have a parent container to add margins, which then doesn't cause the issue.

**Comment by ThomasBurleson** [comment]
Will not fix. Workaround is appropriate.
