### ISSUE TITLE
Scrolling should be disabled when sidenav is open

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#5845]
As of https://www.google.com/design/spec/layout/structure.html#structure-side-nav, when opening a sidenav, scrolling should be disabled in 2 ways : 
 - sidenav should be '''position:fixed'''
 - md-backdrop shouldn't be scrollable 
A good example is their own menu, even though it allows "3rd click scroll" on backdrop whereas it shouldn't (?)
Else what, codepen demo of what's missing/not working (click right side nav)
http://codepen.io/anon/pen/rObOZE

**Comment by Wardormeur** [comment]
related to #5861 ?

**Comment by DevVersion** [comment]
@Wardormeur Yes, seems to be the same, btw: perfect demo :+1:

**Comment by EladBezalel** [comment]
@Wardormeur please write your comment there, your issue was first but #5861 has more info. thanks!
