### ISSUE TITLE
$mdDialog scope: $scope only has single use

### ISSUE THREAD

**Issue by mantissa7** [angular/material#5846]
Closed in #1531 but still an issue pertaining to re-usability.

I want to create a directive to allow me to open a generic dialog by just passing a template path for <code>templateUrl: </code>

I tried both with a directive and using <code>$scope.popup=function(path){}</code>, however when passing <code>scope:$scope</code>the dialog will only work once, and then the action no longer responds.

I am currently working around this issue by using <code>scope:$scope.$new();</code>

**Comment by danjarvis** [comment]
I didn't read through #1531 yet, but have you tried setting `preserveScope` to `true`?

**Comment by mantissa7** [comment]
Ahh, brilliant. Yes that works.
