### ISSUE TITLE
angular material phonegap build not working in android version below 4.4

### ISSUE THREAD

**Issue by nishahariii** [angular/material#5848]
Following are my html, css and js file:

       <head>
           <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
           <link rel="stylesheet" href="custom.css">
           <link rel="stylesheet" href="https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-rc4/angular-material.css">
        
        </head>
        <body>
    <div ng-controller="AppCtrl as appCtrl">
      <md-grid-list
        md-cols-sm="1" md-cols-md="2" md-cols-gt-md="6"
        md-row-height-gt-md="1:1" md-row-height="2:2"
        md-gutter="12px" md-gutter-gt-sm="8px" >

        <md-grid-tile class="gray"
        md-rowspan="3" md-colspan="2" md-colspan-sm="1">
      <md-grid-tile-footer>
        <h3>#1: (3r x 2c)</h3>
      </md-grid-tile-footer>
    </md-grid-tile>

    <md-grid-tile class="green">
      <md-grid-tile-footer>
        <h3>#2: (1r x 1c)</h3>
      </md-grid-tile-footer>
    </md-grid-tile>

    <md-grid-tile class="yellow">
      <md-grid-tile-footer>
        <h3>#3: (1r x 1c)</h3>
      </md-grid-tile-footer>
    </md-grid-tile>

    <md-grid-tile class="blue"
        md-rowspan="2">
      <md-grid-tile-footer>
        <h3>#4: (2r x 1c)</h3>
      </md-grid-tile-footer>
    </md-grid-tile>

    <md-grid-tile class="red"
        md-rowspan="2" md-colspan="2" md-colspan-sm="1">
      <md-grid-tile-footer>
        <h3>#5: (2r x 2c)</h3>
      </md-grid-tile-footer>
    </md-grid-tile>

    <md-grid-tile class="green"
        md-rowspan="2" >
      <md-grid-tile-footer>
        <h3>#6: (2r x 1c)</h3>
      </md-grid-tile-footer>
    </md-grid-tile>

     </md-grid-list>
    </div>
      </body>
         <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-animate.min.js"></script>
         <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-route.min.js"></script>
         <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-aria.min.js"></script>
         <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-messages.min.js"> </script>
          < script src="https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-rc4/angular-material.js"></script>
          < script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-114/assets-cache.js"></script>
          <script src="custom.js"></script>

And custom.css:
.gridListdemoBasicUsage md-grid-list {
  margin: 8px; }
.gridListdemoBasicUsage .gray {
  background: #f5f5f5; }
.gridListdemoBasicUsage .green {
  background: #b9f6ca; }
.gridListdemoBasicUsage .yellow {
  background: #ffff8d; }
.gridListdemoBasicUsage .blue {
  background: #84ffff; }
.gridListdemoBasicUsage .purple {
  background: #b388ff; }
.gridListdemoBasicUsage .red {
  background: #ff8a80; }
.gridListdemoBasicUsage md-grid-tile {
  transition: all 400ms ease-out 50ms; }

And custom.js:

angular.module('MyApp')
.controller('AppCtrl', function($scope) {});

And after creating the build through cordova and install the apk on android phone below 4.4, the grid title is not working. Only we can see the blank screen. But its working in android version 4.4 and above.

**Comment by ThomasBurleson** [comment]
We do not support versions preceding 4.4
