### ISSUE TITLE
md-tabs switched when <select> options is changed

### ISSUE THREAD

**Issue by ws-malysheva** [angular/material#5849]
Almost time when I tried to change <select> value into md-content, next tab became active.
It happens on chrome (os ubuntu 12.04)

*  [jsFiddle](http://jsfiddle.net/m1u8hzxk/7/) 
*  [Video](https://drive.google.com/file/d/0BxLwEiNVf4XqNFdVSHJqNFZUbmc/view)

**Comment by ThomasBurleson** [comment]
<img width="718" alt="screen shot 2016-01-14 at 3 17 18 pm" src="https://cloud.githubusercontent.com/assets/210413/12340795/f6c43ca8-bad1-11e5-8ed0-e684bee465a7.png">

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
