### ISSUE TITLE
md-sidenav was delayed

### ISSUE THREAD

**Issue by Shyam-Chen** [angular/material#5850]
When I scroll down and open the `md-sidenav`, the `md-sidenav` was delayed.

![default](https://cloud.githubusercontent.com/assets/13535256/11300477/64460e2e-8fca-11e5-9633-08a9f825cf15.png)

**Comment by DevVersion** [comment]
I copied the Codepen Link from your Screenshot into a plain link, so we can investigate better. Next time ... please share your link directly.
