### ISSUE TITLE
md-select inside md-dialog fires twice when the options-menu is activated on iOS

### ISSUE THREAD

**Issue by sandan10** [angular/material#5851]
I use latest ionic with latest (1.0.0-rc4) angular-material.

I have a couple of md-selects inside a md-dialog.
When the user clicks a md-select, the options-menu fires, but closes immediately, resulting in that no option is selected. This works fine on Android. 
If i click the select, and then try to hit one of the options very fast, it works (think doubleclick).

I checked some earlier versions, and found out it works in 0.9.0.

Can this be related to #5698 or #5696?

**Comment by Vishnuraj910** [comment]
I'm facing the same issue. Works fine in Android and Ripple but dropdown automatically getting closed in iOS. Is there any fix?

**Comment by smileapplications** [comment]
Same thing happens to me

**Comment by Vishnuraj910** [comment]
Any updated or fixes on this issue?

**Comment by sandan10** [comment]
Nothing new on this?

**Comment by jpike88** [comment]
#5698 is almost certainly linked to this issue too. They've moved the milestone back to RC8, which I think is just lazy. It's a serious usability bug and should be a priority.

**Comment by ThomasBurleson** [comment]
Ionic-ngMaterial hybrids are not supported. If you can reproduce this without Ionic **AND** provide a CodePen demo, we will reopen.
