### ISSUE TITLE
md-maxlength and ng-messages together are not showing text counter

### ISSUE THREAD

**Issue by andrew-cunliffe** [angular/material#5853]
The counter for characters seems to end up inside the ng-messages block when both maxlength and messages are used together,

The result is that there is no counter until an error occurs....

Before reaching the maxlength...

![screen shot 2015-11-20 at 15 48 31](https://cloud.githubusercontent.com/assets/773633/11304078/4215a502-8f9e-11e5-9616-6d362833fccc.png)

When finally reaching the maxlength the counter appears without knowing I'm approaching the limit...

![screen shot 2015-11-20 at 15 48 55](https://cloud.githubusercontent.com/assets/773633/11304085/4d88b06e-8f9e-11e5-947f-39114a17a20b.png)

HTML CODE

```
    <md-input-container>
        <label>Detailed Description</label>
        <textarea name="detailDescription"
                  required="required"
                  md-maxlength="1000"
                  ng-model="ctrl.detailDescription"></textarea>

        <div ng-messages="form.detailDescription.$error">
            <div ng-message="required">Detailed description is required</div>
        </div>
    </md-input-container>
```

**Comment by andrew-cunliffe** [comment]
To add, resulting HTML DOM looks like this...

```
<md-input-container class="md-input-has-messages md-input-has-value" style="height: auto;">
    <label for="input_5">Detailed Description</label>
    <textarea name="detailDescription" required="required" md-maxlength="1000" ng-maxlength="1000"  ng-model="ctrl.detailDescription" class="ng-pristine ng-valid md-input ng-valid-required ng-valid-maxlength ng-valid-md-maxlength ng-touched" id="input_5" rows="1" ng-trim="false" aria-multiline="true" aria-disabled="false" aria-required="false" aria-invalid="false" style="height: 237px;"></textarea>

    <div ng-messages="form.detailDescription.$error" aria-live="assertive" class="ng-inactive">
        <div class="md-char-counter">900/1000</div>
        <!-- ngMessage: required -->
    </div>
</md-input-container>
```

As you can see the `md-char-counter` is being put inside the ng-messages which has been given the ng-inactive class that has an opacity of 0 set.... which is correct for not showing error messages

**Comment by kimsrung** [comment]
+1. That's what I've been facing either.

**Comment by corneschouten** [comment]
+1

**Comment by Perchework** [comment]
+1

**Comment by SocVi100** [comment]
+1

**Comment by topherfangio** [comment]
Hi all, this should be fixed in master as we rebuilt the CSS to move the counter outside of the ngMessages container.

Can someone please verify that it is fixed or provide a demo if you are still experiencing issues?

**Comment by andrew-cunliffe** [comment]
Yes, it looks good in RC-7

**Comment by topherfangio** [comment]
@andrew-cunliffe Awesome! Thanks for the feedback. Going to close this issue.

Please post a comment if you're still having trouble and we will reopen.
