### ISSUE TITLE
md-autocomplete: placeholder in md-autocomplete with floating label not working

### ISSUE THREAD

**Issue by adrianchia** [angular/material#5854]
In Autocomplete demo with Floating Label, if I add a placeholder attribute the placeholder text is not being displayed. Example is shown in the following [plunker](http://plnkr.co/edit/2iz1qSqEfEkxvHZvkfDG?p=preview)

Angular version: 1.4.7
Angular Material version: 1.0.0-rc4
Browser / Operating System: Windows 7 Professional SP1, Chrome 46.0.2490.86, Firefox 42.0, IE11

**Comment by vbanuelos** [comment]
+1 These should be allowed to work together. 

Similar to how it works with md-input-container:
![image](https://cloud.githubusercontent.com/assets/2799090/12311844/f049be16-ba0e-11e5-975a-b08586003b1d.png)

![image](https://cloud.githubusercontent.com/assets/2799090/12311860/0b8b23e0-ba0f-11e5-8d23-11e2a723087f.png)

**Comment by ThomasBurleson** [comment]
May be a duplicate.

**Comment by vbanuelos** [comment]
@ThomasBurleson -- I found a simple fix and created a PR for it https://github.com/angular/material/pull/6817

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by U-like** [comment]
If someone needs this, I've made [this decorator](https://gist.github.com/U-like/dd1994c408d15b9b55ea4b0488a8206a) to allow placeholder work with floating label.

**Comment by rbournissent** [comment]
@gmanriqueUy The link is broken, can you share your solution again? Thanks!

**Comment by gmanriqueUy** [comment]
@rbournissent Oh, sorry about that. Link fixed.
