### ISSUE TITLE
Tabs underline color

### ISSUE THREAD

**Issue by jgo4th** [angular/material#5855]
Is there anyway to change the color of the selected tab underline for md-tabs? I have been searching for no avail as to what the active tab underline is actually coming from. There is no such indication of how this is done in the documentation

**Comment by jornncc** [comment]
I believe this is done via setting the theme, ie, alternate theme.

**Comment by DevVersion** [comment]
Yes, you can only modify the current tab color with the specified accent color:

Here a snippet from the tabs styling
```
color: '{{accent-color}}';
```
