### ISSUE TITLE
md-radio-button: Enter key when focus is on radio group does not set form as submitted

### ISSUE THREAD

**Issue by calebegg** [angular/material#5857]
Demo: http://codepen.io/anon/pen/LpvyxB

Repro steps: Focus the radio group (by tabbing from text input) and press enter

Expected: Alerts "true" (like when you press enter when the button or text input are selected)

Actual: Alerts "false"

**Comment by epelc** [comment]
Could this have something to do with `md-radio-button` not using a hidden `<input type="radio">`? Tabbing through `md-radio-buttons` also only ever puts you on the selected one(it skips all unselected radio buttons no matter what).

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (428/400 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:39712 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsZn-001Z8T-81
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:30:20 +0200
Date: Thu, 28 Apr 2016 13:28:01 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875281;
	bh=u4IR+VC1aIxZCjNJGP4+j9gCW+Tv3wl9+WDH5m8Z0t8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ddbnfqDnpB04Z30qogPnvtxQ7pYABc7kBxgeO+kB/AngVdzAB6j4C9h42txxdZC2G
	 ZdS7lTBf1MEY5uRwPzGHZNzOlptHmeRNRLW/jNiU2CxPoiJkz2jTYB3NhO9LKZujs1
	 xTTK5qFXrdWUjViqi9Er3oNd7AKj7LNZQMtuZdxg=
