### ISSUE TITLE
md-subheader bounces badly if scrolling is too fast and granular enough

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#5862]
Here is the [pen](http://codepen.io/Mopholo/pen/yYrydJ) this only happens on smooth scrolling screens or mobile devices, the easiest way to see this on a desktop is to use your mouse wheel to scroll rapidly, assuming it scrolls smoothly ( many don't ) 

When you use the actual scroll bars this doesn't happen. 

The easiest way to see this is in the pen is to use the chrome emulator ( use the iPad ) so that touch emulation is enabled, then drag up rapidly from bottom to top, or bottom to top. 

I assume that this has to do with the sticky function, since I can see this on anything that uses it ( tool bars that shrink on scroll, etc. )

Doesn't reproduce on Firefox, but does on IE and Chrome

![bouncing header](https://cloud.githubusercontent.com/assets/5982829/11317028/d12e4f8a-8fd2-11e5-8161-a08753a351c8.gif)

**Comment by Todd-Werelius** [comment]
Closing this since I can't repeat with the latest master build

**Comment by nitin7dc** [comment]
@Todd-Werelius : facing same issue on mobile devies. Any fix ?

**Comment by Todd-Werelius** [comment]
@nitin7dc re-open, it stopped after using the master last time, now it's back, not quite as badly as before

It has to do with too many animations butting up against each other, I experimented with using an animation frame to quite things down with some moderate success but never got fulling into it.

**Comment by olegweb** [comment]
#5483

**Comment by biswas123** [comment]
Excuse me, is this issue fixed already? I tried with latest angular material 1.5.5 still able to reproduce it.
