### ISSUE TITLE
md-fab-speed-dial and ng-class

### ISSUE THREAD

**Issue by LeoLozes** [angular/material#5864]
Fab doesn't work properly if ng-class is set like this:
`<md-fab-speed-dial md-open="false" md-direction="down" ng-class="md-fling">`

It works only when it's set between single quotes like this:
`<md-fab-speed-dial md-open="false" md-direction="down" ng-class="'md-fling'">`

In the angular doc it doesn't seem that putting a class between quotes is necessary:
https://docs.angularjs.org/api/ng/directive/ngClass

You can see an example here: 
http://plnkr.co/edit/KrIRskHYBBafDo8RSPpW

**Comment by 0101adm** [comment]
ng-class interpolates the value.

use class='md-fling'.

**Comment by DevVersion** [comment]
As @0101adm already said:

An expression isn't `md-fling`. Then at $compile it tries to find the variable `md-fling`.
You should put this in brackets, then its interpreted as a string ([See here](http://www.w3schools.com/js/js_datatypes.asp))

**Comment by LeoLozes** [comment]
Ok, my bad, I didn't read the documentation properly :) 
It works with class='md-fling'.
Thanks!
