### ISSUE TITLE
When multiple md-autcomplete on the same page, md-not-found doesn't work 

### ISSUE THREAD

**Issue by IvanLeonenko** [angular/material#5865]
I'm using rc-4 and when I have multiple md-autocomplete with one of them having md-not-found defined (as in demo) on one page, it never shows up. If I have only one md-autocomplete, I see this item in the list, it works fine.
Also it looks like on demo page you don't have such issue, but I'm using same JS code and layout.

**Comment by DevVersion** [comment]
Hmm, there must be something different. Can you share your *exact* code with us (codepen or something like that). Then we can investigate much better.

**Comment by IvanLeonenko** [comment]
Ok, it's a bit trickier,
If you have first autocomplete with not found template, and after it you have another one without not found template, then first autocomplete won't show not found item in the list, when it should.

Here take a look. (of cause they're bound to the same fields, but it doesn't matter, if you put not found template in both or change the order problem disappears): 
http://plnkr.co/edit/KRCN2xYo0kNyoDOGgugm?p=preview

**Comment by DevVersion** [comment]
Okay, I know how where the bug is, I will upload a fix in a few minutes... I have some connectivity problems

**Comment by KapilParam** [comment]
i found solution.
http://plnkr.co/edit/abhcwfN48lFvpMbocgLY?p=preview

**Comment by DevVersion** [comment]
@KapilParam That's a solution we don't need. We wan't to remove the `md-not-found` template on one `autocomplete`. But then the Template won't show on both.

My PR is fixing this already. (pending for being merged)

**Comment by KapilParam** [comment]
please check this again
http://plnkr.co/edit/abhcwfN48lFvpMbocgLY?p=preview

**Comment by DevVersion** [comment]
What did you change? looks like the other code snippets?.
At least, we should not store the `not-found` state as a global variable.
Perhaps we will compile at both times....

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you review the PR plz
