### ISSUE TITLE
md-stretch-tabs on resize

### ISSUE THREAD

**Issue by AliPoder** [angular/material#5871]
hello guys,

i am building a website currently on rc4 and i figured out that md-stretch-tabs="auto" doesn't work on resize.

i want my tabs to stretchon mobile view. well if i resize my window to mobile size from desktop size it does not stretches tabs but if i reload page with ctrl + r it does.

example case: a user with tablet switches landscape view to portrait view.

http://plnkr.co/edit/TevxU9XrDEUPclCcLYDs?p=preview

**Comment by ThomasBurleson** [comment]
Try:

```html
<md-tabs flex 
      md-dynamic-height 
      md-border-bottom 
      md-stretch-tabs="auto" 
      md-no-pagination>
```
