### ISSUE TITLE
Slider gets too long if ng-model value goes higher than max

### ISSUE THREAD

**Issue by defcronyke** [angular/material#5872]
A text input and a material-slider share the same ng-model variable. The slider is set with a max value. Now if the input receives a value larger than the slider's max, the slider grows across the page. It's very ugly!

I would argue that the slider should not get longer, instead its marker should just go to the end of the bar.

**Comment by DevVersion** [comment]
As always, I try to reproduce that issue. (http://codepen.io/DevVersion/pen/epobNq?editors=101). 
Can you please review the codepen, everything is working well for me :+1:

**Comment by defcronyke** [comment]
You are using a number input. The problem happens when using a text input:

http://codepen.io/anon/pen/vNMvNZ

**Comment by DevVersion** [comment]
Thanks for that quick response :+1:. Here is a Pull Request, which fixes that issue

**Comment by defcronyke** [comment]
No thank you! :)

**Comment by ThomasBurleson** [comment]
Fixed with SHA e0abeb4dc46a1753616a911fe54f14d8f1148a25
