### ISSUE TITLE
md-select: flickering with ng-messages

### ISSUE THREAD

**Issue by Raidri** [angular/material#5879]
When i use a md-select with ng-messages and i only want to show the message if the value is dirty or touched i got the problem that the touched event is fired on the click of the selectbox. But only for a short time. the message becomes visible and then invisible again.

i think that is not a correct behavior, right?

here a demo.
http://codepen.io/Raidri/pen/BoWXxq

**Comment by rschmukler** [comment]
Definitely not. Nice find. I'll take a look.
