### ISSUE TITLE
md-autocomplete

### ISSUE THREAD

**Issue by tnbalu** [angular/material#5880]
Hi,
How to set auto focus in md-auto-complete

Regards
N.Balusamy

**Comment by DevVersion** [comment]
Hello,

Normally you should not ask questions like that, here on GitHub
 -> better checkout the ngMaterial Group (https://groups.google.com/forum/#!forum/ngmaterial)

But this time I will give a quick answer.
- As you can see here (https://material.angularjs.org/HEAD/api/directive/mdAutocomplete)
- You need to specify the `md-autofocus` attribute (like that `md-autofocus="true"`)
