### ISSUE TITLE
mdInput: mdButtons placed in a layout-row container are sized and aligned incorrectly

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#5885]
Not sure if this needs its own issue since it is pretty much the same cause as https://github.com/angular/material/issues/5672

Buttons placed inside a layout-row container with md-input containers will be improperly sized.  Buttons without layout-row containers will be improperly aligned due to the bottom margin on md-inputs.  This seems to be a side effect of the inline-block change.

Setting the layout-align attribute on the layout-row container will return expected behaviour.  An example of this can be seen on the tabs demo, or in this codepen: http://codepen.io/mckenzielong/pen/GpaoqM

Version: 1.0.0_rc4 / master
Browser & OS:  Opera 33 / Chrome 46 - Windows 7
Reproduce: http://codepen.io/mckenzielong/pen/GpaoqM
Related: https://github.com/angular/material/issues/5672

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
