### ISSUE TITLE
Updated model not reflected in md-datepicker

### ISSUE THREAD

**Issue by demvin** [angular/material#5886]
Changing the date of the ng-model of a md-datepicker has no effect.  Shouldn't it be synced ?

http://codepen.io/anon/pen/KdLzEW?editors=101

**Comment by BernhardRode** [comment]
I'd say it is ok to not update the model, as long as no valid date is entered. But imho the ngModel.$setValidity('valid',false) should be updated correctly... currently ngMessages is not working :(

**Comment by jelbourn** [comment]
This should now be working as intended. The ngModel will only update when a valid date is entered.
