### ISSUE TITLE
md-dialog: support chained resolves

### ISSUE THREAD

**Issue by andrea-spotsoftware** [angular/material#5894]
It would be nice to have the possibility of chaining resolved promises, injecting the result of the first promise in the second, etc.

This is an example of code where i'm trying to obtain this behaviour:
http://codepen.io/anon/pen/yYWovd

previousItems is resolved but not injected in the second resolve function, that is never executed.

The request is for a resolve chaining behaviour like the ui-router: http://stackoverflow.com/a/27036758

**Comment by sebastianhenneberg** [comment]
+1
