### ISSUE TITLE
Need example layouts

### ISSUE THREAD

**Issue by TheSachin** [angular/material#5895]
Hi,
I am coming from bootstrap background(basically backend developer)
I am finding learning material quite difficult. New user could definitely learn if he is provided with some basic layouts just to get to started and then he can learn by tinkering with it.

**Comment by corentin-gautier** [comment]
Yeah thought about it too, what could be great would be to reproduce material guidelines templates because that's a starting point for many users ;)

so +1

**Comment by ThomasBurleson** [comment]
We are working to improve our documentation and to provide better samples.

**Comment by qorsmond** [comment]
I have been trying to get this layout correct for a while now and would love to see an **example** on how the team would do a layout for something like this:

![image](https://cloud.githubusercontent.com/assets/4716711/12657755/b427a8ca-c60d-11e5-8021-10f522ae24ac.png)

I got it to work in Chrome 48 but in Firefox and Edge it's broken.

The table in the right pane presented a challenge as it forced some scroll bars on the main div:
![image](https://cloud.githubusercontent.com/assets/4716711/12657929/91f5d38e-c60e-11e5-9383-020fb6e82d7d.png)
 I added a width:0; to the right pane and it was sorted not totally sure why.

Here a pen for the layout using angular material v1.0.3 : http://codepen.io/qorsmond/pen/GodBPY

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
