### ISSUE TITLE
md autocomplete required not working

### ISSUE THREAD

**Issue by ei09026** [angular/material#5896]
Tag required in md autocomplete elements is not working. I need to change it to ng-required="true" or to required="true"?

**Comment by hillerstorm** [comment]
Yep, not even working on [the demo page](https://material.angularjs.org/HEAD/demo/autocomplete) (the "Floating Label" demo has `required` on "Favorite State").

2ab1d2d <- this commit is the culprit...
```javascript
var value = '';
!!value;
// false
```

which means the shorthand version where you only write `required` resolves to `false`

**Comment by gpopovic** [comment]
+1
This is serious error

**Comment by kalokamgit** [comment]
+1

**Comment by brianfeister** [comment]
+1

**Comment by ThomasBurleson** [comment]
Duplicate ?

**Comment by DevVersion** [comment]
Should be fixed in #6803

**Comment by uxitten** [comment]
ok this url is worked https://material.angularjs.org/HEAD/demo/autocomplete
but this url not worked https://material.angularjs.org/1.0.5/demo/autocomplete
