### ISSUE TITLE
md-chips small screen 

### ISSUE THREAD

**Issue by shantanu1227** [angular/material#5897]
chips are not being selected on small screen

**Comment by DevVersion** [comment]
How are you defining ``small screen`. Please provide Device Information.

Everything is working fine, in selecting chips on small screen `768px`)

**Comment by shantanu1227** [comment]
I can select chip in desktop but the chip in mobile is not being selected although it can be deleted.

![angular material - demos - chips - google chrome_015](https://cloud.githubusercontent.com/assets/3425255/11426064/69af475e-947f-11e5-9c56-a0dc1592fc31.png)
![angular material - demos - chips - google chrome_016](https://cloud.githubusercontent.com/assets/3425255/11426063/69a292f2-947f-11e5-9c2f-35a1ab2b89c6.png)

**Comment by DevVersion** [comment]
Yes, I can reproduce that. I did a little bit of research. It look's like the focus event won't get triggered by these touch events. If we change the `tabIndex` of the chips content from `1` to zero, the chip will get focused after not clicking on the text.

**Comment by a2bsoftware** [comment]
+1
