### ISSUE TITLE
md-dialog: Theme not updating 

### ISSUE THREAD

**Issue by LuckY1** [angular/material#5899]
```javascript
// register themes (in config)
$mdThemingProvider.setDefaultTheme('blue-grey');
$mdThemingProvider.theme('blue-grey').primaryPalette('blue-grey');
$mdThemingProvider.theme('red').primaryPalette('red');
...

// bind model to theme
<md-select ng-model="vm.company.theme" required>
  <md-option ng-repeat="item in vm.palettes" >{{item}}</md-option>
</md-select>

// index.html
<body md-theme="{{vm.company.theme}}">

// always watch (in config)
$mdThemingProvider.alwaysWatchTheme(true);
```

```javascript
// in the controller
vm.openTicketDialog = function(ev) {
    $mdDialog.show({
        controller: TicketCtrl,
        controllerAs: 'vm',
        templateUrl: 'dashboard/tickets/createTicketView.html',
        parent: angular.element(document.body),
        targetEvent: ev,
        clickOutsideToClose:true
    })
}

// the html partial (createTicketView.html)
<md-dialog flex-sm="95" ng-cloak>
  <md-toolbar>
    <div class="md-toolbar-tools">
      <h2>foobar</h2>
      <span flex></span>
    </div>
  </md-toolbar>
...
</md-dialog>
```

I hope you understand the provided code snippets.
I bind a select input to the selected theme for the entire page and change it dynamicly on runtime.
That itself works great, but the dialog templates don't seem to get updated. That means, that the toolbar in the dialog and almost all elements in it aren't updated properly.
How can i fix that?

**Comment by zack24q** [comment]
+1, <md-dialog flex-sm="95" ng-cloak md-theme="{{vm.company.theme}}"> this change may fix it. make sure vm.company.theme is in your dialog's scope.

**Comment by LuckY1** [comment]
It seems to be fixed in RC5 :)

**Comment by LuckY1** [comment]
In RC5 the initial theme is set correctly, but still doens't update on theme change on the body.
How can i add it to my dialog's scope? vm.company.theme itself is bound to a Settings factory.

**Comment by zack24q** [comment]
add md-theme to your dialog, \<md-dialog flex-sm="95" ng-cloak md-theme="{{theme}}"\>. this change may fix it. you can put theme in $rootScope.

**Comment by LuckY1** [comment]
I was hoping that I could avoid using $rootScope. Do you think that it's going to stay that way and it's supposed to be implemented like that?

**Comment by zack24q** [comment]
or you can create a service, create put set method to maintain {{theme}}.

**Comment by DevVersion** [comment]
Just created a little demo, which simplifies investigating. http://codepen.io/DevVersion/pen/VegXPB?editors=1010

**Comment by Arns** [comment]
Certain elements of dialogs like md-button with md-primary class don't correctly inherit new theming since release 1.1.2. 

Likely something in the following changes that broke it: https://github.com/angular/material/pull/9762/files#diff-58cbee594b2fabf2c78b6d283750e535R806

**Comment by Splaktar** [comment]
@Arns have you tested this with 1.1.8? I believe that it may be resolved in that release.

**Comment by Arns** [comment]
@Splaktar I did test 1.1.8, yes. Same issue, unfortunately.

**Comment by Splaktar** [comment]
@Arns thank you for confirming that. Please open a new issue with a CodePen reproduction of the problem and we'll take a look.
