### ISSUE TITLE
md-tooltip should be position as fixed

### ISSUE THREAD

**Issue by allenhwkim** [angular/material#590]
As you see here
http://plnkr.co/edit/7QNtq7gVEHAgNZ7hVMKQ?p=preview

When document size is bigger than window size, tool tip is not well positioned.

If tooltip follows the mouse position, it should be positioned as fixed, not absolute

md-tooltop {position:fixed}

**Comment by ajoslin** [comment]
Don't use document scrolling. Create an md-content container and scroll through that, then md-tooltip will work.

**Comment by mkyukov** [comment]
"Don't use document scrolling. Create an md-content container and scroll through that, then md-tooltip will work."

@ajoslin  This doesn't work for me. The problem still persists and I believe this issue isn't resolved. :)

**Comment by Darksoulsong** [comment]
I had to change md-tooltip style from` position: absolute` to `position: fixed` to make it work.
