### ISSUE TITLE
md-tabs function is too specific and should be reworked to be more modular

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#5902]
In Android development, these is no such thing as an md-tabs. Maybe there is on iOS, but Google's solution makes more sense. Essentially, you have multiple vertical panes called a ViewPager. 

From there, you can add tabs on the top, titles to the top, or some sort of page indicator on the bottom. All of them are optional. Also, you can enable swiping support.

Essentially, right now, md-tabs is just a ViewPager + Tabs.

Here's a codepen of the difference:

http://codepen.io/anon/pen/yYWKNo

I just reworked the CSS to make it work like a pager.

Here's the Android developer guide showing how View Pagers can use Tabs or Titles (or none): 

http://developer.android.com/training/implementing-navigation/lateral.html#PagerTitleStrip

Here's an example of using indicators

https://github.com/JakeWharton/ViewPagerIndicator

If you're wondering where this is using with the Material Design spec, Google's Android apps have a start up wizard with indicators and view pagers as referenced here: http://stackoverflow.com/questions/26954217/how-to-implement-first-launch-tutorial-like-android-lollipop-apps-like-sheets

**Comment by marcysutton** [comment]
If there is talk of abstracting tabs into a more generic pattern and changing the display depending on the context, the Panels and Panelsets proposal should be thrown into the mix. It doesn't give much consideration to Android/native mobile designs necessarily, but since Angular Material is a responsive web framework, the proposed spec and accompanying polyfills should definitely be considered: http://discourse.wicg.io/t/panels-and-panelsets/1184

**Comment by marcysutton** [comment]
That said, what you are requesting is a major breaking change that would be hard to justify now that the framework has reached 1.0.

**Comment by clshortfuse** [comment]
@marcysutton Well, it doesn't have to break much, if md-tabs just generates a md-panel with md-panel-tabs. But, yeah, it would require a bit of work to make it backwards compatible.

**Comment by Sithdown** [comment]
I understand this change cannot be made around 1.0, but it makes sense and should be considered.
