### ISSUE TITLE
Add dependencies to package.json

### ISSUE THREAD

**Issue by felixfbecker** [angular/material#5906]
Currently, when you install angular-material with npm, its dependencies don't get installed. You have to install them manually. And if you unsinstall angular-material, they will not get uninstalled. ~~ngMaterial also has no control over which _versions_ are required.~~

As far as I know, the dependencies are angular, angular-aria and angular-animate. Without these, ngMaterial will not bootstrap. These should be added to `dependencies` of package.json ~~(and can then be removed from `devDependencies`)~~.

After that, npm should also be added alongside Bower and CDN to the "how to install" section.

**Comment by felixfbecker** [comment]
Ok I just noticed that these dependencies are there - in the npm repo - but as peerDependencies. This doesn't make any sense, these are hard dependencies. Without these, ngMaterial will not work. Therefor these should be automatically installed alongside, they are even being require()d in the index.js file. If you provide a plugin to something (like a gulp plugin) but don't require it (gulp) then it is a peer dependency. If you require() it, it's a hard dependency. peerDependencies also don't get installed automatically.

**Comment by felixfbecker** [comment]
no update on this?

**Comment by ThomasBurleson** [comment]
@felixfbecker - I am very unclear as to what you want changed in the `angular/material` source repository. Do you mean the settings in the deployed, builds of the library (which are in `angular/bower-material`)? 

**[/angular/bower-material](https://github.com/angular/bower-material/blob/master/package.json)** has this:

```json
"peerDependencies": {
    "angular": "^1.4.7",
    "angular-animate": "^1.4.7",
    "angular-aria": "^1.4.7"
  }
```

> So I assume you mean change to this:

```json
"dependencies": {
    "angular": "^1.5.0",
    "angular-animate": "^1.5.0",
    "angular-aria": "^1.5.0",
    "angular-messages": "^1.5.0"
  }
```

**Comment by ThomasBurleson** [comment]
Angular Material has a **[peer dependency](https://nodejs.org/en/blog/npm/peer-dependencies/)** upon Angular; please read link.

**Comment by felixfbecker** [comment]
@ThomasBurleson if bower-material is the source for NPM too, then yes. It has this:
```json
"peerDependencies": {
  "angular": "^1.5.0",
  "angular-animate": "^1.5.0",
  "angular-aria": "^1.5.0",
  "angular-messages": "^1.5.0"
}
```
when it should really be:
```json
"peerDependencies": {
  "angular": "^1.5.0"
},
"dependencies": {
  "angular-animate": "^1.5.0",
  "angular-aria": "^1.5.0",
  "angular-messages": "^1.5.0"
}
```

**Comment by Joshdav** [comment]
@ThomasBurleson the build on npm/bower has 

`"peerDependencies": {
  "angular": "^1.5.0",
  "angular-animate": "^1.5.0",
  "angular-aria": "^1.5.0",
  "angular-messages": "^1.5.0"
}`

when the bottom three should be dependencies as stated above. Peer dependencies shouldn't be breaking without them installed as per your link above. Currently angular-material breaks without those packages and as such should have all of them under dependencies.

**Comment by Splaktar** [comment]
@Joshdav I don't think that is quite the correct interpretation of that blog post. The `lenient` part was referring to using `^1.5.0` instead of something like `1.5.3` (note the `^`). It wasn't indicating that `peerDependencies` should be optional.

> "I only work when plugged in to version 1.2.x of my host package, so if you install me, be sure that it's alongside a compatible host." We call this relationship a peer dependency.

> You will receive a warning that the peerDependency is not installed instead.
