### ISSUE TITLE
md-autocomplete results don't update

### ISSUE THREAD

**Issue by STOpandthink** [angular/material#5910]
When I type text into autocomplete, the results show up, but when I continue typing they don't update, even though the loading bar does flicker. I checked my `performSearch` function, and it definitely returns very different results. The results do update if I erase all the text and start typing again.

```javascript
scope.getSearchResults = function(text) {
  var deferred = $q.defer();
  // performSearch returns an array of objects
  performSearch({term: text}, function(results) {
    deferred.resolve(results);
  });
  return deferred.promise;
};
scope.searchResultSelected = function(result, blah, bloo) {
  window.location.href = "/";
}
```

```html
<md-autocomplete md-selected-item="searchItem"
				md-search-text="searchText"
				md-items="result in getSearchResults(searchText)"
				md-item-text="searchText"
				md-selected-item-change="searchResultSelected(result)"
				md-no-cache="true"
				md-min-length="2"
				md-delay="300"
				md-autofocus="true"
				placeholder="Search"
				flex="80">
  <md-item-template>
    <a href="#">{{result.label}}</a>
  </md-item-template>
  <md-not-found>
    No matches found.
  </md-not-found>
</md-autocomplete>
```

**Comment by STOpandthink** [comment]
Okay, I figured out exactly what's wrong. It's having a custom directive inside the "md-item-template". For some reasons it doesn't recompile itself. Here is a codepen to demostrate the bug: http://codepen.io/anon/pen/jbjxpQ?editors=101
Note how the second number doesn't change as you type more text.
(Btw, I'm an ex-Googler, so happy to help in any way I can.) :)

**Comment by STOpandthink** [comment]
Oh ok ok, it's even simpler than that!! I took the first example from here: https://material.angularjs.org/latest/demo/autocomplete  
And changed {{item.display}} to do ng-bind instead. And it breaks!
http://codepen.io/anon/pen/ZQYJja?editors=101  
Just type a few letters at a time, and then backspace slowly, and you'll see items missing / not being rendered.

**Comment by RolandHeath** [comment]
Isn't it more likely that this is an issue with the virtual-repeat that autocomplete is using? This probably has to do with when the compilation step is happening, and what steps happen before/after it.

**Comment by kseamon** [comment]
This sounds like it is working as intended behavior for virtual repeat, which recycles dom nodes to save performance. To make your directive work, have it update in a watcher rather than once at startup.

**Comment by STOpandthink** [comment]
So if I understand correctly, the solution is to use {{ }} instead of ng-bind? (Looks like that works as a fix in the demo and for my project as well.)

**Comment by RolandHeath** [comment]
@STOpandthink 
That actually makes sense - the purpose of using `ng-bind` instead of `{{ }}` is to stop the raw template is being momentarily displayed before compilation. 
But with virtual-repeat, I'm pretty sure those elements don't exist in the DOM until compilation, so that shouldn't occur. 
If I'm wrong on that, ng-cloak is the alternative solution to that problem.

**Comment by STOpandthink** [comment]
Yeah, it wasn't clear to me exactly what was going on with virtual repeat,
but now that I've thought about it, I understand the limitations and the
reason why md-autocomplete uses it. Looks like changing ng-bind to {{ }}
does work as a fix.
Thanks guys!
