### ISSUE TITLE
Datepicker won't close on iOS if jQuery is included

### ISSUE THREAD

**Issue by chr22** [angular/material#5914]
The only way to close it is by selecting a date.

I only see this on iOS, but on both iOS 8 and iOS 9.

See this CodePen: http://codepen.io/chr22/pen/xwoxBN?editors=101

**Comment by jelbourn** [comment]
@chr22 Which version of iOS was this on? I assume this was in Safari? Trying on iOS 8 in Safari, I have the opposite problem: the datepicker immediately closes right after opening.

**Comment by chr22** [comment]
I tried on a real iPad with ios 9 and an iPhone simulator with ios 8

**Comment by chr22** [comment]
And yes it was in safari
