### ISSUE TITLE
Step validation for input

### ISSUE THREAD

**Issue by tatulea** [angular/material#5916]
Hi!

I have this code:

<code>input type="number" ng-model="client.procent_achizitii" ng-change="compare($index)" aria-label="Procent potential" min="0" max="1" step="0.01" required></code>

My form tells me when the imput is not a number or if it is not between 0 and 1, but it not tells me when "step" property is not valid. Firefox shows me a message, but my form is still valid even my number is 0.0222. How can I fix this?

**Comment by matyee** [comment]
Step does not have affect on the validation. It only controls the amount that is added or subtracted from value of the field when the up and down arrow keys, or the arrow icons on the screen are used.

**Comment by tatulea** [comment]
Thanks! I will do that.
