### ISSUE TITLE
mdInkRipple: fab button with md-icon has wrong ripple placement

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#5917]
The ripple is incorrectly placed when using a fab button that contains an md-icon.  A plain text fab button will have the correct ripple placement.  The ripple will incorrectly start from the top left of the button unless clicking near the bottom right of the fab.

**Browsers and OS:** Opera 33 / Chrome 46 - Windows 7 x64
**Reproduce:** [this codepen](http://codepen.io/mckenzielong/pen/BogoLj) click on the good or test button near the center to get a feel for how the ripple should be displayed.  Click on one of the icon fabs near the center and notice that the ripple will start from the top left.
**Suggested Fix:** haven't really had a chance to look... is offsetX/Y behaviour stable?

**Comment by DevVersion** [comment]
Yes, that's only happening, if you click directly on the icon.

![](https://i.gyazo.com/6ec6dc7b945270c4d2fe2ae2d217ffb0.gif)
