### ISSUE TITLE
rc5 : multi select values are  vertically aligned .

### ISSUE THREAD

**Issue by asjadsaboor-10p** [angular/material#5926]
when multiple values are selected in multi select they are aligned vertically instead of horizontal alignment.

code pen: http://codepen.io/anon/pen/BogQxg
![rc5 multi select issue](https://cloud.githubusercontent.com/assets/11973227/11419927/74bc12a4-944c-11e5-91a9-e642d45d494a.png)

**Comment by TheRealBryon** [comment]
+1

**Comment by andrew-cunliffe** [comment]
:+1: 

still happens in rc-6 too

**Comment by dohomi** [comment]
+1. issue happens in rc-5 and rc-6. The documentation doesn't display a ```multiple="true"```example any longer

**Comment by mprentic-harris** [comment]
@ThomasBurleson This really doesn't look good and an regression like this (from RC5) shouldn't go into 1.0.

**Comment by tamsler** [comment]
+1

**Comment by mprentic-harris** [comment]
This was fixed in https://github.com/angular/material/commit/2ab30758ec451383ef03d234ffc729517afb92e3. This should be closed.

**Comment by DevVersion** [comment]
Right! Thanks for keeping an eye on that @mprentic-harris :smile:

**Comment by praetor-ss** [comment]
I am surprised that this was changed. I want it to work as it originally did as I have long texts to select within the md-select.... Why was this considered a bug and why wasn't instead an option introduced to control the alignment of selected items?

**Comment by Splaktar** [comment]
@praetor-ss please open a new issue and link to this one.
