### ISSUE TITLE
md-swipe-down: md-swipe-down example causing errors in demo site

### ISSUE THREAD

**Issue by tenshiAMD** [angular/material#5928]
https://material.angularjs.org/latest/demo/swipe

When using md-swipe-down, this 3 errors appeared:

- Error: [$rootScope:inprog] http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24apply
- Error: [$rootScope:inprog] http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24apply
- Uncaught Error: [$rootScope:inprog] http://errors.angularjs.org/1.4.7/$rootScope/inprog?p0=%24apply

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
