### ISSUE TITLE
md-tooltip on Chrome mobile, tooltip keeps position on scroll

### ISSUE THREAD

**Issue by justingrayston** [angular/material#593]
Most likely present on other mobile browsers, but I haven't tested. See screen shot of the demo site, on Nexus 5 KitKat.

Touching the Fab button shows the tooltip. Touching the tooltip itself clears the tool tip. If you scroll your screen before clearing the tooltip the label keeps its position which is a little odd.

![nexus_5_kitkat](https://cloud.githubusercontent.com/assets/5277488/4981583/6eb0f5b4-690a-11e4-8ca3-3ed63d7b5b7e.png)

**Comment by bigterminal** [comment]
i have the latest build and this is still issue an in chrome, and not viewing on mobile. The directive should not be appended to the body but relative to its parent element and then manipulated with margin-top rather to ensure it's styles align with its parent element in varying scenarios.
