### ISSUE TITLE
mdSubheader:  jumpy on high-pixel screens

### ISSUE THREAD

**Issue by NoamKix** [angular/material#5931]
I forked the code for basic subheader usage from:
http://codepen.io/mckenzielong/pen/RWdvLX

if you click "change view" -> "full page" 
and put the window on a high resolution screen i.e. Mac Retina the subtitles start to jitter when scrolling 
this is also what i'm reproducing if i just copy the demo code from material.angularjs.org and run it locally. it has reproduced on all machines in the office.

reproduced in rc5. angular 1.4.8
and rc4, angular 1.4.7

strangely the demo on the material web site is not showing this behaviour

in the gif attached you can see the at first the window on a regular res screen, the subtitles working perfectly, then when the same window is on the high res screen, turns a little greener, thats on the mac screen, you can see the laggy behaviour.
![ezgif com-add-text](https://cloud.githubusercontent.com/assets/8720873/11419671/9ed4896a-9431-11e5-9141-7def50b648fe.gif)

**Comment by NoamKix** [comment]
I believe this is the same issue as #5483

**Comment by agepath** [comment]
:+1: also experiencing this on Macbook Pro Retina

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (509/500 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:56598 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsc0-000L0A-Bv
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:36 -0500
Date: Thu, 28 Apr 2016 13:32:09 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875529;
	bh=GSnO+nOuqv4u7M3YtH1VUy4V3jXARugq/jqOjmU3CIA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JfMpzcN3ucU5cQ+ElspgGGWraxvfpe1WazNQXloby30wieyBXKnp5LLsznYQFHNPL
	 /9ZF5A5A22vzGE5SvS5Xu6PA3NP7AvGlHsVvE+c6p3ZVoM4S/ew6G535RmS8GtxijE
	 RfcXSarIvHZEKRz8dNEU0f2MiCmML0s0iOnv8IwU=
