### ISSUE TITLE
Datepicker: invalid input keeps the model valid

### ISSUE THREAD

**Issue by matyee** [angular/material#5935]
Once the datepicker had a valid date set the state of the model remains valid even if an invalid input is given. http://codepen.io/anon/pen/NGZagZ

![image](https://cloud.githubusercontent.com/assets/1215146/11425183/f728f790-944a-11e5-94b6-489e6aba0ea0.png)

The example shows that after the first stage you can give any invalid date, the model remains valid. The datepicker gets the invalid class, so the bottom border gets red, but the form still can be submitted. This behaviour can be confusing for the users, since they don't see the date that will be sent to the server.

**Comment by jelbourn** [comment]
The is the intended behavior; the ngModel is only updated when the value is valid. Form submission is typically gated on data validity.
