### ISSUE TITLE
CSS: layout change in rc5

### ISSUE THREAD

**Issue by matyee** [angular/material#5936]
With rc5 the layout of sibling input elements has changed.

RC4:
![image](https://cloud.githubusercontent.com/assets/1215146/11425596/e51febc8-944d-11e5-9a99-0c9e27054da0.png)
http://codepen.io/anon/pen/wKLrXL

RC5:
![image](https://cloud.githubusercontent.com/assets/1215146/11425605/f5dd280e-944d-11e5-951f-261696a56113.png)
http://codepen.io/anon/pen/Yyoraj

**Comment by Todd-Werelius** [comment]
@maytee both your pens have rc5 referenced in js/css.

**Comment by RolandHeath** [comment]
This probably has to do with the breaking change to layout/layout-align, listed in the changelog [here](https://github.com/angular/material/blob/release/1.0.0-rc5/CHANGELOG.md). Not a guarantee, but worth looking at.

**Comment by matyee** [comment]
@Todd-Werelius, well spotted. I corrected.

**Comment by wiesys** [comment]
Just updated to RC7 and **"alignment issue" is back**! Alignment in RC6 was working though.

**Comment by RolandHeath** [comment]
@wiesys Are you sure it's the same issue? 
I'm not seeing this on the OP's codepens, after updating them to rc7. Might be worth creating your own pen to recreate the issue you're seeing.
