### ISSUE TITLE
datepicker: validation issues

### ISSUE THREAD

**Issue by matyee** [angular/material#5938]
The following example demonstrates two issues I have found with the datepicker. The example has two datepicker fields, date1 and date2. The min date fot date2 is date1.
http://codepen.io/anon/pen/ZbdXgK

1) After the first load, date2 is set 2 days after date1. The min date for date2 should be date1 inclusively, but only the next day is selectable from the dropdown. If I select the current date for date1 in the dropdown, then the current date gets selectable for date2 as well.

2) Setting date1 to a date that is after date2 does not invalidate date2 regardless it is set before the min date.

**Comment by julienmeyer** [comment]
Same problem

**Comment by BernhardRode** [comment]
+1

**Comment by jelbourn** [comment]
Possibly a timezone issue.

**Comment by ngraef** [comment]
The second issue noted by @matyee simply requires a `$watch` on `mdMinDate` in `DatePickerCtrl` to run the validation logic when it's changed.

Here's the obvious quick workaround that resets the second date when the first changes, which forces the datepicker to validate:

```javascript
$scope.$watch('startDate', function () {
    var end = $scope.endDate;
    $scope.endDate = null;
    $timeout(function () {
        $scope.endDate = end;
    });
});
```

Demo: http://codepen.io/anon/pen/xVPopG

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (522/500 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:60004 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avscA-000L5A-7H
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:46 -0500
Date: Thu, 28 Apr 2016 13:32:09 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875529;
	bh=cpkXXU/Arpgx65ShqA5xrsDAQApitZq8cX/tL4k0sUk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=wcRbNGlo/kZpdjbirs4fHk6k59vFhtmMiZ7dP7B908cVJFdKbUWB59BGB3IbJiLgx
	 YDRKhZlMUsKCUoyO/gnUNKy5422ocXlK/dWCUzeI+TXJYleuTooP1gB0vFNh6V0aqT
	 Ha5a8LvfqNrbCrsnfke1g5G1VmnwoAGyyaVTK5uM=
