### ISSUE TITLE
Document CSS API

### ISSUE THREAD

**Issue by ajoslin** [angular/material#594]
Add a 'CSS' section to the documentation for each component, and decide on good CSS classes where they don't exist yet.

**Comment by david-gang** [comment]
:+1: 
This is great because now it will be easier to interact with designers who want to work with clean css :-)

**Comment by nicbon** [comment]
This is a great idea!

We feel hesitant using some classes because we don't know if they are gonna disappear or change in future releases. This feeling is increased by the fact that some classes are documented (I'm thinking about .md-whiteframe-z*), while others can only be found on (sometimes unrelated) examples (e.g. .md-mini).

**Comment by ThomasBurleson** [comment]
@david-gang , @nicbon - Documenting CSS is definitely on our roadmap. A team is currently focused on implementation of components for the planned Q2 1.0 release. Perhaps you guys could help us and create a initial CSS markdown document (submit via PR)?

**Comment by david-gang** [comment]
@ThomasBurleson I will be happy to document every css class i make a customization on. What should be the name of the file and where should it be located ?

**Comment by ThomasBurleson** [comment]
@david-gang - As you prepare this document, I will connect with you as a formal contributor and we can dialog as needed so I can help with questions, suggestions, and feedback. What is your email?
I will contact you and we can discuss ideas on CSS documentation.

> The 1st question is whether to have a separate CSS section that discusses the CSS for all components  or the enhancement of each component's online docs with a CSS section. Currently, the component docs have **Usage** and **Attributes** sections; we could easily add a "CSS" section there; but that would require jsDocs instead of markdown docs.

**Comment by lee-40square** [comment]
@david-gang Thanks for doing this. As a front-end developer, I appreciate it. Having worked with many UI frameworks, I would suggest that Bootstrap has the best and easiest-to-follow documentation and might be a good reference point.

**Comment by DavidSouther** [comment]
Thank you for the reference, @ThomasBurleson.

From the linked issue:

"As a user, I expect the demos to be copy/paste and "just work"; instead, I need to dig into the docs.css to get the same visual styles."

As a developer who works with designers (and fears the days he must dabble in design himself), this is a critical story for "working" demos.

**Comment by lookfirst** [comment]
related: https://github.com/angular/material-start/issues/19

**Comment by mprentic-harris** [comment]
:+1: really happy to see this being worked on!
