### ISSUE TITLE
mdButton, mdTooltip, mdSidenav: incorrect button and tooltip status after dismiss sidenav

### ISSUE THREAD

**Issue by billkim84** [angular/material#5944]
Codepen: http://codepen.io/anon/pen/epwVKB

I have tooltip in the fab button and the button toggles sidenav. 
when I dismiss sidenav, fab button and tooltip status looks like invalid.

![image](https://cloud.githubusercontent.com/assets/2604192/11430065/e9023b82-944e-11e5-8479-cbec969e8935.png)
![image](https://cloud.githubusercontent.com/assets/2604192/11430307/7a4dbc6c-9452-11e5-83d9-43986c4b257d.png)

**Comment by DevVersion** [comment]
Hello,

1. The Tooltip got restored by the Sidenav.
 I already created a fix for that, which is currently pending for being merged. Here is the PR #5589

**Comment by billkim84** [comment]
Thanks
