### ISSUE TITLE
rtl problem when upgraded from rc4 to rc5

### ISSUE THREAD

**Issue by eqbalsajadi** [angular/material#5946]
Before upgrade, everything was OK:
![image](https://cloud.githubusercontent.com/assets/8365938/11430632/cc813116-949e-11e5-8814-33cd46210e52.png)

After that:
![image](https://cloud.githubusercontent.com/assets/8365938/11430724/4dfdfc00-94a0-11e5-8afb-204a51031d7d.png)

**Comment by EladBezalel** [comment]
can you please provide a codepen with your problem so we can investigate more?

**Comment by eqbalsajadi** [comment]
Hi, 
just add style="direction:rtl" in root div tag
http://codepen.io/eqbalsajadi/pen/GpbPLy

labels should be on the right

**Comment by ThomasBurleson** [comment]
Thx @eqbalsajadi - closing.

**Comment by eqbalsajadi** [comment]
this problem has not been solved in rc6!

**Comment by EladBezalel** [comment]
This hasn't been merged yet.

**Comment by eqbalsajadi** [comment]
Thank you

**Comment by eqbalsajadi** [comment]
@EladBezalel in which milestone this issue will be merged?

**Comment by eqbalsajadi** [comment]
@ThomasBurleson @EladBezalel  would you please explain when your solution for this issue will be merged?

**Comment by EladBezalel** [comment]
It was closed with https://github.com/angular/material/commit/db72b39add9f4b9cf00e04d98fd16a847997475c

**Comment by eqbalsajadi** [comment]
@EladBezalel ok. you r right and thanks, i checked it today and see it has been merged. but it has a small problem:
right position of labels should be zero when they are in floating position
![image](https://cloud.githubusercontent.com/assets/8365938/12864909/a7e2907a-ccb1-11e5-9f85-68e09276e35a.png)

**Comment by eqbalsajadi** [comment]
codePen: http://codepen.io/anon/pen/YwJrZJ

**Comment by eqbalsajadi** [comment]
@EladBezalel I found that is is ok in my project 

thanks alot :)

**Comment by EladBezalel** [comment]
Your'e welcome.
