### ISSUE TITLE
Custom dialog with disableParentScroll doesn't show up in the correct place

### ISSUE THREAD

**Issue by STOpandthink** [angular/material#5950]
Here is the codepen: http://codepen.io/anon/pen/pjXKwv
Scroll down and click "Custom Dialog" button. Note that the dialog shows up at the top of the page, scrolling the window up, when you'd expect it to just show up without scrolling the window.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (513/500 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:51421)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avsc5-000L1e-ST
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:42 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=aVAURlNEuBIbo1JTej0zohpVU54=; b=Rvl44tJns059nexn
	KGVnwkdjBra9vcwdNCeFJ4cVqalInQH6fa0G6+JWgmjCM9byw0KlakpCClGnuEmn
	wVuRrw3u6lN+3tIyiNo9px1x3oRIVedD+1jONbNY3UqN6V49l9xi//2zL2Q4ieEt
	8zTFiA7JaD+Vjtcz0o4O908JSBg=
Received: by filter0919p1mdw1.sendgrid.net with SMTP id filter0919p1mdw1.29036.5722734A4
        2016-04-28 20:32:10.059702997 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id x6d5UJBNTV-9v0wVHTSuhw
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:10.130 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:09 -0700

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (614/500 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:54014 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdJ-000LkD-9C
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:57 -0500
Date: Thu, 28 Apr 2016 13:32:29 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875549;
	bh=d2gWxNCpZvG0pAm2QySf4JGhfaXxVBESYLAvbt81IYw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=agiHcwHQYjqR21ZxeMlW3kGItfWov7MzHyXYfOf/pUPR7UPdqr89wKMSzRqOODq4y
	 CQlNh0wWxtjxqnjjfv48Uanb/pNH6hrt2pIwzFERgQruDXoWDiimnHRdvmJs0zsgsf
	 FP0SomxQ55YJgEbX1vXZZ23oaQlFGHf57lKhqk+E=
