### ISSUE TITLE
Sidebar behavior changes when its locked in comparison to when its  dynamically shown

### ISSUE THREAD

**Issue by Gentlehag** [angular/material#5952]
I've a very basic view with a sidebar see http://codepen.io/anon/pen/zvVJMx

Now when the sidebar is locked its just a content area on the left side of the main content. 
but when its dynamically shown it behaves completly different

This way it looks like when its locked
![image](https://cloud.githubusercontent.com/assets/4619513/11438792/812a3754-94f7-11e5-9ad1-b607a0249bb1.png)

and this way when its dynamically shown
![image](https://cloud.githubusercontent.com/assets/4619513/11438802/8e01f11a-94f7-11e5-815e-11dd41df6b16.png)

it grays out content and overlaps the main content

So what can I do to have it always the same style? 

I also posted here if someone is collection SO points 
http://stackoverflow.com/questions/33954476/angular-material-not-locked-sidebar/

**Comment by EladBezalel** [comment]
This is the normal behavior of sidenav, to contain sidenav inside you content change
``` html
<div layout="row" flex>
...
</div>
```

with
``` html
<md-content layout="row" flex>
...
</md-content>
```

for further information, please ask in our [forums](https://groups.google.com/forum/#!forum/ngmaterial).
