### ISSUE TITLE
md-autocomplete issue with position fixed

### ISSUE THREAD

**Issue by morriq** [angular/material#5953]
Hey, I have big issue with this since begining.

Check this out. 
http://jsfiddle.net/54mh0skf/20/

Testcase:
1. scroll down #page
2. write something in autocomplete. It will display no matches info on the top of input.

**Comment by DevVersion** [comment]
Hello (again),

I'm trying to understand your issue, but I can't figure it out. 
You mean there are no Query Matches (like `Alabama`) ?

Everything is the same, if I remove the `fixed` property or if I don't scroll down.

**Comment by morriq** [comment]
is it works on your machine even after scrolling down?
I'm testing it on chrome 46

Here is video showing bug
http://screencast.com/t/9WwqFK01p

**Comment by DevVersion** [comment]
Yes, I can't reproduce that issue on my Chrome Version 46.0.2490.86 m

![](https://i.gyazo.com/495c9135670b929ae64e33157521aec7.gif)

**Comment by morriq** [comment]
lol :D. Ok, I think it can be reproduced in some specific testcase http://screencast.com/t/WAg2l5xw7vC

**Comment by DevVersion** [comment]
So I didn't get it in the video. What did you changed to fix the issue?

I make gives, using `Gyazo`

**Comment by morriq** [comment]
Actually I changed nothing, just resize jsfidle's iframe

![](https://i.gyazo.com/713cd6bc81d9b0bdffb56a02dea4d2d1.gif)

There is still space to put it above input:
![](https://i.gyazo.com/49ebae357638b66a20dbf32a18f7da2f.png)

**Comment by DevVersion** [comment]
That logic, if the window is definitely too small, then we don't know where to place the popup. That's not a bug

**Comment by morriq** [comment]
Not exactly.On examples below window has 640px height

![](https://i.gyazo.com/ed277775c313607402419231cdc08572.gif)

I modifed positionDropdown function adding

```javascript
 if (window.scrollY) top += 60;
```

![](https://i.gyazo.com/6cfdc6cdcaa8c8381da4090f3868601c.png)

And here is results: 

![](https://i.gyazo.com/0f1697136f903844f2bc754d65bdfcc6.gif)

I know it's workaround and real issue is deeper

**Comment by morriq** [comment]
this workaround didnt solve problem, so I'm trying with something else:

Added
```
    if (!$mdUtil.disableScrollAround._enableScrolling) return $mdUtil.nextTick(positionDropdown, false, $scope);
```

Right below:
```
if (!elements) return $mdUtil.nextTick(positionDropdown, false, $scope);
```
