### ISSUE TITLE
<md-progress-circular> Confusing diameter property, possible bug

### ISSUE THREAD

**Issue by nathanmarks** [angular/material#5955]
A circular progress indicator with `md-diameter="40"` results in a spinner roughly ~20px in diameter.

Is this by design? I feel like the `diameter` should not include any padding, otherwise the terminology is confusing.

![image](https://cloud.githubusercontent.com/assets/4420103/11443684/0d6d5972-94ed-11e5-95dc-49dc74b98258.png)

**Comment by karthik-rp** [comment]
It was actually as you mentioned till 0.11.4, I don't see any reason why it was changed.
Its better if its reverted back or terminology is changed.

+1

**Comment by conniew** [comment]
+1, seems to be this CSS: https://github.com/angular/material/commit/ff2e92b4b97b5d2531bb53110127b24ffb8b741a#diff-30944a809922510e5d8034a3d99cc5c8R145
