### ISSUE TITLE
When will datepicker actually be usable?

### ISSUE THREAD

**Issue by kpgarrod** [angular/material#5959]
I really appreciate what this project has delivered and would hate to seem ungrateful, but the constant slippage of the md-datepicker issues from release to release is giving me a major headache. I have been waiting for a usable datepicker since 2014 and it has always been 'just around the corner'. 

I see that a number of md-datepicker fixes have been pushed out again to rc7 and would really like to know if they will actually be fixed  in that release or not. For me the critical issues are #4233 and #4251. The datepicker is practically unusable without those issues being addressed and yet they still have priority:medium which concerns me.

It is not a trivial task to implement a different datepicker that is compatible with angular-material forms without JQuery, so I would really appreciate knowing when the md-datepicker will actually be usable.

Thanks again for a great project!

**Comment by LeoLozes** [comment]
This. The work being done in the project is amazing, and that's probably why the datepicker feels like it has been botched (at least so far).
 
It's probably one of the most complicated components there is, and it has to take into account a lot of things, but the list of things going wrong is just growing:
- fixed white background.
- scrolling is nice, but really not basic-user-friendly. 
- broken when used with an input-container.
- doesn't work with the other inputs (alignment).
- can't select years / months.
- no linked datepickers (basic from / to use case, the "to" can't be smaller than the "from").

And like @kpgarrod, we can only thank you once again for the great job you're doing!

**Comment by michaelkrog** [comment]
Meanwhile... I am using this polyfill which is pretty okay-ish.
http://chemerisuk.github.io/better-dateinput-polyfill/

**Comment by jelbourn** [comment]
Closing this issue since it's all things that are captured by other issues. We do want to get fixes for these things, but other work has taken priority. Be sure to follow those individual issues for updates.

**Comment by kpgarrod** [comment]
@jelbourn, @ThomasBurleson  Just to be clear, this is more of a project management issue than a technical one. The question is whether the underlying technical issues with md-datepicker will actually be addressed in 1.0-rc7, on or about 10 December, or they will be pushed out again. This is a critical question from the point of view of a user's project planning and is distinct from the technical issues.
