### ISSUE TITLE
md-contact-chips suggestion blank my webpage

### ISSUE THREAD

**Issue by johnlim5847** [angular/material#5960]
Hi, I just upgraded from version 0.10.0 to 0.11.4 and i'm having some issues with the md-contact-chips, everything is working perfectly fine just that when i search on my contact chips it happens to blank my webpage with the suggestion. The md-contact-chips is being injected into a nested ui-view, if i place it on the first ui-view it works but if it is in a nested ui-view it blank the page with the suggestion.
**Before search**
<img width="1278" alt="screen shot 2015-11-28 at 3 16 28 am" src="https://cloud.githubusercontent.com/assets/3675946/11447279/8fb52db0-957e-11e5-82a1-9613be1754bb.png">
**After search when suggestion show up (it blank half of my page as show in the picture below)**
<img width="1280" alt="screen shot 2015-11-28 at 3 16 41 am" src="https://cloud.githubusercontent.com/assets/3675946/11447280/8fb5c4be-957e-11e5-8bda-bdbc468bf7c7.png">
**After pressing enter on suggestion (it is back to normal)**
<img width="1280" alt="screen shot 2015-11-28 at 3 16 49 am" src="https://cloud.githubusercontent.com/assets/3675946/11447281/8fb9e38c-957e-11e5-8854-965bce624349.png">

is there a way to solve this problem? i think it got to do with css but i'm not sure which part of the css should i overwrite.

**Comment by topherfangio** [comment]
@johnlim5847 Any chance you can provide a Codepen demo so we recreate it and help debug?

If not, my guess is this has something to do with the sizing of the `md-virtual-repeat` container that the chips use. This gets appended to the `<body>` tag and is invisible when the suggestions are hidden. You can probably find the element and force it to be visible with CSS `display: block` and then figure out what CSS you need to alter.

**Comment by topherfangio** [comment]
If you can provide a demo for this (using the latest 1.x release), we would be happy to reopen this issue and investigate further.
