### ISSUE TITLE
fabSpeedDial: md-tooltip doesn't disappear sometimes

### ISSUE THREAD

**Issue by STOpandthink** [angular/material#5963]
Straight from https://material.angularjs.org/latest/demo/fabSpeedDial (More Options) example:

* However over the FAB to expand
* Click on Twitter button, hold the button, drag the mouse away until the FAB hides, then release
* Hover over the FAB to expand again
* Hover over Twitter button, then hover away.
* Note that the tooltip doesn't disappear

I think there are easier ways to cause this to happen, but this is the one I was able to reproduce consistently.

**Comment by jpike88** [comment]
Having this issue as well, Safari on El Capitan.

**Comment by topherfangio** [comment]
I believe this is simply an issue with the demo because it uses `md-autohide="false"` on the tooltip and binds the `md-visible` to a scope variable.

It looks like there is some conflicting action in the demo between the scope variable and the auto-hiding. If you set `md-autohide="true"`, it gives a slightly different functionality, but fixes the issue you are mentioning.

**Comment by STOpandthink** [comment]
Thanks, Topher, looks like that does fix that issue.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (404/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:14971)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avsZJ-001Z0t-VU
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:29:50 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=YoBf6+bvGH0Ifut8db4vRTiKPC4=; b=lQ9O5LkcNedkx0m1
	A3a/DNEn7nxCo+nSx2Bg7Se6eRLrp5HvjPXT29b64K0n0L81oXjr4A4Yi3bFTl7Y
	RHHY84oLpmduTtj9R8wE72pzehTpDxcoewVZLO4+1Iuw9PjmB6fzgNAAAspfVARB
	3rBE6dnWEP7JxegC4W/hyoXWSVo=
Received: by filter0523p1mdw1.sendgrid.net with SMTP id filter0523p1mdw1.15474.5722724834
        2016-04-28 20:27:52.596942237 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id mPF2JrzQS9Kh3LY1aHrekQ
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 20:27:52.576 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:27:52 -0700
