### ISSUE TITLE
<md-select> in Dialog/Modal Box not shows

### ISSUE THREAD

**Issue by himanshuapril1** [angular/material#5964]
When using <md-select> in a Bootstrap Modal or even in Angular Material Dialogue box, it doesn't show, there is z-index issue in css file at-
<code>.md-select-menu-container {
    position: fixed;
    left: 0;
    top: 0;
    z-index: 90;
    opacity: 0;
}</code>
Currently it's value is <code>90</code>, I think there should be some fix to it with javascript or We can define a value like - <code>9999</code> to it in css by default, so that it can appear even in modal box.

**Comment by ThomasBurleson** [comment]
Not supported.

**Comment by himanshuapril1** [comment]
'Not Supported' ?? What does it mean?? Is it fixed now or not?
