### ISSUE TITLE
chips layout is not visible

### ISSUE THREAD

**Issue by arushijain45** [angular/material#5966]
Hello community, I am new to angular-material. I tried using md-chip as follows:
<md-chips>
<md-chip>Hockey</md-chip>
<md-chip>Base Ball</md-chip>
</md-chips>

as seen in docs: https://material.angularjs.org/0.9.3/#/demo/material.components.chips
Demo for displaying a set of items as chips.

But in contrast of demo my items does not have any layout. It looks like this:

Hockey  BaseBall

I have also seen in thread https://github.com/angular/material/issues/2333
But could not find the solution. Any suggestion would be highly appreciated.

**Comment by DevVersion** [comment]
You should use the latest Release Candidate `RC5` 
Here is the current documentation for using `md-chips` (https://material.angularjs.org/latest/demo/chips)

**Comment by arushijain45** [comment]
@DevVersion the link you attached above is also using chips alike. I could not find any difference.

**Comment by DevVersion** [comment]
Okay, then you should provide your code (perhaps use codepen.io). And it would be great if you create a screenshot of your current `not working page`

**Comment by arushijain45** [comment]
I got the solution, the problem was with angular-material version. Using HEAD instead of 0.11.4 resolved my issue.
