### ISSUE TITLE
header title is not horizontally align with avatar in md-card

### ISSUE THREAD

**Issue by arushijain45** [angular/material#5968]
Hello everyone, I am trying to use md-card as follows:
[New Text Document (6).txt](https://github.com/angular/material/files/46338/New.Text.Document.6.txt)

as given in demo:
	https://material.angularjs.org/HEAD/demo/card

But what I observed is my card shows all thing vertically align
Avatar image
Below Avatar image, UserName

But demo shows me different layout.
Can u help me what I am doing wrong.

**Comment by DevVersion** [comment]
Hello, please fix your screenshots, they aren't working

**Comment by arushijain45** [comment]
@DevVersion thank you for your quick response, I have updated my issue.

**Comment by DevVersion** [comment]
Because I want to simplify reading your issue I provide your given code in Markdown, not in an extra file

```
<md-card>
    <md-card-header>
        <md-card-avatar>
            <img class="md-user-avatar" src="user_avatar.png" />
        </md-card-avatar>
        <md-card-header-text>
            <span class="md-title">UserName</span>
        </md-card-header-text>
    </md-card-header>
    <img ng-src="{{imagePath}}" class="md-card-image" alt="Washed Out">
    <md-card-title>
        <md-card-title-text>
            <span class="md-headline">In-card mixed actions</span>
            <span class="md-subhead">Reversed</span>
        </md-card-title-text>
    </md-card-title>
    <md-card-content>
        <p>
            The titles of Washed Out's breakthrough song and the first single from Paracosm share the two most important words in Ernest Greene's musical language: feel it. It's a simple request, as well...
        </p>
    </md-card-content>
</md-card>
```

I just took a look at your code and applied the flexbox layout. 

http://codepen.io/DevVersion/pen/YymzOm
Check that codepen, that's a working demo

**Comment by arushijain45** [comment]
@DevVersion thank you for your action. I am not getting how you did this. Is there is a problem with installation of angular-material with me or anything.

**Comment by DevVersion** [comment]
Can you provide a screenshot of your current page? A few screenshots, so I can investigate better

**Comment by arushijain45** [comment]
@DevVersion I got it what I was doing wrong, I was using 0.11.4 version of angular material. Probably that version does not have this feature.

**Comment by DevVersion** [comment]
Great :+1: Then you can close that issue ;) (that would be great)
