### ISSUE TITLE
fab speed dial

### ISSUE THREAD

**Issue by emps** [angular/material#5969]
fab speed dial do not get opened with touches (using chrome mobile debug view)
'latest' version of angular material, but works with 'master'

**Comment by DevVersion** [comment]
![](https://i.gyazo.com/5a371fcd283bd336f060cac1eeedb6f7.gif)

It's working for me (and yes: I simulate touch events)

**Comment by marcysutton** [comment]
Are you checking it on an actual device?

**Comment by topherfangio** [comment]
@emps You say that it ***does*** work on master? Master is newer than RC5, so it's quite possible something was fixed since then.

**Comment by emps** [comment]
thanks it fixed with latest
