### ISSUE TITLE
Labeling md-radio-group

### ISSUE THREAD

**Issue by anandshankar** [angular/material#5975]
Hi Experts,

I am using md-radio-group/md-radio-button in one of my forms along with md-input-container/label/input tags.

I need two radio groups, say,  'My Most Preferred Work Location' and 'My Most Undesirable Work Location', with same set of radio buttons, say, 'Delhi', 'Mumbai', 'Pune', 'Bangalore'. 

My problem is that I don't see any option to set a label for each of the radio groups, at least with the same look and feel as the input component. 

Any suggestions to me how to achieve it or can we have some thing for labeling radio groups and check box groups similar to input components? 

Best Regards
Anand

**Comment by DevVersion** [comment]
Your mean something like that?
![](https://i.gyazo.com/b2c306a760090d9e5110711173a480f4.png)

You're right, it doesn't look as the other Material Labels... but I think that's by intention.

**Comment by anandshankar** [comment]
Yup right. But can't imagine the intention. It looks so different in size and color from rest of the form.

**Comment by DevVersion** [comment]
Yes I can feel the same. You have any ideas in styling that label?

**Comment by anandshankar** [comment]
To make it consistent with Input component, it would be nice if <md-radio-group> allows a <label> as an immediate child tag, similar to <md-input-container>. If an immediate child <label> is found, it gets transformed similar to <input>'s label. 
Some of the expected behavior can be as follows:
- If any of the radio buttons/ check boxes are selected, group's label should be styled similar to label of <input> tag which has got focus or is already filled, if not, it should be styled as an input tag not in focus and not initial value. Of course, there wont be any floating feature as well as no different styles based on validation.
- Secondly, similar to <input>'s label in disabled state, radio group's label should also be styled accordingly.

**Comment by EladBezalel** [comment]
dup #5834

**Comment by ravidannani** [comment]
I have the same requirement but with angular 6. I could not get any solution to style the label similar to same look and feel as the input component.

Also I looked into below link,
https://codepen.io/jakobadam/pen/xqZoBR
but it was angular 1, and I tried to replace md-input-container with mat-form-field but it throws below error.
 "mat-form-field must contain a MatFormFieldControl."

I am not sure what to do further. Could you please give some suggestions. 

Thanks for your help.

**Comment by Splaktar** [comment]
@ravidannani Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2). This repo is for AngularJS Material.
