### ISSUE TITLE
changelog.md file is wrong about "md-dialog-content"

### ISSUE THREAD

**Issue by tolemac** [angular/material#5978]
I think there are an error on changelog.

On 0.11.0-rc1 breaking changes you can see:

    <md-dialog-content>
       <h2></h2>
       <div class="md-dialog-content-body">
         <p></p>
        </div>
    </md-dialog-content>

But the correct way is:

    <md-dialog-content>
       <h2></h2>
       <div class="md-dialog-content">
         <p></p>
        </div>
    </md-dialog-content>

Are you agree?

**Comment by ThomasBurleson** [comment]
No. `class="md-dialog-content-body"` is correct.

**Comment by tolemac** [comment]
then I think the docs are wrong?
In this demo: https://material.angularjs.org/latest/demo/dialog on DIALOG1.TMPL.HTML I can see:

    <md-dialog-content>
        <div class="md-dialog-content">

In addition, after update from 10.1 version to 1.0 RC5 I have used `md-dialog-content-body` and my dialogs appears without margins, then changing `md-dialog-content-body` by `md-dialog-content` the margins appears fine.

Perhaps I am confused, sorry if is it.
