### ISSUE TITLE
Layout row with vertical stretch not working as expected

### ISSUE THREAD

**Issue by julienpa** [angular/material#5979]
If you set a container with `layout="row"` and `layout-align="center stretch"` (or anything other than _start_ for the first align parameter), it won't work as expected since the child elements will be aligned on the left as if it was `start stretch`.
Same result with _stretch_ as the first param, and with `layout="column"`.
This behavior can be seen directly on the demo page (Chrome 46): https://material.angularjs.org/latest/layout/alignment
<img width="766" alt="capture d ecran 2015-11-29 a 20 13 47" src="https://cloud.githubusercontent.com/assets/4720300/11460562/c67acc80-96d5-11e5-9dc0-d765f0adced4.png">

**Comment by ngraef** [comment]
This was fixed on master by 3d65dea8003375ec41cf4ff5be6f1376b85f5a71. You can check it out at https://material.angularjs.org/HEAD/layout/alignment

**Comment by julienpa** [comment]
@ngraef nice! Hadn't checked out the updates on HEAD... Good to know :)

**Comment by julienpa** [comment]
Fixed in 3d65dea
