### ISSUE TITLE
md-toast flexbox issue windows phone 8.1

### ISSUE THREAD

**Issue by graphefruit** [angular/material#5982]
Hello Team,

the toast-popup in Windows Phone 8.1 isn't flexing the button to the right.
![toast](https://cloud.githubusercontent.com/assets/6260244/11466932/0f04220c-9745-11e5-9f4f-de39ea7951af.png)

This is because the <span flex> element isn't a block element, if I change the element to:

```<div flex> or <span style="display:block" flex> ```
The button is aligned to the right.

This just occurs on windows-phone.
![toast](https://cloud.githubusercontent.com/assets/6260244/11465628/ae6e3c98-973a-11e5-87c0-74788086aa1c.png)

Greetings & Thanks
Graphefruit

**Comment by ThomasBurleson** [comment]
@topher - Your fixes may be dependent upon https://github.com/angular/material/pull/6082/
