### ISSUE TITLE
hide-sm not working screen smaller than 600px in 1.0.0 RC5

### ISSUE THREAD

**Issue by windhunter89** [angular/material#5983]
@media (max-width: 959px) and (min-width: 600px)
.hide-sm:not(.show-sm):not(.show), .hide:not(.show-sm):not(.show) {
    display: none;
}

So it make smaller 600px screen show back the div

**Comment by felipemeirelles** [comment]
+1

**Comment by felipemeirelles** [comment]
Also, layout-sm is bugged too

**Comment by felipemeirelles** [comment]
In fact all -sm aren't working

**Comment by julienpa** [comment]
Discovered the same issue today after running `bower update`
It is because a new breakpoint has been secretly introduced: *-xs

See: https://github.com/angular/material/blob/master/src/core/style/variables.scss
I hadn't seen this issue and opened a new one, related to the same thing: #5995

**Comment by felipemeirelles** [comment]
The problem is, the breakpoints changed, but the directives dont, so I can't do hide-xs, can I? Also, the docs are outdated too.

**Comment by julienpa** [comment]
Yes @felipemeirelles, I have the same problem and can't use things like `flex-xs`...
I believe the problem (at least for me) is that my bower file is configured on `^1.0.0` for Angular Material which seems to point directly to the latest commit from master, and not to the latest release tag. You can fix this by setting the bower dependency to `1.0.0-rc5` explicitely.

**Comment by zevmo** [comment]
@felipemeirelles is correct. xs was introduced, but as a result sm doesn't work anymore.

**Comment by julienpa** [comment]
@zevmo `sm` works, it's just not the same value anymore. `xs` is going to be the old `sm`, and now `sm` as the same value as the _old_ `md`...etc.

**Comment by zevmo** [comment]
@julienpa You're right. I meant to say that hide-xs isn't working for me. Sorry.

**Comment by ThomasBurleson** [comment]
@windhunter89 - where do you see this invalid/incorrect **@medai** query? The latest builds appear correct:  https://github.com/angular/bower-material/blob/master/angular-material.css#L2798.

**Comment by ThomasBurleson** [comment]
@julienpa - are you using the latest build from master ? If yes, please provide a CodePen that demonstrates the issue with **hide-xs**. Thx.

**Comment by julienpa** [comment]
@ThomasBurleson I was using `^1.0.0` in my bower.json which seems to use the latest commit from master, even if it's been done after the latest tagged release. I didn't have problem with `hide-xs` personnally, just `flex-xs` that wasn't working when I tried 2 days ago.
Thanks!

**Comment by Mylogin-info** [comment]
@ThomasBurleson

I have the same is issues:

This doesn't work:
-div layout="row" layout-xs="column"-

When I add the class by hand it works:
-div layout="row" class="layout-xs-column"-

I'm on:
v1.0.0-rc5-master-358fd98 (.js and .css)
Chrome Browser

**Comment by ThomasBurleson** [comment]
@Mylogin-info - Thx this is helpful. We will resolve today.

**Comment by ThomasBurleson** [comment]
@windhunter89, @Mylogin-info, @julienpa, @zevmo - Thanks for this issue report and your persistence. This revealed some important oversight(s) for **xs**, **gt-xs**, and **xl** breakpoints that were missing in recent Layout api changes. 

> The above Pull request should be merged today

**Comment by julienpa** [comment]
It will also fix #5995 then.
Thanks for keeping us posted @ThomasBurleson!
