### ISSUE TITLE
directive for optional remove layout attribute

### ISSUE THREAD

**Issue by Stefan2505** [angular/material#5984]
1.0.0-rc5 does not remove layout attribute anymore (https://github.com/angular/material/commit/7cb035d9). Its a cool improvement for better DOM structure, but generates in my code other problems. 

I create a directive for removing the layout attribute:
```
(function(){
    'use strict';

    angular
        .module('ngMaterial')
        .directive('removeLayoutAttr',removeLayoutAttr);

    removeLayoutAttr.$inject = [];

    function removeLayoutAttr() {

        var directive = {
            link: function(scope, element, attrs) {
                element.removeAttr('layout');
            },
            restrict: 'A'
        };

        return directive;
    }
})();
```
and it can be used like this:  ```<div remove-layout-attr></div>```

It would be great if this directive will be integrated in the future releases.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
