### ISSUE TITLE
Website looking horrible with IE 11

### ISSUE THREAD

**Issue by reisi007** [angular/material#5988]
I am speaking of http://reisi007.github.io/ at version https://github.com/reisi007/reisi007.github.io/tree/81dc7c1c24173a8c352e07f69847c4e973a58a52.

1) The picture in the sidebar should be 140x140px, but isn't most time.
2) The height of the cards is too tiny, so that not all text fits in it.
3) when loading the page with a smaller width (e.g. 490px) the page looks even more destroyed.

![3 visualisation](https://cloud.githubusercontent.com/assets/2719454/11476425/f471198e-9782-11e5-8d42-86009411db07.PNG)

Looking "perfect" on Chrome. Both tested on Windows 10.

I am not really god in designing websites, so it could be me to blame as well.

Thanks for looking into this issue.

PS: I just updated the page to RC5 and the situation got slightly better :) Thanks for improving support!

**Comment by Wardormeur** [comment]
For 2) and 3), see #5382

**Comment by reisi007** [comment]
@Wardormeur thanks for your suggestions. So issue 1 in more detail.
In the sidebar I have an image:  

    <img src="https://s.gravatar.com/avatar/27b7b7ec5ea21af0864b83d9107ac302?s=140"  width="140px" height="140px"
     style="margin-top: 12px "/>

Should (Chrome): 
![should](https://cloud.githubusercontent.com/assets/2719454/11501859/945d980a-9837-11e5-93ba-67fa1dbe5f6b.PNG)
Is (IE11)
![is](https://cloud.githubusercontent.com/assets/2719454/11501864/9cadd0a6-9837-11e5-9711-4209ca49de10.PNG)

No idea what is happening here....

**Comment by ThomasBurleson** [comment]
@reisi007 - Please provide a CodePen with this image issue. 

> Have you tried manually (without Material Layouts) apply flexbox styles to see if the same image issue occurs?

**Comment by reisi007** [comment]
Hi,
Should I post my website as a codepen?
@ThomasBurleson It seems flex related.

     <md-sidenav layout="column" class="md-sidenav-left md-whiteframe-4dp" md-component-id="left"
                md-is-locked-open="$mdMedia('min-width: 40rem')">
If I remove `layout="column"` and add a div as first child element with layout="column" it works. So a layout bug related to md-sidenav (I guess).

So only the issue better described in #5382 remains. Still some wired animation behavior (when opening sidebar picture is invisible. Gets visible when sidebar has opened.

Anyway thanks for your time triaging my bug and sorry I couldn't provide a codepen, which makes sense.

Please tell me if it is of any use to make a codepen from the current version of the website.

I guess this can be closed as for 1 & 2 we have an older and better bug and 3 can be fixed with a inner div. I won't close it as I am not sure its the right thing in your project's workflow.

**Comment by ThomasBurleson** [comment]
@reisi007 - you may need to set your CSS to include `img {  width:100%; max-width:100%; }`.
Closing unless you can provide a CodePen.
