### ISSUE TITLE
Contrast color of buttons in toolbars

### ISSUE THREAD

**Issue by cgx** [angular/material#5989]
When assigning the _accent_ or _warn_ palette to a toolbar, the **buttons** use the contrast color of the primary palette instead of respecting the contrast color of the active palette.

This [pen](http://codepen.io/flachapelle/pen/rOXKVB) shows that the button color doesn't change when the hue changes as the text does.

**Comment by cgx** [comment]
![flachapelle-pen-roxkvb](https://cloud.githubusercontent.com/assets/1088448/11722588/9f8cc564-9f37-11e5-91d0-b53934a42210.png)

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (504/500 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:46672 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsbd-000Krn-Fv
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:13 -0500
Date: Thu, 28 Apr 2016 13:26:07 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875167;
	bh=K3Eng4F1A2HH7PMraC2JOnyqKb7CsWq30rWpIAyVfzc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Yv5w/FeLWKqzOxi2vaXBVD8+6czpBfdn5WWh6TMKak7QCenquQ4Mx8XjMbrflaysD
	 jmwcWx4UpT8OTZ5iQ5x0qWlBZsPC+3l314pobis7C9NFQSOnrEu1Qf9Lhvp0QBrSP+
	 URSuwO/083YbuaDGpkN8+Okwk0n9x/neC5e5jPhQ=
