### ISSUE TITLE
Demo site on desktop/mobile chrome + suggestions

### ISSUE THREAD

**Issue by m-rakic** [angular/material#599]
Hi,
Really great work, I’m impressed how is fluent and nice! 
I was using Angular material design for about 8 hours and managed to get app infrastructure working nice not sure if is a right place post my impressions and experience but hope can help.
Didn't read all issues so maybe some observation is already in issue list.

Desktop:
About demo site, using chrome 38.0.2125.111

Sidenav
- the sidenav left has button "Toggle left", the button was not visible on bigger screen size and visible on lower screen size (like hamburger button),
This was functionality in ng-europe session http://www.youtube.com/watch?v=2qiyhkQVyxE ... 8:40 ...  but now not anymore not sure if is a issue or is by design :)

- will be nice to have drag effect to close/open a left/right sidenav panel (like we have a bottom sheet than can be closed, very nice :) ) 

Lists
- Noticed that list items does not have ink effect, should we wrap content in transparent button with ink effect or will be added?

Missing things
- Validations, date control I see that will come and will be very nice to have it. (saw it in issue list that is on way)

- Missing integration examples with different controls together.
Depend how you set it up there is different behaviours, when we don't have some guide lines then is lot of possibilities :).

- Not sure if is part of material design to show but will be nice to have a animated transitions between pages (for list and data I think there is examples), example from left to right and from right to left etc.
Because material design is setting up UI and will be nice to have a transition examples between them.

Mobile:
I was playing with my mobile and went through site, notice following issues on Android 4.42. Chrome 38.0.2125.114

Sidenav:
- If the left sidenav is open and then click on hamburger icon of site, the main menu is shown under nav left.

Bottom sheet
- When I clicked "Show as list" was just expanded less than half, I tried to drag it up to see last item but didn’t manage to see "Print this page", for grid is same problem not all icons is shown (on my test project this is working fine all 4 items is visible)

Text fields
- Can't scroll the form only if you drag right part of screen on scrollbar (scrolling problems)

Toast
- I has to be pushed little bit more down

**Comment by m-rakic** [comment]
I find out element... md-ink-ripple="#bbb"... this can be used to add ink effect to the elements to make it interactive ... so if you want interactive list items add following

<md-item-content md-ink-ripple="#bbb">

**Comment by marcysutton** [comment]
But you *must* make them work from the keyboard, too! Make sure you can tab onto anything with a click and fire it from the keyboard. Here is some info on it: http://marcysutton.github.io/angular-a11y/#/11

**Comment by marcysutton** [comment]
Many of these issues have been already addressed or are reflected in other issues. In the future, please help us by creating separate issues for each item–long lists of things are very hard to work with.
