### ISSUE TITLE
layout-align: Resetting to default when only one argument

### ISSUE THREAD

**Issue by epelc** [angular/material#5996]
`layout-align` no longer works with a single argument. It will replace it with `layout-align="start-stretch"` which drastically changes layouts.

One Example
`layout-align="space-around"` no longer works since 1.0.0-rc5. It is replaced with `layout-align="start-center"` when it should default the second argument to `center` ie parse `layout-align="space-around"` as `layout-align="space-around center"`.

This also happens with the other single argument usecases like `layout-align="space-between"`. I'm suspectting the recent change to the default `layout-align` introduced this issue.

**Comment by ngraef** [comment]
The issue is in [`layout.js` line 437](https://github.com/angular/material/blob/f22b2fecc9feab970210165aa312d9680c555426/src/core/services/layout/layout.js#L437):
```javascript
var values = (value || "").replace(WHITESPACE, "-").split("-");
if ( values.length == 3 ) {
  values = [ values[0]+"-"+values[1],values[2] ];
}
```

The conditional check for `values.length == 3` assumes that a cross axis argument was provided if the main axis is `space-around` or `space-between`.

I'll submit a PR.

**Comment by julienpa** [comment]
But the default cross-axis value is `stretch` in Flexbox specification, and it is the one applied if you don't specify the second parameter, as the doc states:
https://material.angularjs.org/latest/layout/alignment

Or am I missing something?

**Comment by ngraef** [comment]
@julienpa Correct. There's just a parsing issue if the only value provided is `space-around` or `space-between`. It gets processed as two separate values (i.e. `space around`), neither of which is a valid value, so it gets replaced by the default `start stretch`.

**Comment by julienpa** [comment]
@ngraef ok, I understood now. Can it be linked in any way with the problem I describe in #5979?
