### ISSUE TITLE
Remove jQuery Dependency 

### ISSUE THREAD

**Issue by ajoslin** [angular/material#60]
Pending Web Animations polyfill.

**Comment by dziamid** [comment]
I'm getting `element.height() is not a function` in `growTextarea` function when using without jquery.

**Comment by thynctank** [comment]
@dziamid That's right. JqLite does not include this method. See https://docs.angularjs.org/api/ng/function/angular.element for the list of methods it *does* include.

**Comment by dziamid** [comment]
@thynctank why is in the source code then?

**Comment by ThomasBurleson** [comment]
@dziamid - do you see a `height()` call in the Angular Material source? Are you using the latest version from [master](https://github.com/angular/bower-material/tree/master)?
