### ISSUE TITLE
Layout: Switch breakpoint units to em instead of px 

### ISSUE THREAD

**Issue by epelc** [angular/material#6001]
Right now the various layout breakpoints are using pixels for their units. I just found out you can use ems instead and there are several benefits especially when zoomed.

http://blog.cloudfour.com/the-ems-have-it-proportional-media-queries-ftw/

I found out about it from the recent chrome devtools update video with TechCrunch using ems for their breakpoints. It may be a good idea to look into switching before 1.0

**Comment by RolandHeath** [comment]
Looks like #4974

**Comment by epelc** [comment]
Didn't see that one. I'll close this as duplicate.
