### ISSUE TITLE
wrong floating label position in input fields with icons

### ISSUE THREAD

**Issue by jb29** [angular/material#6005]
Just look at the [md-input demo page](https://material.angularjs.org/HEAD/demo/input) in the icons section. The placeholder overlaps with the icon. Must be one of the commits of Nov 30, 2015.

![2015-12-01_08h49_11](https://cloud.githubusercontent.com/assets/13062631/11495061/6eb03e8e-9808-11e5-8c1f-96ff6ef938c3.png)

**Comment by DevVersion** [comment]
Here is a PR, which fixes that #6013
