### ISSUE TITLE
md-select + md-checkbox wrong label position v1.0.0-RC5

### ISSUE THREAD

**Issue by norkunas** [angular/material#6006]
![image](https://cloud.githubusercontent.com/assets/2722872/11496131/aec6d054-9818-11e5-8e20-bd3778a30cf0.png)

http://codepen.io/norkunas/pen/RWXOgr

**Comment by himanshuapril1** [comment]
There is no such problem in version, it's just a problem of your syntax, wrap up your checkbox either into md-input-container(refer below) or into simple Div using flex-


    <md-input-container flex="25">
        <md-checkbox ng-model="data.cb1" aria-label="Checkbox 1">
          Checkbox 1: {{ data.cb1 }}
        </md-checkbox>
    </md-input-container>

**Comment by norkunas** [comment]
ha, forgot about that, thanks for reminding

**Comment by himanshuapril1** [comment]
Cool :+1:
