### ISSUE TITLE
mdSidenav: Blurry content in IE

### ISSUE THREAD

**Issue by Belicosus** [angular/material#6007]
The same goes for mdDialog.

This is clear clear on the demo page when using the sidenav and the dialogs.

### Sidenav:
When opening the sidenav from the right, the content is blurry.
https://material.angularjs.org/latest/demo/sidenav

### mdDialog:
This would be related to this issue #4544 
https://github.com/angular/material/issues/4544
This is also visible when using the demo for mdDialog on material.angularjs.org.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (511/500 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:59158 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsc3-000L0x-8f
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:39 -0500
Date: Thu, 28 Apr 2016 13:32:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875532;
	bh=6fCGpQB0C7/Hy+nZHu97eYZJqau+bevTPeb6kFyAxwA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ht9kbotqOPu6dysjj8gfONitekjChtQxdboimRzhEWLBTRGClrTsFVPxRNqjO7Cug
	 AaiRs1TMWccN3rsdMi7MuPey1Tx4DCd3399bcE4OUZ6S+tK7TFYNl4jq8neNmERQM+
	 8IGHSldDzaAXpCRJ8PCkKv4fudjHlxXtYw0LbCjM=

**Comment by Splaktar** [comment]
Fix for this is in `sidenav.scss`:
```scss
.md-sidenav-right {
  left: 100%;
  top: 0;
  transform: translate(-100%, 0);
  &._md-closed {
    transform: translate(0%, 0);
  }
}
```

Reference: https://github.com/angular/material/commit/689a34da23f68d76ab682544f46441005ec20fd9

**Comment by ThomasBurleson** [comment]
@Splaktar  - thx for the alert and the PR.

**Comment by Splaktar** [comment]
@ThomasBurleson no problem :)

I think the same fixes that apply to the `md-sidenav-right` also apply to the `md-sidenav-left`, but so far I've only been able to reproduce the blurry `md-sidenav-left` in my app and not in a CodePen (after plenty of effort) or the demos.

**Comment by jftsaraiva** [comment]
I have the same problem with md-sidenav-left, should open another issue or should do a PR for this issue?

**Comment by Splaktar** [comment]
@jftsaraiva open another issue with a demo that shows the issue in the left sidenav please.
