### ISSUE TITLE
md-tooltip "left" position overlaps button

### ISSUE THREAD

**Issue by alphatwit** [angular/material#6011]
"right", "bottom" and "top" all leave a little bit of space between the button and the tooltip. "left" does not
Can be seen here. Select the "left" position

https://material.angularjs.org/1.0.0-rc5/demo/tooltip

![left positioning of tooltip](https://dl.dropbox.com/s/pr0bxk3qla78jtp/Screenshot%202015-12-01%2012.01.36.png)

**Comment by DevVersion** [comment]
That's because the Tooltip can't be shown outside of the content.

http://codepen.io/DevVersion/pen/XXrEXN

As you can see here in my codepen its working on the other button if there is enough place.
