### ISSUE TITLE
layout-align="end" changes to "end-stretch"

### ISSUE THREAD

**Issue by calebegg** [angular/material#6012]
`layout-align="end"` gets replaced with `layout-align="end-stretch"` for some reason. I think that if anything `"end center"` would be better. Or just set `justify-content` and not `align-items` for `layout-align="end"`.

**Comment by ngraef** [comment]
The default CSS value for `align-items` and `align-content` is `stretch`, so this behavior is simply following that spec, and it's the same behavior as omitting those values.

The only issue I see is that explicitly setting `stretch` could override some custom CSS; but it would be kind of silly to use both `layout-align` and CSS to control flex layout alignment on the same element, right?

**Comment by calebegg** [comment]
Ah, I didn't realize, my mistake. I could have sworn the default was either start or center.

**Comment by ThomasBurleson** [comment]
@calebegg the default for the main axis (justify-content is **start**).

```js
'justify-content' : "start";     // default
'align-items' :  "stretch";   // default
'align-content' : "stretch";   // default
```
