### ISSUE TITLE
Can you pass scope from an Ng-repeat to mdDialogue

### ISSUE THREAD

**Issue by Nick-t-go** [angular/material#6014]
Here is my function call to initiate a dialogue box:

<md-content>
    `<md-list>`
        `<md-list-item class="md-3-line"  ng-repeat="post in localPosts | orderBy : 'distance' " >`
           ` <img ng-src="{{post.pictures[0]}}" class="md-avatar" alt="{{post.user.username}}" />`
           ` <div class="md-list-item-text" layout="column">`
               ` <h3>{{ post.user.username }}</h3>`
               ` <h4>Votes: {{ post.votes }} Distance:{{post.distance }}</h4>`
                `<p >{{ post.content }}</p>`
               ` <md-button class="md-primary md-raised"  ng-model="post" ng-click="showAdvanced($event, post)" flex-sm="100" flex-md="100" flex-gt-md="auto">
                    Custom Dialog
                </md-button>`
           ` </div>`
       ` </md-list-item>`
`</md-content>`

Here is my setup:
$scope.showAdvanced = function(ev, post) {
        $mdDialog.show({
            locals: { post: post },
            controller: 'postDetailCtrl',
            templateUrl: 'js/post_detail/post_detail.html',
            parent: angular.element(document.body),
            targetEvent: ev,
            clickOutsideToClose:true,
            fullscreen: $mdMedia('sm') && $scope.customFullscreen
        })
            .then(function(answer) {
                $scope.status = 'You said the information was "' + answer + '".';
            }, function() {
                $scope.status = 'You cancelled the dialog.';
            });
        $scope.$watch(function() {
            return $mdMedia('sm');
        }, function(sm) {
            $scope.customFullscreen = (sm === true);
        });
    };

In my postDetailCtrl I am simply trying to get the post that I am attempting to pass through using the locals. I can't. When I try to access {{post}} in post_detail.html I get nothing. I can use the scope: $scope option on mdDialogue to get all the posts but I just want to pass the one post through to the controller and on to my template. I've tried several different things and none have worked. I'm aware that trying to pass post into the function call doesn't resemble any of the examples in the docs but at this point I am just trying to get creative. Any ideas?

**Comment by rschmukler** [comment]
Exposing it as a local makes it injectable. ie. in your `postDetailCtrl` you have to inject it like this:

```js
function postDetailCtrl(post, $scope) {
  $scope.post = post;
}
```

Hope this helps. Please close this issue if this resolves for you.

**Comment by Nick-t-go** [comment]
This guy right here Mr @rschmukler  got all the answers. Thanks alot. Come to NYC and I owe you a drink! Problem Solved.
