### ISSUE TITLE
floating icons on md-input-container

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6015]
on head. chrome.

only for email and donation.

![screen shot 2015-12-01 at 1 51 25 pm](https://cloud.githubusercontent.com/assets/5133412/11513845/a3fb4bf4-9832-11e5-9617-641224622fb0.png)

**Comment by DevVersion** [comment]
That's not only happening to the E-Mail Input, that's also happening to the Name Field (but there is currently a text placed).

Here is the fix for that issue. #6013
