### ISSUE TITLE
docs: api reference mdSelect incorrectly sized, unclickable

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#6023]
The api reference md-select incorrectly sized and unclickable.  When opened it spans the entire page, and any click will just click through the select.  Only seems to happen on large screens (though #4243 still present here)

![mdSelect incorrectly sized](http://i.imgur.com/cCGHYdb.png)

Potentially related to the recent changes? f73e5033bd4446412ca6b5ce7a769901274f4147

**OS:** Windows 10 x64, Chrome 46, Opera 33
**Steps to reproduce:**  go to a component demo like button, click the api reference drop down.

**Comment by jb29** [comment]
+1, I've got a similar issue. In my app md-select has the correct size, but is incorrectly positioned.
It's not possible to select an option, too.

![2015-12-02_12h00_46](https://cloud.githubusercontent.com/assets/13062631/11529318/9955bfd0-98ec-11e5-9da8-522ead7562d1.png)

**Comment by cleever** [comment]
Same here in Master.

**Comment by tcsiegl** [comment]
+1, position depends on surrounding containers, but options can only be selected using keyboard

**Comment by lmignot** [comment]
+1, same issue when you have an md-select inside an md-dialog, i've setup a codepen to illustrate: http://codepen.io/anon/pen/vLBeBy

**Comment by mckenzielong** [comment]
This was resolved by b3177f2f5cac055f27cc620e27c81c812ef02c50
Closing.
