### ISSUE TITLE
md-autocomplete: iterate over object properties in md-items

### ISSUE THREAD

**Issue by elyas-bhy** [angular/material#6025]
Is there any way to iterate over object properties in the `md-items` directive, in the same manner as [ng-repeat](https://docs.angularjs.org/api/ng/directive/ngRepeat#iterating-over-object-properties)?
```html
<md-autocomplete
    ...
    md-items="(key, value) in ctrl.querySearch(ctrl.searchText)"
    ...>
</md-autocomplete>
```

**Comment by omeid** [comment]
+1 

md-items is expected to work like ngRepeat.

**Comment by ndkcha** [comment]
Is it working ?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (510/500 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:31347)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avsc2-000L0B-8u
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:38 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=EvHPYaVPJju9Lwoh4g30rroThAI=; b=YPWW5bIIUE8t2kQK
	82KFMKuWJ9A49IK1VK11FsFc5yEBO6u5K4E3WptLtExk6Av3YB2+c9b3i5gy8tZU
	qXhAayLyDTbD84xdDDA99m8+N/K6pP+/CNy8cwLR5q27Pc2ZLgllVy2xZgTB1GHz
	K1DOUx6DilQcGC6/9mqlSOXWgEw=
Received: by filter0473p1mdw1.sendgrid.net with SMTP id filter0473p1mdw1.20730.572273493
        2016-04-28 20:32:09.043269176 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id K391rhpkTeSnCGY9Cf-EyQ
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:09.299 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:09 -0700
