### ISSUE TITLE
Publish tagged npm packages for RCs

### ISSUE THREAD

**Issue by jonrimmer** [angular/material#6026]
Not putting the RCs into npm is a pain. I understand the desire is not to push potentially breaking changes to npm users, but this is exactly the problem [distribution tags](https://docs.npmjs.com/cli/dist-tag) are intended to solve.

By default, npm packages use the "latest" tag. By publishing under a different tag, such as "rc", you can allow users to install and depend on these packages, while protecting users who only want stable releases.

**Comment by jonrimmer** [comment]
@ThomasBurleson Why? Closing this issue without even providing an explanation is pretty rude.

**Comment by eXaminator** [comment]
I'm with @jonrimmer here. Semver takes care of stability issues. Just publish it with the correct prerelease version and people won't get the version unless they explicitly request it.

**Comment by kpgarrod** [comment]
I would also find this useful.

**Comment by pfinkbeiner** [comment]
+1

**Comment by antinescience** [comment]
With @jonrimmer here, I understand y'all are busy but closing w/o an explanation as to why the RCs aren't on npm when a good portion of folks use it for front-end package management is pretty cold.

**Comment by antinescience** [comment]
...okay my comment was kind of poor timing. Grats on 1.0!
