### ISSUE TITLE
custom dialog targetEvent

### ISSUE THREAD

**Issue by AliPoder** [angular/material#6027]
with the latest commits custom mdDialogs not opening from targetEvent. you can check it from demos.

**Comment by andrew-cunliffe** [comment]
:+1:

**Comment by AlphaWong** [comment]
The pop-up Custom dialog target is missing since 1.0 rc-5

**Comment by bastianwegge** [comment]
This is due to `ng-cloak` on the example dialog. Remove it and you're fine.
This issue can be closed.
