### ISSUE TITLE
md-text-float with placeholder

### ISSUE THREAD

**Issue by kimsrung** [angular/material#603]
I wonder whether md-text-float could play along with hint. Can anyone answer this question? There should be a way to provide hint with md-text-float.

**Comment by CxRes** [comment]
@ThomasBurleson - How would you propose that one deals with the situation where both a label and a hint (placeholder attribute) may be desired in `<input>` & `<textarea>`. (It seems unspecified in Material Design spec.)

Please correct me if I am wrong, but wouldn't it be more intuitive to have:
Initially: 
*LABEL* - *Hint* 

which on click becomes:
LABEL
*Hint*

which on becoming dirty becomes:
LABEL
user text
