### ISSUE TITLE
md-card img stretched

### ISSUE THREAD

**Issue by emps** [angular/material#6031]
img - Image for the card

gets stretched with the size of the window

**Comment by kunKun-tx** [comment]
put it inside   `md-card-content` if you don't want it to be responsive.

**Comment by EladBezalel** [comment]
@kunKun-tx  :+1:

**Comment by emps** [comment]
ye ok thanks did that

**Comment by dohomi** [comment]
Wrapping the ```md-card-content```adds padding which results in unwanted behaviour. Actually its just important to wrap it into any ```:not(md-card-content)```:
```
<md-card>
<md-title>
(....)
</md-title>
<div>
<img class="md-card-image" src="...">
</div>

</md-card>
```

If the md-card-image is not the first content element it shouldn't add rounded border. This should get included into the core css

Cheers
