### ISSUE TITLE
[md-select][1.0.0-rc5]Cannot set property 'isOpen' of undefined

### ISSUE THREAD

**Issue by gitawego** [angular/material#6033]
md-select throws error ``Cannot set property 'isOpen' of undefined`` around method
```
 function openSelect(e) {
        selectScope.isOpen = true;
        element.attr('aria-expanded', 'true');

        $mdSelect.show({

```

when set 

```
$compileProvider.debugInfoEnabled(false);
```
for production.

the element.scope warning appeared as well:

    element.scope() is not available when 'debug mode' == false. 
    @see https://docs.angularjs.org/guide/production!

**Comment by fjoubert** [comment]
I am experiencing the same issue with rc5 and rc6. Opening the console and executing angular.reloadWithDebugInfo() makes the md-select work as expected.

**Comment by vlopez5** [comment]
Here is a demo of this bug in action:

http://codepen.io/anon/pen/bEGBjj?editors=001

**Comment by salalaslam** [comment]
+1

**Comment by erween** [comment]
+1

**Comment by myagoo** [comment]
Made a pull request here : https://github.com/angular/material/pull/6156

**Comment by lmignot** [comment]
+1
