### ISSUE TITLE
Issue md-datepicker format

### ISSUE THREAD

**Issue by souchea** [angular/material#6035]
I encountered a problem with the md-datepicker’s format.
I work in French and the date's format is 'DD/MM/YYYY'.

When the datepicker is initialized, or when i select a date in the calendar, the format used is DD/MM/YYYY.

![md-datepicker-click-calendar](https://cloud.githubusercontent.com/assets/2019385/11536827/7514fda6-991a-11e5-84d0-e40dda2bd41a.jpg)

But when i write the date in the input, the format changes and becomes MM/DD/YYYY.

![md-datepicker-write1](https://cloud.githubusercontent.com/assets/2019385/11536834/80ac3ae4-991a-11e5-8f02-c7b122de1208.JPG)
![md-datepicker-write2](https://cloud.githubusercontent.com/assets/2019385/11536837/82d92520-991a-11e5-8f85-7793022a5785.JPG)

I reproduced this issue on the site’s demo: https://material.angularjs.org/latest/demo/datepicker

**Comment by mostafaSherif** [comment]
please try this
```
angular.module('app').config(function($mdDateLocaleProvider) {
    $mdDateLocaleProvider.formatDate = function(date) {
       return moment(date).format("DD/MM/YYYY");
    };
});
```

**Comment by jelbourn** [comment]
@souchea The internationalization of the datepicker is done through `$mdDateLocaleProvider`. Please see the [documentation](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider).

**Comment by talatbaig** [comment]
setting the formatDate causes issues with having a default date of null (so that the palceholder shows) and with clearing the date

**Comment by jelbourn** [comment]
@talatbaig if you're running into a bug, please file a new issue with more details.

**Comment by hamboldt** [comment]
I'm on the same problem using datepicker on the brazilian format. @mostafaSherif this code doesn't work when you have to type the date. My birthday is 04/05/1995 (dd-mm-yyyy). When I type it on the datepicker it comes for me as April 5, 1995, But if i choose my birthday in the picker the format comes 04/05/1995 (dd-mm-yyyy) after the selection.

**Comment by vecernik87** [comment]
I know issue is closed but people still find it via google. I encountered this recently and solved it by using both formatDate (for displaying) and parseDate (for manual typing)
```
    $mdDateLocaleProvider.formatDate = function(date){
        var m = moment(date);
        return m.isValid() ? m.format('DD-MM-YYYY') : '';
    };
    $mdDateLocaleProvider.parseDate = function(dateString){
        var m = moment(dateString, 'DD-MM-YYYY', true);
        return m.isValid() ? m.toDate() : new Date(NaN);
    };
```
