### ISSUE TITLE
[0.11.4] Scrollbar problem

### ISSUE THREAD

**Issue by hewaroth** [angular/material#6038]
Hi,

after update Chrome to new release (47), my website has problems.
If "md-sidenav" has scrollbar, then content move to left, and add blank space on right side.
Like on the image.

![-2 xora czytnik](https://cloud.githubusercontent.com/assets/15063045/11539900/d3425d7e-9929-11e5-947f-7903fe6ab6fb.png)

Anyone know why? :-)
Here is my code:

```
<div layout="row" flex>
    <md-sidenav layout="column" class="md-sidenav-left md-whiteframe-z2" md-component-id="left" md-is-locked-open="$mdMedia('gt-md')">
        <md-menu-item ng-repeat="item in items">
            <md-button ng-click="goTo(item.id)">
                <md-icon md-svg-icon="" aria-label=""></md-icon>
                <span md-menu-align-target>{{item.title}}</span>
            </md-button>
        </md-menu-item>
    </md-sidenav>
    <div layout="column" flex>
        <md-toolbar class="md-whiteframe-z2">
            <div class="md-toolbar-tools">
                <h2>Subpage</h2>
            </div>
        </md-toolbar>
        <md-content id="page-content" layout-padding flex>
            <div class="ng-cloak" ng-view></div>
        </md-content>
    </div>
</div>
```

Regards,
Rafał

**Comment by mieczyk1918** [comment]
Cześć Rafał. Mam pytanie do Ciebie. Niezwiązane z tym wątkiem. Mianowicie dotyczy tego:
https://forum.home.pl/threads/php-integracja-z-przelewy24-pl.596/

W jaki sposób wysłać formularz i odebrać token i dalej wysłać go do Przelewy24?
Nie opisałeś procesu startowego w tym przykładzie. Chodzi createtoken().
Gdzie użyć tego createtoken()? W formularzu wysyłającym? W którym miejscu?

Przepraszam, że tutaj odpisuję, ale nie mogę zarejestrować na forum home.pl, bo nie posiadam u nich usług. Z góry dzięki za odpowiedź.

**Comment by hewaroth** [comment]
Cześć. Ale tam jest opisany proces od samego początku przecież :-)

W pliku [b]payments.php[/b] wstawiasz kod, który jest zawarty na forum.home.pl (nawet w kodzie masz dokładnie opisane jaka wartość, w które miejsce).

Robisz sobie formularz w pliku np. [b]form.php[/b], a jego wysyłkę kierujesz na [b]payments.php[/b], i w odpowiednich miejscach podpinasz dane z POST i tyle :-)

**Comment by mieczyk1918** [comment]
Hmm, no to mi coś nie lata. Bo staje na payment.php i biały ekran ;)
Mimo, że skonfigurowałem wszystko, formularz też na pewno dobrze działa.

**Comment by hewaroth** [comment]
Aktywowałeś konto "sandbox" w Przelewy24? Sprawdzałeś zwracane kody błędów?
Klasa jest na pewno poprawna, bo była testowana przez chłopaków z forum.home.pl ;-)

**Comment by mieczyk1918** [comment]
Obecnie pracuję w trybie secure i przelewam drobne sumy, aby sprawdzić finalnie czy wszystko śmiga.

**Comment by hewaroth** [comment]
Sprawdzałeś w panelu Przelewy24, czy jest wysyłana odpowiedź do Twojego sklepu/serwisu? Czy jest poprawnie weryfikowana? Rozumiem, że przekierowanie na stronę płatności działa, a masz tylko problem ze "zwrotką"?

**Comment by mieczyk1918** [comment]
Ogólnie, nie biorąc pod uwagi Twojego API, tylko moje rozwiązanie, to płatności działają, ale nie weryfikują (ten ostateczny etap). W związku z czym płatności nie są finalizowane. Mam też problem z odebraniem tokena i przesłaniu ponownym formularza z tokenem, dlatego korzystam z trnDirect. Szukałem rozwiązania i trafiłem na Twoje API i na nim chce zbudować całość. Tyle, że tutaj mi nic nie hula ;)

**Comment by hewaroth** [comment]
Nie możesz łączyć dwóch rozwiązań. Albo w całości moje, albo w całości własne (kwestia przekazywanych danych w tokenie) :-)

Musisz pamiętać o najważniejszych sprawach:
1) serwis WWW musi być na serwerze produkcyjnym (localhosty nie działają),
2) **$p24_url_return** - to adres do przekierowania użytkownika po płatności, **$p24_url_status** - to adres do wysłania informacji o statusie płatności (mogę być oczywiście te same, ale również na serwerze produkcyjnym),
3) kwota musi być pomnożona x100 (inaczej wygeneruje błąd),
4) sprawdź, czy na serze działa Ci CURL,
5) trzeba pamiętać, że jest inne MERCHANT_ID i CRC na "sandbox" i "secure".

Jeżeli to wypełniłeś poprawnie:
```
$redirect = $oPrzelewy24_API->Pay('Tutaj wstaw kwotę do zapłaty', 'Tutaj wstaw tytuł płatności', 'Tutaj adres e-mail osoby płacącej', $p24_url_return, $p24_url_status);
```
i nie zrobiłeś błędu w innym miejscu, to musi działać - nie ma innej opcji - bo u innych i u mnie działa, a już sporo osób do mnie w tej sprawie pisało :-)

No i zawsze możesz sprawdzić (jeżeli w ogóle występuje jakieś błąd w kodzie), jakie logi błędów generuje Ci apache.

**Comment by mieczyk1918** [comment]
" Rozumiem, że przekierowanie na stronę płatności działa"
No właśnie nie działa. jak dałem:

<form action="payments.php" method="post"> ...

to otwiera payments.php i biały ekran, wszystko stoi

**Comment by hewaroth** [comment]
Sprawdź logi błędów apache.

**Comment by mieczyk1918** [comment]
Hmm, nic ciekawego ta nie ma co by tego dotyczyło.

**Comment by mieczyk1918** [comment]
Dobra, coś znalazłem:
PHP Parse error:  syntax error, unexpected '}' in - w pliku payments.php
więc czegoś za dużo ;) zaraz przejrzę

**Comment by hewaroth** [comment]
Zrób sobie wszystko na "sucho". Plik **Przelewy24_API.php** i wklej do niego kod ze strony, podmieniając dokładnie dane na swoje.

Później plik **payments.php** i to samo. Nic nie zmieniaj, oprócz oczywiście poniższego:
```
$oPrzelewy24_API->Pay('Tutaj wstaw kwotę do zapłaty', 'Tutaj wstaw tytuł płatności', 'Tutaj adres e-mail osoby płacącej', $p24_url_return, $p24_url_status);
```
i linków zwrotnych.

Odpal /payments.php.

**Comment by hewaroth** [comment]
No widzisz, to zasadniczy błąd w kodzie ;-)

**Comment by mieczyk1918** [comment]
Ok, mam kolejny błąd:
PHP Notice:  Undefined index: error in Przelewy24_API.php linia 73

tj 
            return ($output['error'] == '0') ? true : false;

**Comment by hewaroth** [comment]
Tak jak pisałem na stronie forum. Trzeba sobie samemu sprawdzać, co zwraca API Przelewy24 i zrobić swojego "ifa". Sprawdź, co Ci zwraca **$output** i dostosuj.

**Comment by mieczyk1918** [comment]
Na sucho poszło, przekierowało, oczywiście błąd sesji, itd (wiadomo). Dobra, zabieram się jeszcze raz od początku.

**Comment by mieczyk1918** [comment]
Dobra, chyba coś wywęszyłem. W API jest generator:

$p24_session_id = uniqid();

Ale ja także to generuję w formularzu - te dwie wartości są inne, więc może w tym problem? Czy może API wymusza swoją sesję i ją podmienia?

**Comment by hewaroth** [comment]
Tak, to zdecydowanie problem, dlatego, że wtedy suma **md5()** się nie zgadza, jeżeli wartości są inne. Otrzymasz komunikat na stronie Przelewy24 o błędzie sesji (lub podobny).

**Comment by mieczyk1918** [comment]
Jeśli u siebie w formularzu skasuję 2 wartości:
p24_session_id
p24_sign

to dalej przechodzi na stronę P24, jednak z błędem - błąd sesji

**Comment by hewaroth** [comment]
W swoim formularzu masz tylko mieć dwa pola **adres e-mail** i **kwota**. Nic więcej. Jego kierujesz na skrypt, tam pobierasz dane z _POST i śmiga.

**Comment by mieczyk1918** [comment]
Zostawiając tylko 2 pola, i tak mam błąd identyfikatora sesji na P24.

form action="payments.php" method="post"> 
  input type="hidden" name="p24_amount" value="'.$kwotadozaplaty.'" /> 
  input type="hidden" name="p24_email" value="'.$email.'" />   
  input name="submit_send" value="Zapłać" type="submit"  /> 
/form

**Comment by hewaroth** [comment]
Nadal tryb secure?

**Comment by mieczyk1918** [comment]
Tak.

**Comment by mieczyk1918** [comment]
W trybie sandbox to samo. Błąd id sesji w P24.

**Comment by hewaroth** [comment]
Przy zwrocie, czy przy generowaniu transakcji?

**Comment by hewaroth** [comment]
Ustaw **$p24_url_return** na adres, gdzie zostanie przekierowany użytkownik po transakcji (np. strona z podziękowaniem), natomiast **$p24_url_status** na plik **payments.php** - czyli ten z weryfikacją płatności. I zobacz sobie w panelu, czy transakcja jest odhaczona na zielono ;-)

**Comment by mieczyk1918** [comment]
Przy generowaniu. Zatem nawet nie da się zacząć procedury zakupu z 2 polami ;)

**Comment by hewaroth** [comment]
Jeżeli przy generowaniu, to secure nie zgadza się z podanymi przez Ciebie MERCHANT_ID i CRC.

**Comment by mieczyk1918** [comment]
10 razy sprawdzałem teraz ;) Na 100% wszystko jest w porządku.
Nie ingerowałem w kod (oprócz ustawień w API na moje). Tylko formularz przesyłam jak wyżej.

**Comment by mieczyk1918** [comment]
Jak przerzuca do https://secure.przelewy24.pl/trnRequest/0 (powinno być 0?) to jest:

"Błąd wywołania strony:
Nieprawidłowy identyfikator sesji (numer sesji)
Skontaktuj się z obsługą sklepu i zgłoś powyższe błędy."

**Comment by hewaroth** [comment]
Sprawdź sobie, czy Ci dokonuje płatności:
http://64s.pl/a/after.php

Ustawiłem sandbox jak widać, więc możesz "płacić" śmiało ;-)

**Comment by hewaroth** [comment]
Sprawdź sobie, czy Ci dokonuje płatności:
http://64s.pl/a/form.php

Ustawiłem sandbox jak widać, więc możesz "płacić" śmiało ;-)

**Comment by mieczyk1918** [comment]
Wyświetla się tylko OK.

**Comment by hewaroth** [comment]
Zły link, poprawiłem ;-)

**Comment by mieczyk1918** [comment]
No działa.. Hm.. Nie rozumiem o co tutaj chodzi.

**Comment by hewaroth** [comment]
Prześlę Ci te pliki, które tam wrzuciłem testowo. Wrzucę zaraz i sobie pobierzesz.

**Comment by mieczyk1918** [comment]
Super! Dzięki! :)

**Comment by hewaroth** [comment]
Proszę:
64s.pl/aaa.zip

Oczywiście nie ma żadnej walidacji danych, sprawdzania poprawności wprowadzonych przez usera danych, bo robiłem to na szybko, żebyś sobie tylko zobaczył, jak to ma wyglądać.

**Comment by hewaroth** [comment]
No i klasę i payments zrobiłem na jednym pliku, bo mi się nie chciało dwóch :-P
Ale to sobie rozdziel i zrób include ;-)

**Comment by mieczyk1918** [comment]
Nie hula. Wrzuciłem na swój serwer te pliki i tylko poprawiłem moje identyfikatory. Dalej to samo. Nie kumam.

**Comment by hewaroth** [comment]
A z moimi identyfikatorami działa?

**Comment by hewaroth** [comment]
To są testowe, sandbox, więc możesz wykorzystać i sprawdzić.

**Comment by mieczyk1918** [comment]
Sekunda, sprawdzę na innych kontach jeszcze - mimo, że jesteśmy w połowie drogi, to i tak serdeczne z góry dzięki za pomoc :)

**Comment by mieczyk1918** [comment]
Dalej to samo, absurd jakiś ;) Może to kwestia ustawień php? Tryb secure? Coś w ten deseń szukać?

**Comment by hewaroth** [comment]
Nie, nie, nie. Secure, a sandbox, to po prostu różnica w linku, który kieruje do Przelewy24. W przypadku filnalnej wersji, ustawiasz "secure" i podajesz dane, które masz w http://secure.przelewy24.pl/panel a gdy testujesz, ustawiasz "sandbox" i podajesz dane, które masz w http://sandbox.przelewy24.pl/panel - więc to z PHP nie ma nic wspólnego ;-)

**Comment by mieczyk1918** [comment]
Ale mam na myśli tryb SAFE w PHP (Secure)

**Comment by hewaroth** [comment]
Możesz spróbować zrobić wszystko na formularzu (p24_merchant_id, p24_pos_id, p24_crc itd.) i wysłać go bezpośrednio pod "trnRegister" i zobaczyć, czy dostajesz token. Jeżeli tak, to znaczy, że coś z Twoim cURL jest nie tak.

**Comment by mieczyk1918** [comment]
z Twoimi danymi też nie lata - skrypt w całości odpaliłem.

**Comment by mieczyk1918** [comment]
Tak, token dostaje, to już sprawdzałem wcześniej.

**Comment by mieczyk1918** [comment]
takie cos przychodzi bodajze error=0&token=xxxxxxxxxxxxxxxxx

**Comment by hewaroth** [comment]
To jest zwrotka z funkcji "Verify"?

**Comment by hewaroth** [comment]
Przepraszam, "CreateToken"?

**Comment by mieczyk1918** [comment]
Pytałeś o to:
"Możesz spróbować zrobić wszystko na formularzu (p24_merchant_id, p24_pos_id, p24_crc itd.) i wysłać go bezpośrednio pod "trnRegister" i zobaczyć, czy dostajesz token. Jeżeli tak, to znaczy, że coś z Twoim cURL jest nie tak."

Dokładnie tak robiłem wcześniej, bez API i dostałem z ich strony tylko biały ekran z tokenem.

**Comment by hewaroth** [comment]
No to w takim razie problemy z cURL na Twoim serwerze. Widocznie nie przekazuje POST. Gdzie masz serwer?

**Comment by mieczyk1918** [comment]
Dedykowany. Firmowy.

**Comment by mieczyk1918** [comment]
Jeśli wiesz co można poprawić/sprawdzić, to przekażę adminowi - od ręki robi.

**Comment by hewaroth** [comment]
Nie mam pojęcia jakie trzeba zmiany w cURL wprowadzić, bo kwestie administracyjne serwerów, to niestety nie moja działka. Ale przynajmniej wiesz, gdzie masz szukać problemów, bo sam skrypt działa ;-)

**Comment by mieczyk1918** [comment]
Gdyby dali normalnie drugi parametr (jeden, gdy transakcja ok i drugi gdy blad) to nie bylo problemu. Bo mialem cale skrypty, wszystko pieknie dzialalo... ale jak ktos kliknal anuluj to przechodzilo do akceptacji platnosci po mojej stronie i aktywowalo usluge... bo nie polasili, zeby sie zrobi drugi url w przypadku anulowania...

**Comment by mieczyk1918** [comment]
No i niestety jak się nie uda tego rozwiązać, to będę musiał skorzystać z dynamicznie generowanych linków, ale bez automatycznego aktywowania uslugi (w przypadku klikniecia anuluj) tylko reczne aktywowanie na podstawie zaksiegowania (maila) od P24.

**Comment by mieczyk1918** [comment]
W każdym bądź razie dzięki za pomoc. Jak się uda to odpalić z Twoim API, to się odezwę w sprawie "donacji" projektu :)

**Comment by mieczyk1918** [comment]
Teraz zabieram się za cURLa

**Comment by hewaroth** [comment]
Bo akurat faktem jest, że API systemu Przelewy24, to chodzący dramat. Tego się nawet nie powinno produkcyjnie wypuszczać.

Jaką masz wersję PHP? cURL jest doinstalowany? Ale zapewne jest, bo skoro masz tylko błąd sesji, więc "jakiegoś" POSTa tam wysyła.

**Comment by mieczyk1918** [comment]
Current PHP version: 5.3.3

**Comment by hewaroth** [comment]
A spróbuj z najprostszym POSTem w cURL. Czyli w "CreateToken", zamień:
```
$oCURL = curl_init();
            curl_setopt($oCURL, CURLOPT_POST, 1);
            curl_setopt($oCURL, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
            curl_setopt($oCURL, CURLOPT_POSTFIELDS, implode('&', $headers));
            curl_setopt($oCURL, CURLOPT_URL, 'https://' . PRZELEWY24_TYPE . '.przelewy24.pl/trnRegister');
            curl_setopt($oCURL, CURLOPT_SSL_VERIFYHOST, 2);
            curl_setopt($oCURL, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)');
            curl_setopt($oCURL, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($oCURL, CURLOPT_SSL_VERIFYPEER, false);
            $response = curl_exec($oCURL);
            curl_close($oCURL);
```
na:
```
$oCURL = curl_init();
            curl_setopt($oCURL, CURLOPT_POST, 1);
            curl_setopt($oCURL, CURLOPT_POSTFIELDS, implode('&', $headers));
            curl_setopt($oCURL, CURLOPT_URL, 'https://' . PRZELEWY24_TYPE . '.przelewy24.pl/trnRegister');
            curl_setopt($oCURL, CURLOPT_RETURNTRANSFER, 1);
            $response = curl_exec($oCURL);
            curl_close($oCURL);
```

**Comment by mieczyk1918** [comment]
Poszło!:)

**Comment by hewaroth** [comment]
No to jeszcze w funkcji "Verify" zamień:
```
$oCURL = curl_init();
            curl_setopt($oCURL, CURLOPT_POST, 1);
            curl_setopt($oCURL, CURLOPT_SSL_CIPHER_LIST, 'TLSv1');
            curl_setopt($oCURL, CURLOPT_POSTFIELDS, implode('&', $headers));
            curl_setopt($oCURL, CURLOPT_URL, 'https://' . PRZELEWY24_TYPE . '.przelewy24.pl/trnVerify');
            curl_setopt($oCURL, CURLOPT_SSL_VERIFYHOST, 2);
            curl_setopt($oCURL, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 5.01; Windows NT 5.0)');
            curl_setopt($oCURL, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($oCURL, CURLOPT_SSL_VERIFYPEER, false);
            $response = curl_exec($oCURL);
            curl_close($oCURL);
```
na:
```
$oCURL = curl_init();
            curl_setopt($oCURL, CURLOPT_POST, 1);
            curl_setopt($oCURL, CURLOPT_POSTFIELDS, implode('&', $headers));
            curl_setopt($oCURL, CURLOPT_URL, 'https://' . PRZELEWY24_TYPE . '.przelewy24.pl/trnVerify');
            curl_setopt($oCURL, CURLOPT_RETURNTRANSFER, 1);
            $response = curl_exec($oCURL);
            curl_close($oCURL);
```

i powinno hulać ;-)

**Comment by mieczyk1918** [comment]
W zasadzie działa, ale nie wykonuje operacji wskazanych po poprawnej weryfikacji (aktywacji usług)

**Comment by hewaroth** [comment]
Ale ten warunek jest spełniony?
```
    if ($oPrzelewy24_API->Verify($_POST) === true) {
            // Tutaj dokonujemy aktywacji usługi, która jest opłacana
    }
```

**Comment by mieczyk1918** [comment]
Po wykonaniu transakcji w trybie secure kwota widniejie jako niezweryfikowana w panelu P24

**Comment by hewaroth** [comment]
Robisz to na plikach, które Ci przesłałem?

**Comment by mieczyk1918** [comment]
Tak, ale już rozwiniętych o inne $_POSTy i te poprawki co dałeś.

**Comment by hewaroth** [comment]
Najlepiej pokaż kod, bo tak "na sucho", ciężko stwierdzić w czym problem ;-)

**Comment by mieczyk1918** [comment]
Dobra, w zasadzie działa wszystko, oprócz tego:
if ($oPrzelewy24_API->Verify($_POST) === true) { tutaj unlock zamowienia }
mimo, ze zlecenie jest zweryfikowane i w P24 mam jako oplacone

**Comment by hewaroth** [comment]
A co Ci zwraca $output w funkcji Verify?

**Comment by mieczyk1918** [comment]
w którym miejscu postawić echo $output, żeby wyświetlił w odpowiednim momencie?

**Comment by hewaroth** [comment]
```
parse_str($response, $output);
var_dump($output);
return ($output['error'] == '0') ? true : false;
```

**Comment by mieczyk1918** [comment]
hm, przelatuje wszystko i tego nie widać

**Comment by hewaroth** [comment]
To zamiast: 
```
var_dump($output); exit;
```
daj:
```
file_put_contents('a.txt', $output);
```
i pokaż zawartość a.txt

**Comment by mieczyk1918** [comment]
0

**Comment by hewaroth** [comment]
A np.:
```
file_put_contents('b.txt', json_encode($output));
```
co zwraca w pliku b.txt? Masz jakąś dziwę konfigurację serwera i trzeba próbować.

**Comment by mieczyk1918** [comment]
{"error":"0"}

**Comment by hewaroth** [comment]
Eee... no to funkcja Verify Ci poprawnie zwraca "true", ja myślałem, że z nią masz błąd.
No to błąd już jest po stronie kodu, którym robisz odblokowanie usługi.

**Comment by mieczyk1918** [comment]
No chyba nie. Dodałem tam prosty kod także:
Niestety, wszystko co jest tutaj w klamrze jest pomijane
if ($oPrzelewy24_API->Verify($_POST) === true) { file_put_contents('c.txt', 'udalo sie'); }

**Comment by hewaroth** [comment]
Jeżeli faktycznie w pliku b.txt miałeś:
```
{"error":"0"}
```
to znaczy, że **$output** zwróciła Ci:
```php
array('error' => '0');
```
czyli warunek na dole **Verify** jest spełniony:
```php
return ($output['error'] == '0') ? true : false;
```
Pokaż cały kod :-)

**Comment by mieczyk1918** [comment]
Co ciekawe, po dokonanej transakcji w trybie secure, nie przychodzi żadne potwierdzenie na maila od P24

**Comment by hewaroth** [comment]
A masz je włączone w panelu? Żebyś je otrzymywał i Ty i klient?

**Comment by mieczyk1918** [comment]
ok, przyszło powiadomienie od P24
o treści:

Z naszych rejestrów wynika, iż proces dokonywania transakcji nie został poprawnie zakończony.

W obecnej sytuacji, aby przekazać należność na Państwa konto, należy wykonać jedną z poniższych czynności:

- aktywować transakcję poprzez Panel administracyjny
- poprosić klienta o powtórzenie zakupu
- zgłosić się do obsługi serwisu Przelewy24 podając odpowiedni numer transakcji

**Comment by mieczyk1918** [comment]
mniejsza z tym, ale dalej nie przerabia nic z klamry w weryfikacji, caly kod przejrzalem, nic nie zmienialem

**Comment by hewaroth** [comment]
Podsumujmy... kod Ci działa, bo do transakcji dochodzi, ale w panelu P24, masz transakcję na zielono, czy na niebiesko?

**Comment by mieczyk1918** [comment]
teraz już na zielono, to jakieś stare powiadomienie przyszło, akurat jak nadałem pierwsze w trybie secure i zrobiło zamęt, bo nie zwróciłem na ID transakcji

**Comment by mieczyk1918** [comment]
takze wszystko jest w porzadku, oprocz wykonywania kodu z weryfikacji

**Comment by mieczyk1918** [comment]
zupelnie nic nie dziala, obojetnie co tam wpisze, czy to akcja na mysql, czy na plikach, nic a nic

**Comment by hewaroth** [comment]
Wejdź sobie jeszcze raz na:
http://64s.pl/a/form.php

Tam w klamrze dałem prostą funkcję **mail**, jeżeli transakcja się dokona, dostaniesz maila na podany adres. Wybierz jakąkolwiek opcję platności i zatwierdź.

**Comment by mieczyk1918** [comment]
Ja pierniczę, absurd jakiś. Także dodałem sobie funkcję mail w weryfikacji, i po dokonaniu platnosci działa tylko ona w tej klamrze, bo, żadne zmienne do innych poleceń nie działają (sprawdzalem je zarowno poprzez mysql_query jak i operacje na plikach

**Comment by mieczyk1918** [comment]
qrde, ale skladnia, tak to jest jak sie pisze, wiszac na tel :)

**Comment by hewaroth** [comment]
Żadne inne zmienne do weryfikacji transakcji nie działają, bo zapewne źle je przekazujesz ;-)
Musisz to robić _GETem na adres zwrotny statusu, czyli:
```
$p24_url_status = 'http://twoja-strona.com/payments.php?id_uslugi=1234567';
```
a odbierasz je:
```php
if ($oPrzelewy24_API->Verify($_POST) === true) {
    $costam->AktywujUsluge($_GET['id_uslugi']);
}
```
Nie ma opcji, musi działać ;-)

**Comment by mieczyk1918** [comment]
ale adresem zwrotnym mogę to aktywować, owszem, tyle, ze adres zwrotny tez zaskoczy jak Klient zrezygnuje z platnosci albo jest jakies niepowodzenie

**Comment by mieczyk1918** [comment]
cala sztuka, ze ja to wlasnie adresami zwrotnymi aktywowalem, ale to nie moze tak dzialac, na wypadek bledow i niepowodzen

**Comment by hewaroth** [comment]
Nie. Ty źle rozumujesz. Nie aktywujesz usługi adresem zwrotnym, tylko przekazujesz w nim ID usługi, która ma być aktywowana po POPRAWNYM dokonaniu płatności. Jeżeli klient anuluje, albo nie będzie płatności, to funkcja  Verify zwróci FALSE i aktywacja się nie powiedzie.

Ale w przypadku poprawnej transakcji, system musi przecież wiedzieć, co aktywować. A się to po ID pobranym z GET. Inaczej zmiennych nie jesteś w stanie przekazać, jak właśnie GETem na adres zwrotny statusu (nie adres zwrotny główny).

**Comment by mieczyk1918** [comment]
"$p24_url_status = 'http://twoja-strona.com/payments.php?id_uslugi=1234567';"

Czy w takim razie już samego ID nie powinien przekazać w formularzu?
<form action="payments.php?id_uslugi=1234567" method="post">

**Comment by hewaroth** [comment]
No właśnie, jak POST, to nie GET. Przekazujesz sobie ID w **$p24_url_status**, P24 Ci go pięknie GETem zwraca, Ty sobie usługę w przypadku zaksięgowania wpłaty aktywujesz i każdy szczęśliwy ;-)

**Comment by mieczyk1918** [comment]
Coś tu nie gra, bo nawet dla picu chcę wykonać jedną operację dla wszystkich zleceń (bez pobierania  ID), tj.

if ($oPrzelewy24_API->Verify($_POST) === true) {
mysql_query("UPDATE `zlecenia` SET oplacony = '1'");
}

Nie dzieje się nic.

**Comment by mieczyk1918** [comment]
Naprawdę coś dziwnego się dzieje, bo oprócz funkcji mail() w przypadku "true" nie działa absolutnie nic

**Comment by hewaroth** [comment]
Sprawdź jakie błędy generuje Ci apache, bo widać jak na dłoni, że masz coś źle w kodzie.

**Comment by mieczyk1918** [comment]
Qrwa, konkretna wtopa. Przecież payments.php nie ma zadeklarowanego połączenia z bazą :(
Sorry za zamęt.

**Comment by hewaroth** [comment]
Uduszę, normalnie uduszę ;-))

**Comment by mieczyk1918** [comment]
Działa, wszystko działa. Ja pierniczę. Idę odsypiać! Jesteś mistrzem, że dałeś radę wytrzymać to wszystko. Ale 3 dni nie śpię przez to oryginalne API P24, bo skończyć nie mogłem i kurwica mnie brała, a deadline minął i dzisiaj już ledwo kontaktuję, stąd takie słabe kojarzenie! :)

Donation soon! Za pracę i poświęcenie! A tymczasem mogę spokojnie powiedzieć dobranoc i z uśmiechem na twarzy idę spać, z kilogramem worków pod oczami z niedospania :)

PS Pieprzyć Original P24 API.

**Comment by hewaroth** [comment]
Proszę bardzo ;-) Nie ma problemu - najważniejsze, że wszystko działa. Dla nas Developerów to podstawowa sprawa. Dobranoc, powodzenia i polecam się na przyszłość! :-)

**Comment by mieczyk1918** [comment]
Witam ponownie Przyjacielu,

Ostatnio P24 napisały maila, w którym pisały, że zmienia się ich system i należy przekazać devkom ich informacje - kwestie techniczne. Czy czytałeś może tego maila od nich? Czy Twoje API wymaga zmian, aby działało poprawnie po ich modernizacji?

PS Rozliczenie projektu mam jeszcze w tym roku (te terminowe faktury...) - wrócimy tym samym do kwestii finansowej za okazaną pomoc i wsparcie dla dobrych projektów, jakim jest Twoje API.
