### ISSUE TITLE
default md-toolbar-tools styling for md-toolbar and/or its children

### ISSUE THREAD

**Issue by wcjr** [angular/material#6045]
I'm requesting `md-toolbar-tools` be automatically added to `md-toolbar` by default.  I've never seen an example where it wasn't added to the children of that directive, it would be nice to expect it and override it if necessary.

**Comment by topherfangio** [comment]
At this point, I think we are pretty much set in how this component is used since we have already released 1.0, however, we will definitely consider this for the 2.0 release.

**Comment by wcjr** [comment]
ok, thanks for the consideration.

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (526/500 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:25906)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avscA-000L55-ER
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:46 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=lkjOm1fXVbAJgiRoG9P3HjbkCUk=; b=nlKv7QUAigmqqpyu
	oII04MIpmguceQIuQBjWYd1LpViYXBebZ2nGub8NhZtdRLHWOQdK1HWiwlpra0+a
	+LTcdkG/T8JdhAIyv+mAPmz7cblumM+cr3EII4AB+1U2zmGld/502TxUxIeo18WR
	G4WDpKzy/ixYPZU+z7Fy0cQNoAk=
Received: by filter0644p1mdw1.sendgrid.net with SMTP id filter0644p1mdw1.27695.5722735252
        2016-04-28 20:32:18.415852776 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id rNFhXTpbRfSSUjeX9ujDdQ
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:18.487 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:18 -0700
