### ISSUE TITLE
Non-dynamic-height tabs inside a dynamic-height-tab styling

### ISSUE THREAD

**Issue by STOpandthink** [angular/material#6046]
If you put a non-dynamic-height tab inside a dynamic-height-tab, it'll have the md-dynamic-height CSS class applied to it, because it's technically under a .md-dynamic-height. Hope this makes sense, if not, I can build an example.  
Believe it or not this is actually an issue for my app.

**Comment by ThomasBurleson** [comment]
Will not fix.
