### ISSUE TITLE
IE11 - Menu Demo - Extra Scrollbar on wide screen - HEAD(MASTER) plus recent versions

### ISSUE THREAD

**Issue by ptrenery** [angular/material#6047]
On the demo site, the problem shows in IE11 on the menu demo for multiple recent versions including HEAD.

On a narrow screen, opening the menu does not create an extra scrollbar. See below.

![image](https://cloud.githubusercontent.com/assets/5481066/11551517/db4b73d4-992e-11e5-9ffd-c8f95c7e115b.png)

On a wider screen, an extra toolbar appears on the right when the menu is open. See below.

![image](https://cloud.githubusercontent.com/assets/5481066/11551537/f85e0202-992e-11e5-88fe-c7266d351bea.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (512/500 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:63056)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avsc5-000L1Y-2q
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:41 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=wyZw6I6bd9rViLLjq0zhhs2yZvA=; b=slB+K0riofgWsy1B
	upzG7XVKO9gkTWNL+DJo/XX3XcRPccaj7Ggff85ZHw9IlNfIfLWmThAtpRTqLidO
	KId8K10efY99iiAZnDWNUVYHR20604zVQBxWuY6USkgZvX6zunspgjmxsbK+NsH8
	LaGqH/dGVotVpBmd8Xs1S5SNP8M=
Received: by filter0446p1mdw1.sendgrid.net with SMTP id filter0446p1mdw1.24563.5722734C19
        2016-04-28 20:32:12.196845048 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id NqsOBqvJROajFF_pNakMUA
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:12.230 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:12 -0700
