### ISSUE TITLE
md-ink-ripple doc typo

### ISSUE THREAD

**Issue by jkiimm** [angular/material#6052]
Document typos([first](https://github.com/angular/material/blob/v1.0.0-rc6/src/core/services/ripple/ripple.js#L22), [second](https://github.com/angular/material/blob/v1.0.0-rc6/src/core/services/ripple/ripple.js#L24)) should be fixed from `md-ripple-ink` to `md-ink-ripple`.

**Comment by EladBezalel** [comment]
A PR is very welcomed, thank you!
