### ISSUE TITLE
Autocomplete Demo - Input field jumps out of viewable range when item is selected (Mobile device)

### ISSUE THREAD

**Issue by runethh** [angular/material#6054]
1. Open the menu
2. Select autocomplete in the demo area
3. Without scrolling - Select the field "What is your favorite US state?"
4. Start typing "Was"
5. Select "Washington" from the list. Observe that the page now moves, and that the field is now hidden below the keyboard.

Tested on:
Model: Iphone 6 (MG4F2QN/A)
Operating system: iOS 9.1 (13B143)
Browser: Safari 9.0 Mobile 

Note that this works well on: 
Model: Nexus 6 (Shamu)
Operating system: Android Lollipop 5.1.1 (LMY47Z)
Browser: Chrome 46.0.2490.76

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
