### ISSUE TITLE
md-prevent-menu-close not working in RC-6

### ISSUE THREAD

**Issue by makkart** [angular/material#6055]
md-prevent-menu-close is working just fine in rc-5, in rc-6 it closes the menu.

Im using checkboxes inside the menu list to let the user choose some options and then click outside to close. md-prevent-menu-close is critical for this to work.

**Comment by craigsnyders** [comment]
+1 I would expect `md-prevent-menu-close` to work on any element.  I encountered the problem with md-checkbox, in v0.11.4

**Comment by maximethebault** [comment]
@craigsnyders md-prevent-menu-close was added in 1.0.0 (around rc2 if I remember well), so it's normal it's not working in 0.11.4
