### ISSUE TITLE
TypeError for empty flex attribute on md-button

### ISSUE THREAD

**Issue by julienpa** [angular/material#6057]
I get this error since updating to **rc6** this morning:
```
TypeError: Cannot read property 'warn' of undefined at validateAttributeUsage
(angular-material.js:3374:15)
[...]
at angular-material.js:1567:20 <md-button flex="" ng-click="switchAction()"
aria-label="Change server" class="md-primary">
```
I guess it is because the `flex` attribute is empty? Is it now required to have a value?

**Comment by julienpa** [comment]
Actually it happens even with a value for the `flex` attribute.
Here is my code:
```jade
md-dialog.about-dialog(aria-label="Dialog with app info")
  md-toolbar
    .md-toolbar-tools
      h2(flex) {{ appData.name }}
      md-button.md-icon-button(ng-click="closeDialog()", aria-label="Close dialog")
        md-icon close
  md-dialog-content.md-padding
    .md-body-2 Version: {{ appData.version }}
    .md-body-2 Release date: {{ appData.releaseDat }}
    // (more info) ...  
    .change-server(layout)
      md-button.md-primary(flex="grow", ng-click="switchAction()", aria-label="Change server")
        translate Change server
```
The error is declared for the last button, in the `.change-server(layout)` wrapper

**Comment by julienpa** [comment]
If found that the error is here:
https://github.com/angular/material/blob/master/src/core/services/layout/layout.js#L364

@ThomasBurleson what could cause `$log` to be undefined? I use this service in my Angular app, but the injections are separate between my app and Angular Material module, right?

**Comment by hoopyfrood** [comment]
+1

**Comment by ethanmick** [comment]
Just ran into this as well. Just upgraded to RC6. Same place as @julienpa. Thanks!

**Comment by ThomasBurleson** [comment]
Fixes are pending with https://github.com/angular/material/pull/6082/

**Comment by ThomasBurleson** [comment]
@julienpa - the `$log` was not being properly injected into `attributeWithoutValue( )`. Yet I am still confused as to why you are getting that error when it only triggers for `<md-button flex>` or `<fieldset flex>`.

**Comment by julienpa** [comment]
@ThomasBurleson actually the issue is not linked with `attributeWithoutValue( )`, I was wrong about the "no value" thing. It's just because I am using a md-button with flex directive, which uses `validateAttributeUsage( )` and this one had the injection problem.
