### ISSUE TITLE
layout-sm is not working on mobile devices 1.0.0-RC6, it was working on 0.11.4

### ISSUE THREAD

**Issue by colbroth** [angular/material#6058]
Issue: The layout-sm does not appear to work on an iphone 5 using Safari, also reproducible using google chrome and setting device mode to any apple phone.
Reproduce:
1. Open Angular Material Demo Input in chrome
     Note: First Name and Last Name is next to each other on the same row
2. Change google chrome to render as a mobile device (or open demo on iphone using safari)
    F12 key->click the icon which looks like a phone->set device to iphone 
    Note: First Name and Last Name is next to each other on the same row
****Expected: First Name and Last Name to be on separate rows, first name on top of last name input
3. Switch angular material to version 0.11.4 and you will see the layout-sm does work properly on mobile devices. It changes to column when the layout is small.

**Comment by mckenzielong** [comment]
:+1: I bumped into this yesterday when I pulled the latest version. See #6056 
The sm breakpoint changed, I had to swap over to xs.
> Added breakpoints: xs, gt-xs, xl per Material Design spec. Breakpoints sm and gt-sm have changed.

**Comment by EladBezalel** [comment]
dup
