### ISSUE TITLE
Content Security Policy error on md-button click since rc6 and/or Chrome 47

### ISSUE THREAD

**Issue by julienpa** [angular/material#6062]
This morning I updated both Angular Material from rc5 to rc6, and Chrome from 46 to 47. Since then, I have the following issue appearing in the console each time I click an md-button:
<img width="769" alt="img-src-error" src="https://cloud.githubusercontent.com/assets/4720300/11573229/54e08960-99ec-11e5-9eb2-885960eab352.png">

### Textual version below
Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAGXRFW…9iZSBJbWFnZVJlYWR5ccllPAAAAA5JREFUeNpiYGBgAAgwAAAEAAGbA+oJAAAAAElFTkSuQmCC' because it violates the following Content Security Policy directive: "default-src *". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.
forEach.prop @ angular.js:3200
JQLite.(anonymous function) @ angular.js:3277
InkRippleCtrl.handleMousedown @ angular-material.js:4017
(anonymous function) @ angular.js:1206
defaultHandlerWrapper @ angular.js:3346
eventHandler @ angular.js:3334

**Comment by robertmesserle** [comment]
@julienpa Can you include your CSP info?

**Comment by julienpa** [comment]
@robertmesserle I'm sorry I didn't update the issue, but it seems to be gone in later releases. I'm currentlye on 1.0.5 and I do not encounter this error anymore.

**Comment by asanin-2sol** [comment]
This is still happening to me and I am using 1.0.5
 
It mostly happens the first time I open any sidenav.

I'm starting to develop a bad habit of ignoring console errors because of these errors being constantly on the console.

**Comment by swardi** [comment]
I am facing the same issue and I am using version 1.1.1 with angular 1.5.8

**Comment by DustinJSilk** [comment]
Same with version 1.1.3 and angular 1.6.2
