### ISSUE TITLE
md-dialog - Unable to select md-menu-item

### ISSUE THREAD

**Issue by gbruins** [angular/material#6068]
Unable to select a menu item when contained inside md-dialog  (Angular Material 1.0.0. RC6)

Codepen:
http://codepen.io/anon/pen/adbOQN

**Comment by PapyElGringo** [comment]
cf #6049

**Comment by ThomasBurleson** [comment]
Fixed.

**Comment by gbruins** [comment]
Awesome thanks Thomas!
