### ISSUE TITLE
Can't use mdToolbar directive with NgUpgrade

### ISSUE THREAD

**Issue by alex94puchades** [angular/material#6069]
NgUpgrade UpgradeAdapter#upgradeNg1Component fails with ```Error: Directive 'mdToolbar' is not a component, it is missing template.``` NgUpgrade throws this error if a component (aka directive) does not have either a 'template' or 'templateUrl' in its DDO. Where is the mdToolbar html coming from then?

Please, if there's anything I can do to get this working, I'd be glad to help

**Comment by EladBezalel** [comment]
Since 1.0 will be released soon, our focus will be on ngMaterial 2 which will be our implementation of the spec for ng2

**Comment by pete-otaqui** [comment]
Shame this wasn't taken more seriously since Angular Material 2 is still so far from complete, even though it's taken Angular 2 a further 9 months to make it to final!

Is there a timeline for delivery of NG Material 2
