### ISSUE TITLE
md-fab-speed-dial: allow for morphing or replacement of trigger image (as shown in spec)

### ISSUE THREAD

**Issue by johnny5dm** [angular/material#6070]
The FAB speed dial's trigger image currently does not change when triggering it, so there's no way to turn it into either another action or a cancel button.  See the [material spec, "speed dial" section](https://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions).

Feature request is to allow for:
- replacing trigger image with "x" or submitted image with click triggering (see [here](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3TmpnUHVKRV9DU0E/components-buttons-fab-transition_speeddial_02.webm))
- replacing trigger image with clickable primary action and submitted image on hover (as with Inbox)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
