### ISSUE TITLE
new in rc6 - md-menu contents crashed in md-toolbar

### ISSUE THREAD

**Issue by alanpurple** [angular/material#6073]
works fine with rc5

**Comment by Mischazz** [comment]
+1

**Comment by ThomasBurleson** [comment]
@alanpurple Where do you see this happening. If not in our online Docs, please provide a CodePen and more details.

**Comment by alanpurple** [comment]
@ThomasBurleson  I'm still working on it, it's hard to get in codepen

**Comment by Mischazz** [comment]
It seems that there is a problem with menu and md-toolbar. I made this fiddle
http://jsfiddle.net/ps25aotj/6/
It´s working with rc5

**Comment by alanpurple** [comment]
@Mischazz  Yes!!! Thank you!!

**Comment by jelbourn** [comment]
#6071 might be related

**Comment by copooper** [comment]
+1

**Comment by beny78** [comment]
+1

**Comment by RolandHeath** [comment]
It seems like the options can still be selected through the keyboard, it's just not responding to mouse events any more. That, and it takes on the text-colour of the parent, so the options appear white - but there's already an issue for that from rc5.
