### ISSUE TITLE
Layout Vertical Panel 100%

### ISSUE THREAD

**Issue by christophechevalier** [angular/material#6074]
Hi everyone.

Here is the description of my problem :

I wish my right panel where my is displayed 100% vertically ,
and my located in the left panel .

I think I have tested all possible classes of the library to solve my problem but I have doubts about the compatibility with Firefox and Chrome browsers.

If you have a moment to look at my code ...

Here are 2 Screenshots of my main window in Firefox and Chrome:

Firefox : 

![firefox_error](https://cloud.githubusercontent.com/assets/7148846/11586791/add07524-9a75-11e5-8ecd-50d5861a0e4e.JPG)

Chrome : 

![chrome_error](https://cloud.githubusercontent.com/assets/7148846/11586797/b6eaff3a-9a75-11e5-8d61-75a50a992dce.JPG)

Here is a link to my Views of my main window :

https://github.com/petalslink/petals-cockpit/tree/master/public/modules/core/views

ps: Sorry for my bad English speaking ! :)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
