### ISSUE TITLE
Three issues with md-menu in 1.0.0-rc6

### ISSUE THREAD

**Issue by jb29** [angular/material#6075]
Since RC6 I've got the following issues with `md-menu`:

1. md-menu-items can't be selected. The menu just closes when I click on them.
2. The menu is displayed behind neighboring md-cards. See this screenshot:
![2015-12-04_10h46_35](https://cloud.githubusercontent.com/assets/13062631/11586847/09a74b84-9a76-11e5-80f5-f24465d2e58c.png)
3. When I set `md-position-mode="target-right target"` the menu is positioned too far to the right. See this screenshot:

![2015-12-04_10h47_44](https://cloud.githubusercontent.com/assets/13062631/11586881/5b448ba0-9a76-11e5-9709-171dfe71a273.png)

FYI, I set `md-menu-origin` on the `more_vert` icon and `md-menu-align-target` on the icons in the md-menu-items.

**Comment by VinceOPS** [comment]
+1 for issue 1 & 2.

Menu items can't really be "clicked" anymore.
And the default CSS changed, also. The default text color turned to white. I'm using the same HTML code than the last example of "position mode demos": https://material.angularjs.org/latest/demo/menu

Thanks!

**Comment by PapyElGringo** [comment]
cf #6049

**Comment by dg1202** [comment]
+1
 Experiencing similar issues

**Comment by ryanespin** [comment]
+1

For the time being, I was able to play with z-index on the parent element to make it work.  Its a workaround until its fixed up.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
