### ISSUE TITLE
1.0.0-rc6 - Still no dialog stacking?

### ISSUE THREAD

**Issue by jaymanned** [angular/material#6076]
I just modified the [dialog demo](http://codepen.io/anon/pen/ZQEpjR) to include an overlapping dialog in the tab dialog. It doesn't work.

Despite some plans I saw announced in issue [2437](https://github.com/angular/material/issues/2437) by @ThomasBurleson, `1.0.0-rc6` still seems to not support dialog stacking.  Are there plans to add this feature shortly?

**Comment by ThomasBurleson** [comment]
@jaymanned - my comment included:

... There are plans (in a **post v1.0** release) to add...

**Comment by jaymanned** [comment]
Hi Thomas. I didn't mean to bother you. It's just that I saw some of the stuff on that post got implemented for rc6. IMMO stacking dialogs is way more important to provide richer and more complete interaction than those other features. Of course it's up to you guys. 

And let me add the work you've guys are doing is priceless. Huge thanks.

**Comment by EladBezalel** [comment]
@jaymanned as always, PRs are very welcome!

**Comment by ThomasBurleson** [comment]
@jaymanned - Thank you. Dialog stacking will be a great enhancement in 2016. ;-)
