### ISSUE TITLE
md-select: impossible to set "multiple" dynamically

### ISSUE THREAD

**Issue by norkunas** [angular/material#6077]
http://codepen.io/norkunas/pen/pgoNZY

**Comment by norkunas** [comment]
oh.. duplicated https://github.com/angular/material/issues/3068

**Comment by norkunas** [comment]
Would somebody reconsider to fix this in v1?

**Comment by mprentic-harris** [comment]
@norkunas you should ask that in #3068 and close this issue since it is a duplicate.
