### ISSUE TITLE
Utilis, scrollTop returns wrong position

### ISSUE THREAD

**Issue by morriq** [angular/material#6078]
Hello,

Try it yourself.

window.scrollTo(0,0);
console.log($mdUtil.scrollTop(document.body)); 

Output is 60. It should be 0, right?

https://github.com/angular/material/blob/master/src/core/util/util.js#L94

replace with:
```javascript
return scrollTop !== undefined ? scrollTop : Math.abs(element[0].getBoundingClientRect().top);
```

**Comment by EladBezalel** [comment]
Can you please provide a codepen? i tried and got 0..

**Comment by morriq** [comment]
Ok, I can't repeat it on codepen either. Sorry

Seems it's kind of magic on my website.
http://screencast.com/t/Fsugxc0P

**Comment by morriq** [comment]
But one moment.  This condition will  execute everytime Math.abs(element[0].getBoundingClientRect().top) for var scrollTop = 0;

**Comment by EladBezalel** [comment]
I'm sorry but i didn't got what you've tried to say..
Without an actual codepen I couldn't help your issue. please do your best to recreate.

**Comment by morriq** [comment]
http://jsfiddle.net/h2r18swL/

**Comment by EladBezalel** [comment]
@morriq Your issue was putting `ng-app` on the container div, you should put it on the body and this will solve it.

**Comment by morriq** [comment]
No. it's not fixing issue.
http://jsfiddle.net/h2r18swL/1/

tested on chrome and firefox

**Comment by EladBezalel** [comment]
your problem is not in mdUtil.scrollTop, if you will inspect your demo elements you will see that the body starts from the margin-top of the content, adding `overflow: hidden` to `#page` solves this.
