### ISSUE TITLE
margin-left of md-icon is not set inside a md-list-item

### ISSUE THREAD

**Issue by sydneyhenrard** [angular/material#6084]
The md-list-item is align to right if the first child is md-icon.

```
  <md-list>
    <md-subheader class="md-no-sticky">margin-left of md-icon is not set</md-subheader>

    <md-list-item>
      <md-icon md-font-icon="ion-home" aria-label="Home"></md-icon>
      <div class="md-list-item-text">
        <span class="md-body-2">Home</span>
      </div>
    </md-list-item>

   <md-subheader class="md-no-sticky">margin-left of md-icon is set when md-2-line</md-subheader>

    <md-list-item class="md-2-line">
      <md-icon md-font-icon="ion-home" aria-label="Home"></md-icon>
      <div class="md-list-item-text">
        <span class="md-body-2">Home</span>
      </div>
    </md-list-item>
    
    </mdlist>
```

See codepen: http://codepen.io/anon/pen/KVKvrZ

This is reproducible with 1.0.0-rc6

**Comment by ThomasBurleson** [comment]
You are using unsupported v0.8.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.
