### ISSUE TITLE
mdMenu does function properly inside an mdSidenav or mdList

### ISSUE THREAD

**Issue by bgoerdt** [angular/material#6089]
In 1.0.0-rc6 the styling and click functionality of the mdMenu component is broken when inside a sidenav or list. The menu is sometimes cut off when it would normally go outside the parent container, and the intended click action does not fire.

Here is a CodePen demonstrating the issues: 
http://codepen.io/bgoerdt/pen/pgoWBm

**Comment by nervestaple** [comment]
+1

Similar problems with mdToolbar.

http://codepen.io/anon/pen/pgodJM

**Comment by cranesandcaff** [comment]
Went back through the versions on bower, this issue starts after `v1.0.0-rc5-master-08b5af5`

**Comment by MilosStanic** [comment]
With 1.0.0-RC4 my menu looks like this
![mdrc5](https://cloud.githubusercontent.com/assets/3983854/11603583/20f2a1f4-9ae3-11e5-8761-f639edeab771.png)

And with 1.0.0-RC6 my menu looks like this, and menu items are not clickable: 
![mdrc6](https://cloud.githubusercontent.com/assets/3983854/11603597/4185f376-9ae3-11e5-9de1-cc8cf1448d1a.png)

In my case md-menu is nested into md-toolbar.

**Comment by MilosStanic** [comment]
Same as #6073

**Comment by corneschouten** [comment]
+1

**Comment by SuperheroicCoding** [comment]
+1 
Same as https://github.com/angular/material/issues/6109
