### ISSUE TITLE
Material is extremely slow with protractor

### ISSUE THREAD

**Issue by ashaffer** [angular/material#6090]
This isn't exactly a bug per se, but it's pretty debilitating for protractor tests. The cause is waitTransitionEnd, particularly (for me, at least) on ngShow and ngHide. When these directives don't have associated transitions material falls back to a default timeout of 3 seconds, which protractor dutifully waits for - every single time.

You can stub this out for tests like this:

```javascript
$mdUtil.dom.animator.waitTransitionEnd = function () {
  return $q.when(null)
}
```

But that seems a little risky. At least this should probably be mentioned in the docs or something.

**Comment by topherfangio** [comment]
References #6380 and #7159.

**Comment by BelfordZ** [comment]
@ashaffer You could always just disable angular animations inside your protractor tests.
