### ISSUE TITLE
Can someone tell me what are the dependencies for using CDN version of angular material  1.0.0-rc4

### ISSUE THREAD

**Issue by sharduul** [angular/material#6094]
I recently jumped from 0.11.2 to directly 1.0.0-rc4 and all the application's layout was messed up.

I am sure I will have to fix it in the code. But just wanted to know where can I get latest version of angular material dependencie.

Currently I am using these dependencies-
'https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-animate.min.js',
'https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular-aria.min.js',

**Comment by epelc** [comment]
Angular 1.4.x is recommended

**Comment by rfuhrer** [comment]
I think you're missing this guy:
`<link href="//cdnjs.cloudflare.com/ajax/libs/angular-material/1.0.0-rc6/angular-material.layouts.min.css" rel="stylesheet"/>`
They added a layouts.css in one of the more recent versions.  I believe it was just before the 1.0 RC's started

**Comment by sharduul** [comment]
actually in their latest version they have documented all the dependencies here-
https://material.angularjs.org/latest/getting-started
