### ISSUE TITLE
[Bug] md-chips container width: 100%

### ISSUE THREAD

**Issue by thanhtruong0315** [angular/material#6095]
Dear all,

In version 1.0.0-rc6, I saw bug of md-chips container on ipad. I set md-chips autocomplete to full width, then I got no effect when I tap at the end of md-chips container. The cause by:
```
.md-chips .md-chip-input-container {
    display: block;
    line-height: 32px;
    margin: 8px 8px 0 0;
    padding: 0;
    float: left;
} /* angular-material.css*/
```
I fixed the bug by the way that I added width: 100% to above class in my css.
```
/*Fix bug material */
.md-chips .md-chip-input-container{
    width: 100%;
}
```
If the bug was fixed, please ignore my report.

Thanks.

**Comment by topherfangio** [comment]
If you are still experiencing issues (i.e. since we released 1.0.1), please provide a minimal Codepen demo of the issue and we will reopen this issue and investigate.
