### ISSUE TITLE
Smart app banners

### ISSUE THREAD

**Issue by blackxored** [angular/material#6106]
There seems to be an issue when [smart app banners](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html) are used in a mobile view. The whole banner gets cut off, and you have to manually scroll top from the toolbar.

**Comment by topherfangio** [comment]
Can you please provide a minimal Codepen which demonstrates the issue so that we can investigate further?

**Comment by blackxored** [comment]
I've since discovered that it only happens when you have auto scroll enabled in your container, so I'm not really sure it's a core issue per se and I'd be more interested in a workaround. Thanks.

**Comment by topherfangio** [comment]
Okay, we can definitely look at providing a workaround, but we will need a demo to test against so that we make sure we properly understand your problem.

Alternatively, you might post a message on the forums to see if anyone else has already come up with a workaround.
