### ISSUE TITLE
md-radio-button does not call ng-change

### ISSUE THREAD

**Issue by scottmboring** [angular/material#6107]
When the radio button is changed, the ng-change expression should be called. With the following example, ng-change is never called. According the radio-button documentation, this should work.

    <md-radio-group ng-model="controller.sort" ng-change="controller.filter()" layout="row" layout-align="center center">
        <md-radio-button class="md-primary" value="name" ng-model="name" ng-change="controller.filter()">
            Name
        </md-radio-button>
        <md-radio-button class="md-primary" value="index" ng-model="index" ng-change="controller.filter()">
            Index
        </md-radio-button>
    </md-radio-group>

Note: that it does not work for md-radio-group either which seems like it should be a feature of that component.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (609/500 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:53848 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdI-000Ljd-Ps
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:56 -0500
Date: Thu, 28 Apr 2016 13:32:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875545;
	bh=+Kq2y+K8whltnaxuxmQPV02DutrNKwrRaPRnUdD9SlI=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=RbjdUJE4kRDp9JrHPGx7yKoT+oJ7C5ECwllfxb7ABo3dhsmTP50UyKBOmtDkXdWdx
	 EoSsiR1s5Mer/7ywOTF+HG0Se4jMq8N3a1PU1GZYCvQdYV/vtZLclggAWVdJ2bVWRg
	 apPMzUOcRuwgnnXis2LsKquqBk7LIwMUdLGZlPLk=
