### ISSUE TITLE
Import material components (and dependancies) individually

### ISSUE THREAD

**Issue by kmturley** [angular/material#6108]
I have installed the pre-built version using jspm (overriding the dependency on css):

    jspm install angular-material -o '{ shim: {} }'

Then I can use JSPM and ES6 to import the javascript only:

    import angularMaterial from 'angular-material';

And SASS to import the css into my css build:

    @import '../../../jspm_packages/github/angular/bower-material@0.11.4/angular-material.scss';

This works really well. For development JSPM will inject the correct dependancies (angular, angular-animate, angular-aria, angular-material) and gulp-connect will reload my page. Then for production I can run gulp-jspm and uglify to minify the bundle.

However both bundles include all 30 components javascript and css (200KB css and 460KB js without my own site code). I would like a way to install the source files for only the components i'm using e.g.

    jspm install material=github:angular/material

Then import the core then components one by one, with jspm importing the dependencies for each one automatically e.g:

    import angular from 'angular/angular';
    import angularAnimate from 'angular-animate/angular-animate';
    import angularAria from 'angular-aria/angular-aria';
    import angularMaterial from 'material/src/core/core';
    import card from 'material/src/components/card';

etc.. Is this possible to implement? at the moment my only option it to rebuild the library manually without the components I need using your tools:

    gulp build

Ideas for implementation:
* Include the material repo as the default, rather than the built version
* Add config file in material repo with all components (choose which to include/exclude in a specific build)
* material-start to show example of building material with only a few components
* FUTURE: Rewritten in ES6 to support import statements and dependancies

**Comment by iainreid820** [comment]
This is something that I'm pretty keen on as well, I have a potential solution in mind that I could contribute to make this possible. What's the traction behind this feature at the moment?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (519/500 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:5770)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-b37a-greg=biomassiv.es@sgmail.github.com>)
	id 1avsc8-000L4M-If
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:44 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=PdzMOznUDjuDRoE2IhcLWFZSQZA=; b=PAAslGo2U6XdAsVb
	QM3jHy8x/Cdc8YVi647tEDZmNG+Xg+fnl05EiKY8xeAoge3rHTRKbkH82oENbST2
	fsdDmkR/w9hGtlw7a2EGggVzQ8VfEQh+HPk49rOxzWJMa1Rx/UfFNIh2xVoAWJWl
	bn9iPZC6SHL6nzbajPJ6T7OWhyo=
Received: by filter0508p1mdw1.sendgrid.net with SMTP id filter0508p1mdw1.2223.5722734E22
        2016-04-28 20:32:14.264458795 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id xSX7bKhlTBymz9dO1LKOdQ
	for <greg@biomassiv.es>; Thu, 28 Apr 2016 20:32:14.252 +0000 (UTC)
Date: Thu, 28 Apr 2016 13:32:14 -0700

**Comment by biomassives** [comment]
sorry for this mail burst- I am investigating its cause.
