### ISSUE TITLE
md-grid-lists aren't rendered on small screen

### ISSUE THREAD

**Issue by alanpurple** [angular/material#6114]
resize browser small and go to material angular js demo and doesn't appear

but if we resize to big and resize to small again, it shows fine

so for now md-grid-list doesn't work on small screen like smartphone's chrome

**Comment by emps** [comment]
see new sizes of https://material.angularjs.org/HEAD/layout/introduction
current md is like old lg

**Comment by alanpurple** [comment]
@emps  you don't understand what I said

It works when I resize, it's not the problem of settings or properties

**Comment by alanpurple** [comment]
My misunderstanding was caused by wrong demo
not a bug, closed
