### ISSUE TITLE
Cannot select for value of select when situated on top of page.

### ISSUE THREAD

**Issue by xavierva** [angular/material#6115]
I have a select in the header of my page in order to select languages, but it displays like this : 
![image](https://cloud.githubusercontent.com/assets/3062366/11623105/d5a7c1b8-9cca-11e5-947d-dab427fd324f.png)

And it is impossible to select "English", It just quit the select.

(On release 0.11.4)

**Comment by ThomasBurleson** [comment]
Please retry with lastest code from HEAD and submit a CodePen.
