### ISSUE TITLE
md-tooltip cropped when more than one line of text

### ISSUE THREAD

**Issue by MilosStanic** [angular/material#6117]
md-tooltip gets cropped if there's more than one line of text in it. It shows only the top line. 
If the top line is enclosed in `<h3>`, only a part of it is shown, the rest is cropped. 
This used to work fine before 1.0.0. md-tooltip used to grow with content.

**Comment by topherfangio** [comment]
Can you please provide a Codepen demo so that we can validate the issue and any potential fixes?

**Comment by MilosStanic** [comment]
Yes, here you go: http://codepen.io/MilosStanic/pen/zrrbRX

This is a copy of demo pen from the main angular-material site. 
You can hover over these fabs and see that the tooltips are cropped. 

Thanks!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
