### ISSUE TITLE
md-autocomplete should have a dropdown arrow option.

### ISSUE THREAD

**Issue by cleever** [angular/material#6118]
As we can see in material design specs.

![image](https://cloud.githubusercontent.com/assets/2815335/11627142/6f21a080-9ccf-11e5-8405-d251b85c71e4.png)

md-autocomplete directive should have an option like "dropdown-arrow".

    <md-autocomplete dropdown-arrow="true" ...

Obs. This discussion started in issue #2546, that we discussed that md-autocomplete and md-select could be one unique component.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (618/500 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:54180 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdJ-000Lkp-Pa
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:57 -0500
Date: Thu, 28 Apr 2016 13:32:49 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875570;
	bh=hbHaoDG5fnjmrettGeI0qgWL1DcTIIlEZEAczCsDEnE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=FZCMy7rl3BDbN8A0o+I4wGIngCmFQflpIBeeHanoEfnQbYh3o4Dse0mRRFpF4cUnN
	 8koSsuyr6RSq4SH/hFBgT9+hNryOsqV6LWx781KbGrURiAGb8lw3BbT148eHEhNkO0
	 bELb8u6SR1m7BX7LLhGpXc4zc+yAdT61mAQ2XP/M=
