### ISSUE TITLE
no border bottom on any input types other than text on the master branch

### ISSUE THREAD

**Issue by shfaizanali** [angular/material#6119]
I am adding input types in the login and registration form and no other input types except for text display the border bottom 

http://puu.sh/lMCkB/785f9268db.png

**Comment by EladBezalel** [comment]
@shfaizanali can you please provide a codepen so we can investigate more?

**Comment by shfaizanali** [comment]
Hey sorry, I was using it in conjunction with Ionic and Ionic's CSS was over riding material design css
