### ISSUE TITLE
Selectbox cutoff letter under the baseline

### ISSUE THREAD

**Issue by ebastuart** [angular/material#6121]
![cutoff](https://cloud.githubusercontent.com/assets/5196882/11628662/6996d030-9cf3-11e5-82e3-dc31953214fc.jpg)

See the 'g' in sausage

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (532/500 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:34162 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avscC-000L6B-1X
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:32:48 -0500
Date: Thu, 28 Apr 2016 13:32:15 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875535;
	bh=nVrp4e21nLsR9f9rSEtBxesqaSsm95aXkF2c8pEzclg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=D0fkmu1NjbLscaCUvz7xuyq0NMGYuRClVRQdZW7wA9TNKNiZWxJXwgBIn9wXmvI2C
	 87E6nOLpZeb4lHhvdCRvFZEpM9KjxG4H03Z7uZ6YO5h+Xau4ERutbYfhDdAOY2oHB+
	 sBuu92Lf8Q4ZQ8o/Jm3aCxLE505NvftLl0aV4Qg0=

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (619/500 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:54179 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by ps5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1avsdJ-000Lkr-PX
	for greg@biomassiv.es; Thu, 28 Apr 2016 15:33:57 -0500
Date: Thu, 28 Apr 2016 13:32:49 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875569;
	bh=XvVf384hHra1FUovopqWCEZ2xtndiJLiL41KxFnAgEE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=a61t9zO33bUtYnhRZDBTv0ve72fK6U+NWlmbrkk/chLCDlt2IoDZzMEhVJ5Jg0T+0
	 i6zf91kcNP2EtcSPbhpk0iF+Ry1Lsl1Mc/2SrTOYTA+Q67t6VHAc8jkG8AYk2gnbBH
	 pIZbudRhNYpBWVEoET4RHI5P6WM4YyQYZ2QEjSFY=
