### ISSUE TITLE
Demos, select validation fails on Clear

### ISSUE THREAD

**Issue by guillaume-fr** [angular/material#6122]
Official doc : https://material.angularjs.org/latest/demo/select
In the last sample (Validations), when you set a value then clic on CLEAR the select is displayed with a validation error (Required) and the label is shown two times (Top + Placeholder).

Expected result : no validation error, label only in Placeholder.

I tried to call `$setPristine` and `$setUntouched`. It fixes the validation error but the label is still here.
http://codepen.io/anon/pen/BjyzYM

**Comment by DevVersion** [comment]
Here is a fix for that #6132
