### ISSUE TITLE
md-menu-item type="checkbox" use md-svg-icon?

### ISSUE THREAD

**Issue by PapyElGringo** [angular/material#6123]
Why the **md-menu-item** with **type="checkbox"** use an **md-icon** with **md-svg-icon="check"**?

What if we use google **material font icon**?

**Comment by PapyElGringo** [comment]
Up after edit :)

**Comment by igorcamp** [comment]
+1 for material font icon.

**Comment by Edorka** [comment]
+1

**Comment by abides** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
