### ISSUE TITLE
Cannot read property '$$phase' of null

### ISSUE THREAD

**Issue by AliPoder** [angular/material#6129]
I'm getting this error when loading the app.

It comes from `VirtualRepeatController.prototype.containerUpdated` function and on this line:

`if (!this.$scope.$root.$$phase) this.$scope.$digest();`

If I do this, it fixes: 

`if (this.$scope.$root && !this.$scope.$root.$$phase) this.$scope.$digest();`

What's the problem?

**Comment by ThomasBurleson** [comment]
@AliPoder - which version of angular and angular material are you using?

Whenever possible, provide a CodePen demo.

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).

> Can you confirm the issue still exists with the above versions ? I will reopen if needed.

**Comment by AliPoder** [comment]
I am using `AngularJS v1.5.0-beta.1` and `Angular Material v1.0.0-rc6 (f73ef23)`

You can see the error here: https://beta.scorpapp.com/

**Comment by AliPoder** [comment]
Updated Angular Material to `v1.0.0-rc6-master-d3c0acb` and i'm getting the same error.
