### ISSUE TITLE
mdToast: width on small devices differs from spec

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#6130]
mdToast currently has a width of 100% on small devices.  This is determined by this check: `var isSmScreen = !$mdMedia('gt-sm');` when the toast is opened.

The spec https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs specifies that the toast be full-width on mobile, but also lists a max-width of 568dp on tablets / desktops. 

There is the following css that enforces this rule on large displays, but this check is not consistent with the adaptive ui spec.
```css
@media (min-width: 1920px) {
  md-toast {
    max-width: 568px; } }
```

**OS:** Windows 7 x64, Opera 33/ Chrome 46
**Suggested fix:** change the query to `!$mdMedia('gt-xs');` fixes the 100% width issue, but does not address the 568 max-width on desktops/tablets

**Comment by EladBezalel** [comment]
dup #4827
