### ISSUE TITLE
Menu items not clickable when inside an md-toolbar or md-menu-bar

### ISSUE THREAD

**Issue by llblu15** [angular/material#6131]
I cannot seem to click a menu item when the menu is inside of a toolbar or the menu bar.  

Here is a codepen showing the menu working without a toolbar and with a toolbar, commented out is the menu bar, but the same behavior exists.

http://codepen.io/llblu15/pen/obgBap

**Comment by stunaz** [comment]
dupe of #6109, #6116, #6049, #6073, #6080

**Comment by ThomasBurleson** [comment]
@rschmukler  - can you investigate?

**Comment by jeroenvheel** [comment]
i have the same problem with the latest master d3c0acb

**Comment by florent1933** [comment]
Still not working (even with RC7 and master) : http://codepen.io/anon/pen/xZwobN
