### ISSUE TITLE
accessibility: md-checkbox 'Syncing' example

### ISSUE THREAD

**Issue by philmerrell** [angular/material#6136]
Chromevox doesn't report whether a `md-checkbox` is, 'checked' or 'not checked' in the example "Using md-checkbox with ng-checked".

http://codepen.io/anon/pen/WrbpgR

**Comment by marcysutton** [comment]
Yep, you caught a bug! For some reason it's not setting `aria-checked`.

**Comment by philmerrell** [comment]
Awesome!  Thanks for taking a look. :)

**Comment by marcysutton** [comment]
This will be addressed with some ngAria fixes I have forthcoming. Basically, `ng-checked` only works on native inputs, and mdCheckbox is custom. ngAria will handle ngChecked in addition to ngModel very soon.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
