### ISSUE TITLE
Usign Multiple Dialogs

### ISSUE THREAD

**Issue by hernando100** [angular/material#6137]
I would like to know if it's posible to open a dialog inside another without closing the parent dialog.

I've read issue #698 but solution the give it's by closing the parent dialog, and that solution does not work for me.

Sorry for my English

**Comment by yccteam** [comment]
It seems to work with this configuration: http://plnkr.co/edit/Ga027OYU5nrkua3JxNRy?p=preview
In the inner "confirm" dialog I've added: 
```
preserveScope: true,
skipHide: true
```
