### ISSUE TITLE
Promises and $apply

### ISSUE THREAD

**Issue by kseamon** [angular/material#614]
One of the things I noticed over and over while looking over the codebase was the use of promises to handle animations completing. From an API perspective this is very nice, but it would be nice to avoid the $apply calls when the promise has no outside listeners.

I'm still thinking out how this would work, but It would be something to the effect of using $$q internally to propagate promises without the digest cycle (For dom manipulations, not scope updates).

On the exposed promise, overwrite then to return a promise from the $q system. ($q.when might be helpful here). If the original promise is resolved outside of the digest cycle and has had one of these $q promises latched onto it, ensure that an $apply is triggered ($q.when probably does this already).

**Comment by ThomasBurleson** [comment]
Angular 1.4 $animate now supports Promises.
