### ISSUE TITLE
md-datepicker: change background color

### ISSUE THREAD

**Issue by vsrboth** [angular/material#6142]
First, sorry for my created issue is you guys feel like this is nonsense (bow).

Anyway, I am encountering with md-datepicker background color. Do you think the background color would rather be able to change according to the design layout. Kindly find the following screenshot:

<img width="779" alt="screen shot 2015-12-08 at 9 38 18 am" src="https://cloud.githubusercontent.com/assets/5484995/11646349/bfd09502-9d8f-11e5-909c-b4c4a4caa4db.png">

Thanks a lot and hope to hear from you all soon :)

**Comment by gbaj** [comment]
+1

I think just killing the explicit white background should be good enough hopefully

**Comment by vsrboth** [comment]
@gbaj I did as your suggestion and it won't work. More problems still exist; for ex, the icon color is dark gray, therefore, the date picker will look even darker.

**Comment by jelbourn** [comment]
The background color is currently based on the theme. By default, the theme's background color is white. You should be able to override it by:
```css
md-datepicker.md-THEME_NAME-theme {
  background: magenta;
}
```

Where `THEME_NAME` is the name of your theme, or `default` if you're using the default.
