### ISSUE TITLE
Interpret custom timezone in datepicker

### ISSUE THREAD

**Issue by natcohen** [angular/material#6144]
The datepicker interprets only local timezone meaning that 2015-12-08T00:00:00Z will be interpreted as 2015-12-07 in New York.

Could we add an option to interpret the date to a custom timezone?

**Comment by altsel** [comment]
just have a look here #4636 !

**Comment by natcohen** [comment]
Well, it's not exactly the same thing...

My point is that the datepicker should be compatible with ng-model-options (https://docs.angularjs.org/api/ng/directive/ngModelOptions) timezone...

**Comment by jelbourn** [comment]
Internationalization is done through the `$mdDateLocaleProvider`. Please see the [documentation](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider). Angular Material still supports AngularJS going back to 1.3, which only supported "UTC" in ngModelOptions.

The issue of the demo not being internationalized can be tracked in #4671
