### ISSUE TITLE
$mdDialog is not displayed properly 

### ISSUE THREAD

**Issue by Nekle** [angular/material#6145]
The diloag is not displayed on the right place after scroll down page.

Please check it here : http://codepen.io/anon/pen/XXJzVd

![snip20151208_3](https://cloud.githubusercontent.com/assets/1272353/11650032/2f7867a6-9dc0-11e5-9d5f-40cb95b16622.png)

**Comment by trevorhreed** [comment]
You can prevent scrolling on the parent container using the `disableParentScroll` option when you create a custom dialog. It doesn't appear from the documentation that there is a way to use this option with preset dialogs.
