### ISSUE TITLE
angular-material.layouts - WP8 - Performance brake

### ISSUE THREAD

**Issue by graphefruit** [angular/material#6147]
Hello Angular-Material-Team,

I've included the latest material-layouts-RC6 - https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.0.0-rc6/angular-material.layouts.min.css)

But after including this stylesheet, the Windows-Phone 8.1 isn't useable anymore.
All click events are delayed. Content can't be scrolled anymore, animations are more laggy as before aswell.

No problems in IOS (>=7) and Android (5.0 and 6.0)

PS: Its a Cordova-App (not a "website")

Thanks
Graphefruit

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
