### ISSUE TITLE
md-autocomplete: should have a 'display icon' option

### ISSUE THREAD

**Issue by drinkbird** [angular/material#6150]
It's commonplace to display an informative icon next to some controls, especially if that control is used for searching. It would be nice if the autocomplete control could accept an icon property that would result to something like the following:

![sb1](https://cloud.githubusercontent.com/assets/1180736/11653340/77cf4b08-9d95-11e5-85b5-124ed6808a7e.png)

![sb2](https://cloud.githubusercontent.com/assets/1180736/11653341/791e3d66-9d95-11e5-8060-b6477dc31986.png)

Cheers

**Comment by cleever** [comment]
+1

**Comment by troig** [comment]
+1
At the moment, just as a workaround, we can do something similar with a bit of custom CSS. See [plunker](http://codepen.io/anon/pen/GoxBeL)

**Comment by drinkbird** [comment]
@troig thanks for the suggestion, it's similar to what I'm doing for now. It's just so standard to see an icon there that it would make sense to be supported out of the box.

**Comment by fernandogomesdf** [comment]
+1 for icons

**Comment by JLWeich** [comment]
+1 for icons

**Comment by zbroman** [comment]
+1 for icons

**Comment by cpBurn** [comment]
+1 for icons

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (405/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:47286 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw3-001GOZ-0S
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:21 +0200
Date: Thu, 28 Apr 2016 12:46:34 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872794;
	bh=XcunXfD79RD+rg0F3sRfv9cpDQili0DRvK2+Z9tk62Q=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=11AxBtTFnMOoEa0Ql/g/CFzkTokCEOc4kd0RLzNpLdYio9onWdc9jUmQyuVFZsSqx
	 H0PNzrW61Vg6QnFZaGr5mMPFBTTpQOwv8jBiFQaVIw9x58VedFz2icjwJkD5iULnQj
	 hda53i+2z0nAyVBb4vfE71W+D8/0S5SXd8eDu4yY=

**Comment by Dunos** [comment]
Is this issue going to be resolved or we should use the CSS workaround all the time?

**Comment by LeoLozes** [comment]
I guess it has been closed on the spring issue cleaning spree. Would be really nice to have without nasty CSS hacks though.

**Comment by Gimmeaphatbeat** [comment]
+1

**Comment by peterculak** [comment]
+1

**Comment by kdsingharneja** [comment]
+1

**Comment by ascold** [comment]
+1

**Comment by darxx** [comment]
+1

**Comment by Meshiest** [comment]
+1

**Comment by jefferson-silva** [comment]
+1

**Comment by naveen09** [comment]
+1

**Comment by decko** [comment]
:+1:

**Comment by Alexberemart** [comment]
+1

**Comment by mihailvalchev** [comment]
+1 for icons

**Comment by CaptainYouz** [comment]
Also, when using the md-autocomplete with a floating label, it can be good to have a select icon at the right, as the simple select component

**Comment by ElPsyCongro** [comment]
+1

**Comment by ronsuez** [comment]
+1

**Comment by joaocraveiro** [comment]
+1

**Comment by amirping** [comment]
+1

**Comment by stephengardner** [comment]
+1

**Comment by abelbarbosa** [comment]
+1

**Comment by LuXDAmore** [comment]
+1

**Comment by themausam** [comment]
+1

**Comment by csimpi** [comment]
+1 for icons

**Comment by zcharleshebert** [comment]
Since this issue is closed, I don't think this is gonna be fixed. CSS workaround works well so...

**Comment by glowinthedark** [comment]
This works with `@angular/material@12.2.13`

```html
<mat-form-field appearance="outline">
  <mat-label>Country of residence</mat-label>
  <input type="text" placeholder="Pick or type a country" aria-label="Country" matInput [formControl]="countryField"
  autocomplete="off"
    [matAutocomplete]="auto">
  <mat-autocomplete formControlName="country" #auto>
    <mat-option>Andorra</mat-option>
    <mat-option>Antigua and Barbuda</mat-option>
    <mat-option>...</mat-option>
  </mat-autocomplete>
  <mat-icon matSuffix>language</mat-icon>
  <mat-hint>Location</mat-hint>
</mat-form-field>
```

![image](https://user-images.githubusercontent.com/48893368/143615760-8bab1cde-0b05-4d2a-ab2c-7eeb7961ebf4.png)

**Comment by Splaktar** [comment]
@glowinthedark Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for AngularJS Material.
