### ISSUE TITLE
mdInput: uses red color instead of md-warn

### ISSUE THREAD

**Issue by arabsight** [angular/material#6153]
md-input-invalid is using a red color rgb(213,0,0) for the border and floating label which doesn't look good in a dark theme. it would be nice if it uses md-warn color.

version:1.0.0-rc6

**Comment by EladBezalel** [comment]
@arabsight can you please provide a codepen?

**Comment by EladBezalel** [comment]
closed via ff11fb46ebee67ecb6c4e59016e9157159090f4d
