### ISSUE TITLE
desktop breakpoints should be X-16px

### ISSUE THREAD

**Issue by antoinebrault** [angular/material#6157]
As per material spec (https://www.google.com/design/spec/layout/adaptive-ui.html#adaptive-ui-breakpoints):

** Desktop breakpoints are 16dp below the listed values to accommodate variations in browser chrome.

1024**
1280**
1440**
1600**
1920**

so lg should start at 1264px and xl 1904px.

**Comment by ThomasBurleson** [comment]
@jelbourn - do you concur?

**Comment by jelbourn** [comment]
@ThomasBurleson this needs more discussion.

**Comment by birkskyum** [comment]
@antoinebrault as I read the column for window size should large first start at 1440 px - 16 px = 1424 px, and xlarge like you calculated at 1904px.

Don't you agree?

**Comment by antoinebrault** [comment]
@birkskyum It seems that the column for window size doesn't match the image.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
