### ISSUE TITLE
Include jade template for custom mdDialog?

### ISSUE THREAD

**Issue by sankhadeeproy007** [angular/material#6160]
Is there any way I can use a `jade` template as the template for the custom dialog? I tried and this is what I get. Is there any specific reason for the escape characters at the start of each class name.
![screen shot 2015-12-08 at 8 19 55 pm](https://cloud.githubusercontent.com/assets/10998047/11658525/2c8af670-9de9-11e5-8724-0289c34164fb.png)

**Comment by trevorhreed** [comment]
Maybe I'm missing something, but wouldn't you need to compile the `jade` template first?

**Comment by sankhadeeproy007** [comment]
`template: dialog()` fixed it for me. If that's what you mean by compiling the jade file.
