### ISSUE TITLE
some sort of Info-tooltip similar to md-tooltip, but more freedom

### ISSUE THREAD

**Issue by GustavSt** [angular/material#6163]
According to issue #4464 md-tooltip will not support multi line content, since material design specs says it shouldn't.

However a directive/component with this feature would be really nice, if you want to show more detailed info on hover than just one line.

**Comment by epelc** [comment]
I think your looking for `md-popover` see https://github.com/angular/material/issues/1217

I had multi line tooltips for a while but they aren't user friendly with that much info. A major point is you can't copy text out of them. I ended up switching to a click this to show more info sort of drop down.

**Comment by GustavSt** [comment]
Yes! I also realised this with copy not being possible. I decided to solve using some CSS instead and showing the entire content expanding the container. I'll close this issue/request.
