### ISSUE TITLE
cosmetic change to md-dialogue

### ISSUE THREAD

**Issue by ganySA** [angular/material#6165]
Hi

Sorry if this is a pedantic point, but currently md-dialogue background is set to white.

This causes the edges of the rounded corners to display with a white 'ness (especially visible on the top left and right when dialogue is open on the dark gray background)
Changing background:transparent removes this white hue on the edges - it looks cleaner but this then will impact the rest of the dialogue which becomes transparent, which then needs a tweet to set background white.

This is only visible when the dialogue has a non white header - e.g when using md-toolbar etc.

Maybe there is an easy fix.

**Comment by topherfangio** [comment]
Can you please provide a Codepen showing the issue with the white background so that we can look for a quick solution?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (404/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:46778 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw2-001GNx-3b
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:21 +0200
Date: Thu, 28 Apr 2016 12:46:32 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872792;
	bh=2K3dH/T5G2RHwSmtu/5vZ+VeQxRodUTIoyP5xelB4dU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Dc89eBwepRINookzGsYRW3hXKPX6SPdn8dGux1wBc4aRHcaVXhhnv8D4q9rNwzry8
	 yRQS1eu0As/NVgnhxAcbAD2CXQCTpDfGuEBLB7HtoqP+JWEWBdesGiwzAtCWXF9hrT
	 kH5qTUqD/lu8oZNLLvAK5m7KNi+eYwgCdWqNpxiA=
