### ISSUE TITLE
Exception: cannot read warn of undefined

### ISSUE THREAD

**Issue by chr22** [angular/material#6166]
![image](https://cloud.githubusercontent.com/assets/3649594/11664003/7222b830-9ddf-11e5-8b0a-7ef726cd51a4.png)

$log is undefined
![image](https://cloud.githubusercontent.com/assets/3649594/11664031/9e455440-9ddf-11e5-9ed8-9a5613a4f9a6.png)

Version 1.0-rc6

**Comment by danjarvis** [comment]
+1

Note: remove the `flex` attribute from your `md-button` to avoid this until a fix is posted.

**Comment by mprentic-harris** [comment]
Please test with master, this should already be fixed.

**Comment by topherfangio** [comment]
Please post a comment if you're still experiencing this after upgrading to 1.0.0 and we will reopen.
