### ISSUE TITLE
md-fab-toolbar <span flex> </span> is not working 

### ISSUE THREAD

**Issue by ishankhare07** [angular/material#6168]
possible duplicate #3477

i see that the issue was closed because there was not codepen example provided
i wish to reopen this issue that i'm also facing

[here is the codepen](http://codepen.io/ishankhare07/pen/LGEgbw) demonstrating the issue

basically the use of `<span flex><span>` to position the icons towards right is **not working** inside `<md-fab-toolbar>` while this same approach **works fine** inside `<md-toolbar>`

**Comment by gbaj** [comment]
Span is an inline level element, I don't think flex should/would work on it

**Comment by ishankhare07** [comment]
@gbaj it does work in case of `<md-toolbar>`
in fact, that's how its shown in the [official demos](https://material.angularjs.org/latest/demo/toolbar)

**Comment by topherfangio** [comment]
@ishankhare07 The FAB Toolbar is a specialized version of the toolbar and does not currently support custom layout styles inside. I'm going to mark this as a feature request for a later version.

As a workaround, you could apply the following CSS style to your FAB Toolbar, but I can't really say that this is "supported":

```css
.my-fab-toolbar .md-fab-action-item:nth-child(2) {
  flex: 1;
}
```

_If you use this, make sure to add the `my-fab-toolbar` class (or something better) to your element so the CSS is properly applied._

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (403/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:47336 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw3-001GOk-9V
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:20 +0200
Date: Thu, 28 Apr 2016 12:46:38 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872798;
	bh=ygbWrlHqyeXYSryDiZkVOnEIzOquAy9gd2JpB3l+Qkw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=eMDOqfxhlc+sM3q14nLUjONkK+RvKlYPLZCyUcCEGRGWt3GCGwDbmPNHiBbumVWp8
	 DZGuSZU07EqrVRE3eV8ot9hEWGyRtNw1jD+AEq84FTDMjgZ498y6ZluGO8tN/ZrY8X
	 VyKeENQ5l/J4EsktP2s2MTNKJL+B8UeReDvXeWyU=
