### ISSUE TITLE
md-autocomplete md-min-length not fully programmable

### ISSUE THREAD

**Issue by erinjanae** [angular/material#6173]
When setting the md-min-length programmatically, the dropdown doesn't update automatically.

I'd like the dropdown to open without having to enter any text into the md-autocomplete field, when first entering the the input field. After selecting an item from the dropdown, I'd like the dropdown to close. (This works through programmatically setting the md-min-length).

Then after clicking into the md-autocomplete field again, I'd like the dropdown to open automatically without having to enter text into the input field. (I was able to programmatically set the md-min-length to 0 after clicking into the md-autocomplete field, but the dropdown doesn't update immediately).

I was able to enter search text into the md-autocomplete and then remove the search text and then the dropdown still displays (which shows that the md-min-length is being set to 0 just not updating if the dropdown is showing or not automatically).

This code pen shows the issues I am having with programmatically setting the md-min-length:
http://codepen.io/anon/pen/NxPLbq

![onlyupdatingdropdownaftermodifyingsearchtext](https://cloud.githubusercontent.com/assets/6215642/11667492/447f1f34-9daf-11e5-9758-578684a88a4a.gif)

**Comment by Wykks** [comment]
+1
