### ISSUE TITLE
md-progress-circular with md-mode="indeterminate" doesn't rotate anymore

### ISSUE THREAD

**Issue by dennislaupman** [angular/material#6178]
HI Guy's

The md-progress-circular doesn't rotate anymore. And it's not centered in his parent container.

Grtz Dennis

**Comment by csvan** [comment]
Seems to work fine as of rc7:

https://material.angularjs.org/latest/demo/progressCircular

**Comment by dennislaupman** [comment]
Hmmm weird! 

If I compare my code with the code of the demo that is generated by the md-progress-circular,
I miss a md-scale-wrapper div between md-progress-circular and the md-spinner-wrapper div.

This is my implementation:
<md-progress-circular md-diameter="40px" md-mode="indeterminate"></md-progress-circular>


What's generates:

<md-progress-circular md-diameter="40px" md-mode="indeterminate" aria-valuemin="0" aria-valuemax="100" role="progressbar" class="ng-scope" style="transform: scale(0.4);"><div class="md-spinner-wrapper md-mode-indeterminate"><div class="md-inner"><div class="md-gap"></div><div class="md-left"><div class="md-half-circle"></div></div><div class="md-right"><div class="md-half-circle"></div></div></div></div></md-progress-circular>

**Comment by dennislaupman** [comment]
Ai Ai ai,

We forgot to update the JS files of angular-material. Problem solved ;)

Thanx!
