### ISSUE TITLE
demos(speedDial): Open checkbox firing twice

### ISSUE THREAD

**Issue by topherfangio** [angular/material#6183]
**Steps to Reproduce**

1. Visit https://material.angularjs.org/HEAD/demo/fabSpeedDial

1. Click on the speed dial trigger until it is closed and the Open checkbox is unchecked.

1. Now, click/tap very quickly on the Open checkbox

**Expected Results**

The Open checkbox becomes checked and the FAB Speed Dial is displayed.

**Actual Results**

The Open checkbox is not checked and the FAB Speed Dial is still closed.

**Notes**

- It looks like the checkbox is firing the tap twice because the component itself is receiving two calls to the watcher for the `vm.isOpen` attribute and the ripple animation appears to fire twice.

- If you click and hold for a second, then release, the issue does not appear

- You can reproduce it multiple times if you open/close the Speed Dial and tap the checkbox (i.e. it doesn't just happen the first time).

**Comment by laicosly** [comment]
I'm experiencing this issue on 1.0.0-rc1-master-325d83e
