### ISSUE TITLE
md-menu-bar child menus don't stay open

### ISSUE THREAD

**Issue by srcn** [angular/material#6184]
When you hover over the child menus in md-menu-bar, they are not staying open.

To reproduce the issue:

1. Go to https://material.angularjs.org/latest/demo/menuBar
2. Click on the **File** menu
3. Hover over the **New** menu item
4. Try to go over the child menu and it will be closed

This only occurs when you open the menu for the first time. If you completely close the **File** menu and try it again, it works as intended.

Tested on Chrome 47 (Mac)

**Comment by jraadt** [comment]
And if you have multiple submenus (for instance if "Open" had a submenu in the menuBar demo), then you need to open each one individually, close the entire menu, and re-open it for them all to work.

**Comment by daviian** [comment]
#7019 seems to be the same problem.
