### ISSUE TITLE
custom toast's background is transparent

### ISSUE THREAD

**Issue by gyn7561** [angular/material#6186]
![toast](https://cloud.githubusercontent.com/assets/8389980/11678586/4ca01724-9e84-11e5-9504-1d437aecb4a6.png)

**Comment by gligoran** [comment]
+1

**Comment by corneschouten** [comment]
+1
`<div class="md-toast-content"></div>` seems to be missing.

**Comment by philmerrell** [comment]
+1

**Comment by topherfangio** [comment]
This was fixed recently and the fix is available in 1.0.0. Please post a comment if you are still having trouble after upgrading.
