### ISSUE TITLE
When using md-select within native Bootstrap "Modals", the top value in css of body may be set to negative and caused whole page blank

### ISSUE THREAD

**Issue by vc05946** [angular/material#6188]
Hi! I have used the md-select element within the native Bootstrap "Modals", when the page needed scrolling and is scrolled to bottom, the body would be set with top in css be negative. This would caused the body behind the dialog could not be visible and caused the whole page blank.

Currently I have fixed this problem by change the "bootstrap.js" function Modal.prototype.setScrollbar and Modal.prototype.resetScrollbar in order to fixed the problem. See if there is any solution can be made by angular material side.

PS: For your reference, I have fixed in "bootstrap.js" like:

Modal.prototype.setScrollbar = function () {
    var bodyPad = parseInt((this.$body.css('padding-right') || 0), 10)
    this.originalBodyPad = document.body.style.paddingRight || ''
    if (this.bodyIsOverflowing){
       this.$body.css('top', "-" + this.$body.scrollTop() + "px")&&this.$body.css('position', 'fixed')&&this.$body.css('width', '100%')&&this.$body.css('max-height', '100%')
       this.$body.css('padding-right', bodyPad + this.scrollbarWidth)
       this.$body.css('position', 'fixed')
       this.$body.css('width', '100%')
       this.$body.css('max-height', '100%')
    }
  }

  Modal.prototype.resetScrollbar = function () {
    this.$body.css('padding-right', this.originalBodyPad)
    this.$body.css('position', '')
    this.$body.css('width', '')

    var scrollTop = Math.abs(parseInt(this.$body.css('top')));this.$body.css('position', '');this.$body.css('width', '');this.$body.css('top', "");this.$body.scrollTop(scrollTop);this.$body.css('max-height', '');
    this.$body.css('top', "");
    this.$body.scrollTop(scrollTop);
    this.$body.css('max-height', '')
  }

**Comment by csvan** [comment]
Since you are mixing bootstrap and md, I doubt this is really an md issue. What is stopping your from using one or the other?

**Comment by vc05946** [comment]
You mean is using angular material alone rather than mixed?

**Comment by csvan** [comment]
I mean that the problem is most likely a symptom of you mixing two frontend frameworks, which generally is a very bad idea. Hence, it is probably not an Angular Material issue.

**Comment by vc05946** [comment]
Understand, as I have used bootstrap at start, and later encounter angularjs material v0.10 later. May be I should fully use angularjs material when its full version out.

Thanks for you reply.

**Comment by ThomasBurleson** [comment]
Hybrid solutions not supported until ngMaterial 2

**Comment by hoffination** [comment]
I'm still getting this problem on my application and I'm not using Bootstrap. I get this problem only at the bottom of my views with md-select and md-autocomplete elements. Setting {top: 0} whenever I open the selector seems to fix my problem. It seems to offset up in some relation to how far down the page I have already scrolled or how close to the bottom of the page I get

![problemview](https://cloud.githubusercontent.com/assets/2348974/12707046/c199dc22-c84b-11e5-9986-8b4ed67a96ad.PNG)

`<md-select flex placeholder="City" ng-model="newSubrally.selectedLocation" flex="40" layout>`
`    <md-option ng-value="location" ng-repeat="location in newSubrally.locations">{{location.name}}</md-option>`
`</md-select>`

![inlinedstyle](https://cloud.githubusercontent.com/assets/2348974/12707083/351e7b94-c84c-11e5-801c-925afc95d80f.PNG)

**Comment by winnerf** [comment]
Hi, if you set disableParentScroll to false then this should work

**Comment by naderst** [comment]
@winnerf Thanks, it fixed the issue.
