### ISSUE TITLE
$mdDialog: Enter key causing multiple Dialogs to be displayed but only one with a controller.

### ISSUE THREAD

**Issue by darkninja462** [angular/material#6189]
Hello, I'm having an issue where if you open a mdDialog from a button and the 'Enter' key is pressed it suddenly closes the Dialog and reopens it again, which is made worse by if you continually press the 'Enter' key this will close and open a series of Dialogs. Which only the top Dialog can be closed/dismissed.

I was wondering if anyone had come across this before or how to get around it, so only a single instance is opened, I also noticed that this same behaviour is shown on the Demo page: https://material.angularjs.org/latest/demo/dialog if you open a modal and press 'Enter' a few times you should see the same issue.

Thanks in advance 

-Darkninja462

**Comment by RolandHeath** [comment]
Wow... If you hold down enter just long enough, it will keep making dialogs for about a second after you let go, and you can never get rid of all of them.

**Comment by trevorhreed** [comment]
In Chrome 48, OSX, I'm able to get the demo page to open multiple dialog boxes, but by clicking the appropriate button, I'm able to dismiss all of them without a problem. All behavior seems correct to me.

**Comment by RolandHeath** [comment]
@trevorhreed - I'm seeing the same in the latest now, it seems that this is at least partially fixed. 

I think there is still a focus issue - when multiple dialogs are open, pressing enter to close one will focus the element that spawned it, even if the backdrop of another dialog should be preventing this. 
This is fine for a keyboard/mouse user as we can just click to close, but could be an accessibility issue.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (412/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:47405 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw3-001GPE-Lw
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:22 +0200
Date: Thu, 28 Apr 2016 12:46:42 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872802;
	bh=v6Kj/zmnNxdDPpsMSTJ0bCHLoc3R0/6qiXZKHCDrNuM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=BrN2bkWWBYJ5RG306FSH2P9Vme2vKBPhAybztbRSPQanF+x0ODr76c/Ijrstoi7JW
	 SkpqZSahndi1fyb7/J+UpeBWSQbKQOc6Hd9vRdyC0O5KuWjSM6L4kKquwG60eb+KZO
	 GhZgLX/6PXO/EBf5tj3EuEot+vWPRBLUl/9yVXPU=
