### ISSUE TITLE
md-select misplaced

### ISSUE THREAD

**Issue by chr22** [angular/material#6190]
md-select is misplaced when you select something far down the list.  The further down the list, the more misplaced.

![image](https://cloud.githubusercontent.com/assets/3649594/11681933/39008c8e-9e62-11e5-9047-593edff7a0c3.png)

1.0-rc6, 1.0-rc7 and master.

Tested in Chrome, Firefox and Edge on Windows 10.

**Comment by treyhoover** [comment]
:+1:

**Comment by murphmar** [comment]
+1

**Comment by andrew-cunliffe** [comment]
:+1: somewhat annoying to use :laughing:

**Comment by amritk** [comment]
+1, gets pretty bad sometimes
![screen shot 2015-12-11 at 5 03 38 pm](https://cloud.githubusercontent.com/assets/2039539/11759112/3d8b29c6-a029-11e5-8740-c266a57ba620.png)

**Comment by richieforeman** [comment]
+1
