### ISSUE TITLE
Can't click in other tag in <md-not-found>

### ISSUE THREAD

**Issue by IlyaJurgens** [angular/material#6191]
<code>\<md-not-found ng-click="ctrl.addNewItem()">
                                    \<span>Not found "{{ctrl.searchText}}" \<a ng-click="ctrl.addNewItem()">Add to DB?\</a>\</span>
                                \</md-not-found></code>

Can't click to \<a> tag

**Comment by DevVersion** [comment]
Fixed in my PR #6103, which is currently waiting for merge.

**Comment by IlyaJurgens** [comment]
Thanks

**Comment by vlopez5** [comment]
+1
