### ISSUE TITLE
mdGridList and cached images

### ISSUE THREAD

**Issue by dballesteros7** [angular/material#6193]
I have the following setup:

```html
<md-grid-list md-cols="3" md-row-height="1:1" md-gutter="8px">
  <md-grid-tile ng-repeat="category in vm.trendingCategories">
    <img ng-src="{{ category.image }}" class="tile-img">
  </md-grid-tile>
</md-grid-list>
```

With css:

```css
.tile-img {
  max-width: 100%;
  max-height: 100%;
}
```

The images are from different sources hence the max-width and max-height. The size of vm.trendingCategories is always 9. When 2 images that are in the browser's cache are next to each other in the grid, the second one disappears, see the empty space in the screenshot:

![screenshot from 2015-12-09 11-29-42](https://cloud.githubusercontent.com/assets/1774523/11683001/60c646e0-9e68-11e5-94c3-9f3a05e12791.png)

Inspect the grid reports that the image has 0 width, but full height. I'm not sure what the problem is here but after multiple reloads it is consistent that only happens to images fully cached when they appear next to each other.

Adding this to the CSS fixes the problem, but only on desktop:

```css
md-grid-list md-grid-tile figure {
  width: 100%;
}
```

On mobile, most of the images disappear after they have been cached. So far the only fix I have is to defer the class application until the image is loaded.

**Comment by crisbeto** [comment]
This was posted quite a while ago, but did you manage to resolve it @dballesteros7? I'm trying to reproduce it but I can't.

**Comment by dballesteros7** [comment]
I had this problem with some images and flex in other case too, in the end I found a solution but I no longer work in that app so I don't really remember what it was (some mix of flex and max-height/width, an inside div with position absolute and other magic).
