### ISSUE TITLE
Datepicker wrong formatting in Chrome

### ISSUE THREAD

**Issue by chr22** [angular/material#6194]
![image](https://cloud.githubusercontent.com/assets/3649594/11684284/e3aa34b0-9e70-11e5-86dc-3922630cccaa.png)

The date formatting in europe should be 12-09-2015.

It works correctly in all browsers except Chrome.

**Comment by jelbourn** [comment]
Internationalization is done through the `$mdDateLocaleProvider`. Please see the [documentation](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider).

The issue of the demo not being internationalized can be tracked in #4671
