### ISSUE TITLE
Datepicker formatting in Safari makes it hard to input date

### ISSUE THREAD

**Issue by chr22** [angular/material#6195]
![image](https://cloud.githubusercontent.com/assets/3649594/11684386/8384f182-9e71-11e5-9a66-2bbb26f0e42d.png)

This formatting makes it much harder to write a valid date, than in other browsers where the formatting is 12-09-2015.

Only in Safari.

**Comment by jelbourn** [comment]
By default it uses the browser's date parsing and formatting. You can define your own behavior with `$mdDateLocaleProvider` as described in the [documentation](https://material.angularjs.org/latest/api/directive/mdDatepicker).
