### ISSUE TITLE
error when input has a validation

### ISSUE THREAD

**Issue by marcomafessolli** [angular/material#6198]
Hi there, 

Material throws an error when input has a validation 

Ex:
```
<md-input-container class="md-block">
         <label>Login</label>
          <input type="text" name="login" ng-model="user.login" required>
</md-input-container>
```

Throws error: 

![Error]
(https://cloud.githubusercontent.com/assets/1048545/11686592/c7c4cede-9e68-11e5-9c6a-69e47cb734da.png)

**Comment by jakubweber** [comment]
Same here, need to be fixed

**Comment by marcomafessolli** [comment]
Seems like it no more occur. Closing issue
