### ISSUE TITLE
When scrollbar appear in sidenav, Chrome anchors content elements to wrong position. 

### ISSUE THREAD

**Issue by brunsgaard** [angular/material#6201]
The bug is shown here, try to force a scrollbar to appear in the sidenav by resizing the window.
Chrome 47 will then move the rest of the content left anchoring the element to the top left corner of the
scrollbar. The bug is illustrated here.

http://codepen.io/anon/pen/xZGwvr

**Comment by hewaroth** [comment]
+1

**Comment by braintapper** [comment]
+1

**Comment by EladBezalel** [comment]
Using Chrome 48 i couldn't see the bug..
