### ISSUE TITLE
How to get $element in md-dialog controller?

### ISSUE THREAD

**Issue by kzhdev** [angular/material#6203]
Add $element to md-dialog controller cause an error:
```
function blockEditorCtrl($scope, $element, $mdDialog) {
```
Error: [$injector:unpr] Unknown provider: $elementProvider <- $element <- blockEditorController

Is it a bug?

**Comment by bolerodan** [comment]
I'm curious where you think you can inject an "$element" into a controller that you pass to $mdDialog ? I don't see this in the docs.  That's besides the point, since you shouldnt be doing DOM manipulation with any element in your controller anyways.

**Comment by EladBezalel** [comment]
@bolerodan is right, please address this question to our [Forums](https://groups.google.com/forum/#!forum/ngmaterial) i'm sure you will be answered there

**Comment by kzhdev** [comment]
@bolerodan 
Why a controller passed into $mdDialog is different than a controller of directive? $element will be injected in a directive controller, why it cannot be injected by $mdDialog service?

**Comment by bolerodan** [comment]
@kzhdev  That is wrong. You're thinking of the link function. The controller of a directive does NOT receive the element.

**Comment by urrri** [comment]
@bolerodan If you declare $element in controller of a directive or a component element will be injected. In the link function it will be passed as second parameter anyway.

**Comment by phamtuananh791994** [comment]
I have the same problem :(

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
