### ISSUE TITLE
The md-fab-speed-dial not getting displaced appropriately by toast

### ISSUE THREAD

**Issue by petersgiles** [angular/material#6211]
In this demo https://material.angularjs.org/latest/demo/toast The buttons get displaced appropriately by the toast

```
 <div layout="row">
      <md-button class="md-accent md-fab md-fab-top-right">
        FAB
      </md-button>
    </div>
```

if I change the button to be a speed-dial it doesn't get displaced

```
 <div layout="row">
      <md-fab-speed-dial md-open="false" md-direction="up" class="md-fab-bottom-right">
        FAB
      </md-fab-speed-dial>
    </div>
```

if I add `class='md-button'` to the the `md-fab-speed-dial` then it displaces but the styling is all messed up.

I guess would probably be better if it used another marker to determine its displacement.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (406/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:47287 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw3-001GOa-17
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:21 +0200
Date: Thu, 28 Apr 2016 12:46:33 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872793;
	bh=4DJjreRGd95V1TlpCC+nI//vwNpWU8VZEPHFBApWBQQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=zwU34mJgEMf938zYqQhjpE3/OXPBocjUkCe1KxbG4aiImsySVz9wEf7y4No7rSvJ9
	 PYJHts+idma2QCLUTCQgK6AppdSrAEjIN6ddN+nrku9/Jkztrl9FkguyZTQDsybDdM
	 Y6au2GOVM5/tYvOK0QZuseORCz1jCPEy3Ygo6ovw=

**Comment by murphmar** [comment]
It looks like the styling isn't setup for toast + FAB. I worked around it by just creating these CSS rules for now:

.md-toast-open-bottom .md-fab.md-fab-bottom-left, .md-toast-open-bottom .md-fab.md-fab-bottom-right {
    -webkit-transition: all .4s cubic-bezier(.25,.8,.25,1);
    transition: all .4s cubic-bezier(.25,.8,.25,1);
    -webkit-transform: translate3d(0,-42px,0);
    transform: translate3d(0,-42px,0);
}

.md-fab.md-fab-bottom-left, .md-fab.md-fab-bottom-right {
    -webkit-transition: all .4s cubic-bezier(.25,.8,.25,1);
    transition: all .4s cubic-bezier(.25,.8,.25,1);
    -webkit-transform: translate3d(0,0px,0);
    transform: translate3d(0,0px,0);
}
