### ISSUE TITLE
Bug in release 0.11.4

### ISSUE THREAD

**Issue by pulkitnandan** [angular/material#6213]
I can't have selected tab showing its name in tab-selector.

Here goes the live proof @ https://material.angularjs.org/0.11.4/demo/tabs

You can select any tab and and verify that it doesn't shows the name of the currently selected tab in tab selector. I have verified this locally as well but the strangest thing it does is ,it works here http://codepen.io/anon/pen/jWPLoy which has this same 0.11.4 version and almost the same code.
The only difference I can notice is this example uses 1.4.6 version while mine had 1.4.8

And the reason I can't change my angular versions in failing app is because of some backward compatibility I have  to maintain.

**Comment by pulkitnandan** [comment]
I think the bower.json is responsible for above but here's the new caveat in this pic 
![image](https://cloud.githubusercontent.com/assets/5687927/11712167/38e580b6-9f51-11e5-8881-8d0ba4d0cdc0.png)
 It looks as it if works bt you can spot the bug, So I'm currently creating a demo app for the clients. Could angularjs-material be so buggy that practically such 1.0 release should be excluded in using them on production servers.

**Comment by 0101adm** [comment]
had this in 11.4.  fixed in 11.5.

**Comment by pulkitnandan** [comment]
Hey I have even tried bower installing the master version but my app as based on older versions of angular libs makes the resolution turns out to be 0.11.4 , well I'm trying to angular-materialize the generator angular from yeoman team.

**Comment by pulkitnandan** [comment]
Now I can install the latest release of angular-material but still I can't put a select box inside the fab speed dial, which used to work in 0.11.4 release and here goes the link for that http://codepen.io/pulkitnandan/pen/yeOBVa .

**Comment by ThomasBurleson** [comment]
Will not fix.
