### ISSUE TITLE
FAB Speed Dial on mobile (md-fab-speed-dial height)

### ISSUE THREAD

**Issue by jamalx31** [angular/material#6215]
The height of the element md-fab-speed-dial is fixed even with the FAB is closed
![screenshot 2015-12-10 12 27 02](https://cloud.githubusercontent.com/assets/3521238/11713066/b27f1dc8-9f39-11e5-9766-00a154fe31dc.png)

On mobile that confuses the scroll when the user touch the blue area (as in the image)

**Comment by topherfangio** [comment]
This should have been fixed a while ago when we added `pointer-events: none` to the closed speed dial. What version are you experiencing this with?

**Comment by jamalx31** [comment]
@topherfangio 
Thanks, I found out that I have to apply the same rule on the parent div
