### ISSUE TITLE
md-autocomplete progressbar is misaligned when using float-label and query results

### ISSUE THREAD

**Issue by vlopez5** [angular/material#6218]
When using float label, the progress bar position is misaligned as you can see here:

http://codepen.io/anon/pen/mVJXry?editors=101

**Comment by DevVersion** [comment]
Hello @vlopez5 ... I create a fix for that, but the another issue got combined with that. See #6258 (thats the actual new fix)

**Comment by vlopez5** [comment]
@DevVersion I see your other pull request too... Looks good to me... The bottom padding was bothering me too...
Thank you...

**Comment by ThomasBurleson** [comment]
Will review PR and merge soon.
