### ISSUE TITLE
md-select inside $mdDialog broken in rc6 & rc7

### ISSUE THREAD

**Issue by f1tech** [angular/material#6222]
I have an md-select that I'm using within $mdDialog that was working fine up until RC6. This is the relevant HTML:

    <md-select ng-model="longFormat" placeholder="Format">
        <md-option value="ACD">
            ACD
        </md-option>
        <md-option value="ADB">
            ADB
         </md-option>
         <md-option value="BLU">
             BLU
         </md-option>
         <md-option value="DVD">
             DVD
         </md-option>
         <md-option value="PLA">
             PLA
        </md-option>
        <md-option value="PLV">
            PLV
        </md-option>
    </md-select>

Starting with RC6, when I click on it I receive an "Uncaught TypeError: Cannot set property 'isOpen' of undefined. 

This continues in RC7 and in RC7 it also renders oddly. It used to align itself properly with the other items in the row and now it sits lower than the following elements. 

The surrounding HTML looks like this:

   <md-content layout="row">
        <md-select ng-model="longFormat" placeholder="Format">
        </md-select>
        <md-input-container>
           <label>Material #</label>
            <input ng-model="stk_num" size="10" style="text-transform:uppercase">
        </md-input-container>
        <md-input-container>
            <label>Title </label>
            <input ng-model="title" size="50" style="text-transform:uppercase">
        </md-input-container>
</md-content>

**Comment by jeson114** [comment]
+1

**Comment by EladBezalel** [comment]
Can you please provide a codepen?
