### ISSUE TITLE
mdSlider: Allow non-linear slider values

### ISSUE THREAD

**Issue by WillsB3** [angular/material#623]
Sometimes a slider may be required which does not have a linear scale for it's possible values. We have a use case where a slider represents the playback speed of a YouTube video where the available values are: 0.25, 0.5, 1, 1.25, 1.5, 2. This is not possible with the current angular-material implementation. 

This is just one example, you could have a slider that required a logarithmic scale for instance. 

It'd be nice if there was a way to explicitly determine the available steps of a slider. Alternatively, if it were possible to define a mapping of UI values to actual model values that might also be a solution.

**Comment by ArdentKid** [comment]
+1

**Comment by mfdev1** [comment]
+1

**Comment by vssystemluba** [comment]
+1

**Comment by zargold** [comment]
I will work on this PR and my plan was to implement it similar to how Thomas suggested with something called steps (but I will call it md-steps). I have a deadline need for it so I will implement it as fast as possible, but we may need it to be polished.
