### ISSUE TITLE
Small bug in the documentation

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#6230]
The documentation here:
https://material.angularjs.org/latest/layout/introduction

Says:
flex	integer (increments of 5 for 0%->100%)

But the example use:
flex="33"

See:
<div>
  <div layout="row">
    <div flex>First item in row</div>
    <div flex="20">Second item in row</div>
  </div>
  <div layout="column">
    <div flex="66">First item in column</div>
    <div flex="33">Second item in column</div>
  </div>
</div>

flex	
integer (increments of 5 for 0%->100%)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
