### ISSUE TITLE
autocomplete, text input, select and button do not align vertically

### ISSUE THREAD

**Issue by chet-manley** [angular/material#6232]
http://codepen.io/anon/pen/OMVBRN
NG v1.4.8
MD v1.0.0

Issue: 
When displaying any two of these components horizontally, they are not aligned vertically. 

Expected:
labels, autocompletes, text inputs, select inputs and buttons should align vertically when placed next to each other horizontally.

**Comment by mckenzielong** [comment]
Related to #5764 (just autocomplete though)

**Comment by xplodwild** [comment]
Likely related to #6214 too

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (408/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:47678 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw4-001GPX-2I
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:22 +0200
Date: Thu, 28 Apr 2016 12:47:11 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872831;
	bh=kxSsgUkOPUcDiKhi3+1X/2alzC3PGiGb2KCMVEDyTFw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=HCfg8rU7ED/RSD10d9+bOyIXKb/YxyA50ofCHn9qyOKDr3CMUjlinzvfqTQ6YLKFC
	 kt04WC73DeqLR1F4hQxjgt2QeAukTs22NxxkagJTzYn5t1FqvS2gwkov6ekWW18rD0
	 74VqckbuN9s/nadN+SbKYWO9b1fzBRCT6+DU/v+Y=
