### ISSUE TITLE
Using angular-material with jspm loads multiple styles in the head

### ISSUE THREAD

**Issue by craigsh** [angular/material#6236]
I'm trying out a seed project with jspm and angular-material.

When I run it in the browser the styling of my material components doesn't work correctly - whereas if I use a code pen is all looks as I expect.

I'm seeing that my page is loading 16 style entries into the head of the page all of which seem to reference material classes (I suspect jspm is somehow doing this). 

My issue is the same as is described here: 

http://stackoverflow.com/questions/33466779/how-to-get-rid-off-angular-material-extra-styles-and-css-linked-by-it-forcefull 

but the answer given there doesn't work for me.

How can I fix this?

**Comment by MacKentoch** [comment]
It also occur on [angular material website](https://material.angularjs.org/latest/). 

See head tag in chrome : so many md-theme-style.

Is it theme related?

**Comment by craigsh** [comment]
Yes, I've seen that, so it appears that this isn't related to my problem, although it does seem odd.

I've now resolved my problem - I was seeing styling differences between the 1.0.0rc version and the previous version.
