### ISSUE TITLE
mdSidenav doesn't receive md-dark-theme class like other directives

### ISSUE THREAD

**Issue by angrybakon** [angular/material#6237]
When using the dark version of a theme, directives see themselves decorated of `.md-dark-theme`. Except for `<md-sidenav>` who remains on the bright side.

**Workaround:** manually add the theme class `ng-class="'md-' + theme + '-theme'"`.

**Edit:** Not necessarily `.md-dark-theme`. I haven't quite grasped how the theming works, but if I create another theme - inheriting `default` - the sidebar won't receive `.md-mytheme-theme` either.

**Comment by EladBezalel** [comment]
@angrybakon Can you please provide a code pen so we can investigate this more?

**Comment by kouak** [comment]
I guess this pen should demonstrate the issue with sidenav styling.

http://codepen.io/anon/pen/MKQBqm

**Comment by EladBezalel** [comment]
will be fixed in #5868
