### ISSUE TITLE
Inkbar won't show / move when tab has element as content x3d with firefox 42.0

### ISSUE THREAD

**Issue by KalleKettunen** [angular/material#6239]
When creating x3d element inside the md-tab the ink bar indicating the selected tab won't render.

If you change tab in the browser and come back inkbar is rendered to it's correct place.

http://codepen.io/anon/pen/xZGXxy

Chrome seems work well.

**Comment by topherfangio** [comment]
The tabs controller exposes the `updateInkBarStyles()` method which you can call once the x3d scene has rendered. I am not familiar with x3d, so another alternative is to use `$timeout` if you don't have some sort of x3d `onRender()` callback.

Aside from this, I am not sure we can provide support. You may have better luck if you post this on the [forums](https://groups.google.com/forum/#!forum/ngmaterial).
