### ISSUE TITLE
show / hide accepting expressions

### ISSUE THREAD

**Issue by subarroca** [angular/material#6242]
Sometimes when creating a complex component you want to show or hide something depending on a condition AND media query. It would be great to have all those show-* hide-* accepting expressions

**Comment by EricBorlandAGS** [comment]
It would be very helpfull

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
