### ISSUE TITLE
md-autocomplete - keep the class “md-not-found”

### ISSUE THREAD

**Issue by rafaelhc** [angular/material#6244]
The md-autocomplete provides a class named md-not-found in the md-virtual-repeat-container when you are trying to search for an element that does not exist in the dropdown, displaying an error message underneath. When you remove focus from the input element, the md-not-found is removed. The autocomplete therefore gives a false impression of having a valid input, as the user is not presented with any feedback.

Is there any way to keep the class "md-not-found", even after you unfocus the input element?

**Comment by topherfangio** [comment]
I'll need to dig into this a bit more to see why the class is being removed.

**Comment by rafaelhc** [comment]
I have made a temporary solution:

<label class="{{selectedItem !== null || searchText === '' ? '' : 'label-error'}}">Name</label>

The label-error class applies a red color.

The solution is not an answer to the question per se, but offers an alternative quick fix

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (415/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:48190 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw5-001GQ5-7d
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:23 +0200
Date: Thu, 28 Apr 2016 12:47:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872847;
	bh=ZKbc2/g4VTJv/SbZauSpCAWR8gnCiOOnyisNOyCv8To=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ps7defIMsr4W/PqN9ZDLPaqM7HrUFCyTOxEYsCKav3nCcZSWVqE5oUhKdOc4C/5CL
	 5kxOI2MoFdsewO78g+l28ZuIHd26rDDmoUIlQ/BOQLVCHQqMS0yiWg7r8fzVSM4kIz
	 iVkZRJu77VZ0AsxXRo1xv3DOCr2CQAHsF6oo1cyo=
