### ISSUE TITLE
md-select template displays items and commas in separate lines

### ISSUE THREAD

**Issue by egamonal** [angular/material#6245]
Affects at least v1.0.0-rc7

when selecting multiple elements the label is updated with a concatenation of selected values and commas. Additionally, there is one line per item (value, comma, value, comma, etc)

this codepen shows the wrong behaviour:
http://codepen.io/team/AngularMaterial/pen/RrbXyW

<img width="288" alt="screen shot 2015-12-11 at 13 49 44" src="https://cloud.githubusercontent.com/assets/1971675/11744144/174d5bbe-a00e-11e5-841c-898e7cda0162.png">

I think the best approach should be allowing to override thi, so that we can use `md-select` to search multiple values, click on them and add them to a results list. I'd display the results in a different place, for example http://i.stack.imgur.com/f3QHk.png
md-select is great for very short lists but when there are more than, say, 10, it's quite hard to use.

**Comment by danjarvis** [comment]
This was introduced in rc5. This is a duplicate of #5926 and #6176 :)

**Comment by egamonal** [comment]
and apparently it was fixed in 2ab3075 2 days ago
I promised I searched before ;)
thanks!

**Comment by danjarvis** [comment]
@egamonal It is OK -- I did the same thing as you ;)
