### ISSUE TITLE
ng-messages. Validation is broken in 1.0.0-rc7

### ISSUE THREAD

**Issue by kamarouski** [angular/material#6246]
Codepen: http://codepen.io/anon/pen/wMKwwK

It looks like validation is broken in  1.0.0-rc7

1. When field becomes invalid all validation messages are displayed.

2. When field is back into valid state validation messages are not got hidden.

**Comment by jakubweber** [comment]
Same here. Need to be fixed.

**Comment by bgoerdt** [comment]
+1

**Comment by iamisti** [comment]
@kamarouski did you try using md-is-error on the md-input-container?

**Comment by topherfangio** [comment]
@kamarouski You need to include `ngMessages` as a dependency. It is not automatically included.

Here is an updated Codepen with it working.

http://codepen.io/topherfangio/pen/eJpoZN
