### ISSUE TITLE
Support older browsers throught bourbon

### ISSUE THREAD

**Issue by DominicBoettger** [angular/material#6247]
I did a little rewrite and included the bourbon library into the code and replaced the transforms to use bourbon to automatically compatible code.
This was needed to support Chrome 35.
I realized it was very helpful to get a lot of stuff in material cross-browser compatible.

Is bourbon unwanted or is there no interest to make it compatible? If there is interest i can add bourbon and make the code compatible as it's mainly copy and paste from my sources....

**Comment by epelc** [comment]
@DominicBoettger are you talking about the sass mixins [lib](https://github.com/thoughtbot/bourbon)?

Is there any reason you need to support chrome 35? Don't you have to spend a lot of effort to even get chrome to stay on a specific version as it aggressively auto updates. Is 35 special in some other way(windows xp support or something?)?

**Comment by DominicBoettger** [comment]
The enterprise version has often disabled automatic updates ( i hate it, but the poor thing is that this is still common in a lot of companies.
Also every browser which does not support the native versions (like transform) and instead uses the -webkit-transform or -ms-transform stuff is unsupported (often safari i think). As we develop software for companies we often don't have that impact on their software version ...

**Comment by epelc** [comment]
Have you tried adding an automatic css prefixer to you build process? That
should solve the vendor prefix issue  for all browsers. I use it and it
works quite well.

On Friday, December 11, 2015, DominicBoettger <notifications@github.com>
wrote:

> The enterprise version has often disabled automatic updates ( i hate it,
> but the poor thing is that this is still common in a lot of companies.
> Also every browser which does not support the native versions (like
> transform) and instead uses the -webkit-transform or -ms-transform stuff is
> unsupported (often safari i think). As we develop software for companies we
> often don't have that impact on their software version ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/6247#issuecomment-163983414>.
>


-- 
Thank you,
Ed Pelc

**Comment by DominicBoettger** [comment]
Thanks for the information. Did you ever try this? What if some styles have vendor prefixes and others not?

**Comment by epelc** [comment]
Np. The non prefixed override the prefixed ones after browsers turn on the prefix version. It works very well. I have been using it for over a year. Also most of the prefixers let you specify the minimum browser versions you would like to support. This reduces bloat which is nice.

It also has the added benefit of working with all your css and all 3rd party css for free.

**Comment by DominicBoettger** [comment]
```js
gulp.task('scss', function () {
  gulp.src(path.scss)
		.pipe(plumber())
		.pipe(sourcemaps.init({loadMaps: true}))
		.pipe(sassResolver({systemConfig: './system.config.js', includePaths: includePaths}))
		.pipe(sass({includePaths: includePaths, errLogToConsole: true}))
    .pipe(autoprefixer({browsers: ['Chrome >= 34', 'iOS 8', 'last 2 versions'], cascade: false}))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(path.output));
});
```
Thanks. It worked perfectly for me!
