### ISSUE TITLE
Rendering issues in Mac chrome

### ISSUE THREAD

**Issue by ThrowableFactory** [angular/material#6248]
Don't know the exact cause of this problem , but it happens when I scrolls.
<img width="1027" alt="issue" src="https://cloud.githubusercontent.com/assets/13232736/11747946/ddca890e-a060-11e5-8ff6-baa4c6c21f8d.png">

Scattered elements will reappear when I click on something or resize the browser.

It won't appear in Safari.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
