### ISSUE TITLE
Injection fails with angular 1.4.8

### ISSUE THREAD

**Issue by vrghost242** [angular/material#6249]
OK, not certain, I might have done some edit of the file (almost certain I did not) but after staring myself bling, I think there is an issue with angular-material (0.11.4) when trying to inject it into Angular (1.4.8)

Get the following issue:
Uncaught Error: [$injector:unpr] http://errors.angularjs.org/1.4.8/$injector/unpr?p0=%24%24asyncCallbackProvider%20%3C-%20%24%24asyncCallback%20%3C-%20%24animate%20%3C-%20%24compile

I have double checked, and the webpage loads the files (checked the URLs via source code):
<script src="/bower_components/angular/angular.min.js"></script>
<script src="/bower_components/angular-animate/angular-animate.min.js"></script>
<script src="/bower_components/angular-aria/angular-aria.min.js"></script>
<script src="/bower_components/angular-messages/angular-messages.min.js"></script>
<script src="/bower_components/angular-ui-router/release/angular-ui-router.min.js"></script>
<script src="/bower_components/angular-material/angular-material.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-material-icons/0.6.0/angular-material-icons.min.js"></script>
<script src="/javascripts/2group.js"></script>

And this is all that the angular script does so far.
var 2app = angular.module('2app', [ 'ngMaterial', 'ngMdIcons'])
    .config( function($mdThemingProvider) {
        $mdThemingProvider.theme('default')
            .primaryPalette('2Group')
            .backgroundPalette(2Group')
            .accentPalette('blue')
            .warnPalette('red');
        $mdThemingProvider.definePalette('2Group', {
            "50":"#f6f7f9",
            "100":"#c9d3d9",
            "200":"#a8b8c2",
            "300":"#7d95a5",
            "400":"#6b8798",
            "500":"#5e7787",
            "600":"#516775",
            "700":"#455763",
            "800":"#384751",
            "900":"#2c373f",
            "A100":"#f6f7f9",
            "A200":"#c9d3d9",
            "A400":"#6b8798",
            "A700":"#455763",
            'contrastDefaultColor': 'dark',    // whether, by default, text         (contrast)
            // on this palette should be dark or light
            'contrastDarkColors': ['50', '100', //hues which contrast should be 'dark' by default
                '200', '300', '400', 'A100'],
            'contrastLightColors': undefined    // could also specify this if default was 'dark'
        });

    });

**Comment by mpike1968** [comment]
I had the same issue.  I went back and updated my bower.json to the following:

{
  "name": "angular-material-starter",
  "description": "A starter project for AngularJS Material",
  "version": "0.0.1",
  "homepage": "https://github.com/angular/material-start",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "~1.3.x",
    "angular-animate": "~1.3.x",
    "angular-aria": "~1.3.x",
    "angular-material": "^0.8.0"
  },
  "devDependencies": {
    "angular-material": "~0.8.3"
  },
  "resolutions": {
    "angular": "1.4.8"
  }
}

This loaded in angular 1.3.20, which does work.

**Comment by vrghost242** [comment]
Strangely enough I pulled down my backup copy, and it works,But it seems to be using the same versions as the one that was broken

**Comment by ThomasBurleson** [comment]
To expedite resolution, please always test with the latest versions:

*  **Angular Material HEAD** or Angular Material **v1.0.0-rc7**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).

**Comment by vrghost242** [comment]
That did resolve it. Upgraded to angular-material 1.0.0 and angular 1.5.0 

Just a note (for people who haven't mastered bower, like me, who haven't mastered bower) it is a bit of a headache to update using bower, ended up manually editing bower.json then running bower install. bower update did nothing for me (unrelated problem, but guessing other people may have the same issue:) )
