### ISSUE TITLE
layout-margin and layout-padding missing selectors for new xs/xl breakpoints

### ISSUE THREAD

**Issue by someone1** [angular/material#6250]
The new breakpoints changed the pre-existing sm breakpoint and so equivalents for the new breakpoints should be added for layout-margin and layout-padding

**Comment by someone1** [comment]
Actually, is this even implemented as expected? Should layout-padding-gt-sm only apply if the viewport exceeds 960px? It seems to apply at any viewport. 

If I add layout-padding-sm and layout-padding-gt-sm shouldn't I expect a 4px padding on "small" screens and 8px padding on everything greater than that? This is not the current behavior.

**Comment by hkjels** [comment]
As far as I can see, it's not using any breakpoints, so it has no effect.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
