### ISSUE TITLE
Autocomplete with Chips to show options on focus?

### ISSUE THREAD

**Issue by tehabstract** [angular/material#6251]
Setting md-min-length to 0 doesn't work when Chips contain autocomplete, although it's meant to.

Best regards.

**Comment by topherfangio** [comment]
Please provide a Codepen to show us the exact issue.

**Comment by RolandHeath** [comment]
@tehabstract 
Have you set md-min-length on the chips, or the autocomplete? 
I'm not having any trouble with this in my app, using md-min-length on the autocomplete.

**Comment by tehabstract** [comment]
Hello, thanks for reply, yes, I am using md-min-length on autocomplete. Just to clarify, I want the dropdown to show as soon as I focus the input field. 

Here is my codepen:
http://codepen.io/anon/pen/adNzmv

Thanks in advance.

**Comment by RolandHeath** [comment]
Your problem is that the empty string is a false value. So in your codepen, you have: 

    var results = query ? clipping.institutions.list.filter(createFilterFor(query)) : [];

So for an empty string, query is false => results = []
The result gets cached, so you only see this line of code run once.

**Comment by tehabstract** [comment]
So I solve it with this:

clipping.institutionsQuerySearch = function(query) {
        var results = query ? clipping.institutions.list.filter(createFilterFor(query)) : clipping.institutions.list.filter(createFilterFor(''));
        return results;
    };

It works, thank you.

**Comment by topherfangio** [comment]
Glad you got it resolved. I am going to close this issue.
