### ISSUE TITLE
Small mistake in documentation

### ISSUE THREAD

**Issue by kazmenko** [angular/material#6252]
Hello. I identified small misstatement here: https://material.angularjs.org/latest/getting-started in section "Build a Material Application (blank shell)" in HTML code. Must be < link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc7/angular-material.min.css" > but not < link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc7/angular-material.min.css" > otherwise it work not correctly.

**Comment by marcomafessolli** [comment]
I don't see the difference :

**Correct:**
```
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc7/angular-material.min.css" > 
```
**Incorrect:**
```
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc7/angular-material.min.css" >
```

The link's are the same

**Comment by danjarvis** [comment]
@marcomafessolli I think OP has a copy / paste error. If you look at the getting-started link the stylesheet being loaded is from rc5:

`<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0-rc5/angular-material.min.css">`

**Comment by kazmenko** [comment]
danjarvis Thanks.

**Comment by topherfangio** [comment]
@ThomasBurleson Is it safe to just update this to 1.0.0 now that it's released?
