### ISSUE TITLE
md-accent/md-warn/md-primary don't work on a custom toast button

### ISSUE THREAD

**Issue by calebegg** [angular/material#6256]
See demo: http://codepen.io/calebegg/pen/GopJXZ

Despite having md-primary, the toast button is still white.

**Comment by maryisdead** [comment]
Can confirm.

**Comment by du6** [comment]
+1

Demo: http://codepen.io/anon/pen/pgyEoQ
Screenshot: https://screenshot.googleplex.com/h7cQ3XQfzLY

It used to work for v0.11.0:

Demo: http://codepen.io/anon/pen/rxeMNE
Screenshot: https://screenshot.googleplex.com/EDj1EQmPLxO
