### ISSUE TITLE
Demo pages menu doesn't open when reloaded

### ISSUE THREAD

**Issue by super-coder** [angular/material#6262]
if you reload https://material.angularjs.org/latest/demo/toolbar the arrow points up but the list with selected **toolbar** item doesn't show up. You have to click two times on **Demos** menu item

![image](https://cloud.githubusercontent.com/assets/2155554/11759904/2426d668-a0c1-11e5-9617-4fe5c18a3db4.png)

**Comment by topherfangio** [comment]
We are aware of this issue and plan to fix it when someone has time to look into it.

In the meantime, if you wanted to track it down and provide more info or a PR, we'd be certainly be delighted to look at it :smile:
