### ISSUE TITLE
Display issue for mobile devices esp. nexus 4,5

### ISSUE THREAD

**Issue by wizjack** [angular/material#6264]
I've this particular problems with angular material.

When I load a form it doesn't show all input fields filled up, however when I click on them the data appears, same thing happens when I scroll down the form, then the previous contents get hidden.
The first grab represnts the data hidden and second grab represents the data shown after clicking.
1- 
![capture1](https://cloud.githubusercontent.com/assets/15883444/11760182/64d9b384-a0b6-11e5-922b-44a919ebbfaf.PNG)

2-
![capture2](https://cloud.githubusercontent.com/assets/15883444/11760184/b3946640-a0b6-11e5-9eb3-29f151e24508.PNG)

It behaves normally on full screens or normal screens though.

**Comment by topherfangio** [comment]
Might be related to #5707.

**Comment by jlebras** [comment]
I got kinda the same problem with v0.11.0 on Android 4.4.2, random content hidden after a scroll (they don't show up anymore).
I fixed it by replacing the md-content ancestor element by a simple div... I didn't dig further since it was ok for me.

**Comment by wizjack** [comment]
I faced the problem while opening my site in chrome for android. It works well for desktops or normal screens. @jlebras I have already tried that but it didn't work. I even tried removing md-content tag with a div tag.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (400/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:46777 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw1-001GNy-TE
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:18 +0200
Date: Thu, 28 Apr 2016 12:46:32 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872792;
	bh=zVmRoRog4p4s8MjBH7AGo+UNc2mhGB7j6TifW3QOIpo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=T7prMrRm1tDiXZcrUHl9/l6furgfVPbEf+2N+d6yjC+ob4htLvAMMCjbcc8uTNmnq
	 ty4mcg/9yKwtPIdkoet7UFPqBkvcRM9FI8y83CqQxn7yQWg5cRpvWgS9lOkq0JsrDY
	 pOGqgenUEc2bziw0AgC4ah4F2pRBLDOCd2qQYYCY=
