### ISSUE TITLE
mdInputContainer: messages are displayed more than once

### ISSUE THREAD

**Issue by Frank3K** [angular/material#6265]
When an error in an `md-input-container` is triggered multiple times (e.g. when repeatedly changing the value using <kbd>backspace</kbd> and some other key) it is possible that the error message is displayed multiple times.

Issue tested on master. See the following screenshot:

![ngmessage](https://cloud.githubusercontent.com/assets/8014077/11761386/0bc9fffa-a0c1-11e5-815b-dcbd4a890687.jpg)

**Comment by DevVersion** [comment]
Yes I can reproduce that. Just to remember myself... this is happening on an `autocomplete` too (wrapped in input container by it self)

**Comment by DevVersion** [comment]
As we discussed in the previous PR, we found a few ways to solve that issue.
- Debouncing of the Model / Animation
- Logical Conditions for the Animation Expression

I suggest, to combine both ways. 
In addition to that, @topherfangio is working on some improvements / fixes for ngMessages.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
