### ISSUE TITLE
Scrollbars in layout using mdContent

### ISSUE THREAD

**Issue by waegen** [angular/material#6268]
Hi there,

i have prepared an example to show you my desired layout. The scrollbars on the content work as expected as long as the toolbars and content are direct decendents of the surrounding one (id=main). As soon as there are more divs around the scollbar on the right hand side is moved to the top container which is not what i want. 

FYI the additional divs will be generated because we are using ui-router which adds these to inject the views.

What am i missing here.

Plunkr: http://plnkr.co/edit/07bQaSRXSo6WhxO0TlUj?p=preview

Thanks in advance.

**Comment by topherfangio** [comment]
Try this: http://plnkr.co/edit/AhBL4E5xLdVbQb1HUkI9?p=preview

Basically, you'll need the `layout="column"` to be on the lowest div, and the parents to have the `layout-fill` directive so that they take up the proper amount of space.

Please let us know if this works for you.

**Comment by waegen** [comment]
Thank you for your answer. Unfortunately my project hierarchy is a bit different so that the HeaderInformation is outside the injected ui-view. I have updateted the [plunkr](http://plnkr.co/edit/07bQaSRXSo6WhxO0TlUj?p=preview) to reflect that. Now you can see an addtional scrollbar for the outside container.

Will it be possible to remove that or do I have to change my structure?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
