### ISSUE TITLE
docs(layout): layout alignment doc spelling error

### ISSUE THREAD

**Issue by Zenith-One** [angular/material#6271]
In the Alignment section of the Layout documentation, there is an instance of "layout" spelled as "lay3ut"

This is in the 1.0.0-rc7 version of the docs page (according to the footer).

Will be submitting a pull request soon to correct this.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
