### ISSUE TITLE
Card image scalling issue on chrome 48

### ISSUE THREAD

**Issue by daniel79** [angular/material#6273]
Chrome 48.0.2564.41 beta (64-bit) OS X 
Angular material 0.11.4

Is | Should be
------------ | -------------
![screen shot 2015-12-12 at 17 03 23](https://cloud.githubusercontent.com/assets/30544/11762768/85d5fab6-a0f2-11e5-9280-f82f3f07a32c.png) | ![screen shot 2015-12-12 at 17 02 37](https://cloud.githubusercontent.com/assets/30544/11762767/85d2204e-a0f2-11e5-87da-bba097fdf7fb.png)

**Comment by Frank3K** [comment]
Related for master: #6267.

**Comment by EladBezalel** [comment]
Note to self: `img` should have `width: 100%`

**Comment by daniel79** [comment]
@EladBezalel this also doesn't work for 0.11.4 where css selector is ok. It worked there for previous chrome version so not sure what changes in chrome were made and if it is not chrome bug (chrome v48 is beta version) Would be grateful for tip how to fix it.

**Comment by Splaktar** [comment]
More examples:
![screen shot 2015-12-15 at 12 56 41 am](https://cloud.githubusercontent.com/assets/3506071/11803600/5d5c0042-a2ca-11e5-8f02-04e476bde68b.png)
![screen shot 2015-12-15 at 1 23 26 am](https://cloud.githubusercontent.com/assets/3506071/11803617/7c0cebdc-a2ca-11e5-8693-2502f7892689.png)

**Comment by daniel79** [comment]
Scaling doesn't work on chrome beta for JPG images.
Here is codepen:
http://codepen.io/anon/pen/BjLVbE
