### ISSUE TITLE
Clearing md-select value (model) causes label to overlap empty select

### ISSUE THREAD

**Issue by apat183** [angular/material#6274]
Noticed the following layout issue. 

I use select option to filter some results and allow the user to clear filter. 

1. Selecting a md-select option
2. Clicking button to set model to "", null, or undefined
3. The md-select label positions over the select field even when it is blank.

http://codepen.io/anon/pen/YwyZXY

![capture](https://cloud.githubusercontent.com/assets/7892604/11762846/6835622e-a0c2-11e5-9ac1-0aeb6c18746b.PNG)

Thanks

**Comment by DevVersion** [comment]
This is already fixed in my pending Pull Request. See #6207

**Comment by apat183** [comment]
Great thanks, will close.
