### ISSUE TITLE
Remove theme css const from angular-material.js

### ISSUE THREAD

**Issue by kmturley** [angular/material#6277]
angular-material includes default theme css as a const variable in JavaScript. This can be seen in angular-material.js at the bottom starting:

    angular.module("material.core").constant("$MD_THEME_CSS"...

When loaded into your browser this adds lots of css style tags dynamically to the page document. Not only are these messy when debugging, but are very awkward to remove (I had to create my own build of angular-material.js just to remove them).

Maybe you can include an option in the gulp process to inline css, but I don't think it should be on by default. My suggestion would be in gulp/util.js change line 53 from:

    var jsProcess = series(jsBuildStream, themeBuildStream() )

to be:

    var jsProcess = series(jsBuildStream)

Then include the default theme code into the scss build instead. This also has a benefit of reducing the javascript filesizes from:
* angular-material.js 842KB > 792KB
* angular-material.min.js 291KB > 242KB

Here is the related stackoverflow dicussion:
http://stackoverflow.com/questions/33466779/how-to-get-rid-off-angular-material-extra-styles-and-css-linked-by-it-forcefull/34108615#34108615

**Comment by yoorek** [comment]
+1

**Comment by voor** [comment]
I would like to associate this with #6202 since then providing a SCSS file with the theme variables would be great.
