### ISSUE TITLE
Pagination from material design not yet implemented.

### ISSUE THREAD

**Issue by akash175** [angular/material#6283]
Needed pagination tag from MD in ng Material Design. Will it be available any time soon?

**Comment by ThomasBurleson** [comment]
I do not understand what you mean. Please clarify with more details.

**Comment by nestorneto** [comment]
he mean...

![screenshot from 2015-12-14 11 31 33](https://cloud.githubusercontent.com/assets/362382/11783475/4419cb74-a256-11e5-9b3d-0d74122ef462.png)

**Comment by ThomasBurleson** [comment]
Will not fix.

**Comment by kusmierz** [comment]
@ThomasBurleson why?
