### ISSUE TITLE
How to keep showing the select label?

### ISSUE THREAD

**Issue by rochapablo** [angular/material#6286]
All selects (https://material.angularjs.org/latest/demo/select) hide the label when I focus.

Is it possible keep the label, for newbie users?

**Comment by rochapablo** [comment]
Sorry, but is this how to use?

```
<md-input-container>
   <label>State</label>
   <md-select ng-model="orcamento.bonus" permanent-label="true">
      <md-option>AAA</md-option>
      <md-option>BBB</md-option>
   </md-select>
</md-input-container>
```

It should be working on version 1.0.0?

**Comment by DevVersion** [comment]
Sorry, for the late answer. We just need to wait for the PR to get merged. If this is merged, you are right - you can easily add the attribute `permantent-label`. But perhaps we should change the attribute name to `md-permanent-label`. With the prefix `md-`

**Comment by rochapablo** [comment]
Well I've just checked again and it's not working.

I'll just wait a little more.

Thanks.

**Comment by DevVersion** [comment]
If the PR got accepted, I will write here, you will be notified.

**Comment by ThomasBurleson** [comment]
@DevVersion - what is the PR associated with this issue?

**Comment by DevVersion** [comment]
It was #6292
