### ISSUE TITLE
mdInputContainer: ngMessages don't appear the first time until focus is removed from the element

### ISSUE THREAD

**Issue by richieforeman** [angular/material#6287]
ng-messages don't appear on an mdInputContainer if its the first time the user is interacting with the form element.  Once you blur the element, messages always appear consistently while typing.

Steps to dupe:
- Click in the input
- Type "333"
- (no ngMessages appear)
- Unfocus the element
- (messages appear)
- Focus the element
- blank out the previous text
- (messages appear)
- type "aaaaaaa"
- (messages appear)

http://codepen.io/richieforeman/pen/rxOgVz

Also, I'm a Googler - richieforeman@

**Comment by gligoran** [comment]
+1

**Comment by michaelkrog** [comment]
Dublet of https://github.com/angular/material/issues/5837?

**Comment by richieforeman** [comment]
@michaelkrog I think you're right :)

**Comment by topherfangio** [comment]
Indeed, this is a duplicate. You'll need to add `md-auto-hide="false"` or `ng-show="true"` to your messages to turn off the new auto-hiding capabilities (this was added per the guidelines in the official spec).
