### ISSUE TITLE
1.0.0-rc7 broken multi select menus

### ISSUE THREAD

**Issue by enpfeff** [angular/material#6289]
Multi-select menus do not grow in size to display a comma seperated lists as they did in previous versions.  

http://codepen.io/anon/pen/XXmwqY

![image](https://cloud.githubusercontent.com/assets/7192978/11787708/7341edde-a24a-11e5-9605-2c5ac8f15850.png)

**Comment by rschmukler** [comment]
This was fixed in https://github.com/angular/material/commit/2ab30758ec451383ef03d234ffc729517afb92e3
