### ISSUE TITLE
md-tabs(static-tabs): Tabs and content becoming invisible on ios safari

### ISSUE THREAD

**Issue by epelc** [angular/material#6290]
The static tabs demo(and if you use the method in your own app) of rendering content outside of the tabs is very buggy on ios safari(I couldn't reproduce on os x but it always shows on ios). The tabs partially become invisible and the tab content totally disappears. I'm not sure why and it has been like this for a while.

See the `static tabs` demo here at the very bottom (here)[https://material.angularjs.org/latest/demo/tabs] on ios using safari(I'm not sure if it affects ipads but it definitely affects iphones).

This is what it looks like sometimes when loading but most of the time after you switch tabs(note you may have to switch multiple times to see it). It requires a refresh of the page once this happens no matter what.
![img_0262](https://cloud.githubusercontent.com/assets/5204642/11787901/32d57984-a25c-11e5-9f20-ecc2b966b031.PNG)

Tested on an iphone 6s running ios 9.2
Note it does not show up in os x safari

**Comment by scottreisdorf** [comment]
this could be related to the bug i found:
https://github.com/angular/material/issues/6212
try modifying the source code as described in the issue above and see if it fixes it

**Comment by epelc** [comment]
I don't think that issue is related. This causes more of a rendering issue covering your content even though it is outside of the tabs container. It also screws up the whole tab switcher.

I have to test it some more but I found Some references to WebKit having some issues with position fixed sometimes. I'm not so if tabs uses this so I have to look into it more.

**Comment by tamsler** [comment]
I think this is a duplicate of https://github.com/angular/material/issues/4477

This seemed to work around the 1.0.0 release but it's definitely broken again. I did some testing with an iOS simulator and remote debugging and setting the focus attribute on any content item makes the content show up again.
