### ISSUE TITLE
Add "no conflicts" layout option to layout to add `md-` prefixes.

### ISSUE THREAD

**Issue by jelbourn** [angular/material#6294]
We should add a "no conflicts" configuration option to allow people to use the layout module without the attributes conflicting with other `layout` attributes by adding an `md-` prefix to everything.

cc @ThomasBurleson

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
