### ISSUE TITLE
md-select multiple label on top of default placeholder

### ISSUE THREAD

**Issue by matanh-tzmedical** [angular/material#6295]
When adding items to a multiple md-select and then removing all items, a default placeholder shows up and gets obscured by the explicit label.

http://codepen.io/anon/pen/KVdjYJ

![image](https://cloud.githubusercontent.com/assets/11762657/11791149/8adf27f4-a254-11e5-90e3-4a078c8d21c5.png)

**Comment by DevVersion** [comment]
See #6207

**Comment by matanh-tzmedical** [comment]
Thank you.
