### ISSUE TITLE
md-input textarea auto grow is broken

### ISSUE THREAD

**Issue by mmatheson1** [angular/material#6296]
It's working in the 0.11.0 demo:
https://material.angularjs.org/0.11.0/#/demo/material.components.input

but broken in the 1.0.0 demo: 
https://material.angularjs.org/latest/demo/input

**Comment by mckenzielong** [comment]
Looks like it is related to 7fe6f87bb3ecd1d3bc913c19b35eba3273a2ea03? I am guessing the desired behaviour here was to have the textarea stay at however many rows? Or is it supposed to grow up to however many rows then shrink back down to 1?

Keep in mind the demo itself changed to include the rows attribute too.

I haven't had a chance to test this, but this looks like the reason it grows: `var rows = Math.min(min_rows, Math.round(node.scrollHeight / lineHeight));` was changed from `var rows = Math.max(min_rows, Math.round(node.scrollHeight / lineHeight));` The first call to growTextArea will set the rows attribute to 1.

As for why it doesn't shrink, think the client height doesn't get recalculated on delete? So again it will default to `min_rows`.

**Comment by mmatheson1** [comment]
A ngMat team member reached out to me. Seems the behaviour has been purposely changed to grow from 1 row to rows value, rather than starting at rows value and growing indefinitely.

He mentioned the not shrinking afterward is a known issue.

**Comment by DevVersion** [comment]
This issue is fixed in a extended fix. See #5757 and check it out.

**Comment by DevVersion** [comment]
@crisbeto already fixed that issue in #7649 and we're currently working on some textarea improvements here: #7649
