### ISSUE TITLE
FAB Speed Dial starting visible

### ISSUE THREAD

**Issue by trevorade** [angular/material#6299]
You can see this pretty clearly in this demo:
https://material.angularjs.org/latest/demo/fabSpeedDial

Even though the speed dial isn't open, it visibly is shown as if it were.  Clicking on the trigger makes it officially open and the second click will close it.

**Comment by bunjiboys** [comment]
This is an issue with md-fling. If you use md-scale instead it works as intended, I've had to make that adjustment as well

**Comment by trevorade** [comment]
Thanks, looks like this issue repros with md-scale as well.  Good to know they fixed it.

**Comment by topherfangio** [comment]
Please see issues #6111 and #6344 for workarounds until a more permanent fix is provided.
