### ISSUE TITLE
Drag enable and position memory

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#63]
The popup service needs to be extended to support:

*  Drag-n-drop of the popup location
*  Save the last popup location and zoom-open subsequent openings `to` that location
*  Support zoom-open popup `from` a specified global position; with default fallback to screen center.

These features would make the popup extremely usable and versatile; especially with the `Material Design with Angular` Demos

**Comment by rschmukler** [comment]
Closing as a duplicate of #1206
