### ISSUE TITLE
IE11: Manual entry in md-datepicker leaves field always invalid. mindate/maxdate don't work. rc7

### ISSUE THREAD

**Issue by clydetacoma** [angular/material#6300]
You can see this behavior comparing the demo page in IE11 vs Chrome. https://material.angularjs.org/latest/demo/datepicker

Change the date to a date before the md-min-date or after the md-max-date.
Notice the error in IE11 never changes from "The entered value is not a date!"

**Comment by jelbourn** [comment]
@clydetacoma I think this has been fixed in 1.0. Are you still seeing an issue?

**Comment by clydetacoma** [comment]
@jelbourn It's been fixed now thanks!
