### ISSUE TITLE
md-input-container shows X in IE when focused

### ISSUE THREAD

**Issue by PeerInfinity** [angular/material#6303]
In Internet Explorer, when you click on an input box in an md-input-container, it will show an X in the right edge of the input box.  Clicking the X will deselect the input box.  This X is not displayed in other browsers.  This happens in all instances of md-input-container, including the ones in the demo page.  It's not a serious problem, but it's inconsistent between browsers, and takes up space in the input box.

**Comment by ccstevenson** [comment]
I don't believe this is specific to md-input-container. It's a style that IE applies to all text inputs. 

You can [remove it with a simple CSS rule.](
http://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs)

**Comment by EladBezalel** [comment]
@PeerInfinity @ccstevenson thanks for addressing this, this should be discussed

**Comment by Splaktar** [comment]
Was there a decision here? It seems like a simple fix. I can submit a PR, but want to confirm that it will be accepted first.
