### ISSUE TITLE
Extract the `layout...` attributes into a separate library

### ISSUE THREAD

**Issue by francoishill** [angular/material#6308]
The `layout="row"`, `layout-align="start center"` attributes are quite generic and does not require any angular or material code. So this could be extracted into a separate library. Refer to my library as I have done this temporarily to be used with other frameworks (like aurelia).

Here is my "extracted" code: https://github.com/francoishill/css3-flex-layout/blob/master/dist/main.css

**Comment by smashercosmo** [comment]
+1. Would be nice to have it in the separate package.

**Comment by Frank3K** [comment]
Do you mean [angular-material.layouts.css](https://github.com/angular/material/issues/5020#issuecomment-148344363)?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
