### ISSUE TITLE
value in input[text] with ng-value not automatically show

### ISSUE THREAD

**Issue by AhmadZuhdi** [angular/material#6309]
value in input[text] is not automatically show if value is set with ng-value, it need to focus first

![angular-material-ng-value-input-text](https://cloud.githubusercontent.com/assets/3438626/11805644/0dd96d54-a340-11e5-8c93-b099c16b0a9d.gif)

HTML
```html
<md-input-container>
  <label>Name (ng-value)</label>
  <input type="text" ng-value="name">
</md-input-container>
<md-input-container>
  <label>Name (ng-model)</label>
  <input type="text" ng-model="name">
</md-input-container>
<md-input-container>
  <label>Name (value)</label>
  <input type="text" value="John Doe">
</md-input-container>
```

Javascript
```javascript
$scope.name = 'Tasks';
```

versions
```
angular#1.4.8
angular-material#1.0.0-rc7
```

**Comment by joezirilli** [comment]
+1

**Comment by EladBezalel** [comment]
@AhmadZuhdi Can you please provide a codepen so we can investigate more?

**Comment by AhmadZuhdi** [comment]
@EladBezalel like this http://codepen.io/AhmadZuhdi/pen/wMdEyw ?

**Comment by EladBezalel** [comment]
yes thank you :) i'm on it..

**Comment by EladBezalel** [comment]
@AhmadZuhdi [ngValue](https://docs.angularjs.org/api/ng/directive/ngValue) shouldn't be used on text input.

**Comment by j86** [comment]
Thanks for getting round to this issue @EladBezalel . Do you have a suggestion how to pre-populate a text input if not using ngValue?

**Comment by EladBezalel** [comment]
controller is the best solution, ng-init might work as well
