### ISSUE TITLE
$mdMedia not always returning correct boolean value

### ISSUE THREAD

**Issue by samirgit** [angular/material#6310]
$mdMedia('gt-sm')  and $mdMedia('gt-md') always returning false
latest release 1.0.0

Note: this is true when using the un-minified version of angular-material

**Comment by XGHeaven** [comment]
I have same error with you...

**Comment by ThomasBurleson** [comment]
Please note:

*  `'gt-sm' : '(min-width: 960px)'`
*  `'gt-md' : '(min-width: 1280px)' `

What screen size are you testing on ? Which device ? Whenever possible, provide a CodePen demo.

---

To expedite resolution, please always test with the latest versions:
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).

**Comment by topherfangio** [comment]
If you can provide a Codepen demo of the issue you are experiencing and what browsers you are using, we will reopen.
