### ISSUE TITLE
multiple md-select issue still persist in 1.0.0

### ISSUE THREAD

**Issue by dohomi** [angular/material#6311]
Hello,

the ```md-select```still has ```multiple="true"```issue in 1.0.0:

http://codepen.io/anon/pen/Rrraew

If you deselect all fields the label overlay position is misplaced.

**Comment by dohomi** [comment]
<img width="449" alt="screen shot 2015-12-15 at 11 09 06" src="https://cloud.githubusercontent.com/assets/489221/11807781/4ee1b6fe-a31c-11e5-845d-b75cca59c6bd.png">

**Comment by TheRealBryon** [comment]
Then as soon as it loses focus, it seems to disappear

**Comment by jayeshanandani** [comment]
+1

**Comment by dohomi** [comment]
Could someone post any temporary fix for this issue? Would be great to see this fixed sometimes in 1.0.x release. Thanks

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (402/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:47230 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw2-001GOM-Tm
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:19 +0200
Date: Thu, 28 Apr 2016 12:46:33 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872793;
	bh=4dBUbL2R+G6jxoLr3EaBMfaEiK6jDaEpMYSxmEBHh0o=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=hiJ2Gj8LkufVLxBky725mVomSPcIyiofzajwksCJ3gZ3R0jMrir/9ADHlhHDmIMHQ
	 ujwn+ojf2ThpziSKWh9/MyWGrebJQtStIJqWVGPhz2MDmoWsOA6LHP8il/72cKSNwJ
	 VJDYqgtsZ4NOu6jzrgoOR6zgA/KxcfNRl54AnVLA=
