### ISSUE TITLE
md-autocomplete(1.0.0+): ng-messages are not shown

### ISSUE THREAD

**Issue by michaelkrog** [angular/material#6313]
I just tried creating a blank pen via the getting started page(release 1.0.0).

I then added the example with ngmessages from https://material.angularjs.org/latest/api/directive/mdAutocomplete. 
```html
<form name="autocompleteForm">
  <md-autocomplete required md-input-name="autocomplete" md-selected-item="selectedItem" md-search-text="searchText" md-items="item in getMatches(searchText)" md-item-text="item.display">
    <md-item-template>
      <span md-highlight-text="searchText">{{item.display}}</span>
    </md-item-template>
    <div ng-messages="autocompleteForm.autocomplete.$error">
      <div ng-message="required">This field is required</div>
    </div>
  </md-autocomplete>
</form>
```

But the ng-messages are completely removed from the DOM.
http://codepen.io/anon/pen/ZQQObj

**Comment by Nazanin1369** [comment]
@topherfangio Any one working on this? Can I go ahead?

**Comment by mimani** [comment]
@Nazanin1369 I have tried to fix this in this [PR](https://github.com/angular/material/pull/6419), Let me know if it seems OK.

**Comment by topherfangio** [comment]
@Nazanin1369 I am going to dig into this over the next day or two, but if you have any insights already, the knowledge would certainly be appreciated!

**Comment by iamisti** [comment]
@ThomasBurleson 
Maybe we should change the milestone to `1.0.3`, since the fix is not in `1.0.2`, right?
Can you guys give me some insights when this fix will be released?

**Comment by michaelkrog** [comment]
Updated pen to use 1.0.5, but it is still not possible to use ng-messages in autocomplete.
[The documentation](https://material.angularjs.org/latest/api/directive/mdAutocomplete) still states that it should be possible, but it is not.

New pen: http://codepen.io/anon/pen/obKBej

**Comment by chillyspoon** [comment]
This bug is visible in the 1.0.4 (the version I'm using) and 1.0.5 Angular Material demos - see attached. The state length error shows correctly but no amount of messing with a blank/null state value can prompt the "required" message to display.

![screenshot 2016-02-27 11 31 49](https://cloud.githubusercontent.com/assets/6490625/13372679/34a3022a-dd46-11e5-84c1-5b04fde5404b.png)
![screenshot 2016-02-27 11 31 54](https://cloud.githubusercontent.com/assets/6490625/13372678/34a256e0-dd46-11e5-87e5-0ad9def8fbb9.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
