### ISSUE TITLE
form layout/spacing between md-input-containers not consistent

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#6314]
https://github.com/angular/material/commit/cf7f21aa6c633d9f0bd22013e9a79f99b82b16af added an md-error-spacer on input containers with text inputs. Same is needed for selects/autocomplete etc.
Right now forms that are a little bit more complex then the demos have very inconsistent spacing between the rows.

Additionally the current mechanism with `md-block` doesn't work with well with layout rows, spacing is to high here as well.

Both issues displayed here: http://codepen.io/anon/pen/qbbaYX

**Comment by peio72** [comment]
+1

**Comment by xplodwild** [comment]
Already reported in #6412

**Comment by ThomasBurleson** [comment]
Duplicate
