### ISSUE TITLE
md-select : floating-label problem with layout=row

### ISSUE THREAD

**Issue by matcobat** [angular/material#6315]
I have a problem with md-select.
As you can see on this pen : http://codepen.io/anon/pen/NxxbrG
when you select the technical speciality "a", the floating label is partially hidden, because the select resize itself to stretch the content.

Have you got any solutions for this ? I tried to encapsulate in a div style="white-space: nowrap", but if I do so, the two labels are mixed together, as you can see on the second line.

Have you got any solution ?

**Comment by topherfangio** [comment]
There are a few different solutions. You could use the `flex="..."` attributes to define a particular flex width on the input container.

You could also use plain CSS to set the `min-width` property to something appropriate as I have done below:

http://codepen.io/topherfangio/pen/RrrVwE?editors=100
