### ISSUE TITLE
$mdDialog templateUrl broken

### ISSUE THREAD

**Issue by Forestdev** [angular/material#6316]
The $mdDialog templateUrl variable when assigned a correct HTML template loads the whole page instead of the template required.

This can be seen here. If you were to clone it, run `grunt serve`, login with the details provided on the login screen, and go to `/admin/create`

- [code](https://github.com/Forestdev/custom-portfolio)

the bit of code concerned:

`(function() {
  "use strict";

  class AdminCreateCtrl {
    constructor(Auth, $mdDialog, $mdMedia) {
      this.Auth = Auth;
      this.user = this.Auth.getCurrentUser();
      this.$mdDialog = $mdDialog;
      this.$mdMedia = $mdMedia;
    }

    showSettings($event) {
      this.$mdDialog.show({
        templateUrl: "/client/components/dialogs/color-settings-dialog.tmpl.html",
        targetEvent: $event,
        clickOutsideToClose:true,
        fullscreen: this.$mdMedia('sm')
      })
      .then(function(answer) {
      }, function() {
      });
    }
  }

  angular.module("trustPilotCvApp")
    .controller("AdminCreateCtrl", AdminCreateCtrl);
})();
`

**Comment by topherfangio** [comment]
@Forestdev Can you please provide a minimal Codepen that demonstrates the issue so that we can test more easily.

**Comment by Forestdev** [comment]
Sure, I'll attempt that later in the day.

**Comment by Forestdev** [comment]
Cannot reproduce this in Codepen. I suppose the issue is on my end. It's just really weird that the template doesn't get loaded in, instead the whole `index.html` page gets loaded. However, the controller fires just fine.

**Comment by Forestdev** [comment]
Alright, so it seems it's only an issue if it tries to load from a localhost url. If I try and load any external source, like another website, it works just fine.
