### ISSUE TITLE
md-list-item with href or ng-click have different margin

### ISSUE THREAD

**Issue by XGHeaven** [angular/material#6317]
`md-list-item` with href have external margin value.
![image](https://cloud.githubusercontent.com/assets/9291212/11815320/19aa7a7e-a386-11e5-99eb-0101e80cc1bb.png)
`md-list-item` with `ng-click` will create a `button` element.
That element with `md-button.md-no-style` to remove margin value.
![image](https://cloud.githubusercontent.com/assets/9291212/11815339/326e1db8-a386-11e5-927e-8beb20297c93.png)
But it's with `href` doesn't remove it.

I suppose add a css called `a.md-no-style` to remove margin value inherit from `md-button`

**Comment by ripper2hl** [comment]
Same problem with ng-href on md-list. :+1: check this :


![md-list-item](https://cloud.githubusercontent.com/assets/2611201/12026104/3db0e0c6-ad7b-11e5-9a69-4f7f31890301.PNG)
