### ISSUE TITLE
md-select bad positionning when selected item is in the bottom of the list

### ISSUE THREAD

**Issue by matcobat** [angular/material#6318]
![image](https://cloud.githubusercontent.com/assets/10220538/11816324/c7385402-a347-11e5-8903-6253ae48426c.png)

![image](https://cloud.githubusercontent.com/assets/10220538/11816587/fd990144-a348-11e5-96e8-dc0254725e94.png)

As you can see on this example from the official website, there is a big problem in the md-select position...

**Comment by matcobat** [comment]
Note that there is no problem on version 0.11.4

**Comment by murphmar** [comment]
Discussed here as well:

https://github.com/angular/material/issues/6190#issuecomment-163985721

**Comment by topherfangio** [comment]
Closing in favor of #6190.
