### ISSUE TITLE
mdMenu and mdMenuBar should work with ngRepeat

### ISSUE THREAD

**Issue by jztein** [angular/material#6320]
Currently, the mdMenu directive labels the nest level of child menus during compile time, before ngRepeated child menus are created. So, the nest level of those menus will always be 0. Opening and closing menus thus becomes buggy for 3-and-higher-leveled cascaded menus.

**Comment by jelbourn** [comment]
@jztein could you add a code snippet that would demonstrate the issue (or, even better something like a CodePen)?

cc @rschmukler

**Comment by jztein** [comment]
It's hard to demo in codepen since there's another mdMenu issue (https://github.com/angular/material/pull/6261 would fix #6184)

But here's a html snippet:
```
<md-menu-bar>
. . .
<md-menu>
  <md-button ng-click="$mdOpenMenu($event)">
    Demo
  </md-button>
  <md-menu-content>
    <md-menu-item ng-repeat="level2Name in ctrl.secondLevel">
      <md-menu>
        <md-button ng-click="$mdOpenMenu($event)" md-prevent-close-menu="true">
          {{ level2Name }}
        </md-button>
        <md-menu-content>
          <md-menu-item ng-repeat="level3Name in ctrl.thirdLevel">
            <md-button ng-click="console.log('hello, ', level3Name)" md-prevent-close-menu="true">
              {{level3Name}}
            </md-button>
          </md-menu-item>
        </md-menu-content>
      </md-menu>
    </md-menu-item>
  </md-menu-content>
</md-menu>
</md-menu-bar>
```

**Comment by cmacdonnacha** [comment]
+1

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (410/400 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:47677 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw4-001GPW-5G
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:22 +0200
Date: Thu, 28 Apr 2016 12:47:09 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872829;
	bh=kN+7FznbGwDlv2tWWPbQzm63FeA+AMS/C8FZ9AQdZkc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Zgg3i5V4BU2KG/XYwVnp3RkSCekFJe2M94BvcQIGkas7PWjQv9yaKdHd3UW1qqsJq
	 62SfnMB+yCDNyBrgvgZygQs01DGKBmD24ynlx36uFtdHez9lLrvTb6VE4Iwx8yuFdr
	 SKZQum/dOEk+NkqSTzh4w0F7ZgDBpQvOkPO7RzTw=
