### ISSUE TITLE
Dialog jumps out of view on focus on mobile.

### ISSUE THREAD

**Issue by greim** [angular/material#6321]
I've been testing on iOS 9 on an iPhone 6. I saw it happen inconsistently in mobile Safari, but more consistently inside a UIWebView.

When launching a dialog on a page that has been scrolled far down, it positions itself in the viewport, but when focusing a textarea inside of the dialog, the keyboard pops up and the dialog re-positions itself outside of the viewport, up higher on the page. Sometimes you can still see part of the dialog, sometimes it disappears completely out of view. Presumably it's calculating the `top` position wrong?

https://github.com/angular/material/blob/v1.0.0/src/components/dialog/dialog.js#L940

Out of curiosity, why do material dialogs use abs positioning and then reset `top` on the fly, instead of  using fixed positioning and leaving `top` zero? It fixes it on our end if we add this our own CSS:

```
.md-dialog-container {
  position:fixed!important;
  top:0!important;
}
```

**Comment by greim** [comment]
@Baldauf

**Comment by Wardormeur** [comment]
Agreed, have the same issue on Adnroid default browser.
I suspect the size is based upon the total size instead of the available size (when keyboard is open), and once the keyboard disappears, doesn't resize.
