### ISSUE TITLE
datepicker: arrow has grey circle after closing the date picker

### ISSUE THREAD

**Issue by cvwilliams** [angular/material#6322]
The datepicker arrow icon has the grey circle ripple after closing the dialog until something else on the screen is selected. There is an example below:

<img width="378" alt="datepicker_bug" src="https://cloud.githubusercontent.com/assets/3373804/11822069/b7ba56b8-a33a-11e5-846b-375f5a2bc54e.png">

**Comment by marcysutton** [comment]
It must be maintaining focus after clicking.

**Comment by jelbourn** [comment]
@cvwilliams That is the focus indicator and as of now it is intentional. I can consult with our UX designers to see if they have any ideas about polishing it.
