### ISSUE TITLE
md-bottom-sheet: some scrolling on desktop browser

### ISSUE THREAD

**Issue by florent1933** [angular/material#6323]
<img width="1280" alt="capture d ecran 2015-12-15 a 17 36 52" src="https://cloud.githubusercontent.com/assets/3958123/11816917/e33ec1ee-a352-11e5-8848-85ecec8cc74d.png">

Even the code from the example: http://codepen.io/anon/pen/xZZrJx

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
