### ISSUE TITLE
md-datepicker with ng-disabled 

### ISSUE THREAD

**Issue by fabiusss** [angular/material#6324]
when I use the property ng-disabled component does not respond properly.

**Comment by jabraok** [comment]
+1

**Comment by guanjinke** [comment]
+1

发自我的 iPhone

**Comment by jelbourn** [comment]
@fabiusss I'm closing this issue for lack of further info. Please file issues with more details- either steps to reproduce, code samples, or something like a CodePen reproduction. The disabled example in the [demo](https://material.angularjs.org/latest/demo/datepicker) is working, so I would need further information.
