### ISSUE TITLE
md-autocomplete not showing error messages

### ISSUE THREAD

**Issue by dnd** [angular/material#6326]
This issue was mentioned by @michaelkrog in issue #5837. That issue was closed, so I am opening this one.

Errors do not show for `md-autocomplete` even after being touched. Michael's pen that demonstrates this can be found here: http://codepen.io/anon/pen/yeLPVy 

I am still experiencing this problem with the latest master 00ce3bea10.

**Comment by michaelkrog** [comment]
Hey. Already created an issue.  :) 
Dublet of https://github.com/angular/material/issues/6313
