### ISSUE TITLE
OMG the chips, what is going on with the chips?!

### ISSUE THREAD

**Issue by secretgspot** [angular/material#6327]
appears when compiled with grunt for /dist  chips readonly property doesn't compile or gets included and end result always displays secondary-placeholder

on local machine while in dev mode when readonly enabled none of the placeholders are visible but if I run a site from dist after compiling for production it shows placeholders at all times

**Comment by RobertBaron** [comment]
Hi,

That happen to me too, that is not the angular material itself , check that you don't have the
collapseBooleanAttributes set to true, if so set it to false on your grunt file.
What happens is that if you compiled with that flag set it to true, it will print your html as readonly without the value of the scope you want to check readonly="scope_var" and the readonly prop needs a value to handle that!
