### ISSUE TITLE
Inconsistent input label animation speeds

### ISSUE THREAD

**Issue by apokusin** [angular/material#6328]
An input's floating label animation is quicker when using a `label` tag compared to just setting the `placeholder` attribute.

![Example](http://pokus.in/12510.gif)

**Comment by tjlav5** [comment]
@apokusin a quick update to the CSS resulted in this: http://codepen.io/anon/pen/RradMW

Let me know if that if that fixes it for you.

Cheers

**Comment by ThomasBurleson** [comment]
@topherfangio - can you review this with the spec and validate?
