### ISSUE TITLE
Using ngMessages as an element prevents input from being focused

### ISSUE THREAD

**Issue by wthomsen** [angular/material#6329]
When using ngMessages as an element (`<ng-messages for="...">` vs `<div ng-messages="...">`) the input can no longer be focused (via click) after it displays an error message:

http://codepen.io/anon/pen/addLGj

**Comment by topherfangio** [comment]
It looks like there is definitely an issue with the fact that `ng-messages` as a tag name doesn't have some styles specified.

Can you please try adding the following to see if it provides a quick fix?

```css
md-input-container ng-messages {
  display: block;
}
```

We definitely need to test this more before putting it directly in our CSS.

**Comment by wthomsen** [comment]
That style declaration does fix it. It was working fine on 0.11.2 and only showed up in my move to 1.0.0. There must've been some other additional style added that exposed the issue. Thanks.

**Comment by topherfangio** [comment]
Thanks for the update. I've assigned it to our next milestone to see if we can simply use that CSS or if we'll need a better fix.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
