### ISSUE TITLE
demos - 'Edit on CodePen' feature doesn't work for v1.0.0

### ISSUE THREAD

**Issue by sazonenka** [angular/material#6330]
https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0/angular-material.js returns 'Not Found'.
This breaks CodePen snippets for v1.0.0 demos.

**Comment by FrancescoRizzi** [comment]
Which codepen or sample did you get that from?

I think the codepen samples are (supposed to) use files from ajax.googleapis.com.

Here's [an example](http://codepen.io/team/AngularMaterial/pen/RrbXyW?editors=101)
This is linked to from [Getting Started](https://material.angularjs.org/latest/getting-started) (Build a Material Application (blank shell -> Edit on Codepen)
and it uses

    <script src="http://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.js"></script>

[Another example](http://codepen.io/team/AngularMaterial/pen/WvMeMQ?editors=101)
This is one of the templates found from the [Codepen Community](http://codepen.io/team/AngularMaterial/)
and it uses (HTML > Settings > JavaScript)

    https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.js

**Comment by sazonenka** [comment]
@FrancescoRizzi The [gitcdn link](https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0/angular-material.js) still doesn't work for me. Response has 200 status code, but has only `Not Found` string instead of JS code.

These are the steps how I get to broken CodePen samples:

1. Go to https://material.angularjs.org/latest/demo/input
1. Click on `Edit on CodePen` icon that is located on the right side of `Basic Usage` toolbar

**Comment by ThomasBurleson** [comment]
Working now.

**Comment by epelc** [comment]
@ThomasBurleson Can you take a look at #6343 it's partially broken still

**Comment by sazonenka** [comment]
Doesn't work for me.

CodePen samples from [latest](https://material.angularjs.org/latest/demo/input) demos still use broken [gitcdn link](https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0/angular-material.js)

However, CodePen samples from [HEAD](https://material.angularjs.org/HEAD/demo/input) demos seem to work because they are using different [library link](https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-master-b8a9624/angular-material.js)
