### ISSUE TITLE
md-menu-bar consecutive menu options with child menus don't open

### ISSUE THREAD

**Issue by jraadt** [angular/material#6333]
@rschmukler - The fix you made in https://github.com/angular/material/issues/6184 fixed that problem (thanks for doing that so quickly!), but I believe it has caused a new bug now.  If you have multiple menu options that have child menus, one after the other, then only every other child menu opens.

In the following codepen under the File menu I have options New1, New2, and New3 that all have child options.  Mouse over them in order and you'll see only New1 and New3 child menus open.  However, if you start with New2, then that will open and New3 wont open.

http://codepen.io/anon/pen/YwweKO

**Comment by chrisconover** [comment]
+1. I think this might be related to the transition for the sub menu.

I notice that whenever that sub menu's transition hasn't finished (it's still fading out) and I hover over another option with children it won't trigger. If I start on an option that has no children, therefore no transition, and move to an option with children, the sub menu is shown correctly.

**Comment by jraadt** [comment]
@chrisconover Yep that seems to be it.  Not sure what the fix is, but that seems to be the issue.

**Comment by chrisconover** [comment]
@rschmukler since you recently touched this code, does this seem like a reasonable theory for the problem?

**Comment by chrisconover** [comment]
@ThomasBurleson any chance someone will be able to take a quick look at this?

**Comment by hulyav** [comment]
+1

**Comment by daviian** [comment]
#7019 seems to be the same problem.
