### ISSUE TITLE
.layout-padding adds padding to all immediate children

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material#6334]
According to the [documentation](https://material.angularjs.org/latest/layout/options):
> layout-padding adds padding inside each flex child. It also adds padding to the layout container itself.

However, it seems that material css has the following rule:

```
.layout-padding > * {
    padding: 8px;
}
```
... which make all immediate children get the padding - not only the flex children.

Also, what is the reason to apply padding to flex children? Would not it be more flexible if it was left to the discretion of the developer to decide whether the flex element should have padding or not?

**Comment by germanferrero** [comment]
I'm facing the same problem in latest release. Also in 1.0.0-rc2 breaking changes we have: "layout-margin and layout-padding styles will apply to all children of layout=row and layout=column". But documentation has not been updated in this point.

**Comment by germanferrero** [comment]
http://codepen.io/germanferrero/pen/EPgNvg

Here is a codepen. please take a look.

**Comment by Asoseil** [comment]
same problem on 1.0.1

**Comment by parky128** [comment]
On the flip side, are there any plans to have layout directives that allow for only child items to have padding and not the parent container?

**Comment by jeffthompson1971** [comment]
fsfs

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by jeffthompson1971** [comment]
Hi angular/material,

I'd like to add you to my professional network on LinkedIn.

- Jeffrey

Confirm that you know Jeffrey: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=asFVxrQ5&invitationId=6184839338900152320&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eitev8msz%7E8i








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-itev8msz-8i&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHTPYXMu_rcfwAAAVdT2vY7Go56Qwjw5ur7qJuW6qlBqTy0i6gg8UC1B6civrEj6v6AurEXDf4zojmY5pRCWw6xyNHBagCnHM5BgsVGKHnHyuw04gCUGtxIbpKBZimfK4I0DBuizpCXxG3KyHolunVzP1Ed_2ohaQjoFg0q2Sdhmqzh4fS_kFVByJtYSI0NanRF&eid=0-itev8msz-8i


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-itev8msz-8i&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by DmitryEfimenko** [comment]
wtf is this?

**Comment by jeffthompson1971** [comment]
Jeffrey Thompson would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=asFVxrQ5&invitationId=6184839338900152320&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-r3olkr%7Eitndakpz%7Ed4

View Jeffrey Thompson&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=asFVxrQ5&invitationId=6184839338900152320&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-r3olkr%7Eitndakpz%7Ed4





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=r3olkr-itndakpz-d4&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=r3olkr-itndakpz-d4&loid=AQEZgeYhPbwNrwAAAVdzQPKiKjKVAwrw6vrkXi6joYzl8gWv183XgK9EWEFVFaru_CtXzdPhMwugo-r14Q0MbFNcYIl1UEoqKdokSiHb1JP38M2jvSl8R5HMawOj9sIyk6qLRk77ukFGg2bbDBZt8OmJ4Ckl21e41Wuoq3Iy986pSbTgvwu3JtaXjEFYDqgPNiTp

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=r3olkr-itndakpz-d4&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
