### ISSUE TITLE
.md-errors-spacer visible on toolbar

### ISSUE THREAD

**Issue by pc3b3r** [angular/material#6338]
Consider this CodePen:

http://codepen.io/pc3b3r/pen/obbdgY

the .md-errors-spacer element is visible even if there are no errors/hints.

**Comment by xplodwild** [comment]
Duplicate of #6214

**Comment by stewones** [comment]
+1

**Comment by topherfangio** [comment]
Work is currently being done in #6209 to address this.

**Comment by mathiasmoeller** [comment]
+1

**Comment by elekzalan** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
