### ISSUE TITLE
md-dialog duplicating IDs

### ISSUE THREAD

**Issue by berikin** [angular/material#6339]
Consider this CodePen:

http://codepen.io/berikin/pen/gPPzRK

When the md-dialog is created, his child md-dialog-content receives the same id of the parent.

![Duplicated id](https://cloud.githubusercontent.com/assets/1564947/11837242/e811fc30-a3df-11e5-9797-ae3ee51aadfb.png)

Even if we force a different id for md-dialog-content, as seen in this CodePen:

http://codepen.io/berikin/pen/JGGvyE

**Comment by DevVersion** [comment]
Yes that seems to be an issue. The problem is caused [here](https://github.com/DevVersion/material/blob/0a7ded9ef157454f069c06d0aaf0cabbfc884cb3/src/components/dialog/dialog.js#L845). 
And this line makes no sense, because this will always cause duplicate `id` (if specified)
