### ISSUE TITLE
Form elements are not aligned after moving from material 0.11.4 to 1.0.0

### ISSUE THREAD

**Issue by nareshbhatia** [angular/material#6340]
I can't figure out from the examples what has changed that is causing form elements to no longer align. Here's my code for a form within a dialog that used to work perfectly fine with 0.11.4. The real issue behind this issue is that there is really no documentation for CSS classes in Angular Material. For example, in the `input` example, the class `md-inline-form` has been used. I cannot tell what this class does or is this what is affecting the alignment. I have to figure out all this by trial and error. Also my use case is that of a form inside a dialog, which is very common. There is no example of this use case.

    <md-dialog>

        <form name="loginForm" data-ng-submit="vm.handleSubmit()">

            <md-toolbar>
                <div class="md-toolbar-tools">
                    <h2>Login</h2>
                    <span flex></span>
                    <md-button type="button" class="md-icon-button" ng-click="vm.handleCancel(); $event.stopPropagation();">
                        <md-icon md-svg-icon="navigation:close" aria-label="Close dialog"></md-icon>
                    </md-button>
                </div>
            </md-toolbar>

            <md-dialog-content class="md-padding">

                <md-input-container>
                    <label>Username:</label>
                    <input ng-model="vm.username" required>
                </md-input-container>

                <md-input-container>
                    <label>Password:</label>
                    <input ng-model="vm.password" type="password" required>
                </md-input-container>

                <div class="md-actions">
                    <md-button type="submit" class="md-primary"
                               ng-class="{'md-raised md-hue-1': (loginForm.$dirty && loginForm.$valid) }"
                               aria-label="OK">OK</md-button>

                    <md-button type="button" ng-click="vm.handleCancel(); $event.stopPropagation();"
                               aria-label="Cancel">Cancel</md-button>
                </div>
            </md-dialog-content>

        </form>

    </md-dialog>

The full working code is here: https://github.com/archfirst/angular-material-template/tree/master/src/components/login

**Comment by ThomasBurleson** [comment]
Whenever possible, provide a CodePen demo.

---

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).

**Comment by nareshbhatia** [comment]
As requested, here are the CodePen examples:

- Using Material 0.11.4: http://codepen.io/nareshbhatia/pen/dGGExE

- Using Material 1.0.0: http://codepen.io/nareshbhatia/pen/qbZjXG

There are zero changes in code. The only difference is that they are using different versions of Angular Material. The first version has username and password field nicely aligned vertically. The second version has lost this alignment.

**Comment by hewaroth** [comment]
Inline:
```
    <div layout="row">
        <md-input-container>
                <label>Username:</label>
                <input ng-model="vm.username" required>
            </md-input-container>

            <md-input-container>
                <label>Password:</label>
                <input ng-model="vm.password" type="password" required>
            </md-input-container>
    </div>
```
or block:
```
            <md-input-container class="md-block">
                <label>Username:</label>
                <input ng-model="vm.username" required>
            </md-input-container>

            <md-input-container class="md-block">
                <label>Password:</label>
                <input ng-model="vm.password" type="password" required>
            </md-input-container>
```

**Comment by nareshbhatia** [comment]
@hewaroth, thanks so much for your help.

I hope the larger point I was trying to make is obvious. Without good documentation of the CSS classes, I assume many devs will be wasting their time fumbling around for the right approach. In this case, there was no easy way for me to discover the "md-block" class and know what its purpose was. Is the documentation of CSS classes on a to-do list somewhere?

Also I would like to request the inclusion of my example in the standard example set. I see separate examples of forms and dialogs, but nothing that combines the two. This is an important use case. It is specially tricky because the form and dialog directives are nested within each other, at least the way I have coded it. So it is important for the material team to review my code before including it in the standard example set, if you choose to do so.

Please let me know if I need to open new issue(s) for this and/or help in any other way.
