### ISSUE TITLE
md-autocomplete not rendering html in md-floating-label

### ISSUE THREAD

**Issue by syedmfaizan** [angular/material#6341]
md-floating-label expects a string, when a html is passed, it encodes all the special characters(i,e. <,>) into html entities and then show's it up.

I wanted to put a red star along with the label in md-autocomplete to give it a required look. but it just pushed the code on the screen.

md-floating-label should work in a way which takes html and renders it within the autocomplete.

http://codepen.io/anon/pen/rxxKEK

**Comment by ThomasBurleson** [comment]
Will not fix.
