### ISSUE TITLE
md-tabs:md-enable-disconnect doesn't work

### ISSUE THREAD

**Issue by Hotell** [angular/material#6342]
`md-enable-disconnect` doesn't render tab content lazy via ngIf.

all content is rendered on boot and not destroyed on tab change.

demo includes a component which is inside `md-tab` and should console.log on scope `$destroy`, which is unfortunately never called.

demo:
http://codepen.io/Hotell/pen/QyyKjY?editors=101

**Comment by krasevych** [comment]
I have the same problem(
