### ISSUE TITLE
Error in the documentation in "Extra Options"

### ISSUE THREAD

**Issue by ekaitzht** [angular/material#6345]
Hi, Is this a error in the documentation? All are show but one is hide.

![2015-12-16_1605](https://cloud.githubusercontent.com/assets/3002311/11844443/17ae2750-a40f-11e5-8e9b-8e1f3c511357.png)

**Comment by topherfangio** [comment]
@ThomasBurleson Is there a reason this is assigned to me even though there is a PR to fix it? I put an "LGTM" on the PR in case that is what was needed.
