### ISSUE TITLE
md-button not rendering below initial page area until hovered over

### ISSUE THREAD

**Issue by jaGarcia** [angular/material#6347]
Very peculiar, and I don't seem to see any classes flashing in the "Element" inspector when I hover over them to make them visible.  Has any one experienced this?  We're currently using (migrating away from) foundation for Apps so I'm suspicious that it may be some sort of layout collision but I'm stumped at the moment. 

![screen shot 2015-12-16 at 10 19 30 am](https://cloud.githubusercontent.com/assets/354362/11844819/b445dac6-a3de-11e5-9d8d-f097ec99c635.png)
![screen shot 2015-12-16 at 10 19 20 am](https://cloud.githubusercontent.com/assets/354362/11844820/b44b21d4-a3de-11e5-83d2-d2405a0688da.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
