### ISSUE TITLE
md-ink-riple leaking

### ISSUE THREAD

**Issue by rochapablo** [angular/material#6350]
I'm using the last version of material, and at the menu my md-ink-riple is leaking the md-item-content.

```
<md-item ng-repeat="item in menu">
    <a href="#/{{item.link}}">
        <md-item-content md-ink-ripple layout="row" layout-align="start center" style="background-color:red;overflow:hidden;">
            <div class="inset">
                <ng-md-icon icon="{{item.icon}}"></ng-md-icon>
            </div>
            <div class="inset">{{item.title}}</div>
        </md-item-content>
    </a>
</md-item>
```

I have already disabled my css, loading only the original, but nothing.

Also, I've tried disable using md-ink-ripple="false", but nothing changed.

**Comment by rochapablo** [comment]
I think I got it. 

```
.layout-row
```

is missing

```
position: relative;
```

Is that right?

**Comment by topherfangio** [comment]
Can you please provide a Codepen demo of the issue?

Also, these kinds of issues can typically be resolved by wrapping the inner contents of your content (`md-item-content` in this case) with a div containing the layout attributes (since the div has a display of block).

**Comment by rochapablo** [comment]
@topherfangio, I'm sorry.

I'm working in another project. You can close this issue and if the problem occurs I share a demo.

Thank you for your time.

**Comment by topherfangio** [comment]
@rochapablo Thanks! And good luck on your other project!

**Comment by jeson114** [comment]
+1
