### ISSUE TITLE
md-select missing md-errors-spacer

### ISSUE THREAD

**Issue by johnSowingo** [angular/material#6351]
When md-select contains ng-messages, there is no md-errors-spacer. 

This causes the height to change when the error is shown  (shifting everything down).

This is occuring in your example as well: http://codepen.io/anon/pen/qbbvaG

**Comment by epelc** [comment]
+1 this screws up alignment of some forms in 1.0.0

**Comment by vrosa** [comment]
+1

**Comment by nurp** [comment]
I didn't add any error handling but my form looks weird because of missing md-errors-spacer under md-select (I guess).
http://codepen.io/anon/pen/RrRJvE

**Comment by hewaroth** [comment]
@nurp yes you are right. You can add ```<div class="md-errors-spacer"></div>```.

**Comment by pdore-netfore** [comment]
+1

**Comment by bojancai** [comment]
+1 have to add <div class="md-errors-spacer"></div> for workaround

**Comment by bojancai** [comment]
+1

**Comment by bostondv** [comment]
+1

**Comment by mangrish** [comment]
+1

**Comment by oldirony** [comment]
+1

**Comment by juanpujol** [comment]
+1

**Comment by fyodorvi** [comment]
+1

**Comment by brunocabezas** [comment]
+1

**Comment by nestorbritez** [comment]
+1

**Comment by jpolo** [comment]
I am having many issues with md-errors-spacer in general. For some components it is not displayed. For some other cases such as composed input (i.e. ngModel based directive with multiple input, select, checkbox inside) it is displayed inside the directive and breaks the layout.

**Comment by mattdanna** [comment]
Yeah it's definitely inconsistent. I get different behavior if it's in a `<md-input-container>` vs. standalone.

**Comment by fmalk** [comment]
+1
Trying to put two `<md-input-container>` together, first with `<input>` has the `<md-errors-spacer>`, second with `<select>` doesn't have it, so vertical alignment is off

**Comment by fmalk** [comment]
To be fair, https://github.com/angular/material/issues/6214 has a valid workaround

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by johnSowingo** [comment]
Under which reason is this issue being closed?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (425/400 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:44146 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avs1i-001OKW-96
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:55:09 +0200
Date: Thu, 28 Apr 2016 12:54:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461873264;
	bh=3e8TKximodf29yRsWOyMbA4RQdG9jSWNh/ApSzIlH+Q=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=t5YqFlUQvFNyFkIASYiFPHIceARhwRRhCWpyOzn88wyoNS5l6KX+EEbuhWEaHh/lx
	 F9ZGhPoRb9+knHHAiYP5n1gW4mAQR3Cn+Czda9VR1xLshXmpNf3NR//+2x7WBYmCdi
	 wR1V7JigZGngScw48aqcklx30S43fXLKxDMe/qDI=

**Comment by stephengardner** [comment]
WOW it's been a while.  This is seriously still open?  You can just add a custom directive to put an errors spacer in... Perhaps I'll throw that together and submit it. 
But really?

**Comment by stephengardner** [comment]
Extend the md-select directive and add the spacer to all of them so you don't have to sweat it.

```typescript
module mdSelectDirective {
    function mdSelectDirective(): ng.IDirective {
        return {
            restrict: 'E',
            link: (scope: ng.IScope, element: ng.IAugmentedJQuery, attrs: ng.IAttributes): void => {
                element.after('<div class="md-errors-spacer"></div>');
            }
        }
    }
    angular.module('myApp').directive('mdSelect', mdSelectDirective);
}
```
