### ISSUE TITLE
Button tooltip does not disappear after click

### ISSUE THREAD

**Issue by chet-manley** [angular/material#6355]
http://codepen.io/anon/pen/OMVBRN
NG v1.4.8
MD v1.0.0

Issue:
Click button. Mouse out, then hover over button again. Tooltip is permanently displayed until focus changes. 

Expected:
Tooltip should always disappear on mouseout event.

**Comment by antoinebrault** [comment]
+1

**Comment by Nadenson** [comment]
You can add md-autohide to your md-tooltip

Here the fixed codepen : http://codepen.io/anon/pen/xZompL

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
