### ISSUE TITLE
md-select label is not dynamically updated properly

### ISSUE THREAD

**Issue by vrosa** [angular/material#6356]
When the label of a ```md-select``` is dynamically updated via data binding it doesn't actually render correctly until you open the select dialog and close it.

You can see the behaviour in action here: [http://codepen.io/vrosa/pen/BjjYZy](http://codepen.io/vrosa/pen/BjjYZy)

Make a selection on the first ```md-select``` and notice that the label for the input field is properly updated, whereas you need to click the second ```md-select``` and close it to make it work.

I know [4f3c5d91](https://github.com/angular/material/commit/4f3c5d91) solved related issues but not this specific one.

**Comment by baelter** [comment]
+1

**Comment by baelter** [comment]
FYI. The ```<label>``` is updated but not the ```aria-label``` or ```<md-select-value>```
