### ISSUE TITLE
md-subheader + md-radio-button

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6357]
v1.
chrome.

when clicking on a radio button, the scroll jumps and the subheader starts to move.

![untitled screencast](https://cloud.githubusercontent.com/assets/5133412/11860614/cffbbe70-a433-11e5-8ca4-e134bd1af202.gif)

```
md-dialog
	md-toolbar
		div.md-toolbar-tools
			h1
				| Filter

	md-dialog-content(layout='column'
							layout-align='start center'
							layout-fill=''
							flex='')

		md-content(	flex=''
						layout='column'
						layout-fill='')

			section
				md-subheader
					strong
						| Property Type

				div(	layout='row'
						layout-align='center start'
						layout-fill=''
						flex='')
				
					md-radio-group(ng-model='filterCtrl.propertyType')
						md-radio-button(value='sale')
							| Sale

						md-radio-button(value='rent')
							| Rent
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (400/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:44346)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1avrvq-001GMt-LV
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:18 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=vhyqTUbFOWXDBPHmoxWKdH6rLZ8=; b=GCijSG/gveaH10gh
	0Uj+NaX8wvNvISO+wGhmIvu4LvHmqvdBBxkiMWMbUX7BU+ckQCJ42bo2aB6CURy5
	KGJLLVmVg/lO0Ss0DmFb+mCmVISBOnTke8T0cDFUxVCZo0k2e/1FlNRZLLSpxj98
	8qyahB0nfeb6W19YvYHSCMpZdZg=
Received: by filter0535p1mdw1.sendgrid.net with SMTP id filter0535p1mdw1.24848.572268F64C
        2016-04-28 19:48:06.555594898 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id __8p8bAoSrSUnPzJkwa5zw
	for <yann.dupuy@zyapps.com>; Thu, 28 Apr 2016 19:48:06.594 +0000 (UTC)
Date: Thu, 28 Apr 2016 12:47:50 -0700
