### ISSUE TITLE
md-dialog-actions + button padding

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6358]
v1
chrome

trying to evenly space action buttons on a dialog.  it seems the right margin is missing on each button.

also, the left and right padding on the button container are at different values.

![untitled screencast 1](https://cloud.githubusercontent.com/assets/5133412/11861508/52c8eaf8-a43e-11e5-987f-72c24a65d7cd.gif)

```
md-dialog-actions(layout='row'
							layout-align='space-between center'
							flex='')

		md-button.md-warn
			| Reset

		md-button
			| Cancel

		md-button.md-primary
			| Apply
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
