### ISSUE TITLE
md-text-float "shakes" when clicking

### ISSUE THREAD

**Issue by Busata** [angular/material#636]
On the demo website, using Chrome 38.0 , the text field shakes when clicking.

For example, on the demo site https://material.angularjs.org/#/demo/material.components.textField when the focus is on the last name field, and you then click on the postal code field, you can see the text shake. Seems to happen very randomly, focus needs to be on window first -> then last name -> then postal code. 

Fields on the same line do not trigger it.

**Comment by eduardoroyer** [comment]
This only happens if you do not use flex-box to align the components

**Comment by marcysutton** [comment]
I'm not seeing this issue anymore, please let us know if it persists.
