### ISSUE TITLE
Artifacts in layout scss files

### ISSUE THREAD

**Issue by gligoran** [angular/material#6360]
Hello,

My node-sass has been complaining about some artifacts that seem to have crept up in a few layout SCSS files.

For example, here's [line 135 of layout.scss](https://github.com/angular/material/blob/master/src/core/services/layout/layout.scss#L135):

    @media screen\0 {
        .#{$flexName} {
          flex: 1 1 0%;
        }
    }

I'm talking about the ```\0``` in the first line. The same thing appears in line 144 of [layout.attributes.scss](https://github.com/angular/material/blob/master/src/core/services/layout/layout.attributes.scss#L144).

**Comment by jelbourn** [comment]
Dupe of #6304
