### ISSUE TITLE
Not all layout and flex combinations work

### ISSUE THREAD

**Issue by gligoran** [angular/material#6362]
Here's an example:

![2015-12-17_14-33-19](https://cloud.githubusercontent.com/assets/444829/11870805/3c64472a-a4cb-11e5-93be-cc1fed21dea9.png)

    <div class="colorNested-noPad" ng-app="MyApp">
        <div class="demo-content">
            <div layout-gt-xs="row" layout-wrap>
                <div flex="33">
                    [flex="33"]
                </div>
                <div flex="66">
                    [flex="66"]
                </div>
                <div flex-gt-xs="33">
                    [flex-gt-xs="33"]
                </div>
                <div flex-gt-xs="66">
                    [flex-gt-xs="66"]
                </div>
                <div flex-sm="33">
                    [flex-sm="33"]
                </div>
                <div flex-sm="66">
                    [flex-sm="66"]
                </div>
                <div flex="50">
                    [flex="50"]
                </div>
                <div flex>
                    [flex]
                </div>
            </div>
        </div>
    </div>

[pen](http://codepen.io/gligoran/pen/obxgJG?editors=100)

As you can see ```flex``` and ```flex-sm``` don't work when ```layout-ft-xs``` is used, but they should. I haven't tested all the possible combinations, but looking at the compiled [```angular-material.css```](https://github.com/angular/bower-material/blob/master/angular-material.css#L1242), there are things like this:

    .layout-row > .flex-33, .layout-row > .flex-33, .layout-row > .flex-33, .layout-row > .flex-33 {
      -webkit-flex: 1 1 33%;
      -ms-flex: 1 1 33%;
      flex: 1 1 33%;
      max-width: calc(100% / 3);
      max-height: 100%;
      box-sizing: border-box;
    }

Note, that there are 4 of the same selector. I'm guessing this should be different ones.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
