### ISSUE TITLE
CodePen demos calling wrong assets

### ISSUE THREAD

**Issue by joe-watkins** [angular/material#6363]
Ver. 1.0 docs CodePen demos are calling wrong CSS/JS assets.

Wrong CSS:
<img src="http://content.screencast.com/users/joe-watkins-emerge/folders/Snagit/media/722faca6-6dd6-4612-a9c9-019c8cc28c17/2015-12-17_06-45-07.png" alt="Missing CSS File">

Wrong JS:
<img src="http://content.screencast.com/users/joe-watkins-emerge/folders/Snagit/media/298b7b71-32c7-4e77-a1aa-05a98bd1076f/2015-12-17_06-46-41.png" alt="Missing Material JS File">

I've [created a working Pen](http://codepen.io/joe-watkins/pen/LGGjoQ) that points to "correct" files.

**Comment by sazonenka** [comment]
http://localhost:8080/angular-material.js

![image](https://cloud.githubusercontent.com/assets/1306376/11885745/4148e3f2-a4d7-11e5-9b28-ab9dfc601424.png)

**Comment by mescalito** [comment]
+1

**Comment by topherfangio** [comment]
Apologies, the fix unfortunately introduced a different error. We are re-opening and investigating now.
