### ISSUE TITLE
$mdBottomSheet.hide() hides/kills the md-tab it was invoked from...

### ISSUE THREAD

**Issue by healyje** [angular/material#6366]
Not sure if I'm simply doing something wrong, if this is a known issue, or if I need to prevent some event from bubbling back up to the tab. But on the whole not sure what the wiring is such that the .hide() for an $mdBottomSheet would in any way be fielded by a tab directive. Any suggestions?

P.S. behaves the same on latest chrome, firefox and safari

**Comment by naomiblack** [comment]
can you provide a codepen to reproduce?
