### ISSUE TITLE
md-menu inside an element with z-index lower than 99 is not clickable

### ISSUE THREAD

**Issue by guillaume-fr** [angular/material#6368]
When the menu is inside a div with a lower z-index than the backdrop it's no longer clickable, the backdrop is over it.
z-index is inherited and a child z-index cannot be higher than its parent z-index.

You can easily reproduce the issue by putting an md-menu inside a md-sidenav.

I think a proper fix would be putting the md-menu at the same dom level than its backdrop... maybe by cloning nodes.

**Comment by naomiblack** [comment]
This is working as intended.
