### ISSUE TITLE
font-family applied to elements without namespacing

### ISSUE THREAD

**Issue by peterhodges** [angular/material#6369]
The material stylesheet sets the font-family on a handful of generic selectors like button, select etc.

This overwrites the font-family on these elements in the parent app.

```
/************
 * Defaults
 ************/

button,
select,
html,
textarea,
input {
  font-family: $font-family;
}
```

An app should be able to have a font-family defined on body and have this cascade down to child elements without it being overwritten by material.

Can these styles be namespaced (.md-button instead of button)?

**Comment by EladBezalel** [comment]
@peterhodges After discussing with the team we've come to realize that changing this implementation will be a risk for a huge breaking change that we sadly cannot take.

I'd suggest overriding those in your css,
As it's not as elegant as we wish, this is the best solution for now.
