### ISSUE TITLE
md-fab-speed-dial  doKeyRight comparing with left direction (code readability issue)

### ISSUE THREAD

**Issue by MohMaherId** [angular/material#6370]
Under the mdFabSpeedDial controller source code:
['components/fabSpeedDial/fabController.js'](https://github.com/angular/material/blob/master/src/components/fabSpeedDial/fabController.js)

The current implementation of the function doKeyRight may be working fine, but I see that it has a readability and consistency issue compared to the other function for left/up/down.

For a better readability/maintainability, I would prefer if the doKeyRight is using the **right** direction similar to the other methods:
```javascript
function doKeyRight(event) {
     if (vm.direction === 'right') {
       //...
      } else {
        //...
      }
}
```
instead of the current implementation that is comparing with the left direction

```javascript
function doKeyRight(event) {
      if (vm.direction === 'left') {
        //...
      } else {
        //...
      }
 }
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
