### ISSUE TITLE
angular-material.css does not load when using SystemJS for v1.0.0-rc7 onwards [CRITICAL]

### ISSUE THREAD

**Issue by CxRes** [angular/material#6378]
Like the title says, when I upgraded to 1.0.0-rc7 and 1.0.0 with JSPM, angular-material.css is not loading and everything is broken! Works fine 1.0.0-rc6.

**Comment by photusenigma** [comment]
It looks like angular-material.css has been removed from the dependencies "shim" block for angular-material in the bower-material repo (where the package is pulled from for npm, jspm, and bower).

![screenshot of package.json]
(https://www.evernote.com/l/AIsZwU70yDdHmLvum8x5bCxUyzm_3QROUiEB/image.png)

**Comment by CxRes** [comment]
@photusenigma Thanks for pointing that out - at least I can carry on with my work for now. 

I believe Angular Material team ought to fix this regression themselves because it seems a bit stupid to include `angular-material.css` every time I include the `angular-material` and I cannot be bothered to keep rebasing every time a new version is released.

**Comment by ThomasBurleson** [comment]
Will not fix. See https://github.com/angular/material/issues/6063

**Comment by CxRes** [comment]
If so, Please clearly document this Information and why this has been done. It is unfair for every jspm user to dig up #6063. I'll open a separate ticket if you like?
