### ISSUE TITLE
waitTransitionEnd causes crazy number of digests

### ISSUE THREAD

**Issue by ashaffer** [angular/material#6380]
Currently waitTransitionEnd is called for every show/hide, among other things. Within waitTransitionEnd $timeout is used, which causes a unique $apply each time it's called. By passing false as the third param to $timeout and manually calling $rootScope.$applyAsync, you could achieve the same functionality with *substantially* fewer digests.

**Comment by topherfangio** [comment]
@ashaffer Can you give us an example of how this is causing so many digests in your code?

As far as I can tell, `waitTransitionEnd` is only called when a virtual repeat directive is shown/hidden, and it only causes a single digest when that happens, so I feel like I'm not understanding your exact issue. Some guidance would definitely be appreciated.
