### ISSUE TITLE
Default them display over custom toast theme

### ISSUE THREAD

**Issue by Nick-t-go** [angular/material#6382]
Here is an example. Trying to change the theme of the md-toast box but the default them is displaying over my custom theme.

http://codepen.io/anon/pen/OMNWpR

**Comment by RolandHeath** [comment]
I think the css class you want to override is in actually 
md-toast .md-toast-content {
    background-color: red;
}

**Comment by Nick-t-go** [comment]
Yep that does it but putting it on the theme looks like this:
```md-toast.md-fail-toast-theme .md-toast-content {
background-color: red;
}```
