### ISSUE TITLE
md-icon - ng-click not working on FireFox (mac)

### ISSUE THREAD

**Issue by jeffthompson1971** [angular/material#6385]
Tried my app today on firefox and while ng-click works in general, for md-icon directive i see the ripple effect of the button but ng-click is not fired.    Using the latest FireFox.

**Comment by marcysutton** [comment]
Can you provide a Codepen demo showing your issue? Which Angular Material version? You should be putting `ng-click` on an `md-button` with `md-icon` inside of it, so that keyboard users can operate it.

**Comment by naomiblack** [comment]
Closing. Please submit a codepen to reopen.
