### ISSUE TITLE
Difference between md-whiteframe-z* and md-whiteframe-dp*

### ISSUE THREAD

**Issue by Masadow** [angular/material#6386]
I can see the difference between the two, but why keeping `whiteframe-z*` whereas it's not in the doc anymore ?

Also, there is nothing like `md-whiteframe-z*` currently. Is it going to be discontinued ? Should I apply the margins and backgrounds myself to `md-whiteframe-dp*` ?

**Comment by mattdanna** [comment]
`md-whiteframe-z*` has been deprecated since https://github.com/angular/material/issues/4586
I assume they left it in there to avoid breaking changes for the time being.

**Comment by EladBezalel** [comment]
@mattdanna your'e right, @Masadow `md-whiteframe-z*` has been deprecated but left there to avoid breaking changes.
