### ISSUE TITLE
radio-group: Incorrect margin in row

### ISSUE THREAD

**Issue by epelc** [angular/material#6387]
When an `md-radio-group` has `layout="row"` or any of the `-gt*` attributes the following style is incorrect. It causes the first item to not be centered vertically with the other items.

```
md-radio-group md-radio-button:not(:first-child) {
    margin-top: 16px;
}
```

https://github.com/angular/material/blob/master/src/components/radioButton/radio-button.scss#L119-L121

Also there is no margin-left/right so they are all too close together. I believe the recent changes to radio-group/checkbox styles caused this issue.

**Comment by epelc** [comment]
Never mind these issues are caused by #5772 I was using `layout="column" layout-gt-sm="row"` instead of `layout-sm="column" layout-xs="column" layout="row" `. However there is no `margin` on the top or bottom when they are in a row which doesn't look right especially if you put a header or anything above them. I believe checkboxes also have no margin top/bottom when they are in a row now too.

**Comment by EladBezalel** [comment]
@epelc The spec doesn't define the margin checkboxes and radio groups should have, I didn't applied any margin on top and bottom to not break current apps design.

**Comment by epelc** [comment]
@EladBezalel I see it doesn't define any margin. Maybe there should be one so the circle which shows up when you click it is only within the elements space.

Here's a demo with rows/columns of radio buttons to experiment with.
http://codepen.io/anon/pen/zrBaVE?editors=101

Also Idk if this is a bug but if your `md-radio-group` doesn't have `layout="column"`(might also require parents to not have it set) it will display differently then if you do add a `layout="column"`(the margins on the radio buttons collapse over each other without it.). See [this](http://codepen.io/anon/pen/KVMBwg?editors=101) demo for an example.

**Comment by epelc** [comment]
Also it slightly broke my app in a few places.

If you have elements above a checkbox/radio-group which do not have their own margin then checkbox/radio-group below it(with layout="row" on them) has no margin top and they become very close. In the older version the checkbox/radio-group with (layout="row) use to have a `margin-top` set.

**Comment by guiporto** [comment]
I found a bug (I believe it's related to this issue) that happens when you use for example `layout-xs="row"` instead of `layout="row"`.

Here's a codepen to describe the issue: http://codepen.io/guiporto/pen/eJzxqW

The issue is exactly here:
<img width="245" alt="screenshot 2015-12-23 00 46 06" src="https://cloud.githubusercontent.com/assets/1811399/11970246/b6a9b0be-a90e-11e5-86bb-c68843af2e87.png">
