### ISSUE TITLE
<md-text-float> is canceling the <md-dialog> on enter key is pushed

### ISSUE THREAD

**Issue by epool** [angular/material#639]
I need help in my Dialog form, Why does the `<md-text-float ...> </md-text-float>` it's canceling the `<md-dialog>` when I push the enter key on the `<md-text-float ...> </md-text-float>`? I would like to submit the form when I press the enter key. I have seen that when I change the order of the 'cancel' and the 'okay' buttons the form is submited correctly, I'm not sure if the `<md-text-float>` launches the nearest `ng-click` event.

Here is the source code: http://jsfiddle.net/eduardo_pool/osqLhhm7/1/

**Comment by wmertens** [comment]
I updated the fiddle to work with 0.7.0 rc2: http://jsfiddle.net/osqLhhm7/6/

I put the form outside the dialog, but that doesn't help with formatting. Remove the form and see how the dialog action buttons suddenly change and the content scrolls. Looks like there's no way to have a form in a dialog.

Also used the `dialog-close` class to mark an input as getting focus.

**Comment by marcysutton** [comment]
Can you verify whether this is still an issue?

**Comment by charneykaye** [comment]
In my case, I put the field inside a `<form>` and used `ng-submit="ctrlTimespan.save()"` where that expression implements `$mdDialog.hide(...)` from the DialogController.
