### ISSUE TITLE
md-autocomplete 'required' validation broken in 1.0.1

### ISSUE THREAD

**Issue by gnomff** [angular/material#6393]
The Floating Label Autocomplete demo is broken in versions 1.0.0, 1.0.1 and HEAD, although it was working in 0.11.4. Leaving the field empty does not cause the form to have the 'required' error.  

Other validations (min, max) seem to be working.

**Comment by topherfangio** [comment]
Related to #6313.

**Comment by Nazanin1369** [comment]
@topherfangio Any one working on this?

**Comment by bOOm-X** [comment]
It should work if you put required="true"

**Comment by gnomff** [comment]
it looks like required="true" does work

**Comment by bOOm-X** [comment]
Yes it does !
It is a small bug in the parsing of the required attribute.
I will do a merge request as soon as I can (tomorrow Paris time)

**Comment by gnomff** [comment]
Thank you!

**Comment by 91K00** [comment]
Ok great! Thanks

**Comment by manasovdan** [comment]
seems like `required="true"` makes sense but `ng-messages` still not working

**Comment by MasterRam** [comment]
i installed bower component "angular-material": "1.0.6"
but i feel the issue #6803 still exist.
![image](https://cloud.githubusercontent.com/assets/11454989/14108503/9f75213e-f572-11e5-9b17-0e25410a9bb4.png)

**Comment by DevVersion** [comment]
@MasterRam The fix has been released in `1.1.0-rc1`, not in v1.0.6

**Comment by kevinlbatchelor** [comment]
+1

**Comment by MasterRam** [comment]
Thanks It is working fine....:)

**Comment by jonathanread** [comment]
I am using angular material 1.1.1. I am not able to get my required autocomplete to work. The form does not submit, to the required attribute is working but the ng-message never shows.

`<form name="projectForm" id="projectForm">
  <md-autocomplete
                                        md-selected-item="ctrl.selectedCustomer"
                                        md-items="item in ctrl.queryCustomers(ctrl.customerSearchText)"
                                        md-item-text="item.name"
                                        md-search-text="ctrl.customerSearchText"
                                        md-no-cache="false"
                                        md-min-length="0"
                                        md-input-name="customer"
                                        ng-disabled="ctrl.isEditing" required="true">
                                    <md-item-template>
                                        <span md-highlight-text="ctrl.customerSearchText">{{ item.name }}</span>
                                    </md-item-template>
                                    <md-not-found>
                                        No customers found.
                                    </md-not-found>
                                    <div ng-messages="projectForm.customer.$error">
                                        <div ng-message="required">This field is required</div>
                                    </div>
                                </md-autocomplete>
</form>`

I have tried all above suggestions ...

**Comment by Karasuni** [comment]
I'm observing the same exact issue as @jonathanread : In 1.1.1 the md-autocomplete does not work using 'md-required' or 'required' tags. This is inconsistent with other elements and the documentation.
