### ISSUE TITLE
md-datepicker won't allow dates before August 1932

### ISSUE THREAD

**Issue by craigsh** [angular/material#6397]
md-datepicker won't allow dates before August 1932. Even if a minDate is set it doesn't allow scrolling back if earlier than August 1932.

I want to use the md-datepicker to enter birthdates. There are still people alive born before then!

**Comment by RolandHeath** [comment]
This issue can be reproduced on the [documentation](https://material.angularjs.org/latest/demo/datepicker), using the first field. 
Start by entering a date in 1932, then scroll back - it won't go past August.

**Comment by jelbourn** [comment]
Yep, known issue. I'm surprised someone didn't file it sooner. Making it actually (mostly) infinite is on the to-do- list. At the time it was written, `md-virtual-repeat` didn't have the required feature yet.

**Comment by jelbourn** [comment]
This one is still a real issue.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
