### ISSUE TITLE
Improve documentation for $mdDialog?

### ISSUE THREAD

**Issue by okaiyong** [angular/material#6398]
Met with a few problems when using mddialog, can't find any reference for it. 
1. Cannot find a way to change the settings for mdDialog dynamically, is it possible in the first place? e.g. closeWhenclickedoutside, etc
2. Is it possible to hide without destroying scope created and show without new scope created, but need to destroy it after that? Currently exploring to store the $scope in service to retrieve the scope.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
