### ISSUE TITLE
Bottomsheet should support selector to determine parent

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#640]
If a bottomSheet parent DOM element is not provided, the InterimService will use the $rootElement body or the $rootElement as the parent container for the mask and bottomsheet.

The following enchancement is needed:

``` js
$$interimElement({
    parent: "#myBSContainer",
    onShow: onShow,
    onRemove: onRemove,
  });
```

**Comment by joaogarin** [comment]
While using this and going through the framework for first time on the documentation it looks like you need to provide the actual element. But reading the code on the feature from @ajoslin I can see you actually need to provide the selector. Its not completely clear at least in my opinion on the documentation. Maybe I missed somewhere what the "Element" refers to in the scope of the documentation (perhaps its used in other servies as well).

Anyway nice that it is there ;)

**Comment by ThomasBurleson** [comment]
The `parent` option can be:

* function
* a selector string
* a object reference
* null/undefined (in which case the `$rootElement.body || $rootElement` is used).

Check out the [Material-Start](https://github.com/angular/material-start/blob/master/app/src/users/UserController.js#L66-L72) use of bottom sheet:

```js
$mdBottomSheet.show({
          parent: angular.element(document.getElementById('content')),
          templateUrl: '/src/users/view/contactSheet.html',
          controller: [ '$mdBottomSheet', UserSheetController],
          controllerAs: "vm",
          bindToController : true,
          targetEvent: $event
        }).then(function(clickedItem) {
          clickedItem && $log.debug( clickedItem.name + ' clicked!');
        });
```
