### ISSUE TITLE
.dark() doesn't change input and dropdown menu text color

### ISSUE THREAD

**Issue by lacvapps** [angular/material#6404]
![screen shot 2015-12-19 at 11 35 13 pm](https://cloud.githubusercontent.com/assets/13122971/11917015/814b484a-a6a9-11e5-85bf-a3835eea9fef.png)

when I dynamically change my theme to dark with the grey primary palette the border and text in the input boxes is grey, It stays the same as when the theme is light

**Comment by lacvapps** [comment]
![screen shot 2015-12-19 at 11 35 04 pm](https://cloud.githubusercontent.com/assets/13122971/11917020/b7a050a2-a6a9-11e5-92cf-f5e26a63c608.png)

**Comment by DevVersion** [comment]
I created a codepen for that, so we can investigate better.

http://codepen.io/DevVersion/pen/EPKBBz
