### ISSUE TITLE
Content out of md-whiteframe

### ISSUE THREAD

**Issue by tatulea** [angular/material#6405]
Hi! I have the next code: http://codepen.io/tatulea/pen/rxeEXP

The problem is that if the page is smaller than the md-whiteframe, the content (h1, md-inputs) is going out of my whiteframe.

**Comment by EladBezalel** [comment]
@tatulea This type of questions are related to our [Forum](https://groups.google.com/forum/#!forum/ngmaterial)

You should take a look at our layout [demos](https://material.angularjs.org/latest/layout/introduction), [use `flex-*` attributes](http://codepen.io/EladBezalel/pen/adNePZ)

**Comment by tatulea** [comment]
My problem is not the width. My problem is the height. If the height is too small, the content is getting out from my whiteframe.

**Comment by EladBezalel** [comment]
You should apply `overflow: scroll `
