### ISSUE TITLE
md-tab Inkbar breaks when updating md-tab-label too fast.

### ISSUE THREAD

**Issue by coshxx** [angular/material#6408]
When updating a md-tab-label too fast (interval <= 100ms) the ink bar does not respond anymore/does not even show up.

1. See http://codepen.io/anon/pen/XXKbrd.
2. change self.intervalTime to a value < 101.
3. no ink bar anymore.

**Comment by coshxx** [comment]
When you remove the ng-cloak from the html it will actually show the inkbar, but the ink bar does not respond anymore. http://codepen.io/anon/pen/ZQOWjL

**Comment by topherfangio** [comment]
The `tabsController.js` file currently has the following line:

```js
ctrl.updateInkBarStyles = $mdUtil.debounce(updateInkBarStyles, 100);
```

The `debounce()` method does not call the function unless there is at least 100ms between calls. We may be able to fix this by changing it to use `$mdUtil.throttle()` instead, but we need to investigate further.
