### ISSUE TITLE
How to create a round md-warn button?

### ISSUE THREAD

**Issue by demisx** [angular/material#641]
I want to use Angular Material for my next project. How would I go about creating material UI elements besides what's shown on the demo page? For example, I need a warn button similar to `md-warn md-raised` shown on
https://material.angularjs.org/#/demo/material.components.button, but I need it round instead of rectangular. What would be the proper way to achieve something simple like that?

**Comment by bram2507** [comment]
Nice ! the csss lines did the trick for me . Thanks a lot ! Good work
