### ISSUE TITLE
sidenav like inbox.google.com

### ISSUE THREAD

**Issue by justechn** [angular/material#6411]
Hey guys,

Thanks for this great app. I have just started using it, and I have a question about the sidenav. I would like mine to behave like inbox.google.com

With inbox the sidenav opens under the toolbar, and it does not grey out the main page. how can I duplicate this in angular material?

**Comment by DevVersion** [comment]
At the moment it is possible to place the sidenav under the toolbar, easily use flexbox with rows to align it under the toolbar.

The actual problem is the backdrop, maybe we should provide an attribute to disable the backdrop.

**Comment by justechn** [comment]
Thanks for the suggestions. 

I have been playing with the sidenav for a couple days and it seem like it does not honor the flexbox layout unless I use the md-is-locked-open expression. Am I missing something? 

also, while aligning the sidenav under the toolbar I first had to use the layout column which causes the locked sidenav to not fill the screen vertically. I even put a layout="row" on the sidenav itself, but it still only goes down to the bottom of the content, not the bottom of the page. Is there a way to use both column and row layout at the same time so I can fill the page both horizontally (for the toolbar) and vertically (for the sidenav)?

Thanks again.

**Comment by Todd-Werelius** [comment]
As a wider discussion, unless I missed this topic elsewhere, the spec provides for 5 modes with a total of 7 variants, listed below for reference ( as of today anyway ) I think the answer should always be, support the spec first, leave customization up to the user or at least defer it until the spec is completely supported.

As far as I can tell support only exists for the following in Angular Material 

1A - Permanent Full Height - but it requires overly complex strategies to work on all device sizes if you want to transition from one mode to the next, i.e. it's not at all easy, as a matter of fact a better approach for permanent is just design your own column that acts that way at the moment and hide it based on a media query ( Am I wrong about this? )   

4A - Temporary 
Really only 4A works as expected without a lot of thought needed.

As it is now I would have to work pretty hard to create a transition from permanent, to persistent, to temporary dependent on device capability 

It seems like a better semantic approach from a users perspective would be

<md-sidnav md-sidnav-mode="permanent | persistent | temporary" md-sidenav-mini="true | false">

With media query support of course, that would not make it any easier to implement, just easier to understand.  

**Material Design Spec  **

1. Permanent - Always Open - No Backdrop 
1A Full Height ( does not overlap content )   
2B Clipped under app bar  
3C Floating  
![image](https://cloud.githubusercontent.com/assets/5982829/13154855/e09d97f2-d62f-11e5-85c7-1eb27bac26a4.png)

2. Persistent - No Backdrop
2A Forces all content to re-size when open ( does not overlap content ) 

3. Persistent Mini Variant - No Backdrop
3A Permanent single column clipped by toolbar, when activated emulates persistent mode until closed
![image](https://cloud.githubusercontent.com/assets/5982829/13155340/15162826-d632-11e5-8624-976f90630754.png)


4. Temporary - Uses Backdrop - Higher than Content Area 
4A Overlays content 

5 Temporary Mini Variant - Uses Backdrop - Higher than Content Area 
5A Has permanent single column clipped by toolbar, over lays when activated until closed

**Comment by EladBezalel** [comment]
closed with 1554eb1
