### ISSUE TITLE
$mdDialog.hide cannot pass more than 1 parameter to promise

### ISSUE THREAD

**Issue by alanpurple** [angular/material#6413]
``` js
$mdDialog.show({
                controller: editNewsDlgController,
                templateUrl: '/admin/partials/dialogs/editNewsDlg.html',
                locals: {
                    isNew: false,
                    news: $scope.newsList[index]
                },
                clickOutsideToClose: true
            })
            .then(function (result, update, newPhoto) {
                console.log(result); // true
                console.log(update); // undefined
                console.log(newPhoto); // undefined

console.log('only photo hide');  // hit, printed
$mdDialog.hide(true, null, true);
```

**Comment by EsunaProxy** [comment]
You could temporarily solve this by creating an object with all three of those params values and passing them through:

result:{
       result: result,
       update: update,
       newPhoto: newPhoto,
}

$mdDialog.hide(result);

.then(function(result){
        console.log(result.result, result.update, result.newPhoto)
});

**Comment by alanpurple** [comment]
Yeah I temporarily solved it already, thx

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
