### ISSUE TITLE
CodePen examples from online docs not working

### ISSUE THREAD

**Issue by camden-kid** [angular/material#6414]
Sorry, I know this isn't an issue with the code but I didn't know where else to give you a heads-up about this problem.

For each example the following Pen Settings are the cause of the problem:

http://localhost:8080/angular-material.css
http://localhost:8080/docs.css
http://localhost:8080/angular-material.js

They need to be changed from http://localhost:8080 to https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8

**Comment by mprentic-harris** [comment]
Should be fixed now by @topherfangio in https://github.com/angular/material/commit/43464d034ad4dd43156a0b804edb4f4956484302.

**Comment by topherfangio** [comment]
@mprentic-harris Thanks for updating all of the relevant issues ;-)

**Comment by topherfangio** [comment]
This should now be fixed. Please let us know if you are still experiencing issues and we will reopen.

**Comment by camden-kid** [comment]
There is one problem I recently spotted on this page https://material.angularjs.org/latest/layout/alignment but it's not related to CodePen issues. After clicking on the View Source icon in the demo the markup doesn't reflect the options selected and the expanded markup display obscures some of the options.

**Comment by topherfangio** [comment]
@camden-kid Can you please open a separate issue for this so that we can track it and fix it?

**Comment by camden-kid** [comment]
The CodePen problem has reappeared.

Also, when the CodePen examples were working the md-icon svg icons did not load.

**Comment by topherfangio** [comment]
@camden-kid Thanks; it looks like it's only "latest" that is having trouble; HEAD codepens appear to point to the proper place.

**Comment by ThomasBurleson** [comment]
Duplicate.
