### ISSUE TITLE
mdTabs: many DOMSubtreeModified calls

### ISSUE THREAD

**Issue by Otanikotani** [angular/material#6416]
This is the code I use for tabs on my page:
```html
        <md-tabs md-dynamic-height>
            <md-tab md-on-select="ctrl.$state.transitionTo('kpi.new.vehicle', {})"><md-tab-label>Vehicle</md-tab-label></md-tab>
            <md-tab md-on-select="ctrl.$state.transitionTo('kpi.new.dealer', {})"><md-tab-label>Dealer</md-tab-label></md-tab>
        </md-tabs>
        <div ui-view ng-cloak></div>
```

I profiled tabs switching from one to another:
![with_subtreeevent](https://cloud.githubusercontent.com/assets/1468666/11931298/5ccdcfac-a7fc-11e5-91e7-aebe1cef85da.png)

As you can see on the pic, selected yellow area is the moment of tabs switching. It took about one second. Please, notice the DOMSubtreeModified events in the stacktrace. There are tons of them.

I think the issue is in this code, in the mdTabsTemplate directive:
```javascript
    element.on('DOMSubtreeModified', function () {
      ctrl.updatePagination();
      ctrl.updateInkBarStyles();
    });
```

If I comment it out and make the same test:
![without_event](https://cloud.githubusercontent.com/assets/1468666/11931355/1d9da734-a7fd-11e5-9355-fe70017d54d8.png)

Commenting out 'DOMSubtreeModified' event handler made about 0.8s difference in time - it is only 224ms now. Also notice that there are no DOMSubtreeModified in the stacktrace.

I think the issue here is that this event handler is getting called many times during tab content compilation. Is it needed to be called so often, though?

**Comment by EladBezalel** [comment]
@Otanikotani A dup of #5681, 
Your description is a great input do you mind move this to the other issue?
> i don't want to close this yet until you will respond.

**Comment by Otanikotani** [comment]
@EladBezalel Added a comment to #5681. I am sorry, I didn't notice it.

**Comment by EladBezalel** [comment]
@Otanikotani thanks! :+1:
