### ISSUE TITLE
Usage of hide with other layout options - differences across versions

### ISSUE THREAD

**Issue by parky128** [angular/material#6417]
I am trying get some table columns to show and hide based on screen sizes using the layout options and the hide attribute as per the layout docs.

I'm actually using 0.11.2 which I know is a bit old now, and the project I'm working on needs upgrading to 1.0 but we just haven't made the jump yet. So in the meantime I'm just trying to get the behaviour working for 0.11.2.

I have a couple of code pens below that show what I want to achieve, nothing complex as you can see, I just want one column to hide on small screens:

[0.11.2](http://codepen.io/parky128/pen/qbNaOE)

This version works perfectly, but I had to use the attributes as class values, using as in line attributes does not work (as per the docs)

[1.0.0](http://codepen.io/parky128/pen/PZzbgM)

Here I have used attributes as per the docs, but none of the columns show\hide and the table content does not fill the available width of the card that contains it, unlike the older version above.

How can I get this to work for the latest release?

On a side note, when viewing the examples in the docs (https://material.angularjs.org/1.0.0/layout/options) there is a particular example in the 'Show & Hide' section where one of the panels should be hidden on gt-md devices:

````
<div show hide-gt-md flex>
    Shown on small and medium size devices.<br>
    Hidden on gt-md devices.
  </div>
````

But it shows for me and i'm running a 1440px width screen!

And this div:

````
<div hide show-gt-lg flex>
    Shown on devices larger than 1200px wide only.
  </div>
````
Does not show at all when my screen is maximised.

Is this a bug? Or am I misunderstanding something here?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
