### ISSUE TITLE
edit on codepen doesn't work

### ISSUE THREAD

**Issue by JA44** [angular/material#6418]
The links "edit on Codepen" on the Angular Material's site doesn't work. The settings on CodePen for the CSS, JS files calls this URLs: http://localhost:8080/docs.css, http://localhost:8080/angular-material.css, http://localhost:8080/angular-material.js instead of an CDN URL

**Comment by mprentic-harris** [comment]
Yep, I just ran into this as well. It works in the 1.0.0 docs and in HEAD, but not 1.0.1.

Thankfully @topherfangio just resolved this in https://github.com/angular/material/commit/43464d034ad4dd43156a0b804edb4f4956484302.

**Comment by topherfangio** [comment]
This was merged and should now be fixed. Please let us know if you're still having issues and we will reopen.
