### ISSUE TITLE
md-tall measure

### ISSUE THREAD

**Issue by jjalonso** [angular/material#642]
he toolbar md-tall must be in total 128px height, and not 192px like now.
Is this the size that you want to target?

Source: https://www.google.com/design/spec/layout/metrics-and-keylines.html#metrics-and-keylines-keylines-and-spacing

**Comment by EladBezalel** [comment]
Isn't that [fixed](https://github.com/angular/material/blob/master/src/components/toolbar/toolbar.scss#L4)?

**Comment by rschmukler** [comment]
[as per this jsfiddle](http://jsfiddle.net/rschmukler/g8z57Lvz/) this appears to be resolved. Please re-open if you can recreate the issue.
