### ISSUE TITLE
Validation doesn't work for md-autocomplete within md-chips

### ISSUE THREAD

**Issue by erinjanae** [angular/material#6424]
Validation doesn't work properly for md-autocomplete within md-chips. The following code pen shows validation working for md-autocomplete but not working for md-autocomplete within md-chips.

http://codepen.io/anon/pen/Veapvm

When invalidating the md-autocomplete within the md-chips the label becomes red but input field line does not turn red. Also the ng-message only flashes for a second and then disappears.

**Comment by enderdickerson** [comment]
+1

**Comment by manasovdan** [comment]
+1

**Comment by stefan-leye** [comment]
+1

**Comment by tipodisimmia** [comment]
+1

**Comment by hagerupe** [comment]
+1

**Comment by ThomasStubbe** [comment]
+1

**Comment by zverevalexei** [comment]
+1
More over, "ng-messages" doesn't work for md-chips

**Comment by zverevalexei** [comment]
+1
Moreover, "ng-messages" doesn't work for md-chips

**Comment by pccjamie** [comment]
Hi @ThomasBurleson  - I see that you've moved this to Deprecated. Can you clarify what the intent is here? Will this issue be addressed in another release or not at all?

**Comment by DevVersion** [comment]
@pccjamie This issue was closed by our [Spring Cleaning](https://groups.google.com/forum/#!topic/ngmaterial/3Ip9nd68bfk)

**Comment by IMM0rtalis** [comment]
@DevVersion but I think this is still up2date!

+1
