### ISSUE TITLE
md-menu not working in 1.0.0

### ISSUE THREAD

**Issue by ViciousGrant** [angular/material#6427]
Hi, recently i started a project using angular-material ver. 1.0.0 and the md-menu tag isn't working, i`ve tried copying the code directly from the demos, and nothing, I click the element and nothing opens, also after that i can't click anything else, apparently it puts up a mask on the page.

I changed the angular-material.js file to the one of v1.0.0-rc1 and it works just fine, did something changed, can somebody explain me if i am doing something wrong?.

Thanks

**Comment by EladBezalel** [comment]
@ViciousGrant Can you please provide a codepen so we can investigate more further?

**Comment by ViciousGrant** [comment]
Hi, i'm so sorry, i did the codepen and it worked, so i updated all my dependencies including angular, and it worked!, sorry for the inconvenience, thank you.
