### ISSUE TITLE
md-tabs with md-accent ignores the palette's text color

### ISSUE THREAD

**Issue by rfuhrer** [angular/material#6431]
If you have a md-tabs setup with the class="md-accent" property (it's shown as an example at the bottom of https://material.angularjs.org/latest/demo/tabs, so it should be a valid use case) it ignores the text color for that palette which can lead to unreadable text.  Here's a quick example where you can't read the text of the available tabs simply by setting the md-accent palette to default to 100:
http://codepen.io/anon/pen/PZzKmJ
Even setting the theme's hue-# properties to different colors does not affect the text inside a tab
![image](https://cloud.githubusercontent.com/assets/2529744/11941591/f9ad5c20-a7ed-11e5-8247-98f799cb2f53.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
