### ISSUE TITLE
Switch on drag moves but doesnt change value. Only when clicked is changed. (Tested on ipad)

### ISSUE THREAD

**Issue by mikila85** [angular/material#6432]

**Comment by EladBezalel** [comment]
Can you add description and a codepen so we can understand your issue better?

**Comment by mikila85** [comment]
nothing to codepen.
go to switches demo and instead of clicking it for on/off.. try drag it from off to on. (on Ipad).
it drags nicely from off to on.. but when u release the switch it goes back to the initial state.

**Comment by DevVersion** [comment]
Yes I can reproduce that. If you drag it from `off` to `on` it will move back. And something strange is, if you drag from `off` to the other side `<-- left`, it will move to `on`

Little GIF, which should shows the problem
![](https://i.gyazo.com/37d7c373d9c88b27be2b47a73641ba52.gif)

**Comment by EladBezalel** [comment]
dup #4719
