### ISSUE TITLE
Virtual scroll on ipad

### ISSUE THREAD

**Issue by mikila85** [angular/material#6433]
On ipad, When scrolling virtual scroll with inertia you get stuck with empty list for a few seconds.. Untill inertia stops and then it renders new list.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
