### ISSUE TITLE
mdChips: Items without trailing separator not included in ng-model

### ISSUE THREAD

**Issue by laberle** [angular/material#6435]
When you use md-chips for inputs, if the user forgets to add the last 'ENTER', the last item does not get picked up. IMHO, this is counter-intuitive.

![screenshot from 2015-12-21 16 33 22](https://cloud.githubusercontent.com/assets/1323647/11944108/929d5298-a800-11e5-93da-d414f6a87af5.png)

[CodePen](http://codepen.io/anon/pen/rxLGOx)

There is currently no way to validate if such "trailing input" (for lack of a better term) exists. I see a few options for behavior to warn the user:
1. Warn the user when they hit the "Submit" button that they have trailing input
2. Invalidate the submit button if there is trailing input
3. Process the trailing input as if the 'ENTER' key had been pressed
4. (Others I haven't thought of)

There are pros and cons to each one. It would be nice to allow the developer the ability to pick which behavior to implement, but as it currently stands I don't see a way to do this.

**Comment by GustavoCostaW** [comment]
+1 

I have the same with list of e-mails, in the last e-mail user not press enter or , and does not get picked up

**Comment by GustavoCostaW** [comment]
Or add this possibility with readonly :-)

**Comment by RolandHeath** [comment]
You might be able to make a workaround for this by providing an input element to md-chips (similar to the chips/autocomplete examples), and doing some kind of validation on that. You essentially need the opposite of the required attribute.

**Comment by EladBezalel** [comment]
I think that chips should also create a chip on focus loss, this will cover all your cases. @laberle @GustavoCostaW  @RolandHeath thoughts?

**Comment by GustavoCostaW** [comment]
@EladBezalel I think great.
When lost focus convert the possibilities in chips =]

**Comment by EladBezalel** [comment]
@GustavoCostaW i think i will add an attribute, some thing like:
```js
<md-chips md-convert-on-blur="true" ...>
...
</md-chips>
```

**Comment by GustavoCostaW** [comment]
@EladBezalel This sample works for me.

**Comment by RolandHeath** [comment]
@EladBezalel I agree, provided that (as in your example) it is optional.

**Comment by GustavoCostaW** [comment]
@EladBezalel news?

**Comment by EladBezalel** [comment]
@GustavoCostaW not yet sadly, PRs are welcome!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
