### ISSUE TITLE
Hi-dpi scroll handle for containers

### ISSUE THREAD

**Issue by dalgard** [angular/material#6438]
The scroll handle on md-virtual-repeat and the content container seems pixelated on my Retina screen. Would it be possible to use a hi-dpi version instead?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
