### ISSUE TITLE
md-select items in md-select-menu are overflowed on Windows

### ISSUE THREAD

**Issue by oskarwrobel** [angular/material#6441]
Hi,

Looks like md-select-menu width is a little to small on Windows (Chrome and Firefox) and text is overflowed (ellipsis). On OSX is OK, maybe it's because on osx scrollbar is smaller?
On IE11 on Windows7 is also OK.

**NOT OK - Windows7 Firefox 43.0.1**
![firefox-win7](https://cloud.githubusercontent.com/assets/1057056/11955051/4c0c9dd0-a8ae-11e5-8248-f5765607603c.PNG)

**NOT OK - Windows7 Chrome 49.0.2597.3 canary (64-bit)**
![chrome-win7](https://cloud.githubusercontent.com/assets/1057056/11955017/f46151fc-a8ad-11e5-911e-a4d394141dc5.PNG)

**OK - OSX 10.11.1 Chrome 49.0.2599.0 canary (64-bit)**
![screenshot 2015-12-22 11 20 11](https://cloud.githubusercontent.com/assets/1057056/11955088/dcb9ef04-a8ae-11e5-947f-75d30a38db31.png)

**OK - Windows7 IE 11.0.9600.17728**
![ie-win7](https://cloud.githubusercontent.com/assets/1057056/11955066/96e7e364-a8ae-11e5-9129-32305dcd6b9e.PNG)

**Comment by bojancai** [comment]
my issue is that text is not overflowed (ellipsis) On OSX - Chrome Version 47.0.2526.106 (64-bit), then bring scroll bar

**Comment by oskarwrobel** [comment]
This bug is classified as IE Bug, but it works OK on IE. It occurs on Chrome and Firefox.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
