### ISSUE TITLE
Documentation for Layout Extra Options show/hide misses show-gt-sm

### ISSUE THREAD

**Issue by FrancescoRizzi** [angular/material#6442]
Looking at the [Documentation for Layout > Extra Options](https://material.angularjs.org/HEAD/layout/options) (checked in v.1.0.0 and v.1.0.1) I noticed a typo in the table listing hide-* and show-* options.

The row for `hide-gt-sm` also lists `hide-gt-sm` in the second column (aka: `show (negates hide)`) instead of `show-gt-sm`.

**Comment by DevVersion** [comment]
Fixes in #6349

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
