### ISSUE TITLE
ngMessages have multiple bugs

### ISSUE THREAD

**Issue by gligoran** [angular/material#6443]
Hello,

I've [created a pen](http://codepen.io/gligoran/pen/GoqdPy), with multiple cases where ngMessages don't work as they should.

There seem to be 2 core issues:
1. The auto hide functionality (ngMessages that doesn't use md-auto-hide, ngIf, ngShow, or any other directive that disables auto hide) has trouble switching between different errors.
2. Custom $asyncValidators display multiple of the same message at once.

**Comment by jaGarcia** [comment]
+1  to point 1

**Comment by jaspersorrio** [comment]
+1 to point 1

Here is my <a href="http://codepen.io/jaspersorrio/pen/LGxyNV?editors=101">pen</a>!

I noticed if the user typed too fast, the errors do not appear.
And @gligoran 2nd point, i am facing that too.

**Comment by Odahi** [comment]
I've also noticed that using ngMessagesInclude can change the show/hide behavior in messages.

**Comment by wcjr** [comment]
I've noticed the nodes for the messages are there but they have an `opacity: 0` when it should be `1`.  Does this have something with ngAnimate?

**Comment by Clarity-89** [comment]
+1 to wcjr's issue

**Comment by wcjr** [comment]
I took a closer look at issue [6610](https://github.com/angular/material/issues/6610) referenced by @grosem and it is fully explained there.  Unfortunately it seems @ThomasBurleson labeled it for Q2 consideration :-(  I noticed it was also labeled as an "Edge" case...that seems under-prioritized to me personally if I'm understanding the team's approach to solving this one.

**Comment by chadjaros** [comment]
+1
The required (number one) bug also seems to prevent other error messages (such as pattern) from showing up properly. Very annoying.

**Comment by wcjr** [comment]
looks like these are related issues that are being worked now:  [6859](https://github.com/angular/material/issues/6859) and [6399] (https://github.com/angular/material/issues/6399)

**Comment by topherfangio** [comment]
Hi all, we are indeed working on these issues; just trying to make sure we get some proper tests, and since this is related to animations, we're working with the core Angular team to make sure we have the proper approach. This is definitely a priority on our list!

**Comment by wcjr** [comment]
Thanks for letting us know @topherfangio

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
