### ISSUE TITLE
Grid Layouts

### ISSUE THREAD

**Issue by erslater** [angular/material#6444]
I would love to see something similar to David Desandro's projects implemented:
Masonry (http://masonry.desandro.com/), 
Packery (http://packery.metafizzy.co/)
Isotope (http://isotope.metafizzy.co/)

These provide flexible grid layouts with drag/drop, sorting and filtering.  Would be a great addition.  The current grid system is great for general layouts however when displaying data from a database it would be nice to have a more flexible/powerful layout.

Thanks for your consideration and love your work on this project!

**Comment by elyas-bhy** [comment]
You might want to check out [angular-gridster](https://github.com/ManifestWebDesign/angular-gridster), a project inspired by [gridster](http://gridster.net/).

**Comment by erslater** [comment]
I have however gridster is no longer in development since New Relic aquired the maker of Gridster over a year ago.  I would prefer putting my time into something that is going to be maintained going forward.

**Comment by elyas-bhy** [comment]
[angular-gridster](https://github.com/ManifestWebDesign/angular-gridster) is _inspired_ by gridster, not based off of it. It is not a wrapper project.
Quoting the README of angular-gridster:

> An implementation of gridster-like widgets for Angular JS. This is not a wrapper on the original gridster jQuery plugin (http://gridster.net/). It is instead completely rewritten as Angular directives. Rewriting allowed for some additional features and better use of Angular data binding.

**Comment by naomiblack** [comment]
Sorry, this is out of scope for the forseeable future.
