### ISSUE TITLE
md-menu-bar must be within md-toolbar, otherwise backdrop causes issues

### ISSUE THREAD

**Issue by bwegrzyn** [angular/material#6446]
I ran in to a weird issue where I had to set the z-index of md-menu-bar to 100 in order to get the menu bar to be above the backdrop and work properly. The demo/code looks for a parent md-toolbar and sets this, so it appears that the md-menu-bar must always be nested within a md-toolbar or the backdrop will mess things up. 

However, setting md-menu-bar z-index to 100 causes it to be above the md-dialog backdrop (z-index of 80). My work around was to set the md-menu-bar.md-open to z-index 100 instead to be more inline with the md-menu-bar code that sets this z-index on a parent md-toolbar, but it would be nice if this was reworked to be more compatible with other components or at the very least be mentioned in the documentation.

**Comment by naomiblack** [comment]
@rschmukler is this intended?

**Comment by rkimaoui** [comment]
Hi there,
I have the same problem.
When i open md-menu-bar, the code sets z-index to 100 for the parent md-toolbar, after that, i can't close it from the toolbar.

**Comment by bushev** [comment]
The same problem. When I opened mdDialogue from the **second menu item**, ex: File -> New Project 

![image](https://cloud.githubusercontent.com/assets/7535766/12775660/43e55a70-ca82-11e5-9ca4-df1e8dd376be.png)

![image](https://cloud.githubusercontent.com/assets/7535766/12775653/386b5f46-ca82-11e5-8eeb-539344942267.png)

**Comment by alekece** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
