### ISSUE TITLE
md-chips feature request: allow copy from chips field

### ISSUE THREAD

**Issue by uriva** [angular/material#6449]
Currently it's difficult to copy contents of chips field.

**Comment by topherfangio** [comment]
Can you please add a little bit more information to this issue? It's very hard to understand what you mean by "copy". A usage scenario would be very helpful.

**Comment by uriva** [comment]
I mean use the mouse to select the text of all chips together and copy it somewhere else

**Comment by topherfangio** [comment]
I really feel like a better user experience (if you need this), would be to provide a button that copies it directly to the clipboard. If you had enough chips to make two lines, I imagine it would be difficult.

Why do you need them to copy/paste the chip's contents?

**Comment by uriva** [comment]
Same reason an HTML table is copyable

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
