### ISSUE TITLE
md-autocomplete doesn't allow values not in list

### ISSUE THREAD

**Issue by jpike88** [angular/material#6450]
Autocomplete is just that, an autocomplete. It shouldn't try to enforce a particular set of values unless it's told to. There are plenty of cases where it's more of a suggestion dropdown than an actual enforced list and that should be implemented.

The problem occurs when I defocus an autocompleted text field after entering data in it that doesn't match any results. The text seems to just disappear but is still selectable, and reappears on focus.

**Comment by jpike88** [comment]
It's more of a styling issue by the look of it.

Got around it by inserting this CSS inline:

md-input-container .md-input{
  color: rgba(0, 0, 0, 0.87) !important;
}

**Comment by uriva** [comment]
+1

**Comment by uditalias** [comment]
+1

**Comment by naomiblack** [comment]
cannot reproduce. could you provide a codepen?

**Comment by frenchynz** [comment]
+1

**Comment by splnty** [comment]
+1
