### ISSUE TITLE
Tabs content not flexable

### ISSUE THREAD

**Issue by emps** [angular/material#6453]
im tring make md-tab-body flex to be full page the problem is that after the render there is new div element  inserted that isnt flex so tab contect stays small while i need my md content inside the tabls be full page ,  fix can come ?
```
<div md-tabs-template="::tab.template" md-connected-if="tab.isActive()" md-scope="::tab.parent" ng-if="$mdTabsCtrl.enableDisconnect || tab.shouldRender()">
```
this elemnt should get some option for us to tell him be flex, for now i use some class at md-tabs that telling to that div height = 100%.

im using 
--
html:
```
<md-tabs flex class="tab-conter-div-100">
  ...
  <md-tab-body>
    <ui-view flex layout="column" layout-fill>
```
--
css:
```
.tab-conter-div-100 md-tab-content > div:first-child {
  height: 100% !important;
}
```
--
than i can use template for ui-view 
```
<md-contect flex>
```
as view to get full height content for each tab

**Comment by Abekonge** [comment]
Don't know if this is relevant. I had the same problem, but if I use the directive `md-tab-content` with the attribute `flex` instead of `md-tab-body` it works as expected:

```
<body layout="column">
  <md-tabs md-center-tabs flex>
      <md-tab label="Home">
        <md-tab-content flex>
          <h1>Content</h1>
        </md-tab-content>
      </md-tab>
    </md-tabs>
</body>
```

In the online documentation, in the demo of the tabs, the content is defined with `md-content` which has the same problem regarding full-page-height as the OP.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
