### ISSUE TITLE
 <md-toolbar> does not get displayed correctly

### ISSUE THREAD

**Issue by sudiptokc** [angular/material#6455]
md-toolbar does not get displayed correctly in browsers that does not support flex box. 

Example :  https://material.angularjs.org/latest/demo/toolbar , 
when this page is opened , it does not load the background color , alignment is completely messed up.

**Comment by topherfangio** [comment]
Angular Material uses flexbox extensively which is why we only support the latest browsers (current version + the last version of each).

On which browser/version are you experiencing issues?

**Comment by zeeshanhyder** [comment]
In IE 11, md-toolbar is appearing completely messed up after updating to version 1.0.1 in md-dialog. It doesnt take up entire width of the dialog and also the content inside md-dlalog doesnt get rendered unless we explicitly mention the height of dialog.

**Comment by topherfangio** [comment]
Thanks for the additional information. Everything looks right in IE11 on the demo page you linked above.

Would you be able to provide a very simple Codepen which demonstrates how you are using the toolbar inside the dialog so we can look at getting it fixed?

**Comment by zeeshanhyder** [comment]
@topherfangio Here is the demo i have made.
http://codepen.io/zeeshanhyder/pen/WrOzRJ
Also if you check it on other browsers, there is small full screen check box just below the button, which appears on all other browsers except IE 11.

**Comment by zeeshanhyder** [comment]
I think the issue is with flexbox on IE. Seeing the default css of md-dialog, you have specified layout-column, min-width,max-width but no explicit height which actually confuses IE. Here is the issue link
https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview
