### ISSUE TITLE
<md-input>, <md-select> can't release focus from mobile

### ISSUE THREAD

**Issue by bojancai** [angular/material#6457]
Since 1.0.0, input can't release focus while testing on https://material.angularjs.org/latest/demo/input from mobile (Google Nexus 5, Chrome version 47.0.2526.83 in my case), unless click on another input.

**Comment by sudiptokc** [comment]
+1

**Comment by 0101adm** [comment]
dup of #5365

**Comment by abinashpanda** [comment]
+1

**Comment by StefanCenusa** [comment]
+1

**Comment by naomiblack** [comment]
Community contribution welcome.

**Comment by EladBezalel** [comment]
dup of #5365
