### ISSUE TITLE
Material for Angular 2

### ISSUE THREAD

**Issue by krasevych** [angular/material#6458]
Hello.
I have one question, When will you make the Material for Angular 2?

**Comment by EladBezalel** [comment]
ngMaterial2 efforts are already in progress, the team is now focused on bug fixes for 1.0 and more components development, ngMaterial2 will grow as ng2 will grow.

**Comment by zwacky** [comment]
can you give some updates where to try/contribute the ng2 material repo?

**Comment by EladBezalel** [comment]
There's no official repo yet, some components were hard copied to [ng2 repo](https://github.com/angular/angular/tree/master/modules/angular2_material)

**Comment by femski** [comment]
What does "ngMaterial2 will grow as ng2 will grow" mean ? Angular Material 1.x has been released. ng2 itself is in  beta. But there has been no visible progress on ngMaterial2 in nine months.

**Comment by krasevych** [comment]
I have real project on ng1 and material 1.0.1. I want to try ng2 in my project, but I can't do it,  because I need material for ng2 beta.

**Comment by Koslun** [comment]
@femski @krasevych As far as I have understood it ngMaterial2 is very far from release. Wouldn't expect  anything close to parity until after the summer. Especially with ngAnimate2 not complete.

I think the best bet to use Angular 2 with material components in a very near future would be to use ngUpgrade or something else to wrap the directives and services of this library.

Using material v1 through ngUpgrade is being tracked in issue #6336. It's been flagged as high priority so would expect we'll hear more about the core team's opinion on the matter after the holidays.

**Comment by MilosStanic** [comment]
@krasevych +1
Failing to come up quickly with ng2-material can prove a deal breaker for many of us who want to switch their apps from AngularJS to Angular2 as soon as possible. 

I was thinking of using Material Design Lite as a substitute until ng2-material comes out. However, the thing I miss the most in MDL is the flexbox layouts. The positive side is that MDL is very fast. It is my subjective impression that it's much faster than angular-material. 

There is also this independent effort that looks nice, but I'm afraid a single person will not be able to keep up with the development: 
http://justindujardin.github.io/ng2-material/

**Comment by friksa** [comment]
+1

**Comment by leshin** [comment]
+1

**Comment by FrancescoRizzi** [comment]
I'll pitch a -1 here, sorry... at least for now.
Eventually yes, I'd like to see ng-material move to angular2, but I am worried of the focus being shifted to that update/rewrite while an angular1.x implementation of the material language is not yet complete. Is there any document illustrating how much of the material spec is covered by the current ng-material?

**Comment by zoechi** [comment]
https://github.com/angular/material2

**Comment by gshireesh** [comment]
+1
