### ISSUE TITLE
unable to get ng-model value of md-checkbox inside  md-list-item

### ISSUE THREAD

**Issue by ganeshkumarj** [angular/material#6461]
```html
<md-list ng-cloak flex >
    <md-list-item ng-repeat="topics in courseList" >
        <p> {{topics.courseDesc}}</p>
        <md-checkbox class="md-secondary"  ng-model="topics.name"></md-checkbox>
    </md-list-item>
</md-list> 
```
unable to retrieve checkbox value.

How to retrieve checkbox value since it is inside list.
each one going to carry same name topics.name

if I add ng-click event in md-checkbox then by clicking list item md-checkbox not checked/unchecked

**Comment by topherfangio** [comment]
Can you please provide a Codepen which shows the issue you are having so that we can modify/update it with some options?

**Comment by DevVersion** [comment]
@ganeshkumarj I tried to reproduce your issue (http://codepen.io/DevVersion/pen/xZPzpL), but I'm not sure what you mean about retrieving the `ngModel`, everything works fine there.

**Comment by ganeshkumarj** [comment]
@DevVersion Perfect this was my need. for me it was not working may be i done in work way. thank you
