### ISSUE TITLE
ng-messsages doesn't work when the field is filled by autocomplete

### ISSUE THREAD

**Issue by stunaz** [angular/material#6462]
The check is not triggered when the field is filled by autocompletion, i.e. when for example the `input` element as the attribut `autocomplete='email'`.

**Comment by topherfangio** [comment]
This is related to #1376. There is currently way to be notified of when the browser auto-fills a field. We are continuing to investigate solutions.

**Comment by stunaz** [comment]
just adding here that I am using Safari 9.0.2 , and it is not an autocompletion by stored username/password.

**Comment by leshin** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
