### ISSUE TITLE
Allow md-scroll-shrink on md-tab

### ISSUE THREAD

**Issue by CxRes** [angular/material#6464]
On small screens/long pages it is painful to scroll up to change page tabs when they are hidden to save real estate. Please implement md-scroll-shrink for md-tab or $mdScrollShrink service for any element.

**Comment by topherfangio** [comment]
Do you mean `$mdSticky`? You want the tabs to stick to the top of the screen, not disappear as you scroll right?

**Comment by CxRes** [comment]
No, I mean md-scroll-shrink. I want the tabs to disappear as I scroll down - real estate is limited on mobile devices!

**Comment by EladBezalel** [comment]
dup #1054
