### ISSUE TITLE
bottomsheet slideIn animations not working.

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6468]
bottomsheet open animation sometimes (most of the time) doesnt happen.  the close animation seems to happen regularly.

https://material.angularjs.org/1.0.1/

**Comment by DevVersion** [comment]
I checked it out. It is an issue from the $animate, because we inserting the bottom sheet at `y = 0` and then we try to move that down `y = -100%` and directly after that we try to move that again up to `y = 0`. So we need to move the bottom sheet before insertion `y  = -100%` down

**Comment by 0101adm** [comment]
:+1:

**Comment by hughred22** [comment]
Same issue here in 1.0.5. Any hack to fix it temporary?

**Comment by aidarbuy** [comment]
+1 same issue in 1.0.5.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
