### ISSUE TITLE
Grid list codepen demo seems to be broken

### ISSUE THREAD

**Issue by mackelito** [angular/material#6469]
Looking at your example on codepen (clicking on the codepen icon on https://material.angularjs.org/latest/demo/gridList you can see that the demo is broken when using "1.0.1-master-a687bfc".

Swapping this to to eg "https://ajax.googleapis.com/ajax/libs/angular_material/0.11.2/angular-material.min.js" and the demo works again :)

**Comment by mackelito** [comment]
Just noticed that the demo is broken when using "https://ajax.googleapis.com/ajax/libs/angular_material/1.0.0/angular-material.min.js" as well

**Comment by jozsi** [comment]
Unfortunately the grid is appears to be broken on mobile (the demo and my previously working implementation as well). It works on desktop or if you resize it to mobile, but not when initially in mobile.

**Comment by EladBezalel** [comment]
Checked with HEAD and it seems like it was solved,
