### ISSUE TITLE
Add support for less pre-processor

### ISSUE THREAD

**Issue by rayshan** [angular/material#647]
Hope it's not a dupe, tried to search for it but less is a very generic term.

**Comment by nfriend** [comment]
Just a note - [the Angular CLI includes support for creating apps that use LESS using the `--style` parameter](https://github.com/angular/angular-cli/wiki/new):
```bash
ng new my-app --style=less
```
So this is one reason people (like me :) ) might expect Angular Material to support LESS.

**Comment by Splaktar** [comment]
@nfriend Just FYI, This repository is for AngularJS Material, not Angular Material. So mentioning the Angular CLI is not relevant here.

**Comment by nfriend** [comment]
@Splaktar Ah, my bad!  The repository name threw me off.
