### ISSUE TITLE
Custom Intention Classes

### ISSUE THREAD

**Issue by SirDarquan** [angular/material#6471]
I've only been following #1269 for a few weeks and am now wondering it's status. It feels like a good solution to help understand what colors are being used but I believe it's too complicated. Why should we have to use JavaScript to figure out what colors to use when CSS can be generated to do the same thing with no performance overhead. I don't mean any offence but md-colors feels tacked on and I'd be more interested in a system that allows us to develop in the same manner that the material project uses. Let me give an example.

Let's say I wanted to create a dialog header component that uses the primary color as it's background but could also an intention group to alter the color. It might look something like this:
```html
  <my-dialog-header class="md-primary">
    Dialog Heading
  </my-dialog-header>
```
The angular material project creates a themeCSS string that describes all the styles for its components using a special theming expressions syntax used to generate the css. I should be able to use that syntax also. My dialog theme css would look like this:
```CSS
md-dialog my-dialog-header.md-THEME_NAME-theme.md-primary{ background-color: '{{primary-color}}'; }
```
Also following in the angular material footsteps, I would take the above css string and set it in an angular constant:
```javascript
angular.module("myDialogHeader", ['$mdThemingProvider']).constant("myDialogHeaderCSS", "md-dialog my-dialog-header.md-THEME_NAME-theme.md-primary{ background-color: '{{primary-color}}'; }");
```
Everything I've done up to this point is already possible but there is no way to do anything with it because the theming  provider is hard-coded to find the $MD_THEME_CSS constant. I'm going to propose changes to allow my component theme to become a first class citizen in the style sheet.

First, there needs to be a function that registers the constants that contain themes added to the $mdThemeProvider. It might look something like this:
```javascript
    var componentCssRegistry = [];
    function registerComponentCSS(string componentConstantName){
        if(componentCssRegistry.indexOf(componentConstantName) == -1){
            componentCssRegistry.push(componentConstantName);
        }
    }
```
Next, the `generateAllThemes` method would be modified to retrieve all the registered theme constants and append them to the themeCSS variable used to generate the themes. I'll only include the relevent parts of `generateAllThemes`:
```javascript
  var firstChild = head ? head.firstElementChild : null;
  var themeCss = $injector.has('$MD_THEME_CSS') ? $injector.get('$MD_THEME_CSS') : '';

  angular.forEach(componentCssRegistry, function(value){
    themeCss += $injector.has(value) ? $injector.get(value): '';
  }

  if ( !firstChild ) return;
  if (themeCss.length === 0) return; // no rules, so no point in running this expensive task
```
There maybe a function to validate that the text in the external themes are valid but the currently doesn't exist. But now my components follow the same rules as native components without special directives or run time processing to get it to do so.

 If I'm oversimplifying this then i apologize for my ignorance but this seems to me to be the easiest way to get what we want in the code base.

**Comment by reppners** [comment]
+1 

I think this approach is the best. Make it possible to re-use what the library does to get the job done. Maybe provide a gulp/grunt task to do the required post-processing on the *-theme.scss files.
