### ISSUE TITLE
feat(bottomsheet) open without backdrop

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6473]
just like sidenav.

**Comment by DevVersion** [comment]
You mean like #6343

**Comment by EladBezalel** [comment]
@DevVersion i'd suggest you would add this to your PR

**Comment by 0101adm** [comment]
@DevVersion yep :+1:

**Comment by DevVersion** [comment]
@EladBezalel, @0101adm - It's a now an option in the interim element
