### ISSUE TITLE
$mdutil.findFocusTarget uses scope() which will not work if debug information is turned off

### ISSUE THREAD

**Issue by geersch** [angular/material#6474]
function scanForFocusable(target, selector) {
        var elFound, items = target[0].querySelectorAll(selector);

        // Find the last child element with the focus attribute
        if ( items && items.length ){
          var EXP_ATTR = /\s*\[?([\-a-z]*)\]?\s*/i;
          var matches = EXP_ATTR.exec(selector);
          var attribute = matches ? matches[1] : null;

          items.length && angular.forEach(items, function(it) {
            it = angular.element(it);

            // If the expression evaluates to FALSE, then it is not focusable target
            var focusExpression = it[0].getAttribute(attribute);
            var isFocusable = !focusExpression || !$mdUtil.validateScope(it) ? true :
                              (it.scope().$eval(focusExpression) !== false );

            if (isFocusable) elFound = it;
          });
        }
        return elFound;
      }

The scope() function is only available if debug information is available! Evaluating the expression assigned to the focus attribute will break as soon as this is turned off in production.

**Comment by Frank3K** [comment]
This isn't the first issue where `scope()` is used, see also e.g. #6033. Is this some that can be tested automatically using e.g. karma?
