### ISSUE TITLE
md-contact-chips($query)

### ISSUE THREAD

**Issue by armangevorgyan** [angular/material#6475]
![untitled](https://cloud.githubusercontent.com/assets/13254080/12017995/901a872a-ad6e-11e5-9381-0e316ad30cd1.jpg)
Why don't check first P?? Thank you

**Comment by topherfangio** [comment]
Can you try adding `md-highlight-flags="i"` to your `<md-chips>` element? This should set the filtering to be case-insensitive.

https://material.angularjs.org/latest/api/directive/mdHighlightText
