### ISSUE TITLE
Problem with multiple md-auto-complete directives

### ISSUE THREAD

**Issue by prakashjp123** [angular/material#6478]
I am trying to use two `md-autocomplete` directives. In which one has `md-not-found` directive and another doesn't have it. Now both are not showing the not found template.

I have cloned the demo from md-autocomplete [here](http://codepen.io/anon/pen/gPLbeg)

**Comment by DevVersion** [comment]
Should be fixed in there #5867

**Comment by naomiblack** [comment]
dup #5865
