### ISSUE TITLE
error in md-datepicker

### ISSUE THREAD

**Issue by confeccionar** [angular/material#6479]
if I select the date format is dd / mm / yy but if I write the date format is mm / dd / yy, I can make it the same writing format that selecting

**Comment by skosno** [comment]
Can you post example in codepen and/or your configuration of datepicker service?

**Comment by confeccionar** [comment]
http://codepen.io/anon/pen/PZWXPY

**Comment by jelbourn** [comment]
Internationalization is done through the `$mdDateLocaleProvider`. Please see the [documentation](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider).

The issue of the demo not being internationalized can be tracked in #4671
