### ISSUE TITLE
Erratic height in md-virtual-repeat-container even in the online demo for md-autocomplete

### ISSUE THREAD

**Issue by tordhr** [angular/material#6480]
Replication steps:
1 Visit https://material.angularjs.org/latest/demo/autocomplete
2 Issue is found in all the examples, for testing sake lets pickup the first example i.e. Basic Usage, click on the field to see the options as in below screenshot

![image](https://cloud.githubusercontent.com/assets/9679885/12021047/118c596e-ad9c-11e5-930a-9be47d4634c6.png)

3 Select any option, lets say Alabama which becomes selected
4 Press Cross/Cancel button to clear and select another option or even the same option once again
5 Repeat through step 3 and eventually suggestion box shows only 1 option as in below screenshot

![image](https://cloud.githubusercontent.com/assets/9679885/12021077/4bd15502-ad9c-11e5-976e-efb722f80ca4.png)

Sometimes this behavior appears within single iteration from step 3-5 and at times, we have to do it 4-5 times which is quite erratic in nature. I tried adding style="height: 480px" alongside md-autocomplete which didn't work. Also tried, md-virtual-repeat-container{ height: 480px; } in CSS, which didn't help either.

Testing Environment
Browser: Chrome 46.0.2490.86 (64-bit)
OS: Ubuntu 14.04.3 LTS

**Comment by alexisgahon** [comment]
Very annoying bug ! +1

**Comment by romain-poirson** [comment]
Hello,
I also confirm I have the same problem (Ubuntu 15.10 & Chrome 46.0.2490.80 (64-bit)

**Comment by kseamon** [comment]
This will be fixed by #6394, which still is having some issues with CI that need resolving.

**Comment by kseamon** [comment]
Fix should go out in the next release.
