### ISSUE TITLE
animate text fields

### ISSUE THREAD

**Issue by confeccionar** [angular/material#6481]
They can make the animation of the text fields as it does in http://ui.lumapps.com/directives/text-fields

**Comment by DevVersion** [comment]
I think this animation is not desired, because it's not in the Material Specs

[See here](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B7WCemMG6e0VcHFla0dwOE5pVVE/forms-supportive-content-v3_xhdpi.webm)

**Comment by confeccionar** [comment]
polymer is not material design ? https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input

**Comment by EladBezalel** [comment]
@confeccionar polymer is another implementation of material design, 
we follow the spec, as much as i like the animation you mentioned, it's not a part of the material spec and therefore not part of our project.
