### ISSUE TITLE
mdToast position in small (<960) screen size

### ISSUE THREAD

**Issue by HW-Siew** [angular/material#6487]
The position of mdToast seems to be reset to default position in small screen even position parameter was set. Is that any way to override this behavior? Thank you.
![untitled](https://cloud.githubusercontent.com/assets/10137637/12029508/b1d64264-ae27-11e5-8886-c15b6eab52d7.png)

**Comment by EladBezalel** [comment]
@HW-Siew there's no option to override this behavior, this behavior is following the spec, however i do agree that <960 is way to much and we should consider lower that to xs breakpoint.

**Comment by EladBezalel** [comment]
@HW-Siew according the spec, toast should be full width bottom only on moblie

![landscape](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsa1VjR0RYWEpZZUE/components_toasts_mobile3.png)

according the resonsive ui section 
![respo](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B8olV15J7abPSGFxemFiQVRtb1k/layout_adaptive_breakpoints_01.png)
mobile defined `<960` on landscape

**Comment by HW-Siew** [comment]
Hi, @EladBezalel. Thank you. I missed out the spec.

**Comment by code-tree** [comment]
I display a toast when a bottom toolbar button is pressed, and on small screens the toast appears over the button that was just pressed, preventing further use of the toolbar until the toast disappears.

I understand we are to follow the spec here, but could you suggest an alternative? As it seems like a bit of an oversight (in the spec)...

**Comment by johndshea** [comment]
The problem with this default (and with not providing an override) is that mobile devices aren't the only case of small viewports. I'm developing a chrome extension, for instance, which has a max 600x800 viewport, and not being able to place toasts at the top of the view was a real pain. For others who might be having the same issue, here's how I overrode it: 

`md-toast {
  position:fixed;
  top: 0px;
}`

**Comment by avreddy1996** [comment]
What they actually thought is the same as @EladBezalel  said but what is happening id toast coming at bottom of div not the bottom of screen they missed this point until this is fixed use media queries

@media(max-width : 960px){
    md-toast{
        position: fixed;
        bottom: 0;
    }
}
