### ISSUE TITLE
md-autocomplete md-no-cache attribute not working as expected. 

### ISSUE THREAD

**Issue by nhanly** [angular/material#6489]
The md-no-cache attribute set to "true" for disabling the internal caching of md-autocomplete only work s correctly after one or two time select the input . If i try multiple times this will automatically cache the first selection that has been made.

**Comment by naomiblack** [comment]
Please submit a reproduction case with codepen? This isn't enough information.

**Comment by AnkitGupta88** [comment]
Same problem. For a while it shows last response.

**Comment by AnkitGupta88** [comment]
Don't close this ticket. Please share the resolution.

**Comment by AnkurChoraywal** [comment]
is this issue fixed ?
