### ISSUE TITLE
A wysiwyg editor?

### ISSUE THREAD

**Issue by Nowis** [angular/material#6490]
Hello there,

I was wondering if a wysiwyg would be implemented in Angular Material.
If not, does someone have a solution of what using in replacement? The wysiwyg I saw on the web were not suitable with material design.

Thanks.

**Comment by EladBezalel** [comment]
@Nowis there's no mention of wysiwyg editor on the spec so for now, there's no intention to do one.
[Toggle buttons](https://www.google.com/design/spec/components/buttons.html#buttons-toggle-buttons) are planned and with them and the menu you can easily create very basic one

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
