### ISSUE TITLE
md-datepicker italian language

### ISSUE THREAD

**Issue by davidedellai** [angular/material#6491]
Is it possible translate the datepicker in another language? For example, instead have as label:
december, have "Dicembre"? In italian. Thanks

**Comment by DevVersion** [comment]
For questions, you should normally use the Google Group ([here](https://groups.google.com/forum/#!forum/ngmaterial)).

But I will answer the question here.

```
myAppModule.config(function($mdDateLocaleProvider) {
  // Example of a French localization.
  $mdDateLocaleProvider.months = ['janvier', 'février', 'mars', ...];
```

There is a provider for the datepicker which is called `$mdDateLocaleProvider`, you can modify a few settings there (see more [here](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider))

**Comment by davidedellai** [comment]
Thanks it's working with the standard picker. Now see this one: https://github.com/alenaksu/mdPickers it's based on the picker of the angular material but restyled. I tried to use the same config but not works. Can you help me to understand why? If of course it's possible mantain this question open. Thanks

**Comment by FrancescoRizzi** [comment]
Seems that the mdPickers library is not (currently) using the angular material locale provider.

**Comment by davidedellai** [comment]
@FrancescoRizzi ok thanks. Well i think i will change the picker. Thanks again guys

**Comment by DevVersion** [comment]
If you actual question is answered, you can close the issue.
