### ISSUE TITLE
JPG scaling problem (image stretched) on card in chrome  48.0.2564.48 beta

### ISSUE THREAD

**Issue by daniel79** [angular/material#6492]
Here is code pen with example:
http://codepen.io/anon/pen/BjLVbE

Uncomment line in js to see it works for png.

**Comment by daniel79** [comment]
Created chromium issue:
https://code.google.com/p/chromium/issues/detail?id=572844&thanks=572844&ts=1451390844

**Comment by EladBezalel** [comment]
This issue is not related to our project.
