### ISSUE TITLE
md-toolbar and flex options not working as expected

### ISSUE THREAD

**Issue by 4tron** [angular/material#6499]
I am using a basic flex option
`flex-offset-gt-md="15" flex-gt-md="70"` 

offset 15 for each side and 70 for the main content 

```
<md-toolbar>
    
    <div class="toolbar-wrapper" flex-gt-md="70" flex-offset-gt-md="15">
         <div class="md-toolbar-tools">
                         content here
        </div>
    </div>
    
</md-toolbar>
```

This however does not work in the way that one might expect. 
![derp](https://cloud.githubusercontent.com/assets/11210554/12051516/9fc7bfbc-af0d-11e5-8193-99ecd206f6c5.png)

There is a odd space on the right that it out of place and it is not in the position it should be based on flex options. A quick fix is just to change the md-toolbar into a div.

**Comment by topherfangio** [comment]
Can you please add a Codepen demo that shows the exact issue? I copy/pasted your code from above, but it's not really showing anything relevant.

**Comment by 4tron** [comment]
Sorry i cant recreate it , nor find the original code , it had been a very long day. I think it had something to do with the outer flex i was using , not sure .. anyways its closed
