### ISSUE TITLE
attr hide-sm not functioning in Angular1.0

### ISSUE THREAD

**Issue by mtdegoes** [angular/material#6503]
I'm using AngularMaterial1.0.1 and the hide-sm attribute doesn't function. With my specific implementation, I'm hiding several md-button elements in a header menu. HIDE-SM doesn't apply any style additions, when inspecting the CSS.

**Comment by DevVersion** [comment]
`hide-sm` works well by using the latest Material Build ([See here](http://codepen.io/DevVersion/pen/rxWQrz)). As `hide-sm` just says, it will only hide between a screen size of `600px` and `960px`

**Comment by stunaz** [comment]
works well, be aware that they were a breaking change, that they add a `hide-xs` which hide for screen  `< 600px` .  (the old definition on `hide-sm`)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
