### ISSUE TITLE
Clear md-select

### ISSUE THREAD

**Issue by cleever** [angular/material#6504]
How can I clear md-select value without external control/code?

In md-autocomplete we have the clear button or we can use a delete or backspace to clear.

But in md-select, I don't see any option to clear.

**Comment by skosno** [comment]
mg-select is basically based on https://www.google.com/design/spec/components/menus.html#menus-specs and also standard browser select, that does not really have "clear" option.

You can try solutions similar to standard select like adding "empty" option:
http://codepen.io/anon/pen/pgNXjv

Downside is that it looks like standard option so you would need to add some custom style to that "empty item" so it looks more like placeholder. Additionally if label is to be used it would have to be hidden (if you are using approach with labels appearing only if value is in input):
http://codepen.io/anon/pen/obYrjo

**Comment by EladBezalel** [comment]
@skosno thanks for your answer :smile:

**Comment by sterry79** [comment]
In order to use ng-required with md-select and empty options was to simply create a hidden input element that had the ng-model tied to the md-select ng-model.
