### ISSUE TITLE
md-separator-keys ignores shift

### ISSUE THREAD

**Issue by vbraun** [angular/material#6505]
The md-chips custom keys ignore shift (and other modifiers), so if "," is a separator then "<" is also a separator and cannot be part of a chip. This was sort-of ok with tab and enter, but starts getting awkward with custom separators.

Steps to reproduce: 
* Go to the "custom separator keys" demo at https://material.angularjs.org/HEAD/demo/chips
* Try to enter "1<2" as a tag

**Comment by EladBezalel** [comment]
I think our implementation for separator keys (chips) is not full, 
There's a `,` (comma) separator but when trying to write `<` (which is `shift+,`) it doesn't work because we don't take in account shift, alt or ctrl keys.
We should have in mind that changing this is a breaking api, but it must be done. 
I've thought about extending our api to get a list (as now) but each element will be an object that the key (of the object) will be the key (number of key pressed) code and the value will be an object that contains 
```js
{ 
  alt: false, 
  ctrl: false, 
  shift: true
}
``` 
for example.
This means that we also provide key combination for separator, which is a nice feature.
@ThomasBurleson @jelbourn @topherfangio Any thoughts?

**Comment by topherfangio** [comment]
We should definitely avoid shift as that disallows the < character and I
can see some people wanting to use it.

**Comment by noypi** [comment]
maybe allow users to customize this condition:
if (this.separatorKeys.indexOf(event.keyCode) !== -1) {

as a workaround, i have to override ""indexOf""".

**Comment by topherfangio** [comment]
@noypi Can you explain your comment a bit more, or provide a Codepen? I'm not sure I understand what your issue is.

**Comment by noypi** [comment]
example at: https://material.angularjs.org/latest/demo/chips
scroll down to "~Add custom separator key codes such as semicolon for e-mails.~" section:

with chrome (Version 48.0.2564.109 m), there is no way to differentiate between a ""colon""" and a """semicolon""" for a separators. the example will create chips if a """colon""" is entered.

**Comment by topherfangio** [comment]
@noypi Thanks; I definitely understand the issue now.

@EladBezalel Perhaps we should create a `$mdKeyboard` service (or something) to handle the key events and track which actual character was pressed. For instance, it would be great if our code could call something like

```js
var separators = [':', ';', ','];
var character = $mdKeyboard.whichCharacter(event);

if (separators.indexOf(character) !== -1) {
    ...
}
```

In this case, all of the special logic for reviewing the keycode/meta keys would be contained in the service and we could specify just the characters.

Thoughts?

**Comment by EladBezalel** [comment]
@topherfangio sounds like the right direction

**Comment by DevVersion** [comment]
@EladBezalel @topherfangio The correct character of the event can be easily retrieved by a `keypress` event. Using the following snippet.
```js
alert(String.fromCharCode(event.which)); 
```

`keypress` should be fine to be replaced with `keydown`.
eg. If you press <kbd>Shift</kbd> + <kbd>A</kbd>, you'll get:

- `keydown`: <kbd>Shift</kbd>
- `keydown`: <kbd>A</kbd>
- `keypress`: Char: <kbd>A</kbd> (if no Shift, it would be <kbd>a</kbd>)
- `keyup`: <kbd>A</kbd>
- `keyup`: <kbd>Shift</kbd>

**Comment by jayj** [comment]
The demo for "custom separator keys" using semicolon is also broken on Danish keyboards. The '186' key code used as semicolon separator is also used for the letter 'æ', so every time you write 'æ' it adds a new chip.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by vbraun** [comment]
Reopened as #8319
