### ISSUE TITLE
bug(md-select): untouched on focus out

### ISSUE THREAD

**Issue by kamilkisiela** [angular/material#6506]
After focusing on md-select by pressing TAB and then focusing out the `$untouched` is being set to `false` but then it comes back to `true`.

http://codepen.io/kamilkisiela/pen/QyGJeG

**Comment by mckenzielong** [comment]
```javascript
$mdUtil.nextTick(function () {
      element.on('blur', function() {
       if (untouched) {
          untouched = false;
          ngModelCtrl.$setUntouched();
       }
```

First cycle through will trigger the setUntouched, and any others will not.  So cycling a second time will trigger the expected behaviour.  I only see the untouched variable is only used here.

My guess as to why this is here:  the blur is called twice on a mouse interaction, first when the select is opened, and then when the menu is blurred (second click after closing).  I think the goal was to hide the required message until the menu is finally closed (which it does in a some what janky way).

**Comment by ThomasBurleson** [comment]
Community contribution welcome! ;-)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (407/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:47231 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avrw2-001GOK-TY
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 21:49:21 +0200
Date: Thu, 28 Apr 2016 12:46:32 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461872793;
	bh=HFzpU18FoZ6chgwTgGjJEyLsEHPYJzJOiHAE/TiL1AY=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=KxuFEWuvg5n4Y8xB7a8sutNXmV/NF49y/KX5MhWNhnz2swOA96vfACV52FiUNAt6v
	 Dt8uaQN6qu1PMUqKNNn/cVCgqRbiDCimJrTYYdIY+TYohO2jV8voFcujnSVPtKpqk1
	 pwwQX9zKlr+wIP+6tNJN12ZGN7ittdvNLhc9SURw=
