### ISSUE TITLE
md-switch doesn't as expected when inside an ng-if

### ISSUE THREAD

**Issue by mimani** [angular/material#6508]
Hi, 

Data binding of md-switch breaks when it is inside some ng-if as shown in this [codepen](http://codepen.io/anon/pen/qbqgJR).

When it is inside ng-if, if we change the model value in controller, it does not bind that in view.

**Comment by skosno** [comment]
Hi,

This is not material/md-switch issue, you made scope mistake - ng-if is creating new scope, so in your example "data1" initially inherits value from parent scope, but as this is primitive value (boolean) it is not really referring the parent scope variable. So if you change "data1" inside "ng-if" you are not really changing that value on "SwitchDemoCtrl". This is the famous "use dot in your model" issue.

To fix it just pass data1 same as you did with "cb5", as a property on "data" object:
http://codepen.io/anon/pen/JGbQjN

Please close this issue if you find this explanation enough (let's help material team clean issues).

**Comment by mimani** [comment]
@skosno Thanks for the explanation.
