### ISSUE TITLE
feat(md-sidenav) on open / on close

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6509]
on open callback.

would like to see it fire when the animation ends.

**Comment by DevVersion** [comment]
You can simply hook into the the [promise](https://github.com/angular/material/blob/master/src/components/sidenav/sidenav.js#L231), but there is no way to access the variable from the controller, so you need to use `$toggleOpen` for `closing / opening` the sidenav.

But the important thing is, don't use the `mdSidenav` service, you should use the clean directive controller.

**Comment by 0101adm** [comment]
:+1:
