### ISSUE TITLE
Cannot position FAB in scrolling tab content

### ISSUE THREAD

**Issue by dnd** [angular/material#6510]
It seems to currently not be possible to position a FAB inside of scrolling tab content. md-tab seems like it tries to find the highest up parent md-content to attach itself to, and make that the scrolling container(which is wrong, as it causes the tab bar itself to scroll out of view). Unless the FAB is placed outside of this topmost md-content element the button will either start positioned in what looks to be the correct location and scroll with the page, or be in the correct position out of view, and scroll with the page.

A FAB is almost always specific to a given tab especially so on mobile where the tab is usually the entire viewport, so it should be able to be defined inside of the tab definition or at least near it or connected in some way and positioned properly.

**Comment by topherfangio** [comment]
Can you please provide a Codepen which demonstrates the issue you are having? Typically, each tab would have it's own `md-content` with the FAB as a sibling using one of the positioning classes such as `md-fab-bottom-right` which will absolutely position it at the bottom right of the screen.

**Comment by dnd** [comment]
http://codepen.io/anon/pen/adpgvZ As you'll be able to see, the FAB is down at the bottom of the scroll area on the tab. Tab 1 shows the FAB as a child of the md-content, and tab 2 shows the FAB as a sibling.
