### ISSUE TITLE
Required inputs as spec

### ISSUE THREAD

**Issue by FrancescoRizzi** [angular/material#6511]
Looking at the latest update to the Angular Material spec ([Dec. 2015](https://www.google.com/design/spec/whats-new/whats-new.html)), I noticed an update about [Required Text Fields](https://www.google.com/design/spec/components/text-fields.html#text-fields-search-filter):

> To indicate that a field is required, display an asterisk (*) next to the field. At the bottom of the form, include a note explaining that an asterisk indicates a required field.
> 
> Helper text, or hint text, should appear below the text field and either be persistently visible, or only visible on focus.

Mind you, the given video example shows the asterisk at the end of the field label (while the spec above talks about placing it `next to the field`, but regardless...

Due to the timing of the spec update, I'm not surprised the v.1.0.0, 1.0.1 and HEAD are not yet matching this detail, but I wonder if it could be an enhancement for future version.

**Comment by ThomasBurleson** [comment]
Duplicate
