### ISSUE TITLE
Unexpected behaviour on md-select with ng-selected

### ISSUE THREAD

**Issue by aldo-roman** [angular/material#6512]
Hi everyone,

I'm using the md-select component and want to have it to represent a model with default options. Given the app, it would be easier to handle this on the view and not in the controller (many controllers using the same view, means many changes to maintain).

Expected behaviour:
`foo == null` => `One is selected`
`foo == 3` => `Three is selected`

Found behaviour:
`foo == 3` => `Three is selected`
- Everything all right

`foo == null` => `One is selected`
- model gets `1` as value, but md-select is not updated, no md-option displayed
- click on `md-select`, then click outside, `foo` miss its value
- click on `md-select`, pick a value, everything works as expected

Also, there is an extrange flickering with `label`, in my app it is quite more visible.

Reproducing bug in:
https://jsfiddle.net/mmoj9867/2/

Thanks!

**Comment by mckenzielong** [comment]
$scope strikes again.  Using controller as syntax avoids confusing scope being referenced.  See this updated fiddle https://jsfiddle.net/mmoj9867/3/

**Comment by ThomasBurleson** [comment]
Use `ControllerAs` syntax.
