### ISSUE TITLE
md-calendar unit test fails on 31 Dec 2015

### ISSUE THREAD

**Issue by ericgundrum** [angular/material#6513]
```
PhantomJS 1.9.8 (Mac OS X 0.0.0) md-calendar calendar construction should have ids for date elements unique to the directive instance FAILED
	TypeError: 'undefined' is not an object (evaluating 'dateElement.id')
	    at https://github.com/angular/material/blob/master/src/components/datepicker/calendar.spec.js#L355
```

This test fails on 31 Dec 2015. Unfortunately this test uses different data depending on what date it is run. (See https://github.com/angular/material/blob/master/src/components/datepicker/calendar.spec.js#L340)

If I correctly understand what I see in the debugger, the test is searching for the 31st day of September instead of the 31st day of December. The next time these failure conditions will occur is 30 May 2016.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
