### ISSUE TITLE
input type of md-autocomplete should not be hardcoded

### ISSUE THREAD

**Issue by Yannic92** [angular/material#6517]
Currently the input type of the input field used for md-autocomplete is "search".

I know about #2699, but it would be nice to have a choice.

My problem is that Androids Keyboard uses a lense for the submit button on inputs with type="search".
I don't use md-autocomplete as pure search field. In fact it is an input field for a new item on a shopping list. I use md-autocomplete to suggest previously added items. 

I don't want to have a lense at the Android keyboard. The default arrow would fit better

**Comment by RolandHeath** [comment]
Related #5040

**Comment by ThomasBurleson** [comment]
Community contribution encouraged!   ;-)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
