### ISSUE TITLE
display side by side 

### ISSUE THREAD

**Issue by kerocode** [angular/material#6520]
how i display label side by side next to input field?

**Comment by dnd** [comment]
The Material Design spec does not define inputs that way. Labels are inside the field, or floating above it. So you would probably be on your own for trying to style that. 

https://www.google.com/design/spec/components/text-fields.html

**Comment by EladBezalel** [comment]
@dnd thanks!
@kerocode more than that, this kind of questions should be asked in our [forum](https://groups.google.com/forum/#!forum/ngmaterial).
