### ISSUE TITLE
mdDialog can only shows once

### ISSUE THREAD

**Issue by Eden-Sun** [angular/material#6525]
http://codepen.io/anon/pen/rxjqao?editors=101
The first button is normal .
I try to bind $scope on the second button dialog , then it only works once.
I have no idea if it is an issue.

**Comment by jmcmullen** [comment]
+1

**Comment by patrickjahns** [comment]
I also came across this issue yesterday - any news?

**Comment by divyekhanna** [comment]
+1

**Comment by jmcmullen** [comment]
The solution that I used for this issue is to send back data with a flag inside the `$mdDialog.hide()` then creating a second dialog from there. Here's an example: 

https://gist.github.com/jmcmullen/b027adf46eccf9e1a299
