### ISSUE TITLE
autocomplete: Value is deleted after focus of numeric input

### ISSUE THREAD

**Issue by moktec** [angular/material#6526]
When i try to use the AutoComplete Directive in Angular-Material (1.0.1).
If the Input is numeric, it will be deleted after losing the focus!! 

Original Code (focus-function) from angular-material.js in the controller MdAutocompleteCtrl:

```javascript
/**
Handles input focus event, determines if the dropdown should show.
*/
function focus () {
hasFocus = true;
//-- if searchText is null, let's force it to be a string

if (!angular.isString($scope.searchText)) $scope.searchText = '';

if ($scope.minLength > 0) return;
ctrl.hidden = shouldHide();
if (!ctrl.hidden) handleQuery();
}
```
Possible Solution to fix the deletion of numeric value if the input field is focused:
```javascript
/**
Handles input focus event, determines if the dropdown should show.
*/
function focus () {
hasFocus = true;
//-- if searchText is null, let's force it to be a string

if ($scope.searchText === null || angular.isUndefined($scope.searchText)) $scope.searchText = '';

if ($scope.minLength > 0) return;
ctrl.hidden = shouldHide();
if (!ctrl.hidden) handleQuery();
}
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
