### ISSUE TITLE
$mdDialog

### ISSUE THREAD

**Issue by kanchanpd** [angular/material#6527]
I am trying to implement Confirm Dialog of angular material using exactly the code given in angular material official site(https://material.angularjs.org/latest/demo/dialog) ,but I am getting error as mentioned below I have injected the services  $mdDialog,$mdMedia in my controller also. 

Error   
TypeError: $mdDialog.alert(...).clickOutsideToClose(...).title(...).ariaLabel(...).ok(...).openFrom is not a function.

**Comment by eshansingh** [comment]
The most likely problem is your Angular Material version. If you're using bower, update your `bower.json` to refer to `~1.0.3` and then run `bower update`. If you downloaded manually, download the latest version now.

**Comment by DevVersion** [comment]
Yes, everything works as expected with the latest version.

- http://codepen.io/DevVersion/pen/zqZZJO
