### ISSUE TITLE
Layout issue with flex and layout breakpoints

### ISSUE THREAD

**Issue by HendrikWansing** [angular/material#6528]
Hi,

we ran into an issue with the layout changes in Angular Material 1.0.0 or 1.0.1.
We want a column layout on mobile device and a row layout on desktop, where the second div has a 40% width  and 100% height on row-layout and 40% height and 100% width on column-layout.

Example Code ( http://codepen.io/anon/pen/yegQBm ):
<div layout="column" layout-gt-sm="row" layout-fill>
  <div flex></div>
  <div flex="40"></div>
</div>

If the wrapper has layout="column" and layout-gt-sm="row", the max-width is not set correctly on  larger width than sm.

The same problem appears if I change the layout to 
layout-xs="column" layout-sm="column" layout="row" ( Code: http://codepen.io/anon/pen/pgRQvX ) or
layout-xs="column" layout-sm="column" layout-gt-sm="row"

**Comment by smashercosmo** [comment]
Yep, this is very critical issue

**Comment by keenondrums** [comment]
Pull request with resolve pending  #https://github.com/angular/material/pull/7327

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
@keenondrums - thx for your patience here. Let's hope there are not inadvertent side affects from this merge.

**Comment by keenondrums** [comment]
@ThomasBurleson thank you for a great lib!
