### ISSUE TITLE
(Re)cache used icons like "md-tabs-arrow'" after $templateCache.removeAll()

### ISSUE THREAD

**Issue by dennislaupman** [angular/material#6531]
Hi guys,

For my app we need to delete the entire templateCache after creating or updating some GUI forms. The problem is the MdIconProvider with function "preloadIcons" cached some icons in the templatecache.

After $templateCache.removeAll() the cached icons are gone ;)

Is there an option to rerun this "preloadIcons" function on runtime (in a controler)? 

Would be nice!

Grtz Dennis

**Comment by ThomasBurleson** [comment]
Refactor into reusable function with API access. 

> Community contribution encouraged.

**Comment by programmist** [comment]
Quick update: Now that data URLs are possible with md-icon, that feature can be leveraged for our internal icons, rather $templateCache.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
