### ISSUE TITLE
md-autocomplete cannot clear from js

### ISSUE THREAD

**Issue by mihaellenic** [angular/material#6533]
I am just wondering if it is possible to clear md-autocomplete value from js? 
I found that clearing md-selected-item object does not clear the value of md-autocomplete itself.

Is there any other way to clear md-autocomplete selected value from js?

Here is codepen example: http://codepen.io/mihaellenic/pen/QydYxV

**Comment by antoinebrault** [comment]
use:

 $scope.clearSelectedItem = function() {
    $scope.searchText.name = '';
  }

**Comment by mihaellenic** [comment]
Thank you!
