### ISSUE TITLE
md-chips/autocomplete: pressing Esc to close autocomplete list removes focus from input

### ISSUE THREAD

**Issue by csvan** [angular/material#6534]
For example, consider the "vegetables" example on the Demo (last under Custom Inputs):

https://material.angularjs.org/latest/demo/chips

To reproduce here:

1. select the input element
2. start typing so that the autocomplete list appears
3. press Esc

**Expected**: the autocomplete list should close, and I should be able to keep typing or otherwise interact with the input element.

**Actual**: focus is removed from the element entirely - user has to manually select it again in order to interact with it.

I am not sure if this is actually by design. However, the expected behavior above is most likely what most users will be expecting as well.

**Comment by tjlav5** [comment]
@csvan would you rather have to press ESC twice to trigger the blur? Once for the autocomplete form, and a second time for the input field?

**Comment by clshortfuse** [comment]
Related https://github.com/angular/material/issues/5196

**Comment by csvan** [comment]
@tjlav5 I am sorry for the late reply. https://github.com/angular/material/issues/5196 perfectly sums up what I would expect from it.
