### ISSUE TITLE
The layout api doesn't follow the material design grid specifications

### ISSUE THREAD

**Issue by dilvane** [angular/material#6537]
As we can see on the spec:
https://www.google.com/design/spec/layout/responsive-ui.html#responsive-ui-grid

Material design’s responsive UI is based on a 12-column grid layout, with specific margins and gutters, but with the layout api, using flexbox, isn't possible recreate that.
Or the layout api is not for the same purpose?

**Comment by dilvane** [comment]
My first solution was reuse some mixins from the angular-material.scss to create a custom grid. https://gist.github.com/dilvane/a5418f3f3c5d68cf1059

Does anyone have a different approach?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by jaminroe** [comment]
Is this still being considered? I'd like to be able to have responsive padding/margins based on the viewport size/breakpoints. e.g. 960 - 1280px uses 24px gutters, >1280 - 1600px uses 32px gutters, etc.

**Comment by Splaktar** [comment]
This issue is closed. I'll respond in your newly opened issue.
