### ISSUE TITLE
Page's scope not available in Modal

### ISSUE THREAD

**Issue by VikramTiwari** [angular/material#6539]
How to access the variables that are present in the normal page scope, to be available in the modal too. 

Example : http://codepen.io/anon/pen/vLgoGP

**Comment by 0101adm** [comment]
you can bind variables to the modal using the 'locals' param or bind the scope using 'scope' and 'preserveScope' params of $mdDialog.

https://material.angularjs.org/latest/api/service/$mdDialog

**Comment by VikramTiwari** [comment]
Thanks @0101adm. Got it. :+1:
