### ISSUE TITLE
Inkbar not resizing when md-tabs width changes

### ISSUE THREAD

**Issue by steur36** [angular/material#6543]
The inkbar in `md-tabs` is scaled when te window gets resized but when `md-tabs` gets resized by something else the inkbar size doesn't scale along. This problem only occurs when `md-stretch-tabs` is set to `always`. See this example where showing and hiding a div changes the `md-tabs` width but doesn't scale the inkbar.

http://codepen.io/csteur/pen/rxyxPK

**Comment by HBO2** [comment]
+1 same issue.
