### ISSUE TITLE
Custom validation in md-autocomplete

### ISSUE THREAD

**Issue by calebegg** [angular/material#6544]
We have some custom validation directives that we'd like to be able to use on `md-autocomplete`, but can't, because it doesn't use `ng-model` (and the wrapped `<md-input-container>` has its own ng-model).

**Comment by ThomasBurleson** [comment]
Great feature for PR from community contributor.

**Comment by DevVersion** [comment]
@calebegg What item you want to access from the `ngModelController`? The selected item or just the search text?

**Comment by calebegg** [comment]
For our use case, we want the search text. Though, I know other people want the selected item so they can mark it as invalid if there's no selected item.

**Comment by enderdickerson** [comment]
For our use case we would like to access the selected item as @calebegg said just to ensure an item was selected from the list instead of validating against the presence of search text.

**Comment by DevVersion** [comment]
Okay, I just think about the search text too. We should provide both possibilities. But in first, what do you think about mirroring a ngModel, which can be accessed from the custom directives?

**Comment by enderdickerson** [comment]
Mirroring the ngModel for use with custom directives would be fine

**Comment by pranshunz** [comment]
I have created a [fork](https://github.com/pranshunz/material/blob/master/src/components/autocomplete/js/autocompleteDirective.js#L223) in which the custom validators can be provided by a md-validators attribute and are appended to the input field. Demo is can be check out [here](http://acd.azurewebsites.net/).

![image](https://cloud.githubusercontent.com/assets/9563377/13342006/5b70b39c-dca2-11e5-8544-89dcc83531d6.png)

Is this a prudent approach or am I on the completely wrong track?

**Comment by timruffles** [comment]
Ah great to see this is already being discussed, I'll close my issue.

@DevVersion what does mirroring the ngModel mean? Would it support the standard `<md-autocomplete name=someName ng-model=$ctrl.someProp` approach (see #7910)?
