### ISSUE TITLE
md-menu backdrop persists when browser's back button is pressed

### ISSUE THREAD

**Issue by cah-alexsukhodolsky** [angular/material#6545]
When open, the md-menu in the latest version of angular material (1.0.1) isn't removing the md-backdrop element after the "back" button is pressed.

Steps to reproduce:

1. Visit the Angular Material homepage https://material.angularjs.org/1.0.1 (currently https://material.angularjs.org/latest/)
2. Expand the Demos dropdown and click on "Menu" to visit the md-menu demo page
3. Click on the phone under the Simple dropdown menu demo: an md-menu should pop out with a list of options. Do NOT click out of the menu or select an item--just leave it open)
4. Press your browser's back button
5. Notice that the links on the page aren't clickable

If you're using Chrome and you right-click and "Inspect" the page, you'll notice the selected element is the md-backdrop. 
I suspect the md-backdrop can simply be removed in the md-menu element's destroy event.

**Comment by DevVersion** [comment]
I created a fix for that, see #6558

**Comment by cah-alexsukhodolsky** [comment]
Thanks for fixing it (and the quick turnaround)! I love the Angular Material library--I'm glad there's such a dedicated and talented team developing it.

**Comment by cah-alexsukhodolsky** [comment]
@ThomasBurleson can we append this bug fix to the next (minor) version release? Is there a reason this story was put in the backlog?
