### ISSUE TITLE
md-tabs horrendously poor performance when Chrome dev tools open

### ISSUE THREAD

**Issue by craigsh** [angular/material#6548]
I'm seeing horrendously bad performance when using md-tabs with the Chrome dev tools open. It seems fine when the dev tools aren't open. E.g. using this code pen: 
http://codepen.io/anon/pen/OyjBLz

running with the dev tools closed brings up the app in about 1 second - changing the HTML sees it re-render in the same time. But with the dev tools open it takes about 13 seconds. I'm seeing similar issues in my app with dev tools open.

While I don't expect my users to be running my app with the dev tools open it's a pain to develop with, and makes me nervous about performance as my app grows.

**Comment by craigsh** [comment]
Seems this is only happening for me on one machine (Windows 10 running the latest Chrome - 47.0.2526.106 m). I've restarted my machine but no change.

**Comment by warpdesign** [comment]
@craigsh I think this is related to #5681 (I noticed the same problem as well).

**Comment by craigsh** [comment]
@warpdesign Thanks - that's good news that it's not just me! It happening on pages that I'm using md-tabs on,

**Comment by baelter** [comment]
I'm seeing this as well

**Comment by jeff-mccoy** [comment]
Same for me Windows 10, Chome  49.0.2623.87---though if you run the JS profiler it seems to also go away, which is actually pretty ironic.  It takes several seconds when dev tools is running, instant otherwise (i7 machine w/32 GB ram).

**Comment by lukaw3d** [comment]
For me, this problem goes away if I uncheck "async" stack traces:
![async flag](http://i.stack.imgur.com/xMUM9.gif)

@jeff-mccoy I guess this flag is not used when JS profiler is running. I was able to use `console.profile()` and `console.profileEnd()` to find that `DebuggerScript._frameMirrorToJSCallFrame` was the main cause.

It also goes away if I remove DOMSubtreeModified listener (#5681).

**Comment by ThomasBurleson** [comment]
Closing as Duplicate.
