### ISSUE TITLE
md-tooltips still appear when link-type buttons are disabled

### ISSUE THREAD

**Issue by Anaphase** [angular/material#6551]
Tooltips are not hidden when link-type buttons are disabled. See this [CodePen](http://codepen.io/Anaphase/pen/adJJBY) for an illustration of this bug:

1. Hover over the buttons and note the tooltips.
2. Toggle the switch to disable the buttons.
3. Hover over the normal button and notice the tooltip doesn't appear.
4. Hover over the link button and notice the tooltip still appears.

**Comment by mzoabi** [comment]
you can disable the tooltip with ng-if
<md-tooltip ng-if="!App.buttonsDisabled">Link Button Tooltip</md-tooltip>

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
