### ISSUE TITLE
(dialog): Default behavior of reopen dialog. 

### ISSUE THREAD

**Issue by Jacksunwei** [angular/material#6552]
Currently if we reopen a dialog, the default behavior is $mdDialog.hide(), which resolves the previous promise. However, I think it makes more sense to call $mdDialog.cancel(), because the previous dialog is closed unexpectedly. 

A sample codepen is here: 
http://codepen.io/Jacksunwei/pen/VepWvW

**Comment by ThomasBurleson** [comment]
API will not be changed.
