### ISSUE TITLE
How to use angular-material in Angular2 Beta ?

### ISSUE THREAD

**Issue by osi-bhushankumar** [angular/material#6555]
Hi,

Is their any way to use angular-material with Angular2 (TypeScript ).

**Comment by zoechi** [comment]
Have you searched for existing issues before creating a new one?

**Comment by davidcui2** [comment]
+1. This [one](https://github.com/angular/material/issues/6458) closed only a few days ago.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
