### ISSUE TITLE
Multiple md-select , adding one resets pristine to true

### ISSUE THREAD

**Issue by Gbacc** [angular/material#6556]
Ok this is my first message here.

Using lastest version of angularjs/material , it seems i found out an issue using md-select.

See this jsfiddle : http://jsfiddle.net/ypjgdzxp/3/

What you can see here is that i'm adding rows on the fly wich contains an md-select. The problem is that adding a new md-select to the Dom resets the form pristine to true , even if it was false/dirty before.
In my exemple , juste put anything in the upper input "Nom de couche" wich will make the form dirty , then add a new row using the "+" button at the bottom.

**Comment by DevVersion** [comment]
Hello, just got into this.

At the first, after querying the `git logs` I found the commit. which introduced the issue. See 09bd5a3b52f29dfe530192099d2c405f204ec3ad

I created a PR which fixes that #6782

**Comment by cstephe** [comment]
http://jsfiddle.net/cstephe/ypjgdzxp/49/

This breaks inline forms that use a repeat filter,   basically if you dirty the form then enter a filter then clear it.  the form is set to pristine again.

**Comment by cstephe** [comment]
I'm a bit confused on this,  the commit which keeps being referenced as a fix is actually the cause of the issue,  it attempts to fix the issue by causing a side effect on the form.  It tries to mitigate the side effect by making a bad assumption that adding to a form with a value set at creation means the form should be clean.   Which maybe a 50%+ case for uses but I think there is a very large gap of use cases which this is very bad.
