### ISSUE TITLE
md-tabs: md-button ripple effect broken in Chrome

### ISSUE THREAD

**Issue by fridolin-koch** [angular/material#6559]
If the `md-tabs`component is present on the page, the ripple effect is broken in Chrome 47.0.2526.106 (Mac). Latest Firefox and Safari are fine.

Expected behaviour (FF):

![expected_ff](https://cloud.githubusercontent.com/assets/1880828/12143418/be7e1aaa-b480-11e5-995f-ddb2698b1a5d.gif)

Actual behaviour (Chrome):

![actual_chrome](https://cloud.githubusercontent.com/assets/1880828/12143435/cf603a92-b480-11e5-8b73-be2a1446a2d9.gif)

Chrome without the Tabs works as expected:

![actual_chrome_withouttabs](https://cloud.githubusercontent.com/assets/1880828/12143441/de035b24-b480-11e5-8fb5-4fdb8842adfb.gif)

Demo-Code:

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset='UTF-8'><meta name="robots" content="noindex">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel='stylesheet prefetch' href='http://rawgit.com/angular/bower-material/master/angular-material.css'>
  <link rel='stylesheet prefetch' href='http://fonts.googleapis.com/icon?family=Material+Icons'>
  <style>
  .site-sidenav {
    background-color: red;
    }
  </style>
</head>
<body layout="column" ng-app="myApp">
  <md-toolbar layout="row" layout-align="center center" class="md-whiteframe-glow-z1 stm-site-toolbar">
    <h2>
      <span>MyApp</span>
    </h2>
  </md-toolbar>
  <!-- Sidebar an main content -->
  <div layout="row" flex>
    <md-sidenav flex layout="column" md-is-locked-open="true" md-component-id="left" class="site-sidenav md-sidenav-left">
    </md-sidenav>
    <div layout="column" class="ui-view-container" flex style="overflow: auto">
      <md-content>
        <md-card>
          <md-card-content>
            <h1>Some space</h1>
            <h1>Some space</h1>
            <h1>Some space</h1>
            <md-tabs md-border-bottom>
              <md-tab label="Tab 1"></md-tab>
              <md-tab label="Tab 2"></md-tab>
              <md-tab label="Tab 3"></md-tab>
              <md-tab label="Tab 4"></md-tab>
            </md-tabs>
            <div flex>
              <md-button class="md-icon-button" aria-label="no ripple">
                <md-icon>star</md-icon>
              </md-button>
              <md-button>Test</md-button>
            </div>

          </md-card-content>
        </md-card>
      </md-content>
    </div>
  </div>
<script src='http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js'></script>
<script src='http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.min.js'></script>
<script src='http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-aria.min.js'></script>
<script src='http://rawgit.com/angular/bower-material/master/angular-material.js'></script>
<script>
angular.module('myApp', ['ngMaterial']);
</script>
</body>
</html>
```

The bug is present in 1.0.1 and master.

**Comment by DevVersion** [comment]
I baldy imported your code into a codepen demo. I run it on Chrome 47.0.2526.106 m (Windows) and it works perfectly. Are you running this on a Webserver or per file protocol?

![](https://i.gyazo.com/ed8b184180c1a466ea05d35389801d10.gif)

- http://codepen.io/DevVersion/pen/LGWdVb

**Comment by fridolin-koch** [comment]
Yes, it works within the Codepen iFrame. But it won't via HTTP or local file. 

If you open the corresponding Codepen iFrame in a new tab it won't work.

**Comment by DevVersion** [comment]
Yes, I can reproduce that ;)

**Comment by manish2535** [comment]
Unrelated comment - how do you guys create those nice videos or gifs?

**Comment by fridolin-koch** [comment]
https://github.com/lepht/licecap ;-)

**Comment by manish2535** [comment]
Thanks a lot. This is so Cool!

**Comment by DevVersion** [comment]
@fridolin-koch - Please run the `iframe` of this [codepen](http://codepen.io/DevVersion/pen/GoWdmb). 
And then you can remove the sidenav - and you see the ripple is working. I don't think it's related to the performance because the Timeline shows nothing :). 

But if we analyze the `ripple container`, we can see it's aligned correctly. 
Also the ripple service is called correctly. 

And I need to negate your hypothesis, because you can remove the `overflow` computed style of ripple container, and you will see the ripple effect is running smooth.

@manish2535 - I'm using `Gyazo` it's really easy to use for Screenshots and GIF's

**Comment by fridolin-koch** [comment]
Here is an example without the sidebar - same issue - http://preview.fkse.io/md/nosidebar.html
As you found out, it's obviously not a performance issue. Despite that, it's somehow related to the `md-tabs` component. Same code, but without tabs http://preview.fkse.io/md/sidebar-notabs.html -> working

I tested many combinations in my app, the bug only occurred if the `md-tabs` component was present.

**Comment by DevVersion** [comment]
That's really strange!, If I run my version and without the tabs directive, the ripple still won't work. But if I remove the sidenav directive it will work. 

We need to collect information. So in my case it only works if there is no `locked sidenav` present.

**Comment by rfuhrer** [comment]
I have the same issue as you guys, but for me it only happens if the button is using the "md-icon-button" class.  Regular buttons work just fine. I have a sidenav and tabs and it breaks, sidenav and no tabs and we're good. Again it only happens in chrome, even Edge works properly :)  I doubt that's much help but maybe there's some difference between a button and a md-icon-button that will lead you down a path that shows the real issue

**Comment by ThomasBurleson** [comment]
Attn: @robertmesserle

**Comment by craigsnyders** [comment]
I too have this issue with v1.0.1 where md-tabs breaks every ripple effect on every button on the page.

**Comment by d3lm** [comment]
Same issue for me, using angular-material 1.0.6 and Chrome 49.0.2623.87. The md-tabs directive breaks the ripple effect of buttons but somehow only in Chrome. In Firefox everything works fine. If I remove the tabs the ripple works again.

**Comment by dreamsfrag** [comment]
Me too, even of 1.1.0 rc2, mb-tabs breaks the ripple effect on the buttons. Only Chrome not working. Anyone resolve this issue ?

**Comment by craigsnyders** [comment]
I have found two strange things happening when md-tabs is present on the page:

1. If button height is >=65px then the ripple works fine
2. If you remove the **inline transform: translate3d(0px, 0px, 0px)** style from `<md-pagination-wrapper>` then all button ripples on the page work fine again

Is it possible that there is a CSS engine but using inline translate3d transformations on custom HTML elements?

**Comment by DevVersion** [comment]
@craigsnyders Indeed, this seems to be a Chrome Bug.

- https://bugs.chromium.org/p/chromium/issues/detail?id=157218
- http://jsfiddle.net/laukstein/bhmka/3/

**Comment by craigsnyders** [comment]
Deprecated, then closed?  The issue is still reproducible using Angular 1.5.3 and Material 1.1.0-rc2

see improved http://codepen.io/craigsnyders/pen/mEyaZa

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
