### ISSUE TITLE
md-contact-chips need to expose whole md-chips API

### ISSUE THREAD

**Issue by kvetis** [angular/material#6560]
md-contact-chips is a very pretty directive combining a pretty template for both md-chips and md-autocomplete. Unfortunately it does not expose the whole power of md-chips. The directive itself should provide most of the API the md-chips directive has. I'm talking about these attributes:
`readonly` `md-on-add` `md-on-remove` `md-on-select` `delete-button-label` `delete-hint`

Otherwise we need to $watch the collection and use different 'hacks' because we do not have access to the md-chips component ourselves.

Different solution is to copy-paste the template from `src/components/chips/js/contactChipsDirective.js` and customize it so it matches our needs.

**Comment by Anaphase** [comment]
I'd also love to be able to use a custom chip template with md-contact-chips the same way you can with normal md-chips. My issue is that when you add multiple new contacts, they all display the default "New Contact" name instead of the unique email, which is preferable.

**Comment by kvetis** [comment]
@Anaphase md-contact-chips is a more-or-less just two custom templates put together. One is the chips template and the other is the autocomplete template. You can use the md-contact-chips directive template in `src/components/chips/js/contactChipsDirective.js` and customize it your way.

**Comment by Anaphase** [comment]
Yeah, I know. It would just be nice to be able to use md-contact-chips and also specify a custom md-chip-template instead of using the hardcoded template.

**Comment by mohitadwani** [comment]
+1

**Comment by apat183** [comment]
I did a pull request to try and expose most of the above md-chips API. #6961

**Comment by topherfangio** [comment]
Related to #4537.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
