### ISSUE TITLE
md-autocomplete dropdown height shrinks sometimes thus showing small height list with scroll bar

### ISSUE THREAD

**Issue by alphazhe** [angular/material#6563]
Some times md-autocomplete dropdown list shrinks thus showing list with one item visible with scroll bar. Please fix this issue or tell me where I am doing wrong.

**Comment by ssj3sunny** [comment]
+1

**Comment by phamtuananh791994** [comment]
+1

**Comment by omarkammoun** [comment]
+1
Even here, if you chose and delete an item many time https://material.angularjs.org/latest/demo/autocomplete

**Comment by mexican-jack** [comment]
+1

**Comment by mexican-jack** [comment]
it appears that this has been fixed in head..

**Comment by Ram-Kale** [comment]
+1

**Comment by lukesodre** [comment]
+1

**Comment by jayeshanandani** [comment]
I think this is related to #5611
