### ISSUE TITLE
md-dialog + not going fullscreen

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6566]
chrome

am 1.0.1

http://codepen.io/0101adm/pen/wMJXGJ

**Comment by cranesandcaff** [comment]
Can confirm, the docs say adding the property results in the `md-dialog-fullscreen` class (or similar) being applied, I've tried using both the property and directly adding the class to my `md-dialog` element.

**Comment by BIGbuu** [comment]
```
@media (max-width: 959px)
md-dialog.md-dialog-fullscreen {
    min-height: 100%;
    min-width: 100%;
    border-radius: 0;
}
```
md-dialog.md-dialog-fullscreen work on screen < 960px.
Just resize you window or owerride this style.

**Comment by stunaz** [comment]
https://github.com/angular/material/issues/5924
