### ISSUE TITLE
md-autocomplete: ignores md-min-length="0"

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material#6568]
**ngMaterial version:** 1.0.4
**Browsers:** all
**Reproduce the Error:** [Codepen](http://codepen.io/anon/pen/QypBew?editors=101)
**Related Issues:** #5678 might be relevant
**Overview of the Issue:**
There is corner case when the `md-min-length="0"` and the initial value of `md-search-text` is set to empty string.
The expected behavior is that once focused there would be some suggestions displayed (because of the `md-min-length="0"`). However, that does not happen.
**Suggest a Fix:**
I tracked down the issue to [this line of code](https://github.com/angular/material/blob/release/1.0.1/src/components/autocomplete/js/autocompleteController.js#L343-L344). The if statement returns true. The following seems to fix issue, but that's just my suggestion. Not sure if ti's a proper fix.
```javascript
if (searchText === previousSearchText && getMinLength() !== 0) return;
```

**Update 2016/01/28**
Still happens in 1.0.3. Same fix still works.

**Update 2016/01/29**
Still happens in 1.0.4. Same fix still works.

**Comment by RolandHeath** [comment]
If you delete the line where you set `md-search-text` from your controller, this works as expected.
In your codepen, this is line 13.
`self.searchText    = '';`

In your codepen, I followed these steps, looking at `self.searchText` in the chrome developer tools.

1. Focus the autocomplete field.
2. Type something.
3. Backspace everything you typed.

`self.searchText` is set then set to undefined, not to the empty string. 

Do you have a reason you need to initialize it?

**Comment by DmitryEfimenko** [comment]
of course it'll work if I delete the line 13. It would be the same as setting it to undefined, which does not equal to empty string (which is the corner case I described).

I need suggestions to show up right away, when the input gets focus. Not after I type something. That's why I set `md-min-length="0"` and expect this behavior. And it does behave like this unless that corner case with the empty string is in place, which means it's a bug.

**Comment by RolandHeath** [comment]
That's fair, this is definitely not the expected behaviour.

**Comment by spoco2** [comment]
I too am having this issue, but it doesn't seem to be related to the same line as mentioned here.

From tracing it through the various checks it makes, this seems to be the problem for me:
```js
 /**
   * Determines if the menu should be shown.
   * @returns {boolean}
   */
  function shouldShow() {
    console.log("SHOULD SHOW? ", ((isMinLengthMet() && hasMatches()) || notFoundVisible()));
    return (isMinLengthMet() && hasMatches()) || notFoundVisible();
  }
```
(I added the console log)
Which says it'll only show if there are matches, which it can't even know yet because no matching has run at this point. If I just make it : 
```js
 function shouldShow() {
    return isMinLengthMet() || notFoundVisible();
  }
```

It seems to behave as desired... although I may be breaking something here

**Comment by DmitryEfimenko** [comment]
@ThomasBurleson 
I don't understand the logic of this project management.
Why are valid issues being closed? I'd understand setting label `Backlog` on it, but why close it? Will closed issues that have label `Backlog` be looked at in the future? What about Milestone `Deprecated`? 

---

Is there a document anywhere describing the meaning of labels, milestones?
Having such document for community to read would reduce amount of frustration.
Otherwise I feel that contributing to this project by opening issues is useless.

**Comment by bsandrow** [comment]
This is part of their "[Spring Cleaning](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk)" effort, which is newspeak for "we close everything and hope that most of it goes away so we don't have to fix it."

**Comment by DmitryEfimenko** [comment]
@bsandrow thanks for pointing to this.

**Comment by bsandrow** [comment]
@ThomasBurleson posts a link to the Spring Cleaning effort on some of the closed issues, but not others. It's a bit inconsistent unless he just happened to close your issue for an unrelated reason at the same time that he was closing other issues by the dozen.

**Comment by spoco2** [comment]
I gave up with this component some time ago, and just rolled my own. Too many bugs in it, spent too long trying to make it work how I wanted.
