### ISSUE TITLE
$mdMedia giving wrong boolean values

### ISSUE THREAD

**Issue by aeslinger0** [angular/material#6577]
It seems like a race condition to me. Here's the plunker: https://plnkr.co/edit/T0RfECzDyGkaWTpxsN9T?p=preview

Just resize the window a few times and you'll see that sometimes you have 'true' for multiple sizes and sometimes you'll get 'false' for everything.

**Comment by ThomasBurleson** [comment]
duplicate

**Comment by eshansingh** [comment]
Dulpicate of _what_?
