### ISSUE TITLE
md-input-container keep focused/open after touch outside

### ISSUE THREAD

**Issue by mario-aleo** [angular/material#6578]
An md-input-container stay focused ('clicked') when touch outside it.

Somewhere, in the older releases the touch outside was closing the interaction with the md-input-container, but now, if you touch on an md-input-container and than touch outside it, it still focused/click and on devices the touch outside event open the keyboard.

You can see it here: http://codepen.io/bgoerdt/pen/wMgZzK
Just use the Chrome Dev Tools device emulation to test. 

Is there any work around?

Thanks.

**Comment by mario-aleo** [comment]
I've found an work around, that is to comment the line 2114:
"document.addEventListener('mousedown', mouseInputHijacker, true);"

**Comment by 0101adm** [comment]
related / dup of #5365

**Comment by EladBezalel** [comment]
dup of #5365
