### ISSUE TITLE
Holding down backspace to clear autocomplete causes page to go back (JAWS/Firefox)

### ISSUE THREAD

**Issue by calebegg** [angular/material#6582]
1. Enable JAWS
2. Load [the autocomplete demo page](https://material.angularjs.org/HEAD/demo/autocomplete)
3. Check the "simulate query"
4. Copy a long string from somewhere (a few words)
5. Paste it into the autocomplete box (this is needed to prevent the next step from hitting the cache)
6. Hold down backspace to clear the field

Usually (not 100% of the time), you'll get taken back to the previous page during this. I assume that something is causing the field to temporarily lose focus, so the backspace keypress goes to the page, which causes the browser to go 'back'.

Note that this only seems to happen with JAWS enabled.

**Comment by ThomasBurleson** [comment]
Prevent default upon backspace if empty
