### ISSUE TITLE
Everything in bold?

### ISSUE THREAD

**Issue by AntonKL** [angular/material#6583]
Since ```0.11.0``` almost everything seems to be very bold-ish. Even text in a p-tag seems to be in bold. Is this something in the specs I'm not aware about? In my eyes it looks like everything is put emphasis on. 

## 0.10.1
![0 10 1](https://cloud.githubusercontent.com/assets/1410781/12181997/d1cb9b22-b585-11e5-9208-804e5cfdd109.jpg)

## 0.11.0
![0 11 0](https://cloud.githubusercontent.com/assets/1410781/12181988/c2ae5dd2-b585-11e5-8b3b-d268f6e5927e.jpg)

**Comment by DevVersion** [comment]
What browser are you using?

**Comment by AntonKL** [comment]
Version 47.0.2526.106 (64-bit) @ OSX 10.11.2 (El Capitan).

Same problem applies to Safari.

**Comment by ThomasBurleson** [comment]
Not an issue.

**Comment by AntonKL** [comment]
Thomas, will you please clarify? Is it a change in the Roboto font or are you referring to this as irellevent due to the fact the the issue should be local?
