### ISSUE TITLE
No CDN for 1.0.1 ?

### ISSUE THREAD

**Issue by cadilhac** [angular/material#6584]
I don't know the policy for publishing to the CDN, so is there a plan to put each new version on the CDN? I am missing the 1.0.1 release and I hope to find 1.0.2 there with a fix I need too.
Thanks

**Comment by DevVersion** [comment]
Hello,

I'm not sure about this `CDN` but you should be able to use this one too, its also used by all codepen demos from the docs.

`http://cdn.rawgit.com/angular/bower-material/v1.0.1/angular-material.css`
`http://cdn.rawgit.com/angular/bower-material/v1.0.1/angular-material.js`

**Comment by cadilhac** [comment]
Great, thank you.

**Comment by jmmehta63** [comment]
Not working in IONIC... :(
