### ISSUE TITLE
md-scroll-mask might not take effect in time with md-autocomplete

### ISSUE THREAD

**Issue by hitigon** [angular/material#6585]
There would be a small window when search in md-autocomplete and make a page scrolling that causes md-autocomplete suggestion box's position changed with scrolling. There is a screenshot:

<img width="927" alt="screen shot 2016-01-07 at 1 30 28 pm" src="https://cloud.githubusercontent.com/assets/493756/12183343/27b587f2-b543-11e5-89e6-ec34b8edaf58.png">

**Comment by DevVersion** [comment]
It is fixed in #6589
