### ISSUE TITLE
Invalid input does not disappear with ng-show

### ISSUE THREAD

**Issue by cadilhac** [angular/material#6587]
In a form, I have one checkbox to show or hide some other fields (with ng-show). If all fields are valid and the expression in the ngshow becomes false, then the fields are correctly hidden. However, if one of the fields becomes invalid, it does not become hidden. Note that if the field is invalid at first, it can be hidden (but make it valid and then invalid later and the problen happens).

http://codepen.io/anon/pen/MKmKmJ

**Comment by cadilhac** [comment]
and FYI (I know this is obvious), the problem does not occur if the ng-show directive is placed one level up in a parent DIV of the md-input-container, or if ng-show is replaced by ng-if.

**Comment by ThomasBurleson** [comment]
Workaround is to move the `ng-show` 1-level up.
