### ISSUE TITLE
Percentage flex in nested layout containers

### ISSUE THREAD

**Issue by wallw-bits** [angular/material#6588]
Using percentage flex items like flex="30" do not work properly when nested in layout containers. The [Codepen here](http://codepen.io/anon/pen/QyvyMy) shows the problem on the left and the expected heights of the blue and green divs on the right.

**Comment by epelc** [comment]
Possibly a duplicate of #5772

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
