### ISSUE TITLE
datepicker inconsistent with select when navigating with keyboard

### ISSUE THREAD

**Issue by pablogrisafi1975** [angular/material#6591]
If you navigate via tab and a select gets focus you can open the dropdown using the down arrow in the keyboard. Once you open it, you can navigate with keys and select with space or enter, you close with scape, esc or tab. There is no way to focus in the down arrow in the right.

If you access a datepicker you can (and need to) focus in the down  arrow to open the dropdown. You can navigate with left/right/up/down keys, but space does not select, and  moves a month forward.

I think datepicker should act more similar to select, for consistence and accessibility. At least, the 'down arrow to show options' should be respected. 

Just write a page with the 2 controls and try to navigate using keyboard, it is very clear.

**Comment by ThomasBurleson** [comment]
The current functionality is conformant with DatePicker specs.
