### ISSUE TITLE
select multiple options no background when focused and selected

### ISSUE THREAD

**Issue by pablogrisafi1975** [angular/material#6592]
if you use a select  multiple and try to navigate using the keyboard, you'll see that the options have a nice light grey background when not selected, and turn blue with no background when selected using keyboard. Selected options are always blue on white, making it impossible to know the option you are focused right now.

A simple hack to solve it

    md-select-menu md-option:focus {
    	background:rgb(238,238,238);
    }

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
