### ISSUE TITLE
Speed Dial start with an open list

### ISSUE THREAD

**Issue by reinos** [angular/material#6595]
I setup a simple Speed Dials code pen here http://codepen.io/anon/pen/JGNWYr where you see that the list start open instead of closed...

Any idea how i can start with a closed list.

**Comment by nestorneto** [comment]
same here.

**Comment by lalo4ka** [comment]
same here

**Comment by lalo4ka** [comment]
try this (the magic is in the attribute ng-cloak): 

<div style="position: fixed; bottom:20px;right: 20px" ng-cloak>
  <md-fab-speed-dial md-open="false" md-direction="up"
                     class="md-fling">
    <md-fab-trigger>
      <md-button aria-label="send" class="md-fab md-warn">
        <md-icon>send</md-icon>
      </md-button>
    </md-fab-trigger>
    <md-fab-actions>
      <md-button aria-label="Twitter" class="md-fab md-raised md-mini">
        <md-icon>android</md-icon>
      </md-button>
      <md-button aria-label="build" class="md-fab md-raised md-mini">
        <md-icon>build</md-icon>
      </md-button>
      <md-button aria-label="Google Hangout" class="md-fab md-raised md-mini">
        <md-icon aria-label="work">work</md-icon>
      </md-button>
    </md-fab-actions>
  </md-fab-speed-dial>
</div>

**Comment by ThomasBurleson** [comment]
Cc: @topherfangio - Resolve by wrapping FabSpeedDial in a ng-cloak container.
