### ISSUE TITLE
[Documentation] $mdMenu should be listed as a service

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#6596]
https://material.angularjs.org/latest/api/directive/mdMenu
"You can then close the menu programatically by injecting $mdMenu and calling $mdMenu.hide()."
As it, it's a service and should be listed as one in the side menu :)
Thanks !

**Comment by ThomasBurleson** [comment]
This will remain part of the mdMenu documentation.

**Comment by jacob-robertson** [comment]
I realize that this is an ancient issue, and everyone is focusing on Angular Material 2 now.  Having said that, this seems like a silly decision. The existing documentation for $mdMenu is pretty non-existent. There is almost no mention of it or what it does. This is a hole in the documentation that should have been filled, in my opinion. We shouldn't need to reason out how a the apis of a service work by experimenting in code.
