### ISSUE TITLE
md-grid-tile with ng-show still occupy the space

### ISSUE THREAD

**Issue by davidcui2** [angular/material#6597]
Tried to search two keywords `md-grid-tile` and `ng-show` together and get no existing issue.

I don't know whether the blank space left is intended or not.

Super simple [pen](http://codepen.io/zhc/pen/qbmXoK) available.

**Comment by RichOren** [comment]
I would try ng-if instead of ng-show/ng-hide if you do not want it to occupy the space.

**Comment by davidcui2** [comment]
Yeah, I know that should do the job. Just wondering whether that's a bug or not.
