### ISSUE TITLE
Styling md-autocomplete

### ISSUE THREAD

**Issue by manish2535** [angular/material#6599]
My App uses multiple md-autocomplete. One md-virtual-repeat-container is created for each md-autocomplete and inserted at the end of the body.

I want to style the position of each md-virtual-repeat-container differently but since there is no way for me to pass a special class or id to this element using the directive, I am not able to do this.

I can use the ordering to my advantage and use the CSS:nth-child to get the end result but that seems very hacky. Is there any way I can pass a Class to the main md-virtual-repeat-container element that gets generated?

Note: The md-menu-class parameter is useless in this case because it only adds the class in the inner ul element not on the parent element,

**Comment by kseamon** [comment]
If you use a custom template for your menu items, you could add an ng-class or ng-style to it, right?

**Comment by manish2535** [comment]
Yes but the md-autocomplete gets dynamically generated and appended to the body so that class or style will not make it through.

**Comment by aaronPMorabito** [comment]
I am running into this issue as well. I wanted to shrink the size of the <code>md-autocomplete</code> input with floating label to size it similarly to other <code>md-input-container</code> elements in the same row. 

Messing with margins/padding will cause the menu/progress bar to be misaligned. The <code>md-progress-linear</code> is easy enough to re-position, but having access to the menu <code>md-virtual-repeat-container</code> parent element or passing it a class/id would be useful.

**Comment by manish2535** [comment]
any updates on this one?

**Comment by cornerbodega** [comment]
+1

**Comment by jensbodal** [comment]
Using information from [this pull request](https://github.com/angular/material/pull/8397/files) I made a decorator to add to my app's config;  the decorator allows an `md-menu-container-class` attribute to be added to the `md-autocomplete` directive which can then be used for styling.  [Plunker](https://plnkr.co/edit/0tzee8RpoD2WeFSJX1z1?p=preview)

**Comment by ibnYusrat** [comment]
+1

**Comment by cweise93** [comment]
Awesome jensbodal.  Thank you.  Works perfect.
