### ISSUE TITLE
update codepen examples to include MIT License

### ISSUE THREAD

**Issue by naomiblack** [angular/material#6601]
All of our codepen examples must include the following statement at the end of each file:

```
Copyright 2016 Google Inc. All Rights Reserved.

Use of this source code is governed by an MIT-style license that can be found in the LICENSE file at https://github.com/angular/material/blob/master/LICENSE
```
It might be nice to just create a site-level alias for http://material.angularjs.org/license that points to the github page for simplicity

(related: https://github.com/angular/material/issues/6600)

**Comment by ThomasBurleson** [comment]
This will be appended to the source in the HTML source pane:

```html
<!--  
Copyright 2016 Google Inc. All Rights Reserved.  

Use of this source code is governed by an MIT-style license that can be in the LICENSE file at http://material.angularjs.org/license
 -->
```

> Not visible in the CodePen 'results' pane.

**Comment by naomiblack** [comment]
should also appear in any js and css files that we provide

**Comment by ThomasBurleson** [comment]
I see. I will amend and fix that also.

**Comment by naomiblack** [comment]
Is there a propagation delay? When I click the Live Demo link for autocomplete, I don't see our boilerplate in the codepen source files that are live

**Comment by ThomasBurleson** [comment]
Add to CodePen Community samples.

**Comment by ThomasBurleson** [comment]
Fixed.
