### ISSUE TITLE
Inline <style> elements violates style-src Content Security Policy

### ISSUE THREAD

**Issue by jelbourn** [angular/material#6602]
See https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#style-src

In order to address this, there would need to be build-time tooling to let people generate their own theme css outputs.

**Comment by epelc** [comment]
Would be nice if there was also a gulp plugin for this

**Comment by jelbourn** [comment]
@Emeegeemee fixed the `<style>` element issue in #6691, but there are still inline style attributes that are potentially a problem in: [slider](https://github.com/angular/material/blob/91291ed425def4fde3e3343b531f5117d33b9756/src/components/slider/slider.js#L200), [tabs](https://github.com/angular/material/blob/91291ed425def4fde3e3343b531f5117d33b9756/src/components/tabs/js/tabsDirective.js#L137), and two in util.js [here](https://github.com/angular/material/blob/91291ed425def4fde3e3343b531f5117d33b9756/src/core/util/util.js#L248) and [here](https://github.com/angular/material/blob/91291ed425def4fde3e3343b531f5117d33b9756/src/core/util/util.js#L324)

**Comment by Emeegeemee** [comment]
I found a few more violations with using *.setAttribute('style', *) in [MenuBarController](https://github.com/angular/material/blob/0e334cd3569841c8fd9abb73f812dd968b4ccccf/src/components/menuBar/js/menuBarController.js#L111) and [util.js](https://github.com/angular/material/blob/0e334cd3569841c8fd9abb73f812dd968b4ccccf/src/core/util/util.js#L305-L306).

**Comment by Emeegeemee** [comment]
I believe I've fixed all the unsafe-inline violations in this [commit](https://github.com/Emeegeemee/material/commit/42bd84f7782a932d70350dfcf6f160adfc03e0cc), but will do another check and update any tests before sending a pull request next week.

In case anyone wants to test out the doc site with CSP enabled, I created this [commit](https://github.com/Emeegeemee/material/commit/849e0db9bee2a175c1a911967d8ba2089f4478c2) for reference.

**Comment by jelbourn** [comment]
This should now be resolved by the two commits from @Emeegeemee
