### ISSUE TITLE
Unit testing with angular-material

### ISSUE THREAD

**Issue by mattfysh** [angular/material#6604]
Attempting to unit test a directive which uses `$mdDialog.show()`, and decided to keep the real dialog implementation in place as the API is too large to stub. Have run into a couple of problems, here's what I have so far:

```javascript
el.find('.this-shows-dialog').click(); // click on the button that opens the dialog
$rootElement.find('md-select[ng-model="myScope.property"]').click(); // open a md-select in the dialog
$rootScope.$apply();
$timeout.flush();
$('body').find('md-option[value=optionValue]').click(); // select a value from the list of options
$rootScope.$apply();
$timeout.flush();
// repeat above pattern for every dropdown in the dialog
$rootElement.find('.md-actions .md-primary').click();
expect(...)...
```
A couple of issues with this:
1. The rootScope/timeout pattern needs to be repeated after each interaction with the dialog's controls
2. md-option's are not added to $rootElement, but rather the document.body which makes accessing them difficult

Are there any options to simplify this approach to testing with angular material, and how can I make sure all elements added to the DOM during the unit test are held inside of a specific container (i.e. not `document.body`)

**Comment by ThomasBurleson** [comment]
This is a known issue and area that needs enhancement.

**Comment by mattfysh** [comment]
great, thanks @ThomasBurleson. Any thoughts on how to approach this enhancement?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by mattfysh** [comment]
😢
