### ISSUE TITLE
Virtual repeater slow on iphone

### ISSUE THREAD

**Issue by gpopovic** [angular/material#6606]
When i'm scrolling through the virtual repeater demo on  iphone (chrome browse), faster than normal, it takes a lot (like a second) before items appear.

On the desktop this doesn't occur. This deteriorates user experience on iphone.

update:

Safari && firefox mobile don't have these problems.

update2:

it appears on chrome(iphone), dom gets updated when scrolling stops.

**Comment by kseamon** [comment]
Does the same thing happen in MobileSafari, out of curiosity? What I've seen there is that the browser does not redraw the scroll buffer synchronously while scrolling, so there's not much we can do about that aside from perhaps rendering more "extra" rows than we do now (3). Obviously doing that harms performance generally.

**Comment by gpopovic** [comment]
It doesn't happen on safari.

This link seems to describe this behavior.
.
http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/

**Comment by kseamon** [comment]
There's a new version of iOS chrome out that switches to a newer webkit engine. Can you give that a try? There's not really a whole lot I can do about this, and I'm not looking to support iOS 7 at this point.

**Comment by gpopovic** [comment]
It works like a charm now..
