### ISSUE TITLE
mdToast (docs): examples don't align with Material Spec

### ISSUE THREAD

**Issue by Splaktar** [angular/material#6607]
Currently the [docs](https://material.angularjs.org/latest/demo/toast) show an 'OK' button and a 'Close' button in the two snackbar (toast) examples (Show With Action, Show Custom).

Based on the [spec](https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-usage) having this kind of a 'Dismiss', 'OK', 'Close' button in a snackbar is a "Don't".

The docs should not show examples of things that go against the spec as it creates [confusion](http://stackoverflow.com/questions/28481029/how-can-i-change-the-color-of-toast-depends-on-message-type-in-angular-material/32241428?noredirect=1#comment56994080_32241428) with users.

**Comment by DevVersion** [comment]
That's right, so perhaps we should only add a button for `UNDO`, which represents the possibility of placing a button in there. Thoughts?

**Comment by Splaktar** [comment]
Yes, I think an UNDO or RETRY button in the examples would better align with the spec.

**Comment by DevVersion** [comment]
Yes, sounds good ;) then we should simply add a highlight color. 
And how can we get that green color? is it also in the palette?

**Comment by Splaktar** [comment]
Using `.highlightAction(true)` on the simple toast builder gives the button `md-primary`. Should this be accent instead?

For the custom action, there is a style that is overriding putting `md-accent` on the button in the template and making the button white. I had to add a custom style to use the accent color over this white style.

http://codepen.io/Splaktar/pen/jWmQad

**Comment by DevVersion** [comment]
The Accent Color looks much more handsome as the primary highlight. But I think the Specs use the Accent Color too?

**Comment by Splaktar** [comment]
It does look like the spec prefers the accent color for the snackbar action highlight. It seems like using `md-warn`, and `md-primary` on the button should be allowed as well, but not the default.

**Comment by topherfangio** [comment]
@DevVersion Sorry for the confusion in our discussion; yes, as far as I can tell, it should use the accent color, not the primary color.
