### ISSUE TITLE
Clarification: Dynamic capabilities of CSS

### ISSUE THREAD

**Issue by oravecz** [angular/material#6609]
The Material Design introduces the device-independent measurement of dps. The SCSS file seems poised to take advantage of this calculation, however the distributed CSS file is, of course, static. Is there any provision within Angular Material to adjust layout and components based on the devices screen density, or is it fixed to a 160dpi screen?

**Comment by ThomasBurleson** [comment]
Angular Material 1.x uses pixels. Use of `dp` will not be supported in 1.x
