### ISSUE TITLE
md-bottom-sheet + screen position

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6613]
chrome

am 1.0.1

bottom-sheet opens in wrong position if opened anywhere beyond the top of the page.

http://codepen.io/0101adm/pen/MKoaeZ

scroll to the last button.  make sure the page has scrolled.  click.  bottom-sheet should open further up the page.

**Comment by DevVersion** [comment]
This can be fixed in #6484. Will add that, when PR got reviewed. 

I tested that today and it work's good. It allows the user to open the `<md-bottom-sheet>` at any scroll position in the viewport

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by Jenhaohsiao** [comment]
in your css file, add this :
md-bottom-sheet {
    position: fixed;
    bottom: 0;
}
