### ISSUE TITLE
CSS Error on v1.0.0 and v1.0.1 while app deployment in production mode.

### ISSUE THREAD

**Issue by tenshiAMD** [angular/material#6614]
This error appeared while deploying the app in production mode, this persist in v1.0.0 and v1.0.1. Could you check this guys? In v1.0.0rc7, the deployment is successful. It keeps on failing in v1.0.0 and v1.0.1.

<b>Sass::SyntaxError: Invalid CSS after "...a screen\0 and ": expected "{", was "(max-width: 599..." (sass):2235</b>

**Comment by odedniv** [comment]
+1

**Comment by macchie** [comment]
+2

**Comment by kouak** [comment]
Duplicate of #6304 ?

**Comment by jelbourn** [comment]
Yes, this is a dupe.
