### ISSUE TITLE
Slider not working on IOS when page is zoomed in

### ISSUE THREAD

**Issue by nsdcss** [angular/material#6615]
I encountered a problem with the sllider-component on an Ipad (IOS 9):

When the page is zoomed in the sliders are not working anymore. The used pointer.x property delivers a wrong value in this case.

When I do: x = x - document.body.scrollLeft - document.documentElement.scrollLeft; (in adjustThumbPosition(x) and positionToPercent(x) in slider.js)
It seems to work properly, which is basically using "clientX" instead of "pageX" as pointer.x.

**Comment by ThomasBurleson** [comment]
Contact @jelbourn for details!
