### ISSUE TITLE
anchor in a md-toolbar, click on the anchor, it move the toolbar

### ISSUE THREAD

**Issue by JA44** [angular/material#6616]
I create a toolbar with some links which pointing anchors in the md-content.
When I click on the anchor, it should show the targeted anchor without move the toolbar.

codepen: http://codepen.io/anon/pen/mVwVZY

To reproduce: 

1. Click on the link "Content1"

The result: The browser shows the anchor but the toolbar moves. It shows the md-toolbar partially

I expect the browser shows the anchor without move the toolbar

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
