### ISSUE TITLE
md-dialog messed up in IE11 after updating to version 1.0.1

### ISSUE THREAD

**Issue by zeeshanhyder** [angular/material#6617]
The md-dialog is completey messed up in ie11 after updating to version 1.0.1. The md-dialog-content is not visible, unless you explicitly mention the height of md-dialog or set the md-dialog as "layout-fill"

Below is the demo:
http://codepen.io/zeeshanhyder/pen/WrOzRJ

**Comment by Wardormeur** [comment]
flex without value is badly supported by IE, and flex="100" isn't by Android default browser/iOS
Change flex to flex="auto" in your md-dialog-content and it'll work fine :)

**Comment by zeeshanhyder** [comment]
Works now. Thanks. Closing the issue.

**Comment by sstorie** [comment]
Is there a "proper" fix for this in the works?

I'm running 1.0.2, and have run into this issue where in IE11 the dialog takes the proper height, but the width is only wide enough to display the buttons I have in my *md-dialog-actions* div. I can use the layout-fill trick to get things usable in IE11, but then the dialog takes 100% of the vertical height across all browsers, which obviously isn't desirable.

I've tried the *flex="auto"* trick, but it doesn't work with my specific dialog. I've also tried specifying a min-width value and that kinda helps, but layout within the window is all screwed up.

Anyway, thanks for posting this technique as it's helping me learn, but I'd love to know if someone is working on getting this to all "just work" in IE11.

**Comment by zeeshanhyder** [comment]
There is no proper fix as the bug is in Internet Explorer itself. So i think we may have rely on workarounds for now, unless there are some changes to code itself. There is a reason why devs hate internet explorer (including me). But the issue is fixed in Edge now (it still sucks!).
