### ISSUE TITLE
[mdDialog] Fullscreen behavior is strange

### ISSUE THREAD

**Issue by Wardormeur** [angular/material#6618]
Hi
http://codepen.io/anon/pen/rxwyNx
tldr; watch hover sizeis only done when fullscreen is true on initial opening

When opening the "CUSTOM DIALOG" in small screen, it evaluate as expected to fullscreen.
Same goes when opening on larger screen, it goes as "windowed".
However, when resizing from "windowed" to smaller, it doesn't trigger the fullscreen on xs/sm; whereas opening it on small resolution to then extend it and it adapts as expected.
Thanks :)

**Comment by charlietfl** [comment]
@Wardormeur The value for your variable `useFullScreen` and therefore `fullscreen` object property is only going to be evaluated at the moment `showAdvanced()` gets called. Seems like you are expecting a watch on a primitive variable that has no watch.

**Comment by Wardormeur** [comment]
Well, it's being watched somehow since there is a switch from small-fullscreen to large-windowed,  or am I missing an info on how it has been implemented?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
