### ISSUE TITLE
md-checkbox tick doesn't show inside table

### ISSUE THREAD

**Issue by Elfayer** [angular/material#6619]
When an `<md-checkbox>` is put inside a table with the `border-collapse: collapse;` CSS, the tick doesn't show (**Only on IE or Edge**) : https://jsfiddle.net/a8zco7nt/

![image](https://cloud.githubusercontent.com/assets/15869149/12239607/ec166582-b889-11e5-9b19-d15236298387.png)

This is so weird I have no idea how to fix this. Any thought ?

**Comment by SalmanZafar214** [comment]
same issue here . any solution to get it fixed
