### ISSUE TITLE
disableBodyScroll causing body jump

### ISSUE THREAD

**Issue by clabough** [angular/material#6621]
I've found that the disableBodyScroll function is causing my body to jump to the left.  This only happens when the body width is not 100% and the scrollHeight is > clientHeight.

See this CodePen as an example. It's taken from your documentation sample.

http://codepen.io/anon/pen/EPXXXY

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
