### ISSUE TITLE
md-sidenav usability issue (CSS documentation).

### ISSUE THREAD

**Issue by vivekimsit** [angular/material#6625]
I am implementing the side navigation and I want that the top of the side navigation should contain the image of the logged in user. Currently I see that I can use `md-icon` but I have to manually tweak the CSS to get the desired effect. I see that there are other directives too. The docs at present seems sparse right now so, it will be great when someone points me to or at least give an small example on the usability of the following directive / classes:

* md-icon
* md-avatar
* md-avatar-icon

PS: I believe that angular community is doing great work on material design.

**Comment by ThomasBurleson** [comment]
Need to clarify when an icon or an image tag is the preferred usage.
