### ISSUE TITLE
chips remove button should carry md-prevent-menu-close attribute

### ISSUE THREAD

**Issue by marshfire** [angular/material#6628]
I'm trying to implement a filter inside a menu where chips are used to indicate the different filter values selected. This works quite good until you try to remove one of them. In this case the menu closes, which is quite inconvenient for the user. 

I can not think of a situation where I want a menu closed when I remove a chip. So best is to always add this attribute.

The code that would need to be modified would be:

    var CHIP_REMOVE_TEMPLATE = '\
      <button\
          class="md-chip-remove"\
          ng-if="!$mdChipsCtrl.readonly"\
          ng-click="$mdChipsCtrl.removeChipAndFocusInput($$replacedScope.$index)"\
          type="button"\
          aria-hidden="true"\
          md-prevent-menu-close="md-prevent-menu-close"\
          tabindex="-1">\
        <md-icon md-svg-icon="md-close"></md-icon>\
        <span class="md-visually-hidden">\
          {{$mdChipsCtrl.deleteButtonLabel}}\
        </span>\
      </button>';

**Comment by marshfire** [comment]
Huh? Closed without a comment? Is it a won't fix or a no-brainer?

**Comment by zhenya2224** [comment]
I'm having the same issue. When clicking on remove icon on one of the chips it closes the menu. Is there a way to prevent it from closing?
