### ISSUE TITLE
md-select support for separate searchbox and filtering the option list

### ISSUE THREAD

**Issue by Robin-Hoodie** [angular/material#6629]
Filtering the option list based on what the user types in a separate searchbox would be much needed for us. We're currently using our own custom-made directive for selects which supports this but wanted to switch to angular-material. However for selects this is an option we would really need before considering replacing them.

This is more or less what I mean: http://ui.lumapps.com/directives/selects.

Autocomplete does this and is a valid alternative for most cases. But with autocomplete selecting multiple items does not seem to be possible. We would need both in one component.

**Comment by Pega88** [comment]
+1!

**Comment by Krie999** [comment]
+1!

**Comment by ThomasBurleson** [comment]
References #6643

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
