### ISSUE TITLE
slider  discrete - option not to display value

### ISSUE THREAD

**Issue by 6gsaifulislam** [angular/material#663]
Using md-slider I have to use the discrete setting to prevent multiply calls to ng-change - but I do not need to display the value (in fact it would confuse the user) - is there any option not to display the value?

![slide](https://cloud.githubusercontent.com/assets/7714810/5062290/d296072a-6db2-11e4-934a-563302a2f5ce.png)

**Comment by SahinU88** [comment]
I know this issue is closed, but maybe it would be nice to have an option to place it "top" or "bottom".
hope this comment is not misplaced ( even though this thread is marked as closed ).

cheers
