### ISSUE TITLE
layout="column" and flex="50" don't work in IE

### ISSUE THREAD

**Issue by super-coder** [angular/material#6630]
Edit: IE11
I was following https://material.angularjs.org/latest/layout/introduction and seems like **layout="row"** and **flex="50"** is not working 
http://codepen.io/anon/pen/mVwKLJ

![image](https://cloud.githubusercontent.com/assets/2155554/12261624/4e6046f0-b933-11e5-96f9-1e3bf56aed52.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
