### ISSUE TITLE
Add ng-disabled to md-list

### ISSUE THREAD

**Issue by Grendizr** [angular/material#6632]
Hi !

Please correct me if I am wrong, but I am bit surprised to see the md-list not supporting / propagating the ng-disabled value to childrens

                    <div layout="row" flex>
                     <md-list layout-align="center start"
                             ng-disabled="!submissionDate">
                        <md-subheader class="md-no-sticky">Providers</md-subheader>
                        <md-list-item ng-repeat="provider in data.providers"
                                      layout="row"
                                      layout-margin
                                      title="{{(!submissionDate) ? 'Please select a reporting date' : '' }}"
                                      >
                            <div class="md-list-item-text">
                                {{provider.name}}
                            </div>

                            <md-radio-group ng-model="provider.type"
                                            class="md-primary"
                                            layout="row"
                                            layout-margin>
                                <md-radio-button ng-repeat="d in data.dataTypes"
                                                 ng-value="d.id"
                                                 >
                                    {{ d.name }}
                                </md-radio-button>
                            </md-radio-group>
                    ...

I have other controls .. like buttons within each list item, and the only way I have to disable controls within the md-list-items is to disable each of them .. thus by duplicating the disabled validation .. where I should apply it only to the main container aka md-list

Note even by setting ng-disabled="true" on eitehr md-list or md-list-item this is doing .. nothing.

Thanks for your feedback.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by cmacdonnacha** [comment]
+1
