### ISSUE TITLE
Responsive Layout example doesn't work in IE11

### ISSUE THREAD

**Issue by super-coder** [angular/material#6635]
from https://material.angularjs.org/latest/layout/container 
**Responsive Layouts** section, just pasted in codepen 
http://codepen.io/anon/pen/eJRPbj

![image](https://cloud.githubusercontent.com/assets/2155554/12266933/c7161fca-b956-11e5-9aec-07aad226cfcf.png)

this is my 3rd bug today, layout suck big time, feels like going with Angular material was a major mistake

**Comment by Wardormeur** [comment]
flex="auto" :)

**Comment by super-coder** [comment]
still flex='50' doesn't work
http://codepen.io/anon/pen/eJRPbj

![image](https://cloud.githubusercontent.com/assets/2155554/12269467/95b2693c-b962-11e5-8d4f-0e08d51a7105.png)

**Comment by bonatoc** [comment]
Did you take a look at [https://github.com/philipwalton/flexbugs](https://github.com/philipwalton/flexbugs) ?

**Comment by super-coder** [comment]
Related: 
http://codepen.io/anon/pen/EPvyWz
removing **layout-fill** from standard example **[Menu Position Modes](https://material.angularjs.org/latest/demo/menu)** breaks example in IE11

![image](https://cloud.githubusercontent.com/assets/2155554/12288384/07028220-b9e5-11e5-9548-0b4a72c4c5ec.png)

**Comment by super-coder** [comment]
@bonatoc do you understand what "supported browser" means? it means - it works in that browser without workarounds

**Comment by mpfisterUniBE** [comment]
flex="auto" won't help in this case because as soon as flex is being applied to a column element it fails to properly render in IE11:
=> http://codepen.io/cyberlnk/pen/NxwqoG 

This bug (or maybe I'm just doing something wrong) has become a show stopper for our current project so hopefully there is a way to fix this issue.

Interestingly the Layout Directive demo on the following page works perfectly well in IE11
=> https://material.angularjs.org/latest/layout/container

**Comment by super-coder** [comment]
i managed to make it work by removing flex='column' and controlling with flex='33' and max-width

**Comment by super-coder** [comment]
http://codepen.io/anon/pen/adVvzK

**Comment by mpfisterUniBE** [comment]
nice catch, it's indeed happening as soon as layout="column" is being added.

For some reason IE11 seems to have an issue with a flex-basis of 0%, so I've added an auto flex-basis for columns:
```css
.layout-column > .flex {
	-ms-flex: 1 1 auto;
	-webkit-flex: 1 1 auto;
	flex: 1 1 auto;
}
```
This way I don't have to change the HTML code itself.
=> http://codepen.io/cyberlnk/pen/wMPKjJ

...need to further test it but you've put me into the right direction, thanks.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
