### ISSUE TITLE
layout="row" input alignment issues

### ISSUE THREAD

**Issue by Andrew1503** [angular/material#6636]
`md-input`, `md-select`, `md-checkbox`, `md-switch`, and `md-button` don't seem to want to align properly when they are siblings in a parent with `layout="row"`.

[codepen](http://codepen.io/Andrew1503/pen/QygZGG)

I tried different combinations of layout-align, and none seem to get everything lined up. The best result I've found is using `layout-align="start center"` and overriding the height of the resulting `<div class="md-error-spacer"></div>` to 0.

Is there something obvious I'm missing, or do I just have to keep fiddling with css overrides to get these elements to play nicely together?

**Comment by bonatoc** [comment]
Yes, can someone from the team explain the rationale behind the different **margin-top** and **margin-bottom** inconsistencies for form elements ?

**Comment by scriptsure** [comment]
+1 when adding the md-datepicker to the mix things get even worse... this is kind of a serious issue. Not to be pushy but so you have an estimate for 1.1.0 release?

**Comment by bonatoc** [comment]
@scriptsure — It doesn't mean you have to wait. 
Open Source projects leaders such as Thomas may be heroes, but they're not Superman :-)

15 mn of CSS temporary overwrites will get you up and running.
Just saying.

**Comment by scriptsure** [comment]
ok np but do we have direction at this point as to the reasons. I see in this particular example that the md-inline-form is missing... so that will clean up a lot i expect... I guess on this one its just tough sometimes... have to be super careful with order and directives that are used. Something that you think will work might not... I hear what your saying though there are work arounds.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
