### ISSUE TITLE
$mdDialog: option 'onRemoving' is fired upon dialog opening, not closing.

### ISSUE THREAD

**Issue by bonatoc** [angular/material#6637]
I would expect, as the [docs state](https://material.angularjs.org/latest/api/service/$mdDialog), that 'onRemoving' would be fired when the mdDialog hides/closes.

Looks like it's not the case :
http://codepen.io/bonatoc/pen/obwOvZ

**Comment by DevVersion** [comment]
That's not an issue. Your JSON Object is just wrong.
You are defining the `onRemoving` and `onShowing` functions not as function should defined.
These statements will be executed immediately.
 
```
{
  onShowing: (alert("opening!")),
  onRemoving: (alert("closing!")),
}
```

Everything work's perfect if you define the functions correctly

```
{
  onShowing: function() { alert("opening!") },
  onRemoving: function() { alert("closing!") }
}
```
Demo to checkout: http://codepen.io/DevVersion/pen/NxMMbG
This issue should be closed :)

**Comment by bonatoc** [comment]
Doh!

@DevVersion — Thanks. Ahhh, Javascript.

That's right, you can close this one.

**Comment by DevVersion** [comment]
@ThomasBurleson Please close.

**Comment by DevVersion** [comment]
Closing this, because it was a simple mistake in the `dialog` options.
