### ISSUE TITLE
Interest for doing theming in SCSS

### ISSUE THREAD

**Issue by DominicBoettger** [angular/material#6638]
Hi,

i did some work today to solve the theming completely in scss and to be able to create themes in scss dynamically.
To change the theme i just toggle the <body theme="mytheme"> attribute and change the theme without rewriting all the elements via javascript. It works very well and i am quite happy with the performance.

Do you have an interest to get this added to the default branch? If not i will start it as separate project...

Best regards
Dominic

**Comment by DevVersion** [comment]
Sounds in general really nice!. I didn't got one thing... how can I switch a theme dynamically? Is this still    possible? If so, how do you resolve the current `theme`, due a DOM Element / Attribute / Class?

**Comment by Frank3K** [comment]
I am also interested to see this feature. Can you provide a demo?

**Comment by ThomasBurleson** [comment]
Theming enhancements will be integrated only in ngMaterial 2.

**Comment by DominicBoettger** [comment]
@ThomasBurleson That's the information i needed. Thank you. I think i will  run this as separate project. 

I just did a quick workaround for the stuff i needed and copied all the javascript injected styling part into a scss file and reformated it. Then i added a theme="" attribute to my body.

If i want to toggle the theme i just toggle the variable in theme="mytheme".

```
body[theme="mytheme"] {
md-toolbar {
    &.md-hue-2 {
      &:not(.md-menu-toolbar) {
        background-color: $color-primary-hue-2;
        color: rgba(0,0,0,0.87);
      }
    }
    &:not(.md-menu-toolbar) {
        background-color: $color-primary-default;
        color: rgba(0,0,0,0.87);
        &.md-accent {
          background-color: rgb(189,189,189);
          color: rgba(0,0,0,0.87);
        }
    }
  } ............

The color generation happens with sass-material-colors.

I will now create functions to automatically generate a theme by adding the name and the colors. I think i will need some help when adding all the elements. I just added the elements used by myself right now and will improve it in the future. What i can say right now is that it may be more work to use scss in the first moment, but it's a huge improvement for me that i can manage the material and my custom theming at the same place and use central variables.

I will publish the scss files as soon as possible and maybe somebody is interested in improving the stuff.

Best regards
Dominic

**Comment by laicosly** [comment]
Angular Material could use an improved color-theming story.  I'd like to see colors defined separately from the angular-material.scss file.

**Comment by laicosly** [comment]
I don't understand the choice to use javascript theming, that idea doesn't seem right.  I'd like to see pure scss style/theming.
