### ISSUE TITLE
menu: support nested submenus

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6640]
<img width="286" alt="screen shot 2016-01-12 at 1 41 24 pm" src="https://cloud.githubusercontent.com/assets/338073/12277808/58d22d5c-b932-11e5-8bab-7c21a1b79e9e.png">

@conniew, @bourey

**Comment by bourey** [comment]
<img width="286" alt="screen shot 2016-01-12 at 1 41 24 pm" src="https://cloud.githubusercontent.com/assets/338073/12277808/58d22d5c-b932-11e5-8bab-7c21a1b79e9e.png">

**Comment by bourey** [comment]
priority: medium

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
