### ISSUE TITLE
menu: add labels

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6641]
<img width="156" alt="screen shot 2016-01-12 at 1 44 55 pm" src="https://cloud.githubusercontent.com/assets/338073/12277890/dce450fc-b932-11e5-8014-0327af2aa9a1.png">

> Also needed for mdSelect. Both Menu and Select need dividers and labels.

**Comment by bourey** [comment]
<img width="156" alt="screen shot 2016-01-12 at 1 44 55 pm" src="https://cloud.githubusercontent.com/assets/338073/12277890/dce450fc-b932-11e5-8014-0327af2aa9a1.png">

**Comment by bourey** [comment]
priority: medium

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
