### ISSUE TITLE
menu: open below originating element

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6642]
Support for position below the originating element and any optional offset.

**Comment by bourey** [comment]
<img width="128" alt="screen shot 2016-01-12 at 1 49 04 pm" src="https://cloud.githubusercontent.com/assets/338073/12278002/70ebfc96-b933-11e5-8a61-7a43ce2acbc1.png">

**Comment by bourey** [comment]
priority: medium

**Comment by DevVersion** [comment]
Isn't this already working with using the `y` target `bottom`?

**Comment by ThomasBurleson** [comment]
Related to #5150

**Comment by Splaktar** [comment]
Verified that this is working since at least `1.1.9`. ([Example CodePen](https://codepen.io/Splaktar/pen/bzjGgQ?editors=1010#0)) ([Documentation](https://material.angularjs.org/latest/api/directive/mdMenu#position-mode))
