### ISSUE TITLE
Support long labels in Select 

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6645]
In some cases the select label length may exceed the available horizontal space. 

@joeyperson

**Comment by bourey** [comment]
priority: low

**Comment by ThomasBurleson** [comment]
UX team feedback suggests "line wrapping" for both the selected text and the menu item text.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
