### ISSUE TITLE
Support for `required` field indicator

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6647]

**Comment by DevVersion** [comment]
Is this related to an Asterisk? Or what is meant by that?

**Comment by bourey** [comment]
Yes.  Here's a link to the latest Material spec for required fields: https://www.google.com/design/spec/components/text-fields.html#text-fields-required-fields

**Comment by DevVersion** [comment]
Oh okay I was wondering, because I already created a PR, which is ready for merge, a few days ago.
See #6518 Whats now :smile: ?

**Comment by DevVersion** [comment]
@ThomasBurleson Needs to be closed

**Comment by kuhnroyal** [comment]
This is very nice, could you add that to `md-select` as well? Should be a quick fix and keeps the inputs consistent. Maybe even datepicker/autocomplete?

**Comment by kuhnroyal** [comment]
Two things I noticed:
- doesn't work with `ng-required`
- asterisk is always red when the field is focused, should probably have the theme color until it is invalid?

**Comment by DevVersion** [comment]
Can't reproduce. Maybe create another issue with a demo. Already noticed the ng-required problem, but this relates to the given compontents.

**Comment by kuhnroyal** [comment]
https://material.angularjs.org/HEAD/demo/input
Focus one of the required fields, label is blue and asterisk is red.

**Comment by DevVersion** [comment]
@kuhnroyal - See #6978, everything works as expected. The only thing which is an issue, is the `ng-required`

**Comment by kuhnroyal** [comment]
@DevVersion Yea I just checked the spec, thanks.

**Comment by DevVersion** [comment]
@kuhnroyal Can you create a new issue for the `ng-required`, then I can reference it correctly

**Comment by kuhnroyal** [comment]
Created https://github.com/angular/material/issues/7105 to track `ng-required` support.

**Comment by corentin-gautier** [comment]
@DevVersion is there a support for the required asterisk on md-select ?

**Comment by DevVersion** [comment]
@corentin-gautier No not yet, please file another issue and ping me there.
