### ISSUE TITLE
chrome address bar won't hide on scrolling down

### ISSUE THREAD

**Issue by Navgeet** [angular/material#665]
md-content has overflow css attributes that prevent chrome address bar to hide when scrolling down. This generally happens on most websites and IMHO is a much required feature for mobile (combined, the address bar and top toolbar take valuable real estate).

In the meantime, I've overridden all overflow attributes on md-content to achieve the above. I suggest that angular-material should ship with overflow-scrolling = off by default to observe the common behavior.

**Comment by stephengardner** [comment]
Why is this closed?  I'm having this issue :/

**Comment by Remco75** [comment]
Same here, This should not be closed.

**Comment by Devjossy** [comment]
Issue close, guess I should look for a work-around
