### ISSUE TITLE
hover/focus for buttons (ux question)

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6651]

**Comment by ThomasBurleson** [comment]
@joeyperson - can you help us escalate this for resolution?

**Comment by bourey** [comment]
priority: medium

**Comment by ThomasBurleson** [comment]
* No hover indicator - need for desktop; important for discovery of icon buttons that are interactive.
* Focus has changes in percentages (12-20% black or white) of color.  

> Need specifications from UX team. @bourey to followup.
