### ISSUE TITLE
Refactor CSS classes to support public and private classnames

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6653]
To facilitate identification of CSS classes that can be easily customized and classes that should **not** be customized.

> This is a breaking change and should also see:
*  separate of animation stylings from other SCSS
*  use of a private css class also. e.g.
  *  select.css (public classes only)
  *  _select.css (private classes only)
* classnames have prefixing or trailing `_` character.
* support for unit tests that validate changes to public css only. 
  * @jelbourn - can you elaborate here ?

**Comment by topherfangio** [comment]
@ThomasBurleson Do you think we can close this issue now?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
