### ISSUE TITLE
build: detection duplicate css names

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6655]
Need a node module for css parsing to detect duplicate class names during builds. 

> Other considerations:
*  support property prefixing (e.g. `transition`
  transition property value prefixing)

**Comment by jelbourn** [comment]
Doesn't necessarily have to be a CSS parser, but something in the tooling that cleans up the same property being used more than once in the same rule. This does *not* apply to specific properties that have browser-prefixed values (such as `display` having `-webkit-flex` and then `flex`).

All three existing cases come from the use of SCSS mixins. They are:
* menu (text-align)
* menu-bar (text-align)
* datepicker (height)

If there was some way to clean this up with SCSS directly, that would be the best approach.

**Comment by jelbourn** [comment]
@ThomasBurleson I'm changing this to P2 because the amount of manual work it requires is very low.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
