### ISSUE TITLE
Checkbox with Select All/None in dropdowns

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#6656]

**Comment by DerekLouie** [comment]
Just for personal reference, an example: https://github.com/angular/material/pull/7674

**Comment by ErinCoughlan** [comment]
This is now possible using the md-select-header. Closing this issue.

**Comment by ThomasBurleson** [comment]
See the [Select Demo](https://material.angularjs.org/latest/demo/select) Pizza Toppings which uses the *multiple* attribute: `<md-select ng-model="selectedToppings" multiple>`
