### ISSUE TITLE
datepicker on non-white background or background image

### ISSUE THREAD

**Issue by philippbussche** [angular/material#6658]
Hi there,
please see my codepen http://codepen.io/anon/pen/dGzoeL
When using a datepicker component on a background that is not white (possibly a background picture) then there are a few not so nice looking things:
First the input field height does not seem to be right. Also when opening the date box then the header of the box is half transparent and half white.
Thanks
Philipp

**Comment by ThomasBurleson** [comment]
Duplicate

**Comment by philippbussche** [comment]
Hi @ThomasBurleson what issue is this a duplicate of please ?
Thanks
