### ISSUE TITLE
These flex options are missing in the docs.

### ISSUE THREAD

**Issue by donedgardo** [angular/material#6660]
... or very hard to find.

flex - Sets flex on all.
flex-sm - Sets flex on devices less than 600px wide.
flex-gt-sm - Sets flex on devices greater than 600px wide.
flex-md - Sets flex on devices between 600px and 960px wide.
flex-gt-md - Sets flex on devices greater than 960px wide.
flex-lg - Sets flex on devices between 960px and 1200px.
flex-gt-lg - Sets flex on devices greater than 1200px wide.

**Comment by ThomasBurleson** [comment]
Please see https://material.angularjs.org/latest/layout/introduction
