### ISSUE TITLE
md-select label displayed incorrectly when ng-model is null.

### ISSUE THREAD

**Issue by cafrean** [angular/material#6663]
When using a `<label>` along with `<md-input-container>` and `<md-select>`, and `ng-model` gets set to "null", two instances of the label is shown, in different states.

This was observed with the following code:

                <md-input-container>
					<label>Category</label>
					<md-select ng-model="selectedFilter">
						<md-option ng-repeat="filter in filters" value="{{filter}}">{{filter}}</md-option>
					</md-select>
				</md-input-container>

If I set `selectedFilter` to null in a function unrelated to the `md-select` the result is this:

![incorrectlabel](https://cloud.githubusercontent.com/assets/8956472/12291644/bef2bbb8-b9e8-11e5-80e9-432f8fac0a72.png)

**Comment by naomiblack** [comment]
This looks related to this issue, which should have been resolved. Regression? Or a missed use case? https://github.com/angular/material/issues/6274

**Comment by cafrean** [comment]
I'm sorry! Looking at the issue that @naomiblack referenced I realized that my project hadn't updated its version of Angular Material for a few weeks. The problem is no longer present in 1.0.1.
