### ISSUE TITLE
md-subheader with an centered parent

### ISSUE THREAD

**Issue by ricardobfa** [angular/material#6665]
Check pen for issue:
http://codepen.io/anon/pen/zrdNzX

In my desktop app, I have a div that make a centralized content, leaving the parent `md-content` fluid.

When scroll happen, `md-subheader` gets some extra margin and break his position.

I believe that subheader sticky event is basing on md-content position, but in this case, its diferent.

Is there any way of making this work? Except centering the hole md-content.

Thanks! 

edit: Firefox works fine.

**Comment by pdore-netfore** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
