### ISSUE TITLE
Header of interactive demo of Child Alignment not updated

### ISSUE THREAD

**Issue by glwesterbeek** [angular/material#6666]
The header from the Demo on: https://material.angularjs.org/latest/layout/alignment is not updated when changing the bullets. In the past it used to work fine. But not since 2 months or so.

![demoissue](https://cloud.githubusercontent.com/assets/7727296/12294809/589041be-b9fd-11e5-9264-7465b5410433.jpg)

**Comment by DevVersion** [comment]
That's a dupe issue, and is fixed in #6567

**Comment by glwesterbeek** [comment]
Ah, thanks for your reply. I should have checked for dupes. When will the fix become in effect on https://material.angularjs.org/latest/layout/alignment ?

**Comment by DevVersion** [comment]
That completely depends on the Team, when they got enough time to merge. But because this is dupe issue, you should close this issue :+1:

**Comment by glwesterbeek** [comment]
Will do! Enjoy your day
