### ISSUE TITLE
mdtabs freezes when the tab labels are of certain length or characters

### ISSUE THREAD

**Issue by arizonsolutions** [angular/material#6667]
md tabs freezes when the tab labels are of certain length or characters. Not sure if the length is the problem here. But, when i change the label, it works. Here is a codepen for investigation.

http://codepen.io/anon/pen/wMqgEy

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
