### ISSUE TITLE
md-toast weird behavior

### ISSUE THREAD

**Issue by dmaslov** [angular/material#6669]
When we have vertical scroll on the page and the ```Toast``` appears at the bottom, page scrolls up.
 [Link](http://codepen.io/anon/pen/vLJxBJ) to see the behavior (official doc with more content)

Thanks in advance!

**Comment by bozheville** [comment]
+1
Same behaviour when `md-toast` appears at the top

**Comment by DedMorozzz** [comment]
+1 same problem

**Comment by Greynight** [comment]
+1

**Comment by AntonKiva** [comment]
+1

**Comment by tuchk4** [comment]
+1

**Comment by PavloKovalov** [comment]
+1

**Comment by dani3l** [comment]
+1, happens from 1.0.0-rc6

**Comment by dani3l** [comment]
does anybody has a hotfix for that? it makes my app unusable at the moment

**Comment by Emeegeemee** [comment]
+1

**Comment by dani3l** [comment]
hotfix: 
```
.md-toast-animating {
  overflow: initial !important;
}
```

that works for me for now
