### ISSUE TITLE
Using angular-material in combination with Cordova/phonegap windowSoftInputMode

### ISSUE THREAD

**Issue by sushitommy** [angular/material#667]
Don't know if it's an issue, but if you want to use angular-material in a cordova/phonegap project you will encounter problems using 'adjustPan' or 'adjustResize' as windowSoftInputMode.
Because angular-material sets the body height to 100%, the soft keyboard will not make a form scroll to the selected field in order to keep it visible when the soft keyboard pops up.

**Comment by SaschaKrist** [comment]
I have the same problem. 
Could you fix the problem or did you find further information?
