### ISSUE TITLE
md-autocomplete ng-model issue

### ISSUE THREAD

**Issue by colbroth** [angular/material#6671]
Is there an example on how to make a custom directive from md-autocomplete? This is needed for a scenario in which I have two web pages. Each web page needs a state entry. I would like a shared directive to autocomplete the state entry as shown in the demo.

I have tried the following but the querySearch appears to fail to show auto-complete entries
For example

web page html has this
<state-directive ng-model="ctrl.selectedState"></state-directive>

state-directive.js has this
angular.module('myApp')
  .directive('stateDirective', function () {
    return {
      templateUrl: 'shared/state/state-directive.html',
      controller: 'stateCtrl',
      controllerAs: 'statectrl',
      scope: {
                ngModel: '='
            }
    };
  });

state.js has similiar code as demo.

I saw an example at http://www.chroder.com/2014/02/01/using-ngmodelcontroller-with-custom-directives/
and an example at http://plnkr.co/edit/A29hl6?p=preview

I tried both but they do not seem to work with md-autocomplete

**Comment by colbroth** [comment]
Here is the codepen http://codepen.io/colbroth/pen/QyMaQX/?editors=101

**Comment by scottsword** [comment]
@colbroth this is an issue for a google group or Stackoverflow not an issue with the project.
