### ISSUE TITLE
md-tabs can't be used for page navigation

### ISSUE THREAD

**Issue by gmoothart** [angular/material#6676]
The tab component does not work well as top-navigation (header links, with no md-tab-body). The root of the problem is that md-tabs fires a synthetic click event on init, which causes an infinite redirect loop if clicking on a tab causes a page navigation (which re-initializes the tabs which causes a click which triggers a page navigation...).

tab init triggers the select() function:
https://github.com/angular/material/blob/a4ea9deacd42933f9a4cefaecea23e904bfa1d05/src/components/tabs/js/tabsController.js#L81

select() triggers a click:
https://github.com/angular/material/blob/a4ea9deacd42933f9a4cefaecea23e904bfa1d05/src/components/tabs/js/tabsController.js#L293

**Comment by super-coder** [comment]
hm, i am using it with ui router and seems fine. I have a MoreInfoCtrl.js where i check ** vm.stateName = $state.current.name;** and tabs that are in moreinfo.html have md-active="vm.stateName=='moreinfo.someState'" and embedded  ui-view  in moreinfo.html 

So this way i can reload the page and selected tab becomes active

**Comment by charlietfl** [comment]
There is also a demo in the codepen examples that works fine  http://codepen.io/ThomasBurleson/pen/RNRBNq

**Comment by mackelito** [comment]
@super-coder does your stateChange fire once or twice? We keep getting dual triggers on the ng-click function.

**Comment by gmoothart** [comment]
@charlietfl in the codepen, `init` is not firing on tab change. If you are only reloading a view "under" the tabs, so the tab component is never re-initialized, it will work (maybe that is why @super-coder has it working).

For uninteresting reasons I need to do a reload of the top-level view that contains the tab bar. This causes the tabs to re-load, which causes that synthetic click, which causes a reload...

**Comment by gmoothart** [comment]
Here is a pen:
http://codepen.io/gmoothart/pen/VerGWj

It is actually not displaying the infinite-redirect problem, that may comes from a slightly different usage. But notice that in order to fully transition from tab 1 to tab 2 you have to click twice. the first click loads the tab content, but it takes a second click to move the selection bar.

**Comment by charlietfl** [comment]
@gmoothart switch to ui-router with nested view. So much more you can do with ui-router than ngRoute

**Comment by gmoothart** [comment]
@charlietfl that's not an option in my case, for historical/practical rather than technical reasons.

**Comment by laicosly** [comment]
with the latest angular + md versions, pagination doesn't seem to work.

**Comment by matheusdavidson** [comment]
I have the same issue, in my case i have one tab for a group of pages, for example: ```products```.
I have a ```ng-click``` on that tab pointing to ```product.list```, if i am in ```product.edit``` and reload the page, i get redirected back to ```product.list``` because ```md-active``` will select ```products``` and trigger ng-click.

**Comment by matheusdavidson** [comment]
Also, it gets really messy when i use the sidenav navigation(i have a main navigation in toolbar using md-tabs and sidenav menu with normal ```a``` tags and ```ui-sref```), this will change the state, making the tab trigger ng-click, in this case i get infinite loop redirect.

**Comment by xsegrity** [comment]
I am also having this issue. In my case I am using ui-router and have 2 abstract states with with a tab bar and multiple tabs each using ui-sref attributes to navigate. Each tab is a state (e.g. page). If I load a state that represents any of the tabs other then the first tab in the tab bar, and then navigate to any of the states in the other tab bar then the app will automatically bounce between the first tab states of both of the abstract pages. For example,

Page A (abstract state with 2 tabs)
    A.1 (tab 1)
    A.2 (tab 2)

Page B (abstract state with 2 tabs)
    B.1 (tab 1)
    B.2 (tab 2)

Load state for A.2 (it is important that it is NOT the first tab). Now navigate to state B.1 (it is important that it is the first tab).

The system will now bounce between A.1 and B.1 states. In Chrome adn FF this seems to go on forever. In Safari it will bounce several times and then stop.

**Comment by xsegrity** [comment]
Here is a workaround...

This seems to be an adverse reaction between the material tab code and the ui-router code when using ui-sref attribute. The infinite bounce occurs if I use the ui-sref attribute in md-tab. If I replace ui-sref with an ng-click that calls $state.go in the controller then it works as expected.

**Comment by alphatwit** [comment]
I think it would be good if md-on-select fired whenever the condition is satisfied (as it does now) but ng-click should only fire when someone actively presses the tab. The fake click on ng-click is counter-intuitive.

**Comment by epelc** [comment]
Please take a look at `md-no-select-click`. Enabling it should allow you to manage the selected tab yourself and prevent the initial click from `md-selected`.

Very bottom of page(md-no-select-click): https://material.angularjs.org/latest/api/directive/mdTabs

**Comment by mackelito** [comment]
Or take a look at the new navbar component.. https://material.angularjs.org/latest/demo/navBar

**Comment by epelc** [comment]
@mackelito there is that. But I'm trying to get it reverted as `md-no-select-click` should do the same thing without a ton of bloat.

https://github.com/angular/material/pull/7781#issuecomment-224935945

Please try your use cases with `md-no-select-click`.

**Comment by epelc** [comment]
@mackelito I take back my previous comment. I'm for `md-navbar` now. I wasn't aware of the subtle differences before. 

If you look at the spec in the issue @gmoothart mentions, they are targeted at different use cases even though they overlap a tiny bit.
https://github.com/angular/material/pull/7781#issuecomment-225020263
https://github.com/angular/material/issues/8421
https://material.google.com/components/bottom-navigation.html#

**Comment by topherfangio** [comment]
@gmoothart @epelc Can this be closed now that we offer the NavBar component? Should we just add some docs to the tabs pointing this use-case at the NavBar?

**Comment by gmoothart** [comment]
Yeah, sounds good to me.
