### ISSUE TITLE
pre-select text in input on md-autofocus?

### ISSUE THREAD

**Issue by adrianandreias** [angular/material#6679]
Shouldn't the text in an input box be selected when using md-autofocus on an input box?

```javascript
<md-input-container>
  <label>Name</label>
  <input name="name" type="text" value="abc" md-autofocus>
</md-input-container>
```

Currently the focus is set on the input box, but the cursor is placed at the end of text.

I'd prefer to have the text pre-selected, that's what happens when you use TAB key to move to another input box.

If you still think this behavior is fine what do you recommend to use in order to have the text pre-selected?

**Comment by ThomasBurleson** [comment]
IMO, this would be an enhancement with something like a `selectOnFocus` directive. 

> A PR is encouraged.

**Comment by bluebirdtech** [comment]
Really helpful, thank you.  I can now delete some custom code!

How about the same attribute for md-autocomplete?

**Comment by DevVersion** [comment]
@bluebirdtech You can create another issue for the autocomplete :+1:

**Comment by bluebirdtech** [comment]
Done, thanks! https://github.com/angular/material/issues/7125
