### ISSUE TITLE
Form error not working well with mdTextFloat

### ISSUE THREAD

**Issue by Nowis** [angular/material#668]
Hi.

There are some issues with the validation of type.
For exemple : 

```html
<input label="e-Mail" name="email" type="email" ng-model="user.email" required></input>
{{myForm.email.$error}} 
```

will show me the error if the email is not of the good format. ({"email":true})
BUT, 

```html
<md-text-float label="e-Mail" name="email" type="email" ng-model="user.email" required></md-text-float>
{{myForm.email.$error}} 
```

won't work for the same case.

edit : the form is considered invalid as expected event if {{myForm.email.$error}} is not accessible.

**Comment by ajoslin** [comment]
Fixed via 60fcd6f4d8b895162b37a940c3f33164d8044382
