### ISSUE TITLE
Accessing Documentation For Version 0.0.2

### ISSUE THREAD

**Issue by elimence** [angular/material#6683]
Hello ;)
I need a bit of help here. My company is still using a really old version of Angular material, we plan on migrating to the latest soon but that will be a lot of work and for the mean time we need to build some pressing features with version 0.0.2.

As it turns out, the documentation for 0.0.2 is no longer available online, so I've clone the repo and intent to revert to whatever commit corresponds with this version so I can access the docs.

I'd need some help with this though, for instance on which commit number to revert to and so on.
Hope this is possible.
Thanks :)

**Comment by topherfangio** [comment]
With running a version that old, you may run into some issues, but I *think* the following should get you what you want:

```bash
git checkout v0.0.2
npm install
bower install
gulp docs
```

I'm not positive (I haven't been on the project that far back), but I bet everything is output into the `dist/docs` directory which you can then drop on a web server (or use something like [live-server](https://github.com/tapio/live-server)) to view.

There may be some other useful commands in the `gulpfile.js` which you can review, but being that far back, I'm not sure we can offer much more assistance.

**Comment by elimence** [comment]
@topherfangio 
Thanks for the help. That worked. I had to downgrade npm and node to get it to work though.

**Comment by topherfangio** [comment]
@elimence Glad you got it working!
