### ISSUE TITLE
md-menu not opening adjacent submenus on hover.

### ISSUE THREAD

**Issue by jztein** [angular/material#6685]
Reproduce issue at:
http://codepen.io/anon/pen/zrdQwP
1. Open File menu
2. Alternate hovering on both New submenus.

It seems that only one menu item can react to open/closing hover events at a time.

**Comment by topherfangio** [comment]
Can definitely see this issue; working on a test/fix now.

**Comment by marc-antoinepelletier** [comment]
Thank you for the fix, it will be deploy for the 1.1.0 ? why not before ?

**Comment by DevVersion** [comment]
@marc-antoinepelletier This fix is a `patch` and should be available in the next patch release. `1.0.7`

**Comment by topherfangio** [comment]
@marc-antoinepelletier @DevVersion is correct; I am not sure why this was marked for milestone 1.1.0, but it indeed was pushed into our minor branch (in 4bdda21c03484443e5ec91df47a3d98cef95a9c7) which will be available in 1.0.7.

**Comment by marc-antoinepelletier** [comment]
Perfect, thank you !
