### ISSUE TITLE
#487 & #4233 sinking into the oblivion

### ISSUE THREAD

**Issue by michaelkrog** [angular/material#6694]
It seems that #487 and #4233 is sinking deeply into the oblivion.

They have been postponed since before release candidates, but much preferred by the community.
Please delegate to community if you do not plan to fix them!

**Comment by rhllor** [comment]
+1

**Comment by ThomasBurleson** [comment]
@michaelkrog - External Pull Requests on those would be welcomed.

**Comment by michaelkrog** [comment]
Cool. 

According to https://github.com/angular/material/issues/6278#issuecomment-169156296 the md-datepicker is following a spec not available to external contributors. 

But in your opinion that spec does not impose anything that would make a PR for #4233 a waste of time?

**Comment by twitchyliquid64** [comment]
+1
