### ISSUE TITLE
Adding max condition in input type="number" make form width smaller

### ISSUE THREAD

**Issue by xavierva** [angular/material#6696]
When I add a max limit like this :

                    <input type="number" min="0" max="20" required>

my form become smaller.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/ThomasBurleson/pen/zvorxN
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by xavierva** [comment]
Here is a Plunkr : http://plnkr.co/edit/5mNQOS3xbEqIlwTCaLQ3?p=preview

If you remove : 
 max="20" of input field seats you will see that the form width change.
