### ISSUE TITLE
Exclude layout.attributes.scss from closure build output

### ISSUE THREAD

**Issue by jelbourn** [angular/material#6703]
When running `gulp build-all-modules --mode=closure`, the definitions for `layout.attributes.scss` are included in the outputted `core.css`. These styles should be omitted.

cc @ThomasBurleson

**Comment by jelbourn** [comment]
Still a thing we need to do.

**Comment by ThomasBurleson** [comment]
@jelbourn - I will take care of this before Monday.

**Comment by ThomasBurleson** [comment]
@jelbourn - @DevVersion already did this on 4/5/2016 with SHA 8fe22d12af

> chore(build): bower-material should update style modules and remove stale files  
* `angular-material.scss` copied into `modules/scss` * `core/layout/ie_fixes.css` copied into `modules/css` * `layouts/*.{css,scss}` copied into `modules/{css,scss}` * Removed stale `./demos/` folder. 
* Core Modules (default + closure) should not contain layout attributes. (only classes)  
Fixes #7835. Closes #7849
