### ISSUE TITLE
Don't add `goog.require` for ngAnimate in Closure output

### ISSUE THREAD

**Issue by jelbourn** [angular/material#6704]
When running `gulp build-all-modules --mode=closure`, the outputted `core.js` file contains the line `goog.require('ng.ngAnimate');`. The `ngAnimate` module should be excluded from generation of `goog.require` statements.

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you fix this one?

**Comment by ThomasBurleson** [comment]
@DevVersion  - can you reopen #6721 ?

**Comment by DevVersion** [comment]
@ThomasBurleson Done. I just thought that @robertmesserle is taking this issue.

**Comment by robertmesserle** [comment]
Ah, this issue wasn't really on my radar because we had a PR to fix it.  Let's use the PR =p

**Comment by DevVersion** [comment]
@robertmesserle Oh well :) - About the PR, I think it would be great if you take a look at it, I'm not really sure about the way the modules should be exported.
