### ISSUE TITLE
Request: md-colorpicker

### ISSUE THREAD

**Issue by omeid** [angular/material#6709]
`<input type="color">` is still [not supported by some major browsers](http://caniuse.com/#feat=input-color), the usual suspects, IE and the IE6-round-two (also known as Safari).

Inline with md-options, md-select, md-datepicker, and other _enhanced_ form controls, it would be nice to have `md-colorpicker` or provide a consistent colorpicker when using `<input type="color">`.

Some previous art:

[Paper Color by David Mulder](https://github.com/David-Mulder/paper-color-picker)
![Color Picker Paper Element](https://cloud.githubusercontent.com/assets/46602/11616912/36579ee6-9c87-11e5-9067-6a64922d6636.png)

This dribble by [Carl Hauser](https://dribbble.com/shots/2013584-Material-Colorpicker).

![Color Picker Mockup](https://d13yacurqjgara.cloudfront.net/users/48670/screenshots/2013584/material-colorpicker.gif)

And the [brianpkelley](https://github.com/brianpkelley/md-color-picker)'s Angular Material Implementation
![Angular Material Colorpicker](https://raw.githubusercontent.com/brianpkelley/md-color-picker/master/md-color-picker.png)

**Comment by Frank3K** [comment]
Is there an official color picker in the [material design guidelines](https://www.google.com/design/spec/material-design/introduction.html)? If not, I doubt if the component is going to be added.

Are there issues with e.g. brianpkelley implementation?

**Comment by omeid** [comment]
@Frank3K Yes, quite a few. For example, you can't use it inside an md-dialog as it uses an md-dialog itself.

**Comment by EladBezalel** [comment]
@omeid at this moment there's no memory of color picker in the material design spec. 
ngMaterial project aims to provide components according the design spec and follow it completely. 
The idea you posted are very nice, you can create a directive that uses datepicker or a dialog to assemble the color picker, PRs are very welcome.

**Comment by EladBezalel** [comment]
@omeid at this moment there's no memory of color picker in the material design spec. 
ngMaterial project aims to provide components according the design spec and follow it completely. 
The idea you posted are very nice, you can create a directive that uses datepicker or a dialog to assemble the color picker, PRs are very welcome.

**Comment by Frank3K** [comment]
I ended up using [angular-color-picker](https://github.com/ruhley/angular-color-picker), which since 1.0.0 does not have a dependency on `bootstrap` (and therefore `jQuery`) anymore.
