### ISSUE TITLE
md-autocomplete - when dropdown list is open, attempting to scroll while hovering over the input, shifts the dropdown 

### ISSUE THREAD

**Issue by tonyawad88** [angular/material#6716]
Hello,

When hovering over the autocomplete input, attempting to scroll while the mouse is over the input shifts the dropdown list. This happens in Master branch and in version 1.0.2. This happens in Chrome, Firefox, Safari on MAC. It seems like it happens on all browsers.

Please let me know if you need more info.

Here's a snapshot of it:
![autocomplete_bug](https://cloud.githubusercontent.com/assets/3638322/12374184/f88cdd6a-bc61-11e5-9f1f-8aef70425187.gif)

**Comment by 0101adm** [comment]
this is a dup.

**Comment by DevVersion** [comment]
Correct @0101adm - PS: it's already fixed in #6589

**Comment by tonyawad88** [comment]
@DevVersion @0101adm Thanks guys.

**Comment by DevVersion** [comment]
@tonyawad88 It would be nice if you close your duplicated issue :)

**Comment by tonyawad88** [comment]
For sure :)
