### ISSUE TITLE
md-dialog still does not work with $q.all()

### ISSUE THREAD

**Issue by philippbussche** [angular/material#6719]
Hi,
I am trying to show a dialog with a progress circle while data loads and automatically hide the dialog again after data has arrived. I found the solution of a gentleman who reported the usage of $q only to be working in angular material 0.10.x and below (https://github.com/angular/material/issues/3919). What he built would be exactly what I am after.
The issue is marked as fixed but when I tried with a recent version then this still does not seem to work. Please see my codepen: http://codepen.io/anon/pen/EPwpKe - the dialog never closes.
Are there any other ways how to open and close a dialog after data loading has finished ?
Thanks
Philipp.

**Comment by Emeegeemee** [comment]
My guess is that it has something to do with the promises resolving in the same digest as opening the dialog. I modified [your codepen](http://codepen.io/anon/pen/YwrJqv?editors=101) by wrapping the promises in a timeout and it seems to work as you want it to.

**Comment by philippbussche** [comment]
Thanks @Emeegeemee. I took your changes over into my app and it is now working as I am expecting it. I am pasting my Controller source below if anybody else ever needs something similar. As you can see I am querying data via a factory and as soon as thats there I am closing my dialog again. I am still new to Angular so one of the things I currently dont yet understand is why I have to specify the promise I get back from the factory call with $promise in my return function as this is different in the codepens but if I don't do that it just won't work meaning that the Dialog hide is executed immedeatly.
Thanks again for your help on this !

myControllers.controller('ResultsCtrl', ['$scope', 'DialogFactory', '$q', '$timeout', 'Cities',
    function ($scope, DialogFactory, $q, $timeout, Cities) {

    DialogFactory.show("Loading cities...");
    $q.all([fetchCities()]).
         then(function(result) {
            DialogFactory.hide();
    });

    function fetchCities() {
        $scope.cities = Cities.query();
        return $timeout(function() {return $scope.cities.$promise;});
    }

}]);

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
