### ISSUE TITLE
Refactor aria checks into compile phase instead of directive link or controller init.

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#672]
See @kseamon PR #613.

**Comment by marcysutton** [comment]
@ajoslin @rschmukler I committed the checkbox fix for #1094 in https://github.com/angular/material/commit/4c394732a4291ba65d8a1b1a09ef92005d977ce0. 

The remaining issue with `$mdAria` is around `ng-bind` on mdButton. This warns there is no label even though the text will read fine in a screen reader:

```html
<md-button ng-if="section.type === 'link'"
  ng-class="{'active' : menu.isSectionSelected(section)}"
  ng-href="#{{section.url}}">
  <span ng-bind="section | humanizeDoc"></span>
</md-button>
```

To close https://github.com/angular/material/issues/507#issuecomment-68619808, I could use some help timing the label enforcement.
