### ISSUE TITLE
Datepicker Issues (Release 1.0.2)

### ISSUE THREAD

**Issue by sudharsanmit** [angular/material#6725]
One of the best date pickers with no JS needed. Appreciations. However, I encountered too many issues while using it. Putting all together as one.

Standard Day Picker:

Issue 1:
Onhover disabled indicator existed on the disabled date picker in version 0.11.4 - https://material.angularjs.org/0.11.4/demo/datepicker
Missing in latest release (https://material.angularjs.org/latest/demo/datepicker). Intentional?

Issue 2:
No way to navigate the months/years without using keyboard arrows. 

Issue 3:
Calendar icon and Dropdown arrow next to date input are redundant. Onclick of the dropdown, the Calendar icon gets highlighted and calendar form fans out thus making it redundant. 

Issue 4:
Date can be selected through click of mouse only till Jul-13-2097. But keyboard can be used to select further dates.

Issue 5:
Input date 13/20/2097 through keyboard. On clicking calendar icon, the date Jan 20 2098 gets highlighted and able to select first week of Jan 2098 (1,2,3 & 4) selectable thru mouse. Unable to choose any before or after. Also note, no restriction on the month (13 entered).

Issue 6:
I selected Jan 1 2098, and reopened the calendar dialog by clicking on the icon, onhover - Dec 2097, 22nd to 28th becomes selectable. I did not select any but pressed up arrow once to go to Dec 2097 month. But the same Dec 2097, 22nd to 28th becomes un-selectable.

Issue 7:
When the calendar dialog is closed by clicking outside, the focus is still retained on the icon/dropdown with shadow.

Issue 8:
33333/1/2016 and 33333/1//2016 seems to be a valid input on a standard date picker but highlighted with red underline on all others. Infact, none of the basic validations on a date are done implicitly.

Issue 9:
Can see no dates later than Mar 2099 on calendar either thru keyboard scroll or a date input and a calendar open. So, the calendar supports only max 83 years!!

Issue 10:
No implicit input type validations present on date input.
https://docs.angularjs.org/api/ng/input/input%5Bdate%5D

 

Only weekends are selectable:
Issue 1:
Max date selectable by click of mouse is 1/3/2099. Able to scroll through arrow keys and select further weekends. If I select thru' keyboard, unable to use mouse to select even the 1/3/2099 which was possible earlier.

With ngMessages:
Issue 1:
Input = 13/32/874852
Output = The entered value is not a date!

Input = 13/32/2016
Output = This date is required!

Input validation is not consistent.

**Comment by jelbourn** [comment]
@sudharsanmit Please try to only file one problem per issue. Grouping a bunch of things into a single issue makes it impossible to track and de-dupe.

**Comment by sudharsanmit** [comment]
@jelbourn @ThomasBurleson Opened issues separately as requested and pinned to parent #6725. Let me know if anything more is required.

**Comment by DevVersion** [comment]
Thanks for filing all that issues, but to be honest the titles of all that issues are confusing me a bit. It would be awesome if you change them to a actual title.

**Comment by jelbourn** [comment]
@sudharsanmit thanks for breaking them up. In the future, please note that the issue title should describe what the issue is about. Just saying "Datepicker issues" is not very helpful.
