### ISSUE TITLE
FAB Speed dial is empty after being displayed due to breakpoint change

### ISSUE THREAD

**Issue by SpenceDiNicolantonio** [angular/material#6726]
When a FAB Speed Dial component is initially hidden when the page loads, and later displayed as a result of a breakpoint being reached, the Speed Dial is empty. For example, applying `hide-xs` to a FAB Speed Dial, loading the page with the browser at less than 600px, and then expanding the browser window to greater than 600px causes the Speed Dial to appear, but there are no buttons within it.

**Comment by ThomasBurleson** [comment]
@topherfangio - FYI.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
