### ISSUE TITLE
md-select bug

### ISSUE THREAD

**Issue by yccteam** [angular/material#6733]
Hi,
I've noticed a bug in md-select (it might be intentional though).
In version 0.10 and below, when you had a small wrapper for the md-select, it would have cut the label inside the md-select and added 3 points:
http://plnkr.co/edit/T1UzWlWY8aaMWrM9xPWb?p=preview
Now, when I try to do the same with version 0.11 and above, the label from the md-select now overflows:
http://plnkr.co/edit/hTBqUnFQQekNEy5YUVc5?p=preview
(in this case I've used the latest version, but v 0.11 also exhibits the same difference).
Is this intentioal? Is it a bug? It seems like the correct behavior is the one before version 0.11.

**Comment by pasqLisena** [comment]
+1 I confirm this issue

**Comment by RolandHeath** [comment]
This is a duplicate of #6312 - but it might help the team to know where it was introduced.

**Comment by pasqLisena** [comment]
Yes, it is the same behavior... We can close this one.

**Comment by yccteam** [comment]
Yeap, the same indeed :)
