### ISSUE TITLE
Error in $mdDateLocaleProvider documentation

### ISSUE THREAD

**Issue by vguede** [angular/material#6735]
In $mdDateLocaleProvider documentation, the formatDate implementation doesn't support null or undefined values.
Suggestion of fix :
Instead of :
```javascript
$mdDateLocaleProvider.formatDate = function(date) {
    return moment(date).format('L');
  };
```
Write :
```javascript
$mdDateLocaleProvider.formatDate = function(date) {
    return !date ? '' : moment(date).format('L');
  };
```

**Comment by DevVersion** [comment]
At the moment, the `$mdDateLocaleProvider` / `momentjs` will return `"Invalid date"` if using `null` as input date. And if you use `undefined` it will return the current date formatted in `L`

Wouldn't it be better to return just an `undefined` value instead of an empty string?

**Comment by vguede** [comment]
I think null ou undefined values means no data.
The default formatDate begins by :
``` javascript
if (!date) {
    return '';
}
```
This is why I suggest my fix.

**Comment by vguede** [comment]
The default formatDate method is in dateLocaleProvider.js, lines 157 to 175 :
```javascript
 function defaultFormatDate(date) {
        if (!date) {
          return '';
        }

        // All of the dates created through ng-material *should* be set to midnight.
        // If we encounter a date where the localeTime shows at 11pm instead of midnight,
        // we have run into an issue with DST where we need to increment the hour by one:
        // var d = new Date(1992, 9, 8, 0, 0, 0);
        // d.toLocaleString(); // == "10/7/1992, 11:00:00 PM"
        var localeTime = date.toLocaleTimeString();
        var formatDate = date;
        if (date.getHours() == 0 &&
            (localeTime.indexOf('11:') !== -1 || localeTime.indexOf('23:') !== -1)) {
          formatDate = new Date(date.getFullYear(), date.getMonth(), date.getDate(), 1, 0, 0);
        }

        return formatDate.toLocaleDateString();
      }

```

**Comment by DevVersion** [comment]
Okay, thanks for pasting that snippet and for the clarity. Then as the `defaultFormatDate` function is also returning an empty string, the `formatDate` function should do the same. If you want you can create a Pull Request with your suggestion. If not, let me know ;)

**Comment by vguede** [comment]
I never submit a PR. If you can do this... ;o)

**Comment by crisbeto** [comment]
This seems like it got fixed at some point, the method looks like this, at the moment:

```js
$mdDateLocaleProvider.formatDate = function(date) {
    var m = moment(date);
    return m.isValid() ? m.format('L') : '';
};
```

**Comment by dipak-oodles** [comment]
$mdDateLocaleProvider.formatDate = function(date) {
    return !date ? '' : moment(date).format('DD-MM-YYYY');
  };
