### ISSUE TITLE
md-tabs don't work with md-dynamic-height 

### ISSUE THREAD

**Issue by Davidx7** [angular/material#6739]
`<md-tabs md-dynamic-height md-border-bottom md-selected="currentTab">
       <md-tab label="one">`

Just a standard copy/past of tabs using `angular 1.4.8` and latest `angular-material`.
The bug is while using `md-dynamic-height` and the height changes (does NOT apply to to tabs of same size, even if the directive is there), after it changes, you can no longer switch to other tabs because the it doesn't work anymore. 

1st time the height changes, the click event dissappears and you can no longer change tabs

**Comment by RolandHeath** [comment]
@Davidx7 You'll get a better response from the community and/or team if you can provide a demo - it might be worth making a minimal codepen/plunkr to reproduce this, and post it here.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. I will reopen at that point.
Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by Davidx7** [comment]
Found the fix! 
HammerJS needs to be loaded before angular-material and not after (I was loading it straight after)
For some reason it works now.
