### ISSUE TITLE
flex-* options missing from docs

### ISSUE THREAD

**Issue by zbjornson** [angular/material#6742]
Here it seems that `flex-xs` and friends were removed from the docs:
https://github.com/angular/material/commit/f6e97a02a9c88b1695094a8a85a11958924e4c61#diff-f43b73a8f49340f536407d62cc0e1ad9L127

I don't see that they were moved, nor do I see a reason in the commit message. They still work. Mistake?

**Comment by zbjornson** [comment]
@ThomasBurleson not sure why this was put in the deprecated milestone. Are they now considered private? Would a PR be accepted to revert the part of the commit that removed them?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
@zbjornson - Not sure I understand, so these Layout pages arond https://material.angularjs.org/latest/layout/children not provide the documentation?

**Comment by zbjornson** [comment]
@ThomasBurleson Sorry, now I see why this was confusing. That page is missing the responsive media queries for `flex` only. That page has:

* `flex-offset` and its responsive variants (`flex-offset-xs`, etc.)
* `flex-order` and its responsive variants (`flex-order-xs`, etc.)
* `flex`, but **not** its responsive variants (`flex-xs`, etc.). The commit that I referenced removed the documentation, but did not remove the implementation.
