### ISSUE TITLE
bug(toast): causes scrollbars to hide while animating in

### ISSUE THREAD

**Issue by sebakerckhof** [angular/material#6743]
I have a page where the body has scrollbars, when adding an toast to it, the scrollbars are hidden for a moment and then reappear.

Btw, this seems opposite to:
https://github.com/angular/material/issues/4019

**Comment by DevVersion** [comment]
Here a demo to reproduce the issue. http://codepen.io/DevVersion/pen/jWaedW

**Comment by dani3l** [comment]
hotfix: 
```
.md-toast-animating {
  overflow: initial !important;
}
```

that works for me for now

**Comment by sebakerckhof** [comment]
@ThomasBurleson Why deprecated?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
