### ISSUE TITLE
Mobile : Focus stays on input when clicking elsewhere

### ISSUE THREAD

**Issue by pellenberger** [angular/material#6747]
To reproduce using a mobile device : 
Go to material.angularjs.org -> Demos -> Input -> Errors Advanced.
Click on the email input. The keyboard is opened. Close it or not then click on a text or on the input switch placed in the same form (without enter any text in the email input). 
Expected behavior is : the keyboard is closed and the email input loses focus.
Effective behavior is : the keyboard is reopened if previously closed and the email input keeps the focus

Tested on Chrome using Android 6.0.1 (Nexus 5)

**Comment by 0101adm** [comment]
dup of #5365.
