### ISSUE TITLE
md-select inside md-input-container has wrong margin/padding

### ISSUE THREAD

**Issue by usarskyy** [angular/material#6748]
As you can see on the image below, "Titel" label overlap "md-select" element because "md-select" does not have any following "md-errors-spacer" DIV element (like text input does).

![image](https://cloud.githubusercontent.com/assets/1206777/12420936/c1ad20c4-bebf-11e5-8f59-d68021a8d05e.png)

"md-input-container>md-select" CSS style explicitly defines "margin: 0" but the right solution would be to have "margin-bottom: 24px;" (24px => height of "md-errors-spacer" DIV element)

Also you could notice small issue with floating label on "md-select" element: 2-3 pixels on the top are hidden. I could not find the source of this problem and not sure whether I have to update my layout or it is a bug. Please advise.

I am using Google Chrome 47, Angular Material v1.0.2

**Comment by usarskyy** [comment]
BTW, I am using Google Chrome 47, Angular Material v1.0.2

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
