### ISSUE TITLE
"md-no-float" does not work

### ISSUE THREAD

**Issue by usarskyy** [angular/material#6749]
I have two text inputs. First one does not have "md-no-float" attribute on "md-input-container" specified. Second contains this attribute.
At the end the behavior for both elements is exactly same:

![image](https://cloud.githubusercontent.com/assets/1206777/12421679/aa06559a-bec3-11e5-9bf6-cc45965b2815.png)

I am using Google Chrome 47, Angular Material v1.0.2

**Comment by DevVersion** [comment]
As you can see [here](https://material.angularjs.org/latest/api/directive/mdInputContainer), if the attribute `md-no-float` is provided, we not convert placeholders to floating labels, but you are using a `<label>` which will be converted to a `floated label`, so you should use the `placeholder` attribute on the `<input>` and remove the `<label>`

**Comment by usarskyy** [comment]
Sorry, I thought that "placeholders" in the description was just a mistake because in the example above "label" was used :) My bad!

**Comment by DevVersion** [comment]
That's a good point (can confuse the demo above). But I think if you read the attribute definition you will get the right usage ;)

**Comment by ThomasBurleson** [comment]
Documentation needs to be improved/clarified.
