### ISSUE TITLE
md-autocomplete forced to double click selected item 1.0.2

### ISSUE THREAD

**Issue by colbroth** [angular/material#6750]
After clearing autocomplete options, one is forced to select the item twice before it will actually be selected.

Reproduce:
1. Load Angular Material Demo App for md-autocomplete
2. Select any state 
3. Click the X button
4. Select any state 
** at this point when you click on a state nothing happens, expected the state to be selected just as it had been selected in step 2
5. Click on the selected state again. 
** at this point, the state gets selected.

Expected the state to get selected at step 4, we should not have to click on the state twice to get it selected.

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you investigate plz.

**Comment by robertmesserle** [comment]
@ThomasBurleson Were you able to recreate this issue on HEAD?  It seems to be working fine for me.

**Comment by colbroth** [comment]
It is not reproducible on HEAD. Sorry I didn't check if it was fixed on HEAD. It is reproducible in the current version 1.0.2 using Google Chrome and Windows 10.

**Comment by colbroth** [comment]
The issue still exists in version 1.0.3. It does not exist in HEAD.

**Comment by topherfangio** [comment]
I just tested 1.0.3 on Chrome, Edge and IE and could not reproduce.

@colbroth What browser are you using?

**Comment by colbroth** [comment]
I am using google chrome Version 48.0.2564.82 m on a Windows 10 Desktop 64
bit

On Mon, Jan 25, 2016 at 2:24 PM, Topher Fangio <notifications@github.com>
wrote:

> I just tested 1.0.3 on Chrome, Edge and IE and could not reproduce.
>
> @colbroth <https://github.com/colbroth> What browser are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/6750#issuecomment-174628370>.
>



-- 
* ´¨)
¸.· ´¸.·* ´¨) ¸. ·*¨)
(¸.·´ (¸ Lisa

**Comment by ThomasBurleson** [comment]
Closinig as code not reproduce.
