### ISSUE TITLE
defaultViewBoxSize, doesn't set a size for md-icons directives. it doesn't work

### ISSUE THREAD

**Issue by morwin10** [angular/material#6766]
I'm new with angular and programming in general
So maybe I'm wrong

But I tried to solve it alone with a few variations and it does not work for me
I made an example here:
http://codepen.io/anon/pen/XXzybz?editors=101

PS
I also tried with defaultIconSet() with a URL.
like this:
$mdIconProvider.defaultIconSet ( url )
But it doesn't work to

And Just make sure that I understand correctly :

$mdIconProvider.defaultViewBoxSize( int )
Sets a default size for all  `<md-icon>` directives
right ?

Thanks for the help

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
