### ISSUE TITLE
 Datepicker Issues (Release 1.0.2) #6725 #6764 

### ISSUE THREAD

**Issue by sudharsanmit** [angular/material#6768]
Datepicker Issues (Release 1.0.2) #6725 #6764 

Reopening the issue #6764 and attached screenshot. @jelbourn

**Comment by jelbourn** [comment]
@sudharsanmit Please read and follow our [guide for submitting issues](https://github.com/angular/material/blob/master/CONTRIBUTING.md#submit). Please be aware that we get _hundreds_ of issue reports per week and that we are not able to investigate issues that don't follow these guidelines to provide enough information.

Most important missing things here are the *issue title* and *browsers / OS*.

**Comment by sudharsanmit** [comment]
The issue was produced on Firefox browser.

**Comment by ThomasBurleson** [comment]
@sudharsanmit - please do not **pin** issues. If you do not provide clear details for each issue **AND** CodePen then we will not support your issue.
