### ISSUE TITLE
Component Build Incomplete

### ISSUE THREAD

**Issue by pdjisok** [angular/material#6773]
I followed instructions to build component for debug (on Windows 2008).  I ran 'gulp watch-demo -c tabs' and then 'gulp server'.  It looks like index.html needs processing step.  I have attached it (added.txt extension).

[index.html.txt](https://github.com/angular/material/files/96839/index.html.txt)

**Comment by DevVersion** [comment]
Hello,

That's a duplicate of #6396 and is fixed in #6406

**Comment by pdjisok** [comment]
Works now, thanks.  I can quit banging my head.
