### ISSUE TITLE
md-list-grid to work like masonry.js

### ISSUE THREAD

**Issue by acondiff** [angular/material#6775]
Would it be possible to have md-list-grid to work like masonry.js?

**Comment by ThomasBurleson** [comment]
Please provide more details and specific requests.

**Comment by DevVersion** [comment]
@acondiff Any updates here?

**Comment by acondiff** [comment]
To clarify, I believe Angular Material would benefit from a brick-like layout like this. http://codepen.io/acondiff/pen/jWvree

They do something similar in the new Google+. It should have Infinite and virtual scroll functionality as seen in this pen. Infinite scroll meaning we have a callback method when the users scroll approaches the bottom of the content area. Virtual scrolling meaning as you scroll down it removes DOM items from the top (and vise versa).

**Comment by bennyp123** [comment]
This would be killer. I tried laying out a blog with <md-list-item><md-card> and it just didn't work as expected when cards and images were of variable height.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
