### ISSUE TITLE
Using multiple versions of angular-material in a project

### ISSUE THREAD

**Issue by elimence** [angular/material#6777]
Hi everyone :)

So my company started using angular material from the early days and haven't been able to keep up because it's a lot of work migrating because our code base is huge and we don't have too many hands at the moment.
We are currently on version 0.0.2 (very ancient, I know)
Thing would be really cool to start using the latest version, with all the awesome additions currently available.
But since we can't immediately migrate, I'm considering the possibility of using the latest version along with our current version, 0.0.2
Is this possible? or would the two versions conflict. Version 0.0.2 uses the material prefix (e.g <material-divider>) as opposed to the latest which uses md (e.g <md-divider>), not sure if that makes a difference.

Hope it's possible
Thanks

**Comment by ThomasBurleson** [comment]
That is not possible. And you should definitely update to 1.0... otherwise even forum support will not be available/pertinent for you.
