### ISSUE TITLE
mdListItem: .md-exclude class is being ignored

### ISSUE THREAD

**Issue by websirnik** [angular/material#6779]
According to the docs https://material.angularjs.org/latest/api/directive/mdListItem, I can add `.md-exclude` class to the element inside `<md-list-item>` and it will not be wrapped inside the primary `<md-button>`.

However this is not happening. In the following example, `.md-exclude` is being ignored, "Action" button is placed inside the primary `md-button`, so clicking "Action" will trigger 2 alerts, instead of 1: http://codepen.io/websirnik/pen/xZpGKO

**Comment by DevVersion** [comment]
Yes I can reproduce that issue. And it will be fixed in #6493 (PR is pending)

**Comment by websirnik** [comment]
Great. As a side comment: would be good if `.md-exclude` would work with any element, not only `md-button`. (may be it is already in the PR)

**Comment by DevVersion** [comment]
Update: `.md-exclude` is only working if the element is not containing `ngClick`, `ngHref`, etc. And your `<md-list-item>` is containing `ngClick`, that's why in your case `.md-exclude` isn't working. But as said, #6493 is solving all child button `click / mousedown` issues. So this issue is still related to #6493 (exactly for your case)

**Comment by DevVersion** [comment]
@websirnik Just wan't to notify you, #6493 got merged. 

See your demo running with `master`: http://codepen.io/DevVersion/pen/zrepyQ

**Comment by DevVersion** [comment]
Fixed the general layout issue with  SHA bb5c105 - Marking this as `works as expected` because:
> .md-exclude is only working if the element is not containing ngClick, ngHref, etc. And your <md-list-item> is containing ngClick, that's why in your case .md-exclude isn't working
