### ISSUE TITLE
ng-show on md-button

### ISSUE THREAD

**Issue by wiwofone** [angular/material#678]
I have an ng-show on an md-button. A click on the button triggers a function (with ng-click) which sets the variable that ng-show depends on, effectively hiding the button and showing a couple of other buttons. I.e: a click on the button hides the button itself and shows new buttons.

However, even with the ripple ink effect disabled, the md-button doesn't seem to hide until the ripple (existent or non-existent) has finished its animation. This means that the button isn't hidden immediately, but with a slight delay.

When doing this with regular buttons, the problem does not arise, which leads me to think that the problem is with the md-button directive. How would one go about fixing this? I've included a short gif (with clicks highlighted) to make it easier to understand.

![md-button2](https://cloud.githubusercontent.com/assets/1745801/5090578/557c453c-6f43-11e4-81a4-521b64a6b88b.gif)

**Comment by olee** [comment]
Hi, I somehow got the exact same issue, however using latest version.
If I exchange the md-button for a simple button, it directly disappears like it's supposed to do.
