### ISSUE TITLE
List popout/expansion feature

### ISSUE THREAD

**Issue by langdonx** [angular/material#6781]
I'm not really sure what these things are called, but but both Inbox and Apps uses them:

![image](https://cloud.githubusercontent.com/assets/441982/12452991/33a147d8-bf5f-11e5-986b-7fee6c25abd3.png)

![image](https://cloud.githubusercontent.com/assets/441982/12452989/314711d4-bf5f-11e5-8a8c-2f0693ca3691.png)

Where a list item pops out of the list and expands into the forefront.

I'm fairly certain this type of functionality doesn't exist in Angular Material at the moment, but is it on the roadmap or is there a side project that offers this type of control already (like what md-data-table has done for Data Tables)?

**Comment by ThomasBurleson** [comment]
Not planned for v1.0.0.

**Comment by extra-0** [comment]
@ThomasBurleson Is this planned to be included in v2.0 stable?
