### ISSUE TITLE
Roadmap for the project is missing

### ISSUE THREAD

**Issue by korya** [angular/material#6787]
I would like to know what is the status of the project, what are the next milestones, and the current priorities. Currently the project has almost 1.5K open issues and more than 4K closed ones, so it is really hard to get the big picture of the project and understand its dynamics.

Where can I find a roadmap for the project? Is there one?
If there is one, is it possible to publish it here in the repository? or at least to have a link to it?

**Comment by vrosa** [comment]
+1

**Comment by ThomasBurleson** [comment]
Valid point!
