### ISSUE TITLE
SpeedDial: Remove necessity of ng-cloak on parent.

### ISSUE THREAD

**Issue by topherfangio** [angular/material#6788]
Currently, there is often a requirement that the Speed Dial's parent use `ng-cloak`. Although we document this, it should not be required.

The main reason this is currently necessary is because the Speed Dial uses flex positioning for the hidden items, meaning that the "default" CSS state of the component has the items positioned where they will be when opened, and we use JS to translate the positions to be hidden behind the trigger.

Ideally, we would ensure that the component starts out closed with all of the items hidden behind the FAB and upon opening, it translates the items into place. This may require a rewrite of the layout/CSS to use absolute/relative positioning rather than flex.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
