### ISSUE TITLE
md-tabs + .md-primary

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6791]
chrome.

md 1.0.2

to make the tab labels part of the toolbar, am styling with .md-primary.

the undesired effect is the 'tab highlight' color super imposes on the md-primary, making a new color... which isnt useful or tasteful.

the color is very faint but noticeable.

![screen shot 2016-01-20 at 6 14 21 pm](https://cloud.githubusercontent.com/assets/5133412/12468603/58dd5594-bfa2-11e5-8554-c3fa028da925.png)

**Comment by ThomasBurleson** [comment]
A Pull request would be welcomed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
