### ISSUE TITLE
In-place editing support

### ISSUE THREAD

**Issue by ersensen** [angular/material#6794]
Hi,

It would be very nice angular material to have its own in-place editing support.

Here is a great bundle of angular directives, but its theme is not compatible with angular material.
https://vitalets.github.io/angular-xeditable

Here is a discussion about angular material compatibility;
https://github.com/vitalets/angular-xeditable/issues/232

**Comment by ThomasBurleson** [comment]
Submit a PR with this feature and we can review and discuss integration into the current feature set.
