### ISSUE TITLE
$mdToast show on become bottom when in small screen

### ISSUE THREAD

**Issue by jazztong** [angular/material#6798]
When i test mdToast in large screen it is work expected, but when i test in smaller screen, it always show in bottom left position, it is a bug?

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by alexilyaev** [comment]
@ThomasBurleson Having the same issue, here's the CodePen:
http://codepen.io/alexilyaev/pen/ZWJxvQ?editors=1010

I'm working on a laptop with DevTools open, and I've set `.position('top right')` and couldn't understand why it's not working. Already an hour into it, until I found this.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by alexilyaev** [comment]
@ThomasBurleson Do we really need to open another issue for this?  
I've already made the CodePen on March.  
The bug is straightforward, the toast shows up at the bottom when we clearly set it to be at the top.

**Comment by stephengardner** [comment]
I believe the reasoning behind this is that the Material Design spec specifies toasts showing at the bottom on mobile.  I, however, think it's a bit of an oversight that this issue is not adjustable.

Here's the CSS that sets it to the bottom:
```css
@media (max-width: 959px)
md-toast {
     left: 0; 
     right: 0; 
     width: 100%; 
     max-width: 100%; 
     min-width: 0; 
     border-radius: 0; 
     bottom: 0; 
     padding: 0; 
```
