### ISSUE TITLE
md-chips with custom input as button

### ISSUE THREAD

**Issue by jpolo** [angular/material#6804]
I am currently struggling adding a button that opens a more complex dialog (instead of a custom input) in a md-chips : any code that is not an input is never put in the md-chip-input-container.

How can I achieve my goal ? 

If not possible, an improvement request to md-chip could be : 
_I would like md-chip to handle any ng-model based directive as an input_ (ie md-select, etc...)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
