### ISSUE TITLE
<md-menu> shrinks on iOS safari

### ISSUE THREAD

**Issue by echenley** [angular/material#6806]
If an `md-menu` is opened when iOS safari is in "minimal UI" mode (after scrolling down), it will shrink to a tiny size. Example:

![md-menu-bug](https://cloud.githubusercontent.com/assets/6344219/12490228/1cfefe72-c03a-11e5-86be-f494534da5c9.gif)

This doesn't affect the demo site since the behavior is prevented by restricting overflow scrolling to a `div`, rather than the `body` element.

**Comment by brad-sobie** [comment]
+1

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you review and test this?

**Comment by jpike88** [comment]
Just came across this one. +1

**Comment by jpike88** [comment]
This issue doesn't just occur in iOS safari, also happens in Chromium (Crosswalk). Might be related to touch devices

**Comment by jpike88** [comment]
And that pull request didn't work for me

**Comment by DevVersion** [comment]
Just wan't to pin this here.
- The fix works as expected in my case. 

@jpike88 said its not working, because he missed copying all lines. (See [here](https://cloud.githubusercontent.com/assets/4987015/13380632/03cdca38-de48-11e5-8623-92cb9e0d3d4d.png))

**Comment by nicolac18** [comment]
+1

**Comment by Lykathia** [comment]
So, is this fixed? What was the PR?

**Comment by herophuong** [comment]
My current workaround for this is just disabling the scaling animation when on Safari mobile:

````js
// Detect mobile safari
var ua = window.navigator.userAgent,
iOS = !!ua.match(/iPad/i) || !!ua.match(/iPhone/i),
webkit = !!ua.match(/WebKit/i),
iOSSafari = iOS && webkit && !ua.match(/CriOS/i);
if (iOSSafari) {
	$('body').addClass('safari-mobile');
}
````

````css
/* Disable transformation */
.safari-mobile .md-open-menu-container.md-active {
	transform: none !important;
}
````

**Comment by FlorianBurgevin** [comment]
any news to fix this ?

**Comment by FlorianBurgevin** [comment]
Not working for me. 
Any date for a fix?

**Comment by fierysolid** [comment]
Agreed, I'd like to see this get fixed as well.

**Comment by mattjennings** [comment]
The solution from @herophuong works well. It'd be nice to have an official fix soon, though.
