### ISSUE TITLE
Scrolling disabled when md-menu is active/open

### ISSUE THREAD

**Issue by TimonVS** [angular/material#6808]
md-menu disables scroll, I don't know if this is intended behaviour or not. This issue doesn't occur in the demo (https://material.angularjs.org/HEAD/demo/menu). If you however isolate md-menu in a CodePen for instance, the issue does appear. Demo: http://codepen.io/anon/pen/WrdYNN.
This issue also only appears in mobile browsers, I tested it in Safari on iOS 9.2.

**Comment by ThomasBurleson** [comment]
If the `md-menu` is open, scrolling is disabled in the page.

**Comment by TimonVS** [comment]
That makes no sense in my opinion, and is really terrible for the user experience. Maybe there should be a way to disable this?

**Comment by ivanff** [comment]
+

**Comment by ThomasBurleson** [comment]
@TimonVS - PRs are welcome to support page scroll and *open-menu-container* repositioning.

**Comment by suriyakumarcs** [comment]
if md-menu is opened outside page scroll didn't get closed.md-menu-item stay open in page scroll(only in IOS).Can you guys give some solutions..??
