### ISSUE TITLE
Closed-up md-select with a template does weird styling

### ISSUE THREAD

**Issue by craigsh** [angular/material#6811]
I've got an md-select where I want to do some fancy styling of the options. This works fine when the md-select is open but when closed up and an option is selected the styling is funny. 

See this Codepen:

http://codepen.io/craigsh/pen/MKQWqv

On version 1.0.3
Same behavior in various browsers (Chrome, IE, FF)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
