### ISSUE TITLE
input-container with md-icon in a label has broken layout

### ISSUE THREAD

**Issue by jarmesbarry** [angular/material#6814]
When you have an input container with a md-icon in the label rather than in the container body. The layout used to be fine. Now you have an md-has-icon class applied which forces the input to apply spacing for the icon which is not needed.
If the Input container only applied this class when the md-icon is not part of a label it'd fix the issue.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by jarmesbarry** [comment]
Please see below. I also added the fix I used. This used to be fine in 1.4.7 I believe.

http://codepen.io/jarmesbarry/pen/BjxaeX
