### ISSUE TITLE
No way to color web links?

### ISSUE THREAD

**Issue by cadilhac** [angular/material#6815]
In the specs (https://www.google.com/design/spec/style/color.html#color-ui-color-application) it says to use the accent color to colorize web links. But is it even possible with Angular Material? I didn't find anything in the doc to style a link (A tag) with the accent color (and by default links are really normal, i.e. ugly).

**Comment by ThomasBurleson** [comment]
You can use `<span class="md-accent">body text</span>` to add the accent color (note the anchor/link markup is missing).

> Per spec:  Only use the accent color for body text to accent a web link.

**Comment by cadilhac** [comment]
Thanks. And if this is to "accent a web link" I expect that this has to be applied to an A tag...

**Comment by cadilhac** [comment]
Hummm, this is what I feared. If I apply it to an anchor tag, it doesn't do anything. The spec says I can apply it to a web link, which to my minds means an A tag inside normal text (if you check the image they use in the spec, there is a colored word which is surely a link).

**Comment by cadilhac** [comment]
Btw, a simple span does not work either. This issue should be reopened !

**Comment by ThomasBurleson** [comment]
@EladBezalel - refs #6916 also.

**Comment by sryzycki** [comment]
+1

**Comment by EladBezalel** [comment]
![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsUklUeG9sRTdTOEk/style_color_uiapplication_accent3.png)

>Only use the accent color for body text to accent a web link.

**Comment by cadilhac** [comment]
@EladBezalel Yes, a web link. This is what I'm requesting.

**Comment by EladBezalel** [comment]
I know, just posted it to refer the spec :smile:

**Comment by cadilhac** [comment]
With 1.1 RC1, it seems that the link color is forced to the accent color. This has never been discussed here. I thought that, as proposed, I would have to use the md-accent class, so that I can also be free to use other colors for links...

**Comment by EladBezalel** [comment]
@cadilhac after reading further in the spec, and specially quoting: 
> Web links and buttons **can be** customized using your palette accent color.
I will remove the force a links color and make `md.accent` available.

**Comment by EladBezalel** [comment]
closed with 81b44a47cdf6c23f6811ebbb4ccaad17fd0b81af

**Comment by cadilhac** [comment]
Still non functional with 1.1.3. A simple anchor tag with md-accent class does nothing. Link has the default color given by the browser (purple).
