### ISSUE TITLE
Vertical fab-toolbar

### ISSUE THREAD

**Issue by brunofin** [angular/material#6816]
According to https://material.angularjs.org/latest/demo/fabToolbar this directive supports only `left` and `right` directions. I think it would be very useful to add support also to `up` and specially `down`.

Right now I'm using a hackish FAB Speed-dial (https://material.angularjs.org/latest/demo/fabSpeedDial) with a fading background on hover to achieve this effect, but it doesn't look as Material as it could with a vertical `fab-toolbar`.

**Comment by ThomasBurleson** [comment]
@topherfangio - thoughts?

**Comment by topherfangio** [comment]
I don't see anything in the spec regarding this, but a pretty quick/easy solution would be to simply add some CSS that does a 90˚ rotate transform on the fab toolbar, and a -90˚ rotation on the item (or a 270˚ rotation).

I'm actually planning to do this for the SpeedDial, so I'll take a look at adding this support for the toolbar as well.

**Comment by brunofin** [comment]
@topherfangio Sounds like a simple and elegant solution, I will give it a try meanwhile.
