### ISSUE TITLE
Bug report: Justify Content: start, should be flex-start;

### ISSUE THREAD

**Issue by darkoefremov** [angular/material#6818]
I was working with angular material and I needed the property layout-align="start start", I wasn't getting the expected result, so I checked the developer tools. There, I noticed that justify-content has a syntax issue, instead of "justify-content: flex-start;" it is "justify-content: start;" 

![478960](https://cloud.githubusercontent.com/assets/10568927/12525349/eac14f34-c163-11e5-8988-9195e4d969dd.png)

I am using the latest Angular Material version.

**Comment by DevVersion** [comment]
Should be fixed after #6827 is merged.

**Comment by ThomasBurleson** [comment]
@darkoefremov - the Layout Attribute selectors CSS file will be deprecated in the near future. It is highly recommended that you use the standard Layout API (with layout.scss).
