### ISSUE TITLE
Minor Broken Link from Angular Material Demo Site to Github

### ISSUE THREAD

**Issue by tonyawad88** [angular/material#6821]
Hey guys,

Just a minor one, the link from the Angular Material Site to Github is broken.
Current Broken Link: https://github.com/angular/material/tree/v1.0.3
Proper Link: https://github.com/angular/material/tree/release/1.0.3

You guys are doing great. I compared ionic with angular material recently, much better performance with angular material. Keep it up !

**Comment by DevVersion** [comment]
@tonyawad88 Yes, can see the issue. This is happening, because there is no `1.0.3` tag and branch created on the GitHub repository.

**Comment by ThomasBurleson** [comment]
Fixed.
