### ISSUE TITLE
Horizontal scrolling inside md-bottom-sheet breaks when applying -webkit-overflow-scrolling: touch.

### ISSUE THREAD

**Issue by utrolig** [angular/material#6824]
Hello everyone!

I've been trying to make a mobile nav, using md-bottom-sheet. Scrolling works okay on browser when resized, but not on my iOS device. When I add -webkit-overflow-scrolling: touch to the container element, the scroll stops working altogether on iOS devices. 

Scrolling works when it's not enabled, but then the scrolling feels janky and unnatural.

Any ideas?

http://codepen.io/utrolig/pen/ZQrawX

Codepen attached.

**Comment by EladBezalel** [comment]
@topherfangio do you have access to iOS device?

**Comment by topherfangio** [comment]
@EladBezalel Indeed; I can take a look at this one later today.

**Comment by EladBezalel** [comment]
@topherfangio thanks!
