### ISSUE TITLE
md-card shadow

### ISSUE THREAD

**Issue by eshansingh** [angular/material#6829]
There is currently no (documented) way to control the elevation of the `md-card` element.

**Comment by EladBezalel** [comment]
Use our [whiteframes](https://material.angularjs.org/latest/demo/whiteframe)

**Comment by atentis** [comment]
@EladBezalel Was shadow /elevation ever added since this was closed?

**Comment by zparduhn** [comment]
Any way to turn the box-shadow off on the md-card?

**Comment by EladBezalel** [comment]
add a class with `box-shadow: none`
