### ISSUE TITLE
textarea doesn't respond to mouse scroll / PageUp / PageDown

### ISSUE THREAD

**Issue by uriva** [angular/material#6830]

**Comment by EladBezalel** [comment]
Please provide a description and a demo.

**Comment by uriva** [comment]
Just put a lot of text in the textarea on the demo site, see that it scrolls using the arrow keys but not using mouse scroller or pageup/down.

**Comment by mckenzielong** [comment]
Did up a codepen here: http://codepen.io/mckenzielong/pen/GoxpOz -- this replicates it in at least Opera 34.

Added bonus of pop-in height issue (believe was tracked by another item?)

**Comment by DevVersion** [comment]
@mckenzielong Thanks for the perfect codepen! and yes I can see that issue.

PS: about the bonus pop-in height: Check http://codepen.io/DevVersion/pen/Goxpxe, (as already discussed in #5757, codepen contains these changes)

**Comment by EladBezalel** [comment]
From [Google Material Spec](https://www.google.com/design/spec/components/text-fields.html#text-fields-multi-line-text-field):
> Multi-line text fields automatically break to a new line for overflow text and **scroll vertically** when the cursor reaches the lower edge.

**Comment by EladBezalel** [comment]
@crisbeto is your PR solves this issue?

**Comment by crisbeto** [comment]
I'd say so. I also pushed something similar a little earlier that should've solved this issue as well. See #7553.

**Comment by DevVersion** [comment]
@crisbeto @EladBezalel Already solved by #7553

- http://codepen.io/DevVersion/pen/Goxpxe
