### ISSUE TITLE
md-ripple-container goes out of context area when applying in md-sidenav.

### ISSUE THREAD

**Issue by midhunadarvin** [angular/material#6832]
Hi,
I used the code pen in this link : http://codepen.io/kyleledbetter/pen/gbQOaV

However in link given above. The angular material version used is 0.8.3 . When i switched to version 1.0.1, In the sidenav, clicking on any on the menu items created a ripple effect across the whole sidenav instead of that particular menu item.

 When i inspected it i saw that that md-ripple-container div which was automatically created when applying the md-ink-ripple attribute to the md-item-content tag was taking up the height and width of the sidenav. For each md-item in md-list , the md-ripple-container was taking up the whole space of the sidenav, thereby creating a ripple effect across the whole sidenav when clicking on any of the menu items.

As a quick fix, i applied the <code>position:relative</code> styling to md-item-content . Since the md-ripple-container had <code>position:absolute</code> styling. Now the md-ripple-container fits inside md-item-content and ripple effect only  occurs across the clicked menu item.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

> Use `md-list-item`. See http://codepen.io/team/AngularMaterial/pen/mVxgbg?editors=1010
