### ISSUE TITLE
md-tabs-body + retaining classes

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6835]
am 1.0.2

md-tab-body compiles to ` div(md-tab-template='')` but doesnt maintin the classes applied pre-compile.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by 0101adm** [comment]
http://codepen.io/0101adm/pen/RrZdjR

the user group suggest that i place classes on the parent md-tabs then select down.
