### ISSUE TITLE
The child alignment demo doesn't update the layout-align properties

### ISSUE THREAD

**Issue by janvandenberg** [angular/material#6836]
Since a couple of versions back the layout-align attributes always say "center center". No matter what you select. It's a small issue but I guess its worth reporting. 

Really happy with this framework by the way. Keep up the good work!

**Comment by DevVersion** [comment]
That's a duplicate of #6319, fixed in #6567.

**Comment by janvandenberg** [comment]
You're right. I've searched the issues before creating this issue. Apparently not thoroughly enough.
