### ISSUE TITLE
md-select in md-menu 

### ISSUE THREAD

**Issue by cskiwi** [angular/material#6837]
So I'm trying to do a md-select in my md-menu.

but this gives me a lot of problems

1) the order of the items is wrong:
![image](https://cloud.githubusercontent.com/assets/847540/12548455/a2030aae-c356-11e5-9357-df4cfed8ce00.png)

2) when I change the `z-index` to 10 on the select via css, I can't open the `md-select` anymore

3) when I change the z-index in the devtools, it can open the select, but I can't select an options, unless the md-menu is closed first

4) the md-select isn't close when the md-menu is closed

md-menu code:

    <md-menu md-position-mode="target-right target" md-offset="30">
        <div aria-label="Open interactions menu" class="md-icon-button" ng-click="ctrl.openMenu($mdOpenMenu, $event)">
            <img ng-src="{{user.face}}" alt="{{user.username}}" class="small-face">
        </div>
        <md-menu-content flex layout="row" width="6" id="profile">
            <div flex layout="column">
                <div flex layout="row">
                    <div layout="row">
                        <img ng-src="{{user.face}}" alt="{{user.username}}" class="face">
                    </div>
                    <div layout="column">
                        <h3>{{user.username}}</h3>
                        <small>firstname.lastname@arcelormittal.com</small>
                        <md-select ng-model="ctrl.language" aria-label="Language">
                            <md-option ng-repeat="lang in ctrl.languages" ng-value="lang.code">
                                {{lang.lang}}
                            </md-option>
                        </md-select>
                    </div>
                </div>
                <md-divider inset></md-divider>
                <div flex layout="row">
                    <div flex>
                        <md-button>Button</md-button>
                    </div>
                    <div flex>
                        <div layout="row">
                            <div flex layout="row" layout-align="end center">
                                <md-button>Button</md-button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </md-menu-content>
    </md-menu>

**Comment by ThomasBurleson** [comment]
Not supported. What you really want is a Popup with a template; not a menu.
This work is in-progress.

**Comment by kylekrzeski** [comment]
+1
