### ISSUE TITLE
md-tabs issue with tabs number in firefox

### ISSUE THREAD

**Issue by NoHomey** [angular/material#6838]
I found that my last tab isn't showing in firefox. I also found a solution of pushing extra element only when tabs number is greater than 5 and tab's label length is greater than 15+ . Probably something with it's canvas wrapper.
Edit: The last tab is actually rendered but showed partially (if tab label length increases the tab is shown more and more if the length gets long enough it starts showing tabs like devices with small screens).

The same jade template is used in all 3 cases:
```
div(layout="column" layout-wrap)
  md-tabs(md-dynamic-height="true" md-selected="stateSwitcherCtrl.selected" md-center-tabs) 
    md-tab(ng-repeat="state in stateSwitcherCtrl.states" ng-click="stateSwitcherCtrl.switchState($index)")
      md-tab-label
        span(translate="{{'button-' + state}}")

```

Initial view:
![case1](https://cloud.githubusercontent.com/assets/8791438/12549239/900509ac-c364-11e5-885f-b3a4d71c974b.png)

With extra tab:

```
.... states forming logic ...
if ($window.navigator.userAgent.match /firefox/i)?
      controller.states.push ""
```

![case2](https://cloud.githubusercontent.com/assets/8791438/12549248/9cbc2284-c364-11e5-97d7-ddd35692fc83.png)

Extra tab only when tabs number is greater than 5:

```
.... states forming logic ...
if ($window.navigator.userAgent.match /firefox/i)? and controller.statesN > 5
      controller.states.push ""
```

![case3](https://cloud.githubusercontent.com/assets/8791438/12549251/a4e7d890-c364-11e5-8c27-f0ba2c6f5116.png)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
