### ISSUE TITLE
md-subheader is not consistent across devices and browsers

### ISSUE THREAD

**Issue by david-meza** [angular/material#6839]
I'm having an issue where `md-subheader` behaves differently in different browsers and overlaps other elements that go after it (see screenshots and Plnkr below). This happens whether it has the `md-no-sticky` class or not. If it does not have the `md-no-sticky` class and is fixed on the screen, there will be a moment where another bug occurs and the subheader just stops updating the `translate3D` attribute as you scroll down, making it stop being a fixed element.

* Plunker (MCVE): [See](https://plnkr.co/edit/0uIAufRwyHFxla28u4j1?p=preview)
* Site where I'm trying to use it: [See](https://park-jobs.surge.sh/#/)

It works as intended on **Google Chrome** as you can see in this screenshot:

![chrome-mac](https://cloud.githubusercontent.com/assets/11840636/12558303/ded98b64-c35c-11e5-9a74-6c401e520d2e.png)

But then when I run it on **Safari**, the subheader loses its margin or block display and overlaps other elements:

![safari-mac](https://cloud.githubusercontent.com/assets/11840636/12558302/ded857a8-c35c-11e5-8145-3794013637bc.png)

This also happens in my **iOS device** in both Safari and Chrome:

**Safari**:

![chrome-ios](https://cloud.githubusercontent.com/assets/11840636/12558305/dedbb8f8-c35c-11e5-8357-61dba0ad4a5a.PNG)

**Chrome**: 

![safari-ios](https://cloud.githubusercontent.com/assets/11840636/12558304/dedb23ca-c35c-11e5-9b53-d938078d79cc.PNG)

**BONUS**: If you ran the Plunker in Safari, you may have also noticed that the `md-scroll-shrink` directive does not shrink very smoothly, and if you scroll fast enough it just disappears without any animation.

**Comment by jaGarcia** [comment]
+1 we've just run into this in Safari.  md-subheader is inside a md-sidenav

**Comment by jaGarcia** [comment]
we worked around this issue by doing the solution from #580 which was to wrap our md-content inside another naked md-content :/
