### ISSUE TITLE
Determining Side Label Shows up on md-checkbox?

### ISSUE THREAD

**Issue by bobber205** [angular/material#6843]
Currently checkbox labels seem to only be positioned on the right side of a checkbox.
I usually like the prompt text to be on the left.

Is this possible to add? :)

**Comment by ThomasBurleson** [comment]
Sure use custom CSS for .md-label.

**Comment by andydion** [comment]
Just use css class "order" with a value of to tell flex to specify the order.
Here you go!!!!

md-switch .md-container{
  order : 2
}

**Comment by FDiskas** [comment]
:recycle: Another way is to add `dir="rtl"` attribute to parent element. This solution is better I think. You don't need to support this on feature updates.
```
<md-input-container dir="rtl">
   <md-checkbox>Import</md-checkbox>
</md-input-container>
```
