### ISSUE TITLE
Support usage in ngUpgrade with Angular2

### ISSUE THREAD

**Issue by joerideg** [angular/material#6847]
Hi guys,
First of all, awesome framework!
I know that there is an Angular2 version in the works but I also know that for now that Angular2 material is far from completion. So therefore I tried the following idea:
Having an Angular2 application with ngMaterial (Angular1) using ngUpgrade.
Basicly using the updateAdapter.upgradeNg1Component() to upgrade the ngMaterial directives in order to use them in my Angular2 component templates. 

Unfortunately some of the directives like for example mdButton do not match the requirements that ngUpgrade demands of Angular1 directives to be able to upgrade them. For example directives must always have a template (even if its empty) and can not use 'replace'. [All the requirements are listed here] (https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-component-directives). 

It would be very nice to be able to use ngMaterial Angular1 version as long as the Angular2 version is not finished yet.

**Comment by EladBezalel** [comment]
dup #6336

**Comment by joerideg** [comment]
Ah great!
