### ISSUE TITLE
flex-33 and flex-66 use calc within a flexbox

### ISSUE THREAD

**Issue by mmaguigan-dti** [angular/material#6849]
According to http://caniuse.com/#search=calc calc is not properly supported within a flex box on IE 11. 3d6077b446b7c7831d4ec0d95a3250e9e4b59be0 uses calc() in this fashion.

### before the update (working)
http://codepen.io/mmaguigan-dti/pen/bEvLjj
### after the update (not working)
http://codepen.io/mmaguigan-dti/pen/EPEQQa

**Comment by ThomasBurleson** [comment]
Fixed.
