### ISSUE TITLE
Automate deployment of latest versions to Google Hosted Libraries

### ISSUE THREAD

**Issue by jaGarcia** [angular/material#6850]
First, great work ya'll on this library. 

Google CDN is at 1.0.0 with latest version at 1.0.3.  I'm sure it's annoying to regularly update the versions hosted there but it looks like it's behind again.

Thanks!

**Comment by ThomasBurleson** [comment]
This is in-progress.

**Comment by jaGarcia** [comment]
It looks like the problem still exists with 1.0.6 and the latest RC-1 missing from Google Hosted Libraries:

https://developers.google.com/speed/libraries/#angular-material

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (427/400 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:58918 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNB-000arm-38
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:51 +0100
Date: Mon, 14 Mar 2016 15:49:54 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457995794;
	bh=flXonJnQ3GuPjcxc4Ukkvtg0DS16cmDIoPPTDi0rjl0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=NCTTas0wNOqe5JFfI93FdIN3T3EFvJX778lxTkpEA3mqDiIi9nM++tw+aK0GZswBL
	 FnsqrKUNWimNtF5uYEerA3+BzqwXhp4ArVsO4/fODfu5l2LJRG6/7OxwM7+F/6tGeV
	 KPqR/2Unkrz1NhXhru4XVDx34B5r8ORmR9IEGgO4=
