### ISSUE TITLE
md-datepicker: ngMessages always showing

### ISSUE THREAD

**Issue by marcomafessolli** [angular/material#6853]
Hi there. 

I'm trying to hide ngMessages on md-datepicker component until user touches the component/input. The problem is that md-datepicker shows the validation even when the user not touched the component.

When I try to add ng-show at ng-messages, the validation message not always shows after the user touched the component.

Here's a [codepen](http://codepen.io/anon/pen/WrzKZV).

It seems like when clicked at the input (not at calendar button or arrow down) the attribute $touched doesn't change.

**Comment by lucasgao** [comment]
Supported attributes are:

required: whether a required date is not set.
mindate: whether the selected date is before the minimum allowed date.
maxdate: whether the selected date is after the maximum allowed date.

**Comment by ThomasBurleson** [comment]
@jelbourn - can you investigate ?

**Comment by jelbourn** [comment]
@marcomafessolli does #6722 resolve your issue?

**Comment by marcomafessolli** [comment]
@jelbourn I tested a little and I think it's working now.
