### ISSUE TITLE
ng-messages in ng-repeat

### ISSUE THREAD

**Issue by confeccionar** [angular/material#6854]
each user will have 4 data , I want to differentiate each of these data to show the error of the data is required . I put name="date1[{{$index}}]" but ng-messages="data.date1[$index].$error" not detected, not like the name calling to work ng -messages if the amount of users may vary.

http://codepen.io/anon/pen/bEvxwp

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
