### ISSUE TITLE
ngMessages without md-auto-hide: Unexpected behaviour

### ISSUE THREAD

**Issue by tniezurawski** [angular/material#6859]
Hi guys,

I prepared test cases and **workaround** for this issue. You will find everything in this plunker: http://plnkr.co/edit/CppqUwm4X9lRGZCxxIYF

_Description from my plunker_:
It seems that when you do not use "md-auto-hide" with "ng-messages" something is going wrong.

Steps to reproduce (Last Name field):

1. Type "John"
2. Remove "John"
3. Tab out
4. Write fast some numbers (e.g. 123541)
5. Notice: there is no error msg for "ng-pattern"
6. You can remove these numbers and still - there is no error

-- used versions:
Angular: 1.4.9
Angular-Material: 1.0.3

It seems to work properly with angular-material 0.11.0.

**Comment by akoutmos** [comment]
I've been having the same issue. Looks like the correct error message is finding its way into the DOM, it's just missing the following style `style="opacity: 1; margin-top: 0px;"`

Once that style is added, it's showing up in the right place. That appears to be the only different between error messages showing up in the right place and not.

**Comment by mhamel06** [comment]
Not sure if this is related or should be a new issue but I have noticed the following behavior with both the workaround version and non workaround version:

1. Enter Text
![screen shot 2016-03-07 at 1 37 43 pm](https://cloud.githubusercontent.com/assets/473551/13579708/e1a732d4-e46c-11e5-90b5-8e2f627a55c3.png)

2. Select then clear text
![screen shot 2016-03-07 at 1 38 13 pm](https://cloud.githubusercontent.com/assets/473551/13579716/f03f19a6-e46c-11e5-9137-75672c15ac6c.png)
At this point the required error message is immediately displayed without an enter animation and it isn't reflected in the inspected DOM. 

3. The first required message disappears
![screen shot 2016-03-07 at 1 38 28 pm](https://cloud.githubusercontent.com/assets/473551/13579784/33e8abc2-e46d-11e5-8bfa-577b6fa6e417.png)

4. The second required message fades in with ngAnimate
![screen shot 2016-03-07 at 1 39 22 pm](https://cloud.githubusercontent.com/assets/473551/13579802/49dbbc76-e46d-11e5-90ca-7402107340ee.png)
![screen shot 2016-03-07 at 1 56 19 pm](https://cloud.githubusercontent.com/assets/473551/13579806/4cb10190-e46d-11e5-8058-9f35c9c786fc.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by tuhoojabotti** [comment]
Seems broken still on 1.1.0-rc5

**Comment by cakeinpanic** [comment]
+1 seems broken

**Comment by topherfangio** [comment]
@cakeinpanic This should be fixed in 1.1.0 final which was released last week. Have you updated to the latest release?

**Comment by mcianc** [comment]
I have the same problem too

**Comment by topherfangio** [comment]
@mcianc @cakeinpanic We just found another issue that may be related and which has a PR (#9468).

Can you please follow that thread and see if your issue is resolved when it gets merged?
