### ISSUE TITLE
[minor] Deep links to demo page in the docs don't show the demo list 

### ISSUE THREAD

**Issue by stefano-maggiolo** [angular/material#6861]
Very minor, but if you go to https://material.angularjs.org/latest/demo/dialog the "demo" section in the sidenav is selected but doesn't show the children (clicking once close it and clicking it again correctly shows the children).

**Comment by ThomasBurleson** [comment]
known issue. care to push a pull request fixing this?

**Comment by stefano-maggiolo** [comment]
Done.

**Comment by DevVersion** [comment]
@ThomasBurleson This should be closed. Right?

**Comment by ThomasBurleson** [comment]
Fixed.
