### ISSUE TITLE
mdSelect API Docs are missing md-on-open

### ISSUE THREAD

**Issue by Phr33d0m** [angular/material#6863]
Hi, ```md-on-open``` is used as an example in the ```Demo ==> Select``` but does not appear documented in the Directives section.

Regards.

**Comment by DevVersion** [comment]
Indeed, thank you.

**Comment by ThomasBurleson** [comment]
@DevVersion - please push a PR for this.

**Comment by DevVersion** [comment]
@ThomasBurleson - Already done - #6869
