### ISSUE TITLE
Fab Speed Dial is always open if no ng-controller="DemoCtrl as demo"

### ISSUE THREAD

**Issue by alonle** [angular/material#6865]
If I remove the line ng-controller="DemoCtrl as demo" and use in my site the ui-router state to set the controller, the Fab Speed Dial is always open!

Please see the demo example with hard coded md-open="false":
http://codepen.io/anon/pen/pgVoKj

Please help :-(

**Comment by DevVersion** [comment]
Hello @alonle,

This is because you didn't specify any animation class (like `md-fling`). So to fix your issue, you should add `class="md-fling"`. (See in codepen [here](http://codepen.io/DevVersion/pen/rxvaGJ)).

**Comment by alonle** [comment]
Thanks @DevVersion 
Changing ng-class="md-fling" to class="md-fling" is working!
