### ISSUE TITLE
Cannot read property '$submitted' of undefined

### ISSUE THREAD

**Issue by AliPoder** [angular/material#6866]
`TypeError: Cannot read property '$submitted' of undefined
    at b (angular-material.min.js:10)
    at Object.g (angular-material.min.js:10)
    at m.$digest (angular.js:16538)
    at m.$apply (angular.js:16810)
    at angular.js:18632
    at e (angular.js:5793)
    at angular.js:6070`

Is this a bug?

**Comment by AliPoder** [comment]
AngularJS v1.5.0-rc.1

Angular Material 1.0.3

**Comment by Iankill** [comment]
I've got the same on AngularJS 1.3.15 / Angular Material 1.0.1
For me it seems to be caused by the `required` validator on `input`

**Comment by chiccomask** [comment]
I'v got the same issue. Also for me seems the required validator, but only if there are at least two fields on the form. With Material 1.0.2 I don't see the error.

This codepen show my case: when you close the bottomSheet the error is shown in console

http://codepen.io/chiccomask/pen/XXqWmm

**Comment by alextreppass** [comment]
Related to this? https://github.com/angular/material/issues/6807

**Comment by Iankill** [comment]
Upgrading to latest master (1.0.3-master-0918596) did the trick

**Comment by chiccomask** [comment]
Looks exaclty the same issue.

**Comment by AliPoder** [comment]
Yeah, i updated angular material to master and seems it did the trick.

**Comment by DevVersion** [comment]
So if this issue was just a problem of 1.0.3, you should close that issue. :)
