### ISSUE TITLE
mdSelect's usage of md-progress-circular does not respect {start,end}Symbol

### ISSUE THREAD

**Issue by Phr33d0m** [angular/material#6868]
Hi, I'm using mdSelect in async mode and when ```md-progress-circular``` appears it's using the {{ }} notation for progressMode:
```html
<md-progress-circular md-mode="{{progressMode}}" ..........></md-progress-circular>
```

Where in my ```.config()``` I've said it to be:
```javascript
$interpolateProvider.startSymbol('[[').endSymbol(']]');
```

[Issue can be found here](https://github.com/angular/material/blob/de5237f1b7ad8185e1af143f467fae01edaa33e5/src/components/select/select.js#L145).

Regards.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
