### ISSUE TITLE
gridList: md-row-height is required but throws unhelpful error

### ISSUE THREAD

**Issue by epelc** [angular/material#6870]
`md-grid-list` should either handle not having `md-row-height` set or throw a more helpful error that it is required. The other grid list attributes give nice errors but `md-row-height` doesn't.

Here is a demo showing it
http://codepen.io/anon/pen/dGeoYP
Just add back `md-row-height="3:2"` to show it working besides this.

Currently you get the following
![image](https://cloud.githubusercontent.com/assets/5204642/12616724/8c33dd18-c4da-11e5-97ca-9a3243db5284.png)
![image](https://cloud.githubusercontent.com/assets/5204642/12616737/96e09e7c-c4da-11e5-928f-3728517f8174.png)

**Comment by ThomasBurleson** [comment]
Agreed - at least an information Exception.
