### ISSUE TITLE
md-grid-list: re-ordering of items

### ISSUE THREAD

**Issue by parky128** [angular/material#6873]
I have been looking at md-grid-list lately for a design requirement I am trying to solve.

I have a bunch of div's that are children to a container with layout row applied. Each of the child items have set widths\heights and have a toggle button to expand\collapse, which just doubles their sizes on expand and then return to original sizes on collapse.

What I'd like is for the child items to re-order to fill available space (provided that space is big enough) around other items that have been expanded.
![re-order-items](https://cloud.githubusercontent.com/assets/10373419/12618988/1c45dcb6-c50e-11e5-98ee-ccbb2511c7c6.png)

Right now the container element for my child items also has layout-wrap applied and so of course as items gets expanded, any children that don't fit horizontally just push down below the previous item.

I have come across md-grid-list but I am not so sure this will provide me with what I am after,  as it seems to be more suited for percentage based sizes - or have I got that wrong? 

I have seen http://masonry.desandro.com/ where if you resize the window on the homepage, that's the kind of behaviour I am looking for, although I would not want the height\widths to update dynamically.

Can this behaviour be achieved using Angular Material alone?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
