### ISSUE TITLE
$mdDialog position not updating when escapeToClose set to false

### ISSUE THREAD

**Issue by AliPoder** [angular/material#6876]
You can see it in action on plunkr: https://plnkr.co/edit/EC9CexUlBa41jrrpybdJ?p=preview

1. click on escapeToClose: true, resize window height and dialog stays centered and its height updating as you resize window. as expected.

2. click on escapeToClose: false, resize window height and dialog do not update its height and not staying centered.

Is this a bug or am i missing something?

**Comment by DevVersion** [comment]
Escape: True

![](https://i.gyazo.com/6e00b4682643a0bc52537a6a1485a7fd.gif)

Escape: False

![](https://i.gyazo.com/325df3e0545a8fe9dc1241e7ee68811c.gif)

Both works as expected

**Comment by AliPoder** [comment]
It's okay with width, but not with height:

escapeToClose: true

![true](http://g.recordit.co/If8fG77Cre.gif)

escapeToClose: false

![false](http://g.recordit.co/BTQbCwLLOd.gif)

btw @ThomasBurleson why do you keep closing issue without any word?

**Comment by DevVersion** [comment]
@ThomasBurleson Sorry for that - Can reproduce now - only with height
@AliPoder - My fault, I think Thomas thought, everything works, because of my GIF's

Working on a fix, found the problem.

**Comment by AliPoder** [comment]
Oh, okay! Thank you :}

**Comment by AliPoder** [comment]
Also, as you can see on first gif, when you increase the height of window, the height of dialog not growing. i think #6871 points the same.

**Comment by DevVersion** [comment]
@AliPoder @ThomasBurleson - Fix is done - See #6878. 
PS: I don't think it is related to #6871, because the issue was described by flexbox problems.

**Comment by AliPoder** [comment]
yeah, thanks it works! :+1:
