### ISSUE TITLE
mdSelect: ghost click when selecting option causing focus on underlying input

### ISSUE THREAD

**Issue by mambose** [angular/material#6879]
Annoying bug in iOS Safari but when you select one of the options in an md-select and there is an underlying text input directly under the option selected a ghost click is "trying" to give that input focus. I say "trying" because the input does not actually get focus but the keyboard is pulled up anyway. The focus remains with the md-select which does not require a keyboard.

I have managed to fix the problem by adding a timeout to the hideBackdrop function so the backdrop can absorb the ghost click.

```
if (options.backdrop) {
    $timeout(function() {
      options.backdrop.remove();
   },500);
}
```

Angular Material: 1.0.3
Angular: 1.4.9
Browser: iOS Safari 9.2

![screen shot 2016-01-27 at 1 08 20 pm](https://cloud.githubusercontent.com/assets/1072396/12623267/52e31016-c4f7-11e5-85d8-748cbaf0c17f.png)

![screen shot 2016-01-27 at 1 08 40 pm](https://cloud.githubusercontent.com/assets/1072396/12623294/69e63af4-c4f7-11e5-8246-6ab90d42ba17.png)

**Comment by ramirezd42** [comment]
I'm experiencing this as well with angular 1.5.0 on Safari 9.2, but not Chrome iOS 48.

I'm thinking this is related to #5696

**Comment by ramirezd42** [comment]
What was actually happening for me was that the md-select was being focused on, not the input below it. It seems to only be an issue when launching the page as a desktop shortcut in Safari. I opened up a separate issue in #7256

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
