### ISSUE TITLE
fabSpeedDial - 'FabController' name is not namespaced

### ISSUE THREAD

**Issue by zzebastien** [angular/material#6881]
The **FabController** is not namespaced with 'Md'.

In our application we already have a controller named 'FabController', and it overrides the Angular Material FabController.
File: [fabController.js](https://github.com/angular/material/blob/master/src/components/fabSpeedDial/fabController.js)

```js
angular.module('material.components.fabShared', ['material.core'])
    .controller('FabController', FabController);
```

So all the logic of FAB Speed Dial does not work in our application. Of course we can rename our controller, but still you should name it '**MdFabController**' instead.

**- Please rename FabControler to MdFabController**

Other controllers within Angular Material are namespaced with 'Md' so I assume you do not have a pre-build check to verify that all controllers are correctly namespaced.

Example of a controller with a correct name: [chipsController.js]
(https://github.com/angular/material/blob/master/src/components/chips/js/chipsController.js)

```js
angular
    .module('material.components.chips')
    .controller('MdChipsCtrl', MdChipsCtrl);
```

The **menuItemController** have the same problem: [menuItemController.js](https://github.com/angular/material/blob/eb1695a0d54f6794a08f04169ad8a390b92a1849/src/components/menuBar/js/menuItemController.js)

**'MenuItemController' should be 'MdMenuItemController'**

Angular Material: 1.0.3

Thanks !
Keep up the good work team :)

**Comment by Yann77** [comment]
+1

**Comment by LPCmedia** [comment]
+ 2
