### ISSUE TITLE
v1.0.3 is not available in npm

### ISSUE THREAD

**Issue by sirbarrence** [angular/material#6883]
When I `npm install angular-material` I get 1.0.2 which is not the latest tagged release. 1.0.3 was tagged 6 days ago, is listed in the Releases page on github, and is listed in the changelog as the latest release. 

If I try

    npm install angular-material@1.0.3 

I see "version not found: angular-material@1.0.3"

    npm install angular-material@1.0.2

works fine. 

1.0.2 is listed as the latest version on https://www.npmjs.com/package/angular-material

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you investigate ?

**Comment by ThomasBurleson** [comment]
Will Not fix since v1.0.4 is build today.
