### ISSUE TITLE
An secondary action md-button with an ng-href also performs the primary action on click.

### ISSUE THREAD

**Issue by TylerDixon** [angular/material#6886]
Example adapted from the "List Controls" codepen:
http://codepen.io/anon/pen/vLjXME

The `md-list-item` has a primary action to bring up a dialog, and there is an link in the form of an `md-button` with an `ng-href` as the `md-secondary` of the list item. Clicking this link performs both the primary and secondary action of the list item.

**Comment by ThomasBurleson** [comment]
Need identify way to stop propagation of secondary action events.

**Comment by DevVersion** [comment]
#6493 will also fix that issue, through the separated content, which has much positive effects (click events for child events will not propagate to the actual button; will allow multiple secondary elements to be clicked)
