### ISSUE TITLE
images size with flex

### ISSUE THREAD

**Issue by sky10p** [angular/material#6889]
Hi,

In the latest update to Google Chrome, the heigh of the images has changed.

In firefox and internet explorer the appearance is correct.

I don't know if it is a bug in the browsers or a problem of the library.

Thanks!!

`<div layout="column" layout-gt-md="row">

    <div class="flex-100 flex-gt-md-33">
        <md-card class="card-historic">
            <img src="img/calidad.jpg" class="md-card-image imagen" alt="image caption">
            <md-card-content>
                <h2>Calidad SAER</h2>
                <p>Carga de ficheros calidad,incidencias, seguimiento de calidad...</p>
            </md-card-content>
            <md-card-actions layout="row" layout-align="end center">
                <md-button  href="incidencias" >Entrar</md-button>    
            </md-card-actions>
        </md-card>
    </div>

    <div class="flex-100 flex-gt-md-33">
        <md-card class="card-historic">
            <img src="img/people.jpg" class="md-card-image imagen" alt="image caption">
            <md-card-content>
                <h2>People</h2>
                <p>Gestion de personas, dar de alta e información puesto, controlar ausencias...</p>
            </md-card-content> 
            <md-card-actions layout="row" layout-align="end center">
                <md-button href="personas">Entrar</md-button>    
            </md-card-actions>
        </md-card>
    </div>

    <div class="flex-100 flex-gt-md-33">
        <md-card class="card-historic">
            <img src="img/time-app.jpg" class="md-card-image imagen" alt="image caption">
            <md-card-content>
                <h2>Time App</h2>
                <p>Gestión de tiempos de los tramites gestionados, gestionar procesos, tiempos medios...</p>
            </md-card-content>
            <md-card-actions layout="row" layout-align="end center">
                <md-button href="timeapp">Entrar</md-button>    
            </md-card-actions>
        </md-card>
    </div>

</div>`

**Comment by ThomasBurleson** [comment]
Please provide a CodePen, JSBin, Plunkr demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd

**Comment by Frank3K** [comment]
@sky10p: possible related to #6841?

**Comment by Kelvin-Chu** [comment]
Had the same issue, the workaround for #6841 fixed it for me.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
