### ISSUE TITLE
Question: Angular 2 components

### ISSUE THREAD

**Issue by ganySA** [angular/material#6890]
Hi

I have looked around on the web a bit for angular2 material. I am trying to understand where the angular material 2 site is.... and what the view is given that Angular 2 is rapidly moving towards a 1.0...

Thanks

**Comment by DevVersion** [comment]
The current Material Design for Angular 2 is currently in progress. The official home is located [here - angular/material2](https://github.com/angular/material2).

**Comment by ganySA** [comment]
do you know what the plans are around getting it up and running?

**Comment by DevVersion** [comment]
At the moment, the `material2` team is working on the build cycle and on a few components. So it is not recommend to use that yet, It will take a little bit of time. I already created a `switch` component with drag functionality, but it is too early (completely understand that decision) to create huge PR's.. so this won't be merged.

**Comment by ThomasBurleson** [comment]
Please file Angular Material 2 **questions** at https://github.com/angular/material2/issues.
