### ISSUE TITLE
mdDialog and form: Closing with $invalid form cause error thrown into dev console

### ISSUE THREAD

**Issue by tniezurawski** [angular/material#6892]
Hey guys,

I've prepared plunker with the situation:
http://plnkr.co/edit/NIoepepoRn4ifC6yHhpp?p=preview

To be more specific md-input or md-input-container is throwing that error. Basically every inside the form.

_Description from my plunker_:
Look at dev console. If the form inside the dialog is invalid you will notice an error thrown out in dev console.

Interesting cases:

- Open dialog, click "cancel" - you will notice an error in dev console
- Open dialog, type "First Name", click "cancel" - no error (because form is valid)
- Open dialog, type "First Name", click "submit" - no error (because form is valid and submitted)

Thanks to stacktrace it should be easy to find the reason of this bug.

-- used versions:
Angular: 1.4.9
Angular-Material: 1.0.3

**Comment by DevVersion** [comment]
Already fixed in #6809 on `master`. The error is fixed in `1.0.4` / `master`

**Comment by tniezurawski** [comment]
I somehow failed in finding it ;)

Thanks!
