### ISSUE TITLE
mdSelect: Need spacing for ngMessages

### ISSUE THREAD

**Issue by vbanuelos** [angular/material#6903]
Currently the error message pushes mdSelect up a few pixels.

Quick fix I found, was to add the error spacer (a la mdInput) to the select directive postLink:

```js
containerCtrl.input = element;

// Add an error spacer div after our input to provide space for the char counter and any ng-messages
var errorsSpacer = angular.element('<div class="md-errors-spacer">');
element.after(errorsSpacer);

if (!containerCtrl.label) {
    $mdAria.expect(element, 'aria-label', element.attr('placeholder'));
}
```

**Comment by ThomasBurleson** [comment]
Closing without associated CodePen that demostrates the issue.

**Comment by nikclayton** [comment]
https://github.com/angular/material/pull/8209 is relevant to this issue (and includes CodePen examples).
