### ISSUE TITLE
mdDialog, mdToast, mdMenu and other components conflict with each other

### ISSUE THREAD

**Issue by teszymanski** [angular/material#6905]
As of a recent version (1.0.2 or 1.0.3) I've noticed that it's no longer safe to use multiple components at the same time. I believe the problems are caused when two components that spawn a scroll mask, especially ones that play an animation, are both called at nearly the same time and interfere with each other.

A simple reproduction that causes visual errors when the user has scrolled down is:

``` js
$timeout(function() {
  $mdToast.show($mdToast.simple().textContent('Hello!'));
});
$mdDialog.show($mdDialog.alert().ok('Alert'));
```

This reproduction only causes temporary visual corruption, and only while the toast is animating in and out, while the page remains usable. I have a more complex page that gets locked into an unusable state, where a dialog spawns above the screen and even calling $mdDialog.cancel() from the console won't dismiss the dialog.

**Comment by EladBezalel** [comment]
@teszymanski can you provide a codepen?
I've [tried](http://codepen.io/EladBezalel/pen/NxzPjq) and it seems to work well.

**Comment by teszymanski** [comment]
http://codepen.io/anon/pen/qbyaGy

I've added a background and some padding to make it obviuous. If you scroll down before clicking the button it cause the visual corruption I expect.

I'll try putting together a codepen that recreates the problem my non-public site is having where it gets stuck in an unusable state. My site has a fair number of moving parts so I'm trying to boil it down to just what is necessary.

**Comment by EladBezalel** [comment]
When trying this specific code in our docs it seems to work, the white background that you see is the html and body not filling the codepen full width and height therefore it goes crazy.

maybe plunkr will do better?

**Comment by teszymanski** [comment]
If I disable the timeout in my above codepen I'm able to scroll around while the dialog is present, which shouldn't be possible. There is some kind of conflict even if I can't replicate my exact problem. Turns out the timeout was unnecessary.

http://codepen.io/anon/pen/LGBWPL


The problem that actually makes my page unusable, without a workaround, is that the two components will conflict with each other with the outcome being that the body is given the overflow:hidden style and it's never removed.

This only happens when two or more components interfere with each other, and didn't happen at all before a recent version of angular material.


It looks like the body styling is being applied in $mdUtil.disableScrollAround.disableBodyScroll when it's called twice before restoreBodyScroll is ever called. When the styling gets restored as the toast finishes animating it restores the values that the dialog set.

**Comment by EladBezalel** [comment]
@teszymanski in your codepen i can't see any `overflow: hidden` that's never removed,
`md-dialog` is using `$mdUtil.disableScrollAround` but `md-toast` is not, also toast is applying classes the the div container and the dialog to the body..

**Comment by teszymanski** [comment]
Thank you for pointing out that the `md-toast` was using the div as its parent but the `md-dialog` was using the body.

http://codepen.io/anon/pen/ZQmwde

This reproduces the issue I'm seeing, as long as you're required to scroll down to click the button.

**Comment by EladBezalel** [comment]
I'm sorry, but i couldn't figure what's wrong in your example,
You're using `top` to create a fake scroll but it doesn't actively make the body get the size of the scroll container, because of using `top`.

Therefor the `md-toast` is not being aligned to the left bottom of the viewport but aligned to the left bottom of the body element, if you would inspect the body element you would see that clearly.

**Comment by teszymanski** [comment]
Usage of `top` has nothing to do with it, see http://codepen.io/anon/pen/ZQVJQM which is using a regular div as a spacer without using any positioning. Angular-material sets the html and body height to 100% of the viewport's height and breaks if that styling is overridden.

Likewise the position of the toast is immaterial and unimportant to this bug. I have given the toast a fixed position with some CSS, it makes no difference.

If you inspect the body of the iframed content you'll see that it has the styling `overflow:hidden` applied. This styling is not applied if you use `md-toast` or `md-dialog` on their own. Each one on its own will work as intended, but combined they have unexpected results.

Inspecting the DOM will also show that the dialog is present but is partially or completely out of the viewport because of the `overflow:hidden` styling, which is never removed. If you manually remove that styling from the body the dialog will be visible as expected.

Compare the behavior of these three pens:
http://codepen.io/anon/pen/xZmLdv
http://codepen.io/anon/pen/EPGvmz
http://codepen.io/anon/pen/ZQVJQM

**Comment by EladBezalel** [comment]
@teszymanski I can totally see what you're saying.
I will find the commit that introduced this problem and will let you know, more than that, I've come up with a solution for toast positioned as fixed, we will apply fixed style only if it's appended to body.

How ever, here's a [workaround](http://codepen.io/EladBezalel/pen/RrvoYM) for you, hope it's helpful

**Comment by EladBezalel** [comment]
Narrowed down to this commmit d641433f91499fbc7cba68ce7c897efd751f8113 who created this bug/issue

**Comment by topherfangio** [comment]
So, this is definitely a by-product of my code addition in the commit above, however, it looks like it's actually the following line that is causing issues:

https://github.com/angular/material/blob/master/src/core/util/util.js#L221

For some reason, if you open the toast and the dialog in the same digest loop, the `body.clientWidth` is in fact less than the `clientWidth` and it's setting the `overflow: hidden` property. By opening your dialog within a `$timeout()` (even with no delay), it appears to fix the issue.

I need to touch base with some of the rest of the team on how to best approach a fix.

**Comment by teszymanski** [comment]
I don't actually think it's the `clientWidth` logic there. It looks like https://github.com/angular/material/blob/master/src/core/util/util.js#L205 is taking a snapshot of the body's style, so when the mdToast sets `overflow:hidden` it gets saved and restored when `restoreScroll()` is called.

**Comment by topherfangio** [comment]
@teszymanski If you comment out line 221, the demo works as expected. This obviously breaks other things though, so it is not a good solution.

**Comment by EladBezalel** [comment]
@topherfangio any idea how can we proceed?

**Comment by topherfangio** [comment]
@EladBezalel Honestly, we may need to rethink how we handle the toast's positioning and try to remove some of the "automatic" changes we make to the parent container (like setting it's position to relative and the overflow to hidden).

**Comment by teszymanski** [comment]
I just ran into this issue when several md-toasts are spawned in a short period of time. It does not require a dialog or any other non-toast component.

The exact problem was the `md-toast-animating` class remaining on the body element even after all the toasts were finished.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by iMomen** [comment]
I have the same issue with sidenav, you can overcome it dirty by adding 
`md-backdrop {
    position: fixed !important;
}
md-sidenav {
    position: fixed !important;
}`

**Comment by sergiy-talashko** [comment]
Has a problem with Dialog and Toast message displaying in a same time. 
Fixed by:

```
body.md-dialog-is-showing.md-toast-animation{
   max-height: inherit;
}
```

**Comment by colmben** [comment]
On 1.1.1, I am seeing issues with a simple mdToast leaving position:relative on the app body which causes subsequent mdDialog 's to screw up. The mdToast code explicitly checks for existing an existing position style before applying the position:relative in the first place, so something like this is solving it for me :

div[ng-app] {
  position: static !important;
}
