### ISSUE TITLE
md-sidenav scrolls source page on open

### ISSUE THREAD

**Issue by rudijs** [angular/material#6909]
Hi,

When I rig up an md-sidenav and click to open it's scrolls the source (underlying) page.

I have a codepen example that shows this: http://codepen.io/rudijs/pen/bEMaje

In the codepen example, if you scroll to the bottom, click open left menu - you'll see the page scroll to top when the nav opens.

When the nav closes it scrolls back to bottom.

My my development application code (not the codepen example) it scrolls to the top and stay at the top when the sidenav closes.

Tested with Chrome, FF and Android Chrome.

Seems like unwanted behaviour, earlier versions I played with didn't do this scrolling on side nav open/close.

The code pen example uses code from the ngmaterial site along with some lorem ipsum text to enable page scroll.

Are you seeing the same as I am? Is this a bug or expected current behavior?

Thanks.

**Comment by DevVersion** [comment]
Hello,

That's a duplicate of #5850 and should be fixed in #5887

**Comment by rudijs** [comment]
@DevVersion Ah .. Thanks Paul. I did do a search in the issues prior to posting this issue, my bad I over looked it.

**Comment by asureshhegde** [comment]
I'm still facing the same issue nothing working for me 
Can I know the fix for this? or do I need to make any changes?
Thank you

**Comment by travelerspb** [comment]
@rudijs related fix https://github.com/angular/material/pull/5887 is closed (not merged), so the bug is still exists. Probably it worth to re-open this ticket?

**Comment by fabiannagel** [comment]
Any news on this issue?

**Comment by tzar** [comment]
It depends on how you've structured your page - [here's a bodged example to make it work properly by having md-sidenav higher up in the DOM](https://codepen.io/anon/pen/awmxKr)
