### ISSUE TITLE
interim stack order (multiple dialog)

### ISSUE THREAD

**Issue by GongT** [angular/material#6912]
version @ 1.0.4 & master

why `hide` and `cancel` has different order?

That cause sub-dialog `hide` self to parent, but `cancel` from parent to self.

[here is the plunker](http://embed.plnkr.co/MKbhI3dvCxR5YjoQLvrx/)

[line 296](https://github.com/angular/material/blob/6a564508567cf1e352495bdf803f6db94334c601/src/core/services/interimElement/interimElement.js#L296)
```javascript
  function show(options) {
    ....
    stack.push(interimElement);
    ....
```

[line 363](https://github.com/angular/material/blob/6a564508567cf1e352495bdf803f6db94334c601/src/core/services/interimElement/interimElement.js#L363)
```javascript
  function cancel(reason, options) {
    var interim = stack.shift();
    ....
```

[line 335](https://github.com/angular/material/blob/6a564508567cf1e352495bdf803f6db94334c601/src/core/services/interimElement/interimElement.js#L335)
```javascript
  function hide(reason, options) {
    ....
    var interim = stack.pop();
    ....
```

**Comment by DevVersion** [comment]
Hello,

This is a side-effect of #6684, which fixes that issue too. Just give it a try :)
So this issue is fixed in #6684

**Comment by GongT** [comment]
not exactly

**Comment by DevVersion** [comment]
Did you even took a look? The stack order using the new queue count works perfectly.

**Comment by GongT** [comment]
already commented under your issue

**Comment by DevVersion** [comment]
Using the changes from the PR: 

![](https://i.gyazo.com/411c7218bf21b7bda34376cf0ac6ca18.gif)

**Hide works as expected.**

![](https://i.gyazo.com/ebff10b35c53880699933dc1cb6826a8.gif)

**Cancel works as expected.**

So what isn't *exactly* working? Everything works as desired in the plunker?

**Comment by GongT** [comment]
the dialog 4 is the last shown dialog (if modal , you can only click button on dialog 4)
if you click hide & cancel from 4 to 1 ,you will see different

**Comment by DevVersion** [comment]
Alright, so this isn't related to my PR..

**Comment by GongT** [comment]
yeah.. but your logic is right , so really can fix my issue :P
