### ISSUE TITLE
md-input-container: input with icon and ng-if is broken (1.0.4)

### ISSUE THREAD

**Issue by Raidri** [angular/material#6913]
Hi,

if i use a md-input-container with an icon and i have a ng-if on my input, the icon will not shown to the left. it overlaps the input field.

that happens since Version 1.0.4 with 1.0.3 everything was ok.

here is an example:
http://codepen.io/Raidri/pen/EPLBMW

**Comment by xplodwild** [comment]
Same happens here. Icon is broken (inside the input area) if:
- <md-icon> is before <label> in <md-input-container>
- <md-icon> with <textarea> in <md-input-container>
- <md-icon> with <md-select> in <md-input-container>

Works fine on 1.0.3, complete mess on 1.0.4.

**Comment by gkohen** [comment]
+1

**Comment by BBeauchemin** [comment]
+1

**Comment by ThomasBurleson** [comment]
The icons are not show 

```html
<md-icon>&#xE88F;</md-icon>
```

> Do you have the css url for these icons?

**Comment by EladBezalel** [comment]
Also i can't find any `ng-if` in the codepen

**Comment by Raidri** [comment]
Hi, i don't know why but i was gone. I have added it again.
And that is the icon : https://design.google.com/icons/#ic_info_outline

**Comment by EladBezalel** [comment]
The ng-if should be on the input-container not the input element..

http://codepen.io/EladBezalel/pen/OMBNdy
