### ISSUE TITLE
md-dialog height width

### ISSUE THREAD

**Issue by dhruvdutt** [angular/material#6915]
I have a dialog which navigate through different stages of a form using `ng-show`, `ng-hide` (no `md-tabs`) but I cannot set custom static height and width in `md-dialog` to maintain the UX view (height, width of the dialog) consistent across different stages.
Tried applying min, max-height but eventually ended up breaking `md-actions` which I wanted to stay on the bottom.

**Comment by 0101adm** [comment]
i remember applying it to the md-dialog tag and it working.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by dhruvdutt** [comment]
Conventional workout is to make a parent column and adjust it's width statically!
