### ISSUE TITLE
angular-material tags and SEO

### ISSUE THREAD

**Issue by jekka-ua** [angular/material#6917]
Hi

We are going to use angular-material on not-heavy angularjs web-project (without ng-routes, ajax etc) to adjust html-templates. But I'm not sure about angular-material tags "compatibility" with Googlebot and SEO. 

Is it possible (in sense of SEO) to use md- tags or is it better to use only css-classes of angular-material ?

**Comment by AliPoder** [comment]
Material Design tags are not different than standard angularjs tags, well aka, directives. Googlebot does not care about directives, instead all it cares is the meta tags and the html tags.

All angular material project does is that it transforms directives into html blocks which styled with css and javascript.

So if you're using, for example, phantomjs renderer for your angularjs project, angular and angular material directives will be able to analyzed by googlebot.

The only bad thing about directives, well as far as i've faced with, is the ngClick directive. Googlebot can not follow links inside ngClick.

To solve this issue, you can create a directive that appends a hidden `<a>` html tag after the html block that you've used ngClick.
