### ISSUE TITLE
mdAutocomplete: Close button doesn't clear the typed text on IPad

### ISSUE THREAD

**Issue by chughk1** [angular/material#6918]
The close button on mdAutocomplete stops working after a user taps on the close button before closing the keyboard on the IPad

Steps to produce the bug:

1) Type some text in autocomplete with a custom template(Results will be shown)
2) Tap on the close button a couple of times with the keyboard on the IPad showing.
3) Close the keyboard.
4) Tap on the close button (won't clear the text)

**See this in action here**: https://jsfiddle.net/NathanFriend/Lctcxjqr/
The examples at https://material.angularjs.org/latest/demo/autocomplete don't exhibit this issue.

Some additional information:

Angular Material Version: 1.0.3
Angular Version: 1.4.9
Browser and OS: Chrome 47.0.2526.111 on Windows 8.1

**Comment by chughk1** [comment]
Has anybody been able to fix this issue?

**Comment by topherfangio** [comment]
Just tested; looks like it is still an issue in 1.1.0-RC4, so I don't think it has been fixed yet.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
