### ISSUE TITLE
Bottom Sheet does not close with esc

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#6924]
I have seen in the docs example that this component do closes.. but when you click outside the sheet.. keeping the option to disable closing upon clicking outside, and then press `esc`. the sheet does not close.. only way to close by then is by dragging it down

it does not even close when i click in some part of the sheet and then press `esc`

**Comment by DevVersion** [comment]
@Nosthertus I'm not sure if I correctly understand you issue. You mean [this demo?](https://material.angularjs.org/latest/demo/bottomSheet). Here you said that closing through ESC / or clicking on the Backdrop isn't working. This is by intention if you open the `Show as Grid` bottom sheet. The `Show as List` bottom-sheet will support `ESC` and clicking on the backdrop.

**Comment by Nosthertus** [comment]
sorry for not linking to demo part.. and the bottom sheet showing as grid, which is the one that has the property to close only on esc or dragging down.. does not close if you click outside (this does not mean i want to close through clicking outside) and then press esc. the button binding is lost when that happens

**Comment by ThomasBurleson** [comment]
will not fix.
