### ISSUE TITLE
Bottom Sheet targetEvent not in docs explanation

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#6925]
The explanation of usage for this property in the service `$mdBottomSheet` is not listed in options property.. So i don't know what is event target working for.

https://material.angularjs.org/latest/api/service/$mdBottomSheet

**Comment by DevVersion** [comment]
That's because here is no `targetEvent` property in the $mdBottomSheet interim element.

**Comment by Nosthertus** [comment]
but why is it used in the demo?.. check on the demo code

**Comment by DevVersion** [comment]
Yes, can see it! - Just took a look at the source code of the bottom-sheet interim element, there is no use of a `targetEvent` property, so I think this is like a unnecessary option in the $bottomSheet.

**Comment by Nosthertus** [comment]
alright.. it's not necessary. i was just asking because sometimes i find docs uncompleted and i was curious about it... thanks

**Comment by DevVersion** [comment]
No please keep it open :smile: , That was a good catch from you, I think we should remove that from the demo.

**Comment by Nosthertus** [comment]
no problem

**Comment by ThomasBurleson** [comment]
@DevVersion - PR please?

**Comment by DevVersion** [comment]
I'd love to! See #6932
