### ISSUE TITLE
md-autocomplete: problems on elements with position fixed 

### ISSUE THREAD

**Issue by nicolac18** [angular/material#6929]
Hi!
I'm using md-autocomplete but I'm having some problems with other elements on the page that have style "position: fixed" (like header and a left sidebar).
When I'm scroll down on the page and write on input, the autocomplete list does a strange thing: fixed elements appears like losing fixed attributes.

Thanks!

Original:
![before](https://cloud.githubusercontent.com/assets/11179552/12696229/d7a0ea02-c764-11e5-90d0-bb38f86b057e.png)

When I writing on autocomplete. The profile bar doesn't appear because goes on top.
![after](https://cloud.githubusercontent.com/assets/11179552/12696228/d79dd722-c764-11e5-8a4e-554962968c5d.png)

**Comment by evanjmg** [comment]
+1

**Comment by topherfangio** [comment]
Can you please provide a Codepen which demonstrates the issue?

**Comment by ThomasBurleson** [comment]
Closing - see [Angular Material Deprecation Policy](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk)

**Comment by mikila85** [comment]
+1
