### ISSUE TITLE
build:  CodePen demos broken with GitCDN links

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#6930]
Our codepens injecting `{{newVersion}}` to the cdn links:
[https://cdn.gitcdn.xyz/cdn/angular/bower-material/v{{newVersion}}/angular-material.js](https://cdn.gitcdn.xyz/cdn/angular/bower-material/v{{newVersion}}/angular-material.js)

Besides that, even older versions is not available:
[https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0/angular-material.js](https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0/angular-material.js)

**Comment by ThomasBurleson** [comment]
![screen shot 2016-01-30 at 10 09 10 am](https://cloud.githubusercontent.com/assets/210413/12696833/cd744748-c739-11e5-9cf9-3c6d7ade2317.png)

**Comment by ThomasBurleson** [comment]
Notice that Latest at http://material.angularjs.org has a different issue. The links are not interpolating properly:

`https://cdn.gitcdn.xyz/cdn/angular/bower-material/v{{newVersion}}/angular-material.js`

Is this a release/build issue?

![screen shot 2016-01-30 at 10 23 25 am](https://cloud.githubusercontent.com/assets/210413/12696909/88f44ec2-c73b-11e5-87a3-027ad3cad967.png)

**Comment by EladBezalel** [comment]
It seems that gitcdn.xyz is down, read more in schme16/gitcdn.xyz#4

**Comment by DevVersion** [comment]
I suggest using [rawgit](http://rawgit.com/). Thoughts?
