### ISSUE TITLE
Professionnal services ?

### ISSUE THREAD

**Issue by sam2x** [angular/material#6931]
Hey, i know this may be the wrong place to ask, but is the team providing any professionnal service  ?
I have started to use angular-material, but i want to speed up the process, 
is there any talented developper willing to work ? Seems hard to find one.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial).

> Best of success with your Angular Material efforts.
