### ISSUE TITLE
md-chip should be case insensitive

### ISSUE THREAD

**Issue by LisaTatum** [angular/material#6933]
When I use the default chip template: https://material.angularjs.org/latest/demo/chips

and create a chip "orange" that already exists "Orange" that should not be possible.

I want to create entities where the name is unique doesn`t matter wether is upper/lowercase.

**Comment by DevVersion** [comment]
That's a duplicate of #5782.

**Comment by DevVersion** [comment]
Thanks, can reproduce. I try to take a look.

**Comment by gouravsood** [comment]
I am also facing the issue. 
Just trying to understand, why this enhancement has been deprecated? This is valid scenario to pick unique values in the chips.
