### ISSUE TITLE
flex not wok properly with layout overridden by another breakpoint

### ISSUE THREAD

**Issue by konopiux** [angular/material#6934]
```html
<div layout="row" 
        layout-gt-sm="row" 
        layout-sm="column" 
        layout-xs="column" 
        layout-align="center">
    <div id="content" flex="30" layout="column">
    </div>
    <div flex="50" id="suggestor" layout="colum">
    </div>
</div>
```

Using such code of layouts,  `div content + suggestor` grabs 80% width of big screen. Everything ok.
But according to documentation, first line can be written shorter: 

```html
<div layout="column" layout-gt-sm="row" layout-align="center">
```

and then `div content + suggestor` becomes 100% width of screen bigger than 960px.

Do not understand why?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
