### ISSUE TITLE
Datepicker demo: ngMessage color is slightly off-spec

### ISSUE THREAD

**Issue by MariskaS** [angular/material#6941]
Will the validation have been fixed datepicker ?
(color validation and transition for error)

![input](https://cloud.githubusercontent.com/assets/5942101/12701846/72041bdc-c828-11e5-9e7c-c6162ecc3ce0.png)

**Comment by DevVersion** [comment]
The color of the ngMessage is set manually in the demo. See [here](https://github.com/angular/material/blob/c2e17ad6ce0a0f16b2169986adb278083ad22eb8/src/components/datepicker/demoBasicUsage/style.css#L8-L8). @jelbourn Is that by intention?

**Comment by jelbourn** [comment]
I just made it some arbitrary red.

**Comment by MariskaS** [comment]
Thanks for the answer. More interested in the appearance of the animation block error. currently the field is different and has to build upon css

**Comment by DevVersion** [comment]
@MariskaS Can you provide a codepen from your `aniamtion block` version? Currently the datepicker doesn't support its own ngMessages animations.

**Comment by MariskaS** [comment]
/***
 * Exammple c-datepicker:
 *  <div layout-gt-sm="row" class="c-datepicker_container">
 *      <label class="c-datepicker_container__label">Available</label>
 *      <div class="c-datepicker_container__date">
 *          <md-datepicker name="availableFrom" ng-model="vm.houseType.availableFrom" ng-required="true"></md-datepicker>
 *          <div class="c-validation-messages" ng-messages="editForm.availableFrom.$error">
 *              <div ng-message="valid">Please enter valid date</div>
 *          </div>
 *      </div>
 *      <div hide-xs="" hide-sm="" class="c-datepicker_container__icon">
 *          <label>&nbsp;&mdash;&nbsp;</label>
 *      </div>
 *      <div class="c-datepicker_container__date">
 *          <md-datepicker name="availableTo" ng-model="vm.houseType.availableTo"></md-datepicker>
 *          <div class="c-validation-messages" ng-messages="editForm.availableTo.$error">
 *              <div ng-message="valid">Please enter valid date</div>
 *          </div>
 *      </div>
 *      <div class="c-datepicker_container__icon">
 *          <md-icon md-svg-icon="icon-warning" ng-show="vm.isExpired()">
 *              <md-tooltip>House type is expired</md-tooltip>
 *          </md-icon>
 *      </div>
 *  </div>
 */

Less
`.c-datepicker_container {
    display: block;
    position: relative;
    padding: 2px;
    margin: 18px 0;

    &__label {
        -webkit-font-smoothing: antialiased;
        padding: 0 0 2px 3px;
        -webkit-transform-origin: left top;
        transform-origin: left top;
        position: absolute;
        bottom: 100%;
        left: 0;
        right: auto;
        -webkit-transform: translate3d(0, 6px, 0) scale(0.75);
        transform: translate3d(0, 6px, 0) scale(0.75);
    }

    &__icon,
    &__date {
        float: left;

        &:not(:last-child) {
            margin-right: 20px;
        }
    }

    &__icon {
        padding-top: 10px;
        margin-right: 5px !important;
    }

    &__date {
        max-width: 204px;
    }

    .clearFix();

    &:after {
        min-height: 24px;
    }

    .md-datepicker-input-container {
        margin-left: 0;
        width: 160px;
    }
}

//** Md Datepicker (validation)
.c-datepicker_container .c-validation-messages {
    padding-left: 40px;
    overflow: hidden;
    word-wrap: break-word;

    ng-message,
    [ng-message] {
        .transition(all 0.3s);
    }

    &.ng-active {
        ng-message,
        [ng-message] {
            opacity: 1 !important;
            margin-top: 0 !important;
        }
    }

    &.ng-inactive {
        ng-message,
        [ng-message] {
            opacity: 0 !important;
            margin-top: -100px !important;
        }
    }
}`

**Comment by MariskaS** [comment]
# Exammple c-datepicker
```
  <div layout-gt-sm="row" class="c-datepicker_container">
      <label class="c-datepicker_container__label">Available</label>
      <div class="c-datepicker_container__date">
          <md-datepicker name="availableFrom" ng-model="vm.houseType.availableFrom" ng-required="true"></md-datepicker>
          <div class="c-validation-messages" ng-messages="editForm.availableFrom.$error">
              <div ng-message="valid">Please enter valid date</div>
          </div>
      </div>
      <div hide-xs="" hide-sm="" class="c-datepicker_container__icon">
          <label>&nbsp;&mdash;&nbsp;</label>
      </div>
      <div class="c-datepicker_container__date">
          <md-datepicker name="availableTo" ng-model="vm.houseType.availableTo"></md-datepicker>
          <div class="c-validation-messages" ng-messages="editForm.availableTo.$error">
              <div ng-message="valid">Please enter valid date</div>
          </div>
      </div>
      <div class="c-datepicker_container__icon">
          <md-icon md-svg-icon="icon-warning" ng-show="vm.isExpired()">
             <md-tooltip>House type is expired</md-tooltip>
          </md-icon>
      </div>
   </div>
```


# Less

## MIXINS

### Transition
```
.transition (@transition) {
    -webkit-transition: @transition;
    -moz-transition: @transition;
    -o-transition: @transition;
    transition: @transition;
}
```
# Md Datepicker (align - input, label)
```
.c-datepicker_container {
    display: block;
    position: relative;
    padding: 2px;
    margin: 18px 0;

    &__label {
        -webkit-font-smoothing: antialiased;
        padding: 0 0 2px 3px;
        -webkit-transform-origin: left top;
        transform-origin: left top;
        position: absolute;
        bottom: 100%;
        left: 0;
        right: auto;
        -webkit-transform: translate3d(0, 6px, 0) scale(0.75);
        transform: translate3d(0, 6px, 0) scale(0.75);
    }

    &__icon,
    &__date {
        float: left;

        &:not(:last-child) {
            margin-right: 20px;
        }
    }

    &__icon {
        padding-top: 10px;
        margin-right: 5px !important;
    }

    &__date {
        max-width: 204px;
    }

    .clearFix();

    &:after {
        min-height: 24px;
    }

    .md-datepicker-input-container {
        margin-left: 0;
        width: 160px;
    }
}
```

# Md Datepicker (animation validation-messages)
```
.c-datepicker_container .c-validation-messages {
    padding-left: 40px;
    overflow: hidden;
    word-wrap: break-word;

    ng-message,
    [ng-message] {
        .transition(all 0.3s);
    }

    &.ng-active {
        ng-message,
        [ng-message] {
            opacity: 1 !important;
            margin-top: 0 !important;
        }
    }

    &.ng-inactive {
        ng-message,
        [ng-message] {
            opacity: 0 !important;
            margin-top: -100px !important;
        }
    }
}
```

**Comment by MariskaS** [comment]
http://codepen.io/anon/pen/VeVrQo

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
