### ISSUE TITLE
Using `$mdToast` inside an interceptor is triggering circular dependency

### ISSUE THREAD

**Issue by diosney** [angular/material#6946]
```js
angular
    .module('app.components.http-errors-interceptors')
    .factory('HttpError500Interceptor', HttpError500Interceptor);
    .config(moduleConfig);

  /* @ngInject */
  function moduleConfig($httpProvider) {
    $httpProvider.interceptors.push('HttpError500Interceptor');
  }

  /* @ngInject */
  function HttpError500Interceptor($q, $mdToast, $filter) {
    var interceptor           = {};
    interceptor.responseError = responseError;

    function responseError(responseError) {
     var toastContent = $filter('translate'('APP.COMPONENTS.HTTP_ERRORS_INTERCEPTORS.500');
      if (responseError.status === 500) {
        $mdToast
            .show($mdToast.simple()
            .content(toastContent)
            .position('bottom right')
            .hideDelay(5000));
      }
      return $q.reject(responseError);
    }

    return interceptor;
  }
```

See the full problem description at http://stackoverflow.com/q/35119231/881286

Thanks

**Comment by ThomasBurleson** [comment]
`$mdToast` uses `$http` or the `$templateCache` to load the toast template (if it is not simple content). 
This issue sounds like an edge-case and needs investigation.

**Comment by diosney** [comment]
@ThomasBurleson Thanks, if you need more information just tell me.

It would be great that this is sorted out since it is very useful to show errors to users in the http response interceptors.

**Comment by diosney** [comment]
More about it, mid 2015. The solution with $inject didn't worked for me.

http://www.thoughtdelimited.org/thoughts/post.cfm/angular-material-design-mdtoast-and-httpinterceptors

**Comment by codymikol** [comment]
+1 I think it's a pretty common use case for showing errors returned from the server.

**Comment by Splaktar** [comment]
@codymikol please take a look at the solution here: https://stackoverflow.com/a/39595706/633107
