### ISSUE TITLE
Feature Request - mdDialog show/hide should make the dialog template (in)visible, instead of creating/destroying it

### ISSUE THREAD

**Issue by akdor1154** [angular/material#6947]
It would be great if an mdDialog's contents could be pre-loaded and persisted, with show() and hide() simply making them visible and invisible, instead of creating and removing them each time.

Use case:
I have a small admin / CRUD interface as a component of a larger app, with said admin interface being written in AngularJS with Material. The admin interface is UI-wise contained in an mdDialog (think of something like an load/share/upload/save interface overlaying my larger canvas-style app), which takes a relatively long time to open as it needs to compile its template each time. It's also a bit complicated to save the state of the dialog each time. If the contents of the dialog were persistent with only their visibility being toggled by hide()/show(), then this would make this use-case a lot smoother.

Alternatively, is there any way to achieve this functionality now? I've been having a quick peek through the sources and it looks like the assumption of creating/deleting the element runs quite deep. :(

**Comment by MaximeAnsquer** [comment]
Hello, could someone tell me what happened with this PR please ? Is there a way to do what is asked now?

Thank you very much.

**Comment by raychz** [comment]
I am also wrestling with the same thing now.  Any updates?

**Comment by Splaktar** [comment]
@MaximeAnsquer this is just a feature request. No PR has been submitted with this functionality.

`md-dialog` is designed for quickly showing a small amount of template/DOM. It is not designed to encapsulate a full app as this does not align with the [Material Design spec](https://material.io/design/components/dialogs.html).

If you need to run an entire app within a dialog, then I would suggest that you build your own custom dialog component. For reference, I would refer to `md-dialog` and `md-panel`.
