### ISSUE TITLE
md-autocomplete shows single empty result in dropdown when result not found and sometimes adds up multiple empty values to dropdown

### ISSUE THREAD

**Issue by alphazhe** [angular/material#6948]
When input array is empty it shows blank single result in dropdown. Please check this issue.

**Comment by alphazhe** [comment]
I even tried it with filter as per given in demo. It worked for few times and again it started to show blank result randomly.

**Comment by alphazhe** [comment]
I found out the reason behind this , the empty bar was coming because of md-min-length is set to 0. So when result is not found out it was showing tab for md-not-found even when I havent added it in my html. I fixed my problem by setting md-min-length to 1. But it should not show not found bar when md-min-length is 0.  And also the issue adding extra blank fields is not fixed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
