### ISSUE TITLE
Update docs only on releases

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#695]
Once we have achieved 1.0 Beta stages, we should modify the Doc builds to occur only during an explicit release.

**Comment by matthewrfindley** [comment]
@ThomasBurleson This should be complete based on this PR https://github.com/angular/material/pull/2852 and numerous commits in master that copy tags to code.material.angularjs.org repo.  Let me know if there is more to this issue, otherwise we can consider this closed.

**Comment by matthewrfindley** [comment]
Closing issue.  Snapshots are being being created on merges to master.
