### ISSUE TITLE
mdTabs: md-dynamic-height animation is not working correctly with nested tabs

### ISSUE THREAD

**Issue by marcel-dancak** [angular/material#6950]
When some mdTab item contains nested mdTabs component and both mdTabs use md-dynamic-height, height animation is not working as expected in some cases. Here is an example (using 1.0.4 version). When you select third tab, animation from first or second tab is broken.

http://codepen.io/anon/pen/rxKEzB?editors=1000

I tried to debug it and I found, that outer mdTabs mixes it's own ```<md-tab-content>``` elements with ```<md-tab-content>``` elements of nested mdTabs component. So in this example, it thinks it have 4 content elements, and that third content element is content of nested tab - ```<md-list>```. So it use wrong element to determine final height in animation.
I was able to fix this issue in one line of code, so I didn't create a pull request. The fix consist of using
```javascript
elements.contents = elements.contentsWrapper.children;
```
instead of
```javascript
elements.contents        = elements.contentsWrapper.getElementsByTagName('md-tab-content');
```
for getting right collection of content element (MdTabsController.getElements method in modules/js/tabs/tabs.js).

**Comment by ThomasBurleson** [comment]
Nested Tabs are not supported.
