### ISSUE TITLE
Material is broken on Chrome 48. (Ok on Chrome 47 and Firefox)

### ISSUE THREAD

**Issue by GautierT** [angular/material#6952]
Still got the bug after upgrading to 1.0.4 on Chrome 48. 
I have to put min-height: 0; to almost all element (md-card, md-card-content, md-card-title, ...)
The behaviour is very weird because if i add min-height: 0; on the debug console on chrome it will work and calculate the height correctly but if i remove min-height: 0; after that is still correctly calculate the height...

Firefox 43 with Angular Material 1.0.4
![capture d ecran 2016-02-01 a 11 50 56](https://cloud.githubusercontent.com/assets/6089653/12715344/1c64d358-c8da-11e5-85ec-e7cc9ac7519e.png)

Chrome 48 with Angular Material 1.0.4
![capture d ecran 2016-02-01 a 11 50 41](https://cloud.githubusercontent.com/assets/6089653/12715343/1c5fb21a-c8da-11e5-9337-dd2a0e1c62ef.png)

Thanks

**Comment by ThomasBurleson** [comment]
This sounds like a flexbox-related issue. Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd

**Comment by GautierThiriez** [comment]
@ThomasBurleson. I think its related to this issue #6841. And @pradeep330 told me to put flex="none" on all non flex div and it's working.

**Comment by kunKun-tx** [comment]
@GautierThiriez ** flex="none" **solved my problem

**Comment by srokatonie** [comment]
Not fixed on Chrome 49 neither...

**Comment by nkoterba** [comment]
Here's a codepen:
http://codepen.io/anon/pen/bpoVzy

View in safari and firefox.  The top and bottom divs should be the same HEIGHT.  They are.

In my latest Chrome (Version 49.0.2623.110 (64-bit) - Mac OSX) the divs are different heights.  I'm including screen shots here.

What's very odd is the CONTENT inside of the flex'd `div`s actually affects the layout/rendering of the parents.  I've never seen this before with MD or Flexbox.  I literally ripped my entire App down to basic divs before I thought try to it in other browsers....

## This is why I :heart: web development.

**Safari Version 9.1 (11601.5.17.1)**
![image](https://cloud.githubusercontent.com/assets/2508944/14193539/cca3d940-f773-11e5-8bde-b6054da9a7b0.png)

**Firefox  45.0.1**
![image](https://cloud.githubusercontent.com/assets/2508944/14193547/e894739e-f773-11e5-876b-afcc35dad180.png)

**Chrome (Version 49.0.2623.110 (64-bit))**
![image](https://cloud.githubusercontent.com/assets/2508944/14193572/0b425c8a-f774-11e5-9758-8a230435ce94.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
