### ISSUE TITLE
AngularJS Code Is Not Working

### ISSUE THREAD

**Issue by Kaleemulla** [angular/material#6954]
The AngularJS code is not working on any of my browser(Chrome, Mozilla, IE). when i tried to see if i can re-generate the code again from the scratch, the angularjs examples given in "material.angularjs.org" is also not working for me when i edit it with codepen. plz help

**Comment by DevVersion** [comment]
You provided very less information but if understood your situation right, then this relates to #6930. So that's a duplicate.

**Comment by Kaleemulla** [comment]
the link in my code is "https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.1-master-a687bfc/angular-material.js" which shows unavailable. which is the new version which shld be replaced with this link?

**Comment by DevVersion** [comment]
Okay, seems I understood your problem correctly. This is a duplicate #6930. If you have anything you wan't to suggest, you should write it in there... It would be great if you close your issue :+1: 

The current problem can be tracked in #6930 (as already said)
