### ISSUE TITLE
Add possibility to specify default icon for md-select via $mdIconProvider

### ISSUE THREAD

**Issue by romanchak** [angular/material#6956]
Right now to replace md-select-icon I need to redefine it with css, which forces me to load some additional fonts, since I can do it only by replacing 'content' property, e.g.: .md-select-icon:after

```css
    display: block;
    content: '\25BC';
    position: relative;
    top: -1px;
    speak: none;
    -webkit-transform: scaleY(0.6) scaleX(1);
    transform: scaleY(0.6) scaleX(1);
```

Would be nice if we could do this via $mdIconProvider.

**Comment by romanchak** [comment]
Ok. Looks like we can load svg icon via content property by url. Not sure how consistent this approach across different browsers, but in Chrome works well.

```
  md-select .md-select-icon {
    content: url('../assets/icons/align.svg')
  }
```

**Comment by ThomasBurleson** [comment]
Will not fix.
