### ISSUE TITLE
Offset for md-select directive

### ISSUE THREAD

**Issue by mzahor** [angular/material#6957]
Would be great to have a possibility to set position offset for `md-select ` the same way we can do for `md-menu` with `md-offset` (example: https://github.com/angular/material/blob/f6e97a02a9c88b1695094a8a85a11958924e4c61/src/components/menu/demoMenuPositionModes/index.html#L28).

**Comment by DevVersion** [comment]
Seems like this feature won't be implemented, see #6960, which has been rejected, so I'll close that issue too.
