### ISSUE TITLE
HEAD(MASTER) in angular material throws error

### ISSUE THREAD

**Issue by jayeshanandani** [angular/material#6958]
https://material.angularjs.org/HEAD/demo/autocomplete throws error when clicked on demos. 
`Unknown provider: componentProvider <- component <- DemoCtrl <- DemoCtrl <- DemoCtrl <- DemoCtrl`

**Comment by DevVersion** [comment]
Yes, can reproduce. Investigated, it's caused by 82625cf4edeba84ef38fb816f1b32ded902c8064

**Comment by DevVersion** [comment]
Fixed in #6959.. read more there.

**Comment by jayeshanandani** [comment]
Commit has fixed this. Closing this issue.
