### ISSUE TITLE
Using targetEvent for $mdDialogshow cause very janky animation

### ISSUE THREAD

**Issue by Todd-Werelius** [angular/material#696]
Using the targetEvent has a very janky animation when using the targetEvent option for $mdDialogshow

Keep an eye on the upper left corner, you can see the dialog flash into existence, this is even worse than it looks in the gif 

![ed37k](https://cloud.githubusercontent.com/assets/5982829/5116225/c123b6a8-6ffc-11e4-9298-b2dd70d0e394.gif)

Removing the targetEvent option results in smooth animation from the bottom of the screen  

##### [Link to Plunkr](http://plnkr.co/edit/WLuxGe) using v0.5.1-master-96d3208

**Comment by ajoslin** [comment]
This is much better in master.
