### ISSUE TITLE
mdTabs: SelectedIndex Adjustments when removing tabs

### ISSUE THREAD

**Issue by SirDarquan** [angular/material#6963]
I've found an issue where the ui moves to a new tab when I close a tab that is to the left of the tab that is actually active. 

Here is a plunker of the issue: https://plnkr.co/edit/QHBEfwL9yJY0j0dovw0p?p=preview.

Basically i created 3 tabs and set md-selected="1" which is the middle tab. Tab 1 has an ng-if expression on it to allow me to hide the tab at will. The other two tabs are normal. At this point, selectedIndex is **1**. Now if you click the Toogle First Tab button, it deactivates a boolean which will hide the First tab. The selectedIndex remains **1** but now the number of available tabs have changed and the ui moves to the tab that is now designated as index 1.  I feel that in this case the ui should have remained on the the tab that was actually selected and that the selectedIndex should have been adjusted to reflect the change. The same with unhiding the tab except it moves back to the second tab.

**Comment by ThomasBurleson** [comment]
Will not fix.
