### ISSUE TITLE
Feature Request: Set background color of whole md-chip

### ISSUE THREAD

**Issue by LisaTatum** [angular/material#6965]
I have not find a way to style the whole md-chip.

The only background color I could set was on the tag around the text in the md-chip like or around the md-chip-template: Both ways colorize only the text block.

```
<md-chip-template style="background: orange;">
                <strong>{{$chip.name}}</strong>
 </md-chip-template>
```

**Comment by DevVersion** [comment]
I don't think there will be any possibility to easily change the color of the `md-chips`, because whenever we provide theming support through our `$mdTheming` service but not through plain css.

**Comment by LisaTatum** [comment]
Theming would be another scenario. I think more of business logic requirements. You want to quickly get an overview which subjects you teach and this happens by a color of your choice.

**Comment by DevVersion** [comment]
@LisaTatum No, wasn't misunderstanding you, just meant `'md-chip` instead of `md-chips`. 
And after your example, it seems to be a good feature, which should be added IMO. 
:+1:

**Comment by LisaTatum** [comment]
I want to second my request with more uses cases from edutainment field:

You see at first glance what students are taught in which subjects. In certain school systems/classes this can really vary.

![image](https://cloud.githubusercontent.com/assets/13928925/12761571/c52089d0-c9eb-11e5-9c5c-e08c14ab7337.png)

Another use case would be the administration of https://en.wikipedia.org/wiki/Periodic_table where each atom would have its certain color. Of course a round chip/atom would make more sense instead of an oval shape. But I would already be very grateful for a colored md-chip!

**Comment by EladBezalel** [comment]
@LisaTatum A quick override will be
``` css
.math.md-chip {
  background-color: yellow;
}
```
``` html
<md-chip class="math">Math</md-chip>
```

as you can see [here](http://codepen.io/EladBezalel/pen/NxOXye)

**Comment by ThomasBurleson** [comment]
@EladBezalel - your approach uses Static chips... but @LisaTatum needs dynamic chips with *remove* features.

**Comment by EladBezalel** [comment]
@ThomasBurleson, I've just checked on every chip component, and it's working with no problem.

also my PR removes the .md-chip class, so she will only need to define the class to apply
if she needs some logic applying a class she can always use `ng-class` or `ng-style` to apply cretin style according her logic.

**Comment by LisaTatum** [comment]
@EladBezalel As Thomas said I have dynamic chips. There is no logic to apply ng-class/style. I just get a rgb string "255,100,50" from backend and I want to render that color on the whole md-chip.

**Comment by EladBezalel** [comment]
That's even easier, `ng-style` on the `md-chip` with your background color

**Comment by jdiapps** [comment]
How would I apply the background color change to md-chips?

**Comment by LisaTatum** [comment]
@EladBezalel Thanks for quick fix!

**Comment by amielmendoza** [comment]
How can I change the font color of the placeholder?

**Comment by z3ntu** [comment]
@EladBezalel Do you have an example for `md-chips` with a `ng-model`? When you set the background color in `md-chip-template`, it only gets applied to the text and not the whole chip.
![selection_071](https://cloud.githubusercontent.com/assets/3768500/15672565/b91b05a4-2731-11e6-9460-3f9f4992b1c6.png)

**Comment by EladBezalel** [comment]
@z3ntu please provide your codepen so i can try to apply it there :)

**Comment by z3ntu** [comment]
@EladBezalel like [this](http://codepen.io/z3ntu/pen/dXPXdp)?

**Comment by z3ntu** [comment]
@EladBezalel Can you please take a look at it?

**Comment by EladBezalel** [comment]
@z3ntu can you please open a new issue about it and refer this one?

**Comment by z3ntu** [comment]
@EladBezalel done.

**Comment by sohail85** [comment]
@EladBezalel: How to apply custom style for md-chips not md-chip (the dynamic one)

**Comment by EladBezalel** [comment]
@sohail85 the active issue for that is #8692,we're on it :)

**Comment by Bleil** [comment]
For multiple color on chips, I've created in sass an loop for that:

`@for $i from 1 through length($analogous_colors) {
        md-chip:nth-child(#{length($analogous_colors)}n+#{$i}) {
            background: nth($analogous_colors, $i);
            color: white;

            md-icon {
                color: white;
            }
        }
    }`

It's based on an array of colors and the childs of the chips wrapper...

Hope I can help someone
