### ISSUE TITLE
Demo for Radio button shows wrong values in HEAD release

### ISSUE THREAD

**Issue by jayeshanandani** [angular/material#6969]
https://material.angularjs.org/HEAD/demo/radioButton , Contact List appears to be buggy. It doesn't displays the appropiate value selected.

**Comment by kevinlbatchelor** [comment]
I think all of the demos are broken, or their CDN is not up to date.

**Comment by jayeshanandani** [comment]
@kevinlbatchelor Demos are working fine after latest commit they made. But either code or something is buggy in that particular example.

**Comment by RolandHeath** [comment]
This has been broken for quite a while, actually - see #5623
I think it's just a bug in the documentation, not the radio buttons.

**Comment by jayeshanandani** [comment]
Yes. That sounds correct. Its duplicate. I will close this issue so we can track changes from #5623 itself.

**Comment by kevinlbatchelor** [comment]
@jayeshanandani none of the demos work for me :( and by that I mean the codepen examples. I just get a bunch of 404 errors.

**Comment by Kjuib** [comment]
https://github.com/angular/material/issues/6930
