### ISSUE TITLE
md-select and md-autoselect

### ISSUE THREAD

**Issue by Knoxvillekm** [angular/material#6974]
How to select first option when model is undefined for md-select?

**Comment by mpiasta-ca** [comment]
Using basic logic in your controller...? 

```
if (!$scope.mySelect) $scope.mySelect = selectOptions[0]; //where $scope.mySelect is the ng-model for your md-select field
```

**Comment by topherfangio** [comment]
Can you please provide a Codepen of what you are attempting/wanting to do?

**Comment by Knoxvillekm** [comment]
Add md-autoselect (If true, the first item will be selected by default) attribute, like in mdAutocomplete

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
