### ISSUE TITLE
md-sidenav possibility to push the main content instead of covering it

### ISSUE THREAD

**Issue by herbalizer404** [angular/material#6975]
I'm trying to change the sidenav behavior, to push the main content instead of covering it.
When I put the position of the sidenav in relative en display:none the backdrop, I almost have the behavior I'm looking for, but the animation is laggy. Do you have a solution for that, or do you have planned to choose type of behaviour for sidenav. Thx

**Comment by DevVersion** [comment]
That's a duplicate of 2208
