### ISSUE TITLE
Open multiple dialogs?

### ISSUE THREAD

**Issue by fhrtms** [angular/material#698]
I would like to open multiple layered dialogs from each controller. Is this possible?
Currently if i open a second dialog, the first one closes automatically.

**Comment by MarcosPortugal** [comment]
@fhrtms thanks for that code! It took me a while to figure out what you were doing since there were no english comments but it seems you are just saving the main dialog's scope before opening the second dialog, and then if the user cancels this second one, you just reopen the main with the old scope, is that right?
 I'm going to do it a bit differently from you, but the idea remains the same. Thanks a lot!

**Comment by fhrtms** [comment]
@MarcosPortugal: Yes, this is what i do.

**Comment by benn0r** [comment]
I really need nested dialogs for our application, so i took a look at the source code. I didn't test it very well but i think its working, at least for us. Its a quick solution (manipulating the z-index like i do is not very nice, i guess).

If a new dialog opens, old dialogs won't close. If $mdDialog.cancel() is called the most recent dialog will be closed.

https://github.com/hayloft/material/commit/2ad189a6adaa49975ed82df5ad0e54db9d51629d
Obviously some unit tests break with this commit...

**Comment by jpdesigndev** [comment]
:+1: for multiple dialogs.

**Comment by jpdesigndev** [comment]
Has anyone from core team been able to try out @benn0r's code? The change seems easy to digest.

**Comment by e209m631** [comment]
Is it possible to update template of current dialog instead of showing different dialog?

**Comment by rschmukler** [comment]
@ThomasBurleson the UX team stated that dialogs should stack, but I think that the UX @fhrtms might be better given that dialogs could be different sizes. Could we explicitly show them the screenshot and see what they say.

![ScreenShot](https://camo.githubusercontent.com/93e2c74cf5c2f8cca68d73dcf28a5a4f094978a1/687474703a2f2f692e696d6775722e636f6d2f4e423258774e342e6769663f31)

**Comment by DmitryEfimenko** [comment]
+1

**Comment by ThomasBurleson** [comment]
@rschmukler - excellent idea. 
@fhrtms - thank you.

**Comment by patriknyd** [comment]
Yes, please, I would love to see this fixed. Bumped in to this problem today. Large dialog needs to show a smaller confirmation dialog. Looks like this has been moved up to 0.10.0, so I guess I'll have to hack 0.9.X with some version of benn0rs code until then. Or something else.

**Comment by ThomasBurleson** [comment]
@patriknyd - this is a new feature that we will try to address in 0.10. 

> 0.90 is focused on bugs and polish.

**Comment by anderson-arlen** [comment]
+1

**Comment by mathiasmoeller** [comment]
+1

**Comment by tamsammyy** [comment]
+1

**Comment by everlaat** [comment]
+1

**Comment by websirnik** [comment]
+1

**Comment by ishener** [comment]
+1

**Comment by dyatchenko** [comment]
I would really glad to have this issue fixed.

**Comment by kikhtenko** [comment]
+1

**Comment by edicius6** [comment]
+1

**Comment by ThomasBurleson** [comment]
Locking this issue until it becomes active, in-progress.

**Comment by ginader** [comment]
any update on this @ThomasBurleson?
