### ISSUE TITLE
Web-site demo bug

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/material#6980]
Didn't know where else to post it, since didn't find any contact information
This isn't really an issue with ngMaterial itself, just an inconsistency in a demo:

https://material.angularjs.org/latest/demo/radioButton

The very bottom demo (Multi Column) doesn't display the "Selected User" right, and that's perhaps because the "selectedIndex" (which is the ng-model for the Radio group) is used as the index in the array. Need to subtract '1' from it

There is also something wrong about the Google copyright comment at the bottom when you open the code in Codepen, more specifically about where the license can be "found". Looks like this comment has propagated into most of the demos. Nobody really sees the comment, but what if someone indeed wants to read and memorize the license for these code snippets?

**Comment by ThomasBurleson** [comment]
The radioButton selectedIndex is a known issue. Closing as duplicate.
