### ISSUE TITLE
md-dialog + long forms + IOS

### ISSUE THREAD

**Issue by 0101adm** [angular/material#6983]
AM 1.0.4 (reproduced on .3 and .2)

this only reproduces on a real iphone.   on safari and chrome.

http://codepen.io/0101adm/pen/RrBeWm

to reproduce: click 'open' to open the dialog.

heights are skewed.  form elements become clipped and hidden.

renders as normal on android.

**Comment by 0101adm** [comment]
also appearing in 1.1.0-rc1.

**Comment by 0101adm** [comment]
closing.

**Comment by ChrisSoto** [comment]
Was this resolved?

**Comment by 0101adm** [comment]
@ChrisSoto i believe the issue stemmed from md-subheader.
