### ISSUE TITLE
[Question] md-chips pending features

### ISSUE THREAD

**Issue by LisaTatum** [angular/material#6987]
When I look at your documentation:

Where can I test these features? Is there any branch I should check out?

"Pending Features

Style
Colours for hover, press states (ripple?).
Validation
allow a validation callback
hilighting style for invalid chips
Item mutation
Support <md-chip-edit> template, show/hide the edit element on tap/click? double tap/double click?
Truncation and Disambiguation (?)
Truncate chip text where possible, but do not truncate entries such that two are indistinguishable.
Drag and Drop
Drag and drop chips between related <md-chips> elements.
Warning: This component is a WORK IN PROGRESS. If you use it now, it will probably break on you in the future."

**Comment by 0101adm** [comment]
you can get a quicker response by posting to the group.

https://groups.google.com/forum/#!forum/ngmaterial

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
