### ISSUE TITLE
feature-request(mdDialog): Show an indeterminate progress circular while external template is loading

### ISSUE THREAD

**Issue by mbarakaja** [angular/material#6988]
Having a **mdDialog** that loads from the server a heavy template for the first time, nothing is shown on the screen until the template is fully loaded.

Imagine an user clicking a button that call such mdDialog, the application will not respond leaving the sensation that the button is not working.

It will be nice, if the **$mdDialog** opens immediately with his default white box containing a indeterminate progress circular in the center.

![dialog-loading-template](https://cloud.githubusercontent.com/assets/7861175/12763241/138deb9a-c9d2-11e5-807e-a2c24cad5176.png)

I accomplished this using an inline template in the template property with **ng-include** that loads the external template, but this solution is very ugly in my opinion.

**Comment by ThomasBurleson** [comment]
Attn @ErinCoughlan - another feature for `panel`

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
