### ISSUE TITLE
Accessibility - Menubar tab-index

### ISSUE THREAD

**Issue by pdore-netfore** [angular/material#6989]
The tab-index of the menu-bar items should come immediately after the menubar icon.
As is stands now, the User needs to tab through the entire app before reaching the menubar itself.

**Comment by pdore-netfore** [comment]
This seems to be an issue when the md-menu-content's first child is not a button.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
