### ISSUE TITLE
Angular-material unusable with Jammit and JSMin

### ISSUE THREAD

**Issue by bobber205** [angular/material#6991]
Sort of a huge bummer.

Anyone know why this is happening?
![console](https://cloud.githubusercontent.com/assets/5841107/12764932/0651b2fc-c9b1-11e5-8b38-36a9ac28fb16.png)

![the social commerce and payments platform chirpify 2016-02-02 13-30-10](https://cloud.githubusercontent.com/assets/5841107/12764950/1a2c5cc8-c9b1-11e5-92ab-caa9aa97b5a6.png)

Why is that throwing the error in the 1st screenshot? (`Uncaught SyntaxError: Unexpected identifier`)

**Comment by RolandHeath** [comment]
Minifying angular code has some significant pitfalls, this might not be angular-material specific, and it might not have an easy fix. 
This might help: 
https://docs.angularjs.org/tutorial/step_05#a-note-on-minification

**Comment by bobber205** [comment]
I know the pitfalls and workarounds for minifying angularjs. 

It should definitely be supported, most of us don't have a choice when it comes to how JS is served.

**Comment by RolandHeath** [comment]
Yeah, that's cool - with no idea how experienced a person is, it's hard to gauge whether I have useful advice.
