### ISSUE TITLE
mdChips: with autocomplete minLength=0, list should not open automatically when a chip is removed.

### ISSUE THREAD

**Issue by antoinebrault** [angular/material#6992]
It feels weird that the list opens after a delete. 
And the list opens at the wrong place too.

![bug](https://cloud.githubusercontent.com/assets/852552/12765233/b3583312-c9cb-11e5-91bb-0d705b4a48ba.gif)

**Comment by DevVersion** [comment]
Little codepen to see the current behavior: http://codepen.io/DevVersion/pen/vLzgeX?editors=1010
@antoinebrault What do you suggest for the behavior? it's the default behavior of the autocomplete.

**Comment by antoinebrault** [comment]
Maybe it's only cause the focus is on the list and I have to click twice to delete an item.

Look at how select2 and chosen do it:
https://harvesthq.github.io/chosen/#multiple-select
List doesn't open until input is refocused after a add/delete. I can remove multiple chips quickly.

https://select2.github.io/examples.html#multiple
List does open after a delete but I can remove multiple chips and the list stays open between deletes and doesn't move around. 

Either way, it feels more natural than the current impl of chips/autocomplete.

**Comment by antoinebrault** [comment]
Any plans on fixing this?

**Comment by afreeland** [comment]
I am experiencing this issue as well.  I feel that if a user selects the 'x' to remove the chip that the autocomplete should not be triggered.  Are they any workarounds for this?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
