### ISSUE TITLE
md-toolbar with icon button and mdSideNav - icon click is active when it shouldnt

### ISSUE THREAD

**Issue by KalpanaAr** [angular/material#6994]
I have an icon button for menu on toolbar. When I click on the menu icon, it will be overshadowed by left sidenav and when I close the sidenav, the icon button appears clicked like shown below. Can someone tell me how to overcome this issue? Thanks!

Menu icon
![menu icon](https://cloud.githubusercontent.com/assets/8092075/12768375/d7ba4a16-c9d4-11e5-9aa0-e4d110f337b6.PNG)

After clicking on menu icon, sidenav opens
![after clicking on icon menu](https://cloud.githubusercontent.com/assets/8092075/12768380/dfa54ee2-c9d4-11e5-8f18-d87184acbdd7.PNG)

After closing sidenav, icon click is still active
![closing side nav](https://cloud.githubusercontent.com/assets/8092075/12768381/dfab0116-c9d4-11e5-8c24-a37d6680e4d5.PNG)

**Comment by DevVersion** [comment]
That's a duplicated issue of #5563 and a related PR, which fixes that issue, is pending - See #5589

**Comment by KalpanaAr** [comment]
Thanks for the reply @DevVersion ! Looking forward for your fix to go live!

**Comment by DevVersion** [comment]
@KalpanaAr Can you please close your issue, because of the duplicate :)
