### ISSUE TITLE
[a11y] Bug in Tab UI

### ISSUE THREAD

**Issue by opozo** [angular/material#6995]
@jelbourn, I was testing the Tab UI and found a bug in the keyboard navigation flow, just try this demo [1] out.

Let me know if you are able to reproduce it consistently.

Thanks,
Orlando

[1] https://material.angularjs.org/latest/demo/tabs

**Comment by jelbourn** [comment]
@opozo could you be more specific as to what the bug _is_?

**Comment by opozo** [comment]
* Steps to reproduce the bug

1 - Go to https://material.angularjs.org/latest/demo/tabs
2 - Press "tab" to enter the Tab Widget
3 - Notice that the first tab is not highlighted (this is the bug)
4 - Press "right arrow" to navigate tab with the keyboard
5 - Press "left arrow" to go back to the first tab
6 - Press "shift+tab" to go back to "Edit on CodePen"
7 - Press "tab" to enter the Tab Widget (now it's working as expected)

BTW, Tab demos are not rendering on CodePen.

**Comment by opozo** [comment]
Also, for mouse users, we should highlight a tab [1] when they mouse over it.

[1] http://www.orlandopozo.com/video/devtool-tab-ui.mov

**Comment by ThomasBurleson** [comment]
@robertmesserle - can you investigate?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
