### ISSUE TITLE
disabled md-slider is included in keyboard focus traversal.

### ISSUE THREAD

**Issue by pietschy** [angular/material#6996]
Including `md-slider:focus {background:blue}` in the demo (release 1.0.4) gives the following:
![image](https://cloud.githubusercontent.com/assets/556703/12771955/6816c8ee-ca81-11e5-9b09-d1d49a35099d.png)

**Comment by ThomasBurleson** [comment]
Fixed with SHA e0abeb4dc46a1753616a911fe54f14d8f1148a25
