### ISSUE TITLE
md-datepicker date format validation issue

### ISSUE THREAD

**Issue by iamisti** [angular/material#6997]
Hi Guys,

**Description**
There is an issue with having a formatted date with the `md-datepicker` directive.
After I used `$mdDateLocaleProvider` to set up the date format I need, now it's no longer possible to edit the dates manually (not using the date picker, just changing the numbers inside the input)

Using the picker still works, the problem is only with manually editing the dates there.
Here is a plunkr, try to edit the month or the date number to something else and you'll see that the validation will kick-off.

The interesting thing is that I've used this date format: `DD/MM/YYYY`
But if I use a different date format like this: `MM/DD/YYYY` then everything is working. (probably only because of my regional settings cause somehow it's trying to apply my region defaults to the validation rules... just a hint.)

**Retro steps:**
1. open example: http://codepen.io/iamisti/pen/ZQjgOG
2. load the example and pick this date with the date picker: 24/02/2016
3. try to change february to march, e.g.: 24/03/2016

**Expected behaviour:** 
validation still passes

**Current behaviour:**
validation kicks-off

**Browser**
Chrome  48.0.2564.97 (64-bit)

**Version used:** 
`1.0.3`

**Comment by jelbourn** [comment]
@iamisti You're setting a custom date formatter, but not the parser (`parseDate`) which is also required in order for the component to know how to convert a string into a date instance. Without specifying that, it defaults to using the browsers default parser, which see "24/02/2016" as an invalid date.

**Comment by iamisti** [comment]
Thanks @jelbourn , it wasn't so obvious but it solved my problem.
If somebody else also struggling with this issue, here is an example how to fix it:
http://codepen.io/iamisti/pen/YwJzoN

**Comment by joaodallarosa** [comment]
@iamisti You just saved my day... Thank you!

**Comment by horelvis** [comment]
thanks you @iamisti  perfect workaround!
