### ISSUE TITLE
md-datepicker: Why Didn't the Angular Material Team Follow the Material Design Specs?

### ISSUE THREAD

**Issue by FlipOneDev** [angular/material#6998]
Just curious why the Angular Material development team/contributors decided NOT to follow the official Material Design specs for **md-datepicker** (https://www.google.com/design/spec/components/pickers.html#pickers-date-pickers).

Any reason(s) why?

**Comment by LisaTatum** [comment]
I can not give an answer but according to the screenshots the datepicker is a modal dialog. They are bad UX generally.

**Comment by jayeshanandani** [comment]
@FlipOneDev I believe the current layout is not the final one. Its just v1.0. There are going to be changes in calendar (UI is one of them) for which there are issues that have been pending and will soon be done.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
