### ISSUE TITLE
md-autocomplete: tabindex bug - attribute should be removed from md-autocomplete to avoid tabbing twice to get inside inner input

### ISSUE THREAD

**Issue by tniezurawski** [angular/material#6999]
Hi guys,

I prepared test case. You will find everything in this plunker: 
http://plnkr.co/edit/7sR7xillUBgp8BeiT0p9

**There is a workaround decorator inside this plunker** if you need it.

_Description from my plunker:_
It seems that when you use "tabindex" attribute on "md-autocomplete" directive it is properly propagated to "input" element inside. But the "tabindex" on "md-autocomplete" should be removed.

Now when you do specify tabindexes you will end up with pressing "tab" key twice to get inside "autocomplete".

-- used versions:
Angular: 1.4.9
Angular-Material: 1.0.4

**Comment by DevVersion** [comment]
@tniezurawski Would like to take a look at #7005?

**Comment by tniezurawski** [comment]
@DevVersion I think that approach in #7005 is valid and should do the trick. Thanks!

**Comment by DevVersion** [comment]
@tniezurawski :Perfect +1:
