### ISSUE TITLE
md-tabs: Add support for aligning some tabs to the right.

### ISSUE THREAD

**Issue by Vayvala** [angular/material#7002]
Currently all tabs are aligned to the left, but I need to align one tab to the right. I have tried to add `float:right`:

    <md-tab label="compare"  style="float:right!important;"></md-tab>

But it didn't make a difference.

**Comment by kyrylkov** [comment]
+1

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by Ravindra042** [comment]
Is this resolved ?. Can you please share link of solution

**Comment by caneraydinbey** [comment]
What is soltion?

**Comment by FeLiX-7** [comment]
+1

**Comment by Splaktar** [comment]
I can't find any part of the Material Design [tabs spec](https://material.io/guidelines/components/tabs.html#) that covers this behavior. Please extend the component to do this in your local project as we don't plan to add this off-spec feature to AngularJS Material.

Also please avoid adding posts with `+1` in them. Please use the emojis to give the OP a thumbs up if you want to signal your agreement or support.
