### ISSUE TITLE
codepen-example: codepen example doesn't work

### ISSUE THREAD

**Issue by IPRIT** [angular/material#7004]
Codepen example (Layout -> [Troubleshooting](https://material.angularjs.org/latest/layout/tips) -> Flex Element Heights) doesn't work due to non-working host cdn.gitcdn.xyz.
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module StarterApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
Error: [$injector:nomod] Module 'ngMaterial' is not available!
```
Follow the fixed version: http://codepen.io/IPRIT/pen/adaOLj

**Comment by DevVersion** [comment]
When I understand you correctly. This will relate to #6930. So that means the CDN is down, which hosts the `ngMaterial` module for the codepens.

**Comment by IPRIT** [comment]
@DevVersion thank you for paraphrasing :+1:

**Comment by DevVersion** [comment]
Yes, so you should close your issue, because we already have one open. -> #6930

**Comment by IPRIT** [comment]
Duplicate #6930
