### ISSUE TITLE
mdTooltip: [Feature request] Add mdVisibleAlways

### ISSUE THREAD

**Issue by Phr33d0m** [angular/material#7011]
Hi, when building mdFabSpeedDials on the side of a page - most of the time it's useful for the tooltip to stay **always** visible so the user knows what the icons are for at all times. Currently setting mdVisible to ```true``` shows the tooltips, although if the user hovers in and out any of the icons the tooltips disappear.

![tooltip-example](https://cloud.githubusercontent.com/assets/1591486/12785744/3ea53b8c-ca8e-11e5-8d1e-fc56661903a1.png)

A proposed solution to this request is to make ```mdVisibleAlways``` do:

* if ```true```: once the tooltip appears (either by mouse hover or ```mdVisible="true"```) it will never hide unless it's programatically set to false
* if ```false```: it will do nothing to change the current functionality

Regards.

**Comment by ThomasBurleson** [comment]
will not fix.
