### ISSUE TITLE
[Feature-Request] Readonly of md-chips should be separated into CanAdd and CanDelete Attribute

### ISSUE THREAD

**Issue by LisaTatum** [angular/material#7013]
See the image below the assigned subjects of a pupil.

- I do not want that my user can Add a subject there.
- But I want that they can detach/delete a subject

At the moment according to the docs I have to use readonly attribute. But that disables both.

Please separate the readonly into CanDelete and CanAdd Attribute.

![image](https://cloud.githubusercontent.com/assets/13928925/12799221/07add478-cace-11e5-9ab8-d287f3e08c99.png)

**Comment by DevVersion** [comment]
There is a PR pending for that. See #5799

**Comment by ThomasBurleson** [comment]
Duplicate
