### ISSUE TITLE
md-autocomplete parameter to execute function on dismiss

### ISSUE THREAD

**Issue by fernandogomesdf** [angular/material#7016]
md-autocomplete should have a parameter like md-search-dismiss (expression) to allow developers run a function when the user cancel the search. It could be used to hide the autocomplete input field and show only the icon when user cancel the search.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
