### ISSUE TITLE
md-select doubles the clicks for selction

### ISSUE THREAD

**Issue by praskarnam** [angular/material#7017]
The md-select component when used , needs two clicks one to open it and if you have to click on another component then you have to click outside to close the overlay and then again another click for the other component to gain focus. Can this be fixed as applications with real time data , the number of clicks would be doubled and its not usable.

**Comment by topherfangio** [comment]
I believe this has to do with the way our `disabledScrollAround` feature works. We may or may not be able to easily change that, but we'll take a look.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
