### ISSUE TITLE
md-menu-bar: Open/close menu on mouseenter/leave

### ISSUE THREAD

**Issue by websirnik** [angular/material#7018]
Currently in order to initially open the menu, user need to click on the button. In certain cases users would benefit from opening the menu on button's mouseenter and closing it on mouseleave from either the button, or the md-menu-content itself. 
Atm we can't manually add mouseenter/mouseleave triggers as `md-menu-content` get's added the end of the body and it breaks the intended logic.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
