### ISSUE TITLE
md-progress-linear + IOS + incorrect animation 

### ISSUE THREAD

**Issue by 0101adm** [angular/material#7020]
am 1.0.4

can only reproduce on a real iphone.  tested on chrome.

http://codepen.io/0101adm/full/zrJLMg

using md-mode='indeterminate', animation does not work right.

**Comment by 0101adm** [comment]
also appearing in 1.1.0-rc1.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
