### ISSUE TITLE
CodePen examples not working (again)

### ISSUE THREAD

**Issue by camden-kid** [angular/material#7021]
The CodePen examples no longer work. I have flagged this problem before but it continues to occur and even when it is fixed it gets broken at the next release. Could you please make sure that the CodePen examples **always** work and that they are thoroughly tested after each release?

Thank you.

**Comment by ThomasBurleson** [comment]
@robertmesserle - this is on **LATEST** (https://material.angularjs.org/latest/demo/button). **HEAD** is working fine ATM.

**Comment by robertmesserle** [comment]
I think I saw this last night, looks like there's something wrong with the
`docs` CSS file not getting its path updated during release.

**Comment by camden-kid** [comment]
I think it is the same problem as before:

https://material.angularjs.org/{{newVersion}}/docs.css

https://cdn.gitcdn.xyz/cdn/angular/bower-material/v{{newVersion}}/angular-material.js

**Comment by topherfangio** [comment]
This is relevant as well: https://github.com/schme16/gitcdn.xyz/issues/4

Looks like we will need to update our links to use `.link` instead of `.xyz`.
