### ISSUE TITLE
md-sidenav should have a clickOutsideToClose option.

### ISSUE THREAD

**Issue by Grantismo** [angular/material#7022]
There's no easy way to disable the click or Esc to close behavior of the Sidenav. It would be great to have something similar to Dialog's clickOutsideToClose option to disable/enable this behavior.

**Comment by ThomasBurleson** [comment]
In material.angularjs.org, our SideNav is locked open for browser windows > 960px. If you resize below that the SideNav auto-hides. Clicking the button to show the SideNav slides it out and clicking the backdrop will autoclose/hide again. Same with escape.

Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd

**Comment by Grantismo** [comment]
This is a request for a feature entirely different from md-is-locked-open:

When I open the sidenav and click on the backdrop, the sidenav autocloses/hides. I want an attribute on the directive which allows me to disable the autoclose/hiding behavior.

If the navbar is open in this demo, I want to prevent the user from closing the sidenav without clicking on the "Close Nav" button.
http://codepen.io/anon/pen/bExPwW

This behavior is identical to the "Confirm Dialog" in the dialog demo https://material.angularjs.org/latest/demo/dialog

**Comment by DevVersion** [comment]
@ThomasBurleson @Grantismo This can be easily done when #6434 is merged. (just adding `md-disable-backdrop="true"` to the sidenav, will do the trick.

**Comment by Grantismo** [comment]
@ThomasBurleson nice! We'll still need to add logic for disabling the escape key though.

**Comment by EladBezalel** [comment]
This is a dup of #4699
@DevVersion i don't understand why #6434 is related?
Sidenav should simply support clickOutsideToClose

**Comment by DevVersion** [comment]
@EladBezalel With #6434 can be the same achieved as with `clickOutsideToClose`. Combined with #7482, is the user able to disable <kbd>ESC</kdb> too.

**Comment by EladBezalel** [comment]
I think the elegant why is just supporting `clickOutsideToClose` ..

**Comment by DevVersion** [comment]
Ah, I got your thoughts.. It is also aimed to keep the backdrop, but just disable the click outside functionality ;)

**Comment by DevVersion** [comment]
Closing this as a duplicate of #4699
