### ISSUE TITLE
toast: there is no preset we can use as default when we use `$mdToast` service

### ISSUE THREAD

**Issue by PabloRN** [angular/material#7023]
The problem is when we need to use the `$mdToast` service several times. There are some options we don´t need to modify every time we declare the service, as the position or the delay time. So it would be better if we could save default presets in a file.

**Comment by ThomasBurleson** [comment]
Add a ToastProvider to configure presets. A PR would be welcomed.

**Comment by DevVersion** [comment]
Adding presets to the `$mdToast` service is currently possible. You just need to access the `$mdToastProvider` in the `config` function, and then you can start adding your presets.

```js
$mdToastProvider
  .addPreset('testPreset', {
    options: function($mdToast, $mdTheming) {
      return {
        template:
          '<md-toast>' +
          '  <div class="md-toast-content">' +
          '    This is a custom preset ' +
          '  </div>' +
          '</md-toast>',
        theme: $mdTheming.defaultTheme(),
        controllerAs: 'toast',
        bindToController: true
      };
    }
  });
```

So now you can use your preset in a controller for example.
```js
$mdToast.show($mdToast.testPreset());
```

So @ThomasBurleson, seems like there's already a way for defining presets, so for now I suggest documenting the how-to for adding own presets.
