### ISSUE TITLE
md-input-container paddings & margins interfere with md-button in same container

### ISSUE THREAD

**Issue by jmd1921** [angular/material#7024]
Previous to version 1.0.3, the md-input-container would behave normally, as an inline item with no more than one line, aligned with the relative inputs. Now, it breaks the alignment of the other siblings, including md-button and md-datepicker.

http://embed.plnkr.co/ENjcuyZsgGJPNdbVvZyS/

**Comment by pjwalmsley** [comment]
+1

**Comment by DevVersion** [comment]
@topherfangio Can you confirm that this relates to your PR #6209?

**Comment by topherfangio** [comment]
@DevVersion This is indeed related.

**Comment by DevVersion** [comment]
@topherfangio Thanks, would you mind if I assign this issue to you / or close it?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
