### ISSUE TITLE
Images in md-card do not maintain aspect ratio

### ISSUE THREAD

**Issue by jjmschofield** [angular/material#7027]
We are seeing in images in md-card directives do not maintain their aspect ratio, despite having width:100% and height:auto set.

Applying the `overflow:hidden` to the image clears the issue. Fix described by @guzza in https://github.com/angular/material/issues/1230

**Comment by ThomasBurleson** [comment]
Fixed with SHA df902381664bc568ad4011f1747ccc44a856995f
