### ISSUE TITLE
MD-SELECT stays open and un-clickable when pressing it at first in version 1.0.0-rc5 till 1.0.4

### ISSUE THREAD

**Issue by dianagastrin** [angular/material#7028]
All the versions 1.0.0-rc5 till 1.0.4 breaking md-select in my site.(I've checked each of them) It is still unclear how to solve the implemantaion of mdSelect in my site to fit the updated versions.

I suspect this what breaks; "select no longer overflows window, resizes from small to big correctly"(version 1.0.0-rc5)

I hope someone could help me understand how to fix it so I could upgrade to the newest version.
Thank you, Diana.

```html
<md-input-container flex>
    <md-select ng-model="product.paymentCode" name="paymentCode"  md-on-open="loadPaymentCode()" placeholder="Payment Code"  required>
        <md-option ng-value="rPaymentCode" ng-selected="rPaymentCode.id==product.paymentCode.id" ng-repeat="rPaymentCode in paymentCodes">{{ rPaymentCode.code}}</md-option>
    </md-select>
    <div ng-messages="createProductForm.paymentCode.$error" ng-show="createProductForm.paymentCode.$touched">
        <div ng-message="required">choose payment code</div>
    </div>
    <tr-clear model-to-clear="product.paymentCode" ng-if="product.paymentCode"></tr-clear>
</md-input-container>
```

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
