### ISSUE TITLE
Cannot find latest changes in 1.0.5

### ISSUE THREAD

**Issue by jayeshanandani** [angular/material#7031]
Hi,
  Some changes like asterik in input container are not visible as part of 1.0.5 release. Any specific reason behind that?

**Comment by DevVersion** [comment]
Yes, indeed. In the [changelog](https://github.com/angular/material/blob/master/CHANGELOG.md#105-2016-02-04)

**Comment by zbjornson** [comment]
I was confused about this too -- a number of changes tagged with 1.0.5 are in 1.0.5-master___. I don't understand your comment, @DevVersion.

**Comment by DevVersion** [comment]
@zbjornson Just confirmed, that there are missing much things in the changelog.

**Comment by ThomasBurleson** [comment]
Angular Material has revised/improved its build processes. To be consistent with semver ideas, we have three (3) types of releases:

*  `major` :  this will be the Angular 2.x efforts maintained in a separate repository called [Material2](https://github.com/angular/material2)
*  `minor`:  aka `master` contains patch commits AND breaking changes and new features
*  `patch`:  non-breaking API, CSS, UX changes

##### Patch Releases

The patch builds (1.0.4, 1.0.5, 1.0.6) are prepared based on commits in the `patch` branch; which contains only non-breaking changes (eg bug fix, some API additions, minimal non-breaking CSS changes ).  We will be building `patch` releases every week.

##### Minor Releases

`master` will remain the daily development branch AND will be the source for the `minor` releases.
Our formal release of `minor` builds is much less frequent; probably 1x / Quarter.

##### Changelog

The Changelog may contain releases for `patch` or `minor`. If you do not see a fix listed in the Changelog but issue has been resolved or PR merged, then those changes will be master available in the next `minor` release.

> for the purposes of Angular Material 1.x, you *could* think of the patch releases as being *minor* changes and the 'minor' releases as being *major* changes.

**Comment by jayeshanandani** [comment]
Thanks that makes it much clear!
