### ISSUE TITLE
New Dialogue with Tab - Top right white line in toolbar

### ISSUE THREAD

**Issue by ganySA** [angular/material#7034]
Hi

With the new update 1.0.5 when a tab is placed within the dialogue. The top right hand side of the dialogue header/toobar has what looks like a 1px white line on it. This strange artifact appears on the demo site. A dialogue without the tab does not seem to have this artifact.

I have not tested other browsers but this is visible in chrome.

![image](https://cloud.githubusercontent.com/assets/3189206/12838568/4478dabe-cbd8-11e5-8de1-23a6c8fa58f6.png)

**Comment by ThomasBurleson** [comment]
I am unable to reproduce in Mac OSX El Capitan, Chrome Version 48.0.2564.97 (64-bit).

*  https://material.angularjs.org/HEAD/demo/dialog
*  https://material.angularjs.org/latest/demo/dialog

**Comment by leocaseiro** [comment]
I have the same one. It happens also at the Angular Material WebSite!

MAC OSX El Capitain 10.11.13
Google Chrome Version 49.0.2623.75 (64-bit)

Angular Material  v1.1.0-rc1 from the website!

I believe it happens in large screen.
I have a GIF to illustrate it: http://recordit.co/51nJeJBZ6Q

**Comment by Arti3DPlayer** [comment]
the same

**Comment by Arti3DPlayer** [comment]
issue with using `class="md-caption"`
