### ISSUE TITLE
md-not-found doesn't work if there is a ng-if on the md-autocomplete

### ISSUE THREAD

**Issue by ramprabhuj** [angular/material#7035]
There is some caching behavior on the MDAutoComplete controller which assumes the element() object will be the same in the lifecycle. This makes the check for ctrl.hasNotFound being reported as undefined. seems like this check should be done with no caching in the link() function and not in the template() function.

http://codepen.io/anon/pen/GoYKOb

**Comment by DevVersion** [comment]
Introduced in 655eb0f053585e24616d3c7c65acc99c0e6f8bed.
