### ISSUE TITLE
md-dialog height incorrectly resized when resizing browser height from small to large

### ISSUE THREAD

**Issue by ismarslomic** [angular/material#7037]
**Steps to reproduce the bug:**
1. Go to http://codepen.io/ismarslomic/pen/BjqjZP
2. Reduce browsers height
3. Press CUSTOM DIALOG button
4. While dialog is still open extend browser height
5. See that md-dialog is not filling new space at the bottom of browser

Tested on Chrome and Safari on OS X

See attached files

<img width="1136" alt="screen shot 2016-02-05 at 14 15 00" src="https://cloud.githubusercontent.com/assets/2174314/12847536/50ec94e8-cc14-11e5-9f52-a152cc2880c6.png">
<img width="1133" alt="screen shot 2016-02-05 at 14 16 07" src="https://cloud.githubusercontent.com/assets/2174314/12847537/51191284-cc14-11e5-9248-655891c17df2.png">

**Comment by ThomasBurleson** [comment]
I am unable to reproduce this with your CodePen. Tested on Mac OSX El Capitan

Safari version 9.0.3 (11601.4.4)
Chrome Version 48.0.2564.97 (64-bit)

**Comment by ismarslomic** [comment]
I have tested with OS X Yosemite 10.10.5. I have same issue with Chrome on Samsung S6 Edge.

Safari: Version 9.0.3 (10601.4.4)
Chrome: Version 48.0.2564.103 (64-bit)

See attached animated GIF
![md-tab](https://cloud.githubusercontent.com/assets/2174314/12867547/8c35572e-ccf0-11e5-9897-054bed08b4a4.gif)

**Comment by DevVersion** [comment]
Yes, can reproduce too. This seems to relate to the backdrop.

**Comment by ismarslomic** [comment]
Thanks, @DevVersion! @ThomasBurleson can you please tag this as a bug?

As @DevVersion already mentioned, a workaround is:
`
md-backdrop{
  height: 100% !important;
}
`

**Comment by DevVersion** [comment]
@ThomasBurleson I would suggest adding an attribute to the md-backdrop, which prevents the `fixed` body check (because of `disableBodyScoll`- as [here](https://github.com/DevVersion/material/blob/a8537e6386e0906db044d1f00a2b82ec59c13570/src/components/backdrop/backdrop.js#L35)).

**Comment by mpiasta-ca** [comment]
+1

I also noticed issues with scroll bars when testing in "iPhone 4" mode, and when you switch between portrait and landscape while the dialog is open. For example, when the main page content is longer than the viewport and then you open the dialog, the dialog tries to disable scrolling in the background. But now if you switch from portrait to landscape, or vice versa, the scroll-block doesn't update properly. 

Especially troublesome if the modal content exceeds viewport height (ie. iPhone 4 in landscape mode), and now you have a scroll-bar for the dialog, as well as another scroll-bar for the body/background. It's really poor usability.

I don't have time to make a demo right now, however.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
