### ISSUE TITLE
iOS: breakpoints not rendering correctly

### ISSUE THREAD

**Issue by carmona** [angular/material#7038]
Before posting here, i've tried the ngMaterial website and a few other apps i've made in this device and it worked fine so this could clearly be my fault, but this particular app won't render properly.

this is my code for this page (partial):
![captura de tela 2016-02-05 as 13 23 36](https://cloud.githubusercontent.com/assets/719314/12850414/ba97aa44-cc0b-11e5-8263-e72dc5a1f748.png)

here's how it looks like on chrome (Mac/Windows/Android):
![captura de tela 2016-02-05 as 13 19 59](https://cloud.githubusercontent.com/assets/719314/12850314/36ec12e8-cc0b-11e5-8c60-27f15e5880a5.png)

and here's a screenshot of how it looks like on an iPhone 6s:
![slack for ios upload png](https://cloud.githubusercontent.com/assets/719314/12850283/0ce39732-cc0b-11e5-8122-41c1d12eb34a.jpeg)

**Fun fact**: when i turn the phone over to landscape and back to portrait, it renders correctly

**Comment by ThomasBurleson** [comment]
Looking at your code sample, you are not using any [ngMaterial Layout API](https://material.angularjs.org/HEAD/layout/introduction) breakpoints. Try using those first... if that does not work, then submit a new issue with a CodePen demo.

*  CodePen template: http://codepen.io/pen?template=bEGJdd

**Comment by carmona** [comment]
thanks @ThomasBurleson i'll give it a try :smile:
