### ISSUE TITLE
fabtoolbar + 1.0.5 changes

### ISSUE THREAD

**Issue by 0101adm** [angular/material#7039]
having issues w/ 1.0.5 fabtoolbar.

can not longer launch dialog from fab item click.  also, it no longer super imposes when it expands into the container. as you see the agent phone and pic are now seeable.

![fabtoolbar](https://cloud.githubusercontent.com/assets/5133412/12853921/f649fe1a-cbf3-11e5-91d9-a2a707397c34.gif)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd

**Comment by ThomasBurleson** [comment]
Closing until a CodePen is provided.
