### ISSUE TITLE
dialog closing animation + 1.0.5 changes

### ISSUE THREAD

**Issue by 0101adm** [angular/material#7040]
dialog does not close to the element (its closing to the menu trigger button and not the menu item). 

the 'opening from' works as normal.

![dialog](https://cloud.githubusercontent.com/assets/5133412/12854172/568ac48e-cbf5-11e5-87fa-3f9cd62b188d.gif)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd
