### ISSUE TITLE
md-subheader + change of height

### ISSUE THREAD

**Issue by 0101adm** [angular/material#7045]
am 1.0.5 
chrome

when container for a subheader changes height (increase), the position of the label is not updated.

to recreate, click the button 'show extra data' and scroll the contents of the list.  you will see the labels incorrectly switching as you scroll.

http://codepen.io/0101adm/pen/MKPpZw

**Comment by ThomasBurleson** [comment]
Working as expected.

**Comment by craigivemy** [comment]
How is this working as expected? - it's the complete opposite!
