### ISSUE TITLE
$mdDialog.prompt should have a defaultValue option

### ISSUE THREAD

**Issue by zbjornson** [angular/material#7046]
I missed this when I made this config...

To be a full replacement for window.prompt, we should be able to provide a default value.

https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt

**Comment by ThomasBurleson** [comment]
PRs welcomed.

**Comment by DevVersion** [comment]
@zbjornson Already working on that? - Don't want to waste your work if already working on it :)

**Comment by zbjornson** [comment]
@DevVersion I can't do it until this weekend, so please go ahead! Thanks for checking :)

**Comment by angular-tools** [comment]
Hi, when will this be merged into the main branch? 

This is a pretty useful feature because it makes the prompt dialogs more useful (like not asking the user where to send the test email again and filling it for him if there is a cookie present, etc).
