### ISSUE TITLE
md-dialog: Tab dialog not showing all tabs before clicking on tab one

### ISSUE THREAD

**Issue by ismarslomic** [angular/material#7048]
Steps to reproduce the bug:
1. Go to http://codepen.io/ismarslomic/pen/BjqjZP
2. Press TAB DIALOG
3. You will only see one tab with label "ONE", but actually it is three tabs
4. When clicking on tab "ONE", tab 2 and 3 is displayed

Tested with Safari and Chrome on OS X

See attached screenshots

<img width="947" alt="screen shot 2016-02-06 at 00 26 39" src="https://cloud.githubusercontent.com/assets/2174314/12862086/8a5e7382-cc68-11e5-865b-277d7c13e9a3.png">

<img width="945" alt="screen shot 2016-02-06 at 00 26 49" src="https://cloud.githubusercontent.com/assets/2174314/12862085/8a32d5a6-cc68-11e5-99e3-debc8ac3d09a.png">

**Comment by ThomasBurleson** [comment]
@robertmesserle - This bug recently manifested; not sure which commit broke this feature.

**Comment by EladBezalel** [comment]
@ThomasBurleson @robertmesserle bc55ac900498648e61da41fc18149403409e8e58 broke it

**Comment by jiffify** [comment]
using google chrome, cannot see third tab in dialog demo. I can see third tab using IE
