### ISSUE TITLE
Changing route in response to md-autocomplete clear creates md-scroll-mask 

### ISSUE THREAD

**Issue by ramprabhuj** [angular/material#7049]
Assign model to $scope.
$watch model.
Create a md-autocomplete, bind to a model, select an value, clear the value.
In the model $watcher, change route.

there will be a stale md-scroll-mask attached to the body.

**Comment by cah-alexsukhodolsky** [comment]
I'm running into a similar issue when using md-menu and changing route on menu-item selection.

**Comment by ramprabhuj** [comment]
This can be easily reproduced in the angular demo page by opening the autocomplete dialog and clicking on any other demo in the left sidebar.
