### ISSUE TITLE
md-chips: adapt to md-input-container

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#7050]
i think it would be good if chips are adapted to `md-input-container` so it could adjust easily with the margin of the form and have a placeholder that would not duplicate when it's inside this container

without the container
![without container] (http://i.imgur.com/IN1djsr.png)

with the container
![with container] (http://i.imgur.com/wbnV60U.png)

in both ways, placeholder is an attribute of autocomplete and it's being used in angular-material version 1.0.3

**Comment by prakashjp123** [comment]
@Nosthertus try using md-no-float in md-input-container. It doesn't display like duplicated. But this might not be the correct solution.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
