### ISSUE TITLE
bug(toolbar): no styling inside toolbars

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#7052]
64911ab71db897e142d93b404ff4d818941f54ab removed a style definition so that `md-accent` and `md-warn` would work in toolbars, but it just removed the special styling for buttons inside toolbars completely

**Comment by EladBezalel** [comment]
Having second thoughts about this issue,
@jelbourn @ThomasBurleson take a look at this [codepen](http://codepen.io/EladBezalel/pen/EPdQQo) i don't see anything wrong.

**Comment by jelbourn** [comment]
I think it has to do with the theme. I'll follow up with an example.

**Comment by EladBezalel** [comment]
@jelbourn are you fine with closing this?

**Comment by jelbourn** [comment]
Sorry, this fell off my radar. I will track down that example as soon as I can.

**Comment by EladBezalel** [comment]
closed due to inactivity
