### ISSUE TITLE
md-datepicker: Date not updated on model updates

### ISSUE THREAD

**Issue by dratchkov** [angular/material#7054]
Hi,

The date display is not getting updated when the model value is updated externally. See fiddle [here](https://jsfiddle.net/hd7fd325/4/).

Is there a workaround for this?

Thanks,
-dave

**Comment by DevVersion** [comment]
Hey @dratchkov,

You can find more information on a previous tracked issue on AngularJS https://github.com/angular/angular.js/issues/13224

**Comment by dratchkov** [comment]
Thanks @DevVersion!
