### ISSUE TITLE
IE11 md-card demo messed up

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material#7061]
Version 1.0.5
The demo page for [md-card](https://material.angularjs.org/latest/demo/card) is really messed up if you open it in IE11. Probably has to do with flex issues in IE.

**Comment by DevVersion** [comment]
Just a little screenshot, for non-IE11 users

![](https://i.gyazo.com/dcf3c574ea4df2cd54c9e64dec1ebb08.png)

**Comment by corentin-gautier** [comment]
+1

**Comment by topherfangio** [comment]
It looks like this has been broken since we added new demos in v1.0.0.

@EladBezalel Do I recall correctly that you added these demos? If so, did you notice the issues on IE?

**Comment by BigEgg** [comment]
Still happened in current demo site, could you reopen this one?

**Comment by topherfangio** [comment]
@BigEgg I believe we have an issue with the current HEAD of the docs site pointing to 1.0.5 instead of master, so the site may not have the latest code.

**Comment by BigEgg** [comment]
@topherfangio Got it, thanks
