### ISSUE TITLE
Md-avatar/md-item-list inside virtual repeater display problems

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7064]
It appears that v1.0.5. created some problems with displaying avatars when scrolling.

On first render, virtual repeater will show all avatars, but when scrolling some avatars will not be displayed even tho they are fetched (scrolling + watching network tab in chrome confirmed it)

When checking css of md-avatar after rendering, i'm noticing that height is set to 0 !! 
By adding style="height:40px !important" to md-avatar img tag, this problem is fixed..but it's a nasty hack.

**Comment by DevVersion** [comment]
Can you provide a codepen?

**Comment by ThomasBurleson** [comment]
No CodePen provided.
