### ISSUE TITLE
Text overflow not working on h3,h4 in md-list-item

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7065]
Text overflow is not working on md-list-item on h3,h4.

http://codepen.io/anon/pen/jWQNab

**Comment by DevVersion** [comment]
Just want to say, this isn't related to bb5c10575aeb439a5dc33001ac674fd1611f85ef and 3ffa0a2b9d45e648d9d50df679d46310519995b0

**Comment by DevVersion** [comment]
@gpopovic Created a PR for your issue #7272.

Here a little screenshot, how the overflow will look after the PR

![](https://i.gyazo.com/d4c306811fe72879600b9931c59ad714.png)
