### ISSUE TITLE
md-data-table full height

### ISSUE THREAD

**Issue by cskiwi** [angular/material#7069]
Hi,

I'm trying to make the md-data-table full height, because in my current setup it's causing 2 scrollbars to apear,

![image](https://cloud.githubusercontent.com/assets/847540/12883492/ae7f6f7c-ce58-11e5-964c-ccb8fd6ea701.png)

but I can't seem to make it full size: it keeps adding the scrollbar

    <md-card flex="100">
        <div id="filter">
            <md-chips ng-model="ctrl.chips" chip-bar md-component-id="landingFilter">
            </md-chips>
        </div>
        <md-toolbar class="md-table-toolbar md-default">
            <div class="md-toolbar-tools">
                <h2>Values</h2>
            </div>
        </md-toolbar>

        <md-table-container>
            <table md-table md-row-select ng-model="ctrl.selected" md-progress="ctrl.promise">
                <thead md-head md-order="ctrl.query.order" md-on-reorder="onReorder">
                <tr md-row>
                    <th md-column md-numeric md-order-by="id">
                        <span>ID</span></th>
                    <th md-column md-order-by="name">
                        <span>Name</span></th>
                    <th md-column md-order-by="info">
                        <span>Info </span></th>
                    <th md-column md-order-by="info2">
                        <span>Info 2</span></th>
                    <th md-column md-order-by="info3">
                        <span>Info 3</span></th>
                    <th md-column style="width: 100px;">
                        <span></span></th>
                </tr>
                </thead>
                <tbody md-body>
                <tr md-row md-select="value" md-select-id="{{value.name}}" md-auto-select ng-repeat="value in ctrl.values">
                    <td md-cell>{{value.id | number: 1}}</td>
                    <td md-cell>{{value.name}}</td>
                    <td md-cell>{{value.info}}</td>
                    <td md-cell>{{value.info2}}</td>
                    <td md-cell>{{value.info3}}</td>
                    <td md-cell>
                        <md-button ui-sref="app.values.detail({id: value.id})" class="md-icon-button" aria-label="Goto detail">
                            <md-icon>forward</md-icon>
                        </md-button>
                    </td>
                </tr>
                </tbody>
            </table>
        </md-table-container>

        <md-table-pagination md-limit="ctrl.query.limit" md-page="ctrl.query.page" md-total="{{ctrl.values.pagination.total}}" md-on-paginate="ctrl.onPaginate" md-page-select></md-table-pagination>
    </md-card>

how would you make it that the md-data-table becomes the full height (and thus no scrollbar on the value list) and by that making the md-card bigger?

**Comment by DevVersion** [comment]
Hey,

I'm a bit confused. In `angular/material` we don't have a `md-data-table` component yet. 
So you need to look for the actual project and file the issue there.

Or in general you can ask your question in the [ngMaterial Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by cskiwi** [comment]
@DevVersion ow indeed wrong github, srry you can delete this

**Comment by sorb999** [comment]
it is continuously giving me warning of 'ARIA: Attribute " aria-label ", required for accessibility, is missing on node:' please give me a solution for everywhere to hide/remove this warning..
