### ISSUE TITLE
Menu callbacks

### ISSUE THREAD

**Issue by Inuart** [angular/material#7070]
Can you please add callbacks to the `md-menu` element? Maybe like `md-on-remove` for chips?

**Comment by DevVersion** [comment]
@Inuart Ah, you mean something like `md-on-close`, which should be called when the menu is closing?

**Comment by Inuart** [comment]
@DevVersion Yes. And maybe without having to `$watch`

**Comment by Inuart** [comment]
$scope.$on("$mdMenuClose", function() { console.log("menu closing") });
