### ISSUE TITLE
ng-messages pushing the others elements down

### ISSUE THREAD

**Issue by felipemeirelles** [angular/material#7072]
Is this the desired behavior?
if not, the css is lacking of a
`
md-input-container [ng-messages] {
    float: left;
}
`

**Comment by topherfangio** [comment]
Can you please provide a Codepen demo of the issue you are facing.

**Comment by felipemeirelles** [comment]
Here it goes.
http://codepen.io/anon/pen/YwdBVr
I think material design states the same in its error displaying definition. Just don't know if this is the best solution (if you have multiple errors, for example, the next fields on the form would be pushed anyway.)

**Comment by topherfangio** [comment]
Thanks for the demo; definitely seeing the issue. The errors should only push down if there is more than one line of text, or more than one error. By default, we "preallocate" enough space for a single message. 

However, it looks like something changed/broke in 1.0.4. We'll dig in to find the regression.

**Comment by topherfangio** [comment]
Looks like it was introduced in 0c87f0897253e79513e8d3f45687a43a8ff73fb5 by changing `element.after(errorsSpacer)` to `element.parent().append(errorsSpacer)`. Digging in now to see if we can find a fix that works for both issues.
