### ISSUE TITLE
mdMenu + mdOffset: specifying an x-axis offset has no effect

### ISSUE THREAD

**Issue by nfriend** [angular/material#7073]
According to [the documentation](https://material.angularjs.org/latest/api/directive/mdMenu), the position of a `md-menu` can be fine-tuned using the `md-offset` directive.  However, giving this directive a value for the x-axis parameter, i.e. `md-offset="100 0"` has no effect.  Here is a fiddle demonstrating this behavior:

https://jsfiddle.net/NathanFriend/2cekvdeL/

The y-axis parameter works as expected.

In addition, [the documentation](https://material.angularjs.org/latest/api/directive/mdMenu) reads:

> For example, to move a menu by `2px` from the top, we can use:
> `<md-menu md-offset="2 0">`

The example should instead show:
> `<md-menu md-offset="0 2">`

since `md-offset` parameters are specified as `x y`, not `y x`.

Additional information:
Angular Material Version: 1.0.5
Angular Version: 1.4.9
Browser and OS: Chrome 48.0.2564.103 m (64-bit) on Windows 8.1

**Comment by DevVersion** [comment]
@nfriend You already reached the end of `x-axis`. So try using `-100` to demonstrate the `md-offset` behavior. 

See using `-100`: https://jsfiddle.net/3ufcpq4c/

**Comment by nfriend** [comment]
Thanks, @DevVersion.  I wasn't expecting the control to enforce a maximum value on the x-axis.

**Comment by IgorMilosavljevic** [comment]
The [documentation](https://material.angularjs.org/latest/api/directive/mdMenu) still shows a wrong example on what value controls which offset axis. 

> For example, to move a menu by 2px from the top, we can use: 
`<md-menu md-offset="2 0">`

The first value specifies the X axis offset (left/right), while the second takes care of Y axis (top/bottom).
So I just requires a minor change:

> For example, to move a menu by 2px from the top, we can use: 
`<md-menu md-offset="0 2">`
