### ISSUE TITLE
md-autocomplete binding to md-items

### ISSUE THREAD

**Issue by postama** [angular/material#7074]
Binding md-autocompletes md-items to an empty array or object, then clicking into md-autocomplete will cause md-autocomplete to not function property even after md-items are populated until a reload.

http://codepen.io/anon/pen/Gowjmv?editors=1010

**Comment by DevVersion** [comment]
@postama You are not specifying an array. (`  $scope.autocompleteItems = {};`)
- This is a JSON-Object which will be detected as a promise (so the autocomplete thinks this is an async request)

So, you should fix this by changing `{}` to `[]`, which is an empty array.

Demo with the fix: http://codepen.io/DevVersion/pen/vLQQvO?editors=1010

**Comment by postama** [comment]
@DevVersion 

Thanks for your response. This bug happens if you initialize the `$scope.autoCompleteItems` with all Javascript types except array. Should it maybe have different detection on whether or not it is a promise? Either way, I don't think the control breaking and requiring a reload to fix a great experience. I would expect it to not work with bad values, but as soon as it holds good values (an array) I would expect it to work.

**Comment by DevVersion** [comment]
@postama Just created a PR, works great now :+1:

**Comment by postama** [comment]
@DevVersion Great, thanks for your help!
