### ISSUE TITLE
md-select throws "Cannot read property 'selectedLabels' of undefined", suggest existence check first

### ISSUE THREAD

**Issue by jaGarcia** [angular/material#7079]
Occurred in 1.0.4 and 1.0.5 that I've tested.

I have a function that updates the div the md-select is in with HTML pulled from the server.  It looks like the old DOM element is being swapped out before this latent function fires.  Suggest perhaps checking the existance first:

```js
    function announceClosed(opts) {
      var mdSelect = opts.selectCtrl;
      if (mdSelect) {
        var menuController = opts.selectEl.controller('mdSelectMenu');
        **if(menuController) {**
             mdSelect.setLabelText(menuController.selectedLabels());
             mdSelect.triggerClose();
        **}**
      }
    }
```

**Comment by topherfangio** [comment]
Any chance you can provide a Codepen demo of how you are getting the error? It's definitely an easy fix, but I'd like to write a test to go with it, and the demo would certainly help.

**Comment by jaGarcia** [comment]
I gave it a quick shot but can't seem to trigger it :(
http://codepen.io/anon/pen/VeqWxO

If you go [here](https://www.goodshuffle.com/search/results) and click "Sort $ High to Low" you'll see it trigger the error.

I know it's not what you need to implement/write a test, but maybe you'll see something I don't...

I'm hitting my server, pulling HTML fragment, and then "compiling" it on the front end to enable the angular components in the fragment to be enabled

**Comment by topherfangio** [comment]
@jaGarcia Thanks for the link. I will try to dig in soon and see if I can write a failing test.

**Comment by gigadie** [comment]
I had the same issue today for the first time. Upgrading to 1.0.5

**Comment by dohomi** [comment]
+1

**Comment by bluebirdtech** [comment]
+1

**Comment by patrickmichalina** [comment]
:+1:

**Comment by dlochynski** [comment]
+1

**Comment by zacol** [comment]
+1

**Comment by rainabba** [comment]
I'm still seeing this. For each md-select, I get the following logged to the console:

```
ARIA: Attribute " aria-label ", required for accessibility, is missing on node: 
<md-select ........>
```

```
TypeError: Cannot read property 'nodeName' of undefined
```

**Comment by GavinSong123** [comment]
+1

**Comment by Splaktar** [comment]
@rainabba that is a separate issue. It looks a little like https://github.com/angular/material/issues/10546, but that one is for `md-radio-button` and does not have a CodePen demo. Can you please open a new issue with a CodePen reproduction?

@GavinSong123 Please 👍 the OP if you want to vote for an issue. Please avoid posting `+1` comments. Also since this issue is closed, please open a new issue if you are seeing a problem and provide a CodePen reproduction.
