### ISSUE TITLE
mdSubheader right margin CSS property causes gap

### ISSUE THREAD

**Issue by mlibby** [angular/material#708]
I have an mdContent that contains a few sections, each with mdSubheader. 

As I scroll content up and the subheader sticks, the subheader's `margin-right` css property causes the content under the subheader to show in a small strip along the right side. It seems like this should be `padding-right` instead.

![screen shot 2014-11-20 at 10 23 47 am](https://cloud.githubusercontent.com/assets/36049/5128222/752628f0-709f-11e4-9061-4755313ba8f1.png)

**Comment by EladBezalel** [comment]
It seems that the sub header have [16px margin right](https://github.com/angular/material/blob/d06b1936171fb0a7a7578e40f964b1791ac1980a/src/components/subheader/subheader.scss#L33)

Is there a reason for that? should it be padding?

**Comment by srinathvsp** [comment]
hi i have inside md-content subheader sections when i scroll layout moving subheader and stoping on top means above the toolbar wts the mistake pls let me know
