### ISSUE TITLE
migrating angular-material.min.js v0.9.7 to v1.0.5 is not working with  angularJS v1.3.0  however its works fine with  angularJS v1.4.0 , why ? is it not compatible with angularjs  v1.3 ?

### ISSUE THREAD

**Issue by ravivaghela-searce** [angular/material#7080]
HI , i am migrating angular-material.min.js v0.9.7 to v1.0.5 where as i have used angularJS v1.3.0 , Which gives me error
is it compulsory to use angularjs v1.4.0 with angular-material.js v1.0.5 ?

**Comment by websirnik** [comment]
I'm running 1.0.5 with Angular 1.3 without any issues.

**Comment by topherfangio** [comment]
@ravivaghela-searce Make sure you are using the latest 1.3.x version of Angular. There may be some issues with older versions.

What is the exact error you are seeing, and are you using Angular 1.3.0 or a different version?

**Comment by ravivaghela-searce** [comment]
i used 1.3.4, got some dependency issues.. now its resolved and working fine. :) thank you guys
