### ISSUE TITLE
Problem with explicitly sized div, md-content and flex children

### ISSUE THREAD

**Issue by ibachar** [angular/material#7082]
Hi,

I think I've found an issue or at least not able to achieve what I want (ver 1.0.1):
http://codepen.io/anon/pen/VeVyZv

I want to have a list of several elements laid out horizontally with an explicit width.
The first label should take 30% of the width, the last button should be 15% and the three middle input boxes should evenly fill the remaining space. I can't achieve this using explicit flex percentage since 55 is not dividable by 3.

Thanks

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
