### ISSUE TITLE
$mdDialog doesn't hide

### ISSUE THREAD

**Issue by AndreiSazanovich** [angular/material#7083]
Hi. I have a problem with mdDialog. Dialog appears on error with all data I passed. But when I try to close it on ng-click = closeDialog, nothing happens. 
Here is a code: http://plnkr.co/edit/YAvQVPR6emgRf8gL9xS7?p=catalogue
AngularJS v1.4.7
Angular Material v0.11.4

**Comment by scottmcarthur** [comment]
It's not `$mdDialog.hide();` you need `$mdDialog.cancel();`.

**Comment by tonyawad88** [comment]
@AndreiSazanovich I would recommend using angular material team base codepen and then add your html/js/css to it. https://codepen.io/team/AngularMaterial/pen/RrbXyW

Plus I strongly recommend going to the latest version of Angular Material, there are lots of improvements and more stability.

**Comment by DevVersion** [comment]
I'm not sure, you posted the complete Plnkr?

There are many things:
- No includes for angular, material and your other scripts
- No Angular App initialization in a document element like `<body>` (`ng-app="MyApp"`); 
- A body, which holds the template (using `text/ng-template` or a inline-js template)
- No module creation in the Javascript (`angular.modulue('MyApp')`)
- You create a service from scratch using a unresolved variable (`servicesModule`)

**Comment by DevVersion** [comment]
Closing this, because the demo is completely wrong / invalid. In addition to that, the hiding of a dialog works fine for me. If there are any updates, please let me know!

**Comment by AndreiSazanovich** [comment]
Yes. It was completely another problem. Thanks, guys 

-----Original Message-----
