### ISSUE TITLE
md-sidenav: using md-theme does not set CSS class on sidenav element

### ISSUE THREAD

**Issue by oemmes** [angular/material#7084]
When a theme is defined on a sidebar element the CSS class is not set on that element.

`<md-sidenav md-theme="dark"></md-sidenav>`
should result in
`<md-sidenav md-theme="dark" class="md-dark-theme"></md-sidenav>`

Though the class is set on the (automatically generated) backdrop element, the class is not set on `<md-sidenav>` itself.

As there is the selector `md-sidenav.md-THEME_NAME-theme` in [sidenav-theme.scss](sidenav-theme.scss) I think the class should be automatically assigned to the sidebar element, too.

Codepen: http://codepen.io/anon/pen/YwRjNb
Angular Material version: 1.0.5

**Comment by DevVersion** [comment]
This should relate to #5868 @EladBezalel

**Comment by DevVersion** [comment]
@oemmes Nice catch :+1: - definitely an issue - Fixed in #7374
