### ISSUE TITLE
mdAutocomplete -  not found is not displaying

### ISSUE THREAD

**Issue by gilnoy** [angular/material#7085]
The element i'm getting on the template function  is different from the one im getting on the link function  - resulting by  element.hasNotFound == undefined

 link: function(scope, element, attrs, controller) {
      controller.hasNotFound = element.hasNotFoundTemplate;
      delete element.hasNotFoundTemplate;
    },
    template:     function (element, attr) {
      var noItemsTemplate = getNoItemsTemplate(),
          itemTemplate    = getItemTemplate(),
          leftover        = element.html(),
          tabindex        = attr.tabindex;
      
      // Set our variable for the link function above which runs later
      element.hasNotFoundTemplate = !!noItemsTemplate;
}

**Comment by DevVersion** [comment]
This is a already-known issue. See #7042

**Comment by DevVersion** [comment]
Duplicate issue, can you please close your issue? - #7042
