### ISSUE TITLE
IE11 md-checkbox ng-model-options not working with blur

### ISSUE THREAD

**Issue by maureenvdr** [angular/material#7086]
If I add ng-model-options="{updateOn:'blur'}"  to a md-checkbox it is not updating the ng-model after i click on something else.  It works fine in firefox and chrome, but not in IE11.
You can reproduce this easly using the codepen that can be reached at https://material.angularjs.org/latest/demo/checkbox the one in basic usage, just add ng-model-options="{updateOn:'blur'}" to the first checkbox.

**Comment by DevVersion** [comment]
Yep, can reproduce. Here a little demo to compare with the native checkbox (which works :+1:) and the  `<md-checkbox>` http://codepen.io/DevVersion/pen/KVrGLM
