### ISSUE TITLE
FAB icon offset with ui-sref instead of ng-click

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#7087]
Using `md-fab-trigger` with `ui-sref` instead of `ng-click` breaks the icon alignment. Works in 1.0.5 but not on master but I can't quite pin it down to a commit.

`ui-sref` becomes an anchor while `ng-click` becomes a button.

```
md-fab-trigger
    md-button.md-fab.md-primary(aria-label="foo" ui-sref="foo.bar")
        md-tooltip(md-direction="left") Foo
        md-icon(md-svg-icon="editor:mode_edit")
```

**Comment by topherfangio** [comment]
This doesn't appear to be limited to the speed dial, it looks like it is affecting all FABs: http://codepen.io/topherfangio/pen/eJbWPd?editors=1000

Notice how the Cake FAB in the demo above is offset because I added the `ui-sref` attribute. Still trying to track it down.

**Comment by topherfangio** [comment]
Appears to be related to this commit: https://github.com/angular/material/commit/b70234e38c96fdf893e6562569765143c456307b

@DevVersion Can you explain why you removed the FAB's `line-height` in the above commit? I don't see anything in the commit message about it and it's causing this issue. Might need to revert that change, but wanted to make sure it wasn't fixing something else.

**Comment by DevVersion** [comment]
@topherfangio That wasn't me, seems that Thomas modified the commit. Sorry

**Comment by kuhnroyal** [comment]
Nice find. I messed around with the dev tools for an hour and didn't locate it. Silly me.

**Comment by topherfangio** [comment]
@DevVersion Thanks for the info; I'll touch base with @ThomasBurleson to get this thoughts.

@kuhnroyal I too messed around in the dev tools for a while and didn't find it. I finally just looked at the history of the `button.scss` figuring it would have been changed and found it :smile:

**Comment by topherfangio** [comment]
Talked to Thomas, it appears that removing this line fixed an issue with the FABs on the tooltip demo. We discussed re-adding this line and figuring out a different way to fix the tooltip issue. I am investigating now.

**Comment by DevVersion** [comment]
@topherfangio Okay great! :+1: Thanks
