### ISSUE TITLE
mdSlider: Left-most value for discrete slider shouldn't be hollow

### ISSUE THREAD

**Issue by apokusin** [angular/material#7093]
Discrete sliders shouldn't have a hollow visual design when at left-most value.

Example from Angular Material `1.0.5`:
![Screenshot](https://d.pr/145PR.png)

[Material Design Spec](https://www.google.com/design/spec/components/sliders.html#sliders-discrete-slider)

Example from Material Design Spec:
![Screenshot](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7dEtQQ2s4VUZxZG8/components_sliders_discrete1.png)

**Comment by DevVersion** [comment]
I bet this is already fixed in #6538 :smile: Can you confirm?
cc @EladBezalel

**Comment by EladBezalel** [comment]
Yep :)

**Comment by ThomasBurleson** [comment]
Fixed with SHA e0abeb4dc46a1753616a911fe54f14d8f1148a25
