### ISSUE TITLE
md-select does not show optgroup label when there are lots of md-options

### ISSUE THREAD

**Issue by stormageddon** [angular/material#7095]
When I populate an md-select with an md-optgroup that contains lots of options, the dropdown automatically scrolls down to the first option and hides the optgroup label. This makes it difficult to tell that there may be multiple sections to the dropdown.

Here is a [demo](https://jsfiddle.net/03t8qkeL/) using md 1.0.5 that shows the issue.

**Comment by DevVersion** [comment]
That's related to the following snippet (See [here](https://github.com/DevVersion/material/blob/9179c61906d1174ed3487daee5e29ae03928317c/src/components/select/select.js#L1372-L1372)).

**Comment by stormageddon** [comment]
So it this working as intended then? It seems counterintuitive to me to scroll past the optgroup label.

**Comment by DevVersion** [comment]
I don't think this is by intention. We should get more information about the referenced snippet, and of the desired behavior.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
