### ISSUE TITLE
toast: Text wrapping on mobile

### ISSUE THREAD

**Issue by dansanderson** [angular/material#7096]
https://www.google.com/design/spec/components/snackbars-toasts.html#snackbars-toasts-specs

<img width="466" alt="screen shot 2016-02-09 at 2 34 28 pm" src="https://cloud.githubusercontent.com/assets/408973/12932941/5e34c250-cf3a-11e5-984c-48a91665e0d2.png">

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
