### ISSUE TITLE
mdTabs: tab items overflows md-tabs-canvas on Chromium (wraps tabs under bar)

### ISSUE THREAD

**Issue by JonathanMontane** [angular/material#7103]
**Angular version:** v1.0.3

**Overview:**

In Chromium, element.offsetWidth is truncated to the nearest integer, which results in a shorter computed width than expected (by the function updatePagingWidth).

**Browser/OS:**
Chromium (Version 47.0.2526.106 Ubuntu 15.04)
[discussion ](https://code.google.com/p/chromium/issues/detail?id=512307) on a related issue in code.google.com.
[jsfiddle](http://jsfiddle.net/sbel/sykrLf2u/6/) showing the truncature.

**Possible Fix**

change
```
function updatePagingWidth() {
  var width = 1;
  angular.forEach(getElements().dummies, function (element) {
    width += Math.ceil(element.offsetWidth);
  });
  angular.element(elements.paging).css('width', width + 'px');
}
```

to:

```
function updatePagingWidth() {
  var width = 1;
  angular.forEach(getElements().dummies, function (element) {
    width += Math.floor(element.offsetWidth)+1;
  });
  angular.element(elements.paging).css('width', width + 'px');
}
```

`Math.ceil()` and `Math.floor()+1` have identical behaviors except for the case where the width is an integer,which is currently causing an issue.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
