### ISSUE TITLE
Support asterisk on input with `ng-required` in the same way as with `required`

### ISSUE THREAD

**Issue by kuhnroyal** [angular/material#7105]
Currently only `<input required>`is support but a lot of uses involve `<input ng-required="foo.bar">`.

**Comment by DevVersion** [comment]
Thanks for the extra issue. Now working in #6803 :)

![](https://i.gyazo.com/fd86449420c6f1a150f7193df0638156.gif)

**Comment by kuhnroyal** [comment]
Nice job!
