### ISSUE TITLE
$md-autocomplete scroll keeps the last known position

### ISSUE THREAD

**Issue by gilnoy** [angular/material#7106]
scroll  position doesn't change when i get different results - if i scrolled to the bottom of the results list, type a different search, the scroll stays at the bottom instead at the top

**Comment by kevintc** [comment]
The same happens here, I use the auto-complete in a modal, if I don't select an item, close the modal and reopen it, the following happens :
- the search field is empty
- the list is reset to the first position
- the scroll keeps the last known position (and is not reset to default top)

**Comment by gilnoy** [comment]
Added:

positionDropdown() {
.....
elements.$.scroller.scrollTop(0);
$mdUtil.nextTick(correctHorizontalAlignment, false);

...
}

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ramyagithub-1** [comment]
Hi @topherfangio,

I can still see this issue in angular 1.1.4. 
$md-autocomplete scroll still keeps the last known position
