### ISSUE TITLE
bug(md-select): overlapping labels just after deselect

### ISSUE THREAD

**Issue by kamilkisiela** [angular/material#7108]
**Reproduction steps:**
 > 1. Create md-select with **multiple** selection
 > 2. Select at least one option
 > 3. Click outside md-select to close it
 > 4. Then open it again
 > 5. Deselect all
 > 6. Click outside md-select again *(it backs to just one label on second click)*

[Reproduction on codepen](http://codepen.io/kamilkisiela/pen/dGwXWa)

**Looks like this:**
![Grrr](http://i.imgur.com/H4yvcUy.jpg)

It happens on `chrome`, didn't check other browsers.

Related version of `angular-material`: **v1.0.5**

**Comment by DevVersion** [comment]
@kamilkisiela Already fixed in `master`. Here a demo using `master` ([Codepen](http://codepen.io/DevVersion/pen/rxoWBN))

**Comment by kamilkisiela** [comment]
@DevVersion Oh, that's nice :) I didn't find related issue on it.

Could you point to me a commit with fix of that issue?

**Comment by DevVersion** [comment]
@kamilkisiela Uff, that was really complicated to find the right commit. Resetting HEAD all time :stuck_out_tongue_winking_eye: 
- Before this commit it won't work: fd46483c02219795a200adec83a2f2803accfc39
- May relate to the `input-container`

**Comment by kamilkisiela** [comment]
@DevVersion 
I think it's related to `md-input-focused` (if I remember the class name correctly).

The "focus class" drops off after the second click but stays until it happens.

**Comment by DevVersion** [comment]
@kamilkisiela Yes, can be true, but in general just meant that it relates to the `container`, not to the `input` directive. 

So as I said, this is fixed in `master`.

**Comment by kamilkisiela** [comment]
Ok then, thanks again :+1:

**Comment by DevVersion** [comment]
No problem :wink: Would be great if you close your issue :smile:
