### ISSUE TITLE
Firefox: can't check on checkbox in the md-list-item

### ISSUE THREAD

**Issue by JA44** [angular/material#7109]
This codepen: http://codepen.io/anon/pen/VeqKqP

On firefox, when I click on one checkbox, the ng-click doesn't trigger and i can't check the checkbox. Only the ng-click on the md-list-item triggers. The console returns only "clickList" instead of "clickCheckbox" and "clickList"

It should propage the click event at this children

On chrome, this works fine.

**Comment by DevVersion** [comment]
Already fixed in `master` in bb5c105 - #6493

**Comment by JA44** [comment]
thanks, it's good with master.

**Comment by DevVersion** [comment]
Yea, can you please close your issue?
