### ISSUE TITLE
md-select doesn't line up with other input elements

### ISSUE THREAD

**Issue by eneufeld** [angular/material#7110]
The issue #2793 is still there if the md-select is wrapped in a ng-transclude element.
The css selector for aligning md-select inside md-input-container is "md-input-container > md-select" but for all other input elements it is "md-input-container .md-input"

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
