### ISSUE TITLE
md-[datepicker-]calendar table elements are dependent on browser defaults

### ISSUE THREAD

**Issue by conniew** [angular/material#7111]
Particularly tbody, td, tr rely on the default vertical-align:middle style.
This is incompatible with popular CSS resets that use vertical-align:baseline as the standard, e.g. http://meyerweb.com/eric/tools/css/reset/

Headers are misaligned vertically with vertical-align:baseline
![datepicker screenshot](https://cloud.githubusercontent.com/assets/1839009/12958940/f7b31022-cfe8-11e5-95c4-76cd4dd304fd.png)

md-calendar-specific table element rules with vertical-align:middle would make this less fragile

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
