### ISSUE TITLE
mdDialog: .cancel() resolves dialog promise

### ISSUE THREAD

**Issue by trevorhreed** [angular/material#7112]
Version: 1.0.5
Chrome 48
Mac OS X
See this example to reproduce: http://codepen.io/trevorhreed/pen/xZmdjr?editors=1010

**Calling $mdDialog.cancel() resolves the promise from $mdDialog.show() when a second dialog is triggered before calling $mdDialog.cancel()**

I have a dialog in which I attempt to make an ajax request when the user clicks a dialog action button. If the ajax request fails, I send the error through my application's error handling service, which in turn causes another dialog to open and display the error. After sending the error to the application's error handling service, I try to call $mdDialog.cancel(), so that the dialog's promise will be reject and no more action will be taken by the calling controller. However, after triggering the second dialog box, calling $mdDialog.cancel() causes the dialog promise to resolve successfully.

**Comment by jrandeniya** [comment]
+1 in v1.5.0-rc.2 as well.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
