### ISSUE TITLE
"Getting started" CodePen is missing <meta> tag

### ISSUE THREAD

**Issue by jelbourn** [angular/material#7113]
The CodePen on [the getting started page](https://material.angularjs.org/latest/getting-started) should include the following:
```html
<meta name="viewport" content="initial-scale=1">
```

We should also probably link this as a resource on the getting started page:
[Responsive web design basics
](https://developers.google.com/web/fundamentals/design-and-ui/responsive/fundamentals/?hl=en)
@ThomasBurleson I would update it myself, but I don't think I have permissions to that pen.

**Comment by ThomasBurleson** [comment]
@jelbourn - I fixed the CodePen template to include the `<meta>`.  I am not sure how to update the "Responsive Web Design Basics". Assigning back to you.

**Comment by jelbourn** [comment]
@ThomasBurleson I meant update [our "Getting started"](https://material.angularjs.org/latest/getting-started) page to link to the [Responsive web design basics](https://developers.google.com/web/fundamentals/design-and-ui/responsive/fundamentals/?hl=en)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
