### ISSUE TITLE
md-text-float does not set $touched

### ISSUE THREAD

**Issue by ACDN** [angular/material#712]
Using md-text-float in a form is all well and good, but if it doesn't set the appropriate fields on the js form object then it makes them difficult to interact with.

For example, here is the HTML used:

```html
 <md-text-float 
         ng-model="userName" 
         label="User Name" 
         name="userName" 
         required >
</md-text-float>
```

With the name attribute set, there is corresponding property in the js form object called: userName. However, that property has many useful sub properties that are not getting set.  

The HTML attributes are getting correctly assigned to the INPUT element on the dom within the MD-INPUT-GROUP however.

**Comment by ajoslin** [comment]
Fixed via 60fcd6f4d8b895162b37a940c3f33164d8044382
