### ISSUE TITLE
Select acts weirdly in fixed block (Chrome 48)

### ISSUE THREAD

**Issue by Vayvala** [angular/material#7122]
I have created a side block which is `static` by default, but becomes `fixed` when you scroll to some point. And in this block I use Angular-Material select.

CSS:

    .pos-fixed {
	    position:fixed;
    	top: 60px;
	    width:16.5%!important;
    }

    #sidebar-right {
    	float:right;
    	width:23%;
    }
	#sidebar-right #widget {
		width:100%;
	}

HTML:

      <div id="sidebar-right">
        <div id="widget" ng-class="{'pos-fixed': imageHidden}" class="panel md-padding">
          <div>
            <md-input-container style="width:100%">
              <md-select ng-model="number1" placeholder="number 1">
                <md-option ng-repeat="number in ['one','two','three','four','five','six','seven']" value="{{number}}">{{number}}</md-option>
              </md-select>
            </md-input-container>
            <br />
            <md-input-container style="margin-top: 0px;width:100%">
              <md-select ng-disabled="!number1" ng-model="number2" placeholder="numbe 2">
                <md-option ng-repeat="number in ['one','two','three','four','five','six','seven']" value="{{number}}">{{number}}</md-option>
              </md-select>
            </md-input-container>
          </div>
        </div

JS (scroll spy):

    app.directive('scroll', function($window) {
      return function(scope, element, attrs) {
        angular.element($window).bind('scroll', function() {
          if (this.pageYOffset >= 320) {
            scope.imageHidden = true;
          } else {
            scope.imageHidden = false;
          }
          scope.$apply();
        });
      };
    });

Before side-block is `fixed`, Material select works fine, but as soon as you scroll and it becomes `fixed`, select starts to act weirdly in Chrome 48.
GIF: http://recordit.co/i72EaaVxJf
Plunker: http://plnkr.co/edit/lfik78wR2FqPoSFSCNlz?p=preview

**Comment by DevVersion** [comment]
I created a demo myself for your desired behavior. In my case everything works excellent. 
See http://codepen.io/DevVersion/pen/zryJoe

**Comment by Vayvala** [comment]
@DevVersion It work excellent if you **only ** have `select` fixed, when you have a fixed block with `select` in it, it doesn't.

I made a fork of your pen and just replaced select with:

      <div
          ng-class="{'fixed': isFixed}"  
          class="panel md-padding" style="width:200px; background-color:grey">  
            <div>
              <md-input-container style="width:100%"> 
                <md-select ng-model="number1" placeholder="Number 1">
                  <md-option ng-repeat="number in ['one','two','three','four','five','six','seven']" value="{{number}}">{{number}}</md-option>
                </md-select>
              </md-input-container>
              <br>
              <md-input-container style="margin-top: 0px;width:100%">
                <md-select ng-disabled="!number1" ng-model="number2" placeholder="number 2">
                  <md-option ng-repeat="number in ['one','two','three','four','five','six','seven']" value="{{number}}">{{number}}</md-option>
                </md-select>
              </md-input-container>
            </div>
        </div>

Output: http://recordit.co/zTJeRyc1Xu
CodePen: http://codepen.io/anon/pen/jWXePd?editors=1000

**Comment by DevVersion** [comment]
@Vayvala Ah, yes now I see it. That's related to your `scroll` binding, because if you open the select menu, we will disable scrolling for `body` (so `body` becomes fixed etc) that's because the fixed container will move up. So as result we can say this is **not** related to the `mdSelect` service.

I know it's not a elegant solution but that's a logical step. See in my new demo, which checks for the `disabled` scroll.
- http://codepen.io/DevVersion/pen/zryJoe

**Comment by Vayvala** [comment]
@DevVersion It works great now. Thanks for your help.
