### ISSUE TITLE
md-datepicker - parseDate with individual parsing

### ISSUE THREAD

**Issue by wolfHH** [angular/material#7123]
Hi all,
I would like to use parseDate to make a, at first, invalid dateString to a valid one. I.e. let the user enter '020202' for the Second, February 2002. The parse function shall transform it to a valid Date Object representing the 02/02/2002. So far, so cool. Problem in angular-material.js, line 8443: The isValidInput checks just the obviously invalid input-String and due to that denys the update of the model.
I think this behavior is wrong.
Possible solution:
angular-material.js, line 8457: 
    if (isValidInput || (parsedDate!=null && !isNaN(parsedDate))) {
      this.inputElement.value=this.dateLocale.formatDate(parsedDate);
      this.ngModelCtrl.$setViewValue(parsedDate);
      this.date = parsedDate;
    }

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
