### ISSUE TITLE
mdTabs: md-on-select is not evaluated on mdTab

### ISSUE THREAD

**Issue by kingdeim** [angular/material#7126]
Hi,

I would like to use the "md-on-select" attribute on a "md-tab". In my point of view the expression is never evaluated. I tried it at least with an alert statement. It looks as if there is no event fired by selecting a tab.

[https://plnkr.co/edit/r3QMKCFqo30Amq8oKS95?p=preview](https://plnkr.co/edit/r3QMKCFqo30Amq8oKS95?p=preview)

**Comment by Knoxvillekm** [comment]
Use $scope.onTabSelection = ... in JS
or ng-controller="MyTabsCtrl as vm" and vm.onTabSelection in HTML
P.S. alert() not work

**Comment by kingdeim** [comment]
Thank you, I have updated the plunk, works for me.
