### ISSUE TITLE
md-autocomplete triggering an ng-route change makes page unusable

### ISSUE THREAD

**Issue by hweigel528** [angular/material#7128]
I'm running into a few issues when using an autocomplete list which triggers a $location.path() call on an md-selected-item-change.

Fiddle: http://jsfiddle.net/999t17Lw/12/

note that when selecting B or C, the page gets successfully routed, but then nothing can be interacted with due to an md-scroll-mask.  The hacky workaround of adding $mdUtil.enableScrolling() to the controller allows the page to be usable upon routing, but the autocomplete directive becomes useless on the new page.

**Comment by jelbourn** [comment]
@robertmesserle This seems like something that could be handled by cleaning up the scrolling state on route change.

**Comment by cah-alexsukhodolsky** [comment]
I'm running into a similar issue when using md-menu and changing route ($state.go) on menu-item selection.
