### ISSUE TITLE
layout: Column Child Elements Not Always max-width="100%"

### ISSUE THREAD

**Issue by kyleguate** [angular/material#7130]
**Expectation**
That the children of `layout="column"` are styled with `max-width="100%"`
regardless of what child perpendicular alignment is set to. Documentation sources are:
[Layout Containers](https://material.angularjs.org/latest/layout/container)
[Child Alignment](https://material.angularjs.org/latest/layout/alignment)

**Actual**
[JS Fiddle](https://jsfiddle.net/322j5oxn/3/)

**Example 1** shows child elements full-width, with `layout-align="center"`

**Example 2** is exactly the same as Example 1 with the only change being `layout-align="center start"`
The child elements are not full width as expected per documentation.

**Resolution**
Either the documentation needs some clarification or there is a bug.

**Comment by sahilanguralla** [comment]
I am also facing the same issue. Please fix it fast. Thanks.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
