### ISSUE TITLE
Github links for some API docs are broken

### ISSUE THREAD

**Issue by jelbourn** [angular/material#7131]
For example: https://material.angularjs.org/latest/api/service/$mdInkRipple
The github links points to
```
https://github.com/angular/material/blob/master/src/components/gle/home/jelbourn/ng-material/src/core/services/ripple/ripple.js
```

Cause:
The fuction `publicDocData` in `componentData.js` just checks whether the docType is `"directive"`. And, if so, assume the thing will live under `components/`. But ripple (and a few other things) are marked as `directive` and live in `core/`. So an `indexOf` check on my local path, while cutting a release, messes up. E.g., the path to the file is
```
/usr/local/google/home/jelbourn/ng-material/src/core/services/ripple/ripple.js
```
And the substring is removing everything up to `goo` instead of everything up to `core/`

Thanks to @petebacondarwin for pointing this out.

**Comment by DevVersion** [comment]
@jelbourn Can you please take a look at #7319?
