### ISSUE TITLE
Does Angular Material load somehow the Roboto font or i should import it?

### ISSUE THREAD

**Issue by vapits** [angular/material#7133]
I'm quite confused as i see in scss that for nt called multiple times but i cannot find in build @import or something similar.

**Comment by DevVersion** [comment]
@vapits Yes, by default Angular Material isn't injecting the Roboto font.
It uses the most time the following font defintion for components
-  `font-family: Roboto, "Helvetica Neue", sans-serif;`

So you should include `Roboto` yourself because otherwise it will use `Helvetica Neue`

**Comment by vapits** [comment]
I think this should be included to the docs.

Thx @DevVersion

**Comment by DevVersion** [comment]
@vapits Yes that's a good idea, please reopen the issue, so the team can track it.
