### ISSUE TITLE
<md-fab-toolbar> Is there a way to change the color of the toolbar to be different to the button color?

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#7134]
See cleaner [demo](http://codepen.io/cmacdonnacha/pen/PZVqXx) for example. 

Is there an easy way (i.e not having to override css) to change the color of the toolbar or will it always be the same color as the button?

So I want the button to be one color, but the toolbar to be another color.

**Comment by topherfangio** [comment]
Unfortunately, due to the way the component is built, there is no way to specify a different color for the toolbar; it is something we want to add eventually, but it is a lower priority. If you are interested in submitting a PR to add this functionality, it would be welcomed!

**Comment by cmacdonnacha** [comment]
@topherfangio Thanks for that!

**Comment by ThomasBurleson** [comment]
👍

**Comment by matze1234** [comment]
+1 
In a lot of apps (e.g. whatsapp, google-music) when you hit  the search-icon, a white toolbar slides out. Would be great if this will be possible with md-fab-toolbar.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
