### ISSUE TITLE
<md-fab-toolbar> inside <md-toolbar> Is it possible to have the <md-fab-toolbar> fill the height of <md-toolbar> when custom height is used?

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#7135]
See [demo](http://codepen.io/cmacdonnacha/pen/vLbNOz).

I have an <md-toolbar> in which I have placed an <md-fab-toolbar>. I overridden the css to set the height of <md-toolbar> to 50px. Is there a way to tell <md-fab-toolbar> to just fill the height of it's parent?

Thanks,
Cathal.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by fabienmoyon** [comment]
Hello @ThomasBurleson are you sure? I always have the problem...
See [demo](https://codepen.io/fabienmoyon/pen/JMVqyJ )

**Comment by Splaktar** [comment]
This can be done with some custom CSS. Here is a [CodePen](https://codepen.io/Splaktar/pen/XZRXLa) that demonstrates this.
