### ISSUE TITLE
prevent closing the fabSpeedDial from closing when clicking on a md-fab-action

### ISSUE THREAD

**Issue by reinos** [angular/material#7137]
On the fabSpeedDial I have 3 actions. On every action I open a popup or a popover. The default behaviour of the fabSpeedDial is that it close himself after clicking on one of the md-fab-actions. 

Is there a way to avoid closing the fabSpeedDial on some action? in my case the fabSpeedDial needs te be open when i click on an action.

**Comment by ThomasBurleson** [comment]
Not supported.
