### ISSUE TITLE
<md-icon> inside <md-input-container> overlaps floating label

### ISSUE THREAD

**Issue by rolandjitsu** [angular/material#7139]
It looks like with the `1.0.5` release, if using:
```html
<md-input-container class="md-icon-float md-block">
    <!-- Use floating label instead of placeholder -->
    <label>Name</label>
    <md-icon md-svg-src="img/icons/ic_person_24px.svg" class="name"></md-icon>
    <input ng-model="user.name" type="text">
</md-input-container>
```
The icon overlaps the floating label. Inspecting the element shows that the class `md-icon-left` is missing from `<md-input-container>`, but there is another class added `md-has-icon` (or something like that), which has no side effects.

**Comment by DevVersion** [comment]
I can't reproduce that. Can you provide a codepen or something else?

**Comment by rolandjitsu** [comment]
I cannot reproduce either in a codepen. It might be because of something specific to the project I use this in. I'd better close this.

**Comment by AnirudhaGohokar** [comment]
Am facing this same issue after upgrading from 1.0.x to 1.1.x
