### ISSUE TITLE
md-search-text-change is not trigger when adding whitespace

### ISSUE THREAD

**Issue by ThomsCass** [angular/material#7140]
Hi,

In the `md-autocomplete`directive the event `md-search-text-change`is not trigger when we press the space bar.

**Comment by DevVersion** [comment]
Yes, can reproduce. That's cause by Angular's default input directive which trims the ngModel text. (See [here](https://docs.angularjs.org/api/ng/input/input%5Btext%5D)). 
This can be fixed with using the ngTrim attribute on the input.

**Comment by ThomsC** [comment]
Thanks I didn't know that!

 But as for now we can't add ng-trim to the input when I see the issue #4492.

**Comment by bayucandra** [comment]
@ThomsCass Seem we have to make changes directly to the angular-material.js file. I have tried to put the ng-trim at angular-material.js v1.0.7 and it is works.
You can check at line number start from 19891 to 19958. I have add ng-trim="false"\ to both of two conditional case there which i am nut sure what it does, something about 'attr.mdFloatingLabel' which i am not yet check further what is it. In my case the ng-trim="false"\ works for the 'else' block of 'if' conditional case there.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by DenisKot** [comment]
Still this bug in "angular": "1.7.0"

**Comment by Splaktar** [comment]
@DenisKot [support for `ng-trim`](https://github.com/angular/material/issues/4492) was added to `md-autocomplete` in 1.1.2. If you have a question, please post it to the [AngularJS Material forums](https://groups.google.com/forum/?pli=1#!forum/ngmaterial). If you have a bug report and a CodePen reproduction, please open a new issue.
