### ISSUE TITLE
md-not-found won't show when using md-autocomplete in ng-repeat scopes (since 1.0.5)

### ISSUE THREAD

**Issue by outofrange** [angular/material#7142]
Took me some time to figure out that it's not me - it's you :)

Since angular-material 1.0.5, using `md-autocomplete` in a repeating element won't show a text when nothing is found. The normal dropdown for regular results seems to work fine.

I created a [codepen](http://codepen.io/anon/pen/PZVGGz) to demonstrate the bug - when you change the material version in the script tag to 1.0.4, `md-not-found` will be rendered properly.

Probably the same bug as in #7035.

**Comment by DevVersion** [comment]
Hey @outofrange,

Just checked your issue with #7035. You're right thats the same bug.
I will reference that issue within the commit message, so everything is linked properly.

**Comment by outofrange** [comment]
Thanks @DevVersion :)

**Comment by DevVersion** [comment]
@outofrange I don't know, this is depending on Thomas' decision.
