### ISSUE TITLE
Remove references to $mdConstant from docs

### ISSUE THREAD

**Issue by jelbourn** [angular/material#7143]
A couple of places in the docs (such as in mdChips) make reference to `$mdConstant`, but the service is actually not part of ng-material's public API; it's meant to be an internal-only utility and it does not have any documentation of its own. References to `$mdConstant` is user-facing docs should be removed.

**Comment by calebegg** [comment]
The example code for mdChips still uses `$mdConstant`

https://github.com/angular/material/blob/0b89a877ad31d0f7d425272f29d8c02600a12a88/src/components/chips/demoCustomSeparatorKeys/script.js
