### ISSUE TITLE
md-floating-label doesn't support html

### ISSUE THREAD

**Issue by ThomsCass** [angular/material#7144]
hi,

We can't style the floating label of `md-auto-complete` with some html here is an image to illustrate that :
 
<img width="344" alt="capture" src="https://cloud.githubusercontent.com/assets/10784312/13014554/b214a1c0-d1b4-11e5-9650-0741d15e007b.png">

**Comment by DevVersion** [comment]
Injecting the actual HTML code, instead of the parsed string, will need `ngSanitize` or the use of `$sce`, which I recommend.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
