### ISSUE TITLE
tabs are missing in Demos - Dialog

### ISSUE THREAD

**Issue by super-coder** [angular/material#7147]
![image](https://cloud.githubusercontent.com/assets/2155554/13020860/9e185890-d1cf-11e5-8208-d54eaa1f4d7c.png)

**Comment by iRoachie** [comment]
The tabs are there just hidden. The `<md-pagination-wrapper>` width of 125px that prevents the other tabs from showing.

**Comment by DevVersion** [comment]
This should be fixed in #7118

**Comment by DevVersion** [comment]
Confirmed it, it's fixed in #7118

**Comment by matthiasg** [comment]
This is happening again in 1.1.0-rc5 :( .. the first time a dialog comes up its all fine, with every other dialog opening afterwards the tabs are missing though.  resizing the window fixes that issue.

**Comment by DevVersion** [comment]
@matthiasg Please file a new issue and confirm with `master`
