### ISSUE TITLE
Autocomplete is very tall.

### ISSUE THREAD

**Issue by ashwinputhige** [angular/material#7153]
The height of Autocomplete field is a lot more than other components. Please provide a way to make autocomplete fields shorter.

<img width="415" alt="autocomplete-height-issue" src="https://cloud.githubusercontent.com/assets/7256876/13030852/a8ba3e6e-d26d-11e5-9386-24729a86400a.png">

**Comment by LeoLozes** [comment]
I have the same issue, and it seems that what cause it is a mix between
`md-autocomplete[md-floating-label] md-input-container` having a `padding-bottom: 26px;` 
and `md-input-container .md-errors-spacer` having a `min-height: 24px;`

It seems related to [this issue](https://github.com/angular/material/issues/5764). Which I don't understand why is labelled as an "edge case" and in the backlog.  Anyway. 

Normal rendering: 

![before](https://cloud.githubusercontent.com/assets/11133817/13642092/6d68f0dc-e61b-11e5-9b2f-ce7e679c3af8.PNG)

After commenting the above-mentioned css properties:

![after](https://cloud.githubusercontent.com/assets/11133817/13642100/72e01efa-e61b-11e5-938b-4ec413455088.PNG)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
