### ISSUE TITLE
md-list-item doesn't display an ellipsis when text overflows

### ISSUE THREAD

**Issue by roidayan** [angular/material#7155]
the list item h3 css does have text-overflow ellipsis attribute set but the parent div seems to be missing overflow hidden attribute for it to actually show the ellipsis.

v1.0.5:
http://codepen.io/anon/pen/rxPgOg

v1.0.5 with overflow hidden attribute to show the ellipsis:
http://codepen.io/anon/pen/LGqoNG

**Comment by gpopovic** [comment]
related #7065

**Comment by ThomasBurleson** [comment]
Fixed with SHA 8499d029a800890e53b6f09b4b014d4d902bd162

**Comment by DevVersion** [comment]
:+1:
