### ISSUE TITLE
<md-fab-toolbar> with text, won't show them on transition to close state

### ISSUE THREAD

**Issue by Thomas-P** [angular/material#7156]
Hi,

I do not know if this should happen, but if I use the md-fab-toolbar with text instead of an icon, the text would not be shown after closing the toolbar.

```html
<md-fab-toolbar md-direction="left">
        <md-fab-trigger class="align-with-text">
            <md-button aria-label="Menu" class="md-fab md-primary">
                Menu
            </md-button>
        </md-fab-trigger>
        <md-toolbar>
            <md-fab-actions class="md-toolbar-tools">
                
            </md-fab-actions>
        </md-toolbar>
    </md-fab-toolbar>
```

If I clear the element styles of the background layer div, then the text would be shown.

```html
<md-fab-trigger class="align-with-text ng-scope" aria-haspopup="true" aria-expanded="false">
        <button class="md-fab md-primary md-button md-ink-ripple" type="button" ng-transclude="" aria-label="Menu">
                <div class="md-fab-toolbar-background" style="border-radius: 1920px; width: 56px; height: 56px; transform: scale(1); transition-delay: 200ms; top: 0px; background-color: rgb(63, 81, 181);"></div>
                <span class="ng-scope">
                        Menu
                </span>
                <div class="md-ripple-container"></div>
        </button>
</md-fab-trigger>
```

**Comment by DevVersion** [comment]
@Thomas-P Yes can reproduce that - As always please provide a codepen, which will simplify investigation so much.

I just created a codepen demo for this: http://codepen.io/DevVersion/pen/wMNLRa

**Comment by topherfangio** [comment]
Definitely see the issue. We'll see if we can find a good way to support both icons and text.

**Comment by topherfangio** [comment]
Sorry; I haven't had a chance to get to this issue yet. If you find a workaround or want to submit a PR, it would be most appreciated :smile:

**Comment by Thomas-P** [comment]
@johnwebbcole 

Workaround could be a listener on transition, which will remove the element styles, as seen above.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
