### ISSUE TITLE
Conflicts between `height: 100%` and `<md-autoselect>` windows

### ISSUE THREAD

**Issue by mathiasmoeller** [angular/material#7158]
In my project I have to set `height: 100%` on the `<html>` and `<body>` tags to make center elements and to have the `<md-sidenav>` over full page height.

This somehow breaks the `<md-autoselect>` directive. In my case I have lots of autoselects below each other. As soon as I click on one of the lower ones the whole page turns white.
This is caused by the `disableBodyScroll`-method in `$mdUtils` which gets called when autoselects, sidenavs etc. are opened.

The primary problem seems to be that `body.scrollHeight` in our case is the same as `body.clientHeight`. 

`$mdUtils.disableBodyScroll` code:
```` javascript
var clientWidth = body.clientWidth;
if (body.scrollHeight > body.clientHeight + 1) {
    applyStyles(body, {
        position: 'fixed',
            width: '100%',
            top: -scrollOffset + 'px'
    });

    applyStyles(htmlNode, {
        overflowY: 'scroll'
    });

    if (body.clientWidth < clientWidth) applyStyles(body, {overflow: 'hidden'});
}
````

This is caused by the 100% height. Removing the height property from the body and html tag solves the problem with the autoselects. But if we remove the height, pages that are smaller than 100% show a wrong sidenav behaviour (the sidenav is only as tall as the page). 
We temporarily fixed the problem by monkey patching `$mdUtils.disableBodyScroll`. 
We replaced 
`if (body.clientWidth < clientWidth) applyStyles(body, {overflow: 'hidden'});`
with
`applyStyles(body, {'overflow': 'visible'});`

It is hard to create a plnkr for this example as the structure is quite complicated and the problem does not occur as soon as I try to simplify the code.
Has anybody encountered this problem?

I posted this question on StackOverflow as well: http://stackoverflow.com/questions/35404594/conflicts-between-height-100-and-md-autoselect-windows

**Comment by TiboQc** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
