### ISSUE TITLE
material.components.showHide: Delays AngularJS digest cycle stability

### ISSUE THREAD

**Issue by tuxford1** [angular/material#7159]
material.components.showHide enhances AngularJS's ngShow / ngHide directives to raise a $md-resize event when the transition is complete. It uses $mdUtil.dom.animator.waitTransitionEnd which expects a transitionend/webkitTransitionEnd event to be raised by the element. However in my project this event is never raised, and hence the promise it returns does not resolve until the method's default timeout (3000ms). 

After any element show / hide, AngularJS thinks the model is unstable for the next 3000ms. This is an issue for running end-to-end tests, as protractor noticeable pauses whenever an element is shown or hidden, and this adds significantly to the overall test time.

Is it possible to review this code so as not to impact end-to-end tests?

**Comment by topherfangio** [comment]
References #6380.

@tuxford1 Can you please provide an example of how this is causing issues for you? The code is written so that this only applies to the show/hide of the virtual repeat directive, so it should not affect any other elements which are shown/hidden.

If it's causing a performance issue, we definitely want to track it down, I just don't think I'm fully understanding the problem and I'd like to make sure we know exactly what it is before we try to fix it :-)

**Comment by tuxford1** [comment]
Yes, It think this is the same issue as [#6090](https://github.com/angular/material/issues/6090) - sorry for not finding that before opening the issue. It affects any end-to-end testing tool (e.g. protractor) that waits for AngularJS's model to stabilize before proceeding. You can repro it by:

JS:
(function () {
    'use strict';

    angular
      .module('MyModel')
      .controller('MyController', function ($window, $$testability) {

          function checkStability() {
              angular.element('#stability-status').text('unstable').css({ backgroundColor: 'red' });
              $$testability.whenStable(function () {
                  angular.element('#stability-status').text('stable').css({ backgroundColor: 'green' });

                  $window.setTimeout(checkStability, 100);
              });

          }

        checkStability();

    });
})();

HTML:
<div ng-controller="MyController">
	Model is currently <span id="stability-status"></span>
	
	<md-autocomplete md-selected-item="selectedItem"
					md-search-text="searchText"
					md-items="item in ['AL', 'AK', 'AZ']"
					md-item-text="item"
					md-min-length="0">
	</md-autocomplete>
</div>
Click into the autocomplete to show the list of suggestions and the AngularJS model is shown as unstable for 3 secs... doesn't sound a lot but over the course of many tests it really adds up (added about 17mins to our CI build time)

**Comment by topherfangio** [comment]
@tuxford1 What I'm trying to understand is why it's causing such a slowdown. Do you have so many autocomplete tests that it's adding 17 minutes? Or is this somehow affecting **all** of your tests even if they don't interact with the autocomplete?

**Comment by tuxford1** [comment]
Hi @topherfangio it seems that the **presence** of md-autocomplete on the page causes the delay whenever a ng-show / ng-hide is triggered on the page, changing my html to 

```
<div ng-controller="MyController">
    Model is currently <span id="stability-status"></span>

    <md-autocomplete md-selected-item="selectedItem"
                     md-search-text="searchText"
                     md-items="item in ['AL', 'AK', 'AZ']"
                     md-item-text="item"
                     md-min-length="0">
    </md-autocomplete>
    <div ng-hide="!show">Hi!</div>
    <button type="button" ng-click="show = !show">Click on me</button>

</div>
```

Clicking on the button, without even touching the md-autocomplete, shows AngularJS's model to be unstable for 3 secs. Since we are using md-autocomplete, any user interaction that triggers a ng-show / ng-hide (which are very widespread) results in 3 sec delay in our end-to-end tests, and as there are hundreds of such interactions this adds up to a substantial delay.

**Comment by topherfangio** [comment]
@tuxford1 Thanks so much, that is exactly what I needed. I'll dig in to find out why it's affecting all of the `ngShow`/`ngHide`s instead of just the autocomplete ones. We may not be able to do much about the autocomplete, but it definitely shouldn't be affecting other things.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
