### ISSUE TITLE
apply flex on one md-dialog, width become 100% instead 80%

### ISSUE THREAD

**Issue by JA44** [angular/material#7160]
If I apply the flex property on one md-dialog, it changes the property max-height from 80% to 100%. 

It shouldn't change the max-height property?

On this codepen, I applied a flex on the custom dialog. It shows itself on the whole height of the screen. Without flex property, it takes 80% of the screen.

http://codepen.io/anon/pen/vLPyBK

**Comment by DevVersion** [comment]
Can reproduce. This seems not to be by intention. As you can see in the following screenshot this is caused by the flex class itself. I'm not sure why the `max-height` property was added to a `row` directional layout. 

![](https://i.gyazo.com/dd05fa3cc3d278e8194d5d0d93b655bc.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
