### ISSUE TITLE
md-select - Option positioning is not correct

### ISSUE THREAD

**Issue by tonyawad88** [angular/material#7162]
Hey guys,

I have a md-select with 10 options placed within an md-tab as shown below.
When I select Option 10 / last item in the list, and open the list again to select item 1 (Opt1-Url1) in the example below, (Opt1-Url1) is not shown and is overlayed my guess is. 

Now I can fix that by changing the z-index on the .md-select-menu-container.md-active and set it high enough. The logic for positioning the md-select-menu-container should we revisit it or this is how it should be? I wonder why we shift it up when option 10 is selected and there's enough room for it to expand down. 

Thanks,

![optionbug](https://cloud.githubusercontent.com/assets/3638322/13052932/c7e2fb38-d3cf-11e5-8d20-76f07a71f986.gif)

**Comment by DevVersion** [comment]
Is it possible that you share your demo with us? This will simplify so much.

**Comment by tonyawad88** [comment]
There. Hope this helps a bit.
https://codepen.io/tonyawad88/pen/ZQPKwE

**Comment by DevVersion** [comment]
@tonyawad88 Can reproduce. I will try having a look at the position method.

**Comment by tonyawad88** [comment]
@DevVersion Thank you !

**Comment by gpalmer1984** [comment]
I noticed that the clamp function in the calculateMenuPosition function has an incorrect containerNode dimensions onShow.  I can do a manual resize event to make the menu re-position with correct containerNode dimensions.

My hack was to comment out the transform section in the return value of calculateMenuPosition and fire a window resize event within a $timeout after the menu item is clicked.

I figured this information might help with identifying a better solution.

**Comment by topherfangio** [comment]
This might be related to PR #6429 which adds some tests for a similar scenario. I need to spend some time rebasing/updating that PR. When I do, I'll see if I can add some tests and fix this case too.

**Comment by jayeshanandani** [comment]
Does #5754 indicates same?

**Comment by jayeshanandani** [comment]
May be #5435 is same?

**Comment by topherfangio** [comment]
@jayeshanandani Indeed; looks like the same issue.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
