### ISSUE TITLE
IE11 Dialog Demos are positioned incorrectly

### ISSUE THREAD

**Issue by chris-eaton** [angular/material#7163]
The Dialog Demos listed here https://material.angularjs.org/latest/demo/dialog dont work correctly.

There are two issues

1. The tabbed dialog shrinks before opening looking odd
2. Any dialog that opens within a container (not page wide) appears at the bottom rather than in the middle. Alert Dialog for example

**Comment by topherfangio** [comment]
@m0nkeymafia What browser are you using? I'm not seeing either of these issues in Chrome.

**Comment by topherfangio** [comment]
So sorry...just reread the title and saw IE11...I can reproduce both issues.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by chris-eaton** [comment]
Hi Thomas

I understand your spring cleaning efforts but this bug shows fundamentally broken logic as well as being in an up to date browser.  It kind of makes material unusable in IE.  Should it not still be fixed?
