### ISSUE TITLE
Datepicker icon getting drawn too large

### ISSUE THREAD

**Issue by peffreycollins** [angular/material#7165]
It appears that something is causing any embedded icons to be drawn rather largely:
![image](https://cloud.githubusercontent.com/assets/12089878/13062781/927a195e-d406-11e5-9ad4-667fea8a8d9a.png)

I don't appear to have any CSS overwriting the default material styles.  The icon appears to be stretched to its 40 by 40 .md-button.md-icon-button container.

![image](https://cloud.githubusercontent.com/assets/12089878/13062831/257df82e-d407-11e5-8fd9-91cd28c0b35e.png)

Has anyone else experienced this?

**Comment by RolandHeath** [comment]
I haven't (chrome Version 47.0.2526.106, fedora 22). 

What browser are you using, and does it occur on the [docs page](https://material.angularjs.org/latest/demo/datepicker)?

**Comment by peffreycollins** [comment]
Sorry for the red-herring.  Not an issue, just a conflict with an old polymer 0.5 component.
