### ISSUE TITLE
md-autocomplete: [feature] adding category functionality 

### ISSUE THREAD

**Issue by samithaf** [angular/material#7166]
Would be great if can have different categories in auto complete dropdown. Same feature do exist in jQuery auto complete https://jqueryui.com/autocomplete/#categories

E.g. Employee search, search term "an" will gives a list as follows
**Developers**

- Andy
- Andrew

**Testers**

- Annie
- Anne

**Comment by topherfangio** [comment]
Duplicate of #7417. Please comment if you disagree and I will reopen.

**Comment by samithaf** [comment]
It's pretty much the same feature. @topherfangio #7417 is been marked as deprecated. Does that mean it will never be part of autocomplete Material?

**Comment by topherfangio** [comment]
@samithaf It means that it is not likely to be part of the Material 1 Autocomplete unless someone else is willing to work with us and contribute the functionality.
