### ISSUE TITLE
md-tabs Pagination Not Working With Larger Label 

### ISSUE THREAD

**Issue by jweinstein92** [angular/material#7167]
I noticed that if an md-tabs requires pagination and the labels are large - a larger font size or a bigger line spacing for example, the pagination does not work. The example md-tabs codepen has been edited to show the issue. If needed, resize your window to see the pagination. I tested with both font-size and line-spacing and both cause the issue. I also tried adding 
```
md-pagination-wrapper {
    width:auto !important;
}
``` 
to the CSS with no luck.

http://codepen.io/anon/pen/OMqEJm

**Comment by topherfangio** [comment]
That is a really interesting issue. I'll see if I can track it down. If you come up with any new info, please let us know.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by RangaKom** [comment]
Hi can you tell me what is the solution in detail.Means how can I get the fix.
