### ISSUE TITLE
md-select doesn't work on webview (Android 4.4.4)

### ISSUE THREAD

**Issue by mfernandez92** [angular/material#7171]
I'm working on an app that needs to display an Angular Material Form in a Webview.
All components of the form displayed well and works fine except md-select.
When I touch the md-select, the page goes blank and it is impossible to go back.
The application continues to work.
The md-select and the same html works fine on desktop chrome browser.

I tested with this tools:

- Angular Material 1.0.0 ; 1.0.4 ; 1.0.5
- Angular 1.4.9 ; 1.5.0
- Android 4.4.4
- Tablet Noblex NBX-T7A3l

**Comment by mfernandez92** [comment]
The problem seems to be the css "-webkit-overflow-scrolling touch" from md-content inside md-select.

**Comment by mfernandez92** [comment]
This issue has been fixed. 
In my Android Activity, I have changed this propertys of my WebView:

- layout_width="wrap_content" to layout_width="match_parent"
- layout_height="wrap_content" to layout_height="match_parent"

And all the components works fine! :)

**Comment by topherfangio** [comment]
Glad you got it figured out!

**Comment by kmturley** [comment]
Getting this issue again with the latest angular-material.

This is a workaround i'm using:

    angular.module('MyApp', ['ngMaterial'])
        .config(function($mdGestureProvider) {
            $mdGestureProvider.skipClickHijack();
        });
