### ISSUE TITLE
material element cause google docs iframe appear a scrollbar.

### ISSUE THREAD

**Issue by zixia** [angular/material#7174]
I use angular-material in a google spreadsheets' add-on, which means "transform: translate3d(...);" run inside google spreadsheet, a iframe.

I used a form input element, which has a animate 'label' tag. then I got a scrollbar in the iframe, it's quite hard to debug, at last I found if I delete the css setting of "transform" on 'label' tag, the scrollbar's gone.

I believe it is caused by this issue: 'transform' has side effect to other containters, which cause position error.

so at last, I had to hard coded a css style code in my html header: "transform: none !important;" (I lost animate of my input label).

about w3c spec bug of transform discusstion:

* https://code.google.com/p/chromium/issues/detail?id=20574#c50
* https://github.com/jakiestfu/Snap.js/issues/24
* analyze: http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/
* https://github.com/twbs/bootstrap/issues/14227
* disable transform: http://stackoverflow.com/questions/19652574/how-to-disable-by-overriding-webkit-transform-and-not-deleting-the-line
* translate3d in angular material: https://github.com/angular/material/search?p=2&q=translate3d&utf8=%E2%9C%93

**Comment by zixia** [comment]
I use md-tabs , with disabled almost all transform to prevent scroll bar appear by: 

```html
  <style>
    md-input-container label { transform: none !important; }
    md-pagination-wrapper { transform: none !important; }
    md-tabs-wrapper { transform: none !important; }
    md-prev-button, md-next-button { transform: none !important; }
    md-icon { transform: none !important; }
</style>
```

however, I found a hardcoded transform here:
https://github.com/angular/material/blob/v1.0.5/src/components/tabs/js/tabsController.js#L196

is there any attribute to disable transform for md-tabs, like `md-no-ink` ?

**Comment by ThomasBurleson** [comment]
Currently, component animations are tightly integrated and **not** easily disabled. This would be a great feature change... but would have huge impacts to project structure and all components.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
