### ISSUE TITLE
<md-input-container> Cursor moves up when non-number is added "number only" <input>

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#7175]
See [demo](http://codepen.io/cmacdonnacha/pen/WrmqeP?#)

If you type a text (e.g "abc") into the "number only" input you'll notice that the cursor jumps up slightly.

This only happens when using **type="number"**

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
