### ISSUE TITLE
<input> Firefox Issue: Can enter text into number only input field

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#7176]
See [demo](http://codepen.io/cmacdonnacha/pen/WrmqeP?#)

Even though the input type has been set to **type="number"** it still accepts text.

This occurs in Firefox. Does not occur in Chrome. Haven't tested any other browsers.

**Comment by iRoachie** [comment]
This isn't a angular material error. Firefox does yet support `<input type="number">`.

http://quirksmode.org/html5/inputs/

**Comment by cmacdonnacha** [comment]
I see. Should something like this be implemented into Angular Material though instead of leaving it up to the user?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
