### ISSUE TITLE
md-datepicker incorrect days

### ISSUE THREAD

**Issue by rvarbanov** [angular/material#7179]
As of now the md-datepicker is accepting days from 1 through 31 and not verifying the months. For example, if a user types 04/31/2016 which is invalid because April has only 30 days does not throw an error and the calendar assumes the user meant May 1st. Same thing applies to the month of February and others.

**Comment by cuttingd** [comment]
I'm experiencing this issue as well.  At first I thought it was a bug because today is leap day, but it appears that it's just a generic bug validating days against the selected month

**Comment by ngraef** [comment]
FYI, this reflects the behavior of the `Date` constructor.
```javascript
new Date(2016, 3, 31)  // month is 0-inexed
// Sun May 01 2016 00:00:00 GMT
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
