### ISSUE TITLE
Code highlights with are sometimes corrupted with PageSpeed issues

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#718]
Intermittently, the online docs have random corruption in the html: in the API views and in the Demo source views, etc. A brief investigation indicates the the highlightJS `<hljs>` may have some interference with GA.

![doccorruption](https://cloud.githubusercontent.com/assets/210413/5141952/f04e92fe-7141-11e4-84e0-ddc32b20d555.png)

**Comment by marcysutton** [comment]
Closing as duplicate of https://github.com/angular/material/issues/1010.
