### ISSUE TITLE
autocomplete requiere double click in text

### ISSUE THREAD

**Issue by miguelcaravantes** [angular/material#7180]
https://material.angularjs.org/latest/demo/autocomplete

tested in chrome in autocomplete demo and in my project

select item in autocomplete requiere double click if you click in text

image: https://drive.google.com/file/d/0B4BrpMT6tZxtQlJUWU1GQXNCZGc/view?usp=sharing

PD: only occurs when clean from the button

**Comment by DevVersion** [comment]
@miguelcaravantes I don't get the actual issue? Can you provide more information?

**Comment by miguelcaravantes** [comment]
Yes this is bug is replicable in autocomplete demo in "Basic Usage" secction.
Chrome version: 48
Windows version: 10

This video illustrates the bug
https://www.youtube.com/watch?v=KbzUgHPJRlg&feature=youtu.be

sorry for my bad english
