### ISSUE TITLE
mdCheckbox: md-tooltip doesn't appear when hovering over checkbox, but only when hovering over the text in div.md-label

### ISSUE THREAD

**Issue by snaumets** [angular/material#7182]
This issue is similar to [#1101](https://github.com/angular/material/issues/1101).
A live example can be seen [here](http://codepen.io/anon/pen/VeNLrj). 
If you hover over the 'Checkbox 1: true' text, the tooltip will appear. But hovering over the checkbox itself doesn't show the tooltip. Since the checkbox is too a part of the md-checkbox element, hovering over it should also show the tooltip.

**Comment by snaumets** [comment]
I found a temporary fix for this issue by simply adding a style for the md-checkbox:
```
md-checkbox [ng-transclude] {
  pointer-events: none;
}
```

A working example can be seen [here](http://codepen.io/anon/pen/MKRaJY).

**Comment by GustavSt** [comment]
I noticed the same issue! 
Thanks for the fix!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
