### ISSUE TITLE
md-tooltip shows for disabled element in IE 11

### ISSUE THREAD

**Issue by matthillman** [angular/material#7183]
This is somewhat weird to reproduce. It seems you move the mouse onto the button very quickly. Here is a [codpen with a disabled button](http://codepen.io/anon/pen/RrEqyz) and a [video showing the tooltip appearing on the disabled button](https://raw.githubusercontent.com/matthillman/matthillman.github.io/master/Capture_2016-02-11_10-32-04_AM.mov)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
