### ISSUE TITLE
md-tooltip height changes when mobile keyboard pops up

### ISSUE THREAD

**Issue by jpike88** [angular/material#7184]
This issue changes the toolbar height when a keyboard pops up. I think it triggers a CSS rule that really shouldn't be triggered.

```
@media (max-width: 959px) and (min-width: 0) and (orientation: portrait)
md-toolbar {
    min-height: 56px;
}
```

gets overridden by:

```
@media (max-width: 959px) and (min-width: 0) and (orientation: landscape)
md-toolbar {
    min-height: 48px;
}

```

Video of it occurring:
https://www.dropbox.com/s/rudtgiarmvg4bya/Menu%20sizing.mp4?dl=0

**Comment by jpike88** [comment]
Workaround:

```
md-toolbar {
    min-height: 56px !important;
}
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
