### ISSUE TITLE
Nested layouts not working as expected in chrome

### ISSUE THREAD

**Issue by vigneshnrfs** [angular/material#7185]
http://codepen.io/anon/pen/pgBbbM

I am trying nest columns inside the rows as given in this codepen. The content overflows to the next row/column.

It does not happen in firefox. For some reason, the codepen displays it correctly. But loading it on a blank page, this issue crops up. 

Is it a bug or my coding is wrong?

**Comment by GavinPalmer1984** [comment]
I have seen this for some time now and reported it to the Chrome team months ago.  I will leaven example as well:
http://gavinpalmer1984.github.io/layout-problem/

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
