### ISSUE TITLE
md-icon displaced to the right of placeholder text in md-input-container

### ISSUE THREAD

**Issue by kanethal** [angular/material#7188]
I'm trying to simply place an icon on the left of an input field like is done in the angular material demos. However, the icon is shifted considerably to the right of where I expect it.

http://codepen.io/anon/pen/OMGxqQ

**Comment by DevVersion** [comment]
At first you should use the latest version for your demo. There were a few changes in the icon support for inputs, like the smart alignment detection. And just took a look at your demo with the latest version, this seems not to be an issue of the input component, this seems to be a misalign of the material icons stylesheet.

**Comment by kanethal** [comment]
Thank you for responding. I modified an existing codepen to render the
example, but my project is using the master version from github and it
looks the same. What version has this working properly?

**Comment by DevVersion** [comment]
No the actual issue is not resolved by updating to the latest version. In general the latest version is detecting automatically the icon alignment, but the actual issue is that the icon stylesheet (Material Icons) are rendering the icons not correctly.

**Comment by kanethal** [comment]
OH! I see. So a problem with the icon font itself then? It would explain
why the element inspector highlights the correct area where I would expect
the icon, but the icon itself resides outside. I'll switch to FA and see if
that helps. Thank you!

**Comment by DevVersion** [comment]
Just dive into this again and need to say again, this is caused because you are not using the latest version, and as a little side-issue you chooses an icon which has a strange width.

I'll close this issue, because the icon placement is actually working in the latest version. If there any more issues you have, just let me know.
