### ISSUE TITLE
md-chips has watchers that doesn't disappear

### ISSUE THREAD

**Issue by GustavSt** [angular/material#7189]
When having a md-chips directive, entering chips and then removing them, there seem to be 3 "ghost" watchers that is not removed.

I can't reproduce with a plunkr or something because the [chrome plugin](https://chrome.google.com/webstore/detail/angular-watchers/nlmjblobloedpmkmmckeehnbfalnjnjk) that I'm using doesn't seem to  find that scope of the page or something. 
But I used the following code and everytime I add a chip I get +8 watchers and each time I remove one I get -5, ie 3 of them not removed.

```
<div ng-app="app" ng-controller="testController">
            <md-chips
                placeholder="foo"
                ng-model="foo">
                <md-chip-template>
                    <strong>{{$chip}}</strong>
                </md-chip-template>
            </md-chips>
        </div>

```

```
angular.module('app', ['ngMaterial'])
      .controller('testController', ['$scope',function($scope){
        $scope.foo = [];
      }]);
```
I have no idea what might cause this. It would be nice to hear if anyone else can reproduce this.

Angular material 1.0.5
Angular 1.4.9

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
