### ISSUE TITLE
md-grid-list first render is broken with limited width

### ISSUE THREAD

**Issue by LeoLozes** [angular/material#7190]
I've been playing around with the md-grid-list component. It usually works fine, but when the width of the screen is small, the first rendering is broken. If you resize the window and then get it back at the original width, it scales well, but when you refresh the page, the rendering is broken again. 

You can see it in the [gridList demo](https://material.angularjs.org/latest/demo/gridList)

You can see the (not very well done) video here: https://goo.gl/Um7ZL6

**Comment by troig** [comment]
+1. Same problem here

**Comment by Hammild** [comment]
+1. The problem is also true on Iphone 6. Vertical view = narrow screen width, and horizontal view = resizing. 

iPhone 6 (MG4F2QN/A)
Operating system: iOS 9.1 (13B143)
Browser: Safari 9.0 Mobile

**Comment by topherfangio** [comment]
@DevVersion Can you take a look please?

**Comment by DevVersion** [comment]
The problem is, that there is only space for one column. 

> angular.js:12520 md-grid-list: Tile at position 0 has a colspan (2) that exceeds the column count (1)

**Comment by DevVersion** [comment]
@topherfangio Fixed it :)
