### ISSUE TITLE
mdPanel: Implement mdPanelPosition relativeTo method.

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#7192]
Make sure the element exists on the screen. If it doesn't, use the same fallback as md-dialog.

Store location of the element so that it can be used for positioning.

**Comment by KarenParker** [comment]
Remember to have a watcher on the window resizing.

**Comment by Head** [comment]
@KarenParker @ErinCoughlan seems like nobody remembered the 

> watcher on the window resizing

Or is it a new bug?

https://github.com/angular/material/issues/10560
