### ISSUE TITLE
md-menu position not updating after window resize

### ISSUE THREAD

**Issue by diminutivesloop** [angular/material#7199]
Md-menu components do not properly update the position of their drop-down content when their containing window is either resized quickly or maximized. 

For example on the [Angular Material Menu demo page](https://material.angularjs.org/latest/demo/menu), if I open a menu while my browser window is small:

![capture1](https://cloud.githubusercontent.com/assets/667716/13125755/53d66e10-d595-11e5-8121-e90d512dc698.JPG)

and then proceed to maximize the browser window, the drop-down is misaligned to its emitting button:

![capture2](https://cloud.githubusercontent.com/assets/667716/13125804/797fb8a6-d595-11e5-9a68-68cded1976db.JPG)

**Comment by ddjonline** [comment]
+1

**Comment by zoness32** [comment]
+1

**Comment by pete-mckinney** [comment]
+1

**Comment by mpiasta-ca** [comment]
+1

**Comment by gokceyalcin** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
