### ISSUE TITLE
Issuing with Ionic

### ISSUE THREAD

**Issue by furyscript** [angular/material#7203]
I started my projects with `Ionic` and Angular Material (https://material.angularjs.org/latest/).

I encountered some problem with theme. Angular material load it's theme dynamically with its internal code and prepend it to `<head>` tag. This is pseudo code example:

    <head>
        
        <link rel="stylesheet" href="css/ionic.app.css">
    </head>

When page are loaded `ngMaterial` load its theme before `ionic.app.css` so most of css components not working because are overwriting by ionic's style.

If anyone know how to append `ngMaterial` theme after my style or simply after `ionic.app.css` it would be nice if you tell me how.

This is a demostration link: http://codepen.io/anon/pen/EPJBqX (note the border of input not work properly)

I've already open issue to SO but without success...

Regards,
D.

**Comment by DevVersion** [comment]
Hey,

ngMaterial is not official compatible with `Ionic` as mentioned in the `Getting Started` section ([here](https://material.angularjs.org/latest/getting-started)). 

In you case you should ask you question in the ngMaterial Google Group.
https://groups.google.com/forum/#!forum/ngmaterial

**Comment by furyscript** [comment]
Do you know when they make integrations?

**Comment by DevVersion** [comment]
@furyscript I don't think this will be made compatible in the near future. About your actual issue, which should be normally answered in the Google Group, but I will answer it here.

If you really wan't to load your actual `ionic.app.css` after the theming styles, then you should inject your css dynamically through JavaScript, for example [loadCSS](https://github.com/filamentgroup/loadCSS)

**Comment by ThomasBurleson** [comment]
Not supported.

**Comment by furyscript** [comment]
what is not supported? @ThomasBurleson ........

**Comment by DevVersion** [comment]
@furyscript In the `Getting Started` section is briefly mentioned, that Ionic isn't supported with `ngMaterial`. Therefore it was mentioned that: 

>  ngMaterial conflicts with ngTouch for click, tap, and swipe support on touch-enabled devices.

**Comment by furyscript** [comment]
I don't think @DevVersion 
This works correctly: http://codecanyon.net/item/ionic-material-design/12833673 but with only problem that some input's styles are incompatible

**Comment by DevVersion** [comment]
@furyscript I'm sorry I copied the wrong quote... and about `Ionic Material Design`, this is a modificated version of `ngMaterial`, which is specialized on compatibility with Ionic.

![image](https://cloud.githubusercontent.com/assets/4987015/13636377/f1b5db58-e601-11e5-9824-df657dce2e44.png)
