### ISSUE TITLE
Datepicker display problems

### ISSUE THREAD

**Issue by alvin97231** [angular/material#7205]
The picker does display too large and other problems too. Look at the pic...
![datepicker_issue](https://cloud.githubusercontent.com/assets/6461422/13143591/3a87a3a6-d645-11e5-8f61-8b58a03add19.JPG)

**Comment by sryzycki** [comment]
Getting similar behaviour (https://www.dropbox.com/s/q77m1wjpjuzjz98/Screenshot%202016-03-08%2016.41.07.png?dl=0). I noticed that this only happens, in my case, when I scroll the window more than ~30px and the datepicker popup window is not that close enough to the bottom of the window to kind of "stick" to it at the very bottom with some 10px bottom offset.

Happy to help debugging this.

**Comment by topherfangio** [comment]
Can one of you please provide a Codepen demo which shows this issue as well as telling us what browsers you are using/

**Comment by homerjam** [comment]
+1 (will try and do a demo tomorrow)

**Comment by alvin97231** [comment]
I have already change my filter way. I haven't code of this issue. I think that this issue is result of put datepicker in a <th> cell of a table.
