### ISSUE TITLE
md-select multiple auto-close option

### ISSUE THREAD

**Issue by manuelagard** [angular/material#7212]
By default, a md-select with "multiple" activated will not close the options box when a choice is made by user. To close the box, user is obliged to click outside the box which is, from my point of view, not very user friendly.
It would be great to have an "autoclose" option on the md-select directive to allow options box hiding when a choice is made by user.

**Comment by zargold** [comment]
:+1:

**Comment by aeslinger0** [comment]
@manuelagard, what version are you using? I have the same problem, but I can't even click outside the box. It looks like md-scroll-mask is blocking the click event!

**Comment by manuelagard** [comment]
Hi @aeslinger0 ,
I am using the v1.4.9 for AngularJS and 1.0.5 for Angular Material.
Maybe you could post a Jsfiddle to get some help.
But in any case, this "autoclose" option would be very welcome, even more in your case...

**Comment by DevVersion** [comment]
I think, this will be a good addition to the `select` component.

@aeslinger0 If your problem isn't related to this *feature request*, you should create a separated issue.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
