### ISSUE TITLE
$mdDialog reopens on tab change

### ISSUE THREAD

**Issue by lexyfeito** [angular/material#7215]
I am using v1.0.3-master-b707375 of angular material and i have created a custom dialog, sometimes with it opens it can not be close neither using $mdDialog.cancel() or $mdDialog.hide(), and sometime it can be close but if i change windows or tabs when the tab which have the dialog is refocused it reopens the dialog. Is there knowledge of this already? Thank you.

**Comment by DevVersion** [comment]
No, I haven't seen an issue which shows your issue. I would like to take a look at your issue, but I can't reproduce your actual issue, so I'd love to see a demo. Can you provide one?

**Comment by lexyfeito** [comment]
Hello @DevVersion sorry for the inconvenience, it was an error on my side i was sending the $event == undefined thank you

**Comment by DevVersion** [comment]
No worries, thanks for letting me know!
