### ISSUE TITLE
md-menu sits on top of md-select>md-option

### ISSUE THREAD

**Issue by zargold** [angular/material#7218]
If I have a md-menu which has in it a md-select...
```html
<md-menu md-position-mode='target-right target'>

    <md-button
        class="md-icon-button"
        ng-click="openMenu($mdOpenMenu, $event)"
    >
        <md-icon md-menu-origin md-svg-icon='my-icon'></md-icon>
    </md-button>

    <md-menu-content
        width="6"
        class="full-height"
        id="alerts-menu-content"
    >
        <md-menu-item layout='row' layout-align='center'>
            <div flex="35">
                <h5>Sort by:</h5>
            </div>
            <md-input-container flex="65">
                    <md-select
                        class="md-primary"
                        ng-model="order.value"
                        aria-label='Sorting By'
                    >
                        <md-option
                            ng-repeat="sorter in sorters"
                            aria-label="{{sorter.name}}"
                            value="{{sorter.value}}"
                            class="md-accent"
                        >{{sorter.name}}
                     </md-option>
                   </md-select>
            </md-input-container>
        </md-menu-item>
    </md-menu-content>
</md-menu>
```
![screen shot 2016-02-19 at 2 16 55 pm](https://cloud.githubusercontent.com/assets/11298496/13186439/369dfd9c-d714-11e5-8b94-78344f9e8f19.png)

As you can see in the photo: I would like for the md-select to sit on top of the md-menu and all of its options likewise but instead they sit under making them invisible especially when you have more than 1 items in the md-menu... by the way I'm using: the work around for the md-menu closing on any kind of click: even without that same thing happens:
``` javascript
            scope.openMenu = function($mdOpenMenu, $event) {
                $event.stopPropagation();
                var menu = $mdOpenMenu($event);

            };
```
And this is with the latest bower update angular-material (1.0.5), but did not happen a little while ago with a previous version of angular-material not sure which version was the last one where it worked.

**Comment by zargold** [comment]
Hi am I doing something wrong?

**Comment by topherfangio** [comment]
We don't currently support mixing menus inside of selects or vice versa as these are both "Menu" components according to the [spec](http://www.google.com/design/spec/components/menus.html#menus-menu-items). And although it doesn't outright specify this, I think the spec leans towards only having one menu open at a time, so I would highly recommend a different structure to your application.

It may take a bit of hacking/modification, but the Menu Bar component currently supports cascading menus (i.e. sub-menus within a menu), so that might offer a better functionality.
