### ISSUE TITLE
No toolbars shown

### ISSUE THREAD

**Issue by soleheir** [angular/material#722]
The toolbar from the material demo on native Browser on Android 4.1.2 has these issues:
- Span text not shown
- No Background Color of Toolbar
- Trying to click on the invisible "Source" span does not work.

**Comment by ajoslin** [comment]
We only support the current browsers minus 2. Therefore, we don't officially support Android 4.1.

Nevertheless, I'm confident this is much better in the latest build... 

If there are more problems on Android 4.1, please open a new issue.

**Comment by weimingwang** [comment]
Save issue found on Nokia X2 (Jelly Bean). Toolbar text can be seen, background color is not.
