### ISSUE TITLE
Input element in md-card not rendering right

### ISSUE THREAD

**Issue by izaakhaliq** [angular/material#7223]
Not sure if this has been reported or not. The input element does not render its full length in the md-card. Anyone else has the same issue? Any solutions?

**Comment by DevVersion** [comment]
Not sure about reproducing that correctly. 
I've created a little Codepen which should represent your issue. Is that representing your issue?

- Class `.md-block` will stretch the input at its full width.

http://codepen.io/DevVersion/pen/jWjNNy

**Comment by izaakhaliq** [comment]
The solution is to override any input element by adding a class with property `width: 100%`. But I feel that it should be working by  #default.

**Comment by izaakhaliq** [comment]
Thanks @DevVersion for the solution

**Comment by DevVersion** [comment]
Have you tried using `.md-block` as a class? 

As you can see in the `input` demo, the `adress` input container also uses `.md-block`, so if you remove that class you will see it will use the required width from the floating label instead of the full width.

**Comment by DevVersion** [comment]
Ah perfect :+1: Just saw you answer, when I sent mine. So its obviously not an issue.
