### ISSUE TITLE
md-dialog issue - is opening  current view instead of templateUrl

### ISSUE THREAD

**Issue by jakeseltz** [angular/material#7224]
I haven't had any issues with md-dialog in past projects. However, today when trying to install a simple custom dialog following the angular material site example -- when I prompt the dialog to open with $md.Dialog it is opening the current html view(rather than the templateURL) ... it is loading the correct controller but still somehow has the current controllers scope.

Lastly, I can put any string in to templateUrl and it will default to the current view.. you'll see below I have put '1' into the templateURL and it loads the screenshot result -- (I have tried to put the correct url in). Is there some kind of default behavior going on that I don't know of? Any ideas.. 

![screen shot 2016-02-20 at 10 22 49 am](https://cloud.githubusercontent.com/assets/6465338/13197752/4941e118-d7bc-11e5-95d9-3df74d9a0452.png)

```js
`'use strict';

angular.module('coachInterface')
  .controller('UsersCtrl', function ($scope,$mdDialog, $mdMedia) {
    
   	$scope.status = '  ';
  	$scope.customFullscreen = $mdMedia('xs') || $mdMedia('sm');


    $scope.showAdvanced = function(ev) {
   		var useFullScreen = ($mdMedia('sm') || $mdMedia('xs')) && $scope.customFullscreen;
   		$mdDialog.show({
   		        controller: DialogController,
   		        templateUrl: '1',
   		        parent: angular.element(document.body),
   		        targetEvent: ev,
   		        clickOutsideToClose: true,
   		        fullscreen: useFullScreen
   		    })
   		    .then(function(answer) {
   		        $scope.status = 'You said the information was "' + answer + '".';
   		    }, function() {
   		        $scope.status = 'You cancelled the dialog.';
   		    });
   		 $scope.$watch(function() {
   		    return $mdMedia('xs') || $mdMedia('sm');
   		}, function(wantsFullScreen) {
   		     $scope.customFullscreen = (wantsFullScreen === true);
   		});
	};

});

function DialogController($scope, $mdDialog) {
  $scope.hide = function() {
    $mdDialog.hide();
  };
  $scope.cancel = function() {
    $mdDialog.cancel();
  };
  $scope.answer = function(answer) {
    $mdDialog.hide(answer);
  };
```

```html
 <md-button  ng-click="showAdvanced($event)" class="md-primary md-raised md-secondary" aria-label="Add New Behavior" style="margin-bottom:0px;margin-right:50px">
                                    Add New Behavior
   </md-button>
```

**Comment by DevVersion** [comment]
Can't reproduce your issue - Is it possible that you share a demo using Codepen or something else.

That's a demo, which shows the current usage of the `templateUrl` property.
- http://codepen.io/DevVersion/pen/NxZPxZ
