### ISSUE TITLE
Errors in console when using md-select

### ISSUE THREAD

**Issue by ashwinputhige** [angular/material#7225]
Recently I have started seeing these errors when selecting a value in md-select. I cant figure out whats going on. Is anybody else seeing the same issue?

```
TypeError: undefined is not a function
    at Array.map (native)
    at Object.SelectMenuController.self.selectedLabels (...)
    at Scope.$digest (...)
    at Scope.$apply (...)
    at http://localhost:3000/...
    at completeOutstandingRequest (...)
    at http://localhost:3000/...
```

**Comment by DevVersion** [comment]
Please provide more information, what page are you currently running? What's your source code?

**Comment by ashwinputhige** [comment]
I havent been able to reproduce this in codepen, so I guess its something related to my setup.
