### ISSUE TITLE
$mdInkRipple doesn't clear background color when hovering between buttons

### ISSUE THREAD

**Issue by MexicanAce** [angular/material#7226]
The current Bug I'm seeing is in the following scenario: There are two buttons on the same page that have the $mdInkRipple service enabled by default, Button1 and Button2.

Steps to Reproduce:
1. Click Button1
2. Click Button2 and leave mouse cursor hovered over it. Notice that the background color of Button2 is slightly grey
3. Wait ~1 second for the ripple effect to complete
4. Notice that Button1 will have its background color changed to match Button2

**Comment by MexicanAce** [comment]
Step 1 from above:
![image](https://cloud.githubusercontent.com/assets/1890113/13204370/51b1362e-d89c-11e5-8abe-f1ddbb50df96.png)

Step 2 from above:
![image](https://cloud.githubusercontent.com/assets/1890113/13204376/7b58fa8e-d89c-11e5-9563-85546ef6d156.png)


Step 4 from above:
![image](https://cloud.githubusercontent.com/assets/1890113/13204367/3724bc18-d89c-11e5-99b4-0592531352aa.png)

**Comment by DevVersion** [comment]
@MexicanAce This may be a really unspecific bug, but in my case I can't reproduce that. You mind sharing a little GIF or something else? And maybe tell us the current version you use.

**Comment by MexicanAce** [comment]
Angular Material v 1.0.5

**Comment by MexicanAce** [comment]
http://recordit.co/GaNKa8pSQD

**Comment by ThomasBurleson** [comment]
Unable to reproduce.
