### ISSUE TITLE
semi-colon key code

### ISSUE THREAD

**Issue by shanezheng** [angular/material#7228]
It would be great if we can add semi-colon as a new key code in $mdConstant.KEY_CODE

**Comment by ThomasBurleson** [comment]
Why?

**Comment by shanezheng** [comment]
@ThomasBurleson Because I would like to use semi-colon as a key separator for md-chips. It is quite common to allow semi-colon as a tag separator, for example, stackOverFlow. I am hard-coded the code into my script, but it would be good if it is part of the constant.

**Comment by ThomasBurleson** [comment]
@shanezheng - seems reasonable.

**Comment by ThomasBurleson** [comment]
related to #6505
