### ISSUE TITLE
md-divider md-inset does not listen to rtl

### ISSUE THREAD

**Issue by ofer** [angular/material#7229]
If you set the page to render in rtl, the md-inset still renders the offset on the left side when it should now be the right.

http://codepen.io/anon/pen/yedpOy

**Comment by DevVersion** [comment]
There is already a PR, which adds RTL Support for `md-inset`. See #7245. 

@hosseinkhaledi Can you reference that issue probably?

**Comment by hosseinkhaledi** [comment]
@DevVersion  that solved in #7245

**Comment by DevVersion** [comment]
@hosseinkhaledi That's what I've just said, I just asked you for referencing that issue probably, by modifying the commit message and adding a line like this `Fixes #7229`

**Comment by DevVersion** [comment]
Fixed with SHA 08bf4f9
