### ISSUE TITLE
md-calendar dynamically change min/max-date

### ISSUE THREAD

**Issue by mickej** [angular/material#7230]
I would like to change the values of min-date and max-date. Does not seem to be supported today without reloading the calendar.

My use case is to remove scrolling of the calendar and change the month with swipe and buttons, that could easily be done if the min-date and max-date was changeable.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by stephen-james** [comment]
@mickej I'm not suggesting this is performs well or is a massively good idea, but it is possible (using Angular Material 1.0.9) to add another watch to `mdCalendarMonthDirective` to regenerate content if either of the date limits change...

```
$provide.decorator('mdCalendarMonthDirective', function($delegate) {
    var directive = $delegate[0];

    var originalLinker = directive.link;
    var link = function(scope, element, attrs, controllers) {
        var calendarCtrl = controllers[0];
        var monthCtrl = controllers[1];

        scope.$watch(function() {
            return calendarCtrl.minDate + calendarCtrl.maxDate;
        }, function(range, oldRange) {
            if (range != oldRange) {
                monthCtrl.generateContent();
            }
        })
    };

    directive.compile = function() {
        return function(scope, element, attrs) {
            originalLinker.apply(this, arguments);
            link.apply(this, arguments)
        };
    };

    return $delegate;
});
```

Note: This needs to run in a Angular `config` function.  For 1.10.0 generateContent has moved to `mdCalendarMonthBodyDirective` (from `mdCalendarMonthDirective`)

**Comment by lashisu** [comment]
Is there any update on this?

**Comment by benn0r** [comment]
@lashisu 
@stephen-james workaround works for newer versions too. You just need to use monthBodyCtrl:
`$provide.decorator('mdCalendarMonthBodyDirective', function($delegate) {
            var directive = $delegate[0];

            var originalLinker = directive.link;
            var link = function(scope, element, attrs, controllers) {
                var calendarCtrl = controllers[0];
                var monthBodyCtrl = controllers[2];

                scope.$watch(function() {
                    return calendarCtrl.minDate + calendarCtrl.maxDate;
                }, function(range, oldRange) {
                    if (range != oldRange) {
                        monthBodyCtrl.generateContent();
                    }
                })
            };

            directive.compile = function() {
                return function(scope, element, attrs) {
                    originalLinker.apply(this, arguments);
                    link.apply(this, arguments)
                };
            };

            return $delegate;
        });`
