### ISSUE TITLE
fab-speed-dial animation not working

### ISSUE THREAD

**Issue by mihaellenic** [angular/material#7237]
Here is codepen example of the problem, I've copy-pasted code from fab-speed-dial demo: http://codepen.io/mihaellenic/pen/adgPaL?editors=1010

All buttons are expanded and the animation is not working, clicking on the main button does nothing, same is with other buttons.
I have the same problem in my project, am I doing something wrong?

**Comment by DevVersion** [comment]
That's not a bug, you have a simple error in your project.
Because you use a controller which is bound to the variable `demo`, you should use that in your `ng-controller` attribute too.

Like so - this fixes your issue
```html
<div ng-app="app" ng-controller="mainController as demo">
```

Updated codepen: http://codepen.io/DevVersion/pen/OMedLL?editors=1010

**Comment by mihaellenic** [comment]
omg. 
well, that happens when you just c/p code. maybe it's time to call it a day. thank you for you help and sorry for bothering.
