### ISSUE TITLE
How can I use the example of tabs->demoDynamicHeight ?

### ISSUE THREAD

**Issue by hash-X** [angular/material#7242]
hello angularjs experts, I am a big data programmer. This is my first time to know angularjs and it takes me a lot of time. As title described. I have already git clone this project in my laptop and I want to use the tabs example in my project. In the path of this project ```src->components->tabs->demoDynamicHeight```, I find it what I want. But I trying to figure out how to see the view of this project ? Just open ```index.html``` seems useless. It can only show the original html content and make me very confusing.  Can anyone help me to solve this ? Many many thanks to your's help.

**Comment by DevVersion** [comment]
Hey @hash-X,

You should ask your general question in the Google Group, instead of here.

http://groups.google.com/forum/#!forum/ngmaterial
