### ISSUE TITLE
Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by jaGarcia** [angular/material#7251]
Similar process as #7079 where I retrieve an HTML fragment from the server via AJAX, "compile" it with the function pasted below and I'm getting this error.  It appears that the job to trigger animation on the ng-message is firing before the inputcontainer it belongs to is ready/exists.

![screen shot 2016-02-23 at 10 23 47 am](https://cloud.githubusercontent.com/assets/354362/13256236/d0779724-da17-11e5-8fad-c0cd16915640.png)

 var rootElement = angular.element(document);
    rootElement.ready(function () {
        rootElement.injector().invoke(["$compile", function ($compile) {
            var content;
            if (loadedPanelID == 'body') {
                content = jQuery('body');
            } else {
                content = jQuery("#" + loadedPanelID);
            }

            var scope = angular.element(content).scope();
            $compile(content)(scope);
        }]);
    });

**Comment by jaGarcia** [comment]
I wanted to capture it asap in case others run into it, but haven't had a chance to create a codepen

**Comment by DevVersion** [comment]
@jaGarcia Is it possible that you share your HTML fragement here? - But please keep in mind that a full demo will also help.

**Comment by jaGarcia** [comment]
To see it happening "in the wild" you can go here [https://www.goodshuffle.com/i/21072](url) and click the orange/red "Add to 'My Event' Cart" button.  It happens every time (but doesn't appear to be fatal to rendering/page behavior).  HTML fragment in next comment..

**Comment by jaGarcia** [comment]
Sure thing here is the snippet:
`
<div class="grid-block vertical" ng-controller="EventController as eventCtrl"
     onclick="jQuery(document.documentElement).click();">
    <div class="primary title-bar">
        <div class="center title">Create Event Shopping Cart</div>
        <a href="#" zf-close="" class="right">Cancel</a>
    </div>
    <md-content layout-padding>
        
            <p style="margin-bottom: 0;">
                Shop for multiple events at once (or multiple budgets for one event)!
                <br/>Name this cart for your event to keep things organized.
            </p>
        
        <form id="eventForm" name="eventForm"
              ng-submit="eventCtrl.updateEvent()">
            <div class="grid-content padding" style="padding-top: 1rem;">

                <div>
                    <div layout="column">
                        <md-input-container flex>
                            <label>
                                Event Name (Required)
                            </label>

                            <input type="text" id="eventName" name="eventName" ng-model="eventCtrl.eventName"
                                   required=""/>

                            <div ng-messages="eventForm.eventName.$error" role="alert" ng-messages-multiple
                                 ng-show="eventForm.eventName.$touched || eventForm.$submitted">
                                <div ng-message="required">This field is required.</div>
                            </div>

                        </md-input-container>
                    </div>

                    <div layout-gt-xs="row" layout="column" layout-margin>
                        <div flex>
                            <label>Event Start Date</label>
                            <md-datepicker id="fromDate" ng-model="eventCtrl.fromDate" md-placeholder="Start Date"
                                           md-min-date="eventCtrl.minFromDate"
                                           md-max-date="eventCtrl.maxFromDate"
                                           ng-disabled="eventCtrl.lockDates"></md-datepicker>
                        </div>

                        <div flex layout-margin>
                            <label>Start Time (EST)</label>
                            <select name="fromDateTime" ng-model="eventCtrl.fromDateTime" style="margin-bottom:0;" ng-disabled="eventCtrl.lockDates" id="fromDateTime" >
<option value="">-Start Time-</option>
<option value="12:00 AM" >12:00 AM</option>
<option value="12:30 AM" >12:30 AM</option>
<option value="1:00 AM" >1:00 AM</option>
<option value="1:30 AM" >1:30 AM</option>
<option value="2:00 AM" >2:00 AM</option>
<option value="2:30 AM" >2:30 AM</option>
<option value="3:00 AM" >3:00 AM</option>
<option value="3:30 AM" >3:30 AM</option>
<option value="4:00 AM" >4:00 AM</option>
<option value="4:30 AM" >4:30 AM</option>
<option value="5:00 AM" >5:00 AM</option>
<option value="5:30 AM" >5:30 AM</option>
<option value="6:00 AM" >6:00 AM</option>
<option value="6:30 AM" >6:30 AM</option>
<option value="7:00 AM" >7:00 AM</option>
<option value="7:30 AM" >7:30 AM</option>
<option value="8:00 AM" >8:00 AM</option>
<option value="8:30 AM" >8:30 AM</option>
<option value="9:00 AM" >9:00 AM</option>
<option value="9:30 AM" >9:30 AM</option>
<option value="10:00 AM" >10:00 AM</option>
<option value="10:30 AM" >10:30 AM</option>
<option value="11:00 AM" >11:00 AM</option>
<option value="11:30 AM" >11:30 AM</option>
<option value="12:00 PM" >12:00 PM</option>
<option value="12:30 PM" >12:30 PM</option>
<option value="1:00 PM" >1:00 PM</option>
<option value="1:30 PM" >1:30 PM</option>
<option value="2:00 PM" >2:00 PM</option>
<option value="2:30 PM" >2:30 PM</option>
<option value="3:00 PM" >3:00 PM</option>
<option value="3:30 PM" >3:30 PM</option>
<option value="4:00 PM" >4:00 PM</option>
<option value="4:30 PM" >4:30 PM</option>
<option value="5:00 PM" >5:00 PM</option>
<option value="5:30 PM" >5:30 PM</option>
<option value="6:00 PM" >6:00 PM</option>
<option value="6:30 PM" >6:30 PM</option>
<option value="7:00 PM" >7:00 PM</option>
<option value="7:30 PM" >7:30 PM</option>
<option value="8:00 PM" >8:00 PM</option>
<option value="8:30 PM" >8:30 PM</option>
<option value="9:00 PM" >9:00 PM</option>
<option value="9:30 PM" >9:30 PM</option>
<option value="10:00 PM" >10:00 PM</option>
<option value="10:30 PM" >10:30 PM</option>
<option value="11:00 PM" >11:00 PM</option>
<option value="11:30 PM" >11:30 PM</option>
</select>
                        </div>
                    </div>

                    <div layout-gt-xs="row" layout="column" layout-margin style="margin-top: 2rem;">
                        <div flex>
                            <label>Event End Date</label>
                            <md-datepicker id="toDate" ng-model="eventCtrl.toDate" md-placeholder="End Date"
                                           md-min-date="eventCtrl.minToDate"
                                           md-max-date="eventCtrl.maxToDate"
                                           ng-disabled="eventCtrl.lockDates"></md-datepicker>
                        </div>

                        <div flex layout-margin>
                            <label>End Time (EST)</label>
                            <select name="toDateTime" style="margin-bottom:0;" ng-model="eventCtrl.toDateTime" ng-disabled="eventCtrl.lockDates" id="toDateTime" >
<option value="">-End Time-</option>
<option value="12:00 AM" >12:00 AM</option>
<option value="12:30 AM" >12:30 AM</option>
<option value="1:00 AM" >1:00 AM</option>
<option value="1:30 AM" >1:30 AM</option>
<option value="2:00 AM" >2:00 AM</option>
<option value="2:30 AM" >2:30 AM</option>
<option value="3:00 AM" >3:00 AM</option>
<option value="3:30 AM" >3:30 AM</option>
<option value="4:00 AM" >4:00 AM</option>
<option value="4:30 AM" >4:30 AM</option>
<option value="5:00 AM" >5:00 AM</option>
<option value="5:30 AM" >5:30 AM</option>
<option value="6:00 AM" >6:00 AM</option>
<option value="6:30 AM" >6:30 AM</option>
<option value="7:00 AM" >7:00 AM</option>
<option value="7:30 AM" >7:30 AM</option>
<option value="8:00 AM" >8:00 AM</option>
<option value="8:30 AM" >8:30 AM</option>
<option value="9:00 AM" >9:00 AM</option>
<option value="9:30 AM" >9:30 AM</option>
<option value="10:00 AM" >10:00 AM</option>
<option value="10:30 AM" >10:30 AM</option>
<option value="11:00 AM" >11:00 AM</option>
<option value="11:30 AM" >11:30 AM</option>
<option value="12:00 PM" >12:00 PM</option>
<option value="12:30 PM" >12:30 PM</option>
<option value="1:00 PM" >1:00 PM</option>
<option value="1:30 PM" >1:30 PM</option>
<option value="2:00 PM" >2:00 PM</option>
<option value="2:30 PM" >2:30 PM</option>
<option value="3:00 PM" >3:00 PM</option>
<option value="3:30 PM" >3:30 PM</option>
<option value="4:00 PM" >4:00 PM</option>
<option value="4:30 PM" >4:30 PM</option>
<option value="5:00 PM" >5:00 PM</option>
<option value="5:30 PM" >5:30 PM</option>
<option value="6:00 PM" >6:00 PM</option>
<option value="6:30 PM" >6:30 PM</option>
<option value="7:00 PM" >7:00 PM</option>
<option value="7:30 PM" >7:30 PM</option>
<option value="8:00 PM" >8:00 PM</option>
<option value="8:30 PM" >8:30 PM</option>
<option value="9:00 PM" >9:00 PM</option>
<option value="9:30 PM" >9:30 PM</option>
<option value="10:00 PM" >10:00 PM</option>
<option value="10:30 PM" >10:30 PM</option>
<option value="11:00 PM" >11:00 PM</option>
<option value="11:30 PM" >11:30 PM</option>
</select>
                        </div>
                    </div>

                    <div layout="column" flex layout-margin>
                        <md-input-container flex>
                            <label class="control-label">Event Address</label>
                            <input type="text" name="eventAddress" ng-model="eventCtrl.eventAddress" class="address-autocomplete_bind" ng-enter="" value="" id="eventAddress" />

                        </md-input-container>
                        <input type="hidden" name="eventAddress_name" ng-model="eventCtrl.eventAddress_name" value="" id="eventAddress_name" />
                        <input type="hidden" name="eventAddress_street" ng-model="eventCtrl.eventAddress_street" value="" id="eventAddress_street" />
                        <input type="hidden" name="eventAddress_zipCode" ng-model="eventCtrl.eventAddress_zipCode" value="" id="eventAddress_zipCode" />
                        <input type="hidden" name="eventAddress_city" ng-model="eventCtrl.eventAddress_city" value="" id="eventAddress_city" />
                        <input type="hidden" name="eventAddress_county" ng-model="eventCtrl.eventAddress_county" value="" id="eventAddress_county" />
                        <input type="hidden" name="eventAddress_state" ng-model="eventCtrl.eventAddress_state" value="" id="eventAddress_state" />
                        <input type="hidden" name="eventAddress_country" ng-model="eventCtrl.eventAddress_country" value="" id="eventAddress_country" />
                    </div>
                </div>

                <div layout-gt-xs="row" layout="column">
                    
                    
                    
                    
                    <div layout-margin>
                        <select ng-model="eventCtrl.eventType" placeholder="Select Event Type"
                                ng-options="eventType.key for eventType in eventCtrl.eventTypes track by eventType.value">
                            <option value="">- Select an Event Type -</option>
                        </select>
                    </div>
                    <md-input-container flex layout-margin>
                        <label>Head Count</label>
                        <input type="text" name="headCount" ng-model="eventCtrl.headCount" value="" id="headCount" />
                    </md-input-container>

                </div>

                <div>
                    <input type="submit" class="button expand" value="Save" ng-hide="eventSpinnerMode"/>
                    <md-progress-circular ng-show="eventSpinnerMode"
                                          md-mode="{{eventSpinnerMode}}"></md-progress-circular>
                </div>
            </div>
        </form>
    </md-content>
</div>

<script type="application/javascript">
    jQuery(document).on("focus", ".address-autocomplete_bind:not(.hasAddressAutoComplete)", function () {

        var addressField = jQuery(this);

        if (!addressField.hasClass("address-autocomplete_set")) {
            console.log(this.id + " address needs autocomplete initialized. intitializing.");

            initializeAddressAutoComplete(this.id, null, false);
            addressField.addClass("address-autocomplete_set");
        }
    });

    app.controller('EventController', ["$scope", "$http", "$global", function ($scope, $http, $global) {
        this.eventSpinnerMode = null;
        this.lockDates = false;

        this.eventTypes = 
[
  {
    "key": "Corporate Event",
    "value": "CORPORATE"
  },
  {
    "key": "Fair / Festival",
    "value": "FAIR_FESTIVAL"
  },
  {
    "key": "Non-Profit / Charity Event",
    "value": "NON_PROFIT_CHARITY"
  },
  {
    "key": "Other Event",
    "value": "OTHER"
  },
  {
    "key": "Private Party",
    "value": "PRIVATE_PARTY"
  },
  {
    "key": "Wedding",
    "value": "WEDDING"
  }
];

        this.eventType = '';

        this.headCount = "";

        var now = new Date();

        
        this.eventName = null;
        


        
        this.fromDate = new Date('Feb 24 2016');
        this.fromDateTime = "";
        

        
        this.toDate = new Date('Feb 24 2016');
        this.toDateTime = "";
        

        if (this.fromDate.getTime() === this.toDate.getTime()) {
            var from = Date.parse($scope.eventCtrl.fromDateTime);
            var to = Date.parse($scope.eventCtrl.toDateTime);
            if (to < from) {
                this.toDateTime = null;
            }
        }

        this.eventAddress = "";
        this.eventAddress_name = "";
        this.eventAddress_street = "";

        this.eventAddress_zipCode = "";
        this.eventAddress_city = "";
        this.eventAddress_state = "";
        this.eventAddress_county = "";
        this.eventAddress_country = "US";

        this.minFromDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
        this.minToDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());


        //prevent toTime being set before fromTime when from/to are on same day.
        $scope.$watch("eventCtrl.toDateTime", function (newVal, oldVal) {
            //this prevents watch from firing after initial page load
            if (newVal === oldVal) return;


            if ($scope.eventCtrl.fromDate && $scope.eventCtrl.toDate && $scope.eventCtrl.fromDate.getTime() === $scope.eventCtrl.toDate.getTime()) {

                var from = Date.parse($scope.eventCtrl.fromDateTime);
                var to = Date.parse($scope.eventCtrl.toDateTime);

                if (to < from) {
                    $scope.eventCtrl.toDateTime = null;
                    showDynamicNotification('Back to the Future', 'End date/time must be later than the Start date/time',
                            4000, 'bottom-right', 'warning');

                }
            }
        });

        $scope.$watch("eventCtrl.fromDate", function (newVal, oldVal) {
            //this prevents watch from firing after initial page load
            if (newVal === oldVal) return;

            if (newVal) {
                $scope.eventCtrl.minToDate = newVal;
            } else {
                $scope.eventCtrl.minToDate = new Date(now.getFullYear(), now.getMonth(), now.getDate());
            }

            if ($scope.eventCtrl.toDate < $scope.eventCtrl.fromDate) {
                $scope.eventCtrl.toDate = $scope.eventCtrl.fromDate;
            }

        });


        this.createEvent = function () {
            var eventNameVal = this.eventName;
            this.eventSpinnerMode = "indeterminate";

            $http({
                method: "POST",
                url: '/order/createActiveOrder?createNew=false',
                data: jQuery.param({

                    eventName: eventNameVal,
                    fromDateStr: dateToString(this.fromDate),
                    toDateStr: dateToString(this.toDate),
                    fromDateTimeStr: this.fromDateTime,
                    toDateTimeStr: this.toDateTime,
                    eventAddress_name: this.eventAddress_name,
                    eventAddress_street: this.eventAddress_street,
                    eventAddress_zipCode: this.eventAddress_zipCode,
                    eventAddress_city: this.eventAddress_city,
                    eventAddress_state: this.eventAddress_state,
                    eventAddress_county: this.eventAddress_county,
                    eventAddress_country: this.eventAddress_country,
                    eventType: this.eventType.value,
                    headCount: this.headCount
                })

            }).then(function successCallback(response) {
                $scope.eventCtrl.eventSpinnerMode = null;

                if (response.status == 200) {

                    $scope.$root.showConfigureDialogOnOpen = false;

                    $global.setActiveOrder(response.data.orderID, eventNameVal, false, $scope);


                    jQuery("#cartItemCount").html(eventNameVal);

                    setVisibilityFoundationDirective('createEventModal', 'hide');
                } else {
                    console.log("error calling service. status=" + response.status + ", text=" + response.statusText);
                }
            });
        };


        this.updateEvent = function () {
            var eventNameVal = this.eventName;

            console.log("calling update event.");

            $http({
                method: "POST",
                url: '/order/updateOrderInfo',
                data: jQuery.param({
                    orderID: null,
                    eventName: eventNameVal,
                    fromDateStr: dateToString(this.fromDate),
                    toDateStr: dateToString(this.toDate),
                    fromDateTimeStr: this.fromDateTime,
                    toDateTimeStr: this.toDateTime,
                    eventAddress_name: this.eventAddress_name,
                    eventAddress_street: this.eventAddress_street,
                    eventAddress_zipCode: this.eventAddress_zipCode,
                    eventAddress_city: this.eventAddress_city,
                    eventAddress_state: this.eventAddress_state,
                    eventAddress_county: this.eventAddress_county,
                    eventAddress_country: this.eventAddress_country,
                    eventType: this.eventType.value,
                    headCount: this.headCount
                })

            }).then(function successCallback(response) {
                if (response.status == 200) {

                    var cartPanelContent = jQuery('#cartPanelContent');
                    if (cartPanelContent.size() > 0) {
                        cartPanelContent.html(response.data);
                        compileAngular("cartPanelContent");

                        jQuery("#cartItemCount").html(eventNameVal);
                    }

                    $global.reloadContentBody();

                    setVisibilityFoundationDirective('createEventModal', 'hide');
                } else {
                    console.log("error calling service. status=" + response.status + ", text=" + response.statusText);
                }
            });
        };

    }]);
</script>`

**Comment by DevVersion** [comment]
@jaGarcia This may be related to your steps of compilation. Can you try appending the uncompiled element into the visible DOM and then compiling it?

**Comment by jaGarcia** [comment]
That's actually the order I'm doing it.  I attempted to do a pre-compile, of sorts, before attaching it to the DOM but the angular state of things got wacky.  Here's what a typical ajax call pulling a fragment looks like (I'm using grails):

 $http({
                method: "POST",
                url: "${g.createLink(controller:'aggregateItem', action:'toggleAggregateItemAvailability')}",
                data: jQuery.param({
                    id: itemID
                })
            }).then(function successCallback(response) {
                if (response.status == 200) {
                    jQuery("#itemStatus_" + itemID).html(response.data);
                    compileAngular("itemStatus_" + itemID);
                } else {
                    console.log("error calling service. status=" + response.status + ", text=" + response.statusText);
                }
            });

**Comment by jaGarcia** [comment]
Better yet, here is the exact function I'm calling when the error I pasted above occurs.  In the use case, a renter is opening an event to edit it's metadata, name, head count, etc.


 createUpdateEvent: function (isLoggedIn, createNew, activeOrderIsConfigured, orderID, lockDates) {

                if (!isLoggedIn && activeOrderIsConfigured && createNew) {
                    setVisibilityFoundationDirective('loginToCreateMoreEvent', 'show');
                    return;
                }


                angular.element("#createEventModal").html('<md-progress-circular md-mode="indeterminate"></md-progress-circular>');
                compileAngular('createEventModal');

                setVisibilityFoundationDirective('createEventModal', 'show');

                $http({
                    method: "POST",
                    url: '/order/loadCreateUpdateOrderModal',
                    params: {
                        orderID: orderID,
                        createNew: createNew == true,
                        //allowClose: allowClose == true,
                        lockDates: lockDates
                    }
                }).then(function successCallback(response) {

                    if (response.status == 200) {

                        var createEventModal = jQuery('#createEventModal');
                        if (createEventModal) {
                            createEventModal.html(response.data);
                            compileAngular("createEventModal");
                        }


                    } else {
                        console.log("error calling service. status=" + response.status + ", text=" + response.statusText);
                    }
                });
            },

**Comment by DevVersion** [comment]
Oh well, can you try compiling the plain template string (like `$compile(MY_FRAGMENT_STRING)(scope)`) and maybe share the `compileAngular`

**Comment by jaGarcia** [comment]
Compiling just the plain template string is what I attempted in that "pre-compile" step I mentioned, where I tried compiling the fragment before attaching it to the DOM, but that created a funky state where angular scope variables still attached to the DOM were colliding with ones not yet attached.  

Here is the compileAngular function, you'll notice I have a little code to wipe out md-tooltips on a DOM element that's being replaced as since they appear out-of-line with the DOM element they're related to.

function compileAngular(loadedPanelID) {

    console.log("compileAngular('" + loadedPanelID + "')");


    var rootElement = angular.element(document);
    rootElement.ready(function () {
        rootElement.injector().invoke(["$compile", function ($compile) {
            var content;
            if (loadedPanelID == 'body') {
                content = jQuery('body');
            } else {
                content = jQuery("#" + loadedPanelID);
            }

            var scope = angular.element(content).scope();
            $compile(content)(scope);
        }]);
    });


    clearTimeout(toolTipPurgeTimeout);
    //remove any straggler tooltips that existed in partial that is being swapped out.
    toolTipPurgeTimeout = setTimeout(function () {
        console.log("purge straggler md-tooltip");
        jQuery("md-tooltip").remove();
    }, 250);


}

**Comment by DevVersion** [comment]
The thing I figured out, is that the element is not added to the visible DOM at compilation, that may be the issue. 

![Img](https://i.gyazo.com/866615d2c8ca240faca4ce7f5c27a7de.png)

Take a look at the console, the element is not appended to the DOM.

**Comment by jaGarcia** [comment]
But I'm curious how that's possible when it seems I'm clearly attaching the partial to the DOM before calling 'compile'.  What's more, I just tried putting the ajax call inside a setTimeout with a delay of 2000 to make sure the call to setVisibilityFoundationDirective('createEventModal', 'show'); that shows the modal had completed.  Even then, I'm still getting the error.  So, the modal element is clearly visible, I'm attaching the partial to the DOM, calling compile, don't have any ng-if's or ng-show's hiding the eventName field and it's still showing the element isn't appended to the DOM....?

  createEventModal.html(response.data);
                            compileAngular("createEventModal");

**Comment by jaGarcia** [comment]
it may be unrelated, but is odd to me, that when the modal pops up the ng-message showing that the field is required, is showing by default even though the form hasn't been touched (since it just loaded).  So, it's weird that the field things that it needs to trigger the ng-message animation when for all intents it hasn't been touched/shouldn't be dirty..

**Comment by DevVersion** [comment]
Maybe the modal will keep its content not in the visible DOM, can you try that one time without the modal?

**Comment by jaGarcia** [comment]
For full disclosure, I'm performing this wizardry since the partial I'm pulling back has an angular controller defined in it that I need to register after bootstrap has already occurred. 

       //https://gist.github.com/bennadel/7302417
        app._controller = app.controller;

        // Provider-based controller.
        app.controller = function (name, constructor) {
            console.log("calling post bootstrap registration of controller.");
            $controllerProvider.register(name, constructor);
            return ( this );
        };

**Comment by jaGarcia** [comment]
The DOM element I'm stuffing the partial into, is contained in a file _cartPanel.gsp.  That file holds the DOM element:

<md-backdrop class="md-sidenav-backdrop md-opaque md-default-theme disabled" style="z-index: 501;"></md-backdrop>
<md-sidenav class="md-sidenav-right md-whiteframe-z2 lg" md-component-id="cartPanel" ng-cloak>

    <div id="cartPanelContent" class="cart-panel" ng-controller="CartPanelController as cartCtrl"
         onclick="jQuery(document.documentElement).click();" ng-cloak>
        <g:render template="/order/cartPanelContent" model="[currentUser: currentUser, activeOrder: activeOrder]"/>
    </div>
</md-sidenav>

<div zf-modal="" id="createEventModal" class="collapse" overlay-close="false" ng-cloak>

</div>

Now, when the cartPanel is opening, it detects if it needs to trigger the modal, like so:

    this.isOpen = function () {
                return false;
            };

            $mdComponentRegistry
                    .when('cartPanel')
                    .then(function (sideNav) {
                        $scope.cartCtrl.isOpen = angular.bind(sideNav, sideNav.isOpen);
                        $scope.cartCtrl.toggle = angular.bind(sideNav, sideNav.toggle);
                    });

            $scope.$watch("cartCtrl.isOpen()", function (newVal, oldVal) {
                if (newVal) {
                    //fired when panel is opening
                    jQuery("#sidebar").css("z-index", 399);

                    if ($scope.$root.cartOptions.configModalOnOpen) {
                        $global.createUpdateEvent(${currentUser != null}, false, false, $scope.cartCtrl.activeOrderID);
                    }
                } else {
                    //fired when panel is closing
                    jQuery("#sidebar").css("z-index", 500);
                }
            });



So... if the cartPanel md-sidenav is visible enough to trigger the isOpen state, its bizarre that it's sibling DOM element "createEventModal" isn't....

If I use a setTimeout to delay the compilation is appears to reduce the likelihood of the error, but now I'm just playing around with a race condition:

   setTimeout(function() {
                                compileAngular("createEventModal");
                            }, 500);

**Comment by jaGarcia** [comment]
In case anyone is wondering jQuery's html() is a synchronous operation. I just looked it up to confirm.

And the fact that a loading throbber I show is visible on the screen (which inside the same "#createEventModal" DOM element it can't be that the DOM element isn't visible... right?  right?!  :(

**Comment by DevVersion** [comment]
@jaGarcia I created a demo of your issue and everything works fine. 
- The demo contains a delayed fake `http` request and uses a snippet of your provided HTML Fragment as the template

So I can't reproduce your issue and it seems to relate to your configuration.. even its not a bug of `ngMaterial`, so I will close that issue. If there any updates and a demo of your issue that shows the error, then I'll reopen that issue.

**Comment by jaGarcia** [comment]
Ok, thanks for giving it a shot!  I think the issue is related to, and it's weird to see it happening, that when that template loads (as you can see in your example) you can see the ng-message flash and then hide itself.
