### ISSUE TITLE
Radio Button Group Layout gets changed when files are compressed via gulp

### ISSUE THREAD

**Issue by jayeshanandani** [angular/material#7253]
Here are few screen shots which show radio button CSS when combined via gulp for minification results in invalid CSS which chrome doesn't understand and it creates alignment issues.

<img width="454" alt="screen shot 2016-02-24 at 12 47 51 am" src="https://cloud.githubusercontent.com/assets/3860787/13263697/c061ff36-da90-11e5-97ee-d0a0e5b249e3.png">

<img width="323" alt="screen shot 2016-02-24 at 12 48 19 am" src="https://cloud.githubusercontent.com/assets/3860787/13263682/a0858f16-da90-11e5-9ec4-c4a12f8ea37f.png">

**Comment by ThomasBurleson** [comment]
The online docs https://material.angularjs.org/latest/demo/radioButton uses minified CSS without any issues. Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by jayeshanandani** [comment]
@ThomasBurleson : This is same as #6472. The radio button should not have inherit in margin-left which causes issue for radio buttons.

**Comment by jayeshanandani** [comment]
@ThomasBurleson : The online docs https://material.angularjs.org/latest/demo/radioButton uses minified file but in gulp automation, we minify the main CSS and on minifying the file via gulp plugin it results into the above posted CSS.
