### ISSUE TITLE
md-select is missing md-input-focused class on its md-input-container when field is focused

### ISSUE THREAD

**Issue by mpiasta-ca** [angular/material#7254]
If you have a form with `<md-input>` and `<md-select>` fields, as you tab through the fields, the `<md-input-container>` parent is supposed to be updated with an "md-input-focused" class.

However, when the user has tabbed onto an `<md-select>` field with no value selected yet, the `md-input-focused` class is not set. 

Only after the user selects a value, then if you tab back-and-forth between that `<md-select>` field, will you see the `md-input-focused` class begin to be set.

**Reproduce bug:**
1. Go to: https://material.angularjs.org/latest/demo/select
2. In the "Basic Usage" block, inspect the "Street name" field using "Google Chrome Developer Tools" (F12). You should be able to see the `<md-input-container>` parent element for this field, as well as for the two neighboring fields.
3. Now focus your cursor into the "Street name" field. You should see it's parent container updated with a class "md-input-focused".
4. Now tab into the "City" field. You will see the "md-input-focused" class removed from the "Street name" parent element, and now it will be on the "City" parent element.

![md-select-focus-1](https://cloud.githubusercontent.com/assets/672103/13265997/c78a3938-da2a-11e5-9dc5-01750402d0ef.png)
5. Now tab again, you should now be focused on the "State" `<md-select>` field.  You will see the "md-input-focused" class removed from the "City" parent element, and now it SHOULD be on the "State" parent element. BUT, notice that the parent DOES NOT show an "md-input-focused" class.

**Notice:**
6. Select any "State" value (ie. "CA"). 
7. Now if you repeat Steps 2 to 5, you will notice that as you tab into the "State" field THIS TIME, the parent class DOES become update with "md-input-focused" class. Therefore, this bug only appears when user tabs into an unset `<md-select>` field.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by mpiasta-ca** [comment]
Tested and this issue is now fixed in `bower install angular-material#master`.
