### ISSUE TITLE
md-select is missing md-input-invalid class on its md-input-container when field is blurred

### ISSUE THREAD

**Issue by mpiasta-ca** [angular/material#7255]
Demo: http://codepen.io/anon/pen/xZvXoM

**Reproduce bug:**
1. Inspect the "Your name" field so you can see the `<md-input-container>`.
2. Focus your cursor into the "Your name" field. Do not type anything, leave it blank.
3. Tab to the "Favorite Number" field, but do not open the list and do not select any options. Notice how the parent `<md-input-container>` for "Your Name" field is updated with a new class "md-input-invalid".

![md-select-invalid-class-1](https://cloud.githubusercontent.com/assets/672103/13265820/e8ccd1ec-da29-11e5-9aed-202d7d64c4ef.png)
4. Now hit tab again to leave the "Favorite Number" field. Notice that the `<md-input-container>` parent of "Favorite Number" is NOT updated with the expected class "md-input-invalid".

**Notice (1):**
5. If you NOW tab from the "Your name" field into "Favorite Number" field (meaning you tab through the field set a second time)...
6. And you tab again to blur from the "Favorite Number" field, NOW the `<md-input-container>` parent for "Favorite Number" will be updated with the "md-input-invalid" class.

**Notice (2):**
7. Refresh the codepen page to clear the form.
8. Click the "Submit" button (do not focus or type into any fields before doing this).

![md-select-invalid-class-2](https://cloud.githubusercontent.com/assets/672103/13265832/faef5066-da29-11e5-9c73-9d4ca7de5c8d.png)
9. Notice that the `<input>` container manages to display its error message. But `<md-select>` container fails to display its error message. Likely caused because of the missing "md-input-invalid" class.

**Notice (3)**:
![md-select-invalid-class-3](https://cloud.githubusercontent.com/assets/672103/13265848/07da7c6a-da2a-11e5-9f14-efabe75cfa3c.png)
10. When you manage to get the error message to display for the `<md-select>` container (by tabbing in-and-away two times), the border-bottom on the field remains gray (expected color is red).

**Comment by sdesmond** [comment]
It looks like this did not make it into the 1.0.6 release, correct?

**Comment by mpiasta-ca** [comment]
@sdesmond nope, still broken.

**Comment by volmerf** [comment]
Any progress on this bug?

**Comment by michelem09** [comment]
+1

**Comment by neclamis1285** [comment]
+1

**Comment by fabrizio5680** [comment]
+ 1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by adonaicruz** [comment]
Use `pattern=".{1,}"` instead `required` to fix it

**Comment by adonaicruz** [comment]
Use pattern=".{1,}" instead required to fix it

**Comment by mpiasta-ca** [comment]
Tested and this issue is now fixed in `bower install angular-material#master` branch.
