### ISSUE TITLE
md-select focuses on itself if an option is selected that is rendered above an md-input on mobile Safari in full screen mode

### ISSUE THREAD

**Issue by ramirezd42** [angular/material#7256]
The steps to reproduce are kind of demanding, but you can see what I’m talking about if you go to the following plunkr on an iOS device with Safari:
http://run.plnkr.co/plunks/jnh532MDoYIGsPdGlw27/

The click the share button and select “Add to Home Screen”.

A shortcut for the page is added to your desktop. Launch from the shortcut, touch on the md-select menu and pick whichever option is placed directly over the text input. The menu closes but the keyboard pops up and focuses on the select element.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
