### ISSUE TITLE
Tabs are counted twice with Chromevox

### ISSUE THREAD

**Issue by xaro** [angular/material#7258]
If reading through a page with tabs (the tabs demo for example), Chromevox will report twice the amount of tabs that are actually present (saying "Selected tab 5 of 8" when you actually selected the first of 4).

I suspect this is because of the hidden tabs created in the DOM, which Chromevox counts towards the total.

Is this a known issue?

**Comment by ThomasBurleson** [comment]
@robertmesserle - thoughts?

**Comment by robertmesserle** [comment]
@ThomasBurleson Hm, sounds like it's seeing the hidden tabs that are used to capture focus.  I'm not sure if we tested with Chromevox.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
