### ISSUE TITLE
md-select multiple mode ， The selected values will overflow value box

### ISSUE THREAD

**Issue by baihuibo** [angular/material#7259]
![1](https://cloud.githubusercontent.com/assets/5130197/13277556/a531ea0e-db04-11e5-975f-9b60e5aa568f.png)

-- When I choose multiple values, display the contents of the overflow box
![2](https://cloud.githubusercontent.com/assets/5130197/13277567/b048969a-db04-11e5-809b-e40c27e0c06f.png)

----
The current display value style  `flex:1 0 auto;`
![3](https://cloud.githubusercontent.com/assets/5130197/13277644/6c726896-db05-11e5-9048-3267f7374462.png)

I will adjust it  `flex: 1 1 auto;`, after normal
![4](https://cloud.githubusercontent.com/assets/5130197/13277647/7302e4a6-db05-11e5-9284-d5c05f306b01.png)

angular-material version : 1.0.5

**Comment by DevVersion** [comment]
Please provide a demo, which represents your issue.

**Comment by baihuibo** [comment]
@DevVersion 
Thank you , has been resolved in the new version

**Comment by DevVersion** [comment]
@baihuibo Thank's for letting me know.
