### ISSUE TITLE
Internet Explorer Compatibility?

### ISSUE THREAD

**Issue by evanpaschke** [angular/material#726]
Angular 1.3 is [Internet Explorer Compatible](https://docs.angularjs.org/guide/ie) back to IE9. I understand [Flexbox Layout](http://caniuse.com/#feat=flexbox) is only supported from IE11.

The [readme](https://github.com/angular/material/blob/master/README.md) mentions 'evergreen' browser support (including IE). 

What is the planned IE compatibility for Angular Material? Does it include IE9-10 or just IE11+?

**Comment by jadjoubran** [comment]
@evanpaschke you can just include a polyfill for IE9 via conditional comments and you're good to go.
http://en.wikipedia.org/wiki/Progressive_enhancement

**Comment by raDiesle** [comment]
@jadjoubran can you give a more detailed explanation, how to polyfill? Which polyfills are required ? I will give it a try.

**Comment by ThomasBurleson** [comment]
Please post these conversations in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
