### ISSUE TITLE
$mdOpenMenu() have someMethod let me use ng-mouseout can close the md-menu?

### ISSUE THREAD

**Issue by zhougonglai** [angular/material#7260]
sorry,my boos let me ask this questions!
he can't speck english ,so did i~``

**Comment by ThomasBurleson** [comment]
Currently not supported; easily added to support `ng-mouseout="$mdMenu.close()"`; where the `$mdMenu` is published to the $rootScope just like `$mdMedia`.


Pull Requests welcome!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
