### ISSUE TITLE
md-card responsive

### ISSUE THREAD

**Issue by mohammad6006** [angular/material#7264]
when I use md-card like this:

```
<md-card>
	lorep ipsum
</md-card>


```
it doesnt width 100% : 
![](http://s29.postimg.org/v035o5d9z/download11.png)

but when I use other codes like <p> before outside or inside of md-card it 

```
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<md-card>

     inside md card : lorem ipsum

</md-card>

```

![](http://s29.postimg.org/b6r1vfzw7/download12.png)

I want to have responsive image in view but it doesnt responsive when i use below code without usign p code or other codes in my view page

```
 <md-card>
        <img ng-src="{{imagePath}}" class="md-card-image" alt="Washed Out">
</md-card>

```

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
