### ISSUE TITLE
Integrations with Ionic

### ISSUE THREAD

**Issue by furyscript** [angular/material#7265]
I search a lot but I don't find when Angular Material will be integrate with Ionic.

Can you ask me?
Thanks

**Comment by DevVersion** [comment]
You already asked me that question in issue #7203, I don't think that ngMaterial will be made compatible with Ionic in the near future.

**Comment by ThomasBurleson** [comment]
not supported.

**Comment by furyscript** [comment]
Ah thank you, I did not understand eh.... pff @ThomasBurleson
