### ISSUE TITLE
Is is possible to access theming with classes?

### ISSUE THREAD

**Issue by shaundon** [angular/material#7266]
Currently, I can apply the colours from my theme to certain elements. For example, a button:
`<md-button class="md-primary">Button</md-button>`

However, to use theme colours arbitrarily, I need to place the theme colours into my stylesheets. For example:

```
@theme-primary-colour: #5abe57;
.md-primary-color {
  color: @theme-primary-colour;
}
.md-primary-background {
  background: @theme-primary-colour;
}
```

..and then I can use the themes on any element, for example a heading:

`<h1 class="md-title md-primary-color">Heading</h1>`

The issue with this approach is that it requires the theme colours to be defined in multiple places - both the `.config` block of my app, and my stylesheets.

Is there any way to do this 'out of the box'? I've noticed that ngMaterial injects stylesheets for theming into the `<head>` of the page - is there anything in there which can be applied arbitrarily on any element? If not, is this something the community would consider adding? 

I'm happy to implement this myself, but I'd like to check that it's got a good chance of being merged first.

Thanks 📐

**Comment by ThomasBurleson** [comment]
See https://material.angularjs.org/HEAD/Theming/03_configuring_a_theme sections: Specifying Custom Hues For Color Intentions
