### ISSUE TITLE
TypeError: $mdMedia is not a function

### ISSUE THREAD

**Issue by vrghost242** [angular/material#7267]
Not certain if I am doing this wrong, but stole an example to open modal straight from the documentation

Get the following error message
TypeError: $mdMedia is not a function

The code that causes it
```
angular.module('test', ['ngMaterial', 'ui.router', 'colorpicker.module', 'jdFontselect', 'ngMdIcons'])
.controller('indexController', ['$scope', function($scope,$mdDialog, $mdMedia) {
    var originatorEv;
    //Not certain what this does, but lets add it
    $scope.customFullscreen = $mdMedia('xs') || $mdMedia('sm');
```

Am I missing to load something or is this an issue

Version 
/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v1.0.1
 */

**Comment by DevVersion** [comment]
This seems to be an issue with your `Strict DI`, if you that, then you need to add the injected service name to the array. Like so
```js
.controller('indexController', ['$scope', '$mdDialog', '$mdMedia', function($scope,$mdDialog, $mdMedia) {

```

**Comment by vrghost242** [comment]
That worked amazingly well, should probably have tested that first to come to think of it. 

Thank you very much:)

**Comment by DevVersion** [comment]
Great, if everything works great, then it would be great if you close the issue :)
