### ISSUE TITLE
mdSlider: Ticks rendering only after screen resize

### ISSUE THREAD

**Issue by stinaq** [angular/material#7268]
When `md-discrete` is set there are ticks showing, but they only show up after the screen is resized, not from the beginning. 
According to[ this spec](https://www.google.com/design/spec/components/sliders.html#sliders-continuous-slider) the ticks should show up on click, but they don't.

Can be seen [here on codepen](http://codepen.io/stinaq/pen/obKmLM) as well as on the demo site. On the codepen the ticks are not visible when page is loaded, but as soon as the output window is resized, they show up.

Reproduced in Firefox, Chrome, Edge, Chrome on iPhone.

Angular material v1.0.5

**Comment by nitnoy** [comment]
+1

**Comment by DevVersion** [comment]
@EladBezalel Can you take look at this issue, may that relate to your PR? #6538

**Comment by EladBezalel** [comment]
it's in there :)

**Comment by DevVersion** [comment]
Fixed with SHA e0abeb4dc46a1753616a911fe54f14d8f1148a25
