### ISSUE TITLE
mdSelect causes pages to jump

### ISSUE THREAD

**Issue by jayeshanandani** [angular/material#7273]
Opening a new issue since issue #1648 has been closed but this issue still persist in latest release 1.0.5.

**Comment by mpiasta-ca** [comment]
I don't see the issue in the codepen. Not in Chrome, Firefox, or even Firefox/Android. How do you reproduce it?

However, I am experiencing a jumping issue with the app I am building hen using md-select, but only in Firefox/Android (v.44.0.2).

**Comment by jayeshanandani** [comment]
I think this is due to ng-message bug. When you focus on select the ng-message appears instantly in background which causes UI to jump a little. Ideally ng-message should be displayed when focus is removed from select dropdown.

**Comment by jayeshanandani** [comment]
#6351 this seems to be related one I suppose.

**Comment by jayeshanandani** [comment]
In addition I found this: #5256 which was fixed earlier. But seems some commit has reintroduced the bug.

**Comment by gusnips** [comment]
+1

**Comment by topherfangio** [comment]
I believe this will be fixed by #7646. Can anyone confirm?

**Comment by jayeshanandani** [comment]
Yes this will be fixed by #7646

**Comment by jayeshanandani** [comment]
I believe #7646 has been merged and it should resolve this. Hence closing issue.
