### ISSUE TITLE
radio-button: Controller 'mdRadioGroup', required by directive 'mdRadioButton', can't be found

### ISSUE THREAD

**Issue by Misiu** [angular/material#7275]
I'm trying to build custom directive that uses Angular Material directive inside.
My idea is to have main directive that will have conditional template. In that template I'd like to use my custom directives that have Angular Material Directives inside.

I've managed to create prototype of desired functionality, but I get error:

> Controller 'mdRadioGroup', required by directive 'mdRadioButton', can't be found

Here is my directive:

```
.directive('question', function($compile) {
  var combo = '<div>COMBO - {{content.text}}</div>';
  var radio = [
    '<div>RADIO - {{content.text}}<br/>',
    '<md-radio-group layout="row" ng-model="content.answer">',
    '<md-radio-button ng-repeat="a in content.answers track by $index" ng-value="a.text" class="md-primary">{{a.text}}</md-radio-button>',
    '</md-radio-group>',
    '</div>'
  ].join('');
  var input = [
    '<div>INPUT - {{content.text}}<br/>',
    '<md-input-container>',
    '<input type="text" ng-model="content.answer" aria-label="{{content.text}}" required md-maxlength="10">',
    '</md-input-container>',
    '</div>'
  ].join('');

  var getTemplate = function(contentType) {
    var template = '';

    switch (contentType) {
      case 'combo':
        template = combo;
        break;
      case 'radio':
        template = radio;
        break;
      case 'input':
        template = input;
        break;
    }

    return template;
  }

  var linker = function(scope, element, attrs) {

    scope.$watch('content', function() {
      element.html(getTemplate(scope.content.type))
      $compile(element.contents())(scope);

    });
  }

  return {
    //require: ['^^?mdRadioGroup','^^?mdRadioButton'],
    restrict: "E",
    link: linker,
    scope: {
      content: '='
    }
  };
})
```

I've created [this Plunker](http://plnkr.co/edit/t0HJY51Mxg3wvvWrBQgv?p=preview) to show my issue. Just click Next button two times and see error in console.

I've asked this question on [StackOverflow](http://stackoverflow.com/questions/35504567/angular-material-controller-mdradiogroup-required-by-directive-mdradiobutt) but I didn't get any responses that would helped me with resolving that issue so I thought this might be a bug or (probably) I have error in my code.

If I remove md-radio-group and md-button everything works fine.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by Misiu** [comment]
Sorry for asking in wrong place. I've created topic in ngmaterial group: https://groups.google.com/forum/#!topic/ngmaterial/OVZIeOEMLeQ

**Comment by Misiu** [comment]
@ThomasBurleson I think this might be an error in Material.
As I wrote before after removing material directives everything works.
I've got one answer on SO: http://stackoverflow.com/a/35509199/965722 that suggests it is problem with $index in mdRadioGroup.
I've asked several people to help me find bug in my code, but they didn't found anything that could be the cause of that error.

I've created [second Plunker](http://plnkr.co/edit/fq6nTXGYBT8oJSkvOFIE?p=preview) that shows my error.
On top I'm showing all questions using **ng-repeat** and below (on blue background) I have one question at a time. After clicking **Next question** two times I get error in console.

This must be Angular Material that cause that error.

Could You please reopen this Issue?

**Comment by Misiu** [comment]
@ThomasBurleson I've created a bounty on SO, but I didn't get any answer related to my issue.
On ngMaterial group I also didn't get any answer.
Could You please take a look on this issue?

**Comment by Splaktar** [comment]
I've asked an AngularJS compiler expert to look into this.

**Comment by Splaktar** [comment]
@marosoft thanks! That looks promising, I'll dig into that a bit more.

**Comment by Splaktar** [comment]
Answered here: https://stackoverflow.com/questions/35504567/contidional-template-controller-mdradiogroup-required-by-directive-mdradio#answer-52311046
