### ISSUE TITLE
Dialog resizes content inside when it shouldn't

### ISSUE THREAD

**Issue by secretgspot** [angular/material#7279]
Added a 600x600 image and dialog decided to shrink it to and display 580x580
problem is amplified when doing something like 

```html
<md-dialog-content class="creative-content" layout="column" layout-align="center center">

I want the dialog to size up, not shrink content down. 


  md-dialog-content class="creative-content" layout="column" layout-align="center center" flex>

    <!-- image -->
    <img ng-if="creative.picture.mimeType.indexOf('image/') != -1"
      id="imageCard" ng-class="{invisible: hideImgWhileLoading}"
      ng-src="{{creative.picture.url}}"
      sb-load="onImgLoad($event)"
      width="{{creative.size.width}}"
      height="{{creative.size.height}}" />

    <!-- flash -->
    <flash-viewer ng-if="creative.picture.mimeType == 'application/x-shockwave-flash' || creative.picture.mimeType == 'application/vnd.adobe.flash.movie'"
      file="{{creative.picture}}"></flash-viewer>

    <!-- html-->
    <iframe ng-if="creative.picture.mimeType == 'text/html-ad-tag'"
      ng-src="{{creative.picture.url}}"
      width="{{creative.size.width + 22}}"
      height="{{creative.size.height + 22}}"
      frameBorder="0" scrolling="no"></iframe>

    <!-- video -->
    <video ng-if="creative.picture.mimeType.indexOf('video') > -1"
      class="video-preview" controls alt="{{creative.name}}"
      ngf-src="creative.picture.url"
      width="{{creative.size.width}}"
      height="{{creative.size.height}}"></video>

    <fieldset class="message" ng-class="log.status" ng-if="log" ng-messages='form.$error && log' ng-messages-multiple>
      <div ng-message='status == "fail"'>{{log.data}}</div>
      <div ng-message='status == "error"'>Request  Failed! Try Again.</div>
    </fieldset>
  /md-dialog-content>

```

**Comment by secretgspot** [comment]
doesn't matter what I put in, it'll reside it to something that is not original size and if I force original size then dialog creates scroll bars for just few pixels.   In other cases where there is obviously enough space on a side and top/bottom, dialog chooses to present ugly horizontal scroll-bars


![dialog1](https://cloud.githubusercontent.com/assets/203323/13308627/9cf34b86-db3a-11e5-8634-7efd0d21c514.PNG)
![dialog2](https://cloud.githubusercontent.com/assets/203323/13308628/9cf93dca-db3a-11e5-824c-bca2680b5875.PNG)

**Comment by secretgspot** [comment]
additionally image being cut off when max-width is set to initial, thus resetting image size hold. 
Unable to view the top part of the image and or scroll to it.  Why is that? 

![dialog3](https://cloud.githubusercontent.com/assets/203323/13309945/25562e42-db47-11e5-9151-ec21bba00388.PNG)

**Comment by ajoslin** [comment]
Try setting flex-shrink: 0 on your content.

**Comment by secretgspot** [comment]
didn't have any effect setting that property on newly added div.md-dialog-content that wraps the images and videos.   Resizing problem was fixed with adding that div.md-dialog-content and setting image max-width:initial  however on video it still cuts off as shown in 3rd screenshot with the image where I am unable to scroll to the top of the image as shown in screen-shot bellow.

![cutsoff](https://cloud.githubusercontent.com/assets/203323/13334862/b05d7c48-dbd3-11e5-8b49-faa6e905cc0c.PNG)

if you can see, I am unable to see portion of the video or get to the Play/Stop control

**Comment by secretgspot** [comment]
when I remove layout="column" from parents, then it works, if I enable any layout, then it becomes like this

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
