### ISSUE TITLE
mdSlider: First move of slider has graphical bug (leaves trace)

### ISSUE THREAD

**Issue by stinaq** [angular/material#7280]
When a slider is first moved it leaves a graphical trace behind. Can be seen [on this codepen](http://codepen.io/stinaq/pen/obKmLM) as well as in the following gif:

![2016-02-25_08-53-33](https://cloud.githubusercontent.com/assets/1426788/13313415/f80ea070-db9d-11e5-8949-4c40e8286308.gif)

Occurs in Firefox only, not in Chrome, IE11, Chrome on iPhone or Edge.
Angular Material v1.05

**Comment by EladBezalel** [comment]
@stinaq Can you please check this again against HEAD, Slider went through some changes :)

**Comment by stinaq** [comment]
I have now checket against master HEAD locally, but unfortunately have the same issues as before, though it seems to have lessend somewhat.
![2016-03-17_12-11-09](https://cloud.githubusercontent.com/assets/1426788/13844317/5ee61778-ec39-11e5-89b9-0caf89071d5b.gif)

**Comment by stinaq** [comment]
Ping @EladBezalel

**Comment by EladBezalel** [comment]
@stinaq can confirm, couldn't find the solution yet..

**Comment by ThomasBurleson** [comment]
Working on HEAD.
