### ISSUE TITLE
Foreground variables

### ISSUE THREAD

**Issue by oknechirik** [angular/material#7281]
I have question for you. Are you planning to give us access to **foreground** variables through theme process?
Just adding fifth theme to existing four (4 -- e.g. primary, accent, warn and background).
Thank you for answering

**Comment by ThomasBurleson** [comment]
The foreground color is accessed via the primary or accent palettes within the Theme.
No changes planned for now.

**Comment by wingedfox** [comment]
Hi,
The question is not in the foreground colors themselves, but in the possibility to override them in theme for cases when they are used as background colors, e.g.
```
.md-button.md-THEME_NAME-theme.md-fab[disabled] {  background-color: '{{foreground-4}}';
```
At this point there's no way to define or override the foreground colors.

We'd be glad to provide a PR for this if you have an implementation guide.

**Comment by aprocom** [comment]
Hi, it will be great to have option to override it!
