### ISSUE TITLE
Carousel like directive for angular material

### ISSUE THREAD

**Issue by ishankhare07** [angular/material#7282]
After searching on the web and reading replies like `material design spec does not have carousel` I encountered [material design carousel design.google.com/resources/](https://design.google.com/resources/)

![screenshot from 2016-02-25 15-05-24](https://cloud.githubusercontent.com/assets/7482025/13315563/66f83202-dbd1-11e5-81a2-90c44cf7ea43.png)

It might not be in the spec but its being used on the site that documents the spec itself.
Is this a good enough reason to have such a directive?

I would also like to shed light to something very similar to a carousel, that's also document in the spec, and not available in Angular material - [Steppers](https://www.google.com/design/spec/components/steppers.html)

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B7WCemMG6e0VZV9JT1hKVjJwcFE/components_acux_stepper_mbldots.png)

**Comment by ThomasBurleson** [comment]
A Pull Request would be welcomed!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
