### ISSUE TITLE
md-autocomplete: md-autofocus not focusing input.

### ISSUE THREAD

**Issue by flea89** [angular/material#7283]
Passing md-autofocus="true" to the md-autocomplete directive has no effect: the input doesn't get focused.

Material version 1.0.5

Live example: http://codepen.io/anon/pen/ZQgZgp

thanks.

**Comment by DevVersion** [comment]
That's not the right use of the `md-autofocus` directive. As you can read [here](https://material.angularjs.org/latest/api/directive/mdAutofocus), the element will be only auto-focused when a `bottomsheet`, `dialog` or `sidenav` opens.

**Comment by flea89** [comment]
Thanks for this, that's good to know, however is not made really clear by the docs.
If you have a look [here](https://material.angularjs.org/latest/api/directive/mdAutocomplete) doesn't really imply that it works in that scenario only.

Might be reasonable to add some more info there ?

**Comment by DevVersion** [comment]
@flea89 Yes indeed, it seems that the actual directive documentation is really clear, instead of the reference in the `autocomplete` documentation, which seems really unclear.

**Comment by DevVersion** [comment]
@flea89 Can you take a look at #7290, is this description more clear to you?
