### ISSUE TITLE
Fab dial stops working when placed in the container which has its visibility dynamically changed from hidden to visible.

### ISSUE THREAD

**Issue by velja** [angular/material#7287]
Fab dial stops working when placed in the container which has its visibility dynamically changed from hidden to visible.

The example is dirty but shows the problem.

http://codepen.io/anon/pen/jqNwZZ

To eliminate the problem just remove:

ng-hide="demo.hide"
or change js line:

this.hide=true;
to

this.hide=false;
Thanks

**Comment by topherfangio** [comment]
@velja Is this possibly a duplicate of #6789?

**Comment by velja** [comment]
Possible. I will check in the morning.

**Comment by velja** [comment]
Removing ng-cloak from container resolves it but there is another bug that makes fab dial open and then it has to be clicked 2 times. I think I saw that ticket here already.
