### ISSUE TITLE
tabs: md-on-select triggered too often in directive

### ISSUE THREAD

**Issue by robotnic** [angular/material#7288]
Not sure if this is a bug or I do something wrong
http://plnkr.co/edit/Ii6gGN?p=preview

md-on-select triggers for unselected tabs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
