### ISSUE TITLE
Accordion Component

### ISSUE THREAD

**Issue by naumanahmed19** [angular/material#7289]
Hi,

I am testing angular material and so far its looking great. Is there any accordion/collapse component available. I couldn't find in docs

**Comment by DevVersion** [comment]
This may be the same as a stepper? See #5241 - can you confirm?

**Comment by jayeshanandani** [comment]
@DevVersion I believe mdStepper and accordion should be different. Accordion is more like toggle and collapse without any dependency on any steps.

**Comment by naumanahmed19** [comment]
@jayeshanandani is right.

**Comment by jayeshanandani** [comment]
#1861 in progress I believe. We should be tracking that in order to know status of component :)

**Comment by topherfangio** [comment]
Although we do not have a component at this time, our own Material Docs site has something very similar. You can see how this was implemented in the `menuToggle` directive here: https://github.com/angular/material/blob/master/docs/app/js/app.js#L467

Closing as duplicate of #1861.
