### ISSUE TITLE
$mdToast: toast never goes away if a previous toast exists

### ISSUE THREAD

**Issue by denver-HJS** [angular/material#7296]
I've added a fairly simple toast function to my $rootScope so that I can easily provide user feedback throughout my app. I've come across a scenario where my app is trying to toast two messages in succession. I know that the app flow can be tweaked to avoid this, but in my mind an optimal solution would be to display all toast notifications (perhaps above/below each other)

I thought maybe using $mdToast.hide() before showing any new toast would resolve this behavior but no such luck.

```
/**
       * Displays a toast message to the user in the top right corner of the screen
       * @param msg The message to be displayed
       * @param duration The length of time in seconds that the message will display
       */
      $rootScope.toast = (msg, duration = 3) => {
        var _duration = duration * 1000;
        $mdToast.hide(); // Having multiple toasts displayed at once will cause the latest toast to never disappear
        $mdToast.show(
          $mdToast.simple()
            .content(msg)
            .position("top right")
            .hideDelay(_duration)
            .parent(".header-wrapper")
        );
      };
```

**Comment by ThomasBurleson** [comment]
@denver-HJS - Toast displays will autoHide the current toast before showing the next. Toast **stacking** is a feature that is planned but not yet available: #2799
