### ISSUE TITLE
Dynamic pallets

### ISSUE THREAD

**Issue by Kratos-SA** [angular/material#7299]
I know there is a function that allows you to switch between themes. And I know a work around for dynamic themes is to just declare in the config then use it. But I have dynamic pallets that once I have assigned to the theme I need to run the same $mdTheming function in the config that updates the head section with all the relevant styles. Is there a function that I can call or is there a update coming out soon with this ability.

With calling the function I know there is an existing function in the core library but how would you access it?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
