### ISSUE TITLE
mdToolip: issue with mdVisible in fabDial

### ISSUE THREAD

**Issue by evoker** [angular/material#7300]
I've been using the demo codepen from the speed dial as a playground to make tooltips always visible after the parent button has been pressed: http://codepen.io/anon/pen/KzPjvy

But had no luck so far. After I took a dive in the code, I think the issue lies with this bit:

`$document[0].activeElement !== parent[0]`

Scrolling from speed dial button to speed dial button, this return false. The activeElement is the trigger button, while parent[0] is the speed dial button (children). Because of that, this always returns true even with md-autohide set to false.

My objective is to show all tooltips like in the demo after the menu opens but to remain showing after the user rolls over them. That doesn't happen now since mdVisible seems to "bug out" or gets confused.

**Comment by LarsVonQualen** [comment]
Hi,
does anyone know what the actual line of code is there for? And how come this has been marked as an edge case when it clearly makes the autohide feature unusable in the case where you want to disable autohiding? :sweat_smile:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by LarsVonQualen** [comment]
I really think this issue should be reconsidered, seeing that it actually affects the FAB Speed Dial demo codepen too http://codepen.io/anon/pen/VjYzyX

I can see that it has been labeled as an edge case, but again considering the fact that this feature has been shown in the demo, i think this issue should be investigated further.

Cheers :beer:
