### ISSUE TITLE
md-subheader dynamically show sticky header

### ISSUE THREAD

**Issue by pdore-netfore** [angular/material#7303]
Is there a way to dynamically 'stick' the subheader?

I have a list of 'n' Users, and looking for a way to 'stick' the User's details when editing it.

I've tried a couple solutions:

**Solution 1**
`
<md-subheader ng-if="isEditingContent">
  ...
</md-subheader>`
**Solution 2**
`
<md-subheader ng-class="{!isEditingContent: 'md-no-sticky'}">
  ...
</md-subheader>`

Both solutions work if `isEditingContent` is `true` on initial load, but the 'stickiness' is not changing with the boolean.

**Comment by topherfangio** [comment]
I don't think there is any way to support this currently, but we will look into it.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
