### ISSUE TITLE
icons spin classes

### ISSUE THREAD

**Issue by miguelcobain** [angular/material#7305]
At ember-paper we are using Angular Material Scss. We've added classes to make icons spin (like font-awesome). Here is the PR: https://github.com/miguelcobain/ember-paper/pull/302

I wonder if such a feature would be interesting upstream?
And if not, why?

Thanks.

**Comment by DevVersion** [comment]
Hey @miguelcobain,

Is this anywhere specified in the [Material Specs](https://www.google.com/design/spec/material-design/introduction.html)?

Would be great if you take a look :)

**Comment by miguelcobain** [comment]
Well, not explicitly, but there is this paragraph:

> Animation can exist within all components of an app and at all scales, from detailed icons to key transitions and actions.

Source:
https://www.google.com/design/spec/animation/delightful-details.html

**Comment by DevVersion** [comment]
@miguelcobain Awesome, thanks!

![animation_delightfuldetails_wellcrafted](https://cloud.githubusercontent.com/assets/4987015/13905503/a4cb11f0-eec1-11e5-8920-b7e5283ddb6f.gif)

**Comment by topherfangio** [comment]
@miguelcobain I think this could be a useful feature. If you're still interested, feel free to create a PR :+1:

**Comment by miguelcobain** [comment]
@DevVersion @topherfangio What I'm proposing isn't a functionality like the one present in @DevVersion's comment.
It is a simple icon rotation class using css. The icon rotates while that class is present.

**Comment by topherfangio** [comment]
@miguelcobain Indeed; it is just like the `fa-spin` class in FontAwesome right?

**Comment by DevVersion** [comment]
@topherfangio Take a look at this [diff](https://github.com/miguelcobain/ember-paper/pull/302/files#diff-09fbe7d518b06d14576d4a6e072f8ba2R59)

**Comment by topherfangio** [comment]
@DevVersion Yeah, that just adds a CSS animation to spin the icon. I understand that it is not like the transform that you linked to above, but I still think it might be a useful PR. Particularly if you wanted a refresh icon or something similar and didn't want to use the default circular progress indicator for some reason.

**Comment by DevVersion** [comment]
@miguelcobain Are you working on a Pull Request?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
