### ISSUE TITLE
Gesture drag on md-list-item prevents list from scrolling on iOS

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#7311]
Hey there,
I have built a custom directive for achieving the Dismiss gesture, [as documented in the Material Design spec](http://www.google.com/design/spec/patterns/gestures.html#gestures-drag-swipe-or-fling-details).

The directive registers a `drag` gesture with `$mdGesture` in the element, currently an `<md-list-item>`:

![](http://i.imgur.com/NdJhcCN.gif)

Because of the registered `drag` gesture, **I can't scroll this list** in my iPad 2 (I don't have other iOS devices to test this). This behavior can be observed in Safari, Firefox and Chrome for iOS.

**Comment by DevVersion** [comment]
This won't be related to the actual `md-list` component, it may relate to your implementation of the `$mdGesture` service in your directive. I can take a look, if you share a few code snippets or maybe a demo.

**Comment by gustavohenke** [comment]
@DevVersion there you go: http://codepen.io/gustavohenke/pen/grOrWq

Open in an iOS device.

**Comment by gpopovic** [comment]
Nice job man !! Hopefully this gets into library

**Comment by DevVersion** [comment]
@gustavohenke Just wanted to let you know, this issue issue is in progress.

**Comment by Vercryger** [comment]
@gustavohenke Did it work? @ThomasBurleson I still having the same issue.
