### ISSUE TITLE
md-datepicker input size doesn't fit placeholder

### ISSUE THREAD

**Issue by viktarkorshun** [angular/material#7313]
I found the issue where datepicker input size doesn't reflect size of placeholder, so if placeholder is longer then 120px it looks corrupted(http://codepen.io/anon/pen/JXjKXe).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
