### ISSUE TITLE
Flex IE10 Support?

### ISSUE THREAD

**Issue by attila226** [angular/material#7314]
My understanding that Angular Material supports the n-1 version of current browsers. What's not clear if Edge is considered the most recent version, and therefore IE 11 is n-1, or if IE 11 is considered the most recent version, and therefore IE 10 is in fact support. A clear and definitive answer would be much appreciated.

**Comment by LeoLozes** [comment]
I saw it in the docs at some point. The supported versions were Edge and Internet Explorer 11. I suppose it remains the same.

**Comment by mpiasta-ca** [comment]
It works in IE10 with small fix:

```
@media screen and (min-width:0\0) {
  span[flex], md-card-content, md-dialog-content {
    display: block;
  }
}
```

You may also need to set `display: block;` on some other flex containers on an as-needed basis.

**Comment by attila226** [comment]
Thanks, I was able to get things to work in IE 10 with some tweaking. What would be great is a definitive answer on if IE 10 is officially supported by Angular Material or not. Our site works with IE 10, although the  behavior isn't always consistent with the other browsers.

**Comment by topherfangio** [comment]
We do not currently support IE10. There was a recent thread on the forums with more information: https://groups.google.com/forum/#!searchin/ngmaterial/IE10/ngmaterial/U-gmDd5_jq8/0N6jovrYDAAJ
