### ISSUE TITLE
Using Material Design with a treeview

### ISSUE THREAD

**Issue by kasajian** [angular/material#7315]
Here's an example that uses the Angular Material with ivh-treeview so that the checkboxes and icons are from material design:

http://codepen.io/kasajian/pen/MyWyMo

**Comment by DevVersion** [comment]
Is that a feature request or an issue? 
BTW:  really nice demo :+1:

**Comment by kasajian** [comment]
@DevVersion It's neither one.  I figure, if anyone else was looking for how the two can be integrated, would probably look at the issues list and search for "treeview" or ivh-treeview and would find this comment, and save themselves a few hours.   

But the again, having said that, maybe what this is is a "feature request" against the documentation to have a section where one can post "unsupported, third-party integration" so that we can just add things like this to that section.

Feel free to close this issue.

**Comment by DevVersion** [comment]
That's great, thanks for sharing these things with the community! 

I'm not sure about an extra section for the docs, but in general I think it would be great to have a place to share things with the community. Maybe those things can be shared in the Google Group ([here](https://groups.google.com/forum/#!forum/ngmaterial))

I'll close that issue because it's not actually an issue, but I'll ask about a good place to share these type of things. In general, if now someone searches the issue list, he'll find your issue. So thanks :)

**Comment by faustomorales** [comment]
Thanks so much for the demo! I think your mdBox directive can do without the explicit reference to the treeview source object. Indeed, I think that in most cases that object is defined in a controller scope and is unavailable globally the way it is in your example. Fortunately, everything we need is in the node scope already. We also avoid a `$scope.$apply()` this way.

For completeness, here's the current code.

```
app.directive('mdBox', function(ivhTreeviewMgr) {
  return {
    restrict: 'AE',
    template: [
      '<span class="ascii-box">',
        '<span ng-show="node.selected" class="x"><md-checkbox style="min-height: 100%; line-height: 0" aria-label="checked" ng-checked="true"></md-checkbox></span>',
        '<span ng-show="node.__ivhTreeviewIndeterminate" class="y"><md-checkbox style="min-height: 100%; line-height: 0" aria-label="checked" ng-checked="false"></md-checkbox></span>',
        '<span ng-hide="node.selected || node.__ivhTreeviewIndeterminate"><md-checkbox style="min-height: 100%; line-height: 0" aria-label="checked" ng-checked="false"></md-checkbox></span>',
      '</span>',  
    ].join(''),
    link: function(scope, element, attrs) {
      element.on('click', function() {
        ivhTreeviewMgr.select(stuff, scope.node, !scope.node.selected);
        scope.$apply();
      });
    }
  };
});
```

And here's my recommended revision.

```
app.directive('mdBox', function() {
  return {
    restrict: 'AE',
    template: ['same as above'].join(''),
    link: function(scope, element, attrs) {
      element.on('click', function() {
        scope.trvw.toggleSelected(scope.node);
      });
    }
  };
});
```
