### ISSUE TITLE
FAB toolbar blocking buttons while closed.

### ISSUE THREAD

**Issue by tharekmohtar** [angular/material#7317]
If a button is placed (or any clickable element) alongside the fab toolbar it blocks the button since it has a higher z-index. This happens even if the toolbar is collapsed.

**Comment by 0101adm** [comment]
+1

**Comment by topherfangio** [comment]
Indeed, the FAB Toolbar should support the `md-hover-full` class like the FAB Speed Dial, or come up with an alternate method of display which doesn't cause this issue.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
