### ISSUE TITLE
Off Canvas Sidebar

### ISSUE THREAD

**Issue by naumanahmed19** [angular/material#7323]
Sidebar component works great. Is this possible to create offcanvs push effect as explain in this demo http://codepen.io/ncerminara/full/KJjiD/

**Comment by topherfangio** [comment]
It's not currently supported out of the box, but I accomplished something similar here: http://codepen.io/topherfangio/pen/KVOZqO/?editors=0110

Also, there is an open request for this in #6411, so I am going to close as a duplicate.
