### ISSUE TITLE
Time picker needed

### ISSUE THREAD

**Issue by jpike88** [angular/material#7326]
Take a look at this, he's built off angular material and it might be useful for time selections
https://github.com/logbon72/angular-material-datetimepicker

**Comment by DevVersion** [comment]
This is a dupe of #5029

**Comment by jpike88** [comment]
It might be a dupe issue, but that link shows a pretty impressive implementation. I'll post it in the other one

**Comment by DevVersion** [comment]
Yeah, that's great, everything you wan't to pin to the Timepicker should be done in #5029.
