### ISSUE TITLE
Subheader Demo - Inconsistency/disappears when scrolling

### ISSUE THREAD

**Issue by Hammild** [angular/material#7328]
1. Open the menu
2. Select Subheader in the demo area
3. Scroll once, and observe that the subheader disappears
4. Scroll again, and observe that the subheader appears

Tested on:
Desktop, Win7E SP1
Browser: Google Chrome 48.0.2564.116 m

**Comment by topherfangio** [comment]
Very inconsistent. It should always disappear when scrolling (because it has `md-scroll-shrink`), but it only works sometimes. Need to investigate.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
