### ISSUE TITLE
Demo - Doesn't load correct

### ISSUE THREAD

**Issue by Hammild** [angular/material#7330]
An error occurs if the previous page isn't done loading.
E.g:
1. Open the menu
2. Select Tabs
3. Before it's done loading, select Toolbar. Observe that the page now looks like Tabs, but the header says Toolbar.

Tested on:
Desktop, Win7E SP1
Browser: Google Chrome 48.0.2564.116 m

**Comment by DevVersion** [comment]
Related to `md-tab-item` by using `$animate`

**Comment by topherfangio** [comment]
Possibly related to #4388.

**Comment by ThomasBurleson** [comment]
I think we need to stop the animations during a $destroy process.

**Comment by DevVersion** [comment]
This seems not to occur anymore. Please recheck.
