### ISSUE TITLE
Toasts appear in the same position regardless of settings (mobile device)

### ISSUE THREAD

**Issue by runethh** [angular/material#7332]
How to reproduce:
1. Go to Toast in the Demo area
2. Change "Toast position" to e.g. "Top" and "Right"
3. Click "Show simple"
4. Observe that the toast is displayed in the buttom regardless of settings

Tested on
Angular Material version 1.0.5
Model: Motorola Nexus 6
Browser: Chrome version 47
Operating System: Android 5.1.1 (Lollipop)

Note that this works well on a desktop

**Comment by Nuajan** [comment]
+1 Same here.

**Comment by DevVersion** [comment]
This is by intention, we decided to show the toast at the bottom if the current device is `small` (breakpoint)

Code line: [here](https://github.com/angular/material/blob/master/src/components/toast/toast.js#L386)

**Comment by Nuajan** [comment]
Well, found that it can be solved by overriden style
@media (max-width: 959px) {
  md-toast { ...
and changing bottom: 0; to top: 0,
So you can apply it to specific requirements of your proyect by not modifiying framework.
Don´t now if it's the best practice but works.
Thanks, @DevVersion
