### ISSUE TITLE
Virtual repeat: Container does not fit on screen on mobile device

### ISSUE THREAD

**Issue by runethh** [angular/material#7333]
How to reproduce:
1. Go to Virtual Repeat in the Demo area
2. Observe that the container is wider than the viewable area (and thus it's possible to scroll horisontally).

Tested on
Angular Material version 1.0.5
Model: Motorola Nexus 6
Browser: Chrome version 47
Operating System: Android 5.1.1 (Lollipop)

**Comment by topherfangio** [comment]
The CSS for the Horizontal Usage demo has the width of the scroller set to `830px` which is wider than the demo container on mobile. Should be able to add `max-width: 100%` or something to fix it.
