### ISSUE TITLE
md-autocomplete multiselect

### ISSUE THREAD

**Issue by uxitten** [angular/material#7334]
hi
i design multiselect with md-autocomplete please help me for complete this design
have a problem

http://codepen.io/itten/pen/reaNYd?editors=1010

**Comment by topherfangio** [comment]
I see a few issues with your demo, but can you tell us what problems you are trying to fix?

**Comment by uxitten** [comment]
thank @topherfangio i fixed, but this feature release by Material Design

**Comment by topherfangio** [comment]
Glad you got it fixed. Are you requesting that we add some new functionality to match something in the spec? If so, can you provide a link to the spec?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
