### ISSUE TITLE
md-tabs inside md-toolbar. md-tabs next to other elements inside md-toolbar

### ISSUE THREAD

**Issue by FilipPoreba** [angular/material#7336]
I want to have md-tabs within md-toolbar and i use solution provided by Sithdown in https://github.com/angular/material/issues/1076

It works fine for me, but my problem is that i need to have md-tabs next to other elements inside md-toolbar, but for now, md-tabs is always underneath of other elements, just like that:

Image example: http://imgur.com/SSVaet9

My code on Plunker: http://plnkr.co/edit/guKrRzB9F34mlFDqj4AS?p=preview

**Comment by HamletHakobyan** [comment]
I'm interested for this, too.

**Comment by topherfangio** [comment]
Can you not just specify `layout="row"` on the toolbar? http://plnkr.co/edit/iyq3DVaUSquaQLAgqPE5?p=preview

**Comment by topherfangio** [comment]
@FilipPoreba I'm going to go ahead and close this due to inactivity. If my Plunkr didn't meet your needs, please post a comment and we can reopen.
