### ISSUE TITLE
Buttons are not working in Firefox.

### ISSUE THREAD

**Issue by pniraula** [angular/material#7338]
With new updates from 1.0.5-master-5cf32d0 buttons are not working in md-list. (Firefox)

**Comment by DevVersion** [comment]
That's caused because bb5c10575aeb439a5dc33001ac674fd1611f85ef isn't released yet. It wasn't a patch, so it will be only available in the next release.

**Comment by gpopovic** [comment]
Yep..and buttons also doesn't work on IE 11.
I received angry calls this morning because of this bug :)

**Comment by DevVersion** [comment]
Everything works as expected in `master`. Can anyone confirm that this is fixed in `master`?

**Comment by DevVersion** [comment]
Everything works as expected in `HEAD`.
