### ISSUE TITLE
Chips: The graphic disappears when using the input field (mobile device)

### ISSUE THREAD

**Issue by runethh** [angular/material#7339]
How to reproduce:

1. Go to the demo area on Angular Material site
2. Select Chips
3. In the "Use Placeholders and override hint texts" area type in some random letters.
4. Observe that the graphics on the chips above disappear (leaving only the x'es left).

Tested on:
Version: Angular Material 1.0.5
Model: Ipad mini (ME279KN/A)
Browser: Safari 9
Operating system: Safari 9.1 (13B143)

**Comment by runethh** [comment]
On a similar note: 

The graphic in the area "Contact Chips" also disappears when scrolling up and down on that page.

**Comment by topherfangio** [comment]
Seems to be fixed in 1.1.0-RC1. Please comment if you're still having trouble after upgrading and we will reopen.
