### ISSUE TITLE
md-tabs. md-selected works only as initial value. Then it watches after ng-click="$mdTabsCtrl.select(tab.getIndex())"

### ISSUE THREAD

**Issue by levgaas** [angular/material#7341]
I have more complicated scenario when I need to select active tab based on `md-selected="vm.someVariable"`

As far as I read the code. You place the watcher for **$mdTabsCtrl.selectedIndex**. 
Then after `ng-click="$mdTabsCtrl.select(tab.getIndex())"` tab is selected. 

But in my case each tab is a state. And I need some checkings before I go to another state (tab). But selection lives own life without connection to `md-selected="vm.someVariable"` because of `tab.getIndex()`

Replacing line **23730** in angular 1.5.0. with `if (!locked) ctrl.focusIndex = index;` **helps**. 

```
function select (index) {

    // if (!locked) ctrl.focusIndex = ctrl.selectedIndex = index;     <------------- this one

    if (!locked) ctrl.focusIndex = index;                          // <------------- to this one

    ctrl.lastClick = true;
    // nextTick is required to prevent errors in user-defined click events
    $mdUtil.nextTick(function () {
      ctrl.tabs[ index ].element.triggerHandler('click');
    }, false);
  }
```

Please point me to another solution if it exists or think about providing such functionality.

Thanks!

**Comment by levgaas** [comment]
**UPDATE:**

Also this is good solution if state has big computations (huge amount of watchers etc). Because if tab "lives own life" **md-ink-bar** transition becomes intermittent. If we depend on $watcher everything seems to be fine.

**Comment by topherfangio** [comment]
I'm having a difficult time understanding what exactly you want/need. Could you provide a Codepen demo which shows the issue?

**Comment by levgaas** [comment]
@topherfangio seems like it's my bad. If you do so the selection of the tab is clicked won't work.

What I need is to run some validation code to check if user can change the tab before it actually changes(selects)

For example, There are 3 tabs: 
Step 1, Step 2, Step 3;

And user cannot jump from first tab to third. Only prev / next.

Normally, I would do some validations and then change value of `vm.variable` in `ng-click` where `md-selected="vm.variable"` 

It would be a good option to write some directive which overrides default behavior of `select on click`
 if md-selected was specified.

Maybe I use tabs in a place they haven't developed for.

Thanks!

**Comment by topherfangio** [comment]
Perhaps you can use `<md-tab ng-disabled="true">` instead of trying to do it on click?

https://material.angularjs.org/HEAD/api/directive/mdTab

**Comment by levgaas** [comment]
@topherfangio Ok. Thanks I'll look at it.
