### ISSUE TITLE
md-chips md-on-add not working

### ISSUE THREAD

**Issue by beazergood** [angular/material#7342]
I've tried getting this to work and from what I can tell it's setup correctly. md-on-remove works but md-on-add isn't

Am I missing something or is it broken?

Codepen: http://codepen.io/beazergood/pen/BKyKeX?editors=1010

Thanks!

**Comment by TinusJ** [comment]
Could not replicate even with your codepen. It works if you press enter and might need to add some code to auto enter when done typing.

**Comment by beazergood** [comment]
I have updated my codepen and set the md-on-add function to alert the chip that was just entered and it never fires. It works on removing the chip but I'm unable to obtain what chip has just been added.

**Comment by topherfangio** [comment]
@beazergood The `md-on-add` callback was added fairly recently, it looks like your Codepen is using v0.11.4 which only had the `md-on-append` callback available, and it worked a bit differently.

Please upgrade to the latest version of Material or you can view the [0.11.4 docs](https://material.angularjs.org/0.11.4/api/directive/mdChips) and see the usage of the `md-on-append`.

Last note: it looks like the Codepen you provided also had different versions of the JS (0.11.4) and the CSS (0.10.0). Should't make much of a difference for your Codepen, but it would definitely cause problems if you do that in your app :smile:

**Comment by beazergood** [comment]
Bingo. Sorry for wasting your time. Thanks though!

**Comment by topherfangio** [comment]
@beazergood Not a problem! ;-)
