### ISSUE TITLE
mdDialog: "escapeToClose: false" does not work

### ISSUE THREAD

**Issue by caferrari** [angular/material#7343]
I am still able to close the dialog with the escape key when this setting is set to false.

```
$mdDialog.show({
  templateUrl: '/view/flow/manager.html',
  controller: 'Flow.ManagerCtrl',
  clickOutsideToClose: false,
  escapeToClose: false,
  targetEvent: $event,
  locals: {
    cancel
  }
});
```

**Comment by DevVersion** [comment]
Works perfect for me in `HEAD` - http://codepen.io/DevVersion/pen/xVbXjr

**Comment by caferrari** [comment]
Just tested with the master branch and it's working, probably was a bug on v1.0.5.

Thanks.
