### ISSUE TITLE
mdDatepicker validation issue in IE11

### ISSUE THREAD

**Issue by rvarbanov** [angular/material#7344]
This is a very strange issue with the datepicker that I could find a way to solve.

My setup:
Angular 1.4.9
MD 1.0.5
OS Win 7
Browser: IE11

The issue:
I have a model that takes a start date that I use the md-datepicker for. It works fine when you are to enter a date for the first time, but if you are to update the date the validation breaks. It will load the date in the md-datepicker but will show it as an invalid date.
```js
$valid: false
$viewValue: "2016-02-29T20:55:05.232Z"
$modelValue: "2016-02-29T20:55:05.232Z"
```

As you can see, there is already a date object. If I am to click on the calendar icon and select the same date the validation passes.

I also observe that when the dialog opens the date is valid, but it get set to invalid in the next moment. It feels like something is setting the `$valid` to `false` after loading the dialog.

Do you have any idea what could be doing that only in IE11?

Appointment Controller:
```js
'use strict';

const angular = require('angular'),
	app = angular.module('crm');

app.controller('AppointmentDetailsController',
	function ($scope, $mdDialog) {
		$scope.onEditClicked = function (ev) {
			$mdDialog.show(
				{
					controller: 'AppointmentDetailsDialogController',
					templateUrl: 'partials/dialogs/appointment-details-dialog.html',
					parent: angular.element(document.body)
				}
			).then();
		};
	}
);
```

Dialog Controller:
```js
'use strict';

const angular = require('angular'),
	app = angular.module('crm');

app.controller('AppointmentDetailsDialogController',
	function ($scope) {
		$scope.dateT = new Date();
	}
);
```
**EDIT:** Tested with `<input type="date">` and that worked fine, so it is not angular.

**Comment by topherfangio** [comment]
Can you please provide a Codepen which demonstrates the issue so we can test it on IE?

**Comment by jltrem** [comment]
Here is a codepen for what appears to be the same issue:  http://codepen.io/jltrem/pen/RaZMde
Working in Chrome & FF.  Problem exists in IE 11.

Changing the date by typing into the input (e.g., from 3/30/2016 to 3/31/2016) $error.valid is set.  Selecting the same date from the picker works fine.  If I first clear the date so that $error.required is set and then type in a date, it is successful.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by harmoniemand** [comment]
I was able to solve it by using a custom validation.

https://gist.github.com/harmoniemand/d6fd7aec43224ae4010f8791bf391aa0

And it is important to set the settings for $mdDateLocaleProvider correctly.
