### ISSUE TITLE
iPad keyboard and a md-select

### ISSUE THREAD

**Issue by chrisajohn** [angular/material#7345]
We are seeing an issue with the keyboard interaction on an ipad.  You can replicate the same error here:  https://material.angularjs.org/latest/demo/input

The issue is that when you lose focus on an input box by clicking on the md-select, the keyboard goes away and the md-select values float away from the md-select.

To replicate (on an ipad in horizontal mode via the link above):
 - only scroll down until you can see the postal code input at the bottom of the screen (don't scroll all of the way up)

![1](https://cloud.githubusercontent.com/assets/16691486/13410920/fb036fe4-deff-11e5-8a91-cbe89dab7a77.jpg)

 - tap the postal code input (keyboard should appear)

![2](https://cloud.githubusercontent.com/assets/16691486/13410927/01aaf2b8-df00-11e5-8172-155dc03ddbd2.jpg)

 - tap the state md-select
 - note how the keyboard disappears, the screen shifts down, but the md-select options appear on the top of the page.

![3](https://cloud.githubusercontent.com/assets/16691486/13410933/07af107c-df00-11e5-86c4-e718377f5ac9.jpg)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
