### ISSUE TITLE
md-autocomplete required attribute not working without value

### ISSUE THREAD

**Issue by dmitriylyner** [angular/material#7350]
It seems that md-autocomplete may have a bug and requires a value for required attribute. e.g. md-autocomplete required="true" vs md-autocomplete required

![image](https://cloud.githubusercontent.com/assets/3218659/13418304/5e285ca2-df31-11e5-94b2-379fa8e57e5d.png)

**Comment by DevVersion** [comment]
This is already fixed in `master` 32ba92f44e5ffcb18f0663074d7c9c1913e72836
