### ISSUE TITLE
md-dialog resize with mouse 

### ISSUE THREAD

**Issue by anujsingla** [angular/material#7352]
Hi ,

I want md-dialog to resize with mouse.
I am showing dialog using $mdDialog service. please see below code
$mdDialog.show({
      scope : $scope,
      controller: 'quickInfoController',
      templateUrl: 'template/quickInfoDialog.html',
      parent: angular.element(document.body),
      targetEvent: ev,
      clickOutsideToClose:false,
      preserveScope:true,
      fullscreen: useFullScreen
    });

Now i want to resize the dialog. Please help me i don't know how to handle this situation

**Comment by topherfangio** [comment]
The `<md-dialog>` component does not currently support resizing with the mouse. You might see if anyone on the [forums](https://groups.google.com/forum/#!forum/ngmaterial) has accomplished this or made a similar component.
