### ISSUE TITLE
md-fab-speed-dial not reading 

### ISSUE THREAD

**Issue by vrghost242** [angular/material#7353]
I think I may be missing something, potentially quite obvious, but I have gotten to the point where I don't even know where to look any more. 

So I have the following fab-speed-dial. (mostly stolen from the demo):
````
<div class="actionmenu-container lock-size" ng-controller="defCtrl as demo">

    <md-fab-speed-dial md-open="isOpen" md-direction="up" ng-class="demo.selectedMode">
        <md-fab-trigger>
            <md-button aria-label="menu" class="md-fab md-primary">
                <md-tooltip md-direction="top">Show/Hide menu</md-tooltip>
                <ng-md-icon icon="menu" size="35"></ng-md-icon>
            </md-button>
        </md-fab-trigger>

        <md-fab-actions>
            <md-button ui-sref="home.profile" ui-sref-active="active" class="md-fab md-primary" md-theme="default" aria-label="Welcome">
                <md-tooltip>Welcome to Knowledge</md-tooltip>
                <ng-md-icon icon="info" size="35"></ng-md-icon>
            </md-button>
            <md-button ui-sref="home.cvview" ui-sref-active="active" class="md-fab md-primary" md-theme="default" aria-label="View">
                <md-tooltip>View your CV</md-tooltip>
                <ng-md-icon icon="comment" size="35"></ng-md-icon>
            </md-button>
            <md-button ui-sref="home.cvedit" ui-sref-active="active" class="md-fab md-primary" md-theme="default" aria-label="Edit">
                <md-tooltip>Edit your CV</md-tooltip>
                <ng-md-icon icon="edit" size="35"></ng-md-icon>
            </md-button
        </md-fab-actions>
    </md-fab-speed-dial>
</div>
````

It works, it can open and close, all fine. 
However, I can not get it to load "minimised". Tried to set $scope.isOpen to false. Just does not work. I then tried creating a function that waits three seconds then sets it to false. That does not work, however, if press the button once (to set isOpen to true) it will close it three seconds later. It tells me that before it changes $scope.isOpen, the value is false (and it is boolean) even though the fab is open. 

It is almost like the connection between the fab md-open does not exist until you have pressed the button. But that just does not make any sense. 
The controller I use looks as follows:
````
.controller('defCtrl', function ($scope, $timeout) {
    $scope.openmenu = false;

    this.topDirections = ['left', 'up'];
    this.bottomDirections = ['down', 'right'];
    this.isOpen = false;
    $scope.isOpen = false
    this.availableModes = ['md-fling', 'md-scale'];
    this.selectedMode = 'md-fling';
    this.availableDirections = ['up', 'down', 'left', 'right'];
    this.selectedDirection = 'up';
    $timeout(function(){
        console.log($scope.isOpen);
        console.log(typeof($scope.isOpen));
        $scope.isOpen = true;
        $scope.isOpen = false;
        //this.isOpen = true;
        //this.isOpen = false;
    }, 3000);



});
````
Its Angular 1.5.0 and material 1.0.6

As I thought I was doing something wrong I also opened a call on stackoverflow as well:
http://stackoverflow.com/questions/35702771/false-is-not-false-in-angular

**Comment by DevVersion** [comment]
The speed-dial works perfectly. (http://codepen.io/DevVersion/pen/Wwppzy)

Whenever you use the `[ctrl] as [name]` syntax
```html
<div ng-controller="defCtrl as demo">
```
then the `$scope` valid anymore.

That's why you need to change the `md-is-open` attribute to:
```html
    <md-fab-speed-dial md-open="demo.isOpen">
```

And caution: in the controller, you should also use
```js
this.isOpen = false;
```
