### ISSUE TITLE
Missing v1.0.6 tag

### ISSUE THREAD

**Issue by cah-alexsukhodolsky** [angular/material#7355]
The tag for the latest version (v1.0.6) is missing. 

This also results in a bad "View Source on Github" link on https://material.angularjs.org/latest/.

**Comment by jayeshanandani** [comment]
CHANGELOG.md also doesn't reflects the new version inclusions.

**Comment by DevVersion** [comment]
Changelog is now available in 05aad07506feb9437c9866785b7ec75a870a8a76

**Comment by ThomasBurleson** [comment]
@robertmesserle - is this still an issue in our release script(s)?

**Comment by robertmesserle** [comment]
Not still an issue - this is the build that failed informing us that it was broken. Has to be done manually.  I can’t do it now, I’m on a flight with limited wifi, but it’s just a matter of going into the release branch and tagging it.  I think I manually did everything else.

**Comment by ozsay** [comment]
Can 1.0.6 be uploaded to atmospherejs as well?

**Comment by DevVersion** [comment]
@jelbourn created the missing tag, and the release script seems to work now.
