### ISSUE TITLE
mdFabSpeedDial: nested speed dial style broken

### ISSUE THREAD

**Issue by IcanDivideBy0** [angular/material#7356]
Nested speed dials doesn't always get the correct style applied.

v1.0.6

**Comment by topherfangio** [comment]
I know that you're working on a PR already, but can you please provide a demo of the issue so that we can understand what you are trying to do?

**Comment by IcanDivideBy0** [comment]
@topherfangio here is a plunker https://plnkr.co/edit/i5NQFnHxhBAbaOFl6ISk?p=preview
As you can see, the animations are broken, and that's even worst when you invert the `md-fling` and `md-scale` of the parent and children.

**Comment by topherfangio** [comment]
Although the spec doesn't say it, I'm pretty sure that speed dials are not meant to be nested.

@ThomasBurleson Is this something we want to support?

**Comment by IcanDivideBy0** [comment]
IMO the fix mostly add robustness (don't look for `.md-fab-trigger`, `.md-fab-actions` or `_md-css-variables` too deep in the DOM) and is pretty simple (at least for recent browsers).

Even without the spec saying a word about it, this is a good example of how much angular-material's components are customisable and side effects free.

**Comment by topherfangio** [comment]
I just worry that this will break existing functionality as the following would no longer work since it is searching for direct descendents:

```html
<md-fab-speed-dial>
    <div>
        <md-fab-trigger>
            ...
        </md-fab-trigger>

        <md-fab-actions>
            ...
        </md-fab-actions>
    </div>
</md-fab-speed-dial>
```

**Comment by ThomasBurleson** [comment]
Nested Speed dials will not be supported.

**Comment by IcanDivideBy0** [comment]
Wow, is there any special reason for that ? Does only `md-buttons` are supported in `md-fab-action` ? 
The doc says
> The speed dial supports many advanced usage scenarios.
I do not consider this one specially "advanced"
