### ISSUE TITLE
[ng-md-icon]:  _border icons are not displaying

### ISSUE THREAD

**Issue by aryalprakash** [angular/material#7357]
*_border icons like star_border, favorite_border are not displaying inside ng-md-icon

**Comment by DevVersion** [comment]
Can't reproduce, see [my codepen](http://codepen.io/DevVersion/pen/wGKEYJ?editors=1010). Maybe it's only occurring when using the whole icon stylesheet. So please provide a demo.

**Comment by AlexCid** [comment]
Actually, I might help (and this problem has been driving me crazy for a while) : http://codepen.io/anon/pen/dMGOPy . Why is this happening ?

**Comment by aryalprakash** [comment]
@DevVersion Here's my preview and the code. It works with svg icons but not with class.
![preview](https://cloud.githubusercontent.com/assets/3658290/13592480/802c9928-e51a-11e5-9269-03e811508f9a.PNG)
![code](https://cloud.githubusercontent.com/assets/3658290/13592484/8a7faf82-e51a-11e5-85a9-402227a61373.PNG)

**Comment by Xyara** [comment]
Hello, I was going crazy, but star_border and other icons are not displayed. Look at your sample:
[http://codepen.io/anon/pen/dMGOPy](url)

![image](https://cloud.githubusercontent.com/assets/6213036/24510289/16a3f3cc-1569-11e7-841c-236dd8506984.png)

**Comment by Xyara** [comment]
I upgraded angular-material-icons to version 1.7.1 and it works
