### ISSUE TITLE
mdAutoComplete and mdDialog: when autocomplete is in dialog, scrolling displaces the autocomplete suggestion container

### ISSUE THREAD

**Issue by kathkroll** [angular/material#7359]
Version: 1.0.5 (but have seen in all tried thus far)

Whenever an mdAutocomplete is on a regular page, the scroll mask gets applied like it does with mdSelect, and keeps the page from displacing the suggestion container by removing the ability to scroll the page while it is open. However, whenever you put the autocomplete in an mdDialog, the scrollmask is not applied and scrolling in the dialog will displace the mdAutoComplete's container of suggestions.

CodePen: http://codepen.io/anon/pen/xVbyZO

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
