### ISSUE TITLE
mdMenu has wrong open and closing transition point of origin when near bottom of screen

### ISSUE THREAD

**Issue by drayvock** [angular/material#7363]
According to the [Material Design Spec](http://www.google.com/design/spec/animation/responsive-interaction.html#responsive-interaction-material-response): When a user triggers the creation of new material, it should grow in size starting from the point of input.

This is seemingly correct for most uses of mdMenu. When the directive is placed near the bottom of the screen, however, the transition comes in from the top left instead of from the clicked location.

Here's a pen of the behavior: 
http://codepen.io/anon/pen/XdJOXJ

I may just be missing something here, but it seems to me that the menu should come in from the bottom left in this scenario, not the top left.

**Comment by topherfangio** [comment]
I am pretty sure that this is related to the functionality which moves the menu up so that it always appears on screen if it would otherwise have gone below.

Might be difficult to fix, but it might just require a small bit of CSS to transition it better.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
