### ISSUE TITLE
md-menu: md-button inconsistent theming

### ISSUE THREAD

**Issue by ivoviz** [angular/material#7367]
Since 1.0.6 the menu button behaves differently in `md-toolbar`.

Demo [here](http://codepen.io/anon/pen/reaEem).

Prior the text had the same color as the icon.

Also - this has been there for a while, but I couldn't find any report regarding it - notice there is a different "padding" (it's not exactly padding) depending whether an md-menu-item (md-button) has ng-click or href/ui-sref. *I'll open a separate issue for this if it's needed and not reported yet.*

**Comment by EladBezalel** [comment]
@ivoviz couldn't find the differences can you please direct me?

**Comment by ivoviz** [comment]
It's the text color on the menu opener md-button. In the toolbar it doesn't have the `md-accent` color.

**Comment by EladBezalel** [comment]
related #4928

**Comment by ivoviz** [comment]
It was working in 1.0.5 though.
