### ISSUE TITLE
Angular Material md-input-class

### ISSUE THREAD

**Issue by Dean-Christian-Armada** [angular/material#7370]
I think it would be great if we can add or manipulate the class on the input produced by the md-autocomplete

**Comment by topherfangio** [comment]
Can you please expand upon this a little bit? It looks like your message was cut off.

**Comment by Dean-Christian-Armada** [comment]
I think it would be great if we can add or manipulate the class on the input produced by the md-autocomplete

**Comment by mathiasconradt** [comment]
Not sure if the original poster meant what I also have in mind: the autocomplete widget and the md-input widget look totally different. I don't see any reason why. If those fields are combined in a form, it does not look good.
For example: the autocomplete has a box-shadow, while regular md-input has not.

I use 

```
    .md-whiteframe-1dp, .md-whiteframe-z1 {
        box-shadow: none;
    }
```

to make both fields appear the same. Therefore it would be good if it's possible to style the autocomplete widget in the same way as md-input, or even better, if the style would already match by default.

![snip_20160303160948](https://cloud.githubusercontent.com/assets/295122/13498462/61eeed58-e15a-11e5-9818-63d1c7501b36.png)

**Comment by DevVersion** [comment]
@mathiasconradt @topherfangio - He searches for a way to append custom classes to the generated input.

![image](https://cloud.githubusercontent.com/assets/4987015/13498649/1d1055d6-e15b-11e5-84b9-52ded5d8eba0.png)

For example like so:
```html
<md-autocomplete md-input-classes="my-custom-input red">
```

**Comment by Dean-Christian-Armada** [comment]
@DevVersion , that is exactly what I meant. For example I want to add form-control on the input class

**Comment by crisbeto** [comment]
I've put in a PR for the ability to specify a custom class on the input. As for the note from @mathiasconradt, I'd say the current [autocomplete style matches the spec](https://www.google.com/design/spec/components/text-fields.html#text-fields-auto-complete-text-field).

**Comment by crisbeto** [comment]
It's been a while since I submitted the PR for this. It didn't end up getting merged, because it was hard to maintain (every change to the autocomplete caused a merge conflict). I'll close the issue, but if you think that this is still something necessary, post a comment and I'll reopen it.

**Comment by lassmann** [comment]
@crisbeto I have the same issue, I want to give a class to the input="search" of the autocomplete and I can't. Could we open again this issue?

**Comment by vaso2** [comment]
Hi @crisbeto, I too have this issue, I need to add custom classes to input, "form-control" to be sure

**Comment by IAMtheIAM** [comment]
Of course this is necessary, how can you expect ui developer to give up control of styling input elements? adding custom class is absolute necessity
