### ISSUE TITLE
Trying to use Autocomplete in a custom control

### ISSUE THREAD

**Issue by alexkolt** [angular/material#7371]
I am trying to create a custom control to pick a user from a list. It is simply a wrapper around autocomplete control. The control monitors a field (User ID) and allows the user to pick a different user. The field is ID and control should display Name. I know this may not be specifically Material issue, but I am trying to use material controls in ng material way and failing somewhere:

1. Control loads list of users asyncronously. User ID is provided from the parent page, but is also loaded asynchronously. User ID is not populated in the constructor of the control. I work around that by capturing ngModel in postLink and invoking controller. Somewhat ugly. Is there a better way?

2. I got the control working for a field. I have several I want to control: User1, User2. I added couple controls, but they all get synced up. When I change user in one control it changes them in all controls. I can't replicate issue in sample project. What could it be?

Here's the codepen with the issue: http://codepen.io/akoltsov/pen/BKNKJq

To make it work go to js and change first variable(async) to false; 

Project is written in ES6 and I translated to ES5 best I could.

P.S. Apparently the state is shared when using a controller. Just switched to link and the behavior is better.

**Comment by alexkolt** [comment]
Finally figured out what the problem was - ES6 transpilation. The controllers are declared in the following way:

var self;
class Controller {
  constructor() {
    self = this;
  }
}

the problem with this was that the variable self is overriden if another control is created, thus any instance variables are lost and only last one remains. I'm freaked out as to how I didn't see this sooner. Obviously not angular material issue. You can close the issue.

**Comment by topherfangio** [comment]
@alexkolt Thanks for the update. Also for future note, if you solve the issue before we get around to it, you are able to close it yourself :smile:
