### ISSUE TITLE
ng-click it's not working on OSX Safari 9 when entering "Responsive Design Mode" for any iPhone or iPad devices from the list

### ISSUE THREAD

**Issue by nickchisiu** [angular/material#7372]

**Comment by DevVersion** [comment]
Please provide more information.

- Which Angular Material Version
- Show your `list` snippet

And a demo is also really helpful.

**Comment by nickchisiu** [comment]
When using Angular Material >= 1.0.0 on a Safari browser with the "Enter Responsive Design Mode" from "Develop" section on top Safari menu "ng-click" it's not working, I was able to fix it with   $mdGestureProvider.skipClickHijack() , but I'm not sure that's the best solution

**Comment by DevVersion** [comment]
@nickchisiu Yes can reproduce that in the `Responsive Design Mode`. But I'm not sure in which case this is related to the Mobile Use and Desktop Use. 

cc @EladBezalel

**Comment by nickchisiu** [comment]
the issue it's on Safari - IOS 9.1 - IPhone

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
