### ISSUE TITLE
input: improve click area for users accustomed to older style inputs.

### ISSUE THREAD

**Issue by wcjr** [angular/material#7373]
Would the team consider a couple of changes to the md-input-container that might help users recognize Material inputs a little easier?

I believe a couple of small changes would help immensely:
1. Make the md-input-container area clickable, it should trigger the input's focus event
2. Apply a text cursor upon hover into the md-input-container

These small changes would help users who haven't quite made the complete transition into Material design when it comes to form inputs.

Thanks for the consideration!

I don't feel this is a very elegant solution but it's what I'm doing in the meantime to help our users that have been struggling how enter form data.  I'm hoping someone can help me with a better solution with this [SO question](http://stackoverflow.com/questions/35731406/how-would-one-go-about-extending-the-click-area-of-material-input-to-its-contain).

```
    .directive('mdInputContainer', mdInputContainer);

    function mdInputContainer() {
    return {
        restrict: 'E',
        require: 'mdInputContainer',
        link: link
    };

    //////////////////////////////////////////////////////////////////

    function link(scope, element, attrs, mdInputContainerCtrl) {
        element.on('click', function () {
            mdInputContainerCtrl.delegateClick();
        });
    }
}


```

```
md-input-container {
    cursor: text;
}
```

**Comment by cleever** [comment]
I agree.

BTW, I think we need a second input style avaliable, without css racks. Like ionic framework have.
At first sight, material inputs are beautiful. But in big forms they are confusing for daily and old users.

**Comment by wcjr** [comment]
Thanks for the support @cleever glad to hear it isn't just our users having these issues.

**Comment by topherfangio** [comment]
I'm a bit confused as the inputs currently do both of these things (focus when clicked and provide a text cursor on hover).

What version of Material are you using and what browser?

**Comment by topherfangio** [comment]
@wcjr Any chance you can provide some additional info?

**Comment by wcjr** [comment]
@topherfangio our users were clicking slightly outside the actual input and therefore the focus wasn't occurring.  Try it for yourself, click within the input-container but outside the actual input.  It's that small area that will help our users immensely.

**Comment by topherfangio** [comment]
To clarify, what you're wanting is the top orange area (where the label floats to) to be clickable? If so, I think that makes sense. It is a bit awkward right now that you can click on the input, then click on the floating label and it de-selects the input...

<img width="593" alt="inputs_clickable_area" src="https://cloud.githubusercontent.com/assets/54370/14687491/7f034b5e-0703-11e6-86fd-74eecebedffb.png">

**Comment by wcjr** [comment]
yes, that's correct.  You'll notice in my code I also change the cursor in that area.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
