### ISSUE TITLE
md-menu-item has inconsistent hover behavior, href vs ng-click

### ISSUE THREAD

**Issue by rguico** [angular/material#7378]
Codepen: http://codepen.io/rguico/pen/wGagVW

Note that "Logout" and "Banana" remain highlighted on blur from the menu item; the other elements are not affected. Logout and Banana have the **ng-click** attribute while the others have an **href** attribute.

Even more bizarre, this behavior does not occur when you Inspect the element!

Affects: 
- Chrome: Version 48.0.2564.116 (64-bit)
- Firefox: 44.0.2
- Safari: 9.0.3

**Comment by fkpwolf** [comment]
I also found this issue when I used "ng-click" & "ui-sref" in same md-menu.

**Comment by DevVersion** [comment]
Issue is fixed in `master`. See [demo](http://codepen.io/DevVersion/pen/oxbNop)

**Comment by totallyrandomtext** [comment]
Still [reproducible](https://codepen.io/anon/pen/NVMdJR) with angular-material 1.1.8 and angular 1.6.10

Chrome: Version 74.0.3729.169 (Official Build) (64-bit)
Firefox: 68.0b4 (64-bit)

**Comment by Splaktar** [comment]
@kasthack can you please open a new issue and link to this issue from there?
