### ISSUE TITLE
md-icon: render issue when using md-svg-icon with svg sprite (Firefox, IE Edge)

### ISSUE THREAD

**Issue by mpiasta-ca** [angular/material#7381]
Strange issue where an svg icon with `<circle>` renders as a square (Firefox), or renders transparent (IE Edge), when (1) a specific icon is used TWICE (or more than once) with `<md-icon md-svg-icon="..."></md-icon>`, and (2) the first iteration of that icon is hidden using some form of ng-show (ie. in our app, the first iteration of the icon appears in the md-sidenav that switches between open/hidden; the second iteration appears in a "Select your current location" modal dialog).

**Plnkr demo (open in Firefox or IE):**
https://plnkr.co/edit/UIzqOTmyHa6we3vnE0um?p=preview

**Expected:**
![region-chrome](https://cloud.githubusercontent.com/assets/672103/13474496/1717a5fa-e073-11e5-8ad1-60d4ff9a4b32.png)

**Firefox:**
![region-firefox](https://cloud.githubusercontent.com/assets/672103/13474544/53250db2-e073-11e5-94d8-d9711a18b88f.png)

**IE Edge:**
![region-ie](https://cloud.githubusercontent.com/assets/672103/13474583/8157a654-e073-11e5-8cc0-353c646a39c0.png)

I also setup a demo using icons from the angular-material icon set, which don't seem to have the same problem (works in Firefox and IE Edge):
https://plnkr.co/edit/mMnO8nI2fjpxM0F0r5ax?p=preview

**Comment by DevVersion** [comment]
@mpiasta-ca - When using a simple circle SVG, everything works fine. 
This seems to relate to your SVG's / generated Sprite (https://github.com/jkphl/gulp-svg-sprite/issues/47)

**Comment by mpiasta-ca** [comment]
@DevVersion, issue might be specifically when using the circle as a clip-path (in the firefox demo case, the clip-path fails and everything beyond its edge is rendered). 

I tried to clean-up the svg code directly (as xml instead of in illustrator) to see if that would help, but I couldn't get it to a point where it would work.

**Comment by mpiasta-ca** [comment]
@DevVersion [I asked the question on stackoverflow](http://stackoverflow.com/questions/35853218/svg-clip-path-circle-fails-when-using-svg-sprite-and-multiple-instances?noredirect=1#comment59373905_35853218), and a user pointed-out that if you look inside the `<md-icon>` element when it renders, there is a child `<svg id="...">` element.

So if you have two instances of `<md-icon>` on the page that display the same svg image, you will have two elements trying to use the same id, which will create a conflict in the browser.

I'm not sure how `<md-icon>` code works with sprite, does it read the text from the sprite file and output the specific element that is requested? If so, a fix could be to change `<md-icon>` so when it renders the content for the svg, it should strip the id from the parent `<svg>` tag (or make it unique by adding a prefix). 

Or, do I need to change my svg-sprite file to make it work somehow (I've been looking at the svg-sprite created by angular-material team, and I see they use `<g>` parent tags instead of `<svg>`, but not sure if that will work.

**Comment by mpiasta-ca** [comment]
@DevVersion, the problem is even worse than that, because the `<clipPath>` uses an id too. So now if the `<md-icon>` renders the same svg twice, there will be two instance of `<clipPath id="...">`, and two elements which reference that id.

Not sure what the solution is to this, without prefixing every id attribute in each child element each time the svg is rendered using `<md-icon>`.

**Comment by DevVersion** [comment]
The duplicate ids, have been fixed in 810c4f3309b76b3337a155b177398ac2dd8ad0b0

**Comment by mpiasta-ca** [comment]
So I see in iconService.js@433 the code is removing id from all child elements of the svg. I think this might break svg `<clipPath id="...">`, since now the other elements in the svg will not be able to reference the clipPath. And there doesn't seem to be any other way to use clipPath without an id (without altogether rebuilding the svg without a clipPath).

**Comment by DevVersion** [comment]
Oh, that seems to be a new issue, introduced by 810c4f3 - if so, please create another issue for that.

**Comment by mpiasta-ca** [comment]
Yeah, just tested with the change from 810c4f3, and it breaks all `<clipPaths>`. In my case, the svg that should appear as circle appear as squares all the time now (instead of in the case of multiple icons), since the clipPath is failing.

OK, will create a new issue for it.
