### ISSUE TITLE
Firefox & flex layout

### ISSUE THREAD

**Issue by char0n** [angular/material#7382]
Hi,

Is there any particular reason why commit(https://github.com/angular/material/commit/99c9b60e4521b388ee979d796cec247cffe44499) was made ? The min-height, min-width does no longer have influence on chrome 48 but firefox is still affected without these css properties.

Can you please collaborate ?

After upgrading to angular-material 1.0.6 our application which is in holly grail layout broke down. This is the code we had to introduce to be able to run the application on Firefox and to support version 1.0.6

https://gist.github.com/anonymous/a767374e07209ae8fffa

Reproducable on FireFox 44.0.2

**Comment by ThomasBurleson** [comment]
@char0n - Thank you for this issue. It will be addressed today!

**Comment by dholbert** [comment]
@char0n is there a live page / testcase anywhere that reproduces this issue in Firefox? (using the affected Angular version)

I work on Firefox's layout code, and I'd like to take a closer look at the rendering difference between Firefox & Chrome and see if there's something we need to fix (or if it's a known bug in Firefox, or a known bug in Chrome).

Thanks!

**Comment by char0n** [comment]
@dholbert use this repo: https://github.com/char0n/angular1-slack

In bower.json change 1.0.5 to 1.0.6 and the layout will break on Firefox.

**Comment by dholbert** [comment]
@char0n thanks -- just got that set up, I think. (I am not particularly familiar with npm/grunt/bower, so I'm not 100% confident I did everything right, but it seems to be working.)

I'm not sure where to look for the layout issue, though -- can you be more specific? (click this button, look at this particular piece of the layout, etc)

**Comment by dholbert** [comment]
(the only prominent broken-seeming thing that I'm hitting is with the hamburger-menu button ending up quite large sometimes.  But none of its ancestors seem to have `display:flex`, so I don't think that can be the issue you're describing here.)

**Comment by dholbert** [comment]
(This is what the page looks like for me; it's mostly unstyled, so it's possible something didn't work during the configuration.)

![screenshot](https://cloud.githubusercontent.com/assets/426803/13519114/40e2db36-e189-11e5-8977-5c451104d22c.png)

**Comment by dholbert** [comment]
For completeness, here's the output when I run 'grunt':
https://gist.github.com/dholbert/5b9dbacc6a0726fd7330
...and when I run 'grunt serve':
https://gist.github.com/dholbert/6d6ea1fa0734679a95bd

I'm probably missing a step somewhere -- there are various errors/warnings, many of which I've churned through by installing packages, but errors/warnings remain.  The one about 'compass' might be the particular one that's giving me unstyled content; not sure. I tried to address it with `npm install compass` and `npm install grunt-contrib-compass` but that didn't help.

Since you're able to reproduce it, if you could stand up a public instance of the server somewhere where I could just view it directly, that would be awesome! (Or, if you could do "File|Save" when the bug is reproducing & zip up the saved resources (assuming the saved version demonstrates the bug) and send me the zip file, that would also be great.

**Comment by dholbert** [comment]
(Also: I'm technically on vacation at the moment, so depending on my vacation plans, I may not get back to you right away. Thanks in advance for any help coming up with a testcase here!)

**Comment by char0n** [comment]
@dholbert I am sorry for lack of info regarding the repo.

Installing process:
$ npm install
$ bower install
Install compass: http://compass-style.org/install/  (after installation it should be in your PATH)

Then you will run
$ grunt serve

Goto: http://localhost:9000/#/conversation

Everything looks good in every browser. On left are channels and on the right there is content area for messages. If messages are higher than content area content area will scroll the messages.

Modify bower.json and change "angular-material": "=1.0.5" to "angular-material": "=1.0.6". Run 
$ bower install
$ grunt serve

After opening the page in browser you will see that if messages height is higher that the viewport entire page is scrolling now, not only the content area designated for them.

Hope it is more clearer now. If you have further questions don't hesitate to ask.

**Comment by dholbert** [comment]
Thanks. With that, I was able to reproduce the issue.

The difference between Firefox & Chrome there is due to https://bugs.chromium.org/p/chromium/issues/detail?id=487302 -- i.e. it's a bug with Chrome producing the wrong min-content height, for a flex item that happens to have a scrollable child.

**Comment by char0n** [comment]
Cool, so I guess in 1.0,7. will you introduce the min-height fix which was reverted in 1.0.6 ?
