### ISSUE TITLE
bottomsheet: closing through escape key isn't working when clicking on backdrop.

### ISSUE THREAD

**Issue by auty** [angular/material#7387]
Repro:

- Navigate to https://material.angularjs.org/1.0.6/demo/bottomSheet
- Click "Show as Grid"
- Click outside
- Click esc
- Click down arrow

Actual:

- Nothing happens
- Need to reload page to remove bottom sheet

Expected:

- The Bottom Sheet should close

This occurs using Chrome on Mac.

**Comment by DevVersion** [comment]
The `Show as Grid` demo is configured to disable the outside click. So if you click outside and then hit <kbd>ESC</kbd> nothing won't happen, because the bottomsheet isn't focused anymore. 

So to summarize - the actual bug, is the focus for the <kbd>ESC</kbd> keydown.
