### ISSUE TITLE
mdProgressCircular hide issue

### ISSUE THREAD

**Issue by gaurav5430** [angular/material#7388]
when setting `md-mode=""` or `md-mode=null`, only the `md-scale-wrapper` is hidden and not` md-progress-circular`. It still stays in place.

This causes problems if there is another element behind it, which does not receive pointer-events.

Suggestion: either set `display:none` to `md-progress-circular` or set `pointer-events:none` when hiding.

Angular-material-version: v1.0.0

**Comment by DevVersion** [comment]
Issue is fixed in `master` by 640b55db400cb5c45381edce8b75058a75399c14
