### ISSUE TITLE
Highlighting form errors on submit does not work with ng-form

### ISSUE THREAD

**Issue by Slettan** [angular/material#7389]
http://codepen.io/Boxiom/pen/BKNVgM

As you can see, when using `form` it highlights any input errors when you submit the form. However, it does not work with `ng-form`. It only shows the error if the input is dirty.

Should `ng-form` not have the same behavior in this case as a HTML form?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
