### ISSUE TITLE
mdChips with mdAutocomplete: readonly lets floating label disappear on autocomplete

### ISSUE THREAD

**Issue by migingreen** [angular/material#7390]
See md-chips autocomplete example with additional readonly checkbox and autocomplete with md-floating-label instead of placeholder:
[http://codepen.io/anon/pen/NNqzQV](http://codepen.io/anon/pen/NNqzQV)

There are several issues present:

- The md-chips disappears completely if there's no value present and set to readonly (related to #7136 )
- Floating label (same for placeholder) disappears if value is present and set to readonly
- md-autcomplete input-container (with floating label) doesn't align with md-chips

Floating labels should always be visible in my opinion, most of the time there are more than just one input field present in a form which leads to confusion if some inputs have no label.

Possibly related to #3200 

 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v1.0.5

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
