### ISSUE TITLE
Specify `"private": true` in package.json

### ISSUE THREAD

**Issue by mgol** [angular/material#7393]
Refs 19156c865d3f271df0d968a867c0b071e474c64b

Preventing accidental `npm publish` is better done via adding the `"private": true` entry to package.json than by renaming the package in this file.

See https://docs.npmjs.com/files/package.json#private

**Comment by DevVersion** [comment]
Yes, I agree, that seems to be a better way.

**Comment by robertmesserle** [comment]
I'm not opposed to this approach, but it's not entirely accurate.  What we have isn't a private repository, it just isn't the repository that we publish to NPM.  Giving it the same package name that we use on NPM seems misleading.

That being said, I really don't have a strong preference one way or the other.

**Comment by mgol** [comment]
`"private": true` doesn't mean the repository/project itself is private but that its code shouldn't be accidentally published via `npm publish`. Since you treat those packages as source-only, even if you keep different names for them than for the published ones, adding `"private": true` still seems like a good idea.

**Comment by topherfangio** [comment]
@ThomasBurleson Can you weigh in here and prioritize?
