### ISSUE TITLE
mdInputContainer: Has padding-left when icon is in nested button when migrate from 1.0.5 to 1.0.6

### ISSUE THREAD

**Issue by styxiak** [angular/material#7394]
md-input container get class .has-icon and padding-left when icon is in nested button:

```
<md-input-container style="padding-bottom: 0">
    <md-button align="center" class="md-primary md-raised">
      <md-icon md-font-icon="fa-google-plus-square"></md-icon>test
    </md-button>
</md-input-container>
```
In version 1.0.5 it was ok.
 [demo](http://codepen.io/styxiak/pen/JXdzRO)

**Comment by topherfangio** [comment]
@crisbeto This is almost certainly related to my earlier commit here : e6176fb5d2daef749c29fccd44d9ed02a4dbb316

**Comment by topherfangio** [comment]
Actually; sorry; I just realized that my change came after 1.0.6. This should be fixed in master, here is an updated Codepen: http://codepen.io/topherfangio/pen/yOgjmB?editors=1000

Please let us know if you still experience the issue after upgrading and we will reopen.
