### ISSUE TITLE
Setting range on md-progress-linear

### ISSUE THREAD

**Issue by pjwalmsley** [angular/material#7396]
The example has a darker bar over a lighter bar to convey progress.  I don't see min/max options, only a value attribute.  Any advice on getting this to work?  Thanks!

**Comment by DevVersion** [comment]
Hey, sorry didn't got your actual problem. What `example` do you mean?

**Comment by pjwalmsley** [comment]
NVM, I just figured it out.   I misread the code.  I was accidentally using the number before being converted to a faction of 100.

It was the first example on this page:
https://material.angularjs.org/latest/demo/progressLinear

**Comment by DevVersion** [comment]
@pjwalmsley No problem, thanks for using Angular Material :) If you have any further issues, just let us know.
