### ISSUE TITLE
md-select label overlaying placeholder after forced focus (bug)

### ISSUE THREAD

**Issue by rvarbanov** [angular/material#7398]
I have a form that has a reset button:
```js
$scope.onResetClicked = () => {
	$scope.initForm();
	$scope.form.$setPristine();
	$scope.form.$setUntouched();
	document.getElementById('customer-name').focus();
};
```

When I click the button the form is reset and the customer input is focust with an ugly side effect: 
[CodePen Demo](http://codepen.io/radi/pen/BKNegv)

<img width="325" alt="screen shot 2016-03-03 at 1 45 20 pm" src="https://cloud.githubusercontent.com/assets/2780282/13505383/e8b56a92-e146-11e5-9369-2452734b59b5.png">

To fix that I added this CSS:
```css
.md-input-focused:not(.md-input-has-value) label.md-placeholder {
	opacity: 0;
}
```

I would like to submit a pull request, but I am not sure what is the best place to insert that code.

What is the best place to add that code?

**Comment by rvarbanov** [comment]
I started a new PR #7488

**Comment by topherfangio** [comment]
This was fixed recently and is available in master: http://codepen.io/topherfangio/pen/KzaRJY
