### ISSUE TITLE
Bi-di issues with demos

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#7399]
After the commits for improved Bi-Directional support, the following demos still need work:

![screen shot 2016-03-02 at 8 52 12 am](https://cloud.githubusercontent.com/assets/210413/13506964/20c3b67e-e146-11e5-92e6-956634cff95e.png)

![screen shot 2016-03-02 at 8 52 30 am](https://cloud.githubusercontent.com/assets/210413/13506974/2e3a4b06-e146-11e5-8195-5849ff09249e.png)

**Comment by EladBezalel** [comment]
@ThomasBurleson @DevVersion as my native language is RTL and i'm really close to this issue do you mind if i'd do it?

**Comment by DevVersion** [comment]
@EladBezalel Sure, enjoy :)

**Comment by ThomasBurleson** [comment]
@EladBezalel - Thanks for volunteering. I was hesitant to overload you. :fearful: :+1:

**Comment by EladBezalel** [comment]
![image](http://marker.screenshots.prod.s3.amazonaws.com/9dbcaec82d6940969a9758467560852b-1457075744321.png)

**Comment by EladBezalel** [comment]
all those are related to [`rtl-prop`](https://github.com/angular/material/blob/master/src/core/style/mixins.scss#L114) mixin which doesn't 'disables' the `ltr` property when in `rtl` mode
