### ISSUE TITLE
Add Chips component

### ISSUE THREAD

**Issue by ajoslin** [angular/material#74]
Specification: [Chips](http://www.google.com/design/spec/components/chips-tokens.html#)

![image](https://cloud.githubusercontent.com/assets/210413/4068804/8aa8e938-2e3c-11e4-8354-a31e592cd2a2.png)

```html
<material-chips>
  <material-chip ng-repeat="contact in contacts" active="contact.selected">
    <img ng-src="{{contact.img}}">
    <h2>{{contact.name}}</h2>
    <p>{{contact.email}}</p>
  </material-chip>
</material-chips>
```

Considerations:
*  All chips inside are available in the menu.
*  All chips that evaluate to `active` true will be rendered.

**Comment by Hendrixer** [comment]
what about the action for the `x`? 
There would be two solutions I can think of:

1. Allow devs to use whatever icon they want for the action on the right if so then this could work

``` html
 <material-chips>
  <material-chip ng-repeat="contact in contacts" active="contact.selected">
    <img ng-src="{{contact.img}}">
    <h2>{{contact.name}}</h2>
    <p>{{contact.email}}</p>
    <md-icon class="md-chip-action" md-svg-icon="icon"  ng-click="action($index)"><md-icon>
  </material-chip>
</material-chips>
```

2. place an action directive on the `material-chip` directive
``` html
 <material-chips>
  <material-chip ng-repeat="contact in contacts" active="contact.selected"
   material-chip-action="action($index)">
    <img ng-src="{{contact.img}}">
    <h2>{{contact.name}}</h2>
    <p>{{contact.email}}</p>
  </material-chip>
</material-chips>
```

What do you think @ajoslin ?

**Comment by jeroenvheel** [comment]
when you delete a item thats not the item that got deleted.

example: [Basic usage](https://material.angularjs.org/#/demo/material.components.chips)
when you click delete[X] on (fruit:orange).
(fruit: apple) got deleted

**Comment by lyschoening** [comment]
Along the same lines (not making a new issue since this one is still open): If you re-enter an existing chip, all further chips entered after it will not show up until that chip is deleted.

1. add 'foo' (this works)
2. add 'foo' again (nothing happens)
3. add a few other chips (nothing happens)
4. delete 'foo': The second 'foo' as well as all other new chips appear.

**Comment by jeroenvheel** [comment]
nice works like a charm !
