### ISSUE TITLE
md-progress-circular for indeterminate not working

### ISSUE THREAD

**Issue by goodseller** [angular/material#740]
Please see the code:
http://plnkr.co/edit/Ez5Ux7OJ08rP39zLYrpJ?p=preview

The line below

---

Indeterminate

For operations where the user is asked to wait a moment while something finishes up, and it’s not necessary to expose what's happening behind the scenes and how long it will take, use an indeterminate indicator.

---

Should show the proccess circular according to the tutorial.

https://material.angularjs.org/#/api/material.components.progressCircular/directive/mdProgressCircular

Does anyone know why?
Thanks.

**Comment by pushkaraditya** [comment]
ftest
