### ISSUE TITLE
docs(dialog): unclear about how to use resolve property

### ISSUE THREAD

**Issue by mmiszy** [angular/material#7400]
According to the [documentation](https://material.angularjs.org/latest/api/service/$mdDialog) of `$mdDialog.show`, `resolve` property is an object which "_takes promises as values, and the dialog will not open until all of the promises resolve_". Unfortunately this doesn't work. If a Promise is given, the dialog will never appear and will fail silently instead.

Here's a very simple test case which shows the problem. The first button works, the second one doesn't: http://codepen.io/mmiszy/pen/PNqMvm?editors=1010

**Comment by DevVersion** [comment]
It seems like the `resolve` method isn't available yet. 
[See the interimElement snippet](https://github.com/angular/material/blob/master/src/core/services/interimElement/interimElement.js#L56)

**Comment by bellaire** [comment]
I think the release documentation (e.g. for 1.0.8) should be amended to indicate this property doesn't work in that version.  Or maybe just take it out completely.

https://material.angularjs.org/latest/api/service/$mdDialog

**Comment by gagalago** [comment]
what is the current status ?

**Comment by deonclem** [comment]
Could you guys please at least update the documentation ? It's the second time I'm losing time trying to make this work following the documentation, forgetting that the feature simply does not exist...

Cheers !

**Comment by tyrdavis** [comment]
I'm pretty certain the resolve functionality does work, but the documentation isn't very clear. It works if the values on the resolve object are functions that return promises, but not if the values are directly promises as in the original codepen demo.

Here's a codepen I've set up showing this. I've also bound the resolved promise to the template to show that it's getting through. Take a look:

http://codepen.io/anon/pen/NpOpQx?editors=1010

**Comment by swizzmagik** [comment]
Well done @tyrdavis your solution is a valid workaround for me!

**Comment by murwa** [comment]
@tyrdavis 👍 💯

**Comment by tyrdavis** [comment]
A bit disappointing that the PR to totally remove this from the documentation was merged, when the feature is in fact there.

**Comment by Splaktar** [comment]
I'm going to close this one so that future work can be done in relation to https://github.com/angular/material/issues/11159. 

We would welcome a PR that added this documentation back in and provided an example of how to properly provide the value as explained in [the comment above](https://github.com/angular/material/issues/7400#issuecomment-289870601).
