### ISSUE TITLE
input: label overflows and shows horizontal scrollbar

### ISSUE THREAD

**Issue by rhllor** [angular/material#7403]
Hi,
I use mdDialog for create a fast form. From version 1.0.2 i have a problem with Internet Explore 11.

When an input text get focus an horizontal scrollbar appears. 

![cattura](https://cloud.githubusercontent.com/assets/1021565/13511865/73e739ce-e197-11e5-989e-55f629ef0c4a.PNG)

This is the template code:

```html
<md-dialog aria-label="Log"  ng-cloak>
<md-dialog-content layout="column" class="md-dialog-content">
<md-input-container class="md-block">
          <label>Biography</label>
          <textarea ng-model="vm.Note" ></textarea>
        </md-input-container>
</md-dialog-content>
</md-dialog>
```

**Comment by rhllor** [comment]
Hi, 
we found this problem with IE

`  md-input-container.md-input-focused label:not(.md-no-float), md-input-container.md-input-has-placeholder label:not(.md-no-float), md-input-container.md-input-has-value label:not(.md-no-float) {
    -webkit-transform: translate3d(0, 6px, 0) scale(0.75);
            transform: translate3d(0, 6px, 0) scale(0.75);
    transition: -webkit-transform cubic-bezier(0.25, 0.8, 0.25, 1) 0.4s, width cubic-bezier(0.25, 0.8, 0.25, 1) 0.4s;
    transition: transform cubic-bezier(0.25, 0.8, 0.25, 1) 0.4s, width cubic-bezier(0.25, 0.8, 0.25, 1) 0.4s;
    width: calc((100% - 18px) / 0.75); }`

The Attribute width generate this problem. If we remove this attribute we don't have more bug and all work fine.

**Comment by topherfangio** [comment]
@crisbeto The `calc()` does it's calculations based on the viewport width. Do you think you can find another way to achieve whatever this is doing?

**Comment by peio72** [comment]
Problem remaining on IE11 with 1.1.0-rc3. Visible on demo input.

**Comment by crisbeto** [comment]
@peio72 I couldn't reproduce this particular issue on IE11 with rc3. The overflow that you see in the demo is because of the `datepicker`.

**Comment by peio72** [comment]
I still see the scrollbars on the demo input on my IE11 for the basic usage and the icons.

On my App the problem is only present on the inputs with icons.

**Comment by crisbeto** [comment]
The scrollbar on the demo is because of the datepicker, not the input. As for having the icons together with an input, can you post a code example or a codepen?

**Comment by peio72** [comment]
Email me so i show you the app directly.

**Comment by crisbeto** [comment]
I don't know your email address.

**Comment by peio72** [comment]
I update my profile, you should be able to contact me so I can show you the live example. Thanx.

**Comment by crisbeto** [comment]
I'll reopen this one because it's still an issue. I managed to reproduce it using @peio72's example.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
