### ISSUE TITLE
$mdSidenav returns wrong value of isOpen() when isLockedOpen() is in effect

### ISSUE THREAD

**Issue by iamjt** [angular/material#741]
v0.6.0-rc1-master-fca5376

<md-sidenav md-component-id="sidenav" class="md-sidenav-left md-whiteframe-z2" md-is-locked-open="$media('md')">

$mdSidenav returns false (instead of true) when the sidebar is locked open.

Works fine without isLockedOpen.

**Comment by rschmukler** [comment]
Keeping the behavior as is (it'd confusing if `is-locked-open` ended up changing the state of `is-open`) but documenting it and also exposing a new method on `$mdSidenav`. You can now call `$mdSidenavInstance.isLockedOpen()` to see whether it is locked open, and `$mdSidenavInstance.isOpen()` for whether it's set to open.

This means that you can check if side-nav is displayed with the following:

```js
var sidenav = $mdSidenav('mySidenav');
$scope.sidenavDisplayed = sidenav.isLockedOpen() || sidenav.isOpen();
```

**Comment by ThomasBurleson** [comment]
@rschmukler - would not `sidenav.isOpen() == true` if locked? So the extra check is unneeded ?

**Comment by rschmukler** [comment]
`sidenav.isOpen() == true` refers to whether it's set to open. Whether that is true or not, if `isLockedOpen()` is true, it will be locked open.

**Comment by ThomasBurleson** [comment]
@rschmukler - exactly my point. So this is not more succinct:

```js
var sidenav = $mdSidenav('mySidenav');
$scope.sidenavDisplayed = sidenav.isOpen();
```

**Comment by rschmukler** [comment]
The problem with that is that `sidenav.isOpen()` binds to a boolean on the directive. It'd be very confusing as the browser window resize could set that to `false`, and it would become the developers responsibility to watch for media queries that could change the state of their sidenav.
