### ISSUE TITLE
Bottomsheet in 1.0.6 generates scrollbar (both chrome and IE)

### ISSUE THREAD

**Issue by jalajc** [angular/material#7410]
I observe that bottomsheet in 1.0.6 generates the scrollbar in Chrome and IE (in IE both horizontal as well vertical scroll bar appears).
When I replace back angular material **css** to 1.0.5, the scrollbar disappears.

refer pen: http://codepen.io/anon/pen/pyjwNJ (codepen from https://material.angularjs.org/latest/demo/bottomSheet)

Just try changing the css from codepen settings to observe this behavior

**Comment by DevVersion** [comment]
The current issue is now noticeable, because we removed the `overflow` property from the body for codepens. So yes, can reproduce.

**Comment by mortware** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by sjlynch** [comment]
So if we're not moving to Angular2, we're SOL! Great.

Time to go to React.

**Comment by sjlynch** [comment]
For anyone running into this issue  -- 

Found a good fix for this by setting the parent of md-bottom-sheet to a div which is relatively positioned and overflow:hidden. See http://stackoverflow.com/questions/19308257/positionabsolute-causes-horizontal-scrollbar

To set the parent, see the bottom of this page -- https://github.com/angular/material/issues/640

**Comment by EstiMarc** [comment]
#1211  

md-bottom-sheet {
padding: 0px;
bottom: 80px;
overflow: hidden;
}

Should save the day, only tested on safari iPhone, chrome iPhone and chrome desktop but it should also work for the rest.

The value 80px need adjustment
