### ISSUE TITLE
Allow to clear md-autocomplete cache

### ISSUE THREAD

**Issue by bluebirdtech** [angular/material#7411]
I would like to use the caching provided by `md-autocomplete` but need to clear/invalidate the cache upon certain events.

I propose to let the application remain in charge of when the cache should be cleared, so it could be done on timeout or (as in our case) when something specific occurs.

Example usage:
```<md-autocomplete md-cache-invalid="cacheInvalid">```

Where `cacheInvalid` is a scope variable that the application sets to true as needed.  `md-autocomplete` would see it was now true, clear the cache and set it to false.

If anyone has a workaround, please post it.  I'm able to get the `$mdAutocompleteCtrl` object but none of the public functions are of help here.

**Comment by DevVersion** [comment]
I don't think a feature like you described isn't desired, because it needs a two-way binding and is in my opinion the wrong implementation for the cache clear. I would rather suggest a timeout (as you said) or maybe just a public controller function (I prefere this one)

**Comment by bluebirdtech** [comment]
A public controller would be fine too, and perhaps more versatile.  Timeout wouldn't work for our case as the cache is invalidated by a specific event.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
