### ISSUE TITLE
Noto font fallback

### ISSUE THREAD

**Issue by code-tree** [angular/material#7416]
Since Noto is the official Material Design font when Roboto doesn't cover a character set, should the font family variable be changed from:

`$font-family: Roboto, 'Helvetica Neue', sans-serif !default;`

to:

`$font-family: Roboto, 'Noto Sans', sans-serif !default;`

Though, I'm still a bit confused as to whether that will make e.g. 'Noto Sans CJK` (if installed on the user's computer) be used by the browser if only 'Noto Sans' is specified. So this is half a suggestion, half a question.

cheers

**Comment by DevVersion** [comment]
Yes, indeed. 

![](https://i.gyazo.com/6a8cd2b2ab683c8104f91ac6a2ecf338.png)

https://www.google.com/design/spec/style/typography.html#typography-typeface

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
