### ISSUE TITLE
 Angular Material Autocomplete custom template - group items

### ISSUE THREAD

**Issue by dhiman252** [angular/material#7417]
Is there any functionality in the autocomplete custom template we can show the results like in the image attached
![screenshot_2](https://cloud.githubusercontent.com/assets/8954468/13546378/223bbffa-e2d2-11e5-8165-f0108f1356fc.png)

**Comment by topherfangio** [comment]
I assume you're asking about the grouping/multiple datasets functionality. No, the autocomplete does not currently support this. I'll mark this as a feature request.

**Comment by samithaf** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
