### ISSUE TITLE
Tab - style compatability - change in CSS - FIX

### ISSUE THREAD

**Issue by ganySA** [angular/material#7418]
Hi

If you change the tab style with custom CSS the margins breaks the layout because the tab calculation does not take into account any margin on the elements.

Here is a fix - call getComputeStyle then add left and right margin to the calculation.

     function updatePagingWidth() {
         var width = 1;
        angular.forEach(getElements().dummies, function (element) {
        // uses `getBoundingClientRect().width` rather than `offsetWidth` to include decimal values
   
        var style = window.getComputedStyle(element, null);
        width += style.marginLeft;
        width += style.marginRight;
        width += Math.ceil(element.getBoundingClientRect().width);
        });
        angular.element(elements.paging).css('width', width + 'px');
      }

**Comment by topherfangio** [comment]
@ganySA Care to submit a PR with tests? If you don't have time, could you at least add a Codepen to this issue so that we can look into it when we get a chance?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
