### ISSUE TITLE
default theme is injected even when we use setDefaultTheme with another value

### ISSUE THREAD

**Issue by david-gang** [angular/material#7425]
In function generateAllThemes we have teh following code

```javascript
 angular.forEach(THEMES, function(theme) {
    if (!GENERATED[theme.name]) {
      generateTheme(theme.name);
    }
  });
```

this code is called also for 'default' theme even when actually i used setDefaultTheme with another theme name.
This should not happen.
The result is that have twice style tags as i would really want.

**Comment by DevVersion** [comment]
@david-gang Indeed, this seems not to be correct. I've create a PR, which fixes that issue.
