### ISSUE TITLE
md-list: primary action fires for secondary action when using ui-sref instead of ng-click

### ISSUE THREAD

**Issue by ruant** [angular/material#7431]
Current development environment:
angular: 1.4.8
angular-material: 1.0.2
angular-ui-router: 0.2.15

When a seconday action is present on a list item with ui-sref attribute (no ng-click attribute) the secondary action is never moved out into the _md-secondary-container.
Everything looks like it should work, but the primary action is fired (and also highlighted when hovering the secondary action)

**Comment by DevVersion** [comment]
@ruant There was a lot of progress in the `md-list` component. If you use `master`/ `HEAD`, then the primary button won't be fired. Can you confirm that?

**Comment by ruant** [comment]
@DevVersion  You're right. My bad, I should update more often.
Thanks for responding so quick.

**Comment by ruant** [comment]
@DevVersion 
One question, I haven't tested this and I don't know what changes that was made to make the ui-sref work, but would it still be necessary to do the process of move the ng-click out into it's own container? Or could that code be removed entirely?
