### ISSUE TITLE
md-chips & duplicate values

### ISSUE THREAD

**Issue by bathos** [angular/material#7435]
The md-chips directive was probably designed foremost as a "tags" input, so the default behavior of discarding duplicates makes sense.

However this type of input can also be useful in situations where de-duping isn't desired. In my particular case it broke my heart because the md-chips directive was ideal in all other regards -- it's compact, inline, and items can be removed and reordered individually, and these are features that I'm pretty sure don't exist in any other material design inputs. I've been combing through the code to see if there's some hidden configuration for the automatic de-duping behavior, but it's looking like there isn't such a thing.

The docs say this component is a work in progress, so I figured I'd throw out there that I think it'd be great if this behavior were optional.

**Comment by iRoachie** [comment]
Can't you just check for duplicates on the array provided for the model?

**Comment by DevVersion** [comment]
@bathos In general it's easy to prevent the `de-duplication`, you just need to specify a unique object for every chip. See for example in my demo. http://codepen.io/DevVersion/pen/wGMdmy?editors=1010

**Comment by bathos** [comment]
Thanks, @DevVersion -- "transform" is a great solution, and I overlooked it because I had the wrong idea about where it fit into the pipeline. I'll need to wrap it in a custom ng-model directive if I want to actually model an array of primitives (numbers, in my case), but that's quite sensible anyway (validation, etc). Closing because `transform` is a suitable generic tool for dealing with this and probably other usage variations.

**Comment by Dunos** [comment]
I don't think this is issue should be closed, the allow duplicates must be clearly an option, set to false by default to the regular use, but sometimes you might want to use this type of field for something that may require duplicate elements, and the object transform is not a good option.
