### ISSUE TITLE
Angular Material Autocomplete

### ISSUE THREAD

**Issue by dhiman252** [angular/material#7438]
Do we have any option to disable an item listed in the autocomplete ?
Like wise we have a listing of the items and i want to disable some items to be selected but want them to display.

**Comment by DevVersion** [comment]
I don't think this is desired by the specs. In my opinion an autocomplete component should be used to complete the entered text, instead of just displaying options (with even disabled item)

**Comment by topherfangio** [comment]
@dhiman252 No, I don't think we have this functionality currently.

@DevVersion I think this may be something that we consider adding in the future though; particularly for people who use the Autocomplete like a Select. The default HTML Select allows you to disable certain options which can provide feedback to the user.

I think this topic could definitely use some more discussion and perhaps some feedback from the UX team.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
