### ISSUE TITLE
md-datepicker disable views.

### ISSUE THREAD

**Issue by furyscript** [angular/material#7443]
Hi,

I need to be able choose only week like `17 to 23` without disable day that I don't use. At this moment I set only Sunday available and I go Sunday by Sunday...

If there is this feature let me know otherwise can you link me some plugins? Thanks...

**Comment by topherfangio** [comment]
Checkout the [Datepicker Demo](https://material.angularjs.org/latest/demo/datepicker), specifically the "Only weekends are selectable" one. I think it will do what you need.

Please post a comment if it's not what you're looking for and I will reopen.
