### ISSUE TITLE
minimal requirement : difference between bower and npm

### ISSUE THREAD

**Issue by merlosy** [angular/material#7445]
In v1.0.6 (current), the minimal version required for Angular modules is different between : 

- Bower (^1.4.8), and 
- Npm (^1.5.0).

Is Angular 1.5.x really supported yet?
Thx

**Comment by Frank3K** [comment]
Angular 1.5.0 works fine for me.

**Comment by appie18** [comment]
For some reason I just can't get angular material to work with angular 1.5

**Comment by ThomasBurleson** [comment]
Not an issue.
