### ISSUE TITLE
Toolbar content does not change when clicking browser back

### ISSUE THREAD

**Issue by jlmagee** [angular/material#745]
If for example, I navigate to Demos Subheader and then click browser back, the page content changes but the toolbar content still has "Demos > Subheader"

Thought you'd want to know.

On an unrelated note, I find it annoying that one cannot scroll content using the up/down arrow on my keyboard

**Comment by marcysutton** [comment]
I'm not seeing this issue anymore, the docs toolbar updates with the back button.
