### ISSUE TITLE
md-dialog: async animation behavior allows more than one instance (unexpected)

### ISSUE THREAD

**Issue by mpiasta-ca** [angular/material#7450]
Plnkr demo (try "Expected" and "Actual" examples):
https://plnkr.co/edit/IYzkQvEDINbuecK13L4F?p=preview

You can also try to uncomment script.js@29 (remove script.js@27) to see some even worse behavior. In that case, you can't close the md-dialog in the "Actual" example at all.

Seems that md-dialog is not supposed to allow two instances to open at once. So if one instance is already open, and another md-dialog instance is triggered, it's supposed to close the first instance and then open the second instance.

But there is ~300ms where md-dialog has opening animation. So if another md-dialog is launched in this time, both will open, causing two instances of md-dialog-container (and two instances of md-dialog-backdrop). And in some cases, the first md-dialog content is overwritten by the second md-dialog, so it serves no purpose for both to be open.

This can happen if you have an app that launches an md-dialog upon boot (ie. user must select a country or state/province before doing anything else on the website; while a second md-dialog is triggered from elsewhere, like a "Connection failed" message related to an API call or some files that didn't load as expected).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
