### ISSUE TITLE
md-divider md-accent not working

### ISSUE THREAD

**Issue by whittssg** [angular/material#7451]
When i ad the class md-accent to a md-divider the color remains the same (light grey) and doesnt change to the themes accent color..

Is this normal?

thanks

**Comment by DevVersion** [comment]
That's currently not supported by the `divider` component, but it would be a nice enhancement.

**Comment by DevVersion** [comment]
Update: The specs say that dividers should not have any color.

https://www.google.com/design/spec/components/dividers.html

**Comment by whittssg** [comment]
Ok thanks.. i was trying to figure out a nice way of splitting input blocks... the divider would have worked if it wasnt the same color as the text input line - it makes it look like their is another field to fill in..

![image](https://cloud.githubusercontent.com/assets/6453857/13582775/2aa9e062-e47c-11e5-829d-b04dd5272fc4.png)

Not related but.. why do the fonts look different between the 3 input types (datepicker, select and input).
