### ISSUE TITLE
selection and cursor: should be accent color by the spec

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#7453]
As mentioned in [here](https://www.google.com/design/spec/components/text-fields.html#text-fields-style)
and as clearly seen in 

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3YUpKa211TW5leWc/patterns_selection_text_color2.png)

![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3bGtkM3VYcWlPTWM/patterns_selection_text_color1.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
