### ISSUE TITLE
ng-show is not working on md-progress-circular

### ISSUE THREAD

**Issue by jelbourn** [angular/material#7454]
See the first progress-circular on the page:
http://codepen.io/jelbourn/pen/RareKa

cc @calebegg

**Comment by ThomasBurleson** [comment]
Another demo with issue http://codepen.io/anon/pen/grpNNO?editors=1000

cc @EladBezalel

**Comment by Frank3K** [comment]
Facing the same issue. Observed behavior: when the value for `ng-show` is constant (either `true` or `false`) it does not work. When the value is set later on (e.g. from an onLoaded callback) it does work (at least in my case).
