### ISSUE TITLE
Angular material date picker not able to update ng-model value on keyboard change in IE

### ISSUE THREAD

**Issue by AshwanKumar** [angular/material#7456]
Hi Team,

We are using angular material components in our project and for having customized dates we used angular material date picker and found that in IE when user manually changes the date using keyboard the ng-model value doesn't get updated, I have even checked with angular site and same problem exists in site as well.

Here is the screenshot of above mentioned problem.
![untitled](https://cloud.githubusercontent.com/assets/17707222/13603101/d18abdfe-e560-11e5-975e-baf9991e670a.png)

As you have seen in screen shot I have changed the year to 2015 but still the calender shows march 2016 only and ng-model still holds 8th march 2016 as a value.

Kindly please help us in above mentioned issue.

Regards,
Ashwan Kumar Siddireddi
ashwan.s.91@gmail.com

**Comment by crisbeto** [comment]
The cause for this one is that the browser can parse dates in the format MM/DD/YYYY, but not DD/MM/YYYY. If your locale happens to use the second one, it gets considered invalid. This is because the initial value on the `input` gets set via `toLocaleDateString`.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
