### ISSUE TITLE
md-autocomplete: When clicking on the clear button, the md-not-found template appears instead of the searched results

### ISSUE THREAD

**Issue by siulung4073** [angular/material#7457]
This is going on in **1.0.6** and it can be reproduce in the material demos. In fact in my app, it doesn't show the search result. I have to click on the `md-not-found` template and it then appears.
But since in the material demos it also happens you can see it there

1. Select Simulated Query
2. click in the input
3. select any item
4. click the clear button
5. you should see the `md-not-found` template
6. click in the `md-not-found` template and the results appear

Again, in the material demos you can see it for a second or two. in my app, it stays

![animation](https://cloud.githubusercontent.com/assets/5748554/13603372/89e2070e-e51b-11e5-8b11-a09823818383.gif)

![animation2](https://cloud.githubusercontent.com/assets/5748554/13603470/2c62b208-e51c-11e5-94ee-1ee1c6b91e0b.gif)

**Comment by RolandHeath** [comment]
I can confirm this (chrome 48.0.2564.116, fedora 22).
I also found that after the results appear, if I waited a little while (about 3 seconds), California showed up (right where it belongs, just a bit late). That probably either deserves a separate issue though, if it doesn't already have one.

**Comment by topherfangio** [comment]
@RolandHeath The 3 second delay may be related to #7159. I am working on a fix for that as well.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by adminarun** [comment]
how to use the clear button to call the function when clicking cleare button
