### ISSUE TITLE
data-ng-click doesn't work on md-list-item

### ISSUE THREAD

**Issue by stuartm** [angular/material#7463]
data-ng-click doesn't work, changing it to ng-click however does.

The data- prefixes are required if you run your project through HTML validation tools - https://docs.angularjs.org/guide/directive#normalization

**Comment by DevVersion** [comment]
Yes, this is a known issue and there's already a previous issue. So I'll close this as a duplicate of #4392

**Comment by stuartm** [comment]
Apologies, I didn't find the earlier issue when searching
