### ISSUE TITLE
md-fab-speed-dial should support disabled state

### ISSUE THREAD

**Issue by bchen888** [angular/material#7473]
The md-fab-speed-dial tag doesn't support "ng-disabled" attribute. Adding it to the trigger button just makes the button looks disabled, but it still opens the speed dial.

http://codepen.io/anon/pen/wGGWVb

**Comment by topherfangio** [comment]
Agreed. We'll try to add that functionality soon. In the meantime, PRs would be welcomed :smile:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by vishnu-vv** [comment]
Is this issue closed ??? 
Fixed ???

**Comment by Jonybang** [comment]
@vishnu-vv You can use ng-disabled for md-button inside md-fab-trigger + ng-if for md-fab-actions

**Comment by garretwilson** [comment]
> You can use ng-disabled for md-button inside md-fab-trigger + ng-if for md-fab-actions

There seems to be a big problem even with this workaround in Angular 1.6.4 with Material 1.1.3: using `ng-if` prevents the actions from initially being hidden, even using `ng-cloak` on the parent container. Worse, if the condition for `ng-if` is `false` but later becomes `true`, the trigger becomes enabled and the actions appear! In other words the speed dial shows as open, and I'm required to click on it to close it.

**Comment by garretwilson** [comment]
> You can use ng-disabled for md-button inside md-fab-trigger + ng-if for md-fab-actions
> There seems to be a big problem even with this workaround in Angular 1.6.4 with Material 1.1.3 …

It turns out you also have to switch to using `md-scale` instead of `md-fling` to get this workaround to work.
