### ISSUE TITLE
md-slider does not update correctly when change min value

### ISSUE THREAD

**Issue by johnrivelt** [angular/material#7474]
#479 

It still seems not working correctly in my case.
Here is my case from plunker.

[https://embed.plnkr.co/FCizUTQnOTzsklhxSIry/](https://embed.plnkr.co/FCizUTQnOTzsklhxSIry/)

click SSD 1 -> SSD 10 direction set min and value correctly.
But SSD 10 -> SSD 1 backward case, md-slider does not update correctly.
Even min-value is same with valuenow but slider cursor indicate middle of somewhere.

**Comment by topherfangio** [comment]
Can you please create a more simple example using Codepen? There is a lot of custom code in the existing Plunkr that makes it difficult to understand.

**Comment by johnrivelt** [comment]
Here is simpler one.

http://codepen.io/johncho/pen/rejKJj

On Fri, Mar 18, 2016 at 8:22 AM, Topher Fangio <notifications@github.com>
wrote:

> Can you please create a more simple example using Codepen? There is a lot
> of custom code in the existing Plunkr that makes it difficult to understand.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/7474#issuecomment-198086931>
>



-- 
Regards
John, Cho
王言, 趙
Wang Eon, Cho

**Comment by topherfangio** [comment]
@johnrivelt Thanks!

@EladBezalel Looks like it has a problem when the min value goes from larger to smaller.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
