### ISSUE TITLE
Expose the <menu-toggle> directive used in your demo app.

### ISSUE THREAD

**Issue by migmigmig** [angular/material#7475]
You guys have an awesome demo app:  https://material.angularjs.org/latest

It has an awesome left-nav menu using a `<menu-toggle>` directive.

Your awesome menu-toggle isn't available as a standard part of your set of directives.

I'd like to awesomely use it without cargo-culting it.  :) ?

Thanks!

mig

**Comment by topherfangio** [comment]
@migmigmig I would enjoy seeing this as well, but with everything else we have happening, I think this is a fairly low priority. PRs would most certainly be welcome!

**Comment by DevVersion** [comment]
@topherfangio Do we really want to add this as a new component? I think it's not a component which has  a material design policy?

**Comment by topherfangio** [comment]
Actually, this is VERY similar to #985; although I think that one assumes the use of the existing List component.

**Comment by migmigmig** [comment]
Actually, when it came down to it, I wound up using the angular-recursion
compiler and implementing a proper tree.

But something along these lines would be nice to have out of the box.

Uber bonus points for a nested tree implementation that doesn't require the
user to install extra modules.

mig

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
