### ISSUE TITLE
md-tooltip + md-datepicker

### ISSUE THREAD

**Issue by tom94zoe** [angular/material#7476]
Is it possible to use md-tooltip on a md-datepicker.?
I change the plunkr(datepicker) code but nothing happend. 
Currently I used a span-tag around the datepicker, it works, but that couldn't be best practice.

**Comment by topherfangio** [comment]
Please provide a Codepen of the issue using the latest version of Material and we will reopen.

**Comment by VikramTiwari** [comment]
Does not works. http://codepen.io/anon/pen/Kzyzxo

**Comment by tom94zoe** [comment]
@VikramTiwari, you sir are awesome

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
