### ISSUE TITLE
md-dialog & restoring focus

### ISSUE THREAD

**Issue by bathos** [angular/material#7478]
In the demos, when a modal closes, focus is restored to the element which had focus previously. This behavior wasn't occurring for me with a custom modal that looks like this and gets launched from an ng-click on an md-button:

```js
    scope.open = () => {
      const dialog = $mdDialog.show({
        clickOutsideToClose: true,
        closeTo: button,
        openFrom: button,
        preserveScope: true,
        scope,
        template: `
          <md-dialog flex="33" md-padding>
            <md-dialog-content>
              <div class="md-dialog-content">
                <h1>
                  <md-icon md-svg-icon="{{ icon }}"></md-icon>
                  {{ button }}s
                </h1>
                <md-input-container>
                  <md-chips
                    aria-label="{{ button }}s"
                    md-autofocus
                    md-transform-chip="toObject($chip)"
                    ng-model="model.list"
                    um-numbers-only="float">
                    <md-chip-template>
                      {{ $chip.value / 100 | currency }}
                    </md-chip-template>
                  </md-chips>
                </md-input-container>
              </div>
            </md-dialog-content>
          </md-dialog>
        `
      });
    /* ... */
    };
```

The activeElement was `body` after the dialog closed regardless of the closing mechanism. I was able to achieve the correct behavior easily enough anyway (`dialog.then(focusButton, focusButton);`), but it seemed like it may be a bug that this was necessary, unless maybe this is intentional behavior for custom dialogs? This was with version 1.0.6.

**Comment by topherfangio** [comment]
@DevVersion Seems related to your comments on commit https://github.com/angular/material/commit/e592012d03fb9208136f0f18f70566d4537ffcd1?

**Comment by DevVersion** [comment]
@topherfangio Can be the problem, but to be honest I can't reproduce this bug. 

@bathos So it would be very great if you provide a demo (codepen etc), so I can investigate better at your issue.

**Comment by DevVersion** [comment]
Not an issue, you need to specify the `options.targetEvent` or `options.origin`

Here is the code snippet: [Here](https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L709)
