### ISSUE TITLE
it is possible to have< md-menu-bar> horizontal scrolling option like for md-tabs ?

### ISSUE THREAD

**Issue by christianpanea** [angular/material#7481]
Here is the issue !
![5ebmm 1](https://cloud.githubusercontent.com/assets/13203612/13634326/8be855ac-e5fd-11e5-9f74-2f26cbacce25.png)

http://i.stack.imgur.com/5EbmM.png

**Comment by topherfangio** [comment]
This sounds like a decent request, but it is fairly low in priority. PRs would certainly be welcome :-)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
