### ISSUE TITLE
mdSideNav: Animation is broken when specifing "style="width: ...px" attribute

### ISSUE THREAD

**Issue by levgaas** [angular/material#7483]
I have a scenario when a sidenav has ability for resizing dynamicly.

For that purpose I add **"style="width: ...px"** attribute for **<'md-sidenav'>** element.
Resizing works perfectly. 

But after attribute is added animation of the toggle is broken. Without it animation works.

Here is [Codepen](http://codepen.io/anon/pen/qZZxQB)

Thanks!

**Comment by DevVersion** [comment]
Note: Also caused when applying `[flex]` on the sidenav. (Applying flex on the sidenav is really common)

**Comment by flick36** [comment]
I don't think this is solved, code pen still doesn't work and in my project when i was in 1.1.0-rc2 i solved this by also setting the `min-width & max-width` to the custom `width` i set by default, for example:

    md-sidenav, md-sidenav._md-closed._md-locked-open-add-active {
        width: 240px;
        min-width: 240px;
        max-width: 240px;
    }

but now in 1.1.0-rc3 it doesn't work, and the slideIn animtion doesn't work, only when you hide the nav the animation it's working

**Comment by flick36** [comment]
the min-width's have to be `important` cause if i remove them, the animation it's working:

http://codepen.io/flick36/pen/pyLQgP
