### ISSUE TITLE
md-item-value in autocomplete

### ISSUE THREAD

**Issue by Knoxvillekm** [angular/material#7485]
How to set value expression (like md-item-text for display). For now model contains full object, need use only him 'id' field.

**Comment by topherfangio** [comment]
We don't currently offer an attribute for this, but you should be able to do what you need using the `md-selected-item-change` callback method to set what you need.

https://material.angularjs.org/HEAD/api/directive/mdAutocomplete

If that doesn't work; can you please provide a Codepen showing what you're trying to do?
