### ISSUE TITLE
autocomplete Lexer error with "in" keyword

### ISSUE THREAD

**Issue by debslord** [angular/material#7486]
When using autocomplete the search functionality fails if the source (md-items) includes an item where the display property (md-item-text) contains the keyword "in"

For example display property could be "Not in here"

`Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 47-51 ["Not] in expression [lookupSearch(searchText, [{"_id":"51e06ddf3121a51700fdbf29","description":"Not].`

This occurs when clicking the autocomplete box and a message appears saying it cannot find any items.  The error is thrown in the console.  It only occurs if there is text before and after the in and a space either side as in my example.

**Comment by DevVersion** [comment]
@debslord Can you please provide a demo of your issue?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
