### ISSUE TITLE
md-input textarea is broken as earlier

### ISSUE THREAD

**Issue by jalajc** [angular/material#7487]
md-input textarea is broken as earlier in #2007 
Bug is even in 1.06
1. scroll-bar is not appearing
2. when in md-no-autogrow just one line of text appears (even if rows= 5, and one has 3 lines of text)
3. md-select-on-focus: just flashes the select and then select disappears.

**Comment by crisbeto** [comment]
@jalajc I've fixed 1 and 2, however I can't reproduce 3. Do you have any more info?

**Comment by jalajc** [comment]
for 3: Check the first demo (Basic Usage) at https://material.angularjs.org/latest/demo/input
Notice behavior for textarea: '_Biography_'.
When you click on text, text flashes and disappears (you make have to click on text and outside at multiple times-it was little unpredictable today!)

**Comment by crisbeto** [comment]
Ah I see what you mean. It doesn't happen on Chrome, but it definitely does on Firefox. For future reference: 

![select](https://cloud.githubusercontent.com/assets/4450522/13730435/8d59f954-e94f-11e5-9629-90027b0e5372.gif)

**Comment by jalajc** [comment]
Thanks for the gif grab, that's what I was referring to.
apparently, this is happening for me on chrome too, Version 43.0.2357.132 m.

**Comment by DevVersion** [comment]
This is only happening if you hit the cursor between the chars.

**Comment by crisbeto** [comment]
Not quite sure that's the case, here me trying to hit right in the middle of the "m". The gif recording app seems to move the cursor slightly though:

![select](https://cloud.githubusercontent.com/assets/4450522/13730845/4fc3034a-e95b-11e5-86c0-82ebb5962d4e.gif)

**Comment by crisbeto** [comment]
Seems like a `mouseup` event is being fired right after the focus. Preventing the default solves it but makes for a crappy user experience.
