### ISSUE TITLE
allow md-select-on-focus on md-autocomplete

### ISSUE THREAD

**Issue by ilovett** [angular/material#7493]
`md-select-on-focus` directive can only be used on input and textarea, it would be great if it could be used on `md-autocomplete` and be applied to the input created by autocomplete

**Comment by mzbyszynski** [comment]
Hi @ilovett, 

I think this was implemented. See #7125

**Comment by ilovett** [comment]
Nice. Thanks.

**Comment by Maks-Yaremenko** [comment]
doesnt work for me, where i must put this attr? 
can any body told me how to select selected text by click or focus on input with autocomplete? i would like to clear input text if user start typing after click or focus on this field, but i dont know how to do that =(
