### ISSUE TITLE
MD-Tabs with MD-Icons off-centered

### ISSUE THREAD

**Issue by k3ilbasa** [angular/material#7495]
Adding an md-icon inside an md-tab-label produces an icon that is off-centered inside its container if the size is over 24px.

```
        <md-tabs md-dynamic-height md-stretch-tabs="always" md-border-bottom>
          <md-tab>
            <md-tab-label>
              <md-icon style="font-size:48px" class="material-icons md-primary">warning</md-icon>
            </md-tab-label>
            <md-tab-body>
              <md-content>
                content1
              </md-content>
            </md-tab-body>
          </md-tab>
```

[codepen](http://codepen.io/wdshannon/pen/BKKqNK)

**Comment by mckenzielong** [comment]
@k3ilbasa Might want to check that codepen again... currently not demonstrating the issue.

**Comment by DevVersion** [comment]
@mckenzielong Is right, please provide a demo which represents your issue.

**Comment by topherfangio** [comment]
Also, please tell us what browser(s) is having issues unless it manifests in all browsers.

**Comment by k3ilbasa** [comment]
Sorry about that, not quite sure how I linked the wrong one.  The correct one is [here](http://codepen.io/wdshannon/pen/ZWWqxM)

**Comment by topherfangio** [comment]
@k3ilbasa You have changed the `font-size` property to make it larger, but you didn't update the width/height to compensate.

Here is an example where the first two icons are fixed: http://codepen.io/topherfangio/pen/EKNjav

_P.S. I would recommend doing this in your stylesheet instead of a `style="..."` tag._

**Comment by mckenzielong** [comment]
@topherfangio huh, interesting... haven't really used font-icons all too often myself... is it common to set width/height and font-size?  It isn't terribly obvious that you would have to do that (see docs: https://material.angularjs.org/latest/demo/icon, only changes the font-sizes)

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (423/400 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:54256 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMi-000akn-UF
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:30 +0100
Date: Mon, 14 Mar 2016 13:28:41 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457987321;
	bh=UZv1Tw1pAiIymzw7inxrVoIAlU2Xcm0YfOtMmt1VxTY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=PtNrhVR0qL0L7B5leA+WJUvYqdKA/kds36iLy2ZyJgbWC/xM/RZxBMgObNEPH9Ir8
	 1rWrI7oDwpGUUO13B5sXITOC2Exca+IKkE6L+gRo1GQkGLa5ErcfGC9ha+d67xK/s8
	 Y+HYbb2QKy69R1s0I4Dh5Dikq0Xef4bY63wvH7J8=
