### ISSUE TITLE
Autocomplete progress bar height is wrong

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7497]
Progress bar height is too large on autocomplete

Just try to write something in the autocomplete
http://codepen.io/anon/pen/mPPZYK

**Comment by DevVersion** [comment]
In my case it works? The `5px` height progress bar is showing up.

**Comment by gpopovic** [comment]
I know it works, but 5px is too large.. It wasn't that big before..

**Comment by DevVersion** [comment]
You just saw it that small, because the item panel overlaid the progress bar. In general the progress was always that big.

**Comment by gpopovic** [comment]
What about autocomplete with floating label? Is it suppose to be that large here also?

http://codepen.io/anon/pen/mPPZYK

**Comment by DevVersion** [comment]
Oh I'm overwhelmed about that, I'll ask the team about that.

**Comment by gpopovic** [comment]
Not sure if related, but loading on select is also a lot bigger in master than in v1.0.6.

**Comment by DevVersion** [comment]
@gpopovic Just investigated a bit, and the height of `5px` isn't by intention, it should be `3px`. Issue introduced in 78ccef6354cbe8898bfe3c489e3b7ea1d43bbffc

**Comment by gpopovic** [comment]
Done, #7505
