### ISSUE TITLE
Autocomplete returns error when query result is null or undefined

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7498]
When query result is null or undefined, autocomplete will throw an error 
"Cannot read property 'length' of null"

I think autocomplete should be smart enough to check if query result are null or undefined and parse it as an empty array.

Try to write anything to autocomplete, and check logs
http://codepen.io/anon/pen/NNNQKV

**Comment by topherfangio** [comment]
The issue is in the `hasMatches()` function which doesn't check if `ctrl.matches` exists. This is an NPE which we should definitely fix.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
