### ISSUE TITLE
Typo in docs! 

### ISSUE THREAD

**Issue by pushkarmoi** [angular/material#7501]
Demos> Input> Errors
When the user enters a hourly USD rate.
When the value esceeds a limit, the error shown is: 
" $50,022 an hour? That's a little ridiculous. I doubt event Bill Clinton could afford that."
"event". 
Seriously? You dont make a typo while giving a quirky error message

**Comment by DevVersion** [comment]
Closing this, because the issue is already known and a PR is in progress. #7364
