### ISSUE TITLE
md-date-picker no longer transparent

### ISSUE THREAD

**Issue by whittssg** [angular/material#7502]
My datapicker used to be transparent (i have it in a card that has a white background):

![image](https://cloud.githubusercontent.com/assets/6453857/13671025/69f1effa-e69b-11e5-8480-2d16f94e27fe.png)

No it has a slight grey color to it..

**Comment by topherfangio** [comment]
Good catch; you can't see the issue in our demos because the grey color matches the new body background. Changing the demo background to white makes this easily visible.
