### ISSUE TITLE
mdMenu: Cascaded Menus (Feature Request)

### ISSUE THREAD

**Issue by maelfrize** [angular/material#7507]
Hi,

I was wondering if cascaded menus are still on your roadmap.

It was mentioned here as 'phase 2' of the md-menu component and was targeted for v0.11: https://github.com/angular/material/issues/78#issuecomment-106292335

Here are the Material Design specs:
https://www.google.com/design/spec/components/menus.html#menus-usage

> Desktop: a menu can also cascade. Reposition menus vertically and horizontally based on their proximity to screen edges.

![components_menus_usage7](https://cloud.githubusercontent.com/assets/11228926/13676278/7152971e-e6e5-11e5-8f61-c0b6e7a41a88.png)

Thanks a lot for all your efforts!

**Comment by topherfangio** [comment]
@maelfrize Are you asking about the Menu Bar? https://material.angularjs.org/latest/demo/menuBar

**Comment by ThomasBurleson** [comment]
Will not implement stand-alone (outside menuBar) cascaded menus.
