### ISSUE TITLE
ng-view animation not working in IE11

### ISSUE THREAD

**Issue by kumar99m** [angular/material#7511]
Hi,

I am trying to use CSS3 animations in ng-view, it seems working fine in Chrome and FF and in IE 11 it is not working as expected(In IE11 animation is really slow) , I am using Angular Material Framework, please suggest.

**Comment by topherfangio** [comment]
Please provide a Codepen demonstrating your code/issue.

**Comment by kumar99m** [comment]
Hi topherfangio,

Thanks for the response, yesterday I have played with different versions of angular material CSS
(https://cdn.gitcdn.link/cdn/angular/bower-material/v1.0.0/angular-material.css) and I have identified the issue occurs only with version 1.0.6, I will provide the demo code soon.

**Comment by ThomasBurleson** [comment]
If you demo shows this issue still exists with 1.1.0-rc1 then we will reopen.
