### ISSUE TITLE
1.1.0-rc1 md-content is transparent. Shouldn't it inherit from the body?

### ISSUE THREAD

**Issue by cadilhac** [angular/material#7512]
Changelog says:

> md-content no longer has defined background color; most components inherit background color from body

I checked that the body actually now defines a background color and it does. But when I display an md-content (in an absolutely positioned popup), it is transparent. Is it normal?

**Update**:
I just read about [inheritance of background-color](https://developer.mozilla.org/en-US/docs/Web/CSS/background-color). Can it really be inherited as your changelog says?

**Comment by topherfangio** [comment]
We're trying to make fewer assumptions about how people use our components. In the case of `<md-content>`, this could very easily be used in the left sidenav, the main body, or even a popup (like you suggest).

Based on recent updates to the [Material Color Themes Spec](http://www.google.com/design/spec/style/color.html#color-themes), the popup/dialog is what should have the background color set to white. Depending on what your popup looks like, you might easily add the [whiteframe attribute](https://material.angularjs.org/latest/api/directive/mdWhiteframe) to get the color you want.

**Comment by ThomasBurleson** [comment]
`md-whiteframe` is only a *box-shadow*... and does not assign/define a background color.

**Comment by cadilhac** [comment]
I now use RC3 and I see this style set by angular material:

md-content.md-default-theme, md-content {
    background-color: rgb(250, 250, 250);
    color: rgba(0, 0, 0, 0.87);
}

So now md-content has changed again and is not transparent anymore?
If md-content is in a parent (not an angular material component), how should I set the parent color so that it's the same than the md-content?

**Comment by ThomasBurleson** [comment]
@cadilhac - we have been working to improve (a) how Theme works with foreground and background colors and (b) compliance with the MD specs. Content and Subheader now have the same background colors. `background-color: '{{background-default}}';` which === `#fafafafa` for the background grey palette (default). 

If you want to color the parent similarly use the new directive `md-colors="{background-color:'background-default'}"` on the parent element.
