### ISSUE TITLE
release: chips theme unexpected bracket

### ISSUE THREAD

**Issue by DevVersion** [angular/material#7514]
![](https://i.gyazo.com/b065fb6290854023fd923070d5aef395.png)

![image](https://cloud.githubusercontent.com/assets/4987015/13681491/b4048816-e6fd-11e5-8eb1-7d4d1b071b66.png)

**Comment by ThomasBurleson** [comment]
@DevVersion - my dev environment does not have any issues with SASS `unquote()`

**Comment by DevVersion** [comment]
@ThomasBurleson Try building the closure modules and also have a look at the Travis Build & Deploy Output

**Comment by DevVersion** [comment]
Fixed with SHA 467129ccac2cfbc1f1e4eeffea02cc06d8fa0a03
