### ISSUE TITLE
weird behaviour on chrome 48 - mac

### ISSUE THREAD

**Issue by lionelB** [angular/material#7516]
Hello,
Thanks for this amazing lib !
I have a strange behaviour using chrome (Version 48.0.2564.116 (64-bit)) on mac 
Visiting https://material.angularjs.org/1.1.0-rc1/demo/dialog 
click on **alert dialog** 
click  **Got it!** 
there is noticeable delay before the dialog close and after that, I can't  click anymore on buttons to open another dialog. 

Using chrome canary, all seems to be ok.

**Comment by ThomasBurleson** [comment]
Unable to reproduce on Chrome Version 48.0.2564.116 (64-bit)  (Mac OSX El Capitan).

**Comment by lionelB** [comment]
Since I encounter the problem today with the latest chrome,  I decided to investigate more, it seems to be a chrome memory problem (I don't restart my computer / browser so often). 
Once the browser is restarted, all's go fine !

Hope it helps.
