### ISSUE TITLE
md-fab-speed-dial keyboard accessibility

### ISSUE THREAD

**Issue by dlombardi** [angular/material#7517]
when landing on the md-fab-speed-dial element while tabbing through the web page it will start to cycle off and on it and not move on to the next elements.

**Comment by topherfangio** [comment]
Yup. It looks like it isn't properly skipping the actions when it's closed.

They should have the `tabindex` set to `0`. We will investigate/fix.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
