### ISSUE TITLE
select: Options have no hover effect on 1.1.0-rc1

### ISSUE THREAD

**Issue by topherfangio** [angular/material#7518]
When hovering a select option, there is no longer a hover effect. Likely due to recent privatization changes.

Can be viewed on the select demo page for latest/HEAD.

**Comment by DevVersion** [comment]
@topherfangio I've never seen a hover effect on the select. 

See for example `v1.0.0`
https://material.angularjs.org/1.0.0/demo/select

**Comment by topherfangio** [comment]
@DevVersion You are indeed correct! Not sure how I didn't see this before. It's very odd as the [official spec](http://www.google.com/design/spec/components/menus.html) says nothing about hover effects. Yet, every single Google application I use (Inbox, Drive, Photos, G+, etc) all have a hover effect for the menus.

Perhaps we should touch base with UX on this?

**Comment by topherfangio** [comment]
Just spoke with Thomas real fast. He suggested that we create a PR of how it would look so that we have something we can show UX to get their feedback on exact colors and whatnot. This would be a breaking change, but we feel like it's probably worth it.

**Comment by DevVersion** [comment]
@topherfangio Yes, that sounds like a good idea. I think hover effect won't be even too much effort.

**Comment by crisbeto** [comment]
I've put in https://github.com/angular/material/pull/7765 to address this. I used the same hover styles as the autocomplete. Also fixed the disabled styles that weren't being applied.
