### ISSUE TITLE
data-binding in svg icon, using md-svg-icon, doesn't work

### ISSUE THREAD

**Issue by morwin10** [angular/material#7519]
Here is an example:
http://plnkr.co/edit/ImzTiPEKHqGhxsb9xygK?p=preview

I want to insert variable content in icon
But it doesn't work
It is possible ?

**Comment by topherfangio** [comment]
Honestly not sure if this is possible at the moment. @DevVersion can you take a look and see if it's easy to do already or if it's something we might want to add?

**Comment by DevVersion** [comment]
@topherfangio I don't think we should compile the SVG into a scope. That's how an icon is defined, an icon should have persistent paths etc. 

If you really want to use the SVG in a scope (for templating), then you should compile the icon yourself into a scope.

```js
      $mdIcon('with_data-binding').then(function(svg) {
        document.getElementById('data-binding-wrap')
          .appendChild($compile(svg.outerHTML)($scope)[0]);
      })
```
- http://plnkr.co/edit/Tx0GLaHJMdVzpclaQ817?p=preview

So in my opinion, a SVG should be not compiled within a scope.

**Comment by topherfangio** [comment]
I think I agree. Typically, any dynamic text/content would be handled outside of the SVG.

@morwin10 What is your use-case for dynamic content within the icon?

**Comment by morwin10** [comment]
`<svg id="cart" width="100%" height="100%" viewBox="2 0 100 85" xmlns="http://www.w3.org/2000/svg" fit="" preserveAspectRatio="xMidYMid meet">
	  <path id="svg_1" fill="#ffffff" d="m14.999,91c0,5.523 4.477,10 10.001,10s9.999,-4.477 9.999,-10s-4.475,-10 -9.999,-10s-10.001,4.477 -10.001,10zm50,0c0,5.523 4.477,10 10.001,10s9.999,-4.477 9.999,-10s-4.475,-10 -9.999,-10s-10.001,4.477 -10.001,10zm-32.264,-23.638l55.342,-15.812c1.058,-0.303 1.923,-1.45 1.923,-2.55v-27.5h-70.5v-8.5c0,-1.1 -0.899,-2 -2,-2h-15.5c-1.101,0 -2,0.9 -2,2v8h9.718l9.839,45.284l0.943,4.716v7.5c0,1.1 0.899,2 2,2h2.5h50h13c1.101,0 2,-0.9 2,-2v-7.5h-56.239c-5.748,0 -5.865,-2.253 -1.026,-3.638z"></path>
  <circle id="svg_2" r="34.07537" cy="20" cx="62.25" stroke-linecap="null" stroke-linejoin="null" fill="#3F51B5"></circle>
<text font-weight="bold" transform="matrix(2.1106928560326748,0,0,2.129052277984602,-65.3584283903659,-19.319146851608494) " xml:space="preserve" text-anchor="middle" font-family="serif" font-size="24" id="svg_3" y="25.41743" x="60.40827" stroke-linecap="null" stroke-linejoin="null" stroke-width="0" fill=" #FFFFFF" style="text-shadow: aliceblue; text-shadow: 2px 2px rgba(75, 150, 120, 0.62);">7</text>
</svg>`

**Comment by morwin10** [comment]
@topherfangio 
Actually I need it for cart icon with a number that changes every time there is an update quantity of the products in the cart

**Comment by topherfangio** [comment]
@morwin10 Is there some feature of `<md-icon>` which you need? It sounds like you might just want to create a custom `<cart-icon>` component that uses SVG instead of HTML?

**Comment by morwin10** [comment]
I'm not sure I understand you
I'm talking about `md-svg-icon` Directive.

I wanted to use it to display svg cart icon
And inside the svg icon I have my tag text 

My html looks like this If it helps :
```

    <span ng-show="ngCart.$cart.items.length">
      <md-button href="cart" class="md-fab md-primary md-fab-bottom-right" aria-label="cart-icon" style="position: fixed;"> 
        <md-icon md-svg-icon="cart" style="width: 41px; height: 48px; color: black; fill: #fff; vertical-align: sub;"></md-icon>
      </md-button>
    </span>
```

**Comment by topherfangio** [comment]
I think that compiling elements within an icon is not very common and might add a lot of overhead. Also, the `$mdIcon` service currently does a lot of caching for performance reasons, I am afraid that adding a dynamic capability might cause issues.

Have you tried @DevVersion's solution above? If that doesn't work for your needs, then I really think the best approach is a custom component used like this:

```html
<my-cart-icon num-items="numItems"></my-cart-icon>
```

and perhaps written like this:

```js
myapp.directive('myCartIcon', function() {
  return {
    restrict: 'E',
    template: '<svg><path d="..." fill="white" stroke="black"></path>{{ctrl.numItems}}</svg>',

    scope: {
      numItems: '='
    },

    bindToController: true,
    controllerAs: 'ctrl',
    controller: function() {
      // ...
    }
  }
});
```
