### ISSUE TITLE
How to extend the mdCalendar directive?

### ISSUE THREAD

**Issue by rvarbanov** [angular/material#7520]
I need to add to the mdCalendar two buttons that will allow the user to scroll to the next/prev month.

All of the howto's that I found online are very old.

Would you please point me the right direction?

**Comment by topherfangio** [comment]
You will probably have a bit more luck asking on the [forums](https://groups.google.com/forum/#!forum/ngmaterial).

We try to keep GitHub specifically related to bugs/feature requests. If you find a particular way that you would like to extend the calendar (like adding support for translcuded content somewhere), please feel free to open a separate issue with a bit more info about what you would like to see.
