### ISSUE TITLE
Scrollbars missing from md-select for MacOS users with scrollbars hidden

### ISSUE THREAD

**Issue by sarahb13** [angular/material#7521]
For users of MacOS, there is an option to turn off scrollbars. (System Preferences > General > Show scroll bars). At time some point, this setting was defaulted to "Automatically based on mouse or trackpad".

This means, that for md-selects that have more options than fit vertically into the element, the scrollbar is hidden. An example of this can be found in the Angular Material documentation for [md-select](https://material.angularjs.org/latest/demo/select) by clicking on the "State" example. 

I feel like there should be some way to indicate to users that there is more content in the md-select than is currently being shown that doesn't involve some of the horrible CSS + JS hacks that I've seen.

**Comment by jelbourn** [comment]
@ThomasBurleson would anyone have the cycles to look into this? It sounds like OSX default behavior makes life difficult for everyone.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
