### ISSUE TITLE
v1.1.0-rc1 md-list to md-list-item margin-right issue

### ISSUE THREAD

**Issue by siteshackinc** [angular/material#7522]
v1.1.0-rc1 broke margin-right on md-list-item. Text, or icon is about 32px off canvas.

`<md-list>
        <md-list-item ui-sref="{{item.state}}" ng-click="vm.close('left')" ng-repeat="item in menu.items | orderBy: order">
          <md-icon md-font-set="material-icons">{{item.icon}}</md-icon>
          <span flex></span>
          {{item.title}}
        </md-list-item>
      </md-list>`

Right now I just add `<span style="margin-right:32px;"></span>` after {{item.title}} to currently remedy this issue.

**Comment by DevVersion** [comment]
This should be already fixed in `HEAD` / `master`. Can you provide a demo or check your issue with `master`?

**Comment by siteshackinc** [comment]
Fixed in HEAD / master
