### ISSUE TITLE
Md-list-item with ng-click still broken in master

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7525]
It appears that text overflow is still not working on md-list-item with ng-click
http://codepen.io/anon/pen/KzMyGY

Solution this time is
`._md-list-item-inner {
    overflow: hidden;
}
`

**Comment by char0n** [comment]
I can confirm, but this requires some more information.
 
Only affected browser is Firefox. I can reproduce the issue on Firefox 44.x and Firefox 45.0
Latest Chrome and IE11 seems to be working fine. 

Basically this bug manifests it self as user not being able to click on item with primary action, which is really a big issue.

You can reproduce the issue directly on documentation page: 

Url: https://material.angularjs.org/latest/demo/list
Section: Avatar with Secondary Action Icon
Actual Behavior: clicking on `Janet Perkins` does not trigger primary action on list-item
Expected Behavior: clicking on `Janet Perkins` opens md-dialog

**Comment by char0n** [comment]
@gpopovic I don't get your workout. Can you collaborate more how to apply it ?

**Comment by gpopovic** [comment]
@char0n chrome is also affected!

use that css line and bug will be fixed..

example:

http://codepen.io/anon/pen/WwxyZp

**Comment by char0n** [comment]
@gpopovic yep, so I guess I am seeing a completely different issue then. I will issue a separate ticket. Any click on <md-list-item ng-click="action()"></md-listi-item> if the text is not overflowing in Firefox will no trigger action(). In Chrome  49.0.2623.87 m and IE 11 it will.

**Comment by ThomasBurleson** [comment]
Please make sure you are testing with the latest in `master` @ [HEADH](https://material.angularjs.org/HEAD/demo/list)

**Comment by char0n** [comment]
@ThomasBurleson will do, I was testing from 1.1.0-rc1 tag.

**Comment by gpopovic** [comment]
@ThomasBurleson this issue is tested on the latest master

**Comment by DevVersion** [comment]
@gpopovic I'm sorry for the issues. The list-item-inner was wider than the actual container.. this was caused by Flex and the container.

![image](https://cloud.githubusercontent.com/assets/4987015/13711120/2fb9e720-e7bd-11e5-96db-848c371950b7.png)

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (413/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:52944 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMW-000aiG-Gl
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:10 +0100
Date: Mon, 14 Mar 2016 10:00:51 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457974851;
	bh=oycnmra+IGsQeXYRR3UzNlrUV5NyF32ZT9aDNg2N5L0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=JbMTLNE8iXhUptQNX95nvfAyfxMc9CnSExRECkIlnjuZT+0QHakF6HaOGXouTIGlC
	 t8j6MLTV/MZjdHGjdqRi0u5vZc5u74pouUdSBVTF+tdGKkeqUGHVGWRLYJ7FxNuD09
	 EqEw0pK6pJ8Y0ofnpKcVlwn0gEaXuBjjoyBx3YNc=
