### ISSUE TITLE
md-menu-item with md-icon not side by side (FF issue)

### ISSUE THREAD

**Issue by stevezau** [angular/material#7526]
Using firefox 45.0 the menu items are not displaying correctly. The md-icon is below the menu button.

To reproduce just go to https://material.angularjs.org/latest/demo/menu and click the menu..

**Comment by char0n** [comment]
Yes I can confirm: affected version is 1.1.0-rc1. Affected is Firefox only.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
