### ISSUE TITLE
md-ink-ripple within md-theme get wrong colors

### ISSUE THREAD

**Issue by jakubweber** [angular/material#7527]
Hello, I found this (probably) issue.

When I have defined second theme. eg."dark", md-ink-ripple doesn't gets colors of "dark" theme, but it gets colors of "default" theme. 
If it's feature, it's inconsistent, because ripple of md-tab label gets correct color of ripple from "dark" theme.

```
<div md-theme="dark">
<a ui-sref="dashboard" md-ink-ripple>Dashboard</a>
<md-tabs md-selected="selectedIndex" md-dynamic-height>
 <md-tab label="Menu">
...
</md-tab>
</md-tabs>
</div>
```
Anchor in this example with md-ink-ripple gets background color from "default" theme.
The md-tab label and its ripple gets background color from correct "dark" theme.

**Comment by EladBezalel** [comment]
@jakubweber can you please provide a codepen?

**Comment by EladBezalel** [comment]
@jakubweber seems to [work](http://codepen.io/EladBezalel/pen/OXMevy) for me.

if it's still a problem please post a codepen with a repro and i will look into it.

closing for now.
