### ISSUE TITLE
Checkboxes and switches not rendering when using minified modules

### ISSUE THREAD

**Issue by iainmcgin** [angular/material#7529]
Switches and checkboxes do not render correctly when using the minified variants of the [separate modules](https://github.com/angular/bower-material/tree/v1.0.6/modules/js) in the bower repository. I'm using v1.0.6 imported using Bower. 

If I use [core.min.js](https://github.com/angular/bower-material/blob/v1.0.6/modules/js/core/core.min.js) instead of [core.js](https://github.com/angular/bower-material/blob/v1.0.6/modules/js/core/core.js), the background of the switches (and the accent coloring of the ripple) disappears.  Independently, if I use [switch.min.js](https://github.com/angular/bower-material/blob/v1.0.6/modules/js/switch/switch.min.js) instead of [switch.js](https://github.com/angular/bower-material/blob/v1.0.6/modules/js/switch/switch.js), the switch rendering disappears entirely.

I am including the full [angular-material.css](https://github.com/angular/bower-material/blob/v1.0.6/angular-material.css) by default. Switching between that and the [minified version](https://github.com/angular/bower-material/blob/v1.0.6/angular-material.min.css) does not appear to make a difference. 

Interestingly, if I also include [switch.min.css](https://github.com/angular/bower-material/blob/v1.0.6/modules/js/switch/switch.min.css), the toggle rendering works again, but without the background. The [non-minified](https://github.com/angular/bower-material/blob/v1.0.6/modules/js/switch/switch.css) version of that CSS file does not work.

I've created a codepen to demonstrate this issue: http://codepen.io/iainmcgin/pen/grPvaw

**Comment by DevVersion** [comment]
@iainmcgin I've tried to recreate your demo with the latest build (`HEAD` / `master`) and everything works as expected.

http://codepen.io/DevVersion/pen/JXRjrd?editors=1000

**Comment by iainmcgin** [comment]
Thanks for investigating!

**Comment by DevVersion** [comment]
No problem, it seems like your minified `core` modules is not valid. Can you point me to the current state of your issue?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (407/400 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:47321 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmLf-000aXH-E6
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:37:31 +0100
Date: Mon, 14 Mar 2016 11:10:48 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457979048;
	bh=6mbiDJPphU+qa+WIWndByb0vjWj3b8leLvxT1zEV5hg=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Mu6bH+f2pRipDcDvXmqVsqe1KVS1fwDgwYTOyLfSzviSNe8c+ZnDDKilJkU2EJ4GE
	 YJwFQog8gorcDwzZ2C3lUIOt817pr7cIt4DsS5gda9l9ZStTuwePRJHVeeMhCaWN8N
	 rerDnRVp8PFLKfhf7GjYRzV+ImY6sVbHggxxX6VQ=

**Comment by iainmcgin** [comment]
I have a workaround for v1.6.0, and it looks like this will be fixed in the 1.1.0 release, so I'm happy to close this issue.
