### ISSUE TITLE
How to make md-autocomplete and JSONP request work...

### ISSUE THREAD

**Issue by OliverTr54** [angular/material#7530]
Hey folks,

I have a problem and hopefully someone is able to give me solution.

I'm currently using the md-autocomplete directive in one of my partials - and it should be filled with a JSONP repsonse from Google.

Within my partial I inserted the following:
```
<md-autocomplete
	class="searchSuggest"
	md-select-item="ytItem.value"
	md-search-text="suggestorSearchText"
	md-items="ytItem in Suggestion.getSuggestions(suggestorSearchText)"
	md-item-text="ytItem.display"
	md-delay="500">
		<span md-highlight-text="suggestorSearchText" ng-bind="ytItem.display"></span>
</md-autocomplete>
```

My controller has a scope that is just linked to a service.
`$scope.Suggestion = SuggestionService;`

And the service looks like this:
```
app.service('SuggestionService', function($q, $http) {
	var self = this;

	this.getSuggestions = function(query) {
		console.log("Trying to find suggestions for: "+query);
		
		var deferred = $q.defer();
		$http
			.jsonp('http://suggestqueries.google.com/complete/search?q='+query+'&ds=yt&client=youtube&callback=JSON_CALLBACK')
			.success( function (data) {
				var suggestions = data[1].map( function (state) {
					return {
						value: state[0].toLowerCase(),
						display: state[0]
					};
				});
				console.log(suggestions);
				deferred.resolve(suggestions);
				return deferred.promise;
			})
			.error(function() {
				deferred.reject();
				return deferred.promise;
			});
	}
});
```

So what it does currently - once you enter something, it sends the request to the service and the service is getting a result as well, but the md-autocomplete "Items" stays empty.

Does someone have a solution for this?

Thanks,
Oliver

**Comment by gpopovic** [comment]
This is just too complicated, try this one

`app.service('SuggestionService', function($q, $http) {
    var self = this;

    this.getSuggestions = function(query) {
        console.log("Trying to find suggestions for: "+query);


        var deferred = $q.defer();
        $http
            .jsonp('http://suggestqueries.google.com/complete/search?q='+query+'&ds=yt&client=youtube&callback=JSON_CALLBACK')
            .success( function (data) {
                var suggestions = data[1].map( function (state) {
                    return {
                        value: state[0].toLowerCase(),
                        display: state[0]
                    };
                });
                console.log(suggestions);
                deferred.resolve(suggestions);
                return deferred.promise;
            })
            .error(function() {
                deferred.reject();
                return deferred.promise;
            });
    }
});`

**Comment by gpopovic** [comment]
There is no need to use $q here..

`
app.service('SuggestionService', function($http) {
    var self = this;

    this.getSuggestions = function(query) {
        console.log("Trying to find suggestions for: "+query);

        return $http
            .jsonp('http://suggestqueries.google.com/complete/search?q='+query+'&ds=yt&client=youtube&callback=JSON_CALLBACK')
            .then(function(data){
                console.log(data);
                // Not sure what you want to do with this, but data you want is within data.data !!
                var suggestions = data.data[1].map( function (state) {
                    return {
                        value: state[0].toLowerCase(),
                        display: state[0]
                    };
                });
                console.log(suggestions); // Make sure suggestions are correct
                return suggestions;
            });
        
    }
});
`

**Comment by OliverTr54** [comment]
Thanks you - I haven't seen this mistake :( Anyway, it's working!
