### ISSUE TITLE
md-list-item not working in Firefox, IE11 with ui-sref

### ISSUE THREAD

**Issue by antoinebrault** [angular/material#7532]
Directive html output is wrong for Firefox, IE11.

``` html
<!-- It generates -->
<button class="md-button _md-no-style" ...>
  <a class="_md-no-style md-button" ...> 
    ..
  </a>
</button>
<!-- instead of -->
<a class="_md-no-style md-button" ...>
...
</a>
```

See (look for errors in console on click):
http://output.jsbin.com/dizuxewiba/1/

I've included a working output.

**Comment by cadilhac** [comment]
Seems like #7513

**Comment by DevVersion** [comment]
@antoinebrault That's fixed in `master` - http://jsbin.com/vijotizoya/1/edit?html,css,js,output
