### ISSUE TITLE
md-icon in span is centered and text follows

### ISSUE THREAD

**Issue by cadilhac** [angular/material#7533]
Check [this codepen](http://codepen.io/anon/pen/BKzvdb).

See the issue when there is an md-icon and a text inside a SPAN tag.
[Your doc suggests](https://material.angularjs.org/latest/api/directive/mdListItem) to use a SPAN tag in this case. When I use a P tag, this is correct.

Note: in firebug, when I remove the "margin:auto" in md-icon css, it fixes the alignment.

Checked in various browsers under Win 7 Ult x64.

**Comment by DevVersion** [comment]
Not related to the `md-list` component. It's caused by `md-icon`'s margin property.

http://codepen.io/DevVersion/pen/ZWpEpV?editors=1010

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
