### ISSUE TITLE
md-button shifts down in latest chrome (with md-progress-linear visible)

### ISSUE THREAD

**Issue by whittssg** [angular/material#7534]
Hello,

When you click an md-button (actions section of md-card) and the card has a md-progress-linear control the buttons (or the actions bar) will shift down.. It only seems to happen in Chrome - IE and Firefox are not effected.

Please see my fiddle: Click on and off the button a few times.

http://jsfiddle.net/whittssg/5n7pewgf/17/

Thanks

**Comment by david-meza** [comment]
I was not able to recreate your issue. However, after running it a few times, I noticed that the card content seemed to be shifted down by the height of the progress bar. But that should be easily fixable from your markup by replacing 

    <md-card-content style="height:100%;">
      My Content
    </md-card-content>

with

    <md-card-content flex>
      My Content
    </md-card-content>

so the card content isn't forced to take all 350px of your card, when all it needs is whatever is remaining after allocating to the toolbar, progress bar, and card actions section.

**Comment by whittssg** [comment]
Super strange.. thanks for checking - i hadnt noticed the card content moving down but now i do.. I had tested the fiddle on two different machines at work (different computers with the same monitors) and i could reproduce it - now that i am at home on my much smaller screen i cant seem to reproduce it.. Please close this out for now and when i get back to work on monday i will check again. Thanks

**Comment by whittssg** [comment]
All good with the flex instead of height=100%. Thanks
