### ISSUE TITLE
Allow duplicate md-option values in a select.

### ISSUE THREAD

**Issue by JDGoldman** [angular/material#7536]
Presently, duplicate md-option values are not allowed in an md-select (line 688 of src/components/select/select.js).  I have a scenario where I am populating a select list with duplicate values deliberately, and I would like to have an option to allow duplicate values if we specifically want them without an error being thrown.  Perhaps a new attribute on the md-select directive?

**Comment by david-meza** [comment]
This would go against the design specs of the component as can be seen here: https://www.google.com/design/spec/components/menus.html#menus-behavior

**Comment by JDGoldman** [comment]
Obviously, don't want to go against the design spec (by the way, your link seems to point to something else), but all I am talking about is a way to suppress the error message so my console (and the user's console) isn't littered with unnecessary messages.

**Comment by Nextt1** [comment]
I think value works like a id here. so It needs to be unique and as long its unique you can select that item.

**Comment by david-meza** [comment]
The link was right. This part, in particular, is what I was referring to:

![2016-03-12_16-02-37](https://cloud.githubusercontent.com/assets/11840636/13725343/a48521b4-e86c-11e5-8de9-69acd5db34a3.png)

Have you considered using a `md-optgroup` label for broader categories?

**Comment by JDGoldman** [comment]
Thank you for the link, and the photo.  I did find it finally.  It is not really applicable because what shows up for the user is, for example, Vests on the one hand, and Tops --> Vests on the other hand.  I don't want to use an option group because the idea is we have about 100 categories and sub-categories and somebody may be looking for Vests and not realize that the Vests are actually a sub-category of Tops.  Tops and Vests appear about 20 items in the list apart from each other so a user may not see them together, hence the need to make it easier for my users to find the categories they want (and the duplicate values).  The md-select works fine, it just emits an error because of the duplicate Ids.  I want to suppress the error.

**Comment by topherfangio** [comment]
In general, I agree that each id should be unique. We will leave this open, but with a low priority. If it gets enough votes, we will consider adding it.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by amritk** [comment]
+1
