### ISSUE TITLE
sideNav: auto-disable backdrop when is-locked-open == true.

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#7537]

**Comment by DevVersion** [comment]
@ThomasBurleson The backdrop isn't enabled / added to DOM, when `is-locked-open` is set to true. You can confirm that in the latest docs. 

So I'll treat this as a performance update.

**Comment by DevVersion** [comment]
@ThomasBurleson - If evaled `md-is-locked-open` is `false` and the sidenav is open.

```js
document.body.querySelectorAll('md-backdrop').length // === 1;
```


If evaled `md-is-locked-open` is `true` and the sidenav is open (through the locked open).
```js
document.body.querySelectorAll('md-backdrop').length // === 0;
```

Already talked with @ErinCoughlan about that and we figured out, that the disabled animations are responsible for this bug.

So as conclusion, we can say that the backdrop is probably disabled when `md-is-locked-open === true`. 

About the disabled animations, that maybe another issue. Can you close the issue if you understood my thoughts.
