### ISSUE TITLE
md-datepicker-- md-scroll-mask remains open on navigation back

### ISSUE THREAD

**Issue by j2m6lz5n** [angular/material#7542]
If you open the md-datepicker that is on a secondary route in the app and then hit the back button while the datepicker is still open, the scroll mask remains open and preventing scroll until the user clicks.

**Comment by DevVersion** [comment]
@j2m6lz5n Can you provide a demo of your issue?

**Comment by j2m6lz5n** [comment]
Hi DevVersion,
Thanks for looking into this...Its not the worst issue in the world, but I thought Id mention it. I assume that there is something that could be added onRouteChange. Please let me know.
Here is a quick example codepen of what I am talking about. When you open the page, you can scroll...if you go to the next page, open the datepicker, then hit the back button without selecting the date, then you will not be able to scroll until you click once.

http://codepen.io/j2nm6lz5n/pen/dMpyxW?editors=1111

Again, I know that this is a really minor issue, but I figure if you or someone can fix it easily, itll make the project just ever so slightly more user friendly. Thanks again for looking into it

**Comment by j2m6lz5n** [comment]
Thank you @DevVersion
