### ISSUE TITLE
md-menu closing on any outside click

### ISSUE THREAD

**Issue by Bassel-m** [angular/material#7543]
I am trying to make a menu but letting the user open another menu if clicked on it without having to close the first, first.
So if the user clicked another menu, that click closes the first and opens the second
How to change the default behaviour?!

**Comment by Nextt1** [comment]
[md-menu behaviour in Angular Material](http://stackoverflow.com/questions/35959169/md-menu-behaviour-in-angular-material/35960200). Its working now.

**Comment by Bassel-m** [comment]
Yeah but I noticed something in that codepen, when I click on an empty area on the toolbar the menu doesn't close, it only close when clicking on white areas

**Comment by Nextt1** [comment]
It is a bug I guess. It should close.

**Comment by Bassel-m** [comment]
@DevVersion Can you see this?

**Comment by DevVersion** [comment]
@Bassel-m Yes. Investigated a bit and found the problem. The backdrop has a lower z-index as the toolbar. That's why the menu isn't closing.

**Comment by Bassel-m** [comment]
Yes but if you increase the z-index of the backdrop the menu behaviour changes hovering doesn't open the  other menus :/

**Comment by DevVersion** [comment]
Since we need to be careful about changing the z-index, I marked this to require a team discussion.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
