### ISSUE TITLE
Md-max-chips doesn't work with autocomplete

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7549]
Md-max-chips works with only input, but doesn't work when autocomplete is used with chips.

On codepen, ,d-max-chips is set to 1 on both autocomplete and input.
Chips with input will not allow adding another chip, while autocomplete will just ignore that tag.
http://codepen.io/anon/pen/GZjrQE

**Comment by DevVersion** [comment]
@gpopovic Thanks for catching this :+1:
