### ISSUE TITLE
Text disappears in md-list-item if background-color is set

### ISSUE THREAD

**Issue by Millen31** [angular/material#7551]
Hi,
if you want to set a background-color in a md-list-item (with ng-click), the text inside the list-item disappears.

http://codepen.io/anon/pen/dMpWpQ

Best Regards
Frank

**Comment by DevVersion** [comment]
Thanks, that's already fixed in #7531.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (433/400 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:58284 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNQ-000avP-Te
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:39:08 +0100
Date: Mon, 14 Mar 2016 10:00:50 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457974850;
	bh=Q05Ssd9qoW5Pf8Y54Gg/KKVI8wg2ydG6/52gbySaH2I=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=vtPMffkP/ay8EV9/PbFpPl+WyLjPCMDevQONz2meJiEyc/cjOXvG3Vk4viSwwd1Of
	 L6RT/QmFfQq9TKtHLBtiKkadtdleIcmphk4QC/4tXga22+75mKcefGn/aCYZiABX4n
	 nmugs3tYGwL+OPQjhdrPhUbxoD42eTmxk+UlwNY8=
