### ISSUE TITLE
md-list: .md-dense - wrong font-size

### ISSUE THREAD

**Issue by ivoviz** [angular/material#7552]
`md-list.md-dense` has wrong font-size set. According to the spec it should be 13px, but it actually goes up to ~21px.

Demo [here](http://codepen.io/anon/pen/JXRyNW).

Note that the official demo has some additional css added (`html: font-size: 62.5%;`) which makes it look good there.

**Comment by DevVersion** [comment]
I guess you're using IE11?

**Comment by elekzalan** [comment]
I had the same problem. By default the `<h3>` font-size of `md-list.md-dense` is set to 1.3rem, which is relative to the root element `<html>`. Thus you have to specify the font size of the root element.

If you set it as `html: font-size: 62.5%;`, the 1.3rem is going to be like ~13px.
