### ISSUE TITLE
md-select: Document md-optgroup

### ISSUE THREAD

**Issue by epelc** [angular/material#7554]
Currently `md-optgroup` for `md-select` only has an example [here](https://material.angularjs.org/latest/demo/select). It should have a page listing the attributes and what they do(currently only `label`) like the other directives.

It's also not mentioned on the `md-select` api page while `md-option` is.

https://material.angularjs.org/latest/api/directive/mdSelect

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by thetomja** [comment]
How not to manage a project 101.
