### ISSUE TITLE
md-dialog stays on top even if state changes

### ISSUE THREAD

**Issue by jayeshanandani** [angular/material#7555]
Hi,
  I am using UI router with Angular Material v1.0.5. When we open custom dialog, we have configured it to get attached to the parent body. Now if anyone hits browser back button the state changes but dialog stays floating on top as it falls outside ui-view tag. Is there a way to mitigate this? I saw on the demo site, don't know what has been done since there also dialog is outside ng-view but when we hit back it goes away.

Is there a way we can solve this for UI router as well?

**Comment by corentin-gautier** [comment]
You should try calling the $mdDialog hide method on a $stateChangeSuccess listener :)

**Comment by jayeshanandani** [comment]
@corentin-gautier : Yeah that is what I did. Thanks. :+1:
