### ISSUE TITLE
Hyperlink style changed

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7556]
Hyperlink style is changed in master

master
http://codepen.io/anon/pen/dMpeOz

v1.0.6. (and before ...)
http://codepen.io/anon/pen/vGXjyp

**Comment by DevVersion** [comment]
Introduced in #7472 

![image](https://cloud.githubusercontent.com/assets/4987015/13746512/11213dde-e9f4-11e5-8bbd-171a46dd8649.png)

**Comment by ThomasBurleson** [comment]
Changed is based on Material Design specifications.
