### ISSUE TITLE
Padding on item-list with ng-click wrong on ie 11

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7557]
On ie11, padding is wrong ...
![ebb2b408-af11-4f9f-a786-99b293c3e12f](https://cloud.githubusercontent.com/assets/2094147/13743979/5601ff10-e9e5-11e5-82a9-27eee55c1232.png)

**Comment by DevVersion** [comment]
Provide a demo, and check within `master`. In addition to that try confirming with #7531

**Comment by gpopovic** [comment]
@DevVersion check in IE11

http://codepen.io/anon/pen/ZWpwRa

**Comment by DevVersion** [comment]
Seems like the vertical alignment for the `md-list-item-inner` div isn't working probably on IE11

IE11:
![image](https://cloud.githubusercontent.com/assets/4987015/13752513/5acdd58a-ea0f-11e5-942a-46996bd8077e.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/4987015/13752520/623b8196-ea0f-11e5-8291-0317db82c364.png)

**Comment by gpopovic** [comment]
Ok, so this actually isn't fixed.

It works well on IE 11 Version 11.162.10586.0 (on Windows 10)
but it doesn't work on IE 11.0.9600 Version (on Windows 7)

@DevVersion sorry man :D I know this must be frustrating

**Comment by DevVersion** [comment]
Damn... :smile: I thought now everything is great with the list component. Can you post a screenshot of the Dom Inspection / Preview Output etc. So I can confirm, that the bug is still present?

**Comment by gpopovic** [comment]
![work](https://cloud.githubusercontent.com/assets/2094147/13872481/3ed9bafe-eceb-11e5-88ba-a59d085c74cd.png)

Please note, it works on IE11 on Win 10.

This is the picture on IE11 Windows 7.
I'm having some problems with IE on home computer, so i can't check dom..i'll send you one in few days(I checked on multiple win7 computes on IE 11, always the same error)
