### ISSUE TITLE
demo: toolbar demos aren't responsive

### ISSUE THREAD

**Issue by DevVersion** [angular/material#7558]
The toolbar demos look really weird on a mobile device.

![image](https://cloud.githubusercontent.com/assets/4987015/13747308/e87e8bf8-e9f7-11e5-9fb5-a3f6639db511.png)

**Comment by DevVersion** [comment]
In case of having toolbars with really long texts, we should disable text-wrapping generally in toolbars.
Additionally for the demos: we need to shrink the text content there.

`favorite` icon related to #7599 (with button)

What do you think? @EladBezalel

**Comment by EladBezalel** [comment]
https://css-tricks.com/rem-global-em-local
http://zellwk.com/blog/viewport-based-typography/

Might be the best solution

**Comment by DevVersion** [comment]
I don't think that's the best behavior for the toolbar, since the toolbar is not shrinking vertically on viewport changes. This will cause the text to be completely unreadable.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
