### ISSUE TITLE
mdSelect: md-accent from mdInputContainer not applied

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#7559]
Took a quick look for an issue open already, but didn't spot one.  An md-accent class given to a parent md-input-container is not passed down to the child md-select.  This can produce some pretty inconsistent / gross visuals.  

I expected the md-accent to be applied to the internal md-select.  To get the correct output, md-accent has to be set on both input-container and element.  This seems slightly inconsistent with elements and behaviour like input and textarea.

Browser and OS: Opera 35 / Chrome 48

Reproduce the error: http://codepen.io/mckenzielong/pen/BKLMmN - select a state.  The underline and label will be two different colours.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
