### ISSUE TITLE
1.1.0-RC1 - Clickable md-list-item broken on FireFox 44/45

### ISSUE THREAD

**Issue by IsNull** [angular/material#7561]
I just tried the latest version 1.1.0-RC1 and the md-list-items primary action is completely broken (there is no hover effect, and the items are not clickable)

You can test it with the current FireFox on https://material.angularjs.org/latest/demo/list

Tested with FF 44 on OSX and FF 45 Windows 10.
The problem does not occur with other tested Browsers (Chrome, Edge, Safari)

**Comment by gpopovic** [comment]
This is fixed in master

**Comment by IsNull** [comment]
Ah thanks for the hint, its working on `#master`. Closing now.
