### ISSUE TITLE
Angular Material Animations Inconsistent behavior between IE and non IE browsers

### ISSUE THREAD

**Issue by kumar99m** [angular/material#7563]
Hi,

I am trying to use angular material Dialog in my project and found that animations are not smooth in IE also inconsistent in IE and non IE browsers(Chrome and FF), below is the example, when you click on dialog's you can observer the different animations in IE and non IE browsers.

https://material.angularjs.org/latest/demo/dialog

You can find lot of scenarios in the Angular Material demos it self, You can observe animations works smooth and consistent in Chrome and FF but Animations are not smooth and consistent in IE11 or IE10

**Comment by topherfangio** [comment]
We do not currently support IE10, only IE11.

If you notice any issues (like the dialog one above), could you please open specific issues for each one detailing the problem for that component? In the case of the dialog, I actually think it's a positioning issue unrelated to the animations.

It may also be related to some performance issues which we are also working to address.
