### ISSUE TITLE
Button ripple effect doesn't work smoothly

### ISSUE THREAD

**Issue by Millen31** [angular/material#7565]
Hi,
it seems like that the ripple effect on a button is affected by the content that is loaded. You can check it on the Angular-Material Page. If you press a button to open some submenus, everything is working fine, If you press a Button to change the content it's pretty laggy. Especially there is a lot of stuff to load. 

First I thought the problems caused by my routing framework UI-Router but it seems to be a problem in general. 

Thanks!

**Comment by topherfangio** [comment]
Duplicate of #6738.
