### ISSUE TITLE
mdSlider: can not drag slider while scrolling bar is visible (positionToPercent)

### ISSUE THREAD

**Issue by soooooot** [angular/material#7569]
You can check on [CodePen](http://codepen.io/anon/pen/WwoRzd).

I'm using the vertical slider. (And I think horizontal slider has the issue too)
When the scrolling bar is visible, the thumb icon always go to bottom and the value is the min number.
I have to drag higher to leave a offset of scrollTop so that the thumb icon can move.

my environment: 
OS X  10.11.1 (15B42)
Google Chrome Version 48.0.2564.116 (64-bit)

I think the issue is about to `positionToPercent` function in `md-slider.js`.
```js
    function positionToPercent( position ) {
      var offset = vertical ? sliderDimensions.top : sliderDimensions.left;
      var size = vertical ? sliderDimensions.height : sliderDimensions.width;
      var calc = (position - offset) / size;
      return Math.max(0, Math.min(1, vertical ? 1 - calc : calc));
    }
```

`position`:  ev.pointer.y,  the offset to **page**.
`offset`:  offset to **viewport**.

sliderDimensions is retrieved by `sliderDimensions = trackContainer[0].getBoundingClientRect();`, and according to [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect), the `top` value is the offset to viewport.

Here's my solution, it works for me, but it's NOT fully tested. 
And I don't know is it the right way to fix that.

```js
    function positionToPercent( position ) {
      var offset = vertical ? sliderDimensions.top : sliderDimensions.left;
      var size = vertical ? sliderDimensions.height : sliderDimensions.width;
      // minus the scrolling bar missing offset
      var calc = (position - offset - ( vertical ? document.body.scrollTop : document.body.scrollLeft)) / size;
      return Math.max(0, Math.min(1, vertical ? 1 - calc : calc));
    }
```

If the solution works, I'm very pleasant to send a PR.

**Comment by soooooot** [comment]
BTW, FYI, in the [angular material docs](https://material.angularjs.org/latest/demo/slider).
I inserted a `<section style="height: 100px;"></section>` block by inspect tool to the position before `md-content` that the `md-slider`  inside. But the issue doesn't occur in the situation. 
I can't figure out why.

**Comment by topherfangio** [comment]
Confirmed bug. @EladBezalel If you are viewing the Codepen, make sure to open the inspector to make the view small enough to force a scrollbar to appear and then try to change one of the sliders.

**Comment by EladBezalel** [comment]
@soooooot please create a PR, your solution seems legit

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
