### ISSUE TITLE
progress-circular: theming not working probably.

### ISSUE THREAD

**Issue by HBO2** [angular/material#7570]
Hi,

I have checked the master and I noticed all the theming issues are solved. Only the  md-progress-circular is stilling a little out of order by using the default blue rgb color indicating the theme is not set for the  md-progress-circular. Also the adapted size in my theme size seems to be ignored.

Thanks

**Comment by crisbeto** [comment]
I'll take a look at the theming, but what do you mean about the size? The size on the `progressCircular` will definitely be different from before since the old implementation wasn't completely accurate (e.g. if you specified 50px, it would render around 30px).

**Comment by mpiasta-ca** [comment]
I'm trying to setup *md-progress-circular* right now (using 1.0.6). When I set `md-diameter="100px"`, the width and height box on the element is 100px. But the actual spinning circle is only 50px in diameter, resulting in huge empty space around the spinning circle inside of its container.

I think 1.1.0-RC might fix it, but looks like that's still not available on bower.

**Comment by ThomasBurleson** [comment]
@mpiasta-ca - 
[1.1.0-rc1](https://github.com/angular/bower-material/tree/v1.1.0-rc1) is available on Bower
I recommend you use the latest on `bower-material/master`  with the

```console
# To get the most recent, last committed-to-master version use:
bower install angular-material#master
```
