### ISSUE TITLE
md-autocomplete marks the search term first appearence

### ISSUE THREAD

**Issue by virtser** [angular/material#7571]
Although filter actually found the second appearance of the search query, the first one was marked.

![oyarjxgmook](https://cloud.githubusercontent.com/assets/468590/13778868/da83cb98-eac0-11e5-95f6-9e4100a07708.png)

See the following example:
http://plnkr.co/edit/7Ch6VnasM3y9GIYZXsem?p=preview

**Comment by topherfangio** [comment]
@DevVersion I think this is actually an issue with the `md-highlight-directive`, not the autocomplete itself.

**Comment by topherfangio** [comment]
@virtser Quick question: are you wanting it to highlight both matches? If so, you can use `md-highlight-flags="^ig"`.

If not, can you explain a bit more by your statement:

>  filter actually found the second appearance of the search query

Based on the code in the Plunkr, the regexp looks to use the `global` flag, so I would assume it finds both.

Thanks!

**Comment by DevVersion** [comment]
@topherfangio Just wen't through this issue again. And the `highlight` directive works well, if you wan't to match all items, then you should use the `g` ( globlal ) flag as @topherfangio mentioned.

Here is the flag documentation for the directive:
- https://material.angularjs.org/HEAD/api/directive/mdHighlightText

If I missed something, please let me know, and I'll reopen.
