### ISSUE TITLE
<md-menu-item> doesn't open cascading menu on hover of second menu item

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#7574]
See [codepen](http://codepen.io/cmacdonnacha/pen/XdNEGw?editors=1000)

1. Click on File
2. Hover over "Child 1"
3. Hover over "Child 2"

**Result:** The nested menu opens when hovering over "Child 1" but not "Child 2".

I did notice that if you hover over another menu item like "Open" and then hover over "Child 2" it works fine and the nested menu opens.

**Comment by DevVersion** [comment]
Already fixed in `v1.1.0-rc1` by @topherfangio :+1: 

See your demo with the the working release.
- http://codepen.io/DevVersion/pen/LNbJPG?editors=1100

**Comment by cmacdonnacha** [comment]
@DevVersion Good stuff thanks for that :thumbsup:
