### ISSUE TITLE
List Item text clips with secondary content

### ISSUE THREAD

**Issue by gomerdoom** [angular/material#7578]
I ran into an issue with [md-list](https://material.angularjs.org/latest/demo/list), when the list item text wraps behind the secondary content. Not exactly a huge issue, can just be kinda unattractive. 

![image](https://cloud.githubusercontent.com/assets/3951600/13791319/7e40d08e-eaba-11e5-9b3e-ac65caab2e78.png)

![image](https://cloud.githubusercontent.com/assets/3951600/13791383/d979818a-eaba-11e5-974d-03996997cf28.png)

**Comment by gpopovic** [comment]
duplicate #7500

**Comment by DevVersion** [comment]
Thanks @gpopovic.
