### ISSUE TITLE
Chips with autocomplete not editable

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7580]
It is not possible to edit chips with autocomplete.

Not only that, when md-edit-chips is true, and chips are using autocomplete, when you double click on a chip, chip content gets messed.

http://codepen.io/anon/pen/EKNezZ

**Comment by DevVersion** [comment]
Ping @mertdeg2

**Comment by mertdeg2** [comment]
Sorry I couldn't try this out before. Editing functionality works only if
default chip template is being used.

I have created a PR to make sure this is the case before we enable chip
edit: https://github.com/angular/material/pull/7585

On Tue, Mar 15, 2016 at 1:28 PM, Paul Gschwendtner <notifications@github.com

**Comment by DevVersion** [comment]
@mertdeg2 Great thank you! 

Fixed with SHA 31787c055b60fa0acf043417753003d7ec464db4

Demo with the new fix:  http://codepen.io/DevVersion/pen/yOgNRg
