### ISSUE TITLE
md-tab how to active and focus tab  from my controller function call

### ISSUE THREAD

**Issue by bhandaribhumin** [angular/material#7581]
From my nav menu I want to active and focus perticular tab how can i do it ? 
Anyone pleas give me example for active tab from my nav view 
Also tab is dynamic and menu item list same as tab list

**Comment by topherfangio** [comment]
Please post this on the [forums](https://groups.google.com/forum/#!forum/ngmaterial).

**Comment by bhandaribhumin** [comment]
please let me know if you know i want to share issued https://drive.google.com/file/d/0B0qdA1kUoM_hUTdUT3NCd2ltRTg/view?usp=sharing

**Comment by topherfangio** [comment]
@bhandaribhumin Here is a quick example that shows you how to change tabs programmatically using the `md-selected` attribute:

http://codepen.io/topherfangio/pen/wGgmLq?editors=1010

If you still have trouble; please ask on the forums as GitHub is really only for submitting bugs :smile:

**Comment by bhandaribhumin** [comment]
no not working when by default i set my md-selected="3" whichis also not working don't know what's the problem?  i am stuck please help me

**Comment by bhandaribhumin** [comment]
$scope.selectedIndex = 1; is not working while controller load 
and also not working wile i call function and change  $scope.selectedIndex = 2;
from my nav bar

nav-menu .html

 <md-list-item menu-close ng-if="catTabTitle" class="menu-list-item"  
                ng-repeat="(cat_id, categorie) in catTabTitle"
                 ng-click="getItems(cat_id,$index)">

category.html

<md-tabs md-selected="selectedIndex"  md-dynamic-height md-border-bottom="" class="material-background">

in category controller

initialise  $scope.selectedIndex = 1;

 

  $rootScope.getItems = function(cat_id,index){
                console.log('cat id');
                $scope. selectedIndex = index+2;
                $mdSidenav('left').close();
                
            
}

https://drive.google.com/file/d/0B0qdA1kUoM_hWUtPUTdrMUlzV2M/view?usp=sharing

**Comment by bhandaribhumin** [comment]
when i click on  $rootScope.getItems(), check  selectedIndex value it's seems like 

$scope.$watch('selectedIndex', function(current, old){
           console.log('current',current);
           console.log('old',old);
  });

Console output 
current 2
old 3
