### ISSUE TITLE
List Item text doesn't wrap correctly with list-item ng-click

### ISSUE THREAD

**Issue by scottrodoty** [angular/material#7584]
See the attached codepen. When list items have an ng-click on the md-list-item, there is a div styled with a class _md-list-item-inner.  This div extends beyond the right edge of its container, and so the text that is contained does not wrap correctly.

http://codepen.io/scottrodoty/pen/grLbVq

**Comment by DevVersion** [comment]
Already fixed in 91585893db8a84312b9fb2a904008ffb169e0946.

Don't wonder, the text will underlay the secondary items, that's a bug, which is already tracked.
