### ISSUE TITLE
Dynamic MD Tab won't change Chrome Extension Popup Size

### ISSUE THREAD

**Issue by rosco1502** [angular/material#7587]
The Dynamic MD Tab won't change the Popup window size in a chrome extension. Is there an event that fires when the tab is changed with the tab height so I can manually do this? To change a chrome extension popup size, just set the height using CSS on the HTML and BODY element.

P.S. This might be a feature request as this functionality may not be intended.

**Comment by topherfangio** [comment]
Can you explain a bit more what you're needing or perhaps provide a Codepen? I realize that may be difficult if it's only for a Chrome extension, but it would be helpful if we better understood the problem.

Some pictures of the issue would also be helpful.

**Comment by rosco1502** [comment]
@topherfangio I seemed to have fixed the issue, but only by forcing some custom css to override Angular's. 
`body, html {`
`  height: 0 !important;`
`  min-height: 0 !important;`
`}`
A chrome extension popup will adapt its size based on its content. In the given popup one tab has less content than the other. The chrome popup will adjust to the tallest content and go back down to the shorter height when viewing the tab with less content. However Angular is putting out a minimum height of 100%. So when it is introduced to the taller content and then switched back it will not go down as it requires 100% height, while the chrome popup is trying to set a height smaller then that (for example 80%). Hopefully this makes sense as it was a bit hard to word properly.
[The culprit](https://gyazo.com/1189b24d4612306aa1e6b1bbf5a16155)

**Comment by topherfangio** [comment]
I'm glad you got it fixed. Honestly, I'm not sure there is much we can do in the 1.x series since that has been defined that way for so long and changing it would affect pretty much every app out there.
