### ISSUE TITLE
MD Toast positioning issue when using layout-align="center center"

### ISSUE THREAD

**Issue by rosco1502** [angular/material#7588]
When you use layout-align="center center" a toast will always appear on the bottom, fully stretched.
[Screenshot](https://gyazo.com/64afc64475e9889d5386a925e4705cff)

**Comment by DevVersion** [comment]
This is by intention, we always show the toast at the bottom, when your screen is matching the `sm`-breakpoint.

We documented that recently: https://material.angularjs.org/HEAD/api/service/$mdToast
