### ISSUE TITLE
$mdDialog, $mdBottomSheet inheritance

### ISSUE THREAD

**Issue by jpolo** [angular/material#7589]
Hi,

I could not find a nice way (= fluent api using interimElement) to create new dialog factory.

Here is the result that I want : (just like alert, prompt, etc)
```javascript
var dialogInstance = $myDialogFactory
  .myDialog() // my custom preset like .alert(), .confirm()
  .myParameter("blah") //my custom parameter
  .clickToClose(true)  //inherited from the default settings
  .targetEvent(...) //inherited from the default settings

$mdDialog.show(dialogInstance);
```

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
