### ISSUE TITLE
[DOCS] mdCheckbox example with ngModel = true, doesn't show as checked

### ISSUE THREAD

**Issue by Phr33d0m** [angular/material#7590]
Hi,

As you can see in the [official demo](https://material.angularjs.org/latest/demo/checkbox) the first example ```$scope.data.cb1 = true;``` should set the checkbox to checked but it doesn't. This seems to affect only the docs version of it as locally it works as expected.

Regards.

**Comment by topherfangio** [comment]
Very interesting. Note that it also works fine if you click the link to open in a Codepen. My first guess would be that the name of the module is somehow breaking it.

**Comment by DevVersion** [comment]
@topherfangio Found the bug, after completely investigating at the docs demo source :smile: and the problem is, that we registered the same module twice.

**Comment by topherfangio** [comment]
Yup, I figured it would be something along those lines :smile:
