### ISSUE TITLE
md-chips with autocomplete input too small

### ISSUE THREAD

**Issue by uriva** [angular/material#7591]
md-chips with autocomplete input doesn't expand, users can't see what they typed
Screenshot: http://s14.postimg.org/jagdrlnht/image.png

**Comment by topherfangio** [comment]
Related to #4450. Right now the best workaround is to simply increase the inner input's width via CSS if your chips have longer text.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
