### ISSUE TITLE
md-dialog controller can't see dialogs DOM

### ISSUE THREAD

**Issue by vrghost242** [angular/material#7592]
Have a similar issue. In my case I am trying to open a dialog to display a reveal.js presentation. Problem is that reveal.js wants to find two ids in the dom (.reveal and .slides). Tried to load the slides into a dialog (works) then initiate reveal.js from the controller. However, it failse because it can't access the modals DOM, it runs on the top project. So is there a way to "connect" the modals dom to the contoller. Think this issue is similar to 
https://github.com/angular/material/issues/5368

In my example, all I do is (in controller):
````
app.controller('displayRevealController', function($scope, $http, $mdDialog){
    console.log("I am so initialising")
    Reveal.initialize({
        controls: true,
        progress: true,
        history: true,
        center: true,


        transition: 'slide', // none/fade/slide/convex/concave/zoom
        // Optional reveal.js plugins
    });
    Reveal.addEventListener('ready', function (event) {
        console.log("I have now entered " + event.currentSlide)
        // event.currentSlide, event.indexh, event.indexv
    });


});
````

The code (or first code) in reveal.js that fails  (my debug comments) is 
		console.log("Accessing the slides")
		dom.wrapper = document.querySelector( '.reveal' );
		//dom.wrapper = document.querySelector( '.modalModal' ); //(Tried to see what it could see and not)
		console.log("This is wrapper " + dom.wrapper)
		//dom.wrapper = angular.element(element[0].querySelector('.reveal'));
		dom.slides = document.querySelector( '.reveal .slides' );

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
