### ISSUE TITLE
Bootstrap-style Alerts

### ISSUE THREAD

**Issue by patorjk** [angular/material#7593]
Bootstrap has a set of alert classes for giving contextual feedback. You can see them here:

http://getbootstrap.com/components/#alerts

These can be useful when providing information to users, highlighting important points, or writing documentation. The Angular Docs even use them:

https://docs.angularjs.org/guide/concepts#directive

The closest thing I could find in Material is md-whiteframe. You can create Material-like alerts by doing the following:

```
<div layout="row" layout-padding layout-wrap layout-fill>
    <div md-whiteframe="3" class="padded">
        Some text here
    </div>
</div>
```

However, md-whiteframe doesn't work with md-warn. I understand this since the name implies white, but I think it would be useful to have a standard way of creating these types of boxed messages in the Material-style.

**Comment by ThomasBurleson** [comment]
Invalid or not core focus for Material 1.
