### ISSUE TITLE
md-date-picker: disable all dates before today's date

### ISSUE THREAD

**Issue by sunil-ideas2it** [angular/material#7607]
Right now we dont have any option to disable the dates which are before today's date. I want to disable all those dates which are occuring before current date . So that user is not allowed to select date less than today's date

**Comment by sunil-ideas2it** [comment]
I got this thing i am using older version of angular material 0.11.4 in that date picker dont have this functionality fully developed . I have updated my angular-material version and things started working.

**Comment by corentin-gautier** [comment]
How about md-min-date ? ( [here]( https://material.angularjs.org/latest/api/directive/mdDatepicker ) )
