### ISSUE TITLE
Many injected functions don't have @ngInject

### ISSUE THREAD

**Issue by mhansen** [angular/material#7610]
A lot of functions that have injected services are annotated with @ngInject, but a lot aren't.

Closure compiler renames function arguments, so you need to add @ngInject to these for them to work after compilation.

**Comment by topherfangio** [comment]
@crisbeto Can you take a look at this one and see how much work is required to do this?

**Comment by crisbeto** [comment]
Sure. Also would be a good chance to make them all consistent (we have some that are in the doc strings and apparently that shows a warning).

**Comment by topherfangio** [comment]
Awesome, thanks!

**Comment by mhansen** [comment]
Has that fix been tested by running it thru the closure compiler? I thought
the closure compiler only interpreted jsdoc annotations - starting with two
stars (/** */), though I may be wrong on this.

**Comment by crisbeto** [comment]
I think your changes got merged. We determined that the changes I did in #7744 aren't necessary.
