### ISSUE TITLE
Height of md-card to small on Safari

### ISSUE THREAD

**Issue by daB0bby** [angular/material#7614]
The height of `md-card` is not big enough so the `md-card-actions` aren't completely within the `md-card`.

This occurs on `Safari` for OS X and iOS.

![screen shot 2016-03-17 at 10 37 00](https://cloud.githubusercontent.com/assets/9976654/13842078/a028aadc-ec2c-11e5-9998-566cc37d9ac0.png)
![untitled](https://cloud.githubusercontent.com/assets/9976654/13842116/c6df716a-ec2c-11e5-95a4-62b58373ca5c.png)

The code:

```html
<md-card>
  <md-card-title>
    <md-card-title-text><span class="md-headline">Card</span><span class="md-subhead">Large</span></md-card-title-text>
  </md-card-title>
  <md-card-content>
    <p>
      The titles of Washed Out's breakthrough song and the first single from Paracosm share the
      two most important words in Ernest Greene's musical language: feel it. It's a simple request, as well...
    </p>
  </md-card-content>
  <md-card-actions layout="row" layout-align="end center">
    <md-button>Action 1</md-button>
    <md-button>Action 2</md-button>
  </md-card-actions>
</md-card>
```

**Comment by topherfangio** [comment]
Not seeing this issue when put inside a Codepen: http://codepen.io/topherfangio/pen/eZgrJx

What version of Material are you using?

**Comment by daB0bby** [comment]
I am using `1.0.6`.

If I open your Codepan, everything looks fine...

So maybe there's a problem with my layout.

**Comment by topherfangio** [comment]
@daB0bby Can you fork and update the above Codepen with some more of your code and reproduce it?

**Comment by daB0bby** [comment]
it was my own fault. i was overriding some styles.

**Comment by topherfangio** [comment]
@daB0bby Thanks for updating us and closing out the issue! :+1:
