### ISSUE TITLE
Roadmap and milestones

### ISSUE THREAD

**Issue by kschwidder** [angular/material#7615]
Dear all,
Angular Material has progressed so well so far !
Over the last couple of Weeks i am struggeling with the defined milestones.
Could you please provide some dates when the defined milestone should be
available. Why do you create fine grained milestones and suddenly Release a candidate with a next
Release stamp?

Thx for clarification !

**Comment by DevVersion** [comment]
@kschwidder Yes I agree with you. Also related to #6787

**Comment by ThomasBurleson** [comment]
We are refining our process to balance resource loads for ngMaterial 1 and ngMaterial 2 teams.
