### ISSUE TITLE
docs: API Reference select dropdown assumes all directives are elements

### ISSUE THREAD

**Issue by epelc** [angular/material#7620]
The `API Reference` select dropdown assumes that all directives work as elements when some are only available as attributes. See how all directives are within `<` and `>`.

![image](https://cloud.githubusercontent.com/assets/5204642/13850678/5d98d07a-ec31-11e5-8486-aeebd833de8e.png)
Page above https://material.angularjs.org/latest/demo/input

The `md-select-on-focus` directive is restricted to an attribute. See restrict line [here](https://github.com/angular/material/blob/master/src/components/input/input.js#L624).

**Comment by DevVersion** [comment]
Indeed, I can see the problem. Maybe we should consider the `@restrict` annotation.

https://github.com/angular/material/blob/master/src/components/input/input.js#L593

@topherfangio Please take a look as well.

**Comment by topherfangio** [comment]
Working on a fix, but it looks like Dgeni might not pass us the data we need. Will work with them to find a solution.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by topherfangio** [comment]
Re-opening because dgeni pushed necessary changes and we have a fix.
