### ISSUE TITLE
md-tab-body does not layout-fill or flex to the bottom

### ISSUE THREAD

**Issue by WDShannon** [angular/material#7621]
I am testing this in IE 11:

[Codepen](http://codepen.io/wdshannon/pen/grgXRa)

I am attempting to have the md-tab-body of my md-tabs control flex to the bottom of the page. I have had to include this css rule to get that somewhat working:

```
#tab-content-0 > div, #tab-content-1 > div, #tab-content-2 > div, #tab-content-3 > div {
  height: 100%;
}
```
If you look at the codepen above, you will see that I get a scroll bar when I do so. What am I doing wrong? I want the tab content to flex to the bottom of the page, the first interior container to just take up however much space it needs and the second interior container to flex to the bottom of the tab content, and if it needs more space, it should have a scrollbar inside.

How do I accomplish this? I think the issue has something to do with the CSS rule above, but I cannot get it to flex at all without it.

Is this an issue with md-tab or am I doing something incorrectly?

**Comment by topherfangio** [comment]
Looks like you found the answer: http://stackoverflow.com/questions/36066358/tab-content-not-flexing-correctly

**Comment by SnehaShreshtha** [comment]
Facing the same issue in "version": "2.0.0-beta.10".
