### ISSUE TITLE
how to fetch the data from json to custom dialog box of angular material.

### ISSUE THREAD

**Issue by thilakWD** [angular/material#7628]
I am able to fetch the data to normal view. but i am not able to fetch into custom dialog of angular material.
ex: if i have the data like this
`  $scope.users = [{
    _id:1,
    firstName: 'Obi-Wan',
    lastName: 'Kenobi'
  }, {
    _id:2,
    firstName: 'Boba',
    lastName: 'Fett'
  }, {
    _id:3,
    firstName: 'Han',
    lastName: 'Solo'
  }];`
i am trying to fetch _id into custom dialog.
please check the [plunker] (http://plnkr.co/edit/rETeNlIMbutvfN4ZRKZR?p=preview) ,
 i am not able to fetch the id inside template as well as in console. 
 i know, i've done some mistake here. but i am not able to find it out.can anyone  help me

**Comment by Nextt1** [comment]
http://plnkr.co/edit/ftMGUOseru5dXcFqUYsG.

**Comment by thilakWD** [comment]
Thank you so much for your time and help

**Comment by Nextt1** [comment]
No Problem at all.. :)
