### ISSUE TITLE
Vertical Alignment on IE 11 with ng-click still not fixed

### ISSUE THREAD

**Issue by gpopovic** [angular/material#7629]
Padding on IE 11 on Win 7, still not fixed.

Everything works fine on IE11 on Win 10.

More data #7557 

@DevVersion lets continue here

**Comment by gpopovic** [comment]
![goran](https://cloud.githubusercontent.com/assets/2094147/13914568/6ae3dcae-ef4f-11e5-9c39-1e546c898cdf.png)

@DevVersion dom

**Comment by DevVersion** [comment]
@gpopovic Thanks for the screenshot, but can you please use `HEAD` for the DOM screenshot?

Like so:
![image](https://cloud.githubusercontent.com/assets/4987015/13914684/47a35d22-ef50-11e5-9bd2-c66f26fffd93.png)

Thanks in advance :)

**Comment by gpopovic** [comment]
@DevVersion sorry, forgot clicking head

![goran 2](https://cloud.githubusercontent.com/assets/2094147/13914864/829df63e-ef51-11e5-9704-c36bc9282b8c.png)

**Comment by gpopovic** [comment]
@DevVersion is last screenshot ok?

**Comment by DevVersion** [comment]
Yes, perfect - thanks!

**Comment by DevVersion** [comment]
Hey @gpopovic, just wanted to let you know, that I finally got time to work on that issue. It was in my queue, but there were other issues, which had a higher priority, so sorry for the late response.

A PR to fix that issue is now pending

**Comment by gpopovic** [comment]
@DevVersion thanks!!! i'm currently on a vacation so i cant test it right now..Looking forward to it getting to master
