### ISSUE TITLE
md-card + flexbox + IE11 rendering problems

### ISSUE THREAD

**Issue by char0n** [angular/material#7633]
**What is the current behavior?**

In IE11 md-cards are rendered incorrectly and the flex layout is messed up.

**What is the expected behavior?**

md-cards should be rendered the same way there are rendered in Chrome or Firefox

**What is the motivation / use case for changing the behavior?**

My motivation was to display users in company in responsive flex card grid.

**Which versions of Angular, and which browser / OS are affected by this issue? Did this work in previous versions of Angular? Please also test with the latest stable and snapshot (https://code.angularjs.org/snapshot/) versions.**

OS: Windows 8.1
Browser: IE 11.0.9600.18231
Screen resolution: 1920x1200
Angular 1.5.0
Angular Material: 1.1.0-rc1

**Steps to reproduce**

1.) Open http://plnkr.co/edit/TiszDmbbKRiKxPsQ2Ev0?p=preview
2.) Launch the plunker in separate window: [show image](http://pasteboard.co/2mdR1crI.png)
3.) Resize the separated plunker window to max & hit F5: 

This is the [result](http://pasteboard.co/2mdS5SGv.png)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by char0n** [comment]
@ThomasBurleson is there a particular reason why this sort of issue should be dealt with on forum instead of github issues ?

Thanks for the answer

**Comment by ThomasBurleson** [comment]
@char0n - I completely misread your issue. Your issue initially appeared to be a list of questions; instead your issue was providing a well-structured details.  

> Thank you for the followup and correction. And **thank you** for such a nice breakdown.

**Comment by char0n** [comment]
@ThomasBurleson no problem.  I was just trying to follow-up angular.js issue reporting (https://github.com/angular/angular.js/issues/new).

**Comment by AtahAhmed** [comment]
I am working on fully fledge Angular Project but running into Browser compatibility issue, My Website work fine in Chrome but breaks completely in IE11.

Angular-js version : 1.4.7
IE : 11 
OS 8.1
Angular Material - v1.0.0-rc1,

It's look's like IE has problem with 'height:auto' which caused the styles to messed up. I have gone through following link, but didn't achieve what i was looking for.

http://stackoverflow.com/questions/27132864/how-to-get-angular-material-designs-md-card-directive-to-scale-to-image-prope

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
