### ISSUE TITLE
md-autocomplete blocks user interacton on next screen if md-selected-item-change does a route change

### ISSUE THREAD

**Issue by colmben** [angular/material#7634]
If the md-selected-item-change function for an md-autocomplete does a route change (either an ngRoute $location.path= or a ui-router change of state) then there is a full screen md-scroll-mask left over the new route which blocks all user interaction on the new screen.
See example code pen, cobbled together from the autocomplete demo codepen and an ngRoute codepen. When you change to the book route and select any state, the md-selected-item-change function changes route to /main but the autocomplete leaves its md-scroll-mask on the screen blocking any further user interaction.

http://codepen.io/colmb/pen/LNxMQZ

**Comment by colmben** [comment]
Sorry, Its look like this is a dupe of https://github.com/angular/material/issues/3287

**Comment by vshanbha** [comment]
@colmben I see you have referenced #3287 here. However #3287 seems to be closed and a lot of comments there are about the issue that you have detailed indicating that likely it is a separate issue. There are comments there citing this issue even in release 1.0.6. I see that the codepen uses the release candidate (1.1.0 RC1) meaning that the problem still exists and therefore I think it merits being considered as a separate bug. If you agree, I suggest reopening this one.

**Comment by ruihan-jia** [comment]
I looked at most of the other problems and they involve removing the md-scroll-mask. 
However even if I remove md-scroll-mask, the page is still unscrollable. 
So my work around was to wait 0.1 seconds after md-selected-item-change so that autocomplete would close the drop down and remove md-scroll-mask before route change.
