### ISSUE TITLE
md-autocomplete md-not-found container displayes above $mdDialog 

### ISSUE THREAD

**Issue by qorsmond** [angular/material#7637]
When clicking on the link on the md-not-found container to display a dialog, the md-not-found container is displayed above the dialog:

![image](https://cloud.githubusercontent.com/assets/4716711/13884515/01719b22-ed37-11e5-89ac-8a374d6f2627.png)

Here is the [code pen](http://codepen.io/qorsmond/pen/PNWLQZ)

I tried setting the ` z-index:101 ` on the dialog because the `.md-virtual-repeat-container.md-autocomplete-suggestions-container ` has `z-index:100` but its not working.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
