### ISSUE TITLE
Md-input-container validation for email using ng-messages is not working properly

### ISSUE THREAD

**Issue by yugalbagul** [angular/material#7644]
Hi,
I am trying to show multiple ng-messages for form validation having an email input field.

The validation works once for only one case , either required or invalid email. After selecting any other filed or changing the input field , the validations does not work. 

Here is a codepen depicting the issue - 

http://codepen.io/Yugal/pen/qZrBwz?editors=1000

It works good without md-input-container as seen here

http://plnkr.co/edit/?p=preview

Is this an issue??

**Comment by DevVersion** [comment]
Not an issue, which is related to Angular Material.

See simple email validation using plain ngMessages.
- http://codepen.io/DevVersion/pen/LNWNpy

In this case, I suggest using a pattern, like in the demos.
```js
ng-pattern="/^.+@.+\..+$/"
```

I will close this issue, because it's not related to ngMaterial.

**Comment by yugalbagul** [comment]
Hi @DevVersion 

Unfortunately after using ng-pattern as well the issue persists.

Update Codepen - 
http://codepen.io/Yugal/pen/qZrBwz/?editors=1000


I have added file "Email3" which is without <md-input-contained>. Which works fine.

Filed "Email2" is having ng-pattern validation. For this the form validation only works once.

I think the issue is with <md-input-container>..

**Comment by yugalbagul** [comment]
Can this issue be re-opened if its is legit ??

**Comment by DevVersion** [comment]
Hey @yugalbagul,

`ng-pattern` works fine for the validation, the message is just not showing up. We already have an issue, which tracks that. #6399
