### ISSUE TITLE
Error when defining a custom theme

### ISSUE THREAD

**Issue by fmavdb** [angular/material#7645]
When I define the following theme:
`        $mdThemingProvider.theme("dark", "default")
          .primaryPalette("blue")
          .accentPalette("blue-grey")
          .backgroundPalette("blue-grey").dark();`

I get an error:
![capture](https://cloud.githubusercontent.com/assets/5363672/13899881/0734ea7e-edf9-11e5-89ae-b20a5256a1af.JPG)

The opacity attribute seems to be undefined. I know how to manually fix it by replacing an undefined opacity with the value 1.0, but that's only a temporary solution.

I'm using release 1.1.0-rc1

http://codepen.io/fmavdb/pen/xVqOJm

**Comment by EladBezalel** [comment]
Can you please provide a codepen?

**Comment by fmavdb** [comment]
http://codepen.io/fmavdb/pen/xVqOJm

**Comment by EladBezalel** [comment]
dup #7600
