### ISSUE TITLE
Space at the end of item causes incorrect dropdown result

### ISSUE THREAD

**Issue by simondevries** [angular/material#7655]
This issue occurs when the auto complete is bound to a list of items and one of the records contains a space character at the end. If the user selects the item with the space and presses the 'X' button to clear the autocomplete, the dropdown will only show that one item rather than loading the whole list of items.

I used the Angular material code from their demo illustrate my point, with the only modification being the addition of a space to the end of 'Alabama ' See http://codepen.io/simondevries/pen/BKWwYM
1) Type 'Alabama ' into the autocomplete,
2) Press the 'X' button
and then you will notice only one item is displayed when all should be displayed.

**Comment by topherfangio** [comment]
Confirmed, and nice catch :smile:
