### ISSUE TITLE
Please provide standalone layout grid again

### ISSUE THREAD

**Issue by MartinMuzatko** [angular/material#7660]
Please restore the very handy flexbox standalone grid,
see https://github.com/angular/material/pull/5180

**Comment by ThomasBurleson** [comment]
@MartinMuzatko - Can you provide more details? What specifically do you want?

> we do publish [angular-material.layouts.css](https://github.com/angular/bower-material/blob/master/angular-material.layouts.css)

**Comment by MartinMuzatko** [comment]
A standalone sass version of the angular material grid layout would be nice to have available.
Thanks for the information about the additional repo!

Any further information is very much appreciated.

**Comment by ThomasBurleson** [comment]
@MartinMuzatko - The build in master will now deploy (to bower-material) the following css and SCSS; notice the `/layouts/` directory:

<img width="423" alt="screen shot 2016-03-21 at 10 22 48 am" src="https://cloud.githubusercontent.com/assets/210413/13931447/9d0a6818-ef60-11e5-9917-db803da0bdeb.png">
