### ISSUE TITLE
Conditions in md-component-id of mdSidenav

### ISSUE THREAD

**Issue by Shirohana** [angular/material#7661]
I want to generate md-sidenav with dynamic md-component-id.
Does anyway to solve this problem (´・ω・｀)？

This is how I do now:
http://codepen.io/shirohana/pen/xVqYWd?editors=1010

![2016-03-21 7 01 17](https://cloud.githubusercontent.com/assets/11359892/13916745/5d08e8b6-ef97-11e5-9cd3-7a67becd8877.png)
<img width="494" alt="2016-03-21 7 04 55" src="https://cloud.githubusercontent.com/assets/11359892/13916825/e00660ae-ef97-11e5-819b-850da016bfff.png">

**Comment by DevVersion** [comment]
@Shirohana This should be possible, when #5972 is merged. 

cc. @EladBezalel

**Comment by Shirohana** [comment]
E..excuse me,
how should I change my code and keep it intuitively (´；ω；｀)

**Comment by DevVersion** [comment]
@Shirohana Closing this, because the interpolation you use, is not valid.

You should create a function or variable in the scope, which concats these both strings.

E.g `md-component-id="{{ first }}"` works well.

**Comment by Shirohana** [comment]
I see.
Thanks a lot anyway (๑• ω •๑)

**Comment by adadgio** [comment]
I'm sorry, but md-component-id="{{ variable }}" does NOT work.

**Comment by Splaktar** [comment]
Fixed in `1.1.2` via PR https://github.com/angular/material/pull/9255
