### ISSUE TITLE
Angular materials md-slider aria-valuenow picking up value from previous value

### ISSUE THREAD

**Issue by ksabariraj** [angular/material#7663]
Hi,

I have few slider options in my application, when clicking on the button I am changing the min and max value dynamically. 

In second attachments,  aria-valuenow take the the min value of the previous one. I Set the min to -6.3 and max to 6.3 but the aria-valuenow show 281which the previous value.

<img width="557" alt="first" src="https://cloud.githubusercontent.com/assets/3765085/13917346/2a82f4b0-ef86-11e5-921e-00894a6981cf.png">
<img width="547" alt="second" src="https://cloud.githubusercontent.com/assets/3765085/13917348/2ac3c4f4-ef86-11e5-84e4-99486bbb72e0.png">

Thanks,
Sabari.

**Comment by topherfangio** [comment]
Can you please provide a demo? Seems related to #7474.
