### ISSUE TITLE
md-tab-label get truncated on mobile

### ISSUE THREAD

**Issue by sahilanguralla** [angular/material#7664]
In mobile view the md-tab-label get truncated on mobile making it impossible to read on mobile which is bad in terms of user experience. Their must be some option like **md-label-view** than can be set to **scroll**, **truncate** or **full**. And make **truncate** by default.
Thanks in advance!

**Comment by topherfangio** [comment]
According to [spec](http://www.google.com/design/spec/components/tabs.html#tabs-content), we should be wrapping long text at least one line before truncating.

Also noticed some issues on small screens with very large tab labels that take up more than the screen width; should investigate/fix at the same time.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
