### ISSUE TITLE
mdSlider: md-reverse feature request

### ISSUE THREAD

**Issue by soooooot** [angular/material#7666]
```html
<md-slider md-reverse min="0" max="100"></md-slider>
```
it makes min value to top/right, and max value to bottom/left 
(regularly  min value at bottom/left, max value at top/right)

I have implemented it in [CodePen](http://codepen.io/anon/pen/bpqNYv). 
I don't know is anybody else need the feature or not, anyway, I will make a PR soon.

**Comment by topherfangio** [comment]
@soooooot What is the purpose of the reverse mode? Is it to support RTL languages? If so, I think it would be better if the component supported the `[dir="rtl"]` attribute.

@EladBezalel We had a similar discussion recently correct? Any updates/thoughts?

**Comment by soooooot** [comment]
@topherfangio my case is not a RTL case but a pagination slider, which should be reversed.

**Comment by EladBezalel** [comment]
@topherfangio this is just to make the slider reversed, legit request

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
