### ISSUE TITLE
Flex and layout wrap content issue on Mobile Devices

### ISSUE THREAD

**Issue by fals** [angular/material#7668]
angular: 1.4.8
angular-animate: 1.4.8
angular-material: 1.0.0-rc5

I'm having a issue with flex and layout content, only for mobile devices, more precisely Google Chrome browser. When the content is in the scrolled area, it appear correctly, show up everything, redering as intended.

![screenshot_1](https://cloud.githubusercontent.com/assets/3750960/13923564/f8a62fb4-ef5f-11e5-8bd3-eefcacaea292.png)

But the content that was not scrolled at the time that the page renders gets messed up, like the image below.

![screenshot_2](https://cloud.githubusercontent.com/assets/3750960/13923586/103ae91c-ef60-11e5-9073-0c30a1db3914.png)

If I somehow interact with the page, for exemple, click on the menu hamburguer buttom, the content appear as intended

![screenshot_3](https://cloud.githubusercontent.com/assets/3750960/13923619/27e3d182-ef60-11e5-964e-5deacb6a2eaf.png)

I'm using loyout-md="column" for tablets, layout-wrap and only the default flex.

What could I do to fix this? I'm struggle with this!

**Comment by topherfangio** [comment]
If you haven't already, you might try upgrading to 1.1.0-RC1, this may fix it, but it may not.

In 1.1.0, we are also adding a new class to the `<md-content>` component called `md-no-momentum` which may fix the issue, but it unfortunately causes the momentum scrolling to be disabled.

Here are some similar issues for reference: #5707, #2887, #4477, and #2640. I am almost positive this is the same issue, so I am going to close as a duplicate. If none of the suggestions above or in the linked issues work, please let us know and we will reopen.

**Comment by topherfangio** [comment]
Sorry, meant to link the relevant `<md-content>` docs: https://material.angularjs.org/1.1.0-rc1/api/directive/mdContent
