### ISSUE TITLE
md-sidenav, md-list, md-list-item don't inherit default theme

### ISSUE THREAD

**Issue by maenthoven** [angular/material#7673]
http://codepen.io/anon/pen/QNpZEo

Shouldn't the sidenav be dark here as well?

**Comment by DevVersion** [comment]
@maenthoven The sidenav wasn't applying the theme correctly. We recently fixed that with SHA cb864d558ad780dc573c02adc2ba9a0b336c28c9

I will close that issue, because it's actually fixed when using the latest version.

By the way: You are using `0.9.4`, that's why the fix isn't present here.
