### ISSUE TITLE
Multi-line prompt dialog

### ISSUE THREAD

**Issue by jadjoubran** [angular/material#7679]
Thanks for this great project.

I'd like to ask if multi-line prompt dialog would be considered in the pipeline.

And if so, would you accept a PR?

:smile:

**Comment by topherfangio** [comment]
Can you point to something in the [Spec](http://www.google.com/design/spec) that shows what you want?

**Comment by jadjoubran** [comment]
@topherfangio I couldn't find any of the md-dialogs in [Dialogs spec](http://www.google.com/design/spec/components/dialogs.html) so I also couldn't find the multi-line prompt.

However what I meant is an option to the existing [Prompt Dialog](https://material.angularjs.org/latest/demo/dialog) that allows you to specify whether the prompt should be multi-line or not

**Comment by topherfangio** [comment]
@jadjoubran I think this would be a useful addition and we would definitely welcome a PR :smile:

**Comment by topherfangio** [comment]
@EladBezalel I'm assigning you to this so you can provide feedback, but also so that it's not unassigned :smile:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
