### ISSUE TITLE
tabs: tab label text and inkbar colors not aligned with spec

### ISSUE THREAD

**Issue by ilovett** [angular/material#7685]
Based on the spec, they show tabs on a white background having the indicator the same color as the text and primary color:

![image](https://cloud.githubusercontent.com/assets/1776100/13936417/cedd3342-ef7a-11e5-9cd1-e73567b2530c.png)

The current `md-tabs` shows the indicator as the accent color on a white background:

![image](https://cloud.githubusercontent.com/assets/1776100/13936436/f99ac072-ef7a-11e5-8a14-5108a69f7cae.png)

To make matters more complex, in the spec, the accent color is used when the theme background is non-white (or is the primary color)

![image](https://cloud.githubusercontent.com/assets/1776100/13936462/1adcdc20-ef7b-11e5-83c5-679909f7301e.png)

I'm not sure if this can be easily fixed or if it will cause some theme inheritance problems.  If so, perhaps md-tabs should be able to take `md-theme` ?  Or does this just have to do with light theme vs. dark theme?

**Comment by ddimitrop** [comment]
In fact reading the spec, it also shows an example where it states:
"Text color is the same as the tab indicator"

while in details below

Indicator:
"Height: 2dp"
"Color: #fff or accent color"

Tabs with text only

Text
14sp Roboto Medium
Active color: #fff or accent color
Unfocused tab color: #fff 70%

Reading this, it looks to me that the typical option is to use accent color for both the text and the indicator.

Do I read this incorrectly or is there an inconsistency?

**Comment by topherfangio** [comment]
Definitely need to take a look and see if it still lines up with the spec. Perhaps something changed and we haven't updated styles accordingly.

**Comment by ilovett** [comment]
The spec does seem to contradict itself.  I've seen in many google apps using the same primary color for both the indicator and the text, so long as the background is white/grey.

Either way, perhaps `md-tabs` can take the class `md-primary` and we can leave it up to the developer.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by FabiolaBautista** [comment]
Is this fixed in material2? It looks like the this issue is still visible in material2.

**Comment by Splaktar** [comment]
Based on the [tabs spec](https://material.io/archive/guidelines/components/tabs.html#tabs-usage), there should be the following options for coloring
- White text on a primary background with an accent color inkbar
- White text on a primary background with a white inkbar
- Primary color text on a light background with a primary color inkbar 

Currently `md-tabs` uses the following
- Primary color text and accent color inkbar on a light background
- White text and accent color inkbar on primary background
- White text and primary color inkbar on an accent background

**Comment by Splaktar** [comment]
This should be resolved now, here are some screenshots:

# Before

![Screen Shot 2020-07-30 at 19 14 18](https://user-images.githubusercontent.com/3506071/88988409-d1885b80-d2a6-11ea-94c4-e0949695a557.png)
![Screen Shot 2020-07-30 at 19 14 57](https://user-images.githubusercontent.com/3506071/88988404-d0572e80-d2a6-11ea-8af7-e894d1a1f1d3.png)

# After

![Screen Shot 2020-07-30 at 19 14 27](https://user-images.githubusercontent.com/3506071/88988405-d0efc500-d2a6-11ea-97b8-f7c233785d5c.png)
![Screen Shot 2020-07-30 at 19 15 07](https://user-images.githubusercontent.com/3506071/88988402-cfbe9800-d2a6-11ea-90e4-d660683440f6.png)

Here is the new `md-tabs` documentation on theming:
![Screen Shot 2020-07-30 at 20 55 45](https://user-images.githubusercontent.com/3506071/88988521-1d3b0500-d2a7-11ea-80b7-f9516ada97d3.png)

**Comment by Splaktar** [comment]
And here are a bunch of tests that I did with primary/accent/warn palettes and light/dark modes:

# md-primary

![Screen Shot 2020-07-30 at 20 41 59](https://user-images.githubusercontent.com/3506071/88988616-57a4a200-d2a7-11ea-8e32-2dae762bac22.png)
![Screen Shot 2020-07-30 at 20 38 55](https://user-images.githubusercontent.com/3506071/88988623-58d5cf00-d2a7-11ea-8f66-3de7cd01c166.png)
![Screen Shot 2020-07-30 at 20 41 46](https://user-images.githubusercontent.com/3506071/88988617-583d3880-d2a7-11ea-8de3-1cfcddfb1dbd.png)
![Screen Shot 2020-07-30 at 20 39 13](https://user-images.githubusercontent.com/3506071/88988621-58d5cf00-d2a7-11ea-9558-4480dbc0c695.png)

# md-accent / md-warn

![Screen Shot 2020-07-30 at 20 39 57](https://user-images.githubusercontent.com/3506071/88988619-583d3880-d2a7-11ea-9e80-4f07959ac062.png)
![Screen Shot 2020-07-30 at 20 34 27](https://user-images.githubusercontent.com/3506071/88988624-58d5cf00-d2a7-11ea-8e6a-67f54961d9fd.png)
![Screen Shot 2020-07-30 at 20 34 01](https://user-images.githubusercontent.com/3506071/88988625-596e6580-d2a7-11ea-8a10-77f7185a065a.png)
![Screen Shot 2020-07-30 at 20 29 17](https://user-images.githubusercontent.com/3506071/88988626-596e6580-d2a7-11ea-9a7a-e0ee251f6036.png)
![Screen Shot 2020-07-30 at 19 25 59](https://user-images.githubusercontent.com/3506071/88988627-596e6580-d2a7-11ea-81d6-b748439e4103.png)
![Screen Shot 2020-07-30 at 19 24 37](https://user-images.githubusercontent.com/3506071/88988629-5a06fc00-d2a7-11ea-8764-b2d5091a4ec1.png)
![Screen Shot 2020-07-30 at 19 24 01](https://user-images.githubusercontent.com/3506071/88988631-5a06fc00-d2a7-11ea-9e30-5a6f41b94cf5.png)
