### ISSUE TITLE
Cards do not show images in Safari

### ISSUE THREAD

**Issue by Tommatheussen** [angular/material#7692]
The cards images are not being shown on safari. If I change some properties through the in browser editor I can sometimes see the images. I know they are some specific rules for flex attributes in safari.

The major problems is that the issue also exists on the demo site: https://material.angularjs.org/latest/demo/card
If might be good if it gets fixed there, are is mentioned somewhere so ppl are aware that they need specific attributes for this to work.

Safari Version 9.0.3 (11601.4.4) for reference

**Comment by DevVersion** [comment]
I can reproduce that.

![image](https://cloud.githubusercontent.com/assets/4987015/13948498/b808840e-f020-11e5-9489-a6fcd5bc3e15.png)

**Comment by topherfangio** [comment]
@DevVersion Can you look into this and find the cause?

**Comment by DevVersion** [comment]
@topherfangio I've found the issue, it's caused by the width, which is set to `100%`, it seems like the computed height of 100% is zero. That means, when switching that to `auto`, everything works.

But I've noticed, that the `100%` were recently and intentionally  added, so I'm trying to understand those thoughts.

**Comment by Tommatheussen** [comment]
Btw, when testing my app cross browser, I noticed that the images are not quite correct in FF either. So I went to check if they are correct in the demo page, and it seems the issue exists there as well, probably is fixed by the auto height as well, just wanted to let you know.

![screen shot 2016-03-24 at 11 17 11](https://cloud.githubusercontent.com/assets/13683094/14014306/1200f2ec-f1b2-11e5-91c0-cdf86ed4d130.png)

**Comment by topherfangio** [comment]
@DevVersion Can you point me to the commit where it was added so I can take a look?

**Comment by TitanNano** [comment]
@topherfangio The image height was set from `auto` to `100% !important` in df902381664bc568ad4011f1747ccc44a856995f

**Comment by topherfangio** [comment]
@DevVersion It might be helpful for you to pair with @EladBezalel on this one as he did a major upgrade to the cards for 1.0.

**Comment by DevVersion** [comment]
@EladBezalel I just assigned the issue to you, because you worked on those image rations.

**Comment by jeremypokeefe** [comment]
I found a workaround for now if anyone is interested. I wrapped the img element in a div with the layout set to row and the alignment to center, center.

`<div layout="row" layout-align="center center">
   <img src="{{feature.imagePath}}" class="md-card-image" alt="{{feature.title}}" >
 </div>`

**Comment by ThomasBurleson** [comment]
See PR #8183.

**Comment by EladBezalel** [comment]
@ThomasBurleson can you confirm it's fixed? (doesn't have a Safari ATM)

**Comment by topherfangio** [comment]
@EladBezalel @ThomasBurleson Looks good to me in Firefox, Chrome and Safari on OS X.

Also looks good on IE/Edge/Firefox on Windows 10 tested via BrowserStack.

I think we can close?

**Comment by SekharBeri** [comment]
Is this issue really fixed. i am still getting the same issue in safari both web and mobile.

**Comment by topherfangio** [comment]
@SekharBeri Just tested 1.1.1 on both desktop and iOS Safari and all looks good.

What version are you using?

**Comment by SekharBeri** [comment]
@topherfangio It is 9.1.2 . This version only I'm using in both mobile and desktop.

**Comment by topherfangio** [comment]
@SekharBeri Sorry, what version of Angular Material are you using?

**Comment by SekharBeri** [comment]
@topherfangio Angular Material version 1.0.9. I will update to the latest version and let you know if I got any problem. Thank you for your response.

**Comment by SekharBeri** [comment]
@topherfangio Sorry for the late reply. I have updated my angular material version. Still, I have the same problem. I am unable to display images on cards. This causes  big problem to me so, I have changed my application to boostrap css.

**Comment by ThomasBurleson** [comment]
@SekharBeri - please open new issue with details AND CodePen Demo.
