### ISSUE TITLE
md-progress-circular seems to be pixellised

### ISSUE THREAD

**Issue by ByJC** [angular/material#7694]
Hi everyone,

The progress circular seems to be pixellised. it's more and more pixellised when the diameter is small.

is there a way to improve the look and feel of it ? 

to try : https://material.angularjs.org/latest/demo/progressCircular

I use Chrome Version 49.0.2623.75 (64-bit) but I have the same effect with safari

**Comment by crisbeto** [comment]
It's using SVG so this is pretty much as sharp as it's going to get. This also depends on your screen resolution and pixel density.

**Comment by DevVersion** [comment]
I can't see any pixelized circulars in the demos.

Notice: this is a 50x50 px circular.
![image](https://cloud.githubusercontent.com/assets/4987015/13949409/27ec1868-f025-11e5-8b12-194b559b24e9.png)

@crisbeto Please take a look.

**Comment by crisbeto** [comment]
Me neither, I tried both on Chrome and the latest Safari (which is kinda old tbh) on Windows.

![new](https://cloud.githubusercontent.com/assets/4450522/13949536/e4d672d4-f025-11e5-978e-335e989e99a1.png)

**Comment by ByJC** [comment]
Well, I have the following resolution : 2560 x 1440.
And when i try the `md-diameter="20px"`
I have this results : 
![screen shot 2016-03-22 at 11 58 43](https://cloud.githubusercontent.com/assets/11909355/13949546/f56b593e-f025-11e5-8978-6f161b2fd59a.png)

**Comment by crisbeto** [comment]
I took the screenshot on a 1920x1080 screen, but as I mentioned, this is as sharp as it gets and we don't really have much control over how the browser decides to render it at that small of a size.

**Comment by ByJC** [comment]
Ok guys ! I was looking an old version (1.0.5) where you transform like that :     `transform: translate(-50%, -50%) scale(0.2);` directly on the md-scale-wrapper.

With the 1.10, I don't have the issue ... Sorry for bothering you

**Comment by DevVersion** [comment]
@ByJC No worries, thanks for keeping track.
