### ISSUE TITLE
Tabs not showing up in IE11 with md-center-tabs 

### ISSUE THREAD

**Issue by super-coder** [angular/material#7695]
used standard demo, added md-center-tabs

http://codepen.io/beyondev/pen/Wwpqjr

![image](https://cloud.githubusercontent.com/assets/2155554/13949273/fa8a134c-f01b-11e5-916c-0c1d5de1e600.png)

if i resize 
![image](https://cloud.githubusercontent.com/assets/2155554/13949278/04ac162c-f01c-11e5-9a6d-60aa3b0d1421.png)

**Comment by topherfangio** [comment]
What version of Windows are you using? I can't seem to reproduce this in IE11 on Win10.

**Comment by super-coder** [comment]
Windows 8.1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
