### ISSUE TITLE
mdDialog: flex elements should adjust to dialog width instead of the viewport

### ISSUE THREAD

**Issue by migingreen** [angular/material#7698]
See altered custom dialog example: [here](http://codepen.io/anon/pen/jqmNLo)

Maybe this suggestion is wrong or I still don't grasp the concept of flexbox in combination with dialog completely, but shouldn't flex elements inside a dialog adjust to the width of the mdDialog element instead of the viewport width?

For example, If we also want to utilize reusable components inside of a dialog, we would have to adjust each flex value in order to display the same component correctly inside of a dialog element, this seems counterintuitive to me.

**Comment by topherfangio** [comment]
The flex/layout properties like `flex-xs` or `layout-sm` currently use CSS media queries (and some fancy JS) to determine the breakpoints.

Unfortunately, this means that the breakpoints are tied only to the viewport size, not the size of the containing elements. So, I'm not sure this is something we can easily support. Also, if we do, it will likely be a different set of directives as the layout/flex directives are solely for device/screen size.

Concerning dialogs, once the viewport reaches a small enough size, the dialog itself will become fullscreen to take up as much width as possible which should help.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
