### ISSUE TITLE
mdMenu: menu shrinks when opening while keyboard closes on mobile

### ISSUE THREAD

**Issue by Zacharias3690** [angular/material#7704]
When opening md-menu on mobile, if the menu opens at the same time the keyboard is closing the menu will shrink.

Using:
angular-material v1.0.6
All browsers

Here's a codepen with an example: http://codepen.io/Zacharias3690/full/VabLzM/
and a video of it occuring (changing browser size to simulate keyboard closing)
![image](http://i.giphy.com/hjCL6kooNegFO.gif)

In the codepen on mobile it occurs ~%25 of the time, but on slower webpages happens more often.

**Comment by Zacharias3690** [comment]
Appears to be related to https://github.com/angular/material/pull/6852

**Comment by topherfangio** [comment]
I believe this is indeed the same as the issue you mentioned. Closing as a duplicate.
