### ISSUE TITLE
dynamic md-tab not set md-select 

### ISSUE THREAD

**Issue by bhandaribhumin** [angular/material#7706]
In controller 
$scope.selectedIndex = 3;
in html
\<md-tabs md-selected="selectedIndex"  md-dynamic-height md-border-bottom="" class="material-background"\>
   \<md-tab ng-repeat="(cat_id, categorie) in catTabTitle"   ng-click="getItems(cat_id)" label="{{categorie}}"\>
        \<md-content class="" ng-repeat="subcat in catItems"\>
 \</md-content\>
\</md-tab\>
\</md-tabs\>
by default tab not select 3rd index

**Comment by topherfangio** [comment]
@bhandaribhumin As we have stated before, we cannot help you without a demo, and this type of question is best asked on the [forums](https://groups.google.com/forum/#!forum/ngmaterial), not here on GitHub. Please post your question there with a demo and all relevant information.
