### ISSUE TITLE
allow registering custom style sheet (mdss ?) into `$MD_THEME_CSS`

### ISSUE THREAD

**Issue by ilovett** [angular/material#7708]
Would be very handy to be able to register your own component and hook into dynamic theming... This may require changing setting `$MD_THEME_CSS` as a constant to a provider or decorator.

Since these style sheets have angular material specific variables, perhaps store the data in `mdss` files.

```
var fs = require('fs');

// require mdss files as a string
require.extensions['.mdss'] = function(module, filename) {
    module.exports = fs.readFileSync(filename, 'utf8');
};

angular.module('myApp').config(function($mdThemingProvider) {
  $mdThemingProvider.registerStyles(require('./my-component-theme.mdss'));
})
```

my-component-theme.mdss
```
tr[md-row].md-THEME_NAME-theme {
  ...
  background: {{ background-200 }}
}
```

I'm not sure what the logic is for the `md-theme` directive to add the class but that may need to be changed as well.

**Comment by DevVersion** [comment]
Wow, this is an awesome feature request! :+1:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).
