### ISSUE TITLE
md-virtual-repeat-container doesn't render correctly on safari

### ISSUE THREAD

**Issue by kthakre9** [angular/material#7709]
While using md-virtual-repeat-container for infinite search, items returned from the search do not show up on the page in safari. I can see them on the Safari Dev Tools though.
Works perfectly on firefox and chrome.

<img width="739" alt="screen shot 2016-03-22 at 4 22 03 pm" src="https://cloud.githubusercontent.com/assets/12789665/13966751/51473074-f04a-11e5-8f56-03f9ad2722a0.png">

If I remove the class .md-virtual-repeat-container , the items show up.

**Comment by topherfangio** [comment]
Can you please provide a Codepen which demonstrates this issue?

**Comment by mhamann** [comment]
The issue was related to a missing `)` in a CSS `calc()` operation. I think this can be closed.

**Comment by topherfangio** [comment]
Awesome, thanks!
