### ISSUE TITLE
md-icon - Creating own scopes?

### ISSUE THREAD

**Issue by graphefruit** [angular/material#7713]
Hello Team,

I'm on my "performance" session in my app, and have installed the Chrome-AngularJS-Plugin to see the created scopes.

After I've debugged a little I saw that the MD-ICON creating his own scopes?
![image](https://cloud.githubusercontent.com/assets/6260244/13982049/10a55f8e-f0e8-11e5-87bf-3784a8d55099.png)

The code looks like:
```
<md-button ng-click="closeNavigation()" class="md-icon-button">
   <md-icon md-svg-icon="navigation:close"></md-icon>
</md-button>
```

Is there a possibility to bind-once this, or am I reading this wrong?

Thanks in advance for your help
Greetings
Graphefruit

**Comment by crisbeto** [comment]
I wouldn't say it's a bug, but it's probably excessive to have an isolate scope on each icon, considering that we can get that info with the `attrs` that are passed into the link. This should be pretty easy to do.

**Comment by topherfangio** [comment]
I'm going back and forth a bit. I can see how we might be able to optimize this not to have a scope, but I wonder if we would just wind up adding watchers instead.

I think that the isolate scope is a cleaner solution, but if there is a significant performance gain from switching and there aren't any breaking changes, I'd be open to it.

**Comment by crisbeto** [comment]
If you take a look at the icon directive's source, it doesn't really use the scope for anything, apart from reading the value.

**Comment by graphefruit** [comment]
Maybe the scope is not used for anything, but it will blow up the scopes.
In my actual project I have more then 40 scopes because of icons, thats not that cool.

**Comment by crisbeto** [comment]
Yeah, that's my point. All those values can be read from the `attrs`.
