### ISSUE TITLE
Layout and flex doesn't work well on Safari mobile (IOS)

### ISSUE THREAD

**Issue by percenuage** [angular/material#7714]
I'm using angular-chart.js. I would like to show 3 charts on IOS with Safari. The charts are superimposed.

 ```javascript
<md-content layout="column" layout-padding layout-align="start center">

		<div flex ng-repeat="chart in charts track by $index"
			 style="text-align: center;">
				<h4>{{chart.title}}</h4>
				<canvas class="chart chart-doughnut"
						chart-data="chart.data"
						chart-labels="chart.labels"
						chart-legend="true">
				</canvas>
		</div>

</md-content>
```

**Comment by crisbeto** [comment]
This isn't a whole lot of info to go on.

**Comment by WieldSoftwareDevelopement** [comment]
It isn't just Safari on IOS.  It is any browser (Chrome and Firefox).  I'm specifically referencing IOS 9.3.  

Digging more into this today and will update this post later.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
