### ISSUE TITLE
How i can change float label in md-input-container to right? 

### ISSUE THREAD

**Issue by aziz1117** [angular/material#7720]

**Comment by DevVersion** [comment]
You mean, interpolating? You should provide more information, currently there are many possibilities of what you mean.

**Comment by aziz1117** [comment]
I try to write this code:
<md-input-container>
<label>اسم العضو</label>    <---------- in browser it will be in left side but i want to be in right side
<input name="name"/>
</md-input-container>

**Comment by aziz1117** [comment]
![label](https://cloud.githubusercontent.com/assets/7342455/14019290/156135ec-f1e3-11e5-8a92-791b245347e6.png)


I want label "اسم العضو" to be in the right side.

**Comment by DevVersion** [comment]
That isn't possible yet. You may use some custom CSS, but at the moment, we just support RTL, LTR automatic detection, what means that the label will be in RTL, at the right aligned.

**Comment by aziz1117** [comment]
Because i am using Arabic Language (RTL), so i need to custom label to the right side.
How i can use custom CSS to align label?

**Comment by DevVersion** [comment]
Works as expected. When using RTL direction, the floating label is aligned to the right.

See in the demo
- http://codepen.io/DevVersion/pen/oxQLzL
