### ISSUE TITLE
Md-Tabs Dynamic Height bug on Safari with trackpad

### ISSUE THREAD

**Issue by xuaninbox** [angular/material#7722]
When using Md-Tabs with Dynamic Height on **Safari** with **trackpad** (i.e. trackpad on a macbook) the tab may **temporally lose height**. This may cause a problem and causing the page to jump to top when switching.

This can only be reproduce via **tap the trackpad** and **not actually click the trackpad**. 

It also cant be reproduced using Chrome or a Mouse.

![bug](https://cloud.githubusercontent.com/assets/5108256/14009377/4ceae394-f159-11e5-9feb-e87f9401c4f9.gif)

**Comment by topherfangio** [comment]
Confirmed; can reproduce on the 1.1.0-RC1 demo site using Safari and a trackpad.

**Comment by manuelagard** [comment]
+1
Same problem here

**Comment by xuaninbox** [comment]
**Update** We are able to fix it by changing the css 

md-tab-content {
bottom: 0 !important;
}

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
