### ISSUE TITLE
mdDialog: wrong padding

### ISSUE THREAD

**Issue by TitanNano** [angular/material#7725]
At @ZmbGmbH we discovered that the md-dialog doesn't follow the exact specification. 

![components_dialogs_updates1](https://cloud.githubusercontent.com/assets/4500858/14013912/77bf68c8-f1af-11e5-9931-ef6aa05f35e7.png)

The title should have a padding of `padding: 24px 24px 20px 24px;` and the content `padding: 0 24px 24px;`

Right now there is just a total padding of 24px with the `.md-dialog-content` class and no separation between title and content.

https://www.google.com/design/spec/components/dialogs.html#dialogs-specs

**Comment by DevVersion** [comment]
Referencing PR #7726 here.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
