### ISSUE TITLE
mdSlider: step slider thumb can not drag to max value

### ISSUE THREAD

**Issue by soooooot** [angular/material#7732]
if the max value can not be divided by step value, we can never drag the thumb to max value or press to max value, what we can do is to press the arrow key to reach the max value.

you can check on [CodePen](http://codepen.io/soooooot/pen/zqwepv).
step is 20, and the max value is 188, but I can only reach to 180 by drag or press.

```js
      var closestVal = minMaxValidator( stepValidator(exactVal) );
```
the exactVal 188 can not pass the `stepValidator` so it's changed to closest step value 180.

Does it design to behaviour like this? 
if not, here's my solution 1, modify the `stepValidator` function only.
```js
    function stepValidator(value) {
      if (angular.isNumber(value)) {
        var formattedValue = value;
        if (value !== max && value !== min) {  // <-- we do not validate min/max value
          formattedValue = (Math.round((value - min) / step) * step + min);
          formattedValue = (Math.round(formattedValue * Math.pow(10, round)) / Math.pow(10, round));
        }
        // some other code here
        return formattedValue;
      }
    }

```
but the `stepValidator` is a little bit wired, since the max value should not pass the step validator on literal.

solution 2:
I found out we call `stepValidator` only in three places, and the usages are the same.
```js
      var closestVal = minMaxValidator( stepValidator(exactVal) );
```
so can we write a `minMaxStepValidator` instead that?
```js
      var closestVal = minMaxStepValidator(exactVal);

    function minMaxStepValidator(val) {
      return (val === max || val === min) ? val : minMaxValidator( stepValidator(val) );
    }
```

I prefer to solution 2 and I'm very pleasant to make a PR if the new behaviour makes more sense.

**Comment by topherfangio** [comment]
@EladBezalel Can you provide your thoughts on the solutions above and recommend for/against a PR?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
