### ISSUE TITLE
mdDatepicker: Validation issue - Required validator with md-min-date and md-max-date does not behave as expected

### ISSUE THREAD

**Issue by 4zuko** [angular/material#7739]
If user deletes value from Date input field custom validation error message (e.g. 'This date is required') is being shown which is expected behavior. The same error message is still shown if user enters date that does not match min/max validation rule (e.g. 10/10/2000).

**Angular Material Version:** _1.1.0-rc1_
**Browsers:** _Tested on IE11/Edge/Chrome/Firefox_
**Operating System:**_Tested on Windows 10_
**Reproduce the Error:** _Please take a look at the [CodePen example](http://codepen.io/_4zuko/pen/xVdNMg)_

**Comment by topherfangio** [comment]
@EladBezalel I haven't looked at the code, but my first guess would be that the picker isn't setting the date somewhere since it's invalid, which is tricking it into thinking it's invalid.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
