### ISSUE TITLE
Autocomplete doesn't work well within tabs

### ISSUE THREAD

**Issue by RaghuramDuraisamy** [angular/material#7743]
Sample code - http://codepen.io/raghuram/pen/ONgLdB

1. Autocomplete inputs in columns 3 and 4 are not working, nothing happens on clicking them
2. When a value is selected in autocomplete input in column 1, autocomplete inputs on column 2, 3, and 4 disappear. Autocomplete inputs on column 2 reappear on hover, but 3 and 4 remain hidden.

Browser: Chrome 43.0.2357.130 (64-bit) on Ubuntu 15.10

Could you please let me know if I am using something incorrectly?

**Comment by topherfangio** [comment]
As far as I can tell, everything works correctly in Chrome 47 on Arch Linux, and Chrome 49 on OS X and Windows.

Also, your code looks good to me. Can you try upgrading Chrome and seeing if that fixes the issue?

**Comment by RaghuramDuraisamy** [comment]
Thanks @topherfangio . I upgraded Chrome to 49.0.2623.108 (64-bit) and that fixed the issue.

**Comment by topherfangio** [comment]
@RaghuramDuraisamy Awesome! Glad it's working! Strange Chrome issue though :smiley:
