### ISSUE TITLE
mdFab, mdRipple: FAB ripple effect doesn't work properly in Mozilla Firefox

### ISSUE THREAD

**Issue by tsarapke** [angular/material#7745]
![am_ff_ripple](https://cloud.githubusercontent.com/assets/7983863/14043895/9b0bf4fe-f29a-11e5-9a38-69d65ae720cd.gif)

The ripple effect goes beyond of the area of the FAB when you focused in.
Checked on Mozilla Firefox 45.0.1

After checking of various cases, i found that the ripple effect don't goes beyond of the area of the FAB in FF, if you add **mask: url();** or **clip-path: url();** (while the **url** value is empty) to the **md-ripple-container** class. Maybe it can help.

Also I had already opened same issue at Google MDL repository (**[link](https://github.com/google/material-design-lite/issues/4215)**).

**Comment by topherfangio** [comment]
Can you please provide a Codepen demo so that we can duplicate it more easily and debug?

**Comment by tsarapke** [comment]
Sure. [Here is demo](http://codepen.io/tsarapke/pen/xVrqxJ).

Also I want to say that it can be reproduced at full page mode and rarely at edit mode.

**Comment by topherfangio** [comment]
Awesome, thanks!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
