### ISSUE TITLE
i,m not getting md-icons in the chrome versions Version 40.0.2214.111 (64-bit) linux from 25th-mar-2016.

### ISSUE THREAD

**Issue by vijj** [angular/material#7746]
i,m not getting md-icons in the chrome  Version 40.0.2214.111 (64-bit) linux from 25th-mar-2016.
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
can you help me

**Comment by DevVersion** [comment]
Please provide more information.

**Comment by vijj** [comment]
![11](https://cloud.githubusercontent.com/assets/14217225/14059655/fc6427f2-f36d-11e5-8212-d9de90803d3d.png)

i,m not getting md-icons in the chrome Version 40.0.2214.111 (64-bit) linux from 25th-mar-2016.
can you help me

**Comment by Nikki1993** [comment]
@vijj why are you running outdated version? if there is no particular reason then update to latest one, it is 49 not 40.  See if that resolves the issue.

**Comment by vijj** [comment]
from starting onwords  i run this my application in  40 version.but from  last 2 days problem occurs like material icons not supported. i need reason behind this  problem please if you know

**Comment by Nikki1993** [comment]
I can't really fully understand what's up with use of Chrome 40 not 49 but 2 things. First, update it. Second, show the source code and how are you applying material icons. Without code, nothing we can help with.

**Comment by vijj** [comment]
official materialDesign website seems like nothing there is no icons on that
![ss](https://cloud.githubusercontent.com/assets/14217225/14174072/b2dd43f2-f75f-11e5-86b5-13141c5f5e04.png)

**Comment by Nikki1993** [comment]
Everything works just fine here on Google chrome 49. Update it to latest version.

**Comment by ThomasBurleson** [comment]
Closing issue since a CodePen is not available.
