### ISSUE TITLE
mdAutocomplete: scrolls to top then back to correct position on focus in Safari (OS X)

### ISSUE THREAD

**Issue by rochdev** [angular/material#7752]
When focusing the autocomplete input field, the page scrolls to the top and back down quickly (you can see a flicker).

This doesn't seem to affect the docs, however the scroll lock doesn't work either on the docs so maybe it's related to that.

I could reproduce on angular-material 1.0.5 and 1.1.0-rc1

Demo of the issue: [maclev.io](http://maclev.io)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by rochdev** [comment]
I've solved it by using `display: flex` but I don't understand why this is required

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
