### ISSUE TITLE
Flex issue in IE 11 layout

### ISSUE THREAD

**Issue by paulsperanza** [angular/material#7753]
This code renders correctly in Chrome and Firefox, where the second column is to the right of the first. When the window is resized to a smaller size in IE 11 the text on the right meshes with the text on the left, instead of the text on the right going below the text on the left. See attached screen shots. Using Angular 1.0.6 on Windows 10.

```
    <div>
        <div layout="row" layout-xs="column">
            <div flex>
                I'm above on mobile, and to the left on larger devices.
            </div>
            <div flex>
                I'm below on mobile, and to the right on larger devices.
            </div>
        </div>
    </div>
```
![ienormalstate](https://cloud.githubusercontent.com/assets/154852/14052866/be49bd58-f2a3-11e5-8f36-6d48b6eefc93.png)

![ielayouterrorstate](https://cloud.githubusercontent.com/assets/154852/14052869/c1c36f38-f2a3-11e5-9779-9061ddbd3d37.png)

**Comment by fookoo** [comment]
I got the same issue on:

Angular 1.5.3
Material Design: ( "angular-material": "~1.0.7")

**Comment by ThomasBurleson** [comment]
Please provide a CodePen that demonstrates this issue: CodePen template: http://codepen.io/pen?template=bEGJdd

> You may also refer to our [Flexbox TroubleShooting Tips](https://material.angularjs.org/latest/layout/tips)

**Comment by paulsperanza** [comment]
http://codepen.io/anon/pen/zqJJBP

**Comment by spamguy** [comment]
I had been having a similar, infuriating problem for awhile.

This works on the desktop, but not on mobile: `<div layout="row" layout-xs="column">...</div>`

Although that block is technically correct, your intentions are clearer to the browser using this: `<div layout-gt-xs="row" layout-xs="column">...</div>`

When I rewrote my code that way, the container's children stopped overlapping.

If y'all think this should get a ticket I will write one up.

**Comment by kubaprzetakiewicz** [comment]
For some reason we're running into the same problem in the whole project, only with IE.

Our global fix for that currently is:
```
  :-ms-fullscreen, :root {
    [class*=flex] {
      flex-basis: auto;
    }
  }
```

You can see it working here: http://codepen.io/jimmythenice/pen/MyPPoG
The enclosing tag is the browserhack targeting IE10-11 which will not work in CodePen, but will natively.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
