### ISSUE TITLE
 md-button as flexbox container

### ISSUE THREAD

**Issue by aldeso** [angular/material#7756]
Hi @ all,

I would like to discuss about the md-button directive. The directive transclude the `<md-button>` in a `<button>` tag. In some Browsers, elements like `<button>` do not  work  with flex. i.e. Firefox
If the user needs flexbox, a wrapper element is necessary. 
Maybe you should leave it (optionally) as a `<md-button>` like `<md-checkbox>`.

What's your opinion?

Greetings

**Comment by ThomasBurleson** [comment]
Will not fix.
