### ISSUE TITLE
mdTab: tab select/deselect events not fired for dynamically added tab

### ISSUE THREAD

**Issue by saeedshahab** [angular/material#7757]
Hi,

I was using an mdDialog with tabs, which is populated from an array. When the currently selected tab is removed from the array, the tab list is in view is updated and deselect event is fired to the tab and the adjacent tab is selected with select event. At the same time, when a new element is added to the same index, the view is updated correctly but the deselect/select events are not fired.

I'm using information with the event fired to update the mdDialogActions bar, and this issue is causing it not to update it correctly.

Version: v1.0.6-master-0855fd3
Browser tested: Chrome 48
OS: CentOS 7

Thanks,
Saeed

**Comment by topherfangio** [comment]
Could you please provide a Codepen of the issue so that we can debug it?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
