### ISSUE TITLE
ng-bind-html doesn't always shown in md-autocomplete

### ISSUE THREAD

**Issue by kfirufk** [angular/material#7759]
Hi.
I'm using md-autocomplete to read html results from server. when i use ng-bind-html for a span inside  md-item-template, the items sometimes appear sometimes don't. weird behaviour. created jsfiddle for that at https://jsfiddle.net/kfirufk/9mwL3142/

just start the jsfiddle and start trying stuff. it will return the same results no matter what's in the text field. and sometimes the results are shown and sometimes i just get blank lines.
thanks.

**Comment by ThomasBurleson** [comment]
will not fix.
