### ISSUE TITLE
how to set md-item-text dynamically?

### ISSUE THREAD

**Issue by MohamedAbdelkarim** [angular/material#7760]
Hello guys,
I using `md-autocomplete` along with `md-select`, so users should select search category by `md-select` and then `md-autocomplete` fetches data by calling `$http` service based on `md-select` option selected. for example `md-select` options : search by Number , search by name, search by phone. everything works fine except for `md-item-text` because it's weather item.number , item.name or item.phone.
i wonder if it's possible to access and set `md-item-text`  it in code 
thanks

**Comment by emomon23** [comment]
md-items="item in $ctrl.querySearch($ctrl.searchText)" 
md-item-text="item[$ctrl.itemTextPropertyName]"

This worked for me, where querySearch returns a list of cars (item = a single car)
itemTextPropertyName = 'make', or 'vin', or 'model'
