### ISSUE TITLE
mdTooltip overlaps mdSidenav while its transition

### ISSUE THREAD

**Issue by websirnik** [angular/material#7764]
When the sidenav trigger is located on the side and has a tooltip, the tooltip will overlap the sidenav while its transition to open state. The better UX is not to have the overlap.

See the demo: 
http://codepen.io/websirnik/pen/eZRGoN

**Comment by marcomafessolli** [comment]
I have a similar issue but with tabs, when it changes the tab tooltip keeps showing

**Comment by DevVersion** [comment]
If we set the tooltip z-index to a lower value than the sidenav, we will fix that issue, but also introduce new bugs.

e.g the tooltip will never display inside of a `md-sidenav`.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
