### ISSUE TITLE
Sticky subheader inside tabs issue

### ISSUE THREAD

**Issue by Thijs5** [angular/material#7766]
When having a list in each tab with sticky subheaders, only the subheaders of the first tab are shown. Please look at the gif below.

![subheader-issue](https://cloud.githubusercontent.com/assets/1286325/14065536/62dc95bc-f42e-11e5-939f-6a5c0e35aec7.gif)

The subheader on the first tab says 'Deze week'. This works and after scrolling down, the header changes correctly. After switching tabs, the subheaders of the first tab are still getting used.

**Comment by adam-s** [comment]
I'm experiencing the same problem. What happens is that with three tabs and three subheader groups in each tab, all nine subheaders end up in the active state at some point when scrolled on any tab from top to bottom.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
