### ISSUE TITLE
mdSelect: disabled select is set to touched when clicking at it

### ISSUE THREAD

**Issue by montgomery1944** [angular/material#7773]
Disabled select is set to touched when clicking at it and clicking somewhere else on the page. This causes the error message to be shown. This is not consistent with behaviour of disabled mdInput, which is not set to touched when clicking at it.

Demo can be found at: http://codepen.io/anon/pen/MyoVwY.

Tested with jQuery 2.2.2, Angular 1.5.2 and Angular Material 1.1.0-rc1.

I can provide a pull request with fixes for this issue, including tests, if this is going to help.

**Comment by crisbeto** [comment]
True, I could reproduce it on master. I'll take a look.
