### ISSUE TITLE
App bar title left padding does not comply with Material Design Specs

### ISSUE THREAD

**Issue by angrylala** [angular/material#7776]
According to Material Design Specifications:

For App bar height of 56dp, app bar title left padding should be 72dp
For App bar height of 64dp, app bar title left padding should be 80dp

Reference
https://www.google.com/design/spec/layout/structure.html#structure-app-bar

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
