### ISSUE TITLE
md-select-on-focus directive doesn't work in safari browser

### ISSUE THREAD

**Issue by janvandenberg** [angular/material#7777]
You can test it in any Safari browser using Angular Material's own demo page: https://material.angularjs.org/latest/demo/input

Just focus in the text area in the first section (Basic Usage). Sometimes you see the text selected very briefly, but the end result is always the same, no selected text.

Kind regards,
Jan van den Berg

**Comment by DevVersion** [comment]
Hey, it's already fixed in `master`. [See here](https://material.angularjs.org/HEAD/demo/input)

**Comment by janvandenberg** [comment]
Correct. I've tested several releases, but omitted master. Good to know that this is fixed!

**Comment by DevVersion** [comment]
@janvandenberg Haha, no worries :)
