### ISSUE TITLE
Need validations for  md-chips in the materialdesign

### ISSUE THREAD

**Issue by vijj** [angular/material#7779]
if you know md-chips validations  can you suggest me please 
![screenshot from 2016-03-28 18 08 12](https://cloud.githubusercontent.com/assets/14217225/14078097/5e794cf8-f510-11e5-9a65-f3c8e0a5c936.png)
![22](https://cloud.githubusercontent.com/assets/14217225/14078112/7d1b6f6a-f510-11e5-93ab-df28024ad5f8.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
