### ISSUE TITLE
Theming docs do not cover adding a nonce for CSP

### ISSUE THREAD

**Issue by pames** [angular/material#7780]
Angular Material seems to rely on the use of inline styles even in an ng-csp application:

https://gist.github.com/pames/183a24cd419f8d640b46

which causes problems for sites which want to avoid use of directives such as 'unsafe-inline' etc. for styles.

I haven't investigated the root cause, but is this behavior something you'd be willing to change?

**Comment by jelbourn** [comment]
As @Emeegeemee pointed out, the intended approach is the use of a nonce provided to the theming service. The real bug here is that this isn't mentioned in the documentation.

**Comment by ThomasBurleson** [comment]
@topherfangio - https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L89

**Comment by topherfangio** [comment]
@jelbourn @ThomasBurleson It looks like it is already mentioned in the service docs: https://material.angularjs.org/HEAD/api/service/$mdThemingProvider

Should we add it somewhere else so that people can find it more easily?

**Comment by jelbourn** [comment]
It would probably be helpful to have in the theming guide somewhere in addition to the API docs.
