### ISSUE TITLE
Latest release 1.1.0-rc1 not hosted in Google Hosted Libraries

### ISSUE THREAD

**Issue by jaGarcia** [angular/material#7783]
Latest release isn't yet uploaded to the hosted libraries.  I wasn't sure if this was intentional or if the auto-deploy script to push the built library up there wasn't working..?

**Comment by Phr33d0m** [comment]
I believe this is intentional, as -rc states this is a release candidate, not a release itself. It should serve testing purposes only, thus it's not at the Google Hosted Libraries.

**Comment by jaGarcia** [comment]
Hmm, 1.0.6 is missing as well so I wasn't sure but yeah, that makes sense.

**Comment by Phr33d0m** [comment]
Hmm true that. For the time being you could use [cdnjs](https://cdnjs.com/libraries/angular-material/1.1.0-rc1) which I switched quite sime time ago to.

**Comment by ThomasBurleson** [comment]
https://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js is available... as well as rc3, etc.

> There does appear to be an issue that they are not listed properly. However they are available for download.
