### ISSUE TITLE
iOS: mechanical md-sidenav (menu) scrolling 

### ISSUE THREAD

**Issue by Hammild** [angular/material#7786]
Scrolling in the md-sidenav menu in iOS is very mechanical compared to Android. On an Android device, a scroll will decelerate before it comes to a halt. On a iOS device, a scroll stops abruptly which is in conflict with the guidelines [(MD-Mass and weight)](https://www.google.com/design/spec/animation/authentic-motion.html#authentic-motion-mass-weight).

How to reproduce:
1. Open the md-sidenav menu (not the sidenav component)
2. Open the "Demo"-accordian to make the md-sidenav scrollable
3. Scroll up and down
4. Observe that the scroll stops instantly when using a iOS device

Tested on:
Version: Angular Material 1.1.0-RC1
Model: iPad mini
Browser: Safari 9.3
Operating system: 9.3 (13E237)

Tested on:
Version: Angular Material 1.1.0-RC1
Model: iPhone 6
Browser: Safari 9.3
Operating system: 9.3 (13E233)

**Comment by crisbeto** [comment]
Wasn't aware that we had this on sidenav as well, I added https://github.com/angular/material/pull/7751 recently to address the same issue on the demos. I'll take care of this one.
