### ISSUE TITLE
Setting all Sass variables to !default

### ISSUE THREAD

**Issue by bradrich** [angular/material#7788]
There are several Sass variables in the angular-material.scss file that are not set with the **!default** indicator. This means that if you try to define the variable before you import the angular-material.scss file in order to overwrite the variable, it will fail to do so. One reference to this are the tooltip variable declarations.

It would also be nice if the angular-material.scss file could be written with a more semantic approach, splitting the file into several such as variables, global, input, tooltip, etc, i.e. how Bootstrap or Foundation organize their Sass files.

**Comment by DevVersion** [comment]
I just filtered for all variables, which are not set with `!default`.

- `$font-size:   10px;`
- `$button-left-right-padding: rem(0.600);`
- `$app-bar-height: 64px;`
- `$shadow-key-umbra-opacity:      0.2;`
- `$shadow-key-penumbra-opacity:   0.14;`
- `$shadow-ambient-shadow-opacity: 0.12;`
- `$autocomplete-option-height: 48px;`
- `$button-icon-border-radius: $button-fab-border-radius;`
- `$md-calendar-header-height: 40px;`
- `$md-calendar-scroll-cue-shadow-radius: 6px;`
- `$md-calendar-width: (7 * $md-calendar-cell-size) + (2 * $md-calendar-side-padding);`
- `$md-date-arrow-size: 5px;`
- `$dialog-padding: $baseline-grid * 3;`
- `$input-label-float-width: $input-container-padding + 16px;`
- `$input-error-line-height: $input-error-font-size + 2px;`
- `$error-padding-top: ($input-error-height - $input-error-line-height) / 2;`
- `$icon-top-offset: ($icon-offset - $input-padding-top - $input-border-width-focused) / 4;`
- `$menu-border-radius: 2px;`
- `$max-visible-items: 6;`
- `$menu-item-height: 6 * $baseline-grid;`
- `$dense-menu-item-height: 4 * $baseline-grid;`
- `$max-menu-height: 2 * $baseline-grid + $max-visible-items * $menu-item-height;`
- `$max-dense-menu-height: 2 * $baseline-grid + $max-visible-items * $dense-menu-item-height;`
- `$radio-margin: 16px;`
- `$select-option-height: 48px;`
- `$select-option-padding: 16px;`
- `$select-container-padding: 16px;`
- `$select-container-transition-duration: 350ms;`
- `$select-max-visible-options: 5;`
- `$md-toast-content-padding: 3 * $baseline-grid - $button-left-right-padding;`
- `$md-toast-button-left-margin: 3 * $baseline-grid - 2 * $button-left-right-padding;`
- `$md-toast-text-padding: $button-left-right-padding;`
- `$tooltip-fontsize-lg: rem(1);`
- `$tooltip-fontsize-sm: rem(1.4);`
- `$tooltip-height-lg: rem(2.2);`
- `$tooltip-height-sm: rem(3.2);`
- `$tooltip-top-margin-lg: rem(1.4);`
- `$tooltip-top-margin-sm: rem(2.4);`
- `$tooltip-lr-padding-lg: rem(0.8);`
- `$tooltip-lr-padding-sm: rem(1.6);`
- `$tooltip-max-width: rem(3.20);`
- `$virtual-repeat-scrollbar-width: 16px;`
