### ISSUE TITLE
Feature request for mdTabs/mdTab: async tab switching

### ISSUE THREAD

**Issue by scanspeak** [angular/material#7795]
Right now the tab switching is synchronous, with mdOnDeselect and mdOnSelect evaluation for deselected and selected tabs respectively.

I think it would be useful to have an option of asynchronous switching, when the mdOnDeselect or/and mdOnSelect return a promise, which can be resolved or rejected. In case of rejection the switching is canceled. It's also nice to show a loading indicator while the promise is being resolved.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by scanspeak** [comment]
It is very easy to close the issue. In other words, you are saying "don't use angular material".

We have very complicated form consisting of a set of tabs, each of them has some async functionality. This functionality is impossible to implement with tabs which does not support async switch.

Think about consistency. Part of the controls do support async mode of work, others do not.
I am very disappointed. Today I do not see how the Angular Material can be a part of some serious application.
