### ISSUE TITLE
Layout issue in md-datepicker footer

### ISSUE THREAD

**Issue by jexneedls** [angular/material#7796]
I'm getting layout issue with md-datepicker whenever the container of the md-datepicker exceeds the viewport (check number 1 on screenshot). But when the container is in the viewport issue doesnt occur (check number 2 on screenshot). So I'm thinking this has to do with the md-scroll-mask.

![md-datepicker](https://cloud.githubusercontent.com/assets/14348836/14129028/22c32d5c-f5f4-11e5-8987-097718ea9255.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
