### ISSUE TITLE
Checkbox not working properly

### ISSUE THREAD

**Issue by JamesWangSaiBong** [angular/material#7797]
Somehow, I can't toggle the checkbox directly in the following code. But when I click the anchor tag beside it which shares the same function, it's able to update the model binded to the checkbox, and update the view properly. This may just be a little mistake that I have done, but I am not sure as it had me wondering for hours already. 

`<div layout="row" class="choices-list-header">
			<md-checkbox class="md-warn" ng-model="allSelected" ng-change="selectAll()" aria-label="Select all choices"></md-checkbox>
			<a ng-click="selectAll()">Select All</a>
		</div>`
`// Select All
	$scope.allSelected = false;
	
	$scope.selectAll = function() {
		$scope.allSelected = !$scope.allSelected;
	}`

Can someone please kindly help?

**Comment by tstephansen** [comment]
I had a similar issue and couldn't figure out a way to do it through code. I ended up calling the click method from the code. The code may not work as is (I tried to strip it out from a much larger function) but hopefully it will give you a good place to start. If I have time in the morning I'll make a plunker. Depending on how your code is written you may just be able to use a $timeout and make it work. I hope this helps.

`var checks = $('md-checkbox');`
`var allChecks = $('#whateverDivContainsYourCheckBoxes').find(checks);`
`$.each(allChecks, (index, item){
    $timeout(function(){
        $(item).click();
    }
}
`

**Comment by jayeshanandani** [comment]
A demo link for this will be appreciated!

**Comment by crisbeto** [comment]
Without having seen this in action, I assume that what's happening is that the `ng-click` is executing and flipping the value, but the `ng-change` kicks in afterwards and flips the value back.

**Comment by Phr33d0m** [comment]
If I had to guess without testing it out - when you click on the checkbox, the ngModel toggles ```selectAll``` to ```true``` then ngChange fires up the ```selectAll()``` function and changes ```selectAll``` back to ```false```. If you fire up the anchor it works because it only calls the ```selectAll()``` function.

**Comment by JamesWangSaiBong** [comment]
@Phr33d0m I'm not sure if that's the case. Since ng-model refers to allSelected, which is simply a boolean, I am unsure where the double-firing would come from.

@jayeshanandani I will create a fiddle/plunkr for this later when I have more time because I somehow got it working again after adding more stuff to my controller. I am not 100% sure why it didn't work before, and why it is working now, so I would like to figure it out.

**Comment by tstephansen** [comment]
This is what I was talking about. It probably (99% sure it isn't) the best way to do this but it works in my case. [example](https://github.com/tstephansen/md-checkbox-Example)

**Comment by ThomasBurleson** [comment]
Closing as invalid without CodePen Demo.
