### ISSUE TITLE
Add feature to scroll paged tabs by swipe.

### ISSUE THREAD

**Issue by dlinx** [angular/material#7799]
In current implementation, we can scroll through paged tabs using navigation buttons. It will be good if user can swipe and scroll through tabs. After swipe it scrolls full page but doesn't allow to scroll like a page.

**Comment by DevVersion** [comment]
@dlinx Sorry, I didn't get your actual issue. Are you requesting `swipe` or `drag` support?

- `swipe` is currently available.

**Comment by dlinx** [comment]
@DevVersion , Swipe is currently available, but if you swipe, it change page, which is bit confusing for user. But if tabs moves with touch move, then it will be better experience. just like scroll bar.
Just think, if scrollbar  scrolls one page instead of line, then user will loose his context, what he was looking for.
I am just requesting a feature, when user drag any tab, the effect need to be similar like page scroll smoothly.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
        For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
