### ISSUE TITLE
mdMenu: a menu component

### ISSUE THREAD

**Issue by ajoslin** [angular/material#78]
Specification for [Menus](http://www.google.com/design/spec/components/menus.html#menus-usage)

![image](https://cloud.githubusercontent.com/assets/210413/4068377/515151ec-2e38-11e4-9b7c-548144f2a86a.png)

**Comment by sondreb** [comment]
Have anyone started implementing the menu component in any of the branches? Can't find any branches that mentions "menu"...

**Comment by borgdylan** [comment]
I did not know of lumx. However lumx does not have cards and other stuff i need in my app. Plus angular-material comes from google directly and implements certain animations better like the ones of text-fields.

**Comment by karol-f** [comment]
@borgdylan Sure, matter of prefference. Hovewer I can see that cards are available (CSS category in menu) - http://ui.lumapps.com/css/cards . Regards.

**Comment by borgdylan** [comment]
thanks. lumx appears to be complete.

**Comment by sondreb** [comment]
Thanks for the tip on LumX, it appears to be a bit more complete than AngularMd. I've spent a bunch of time implementing AngularMd, learning it and everything. Might convert to LumX until AngularMd matures.

**Comment by mackelito** [comment]
LumX seems good.. except for the jQuery dependency :/

**Comment by hatpick** [comment]
LumX looks awesome, that multi-select directive is a killer feature.

**Comment by mackelito** [comment]
Still.. the dependency is what will make me not use it :P

**Comment by Telemakhos** [comment]
+1

**Comment by borgdylan** [comment]
Is there an indication of when the menu component  will be added?

**Comment by fabiusss** [comment]
+1

**Comment by gyss** [comment]
+1;

**Comment by dg1202** [comment]
+1

**Comment by ThomasBurleson** [comment]
We will be working on the Menu component for Milestone 0.9
Currently we are working on Milestone 0.8 to release autoComplete, select,
Gridlist, and icon components.

**Comment by mackelito** [comment]
Awesome!... btw, love the work grid component!... This framework is just so sweet! :)

**Comment by DBGTTECHJAM** [comment]
+1

**Comment by ThomasBurleson** [comment]
Angular Material is really maturing: we still want to deliver [to the
community] Select, Menu, Speed Dial, Dialog/Toast stacking and queue, Date
Picker and more... stay tuned!

**Comment by Lunatic83** [comment]
+1

**Comment by borey** [comment]
+1

**Comment by m4cx** [comment]
+1

**Comment by ask007java** [comment]
+1

**Comment by bendo01** [comment]
+1

**Comment by mzry1992** [comment]
+1

**Comment by eclipse1985** [comment]
+1

**Comment by dotTwelve** [comment]
oneplus!

**Comment by ross-nordstrom** [comment]
+1

**Comment by andreabadesso** [comment]
+1

**Comment by mib4fun** [comment]
+1

**Comment by sunnyshah01** [comment]
+1

**Comment by mobelio** [comment]
+1

**Comment by kschwidder** [comment]
Date/Time Picker +1

**Comment by colinskow** [comment]
+1

**Comment by vlopez5** [comment]
+1

**Comment by janesconference** [comment]
Menu has been now postponed to 0.10.0 It will be available in April if it doesn't shift again (which has been the norm for the Menu component since 0.4). It's one of the most requested component and a blocker for most people. Every other material library has it. I don't really want to discuss Angular Material's priorities, but why such an important component does always get relegated to such a low priority?

**Comment by vlopez5** [comment]
@janesconference +1

**Comment by maelfrize** [comment]
+1

**Comment by kschwidder** [comment]
+1
The same with the Date/Time Picker ! (Both are used heavily in apps)

**Comment by ereztison** [comment]
+1

**Comment by MarijnMensinga** [comment]
+1

**Comment by clalag** [comment]
+1

**Comment by dg1202** [comment]
+1

**Comment by demisx** [comment]
I've already sold my soul for `md-select`. If I had two,  I would give it up for `md-menu'`.

**Comment by jaoued** [comment]
+1

**Comment by dmackerman** [comment]
Menu would be awesome.

**Comment by borey** [comment]
+1 
Wish it's out soon.

**Comment by emadgh** [comment]
+1 :+1:
This is one of my wishes

**Comment by emadgh** [comment]
+1 :+1:
This is one of my wishes

**Comment by marcramser** [comment]
+1

**Comment by janesconference** [comment]
Postponed again, lol.

**Comment by ThomasBurleson** [comment]
@janesconference  - We announced at ng-Conf that our team focus for the 0.9 release would be:

*  issue resolution
*  performance
*  device support
*  polish

This is what the team focused on for 0.7; and the 0.8 release revealed major new components and features. This cyclical focus on component and polish has been very successful. New components and features will be available for 0.10.0.

**Comment by demisx** [comment]
In the meantime, I wonder if there a good way to mimic the `md-menu` component with `md-select` maybe?

**Comment by joselo** [comment]
Thanks for the hard job  :)

**Comment by Nowis** [comment]
same as demisx. 
A way to do a menu with md-select ?

**Comment by SummerWish** [comment]
+1

**Comment by solenovex** [comment]
+1

**Comment by offminded** [comment]
+1

**Comment by leibale** [comment]
+1

**Comment by imjoeybrennan** [comment]
+1

**Comment by benbeadle** [comment]
+1

**Comment by daw451-duplicate** [comment]
+1

**Comment by marduke182** [comment]
+1

**Comment by audleman** [comment]
:+1:

**Comment by gpopovic** [comment]
+1

**Comment by EladBezalel** [comment]
+1 any wip on this?

**Comment by ThomasBurleson** [comment]
@all - Menu implementation is starting **this** week.

**Comment by dotTwelve** [comment]
+cool

Dne út 7. 4. 2015 14:15 u¾ivatel Thomas Burleson <notifications@github.com>
napsal:

**Comment by vlopez5** [comment]
Thank you!

**Comment by m99coder** [comment]
Appreciate this really much! Thanks a lot.

**Comment by smitty02001** [comment]
Thank You ThomasBurleson. Will the menu be able to display md-select inside it?

**Comment by dotTwelve** [comment]
Dropdown menu will display a select menu inside ;-)

Dne st 8. 4. 2015 17:46 uživatel smitty02001 <notifications@github.com>
napsal:

Thank You ThomasBurleson. Will the menu be able to display md-select inside

**Comment by ivks** [comment]
+1.
Thank you for the update. Any probable date for the release of menu component. 
I know seeing the history of conversation, you guys would not like to comment on the timeline.
But it would be really helpful for lot of us. 

Also a question for the team, what you would have used instead of menu component?
Just wanted to know what is the best approach I can take for now.

**Comment by goncaloneves** [comment]
+ 1.

Thanks for the update. Terrific time !

**Comment by dmackerman** [comment]
Fantastic! Thanks for the update.

**Comment by dhawken** [comment]
Sweet.  Looking forward to it.

On Thu, Apr 9, 2015 at 8:57 AM, Dave Ackerman <notifications@github.com>
wrote:

> Fantastic! Thanks for the update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/78#issuecomment-91222783>.
>



-- 
*Most people have more than the average number of legs*

**Comment by ThomasBurleson** [comment]
@all - everyone has been very patient and support of our efforts. Thank you. 
@rschmukler  is leading the effort on the Menu implementation... I am sure everyone will love his results.

**Comment by ThomasBurleson** [comment]
@rschmukler  - another example of menu with important features: 

* headers
* dividers
* selection indicators

![menuwithheader](https://cloud.githubusercontent.com/assets/210413/7107138/e6786874-e11f-11e4-8c07-938c665a6fae.png)

**Comment by m99coder** [comment]
Can’t wait to use it in real world. Thanks a lot.

+1

**Comment by ivks** [comment]
Wow!!
Was not expecting so much to be delivered in the first version, looking forward to it.
@rschmukler Thanks for your effort. :smile:

**Comment by EladBezalel** [comment]
I'd love if you'll update when a minimal work has done

**Comment by rschmukler** [comment]
@ThomasBurleson please ask the UX team regarding spec on headers in menus on desktop

**Comment by victormacae** [comment]
+1

**Comment by fnlctrl** [comment]
+1

**Comment by luclanet** [comment]
+1

**Comment by janesconference** [comment]
Thanks @ThomasBurleson and @rschmukler.
Since this finally started 2 weeks ago, is there a branch that we can check out to start integrate & track progress?

**Comment by rschmukler** [comment]
@janesconference we've been mostly focused on `0.9.0` issues that have popped up since the RCs shipped. Will keep you updated as things progress.

**Comment by vko-online** [comment]
+1

**Comment by geovanisouza92** [comment]
+1

**Comment by victormacae** [comment]
+1

**Comment by rashidi** [comment]
:+1:

**Comment by Polyethylene** [comment]
+1

**Comment by anderson-arlen** [comment]
+1

**Comment by spuleri** [comment]
+1

**Comment by ishener** [comment]
+1

**Comment by vanntian** [comment]
+1

**Comment by swapnilsm** [comment]
+1

**Comment by skeenan** [comment]
+1

**Comment by kevindstanley1988** [comment]
+1

**Comment by PavelKonon** [comment]
+1

**Comment by TommyM** [comment]
+1

**Comment by pdf13** [comment]
+1

**Comment by redyyu** [comment]
I temporary build a rough module, ng-material-dropmenu
It's modify by ng-select (no ng-model required). 
If some one need you can git here https://github.com/Soopro/ng-material-dropmenu
=====================
*** Those content for the tens of thousands of Chinese developer who can't read english. ignore if you are not :) ***

我等不及官方出正式的ng-menu 下拉菜單, 於是我拿 ng-select 山寨了一個，如果你也等不及，就拿這個去先湊合用。回頭等他們出了再換。
https://github.com/Soopro/ng-material-dropmenu

=====================
### Idea of ng-menu
The old school drop menu (etc., bootstrap) some problem you always have deal with:
1. The button is too short but the item in menu is long. drop menu should be fixed width?
2. Where is the drop menu should popup, sticky with the button? what if the popup is impassable fit the screen? do some custom responsive when you use drop menu ?
3. The 'drop' from top or bottom or even left or right should define by custom?
4. What happen you have submenu? or sub-sub-sub...menu?

In my project, the bootstrap way is work on desktop (large screen).
but I had do many custom work for responsive. (wrote some directives.)

When I saw ng-select, I love it. the position will adjust automatically. the behavior is pretty much full fill my need, so I copy a ng-select and do some modify to make a my fake drop menu.

I hope the 'ng-menu' can do:
1. something like ng-select while on sm screen.
2. maybe new way to make sub-menu.
3. automatic responsive for any screen.
4. able to stuff everything in side(no just limit with item like ng-option).

btw: I hope we can get more Theme api support custom ng-material module.

**Comment by no-more** [comment]
+1

**Comment by hays88** [comment]
+1

**Comment by saystone** [comment]
:+1:

**Comment by masterakos** [comment]
+1

**Comment by amanjain** [comment]
@ThomasBurleson milestone 0.10.0 seems to be due by May 12, 2015. Should we expect this feature in 0.10.0?

**Comment by janesconference** [comment]
@amanjain: I don't speak officially, but I reckon that yes, we should expect it in 0.10.0, but the milestone date is more indicative than a strict deadline and it will be inevitably delayed (there are 270 issues, and 0.9, which delayed everything, had almost 500) .

**Comment by redyyu** [comment]
I think any other developer can write module by their own, if 2 thing is ready:
1. Theme for module api **this one is mostly important.
2. Documents of low level ($$) providers api.

**Comment by macbury** [comment]
+1

**Comment by ThomasBurleson** [comment]
The Angular Material Menu component will be delivered in 3-phases:

1) Menu dropdown; with optional icons
2) Menu bar and Cascaded menu
3) Menus with shortcuts/keyboard equivalents

We plan to have Menu - Phase 1 in `master` next week.

**Comment by no-more** [comment]
That's a great news! thanks!

**Comment by vanntian** [comment]
@ThomasBurleson awesome!can't wait

**Comment by luclanet** [comment]
Yeeeeaaaahhhh!!!

**Comment by janesconference** [comment]
> Menu bar
@ThomasBurleson  What is the menu bar exactly? Like an horizontal toolbar containing buttons / icons that, on click, generate dropdown menus?

> Menu dropdown; with optional icons
Will it integrate with hamburger icons at the end of a list item or is this a feature that comes in 2?

**Comment by ThomasBurleson** [comment]
@janesconference 

1[Menu Bar](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0Bx4BSt6jniD7VW5LS2JTQ2puOUE/components_menus_usage3do.png)

**Comment by adrianandreias** [comment]
@ThomasBurleson great news!

How about a left main menu part of a sidenav(i.e. left menu in documentation)? In which of the phases would this fit?

**Comment by lucasloliveira** [comment]
Great work! Waiting for the update :smile:  :+1:

**Comment by sars** [comment]
+1

**Comment by dwanderton** [comment]
+1 Cant come soon enough @ThomasBurleson thanks for all your work on this I cant wait to get stuck in.

**Comment by dotTwelve** [comment]
Where is it? ;-)

**Comment by ThomasBurleson** [comment]
We are currently hyper-focused on  a summer release for Angular Material v1.0; which will include Menu and DateTimePicker components, performance enhancements, bug fixes, and improved documentation.

As mentioned earlier, the Menu will be delivered in three (3) Phases:

*  Phase 1 will be included in the upcoming v0.10 release. 
*  Phase 2-3 are targeted for v0.11.

> So we can maintain focus, we are locking this issue for now... it will remain an **open** issue, but locked to future discussions. Please future discussions in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by ThomasBurleson** [comment]
These features are currently in Master and will be published with Release v0.11
