### ISSUE TITLE
<md-autocomplete> does not contain a "clear" icon when "md-floating-label" attribute is used

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#7800]
See [codepen](http://codepen.io/cmacdonnacha/pen/dMzZVZ?editors=1010)

The **md-autocomplete** component contains a "clear" icon once text is present. However, if the **md-floating-label** attribute label is applied the "clear" icon is not displayed. 

![image](https://cloud.githubusercontent.com/assets/9777763/14138514/889a510c-f665-11e5-862a-665fc3685578.png)

**Comment by DevVersion** [comment]
This is currently by intention. (See [here](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteDirective.js#L259-L290)). 

I think was removed from floating label autocomplete's, because they should look like normal inputs.

**Comment by cmacdonnacha** [comment]
Thanks for your reply. Is there any way this can be added as an option to display the "clear" button? Hidden by default.

**Comment by cmacdonnacha** [comment]
@DevVersion  Or is there any other way to have the functionality of the **autocomplete** component and have the styling of the **md-input** component which includes the "clear" button?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
