### ISSUE TITLE
<md-autocomplete> should propagate disable-validation-message=""

### ISSUE THREAD

**Issue by biancarosa** [angular/material#7801]
I have a `disable-validation-message=""` attribute in `<md-autocomplete>` that is not appearing the generated input:

`<input flex="" type="search" id="input-0" name="" ng-if="!floatingLabel" autocomplete="off" ng-required="$mdAutocompleteCtrl.isRequired" ng-disabled="$mdAutocompleteCtrl.isDisabled" ng-model="$mdAutocompleteCtrl.scope.searchText" ng-keydown="$mdAutocompleteCtrl.keydown($event)" ng-blur="$mdAutocompleteCtrl.blur()" ng-focus="$mdAutocompleteCtrl.focus()" placeholder="Condominium" aria-owns="ul-0" aria-label="Condominium" aria-autocomplete="list" aria-haspopup="true" aria-activedescendant="" aria-expanded="false" class="ng-pristine ng-untouched ng-scope ng-empty ng-invalid ng-invalid-required flex" required="required" aria-invalid="true">`

I am warning the user only through a red border-box and I'm having to hide the message through CSS.

**Comment by mckenzielong** [comment]
Could be slightly related to https://github.com/angular/material/issues/6544? I had to implement custom autocomplete validation messages recently, and it was not a fun experience.

**Comment by biancarosa** [comment]
I am not sure if it's related. Seems like a different issue to me.

The field is being validated correctly (I am using `jcs-autovalidate`) and the proper message is showing up, but I wanna disable it and the property `disable-validation-message=""` should be carried along to the input in order to do so.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
