### ISSUE TITLE
md-autocomplete and mdDialog

### ISSUE THREAD

**Issue by Bazys** [angular/material#7802]
md-autocomplete `<md-not-found>` don`t hide when using mdDialog

<img width="912" alt="screen shot 2016-03-30 at 16 26 46" src="https://cloud.githubusercontent.com/assets/5006008/14143506/4e113346-f694-11e5-87fe-9c6eb0466438.png">

See [codepen](http://codepen.io/anon/pen/EKvQvB)

**Comment by DevVersion** [comment]
Just investigated a bit and it seems to be pretty difficult to solve that, because we need to detect whether the dropdown should hide from the last interaction.

Here is some code which works, but it is delayed, because the dialog focuses its element after animation.

```js
  function blur () {
    hasFocus = false;

    if (!noBlur || notFoundVisible() && !isMouseInteraction) {
      ctrl.hidden = shouldHide();
    }
  }
```

**Comment by DevVersion** [comment]
Merging this issue into #9456
