### ISSUE TITLE
Text overlaps with md-select

### ISSUE THREAD

**Issue by Sarpedion** [angular/material#7806]
After clearing selection in md-select, by selecting null value, floating text remains and overlaps with label.

Quick codepen:
http://codepen.io/Sarpedion/pen/VazXQQ

**Comment by jayeshanandani** [comment]
I believe there is some issue for this already opened somewhere.

**Comment by jayeshanandani** [comment]
I think this is similar to #7398 and seems to be fixed in master.

**Comment by Sarpedion** [comment]
That is correct, thank you for sharing. Closing issue.
