### ISSUE TITLE
Docs examples available locally

### ISSUE THREAD

**Issue by noilly** [angular/material#7812]
I know this is obvious, however the CodePen examples are not available when viewing the docs offline, i.e., viewing a local build of the docs without a connection to the Internet.

I am having to write code offline and somehow being able to have access to these examples within the context of the docs would be very useful.

**Comment by ThomasBurleson** [comment]
You can easily do this with a local clone of this repository `angular/material`:  

```console
npm install;
npm run watch
````

Then open a web page to `http://localhost:8080`

**Comment by noilly** [comment]
@ThomasBurleson When I first tried viewing the CodePen examples through the installed docs, none of them were showing. Just tried again, and they're showing. Thanks!
