### ISSUE TITLE
When a control element is open, clicking on another element should open it immediately

### ISSUE THREAD

**Issue by ArtemEkzarho** [angular/material#7814]
Currently there is an additional click needed to close the first element, and only then the second element is clickable. Example: open the menu on the current page and then click on the other menu.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
