### ISSUE TITLE
md-autocomplete translateY issue in Firefox

### ISSUE THREAD

**Issue by HendrikWansing** [angular/material#7816]
Hello,

we have an issue with the md-autocomplete / md-virtual-repeat in Firefox. 
The issue is reproduceable in the demo: 
https://material.angularjs.org/latest/demo/autocomplete (Basic Usage).

Steps to reproduce it:
1. Open a md-autocomplete
2. Scroll to the bottom of the md-virtual-repeat
3. Close and open md-autocomplete a few times till the md-virtual-repeat is blank.

It happens that the value of translateY is 0 but we have scrolled to the bottom, before.
If you scroll in the blank container, the list items will appear again.

Best regards
Hendrik

**Comment by crisbeto** [comment]
I could reproduce it as well, seems pretty weird.

**Comment by ThomasBurleson** [comment]
will not fix. PR Welcome.
