### ISSUE TITLE
mdMenu: Cannot read property 'open' of null

### ISSUE THREAD

**Issue by nkeeslin** [angular/material#7819]
On mdMenu, if you have a sub menu and another item that doesn't have a submenu in the same menu. If you open the subMenu and then hover over the non-subMenu item it throws the error "Cannot read property 'open' of null" and remains highlighted even after hovering over a different menu item

angular material version: 1.1.0-rc1
browser: chrome 49.0.2623.87

I also tested this on the demo page for the latest version on the angular material website and I'm getting the same error

**Comment by crisbeto** [comment]
I couldn't reproduce it, could you give a little bit more detail about what you're clicking and hovering etc.

**Comment by nkeeslin** [comment]
Go to the demo at https://material.angularjs.org/1.1.0-rc2/demo/menuBar

Open the File Menu.  Hover over the "New" menu until it opens.  Then hover over the "Open..." menu item.  If you have your developer console open you should see TypeError: Cannot read property 'open' of null.  Then if you try to go back and hover over something else, the "Open..." menu item ill remain highlighted until you click on another menu item.

**Comment by crisbeto** [comment]
Thanks, now I got it. I'll take a look at it a little bit later.
