### ISSUE TITLE
md-content to take 100% of the available vertical height

### ISSUE THREAD

**Issue by prasannapattam** [angular/material#782]
It would be a nice feature if md-content takes 100% of the available vertical space. Currently I am using the current offset and height of the window for setting the height of the md-content.

**Comment by brutto** [comment]
@sondreb  you save my day! Thanks alot

**Comment by pmdusso** [comment]
Hi, the solution from @sondreb did not worked for me. I have the following scenario:
```
<div style="height:100%">

    <md-button id="mdAdd" class="md-fab md-raised md-primary" ng-click="showDialog($event)">
        <md-icon icon="bower_components/material-design-icons/content/svg/production/ic_add_24px.svg"
                 style="width: 24px; height: 24px; fill:white"></md-icon>
    </md-button>

    <div layout="row" layout-align="space-between center">
        <!-- Left column, with the farm tile and card list -->
        <div flex>
            <!-- Title and Search box -->
            <div flex layout="row" layout-align="space-between center">
                ...
            </div>

            <div layout="row" flex>
                <md-content style="height: 100%; background-color: #ececec" flex>
                    <div layout="row" layout-align="space-between center top">
                        <!-- cards -->
                        <md-list ... >
                        <div flex="5"/>
                    </div>
                </md-content>
            </div>
        </div>
        <!-- Right column, with the map -->
        <div flex="50">
            <!-- MAP -->
            <ui-gmap-google-map center='mapOptions.center' zoom='mapOptions.zoom' options='mapOptions.options'
                                control="mapControl" flex="50">
            </ui-gmap-google-map>
        </div>
    </div>
</div>
```
This markup results in the following screen, with the md-content expanding to fit all cards:
![selection_041](https://cloud.githubusercontent.com/assets/834751/6171057/d9626c86-b2bf-11e4-886e-34e7ea68e094.png)

However, I would like it to be limited by the size of the screen as in this picture (where I defined the height in pixels to take the picture):
![selection_040](https://cloud.githubusercontent.com/assets/834751/6171079/efcb470e-b2bf-11e4-9d3e-762b5bf56b79.png)

Where can I work on?

**Comment by CavemanNinja** [comment]
@sondreb 's solution only works for me if I removed the fixed height I had set on md-content. Problem is when I remove that md-content does not scroll.

**Comment by pmdusso** [comment]
We further discusse this topic (and found some solutions) in the google group: https://groups.google.com/forum/#!topic/ngmaterial/FzyZXYdcPBk

**Comment by yarsh** [comment]
See a (somewhat hacky) solution for full-height md-tabs here: http://stackoverflow.com/questions/30314441/angularjs-material-tab-height-issue/37856853#37856853

**Comment by wingoku** [comment]
@pmdusso How did you resolve the mentioned problem?

**Comment by sukhveersingh** [comment]
.example-container {
    position: absolute;
    min-height: 100% !important;
    
}

add this class to <md-sidenav-container> will resolve the issue

**Comment by moleisking** [comment]
.app-component-filler {  
  min-height: 100vh
}

**Comment by leiradk** [comment]
try this guys
.divclass{
height: inherit;
min-height: 275px;
max-height: 600px;
}
