### ISSUE TITLE
Md-menu icons alignment problem in Firefox

### ISSUE THREAD

**Issue by manish2535** [angular/material#7824]
![1](https://cloud.githubusercontent.com/assets/4663798/14186865/749fa7ee-f74e-11e5-99a2-e346ca837466.JPG)

In Firefox the icons in md-menu is not aligned properly. 

**fix:**
```
md-menu-item > .md-button {
	display: inline;
}
```

**Comment by andrew-mc** [comment]
I also noticed this - after a quick look at the SCSS for md-menu it looks like it was broken in https://github.com/angular/material/commit/34f2704c8a004c98ecece39313249ed5e2caa72a

Similar issues were previously mentioned in https://github.com/angular/material/issues/3292 and  https://github.com/angular/material/issues/4070 and fixed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
