### ISSUE TITLE
anchor uses incorrect accent color if using `setDefaultTheme('custom-theme')`

### ISSUE THREAD

**Issue by ilovett** [angular/material#7827]
Defining `accentPalette` directly on the default theme will work:
```
$mdThemingProvider.theme('default').accentPalette('green');
```
However attempting to set the default theme to a custom one will not carry the changes over:
```
$mdThemingProvider.theme('custom-theme').accentPalette('green');
$mdThemingProvider.setDefaultTheme('custom-theme');
```
In particular, anchor tags use the accent color which will be green only using the first method.
```
a.md-THEME_NAME-theme:not(.md-button) {
  color: '{{accent-color}}';
}
```
Additionally, setting `<a href="#" md-theme="custom-theme">derp</a>` does not add the corresponding theme class name to the element.

**Comment by tenshiAMD** [comment]
+1

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
