### ISSUE TITLE
md-autocomplete md-menu-class does not change width of menu list

### ISSUE THREAD

**Issue by artemjackson** [angular/material#7836]
I'd like to have `md-autocomple` input of width 200px and dropdown menu of width 400px
Addition of `md-menu-class` does not solve the problem.
Codepan eample(first exmple from https://material.angularjs.org/latest/demo/autocomplete with just `md-menu-class` added):
http://codepen.io/anon/pen/dMVNvW

How should I do that in the right way?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
