### ISSUE TITLE
md-select: docs error on multiple attribute

### ISSUE THREAD

**Issue by lordfuoco** [angular/material#7840]
In the docs it's reported that the attribute to add to achieve multiple item selection is multiple.

While adding multiple trigger the behaviour the correct attribute to add is ng-multiple, that support  a boolean to be configured. Also inspecting the code it result that the code is checking for ng-multiple. and adding the attribute multiple when needed.

Line 338 of select.js ( 1.0.6 )

`attr.$observe('ngMultiple', function(val) { .. }`

Ps: I have made the change on my local fork.. line 37 col 22 add ng- but the process for submitting a pull request is too time consuming for such a minor fix.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
