### ISSUE TITLE
Grey background for disabled md-autocomplete

### ISSUE THREAD

**Issue by calebegg** [angular/material#7841]
Disabled md-autocomplete instances with the default theme and with md-floating-label have a weird gray background:

http://codepen.io/calebegg/pen/yOzXYw

![image](https://cloud.githubusercontent.com/assets/782920/14214240/f703a0bc-f809-11e5-9aac-bb97517adea1.png)

**Comment by crisbeto** [comment]
Should be a quick fix, I'll take care of it.
