### ISSUE TITLE
mdComponentRegistry only allow one .when

### ISSUE THREAD

**Issue by trainerbill** [angular/material#7846]
https://github.com/angular/material/blob/master/src/core/services/registry/componentRegistry.js#L105

Not sure if this is intended or not but I have multiple places where I need to wait for a component.  It would be nice if .when would push the promise onto an array and resolve them all when the instance is ready.  If this is intended what is your recommendation?  I would rather not create a service that executes it and my controllers wait on my service.

I can PR it if it is something that should be supported.

PR https://github.com/angular/material/pull/7847

**Comment by trainerbill** [comment]
https://github.com/angular/material/pull/7847

**Comment by DevVersion** [comment]
Fixed with SHA 7988cf60fa86d081ba0b3b4efbaeca86059ce91b
