### ISSUE TITLE
Swipe not sensitive enough

### ISSUE THREAD

**Issue by code-tree** [angular/material#7855]
I've found the `minVelocity` setting (0.65) for swipe gesture to not be sensitive enough. I'm currently trying out a setting of 0.3, which feels much more natural. Could swipe sensitivity be increased, or at least made configurable?

e.g. `md-swipe-content="3"` taking into account both minVelocity & minDistance

**Comment by crisbeto** [comment]
I'd say it makes sense to have it configurable.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
