### ISSUE TITLE
Margin problem with md-input-container inside a row, followed by md-input-container outside the row

### ISSUE THREAD

**Issue by stephengardner** [angular/material#7859]
When putting `md-input-container` inside a `div layout="row"` followed by a `md-input-container` outside of that row, the margins are doubled due to the `div layout="row"`.  Is there a documented class based structure for having some `md-input-container`s inside a `div layout='row'` and some outside the row? 

The spacing issue is even seen in the docs.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
