### ISSUE TITLE
mdSelect: values overlap and have no ellipses

### ISSUE THREAD

**Issue by tenshiAMD** [angular/material#7865]
md-select with multiple values cause overlaps and have no ellipses when selected items are too many for the md-input-container 

The issue is the in the selection of items in the md-select does not have an ellipses and causes to overlap the next md-select on the left of the first md-select; md-select keeps growing and growing after adding another item.

The example of the issue can be viewed in this codepen: 
- http://codepen.io/tenshiAMD/pen/oxGKyP

**Comment by tenshiAMD** [comment]
I'm using this css fix to patch this issue temporarily:

```
._md-select-value *:first-child {
  width: calc(100% - 24px);
}
```

**Comment by crisbeto** [comment]
Seems legit, you just have a SASS error in your codepen.

**Comment by tenshiAMD** [comment]
Fixed the codepen sass error its just a extra ':' on the first div and does not affect the md-select css at all. I just recreated the scenario on my project where the md-select with multiple value causes this layout misrendered. Check the codepen again. http://codepen.io/tenshiAMD/pen/oxGKyP

**Comment by crisbeto** [comment]
It should be a quick fix, I can take a look at it later today.

**Comment by tenshiAMD** [comment]
Thanks man :+1:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
