### ISSUE TITLE
Using return on md-chips with md-autocomplete on IE 11 causes two items to be added

### ISSUE THREAD

**Issue by ViDaNgEr** [angular/material#7867]
It's the same bug describes as #4996 but it's still there on IE 11.

it's very easy to reproduce:
- Use IE 11
- Go to Angular Material md-chips Demo: https://material.angularjs.org/latest/demo/chips
- In the "Custom Inputs" section, uncheck "Tell the autocomplete to require a match"
- In the "Search for a vegetable" field, type "spi", then the down arrow, then press return.

Et voila.

both "spi" AND "Spinach" will be added.

It seems to only happens on IE, at least in IE 11.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
