### ISSUE TITLE
md-autofocus does not work on md-menu-item > md-button

### ISSUE THREAD

**Issue by isaaclyman** [angular/material#7868]
When using `md-autofocus` with an optional expression (e.g. `md-autofocus="ctrl.a === ctrl.b"`) on an `md-button` that is the direct child of an `md-menu-item`, the `_md-autofocus` class is applied to the compiled `<button>` element, but when the menu opens, focus is given to the first item in the list anyway. It appears that the `md-autofocus` attribute is completely disregarded in this case.

Applying the `md-autofocus` to the `md-menu-item` element itself does not work either. If it is intended behavior that `md-autofocus` does not work for elements in an `md-menu`, this should be documented (and I'd like to know the reason why).

**Comment by DevVersion** [comment]
The problem is, that `md-autofocus` is not the correct attribute for the `menu` component.
- It's `md-menu-focus-target`

In my opinion, we should also support `md-autofocus` here.

http://codepen.io/DevVersion/pen/BKPEBy

**Comment by ThomasBurleson** [comment]
@DevVersion - Agreed. Please add support.
