### ISSUE TITLE
md-content no longer sets background color in 1.1.0-rc*

### ISSUE THREAD

**Issue by hodeyp** [angular/material#7880]
md-content used to define background color based upon theme, and also allowed usage of md-hue-1/2/3. This no longer works. There does not seem to be any way to use theme colours to set application background colours?

**Comment by Phr33d0m** [comment]
This was introduced with 1.1.0-rc1 [with this pullreq](https://github.com/angular/material/pull/7422) but seems to have been restored in -rc2 as per [this CHANGELOG](https://github.com/angular/material/blob/release/1.1.0-rc2/CHANGELOG.md)

**Comment by hodeyp** [comment]
md-hue-1 md-hue-2 md-hue-3 have no effect on the md-content background color on 1.1.0-rc2
