### ISSUE TITLE
md-input-container/input on IE10: click on the label sometimes does not work

### ISSUE THREAD

**Issue by scanspeak** [angular/material#7881]
In general, when the input is empty, click on the label (placeholder) makes the label float up and allows entering data into the input.

It does not work for some fields on my IE10/Win7. Chrome, Firefox, Safari/iPad seem ok.
Example: please see the official [input demo](https://material.angularjs.org/1.1.0-rc2/demo/input). The last section (Icons), the "Email (required)" field. Click on the placeholder text does nothing on IE10. Click on the empty space on the right works as expected.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
