### ISSUE TITLE
md-no-float in md-autocomplete

### ISSUE THREAD

**Issue by Knoxvillekm** [angular/material#7882]
Need to use md-autocomplete with floating style without label. Add md-no-float like in md-input-container.

Or allow empty label or `&nbsp;`

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
