### ISSUE TITLE
md-content no longer allows md-hue-1/2/3 in 1.1.0-rc2

### ISSUE THREAD

**Issue by hodeyp** [angular/material#7886]
md-hue-1 / 2 / 3 all return the same background colour for md-content

looking at the specs https://www.google.com/design/spec/style/color.html#color-text-background-colors

it suggests that I should be able to use hues 50/100/300 on background elements.

**Comment by EladBezalel** [comment]
This is not correct, background is only in one hue, other components have other backgrounds

**Comment by hodeyp** [comment]
@EladBezalel - commit 0df4b16eca2c8af9805615da646d38db04a33d7f a year ago added this functionality and it was removed in last week in commit 4a2c362c3364260ebf04d81f298098412c370eca.

With the latest build it is impossible to use md-content in cards as it defaults the background color to the same as the parent background color.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
        For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
