### ISSUE TITLE
md-button margins in toolbar does not work properly in RTL

### ISSUE THREAD

**Issue by alisabzevari** [angular/material#7887]
`md-button` in toolbar `(dir="rtl")` does not work properly. Here is a sample:
```html
<md-toolbar>
    <div class="md-toolbar-tools">
      <md-button class="md-icon-button" aria-label="Settings">
        <i class="fa fa-bars"></i>
      </md-button>
...
```
the problem is in this ruleset:
`.md-toolbar-tools > .md-button:first-child`

I can create a PR for that.

**Comment by ThomasBurleson** [comment]
@alisabzevari - please do.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by yoav-zibin** [comment]
Hi alisabzevari, did you end up fixing this locally? (because you said you can send a PR)
If so, can you paste the fix in this bug? (I would love to have it and I'm changing the css myself anyway because there won't be any future releases for angular 1.x)

**Comment by yoav-zibin** [comment]
I'm assuming the issue you have is the same as mine:

![image](https://cloud.githubusercontent.com/assets/1890589/21429296/30635c7e-c82c-11e6-8697-60efad765ff7.png)

**Comment by alisabzevari** [comment]
@yoav-zibin My problem has been fixed in the newer versions. Yours should be something else.
