### ISSUE TITLE
mdAutocomplete: Glitch when using floating label and md-min-length="0"

### ISSUE THREAD

**Issue by bernizt** [angular/material#7888]
When clicking on an option while the field is **empty**, the _md-autocomplete_ goes into the empty state before releasing the mouse button. Afterwards, the selected option is copied into the field.
If _md-autocomplete_ is tagged as **required**, the field is shown in the error state (red floating label and line) in between pressing the mouse button and releasing it.

![bug_preview3](https://cloud.githubusercontent.com/assets/6201454/14287509/323a1598-fb53-11e5-857b-34e52e285c51.gif)

Example: [http://codepen.io/anon/pen/jqaYqN](http://codepen.io/anon/pen/jqaYqN)

- Tested with Firefox and Chrome
- Tested for v1.1.0-rc2

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
