### ISSUE TITLE
md-switch doesn't have an option to align text

### ISSUE THREAD

**Issue by johnyricalde** [angular/material#7889]
Right now the md-switch component only allows to have the text on the right side of the switch control
![switch-right-side-text](https://cloud.githubusercontent.com/assets/342287/14289375/e698df56-fb30-11e5-926d-265eeeab5223.png)

It will be nice to have the ability to set the text on the left size of the switch control
![switch-left-side-text](https://cloud.githubusercontent.com/assets/342287/14289387/ef5b3076-fb30-11e5-83d4-13eb5624d1f0.png)

**Comment by francittadini** [comment]
+1

I think this is a very needed feature.

**Comment by angryfatkid** [comment]
Since the switches are typically to the right of the text, the option to configure the text placement is required for this control.  We have implemented this in several places and really need this to be a standard config.

**Comment by smfiorillo** [comment]
+1

I'd be really useful to have that option

**Comment by Lordnoname** [comment]
@DevVersion I would like to submit a pull request for this issue. What is needed to put a PR together.

**Comment by DevVersion** [comment]
@Lordnoname Cool.

I think, we should add an attribute, which will be observed and can be interpolated.

```html
<md-switch md-invert="isInverted"></md-switch> // Interpolated
<md-switch md-invert></md-switch> // True
<md-switch md-invert="false"></md-switch> // False
```

So, the `postLink` observes the attribute and applies changes correctly.

```js
// On Init and on Attribute Value Change
$attrs.$observe('mdInvert', function(newValue) {
  isInverted = $mdUtil.parseAttributeBoolean(newValue);

  // Update Elements with CSS or JS 
 //  Think JS is better, to support RTL as well

 // Add a class to invert the margin / padding as well.
  element.toggleClass('_md-invert', isInverted);
});
```

```css
&._md-invert {
  @include rtl-prop(padding-right, padding-left, PADDING);
}
```

If you have any further questions, let me know.

**Comment by 0815fox** [comment]
+1
This would really help.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
