### ISSUE TITLE
md-datepicker removing icon alignment issue

### ISSUE THREAD

**Issue by jero07** [angular/material#7892]
if i set css .md-datepicker-button display:none to remove icon, the datepicker tends to push the adjacent divs below to the right.

http://codepen.io/jerome07/pen/pydaGV

![image](https://cloud.githubusercontent.com/assets/759404/14290468/0a92772c-fb14-11e5-8f58-4bef9476e1a3.png)

![image](https://cloud.githubusercontent.com/assets/759404/14290475/13508a70-fb14-11e5-827f-7a44f92c7e46.png)

```
<div style="padding:4px;">
                            <div style="float:left"layout="column" flex>  <md-datepicker ng-model="myDate1" md-placeholder="enter1"></md-datepicker></div>
                            <div style="float:left"  layout="column" flex>   <md-datepicker ng-model="myDate2" md-placeholder="enter2"></md-datepicker></div>
                            <div layout="column" flex>  <md-datepicker ng-model="myDate2" md-placeholder="enter3"></md-datepicker></div>
                        </div>
                        <div style="padding:4px;">
                            <div style="float:left"  layout="column" flex>   <md-datepicker ng-model="myDate1" md-placeholder="enter4"></md-datepicker></div>
                            <div style="float:left"  layout="column" flex>  <md-datepicker ng-model="myDate2" md-placeholder="enter5"></md-datepicker></div>
                            <div  layout="column" flex>   <md-datepicker ng-model="myDate2" md-placeholder="enter6"></md-datepicker></div>
                        </div>

.md-datepicker-button {
    display: none;
} 

```

**Comment by clshortfuse** [comment]
I'm going to add that the probably icon shouldn't even be there since it's not part of the material design spec.

**Comment by jero07** [comment]
+1. should be removed, since there's the drop down button already, looks redundant.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
