### ISSUE TITLE
icons inside md- button or md-icon-button are not themed when inside a md-toolbar

### ISSUE THREAD

**Issue by CxRes** [angular/material#7894]
See Pen
http://codepen.io/anon/pen/RajMop

Both the vertical dots button and the heart in "Love More" button remain uncolored.

This is happening because a fill property is being defined for icons and icon-buttons on toolbars 
```
md-toolbar.md-default-theme:not(.md-menu-toolbar) md-icon, md-toolbar:not(.md-menu-toolbar) md-icon {
    color: rgba(255,255,255,0.87);
    fill: rgba(255,255,255,0.87); }
```

This should be specific to icons on toolbar;
not icons inside buttons inside toolbar

**Comment by CxRes** [comment]
The same thing happens in md-list with md-avatar-icon...

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
