### ISSUE TITLE
md-input-container margins, alignment, and font-sizes do not match material design spec

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#7898]
So many, many, input items don't match the spec.

The most notable of issues is large vertical margins.

I'm started work on trying to fix all these issues and have a made a codepen with the fixes I have made. All the fixes are in CSS, so they would have to been merge into the SCSS files.

http://codepen.io/shortfuse/pen/oxGowZ

The codepen allows you to compare with a couple of templates on the material design site. I tried as best I could to match 1:1 it with the spec images.

The issues are as follows:

- md-toolbar should not have a max-height
- md-input-containers in md-toolbar have the wrong color
- md-input-containers shouldn't have padding-right as 0px when last-of-type
- md-select caret is scaled wrong, should be offset to the right by 7px, and font-size forced to 16px
- md-input-container labels should 12px in font-size and height
- md-input-container md-icon color and position is wrong
- md-input-container md-input have the wrong margins and padding
- md-input-container md-input text height should always match font-size (not possible with CSS fix)
- floating labels should transform from input text font-size and height to 12px, not scale to 75%
- md-select has wrong padding
- md-checkbox checkbox should be 18px not 20px

I'm sure there might others I did in my codepen, but I was doing a quick run through. It's worth noting, that some of the math is funky in the templates, especially the spacing between items, but I did the best I could to match them all without any forced styling on specific md-input-container elements. 

This means you can specify md-no-float without rework anything and it will scale properly. I also added md-display-1 support but that can be done programmatically over javacsript to support any font-size (not just 34px).

In the codepen, you can click on the right hand side and see how it matches up with the generated version.

**Comment by clshortfuse** [comment]
The previous codepen is based on 1.07

This is against master: http://codepen.io/shortfuse/pen/ZWxYpN

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
