### ISSUE TITLE
layout: no rendering of cards in IE11 when layout=column and child has flex

### ISSUE THREAD

**Issue by sjaase** [angular/material#7899]
Created a plunk containing an example where the cards don't get rendered (cards disappear) when breakpoint causes layout to be column. It seems to be the combination of layout=column and the child being set to flex.

Appears only in Internet Explorer 11, other browsers like Firefox and Chrome renders correctly.
Angular Material version: 1.1.0-rc2

https://plnkr.co/edit/6t8uA39tOVEDBjOKSS4E?p=preview

**Comment by ThomasBurleson** [comment]
Trying using (loading) the Layout IE_fixes contained in [**`angular/bower-material/modules/layouts`**](https://github.com/angular/bower-material/tree/master/modules/layouts)

**Comment by sjaase** [comment]
The issue remained the same.

**Comment by ThomasBurleson** [comment]
Flexbox Column layouts have proven to be tricky. Try wrapping your child content in a wrapper `<div>`:

e.g.

```html
<myContainer layout="column">
   <div>  <child1 flex >  </div>
   <div>  <child2 flex >  </div>
</myContainer>
```

**Comment by sjaase** [comment]
Different result but didnt solve it.

However, I tried another approach by just setting layout=row on parent and then setting a flex-xs=100 on each child content. This gave the wanted result.

```html
<div layout layout-wrap>
  <div flex="50" flex-xs="100">
    <md-card>
      <md-card-title>
        <md-card-title-text>
          <span class="md-headline">Headline</span>
        </md-card-title-text>
      </md-card-title>
    </md-card>
  </div>
</div>
```

**Comment by vinylhero** [comment]
I've also seen this issue. sjaase's fix also helped me.
