### ISSUE TITLE
Button shadows don't match Material shadow

### ISSUE THREAD

**Issue by joeyperson** [angular/material#7904]
Raised buttons have a rogue shadow, but should match normal and elevation states.

Should be using 2 and 8dp:
https://github.com/angular/material/blob/master/src/core/style/variables.scss#L56

**Comment by DevVersion** [comment]
@EladBezalel Can you take a look at this? since you made the most whiteframe implementation.

**Comment by EladBezalel** [comment]
@joeyperson can you link the spec relevant ?

**Comment by joeyperson** [comment]
https://material.angularjs.org/latest/demo/button

I see this as the shadow:
.md-button.md-raised:not([disabled]){box-shadow:0 2px 5px 0 rgba(0,0,0,.26);}

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
