### ISSUE TITLE
clickOutsideToClose for md-bottomsheet doesn't work

### ISSUE THREAD

**Issue by VikramTiwari** [angular/material#7905]
example: http://codepen.io/anon/pen/bpYxjb

**Comment by tenshiAMD** [comment]
It seems you have a warning in your codepen: "<md-backdrop> may not work properly in a scrolled, static-positioned parent container."

**Comment by tenshiAMD** [comment]
+1. It seems this is a issue on 'v1.0.7' md-backdrop for md-bottomsheet. I'd tried on 'v1.1.0rc2' its working properly.

**Comment by ThomasBurleson** [comment]
https://material.angularjs.org/latest/demo/bottomSheet works!

**Comment by rmaspoch** [comment]
I'm experiencing the same problem in version 1.0.7. If you update this codepen to use version 1.0.7, you could easily reproduce the issue.
https://codepen.io/team/AngularMaterial/pen/mVxgbg

**Comment by VikramTiwari** [comment]
@rmaspoch You should update your Angular-Material to latest version (1.0.8).
