### ISSUE TITLE
md-select: incorrect arrangement on multiple values selected to be vertically arranged.

### ISSUE THREAD

**Issue by tenshiAMD** [angular/material#7907]
[v1.1.0rc2] This occurs on md-select with multiple values that values arranged in vertical manner.
- http://codepen.io/tenshiAMD/pen/grXQam

**Comment by tenshiAMD** [comment]
or atleast there are options for horizontal and vertical arrangement of values. horizontal arrangement looks neat in tight forms rather than vertical. :+1:

**Comment by ilovett** [comment]
Would be great to have a class to display inline with ellipsis for overflow

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
