### ISSUE TITLE
md-combobox

### ISSUE THREAD

**Issue by icenold** [angular/material#7908]
I need a combobox for project but I need it to have same design on md-input+md-select combined

**Comment by icenold** [comment]
BUMP

**Comment by icenold** [comment]
BUMP

**Comment by icenold** [comment]
BUMP

**Comment by icenold** [comment]
BUMP

**Comment by icenold** [comment]
BUMP

**Comment by ryan-kimber** [comment]
Take a look at md-autocomplete. You should be able to accomplish what you're looking for.

**Comment by icenold** [comment]
it doesnt have a dropdown button

**Comment by icenold** [comment]
Nevermind..as a last resort I needed to add a custom CSS for the dropdown.
```
    .md-autocomplete-suggestions-container{
        margin-top: 2em;
        width:auto;
    }
```
