### ISSUE TITLE
angular-material vs angular-material-source package name

### ISSUE THREAD

**Issue by sryzycki** [angular/material#7909]
Hello,

I've been using your awesome Angular Material project for a few months now on this project. So far I always had this line in our project's package.json:
```
"angular-material": "1.0.7"
```
but when I spotted your 1.1.0 RC I decided to utilise it and changed our code to:
```
"angular-material": "angular/material#v1.1.0-rc2"
```
In effect our build started failing because we are importing Sass partials for a bit more scss freedom instead of importing the default css file. The reason is that it gets installed in `node_modules/angular-material-source` folder since the package name is different.

I assume this is intended and you have your reasons for serving it with two different package names from npm and from github?

Thanks,
Keep up the good work!

**Comment by ThomasBurleson** [comment]
You should use npm to install angular-material and update your `package.json`. Here are `npm` commands you may find useful:  [Installing with NPM](https://github.com/angular/bower-material/blob/master/README.md#npm)
