### ISSUE TITLE
md-autocomplete does not play well the rest of Angular

### ISSUE THREAD

**Issue by timruffles** [angular/material#7910]
`<md-autocomplete>` doesn't use the `ng-model` system correctly, requiring hacks to get basic features (`md-input-name`) and making composing it with validators impossible (which is why `required` is manually added within the directive).

Desired
=======

```
<form name="$ctrl.myForm">
  <md-autocomplete ng-model="$ctrl.item.thing"
                                 name="thing"
                                 my-custom-validator
  >
```

1. `mdAutocomplete` uses ng-model as standard, and uses the created `ngModelController` instance
1. Everything else just works - built in validators (`ng-minlength` etc), custom validators (using `ngModelController` API).

Actual
========

1. Can't use directives like `my-custom-validator` as ng-model is hidden down inside
1. Have to use non-standard `md-input-name` approach

Proposal
=======

I'm happy fix this if a maintainer would be ok to merge the PR.

**Comment by timruffles** [comment]
Thought it'd be worth pinging @robertmesserle and @DevVersion as you've both looked at this before.

**Comment by marcomafessolli** [comment]
#6544

**Comment by timruffles** [comment]
Dupe of #6544
