### ISSUE TITLE
A mostly vertical swipe should not trigger a horizontal one (and vice versa)

### ISSUE THREAD

**Issue by code-tree** [angular/material#7911]
Currently, while swiping to scroll down a tab's contents, a horizontal swipe can easily be triggered, changing the tab the user is viewing, when they were obviously just trying to scroll vertically.

I believe, therefore, a horizontal/vertical swipe action should only be triggered if that direction is larger than the opposite.

See pull request

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
