### ISSUE TITLE
 It is possible that the md-progress-circular randomly change color?

### ISSUE THREAD

**Issue by leok85** [angular/material#7913]
Example: http://codepen.io/mrrocks/pen/EiplA

**Comment by crisbeto** [comment]
It's not built into Material, but you can make it change colors yourself. What version of Material are you using (the approach to 1.0.6 vs 1.1 is different)?

**Comment by leok85** [comment]
I`m using 1.0.7 version. 

Looking at the material design documentation does not indicate this color change, but the Gmail application uses two colors (blue and red) in updating the inbox (pull to refresh)

**Comment by crisbeto** [comment]
Seems like you can't do it in 1.0.7, because it's already using the `animation` property to animate the spinner itself. Here's a fiddle of how it can be done in 1.1, though: http://codepen.io/crisbeto/pen/PNOMaL

**Comment by leok85** [comment]
I'll update then.

Thanks for the tip.
