### ISSUE TITLE
Accessibility Issue with Tabs

### ISSUE THREAD

**Issue by manish2535** [angular/material#7916]
I did a quick Screen reader test on the Tabs Directive and found that the screen reader reads twice as many tabs that actually exist. So, if you have 2 tab items, the screen reader is picking up 4 and will start reading "**3 of 4**" and "**4 of 4**". Its probably because of how the HTML is being rendered.

![capture](https://cloud.githubusercontent.com/assets/4663798/14323000/c9907b14-fbec-11e5-8d5f-947586fdd5d5.JPG)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
