### ISSUE TITLE
md-menu with offset seems to break when browser resized

### ISSUE THREAD

**Issue by jrgleason** [angular/material#7917]
I am noticing that something with the absolute positioning in the md-menu is not updating on window resize. This causes the menu to go all over the place when the browser shrinks. Is there a way to overcome this?

I also noticed that it has to do with scrolling. The menu goes further down the more I have scrolled....

removing the max-height from md-menu-content is my work around.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
