### ISSUE TITLE
MD-LIST Spacing off

### ISSUE THREAD

**Issue by tanahara** [angular/material#7921]
![image](https://cloud.githubusercontent.com/assets/1711202/14339377/acb4a3ec-fc43-11e5-8f5f-fee5a31247a6.png)

No custom css being applied.

**Comment by DevVersion** [comment]
@tanahara Please provide a demo, at first, it looks like a wrong use-case of flexbox.

**Comment by DevVersion** [comment]
Closing this as it works as expected - if you have any further questions or you can provide a demo which shows your issue I will reopen this issue.
