### ISSUE TITLE
md-dailog id issue

### ISSUE THREAD

**Issue by vipul-jain** [angular/material#7924]
#This is worst feature in newer material v1.0.7, that every dialog id is prefixed with
'dialogContent_'

Even I assigned  my own id like 'csv-dialog', it will turned to
'dialogContent_csv-dialog'

I have to do major changes in my current project.

**Comment by DevVersion** [comment]
@vipul-jain We prefix the dialog content, because otherwise we will have duplicate ids, which is not valid HTML and not good for A11Y support.
