### ISSUE TITLE
md-bottom-sheet out side to click issue.

### ISSUE THREAD

**Issue by vipul-jain** [angular/material#7925]
Recently I have upgraded material v1.0.5 to v1.0.7

I'm not be able to close the bottom-sheet with out-side click.
Also I have set 
clickOutsideToClose: true

though it's not working, not even close on escape is working.

**Comment by RolandHeath** [comment]
This isn't occurring on the docs page, is it possible for you to replicate it in a codepen or similar?

**Comment by bjporada** [comment]
For me bottom sheet clickOutsideToClose also did not work in v1.0.7. I upgraded to 1.1.0-rc2 and it now works.

**Comment by billsworld** [comment]
bottomSheet clickOutsideToClose not longer closes it with just a click, it takes a swipe down. 

@ThomasBurleson this seems awkward, the bottomsheet should be able to close with just a tap on desktop. Confusion here as well https://github.com/angular/material/issues/2895

**Comment by ThomasBurleson** [comment]
See https://material.angularjs.org/latest/demo/bottomSheet, the "Show as List" demonstrates that `clickOutsideToClose` works as expected.
