### ISSUE TITLE
Strange behavior of md-menu-item's with radio type.

### ISSUE THREAD

**Issue by ghost** [angular/material#7926]
Hello!

I'm using Angular version 1.5.3 and Angular Material 1.0.7. Have a problem with placing md-menu-item's with radio type due to it's strange behavior. 

Codepen is here: [http://codepen.io/anon/pen/VayaoY](http://codepen.io/anon/pen/VayaoY)

Can anybody help me with this issue?

Thank's!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
