### ISSUE TITLE
mdAutocomplete: Progress bar is visible after pressing ESC

### ISSUE THREAD

**Issue by TobiasKrahn** [angular/material#7927]
Since Angular Material v1.0.7 a progress bar is visbile after pressing **ESC** inside an **empty** autocomplete. 

Example from the demo page:
![image](https://cloud.githubusercontent.com/assets/16705453/14351594/7a5172bc-fcd0-11e5-9fe3-d4c3e316ff28.png)

**Comment by San4oPanso** [comment]
I can confirm. Tested on last Chrome and Edge

**Comment by crisbeto** [comment]
It's also in 1.1, I'll look into it.
