### ISSUE TITLE
Make tabs header 'sticky' or Add an option which allow to switch tabs header to 'sticky' mode

### ISSUE THREAD

**Issue by fealaer** [angular/material#793]
Make tabs header 'sticky' or Add an option which allow to switch tabs header to 'sticky' mode

**Comment by sombriks** [comment]
Hi Thomas, 

Example link seems broken, leading to the root of doc index.

i would like to see the example, since it's the first google result and would be a great resource if the link points out to the correct place.

**Comment by ThomasBurleson** [comment]
@sombriks, @fealaer - here is an updated CodePen for **[Tabs with External Content](http://codepen.io/team/AngularMaterial/pen/pbjpVB?editors=1010)**

You can also use *mdNavBar* for tabs-like navigation and external content. See the [NavBar Demo](https://material.angularjs.org/latest/demo/navBar).

> The online docs version was refactored in 3/15 and does NOT use external content. I will update the docs.
