### ISSUE TITLE
Menu-Bar: Switching quickly between menu Items causes overlapping menus

### ISSUE THREAD

**Issue by nkeeslin** [angular/material#7932]
When you switch between two menu items quickly it can cause both of them to remain open simultaneously.  Shown here on the demo page https://material.angularjs.org/latest/demo/menuBar
![screen shot 2016-04-07 at 11 29 13 am](https://cloud.githubusercontent.com/assets/5240940/14360631/90a7c3fc-fcb4-11e5-9eba-23c5adf3109e.png)

Using latest version of angular material 1.1.0-RC2
Browser: Chrome 49.0.2623.110

**Comment by RolandHeath** [comment]
I had trouble getting this to occur at first, but came up with a method that can also chain to open many menus. Steps below:
1. Click the first top-level menu item
2. Click the same item again
3. Press tab
4. Press enter
This will have two adjacent menus open (tested on the docs page)
To move on to having more, continue:
5. Click an open top level menu item
6. Tab to the next unopened one
7. Hit enter

**Comment by topherfangio** [comment]
@RolandHeath Thanks for those steps! Can definitely see the issue. I haven't looked into the code too much, but I would think that whenever we open a menu, we should be notifying the menu-bar so that it can close all other menus.

Need to see if that's currently the case and there is a bug, or if it just isn't implemented.

**Comment by kevintc** [comment]
There is also another bug linked to this one (I don't know if it needs to be a separate issue though).
https://material.angularjs.org/latest/demo/menuBar

Steps to reproduce it :
1. Click an item
2. Quickly hover another item and come back to the one you clicked before
3. If you complete steps 1 & 2 in less than a second, the menu closes and you can't click the item anymore.
4. You have to hover another item to make it work again.

Would it be possible to close menu when clicking on the menu item ?
Actually clicking an item only opens the menu but doesn't closes it if it's already open (while it does so in almost every software).

Tell me if I need to open another issue for this things :)

Tested : Chrome 50 and Firefox 46 [ Ubuntu ]

**Comment by topherfangio** [comment]
@kevintc Pretty sure that's related to #7948.

**Comment by kevintc** [comment]
It could be, although I don't see exactly how :)

Do you have any idea about the close on click behavior ? Is it expected to work as it is now ?

**Comment by topherfangio** [comment]
@kevintc I think it should definitely close on click. I thought this was implemented and just broken, but it may not have been implemented yet. I'm looking at cleaning up a lot of that logic.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
