### ISSUE TITLE
Menu-bar: Using the menu bar with a complex DOM causes the menu bar to react very slowly

### ISSUE THREAD

**Issue by nkeeslin** [angular/material#7933]
We use the menu bar on a page that is rich with html and has a large number of DOM elements, which causes the menu bar to react very slowly when switching from one menu item to another.  When we simplify the DOM it improves.  Is there something that we need to do to account for this? Or is it a bug?  Thanks!

Angular Material Version 1.1.0-RC2
Chrome Version 49.0.2623.110

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
