### ISSUE TITLE
delete button on md-tab-item

### ISSUE THREAD

**Issue by dlombardi** [angular/material#7939]
when ng-repeating the md-tab-items i'd think it would make sense to also be able to delete them by clicking on a delete icon that would optionally accompany each tab.  I would think it would be better to not have to navigate to the tab in order to delete it. 

Right now I'm attempting to add these buttons into the directive through pure javascript but it is going nowhere due to the lack of transclusion or the fact that I'm attempting to place a clickable element inside of another clickable element (the tabs).

**Comment by topherfangio** [comment]
I think this might make sense as an option on the tab `md-removable` (to follow what we're planning with chips) and perhaps a `<md-tab-remove>` element which lets you customize it.

I don't think we have time for this at the moment, but if you want to flesh out the idea some more, you can  always submit a PR :smile:

**Comment by ThomasBurleson** [comment]
Will not fix.
