### ISSUE TITLE
Allow setting of input type on md-chips

### ISSUE THREAD

**Issue by jpike88** [angular/material#7943]
I want an email keyboard to appear by default on iOS devices, this requires setting the input type to "email" but md-chips doesn't give me a way to do it

**Comment by RolandHeath** [comment]
You can pass an input element to md-chips, with whatever input type you like. 
There is an example of how to do this on the [docs page](https://material.angularjs.org/latest/demo/chips), see the one titled "Custom Inputs"

**Comment by jpike88** [comment]
Thanks
