### ISSUE TITLE
mdInputContainer: Inputs do not work properly in Firefox for Android and touch screens

### ISSUE THREAD

**Issue by atorma** [angular/material#7945]
Starting from Angular Material 1.0.0 input fields behave in a weird way in Firefox for Android (45.0.1 tested) and touch screens (Nexus 5 and Samsung Galaxy Tab S2 tested). In version 0.11.4 they are okay.

This can be reproduced in https://material.angularjs.org/0.11.4/demo/input vs https://material.angularjs.org/1.0.0/demo/input.

When tapping on a field, the cursor is at positioned at the beginning of the input content. Touch tapping does not move the cursor. One can only add characters to the start of an existing value but cannot change the existing value in the normal way (backspace, type). The only way to replace an existing value is to long-click to select the value and then delete it. After that the cursor is fixed to the end of the field content and still cannot be moved by touch tapping.

**Comment by farzinpashaee** [comment]
Which version this is going to fixed because downgrading to version 0.11.4 cause other problems

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
