### ISSUE TITLE
Pluralsight - Angular Material Fundamentals videos don't load

### ISSUE THREAD

**Issue by camden-kid** [angular/material#7946]
The [Pluralsight - Angular Material Fundamentals](https://app.pluralsight.com/player?author=ajden-towfeek&name=angular-material-fundamentals-m0&mode=live&clip=0&course=angular-material-fundamentals) videos don't load (except the Introduction).

Going to the actual [Pluralsight player](http://app.pluralsight.com/training/player?author=ajden-towfeek&name=angular-material-fundamentals-m0&mode=live&clip=0&course=angular-material-fundamentals), it tells you that "Your current subscription level does not allow you to view this module." for the separate videos.

**Comment by DevVersion** [comment]
Yes, it seems like this video requires a paid subscription?

**Comment by ThomasBurleson** [comment]
It appears that only the Pluralsight Introduction is free. I will modify the docs to indicate that only the Egghead.io videos are free.
