### ISSUE TITLE
md-menu opening on mouse hover

### ISSUE THREAD

**Issue by Latrisha** [angular/material#7948]
I'm using md-menu-bar to show a menu and the sub-menu with some nested sub-menu. I've added ng-click event to open the submenu. But the menu is still opening on mouse hover. How can I fix it?

**Comment by topherfangio** [comment]
Can you please provide a Codepen which demonstrates the issue?

**Comment by Latrisha** [comment]
[It's something like md-menu-bar demo.](http://codepen.io/Latrisha/pen/NNyOmr) And I understand, that it's regular behaviour when submenu is opened on hover, but it's a little bit unconvinient for my needs. And there is problem with it on smartphone. When I open one of submenus and then try to open another one, the second one dosen't close. It's seen on attached screenshot.

![screenshot_9](https://cloud.githubusercontent.com/assets/7831302/14456859/bd873b7e-00af-11e6-8562-3428eb332605.png)

**Comment by topherfangio** [comment]
What smartphone/browser are you using that is causing issues. We can take a look.

**Comment by Latrisha** [comment]
Samsung Galaxy S4, Android 5.0.1, Google Chrome 49.0.2623.105

**Comment by topherfangio** [comment]
Thanks for the additional info; definitely see the issue!

**Comment by Latrisha** [comment]
Thanks a lot!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by dremie** [comment]
My workaround:

```
<md-menu ng-repeat="a in $ctrl.actions" ng-mouseover="$ctrl.mouseover($event)">
<!-- menu stuff -->
</md-menu>
```

```
$ctrl.mouseover = function ($event) {
      // Prevent adjacent menus opening on mouseover
      $event.stopImmediatePropagation();
    };
```

**Comment by PlugaruT** [comment]
@dremie, you saved me :+1:

**Comment by kvkv** [comment]
Hi , I have the similar issue on the md menu hover but some changes are there. I created issue on github. Please give solution for the issue. I am giving github link below

[link](https://github.com/angular/material/issues/11011)
