### ISSUE TITLE
Floating Input Label disappears on iOS + Cordova

### ISSUE THREAD

**Issue by betorobson** [angular/material#7958]
I'm developing an app based on Cordova and I got a strange behaviour on iOS. 
After an input get focus the related floating label disappears.

Here a screen record demonstration:
![angularfloatinglabel-ios-bug](https://cloud.githubusercontent.com/assets/13212208/14395936/1a929a32-fdab-11e5-804d-715c8f2b504b.gif)

And here a codepen code similar to what I have here.
https://codepen.io/betorobson/pen/XdVyjo

I believe this bug is related to css translate 3d which is used to give an scale effect on floating labels. iOS can turn off this css property sometimes in order to save GPU and also ignore render elements using this property.

I have been looking for any issue related to this but, I couldn't find anything. So, I made by myself a CSS Fix only for iOS to reproduce the same effect. Have a look on my next screen record demonstration:

![angularfloatinglabel-ios-cssfix](https://cloud.githubusercontent.com/assets/13212208/14396053/c9a02026-fdab-11e5-86ea-6f8993a1ea31.gif)

And here a codepen code with my css fix.
https://codepen.io/betorobson/pen/VayqLb

**Comment by topherfangio** [comment]
This is likely related to #5707 for which we have not found a great fix yet.

What exactly does your CSS fix do? It looks like it disables the transforms?

**Comment by betorobson** [comment]
Indeed, I disabled css transform and I created a transition top. Also, it changes font size. 

After a fews tests on iPhone device its looks perfect as a workaround.

I forget to mention that only happens applying KeyboardShrinksView=true on Cordova config.xml.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
