### ISSUE TITLE
Autocomplete force text to uppercase

### ISSUE THREAD

**Issue by adityashedge** [angular/material#7971]
How can I force the text entered in the autocomplete to be uppercase only?

I can do this for an input by writing a directive with a parser. I will set the value to uppercase with '$setViewValue' which will get set on the ng-model(model controller in directive).

how can I do it with material autocomplete since there is no ng-model? I want all the text to be uppercase only.

**Comment by topherfangio** [comment]
Not sure if this will work for you, but you can use the `md-search-text-change` property to update the search text with the uppercase value:

http://codepen.io/topherfangio/pen/VaQQjB?editors=1010

Let us know if that doesn't work for you and we can reopen.
