### ISSUE TITLE
Virtual Repeat & ng-init not working properly

### ISSUE THREAD

**Issue by EricBorlandAGS** [angular/material#7974]
Hi all.
First of all thank you very much for all your work, angular material is an awesome and very useful product that helps us a lot.

I am trying to use the md-virtual-repeat right like I would with the ng-repeat. In the documentation it says is a "limited" component and that "Track by, as alias, and (key, value) syntax are not supported". However, it does not say anything about ng-init.
In my case, when I use an ng-init in each item of the md-virtual-repeat, it only executes the first X items that are visible on load, when scrolling, the next items are not firing the ng-init.

Here is a codepen: http://codepen.io/anon/pen/yOvbjb
In this codepen you can see how the flag initialized is only set to true for the first 9 elements but the rest are all kept to false.

I guess that's because the DOM is recycled or something like that.

I would like to know if this is a bug or a missing feature and if there is any plan to allow an ng-init work with the md-virtual-repeat as it does with the ng-repeat?

Thank you very much!

**Comment by topherfangio** [comment]
Thanks for the kind words!

This is indeed due to the DOM recycling. I'm going to reach out to the original developer to see if this can be easily added. If so, we'll try to get it in one of the upcoming minor releases; otherwise, we'll make sure to update the docs to note that it doesn't work with `ng-init`.

**Comment by EricBorlandAGS** [comment]
Thank you very much @topherfangio !

I could workaround but this could be a good feature to have a md-virtual-repeat less "limited".

If anyone is interested in the workaround (you may be warned, is a very ugly one) when, like in my case, a rollback to an ng-repeat is not possible, here we go: http://codepen.io/anon/pen/JXpaVJ

What I did is to make sure the init function to execute returns undefined and used as a expression inside the md-virtual-repeat item. I know this may have some performance issues and that it is very ugly... but the performance issues with the ng-repeat were not affordable.

Thank you

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
