### ISSUE TITLE
md-list-item: flex filler for secondary container breaks layout

### ISSUE THREAD

**Issue by e-oz** [angular/material#7976]
and it breaks layout.

Codepen: http://codepen.io/evgeniyoz/pen/pyaWoj?editors=1010
Chrome 50.0.2661.66 beta (64-bit),
Safari 9.1
Firefox 45.0.1

Screenshot:
<img width="1280" alt="screenshot 2016-04-11 17 38 39" src="https://cloud.githubusercontent.com/assets/526352/14431048/91447dc2-000c-11e6-892e-e9733cb57426.png">

**Comment by henrymana** [comment]
The codepen referenced on the material section (layout tips https://material.angularjs.org/latest/layout/tips) is also broken by the same or a similar issue.... http://codepen.io/team/AngularMaterial/pen/NxKBwW. Code based on the codepen works with 1.1.0-rc1 but broken after that. There is a "<div flex>" and a secondary item inserted when it shouldn't.

**Comment by e-oz** [comment]
Thanks!
