### ISSUE TITLE
Just adding ngMaterial module changes the behavior of event bubbling somehow

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#7978]
(From a googler ldap yzibin@ :))

This bug happens only on mobile when you have some element (e.g., a FAB) over an iframe, and clicking on the FAB hides it.
The click shouldn't pass to the iframe behind it (because the FAB received it), but somehow (only when ngMaterial is included!) the click passes to the iframe.

I create this example to show it:
http://yoav-zibin.github.io/emulator/examples/ngMaterialBug/bug.html

The bug happens when you click on red square on a mobile device (you can also turn on mobile emulation in chrome):
the click passes somehow to the iframe beneath it (the iframe contains the green square).

The workaround is to hide the FAB using $timeout (it took me a while to discover this :))
I did that with the blue square: clicking on the blue square only hides it with a $timeout, which prevents the click going to the iframe.

To show that this is an ngMaterial issue, I also created:
http://yoav-zibin.github.io/emulator/examples/ngMaterialBug/not_buggy.html
which is exactly like bug.html, but without the dependency on 'ngMaterial' module.

This is a video showing the bug:
https://www.youtube.com/watch?v=8Sy1jWQDl-4

The bug is not critical (due to the easy workaround), but I'm really curious why it happens :)

**Comment by yoav-zibin** [comment]
BTW, I found a better workaround for the bug: to animate hiding/showing the FAB button (instead of using $timeout to hide it)
E.g., see animating ng-if: https://docs.angularjs.org/api/ng/directive/ngIf#animations

**Comment by ThomasBurleson** [comment]
@topherfangio - FYI

**Comment by yoav-zibin** [comment]
BTW, I happened to stumble upon a similar behavior with just angularjs (without material design):
http://yoav-zibin.github.io/emulator/examples/ngMaterialBug/file_example.html

Now I'm always animating my ng-if show/hide :)
Since animation is at the heart of material design, and it fixes this issue, feel free to close the bug or reduce priority.

**Comment by topherfangio** [comment]
@yoav-zibin Thanks for the update!

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
