### ISSUE TITLE
md-datepicker: annoying usage and suggestions

### ISSUE THREAD

**Issue by wembernard** [angular/material#7979]
(TL;DR: skip to the suggestions below)

### Use case 

I'm using `<md-datepicker ng-model="profileCtrl.birthday"></md-datepicker>`. 

But since it's linked to an API, I'm using `ngResource` and have `<md-datepicker ng-model="profileCtrl.user.birthday"></md-datepicker>`

But since `md-datepicker` requires a Date object, I must do this kind of stuff in my `profileCtrl`:
```
var profileCtrl = function(Users) {
   this.user = Users.get({id: 42}, function() {
      this.user.birthday = new Date(this.user.birthday);
   });
};
```

And since I'm using `ngResource` and I'm using `md-datepicker` to update a profile form, I must do this kind of stuff:
```
var profileCtrl = function(Users) {
   this.submit = function() {
      this.user.$update(function() {
         this.user.birthday = new Date(this.user.birthday);
      });
   };
};
```

And since I'm using this `md-datepicker` on 6 different forms on my website, I have to repeat 12 times this callback
```
   function() {
      this.user.birthday = new Date(this.user.birthday);
   }
```
... only because `md-datepicker` is asking for a `Date()` object. 

--

### Suggestions 

1. Change ng-model: init your Date object inside the directive and expect a Date string as parameter instead.
2. Add some parameters such as `transformModel` which would allow 2 functions `sendingModel` and `receivingModel` to be transformed in whatever format we want.
3. Add some `mdDatepickerProvider` configuration we can play with (such as the 2 previous functions) in our `app.config()`. 

**IMHO**:
Number 1 would be the best usage-simple way whereas Number 3 would be the most pragmatic one. Number 2 would be some kind of best & worst solution from both 1 & 3.

**Comment by marcomafessolli** [comment]
@wembernard, issue #6253 might be related

For now, to resolve this, I've created a parser and formatter that do the job, [https://gist.github.com/marcomafessolli/4b5289fdab5a9790ec32](look)

**Comment by wembernard** [comment]
+1 @marcomafessolli 

I thought about suggesting moment.js use with md-datepicker but it would make another dependency not everyone wants to rely on.

**Comment by ThomasBurleson** [comment]
will not fix in ngMaterial 1.x
