### ISSUE TITLE
fabSpeedDial: Spacebar not working when fab is open

### ISSUE THREAD

**Issue by zanemcca** [angular/material#7981]
For some reason the speedDial will prevent spaces from being pressed when it is open. 

The offending [line](https://github.com/angular/material/blob/master/src/components/fabSpeedDial/fabController.js#L192) of code. Removing this line takes care of the issue.

There was a PR for this issue that was closed before. I am not sure why.

**Comment by topherfangio** [comment]
@zanemcca I am fairly certain that the PR was closed because the fix was merged. The line you point to above has to do with the ESCAPE key.

Are you using the latest version?

**Comment by zanemcca** [comment]
@topherfangio You are absolutely correct. Sorry about that I should have checked my version first.

**Comment by topherfangio** [comment]
No worries! Glad it's working!
