### ISSUE TITLE
md-subheader sticky bug in Chrome when using ngRoute

### ISSUE THREAD

**Issue by Xorok** [angular/material#7983]
Hello, I'm experiencing a bug similar to the one listed at the bottom of this post, there is also a link to our GitHub repository which contains the code.

I'm trying to create a website that uses ngRoute with a simple templateurl to load the different subpages into the main view. The sticky subheader works more or less like it should on all browsers when the subpage-code is pasted directly in the main site (so as one document), but as soon as you put it into a different file and load it with ng-route, Chrome enters derp-mode.

Here is a screenshot comparing Firefox and Chrome when all the HTML code is in one file and ngRoute is not being used:
https://i.imgur.com/VUOxala.png

Aside from the fact that the shadow below the bar doesn't show up on Firefox and that the sticky bar appears too soon on Chrome resulting in two bars at once on the screen, everything looks fine.

But as soon as you switch back to the main-view concept with ngRoute, this happens on Chrome (The whole content is being indented, just ignore the gaps on each side of the sticky bar on FF):
https://i.imgur.com/1BRZ55h.png

This is the structure of the index.html-file (with main-view):

```
<body>
<div layout="row" id="wrapper" ng-controller="AppCtrl" layout="column" ng-cloak>
    <md-sidenav class="md-sidenav-left" md-component-id="left" md-disable-backdrop md-whiteframe="4">
      ...
    </md-sidenav>

    <div layout="column" flex>
      <md-toolbar ng-controller="HeaderController">
        ...
      </md-toolbar>

      <md-content class="main-insert-view" ng-view>
    </div>
</div>
</body>
```

And this is the subpage I'm trying to insert:

```
<div ng-controller="LabelController">
  <h2>Labels</h2>
  <md-list id="label-list" ng-cloak>
    <md-subheader class="subheader">General</md-subheader>
    <md-list-item class="secondary-button-padding" ng-repeat="label in labels">
      <md-icon aria-hidden="true" md-svg-src="images/color.svg" ng-style=" {'fill': label.color}"></md-icon>
      <p>{{label.name}}</p>
      <md-button class="md-secondary" ng-click="remove_label(label.id)">Remove</md-button>
    </md-list-item>
  </md-list>
</div>
```

This issue is similar to this already closed, old one:
https://github.com/angular/material/issues/1647#issuecomment-208465431

Here is a link to our GitHub repository, the affected files are the index.html in the static folder, and the labels.html-file in the snippets subfolder. Please note that the subheader currently uses the "md-no-sticky"-class to bypass this problem. Just remove it to reproduce this behaviour.
https://github.com/MadeInSpengergasse/Honeypot/tree/master/static

Am I doing something wrong with the containers or is this a bug?

Regards
Xorok

**Comment by z3ntu** [comment]
bump

**Comment by z3ntu** [comment]
@ThomasBurleson This bug still persists!
[Demo here](https://youtu.be/YyxNFE72CVU) (in firefox the space between the toolbar and the subheader is artificial, so not a bug)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by z3ntu** [comment]
@ThomasBurleson Thanks for the information.
