### ISSUE TITLE
bug(select): label showing up twice

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#7984]
![image](https://cloud.githubusercontent.com/assets/571363/14438075/1880c3c4-ffd9-11e5-9d3a-195936fec1f4.png)

"The double text shows up when we change the tabs in the same card, but it disappears immediately if I click anywhere else on the page. Changing the tabs should not affect the value in the menu."

**Comment by topherfangio** [comment]
I've made a [basic Codepen](http://codepen.io/topherfangio/pen/aNrKyN) which attempts to reproduce this, but I'm really not sure how they have it setup. Can you please provide a demo so we can track this down?

**Comment by topherfangio** [comment]
Working with @ErinCoughlan on Slack to better understand the issue.

**Comment by topherfangio** [comment]
After many attempts and some back-and-forth with the internal Google team, we still cannot reproduce this so we are going to close. If it is still an issue, please provide a Codepen which demonstrates how this is happening so that we can investigate further.
