### ISSUE TITLE
bug(button): buttons are showing up with hover states when not hovered

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#7985]
![image](https://cloud.githubusercontent.com/assets/571363/14438304/4280f4a4-ffda-11e5-9231-086f2d958f10.png)

**Comment by ThomasBurleson** [comment]
@robertmesserle - how can we reproduce this ?

**Comment by robertmesserle** [comment]
Unfortunately, I have no idea - I will try to track somebody down who could give me more info.

**Comment by DevVersion** [comment]
@robertmesserle Great thanks, at the first look I'm guessing somebody is not aware of the auto-focus of the dialog.

**Comment by robertmesserle** [comment]
Yea, that was a thought I had too.  I will follow up with the person who reported the issue.

**Comment by DevVersion** [comment]
As discussed with @robertmesserle, we will close that issue, because there are no new information coming.
