### ISSUE TITLE
bug(theme): md-toolbar flashes with different theme color when page loads

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#7986]

**Comment by EladBezalel** [comment]
@robertmesserle can you please tell more?

**Comment by DevVersion** [comment]
@EladBezalel I also noticed this bug and I guess it was introduced by the added color transitions for the toolbar. 
- http://codepen.io/DevVersion/pen/mEyEWW

Normally the themes are applied after the toolbar is initialized, which means we're not able to disable the transition till the theme is applied. We may have to search for another solution.

**Comment by robertmesserle** [comment]
Ah, good - I don't actually have more info than what I put in the title as I wasn't the one who found the issue.  But I have seen issues where it seemed like themes didn't work with ng-cloak as they were supposed to.
