### ISSUE TITLE
md-slider doesn't update its position when max or min is updated

### ISSUE THREAD

**Issue by PaulMougel** [angular/material#799]
When the `max` value of an `md-slider` is updated, the horizontal position of the slider isn't updated:

``` html
<!-- index.html -->
<md-slider flex min="0" max="{{max}}" ng-model="value"></md-slider>
<md-button ng-click="doubleMax()">Double max!</md-button>
```

``` javascript
// index.js
$scope.doubleMax = function () {
  $scope.max *= 2
}
```

See [this Plunker](http://plnkr.co/edit/Cd95q4Un0UmNgA2xxS1t?p=preview). If I double the maximum value for the slider, it doesn't move to reflect the modification. However, when I try to move it (using the keyboard for instance), then it moves in the right position.
![untitled](https://cloud.githubusercontent.com/assets/1788596/5244449/ef3205d4-794f-11e4-8655-2918e0dfbe5d.gif)

Tested on Chrome, Firefox and Safari.

**Comment by johnrivelt** [comment]
When min value changed, there is still some issue.
[https://embed.plnkr.co/tdyYHl/](url)
In above case, when click ssd 1 to 5, top-to-bottom direction works as I expect.
But, bottom-to-top is not updating correctly.
