### ISSUE TITLE
md-datepicker binds to an actual Date object, not simply a month / year / day of month

### ISSUE THREAD

**Issue by achuinard** [angular/material#7990]
In comparison to something like Android's DatePicker, why does the md-datepicker bind to a Date? This is causing a bit of extra overhead, especially when you consider timezones. I'm guessing the md-datepicker uses the system timezone? My app users can choose from a host of different timezones, so it's not always about the browser timezone.

Shouldn't the md-datepicker be concerned with just a day of month, month, and year?

I'm guessing that a big API overhaul won't be made, and you'll still continue to bind / use a Date object to back the md-datepicker, but I wanted to throw this out there.

**Comment by sdesmond** [comment]
This could open up the ability to use something other than a javascript Date (e.g. Moment), which would be nice here.

**Comment by ThomasBurleson** [comment]
Will not fix.
