### ISSUE TITLE
Inconsistent mdDialog behavior on Safari vs Chrome

### ISSUE THREAD

**Issue by kerbrat-quod** [angular/material#7992]
Hi!

I have a problem when using mdDialog and a custom directive.
On Safari (OS X and iOS) our directive is not shown, but on Chrome (Windows and Android) it is displayed.

Can someone help us figuring out what I do wrong with my code or with the mdDialog API?

Thanks,

Here is my code and some screenshots:

Controller file:
```js
// Called on the plus (+) button you can see on the screenshot.
$scope.addListingToWL = function (ev) {
  $mdDialog.show({
      parent: angular.element(document.querySelector('.watchlist')),
      controller: AddItemToWLCtrl,
      targetEvent: ev,
      templateUrl: 'views/dialogs/addItemToWatchlist.html',
      clickOutsideToClose: true,
      //fullscreen: true,
      locals: {
        watchlist: $scope.watchlist,
        origWatchlists: origWatchlists
      }
    })
    .then(function() {

    }, function() {
    });
};
```

```addItemToWatchlist.html``` file:

```html
<md-dialog layout="column" flex class="ticket-dialog" aria-label="add to watch list dialog">
  <md-dialog-content flex class="ticket-md-dialog-content">
    <listing-research selected-item-change="console.log(item)" default-search="searchText" placeholder="placeholder" not-found="notFound"></listing-research>
  </md-dialog-content>
</md-dialog>
```

```<listing-research>``` directive template file:
```html
<md-autocomplete
    id="autocompleteSymbol"
    md-delay="delay"
    md-no-cache="noCache"
    md-selected-item="selectedItem"
    md-search-text-change="searchTextChange(searchText)"
    md-search-text="searchText"
    md-selected-item-change="selectedItemChange(item)"
    md-items="item in querySearch(searchText)"
    md-item-text="item.display"
    md-min-length="3"
    placeholder="{{placeholder | translate}}">
    <md-item-template>
        <span md-highlight-text="searchText" md-highlight-flags="^i">{{item.display}}</span>
    </md-item-template>
    <md-not-found>
        {{dataNotFound | translate:{ searchText:searchText } }}
    </md-not-found>
</md-autocomplete>
```

Generated DOM in the view:
```html
<div class="md-dialog-container ng-scope" tabindex="-1" style="top: 0px; height: 919px;">
  <div class="md-dialog-focus-trap" tabindex="0"></div>
  <md-dialog layout="column" flex="" class="ticket-dialog layout-column flex md-content-overflow md-transition-in" aria-label="add to watch list dialog" role="dialog" tabindex="-1" aria-describedby="dialogContent_13" style="">
    <md-dialog-content flex="" class="ticket-md-dialog-content flex" id="dialogContent_13">
      <listing-research selected-item-change="console.log(item)" default-search="searchText" placeholder="placeholder" not-found="notFound" class="ng-isolate-scope">
        <md-autocomplete id="autocompleteSymbol" md-delay="delay" md-no-cache="noCache" md-selected-item="selectedItem" md-search-text-change="searchTextChange(searchText)" md-search-text="searchText" md-selected-item-change="selectedItemChange(item)" md-items="item in querySearch(searchText)" md-item-text="item.display" md-min-length="3" placeholder="Add Item to Watchlist" md-has-not-found="true" tabindex="-1" class="ng-isolate-scope">
          <md-autocomplete-wrap layout="row" ng-class="{ 'md-whiteframe-z1': !floatingLabel, 'md-menu-showing': !$mdAutocompleteCtrl.hidden }" role="listbox" class="layout-row md-whiteframe-z1" style="">
            <!-- ngIf: !floatingLabel --><input flex="" type="search" id="input-14" name="" ng-if="!floatingLabel" autocomplete="off" ng-required="$mdAutocompleteCtrl.isRequired" ng-disabled="$mdAutocompleteCtrl.isDisabled" ng-readonly="$mdAutocompleteCtrl.isReadonly" ng-model="$mdAutocompleteCtrl.scope.searchText" ng-keydown="$mdAutocompleteCtrl.keydown($event)" ng-blur="$mdAutocompleteCtrl.blur()" ng-focus="$mdAutocompleteCtrl.focus()" placeholder="Add Item to Watchlist" aria-owns="ul-14" aria-label="Add Item to Watchlist" aria-autocomplete="list" aria-haspopup="true" aria-activedescendant="" aria-expanded="false" class="ng-pristine ng-untouched ng-scope ng-empty flex ng-valid ng-valid-required" aria-invalid="false" style=""><!-- end ngIf: !floatingLabel -->            <!-- ngIf: $mdAutocompleteCtrl.scope.searchText && !$mdAutocompleteCtrl.isDisabled -->                          <!-- ngIf: $mdAutocompleteCtrl.loadingIsVisible() -->                  
          </md-autocomplete-wrap>
          <aria-status class="md-visually-hidden" role="status" aria-live="assertive">
            <!-- ngRepeat: message in $mdAutocompleteCtrl.messages track by $index -->        
          </aria-status>
        </md-autocomplete>
      </listing-research>
    </md-dialog-content>
  </md-dialog>
  <div class="md-dialog-focus-trap" tabindex="0"></div>
</div>
```

Screenshot on Safari (OS X and iOS):
![directive not displayed on safari](https://cloud.githubusercontent.com/assets/16305172/14385528/48f9ea56-fda1-11e5-85c6-215ceafaf544.png)
![image](https://cloud.githubusercontent.com/assets/16305172/14385542/559a84d2-fda1-11e5-8106-9c4183feef4b.png)

Screenshot of Safari DOM (OS X):
![safari dom](https://cloud.githubusercontent.com/assets/16305172/14385527/48f6369a-fda1-11e5-9e36-4400fd674bc1.png)

Screenshot on Chrome (PC):
![capturezzzz](https://cloud.githubusercontent.com/assets/16305172/14386198/1cba9500-fda4-11e5-834f-ced586383bf6.PNG)

**Comment by topherfangio** [comment]
Can you please wrap this up in a Codepen that demonstrates the issue? It really helps us when attempting to debug it :smile:

**Comment by kerbrat-quod** [comment]
Hi @topherfangio !

I found the issue and my problem is solved, but I made a demo for you :)
I don't know how to use Codepen to demo this issue so I made a repository and published it on GitHub Pages.

Here is the link of the **demo**: http://kerbrat-quod.github.io/modal-not-shown
And this is the repository URL: https://github.com/kerbrat-quod/modal-not-shown
You will be able to debug it with DevTools.

The issue was in a view file.
Here you can find the commit that made occur the behavior described:
https://github.com/kerbrat-quod/modal-not-shown/commit/7613e0a8f7058eba860e72cc693bea8f651cd89b

I hope you'll be able to see where the issue comes from.
Maybe it's cross-browser incompatibility and there is nothing you can do :(

Regards,

**Comment by topherfangio** [comment]
Thanks for the demo; this appears to be a flex-related issue. If you remove the `flex` attribute from your `<md-dialog-content>`, it works just fine. With the `flex` attribute, Safari doesn't appear to be calculating the height of the container properly and it lets it shrink to a height of `0px`.

I believe it is related to https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored as the workaround there of setting the `flex-shrink: 0; flex-grow: 1; flex-basis: auto;` seems to work.

We have a page outlining some tips/tricks for layout issues as well as many resources on where to find the latest bugs/info: https://material.angularjs.org/latest/layout/tips

Hope this helps. Since this is related to a specific browser issue, we are going to go ahead and close.
