### ISSUE TITLE
mdCheckbox: Memory leak

### ISSUE THREAD

**Issue by neko1235** [angular/material#7993]
The event handler [in checkbox.js](https://github.com/angular/material/blob/v1.1.0-rc2/src/components/checkbox/checkbox.js#L85) is leaking.
```
// Attach a click handler in compile in order to immediately stop propagation
// (especially for ng-click) when the checkbox is disabled.
tElement.on('click', function(event) {
  if (this.hasAttribute('disabled')) {
    event.stopImmediatePropagation();
  }
});
```

**Comment by crisbeto** [comment]
I'm not sure how this would cause a leak. Could you provide more info or a way of reproducing the issue that you're having?

**Comment by neko1235** [comment]
Please see http://jsfiddle.net/neko1235/kgr1ynt4/1/
I can see some elements leaking. Please correct me if I am wrong.
![screenshot from 2016-04-12 11 51 09](https://cloud.githubusercontent.com/assets/13606126/14471829/34a0ede6-00a5-11e6-9f64-6593f0b04b84.png)

**Comment by crisbeto** [comment]
Sorry, I don't see it, but I'm not too experienced in these types of situations.

**Comment by EladBezalel** [comment]
@neko1235 As i understand there's no unregister for that handler, am i right?

**Comment by neko1235** [comment]
@EladBezalel Correct.

**Comment by EladBezalel** [comment]
Would you be nice and submit a PR? :)

**Comment by ThomasBurleson** [comment]
@neko1235 - nice catch! 👍

**Comment by neko1235** [comment]
Sure, I will submit a PR.
Thank you.

**Comment by crisbeto** [comment]
@neko1235 have you been looking at this? Otherwise I can take care of it.

**Comment by neko1235** [comment]
@crisbeto I tried to remove the event handler in `tElement.on('$destroy')`, but it didn't seem to help, probably, because it's attached in `compile()`. I'm not sure how to fix this at this point. Please feel free to take a look.
Thank you

**Comment by crisbeto** [comment]
Great, thanks. Did you use any tools (apart from the Chrome dev tools profiler) to diagnose this one and the other leaks that you reported?

**Comment by neko1235** [comment]
I'm only using Chrome dev tools.
