### ISSUE TITLE
mdAutocomplete: Memory leak

### ISSUE THREAD

**Issue by neko1235** [angular/material#7994]
The event handler in [autocompleteController.js](https://github.com/angular/material/blob/v1.1.0-rc2/src/components/autocomplete/js/autocompleteController.js#L72) is leaking.
```
$element.on('focus', focusElement);
```

**Comment by neko1235** [comment]
I don't know if this is related, but [this line](https://github.com/angular/material/blob/v1.1.0-rc2/src/components/autocomplete/js/autocompleteDirective.js#L182) seems to also cause a leak.
```
ng-if="$mdAutocompleteCtrl.loadingIsVisible()"
```

**Comment by crisbeto** [comment]
Could you provide some more info? I'm not seeing how this could be causing a leak.

**Comment by neko1235** [comment]
This is what I get in my app.
![download](https://cloud.githubusercontent.com/assets/13606126/14477433/b4781cd4-00c2-11e6-9d2c-a7ca0db7d553.png)

**Comment by neko1235** [comment]
Well, here is another use case.
I am switching to another view in `md-selected-item-change` by calling `$location.path()` and a scope containing the selected item is left in the jQuery cache (tried a few jQuery versions). Since all scopes are connected to each other, this is causing the entire view to stay in memory forever.

![tmtozpipna3](https://cloud.githubusercontent.com/assets/13606126/14515772/d55bcdf2-01b1-11e6-8d47-8664628fe069.png)

Please let me know what you think.

**Comment by EladBezalel** [comment]
Thank you @neko1235!
A PR would be very welcome!

**Comment by neko1235** [comment]
@EladBezalel, These appear to be 3 different issues and I'm not yet able to isolate and reproduce them. I will get back to you when I get more info.

**Comment by neko1235** [comment]
The last issue is a memory leak in md-virtual-repeat. I am submitting a separate bug for it.

**Comment by ThomasBurleson** [comment]
@neko1235 - please provide a CodePen that demonstrates the memory leak. Currently we cannot find any substantive memory leak. We will re-open upon submission of a valid Plunkr/CodePen.
