### ISSUE TITLE
md-list-item: should have option to disable wrapping in button when it has ng-click, ng-href or other similar attribute

### ISSUE THREAD

**Issue by Senthe** [angular/material#7996]
I need something like this:
`<md-list-item ng-click="something()"> ... </md-list-item>`

But it is compiled to:
```
<md-list-item role="listitem" tabindex="-1" class="ng-scope md-clickable">
  <button class="md-no-style md-button" type="button" ng-transclude="" ng-click="something()">
    ...
  </button>
</md-list-item>
```

Relevant part of code:
```
if (tAttrs.ngClick || tAttrs.ngHref || tAttrs.href || tAttrs.uiSref || tAttrs.ngAttrUiSref) {
    wrapIn('button');
}
```

This wrap shouldn't be forced. I think it should be possible to turn off wrapping or at least make the wrapper a div, not a button. This right now causes layout issues (md-list-item can be quite a big element of the page containing a lot of stuff) and can generate invalid HTML with buttons inside buttons.

I use version 1.0.6.

**Comment by DevVersion** [comment]
@Senthe This has been changed recently. It should be a div now.

```html
<md-list-item>
  <div ...>
    <button ...>Click Executor</button>
    <div class="md-inner-content">My content</div>
    <div class="_md-secondary-container">..</div>
  </div>
</md-list-item>
```

The changes are available since `1.0.7`

**Comment by Senthe** [comment]
Okay, thank you. I'll upgrade my bower config.

**Comment by DevVersion** [comment]
@Senthe Awesome, I will close that issue, since the button is not present anymore. If you have something else related to this issue, and you want me to reopen it, let me know :)

**Comment by Senthe** [comment]
@DevVersion So, I did upgrade to 1.0.7 and the
```
if (tAttrs.ngClick || tAttrs.ngHref || tAttrs.href || tAttrs.uiSref || tAttrs.ngAttrUiSref) {
        wrapIn('button');
      } 
```
is actually still present there and works as previously, wrapping md-list-item content in button. Are you sure the fix went through to this version?

**Comment by DevVersion** [comment]
@Senthe I'm sorry, These changes are available in the latest major release, which is `v1.1-rc2`.

**Comment by Senthe** [comment]
@DevVersion It's still present in `v1.1.0-rc2-master-fb4670f` I just downloaded. Am I crazy or what : )

**Comment by DevVersion** [comment]
@Senthe In my case it's working as expected. 

The content is no longer wrapped inside a button.

- http://codepen.io/DevVersion/pen/RaMRxW

**Comment by Senthe** [comment]
@DevVersion Oh you're right, it doesn't wrap content in a button, just adds a button which handles click. Well I guess this solves my problem. Thanks.

**Comment by peio72** [comment]
Sorry still having this md-button wrap using a ng-click on a md-list-item ? 

Still no way to avoid that and keep normal md-list-item wrapping with ng-click ?

Thanx for your help.
