### ISSUE TITLE
How to give badge's content a not static value

### ISSUE THREAD

**Issue by SAM-BI** [angular/material#7999]
Hello all,
in Fuse-demo there are 2 examples (mail & todo) of using a notification icon in a navigation-item:
`msNavigationServiceProvider.saveItem('app.module', {
            title    : 'Module',
            icon     : 'icon-checkbox-marked',
            state    : 'app.module',
            **badge : {
                content: 2,
                color  : '#F44336'
            }**,
            translate: 'MODULE.MODULE_NAV',
            weight   : 1
        });`
I want to set the content the value of **ModuleData.length** which is in the state 'app.module' configutration:
`resolve: {
            	**ModuleData**: function ($stateParams, msApi)
                {
                    return msApi.resolve('module@getAll');
                }
            }`

But does not work and I receive:
> Failed to instantiate module app.module due to: ModuleData is not defined

Is it possible to make **content **as I want?

Thx

**Comment by DevVersion** [comment]
@SAM-BI Sorry, it seems like your issue is not related to ngMaterial. Can you take a look again?

**Comment by SAM-BI** [comment]
that's right, thx DevVersion :)

**Comment by shennero** [comment]
@SAM-BI did you ever figure this out? I'm having the same issue.  Thanks!

**Comment by VT-Zhang** [comment]
You can only access Provider in config phase. Use "msNavigationService" instead of "msNavigationServiceProvider" in the controller rather than in the config.
