### ISSUE TITLE
md-select-on-match on md-autocomplete doesn't work properly in case of substring

### ISSUE THREAD

**Issue by beny78** [angular/material#8005]
Why md-select-on-match select anything if the list contains several elements.

Here is an example of malfunction: 
searchText: "Al"
matches: ["Al", "Alabama"]
No item is selected, but searchText matches one item

I have created a codepen. I duplicate the angular material exemple, but I added "Al" in the list of countries. Enter "Al" and click outiside to close the menu. The searchText will be "Al" but selectItem will be null while "Al" is in the list.
http://codepen.io/anon/pen/JXpxEM

**Comment by topherfangio** [comment]
The docs don't currently state this, but the code first checks to see if there is exactly 1 match, then, it checks to see if it matches exactly. So in your case, there are two matches, so the `md-select-on-match` breaks out before attempting the comparison.

@EladBezalel What do you think of this functionality? Should we modify it to select even if there are multiple matches, or should we update the docs to mention that it only fires if there is one potential match?

**Comment by beny78** [comment]
If you don't select it, it would be nice to clear the display value (searchText). In my case, when I submit my formular, I have an error because no item is selected but "Al" is displayed. This is a strange behaviour.

**Comment by EladBezalel** [comment]
I think we should select the first no matter what..

This is a really weird behavior

**Comment by topherfangio** [comment]
Okay, agreed then.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by madmaxlax** [comment]
what if there isn't an exact match but only one remains in the list, can we still auto select that one? 
ie [monkey, baboon, gorilla]
if you search 'monk' there's only one possible answer,
