### ISSUE TITLE
Menus don't close when another menu is selected

### ISSUE THREAD

**Issue by DonBranson** [angular/material#8006]
This issue is visible at https://material.angularjs.org/latest/demo/menuBar, at least in Linux/Firefox and Android Chrome. To observe it, click in succession on File, Edit, then View. Note that the first two menus are still open along with the third. We could use a fix or a workaround for this.

**Comment by DonBranson** [comment]
It does appear to work in IE.

**Comment by topherfangio** [comment]
@DonBranson Is this the same as #7948?

**Comment by DonBranson** [comment]
I don't think so. Our issue is that menus aren't closing. The other ticket looks like they're opening on the wrong events.

However - it does look like https://material.angularjs.org/latest/demo/menuBar is behaving correctly now, so perhaps the issue's been corrected.

**Comment by topherfangio** [comment]
Okay, we literally just pushed a small change that corrected the de-registration of some event handlers, so perhaps that was related. I'm going to go ahead and close this now; please let us know if you experience it again and we can reopen.

**Comment by yasarhameed** [comment]
![main share click](https://cloud.githubusercontent.com/assets/26715684/24361604/f6478960-1327-11e7-97f9-d663d2fad063.png)
![new document](https://cloud.githubusercontent.com/assets/26715684/24361652/1296e6ce-1328-11e7-8657-2fadc57282ae.png)
Please note the difference when i click File-> Share click and File ->New -> Document dialog not ocupy full view for main menu and sub menu click

**Comment by topherfangio** [comment]
@yasarhameed That is an issue with the demo not properly setting the parent of the dialog. It should be the parent `<body>` element, but it looks like it was set to the demo container instead.

If you are seeing this in your app, I would suggest modifying the `parent` option to point higher up in your DOM (ideally the `<body>` tag or wherever your `ng-app` directive is placed).

If you're specifically talking about the demos being incorrect, could you please open a separate issue for the docs?
