### ISSUE TITLE
mdGesture: Memory leak?

### ISSUE THREAD

**Issue by neko1235** [angular/material#8010]
Please see https://jsfiddle.net/neko1235/uouudntg/2/
I am using a 3rd party library that attaches itself to those leaking nodes, what results in the whole angular scope tree leaking.
![screenshot from 2016-04-12 12 28 15](https://cloud.githubusercontent.com/assets/13606126/14472984/b858898c-00aa-11e6-9353-ae89ba80bf6c.png)

**Comment by EladBezalel** [comment]
@neko1235 can you point where the leak is coming from?

**Comment by neko1235** [comment]
@EladBezalel, The problem is when the view changes, `lastPointer` keeps a reference to an element from the previous view, which in turn has a reference to a scope.
The workaround here is to click anywhere, but this is very annoying and is not always possible (e.g. when event bubbling is prevented).

**Comment by ThomasBurleson** [comment]
This appears to be in the Gestures.js code...

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
