### ISSUE TITLE
add `background-contrast` for dark themes

### ISSUE THREAD

**Issue by ilovett** [angular/material#8014]
All other colors have a contrast value, IE: `{{ primary-contrast }}`, `{{ accent-contrast }}`, and `{{ warn-contrast }}`, but no love for background.  I see there is a notion of `{{ foreground-* }}` but these values appear to be hardcoded at glance depending on whether or not the theme is dark, instead of relative to what the background color actually is.

Or foreground colors could actually be calculated from background (or both)

```
md-icon.md-THEME_NAME-theme {
  color: '{{foreground-2}}';
}

md-icon.md-THEME_NAME-theme {
  color: '{{ background-contrast }}';
}

md-icon.md-THEME_NAME-theme {
  color: '{{ background-contrast-2 }}';
}
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
