### ISSUE TITLE
md-bottom-sheet is broken, also docs demo

### ISSUE THREAD

**Issue by jakubweber** [angular/material#8018]
See https://material.angularjs.org/latest/demo/bottomSheet or screenshot

![bottomsheet](https://cloud.githubusercontent.com/assets/5078760/14494617/ff313ce6-018b-11e6-866e-e739be2e024b.png)

1.1.0-rc2, chrome browser

**Comment by sdesmond** [comment]
What are you expecting to see here, and how is it broken?

**Comment by jakubweber** [comment]
items of bottomsheet are cut and labels below icons due cut aren't visible

**Comment by sdesmond** [comment]
Good catch, it looked to me like just a row of icons.
