### ISSUE TITLE
SideNav with overlay force scroll content to top

### ISSUE THREAD

**Issue by OneMuppet** [angular/material#8020]
Here is a video displaying an issue where opening the side nav with an overlay will force the content to scroll to top. The side nav without the overlay works fine.

https://dl.dropboxusercontent.com/u/8318643/AngularMaterialDesignBug%20-%20sidenav%20with%20overlay.mov

**Comment by DevVersion** [comment]
@OneMuppet This is a duplicate of #5850 - A PR was already pending but it is now outdated and needs some work.
