### ISSUE TITLE
Tooltip should not show if content is empty

### ISSUE THREAD

**Issue by sdesmond** [angular/material#8021]
Pen at http://codepen.io/anon/pen/bpvBJV shows one normal tooltip and one empty one.

If the tooltip content is empty, consider not showing anything instead of showing an empty tooltip.  The Angular Bootstrap team does this (empty strings and undefined/null don't show) and it makes for very easy conditional tooltips.

**Comment by DevVersion** [comment]
Yes, I agree - this would be a useful enhancement.
