### ISSUE TITLE
angular.bootstrap Warnings

### ISSUE THREAD

**Issue by randallmeeker** [angular/material#8023]
When an empty angular app is initiated via `angular.boostrap()` 

I get all these warnings. 

![screen shot 2016-04-13 at 12 36 23 pm](https://cloud.githubusercontent.com/assets/2538537/14503205/a288be4a-0174-11e6-8b0c-6fe12912113d.png)

**Comment by sdesmond** [comment]
Please include the versions you are using (AngularJS and Angular Material).  A link to a working example would be nice as well.

**Comment by randallmeeker** [comment]
I should have known to include code samples. Luckily you guys built one! The es6 branch of material-start will generate this error. 

https://github.com/angular/material-start/tree/es6

It is using angular 1.5.3 and Material/Master. 

I'm also seeing this in Material 1.0.7

**Comment by ThomasBurleson** [comment]
`angular.bootstrap()` has a required element which is the root of angular application.
Closing this issue as invalid.

**Comment by randallmeeker** [comment]
I'm confused. If the use of bootstrap() in this manner is invalid, does that mean your es6 starter app needs to be modified?

**Comment by ThomasBurleson** [comment]
@randallmeeker - why are you reporting a `material-start` issue here on Angular Material.

**Comment by randallmeeker** [comment]
I was not sure it was a `material-start` issue. I have experienced this on different builds and I was using `material-start` as a code example as requested when submitting the issue. When you told me my issue was invalid my follow up was a way of asking if `material-start` then had a bug. I'm happy to open up there, or with a little more research make attempt a PR once I understand where the bug comes from.

**Comment by ThomasBurleson** [comment]
@randallmeeker - FYI, I updated `angular/material-start`:
* master
* es5-tutorial
* es6

> Please refresh your locals and try again. Also plz report material-start issues on the material-start repository. THx.
