### ISSUE TITLE
[Feature Request] md-chips - using an array of objects without having to use a custom chips template

### ISSUE THREAD

**Issue by peffreycollins** [angular/material#8025]
It would be nice to be able to bind to an array of name-value objects without having to implement a custom chips template when using the md-chips directive. 

Per the current spec, it appears that devs can only display an ordered set of objects as chips by using a custom template.

**Comment by topherfangio** [comment]
@peffreycollins Can you give a quick example of the input you want to provide, and what the chips should display?

**Comment by ThomasBurleson** [comment]
Will not fix.
