### ISSUE TITLE
Change Font Weight

### ISSUE THREAD

**Issue by Nextt1** [angular/material#8027]
I want to use Roboto Light and Robot Thin as my primary font. Is there any way I can do that ?

**Comment by sdesmond** [comment]
Please use the issues for actual problems or feature requests.  You can request help at the CodePen community (http://codepen.io/team/AngularMaterial/), StackOverflow or the Google Group (https://groups.google.com/forum/#!forum/ngmaterial)

In response to the question, please read the section on Typhgraphy https://material.angularjs.org/latest/CSS/typography.

> The Roboto font will be not automatically loaded by Angular Material itself. The developer is responsible for loading all fonts used in their application.
