### ISSUE TITLE
Does a palette need to be registered with a theme to be used with md-colors?

### ISSUE THREAD

**Issue by minlite** [angular/material#8031]
Hi,

I was testing out the new `md-colors` directive in my project and I came across an issue. Apparently the only way to get a palette to work with the md-colors directive is to register it as a `primary`, `accent`, `warn`, or `background` palette for a theme or else the `$mdColors` service will throw the following error: 

`mdColors: couldn't find 'example' in the palettes.`

In other words, just doing the following wouldn't work:

```js
$mdThemingProvider.definePalette('Example', {
                    '50': '#ffffff',
                    '100': '#f2f9fe',
                    '200': '#bde1fc',
                    '300': '#79c3f8',
                    '400': '#5cb6f7',
                    '500': '#3fa9f5',
                    '600': '#229cf3',
                    '700': '#0c8eeb',
                    '800': '#0b7ccd',
                    '900': '#096bb0',
                    'A100': '#ffffff',
                    'A200': '#f2f9fe',
                    'A400': '#5cb6f7',
                    'A700': '#0c8eeb',
                    'contrastDefaultColor': 'light',
                    'contrastDarkColors': '50 100 200 300 A100 A200 A400'
                });
```

It has to be registered like this before being used:

```js
$mdThemingProvider.theme('default')
                    .primaryPalette('example');
```

Is this the intended behavior, or am I missing something in my implementation? 

Miro

**Comment by ThomasBurleson** [comment]
Intended.

**Comment by minlite** [comment]
Thanks for the reply.

Any plans for adding a coloring method independent from themes? I think a lot of brands have a set of colors that they want to use on their buttons and other elements and it can be more than 4. It's a pain having to define a theme for every 4 colors and keep track of what color is in what theme.

**Comment by ThomasBurleson** [comment]
@minlite - can you provide more details, sample usage, etc. ?

**Comment by minlite** [comment]
Sure. For instance this is a sample design for which there is no simple way of implementing using the current coloring services:

<img width="575" alt="screen shot 2016-04-13 at 8 08 02 pm" src="https://cloud.githubusercontent.com/assets/878667/14516010/d6f071d4-01b3-11e6-9922-072b6c7c291a.png">

The reason is that this design has buttons with 5 different main colors (dark blue, blue, green, red, and light grey) so for implementing it we would need to have two themes because we can't register more than 4 palettes with one theme. 

Of course I can just sneak in all the colors into a single palette and use hues to get them up, but a more structured solution would be better.

Or maybe I'm misunderstanding the use of palettes and hues?

**Comment by amritk** [comment]
+1 @minlite  I'm in the same boat, four colors is just not enough to cover what our designers give us.

**Comment by ThomasBurleson** [comment]
Themes are intended as consistent styling options for your entire application. You are welcome to override your components with custom, specific CSS styles (to color). You may also wish to use [$mdColors](https://material.angularjs.org/latest/demo/colors) to easily theme-color your components.
