### ISSUE TITLE
yet another md-tooltip design flaw

### ISSUE THREAD

**Issue by djfd** [angular/material#8032]
Hi,

why document.body is a tooltip parent?

for example, we have a some element and set tooltip for it. what will happen on that element detach or remove? tooltip will not be able to hide/destroy self, so we often can see alone hanging tooltips on a pages

Why we cannot use nearest wrapping element as a parent?

Thanks

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by djfd** [comment]
out of curiosity, why?

**Comment by ThomasBurleson** [comment]
General questions should be asked on the Forum.
