### ISSUE TITLE
md-select's error UI inconsistency with md-input's error messages style

### ISSUE THREAD

**Issue by jakubweber** [angular/material#8035]
md-select 's error has different style (bigger font,..) compared to md-input 's error messages.

![md-select-error](https://cloud.githubusercontent.com/assets/5078760/14522035/f0def6a0-022c-11e6-9803-4e13cffc9038.png)
![md-input-error](https://cloud.githubusercontent.com/assets/5078760/14522056/0685a940-022d-11e6-8ef2-8b109800d32d.png)

1.1.0-rc3

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
