### ISSUE TITLE
md-list-item should support target attribute since it supports href

### ISSUE THREAD

**Issue by Sk1Zy** [angular/material#8038]
Following commit 12fe077 and issue #481

md-list-item should support the target attribute on anchors just like md-button does

**Comment by topherfangio** [comment]
It should already: http://codepen.io/topherfangio/pen/YqaRNo

Can you provide a Codepen of what you're expecting to do?

**Comment by Sk1Zy** [comment]
I am attempting to do exactly what you did in that codepen. But I see you're using the v1.1 RC but I'm using v1.0.7. That might make a difference, either way I can see that it works with v1.1 at least so I'll close this.
