### ISSUE TITLE
Docs(chips): UI/CSS - Container does not expand to number input placeholder; text overflows cards

### ISSUE THREAD

**Issue by david-meza** [angular/material#8039]
See screenshot below for issue details:

![2016-04-14_12-46-03](https://cloud.githubusercontent.com/assets/11840636/14536266/83f2aae2-023f-11e6-88e1-c62acb5aa68d.png)

From: https://material.angularjs.org/latest/demo/chips
Browser: Chrome Version 49.0.2623.112 (64-bit)
OS: Mac OS X El Capitan

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
