### ISSUE TITLE
Docs(chips): Autocomplete in contact chips always shows the first four no matter what the input is

### ISSUE THREAD

**Issue by david-meza** [angular/material#8040]
As you can expect, this doesn't allow you to select any other contact on the list. It also doesn't really autocomplete your search since you always get the same results.

![2016-04-14_12-59-41](https://cloud.githubusercontent.com/assets/11840636/14536605/4a4862ee-0241-11e6-8440-f207e35ba61f.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
