### ISSUE TITLE
IOS + md-list

### ISSUE THREAD

**Issue by 0101adm** [angular/material#8042]
AM 1.1.0-rc3

http://codepen.io/0101adm/full/vGRvZg/

md-list does not render properly on any browser on IOS.

left side is chrome on IOS, right side is chromes simulator on OSX.

![screen shot 2016-04-14 at 2 22 43 pm](https://cloud.githubusercontent.com/assets/5133412/14542496/63c29aea-024c-11e6-8e61-b969dc1e0cdc.png)

**Comment by topherfangio** [comment]
@0101adm Can you please provide a Codepen demo so that we can do some testing on potential fixes?

**Comment by 0101adm** [comment]
the codepen is included in my post.  is there something i am missing?

**Comment by topherfangio** [comment]
@0101adm Perhaps I am blind, but I am not seeing a Codepen link, just the images...

**Comment by ThomasBurleson** [comment]
@topherfangio  - http://codepen.io/0101adm/full/vGRvZg/

**Comment by rayita** [comment]
This is related with #8049 (same problem)

**Comment by topherfangio** [comment]
@0101adm This is a similar issue to the other one; moving the layout/flex/padding to a wrapping div fixes the issue: http://codepen.io/topherfangio/pen/revVex?editors=1000

**Comment by topherfangio** [comment]
I'm going to go ahead and close, please let me know if you're still having issues and we can investigate/reopen.
