### ISSUE TITLE
Putting release candidates in npm

### ISSUE THREAD

**Issue by patorjk** [angular/material#8046]
Any chance of putting release candidates like 1.1.0-rc3 in npm? (similar to how the angular project does it)

Not a huge deal or anything, but it would make it easier to try out new versions.

**Comment by pdore-netfore** [comment]
Any news?

**Comment by ThomasBurleson** [comment]
We will consider publishing v1.1.0-rc5  to npm also. Please note this will not happen until after Google IO

**Comment by ThomasBurleson** [comment]
Meanwhile try this:  `npm install http://github.com/angular/bower-material#v1.1.0-rc4 --save`

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
