### ISSUE TITLE
Angular 1.5.4 breaks md-tabs

### ISSUE THREAD

**Issue by craigsh** [angular/material#8047]
md-tabs works fine with Angular 1.5.3 but breaks with 1.5.4 - tabs don't get rendered.

**Comment by ThomasBurleson** [comment]
@craigsh - We are aware of this... tracking it down. Thank you.

**Comment by ThomasBurleson** [comment]
@craigsh - which version of Angular Material are you using [that causes this issue ]?

**Comment by craigsh** [comment]
I'm using 1.0.7 but can also reproduce this on 1.1.0-RC3 in the codepen for md-tabs by changing the angular js version first to 1.5.3 to check it works then 1.5.4 to see it break.

**Comment by ThomasBurleson** [comment]
@robertmesserle, @matsko  - FYI

**Comment by Narretz** [comment]
https://github.com/angular/angular.js/commit/21d148aedc29c7efba4131ff2ef6383b4700868c is the culprit, it seems

**Comment by Osmoss** [comment]
It works for me now. :+1:

**Comment by Narretz** [comment]
@Osmoss unlikely. Neither material nor angular have changed something yet.

**Comment by Osmoss** [comment]
But I just did "bower update"  and it works for me now

**Comment by messteno** [comment]
+1 http://codepen.io/mesteno/pen/RaMXjV

**Comment by ThomasBurleson** [comment]
This is a known issue with the Angular 1.5.4 release and the [**$compile change**](https://github.com/angular/angular.js/commit/21d148aedc29c7efba4131ff2ef6383b4700868c) in that release is being rolled back.

**Comment by ThomasBurleson** [comment]
Works now with Angular  >=1.5.5  or =< 1.5.3
