### ISSUE TITLE
autogrow textarea and max number of rows

### ISSUE THREAD

**Issue by cadilhac** [angular/material#8057]
I'm not sure how to set the max number of rows on an autogrow textarea. I simply set rows="3"...
The issue is that when I type a word and hit Enter, the word scrolls up and disappears. The only visible line waits that I type something else on the second line. As soon as I type a character, the textarea expands and shows 2 lines. So my first word becomes visible again. This happens again when I hit Enter on the second line. It scrolls up, hiding the first line, until I type a fresh new char.
I imagine this is not the intended behavior...

```
<md-input-container class="md-block">
    <label>Message</label>
    <textarea name="message" ng-model="vm.message" minlength="4" aria-label="message" required rows="3"></textarea>
</md-input-container>
```
Tested with RC3.

Secondary question: my dialog is in a md-dialog. When the textarea grows, the size (height) of the dialog increases abruptly. Is it possible to have a smooth growing animation?

**Comment by crisbeto** [comment]
The "rows" are considered the maximum (although there is a PR to change that behavior). After they're reached, the textarea should get the "md-textarea-scrollable" which should make it scrllable. What OS are you testng on (OSX/iOS don't show scrollbars until you start scrolling)?

As for the animation, we don't support it out-of-the-box, but you can manually add a transition on the height.

**Comment by cadilhac** [comment]
1. I checked under various desktop browsers under Windows.
The issue is not about scrollbar. It is about typing Enter and autogrow. When I type Enter, it does not grow one line. Instead, it scrolls one line. It does grow only after I type a new char on the new line.

2. Any link to do that (height animation) please?

**Comment by crisbeto** [comment]
1. Thanks, now it makes sense. That is fixed with #7991. It's because ngModel's listeners don't fire for enter and space characters at the end of input.
2. I don't have a link for that animation, but you can easily do it like this:

```css
textarea.md-input{
  transition: height 0.5s ease;
}
```

**Comment by cadilhac** [comment]
Thank you.
1. Is it in the head?
2. I don't know why, I thought transitions were not possible on size in general. But it works, thx.

**Comment by crisbeto** [comment]
1. It's still pending review.
2. They are possible, but you should keep in mind that the framerate might not be very good on slower devices/browsers, because animating the height causes layout for each frame.

I'll close this issue since it should be resolved when the PR gets merged, but we can continue discussing if you need any more help.
