### ISSUE TITLE
meta "theme-color" relative to toolbar theme

### ISSUE THREAD

**Issue by ram-you** [angular/material#8062]
Hi,
How to change  `<meta name="theme-color" content="#546E7A">`  content color relative to toolbar theme ?

Any idea is welcome.
Thank you.

**Comment by DevVersion** [comment]
@ram-you Very good question, at the moment we have no way to do that easily.

@topherfangio What do you think? I think this would be a useful enhancement?

**Comment by EladBezalel** [comment]
https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/theme-color
