### ISSUE TITLE
Custom md-subheader

### ISSUE THREAD

**Issue by forcewill** [angular/material#8063]
Is it possible to customize the **md-subheader** directive.
I tried for example
```
<md-subheader class="md-accent" layout="row">
    <span translate>Users</span>
</md-subheader>
```

with no success, i believe it would be an useful feature to have

**Comment by ThomasBurleson** [comment]
@forcewill - You have identified an issue with SubHeader which transcludes your custom content into a `<span>` instead of a `<div>`. We should fix this.
