### ISSUE TITLE
Sidenav appearing behind a bottomsheet overlay

### ISSUE THREAD

**Issue by cadilhac** [angular/material#8064]
I have a classic setup: toolbar at the top with a menu button and content underneath. The menu button triggers the opening of a sidenav.

When I have a bottom sheet opened, the overlay lies on top of the content, but not on top of the toolbar. If I click the menu button, the sidenav opens, but behind the overlay of the bottom sheet.
Compare that to a dialog. In this case, the overlay lies also on the toolbar and it's not possible to trigger the sidenav without first closing the dialog, which is logical. Shouldn't it be the same for the overlay of the bottom sheet?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
