### ISSUE TITLE
md-tabs with md-dynamic-height on Safari - scroll to the top

### ISSUE THREAD

**Issue by manuelagard** [angular/material#8065]
When selecting any tab with md-dynamic-height attribute on Safari, we can notice that during a short period, the tabs disappear during tab switching.
![lquhhrujmf](https://cloud.githubusercontent.com/assets/16802569/14567666/839568fe-0335-11e6-86f8-b4e5459132b5.gif)

I think this is due to the very short amount of time when the height = 0 during tab changing. This is very annoying when the tabs are located to the bottom of a page because, when you click a tab, the page randomly scrolls to the top.

No problem when md-dynamic-height is removed.
No problem on Chrome.

**Comment by ThomasBurleson** [comment]
Will not fix in ngMaterial1
