### ISSUE TITLE
md-button-icon: Icon not centered

### ISSUE THREAD

**Issue by epelc** [angular/material#8066]
Icons in `md-button`s are no longer centered vertically. There is more space on the top then to bottom.

See picture 
![image](https://cloud.githubusercontent.com/assets/5204642/14567912/61fe4e94-0304-11e6-857c-cb54d4a99d07.png)
You can see it easily if you set a background color on the icon so the full square is shown. But it's still noticeable without. See the button demo for an example https://material.angularjs.org/latest/demo/button

Adding `layout="row" layout-align="center center"` seems to fix but seems a bit overkill.

OSX 10.11.4
Chrome Version 50.0.2661.75 (64-bit)

**Comment by ThomasBurleson** [comment]
@epelc - Total overkill. Have any other suggestions ?

**Comment by epelc** [comment]
@ThomasBurleson didn't have much time to look as I'm traveling today and
this weekend. But I think the best way might be using the minimal required
fez attributes directly if I can't figure out what Css is causing it.

I was looking at the margin and padding highlights in chrome and it looks
like the icon gets pushed down out of where it should be in the highlights.

On Friday, April 15, 2016, Thomas Burleson <notifications@github.com> wrote:

> @epelc <https://github.com/epelc> - Total overkill. Have any other
> suggestions ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/8066#issuecomment-210546509>
>


-- 
Best regards,
Ed Pelc
*President*


Website: freightchick.com
Phone: 941-735-4047

**Comment by epelc** [comment]
@ThomasBurleson If you change `md-icon`'s `display` from `inline-block` to `block` it works. I think this is safe if we just apply it to `.md-icon-button md-icon` instead of `.md-button md-icon`. 

Basically adding the following css will fix the alignment.
```
.md-icon-button md-icon {
  display: block;
}
```

![image](https://cloud.githubusercontent.com/assets/5204642/14606179/fbb01684-0549-11e6-96db-73260eeca4ca.png)

I found this [codepen](http://codepen.io/edge0703/pen/iHJuA) with a few methods for getting `display: inline-block;` to center correctly. But I could not get any of them to work with angular-material's icon buttons. Angular material also appears to be using the second method by setting a `line-height` and `vertical-align`.
