### ISSUE TITLE
Fabricjs canvas inside Angular Material Tabs doesn't work

### ISSUE THREAD

**Issue by rak13** [angular/material#8071]
I have been trying to use [Fabric.canvas](http://fabricjs.com/) inside [angular material tabs](https://material.angularjs.org/1.0.7/demo/tabs) but that doesn't seem to work. Finally I want there to be multiple tabs with multiple canvases. For now I'm trying it with only one tab.

[This code without tabs seems to wok just fine, it allows free hand drawing with mouse](http://js.do/rak13/no-tabs)
But,
[this html code with angular material tabs doesn't let any drawing or event on the canvas](http://js.do/rak13/with-angular-material-tabs)

The javascript code (at the end) used in both the files are the same

How do I make it work?

**Comment by DevVersion** [comment]
This is caused by the transclusion of the tabs component. Through the transclusion, all the references to the original canvas will be lost and fabricjs can't keep track of them anymore.

```js
    var canvas =  new fabric.Canvas("myCanvas");
```

Maybe there should be a possibility to anchor the tab content.

**Comment by rak13** [comment]
there's a workaround [here](http://stackoverflow.com/questions/36660982/fabricjs-canvas-inside-angular-material-tabs-doesnt-work/36675788#36675788) but a callback function would be more preferable.

**Comment by ThomasBurleson** [comment]
Will not fix.
