### ISSUE TITLE
md-tool bar content alignment 

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#8076]
<img width="1117" alt="screen shot 2016-04-16 at 3 27 05 pm" src="https://cloud.githubusercontent.com/assets/6860473/14580326/bb646444-03e7-11e6-9ce1-eb278d40363d.png">

I want to align the content of the toolbar in middle of line but it is not coming. Please help me to get out of this issue.

**Comment by DevVersion** [comment]
Please provide a demo (codepen, plunkr etc.).

**Comment by jainshravan123** [comment]
I did not upload it anywhere. Please help me here.

**Comment by jainshravan123** [comment]
Click on the image then u'll see that both of the tabs are in the center of the whole screen and closed to each other.But i want to make them in a way that they should be coming in the center of their corresponding tabs.

**Comment by DevVersion** [comment]
@jainshravan123 You can vertically center your content in the toolbar by using the `md-toolbar-tools` class.

```html
<md-toolbar>
  <div class="md-toolbar-tools">
    Vertically Centered Text  
  </div>
</md-toolbar>
```

- http://codepen.io/DevVersion/pen/GZdjPO

**Comment by jainshravan123** [comment]
<md-toolbar ng-show="!showSearch">
                <md-tabs  md-center-tabs="true" md-stretch-tabs class="md-primary" md-selected="data.selectedIndex">
                     <md-tab id="tab1" aria-controls="tab1-content" flex >
                     Recent
                    </md-tab>
                    <md-tab id="tab2" aria-controls="tab2-content" flex>
                    Complete
                     </md-tab>
                </md-tabs>
 </md-toolbar>



This code , m using for this toolbar.

**Comment by jainshravan123** [comment]
<md-toolbar ng-show="!showSearch">
                <md-tabs  md-center-tabs="true" md-stretch-tabs class="md-primary" md-selected="data.selectedIndex">
                  <md-tab id="tab1" aria-controls="tab1-content" flex >
                    Recent
                  </md-tab>
                  <md-tab id="tab2" aria-controls="tab2-content" flex>
                    Complete
                  </md-tab>
                </md-tabs>
              </md-toolbar>

M using above code for this toolbar.

**Comment by jainshravan123** [comment]
<md-toolbar ng-show="!showSearch">
                <div class="md-toolbar-tools">
                  <md-button ng-click="toggleSidenav('left')" hide-gt-md aria-label="Menu">
                    <ng-md-icon icon="menu"></ng-md-icon>
                  </md-button>
                  <h3>
                    Dashboard
                  </h3>
                  <span flex></span>
                  <md-button aria-label="Search" ng-click="showSearch = !showSearch">
                    <ng-md-icon icon="search"></ng-md-icon>
                  </md-button>
                  <md-button aria-label="Open Settings" ng-click="showListBottomSheet($event)">
                    <ng-md-icon icon="more_vert"></ng-md-icon>
                  </md-button>
                </div>
                <md-tabs  md-center-tabs="true" md-stretch-tabs class="md-primary" md-selected="data.selectedIndex">
                  <md-tab id="tab1" aria-controls="tab1-content" flex >
                    Recent
                  </md-tab>
                  <md-tab id="tab2" aria-controls="tab2-content" flex>
                    Complete
                  </md-tab>
                </md-tabs>
              </md-toolbar>``

**Comment by jainshravan123** [comment]
M using following code for this tool bar.
`<md-toolbar ng-show="!showSearch">
                <div class="md-toolbar-tools">
                  <md-button ng-click="toggleSidenav('left')" hide-gt-md aria-label="Menu">
                    <ng-md-icon icon="menu"></ng-md-icon>
                  </md-button>
                  <h3>
                    Dashboard
                  </h3>
                  <span flex></span>
                  <md-button aria-label="Search" ng-click="showSearch = !showSearch">
                    <ng-md-icon icon="search"></ng-md-icon>
                  </md-button>
                  <md-button aria-label="Open Settings" ng-click="showListBottomSheet($event)">
                    <ng-md-icon icon="more_vert"></ng-md-icon>
                  </md-button>
                </div>
                <md-tabs  md-center-tabs="true" md-stretch-tabs class="md-primary" md-selected="data.selectedIndex">
                  <md-tab id="tab1" aria-controls="tab1-content" flex >
                    Recent
                  </md-tab>
                  <md-tab id="tab2" aria-controls="tab2-content" flex>
                    Complete
                  </md-tab>
                </md-tabs>
              </md-toolbar>`

**Comment by jainshravan123** [comment]
M using the following code for this toolbar.

`<md-toolbar ng-show="!showSearch">
                <md-tabs  md-center-tabs="true" md-stretch-tabs class="md-primary" md-selected="data.selectedIndex">
                  <md-tab id="tab1" aria-controls="tab1-content" flex >
                    Recent
                  </md-tab>
                  <md-tab id="tab2" aria-controls="tab2-content" flex>
                    Complete
                  </md-tab>
                </md-tabs>
              </md-toolbar>`

**Comment by jainshravan123** [comment]
M using the following code for this toolbar.



`<md-toolbar ng-show="!showSearch">
                <md-tabs  md-center-tabs="true" md-stretch-tabs class="md-primary" md-selected="data.selectedIndex">
                  <md-tab id="tab1" aria-controls="tab1-content" flex >
                    Recent
                  </md-tab>
                  <md-tab id="tab2" aria-controls="tab2-content" flex>
                    Complete
                  </md-tab>
                </md-tabs>
              </md-toolbar>`
