### ISSUE TITLE
mdButton: light text on dark colors has incorrect transparency level

### ISSUE THREAD

**Issue by apokusin** [angular/material#8077]
See design specification: [Material Style - Color](https://www.google.com/design/spec/style/color.html)
Implementation reference: [mdButton demo](https://material.angularjs.org/latest/demo/button)

The guidelines state that light colors on dark backgrounds, like primary and accent colors, should be white at 100% opacity. The current implementation sets transparency to 87%.

![screenshot](https://d.pr/py2a.png)

**Comment by DevVersion** [comment]
Yes, I can see that. Maybe the specs have changed that or we just missed it.

![image](https://cloud.githubusercontent.com/assets/4987015/14580697/da64bc52-03d5-11e6-9c29-cb0f5b8f2477.png)
