### ISSUE TITLE
FAB speed dial does not support ng-repeat for fab actions

### ISSUE THREAD

**Issue by randallmeeker** [angular/material#8079]
Looks different than #3224 despite the same title 

when using ng-repeat for actions, they peak out of behind the trigger

![image](https://cloud.githubusercontent.com/assets/2538537/14581768/95ac6620-03ba-11e6-82b6-fe445a61b569.png)

CodePen http://codepen.io/anon/pen/revjLY

Locally getting same result on ngMaterial / 1.1.0 | Angular 1.5

**Comment by IcanDivideBy0** [comment]
The doc has a word about that (https://material.angularjs.org/latest/demo/fabSpeedDial)

>You can easily use ng-repeat with the speed dial, but it requires a slightly different HTML structure in order to support the necessary DOM changes/styling.
>
>Simply ensure that your ng-repeat is on a div (or any other tag) that wraps your items.

**Comment by randallmeeker** [comment]
It's always in the docs. My bad. Thanks.
