### ISSUE TITLE
md-menu offset not calculating correctly

### ISSUE THREAD

**Issue by tspayne87** [angular/material#8080]
When you open a menu and you do not have a ng-click before the md-menu-contents tag it will get the first ng-click that may exist within the menu itself.  I was using data-ng-click to open my menu which is not being picked up by the init function.  I have a fix for this and its adding in the data-ng-click into the querySelector, an example is

Current:
triggerElement = $element[0].querySelector('[ng-click],[ng-mouseenter]');

Change To:
triggerElement = $element[0].querySelector('[data-ng-click],[ng-click],[data-ng-mouseenter],[ng-mouseenter]');

this is all within the init function in the MenuController.  I have tested this within my project and it seems to of fixed the issue for me.  I hope this helps.

**Comment by topherfangio** [comment]
@DevVersion I know you are working on a PR to assist in difference between `ng-click`, `data-ng-click`, `x-ng-click`, etc. Will this be fixed as well, or should we just update the querySelector as described above?

**Comment by DevVersion** [comment]
@topherfangio Yea, this will be fixed by my PR.
