### ISSUE TITLE
mdInkRipple not interpreting variable to disable

### ISSUE THREAD

**Issue by konsumer** [angular/material#8087]
Codepen [here](http://codepen.io/konsumer/pen/ONZENw)

In last items ripple should be disabled, but isn't.

`md-ink-ripple="doRipple"` `md-ink-ripple="!yes"` both ripple where `doRipple == false` and `yes == true`.

**Comment by konsumer** [comment]
I worked around it with this, but this seems terrible:

```
<script type="text/ng-template" id="ripplebutton">
STUFF IN MENU ITEM
</script>
<div ng-if="criteria" ng-include="'ripplebutton'" md-ink-ripple></div>
<div ng-if="!criteria" ng-include="'ripplebutton'"></div>
```

**Comment by konsumer** [comment]
I worked around it by using an inline template & `ng-if, but this doesn't seem right at all:

```html
<script type="text/ng-template" id="ripplebutton">
STUFF FOR MENU ITEM
</script>
<div ng-if="criteria" ng-include="'ripplebutton'" md-ink-ripple></div>
<div ng-if="!criteria" ng-include="'ripplebutton'"></div>
```

**Comment by ThomasBurleson** [comment]
@konsumer - This is a bug. Per the [online docs](https://material.angularjs.org/latest/api/directive/mdInkRipple): `or boolean (false or 0) for preventing ripple` should be supported at mouseDown.

**Comment by crisbeto** [comment]
@ThomasBurleson, @konsumer this doesn't seem to be a bug. `mdInkRipple` checks against the string value in `md-ink-ripple` (think of the the `@` binding on directives). The example works if you change the bindings to `md-ink-ripple="{{doRipple}}"` and `md-ink-ripple="{{!yes}}"`. [Here's a forked codepen that shows it](http://codepen.io/crisbeto/pen/eZjjXR).

I'll close the issue since we can't support both syntaxes at the same time.

**Comment by konsumer** [comment]
Ok. Sounds good. Is this in the docs? I noticed they say `false` not `'false'`.

**Comment by crisbeto** [comment]
It's directly stated, but if you look at the "Interpolated values" example:

```html
<any md-ink-ripple="{{ randomColor() }}">
  Ripples with the return value of 'randomColor' function
</any>
<any md-ink-ripple="{{ canRipple() }}">
  Ripples if 'canRipple' function return value is not 'false' or '0'
</any>
```

**Comment by konsumer** [comment]
Cool. Thanks for the info!
