### ISSUE TITLE
md-color overrides md-button hover and focus colors

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#8088]
as seen here: https://material.angularjs.org/latest/demo/colors

This is more important than it sounds for accessibility reasons. Trying to navigate with tabbing with keyboard won't show the user where focus is placed. Just by glancing at mdColors, I'm assuming it's a simple replacement for css with key/value pairs.

I suggest a key called 'palette' so users could instead write

    md-colors={palette: 'blue'}

and then, for example with md-button, would apply

```
  .primary {
    color: '{{primary-color}}';
    &.md-raised,
    &.md-fab {
      color: '{{primary-contrast}}';
      background-color: '{{primary-color}}';
      &:not([disabled]) {
        md-icon {
          color: '{{primary-contrast}}';
        }
        &:hover {
          background-color: '{{primary-600}}';
        }
        &.md-focused {
          background-color: '{{primary-600}}';
        }
      }
    }
```

**Comment by ThomasBurleson** [comment]
Invalid Issue.
