### ISSUE TITLE
Add md-ink-riple docs

### ISSUE THREAD

**Issue by epelc** [angular/material#809]
Currently the `md-ink-ripple` has no documentation. From what I found in the docs source it's used as `md-ink-ripple="#333"` where `#333` is the ripple color.

**Comment by MarcosPortugal** [comment]
I third the request :+1:

**Comment by marcysutton** [comment]
@ThomasBurleson I'm concerned that making the ink ripple public for any element is just asking for it to be abused. I highly recommend developers use `md-button`, which already has ink ripple and accessibility support. 

Quoting @epelc on #1169:
> Currently my only need for it is on my side nav however I think you are working on refactoring the sidenav on the docs to use md-button and ul instead. So I wouldn't need this anymore.

**Comment by MarcosPortugal** [comment]
@marcysutton I don't think you should decide what is and isn't documented based on how people can misuse it. I mean if it's helpful and would benefit some developers, why keep it from being documented just because can start adding ripples to everything?

**Comment by epelc** [comment]
@MarcosPortugal It is currently a private directive which is why it wasn't documented. The argument is about whether or not it should be made public which would in turn require docs for it. Also what is your use case for this? Is it something you could do with `md-button` instead and get the aria benefits? I've stated why I needed it above but It shouldn't be a problem soon.

I think we need some example use cases to really decide if this should be made public as it would likely lead to misuse as @marcysutton was saying. Perhaps we could fix whatever these use cases are directly instead of this general catch all.

**Comment by MarcosPortugal** [comment]
@epelc I was using documenting as a term for "making public" in my comment. And no, I can't use buttons instead. Think about something like http://fortawesome.github.io/Font-Awesome/icons/ with the icons being selectable by clicking on the,.

**Comment by marcysutton** [comment]
That sounds like a button to me, which most definitely requires accessibility support. Are you saying the visual style of md-button doesn't match your design? Is there another place in the Material Design spec that you're hoping to get ironed out? This request is so broad, that by opening a public API for the ink ripple, we are also opening ourselves up to a lot more accessibility support. If you can help us narrow down the use cases, it will make a better case for exposing it.

**Comment by epelc** [comment]
@MarcosPortugal I wasn't saying you have to use a button I just think we can probably solve this more directly then making `md-ink-ripple` public which would then make it really hard to remove later on.

If you want to use font awesome with buttons they work perfectly fine I use them all over like so
```
<md-button aria-label="Settings">
  <i class="fa fa-cogs"></i>
</md-button>
```

If you want a more radio group style element but with icons then we can probably try to address that directly.

**Comment by MarcosPortugal** [comment]
@marcysutton I agree. But no, it is not a button at all. (in my use case) It's a div that you can click on, which gives it a "selected" class. I'll just explain it here:

 It's a container inside a dialog where a user can choose an icon from a wide selection of them, displayed as divs with their name in a span under them. The user can click one of them (seeing the ink effect), and it now has a "selected" appearance (different background color). The user can then press one of two buttons at the bottom, "Choose" or "Cancel".

 It's a situation where I believe the ink ripple effect works really well for the selection animation, and fits nicely with the rest of the design. But it can't be replaced by buttons.

 @epelc Naa man it's not that, the page I sent was just an example of the way the divs are displayed but the click action is very different. But thanks :)

**Comment by marcysutton** [comment]
If I'm understanding correctly, it sounds like it also won't be usable without a mouse. This is exactly the kind of thing we're trying to avoid.

**Comment by MarcosPortugal** [comment]
Why wouldn't it? Just tap one of the divs and it's selected as well.

**Comment by epelc** [comment]
I think she referring to people only using keyboards.

Also maybe we could add an option to specify your own icon for the radio group. It seems to do what you want.

**Comment by epelc** [comment]
@MarcosPortugal As a side note for reasons to make your app accessible think of power users. Any power user or corporate person that has to do data entry would really hate your app if they couldn't use tab to get around. Theres also many other reasons of course but maybe that will hit home.

**Comment by MarcosPortugal** [comment]
@epelc Actually a radio group defines it pretty well. Thanks for that :) The thing is it's not a circle with text in front, it's a radio group comprised of divs with an icon and text under them (think an android app icon).

**Comment by MarcosPortugal** [comment]
@epelc The app I'm working on is a kind of new tab page, it won't really have power users or heavy data entry, as a lot of other apps don't.

**Comment by epelc** [comment]
@MarcosPortugal I get what you mean.
 I was suggesting we extend the radio group to support this use case as it already has 90% of what you need.

Also any chance we can move to [gitter](https://gitter.im/angular/material) this seems a bit long for github issues

**Comment by marcysutton** [comment]
Not just keyboards, but all assistive technologies–including touch devices. You can't access a `<div>` from a desktop keyboard or screen reader without adding accessibility support: `tabIndex="0"`, alternative text (a.k.a. a label for the icon), and a `keypress` event. Divs are not interactive elements by default like buttons are. Even on touch devices where you can "just tap", to make something discoverable by a screen reader user, the element must be announced as an interactive element such as a button. ngAria can add a little bit of support here, but starting with a button or radio-button seriously will seriously make your life easier when it comes to accessibility because you get so much for free.

**Comment by marcysutton** [comment]
Also +1 to moving discussion to gitter, or the [forum](https://groups.google.com/forum/#!forum/ngmaterial).

**Comment by MarcosPortugal** [comment]
Well I do get your point. I am however not very concerned with accessibility due to the "casual" nature of my app. I am happy enough with the example that one of the developers provided in another issue, which works for me. I just thought it would be nice to have it documented, since that would make other developers like me who just need a quick way to make something have the ink ripple effect on click.
 Not making it public won't stop people like me from using it, it will just make their life harder by having to search deeper.

**Comment by epelc** [comment]
@MarcosPortugal It's essentially documented above the use is very simple just add `md-ink-ripple="#hex"`

However by including it in the docs we open ourselves up to supporting it which is a burden on everyone. It also basically encourages people to use it which in most cases they shouldn't be. I think the real base of this problem is that we are still in early development and we have not satisfied everyones use cases yet.

**Comment by epelc** [comment]
@ThomasBurleson Do you have any thoughts on this as you reopened it.

I'd be perfectly fine and happy if we closed this again. If people need this they will go dig for it until hopefully we have implemented enough elements/etc to fit most peoples use cases. As @marcysutton was saying using this alone is terrible for accessibility and it doesn't seem like it's a good idea to formally document this and sign that contract.

**Comment by MarcosPortugal** [comment]
+1 for closing this, and expanding the radio group use cases to fit ones such as the one I exemplified.

**Comment by MarcosPortugal** [comment]
Another use case, spotify radio station buttons

http://i.imgur.com/wMLh1BL.jpg

How would an ink ripple effect be applied to something like this by a developer using the framework?

**Comment by marcysutton** [comment]
@MarcosPortugal that looks more like `md-card`, which I am in the middle of spec'ing out in terms of interactive elements. About to post a comment to #457.

**Comment by MarcosPortugal** [comment]
Well since a card is such a broad category, I guess that would fit most, if not all use cases.

**Comment by marcysutton** [comment]
Recommending we keep ink-ripple internal and instead ask for specific use cases which we can make interactive accessibly, such as interactivity on `md-card`.

**Comment by rknell** [comment]
zOMG just discovered this!!!

![733581](https://cloud.githubusercontent.com/assets/5875053/8666305/c77a4c42-2a32-11e5-85c1-ac2c94d192d2.jpg)


To anyone else who wants to use it here are the docs

Create an element like this:

```html
<div md-ink-ripple='#333' style="position:relative"></div>
```

**Comment by brianpkelley** [comment]
I landed here looking for documentation for md-ink-ripple.   My use case is adding it to a `tr` element in a ng-table where the entire row is clickable.  This results in the entire table having the md-ink-ripple.
