### ISSUE TITLE
md-select-subheader inside md-tabs or md-subheader doesnt work

### ISSUE THREAD

**Issue by bietech** [angular/material#8090]
Hi,
the searchbox in my md-select-subheader doesnt work if i put it inside the md-tabs and md-subheader but it is working outside. Please help. thanks

```xml
<md-tabs md-dynamic-height md-border-bottom>
      <md-tab label="Purchase Order">
            <md-subheader class="subheader">
                  <md-input-container>
                    <label>Select vendor</label>
                    <md-select ng-init="getAllSuppliers()" ng-model="selectedSupplier" md-on close="clearSearchTerm()" data-md-container-class="selectdemoSelectHeader">
                   <md-select-header class="demo-select-header">
                        <input ng-model="searchTerm" type="search" placeholder="Search vendor.." class="demo-header-searchbox _md-text">
                     </md-select-header>
                        <md-option ng-value="supplier" ng-repeat="supplier in suppliers | filter:searchTerm">{{ supplier.name }}</md-option>
                    </md-select>
                  </md-input-container>
              </md-subheader>
         </md-tab>
 </md-tabs>
```

**Comment by gimox** [comment]
same problem, custom directive inside md-tabs not work.

**Comment by gimox** [comment]
angular 1.5.5 fixed the problem

**Comment by bietech** [comment]
hi gimox, thanks for the reply but its still not working on angular 1.5.5 :(

**Comment by bietech** [comment]
this is the sample problem..please help

[http://codepen.io/aldesabido/pen/GZGRBR](url)

**Comment by topherfangio** [comment]
Can you please provide a Codepen demo and describe how it is not working? Is it not clickable, are you not able to select options, etc.

Thanks!

**Comment by bietech** [comment]
Hi, I already got the solution. We have the same solution on this issue. Thanks :)

#8100 md-select-header inside md-tab not working

**Comment by felipemangalo** [comment]
ng-keydown="$event.stopPropagation()"
