### ISSUE TITLE
CSS - Toast-Content - Wrong height adjustment

### ISSUE THREAD

**Issue by graphefruit** [angular/material#8092]
Hello Team,

the md-toast-content doesn't expand to the max-height of 168px.
```   max-height: 168px; ```
Looks like: 
![image](https://cloud.githubusercontent.com/assets/6260244/14602544/db4c43d0-0568-11e6-9424-aa7a1397ad5e.png)

The problem of this is that the height is set to 0.
``` height: 0 ```

After setting the height to auto, it works like expexted.
``` height:auto ```

![image](https://cloud.githubusercontent.com/assets/6260244/14602582/043ffaac-0569-11e6-809c-85bb79bb7f72.png)

This is specially a problem on Windows-Phones with smaller displays. Or some more information in the toast-popup.

![image](https://cloud.githubusercontent.com/assets/6260244/14602622/2ef41cc4-0569-11e6-8620-c8d0860abb40.png)

Anybody can see the same problem?
Greetings
Graphefruit

**Comment by DevVersion** [comment]
@graphefruit Definitely can see the issue. 

- http://codepen.io/DevVersion/pen/wGxxJZ

@topherfangio Can you recall, why you added the `height: 0` property to the css.
Removing that line is working like a charm?
