### ISSUE TITLE
 md-highlight-flags: ^ and $ not working properly

### ISSUE THREAD

**Issue by ivoviz** [angular/material#8096]
Using `md-autocomplete` with custom template where we have multiple span tags with `md-highlight-text` and `md-highlight-flags` the `^` and `$` flags don't work.

[Pen here](http://codepen.io/anon/pen/pyVXLP)

Reproduce:
- Type 'd'

Only the first `D` should be red, but in fact, two more gets highlighted as well.
I can try and put together a PR if needed.

**Comment by DevVersion** [comment]
@ivoviz A PR is as always welcome. 

Just let me know if you start working on that, otherwise someone of us would waste his time :)

**Comment by ivoviz** [comment]
@DevVersion I've just created a PR.
