### ISSUE TITLE
mdPreventMenuClose: doesn't work with radio or checkbox type mdMenuItem

### ISSUE THREAD

**Issue by diminutivesloop** [angular/material#8110]
Setting the `md-prevent-menu-close` attribute on a `md-button` element fails to prevent the enclosing menu from closing when the button is clicked if the enclosing `md-menu-item` element has its `type` attribute set to either "radio" or "checkbox". 

This issue is reproducible for Angular Material 1.0.7 across all major browsers.

http://codepen.io/anon/pen/qZKNmK

**Comment by ThomasBurleson** [comment]
Please verify this issue still exists in HEAD.

**Comment by ThomasBurleson** [comment]
@topherfangio - it seems like this API is becoming complicated?

**Comment by topherfangio** [comment]
@ThomasBurleson Perhaps, but I think this is more of an issue with attempting to reuse the menu code within the menu-bar. The API should never have been available in the plain menu IMO.

**Comment by DevVersion** [comment]
@topherfangio Agree, when I investigated at the issue, I was wondering, why the `menu-item` directive was placed inside of the `menuBar` component.

It just shows in my opinion, that the `menu-item` directive is special-*designed* for the `md-menu-bar`.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
