### ISSUE TITLE
difficulty with sidenav and content height discrepency

### ISSUE THREAD

**Issue by ciel** [angular/material#8113]
I'm having a hard time getting the `<sidenav>` to work like I expect it to because of a discrepancy in the height of my content and the height that the nav opens with.

Reading [this issue](https://github.com/angular/material/issues/1092) you say the solution is to adjust the layout correctly; But that's not proving to be an acceptable solution for this situation.

I'm working with this layout;

````
    <div class="body-content container md-padding" layout="row">
        <div layout="row" class="container">
            <md-sidenav class="md-sidenav-left md-whiteframe-4dp fill-height"
                        style="padding-top: 60px;"
                        md-disable-backdrop
                        md-component-id="left"
                        layout-fill>
                <!-- menu content -->
            </md-sidenav>
            <md-content>
                <md-button class="md-fab md-primary md-fab-top-right" aria-label="Add"">
                <md-icon md-font-set="material-icons">add</md-icon>
                </md-button>
                <!-- content -->
            </md-content>
        </div>
    </div>
````

Where `container` is a class that sets the `margin: 0 auto;` and a width of `1048px` to center and fix the width of the content.

Here's the issue. If the `sidenav` is outside the `container`, it works but it only spans the height of the viewing area; that is the current height of the page disregarding the content. So there is a funky disconnect happening here - if the user tries to scroll or anything, the sidenav is cut off and it looks really awkward and messy. Additionally, if the user has scrolled anywhere on the page and opens the `sidenav`, it forcefully kicks the page back up to the top.

I can resolve this by placing the nav next to the content - within the `container`, but then the `sidenav` opens up within the fixed-width area and looks even more awkward.

Is there any way to achieve a middle-ground here?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort. 
      For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by ciel** [comment]
You're just closing it without so much as looking at it?
