### ISSUE TITLE
Issue when using uglify on 1.1.0-rc*

### ISSUE THREAD

**Issue by corentin-gautier** [angular/material#8114]
I've been having issues when building my app ( which uses uglify as part of the build process )

- autocomplete doesn't work anymore ( the field doesn't appear at all )
- there are several other js errors in the console

Turning uglify off fixes the issue temporarily

**Comment by clshortfuse** [comment]
Try using ng-annotate before uglifying your code.

**Comment by ThomasBurleson** [comment]
Not a core ngMaterial issue. Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by corentin-gautier** [comment]
@ThomasBurleson actually it is since everything work fine with 1.0.x (meaning it's a bug introduced with the 1.1.0 version). I don't think I'm the only one using uglify on my project so if everyone's build breaks in 1.1.0 you will have some issues ^^

**Comment by nobalmohan** [comment]
@corentin-gautier updating my gulp-uglify to 1.5.3 solved this issue.
