### ISSUE TITLE
mdSelect: floating label renders on top of watermark when selection is cleared programmatically

### ISSUE THREAD

**Issue by nfriend** [angular/material#8115]
When an `<md-select>` is cleared programmatically (setting the `ng-model` to `undefined` in the controller), the floating label is rendered on top of the watermark:

![untitled](https://cloud.githubusercontent.com/assets/1638631/14645862/f03d4d84-061c-11e6-8f1b-c219ce2137fc.png)

See this fiddle for a demonstration of the issue and steps to reproduce:

https://jsfiddle.net/NathanFriend/t8gz1sk6/

Angular material version: 1.0.5
Angular version: 1.4.9
Browser: Chrome Version 49.0.2623.112 m (64-bit)
OS: Windows 8.1

**Comment by crisbeto** [comment]
My guess is that the `md-select` isn't calling `setHasValue` on the `mdInputContainer` controller when it gets cleared.

**Comment by machaven** [comment]
Seems to be fixed on master, see:

https://jsfiddle.net/b0fxxk9o/

**Comment by machaven** [comment]
The similar issue that I had is now also resolved in master. Ty!
