### ISSUE TITLE
md-disable-backdrop seems to be ignored

### ISSUE THREAD

**Issue by ciel** [angular/material#8119]
I'm attempting to have a slide out `<sidenav>` and despite giving it the attribute `md-disable-backdrop` it... still generates a backdrop.

````
    <div class="body-content container md-padding" layout="row">
        <div layout="row" class="container">
            <md-sidenav class="md-sidenav-left md-whiteframe-4dp fill-height"
                        style="padding-top: 60px;"
                        md-disable-backdrop
                        md-component-id="left"
                        layout-fill>
                <!-- menu content -->
            </md-sidenav>
            <md-content>
                <md-button class="md-fab md-primary md-fab-top-right" aria-label="Add"">
                <md-icon md-font-set="material-icons">add</md-icon>
                </md-button>
                <!-- content -->
            </md-content>
        </div>
    </div>
````

Is there something extra in the controller I must do to get this functionality to work as I expect it to? or does it only apply to sidenav that are pinned open, and don't close?

**Comment by Emeegeemee** [comment]
I dropped your code into a [codepen](http://codepen.io/anon/pen/wGXrPY) and removed some of the styles that appeared to be custom. From the demo it doesn't seem to be adding a backdrop like it is suppose to. Feel free to update the demo and add the new link if you get it to break.

**Comment by ThomasBurleson** [comment]
Closing until a valid CodePen is presented that demonstrates a ngMaterial issue.

**Comment by vmille** [comment]
Hi !
After some tries, 1.1.0.rc5 is involved. this work with rc4 and previous.
I only test locally as rc5 doesn't seem available on CDN.

**Comment by bondarewicz** [comment]
Just experienced same issue.
Replication steps:
1. navigate to codepen from [this demo](https://material.angularjs.org/1.0.9/demo/sidenav) 
2. replace 
`<md-sidenav class="md-sidenav-right md-whiteframe-z2" md-component-id="right">` 
with 
`<md-sidenav class="md-sidenav-right md-whiteframe-z2" md-component-id="right" md-disable-backdrop>`

codepen linked assets are:
https://cdn.gitcdn.link/cdn/angular/bower-material/v1.0.9/angular-material.css
https://cdn.gitcdn.link/cdn/angular/bower-material/v1.0.9/angular-material.js

When `md-disable-backdrop` was introduced? Should it work with 1.0.9 ?

**Comment by skortchmark9** [comment]
I am having the same issue. I think it is a packaging problem. I'm installing angular-material with npm, and the flag exists in `angular-material/modules/js/sidenav/sidenav.js` but not in `angular-material/angular-material.js` Seems to be fixed in 1.1.1

**Comment by maxrandolph** [comment]
Still having this issue in . Using directly from the angular.io documentation example:
` "@angular/material": "^2.0.0-beta.8",`
```
<md-sidenav-container class="example-sidenav-fab-container md-elevation-z4 myNavbar">
  <h1>header</h1>
  <md-sidenav md-disable-backdrop="true" #sidenav mode="over" opened="false">
    <button md-mini-fab class="example-fab" (click)="sidenav.toggle()">
       <md-icon>chevron_left</md-icon> 
    </button>
    <md-card-content>

      <form class="example-form" name="taskForm">
        <div>
          <div fxFlex class="container">
            <div fxLayout="row">
              <md-input-container fxFlex="50%">
                <input type="text" mdInput placeholder="Name">
              </md-input-container>
              <md-input-container fxFlex="50%">
                <input type="email" mdInput placeholder="Email">
              </md-input-container>
            </div>
            <md-input-container id="commentsarea" fxFlex="100%">
              <textarea type="text" mdInput placeholder="Message"></textarea>
            </md-input-container>
          </div>
        </div>
      </form>
    </md-card-content>
  </md-sidenav>
  <div class="example-scrolling-content">
foo bar
  </div>
</md-sidenav-container>
  <button md-mini-fab class="example-fab" (click)="sidenav.toggle()">
     <md-icon>chevron_right</md-icon> 
</button>

```

**Comment by RaviSankarRao** [comment]
facing the same issue. The documentation seems less detailed.
