### ISSUE TITLE
md-datepicker model

### ISSUE THREAD

**Issue by scriptsure** [angular/material#8124]
i am getting  the following when i bind a date in a JSON object returned from a sequelize query to the md-datepicker...

Error captured from the UI msg=The ng-model for md-datepicker must be a Date instance

I understand the issue but shouldnt material handle this?

**Comment by stunaz** [comment]
There is a big chance that you dont have a date object buy a string

**Comment by ThomasBurleson** [comment]
Closing as invalid issue submission.

---
Required
---

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: 

**Angular Versions**: *
-  Angular Version: 
-  Angular Material Version: 

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:
