### ISSUE TITLE
md-tabs close function

### ISSUE THREAD

**Issue by aldesabido** [angular/material#8125]
Is it possible to put the close button inside the tab button? like a small (X) in upper right of the tab. I did search but can't find anything yet. Thanks!

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by aldesabido** [comment]
Okay, Thanks!

**Comment by Berg-it** [comment]
In order to add close button inside tab button you can write the bellow code:

        <md-tab-label>
          <section layout="row">
            Contrat N°2589 - SAR Michelin &nbsp;&nbsp;
            <i class="material-icons">highlight_off</i>
          </section>
        </md-tab-label>
