### ISSUE TITLE
onOpen, onClose options for sidenav

### ISSUE THREAD

**Issue by onelson** [angular/material#813]
In my specific case, I'd love to be able to run some code when a particular sidenav is closed. Dialog has onShow and onHide which mark the same sort of points on the lifecycle, however onOpen/onClose may be more fitting since that would match the underlying method calls.

**Comment by justindujardin** [comment]
What about the case of using a hideDelay value?  How do I obtain the close/hide promise for that?

**Comment by onexdata** [comment]
This seems to have slipped through the cracks... 

When the user clicks or taps outside of the sidenav, it closes the sidenav without telling your app; you can poll isOpen(), but what is the proper way to $watch for this?  Is there an onClose event yet as this issue describes?
