### ISSUE TITLE
Md-menu headers

### ISSUE THREAD

**Issue by gpopovic** [angular/material#8130]
Is it possible to have headers on md-menu just like on md-select?

http://codepen.io/anon/pen/ONEQmE

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by arikkfir** [comment]
So was this addressed in Material 2?
