### ISSUE TITLE
$mdToast in 1.0.7 doesn't wrap content correctly

### ISSUE THREAD

**Issue by mgol** [angular/material#8131]
See the jsbin (plunker is currently broken): http://jsbin.com/mugelu/edit?html,js,output

Here's the relevant code:
```js
$mdToast.show({
    template: '<md-toast class="md-toast">My message</md-toast>',
    position: 'top',
    hideDelay: '10000',
});
```

In Angular Material 1.0.6, the toast that appears has the following representation:
```html
<md-toast class="md-toast ng-scope md-bottom">
    <div class="md-toast-content">My message</div></md-toast>
```
In 1.0.7 it looks like that:
```html
<md-toast class="md-toast md-bottom">
    My message
    <div class="md-toast-content"></div>
</md-toast>
```

Note the empty `md-toast-content` div appended to the end, the message stays out of it.

**Comment by ThomasBurleson** [comment]
@mgol - Obviously we need to improve our tests with Toast.
