### ISSUE TITLE
Tooltip remains in view after clicking a button

### ISSUE THREAD

**Issue by camden-kid** [angular/material#8136]
The following procedure demonstrates the problem:

 * Click a button with tooltip
 * Move the cursor away from the button
 * Move the cursor over the button
 * Move the cursor away from the button

Try it here https://material.angularjs.org/latest/demo/tooltip

This problem appears in the following browsers and versions:

 * Chrome - 50.0.2661.86

This problem does not appear in the following browsers and versions:

 * Firefox - 45.0.2
 * Safari - 9.0.1

**Comment by peio72** [comment]
+1

**Comment by clshortfuse** [comment]
I can't reproduce this on Chrome v50. Perhaps your browser is keeping the button in focus after you click it?

**Comment by peio72** [comment]
I have same problem on firefox. Tooltips remains after mouse out. On some screens i can have 3 ones permanently displayed. Thanx for help.
