### ISSUE TITLE
How to make FAB Toolbar always open?

### ISSUE THREAD

**Issue by kvitozev** [angular/material#8138]
By default, when you click trigger button once, the toolbar is displayed. And then, when second click is fired off, the toolbar gets closed. Is there any way to make toolbar stay always opened while another (close) button is clicked?

I didn't find any solution for this issue. Thanks.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
