### ISSUE TITLE
Sidenav control disappears when re-sizing up?

### ISSUE THREAD

**Issue by HaakonH** [angular/material#8139]
I am using the sidenav control in my spa and we are noticing when you expand your browser on a larger monitor the buttons in the nav disappear but the menu is still visible. You can look at my plnkr here to see what is 
![sidenav](https://cloud.githubusercontent.com/assets/18037802/14684972/42c29742-06e7-11e6-907b-bf306782c8b0.jpg)
going on. [Sidenav on plnkr](http://embed.plnkr.co/FXOb31AnlOb2fb1pWyHg/)

We aren't doing any size checking in our code, just using the default styles that come with material.

**Comment by stunaz** [comment]
on your `md-button` you have `hide-gt-md`

**Comment by DevVersion** [comment]
@stunaz Thanks for the good catch!
