### ISSUE TITLE
v1.1.0-rc4 md-select-value style issue

### ISSUE THREAD

**Issue by jaxoncreed** [angular/material#8140]
Usually the value provided to the highlighted element is "md-select-value." In rc4, this has been changed to "_md-select-value." Was this supposed to happen?

![image](https://cloud.githubusercontent.com/assets/5464743/14686747/3241e99c-0708-11e6-9190-962a59722040.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
