### ISSUE TITLE
md-autocomplete supporting type="number" or type="tel" fields

### ISSUE THREAD

**Issue by jpike88** [angular/material#8146]
md-autocomplete is used on many mobile devices, and there are instances where a numeric keyboard is appropriate for the autocomplete field. Whether it just be an extra option added to md-autocomplete or whatever that'd be great

**Comment by ThomasBurleson** [comment]
will not fix.

**Comment by jpike88** [comment]
Time for a fork I guess

**Comment by ThomasBurleson** [comment]
@jpike88 - or submit a concise PR and we will merge it in!  PRs are welcomed.

**Comment by hashina** [comment]
Hi guys, did you find any solutions for this? thanks.
