### ISSUE TITLE
md-datepicker border-bottom not the same as md-input border-bottom

### ISSUE THREAD

**Issue by Schlesiger** [angular/material#8148]
md-input border-bottom seems to use RGB(#, #, #, 0.12) on unactivated inputs while md-datepicker's div used a different hue color RBG(#, #, #) with no opacity adjustment. If you inspect the demo here you can see the difference: https://material.angularjs.org/1.0.7/demo/input

This is causing problems for forms and different colors. The borders don't match. md-datepicker should use the same hue and opacity as md-input.

**Comment by ThomasBurleson** [comment]
Related to #7772

**Comment by BevanR** [comment]
Does this screenshot from https://material.angularjs.org/HEAD/demo/input capture the issue?
![screen shot 2016-05-11 at 12 27 16 pm](https://cloud.githubusercontent.com/assets/325176/15166553/1d1c93ba-1774-11e6-9a48-c1c8cef75246.png)

**Comment by DevVersion** [comment]
@BevanR PR, which fixes that issue is already pending. But thanks for the screenshot though.

**Comment by BevanR** [comment]
No problem @DevVersion!  😄  I wanted to check I understood the bug properly before reviewing the PR.
