### ISSUE TITLE
Autofocus on autocomplete

### ISSUE THREAD

**Issue by allocenx** [angular/material#8151]
So i have an autocomplete inside a md chips and i want that whenever i load the page the autocomplete to be autofocused automatic. I tried applied md-autofocus="true" on autocomplet and it didn't worked.

To be more specific, i uploaded an image:

![4adgasf](https://cloud.githubusercontent.com/assets/210413/14706702/f2fd8bb4-0785-11e6-8933-e20312a167d2.png)

I want that autocomplete (Search for contact) to be autofocused when i enter on page so that even if i enter on that page from mobile, being autofocused the keyboard appearing automatic.

* Angular JS Version: 1.4.9
* Angular Material: 1.0.3
* Browser: Chrome
* Browser Version: 48.0.2564.116
* OS: Linux Mint

Any ideea why this doesnt work? Or a workaround for this to work?

**Comment by ThomasBurleson** [comment]
* Please alway test with latest from master before submitting an issue; as a fix may already be in `master`.
* Please provide a CodePen demo.

**Comment by allocenx** [comment]
What you need? JS or HTML?

**Comment by allocenx** [comment]
Thats the html http://pastebin.com/avfhtmEg
