### ISSUE TITLE
theme: custom themes not working properly & API documentation missing

### ISSUE THREAD

**Issue by allocenx** [angular/material#8152]
So i am building an angular web application but i encountered few problems when i got to the theming part. The point is, that even if read hundreds of times the theming documentation, my global custom theme won't apply. 

So if i configure another palette of colors for default theme it does apply global which is exactly the thing i want except i do not want the name md-default-theme in my app, more like md-hekate-theme. 

So i modified the js for my custom theme and the css was generated in `<style>` but the theme didnt applied globally except if i put manually the class md-hekate-theme on body or html.

*  Angular JS: 1.5.3
*  Angular Material: 1.1.0
* Browser: Chrome
* Browser Version: 48.0.2564.116
* OS: Linux Mint
*  **[Demo](http://pastebin.com/z72pMYfg)**

**Comment by ThomasBurleson** [comment]
* Did you `setAsDefault('md-hekate-theme')` ?
* Or did you specify that your application components want to use that theme.
```html
<md-content md-theme="md-hekate-theme" layout-gt-sm="row" layout-padding>
    <div>
      <md-input-container>
        <label>Title</label>
        <input ng-model="user.title">
      </md-input-container>
      <md-input-container>
        <label>Email</label>
        <input ng-model="user.email" type="email">
      </md-input-container>
    </div>
  </md-content>
```

**Comment by ThomasBurleson** [comment]
It appears that the Theme provider documentation is not public in our docs; this will be fixed.

**Comment by allocenx** [comment]
There is no function called setDefaultTheme, you may want to say setDefaultTheme i guess. And to answer your questions, none of them works... . And yes, i need this theming thing work urgent because i am in a hurry with a project.

**Comment by stunaz** [comment]
It is working! (I agree the docs need to be updated), Here is how I configured it

```javascript
		var accentColor = $mdThemingProvider.extendPalette('red', {
			'500': 'EF5350'
		});
		$mdThemingProvider.definePalette('accentColor', accentColor);

		var primaryColor = $mdThemingProvider.extendPalette('blue', {
			'500': '1976D2'
		});
		$mdThemingProvider.definePalette('primaryColor', primaryColor);

		$mdThemingProvider.theme('myTheme')
			.primaryPalette('primaryColor')
			.accentPalette('accentColor')
			.warnPalette('orange');
		$mdThemingProvider.setDefaultTheme('myTheme');
```

**Comment by allocenx** [comment]
It does not work for me. Please provide and html. I need this theme applied globally.

**Comment by allocenx** [comment]
It seems that is generated my custom theme in style tag and also the default one but still it takes the default one applied globally.

**Comment by epelc** [comment]
@allocenx As a workaround you can rename your theme to `default`. example: `$mdThemingProvider.theme('default')...`

The [docs](https://material.angularjs.org/latest/Theming/03_configuring_a_theme) also have a longer example and explaination that the `default` theme is used by default.

I've also opened #8193, to create a docs page for `$mdThemingProvider`.

**Comment by EladBezalel** [comment]
@allocenx can you please provide a codepen with your issue?
