### ISSUE TITLE
Component/Directive lifecycle hooks are not supported 

### ISSUE THREAD

**Issue by gkalpak** [angular/material#8153]
Angular 1.5 has introduced some new lifecycle hooks that can be utilized on component/directive controllers. People are expecting to use them with `ngMaterial` components (such as dialogs, toasts etc), but the material compiler doesn't support them (yet?).

Ideally the `ngMaterial` compiler should support the lifecycle hooks.
If that it not possible (without essentially duplicating the core compiler), a note should be added to the docs, so users know what to expect.

(Related: angular/angular.js#14469)

**Comment by ThomasBurleson** [comment]
@gkalpak - awesome. Thx.

**Comment by rriemann** [comment]
Can this be closed?

**Comment by garretwilson** [comment]
I'm using Angular 1.6.4, and `$onInit()` is still not called for an mdDialog controller. Am I doing something wrong? `$onInit()` works fine for my other component controllers.

**Comment by Splaktar** [comment]
I think that this can be closed now. I believe that all components support the lifecycle hooks other than dialog atm. For dialog, that is being tracked in https://github.com/angular/material/issues/10567.

**Comment by garretwilson** [comment]
Regarding my comment above, `$onInit()` seems to be working after updating to AngularJS Material 1.1.8.
