### ISSUE TITLE
icon: font ligature not properly working on android 4.4

### ISSUE THREAD

**Issue by sjaase** [angular/material#8154]
If using font ligature:

```html
<i class="material-icons">arrow_back</i> or
<md-icon>arrow_back</md-icon>
```
it wont get rendered on android 4.4. This applies only for ligatures where underscore is used. E.g. arrow_back, more_horiz. Ligatures with names like menu, cancel etc. works just fine.

Used:
* Android Emulator - Android 4,4 (API Level 19)
* Angular Material version 1.1.0-rc4

**Comment by DevVersion** [comment]
Cannot reproduce on Samsung Galaxy Note 4 with Android 4.4

![image](https://cloud.githubusercontent.com/assets/4987015/14709024/bf4c1efe-07ce-11e6-9a5c-904204fcd102.png)

**Comment by ThomasBurleson** [comment]
This issue appears not to be an issue with ngMaterial

**Comment by sjaase** [comment]
Tested this on Visual Studio Emulator for Android, using the integrated browser.
