### ISSUE TITLE
Window resize doesn't resize backdrop when document body is position fixed.

### ISSUE THREAD

**Issue by gzerilli** [angular/material#8155]
When the window is a smaller size and I bring up a dialog (with a backdrop), when we maximize the window the backdrop is cut to the viewport size.

![capture](https://cloud.githubusercontent.com/assets/7971655/14711092/f6c649f8-07cf-11e6-9bf3-bc3da4852f3a.PNG)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen demo.

---

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).

**Comment by gzerilli** [comment]
https://jsfiddle.net/t67L06fy/6/

**Comment by mikila85** [comment]
great find and fix. when should it be added to the release.

**Comment by crisbeto** [comment]
I'm not sure really, depends on when the PR gets merged. It's tagged as 1.1.1.

**Comment by mikila85** [comment]
oh now i see, Thanks!
learned something new :)
