### ISSUE TITLE
md-fab-trigger(md-fab-speed-dial) not triggering md-fab-actions for first time

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#8157]
When i am clicking on first time on fab, it's not working. After second click, it is woking fine. And i want that it md-actions must be hidden for first time but these are showing by default while md-open="false".
Please help me. It may look like that it is copy of others but i didn't find any correct answer so please don't close it. 

<img width="112" alt="screen shot 2016-04-21 at 7 15 57 pm" src="https://cloud.githubusercontent.com/assets/6860473/14711433/efb47744-07f6-11e6-9398-022248b5ca0b.png">
<img width="1074" alt="screen shot 2016-04-21 at 7 18 04 pm" src="https://cloud.githubusercontent.com/assets/6860473/14711435/f0132c12-07f6-11e6-9940-db984247b6fd.png">
<img width="242" alt="screen shot 2016-04-21 at 7 22 04 pm" src="https://cloud.githubusercontent.com/assets/6860473/14711434/f011626a-07f6-11e6-9711-24f9d3a47682.png">

**Comment by jainshravan123** [comment]
I have only this much content.

**Comment by ThomasBurleson** [comment]
@topherfangio - any thoughts.

**Comment by topherfangio** [comment]
@jainshravan123 Have you tried adding the `ng-cloak` attribute to a parent/wrapping div as outlined in the [Troubleshooting section of the docs](https://material.angularjs.org/latest/api/directive/mdFabSpeedDial)?

We have plans to remove this restriction, however, this can help a lot with the issues you are seeing.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
