### ISSUE TITLE
Tutorial for Chat App using node JS

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#8158]
Is there any tutorial for implementation of node js based chat application. I have already read a tutorial from socket.io but that is only just basic. I want to implement a fully configured chat app which can check whether a user is online or not. A user can chat to another user only if both are online at the same time. Some features i want to implement. So please suggest me couple of tutorials for this kind of work.

**Comment by DevVersion** [comment]
Please ask in the ngMaterial Google Group. 

- https://groups.google.com/forum/#!forum/ngmaterial

On GitHub we're not solving user-specific question. Support is available on the Google Group.
