### ISSUE TITLE
Autocomplete list positioning incorrect

### ISSUE THREAD

**Issue by anderslyman** [angular/material#8167]
The autocomplete's list is being positioned above the input when there is plenty of room for it below.
Refer: [codepen](http://codepen.io/anderslyman/pen/mPjrMe?editors=1011)

Simply expand/shrink the viewport to see the issue.
Above (plenty of space below):
![image](https://cloud.githubusercontent.com/assets/1380857/14727822/068dddc6-07ec-11e6-872a-ccb94f23b1d5.png)

Below (expanded the viewport slightly):
![image](https://cloud.githubusercontent.com/assets/1380857/14727827/14d25b3c-07ec-11e6-93ee-0da861427637.png)

**Comment by iamisti** [comment]
+1, have the same issue. Is there anyone who could solve it even with a workaround?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by iamisti** [comment]
So not even a workaround suggested?

**Comment by areeb5** [comment]
is there any workaround ? im having the same issue :(
i apply solution of body { height:auto; min-height: 100%; } this solution make the content area of md-autocomplete render below the control but it causing me issues in scrolling, this solution is not effective. 
kindly help regarding this issue
