### ISSUE TITLE
md-toast: incorrect placement if page scrolled

### ISSUE THREAD

**Issue by stunaz** [angular/material#8168]
Hello,
The `toast` placement don't change when the page is scrolled.

Expected behaviour:  the toast should be displayed at the bottom of the page. If I scroll down the page, then any toast which appears should be display at the **new calculated** bottom of the page.

codepen [http://codepen.io/stunaz/pen/dMjOzN](http://codepen.io/stunaz/pen/dMjOzN)

angular : 1.5.3
angular-material: 1.1.0-rc4

Same behaviour were fixed for the dialog in #4115

**Comment by ThomasBurleson** [comment]
Similar to #1106

**Comment by DevVersion** [comment]
@ThomasBurleson I think this can be fixed with the same approach of #8184

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
