### ISSUE TITLE
md-slider with ng-change displays the wrong tooltip

### ISSUE THREAD

**Issue by PaulMougel** [angular/material#817]
When the function called by `ng-change` in an `md-slider` modifies the model's value, the tooltip displays the old value (the one that was selected by the user), and not the one that was set by the function.

``` html
<md-slider flex md-discrete min="0" max="10" ng-model="value" ng-change="stayAt5()" aria-label="Slider"></md-slider>
```

``` javascript
$scope.stayAt5 = function () {
  $scope.value = 5;
}
```

See [this Plunker](http://plnkr.co/edit/oJy0pvEk60v7M0AwC3ke?p=preview).
![untitled](https://cloud.githubusercontent.com/assets/1788596/5261519/e005eeba-7a1a-11e4-801f-43093d3d9b46.gif)

_Edit:_ I have a fix, I'll send the PR as soon as possible.

**Comment by jonasantonelli** [comment]
I just changed the visual value
```sass
.md-sign
{
        &:before
        {
            content:'s';
            color:#fff;
            font-size: 12px;
            font-weight: bold;
            order:2;
        }
}
```
