### ISSUE TITLE
md-slider Nullpointer in parseInt(computedStyle['min-width'])

### ISSUE THREAD

**Issue by IsNull** [angular/material#8174]
Angular Material: 1.1.0-rc4 
Browser: Safari, Firefox (probably not a Browser specific issue anyway)

### How to reproduce

1. Open Codepen: http://codepen.io/_IsNull/pen/GZBBvw
2. Open Browser Developer Console
3. Drag the slider around and observe a lot of errors

### Details
>Error: null is not an object (evaluating 'computedStyle')

```javascript
ctrl.fitInputWidthToTextLength = function (length) {
          var input = element.find('md-input-container');
          var computedStyle = getComputedStyle(input[0]);
          var minWidth = parseInt(computedStyle['min-width']);
          var padding = parseInt(computedStyle['padding']) * 2;
          initialMaxWidth = initialMaxWidth || parseInt(computedStyle['max-width']);

          var newMaxWidth = Math.max(initialMaxWidth, minWidth + padding + (minWidth / 2 * length));

          input.css('max-width', newMaxWidth + 'px');
        };
```

So if  computedStyle() can possibly return null, maybe add a check there.

**Edit**:
I am still trying to make it easily reproducible. It is happening in a (right) side nav, maybe dynamic layout calculations interfere with the md-slider layout logic.

**Edit2**:
Similar Error in Firefox:

>Error: Argument 1 of Window.getComputedStyle is not an object.
postLink/ctrl.fitInputWidthToTextLength@
stepValidator/<@
timeout/timeoutId<@
completeOutstandingRequest@
Browser/self.defer/timeoutId<@

**Comment by ThomasBurleson** [comment]
Please provide [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).

**Comment by IsNull** [comment]
@ThomasBurleson I added a CodePen

After a lot of try & error, I found out that it does not matter where the md-slider is. Just add an md-slider and observe the error in console when dragged around.
