### ISSUE TITLE
md-colors: not accepting color differentiating names (hue-1, etc)

### ISSUE THREAD

**Issue by evankoffler** [angular/material#8175]
md-colors has the flexibility to specify the shade color directly which is nice for ultimate control.

However, it does not allow the use of the hue-1, hue-2, hue-3 in any form (hue1 or hue-1) to specify the shade to use. This means that it is difficult to style non-md elements via md-colors since one has to specify the shade value and realize the relationship between the name and its underlying actual value such as for primary hue-1 is 300. Plus if the hue was changed via the $mdThemingProvider, then it would not reflect this.

Example at: http://codepen.io/anon/pen/VaBMNM

**Comment by ThomasBurleson** [comment]
@EladBezalel - your thoughts? If not valid, please close.
