### ISSUE TITLE
Unexpected Behavior on <md-datepicker> With YYYY-MM-DD Format

### ISSUE THREAD

**Issue by abouillon** [angular/material#8176]
While working with the datepicker component to see which formats are accepted as valid date formats I found this behavior. When using the text input to enter a date in yyyy-mm-dd format it will roll the date back 1 day. So if you type 2016-04-05 into the input this will result in 4/4/2016 being displayed.

https://plnkr.co/edit/Vb43PW

**Comment by crisbeto** [comment]
I couldn't reproduce it. It showed up as 4/5/16 for me.

**Comment by abouillon** [comment]
This is a pickle then because I am at a loss as to what is different on my end that could be causing this because this also happens on the demo.

http://i.imgur.com/2J97hT5.gifv

**Comment by crisbeto** [comment]
The date from the view gets passed through the `parseDate` method on the `$mdDateLocaleProvider` before it gets assigned to the modal. You can override this method if you want more control over what gets inserted.

**Comment by slimovic** [comment]
This happens when your timezone is under GMT and YYYY-MM-DD is the [ ISO 8601](http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15). So the browser will interpret it as the date you entered(Month Day Year 00:00:00) minus the difference of hours.
I still believe its an issue in datepicker.
