### ISSUE TITLE
sniffer: vendorProperty needs to be checked

### ISSUE THREAD

**Issue by DevVersion** [angular/material#8186]
`$mdConstant` uses a function, which prefixes the given property with the correct prefix for several browsers.

| Browser | Supported Properties |
| ----------- | ----------------------------- |
| Chrome | `transform | webkitTransform`  |
| Firefox | `transform | MozTransform`  |
| IE11| `transform | msTransform`  |

Also some Android Browsers are requiring a prefix, `Webkit` or `webkit`.

**Comment by ThomasBurleson** [comment]
| Browser | Supported Properties |
| ----------- | ----------------------------- |
| Chrome | `transform | -webkit-transform`  |
| Firefox | `transform | -moz-transform`  |
| IE11| `transform | -ms-transform`  |

**Comment by DevVersion** [comment]
Yea, those properties are for the CSS - in my description are the properties for the Javascript properties.
