### ISSUE TITLE
Sidenav not fixed 

### ISSUE THREAD

**Issue by saurabhnsonar** [angular/material#8189]
Hi all,

I am implementing the angular material design for my project and found that the position for sidenav is not fixed. If the page size is big and once sidenav is opened on scroll it moves up and not fixed to the position. Even the opacity overlay is not fixed. You can check the below codepen open the sidenav and try scrolling downward. You can get the issue.
http://codepen.io/saurabhnsonar/pen/rerZzv/

**Comment by ThomasBurleson** [comment]
You can see how Sidenav is used in the [Material-Start](https://github.com/angular/material-start/blob/master/app/index.html#L37-L56) samples. You may also wish to post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by saurabhnsonar** [comment]
Hi, but the angular material demo for sidenav is also having that issue. Why is that? Even I facing same issue within my app.
