### ISSUE TITLE
$mdThemingProvider: Add a docs page listing the entire api

### ISSUE THREAD

**Issue by epelc** [angular/material#8193]
Right now `$mdThemingProvider` is lacking a page under `Services`, that lists it's entire api. To view all methods you have to jump between several pages that are mixed with demos.

![image](https://cloud.githubusercontent.com/assets/5204642/14769715/16df8b50-0a2d-11e6-83d1-cf93fe83ed79.png)

**Comment by EladBezalel** [comment]
closed via #8528
