### ISSUE TITLE
md-menu doesn't align with md-button when using md-icon-button

### ISSUE THREAD

**Issue by blbigelow** [angular/material#8196]
I am trying to have three buttons in a row, but one of the buttons needs to be an md-menu button. I can't seem to get them to align when they are just "icon buttons".

Here's an example of the problem:

http://codepen.io/anon/pen/qZMBqj?editors=1010

**Comment by clshortfuse** [comment]
Culprit: https://github.com/angular/material/blob/0b89a877ad31d0f7d425272f29d8c02600a12a88/src/components/menu/menu.scss#L116

@blbigelow Add this to your css to fix it temporarily

    .md-menu {
      padding: initial;
    }

Not sure why it needs vertical padding. I can't find anything in the spec that says it should be padded like this. If the idea is to ensure a minimum size for touch interaction with smaller icons, then maybe min-height should be used instead.
