### ISSUE TITLE
Disable mouse wheel scroll on tab labels

### ISSUE THREAD

**Issue by S8nsick66** [angular/material#8197]
Hello!

With using a desktop browser and scrollable tab labels, the labels scroll with the mouse wheel.
This is annoying when scrolling down a page with some set of tabs and always getting stuck in a tab label scroll.

So is there a way to disable the mouse wheel scroll on tab labels? Scrolling by arrow click and swiping is fine.

Thanks,
Dennis

**Comment by ThomasBurleson** [comment]
Will not fix.
