### ISSUE TITLE
md tooltip, memory leak

### ISSUE THREAD

**Issue by djfd** [angular/material#8198]
Hi,

there is a demo: http://codepen.io/djFD/full/LNJEaw/

how to reproduce.
by default all initial settings of the demo are ready for test (clean leftovers: ON, tooltips-kind: MD, add md-visible attribute: ON, global_visibility: ON)

Strarting from this initial state just press the 'Create fresh buttons' a few times. When the button is clicked: 1) md-buttons get removed using ```element.remove()```; 2) their lost tooltips (see #8033) are being removed too (thus we need global visibility to be able find then and remove); 3) new buttons get created and inserted into document

So after any click we expect to have exactly two buttons and two tooltips. Now toggle global visibility flag OFF, then ON. How many tooltips do you see? Every button click adds 2 tooltips, so we get 2 x N leaked tooltips, not just lost but exactly leaked, as we removed them entirely from DOM using ```.remove()``` op and nobody else now is keeping the references to them except browser's JS engine

Thanks

**Comment by crisbeto** [comment]
@djfd thank you for the great fiddle, I believe I found what's causing this. I just want to confirm: the way I'm testing this is by clicking the "Create fresh buttons" a bunch of times and then toggling the visibility. At the moment, a bunch of old tooltips that are still in the DOM, but we're supposed to have a maximum of 2, right?

**Comment by djfd** [comment]
@crisbeto 
yeah, correct

yet another possible improvement - to use the only window/document events handler. please take a moment to look into related wl-tooltip source, it gives considerably lesser cpu load.

and if possible, you need to use the single entry point for visibility changing, hideTooltip()/showTooltip() need to be a private members of setVisibility()

**Comment by crisbeto** [comment]
@djfd I've managed to fix the following cases:

1. Stuff not being cleaned out when the element is removed, but the scope `$destroy` didn't fire for some reason.
2. Stuff not being cleaned out when the parent is removed. This one usually happens when you add tooltips while the visibility is false.

Are you aware of any other cases I should be looking into? 

Also I didn't manage to work out what is causing the tooltips to stay in the top left on load. I'm not sure whether this is an issue with the test case itself, or the Material component.

**Comment by djfd** [comment]
@crisbeto 
Hi,
1) it is expected (in its current implementation) that there will not be '$destroy' signal on element itself removal, need to have ```element.on('$destroy', function() { scope.$destroy() })``` for that. Regarding parent removal - it no necessarily does have own dedicated scope. Right destroy sequence looks as
```
        // configuring watchers
        parent.on('$destroy', function() { element.remove(); });
        element.on('$destroy', function() { scope.$destroy(); });
 
        scope.$on('$destroy', function() {
            element.remove();
            ...
        });
```

2) well, we cannot force the user to remove elements having tooltip visibility set to true. How do you fix that?

I do not think this is issue of test case, possible parents geometry/visibility is not defined at that time. Look at the same case when wl-tooltip is default: http://codepen.io/djFD/full/WwaQGL/

So need to provide a means for signaling of parent's visibility changes.

What else. Please check that all handlers are detached, eg. this one will live forever
https://github.com/angular/material/blob/master/src/components/tooltip/tooltip.js#L206,
this one is conditional, will not detached in some cases: https://github.com/angular/material/blob/master/src/components/tooltip/tooltip.js#L198 etc etc

**Comment by crisbeto** [comment]
1. Yeah that's pretty much what I did, although it's easy to fall into an infinite loop there.
2. Good catch on the `leaveHandler`, I had only accounted for the `enterHandler` at https://github.com/angular/material/blob/master/src/components/tooltip/tooltip.js#L207.

**Comment by djfd** [comment]
Infinite loop? how? why? scope $destroy is smart enough to do not do the same twice

I know, it is not easy to read the others code, but did you look at wl-tooltip source? I believe you need to implement single window's resize/blur and document/scroll handler. What does happen now. every tooltip visible or not handles all these events. for large scale app having hundreds tooltips it gives good cpu load. look at how this is done in wl-tooltip. typically the only (or no one at all) tooltip will handle it, thus decreasing cpu load literally by orders

**Comment by crisbeto** [comment]
The infinite loop is not because of the `$destroy` on the scope, but the `$destroy` on the element, which can fire multiple times apparently.

As for the other changes, I agree that it could be done a bit better, but this is outside the scope of this particular issue (looking at all the leaking elements).

**Comment by djfd** [comment]
OMG, need to open new issue on high cpu load? :D

as for other the scope of this particular issue, please let me know when your changes will be applied, curious to see.

thanks

**Comment by djfd** [comment]
yeah, one more thing. I did tell, but will repeat. Sometimes scope $destroy is fired without triggering leave handler at first. I did not check why and how this happens, just noticed the fact. thus need to remove 'blur mouseleave touchend touchcancel' inside scope destroy handler
