### ISSUE TITLE
md-datepicker: Allow use of md-input-id

### ISSUE THREAD

**Issue by abouillon** [angular/material#8202]
Exactly how md-autocomplete makes use of the md-input-id directive, it would be useful to have this for md-datepicker as well.

This would allow for the component to be easily testable using Protractor to test the inputs. Currently this component is not very testable when there are multiple on a page due to the need to locate the input by css rather than an id attribute.

**Comment by ThomasBurleson** [comment]
A pull request would be welcomed.

**Comment by abouillon** [comment]
Will work on a PR for this shortly.

**Comment by ThomasBurleson** [comment]
@abouillon - in your PR, please add "Fixes #8202" and I will reopen this issue.

**Comment by abouillon** [comment]
Will do.

**Comment by LayZeeDK** [comment]
@abouillon Any progress?
