### ISSUE TITLE
Feature Request: Add text avatars

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#8204]
A nice feature would be the ability to add text avatars for someones name:

![image](https://cloud.githubusercontent.com/assets/9777763/14789741/dca6bab0-0b05-11e6-8b64-e85b49c3563a.png)

![image](https://cloud.githubusercontent.com/assets/9777763/14789814/38ea41f2-0b06-11e6-9552-292b7dc693aa.png)

Something like this angularjs plugin: https://github.com/thomasmalm/gfl-text-avatar

**Comment by DevVersion** [comment]
This seems to be a cool feature. Would like to implement it ;)

**Comment by ThomasBurleson** [comment]
Would be a nice add-on; but will not be added to core ngMaterial.
