### ISSUE TITLE
core.css causes VERY poor performance in Internet Explorer

### ISSUE THREAD

**Issue by mpiasta-ca** [angular/material#8208]
Came across severe slowness in Internet Explorer which makes it almost unusable (no issue in any other browsers). Seems to be caused by angular-material stylesheet (we are using ng-material version 1.0.7).

In our case, this is evident when using the "intl-tel-input" JQuery plugin. When you are in Internet Explorer and you try to select a different phone country code from the country list, whenever you SCROLL the country list, there is ~750ms delay before the visual update renders (this on an i7-CPU desktop).

But if you remove the "angular-material.css" stylesheet from the `<head>` section, and you test the country list again, you'll see the scrolling render issue goes away. 

Specifically, I debugged the angular-material CSS module by module, and pinpointed the issue to "/angular-material/modules/closure/core/core.css" between lines 1334 and 9169, which is a bunch of layout media queries. If you comment-out this entire section, the IE performance issues are no longer visible.

(1) Plnkr demo: https://embed.plnkr.co/UiuD324sbMTwY2in4dN7/ (open with Internet Explorer)

(2) Plnkr demo w/o angular-material.css: https://embed.plnkr.co/pDYYN3lGvYE07QLv6ryB/ (notice: no longer suffers from performance issues when angular-material.css is removed).

(3) Plnkr demo w/o intl-tel-input.css: https://embed.plnkr.co/822XkJezqvz00kAXgkzC/ (notice: still suffers from performance issue when angular-material.css is present and intl-tel-input.css was removed).

Review/edit code in Plnkr demo: https://plnkr.co/edit/UiuD324sbMTwY2in4dN7

**Comment by ThomasBurleson** [comment]
@mpiasta-ca Can you reproduce these issues with ngMaterial 1.1.0-rc4 ?

**Comment by mpiasta-ca** [comment]
@ThomasBurleson Sweet, seems to work with 1.1.0-rc4. 

https://plnkr.co/edit/C9pEV4pYxzDWJGDLTg8u

**Comment by ThomasBurleson** [comment]
@mpiasta-ca - Thanks for checking.
