### ISSUE TITLE
A vertical scroll appears when a toast is at the bottom

### ISSUE THREAD

**Issue by tiftof69** [angular/material#821]
![anim](https://cloud.githubusercontent.com/assets/4489312/5263573/f5bf85a0-7a32-11e4-9a08-804305fca40a.gif)

JSFiddle : http://jsfiddle.net/tiftof69/jpkhn6rd/

**Comment by rschmukler** [comment]
This seems to be fixed now (perhaps because of #679) - either way, [this pen](http://codepen.io/anon/pen/BypjXp) (using a more up to date version of angular-material) seems to not have the issue. Please re-open if you continue to have problems.

**Comment by michaelkrog** [comment]
Using [the pen](http://codepen.io/anon/pen/BypjXp) @rschmukler referred to I currently have that issue.

Google Chrome 40.0.2214.115

**Comment by lianyi** [comment]
+1, got the same issue

**Comment by TalPasi** [comment]
+1

**Comment by jYacot** [comment]
## +1
