### ISSUE TITLE
md-dialog-content: on resize

### ISSUE THREAD

**Issue by djfd** [angular/material#8210]
Hi,

not sure if it is right place for a possible feature requests, but could we add broadcasting (in the quote $emit is used, but I mean $broadcast, from content/dialog to children) resize event to content's children on dialog resize, like this: (http://stackoverflow.com/questions/2175992/detect-when-window-vertical-scrollbar-appears#answer-26935567)
```
If you're using AngularJS, you can use a directive to detect
 when the width changes (assuming the appearing/disappearing
 scrollbar is a vertical one):

app.directive('verticalScroll', function($rootScope){
    return {
        restrict: 'A',
        link: function (scope, element) {
            scope.$watch(
                function() {
                    return element[0].clientWidth;
                },
                function() {
                    $rootScope.$emit('resize');
                }
            );
        }
    }
});

This fires an event on the root scope which other directives or
 controllers can listen for.

The watch is fired by the angular digest loop, so this relies on Angular
 having loaded/removed the extra content which has caused your scrollbar
 to appear/disappear.
```
maybe turn it on using some attribute, otherwise inactive. There is not expected 
to be a lot of dialogs opened at same time, so it is enough cpu load friendly

Or is there a better way to do it (to detect size changes)?

thanks

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
