### ISSUE TITLE
md-color not updating properly

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#8212]
When using the following code:

    md-colors="{'color': (currentNavItem.id == item.id ? 'accent' : 'grey') }")

The property is set only once, when initially calculated, and not updated when I change the internal value (currentNavItem)

But, this works just fine.

    ng-style="{'color': (currentNavItem.id == item.id ? getThemeColor('accent') : null)}")

with this as a workaround:

    $rootScope.getThemeColor = $mdColors.getThemeColor;

I can make a codepen if needed.

Extra bug, is I can't set md-color to null, but that's not as important.

**Comment by ThomasBurleson** [comment]
CodePen please... as we can use that to co-verify any fixes/changes.

**Comment by clshortfuse** [comment]
Here's the codepen: http://codepen.io/shortfuse/pen/BKOZyO?editors=1010
