### ISSUE TITLE
mdDialog: directive does not work inside mdDialog.alert().htmlContent()

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material#8214]
Angular Material Version: v1.1.0-rc4
Overview of the Issue: Title is pretty explanatory
Please see [Plunker](https://plnkr.co/edit/SFXj4Ne3VYyMTxdD01iR?p=preview)

**Comment by ThomasBurleson** [comment]
Alert and Confirm are text-only dialogs. For htm-content, use custom dialogs.

**Comment by DmitryEfimenko** [comment]
@ThomasBurleson 
Currently in [documentation](https://material.angularjs.org/latest/api/service/$mdDialog#confirm) all these helper methods on `$mdDialog` like `.alert()`, `.confirm()`, `.prompt()` return object, which has `.htmlContent()` method available. It also works fine with regular html.
It does say, however:
> HTML is not run through Angular's compiler.

... in which case it makes it a feature request.
I understand that you guys are swamped with the amount of open issues, but this is a valid request.

**Comment by rumsey1212** [comment]
@DmitryEfimenko `.htmlContent()` worked great for me after initialising the ngSanitize module in my app

**Comment by pushkar1701** [comment]
@rumsey1212 I am trying this but this is not working. Please suggest

   `$mdDialog.show(
            $mdDialog.alert()
                    .clickOutsideToClose(true)
                    .htmlContent('<div><md-button class="md-fab" aria-label="Eat cake">Button</md-button></div>')
                    .title('Service Error')
                    .ariaLabel('Left to right demo')
                    .ok('Nice!')
                    .openFrom('.upload-btn')
                    .closeTo(angular.element(document.querySelector('.delete-btn')))
            );`

**Comment by rumsey1212** [comment]
@pushkar1701 After adding that code to my project verbatim I didn't notice any issues with it. Dialog alerted fine upon a button click.

**Comment by pushkar1701** [comment]
Well @rumsey1212 Is it possible for you to provide the fiddle for it? I am sorry but it is not working at my end
