### ISSUE TITLE
mdTabs: Add option to disable tab focus redirect

### ISSUE THREAD

**Issue by auchEnia** [angular/material#8216]
When there are tabs on the page and the selected tab changes programmatically from some other component on the page, the tabs are focused automatically. This behaviour might be desired in some case, but might disrupt the work flow in others.

**Suggestion:**
- allow for a new attribute on md-tabs (e.g. md-disable-focus-redirect)
- check before if the attribute is present before redirecting the focus ([link to code](https://github.com/angular/material/blob/release/1.1.0-rc4/src/components/tabs/js/tabsController.js#L212))

**Comment by ThomasBurleson** [comment]
Will not fix.

**Comment by auchEnia** [comment]
Can I just ask, why this feature will not be implemented? Thank you.
