### ISSUE TITLE
md-slider: when scrolling to see a slider, the dragging event is caught above the slider

### ISSUE THREAD

**Issue by dorduchovni** [angular/material#8217]
steps to reproduce:
1. go to [codepan](http://codepen.io/anon/pen/vGzeqJ?editors=0010)
2. scroll down the screen to see the sliders
3. try to drag any slider.

([reproduction gif](http://giphy.com/gifs/xT1XGQoS9BWm4tWdMI))

**Comment by ThomasBurleson** [comment]
Will not fix.

**Comment by avivr** [comment]
Hey @ThomasBurleson,

Can you please explain why this issue won't be fixed? or suggest a workaround?

We've also tried to use the new vertical mdSlider introduced in version 1.1.0-rc1,
and we see the same behaviour described in the bug.

**The vertical slider is practically unusable in pages with scrollbar.**

Tested with Chrome v50 both on Mac and Windows 10.

Thanks!
Aviv
