### ISSUE TITLE
mdToolbar's mdScrollShrink does nothing until some action

### ISSUE THREAD

**Issue by Phr33d0m** [angular/material#8221]
Hi,

Sorry about the... vague title. If you have a look at the [latest demo](https://material.angularjs.org/latest/demo/toolbar) (the Scroll Shrink example at the bottom) you can see it doesn't hide or anything ~~until you click ```View Source --> JS or CSS tab```. Once you do this action (change the tabs inside the "View Source") it magically stars working as expected.~~ (see @clshortfuse 's answer below for probably a more concise explanation)

Regards.

**Comment by clshortfuse** [comment]
+1 

I've noticed this before. It's actually not action related. You can idle and it'll eventually kick in.
