### ISSUE TITLE
Dynamically loading template into <md-item-template> element

### ISSUE THREAD

**Issue by Exertive** [angular/material#8222]
I am looking to encapsulate the AutoComplete component within another customer directive. Everything works fine if I embed AngularJS markup within <md-item-template> tags. However, I would like to make this markup more dynamic by loading it from a template and compiling. 

Initial attempts have proved unsuccessful. Before continuing too far I would like to ask whether anyone can see a flaw in this approach or give me some tips...

David

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
