### ISSUE TITLE
md-sidenav toggle right

### ISSUE THREAD

**Issue by nharikakoneru** [angular/material#8223]
When I am using md-sidenav toggle right and changed the width of the html page I am getting some delay when the close button is clicked.Please see the below link.
Also how to adjust the sidenav css so that it takes different width based on parent container width-responsive.
http://codepen.io/anon/pen/VaGxrN

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
