### ISSUE TITLE
md-toolbar background is not getting set

### ISSUE THREAD

**Issue by forethoughtde** [angular/material#8224]
md-toolbar background color(rgb(63,81,181)) is not getting set so the text  is not visible on the screen. Does anyone know here the bug?

**Comment by pythondetective** [comment]
The issues was in particular cdn https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.0.7/angular-material.css. Please check this one.

**Comment by EladBezalel** [comment]
@forethoughtde please provide a codepen with your problem

**Comment by EladBezalel** [comment]
closed due to inactivity.
