### ISSUE TITLE
responsive flex in angular material design

### ISSUE THREAD

**Issue by kalyanakannan** [angular/material#8231]
`<div layout="row"  layout-padding layout-sm="column" layout-wrap>`
  `<!-- single card -->`
  `<div flex-gt-md="25" flex-gt-lg="20"  ng-repeat="item in itemCtrl.items">`
   `<md-card>`
   ` <md-card-content>`
   `  {{item.itemtitle | limitTo: 45  }}  `        
    ` <i class="fa fa-thumbs-up"></i>`
   `  {{item.itemUpVoteCount}} Likes`
     `<i class="fa fa-thumbs-down"></i>`
    ` {{item.itemDownVoteCount}} Dislike`
    `</md-card-content>`
    `<md-card-footer>`
     `<md-card-actions layout="row" layout-align="end center">`
     ` <md-button>Commend</md-button>`
     ` <md-button>Share</md-button>`
     `</md-card-actions>`
    `</md-card-footer>`
  ` </md-card>`
  `</div><!-- single card -->`
 `</div>`
I use following code for displaying item in array. but it takes flex size as flex-gt-lg="20" for media screen size > 1280. i need div as responsive based on media query in angular material.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
