### ISSUE TITLE
BottomSheet: Add a way to set callback function on .hide() (Promise resolved)

### ISSUE THREAD

**Issue by Senthe** [angular/material#8232]
I need to manipulate my $scope when md-bottom-sheet is hidden in any way (scroll, button click, etc.) . It doesn't seem like there's any option to set a callback for when the promise is resolved, why?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
