### ISSUE TITLE
md-select with name-attribute and right icon renders md-icon-left because of hidden select

### ISSUE THREAD

**Issue by gnulp** [angular/material#8234]
<md-input-container>
        <label>Label</label>
        <md-select ng-model="size" name="Test">
          <md-option ng-repeat="size in sizes" value="{{size}}">{{size}}</md-option>
        </md-select>
        <md-icon>help</md-icon>
      </md-input-container>

'Name' is required for ng-form support. md-icon is displayed right but container also has 'md-icon-left' class because mdInputContainerDirective looks for 'md-icon ~ isel' and isel is one of 'INPUT', 'TEXTAREA', 'SELECT', 'MD-SELECT', so it detects the additional hidden select which is created because of the name-attribute.

**Comment by ThomasBurleson** [comment]
Missing demo, closing - see [Deprecation Policy](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk)

**Comment by gnulp** [comment]
Here's a Demo:
[https://embed.plnkr.co/s3NscQ4s2k1xzrT5pLfq/](url)
