### ISSUE TITLE
Missing sourceMappingURL in angular material minified files

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#8246]
Minified files should have the bottom:
//# sourceMappingURL=BLABLA.min.js.map
(also for CSS)

This makes it easier to debug issues in production because chrome supports source-mapping, so it shows the non-minified src (and you can set breakpoints there!)

See:

![image](https://cloud.githubusercontent.com/assets/1890589/14868116/f3289f70-0c99-11e6-89b8-a8fe6fbec99f.png)

**Comment by ThomasBurleson** [comment]
Not a core focus feature. Will not fix.

**Comment by yoav-zibin** [comment]
Maybe I didn't explain well the importance of this tiny feature :)
Without it, I can't de-minify the stacktraces (in bugs like https://github.com/angular/material/issues/8245), and therefore I can't contribute PR (pull requests) fixing the issues (I can't even start to figure out what's happening because I can't map the minified stacktrace to the original code).
Moreover, suppose that I can reproduce some issue in prod, and I want to set a breakpoint in chrome in material code --- look at the printscreen, the non-minified version, angular-material.js is not in the Sources tab, so I can't set a breakpoint (and nobody is going to release to prod an HTML that uses the non-minified version).
And I'm sure I'm not the only one that will need this.
This is a mandatory feature for any minified JS/CSS library --- name me one library/platform that doesn't have sourceMappingURL?
