### ISSUE TITLE
md-progress-circular rAF is not cleared on destroy

### ISSUE THREAD

**Issue by corentin-gautier** [angular/material#8253]
This is a console.log on the rAF in the startIndeterminateAnimation method (after navigating for a while in my app) ...

![image](https://cloud.githubusercontent.com/assets/4660731/14881249/6a9483f0-0d33-11e6-9e8c-f5df16a9f365.png)

**Comment by crisbeto** [comment]
What version are you using? I pushed a fix for this in https://github.com/angular/material/pull/7936, but I don't know if it has been included in an RC yet.

**Comment by corentin-gautier** [comment]
@crisbeto 1.1.0-rc2, I'm gonna try updating to rc4 see if it's still there

**Comment by corentin-gautier** [comment]
@crisbeto yep ok it's been fixed, my bad ! Closing & thanks for your work
