### ISSUE TITLE
md-swipe triggers to light-footed

### ISSUE THREAD

**Issue by graphefruit** [angular/material#8255]
Hello Team,

this ticket is not a bug rather an improvement.

I've mad a two short gifs:
- https://giphy.com/gifs/xT1XGY6zZpXUx5cLcc
- https://giphy.com/gifs/l3V0CUsGnlrTrUamQ

The problem is that the events are triggered very fast on a mobile device while scrolling with the "finger".

Swiping on a mobile device is likely not always just straight up, more likely up/down-left or up/down-right, which is the case why the md-swipe-left/right is triggered.

This is specially recognizable in a tab-component while scrolling and having swipe events to change the tab-container.

Here's the codepen: http://codepen.io/anon/pen/ONBppK
Visit it with an emulator (finger-swiping).

PS: On browser this isn't so good reproduceable, on a mobile browser its more easier and take more into account.

Thanks in Advance
Graphefruit

**Comment by ThomasBurleson** [comment]
A pull request would be welcomed. 
Closing as "not critical" for ngMaterial 1.x.

> see [Deprecation Policy](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk)
