### ISSUE TITLE
Angular Material 1.1.0 stable

### ISSUE THREAD

**Issue by SAM-BI** [angular/material#8256]
Hello guys,
when can we get the statble version 1.1.0 of Angular Material?

Thanks!

**Comment by ThomasBurleson** [comment]
We plan a release after Google I/O... so start of June

**Comment by anujsingla** [comment]
Hi ,

Please confirm stable version of 1.1.0 angular material ?

Thanks.

**Comment by ThomasBurleson** [comment]
Here are the commands to install the latest release candidate for 1.1.0:

- npm install angular-material 
- npm install angular-material@1.1.0-rc.5
- bower install angular-material#v1.1.0-rc.5

> These install v1.1.0-rc.5. The latest patch release is 1.0.9. The patch release does not contain the hundreds of changes publish in v1.1.0-rc.5.

> Note that the syntax for the RCs has changed to **-rc.<xxx>** == v1.1.0-rc.5
