### ISSUE TITLE
Can't get demo of toolbar "Scroll shrink" to work

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#8258]
Hi,
I've followed the instructions on getting a demo to work:
1) I saw the demo "Scroll shrink" on:
https://material.angularjs.org/latest/demo/toolbar
2) I created the empty template based on:
https://material.angularjs.org/latest/getting-started
3) I pasted the HTML & CSS & JS correctly, resulting in the page:
http://yoav-zibin.github.io/emulator/examples/test_material.html
(I double checked that there are no errors/warnings in console)

There are two issues:
* each list element is taking up a huge amount of space (no idea why)
* the toolbar doesn't always shrink: sometimes it does and sometime it doesn't,
see video: https://youtu.be/krkhALdmCr4

**Comment by yoav-zibin** [comment]
BTW, the demo itself (in https://material.angularjs.org/latest/demo/toolbar) sometimes works and sometimes doesn't, see how it doesn't work here:
https://youtu.be/w7UAof0ryZM?t=20s

**Comment by chris-eaton** [comment]
I can replicate the problem (intermittently) on the demo page

**Comment by igdtl** [comment]
@yoav-zibin 

The list elements taking a huge amount of space issue is a known bug #8094
