### ISSUE TITLE
Toast always opens at view port height

### ISSUE THREAD

**Issue by ericellb** [angular/material#826]
When using mdToast, it will always open at the view port height no matter the vertical size of the application.

This first snapshot is when the page is scrolled all the way up. We can see the toast appear at the bottom of the view.
<a href="http://imgur.com/jG3BjIW"><img src="http://i.imgur.com/jG3BjIW.png" title="source: imgur.com" /></a>

This second snapshot is when the page is scrolled slightly lower. We can see the toast appearing at the exact same coordinates as it did before. It is no longer showing up at the bottom of the current view. 
 P.S. The button is fixed in case it is confusing.
<a href="http://imgur.com/rbnARg8"><img src="http://i.imgur.com/rbnARg8.png" title="source: imgur.com" /></a>

It seems like the toast position is being calculated by the height of the viewport and not the height of the browser.

**Comment by rschmukler** [comment]
#1106 covers the non #1067 use case of this. Closing as a duplicate.
