### ISSUE TITLE
Dynamic custom palettes outside of config block

### ISSUE THREAD

**Issue by CodyMorris** [angular/material#8261]
After reading through a few other open issues regarding custom themes and theme switching, as well as reading through related source, I cant figure out how to generate custom palettes based on an API response.

Basic issue is as follows
1) Value cant be fetched from backend service during the config phase
2) Even if I use methods of exposing the themeProvider in a root controller, palettes defined through this method don't get applied when running generateTheme()

I understand theres a few issues that touch on this through the aspect of dynamically switching themes, but I didn't find anything focused specifically on palettes.

I think the only other option is to delay bootstrapping and requesting the hex values before bootstrapping the app, but my backend is protected using AD, so this would require some serious code duplication for auth.

I love this library, thanks for all the hard work and really appreciate any response.

**Comment by ThomasBurleson** [comment]
Will not fix for 1.0.

**Comment by CodyMorris** [comment]
awesome thanks for the update Thomas

**Comment by ThomasBurleson** [comment]
@CodyMorris - The closing of this issue does not mean that your issue is not valid. Rather it falls within our deprecation category.  For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

> Pull Requests are welcomed to resolve this issue. But note that all PRs will be merged into master; if their scope of changes or impact is too large they will be rejected.
