### ISSUE TITLE
Does 1.0.8 contain fixes in 1.1.0-rc4?

### ISSUE THREAD

**Issue by mackelito** [angular/material#8272]
Or is 1.1.0-rc4 still the "later one"?

**Comment by crisbeto** [comment]
[You can check the changelog for yourself.](https://github.com/angular/material/blob/master/CHANGELOG.md)

**Comment by mackelito** [comment]
I did but at a glance it seem to be so different..
Ok.. so you have "cherrypicked" some of the this to add into the 1.0.8! :)

Thx for the reply!
