### ISSUE TITLE
Version 1.04 has x2 better performance than the latest 1.08 version on IE Edge (V25) or other version of IE

### ISSUE THREAD

**Issue by mzaarour** [angular/material#8273]
Thank you guys for you work. I  use material design for my web application and verry satisfied. 
I have just one problem which is the latency of the response on IE. 
 In fact, material runs ok in all browser but from version 1.05 to 1.08, the performance one IE Edge is poor and unusable. 
There was something added in version 1.05 that have penalized the performance. You can try on you demo site by switching from versions. 

Please do you think you ca do something with that ? 

Thank you in advance !

**Comment by mzaarour** [comment]
Hi all, hope it can can help, i have tried these in IE : 

- Test 1 : Version 1.04.js + 1.04.css ==> OK on IE (and all browsers)
- Test 2 : Version 1.04.js + 1.08.css ==> NOK on IE (OK on all others browsers)
- Test 3 : Version 1.08.js + 1.04.css ==> better than Test 1

**Comment by ThomasBurleson** [comment]
The most recent version [with significant fixes and new features] is in HEAD (recent snapshot is v1.1.0-rc4). The 1.0.8 is a **patch** release that is *behind* `master`. Please use HEAD or v1.1.0-rc4.

**Comment by mzaarour** [comment]
You are the best guys ! My fault. 
I tried the lastest version 1.1.0-rc4 and everything seems to be ok for performance on all browsers even in IE edge ! Good effort ! 

Thank you again !

**Comment by ThomasBurleson** [comment]
Excellent. Thanks for the update.
