### ISSUE TITLE
WP/IE Big performance issue from RC 4 to 1.0.8

### ISSUE THREAD

**Issue by graphefruit** [angular/material#8274]
Hello Angular-Team,

I'm also refering to #8273 and did some research.
I had RC 4.0 firstly running and upgraded it some hours ago. The performance on WP/IE fall off drastically.

I've made some profiling and found out that 
- `innerHTML`
- `focus`
- `insertBefore`
- `appendChild`

Doing some realy bad stuff in the new version.

Profiling-Screens - 1.0.8: 
![v_1 0 8_1](https://cloud.githubusercontent.com/assets/6260244/14917388/18c46148-0e1f-11e6-9970-8dd5507206c0.png)
![v_1 0 8_2 png](https://cloud.githubusercontent.com/assets/6260244/14917390/1a63101c-0e1f-11e6-9bca-c0e6494476d7.png)

Profile-Screen: RC -4
![rc_4](https://cloud.githubusercontent.com/assets/6260244/14917394/231642ec-0e1f-11e6-8e2f-43d5d9040c58.png)

There is a realy big gap from 1 second to 125 ms, which makes everything unsuable, even click-events are delayed to 4-5 seconds.

Hopefully you can find that one, need to stick yet to RC 4 actually.

Thanks in advance
Graphefruit

**Comment by ThomasBurleson** [comment]
The most recent version [with significant fixes and new features] is in HEAD (recent snapshot is v1.1.0-rc4). The 1.0.8 is a **patch** release that is *behind* `master`. Please use HEAD.

**Comment by graphefruit** [comment]
Sorry. My fault ;/
