### ISSUE TITLE
nested md-menu doesn't work after second mouseenter

### ISSUE THREAD

**Issue by masitko** [angular/material#8280]
Easiest way to check this issue is to go to [official Menu Bar demo](https://material.angularjs.org/latest/demo/menuBar). Try to open File menu and then move your mouse over "New". It will open a sub-menu as expected but there is an error on mouseleave:
```
TypeError: Cannot read property 'open' of null
    at angular-material.min.js:13
    at angular.js:17918
    at e (angular.js:5552)
    at angular.js:5829
```
and sub-menu doesn't open any more. Looks like the nested menu is being removed from the DOM on mouseleave.

**Comment by ThomasBurleson** [comment]
I am unable to reproduce this on https://material.angularjs.org/HEAD/demo/menuBar.
> Using Chrome 50.0.2661.86 (64-bit) on Mac 10.11.4 (15E65)
