### ISSUE TITLE
mdSelect: dropdown positioning is wrong

### ISSUE THREAD

**Issue by jayeshanandani** [angular/material#8283]
**Behavior**:
-  What is the issue? 
 Wrong positioning on md-options in md-select.
-  What is the expected behavior? 
  The options should always appear below the main control.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
[Link to material latest code with demo](https://material.angularjs.org/HEAD/demo/select)
-  Details: (This needs to be tried with State dropdown in basic usage)

1. Try to select the first option.
2. Try to select some option in between the range.
3. Try to select few last options available and see the position of md-select changes each time and while the last element is selected the options dropdown is on top of select itself.

**Angular Versions**: *
-  Angular Version:  1.4+
-  Angular Material Version: HEAD

**Additional Information**:
-  Browser Type: * All
-  Browser Version: * Latest
-  OS: * Mac

Related issues: #5754, #5435, #7162

**Comment by RolandHeath** [comment]
Confirmed - it looks like this is a consequence of positioning the dropdown relative to the selected element. 

Because the selected element is positioned over the top of the select, if one of the first two or last two elements is selected, the dropdown doesn't position itself the same as if a middle element is selected.

I'm not sure if this is intentional, I couldn't find the spec for select elements.

**Comment by crisbeto** [comment]
It seems pretty intentional to me, the logic is: a) Position the dropdown within the viewport b) Try to position the selected option on top of the select's label. The linked related issues seem to be different, because the dropdown there is positioned incorrectly.

**Comment by RolandHeath** [comment]
The behaviour does seem correct then, even if it is not what the OP expected.

I looked at the codepens for some of the linked issues, and after updating to the latest and simplifying a bit, I was able to make them follow this behaviour consistently as well.

If there's enough interest (or a good PR), and it doesn't violate some part of the spec, it might be worth having an option to align the dropdown below the control (like a standard html select), but that would be a feature than a bugfix.

**Comment by jayeshanandani** [comment]
I tried to dig into specs but didn't found any specs that resemble how this should be positioned. Looking at a few use cases sometimes when your dropdown is on top of nav bar or some position at the top of the screen it might result into dropdown options being not readable/clickable by users.

**Comment by clshortfuse** [comment]
I don't see what's wrong.

Here's the spec: https://www.google.com/design/spec/components/menus.html#menus-simple-menus

**Comment by jayeshanandani** [comment]
@clshortfuse Thanks for link. Closing this issue as it is in lines with what material suggests.

**Comment by esmaydogdu** [comment]
Hey,
I am also struggling with positioning md material dropdowns.
Also when I write css for one of them, all of it effects from it. So I use  data-md-container-class="whatEverYouLike" in the <md-select> 
whatEverYouLike then become a class with md-select-menu-container so at least you can write seperate css
