### ISSUE TITLE
md-tabs performance (updateInkBarStyles gets executed in never ending loop)

### ISSUE THREAD

**Issue by aresn** [angular/material#8289]
**Actual behavior**:

**updateInkBarStyles** function inside **tabs.js** constantly gets executed in background, causing performance problems in mobile devices.

-  What is the issue? 

inside updateInkBarStyles totalWidth is always larger by exactly 2px than tabWidth, so 
` if (totalWidth > tabWidth) $mdUtil.nextTick(updateInkBarStyles, false);` always pass.

Here is a link to CodePen  that I created by modifying the existing angular material demo and just adding "md-center-tabs" to tabs options.

http://codepen.io/madani/pen/ZWmbXg 

Try to set a breakpoint inside updateInkBarStyles to see the problem for yourself.

**Comment by DevVersion** [comment]
Thanks @aresn for the great issue report. 

The `2px` are caused by the `calcPagingWidth` function, which adds by default `1px` and then always rounds up (`ceil`).
