### ISSUE TITLE
floating icon with mdAutocomplete

### ISSUE THREAD

**Issue by nicgirault** [angular/material#8295]
I would like to be able to add a floating icon on the left side of an autocomplete input as I would do with a simple input field:

```jade
md-input-container.md-icon-float
    label Example Label
    md-icon(md-svg-src="plus")
    input
```

Here are two examples of code I would like to be able to write:

```jade
md-autocomplete(
    md-search-text="searchText"
    md-items="movie in movies | filter : searchText"
    md-item-text="movie.originalTitle"
    md-min-length="0"
    md-floating-label="Film"
    md-icon="movie"
  )
```

or event better:
 
```jade
md-input-container.md-icon-float
    label Example Label
    md-icon(md-svg-src="plus")
    input(md-autocomplete)
```

Thank you

**Comment by RolandHeath** [comment]
A solution to many of these issues might be if md-autocomplete could take an input as a parameter, similar to what md-chips does. 
That would allow for further customization, as we could use a modified input element with all the parameters they allow. 
Plus, I wouldn't keep seeing issues like this one, thinking it was possible, then remembering that I was thinking of md-chips :-P

Autocompletes are inputs, they should do everything that inputs can do.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
