### ISSUE TITLE
Toast Big Visual Bug

### ISSUE THREAD

**Issue by allocenx** [angular/material#8296]
So i am building a website around angular material and when i started using toast service i get this big visual bug at the bottom, like in the image: [http://imgur.com/H5dh9ij](http://imgur.com/H5dh9ij).

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0.rc3

**Additional Information**:
-  Browser Type: Chrome, Firefox, any
-  Browser Version: Latest

Anyone have any ideeas? And no its not from my custom style, i already disable it and tested again and the same thing. Did anyone experienced this sort of visual bug and has some fixes for it?

Demo: [http://5.13.173.126/hekatev2/new/build/#/home](http://5.13.173.126/hekatev2/new/build/#/home). Click on Sign In, a dialog will appear and click LOGIN and you'll see the behavior.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
