### ISSUE TITLE
What's the syntax theme in the update?

### ISSUE THREAD

**Issue by Nikki1993** [angular/material#8300]
Hey,

A bit of an unusual question, what's the syntax theme shown in the screenshot (and is is available for atom editor)? https://cloud.githubusercontent.com/assets/210413/14587401/f46c7c8c-0477-11e6-9cfc-79cecebec121.png 

I saw it in the changelog https://github.com/angular/material/blob/master/CHANGELOG.md#110-rc4-2016-04-15

**Comment by karma4u101** [comment]
yes ;) I happen to read your issue report and can probably can answer it for you so no need for any MD devs to spend time on it ;). 
The code syntax is from highlight.js [1] you will find a matching style here [2] 
[1] https://highlightjs.org
[2] https://highlightjs.org/static/demo/

**Comment by Nikki1993** [comment]
@karma4u101 Thanks a lot!
