### ISSUE TITLE
ngDblclick on mdListItem does not add hover or ripple effect

### ISSUE THREAD

**Issue by astynax777** [angular/material#8303]
I have an md-list-item with an ng-dblclick on it which switches the list item to edit mode.  I expected the md-list-item to act similar to one with ng-click.  If I were to use an ng-click, it would add a hover and ripple effect, however this is not the case with ng-dblclick.  

I'm using Angular v1.5.5 with material v1.1.0-rc4.

Codepen: http://codepen.io/anon/pen/PNxOde

**Comment by DevVersion** [comment]
@astynax777 Let's talk a bit about the intention of showing the hover, ripple effect etc.

Currently we're always checking for attributes, which indicate, that the list-item should trigger an action by using a button.

```js`
if (tAttrs.ngClick || tAttrs.ngHref || tAttrs.href || tAttrs.uiSref || tAttrs.ngAttrUiSref) {
```

It would be super easy, to add support for `ng-dblclick`, but I'm just a bit curious. 
In my opinion, a double click is not indicating an action on a button.

PS: We're not supporting `ng-dblclick` in other components.  cc. @ThomasBurleson

**Comment by astynax777** [comment]
Sure thing @DevVersion.  I saw that you add a button to the content to indicate the md-list-item has an action.  Along with the button comes the pointer cursor and the hover effect.  To the developer - we think that this is being added to the actual md-list-item itself but upon inspecting the results we see that the content is wrapped in a button and the click attribute (and some others such as my ng-if) are copied over minus the ng-dblclick.  Without this hover and cursor effect, the user has no indication that they can perform an action on the list item.  Currently I am working around this by adding an ng-click="angular.noop()", but I believe that the functionality should be the same for a click or double-click.  If we wire up an md-button with only an ng-dblclick it still has the hover/ripple effect.  So should we generate a button with an ng-dblclick?

**Comment by DevVersion** [comment]
@astynax777 Thank you for the accurate description.

-  I can see the point and it seems to be reasonable :+1:

**Comment by astynax777** [comment]
@DevVersion I appreciate your time in this!
