### ISSUE TITLE
md-icon-float md-icon-right class not working since 1.0.5

### ISSUE THREAD

**Issue by lucasgao** [angular/material#8305]
After update to 1.0.7 the class="md-icon-float md-icon-right md-block" is not working.

**Comment by lucasgao** [comment]
md-input-container.md-icon-right > md-icon:last-of-type {
  margin: 0;
  right: 2px;
  left: auto;
}

was removed

**Comment by jobsamuel** [comment]
My templates (inputs that have icons in the right side) are broken because of this :cry:

**Comment by ThomasBurleson** [comment]
Due to the daily improvements  on the project, we only support issues reproduced on HEAD/master.
