### ISSUE TITLE
ng-change using md-Dialog

### ISSUE THREAD

**Issue by iyunusov** [angular/material#8309]
I am trying to open mdDialog on ng-change of md-select element which is not working, but ng-click is working as intended. Thank you for your reply.
[CodePen link](http://codepen.io/Yunusov/pen/wGQyRe?editors=1011).

**Comment by Emeegeemee** [comment]
I've updated your [Codepen ](http://codepen.io/anon/pen/aNQjGv?editors=1011). I had to update the version of angular material's javascript from 0.9.4 to 1.0.7 (though you were using 1.0.7 css) and change ng-value to just value. Let me know if that works for you.

**Comment by DevVersion** [comment]
Works as expected. Thanks @Emeegeemee

**Comment by iyunusov** [comment]
Works as expected thanks
