### ISSUE TITLE
clickOutsideToClose in $mdBottomSheet does not work

### ISSUE THREAD

**Issue by rmaspoch** [angular/material#8316]
In version 1.0.7 clickOutsideToClose does not work as expected. Please modify the following pen to use version 1.0.7 to reproduce the issue:

https://codepen.io/team/AngularMaterial/pen/mVxgbg

There is also another issue related to the backdrop, where it does not cover the sidenav. The backdrop z-index is lower than the sidenav z-index.

This issue is probably a duplicate of https://github.com/angular/material/issues/7905, but that one was closed as "not reproducible".

**Comment by DevVersion** [comment]
Seems to work fine with `1.1.0-rc4`
- https://codepen.io/DevVersion/pen/EKOzEd
- http://codepen.io/DevVersion/pen/WwYBzj
