### ISSUE TITLE
Entries for md-select-header and md-colors missing from the online docs

### ISSUE THREAD

**Issue by camden-kid** [angular/material#8317]
According to this [CHANGELOG page](https://github.com/angular/material/blob/master/CHANGELOG.md)  there exists two new directives `md-select-header` and `md-colors`. The latest online docs page does not list either under the Directives section.

Also, where is the Theme Picker mentioned in this [CHANGELOG page](https://github.com/angular/material/blob/master/CHANGELOG.md#110-rc3-2016-04-13)?

**Comment by Splaktar** [comment]
`md-select-header` is documented here (https://material.angularjs.org/latest/demo/select#select-header)and here (https://material.angularjs.org/latest/api/directive/mdSelect).

`$mdColors` docs are here: https://material.angularjs.org/latest/api/service/$mdColors
