### ISSUE TITLE
md-separator-keys ignores shift, other modifiers

### ISSUE THREAD

**Issue by vbraun** [angular/material#8319]
**Actual behavior**:
-  What is the issue? md-separator-keys ignores shift, other modifiers
-  What is the expected behavior? Only the given separator keys should be used to separate chips, not combinations with key modifiers.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : https://material.angularjs.org/HEAD/demo/chips
-  Details: The official "Custom Separator Keys" demo sets up comma as separator, but also shift+comma separates. On an English/Dvorak keyboard, this is the "<" key. On a Danish keyboard, this is the "æ" key. This makes it impossible to enter chips containing these characters.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: HEAD, 1.0.7

**Additional Information**:
-  Browser Type: Chrome, Firefox
-  Browser Version: Chrome 50, Firefox 45 
-  OS: Linux, OSX
-  Stack Traces:

Spring cleaned issue: #6505

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
