### ISSUE TITLE
Error to run docs task

### ISSUE THREAD

**Issue by gadzhimari** [angular/material#8320]
**Actual behavior**:
-  What is the issue? I'm trying to run gulp docs task, but terminal produced the unhandled error.
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: Google Chrome
-  Browser Version: 50.0.2661.86 (64-bit)
-  OS: OS X 10.11.4
-  Node Version: 6.0.0
-  NPM Version: 3.8.6
-  Gulp Version: 3.9.1
 - Stack Traces:
----
➜  material-master gulp docs
(node:3592) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:3592) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[17:51:53] Using gulpfile ~/Downloads/material-master/gulpfile.js
[17:51:53] Starting 'build-scss'...
[17:51:53] Building css files...
[17:51:53] Starting 'build-js'...
[17:51:53] building js files...
[17:51:53] Starting 'docs-html2js'...
[17:51:53] Starting 'demos'...

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: src/components/autocomplete/demoBasicUsage/index.html
Error: Invalid CSS after "...emoBasicUsage {": expected "}", was "<div ng-controller="
        on line 1 of src/components/autocomplete/demoBasicUsage/index.html
>> .autocompletedemoBasicUsage {
   -----------------------------^

    at options.error (/Users/gadzhimari/Downloads/material-master/node_modules/node-sass/lib/index.js:271:32)

**Comment by JeanPerriault** [comment]
Additionally:
* Can't find any reference to ".autocompletedemoBasicUsage" in the project
* Same issue with `npm run watch`
* Same issue with branches:
** master
** release/1.1.0-rc4
** release/1.0.8

**Comment by gadzhimari** [comment]
I don't why, but I just clone the repo and install all dependencies. After that, I run gulp docs task and got this error. Here the proof.
![2016-05-12_13-18-31](https://cloud.githubusercontent.com/assets/1849608/15211475/1781a44c-1844-11e6-8922-9abe539bd971.png)

**Comment by ThomasBurleson** [comment]
We do not support Node 6 yet for builds; only Node 4.x and 5.x are supported.

**Comment by JeanPerriault** [comment]
Is this Node 6 support scheduled in roadmap?
Should I create an issue for that?

I can not find any reference to supported node version in documentation, github or website, have I missed something?
Should I create an issue for that?
