### ISSUE TITLE
md-tab containing an md-progress-circular causes infinite loop in Firefox

### ISSUE THREAD

**Issue by johnhok** [angular/material#8323]
**Actual behavior**:
-  What is the issue? *
An md-progress-circular element inside an md-tab causes the DOMSubtreeModified method to be fired infinitely on Firefox.

**Angular Versions**: *
-  Angular Material Version: 1.1.0

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : 
http://codepen.io/anon/pen/yOQdoG
-  Details:
It's hard to see but if you take the HTML block and add a log into the DOMSubtreeModified listener for md-tabs you'll see that updatePagination and updateInkBarStyles will constantly be fired if there is a progress bar inside an md-tab.

**Comment by crisbeto** [comment]
This should be resolved in 1.1.

**Comment by crisbeto** [comment]
I believe this is an issue with tabs, not the progressbar.

**Comment by crisbeto** [comment]
Hmm it definitely fires a lot, but it's not an infinite loop. Take a look at this: http://codepen.io/crisbeto/pen/reQERa

**Comment by johnhok** [comment]
Hmm when I modify the actual listener in the source, it's console logging forever.

**Comment by crisbeto** [comment]
Perhaps it's just Codepen refreshing ~1s after the last keystroke?

**Comment by johnhok** [comment]
Sorry it looks like it's only in 1.1.x

I was able to reproduce it here for Firefox http://codepen.io/anon/pen/KzrOBV

**Comment by crisbeto** [comment]
Alright, now I see it, but I'm not sure it's a bug, because the progress in 1.1 is being animated with JS, which needs to modify the DOM. This is what causes it to keep firing the event. I'm not sure why it's not firing on Chrome (it actually also happens in IE and Edge as well), but my guess is because the `DOMSubtreeModified` is deprecated.

**Comment by crisbeto** [comment]
I'll close this because that behaviour is expected.
