### ISSUE TITLE
Impossible to write a protractor test once you use a toolbar (because there is a $timeout every 5 seconds)

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#8324]
Hi,
I'm trying to use protractor, but I get:
Failed: Timed out waiting for Protractor to synchronize with the page after 11 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md. The following tasks were pending:
- $timeout: function (){a=n,e.apply(d,c)}

I've tracked it down to an infinite $timeout loop at updateToolbarHeight (where you debounce things for 5 seconds, which call updateToolbarHeight again).
See stacktrace and code below.

Protractor recommends replacing that infinite $timeout loop with $interval, see:
https://github.com/angular/protractor/blob/master/docs/timeouts.md
"If your application continuously polls $timeout or $http, it will never be registered as completely loaded. You should use the $interval service (interval.js) for anything that polls continuously (introduced in Angular 1.2rc3)."

This is an example stacktrace that I took to show that updateToolbarHeight calls itself via debounce:

  at timeout (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.js:19149:7)
    at debounced (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.js:1171:17)
    at onContentScroll (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.js:18031:11)
    at updateToolbarHeight (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.js:18092:11)
    at http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.js:1174:16
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.js:19157:31"

These are the relevant code portions showing the $timeout loop (every 5 * 1000 milliseonds):
        var debouncedUpdateHeight = $mdUtil.debounce(updateToolbarHeight, 5 * 1000);

function onContentScroll(e) {
          var scrollTop = e ? e.target.scrollTop : prevScrollTop;
          debouncedUpdateHeight();

function updateToolbarHeight() {
          ...
          onContentScroll();
        }

**Comment by ThomasBurleson** [comment]
We do not support Protractor tests/issues at this time. Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
