### ISSUE TITLE
$mdToast doesn't hide the old toast prior showing a new one

### ISSUE THREAD

**Issue by divashutin** [angular/material#8327]
**Actual behavior**:
-  What is the issue? *
When trying to show multiple toasts at the same time - overlapping items are shown with broken toast button handlers.
-  What is the expected behavior?
Either one toast is visible at a time or each toast properly handles it's action buttons.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/oxQKyd?editors=1010
-  Details: Clicking "Close" button closes toasts in pairs (in other setup it was closing only top toast).

**Angular Versions**: *
-  Angular Version: 1.5
-  Angular Material Version: 1.08

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.x
-  OS: Ubuntu, MacOS

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by divashutin** [comment]
Hi Thomas,
You've marked it as Deprecated - does it mean that the issue is fixed in the upcoming release?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by trevorhreed** [comment]
Can we reopen this now?
