### ISSUE TITLE
md-select is slow in firefox

### ISSUE THREAD

**Issue by kslo88** [angular/material#8328]
**Actual behavior**:
-  What is the issue? * I have a form which has several md-selects ~ 10. In firefox, it takes 4-5 seconds to display the md-options whereas in safari,chrome it is almost instant.
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: * md-select demo on firefox shows the delay
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version: 1.5.2
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: * Firefox
-  Browser Version: * 38esr,46
-  OS: * Centos, Osx el captain
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by kslo88** [comment]
Any update or workaround on this?

**Comment by kslo88** [comment]
@ThomasBurleson Any update on this issue?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
