### ISSUE TITLE
md-autocomplete flashes md-close on Chrome and Firefox (osx)

### ISSUE THREAD

**Issue by leocaseiro** [angular/material#8330]
**Actual behavior**: Animation bug
-  What is the issue? The md-close button is flashing on selected-item
-  What is the expected behavior? Natural animation instead of flashing

**CodePen** or Steps to reproduce the issue: 
-  Angular Material webiste which shows your issue: https://material.angularjs.org/latest/demo/autocomplete 

**Angular Versions**: 1.4.8
-  Angular Version: 1.4.8 (tested up 1.5.3, same issue)
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Google Chrome / Firefox
-  Browser Version:  50.0.2661.86 (64-bit) / 41.0.2
-  OS: OS X El Capitan 10.11.4

It works fine on Safari...

**Comment by leocaseiro** [comment]
I love the Angular Material team feedback... 😒

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (402/400 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:27861)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1b8INy-002B2U-Tt
	for yann.dupuy@zyapps.com; Thu, 02 Jun 2016 04:29:31 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=o1WkckG61NcSLkbkJiFfZ2Efy6c=; b=izHlp4H38BO0WVBq
	BT5Rz5LKNDqhgw0nk5prnPM5T0NqpCsWlTZ9R8vbw3YUPiTSgBWBR4SqJIjj2Nqo
	dHbBN01yDKX5Af3zFKlOP/L9uzGKP4fCIe8IIso4lFLl1VvArJa1y83vq1yOkoAv
	43ZNMq01QnEc+XIYV1HV/yqD2kw=
Received: by filter0458p1mdw1.sendgrid.net with SMTP id filter0458p1mdw1.25122.574F99D622
        2016-06-02 02:28:38.944905034 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id dGWg2MCVRg27qboB-hyZpw
	for <yann.dupuy@zyapps.com>; Thu, 02 Jun 2016 02:28:38.912 +0000 (UTC)
Date: Wed, 01 Jun 2016 19:28:38 -0700

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by leocaseiro** [comment]
Thank you @ThomasBurleson.
I appreciate you sharing this post.
