### ISSUE TITLE
Angular material flex grid system not working in IE11

### ISSUE THREAD

**Issue by pramitkundu92** [angular/material#8331]
Angular material is terribly slow in IE11. md-card and flex grid layouts are not rendered properly, fields rendered by ng-repeat to achieve dynamicity gets stacked up one over the other instead of coming in multiple rows. md-toolbar size is reduced. ui-router not working correctly, state transition does not work for many states. Please suggest some fixes or workarounds so that I can make the app work better in IE11. Thanks!
I am using,
-  Angular Version: 1.5
-  Angular Material Version: 1.0.5
![screenshot](https://cloud.githubusercontent.com/assets/18255051/15009827/49b2070c-1206-11e6-980b-3b7e33d66123.png)

**Comment by berndvdveen** [comment]
@pramitkundu92 Maybe add a plunker with a full app / code snippet for a reproducible scenario

**Comment by pramitkundu92** [comment]
The problem is not occurring in my test code which has static HTML screens. This problem is coming up only when am traversing over screen metadata to generate HTML screens dynamically using ng-repeat and ng-include to include partials for each field type

**Comment by crisbeto** [comment]
That should still be possible to reproduce in a codepen, otherwise this is too vague for us to be able to help.

**Comment by pramitkundu92** [comment]
here is a small plunk: https://plnkr.co/edit/n6Mw56WTls8qWtsZrA3x?p=preview

**Comment by crisbeto** [comment]
That one renders fine for me on IE:
![plunker_-_internet_explorer_2016-05-04_14-45-16](https://cloud.githubusercontent.com/assets/4450522/15014533/dbfeaa8e-1206-11e6-854e-091cd4002438.png)

**Comment by graphefruit** [comment]
@pramitkundu92 you already tried to dismiss all custom `CSS` files in your project? Had much problems with own `CSS-Files`

**Comment by pramitkundu92** [comment]
@crisbeto  the layout should come in 4 columns and 3 rows, since there are 10 items and we are giving flex-lg-25

**Comment by pramitkundu92** [comment]
@graphefruit  I took out my custom CSS files, but that did not work as well.
Updated the plunk, now its a miniature version of what am using in order to parse screen metadata and generate HTML5 screens on the fly

**Comment by DevVersion** [comment]
As mentioned in the layout docs. ([Here](https://material.angularjs.org/HEAD/layout/options))
> layout-wrap allows flex children to wrap within the container if the elements use more than 100%. 

So, the issue in your demo is, that you apply responsive width's to the items, which means, that those will shrink / grow as needed in relative to the parent / viewport (Since you use `flex-25` for example, which is 25%) 

The point is, that those items will never use more than `100%` of the parent container (See quote above) 

To fix your issue, you need to apply a fixed width, which is not growing and can exceed the 100%.

I've updated your demo, to use some fixed width's.

http://codepen.io/DevVersion/pen/GZPWPz

**Comment by pramitkundu92** [comment]
The problem that is occurring in the actual project is that a div with layout-row is displaying all the rows stacked up one after another to form a single overlapping row. But in firefox, all the rows are displayed properly as separate rows.
@DevVersion if I do not use flex then I lose responsiveness, because of that fixed width, also, I need to make the fields render dynamically where fixed widths can cause a problem.

**Comment by ThomasBurleson** [comment]
Unable to support without better CodePen.  Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

> Please note that IE has known issues with FlexBox. We are working on improvements to the Layout API.
