### ISSUE TITLE
Md-max-chips is not disabling md autocomplete when get in max

### ISSUE THREAD

**Issue by mariohmol** [angular/material#8332]
-  What is the issue? *
When I use md-chips with a md-autocomplete internally, and set md-max-chips=1 to md-chips, it is limiting correctly to 1. But the autocomplete still enabled and is possible to write a text in the field.

-  What is the expected behavior?
The autocomplete must be set to disabled when the number of elements in md-chips get in md-max-chips

**Angular Versions**: *

"angular": "^1.5.0",
 "angular-material": "^1.0.8",

**Additional Information**:
-  Browser Type: * Chrome
-  OS: * OSx Capitan

Here is how to reproduce:

* http://codepen.io/mariomol/pen/RaERdL

The solution could be a watch in md-chips list that when this changes check if length==md-max-chips, if so, ng-show=false in md-autocomplete

bests

**Comment by DevVersion** [comment]
That is currently by intention, so I'm able to change that really easy. 

But in this case, we have no specific policy, of how it should behave property.

**Comment by topherfangio** [comment]
Although it would be nice to have this be a bit more automatic, I think that adding the following to your `<md-autocomplete>` is a viable enough workaround:

```html
<md-autocomplete ng-hide="ctrl.selectedVegetables.length > 0"></md-autocomplete>
```

Specifically, this gives the developer the control to do whatever (s)he wants. In this case, I wanted to hide the autocomplete, but I could have easily also just wanted it disabled (which works just fine).

I'm afraid if we make it automatic, we'll make it more restrictive than what is currently available now.

If others pitch in with opposing thoughts, I'm happy to change my position, though. I don't feel very strongly one way or the other :smile:

**Comment by mariohmol** [comment]
I agree that the workaround is easy, but the problem is that it affects the functionality of md-max-chips.

If part of the process is manual, it should not have md-max and make it all in developer side. 
But if you have this parameter, expects to work all by itself. Thats my opinion.

**Comment by alaksandarjesus** [comment]
I used
` <md-chips ng-model="ctrl.selectedCategories" md-autocomplete-snap md-transform-chip="ctrl.transformChip($chip)" md-require-match="ctrl.autocompleteDemoRequireMatch" md-max-chips="{{ctrl.maxChips}}" ng-keydown="ctrl.stopEnteringText($event)"> `

and in controller

```
self.stopEnteringText = function(event) {
            if (self.selectedCategories.length == self.maxChips) {
                event.preventDefault();
                event.stopPropagation();
            }
        }
```
It worked, but want to confirm is this the right approach.

**Comment by kondalraodurgam** [comment]
I used this is not working properly
   <md-chips ng-model="myItems" md-max-chips="5">
         <md-autocomplete ng-hide="myItems.length > 5" ...></md-autocomplete>
    </md-chips>


i could'n get exactly answer
