### ISSUE TITLE
md-menu-item not full width in chrome

### ISSUE THREAD

**Issue by thatcorey** [angular/material#8335]
**Actual behavior**:
-  What is the issue? md-menu-item doesn't take up the whole width in a md-menu in Chrome
-  What is the expected behavior? md-menu-item should act the same as in other browsers (full width)

**Screenshot** (from the angular material demo site)
<img width="551" alt="screen shot 2016-05-04 at 7 43 11 am" src="https://cloud.githubusercontent.com/assets/443290/15017869/3457b954-11cc-11e6-80f2-a77b8e331045.png">

**Angular Versions**: 
-  Angular Version:  Unknown (this is from the demo site)
-  Angular Material Version:

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: Version 52.0.2724.0 canary (64-bit)
-  OS: OSX 10.11.4
-  Stack Traces: n/a

**Comment by clshortfuse** [comment]
Try this as a CSS fix:

    md-menu-item>*, md-menu-item>.md-button {
        min-width: 100%
    }

I'm trying to find out what broke this

**Comment by jeffsteinmetz** [comment]
may be related, it also seems to add line breaks between icons and text in md-menu-item

This occurs in Firefox as well (not just chrome).  The same css / html template works as expected when reverting back to angular material version 1.0.8

<img width="248" alt="triangular___dashboards___analytics" src="https://cloud.githubusercontent.com/assets/5488059/15031682/626efc9c-120f-11e6-8598-ab7ea7904421.png">

**Comment by thatcorey** [comment]
Seems to work fine now in Version 53.0.2754.0 canary (64-bit)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
