### ISSUE TITLE
md-datepicker: Input grows unexpectedly when date-picker is opened

### ISSUE THREAD

**Issue by alexilyaev** [angular/material#8337]
**Actual behavior**:
-  What is the issue? *  
When opening the date picker, the input line grows unexpectedly.
-  What is the expected behavior?  
Should not grow, especially annoying when inside a table row, will shift the whole table below it

**CodePen** or Steps to reproduce the issue: *
https://material.angularjs.org/latest/demo/datepicker
-  Details:  
Open the first date picker, see the next line jumps down a bit.
This is because of `height: 40px` that's being added:
```
.md-datepicker-open .md-datepicker-input {
  margin-left: 24px;
  height: 40px;
}
```

**Angular Versions**: *
-  Angular Version: `1.5.0`
-  Angular Material Version: `1.0.8`

**Additional Information**:
-  Browser Type: * Any
-  Browser Version: * Any
-  OS: * Any

**Comment by jayeshanandani** [comment]
Please look at the HEAD release. It seems it's fixed there. [Datepicker Demo](https://material.angularjs.org/HEAD/demo/datepicker)

Just in case 1.0.8 is not the latest version. Please see changelog for more information. 1.1.0-rc-4 is the latest version.

**Comment by alexilyaev** [comment]
@jayeshanandani Right, forgot about the HEAD one. I guess we'll see it in the next release.
