### ISSUE TITLE
Carousel Request

### ISSUE THREAD

**Issue by ryanburnett** [angular/material#8338]
Any plans to add a carousel to Angular Material?

Here are the Bootstrap versions in jQuery and Angular:

- http://getbootstrap.com/javascript/#carousel
- https://github.com/twbs/bootstrap/blob/master/js/carousel.js
- https://angular-ui.github.io/bootstrap/
- https://github.com/angular-ui/bootstrap/tree/master/src/carousel

Thanks.

**Comment by jayeshanandani** [comment]
I don't think this will be in the line of action for 1.1.0 atleast, as there are some components and features in the line for release.

**Comment by stunaz** [comment]
and it is not even in the material design specs

**Comment by RolandHeath** [comment]
I submitting a PR which implements this is probably the fastest (possibly the only) way to get this added to angular material.

**Comment by FDIM** [comment]
If you want one without bootstrap, I made this at some point: https://github.com/FDIM/ng-carousel 
On the other hand, it would be great to have something like this as part of the core though.

**Comment by ThomasBurleson** [comment]
I think this type of component should go in an extensions library (eg  angular-material-extensions). This will not be the core library (angular-material).
