### ISSUE TITLE
md-radio-group has no focus indicator

### ISSUE THREAD

**Issue by eegzapp** [angular/material#8339]
There is no indication of focus for a radio group without a selected button.

Without a focus indicator, a user won't know when they are in a radio group and can choose a radio button with the arrow keys.

Other focusable elements such as checkboxes, inputs and buttons have focus indication.

This can be observed with the following code pen:
http://codepen.io/eegz/pen/RaEVom

1. Select a radio button in the first group, then tab to the second radio group and back.
2. Observe that the first radio group has affordance because the selected radio button has a focus effect.
3. Observe that the second radio group has no focus affordance.

Angular: 1.4.8
Angular Material 1.0.8

**Comment by ThomasBurleson** [comment]
Per feedback from the Material Design UX team, this will not change.
