### ISSUE TITLE
In menubar move out of nested menu to a non-nested menu item causes TypeError

### ISSUE THREAD

**Issue by kzhdev** [angular/material#8342]
**Actual behavior**:
-  What is the issue? *

In openMenuTimeout timer callback, if nestedMenu is null, calling nestedMenu.open in ```if (self.currentlyOpenMenu && self.currentlyOpenMenu != nestedMenu)``` causes an TypeError:

angular.min.js:107 TypeError: Cannot read property 'open' of null
    at angular-material.min.js:13
    at angular.min.js:146
    at e (angular.min.js:43)
    at angular.min.js:46

-  What is the expected behavior?
No TypeError

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

1. In a menubar, hover to a nested menu item to open the submenu
2. Move mouse over to another root menu item.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: *
-  OS: Mac OS X
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
Your Codepen is empty, however this error is resolved with https://github.com/angular/material/pull/7826 in 1.1.
