### ISSUE TITLE
Autocomplete results does not vanish on scrolling the page

### ISSUE THREAD

**Issue by madhairsilence** [angular/material#8345]
**Actual behavior**:
Referring to the doc @ https://material.angularjs.org/latest/demo/autocomplete

**CodePen** or Steps to reproduce the issue: 
- Click the autocomplete checkbox.
- When the result appears, scroll the page (mouse scroll)
- The results are still floating in the screen

* CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:1.X
-  Angular Material Version:1.0.8

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: *
-  OS: Windows
-  Stack Traces:50.0

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Thanks for the issue. I'm currently not able to reproduce your issue. Can you provide more information? e.g which Autocomplete Checkbox you mean? etc.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
