### ISSUE TITLE
md-slider event to stop sliding

### ISSUE THREAD

**Issue by androidfreakers** [angular/material#8346]
Use case: I am using md-slider in my application to select the value from range. Whenever user changes the slider it send a command to update the backend and same time it subscribes to changes from backend.
Issue: Because of dual nature it does not gives a smooth animation of slider.

Desired result: Is there any way to get information that slider has stopped sliding or something?

**Comment by RolandHeath** [comment]
I've tried to make a codepen to simulate the model changing, but I'm not really sure if this is anything like your setup. 
It's at http://codepen.io/RolandHeath/pen/XdooPN
You might be able to modify it to create something that shows what's happening in your app, and that would help a great deal in diagnosing fixing the issue.

**Comment by ThomasBurleson** [comment]
@androidfreakers - So the issue is that while dragging (or click-animating), multiple value changes are triggered until the mouse is released (or the animation stops). Debouncing may not always work because you want to know the final value before querying remote data services ?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
