### ISSUE TITLE
md-autocomplete promise result

### ISSUE THREAD

**Issue by vipul-jain** [angular/material#8347]
I made a call when user first clicks inside autocomplete based on the dropdown value(say A), the result appears.

At next I choose another value from dropdown and made a second call based on that value(say B), this time result is empty from response.

Now I again select value(say A) from dropdown, but I get nothing in autocomplete, or sometimes I get blank fields inside autocomplete.

How do I make unique all md-autocomplete inside ng-repeat ?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
