### ISSUE TITLE
Deleting Input content which already has text doesn't invalidate

### ISSUE THREAD

**Issue by ajdaniel** [angular/material#8350]
**Actual behavior**:
-  What is the issue? If an input programmatically has content. If the user deletes the content, and the input is 'required', the input remains valid
-  What is the expected behavior? the input should be invalid, and should look as such (red box etc.)

**Steps to reproduce the issue: *
-  Details: You can see this on the Angular MD demo page https://material.angularjs.org/latest/demo/input. Scroll down to the 'Errors' section, there is a required input with text 'Nuclear Missile Defense System'. If you select the text and delete it (press Backspace or Delete key) the input is still valid. If you navigate away from the input (tab, or click somewhere else) the input is invalid. 

If I type into the input, then delete it all in the same way as steps above, the text field is invalid before navigating away. This means this issue is only on the first time you delete the content of the input

**Angular Versions**: *
-  Angular Version: 1.x
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50
-  OS: Mac OS X 10.11.4
-  Stack Traces:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
