### ISSUE TITLE
md-autocomplete - directives inside md-item-template makes results wrap blank for couple of seconds

### ISSUE THREAD

**Issue by gilnoy** [angular/material#8352]
**Actual behavior**:
-  What is the issue? I'm using inside item-template a lot ng-if\ng-show directives, and when im opening the results wrap for the first time i get a white box and a delay of few seconds until i see the results - easy to reproduce on firefox
-  What is the expected behavior? see the results immediatly, if not ready then show the progress bar

Link for a video to show the problem - https://cti.ctera.com/invitations?share=d6436d54734c4c6efb5e&dl=0

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version: 1.4.9
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: ALL (Easy to reproduce on Firefox)
-  Browser Version: 46.0.1
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
