### ISSUE TITLE
Too slow on IE 11 and Edge after 1.0.5 version.

### ISSUE THREAD

**Issue by ivanbaj** [angular/material#8353]
Too slow on IE 11 and Edge after 1.0.5 version. Is there a plan to make Angular Material fast again on IE? There is a significant difference between 1.0.5 and later 1.0.X versions.

**Comment by jayeshanandani** [comment]
You should be trying latest release. 1.1.0 -rc4 Angular Material.

In addition there is already an issue being watched upon: #8329

**Comment by ganySA** [comment]
Even 1.1.0-rc4 is pretty slow compare to chrome.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
