### ISSUE TITLE
md-content height in percent?

### ISSUE THREAD

**Issue by Superlukec** [angular/material#836]
Is there possible that you can specify height in percents and not only pixels for md-content?

For example:

This works:
`<md-content class="md-padding" style="height: 200px;">`

This doesn't work:
`<md-content class="md-padding" style="height: 30%;">`

Thank you for your help!

**Comment by leisyj** [comment]
I see the issue has been closed, however I am still having this problem for a column style layout; if I set the style for the md-content in px, it works fine, however if I set it in %, I never get a vertical scrollbar.  Any thoughts?

**Comment by Schneider95** [comment]
Same here

**Comment by csvan** [comment]
Same issue

**Comment by bonatoc** [comment]
Wrap md-content with a div with the desired height, and then set md-content with "height: inherit;"

**Comment by 0101adm** [comment]
same issue.  parent wrapper div with an md-content gets no scrollbar.

div(style='height:100%;')
     md-content(flex='')

**Comment by karray** [comment]
Same here

**Comment by topherfangio** [comment]
Here is a quick fix for the issue: http://codepen.io/topherfangio/pen/epOvBd?editors=110

Basically, you need to add the following so that the flex on the md-content renders properly:

```css
.layout {
   height: inherit;
}
```

We are looking at adding this at a framework level but need to make sure that there are no unintended consequences.

**Comment by karray** [comment]
Here is an example from my project: http://codepen.io/anon/pen/PPoYxG?editors=110
Only the left nav works correctly.
