### ISSUE TITLE
<md-content> is shown above <md-sidenav> for about half a second (during animation of <md-sidenav>).

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#8360]
**Actual behavior**:
-  What is the issue? 
<md-content> is shown above <md-sidenav> for about half a second (during animation of <md-sidenav>).
See this video: https://youtu.be/moL90q-Au6g

This is my left-nav definition:
<md-sidenav class="md-sidenav-left md-whiteframe-z2"
      md-component-id="left" md-is-locked-open="$mdMedia('gt-xs')">

-  What is the expected behavior?
<md-sidenav> z-index should always be higher than <md-content> (even during animations/transitions).

Steps to reproduce the issue: *
Go here:
http://yoav-zibin.github.io/default-theme/app
Open mobile-emulation and choose iphone 6 plus (need a height of more than 600px),
make sure the left-nav is open,
then rotate the phone to see the broken z-index animations.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: rc4

**Additional Information**:
-  Browser Type: it happens everywhere (both on android and ios)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
