### ISSUE TITLE
Missing sourceMappingURL in angular material minified files (had to create another issue because ThomasBurleson "locked and limited conversation to collaborators")

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#8361]
See:
https://github.com/angular/material/issues/8246

I just wanted to add a comment that if anyone else wants to have a version with source mappings (sourceMappingURL) for angular-material JS and CSS,
then I created one here:
https://github.com/yoav-zibin/angular-material-with-sourceMappingURL

You can just include these:
http://yoav-zibin.github.io/angular-material-with-sourceMappingURL/angular-material.min.js
http://yoav-zibin.github.io/angular-material-with-sourceMappingURL/angular-material.min.css

BTW, locking a conversation like this in an open source project is a disgrace in my opinion because you're preventing contribution from the community. You're basically hurting yourself with this behavior (lucky for you, I'm a very stubborn person that doesn't care much about rejection :))

Instead of closing a bug (saying it's not a core feature), you can just prioritize it low (lower than other core features). Because not having sourceMappingURL is obviously a bug in angular material...

If you close again this bug, I will stop contributing to angular material, and it's a shame, because I love this project, see what I've done with it:
http://yoav-zibin.github.io/default-theme/app
(It's open source: https://github.com/yoav-zibin/default-theme/tree/gh-pages/app )
I've reported countless issues, I have more than 100K app installs that use material design, and I have e2e protractor tests, open sourced, https://github.com/yoav-zibin/default-theme/blob/gh-pages/tests/e2e_tests.ts,  that covers most of angular-material directives&services, so I'm likely to find more issues in the future :)

**Comment by EladBezalel** [comment]
Please be aware that this title violates our CoC, 
That issue was closed as part of our deprecation effort.
        For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).

**Comment by yoav-zibin** [comment]
No problems, it's completely OK to close a bug :)
(Also feel free to change the title to whatever seems right.)
It's less OK to close all discussions on the previous issue --- I just wanted to post the workaround (the link to the sourceMapping I created) in case anybody else gets exceptions in production code and they can't reverse/decode the stacktrace.

The post Spring Cleaning 2016 also said:
If we missed something, we hope you'll file a new open issue (citing the closed one) and providing a repro case. We'll clarify our reasoning and reconsider the issue on the new list of current issues. 


E.g., a stacktrace I get a lot in production is:
TypeError: Cannot set property '$window' of null
    at o (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:8:2859)
    at new <anonymous> (<anonymous>:6:27)
    at Object.instantiate (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:41:473)
    at Object.n [as attach] (http://ajax.googleapis.com/ajax/libs/angular_material/1.1.0-rc4/angular-material.min.js:8:2751)

Now that I have my minified version, I can reverse/decode that stack trace:

Original:
TypeError: Cannot set property '$window' of null
    at d (http://yoav-zibin.github.io/angular-material-with-sourceMappingURL/angular-material.min.js:2:2859)
    at new <anonymous> (<anonymous>:6:27)
    at Object.instantiate (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js:41:473)
    at Object.c [as attach] (http://yoav-zibin.github.io/angular-material-with-sourceMappingURL/angular-material.min.js:2:2751)

Decoded:
TypeError: Cannot set property '$window' of null
    at $window (angular-material.js:4066:20)
    at new <anonymous> (<anonymous>:6:27)
    at (unknown) (angular.js:4680:13)
    at instantiate (angular-material.js:4052:21)
    at attach (angular-material.js:3839:28)
    at attach (angular-material.js:6639:23)

I'm still trying to figure out how that's possible, but the point is that this is just one example of why sourceMapping are a crucial feature (otherwise you get stacktraces in prod, and you have no clue what to do with them).

Looking at the code:

function InkRippleCtrl ($scope, $element, rippleOptions, $window, $timeout, $mdUtil, $mdColorUtil) {
  this.$window    = $window;  // NPE (Null Pointer Exception) happening here!!!

Which comes from here:
return $injector.instantiate(InkRippleCtrl, {
      $scope:        scope,
      $element:      element,
      rippleOptions: options
    });

which calls this angular code:
function instantiate(Type, locals, serviceName) {
      // Check if Type is annotated and use just the given function at n-1 as parameter
      // e.g. someModule.factory('greeter', ['$window', function(renamed$window) {}]);
      var ctor = (isArray(Type) ? Type[Type.length - 1] : Type);
      var args = injectionArgs(Type, locals, serviceName);
      // Empty object at position 0 is ignored for invocation with `new`, but required.
      args.unshift(null);
      return new (Function.prototype.bind.apply(ctor, args))();
    }

I thought maybe it's some issue with
  Function.prototype.bind
but it's happening on a modern chrome browser, with userAgent:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"

Maybe that browser parses this:
new (Function.prototype.bind.apply(ctor, args))()
 as:
new ((Function.prototype.bind.apply(ctor, args))())
instead of the correct way:
(new (Function.prototype.bind.apply(ctor, args)))()

(That would cause the reported NPE because "this" is bound to null.)
I'll change angular and see if it's still happening...

**Comment by yoav-zibin** [comment]
Ignore what I wrote about:
new (Function.prototype.bind.apply(ctor, args))()

The minified version removed the last "()", so it's actually:
a.unshift(null);return new (Function.prototype.bind.apply(d,a))}

So there must be something else (maybe some weird behavior if you bind the this argument to null).
Really no clue :)

**Comment by yoav-zibin** [comment]
BTW, I have discovered already several problems because I have the source-mapping.
E.g., I discovered I need a polyfill for classlist (I support gingerbread: Android 2.3.6; de-de; GT-I8160P Build/GINGERBREAD),
and I also needed a polyfill for window.matchMedia.

Without source mapping, I get this exception, and I have no clue what's wrong:

TypeError: Cannot call method 'remove' of undefined
    at a.onIsOpenChanged (http://yoav-zibin.github.io/angular-material-with-sourceMappingURL/angular-material.min.js:8:523)

But now I can decode it:
TypeError: Cannot call method 'remove' of undefined
    at remove (angular-material.js:23162:28)

and see the code:

      $element[0].classList.remove('_md-open');

and it's trivial to figure out stuff :)


Anyway, closing this bug, but I hope I convinced you that source mapping are critical for 1.0 :)
