### ISSUE TITLE
md-tooltip: md-delay with md-autohide not working as expected

### ISSUE THREAD

**Issue by ajones-miovision** [angular/material#8363]
If you have md-autohide enabled on a tooltip that has a md-delay set, and you mouse over and off the object in less time then the delay period, then the tooltip will still show up (which it shouldn't) and will remain on (which it also shouldn't do). 

**Actual behavior**:
-  What is the issue? Tooltip displays and remains after the mouse leaves the object.
-  What is the expected behavior? Tooltip should not display because the mouse left the object before the delay period.

**Steps to reproduce the issue**:
-  Add a md-tooltip to a md-fab. Set md-delay and md-autohide (set delay to about 1000 to make this easier to demonstrate)
- Move your mouse over the fab and then off the fab in less time then the delay (ie <1000ms)
- The tooltip will show after the delay, and will remain until you mouse over again. This is new in 1.1. This worked on the previous version that I used (material 1.0.5).

**Angular Versions**: 
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: Chromuim
-  Browser Version: 49

**Comment by peio72** [comment]
+1

**Comment by BevanR** [comment]
A codepen would be really useful here.
