### ISSUE TITLE
DatePicker Week number and week select

### ISSUE THREAD

**Issue by marcfielding1** [angular/material#8364]
hey guys,

First off, I LOVE angular material, do you have any plans in order to display week numbers on the datepicker control, also a method for selecting a range within a week number would be handy ie Monday - Sunday.

I've just had to hack the angular UI bootstrap datepicker to do this, my suggestion would be create clickable week numbers and then have the control update a model (weekStartDay, weekEndDay) which a second datepicker to pay attention to?

Im actually tempted to fork/PR this feature myself but given I don't know the codebase and that it's pretty easy to implement I wondered if there was any motivation to do so?

Kind Regards

Marc

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by Splaktar** [comment]
Related to and more info at https://github.com/angular/material/issues/10003#issuecomment-364730323.
