### ISSUE TITLE
ScrollShrink demo on iOS minimizes the ToolBar when you scroll all the way to the top

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#8365]
**Actual behavior**:
-  What is the issue? *
Open:
https://material.angularjs.org/latest/demo/toolbar
with Chrome on an iPhone (I have an iPhone 6 plus),
go to the Scroll Shrink,
and then scroll UP (not down),
which will minimize the ToolBar (due to a bouncy effect on iOS).

See:
https://youtu.be/Bb4GxH30_i4

-  What is the expected behavior?
Scrolling UP should not shrink the ToolBar :)

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: Chrome on iOS 
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by yoav-zibin** [comment]
One of my students reported the same issue to me (so it's confirmed on several iOS devices, not just mine :))

https://youtu.be/UtIZncBTeyI

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
