### ISSUE TITLE
Problems with md-select label

### ISSUE THREAD

**Issue by douglasbgatti** [angular/material#8367]
I just upgraded the material design version from 0.11.4 to 1.0.8 and had to fix some problems in my application as expected. 
One of the problems I´ve been struggling to fix is the label for the md-select inside a md-input-container.

The problem occurs after I select a value then clear it.
I tried setting the ng-model value to null and undefined, but they both had the same behavior.

```HTML
<md-input-container flex layout-margin>
      <label>Situação</label>
      <md-select name="situacao" ng-model="model.filtersLancamentosAbertos.situacao" ng-change="listLancamentosAbertosByFilters()">
           <md-option ng-repeat="situacao in model.situacoesLancamento" value="{{situacao}}">
                    {{ :: situacao | translate }}
           </md-option>
       </md-select>
</md-input-container>
```

![bug_angular_sembug](https://cloud.githubusercontent.com/assets/8853095/15084767/12acf9ea-13ac-11e6-8e4d-e2eb2de7cd71.PNG)

![bug_angular](https://cloud.githubusercontent.com/assets/8853095/15084768/12ad2dde-13ac-11e6-82c9-d4b5ae12e421.PNG)

-  Details:

**Angular Versions**: *
-  Angular Version: 1.4.7
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.94 m

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by jayeshanandani** [comment]
Can you please try this in 1.1.0 - rc-4 of Angular Material?

**Comment by douglasbgatti** [comment]
I changed md version to 1.1.0-rc4 and it fixed my problem...thanks..although i am having other issues now with the $mdThemingProvider

**Comment by DaeyunKim** [comment]
I solve that <label>  change <md-select-label>.
