### ISSUE TITLE
md-content, ui-view, and scrolling

### ISSUE THREAD

**Issue by matthewjheaney** [angular/material#8370]
**Actual behavior**:
-  What is the issue? *

We have an md-content element bound to a ui-view.  The contents of the md-content element are basically a table.  This table can be many lines (e.g. 1000), so we also enable scrolling for this view.

The problem is that, given a certain viewpoint size, the size of the scroll bar thumb size not appropriate for the table content (specifically, then thumb is too long), such that we are unable to scroll all of the content.  There is content at the bottom that we cannot scroll to.

In our case, we have some navigation buttons on the last row of the table, that a user cannot reach by manipulating the scrollbar thumb.

-  What is the expected behavior?

There should be better synchronization between the viewport size and the content size, such that all of the content is reachable via scrollbar manipulation.

We can make this work by intercepting window resize events and manually changing the size of md-content element, but this feels like the wrong solution.  It seems like there is some interaction between AngularJS, the UI-router, and MD, such that the size of the content is not being reported correctly to MD, and so the size of the scrollbar thumb is incorrect.

**CodePen** or Steps to reproduce the issue: *

I work for Google, and reported this in internal bug #28274930 (under AngularJS).  That bug report includes the steps that demonstrate the issue.

-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *

v1.5

-  Angular Version:
-  Angular Material Version:

Whatever version of MD that is in our third_party repository.

**Additional Information**:
-  Browser Type: *

Chrome

-  Browser Version: *

v50

-  OS: *

GNU/Linux (Gubuntu)

-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by matthewjheaney** [comment]
You can close out this bug report if you like -- we found a work-around.

**Comment by topherfangio** [comment]
@matthewjheaney Thanks so much! Any chance you can share the workaround for future users?

**Comment by mackelito** [comment]
@matthewjheaney having a similar issue.. any chance that you will share your solution?
