### ISSUE TITLE
mdSticky and Subheaders - pin and unpin on wrong positions

### ISSUE THREAD

**Issue by zacol** [angular/material#8373]
**Actual behavior**:
Subheaders works well if section height is constant. If section height is dynamic (e.g. some elements inside section may be collapsible and expandable, section contain textarea and user type more then one line inside it, we resize window width and content inside section change size) subheaders doesn't update theirs positions.

In other way, if section height change after page load, subheaders use old positions. The results is that subheaders pin and unpin in wrong places.

**Steps to reproduce**
Open [official demo for subheaders](https://material.angularjs.org/latest/demo/subheader) with window width equal or bigger than 768px (at this moment everything should works well). After page load, change window width to 320px and now try to scroll content. For now, subheaders should pin and unpin on wrong positions (it still use the old positions).

**Angular Versions**: *
-  Angular Version: 1.5
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.86 (64-bit)
-  OS: All OS

**Comment by RolandHeath** [comment]
For anyone having trouble reproducing, I found that I had to scroll content a short way before changing the window width for this to work.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
