### ISSUE TITLE
md-datepicker breaks on manual entry

### ISSUE THREAD

**Issue by jaspersorrio** [angular/material#8374]
If you select 13 from the datepicker, everything will work.

However if you manually typed in 13, the component breaks.

Codepen here -> http://codepen.io/jaspersorrio/pen/zqeBYm?editors=101

**Comment by crisbeto** [comment]
You should override the `$mdDateLocaleProvider.parseDate` method in order to parse your custom formatting. [Take a look at the docs](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider).
