### ISSUE TITLE
Textareas do not autogrow in dialogs or sidenavs

### ISSUE THREAD

**Issue by haswellr** [angular/material#8376]
**Actual behavior**:
-  What is the issue? *Textareas do not autogrow when inside of dialogs or sidenavs. This seems to be because the textarea only watches for window resize events and keyboard press events - so as the dialog or sidenav animates and grows the textarea's size is not updated appropriately.
-  What is the expected behavior?
Textareas should always attempt to show the text within them unless a maximum number of rows is specified.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: To reproduce, create a page that opens a dialog. Within that dialog's HTML include a textarea that is pre-filled with text longer than one-line.

**Angular Versions**: *
-  Angular Version: 1.5.0
-  Angular Material Version: 1.0.7

**Additional Information**:
-  Browser Type: *Chrome
-  Browser Version: *50.0.2661.94 m
-  OS: *Windows 10 64-bit
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
Try adding the `md-detect-hidden` attribute to the textarea. It's not usually necessary, but it might help in this case.

**Comment by haswellr** [comment]
@crisbeto Thank you for that tip, that does seem to do the trick for dialogs. Textareas in dialogs with the 'md-detect-hidden' attribute function correctly, as far as I can tell.

However, this causes another issue in Sidenavs. Textareas autogrow, but they autogrow to a size far larger than they should be. I would guess this is because sidenavs animate and expand in width, so when the textarea is first shown the 'growTextarea' function fires but the textarea still has a very narrow width and it is set to have a high height to accommodate the text.

**Comment by crisbeto** [comment]
Yeah that's probably what's happening. Thing is that there's no good way of knowing whether the element is being animated, without making it dependent on other parts of Material.

**Comment by haswellr** [comment]
I know - it's a somewhat tricky issue. It unfortunately makes textareas almost unusable in sidenavs as the user experience is pretty confusing. As a temporary partial-fix I have textareas autogrowing on focus.

**Comment by crisbeto** [comment]
Another solution could be to either trigger another digest manually when the sidenav is opened, or using an `ng-if`/`ng-show` to delay the execution until the animation is done.

**Comment by ThomasBurleson** [comment]
@crisbeto 👍
