### ISSUE TITLE
an element within md-select is constantly running animation  

### ISSUE THREAD

**Issue by demsey2** [angular/material#8379]
an animation for svg element in md-select is constantly running, I am not sure if this is the best way to do it, it slows my app and many e2e tests are failing 

http://codepen.io/anon/pen/bpzaYQ?editors=1010

so if locate "md-progress-circular > svh > path" element you can see that path description is constantly changing,

it only happens when md-on-open is used

here is the patch I applied to my app, it hides the issue by removing that element

https://gist.github.com/demsey2/c5e13ec09aabf8ede39c52b8987d71e6

Angular Version: 1.5.5
Angular Material Version: 11.0.-rc4

Browser Type: Chrome
Browser Version: 50
OS: Win

**Comment by stunaz** [comment]
patch link leads to a 404

**Comment by demsey2** [comment]
url fixed, btw this is not a fix

**Comment by crisbeto** [comment]
It's because the `$$loadingAsyncDone` is undefined by default, which causes the `ng-if` to evaluate to `true`.
