### ISSUE TITLE
(feature) ability to create custom palettes asynchronously 

### ISSUE THREAD

**Issue by 0101adm** [angular/material#8380]
**Actual behavior**:
-  What is the issue?  the ability to set a theme's palettes to custom palettes after an XHR request would be appreciated.  right now, you can only set them at boot time.

**Comment by Splaktar** [comment]
I worked with @0101adm a bit in Gitter and tried a number of ways to get around this, but had no success. It would be helpful if some of what you tried could be detailed here along with the error messages. You could probably create a CodePen that captured this as well, without having to actually hit a real server.

**Comment by 0101adm** [comment]
@Splaktar 

my config block
```
$mdThemingProvider.generateThemesOnDemand(true);
$provide.value('themeProvider', $mdThemingProvider);
```

my service block, i build custom palettes and register with `themeProvider.definePalette` then assign (this is all in a promise block).
```
this._themeProvider.definePalette('customPrimary', _.find(palettes, { title: 'primary' }).hues);
this._themeProvider.definePalette('customAccent', _.find(palettes, { title: 'accent' }).hues);
this._themeProvider.definePalette('customWarn', _.find(palettes, { title: 'warn' }).hues);
this._themeProvider.definePalette('customBackground', _.find(palettes, { title: 'background' }).hues);

this._themeProvider
	.theme('default')
	.primaryPalette('customPrimary')
	.accentPalette('customAccent')
	.warnPalette('customWarn')
	.backgroundPalette('customBackground');
```

finally, i try to rebuild/refresh the theme.
```
this._$mdTheming.generateTheme('default');
this._themeProvider.setDefaultTheme('default');
```

**Comment by ThomasBurleson** [comment]
Will not fix in v1.x
