### ISSUE TITLE
zh_cn  date-picker BUG

### ISSUE THREAD

**Issue by 2947721120** [angular/material#8382]
zh_CN
![image](https://cloud.githubusercontent.com/assets/13098589/15113597/d052af26-1627-11e6-801e-1381314fb776.png)
This is the right way
![image](https://cloud.githubusercontent.com/assets/13098589/15113647/1f37f54c-1628-11e6-94cc-31ab695fed68.png)
http://cdn.c2cmalls.com/mdpickers/index.html

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
