### ISSUE TITLE
bug(autocomplete): text highlighting is broken for escaped characters

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#8388]
![image](https://cloud.githubusercontent.com/assets/571363/15123581/b7a8d3ce-15e1-11e6-9926-e6abaf7a3e10.png)

You can recreate this using the following CodePen:
http://codepen.io/anon/pen/zqeywG?editors=1010

### What's going on

The issue only occurs when your search includes a special character (ie. `<`, `>`, `&`).  It will break in one of two ways:

- When your search ends with `&`, it will be searching the actual HTML which looks like `Alabama &amp; something` in this case.  It will match the `&` in `&amp;` and the highlight `<span>` will split the special character, causing the results seen in the screenshot above.  
- When searching for other special characters, it will simply not highlight anything.

### Solution

We need to make sure that we are searching the `textContent` and not the `innerHTML` of the element.

**Comment by robertmesserle** [comment]
@ThomasBurleson Just wanted to bring this to your attention.  I can help out with this if needed.

**Comment by stunaz** [comment]
related to #8356

**Comment by robertmesserle** [comment]
@ThomasBurleson Looks like #8368 already fixes this issue.

**Comment by DevVersion** [comment]
This is fixed in `master` now :)
