### ISSUE TITLE
md-menu in a directive moves to window's upper-left corner on window resize

### ISSUE THREAD

**Issue by shp0** [angular/material#8390]
**Actual behavior**:
-  What is the issue? * md-menu in a directive template moves to window's upper-left corner on window resize
-  What is the expected behavior? md-menu should not change location on window resize.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: * Chrome
-  Browser Version: * 50.0.2661.94
-  OS: * Windows
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
