### ISSUE TITLE
md-autocomplete clear is incredibly slow

### ISSUE THREAD

**Issue by flick36** [angular/material#8391]
**Actual behavior**:
-  What is the issue?
  - When clearing the md-autocomplete or when not setting the autofocus it's increadibly slow to load the elements when they come from a promise, 
-  What is the expected behavior?
  - The items should load ways faster, cause if i delete with the backspace it works normally

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : Im working on a codepen demo, but for now some animations:

![Example](http://i.imgur.com/IdbOOJd.gif)
![Example](http://i.imgur.com/ljx5o1a.gif)
-  Details:

**Angular Versions**: *
-  Angular Version: **1.5.5**
-  Angular Material Version: **1.0.8**

**Additional Information**:
-  Browser Type: * **Desktop, tried on Vivaldi, Chrome, and Edge**
-  Browser Version: * **1.1.453.45, 50.0.2661.94, and 25.10586.0.0**
-  OS: * **Windows 10**
-  Stack Traces:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
