### ISSUE TITLE
mdDialog tab demo

### ISSUE THREAD

**Issue by bonatoc** [angular/material#8395]
**DEMO 1.0.5 - Shows only tab "one" upon opening**:
-  All 3 tabs should be present.

**CodePen** or Steps to reproduce the issue: *
-  http://codepen.io/bonatoc/pen/RadaqO
- Codepen identical to [online 1.0.5 demos
](https://material.angularjs.org/1.0.5/demo/dialog)

**Comment by rhclayto** [comment]
I have encountered the same problem when the md-tabs directive is inside a bootstrap tab that is not the active tab when the page is loaded. So it seems that md-tabs does not initialize all of the defined tabs if it's hidden when the page loads. Once you have clicked on the single md-tab that appears when you display the md-tabs group that was initially hidden, all the md-tabs appear.

**Comment by rhclayto** [comment]
Oddly enough, I found that in my case simply adding an ng-click attribute to the HTML `<a>` tag that opened the Bootstrap tab in which the `<md-tabs>` is hidden resolved the problem: e.g., `data-ng-click=""` .

**Comment by topherfangio** [comment]
This has been fixed in master as well as 1.0.8. Can you please try upgrading to one of those? If you still have the problem after upgrading, please post here and I will reopen.
