### ISSUE TITLE
[md-menu] size renders tiny when window resize

### ISSUE THREAD

**Issue by mpiasta-ca** [angular/material#8398]
**Actual behavior**:
*  What is the issue? 
    * md-menu renders really, really, really small upon opening (`transform: scale(0.11, 0.09);` is never cleared from `<div class="_md-open-menu-container...` when md-menu open animation completes).
*  What is the expected behavior? 
    * md-menu should render at normal size (`transform: scale(...)` should not be there).

**Plnkr** or Steps to reproduce the issue:
-  Plnkr Demo which shows your issue: https://plnkr.co/edit/WCFZRZ9OHmNxcoCifnn7?p=preview
-  Details:
    1. Open in Chrome/Android
    2. Put your cursor in the text field. Android keyboard will open on screen.
    3. Click md-menu icon to open the menu. Android keyboard will collapse (since input field blurred).
    4. Menu will open with really, really small dimensions (see note).

**Note:** might take several retries to make bug appear. In our production app it happens every time though, whenever device keyboard is closed by clicking md-menu. May be based on how the md-menu is resized based on surrounding content.

**Another way to reproduce the bug:**
1. On your desktop, open: https://embed.plnkr.co/WCFZRZ9OHmNxcoCifnn7/
2. Resize your browser window to be approx. the size of a mobile device.
3. Position your hand over Win+Right Arrow (on Windows, which is a hotkey to cause your browser to resize and lock to the monitor border), or use Mac hotkey alternatives.
4. Hold the Win key, click the md-menu icon [to cause the menu to open], and immediately press the arrow [to cause the window to resize as the md-menu animation is opening].
5. Should see that when your window resizes, the md-menu is tiny.

Of course, this would be an edge case in desktop browser. But this is effectively what is happening on a mobile device when user has an input field focused, the device keyboard is open, and then clicking the md-menu causes the keyboard to collapse [causing window to resize], while simultaneously opening the md-menu element. 

In our case, we use the md-menu as an input-group that appears beside the md-input field. The content in the md-menu supplements the md-input. So that's why the keyboard collapse is related to the md-menu opening.

**Bug Screenshots**:
* http://i.imgur.com/dxwKRpZ.jpg
* http://i.imgur.com/OceWI4c.jpg

**Angular Versions**:
-  Angular Version: 1.5.0
-  Angular Material Version: 1.0.8 and 1.1.0-RC4

**Additional Information**:
-  Browser Type: I've reproduced bug in all modern browsers
-  Browser Version: all
-  OS: all
-  Stack Traces: none

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
