### ISSUE TITLE
Unreachable code in function menuDefaultOptions (these lines comes after a "return" statement, so it can't be reached)

### ISSUE THREAD

**Issue by yoav-zibin** [angular/material#8399]
![unreachablecode](https://cloud.githubusercontent.com/assets/1890589/15161046/9b30e1c0-16ca-11e6-9cc3-7b8a4a42af32.png)

Code:
        return function cleanupInteraction() {
          element.removeClass('_md-clickable');
          if (opts.backdrop) opts.backdrop.off('click', onBackdropClick);
          opts.menuContentEl.off('keydown', onMenuKeyDown);
          opts.menuContentEl[0].removeEventListener('click', captureClickListener, true);
        };

        // Some helper functions, and then this code that can't be reached:

        opts.menuContentEl[0].addEventListener('click', captureClickListener, true);

        return function cleanupInteraction() {
          element.removeClass('_md-clickable');
          opts.menuContentEl.off('keydown');
          opts.menuContentEl[0].removeEventListener('click', captureClickListener, true);
        };

**Actual behavior**:
-  What is the issue? *
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Thanks for the issue. This is a known issue and a PR, which includes this fix is already pending #8117.
