### ISSUE TITLE
md-colors default theme

### ISSUE THREAD

**Issue by hodeyp** [angular/material#8407]
**Actual behavior**:
-  What is the issue? * md-colors uses the default theme as the [theme] which means if a component has an md-theme entry as well as an md-colors entry the md-colors is not using the correct md-theme
-  What is the expected behaviour? 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : 
-  Details:  http://codepen.io/anon/pen/pyYqJZ

```html
 <md-card flex md-theme="secondary" md-colors="{'background': 'background-800'}">
```

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: * all
-  Browser Version: * all
-  OS: * all
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EladBezalel** [comment]
@hodeyp hey can you provide a codepen?

Please have in mind that without a codepen this issue will be rejected

**Comment by hodeyp** [comment]
@EladBezalel I have added a codeine reference above, let me know if you need any more information.

**Comment by EladBezalel** [comment]
👍 for now you can use `secondary-primary-800`

**Comment by ThomasBurleson** [comment]
@hodeyp - great avatar!
