### ISSUE TITLE
md-datepicker ignoring required attribute on pristine input

### ISSUE THREAD

**Issue by astynax777** [angular/material#8411]
Codepen is here: http://codepen.io/astynax777/pen/ONqQOY

You'll notice that if you submit the form without first selecting and clearing a date, the validation does not fire on the md-datepicker.

I would like to know a workaround for this in the meantime.

AngularJS stack: 1.5.5
Material: 1.1.0-rc4

**Comment by astynax777** [comment]
Just saw this in the source:

**Comment by dohomi** [comment]
I just have seen this with `md-select` as well.

http://codepen.io/anon/pen/jqoEOG

Would be great to see a fix for this. On regular input it works as expected.
