### ISSUE TITLE
angular material design chip goes blank on pressing enter key/return key in ipad.

### ISSUE THREAD

**Issue by shyambhiogade** [angular/material#8415]
**angular material design chip goes blank on pressing enter key/return key in ipad.**:
-  angular material design chip goes blank on pressing enter key/return key in ipad?*
-  it should not go blank?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :http://codepen.io/shyambhiogade/pen/grEzQe?editors=1000
-  Details:
    access the url from ipad, and try to enter the chips, try for two three times, you will notice the chips are going blank

**Angular Versions**: *
-  Angular Version:1.4.8
-  Angular Material Version:https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.5/angular-material.js

**Additional Information**:
-  Browser Type: Safari and chrome in ipad
-  Browser Version: *latest
-  OS: *ipad os
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/shyambhiogade/pen/grEzQe?editors=1000).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Dunos** [comment]
I have the same bug, when pressing key/go button on iphone (tested with Chrome and Safari), the chips field (and anything around) goes blank.

Here some snapshots of the before/after:

![iphone-tags-normal](https://cloud.githubusercontent.com/assets/1147823/15391767/6f547ca6-1dc3-11e6-86d1-a99b3ebe9afd.jpg)
![iphone-tags-bug](https://cloud.githubusercontent.com/assets/1147823/15391770/7179cfa4-1dc3-11e6-805a-f5d762bac897.jpg)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by pgaubatz** [comment]
Hey @shyambhiogade and @Dunos, did you find a workaround for this issue yet?
It seems that this bug happens with version 1.1.1 too... :unamused: 

Cheers,
Patrick

**Comment by Dunos** [comment]
@pgaubatz Nope, still waiting (is not a primary issue for our platform but it's annoying :/)

**Comment by pgaubatz** [comment]
I've managed to create an absolutely minimal code example that triggers the bug on iOS: http://codepen.io/anon/pen/pEVLLg?editors=1000

My first observations:
- the bug is **not** triggered if the `placeholder` attribute is removed
- the bug is **not** triggered if the surrounding `<md-content>` is removed
- the bug is **not** triggered on material version **1.0.4** (note that the `placeholder` attribute doesn't work on 1.0.4 too...)

**Comment by pgaubatz** [comment]
Okay... Upon further investigation I found that this bug dates back to material version **0.9.0**!
Versions before **0.9.0** didn't support the `<md-chips>` directive...
