### ISSUE TITLE
feat(panel): add groupName config option

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#8424]
add and document `groupName` in [panel](https://github.com/angular/material/blob/464924075b5a68705f9b61dd561246904c8466a6/src/components/panel/panel.js#L152)

**Comment by EladBezalel** [comment]
@bradrich is that included in your work?

**Comment by ErinCoughlan** [comment]
Yes, this is part of that group work.

**Comment by bradrich** [comment]
Closing as this is a duplicate of #8971.
