### ISSUE TITLE
md-datepicker can't display hours-minutes-seconds

### ISSUE THREAD

**Issue by tipodisimmia** [angular/material#8430]
**Actual behavior**:
-  What is the issue? *
   md-datepicker can't display hours-minutes-seconds
-  What is the expected behavior? 
     I need to display a timestamp and modify it, i'd like to use  md-datepicker to do it, is it a use case in development?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
I'd say what you're describing is more of a timepicker, than a datepicker.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by Splaktar** [comment]
Duplicate of https://github.com/angular/material/issues/5029
