### ISSUE TITLE
mdCard: .md-subhead:only-child classes

### ISSUE THREAD

**Issue by tyrsensei** [angular/material#8431]
**Actual behavior**:
-  What is the issue?

With only md-card-title-text in md-card-title component, a .md-subhead tag is always styled as if it had no sibling
-  What is the expected behavior?

When with another sibling, the .md-subhead should be small, grey and have no padding-top applied

**Steps to reproduce the issue:**
-  See the "Card with image - Extra Large" on [documentation](https://material.angularjs.org/latest/demo/card). The subhead is black and lower than expected to be.

![image](https://cloud.githubusercontent.com/assets/4330776/15211069/9422da1c-1839-11e6-8c07-49741a54c832.png)

**Angular Versions**:
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.94 m
-  OS: Win7

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
