### ISSUE TITLE
  Datepickers with different $mdDateLocaleProvider.formatDate

### ISSUE THREAD

**Issue by rafaelhc** [angular/material#8435]
I have formatted the md-datepicker to display the week number when a date has been selected: 

`$mdDateLocaleProvider.formatDate = function(date) {
    var injector = angular.injector(['ng']),
    $filter = injector.get('$filter');
    var currWeek;
    if (date === undefined) {
      date =  new Date();
    }
    var currWeek = 'Week ' + $filter('date')(date, 'ww');
    return currWeek;
  };
});`

The problem now is that all of the datepickers display the week number, but I want to select which acts like the default one, and which one that uses my formatted version. Is this possible?

**Comment by crisbeto** [comment]
No, all datepickers use the formatter that was defined on config.

**Comment by rafaelhc** [comment]
So no possibility to insert a variable in the datepicker, like:

`<md-datepicker **showWeek** md-placeholder="Select date"></md-datepicker>`

or select it using ng-click or the like?

**Comment by crisbeto** [comment]
No. [You can check the docs to see what's available](https://material.angularjs.org/latest/api/directive/mdDatepicker).

**Comment by rafaelhc** [comment]
d

**Comment by rafaelhc** [comment]
I made a temporary fix to this issue.

In angular-material.js: 
Inside `function DatePickerCtrl`, underneath `this.$element = $element;` I added `$scope.$classNameDP = $element.attr('class');`

Inside `DatePickerCtrl.prototype.configureNgModel` I changed:
`self.inputElement.value = self.dateLocale.formatDate(value, self.$scope.$classNameDP);`

Inside `DatePickerCtrl.prototype.attachChangeListeners ` I changed:
self.inputElement.value = self.dateLocale.formatDate(date, self.$scope.$classNameDP);

In my app.js:

`app.config(function($mdDateLocaleProvider) {

  // Show the week number after selection
  $mdDateLocaleProvider.formatDate = function(date, classNames) {
    var dateFormat;

    if(classNames.indexOf("dateWeek") != -1) {
      return dateFormat = 'Week' + moment(date).week();
    } else {
      return dateFormat = moment(date).format('DD.MM.YYYY');
    }
  };
});`

In my html I added the class "dateWeek" to the datepickers with this wanted functionality:

`<md-datepicker class="dateWeek" ng-model="model" md-placeholder="Choose date"></md-datepicker>`
