### ISSUE TITLE
md-select inside md-menu doesn't work

### ISSUE THREAD

**Issue by xsegrity** [angular/material#8437]
I have an md-menu with a couple of md-select inside. There are several issues that keep this from working properly. Any workaround would greatly be appreciated because my requirements specify that I need a menu rather than a dialog.

1. md-select z-index order is 90 and md-menu z-index is 100 so the select container opens behind the menu. This is easy enough to work around with a css override.

1. Clicking outside of the md-select when it is open actually closes the md-menu and not the md-select. Clicking outside after the md-menu is closed then closes the md-select (wrong order).

1. Clicking a second md-select when the first md-select is open does close the first one and open the second one as expected but clicking any other control type inside the md-menu does not close the md-select.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/GZebVj
-  Details: Click the 'Open Menu' to see an example. z-index css is commented out by default.

**Angular Versions**: *
-  Angular Version: 1.5.0
-  Angular Material Version: 1.0.7+

**Comment by HaakonH** [comment]
Did you figure this out? I'm having the same issue with md-select in modal window.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by cstephe** [comment]
Just a comment,  I don't think md menu is meant to be used that way.  I have the same issue and it would be very convenient if it did.  I'm going for a custom mdpanel instead.
