### ISSUE TITLE
Sidenav right triggers horizontal scrollbar during animation

### ISSUE THREAD

**Issue by aeby** [angular/material#8439]
**Actual behavior**:
-  What is the issue? During the fade-in and fade-out animation of the sidenav right the body overflows and shows the horizontal scrollbar. The parent of the sidenav gets the style `overflow: hidden` but this does strangely not prevent the scrolling as it does for the left sidenav.
-  What is the expected behavior? No scrollbar during animation

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/qZveKN
-  Details: Click button "Toggle right"

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.94 (64-bit)
-  OS: Linux (Ubuntu)
-  Stack Traces:

**Comment by char0n** [comment]
I can confirm. Here is my codepen: http://codepen.io/anon/pen/wGLGXY

**Angular Versions**
Angular=1.5.5
AngularMaterial=https://github.com/angular/bower-material/archive/v1.0.8-master-05a3a0f.tar.gz

**Additional Information:**
All browsers affected, even Chrome Mobile

**Comment by qia0756** [comment]
Same issue.Safari and Chrome on Mac OS is normal ,but Chrome on Windows occur this.

**Angular Versions:** 

Angular Version: 1.5.5
Angular Material Version: 1.0.9

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by mlenser** [comment]
FYI this can be fixed by adding the following on the container:
overflow-x: hidden;

**Comment by enricop89** [comment]
@mlenser Can you provide a codepen that solve the issue? If i set overflow-x: hidden on the codepen above, the problem still remains.

**Comment by ThomasBurleson** [comment]
```html
<div ng-controller="AppCtrl" layout="column" style="height:500px; overflow-x:hidden;" ng-cloak="" class="sidenavdemoBasicUsage" ng-app="MyApp">
```
