### ISSUE TITLE
tabindex does not work with md-select on ios devices

### ISSUE THREAD

**Issue by cjardmore** [angular/material#8440]
**Actual behavior**:  When ios keyboard is open, many users will use the 'up/down arrows' to tab between different fields on the form.

-  What is the issue? *  The ios keyboard arrow keys (when toggling between form elements does not recognize md-select (perhaps other material elements as well that do not contain native HTML elements under the covers), and so when a user is toggling between form fields on an ios device using these buttons, the select fields will be skipped.

-  What is the expected behavior?  When the user toggles between form elements using the up/down arrow keys on the ios keyboard the md-select elements will focus when they're the next field in the form.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :  https://codepen.io/cjardmore/pen/PNLMaQ
-  Details:  Tabbing through the form fields using the arrow keys on the ios keyboard will skip the md-select element

**Angular Versions**:
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: Safari
-  Browser Version: n/a
-  OS: ios 9.3.1
-  Stack Traces: n/a

--------------------------------

What I originally tried was to detect the key* events so I could hook into this 'tabbing' process and force the keys to behave as a user would expect.  But it appears ios keyboard does not fire the key* events when these arrow buttons are pressed.  What I've done as a work around for the time being is degrade ios from 'md-select' element to native 'select' element.

**Comment by DevVersion** [comment]
@cjardmore Yes, can reproduce the issue. 

I was looking how the iteration works here for iOS, but it seems like Safari only checks for native elements.

A fix for that issue can be only done, by creating a fake input, which is visually hidden and focuses the select on focus.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
