### ISSUE TITLE
(css): style density for tighter spacing on desktop

### ISSUE THREAD

**Issue by joshcaplin** [angular/material#8441]
**Actual behavior**:
-  What is the issue? The default styling, spacing, etc seems to be slightly too spaced out for a desktop app, especially one which might have a lot of content to display on the screen.  
-  What is the expected behavior?  Would it be possible to have a global flag that users could opt into that decides the spacing?  Maybe "expanded", "normal", "condensed" and developers could choose the appropriate setting based on the look they're going after, and the amount of content they need to show on the screen.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:  some examples:
<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Select dropdowns take up more space than necessary on a desktop
<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Toolbars are big, and there's even an md-tall class to make them bigger, but nothing to make them shorter.
<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Datepicker is pretty big on a desktop

**Angular Versions**: *
-  Angular Version: 1.4.7
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Chrome 
-  Browser Version: 50.0
-  OS: Windows 7
-  Stack Traces:  n/a

 I realize this likely isn't at the top of the priority list, just wanted to throw it out there as a possible improvement.  Thanks!

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
