### ISSUE TITLE
On mobile, 2 clicks are needed to "focus" input or button in $mdDialog.

### ISSUE THREAD

**Issue by sandronm** [angular/material#8443]
Hello!

This issue is hard to explain but easy to see **if you follow exactly the steps to reproduce it**.

This issue exists **only with mobile devices** and also with **Google Chrome with mobile device mode actived before visiting the url of the demo** (to switch on mobile device mode, open Dev tools and click on the icon on top-left or Ctrl + Shift + M)

The issue happens only when you mix a md-button with directives from https://github.com/danialfarid/ng-file-upload
`<md-button class="md-primary md-raised" aria-label="Upload picture" ngf-select="vm.openDialog()" ngf-multiple="false" accept="image/*">Input image</md-button>`

The demo is available here: https://www.kod-it.be/angular-material-bug/
You can download the sources here: https://www.kod-it.be/angular-material-bug/sources.zip

1) Click on the button "Input image"
2) Choose a picture from your mobile/computer.
3) The dialog is opened

Try to click on the input or directly on the "Hide" button. Nothing happens... but if you click a second time, no problem.

This issue doesn't exist if you click on the button "Simply open dialog" because the md-button is not mixed with directives from ng-file-upload.

Any suggestion?

**Comment by graphefruit** [comment]
Try to add `mdGestureProvider.skipClickHijack();` in the app config.
I had the problem when I was not pressing directly on the text, rather on the border.

**Comment by sandronm** [comment]
Adding mdGestureProvider.skipClickHijack() resolves the issue... but certainly also creates other ones for "old" browser.

But already thank you!

**Comment by graphefruit** [comment]
Maybe try to wait DevVersion has polished the event-handler and if the pull-requests gets accepted there should be no need anymore for the `skipClickHijack`.

After I had many problems myself, try to evaluate that no CSS file is crashing the behavior (had this myself).

Also Fastclick can be embedded maybe this fixes some problems aswell.
Greetings

**Comment by DevVersion** [comment]
Just to reference the PR - #8322
