### ISSUE TITLE
Using ui-router inside a mdDialog

### ISSUE THREAD

**Issue by brenolf** [angular/material#8444]
**Actual behavior**:
-  What is the issue? When using `mdDialog` with `ui.router` I am not able to open the correct templates inside the modal itself. It opens the root route inside the modal (so I have the root page A opened in background and page A also opened inside the modal itself).
-  What is the expected behavior? I want to call `.show` once and then be able to swap the templates *inside* the modal by changing routes using `ui.router`. So if I have a route `/x` for opening the modal and routes `/x/a` and `/x/b` that are different templates, I want that changing to `a` or `b` simply changes the modal contents without any reload. 

**CodePen** or Steps to reproduce the issue: *
-  Details: Simply set a modal template to be a `<ui-view/>` and then access any sub-routes of the modal route.

**Angular Versions**: *
-  Angular Version: `1.5.5`
-  Angular Material Version: `1.0.7`

**Additional Information**:
-  Browser Type: Google Chrome
-  Browser Version: 50.0.2661.94 (64-bit)
-  OS: OS X 10.10.2 (14C109)

**Comment by ThomasBurleson** [comment]
@brenolf - please provide a CodePen.

**Comment by ThomasBurleson** [comment]
Invalid issue without CodePen. Closing.

**Comment by simonered** [comment]
+1
