### ISSUE TITLE
md-autocomplete does not select the desired item when it is fully typed in the input

### ISSUE THREAD

**Issue by seansean11** [angular/material#8445]
**Actual behavior**:
-  What is the issue? *
Typing the full name of an option in the md-autocomplete box does not select an item, it only narrows your option down to that one item.  You then need to click on the item in the dropdown for it to be considered 'selected'.  I have seen users struggle with this in user testing.
<img width="963" alt="screen shot 2016-05-12 at 3 05 34 pm" src="https://cloud.githubusercontent.com/assets/2547722/15230723/6cd0cde6-1854-11e6-8806-df53c100f44d.png">

-  What is the expected behavior?
Typing the full name of an option and pressing enter/tab or focusing away from the input should select the item in the list that was typed in full.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/seansean11/pen/EKJjXW
-  Details: This behavior can be seen in the standard md-autocomplete example.

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: * Chrome
-  Browser Version: * 50.0.2661.94 (64-bit)
-  OS: * OSX 10.11.4
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
The attribute `md-select-on-match` may help in your issue. 
- https://material.angularjs.org/HEAD/api/directive/mdAutocomplete

**Comment by seansean11** [comment]
Thank you for the response.  Can't believe I missed that attribute.
