### ISSUE TITLE
Enhancement: Support $mdCloseMenu

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#8446]
We can open a menu using:

**ng-mouseover="$mdOpenMenu($event)"**

but it would be great if something like mdCloseMenu was also supported:

**ng-mouseleave="$mdCloseMenu($event)"**

**Comment by mackelito** [comment]
What´s the status on this?
Will we have a $mdOpenMenu() or .close() feature? :)

**Comment by crisbeto** [comment]
There's https://github.com/angular/material/pull/9193 which has been pending for a while. I'm not too sure when it'll be released.
