### ISSUE TITLE
fix(datePicker): change classList.add to classList.toggle

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#8451]
[Change classList.add to classList.toggle](https://github.com/angular/material/blob/master/src/components/datepicker/datePicker.js#L401) when we stop using PhantomJS in unit tests because it doesn't conform to the DOMTokenList spec.
See https://github.com/ariya/phantomjs/issues/12782.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
