### ISSUE TITLE
fix(datePicker): add md-datepicker to bodyClick

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#8452]
`md-datepicker` itself should be added to [`handleBodyClick` check](https://github.com/angular/material/blob/master/src/components/datepicker/datePicker.js#L622)

**Comment by crisbeto** [comment]
It doesn't make sense to check for the datepicker since the calendar pane isn't a child of it. I've still simplified this a little by checking whether the click occurred inside the calendar (as opposed to the month or year).
