### ISSUE TITLE
<md-autocomplete> doest work properly with ng-bind inside  <md-item-template>

### ISSUE THREAD

**Issue by franciscotln** [angular/material#8457]
`md-autocomplete.flex(md-items='subchapter in getSubchapterMatches(subchapterText)',
    md-selected-item='job.subchapter', md-search-text='subchapterText', required,
    md-item-text='subchapter.pair_number', md-floating-label='Subchapter')
  md-item-template
    span(md-highlight-text='subchapterText') {{ subchapter.pair_number }}`

If I use `span(md-highlight-text='subchapterText', ng-bind='subchapter.pair_number')` it shows an empty list with the matched items.

**Comment by DevVersion** [comment]
@franciscotln Thanks for the issue. It would be great if you provide a demo.

**Comment by franciscotln** [comment]
I shot a small video so you can see. The code is exactly the same as this one above using the ng-bind directive. [check it here](http://screencast.com/t/plThZzFSYZ)

**Comment by ThomasBurleson** [comment]
Invalid issue without CodePen. Closing.

**Comment by patrickmichalina** [comment]
I can confirm ng-bind does not work correctly when used inside this directive.

**Comment by ThomasBurleson** [comment]
@patrickmichalina - codepen plz.

**Comment by blenderer** [comment]
@ThomasBurleson 
@DevVersion 

http://codepen.io/blenderer/pen/RoLGeN
Created a codepen, I was experiencing the same problems

**Comment by xeroxoid** [comment]
Same here. When using md-highlight-text with ng-bind, the while bound value is not rendered.

**Comment by albertpeiro** [comment]
I experience this issue with Angular material 1.1.4
