### ISSUE TITLE
$scope problem with md-dialog 

### ISSUE THREAD

**Issue by jainshravan123** [angular/material#8459]
I have four files. I need to show a dialog box and data is populating inside dialog box from it's own controller. 

1. home.html           -   contains a button(data will pass via ng-click on press of this button)  and script for dialog view
2. HomeController   -   contains a function which gets the data from home.html and opens a dialog box
3. DialogController  -   contains the data to populate in Dialog box via DialogService
4. DialogService     -  contains getter and setter for data

# The Problem is that data is not loading inside dialog box title (blog_title)
Please help me to fix this issue.
<img width="736" alt="screen shot 2016-05-15 at 5 40 11 am" src="https://cloud.githubusercontent.com/assets/6860473/15271293/c20bc4de-1a5f-11e6-8964-a6c0fde95d7c.png">
<img width="682" alt="screen shot 2016-05-15 at 5 40 24 am" src="https://cloud.githubusercontent.com/assets/6860473/15271294/c26c21d0-1a5f-11e6-8c72-c53b74549839.png">
<img width="807" alt="screen shot 2016-05-15 at 5 40 37 am" src="https://cloud.githubusercontent.com/assets/6860473/15271295/c270a71e-1a5f-11e6-886f-8a2db09f868b.png">
<img width="617" alt="screen shot 2016-05-15 at 5 40 50 am" src="https://cloud.githubusercontent.com/assets/6860473/15271296/c270c8fc-1a5f-11e6-8378-e060480822f0.png">

**Comment by jainshravan123** [comment]
Please help me guys to fix this issue.
Please... please..please

**Comment by graphefruit** [comment]
@jainshravan123 Tbh, this sultions looks realy ugly what you're trying to achieve.
You should move this question to *stackoverflow* and do a realy code-sample within *codeplex*.
I've posted you my sample which I'm using.
````
return $mdDialog.show({
            templateUrl: '...',
            parent: angular.element(document.body),
            clickOutsideToClose: false,
            controller: function YourController(BlogsService) {
             $scope.blog_title ="test title";
             //$scope.blog_title = BlogsService.getCurrentBlog()
           } 
});

**Comment by ThomasBurleson** [comment]
@jainshravan123 - convert your screenshots into a CodePen and we can try to help.

**Comment by ThomasBurleson** [comment]
Invalid issue without CodePen. Closing.
