### ISSUE TITLE
FAB Speed Dial IE 10 always opens down

### ISSUE THREAD

**Issue by dborinsk** [angular/material#8460]
http://codepen.io/dborinsk/pen/mPgQdv
works fine on chrome and IE 11 but not on IE10
any suggestions?
Thanks!

**Comment by david-gang** [comment]
Hi,
ie10 is not supported. https://groups.google.com/forum/#!searchin/ngmaterial/ie10/ngmaterial/U-gmDd5_jq8/0N6jovrYDAAJ

BR,
David

**Comment by topherfangio** [comment]
@dborinsk IE10 does not fully support the flexbox standard which this component uses to position the FAB actions.

We are planning a rewrite which will use a different positioning scheme which may make it more backwards-compatible with older browsers, but I can't make any guarantees.
