### ISSUE TITLE
IE - Dialog height shrinks but does not grow back when resizing window height

### ISSUE THREAD

**Issue by david-pe** [angular/material#8461]
**Actual behavior**:
-  What is the issue? The Dialog shrinks when condensing window but __does not grow__ when expanding back the window.
-  What is the expected behavior? The Dialog should grow to 80% of window height

**CodePen** or Steps to reproduce the issue: *
-  Details: 
1. Using IE open a Custom Dialog  [Angular Material Demo](https://material.angularjs.org/latest/demo/dialog) site
2. Reduce the window height
3. Maximize the window
View here - http://screencast.com/t/CSyHTOy2x8uo

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: IE 
-  Browser Version: All recent versions
-  OS: Win
http://codepen.io/team/AngularMaterial/pen/bEGJdd

**Comment by david-pe** [comment]
@ThomasBurleson why the deprecation?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
