### ISSUE TITLE
Ng-cloak while angular-material is used doesn't work as expected

### ISSUE THREAD

**Issue by otterslide** [angular/material#8462]
**Actual behavior**:
-  What is the issue? *
When "ng-cloak" is added to a DOM element, the ng-model tags no longer receive their value.

-  What is the expected behavior?
ng-cloak should not affect any values.

**CodePen** or Steps to reproduce the issue: *

http://codepen.io/otterslide/pen/JXVxRb
remove the ng-material dependency, and the second number will show up fine.

-  Details:

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version:1.0.7

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102 m
-  OS: Windows

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
It works if you use this: 

```js
app.controller('Testcontrol', ["$scope", "$attrs", "$element", "$window", 
function($scope, $attrs, $element, $window) {    
  $scope.x = 50;
}]);
```

This implies that `ng-cloak` is interfering with  `$($element).width()`; which is expected since 

```css
[ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
  display: none !important;
}
```

Will not fix.

**Comment by otterslide** [comment]
Any ideas why it works without 'ngMaterial' ? Just lucky?  I have many other plugins.. none of them stop it from working..
