### ISSUE TITLE
Use ngLocale for firstDayOfWeek in DateLocaleProvider

### ISSUE THREAD

**Issue by devimplode** [angular/material#8471]
Currently we have to manually overwrite $mdDateLocaleProvider.firstDayOfWeek
This property could also directly used from ngLocale:
`firstDayOfWeek: this.firstDayOfWeek || ($locale.DATETIME_FORMATS.FIRSTDAYOFWEEK == 6 ? 0 : $locale.DATETIME_FORMATS.FIRSTDAYOFWEEK +1) || 0`
https://github.com/angular/material/blob/master/src/components/datepicker/dateLocaleProvider.js#L260
Mind that ngLocale is based with 0 for Monday and material with Sunday.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
