### ISSUE TITLE
Update documentation for $mdColors

### ISSUE THREAD

**Issue by sdesmond** [angular/material#8473]
Looks like $mdColors.applyThemeColors now needs 3 arguments (including a scope for interpolated values).  The documentation still shows only 2.

Also, the only way I can get it to work is to pass the colorExpression as a string, not as an expression.  Is all this expected?  If so, can you make sure to update the docs before 1.1 officially hits?

Also, was there any thought of having the scope as the last parameter and making it optional?

This does not work anymore.
`$mdColors.applyThemeColors(angular.element('#idHere'), {color: 'warn'});`

This seems to work now.
`$mdColors.applyThemeColors(angular.element('#idHere'), $scope, "{color: 'warn'}");`

**Comment by EladBezalel** [comment]
@sdesmond docs are already updated, but i do agree the the scope can be the last parameter
