### ISSUE TITLE
md-chips md-max-chips validity

### ISSUE THREAD

**Issue by pylejowdmn** [angular/material#8476]
**Actual behavior**:
-  What is the issue? *
when a user enters the max amount of chips permitted the form immediately becomes invalid
-  What is the expected behavior?
Hitting the max chips should stop further entry but should not invalidate the form.  The form should become invalid if somehow the max amount of chips were exceeded.  If you set the statusList to have 11 entries the form stays valid.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
http://codepen.io/Joshuatpyle/pen/xVNVoX
-  Details:
Add a 10th entry and the form will be marked invalid.  change the js to start with 10 entries and the form is valid until you remove and then add a 10th entry.  change the js to have 11 entries and form is still valid when initially loaded.

**Angular Versions**: *
-  Angular Version:
1.5.5
-  Angular Material Version:
1.0.8 (code pen is with 1.0.7 - could not find a google api link for 1.0.8) 

**Additional Information**:
-  Browser Type: *
Chrome
-  Browser Version: *
50.0.2661.102 m

-  OS: *
Windows 7
-  Stack Traces:
N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
The issue here is one of UX. What should happen when the max-chips is reached. A *silent* blocking of more chips is not intuitive. Some UX is needed to notify the user that the max limit has been reached. Perhaps ngMessages is a solution?

**Comment by pylejowdmn** [comment]
Good point, but the problem is that if you use the md-chips in a form hitting the max invalidates the form.  But the max is not "invalid" exceeding the max would be, but not hitting the max. if the max is set to 10 I should be able to safely add 10 chips without invalidating the form.

**Comment by DevVersion** [comment]
@pylejowdmn You're right - this may be also a good use-case. 
- It seems like, there are two different requests. 

Showing the validity, once the maximum is exceeded, doesn't make any sense. The ngMessage will never show up.

**Comment by moJiXiang** [comment]
I found that md-chips doesn't support valid compeletly.
So I manualy add a function named `checkValidate` to check the length of ng-model value, the function bind to `md-on-add` trigger of `md-chips`.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
