### ISSUE TITLE
date picker does not support "DD/MM/YYYY" Format using input

### ISSUE THREAD

**Issue by ypwu1** [angular/material#8477]
**Actual behavior**: * 
-  What is the issue? *
date picker does not support "DD/MM/YYYY" Format using input, only support by using calendar
-  What is the expected behavior?
date picker should allow user enter date '25/11/2016'  by using text input

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/owu/pen/bpyqBR
-  Details:
   pick  "17/02/2016" from calendar is fine, but use input to enter "17/02/2016" is invalid

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ypwu1** [comment]
In the sample code, I did use $mdDateLocaleProvider to define the date format.

**Comment by crisbeto** [comment]
Apart from `formatDate`, you're also supposed to override the `parseDate` method in order to validate yours custom formatting. [Check the docs.](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider)
