### ISSUE TITLE
md-select key handling problem

### ISSUE THREAD

**Issue by androidfreakers** [angular/material#8478]
I have use case like: i want to control md-select with key board and i have only arrow-keys and enter.
With current implementation of md-select if focus goes to md-select then i can not move to other control like "md-button" using up-down keys. 
Is there any way to overwrite the hey-handling without modifying the source code?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
