### ISSUE TITLE
md-autocomplete: Fifth option gets hidden when deleting text

### ISSUE THREAD

**Issue by ianstigator** [angular/material#8485]
**Actual behavior**
- The 5th option gets hidden when deleting the text
- Expected behavior: Number of displayed options should be consistent.

**CodePen** 
-  See http://codepen.io/enkindel/pen/aNrawM
-  This is same as the Autocomplete demo

**Steps**
1. Click on the autocomplete field and verify that you have 5 options to begin with.
2. Type anything on the input field such as "text".
3. Press backspace until there is a match and the dropdown displays. You can also highlight the whole text and press Delete/Backspace.
4. Verify that the number of options is now only 4.

**Angular Versions**: 
-  Angular Version: 1.5
-  Angular Material Version: 1.0.5

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50
-  OS: Win 10

**Comment by DevVersion** [comment]
This is fixed in `master` with SHA 7e5be01aa9e4cf2fe2f91d1f1673ce592831b517
