### ISSUE TITLE
md-fab-toolbar closes on click outside

### ISSUE THREAD

**Issue by Nosthertus** [angular/material#8486]
I don't find an option to keep the toolbar open, it would be more useful if there was a property named like "clickOutsideToClose" just for the cases on which it needs to stay open.

I have an element which uses the same property as `md-fab-toolbar` to be visible, and it's why i come up with this issue

**Comment by DevVersion** [comment]
I think that's a reasonable feature request. 

Ping @topherfangio

**Comment by topherfangio** [comment]
@DevVersion This seems almost identical to #4973, the `md-is-locked-open` attribute we have previously discussed.

@Nosthertus Can you take a quick read of that one and see if it would meet your needs?

**Comment by Nosthertus** [comment]
@topherfangio yes, it looks like it was already discussed and still under development

**Comment by topherfangio** [comment]
@Nosthertus Awesome, thanks for the feedback! I'm going to go ahead and close this issue in favor of that one. Please post any additional comments to that thread.
