### ISSUE TITLE
Angular Material Rich Text Editor

### ISSUE THREAD

**Issue by mohsinmuzawar** [angular/material#8487]
**Wanted to ask whether there is going to be a rich text editor which will be added to angular material**
Some thing like  [summernote](http://summernote.org/)

**Comment by kskoropada** [comment]
+1

**Comment by ThomasBurleson** [comment]
A pull request would be welcome. And we will contact the SummerNote author to see if he would be interested in making an Angular Material native version.

@topherfangio  - FYI.

**Comment by timbrown81** [comment]
There are several rich text editors available, all with their own benefits and disadvantages.  No single editor will be the best for every problem.  I think this is best left to the individual architect to chose the right editor for their situation.

**Comment by mbarakaja** [comment]
There is an official angular directive for [summernote](https://github.com/summernote/angular-summernote) already, maybe is a good option to start.

**Comment by ThomasBurleson** [comment]
I should also add that an Angular Material-native RichText Editor would be best added to an extension library (eg `angular-material.extensions.js`) and should not be published as a core component in (`angular-material.js`).

**Comment by kpgarrod** [comment]
ngWig would be a good fit for my project because it has no dependency on JQuery or twitter-bootstrap as Summernote does. Unfortunately it has [compatibility issues with angular-material](https://github.com/stevermeister/ngWig/issues/113). While I agree with @timbrown81that different editors will suit different projects, it would be good to have a choice of editors that actually work with angular-material. I have been finding that a challenge.

**Comment by stevermeister** [comment]
@kpgarrod 
it's not compatibility issues of ngWig itself, but it looks like it's compatibility issue of angular-material with contenteditable fields on mobile devices. 

would like to see answer on this https://github.com/angular/material/issues/8593

**Comment by timbrown81** [comment]
I have been experimenting with several different rich text editors for my project on Angular Material.  In doing so, I've taken made CodePens for 5 different WSYWSG editors.  So far I am leaning towards Froala simply because it's native look and feel is implemented with Material Design.  Disadvantage is that it requires JQuery.  So I am also looking at CKEditor, it will take some skinning to follow MD, but has no dependencies and has a rich ecosystem of plugins.

Let me know if there are any other editors you'd like to have my include. 
[Angular Material WYSWYG Editors](http://codepen.io/collection/DLepkM/ )

**Comment by stunaz** [comment]
What about http://textangular.com?

**Comment by kpgarrod** [comment]
Certainly ngWig. Once the bug is fixed in a-m I think it will be ideal.

On Tue, 31 May 2016, 19:47 stunaz <notifications@github.com> wrote:

> What about http://textangular.com?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/material/issues/8487#issuecomment-222765370>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACDjkY-MABRz7OkeovOb61RJnJJA6maiks5qHHQsgaJpZM4Ig_Gg>
> .
>
-- 
Keith Garrod
Phone +356 2156 9774
Mobile +356 9958 6774

**Comment by stevermeister** [comment]
@timbrown81 
it would be nice if you could add ngWig (http://ng-wig.js.org/) into your list as well

**Comment by timbrown81** [comment]
> On Tue, 31 May 2016, 19:47 stunaz ***@***.***> wrote:
>  What about http://textangular.com?

@stunaz Here is textAngular: http://codepen.io/timbrown81/pen/JKoGMr

**Comment by timbrown81** [comment]
@stevermeister  @kpgarrod 

Here is ngWig: http://codepen.io/timbrown81/pen/QEwQqd

**Comment by timbrown81** [comment]
And here is Medium using angular-medium-editor  http://codepen.io/timbrown81/pen/xObYeB

**Comment by stevermeister** [comment]
@timbrown81 great thx! 
forward my blog audience to your list ;)

**Comment by stunaz** [comment]
@timbrown81 not sure to understand what your pens do.
Is there any new material component (subject to be in future angular-material.extensions) ?

Seems to me that you just included external lib, so nothing new.

**Comment by kpgarrod** [comment]
@timbrown81 Just to be clear, I understand that all of these editors suffer from the same angular-material bug (#5937) on mobile devices. IS that right?

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by victordelacruz** [comment]
I'm surprised that *Quill* isn't mentioned here. It looks awesome and more in line with Angular Material philosophy than *summernote*.

Also, it doesn't have any external dependencies on Bootstrap or Jquery: http://quilljs.com/

**Comment by jessicamrbr** [comment]
I used a combination of TinyMCE and sample editor in docs, it worked very well.

![localhost-3000-auxs-appointmenttemplates iphone 6](https://cloud.githubusercontent.com/assets/18180548/22737301/a9f87a32-ede9-11e6-9e83-9b2f6398a3fb.png)

**Comment by demiro** [comment]
hm... anything for angular and not angularJS?

**Comment by henrymana** [comment]
I use quilljs (but still with angularjs...) It looks like there is at least one wrapper for angular versions > 2... not sure it if is any good... https://github.com/KillerCodeMonkey/ngx-quill

**Comment by chych** [comment]
I just discover https://github.com/Sibiraj-S/ngx-editor
works on my project (angular v4)

**Comment by stevermeister** [comment]
updated [ngx-wig](https://github.com/stevermeister/ngx-wig) that should work for both Angular 4 and Angular 5
