### ISSUE TITLE
md-select multiple overflows

### ISSUE THREAD

**Issue by WeFknRise** [angular/material#8488]
I have a `md-select` element with the multiple attribute. When I open the `md-select` the box overflows the `md-input-container` it’s in. As you can see in the screenshot below this looks very strange.

![multiple](https://cloud.githubusercontent.com/assets/7645056/15354321/4d89a9ec-1ced-11e6-9ceb-edf4a35218ce.png)

Even when I take the multiple attribute away the box with options still overflows the `md-input-container` slightly.
  
![nomultiple](https://cloud.githubusercontent.com/assets/7645056/15354326/56fee62c-1ced-11e6-8866-1891dd22c190.png)

I also noticed this in the 1.0.8 `md-select` demos. I have the latest version of Angular Material (1.0.8).

**Comment by DevVersion** [comment]
Is it possible that you share your demo in a codepen or something? This would allow us to investigate your issue better.

**Comment by WeFknRise** [comment]
This is also the case in the 1.0.8 md-select demos on the Angular Material website. You can check this in the codepen of option groups on [https://material.angularjs.org/latest/demo/select].

Here is a screenshot:
![image](https://cloud.githubusercontent.com/assets/7645056/15392486/ab8181a2-1dc7-11e6-9f40-86e0e0a4cf8a.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by AdriVanHoudt** [comment]
So does this mean you will not fix this but you are still open for PR's?
