### ISSUE TITLE
npm package of version 1.0.8 contains incompatible files meant for version 1.1.0-rc4

### ISSUE THREAD

**Issue by atorma** [angular/material#8490]
**Actual behavior**:
-  What is the issue? * Bundles angular-material/angular-material.css and angular-material/angular-material.js in the npm package have been built from different files than those in the packages directory angular-material/modules/js. In the latter at least some files seem to originate from version 1.1.0-rc4.
-  What is the expected behavior? Bundles angular-material/angular-material.css and angular-material/angular-material.js and files in angular-material/modules/... are compatible.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

I am using the npm package angular-material version 1.0.8 and trying to create a custom angular-material build by cherrypicking only the components I need.

* angular-material/modules/js/core/core.js
* angular-material/modules/js/core/core.css
* angular-material/modules/js/core/default-theme.js
* angular-material/modules/js/backdrop/backdrop.js
* angular-material/modules/js/backdrop/backdrop.css
* angular-material/modules/js/input/input.js
* angular-material/modules/js/input/input.css
* angular-material/modules/js/select/select.js
* angular-material/modules/js/select/select.css

Also tried just picking the js files and angular-material.css bundle.

However, md-select is not working (layout issues, multiselect is not closing). When using the bundle files containing all components it's fine.

This seems to be because bundles angular-material.css and angular-material.js in the npm package have been built from different files than those in the packages directory angular-material/modules/js. In the latter at least some files seem to originate from version 1.1.0-rc4.

For example component `material.components.select` is using different CSS classes in the bundle vs the module file:

`angular-material/angular-material.js`:

```javascript
var CHECKBOX_SELECTION_INDICATOR =
  angular.element('<div class="md-container"><div class="md-icon"></div></div>');
```

`angular-material/modules/js/select/select.js`:

```javascript
/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v1.1.0-rc4-master-c81f9f1
 */

...

var CHECKBOX_SELECTION_INDICATOR =
  angular.element('<div class="_md-container"><div class="_md-icon"></div></div>');
```

Even if I was able to get the custom build to work, I'd still be using a different version than promised by the npm package version.

**Angular Versions**: *
-  Angular Version: (1.5.5)
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: * Chrome
-  Browser Version: * 50.0.2661.94 m
-  OS: * Windows 7
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
The patch releases **1.0.x** should not contain code and private CSS classes from `master` (and pending **1.1.0**). I will confirm this in this week's weekly release (1.0.x).

**Comment by ThomasBurleson** [comment]
Fixed
