### ISSUE TITLE
publish single components to npm

### ISSUE THREAD

**Issue by david-gang** [angular/material#8492]
**Actual behavior**:
-  What is the issue? * 
The current package is one javascript which can be used by browserify, webpack ...
-  What is the expected behavior?
Ability to download from npm just single components, like it is now with [angular material 2.](https://www.npmjs.com/~angular2-material) 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:
NA

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

NA

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:
NA
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Hm, I don't think that's easy / good for Angular 1.x Applications

For those users, who wan't to include the components separated, should take a look at our `js` or `closure` modules in `bower-material`
- https://github.com/angular/bower-material/tree/master/modules

Looking forward discussing about possible approaches :)

**Comment by david-gang** [comment]
Hi @DevVersion , 

I think that the proposition is good for angular 1 applications. You only load the amount of css and javascript which is needed for your application. This is especially important for IE.

Additionally if #8474 is developed and part of the directives are migrated to components, we could then use AM1 components which still were not developed by the AM2 team. This would mean that we could use AM1 and AM2 together.

My aim is to load individual elements with browserify and this can't be done with the current solution. (Correct me if you think otherwise)

If we have these modules already in a nice directory why wouldn't it be possible to add a package.json for each module and upload them to npm?



The only change which i see is necessary, is that the theming cannot be done globally for the whole package but rather for every individual element. 

Thanks,
David

**Comment by DevVersion** [comment]
@david-gang Thanks for the explanation.

After #8474 is done, this would definitely make sense. 

Creating those `package.json` files, wouldn't be that easy, because if we implement that approach, we would like to update those `package.json` files automatically.

But yeah, I agree, It would make sense.

**Comment by ThomasBurleson** [comment]
You can already use `npm install angular-material` and have access to components. Consider the button component:

*  `angular/bower-material@master/modules/js/core/core.css`
*  `angular/bower-material@master/modules/js/button/button.css`
*  `angular/bower-material@master/modules/js/button/button.js`

With this available, I contend that publishing individual UI components on NPM is not the right approach; as this would rapidly pollute the NPM space. Perhaps what is also needed is a solution for an  **online material packager**: component selector, customizer, builder, and download  for 1...n components

**Comment by ThomasBurleson** [comment]
Closing as "will not fix"

**Comment by david-gang** [comment]
Hi,

I could try to build a prototype of an online package manager as a simple express application.
If this would be of interest I could build a prototype of this and we could see how to integrate it in the existing angular material site.
For this purpose I would open a different issue,
Br,
David
