### ISSUE TITLE
Placeholder on md-datepicker doesn't show up when using custom format function

### ISSUE THREAD

**Issue by marcincichocki** [angular/material#8493]
When using custom format function `$mdDateLocaleProvider.formatDate` placeholder on `md-datepicker` is not shown. Instead today's date is displayed. Demo on plunker: http://plnkr.co/edit/O5ePYKyo1ILlheMz8KdO?p=preview

If you comment/remove `formatDate` function from config, placeholder is working.

angular-material version: 1.1.0-rc2

**Comment by crisbeto** [comment]
It seems like Moment defaults to today's date if the model is undefined. You can rewrite your function like this:

```js
function formatDate(date) {
  return date ? moment(date).format('L') : '';
}
```

**Comment by marcincichocki** [comment]
@crisbeto Thanks a lot! This solution solved my issue.

**Comment by crisbeto** [comment]
Cool, glad to help.

**Comment by enoxpublicidade** [comment]
Thanks!

**Comment by IrineuFilho** [comment]
I had same issue. thanks @crisbeto

**Comment by tomasz-szymanski** [comment]
Nice, also working for me !!
