### ISSUE TITLE
mdsticky elements lose stickiness inside ng-if element

### ISSUE THREAD

**Issue by jraadt** [angular/material#8498]
**Actual behavior**:
-  What is the issue? *
When applying mdsticky to an element, such as md-subheader, it doesn't stick after the following steps.
1. Activate the sticky element by scrolling down and then de-activate it by scrolling all the way back up.
2. A parent element with an ng-if to resolves to false thus hiding the sticky element.
3. The parent element with the ng-if resolves to true thus showing the sticky element again.
4. Scroll down and it no longer sticks.
If you scroll down and then back to the top again and then scroll down it regains it's stickiness.
-  What is the expected behavior?
It should always have the sticky behavior.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
http://codepen.io/anon/pen/zqVvRE
-  Details:
1. Click the "TOGGLE UNREAD" button to show the unread section.
2. Scroll down on the unread section to activate the sticky element.
3. Scroll back up to de-activate the sticky element.
4. Click the "TOGGLE UNREAD" button to hide the unread section.
5. Click the "TOGGLE UNREAD" button to show the unread section.
6. Scroll down and the unread subheader no longer sticks.

If you scroll back up to the top and then down again it works.  If you skip step 3 so it's activated when you hide the unread section, it works.  It's only broken on elements that have been activated, no longer activated, and then hidden and show again.  Happens not only with ng-if, but also ui-router views.

**Angular Versions**: *
-  Angular Version:
1.4.9
-  Angular Material Version:
1.0.8

**Additional Information**:
-  Browser Type: *
Chrome
-  Browser Version: *
50
-  OS: *
Windows 10
-  Stack Traces:
None

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
