### ISSUE TITLE
online material packager

### ISSUE THREAD

**Issue by david-gang** [angular/material#8499]
**Actual behavior**:
-  What is the issue? *
We are not able to have a bundle with the specific components we want. This leads to a bigger css and js than needed
-  What is the expected behavior?
An online tool with the following abilities:

- [ ]  component selector
- [ ] customize components 
- [ ] download for 1...n components

I would suggest that i could start in a different repository a component selector and downloader. I would start with an express application and angular material in the local file system.
The next steps would be to migrate/ integrate with the angular infrastructure and then create a color picker for all themes. This would also eliminate the need to inject the colors in runtime, which could be a solution for #8218, 

@ThomasBurleson - Before embarking on this i would like to hear what you think about this and what the procedures are in this type of development.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

This is the continuation of the discussion at #8492

**Comment by DevVersion** [comment]
Hey @david-gang, we're internally planning for a node module, which allows developers to generate themes dynamically (#8671)

The Online Package Manager, will probably depend on that (I think so).

Are you going to work on that feature?

**Comment by david-gang** [comment]
Hi @DevVersion and @crisbeto ,

Great that you drop in. I thought about this issue extensively and want to share them. 

# Input

* Material version number
* List of components 
* Color palettes for theming. This is optional

# Output in zip format

* material.js, material.min.js 
* material.css, material.min.css 
* colors.css, colors.min.css 

Open issue:
* Do we want to have source maps? We don't have it in the original file?

I think as a first step, we would like to build a command line which accepts a json and creates a zip file.

The top level function should:
* download the angular material specific version, if it does not exist
* create the files mentioned above
* Take the relevant files from the modules/js folder and create the files mentioned above.
* return a zip stream with the data
The command line program will store the zip file to a command line

As a second step we could build an express application which calls this top level function and just stream the zip file to the browser.

Here we have a bit ui work. We will want to write it with angular material :-). 

We could use gulp, but i don;t know how to call programmatically to gulp from nodejs. I consider calling gulp from the command line as ugly.

I will be very happy to share this work with you and looking forward to hear from you how you think, the work could be best split.

**Comment by DevVersion** [comment]
> colors.css, colors.min.css

I would merge this into one general stylesheet. 

----

In general, I like this approach.

**Comment by crisbeto** [comment]
IMO the biggest challenge here is figuring out the dependencies between modules. I was thinking of either loading the full library and monkey-patching the `angular.module` method and intercept the dependencies that each module registers. Otherwise we can also use a regex to parse it out from the raw files. After we have those, it should be easy to pass everything to Uglify and SASS.

**Comment by david-gang** [comment]
Where do you want to develop this? In the material repository or in a side repository?

**Comment by DevVersion** [comment]
We are currently a bit confused. Are you going to work on the Source? Or are you just helping with planning / designing etc?

**Comment by david-gang** [comment]
Sorry for the confusion. 
Please go ahead :-)
If you need any help in the planning or testing i will be glad to help.
Thanks a lot for your efforts :+1:

**Comment by DevVersion** [comment]
@david-gang Yeah, we definitely would like to get your feedback. Thanks again!

**Comment by crisbeto** [comment]
Well I've been playing around with idea of monkey patching Angular's methods. Here's what I ended up with. It's pretty dirty, but it works without any dependencies.

```js
var noop = function(){};

GLOBAL.window = {
    addEventListener: noop,
    document: {
        addEventListener: noop,
        querySelector: function(){
            return {
                getAttribute: function(){
                    return '';
                }
            };
        },
        createElement: function(){
            return {
                setAttribute: noop,
                pathname: ''
            };
        }
    },
    Node: {
        prototype: {
            contains: noop
        }
    },
    location: {}
};

GLOBAL.angular = window.angular;

require('angular');

var angular = window.angular;

for (var key in angular) {
    if (angular.hasOwnProperty(key) && typeof angular[key] === 'function') {
        angular[key] = noop;
    }
}

angular.module = function(name, dependencies){
    var dummy = {};

    if(name !== 'ngMaterial' && dependencies){
        console.log(
            'Name: ' + name.replace('material.', '') + '\n' +
            'Dependencies: ' + (dependencies.join(', ') || 'None') + '\n'
        );
    }

    [
        'run',
        'config',
        'directive',
        'service',
        'provider',
        'filter',
        'factory',
        'constant',
        'controller',
        'animation'
    ].forEach(function(current){
        dummy[current] = function(){
            return this;
        };
    });

    return dummy;
};

require('angular-material');
```

And here's an output of the dependencies:

```
Name: ngAnimate
Dependencies: None

Name: ngAria
Dependencies: ng

Name: core
Dependencies: ngAnimate, material.core.animate, material.core.layout, material.core.gestures, material.core.theming

Name: core.gestures
Dependencies: None

Name: core.layout
Dependencies: ng

Name: core.theming.palette
Dependencies: None

Name: core.theming
Dependencies: material.core.theming.palette

Name: core.animate
Dependencies: None

Name: components.autocomplete
Dependencies: material.core, material.components.icon, material.components.virtualRepeat

Name: components.backdrop
Dependencies: material.core

Name: components.button
Dependencies: material.core

Name: components.bottomSheet
Dependencies: material.core, material.components.backdrop

Name: components.card
Dependencies: material.core

Name: components.checkbox
Dependencies: material.core

Name: components.chips
Dependencies: material.core, material.components.autocomplete

Name: components.colors
Dependencies: material.core

Name: components.content
Dependencies: material.core

Name: components.datepicker
Dependencies: material.core, material.components.icon, material.components.virtualRepeat

Name: components.dialog
Dependencies: material.core, material.components.backdrop

Name: components.divider
Dependencies: material.core

Name: components.fabActions
Dependencies: material.core

Name: components.fabShared
Dependencies: material.core

Name: components.fabSpeedDial
Dependencies: material.core, material.components.fabShared, material.components.fabTrigger, material.components.fabActions

Name: components.fabToolbar
Dependencies: material.core, material.components.fabShared, material.components.fabTrigger, material.components.fabActions

Name: components.fabTrigger
Dependencies: material.core

Name: components.gridList
Dependencies: material.core

Name: components.icon
Dependencies: material.core

Name: components.list
Dependencies: material.core

Name: components.input
Dependencies: material.core

Name: components.menuBar
Dependencies: material.core, material.components.menu

Name: components.menu
Dependencies: material.core, material.components.backdrop

Name: components.navBar
Dependencies: material.core

Name: components.panel
Dependencies: material.core, material.components.backdrop

Name: components.progressCircular
Dependencies: material.core

Name: components.progressLinear
Dependencies: material.core

Name: components.radioButton
Dependencies: material.core

Name: components.sidenav
Dependencies: material.core, material.components.backdrop

Name: components.select
Dependencies: material.core, material.components.backdrop

Name: components.slider
Dependencies: material.core

Name: components.showHide
Dependencies: material.core

Name: components.swipe
Dependencies: material.core

Name: components.sticky
Dependencies: material.core, material.components.content

Name: components.switch
Dependencies: material.core, material.components.checkbox

Name: components.subheader
Dependencies: material.core, material.components.sticky

Name: components.tabs
Dependencies: material.core, material.components.icon

Name: components.toast
Dependencies: material.core, material.components.button

Name: components.toolbar
Dependencies: material.core, material.components.content

Name: components.tooltip
Dependencies: material.core

Name: components.virtualRepeat
Dependencies: material.core, material.components.showHide

Name: components.whiteframe
Dependencies: material.core
```

**Comment by DevVersion** [comment]
We're going to track this within #8671
