### ISSUE TITLE
Input autofill doubles over the input

### ISSUE THREAD

**Issue by twigg** [angular/material#8501]
When using the md-input for a login if the password has been remembered the input double over the holding text

Expected behaviour is the placeholder to sit above the input, it does this for text input fileds which are remembered but not the password field 

Angular Version - 1.5.3
Material Version - 1.1.0

Google Chrome - 50.0.2661.102
Windows 7 Pro

```
<md-input-container class="md-block">
                    <input type="password" class="ng-pristine ng-valid md-input ng-touched" name="password" value="{{ old('password') }}" placeholder="Password (required)" ng-required="true">
</md-input-container>
```

![image](https://cloud.githubusercontent.com/assets/4605926/15387109/11699772-1da3-11e6-8da3-ebf4e0a5dcc4.png)

**Comment by ThomasBurleson** [comment]
@crisbeto - I think we had previous issues with this. Not sure of the resolution(s).

**Comment by crisbeto** [comment]
The previous issue was with dynamic placeholders on inputs and it has a fix at #8291. This seems to be different, though. I think the input container isn't reacting when the browser autocompletes.

**Comment by keenondrums** [comment]
@twigg, it's a Crome-related issue, not Material's one. http://stackoverflow.com/questions/35049555/chrome-autofill-autocomplete-no-value-for-password

I found a more-or-less suitable workaround. Chrome fills not only the password, but the login as well. Chrome colors the input when it fills it. I suggest binding to ng-change on login field and when it fires compare password field color to an additional hidden input color. If the colors mismatch add 'md-input-has-value' class to password's container. Be aware it won't work if a user uses a custom theme which does not color the input.

It looks like this:
`<div layout="row" flex="100">
    <md-input-container class="container-full-width"
                        md-is-error="loginForm.email.$invalid && (loginForm.email.$dirty || loginForm.$submitted)">
      <label>Email</label>
      <input ng-change="checkPasswordAutofilled()" type="email" ng-model="credentials.email" name="email" maxlength="255" ng-required="true"/>
      <div ng-messages="loginForm.email.$error"
           ng-show="loginForm.email.$invalid && (loginForm.email.$dirty || loginForm.$submitted)">
        <div ng-message="required">{{messages.email.required}}</div>
        <div ng-message="email">{{messages.email.email}}</div>
        <div ng-message="custom">{{loginForm.email.customError}}</div>
      </div>
    </md-input-container>
  </div>

  <div layout="row" flex="100">
    <md-input-container class="container-full-width"
                        md-is-error="loginForm.password.$invalid && (loginForm.password.$dirty || loginForm.$submitted)">
      <label>Password</label>
      <input id="password" type="password" ng-model="credentials.password" name="password" maxlength="255"
             ng-required="true"/>
      <div ng-messages="loginForm.password.$error"
           ng-show="loginForm.password.$invalid && (loginForm.password.$dirty || loginForm.$submitted)">
        <div ng-message="required">{{messages.password.required}}</div>
        <div ng-message="custom">{{loginForm.password.customError}}</div>
      </div>
    </md-input-container>
  </div>

<md-input-container class="hidden">
  <label>Password</label>
  <input id="compareColor" type="password"/>
</md-input-container>
`

`function checkPasswordAutofilled() {
      $timeout(function () {
        if ($window.getComputedStyle(passwordInput).getPropertyValue('background-color') !== $window.getComputedStyle(compareColorInput).getPropertyValue('background-color') ) {
          passwordInput.parentElement.className += ' md-input-has-value';
        }
      });
    }`

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by aston00** [comment]
The following fixes this issue:
1. Put label after input within template
2. Within css add this(adjustments with percentage may be necessary in your particular case):
 `input:-webkit-autofill ~ label {
    -webkit-transform: translate(0, 38%) scale(0.75);
    transform: translate(0, 38%) scale(0.75);
}`
