### ISSUE TITLE
<input type="number" ... /> allows not-numeric characters on Safari browser

### ISSUE THREAD

**Issue by krowal** [angular/material#8502]
On safari browser it is possible to write letters inside <input> when its marked as type="number". Can be tested at official ng-material page at input section - "Donation amount" at the bottom of the page https://material.angularjs.org/latest/demo/input

![image](https://cloud.githubusercontent.com/assets/2960003/15392391/158df3b0-1dc7-11e6-89be-14aa9c7bf9a4.png)

**Comment by crisbeto** [comment]
Material doesn't do any number validations/limitations on the user input. I believe only Angular marks it as invalid.

**Comment by DevVersion** [comment]
@crisbeto I agree. Also on every browser, you can type <kbd>e</kbd> in the number input. 

This seems to be intentionally, but I haven't figured the why yet.

**Comment by crisbeto** [comment]
It might be because of the exponential notation in JS (e.g. `1.00001e+32`).

**Comment by krowal** [comment]
@crisbeto its not only because of JS, its because of global use in math :)

**Comment by krowal** [comment]
@crisbeto @DevVersion ok, actually it is a browser-level problem. Safari handles type="number" differently and allows to write also other characters instead of numbers only. To block it you have to write custom event handler.
