### ISSUE TITLE
datepicker fill

### ISSUE THREAD

**Issue by danielemontesi** [angular/material#8503]
How can i display select and datepicker on same line and both 50% width?
This does not work:

`<md-content class="md-padding"><div layout-gt-sm="row">
		        	<md-input-container class="md-block" flex="50">
		            	<label for="abbonamento">Abbonamento</label>
				      	<md-select ng-model="cliente.id_tipo_abbonamento">
         						<md-option ng-repeat="abbonamento in abbonamenti" value="{{ abbonamento.id }}">
           						{{ abbonamento.descrizione }}
         						</md-option>
       					</md-select>
		          	</md-input-container>
		          	<div class="md-block" flex="50">
		            	<label for="data_inizio_abbonamento">Data inizio</label>
				      	<md-datepicker ng-model="cliente.data_inizio_abbonamento"></md-datepicker>
		          	</div>
		        </div>
       		</md-content>`

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
