### ISSUE TITLE
$mdSticky elements don't un-sticky correctly with non-sticky sibling elements before them.

### ISSUE THREAD

**Issue by jraadt** [angular/material#8506]
**Actual behavior**:
-  What is the issue? *
When you have a sticky element like md-subheader in a md-list with other non-sticky elements in the scroll container before the md-list, the sticky header continues to show up even after you scroll back up past the list.  The sticky header only goes away when you reach the very top of the scroll container.
-  What is the expected behavior?
The md-subheader sticky clone (or any sticky element) should not be shown when the real header is fully in view.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
http://codepen.io/anon/pen/WwqRvq
-  Details:
Scroll down to activate the sticky header for "Unread Messages".  Then slowly scroll up (but not all the way up) and you can see both the sticky and non-sticky "Unread Messages" headers shown.  Only when you reach all the way to the top of the scroll container does the sticky message go away.

**Angular Versions**: *
-  Angular Version: 1.4.9
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: * Chrome
-  Browser Version: * 50
-  OS: * Windows 10
-  Stack Traces: None

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by jraadt** [comment]
For others needing this to work right now you can place a hidden sticky element before your visible sticky element.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
