### ISSUE TITLE
Unable to focus text input when validation error present and using ng-messages as an element

### ISSUE THREAD

**Issue by RKumsher** [angular/material#8508]
**Do you want to request a *feature* or report a *bug*?**
Bug

**Description**
Using ng-messages as an element (instead of an attribute of a DIV), you cannot focus on a text input if there's a ng-message displayed

**Steps to reproduce**
1. Navigate to http://codepen.io/anon/pen/XdLMeP
2. Clear the contents in the 2nd description text input
3. Click in the 1st description text input
4. "This is required." should appear in red as a validation error on the 2nd description text input
5. Click in the 2nd description text input

**Expected Behavior**: Text input focuses
**Actual Behavior**: Cannot focus on text input

**Which versions of Angular, and which browser / OS are affected by this issue**
**Angular Version**: 1.4.8
**Chrome Version**: 52.0.2741.0
**OS**: OSX 10.11.4

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by CristianMR** [comment]
@RKumsher to solve this, just add this to your css file

```css
md-input-container ng-messages {
  display: block;
}
```

Yeah, I know.
