### ISSUE TITLE
md-select does not set aria-label for selected item when not in an md-input-container

### ISSUE THREAD

**Issue by voithos** [angular/material#8509]
**Actual behavior**:
-  What is the issue? `md-select` does not set any appropriate a11y attributes when it isn't included inside an `md-input-container` alongside a `<label>`.
-  What is the expected behavior? `md-select` should add an `aria-label` with the currently selected option's text, or use an `aria-activedescendant` to point to said option.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/BKgRBw
-  Details: The codepen is essentially a copy of one of the [examples from here](https://material.angularjs.org/latest/demo/select), with the `md-input-container` wrappers removed. Using a screen reader (ChromeVox, in my case), when the md-select is focused, the reader just says something along the lines of "list box, collapsed" instead of mentioning the currently selected item (e.g. "small (12-inch)").

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: latest (1.0.8)

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102
-  OS: Ubuntu
-  Stack Traces:

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
