### ISSUE TITLE
md-card: demo page for cards not properly rendered in IE11

### ISSUE THREAD

**Issue by sjaase** [angular/material#8510]
Cards are not rendered properly on the angular demo page when using IE11.

Suspect it is related to layout.

Added screenshot.
![image](https://cloud.githubusercontent.com/assets/11314887/15404396/85c74cea-1dfd-11e6-8b65-106fa8667a81.png)

**Angular Versions**:
-  Angular Version: 1.0.8
-  Angular Material Version: 1.4.8

**Additional Information**:
-  Browser Type: Internet Explorer
-  Browser Version: 11
-  OS: Windows 10

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
