### ISSUE TITLE
md-whiteframe content prints black in chrome

### ISSUE THREAD

**Issue by astynax777** [angular/material#8512]
I can't say if this is a bug in the browser or with the styles specific to Chrome, but if you look at my pen here: 
http://codepen.io/astynax777/pen/yOdopv 
assuming you can reproduce it, you will find that in only Chrome (for me on Windows), the whiteframe shows up as a black box.  If you actually print it, you can possibly see the content underneath the black box though it's illegible.

I'm on Windows 7-64 bit.
Chrome Version 50.0.2661.102 m (64-bit).

I've tested with several different printers - all the same result in Chrome.  Everything printed fine in IE and Firefox.

I should note that I disabled all plugins and extensions in my testing.

**Comment by astynax777** [comment]
After further testing, I found that if I add the following to my css it resolves my issue:

```
@media print {
    md-whiteframe {
        background-color: #FFF;
    }
}
```

**Comment by ThomasBurleson** [comment]
Please note we only support issues using Head/master. If you find an issue with an earlier build, we ask developers to first confirm that it exists in `master`.
> `npm install http://github.com/angular/bower-material#master`

This bug is also present `master`. Thank you.

**Comment by astynax777** [comment]
@ThomasBurleson you must be referring to my codepen.  I apologize - I forced an older pen and didn't update the version.  This has been corrected.

**Comment by RolandHeath** [comment]
You updated the javascript, but don't forget the css. It'd be nice if the new codepen link present when creating a new issue had something to automatically update to the latest angular-material.

**Comment by astynax777** [comment]
@RolandHeath good call. Done.
