### ISSUE TITLE
md-menu-bar error on right key on last menu

### ISSUE THREAD

**Issue by Paolo988** [angular/material#8514]
**Actual behavior**:
-  to the right-click on the keyboard if there are no other md-menu, is created an error
-  [ TypeError: Cannot read property 'open' of undefined ]

Angular MD 1.0.8

**StackTrace**
TypeError: Cannot read property 'open' of undefined
    at angular-material.js:23294
    at angular.js:17918
    at completeOutstandingRequest (angular.js:5552)
    at angular.js:5829

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
