### ISSUE TITLE
mdAutocomplete doesn't get blurred when using touch screens.

### ISSUE THREAD

**Issue by remcohaszing** [angular/material#8515]
**Actual behavior**:
-  What is the issue?
  `mdAutocomplete` can't be unfocused when using a touch screen.

-  What is the expected behavior?
  `mdAutocomplete` should lose focus when tapping outside of it, just like when clicking outside of it in the browser.

**CodePen** or Steps to reproduce the issue: *
The issue can be viewed on https://material.angularjs.org/HEAD/demo/autocomplete.

On a desktop, click the basic example. Now click somewhere outside and notice the `mdAutocomplete` gets blurred.

Do the same on Google Chrome for Android or Android stock browser. Notice that `mdAutocomplete` does not get blurred.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc4

**Comment by ClickerMonkey** [comment]
The md-scroll-mask element is lingering - which keeps the user from doing anything outside of the md-autocomplete. There are similar issues around this issue - not sure if their fixes will correct this scenario.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ClickerMonkey** [comment]
Can you provide more information on why this is being closed? - this control can be completely unusable on mobile devices. It can block you from being able to interact with the application at all. The workaround is to use CSS to hide the scroll mask which makes all the work around the scroll mask useless. 

Thanks

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
