### ISSUE TITLE
featueDiscovery: implement to MD components

### ISSUE THREAD

**Issue by lievenjanssen** [angular/material#8516]
**Feature discovery**

Introduces a feature discovery prompt

![image](https://cloud.githubusercontent.com/assets/958643/15427034/9220515e-1e92-11e6-86a6-6fbeca523a48.png)

See https://www.google.com/design/spec/growth-communications/feature-discovery.html#feature-discovery-design
Will you be implementing components to support Google Material Design onboarding?

**Top user benefits**

Introduces a autoplay carousel component

![image](https://cloud.githubusercontent.com/assets/958643/15427027/80b5e014-1e92-11e6-8ee0-698a6a0b34cb.png)

See https://www.google.com/design/spec/growth-communications/onboarding.html#onboarding-top-user-benefits

**Comment by ThomasBurleson** [comment]
* The **feature-discovery** component is new and should be implemented in ngMaterial core.
* We do not have any plans to implement a carousel component. The is not a core component.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
