### ISSUE TITLE
Backdrop is enabling for md-select

### ISSUE THREAD

**Issue by VivekVikranth** [angular/material#8517]
**Actual behavior**:
-  What is the issue? *
    Issue is backdrop is enabling while using md-select.
-  What is the expected behavior?
    Backdrop is not needed, I never seen backdrop on md examples.
**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:
 

**Angular Versions**: *
-  Angular Version:
    1.4.8
-  Angular Material Version:
   v1.0.8

**Additional Information**:
-  Browser Type: * Firefox and Chrome
-  Browser Version: * All
-  OS: * Windows
-  Stack Traces: [Stackoverflow with image](http://stackoverflow.com/questions/37345090/how-to-disable-backdrop-in-md-select)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
There's a backdrop on the official examples as well, but it's transparent. You're probably adding the color somewhere else in your app.

**Comment by VivekVikranth** [comment]
Yes, my bad!
