### ISSUE TITLE
switch: focus indicator is wrong on dark themes

### ISSUE THREAD

**Issue by DevVersion** [angular/material#8518]
Seems like the focus indicator is not correct on dark themes.
- It should be white on dark themes with an opacity of 12%
- It should be black on light themes with an opacity of 12% as well.

FYI: Actually the ripple indicator is correct on dark themes. But not the focus indicator for keyboard interaction.

![image](https://cloud.githubusercontent.com/assets/4987015/15434473/50d64e40-1eb7-11e6-91af-b01c56421c1e.png)

**Comment by EladBezalel** [comment]
Actually the colors of the switch aren't matching the specs in dark/light themes

'' | Light | Dark
--- | --- | ---
Thumb On | Swatch 500, Opacity  100% | Swatch 200, Opacity  100%
Track On | Swatch 500, Opacity  50% | Swatch 200, Opacity  50%
Thumb Off | Grey 50, #FAFAFA, Opacity  100% | Grey 400, #BDBDBD, Opacity  100%
Track Off | #000000, Opacity  38% | #FFFFFF, Opacity  30%
Thumb Disabled | Grey 400, #BDBDBD, Opacity  100% | Grey 800, #424242, Opacity 100%
Track Disabled | #000000, Opacity  12% |  #FFFFFF, Opacity  10%

**Comment by Splaktar** [comment]
@rudzikdawid I haven't had time to look into this one yet, but it seemed like one that you may be interested in investigating. If this is still an issue, I'd like to try to get it into 1.1.11.
