### ISSUE TITLE
custom md-item-template for md-autocomplete

### ISSUE THREAD

**Issue by blbigelow** [angular/material#8519]
This is a request to re-open a spring cleaning item.

#5182

This would be very handy for showing types of search results. Even the name seems to suggest customization.

**Actual behavior**:
-  What is the issue? *
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by scriptsure** [comment]
+1

**Comment by mcdwight6** [comment]
+1
If the element is called md-item-"template" isn't the ability to customize said "template" with html implied? I could really use this.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
