### ISSUE TITLE
md-checkbox: links in label do not work

### ISSUE THREAD

**Issue by epelc** [angular/material#852]
When you have a link within an `md-checkbox` clicking on the link toggles the checkbox instead of opening the link. Example

![md-checkbox-link](https://cloud.githubusercontent.com/assets/5204642/5301713/eb4453f4-7ba8-11e4-8152-36e213fc1cc4.PNG)

```
 <md-checkbox ng-model="user.AcceptedTerms">
    I agree to the <a ui-sref="legal.tos">Terms of Service</a>
</md-checkbox>
```

I also tried to add `ng-click="$event.stopPropagation()"` and `ng-click="$event.stopPropagation()"` to the `<a>`. It also doesn't work if you use an `href` instead of `ui-sref`.

**Comment by robertmesserle** [comment]
Note: This should be resolved when refactored approach to checkboxes/radio buttons is implemented.

**Comment by robertmesserle** [comment]
Related issues: #1006 #1007

**Comment by epelc** [comment]
@robertmesserle I just noticed that you can tab to the links but the focus state does not seem to show on the link or the checkbox text.

**Comment by leibale** [comment]
what about this?

**Comment by sheaujye** [comment]
Guys, any update on this one?

**Comment by iamgioz** [comment]
click over the link doesn't work because '.md-label' has 'pointer-events: none;' css rule. my quick fix for now: 
```
md-checkbox .md-label {
    pointer-events: auto;
}
md-checkbox .md-label span {
    pointer-events: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

**Comment by Necroskillz** [comment]
When the link has `target="_blank"` clicking the link will check the checkbox (with the 0.10 version). I think this should not happen.

See http://plnkr.co/edit/fjXDqbi6U5p6zv9K1AKM?p=preview

**Comment by ksgupta** [comment]
+1 @Necroskillz  

Any update on the fix for this anyone please?

**Comment by arne-s** [comment]
Here is a workaround

```
   <md-checkbox ng-model="conditions">
 I agree to the <a onclick="window.open('legal.tos')" ng-click="$event.stopPropagation()">Terms of Service</a>
            </md-checkbox>
```
