### ISSUE TITLE
WP 8.1/10 - slow/laggy virtual-repeat beneath tabs

### ISSUE THREAD

**Issue by graphefruit** [angular/material#8521]
**Actual behavior**:
-  What is the issue? Virtual-Repeat is laggy/slow while scrolling. This happends if the virtual-repeat is bound beneath a tabs component, without the virtual-repeat is fast (see videos)
This issue is mainly noticeable on Windows-Phones (8.1 & 10)
-  What is the expected behavior? Virtual-Repeat should scroll without lag or slow like without shown in the CodePen-Demo2 (without the tabs component).

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/eZwjxR?editors=1111
-  Details: This demo inherits the virtual-repeat inside an md-tab. (slow)
- Video: https://vid.me/U26A

**CodePen 2**
- http://codepen.io/anon/pen/NNZOwB?editors=1111
- Details: This demo inherits the virtual-repeat without an md-tab. (fast)
- Video: https://vid.me/pmXY

You also can see, after watching both videos, that the fast version has blank screens (scrolling to fast, I think IE cant render that fast). The slow version doesn't even show up this problem.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: RC-4

**Additional Information**:
-  Browser Type: Windows-Phone 10
-  Browser Version: IE Mobile
-  OS: Windows
-  Phone: Lumia 550
-  Stack Traces:

Greetings
Graphefruit

Update: The scroll is even slower on WP8.1, I can upload a video by monday.

**Comment by graphefruit** [comment]
I played arround the CSS-properties now a little bit, if I set:
```
md-tabs
{
    position:fixed!important;
}
```
the scrolling is more fluid and is (actual on my WP 10 phone) as fast as in the Codepen2.
The problem that is occuring then: THe Tab-component isn't stretching to the full width afterwards.

Maybe this helps you.
Greetings

**Comment by graphefruit** [comment]
@ThomasBurleson Could you please explain me why this one is deprecated? - Thanks in advance.
The "fix" I did above don't solve the issue totally. In a Cordova-APP its even more laggy.

After I to fix this, I did some more workarounds:
HTML:
```
<md-content class="flex">
    <md-tabs class="md-tabs-fixed-height" md-selected="tabs.selectedIndex">
        <md-tab label="Tab1">

        </md-tab>
        <md-tab label="Tab2">

        </md-tab>

    </md-tabs>
	<md-content ng-show="tabs.selectedIndex===0" md-swipe-left="tabs.next()" md-swipe-right="tabs.previous()">Tab1 - Content</md-content>
	<md-content ng-show="tabs.selectedIndex===1" md-swipe-left="tabs.next()" md-swipe-right="tabs.previous()">Tab2 - Content</md-content>
</md-content>
```

JS:
```
$scope.tabs = {
        selectedIndex: $scope.$root.tempSettings.searchpage.sliderIndex,
        next: function () {
            $scope.tabs.selectedIndex = Math.min($scope.tabs.selectedIndex + 1, 1);
        },
        previous: function () {
            $scope.tabs.selectedIndex = Math.max($scope.tabs.selectedIndex - 1, 0);
        }
    };
```
CSS: 
```
.md-tabs-fixed-height
{
    min-height:48px!important;
}
```
Isn't fine but atleast its solving its job even more.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
