### ISSUE TITLE
Opening two sidenavs permanently sets 'overflow: hidden' on container element

### ISSUE THREAD

**Issue by haswellr** [angular/material#8522]
**Actual behavior**:
-  What is the issue? When one sidenav is opened, and then another is opened before the first has closed, the container element is permanently set to 'overflow: hidden'.
-  What is the expected behavior? The container element's overflow styling should revert back to whatever styling it had before the sidenav was opened.

**CodePen** or Steps to reproduce the issue: 
-  CodePen Demo which shows your issue : http://codepen.io/haswellr/pen/zqVMbP
-  Details: Instructions for replication are shown on the codepen.

**Angular Versions**: *
-  Angular Version: 1.5.0
-  Angular Material Version: 1.0.5

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102 m
-  OS: Windows 10 x64
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
