### ISSUE TITLE
<form> with 100 rows of inputs slows down rendering by 3x.

### ISSUE THREAD

**Issue by sheaujye** [angular/material#8524]
**Actual behavior**:
-  What is the issue? *
The app stalls for 10 sec when trying to load 100 items into $scope which get rendered in view as a form using ng-repeat, removing the form element actually speed things up by 3x.

-  What is the expected behavior?
Not sure if this is a angular material issue or angular issue, I just have no idea why it will slow down the app by 3x by adding form element.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/sheaujye/pen/GZbqdL
-  Details: Click on the populate and wait for the rendering, then removing form element and try again.

**Angular Versions**: *
-  Angular Version: 1.5.0
-  Angular Material Version: 1.0.5

**Additional Information**:
-  Browser Type: * Chrome
-  Browser Version: * 49.0.2623.112 (64-bit)
-  OS: * Mac 10.10.3 Yosemite
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
@sheaujye - Please always test with HEAD versions.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
