### ISSUE TITLE
<md-tooltip> does not work inside disabled <md-button>

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#8530]
**Actual behavior**:
-  What is the issue? md-tooltip is not working inside a disabled md-button
-  What is the expected behavior? md-tooltip should work working inside disabled md-button

**CodePen** or Steps to reproduce the issue: 
-  CodePen Demo which shows your issue : http://codepen.io/cmacdonnacha/pen/YqmrNq
-  Details: Hover over the disabled button, tooltip is not displayed.

**Angular Versions**:
-  Angular Version: 1.4
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.94 m
-  OS: Windows 7 SP1
-  Stack Traces:

**Comment by ThomasBurleson** [comment]
Not supported.

**Comment by lumalav** [comment]
Why is not supported? A user might not be aware of why a button is disabled.

**Comment by maelfrize** [comment]
We'd also like to explain to our users why a button is disabled.

**Comment by cmacdonnacha** [comment]
@ThomasBurleson  Will this be supported in material2?

**Comment by yogimittal** [comment]
Would love to see this feature!

**Comment by Pranay92** [comment]
We're having the same issue here - the only solution is to add external css to make this work or use a new library for tooltips

**Comment by mark-langer** [comment]
This issue states that this is a browser-related problem. A browser does not fire mouse events for disabled buttons #2576

**Comment by florin05** [comment]
Seems like a quick workaround is to take the `<md-tooltip>` out of the  `<md-button>` and put them both in a container `<div>`

```
<div>
    <md-button ng-disabled="true">Disabled</md-button>
    <md-tooltip>This is disabled because ...</md-tooltip>
</div>
```

**Comment by dtrenin7** [comment]
florin05,
solution with <div> has no effect....

**Comment by zendu** [comment]
@Pranay92 - Can you share CSS that did the trick to show tooltip on disabled <md-button>?

**Comment by florin05** [comment]
The code I posted still works for me, here is a screenshot.
To be precise, the button contains an icon, if it is empty there is nothing to hover over, so I am updating my code sample
![tooltip disabled2](https://user-images.githubusercontent.com/11194908/34302047-327e2764-e6fd-11e7-9dcf-9cfae6c67e33.PNG)

**Comment by lfreneda** [comment]
+1

**Comment by Splaktar** [comment]
@lfreneda As @florin05 [posted](https://github.com/angular/material/issues/8530#issuecomment-331981902), you can wrap the button in a `div` or `span` and then add the tooltip to that. This is a browser restriction and is not an AngularJS Material issue.
