### ISSUE TITLE
<md-select multiple> Not able to select multiple options to update ng-model while using ng-model-options-{debounce:500}

### ISSUE THREAD

**Issue by anukiransolur** [angular/material#8531]
**Actual behavior**:
-  What is the issue? * <md-select multiple> updates the last clicked option to the ng-model but does not select all the clicked options when used with ng-model-options-{debounce:500}
-  What is the expected behavior? <md-select multiple> when used with debounce should wait for the user to select multiple options and then update the ng-model

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details: Add ng-model and ng-model-options-{debounce:500} to <md-select> to reproduce the issue.

**Angular Versions**: *
-  Angular Version:1.4.9
-  Angular Material Version:1.1.0-rc4

**Additional Information**:
-  Browser Type:  Chrome Canary 
-  Browser Version: 52.0.2708.0
-  OS: 
-  Stack Traces:OS X EI Capitan Version 10.11.3

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Not supported.

**Comment by anukiransolur** [comment]
Will it be added in the future ?
