### ISSUE TITLE
dialog: Opening a dialog while one is shown will resolve the first dialog instead of rejecting it.

### ISSUE THREAD

**Issue by epelc** [angular/material#8533]
**Actual behavior**:
-  What is the issue? *Opening a dialog while one is shown will resolve the first dialog instead of rejecting it.
-  What is the expected behavior? The first dialog should be rejected. I assume all if not most dialog promise's resolve functions expect the passed arguments to be from their explicit call to hide. This causes exceptions when it is automatically resolved instead of rejected.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/oxKpVr?editors=1010
-  Details: Click the `Open automatic dialog` to automatically trigger the bug by opening a dialog waiting a small timeout then opening a second dialog. This reproduces opening a dialog then pressing enter quickly or just opening a second dialog while one is already open.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.0.7 and 1.0.8

**Additional Information**:
-  Browser Type: * chrome
-  Browser Version: * 50.0.2661.102 (64-bit)
-  OS: * os x 10.11.5 
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Resubmit of #7112

**Comment by epelc** [comment]
I'd like to mention the legitimate use case where this is likely to come up.

 If you use a dialog with some inputs that have defaults to add something to a list or what not and you want to add a bunch clicking enter too fast causes this.

**Comment by DevVersion** [comment]
@epelc The PR is now pending. Thanks again for that **excellent** codepen.
