### ISSUE TITLE
Too many watchers in md-input-container

### ISSUE THREAD

**Issue by Alevale** [angular/material#8536]
**Actual behavior**:
-  What is the issue? Every variable in the md-input-container creates an other watcher binding even if the value is already being watched, causing the app to not be optimized
-  What is the expected behavior? No extra watchers by putting the md-input-container

**CodePen**
- Extract from the same code we have in the angular material codebase example
- http://codepen.io/alevale/pen/bpXOop here we have 111 watchers
- http://codepen.io/alevale/pen/BKXvdN here we have 115 watchers

**Angular Versions**: *
-  Angular Version:  1.4.8
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0
-  OS: Mac Yosemite 10.10
-  Stack Traces: --

----

**Comment by crisbeto** [comment]
Most of those watches are from the md-select which has ~100 items, try commenting it out and it goes down to 5. We have an issue about not pre-rendering the select's dropdown at #8534.

**Comment by Alevale** [comment]
okey, i do agree that those 100 watchers are related mostly to the md-select, but i don't like that the `md-input-container` adds an other watcher to each of the elements i have, and that is what i was actually complaining about, **why there's an extra watcher**

**Comment by crisbeto** [comment]
Well it still needs to know things like whether it has a label, whether it has an error etc. Having 0 watches isn't very feasible.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
