### ISSUE TITLE
Directives get executed twice when inside md-subheader

### ISSUE THREAD

**Issue by Undrium** [angular/material#8537]
Following being a very simple example:

`<md-subheader><div my-directive></div></md-subheader>
`

```
  app.directive('myDirective',
  [function(){
    return {
      restrict: 'A',
      link: function link(scope, elem, attrs) {
        console.log("Did I just see double?");
      }
    };
  }]);
```

This will execute the link() function twice, is there anything I'm missing here? If I place the directive outside of md-subheader it'll just be ran once.

**Comment by kevohagan** [comment]
yes i get this too!!

**Comment by kevohagan** [comment]
this is definitely a bug

**Comment by DevVersion** [comment]
I would not treat this as a bug. 

We are always creating a clone of the subheader element, which causes all directives to be recompiled, because otherwise we will lose all bindings and instances.

- http://codepen.io/DevVersion/pen/bedOwj

**Comment by ThomasBurleson** [comment]
You specified your DDO as an attribute directive. But you are using it as
an element directive?

**Comment by Undrium** [comment]
@ThomasBurleson 

My bad, updated it. This is not the problem, though.

**Comment by DevVersion** [comment]
Tracking with #8647
