### ISSUE TITLE
md-autocomplete in md-toolbar focus problem

### ISSUE THREAD

**Issue by char0n** [angular/material#8538]
**Actual behavior**:
Clicking in md-autocomplete input that is already showing results, hides the results and un-focuses the input.

**Expected behavior**:
Clicking in md-autocomplete input that is already showing results, hides the results and re-focuses the input.

**CodePen** or Steps to reproduce the issue: *
-  http://codepen.io/anon/pen/bpXJJg
-  Details: using md-autocomplete in md-toolbar introduces strange behavior.  This behavior only manifests only in this exact setup, which on mobile devices is default I guess. More info in expected/actual behaviors.

**Angular Versions**: *
-  Angular Version: =1.5.5
-  Angular Material Version: https://github.com/angular/bower-material/archive/v1.0.8-master-05a3a0f.tar.gz

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102 m
-  OS: Wondows 8.1
-  Stack Traces:

----

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
