### ISSUE TITLE
angular material md-tabs pagination don't work when the tabs are aligned to right

### ISSUE THREAD

**Issue by deadpull** [angular/material#8539]
When I aligned md-tabs to the right using this code:

> .my-container .md-tab {
>     float: right;
> } 
> 
> .my-container md-pagination-wrapper {
>     right: 0;
>     left: inherit;
> }
> 

it worked, but the pagination did no work, I see the pagination arrows but they are disabled.

How can I fix this issue?

Thanks

**Comment by ThomasBurleson** [comment]
LOL - awesome name @deadpull.
