### ISSUE TITLE
md-select multiple= true  Place holder sliding over

### ISSUE THREAD

**Issue by ramumesh** [angular/material#8540]
**Actual behavior**:
-  What is the issue? *
When you select and de select md-select(multiple =true), the placeholder sliding over as a shadow
![image](https://cloud.githubusercontent.com/assets/18603613/15511734/6682d70c-21a2-11e6-950a-9297da99af7f.png)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ramumesh** [comment]
Hi Thomas,

Thanks for updating about this issue. But I am sad about that this is a
clear issue which is existing in angular material and you are not taking
care of it. We are already chosen angular material for our development and
in the middle of our project. Now we cannot think of other option.

On Wed, Jun 1, 2016 at 6:58 PM, Thomas Burleson <notifications@github.com>
wrote:

> This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
> For details, see our forum posting <http://bit.ly/1UhZyWs>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/material/issues/8540#issuecomment-223159675>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ARveXVksPTrGyzgW0CP9Hs4SUselvdrTks5qHhyNgaJpZM4IlrSQ>
> .
>



-- 
******just think in every situation ....."Its Possible"*******

with regards Umesh Ram

+91 9847732131
