### ISSUE TITLE
sidenav + ui-router not animating

### ISSUE THREAD

**Issue by nbartley** [angular/material#8544]
**Actual behavior**: 
-  What is the issue? * When triggering sidenav toggles, animation does not work, the panels appear.
-  What is the expected behavior? The toggles should smoothly flow out. 

**Angular Versions**: 
-  Angular Version: 1.5.5
-  Angular Material Version: Master (May 25th, 2016)
-  Angular UI: 0.2.11

Note: This is a duplicate of #3576, as the css fix in there repaired the issue.

**Comment by DevVersion** [comment]
@nbartley I was trying to reproduce this issue by creating my _own_ codepen.

---
It seems like everything works fine with the latest versions.

- http://codepen.io/DevVersion/pen/pbRaQV

If you are still seeing that issue, please provide a working codepen.
