### ISSUE TITLE
make autocomplete navigation circular

### ISSUE THREAD

**Issue by david-gang** [angular/material#8545]
**Actual behavior**:
-  What is the issue? *
When we get autocomplete suggestions we have the abilty to navigate with down arrow. When we get to the bottom of the list we get stuck. 
-  What is the expected behavior?
The focus should get back to the text input and the value should have been what we typed.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
https://material.angularjs.org/latest/demo/autocomplete
-  Details:
Type in ala
Press down till you get at the end.
Press an additional time down and you see that it does not get up.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

The desired behavior is like in the typeahead example:
https://twitter.github.io/typeahead.js/
* write david in the  box
* press down a couple of times till you get to the end of the suggestion list
* press down again and you get to the text input again

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
