### ISSUE TITLE
Autocomplete - Support multiple datassets

### ISSUE THREAD

**Issue by david-gang** [angular/material#8546]
**Actual behavior**:
-  What is the issue? *
It is impossible that the autocomplete will show multiple datasets. 
-  What is the expected behavior?
The autocomplete should give an option to show multiple datasets.This will make it much more powerful

**CodePen** or Steps to reproduce the issue: *
Look at https://twitter.github.io/typeahead.js/examples/
-  CodePen Demo which shows your issue :
-  Details:
Go to Multiple Datasets example
Type A

You will see multiple datasets like here
![capture](https://cloud.githubusercontent.com/assets/1292882/15531186/96c3d0aa-2261-11e6-86b4-7450c5963634.PNG) 

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
