### ISSUE TITLE
Datepicker display issue with box-sizing: border-box

### ISSUE THREAD

**Issue by Akaryatrh** [angular/material#8547]
**Actual behavior**:
-  What is the issue?  
When using a global [`box-sizing`](http://www.paulirish.com/2012/box-sizing-border-box-ftw/) rule, Datepicker component displays an extra space when opened :  

![capture du 2016-05-25 11-22-40](https://cloud.githubusercontent.com/assets/574787/15534984/b5a21e5a-226b-11e6-8e81-92026dd64e81.png)

-  What is the expected behavior?  
Extra space is unwanted

**CodePen** or Steps to reproduce the issue: *
- http://codepen.io/anon/pen/KzEoQy
Just click on first datepicker labelled **Standard date-picker**

**Angular Versions**: *
-  Angular Version: reproduced from 1.4.8 to 1.5.2 (but probably affects all versions)
-  Angular Material Version: reproduced from 1.0.6 to 1.0.8 (maybe affects other versions)

**Additional Information**:
-  Browser Type: Chrome, Firefox, Safari (probably affects other browsers)
-  Browser Version: latests
-  OS: OSX El Capitan + Ubuntu 16.04
-  Stack Traces: none

**Additional issue**:
When clicking on datepicker, an extra space appears down the datepicker. This can be seen on linked codepen demo and even on angular-material documentation page : https://material.angularjs.org/latest/demo/datepicker
Tell me if a separated issue needs to be opened for this.

**Comment by kayvij** [comment]
md-select has the same issue (displays weird backgrounds) when border-box is used on *

e.g.
* {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}

Therefore, using bootstrap along with angular-material causes this issue. 

The following fixes it but screws up bootstrap styling.
* {
    -webkit-box-sizing: unset;
    -moz-box-sizing: unset;
    box-sizing: unset;
}

**Comment by crisbeto** [comment]
@kayvij I couldn't get it to break, event with `box-sizing: border-box !important` on everything. Are you sure you're not using an older version of Material or you have some of your custom CSS being applied?

**Comment by kayvij** [comment]
You are right. That wasn't the issue after all, however it did seem to fix the background issue initially when I removed the border-box styling in developer tools. 

Anyway, it turns out the issue was neither due to bootstrap nor any other styling/component being used, or any material version. 
 
The real culprit was the following angular-material style:

```
html.md-default-theme, html, body.md-default-theme, body {
    color: rgba(0,0,0,0.87);
    background-color: rgb(250,250,250);
}
```

overriding with the following style has fixed the issue:
```
html.md-default-theme, html, body.md-default-theme, body {
    background-color: transparent;
}
```

It now works beautifully :)

Just want to note again that this issue was only in (IE Edge on Windows 10).

Thanks

**Comment by kayvij** [comment]
Just wanted to post the codepens for the issue and the fix. (Issue can be seen only in IE Edge browser in Windows 10)

Issue here: http://codepen.io/anon/pen/BzRjBx

Fix here: http://codepen.io/anon/pen/gwOdNm

**Comment by mgol** [comment]
@kayvij There is no such browser as "IE Edge". Do you mean IE 11 in its default document mode (sometimes called "edge mode") or the Microsoft Edge browser, currently at version 14 of its EdgeHTML engine?

**Comment by kayvij** [comment]
Sorry, Yes **IE 11 and Microsoft Edge** on Windows 10. For some reason I have been calling it IE Edge :)

**Comment by mgol** [comment]
Ah, so both of them. Thanks for the update.
