### ISSUE TITLE
Md-backdrop flicker in Desktop Safari

### ISSUE THREAD

**Issue by xuaninbox** [angular/material#8549]
**Actual behavior**:
-  What is the issue? 

In Safari (desktop) component involving MD-backdrop will flicker on open and close, see the md-select example below.

-  What is the expected behavior? 

No flicker, chrome or firefox and mobile safari

**CodePen** or Steps to reproduce the issue: 

-  CodePen Demo which shows your issue : 

This can only be reproduced on site thats **NOT overflow: hidden**
![1](https://cloud.githubusercontent.com/assets/5108256/15538770/fde6549e-2232-11e6-9274-2d776e067a1b.gif)

-  Details:

For md-autocomplete you can reduce the flicker by setting the md-delay, this make me guess it might be when modifying DOM safari is slower than chrome and other browser.

More specifically, as it jump to top of the page and then back (which is the flickr), I would assume the jump to top is caused by setting position: fixed and then come down because setting Top: XXX px.

**Angular Versions**: 

-  Angular Version:1.5.5
-  Angular Material Version: 1.1.0 RC4 master 0e406a519c

**Additional Information**:

-  Browser Type: *Safari
-  Browser Version: *9.1.1
-  OS: *10.11.5
-  Stack Traces:

**Comment by DevVersion** [comment]
I was trying to reproduce that issue, but it didn't occur to me.

Can you share a demo / codepen, which represents your issue?

**Comment by xuaninbox** [comment]
https://www.tixora.com/event?event_id=E160214&view=tickets

Hey, this the site we are building, u can try the me-select on there

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
