### ISSUE TITLE
md-list: scrollbar not responding in IE 11

### ISSUE THREAD

**Issue by sjaase** [angular/material#8552]
**Actual behavior**:
When scrolling a list of items in md-list (or a list of md-card) by clicking on scrollbar (scroll by page, or scroll by clicking buttons, or dragging scrollbar thumb) Internet Explorer 11 is very little responsive. The more items in the list the worse it gets. However scrolling using mousewheel works just fine.

This issue dosen't occur in Firefox, Edge or Chrome.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: IE11

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
