### ISSUE TITLE
Angular Material theming is making md-select {{foreground-1}} color as #fff

### ISSUE THREAD

**Issue by audiodude** [angular/material#8555]
**Actual behavior**:
-  What is the issue? *
The theme system is creating themes with {{foreground-1}} set to #fff, which makes it impossible to read the text in controls such as md-select.

-  What is the expected behavior?
The theme should generate colors that are readable

The theming code is in the codepen, it produces the following theme:
```
{
  "name": "default",
  "colors": {
    "primary": {
      "name": "youTubeRed",
      "hues": {
        "default": "500",
        "hue-1": "300",
        "hue-2": "800",
        "hue-3": "A100"
      }
    },
    "accent": {
      "name": "googleBlue",
      "hues": {
        "default": "A200",
        "hue-1": "A100",
        "hue-2": "A400",
        "hue-3": "A700"
      }
    },
    "warn": {
      "name": "deep-orange",
      "hues": {
        "default": "500",
        "hue-1": "300",
        "hue-2": "800",
        "hue-3": "A100"
      }
    },
    "background": {
      "name": "grey",
      "hues": {
        "default": "A100",
        "hue-1": "300",
        "hue-2": "800",
        "hue-3": "900"
      }
    }
  },
  "isDark": false,
  "foregroundPalette": {
    "1": "rgba(0,0,0,0.87)",
    "2": "rgba(0,0,0,0.54)",
    "3": "rgba(0,0,0,0.26)",
    "4": "rgba(0,0,0,0.12)",
    "name": "dark"
  },
  "foregroundShadow": ""
}
```

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/audiodude/pen/ezOGGQ
-  Details: It doesn't show the issue

**Angular Versions**: *
-  Angular Version: 1.4
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

**Comment by clshortfuse** [comment]
Maybe I'm not understand the issue, but I can't reproduce this with the codepen. Also, as far as I know, the conditions for `{{foreground-1}}` to set to `#fff` is for the palette to specified as `.dark()`

**Comment by audiodude** [comment]
You can close it as not reproducible. Like I said, I copied my theming code to the codepen, but it doesn't seem to reproduce there (but it's definitely happening in my app).

**Comment by clshortfuse** [comment]
@audiodude Sorry you're having issues. 

There are couple of PRs in the pipeline that deal with foreground and contrast colors, so hopefully this can solve your issue. If you can find a way to recreate this is issue in a reproducible state, feel free to add a comment here.
