### ISSUE TITLE
md-datepicker on android and chrome not showing numbers in current HEAD 1.1.x

### ISSUE THREAD

**Issue by dohomi** [angular/material#8557]
**Actual behavior**:
-  What is the issue? 
On Android phones the `md-datepicker` component shows only a white dialog box without any numbers. Scrolling is not working at all, the datepicker closes automatically. It is not possible to select any date.
-  What is the expected behavior?
Showing all numbers as expected on other devices

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
https://material.angularjs.org/HEAD/demo/datepicker
-  Details:
Open this page with my Sony XPeria 

**Angular Versions**: *
-  Angular Version: 1.5.x
-  Angular Material Version: 1.1.rc-x

**Additional Information**:
-  Browser Type: Chrome Android
-  Browser Version: Chrome 50.0.2661.89
-  OS: Android 5.1.1

**Comment by mckenzielong** [comment]
>component shows only a white dialog box without any numbers

This is also happening on desktop if you can position the datepicker near the bottom of the screen.

**Comment by crisbeto** [comment]
I'll have a fix for it as a part of https://github.com/angular/material/pull/8541, but I'm trying to fix another issue before that.

**Comment by xuaninbox** [comment]
Having the same problem but on desktop, where the date picker is in an md-dialog, the ui is a bit off.

<img width="558" alt="1" src="https://cloud.githubusercontent.com/assets/5108256/15575830/b4b154cc-2309-11e6-9350-b40ffcb41e63.png">

**Comment by crisbeto** [comment]
@xuaninbox do you happen to have `box-sizing: border-box` applied to the calendar?

**Comment by xuaninbox** [comment]
@crisbeto Yep ur right! Thanks!

**Comment by crisbeto** [comment]
Great, thanks for confirming. There's an issue to address this as well.

**Comment by xuaninbox** [comment]
@crisbeto 
.md-virtual-repeat-sizer
.md-virtual-repeat-offsetter 

actually have box-sizing: border-box; so have to overwrite that too to fix the shadow thing on the right.
