### ISSUE TITLE
Change Date Picker - Date Format Dynamically Issue

### ISSUE THREAD

**Issue by arvigenio** [angular/material#8559]
In our current sprint, there is a feature that will enable the user to choose his/her preferred date format. However, there is no option in angular material will update the date format on the fly, you still have to configure it during configuration phase and also during config phase there is no way to inject a service/provider to fetch user preferences. Can somebody help me? Thank you!

**Comment by crisbeto** [comment]
You can still determine what format to use within your function.

**Comment by arvigenio** [comment]
Hi Crisbeto, can you please provide a code snippet for this? Thank you!

**Comment by crisbeto** [comment]
Here's some pseudo-code.

```js
$mdDateLocaleProvider.parseDate = function(dateString) {
  if (userPreference === 'option 1') {
    // return formatting here
  } else if (userPreference === 'option 2') {
     // return some outher formatting here
  }

  // return default formatting here
};
```

**Comment by crisbeto** [comment]
Something like this should work, but I can't run it right now:

```js
angular.module('material.components.datepicker').config(['$provide', function($provide){
    $provide.decorator('$mdDateLocale', ['$delegate', function($delegate){
        // override the $delegate.parseDate method here. you can inject anything that is 
        // available after config.
        return $delegate;
    }]);
}]);
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by devotis** [comment]
I've worked out a full example on SO: http://stackoverflow.com/questions/32566416/change-format-of-md-datepicker-in-angular-material/43409002#43409002
