### ISSUE TITLE
md-scroll-shrink in secondary toolbars

### ISSUE THREAD

**Issue by char0n** [angular/material#8561]
**Actual behavior**:
-  What is the issue? 
Secondary toolbar doesn't behave as expected when using md-scroll-shrink directive. You have to wait exactly 6 seconds for scrollshink efect to kick in (no idea why). Additional scrollbar appears and the entire page become scrollable, instead of only md-content. Then the scroll shrink effect works, but instead of sliding under primary toolbar, it slides right over it. When it overlays the primary toolbar completely, the secondary scrollbar (which scrolls entire page) disappears.

-  What is the expected behavior?
Secondary toolbar slides under primary, no additional scrollbars appears and shrink scroll effect kicks in immediately, not after 6 seconds.

**CodePen** or Steps to reproduce the issue: *
-  http://codepen.io/anon/pen/xOKzYo

-  Details:
Simple layout, using left sidenav, primary and secondary toolbar and md-content.

**Angular Versions**: 
-  Angular Version: 1.5.5
-  Angular Material Version: v1.1.0-rc4-master-e588df9

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102 m
-  OS: Windows 8.1
-  Stack Traces:

----

**Comment by crisbeto** [comment]
https://github.com/angular/material/pull/8543 should help with this. Can you try testing with the code we have in HEAD?

**Comment by char0n** [comment]
@crisbeto updated angular-material to v1.1.0-rc4-master-e588df9

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
