### ISSUE TITLE
md-toast doesn't clean its css styles

### ISSUE THREAD

**Issue by char0n** [angular/material#8562]
**Actual behavior**:

-  What is the issue? 
md-toast when opened on xs and sm screen sizes, applies position: relative css rule to element defined by parent() method. After toast closes it doesn't clean up this position: relative rule. This causes md-sidenav not to overlay the primary toolbar (which it should).

-  What is the expected behavior?
md-toast cleans-up css rules after it disappears.

**CodePen** or Steps to reproduce the issue: 
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/bebKPv

-  Details:

1. resize window to sm size
2. open side menu (should overlay primary toolbar)
3. trigger toast by clicking on "OPEN TOAST" button
4. open side menu again (not overlaying primary toolbar any more)

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: https://github.com/angular/bower-material/archive/v1.1.0-rc4-master-2806ec8.tar.gz

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102 m
-  OS: Windows 8.1
-  Stack Traces:

----

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
