### ISSUE TITLE
md-autocomplete with md-no-cache and an ajax request goes into an infinite loop wnen second character is typed

### ISSUE THREAD

**Issue by alan-hobbart** [angular/material#8563]
**Actual behavior**:
-  What is the issue? *
md-autocomplete with md-no-cache and an ajax request goes into an infinite loop wnen second character is typed

-  What is the expected behavior?
single ajax search for each key press, not an infinite loop of ajax requests afther second character

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:
 <md-autocomplete required md-input-name="entityCode"
                         md-selected-item="$ctrl.ngModel"
                         md-search-text="$ctrl.searchText"
                         md-items="item in $ctrl.querySearch($ctrl.searchText)"
                         md-item-text="item.name"
                         md-floating-label="Search for Entity"
                         md-selected-item-change="$ctrl.selectedItemChange(item)"
                         md-no-cache="true"
                         md-delay="300">
            <md-item-template>
                <span md-highlight-text="$ctrl.searchText" md-highlight-flags="i">{{item.name}} ({{item.code}})</span>
            </md-item-template>
            <div ng-messages="searchText.$error">
                <div ng-message="required">This field is required</div>
            </div>
            <md-not-found>
                No matches found.
            </md-not-found>
        </md-autocomplete>

 function querySearch(query) {
            var familyEntityTypesUrlParam = vm.familyEntityTypes.join(',');
            var url = 'api/Entities/Search/' + query + '/' +
                familyEntityTypesUrlParam + '/' +
                config.apiDataReadySearchMaxResults;
            var encodedUrl = encodeURI(url);
            
            console.log('search was run for' + url);

            return dataservice.getData({
                dataUrl: encodedUrl,
                useDataReadyApi: true
            });
        }

**Angular Versions**: *
-  Angular Version: 1.5
-  Angular Material Version: 1.08

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by chunyenHuang** [comment]
I have a fix in PR #10916
