### ISSUE TITLE
test(dialog): focus trap should redirects focus to the md-dialog element

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#8565]
Find a way to test that focusing the traps redirects focus to the md-dialog element. Firefox is problematic here, as calling element.focus() inside of a focus event listener seems not to immediately update the document.activeElement.
This is a behavior better captured by an e2e test.

> originally written by @jelbourn [here](https://github.com/angular/material/blob/master/src/components/dialog/dialog.spec.js#L1355-L1358)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
