### ISSUE TITLE
mdDatePicker - Calendar Icon Placement

### ISSUE THREAD

**Issue by erslater** [angular/material#8569]
The datepicker currently has the calendar icon on the left which is uncommon.  Most controls have the icons on the right. 

There are a few possible scenarios:
1. The calendar appears on the right instead of the down arrow as the default.
2. There is an option of showing it on the right instead of the down arrow.
3. There is an option of showing it on the right beside the down arrow. (Less ideal).

Thanks for your consideration.

**Comment by sdesmond** [comment]
See also #8481

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
