### ISSUE TITLE
Angular material Select

### ISSUE THREAD

**Issue by aveshnaik007** [angular/material#8574]
There is a problem in your material select drop down.
the List is not visible and creates problem on webpage.
Same happens on your documentation page.

**Comment by BigEgg** [comment]
+1

**Comment by KjartanDestino** [comment]
+1
![image](https://cloud.githubusercontent.com/assets/10369990/15599951/47ffee72-23e7-11e6-898c-b09e9e3ac9e1.png)

**Comment by ErinCoughlan** [comment]
If you switch off of latest to 1.0.8 or HEAD, the site will look correct again. We are working to fix the Latest version.

**Comment by ThomasBurleson** [comment]
Fixed.
