### ISSUE TITLE
Enchancement: Add attribute to <md-sidenav> directive to allow for the "greyed out" md-backdrop to be optional.

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#8577]
**Actual behavior**:
-  What is the issue? When the sidenav appears, a backdrop greys out the rest of the window. It would be great if this behavior was optional.
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/cmacdonnacha/pen/gMOYWr
-  Details: Click on "Toggle Right"

**Angular Versions**: *
-  Angular Version: 1.5
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102 m
-  OS: Windows 7 SP1
-  Stack Traces:

![image](https://cloud.githubusercontent.com/assets/9777763/15606118/10246030-2402-11e6-9479-27cae878f2f5.png)

**Comment by DevVersion** [comment]
We're currently supporting the `md-disable-backdrop` attribute, which completely removes the backdrop.

I guess, you still want to be able to click on the (transparent) backdrop, to close the sidenav?

If so, then I propose to manually overwrite the color of the `sidenav` backdrop.

**Comment by cmacdonnacha** [comment]
Thanks for your reply. 

> I guess, you still want to be able to click on the (transparent) backdrop, to close the sidenav?
Yea you're correct there. Do you know which class I'd need to overwrite?

**Comment by DevVersion** [comment]
The class is `md-sidenav-backdrop`, which will be used for every sidenav's backdrop.

I don't think we will support any attribute / property to set the backdrop to transparent. 
This depends on the users application and color changes should be done with some custom css.

**Comment by cmacdonnacha** [comment]
Perfect thanks!
