### ISSUE TITLE
md-tabs dynamic height is calculated from the height of internal tab

### ISSUE THREAD

**Issue by leogdsl** [angular/material#8579]
When a dynamic height is used and a tab contains tabs internally this causes the high is calculated incorrectly when you switch between tab. 

Demo:

http://codepen.io/leogdsl/pen/dXyoNx

**Comment by ThomasBurleson** [comment]
Pull Requests are welcomed. Closing for now as the core team will not fix.

**Comment by stunaz** [comment]
Nested tabs are not supported
https://github.com/angular/material/issues/3703#issuecomment-137818694
