### ISSUE TITLE
Angular material MD-TAB not working when i swipe and click on it ,

### ISSUE THREAD

**Issue by bhandaribhumin** [angular/material#8583]
swipe working good before i  click on tab after click on tab it will not work , i dont know how it works but please help me how i work on tab swipe with click work proper with dynamic tab and tab content data.
i'll send  sample video it's shows  when i swipe tab left and right it will work but if i click on tab swipe not works

Video file :

https://drive.google.com/open?id=0B0qdA1kUoM_haGV0ZHAxYzViWkk

my controller.js is
$scope.selectedIndex = 0;
$scope.onSwipeLeft = function(){
 
 if($scope.selectedIndex < $scope.categoryList.length){
   
$scope.selectedIndex = $scope.selectedIndex + 1;
//alert($scope.selectedIndex);
}

};
$scope.ClickTab = function(){
 alert($scope.selectedIndex+1);

};

$scope.onSwipeRight = function(){
  //alert($scope.selectedIndex);
if($scope.selectedIndex != 0) {
$scope.selectedIndex = $scope.selectedIndex - 1;
}
}

------------and html is

  <md-tabs class="ng-hide tabs-assertive  tabs-top " ng-class="{'tabs-super-top': data > 85, 'tabs-top': data < 85}"  md-swipe-left="onSwipeLeft()" md-swipe-right="onSwipeRight()" ng-click="ClickTab()" md-selected="selectedIndex"  ng-show="!loading" md-dynamic-height md-border-bottom md-swipe-content="true">
            <md-tab label="For you">
                
                <md-content id="social-profile-content" class="">

                    
        <div id="product-list" class="row">
            <div class="col"  >
                <div  ng-repeat="you in arroundYou" ng-click="goToDealList()"  class="cube-item" style="background-image: url({{you.image_url}});">
                    <h1>
                    {{you.category_name}}
                    </h1>

                    <p>
                       {{you.deal_in_category}}
                    </p>
                </div>
            </div>
           
        </div>

                </md-content>

            </md-tab>
            <md-tab  ng-repeat="cat in categoryList" label="{{cat.name}}"  md-swipe-right="next1()" >
                <md-content >
                    
                    <div id="product-list" class="row">
            <div class="col"  >
                <div  ng-repeat="you in arroundYou" ng-if="you.category_id == cat.id" ng-click="goToDealList()"  class="cube-item" style="background-image: url({{you.image_url}});">
                    <h1>
                    {{you.category_name}}
                    </h1>
                    <p>
                       {{you.deal_in_category}}
                    </p>
                </div>
            </div>
           
        </div>
                </md-content>
            </md-tab>
           
             
        </md-tabs>

**Comment by graphefruit** [comment]
@bhandaribhumin Please layout your CSS/JS better, its realy hard to read.
The solution looks like:
HTML:
```
<md-content class="flex">
    <md-tabs md-selected="tabs.selectedIndex">
        <md-tab label="Tab1">
            <md-content md-swipe-left="tabs.next()" md-swipe-right="tabs.previous()">Tab1 - Content</md-content>
        </md-tab>
        <md-tab label="Tab2">
            <md-content md-swipe-left="tabs.next()" md-swipe-right="tabs.previous()">Tab2 - Content</md-content>
        </md-tab>
    </md-tabs>
</md-content>
```
    
JS:
```
$scope.tabs = {
        selectedIndex: 0,
        next: function () {
            $scope.tabs.selectedIndex = Math.min($scope.tabs.selectedIndex + 1, 1);
        },
        previous: function () {
            $scope.tabs.selectedIndex = Math.max($scope.tabs.selectedIndex - 1, 0);
        }
    };
```

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
