### ISSUE TITLE
md-sidenav IE 9 not appearing

### ISSUE THREAD

**Issue by soumya2080** [angular/material#8584]
In IE 9 the sidenav is not appearing.

**Comment by graphefruit** [comment]
@soumya2080  IE9 and IE10 is not supported by AM

**Comment by DevVersion** [comment]
As @graphefruit said, we're not supporting IE9 officially. 
To get some help, you may ask in the ngMaterial Google Group.

- [Angular Material Group](https://groups.google.com/forum/#!forum/ngmaterial)
