### ISSUE TITLE
Any plans to implement loading indicator in buttons?

### ISSUE THREAD

**Issue by sgerace** [angular/material#8588]
I was wondering if there are any plans to support in-button loading indicators, similar to http://remotty.github.io/angular-ladda/ 

I find that this is a great way to indicate indeterminate progress for forms, and it seems like it adheres to the general Material Design guidelines.

**Comment by ThomasBurleson** [comment]
This will be a nice addition for ngMaterial2... will not be part of ngMaterial1.

**Comment by kid-icarus** [comment]
Curious as to why you've categorically rejected loading indicators in buttons as part of ngMaterial1. In general, how are components determined to be rejected or accepted as part of ngMaterial1?

For instance, the md-nav-bar and md-panel components were released in March. Why weren't those determined to be accepted into ngMaterial1 but not a loading indicator button?

Or is this sentiment part of a larger push to get users to migrate to Angular 2? 😕

**Comment by richardaum** [comment]
@kid-icarus exactly, this effort is happening because of ng2. they talked about it in some place.

**Comment by ThomasBurleson** [comment]
@kid-icarus - Pull Requests to resolve this issue are encouraged! Note, however, that Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
