### ISSUE TITLE
Dolphin Browser Compatibility

### ISSUE THREAD

**Issue by SirLouen** [angular/material#8590]
Anyone has experience issues with dolphin browser compatibility? I've found since is based in latest webkit, it should run perfectly, but we found multiple issues relating with css3 flexible boxes. 

Anyone has tested this out?

**Comment by DevVersion** [comment]
This is actually not an issue in ngMaterial.

----
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
