### ISSUE TITLE
$mdDialog.confirm() displays {{DIALOG.OK}} in Microsoft Edge 

### ISSUE THREAD

**Issue by zalcyon** [angular/material#8591]
**Actual behavior**:
-  What is the issue? *
The $mdDialog.confirm() displays {{ DIALOG.OK }} as the confirm text, only and only in Microsoft Edge when the string contains the substring 'Instance'.
-  What is the expected behavior?
Display the actual text, not {{ DIALOG.OK }} 

**CodePen** or Steps to reproduce the issue: *
http://codepen.io/anon/pen/KMKxbM
-  CodePen Demo which shows your issue :
In the codepen example delete or change the string instance and the text will be displayed properly
-  Details:

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: * Microsoft Edge
-  Browser Version: * 25.105
-  OS: * Microsoft Windows 10 x64
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo]
(http://codepen.io/anon/pen/KMKxbM).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by zalcyon** [comment]
Update: It can solved it by adding a space character after the text.

**Comment by DevVersion** [comment]
I can reproduce that issue. It's actually a bug in Microsoft Edge.

Microsoft Edge is not reflecting the DOM correctly into the view, when the element has `text-transform: uppercase` applied. 

By removing the `text-transform` css property, everything will work as expected.

**Comment by ThomasBurleson** [comment]
Closing as 'not-issue' for ngMaterial.
