### ISSUE TITLE
md-select-header : Search Fails and md-optgroup label appears when ng-if is used to show/ hide md-select-header

### ISSUE THREAD

**Issue by surabhin** [angular/material#8592]
When `ng-if` is used as a condition to show/ hide `md-select-header`, the ability to search options fails, `md-optgroup` label appears in select box and throws error saying, `Error: <md-input-container> can only have *one* <input>, <textarea> or <md-select> child element!`

This issue doesn't appear when `ng-show` or `ng-hide` is used on `md-select-header` instead of `ng-if`.

**CodePen** : http://codepen.io/surabhi/pen/oLNaoR

**AngularJS version** -1.4.8
**Angular Material version** - 1.1.0-rc4

Issue exists in all browsers and OS.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
        For details, see our [forum posting](http://bit.ly/1UhZyWs).

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
      For details, see our forum posting @ http://bit.ly/1UhZyWs.
