### ISSUE TITLE
How to i add nav in slider and when i scroll then show toolbar with back button

### ISSUE THREAD

**Issue by bhandaribhumin** [angular/material#8597]
when i click on category view new page and  show full details with slider image of products like below images 
how do i implement on my  project please help me 
https://drive.google.com/open?id=0B0qdA1kUoM_hYmpZM2lzZVRSZ3c
https://drive.google.com/open?id=0B0qdA1kUoM_heHRzUDdxbzU2QjA
https://drive.google.com/open?id=0B0qdA1kUoM_hQVJ2eUNRMExaSm8

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
