### ISSUE TITLE
$mdDialog doesn't work correctly when have scrollbar

### ISSUE THREAD

**Issue by marcomafessolli** [angular/material#8602]
**Actual behavior**:
-  When the browser/container have a scrollbar $mdDialog doesn't work properly, creating some kind of "mask" at the bottom of the browser. 

**CodePen**
-  http://codepen.io/marcomafessolli/pen/pbvyLW

**Angular Versions**: 
-  Angular Material Version: Master

**Additional Information**:
-  Browser Type: Tested on Chrome and Safari
-  OS: MacOS

**Comment by crisbeto** [comment]
Seems like I introduced this with https://github.com/angular/material/pull/8349, I'll look into it.

**Comment by marcomafessolli** [comment]
@crisbeto This problem seems to occurs with autocomplete component too.
