### ISSUE TITLE
md-select inside an md-tab

### ISSUE THREAD

**Issue by jbonigomes** [angular/material#8607]
Hi there,

I am having an issue when nesting an md-select with a search input inside an md-tab directive.

There are two problems:

1. Once the select box expands, one has to scroll up to view the search input
2. The search input does not actually accept any text

I made a [codepen](http://codepen.io/jbonigomes/pen/zBxEYP) to illustrate better what I mean:

Angular.js 1.5.3
Angular-material 1.0.9

Thanks

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
