### ISSUE TITLE
$mdMedia 'landscape' and 'portrait'

### ISSUE THREAD

**Issue by davidenke** [angular/material#8609]
The `$mdMedia` service should return boolean for `landscape` and `portrait`. Changes in the layout may can be reflected by the corresponding css media queries, but it would be more consistent to assign e.g. class names with ng-styles in the templates using this service.

**Comment by ThomasBurleson** [comment]
@davidenke - great idea. Please provide a pull request; at which time this issue will be reopened.

> This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
For details, see our [forum posting](http://bit.ly/1UhZyWs).
