### ISSUE TITLE
html, body css conflicts with other libraries

### ISSUE THREAD

**Issue by gilm0079** [angular/material#8610]
We also use Kendo UI controls from Telerik.  There is a style block in the angular-material stylesheet that causes positioning on the Kendo control's popups to be thrown off.  I commented this out in angular-material stylesheet and it doesn't have any affect on the button controls we are using.  Is this block used for another reason?  Just asking if this is something that can be removed from a future build if it is not needed.  Since it attaches to the html/body elements it would affect ALL page styling and not just items related to angular-material.

With regards to the conflict with the Kendo UI controls this also ONLY affected the Kendo UI controls when rendering for a mobile device.  Desktop and iPad were not affected.  Kendo support pointed me toward this style as the cause which I confirmed.

```
html, body {
  height: 100%;
  position: relative; 
}
```

**Comment by ThomasBurleson** [comment]
We will not change this for ngMaterial1; but this issue will be considered as part of ngMaterial2. 

> This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
For details, see our [forum posting](http://bit.ly/1UhZyWs).
