### ISSUE TITLE
[feature] mdSlider: support for range sliders

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/material#8613]
This is a "re-open" of deprecated issue #487 due to the high demand for that feature.
 
Please consider adding a range (second value) option to md-slider.

Example use case: when searching for a hotel, I want to specify both minimum and maximum price, and have the application show me results that fall between those. Demonstrated in AirBnB search page.

This feature has been previously implemented in
* https://github.com/Venturocket/angular-slider
* http://angular-ui.github.io/ui-slider/demo/demo.html

**Comment by ThomasBurleson** [comment]
@DmitryEfimenko - you are welcome to provide a Pull Request with this enhancement. And we can reopen this issue at that time. Meanwhile, the core team will not work on this. 

> This issue is closed as part of our ‘Surge Focus on Material 2' efforts.
For details, see our [forum posting](http://bit.ly/1UhZyWs).
