### ISSUE TITLE
md-datepicker: doesn't show calender pane when within ng-repeat

### ISSUE THREAD

**Issue by gasserus** [angular/material#8618]
**Actual behavior**:
- md-datepicker does not show the calendar pane, when the datepicker is in ng-repeat and out of the actual sight.

- When I remove the disableScrollAround function it works as expected
```
DatePickerCtrl.prototype.openCalendarPane = function(event) {
...
-> this.$mdUtil.disableScrollAround(this.calendarPane);
...
}
```

Steps to reproduce the issue: *
- Create md-datepicker within ng-repeat
- Make sure you have to scroll down to see the datepicker

**CodePen**:
[CodePen](http://codepen.io/gasserus/full/mEyvPg/)

**Angular Versions**: *
-  Angular Version: v1.5.6
-  Angular Material Version: v1.1.0-rc4-master-ce07651

**Additional Information**:
-  Browsers: Google Chrome (51.0.2704.63), Safari (9.1.1)
-  OS: Mac OS X 10.11.5

**Comment by crisbeto** [comment]
At first glance this seems to be the same issue as https://github.com/angular/material/issues/8602, but I'll take a better look later. There's a fix pending for it at https://github.com/angular/material/pull/8611.

**Comment by gasserus** [comment]
#8611 solves this issue
