### ISSUE TITLE
md-button inside md-menu does not support flex in firefox

### ISSUE THREAD

**Issue by pratikborsadiya** [angular/material#8619]
-  Firefox does not support display: flex on buttons ([bugzila-bug](https://bugzilla.mozilla.org/show_bug.cgi?id=984869)).

- The issue is with md-menu when inside md-menu we use menu item with icon icon and text are not aligned [Docs page demo. See the first menu](https://material.angularjs.org/latest/demo/menu)

- i understand that it's a mozila bug to not to support display : flex on buttons but can't you make it &lt;a&gt; tag instead of button tag

- i can use &lt;a&gt; tag instead md-button but the issue in that is it does not remain keyboard accessible.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 560474f705af750022b5cb07a8102c6ad490aec3
