### ISSUE TITLE
filter-selected for md-contact-chips

### ISSUE THREAD

**Issue by jbonigomes** [angular/material#8621]
Hi All,

Has the 'filter-selected' option been deprecated on 'md-contact-chips'? If so, how can I filter out the elements that have already been selected from the dropdown list?

Angular.js: 1.5.6
Angular Material: 1.0.9

Thanks

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
