### ISSUE TITLE
Datepicker formats supported

### ISSUE THREAD

**Issue by slimovic** [angular/material#8625]
Hello,

Based on the [Datepicker demo](https://material.angularjs.org/latest/demo/datepicker) I found an issue by entering a date manually.

Those formats are supported:
- dd/mm/yyyy
- dd-mm-yyyy
- yyyy/mm/dd

This format is not supported(it reduce one day in the model, the time zone is correct, See screenshots)
- yyyy-mm-dd

**1. Screenshot 1**

![2016_06_02_10_34_48_settings](https://cloud.githubusercontent.com/assets/8292262/15748891/74048476-28ae-11e6-902c-2f1382a8d4ff.png)

**2. Screenshot 2**
![2016-06-02 10_36_55-basic usage](https://cloud.githubusercontent.com/assets/8292262/15748894/78d88024-28ae-11e6-816e-1051d07fae68.png)

Thank you.

**Comment by slimovic** [comment]
This problem is related to Date.parse

A [helpful link](http://stackoverflow.com/questions/2587345/why-does-date-parse-give-incorrect-results).

**Comment by slimovic** [comment]
This issue happens when your browser time zone  is **GMT-_X_**. Im in north America, I have GMT-0400, for the example in the screenshot(2016-06-02), javaScript will handle that as **Wed Jun 01 2016 20:00:00 GMT-0400 (Eastern Daylight Time)**, for this reason it shows in the calendar is June first.

Any luck to make datepicker handle that?

**P.S:** This date format(yyyy-mm-dd) is **ISO 8601**

**Comment by ThomasBurleson** [comment]
You are welcome to submit a PR to enhance the current datePicker. We can reopen this issue at that time. Otherwise this feature will be relegated to ngM2.
