### ISSUE TITLE
md-select should not allow disabled options to be selected

### ISSUE THREAD

**Issue by barunprasad** [angular/material#8626]
**Actual behavior**:*
-  What is the issue? When using the keyboard, any disabled option in the md-select control can be selected. 
-  What is the expected behavior? Any disabled option in the md-select options should not be allowed to be selected either by using a mouse or the keyboard.

**CodePen** or Steps to reproduce the issue:* 
-  CodePen Demo which shows your issue : http://codepen.io/barunprasad/pen/ezNYvQ .
This codepen is copied from the the demo site of the md-select angular material.
-  Details:In the codepen, States "AK" and "AR" are disabled. When using the mouse, we are not able to select the disabled options which is fine. But when using the keyboard, we are able to select the disabled options.

**Angular Versions**: *
-  Angular Version:1.5.6
-  Angular Material Version:1.1.0-rc4

**Additional Information**:
-  Browser Type: * Chrome
-  Browser Version: * 50.0.2661.102
-  OS: * Windows 7 Professional
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
@barunprasad We can't seem to reproduce this issue (via your Codepen) on Chrome for Win 8, OS X or Win 7 (using BrowserStack).

Can you give some additional information on how to reproduce? Also, can you test against the latest RC5 release to see if it has already been resolved?

_Specifically, in your Codepen, using the arrow keys on the keyboard skips over the disabled items so you can't select them._

**Comment by barunprasad** [comment]
@topherfangio I have updated the CodePen to use RC5 and the issue is still there.
To reproduce the issue, use the keyboard TAB to have the focus on the state field and then type the disabled options (AK or AR) using the keyboard. Using the arrow keys, it works fine

**Comment by topherfangio** [comment]
@barunprasad Ah, gotcha! I didn't try typing the option's, I just tried the arrow keys. I definitely see the issue now. Thanks!
