### ISSUE TITLE
md-card image height

### ISSUE THREAD

**Issue by Jays0nnn** [angular/material#8628]
**Actual behavior**:
-  What is the issue? * When sourcing an image locally inside md-card, the height of the image is automatically set to 100% !important, which breaks the element.
-  What is the expected behavior? The image height should remain auto, so the element wouldn't break.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : I copied and paste the same code that I have written locally, to CodePen which worked totally fine. Although my local version is still broken.
-  Details:

**Angular Versions**: *
-  Angular Version:1.5.6
-  Angular Material Version:1.1.0-rc4

**Additional Information**:
-  Browser Type: *Chrome
-  Browser Version: *51.0.2704.63
-  OS: *Mac Book Pro
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
There's a fix for it at #8653.
