### ISSUE TITLE
CSS issue in IE11

### ISSUE THREAD

**Issue by maxhan247** [angular/material#8629]
1. In the nav sidebar on https://material.angularjs.org/latest/
When click the button, it shows snow noise on IE11, Edge also has this problem but it seldom appear. 
![ie11](https://cloud.githubusercontent.com/assets/19585802/15761189/b4dc2cde-28cb-11e6-8575-1ca850bf2105.gif)

2. The layout for user icon is not right.
![user](https://cloud.githubusercontent.com/assets/19585802/15760547/94547866-28c8-11e6-86b6-343fea46baf0.PNG)

3. It is really slow when I open the demo use IE11 for every operations in sometime. 
![slow](https://cloud.githubusercontent.com/assets/19585802/15760813/d926aa08-28c9-11e6-8892-f0de5cf8204c.gif)
![slow2](https://cloud.githubusercontent.com/assets/19585802/15760921/6704fc80-28ca-11e6-8be6-f3968f93c466.gif)

4 Cards are not aligned.
Works on Safari and Chrome, not on Firefox, Edge, IE11
![edge](https://cloud.githubusercontent.com/assets/19585802/15762864/0181aeac-28d5-11e6-8c06-cc8e11d2cb31.PNG)
![firefox](https://cloud.githubusercontent.com/assets/19585802/15762863/0180fff2-28d5-11e6-9c72-8cc8ab52f2ca.PNG)

**Additional Information**:
![ie11-version](https://cloud.githubusercontent.com/assets/19585802/15760392/d783f5ae-28c7-11e6-927a-37c548da7c39.PNG)

-  Browser Type: Internet Explorer
-  Browser Version: 11.306.10586.0
-  OS: Windows 10 Home ver 1511

**Comment by crisbeto** [comment]
I couldn't reproduce the white noise issue, but the rest are definitely there.
