### ISSUE TITLE
$mdSidenav: Add docs

### ISSUE THREAD

**Issue by epelc** [angular/material#863]
Currently `$mdSidenav` service is only partially documented through the `md-sidenav` example found [here](https://material.angularjs.org/#/api/material.components.sidenav/directive/mdSidenav). However the example does not mention the `isOpen()` function and possibly other features(I havn't looked at the source yet). It also doesn't describe it's usage or even existence besides using `$mdSidenav('component-id').toggle()` several times in the example.

**Comment by ajoslin** [comment]
Related: #1311
