### ISSUE TITLE
Accordion + Expando

### ISSUE THREAD

**Issue by PhilLaFayette** [angular/material#8631]
**Actual behavior**:
-  What is the issue? 

As per [https://groups.google.com/forum/#!topic/ngmaterial/4ActiQp3nA0](https://groups.google.com/forum/#!topic/ngmaterial/4ActiQp3nA0): 

> But if we missed something important, we hope you'll file a new open issue (citing the closed one) and providing a repro case. We'll clarify our reasoning and reconsider the issue on the new list of current issues.

And per https://github.com/angular/material/issues/1861:

> ThomasBurleson commented on Jun 4, 2015
> We are currently hyper-focused on a summer release for Angular Material v1.0; which will include Menu and DateTimePicker components, performance enhancements, bug fixes, and improved documentation.
> 
> **The Expando and Accordion features are definitely on our roadmap but not critical to a v1.0 Beta candidate. Time-permitting, a demo of this feature will be posted on CodePen.**
> 
> We are locking this issue for now... it will remain an open issue, but locked to future discussions. Please future discussions in the Angular Material Forum

This was almost exactly **1 year ago.** Both features had much support in the comments, and they seem like core features to have for a proper UI. We want to use Material, not Bootstrap!

Requesting a reopening for what seems like two features which should/would be extensively used.
-  What is the expected behavior?

Follow through, or enlist more help from the community.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : N/A
-  Details: N/A

**Angular Versions**: *
-  Angular Version: 1.x
-  Angular Material Version: 1

**Additional Information**:
-  Browser Type: All
-  Browser Version: All
-  OS: All
-  Stack Traces: N/A

**Comment by antoinebrault** [comment]
Closed the previous issue for no reason. https://github.com/angular/material/issues/985

**Comment by ThomasBurleson** [comment]
Refs #1861: Material Accordion 
Refs #985:  mdList: Expando feature needed

> A pull request [from the community] with this feature would be welcomed.

**Comment by ThomasBurleson** [comment]
Related to mdList improvements.

**Comment by DevVersion** [comment]
@ThomasBurleson Should this go in after the List Refactoring (#8482)? I propose before, because the list is quite stabilized now.

**Comment by manish2535** [comment]
Any updates on this @ThomasBurleson? Thanks.

**Comment by Splaktar** [comment]
The related issues were already closed in the deprecation. It's not good that we've left this feature request open for so long. At this time we do not plan to implement any additional features in AngularJS Material. We'll only be adding minor enhancements to existing components.

If this feature is critical to you, Angular Material has an [Expansion Panel](https://material.angular.io/components/expansion/overview) that may meet your needs and it is possible to run both AngularJS Material and Angular Material in the same app using [ngUpgrade](https://angular.io/guide/upgrade-performance).
