### ISSUE TITLE
ngMessages disappear using Angular Material

### ISSUE THREAD

**Issue by mg-13** [angular/material#8635]
There seems to be a bug in angular material causing the ng-messages to disappear in an unexpected way.

Applying ng-messages and validation to a form, the error messages do not show up properly when both `required` and `minlength` are set. The user remains confused about why his input is invalid.

**Plunker:** 
https://plnkr.co/edit/7omwpbT3Y5h9VoasVMX4?p=preview

steps to reproduce:
- focus and unfocus the field, "required" pops up
- enter "abcde", "required" disappears, but the field stays invalid until "e" (minlength=5) is entered. The minlength message is NOT showing up to indicate why the input is invalid
- delete "e", now the minlength message appears, as ist should
- delete the rest, the "required" message does NOT show up. 
- "required" will only show up if entering and deleting the whole string at once (select all, delete)
- disable angular material and it works as expected

**Angular Versions**: 
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc2

**Additional Information**:
-  Browser Type: Firefox
-  Browser Version: 46.0.1
-  OS: Windows 7

**Comment by mpiasta-ca** [comment]
Not fixed in 1.1.0-rc4 either. But the error has definitely been kicking around git issues for a while now. Hopefully it didn't get closed in the Material2 priority sweep.

**Comment by mg-13** [comment]
The problem is not about multiple error cases but especially the combination of `minlength` and `required`.
However, I figured out from that demo the attribute `md-auto-hide` is set to `false` for `ng-messages`, that did the job actually...

**Comment by DevVersion** [comment]
@ThomasBurleson I also had a PR for that, but @topherfangio said, that he is already working on that.

**Comment by topherfangio** [comment]
@ThomasBurleson @DevVersion Indeed I have a branch that fixes it, but we were debating whether or not to use Protractor or Karma to write the necessary tests. Did we ever come to a conclusion on that?

**Comment by ThomasBurleson** [comment]
Karma is preferred since we really do not have Protractor tests configured and I am not sure we want to open that "pandora box"

**Comment by DevVersion** [comment]
@ThomasBurleson Let me reference my PR (#7583) here, so we can take a look at a possible fix.

@topherfangio Cool looking forward seeing the tests :smile: . When can we expect to see some changes?

**Comment by DmitryEfimenko** [comment]
+1
It seems this does not only happen with `requried` and `minlength`. For me it happened with `required` and `email`. I assume it'll happen with any combination of validation messages.

@ThomasBurleson Also seems to me this is a huge use case. Don't know how this can be placed in Backlog...

@topherfangio Is there progress on this?
