### ISSUE TITLE
Add support for light animation mode that will disable heavy animations

### ISSUE THREAD

**Issue by robertmesserle** [angular/material#864]
Some of the animations in the Material design spec are pretty heavy, and may not make sense for all users or all devices.  We may want to look into adding a light mode for these scenarios that either replaces heavy animations with lighter versions, or disables them altogether.

**Comment by ThomasBurleson** [comment]
Possible options:   auto, lite, off

**Comment by barryvdh** [comment]
This would be a great addition :)

**Comment by jbraccini** [comment]
+1

BTW, is there a way to hack it to disable animations?

**Comment by barryvdh** [comment]
You could put md-no-ink on a lot of items ;)

**Comment by barryvdh** [comment]
@naomiblack You closed this, but added a milestone? Is it still planned? If so, why not keep it open?

**Comment by Codier** [comment]
Yes, we would love to have this as well. Is it still planned?

**Comment by nitin7dc** [comment]
+1

**Comment by nicolae-olariu** [comment]
Are there any other ways to disable animations (for slower computers)? What about adding support for disabling heavy effects? Thanks!

**Comment by stefan-leye** [comment]
+1

**Comment by graphefruit** [comment]
@nicolae-olariu I'm facing the problem on my app actually aswell. I disable them myself by css:
```
.md-ripple-container, .md-ripple-placed {
    transition: none;
}
.md-open-menu-container.md-active {
    opacity: 1;
    transition: none;
    transition-duration: 0ms;
    /* transition: all .4s cubic-bezier(.25,.8,.25,1); */
    /* transition-duration: 200ms; */
}

md-dialog.md-transition-in {
    opacity: 1;
    transition: none;
    -webkit-transform: none;
    transform: none;
}

/*Disable transition for fading in menu items dialog.*/
.md-open-menu-container.md-active > md-menu-content > * {
    opacity: 1;
    transition: none;
    transition-duration: 0ms;
    transition-delay: 0ms;
}
.md-button
{
    transition: none;
    transition-duration: 0ms;
    transition-delay: 0ms;
}
md-dialog._md-transition-in {
    transition: none;
    transition-duration: 0ms;
    transition-delay: 0ms;
}

md-input-container label{
    transition: none!important;
    transition-duration: 0ms!important;
    transition-delay: 0ms!important;
}


md-slider ._md-thumb-container, ._md-focus-ring, ._md-track-fill, ._md-thumb{
    transition: none!important;
    transition-duration: 0ms!important;
    transition-delay: 0ms!important;
}

md-select-menu
{
    transition: none!important;
    transition-duration: 0ms!important;
    transition-delay: 0ms!important;
}
md-select-menu md-content
{
    transition: none!important;
    transition-duration: 0ms!important;
    transition-delay: 0ms!important;
}
```

Also I've disabled the ripple effect in the body-tag which affects all child elements (gladly):
```
<body md-no-ink>...</body>
```

Don't change the transform events cause they will destroy everything... Just disable the transition.

Greetings
Graphefruit

**Comment by nicolae-olariu** [comment]
@graphefruit I shall give it a try! Thanks!

**Comment by Splaktar** [comment]
@graphefruit I gave both of those a try but didn't notice any significant performance impact to IE11 with AM 1.0.5.

**Comment by graphefruit** [comment]
@Splaktar try use 1.1.0-RC4. I tested it on 1.0.8 and the performance betwen 1.0 and 1.1 is realy different,  so give it a try. 

Also have a look then on #8239 for the newest CSS.

**Comment by ashishpatel02** [comment]
<body md-no-ink>...</body>, it will disable for all the browseras?

**Comment by graphefruit** [comment]
@ashishpatel02 It will disable on all browers yes.
I'm using safari, ie and chrome, and no ripple effects here.

**Comment by ashishpatel02** [comment]
Is there anything which can only work for i.e?

**Comment by graphefruit** [comment]
Not tested - Add the md-no-ink on browser start, if its IE?

- If you render the index.html from c#/php/python there shouldn't be any problem.
- If you're directly rendering with a static index.html and javascript try to check if the browser is IE and add the md-no-ink attribute to the body

**Comment by ashishpatel02** [comment]
Cool, Many Thanks :) :) :+1: :-1:

**Comment by ashishpatel02** [comment]
I have added it like below but still facing the same issue. can you please help me for this?
![image](https://cloud.githubusercontent.com/assets/19798102/17134230/0cfc9a2a-5347-11e6-99e4-6cad5e7e54fc.png)

**Comment by graphefruit** [comment]
I think the problem is, that the md-no-ink is added after the angular rendering. 

-> Try to add the md-no-ink static on body -  is it working then? 
If its working you need to add the md-no-ink before angular.  (you can bootstrap your application self instead https://docs.angularjs.org/guide/bootstrap) 

Which angular material version are you using? Try the latest one

**Comment by carmona** [comment]
@ashishpatel02 i had the same question, here's a fix for making css rules targeted to IE https://philipnewcomer.net/2014/04/target-internet-explorer-10-11-css/

**Comment by carmona** [comment]
@graphefruit is there a way to conditionally add `md-no-ink` only when it's an IE browser? I still want the pretty effects on chrome and safari to remain the same.
I tried `ng-attr-md-no-ink="!(window.ActiveXObject) && 'ActiveXObject' in window"` but it doesn't work.

**Comment by graphefruit** [comment]
@carmona The way you're using this isn't working.

You need to attach `md-no-ink` without `ng-attr` and without any `true\false`

```
if (document.documentMode || /Edge/.test(navigator.userAgent)) {
    //its IE. or whatever checkups you want to provide here.
    $("body").attr("md-no-ink","");
    // now bootstrap
    window.onload = function () {
        angular.bootstrap(document, ["app"],  {strictDi: true});
     };
}

**Comment by omieliekh** [comment]
Since there is no way (yet) to override animations officially, there is always dirty hack that will allow you to do that:
```ts
import { MatMenu } from '@angular/material';

MatMenu['decorators'][0].args[0].animations[0] = [trigger('transformMenu', [
  state('void', style({
    opacity: 0,
    transform: 'scale(0, 0)'
  })),
  state('enter-start', style({
    opacity: 0,
    transform: 'scale(0, 0)'
  })),
  state('enter', style({
    opacity: 1,
    transform: 'scale(1, 1)'
  })),
  transition('void => enter-start', animate('0ms ease-in-out')),
  transition('enter-start => enter', animate('300ms ease-in-out')),
  transition('* => void', animate('300ms ease-in-out', style({ opacity: 0 })))
])];
```

This code for example, replaces one of two angular-animations of MatMenu element, dropdown show/hide animation.
It has some limitations - animation name should be the same as original one (`transformMenu`) as well as states...

But coupled with property checks it can be quite long-living solution.

**Comment by graphefruit** [comment]
@omieliekh This is the JavaScript repo for the old material framework.
Did you realy wanted to post this workaround here, or did you rather meant to post it on the Material-Typescript repo?

**Comment by omieliekh** [comment]
@graphefruit right, I missed that somehow 😅

**Comment by Splaktar** [comment]
Just FYI, we added the ability to disable ink ripples across your app. Details can be found in our new performance guide for IE 11: https://material.angularjs.org/latest/performance/internet-explorer
