### ISSUE TITLE
md-tooltip issues on subsequent touches

### ISSUE THREAD

**Issue by tomyinhauser** [angular/material#8642]
**Actual behavior**:
-  What is the issue? On touch devices, the tooltip displays nicely the first time the element is touched, but subsequent touches to the same element will make the tooltip blink and disappear.
-  What is the expected behavior? Touching the target element should always display the tooltip, or at least toggle it consistently.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/bedqYO
-  Details: On a touch device, touch the button or the icon, and the tooltip appears (ok). Touch the element again, and the the tooltip goes away (ok). Touch the element again, and the tooltip is NOT shown anymore (nok).

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Environments: Tested on iPad 2 (Safari), Moto X (Android/Chrome) and Chrome desktop's touch device emulation
-  Browser Type: Chrome / Safari
-  Browser Version: 50.0.2661.102
-  OS: Windows / iOS
-  Stack Traces:

**Comment by ThomasBurleson** [comment]
Please confirm this issue still exists with v1.1.0-rc.5:  https://cdn.gitcdn.link/cdn/angular/bower-material/v1.1.0-rc.5/angular-material.css

**Comment by tomyinhauser** [comment]
The issue still exists, and in this RC the tooltip padding isn't looking great:
http://codepen.io/anon/pen/EyVapy
