### ISSUE TITLE
md-autocomplete inside md-tab, close button not clickable while typing

### ISSUE THREAD

**Issue by otterslide** [angular/material#8649]
**Actual behavior**:
-  What is the issue? *
While typing in the auto-complete the "X" button is not clickable if the autocomplete is inside a md-tab.

-  What is the expected behavior?
Click X and it should clear, without having to click twice.

**CodePen** or Steps to reproduce the issue: *
Try typing text in the autocomplete, and then press X to clear, it will just close the autocomplete instead of clearing.

-  CodePen Demo which shows your issue :
http://codepen.io/otterslide/pen/WxvZmR

-  Details:

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version:  50.0.2661.102 m
-  OS: Windows 10
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Seems like this is a general bug, even outside of `md-tabs`.

> https://material.angularjs.org/HEAD/demo/autocomplete

The bug seems to be only showing up in `master`.

**Comment by frigus02** [comment]
In the "Inside Dialog" demo it works as expected, btw. Here every button outside the autocomplete works while the dropdown is visible. It's even possible to close the dialog by clicking somewhere outside while the dropdown is open.

**Comment by DevVersion** [comment]
So the bug was introduced in https://github.com/angular/material/commit/4e2722cdd18df00b0b24e1bc15bf95bb16f3066d.

You can confirm that, by removing the `md-content` element from the DOM.

**Comment by ThomasBurleson** [comment]
@DevVersion - can you rebase plz

**Comment by ThomasBurleson** [comment]
@DevVersion - can you rebase plz
