### ISSUE TITLE
Cannot set md-menu parent

### ISSUE THREAD

**Issue by nishantkagrawal** [angular/material#8652]
**Actual behavior**:
-  What is the issue? Not able to specify parent for md-menu item. When I hover a div, the button for showing menu shows with other information. As soon as i click on the button, the md-menu opens and the parent element loses the hover and hence all the css effect.
-  What is the expected behavior? I should be able to set the parent element for md-menu.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/nishantkagrawal/pen/QEbrWV
-  Details: Click on the phone button to reproduce the issue.

**Angular Versions**: *
-  Angular Version: 1.5
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102
-  OS: Windows 7
-  I saw the code and by default the parent is set to body. Can it be changed to pass a parent element (or rather default it to the parent). Or any other control that can be used here to achieve this?
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 1 and Material 2' efforts.  For details, see our forum posting @ http://bit.ly/1UhZyWs.

**Comment by alphatwit** [comment]
I wish this would be addressed. I have an element that goes into full screen, and the menu opens in the body instead of within that element, so I can't access the menu at all.
