### ISSUE TITLE
angular-material in nodejs 6

### ISSUE THREAD

**Issue by fthamura** [angular/material#8659]
i got this when try to do 
npm install angular-material --save-dev

this is the error

4 verbose cwd /home/mervo/js/angular-material
45 error Linux 4.4.0-22-generic
46 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "angular-material" "--save-dev"
47 error node v5.11.1
48 error npm  v3.8.6
49 error code ENOSELF
50 error Refusing to install angular-material as a dependency of itself
51 error If you need help, you may report this error at:
51 error     <https://github.com/npm/npm/issues>
52 verbose exit [ 1, true ]

**Comment by devLaaziz** [comment]
npm install http://github.com/angular/bower-material/tarball/master
 
# or use alternate syntax to install HEAD from master 
npm install http://github.com/angular/bower-material#master --save

**Comment by ThomasBurleson** [comment]
We do not yet support Node 6. Here are the commands to install using Node 5.x and the latest release candidate for 1.1.0:

- npm install angular-material 
- npm install angular-material@1.1.0-rc.5
- bower install angular-material#v1.1.0-rc.5

> These install v1.1.0-rc.5. The latest patch release is 1.0.9. Developers should also note that the patch release does not contain the hundreds of improvements that are available and published  in v1.1.0-rc.5 build.

> Note that the syntax for the RCs has changed to **-rc.<xxx>** == v1.1.0-rc.5
