### ISSUE TITLE
Angular Material 1.1.0 stable

### ISSUE THREAD

**Issue by anujsingla** [angular/material#8661]
Hi ,

Please confirm stable version of 1.1.0 angular material ?

Thanks.

**Comment by DevVersion** [comment]
This is not an issue. We're working on a release for `1.1.0`, but before there will be some release candidates.

**Comment by ThomasBurleson** [comment]
Here are the commands to install the latest release candidate for 1.1.0:

- npm install angular-material 
- npm install angular-material@1.1.0-rc.5
- bower install angular-material#v1.1.0-rc.5

> These install v1.1.0-rc.5. The latest patch release is 1.0.9. The patch release does not contain the hundreds of changes publish in v1.1.0-rc.5.
