### ISSUE TITLE
External url for md-svg-icon is not allowed

### ISSUE THREAD

**Issue by Dona278** [angular/material#8662]
After [this commit](https://github.com/angular/material/pull/8484/commits/ce64a2e4a63861c4e9f6eb4147f60d002d1586bf), when using '$mdIconProvider' with an external url like 'https://az123456.vo.msecdn.net/icon.svg' angular throw an exception because the url is not trusted and not allowed

-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc.5

**Comment by DevVersion** [comment]
Not sure this is a bug. You should be able to trust your external URL

```js
$sceDelegateProvider.resourceUrlWhitelist([
  // Allow same origin resource loads.
  'self',
  // Allow loading from our assets domain.  Notice the difference between * and **.
  'http://srv*.assets.example.com/**'
]);
```

**Comment by Dona278** [comment]
Sure! i'm sorry.. now it work without problems.
I did not know the whitelist of angular delegate provider

Thank you!

**Comment by ThomasBurleson** [comment]
@DevVersion - please add ^ as doc additions to the mdIcon service.
