### ISSUE TITLE
md-button text is not centered vertically on Chrome 50 - debian stretch

### ISSUE THREAD

**Issue by Burtan** [angular/material#8665]
Hi,
md-button text is not centered vertically on Chrome 50 - debian stretch. You can see the behaviour on the official demo page:
https://material.angularjs.org/latest/demo/button
It is working on Firefox 45.1.1

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50
-  OS: debian stretch

**Comment by DevVersion** [comment]
@Burtan Thanks for the issue, can you please share a screenshot? Some developers will not have Debian Stretch.

**Comment by Burtan** [comment]
Chrome
![chrome](https://cloud.githubusercontent.com/assets/3275473/15825926/e5e57aaa-2c05-11e6-9a1b-efb9d82ec163.png)
Firefox
![firefox](https://cloud.githubusercontent.com/assets/3275473/15825932/e9e682b6-2c05-11e6-902e-0cafbb5ec1dc.png)

**Comment by Burtan** [comment]
It's the same on Win10 in my virtual box.

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our ‘Surge Focus on Material 1 and Material 2' efforts.  For details, see our forum posting @ http://bit.ly/1UhZyWs.
