### ISSUE TITLE
Does md-checkbox supports required or ng-required options? If not, what are other options for validation?

### ISSUE THREAD

**Issue by himanshu56** [angular/material#8668]
One previous issue have same problem but the issue it refers doesn't solve my problem. Please don't move this issue. I tried using aria-required but it didn't work. Required option is working for md-datepicker. This is my code-
`<md-checkbox md-no-ink ng-model="week" name="day[week]" ng-true-value="'true'" ng-false-value="'false'" ng-required ="true"></md-checkbox> `

**Comment by DevVersion** [comment]
This works as expected. 
- http://codepen.io/DevVersion/pen/QEjbay

What's your issue?

**Comment by himanshu56** [comment]
I used the same code. It doesn't show required error on pressing submit. Also  ng-inspector tool shows value of week to be "undefined" (instead of false) when unchecked.

**Comment by himanshu56** [comment]
This is code for submit:
`<button type="submit" class="btn btn-info pull-right" ng-disabled="submit_disabled">Submit</button>`

**Comment by DevVersion** [comment]
Validation works as expected. You can use `ng-messages` but unfortunately you have to style it yourself. 

Maybe in the future, we'll support `ng-messages´ outside of `md-input-container`'s as well.
