### ISSUE TITLE
Can't include an input in a bottom sheet

### ISSUE THREAD

**Issue by Josh-Burgess** [angular/material#867]
Due to [this line](https://github.com/angular/material/blob/master/src/components/bottomSheet/bottomSheet.js#L206) (I suspect) in `src/components/bottomSheet/bottomSheet.js`, inputs aren't feasible in bottom sheets created via the `$mdBottomSheet` service.

Recommended fix would probably go something like this:

    if (e.target.tagName.toLowerCase() !== "input")
      e.preventDefault();

Or something like this if more elements where default behavior is desired are identified:

    switch (e.target.tagName.toLowerCase()) {
      case "input":
      case "button":
        break;
      default:
        e.preventDefault();
    }

**[JSFiddle Here](http://jsfiddle.net/nennneh3/)**

**[Video Here](http://www.screencast.com/t/bFOpolUNhW)**

----

**Just to clarify, this happens only with touch screen devices.  In a normal web browser, behavior is within what I would consider "expected"**

**Comment by EladBezalel** [comment]
Works on [HEAD](http://codepen.io/EladBezalel/pen/GpdNPg)
