### ISSUE TITLE
Input doesn't show text when it is readonly and focused

### ISSUE THREAD

**Issue by Burtan** [angular/material#8670]
-  What is the issue? 
Input doesn't show text when it is readonly and not focused
-  What is the expected behavior?
Input should always show the text

-  CodePen Demo which shows your issue :
http://codepen.io/Burtan/pen/qNOORw

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: Chrome (Firefox working fine)
-  Browser Version: 50
-  OS: debian stretch / win10
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
I can reproduce this issue.

It seems like the input component is setting the font color to `transparent`

```css
  color: transparent;
```

The following selector is matching
- https://github.com/angular/material/blob/master/src/components/input/input.scss#L172

**Comment by Burtan** [comment]
Shouldn't this be fixed with 1.1.1?
