### ISSUE TITLE
Release Candadate Versioning Convention change

### ISSUE THREAD

**Issue by animedbz16** [angular/material#8674]
Just wondering if this most recent tag was meant to change the versioning format or not since we saw the update and changed our rc number from 4 to 5 and was trying to figure out what was going on since we weren't finding the package and then noticed that there is now a `.` between rc and the number.

* https://github.com/angular/material/tree/v1.1.0-rc.5
* https://github.com/angular/material/tree/v1.1.0-rc4
* https://github.com/angular/material/tree/v1.1.0-rc3
* https://github.com/angular/material/tree/v1.1.0-rc2
* https://github.com/angular/material/tree/v1.1.0-rc1

**Comment by ThomasBurleson** [comment]
Due to community requests, we started publishing our RC releases to NPM.

- NPM does not support notations like `1.1.0-rc5`.
- NPM does support notations like `1.1.0-rc.5`.

> Hence our recent [and future] change to the new name convention.
