### ISSUE TITLE
Not able to update for RC5 using bower

### ISSUE THREAD

**Issue by danielmariz** [angular/material#8679]
**Actual behavior**: Bower update not getting latest version
-  What is the issue? *Trying to update to latest version (1.1.0-rc5) to use Pre Rendered Dialog
-  What is the expected behavior? Getting latest version
////Bower command
bower update -F angular-material
////Error
$ bower angular-material#1.1.0-rc5     ENORESTARGET No tag found that was able to satisfy 1.1.0-rc5

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Here are the commands to install the latest release candidate for 1.1.0:

- npm install angular-material 
- npm install angular-material@1.1.0-rc.5
- bower install angular-material#v1.1.0-rc.5

> These install v1.1.0-rc.5. The latest patch release is 1.0.9. Developers should also note that the patch release does not contain the hundreds of improvements that are available and published  in v1.1.0-rc.5 build.

> Note that the syntax for the RCs has changed to **-rc.<xxx>** == v1.1.0-rc.5

**Comment by danielmariz** [comment]
Sweet, thanks!

**Comment by ashishpatel02** [comment]
@ThomasBurleson  Performance is improved with v1.0.9?
