### ISSUE TITLE
Dialog Pre-rendered not working

### ISSUE THREAD

**Issue by danielmariz** [angular/material#8682]
**Actual behavior**: Receiving and error
-  What is the issue? * trying to use dialog pre-rendered available on rc5 
-  What is the expected behavior? open the dialog based on id

I've just changed from templateUrl to contentElement
///My code working before
scope.$on('showDialog', function(event, controller) {
                console.log('#######', controller.config.name);
                controller.$mdDialog.show({
                    bindToController: true,
                    clickOutsideToClose: true,
                    controller: ctrl,
                    controllerAs: ctrlAs,
                    fullscreen: true,
                    locals: {config: controller.config},
                    parent: angular.element(document.body),
                    templateUrl: template

                });
			});

//Code after changing to pre-redered
scope.$on('showDialog', function(event, controller) {
                console.log('#######', controller.config.name);
                controller.$mdDialog.show({
                    bindToController: true,
                    clickOutsideToClose: true,
                    contentElement: '#AddTunnelModal',
                    controller: ctrl,
                    controllerAs: ctrlAs,
                    fullscreen: true,
                    locals: {config: controller.config},
                    parent: angular.element(document.body)

                });
			});

//Error printed in my console
angular-material.js:1653 Uncaught TypeError: node.hasAttribute is not a functionexpect @ angular-material.js:1653(anonymous function) @ angular-material.js:1672

it seems that element attribute expected on expect function is undefined 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *1.5.5
-  Angular Version:1.5.5
-  Angular Material Version:1.1.0-rc5

**Additional Information**:
-  Browser Type: *Chrome
-  Browser Version: *50.0.*
-  OS: *Mac OSx
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by danielmariz** [comment]
I've fixed this issue, the problem was id on md-dialog instead of a wrapper content

**Comment by felixfbecker** [comment]
@danielmariz could you comment how you fixed it? Im facing the same issue.

**Comment by linqOxelar** [comment]
Issue here : buttons are not reacting !

**Comment by softgenni** [comment]
@danielmariz i am also facing this issue. please comment here, how you fixed this issue. thanks
