### ISSUE TITLE
mdPanel doesn't close when navigating back in history

### ISSUE THREAD

**Issue by JohnKaleson** [angular/material#8683]
**Actual behavior**:
-  What is the issue?
mdPanel doesn't close when clicking backspace or browser's navigation buttons 
-  What is the expected behavior?
mdPanel closes itself when clicking back or forward

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue: https://material.angularjs.org/1.1.0-rc.5/demo/panel
-  Details: Go to https://material.angularjs.org/latest/, then click DEMOS -> Panel and click the button 'Dialog'. Next click backspace on your keyboard or Back button in your browser.

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: Chrome 50, FF46, IE11

----

**Comment by ThomasBurleson** [comment]
@ErinCoughlan - related to `$destroy` ?

**Comment by ErinCoughlan** [comment]
If scope is destroyed, close & destroy the panel.
