### ISSUE TITLE
tooltip issue

### ISSUE THREAD

**Issue by anujsingla** [angular/material#8684]
Hi ,

I am showing tooltip using md-tooltip like
<div class="notificationIcon" style="margin-right: 5px;">
   <md-icon md-svg-src="../techpackapp/resources/images/notify_24x24.svg"  ng-click="techPackGenerationStatusesDialog($event)" ng-class="notificationCount>0 && 'notiBadge'" data-badge="{{notificationCount}}">
<md-tooltip md-direction="bottom">{{ 'PTC.TPAA.Notification' | translate }}</md-tooltip>
 </md-icon>
</div>

There is some issue in it.

when i mouseover the icon tooltip show but it does not go when i mouseout from the icon.
Please check below image:

![tooltip](https://cloud.githubusercontent.com/assets/16379731/15850908/1dae830c-2cb8-11e6-886c-1c5154e5b4d9.png)

Please give some suggestion how to hide tooltip after mouseout.

Thanks

**Comment by ThomasBurleson** [comment]
@anujsingla - why are you not using our Issue Template?
