### ISSUE TITLE
select(multiple): md-selected-text only display when many md-options are selected 

### ISSUE THREAD

**Issue by rafaelhc** [angular/material#8686]
Is it possible to display the `md-selected-text` only when you have selected 3 items or more?

I have a multiple selector showing counties, and they are all supposed to be pre-selected.
This results in a list containing 30+ items, not looking very nice for the page setup.

Is it somehow possible to display the `md-selected-text` when you exceed a limit, in my case 3 or more?

Any other solutions?

**Comment by Splaktar** [comment]
I'm not sure how this solves your use case, but this [CodePen](https://codepen.io/Splaktar/pen/xJbNBq?editors=1010#0) demonstrates how to do what you are asking for.
