### ISSUE TITLE
mdDialogPreset inject inline css classes as a parameter for ok() and cancel()

### ISSUE THREAD

**Issue by PierreRoudaut** [angular/material#8688]
It would be really handy to inject inline css classes as a parameter for the `$mdDialogPresets::ok()` and `$mdDialogPresets::cancel()` methods as a shortcut to apply the current theme styling for the buttons without having to provide a new theme `$mdDialogPresets::theme()`

Considering the button generated by `$mdDialogPresets::ok()` represent the main action, it would be logic to style it with `md-raised` or `md-accent` classes 

An example of usage would be:

```js
$mdDialog
  .confirm()
  .title('Delete item')
  .textContent('Are you sure you want to delete this item ?')
  .ok('Delete', 'md-raised md-warn').cancel('Cancel', 'md-primary');
```
 
Otherwise, is there a way to do so without providing a dedicated theme for the dialogs ?

**Comment by DevVersion** [comment]
I like this approach. 

The second parameter is optional and allows developers to specify classes on the given button.
- It defaults to `.md-primary`.

@ThomasBurleson What do you think? Will be a quick enhancement

**Comment by ThomasBurleson** [comment]
These are edge-features that could be easily done with a custom dialog template.  Will not fix in core.
