### ISSUE TITLE
Where did "offset" attribute go?

### ISSUE THREAD

**Issue by srigi** [angular/material#869]
In 0.6-rc1 there was really useful attribute `offset` for flexible layouts. In 0.6-rc2 this was removed but you are still mentioning this option of layout [at the top of documentation](https://material.angularjs.org/#/layout/grid)

Will `offset` attribute return?

**Comment by nross63** [comment]
+1

**Comment by srigi** [comment]
Can somebody from team make some statement on this?
cc @naomiblack

**Comment by epelc** [comment]
The docs also appear to reference `offset` but it's usage is entirely missing and it links to a another page which doesn't even mention offset. Anyways they need a bit of work if its added or not.

https://material.angularjs.org/#/layout/options
ctrl+f offset

**Comment by jamesspencer** [comment]
Also missing offset classnames in the 0.8rc1 build, it is mentioned in the docs but no longer has its own section/description.

**Comment by ThomasBurleson** [comment]
@rschmukler - Thoughts ?

**Comment by jaoued** [comment]
:+1:

**Comment by Ir1sh** [comment]
+1

**Comment by imjoeybrennan** [comment]
+1

**Comment by rschmukler** [comment]
It's back! Sorry all. Enjoy

**Comment by timtimmytime** [comment]
The offset in multiples of 5 does not seam to work.  example: offset="25" 
It is however working for offset="33",   offset="66" 

Here is what I see in the css from the latest master... if I remove the [offset] it works as expected.  
![screen shot 2015-04-07 at 10 10 35 am](https://cloud.githubusercontent.com/assets/1177839/7024967/677185ca-dd0e-11e4-8d80-935be806fdd9.png)

**Comment by ThomasBurleson** [comment]
@timtimmytime - plz open a new issue.
