### ISSUE TITLE
feat/bug: md-button mdNoFocusStyle not working for md-list-item / md-card

### ISSUE THREAD

**Issue by graphefruit** [angular/material#8691]
**Actual behavior**:
-  What is the issue? * The mdNoFocusStyle can be attach on normal md-buttons but cant be attached on md-list-items aswell as md-cards with an ng-click
The md-list-item aswell as the md-card generate an internal button without the mdNoFocusStyle
-  What is the expected behavior? The mdNoFocusStyle should be attached on md-list-items / md-cards

**CodePen** or Steps to reproduce the issue: *
https://material.angularjs.org/latest/demo/list

Thoughts:
After this would be a bigger task, the question is, if it would be possible/better to add the posibility to disable the mdNoFocusStyle globally for all buttons.

I wrote a simple code for this:
```
if (!angular.isDefined(attr.mdNoFocusStyle) && !$injector.has('$MD_DISABLE_FOCUS_STYLE')) {
  // restrict focus styles to the keyboard
  scope.mouseActive = false;
  element.on('mousedown', function() {
    scope.mouseActive = true;
    $timeout(function(){
      scope.mouseActive = false;
    }, 100);
  })
  .on('focus', function() {
    if (scope.mouseActive === false) {
      element.addClass('md-focused');
    }
  })
  .on('blur', function(ev) {
    element.removeClass('md-focused');
  });
}
```
in .config -> `$provide.constant('$MD_DISABLE_FOCUS_STYLE', '');`

Also this would enable a performance improvement for Internet Explorer (specially on mobile versions aswell).
The problem is:
1. $timeout - Triggers a $q.promise chain for angular. (maybe here use `$timeout(func,timeout,false)`)
2. The addClass/removeClass triggers a complete repaint of the page.
3. Because of the md-list-item/md-card: Many event-listeners cant be disabled (specially on ng-repeat scenarios)

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: RC-5

**Additional Information**:
-  Browser Type: All browsers
-  Browser Version: All versions
-  OS: All OS
-  Stack Traces:

**Comment by DevVersion** [comment]
The approach with the `$MD_DISABLE_FOCUS_STYLE` constant is not something we should support.

Once we introduce a constant, like this, the API will get really confusing and users expect the same constants for other components as well.

The focus style can be easily overwritten per CSS.

---
Indeed, we should probably support the `md-no-focus-style` attribute on the `md-list-item`.

@graphefruit What is about the card component - Can you explain it a bit?

**Comment by graphefruit** [comment]
@DevVersion sorry for late response, got no PC.
Card-Component: I had a wrong look and thought it would be a card, but was a list-item (just ignore please).

Thanks so far & have a great week
