### ISSUE TITLE
md-nav-ink-bar stays visible when nav-item is no longer selected.

### ISSUE THREAD

**Issue by heavysixer** [angular/material#8694]
**Actual behavior**:
When you have a link that deselects the navbar item the `md-nav-ink-bar` stays selected.
I would expect that clicking a link located in the navbar which does not correspond to a page (for example dropdown or a link to a page which is not in the nav bar) that the ink-bar would also disappear.

**CodePen** or Steps to reproduce the issue: *
 http://codepen.io/anon/pen/GqpByo
-  Click a nav-item see that it is selected.
-  Click the link at the end of the nav-bar, see that the previously selected nav-item is no longer selected but the `md-nav-ink-bar` is.

**Angular Versions**: *
-  Angular Version: ~1.5.3
-  master and 1.1.0-rc.5

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

**Comment by gmoothart** [comment]
Yes, this is a bug. When updating the nav-bar, we need a case to clear the selected nav-item if it is null:
https://github.com/angular/material/blob/0e2e60fd0158e39c4325fd5cc49e94f819d34793/src/components/navBar/navBar.js#L221

**Comment by fhernandezn** [comment]
Hi @gmoothart @heavysixer  do you mind if I work on this issue?

**Comment by ThomasBurleson** [comment]
@fhernandezn - give us a PR and perhaps @gmoothart can review and optimize.

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material/pull/8703.
