### ISSUE TITLE
md-select: form validation state with default value

### ISSUE THREAD

**Issue by wolfet** [angular/material#8699]
**Actual behavior**:
-  What is the issue? *
If ng-model is set with a default value on an md-select with a required ng-message, the form has an invalid state upon initialization in angular material 1.1.0-rc5.

-  What is the expected behavior?
If the md-select is set with a valid default value and is a required field, then the form will have a valid state.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/twolfe/pen/dXYxJO
-  Details:
This is codepen is taken directly from the angular material select demo page. Notice how the save button is disabled on load even though a valid model value is assigned. Changing the angular-material version to 1.1.0-rc4 resolves this issue.

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version:
1.1.0-rc5.

**Additional Information**:
-  Browser Type: * Chrome
-  Browser Version: * 51.0.2704.79 m
-  OS: * Windows
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by masitko** [comment]
I think is the same as https://github.com/angular/material/issues/8666
I have the same problem
