### ISSUE TITLE
md-nav-bar: missing md-tab style wrapping/scrolling

### ISSUE THREAD

**Issue by amritk** [angular/material#8701]
**Actual behavior**:
-  If you add a large number of tabs, or view them on mobile, they don't have the nice wrapping effect of md-tabs
-  It is expected that you could add arrows to the sides to allow the user to slide the nav-bar left and right as opposed to just having a horizontal scroller. 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/amritk/pen/yJeLjp
-  Details: You will see a horizontal scrollbar, as opposed to the nice arrow navigation that md-tabs employs

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-RC5

**Additional Information**:
-  Browser Type: All
-  Browser Version: All
-  OS: All
-  Stack Traces:

**md-nav-bar**
![screen shot 2016-06-08 at 3 24 31 pm](https://cloud.githubusercontent.com/assets/2039539/15913158/49b7cf46-2d8d-11e6-8de7-fbe13f66ab78.png)
**md-tabs**
![screen shot 2016-06-08 at 3 24 55 pm](https://cloud.githubusercontent.com/assets/2039539/15913162/4d2c2da2-2d8d-11e6-841f-fea7364213ba.png)

**Comment by p-mcgowan** [comment]
Please implement this. Currently, `md-tabs` without `md-tab-content` is still far less performant than desirable with heavy content when compared to a simple show/hide. If we could have the (customizable?) styling of `md-tabs` with the performance of `md-nav-bar` that would be ideal.

**Comment by ThomasBurleson** [comment]
We will not be implementing pagination in mdNavBar. Those features will only be available in mdTabs.

> Use mdTabs with external content bodies for improved performances.

**Comment by amritk** [comment]
Any time you use md-tabs you get pretty poor performance, but I will try implementing a version myself. Thanks

**Comment by anudeepjusanu** [comment]
It would be nice if pagination is setup in md-nav-bar as with md-tabs its unable to recognise the current position on a page refresh
