### ISSUE TITLE
md-autocomplete separate display value than the bonded value 

### ISSUE THREAD

**Issue by sohail85** [angular/material#8705]
**Actual behavior**:
Hi, I am want to replace my form md-select with md-autocomplete as md-select freezes as it renders all the values bounded with but it seems md-autocomplete only renders the visible part of model.

problem with md-autocomplete is there is no ng-value property for autocomplete so that I can display text to users but the form will be bounded to id of selected item.

**Comment by DevVersion** [comment]
`ng-value` doesn't make any sense for the `md-autocomplete`. The bound value will be always the selected item. You could modify the `selected item` structure to match your desired behavior.

**Comment by sohail85** [comment]
@DevVersion : Yeah I used the change event to do so, which it self had issue (the watchers trigger chnage event multiple time) but any ways I have handled that using condition to process only if the selected item is object @
