### ISSUE TITLE
add browser support documentation to readme

### ISSUE THREAD

**Issue by MickelSierra85** [angular/material#8706]
Hi,

From the documentation:

> Angular Material is targeted for all browsers with versions n-1; where n is the current browser version.

Is it going to be more stable sometime soon? i.e. could I use chrome 50 for a year or so?

**Comment by MickelSierra85** [comment]
From the documentation:

> Angular Material is targeted for all browsers with versions n-1; where n is the current browser version.

Is it going to be more specific?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
