### ISSUE TITLE
IE11, md-list-item, vertical alignment

### ISSUE THREAD

**Issue by Mylogin-info** [angular/material#8708]
**Actual behavior**:
-  What is the issue? * 
In some situations the content of a list item is not shown in the vertical center.
-  What is the expected behavior? It should be in the vertical center.

Steps to reproduce the issue: *
-  Demo which shows your issue : See https://material.angularjs.org/HEAD/demo/list in IE11.

**Angular Versions**: *
-  Angular Version: v1.5.6
-  Angular Material Version: v1.1.0-rc.5-master-0c34ff4

**Additional Information**:
-  Browser Type: * Internet Explorer
-  Browser Version: * 11
-  OS: * Windows 8
![list-item v-align](https://cloud.githubusercontent.com/assets/16088627/15929997/bfdeeca4-2e50-11e6-898e-ac77a06c7fb0.png)

**Comment by DevVersion** [comment]
Hey @Mylogin-info 

We already had some issues for that exact problem. They should be already fixed.

Can you probably try clearing your cache? if the problem still occurs, please provide more information.

Like
- DOM Structure (Screenshot Dev tools)
- Confirm with Master

Thanks in advance.

See #8286

**Comment by Mylogin-info** [comment]
Hey DevVersion,

Thank you for your quick reply. It is definitely not a cache problem.

I made simple codepen that reproduces the issue on Windows 8.1 pro with IE 11:
http://codepen.io/anon/pen/vKLXyX

Chrome vs IE11
![chrome vs ie11](https://cloud.githubusercontent.com/assets/16088627/15931269/4f807e3a-2e57-11e6-9d83-0464f6fe1a90.PNG)

Please let me know if your need more information.

Regards,
Otto

**Comment by DevVersion** [comment]
@Mylogin-info Yes, I can see the problem. I will work on that as soon as possible. Thanks!

**Comment by Mylogin-info** [comment]
Great! Good luck!

_Please let me know if i can be of further assistance._

**Comment by DevVersion** [comment]
@Mylogin-info The PR is pending. It was quite easy to fix, because I recently introduced the IE min-height fix /workaround in dce2fee

**Comment by Mylogin-info** [comment]
Good work! 

Thank you again. I'll update when the PR is accepted.
