### ISSUE TITLE
tooltips will no longer fire with mouse on touchscreen devices

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#8710]
**Actual behavior**:
If you have a touchscreen device that uses a mouse/touchpad, tooltips will not fire on mouseover. Surface Pro devices, touchscreen Chromebooks and touchscreen Chromebases will not fire without touching the screen.

**CodePen** or Steps to reproduce the issue: *
https://material.angularjs.org/HEAD/demo/tooltip

**Angular Versions**: *
Master

**Additional Information**:
Tested on Chrome

This is because of this commit: https://github.com/angular/material/commit/15402f851e2c7726234670b97fa30eec9626473a

It's not proper to say a device "IS_TOUCH" but rather "HAS_TOUCH". Touchscreen is a feature, not an exclusive identifier. I would actually argue that touch devices rarely have hover support. On Android, you would need to hold down touch for 500ms to trigger longClickPress. Hover events in web browsers Chrome on Android are supported by triggering longClickPress. 

You can actually disable touch events on Chrome and the following events occur after holding down the touchscreen.

* touchstart

(after a long delay)
* mouseover
* mouseenter
* mousemove
* mousedown (right click event)
* focus
* touchcancel (because chrome's context menu appeared)

I then tap outside to close the context menu:

* mouseout
* mouseleave
* blur

As you can see, on Chrome, you don't need to map any touch events and allow Chrome to internally to allow touch operation. 

Alternatively, if `onTouchStart` was triggered, you can ignore any MouseEvents until `onTouchEnd`/`onTouchCancel`. For browser compatibility, we can delay for a few milliseconds to see is `mouseover` fires before `touchstart`, though I'm not sure any browser does that. I do have a touchscreen monitor I can connect to my Windows PC and Mac to test any functionality on other browsers.

**Comment by crisbeto** [comment]
I'll revisit this then. It seemed like the enter handler was firing too often though.

**Comment by clshortfuse** [comment]
Agreed. On Chrome, it seems watching touchStart and waiting for touchEnd/touchCancel and ignoring (and preventing) mouseEvents would work fine. I'm going to test on different browsers in the meantime.

I used https://patrickhlauke.github.io/touch/tests/event-listener_all-no-timings.html to quickly test.

**Comment by clshortfuse** [comment]
Mac OS X with Safari doesn't fire onTouchStart. It seems the OS doesn't support touch at all and just emulates mouse events (no multitouch support either).

Edge sends:

* mousemove
* pointerover
* mouseover
* mouseenter
* focus
* pointerdown
* mousedown
* gotpointercapture

while holding:

* pointermove (repeated)
* mousemove (repeated)

on held release (right click)

* pointerup
* pointerup
* lostpointercapture
* pointerout
* mouseout
* pointerleave
* mouseleave
* blur

(context menu fired)

Will add Firefox in it's own comment

**Comment by clshortfuse** [comment]
IE11:

* mousemove
* pointerover
* mouseover
* pointerenter
* mouseenter
* pointerdown
* mousedown
* gotpointercapture
* focus

while holding:

* pointermove (repeated)
* mousemove (repeated)

on held release (right click):

(no events and context menu fired)

tapped outside to close context menu

* pointerup
* mouseup
* lostpointercapture
* pointerout
* mouseout
* pointerleave
* mouseleave
* pointermove
* mousemove
* blur

**Comment by clshortfuse** [comment]
FireFox doesn't send touch events from Windows. It emulates mouse events. The only desktop browser that sends touch events is Chrome, so this issue is probably exclusive to Chrome's touch support. IE11 and Edge use `pointer` instead of `touch` but it doubles by emulating touch events. 

I think you can safely ignore mouse events if `touchstart` is triggered until you receive `touchEnd` or `touchCancel`.
