### ISSUE TITLE
select: margin is outside of toolbar

### ISSUE THREAD

**Issue by epelc** [angular/material#8712]
**Actual behavior**:
-  What is the issue? \* The margin goes outside the toolbar
-  What is the expected behavior? It should be inside. This also may partially cause #8412 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : Look at any demo page on docs with directive select
-  Details: https://material.angularjs.org/latest/demo/select
  ![bad select in toolbar](https://cloud.githubusercontent.com/assets/5204642/15937315/5c99b6f6-2e3c-11e6-896f-6b1e54cae02b.png)

**Angular Versions**: *
-  Angular Version: I also tested locally 1.5.6
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Browser Type: \* chrome
-  Browser Version: \* 51.0.2704.84 (64-bit)
-  OS: \* os x 10.11.5
-  Stack Traces:

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by clshortfuse** [comment]
#8716 has new layout for md-select which does away with some of the previous margins. I believe it would fix the problem.
