### ISSUE TITLE
autocomplete: selectable items outside of viewport is non-accessible on ios safari

### ISSUE THREAD

**Issue by hg222dt** [angular/material#8721]
**Actual behavior**:
-  What is the issue? *
  When writing a query in the autocomplete field and getting more selectable items than able to fit inside the viewport, the user is not able to scroll down in the items list to the bottom items. When the user has scrolled down the list maximum, the bottom items are not shown, because they are hidden behind the virtual keyboard. If the user tries to continue to scroll the items, now instead the whole page scrolls and the items list is kept located at a fixed position in the viewport, still with its bottom items covered by the virtual keyboard.
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:
- Go to Angular Materials autocomplete demo ( https://material.angularjs.org/1.1.0-rc.5/demo/autocomplete ) with Safari on a iPod or iPhone device.
- Type a query in the top component example which will result in at least five dropdown items as suggestions.
- The items will appear below the input field and the bottom items in the list will be covered by the virtual keyboard.
- Try to scroll down the list of items to get to the bottom item.
- When the list doesn’t scroll anymore, there will still be items covered by the virtual keyboard.
- Then try to scroll the list down some more. Now the whole page scrolls instead. And the list of items will be kept at a fixed position in the viewport.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: Safari
-  Browser Version: 601.1
-  OS: iOS 9.3.2
-  Stack Traces:

**Comment by zanderle** [comment]
Any update on this? The problem remains in 1.1.1

**Comment by Splaktar** [comment]
I can no longer reproduce this. Please test again on 1.1.7 and let me know if you still see this issue. I'll re-open if that is the case.

**Comment by zanderle** [comment]
You are right, seems fixed now. Thanks!
