### ISSUE TITLE
mdDatepicker: Directive documentation missing in 1.1.0-rc5

### ISSUE THREAD

**Issue by dandanknight** [angular/material#8722]
**Actual behavior**:
-  What is the issue? 

No directive documentation on angular material website for mdDatepicker in 1.1.0-rc5 https://material.angularjs.org/1.1.0-rc.5/
-  What is the expected behavior?

For it to be documented as it is in 1.1.0-rc4

**Angular Versions**: *
-  Angular Version: NA
-  Angular Material Version: 1.1.0-rc5

**Comment by crisbeto** [comment]
Sorry for that, I'll get it sorted. Meanwhile you can refer to the ones in rc4, nothing has changed between them.
