### ISSUE TITLE
md-menu icons and text not aligned in firefox

### ISSUE THREAD

**Issue by rayita** [angular/material#8724]
**Actual behavior**:

-  What is the issue? 

md-menu icons and text are displayed in two separates lines in **Firefox**

-  What is the expected behavior?

Icons ans text must be in same line

* Steps to reproduce the issue: *

You can check it up in angular material demo web: https://material.angularjs.org/latest/demo/menu

**Angular Versions**: 
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-RC5 and 1.1.0-RC4, 1.0.9 it's ok.

**Additional Information**:
-  Browser Type: FireFox
-  Browser Version: 46
-  OS: Windows 10

**Comment by ThomasBurleson** [comment]
@topherfangio - this appears to be broken AGAIN. We had a previous issue with flexbox layouts in Firefox.

**Comment by topherfangio** [comment]
I think this is the exact issue that https://github.com/angular/material/pull/8675 fixes.

@rayita Do you still see it on HEAD/master? https://material.angularjs.org/HEAD/demo/menu

**Comment by rayita** [comment]
Head it's OK. Issue Fixed.

**Comment by topherfangio** [comment]
Awesome, thanks for double-checking!
