### ISSUE TITLE
i am retrieving the list of options from mongodb. In the example of auto-complete the list of states is a local string, hence works fine. I am trying to get this list from mongodb. This fetch takes some time for the response to come back. hence the list remains empty. can you guys please help?

### ISSUE THREAD

**Issue by nischaym** [angular/material#8728]
**Actual behavior**:
-  What is the issue? *
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
@nischaym Can you please fill the questions from issue template. Otherwise we won't be able to help you.

**Comment by clshortfuse** [comment]
This is probably the place for these types of questions. I suggest you close this and post here instead:

http://stackoverflow.com/questions/tagged/angular-material

**Comment by wesleycho** [comment]
Agreed, this seems much more like a support issue, and not a library issue. SO, IRC, or Slack are better venues for these types of questions.

**Comment by DevVersion** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by nischaym** [comment]
got it working after going through the flow. Thanks.
