### ISSUE TITLE
(md-datepicker) md-datepicker will delete all sibling nodes following it!!

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#8740]
**Actual behavior**:
md-datepicker will remove any sibling nodes that follow it. I have no idea how the demo is working

**CodePen** or Steps to reproduce the issue: *
http://codepen.io/shortfuse/pen/dXMbQm

**Angular Versions**: *
master

**Additional Information**:
Chrome V50/V51

**Comment by crisbeto** [comment]
You didn't close the tag.

**Comment by clshortfuse** [comment]
@crisbeto I did, but I guess it can't be self-closing. 

<md-datepicker ng-model="user.submissionDate" md-placeholder="test date" />

**Comment by crisbeto** [comment]
No it can't, I haven't seen Angular do custom self-closing tags.

**Comment by clshortfuse** [comment]
Yeah, closing this. TIL, I guess. Now to check all my code
