### ISSUE TITLE
Md-button with target blank stays focused after click

### ISSUE THREAD

**Issue by floreks** [angular/material#8749]
**Actual behavior**:
-  What is the issue?

When `md-button` is used with `target="_blank"` it stays focused after click. Using `md-tooltip` with it and hovering after click makes it visible until we click outside the button.
-  What is the expected behavior?

`md-button` should lose focus after click and tooltip should not be visible when button is not hovered.

**CodePen** or Steps to reproduce the issue:
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/WxwpwE
-  Details: Similar behavior reported in kubernetes/dashboard#877

**Angular Versions**: 
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0-rc2

**Additional Information**:
-  Browser Type: Chrome/Firefox
-  Browser Version: Latest
-  OS: Ubuntu 14.04

**Comment by DevVersion** [comment]
@floreks This is actually a known issue. See the issue #7963 and the pending PR #7965

**Comment by floreks** [comment]
Great. Looking forward to see it fixed and merged. Thanks.

**Comment by DevVersion** [comment]
@ThomasBurleson You marked this PR as planned for `1.1.0`. The PR, which would fix this, is _still_ pending. So it would be probably good if you take a look at it :smile:

**Comment by bryk** [comment]
Any update on this?

**Comment by DevVersion** [comment]
Still waiting for review on https://github.com/angular/material/pull/7965

**Comment by DevVersion** [comment]
Will track this now with #7963
