### ISSUE TITLE
Should be able to set max no. items to display in md-autocomplete dropdown

### ISSUE THREAD

**Issue by chrismortega** [angular/material#8751]
**Actual behavior**:
-  What is the issue? md-autocomplete only shows 2 or so items max when pulled down.
-  What is the expected behavior? Should be an option to display n items if the real-estate is available. 

You can write some css to make the list taller, but you have to hard-code it so that if the number of entries is smaller than your hard-coded value you end up with blank space. The md-autocomplete should be updated to allow a max, but still shrink when there aren't enough items to reach that max.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version: *
-  Angular Material Version: *

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
@chrismortega Sorry for the late response. I was looking at your issue right now.

I have some problems understanding your expected behavior.

- You want to be able to set the maximum amount of items shown in the dropdown?
- You want to be able to increase / decrease the height of the dropdown?

**Comment by chrismortega** [comment]
On higher resolutions an opened md-autocomplete could be much more effective if it took some advantage of the extra space it has to drop down. Currently it seems to have a max height. It would be better if I could specify a default height or num items to try to use. It would then need to determine if it has the space to use my desired height, and if not use as much as it can without being cut off. 

If that's still confusing please let me know. Thanks!

**Comment by DevVersion** [comment]
I think that's reasonable.

I have in mind an attribute like `md-dropdown-items="6"` and the it determines if those have enough place to show completely, otherwise it will shrink as less as possible.

I will try to take a look at this functionality and also confirm with the specs.

**Comment by chrismortega** [comment]
That would be a dream come true, ha. Thank you!

**Comment by chrismortega** [comment]
Oh one more clarification: if I specify md-dropdown-items="6" but I only have 3 items in the dropdown the height should shrink to show just those 3 items, rather than showing 3 items plus 3 more items with of blank of blank space.

**Comment by DevVersion** [comment]
@chrismortega Perfect, I actually thought about the same :) 

> Also the PR is now pending with #9307

**Comment by chrismortega** [comment]
Just had a look at the code. Looks awesome, thanks!
