### ISSUE TITLE
Autocomplete:  md-input-minlength and md-input-maxlength doesn't translate to input

### ISSUE THREAD

**Issue by eddieebeling** [angular/material#8753]
**Actual behavior**:
-  What is the issue? When adding md-input-maxlength on the autocomplete directive the attribute and values are not translated to the input when using the non-floating label autocomplete directive.
-  What is the expected behavior? ng-minlength and ng-maxlength are added to the input.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/eddieebeling/pen/KMzZyR
-  Details: Added md-input-maxlength="18" to the directive and the ng-maxlength is not rendered with the input element.

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: Webkit
-  Browser Version: Chrome
-  OS: Mac OS X
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
Going to add on there's another way to see this issue.

https://material.angularjs.org/HEAD/demo/autocomplete

On Floating Label:

* Focus Favorite State autocomplete
* Type `a`
* press Escape
* note that `a` isn't cleared
* Focus autocomplete
* Watch it disappear

**Comment by DevVersion** [comment]
We will address that with #4492. Thanks for the issue!
