### ISSUE TITLE
md-select: with required attr won't allow selection

### ISSUE THREAD

**Issue by dandanknight** [angular/material#8758]
**Actual behavior**:
-  What is the issue? *
When md-select has required attribute, it will not allow value to be selected.
-  What is the expected behavior?
Should allow item to be selected.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :

Select on left has `required` attribute, on right does not. Try selecting values.
[Codepen here](http://codepen.io/dandanknight/pen/WxwZLq)

And here is the same code but changed to 1.1.0-rc4...
[works in 1.1.0-rc4](http://codepen.io/dandanknight/pen/dXMgzW)

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: chrome
-  Browser Version: 52
-  OS: OSX
-  Stack Traces:

**Comment by DevVersion** [comment]
I can reproduce that issue.

I just investigated a bit and found the problem.
- The `required` attribute is always adding a validator to the `ngModelController`, which will validate the `$viewValue` to be **not** empty.

Actually the validator calls the `ngModelController.$isEmpty` function, which will just check the value.

We overwrite the `$isEmpty` method inside of the `select` component, and just check for the `value` being present as an option.

The way, we currently compare the value with the options, is not valid for items, which are objects.

Object (won't work currently)
```html
// Notice, that we use the plain item in ng-value here.
<md-option ng-repeat="item in vm.items" ng-value="item">{{ item.name }}</md-option>
```

Single Variable (This will work anyway) 
```html
// Notice, that we use the id of the item in ng-value here.
<md-option ng-repeat="item in vm.items" ng-value="item.id">{{ item.name }}</md-option>
```

**Comment by DevVersion** [comment]
Update: Going to track this with #8666
