### ISSUE TITLE
input label is too small following changes in datePicker

### ISSUE THREAD

**Issue by cgx** [angular/material#8760]
**Actual behavior**:
-  What is the issue?
> A change in the datePicker Sass file affects the font-size of all input labels.

-  What is the expected behavior?
> The font-size is 2px smaller and look better to its previous size.
> The faulty commit seems to be [4c65fc](https://github.com/angular/material/commit/4c65fce58c4e277c3a3de79212b83cb4c3cdf0ce).

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :

> [Before 4c65fc](http://codepen.io/flachapelle/pen/MeyLMK):
> ![screen shot 2016-06-14 at 11 24 38 am](https://cloud.githubusercontent.com/assets/1088448/16048741/3b0eeeb2-3223-11e6-806c-651c6f847876.png)
>  [After 4c65fc](http://codepen.io/flachapelle/pen/JKXxqJ):
> ![screen shot 2016-06-14 at 11 25 00 am](https://cloud.githubusercontent.com/assets/1088448/16048749/3fa82556-3223-11e6-8ea5-6443fbcca397.png)

**Angular Versions**
> v1.1.0-rc.5

**Comment by crisbeto** [comment]
Strange, I don't see the font size being modified anywhere.

**Comment by cgx** [comment]
The `md-flat-input` mixin does it.
