### ISSUE TITLE
md-autocomplete No Default Search Value

### ISSUE THREAD

**Issue by killerspaz** [angular/material#8767]
**Actual behavior**:
-  What is the issue? *
Without a default search value, md-autocomplete always shows the md-not-found directive.
-  What is the expected behavior?
By default, search value should be an empty string. 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/killerspaz/pen/dXMxYE
-  Details: Try removing the line where I set `this.$searchText` to an empty string

**Angular Versions**: *
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: * All
-  Browser Version: * All
-  OS: * All
-  Stack Traces: None

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This seems to be a reasonable request. 

Actually, the user is responsible for the filtering, so he may consider the searchText differently.
