### ISSUE TITLE
md-autocomplete Selection "Lifecycle" is broken

### ISSUE THREAD

**Issue by killerspaz** [angular/material#8768]
First, I realize this is multiple issues but they're all related to the entire lifecycle of a selected item. Honestly I feel the whole component is needing some serious love and QA.

**Actual behavior**:
-  What is the issue? * 
Where to even start?? 
1) Editing the selectedItem isn't reflected in AutoComplete until cleared, reopened, and reselected.
2) Removing from the values supplied to md-items does not update the auto-complete dropdown.
3) After removing an item from the values, and changing to another item, I am able to re-select the previous "non-existing" value.
4) Duplicate items are finicky at best.
5) Adding an item randomly and OFTEN will not appear in the dropdown list at all, unless searching for a substring causes it to reveal, but goes away again when clearing search text.
6) Arbitrarily, when either clearing searchText manually, programatically, or clearing the selected item value, the indeterminate progress bar will show up, and NEVER GO AWAY.
7) md-autoselect has absolutely no effect.
8) After adding and removing items, and clearing the searchText a few times, the dropdown completely breaks and will never re-appear. Not sure how to replicate, but it happens way too often.

-  What is the expected behavior?
1) Should be reflected in the md-item-text immediately. 
2) md-items should always be exactly what I tell it to be. I told it to be this.values | filter: $searchText, where $searchText is an empty string, I expect it to be exactly that.
3) Just... no... Should not be possible EVER!
4) Y U NO HAVE TRACK BY OPTIONS!??!?!?!?!?!?!?!? Making some seriously flawed assumptions here...
5) Obviously I should see all items added, duplicated or not. I also should not have to search to see them, nor have them disappear when search text is cleared.
6) There's literally never a reason for that bar to show up in my example. There's never a need to have ANY progress, as nothing ever returns a promise, or is even asynchronous in nature. This literally makes no sense from a UX perspective.
7) It should do what it says...
8) The lifecycle is clearly getting broken, and the component has no clue what to do. This should be fixed.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/killerspaz/pen/dXMxYE
-  Details: Try doing any of the above to be horribly disappointed.

**Angular Versions**: *
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0-rc4

**Additional Information**:
-  Browser Type: * All
-  Browser Version: * All
-  OS: * All
-  Stack Traces: None

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by killerspaz** [comment]
In regards to #2 listed above, my current work around is a hacky $timeout() call, temporarily storing values:

var tmp = myItem.subCollection;
myItem.subCollection = [];
$timeout(function() {
   myItem.subCollection = tmp;
});

Horrible, but at least it's semi-functioning as expected.

**Comment by ThomasBurleson** [comment]
This is not an appropriate issue for ngM1:

*  Please break into separate issues. 
*  Please insure that the issue is not already in the issue queue. 
*  Please provide a CodePen to verify fixes for your use cases.
