### ISSUE TITLE
md-dialog: sticky toolbar problem

### ISSUE THREAD

**Issue by bampakoa** [angular/material#8771]
**Actual behavior**:
-  What is the issue? *

When I open a dialog that references an Angular component, the toolbar of the dialog does not remain sticky on top.

-  What is the expected behavior?

The toolbar should remain fixed on top of the dialog.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

https://plnkr.co/edit/ASQ529LDAKEHY3aoU5vg?p=preview. 
The dialog shown is one from the samples but with multiple lines, in order to show the scrollbar. Two buttons exist: one that instantiates the dialog using a controller which behaves normally and another one using a component that shows the issue.

**Angular Versions**: *
-  Angular Version: 1.5.3
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Browser Type: * Google Chrome
-  Browser Version: * 51.0.2704.84 m
-  OS: * Windows 10
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
The problem is the extra DOM element for the component.

```html
<my-component></my-component>
```

The `my-component` component holds the form element.

Without components, it will be just added to the root `md-dialog`.

**Comment by bampakoa** [comment]
@DevVersion thank you very much for your answer. I am bit confused right now. Which element causes the trouble, the **my-component** or the **form**?. Should I remove the problematic one?

**Comment by ThomasBurleson** [comment]
This all works with Angular 1.5.7 and Angular Material 1.1.0-rc.5: [Working Plunkr](https://plnkr.co/edit/LKDzidgJLR4ZtEKXn2SF?p=preview)

**Comment by bampakoa** [comment]
@ThomasBurleson I cannot see any difference with the updated version of the libraries. In the second case, that of the component, the toolbar still does not remain fixed on the top.
