### ISSUE TITLE
mdDatepicker: Adding ng-blur event handling to datepicker (feature)

### ISSUE THREAD

**Issue by tspendel** [angular/material#8779]
**Description**
We are using mdDatepicker in one of our projects. One of main project requirement is saving/updating values on blur (unfocus). Unfortunately mdDatepicker doesn't support that behaviour. This is especially an issue when user is entering the date manually by input field.

In addition current component behaviour by executing update function by ng-change is causing problems. This is because form validations are reloaded after ng-change method execution. 

**Actual behavior**:
-  What is the issue?
Lack of blur event

-  What is the expected behavior?
Datepicker supports ng-blur directive

**CodePen** or Steps to reproduce the issue:
-  CodePen Demo which shows your issue :
http://codepen.io/tspendel/pen/YWWPjw

-  Details:

Steps:

1. Type invalid date
2. Pick correct date from datepicker - The value is not saved (but it should be)
3. Pick correct date from datepicker once again - The value is saved now

**Angular Versions**: *
-  Angular Version: 1.4.9
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: Google Chrome
-  Browser Version: 51.0.2704.84 m
-  OS: Windows 10
-  Stack Traces: -

**Comment by crisbeto** [comment]
We already have an issue about forwarding more of these attributes to the input. See https://github.com/angular/material/issues/8447

**Comment by DevVersion** [comment]
This will play together with #4492. I was looking for a elegant solution. Will follow up with more details, once we have a good approach.
