### ISSUE TITLE
flexOrder: Add responsive flex-order attributes

### ISSUE THREAD

**Issue by mzbyszynski** [angular/material#878]
In  0.5 there were a series of ```layout-order-xx``` attributes defined in layout.scss that allowed you to change the order of items in your layout based on the viewport size. Here is the explanation from the docs in 0.5.x:

>Child elements of a layout container can have their order changed through the use of the    <code>layout-order</code> attribute, and respective responsive attributes such as: layout-order-sm, layout-order-md, and layout-order-lg. Reordering elements is useful when the placement of a cell should be changed depending on the viewport size.

In 0.6,x, ```layout-order``` was renamed to ```flex-order``` and all the responsive versions were removed, so ```flex-order="2"``` works but ```flex-order-sm="2"``` does not. 

The ability to change the order of child elements in a grid layout based on the viewport size seems like a really useful feature. Actually, I tried to use it today in my project and that's how I realized it was no longer supported.

I've searched through the issues and forums but didn't really find any mention of this, but my apologies if I missed the explanation somewhere. Was there a reason that this feature was removed? If not I'd like to request that ```flex-order-xx``` classes for all the viewport size suffixes be added back! I'm happy to submit a PR for this if it helps.

Thanks!

-Marc

**Comment by ajoslin** [comment]
Added via 3e4530785c29650ff46cf7688f0b154adb9a7042
