### ISSUE TITLE
Using angular-translate, md-select label not being translated until select list is clicked

### ISSUE THREAD

**Issue by rhclayto** [angular/material#8781]
I have a form using md-select with a label that is to be translated by the angular-translate module. The problem I am having is that when I change the language, all other translated strings including other Angular Material labels are being translated immediately, but the label for the md-select doesn't change *until* the select box is clicked. If I then click away from the select list (i.e., don't choose an option), the select box is now displayed with the new translation.

Here is a CodePen demonstrating the problem (in Firefox & Chrome latest versions): http://codepen.io/rhclayto/pen/RRRdGJ

In the example, click one of the language links to change the language. You will see that the text 'Nose' as well as the label for the name field change immediately, but the select label doesn't. Click on the select input then click away without selecting an option. Now the label has changed.

Any ideas why this is occurring or how to work around it?

**Comment by DevVersion** [comment]
The `md-select` is only syncing / updating the label when the ngModel is requesting a `$render`.

You can force a label `sync` / `update` by using the following workaround:

```js
var mySelect = document.querySelector('md-select#mySelect');
var ngModelCtrl = angular.element(mySelect).controller('ngModel');

// Manually trigger the $render to update the label
ngModelCtrl.$render();
```

**Comment by rhclayto** [comment]
Hey, many thanks.

That worked for me in the Codepen with one change. When I put that in my function to change the language, on the first language change it did nothing. On the second change it did update the label in the view, but out of sync, one language change behind. I did an ugly hack so that the model value of the select changes every time (between null & an empty string), no matter whether that select is changed by a user or not. That seems to make $render() kick into effect on the first language change.

```javascript
vm.changeLang = function(lang) {
    // You have to change the model on the very first click or $render() won't do anything--until the second click, at which time it is one click behind & out of sync.
    if (vm.securityQuestion === '') {
      vm.securityQuestion = null;
    }
    else if (vm.securityQuestion === null) {
      vm.securityQuestion = '';
    }
    vm.language = lang;
    $translate.use(vm.language);
    // Manually trigger the $render to update the select label.
    var mySelect = document.querySelector('md-select#mySelect');
    var ngModelCtrl = angular.element(mySelect).controller('ngModel');
    ngModelCtrl.$render();
  }
```

Any ideas how i can get the $render() to work the first time, without resorting to this hideous hack of mine?

Thanks again for the tip!

**Comment by rhclayto** [comment]
A further problem with this workaround, in this particular case, is that when angular-translate is told to translate to a new language, it is pulling a translation file asynchronously. If it doesn't arrive before $render() is called, the translation doesn't take place. I'm currently working around *that* with $timeout.

I know that's not an Angular material issue, but it's relevant to the workaround suggested here, so I thought I'd comment.

**Comment by ThomasBurleson** [comment]
Deprecated. Will not fix for ngMaterial 1.x.
