### ISSUE TITLE
md-input-container: textarea gets style="padding: 0px" when JQuery is present

### ISSUE THREAD

**Issue by atorma** [angular/material#8782]
**Actual behavior**:
-  What is the issue? * A textarea within an md-input-container element gets padding: 0 applied in element style 
-  What is the expected behavior? Padding of textarea is not modified

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : 
   - With JQuery 1.12.4: http://codepen.io/atorma/pen/xOONZK
       - Reproduces with JQuery 2.2.4, 3.x not tested
   - Without JQuery: http://codepen.io/atorma/pen/OXXYbx
   - Compare the padding-lefts of the textareas in the two
-  Details: 
   - This seems to be caused by line 453 in file input.js: `element.css('padding', null);`. This does not reset style in JQuery (it may have worked in old versions). The line should be `element.css('padding', '');`

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: * Chrome
-  Browser Version: * 51.0.2704.84 m
-  OS: * Windows 7
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
We remove it temporarily to measure the line height, but this definitely a bug. I'll take care of it.

**Comment by atorma** [comment]
I guess the correct fix is not `element.css('padding', '');` (removes padding) but to store and put back the original padding. The textarea might have an inline style.
