### ISSUE TITLE
Desktop and tablet material's keylines support

### ISSUE THREAD

**Issue by Deliber** [angular/material#8783]
For all angular material's components, for example in the toolbar, the material's keylines applied are those of the mobile. So for example, i see a padding-left of 16 px although I am on desktop devices where material's keylines suggest must be 24px. 

From yours scss:
`.md-toolbar-tools { padding: 0 $toolbar-padding; /*   $toolbar-padding fixed to 16px  */ }`

This isn't the only problem i found for desktop, but there are much more problem with all the desktop keylines.

There is a way to apply the desktop's keylines with Angular Material or i'm obligated to customize these behaviors on mine css? Are the desktop's keyline supported on angular material? Are they planned in future release?

Thanks for your help and ask me if you need more details.

**Comment by Splaktar** [comment]
If you consume the `.scss` files, you can override `$md-toolbar-padding` to be `24px` along with many of the other Sass variables in AngularJS Material.

- You can find the larger SCSS bundles from releases [in our bower-material repo's modules/scss directory](https://github.com/angular/bower-material/tree/master/modules/scss).
- You can only get the modular SCSS bundles from [our source repo](https://github.com/angular/material/tree/master/src/components/toolbar).

If desired, we could probably look at publishing the SCSS files in our bower-material repo's [modules/js directory](https://github.com/angular/bower-material/tree/master/modules/js/toolbar).
