### ISSUE TITLE
mdPanel position broken inside dialog

### ISSUE THREAD

**Issue by twizzzlers** [angular/material#8784]
**Actual behavior**:
-  Issue: When trying to add panels inside a dialog, their position gets broken *
-  What is the expected behavior? Correct panel positions... 

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : I actually made in jsfiddle. https://jsfiddle.net/twizzlers/37k0ry60/29/

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: v1.1.0-rc.5-master-42833aa

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 50.0.2661.102
-  OS: Ubuntu 14.04

The problem may be mine in the relativeTo and the attachTo configurations, just letting you guys know about this problem. Thanks in advance for any help =) PS: Sorry about my English...

**Comment by bradrich** [comment]
If you change the attachTo property of your md-panel config to `attachTo: angular.element(document.body)`, delete line 31 which is the openFrom property, and change the zIndex from 2 to 89. This should make your panels open properly.

**Comment by twizzzlers** [comment]
Ok, it was my fault, should have read more. Thanks for your attention =)

**Comment by ThomasBurleson** [comment]
Thx @bradrich
