### ISSUE TITLE
mdSidenav: rendering issue on Safari when `md-sidenav` is the root element in a component.

### ISSUE THREAD

**Issue by danjarvis** [angular/material#8787]
**Actual behavior**:
-  What is the issue? * When `md-is-locked-open` is true, the Sidenav will overlap the content area if the sidenav is the root element in an angular component.
-  What is the expected behavior? The Sidenav should not overlap the main content area when `md-is-locked-open` is true and the Sidenav is the root element in an angular component.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/danjarvis/pen/BzjREX
-  Details: This is only reproducible using Safari (tested 8.x and 9.x). If not using an angular component, the issue is not observed.

**Angular Versions**: *
-  Angular Version: 1.5.3
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Browser Type: * Safari
-  Browser Version: * 9.0.3
-  OS: * 10.11.3
-  Stack Traces:
-  Screen Shot: 
![image](https://cloud.githubusercontent.com/assets/116640/16156237/4681b2ba-3481-11e6-9946-cb6935f1c59b.png)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by danjarvis** [comment]
Workaround: add `flex-shrink: 0;` to the component element.

**Comment by bradrich** [comment]
@danjarvis That is one of the big "gotchas" when working with components, in that the component does not have the **replace** option that a directive does. Good catch on the added flex-shrink style as that is the way that you would get that to work.

I am closing this as it is not a Material issue.
