### ISSUE TITLE
mdAutocomplete - Problem when md-selected-item become null 

### ISSUE THREAD

**Issue by fif1973** [angular/material#8788]
**Actual behavior**:
-  What is the issue? *
When  md-selected-item change to null or undefined value the field stay with previous value

-  What is the expected behavior?
the field should be cleared

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : 

[http://codepen.io/fif1973/pen/oLzvbj?editors=1010](http://codepen.io/fif1973/pen/oLzvbj?editors=1010)
-  Details:

click on right list on 1st item, the form is updated with correct values

click on right list on 2nd item, the form is updated with correct values

click on right list on 3rd item, the form is updated but the field 'company' should be clear and it stay with previous value

**Angular Versions**: *
-  Angular Version: same issue with AJS 1.4.8 and 1.5.3
-  Angular Material Version: same issue with AM 1.0.9 and 1.1.0-rc2 

**Additional Information**:
-  Browser Type: Chrome  
-  Browser Version: Version 51.0.2704.84 (64-bit)
-  OS: OSX
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by danjarvis** [comment]
Workaround: Add `flex-shrink: 0;` to the component element.

**Comment by fif1973** [comment]
into my example (http://codepen.io/fif1973/pen/oLzvbj?editors=1010), where add flex-shrink: 0; ?

**Comment by danjarvis** [comment]
@fif1973 oh wow I'm sorry! I meant to include this comment in #8787 

I will delete the comment to avoid further confusion.

**Comment by DevVersion** [comment]
The problem is that, `md-selected-item` is not synchronized with the `searchText`. 

The `selectedItem` will be properly cleared, but the `searchText` wont be affected of that.

---
We probably have to consider clearing the `searchText`, when the `selectedItem` will be cleared.

**Comment by fif1973** [comment]
Effectively when i set searchText to null when a person is selected (into my codepen example), it works like expected. 

$scope.setSelectedPerson = function(person) {
    $scope.searchText=null;
    $scope.selectedPerson = person;
  };

but it will be more intuitive if it can be do automatically
