### ISSUE TITLE
How to apply Angular Material design for dynamic html loaded from js file.

### ISSUE THREAD

**Issue by Abhinay1235** [angular/material#8792]
how to apply angular material design when i load html of a Div in this way

angular.element('#DIV').html('<md-checkbox class="md-primary">Checkbox 1</md-checkbox>');

**Comment by DevVersion** [comment]
You have to recompile the DOM element manually, by using the `$compile` service.

Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
