### ISSUE TITLE
Toolbar with shrink option hides scroll down button when toolbar is visible

### ISSUE THREAD

**Issue by alexpozzani** [angular/material#8801]
**Actual behavior**:
-  What is the issue? *
Using md-toolbar with md-scroll-shrink option is hiding the scroll down button of the scrollbar when toolbar shows up.
-  What is the expected behavior?
The scrollbar must be fully visible.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
(its just a copy of the demo)
http://codepen.io/anon/pen/XKjNXG

-  Details:

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version:  v1.1.0-rc.5 (in old versions it also occurs)

**Additional Information**:
-  Browser Type: Chrome, Firefox
-  Browser Version: *
-  OS: Windows
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
will not fix.
