### ISSUE TITLE
md-grid-tile with ng-if occupy twinkle

### ISSUE THREAD

**Issue by hanquf1** [angular/material#8806]
i want use md-gid-tile with `ng-if` or `ng-show`
but `ng-show` use occupy the space. [#6597](https://github.com/angular/material/issues/6597)

So i used the `ng-if` but it occupied twinkle

here [simple pan](http://codepen.io/hanquf/pen/VjKQgp?editors=1010).

when several times click  `twinkle` button, you can see the twinkle Word bunch on the button below

I would like to remove the twinkle Word bunch  
:(  help me...

**Comment by ThomasBurleson** [comment]
Will not fix for Material v1.x.
