### ISSUE TITLE
<code> tags in demos don't do anything in codepen

### ISSUE THREAD

**Issue by uqcgreen** [angular/material#8807]
**Actual behavior**:
-  What is the issue? You click on "Edit in codepen" for Colors (might apply to others) and the <code> tags don't do anyting, and the supposedly escaped angular material tags within them just display as normal
-  What is the expected behavior? It should escape the html 

**CodePen** or Steps to reproduce the issue:
-  CodePen Demo which shows your issue : https://material.angularjs.org/latest/demo/colors
-  Details: Click the first edit in codepen

**Angular Versions**:
-  Angular Version: N/A
-  Angular Material Version: N/A

**Additional Information**:
-  Browser Type: N(W)A
-  Browser Version: N(R)A
-  OS: N(D)A
-  Stack Traces: N(S)A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Thanks for the issue. This is a known issue and currently blocks the select demo from running inside of a codepen. Let's track this issue in #8761
