### ISSUE TITLE
md-datepicker not selecting year

### ISSUE THREAD

**Issue by bloArribas** [angular/material#8810]
I am using md-datepicker. It works as expected, except it will not show the year selector.

Is this caused by using the wrong version?

I need it show the year selector.

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.0.9

**Comment by marcomafessolli** [comment]
According to the [CHANGELOG](https://github.com/angular/material/blob/master/CHANGELOG.md), year view was introduced in **1.1.0-rc.5** version.

**Comment by crisbeto** [comment]
Correct, it was in 1.1-rc5.
