### ISSUE TITLE
Angular material styles for Dynamic html

### ISSUE THREAD

**Issue by Abhinay1235** [angular/material#8812]
I am building this checkboxes dynamically. I want angular material design to be applied here for checkboxes. 

var html = '<md-checkbox class="md-primary">Checkbox</md-checkbox>';

angular.element('#DIV_ID').html(html);

Normal browser default checkboxes are created here. Angular Material styles are not applied. What should i do ?

**Comment by EladBezalel** [comment]
@Abhinay1235 to create a dynamic mdCheckbox directive you need to use [`$compile`](https://docs.angularjs.org/api/ng/service/$compile) service, please ask those kind of questions in our forums
