### ISSUE TITLE
md-stretch-tabs always with pagination

### ISSUE THREAD

**Issue by asanin-2sol** [angular/material#8813]
Is there a way to stretch the tabs for all sizes, except when the pagination is visible?

1. This is how the tabs are stretched with no pagination (as desired):
![no-pagination-stretch](https://cloud.githubusercontent.com/assets/8309626/16217856/b89be712-37ba-11e6-8ed1-5bc2e025ff92.png)

2. However, this is how they look on a smaller screen with pagination
![pagination-stretch](https://cloud.githubusercontent.com/assets/8309626/16217860/bfb1929a-37ba-11e6-9457-dd550484dd56.png)

3. This is how it looks on the smaller screen without stretching
![pagination-no-stretch](https://cloud.githubusercontent.com/assets/8309626/16217858/bd4a5d02-37ba-11e6-872f-649c263240f1.png)

Is there a way to achieve 1 and 3? That is, to stretch for every size except when pagination is needed?

Thanks,
Andres

**Comment by ThomasBurleson** [comment]
Will not fix in ngM1.
