### ISSUE TITLE
ripple shows strangely after chrome updated

### ISSUE THREAD

**Issue by cyx8808** [angular/material#8815]
After chrome stable channel updated to version 51.0.2704.103, the ripple shows strangely.

**Comment by JingkaiZhao** [comment]
same issue happens with me.
the ripple animation duration is too short (looks like blink) under latest chrome version!

**Comment by DevVersion** [comment]
@ThomasBurleson - @crisbeto and I will probably take a look at this today.

**Comment by EladBezalel** [comment]
I'll try to take a look :)

**Comment by EladBezalel** [comment]
@DevVersion seems like somehow `md-ripple-active` class is being removed early, couldn't figure why `fadeInComplete` is called too early..

**Comment by cyx8808** [comment]
I think the problem is not fadeInComplete is called to early. 

I found that Chrome changed the rule of showing transition. When a ripple is active, we change the opacity from 0 to .2 with a swift-ease-out-timing-function during 0.9s. Let's say after 0.5s mouseup triggered and the opacity is .1 at the moment, then we remove "opacity: .2". Before version 51 it still takes 0.9s to change opacity from .1 to 0, but in the last version it only takes .5s to change opacity from .1 to 0 (I'm not sure if the time is .5s, but I think it's the same as the time it takes to play animation before), it's much shorter than 0.9s, so it seems like the ripple disappear suddenly.

I don't know whether Chrome will fix this in the future, I sent a pull request to fix this issue at present.

**Comment by crisbeto** [comment]
@cyx8808 I believe this will change the way the ripple behaves on other browsers.

**Comment by cyx8808** [comment]
@crisbeto Yes, but I think the difference can hardly perceive, you can test. Or maybe there are better ways.

**Comment by ThomasBurleson** [comment]
Fixed with SHA 15da974d51795eb5e0919946ae165a4093a74799
