### ISSUE TITLE
ng-leave animation on element starts with delay with md-input-container inside it

### ISSUE THREAD

**Issue by stijnvn** [angular/material#8817]
**Actual behavior**:
-  What is the issue? 

ng-leave animation on an element starts with delay when it has an md-input-container inside it. It waits until the animation on the input is finished.

-  What is the expected behavior?

It should start the animation immediately.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :

 https://plnkr.co/edit/yCrI68cY9EgwkWtsrXfC?p=preview

**Angular Versions**: *
-  Angular Version: 1.5.7
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: Version 51.0.2704.103 (64-bit)
-  OS: OS X

**Comment by DevVersion** [comment]
This looks like a bug and should be the same as in https://github.com/angular/material/commit/9ef50a7a8c1ab003b54102a85fd3a713aab80294.

**Comment by stijnvn** [comment]
I guess it is not a bug, but the delay is caused by the max-height (see for example http://stackoverflow.com/questions/18087098/how-to-remove-delay-on-css3-slide-out-transition-which-uses-max-height-transitio)
