### ISSUE TITLE
content: scrollable content shifts up a couple pixels on touch

### ISSUE THREAD

**Issue by adare** [angular/material#8821]
**Actual behavior**:
-  What is the issue? *
  There is a couple pixel content shift up when clicking into an md-content which has scrollable overflowing content. This occurs when the viewable area is at the top of the content and only on mobile device browsers.
  This issue does not occur when clicking into the content area of an md-content which is encapsulated by another md-content.
-  What is the expected behavior?
  The content area of an md-content should not shift when interacting with elements within it on device browsers.
  **CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
  http://codepen.io/anon/pen/qNqNmr
-  Details:
  This issue can be reproduced in Chrome 51 and Firefox 47 on Android 6.0.1.
  It can also be reproduced using Device Mode in Chrome 52 on Windows 7.
  It can be observed on the angular material website. https://material.angularjs.org/latest/

**Angular Versions**: *
-  Angular Version:
  1.5.5
-  Angular Material Version:
  1.0.8

**Additional Information**:
-  Browser Type: *
  Mobile Chrome/Firefox
-  Browser Version: *
  Chrome 51, Firefox 47
-  OS: *
  Android 6.0.1
-  Stack Traces:

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by Splaktar** [comment]
I updated the [CodePen](https://codepen.io/Splaktar/pen/VBYJvx) to 1.1.10 and I also tested with 1.0.8. I wasn't able to reproduce this issue on an Android device in Chrome or on macOS in Chrome's device mode with an iPhone 5, Pixel 2, or Pixel 2 XL.
