### ISSUE TITLE
Question: md-virtual-repeat-container 

### ISSUE THREAD

**Issue by ivanzvakoms** [angular/material#8822]
https://groups.google.com/forum/#!topic/ngmaterial/HFanzHvYS18 - is there a chance that md-virtual-repeat-container will support dynamic height of items like it does in http://kamilkp.github.io/angular-vs-repeat/#?tab=6 ? 

Because currently with the latest version(1.1.0-RC5) I have scrolling problems when elements in vertical container have different heights. I understand that this issue is because this possibility is isn't supported, so I want to clarify if you have some plans to add similar behavior like in component above.

**Comment by ThomasBurleson** [comment]
Not in v1.x. This should be addressed in v2.x
