### ISSUE TITLE
mdDatepicker: disabled styles don't match other inputs

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#8823]
**Actual behavior**:
-  What is the issue? *
mdDatepicker component styles do not match other input components when disabled.
-  What is the expected behavior?
The datepicker match the input disabled styles

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
http://codepen.io/mckenzielong/pen/wWozWv
-  Details:
Notice how the label / placeholder text is darker, and the bottom border is inconsistent.

**Angular Versions**: *
-  Angular Version: 1.5.6
-  Angular Material Version: 1.1.0 rc.5

**Additional Information**:
-  Browser Type: Chrome/ Opera
-  Browser Version: 50/36
-  OS: Windows 7 64 bit
-  Stack Traces: N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
Tagging this to check with #8757 before finishing.

**Comment by crisbeto** [comment]
@clshortfuse I'm pretty sure that we don't even try to apply that dotted bottom border, we just hide the regular one.

**Comment by crisbeto** [comment]
@mckenzielong I rechecked it. The stand-alone datepicker doesn't match the other inputs, but if you wrap it with `md-input-container`, like you do with the inputs, then it will. [Here's an updated codepen.](http://codepen.io/crisbeto/pen/wWgxRY)
