### ISSUE TITLE
mdMenu: bar header is not readable when using font with a light color.

### ISSUE THREAD

**Issue by cnestor1** [angular/material#8825]
-  What is the issue? *
**Actual behavior**:
When hovering on a menu item, the menu title background color default to grey. Since my font is white, it's very hard to read it. I tried to override the css but haven't been able to override the menu title background while hovering on a menu item.

![snapshot2](https://cloud.githubusercontent.com/assets/13889121/16269525/9ce8398e-3860-11e6-9964-0d39702e9231.png)

```css
.md-menu:hover{
  cursor: pointer;
  background-color: green;  
}
```

-  What is the expected behavior?
We should be able to customize the menu highlight when using dark background and light font color to improve user experience.

**CodePen** or Steps to reproduce the issue: *
This is the menu bar Angular example slightly modified to demonstrate the issue:
http://codepen.io/cnestor/pen/PzbENv

**Angular Versions**: *
-  Angular Version: Latest
-  Angular Material Version: Latest

**Additional Information**:
-  Browser Type:  Chrome
-  Browser Version: Version 50.0.2661.86 (64-bit)
-  OS: CENTOS 7
-  Stack Traces:

**Comment by EladBezalel** [comment]
related to #8757

**Comment by EladBezalel** [comment]
@cnestor1 after digging into it i figured that although it sounds reasonable, it's not documented in the specs, therefor we cannot apply a fix the following the Material Design Spec.

As you override the header colors and text, you should also use css override:
```css
md-menu-bar md-menu._md-open > button {
  background: ...
}
```

**Comment by clshortfuse** [comment]
@cnestor1 I will just add, I strongly suggest you take a look at [$mdThemingProvider](https://material.angularjs.org/latest/api/service/$mdThemingProvider). 

It's built to allow you to inject custom styles into your application. I suggest reworking [menu-bar.scss](https://github.com/angular/material/blob/master/src/components/menuBar/menu-bar.scss) to your liking using the `primary` or `accent` color, converting it to CSS, and then passing that to `registerStyles`.

**Comment by zendu** [comment]
Using following snippet in CSS solved the problem.
```
md-menu.md-open > button {
  background: ...
}
```
