### ISSUE TITLE
md-datepicker does not support date format DD-MMM-YYYY on Firefox and IE11.

### ISSUE THREAD

**Issue by mdiaATarinc** [angular/material#8826]
**Actual behavior**:
-  What is the issue? When the datepicker is configured via formatDate function to show dates in format DD-MMM-YYYY(e.g 22-Jun-2016) and the date is changed via the input text field it validates fine on Chrome but on Firefox and IE11 it shows that "The entered value is not a date!". This problem does not happen when the date selection is made via the datepicker dropdown.
-  What is the expected behavior? The datepicker should not invalidate the user entered date via the text box in this format on Firefox and IE11.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/anon/pen/QEGmyJ
-  Details: While changing date using the input text box on Firefox and IE11 the datepicker shows the validation message "The entered value is not a date!".

**Angular Versions**: *  
-  Angular Version: 1.5.5
-  Angular Material Version: All 1.x versions.(1.0.1 - 1.1.0-rc5)

**Additional Information**:
-  Browser Type: * Firefox, IE11
-  Browser Version: * Firefox 46.0.1, IE 11 11.0.18015.
-  OS: * OS X Yosemite 10.10.5
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
That's because you also need to override the `parseDate` method, in order to be able to parse your custom formatting. [Check the docs.](https://material.angularjs.org/HEAD/api/service/$mdDateLocaleProvider)

**Comment by mdiaATarinc** [comment]
Thanks for the quick reply @crisbeto. I wish it was more obvious from the documentation. I'm still having trouble understanding why Chrome is more forgiving while Firefox and IE isn't?

**Comment by crisbeto** [comment]
Yeah I was thinking that we could show a warning if you overwrote `formatDate`, but not `parseDate`. I think it might have to do with the locale, but I'm not sure really. All the default `parseDate` does is pass the input value through `new Date()`.
