### ISSUE TITLE
mdNavBar: increase style parity with mdTabs

### ISSUE THREAD

**Issue by csvn** [angular/material#8827]
**Actual behavior**:
-  What is the issue? *
  mdNavBar is missing styling for `md-primary` or `md-accent`. The selected ink-bar for mdNavBar is missing the sweet animation that mdTabs has.
-  What is the expected behavior?
  A closer match to tabs in visual style, with alternate colors (see codepen and image below)
  ![image](https://cloud.githubusercontent.com/assets/8770194/16229491/5b015882-37bd-11e6-9f1a-02f15487558a.png)

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
  http://codepen.io/csvn/pen/QEGmeW
-  Details:

**Angular Versions**: *
-  Angular Version: Any
-  Angular Material Version: 1.1.0-rc5

**Additional Information**:
-  Browser Type: *
  Any
-  Browser Version: *
  Any
-  OS: *
  Any
-  Stack Traces:

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by dgpoon** [comment]
Gabe, can you also remember to eliminate the rounded borders off of the nav bar items?

![nav_bar_item_border](https://cloud.githubusercontent.com/assets/20428935/16787536/d6d1b44e-4851-11e6-8ae7-2bf0075c849f.png)

Thanks,
Daniel

**Comment by marshall007** [comment]
Also note that since `md-nav-item` uses `md-button` (and `md-tab` does not), styling parity is dependent on a resolution to #9154 (i.e. PR #9449).

**Comment by davecyen** [comment]
+1. Thanks @csvn for documenting
