### ISSUE TITLE
toolbar: mdScrollShrink not behaving correctly with autoscroll="true"

### ISSUE THREAD

**Issue by austin4perezident** [angular/material#8828]
**Actual behavior**:
-  Md-Toolbar is shown only partially when you transition from state to state while using Md-Scroll-Shrink. I am using `md-scroll-shrink` and have `autoscroll="true"` on `ui-view`.
-  I just want to be able to show full md-toolbar when state is changed. On mobile, it causes an unwanted bouncing behavior when you scroll to the top of page.

**CodePen** or Steps to reproduce the issue: *
-  If you look at [this](http://jaacmedia.com/) website and click on the contact button on top right of Toolbar you can see how Md-Toolbar is shown only partially when state is changed.

**Angular Versions**: *
-  Angular Version: 1.3.7
-  Angular Material Version: 1.0.6

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 51+
-  OS: OSX 10.11.5
-  Stack Traces:

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by KelvinOm** [comment]
+1
on mobile:
![untitled](https://cloud.githubusercontent.com/assets/11555074/16495163/ce451836-3ef4-11e6-8b88-6b7925fb6597.gif)

**Comment by dbo35** [comment]
take a look at <md-content>

when you nest them like in the website you linked bad things happen.
Looks like the app is counting the wrong scroll position - when the right scroll bar reaches the top, the toolbar is completely shown.

![scrollbars](https://cloud.githubusercontent.com/assets/11125569/16790656/b369f596-4885-11e6-97b1-02187bf7f67e.png)

**Comment by Splaktar** [comment]
The linked website no longer exists and there is no CodePen demo, so I'm going to close this.
