### ISSUE TITLE
We can not move cursor to edit inputted value in text boxes in mobile website in FireFox mobile Browser

### ISSUE THREAD

**Issue by jatinbphp** [angular/material#8829]
Hello,

We are not able to move cursor by holding mobile key board cursor from one place to another for edit text.
It Only not works in Mobile Fire fox version. Please let me know if any solution is there for this.
You can check that issue by visiting below website in Mobile FireFox browser.
https://material.angularjs.org/1.0.5/demo/input
**Actual behavior**:
-  What is the issue? *
-  What is the expected behavior?

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version:
-  Angular Material Version:

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Please retest with v1.1.0-rc.5 or later. Will reopen if this problem persists.

**Comment by tautvydasp** [comment]
I'm able to move my cursor only by dragging it on Chrome Mobile v51.0.2704.81, but I can't set cursor position by clicking on the text where I want it to be. When I "focus" on input/textarea, cursor automatically appears at the end of the text, all other clicks on input/textarea does absolutely nothing, but I would expect it to change position of the cursor to be where I clicked. It's quite a hassle to drag cursor from bottom of textarea to the top, especially when text area is bigger than the screen. 

I'm able to reproduce this bug by emulating touchscreen devices such as iphone 6, galaxy s6 on Google Chrome Desktop browser v52.0.2743.82 (thought it might be helpful to know).

Angular material versions used: v1.1.0-rc.2, v1.1.0-rc.5, v1.1.0-rc.5-master-8568cee.

**Comment by jaspercacbay** [comment]
Encountered same issue. Any updates on this?
