### ISSUE TITLE
Ripple: Button ripple effect is not included in dist build

### ISSUE THREAD

**Issue by borgdylan** [angular/material#883]
Currently the ripple effect on buttons is only included in the docs build but not in the "normal" build that happens by issuing "gulp".

**Comment by robertmesserle** [comment]
I cannot recreate this issue.  I have tried this locally by building fresh, as well as pulling versions from the latest bower-material:

http://codepen.io/robertmesserle/pen/7aa6e2a29c43a5e5742f66c131cceb9d

**Comment by robertmesserle** [comment]
Closing for now, does not appear to be an issue in the latest build.
