### ISSUE TITLE
Text disappears from md-autocomplete when focus is removed

### ISSUE THREAD

**Issue by PresidentCamacho** [angular/material#8830]
I've a ng-repeat wrapper for md-autocomplete that looks like this:

```
<div>
    <md-input-container ng-repeat="param in paramlist" flex="85">
        <md-autocomplete md-selected-item="selectedItem"
                            md-search-text="searchText"
                            md-items="item in querySearch(searchText)"
                            md-selected-item-change="variableSelected(param, item)"
                            md-search-text-change="parameterChange(param, searchText)"
                            md-item-text="item"
                            md-floating-label={{param.displayname}}
                            md-no-cache="true">
            <span md-highlight-text="searchText">{{item}}</span>
        </md-autocomplete>
    </md-input-container>
</div>
```
It works good but I've one graphical problem:

http://g.recordit.co/auo8A3y7VQ.gif

When selecting an item from the md-autocomplete or entering text and then unfocus the md-autocomplete the text disappears. Anyone knows what I'm missing?

**Comment by DevVersion** [comment]
@PresidentCamacho Please provide a demo for your issue. Otherwise we wouldn't be able to recognize the issue.

**Comment by DevVersion** [comment]
Closing this as it's not an issue. You are wrapping the autocomplete inside of an `md-input-container`, which is not valid.

**Comment by omatrot** [comment]
Are there any other scenarii where this is invalid ?
I'm having the exact same problem Inside a md-dialog.

**Comment by nahidhasanswe** [comment]
Remove <md-input-container> tag from your code. This will work fine to me. 
Thanks

**Comment by brunolellis** [comment]
In case someone is having the same problem, try removing `<md-input-container>` tag.
