### ISSUE TITLE
mdAutocomplete doesn't show ng-message when inside an ng-repeat

### ISSUE THREAD

**Issue by scote** [angular/material#8831]
**Actual behavior**:
-  What is the issue? * ng-message doesn't show when the autocomplete is inside an ng-repeat.
-  What is the expected behavior? It should the validation message.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : http://codepen.io/scote/pen/RRomOK?editors=1011
-  Details: 
  1. Click to focus on first autocomplete.
  2. Unclick outside the autocomplete to show the validation error message.

**Angular Versions**: *
-  Angular Version: 1.4.8
-  Angular Material Version: 1.0.9, 1.1.0-RC5

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 52
-  OS: Windows 10
-  Stack Traces: None

Anyone have a workaround to show the ng-message?

**Comment by DevVersion** [comment]
This issue is related to your current setup.

It seems like the `ng-if` on the `ngMessages` never becomes visible. 
You may have some incorrect names for the `input control` and `ngMessages` object.

To show that it works as expected.
Here is a demo with `ng-repeat` and working ngMessages.

- http://codepen.io/DevVersion/pen/EyZQpr

**Comment by scote** [comment]
In my case, my ng-repeat iterate on a list of address object. So I don't have a unique name for my input unless I use the index attribute from the ng-repeat component.

**Comment by shirazz** [comment]
@scote i am facing the same issue. Any inputs regarding the same?

**Comment by 1ka** [comment]
Ditto, $index is not resolved in ng-messages when included in the Autocomplete. Hardcoding the index works but is not the solution
