### ISSUE TITLE
md-slider: Vertical Slider will not work in md-Sidenav

### ISSUE THREAD

**Issue by eliber1** [angular/material#8832]
**Actual behavior**:
-  What is the issue? *
The md-slider cannot be placed vertically in the md-sidenav
https://material.angularjs.org/latest/demo/sidenav
https://material.angularjs.org/latest/demo/slider
-  What is the expected behavior?
When I add md-vertical attribute to the md-slider it will be vertical in any part of the project, however when placed in the md-sidenav it stays horizontal

**CodePen** or Steps to reproduce the issue: *
-  plnkr Demo which shows your issue 
https://embed.plnkr.co/7lBplI/ 
-  Details:
Note how when sidebar is open the md-slider is horizontal and not vertical despite have the vertical attribute
**Angular Versions**: *
-  Angular Version: 1.5.3
-  Angular Material Version: 1.0.9

**Additional Information**:
-  Browser Type: *
chrome: latest version
-  Browser Version: *
Chrome: latest
-  OS: *
Mac: OSX 10.10.5
-  Stack Traces:
n/a
----

Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Works as expected.

It seems like your version in the demo, is not the `latest`.

```js
/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v0.5.1
 */
```

See http://codepen.io/DevVersion/pen/pbROKb
