### ISSUE TITLE
md-select with required fails if ng-value is an object

### ISSUE THREAD

**Issue by ajones-miovision** [angular/material#8833]
I noticed when we moved from 1.1.0-rc4 to 1.1.0-rc5 our "required" select boxes which are bound to an object no longer function correctly. No matter what selection is made, the form thinks it is invalid.

Codepen: http://codepen.io/anon/pen/dXOBQV

**Angular Versions**: *
-  Angular Version: 1.5.3
-  Angular Material Version: 1.1.0-rc5

**Additional Information**:
-  Browser Type: Chromium
-  Browser Version: 50
-  OS: Ubuntu 16.04

**Comment by DevVersion** [comment]
Fixed within `master` with SHA https://github.com/angular/material/commit/875848817bf9820f510647d2b01a347bb4fd8e46
