### ISSUE TITLE
Editorconfig file

### ISSUE THREAD

**Issue by bradrich** [angular/material#8837]
**Actual behavior**:
-  What is the issue? * There is no .editorconfig file in the root directory that could enforce the necessary contributing guidelines.
-  What is the expected behavior? The .editorconfig file could enforce the necessary contributing guidelines.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : None necessary
-  Details: None necessary.

**Angular Versions**: * Latest
-  Angular Version: Latest
-  Angular Material Version: Latest

**Additional Information**:
-  Browser Type: * Not necessary
-  Browser Version: * Not necessary
-  OS: * Not necessary
-  Stack Traces: Not necessary

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by bradrich** [comment]
@ThomasBurleson We were talking about this earlier. What do you think about this addition?

**Comment by clshortfuse** [comment]
For reference: https://github.com/google/material-design-lite/blob/master/.editorconfig

**Comment by bradrich** [comment]
@clshortfuse This has been deemed as a local addition only and will not be added to the main repository.
