### ISSUE TITLE
How to watch when md-autocomplete value is null and when we click on clear feild icon  

### ISSUE THREAD

**Issue by Rahul-Giri** [angular/material#8839]
-  What is the issue? *

sorry for creating  this issue -

 i'm implementing a search functionality using md-autocomplete . 

i were tried to use $scope.$watch but it's doesn't seems to work if i'm entering ng-model="search" on md-autocomplete.

So  i just wants to know how to watch if md-autocomplete is empty after entering some text and empty it out and when i click on the clear search icon on the md-autocomplete field. 

what point i'm missing ans what i needs to do please guide me.

**Comment by clshortfuse** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial).
