### ISSUE TITLE
md-tooltip getting stuck when used in custom directive.

### ISSUE THREAD

**Issue by Tyre88** [angular/material#884]
Hello,

I am using md-tooltip inside of a custom directive and when i do and then i delete the element, the tooltip gets stuck for some reason. If i just put it inside of a div and then delete the div on click then the tooltip is removed aswell, it seems like this error is only when you use it inside of a custom directive.

Here's a codepen with the example. http://codepen.io/Tyre88/pen/XJXmMx 
Just click on an item to remove it and you will see the error.

**Comment by Splaktar** [comment]
I've seen this in a number of places and not always within custom directives. It also happens to me when the `md-tooltip`s are on `md-button`s in an `md-toolbar` and I am interacting with them.

I've updated this codepen for 0.8.3 and Angular 1.3.14. http://codepen.io/Splaktar/pen/emLbQN

**Comment by verkestk** [comment]
Happening for me too. I'm on md-0.10.1 and ng-1.4.4.

I've seen it while using tooltips inside ```ng-if``` directives. Seems like when the element disappears, the tooltip sometimes sticks around and gets "stuck".

**Comment by Splaktar** [comment]
I thought that this may have been resolved indirectly. So I updated the [CodePen](http://codepen.io/Splaktar/pen/PParMp) to 1.0.0-rc1 and Angular 1.4.7. Unfortunately, the issue remains.

**Comment by sethkoch** [comment]
Still getting this when used in mat-toolbar and on a mat-button.  If you hover over the button the tool tip appears, but then on clicking the button and then clicking out of the drop down menu, the tooltip remains.

**Comment by Splaktar** [comment]
@sethkoch which versions are you using? I updated the [CodePen](https://codepen.io/Splaktar/pen/PParMp?editors=1010#0) to 1.1.10 and AngularJS 1.7.2 and the issue appears to have been resolved.
