### ISSUE TITLE
Docs Site: Navigation menu doesn't open properly when refreshing.

### ISSUE THREAD

**Issue by topherfangio** [angular/material#8841]
**Actual behavior**:
-  What is the issue? *When refreshing the docs page, the navigation menu does not properly toggle the open group; forcing you to click on it twice.
-  What is the expected behavior? It should automatically open the group and scroll the selected item into view.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : https://material.angularjs.org/HEAD/demo/icon
-  Details: Notice how if you just click the link; you cannot access the other demos without clicking on the "Demos" nav item twice (once to close; and then once to re-open).

**Angular Versions**: *
-  Angular Version: N/A
-  Angular Material Version: All

**Additional Information**:
-  Browser Type: *
-  Browser Version: *
-  OS: *
-  Stack Traces:

**Comment by bradrich** [comment]
@topherfangio I managed to fix this in a separate project that I am working on where I used the Material/docs navigation. I will investigate it for you and share my findings.

**Comment by DevVersion** [comment]
@bradrich - @topherfangio Already filed a PR, which fixed that issue.

But it would be probably still good to get your findings. Please share :)

**Comment by bradrich** [comment]
@topherfangio and @DevVersion after studying @topherfangio's fix, that is how I solved it as well. I used a $timeout instead of the nextTick(). Good job.
