### ISSUE TITLE
uib tooltip is not hiding

### ISSUE THREAD

**Issue by raman15071991** [angular/material#8843]
my actual is i had given tooltip to the dropdown button hover but when i click on button its not hiding please help me 

![dropdown](https://cloud.githubusercontent.com/assets/14834633/16329848/bb07b950-3a02-11e6-94fb-1a41db52eaaf.png)

**Comment by crisbeto** [comment]
We can't really help just by looking at a screenshot. Can you provide a Codepen that demonstrates the issue?

**Comment by jayeshanandani** [comment]
Issue mentions uib tooltip. Isn't that a bootstrap ui tooltip?

**Comment by raman15071991** [comment]
yes sorry for that my mistake it is bootstrap ui tool tip
