### ISSUE TITLE
mdPanel doesn't destroy controller

### ISSUE THREAD

**Issue by mennya** [angular/material#8845]
**Actual behavior**:
-  What is the issue? mdPanel doesn't destroy controller
-  What is the expected behavior? mdPanel destroy controller after close

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :  http://codepen.io/anon/pen/ezgzEO?editors=0010 (it's official demo modified https://material.angularjs.org/latest/demo/panel)
-  Details:  Just click several times to "dialog" button (or "select menu") and look to console where will displayed $scope.$id. On every click displayed $scope.$id's will grow

**Angular Versions**: *
-  Angular Version: 1.5.5
-  Angular Material Version: 1.1.0-rc.5

**Additional Information**:
-  Browser Type: Chromium
-  Browser Version: 50.0.2661.102 
-  OS: Ubuntu 16.04 (64-bit)
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
I can confirm it as well, the destroy event doesn't get fired.

**Comment by crisbeto** [comment]
@mennya There's a fix pending at #8848, although you should keep in mind that just calling `close` will keep the instance in case you want to open it again. You'll need to call `destroy` after `close` if you don't intend on re-using the panel.

**Comment by mennya** [comment]
Although we should keep in mind that if `escapeToClose` is true - pressing ESC will only `close` the panel.
