### ISSUE TITLE
md-autocomplete suggestion list is hidden when used in sidebar (https://almsaeedstudio.com/AdminLTE)

### ISSUE THREAD

**Issue by himanshu56** [angular/material#8851]
**Actual behavior**:
when I click in the box suggestion list doesn't show (which was when used anywhere else in the app)

![selection_011](https://cloud.githubusercontent.com/assets/10365144/16349954/4274ed42-3a79-11e6-9585-0dd726344a9e.png)

But if scroll down by using down arrow I am able to select the item.
![selection_010](https://cloud.githubusercontent.com/assets/10365144/16349930/17cc9d7e-3a79-11e6-814c-17fadbea53a8.png)

I think the issue is with CSS. The autocomplete is working but the list is hidden when used in side bar
If anyone can point out which element is causing it or is it because size of fonts or boxes used in CSS.
Thank you.

**Comment by DevVersion** [comment]
Please resubmit this issue with a Codepen. 

---
Also notice, that we only can help at issues (not questions / specific user problems).

Otherwise you should ask in the  [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
