### ISSUE TITLE
mdBottomSheet open animation

### ISSUE THREAD

**Issue by bradrich** [angular/material#8854]
**Actual behavior**:
-  What is the issue? md-bottom-sheet is not showing its opening animation in the doc demos.
-  What is the expected behavior? The component should have an animated opening.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue : See demo on Material docs site:  https://material.angularjs.org/latest/demo/bottomSheet
-  Details: Open the bottom sheet from the demo and notice that the animation is not appearing on the opening.

**Angular Versions**: *
-  Angular Version: Latest
-  Angular Material Version: Latest

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: Latest
-  OS: OS X
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
@bradrich Does your PR for this also fix the issue with the bottom sheet "Open as Grid" sheet not taking up the proper amount of space? Here is an image of what I mean:

<img width="896" alt="screen shot 2016-06-27 at 10 02 12 am" src="https://cloud.githubusercontent.com/assets/54370/16384388/462e7db4-3c4e-11e6-9d31-94458edb5bed.png">

Notice how the buttons pop up against the bottom of the dialog. There should be some padding there, and it also is a bit jumpy.

**Comment by bradrich** [comment]
@topherfangio My PR was only for the open animation. I was going to create a separate issue for the addition of the ng-cloak warning and the "Open as Grid" spacing problem.

I also noticed that to see all of the "Open as Grid" you need to scroll down.

**Comment by topherfangio** [comment]
@bradrich Okay; awesome. If you don't mind creating a separate issue; that would be great. I'm going through all of the demos right now looking for issues and I have a bunch more I will be opening.

**Comment by bradrich** [comment]
The PR for this was merged (https://github.com/angular/material/commit/7f01138e13d6d651d390e1eb6eb85af1f0fada68) but the issue was not closed.

Ping @ThomasBurleson @topherfangio
