### ISSUE TITLE
md-radio-group not rendering as expected in Safari

### ISSUE THREAD

**Issue by bkarv** [angular/material#8859]
**Actual behavior**:
I have a multi row of radio buttons through a ng-repeat. In Safari the radio buttons render overlapping each other. A photo of the behaviour below:
[Safari Behaviour](http://imgur.com/hgXLSjJ)
-  What is the issue? *
Safari does not render the radio buttons properly. Everything is overlapping. 

-  What is the expected behavior?
In Chrome it renders as expected photo below.
[Chrome Behavior](http://imgur.com/TZIADBZ)

**CodePen** or Steps to reproduce the issue: *
`<div class='md-padding' flex>
  
    <div ng-repeat="item in multi.multiChoice" layout="column" layout-align='start start' ng-if="multi.viewFn()">
      <div class='multi-button' flex='70' md-theme="altTheme">
        <md-radio-group class='md-primary' ng-model="multi.content.value" >
            <div flex layout='row' layout-padding layout-align="start center"  ng-style="{'background-color':multi.checkFn('BG',item.value),'color':multi.checkFn('FONT',item.value)}">          
              <md-radio-button flex ng-value="item.value">
                {{item.value}}
              </md-radio-button>
            </div>
            <span </span>
        </md-radio-group>        
      </div>      
    </div>
    <md-button  class="md-raised md-warn" aria-label="Edit" ng-click="multi.content.value=null" ng-if="multi.viewFn()">
          Clear
    </md-button> 
    <label ng-if="!multi.viewFn()">{{multi.content.value}}</label>      
</div>
`
-  CodePen Demo which shows your issue :
-  Details:

**Angular Versions**: *
-  Angular Version: 1.5.7
-  Angular Material Version: 1.0.8

**Additional Information**:
-  Browser Type: *Safari 
-  Browser Version: *9.1
-  OS: *OS X El Capitan
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Working in v1.1.0-rc.5.
