### ISSUE TITLE
md-select and required breaks 2-way binding

### ISSUE THREAD

**Issue by nickbrook72** [angular/material#8865]
**Actual behavior**:
-  What is the issue? 

Trying to use md-select repeating over a list of simple objects breaks if I make the md-select 'required'. It seems that the binding breaks down completely: selecting an option will show correctly in the md-select but isn't passed on to the associated model.

-  What is the expected behavior?

I would expect that adding the 'required' attribute would ensure that the form is invalid until an option is selected. However simply adding 'required' breaks the binding.

**CodePen** or Steps to reproduce the issue: *
-  CodePen Demo which shows your issue :

http://codepen.io/nickbrook72/pen/OXpJGw?editors=1010#

-  Details:

Select an existing user - model is correctly updated.
Flip the 'field required' switch, and select a user. The model isn't updated and the field shows as red.

**Angular Versions**: *
-  Angular Version:
1.5.7
-  Angular Material Version:
1.1.0-rc.5

**Additional Information**:
-  Browser Type: * 
Chrome
-  Browser Version: *
49.0.2623.75 (64-bit)
-  OS: 
Linux Mint 17.2
-  Stack Traces:

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is fixed in `master` with SHA 875848817bf9820f510647d2b01a347bb4fd8e46

---
[Demo with latest changes](http://codepen.io/DevVersion/pen/dXvPPV?editors=1010)
