### ISSUE TITLE
checkbox: Odd bouncing border behavior on deselect.

### ISSUE THREAD

**Issue by topherfangio** [angular/material#8866]
**Actual behavior**:
-  _What is the issue?_ * There is an odd bouncing behavior of the borders of a checkbox when it goes from being checked to being unchecked. It appears that the border change is somehow delayed (possibly until after the ink ripple?).
-  _What is the expected behavior?_ The border width should immediately change when the element becomes deselected.

**CodePen** or Steps to reproduce the issue: *
-  _CodePen Demo which shows your issue:_ Most easily visible in the [Select All demo](https://material.angularjs.org/1.1.0-rc.5/demo/checkbox).
-  _Details:_

![checkboxborderbounce](https://cloud.githubusercontent.com/assets/54370/16385138/3756ae4e-3c51-11e6-9c8f-216c6ba7d005.gif)

**Angular Versions**: *
-  _Angular Version:_ N/A
-  _Angular Material Version:_ 1.1.0-RC5

**Additional Information**:
-  _Browser Type:_ *Chrome, Firefox, Edge (although much faster, so barely visible)
-  _Browser Version:_ *Chrome 51, Firefox 47, Edge 25
-  _OS:_ * Win/OS X
-  _Stack Traces:_

**Comment by clshortfuse** [comment]
This is because because of the `transition` style on md-icon in checkbox-container. The object is transitioning from having a border, to not having a border and it takes 240ms.
