### ISSUE TITLE
Is it possible to support drag event

### ISSUE THREAD

**Issue by Thaina** [angular/material#8879]
There are only swipe in 4 direction possible. I actually want a drag event that user may touch or click and drag on fixed element, not move it but drag on it, for control canvas and so on

It should fire event start / end / dragging and give information on start position, current position, and offset from the element it start on

Is it possible on angular material to implement this?

**Comment by DevVersion** [comment]
Angular Material has its own Gesture Service, which has support for dragging.

```js
$mdGesture.register(myElement, 'drag');

myElement
  .on('$md.dragstart', onDragStart)
  .on('$md.drag', onDrag)
  .on('$md.dragend', onDragEnd);

function onDrag(event) {
  // Retrieves the dragged delta X.
  let pointer = event.pointer.distanceX;
}
```

See some examples, in the `md-switch` or `md-bottom-sheet`

**Comment by Thaina** [comment]
Thanks. But, I don't know why, it cannot work when try to drag up/down before sideway

https://plnkr.co/edit/aoPoaqIddowhix7733J3?p=preview

If I try to start dragging up first it like event is not be called at all

**Comment by Thaina** [comment]
I was figure it out that it related to `horizontal` property that has only true or false. If I set to true it cannot start from vertical drag and if it false it cannot start from horizontal drag

**Comment by Thaina** [comment]
Should this code here

https://github.com/angular/material/blob/bd1cce42ba16b733af0163011f8bb2429782b5da/src/core/services/gesture/gesture.js#L275

changed to be this

```js
if (this.state.options.horizontal) {
            shouldStartDrag = Math.abs(pointer.distanceX) > this.state.options.minDistance;
            shouldCancel = Math.abs(pointer.distanceY) > this.state.options.minDistance * this.state.options.cancelMultiplier;
}
if (!this.state.options.horizontal || this.state.options.vertical)
{
            shouldStartDrag = Math.abs(pointer.distanceY) > this.state.options.minDistance;
            shouldCancel = Math.abs(pointer.distanceX) > this.state.options.minDistance * this.state.options.cancelMultiplier;
}
```

**Comment by Thaina** [comment]
#8934
