### ISSUE TITLE
md-highlight-text should be able to hightlight one of multiple terms

### ISSUE THREAD

**Issue by ptrussart** [angular/material#8881]
Hello,

I'm using ``md-highlight-text`` to show search results and when the user searches for : "*term1 term2*", the system only highlights the phrase "*term1 term2*".

What I would like is a way to highlight "*term1*", "*term2*" and "*term1 term2*". I don't think this is possible right now and it could be very useful if you want to handle full-text search results.

I have tried to replace my searched terms with a pipe :  
``` md-highlight-text="getHighlightedText()"  md-highlight-flags="i"```

```javascript
$scope.getHighlightedText = function(){
	var result = $scope.highlightedText	;
	if (result != null && result.indexOf(" ") != -1)
		result = result.replaceAll(" ", "|");
	return result;
}
```

Unfortunately, the text is sanitized so it doesn't work.

Maybe if the returned value for the ``md-highlight-text`` is an array, we can support this case ?

**Comment by ThomasBurleson** [comment]
Will not fix in ngMaterial v1.x: deprecated.
