### ISSUE TITLE
mdSelect with required and complex ng-value

### ISSUE THREAD

**Issue by lucasmaj** [angular/material#8889]
When using mdSelect with required and mdOption with non-string ngValue, the required validation error is raised. It is expected that required error is NOT raised.

In the codepen below, select any option in the input will be erroneously invalidated.
http://codepen.io/anon/pen/beqaZb

Gist below.
In example below, notice ng-value is a complex object, not string primitive.
```
<md-select ng-model="ctrl.userState" required>
          <md-option ng-repeat="state in ctrl.states" ng-value="state">
            {{state.abbrev}}
          </md-option>
 </md-select>
```

**Comment by DevVersion** [comment]
This is actually filed the fourth time.

This is fixed in `master` with SHA 875848817bf9820f510647d2b01a347bb4fd8e46

**Comment by lucasmaj** [comment]
Thanks, I did search for existing Issue but did not find one.

Thank you!

**Comment by DevVersion** [comment]
@lucasmaj No worries. Thanks's for keeping track!
