### ISSUE TITLE
mdPanel: Can't re-open a closed panel

### ISSUE THREAD

**Issue by chrisguerrero** [angular/material#8894]
**Actual Behavior**:
 -  `What is the issue?` * The following error is thrown when attempting to call the `open()` method on an `MdPanelRef` that has already been created, opened, and then closed:

```
TypeError: Cannot read property 'push' of null
```
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/chrisguerrero/pen/zBZWyx
 -  `Details:` I've modified the panel demo from the docs to call the `$mdPanel.create()` method the first time the panel is shown, then store a reference to the `MdPanelRef`. The second time you try to open the modal, the `show()` method is called on the `MdPanelRef`, which throws the error.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` v1.1.0-rc.5-master-15da974

**Additional Information**:
 -  `Browser Type: *` All
 -  `Browser Version: *` All
 -  `OS: *` All
 -  `Stack Traces:`
```
TypeError: Cannot read property 'push' of null
    at MdPanelRef._configureScrollListener (VM3709 angular-material.js:14477)
    at MdPanelRef._addEventListeners (VM3709 angular-material.js:14368)
    at addListeners (VM3709 angular-material.js:13989)
    at processQueue (VM3702 angular.js:15961)
    at VM3702 angular.js:15977
    at Scope.$eval (VM3702 angular.js:17229)
    at Scope.$digest (VM3702 angular.js:17045)
    at Scope.$apply (VM3702 angular.js:17337)
    at HTMLButtonElement.<anonymous> (VM3702 angular.js:25023)
    at defaultHandlerWrapper (VM3702 angular.js:3456)
```

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
@chrisguerrero Thanks for the awesome issue and related PR.
