### ISSUE TITLE
form.$invalid is true for correct value in md-select

### ISSUE THREAD

**Issue by xersiee** [angular/material#8900]
I have a form that is used for modification of existing entity, so form model is initialized at page setup in controller. Then I use `form.$invalid` flag to enable/disable save button. My form contains some `md-select` components (single choice version) with `ng-required="true"`. The problem is that `$invalid` flag for these components is `true`, even if values are set.

I've also noticed that if I do ugly workaround and wrap setting form model in '$timeout' call it works again. [Codepen that presents this behavior](http://codepen.io/anon/pen/yJMGOm).

I'm using angular-material 1.1.0-rc5 and angular 1.5.5.

It works fine with previous version (rc4). After short investigation I've noticed that this is the [commit](https://github.com/angular/material/commit/da02ea2eb500dc297f4028b9cdedd4e86bffd69b) that introduces this bug - select options are not yet available but code tries to use them to check if value is correct.

**Comment by DevVersion** [comment]
This is fixed within `master`.
