### ISSUE TITLE
in "latest" docs, md-datepicker is not listed under directives

### ISSUE THREAD

**Issue by lnathanson** [angular/material#8902]
**Actual Behavior**:
 -  `What is the issue?` * If I look at the Docs site under "/latest" or "/1.1.0-rc.5", md-datepicker is not listed under Directives in the side-nav. It does appear under "/1.1.0-rc4" and "/1.0.9". 
 -  `What is the expected behavior?` If md-datepicker is still a valid directive, that it is listed under Directives for the latest release. If not, the Datepicker demo should be removed.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` (clearly not codepens) https://material.angularjs.org/latest/
and https://material.angularjs.org/1.1.0-rc.5/
 -  `Details:` Compare with https://material.angularjs.org/1.1.0-rc4/

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` Any
 -  `Browser Version: *` Any
 -  `OS: *` Any
 -  `Stack Traces:`

Dunno if this helps at all, but if I try to force the URL to "/latest/api/directive/mdDatepicker", I get redirected to "/".

**Comment by crisbeto** [comment]
[This has been fixed in HEAD.](https://material.angularjs.org/HEAD/)
