### ISSUE TITLE
mdPanel: Always traps focus. Setting trapFocus to false doesn't work

### ISSUE THREAD

**Issue by vaughnmuirhead** [angular/material#8908]
**Actual Behavior**:
 -  `What is the issue?` Focus is is always trapped when the panel appears and there is no way to allow the user to interact with the rest of the application while the panel is displayed.
 -  `What is the expected behavior?` Would expect setting trapFocus to false would allow the user to interact with the rest of the application while the panel is open.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/bZWNBQ
 -  `Details:` Have modified the demo codepen to demonstrate this issue. The trapFocus parameter is set to false but focus is still trapped. Just click the dialog button and attempt to interact with the checkbox in the background.  

**Angular Versions**: *
 -  `Angular Version:` AngularJS v1.5.7
 -  `Angular Material Version:` Angular Material Version: v1.1.0-rc.5-master-8758488

**Additional Information**:
 -  `Browser Type: *` Chrome, IE
 -  `Browser Version: *` chrome latest, IE11
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by vaughnmuirhead** [comment]
@zlovin Thanks for the workaround! This fixes my issue perfectly.

**Comment by ErinCoughlan** [comment]
@vaughnmuirhead `trapFocus` is intended to trap the focus within the panel. For instance, if you have a dialog, for accessibility reasons focus cannot leave the dialog until the user dismisses it. So if you continuously hit tab and `trapFocus` is true, focus cannot leave the panel. If `trapFocus` is false, focus is directed to the next element in the tab order even if it is outside the panel.

I think the issue you are really asking for is allowing clicks to go through the backdrops. I just filed Issue #8968 for this new option.
