### ISSUE TITLE
IE-11 and IE-edge shows the black background in md-select , and sometimes show the full black screen.

### ISSUE THREAD

**Issue by dinesh36** [angular/material#8909]
**Actual Behavior**:
-  `What is the issue?`   When the body content is vertically scrolling then angular meterial show the black border around the select box as shown in this [image.](http://i.stack.imgur.com/rZ0o1.png)
-  `What is the expected behavior?` The black screen should not be shown.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/BzRjBx
-  `Details:` Issue occurs when screen scrolls vertically

**Angular Versions**: *
-  `Angular Version:` 1.4
-  `Angular Material Version:` 1.0.9 and 1.1.0

**Additional Information**:
-  `Browser Type: *` IE
-  `Browser Version: *` 11 , EDGE
-  `OS: *` Windows 10
-  `Stack Traces:` No stack traces

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by binzma** [comment]
+1

This issue is still present in 1.1.1 and causing problems in our project, too.

**Comment by clshortfuse** [comment]
I can't seem to replicate this issue with the included Codepen over IE 11, Edge13 or Edge 14. I would assume the issue is related to the box-shadow here: https://github.com/angular/material/blob/release/1.1.1/src/components/select/select.scss#L234

@dinesh36 I'm also unclear about 

> Issue occurs when screen scrolls vertically

Considering that triggering's md-select popup shouldn't allow you to scroll the screen.

Do you also have issues with md-whiteframe? Can you reproduce the error on the demo site? https://material.angularjs.org/latest/demo/select

**Comment by clshortfuse** [comment]
Closing due to lack of response.

**Comment by vpanugaling** [comment]
Hi @clshortfuse 

I can replicate this issue with the included Codepen over IE 11. It seems the black background is rendering at random when you open the dropdown. Please see this  screen capture: http://i.imgur.com/M9sYoYu.gifv

Also, were experiencing this on our project.

**Comment by ALodha** [comment]
@vpanugaling 

Did you happen to find a solution to this?

**Comment by ALodha** [comment]
@clshortfuse 

Since we can reproduce this issue, can you reopen it? As it is imperative for us to get a solution for this

**Comment by vpanugaling** [comment]
@ALodha The issue is not from Angular Material,  but a graphical bug with your machine/drivers and Microsoft Edge. You can disable hardware acceleration in Edge and see if the problem persists

**Comment by clshortfuse** [comment]
@vpanugaling Thanks, that is correct.

Related: https://github.com/angular/material/issues/10161

**Comment by ALodha** [comment]
@vpanugaling I tried disabling the hardware acceleration in IE and Edge. I can still see the issue. Can you please help us with this, as it is important for the project

**Comment by vpanugaling** [comment]
@ALodha please try testing it to another machine. Thanks
