### ISSUE TITLE
Error: [$injector:nomod] Module 'angularytics' is not available!

### ISSUE THREAD

**Issue by reutopiaer** [angular/material#891]
Uncaught Error: [$injector:modulerr] Failed to instantiate module docsApp due to:
Error: [$injector:modulerr] Failed to instantiate module angularytics due to:
Error: [$injector:nomod] Module 'angularytics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

https://github.com/luisfarzati/angulartics/issues/57

**Comment by tkisme** [comment]
agree
