### ISSUE TITLE
Build: Support Node 6

### ISSUE THREAD

**Issue by DevVersion** [angular/material#8912]
NodeJS will put Node.js v6 in LTS.

![image](https://cloud.githubusercontent.com/assets/4987015/16495027/f12eafc8-3eeb-11e6-96a8-c26444686d7c.png)

Node v6 is scheduled for LTS at `2016-10-01`.

---
Currently developers are not able to build the Angular Material sources with Node v6.
We should fix that and make sure that everything will work for Node v6.

Probably Node v5 will be no longer supported for building the Angular Material sources.

**Comment by clshortfuse** [comment]
Upgrading `gulp-if` to `2.0.1` fixes it for me on ChromeOS/Linux.

**Comment by DevVersion** [comment]
Note: Referencing #8850 to update the dependencies.
