### ISSUE TITLE
Show only one week at the time using the datepicker

### ISSUE THREAD

**Issue by ckip** [angular/material#8918]
How can I show only one week at the time using the datepicker and allow the user to still be able to reveal the rest of the days of the month by sliding down the calendar ?

The images below show an idea of what I am aiming for.

<img width="373" alt="screen shot 2016-06-30 at 12 25 09" src="https://cloud.githubusercontent.com/assets/1453745/16498883/ddaff3be-3ecb-11e6-9add-f8a3ec3a8d0c.png">

<br><br>

<img width="372" alt="screen shot 2016-06-30 at 12 24 37" src="https://cloud.githubusercontent.com/assets/1453745/16498886/e0224016-3ecb-11e6-90b6-c212ee87ad46.png">

**Comment by crisbeto** [comment]
It's not possible, and I'm not sure it makes sense to have in Material.

**Comment by henri92** [comment]
where is the complete code in this example in top?
