### ISSUE TITLE
md-select required attribute is not working in version 1.1.0-rc5

### ISSUE THREAD

**Issue by taxpayer** [angular/material#8922]
**Actual Behavior**:
 -  `What is the expected behavior?` It was working correctly in version 1.1.0-rc4. When there is a **required** attribute in version rc5, the model isn't updated, it keeps the value _undefined_.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [http://codepen.io/wildTiger/pen/EymXjO](http://codepen.io/wildTiger/pen/EymXjO)
 -  `Details:` Also tried  _**required="true"**_ and _**ng-required="true"**_ without success.

**Angular Versions**: *
 -  `Angular Version:` 1.3.6 (CodePen) and 1.5.0 (my particular project)
 -  `Angular Material Version:` 1.1.0-rc5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 51.0
 -  `OS: *` Windows

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
@taxpayer Thanks for the issue. We've fixed that in `master` with SHA 875848817bf9820f510647d2b01a347bb4fd8e46.

- [Updated demo](http://codepen.io/DevVersion/pen/RRVjga)
