### ISSUE TITLE
md-autocomplete with md-min-length 0 and ng-required on another field cause a click fail on the first time

### ISSUE THREAD

**Issue by coteke** [angular/material#8923]
**Actual Behavior**:
 -  `What is the issue?` I have a md-input with an autocomplete that is required when another input is not empty. The md-autocomplete open the list of all items if the field is empty and the focus is on the autocomplete. If there is a value on page load and you erase the content of the autocomplete then the full list appear. If you select an item of the list with the mouse, the field become required and the item is not selected. You need to click a second time on the item you want.
 -  `What is the expected behavior? You should not have to click a second time to select the item.`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo : `(http://codepen.io/kcote/pen/yJMdpR)
 -  `Details: Erase the autocomplete field then select any states with the mouse.`

**Angular Versions**: *
 -  `Angular Version: 1.5.6`
 -  `Angular Material Version:1.0.9`

**Additional Information**:
 -  `Browser Type: Google chrome `
 -  `Browser Version: 51.0.2704.103 (64-bit)`
 -  `OS: Windows 10`
 -  `Stack Traces:`

**Comment by clshortfuse** [comment]
I can't reproduce this from my phone, so I'll have to try on my desktop/laptop later today. When you say clear the text, are you clearing with backspace or ‘escape‘.  Are you getting different results with each of them?

**Comment by coteke** [comment]
Clearing with the escape seems to work everytime.

Clearing with backspace after selecting the whole value seems to work some times.

Clearing with backspace one letter at a time reproduce the error everytime on the first time after a page load.

I also get the error randomly (From backspacing) and then selecting another value.

**Comment by clshortfuse** [comment]
I can't reproduce this anymore in master. This might be due to the new validation changes since this issue was submitted.
