### ISSUE TITLE
Sidenav: Dragging Functionality 

### ISSUE THREAD

**Issue by rayita** [angular/material#8928]
We should be able to close the sidenav by dragging the sidenav.

**Comment by DevVersion** [comment]
I've updated the issue. I was working on that functionality in #6174 and #7857 

I decided to resubmit that PR, once #7857 landed, so it's good that you pinged me on that.

This is a planned work and I'll work on that as soon as possible.

**Comment by ThomasBurleson** [comment]
Will not fix in ngMaterial v1.x
