### ISSUE TITLE
`md-content` should expand on toolbar `md-scroll-shrink`

### ISSUE THREAD

**Issue by MathiasLM** [angular/material#893]
Because `md-scroll-shrink` moves `md-content` up, it makes it unsuitable for use on a static viewport page, such as typical apps. I've looked at the code, and here's my suggested fix:

### toolbar.js

```javascript
[...]

      function setupScrollShrink() {
        [...]
        var contentHeight;
        [...]

        function onMdContentLoad($event, newContentEl) {
            [...]
            contentHeight = contentElement.prop('offsetHeight');
            [...]

        function onContentScroll(e) {
            [...]
            contentElement.css(
              'height',
              (contentHeight + (-(toolbarHeight - y) * shrinkSpeedFactor)) + 'px'
            );
            [...]
```

This fix makes `md-content` seems as though it has a static height, and thus prevents the bottom from bouncing up and down.

**Comment by matthiasg** [comment]
i actually looked into this too for our own application. there are a number of issues with all solutions available so far. 

I think a correct solution will only be achievable once `position:sticky` is supported by all browsers. On mobile devices you always have a lag between scroll event and javascript (to allow for smooth touch based scrolling). Note: Support for click through of transparent parts of divs without loosing  clickability and scrollability would work too.

Even the solution as currently implemented does not actually work. When you make the md-toolbar in the example page big enough (e.g. 200px) and then remove items until all items would fit into the main area the scrollbar will vanish and you wont be able to reach the last few items anymore.

In our case we built two different solutions for mobile and desktop (difference being one has visible scrollbars the other has not) in the desktop case we reposition on the scroll event which is perfectly stable and looks great and in the mobile case we reposition the header in its own layer on top of the scrollable area (with content pushed down of course).
