### ISSUE TITLE
Please separate drag and swipe event

### ISSUE THREAD

**Issue by Thaina** [angular/material#8933]
I want to use mdgesture to register drag event on some element (canvas)

But it has logic of swipe, only start when the pointer move over some threshold in only one direction. If I select horizontal it cannot start drag event in vertical dragging

Which limit its used case only on carousel. It cannot use to normal movement in arbitrary direction (move a map for example)

Please has an option to let us can use a very basic drag event, no threshold and lock direction

**Comment by DevVersion** [comment]
Related Pull Request: #8934

**Comment by Thaina** [comment]
@DevVersion I have made that pull request such a hack and make things a little complicate. It just fastest way to do so

But I would like if you consider to make a new mdDrag with very basic drag event with no direction or threshold, then have mdSwipe extend it instead

**Comment by ThomasBurleson** [comment]
Will not fix in ngMaterial v1.x: deprecated.

**Comment by Thaina** [comment]
@ThomasBurleson I understand but will it be fixed in ngMaterial 2 ?

**Comment by DevVersion** [comment]
@Thaina In Material 2 there will be no standalone gestures support. Material 2 provides a HammerJS gesture configuration, which allows you to use extremely much gesture events. 

> http://hammerjs.github.io/
