### ISSUE TITLE
Angular material toolbar height issue

### ISSUE THREAD

**Issue by tarasrng** [angular/material#8935]
**Actual Behavior**:
 -  When browser width is less than 960p, toolbar change it's height to 48p. It looks logical, although I want my toolbar to be the same height all the time.
But what is really confusing for me - when browser width is less than 500p - toolbar become bigger than just before (56p)!

 - Expected behaviour (in my opinion) - Toolbar height is alwayse the same, or changes only once

**CodePen**: 
 -  http://codepen.io/tarasrng/pen/ZOyYoY
 -  make sure that content area height is greater than 274p, ant try to make browser width smaller.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.0-RC.5

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *`51.0.2704.106 m (64-bit)
 -  `OS: *`Windows 10

**Comment by DevVersion** [comment]
When smaller than breakpoint `-sm` (960px) and orientation is `portrait`
- Height: `56px`;

When smaller than breakpoint `-sm` (960px) and orientation is `landspace`
- Height: `48px`

![image](https://cloud.githubusercontent.com/assets/4987015/16558251/9e3a3728-41e4-11e6-874b-ccc115cd0723.png)
It seems like everything is working as expected and declared by the [Design specifications](https://material.google.com/layout/structure.html#structure-app-bar)
