### ISSUE TITLE
Can this be used without overriding existing styling?

### ISSUE THREAD

**Issue by aliakhtar** [angular/material#8937]
I'd like to use a few directives from angular material, but I only want to use those directives where I use them, and I want the rest of my existing styles to stay the way they are.

But, when I add angular-material.min.css as a stylesheet, it causes my navigation bar to have a white background.

Is it possible to use this without having it mess with existing styles?

Based on googling, I've tried:

```
app.config(function($mdThemingProvider) {
    $mdThemingProvider.setDefaultTheme('none');
})
```

But it hasn't had any effect.

Sorry if I'm asking in the wrong place.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
