### ISSUE TITLE
Question: Is there anyways I can use angular material with older android versions?

### ISSUE THREAD

**Issue by gaurav-chandra** [angular/material#8944]
I have a cordova app which used crosswalk for older android sdk compatibility. But the client has asked me to remove crosswalk as apk size was an issue. Now Android < 4.4 are not rendering correctly as flex box is used in layout.

Is there a polyfill which I can use for rendering problem on older android versions?

**Comment by PDSBGreg** [comment]
Not that I'm aware of. It's Crosswalk or no flex-box for older Android version.

**Comment by mckenzielong** [comment]
Might be worth checking out crosswalk lite: https://crosswalk-project.org/documentation/crosswalk_lite.html

**Comment by gaurav-chandra** [comment]
@mckenzielong I tried installing cordova crosswalk plugin with lite flag but still the release apk size is similar to the full crosswalk one.

**Comment by EladBezalel** [comment]
@gaurav-chandra our official support is n-1 in browsers, assuming old android can install the n-1 version of ie, chrome, firefox etc. it should work
