### ISSUE TITLE
[Request] md-selected-item-change call on selection clear

### ISSUE THREAD

**Issue by apiovesantechgest** [angular/material#8945]
**Actual Behavior**:
 -  `What is the issue?` * Cannot clear foreign key id when user clear the selection
 -  `What is the expected behavior?` md-selected-item-change can be called also when user press the "X"?

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.3
 -  `Angular Material Version:` 1.1.0-rc4

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Invalid without a CodePen demo.
