### ISSUE TITLE
Disabled fieldset won't apply disabled styles to child elements

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#895]
If using a disabled fieldset, styles won't be applied in its child elements.

Current results:
![](http://i.imgur.com/csMpzgb.png)

Note that the button is raised.
I expected the button to look like [the disabled one from the Angular Material demo](https://material.angularjs.org/#/demo/material.components.button).

I think inputs don't need any special styles when they're disabled, except for `cursor: default` (which already is applied).

I'm using Angular Material v0.6.1.

**Comment by marcysutton** [comment]
Hi @gustavohenke, can you verify whether this is still an issue?

**Comment by gustavohenke** [comment]
It works :+1: 
Thanks!

**Comment by gustavohenke** [comment]
I should note that neither buttons or text fields are inheriting the styles anymore...
Demo: http://plnkr.co/edit/brYs1III2uzzsQ84yfJ6?p=preview

**Comment by marcysutton** [comment]
@gustavohenke they look fine to me in 0.7.1. Closing.

**Comment by antoinebrault** [comment]
input-theme.scss is missing "[disabled] &"

https://github.com/angular/material/blob/7789d6a4d07b6c80bbfa34bc5d35b035b7757d4b/src/components/input/input-theme.scss#L78
