### ISSUE TITLE
md-checkbox margin-right is not right using md-primary 

### ISSUE THREAD

**Issue by ManoloAlvarezForo** [angular/material#8954]
**Actual Behavior**:
 -  `The margin right for the CheckBox using the md-primary in the md-list-item so has margin-right = 29px and width = 24px   the checkbox using the md-secondary into the md-list-item uses a container with width = 24px and margin-right = 0` *
 -  `I think that the checkbox needs a container like the md-secondary-container maybe a _md-primary-container to follow the material design to the margin in the list items with 16px`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details: I used this code:
 <md-list-item ng-repeat="topping in toppings">
    <p> {{ topping.name }} </p>
    <md-checkbox class="md-secondary" ng-model="topping.wanted"></md-checkbox>
  </md-list-item>`

**Angular Versions**: *
 -  `Angular Version: 1.5.5`
 -  `Angular Material Version: v1.1.0-rc.5`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
Can you include a demo to help diagnose this issue better?

**Comment by ManoloAlvarezForo** [comment]
http://codepen.io/anon/pen/xOPbxy here is the demo you can reproduce the observation changing the class in the checkbox to md-primary

**Comment by clshortfuse** [comment]
There actually isn't an issue. I know the wording is confusing, but `md-secondary` denotes a secondary item for an `md-list-item`. `md-primary` relates to the color for `md-theme`.

You should write ```class="md-primary md-secondary"```

**Comment by ManoloAlvarezForo** [comment]
Ok name is the problem has the same name to manage the theme color and the item number jeje thanks
