### ISSUE TITLE
md-datepicker background transparent when using custom theme

### ISSUE THREAD

**Issue by oostmeijer** [angular/material#8957]
**Actual Behavior**:
 -  `What is the issue?`
When using a custom theme the date picker background turns transparent.
 -  `What is the expected behaviour?`
That the date picker has a solid background found in the background palette of the theme?

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` 
[demo on codepen](http://codepen.io/oostmeijer/pen/pbwrzK)
 -  `Details:` 
When using a custom theme the date picker background turns transparent.

**Angular Versions**: *
 -  `Angular Version:`
1.5.7
 -  `Angular Material Version:`
1.1.rc5

**Additional Information**:
 -  `Browser Type: *`
Safari, Chrome
 -  `Browser Version: *`
safari Versie 9.1.1 (11601.6.17), chrome Versie 51.0.2704.103 (64-bit)
 -  `OS: *`
OSX El Capitan
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
This has been fixed with https://github.com/angular/material/pull/8718. Until it gets released, you can add this to your code to get it working:

```js
angular.module('yourAppGoesHere').directive('mdDatepicker', ['$mdTheming', function($mdTheming){
  return {
    link: function(scope, element){
      var calendarPane = angular.element(element[0].querySelector('.md-datepicker-calendar-pane'));
      $mdTheming(calendarPane);
    }
  }
}]);
```
