### ISSUE TITLE
Mandatory '*' for md-select label by default

### ISSUE THREAD

**Issue by prabhum07** [angular/material#8958]
**Actual Behavior**:
 -  `Mandatory * is not displayed at the initial stage in md-select it displays when some content is selected` *

**Expected Behavior**:
 -  `It should show the * initial itself as like input boxes`

**Angular Versions**: *
 -  `Angular Version: 1.5.7`
 -  `Angular Material Version: 1.1.0-rc.5`

**Comment by DevVersion** [comment]
This is fixed within `master` http://codepen.io/DevVersion/pen/vKJEyy
