### ISSUE TITLE
Toolbar menu items doesn't close on click

### ISSUE THREAD

**Issue by Edorka** [angular/material#8965]
When a `<md-menu-content>` inside a `<md-menu>` on a `<md-toolbar>` is opened. It can't be closed by clicking on the md-toolbar.

This seems because some component has added to the toolbar styles the rule z-index:100 which produces this element to be over the md-scroll-mask which has a z-index of 50, resulting on this mask can never be clicked on the part of the layout where the md-toolbar stands.

**Angular Versions**: *
 -  `Angular Version: 1.5` 
 -  `Angular Material Version: 1.1.0-rc4`

**Additional Information**:
 -  `Browser Type: Chrome, Safary`
 -  `Browser Version: 51.0.2704.106`
 -  `OS: Linux and MacOS`

**Comment by crisbeto** [comment]
@Edorka can you post a codepen that demonstrates the issue?

**Comment by Edorka** [comment]
[](http://codepen.io/Edorka/pen/jAvVxP)

Found the cause of the error, months ago we had to replace md-button elements in favour of an anchor of `class="md-button"` because of some menu triggers which where not displayed.

Seems that in this case the method `MenuBarController.prototype.init ` is triggered and wrongly updates de style of <toolbar>

I leave at your judgement if this needs fixing
