### ISSUE TITLE
Column layout gets congested in iphone ios 9.3

### ISSUE THREAD

**Issue by bkhoshroo** [angular/material#8966]
**Actual Behavior**:
 -  `What is the issue?` checkbox and radio button are congested together in iphone safari. 
 -  `What is the expected behavior?` in column layout they should stack on top of each other.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue: 1. http://codepen.io/anon/pen/LkjzkL 2. https://material.angularjs.org/latest/demo/checkbox
 -  `Details:` first example of the checkbox demo shows this issue. This issue can be viewed either on iPhone or safari browser under responsive mode selecting iphone.  

**Angular Versions**: * all versions
 -  `Angular Version:` all versions
 -  `Angular Material Version:` all angular material versions

**Additional Information**:
 -  `Browser Type: *` IOS Safari
 -  `Browser Version: *` 9.1
 -  `OS: *` ios 9.3
 -  `Stack Traces:`

iPhone view(broken):
![screenshot from 2016-07-07 11 16 00](https://cloud.githubusercontent.com/assets/6200970/16658414/4d253278-4434-11e6-8e13-ede26589d848.png)

chrome view(correct):
![screenshot from 2016-07-07 11 18 51](https://cloud.githubusercontent.com/assets/6200970/16658510/a5f3d544-4434-11e6-9fc8-aed4c56f6436.png)

**Comment by ThomasBurleson** [comment]
See version using HEAD: http://codepen.io/ThomasBurleson/pen/XKqxBY?editors=1010#0

**Comment by clshortfuse** [comment]
The PR doesn't exactly fix the inherit issue, it just fixes the demo. The problem is due to a Safari bug with `flex-shrink`. This can be fixed by changing

`flex: 1 1 {percentage}` 

to 

`flex: 1 0 {percentage}`

though I haven't fully analyzed the repercussions.

**Comment by topherfangio** [comment]
@clshortfuse Indeed; however, I think that would probably break other things and I know that major work is being done on the layouts, so we wanted a quick-fix for the docs site.

**Comment by NomNomCameron** [comment]
Having similar problems in safari, anyone have a workaround for the safari bugs with flexbox?

**Comment by topherfangio** [comment]
@NomNomCameron Can you post a Codepen which shows your issue? I might be able to find a workaround.

Also, unless you're needing to fill available space with flex, a flex column layout is basically a block layout. So you may be able to work around it by using flex only for the desktop display (like if you want to separate components into rows).
