### ISSUE TITLE
mdPanel: Implement "propagateContainerClicks" config option.

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#8968]
This option should allow users to interact with other elements on the page when the panel is opened.

If `clickOutsideToClose` is also present, the panel should close itself and then click on the underlying element.

If `hasBackdrop` is true, this option should be ignored as the backdrop will visually indicate that clicks will stop at that barrier.

This is currently not possible because the panel container covers the entire screen and captures any click events.

This feature is needed for tooltips and menus.

**Comment by bradrich** [comment]
@ErinCoughlan We are working on this right now and the solution that seems the best is to either:

- Add a `wrapperClass` option to the mdPanel config and initialize it through the `addStyles` function
- OR heavily document the `transformTemplate` option because it is possible to add a class to the `outer-wrapper` from there as well.

Once the class has been added, then just set `pointer-events: none;` on the class.

I think that we should leave the exclusion of these options up to the developer and not tie them to the `clickOutsideToClose` or `hasBackdrop` options. What do you think?

Ping @EladBezalel.

**Comment by ErinCoughlan** [comment]
@bradrich Oh, I couldn't find an issue for this, but it was on my list of features to add for the panel.

A few (disjoint) thoughts:

I wasn't sure that `pointer-events` worked cross-browser, but I see now that I am wrong here. ([caniuse](http://caniuse.com/#search=pointer-events)) I had thought the solution was going to be capture, possibly close the dialog if `clickOutsideToClose`, then re-fire the event with the right target.

From an API point of view, I think of this as a boolean option where we just "do the right thing". I'm less particular about how we get that functionality. It's a common use case, so the less work the user needs to do to get it right, then better we are going to be and the fewer bug reports we'll see from misunderstanding.

`transformTemplate` is not currently exposed to the user because the panel needs to do specific wrapping there. I don't know if we want to allow them to mess with it (unless I misunderstand the document part).

For `hasBackdrop`, it would be a horrible user experience to allow clicks to propagate past the opaque background. Users are used to clicking on backdrops and closing panels. It would be unexpected, I think, to close the panel and do something else as well. On the other side, I understand that keeping them separate gives the developer more freedom, so if everyone else wouldn't feel sad inside about encountering this experience, I could change my mind. @ThomasBurleson What do you think about this?

The reason I mentioned `clickOutsideToClose` is because it stops propagation of clicks, so it was more of a gotcha. They don't need to interact with each other, but there should be a test that it works correct when both options are true.

Also, thanks. :smile:

**Comment by bradrich** [comment]
@ErinCoughlan I think that you are right about the less the dev needs to do the better. With that being said, it is probably best to go with the added option of `wrapperClass`.

What I was meaning by not tying the option of event pass through to the `clickOutsideToClose` and `hasBackdrop` options is that if they are adding a class to the wrapper that allows for the `pointer-events: none;` style, then they should not use those two options. Maybe we add an error message if they venture that way.

**Comment by scriptsure** [comment]
+1

**Comment by ErinCoughlan** [comment]
@bradrich Actually, `clickOutsideToClose` does make sense with `propagateContainerClicks`. Look at the product switcher in gmail. It doesn't have a backdrop, so it looks like I can click elsewhere on the page. When I do, the product switcher closes and my click is not lost. (It can open another popup or focus on search or open an email.)

**Comment by scriptsure** [comment]
@ErinCoughlan one other thing... when you have the clickOutsideToClose: true and you have disableParentScroll: true.... clicking outside no longer works.... here is an example:

http://codepen.io/scriptsure/pen/YWXNNX?editors=0010

if i set disableParentScroll: false and clickOutsideToClose: true everything works great except if i set a max-height AND fullscreen:true the scrolling in the mdPanel causes the panel to shift positions on the page...

**Comment by bradrich** [comment]
@scriptsure There is a pending PR for this issue: #8901.
