### ISSUE TITLE
Docs demo sections have rounded corner, but do not hide overflow

### ISSUE THREAD

**Issue by pandaiolo** [angular/material#897]
Docs sections elements have border radius defined in the CSS, but no overflow hiding, which results in non-curved borders inner elements overflow outside the section, looking as if the section had straight corners.

But this border radius is visible wherever there is padding or transparent elements inside.

Fix : adding `overflow: hidden;` in `.demo-container` in the docs CSS should be sufficient (I am sorry I do not have the time to submit a PR)

**Comment by rschmukler** [comment]
This is fixed in f32a5958e3797aaa7b312470ce0473adc72562b9
