### ISSUE TITLE
md-select ng-change $mdDialog.hide() does not work

### ISSUE THREAD

**Issue by eassa** [angular/material#8972]
when ng-change fires a function i $mdDialog.hide(); stops working and does not close anymore even if i went later on to cancel

**Comment by florindaneliuc-cs** [comment]
Can you please provide additional info (repro, http://plnkr.co/, etc.)
Looks like I'm troubleshooting the same issue.

**Comment by DevVersion** [comment]
Please provide a CodePen demo.

---

To expedite resolution, please always test with the latest versions:
*  **Angular Material HEAD**
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS Latest Release versions:
  *  **Angular 1.3.19** (or greater)
  *  **Angular 1.4.8** (or greater).
