### ISSUE TITLE
mdPanel: Support RTL and LTR positioning.

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#8974]
**Actual Behavior**:
 -  `What is the issue?` *

Developers specify the location in a ltr manner, so when the screen is reversed, panels appear offscreen or in unexpected locations.

 -  `What is the expected behavior?`

Based on the whether the user's orientation, set right or left accordingly when positioning. Currently the panel always sets `left`. [Code](https://github.com/angular/material/blob/master/src/components/panel/panel.js#L1953)

Absolute positioning should be updated as well so that apps work the way developer intended across locales without any additional configuration or thought.

**Comment by ErinCoughlan** [comment]
Add a config option to the panel for `isRTL`.

**Comment by EladBezalel** [comment]
Maybe we should also check for `dir="rtl"` on `<body>` or `<html>`?

**Comment by ErinCoughlan** [comment]
@EladBezalel That was my initial idea, but I can also imagine a configuration being useful. I slightly prefer the dir="rtl" option, but I will go with whatever you think is right.

**Comment by EladBezalel** [comment]
@ErinCoughlan across all of our components our `rtl` implementation relays on `dir="rt"` so i'd say it would be weird to go with a configuration.

**Comment by ErinCoughlan** [comment]
@EladBezalel SGTM! Ship it!

**Comment by EladBezalel** [comment]
@ErinCoughlan best solution for me is checking if we're on rtl mode and switch the `start` with `end` and vice versa,

for example:
if we have a panel with `ALIGN_START` position, before calculating the position i'll check for RTL and in that case i will change the position to `ALIGN_END`

Making the panel change the calculation to `right` (css attr) will my cause some problems when users relay on the `left` to be set
