### ISSUE TITLE
Required md-select validation error

### ISSUE THREAD

**Issue by douglasbgatti** [angular/material#8978]
**Actual Behavior**:
 -  `What is the issue?` *When submitting a form some of the required md-select that have values selected are not validating. This behavior does not happen every time but it is very frequent.
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.4.8
 -  `Angular Material Version:` 1.1.0.rc5

**Additional Information**:
 -  `Browser Type: *` Chrome  
 -  `Browser Version: *` 51.0.2704.103 m
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Please provide a demo and re-confirm within `master`. 

There was a Commit 875848817bf9820f510647d2b01a347bb4fd8e46, which fixed some issues with the validation.

**Comment by DevVersion** [comment]
Once you provided a demo, we'll reopen.
