### ISSUE TITLE
fix(mdPanel): Dynamic update of panel position and CSS class manipulation

### ISSUE THREAD

**Issue by bradrich** [angular/material#8980]
**Actual Behavior**:
 -  `What is the issue? *` **This is actually a two-part issue**
  - **Part 1:** There is no current way to update the position of the mdPanel that is originally established in the configuration, without closing the mdPanel, changing the position and re-opening the mdPanel.
  - **Part 2:** The `addClass`, `removeClass`, and `toggleClass` functions of the `MdPanelRef` only target the mdPanel container, the 'outer-wrapper', even though a developer might want to target the mdPanel element instead.

 -  `What is the expected behavior?`
  - **Part 1:** There should be a public function of the mdPanel API that allows you to update the position object in the current panel's configuration and then it should update the position of the mdPanel.
  - **Part 2:** There should be an option on the `addClass`, `removeClass`, and `toggleClass` functions that allow you target the mdPanel element instead of the container.
  - **Part 2 (EDIT):** **An example of why a developer would want to use** the `addClass`, `removeClass`, and `toggleClass` modifications to specifically target the panel element:
    - Targeting the panel element is useful if you want to add CSS classes to the panel element for custom transitions or behavior. For instance, the transition between showing and hiding the panel with an animation that is not supported by the mdPanelAnimation API.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` N/A
 -  `Details:` N/A

**Angular Versions**: *
 -  `Angular Version:` Latest
 -  `Angular Material Version:` Latest

**Additional Information**:
 -  `Browser Type: *` All
 -  `Browser Version: *` All
 -  `OS: *` All
 -  `Stack Traces:` N/A

**Comment by topherfangio** [comment]
@bradrich Can you edit the issue description in `What is the issue?*` **Part 2** to briefly describe an instance where the developer might want to target the panel instead of the wrapper?

Just trying to *wrap* (he he) my head around the issue.

**Comment by bradrich** [comment]
@topherfangio That request is absolutely punderful!
