### ISSUE TITLE
Datepicker : impossible to select a date in month view

### ISSUE THREAD

**Issue by fbruffaert** [angular/material#8982]
**Actual Behavior**:
 -  `What is the issue?` 

I have created a datepicker with : 
- mdMinDate attribute set to "2000-01-01"
- mdMaxDate attribute set to 2020-12-31".

If I scroll up and down in the default view, I can select any date within this range of dates => **OK**.

However, if I switch to month view, I can't scroll up. I am stuck at 2019 and am unable to select any date prior to 2019 => **KO**

If I remove mdMaxDate, there is no problem anymore with min date: I can select any date from "2000" to "2020" in month view.

 -  `What is the expected behavior?`

In the month view, I should be able to scroll up to the year "2000".

**CodePen** (or steps to reproduce the issue): *
http://codepen.io/fbruffaert/pen/mEBPPp

**Angular Versions**: *
 -  `Angular Version:`1.5.5
 -  `Angular Material Version:` 1.5.5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52.0.2743.60 beta-m (64-bit)
 -  `OS: *` Windows 10
 -  `Stack Traces:` none

**Comment by crisbeto** [comment]
The month view validation definitely needs some more work. Also referencing https://github.com/angular/material/issues/8886
