### ISSUE TITLE
md-select options change position on resize windows

### ISSUE THREAD

**Issue by dennieru** [angular/material#8985]
**Actual Behavior**:
-  `When you expand options in a select component, resize the window's browser and back to original size the position of the options has changed` *
-  `Position of options in select component must be fixed in spite of resize`

*You can reproduce in the demo page *
-  [`Angular Material demo > select`](https://material.angularjs.org/latest/demo/select)

**Comment by dennieru** [comment]
![capture](https://cloud.githubusercontent.com/assets/3968015/16703087/a6d2f684-4538-11e6-9ff2-e0129e9b898d.PNG)

**Comment by dennieru** [comment]
Here is a variation of the bug with a 100% width in md-select:
[http://codepen.io/anon/pen/jAGqoP](url)
![capture](https://cloud.githubusercontent.com/assets/3968015/16749502/b7db2520-4798-11e6-888a-591fb5092384.PNG)

**Comment by Splaktar** [comment]
This appears to be resolved as seen by the latest [select docs page](https://material.angularjs.org/latest/demo/select).
