### ISSUE TITLE
md-tabs (md-selected) selectedIndex changes to 10

### ISSUE THREAD

**Issue by skords** [angular/material#8988]
items.html
```javascript
<md-tabs md-swipe-content md-dynamic-height md-border-bottom md-selected="selectedIndex">
        <md-tab label="{{category.category_name}}" ng-repeat="category in categories">
            <!-- Some code here -->
        </md-tab>
    </md-tabs>
```

app.js

```javascript
angular.module('A2F', ['ui.router', 'ngMaterial', 'LocalStorageModule', 'A2Fcontrollers', 'A2Fservices', 'A2Fdirectives', 'A2Ffilters'])

// Configuration:-
.config(function($stateProvider, $urlRouterProvider) {

  $stateProvider
    .state('welcome', {
      url: "/welcome",
      templateUrl: "partials/welcome.html",
      controller: 'welcomeController',
      data: {
        requireStore: false
      }
    })
   .state('store', {
      abstract: true,
      url : '/store',
      template: "<ui-view autoscroll='true' />",
      controller: 'MainController',
      data: {
        requireStore: true // this property will apply to all children of 'store'
      }
    })
    .state('store.items', {
      url: "/items/:category/:cat_name",
      templateUrl: "partials/items.html",
      controller: 'itemsController',
      params: {
        category: '0'
      }
    })
  // if none of the above states are matched, use this as the fallback
  $urlRouterProvider.otherwise('/welcome');
});
```

controller.js

```javascript
.controller('itemsController', ['$scope', '$state', '$stateParams', function($scope, $state, $stateParams) {
 $scope.selectedIndex = $stateParams.category;
}])
```
**Actual Behavior**:
 -  `What is the issue?` *
I have more than 10 tabs. I am trying to navigate the user to the right tab based on the index that is passed as a state parameter `category`. Whenever I pass `category` as `1`, the selectedIndex changes to 10 and the user is navigated to a different tab. It works fine if `category` is `0` or `2` or any other number.
 -  `What is the expected behavior?`
selectedIndex should be 1 instead of 10.

**Angular Versions**: *
 -  `Angular Version:` 1.5.6
 -  `Angular Material Version:` 1.0.9

----

**Comment by topherfangio** [comment]
Can you please provide a Codepen that shows the issue using only Material? It looks like you have a lot of additional dependencies that we can't include which makes it difficult to test/debug.

**Comment by aandy28** [comment]
I had a similar issue using md-tabs within a md-dialog and it was being cause by selectedIndex not being declares as a number once it was reset.

**Comment by skords** [comment]
I solved the problem by using parsing selectedindex as integer.

**Comment by topherfangio** [comment]
@skords @aandy28 Can you guys elaborate a bit? Is this an issue with Material not setting the `selectedIndex` properly or something in your code?

**Comment by aandy28** [comment]
For me I was changing selectedIndex on click based on an index from an
image, this was being set via attr.index but because it was from attr it
was a string not a number.

**Comment by topherfangio** [comment]
@aandy28 Ah, gotcha.

Okay, then I'm going to go ahead and close this. Please post another comment if you think something in Material needs to change.
