### ISSUE TITLE
Dynamic tile height in grid?

### ISSUE THREAD

**Issue by krystalcode** [angular/material#8991]
I understand that at the moment you need to specify the number of rows that a tile will span in a grid. Is there any way, maybe with some extra javascript, to dynamically change the number of rows so that the content can vertically fit in? That would be a nice feature.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
