### ISSUE TITLE
feature(theme):  integrated theme explorer

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#8994]
I propose that we create and publish in our theming docs a "Theme Explorer".

Below is an example explorer tool... it is missing however features for **dark** themes and **text colors**.

---
http://www.materialpalette.com/brown/teal

![screen shot 2016-07-10 at 9 42 45 am](https://cloud.githubusercontent.com/assets/210413/16714283/edb7a986-4683-11e6-8e3c-2374015e08b8.png)

**Comment by clshortfuse** [comment]
Feel free to pull html from http://codepen.io/shortfuse/full/qZojGW/ for previews

**Comment by topherfangio** [comment]
@ThomasBurleson I have thought of this in the past as possibly applying the theme to the entire site (so you can see how each component would look). Is that something we should investigate, or do you think it wouldn't be useful?

@clshortfuse That's pretty awesome!

**Comment by clshortfuse** [comment]
@topherfangio #8995 would be very useful for that. I'd like to see a theme picker on some corner of the page.

**Comment by ThomasBurleson** [comment]
@topherfangio - the feature to updating the entire doc site is a good idea because you can navigate away from the explorer to see other components and the theme changes. Nevertheless, the theme explorer itself should show the panel and list (as shown) components.

**Comment by EladBezalel** [comment]
@ThomasBurleson @topherfangio agree with both of you, this will be cool!

**Comment by topherfangio** [comment]
@ThomasBurleson Totally agree that the explorer page should show the panel/list (and maybe others).

Looking forward to working on this 😄

**Comment by topherfangio** [comment]
Prototype so I don't forget the URL: http://codepen.io/topherfangio/pen/AXypqg?editors=1000

**Comment by killerspaz** [comment]
I built this a while back, feel free to use anything that helps! MIT license.

**Comment by Splaktar** [comment]
1. We currently have something like this [here](https://material.angularjs.org/latest/demo/colors#theme-picker), though it is a little less flashy and impressive.

1. The Material Design team's [Color Tool](https://material.io/tools/color/#!/) provides a great theme explorer along with some tools to help with accessibility recommendations. This tool just happens to be built with AngularJS 1.6.2 and AngularJS Material 1.1.3 as well!

    Here are some screenshots of the color tool in action:
    ![material io_tools_color_](https://user-images.githubusercontent.com/3506071/44255275-7c470280-a1d3-11e8-8815-369531a5af8c.png)
    ![material io_tools_color_ 1](https://user-images.githubusercontent.com/3506071/44255278-7f41f300-a1d3-11e8-897a-ade32c4c12e4.png)


1. The Material Design team has also published a Sketch plugin that adds a [Material Design Theme Editor](https://material.io/tools/theme-editor/).
