### ISSUE TITLE
autocomplete: md-not-found appears before the promise is resolved and the results are returned

### ISSUE THREAD

**Issue by dhiman252** [angular/material#8998]
**Actual Behavior**:
 -  `md-not-found appears before the returned promise is resolved and after the promise is resolved the items appear`
 -  `when the deffer.promise is returned then md-not-found must wait to get appear till the $http promise is resolved`

**Angular Versions**: *
 -  `Angular Version:1.4.9`
 -  `Angular Material Version:1.0.0`

**Comment by dhiman252** [comment]
In autocomplete the response is loaded from the remote URL, so as the user types in the old request is aborted if the response has not been received using the deffer object and in  the mean time of the assignment the no-results found is displayed.

**Comment by crisbeto** [comment]
1. Can you try with a newer version of Material?
2. Can you provide a codepen that demonstrates the issue?

**Comment by dhiman252** [comment]
1) I tried with the new version ie v1.9 but still the same issue
2) I have created a pen http://codepen.io/dhimanmohit/pen/PzJVVx and for the sake of time i have embedded the http call in the controller itself instead of creating a new service, Please add your URL and view the results

**Comment by DevVersion** [comment]
@dhiman252 We are not able to "create" our own backend / URL to demonstrate your issue. Please provide a demo, which shows your issue.

**Comment by DevVersion** [comment]
Please resubmit with a working demo.
