### ISSUE TITLE
webkit-flex CSS  is not applying in safari browser in gulp dist mode

### ISSUE THREAD

**Issue by mallik482** [angular/material#8999]
**Actual Behavior**:
 - Webkit flex css is not applying in safari browser for new angular material version
 - -webkit-flex css should apply in safari browser

**CodePen** (or steps to reproduce the issue): *
 -  issue in gulp serve:dist mode
 -  no

**Angular Versions**: *
 -  1.5.3
 - 1.0.0

**Additional Information**:
 -  Safari
 -  v8.0.8
 -  Mac & Windows
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by oli107** [comment]
+1

**Comment by mpiasta-ca** [comment]
+1 Using #master and seems to be causing issues with rendering in our older Safari/Chrome browsers, which were working with 1.0.9.
