### ISSUE TITLE
menu: Safari MacOS content flicker on open

### ISSUE THREAD

**Issue by ivan-zakharchuk** [angular/material#9000]
**Actual Behavior**:
-  md-menu(in some rare cases md-dialog too, therefore I can assume that problem is in md-backdrop) after open cause content flicker in Safari
-  md-menu open doesn't cause page flicker

**CodePen** (or steps to reproduce the issue): *
-  http://codepen.io/aromanyukvakoms/pen/grGyaP
-  `Details:` Actually to reproduce this issue you need open CodePen in debug mode (http://s.codepen.io/aromanyukvakoms/debug/grGyaP) and scroll down - press "OPEN MD-MENU", press on backdrop element to close menu, scroll to few pixels up and repeat, after 2-3 iteration(with scrolling to up and down in turn after each iteration) you can see this page flicker which look like page scroll shift by Y-Axis. This is really annoying on screen if you have long page with fixed elements.

**Angular Versions**: *
-  `Angular Version: 1.5.x`
-  `Angular Material Version: >1.0.8`

**Additional Information**:
-  `Browser Type: Safari`
-  `Browser Version: Version 9.1.1 (11601.6.17)`
-  `OS: OSX EL Capitan 10.11.5 (15F34)`

**Comment by Splaktar** [comment]
This appears to be fixed in 1.1.10 (possibly earlier). Updated [CodePen](https://codepen.io/Splaktar/pen/aRvxwJ) and [Debug View](https://s.codepen.io/Splaktar/debug/aRvxwJ).
