### ISSUE TITLE
Md-autoselect doesn't select first item in md-autocomplete

### ISSUE THREAD

**Issue by Winsehr** [angular/material#9001]
Hello!
I'm using md-autocomplete in my project and it's working well apart from that I can't seem to get md-autoselect to work. I wan't it to select first item in the list but it doesn't behave as stated in documentation (If true, the first item will be selected by default).
I tried to make md-autoselect work by experimenting with code in md-autocomplete demos but it didn't work, [http://codepen.io/anon/pen/xOXoRP]. Here I added md-autoselect and deleted placeholder.

**Comment by DevVersion** [comment]
This is working as expected. It's only selecting that in the dropdown, but it's not actually "really" selected in the scope variable.

I think it makes sense to improve the documentation for that attribute.

**Comment by Winsehr** [comment]
Okay, wouldn't it be good to display that "Alabama" is selected before you click on the list? Right now it displays nothing which is confusing and I thought it would behave in the same way as checkboxes/radiobuttons.

**Comment by DevVersion** [comment]
That's not the intention of the `md-autoselect` attribute.

If you want to specify an initial "selected" item, then you could just set it's value in the scope.

```html
<md-autocomplete md-selected-item="ctrl.selectedItem" ..></md-autocomplete>
```

```js
ctrl.selectedItem = 'Alabama';
```

Here is a little demo:
- http://codepen.io/DevVersion/pen/kXxaoB

**Comment by clshortfuse** [comment]
> Okay, wouldn't it be good to display that "Alabama" is selected before you click on the list? Right now it displays nothing which is confusing and I thought it would behave in the same way as checkboxes/radiobuttons.
@Winsehr that's in progress 

#8904

**Comment by Winsehr** [comment]
Thanks, guys! :)
