### ISSUE TITLE
Md-Dialog with conditional inputs using ng-if are not bound to model 

### ISSUE THREAD

**Issue by BobDankert** [angular/material#9004]
I've found that using ng-if in a md-dialog to conditionally show a form element, the form element does not get bound to the provided ng-model property on the scope. However, using ng-show (with the same condition) works as you would expect.

Codepen demonstrating both ng-if (not working) and ng-show (working): http://codepen.io/anon/pen/BzmaKZ

Angular: 1.5.5
Material: v1.1.0-rc.5

**Comment by DevVersion** [comment]
This seems to be a bug.

It seems like the `ngIf` creates another child scope, which means that the `ng-model` isn't synced with the other scope.

When using `$parent` to apply the `ng-model` on the parent scope, everything works as expected.

This issue would require some investigation.

**Comment by DevVersion** [comment]
After some investigation, this is not an issue.

AngularJS creates by default a new child scope, when using `ng-if`.

- See a basic AngularJS demo: http://codepen.io/DevVersion/pen/WxXNgw

**Comment by BobDankert** [comment]
Thanks - Chasing the wrong issue here. Clearly expected functionality - appreciate the additional investigation.

**Comment by DevVersion** [comment]
@BobDankert You're welcome :) If you have any further questions, please let me know!
