### ISSUE TITLE
demo site not working

### ISSUE THREAD

**Issue by mikila85** [angular/material#9005]
**Actual Behavior**:
Not working

**CodePen** (or steps to reproduce the issue): *
go here: https://material.angularjs.org/latest/api/directive/mdTabs

**Angular Versions**: *
any

**Additional Information**:
chrome
![image](https://cloud.githubusercontent.com/assets/3965957/16759030/cd5712de-47c9-11e6-8e81-41b25e4310b6.png)

**Comment by DevVersion** [comment]
There was probably an issue with Firebase - it seems to work for me right now. Still having the issue?

**Comment by mikila85** [comment]
Still not working ;(

**Comment by jayeshanandani** [comment]
working fine!

**Comment by DevVersion** [comment]
@jayeshanandani Thanks, it may relate to your network. Probably running Proxies and other restrictions.
