### ISSUE TITLE
DatePicker does not work correctly with IE 11 in the 1/1/16 format

### ISSUE THREAD

**Issue by SusanDikramanjian** [angular/material#9007]
**Actual Behavior**:
 -  `In the date picker, if I manually type a date in the format 1/1/16, in IE it converts it to  1/1/1916`
 -  `1/1/16 should be converted to 1/1/2016 - it works correctly with Chrome`

**CodePen** (or steps to reproduce the issue): *
 -  `You can see the issue with the demo examples for the datepicker that you guys have on the  Angular Material Site.:`
 -  `Details:`

**Angular Versions**: *
 -  ` we use AngularJS v1.5.6 `
 -  ` v1.0.9 but it is also reproducible with the latest version`

**Additional Information**:
 -  `IE*`
 -  `11*`
 -  `Windows*`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
By default, the datepicker doesn't do any parsing, it only passes the string value through `new Date` to convert it into a proper date. This means that it's up to the browser to determine how to parse it. 

If you want some more control over the output, you can override the `parseDate` method from the [`$mdDateLocaleProvider`](https://material.angularjs.org/HEAD/api/service/$mdDateLocaleProvider).
