### ISSUE TITLE
Change position of md-switch to be on the right side?

### ISSUE THREAD

**Issue by johhansantana** [angular/material#9011]
Is there a way to change the default md-switch position on the left of the text/label to be on the right side instead?

**Comment by DevVersion** [comment]
@Lordnoname previously submitted a PR, which adds this functionality (#8205)

**Comment by jsantana90** [comment]
Hi @DevVersion how do I use that attribute, I added `md-invert` to the `md-switch` but did nothing.

**Comment by DevVersion** [comment]
@jsantana90 It's not available (yet). The PR was closed due to our deprecation efforts.

**Comment by ThomasBurleson** [comment]
@DevVersion - what is the PR # ?

**Comment by DevVersion** [comment]
@ThomasBurleson The associated PR is #8205

**Comment by Pandi1990** [comment]
Use following css for md-check element
direction: rtl;
float: left;

**Comment by recursionbane** [comment]
Would be great to support this via `class="md-secondary"`

**Comment by Splaktar** [comment]
This was implemented in 1.1.2.
