### ISSUE TITLE
md-progress-linear is not getting disabled with ng-disabled

### ISSUE THREAD

**Issue by geniusbabak** [angular/material#9016]
**Actual Behavior**:
 -  md-progress-linear is not getting disabled with ng-disabled, or disable, I tried many things.

`<md-progress-linear  ng-disabled="true" class="md-warn" md-mode="indeterminate"></md-progress-linear> `

[https://codepen.io/baabak/pen/grXKvv](url)

**Angular Versions**: *
 -  `Angular Version: 1.5.7`
 -  `Angular Material Version: 1.0.9`

**Additional Information**:
 -  `Browser Type: Firefox and Chrome`
 -  `Browser Version: Firefox 48, Chrome 51.0... `
 -  `OS: Windows 7.0`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
This should be fixed in 1.1. [Here's a forked codepen.](https://codepen.io/crisbeto/pen/ZOajGW).
