### ISSUE TITLE
md-select: "space" selects triggers completion.

### ISSUE THREAD

**Issue by DavidSouther** [angular/material#9018]
**Actual Behavior**:
 -  `What is the issue? *`

Pressing the spacebar triggers completion in md-select

 -  `What is the expected behavior?`

Pressing spacebar continues incremental completion in md-select

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`

http://codepen.io/DavidSouther/pen/NAwZGA

 -  `Details:`

In the HTML select (lower element), click to open then type "item 5". "item 5" is highlighted, and the select is open.

In the md-select (upper element), click to open then type "item 5". "item 1" becomes selected, and the md-select is closed.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.0-rc5

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` Version 51.0.2704.106 (64-bit)
 -  `OS: *` Ubuntu

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ErinCoughlan** [comment]
A few things:

1. The behavior of typing multiple characters is browser dependent. On Chrome Linux, with your Codepen, typing "Item 5" does not bring me to "Item 5". Whenever I type the letter "i" in the HTML select, I am brought to the next item that starts with "i". Typing "it" does nothing. (From [a11y keyboard testing for selects](http://webaim.org/techniques/keyboard/): "You can also filter by typing letters, but this behavior varies by browser. Some will filter as you type, like autocomplete. Others will only sort by first letter. E.g., in a list of US States, hitting A then R may take you to Arizona, or it may take you to Alabama and then Rhode Island.")

2. md-select is a listbox. It can contain images and other markup, which an HTML select does not. If you look up the [aria spec](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_listbox_role) for listbox, you'll see that pressing space should select them item, so the space behavior exists to make the component accessible.
