### ISSUE TITLE
Can you add the ability to disable an option in the md-autocomplete list

### ISSUE THREAD

**Issue by apils** [angular/material#9019]
I have an autocomplete list, and I want to be able to disable some of the results from the search based on the data. I have managed it by using an item-template containing a div with an ng-click event that stops propagation, but that seems a bit rubbish.

**Comment by DevVersion** [comment]
@apils I can't see the point of disabling an item in the autocomplete dropdown? 

The autocomplete should only show options that are based on that query (and are apparently valid).

Can you give more details about your desired use-case?

**Comment by DevVersion** [comment]
This is not supported in the Material Design specifications.

**Comment by devotis** [comment]
Use case for this is when you want to group items in the list like this: https://github.com/angular/material/issues/7417 . The items that label the group should not be clickable.

**Comment by andrehil** [comment]
@DevVersion Another use case is a list of products where some should not be selectable because of business rules, but you don't want to hide it, you just want to show users that the option is there but not selectable.

**Comment by Scheinin** [comment]
@andrehil. true

**Comment by rosostolato** [comment]
How is it going?

**Comment by tinyweasel** [comment]
I would also like this feature.

**Comment by Splaktar** [comment]
Please use [$mdPanel](https://material.angularjs.org/HEAD/api/service/$mdPanel) to implement this custom behavior in your app. This isn't part of the Material Design specifications, so we won't be adding this to AngularJS Material core.
