### ISSUE TITLE
md-autocomplete in md-virtual-repeat set values to null

### ISSUE THREAD

**Issue by leibale** [angular/material#9020]
**What is the issue?** 
`md-virtual-repeat` keeps the elements consistently placed, while dynamically changing the `$scope`.
In our case, we put `md-autocomplete` directive within the elements placed in the `md-virtual-repeat`.
Surprisingly, the outcome was that the `searchText` watch listener fired before the `selectedItem` watch listener, this would cause the `md-autocomplete` directive to "think" that the `searchText` was wrong after checking it against the new `selectedItem` causing the `selectedItem` to be `null`.

**CodePen:**
http://codepen.io/leibale/pen/zBPbYB?editors=1010
When you scroll up and down you will see red lines, indicating there is a `searchText` without a `selectedItem`.

**My workaround is:**
Add `md-delay` to the `md-autocomplete` which make the `searchText` watch listener to be fired after the `selectedItem` watch listener.
http://codepen.io/leibale/pen/VjARVE?editors=1010

**Angular Versions:**
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.1.0-rc.5

**Comment by DevVersion** [comment]
This seems to be fixed within `master`.
