### ISSUE TITLE
<md-datepicker> input field offset (IE)

### ISSUE THREAD

**Issue by qbitskey** [angular/material#9025]
Hallo,

since the last update of angular material (1.1.0-RC5) I am experiencing a styling issue on md-datepicker. There is an offset on the input field, so that the calendar icon and the ionput field are not on the same level (see attachment).

I am using IE 11 on Windows 7. In chrome etc everything is fine.

The funny thin is, that it looks all good on the codepen page but the demo page of material display the same issue.

Please help :D

Thank you in advance.

Regards
![datepicker](https://cloud.githubusercontent.com/assets/8547057/16835079/32f4a284-49b7-11e6-99e8-50b38df8f5b0.PNG)
![codepen](https://cloud.githubusercontent.com/assets/8547057/16835080/32f84b00-49b7-11e6-8c35-2eb6c817f7a2.PNG)

**Comment by crisbeto** [comment]
This was fixed with https://github.com/angular/material/pull/8645 and will be included in the next release.

**Comment by qbitskey** [comment]
Thank you very much ! Could you provide some information when the next release will be out? Thank you!
