### ISSUE TITLE
Tooltip can be outside of view in default case

### ISSUE THREAD

**Issue by mathieurivest** [angular/material#9028]
Using angular material 1.0.5 (should be the same in latest).

The **md-tooltip** can be outside of view in this case (_all constraint satisfied_):
1. using only md-tooltip (with no md-direction)
2. Large tooltip (width)
3. Element is near horizontal edges

**Workaround**: add md-direction="bottom" (which is the default, but adding it specifically doesn't pass through the same code path as the default case).

The reason is this line: https://github.com/angular/material/blob/master/src/components/tooltip/tooltip.js#L359

If there is enough up/down screen space, the "else" condition will not call "**FitInParent**", which is wrong since there may not be enough horizontal space in the screen to fit the tooltip.

**Comment by crisbeto** [comment]
Could you try with Material 1.1-rc.5. This should be fixed with https://github.com/angular/material/pull/8525

**Comment by crisbeto** [comment]
It's been a while since the last reply here. Closing since #8525 should have solved it.
