### ISSUE TITLE
Checkbox Select All wrong Behaviour/ Bug?

### ISSUE THREAD

**Issue by atodicebear** [angular/material#9029]
**Actual Behavior**:
 -  `What is the issue? *`
1. Clicking on Select all toggles off my Table? Its not more shown anymore
2. Manually clicking all checkboxes -> SelectAll is not toggled to Checked. So if I click it myself it unselects all but shows output "Unselect All" but does the opposite. 
-  `What is the expected behavior?`
1. Toggling not hiding my whole Table
2. SelectAll working correctly

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
http://codepen.io/anon/pen/QEaNLQ
I mocked the Datas from my Database. Because im not working with static checkboxes but generating them via my Database. So Problem Number 2 you can recreate in Codepen.
Number 1 seems not. Not showing this behaviour. But if i reload the Site it starts with "Unselect All" not "Select All". Toggling it hides whole Table and the Button doesnt change after clicking(stands checked). Manually checking some checkboxes same Problem. Checking manually all checkboxes toggling works. So all unchecked. Toggling again hides the Table again. So I think the Problem is in Selecting All.

Edit1:
I think its Deleting my whole array with the Data inside.
Because I have a Grid on the Side and Output there is away as well after Select all.
```
...
this.$http.get('/api/dict_values')
            .then(response => {
              this.$scope.Values = response.data;
...
  toggleAll() {
    if (this.$scope.selected.length === this.$scope.Values.length) {
      this.$scope.selected = [];
    } else if (this.$scope.selected.length === 0 || this.$scope.selected.length > 0) {
      this.$scope.selected = this.$scope.Values.splice(0);
    }
```
So the splice is working not right ?
**Angular Versions**: *
 -  `Angular Version: 1.5>`
 -  `Angular Material Version:1.1.0`

**Additional Information**:
 -  `Browser Type: Chrome Newest*`
 -  `Browser Version: Newest*`
 -  `OS: Windows7*`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
You changed code in the sample, causing side effects

>  $scope.selected = [1];

should be

> $scope.selected = [];

The Select All checkbox should be tied to ng-checked not ng-model. I made those changes and it seems to work as expected.

http://codepen.io/shortfuse/pen/WxzwBz
