### ISSUE TITLE
url not working

### ISSUE THREAD

**Issue by dga83** [angular/material#9035]
**Actual Behavior**:
 -  Can´t open https://material.angularjs.org/ from my PC but my friends can :´(
 -  To open the page

**Additional Information**:
 -  `Browser Type: Chrome
 -  `Browser Version: Version 51.0.2704.106 m (64-bit)
 -  `OS: win 10

![chromeabout](https://cloud.githubusercontent.com/assets/18294512/16857780/b0fa942e-49e7-11e6-971b-ff8c1b5f4a2e.PNG)
![angularmaterialnoopen](https://cloud.githubusercontent.com/assets/18294512/16857781/b3f1fb72-49e7-11e6-9ad5-062f25fc0a01.PNG)
![winabout](https://cloud.githubusercontent.com/assets/18294512/16857783/b633753c-49e7-11e6-80dd-f907dcc8da4a.PNG)

**Comment by dga83** [comment]
![message](https://cloud.githubusercontent.com/assets/18294512/16857844/39406944-49e8-11e6-8f67-5a346c069eb1.PNG)

**Comment by crisbeto** [comment]
Seems to be working for me on Windows 10 with all browsers. Perhaps you caught the site mid-deployment? Could you try again.

**Comment by dga83** [comment]
still not working... there is a win update, im going to update and try again... thx so its not a bug, its only my PC :s, i wont bother any more, sorry

**Comment by crisbeto** [comment]
I'll close this, but we can continue the discussion, in case anything new shows pops up.

**Comment by dga83** [comment]
anything new??? LOL
![console ping](https://cloud.githubusercontent.com/assets/18294512/16878962/1bfe4086-4a74-11e6-9f44-20c4dc2ed104.PNG)

**Comment by dga83** [comment]
grat work, this will bi my last post on the subject, shouldnt have minded...

**Comment by dga83** [comment]
be*
