### ISSUE TITLE
md-list-item md-secondary icons overlap

### ISSUE THREAD

**Issue by bogdhy** [angular/material#9037]
**Actual Behavior**:
 -  `What is the issue? *: icons are not displayed next to each other like in demo ` 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue: http://codepen.io/bogdhy/pen/RRxQVo` 

**Angular Versions**: *
 -  `Angular Version: 1.5.7` 
 -  `Angular Material Version: 1.0.9`

**Comment by DevVersion** [comment]
This is fixed in `master`.
- http://codepen.io/DevVersion/pen/akEYrV

FYI: When adding `ng-click` to the secondary icons, then the icons will be turned into an button.
