### ISSUE TITLE
md radio buttons don't highlight on keyboard tabbing (Accessibility Compliance)

### ISSUE THREAD

**Issue by pved2016** [angular/material#9038]
**Actual Behavior**:
 -  `One keyboard tabbing to md-radio button the individual radio button do not get highlighted or tabbed to. This is causing accessibility compliance issues in our application
**Expected Behavior**
 - a user should be able to tab to individual radio buttons and select the required one using a keyboard

**CodePen** (or steps to reproduce the issue): *

**Angular Versions**: *
 -  `Angular Version:` v1.4.9
 -  `Angular Material Version:`v1.0.4-master-19966a3

**Additional Information**:
 -  `Browser Type: Chrome, IE 11
 -  `Browser Version: 
 -  `OS: Windows
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
@clshortfuse Can you take a look at this when you get a chance? Specifically, I'd like to know what the Material Specs are for this and if we are compliant. If not, we should definitely add this.

**Comment by clshortfuse** [comment]
I've look over it before, essentially. Essentially, we are prioritizing using up/down (when vertical) and left/right (when horizontal) for keyboard navigation instead of Tab/ShiftTab when inside a radio-group. I can agree with the validity of this issue since, while arrow key navigation is nice, we should still support the standard navigation scheme (Tab/ShiftTab).

I'll play around with `tabindex` and try to come up with a PR for this.

**Comment by clshortfuse** [comment]
Actually, this is consistent with the current implementation of radio buttons in HTML pages. As far as I can tell any changes to `tabindex` would go against accessibility guidelines.

https://www.w3.org/wiki/RadioButton

**Comment by topherfangio** [comment]
Ah, agreed. Thanks for double-checking.

@pved2016 In general, we attempt to make our inputs/form elements work as close to the original HTML elements as possible.

**Comment by adam-beck** [comment]
I'm still confused. From the same document:

>When focus is on the group and when no radio button is selected:
>  -  Tab key press moves focus to the first radio button in the group, but does not select the radio button.
