### ISSUE TITLE
mdList: Enhance mdItem to support ripple and clicks

### ISSUE THREAD

**Issue by zachguo** [angular/material#904]
Just like the one used in the sidenav of documentation site.

See also: [related discussion on google group](https://groups.google.com/forum/#!topic/ngmaterial/yWK-MQAmVSM)

**Comment by rschmukler** [comment]
This will be part of #985. Closing as a duplicate.

**Comment by rdesimone** [comment]
@rschmukler why closing this issue? #985 is a different issue. The approach of @marcysutton (see above) should be at least documented in the md-list section with the correct directives and styling even though I am not convinced that md-button is the correct approach. Be also aware of #1890 - at a certain point we need also swipe functionality on list items. Bottom line best practices are needed to support ripple and clicks. Thanks!

**Comment by smaye81** [comment]
So, was md-list-item made to be clickable by default in 0.9.0?  It looks to be that way.  Any way that can be turned off?  Or is there documentation for how to write the markup so that list-item is not a interactive element?

**Comment by marcysutton** [comment]
Just don't put `ng-click` on a list item and it should work. Look at the [first list demo](https://material.angularjs.org/#/demo/material.components.list) to see how it works. 

Also, this issue is closed...further questions should be asked on the [ngMaterial forum](https://groups.google.com/forum/#!forum/ngmaterial). Thanks!

**Comment by smaye81** [comment]
Sorry for commenting here again, but I think this issue needs to be looked at further.  If I put an ```md-checkbox``` in the row, then it makes the entire row clickable, causing a dual ripple effect on the checkbox and the row itself:

http://codepen.io/anon/pen/gpPZvJ

**Comment by marcysutton** [comment]
@smaye81 please file a separate issue.
