### ISSUE TITLE
md-autocomplete placeholder dissappears on IE, when its focussed

### ISSUE THREAD

**Issue by technimadhu** [angular/material#9042]
**Actual Behavior**: Placeholder text disappears on IE, when field is focused, but shows in Chrome
 -  `What is the issue? *` Placeholder text disappears on IE, when field is focused,
 -  `What is the expected behavior?` The Placeholder text should stay in IE, just like in Chrome

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` Go to demo site: https://material.angularjs.org/latest/demo/autocomplete and choose the basic usage. The search text 'Choose your favorite state' shows even after i click on the field.. But on IE, this dissappears, as soon as i click.

**Angular Versions**: *1.3.x
 -  `Angular Version:`
 -  `Angular Material Version:` Latest 1.1.0.RC-5

**Additional Information**:
 -  `Browser Type: *` IE
 -  `Browser Version: *` 11
 -  `OS: *` Windows
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
The autocomplete uses the native `placeholder` attribute, which is being handled differently by different browsers. In this case IE hides the value on focus. [E.g. here's an example of a regular input that has a placeholder, without Material or any other styling.](http://codepen.io/crisbeto/pen/mEpKkq)

**Comment by technimadhu** [comment]
Thanks for your input. Looks like another thing which IE does differently
