### ISSUE TITLE
Required validation on md-select not working with ng-model

### ISSUE THREAD

**Issue by noilly** [angular/material#9046]
**Actual Behavior**:
 -  `What is the issue? *`

If the model has a valid value the required validation is not satisfied

 -  `What is the expected behavior?`

The required validation should be satisfied

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`

http://codepen.io/noilly/pen/wWpYJA

**Angular Versions**: *
 -  `Angular Version:`

1.5.3

 -  `Angular Material Version:`

1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *`

Chrome

 -  `Browser Version: *`

51.0.2704.103 (64-bit)

 -  `OS: *`

OS X 10.11.5

 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is fixed in `master`. 
> http://codepen.io/DevVersion/pen/EyoGEp

**Comment by FinalDes** [comment]
when will patch this bug to release version? @DevVersion

**Comment by bingjie2680** [comment]
There is also a bug when the ng-value is an object. The required validation does not pass when we select a value. Here is the codepen: http://codepen.io/yli/pen/PzRKZA

**Comment by DevVersion** [comment]
@FinalDes This will be available in the `v1.1.0` major release, which will come soon.

**Comment by FinalDes** [comment]
@bingjie2680 use ng-model insted of ng-value no bug
