### ISSUE TITLE
mdSidenav renders before scope variables are populated

### ISSUE THREAD

**Issue by tiagovtristao** [angular/material#9052]
**Actual Behavior**:
 -  `What is the issue? *`

The html below is loaded by a component through the property templateUrl, and the mdSidenav directive is rendered before {{ ::$ctrl.id }} gets evaluated. So the md-component-id becomes literally the string "{{ ::$ctrl.id }}"

&lt;md-sidenav
    class="md-sidenav-left md-whiteframe-2dp"
    md-component-id="{{ ::$ctrl.id }}"
    md-is-locked-open="$mdMedia('gt-sm')"&gt;
        &lt;md-toolbar&gt;
            &lt;h1 class="text-center"&gt;{{ $ctrl.header }}&lt;/h1&gt;
        &lt;/md-toolbar&gt;
        &lt;md-content&gt;
            &lt;menu-dropdown navigation="$ctrl.navigation"&gt;&lt;/menu-dropdown&gt;
        &lt;/md-content&gt;
&lt;/md-sidenav&gt;

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.0.9

**Comment by crisbeto** [comment]
@tiagovtristao I couldn't reproduce it, at least with the docs examples. Can you post a demo that shows the issue? As a side note: doesn't adding `ng-cloak` work?

**Comment by tiagovtristao** [comment]
@crisbeto check https://jsfiddle.net/hjpnp7g6/

If you click on MEN text you get the console error 'No instance found for handle left-sidebar', BUT if you change "{{ $ctrl.id }}" on line 4 to "left-sidebar", then when you click on the text again, the side bar will open

**Comment by crisbeto** [comment]
Ah thanks, now I see it. I was under the impression that the data bindings were showing instead of the text.

**Comment by tiagovtristao** [comment]
No worries, and thanks :)
