### ISSUE TITLE
Appearance quirks on Chrome and iPhone 6

### ISSUE THREAD

**Issue by viztastic** [angular/material#906]
Hi, I have just noticed that on Chrome - latest -  (Windows 8.1) I get this grey box when I hover over elements with ink effects:

![image](https://cloud.githubusercontent.com/assets/8556736/5390675/8b2732fa-8163-11e4-960e-d8f454b5bf5e.png)

I have also noticed that I need to tap twice on menu items to access content when I visit material.angularjs.org using my iPhone 6.

Hope this helps in some way.

**Comment by marcysutton** [comment]
No longer seeing this issue. Let us know if it pops up again!
