### ISSUE TITLE
NavBar not include in material.js with bower install

### ISSUE THREAD

**Issue by BG-Kim** [angular/material#9060]
I use angular material during 2 month. 

recently, I need navBar in my project, so i used it
But Navbar not working. so, I test with other material components and it works good. 

i checked source of navBar,  there's no navBar components.
so if you modifiy this problem, it will be fine for using.

I tested with bower install command 2016.07.18.
And I download this git hub project. and checked navBar but it works good.

but generally, i think many people use bower install for this library

thank you

**Comment by topherfangio** [comment]
Unless you specified a 1.1.0-RC branch in your bower install, you probably got the 1.0.9 release which does not include the navbar.

**Comment by ThomasBurleson** [comment]
Not an issue (with v1.1.0 RCs and later)

**Comment by BG-Kim** [comment]
Yes, I know. But, I meet navBar not working. I confuse that I think my program bug.
So, I search half day - Where is bugs??? What I miss in my program??
I Search google that material navBar Issue. And, I can not found my source. 
So, I open material library and read source. and i found not include navBar in bower install default version.
If I know this. save my times. 
My purpose  this issue. Simply, current default version martial library 1.09. not include Navbar.
