### ISSUE TITLE
mdOption: Doesn't show value when selected if using ng-if(even if the if is true)

### ISSUE THREAD

**Issue by epelc** [angular/material#9061]
**Actual Behavior**:
-  `What is the issue? *` md-option won't show the value selected(when the select is closed) if the option has an `ng-if` on it(even if it is true).
-  `What is the expected behavior?` It should show the option

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/JKpGww
-  `Details:` For some reason I can't reproduce in the codepen. But checking locally it definitely doesn't work when using anything later then `1.1.0-rc.5`(ie some specific commit or master).

**Angular Versions**: *
-  `Angular Version:` 1.5.7
-  `Angular Material Version:` master

**Additional Information**:
-  `Browser Type: *` chrome
-  `Browser Version: *` 51.0.2704.106 m
-  `OS: *` windows 10
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by epelc** [comment]
Locally adding `value="some string"` seems to fix it. I'll leave this open in case someone knows what actually broke this since 1.1.0-rc.5 or in case I can find the commit.

**Comment by yuvalbl** [comment]
I've got an issue with having ng-if on the containg element of the md-select.
It might be related. I've manage to reproduce it on codepen with Angular 1.5.5 and Angular-Material 1.1
https://github.com/angular/material/issues/9372

**Comment by Splaktar** [comment]
This is because `ng-if` causes a new scope to be created. The solution is to use `ng-controller="MyController as ctrl"` syntax as demonstrated in this [CodePen](https://codepen.io/Splaktar/pen/ZjYgEv?editors=1010#0).
