### ISSUE TITLE
Layout: Custom screen breakpoints list

### ISSUE THREAD

**Issue by keenondrums** [angular/material#9064]
**Actual Behavior**:
 -  `What is the issue? *` Layout breakpoints are hard coded in SCSS 
 -  `What is the expected behavior?` Layout breakpoints are supposed to be a list with !default value, which can be easily overridden.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` I have already implemented it in my fork https://github.com/keenondrums/flex-layout . I don't see much sense in submitting a PR due to your focus on Material 2 and this being a breaking change for sure. It's just something for you to think about for Material 2.

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.0.6

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 51.0.2704.106 m
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
@keenondrums - we are actively working on Angular Layouts 2... which should support custom breakpoints.
