### ISSUE TITLE
fix(scss): should allow multiline comments

### ISSUE THREAD

**Issue by EladBezalel** [angular/material#9066]
Multiline comments:
```js
/**
 * yay
 */
```
Can't be compiled (in some node versions) with [`node-sass`](https://github.com/sass/node-sass) into 1 line comment,

**Comment by DevVersion** [comment]
FYI: Issue is only present in the theming pipeline, since it's not minifying the SCSS.

The most elegant solution would be:
- Minifying the SCSS for the `$MD_THEME_CSS` constant.
- Not minifying the SCSS, when exporting a release build for `bower-material`.

**Comment by ThomasBurleson** [comment]
I think we should minify the $MD_THEME_CSS string.

**Comment by DevVersion** [comment]
@ThomasBurleson Agreed. But as said above, we shouldn't minify for `bower-material` deploys. Pretty simple `gulp-if`
