### ISSUE TITLE
Changing the md-select border(underline) color

### ISSUE THREAD

**Issue by dbhat1** [angular/material#9070]
**Actual Behavior**:
 -  `What is the issue? *` I want to change the border line color under md-select menu to grey. It is purple now. But I am unable to get down to that element inspite of trying different combinations of drill down to get to that element.
 -  `What is the expected behavior?`
It should change the line color of md-select drop down menu to grey

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

Here is a snippet of my code
Setup.html
 
<div flex="50" flex-offset="5">
                                                                                <form name="form-horizontal">
                                                                                                <md-input-container class="md-block" flex-gt-sm="">
                                                                                                                <label>State</label>
                                                                                                                <md-select ng-model="model.setup.selectedState">
                                                                                                                                <md-option ng-repeat="s in model.states" ng-value="s">
                                                                                                                                                {{s.name}}
                                                                                                                                </md-option>
                                                                                                                </md-select>
                                                                                                </md-input-container>
                                                                                </form>
                                                                </div>
 
Color.css
 
md-input-container:not(.md-input-invalid).md-input-focused .md-input {
    border-color: #808080
}
md-input-container:not(.md-input-invalid).md-input-focused label {
    color: #808080
}

**Angular Versions**: *
 -  `Angular Version:` ~1.5
 -  `Angular Material Version:`1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`
 -  `OS: *` windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
Issues on Github are related to issues with the acual code.

Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial).

**Comment by MarouaneSH** [comment]
To change label color and underline : 
`mat-focused .mat-form-field-label{
  color: #ee6e73;
}
.mat-focused .mat-form-field-underline .mat-form-field-ripple{
  background: #ee6e73;
}`

**Comment by Splaktar** [comment]
@MarouaneSH Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
