### ISSUE TITLE
how to show html content for md-selected-item in md-autocomplete

### ISSUE THREAD

**Issue by maheshk172** [angular/material#9073]
We are trying to use **md-autocomplete** in our application. Things are working as expected, but we have a specific requirement for displaying the selected item. Instead of just displaying a text, we need to display a HTML content with some avatar and formatted content.

**md-item-text** only displays any text provided, I tried the html content, but it does not work.

**md-item-template** works for the items displayed in the list, but the same styling is not applied to selected item.

Is there anyway to show the html content in Selected Item ? Any suggestions ?

**Comment by DevVersion** [comment]
It is not possible to adjust the `md-selected-item` with some avatars, since the selected item is actually just setting the inputs value to the associated searchText.

Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
