### ISSUE TITLE
md-chip with e-mail value - key combination for "@" pushes chip

### ISSUE THREAD

**Issue by ghego1** [angular/material#9074]
**Actual Behavior**:
-  `What is the issue?` when entering new values in a `md-chips` directive, pressing the keys combination for `@` symbol causes the value to be added to the array of chips when `md-separator-keys` is set to key `186`.
-  `What is the expected behavior?` the `@` symbol should be displayed 

**Steps to reproduce the issue**
-  `Demo which shows your issue:` the issue can be reproduced even at [https://material.angularjs.org/latest/demo/chips](https://material.angularjs.org/latest/demo/chips) (in particular "custom separator" chip).
-  `Details:` enter some text, then press the combination to display the `@` symbol (keyboard layout may be essential, see below).

**Angular Versions**:
-  `Angular Version:` 1.5.3
-  `Angular Material Version:` 1.0.9 and 1.1.0 RC5

**Additional Information**:
-  `Browser Type:` Chrome
-  `Browser Version:` 51.0.2704.103 (64-bit)
-  `OS:` MacOSX 10.11.5
-  `keyboard layout:` Italian (apple)
-  `key combination for "@" symbol:` `ALT + ò` (key on the right of `L`)

**Comment by topherfangio** [comment]
I am having some trouble reproducing this since I do not have an Italian keyboard.

Do you know if there is a similar issue we can reproduce using an English keyboard layout so that we can fix the problem?
