### ISSUE TITLE
Textarea height is caluclated incorrect

### ISSUE THREAD

**Issue by cakeinpanic** [angular/material#9075]
**Actual Behavior**:
lineHeight for textarea is calculated incorrect:
https://github.com/angular/material/blob/master/src/components/input/input.js#L456
so my textarea is VERY big)

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.1.0-rc.5

**Comment by crisbeto** [comment]
Can you post a codepen with an example?

**Comment by cakeinpanic** [comment]
https://codepen.io/cakeinpanic/pen/xOYakP

**Comment by crisbeto** [comment]
Are you expecting the textarea to be a single line? The codepen that you posted seems to work as expected on Chrome.

**Comment by cakeinpanic** [comment]
i expect that it would be two lines max, i set max-rows attribute
On my codepen it can't be seen, but adding some min-height helps a lot:
https://codepen.io/cakeinpanic/pen/xOYakP
If you try to debug it looking at line i specified in first message, you'll see that lineHeight is calculated incorrect)

**Comment by crisbeto** [comment]
[Your codepen](https://codepen.io/cakeinpanic/pen/xOYakP) is as high as it is, because you have a `min-height` on it which overrides the height set by the textarea directive. If you remove the `min-height`, it starts off at 1 row and grows to 2 rows max as expected. [Here's a fork.](https://codepen.io/crisbeto/pen/XKkPzz)

**Comment by crisbeto** [comment]
@cakeinpanic Did you manage to resolve the issue?

**Comment by cakeinpanic** [comment]
We have resolved it by some CSS manipulations. It still seems strange for me that min-height influences that way on row height, but we found a workaround and feel comfortable for now)

thank you for your help
