### ISSUE TITLE
mdAutocomplete: Large data set cripples IE

### ISSUE THREAD

**Issue by belcherbrandon** [angular/material#9081]
**Actual Behavior**:
 -  `What is the issue? *` A simple autocomplete backed by a query which returns a large array (500+ items) displays the results instantaneously in Chrome and Firefox but takes 30 seconds in IE11.  During this time, the browser is unresponsive.  Our actual scenario has more complex objects in the query result and uses an item-template.  It takes a few seconds in Chrome and about 90 seconds in IE.
 -  `What is the expected behavior?` IE should not take 50x longer to display results.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/bpb/pen/LkQaQy
 -  `Details:` This is based on the autocomplete inside a dialog example.  Our use case is actually inside a dialog as well, but I'm not sure what effect the dialog has on this if any.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.0.8, 1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` Desktop
 -  `Browser Version: *` IE11
 -  `OS: *` Windows 10
 -  `Stack Traces:`

**Comment by crisbeto** [comment]
I can reproduce it as well. It seems to be more of a problem of the virtual repeater, rather than autocomplete. Here's what the timeline looks on IE (each of those red bars takes 1sec+ and comes from the virtual repeater):

![timeline](http://i.imgur.com/P2PCcUh.png)

**Comment by belcherbrandon** [comment]
Could not reproduce in regular virtual repeater.  Issue appears starting in v1.0.0-rc7.

**Comment by crisbeto** [comment]
I'll take a better look at it today, but all the call stacks were pointing towards the repeater.

**Comment by crisbeto** [comment]
I think I found the cause @belcherbrandon. You can follow the change at #9089.
