### ISSUE TITLE
Unable to populate the images for different categories using material design

### ISSUE THREAD

**Issue by dbhat1** [angular/material#9082]
**Actual Behavior**:
 -  `What is the issue? *`
I want to display a list of images based on the category chosen by the user. I have re-written Category selection part of code from bootstrap to material design as shown in section 1. 
But this is just populating the category names. And is not populating the corresponding images present in each category. Section 2 has the code to
populate the images. Is it because that needs material design code too? How can I populate the images for the category chosen in Section 1 using material design.

 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
Section 1

```html
<md-input-container class="md-block" flex-offset="40">
							<label>Category:</label>
							<md-select ng-model="model.selectedCategory">
								<md-option ng-repeat="c in model.images.categories" ng-value="c">
									{{c.name}}
								</md-option>
							</md-select>
					</md-input-container>
						<md-button class="md-raised" id="btnClear" ng-click="clearInput();">Clear</md-button>
```

Section 2
```html
<div class="form-group">
							<label>Category:</label>
							<div class="col-sm-8 col-xs-9">
									<select id="inputCategory" class="form-control" ng-model="model.selectedCategory" ng-options="c.code as c.name for c in model.images.categories"></select>
							</div>
							<div class="col-sm-2 col-xs-2">
				<button type="button" id="btnClear" ng-click="clearInput();" class="btn btn-default" role="button" aria-disabled="false">Clear</button>
							</div>
					</div>
```

 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`~1.5
 -  `Angular Material Version:`1.1

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
Rather than pasting some of your code, can you please provide a Codepen demo which shows what you mean?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
