### ISSUE TITLE
md-autocomplete needs public methods for repositioning (or init)

### ISSUE THREAD

**Issue by NKjoep** [angular/material#9085]
**Actual Behavior**:
- `What is the issue?`
 it's impossible to programmatically init, close or reposition the autocomplete list.

- `What is the expected behavior?`
 I would love to have a public method like `init()`, `close()`, `reposition()` exposed by the `MdAutocompleteCtrl`

**Comment by DevVersion** [comment]
The autocomplete is not designed to open the dropdown programmatically.

You could still open / close the `dropdown` by using the following properties
- [Hidden Property](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L36)

Repositioning is currently not exposed, but we could make that public - but we'll not document that function.
- [Repositioning Function](https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L88)

If you want to reposition the dropdown right now, then you can trigger a `resize` event on the window.
```js
angular.element($window).triggerHandler('resize');
```

**Comment by NKjoep** [comment]
@DevVersion Thank you for your suggestion! It is very appreciated.

Quote: `The autocomplete is not designed to open the dropdown programmatically.` 

Please take into account to re-evaluate its design then :) A web interface runs more than one widget or component at the same time and who knows what is the reason why the autocomplete should be closed programmatically? 

Second point is, why trigger the window resize event? window resize is so generic and other components more than autocomplete probably are listening to that. I think is a good answer to fix my personal problem in my personal project but It can't be accepted as a solution since it could slow down performances.

**Comment by DevVersion** [comment]
> Please take into account to re-evaluate its design then :) A web interface runs more than one widget or component at the same time and who knows what is the reason why the autocomplete should be closed programmatically?

As mentioned above, you're still able to open / close those programmatically, but there won't be any documented API to do this.

I could reconsider this, if @ThomasBurleson chimes in an gives some feedback.

> Second point is, why trigger the window resize event? window resize is so generic and other components more than autocomplete probably are listening to that. I think is a good answer to fix my personal problem in my personal project but It can't be accepted as a solution since it could slow down performances.

As said above, we will make that reposition function public. In meanwhile you could use the `workaround` with triggering the `resize` event.
