### ISSUE TITLE
How to disable pause when alert close?

### ISSUE THREAD

**Issue by scorpioRED** [angular/material#9086]
Hi. I`m trying to use$mdDialog.alert 
$scope.showAlert = ()=> {
            alert = $mdDialog.alert({
                title: 'Attention',
                textContent: 'This is an example of how easy dialogs can be!',
                ok: 'Close'
            });
            $mdDialog
                .show( alert )
                .finally(function() {
                    alert = undefined;
                });
        }

But when I pressing "ok" buttom it close with pause. How I can fix it ?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
