### ISSUE TITLE
How to count on chips??

### ISSUE THREAD

**Issue by Dwiga** [angular/material#9092]
how to make a count on it?
for example,
Banana (1), Apple (1), Tomato (1)
----------------------------------
after that, i write on it tomato again
it'll become like this
Banana (1), Apple (1), Tomato (2)
----------------------------------
thank for your help.
dwi.ahmad@protonmail.com

**Comment by DevVersion** [comment]
Normally you should ask that question in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial).

---
You can easily add a counter, by using the following markup:
```html
<md-chips ng-model="ctrl.fruitArray">
  <md-chip-template>
    <strong>{{$chip}}</strong>
    <em>({{  ctrl.fruitArray.indexOf($chip) + 1 }})</em>
  </md-chip-template>
</md-chips>
```

Here is a working demo:  http://codepen.io/DevVersion/pen/akYVPm

**Comment by Dwiga** [comment]
I am so sorry if I doing wrong,
but, I am so thank you for your answer.
I'll try it..
thank you very much!!
@DevVersion

**Comment by Dwiga** [comment]
Sorry to ask again,
it's doesn't like what I mean...
for example : 
before : Apple (1), Banana (1), Orange (1)
------------------------------------------
then I write on it "Apple" again, the apple count change to two
after : Apple (2), Banana (1), Orange (1)
-----------------------------------------
after that, I write "Apple" again,
after 1 : Apple (3), Banana (1), Orange (1)
------------------------------------------
it's increase by adding same fruit on it...
hope you understand what I mean..
thanks
