### ISSUE TITLE
md-select: required validation on reselecting value

### ISSUE THREAD

**Issue by michalkop93** [angular/material#9093]
**Actual Behavior**:
 -  `What is the issue?` When reselecting value select goes into invalid and empty state
 -  `What is the expected behavior?` state of select is unchanged

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/PzRJyW
 -  `Details:` reselect MO and md-select become invalid (failing required validation)

**Angular Versions**: *
 -  `Angular Version:` 1.5.*
 -  `Angular Material Version:` 1.1.0-rc.5

**Additional Information**:
 -  `Browser Type:` Chrome
 -  `Browser Version:`  51
 -  `OS:` Win 10x64
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is also fixed within `master`. Will land in the `v1.1.0` major release.
