### ISSUE TITLE
$mdDialog.show() is freezed after show/hide

### ISSUE THREAD

**Issue by MrFranke** [angular/material#9096]
**Actual Behavior**:
 -  `What is the issue? *:` After open dialog i can't close this about 5 seconds

**CodePen** (or steps to reproduce the issue): *
 -  No need codepen demo, because it's reproduced on the [demo site](https://material.angularjs.org/latest/demo/dialog)

**Angular Versions**: *
 -  `Angular Version: ` 1.5.7
 -  `Angular Material Version: ` 1.0.9

**Additional Information**:
 -  `Browser Type: * ` Google Chrome
 -  `Browser Version: * ` 51.0.2704.103 (64-bit)
 -  `OS: *` OSX El Capitan 10.11.5 (15F34)

**Comment by DevVersion** [comment]
@EladBezalel This is not really bug. The listeners will just initialize after the dialog is completely shown. This leads to the freeze experience.

I locally tried to initialize the listeners before, and it seems to work like a charm.

Any thoughts?

**Comment by MrFranke** [comment]
UPD: this problem in all popup-s in framework (md-menu also freeze)
I can reproduce this bug in chrome only. FF and Safari on mac os work fine.

**Comment by MrFranke** [comment]
Sorry, it's my fall. This bug reproduce only on my macbook

**Comment by EladBezalel** [comment]
@MrFranke me and @DevVersion were able to reproduce it, @DevVersion made a pr #9120 that will be merged soon, thanks :)
