### ISSUE TITLE
Aria - How do I purge my framework of it

### ISSUE THREAD

**Issue by leadinglocally** [angular/material#9098]
I have no use for this annoying feature, how do I disable or remove it?

Many thanks,

Alex

**Comment by DevVersion** [comment]
Please read [the documentation of the `$mdAriaProvider`](https://material.angularjs.org/HEAD/api/service/$mdAriaProvider).

> You are able to disable $mdAria warnings, by using the following markup.

> ```js
app.config(function($mdAriaProvider) {
  // Globally disables all ARIA warnings.
  $mdAriaProvider.disableWarnings();
});
```

You're only able to disable the warnings.

**Comment by leadinglocally** [comment]
many awesome, such love

**Comment by DevVersion** [comment]
As conclusion, there will be no way to completely remove the `aria` module of ngMaterial, since it's a core functionality. Closing this as it's not an issue.
