### ISSUE TITLE
Locked sidenav in IE10 takes time to display

### ISSUE THREAD

**Issue by hans-d** [angular/material#910]
Browsing the demo site with IE10 with >= 960px wide browser: 

- the left sidenav is not displayed 
- it takes some time and only after the top blue band is clicked
- when a choice is made in the sidenav, start at the top of this list....

In the sidenav demo, the right sidenav (toggle) is working good

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
