### ISSUE TITLE
mdSelect: user input from number pad does not function correctly

### ISSUE THREAD

**Issue by danjarvis** [angular/material#9104]
**Actual Behavior**:
 -  `What is the issue? *` Pressing 1 through 9 on the number pad does not change the selected value, when applicable.
 -  `What is the expected behavior?` 1 through 9 on the number pad are accepted by the component.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/danjarvis/pen/EyEppP
 -  `Details:`Load up the demo and try to change the selected value with the number pad keys.

The issue is that `keydown` events specify codes 97 - 105 for 1 - 9 on the number pad.

Note: I have a patch ready to go. I will submit a PR in the next 24 hours.

**Angular Versions**: *
 -  `Angular Version:` 1.5.3
 -  `Angular Material Version:` 1.0.9

**Additional Information**:
 -  `Browser Type: *` Chrome, Firefox, IE
 -  `Browser Version: *`  Chrome: 51.0.2704.79, Firefox: 45.2.0, IE: 11
 -  `OS: *` Debian, Windows 10
 -  `Stack Traces:`

**Comment by DevVersion** [comment]
@topherfangio Can you probably take a look at this? Since you're pretty often working with the keyboard  related things :)

**Comment by p-mcgowan** [comment]
please reopen - using angular 1.5.9 and material 1.1.1 this issue still occurs http://codepen.io/p-mcgowan/pen/MbBvoB

**Comment by eladh** [comment]
Hi  @ThomasBurleson 
its seems that zero numpad (Keycode = 96) is not in the part of the check in isNumPadKey

` isNumPadKey : function (e){ return (3 === e.location && e.keyCode >= 97 && e.keyCode <= 105);`


best,
elad.

**Comment by Splaktar** [comment]
@eladh please open a new issue with a CodePen reproduction if that is still a problem for you in 1.1.10 or `master`.
