### ISSUE TITLE
md-no-underline not working

### ISSUE THREAD

**Issue by sujithmaddi** [angular/material#9105]
<md-select md-no-underline ng-model="selectedStatusType"
  

I am using the above code and I don't want the underline on md-select. md-no-underline is not working.
Am I using it in the correct way? Could not add the entire code as it seems to be disappearing when I add real code.

**Comment by clshortfuse** [comment]
`md-no-underline` is a `class`, not an `attribute`

You should be using `<md-select class="md-no-underline" ng-model="selectedStatusType">`

You can see how this work in the current demo: https://material.angularjs.org/HEAD/demo/select
