### ISSUE TITLE
Label and Icon are not center in Menu-Item (Windows IE11)

### ISSUE THREAD

**Issue by RichOren** [angular/material#9107]
**Actual Behavior**:
 -  `What is the issue? *`
In IE 11.0.096 - AM - 1.1.0-rc.5 - The `<p>` & `<md-icon>` are not centered in the `<md-button>`.
 -  `What is the expected behavior?`
The`<p>` and `<md-icon>` should be centered in the `<md-button>` in the menu-item

 -  `Details:`
Look https://material.angularjs.org/latest/demo/menu - and test the position modes examples.

**Angular Versions**: *
 -  `Angular Version:`
1.5.7
 -  `Angular Material Version:`
 1.1.0-rc.5 

**Additional Information**:
 -  `Browser Type: *`
 IE 11
 -  `Browser Version: *`
 IE 11.0.096
 -  `OS: *`
Windows.

---------

**Comment by crisbeto** [comment]
Are you referring to this?

![angular_material_-_demos__menu_-_internet_explore_2016-07-21_23-28-16](https://cloud.githubusercontent.com/assets/4450522/17039439/d4d53544-4f9a-11e6-9aac-d2ffb9253645.png)

**Comment by RichOren** [comment]
Yes - I have temp fix for now. 

I put `layout-fill` attribute on the `<div>`

and added this to my component css

```
md-menu-item > .md-button p {
    text-align: left; // for IE
    line-height: 48px; // for IE
}
```
```
<md-menu-item ng-repeat="item in [1, 2, 3]">
    <md-button ng-click="ctrl.announceClick($index)">
        <div layout-fill layout="row" flex="">
            <p flex="">Option {{item}}</p>
            <md-icon md-menu-align-target="" md-svg-icon="call:portable-wifi-off" style="margin: auto 3px auto 0;"></md-icon>
        </div>
    </md-button>
</md-menu-item>
```

**Comment by crisbeto** [comment]
[It looks like it's fixed on master.](https://material.angularjs.org/HEAD/demo/menu)

**Comment by RichOren** [comment]
Yep - It LGTM in master. Thank you for looking into that.
