### ISSUE TITLE
md-autocomplete: Clicking back into a window where an autocomplete has blurred can unexpectedly select an item

### ISSUE THREAD

**Issue by keatonboyle** [angular/material#9110]
**Actual Behavior**:
 -  `What is the issue? *`  When clicking back into a just-blurred window with a just-blurred autocomplete, the menu will appear for a moment and select the item that is at the position clicked. 
 -  `What is the expected behavior?`  When clicking back into a just-blurred window I don't expect the autocomplete menu to reopen until I specifically select the input again

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`  https://material.angularjs.org/latest/demo/autocomplete
 -  `Details:`

1. Navigate to https://material.angularjs.org/latest/demo/autocomplete .  Have another application open that you can alt-tab to while keeping your browser window visible. 
2. Click the "What is your favorite US state?" autocomplete.  (Menu will open)
3. Alt-Tab / Cmd-Tab / Somehow navigate w/o your mouse away from the browser, but keep the browser visible. (Menu will close)
4.  Without refocusing your browser yet, move your mouse just below the autocomplete input or even just below the whole "Basic Usage" card.
5. Click.  Menu will open momentarily, selecting the item in the location you just clicked and then closing the menu.

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`  1.1.0-RC.5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 51.0.2701.79
 -  `OS: *` Ubuntu
 -  `Stack Traces:`

**Comment by DevVersion** [comment]
We will not able to fix that issue, since the browser is re-focusing the last control automatically. And we don't want to have any short delay when focusing the autocomplete.

I'm open for some discussion / possible approaches.
