### ISSUE TITLE
md-divider: Responsive layout support is not properly supported

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#9112]
**Actual Behavior**:
-  `What is the issue? *` Divider will display as a column if the any responsive configuration of layout is set to `row`.
-  `What is the expected behavior?`Divider should only display as a column if the current layout is in a row configuration.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/shortfuse/pen/rLdEyR
-  `Details:` The problem is `divider.scss` is based around the `layout-row-*` only existing if it's displayed. The problem is the classes don't disappear when layout changes, locking divider into act as if it's always in a row configuration

**Angular Versions**: *
-  `Angular Version:` 1.1.0-rc5 (master)
-  `Angular Material Version:` 1.5.5

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` v52
-  `OS: *`ChromeOS

---

**Comment by clshortfuse** [comment]
Reopening because commit that closed the issue was reverted.

**Comment by Splaktar** [comment]
[Updated CodePen](https://codepen.io/Splaktar/pen/QWyRwKp?editors=1010) to doesn't use `localhost:8080` for assets.
