### ISSUE TITLE
Angular Material conflict other modules

### ISSUE THREAD

**Issue by dhiman252** [angular/material#9122]
**Description of issue**: Including the angular material library causes the pagination directive to pause while switching the records from one page to another

**Steps to reproduce**: create a simple page and include the angular material library and the module in you app using the dirPagination,now switch across the pages 

**Expected result**: There should not be any delay in displaying the records.

**Actual result**: It must not show any delay in showing records when switching pages.

**Demo**: https://plnkr.co/edit/8ByRaRbvZJMEnW4FakoO?p=preview

If you remove the dependency for the angular module `ngMaterial` the `dirPagination` works perfectly fine.

**Comment by friedolinfoerder** [comment]
It has to do with ngAnimate and not with Angular Material directly.

Remove the transition from your .post-element in your stylesheet and then it works without the 1s delay.
