### ISSUE TITLE
layout-padding-* availability

### ISSUE THREAD

**Issue by ravishan110** [angular/material#9123]
I am creating a webApp, and i want the layout-padding to be 0 in mobile devices.
Is there something like layout-padding-xs to support this? Or just any alternative to achieve this feature.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
