### ISSUE TITLE
md-autocomplete has an implicit "track by" unless the result is highlighted

### ISSUE THREAD

**Issue by mgol** [angular/material#9126]
**Actual Behavior**:
 -  `What is the issue? *`
If you have an `md-autocomplete` element with `md-item-template`, you can't use one-time bindings inside of the template *unless* you also add `md-highlight-text`. It seems as if there's an implicit track-by in the repeater.
 -  `What is the expected behavior?`
The repeater should not reuse elements unless a user explicitly asked for it (via something like `track by`).

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
https://codepen.io/mgol/pen/JKvkjv
https://codepen.io/mgol/pen/EyLRxo
 -  `Details:`
Both of those codepens are almost identical to the first one embedded at https://material.angularjs.org/latest/demo/autocomplete. The only differences are that the first one has `md-highlight-text` removed and both have the `item.display` binding changed to be a one-time one.

If you click in the input and type `s`, the first codepen will display Alabama & Alaska instead of South Carolina & South Dakota

**Angular Versions**: *
 -  `Angular Version:`: 1.5.5 & 1.5.8
 -  `Angular Material Version:` 1.1.0-rc.5 & the version compiled from 0356bed24789e2e9a1c7d7842303031f03e68760

**Additional Information**:
 -  `Browser Type: *` All
 -  `Browser Version: *` All
 -  `OS: *` All
 -  `Stack Traces:` N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
As discussed with @mgol, we won't change that behavior on the `virtual-repeat`, since the virtual repeat is supposed to recycle the old *blocks*

We will document that on the `virtual-repeat` API and link to it from the autocomplete component.
