### ISSUE TITLE
problem in ng messages with required validation in angular material

### ISSUE THREAD

**Issue by ayyappamalla123** [angular/material#9131]
**Actual Behavior**:
 -  `What is the issue? *`
    Once Validation is raised with required or pattern for first that message is showing and after if i change a input value then other validation is failing that error message is not displaying 
 -  `What is the expected behavior?`
validation message should display for second validation also

2) if we want to raise that second validation also that validation should come from valid content to in valid content

**CodePen** (or steps to reproduce the issue): *
 -  http://codepen.io/ayyappamalla123/pen/rLvEAP
 -  Steps:
   1.  first enter four digit value and click out side of the input then you will error message "That doesn't look like a valid postal code".
   2. then clear the input field now required validation will fail but required message is not dispalying which should display

to check second(2) point
   1. enter 6 digit number or 4 digit number now validation will raise
   2. now remove complete number  then it won't rise any validation
   3. now enter 5 digit number which is valid
   4. now click out side
   5. now select entire input content and delete at one shot it will rise required validation also now

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: v1.1.0-rc.5`

**Additional Information**:
 -  `Browser Type:  Chrome`
 -  `Browser Version:  Version 44.0.2403.125(64 bit)`
 -  `OS:  Ubuntu `
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by bopm** [comment]
You should use `multiple` attribute for ng-messages if you want multiple errors to be displayed at the same time. See example [here](https://material.angularjs.org/latest/demo/input) in hourly rate input.

**Comment by DevVersion** [comment]
This is fixed within `master` by @topherfangio https://github.com/angular/material/commit/fa6213d38c2959d6155b546fcadc72c150ab370b
