### ISSUE TITLE
Data table responsive design

### ISSUE THREAD

**Issue by projectmanagementsystem15** [angular/material#9132]
Data table responsive design
 -  Responsive design issue 
 -  I don't want vertical scroll bar
 - I looks like design of https://datatables.net/ when i compress browser site to mobile site same time hide/show field with **+ plus** icon please check a demo link : https://datatables.net/
 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  demo code :  http://codepen.io/yogeshp/pen/BKEpjy

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:`1.1.0

**Additional Information**:
 -  `Browser Type: all browser
 -  `Browser Version:  all browser
 -  `OS: window, mac

**Comment by Jeddf** [comment]
You're using https://github.com/daniel-nagy/md-data-table which is a different project to this one.
