### ISSUE TITLE
Card avatar alignment incorrect in Safari

### ISSUE THREAD

**Issue by gseabrook** [angular/material#9147]
When using an avatar in the heading of an md-card, the svg does not align to the middle of the icon, and so the border looks incorrect

This can be seen by viewing the Angular Material docs in safari and looking at the page for 'Card'.

Material version - 1.1.0-RC5
Safari version -  9.1 (11601.5.17.1)

<img width="414" alt="screen shot 2016-07-27 at 11 48 22" src="https://cloud.githubusercontent.com/assets/5090919/17163272/2edcfb72-53f0-11e6-892d-1c73989e975a.png">

**Comment by BenjaminHofstetter** [comment]
I solved this issue with a CSS Rule

`
md-card-avatar > md-icon {
  height: auto;
}`

**Comment by BenjaminHofstetter** [comment]
` md-card-avatar > md-icon { height: auto; }` solves Safari but breaks IE. This is not a viable solution.

**Comment by clshortfuse** [comment]
Different browsers handle SVG height and width properties differently. It might be better to explicit set the SVG to use the md-icon height and width:

```
md-icon > svg {
  height: inherit;
  width: inherit;
}
```

I'm not sure why Safari would have this issue on md-card-avatar, but not elsewhere. It might be related to `flexbox`.
