### ISSUE TITLE
Flex issue on Internet Explorer

### ISSUE THREAD

**Issue by chacabuk** [angular/material#9148]
**Actual Behavior**:
 -  `What is the issue?`Content not showing on layout="column"
 -  `What is the expected behavior?`Show it.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://codepen.io/Chacabuk/pen/mEKWVq
 -  `Details:`Try resizing window to change between column/row layout.

**Angular Versions**: *
 -  `Angular Version:`1.3.8
 -  `Angular Material Version:`1.0.9

**Additional Information**:
 -  `Browser Type: *`Internet Explorer 11
 -  `Browser Version: *`11.494.10586.0
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Please retest with v1.1.0-rc.4 or HEAD in master.

**Comment by chacabuk** [comment]
Sorry, it's my fault. I'm using the work "Flex" in wrong way.
I was corrected my code at Codepen to work correctly.
I hope someone can lern from my mistake.
