### ISSUE TITLE
Select box validate required failure when model is a object

### ISSUE THREAD

**Issue by thanhphat** [angular/material#9149]
**Actual Behavior**:
 -  `Select box validate required failure when model is a object`
 -  `What is the expected behavior? Can validate model is object`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: v1.1.0-rc.5`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 52`
 -  `OS: Mac OS`
 -  `Stack Traces:`

[src/components/select/select.js](https://github.com/angular/material/commit/da02ea2eb500dc297f4028b9cdedd4e86bffd69b)

`+      self.ngModel.$isEmpty = function($viewValue) {`
` +        return !self.options[$viewValue];`
` +      };`

`$viewValue` is object but `options` is an array contents hash value.

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is fixed in `master`.
