### ISSUE TITLE
CSS initial value is unsupported in IE

### ISSUE THREAD

**Issue by MarkFalconbridge** [angular/material#9150]
There are a number of scss files that specify "initial" as a value for various properties. IE doesn't support the value "initial" - see http://caniuse.com/#search=initial. This can lead to unexpected behaviour because IE falls back to the next most appropriate css selector.

**Comment by crisbeto** [comment]
Could you give some examples where it breaks for you. We do use `initial`, but for the cases that I've see, there's usually a fallback.

**Comment by MarkFalconbridge** [comment]
The instance I had to work around was when using md-list-item elements. When hovering over them I was getting an unexpected fallback for the <div class="md-button _md-no-style"> hover background-color. This was because elsewhere we had specified a different background-color for hovering on elements with the .md-button class so arguably, it's our problem because we've modified the .md-button class but it means you can get into an unusual fallback situation.

**Comment by clshortfuse** [comment]
Here's the usage of `initial`: https://github.com/angular/material/blob/9a2c47dea0cbb4347d2b6aeec8dd8ff3ae684cd1/src/components/list/list.scss#L149

I don't see the use of this CSS rule. `.md-button` doesn't normally have a background-color unless you add a class (`md-primary`, `md-fab`, etc). When it's generated in a list, it doesn't have any of those classes.

The issue stems from here: https://github.com/angular/material/issues/7551

In this commit by @DevVersion: https://github.com/angular/material/commit/91585893db8a84312b9fb2a904008ffb169e0946  `background-color` changed from from `inherit` to `initial`

But when tested on master, I removed the entire `background-color` rule and found no issue.

I think it can be safely removed.

**Comment by DevVersion** [comment]
@MarkFalconbridge That sounds reasonable. 

We recently removed those fallback sequences so there shouldn't be that much properties with unsupported values. See 9a2c47dea0cbb4347d2b6aeec8dd8ff3ae684cd1

---
Also could you specifically file a short issue for the list item, so I can keep track of it?

**Comment by clshortfuse** [comment]
Found `initial` in tabs and filed an issue in #9223 

I also found `initial` in 
https://github.com/angular/material/blob/82fdd2c7c1cd2eb3b84608e2245a353b561c1c28/src/components/sidenav/sidenav.js#L374

And this makes no sense: https://github.com/angular/material/blob/b9db09d5f9e59d90245ecc8986ca00a0faa6887e/docs/app/css/style.css#L190

**Comment by crisbeto** [comment]
The last few should be taken care of with https://github.com/angular/material/pull/9257
