### ISSUE TITLE
Fixing JSHint warnings

### ISSUE THREAD

**Issue by crisbeto** [angular/material#9153]
We have a lot of pretty trivial warnings from JSHint. It would be nice to have them resolved at some point.

**Comment by 5earle** [comment]
Good day. i am a student studying open source at Seneca college, and would like to take a go at this project if it is still available

**Comment by Splaktar** [comment]
@5earle we would be happy to review your PR to solve the remaining JSHint issues. Please make sure to limit the scope of the changes to the bare minimum of what needs to be changed to get JSHint passing.

**Comment by 5earle** [comment]
@Splaktar there is stuff like:

W069  Line 1497, Col 39  ['onCloseSuccess'] is better written in dot notation.
W043  Line 296, Col 17  Bad escaping of EOL. Use option multistr if needed.

would fixing these be an issue?

**Comment by Splaktar** [comment]
@5earle sorry for the delay. We should disable that rule as it is designed for supporting ES3. Those escapes are just fine in ES5, which target.

For the second, I would also disable that rule.

You can add the following to `.jshintrc` to fix both of these:
```json
  "sub": true,
  "multistr": true,
```

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material/commit/cec409a9ab3b5927f8b7726b160383a0d259c6fe.
