### ISSUE TITLE
Ripple does not fill button with md-cornered

### ISSUE THREAD

**Issue by svencowart** [angular/material#9154]
**Actual Behavior**:
-  `What is the issue?` Ripple does not fill button with md-cornered
-  `What is the expected behavior?` Ripple should fill entire button

**CodePen** (or steps to reproduce the issue):
-  `CodePen Demo which shows your issue:` http://codepen.io/svencowart/pen/JKkARL

**Angular Versions**:
-  `Angular Version:` 1.4.8
-  `Angular Material Version:` 1.1.0-RC5

**Comment by clshortfuse** [comment]
Seems like `border-radius` is being set to `3px`. I see three possible solutions:

* Remove `border-radius` completely from `md-ripple-container`
* Set `border-radius` to `inherit` in `md-ripple-container`
* Use extra CSS for `md-cornered` support

I'll investigate and make a pull request

**Comment by Splaktar** [comment]
Verified that this issue still occurs in 1.1.6.

**Comment by Splaktar** [comment]
[Codepen](https://codepen.io/Splaktar/pen/bLWEgZ) that demonstrates the resolution of this issue.
