### ISSUE TITLE
md-tabs captures navigation key strokes (alt+left / alt+right)

### ISSUE THREAD

**Issue by jheijkoop** [angular/material#9161]
**Actual Behavior**:
 -  `What is the issue? *`
When I click on a tab of a `<md-tabs>` and then press `alt+left` to navigate back, instead the focus on the tabs moves left (similar for alt-right) Therefor grabbing the input, before it can be passed to the browser
 -  `What is the expected behavior?`
I expected to navigate in history, maybe only a cursor key without alt would result in the encountered behaviour, but not the combination of `alt+left` / `alt-right`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
"angular": "1.4.9",
 -  `Angular Material Version:`
"angular-material": "1.1.0-rc.5",

**Additional Information**:
 -  `Browser Type: *`
Chromium
 -  `Browser Version: *`
Version 51.0.2704.103 (64-bit)
 -  `OS: *`
4.5.4-tuxonice #1 SMP Thu Jun 9 23:46:36 CEST 2016 x86_64 Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz GenuineIntel GNU/Linux
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Will not fix for ngM1.x
