### ISSUE TITLE
md-menu does not close with Esc key when first menu-item is disabled

### ISSUE THREAD

**Issue by siddhantpp** [angular/material#9165]
**Actual Behavior**:
 -  `What is the issue? *` When the first item in a md-menu is disabled, it refuses to close on pressing Esc
 -  `What is the expected behavior?` md-Menu should close on pressing Esc regardless of whether the first item is disabled or not.

**CodePen** (or steps to reproduce the issue): * CodePen link provided.
 -  `CodePen Demo which shows your issue:` http://codepen.io/siddhantpp/pen/AXdGxm
 -  `Details:` This CodePen demonstrates the issue. Click on Enable / Disable to test accordingly.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.0.9

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *`51.0.2704.106 m (64-bit)
 -  `OS: *` Windows 7
 -  `Stack Traces:` None

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
It's likely due to the lack of a `disabled` attribute check here: https://github.com/angular/material/blob/master/src/components/menu/js/menuController.js#L165

as seen properly implemented here: https://github.com/angular/material/blob/master/src/components/menu/js/menuController.js#L105
