### ISSUE TITLE
md-select doesn't autofill when pressing numbers on numpad

### ISSUE THREAD

**Issue by sreisner** [angular/material#9167]
I have an md-select with the values 1, 2, 3.  If focus is on the dropdown and I press 1, 2, or 3 with the numbers in the row at the _top_ of my keyboard, the dropdown automatically opens and highlights the expected element.  The problem is that when I try to do the same thing using the numpad to the _right_ of my keyboard with Num Lock on (presumably sending the same input), the dropdown does not respond.

[Link to CodePen](http://codepen.io/sreisner/pen/ZOjzzO?editors=1010)

 `Angular Version: 1.5.3` 
 `Angular Material Version: 1.1.0-rc2`

**Additional Information**:
-  `Browser Type: Google Chrome`
-  `Browser Version: 51.0.2704.103 m`
-  `OS: Windows 7 Enterprise Service Pack 1`

**Comment by crisbeto** [comment]
I think https://github.com/angular/material/pull/9106 should have addressed this already. Note that it's not released yet.

**Comment by topherfangio** [comment]
@sreisner Can you please update your Codepen to use the master branch and test? I would do it for you, but I don't currently have a keyboard with a numpad on it 😃

**Comment by topherfangio** [comment]
@sreisner Just a quick ping to see if you can test and see if it's still an issue for you.

**Comment by sreisner** [comment]
Sorry!  I'll test this asap.

**Comment by Splaktar** [comment]
Closing since this should have been fixed and the CodePen demo link is invalid.
