### ISSUE TITLE
Implement Search feature in the Material online docs

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#917]
Similar to search features in the AngularJS docs, Angular Material online docs need a search box.

#### Search UI 

![search](https://cloud.githubusercontent.com/assets/210413/5399659/d5b99a82-8132-11e4-80b4-b3e670aca745.png)

#### Search Results

![search_results](https://cloud.githubusercontent.com/assets/210413/5399662/db8d3b08-8132-11e4-89de-61345970dc8b.png)

**Comment by naomiblack** [comment]
I think we should do this the same way we do search on angular.io. Investigate.
