### ISSUE TITLE
md-datepicker with "md-open-on-focus" sometimes closes immediately on smartphones

### ISSUE THREAD

**Issue by cridus** [angular/material#9170]
**Actual Behavior**:
 -  `What is the issue? *` On android smartphones (tested on 2 devices, both in a webapp and on the demo page of your site) even if a md-datepicker has the "md-open-on-focus" attribute, tocuhing the text field brings up the software keyboard, which (I think) makes the datepicker dialog close right after opening. Also, if the keyboard is open, touching the arrow button opens the datepicker but the keyboard gets dismissed and the datepicker closes too. On md-datepickers that don't have the "md-open-on-focus" attribute, clicking on the arrow button when the keyboard is open doesn't dismiss it, so the datepicker doesn't close either.  
Why "sometimes"? because I made a codepen for this issue and it works as it should, there. In the codepen the software keyboard appears and immediately disappears, and then the datepicker shows up. In my webapp and in your demo page the keyboard opens and immediately closes, the datepicker shows up and then the keyboard opens again, dismissing the datepicker. Maybe the text field gets focused twice for some reason.
 -  `What is the expected behavior?` md-datepickers with "md-open-on-focus" should not bring up the software keyboard when touching the text field, or at least it should close immediately and then not open a second time dismissing the datepicker dialog.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` codepen that doesn't have the issue: http://codepen.io/anon/pen/XKBWqO  
Your demo page, with the issue: https://material.angularjs.org/latest/demo/datepicker
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` My webapp uses 1.4.8, your demo uses 1.5.5 and my codepen also uses 1.4.8. The issue is present only in the first two, though.
 -  `Angular Material Version:` 1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` Chrome and Android's WebView
 -  `Browser Version: *` Chrome 51.0.2704.81, WebView unknown (does Cordova use a specific version? 'Cause I couldn't find anything about it)
 -  `OS: *` Android
 -  `Stack Traces:`

Sorry if things are messy. It's late at night and this is the first "serious" issue I open, so please be gentle >_>

**Comment by crisbeto** [comment]
It happens on iOS as well. My guess is because the windows gets scrolled/resized, which makes it close. I'll see if I can work around it.
