### ISSUE TITLE
dialog(prompt): use textarea to allow for multiple lines of input

### ISSUE THREAD

**Issue by gseabrook** [angular/material#9171]
The new 'prompt' option for the md-dialog is great, however when I showed it to my client they asked if they could have multiple lines of input.

This could be achieved using a textarea instead of an input, by default it would look and behave the same, but would give the option of allow for multiple lines.

**Comment by hperrin** [comment]
+1

**Comment by Splaktar** [comment]
Closing this as the PR [was also closed](https://github.com/angular/material/pull/9173#issuecomment-245987054). This can be done with a custom dialog. We don't want to complicate the basic prompt dialog and there were some concerns about how this would change the behavior on mobile devices.
