### ISSUE TITLE
md-input-container

### ISSUE THREAD

**Issue by birdman2005** [angular/material#9174]
**Actual Behavior**:
 -  `What is the issue?  label not float when input's value changed in md-input-container`
 -  `What is the expected behavior? when the input's value is changed the label float as the input has being clicked`

**Angular Versions**: *
 -  `Angular Version:1.5.3`
 -  `Angular Material Version:1.1.0-rc2`

**Additional Information**:
 -  `Browser Type: crosswwalk 19+`
 -  `Browser Version: *`
 -  `OS: android `

**Comment by jayeshanandani** [comment]
@birdman2005 : Can you please provide codepen to illustrate this? I cannot replicate the behavior in the latest version: [https://material.angularjs.org/HEAD/demo/input](https://material.angularjs.org/HEAD/demo/input)

You have also specified wrong material version.

**Comment by birdman2005** [comment]
After set new value for input , then set the focus to it , and the label float up without animation. and thanks @jayeshanandani
