### ISSUE TITLE
mdSelect: doesn't show selected option with an empty value as selected

### ISSUE THREAD

**Issue by eberlitz** [angular/material#9178]
**Actual Behavior**:
 -  `What is the issue?`

When using an mdSelect with an empty valued option, as:

```html
<md-option value=""> All options</md-option>
```

Then, when the user selects this option, it doens't show as selected. Although the value in ng-model is working as expected. The following codePen shows the problem.

**CodePen**:  [NON Working sample of a empty value option with mdSelect](http://codepen.io/eberlitz/pen/ZOjpBg?editors=1011)

 -  `What is the expected behavior?`

The option must be shown as selected. Working sample bellow.

**CodePen**: [Working sample of a empty value option with mdSelect](http://codepen.io/eberlitz/pen/grjgOb?editors=1011)

**Angular Versions**: 
 -  `Angular Version:` 1.4.8
 -  `Angular Material Version: ` v1.1.0-rc.5-master-1eb1037

**Additional Information**:
 -  `Browser Type: ` Google Chrome
 -  `Browser Version: ` Version 51.0.2704.106 m
 -  `OS: ` Windows 8.1 Enterprise
 -  `Stack Traces:` NA

I noted that this only ocurs with the **master** version of the ngMaterial which had some changes since the rc5 version, but I didnt see any open issue related to this.

**Comment by DevVersion** [comment]
This was introduced with https://github.com/angular/material/commit/fcd42df882a1a1a1a83473204febf4ece6c5d332 and seems to be intentionally. 

Pinging @topherfangio to take over :)

**Comment by eberlitz** [comment]
Changing `<md-option value="">` to `<md-option ng-value="''">` made the trick.

+1 to add a breaking change note.

**Comment by topherfangio** [comment]
@ThomasBurleson At this point, what is the best way to get a BREAKING CHANGE note added to the changelog since I can't make a commit without editing a file, and all we really need is a commit message update?

**Comment by topherfangio** [comment]
Closed manually via Thomas: https://github.com/angular/material/pull/9240#issuecomment-237753512
