### ISSUE TITLE
Provide `versioning` of Online Docs

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#918]
Similar to doc versioning in AngularJS 1.x:

![doc_versioning](https://cloud.githubusercontent.com/assets/210413/5399741/8656fed4-8133-11e4-905e-ab1f0edbfa78.png)

> Will need to use the Select menu also planned for 0.8 Milestone release.

**Comment by epelc** [comment]
@ThomasBurleson If we decide to implement #1103  then I think [hyperboot](https://github.com/substack/hyperboot) would go really well with it.

Hyperboot allows you to save several versions of a webapp for offline viewing with the help of appcache. So if you view a version of the docs while you are online it will be available when you are offline. You can also add js to download all versions and to set defaults for which version to load.

**Comment by marcysutton** [comment]
Discussed: 
1. How far back to include picker: old versions of docs will have different links, structure, etc.
1. UI for picker: select? dropdown? archive page?
1. Where to host snapshots? Angularjs snapshots hosted on code.angularjs.org
1. Picker should include `master` but default to latest tag

**Comment by epelc** [comment]
@Marcus tutor did you take a look at hyperboot by any chance? It seems like a really good fit for this + you get offline support.

**Comment by marcysutton** [comment]
@epelc I'll assume "Marcus tutor" was supposed to be me? :stuck_out_tongue_winking_eye: 

We haven't yet, but that's a great idea. I'll have a look.

**Comment by epelc** [comment]
@marcystutton yes I think auto correct got it. Andoird is so aggressive with its spell checking.

**Comment by ThomasBurleson** [comment]
Feature Summary:  

*  Lock the documentation with its associated release. 
*  Provide a version picker to choose the associated documentation with download zip link.
*  Continue provide development documentation linked to current #master development branch.
