### ISSUE TITLE
Dialog datepicker  support

### ISSUE THREAD

**Issue by eladh** [angular/material#9181]
**Actual Behavior**:
 -  `What is the issue? Display Datepicker as a modal  `
 -  `What is the expected behavior? take a look at Materail [spec] ` (https://material.google.com/components/pickers.html#pickers-date-pickers) 

<img width="237" alt="datepicker" src="https://cloud.githubusercontent.com/assets/1949539/17268888/390b8ed0-5641-11e6-9009-c0213a2ddb92.png">

If its not in the current milstone or any other reason , its will be great to get some hint how to start supporting this kind of datepicker.

thanks for this amazing project , 
elad.

**CodePen** : *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` 

**Angular Versions**: *
 -  `Angular Version: 1.5`
 -  `Angular Material Version: latest `

**Comment by crisbeto** [comment]
I believe that the reason for not using that design for the datepicker is that it's not particularly friendly on larger screens (see https://github.com/angular/material/pull/5971). As for a fullscreen view, that might be useful, especially on touch devices.

**Comment by eladh** [comment]
thanks @crisbeto , that the same reason you mentioned - the datepicker is great , but lack of fullscreen mode - very usfull for mobile/touch devices.

is there any possibilty to use the datepicker with md-dialog in order to support fullscreen mode ?

10x

**Comment by crisbeto** [comment]
We've discussed it internally and it's not something we'd like to support at the moment.
