### ISSUE TITLE
Sidenav content beneath a md-icon positions itself at bottom during animate

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#919]
Elements that are beneath an md-icon in the md-sidenav tag align to the bottom of the sidenav during the open and close animation.  Not sure if this happens on all browsers, but should be reproducible in Chrome 39.

Example: http://plnkr.co/edit/t3EipzSFTaudDdYIQyve?p=preview

**Comment by rschmukler** [comment]
`md-icon` is unsupported right now, look for support coming in 0.8.0
