### ISSUE TITLE
md-button not disabled correctly

### ISSUE THREAD

**Issue by smcardle** [angular/material#9197]
**Actual Behavior**:
 -  `What is the issue? *`
md-button does not get disabled when contained in a parent element that has been disabled using ng-disabled
 -  `What is the expected behavior?`
md-button should not be actionable

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/smcardle/pen/PzBvod 
-  `Details:`
Clicking the button on the pen is allowed even though the md-list-item they are in has been disabled

**Angular Versions**: *
 -  `Angular Version:`
1.4.3
 -  `Angular Material Version:`
0.10.1

**Additional Information**:
 -  `Browser Type: *`
Desktop
 -  `Browser Version: *`
Chrome Version 51.0.2704.103 (64-bit)
 -  `OS: *`
Mac OSX Maverick
 -  `Stack Traces:`
N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
The buttons do not inherit the disabled state from any parent element.

**Comment by smcardle** [comment]
Hi


You cannot just make a statement like this without pointing to some form of documentation that indicates that your comment is correct..

For instance the following link suggests otherwise.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

Check the disabled property for <button /> on that page and it states for firefox ::
------------------------------------------------------------------------------
disabled
This Boolean attribute indicates that the user cannot interact with the button. If this attribute is not specified, the button inherits its setting from the containing element, for example <fieldset>; if there is no containing element with the disabled attribute set, then the button is enabled.

Firefox will, unlike other browsers, by default, persist the dynamic disabled state of a <button> across page loads. Use the autocomplete attribute to control this feature.
-------------------------------------------------------------------------------

So your comment as to buttons not inheriting their disabled state would seem to be incorrect.

Regards

Steven McArdle

**Comment by DevVersion** [comment]
HI @smcardle,

I intentionally didn't add any references to confirm my statement is correct. See below..

---
Let's consider your statement is correct.

1. Try to replace the `md-button` with a native `button` element
    This doesn't work..

    http://codepen.io/DevVersion/pen/AXPWNJ
    *This means that the browser doesn't inherit the `disabled` property in that case.*

2. As your quoted comment says, it should inherit the `disabled` property from the containing element.
  *Seems like that is not valid in that case.*

    For special elements like `fieldset` this behavior is valid.
   http://codepen.io/DevVersion/pen/wWEKkZ

3. Your statement also indicates that it should work for all type of elements.

     http://codepen.io/DevVersion/pen/dXqYEP
    It seems like this does not work either.


Best Regards.

**Comment by smcardle** [comment]
Hi


Just because it does not work does not make my comment incorrect.

You state this is valid for 

> "special elements like fieldset"

 but the mozilla page doesn't say that. It does mention "fieldset" as its example but it specifically states the following...

> the button inherits its setting from the **containing element**, for **example** "fieldset"

So, the fact that it may not be implemented correctly in browsers is another issue and does not make my statement incorrect and does not make the implementation of angularjs material incorrect based on browser implemtation.

My point regarding your initial comment, and then closing the issue, was more to do with you not providing any references to any any source's that point to your stated position being correct.

If you do have any references that confirm what your saying is true I would very much like to see them.

I do not doubt that this is the behaviour that exists but I cannot find any references to state this is correct and in fact the mozilla document would suggest otherwise.

If it is incorrectly implemented in browsers and there is no conflicting documentation available then I will quite happily raise  this as a defect with each of the browser implementers for future releases.

Personally I cannot think of any reason that disabled should not be an inherited attribute for buttons.

Regards

**Comment by DevVersion** [comment]
> but the mozilla page doesn't say that. It does mention "fieldset" as its example but it specifically states the following...

That's why I added the <kbd>3.</kbd> point, which mentions `all type of elements`, which specifically testes the `div` element.

From my understanding the wording here might be incorrect and the behavior is restricted to some specific types of elements. That's why `fieldset` for example works.

> I do not doubt that this is the behaviour that exists but I cannot find any references to state this is correct and in fact the mozilla document would suggest otherwise.
> If it is incorrectly implemented in browsers and there is no conflicting documentation available then I will quite happily raise this as a defect with each of the browser implementers for future releases.

Yeah, I'm grateful that you are trying to figure out what the correct behavior is.

---
To summarize: ngMaterial is not aiming for making any DOM changes, which are specified by the W3C specs.

The `md-button` implementation transforms into a native `button` element, so everything that occurs on a native button element is kind of not related to ngMaterial.
