### ISSUE TITLE
Custom directive is not working on md-tab

### ISSUE THREAD

**Issue by pvsvamsi** [angular/material#9199]
**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` v0.10.1-rc2
----

When adding a custom directive as an attribute in md-tab, it is not being rendered on the UI.
Instead it is being added to the md-tab-data
Can we add a custom directive to md-tab?
If yes, how to do that?

**Comment by topherfangio** [comment]
Please post this question on the [Forum](https://groups.google.com/forum/#!forum/ngmaterial) and include a Codepen using the latest version of Angular & Material.

Here is one you can fork/edit to get started: http://codepen.io/topherfangio/pen/dXgvRo
