### ISSUE TITLE
How I can close the md-datepicker on date selection 

### ISSUE THREAD

**Issue by deeppatidar** [angular/material#9204]
I need to close the date picker on date selection as well as Ok button for that I make some changes in template and added the close button method but its not working .
ng-  dblclick="calendar.selectDate(day.value); datepicker.confirm()"

**Comment by crisbeto** [comment]
Could you post the rest of your HTML in a codepen?

**Comment by deeppatidar** [comment]
@crisbeto on html I have this only 
 <span ng-switch-when="date">
                  <mdp-date-picker
                  mdp-placeholder="mm/dd/yyyy"
                  mdp-open-on-click
                  mdp-format="MM/DD/YYYY"
                  ng-model="record[column.fieldName]">
                </mdp-date-picker>
              </span>

using this lib.
angular-material/angular-material.css
mdPickers/dist/mdPickers.css
angular-material.min.js
mdPickers/dist/mdPickers.js

and injected the dependency of ngMaterial , mdPickers in angular.module.

I tried the above template changes in mdPickers.js.

**Comment by crisbeto** [comment]
You seem to be using the datepicker from a different repo. [You should post your issue there.](https://github.com/alenaksu/mdPickers/issues)

**Comment by deeppatidar** [comment]
@crisbeto  Its from same same repo but somehow I got the answer.

Thanks for reply.
