### ISSUE TITLE
md-datepicker - years selection does not show all the years

### ISSUE THREAD

**Issue by PrasannaAdiga** [angular/material#9213]
**Actual Behavior**:
 -  `What is the issue? *` When md-min-date and md-max-date is selected whose difference is more than a year then year selection does not show all the years. It just shows only the current year
 -  `What is the expected behavior?` Expected to show all the years between the selected md-min-date and md-max-date range

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Just changed the md-min-date and md-max-date in the codepen of the angular material datepicker demo 
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.1.0-RC.5

**Additional Information**:
 -  `Browser Type: *` - In any Browser
 -  `Browser Version: *` - Any version
 -  `OS: *` - Windows
![Uploading md_datepicker.png…]()

 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.
![Uploading md_datepicker.png…]()

**Comment by crisbeto** [comment]
This should have been fixed in master.[ Can you try linking this](https://material.angularjs.org/latest/angular-material.min.js) in your app, or installing the master branch from whatever package manager you're using?

**Comment by PrasannaAdiga** [comment]
Excellent:-) I have taken the latest code from master branch and it is working absolutely fine. This bug is fixed already. Thank you very much.
