### ISSUE TITLE
Refactor rtl-prop mixin to avoid extra CSS

### ISSUE THREAD

**Issue by crisbeto** [angular/material#9217]
Currently the `rtl-prop` mixin adds 3 lines worth of CSS resets. We should refactor it, in order to reduce CSS bloat.

**Comment by clshortfuse** [comment]
```
// fallback for auto
#{$ltr-prop}: 0;
// fallback for IE
#{$ltr-prop}: auto;
#{$ltr-prop}: initial;
```

There should be a `@mixin` that doesn't use this, or perhaps a boolean attribute in `rtl-prop` to not add these lines. It's not needed in every case. For example:

https://github.com/angular/material/blob/82fdd2c7c1cd2eb3b84608e2245a353b561c1c28/src/components/fabToolbar/fabToolbar.scss#L54

Doesn't need those 3 rules.
