### ISSUE TITLE
list: remove unnecessary initial property

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#9222]
**Actual Behavior**:
 -  `What is the issue? *` Certain parts of our code use the CSS rule `initial` without fallbacks
 -  `What is the expected behavior?` No fallback can create unexpected results on IE

**Angular Versions**: *
 -  `Angular Material Version:` 1.1.0-rc5

**Additional Information**:
 -  `Browser Type: *` IE
 -  `Browser Version: *` IE 10, IE 11
 -  `OS: *` Windows
 -  `Stack Traces:`

----

list-item button background color: https://github.com/angular/material/blob/9a2c47dea0cbb4347d2b6aeec8dd8ff3ae684cd1/src/components/list/list.scss#L149

In this commit by @DevVersion: https://github.com/angular/material/commit/91585893db8a84312b9fb2a904008ffb169e0946  `background-color` changed from from `inherit` to `initial`

But when tested on master, I removed the entire `background-color` rule and found no issue.

I think it can be safely removed.

**Comment by DevVersion** [comment]
Thanks @clshortfuse for creating that issue, as requested in #9150
