### ISSUE TITLE
tabs: centered tab uses "initial" width, not supported by IE

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#9223]
**Actual Behavior**:
 -  `What is the issue? *` Certain parts of our code use the CSS rule `initial` without fallbacks
 -  `What is the expected behavior?` No fallback can create unexpected results on IE

**Angular Versions**: *
 -  `Angular Material Version:` 1.1.0-rc5

**Additional Information**:
 -  `Browser Type: *` IE
 -  `Browser Version: *` IE 10, IE 11
 -  `OS: *` Windows
 -  `Stack Traces:`

----

tabs width: https://github.com/angular/material/blob/9a2c47dea0cbb4347d2b6aeec8dd8ff3ae684cd1/src/components/tabs/tabs.scss#L168

This may be old CSS since, `width` is computed on the JS side and overrides anything that is written in the CSS rule. Regardless, we shouldn't use unsupported CSS. `width:auto` seems reasonable.

**Comment by ivorobkalo** [comment]
+1

**Comment by VasiliyZhushma** [comment]
+1

**Comment by soutlan** [comment]
+1

**Comment by valenburm** [comment]
+1

**Comment by DAbrashin** [comment]
+1

**Comment by dmitriyK1** [comment]
+1

**Comment by vovashevchenko** [comment]
+1

**Comment by clshortfuse** [comment]
To everyone replying +1, are you having issues with IE and centered tabs? I was under the impression the `initial` value was ignored and overwritten.

**Comment by clshortfuse** [comment]
closed by 9c7f95e81e750c9e9b91d1e8268fe9011425262d

**Comment by ivorobkalo** [comment]
"are you having issues with IE and centered tabs?" - yes. I added +1 not "for fun".
