### ISSUE TITLE
md-select can't be valid when default value is 0

### ISSUE THREAD

**Issue by wcmboy** [angular/material#9232]
**Actual Behavior**:
 -  `What is the issue? *`md-select can't be valid when default value is 0
 -  `What is the expected behavior?`md-select should be valid when set default value.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://codepen.io/wcmboy/pen/wWYBGZ
 -  `Details:`You can see  the favoriteColor1 is 0 and the favoriteColor2 is 1.The favoriteColor1 is invalid and favoriteColor2 is valid.

**Angular Versions**: *
 -  `Angular Version:`1.5.5
 -  `Angular Material Version:`v1.1.0-rc.5-master-8dcdf82

**Additional Information**:
 -  `Browser Type: *`chome
 -  `Browser Version: *` 52.0.2743.82 m
 -  `OS: *`windows 10

**Comment by ThomasBurleson** [comment]
@topherfangio - can you investigate this?

**Comment by topherfangio** [comment]
@ThomasBurleson At first glance, this appears to be a legitimate bug. I will investigate further this afternoon and see if I can write a test/fix.
