### ISSUE TITLE
iOS/Safari md-list-item secondary button disappears

### ISSUE THREAD

**Issue by daniel-lang** [angular/material#9235]
**Actual Behavior**:
 -  `What is the issue? *` The secondary button in an md-list-item is off the page when `<p>` content stretches over multiple lines
 -  `What is the expected behavior?` The `<p>` should be small enough for the secondary button to stay on the page

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [http://codepen.io/daniel-lang/pen/bZmBdx](http://codepen.io/daniel-lang/pen/bZmBdx)
 -  `Details:` Check the second part about secondary buttons

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.1.0-rc5

**Additional Information**:
 -  `Browser Type: *` Safari, iOS (PhoneGap)
 -  `Browser Version: *` 9.1.2
 -  `OS: *` OS X 10.11, iOS 8.4

**Comment by DevVersion** [comment]
@daniel-lang Thanks for the issue, this is a Flexbox Bug inside of Safari. And was recently fixed within Chrome 44 and Opera 31

**Comment by daniel-lang** [comment]
@DevVersion Wow that was fast. Thanks for the quick response!
