### ISSUE TITLE
md-dropdown?

### ISSUE THREAD

**Issue by ilanbiala** [angular/material#924]
Is there a dropdown component that can be used until a true md-dropdown is created?

**Comment by jmuharsky** [comment]
PaulMougel, Could you clarify how the <md-select> can behave like a Menu (specifically the UX linked in your note)?  <md-select> seems built around the idea of being bound to a "current" value, and display that value as it's text (contrast with a menu, where the trigger may be any element, that is generally not representative of the "selection".

Thanks in advance, and thanks for an overall great set of components!
