### ISSUE TITLE
Required md-select with ng-model-options or object items marked invalid

### ISSUE THREAD

**Issue by jweinstein92** [angular/material#9241]
**Actual Behavior**:
 -  `What is the issue? *` When a md-select is required and its items are objects, ng-model-options with track by '$value.id' must be used. Once an item is selected, it is marked as invalid. This is an issue with or without the ng-model-options.
 -  `What is the expected behavior?` A required md-select should allow the selection of an object.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/PzymqR
 -  `Details:` The selection is marked as invalid with or without the ng-model-options. Adding allowInvalid: true to the ng-model-options sets the model, but the input is still marked invalid.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52.0.2743.82
 -  `OS: *` Mac OS X El Capitan
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is fixed within `master`

> http://codepen.io/DevVersion/pen/pbxWmj?editors=1000#anon-login
