### ISSUE TITLE
Autocomplete: useless error thrown when `md-item-text` is missing

### ISSUE THREAD

**Issue by jelbourn** [angular/material#9242]
To reproduce:
Select a value and then hit the clear button underneath
http://codepen.io/jelbourn/pen/mEzrbJ?editors=1000#anon-login

The issue is this line:
https://github.com/angular/material/blob/master/src/components/autocomplete/js/autocompleteController.js#L338

When `md-item-text` is missing, this ends up being an object instead of a string, so `toLowerCase` is not a function.

If `md-item-text` is _required_, it should throw a more informative error.

If `md-item-text` is _optional_, autocomplete should handle this case gracefully.

**Comment by DevVersion** [comment]
This is a related PR - #9221. Sometimes the `searchText` is also undefined. For example when using the autocomplete inside of the virtualRepeat.
