### ISSUE TITLE
ngShow and ngHide on directives that use comment placeholders will error

### ISSUE THREAD

**Issue by jelbourn** [angular/material#9243]
To reproduce:
Click the "Toggle" button
http://codepen.io/jelbourn/pen/mEzrOP?editors=1010#0

The problem:
Angular sometimes uses comment elements as placeholders so that a real element doesn't have to be rendered. This means the `element` given to a `link` function will be of type `Comment`. 

[Material's decorating of `ngShow` and `ngHide` uses `getComputedStyle` on the `element`](https://github.com/angular/material/blob/master/src/components/showHide/showHide.js#L25), which fails because it is a comment.

cc @topherfangio as the last one to touch these lines

**Comment by ThomasBurleson** [comment]
@crisbeto - another blocker to be fixed asap
