### ISSUE TITLE
md-datepicker should have option to select year and month by default and date formatting.

### ISSUE THREAD

**Issue by shruti0207** [angular/material#9246]
Is there an option to open the datepicker directly to year/month instead of date view there doesn't appear to be an example of this in RC5, see uploaded image. 
And if user enters the date in number format (08052016) it gets formatted as (08/05/2016) and same entered date get selected on calendar. 

**Calendar View**

![calendra view](https://cloud.githubusercontent.com/assets/20793272/17432029/8bbd6238-5b1a-11e6-84d3-e57ea3943231.png)

**Date Format**

![date-format](https://cloud.githubusercontent.com/assets/20793272/17433004/dde3aa90-5b1f-11e6-89b9-036f7f48a694.png)

**Comment by crisbeto** [comment]
It's not in 1.1-rc.5, but it's in master and it should be in 1.1 final. You can do:

```
<md-datepicker ng-model="myDate" md-current-view="year"></md-datepicker>
```

**Comment by shruti0207** [comment]
I try parseDate and FormatDate methods on the $mdDateLocaleProvider but it change the format only when date selected from calendar, if date enter using keyboard in number format (08052016) than it not gets formatted as (08/05/2016)

**Comment by shruti0207** [comment]
I try parseDate and formatDate methods on the $mdDateLocaleProvider but it format the date when date is selected from the calendar, if date enter using keyboard in number format (08052016) it not get formatted as (08/05/2016) and if make the change in mdDatelocalProvider than the date format change every where in application, just need to change the date format in some specific filed only

**Comment by chavewain** [comment]
check this: https://plnkr.co/edit/nJyHfu?p=preview
