### ISSUE TITLE
md-datepicker does not display properly in Chrome 

### ISSUE THREAD

**Issue by JaySardhara** [angular/material#9252]
**Actual Behavior**:
 -  `What is the issue? *` 

md-datepicker display overflows in latest Chrome version. Same is displayed properly in IE 11`
 -  `What is the expected behavior?` 

Should display calendar normally

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

This is how it looks in Chrome version 52.0.2743.116 m (64-bit): 

![image](https://cloud.githubusercontent.com/assets/6151138/17450851/8cbbb052-5b17-11e6-9aea-9d400021f872.png)

This is how it looks in IE 11:

![image](https://cloud.githubusercontent.com/assets/6151138/17450908/dfca20a8-5b17-11e6-9a37-cb26c8ecb32f.png)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` 52.0.2743.116 m (64-bit) 
 -  `OS: *` Windows
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
The demo page seems fine for me on the same version of Chrome. Can you post a codepen that shows the issue?

**Comment by JaySardhara** [comment]
@crisbeto 
Resolved issue by removing <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css"> from my html.
Somehow there is some conflict while using w3.css.

Thanks for help. Posting solution so as to help others facing same.
