### ISSUE TITLE
md-progress-circular indeterminate mode iOS

### ISSUE THREAD

**Issue by daniel-lang** [angular/material#9253]
**Actual Behavior**:
 -  `What is the issue? *` `md-progress-circular` does not animate properly when in indeterminate mode
 -  `What is the expected behavior?` the animation should look like in all the other browsers

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` Just add a `md-progress-circular` to any page or visit [https://material.angularjs.org/latest/demo/progressCircular](https://material.angularjs.org/latest/demo/progressCircular) on iOS

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.1.0-rc5

**Additional Information**:
 -  `Browser Type: *` Safari - iOS
 -  `Browser Version: *`
 -  `OS: *` iOS 8.4
 -  `Stack Traces:`

**Comment by crisbeto** [comment]
Can you be a little more specific? It seems to be working fine for me on iOS 9.

**Comment by daniel-lang** [comment]
Sorry, just so we war talking about the same thing. This is what I see on iOS 8:
![giphy](https://cloud.githubusercontent.com/assets/6500514/17455048/e711d9ec-5bac-11e6-8296-fbe092e24001.gif)
![screen shot 2016-08-06 at 08 03 22](https://cloud.githubusercontent.com/assets/6500514/17455049/e713d09e-5bac-11e6-81e2-d28b53ddc92e.png)

**Comment by daniel-lang** [comment]
Thanks for the quick response!

**Comment by betorobson** [comment]
@jelbourn 
For some reason iOS wont render SVG having style:
```css
transform-origin: 25px 25px 25px;
```

A micro fix for it is change to:
```css
transform-origin: center;
```
