### ISSUE TITLE
Switch to ESLint

### ISSUE THREAD

**Issue by mgol** [angular/material#9261]
**Actual Behavior**:
-  `What is the issue? *` Currently code is linted via JSHint. JSHint is dropping options related purely to code style (a lot of them have already been dropped long ago but e.g. the `laxbreak` option that we currently use is deprecated as well) so if you ever want to validate code style, you'll have to use ESLint anyway. It doesn't make sense to use two linters when one handles it all just fine.
-  `What is the expected behavior?` The code is linted via ESLint.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` N/A
-  `Details:` N/A

**Angular Versions**: *
-  `Angular Version:` N/A
-  `Angular Material Version:` N/A

**Additional Information**:
-  `Browser Type: *` N/A
-  `Browser Version: *` N/A
-  `OS: *` N/A
-  `Stack Traces:` N/A

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

The migration should be easy since:
- JSCS isn't used (a lot of repos - like Angular 1.x - were using the JSHint+JSCS combo)
- There are only 3 JSHint options currently enabled 

If you agree this is sth that could be done, I volunteer to prepare a PR. I've done one for AngularJS and it was way more involved than is needed in this repo. :)

**Comment by DevVersion** [comment]
I think it's a good idea to switch to ESLint.

ESLint seems to be more a active repository and also looks more popular.

> At first I think we should fix all the Lint warnings (probably pair with @crisbeto - #9153). 

Regarding preparing a PR I think it would be good to run that on another Travis Mode, which runs in fast finish mode.

**Comment by mgol** [comment]
> Regarding preparing a PR I think it would be good to run that on another Travis Mode, which runs in fast finish mode.

Could you elaborate? I don't understand. :)

**Comment by DevVersion** [comment]
Sure - We currently only have a gulp task to run JSHint against the sources, so it can be only executed manually.

- It would be good to run ESLint inside of Travis as well.

To concurrently run ESLint and the normal test suite we want to have different "Modes".
> Like in https://travis-ci.org/angular/angular/builds/150683765

The `fast finish` mode for Travis indicates that the ESLint mode is optional and will not fail and block the CI.

We could skip that fast finish option right now and revisit later, because we have to fix the warnings first.
