### ISSUE TITLE
md-datepicker is not documented in the directives pane

### ISSUE THREAD

**Issue by mgol** [angular/material#9263]
**Actual Behavior**:
 -  `What is the issue? *` md-datepicker is not documented in the directives pane, it's only present in the Demo section
 -  `What is the expected behavior?` It should show up in the directives pane

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` N/A
 -  `Details:` N/A

**Angular Versions**: *
 -  `Angular Version:` N/A
 -  `Angular Material Version:` N/A

**Additional Information**:
 -  `Browser Type: *` N/A
 -  `Browser Version: *` N/A
 -  `OS: *` N/A
 -  `Stack Traces:` N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
This is fixed on master: https://material.angularjs.org/HEAD/api/directive/mdDatepicker

**Comment by mgol** [comment]
Thanks, I didn't realise I can check the `master` version. I'll remember next time.
