### ISSUE TITLE
Menu Bar: layout-row expands in size, obscuring elements

### ISSUE THREAD

**Issue by DaylightRobber** [angular/material#9268]
**Actual Behavior**:

 -  When deploying the Menu Bar, its child div with class "layout-row" expands in size during usage, blocking user interaction with html elements positioned below it.
 -   Expected: The size of the div with class "layout-row" should remain constant 

**CodePen** (or steps to reproduce the issue): 
On https://material.angularjs.org/latest/demo/menuBar:
1. Open a drop down menu
2. Find child div of md-toolbar with class "layout-row" in the dom inspector of IE
2. Select a menu item in one of the drop down menu, completing an action
4. Watch the size of the toolbar grow in the debugger of IE (this is where the graphical representation of an element's various dimensions comes in useful). The blue sidebar on the left visibly expands. 

**Angular Versions**: 
 -  `Angular Version:1.5.8`
 -  `Angular Material Version:1.1.0-rc.5`

**Additional Information**:
 -  `Browser Type: IE `
 -  `Browser Version: 11`
 -  `OS: Win7`

**Comment by ThomasBurleson** [comment]
will not fix in ngM1.x
