### ISSUE TITLE
Mobile Firefox: getY() function fails

### ISSUE THREAD

**Issue by borgdylan** [angular/material#927]
I was trying out bottom sheet in app on my nexus 7 using firefox. Nothing happens when i click on the button (things work ok on desktop firefox). I hooked up firefox adb debugging and found out that in the ```getY()``` function, ```e.changedTouches``` was undefined (a js type error). The issue roughly happens in line 2025 in the compiled js file.

**Comment by MilosStanic** [comment]
+1 with this problem. I'm experiencing this problem on mobile devices when touching elements in BottomSheet. 
When I touch an element in the BottomSheet I get error: 
Uncaught TypeError: Cannot read property '0' of undefined
in the same line of angular-material.js.
And this error fires twice for each touch. 
I hope this gets fixed soon.

**Comment by tforbus** [comment]
Having the same issue. With the fix suggested, radio buttons were only getting selected if the radio button label was clicked (not the radio button itself).

**Comment by jnv22** [comment]
@robertmesserle  Would you mind referencing the fix commit?
