### ISSUE TITLE
DatePicker to have additional expressions - modelValue and viewValue

### ISSUE THREAD

**Issue by manishbafna** [angular/material#9270]
**Actual Behavior**:
 -  `What is the issue? *`Right now, the datepicker is using provider for evaluation. In case of the timezone and other details coming from server, it will be difficult to manipulate. (In some cases, the date is coming is epoch format, sometimes, MM-DD-YYYY) . 
 -  `What is the expected behavior?`: Have additional expressions for the directive. 
ModelValue -> Expression is evaluated and stored as model value
ViewValue -> Expression is evaluated and shown in the UI. 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/zBrrvo
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.1.0 RC 5
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *` All
 -  `Browser Version: *` All
 -  `OS: *` All
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ryan-kimber** [comment]
With #9260 working, it would be great to get this as well. We're working on a project where being able to have YYYY/MM/DD on most date fields, but MMM-YY on month-only date fields would be great. It's a little confusing when you select a month but the date displayed shows the day.

**Comment by crisbeto** [comment]
Yes, the idea was to get this in after #9260.
