### ISSUE TITLE
md-subheader does not recalculate sticky position after scope update in Chrome if scrolling has already been initiated

### ISSUE THREAD

**Issue by craigivemy** [angular/material#9277]
If items are added to the view, thus resizing the md-content / section associated with an md-subheader, if the user has initiated scrolling before this change in the view, md-subheader sticks at it's originally calculated position.

If no scrolling has taken place when the height of the md-content / section changes, the md-subheader updates it's sticky position as normal.

This issue is present in Chrome, but not in Safari, and is related to / the same as #7045 , #5420 which have been closed without a fix.

Credit to [0101adm](https://github.com/0101adm) for the following CodePen which demonstrates the issue.  http://codepen.io/0101adm/pen/MKPpZw

Angular Material version: 1.1.0-rc.5
AngularJs Version: 1.5.3

Chrome version: 52.0.2743.116 (64-bit)
OS X El Capitan Version 10.11.5

**Comment by wosevision** [comment]
+1 for this issue; I'm using accordion-style action in tandem with md-list (list items that expand/collapse to reveal their contents) and the subheaders retain the vertical positioning they were initialized at when sections are expanded.

I've been looking for some kind of hack that would "reflow" the stickiness when mutations are applied, but haven't discovered the magic formula yet. Nobody else has happened upon one either I see? I feel as though adding/removing content to lists is a massively common use case, so I'm interested to see where this goes.

Specs: exact same except OS v.: 10.11.6

**Comment by craigivemy** [comment]
I've been looking too. I agree, there can't be many things more common than modifying lists, and yet this renders the whole md-subheader directive pretty useless - it totally ruins the UX. Hopefully this will be fixed soon.

**Comment by Vincent-CHARLANNE** [comment]
+1 for this update, same context, an evolutive md-content

**Comment by DevVersion** [comment]
This can be hopefully fixed after #9359 is available, and we put some extra efforts into it, to detect rectangle changes.

**Comment by DevVersion** [comment]
I will close this issue now, since #9359 already exists, and also has a primary focus on the parent independence, which means that sticky elements can also live outside of a `md-content` element.

Also the new `$mdSticky` will provide a public API to update the rectangles and position of the sticky elements (like subheader)
