### ISSUE TITLE
md-button does not hide under md-subheader

### ISSUE THREAD

**Issue by franollo** [angular/material#9278]
When I put md-button inside md-list-item it does not hide under md-subheader when I'm scrolling.

**CodePen** 
http://codepen.io/anon/pen/grkgok

**Angular Versions**: 
 -  `Angular Version: v1.5.8`
 -  `Angular Material Version: v1.1.0-rc.5`

**Comment by DevVersion** [comment]
FAB's (Floating Action Buttons) shouldn't be inside of a `md-list-item`.

Those are designed to overlay other elements and have a higher `z-index`. 
> https://material.google.com/components/buttons-floating-action-button.html
> That's why those are overlaying the subheader right now.

As a workaround for your _special_ case, you could use the following markup

```css
._md-subheader-wrapper._md-sticky-clone {
  z-index: 21;
}
```
http://codepen.io/DevVersion/pen/oLJkLJ
