### ISSUE TITLE
light-blue-dark-theme has incorrect disabled fab font color

### ISSUE THREAD

**Issue by iamjt** [angular/material#928]
v0.6.1-master-d192083

light-blue-dark-theme fab has a different font colour while in disabled mode. font colour should look more "disabled" even in a dark theme.

Incorrect:
https://dl.dropboxusercontent.com/u/2686709/incorrect.png

Correct:
https://dl.dropboxusercontent.com/u/2686709/correct.png

**Comment by rschmukler** [comment]
Fixed w/ new theming changes from `0.7.0`
