### ISSUE TITLE
Set white through md-colors?

### ISSUE THREAD

**Issue by cadilhac** [angular/material#9285]
I use md-colors to set a background color. Since md-colors also sets implicitely a text color (which is black in this case), I want to override that and set white. An inline style won't work since this is overriden by the directive. I tried md-colors={ backgroundColor:'teal-A700', color:'white'} but obviously it won't work. How can I do that?

A small note about the documentation of md-colors: it uses a property name like border-color but this doesn't work in my code. I have to use borderColor to make it work. Same for backgroundColor of course.

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/pen?template=bEGJdd
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by cadilhac** [comment]
This is not a "it doesn't work" type of question. So I have no codepen to write. This is a "can I use md-colors to set white as a color" question.

**Comment by EladBezalel** [comment]
Hey @cadilhac, this is a bit of an hack :stuck_out_tongue: 
Material Design colors doesn't have accent colors in the `grey` palette so we added our own,
such as `#000000` and `#FFFFFF` and [some others](https://github.com/angular/material/blob/master/src/core/services/theming/theme.palette.js#L333),

So that means you can use
```html
<div md-colors="{ backgroundColor:'teal-A700', color:'grey-A100' }">
```

and that will do the work for you :)

**Comment by shawmanz32na** [comment]
@EladBezalel: would this be an opportunity to improve the md-colors documentation? The md-colors demo/documentation links directly to the [official material pallettes](https://material.google.com/style/color.html#), which doesn't include the black/white accent colors that you mentioned.

I'd like to see some mention of the customized grey pallette used my md-colors.

Additionally, as @cadilhac mentioned, there's no mention that the expression provided to the md-colors directive should be converted from css's hyphen-separated style to javascript's camelCase style. Would this be something that can be added at the same time, or should we open a new issue for that?

**Comment by EladBezalel** [comment]
@shawmanz32na yes this might be a good documentation update, would you mind getting involved and submitting an issue about it and even suggest a PR with those changes?
