### ISSUE TITLE
md-select doesn't update validation when scope value is updated

### ISSUE THREAD

**Issue by AndreySyagrovskiy** [angular/material#9286]
**Actual Behavior**:
 - It doesn't update md-select validation  if it is changed value of md-select in scope . When I select value by mouse all work fine

**Angular Versions**: *
 -  `Angular Version:1.5.8`
 -  `Angular Material Version: v1.1.0-rc.5`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
Can you please provide a Codepen demo using the "new CodePen Demo" link above?

Also, are you actually using Angular 1.6? The latest released version is 1.5.8.

Lastly, you are using Material 1.1.0-RC5. Can you try against master/HEAD? We have made a lot of changes so this might already be fixed.

**Comment by AndreySyagrovskiy** [comment]
I`m sorry about version angular. I`m using  * @license AngularJS v1.5.8 
About git version: If I use npm packege "angular-material": "1.1.0-rc.5", everything must to be ok, sn`t?.
I will give you demo soon!

npm package info coment is 

/*!
 * Angular Material Design
 * https://github.com/angular/material
 * @license MIT
 * v1.1.0-rc.5
 */

**Comment by topherfangio** [comment]
@AndreySyagrovskiy We just released the final version 1.1.0 today which supersedes 1.1.0-RC5. Were you able to get it working after upgrading?

**Comment by AndreySyagrovskiy** [comment]
@topherfangio  https://github.com/stfalcon-studio/stf-angular-select I have written my own select .  I have found problem in yours. If your select does not get full list and selected element is not in loaded list (in situation when we load only ten elements) then value is not showed
