### ISSUE TITLE
problem with scroll behavior on touch devices

### ISSUE THREAD

**Issue by aszharite** [angular/material#9287]
**Actual Behavior**:
-  `Actual Behavior: *` On a tablet device ar any device with a touch screen, if the one row is bigger than the container of the virtual scroll (height) then it will jump to start/end of the row while scrolling *
-  `Expected Behavior:` Should scroll normally and not jump the user making the middle content be inaccessible

**CodePen** (or steps to reproduce the issue): *
-  Have a container that is let's say 300px and rows that are 300+ px. On a touch device, scroll and observe.

**Angular Versions**: *
-  `Angular Version:` 1.3.20
-  `Angular Material Version:` 1.1.0-rc4-master-e638c51

**Additional Information**:
-  `Browser Type: *` Safari
-  `Browser Version: *` 9.2.1
-  `OS: *` iOS 9.2.1

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by DevVersion** [comment]
As @topherfangio already indicated with an label. It is highly recommended to provide a demo.

**Comment by aszharite** [comment]
Managed to figure out that the actual problem is that my rows had varied height.
Don't really consider that this is a bug to fix but would be a nice feature to be able to use dynamic height  in the md-virtual-repeat-container items.

Here is a codepen demo http://codepen.io/aszharite/pen/PzvRxK and you can see how scrolling triggers a slight jump in rows that is annoying.

**Comment by Splaktar** [comment]
To use Virtual Repeat, all items must be the same size. Using dynamic items can only work if you can guarantee that they are all of the exact same size. Otherwise your scrolling will get out of sync. Virtual Repeat is fast because it doesn't have to calculate dynamic sizes when scrolling.
