### ISSUE TITLE
Scroll support for <md-tabs> in RTL languages

### ISSUE THREAD

**Issue by mosiruane123** [angular/material#9292]
**Actual Behavior**:
Scroll arrows are inverted and scrolling on tabs not functioning
-  `What is the issue? *`
  Scroll support for <md-tabs> in RTL not working
-  `What is the expected behavior?`
  Scroll arrows in correct position and supporting scroll on tabs

**CodePen** (or steps to reproduce the issue): *
Change page direction which includes <md-tab> to rtl (dir="rtl")
-  `CodePen Demo which shows your issue:`
  http://codepen.io/anon/pen/oLJKNr
-  `Details:`
  open up developer tools/ Inspect element (F12) to narrow screen size.
  Adjust until the tabs are truncated and the next/previous arrows appear
  Notice the arrows are inverted and the scroll left/right no longer works
  Is there a fix for this issue?

**Angular Versions**: *
-  `Angular Version:`
  v1.5.0
-  `Angular Material Version:`
  v1.1.0-rc4

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *`52.0.2743.82 m
-  `OS: *` Windows
-  `Stack Traces:` ---

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by topherfangio** [comment]
Let me look into this a bit. In *theory*, this should be a simple fix, but I have not dealt with the RTL code in tabs before so I'm not sure exactly how it works.

**Comment by mosiruane123** [comment]
Ah brilliant! Great stuff, that solved the issue. All working now.

**Comment by Avishaidev** [comment]
Please add an code example that you use with rtl support that i can use it too.
Thanks

**Comment by mosiruane123** [comment]
@Avishaidev 

I just made the new changes to the files found in topherfangio's commit. 
https://github.com/profoundry-us/material/commit/e9c91c48e866aee356ef3771e95b4e69deec47a8

tabs.scss and tabsController.js

I just wanted to confirm that it was working, which it was. I reverted the changes on my own files as I will wait until the official build containing the fix is released.

Thanks,
Mossy

**Comment by Avishaidev** [comment]
@mosiruane123 

Thanks for your replay.
I already change my angular-matrial.js file in my project to support rtl.
thanks any way

**Comment by NaNgets** [comment]
This issue is really important to me but it doesn't get fixed, is there any ETA on it to work?

The next\prev buttons aren't working well and the swipes are to the wrong sides.

Is it worthwhile making a PR for it? will it be considered?

**Comment by djidel** [comment]
This is a working codepen demo for this issue: http://codepen.io/djidel/pen/NpMpmY
Are there any workarounds?

**Comment by areeb5** [comment]
![11](https://user-images.githubusercontent.com/5106831/32892447-15640fa2-caf8-11e7-8399-1bcb1441a4f1.JPG)
i have tried  code of  @topherfangio .  embed that in my application, updated tabs.scss & tabController.js 
but still im having the same issue that in RTL, tabs are disabled and not working. 
my angular-material library version is **1.1.4**
Kindly help me in this issue at earliest.
@Avishaidev  what changes you have done in your library to support RTL ?
