### ISSUE TITLE
mdGestures: swipe up and down

### ISSUE THREAD

**Issue by MathiasLM** [angular/material#930]
Currently md-swipe-left/right exists by implementing hammerjs' gestures. I see no reason not to include up and down as well. :)

**Comment by jeffthompson1971** [comment]
Has swipe up and down been implemented?  Sorry I'm not following what the resolution was here.  I don't see it in the docs.

**Comment by gpopovic** [comment]
+1

**Comment by mackelito** [comment]
+1
