### ISSUE TITLE
Datepicker range

### ISSUE THREAD

**Issue by Vova2805** [angular/material#9304]
Why datepicker range is not implemented? I think it'll be widely  used. For examples filters by date. Or are there some way to get it from a simple datepicker?

**Comment by crisbeto** [comment]
I think @jelbourn mentioned that somebody was trying to implement this, but I'm not sure what happened. Otherwise you can always have two "start" and "end" datepickers.

**Comment by jelbourn** [comment]
We did have a contributor who started work on it, but that's been dropped for Angular Material 1 (since it's pretty straightforward to have a separate start and end date).
