### ISSUE TITLE
panel: remove deprecated methods: addClass, removeClass, and toggleClass

### ISSUE THREAD

**Issue by bradrich** [angular/material#9310]
Full deprecation of `addClass`, `removeClass`, and `toggleClass` is scheduled for the Material 1.2.0 release.
During that release, the current functionality of those methods will be removed and replace with an error.

**Comment by Splaktar** [comment]
The decision, rational, and explanation of why this needs to happen can be found here:
https://github.com/angular/material/pull/9231#issuecomment-237907614
