### ISSUE TITLE
md-dialog allows user to interact with page behind the dialog

### ISSUE THREAD

**Issue by johnjesse** [angular/material#9311]
**Actual Behavior**:
When the dialog is on the screen you can click on the body by selecting the background. if you tab then everything works, you are focused on the dialog. However, if you are focused on the body and then you shift+tab you go backwards into the page and are not redirected to the dialog. This is unexpected behaviour as ytou should not be able to focus away from the dialog whilst it is up.

Furthermore shift+tab does not appear to loop from top to bottom in the dialog. It's expected behaviour is to be the inverse of tab - which loops from bottom to top.

**CodePen** (or steps to reproduce the issue): 
repro steps, 
1) have a page with something focusable on, e.g. some buttons, 
2) raise a dialog
3) click on the dialog backgorund
4) shift-tab - this will take focus to the elements on the page behind the dialog

**Angular Versions**: 
 -  Angular Version: v1.5.5
 -  Angular Material Version: v1.1.0-rc.5

**Additional Information**:
 -  Browser Type: chrome
 -  Browser Version: 52.0.2743.116 m

**Comment by ThomasBurleson** [comment]
Closing this issue due to missing CodePen.
