### ISSUE TITLE
CSS attribute selectors in 1.0.6+ (IE performance degradation)

### ISSUE THREAD

**Issue by jvmccarthy** [angular/material#9312]
**Actual Behavior**:
 -  `What is the issue?`
  In angular-material 1.0.6, CSS attribute selectors were added to the produced CSS in addition to class selectors. Attribute selectors were removed in [0.11.0-rc1](https://github.com/angular/material/blob/master/CHANGELOG.md#0110-rc1-2015-09-01) mainly because of IE performance concerns. I recently upgraded from 1.0.5 to 1.0.9 and encountered noticeable performance impacts in IE11 and Edge.

  The difference is easily observable by looking at [v1.0.5 angular-material.css](https://github.com/angular/bower-material/blob/v1.0.5/angular-material.css) without attribute selectors (search for `[layout-fill]`, for example) at ~14K lines and [v1.0.6 angular-material.css](https://github.com/angular/bower-material/blob/v1.0.6/angular-material.css) with attribute selectors at ~23K lines. 

 -  `What is the expected behavior?`
  Only class selectors for layout in `angular-material.css` and attribute selectors removed. **Since this has a performance impact on 1.0.x, I would greatly appreciate a patch release of 1.0.x to address this issue.** The attribute selectors are still present in [1.0.9](https://github.com/angular/bower-material/blob/v1.0.9/angular-material.css) but are absent from [1.1.0-rc4](https://github.com/angular/bower-material/blob/v1.1.0-rc4/angular-material.css). At this time, I can't upgrade to 1.1.0 because of breaking changes and because it is still in release candidates. My other option is to roll back to 1.0.5, but there are a number of bug fixes and improvements in 1.0.6-1.0.9 that I would have to give up.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/jvmccarthy/pen/vKbrYa
 -  `Details:`
  Inspect top div with `layout-fill` attribute. Note class selector `.layout-fill` from `angular-material.css:15386` and attribute selector `[layout-fill]` from `angular-material.css:6411` as well as selectors for `layout` and `layout="column"` styles.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.0.6, 1.0.7, 1.0.8, 1.0.9

**Additional Information**:
 -  `Browser Type: *` Internet Explorer, Edge
 -  `Browser Version: *` IE 11.0.14393.0, Edge 38.14393.0.0
 -  `OS: *` Windows 10
 -  `Stack Traces:`

Thank you for your continued efforts on angular-material and for your consideration.

**Comment by j3ski** [comment]
I was having the same issue (temp. fixed it by removing those selectors in my build step - thanks [filter css](https://github.com/bezoerb/filter-css)), but today I've upgraded to 1.1.0 and it seems to be fixed.

**Comment by ThomasBurleson** [comment]
Please upgrade to v1.1.0.
