### ISSUE TITLE
Scrolled md-virtual-repeat doesn't rerender when the items change

### ISSUE THREAD

**Issue by bsk26** [angular/material#9315]
**Actual Behavior**:
 -  `What is the issue?`
Scrolled md-virtual-repeat doesn't rerender when the items change for some configurations of the scroll and the item lists. Occurs when it enters this statement,
https://github.com/angular/material/blame/master/src/components/virtualRepeat/virtual-repeater.js#L700
but the indexes don't change in updateIndexes so this condition fails,
https://github.com/angular/material/blame/master/src/components/virtualRepeat/virtual-repeater.js#L659
And it doesn't reenter the update method and rerender the list with the new items.
 -  `What is the expected behavior?`
Rerenders to show the new items.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/benkraft/pen/VjgJNQ
 -  `Details:`
Scroll the list down just a couple of pixels, perhaps so the top border is hidden but all the text on the label "black" is still visible. Click "Switch to new color list". Verify that the list did not switch items. You can reload and click the button without scrolling and it indeed should switch to the correct list.

**Angular Versions**: *
 -  `Angular Version:`  
1.5
 -  `Angular Material Version:`
 v1.0.0-rc5 (and earlier)

**Additional Information**:
 -  `Browser Type: *` 
Chrome
 -  `Browser Version: *`
51.0.2704.103
 -  `OS: *`
OS X 10.11.6
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
@crisbeto - can you investigate as P1 priority ? Thx.
