### ISSUE TITLE
div with flex is causing other divs to shrink when it shouldn't in 1.1.0-RC.5

### ISSUE THREAD

**Issue by Liron-K** [angular/material#9316]
**Actual Behavior**:
 -  `What is the issue? *`
I just tried to update to rc.5, and some of my flex controls are getting messed up.

in particular, I have a view with the following general structure:
```
div(layout="column")
  div(layout="column")
    ... some header stuff
  div(flex)
    ... some stuff which should fit between the top and bottom div
  div(layout="column)
    .. some footer stuff
```

What is happening is that the middle div is getting created too large and shrinking the top and bottom divs more than they should.

When I went back to rc4, this behaves as expected.
 -  `What is the expected behavior?`
The div with flex should fill the space but not cause the other divs to shrink.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/anon/pen/KrEVAa
 -  `Details:`
Notice how parts of the header and footer are not visible.

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`
1.1.0-RC.5

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`52.0.2743.116 (64-bit)
 -  `OS: *` OSX
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
This is what I'm seeing on that same version of Chrome on OS X:

<img width="205" alt="screen shot 2016-08-16 at 12 41 04 pm" src="https://cloud.githubusercontent.com/assets/54370/17709461/cba19c06-63ae-11e6-83f3-a4f117126b76.png">

Is this not correct?

**Comment by Liron-K** [comment]
I only see one line in the header and the footer. I'll try send a
screenshot later. Try making the view shorter.

**Comment by Liron-K** [comment]
On all of the below, I would expect the entire header and footer to be visible and the middle area should scale down to fit.

Small | Medium | Large
------------ | ------------- | -------------
<img width="212" alt="screen shot 2016-08-17 at 10 27 59 am" src="https://cloud.githubusercontent.com/assets/2301443/17727991/79fce204-6465-11e6-81f3-2d7386f344c8.png"> | <img width="215" alt="screen shot 2016-08-17 at 10 28 31 am" src="https://cloud.githubusercontent.com/assets/2301443/17727992/79ff29d8-6465-11e6-935a-b5a64f5df0b0.png"> | <img width="227" alt="screen shot 2016-08-17 at 10 28 54 am" src="https://cloud.githubusercontent.com/assets/2301443/17727990/79fb41b0-6465-11e6-95eb-30dbbf2a404d.png">

**Comment by topherfangio** [comment]
Sorry for the delayed response.

So, the issue is that your red `<div>`s are using `layout="column"`. This forces a flex display which uses the default/browser-defined flex value of `flex: 0 1 auto` which specifically allows the element to shrink.

Just remove the `layout="column"` from them so they are `display: block` and it should work like you expect.

Let me know if you have more questions and I can reopen.
