### ISSUE TITLE
md-virtual-repeat and one-time binding causes scroll render bug

### ISSUE THREAD

**Issue by daraosn** [angular/material#9317]
**Actual Behavior**:
 -  `What is the issue? *`
Yesterday I discovered that when using `md-virtual-repeat` and one-time binding variables in templates, the scroll order runs out of control. Here an example of the bad behaviour when scrolling fast:
http://plnkr.co/edit/BkK2swCQKdoKfkvdfp0y?p=preview

 -  `What is the expected behavior?`
This is expected to happen:
http://plnkr.co/edit/RsX9RoPQQevmW8lpFhYc?p=preview

**CodePen** (or steps to reproduce the issue): *
Included above**

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` master

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` Version 52.0.2743.116 (64-bit)
 -  `OS: *` OSX
 -  `Stack Traces:` N/A

**Comment by demsey2** [comment]
I have the same problem inside md-tooltip, my example here

http://codepen.io/anon/pen/zBbyjd

all other details the same, I also tried with Windows browsers

**Comment by crisbeto** [comment]
This has been discussed before (https://github.com/angular/material/issues/9126) and [is mentioned in the docs](https://material.angularjs.org/HEAD/api/directive/mdVirtualRepeatContainer#common-issues). The bottom line is that this is sort of the way it's "supposed" to work. The point of virtual repeat isn't to replace ng-repeat completely, but to be an alternative in performance-sensitive situations. The way it works is that it recycles elements and it updates their associated scope as the user scrolls through the list. When you use a one-time binding, the elements get interpolated once and then stops watching for changes, which causes the list to appear broken. 

A potential solution could be to recreate and recompile each of the elements, but this will most likely be slow and defeat the whole purpose of the virtual repeater.
