### ISSUE TITLE
When md-autocomplete is removed (by ng-if) the md-scroll-mask is not removed.

### ISSUE THREAD

**Issue by leibale** [angular/material#9318]
When `md-autocomplete` is removed (by `ng-if`) the `md-scroll-mask` is not removed.
@cah-alexsukhodolsky tried to fix it in 042086f34f4d9bb54228dbc4968b520228f73de0, but he didn't cover the scenario when `md-autocomplete` is removed immediately after an item is chosen.
The `$mdUtil.nextTick` doesn't call the `$mdUtil.enableScrolling` (because the `$scope` is destroyed) and the `cleanup` function will not remove the `md-scroll-mask` (because the `ctrl.hidden` is true).

[CodePen Demo](http://codepen.io/leibale/pen/kXqbvR)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0-rc.5

**Comment by leibale** [comment]
happens also in version 1.1.0

**Comment by DevVersion** [comment]
We know - We didn't merge it yet. It's also not a super high priority so it didn't get into `1.1.0`

**Comment by leibale** [comment]
I know that you didn't merged my pull request (by the way, it will be great if you can do it soon, it's only a few lines).. I just make sure that it didn't fix in the commits that have pushed between version 1.1.0-rc.5 to 1.1.0 (if there is any).

Thanks :)

**Comment by DevVersion** [comment]
It's not about the lines, `master` was currently locked for the `1.1.0` release, and you PR is just one day old :) 

I will take a look at it as soon as possible.

**Comment by leibale** [comment]
It's a production bug in my project, so i have to run `gulp build` and copy the files from the `dist` folder to my project and add them to my git repository (instead of download them using bower), it's really ugly..
The first think i wanna do is to remove those files from my project..

Thanks for your time
