### ISSUE TITLE
$mdDialog position should be "fixed", not "absolute"

### ISSUE THREAD

**Issue by stefan-dimitrov** [angular/material#932]
When the body overflows and is scrolled the dialog moves with the content.
For example, we have the content at topmost position and everything looks good:
![screenshot from 2014-12-12 16 43 17](https://cloud.githubusercontent.com/assets/6047637/5413333/3c4e196c-821e-11e4-8d28-98507cd1cd2a.png)

... until we scroll down:
![screenshot from 2014-12-12 16 43 44](https://cloud.githubusercontent.com/assets/6047637/5413334/3eb2b636-821e-11e4-989b-a57635934d28.png)

**Comment by davideoliveri** [comment]
This doesn't solve the problem for me. 
Moreover, if I click on a button to open a dialog AFTER scrolling down the page, the dialog opens at the top of the page, it scrolls to the top but not entirely. 
![schermata 01-2457025 alle 17 34 04](https://cloud.githubusercontent.com/assets/2866936/5598006/9c4ce5ea-92a5-11e4-98bd-3c106f670585.png)

Also, I wonder if setting "layout" to every parent could really be a solution. Which still doesn't solve the problem to me.

**Comment by SebiH** [comment]
Can we reopen this issue? This is not solved for me, either.

In addition, this should be linked to #908

**Comment by heikkilamarko** [comment]
The following css worked for me:

```
md-backdrop.md-opaque.md-default-theme,
.md-dialog-container {
  position:fixed;
}
```

**Comment by ThomasBurleson** [comment]
@SebiH @davideoliveri - please provide plunkr or codepens so we can analyse the issue for your configuration.

**Comment by SebiH** [comment]
@ThomasBurleson Taken (and updated) from #908: http://plnkr.co/edit/FmBGZ3G0Y71vh0z7Ffrm?p=preview

**Comment by davideoliveri** [comment]
I was cleaning the above plunker adding the "md-actions" class and I found it doesn't lock the scroll anymore. Nonetheless it works weirdly. 
http://plnkr.co/edit/zizcq45x9D6r79ih6mMj?p=preview

**Comment by zilions** [comment]
Was also having this issue. Added a `layout` to the `body` like @epelc suggested and everything is working perfectly fine now. To whoever comes across this problem, just make sure that all parents of your `md-content` have a `layout="column"` or `layout="row"`.

**Comment by epelc** [comment]
@zilions be careful. `layout="rowOrColumn"` attributes on the `body` tag are dangerous in some situations and no longer recommended.

Try to get it working without the `layout` directly on the body if you can. My advice about the parents going up to `body` still stands though.

**Comment by zilions** [comment]
@epelc can you suggest a way to achieve this without `layout` on the `body`? Tried quite a few things, and `layout` was the only thing that fixed this issue for me.

**Comment by epelc** [comment]
@zilions `height: 100%; min-height:100%;` should work

On Sun, Mar 13, 2016 at 11:44 PM, zilions <notifications@github.com> wrote:

> @epelc <https://github.com/epelc> can you suggest a way to achieve this
> without layout on the body? Tried quite a few things, and layout was the
> only thing that fixed this issue for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/932#issuecomment-196124656>.
>



-- 
Thank you,
Ed Pelc

**Comment by zilions** [comment]
@epelc No luck. Although it does work if I add `display:flex` along with your styles. Is that a dodgy workaround?

**Comment by epelc** [comment]
Maybe? If it works it works though.

I'd just test it in the different browsers to make sure it's not collapsing
or anything weird. You may also run into issues with toasts and dialogs so
test them.

On Sun, Mar 13, 2016 at 11:54 PM, zilions <notifications@github.com> wrote:

> @epelc <https://github.com/epelc> No luck. Although it does work if I add
> display:flex along with your styles. Is that a dodgy workaround?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/932#issuecomment-196128447>.
>



-- 
Thank you,
Ed Pelc

**Comment by zilions** [comment]
@epelc After a ton of testing, this method seems like the wrong path to go down. By having `md-content` as the scrolling element within the application instead of the `body` tag, most mobile devices (especially iOS) won't scroll to the top of the page when the status bar is tapped on. This removes some native functionality for the user on iOS devices since most assume they can scroll to the top with this function.

I haven't looked into any code, although it seems to be like the `md-dialog` uses the scroll top of the `md-content` to determine where to place it. Is it possible to use `body` instead?

**Comment by zuspan** [comment]
I'm not sure this is a true fix, but I was having this same issue. I added this to my css and it seems to solve the problem:
`body {
  overflow-x: visible;
}`

**Comment by AviEt** [comment]
Same problem happens to me. I tried all the solutions here and nothing worked for me. At the end I changed angular-material.min.css. I searched md-backdrop and changed the position to fixed and now it works correctly.

**Comment by sinoohe** [comment]
Same problem here!! it took 4 hours working on it and still doesn't work.
The solution that I got is that I scroll manually to top of the page before calling $mdDialog
      $anchorScroll.yOffset=0;
      $anchorScroll();

I tried every solution that is here, not working. I think maybe somethings wrong with angular material design.

**Comment by opavader** [comment]
same issues with me as well, making `position:fixed` messes the full-screen mode for small screens

**Comment by GavinPalmer1984** [comment]
.md-dialog-container {
    width: 100%;
    height: 100%;
    top: inherit !important;
    bottom: 0px;
    left: 0px;
    position: fixed;
}
