### ISSUE TITLE
mdContent: Support hue colors, like md-hue-2.

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#9322]
**Actual Behavior**:
When I add `class="md-hue-2"` to an md-content, the color is not applied.

**CodePen**:
http://codepen.io/erincoughlan/pen/bZkWvR
Should be light grey instead of dark grey.

**Angular Versions**:
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.1

**Comment by clshortfuse** [comment]
Did you notice your typo in the codepen? 

```<md-content class-"md-hue-2">``` instead of ```<md-content class="md-hue-2">```

**Comment by ErinCoughlan** [comment]
Didn't notice the typo. I'll have to investigate more of why this didn't work in the original code. (There's no typo in that file.)

Basically, md-hue-2 was added as a class, but always evaluated to white as opposed to the grey.

I'll try to get a repro tomorrow for this.

**Comment by Soren234** [comment]
class= not class-

<md-content class="md-hue-2">

**Comment by ErinCoughlan** [comment]
I'll close this bug and open a new one when I figure out why the themes were always evaluated to white even though the class was applied.
