### ISSUE TITLE
mdGridList:  Implement new md-gridlist component

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#933]
#### Overview 

A grid list is best suited to presenting a homogenous data type, typically images, and is optimized for visual comprehension and differentiating between like data types.

![](https://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7YTU2ekJPMU80MVU/components_grids_usage1.png)

See the Material Design Specification for Details:  [Gridlist Specs](https://www.google.com/design/spec/components/grids.html#grids-usage)

The developer will need to implement an Angular Material version that conforms to the functionality and UX defined in the Design specification [above]. 

> Developers should use existing Angular Material components and coding patterns as guides for their own implementation. Shell component assets are available for quick starts [see Below].

#### Important Considerations

*  Consider a `md-gridlist-item` to support needs of tile header and footers, plan to support the **primary** and **secondary** actions specified in the Design docs.
  *  Use css to define the dimensions of each md-gridlist-item.
*  Consider need for `md-image` for image tiles
*  Consider image background loading, promise-based load indicator, image-loaded caching, and transforms for scaling; may be part of functionality associated within an `md-image` component.

```html
<md-gridlist>
   <md-gridlist-item>
     <!-- 
            This is a tile that supports ideas of headers and footers;
            where images have precedence over text.
      -->
     <md-image />
  </md-gridlist-item>
</md-gridlist>
```

*  Static and dynamic (using ng-repeat) usages should be considered.
*  Questions of ripple inks and activity indicators should be considered.

> The component implementation may be dependent upon the `md-icon` rewrite and availability.

**Comment by shyndman** [comment]
Thanks Andrew. That is a good start.

**Comment by ilanbiala** [comment]
@ajoslin I like the implementation. It would be nice to set a min/max number of items and just let the %s work themselves out like with flex.

**Comment by ajoslin** [comment]
Can you set a number of items per row with a flex property that I don't
know of?

Or perhaps there's a different approach I haven't thought of yet..

**Comment by ilanbiala** [comment]
@ajoslin It would probably require some javascript. If the mdGridList will require some JS for styles, I'll see if I can add something in.

**Comment by ajoslin** [comment]
The bad thing about using js for layout is that it's almost impossible to know when you need to recalculate the layout, in every situation. The container could resize without the window resizing, or get a margin added to it, or anything.

**Comment by ilanbiala** [comment]
@ajoslin right, I'll look around any try to come up with a css-based solution.

**Comment by ilanbiala** [comment]
Will doing anything with `min-width`/`max-width` in the media queries work? Setting that through JS would be fine, but I'm not finding a way to get the items to scale to fit the row because they are all equal height and width. Does mdGridList need to be square items?

**Comment by shyndman** [comment]
I was thinking about taking a similar approach to how the project approaches responsive layout. Something along the lines of <md-grid-list cols-{sm,md,lg}="n"> and a fallback "cols" attribute.

@ilanbiala Rectangular items are fine.

**Comment by ilanbiala** [comment]
@shyndman if rectangular items are fine, then we can remove the `:before` rules, and probably get something to work with `min-width` + `max-width`? I'm trying to with [this pen](http://codepen.io/ilanbiala/pen/JobMmV?editors=010), but some alignment issues and such. Do you guys use some sort of helper for setting media queries through javascript?

**Comment by ilanbiala** [comment]
@shyndman just by switching from `flex-grow` to `flex`, I fixed the alignment issues. Only thing to fix now is when they are not fully expanded and not dynamically changing within the same media query..

**Comment by ilanbiala** [comment]
Not sure if [this article](https://grack.com/blog/2015/01/09/abusing-css3-selectors/) helps us at all since we are using flexbox, but still.

**Comment by marcysutton** [comment]
@shyndman per our accessibility discussion and having primary/secondary actions as sibling elements rather than a parent/child relationship, I did a little markup demo. This also applies to `md-card`. http://codepen.io/marcysutton/pen/VYpjQz

**Comment by shyndman** [comment]
Looks great. Thanks Marcy.

I have another question. Is it appropriate to use header and footer inside the md-grid-tile element? I thought the tiles might be considered sectioning roots, but I'm not sure.

**Comment by shyndman** [comment]
And if they are sectioning roots, can I annotate them to that effect?

**Comment by marcysutton** [comment]
From what I just read, for them to be contained in valid sectioning roots `md-grid-tile` might need to be replaced by a `<section>` or `<figure>` element. No one uses the HTML5 heading algorithm, so h1-h6 headings shouldn't start over. But header and footer look ok to use! http://html5doctor.com/outlines/

**Comment by shyndman** [comment]
Is there a way that I can indicate to a screenreader that an md-grid-tile is equivalent to a section?

**Comment by marcysutton** [comment]
I don't think so, it's an abstract role that isn't meant to be used: http://www.w3.org/TR/wai-aria/roles#section. There is `gridcell`, but I think that's more for tables. I think putting the actual `<section>` or `<figure>` tags will be the easiest way.

**Comment by kevinSuttle** [comment]
After perusing this thread, I feel like I misread what you were asking @marcysutton. Hoping @SteveFaulkner or @PatrickLauke will chime in.

**Comment by stevefaulkner** [comment]
Suggestion: 
grid-list as the name suggest is a list, thus role=list
grid-item role=listitem
use figure for content container in each grid-item and figcaption to caption/title content
example forked from @marcysutton http://codepen.io/stevef/pen/zxZZVj

**Comment by shyndman** [comment]
Works for me. @marcysutton, that sound good to you?

**Comment by ThomasBurleson** [comment]
@shyndman - this approach suggest we provide some syntactic sugar with transclusions and directives. Let's discuss this offline.

**Comment by marcysutton** [comment]
Yep, that works! We just have to be sure `<md-grid-item>` is separate from `<figure>` so the two roles work independently.

**Comment by ThomasBurleson** [comment]
@marcysutton - what do you mean. can you provide an example ?

**Comment by marcysutton** [comment]
I mean that we can't put role="listitem" on the `<figure>` element. The markup would look like this:
```
<md-grid-list role="list">
    <md-grid-item role="listitem">
       <figure>
          <figcaption></figcaption>
       </figure>
   </md-grid-item>
</md-grid-list>
```

**Comment by ilanbiala** [comment]
Any progress on this?

**Comment by IDontEatSoap** [comment]
Wrapping the md-grid-tile-footer in a figcaption container prevents flexbox to work as expected.

With the current implementation, it's impossible to align using flex row and space-between.

I suggest removing the figcaption wrapper - it just adds complexity and prevents child elements from aligning correctly inside the footer.

![image](https://cloud.githubusercontent.com/assets/7333418/6540681/8540923c-c4f7-11e4-86e7-9ff55630095b.png)

**Comment by marcysutton** [comment]
`figcaption` is there for semantic reasons, so it should not be removed. Can you provide a Plunker or Codepen with your implementation so we can debug the CSS?

**Comment by samueltcsantos** [comment]
Angular material grid-list is complicated to use and understand. Bootstrap grid system still is more easy to understand.
