### ISSUE TITLE
Typeahead doesn't filter and highlight while looking for text in the middle

### ISSUE THREAD

**Issue by mohanskumar** [angular/material#9330]
**Actual Behavior**: Filters only starting with
 -  `What is the issue? *` Doesn't filter and highlight using contains
 -  `What is the expected behavior?` It should filter and highlight using contains text rather than starting with

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.3
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`52
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is not a valid issue. Please resubmit with a fulfilled issue template.
