### ISSUE TITLE
md-autocomplete: doesn't show items on focus with md-min-length = "0"

### ISSUE THREAD

**Issue by MatiasKiuru** [angular/material#9331]
**Actual Behavior**:
 -  `What is the issue? *`
When md-autocomplete is clicked (focused) it won't display items even though md-min-length is set to 0
 -  `What is the expected behavior?`
When md-autocomplete is clicked (focused) it should display items if md-min-length = "0"

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
This bug can be seen in the "Custom Template" demo: https://material.angularjs.org/1.1.0/demo/autocomplete
. Clicking the "Pick an Angular Repository" does nothing.
 -  `Details:`
It worked correctly in 1.1-rc5.
Also, if you type one letter and then remove the letter, it starts working as expected.

**Angular Versions**: *
 -  `Angular Version:`
1.5.x
 -  `Angular Material Version:`
1.1.0

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
Version 52.0.2743.116 (64-bit)
 -  `OS: *`
Fedora 23
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
That's a known issue. We figured out, that the way we open the dropdown on focus was kind of "hacky". And the issue came up by changing the `searchText`'s default value from `null` to an `empty string`

> See https://github.com/angular/material/pull/9291
> Tracking with #9283
