### ISSUE TITLE
Sidenav: follow dynamic theme background color with md-content - Question

### ISSUE THREAD

**Issue by Soren234** [angular/material#9332]
**Actual Behavior**:
 -  `What is the issue? 

When changing background color to dark() sidenav follows own color scheme:
md-sidenav.md-"name"-theme, md-sidenav.md-"name"-theme md-content

I am able to do this manually with css but when changing theme, my manual css solution does not follow changes.

 -  `What is the expected behavior?`

Is its possible to follow: 
md-content.md-"name"-theme instead? 

I'm sure this is a working feature with sidenav's own background, but i would like to override this.

**CodePen** (or steps to reproduce the issue): 
I was not able to fork a codepen but i will provide screenshots:

[Hard to see "Pickdirection / Flowdirection" with sidenav background](http://i.imgur.com/OYiQgWT.png)

[Easy to see "Pickdirection / Flowdirection" with md-content.md-"name"-theme which follows theme changes.](http://i.imgur.com/kkuk8qe.png) 

Last picture is the result i would like in sidenav.

**Angular Versions**: 
 -  `Angular Version:` 1.5.0
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: Chrome
 -  `Browser Version: 52.0.2743.116
 -  `OS: Windows 10
 -  `Stack Traces:`

**Comment by ThomasBurleson** [comment]
This will not be supported.
