### ISSUE TITLE
md-select: md-no-asterisk not working

### ISSUE THREAD

**Issue by binzma** [angular/material#9339]
**Actual Behavior**:
 -  Having an md-select with the required attribute and a placeholder attribute. 
 -  I would expect to disable the appended asterisk on the placeholder with the md-no-asterisk attribute. But this does not work, the asterisk is appended.

**CodePen** (or steps to reproduce the issue): See behavior description.
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: 1.1.0`

**Additional Information**:
 -  `Browser Type: Google Chrome`
 -  `Browser Version: 52`
 -  `OS: Windows 10`
 -  `Stack Traces:`

**Comment by topherfangio** [comment]
Indeed; I am working on a fix right now.
