### ISSUE TITLE
mdSelect: select label floats after menu is closed

### ISSUE THREAD

**Issue by mckenzielong** [angular/material#9343]
This might be an intended change -- apologies if it is!
**Actual Behavior**:
 -  `What is the issue? *` After opening the select and opting not to choose any option (clicking outside) the md-select will remain focused with the label floating until another click even occurs 
 -  `What is the expected behavior?` See 1.1.0rc4 behavior -- the element is still focused, but the floating label does not float.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/mckenzielong/pen/ZOkGmr
 -  `Details:` click on the menu and don't select any option.  Click outside to close the select menu. The label will still float.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Opera / Chrome
 -  `Browser Version: *` 39 / 52
 -  `OS: *` Windows 7 64bit
 -  `Stack Traces:` N/A

**Comment by topherfangio** [comment]
The new behavior is intentional as the first click outside closes the menu, and the second click actually blurs the select. Since the element still has focus after the first click, we maintain the floating label so users know that they can use keyboard interaction.

That said, perhaps clicking or hitting escape should also blur the component?

@EladBezalel @ErinCoughlan Thoughts?

**Comment by topherfangio** [comment]
Comment from @jelbourn via Slack:

>My understanding is that it should just close it
> For a screen reader user, you want the focus to stay on the trigger
> Otherwise they get dumped back to the document.body
> Which is super annoying

I agree with this. I guess the only potential change we **could** make is for mouse users, we might automatically blur it as well, but we **cannot** do this for touch as some touch users might still be using accessibility devices.

**Comment by ErinCoughlan** [comment]
I agree with @jelbourn. I'm also cautious about having different behavior between keyboard and mouse users and also anyone on mobile. It makes it harder to track down future bugs and makes the solutions between the platforms diverge.

**Comment by topherfangio** [comment]
Ok, cool. I'm going to close this as "works as expected".

Thanks!
