### ISSUE TITLE
Seekable md-progress-bar

### ISSUE THREAD

**Issue by alexwohlbruck** [angular/material#9346]
**Actual Behavior**:
 -  `What is the issue? Need seek functionality in md-progress-bar
 -  `What is the expected behavior? Click anywhere on the progress bar to update it's value

**Angular Versions**: *
 -  `Angular Version:  Any
 -  `Angular Material Version: 1.1.0

**Additional Information**:
 -  `Browser Type: Any
 -  `Browser Version: Any
 -  `OS: Any

----

There should a drag handle similar to the one used in md-slider, that can be used to update the value of the progress bar. This would be used for media playback.

**Comment by crisbeto** [comment]
I believe that this is the use case for `md-slider`.

**Comment by ThomasBurleson** [comment]
@crisbeto - agreed. Closing as will-not-fix.
