### ISSUE TITLE
nav-bar: enhance to support icon buttons and side/bottom positioning

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#9350]
NavBar should be enhanced to support icon buttons, bottom layouts, and side layout:

![screen shot 2016-08-19 at 6 16 42 am](https://cloud.githubusercontent.com/assets/210413/17808230/a20d3f58-65d4-11e6-96b2-7692d825286a.png)

@see Material Design:
-  https://material.google.com/components/bottom-navigation.html#
-  https://material.google.com/patterns/navigation.html#navigation-patterns

**Comment by Splaktar** [comment]
This would be really nice, unfortunately we don't have the resources to add any significant enhancements like this.
