### ISSUE TITLE
checkbox. Release 1.1.0-rc.5. Chrome v.52. Label is not centered

### ISSUE THREAD

**Issue by vladimir-barsuchenko** [angular/material#9351]
I use your latest Angular Material Release 1.1.0-rc.5.
And your official codepen. 
**Windows 10. Chrome Version 52.0.2743.116 m**

When I resize a window or simply checkbox parent container. Label position is calculated wrong.
It seems like the trouble is in fractional `numbers`. And Chrome has issues with it.
Because if I increase width of checkbox container in 1px alignment is perfect.

**I have no issues with latest Firefox.**

```
md-checkbox.md-checked ._md-icon:after {
    box-sizing: border-box;
    -webkit-transform: rotate(45deg);
    transform: rotate(45deg);
    position: absolute;
    left: 6.67px;
    top: 2.22px;
    display: table;
    width: 6.67px;
    height: 13.33px;
    border-width: 2px;
    border-style: solid;
    border-top: 0;
    border-left: 0;
    content: '';
}
```

![capture](https://cloud.githubusercontent.com/assets/10091564/17810524/5b0e2d72-6626-11e6-8a0c-0d73fd00f796.PNG)

**Comment by clshortfuse** [comment]
There won't be any fractional numbers when we change checkbox's size to 18px in #8713. Currently, it's 20px which doesn't divide into whole numbers.

**Comment by ThomasBurleson** [comment]
@clshortfuse - what is the PR #?

**Comment by clshortfuse** [comment]
@ThomasBurleson Sorry, was embedded in the text:

PR: https://github.com/angular/material/pull/8713
