### ISSUE TITLE
docs: some links leads to 404

### ISSUE THREAD

**Issue by U-like** [angular/material#9352]
There is some links leading to 404 on 1.1.0 docs.

I only found these:
- Link from [\<md-subheader\> directive](https://material.angularjs.org/1.1.0/api/directive/mdSubheader) to `$mdSticky`.
- Links from [\<md-autocomplete\> directive (https://material.angularjs.org/1.1.0/api/directive/mdAutocomplete) to `VirtualRepeat` and `VirtualRepeatContainer`.

I can see it's only happening with internal links.

**Comment by DevVersion** [comment]
Thanks for the requested issue. Also thank you for searching for other broken links!
