### ISSUE TITLE
md-card title media is not resized

### ISSUE THREAD

**Issue by angularnewbee** [angular/material#9355]
**Actual Behavior**:
 -  Before I upgraded to angular-material 1.1.0, md-card automatically resized md-card-title-media images. I did not used any styling to resize image

Here is a codepen to show how it works:
http://codepen.io/angularnewbee/pen/NAmXpV

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.0.9

Here is a codepen to show the image is not resized. Is this expected?
http://codepen.io/angularnewbee/pen/GqLyNB

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Comment by ThomasBurleson** [comment]
@angularnewbee - please update to use `https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.1.0/angular-material.min.js`

**Comment by angularnewbee** [comment]
@ThomasBurleson - Thank you. I used this library https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.1.0/angular-material.min.js

Still no change.

**Comment by clshortfuse** [comment]
Regression due to PR: https://github.com/angular/material/pull/8786
