### ISSUE TITLE
fix(panel): Documentation/comment refactoring

### ISSUE THREAD

**Issue by bradrich** [angular/material#9357]
**Actual Behavior**:
 -  `What is the issue? *` There are several documentation / comment lines in the mdPanel service that are not following the correct syntax.
 -  `What is the expected behavior?` These syntax requirements are important to the understanding of the mdPanel service API and the documentation / comment lines need to be adjusted to comply.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` N/A
 -  `Details:` N/A

**Angular Versions**: *
 -  `Angular Version:` Latest
 -  `Angular Material Version:` Latest

**Additional Information**:
 -  `Browser Type: *` N/A
 -  `Browser Version: *` N/A
 -  `OS: *` N/A
 -  `Stack Traces:` N/A

Ping @ErinCoughlan

**Comment by topherfangio** [comment]
@bradrich Just saw this. Might be fixed by #9360?

**Comment by bradrich** [comment]
@topherfangio I am not sure about the incorrect Markdown support in the panel docs. I wasn't aware of that issue. My fix is based on incorrect usage of some of the documentation definitions. I am sure that our fixes could work together.
