### ISSUE TITLE
Demo "Flex Element Heights" on Layout Troubleshooting does not run.

### ISSUE THREAD

**Issue by topherfangio** [angular/material#9358]
**Actual Behavior**:
 -  `What is the issue? *` The "Results" tab for the demo shows uncompiled Angular code/tags.
 -  `What is the expected behavior?` It should show a compiled app.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` https://material.angularjs.org/latest/layout/tips

Likely caused by an GitCDN link; but I haven't tested (I had a very similar issue a few weeks ago though).

**Angular Versions**: *
 -  `Angular Version:` N/A
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Fixed with update to use ngMaterial v1.1.0 on CDN.

**Comment by ThomasBurleson** [comment]
Updated the CodePen templates and embedded version to use ng 1.5.5. and ngM v1.1.0.
