### ISSUE TITLE
$mdSticky: Dynamically added sticky are not sticking

### ISSUE THREAD

**Issue by U-like** [angular/material#9359]
**Actual Behavior**:
 -  `What is the issue? *` I'm working with sticky elements inside ng-repeat. The problem is that sticky-state of dynamically added elements are not sticking when scroll them.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [Here](http://codepen.io/gmanrique/pen/RROjjp)
 -  `Steps to reproduce:`
1. Scroll to end.
2. Click "Append More" button (on toolbar).
3. Scroll to end again.
4. Sticky element added on button click ("Messages 3", for example) are not sticking.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` 52.0.2743.82 (64-bit)
 -  `OS: *` Ubuntu 16.04 (64-bit)
 -  `Stack Traces:` -

**Comment by DevVersion** [comment]
Just took a look at this issue, and it seems like the subheader is made sticky correctly, but it just doesn't show up.

> You can confirm this, when scrolling up and then to the end again.

I hope we can address / fix that issue with #9361

**Comment by U-like** [comment]
I hope that too! Let me know if I can do something to help.

And thanks!

**Comment by DevVersion** [comment]
Will close that issue, since we address this with #9361.
