### ISSUE TITLE
mdGridList: does not work with `canvas` element during browser resize

### ISSUE THREAD

**Issue by onclave** [angular/material#9365]
I have been trying to use angular-chart.js with angular material and I created a gird view using `<md-grid-list>`.

I used a `<canvas>` element to render the charts. Everything works fine, except for the fact that when I try to resize the browser, the `show` and `hide` APIs on the canvas elements do not work. If I resize and refresh the browser, then it works. If I use the show and hide on a `div` which contains the canvas, then everything works. But the chart rendered is way too small and not responsive. Am I doing something wrong or does the APIs not work with canvas elements?

Thanks.

**Comment by ThomasBurleson** [comment]
@onclave - the mdGridList was designed for images and 1-2 lines of text. See [Material Design](https://material.google.com/components/grid-lists.html) specifications.  

Canvas/SVG (eg. Charts) seem like reasonable enhancements. Please provide a CodePen demonstrating the issue. At that time we can try to help.

**Comment by Splaktar** [comment]
No CodePen has been provided to demonstrate the issue as requested.

There are also no current plans to enhance md-grid-list.
