### ISSUE TITLE
mdPanel - allow to specify a content element.

### ISSUE THREAD

**Issue by ErinCoughlan** [angular/material#9366]
**Actual Behavior**:
 -  `What is the issue? *`
    In mdPanel, you can't specify an content element. You can in dialog, so we should find a way to make that code work for both components, probably via the mdCompiler.

 -  `What is the expected behavior?`
This allows developers, to specify a pre-rendered/compiled element, which will be not compiled each time a dialog opens.

It is possible to specify:

- A DOM Element
- A String as CSS Selector

When using an element, which is already present in the DOM, it will be anchored to the dialog, which means, that we temporary fetch it from the DOM into the dialog and move it back to its old DOM position upon close.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
@DevVersion - Can you help Brad here. I think you did something similar for Dialog?

**Comment by DevVersion** [comment]
@ThomasBurleson For sure - I actually planned to move that logic to the compiler anyways, because then we could also use that feature in the `bottom-sheet`, ` toast` and other interim elements.

As we discussed in the last Team Meeting, it would be better to start working on porting a simple component ('bottom-sheet`) to the panel, and concurrently work on the `contentElement` functionality for the panel (to be able to continue porting with the dialog)

**Comment by bradrich** [comment]
@DevVersion I will ping you when I start on this. Thanks!

**Comment by ThomasBurleson** [comment]
@DevVersion - sounds reasonable. I do not have clarity regarding the issues and impacts... but proceed if it makes sense and we can review the PR.

**Comment by crisbeto** [comment]
This was resolved via #9551. There is still some work related to the content element, but that will be tracked in a separate issue.
