### ISSUE TITLE
Using ngMaterial ^1.0.8 breaks drop menu [<md-icon class="material-icons ng-scope">more_vert</md-icon>] icons in Android KitKat 4.4.4

### ISSUE THREAD

**Issue by appplumbr** [angular/material#9368]
**Actual Behavior**:
 -  `What is the issue? *`
Using ngMaterial ^1.0.8 breaks drop menu [md-icons] icons in Android KitKat 4.4.4 and works like a charm in Android 5.0 + 

 -  `Code issue? *`
<md-icon class="material-icons ng-scope">more_vert</md-icon>

 -  `What is the expected behavior?`
Should appear same as in Android 5.0+

**Angular Versions**: *
 -  `Angular Version:`
"angular": "^1.5.5"
 -  `Angular Material Version:`
ngMaterial ^1.0.8

**Additional Information**:
 -  `Browser Type: *`
Android KitKat 4.4.4

**Comment by ThomasBurleson** [comment]
Please upgrade to v1.1.0 and retest. We can reopen if still present.

**Comment by appplumbr** [comment]
Hi Team,

There is no positive change or effect after upgrading to the latest stable version 1.1.0.

Please suggest, for Android 4.4.4 above it works without need of any customisation.

Thanks
![ui_break](https://cloud.githubusercontent.com/assets/16449783/18043092/27f34890-6de3-11e6-9315-c8a7a1fa0c2e.png)

**Comment by gotoashishgupta** [comment]
font-icons ligatures are poorly supported in android <= v4.4, so instead use code points
for more info checkout 
https://github.com/google/material-design-icons/issues/336
https://github.com/google/material-design-lite/issues/1375

**Comment by ThomasBurleson** [comment]
Will not fix.
