### ISSUE TITLE
Setting height value for flex in column layout

### ISSUE THREAD

**Issue by jintoppy** [angular/material#937]
I can give flex to specify how much space I want for a child. 

``` code
<div layout="row">
  <div flex="66" flex-sm="33">
    I flex to one-third of the space on mobile, and two-thirds on other devices.
  </div>
  <div flex="33" flex-sm="66">
    I flex to two-thirds of the space on mobile, and one-third on other devices.
  </div>
</div>
```

However, I think, if the layout is column, and if we give flex values to the child, it should give height, not width.

For eg.

``` code
<div layout="column">
  <div flex="66" flex-sm="33">
    I flex to one-third of the space on mobile, and two-thirds on other devices.
  </div>
  <div flex="33" flex-sm="66">
    I flex to two-thirds of the space on mobile, and one-third on other devices.
  </div>
</div>
```

In this, the height should be 66% for the first child. However, flex is just considering width only for now irrespective of the layout given. 

Please let me know your thoughts.

Thanks

**Comment by csvan** [comment]
This does not seem to be respected. See the following Plunk:

http://plnkr.co/edit/qgLJ18oExkWzjVCKXf9K?p=preview

Even if you manually force the parent element to be 500px, the columns will still not expand to fill their respective place in the column.
