### ISSUE TITLE
How to adjust the height of Angular Material Select Box?

### ISSUE THREAD

**Issue by Sabyasachi18** [angular/material#9371]
I have the following code 
```
<md-input-container style="margin-right: 10px;width: 13%;"  class="ScenarioDetailsDropdown" >
        <h4    class="LabelsPageOne">Geography Type</h4>
       
        <md-select ng-model="GeographyType" ng-change="SelectGeographyType()" >
          <md-option   ng-repeat="(index,ModelTableRow) in ModelTable | unique:'geographyType'" ng-value="ModelTableRow.geographyType" >{{ModelTableRow.geographyType}}</md-option>
        </md-select>

</md-input-container>
```

I am using it to make a drop down as follows : 

![image](https://cloud.githubusercontent.com/assets/20478237/17857072/f816d0be-689d-11e6-9763-36335e995b42.png)

How can i reduce the height of the Select Boxes?
Also, how can I reduce the top padding in md-input-container?
I tried using this : 
`<md-input-container style="margin-right: 10px;width: 13%;" class="ScenarioDetailsDropdown" style="padding : 0px 0px !important;margin:0px 0px;" >`

But, its not working.
Can you please help me to do this??
Thanks!

**Comment by Sabyasachi18** [comment]
this was solved by following answer provided over here: 
[http://stackoverflow.com/questions/39081963/how-to-adjust-the-height-of-angular-material-select-box]

**Comment by EladBezalel** [comment]
Those kind of questions should be asked in our [forums](https://groups.google.com/forum/#!forum/ngmaterial)
