### ISSUE TITLE
ng-model doesn't update for md-select element with ng-if 

### ISSUE THREAD

**Issue by yuvalbl** [angular/material#9372]
**Actual Behavior**:
 -  ng-model doesn't update for md-select element with ng-if
![1](https://cloud.githubusercontent.com/assets/11487010/17857383/39001662-688a-11e6-92d6-d61fcaf4a94c.png)

**Expected Behavior**:
 -  ng-model should update regardless of ng-if

**CodePen** (or steps to reproduce the issue): 
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/zBQoER
 -  `Details:` 
1. look at "Selectd Item name" value. change the select value - selectdItem doesn't change
2. remove ng-if from the HTML. change the select value - selectdItem getting the correct value

**Angular Versions**: 
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *`52.0.2743.116 m
 -  `OS: *` windows 7
 -  `Stack Traces:` not required

**Comment by EladBezalel** [comment]
@yuvalbl it seems like this is a dup of #9061 do you mind transfer your findings over there and close this one?

**Comment by yuvalbl** [comment]
Sure
