### ISSUE TITLE
md-select: empty value selection sets to string?

### ISSUE THREAD

**Issue by epelc** [angular/material#9373]
**Actual Behavior**:
 -  `What is the issue? *`  
In the 1.1.0 change log it notes you should change `value=""` to one of the following for an empty/default option. But if you use one of the first two it sets the value to literall strings(`"null"` or `"undefined"`) which breaks any `ng-if`s or other logic if you click on the empty option.

```
<md-option value="null">All options</md-option>
<md-option value="undefined">All options</md-option>
<md-option ng-value="''">All options</md-option>
```

 -  `What is the expected behavior?`  
Not sure if it should know `value="null"` means the js `null` and not `"null"` or if you just have to use `ng-value="null"`(or `undefined` or `''`). If it is the second, is there anyway to do this without an extra watcher? Or does `ng-value="null"` not create a watcher?

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/pbmRyL
 -  `Details:`
Click the first option which defaults to being selected. Note the binding changes to a string literal `"undefined"`. This also happens when you use `value="null"`

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *` 52
 -  `OS: *` os x 10.11.6
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by epelc** [comment]
ping @topherfangio this is related to #9240(changelog docs) and the original issue #9178(note in the pr the number was mistyped)

**Comment by topherfangio** [comment]
@epelc All `value="..."` attributes will evaluate to a string. Some users were actually checking for `$scope.value == "null"` which does evaluate to true (since they are testing against a string).

Perhaps we should just update the docs to make a note of this? Or are you thinking that there needs to be a code change?

**Comment by epelc** [comment]
@topherfangio I thought it was weird that the changelogs recommend using a string for an empty value. 

Caught me off guard as I somewhat expected it to "Just work™" and use js `null`/`undefined`.
