### ISSUE TITLE
layout: gradual flex (flex="val") doesn't Work with Conditional Layout

### ISSUE THREAD

**Issue by mahmoudajawad** [angular/material#9376]
**Actual Behavior**:
-  `What is the issue? *`
  if you create a container that has a conditional layouting attribute, say, layout-gt-xs="row", ngMaterial would add the class "layout-gt-xs-row" which would render flex="val" attribute invalid as the stylesheet defins flex="val" using a parent container with the class "layout-row".
-  `What is the expected behavior?`
  to work without defining a default layout="row"

**CodePen** (or steps to reproduce the issue): *
http://codepen.io/AjawadMahmoud/pen/WxBpGP

**Angular Versions**: *
-  `Angular Version:`
  1.5.8
-  `Angular Material Version:`
  1.1.0

**Additional Information**:
-  `Browser Type: *`
  Chrome, Firefox
-  `Browser Version: *`
  Latest both
-  `OS: *`
  Fedora 24

**Comment by ThomasBurleson** [comment]
Simply use: 
```html
<div ng-controller="AppCtrl" layout="column" layout-gt-xs="row">
```
This way the *default* layout is `column` and the override is `row`; specifying a default is important. 

Will not fix until ngM1.2

**Comment by AjawadMahmoud** [comment]
In fact, i've done the same. yet, i consider it a workaround where the codepend example should've worked.
it's not a so big deal. just something to work with when having free time.

**Comment by mahmoudajawad** [comment]
Closing this as I'm no longer attending this issue.
