### ISSUE TITLE
Conflict with normalize.css

### ISSUE THREAD

**Issue by MarcosPortugal** [angular/material#938]
When using normalize.css, the buttons will appear darker than they should, when clicked. This is probably due to normalize's lines:

     /**
    * 1. Correct color not being inherited.
    *    Known issue: affects color of disabled elements.
    * 2. Correct font properties not being inherited.
    * 3. Address margins set differently in Firefox 4+, Safari, and Chrome.
     */

    button, <---- buttons are targeted
    input,
    optgroup, 
    select,
    textarea {
      color: inherit; /* 1 */ <---- inherit value is assigned to color, this causes the "darkness"
      font: inherit; /* 2 */
      margin: 0; /* 3 */
    }

Angular material should adjust for this. Thanks!

**Comment by marcysutton** [comment]
Button color is no longer targeted in `normalize.scss`. Closing.
