### ISSUE TITLE
Select list open scrolling locked 

### ISSUE THREAD

**Issue by bvsbharat** [angular/material#9381]
**Actual Behavior**:
 -  `Select list open scrolling locked  *`
 -  `it need to constant at that place' 

**Angular Versions**: *
 -  `Angular Version:1.4`
 -  `Angular Material Version:1.1.0`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EladBezalel** [comment]
@bvsbharat Without codepen we won't start investigating. 
Please provide a codepen and explain more about the problem.
