### ISSUE TITLE
md.select Release 1.1.0-rc.5.  required field doesn't work properly

### ISSUE THREAD

**Issue by gss-patricia** [angular/material#9382]
Actual Behavior:

I have a required select box field, but doesn't display the asterisk and when it isn't filled the bottom border doesn't change to red.

CodePen Demo which shows your issue: http://codepen.io/gss-patricia/pen/YWbOyV
AngularJS v1.5.7
Angular Material Version: 1.1.0-rc.5

Browser Type: Chrome
Browser Version: 51.0.2704.84
OS: Linux 14.04 LTS

<img src="http://storage5.static.itmages.com/i/16/0823/s_1471960028_4789257_3343de1e9c.png" />
----

**Comment by EladBezalel** [comment]
@gss-patricia version 1.1.0 has been released.

Please verify your codepen against MASTER.

**Comment by gss-patricia** [comment]
Tks @EladBezalel sorry
