### ISSUE TITLE
mdPanel -allow clickOutsideToClose works with propagateContainerEvents

### ISSUE THREAD

**Issue by ivanzvakoms** [angular/material#9388]
**Actual Behavior**:
-  Currently mdPanel by default use body element as parent and have wrapper(`.md-panel-outer-wrapper`) with styles `{ height: 100%; left: 0; position: absolute; top: 0; width: 100%; }` so we must use `propagateContainerEvents: true` (`pointer-events: none;`) to be able to interact with page elements. But in this case `clickOutsideToClose:true` doesn't work at all.
-  When `clickOutsideToClose:true` is specified along with `propagateContainerEvents: true` it should close our panel when user clicks somewhere on page, but also propagate this event to a target.

**CodePen** (or steps to reproduce the issue): *
-  You could observe this in demo example in docs for 1.1.0
-  N/A

**Comment by myagoo** [comment]
Here is a codepen where you can see those 2 options set to true : http://codepen.io/anon/pen/EgjpkP
You can see that the dialog panel never close without propagating clicks and that the select panel propagate the click but do not close (you can have fun clicking the select button multiple times)
