### ISSUE TITLE
Chips have poor accessibility

### ISSUE THREAD

**Issue by jelbourn** [angular/material#9391]
It appears that the chips don't have any accessibility treatment other than a few `aria-hidden` and `aria-label` instances. Follow up with me for more details.

**Comment by ThomasBurleson** [comment]
Review the Google Drive *Share* dialog for examples of Chips with a11ly

**Comment by topherfangio** [comment]
@jelbourn @ThomasBurleson Quick update: I spent way more time on this than expected but I finally have what I think is a working version. I want to run it through NVDA one more time tomorrow before I push a PR. Once the PR is pushed, I expect some feedback, and while I wait, I plan to add more tests.

So, gameplan is:

1. Test on NVDA/Firefox tomorrow.
1. If all is good; push my in-progress PR so I can receive feedback.
1. While waiting for feedback, write some additional tests for keyboard navigation.
1. Make any requested changes and push a final version of the PR which requires bigger review and presubmit.

Let me know if I should change anything above.
