### ISSUE TITLE
mdSidenav: Animation and backdrop not working when used with ui-router

### ISSUE THREAD

**Issue by Senyeah** [angular/material#9394]
**Actual Behavior**:

`md-sidenav` does not animate nor have a backdrop when ui-router is used and the `ui-view` attribute is applied to its parent container. This is unexpected; the animation should occur and the backdrop should be visible.

**CodePen**:
- [Example with `[ui-view]` applied to the sidenav’s parent](http://codepen.io/senyeah/pen/AXkGWd)
- [Example without `[ui-view]` applied to the sidenav’s parent](http://codepen.io/senyeah/pen/vKwqKE) (reference – expected behaviour)

**Angular Versions**:
 -  Angular version 1.5.5
 -  Angular Material version 1.1.0

**Additional Information**:
-  Browser: Chrome 52.0 on OS X 10.11.5
-  `ui-router` version 0.2.18

**Comment by clshortfuse** [comment]
The navbar issue existed before in
https://github.com/angular/material/issues/8544

Opening a sidenav is supposed to trigger a succession of classes like `ng-animate` that aren't happening.
The backdrop issue seems related to `ng-enter` class sticking and never getting removed.

I know for sidenav, we can add a transition rule to the base CSS rule for sidenav and it'll fix it, but I rather do some research on how ui-view creates and modifies elements first.

**Comment by ThomasBurleson** [comment]
This may be related to `$destroy( )`; check past issues with ui router

**Comment by clshortfuse** [comment]
I found the issue. `ngAnimate` waits two digest cycles before enabling any animations. `ngAnimate` is still in a disabled (PRE-DIGEST) state when `ui-router` creates `md-sidenav`. When `postLink` is called, the animation service is still not ready, and we are assuming `ng-enter` will get removed since we called it.

https://github.com/angular/material/blob/218c3ec321345d0c6dec9a1a4075a11296472382/src/components/sidenav/sidenav.js#L363

`$animate.leave(backdrop)` is not removing the classes we are expecting.

**Comment by clshortfuse** [comment]
And I investigated further and it seems that `areAnimationsAllowed` in `ngAnimate` can't find the rootElement. It seems you're not supposed to attach `ui-view` to `body` as per Step 2 in 

https://github.com/angular-ui/ui-router/blob/master/README.md

Once you remove `ui-view` from `body` and use it in a `div` as a child, all animations work properly.

**Comment by mpk2** [comment]
To clarify for future issue viewers 

> Once you remove `ui-view` from `body` and use it in a`div` as a child, all animations work properly.

I (in my case) specifically had to have `ng-app` on my `body` and `ui-view` on the child `div`. When I had `ng-app` on the same `div` as `ui-view`, the problem persisted.

**Comment by snrweb** [comment]
This issue is reproducible even I use ng-view.
