### ISSUE TITLE
ie10 MutationObserver is undefined

### ISSUE THREAD

**Issue by j3ski** [angular/material#9395]
**Actual Behavior**:
 -  `What is the issue? *`
When I enter a page which uses md-tabs i get an error: "ReferenceError: 'MutationObserver' is undefined"
 -  `What is the expected behavior?`
I shouldn't be getting the error

**CodePen** (or steps to reproduce the issue): *
 - Go to [the official demo](https://material.angularjs.org/latest/demo/tabs) on ie10
 - [possible culprit](https://github.com/angular/material/blob/875848817bf9820f510647d2b01a347bb4fd8e46/src/components/tabs/js/tabsDummyWrapperDirective.js#L20)

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: 1.1.0`

**Additional Information**:
 -  `Browser Type: ie`
 -  `Browser Version: 10`
 -  `OS: windows 7`
 -  `Stack Traces:`

**Comment by naveedahmed1** [comment]
Can someone please check if the issue still exists? I am receiving below error in my app when running it on IE 10:

```
EXCEPTION: Uncaught (in promise): ReferenceError: 'MutationObserver' is undefined
ReferenceError: 'MutationObserver' is undefined
```

**Comment by prinzt** [comment]
I can confirm the error on IE10.
- Angular 4.0.0
- Material 2.0.0-beta.2

**Comment by dylanlawrence** [comment]
We also had this with IE10,  I was able to add this polyfill - https://github.com/megawac/MutationObserver.js to resolve it but it seems like this 'observing' could just be handled by Rxjs or something that has accounted for these issues.
