### ISSUE TITLE
md gridlist has a padding-bottom that is the size of the actual height of the tile.

### ISSUE THREAD

**Issue by concept-core** [angular/material#9404]
**Actual Behavior**:
-  `What is the issue? *`
  Then gridlist has an height of almost double then what it should be.
-  `What is the expected behavior?`
  Only the height of the actual needed height

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  none, but on the first reply I will open an port on ngrock so it can be viewed.

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.0-rc2

**Additional Information**:
-  `Browser Type: *` Chrome 
-  `Browser Version: *` 52.0.2743.116
-  `OS: *` Mac elcaptain

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed due to one of the following reasons:

*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests (PR) are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Keep your PR small and focused; PRs with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
