### ISSUE TITLE
button: content (name/title) only renders on scrolling 

### ISSUE THREAD

**Issue by subtainishfaq** [angular/material#9405]
**Rendering on Scroll**:
-  `I have developed directive using md button and passed the variable through scope as an attribute ,  variable contains the string to be used as inner html,but the changes in inner html is only visible on scrolling or resizing  *`
-  `change in inner html should be visible , as I am passing a string through scope to the directive`

**Code** : 
-  `Demo which shows theissue:`
-  `Details:
  
  var directive={
            restrict: 'E',
            scope: {
                saveAction: '&',
                cancelAction: '&',
                doneAction: '&',
                backAction: '&',
                saveShow: '=',
                cancelShow: '=',
                skuShow: '=',
                doneShow: '=',
                backShow: '=',
                saveButtonName: '=',
                cancelButtonName: '@',
                doneButtonName: '@',
                backButtonName: '@',
                skuShowButtonName: '@'
            } `

**Comment by subtainishfaq** [comment]
` <md-button  flex="none" class="primary-button" ng-if="CrudButtonsCtrl.backShow" ng-click="CrudButtonsCtrl.backAction()">
        <md-icon class="tmx-button md-accent material-icons">keyboard_return</md-icon>{{CrudButtonsCtrl.backButtonName}}
    </md-button>`

The above code is sample button used as template for the directive , rest of the directive is functional , only rendering is exceptional.

**Comment by Splaktar** [comment]
If this is still an issue, please provide a CodePen demo.
