### ISSUE TITLE
In md-menu-item type="checkbox" the checkbox is not visible

### ISSUE THREAD

**Issue by acherniak** [angular/material#9407]
My md-menu-item type="checkbox" never shows the actual checkbox. It seems to work in the Demo (https://material.angularjs.org/latest/demo/menuBar), but doesn't when I go to the associated CodePen.
I can see md-icon md-svg-icon="check". In demo it's somehow populated from core-icons.svg, but  empty in my case.
I'm using v.1.1.0. Tried it with with the latest AngularJS and 1.5.5 you are using.
Please help.

**Comment by DevVersion** [comment]
It seems like we need to update SVG asset cache to also contain the checkbox svg.
