### ISSUE TITLE
select: sizes options panel to current, not widest, option

### ISSUE THREAD

**Issue by DavidSouther** [angular/material#9409]
**Actual Behavior**:
-  `What is the issue?` `md-select` sizes to current, not largest, element.
-  `What is the expected behavior?` `md-select` should be wide enough to show all `<option>`s.

**CodePen** (or steps to reproduce the issue):
-  `CodePen Demo which shows your issue:` http://codepen.io/DavidSouther/pen/YWovpv
-  `Details:` https://material.angularjs.org/latest/demo/select in Option Groups

![rzfe2oshmip](https://cloud.githubusercontent.com/assets/498712/17978354/9b3bc71e-6ac3-11e6-9b92-bccbea3c748f.png)

**Angular Versions**:
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.0

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 52
-  `OS: *` Ubuntu
-  `Stack Traces:` n/a

**Comment by Splaktar** [comment]
I cannot reproduce this on macOS and Chrome 67. 

Is this still an issue for you? 
Is it only on Ubuntu?
