### ISSUE TITLE
ContentEditable is still not focusable on mobile

### ISSUE THREAD

**Issue by kpgarrod** [angular/material#9414]
**Actual Behavior**:
 -  `What is the issue? *`
Using ngWig editor on a page with angular-material, the ngWig editor window (contentEditable) cannot be brought into focus by clicking on it. 
 -  `What is the expected behavior?`
It should be possible to bring the ngWig editor window into focus (and therefore edit the content) by clicking on it 
**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/kpgarrod/pen/BKVeZV
 -  `Details:` Try to edit the 'Biography' field on an Android (4.4 e.g.) device.

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Android browser
 -  `Browser Version: *` 
 -  `OS: *` Android 4.4
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
That's a valid issue - The problem is related to our Fastclick Solution.

---

As a workaround you can disable the click hijacking and everything works as expected (tried it out)
> http://codepen.io/DevVersion/pen/XKLLrY

```js
$mdGestureProvider.skipClickHijack();
```

Anyways that issue will be hopefully fixed when dropping `$mdGestures` and using another Fastclick solution like HammerJS. See #9362

**Comment by kpgarrod** [comment]
@DevVersion that certainly seems to work for me. I really appreciate the quick response :). Are there any implications of skipping clickHijack?

**Comment by DevVersion** [comment]
I'm going to merge this issue into #9362 now.
