### ISSUE TITLE
Diferents number of inputs per row according to size screen

### ISSUE THREAD

**Issue by ferchoman09** [angular/material#9421]
In others frameworks I can specify the number of columns of an input. (With a grid of 12 columns per row).
I have a dynamic form. I don't know the number of inputs. I want to put according to size screen the inputs. 
With actual layouts.... I only can specify "column" (one input per row) or "row" (all inputs in the same row).

Can someone help me?

**Comment by EladBezalel** [comment]
I'd suggest you'd build you own directive that will use `$mdMedia` to know what screen size you are and set the flex for each element.

Please know that these kind of questions aren't an **issues** and should be asked on our forums.

**Comment by ferchoman09** [comment]
But, flex only works in the same row. I want to specify the input widths and the framework should make line breaks.

**Comment by EladBezalel** [comment]
I'd suggest you read the layout system documentation again, 
You can use layout-wrap, which will wrap if it's past 100

**Comment by ferchoman09** [comment]
Oh thanks bro.
I've been searching and have not found anything .
I will read about layout-wrap.
