### ISSUE TITLE
Virtual Repeat Strange Scroll Behaviour

### ISSUE THREAD

**Issue by SemihGk** [angular/material#9422]
**Actual Behavior**:
I have nested virtual repeats and it renders without problem, but I am having strange scrolling problem. If I scroll down, I cannot view all items and it jumps to another parent item. Well, it is hard to explain.

I assume that problem is the predefined height for parent items. Virtual repeat sets the same height for each item, but mine is not same height. That is why I am having the scrolling problem, but I could not find any solution that makes a dynamic height for each item(not rendering for scrolling).

**CodePen** (or steps to reproduce the issue): *
[Codepen](https://codepen.io/semihgk/pen/Pzrwkj)

-- Scroll down slowly

**Comment by Splaktar** [comment]
I believe that the virtual repeat depends on the items being the same size. If you need a virtual repeater that can support dynamic element sizes, I believe that you will need to build your own. You can certainly use the code for md-virtual-repeat as a starting point.
