### ISSUE TITLE
list-item: add way to disable proxy elements detection

### ISSUE THREAD

**Issue by BenjaminBatman** [angular/material#9423]
**Actual Behavior**:
 -  `What is the issue? *` I have a md-menu inside of md-list-item and it is adding an extra div container (the ripple container) to the md-list-item and opening my menu when the md-list-item is clicked. This is something new to the v1.1.0 release. v1.1.0-rc.5 did not have this issue.
 -  `What is the expected behavior?` The md-menu should only open when button associated with the menu is clicked not the entire list item. Also wouldn't expect the ripple affect to be applied to the entire item.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` 
v1.1.0-rc.5: http://codepen.io/benjaminbatman/pen/BzXoLj
v1.1.0: http://codepen.io/benjaminbatman/pen/pbrJrR
 -  `Details:` The first link demonstrates how it used to work. The menu would only open when the menu button is clicked. The second link shows how it is working now. The menu is opened when the list item is clicked. 

**Angular Versions**: *
 -  `Angular Version:` v1.5.8
 -  `Angular Material Version:` v1.1.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52.0.2743.116 m
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is a new feature, which was added in `v1.1.0` within PR https://github.com/angular/material/pull/6459.

Anyways it is currently not possible to disable proxy elements, so it would be good to have an attribute to disable this.
