### ISSUE TITLE
Highlight does not work correctly for some RTL languages

### ISSUE THREAD

**Issue by m-kermani** [angular/material#9426]
It is  hard to explain for those who do not know the Persian/Arabic alphabet, in English, each letter is separated from other letters which mean if you add quotes (") between  words' letters those quotes won't destroy the word. But in Arabic/Persian alphabet, **there are 4 different contextual forms which are Final, Medial, Initial and Isolated letters.**

Angular Material Highlight used in some different places, autocompletes, chips, etc;  Are using highlight and when highlight find searched word it will include <span> that has the `.highlight` class around it (It is like the quotes).

Here is an example and comparing between English and Persian/Arabic to understand what is the problem, In English when I search **"`rl`"** and I if I had **world** in my page, highlight will do this:
`    wo<span class="highlight">rl</span>d`
    which return:
![image](https://cloud.githubusercontent.com/assets/7496103/17509943/c3eb2f72-5e31-11e6-9e80-b998d28c780c.png)

But, `<span class="highlight">state.term</span>`   (state.term is the searched  term) may destroy the Persian/Arabic readability, because the letter that is at the end (in .highlight) will take a **Final** [contextual forms](https://en.wikipedia.org/wiki/Persian_alphabet).

Here is an example in Persian:
This is what the current version of Angular Material _(v1.1.0)_ returns:
![image](https://cloud.githubusercontent.com/assets/7496103/17510145/e58df6cc-5e32-11e6-8613-d248ec4f8c5f.png)

This is what it should look like:
![image](https://cloud.githubusercontent.com/assets/7496103/17510211/3234cb36-5e33-11e6-9ca7-dfb80cbe0bca.png)

Why solve this problem?

- There  are ~110 million Persian speakers and ~420 million Arabic speakers and I think that problem is for a large number of people/users, and this issue needed to be fixed.

- This bug is destroying readability.

_You can see the Highlight demo Persian language here: http://codepen.io/kermani/pen/NAQdqN_
For example search for "م" 

**I'm working on this bug now**, It will take about 2-4 days for me to solve it, I need to research more about these RTL languages and also write better functions to solve this and I need to read some parts of Angular Material source code.

**I need your help to solve this problem and someone to do me this favor and reviews my codes**

**Comment by EladBezalel** [comment]
@m-kermani this is not angular material problem, this is an html problem.

Look at this [codepen](http://codepen.io/EladBezalel/pen/GqVzjG), as you can see this is not related to angular or angular material at all..

To highlight text you must wrap it with a class, we can't do anything else.
I'm sure someone else have already thought of it so i suggest you continue to look for it, in case there's a css property that solves it, awesome! put a PR and we will test it.

**Comment by m-kermani** [comment]
@EladBezalel Thanks for your comment. Sure, I know this is HTML problem, but it is happening in Angular Material Highlight and we can solve it.

I'm working on this issue now, and thanks for your offer to review my code.

I'm wiring JS for it now, but you said there is a CSS property for that, I'm not sure about it, could you please let me know more about it?

Thanks

**Comment by EladBezalel** [comment]
I was trying to find anything in css that prevents it, in Hebrew we have keys for both regular and final forms..

How are you going to solve it with javascript if i may ask?

**Comment by m-kermani** [comment]
@EladBezalel I did not know there is same problem for Hebrew.

If you remember in my first comment (issue) I said:

> there are 4 different contextual forms which are Final, Medial, Initial and Isolated letters.

In Persian/Arabic there are some characters (Unicode) that can convert for example a _Final_ letter to a _Medial_ letter, what I'm going to do is:

- Check if the searched term has any Arabic/Persian letter (In this case, maybe the text is Persian/Arabic...)

- Then look at the searched term, because there are some different contextual forms, for the different letter, there are different actions the program should take, For example adding a character to the start or end (or both) or the searched term.

- According to the searched term, and the text we also need to add some different characters to text (When we are going to insert our` .highlight` span)

- And some more steps...

I just hope that does not add many lines of JS to it, and I am sure you can help by revising my PR.

Thank you so much

**Comment by EladBezalel** [comment]
IMO this is not related to our code base, this will be a bloat for users that doesn't need it and we try to avoid those kind of stuff, 
I highly recommend that you will create a directive that will hook into the autocomplete and do what you suggested.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
