### ISSUE TITLE
tabs issue with 1.1.0

### ISSUE THREAD

**Issue by emps** [angular/material#9429]
md-pagination-wrapper width is 1px less from what it should be generated, and this makes last tab to disappear from the bar
![untithjkhkhkled-1](https://cloud.githubusercontent.com/assets/2281169/18026541/3652c3f2-6c53-11e6-9a95-b7d8d153c148.png)

when i set 1px more it works ok, this issue happen with all may tabs after updating to 1.1.0 from rc5

**Comment by gdereese** [comment]
I am also seeing this issue.  It seems that refreshing the browser sometimes fixes the problem, but it's intermittent.  I was also observing this behavior before 1.1.0 rc5.

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate more

**Comment by emps** [comment]
hii thanks for replay, im very busy i will try make this tomorrow, but untill then what i see is, md-pagination-wrapper width is 1 px less then what it should be, sometimes it calculated correct and last tab is visible.., if i change it manually 1px more my tab comes back

**Comment by U-like** [comment]
Same as #5439, right?

**Comment by emps** [comment]
yes same, welli just did some directive to fix it, hope there will come fix for this

**Comment by topherfangio** [comment]
If someone can provide a Codepen, I will definitely look into this.

**Comment by zgambino** [comment]
Here's a codepen based on the markup I'm using that also has the same issue:

http://codepen.io/zgambino/pen/PGNrad

**Comment by emps** [comment]
@zgambino thanks for the code, @EladBezalel bro check it out, tab 3 may be appear if u resize the screen or play with the css md-pagination-wrapper width +1px

**Comment by topherfangio** [comment]
@zgambino Thanks for the demo! I'll definitely look into this.

**Comment by twizzzlers** [comment]
+1

**Comment by p-mcgowan** [comment]
```
md-pagination-wrapper {
  width:auto !important;
}``` is a hacky temporary workaround until this is resolved.

**Comment by emps** [comment]
@p-mcgowan that isnt a good fix, i tried that long time ago it make problems too... already forgot what it was//

**Comment by p-mcgowan** [comment]
I found this was a problem with setting ```
md-tabs md-tabs-wrapper md-tabs-canvas md-tab-item:not([disabled]) {
    text-transform: uppercase;
}```
as well, and the only fixes I have found are manually calculating

**Comment by reppners** [comment]
> md-pagination-wrapper {
>   width:auto !important;
> }
> is a hacky temporary workaround until this is resolved.

Won't work when tab items overflow the pagination-wrapper e.g. most likely on small screens.

Is there any other proper workaround? Having to fix this in an production app ASAP.

**Comment by emps** [comment]
for now use this directive 
```
'use strict';
angular.module('APPNAME').directive('fixTabs', function($q, $timeout) {
	function link(scope, element, attrs, ctrl) {

		$timeout(action, 500);
		//TODO: on resize
		function action() {
			let elm = 'md-pagination-wrapper';
			let width = parseFloat(angular.element(document.querySelector(elm)).css('width'));
			angular.element(document.querySelector(elm)).css('width', (width + 1) + 'px');
		}
	}
	return {
		link: link,
		restrict: 'A'
	};
});
```
just add it to any  md-tabs like..
<md-tabs fix-tabs

**Comment by clshortfuse** [comment]
ping @ErinCoughlan

**Comment by clshortfuse** [comment]
http://codepen.io/shortfuse/pen/ENWbjL on master with workaround for dialog

The issue relates to the md-tab's size being changed and the component not properly handling it. As I said in the previous comment, the dialog animation is causing the width to be calculated while in transition. Regardless, it should update itself.
