### ISSUE TITLE
how to disable theming globally?

### ISSUE THREAD

**Issue by haoxins** [angular/material#943]
Is it possiable to add a option to enable/disable theming globally

**Comment by DominicBoettger** [comment]
Sorry to mention this again, but i don't like that behaviour. I think these theming stuff should be done via SASS and not be injected via javascript. Even when setting it to 'none' the default theme will be injected.
In my opinion there should be a body class or Attributewhich toggles the default theme.
Everything else could be done via sass and even the material color stuff can be calculated there. The performance would be much better as i can see all the stuff going in the head section when loading material....

**Comment by sergonius** [comment]
Yeah, at least "none" should remove the default, it is a pain to inspect everything and override a large amount of styles. A SASS config and more control over this would make the whole thing more usable.

**Comment by mackelito** [comment]
Would kind of like to bring this question/issue back to life..
I don't think that the concept of setting theme to none/null/whatever is a proper solution.

All things needed for the themes are still loaded and executed. Surely there must/should be away to really disable it?

**Comment by DominicBoettger** [comment]
I am pretty sure that material is doing too much stuff in js at the moment. I think there would be a dramatic performance increase when doing layout and theming stuff in scss. I am using stuff like sass-material-colors in my themes and i am also able to define a lot of stuff. I also had issues with browser compatibily which i solved in scss with bourbon.

**Comment by mackelito** [comment]
And it you are not using themes in this matter?... What if you don't benefit from the themes?... Just think there would be an option to disable it..

**Comment by DominicBoettger** [comment]
I think it's a misunderstanding. I want to be able to disable the themes in javascript and write the theme information in SCSS.

:+1: for doing something like $mdThemingProvider.setDefaultTheme('none');

**Comment by mackelito** [comment]
When you specify it like $mdThemingProvider.setDefaultTheme('none'); it will still look for a theme with the name "none". And it will add a lot of references to your "none" theme..

So you are not disabling themes you are just calling a none existing theme ;)

**Comment by DominicBoettger** [comment]
Yes, i know.... The idea was that i think that it should be possible to completely disable the theme.

**Comment by mackelito** [comment]
A member of our team just found out that can override the constans.
```javascript
// Setting this will result in not adding theme classes on components
.constant("$MD_THEME_CSS","");
```

**Comment by DominicBoettger** [comment]
That helped a lot. Thanks.

**Comment by luncht1me** [comment]
@mackelito Thank you for that constant! We're using angular-material for the first time at my company, and our css guy doesn't really like overwriting styles but rather structure his own from the ground up. 

This has helped a lot!
