### ISSUE TITLE
mdCheckbox: ng-message are not shown for a md-checkbox inside a md-input-container

### ISSUE THREAD

**Issue by Frank3K** [angular/material#9430]
**Actual Behavior**:
-  `What is the issue? *` 

When a `md-checkbox` is used with `ng-messages` inside a `md-input-container` the errors are not displayed when the model is invalid.
-  `What is the expected behavior?`

The messages are displayed, just as with they are with regular `input` elements.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` https://codepen.io/anon/pen/KrOWdZ?editors=1000
-  `Details:` Forked from a demo by @alexilyaev.

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:`  v1.1.0-master-0cd2a59

**Additional Information**:
-  `Browser Type: *` Chromium
-  `Browser Version: *` 51.0.2704.79
-  `OS: *` Ubuntu 16.04
-  `Stack Traces:`

This is the exact same issue as #8267, which was closed as a part of the Surge Focus on Material 2'. I have created a new issue since I think I have found out why it is not working as expected.

When the checkbox is invalid, the corresponding `md-messages` is added to the DOM. However, the enter animation is not started and therefore the message can not be seen by the user. 

The message animation is triggered by the following `addClass` in [input.js](https://github.com/angular/material/blob/fa6213d38c2959d6155b546fcadc72c150ab370b/src/components/input/input.js#L126-L132):

``` js
    self.setInvalid = function(isInvalid) {
      if (isInvalid) {
        $animate.addClass($element, 'md-input-invalid');
      } else {
        $animate.removeClass($element, 'md-input-invalid');
      }
    };
```

For regular inputs, this method is called [as follows](https://github.com/angular/material/blob/fa6213d38c2959d6155b546fcadc72c150ab370b/src/components/input/input.js#L352-L356):

``` js
    var isErrorGetter = containerCtrl.isErrorGetter || function() {
      return ngModelCtrl.$invalid && (ngModelCtrl.$touched || (parentForm && parentForm.$submitted));
    };

    scope.$watch(isErrorGetter, containerCtrl.setInvalid);
```

The `md-select` and `md-datepicker` directives also contains such constructions [md-select](https://github.com/angular/material/blob/f265a0ed1389141ac74656e6837d4d3e096a65bb/src/components/select/select.js#L285-L302), [md-datepicker](https://github.com/angular/material/blob/6cfb542313eb2b14e147c62bcf5d3744cf63522c/src/components/datepicker/js/datepickerDirective.js#L162-L164).

The [checkbox directive](https://github.com/angular/material/blob/3cf220aaa7121399e97b8ea2ec99f4637f3d02dc/src/components/checkbox/checkbox.js) however lacks such call. Therefore the class is never added and the animation is not started.

**Comment by Frank3K** [comment]
I'm working on a PR for this issue. In my local build it already works, but some `md-switch` (which uses the `md-checkbox` directive) tests are failing...

**Comment by makkart** [comment]
For what I can tell the same problem applies to md-radio-group to, would it be possible for you to have a look at implementing this fix for that to?

**Comment by topherfangio** [comment]
@Frank3K Assigning myself so I can track it while we wait for the PR to be merged :-)
