### ISSUE TITLE
z-index of tool-tip

### ISSUE THREAD

**Issue by smcardle** [angular/material#9439]
**Actual Behavior**:
 -  `What is the issue? *`
The z-index of md-dialog is greater than the tool-tip z-index thus the tool-tip(s) for buttons used in a dialog are displayed under the dialog
 -  `What is the expected behavior?`
The tool-tip should display unde the button but above the dialog

**CodePen** (or steps to reproduce the issue): *
Create an md-dialog, add a button with a tool-tip then hover over the button.
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
1.4.3
 -  `Angular Material Version:`
1.1.0

**Additional Information**:
 -  `Browser Type: *`
Chrome
 -  `Browser Version: *`
52
 -  `OS: *`
Mac OSX Mavericks
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EladBezalel** [comment]
Please provide a codepen so we can investigate more.

**Comment by crisbeto** [comment]
I didn't manage to reproduce it by adding a tooltip to one of the dialog demos.

**Comment by ThomasBurleson** [comment]
Unable to reproduce.
