### ISSUE TITLE
mdSwitch: when focused and without a label, displays a black dot

### ISSUE THREAD

**Issue by PaulMougel** [angular/material#944]
This happens on Chrome, Safari and Firefox, on `v0.6.1-master-fcb9b2c`.

In this example, the first slider has a label and behaves well. The second doesn't have a label, but when focused a black dot is displayed…

[Plunker here](http://plnkr.co/edit/oJy0pvEk60v7M0AwC3ke?p=preview), code below:

``` js
<md-switch ng-model="switched" aria-label="Awesome Switch" ng-model="switched">Yo</md-switch>
<md-switch ng-model="switched" aria-label="Awesome Switch" ng-model="switched"></md-switch>
```

![untitled](https://cloud.githubusercontent.com/assets/1788596/5436556/d7d46328-8467-11e4-9568-0fe679ee7523.gif)

You can also manually trigger this artifact by selecting the `:focus` style in devtools:
![image](https://cloud.githubusercontent.com/assets/1788596/5436609/69a3a534-8468-11e4-80d2-3e5050dc9b9a.png)

**Comment by ilanbiala** [comment]
@ajoslin with 0.7.0 I still have the dot show up after I click. Clicking on something else (moving focus) removes the dot.

**Comment by ilanbiala** [comment]
@ajoslin @ThomasBurleson 0.7.1 still has this issue with the checkbox.

**Comment by ilanbiala** [comment]
@ajoslin @ThomasBurleson still present with 0.8.2.
