### ISSUE TITLE
Angular Material css failing for node version update to 4.2.3

### ISSUE THREAD

**Issue by cosmos-sajal** [angular/material#9440]
**Actual Behavior**:
 -  `My server was runing on node 0.10.3. I updated to version 4.2.3 after which the css for angular material broke. I did a node-sass rebuild but to no avail.`
 
**Expected Behavior**:
 -  `Css shouldn't break`

**Angular Versions**: *
 -  `1.5.8 angular`
 -  `1.1.0 angular material`
 
Attaching screenshot of issue after updating and what it was earlier respectively.
> after
![screen shot 2016-08-29 at 1 10 00 pm](https://cloud.githubusercontent.com/assets/9356893/18044176/1a718f4a-6dea-11e6-8368-24fbd8fd8356.png)

> before
![screen shot 2016-08-29 at 1 10 55 pm](https://cloud.githubusercontent.com/assets/9356893/18044177/1ca86036-6dea-11e6-936c-bd2be5632fca.png)

**Comment by EladBezalel** [comment]
In case your'e using npm/bower as package managers you shouldn't have a problem, we compile and pack everything and then deploy it.

In case you're building it yourself, i'd suggest you'd consider using npm instead.
More on that, i used node 4+, 5 and 6 and they're all working with no problems.

Please be aware that those kind of questions should be asked on our forums.
