### ISSUE TITLE
Content of the div with flex attribute overflows

### ISSUE THREAD

**Issue by jcubic** [angular/material#9441]
**Actual Behavior**:
 -  `What is the issue? *` the div with class spacing and attributes flex="60" and ng-show="item.isVisible" have fixed height even that the content is larger and content of that div overlaps next element
 -  `What is the expected behavior?` the height of that div should contain all elements that are inside

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/jcubic/pen/XKvWjq
 -  `Details:` when you click add button the input overlap textarea

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` 52
 -  `OS: *` Windows 7
 -  `Stack Traces:`

**Comment by EladBezalel** [comment]
I'm sorry i really couldn't understand your issue. it seems to be working when i inspect the elements.

please explain it further.

**Comment by jcubic** [comment]
I don't know what else I can say, just click add button few times and see the results. The input box and button is overlapping the textarea instead of being above it. If you add 3 items (click add 3 times) the height of the div that have ul inside is 346px but the div with attribute flex="60" (parent of previous div) have height of 127px so the content of it overflows.

**Comment by EladBezalel** [comment]
Best solution [here](http://codepen.io/EladBezalel/pen/YWmbAa).
Your expectations is not aligned with how flexbox is working, i'd suggest you'll try [Flexbox Froggy](http://flexboxfroggy.com/) for understanding it better.
