### ISSUE TITLE
About the md - select + multiple problems

### ISSUE THREAD

**Issue by xiecg** [angular/material#9443]
Hi ~

DEMO: http://codepen.io/xiecg/pen/XKvGOP?editors=0010

Why is this so ?

<img src="http://ocm0knkb1.bkt.clouddn.com/DFFD915A-C112-41DA-B9BA-B4009CDD7D3C.png"/>

This is what I want !

<img src="http://ocm0knkb1.bkt.clouddn.com/QQ20160829-0@2x.png"/>

I am using version is 1.1.0

Multiple and I was not set to true !

thank

**Actual Behavior**:
-  `What is the issue? *`
-  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
-  `Details:`

**Angular Versions**: *
-  `Angular Version:`
-  `Angular Material Version:`

**Additional Information**:
-  `Browser Type: *`
-  `Browser Version: *`
-  `OS: *`
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by oemmes** [comment]
Hi, you should be using "track by" in your ng-repeat expressions.

See my comment here: https://github.com/angular/material/issues/9442#issuecomment-243696107

**Comment by EladBezalel** [comment]
@oemmes is that a dup?

**Comment by oemmes** [comment]
yeah, I think this issue is actually a "reply" to #9442

**Comment by Splaktar** [comment]
The author didn't respond to the suggested fix, so I am assuming that it worked. Closing this.
