### ISSUE TITLE
Virtual Repeat OrderBy in angular 1.5

### ISSUE THREAD

**Issue by dennieru** [angular/material#9444]
**Actual Behavior**:
 -  `OderBy is not working in virtual repeat (On demand) with Angular 1.5*`
 -  `Order By must be deprecated or re implemented in virtual repeat`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your [issue:`](http://codepen.io/dennieru/pen/WxVWvX)
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`1.5.8
 -  `Angular Material Version:`1.0.9

**Comment by DevVersion** [comment]
At first glance it seems to wrong to have a `orderBy` on a Virtual Repeat, which has `md-on-demand` enabled.

When using `md-on-demand` you are passing an object, which does not contain any values to be sorted.

Are you sure this worked before Angular 1.5?

**Comment by dennieru** [comment]
You are right @DevVersion, OrderBy  didn't work on virtual repeat there was a code line wrote by a naughty developer in my project that made me think that was functional.
I needed to add the possibility of sort in virtual-repeat, and I already resolved it.
Thanks

**Comment by bersoriano** [comment]
Hey @dennieru, how you solved the sorting in the virtual-repeat? I'm thinking about creating my own virtual repeat, but how did you fixed the issue?
