### ISSUE TITLE
Maximum layout width. 

### ISSUE THREAD

**Issue by Serhioromano** [angular/material#945]
I made a quick search in Google and here and could not find. 

Is it possible to set something like bootstrap container that will have maximum width with gradations according to monitor size? I have just started with material and I want to make my site 1200px max width on big monitors, 980px on smaller and so on. 

Is it possible with material? In my case it always only scale to full width 100%. If I use styles, then it is only ok for one monitor size. And create CSS with all medias for all sizes already looks overwork for out-of-the-box style framework.

So is it my lucky day?

**Comment by kumavis** [comment]
There is a certain column width after which it becomes difficult for humans to track what line of text they left off on when wrapping over, and so the max-width is useful for displaying article text. I second the suggestion that this be added to the vocabulary of material design.

**Comment by peluprvi** [comment]
Just for give another example for who are searching for this, my solution was:

```html
<md-toolbar layout="row" layout-align="center start">
  <div layout="row" flex class="layout-max-width">
    <md-button ng-click="toggleSidenav('left')" hide-gt-sm>
      <span>Menu</span>
    </md-button>
    <h1 class="md-toolbar-tools">Material Limited Width</h1>
  </div>
</md-toolbar>

<div layout="row" layout-align="center start">
  <div layout="row" flex class="layout-max-width">
    <md-content layout="column" flex class="md-padding" id="content">1200px Limited Width</md-content>
  </div>
</div>
```

```css
.layout-max-width {
  width: 100%;
  max-width: 1200px;
}
```

**Comment by kumavis** [comment]
@ThomasBurleson is there a commit associated with this or is this a #notfix?

**Comment by austin4perezident** [comment]
@peluprvi That fixed the problem, but now there is another problem with doing this. all of the content will now stay to the left of the view. How can you center your content? I tried layout-align="center" but that does not fix the problem.

**Comment by ThomasBurleson** [comment]
Our docs and sample demos have been significantly improved:

*  New [Layout Documentation](https://material.angularjs.org/HEAD/layout/introduction) - intro, details, options, troubleshooting
* New [CodePen Community](http://codepen.io/collection/XExqGz/) - Layouts Collection

**Comment by InvDeath** [comment]
Why we can't use common approach with max-width by breakpoints? 
Or percents instead of fixed size (bay particular gap) is right (better) way and I don't understand yet?
I see grid here http://www.google.com/design/spec/layout/responsive-ui.html#responsive-ui-surface-behaviors . 
Is related size better then fixed by screen?

**Comment by ThomasBurleson** [comment]
@InvDeath - Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)
