### ISSUE TITLE
mdInputMessageAnimation: messages not displayed correctly

### ISSUE THREAD

**Issue by daniel-nagy** [angular/material#9454]
**Actual Behavior**:
 -  `What is the issue? *`
  - Error messages are not removed when the input becomes valid.
 -  `What is the expected behavior?`
  - Error messages should disappear when the input becomes valid.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
  - This is reproducible on the main site.

![screen shot 2016-08-29 at 4 55 26 pm](https://cloud.githubusercontent.com/assets/1622446/18071472/fc279f54-6e0a-11e6-8274-87590f03bc22.png)

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: 1.1.0`

**Additional Information**:
 -  `Browser Type: Chrome (I would suspect others)`
 -  `Browser Version: 52.0.2743.116 (64-bit)`
 -  `OS: OS X`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by jcvpacheco** [comment]
- Error Message only appears, if user clicks on the field.
- Open Input codepen.io with "1.1.0-rc.5" and "1.1.0"The error appears when open for the first time "1.1.0-rc.5" and on "1.1.0", only appear if user click on the box.
- regular input type text with angularJS is working fine.
