### ISSUE TITLE
autocomplete: using option selection to trigger a dialog to be displayed causes conflicts

### ISSUE THREAD

**Issue by mortenmoulder** [angular/material#9456]
**Actual Behavior**:
-  `What is the issue?`
  - When opening a dialog after selecting an item in an md-autocomplete, the dialog appears but the search results won't disappear, unless you move the mouse away quickly. On touch devices it won't hide at all. This only occurs because the input of the md-autocomplete is cleared with `searchText = ""` - If the input is NOT cleared, the results disappears nicely as it should.
-  `What is the expected behavior?`
  - It should hide the search results when selecting an item no matter what. This should be useful for grabbing the last few entries in a database/list and displaying them quickly (because the `md-min-length` is set to 0).
    **CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` 
  - http://codepen.io/anon/pen/EgYKxV
-  `Details:` 
  - Click/press the md-autocomplete and select an item. Don't move the cursor. 
  - My theory is this: When the input is cleared/set to an empty string, the `md-items` (or some event) is triggered again, because the input has changed. Basically the same as removing the text in the input.

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:`  1.1.0

**Additional Information**:
-  `Browser Type: *` Chrome, Firefox, Internet Explorer
-  `Browser Version: *` latest on all
-  `OS: *` Windows and OS X
-  `Stack Traces:` 

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by DevVersion** [comment]
I'm going to merge #7802 into this issue, since it's more generic.

_Quote from here_
> Just investigated a bit and it seems to be pretty difficult to solve that, because we need to detect whether the dropdown should hide from the last interaction.

> Here is some code which works, but it is delayed, because the dialog focuses its element after animation.

> ```js
>  function blur () {
>    hasFocus = false;

>    if (!noBlur || notFoundVisible() && !isMouseInteraction) {
>      ctrl.hidden = shouldHide();
    }
  }
```

**Comment by Splaktar** [comment]
You can blur the autocomplete's input before setting the searchText to `""` in order to avoid the pop-up opening again. [Updated example CodePen](https://codepen.io/Splaktar/pen/rNBJvXM?editors=1010#0)
