### ISSUE TITLE
layout-align vertical center issue with IE11

### ISSUE THREAD

**Issue by jardilio** [angular/material#946]
There is a known issue in IE11 with flex and vertical center alignment, the issue is a result of IE not calculating height correctly.

https://connect.microsoft.com/IE/feedback/details/802625/min-height-and-flexbox-flex-direction-column-dont-work-together-in-ie-10-11-preview

My temporary solution in my case was to apply a CSS rule for [layout-fill] to use height:100% rather than just min-height:100%, this fixed the centering issue for me, but only if I'm using layout-fill in conjunction with layout-align.

You can see this broken in IE11 on the demo site here: https://material.angularjs.org/#/layout/alignment

If you inspect the flex container with layout-align and give it an explicit height, it will correctly vertically center.

Realizing that this is an IE issue, not sure if there is a better workaround solution that can be worked into material here to get around this since its a supported browser.

**Comment by ngraef** [comment]
Thanks for the bug report link, @jardilio. I just ran into this issue.

The demo site has changed since the original post and is no longer broken, so here's a codepen that shows the issue: http://codepen.io/anon/pen/WbmRwP?editors=101

**Comment by ThomasBurleson** [comment]
With the SHA 843d63ec5520d313eb327d2d99606e9f6177912e on master, You should be able to verify that the following works as expected using this [CodePen](http://codepen.io/ThomasBurleson/pen/pjbYmy?editors=101) (which using the latest HEAD ngMaterial and AngularJS 1.3.19 code).

> Please always test with the latest versions:
*  Angular Material HEAD
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.js
  *  Bower Install - https://github.com/angular/bower-material/blob/master/angular-material.css 
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.js
  *  RAWGIT - https://rawgit.com/angular/bower-material/master/angular-material.css
* AngularJS  Current
  *  Angular 1.3.19 (or greater)
  *  Angular 1.4.6 (or greater).
