### ISSUE TITLE
select: option text not truncating in certain layout configurations

### ISSUE THREAD

**Issue by jthomson-act** [angular/material#9460]
**Actual Behavior**:
-  `What is the issue? *` option text displayed in md-select components with attribute 'multiple' are not being truncated in certain layout situations (see below)
-  `What is the expected behavior?` Placing md-select inside md-input-container then housed inside a layout of column as default and specifying a layout of row for anything greater than small should not break the layout

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`http://codepen.io/Jackthomsonn/pen/ORLbEA?editors=1000
-  `Details:` We want to put two md-input-containers side by side both housing an md-select component which makes use of the 'multiple attribute'. These two input containers should work when being placed in a layout column for smaller devices and a layout row for larger devices. At the moment, the text does not truncate when this approach is used. Instead, the option text in the md-select continues to grow therefore increasing the width of the md-select input. This issue does not occur when using just layout="row" but then this makes the layout unresponsive.
  
  -_In the codepen, resize the preview window width so that in the second example, both inputs are in a row layout. You will see the first input demonstrates this issue._

**Angular Versions**: *
-  `Angular Version:` 1.5.0
-  `Angular Material Version:` 1.1.0

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 52
-  `OS: *` Windows 7
-  `Stack Traces:` N/A

**Comment by Splaktar** [comment]
It looks like this might have been a bug with Flexbox in Chrome. I can't reproduce this in Chrome 67, even using the same AngularJS Material version.
