### ISSUE TITLE
mdPanel: Document mdPanelAnimation

### ISSUE THREAD

**Issue by epelc** [angular/material#9465]
**Actual Behavior**:
 -  `What is the issue? *` mdPanelAnimate is only documented in an example and most likely does not include all methods.
 -  `What is the expected behavior?` Docs :)

See at the very bottom https://material.angularjs.org/latest/api/service/$mdPanel
![image](https://cloud.githubusercontent.com/assets/5204642/18106796/2ac1b98a-6ed3-11e6-8818-06e033db8f15.png)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ErinCoughlan** [comment]
@bradrich This is fully documented, but the ngdoc type is wrong so it's not showing up (should be "type", not "object").
https://github.com/angular/material/blob/master/src/components/panel/panel.js#L597

Then this will show up in the Types section next to MdPanelPosition and MdPanelRef.
