### ISSUE TITLE
fab-speed-dial: still triggers action when disabled

### ISSUE THREAD

**Issue by phongca22** [angular/material#9467]
**Actual Behavior**:
-  What is the issue? \* Add `ng-disabled="true"` into md-button in md-fab-trigger. This button is disabled but able to click.
-  What is the expected behavior? Prevent click.

**Angular Versions**: 
-  Angular Version: 1.5.8
-  Angular Material Version: 1.1.0

**Additional Information**:
-  Browser Type: Chrome
-  Browser Version: 52.0.2743.116
-  OS: Win 10 64 bit

[Demo](http://codepen.io/anon/pen/gwYZxV)

**Comment by topherfangio** [comment]
Yup, looks like the speed dial does not currently respect the `disabled` status. Will definitely fix.

**Comment by garretwilson** [comment]
See #7473. Workarounds not working.

**Comment by Splaktar** [comment]
Here's an [updated CodePen](https://codepen.io/Splaktar/pen/PrwWrO?editors=1010#0) that shows this is still an issue in `1.1.19`.
