### ISSUE TITLE
ng-message of md-autocomplete is invisible 

### ISSUE THREAD

**Issue by tom94zoe** [angular/material#9468]
**Actual Behavior**:
If you enter something  and remove it, a required error message was shown. 
If you try it a second time, the error message wasn't shown, because of the following style 

`md-input-container .md-input-message-animation:not(.ng-animate) {
    opacity: 0;
    margin-top: -100px;
}.`

**CodePen** (or steps to reproduce the issue): *
Used the floating label example of the demos

**Comment by DevVersion** [comment]
@topherfangio Is this related to the ngMessages issues we experience right now?

**Comment by topherfangio** [comment]
@DevVersion Not sure; it sounds related but I'm having trouble reproducing the issue.

@tom94zoe Can you please provide the link to our docs so we know what version you were testing against?

**Comment by tom94zoe** [comment]
I used the latest version 
https://material.angularjs.org/latest/demo/autocomplete

**Comment by topherfangio** [comment]
@tom94zoe I can't seem to produce this against latest or HEAD (which has my recent ng-messages fixes for input).

Can you help me better understand how to reproduce it? Also, can you test against https://material.angularjs.org/HEAD/demo/autocomplete to make sure it hasn't already been fixed?

**Comment by tom94zoe** [comment]
![nimbus-record-video](https://cloud.githubusercontent.com/assets/17591511/18194788/7f5bcb5e-70e8-11e6-8971-c353b0163bd3.gif)

I also tested it against the head. As you can see the error message is hidden.
Maybe I am missing something or cannot see it.

**Comment by topherfangio** [comment]
@tom94zoe Got it; thanks for the screenshot. I can definitely reproduce now.

At first guess, it might be related to the fact that the element actually has a value even though it's not one of the supplied options, so something with the `ng-required` might be getting confused.

**Comment by prateekchoudhary** [comment]
+1
