### ISSUE TITLE
Md-chips readonly="true" + md-removable="true" still editable

### ISSUE THREAD

**Issue by dennis8844** [angular/material#9471]
**Actual Behavior**:
 -  `What is the issue? *` when I have both attributes as true, the directive is not readonly, and the textfield behavior is applied.
 -  `What is the expected behavior?` I expect the textfield to not work, with no ability to add a chip that way, yet still remove, as what happens in the original codepen demo. 

**CodePenr** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` Used Plunker http://plnkr.co/edit/ldNAIkv0x4tBmunXMSi8?p=preview
 -  `Details:` still working out a way to remove via a checkbox... however, it is weird that this plunker is showing different behavior than the demo codepens

**Angular Versions**: *
 -  `Angular Version:`1.5.3 
 -  `Angular Material Version:` 1.1.0-rc2

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`52.0.2743.116 m
 -  `OS: *`Windows 8
 -  `Stack Traces:`

----
Shortcut to create a [new Plunker Demo]( http://plnkr.co/edit/ldNAIkv0x4tBmunXMSi8?p=preview).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by topherfangio** [comment]
This feature was not introduced until recently, but it looks like your Plunkr is using Material 1.1.0-RC2. Can you please update to the recent 1.1.0 (i.e. final) release?

If you still have issues after that, please post here and I will reopen.

**Comment by dennis8844** [comment]
Thanks Topher. That did get the behavior I was looking for, however it also removed the md-checkbox styling. See plunker now.

**Comment by DevVersion** [comment]
@dennis8844 You did not update the Stylesheet of Angular Material to `v1.1.0`.

**Comment by cmacdonnacha** [comment]
I'm still seeing this issue but only when running our app in production mode. (i.e minfied js, css and html). 

`$mdChipsCtrl.readonly ` seems to be set to false even though it's been set to true in the html.

```
  <md-chips ng-model="attachments" readonly="true" md-removable="false" flex>
    <md-chip-template>
      {{ ::$chip.name }} ({{::convertFormatSize($chip.size)}})
    </md-chip-template>
  </md-chips>
```

**Comment by topherfangio** [comment]
@cmacdonnacha I'm not positive if this is the issue, but I seem to remember that some minifiers do not play well with Angular's version of `readonly` as it will remove the `="true"` part which makes Angular think it's false.

I believe you can work around this by using `ng-readonly="true"` which will set the attribute to `readonly="readonly"` for you and will thus work with the minifier.

Can you give that a try and report back?

**Comment by topherfangio** [comment]
@cmacdonnacha Any chance you can reproduce this in a Codepen?

**Comment by cmacdonnacha** [comment]
Hi @topherfangio,

I finally found the issue, we are using [this](https://github.com/gruntjs/grunt-contrib-htmlmin) html minifier which collapses boolean attributes like **readonly**. After setting the option **collapseBooleanAttributes** to false it's fixed the issue. 

Thanks for guiding me towards the fix. 

Cathal.

**Comment by topherfangio** [comment]
Awesome, glad you got it resolved!

**Comment by ashwinmahesh** [comment]
I'm using the same grunt minifier as cmacdonnacha and I set the collapseBooleanAttributes to false but I still have the same issue. The chips are not removable but I can still add chips instead of them being disabled. 

![image](https://user-images.githubusercontent.com/6790143/31235481-a51c3b1a-a9bf-11e7-90a6-ed9cc29e0f22.png)
