### ISSUE TITLE
md-tooltip within SVG (feature request)

### ISSUE THREAD

**Issue by djfd** [angular/material#9478]
Hi,

currently md-tooltip wont work if placed inside SVG graphics. We can make it working there as shown below:

```html
<svg>
    ...
    <g>
        <rect />
        <foreignObject>
            <md-tooltip>tooltip contents</md-tooltip>
        </foreignObject>
    </g>
    ...
</svg>
```

and in tooltip code (after https://github.com/angular/material/blob/master/src/components/tooltip/tooltip.js#L74) make small addition:

```js
if (parent[0].localName === 'foreignObject') {
    parent = parent.parent(); // or $mdUtil.getParentWithPointerEvents(parent)
}
```
Why to wrap. If not wrapped in foreignObject, then tooltip internal divs have all metrics set to zero, setting widths, heights etc does not work. Maybe it is correct behaviour of JS maybe not, I do not know.

Kindly check http://codepen.io/djFD/pen/ALAZzk
This works in firefox but Chromium is failed because of a kind of bug https://bugs.chromium.org/p/chromium/issues/detail?id=643044 (wl-tooltip has parent's invisibility watchdog based on JQuery https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/css/hiddenVisibleSelectors.js#L11). Original md-tooltip does not have such check so  it is expected to work fine in Chromium too.

**Comment by EladBezalel** [comment]
Can you please provide a codepen so we can investigate more?

**Comment by djfd** [comment]
sorry, pasted wrong link, there is correct one http://codepen.io/djFD/pen/ALAZzk

**Comment by djfd** [comment]
ok, there is simplified version http://codepen.io/djFD/pen/qaBrbL

**Comment by djfd** [comment]
well, there is another approach, using an intermediate directive (codepen is the same, extended a few)
```js
.directive('svgTooltip', ['$compile', function($compile) {
    return {
        scope: false,
        restrict: 'E',
        transclude: 'element',
        link: function(scope, el, attr, dummy, $tfn) {
            $tfn(scope, function(clone) {
                var tooltip = angular.element('<md-tooltip>' + clone.html() + '</md-tooltip>');
                angular.forEach(attr.$attr, function(name, key) { tooltip.attr(name, attr[key]); });
                el.parent().append(tooltip);
                $compile(tooltip)(scope);
            }, el.parent());
            el.remove();
        }
    };
}])
```
thus no changes are required in original tooltip code at all, but possible it need to be standard tooltip behaviour, depending on calling context (HTML,SVG) provide such functionality automatically?

**Comment by djfd** [comment]
well, I think it is related to https://github.com/angular/angular.js/issues/15092, so if it will be accepted and resolved then all will start working just for free

**Comment by ThomasBurleson** [comment]
will not fix in Angular Material 1.x
