### ISSUE TITLE
max date with datepicker

### ISSUE THREAD

**Issue by mouhsine123** [angular/material#9479]
**Actual Behavior**:
 -  `What is the issue? 
Datepicker with only md-max-date does not work properly.`
 -  `What is the expected behavior?
 Clicking on the month headers does not give the correct values.  Also we can navigate upto year 1983 only - we cannot go beyond that`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue: http://codepen.io/mouhsine/pen/GjRRmL`
 -  `Details: Click on the month headers - max date not working + can navigate to years upto 1983(can not go beyond that)`

**Angular Versions**: *
 -  `Angular Version: 1.5.7`
 -  `Angular Material Version: 1.1.0`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 52.0.2743.116 m`
 -  `OS: windows 7`

**Comment by mouhsine123** [comment]
![capture](https://cloud.githubusercontent.com/assets/11781298/18156634/ad52e22e-7028-11e6-9e9d-c50a65ada621.JPG)

**Comment by crisbeto** [comment]
The approach to dealing with the min/max dates was changed recently (https://github.com/angular/material/pull/9309) and it seems like it fixed this issue as well. [Here's a forked codepen that uses the code from master.](http://codepen.io/crisbeto/pen/jrOyRy) The fix should land soon with 1.1.1.
