### ISSUE TITLE
Feat (md-nav-item) : Add an option for settings the uisref options

### ISSUE THREAD

**Issue by stochris** [angular/material#9481]
**Actual Behavior**:
 -  `What is the issue? *`
There is no way to set the ui-sref options on an md-nav-item
 -  `What is the expected behavior?`
There should be a way to set the ui-sref options on md-nav-item

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.57
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

If that's ok with you, I could do a PR adding this feature ( it's pretty trivial )

**Comment by bradrich** [comment]
@stochris I apologize about the late response to your issue. Please refer to the [directives information for `md-nav-bar`](https://material.angularjs.org/latest/api/directive/mdNavBar).

There you will see that because the `md-nav-bar` deals with page navigation, certain routing concepts are built-in. Route changes via `ng-href`, `ui-sref`, or `ng-click` events are supported.

To use the `ui-sref` event for your navigation item, simply put the attribute `md-nav-sref` on your `md-nav-item` element, with its value being your `ui-router` state.

If you need a pen with this demonstrated, please let me know.

**Comment by stochris** [comment]
Thank you for your response.
However, I'm talking about the ui-sref-opts directive, which can be used to
change how the ui-sref will transition.
If I get around to it, I will do a pull request adding it

**Comment by bradrich** [comment]
@stochris Ah, I understand. I will look into this and get back with you ASAP.

**Comment by sonalishirodkar** [comment]
i want to know how to make md-nav-bar responsive? in mobile device?

**Comment by sonalishirodkar** [comment]
<div class="card-body">
            <md-nav-bar md-selected-nav-item="urlState.current.name" nav-bar-aria-label="navigation links">
                <md-nav-item md-nav-click="openTab(jobSeekerAndApplicationDetailsState.profile)" name="{{jobSeekerAndApplicationDetailsState.profile}}">
                    Profile  
                </md-nav-item>
                <md-nav-item md-nav-click="openTab(jobSeekerAndApplicationDetailsState.assessment)" name="{{jobSeekerAndApplicationDetailsState.assessment}}">
                    Assessment Tests
                </md-nav-item>
                <md-nav-item md-nav-click="openTab(jobSeekerAndApplicationDetailsState.videointerview)" name="{{jobSeekerAndApplicationDetailsState.videointerview}}">
                    Video Interview
                </md-nav-item>
                <md-nav-item md-nav-click="openTab(jobSeekerAndApplicationDetailsState.livevideodiscussion)" name="{{jobSeekerAndApplicationDetailsState.livevideodiscussion}}">
                    Live Video Discussion
                </md-nav-item>
            </md-nav-bar>
            <div class="ext-content fl-md-min-height">
                
                <div ui-view></div>
            </div>
        </div>

**Comment by sonalishirodkar** [comment]
can any1 help me ASAP
