### ISSUE TITLE
Feat (md-tooltip): Add ability to display tooltip only when content is overflowed.

### ISSUE THREAD

**Issue by MigFerreira** [angular/material#9482]
I have developed this improvement on the tooltip and want your opinion if its ok for a pull request or not.

Basically i added the md-overflow attribute to the directive, then each time you request to display the tooltip it clones the parent as absolute without width limitations and compares it to the original.

```javascript
function isOverflowing(){
        var clone = parent.clone();
        clone[0].style.maxWidth = '';
        clone[0].style.visibility = 'hidden';
        clone[0].style.position = 'absolute';
        parent.parent().append(clone);
        var isOverflow = clone[0].offsetWidth > parent[0].offsetWidth;
        clone.remove();
        return isOverflow;
    }

    function showTooltip() {
      //  Do not show the tooltip if the text is empty.
      if (!element[0].textContent.trim()) return;

      // Insert the element and position at top left, so we can get the position
      // and check if we should display it
      element.css({top: 0, left: 0});
      tooltipParent.append(element);


      if(scope.overflow!=void 0 && !isOverflowing()){
        scope.visible = false;
        element.detach();
        return;  
      }  
      ...   
 }
```

I plan to improve this, just not sure im taking the right approach. 

Any opinions on this?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)

> Note: it may be 'costly' to clone the parent. We will not add this feature to ngM1.x
