### ISSUE TITLE
<md-datepicker> flex

### ISSUE THREAD

**Issue by inromualdo** [angular/material#9483]
**Actual Behavior**:
 -  `<md-datepicker> just take place need*`
 -  `<md-datepicker flex> or <md-input-container flex>
    <md-datepicker>
  </md-input-container> not work`

**Angular Versions**: *
 -  `Angular Version:1.5.5`
 -  `Angular Material Version: 1.1.0`

**Additional Information**:
 -  `Browser Type: npm*`
 -  `Browser Version: *`
 -  `OS: Ubuntu*`
 -  `Stack Traces:`

**Comment by crisbeto** [comment]
This behaviour is not supported, because it can cause the input to "stick out" beneath the calendar, if the container is too wide. You should be able to force it to stretch in your custom CSS.
