### ISSUE TITLE
mdColors: md-icon in md-toolbar doesn't have correct color

### ISSUE THREAD

**Issue by norkunas** [angular/material#9485]
**Actual Behavior**:
 -  `What is the issue? *` md-icon in md-toolbar doesn't have correct color 
 -  `What is the expected behavior?` md-icon should have the same color as text in md-toolbar

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/norkunas/pen/ozNxWB
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

**Comment by EladBezalel** [comment]
@norkunas this seems to be a dup of #9435, there's an override over there that you can apply at your css that will make `md-icon` automatically inherit its wrapper color
