### ISSUE TITLE
mdTabs RTL behaviour

### ISSUE THREAD

**Issue by NaNgets** [angular/material#9487]
mdTabs in RTL mode is a bit broken:
* Next and previous buttons aren't working,
* Swipe (if enabled) is working in the opposite direction.

http://codepen.io/anon/pen/EgxyAL
(change the screen size so it would have pagination)

(with Angular 1.5.8 and Angular Material 1.1.0)

**Comment by topherfangio** [comment]
Duplicate of #9292. Should be fixed by #9301 when it gets merged.

**Comment by anilk533** [comment]
RTL direction for material tabs not working.
here is the issue.
https://codepen.io/djidel/pen/NpMpmY

please let me know how to solve

thank you
