### ISSUE TITLE
Theming is broken for custom theme rules

### ISSUE THREAD

**Issue by DevVersion** [angular/material#9488]
The theming seems to be broken  with the new NanoCSS changes.

Culprits are NanoCSS and the theming service itself.

**Comment by DevVersion** [comment]
See #9484

**Comment by houmark** [comment]
Is there a reason for using NanoCSS - did you consider [CSSO](https://github.com/ben-eb/gulp-csso)? According to a benchmark I saw gulp-csso outperforms more or less all of the contenders in most situations.

**Comment by jex310** [comment]
Hi, please take a look also in this [plunkr](http://codepen.io/jex310/pen/YGqwGE). Try to hover on green button. Notice that it goes back to defaulted colour not on the themed colour.

**Comment by DevVersion** [comment]
@jex310 This seems to not relate to the NanoCSS changes we've made.

Closing this issue now, since the PR has been merged.
