### ISSUE TITLE
mdDatepicker: IE11 does not detect typed changes

### ISSUE THREAD

**Issue by jonahbron** [angular/material#9489]
**Actual Behavior**:
 -  Modifying the date by typing a different one does not work in IE11.  The model value is not updated.
 -  Typing a new date should behave just like using the calendar date picker, the model should be updated.

**CodePen (and steps to reproduce the issue)**:
 - http://codepen.io/jonahbron/pen/wzvJYq
 - Type a different date in IE11
 - See model has not changed

**Angular Versions**:
 -  Angular Version: 1.5.5
 -  Angular Material Version: 1.1.0

**Additional Information**:
 -  Browser Type: IE
 -  Browser Version: 11
 -  OS: Windows

Note that typing and the calendar selection work fine in Chrome, and the calendar date selection only (not typing) works in IE11.

**Comment by crisbeto** [comment]
Seems to be worked for me:

![a](https://cloud.githubusercontent.com/assets/4450522/18184400/386f1de4-7099-11e6-9f2c-15c34f8cab5e.gif)

**Comment by jonahbron** [comment]
Darn it, you're right.  I tried it again myself, and now it's working???  Sorry about that.
