### ISSUE TITLE
feat($mdDialog): Add support for components

### ISSUE THREAD

**Issue by maxjoehnk** [angular/material#9495]
**Actual Behavior**:
 -  `What is the issue? *`

Currently there is no support for the usage of an angular component as the root of a dialog.
Proposed Usage:
```
$mdDialog.show({
  component: 'fooBar'
}).then(() => ...);
```

This would be a very handy feature, although I guess it won't work atm because of the lacking support for components in general.

Note:
Duplicate of [this comment](https://github.com/angular/material/issues/8409#issuecomment-220759188) but I feel like this should be its own feature request.

**Comment by DevVersion** [comment]
Thanks for the issue - you are right, this is currently not possible due to the versions we currently support.

Nevertheless we already have several issues for that and I'd like to close this issue in favor of  #8409 (#8474, #9259).
