### ISSUE TITLE
select: performance in IE

### ISSUE THREAD

**Issue by ricardovicenteagoraplus** [angular/material#9499]
**Actual Behavior**:
-  `What is the issue?` Some angular material components, such as md-select are very slow, in terms of performance,  in IE11 and Edge, if compared with Chrome and Firefox.
-  `What is the expected behavior?` The performance between browsers should be equivalent.

**CodePen** (or steps to reproduce the issue): *
-  `Link were the issue can be tested:` https://ricardo.agoraplus.fr/elancourt/pck_wf_process.home_view#/testApagar
-  `Details:` Open and close the countries drop down in the mentioned browsers. Please note that the component shown is an Angular directive that has some Angular material components, such as an md-select.

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.1.0

**Additional Information**:
-  `Browser Type:` Internet Explorer, Edge
-  `Browser Version:` IE11, Edge
-  `OS:` Windows 7/10

**Comment by ThomasBurleson** [comment]
Related to #8861

**Comment by topherfangio** [comment]
@ricardovicenteagoraplus The URL you supplied appears to be inaccessible. Can you please provide a Codepen instead which uses only Material components so that we can see the issue better?

**Comment by kefimo** [comment]
Any news? i have the same problem . There is a solution or a bypassing solution??

**Comment by Splaktar** [comment]
FYI, we have added a new [IE11 Performance Guide](https://material.angularjs.org/latest/performance/internet-explorer) that should help mitigate this.

I'm going to close this as no demo was provided as requested. We are still tracking some select performance issues in https://github.com/angular/material/issues/8861.
