### ISSUE TITLE
Common md-block principles. Do they exits?

### ISSUE THREAD

**Issue by brutto** [angular/material#950]
AMT awesome! But I found many things do not work properly if they used not like in tutorial examples.
For example md-tollbar or md-subheader have it's own hard to understand rules for described functionallity. 

Mabe there are any common rules for building with such elements? For example height always must be set or smth like this?

**Comment by ThomasBurleson** [comment]
This is a great forum question.  Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial).

> The response could then be included in a starter project and our new 'Getting Started' online docs.
