### ISSUE TITLE
checkbox: Add margin-top

### ISSUE THREAD

**Issue by epelc** [angular/material#9500]
**Actual Behavior**:
 -  `What is the issue? *``md-checkbox` has no `margin-top` only `margin-bottom/right`.
 -  `What is the expected behavior?` It should have margin on the top so it is centered when in toolbars and in several other situations. Semi related #6387

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/ORJELj
 -  `Details:` using md-checkbox in various ways within a toolbar. The fix is to add `margin-top: 16px;` while the md-checkbox is within a toolbar. I'm not sure if it should be added elsewhere too.
![image](https://cloud.githubusercontent.com/assets/5204642/18209121/664fecea-7100-11e6-9b96-28912abc16f8.png)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *` 52
 -  `OS: *` osx 10.11.1
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by clshortfuse** [comment]
It's works better if we strip vertical margins when in toolbars.
```
.md-toolbar-tools {
  md-checkbox {
    margin-top: 0px;
    margin-bottom: 0px;
  }
}
```

**Comment by clshortfuse** [comment]
Actually, `auto` would be better so we don't reduce touch target size. I'll have to do some testing wtih with IE on compatibility with `margin-bottom` in flexboxes.
```
.md-toolbar-tools {
  md-checkbox {
    margin-top: auto;
    margin-bottom: auto;
  }
}
```
