### ISSUE TITLE
Toast + $emit unable to communicate

### ISSUE THREAD

**Issue by xiecg** [angular/material#9508]
hi~

DEMO: [http://codepen.io/xiecg/pen/PGoXNP](http://codepen.io/xiecg/pen/PGoXNP)

I'm in ToastCtrl `$scope.$emit('apply', 'test');`

When users click the close button， 

In the AppCtrl `      $scope.$on('apply', function(e, data){
        alert(data);
      });` Did not perform

why ?

**Actual Behavior**:
 -  `What is the issue? *`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
`$emit` dispatches an event up through the DOM tree. This means that if `ToastCtrl` is not a child of `AppCtrl, `AppCtrl` won't get notified. You can try a different approach and use `$broadcast` on the `$rootScope` instead.

**Comment by xiecg** [comment]
@crisbeto 

Thanks for your reply！

I don't want to use `$rootScope`,  Because of his maintenance cost is higher , 

I need to use `    scope.$on('$destroy', function() { ... })`,  Is too much trouble ...


I use `$broadcast `,  And have no effect .

why ?

**Comment by crisbeto** [comment]
Most likely because the `ToastCtrl` isn't a child of `AppCtrl`. This means that any events from `ToastCtrl` won't get propagated to `AppCtrl`.

**Comment by EladBezalel** [comment]
@xiecg please ask those kind of questions in our [Forums](https://groups.google.com/forum/#!forum/ngmaterial)
