### ISSUE TITLE
$mdUtil getClosest() failed to find nearest <svg /> node

### ISSUE THREAD

**Issue by djfd** [angular/material#9509]
**Actual Behavior**:
 -  `What is the issue? *`Enclosing <SVG /> node not found
 -  `What is the expected behavior?`expected to be found

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/djFD/pen/qaBrbL (please check console outpiut)
 -  `Details:` Tested in two browsers, firefox and chromium, all SVG internal nodes (including svg itself) have their nodeNames in lowercase (HTML nodenames are in uppercase), and there is a code https://github.com/angular/material/blob/master/src/core/util/util.js#L511 that converts expected parent node to uppercase. 

However nodes' localNames are in lowercase, maybe need to check lowercased target against of localName property?

**Angular Versions**: *
 -  `Angular Version:`1.5.7
 -  `Angular Material Version:`1.1.0

**Additional Information**:
 -  `Browser Type: *`firefox/chromium
 -  `Browser Version: *`48.0/51.0.2704.79
 -  `OS: *`linux
 -  `Stack Traces:`--

**Comment by crisbeto** [comment]
Nice catch, I'll patch the method in Material. Until it gets released, you can work around it yourself by passing in a function to `getClosest`:

```js
$mdUtil.getClosest(el, function(parent) {
  return parent.nodeName.toLowerCase() === 'lower-case-name-goes-here';
}, true))
```
