### ISSUE TITLE
mdRadioGroup - Issue with ng-change for the radio button

### ISSUE THREAD

**Issue by Autushka** [angular/material#951]
I use  v0.6.1. When I try to use ng-change derective for the radio button  like:

<md-radio-button  ng-change="onResetTypeChange()" value="userName">{{'forgotPassword_userName' | translate}}</md-radio-button>

I'm getting an error in the concole:
 Error: [$compile:ctreq] http://errors.angularjs.org/1.3.6/$compile/ctreq?p0=ngModel&p1=ngChange

Br, Aleh

**Comment by STOpandthink** [comment]
Documentation is incorrect. ngChange is listed as belonging to md-radio-button: https://material.angularjs.org/latest/api/directive/mdRadioButton

**Comment by AliPoder** [comment]
+1

**Comment by ChidoYo** [comment]
I cannot get the ng-change in the md-radio-group tag to respond. The nd-model is in the md-radio-group. If I move the ng-change to the md-radio-button then I get this error: Error: [$compile:ctreq] Controller 'ngModel', required by directive 'ngChange', can't be found!

**Comment by jascination** [comment]
+1 to @STOpandthink, thankfully I found this thread as I've been banging my head against the wall trying to work this out!

**Comment by yannicklerestif** [comment]
+1.

**Comment by cchen408** [comment]
+1

**Comment by chris-carrington** [comment]
+1

**Comment by bentaly** [comment]
I noticed this too, still an issue after a few months
