### ISSUE TITLE
contextMenu: implement a right-click popup context menu (desktop) component

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material#9511]
A right-click popup menu component should be implemented. This popup should support cascaded menus similar to the menus in the menu bar. 

> Desktop only. 

![contextmenu](https://cloud.githubusercontent.com/assets/210413/18224775/3c66829e-71a6-11e6-9bbe-a54e5dc13816.png)

---

See @lumalav [ContextMenu CodePen](http://codepen.io/lumalav/pen/pEokVE?editors=1111) for initial usage.

**Comment by EladBezalel** [comment]
@ThomasBurleson IMO this should be developed after `md-menu` has been converted to panel.

**Comment by hanu18** [comment]
We need Context Menu in our project, please help me how can i leverage menu(mdMenu) for that.
It will need support for scroll, sub menu, dynamic menu item creation.

**Comment by EladBezalel** [comment]
@hanu18 i'd suggest you to figure how `panel` is working, and recreate the menu for that manner.

**Comment by Splaktar** [comment]
We have no plans to implement this in AngularJS Material. This is being tracked in https://github.com/angular/material2/issues/5007 for inclusion into Angular Material.
