### ISSUE TITLE
the ink bar is not visible when md-tabs is fixed positioned

### ISSUE THREAD

**Issue by bvahdat** [angular/material#9515]
**Actual Behavior**:
 -  `What is the issue?` The ink bar of a selected tab is not visible when `md-tabs` is positioned `fixed`, neither at it's bottom nor on it's top.
 -  `What is the expected behavior?` Expect to see the ink bar of the selected tab. The best in my case would be on top of the selected tab (not bottom). Maybe even provide an API for this purpose to decide if on top or bottom? See also this [SO question and the working answer for it](http://stackoverflow.com/questions/38442876/angular-material-tabs-ink-bar-on-top)

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://codepen.io/bvahdat/pen/LREpLZ
 -  `Details:`Please note that I've positioned the tab with `bottom: 5px;` so one can see if the ink bar is maybe visible at bottom of the selected tab (which is not)

**Angular Versions**: *
 -  `Angular Version:`1.5.8
 -  `Angular Material Version:`1.1.1

**Additional Information**:
 -  `Browser Type: *`Version 53.0.2785.89 (64-bit)
 -  `Browser Version: *`Chrome
 -  `OS: *`OS X
 -  `Stack Traces:`N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EladBezalel** [comment]
Simply wrap it within a div. [demo](http://codepen.io/EladBezalel/pen/mAyExa/)

**Comment by bvahdat** [comment]
@EladBezalel Thanks for this easy fix!

I'm just curious to understand why it needs an extra div to work. As when on top there's no need for this.

**Comment by EladBezalel** [comment]
ink-bar calculations are based on the tabs position, that's why you need to wrap it..
