### ISSUE TITLE
md-sidenav inside a directive/components is not correctly displayed

### ISSUE THREAD

**Issue by CaptainYouz** [angular/material#9524]
**Actual Behavior**:
 -  `What is the issue? *` When putting `md-sidenav` inside a directive/component, the render is not working correctly, the sidenav does not have a full height.
 -  `What is the expected behavior?` The expected behavior is that `md-sidenav` should have a 100% height.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [codePen demo](http://codepen.io/captainyouz/pen/NRPpov)
 -  `Details:` Strange thing that i noticed, is that if we remove `ngMaterial` dependency of the angular app, it is working fine.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` Version 52.0.2743.116 (64-bit)
 -  `OS: *` OS X Yosemite
 -  `Stack Traces:` 

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Tbutnyakov** [comment]
@CaptainYouz you can use "layout-fill" inside your container. 

```
<md-sidenav layout-fill class="md-whiteframe-2dp" md-component-id="left-side-nav" md-is-locked-open="$mdMedia('gt-md')">
      This is a sidenav
    </md-sidenav>
```

And it will work correctly:)

**Comment by Tbutnyakov** [comment]
But actually yes - we have a problem with framework inside component. 
For example i have app.component as entry point of app aaaand...it will work very strange))

```
<body>
  <app></app>
</body>
```

inside **app** component:

```
<header></header>
<div layout="row" layout-fill>
    <md-sidenav flex="15"  md-is-locked-open="true" class="md-whiteframe-z1">
      <md-content>
        sidenav
      </md-content>
    </md-sidenav>
    <md-content flex>
      <div layout="column" flex>
        <div ui-view="left_side"></div>
        <div ui-view="right_side"></div>
        <div ui-view="center"></div>
      </div>
    </md-content>
</div>
```

For example flex integer value in sidenav  can't understand nothing except 10, 15 and 30 XD
I can't callibrate width for it. And...sidenav will not render with 100% display height...

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)

**Comment by vishalkrv** [comment]
Here is the link to solved demo : http://codepen.io/camden-kid/pen/LREyzN
