### ISSUE TITLE
mdAutocomplete: do not hide the X button

### ISSUE THREAD

**Issue by Serabass** [angular/material#9525]
Please, do not hide the X button in md-autocomplete. It's not comfortable where I typing the text in it.

I've tried to modify this angular-material.js' line
angular-material.js:24806
```html
ng-if="$mdAutocompleteCtrl.scope.searchText && !$mdAutocompleteCtrl.isDisabled"
```
to
```html
ng-disabled="!$mdAutocompleteCtrl.scope.searchText || !!$mdAutocompleteCtrl.isDisabled"
```
And it became a more comfortable.

Or make it as option (e.g. &lt;md-autocomplete ... hide-button="**whenEmptyOrDisabled | never | etc**"&gt;)

**Comment by DevVersion** [comment]
I think this can be a nice enhancement - I have a new attribute in mind, but I can't think of any good name yet.

**Comment by Serabass** [comment]
@DevVersion what about hide-close-button-when="emptyOrDisabled | onlyEmpty | onlyDisabled | never"?

**Comment by ThomasBurleson** [comment]
@DevVersion - this should be a provider configuration IMO.

**Comment by DevVersion** [comment]
@Serabass Thank you for the issue.

We recently had a chat in the team about the size of the public API for the `md-autocomplete` component and we considered the API as too big.

At the moment we won't be able to add such enhancement to the autocomplete API, but we will consider alternate approaches to solve this.

In meanwhile I'm going to close this issue. Thanks again.
