### ISSUE TITLE
input-container: added class md-icon-left when it has md-icon with ng-if false

### ISSUE THREAD

**Issue by omar10594** [angular/material#9529]
**Actual Behavior**:
-  `What is the issue? *` mdInputContainer has class md-icon-left if has mdIcon with ngIf that start on false.
-  `What is the expected behavior?`First ngIf remove mdIcon and after the mdInputContainer directive should check if has an icon, and add or not the class.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` 
  - angular-material 1.1.0: http://codepen.io/omar10594/pen/YGPaav
  - angular-material 1.1.1: http://codepen.io/omar10594/pen/ORPvvq
-  `Details:`On version 1.1.0 had the expected behavior.

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

Related to: #8925 

I think is because the icon placement logic was move to the compile function. #9155.

**Comment by clshortfuse** [comment]
You can work around this issue by using `ng-show` instead of `ng-if`. I will see if we can improve the md-icon-class detection process and add support for `ng-if`.

**Comment by omar10594** [comment]
Since I created this issue, we use this decorator as a workaround.

```ts
angular.decorator('mdInputContainerDirective', mdInputContainerDirectiveDecorator);

function mdInputContainerDirectiveDecorator($delegate: any, $mdTheming: Function): any {
	const INPUT_TAGS: string[] = ['INPUT', 'TEXTAREA', 'SELECT', 'MD-SELECT'];

	const LEFT_SELECTORS: string = INPUT_TAGS.reduce<string[]>(function (selectors: string[], isel: string): string[] {
		return selectors.concat(['md-icon ~ ' + isel, '.md-icon ~ ' + isel]);
	}, []).join(',');

	const RIGHT_SELECTORS: string = INPUT_TAGS.reduce<string[]>(function (selectors: string[], isel: string): string[] {
		return selectors.concat([isel + ' ~ md-icon', isel + ' ~ .md-icon']);
	}, []).join(',');

	const postLinkFunction: (scope: ng.IScope, element: JQuery) => void = function (scope: ng.IScope, element: JQuery): void {
		$mdTheming(element);

		const leftIcon: Element = element[0].querySelector(LEFT_SELECTORS);
		const rightIcon: Element = element[0].querySelector(RIGHT_SELECTORS);

		if (leftIcon) { element.addClass('md-icon-left'); }
		if (rightIcon) { element.addClass('md-icon-right'); }
	};

	$delegate[0].compile = function (): (scope: ng.IScope, element: JQuery) => void {
		return postLinkFunction;
	};

	return $delegate;
}
```

Reverts the changes made to input.js on #9155

**Comment by Splaktar** [comment]
I believe that [this CodePen](https://codepen.io/Splaktar/pen/qMVxZB?editors=1010#0) demonstrates the fix.

For `ng-show`, the space for `.md-icon-left` will be preserved.
For `ng-if`, the space for `.md-icon-left` will not be preserved if the `md-icon` isn't initially visible. If the developer wants to toggle the value of this `ng-if`, then they will need to add `ng-class="{'md-icon-left': showIcon}"` to the `md-input-container`.

Please let me know if this doesn't handle an edge case that you think that we should handle.

**Comment by Splaktar** [comment]
It looks like that fix breaks the fix to textareas from https://github.com/angular/material/pull/9155.
