### ISSUE TITLE
Minify angular-material 1.1.0

### ISSUE THREAD

**Issue by laurindofljunior** [angular/material#9530]
**Actual Behavior**:
 -  `What is the issue? *`
 - The minified version was broken. Minify angular-material using Gulp.
 -  `What is the expected behavior?`
 - The behavior in Development should be the same as the Production.

---

 -  `Details:`

***Development***
After minify the angular-material using Gulp and Bower, the stylesheet was broken.
In developer mode, not using minify version, the result is:

![button developer](https://cloud.githubusercontent.com/assets/5683072/18256084/fc960ef4-7386-11e6-90dc-49fa2d08c475.Gif)
![select mult developer](https://cloud.githubusercontent.com/assets/5683072/18256091/15b38e0c-7387-11e6-8e4a-57148a92e43a.Gif)
![swticher normal](https://cloud.githubusercontent.com/assets/5683072/18256092/15c2f28e-7387-11e6-82c5-5eb489e58776.Gif)

***Production***

After minify using Gulp, the result is:

![swticher minified](https://cloud.githubusercontent.com/assets/5683072/18261291/a2dc5b70-73cc-11e6-8baf-51868de2299e.Gif)
![button minified](https://cloud.githubusercontent.com/assets/5683072/18261292/a2ded7b0-73cc-11e6-97e2-a49a163bae1a.Gif)
![select mult minified](https://cloud.githubusercontent.com/assets/5683072/18261293/a2df051e-73cc-11e6-8408-e69b186941e5.Gif)

---

**Angular Versions**: *
 -  `Angular Version:` 1.5.6
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *` 53.0.2785.89 m (64-bit)
 -  `OS: *` Microsoft Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
Closing as fixed. Please report if this bug persists after you upgrade to v.1.1.1.
