### ISSUE TITLE
md-min-length="0" on autocomplete does not work when used inside md-chips

### ISSUE THREAD

**Issue by arthursouviron** [angular/material#9540]
**Actual Behavior**:
 -  md-min-length="0" on autocomplete does not work when used inside md-chips
 -  Should show result on focus

**CodePen** (or steps to reproduce the issue): *
 -  http://codepen.io/arthur_souviron/pen/RGPNdN
 -  Focus on the input without typing anything, nothing happens.

**Angular Versions**: *
 -  `Angular Version:`V1.5.5
 -  `Angular Material Version:` V1.1.1

**Additional Information**:
 -  `Browser Type: *`Chrome 52.0.2743.116 (64-bit)

----

**Comment by DevVersion** [comment]
This has been already fixed with #9291. Though you need to remove the filter to be able to show some results when the query is empty.

See http://codepen.io/DevVersion/pen/XjbaBE
