### ISSUE TITLE
Can't disable `multiple` attribute mdSelect with parameter

### ISSUE THREAD

**Issue by dorcohen8** [angular/material#9541]
**Actual Behavior**:
-  `What is the issue? *`
  Can't disable multiple attribute on angular material mdSelect when trying to use parameter

The following is working:
<md-select ng-model="size"
           multiple="false">

But the following doesn't:
HTML:
<md-select ng-model="size"
           multiple="isMultiValue">
JS:
$scope.isMultiValue = false;
-  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  Example: http://codepen.io/anon/pen/wzaGKd?editors=1010#anon-login
-  `Details:`

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.1

**Additional Information**:
-  `Browser Type: *`
-  `Browser Version: *`
-  `OS: *`
-  `Stack Traces:`
---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by DevVersion** [comment]
You need to use the `ng-multiple` attribute instead. 

> `multiple` without the `ng-` prefix, means that this is not a data binding.
