### ISSUE TITLE
VirtualRepeat: Multiple large lists inside single container

### ISSUE THREAD

**Issue by yugandhar23** [angular/material#9542]
I have scenario where container has 3 sections containing large lists. Also this sections have sticky header. All 3 sections have same parent container scroll. How can I use md-virtual-repeat for this case ?

**Comment by DevVersion** [comment]
Please ask such a question in the the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial), because GitHub is only for issues and feature requests.
