### ISSUE TITLE
md-datepicker month and year only mode

### ISSUE THREAD

**Issue by mikeycgto** [angular/material#9544]
Would be useful for credit card forms when selecting the expiration date. The resulting input value would be formatting like "MM/YY".

**Comment by crisbeto** [comment]
This functionality is planned. I'll close this issue and continue tracking on https://github.com/angular/material/issues/9260

**Comment by vivek147** [comment]
Feeling lack of this functionality.. is there any update ?

**Comment by ganeshvelanki** [comment]
Hi, any update on this ?

**Comment by mih-kopylov** [comment]
@ganeshvelanki, please subscribe to #9260 - this feature will be implemented there and planned in [1.2.0](https://github.com/angular/material/milestone/34)
