### ISSUE TITLE
$mdMenuOpen is emitted before the menu is actually opened

### ISSUE THREAD

**Issue by otterslide** [angular/material#9545]
**Actual Behavior**:
-  `What is the issue? *`
  $mdMenuOpen is emitted before the menu is actually opened
-  `What is the expected behavior?`
  $mdMenuOpen emitted after the menu is open, or add $mdMenuOpened ?

I need some way to know when the menu is fully open. I think it would be nice if $mdMenuOpen could accept an onComplete function, that is then sent to mdMenu's show. I harded coded this in my version for now.
```js
this.open = function openMenu(ev, onCompleteHandler) {
  $mdMenu.show({ onComplete:onCompleteHandler
```

**Comment by Splaktar** [comment]
This seems to be a duplicate of https://github.com/angular/material/issues/11277. As mentioned there, `$mdMenuOpen` is an undocumented internal event that is not intended to indicate that the menu has finished opening.

I am glad that you found a workaround. If you would like to open a feature request for this, please file a new issue.

Another workaround can be found here: https://github.com/angular/material/issues/11273#issuecomment-387774239. It uses the `md-clickable` class that applied to the menu after it is open and ready for interaction.
