### ISSUE TITLE
flex-md and other flex-* media query directives not overriding properly

### ISSUE THREAD

**Issue by denver-HJS** [angular/material#9546]
**Actual Behavior**:
-  The flex media query for "flex-md" is being applied when the viewport is less than 960px wide
-  The flex-sm and/or flex-xs CSS classes should override the flex-md values

**CodePen** (or steps to reproduce the issue): *
-  http://codepen.io/denver-bohling/pen/VKLbBj
-  Tags of interest are:

```
<div class="status-container" flex="35" flex-md="45" flex-sm="100" flex-xs="100">
...
<div flex="65" flex-md="55" flex-sm="100" flex-xs="100">
```
- An image of the behavior using Chrome's DevTools emulator is attached

**Angular Versions**: *
-  `Angular Version: 1.5.5`
-  `Angular Material Version:  1.1.0`

**Additional Information**:
-  `Browser Type:  Chrome/Webkit browsers`
-  `OS:  Windows7 & iOS 9.3.5`
  ![angular-material-media-queries](https://cloud.githubusercontent.com/assets/1916018/18324195/19fdae42-74f0-11e6-8921-5b185f8cb219.png)

**Comment by denver-HJS** [comment]
Additional info about this:

It behaves as expected in codepen's "full" [view](http://codepen.io/denver-bohling/full/VKLbBj), but still has the issue explained above in the "editor" [view](http://codepen.io/denver-bohling/pen/VKLbBj). My deployed page is exhibiting the same behavior as codepen's editor view. I'm not sure what's creating the difference.

**Comment by ThomasBurleson** [comment]
@denver-HJS - We will investigate. Layouts v2 implementation is currently in-progress and should address these issues nicely.
