### ISSUE TITLE
md-datepicker full-width flex issue

### ISSUE THREAD

**Issue by sivakrrish1994** [angular/material#9550]
**Actual Behavior**:
`md-datepicker full-width flex issue *`
`The input field should be flexed accordingly to the layout given but it doesn't seems to work. The input field Hence I rewrote CSS styling.`

This is the angular material md-datepicker

    <md-input-container flex>
    <label>DOB</label>
    <md-datepicker ng-model="model.dob" name="dob"></md-datepicker>
    <div role="alert" ng-messages="form_name.dob.$error">
    <div ng-message="required">Date Of Birth is required.</div>
    </div>
    </md-input-container>

So, just include this class in your md-input-container to fix them,

     .date-picker {
        padding-right : 18px;
        height        : 58px !important;
        margin-top    : 8px !important;

        label {
            left  : 33px !important;
            right : 0 !important;
            width : calc(100% - 33px) !important;
        }

        md-datepicker {
            display     : inline-block;
            width       : 100%;
            margin-left : 26px;
            height      : 0;

            .md-datepicker-button {
                float       : left;
                margin-top  : -12.5px;
                margin-left : -33px;
            }

            .md-datepicker-input-container {
                width : 100%;
                top   : -14px;
                right : 17px;

                .md-datepicker-input {
                    max-width : 100% !important;
                    min-width : 100% !important;
                }

                .md-datepicker-expand-triangle {
                    border-left  : 4px solid transparent;
                    border-right : 4px solid transparent;
                    border-top   : 4px solid;
                }
            }
        }

        .md-input-messages-animation {
            .md-input-message-animation {
                opacity     : 1;
                margin-top  : 6px !important;
                margin-left : 34px !important;
            }
        }
    }

**Angular Versions**: *
 -  `Angular Version: ^1.4.8`
 -  `Angular Material Version: 1.1.1`

**Comment by crisbeto** [comment]
The datepicker isn't supposed to stretch to full to full width, because it can cause the input to stick out under the calendar if it gets too wide. This is an issue, because the input gets a white background when the calendar is open. I'll close the issue, but people can use this for reference if they really want to use it.
