### ISSUE TITLE
md-toolbar remains open when switching tabs

### ISSUE THREAD

**Issue by acmello** [angular/material#9552]
**Actual Behavior**:
 -  `What is the issue? *` md-toolbar remains open after switch tabs in Chrome, while md-fab-actions disappears completely.

 -  `What is the expected behavior?` In this case, the behavior I'm expecting is that md-toolbar remains open while md-fab-actions is still visible.  

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [demo](http://codepen.io/anon/pen/mAJrWY).
 -  `Details:` Open up a few tabs, go through them for a few seconds and then, get back to the pen. 

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Google Chrome 
 -  `Browser Version: *` 52.0.27
 -  `OS: *` OS X El Capitan 10.11.1
 -  `Stack Traces:`

**Comment by ThomasBurleson** [comment]
Will be resolved in Material 2. Will not fix for Material 1.
