### ISSUE TITLE
Strange error with ng-pattern

### ISSUE THREAD

**Issue by NathanGrimaud** [angular/material#9553]
I'm actually trying to use ng-patern to validate the content of an input.
The input should be only fields with digits, so i'm using this rule :
`ng-pattern="/[0-9]+$/g"`

But, once the input is filled with a correct content, if I delete a number, the pattern error message is shown

Here is an exemple -> [http://g.recordit.co/JR1uLHUqpo.gif](url)

This is not working in chrome, firefox and safari

here is the code [issue.txt](https://github.com/angular/material/files/462086/issue.txt)

 version :    "angular-material": "^1.1.0"

**Comment by ThomasBurleson** [comment]
will not fix.

**Comment by NathanGrimaud** [comment]
this issue is caused by the g flag in the regex
source : https://github.com/angular/angular.js/issues/5870
