### ISSUE TITLE
mdDatePicker: not aligned when in mdInputContainer

### ISSUE THREAD

**Issue by epelc** [angular/material#9555]
**Actual Behavior**:
 -  `What is the issue? *`
It's not aligned with regular inputs in `md-input-container`
 -  `What is the expected behavior?`
everything should be aligned

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/EgjAad
 -  `Details:`
notice the datepicker border-bottom line is about 2-4px higher then it should be
![image](https://cloud.githubusercontent.com/assets/5204642/18360467/35f680ba-75cc-11e6-91e8-8da1d21d49e3.png)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *` 53
 -  `OS: *` osx 10.11.6
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
This seems like it could be fixed with https://github.com/angular/material/pull/9504. I'll double check when it gets merged.

**Comment by crisbeto** [comment]
[Looks like it's fixed now.](http://codepen.io/crisbeto/pen/LRpAyo)
