### ISSUE TITLE
slider: numeric input does not work properly in firefox or edge

### ISSUE THREAD

**Issue by tkarls** [angular/material#9559]
**Actual Behavior**:
-  `What is the issue? *` The number inputs on the demo page https://material.angularjs.org/HEAD/demo/slider is not displaying properly in Firefox or Edge. In fireox only 1 digit out of 3 is visible. In Edge 2.5 digits are visible.
-  `What is the expected behavior?` It should look like in chrome. Or at least the numbers should be readable.

**CodePen** (or steps to reproduce the issue): \* 
-  `CodePen Demo which shows your issue:`
-  `Details:`
  Just go to official demo page. 
  Latest release: https://material.angularjs.org/1.1.1/demo/slider
  Head: https://material.angularjs.org/HEAD/demo/slider

**Angular Versions**: *
-  `Angular Version:` Any
-  `Angular Material Version:` 1.1.0 and HEAD

**Additional Information**:
-  `Browser Type: *` Firefox and Edge
-  `Browser Version: *`  Latest
-  `OS: *` Windows 10 and Linux
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by pegahsafaie** [comment]
this could fix the problem:

**location** : angular-material.js
**function**  : fitInputWidthToTextLength
**problematic  line:**
var padding = parseInt(computedStyle.padding) * 2;
**fixed line :** 
var padding = parseInt((!computedStyle.padding)  ? computedStyle.getPropertyValue('padding-left') : computedStyle.padding) * 2;

**Comment by tkarls** [comment]
Indeed. This seems to fix the issue when trying locally! :)

**Comment by Splaktar** [comment]
PR opened https://github.com/angular/material/pull/11210
