### ISSUE TITLE
Rare crashes on Saucelabs with Firefox

### ISSUE THREAD

**Issue by DevVersion** [angular/material#9560]
The CI sometimes fails with Firefox on Saucelabs.

Might be related to a heavy test for the Virtual repeat with ~1000 items at same time.

**Comment by ThomasBurleson** [comment]
Why is this happen now? Did a recent Firefox release start causing these failures?

**Comment by DevVersion** [comment]
I just went through a few recent Travis builds and found a few flaky runs with Firefox

- https://travis-ci.org/angular/material/builds/156883869
- https://travis-ci.org/angular/material/builds/156648870
- https://travis-ci.org/angular/material/builds/156590649

**Comment by DevVersion** [comment]
I need to correct myself. Not ~thousand items... **two million** items 😄

**Comment by DevVersion** [comment]
Closing this, because #9659 fixed the most firefox crashes due to memory exceeding. And we no longer use the `getElementsXX` methods.
