### ISSUE TITLE
sidenav width varies

### ISSUE THREAD

**Issue by jlmagee** [angular/material#957]
css for md-sidenav specifies a width of 304 but when locked open it varies from low to mid 200s

makes it difficult to plan for format sizes, etc. I first noticed this on some WIP testing of my own but it happens on the material,angular.js site as well so it does not seem that I'd need to create an example.

on a related topic, once this is resolved, it might be handy to make the sidenav width some kind of configuration variable setting.  It would be much less complicated that the new theming configuration :-)

Love all this stuff, by the way.  thanks

**Comment by ThomasBurleson** [comment]
no change expected.

**Comment by jlmagee** [comment]
@ThomasBurleson so the current behavior of varying width depending on window width is the expected behavior??

**Comment by ThomasBurleson** [comment]
@jlmagee - I better understand the question now. Let me reopen and escalate to the UX team.

**Comment by robertmesserle** [comment]
@ThomasBurleson This is an issue with `flexbox`.  A workaround is to set a min and max width of the desired width.  Example:

    md-sidenav {
      min-width: 304px;
      max-width: 304px;
    }

In doing this, I think `304px` is WAY too wide for our content, though:

![screen shot 2015-02-04 at 10 10 35 am](https://cloud.githubusercontent.com/assets/571363/6046340/0c12a1f2-ac56-11e4-81bd-50d1a0ac1565.png)
