### ISSUE TITLE
dialog: causes Mobile Safari address bar to expand, causing page to bounce slightly ~40px

### ISSUE THREAD

**Issue by stephengardner** [angular/material#9578]
When opening an `$mdDialog` with the Mobile Safari address bar in its small / minimized view, the showing of the dialog causes the address bar to expand.  Due to the way that the `$mdDialog` service calculates the scroll position and sets `position: fixed`, what happens is it calculates a `top` position that is less of an offset than it should be.

The body of the page then jumps up about 40px, before correctly showing the dialog.  The dialog ends up fine, but the jump in the page is slightly disorienting.

**Comment by ThomasBurleson** [comment]
@stephengardner - 
*  which version of Angular and Angular Material are you using? 
*  what url or CodePen are you using?
