### ISSUE TITLE
Change md-tab selected index when input field is invalid

### ISSUE THREAD

**Issue by rajatjangir** [angular/material#9579]
Hi,
First of all this i an amazing repository. 

Issue being faced : I am trying to validate a form which have multiple tabs. 
Let say tab1 , tab2, tab3.

All these tabs have multiple input field which should be validated and when error occurs the input field should be focused on the first invalid field.

So far i have been able to successfully focus on the input field in my current selected tab based on a custom directive as posted below : 

```js
app.directive('accessibleForm', function () {
    return {
        restrict: 'A',
        link: function (scope, elem) {

            // set up event handler on the form element
            elem.on('submit', function () {

                // find the first invalid element
                var firstInvalid = elem[0].querySelector('.ng-invalid');

                // if we find one, set focus
                if (firstInvalid) {
                    firstInvalid.focus();
                }
            });
        }
    };
});
```

The problem which i am facing is that when the input field is in current selected tab then focus goes to that tab but when the field is in some other tab then the tab should be changed and the first error element should be focused. 

> I am not sure how could this be achieved or weather it is possible or not.**

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)

**Comment by elessariel** [comment]
it's been some time, but I was interested if you found a solution @rajatjangir ?
