### ISSUE TITLE
md-dialog-container and md-backdrop incorrectly scroll with the page

### ISSUE THREAD

**Issue by naomiblack** [angular/material#958]
If you create and show a dialog with the `$mdDialog` service, the dialog is initially centered on the page with a translucent backdrop. However, when you scroll the page, the dialog and backdrop scroll with it. Investigating the CSS shows that the `md-backdrop` and `md-dialog-container` divs have a `position` value of `absolute`. Overriding to set `position: fixed` ensures that they always remain visible on the page.

**Comment by bigterminal** [comment]
+1

**Comment by ThomasBurleson** [comment]
@rschmukler - does this fix have any negative side affects. What about future support for drag positioning?

**Comment by rschmukler** [comment]
This is now solved by setting `overflow: hidden` on the parent element (`body` unless otherwise specified), disabling scrolling entirely. Fixed with 993fa2bc00598dd18227b12bb197f2d9c667ea75

**Comment by xandorxicay** [comment]
How do you specify the disableParentScroll on a function like this? 

    $mdDialog.show(
      $mdDialog.alert()
      .parent(angular.element(document.querySelector('.side-nav')))
      .clickOutsideToClose(true)
      .title('Your Order Has been Placed')
      .content('You can pick it up at ')
      .ok('Got it!')
      .targetEvent(ev)
    );
