### ISSUE TITLE
md-autocomplete not working with md-chips + md-add-on-blur

### ISSUE THREAD

**Issue by 0190** [angular/material#9582]
When using **md-chips** with **md-autocomplete** and **md-add-on-blur**, click on autocomplete doesn't add selected item as expected, because blur is triggered before it, adding incomplete search input.

**CodePen**: http://codepen.io/0190/pen/pEgzpp
**Explanation**:
Two md-chips forms are identical with an exception of md-add-on-blur attribute presence.
In the first form, if you start typing and then choose an item from autocomplete, it gets filled in the chip field. In the second one, the incomplete search query becomes a chip instead.

Angular Material version 1.1.1

**Comment by mikila85** [comment]
+1
