### ISSUE TITLE
autocomplete: keyboard navigation does not update input box

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#9584]
**Actual Behavior**:
-  `What is the issue? *` When navigating through the dropdown items, the input box is not updated
-  `What is the expected behavior?` Input box should be updated in some way while navigation

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` https://material.angularjs.org/latest/demo/autocomplete
-  `Details:` Compare with Chrome, Firefox, Safari, etc browsers with their autocomplete implemenations in input boxes and address bar

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.0

---

I'm filing a proper issue for this but, a PR has already been built for this feature in #8904 

In my opinion, there are two methods, "replace text" and "append text".

Autocomplete UX Research: https://docs.google.com/document/d/1t60A2_Qni3IOSZDRqwwum3r5EVPjANJAkvFuMoqGfQA/

**Comment by ErinCoughlan** [comment]
@clshortfuse I think "replace text" is scarier than "append text". "Append text" doesn't change the ngModel until the user hits the "right arrow" to fill it out.

**Comment by clshortfuse** [comment]
@ErinCoughlan, if you want "append text" it to act like the current autocomplete implementation browser (Safari, Chrome, FireFox), it still modifies the input box, just doesn't update the model until the input is changed.

Append text doesn't work in all situations because, it only works when search are based on `startWith`. If I were to use it as a keyword search, then it wouldn't work as well. For example, if I had an autocomplete search and typed "Google", I might want the suggestion to be "www.google.com". This wouldn't work with append text. 

Replace text universally works, and you don't have to trigger a search on selection. Google.com triggers a search on selection, but my PR doesn't have that enabled. Also, you can have the drop down item show a different value than what happens when you press enter/tab. For example, the list item might say "Home" and when I select it, the textbox could say "100 Main St". It's somewhat a preview of what would happen when you select the item.

Inline autocomplete is by far the safest (and part of spec), but it's not meant to be used in a drop down environment (why it's called inline). Also, it favors touch and is not commonly seen in keyboard environments.

To clarify, we might have differing interpretations, but "append text" to me, is when autocomplete keeps the cursor in place, appends text to your input box, and highlights the text. Inline is when you get a preview to its side. Replace is replacing the whole text and moved your caret to the end.

**Comment by ErinCoughlan** [comment]
@clshortfuse Thanks for the clarification. What I am imagining is inline then (where I get the preview and can hit right arrow to fill it out). I don't think it's bad to only have the "startsWith" work for that.

**Comment by clshortfuse** [comment]
I went ahead and rebased my code and added the append option. The problem with the floating append tooltip-like is that it's very difficult to manage due to the way input boxes are styled and sized on different browsers.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'will not support' category for one or more of the following reasons:

*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests to resolve this issue are encouraged! Note, however, that Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
