### ISSUE TITLE
orderBy doesn't work with md-autocomplete md-items

### ISSUE THREAD

**Issue by SjorsHijgenaar** [angular/material#9588]
**Actual Behavior**:
 -  On populating md-items with object in md-autocomplete, orderBy doesn't seem to be working. The items get orderd based on object's keys (int). 

 -  Code (JS & HTML): 

`$scope.searchQuery = function (searchText) {
    var users = [];
    angular.forEach($scope.users,
        function (value, key) {
            // value = user object
            // key = userId
            var dN = value["display_name"];
            if (dN) {
                var obj = {};
                obj[key] = value;
                obj["display"] = dN;
                if (dN.toLowerCase().indexOf(searchText.toLowerCase()) !== -1) {
                    users.push(obj);
                }
            }
        });
    return users;
}`

`<md-autocomplete md-selected-item="videoInfo.lineUp[1]" md-items="item in searchQuery(searchText1) | orderBy: item.display" md-search-text="searchText1" md-item-text="item.display" md-floating-label="Loosehead" md-require-match="true">
            <span md-highlight-text="searchText1">{{item.display}}</span>
        </md-autocomplete>`

**Angular Versions**: *
 -  `Angular Version: 1.5.5`
 -  `Angular Material Version: 1.1.0-rc2`

**Additional Information**:
 -  `Browser Type: Chrome*`
 -  `Browser Version: 52.0.2743.116 m*`
 -  `OS: Windows 10.1*`

**Comment by DevVersion** [comment]
This seems to work for me.

- http://codepen.io/DevVersion/pen/mAVqop?editors=1010

Please provide a codepen demo to show that it doesn't work.

**Comment by SjorsHijgenaar** [comment]
Thanks! I had `orderBy : item.display` which should of course be `orderBy : 'display'`
