### ISSUE TITLE
list: md-list-item with multiple lines and secondary menu not truncating

### ISSUE THREAD

**Issue by Slettan** [angular/material#9589]
**Actual Behavior**:
-  `What is the issue? *` List items with 2 or 3 lines are not truncated when using secondary menu 
-  `What is the expected behavior?` Truncate first and second line, like it does with a simple secondary button

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/amdwyb
-  `Details:` Resize browser and notice how the list item with a secondary button truncates the text to fit nicely on mobile screens. The list item with a menu does not do this, but pushes the content outside the view.

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 52.0.2743.116 m
-  `OS: *` Windows 8.1

**Comment by DevVersion** [comment]
I will mark this issue as blocked, because I want to review this with the new List styles which are hopefully coming soon #8482

**Comment by Splaktar** [comment]
I tried with the old CodePen and [updated it](https://codepen.io/Splaktar/pen/gOYZZOv?editors=1111) to the latest versions as well, but I can't seem to reproduce this. The lines of text don't seem very long and they behave the same for button or menu secondary actions on Chrome 77.
