### ISSUE TITLE
When clicking delete on chip it closes the md-menu

### ISSUE THREAD

**Issue by zhenya2224** [angular/material#9593]
**Actual Behavior**:
When I'm clicking on one of the chips to delete it in md-menu it closes the whole menu, I would be grateful for a workaround for this issue. I've manage to add md-prevent-menu-close="md-prevent-menu-close" on checkboxes in the same menu to prevent menu from closing when clicking on checkboxes, but it doesnt work on chips.

**Angular Versions**: *
-  `Angular Version:`1.5.7
-  `Angular Material Version:`1.0.5

**Additional Information**:
-  `Browser Type: *`Chome
-  `Browser Version: *`55.0.2853.0 
-  `OS: *`Windows 8

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by DevVersion** [comment]
Please provide a demo for this issue

**Comment by topherfangio** [comment]
Just wanted to follow up. Please provide a demo so we can investigate.

**Comment by Splaktar** [comment]
No demo provided.
