### ISSUE TITLE
mdMenu stops working after clicking outside when sub-menu is open

### ISSUE THREAD

**Issue by guiligan** [angular/material#9599]
**Actual Behavior**:
 -  `What is the issue? *`
When a sub-menu is open and you click outside (over the mdToolbar area) in order to close the menus, the first-level item keeps open and is impossible to continue navigation on website.

 -  `What is the expected behavior?`
Close all menus

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/latest/demo/menuBar
 -  `Details:`
First open File menu, then open New sub-menu, and then click anywhere on the mdToolbar

**Angular Versions**: *
 -  `Angular Version:` 1.5.3
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52.0.2743.116
 -  `OS: *` Windows 10

**Comment by crisbeto** [comment]
Most likely introduced by #9428.
