### ISSUE TITLE
Attribute md-selected of md-tabs doesn't work

### ISSUE THREAD

**Issue by gcharpentier** [angular/material#960]
I tried to use the directive md-tabs with his attribute md-selected. Tabs headers was displayed correctly but none of them was active so I didn't see any content. After opening the file angular-material.js in order to see how it worked, I saw that directive didn't bind on element "md-selected" but on element "selected": 
L. 6202 : scope: {
      selectedIndex: '=?selected'
    },

When I use this attribute selected, all is working fine. It could be useful to change either the name of the attribute or the documentation for helping others users who will try to use this attribute.

**Comment by renaud** [comment]
Thanks!
