### ISSUE TITLE
 md-datepicker model does not updated

### ISSUE THREAD

**Issue by DamonV** [angular/material#9600]
**Actual Behavior**:
 -  `What is the issue? *`
After upgrade to version 1.1.1 when I change date in md-datepicker model does not updated , however view is changed.
Also the view's value timezone is assigned incorrectly. For example I choose 1 september 2016 and my local timezone GMT+03:00. I get 31 august 2016 in the view.
 -  `What is the expected behavior?`
I expect correct behavior

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` Ordinary usage of datepicker, like this "<md-datepicker ng-model="birthday"></md-datepicker>"

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *`  Chrome, Firefox
 -  `Browser Version: *` Latest
 -  `OS: *` Win 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
Could you post a codepen that shows the issue? There were some changes in 1.1.1 to make the datepicker behave more closely to Angular's `input[type="date"]`.

**Comment by DamonV** [comment]
Excuse me. I checked everything and found that my project used the date filter to output a localized representation. This caused the error. Meanwhile, the filter worked well up to version 1.1.0. and I still needed this filter.  A little later I'll try to make an example in codepen.

**Comment by DamonV** [comment]
You can remove the issue. I solved the problem . My apologize

**Comment by crisbeto** [comment]
No problem, thanks for the quick feedback.

**Comment by tjones0808** [comment]
@DamonV  what exactly was your fix? I am having the same issue. Everything is wired up correctly can't figure out for the life of me why my model won't update. The view changes and the calendar changes and the date looks right but model not updated at all.

**Comment by tjones0808** [comment]
I do have the datepicker inside of a modal but I didn't think that would affect angular material?

**Comment by DamonV** [comment]
@tjones0808 my problem was that I had overridden the date filter, which return the date as a localized string. (It should return a date format)
```
.filter('date', function () {
    return function (input) {        
        var options = {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            timeZone: 'UTC'
        };
        var out = input.toLocaleString("ru", options);
        return out;
    }
```
I just removed it and instead added this: 
`
.config(function ($mdDateLocaleProvider) {
$mdDateLocaleProvider.formatDate = function (date) {
        return moment(date).format('DD.MM.YYYY');
    };
})

`

**Comment by tjones0808** [comment]
@DamonV dang okay i'm not doing anything like that. Just using it inside of a modal and the model wont update. Only the view of the datepicker and calendar update. The onChange event fires but the model is null.

**Comment by Wsteppe** [comment]
Same issue as @tjones0808 , filter looks exactly the same as @DamonV so no issues there.
Worked fine with 1.1.0. Will look further into it once i have more time
