### ISSUE TITLE
Tooltip doesn't disappear off-hover from clicked button/anchor

### ISSUE THREAD

**Issue by rgthree** [angular/material#9607]
**Actual Behavior**:
 -  `What is the issue? *` `md-tooltip` persists on screen when inside a button that has been clicked and hovered back over
 -  `What is the expected behavior?` `md-tooltip` disappears when the user's pointer is no longer hovered over the button. I could also reproduce with regular `<a>` tags; not exlusive to `md-button`.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/rgthree/pen/kkbLgw
 -  `Details:` _(in codepen)_

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.0 and 1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 54
 -  `OS: *` Linux
 -  `Stack Traces:` n/a

![tooltip](https://cloud.githubusercontent.com/assets/476360/18524708/8ef88a68-7a87-11e6-9795-a4b3b65950c1.gif)

**Comment by whittssg** [comment]
Try adding md-autohide to the tooltip:

```
<md-tooltip md-autohide md-direction="right">
My Tooltip
</md-tooltip>
```

**Comment by rgthree** [comment]
That appears to be it. Closing.
