### ISSUE TITLE
DatePicker Format on the fly

### ISSUE THREAD

**Issue by arvigenio** [angular/material#9610]
Please add a feature wherein date format can be programatically changed. Thank you! :)

**Comment by crisbeto** [comment]
You can change it globally via the [`$mdDateLocaleProvider`](https://material.angularjs.org/HEAD/api/service/$mdDateLocaleProvider). As for changing it only on a specific datepicker instance, that's being tracked with #9270. I'll close this issue and continue tracking it on #9270.
