### ISSUE TITLE
ng-if in <md-menu-content> Error

### ISSUE THREAD

**Issue by codetrash** [angular/material#9611]
Im building a dynamic Menu with submenu. 
```
<md-menu-bar>
      <md-menu ng-repeat="mn in ctrl.menuList">
           <button ng-click="$mdOpenMenu()">
                    <md-icon class="material-icons"> {{mn.icon}} </md-icon>
                    {{mn.menu_name}}
                  </button>
                  <md-menu-content ng-if="mn.child.length > 0">
                    <md-menu-item ng-repeat="mch in mn.child">
                      <md-button ng-click="ctrl.sampleAction('share', $event)">
                        {{mch.menu_name}}
                      </md-button>
                    </md-menu-item>
                </md-menu-content>
        </md-menu>
</md-menu-bar>
```

I need to check if a Menu has child (submenu) or not by checking the length of the array

```
<md-menu-content ng-if="mn.child.length > 0">
   ............
</md-menu-content>
```

its raising error 

```
angular.min.js:117 TypeError: Cannot read property 'hasAttribute' of undefined
```

Is there a way to fix it or do I write it wrong?

**Apparently it works fine with ng-show**
```
<md-menu-content ng-show="mn.child.length > 0">
   ............
</md-menu-content>
```

**Comment by crisbeto** [comment]
Via the [docs](https://material.angularjs.org/HEAD/api/directive/mdMenu):

> Every md-menu must specify exactly two child elements. The first element is what is left in the DOM and is used to open the menu. This element is called the trigger element. The trigger element's scope has access to $mdOpenMenu($event) which it may call to open the menu. By passing $event as argument, the corresponding event is stopped from propagating up the DOM-tree.
> 
> The second element is the md-menu-content element which represents the contents of the menu when it is open. Typically this will contain md-menu-items, but you can do custom content as well.

The `md-menu-content` is always supposed to be there. If you want to prevent it from opening when there aren't any items, you can try adding some custom logic in the `ng-click`.
