### ISSUE TITLE
dialog: size not re-computed after virtual keyboard close

### ISSUE THREAD

**Issue by rolintoucour** [angular/material#9614]
**Actual Behavior**:
-  `What is the issue? *`
  On Android, I open a dialog that contains an input.
  I edit this input.
  The virtual keyboard comes up, and the dialog is resized.
  I manually close the virtual keyboard (with the dedicated button), the dialog isn't resized. The space previously occupied by the keyboard is now occupied by the backdrop
-  `What is the expected behavior?`
  When I close the virtual keyboard, the dialog should be resized to still occupy full screen

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` from version 1.1.0 final (version 1.1.0-rc.5 hasn't this problem)

**Additional Information**:
-  `Browser Type: *` Chrome Android
-  `OS: *` Android 5.1.1 and Android 6.0 tested

**Comment by mohammadrafigh** [comment]
+1

**Comment by mohammadrafigh** [comment]
as a quick fix you can try to overwrite the md-dialog-container style like this:

```
.md-dialog-container {
    height: 100% !important;
}
```

this will fix the issue.

**Comment by FlorianBurgevin** [comment]
+1 same issue

It appears only on a page where I have a ng-repeat with flex="100" inside

**Comment by ManishKm263160** [comment]
I am facing the same problem.

**Comment by matthieusieben** [comment]
If you want to hack this using JS, you can do the following. Very dirty, I know.
```js
    $($window).on('resize', $mdUtil.debounce(() => {
      $timeout(() => {
        $window.dispatchEvent(new Event('resize'))
      }, 1, false)
    }, 60, null, false))
```

**Comment by Splaktar** [comment]
I'm not able to reproduce this using the dialog demo in the docs. There was no CodePen reproduction provided, so it's hard to be sure. If this is still an issue, please open a new issue with a reproduction.
