### ISSUE TITLE
Script Error in Chips

### ISSUE THREAD

**Issue by mohanskumar** [angular/material#9618]
**Actual Behavior**:
 -  `What is the issue? *`Getting Script Error
 -  `What is the expected behavior?` No Script Error

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` No
 -  `Details:` Go to Chips Demo and go to search a vegetable chip, type Broccoli and select the item and then click 'X' mark to remove the chip. 

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 52+
 -  `OS: *` Mac
 -  `Stack Traces:` Attaching a screenshot
![image](https://cloud.githubusercontent.com/assets/4041250/18563772/f3c6938e-7b56-11e6-9950-7402e37a8a7b.png)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Fixed in master

**Comment by reppners** [comment]
Any ETA for a release of this fix? I have a product release pending which depends on this fix being released.
