### ISSUE TITLE
Responsive design can be improved for small devices

### ISSUE THREAD

**Issue by MCBL** [angular/material#962]
Toolbar title, breadcrumb and directive name are poorly displayed:
![capture d ecran 2014-12-17 a 13 33 49](https://cloud.githubusercontent.com/assets/6067349/5471094/886c9b76-85f1-11e4-8779-9be9afee7159.png)

A proposed solution would be to switch to menu when width is smaller than 771 pixels instead of 600.

**Comment by marcysutton** [comment]
Closed with bfc947f66b2a2568dc76ca3278eb9b5f83424a2f

**Comment by MCBL** [comment]
It is still poorly displayed. Juste resize your browser on page with a lot of text. It's ugly!
![capture d ecran 2015-01-12 a 11 46 24](https://cloud.githubusercontent.com/assets/6067349/5701800/d74eea6e-9a50-11e4-8dc6-d722e8c50f5d.png)

**Comment by marcysutton** [comment]
Are you looking at material.angularjs.org or a local build from master? We are still working to get the site updated, which won't reflect these changes.

**Comment by MCBL** [comment]
At material.angularjs.org. Ok all right, thanks.

**Comment by ashishpatel02** [comment]
@ThomasBurleson  as you said "When the content width [box area with Basic Usage] is great than 900px, then the SideNav component is locked into the open position. Less than that and it auto-hides."

How can i fix to open for all the resolutions?

**Comment by ThomasBurleson** [comment]
@ashishpatel02 - try `md-is-locked-open="true"`
