### ISSUE TITLE
Fixed postioned Tabs at the bottom of viewport scroll a bit first and then drop back while scrolling down on iOS

### ISSUE THREAD

**Issue by bvahdat** [angular/material#9621]
**Actual Behavior**:
 -  `What is the issue?` While scrolling through a page, the tabs, which are fixed positioned at the bottom of screen (for `max-width: 960px`), will not stick to their fixed position at the bottom of viewport but will first scroll up for a short distance and then jump/drop back to the bottom of the viewport again. I see this exact behaviour on Chrome for iOS as well but not on desktop. As you see inside the markup, the `md-tabs` tag is nested inside `md-toolbar`. If you remove the `fixed-on-top` css class, then the misbehavior on iOS is not given anymore. But my intention is to have `md-toolbar` fixed positoned as well
 -  `What is the expected behavior?` While scrolling down on mobile `md-tabs` should _stick_ to it's fixed position at the bottom of the viewport instead of first moving upwards a bit and then drop back.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://codepen.io/bvahdat/pen/ozLXmm
 -  `Details:` The Demo on CodePen doesn't look exactly the same as I look at the _exact_ same markup on an iPhone or iPad device. For example on a mobile, CodePen shows the tab at the bottom of the page and not at the bottom of the viewport which is wired! But basically if you would serve the same given markup of mine by yourself locally and access the page through your iPhone/iPad device then you will see the behavior while scrolling. I did not test this on an Android device. 

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Safari and Chrome on iOS
 -  `Browser Version: *` 601.1
 -  `OS: *` iOS 9.3.5
 -  `Stack Traces:` N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by bvahdat** [comment]
I manged to find a workaround, in that I made `md-tabs` to be no more a direct descendant of `md-toolbar` but instead it's sibling. In this way it's positioning becomes independent of how `md-toolbar` is positioned.

If there's any better way to do this, or any improvement you can provide, then please let me know. Otherwise feel free to close this.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  Issue has a reasonable workaround
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
