### ISSUE TITLE
mdNavBar should have h1

### ISSUE THREAD

**Issue by dieguezz** [angular/material#9622]
**Actual Behavior**:
-  When using `<md-nav-bar>` its not including an `<h1>` after the `<nav>` tag 
-  Its a good idea to place an `<h1>` that can be hidden inside the nav markup. Because screen readers would find it more accessible. There is an example here: https://dev.w3.org/html5/spec-preview/the-nav-element.html

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`  [Demo](http://codepen.io/dieguezz/pen/rrLOKk).
-  `Details:`

**Angular Versions**: *
-  `Angular Version:`1.5.8
-  `Angular Material Version:`1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *`52.0.2743.116 (Official Build) (64-bit)
-  `OS: *`OSX 10.11.6
-  `Stack Traces:`

---

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by ThomasBurleson** [comment]
This issue is closed due to one of the following reasons:

*  Issue is real, but only affects a very small use case
*  Issue is real and is less urgent than other needs.

> Pull Requests (PR) are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Keep your PR small and focused; PRs with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].
