### ISSUE TITLE
Virtual Repeat (Infinite Scroll) not working inside ng-view

### ISSUE THREAD

**Issue by fer512** [angular/material#9635]
Hi, I have a problem with virtual repeat inside ng-view. I can not see the result like Demo. Why?
What am i doing wrong?

http://plnkr.co/edit/FxwuiL9Aap8KzaFUbWa5?p=preview

**Comment by DevVersion** [comment]
Everything works as expected inside `ng-view` - see http://plnkr.co/edit/likgy0k6CKFYTC010MLA?p=preview

You have a few issues in your markup
- Not loading Angular Material Stylesheet
- Binding to the Controller Instance while `$scope` should be used
- Accessing `this` context inside of an JSON Object

The Plunker above fixes that issues and shows how that it works.
> Here is a good example as well (https://material.angularjs.org/HEAD/demo/virtualRepeat)
