### ISSUE TITLE
Closing by $mdDialog.cancel() a nested dialog closes the parent, not the current one

### ISSUE THREAD

**Issue by franjuan** [angular/material#9638]
**Actual Behavior**:
 -  `What is the issue? ` When I open a new dialog ($mdDialog.show with skipHide: true) inside another dialog, it opens correctly. But when I try to close cancelling it ($mdDialog.cancel), the dialog which is closed is the first one, the parent, the one who opens the dialog which calls cancel operation. The child dialog still remains and when canceled again it is closed then.
 -  `What is the expected behavior?` The dialog which is expected to be closed is the child one, the one whose controller called the cancel operation.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
   1. Open a new dialog with $mdDialog.show
   2. Open a new dialog inside the last one with $mdDialog.show (skipHide:true)
   3. Cancel the last dialog with $mdDialog.cancel

**Angular Versions**: *
 -  `Angular Version: 1.5.5`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: Firefox and Chrome` 
 -  `Browser Version: Chrome 53.0.2785.116 m (64-bit) and Firefox 48.0.2`
 -  `OS: Windows 10` 
 -  `Stack Traces:`

**Comment by DevVersion** [comment]
This should be fixed after #9053

**Comment by franjuan** [comment]
Thanks a lot!

**Comment by DevVersion** [comment]
Should be fixed within `master`. Please notice that `skipHide` has been renamed to `multiple: true`

**Comment by franjuan** [comment]
Thank you very much!
