### ISSUE TITLE
select: setting the max-height will cause the menu to open below the fold

### ISSUE THREAD

**Issue by mike-fastpay** [angular/material#9642]
**Actual Behavior**:
- My team would like to be able to have `md-select` menus open larger than they currently do. But if the menu is close to the bottom of the page the menu will open below the fold and options will be inaccessible. 

**CodePen** 
-  http://codepen.io/reactiongears/pen/EggZPz
-  Shrink the browser so that the browser is smaller than the height of the menu
-  Open the menu and notice that it opens below the fold
-  This is just a simple illustration but we run into this issue frequently with `md-select`s inside and positioned at the bottom of `md-dialog`s. 

It would be nice to have a directive attribute for `max-height` or maybe number of options to display

**Angular Versions**: *
-  1.1.0

**Comment by Splaktar** [comment]
I updated the [CodePen](https://codepen.io/Splaktar/pen/bGbqaer) to the latest version, but I was not able to reproduce this in Chrome 76 (in either `1.1.0` or `1.1.20`). The browser wasn't specified in the issue, so it's unclear if this was seen in another browser.
