### ISSUE TITLE
$mdDialog.prompt() input type should be configurable

### ISSUE THREAD

**Issue by ThomasKerbrat** [angular/material#9646]
**Actual Behavior**:
 -  `What is the issue? *`

The `mdDialog.prompt` template has an `input` element which has no `type` attribute by default.

 -  `What is the expected behavior?`

The `$mdDialog` service should offer the option to add a `type` to the `input` element.
The value can be restricted to a limited set of values (e.g. `text`, `email`, `tel`, `password`...).
Without this option, I have to create a custom dialog which adds a template and a controller file to my code base.

Here is the input I talk about:
https://github.com/angular/material/blob/master/src/components/dialog/dialog.js#L597

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/thomaskerbrat/pen/ALpvYO
 -  `Details:` If you comment the `.inputType('password')` line, the CodePen just works as expected.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 53.0.2785.116 m
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by volmerf** [comment]
+1 

It would also be nice to add custom attributes like maxlength or other attributes.

**Comment by kylekrzeski** [comment]
+1

**Comment by jasonpeate** [comment]
+1

**Comment by asatalkar-ttm** [comment]
Is there a way to restrict the input to certain number of characters in $mdDialog.prompt() ?

**Comment by Splaktar** [comment]
@asatalkar-ttm no, you will need to create a custom dialog via `$mdDialog.show()` as documented [here](https://material.angularjs.org/1.1.10/api/service/$mdDialog#mddialog-show-optionsorpreset).
