### ISSUE TITLE
'bower install angular-material' fails

### ISSUE THREAD

**Issue by ashwinmallikarjun** [angular/material#9648]
For some weird reason, bower install angular-material is failing on my machine(Windows 10). Here is the log -

C:\dev\horizon\horizon_consumer_client_trunk>bower install angular-material
bower angular#1.5.x         not-cached git://10.60.104.253:6789/angular#1.5.x
bower angular#1.5.x            resolve git://10.60.104.253:6789/angular#1.5.x
bower angular-cookies#1.5.x not-cached git://10.60.104.253:6789/angular-cookies#1.5.x
bower angular-cookies#1.5.x    resolve git://10.60.104.253:6789/angular-cookies#1.5.x
bower angular-animate#1.5.x not-cached git://10.60.104.253:6789/angular-animate#1.5.x
bower angular-animate#1.5.x    resolve git://10.60.104.253:6789/angular-animate#1.5.x
bower angular-i18n#1.5.x    not-cached git://10.60.104.253:6789/angular-i18n#1.5.x
bower angular-i18n#1.5.x       resolve git://10.60.104.253:6789/angular-i18n#1.5.x
bower angular-sanitize#1.5.x       not-cached git://10.60.104.253:6789/angular-sanitize#1.5.x
bower angular-sanitize#1.5.x          resolve git://10.60.104.253:6789/angular-sanitize#1.5.x
bower angular-translate#~2.9.1     not-cached git://10.60.104.253:6789/angular-translate#~2.9.1
bower angular-translate#~2.9.1        resolve git://10.60.104.253:6789/angular-translate#~2.9.1
bower angular-translate-loader-partial#~2.9.1       not-cached git://10.60.104.253:6789/angular-translate-loader-partial#~2.9.1
bower angular-translate-loader-partial#~2.9.1          resolve git://10.60.104.253:6789/angular-translate-loader-partial#~2.9.1
bower angular-translate-loader-static-files#~2.9.1  not-cached git://10.60.104.253:6789/angular-translate-loader-static-files#~2.9.1
bower angular-translate-loader-static-files#~2.9.1     resolve git://10.60.104.253:6789/angular-translate-loader-static-files#~2.9.1
bower angular-translate-loader-url#~2.9.1           not-cached git://10.60.104.253:6789/angular-translate-loader-url#~2.9.1
bower angular-translate-loader-url#~2.9.1              resolve git://10.60.104.253:6789/angular-translate-loader-url#~2.9.1
bower angular-translate-storage-cookie#~2.9.1       not-cached git://10.60.104.253:6789/angular-translate-storage-cookie#~2.9.1
bower angular-translate-storage-cookie#~2.9.1          resolve git://10.60.104.253:6789/angular-translate-storage-cookie#~2.9.1
bower angular-ui-router#~0.2.18                     not-cached git://10.60.104.253:6789/angular-ui-router#~0.2.18
bower angular-ui-router#~0.2.18                        resolve git://10.60.104.253:6789/angular-ui-router#~0.2.18
bower angular-messages#1.5.x                        not-cached git://10.60.104.253:6789/angular-messages#1.5.x
bower angular-messages#1.5.x                           resolve git://10.60.104.253:6789/angular-messages#1.5.x
bower angular-aria#1.5.x                            not-cached git://10.60.104.253:6789/angular-aria#1.5.x
bower angular-aria#1.5.x                               resolve git://10.60.104.253:6789/angular-aria#1.5.x
bower angular-mocks#1.5.x                           not-cached git://10.60.104.253:6789/angular-mocks#1.5.x
bower angular-mocks#1.5.x                              resolve git://10.60.104.253:6789/angular-mocks#1.5.x
bower angular-translate-storage-local#~2.9.1        not-cached git://10.60.104.253:6789/angular-translate-storage-local#~2.9.1
bower angular-translate-storage-local#~2.9.1           resolve git://10.60.104.253:6789/angular-translate-storage-local#~2.9.1
bower angular-translate-interpolation-messageformat#~2.9.1       not-cached git://10.60.104.253:6789/angular-translate-interpolation-messageformat#~2.9.1
bower angular-translate-interpolation-messageformat#~2.9.1          resolve git://10.60.104.253:6789/angular-translate-interpolation-messageformat#~2.9.1
bower jquery#2.2.0                                               not-cached git://10.60.104.253:6789/jquery#2.2.0
bower jquery#2.2.0                                                  resolve git://10.60.104.253:6789/jquery#2.2.0
bower jquery-ui#1.11.4                                           not-cached git://10.60.104.253:6789/jquery-ui#1.11.4
bower jquery-ui#1.11.4                                              resolve git://10.60.104.253:6789/jquery-ui#1.11.4
bower spin.js#~2.3.2                                             not-cached git://10.60.104.253:6789/spin.js#~2.3.2
bower spin.js#~2.3.2                                                resolve git://10.60.104.253:6789/spin.js#~2.3.2
bower angular-spinner#~0.8.1                                     not-cached git://10.60.104.253:6789/angular-spinner#~0.8.1
bower angular-spinner#~0.8.1                                        resolve git://10.60.104.253:6789/angular-spinner#~0.8.1
bower moment#^2.12.0                                             not-cached git://10.60.104.253:6789/moment#^2.12.0
bower moment#^2.12.0                                                resolve git://10.60.104.253:6789/moment#^2.12.0
bower foundation-sites#~6.2.0                                    not-cached git://10.60.104.253:6789/foundation-sites#~6.2.0
bower foundation-sites#~6.2.0                                       resolve git://10.60.104.253:6789/foundation-sites#~6.2.0
bower ngMask#^3.0.16                                             not-cached git://10.60.104.253:6789/angular-mask#^3.0.16
bower ngMask#^3.0.16                                                resolve git://10.60.104.253:6789/angular-mask#^3.0.16
bower owl.carousel#2.1.3                                         not-cached git://10.60.104.253:6789/owl.carousel#2.1.3
bower owl.carousel#2.1.3                                            resolve git://10.60.104.253:6789/owl.carousel#2.1.3
bower angular-credit-cards#3.1.3                                 not-cached git://10.60.104.253:6789/angular-credit-cards#3.1.3
bower angular-credit-cards#3.1.3                                    resolve git://10.60.104.253:6789/angular-credit-cards#3.1.3
bower angular-foundation#^0.8.0                                  not-cached git://10.60.104.253:6789/angular-foundation#^0.8.0
bower angular-foundation#^0.8.0                                     resolve git://10.60.104.253:6789/angular-foundation#^0.8.0
bower animate.css#~3.5.2                                         not-cached git://10.60.104.253:6789/animate.css#~3.5.2
bower animate.css#~3.5.2                                            resolve git://10.60.104.253:6789/animate.css#~3.5.2
bower                                                                 retry Request to http://10.60.104.253:5678/packages/angular-material failed with ETIMEDOUT, retrying in 1.5s
bower                                                                 retry Request to http://10.60.104.253:5678/packages/angular-material failed with ETIMEDOUT, retrying in 2.0s
bower angular-animate#1.5.x                                         ECMDERR Failed to execute "git ls-remote --tags --heads git://10.60.104.253:6789/angular-animate", exit code of #128 fatal: unable to access 'https://10.60.104.253:6789/angular-animate/': Failed to connect to 10.60.104.253 port 6789: Timed out

Additional error details:
fatal: unable to access 'https://10.60.104.253:6789/angular-animate/': Failed to connect to 10.60.104.253 port 6789: Timed out

Here is my bower.json file -

{
  "name": "XXXXXXXXX",
  "version": "0.0.1",
  "dependencies": {
    "angular": "1.5.x",
    "angular-animate": "1.5.x",
    "angular-cookies": "1.5.x",
    "angular-i18n": "1.5.x",
    "angular-sanitize": "1.5.x",
    "angular-translate": "~2.9.1",
    "angular-translate-loader-partial": "~2.9.1",
    "angular-translate-loader-static-files": "~2.9.1",
    "angular-translate-loader-url": "~2.9.1",
    "angular-translate-storage-cookie": "~2.9.1",
    "angular-ui-router": "~0.2.18",
    "angular-messages": "1.5.x",
    "angular-aria": "1.5.x",
    "angular-mocks": "1.5.x",
    "angular-translate-storage-local": "~2.9.1",
    "angular-translate-interpolation-messageformat": "~2.9.1",
    "jquery": "2.2.0",
    "jquery-ui": "1.11.4",
    "spin.js": "~2.3.2",
    "angular-spinner": "~0.8.1",
    "moment": "^2.12.0",
    "foundation-sites": "~6.2.0",
    "ngMask": "angular-mask#^3.0.16",
    "owl.carousel": "2.1.3",
    "angular-credit-cards": "3.1.3",
    "angular-foundation": "^0.8.0",
    "animate.css": "~3.5.2",
    "angular-material": "^1.1.1"
  },
  "devDependencies": {
    "angular-mocks": "1.5.x"
  },
  "resolutions": {
    "angular": "1.5.x"
  },
  "overrides": {
    "foundation-sites": {
      "main": [
        "dist/foundation.css",
        "dist/foundation.js",
        "assets/foundation.scss"
      ]
    },
    "jquery-ui": {
      "main": [
        "jquery-ui.js",
        "ui/i18n/datepicker-fr.js"
      ]
    }
  }
}

Any help is much appreciated. Thank you in advance.

**Comment by crisbeto** [comment]
It works for me. Try checking if the files are in your `bower_components` directory. Otherwise it might be something wrong with your setup.

**Comment by ashwinmallikarjun** [comment]
@crisbeto The issue was that I was trying to get angular-material from a private bower repository when in fact it didn't have angular-material in first place. Got it fixed by adding angular-material to it. 

Thanks for your reply.
