### ISSUE TITLE
New theming system issue with intent classes

### ISSUE THREAD

**Issue by PaulMougel** [angular/material#965]
47f0d09e9ebd87891703fa2b7e81355ce3952a86 changed the way theming is handled (awesome change by the way!), but I don't quite understand the role of the `md-primary`, `md-accent` and `md-warn` classes anymore.

The documentation says:

> Most components in Angular Material support intention classes as expected, including:
md-button
md-checkbox
md-progress-circular
md-progress-linear
md-radio-button
md-slider
md-switch
md-tabs
md-text-float
md-toolbar

Sometimes their behavior isn't consistent between elements, in particular when no class is specified some elements take the `accent` color: is it a bug or a feature?

Check out [this Plunker](http://plnkr.co/edit/vnWsb8IOOhoctI9Jv2hX?p=preview), with a custom-made purple theme.

![image](https://cloud.githubusercontent.com/assets/1788596/5505265/5a6b5218-878f-11e4-80f4-3fd0b38bdcba.png)
![image](https://cloud.githubusercontent.com/assets/1788596/5505271/5d968782-878f-11e4-97b5-2908581a8138.png)
![image](https://cloud.githubusercontent.com/assets/1788596/5505273/646f104c-878f-11e4-9dbb-f6896a7f1f60.png)

**Comment by ajoslin** [comment]
Radio, checkbox, and switch default to the accent color. This is according to the spec: http://www.google.com/design/spec/components/switches.html

However, I never ilked this approach.  I think it would be better to make them use the primary color by default, and only use accent when specified.

**Comment by ajoslin** [comment]
@rschmukler any objections to this?

**Comment by rschmukler** [comment]
Nope, fine with me

**Comment by ajoslin** [comment]
Done via 8cbfeadfb32e19e855b6280983784fe0a8a516cb
