### ISSUE TITLE
Needed: Documentation on how to use colors to match material components

### ISSUE THREAD

**Issue by marcospgp** [angular/material#966]
It would be nice to have some documentation on which hues of the colors to use in order to math the other components. Right now I have to resort to the documentation to figure that out, and it's gotten even harder since the last update that implemented the theming feature (using the theming provider).

 Thanks!

**Comment by ajoslin** [comment]
You want to know which colors we implemented as the defaults for each hue?

Like this? https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L62-L77

Yes, we can document these, but I want to be sure we're on the same page.

**Comment by MarcosPortugal** [comment]
No, I meant more like having a information box or something for each component where it says which hues are used (400, 500, etc.) for each part of the component so it gets easier to make new components fit with the design :)

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
