### ISSUE TITLE
How to update Dialog.prompt input value after Dialog shown

### ISSUE THREAD

**Issue by raveesh08** [angular/material#9661]
After showing dialog.prompt(),default input control ll be shown... I want to update input control value from Controller.... I am not talking about initial value....
InitialValue ll be set before showing dialog... But I want update the value after showing the dialog and before closing

**Comment by DevVersion** [comment]
This is not possible with that preset. You might need to create your own preset, or just manually open a dialog with a custom template.

See https://material.angularjs.org/HEAD/api/service/$mdDialog
```js
$mdDialogProvider.addPreset('testPreset', {
  options: function() {
    return {
      template:
        '<md-dialog>' +
          'This is a custom preset' +
        '</md-dialog>',
      controllerAs: 'dialog',
      bindToController: true,
      clickOutsideToClose: true,
      escapeToClose: true
    };
  }
});
```
