### ISSUE TITLE
`md-nav-item` ignores `disabled`-attribute

### ISSUE THREAD

**Issue by Jentsch** [angular/material#9667]
**Actual Behavior**:
-  `What is the issue? *` `md-nav-item` ignores `disabled`-attribute
-  `What is the expected behavior?` shown in the demo as manual disabled

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/ozBBya
-  `Details:` notice the difference between the two tabs "Attempt to disable" and "Manual disabled"

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.0

**Additional Information**:
-  `Browser Type: *` tested on desktop, but assume all
-  `Browser Version: *` tested firefox and chrome, but assume all
-  `OS: *`tested on Linux, but assume all
-  `Stack Traces:` no

**Comment by crisbeto** [comment]
You might want to update your Codepen since it uses `disable="1"` instead of `disabled="1"`. After changing, the behaviour still seems broken though.

**Comment by Jentsch** [comment]
Thanks, I updated the codepen.

**Comment by maxjoehnk** [comment]
There is no support for the disabled attribute on md-nav-item right now.
I've already opened a pull request for ng-disabled and disabled support.

#9613

**Comment by Jentsch** [comment]
In this case I close this issue, because it is a duplicate of #9613.

**Comment by changran52m** [comment]
So, any updates here?

**Comment by IMM0rtalis** [comment]
@maxjoehnk any updates? the two PRs are closed as far as i see it.

**Comment by pnag90** [comment]
Any update? @maxjoehnk

**Comment by Splaktar** [comment]
@maxjoehnk had another PR (https://github.com/angular/material/pull/10202) but like https://github.com/angular/material/pull/9613 he ran into issues with a bad rebase and the PR was closed.

If Max or someone else would like to re-submit the PR, we would be happy to take a look at a clean PR and try to get it merged.
