### ISSUE TITLE
jquery is giving me touch delay and microinteraction delay in iOs application only.

### ISSUE THREAD

**Issue by rahulgupta20nov** [angular/material#9668]
Hi Angular Material Team,

I am developing a ios iPad application in Angular-material. If I am not using jquery then there have no touch delay also have no micro-interaction delay(ripple effect). If I am using jquery lib before angular. then it gives problem in the application in touch and micro-interaction. So it is the as expected thing or there has any alternative to resolve this problem. Because I am using many libraries in my project.

**Comment by DevVersion** [comment]
Yeah Angular Material does not intercept into clicks if jQuery is loaded.

_Quote from the source_
> In some scenarios on Mobile devices (without jQuery), the click events should NOT be hijacked.
   
> `mdGestureProvider` is used to configure the Gesture module to ignore or skip click hijacking on mobile devices.

Here is the line, which includes the check for jQuery.
- https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js#L85

---
I'm actually not sure why we don't enable the click hijacking with jQuery, but anyways we are going to fix a bunch of issues with the HammerJS plans we have. #9362

**Comment by DevVersion** [comment]
Closing this into #9362
