### ISSUE TITLE
Issue: Foreground primary color is 0.73 grey while it should be 0.87 as per google specification

### ISSUE THREAD

**Issue by MarcosPortugal** [angular/material#967]
See here the wrong value https://github.com/angular/material/blob/master/src/core/style/variables.scss

And here the specification http://www.google.com/design/spec/style/color.html#color-ui-color-application

**Comment by ajoslin** [comment]
It's 0.87. The variable in the scss file is being removed.

Check here: https://github.com/angular/material/blob/master/src/core/services/theming/theming.js#L39
