### ISSUE TITLE
Angular Material broken on chrome version 53.~

### ISSUE THREAD

**Issue by dzfweb** [angular/material#9673]
I've an web application with AngularJS and Angular Material.
It works fine on Firefox. On chrome, just versions lower then 53.

angular-material version: 1.1.1

**Firefox**
![screenshot_37](https://cloud.githubusercontent.com/assets/10212321/18759564/6b48673a-80d3-11e6-8cbf-1707d0f2d6cd.png)

**Chrome 52.0.2743.116**
![screenshot_38](https://cloud.githubusercontent.com/assets/10212321/18759565/6b5af2c4-80d3-11e6-82eb-c8690cb844f6.png)

**Chrome 53.0.2785.116**
![error-novo](https://cloud.githubusercontent.com/assets/10212321/18759559/60f2098a-80d3-11e6-8ec9-69b5d3fd482d.gif)

The error begins when page is scrolled. The fields seems to be fixed. I searched for any class with any problem, but everything seems to be ok. I updated material design and angular to the last stable version.
I tested with oldest version without success.

**Comment by crisbeto** [comment]
This seems kind of trippy. I'm on Chrome 53 and I tried the input demo, which has a very similar layout, and it seems to be working fine. Can you post a Codepen that shows it breaking, otherwise it could be something in your own code.

**Comment by dzfweb** [comment]
i'll close this issue, i've found a conflict between angular-material and material-design-lite in my code.
