### ISSUE TITLE
toast: fails to clean up dialog scopes if the new ones are created too fast

### ISSUE THREAD

**Issue by imdark** [angular/material#9677]
**Actual Behavior**:
-  `What is the issue? when new toast dialogs are created before the old once had a chance to finish hiding the old elements are removed but their scope is not destroyed`
-  `What is the expected behavior? for the scopes of the old toasts to be removed after we stop making new once`

**CodePen** (or steps to reproduce the issue): http://codepen.io/anon/pen/dpNqQo
-  `CodePen Demo which shows your issue:http://codepen.io/anon/pen/dpNqQo`
-  `Details:It prints all the scope ids currently under the rootScope, pressing the slow down button will allow the old scopes to catch up, speed up will resume the original toast messages speed, pressing stop toggles creating new toasts`

**Angular Versions**: 1.3.15
-  `Angular Version:1.3.15`
-  `Angular Material Version:1.1.0-rc5, 1.0.9`

**Additional Information**:
-  `Browser Type: chrome`
-  `Browser Version: 53.0.2785.116`
-  `OS: mac os x`
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by DevVersion** [comment]
I will investigate at this, because of the recent changes to the interim elements.

**Comment by imdark** [comment]
I went a little bit into it, I belive the source of the issue is a combination of the fact 
InterimElementFactory.show() contains this line that calls calls cancel on all other dialogs:

var hideExisting = !options.skipHide && stack.length ? service.cancel() : $q.when(true);
that eventually calls cancelAutoHide()
+
this line in toastDefaultOptions.onRemove:
     return ((options.$destroy == true) ? element.remove() : $animate.leave(element)).then
throws an exception when $destroy == true since element.remove() doesn't return a promise
il try to make a pull request later today

**Comment by DevVersion** [comment]
Cool looking forward to it. Just tested this issue against the recent $$interimElement changes we've made, but those were not the culprits.

**Comment by imdark** [comment]
replacing those lines does not completely fix the issue, but it does imporove it, I am still researching
