### ISSUE TITLE
 Deleting the chip created with the autocomplete feature causes the unhandled error. It does happen only after clicking on the 'x' icon. 

### ISSUE THREAD

**Issue by voiceactivity** [angular/material#9679]
**Actual Behavior**:
 -  `What is the issue? ` Deleting the chip created with the autocomplete feature causes the unhandled error. It does happen only after clicking on the 'x' icon. If the chip deleted using the keyboard 'Delete', there is no error.
 -  `What is the expected behavior?` Deleting the chip using the 'x' button should not throw unhandled exception.

**CodePen** (or steps to reproduce the issue): https://material.angularjs.org/1.1.1/demo/chips
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/1.1.1/demo/chips
 -  `Details:` Open dev console -> go to the demo link above ->See example "Use md-autocomplete to build an ordered set of chips." [Search for vegetable item] -> add a chip from autocomplete -> delete chip by clicking on x icon.
This happens in our production code as well.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: Chrome, FF, Opera, Edge`
 -  `Browser Version: all mentioned latest`
 -  `OS: OSX, Windows 10`
 -  `Stack Traces:`
angular.js:13550TypeError: Cannot read property 'nextTick' of undefined
    at e.removeChipAndFocusInput (angular-material.min.js:14)
    at fn (eval at compile (angular.js:14432), <anonymous>:4:516)
    at b (angular.js:15485)
    at e (angular.js:25018)
    at n.$eval (angular.js:17229)
    at n.$apply (angular.js:17329)
    at HTMLButtonElement.<anonymous> (angular.js:25023)
    at Qf (angular.js:3456)
    at HTMLButtonElement.d (angular.js:3444)

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is fixed within `master`.

**Comment by jensravn** [comment]
Heres a link to the commit https://github.com/angular/material/commit/a3b3e7b037fb02acae5c1d979e8373d7e8c93dfd
