### ISSUE TITLE
placeholder autocomplete not working fine. it's hiden

### ISSUE THREAD

**Issue by AdwardNguyen** [angular/material#9689]
**Actual Behavior**:
 -  `What is the issue? *`placeholder autocomplete
 -  `What is the expected behavior?` please help me fix it

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`
![test](https://cloud.githubusercontent.com/assets/22392606/18810160/3444232c-82b9-11e6-9bf8-b0b5828729b3.png)

```html
<style type="text/css">
     md-autocomplete md-autocomplete-wrap input::-moz-placeholder,
    md-autocomplete md-autocomplete-wrap input:-moz-placeholder,
     md-autocomplete md-autocomplete-wrap input::-webkit-input-placeholder {
        color: red; margin:0; text-align:left; padding:0; display:normal; opacity:1; flex:none; vertical-align:text-top;
    }

    md-autocomplete md-autocomplete-wrap input {
        color: green;
    }
</style>
<!--<div layout="column" ng-cloak class="md-autocomplete-suggestions-container" >-->
        <md-autocomplete md-selected-item="selectedItem"
                         md-search-text-change="searchTextChangesearchText"
                         md-search-text="searchText"
                         md-selected-item-change="selectedItemChange(item)"
                         md-items="item in querySearch(searchText)"
                         md-item-text="item[displayProperty]"
                         md-min-length="0" placeholder="Test" aria-disabled="false" md-menu-class="autotest-md">
            <md-item-template>
                <!--<span md-highlight-text="ctrl.searchText" md-highlight-flags="^i">{{item.TenBacSi}}</span>-->
                <span md-highlight-text="ctrl.searchText" md-highlight-flags="^i">{{item[displayProperty]}}</span>
            </md-item-template>
        </md-autocomplete>
<!--</div>-->
```

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Google Chrome
 -  `Browser Version: *`Version 53.0.2785.116 m
 -  `OS: *` WINDOWS 10 Enterprise
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by asirigada** [comment]
facing the same issue...

**Comment by DevVersion** [comment]
This issue is still not providing much information..

From what I _could_ understand, having a custom placeholder color does not work within the autocomplete?

- Works for me on Chrome, Firefox, IE11: http://codepen.io/DevVersion/pen/WGkjXG?editors=1100

I can reopen the issue if a demo, which shows the issue, is provided.
