### ISSUE TITLE
md-autocomplete alignment problem using layout-margin

### ISSUE THREAD

**Issue by oostmeijer** [angular/material#9692]
**Actual Behavior**:
 -  `What is the issue? *`
When using md-autocomplete (floating label) in an element with layout='row' and layout-margin='' it doesn't align correctly with the other form elements.
 -  `What is the expected behaviour?`
The md-autocomplete field aligns with other form elements

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/oostmeijer/pen/xEdxop
 -  `Details:`
Keep your screen wide enough to have both fields on one row. The autocomplete field is lower than the first 'normal' form field.

**Angular Versions**: *
 -  `Angular Version:` 1.5.7
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Safari, Chrome
 -  `Browser Version: *`Versie 9.1.1 (11601.6.17), Versie 53.0.2785.116 (64-bit)
 -  `OS: *` OSX 10.11.5
 -  `Stack Traces:`

----

**Comment by ThomasBurleson** [comment]
Won't fix. See comments in PR #9748
