### ISSUE TITLE
mdSpeedDial: With mouseenter event need two click to open (mobile)

### ISSUE THREAD

**Issue by omar10594** [angular/material#9694]
**Actual Behavior**:
-  `What is the issue? *` On mobile devices speed dial that use mouseenter to open need two clicks to open.
-  `What is the expected behavior?` The speed dial should open when click one time the button .

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` https://codepen.io/omar10594/pen/jrqgwJ
-  `Details:` Need a mobile device or chrome devTools.

![dooubleclick](https://cloud.githubusercontent.com/assets/9435510/18844088/a487f416-83d0-11e6-9b43-bb7c2f831cb1.gif)

Same with the example from docs.
![needdoubleclick](https://cloud.githubusercontent.com/assets/9435510/18844090/a620d054-83d0-11e6-937f-991f09b83725.gif)

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

**Comment by berisberis** [comment]
bump for this

**Comment by ElPsyCongro** [comment]
+1

**Comment by Splaktar** [comment]
I was able to reproduce this with `1.1.1`. I tested again with `1.1.20` using this [updated CodePen](https://codepen.io/Splaktar/pen/bGbqawr?editors=1010#0) and the issue appears to have been resolved.
