### ISSUE TITLE
Can't change hue on backgroundPalettes.

### ISSUE THREAD

**Issue by clydetacoma** [angular/material#9696]
**Actual Behavior**:
-  `What is the issue? *` Only the default hue on backgroundPalette is used. Specifying md-hue-2 etc. as a class does not change the background color.
-  `What is the expected behavior?` Changing the hue on the background should change the color to the color specified on the hue in the theme.

**Codepen showing the issue**:
http://codepen.io/clydetacoma/pen/GjmyzJ

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.1.1

**Comment by danethepain83** [comment]
I have noticed this same issue. Please help.

**Comment by jonycfu** [comment]
It seems like the most recent version in which `md-hue-*` classes will work with `backgroundPalette` is `angular-material@1.0.8`

Tested with `1.1.0` and `1.1.1`, but both versions ignore background hue classes.

**Comment by EladBezalel** [comment]
@clydetacoma @danethepain83 @jonycfu can any of you guys confirm it's still an issue?

**Comment by EladBezalel** [comment]
Closed due to inactivity.

**Comment by BoLaMN** [comment]
ran across this and figured out that supplying .dark() after supplying other palettes eg accentPalette() will ignore the palettes youve defined, isDark check does this [https://github.com/angular/material/tree/master/src/core/services/theming#L495](https://github.com/angular/material/tree/master/src/core/services/theming#L495)

workaround is instead of doing 

```
$mdThemingProvider
    .theme('docs-dark', 'default')
    .primaryPalette('yellow')
    .backgroundPalette('blue', {
      'default': '100',
      'hue-1': '500',
      'hue-2': '800'
    })
    .dark();
``` 

call .dark() first

```
$mdThemingProvider
    .theme('docs-dark', 'default')
    .dark()
    .primaryPalette('yellow')
    .backgroundPalette('blue', {
      'default': '100',
      'hue-1': '500',
      'hue-2': '800'
    });
```
