### ISSUE TITLE
checkbox: md-checked not visible in IE

### ISSUE THREAD

**Issue by jesusmariocalleja** [angular/material#9700]
I have a problem on ie 11. When a click the md-checkbox, it disappears (it's still there, but not visible). But if I select it as text, it appears again. It's like it renders again. I have the v1.1.0-rc.5 version.

Thanks!

**Comment by ibenzyk** [comment]
Hi,
try to edit css and add to ::after { display: block;}

**Comment by Splaktar** [comment]
I tested this on the last IE11 version against AngularJS Material 1.1.0-rc4, 1.1.0-rc.5, 1.1.4, and 1.1.10 and I was unable to reproduce this in any of those situations when using the demos in the docs. If this is still an issue we'll need a CodePen reproduction.
