### ISSUE TITLE
Question/Behaviour - $timeout - Triggers mousedown

### ISSUE THREAD

**Issue by graphefruit** [angular/material#9703]
**Actual Behavior**:
-  `What is the issue? *` 
  This is not rather an issue this is rather an behaviour question about some controls inside the core component.
  I've stumble accross this code, inside the **MdButtonDirective**.

```
if (!element.hasClass('md-no-focus')) {
      // restrict focus styles to the keyboard
      scope.mouseActive = false;
      element.on('mousedown', function() {
        scope.mouseActive = true;
        $timeout(function(){
          scope.mouseActive = false;
        }, 100);
      })
      .on('focus', function() {
        if (scope.mouseActive === false) {
          element.addClass('md-focused');
        }
      })
      .on('blur', function(ev) {
        element.removeClass('md-focused');
      });
    }
```

The question for me is: Why does $timeout is needed here to set the **scope.mouseActive**, and therefore a digestcycle is triggered.

Would be `$timeout(func,100,false)` or `setTimeout()` here better? 
Indeed this shouldn't be a big problem, but the triggered digestcycle shouldn't be needed also.

On the button directive the problem in my opinion is the smallest, but using this in the checkbox directive, and the user checks or unchecks 5-10 boxes, we get 5-10 more digestcycles.

This code parts are also existing in `MdCheckboxDirective` or 'mdListItemDirective' and some more.
-  `What is the expected behavior?` Using `$timeout(func,100,false)` or `setTimeout()`

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 53.0
-  `OS: *` Win 8.1

Greetings 
Graphefruit

**Comment by DevVersion** [comment]
Great question! We have solved this within `master`. See  SHA  https://github.com/angular/material/commit/34823ac36553353394f70ff9de2c53f63a5611ac
