### ISSUE TITLE
Invisible tooltip in Firefox when inside md-button

### ISSUE THREAD

**Issue by mkhbragg** [angular/material#9707]
**Actual Behavior**:
-  `What is the issue? *`

When an `md-icon` is contained within `md-button` the tooltip does not show up when you hover over the icon in Firefox. The tooltip does show up if `md-icon` is not inside `md-button`. 
-  `What is the expected behavior?`

I expect the tooltip to show up whether or not the `md-icon` is inside `md-button`. Works fine in Chrome and Safari, but not in Firefox.

**CodePen** (or steps to reproduce the issue): *

http://codepen.io/mhbragg/pen/jrwPXK?editors=1010

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` 
  
   Works as expected in Chrome and Safari
   Does not work in Firefox
-  `Browser Version: *`
  
   Chrome: 53.0.2785.116
   Safari: 9.1.1
   Firefox: 48.0
-  `OS: *`
  
   OS X Yosemite 10.10.5

**Comment by clshortfuse** [comment]
What you are experiencing is a Firefox bug related to child elements of buttons (md-icon) do not receive mouseover/hover events.

https://bugzilla.mozilla.org/show_bug.cgi?id=843003

md-tooltip should be a direct child of md-button as shown in the demos: https://material.angularjs.org/latest/demo/tooltip
