### ISSUE TITLE
md-virtual-repeat not rendering all items on md-list

### ISSUE THREAD

**Issue by frikkievb** [angular/material#9711]
**Actual Behavior**:
 -  `What is the issue? *`
Not all items are being rendered on md-list when list is implemented as md-virtual-repeat-container.
 -  `What is the expected behavior?`
I expected that all items be rendered.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/frikkievb/pen/VKbEXZ
 -  `Details:` I found that certain values are not being rendered on the md-list.  On my side it is usually items starting on the 0 index of each page.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` v1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 53.0.2785.116 m
 -  `OS: *` Windows 10
 -  `Stack Traces:` None

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
The items are rendering properly, just the onDemand object does not return the item immediately.

Read more about this in https://github.com/angular/material/issues/8638#issuecomment-227507547

> The VirtualRepeat does not know when the page has been fetched because it's in the same $digest.

Try to run the fetching in another digest to let the VirtualRepeat know that something changes, or manually trigger an update (needs to be exposed)

Going to close this issue and tracking with https://github.com/angular/material/issues/8638
