### ISSUE TITLE
Floating label for autocomplete  is not clickable on IE10

### ISSUE THREAD

**Issue by jcubic** [angular/material#9712]
**Actual Behavior**:
 -  `What is the issue? *` in IE10 when you have floating label in autocomplete and you click on it you don't have focus in input box
 -  `What is the expected behavior?`: clicking on floating label in IE should give focus to input box

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/jcubic/pen/yaXPgA
 -  `Details:` click on autocomplete floating label in IE10

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Internet Explored
 -  `Browser Version: *` 10
 -  `OS: *` Windows 7
 -  `Stack Traces:`

**Comment by DevVersion** [comment]
Angular Material does not support IE10, so we won't be able to fix this on our side.

![](https://cloud.githubusercontent.com/assets/210413/18553899/f3fbfbca-7b27-11e6-81c9-2937950c808e.png)
