### ISSUE TITLE
md-autocomplete with md-floating-label attribute doesn't have a clear cross on the right

### ISSUE THREAD

**Issue by julienmartin** [angular/material#9715]
**Actual Behavior**:
-  `What is the issue? *` When using the md-autocomplete with a md-floating-label attribute, the cross in order to clear the input is not available
-  `What is the expected behavior?` Having the cross available even if we use the md-floating-label attribute

**CodePen** (or steps to reproduce the issue): *
-  `Details:` [Official Documentation](https://material.angularjs.org/latest/demo/autocomplete) : Floating Label example

**Angular Versions**: *
-  `Angular Version:` All
-  `Angular Material Version:` 1.1.1

**Comment by mckenzielong** [comment]
I always end up sticking a button beside my selects or floating autocompletes to clear them -- I would love a built in option for this.

**Comment by DevVersion** [comment]
@julienmartin @mckenzielong This enhancement recently landed in `master` with SHA https://github.com/angular/material/commit/70cecda543e9e4724307a674fde08d7330f024d8
