### ISSUE TITLE
md-checkbox not rendering with MaterializeCSS

### ISSUE THREAD

**Issue by andreifloroiu** [angular/material#9716]
**Actual Behavior**:
- Besides Angular Material I also use [MaterializeCSS](http://materializecss.com/getting-started.html), mostly because of the icons working out-of-the-box and columns and rows (dunno much about CSS), and cards.
- No problems until now with `md-checkbox`.

**CodePen** (or steps to reproduce the issue): 
- [Sample](https://codepen.io/andreifloroiu/pen/jrwprZ), my scripts/CSS are included in the order presented in the pen
- [Tried debugging CSS](https://s.codepen.io/andreifloroiu/debug/jrwprZ) (don't forget F12 on the blank page) but couldn't find the source of the problem...

**Expected Behavior**:
- `To work... :(`
- Couldn't find anything about integration problems with MaterializeCSS, [on this page](https://material.angularjs.org/latest/getting-started) or Google or StackOverflow

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` SRWare Iron (Chromium)
 -  `Browser Version: *` 46.0.2450.0
 -  `OS: *` Windows 10 x64
 -  `Stack Traces:` -no need-

**Comment by DevVersion** [comment]
Yeah it looks like MaterializeCSS targets the `[type="checkbox"]` selector, which is affecting the `md-checkbox`.

![](https://i.gyazo.com/8875b306a81c95500ff780e823cc6eba.png)

We can theoretically fix this (but it requires a few ugly CSS selectors) - I would rather add to the docs that MaterializeCSS has problems together with ngMaterial.

**Comment by andreifloroiu** [comment]
Ouch, thanks though...
