### ISSUE TITLE
Feature Request: md-button-toggle component

### ISSUE THREAD

**Issue by PseudoSky** [angular/material#9722]
**Actual Behavior**:
-  `What is the issue? *`
  Switches only toggle between true or false `{ 0, 1 }`
-  `What is the expected behavior?`
  There are some instances where a switch style input can be useful for selecting between a set of options with more than two elements `{ 0, 1, 2, ... }`
  EX: 
  Sound Profiles `{ "Silent", "Vibrate", "Ring" }`
  Workflow `{ "To do", "In Progress", "Complete" }`

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  https://codepen.io/pseudosnow/pen/PGKYow
-  `Details:`
  Not completely implemented with ng material, just wanted to see if it seemed useful.

**Angular Versions**: *
-  `Angular Version:`
-  `Angular Material Version:`

**Additional Information**:
-  `Browser Type: *`
-  `Browser Version: *`
-  `OS: *`
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by DevVersion** [comment]
I think that's a pretty useful component.

In Material 2 it's already available and called `md-button-toggle`, so it might be worth implementing it on Material 1.x as well.

**Comment by PseudoSky** [comment]
I modified the styling of [rzSlider](https://github.com/angular-slider/angularjs-slider) to look more material. 
![](http://g.recordit.co/9Sig4srHZt.gif)

I think their directive interface for rzSlider is interesting but has way too many options. I think a simple clear way to implement it would be with the steps option
`<md-slider ... steps="[ 'step1', 'step2', 'step3'  ]" >`
or
`<md-slider ... steps="{ 'label1': 'value1' , 'label2': 'value2' }" >`

**Comment by Splaktar** [comment]
We have no plans to implement this component at this time. Looking for third party solutions is recommended.
