### ISSUE TITLE
md-datepicker displays wrong date with timezone and initialized model

### ISSUE THREAD

**Issue by mfisch04** [angular/material#9725]
**Actual Behavior**:
 -  `What is the issue? *`

Opening an md-datepicker with the timezone set to UTC with the date already initialized still displays the date and calendar with the localized date.

The datepicker $formatter is being called before the date input $formatter which does the time zone conversion.  I tried adding a custom $formatter, but it's also called after the datepicker.
 -  `What is the expected behavior?`
Display the date in UTC.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
http://codepen.io/anon/pen/RGkkYE
 -  `Details:`
myDate initilized to "2016-09-28T00:00:00.000Z" displays 9/27/2016 and calendar defaults to 9/27.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *`52.0.2743.116
 -  `OS: *` Windows 7
 -  `Stack Traces:` NA

**Comment by jayss** [comment]
Yes, I meet the similar issue, but it may come from the Date() because datepicker require that ng-model is date instance. 
For example, My timezone is UTC8, if my value is 09-28 00:00:00, when my form submit, the value will change to 09-27 16:00:00
