### ISSUE TITLE
Scroll Bar does not work with angular-material.min.css

### ISSUE THREAD

**Issue by jdmagic21** [angular/material#9728]
**Actual Behavior**:
-  You are not able to click on the scrollbar itself and scroll up or down the page because the CSS height attribute is set to 100%.
-  You should be able to click on the scrollbar like on other sites. 

**Angular Versions**: *
-  `Angular Version:`  1.5.0
-  `Angular Material Version:` 1.1.0

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 53.0.2785.116 
-  `OS: *` Windows

**Comment by crisbeto** [comment]
Could you give an example of a page where this happens?

**Comment by Splaktar** [comment]
Closing since a demo CodePen was not provided.
