### ISSUE TITLE
Breaking SCSS Theme Templates

### ISSUE THREAD

**Issue by ericrini** [angular/material#973]
So I saw this commit in master today.

```
Commit: 47f0d09e9ebd87891703fa2b7e81355ce3952a86 [47f0d09]
Parents: c62b970536
Author: Andrew <andrewtjoslin@gmail.com>
Date: December 5, 2014 at 5:34:19 PM EST
Commit Date: December 16, 2014 at 12:45:35 PM EST

feat(theming): use $mdThemingProvider

BREAKING CHANGE: Themes are no longer defined by linked CSS files.

Themes are now defined through Javascript only. A 'theme template' is
bundled into angular-material.js, and then Javascript is used to
generate theme css for every theme the user defines.

The `default` theme is still shipped with angular-material.
```

So FWIW, this is MAJOR bad news for us.

Instead of using your built CSS, we have been @importing and extending your SCSS structure and theme files directly (as one would do with Foundation or Bootstrap or other popular style frameworks) using a SMACSS based style architecture. We even have our own gulp task (a simplified version of your original theme build task) to build out lots of highly customized themes to white label our product.

Now that the theme .SCSS files are a frankenstein of SCSS and a proprietary template language, I'm not sure where to go with it. I guess I was mostly posting to let you guys know this was going to cause a lot of pain in our specific case.

I guess we'll have to figure out how to leave the old theme files intact somehow and manually keep them up to date. :(

**Comment by rschmukler** [comment]
Closing this issue for now. Breaking out the theming logic is definitely something that we should look into. That being said, as @ajoslin said, this makes a radical number of themes possible with very little over-the-wire data transfer. It's much more powerful than what we were able to achieve with scss, and it doesn't impose a pre-processor (sass) on developer's build environments to modify themes.

**Comment by sime** [comment]
Styling via Javascript is a very novel concept for most front end developers who typically implement designs and palettes rather than designing themselves.

This will be a very large barrier to entry for most front end developers. The proposed build system seems worthwhile.

**Comment by johannesjo** [comment]
I can understand the reasons behind that decision, but I got to say, that I think it is a bad one. I often work together with devs and even designers that don't know much about angular and sometimes even JavaScript. It's not good that they have to learn a new system for styling the components when they're used to doing things css-only. This also violates the principle of separation of concerns. Call me old-fashioned, but as I general rule of thumb I believe in 'styling should be done in stylesheets'.

**Comment by hofnarwillie** [comment]
The javascript based system will only benefit a small percentage of projects that require large amounts of colour schemes and palettes, however, majority of projects don't need this and majority of development teams will be negatively affected by this for the following two reasons: 

* As @johannesjo says, you lose the separation of concerns.
* The SASS build system will cannot be extended to your own custom components

...and probably a few more issues. This is a deal breaker for me

**Comment by johannesjo** [comment]
Why not simply provide a default color set for the main css file and if people want to have different colors they could compile there own by using the sass files instead like with bootstrap-sass and ionics sass files. Shouldn't it be possible to replace all those variables by sass variables? If you really want to have multiple themes for the same website, this could also be handled via a sass loop for example and the theming relevant part of the sass files is not too big so the final css file wouldn't be too much bigger.

**Comment by AntonKL** [comment]
For my project this was quite handy, but, is there a way to extend the css stylesheet that gets injected by Angular? I want to add some more classes that the theme shall be applied to... Documentation does not mention this.

**Comment by rschmukler** [comment]
@AntonKL currently there isn't support for extending the stylesheets handled by the theming engine. Some day this might be possible.

@hofnarwillie The javascript theming engine does introduce some extra complexity, but it offers the following:

- We don't dictate your build tool stack. Why should sass be a requirement for using ngMaterial / having themes? Should we also support stylus? What about Less, Rework, CSSNext, etc.? Ultimately we don't want to have any opinion on your build tools, nor be supporting 100 different ways of generating custom CSS.

- Styles are transmitted exactly once no matter how many themes you have. This means less data over the wire, a big win for the end user that consume your applications. This is especially beneficial for applications with multiple themes

Ultimately, if your application is consistent with material design guidelines there are very few exceptions to the color rules that you configure in your theming config. If they aren't, then writing custom CSS (in your flavor of pre-processing tool of choice) doesn't seem like a huge problem, especially since there are other open-source plugins to help with color-palette related tasks:

- [sass-material](https://www.npmjs.com/package/sass-material-colors)
- [material-color](https://github.com/mrmlnc/material-color) with support for less, stylus, and sass

**Comment by breity** [comment]
So if I want to change SCSS variables or make some sizing/layout tweaks to certain elements, I understand that I'll need to edit the SCSS files and make my own builds. That's fine.

But I want to be able to include Angular Material in a larger git project and do some customizations. I also want to be able to update Angular Material when needed (new releases). So, is the best solution right now to include the project as a git (remote) subtree in our repository? Then I can make the changes I need and create custom builds, commit those changes to our repo, and update the subtree periodically by pulling from the remote. Does that workflow make sense at this point?

**Comment by ThomasBurleson** [comment]
@breity Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by breity** [comment]
@ThomasBurleson Okay, sure.  Thanks.

**Comment by laicosly** [comment]
Please go back to scss theming.

**Comment by johannesjo** [comment]
> We don't dictate your build tool stack. 
But you're forcing people to work with your own custom js system. And while sass is pretty common, well established and not too hard to port to less or stylus (make it it's own repo + module for that matter) the combination of the two is.

**Comment by S8nsick66** [comment]
Please go back to scss theming.

**Comment by jdbranham** [comment]
Any further developments for this?
I'm also trying to use the colors in my own scss classes.

**Comment by jdbranham** [comment]
I ended up abstracting the values into a separate JSON file, them sharing them between scss and my javascript.
Here is one way - 

https://www.jonathanfielding.com/how-to-use-your-sass-variables-inside-your-javascript/
