### ISSUE TITLE
Autocomplete locking navigation scroll issue was re-introduced in v 1.1.1

### ISSUE THREAD

**Issue by gegana** [angular/material#9730]
**Actual Behavior**:
 -  `What is the issue? Using md-autocomplete in combination with md-chips will often cause a screen lock issue whereby you cannot scroll on the page. I have not tested this behavior with only using md-autocomplete.`
 -  `What is the expected behavior? The expected behavior is that after you have selected an item in an autocomplete dropdown, the navigation scrollbar should appear again.`

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: Chrome, Edge, Firefox`
 -  `Browser Version: latest`
 -  `OS: Windows 10 Pro`

----

I downgraded my application to use 1.1.0 which fixes the bug our clients were facing.

**Comment by DevVersion** [comment]
I was not able to reproduce this issue in a codepen.

Please provide a demo, which shows that the issue still is valid.

> http://codepen.io/DevVersion/pen/gwGpgY

I can reopen that issue if we are able to see the issue.

**Comment by gegana** [comment]
Is there a way to disable the component from disabling the scrollbar? This is annoying when you test it in mobile browser since the screen is so small and plus when you are typing in an input field, the screen becomes even smaller with the keyboard taking up half the screen...
