### ISSUE TITLE
menu: md-menu-item displays wrong position and zoom out on mobile (Android)

### ISSUE THREAD

**Issue by phongca22** [angular/material#9741]
**Actual Behavior**:
-  `What is the issue? *` md-menu-item is broken on mobile (Android).
-  `What is the expected behavior?` keep position and sizing

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` https://codepen.io/phongca22/full/yazGzB
-  `Details:`

Case 1: focus input and type something. When click md-menu button, the md-menu-item is fly out and become smaller.

Case 2: focus input, keyboard panel is show. Just close keyboard panel and click md-menu button. Try again many times.

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` Latest
-  `OS: *` Android
-  `Stack Traces:`

**Comment by Splaktar** [comment]
I can't reproduce this on Android 10 with Chrome 80 using the above CodePen or my [updated CodePen](https://codepen.io/Splaktar/pen/jObWywL) in [debug view](https://cdpn.io/Splaktar/debug/jObWywL/PBkNWnyxyZyM).
