### ISSUE TITLE
Can no longer use custom directive on md-datepicker

### ISSUE THREAD

**Issue by achuinard** [angular/material#9747]
When I started using md-datepicker in my Angular Material app, I wanted my ng-model to be simply an epoch, not a Date object. I crafted the following directive which did a fine job of allowing me to use a number instead of a Date for my `ng-model`. It also used moment.js to offset the epoch according to my app user's own 'timezone' setting - freeing me from the browser forcing all Dates to be in the local timezone!

```
 .directive('timezonedDate', function () {
        return {
            require: 'ngModel',
            restrict: 'A',
            link: function (scope, elem, attrs, ngModel) {
                var toView = function (val) {
                    if (val) {
                        var offset = moment(val).utcOffset();
                        var date = new Date(moment(val).subtract(offset, 'm'));
                        var newOffset = moment.tz.zone(attrs.timezone).offset(date);
                        return new Date(moment(date).subtract(newOffset, 'm').unix() * 1000);
                    }
                };

                var toModel = function (val) {
                    var offset = moment(val).utcOffset();
                    var date = new Date(moment(val).add(offset, 'm'));
                    var newOffset = moment.tz.zone(attrs.timezone).offset(date);
                    return moment(date).add(newOffset, 'm').unix() * 1000;
                };

                ngModel.$formatters.unshift(toView);
                ngModel.$parsers.unshift(toModel);
            }
        };
```

However, the new md-datepicker throws the following error:

`The ng-model for md-datepicker must be a Date instance. Currently the model is a: number`

Can anyone suggest a better way to do this? I suppose this is not a  'bug', but my custom (appearingly simple) directive has broken with the latest Angular Material (1.1.0), and I don't know how to fix this specific but hopefully easy issue.

**Comment by crisbeto** [comment]
There's PR #9554 that will let you do this. I'm not quite sure why your directive stopped working, but it's probably because the order of the `$parsers` and `$formatters` got changed. You can try registering them earlier by using this:

```js
ngModel.$formatters.push(toView);
ngModel.$parsers.push(toModel);
```

Instead of this:

```js
ngModel.$formatters.unshift(toView);
ngModel.$parsers.unshift(toModel);
```

Alternatively, you can try registering your parsers and formatters in the `preLink` step.

**Comment by achuinard** [comment]
Those other PRs are concerned with Date strings instead of actual epochs, but looking at your code, new Date(millisecondEpoch) will work.

It's almost as if I want to get rid of the existing formatters and parsers, right? Not simply add to them...

Pushing instead of unshifting did not work. Thank you for your suggestion.

**Comment by achuinard** [comment]
Also, I think the directive stopped working because the ng model controller used to not throw an actual exception?

**Comment by crisbeto** [comment]
Alright, what about trying to add the formatters and parsers earlier inside `preLink`. You need to turn this:

```js
{
  link: function() { ... }
}
```

Into this:

```js
{
  link: {
    pre: function(){ ... }
  }
}
```

**Comment by achuinard** [comment]
Unfortunately, it did not work if I prelink the new parser / formatter. Is it possible to clear the parsers / formatters? Or I suppose I need those other ones to work, mine is simply an addition.

**Comment by crisbeto** [comment]
Yeah, those parsers do some extra work and should be there. 
I just got some time to play around with it. You need to set the priority of your directive so it executes before the datepicker (e.g. in this case a priority of 1 should be enough). [Here's a simplified codepen that shows it working.](http://codepen.io/crisbeto/pen/BLmrwg?editors=1010) I've taken out the moment.js parts since I'm not too familiar with it, however it should work in your case as well.

**Comment by achuinard** [comment]
Amazing - using `push` instead of `unshift` and setting my directive priority to 1 has fixed all problems!
