### ISSUE TITLE
docs: use ng-bind for md-icon ligature documentation

### ISSUE THREAD

**Issue by clshortfuse** [angular/material#9750]
**Actual Behavior**:
 -  `What is the issue? *` Current documentation for md-icon uses Angular text markup (eg: `{{...}}`)
 -  `What is the expected behavior?` ng-bind should be used, to keep logic modular inside the md-icon declaration. This is also an important change for users that use multilingual support in their applications and use our demo code as a template.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/1.1.0/demo/icon

**Angular Versions**: *

 -  `Angular Material Version:`  1.1.0+

----

ping @ErinCoughlan

**Comment by ThomasBurleson** [comment]
A use case [that justifies this change] has not been presented. Documentation-alone is not sufficient since interpolation works fine. Rejecting this PR as "noise".
