### ISSUE TITLE
fab-trigger: inside md-fab-speed-dial needs a "display: block" to get the correct position in IE10

### ISSUE THREAD

**Issue by leobustamante** [angular/material#9751]
In IE10 when md-direction is set to "up", the md-fab-trigger don't float to corret position. 

You can see this BUG in the sample link of this feature. [https://material.angularjs.org/latest/demo/fabSpeedDial](https://material.angularjs.org/latest/demo/fabSpeedDial)

STEPS TO REPROCUDE:
1 - Open the link in Internet Explorer 10(emulated or not)
2 - Change the direction in the sample to "up", and test clicking the button.

This is a minor BUG, but is very quick to solve. Just need a "display: block" for the md-fab-trigger when "md-up" class is present on md-fab-speed-dial.

**Comment by Splaktar** [comment]
This is not reproducible in IE11. We no longer support IE10.
