### ISSUE TITLE
Different way to use dialog but style is different

### ISSUE THREAD

**Issue by huangjun604** [angular/material#9752]
Hi, I used two ways to achieve dialog in the same page:

 **Way 1:**

 ```
$mdDialog.show($mdDialog.confirm()
    .ok('Submit')
    .cancel('Cancel'));
```

It will generate `md-dialog-container` as:

`<div class="md-dialog-container ng-scope" tabindex="-1" style="top: 2186px;
    height: 471px;">`

 **Way 2:**

 ```
 var template = '<md-dialog>'
    + '    <md-dialog-content>'
    + '    </md-dialog-content>'
    + '    <md-dialog-actions>'
    + '      </md-dialog-actions>'
    + '</md-dialog>';

  $mdDialog.show({
      template: template,
      parent: angular.element(document.body),
      disableParentScroll: false
  });
```

It will generate `md-dialog-container` as:

`<div class="md-dialog-container ng-scope" tabindex="-1" style="top: 0px;
    height: 471px;">`

Therefore, the difference between those two is obvious:

- formal one is `top: 2186px`, which is based on the scrolling of page and make the dialog in the middle of browser 
- latter one is `top: 0px`, which is on the top of page, in this case, if your page is scrolled down, the dialog won't appear or make the page back to top

Which part in the source code is to control those added style(top: 0px)? How to make them the same, or make the latter one same as formal one. Thanks

**Two Demos:**

http://codepen.io/anon/pen/amEdYv?editors=1010#0

http://codepen.io/anon/pen/PGEkKE (If changing the AngularMateral version to 0.7.1, it will display correctly)

**Comment by DevVersion** [comment]
We are going to revisit this with the planned panel conversion #9675
