### ISSUE TITLE
select: after open option screen is stuck

### ISSUE THREAD

**Issue by rahulgupta20nov** [angular/material#9753]
Hi,
Sometime in the application, md-select totally stuck. User can't scroll or minimize md-select after select option. It's totally uncertain. It comes one's in 100.

PFA attachment of snapshot.
<img width="329" alt="screen shot 2016-10-05 at 2 35 14 pm" src="https://cloud.githubusercontent.com/assets/10140041/19107608/a9edbb8e-8b0a-11e6-97af-266f28e7b3f5.png">

**Comment by divyekhanna** [comment]
+1 this. For me, the options are not showing as well. No error in the console

**Comment by Splaktar** [comment]
No reproduction demo provided. Not able to reproduce. Please open a new issue if this is still a problem.
