### ISSUE TITLE
md-require-match misbehaviour ?

### ISSUE THREAD

**Issue by ekarudianto** [angular/material#9756]
**Actual Behavior**:
 -  `What is the issue? *` Using md-require-match attribute, after did some typing on the input box and clear it out, the validation still presist
 -  `What is the expected behavior?` I think it's logical if the input box is empty / null the md-require-match attribute should return false instead of still running

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/NRXpbY?editors=1010#0
 -  `Details:` To reproduce the issue simply : Type in some string -> after some options showed up -> cleared the input box -> The issue will appear

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` latest

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 53
 -  `OS: *` Windows 7
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is fixed in `master´ http://codepen.io/DevVersion/pen/rrpmEm?editors=1010#0

**Comment by ekarudianto** [comment]
So should I use the master version of angular-material or use the latest which is 1.1.1 ? @DevVersion
