### ISSUE TITLE
Remove @constructor jsdoc on MdChipsCtrl to prevent Closure compiled removal of $inject value

### ISSUE THREAD

**Issue by tsle** [angular/material#9758]
**Actual Behavior**:
Remove @constructor in jsdoc for angular chips. 
The issue that this fixes:
When compiled by closure, the $inject assignment to the constructor is removed, and as a result, in compiled mode, injection error occurs due to obfuscation and no $inject property.

**Angular Versions**: * - 
Angular Material Version:` 1.1

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
While we're at it, perhaps this is a problem in other places as well? We're using that annotation a few more places.

**Comment by tsle** [comment]
So far I've only seen this error on in the chips component, but it's
possible it is elsewhere too.

**Comment by jelbourn** [comment]
A nice alternative to removing `@constructor` might be to make the ngInject tool output 
`WhateverCtrl['$inject']` instead of `WhateverCtrl.$inject`; Closure Compiler always preserves properties defined with the former syntax.

**Comment by crisbeto** [comment]
After playing around with it, it looks like it happens in the cases where `@constructor` is the only directive on the line. We have a bunch of cases that use it as `ngInject @constructor` and those work properly (probably because it's considered invalid). I'm still looking for a way to do this automatically since keeping these comments in sync will get annoying.
