### ISSUE TITLE
autocomplete: clear button does not work in iOS Safari

### ISSUE THREAD

**Issue by donmccurdy** [angular/material#9764]
**Actual Behavior**:
-  `What is the issue? *`
  Clicking the mdAutocomplete <kbd>x</kbd> in Mobile Safari has no effect.
-  `What is the expected behavior?`
  Input contents should be cleared.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` https://material.angularjs.org/latest/demo/autocomplete
-  `Details:` The <kbd>x</kbd> button works correctly in Chrome on Android, but has no effect in Safari on iOS.

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` Safari
-  `Browser Version: *` ?
-  `OS: *` iOS 10.0.2
- `Device:` iPhone 6, iPhone 6S
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by donmccurdy** [comment]
[Here is a counterexample](https://gist.github.com/donmccurdy/2f8695485b55ceed08e42868ff873f08) ([source](https://gist.github.com/donmccurdy/2f8695485b55ceed08e42868ff873f08)) where it does work in iOS. I'm not sure what the difference is.

**Comment by DevVersion** [comment]
@donmccurdy Thanks. I can reproduce this and I assume this relates to the $mdGesture service.

Probably disabling click hijacking should be a workaround

```js
$mdGestureProvider.skipClickHijack();
```

**Comment by donmccurdy** [comment]
@DevVersion thanks, that sounds likely enough but i'm not seeing any effect in my (internal) app, and am not sure how to test the official site's demo. My codepen and gist demos aren't reproducing the issue at all. 😐

**Comment by DevVersion** [comment]
@donmccurdy Just tried it out as well. I can confirm the gesture do not cause the issue.

**Comment by behzadbananmokhtari** [comment]
https://codepen.io/behzadbananmokhtari/pen/PmzyXO
I have fixed this issue (at least temporarily) like this. take a look at the changes marked in the JS file.
It also made #9581 problem to go away.

**Comment by Splaktar** [comment]
Related to the previous comment, PR https://github.com/angular/material/pull/11625 has been posted which should fix https://github.com/angular/material/issues/9581.

However, as far as the clear button not working, I am not able to reproduce this on iOS `12.1.4` with AngularJS Material `1.1.12`. This issue was reported against iOS `10.0.2` which we no longer support ([current browser support](https://material.angularjs.org/latest/#browser-support)).
