### ISSUE TITLE
HTML standard select doesn't open up in Chrome mobile 53.

### ISSUE THREAD

**Issue by NickDart** [angular/material#9766]
**Actual Behavior**:
 -  `What is the issue? * ` HTML standard select doesn't open up in Chrome mobile 53.
 -  `What is the expected behavior?` HTML standard select pops up as normal.

**CodePen** (or steps to reproduce the issue): *
  - `CodePen Demo which shows your issue:` https://codepen.io/NickDart/pen/VKyOQX
  - `Details:` The select does not open in Chrome mobile.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5 (and earlier)
 -  `Angular Material Version:` 1.1.0 (and earlier)

**Additional Information**:
 -  `Browser Type: * ` Chrome (mobile)
 -  `Browser Version: * ` 53
 -  `OS: * ` Android
 -  `Stack Traces:`

----
`Notes:` Hi, i have noticed that Angular Material, in some way, prevents the standard select from opening in Chrome mobile. 
This is not the case with Chrome desktop where the select when clicked works as normal.
This only happens when Angular Material is included (not only its dependecies).

**Comment by DevVersion** [comment]
I assume this relates to the gestures (See planned work #9362)

Can you confirm it works when doing the following the config phase?

```js
$mdGestureProvider.skipClickHijack();
```

**Comment by NickDart** [comment]
Yes, it works.

Here's the updated pen.
http://codepen.io/NickDart/pen/LRQLzX

Thanks for your help!

**Comment by kirtanshah** [comment]
I am facing the same issue and tried your answer. But I got injector error when i used **$mdGestureProvider**

my code:
 app.config(function ($stateProvider, $urlRouterProvider, $ionicConfigProvider, $mdGestureProvider) {
        $mdGestureProvider.skipClickHijack();

....... and so on

Please let me know the solution.

**Comment by Splaktar** [comment]
@kirtanshah Your example seems to match the example mentioned [here](https://github.com/angular/material/issues/1406#issuecomment-308439643). I made a [CodePen](https://codepen.io/Splaktar/pen/QaZqpQ) example as well. It sounds like you are running into a local configuration issue.
