### ISSUE TITLE
Theme changing not happening

### ISSUE THREAD

**Issue by Trixter313** [angular/material#9776]
**Actual Behavior**:
-  When using .setDefaultTheme() it isn't changing theme.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`http://codepen.io/anon/pen/QKQdjy
-  `Details:`

**Angular Versions**: *
-  `Angular Version:`1.5.7
-  `Angular Material Version:`1.1.1

**Additional Information**:
-  `Browser Type:`Chrome
-  `Browser Version:`55.0.2881.5
-  `OS:*`Windows 10
-  `Stack Traces:`

I've tried to recreate the basics of what I'm attempting onto a codepen.

**Comment by EladBezalel** [comment]
@Trixter313 i'm sorry but i don't think you're using angular and angular-material properly..

If i understood your intentions - changing the default theme during runtime is not possible, however you can use `md-theme` directive, i suggest you read about it over [here](http://localhost:8080/Theming/04_multiple_themes)
