### ISSUE TITLE
Md-tabs label length causes sibling tab labels to disappear in md-dialog

### ISSUE THREAD

**Issue by hyrumwhite** [angular/material#9779]
**Actual Behavior**:
-  `What is the issue? *`
  If a tab label is too long the tab label beside it will disappear, and only reappear on page resize.
  Inspecting the elements shows the hidden tab label is below the long tab.
-  `What is the expected behavior?`
  Tab labels should always show.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  http://codepen.io/hyrumwhite/pen/ALVgoQ
-  `Details:`
  The demo has removed the third tab in the tab dialog, changed the first tab label to "Bulk Actions", and the second label to "Confirm".

On launching the dialog with the "Tab Dialog" button the first time, the second tab may show. All subsequent launches hide the second tab.

In my project, the second tab never shows in these conditions.

The second tab will be visible after the page is resized

Changing these tabs to "One" and "Two" causes them both to be visible, which is why I believe it's an issue related to length.

My current hack to get around this is just to add a third empty tab.

**Angular Versions**: *
-  `Angular Version:`1.5.8
-  `Angular Material Version:`1.1.1

**Additional Information**:
-  `Browser Type: *`Chrome
-  `Browser Version: *`53.0.2785.143
-  `OS: *`Linux Mint
-  `Stack Traces:` No error in log

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by peio72** [comment]
+1

**Comment by mjbradford89** [comment]
+1

**Comment by clshortfuse** [comment]
Fixed in #9451
