### ISSUE TITLE
md-secondary css issue inside md-list

### ISSUE THREAD

**Issue by ksgupta** [angular/material#9783]
**Actual Behavior**:
 -  `What is the issue? *`

angular-material.css line: 2724
md-list-item .md-secondary-container,
  md-list-item .md-secondary, md-list-item .md-list-item-inner .md-secondary-container,
  md-list-item .md-list-item-inner .md-secondary {
    position: absolute;
    top: 50%;
    right: 16px;
    margin: 0 0 0 16px;
    -webkit-transform: translate3d(0, -50%, 0);
            transform: translate3d(0, -50%, 0); 
}
 -  `What is the expected behavior?`

The position should be relative. On the demo site too, the rendered position is coming as relative. With absolute positioning, it overlaps all the buttons given as md-secondary class within the line item

**Angular Versions**: *
 -  `Angular Version:`"^1.4.0",
 -  `Angular Material Version:` "^1.0.9",

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 53.0
 -  `OS: *` Mac 
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd
![screen shot 2016-10-08 at 03 05 06](https://cloud.githubusercontent.com/assets/6197427/19212659/c465692e-8d0a-11e6-9d7f-2abe07389959.png)
).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
We've made a lot of changes to the list component and it is planned to restructure a few things #8482.

In `v1.1.0-rc2` we've made the secondary items static (See https://github.com/angular/material/commit/9bb78e06).
