### ISSUE TITLE
Last few days official site now opening

### ISSUE THREAD

**Issue by manojkumar6** [angular/material#9788]
Last few days _https://material.angularjs.org/_ site not opening. please update the site

**Comment by crisbeto** [comment]
It's been working fine for me. Do you get some kind of error?

**Comment by manojkumar6** [comment]
angularjs.org is working, but _https://material.angularjs.org/_  is not working, the error is given below
--------------------------------
This site can’t be reached

material.angularjs.org took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics

**Comment by crisbeto** [comment]
It responds pretty quickly for me. There's probably something wrong with your network.
