### ISSUE TITLE
select: md-on-close doesn't work like ng-change

### ISSUE THREAD

**Issue by jaspersorrio** [angular/material#9789]
**Actual Behavior**:
-  `What is the issue? *`
  md-on-close event is not evoked everytime.
-  `What is the expected behavior?`
  expected it to work like ng-change.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
  http://codepen.io/anon/pen/vXREVX
-  `Details:`
  Follow steps in codepen.

**Angular Versions**: *
-  `Angular Version:`
  1.5.5
-  `Angular Material Version:`
  1.1.0

**Additional Information**:
-  `Browser Type: *`
  Chrome
-  `Browser Version: *`
-  `OS: *`
-  `Stack Traces:`

**Comment by Splaktar** [comment]
I don't see a problem with following the steps in the CodePen. The `md-on-close` is not supposed to be triggered if the options panel never opens.

If this is still a problem, please provide more of a description of the reproduction steps and the expected result.
