### ISSUE TITLE
Missing ripple on buttons when chromes scrollbar is active

### ISSUE THREAD

**Issue by stmpr** [angular/material#9792]
**Actual Behavior**:
-  `What is the issue? *`Missing ripple on buttons when the browser scrollbar is active
-  `What is the expected behavior?` To show the ripple when clicked, even if there is a scrollbar

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
-  `Details:` The ripple on buttons are missing when the scrollbar of google chrome is active, when I hide the scrollbar (overflow hidden on the body) the ripples are back.    I tried it also in firefox, but its only a chrome issue

**Angular Versions**: *
-  `Angular Version:` 1.5.5
-  `Angular Material Version:` 1.1.0

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 53.0.2785.143
-  `OS: *` macOS Sierra 10.12
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by stmpr** [comment]
Demo of whats going on: http://cl.ly/hkIZ

**Comment by Splaktar** [comment]
I tested this on https://material.angularjs.org/latest/demo/button and https://material.angularjs.org/1.1.0/demo/button with Chrome `Version 71.0.3578.98 (Official Build) (64-bit)` on macOS Mojave. The ripples worked with both versions with or without a vertical scrollbar being displayed.

If you are still seeing this, please provide a CodePen demo that reproduces the issue.
