### ISSUE TITLE
setting a default layout="column" makes the flex boxes contained inside it behave strangely

### ISSUE THREAD

**Issue by 1mike12** [angular/material#9796]
**Actual Behavior**:
 -  `What is the issue? *`

My understanding is that we can set a raw `layout="column"` as a default, and add extra `layout-<breakpoint>="row"` , which are supposed to override the defaults, for instance when we leave small viewports. (pattern1)

What's happening is that if I include the `layout="column"` the flex boxes don't behave correctly. They grow and fill 100% of the available space, even if I set `flex="nogrow"`

### pattern 1 doesn't work
```html
<div layout="column" layout-gt-xs="row" style="height:200px;" layout-wrap>
      
      <div flex="nogrow" flex-sm="50" flex-gt-sm="25" class="c1"> Content1 </div>
      <div flex="nogrow" flex-sm="50" flex-gt-sm="25" class="c2"> Content2 </div>
  </div>
```

### pattern 2 gets the desired behavior 
```html
 <div layout-gt-xs="row" style="height:200px;" layout-wrap>
      
      <div  flex-sm="50" flex-gt-sm="25" class="c1"> Content1 </div>
      <div  flex-sm="50" flex-gt-sm="25" class="c2"> Content2 </div>
  </div>
```
 -  `What is the expected behavior?` 

for the behavior to be like when layout="column" is ommited

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
[Demo](https://codepen.io/1mike12/pen/dpmkrZ).
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
1.4.8
 -  `Angular Material Version:`
1.0.0
**Additional Information**:
 -  `Browser Type: *`
chrome
 -  `Browser Version: *`
Version 53.0.2785.116 m (64-bit)
 -  `OS: *`
windows 10
 -  `Stack Traces:`

----

Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ThomasBurleson** [comment]
The Layout API v1.x has known issues with layout="column". Please see [Layout TroubleShooting](https://material.angularjs.org/latest/layout/tips). This will not be fixed with ngM1.
