### ISSUE TITLE
select(multiple): width should not be more then select box

### ISSUE THREAD

**Issue by nil4you** [angular/material#9797]
**Actual Behavior**:
-  `md select multiple width is more then select box`
-  `select dropdown width should not be more then select box width`

**Comment by Splaktar** [comment]
In our docs, I can see a number of examples where the options dropdown width is wider than the trigger element. However, I can't find any guidance in https://material.io/archive/guidelines/components/menus.html to indicate that this is an issue. I actually found a number of examples there in the spec that show this same behavior.
