### ISSUE TITLE
mdAutocomplete autoscrolls input out of viewport 

### ISSUE THREAD

**Issue by klabelle33** [angular/material#9810]
**Actual Behavior**:
 -  `What is the issue? *` On mobile sites where the autocomplete  is some distance down the page, if you scroll down, then start entering text in the input, the page autofocuses some distance down the page such that the input you are typing in is no longer visible. 
 -  `What is the expected behavior?` The autocomplete remains visible.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [Demo](https://bl.ocks.org/klabelle33/raw/83fe0c781ae1a3a9c3f5d9c2eaa3fa98/) and [source](https://gist.github.com/klabelle33/83fe0c781ae1a3a9c3f5d9c2eaa3fa98)
 -  `Details:` 

![2016-10-10](https://cloud.githubusercontent.com/assets/22752819/19251941/f45e9d06-8f0f-11e6-8f0b-a51278b3c92f.gif)

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 53.0.2785.109
 -  `OS: *` iOS 10.0.2
 -  `Stack Traces:`

Also happens on Safari (same OS)

**Comment by klabelle33** [comment]
I think this is due to the `disableScrollAround` call, which sets the body of the document to fixed position and assigns a top negative top position to the body. My workaround for this is to negate it with a `position: initial !important; top: initial !important` css rule on the body. 

Incidentally, this also causes any other fixed position elements on the page to behave unexpectedly (moving out of the viewport, for example)

**Comment by DevVersion** [comment]
Yeah, correct. I figured out the same while trying with Browserstack.

**Comment by DevVersion** [comment]
Just checked this out with `master` and it seems to work as expected. See #9458

**Comment by rajathms** [comment]
@klabelle33 @DevVersion issue is back again with the latest version of the angular material. The issue is only with safari browser (mobile only).
Angular Version: 1.5.8
Angular Material Version: 1.1.9

**Comment by Splaktar** [comment]
@rajathms can you please open a new issue with a CodePen reproduction or point out an example in the docs where this happens? Please reference this issue.
