### ISSUE TITLE
whiteframe: inner mdContent's scrollbar is mispositioned on Retina screens in Chrome

### ISSUE THREAD

**Issue by sanderaido** [angular/material#9811]
Found this very weird edge-case bug:

**Actual Behavior**:
-  `What is the issue? *` mdContent's scrollbar is positioned incorrectly on Retina screens in Chrome when outer div has mdWhiteframe. Scrollbar is offset based on the whiteframe value - more shadow -> more offset. This only happens with the auto-hidden scrollbar that OSX has, if you set to be always visible, everything is correct.
-  `What is the expected behavior?`Should be positioned right.

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/EgEAwj
-  `Details:` Only happens on Chrome and Mac Retina screens. I have an external monitor, if I view this there, everything is correct, viewing on Macbook's own Retina screen is misplacing the auto-hiding scrollbar. Here are screenshots of the produced error:

# Incorrect placement on Retina screen
<img width="427" alt="Incorrect placement" src="https://cloud.githubusercontent.com/assets/9868517/19264119/24ad4956-8fa8-11e6-8843-d7d1f9dd31da.png">

# Correct placement on other screens:
<img width="427" alt="Correct placement" src="https://cloud.githubusercontent.com/assets/9868517/19264161/5080e6be-8fa8-11e6-8bd6-bf3bdb8a8b54.png">

# Correct placement with always visible scrollbar
<img width="418" alt="screen shot 2016-10-11 at 11 23 28" src="https://cloud.githubusercontent.com/assets/9868517/19264184/678df446-8fa8-11e6-8c05-c6b1722330ba.png">

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type: *` Chrome
-  `Browser Version: *` 53.0.2785.143 (64-bit)
-  `OS: *` OS X El Capitan and OS X Sierra (tested)
-  `Stack Traces:`

**Comment by Splaktar** [comment]
Tested with Chrome 80 on macOS Catalina (`10.15.4 (19E287)`) and I can't reproduce this issue anymore. This may have been a webkit or Chrome bug.
