### ISSUE TITLE
Confusing Flex Documentation

### ISSUE THREAD

**Issue by TimBo93** [angular/material#9816]
In my opinion the 33% in the example is confusing, because it implies, that any integer value is legal.
https://material.angularjs.org/latest/layout/children
but 33% are a strict exception.

A reference to 
https://material.angularjs.org/latest/layout/introduction
could be practicable for newcomer who are not familiar with flex.

**Comment by ThomasBurleson** [comment]
@TimBo93 - I lack clarity regarding your recommendation. Where should this reference be placed ?

> The Layout API v1.x indeed has limitations to fixed integer values (0, 5, 10, 15, ... 100) + (33, 66); where 33 == 1/3 and 66 == 2/3. Due to the implementation of the v1.x architecture those limitations will not change. Angular Layouts v2 will be released in the near future with significant performance improvements, 0Kb CSS footprint, and no limitations on directive values.

**Comment by TimBo93** [comment]
@ThomasBurleson thank you for your response.

 Maybe at the same place as

> Currently, the flex directive value is restricted to multiples of five, 33 or 66

but with a warning icon /!\ or something similar which highlights this important fact.

Where can i get more informations about "Angular Layout v2"? Will it be available for Angular 1.x? Are there some breaking changes?

**Comment by Splaktar** [comment]
- You can find more about [@angular/flex-layout here](https://github.com/angular/flex-layout).
- It does not support AngularJS.
- There are breaking changes when migrating from AngularJS Material to Angular Material and Angular Flex Layout.

Currently in the linked example page there is clear wording about which values are allowed.
