### ISSUE TITLE
Feature Request: md-tabs needs to expose nextPage() and previousPage()

### ISSUE THREAD

**Issue by nicooga** [angular/material#9823]
## Actual Behavior
I'm using `md-tabs` for a form that has sections. Some of the tabs are disabled dinamically. I was using `md-selected-index` to power some extra 'next' and 'prev' buttons. With the introduction of the dinamically disabled tabs it doesn't work anymore and implementing next and prev buttons becomes a non-trivial task.

By looking at the source I think this could be easly implemented using `getNearestSafeIndex`.

https://github.com/angular/material/blob/72d068593b7f353d32f8308870d2b0d1c7c759c9/src/components/tabs/js/tabsController.js#L542-L553

## Expected behaviour
Example implementation:

~~~html
<md-tabs expose-controller-on='tabCtrl'>
  <md-tab label="A"/>
  <md-tab label="B" disabled='true'/>
  <md-tab label="C"/>
</md-tabs>

<md-button ng-click='tabCtrl.nextTab()'>Next</md-button>
<md-button ng-click='tabCtrl.previousTab()'>Prev</md-button>
~~~

Is this a feature you would merge?

**Comment by ThomasBurleson** [comment]
This is not a feature we want to implement/publish.
Instead use the `md-selected` attribute which provides 2-way databinding to/from the Tabs.

API - https://material.angularjs.org/latest/api/directive/mdTabs

See the [Dynamic Tabs](https://material.angularjs.org/latest/demo/tabs) demo which binds to `md-selected="selectedIndex"` and the JS which shows how to watch variable change if needed.

**Comment by nicooga** [comment]
I know how `md-selected` works. What I'm pointing here is
that `md-selected` is not a reliable option when you have disabled tabs. If
you have N tabs and they are disabled in a random pattern, setting the
`selectedIndex` to the next non-disabled tab gets really tricky and takes
some good number of lines of code to solve.

This complexity can get ridden with the implementation of "next" and "prev".
