### ISSUE TITLE
Input field overlaps with label in chrome(Windows)

### ISSUE THREAD

**Issue by mahesh-ziffi** [angular/material#9834]
Getting this issue for all inputs in chrome browser of windows. Not Getting why this is happening.
![whatsapp image 2016-10-14 at 2 09 02 pm](https://cloud.githubusercontent.com/assets/13447433/19381205/3b695afa-9218-11e6-8fa2-ce804fc0b116.jpeg)

**Comment by Reddemonfox** [comment]
could you share the section of this html code

**Comment by mahesh-ziffi** [comment]
<div layout-xs="column" layout-sm="column" layout-gt-sm="row" class="info-inputs">
              <md-input-container class="md-block default-font-input" flex-xs="100" flex-sm="45" flex-gt-sm="45">
                <label>E-MAIL ID</label>
                <input type="email" ng-model="addEditData.email" ng-disabled="{{addEditData.action == 'edit'}}">
              </md-input-container>
              <div flex-xs="0" flex-sm="10" flex-gt-sm="10"></div>
              <md-input-container class="md-block default-font-input" flex-xs="100" flex-sm="45" flex-gt-sm="45">
                <label>PREFERRED STYLIST</label>
                <md-select ng-model="addEditData.favourite_stylists" multiple aria-label="favouriteStylist">
                  <md-option ng-value="stylist.stylist_id" ng-repeat="stylist in salonStylists">{{ stylist.name}}</md-option>
                </md-select>
              </md-input-container>
            </div>

**Comment by ThomasBurleson** [comment]
Truthfully, attempting to fix "unknown" problems without details and reproducible examples is impossible.
