### ISSUE TITLE
Circular Progress (md-progress-circular) won't update diameter correctly

### ISSUE THREAD

**Issue by needo2** [angular/material#9841]
**Actual Behavior**:
 -  `What is the issue? *` Even though stroke width and layout dimensions change correctly, path's "d" attribute won't update on diameter change and circular progress will look incorrectly until the value is updated
 -  `What is the expected behavior?` path's "d" attribute should adapt to new diameter

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`http://codepen.io/anon/pen/KgxWAr
 -  `Details:` Upper slider changes the diameter and bottom slider changes the value but diameter doesn't update until value is changed

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chromium (nw.js)
 -  `Browser Version: *` 53.0.2785.143
 -  `OS: *` Windows 10 x64
 -  `Stack Traces:` uh

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
Hmm weird, we have a watch for the diameter, I'll check why it's not updating.
