### ISSUE TITLE
Font Size Select 

### ISSUE THREAD

**Issue by eassa** [angular/material#9843]
i dont know exactly where to put this , but i want something like fontSizeSelect in google docs : 
![image](https://cloud.githubusercontent.com/assets/14801394/19428034/44929990-9450-11e6-8e94-f9bd1a951d85.png)
where you can select from options and write it as well . do you have any solution or improvement coming soon ?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
