### ISSUE TITLE
Problems with position of autocompletes md-virtual-repeat-container

### ISSUE THREAD

**Issue by Painyjames** [angular/material#9844]
Hi,

I'm having some issues with the autocomplete component hints list position.

![problem with autocomplete](https://cloud.githubusercontent.com/assets/1241373/19431350/0776330a-9450-11e6-9a7b-cf84903b67fa.gif)

As you can see, on the image the first autocomplete is alright, but the second autocomplete is misplaced. Looking on the render md-virtual-repeat-container, the position is calculated incorrectly.

Couldn't see any previous issue referring to this problem, has anyone else experienced this and more important, is this a real issue or just me using the autocomplete input incorrectly?

**Comment by DevVersion** [comment]
Can you please provide a demo for this? I was not able to reproduce this in a codepen.

**Comment by Painyjames** [comment]
Turns out we were having overflow: auto on the body element which was causing the error.
With that removed, the problem is gone.
