### ISSUE TITLE
'this.$mdUtil' is undefined within MdChipsCtrl and throws error when used with autocomplete

### ISSUE THREAD

**Issue by ScottCollard** [angular/material#9845]
Angular Version: 1.5.8
Angular Material Version: 1.1.1

![screen shot 2016-10-17 at 11 02 34 am](https://cloud.githubusercontent.com/assets/210413/19445281/3ef0583e-9459-11e6-81e4-25ff274f82eb.png)

In the Contact Chips demo: 'this.$mdUtil' is undefined within MdChipsCtrl and throws error when using autocomplete within chips (i.e. contact chips) the following error is thrown when attempting to delete a chip.

![image](https://cloud.githubusercontent.com/assets/5748221/19442039/eaeb5cf0-9455-11e6-8588-9cdf6db33295.png)

'this.$mdUtil' is undefined in the code below as it does not exist on the MdChipsCtrl object

![image](https://cloud.githubusercontent.com/assets/5748221/19442002/c896d800-9455-11e6-86f5-2516ab11268c.png)

'$mdUtil' is passed into the constructor but not saved as as member of MdChipsCtrl.

![image](https://cloud.githubusercontent.com/assets/5748221/19441904/696b3600-9455-11e6-8408-19619216867a.png)

**Comment by ThomasBurleson** [comment]
@ScottCollard  - Please provide a CodePen.

**Comment by ScottCollard** [comment]
Fails in the demo provided in https://material.angularjs.org
http://codepen.io/anon/pen/BLOrgW

**Comment by ThomasBurleson** [comment]
This has been fixed in HEAD:  https://material.angularjs.org/HEAD/demo/chips
