### ISSUE TITLE
md-contact-chips - model as array deep-levels objects

### ISSUE THREAD

**Issue by Axel186** [angular/material#9852]
In `md-contact-chips` we got attribute "ng-model => A model to bind the list of items to".
Good, we have model's object like this:

```js
this.contacts = [
    {
        properties: {
            name: "test",
            email: "test@gmail.com",
            image: "http://...jpeg"
        }
    },
    {
        properties: {
            name: "test2",
            email: "test2@gmail.com",
            image: "http://...jpeg"
        }
    }
]
```

Then I wanted to use this HTML:
```html
<md-contact-chips ng-model="ctrl.contacts" md-contacts="ctrl.querySearch($query)" md-contact-name="properties.name" md-contact-image="properties.image" md-contact-email="properties.email" placeholder="To">
</md-contact-chips>
```

And I expected to get model's data on the page by getting value of: `item.properties.name`. I gave a path of the attribute to the item, but here we got issues.. As I understand from the source code of  `md-contact-chips`, we can pass only 1 level objects...

Take a look at the example please:
http://codepen.io/anon/pen/bwmrjJ?editors=1010

Anyone have idea how we can work with this?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
