### ISSUE TITLE
windows safari

### ISSUE THREAD

**Issue by paghdalyogesh** [angular/material#9857]
**Actual Behavior**:
 -  `What is the issue? *`
   Window safari browser doesn't support on max-width proprerty 

![safari](https://cloud.githubusercontent.com/assets/3389479/19515916/236b8bf0-9617-11e6-9533-1dbff7ce4f73.png)

 

**Angular Versions**: *
 -  `Angular Version:` 1.1.1
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` safari ( window system)
 -  `Browser Version: *` 5.1.7.
 -  `OS: *` window 10

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
Safari 5 isn't supported by Material. [You can read more about the browser support in the readme.](https://github.com/angular/material/blob/master/README.md)
