### ISSUE TITLE
Grunt concatenation and angular-material dependencies issue

### ISSUE THREAD

**Issue by sashberd** [angular/material#9858]
I`m trying to create one JS file with Grunt from angular-material and it dependencies.
My grunt is :

    concat: {
                options: {
                    // define a string to put between each file in the concatenated output
                    separator: ''
                },           
                remote:{
                  src:[ 'remote/angular-aria.js','remote/angular-animate.js','remote/angular-messages.js','remote/angular-material.js']  ,
                  dest:'../js/build/remote_build.js'
                }
            }
    }

However, after I put reference of concertinaed file in application, I got next angular error:

> Uncaught Error: [$injector:unpr] Unknown provider:
> $$isDocumentHiddenProvider <- $$isDocumentHidden <- $$animateQueue <-
> $animate <- $compile <- FileItem <- FileUploader <- $$animateQueue

I`d tried to put angular-animate as stand alone and it is worked, no error was thrown.
I spent  a lot of time to figure out what can be a problem with put angular material files and dependencies together but no result
Is anybody met such strange behavior?
Stackoverflow: [http://stackoverflow.com/q/40129991/556526](http://stackoverflow.com/q/40129991/556526)

**Comment by ThomasBurleson** [comment]
See [Material-Tools](https://github.com/angular/material-tools).

**Comment by jonathanwiesel** [comment]
You can use [grunt-bower-concat](https://github.com/sapegin/grunt-bower-concat) instead.
