### ISSUE TITLE
$mdUtil.disableScrollAround breaks the page when body has overflow-x:hidden. 

### ISSUE THREAD

**Issue by sebakerckhof** [angular/material#9860]
**Actual Behavior**:
 -  `What is the issue? *`
If a material component with `disableParentScroll` set to true (like `mdDialog`, `mdSelect`, ...) is opened, it calls `$mdUtil.disableScrollAround`. If the body has `overflow-x:hidden;` in its computed style, then `$mdUtil.disableScrollAround` will add `overflow: hidden` to the body (here: https://github.com/angular/material/blob/master/src/core/util/util.js#L298-L300). This breaks the page.

 -  `What is the expected behavior?`
Same as without `overflow-x: hidden` 

**CodePen** (or steps to reproduce the issue): 
http://codepen.io/sebakerckhof/pen/bwQdaV
Scroll down & either open the dialog by clicking the button, or open the select element.

**Angular Versions**: 
 -  Angular version: `1.5.9` 
 -  Angular Material Version: `1.1.1`

**Additional Information**:
 -  `Browser Type: Chrome, Firefox`

Somehow adding `position:fixed; width:100%; top: -Xpx` makes the `body.clientWidth` smaller when the body has `overflow-x:hidden;` so that https://github.com/angular/material/blob/master/src/core/util/util.js#L298-L300 evaluates to true.
No idea why that is though.

**Comment by crisbeto** [comment]
Dialog and select don't use mdPanel yet. This is probably an issue with the `$mdUtil.disableScrollAround` method.

**Comment by sebakerckhof** [comment]
Ow, you're right.

**Comment by crisbeto** [comment]
Seems like this one's causing the issues: `documentElement.style.overflowY = 'scroll';`. If we move it a bit down, it works.

**Comment by sebakerckhof** [comment]
Seems to make sense. It probably adds a scrollbar, making the body smaller?

I could make a PR if that's encouraged. But do you know the rationale behind:
https://github.com/angular/material/blob/master/src/core/util/util.js#L298-L300
and:
https://github.com/angular/material/blob/master/src/core/util/util.js#L295
? 

Just want to make sure swapping these doesn't brake anything else.

**Comment by crisbeto** [comment]
I think the rationale is that it adds an extra scrollbar to prevent the content from jumping when the body becomes non-scrollable. I'll check it up later since I ended up breaking stuff the last time I messed around with that function.

**Comment by crisbeto** [comment]
Alright, it doesn't seem like it's breaking anything. I can do the PR since I want to try and get a unit test for this as well.

**Comment by sebakerckhof** [comment]
Ok. Thanks
