### ISSUE TITLE
md datepicker scroll behaviour

### ISSUE THREAD

**Issue by MigFerreira** [angular/material#9863]
**Actual Behavior**:
 -  `What is the issue? * Scrolling dates with limits does not have correct behaviour`
 -  `What is the expected behavior? When scrolling up should go to previous month and not next.`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`[CodePen Demo](http://codepen.io/MigFerreira/pen/kkQgBp)
 -  `Details: Select the from date and scroll slowly up, it will be visible it goes to the next month instead                 of previous`

**Angular Versions**: *
 -  `Angular Version: 1.5.8`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: Desktop Chrome`
 -  `Browser Version: 54`
 -  `OS: Windows 7`
 -  `Stack Traces:`

**Comment by crisbeto** [comment]
Weird. It seems like the `maxDate` is tripping it over.
