### ISSUE TITLE
chips:  ng-if not working

### ISSUE THREAD

**Issue by IMM0rtalis** [angular/material#9868]
Heyho @ all

When i use

``` html
<md-chips>
<md-chip ng-if="model">SomeText</md-chip>
</md-chips>
```

the chip is not shown. Does not matter what the model has for a value. With ng-show it's working fine.

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.1.0

Why is this not working? Is this a bug or is it made this way and i should not use ng-if?

Best,
Florian

**Comment by topherfangio** [comment]
Reproduction at http://codepen.io/topherfangio/pen/pEQXvw?editors=1011

Using `ng-if="true"` throws the following error in the console:

```
"TypeError: Cannot read property 'insertBefore' of null
```

**Comment by IMM0rtalis** [comment]
hmm... dont know why an angular update fixed it, but since Angular 1.5.10 and material 1.1.1 it seems to work. What is your opinion  on this? @topherfangio

**Comment by topherfangio** [comment]
@IMM0rtalis Indeed; not sure what changed, but it appears to be fixed. Thanks for the update!

**Comment by IMM0rtalis** [comment]
was i completely stupid or why did i say it works now? -> https://codepen.io/anon/pen/GERJKj?editors=1011     it throws no error-message anymore...  but the second chip is not visible^^
