### ISSUE TITLE
Docs: Update https://material.angularjs.org to pull from tag instead of master branch

### ISSUE THREAD

**Issue by marcysutton** [angular/material#988]
To minimize breakage of the docs site ahead of the version picker (https://github.com/angular/material/issues/918), the Angular Material core team discussed publishing code to https://material.angularjs.org from a tag rather than the `master` branch. That way, breaking code inadvertently pushed to master will not affect the docs site. Developers can continue to build the docs locally from any branch, tag, or commit–only the live docs site will be published from specific tag. 

Ideally, we would also run tests in our deployment process to ensure breaking code is not pushed to the live site.

**Comment by marcysutton** [comment]
@ajoslin @rschmukler let's keep talking about this one.

**Comment by ThomasBurleson** [comment]
This will not be needed when we publish the Documentation with a version picker and snapshots on a CDN each document build.
