### ISSUE TITLE
How to solve flex layout issues in chrome

### ISSUE THREAD

**Issue by Matheus-Ribeiro95** [angular/material#9880]
Layout system of angular is just broken in chrome and isnt working as it should.
Is there a workaround for every element or is better to use material design lite?
Thanks adv.

**Comment by ThomasBurleson** [comment]
Closing since this is an invalid issue: lacking in specific details and a CodePen demo.

**Comment by Matheus-Ribeiro95** [comment]
Lol, angular team could just fix this bug instead of saying that is lacking information.
Already said here:
https://github.com/angular/material/issues/6841

And isn't just with card.
Wanting to launch v2 when v1 isn't fully done, nice.
