### ISSUE TITLE
chips: are not aligned with updated Material Design specs

### ISSUE THREAD

**Issue by LeoLozes** [angular/material#9883]
It seems that the chips that are shown in the [demos](https://material.angularjs.org/1.1.0/demo/chips) are not following the [actual spec of Material Design](https://material.io/archive/guidelines/components/chips.html#chips-specs)

Angular Material:

![image](https://cloud.githubusercontent.com/assets/11133817/19597561/9c8dd25c-9795-11e6-8ed9-187aff080119.png)

![image](https://cloud.githubusercontent.com/assets/11133817/19597528/75a5deaa-9795-11e6-926e-ac4b4ccb3371.png)

Material Design Spec:

![image](https://cloud.githubusercontent.com/assets/11133817/19597586/bded245c-9795-11e6-97e5-c0f918fec10f.png)

**Comment by topherfangio** [comment]
Indeed; it looks like the spec changed since we launched the chips.

Talking to team now about how to prioritize and what milestone this should be in.

**Comment by Splaktar** [comment]
PR https://github.com/angular/material/pull/11989 addresses the spec updates other than the remove button isn't shown on mobile part. If that is of interest to anyone, please file a new enhancement request.
