### ISSUE TITLE
autocomplete: bindings are initialized with true when value is undefined

### ISSUE THREAD

**Issue by DevVersion** [angular/material#9890]
**Actual Behavior**:
 -  `What is the issue? *` The autocomplete sets attribute bindings to true when those are undefined.
 -  `What is the expected behavior?` The autocomplete should not set the bindings to true, when the interpolation has no value.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/DevVersion/pen/yakLwv?editors=1011

This is a small set of the attributes which are affected.
- `md-no-cache`
- `md-require-match`
- `md-select-on-match`
- `md-match-case-insensitive`

> Basically all attributes (with two-way-data binding enabled) are affected in the autocomplete (and also in the chips)

**Comment by crisbeto** [comment]
It seems weird that everything is set to `true` by default, although the `initOptionalProperties` allows for defaults to be passed in so it should be an easy fix without breaking current behaviour.

**Comment by DevVersion** [comment]
Agreed with that. This will require us to rework the util function, which is used by a lot of other components.
