### ISSUE TITLE
Problem: md-select with multiple attribute and multiple themes

### ISSUE THREAD

**Issue by renatovieira91** [angular/material#9894]
Hi. I'm using md-select with multiple attribute and my application must have multiple themes to be dynamically loaded. The point is that the checkbox within the md-select does not inherit selected theme style, it uses the colors of the default theme. The options text within the component are ok, just the checkbox background color is wrong.

Thanks!

**CodePen**
-  `http://codepen.io/anon/pen/BLrpJj`

**Angular Versions**: 
-  `Angular Version: 1.5.5`
-  `Angular Material Version: 1.1.1`

![a](https://cloud.githubusercontent.com/assets/3143699/19626699/f24e00fa-9915-11e6-8f5b-eaf6cd071bee.png)

**Comment by crisbeto** [comment]
This seems like it could be related to https://github.com/angular/material/issues/9592

**Comment by renatovieira91** [comment]
Yes, but in my case I'm use md-select with multiple attribute, and the problem is checkbox background color.

**Comment by clshortfuse** [comment]
The `mdOption` directive isn't calling `mdTheming`.
