### ISSUE TITLE
Layout wrong flex in Safari

### ISSUE THREAD

**Issue by EricBorland** [angular/material#9897]
**Actual Behavior**:
 -  `What is the issue? In Safari, the layout children are not properly positioned when using layout="row" and some flex like flex="25" (instead, for flex="33" is working as expected)`
 -  `What is the expected behavior? The expected behaviour is that when using layout="row" and 4 children have flex="25" they should all be in the same row instead of being shown in columns`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue: If you look at the documentation in master branch from safari, you'll see the issue right away. https://material.angularjs.org/HEAD/layout/children`
 -  `Details: Many row layout are shown as column`

**Angular Versions**: *
 -  `Angular Version: *`
 -  `Angular Material Version: master`

**Additional Information**:
 -  `Browser Type: Safari`
 -  `Browser Version: latest`
 -  `OS: Mac OS X`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by EricBorland** [comment]
I was debugging the code a bit and I believe the commit that introduced the issue was this https://github.com/angular/material/commit/c6fb5a5473806c158d6a8675d4948ba3f6b87740

And that's why only the flex multiples of 5 are the ones affected this that commit didn't change the flex-33 or flex-66 for row layouts

**Comment by ThomasBurleson** [comment]
This is a known Safari bug, here is a workaround - 
https://github.com/philipwalton/flexbugs#11-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items

> This will be fixed in Layouts v2.

**Comment by ThomasBurleson** [comment]
This issue is closed as it falls in the 'deprecated' category. We deprecate issues for one or more of the following reasons:

*  **Issue has a reasonable workaround for ngM1.1.x**
*  Issue doesn't have a demo or reproducible case available
*  Issue is real, but fixing it is risky for users who depend on existing behavior
*  Issue is real, but only affects a very small use case
*  Issue is real, but would require significant work to fix, and is less urgent than other needs.

> Pull Requests are welcomed to resolve this issue. But note that **not** all community PRs will be merged into master. Pull Requests with large changes or large scope impacts will probably be rejected [due to stability risks to existing users].

**Comment by luncht1me** [comment]
It's not that reasonable of a workaround..... Getting Material working in Safari is a pain in the ass manually setting flex-basis on a per-element basis. The % values simply don't work in Safari, a manually set px value is required to get anything to render properly. 

Material is wonderful, it's simply super annoying to try and get it cross-browser production ready though.
