### ISSUE TITLE
jQuery and jQuery-UI doesn't work inside md-tabs

### ISSUE THREAD

**Issue by jesusmariocalleja** [angular/material#9900]
I have a `<div class="draggable"></div>` inside an `<md-tab></md-tab>` and in my controller:
`$('.draggable').draggable();` and it doesn't work. I doesn't throw an error, but ignores the function. I changed the jQuery-UI function to a simple `$('.draggable').click(function(){alert('hey');});` and it doesn't work neither. If I put the div outside the md-tab, it works perfectly. Is there any way to make jquery work inside md-tabs??

Thanks!

**Comment by BRUNNEL6** [comment]
I think it is not angular materials fault. Maybe you're calling `$('.draggable').draggable();` when .draggable is no even created?

I suggest creating a directive, which binds the jQuery events (`.click() or .draggable()`) inside the link() function. [Have a look here](https://docs.angularjs.org/guide/directive#creating-a-directive-that-manipulates-the-dom)

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
