### ISSUE TITLE
autocomplete md-not-found has initially the wrong size

### ISSUE THREAD

**Issue by ngehlert** [angular/material#9901]
**Actual Behavior**:
 -  `What is the issue? *`

   md-not-found has initially the wrong size and shows a scrollbar 

 -  `What is the expected behavior?`

   having the correct size initially to prevent scrollbars

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
   http://codepen.io/anon/pen/rrPAWy
 -  `Details:`

Steps to reproduce:

1. Enter a text with no search results, e.g. 23,  in the field
2. not-found container is scrollable and has the wrong size
3. remove entries and enter valid text, e.g. Ang
4. remove valid text and enter text with no results again
5. not-found container has now the correct size and no scroll bar

**Angular Versions**: *
 -  `Angular Version:`  1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome / Firefox / Safari
 -  `Browser Version: *` 54.0.2840.59 (64-bit) / 49.0.2 / 10.0 (12602.1.50.0.10)
 -  `OS: *` macOS Sierra
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
This is not an issue with the autocomplete.

You are using the `md-menu-class` attribute with a className that's already used by our docs and now adds some extra padding to the top and bottom.

```html
<md-autocomplete md-menu-class="autocomplete-custom-template"></md-autocomplete>
```

See http://codepen.io/DevVersion/pen/mAvNqA?editors=1010

**Comment by ngehlert** [comment]
first of all i did not add any classes by myself. my example is taken straight from  the angular material documentation, and the bug is happening there as well.
to me it looks like the padding is initially not added to the md-not-found container, but once the item container is rendered correctly, the md-not-found has the correct size.

how can i use larger auto complete items and still resize the md-not-found properly?

**Comment by DevVersion** [comment]
Regardless of where this snippet comes from, the attribute which was "added" to the `md-autocomplete` directive matches a CSS selector which is provided in the stylesheet from our docs.

- Here are the lines: https://github.com/angular/material/blob/master/docs/app/css/style.css#L828-L845

This is not an issue inside of our documentation, because we don't show any `md-not-found` item.

> If we would have a `md-not-found` then it would need to have the same height as the normal items (this does not happen on your Codepen)

Also it is not possible to custom sizes for different list items right now, but we recently had a discussion about this (and we will continue exploring ideas.

Let me know if you any other questions :)
