### ISSUE TITLE
dialog: appears outside of the screen after iPad virtual keyboard opens

### ISSUE THREAD

**Issue by ydydxhg** [angular/material#9910]
**Actual Behavior**:
-  `What is the issue? *` md-dialog appears outside of the screen after mobile keyboard shows
-  `What is the expected behavior?` the md-dialog should appear in the center of the screen

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:`
-  `Details:`
  1. I click on any of the text boxes on the web page, which brings up the mobile keyboard, this is on IPad 9.3.2.
  2. after typing, I then either minimise the keyboard or leave it on
  3. and click a button which shows a md-dialog as modal.
  4. the modal shows up, which grays out and blocks the whole page. but the dialog box appears outside of the screen, i.e. you cant see it, you cant touch it, you cant close it.

**Angular Versions**: *
-  `Angular Version:` 1.4.8
-  `Angular Material Version:` 1.1.0 RC.5

**Additional Information**:
-  `Browser Type: *` ipad safari
-  `Browser Version: *` 
-  `OS: *` ios 9.3.2
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by bradsavon** [comment]
I had a similar issue and resolved it by wrapping it in a timeout:

`        
var confirm = $mdDialog.confirm()
			  .title('Test')
			  .content('This is test content')
			  .ariaLabel('Test')
			  .ok('Got it!')
			  .cancel('Cancel');

$timeout(
	$mdDialog.show(confirm).then(function () {

	})
, 0);
`

**Comment by Splaktar** [comment]
This didn't include a demo for reproduction so I created a [CodePen](https://codepen.io/Splaktar/pen/vvyYdj) based on the description. I wasn't able to reproduce this on an iPad with iOS 12.1.1 using the HEAD version of AngularJS Material (soon to be 1.1.11). It was likely fixed some time ago.
