### ISSUE TITLE
menu: Bounded offset and constant margins

### ISSUE THREAD

**Issue by derekrliang** [angular/material#9912]
Currently, md-menu has a constant bounding margin box of 8 px: https://github.com/angular/material/blob/master/src/components/menu/js/menuServiceProvider.js#L16

Using attribute `md-offset` with negative values does not work due to bounding clamping here: https://github.com/angular/material/blob/master/src/components/menu/js/menuServiceProvider.js#L494

Can we change it to either allow offset values outside of the bounds or allow the user to change the margins?

**Comment by chunnallu** [comment]
I meet the same problem ! Have you fix it ?

**Comment by razorch** [comment]
+1, i need to position menu exactly at x=0, y=0 but the minimum offset is 8px. please fix the issue

**Comment by Splaktar** [comment]
We could consider something like this, but we need some demos that reproduce the issue and some more use cases where this would be needed.

**Comment by Splaktar** [comment]
No demos provided.
