### ISSUE TITLE
function bound to ng-checked is running too many times.

### ISSUE THREAD

**Issue by vajahath** [angular/material#9913]
**Actual Behavior**:
 -  `What is the issue? *`
The function bound to ng-checked (md-checkbox) is running too many times.
```html
	<div ng-repeat="item in items">
		<md-checkbox ng-checked="exists(item, selected)" ng-click="toggle(item, selected)">
			{{ item }}
		</md-checkbox>
	</div>
```
```javascript
	$scope.items = [1];
	var i = 0;
	$scope.exists = function(item, list) {
		console.log("ran " + i++);
		return list.indexOf(item) > -1;
	};
```
output in console:
```
"ran 0"
"ran 1"
"ran 2"
"ran 3"
"ran 4"
"ran 5"
```

 -  `What is the expected behavior?`output in console:
```
"ran 0"
```
**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`pen : http://codepen.io/vajahath_ahmed/pen/WGmjrP?editors=1012

 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**: 
 -  `Browser Type: *` Chrome firefox
 -  `Browser Version: *`Version 54.0.2840.59 (64-bit)
 -  `OS: *` Ubuntu 16.04
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
This has come up before (see https://github.com/angular/material/issues/9040). It's because of `ngAria`.
