### ISSUE TITLE
It is possible to input '02/31/2016' (impossible) date

### ISSUE THREAD

**Issue by KarynaTaranova** [angular/material#9914]
**Actual Behavior**:
 -  `What is the issue? It is possible to input '02/31/2016' (impossible) date`
 -  `What is the expected behavior?`

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details: type '02/31/2016' into calendar input from keyboard or past from clipboard. See this date in input, and another date in calendar table`

**Angular Versions**: find on link https://material.angularjs.org/latest/demo/datepicker
 -  `Angular Version:`
 -  `Angular Material Version:`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 54.0`
 -  `OS: Mac`
 -  `Stack Traces:`

![screen shot 2016-10-25 at 2 13 43 pm](https://cloud.githubusercontent.com/assets/17509880/19683994/8a518aae-9abd-11e6-99d3-218f51c3197e.png)
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
This was discussed in https://github.com/angular/material/issues/9714#issuecomment-251497830, as well as why it hasn't been addressed in Material. You can check the comments on how to work around it, if it's an issue in your app.
