### ISSUE TITLE
Layout > Introduction with wrong text.

### ISSUE THREAD

**Issue by LucasArgate** [angular/material#9917]
Hello Guys, i dont now if it is important, but in AngularJS page, Layout > Introduction there is a error:

On section:
**API with Responsive Breakpoints:**

In table of values:
layout-gt-lg	flex-gt-lg	width >= 1920**/b>**px

there is /b> lost there. 
Link of page: [https://material.angularjs.org/latest/layout/introduction](https://material.angularjs.org/latest/layout/introduction)

👍

**Comment by crisbeto** [comment]
[This looks like it's fixed in master.](https://material.angularjs.org/HEAD/layout/introduction) Thank you for the report, though 👍
