### ISSUE TITLE
theme: how do I change the button foreground color?

### ISSUE THREAD

**Issue by scriptsure** [angular/material#9918]
pretty basic not sure if this is an issue or not.... all i want to do it set it to use a white foreground... here is the codepen:

http://codepen.io/scriptsure/pen/YGggWv?editors=1010

what is wrong here????

**Comment by scriptsure** [comment]
anyone have an idea on this????

**Comment by DevVersion** [comment]
Just looked at it. At first glance it looks like the `md-button` does not use the `foreground palette` for the font-color.

> See the source [here](https://github.com/angular/material/blob/master/src/components/button/button-theme.scss#L72)

I think we should be consistent with using the foreground-palette for fonts.

**Comment by scriptsure** [comment]
OK... I dont suppose you can set the text color in a another way in the theme???

**Comment by Splaktar** [comment]
This is done using `extendPalette` and `contrastLightColors` as demonstrated in this [CodePen](https://codepen.io/Splaktar/pen/pZJxOB?editors=1010).
```js
    var myGreenPalette = $mdThemingProvider.extendPalette("green", {
      // whether, by default, text (contrast) on this palette should be dark or light
      // This is the default for the green palette
      'contrastDefaultColor': 'dark',
      // hues which contrast should be 'light' by default
      'contrastLightColors': ['400']
    });
    $mdThemingProvider.definePalette('myGreenPalette', myGreenPalette);
    $mdThemingProvider.theme("actions").primaryPalette("myGreenPalette", {
      "default": "400",
      "hue-1": "400",
      "hue-2": "300",
      "hue-3": "100",
    });
```
