### ISSUE TITLE
md-autocomplete tabbing issue

### ISSUE THREAD

**Issue by shannonhochkins** [angular/material#9919]
**Actual Behavior**:
 -  `What is the issue? *` Tabbing does not work in the autocomplete menu.
 -  `What is the expected behavior?` - I would expect to be able to tab into the autocomplete items once typed in an option,

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/latest/demo/autocomplete
 -  `Details:` tab into field, type something and then hit tab again. 

**Angular Versions**: *
 -  `Angular Version:` 1.5.X
 -  `Angular Material Version:` 1.1.X

I know it's because it's using the virtual repeat direcitive to draw the options in the menu, however I would have assumed it would naturally dump the virtual repeat after the input element which would then fix the tabbing issue?

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
I think it's intentionally to not make the dropdown tab-able, because users are able to select the items with the arrow keys.
