### ISSUE TITLE
No accent colors defined in certain themes

### ISSUE THREAD

**Issue by borgdylan** [angular/material#992]
I have tried to use "md-accent" as a class on buttons while using the blue and indigo themes. This failed as no accent colors get defined in the theme css files.

**Comment by sclearion** [comment]
I had the same issue until I used the $mdThemingProvider like so:

$mdThemingProvider.theme('default').primaryColor('blue-grey').accentColor('amber');

**Comment by PaulMougel** [comment]
From what I understand of 47f0d09e9ebd87891703fa2b7e81355ce3952a86, themes declared from CSS files are no longer supported. You should use `$mdThemingProvider`, as explained in the commit message.

**Comment by ThomasBurleson** [comment]
@ajoslin  - documentation issue?

**Comment by ajoslin** [comment]
This is due to people including the CSS files. I'm deleting them from the bower repo now.
