### ISSUE TITLE
`item-metastat` css class missing in autocomplete demo

### ISSUE THREAD

**Issue by ranjan-ranjan** [angular/material#9920]
I am following https://material.angularjs.org/latest/demo/autocomplete for implementing autocomplete. I think `item-metastat` css class is missing. kindly confirm.
![1](https://cloud.githubusercontent.com/assets/16834561/19716725/ea7d00da-9b7a-11e6-9073-8be27e901cfc.png)

*Migrated from https://github.com/angular/angular.js/issues/15315

**Comment by DevVersion** [comment]
Thanks for the issue. This is actually a custom class we added **only** to our docs (for the demos)

I agree that this is confusing, because it is not available in the actual demo "source".

> I will take a look to make this CSS available in the actual demo source.

**Comment by ranjan-ranjan** [comment]
Also, angular-messages.js and angular-route.js is not needed.
