### ISSUE TITLE
Text area 'rows' attribute broken.

### ISSUE THREAD

**Issue by karthik-rp** [angular/material#9921]
**Actual Behavior**:
 -  `What is the issue? *` Rows attribute for textarea broken, Textarea height goes on increasing even when rows attribute is present.
 -  `What is the expected behavior?` Height in textarea limited and the content should be scroll able when rows attribute is present.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` [TextArea: CodePen](http://codepen.io/anon/pen/ALzLOa)
 -  `Details:` TextArea Biography in demo.

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 51.0.27
 -  `OS: *` Ubuntu
 -  `Stack Traces:` N/A
 - `Issue present in Versions`: 1.1.0-rc5 and above.

**Comment by crisbeto** [comment]
The `rows` attribute is the amount of _minimum_ rows for the textarea. If you want it to stop growing after a certain point, you can add the `max-rows` attribute.
