### ISSUE TITLE
input inside tab not allowing spaces

### ISSUE THREAD

**Issue by avilao** [angular/material#9922]
**Actual Behavior**:
I'm trying to have a tabs component where the tab names are editable.

I use an input inside the tab.

**CodePen** (or steps to reproduce the issue): *
http://codepen.io/team/AngularMaterial/pen/bEGJdd

**Angular Versions**: *
-  `Angular Version:` 1.5.8
-  `Angular Material Version:` 1.1.0-rc.5

**Additional Information**:
- IE, Chrome, Firefox

**Comment by Splaktar** [comment]
Closing as no valid demo was provided.
