### ISSUE TITLE
md-chips with md-autocomplete throws error when removing chip

### ISSUE THREAD

**Issue by craigsh** [angular/material#9928]
**Actual Behavior**:
 -  `What is the issue? *`

Removing a chip from an md-chips using md-autocomplete throws an exception:

console_runner-d0a557e….js:1 TypeError: Cannot read property 'nextTick' of undefined
    at MdChipsCtrl.removeChipAndFocusInput (angular-material.js:24883)
    at fn (eval at compile (angular.js:14432), <anonymous>:4:516)
    at expensiveCheckFn (angular.js:15485)
    at callback (angular.js:25018)
    at ChildScope.$eval (angular.js:17229)
    at ChildScope.$apply (angular.js:17329)
    at HTMLButtonElement.<anonymous> (angular.js:25023)
    at defaultHandlerWrapper (angular.js:3456)
    at HTMLButtonElement.eventHandler (angular.js:3444)

 -  `What is the expected behavior?`
That removing a chip not throw an error

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`

The CodePen demo for md-chips produces this behaviour, or here for a minimal demo: 

[CodePen](http://codepen.io/craigsh/pen/QKPJvZ)

 -  `Details:`
Add a chip then remove it. An error will be thrown.

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

This works fine on 1.1.0

**Comment by craigsh** [comment]
It appears that $mdUtils is being passed into the constructor but not being saved on this.

**Comment by DevVersion** [comment]
Thanks for the issue. We already solved this within master.

**Comment by hpawe01** [comment]
Hey @DevVersion,
thank you for fixing this issue. Do you know, when you release this? The last patch is already three months ago altough you planned to release a patch every week. Or can you link the commit that fixes this issue? Than I could temporary adopt the fix. Thanks in advance for any information.

Cheers,
Friedrich

**Comment by DevVersion** [comment]
Hey @hpawe01 - I don't have any information about the upcoming release.

The commit which fixes this issue is https://github.com/angular/material/commit/a3b3e7b037fb02acae5c1d979e8373d7e8c93dfd

**Comment by hpawe01** [comment]
For the sake of completeness: This is fixed with the release [1.1.2 (2017-01-05)](https://github.com/angular/material/blob/master/CHANGELOG.md#112-2017-01-05).
