### ISSUE TITLE
autocomplete doesn't update list with md-min-length="0"

### ISSUE THREAD

**Issue by uriva** [angular/material#9929]
**Actual Behavior**:
 -  `What is the issue? *`

Autocomplete with md-min-length does not update when changing suggestion list. Instead it shows the old options.

**CodePen** (or steps to reproduce the issue): *
http://codepen.io/anon/pen/JRqPqK?editors=101

Focus the input, see countries. Click on the button. Focus the input, still see countries despite model is fruits

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *` 54
 -  `OS: *` linux

**Comment by DevVersion** [comment]
The autocomplete by default caches all results, so be sure to use the `md-no-cache` attribute, if you want to update the results at runtime.
- http://codepen.io/DevVersion/pen/dpEyBq?editors=1011
