### ISSUE TITLE
md-text-float type="number", bug on entering string data. 

### ISSUE THREAD

**Issue by SanjayAlanoly** [angular/material#993]
The text field md-text-float when set to type="number" renders wrongly when string data is entered and the focus changes as shown below :

![image](https://cloud.githubusercontent.com/assets/1556040/5503521/e75f49c8-879d-11e4-9cb4-1640c5cd2ba1.png)

![image](https://cloud.githubusercontent.com/assets/1556040/5503530/ff2a152e-879d-11e4-9475-a1f461fc8604.png)

However it works correctly when number data is entered.

![image](https://cloud.githubusercontent.com/assets/1556040/5503536/1519f8a4-879e-11e4-8244-1c89d6ff088b.png)

**Comment by MJDSys** [comment]
I don't think this issue can be closed, as I still experience this issue while using the new md-input-container.  See here: http://jsfiddle.net/L4eto7up/ .  I tried both on Chrome 39 and Firefox 34.0.5.

**Comment by ajoslin** [comment]
Need to make it '!element.val().length && !ngModel.$isEmpty()'
