### ISSUE TITLE
Input alignment changes within a form

### ISSUE THREAD

**Issue by LeoLozes** [angular/material#9932]
**Actual Behavior**:
-  `What is the issue?` 
  The alignment of inputs changes depending on the location of the form (inside or outside md-content)
-  `What is the expected behavior?`
  I think the form shouldn't change a thing about the input alignment. 

**CodePen** (or steps to reproduce the issue): 
-  `CodePen Demo which shows your issue:` http://codepen.io/anon/pen/KgLdjz

**Angular Versions**: *
-  `Angular Version:` 1.5
-  `Angular Material Version:` 1.1.1

**Additional Information**:
-  `Browser Type:` Chrome
-  `Browser Version:` 54
-  `OS:`Windows 10
-  `Stack Traces:` None needed
---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by clshortfuse** [comment]
Your usage of `layout-padding` isn't matched, which is causing the alignment to change. This isn't an issue in the framework:

```
CONTENT - FORM - TEXTAREA
<md-content flex layout-padding>
    <form>
```
```
FORM - CONTENT - TEXTAREA
  <form>
    <md-content flex layout-padding> 
```

In FORM - CONTENT - TEXTAREA, place the layout-padding to the form element instead and it should match.
