### ISSUE TITLE
MdPanelPosition center() is broken

### ISSUE THREAD

**Issue by craigsh** [angular/material#9935]
**Actual Behavior**:
-  `What is the issue? *` Using MdPanelPosition.center() now positions the top/left corner of a panel in the center of the screen.
-  `What is the expected behavior?` center() should use the panel width and height so that the whole panel is centered on the screen (as it did in 1.1.1).

**CodePen** (or steps to reproduce the issue): *
-  `CodePen Demo which shows your issue:` [CodePen](http://codepen.io/craigsh/pen/yaWorr)
-  `Details:` Click the Dialog button to see that the panel is incorrectly positioned.

**Angular Versions**: *
-  `Angular Version:`1.5.5
-  `Angular Material Version:`master

**Additional Information**:
-  `Browser Type: *`
-  `Browser Version: *`
-  `OS: *`
-  `Stack Traces:`

---

Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
>   Add more lines if needed.

**Comment by craigsh** [comment]
Seems that for some reason the translate transform isn't being applied.

**Comment by crisbeto** [comment]
AFAIK centering only works on an absolute position. If you change the position to this, it should work:

```js
var position = this._mdPanel.newPanelPosition().absolute().center();
```

**Comment by craigsh** [comment]
@crisbeto Thanks, yes that works. Interestingly absolute() is not required in 1.1.1 but is in master.

**Comment by Splaktar** [comment]
As suggested, this works when using `.absolute()`. [Updated CodePen](https://codepen.io/Splaktar/pen/RwbpxZG) for `1.1.20`.
