### ISSUE TITLE
problem in material2,md-list-item in md-list grows up on the screen instead of down.So i guess the md-list is not growing with the md-list-items

### ISSUE THREAD

**Issue by stefanaerts** [angular/material#9936]
**Actual Behavior**:
 -  `What is the issue? *`
The item list is not completely shown the screen,it just moves the data above the top of the screen.
If i disable "display:flex or align-items:center" on the generated div.md-list-item in chrome devtools then it shows everything.
I have 2 links to video's attached to explain.
The first video is when i found the problem, @feloy @jelbourn now about it.
I was thinking in the beginning it had to do with the snackbar ViewContainerRef,but that works fine.
https://drive.google.com/open?id=0By7_cJqSCsKNMjVMWktaY3BLU3M

The second video is what i believe a bug in material.
https://drive.google.com/open?id=0By7_cJqSCsKNMno4ZHM1RDZCOFU

A positive note on this problem, it forced me to learn more about css and html.
The most time consuming part of web development for me until now is depending on css of others because i didn't write a lot myself yet until now.

And also a question to workaround this problems.
How can i overwrite inherited css properties of material components.
So to say for example "Do not use "display:flex" or "align-items:center" on this components md list and md list item stuff.Like i could do with the chrome devtools enable/disable checkboxes.
Where do i best post these kind of questions?
Thanks

 -  `What is the expected behavior?`

To see all data on the screen

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`
 -  `Angular Material Version:`

 "@angular/material": "^2.0.0-alpha.9-3",

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by crisbeto** [comment]
This is the repo for the Angular 1 version of Material. [Please post your issue here.](https://github.com/angular/material2/issues)
