### ISSUE TITLE
fab-toobar: input inside looses focus on "left" / "right" button click

### ISSUE THREAD

**Issue by vladimir-barsuchenko** [angular/material#9937]
Hi. 
I know that it's not expected to put an input inside `mdFabToolbar`. 
But here is what I did =)

And eventually, when I want to move a carriage to the left to edit text the input loses its focus.

![toolbar](https://cloud.githubusercontent.com/assets/10091564/19807796/71925ef2-9d2a-11e6-89a2-4570cb4383ad.gif)

I just want to ask: 

> Can I somehow override "left / right" events to expect default behavior for text input and not to dig into lib code or change the whole element structure ? Maybe there is something I'm missing

Angular v.1.5.8
Angular Material v.1.1.1
Chrome v.54.0.2840.71 m

Thanks a ton!

**Comment by Splaktar** [comment]
We would need a CodePen demo to debug and help with this. However, it's likely that you just need to handle those events on the input and not let them bubble up to the toolbar.
