### ISSUE TITLE
Tooltip setting property bug in Firefox Developer Edition

### ISSUE THREAD

**Issue by fundon** [angular/material#994]
```jade
        md-button(md-theme="blue" aria-label="Add Container")
          md-tooltip Add Container
          div.icon.svg-ic_add_24px

```

`TypeError: setting a property that has only a getter angular-material.js:5601:0`

`parentRect.top += contentCtrl.$element.prop('scrollTop');`

**Comment by Splaktar** [comment]
@fundon is this still an issue in 0.10.0 or master? This is likely to be fixed already. If not, do you have a CodePen/Plunker?
