### ISSUE TITLE
How do I perform crud operations on the $mdSidenav  ?

### ISSUE THREAD

**Issue by jpca999** [angular/material#9951]
nothing is wrong but im not able to figure out how do i perform crud operations on teh side nav ?

I want to populate and update the info on the sideNav. 

![image](https://cloud.githubusercontent.com/assets/1026325/19842034/d82efadc-9eea-11e6-9473-08ef46a64c98.png)

**Comment by Frank3K** [comment]
The issue tracker is not for questions. For questions, please head over to the [forum](https://groups.google.com/forum/#!forum/ngmaterial).
