### ISSUE TITLE
stacked/ combined md-icons

### ISSUE THREAD

**Issue by ajaysattikar** [angular/material#9953]
I have found "Material Design Iconic Font" library which is similar to md-icon and allow to create a stacked icon: http://zavoloklom.github.io/material-design-iconic-font/examples.html

But wasn't able to create a stacked icon combining angular material icons. https://material.angularjs.org/latest/api/directive/mdIcon

I'm already using angular material icons in my project, and don't want to include another library just for stacked icon.

Is there any way/work around we can combine md-icons to create a stacked angular material icons?

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial) or Gitter Angular Material (https://gitter.im/angular/material)
