### ISSUE TITLE
docs: broken link in menu demo page

### ISSUE THREAD

**Issue by LuxDie** [angular/material#9959]
**Actual Behavior**:
 -  `What is the issue? *` There is a link in the menu demo page with the following source code `<a href="ctrl.menuHref" class="md-accent">official spec</a>` Not only is it missing the interpolation braces but also there is no "menuHref" property in the controller.
 -  `What is the expected behavior?` Link shouldn't be broken

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` N/A
 -  `Details:` N/A

**Angular Versions**: *
 -  `Angular Version:` Unknown
 -  `Angular Material Version:` Unknown

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 54
 -  `OS: *` Windows 10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
Looks like this was broken by 12ceef39d80b9b8e49374c121511554132eec847. Thank you for pointing this out!
