### ISSUE TITLE
autocomplete: set input [size] based on interpolated [placeholder] attribute value

### ISSUE THREAD

**Issue by dshamgin** [angular/material#9962]
**Actual Behavior**:
 -  `What is the issue?`

If 'placeholder' value is an expression (which executes at lower priority than mdAutocomplete directive), the <input> won't be properly sized by browser:
`<md-autocomplete placeholder="{{::ctrl.getLocalizedPlaceholderText()}}">`
And placeholder text would appear cropped, especially for German :de: locale :cry: 

 -  `What is the expected behavior?`

I'd expect text inputs to set the 'size' attribute based on interpolated 'placeholder' value (at the "linking stage"). At least conditionally.

**Angular Versions**: *
 -  `Angular Version: 1.5.9`
 -  `Angular Material Version: 1.1.1`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 54`
 -  `OS: Linux`

**Comment by Splaktar** [comment]
I am not able to reproduce this without a demo and with using `1.1.12` ([CodePen](https://codepen.io/Splaktar/pen/aXGQJW?editors=1010#0)).
