### ISSUE TITLE
md-chip inside dialog, shows invalid characters when last item is removed

### ISSUE THREAD

**Issue by bimalvasan** [angular/material#9963]
**Actual Behavior**:
 -  `What is the issue? *` When we close the last item from the md-chip control, it shows some invalid chips.
 -  `What is the expected behavior?`It should show clean md-chip

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:`1.0.9

**Additional Information**:
 -  `Browser Type: *` Google chrome
 -  `Browser Version: *`
 -  `OS: *`Windows 7
 -  `Stack Traces:`
![image](https://cloud.githubusercontent.com/assets/5025373/19925681/0409f124-a117-11e6-80c1-5eaba56b976e.png)

`<md-chips ng-model="newItem.tags"></md-chips>`
----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
Can you please provide a Codepen demo for this issue?

**Comment by topherfangio** [comment]
Just wanted to touch base; can we please get a demo for this so we can investigate?

**Comment by Splaktar** [comment]
No demo provided.
