### ISSUE TITLE
Accessibility: Remove aria-invalid from required inputs on initial load

### ISSUE THREAD

**Issue by manish2535** [angular/material#9967]
**Actual Behavior**:
 -  `What is the issue? *` The attr aria-invalid is added to a required input right from the begining. 
 -  `What is the expected behavior?`  Copied from w3c.org - "If the user has not attempted to submit the form, authors SHOULD NOT set the aria-invalid attribute on required widgets simply because the user has not yet entered data." 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` This happens everywhere in the Docs where a required field is empty initially. 
 -  `Details:` https://www.w3.org/TR/2010/WD-wai-aria-20100916/states_and_properties#aria-invalid

**Angular Versions**: *
 -  `Angular Version:` 1.5
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *`
 -  `Browser Version: *`
 -  `OS: *`
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by manish2535** [comment]
OK so here is what I had to do make the screen readers behave properly in most browsers/Screen readers combination.

```
<md-input-container class="md-block">
	<label>{{ 'FORM_FIELDS.EMAIL' | translate }}</label>
	<input type="email" 
		name="Email" 
		ng-model="activateEmailObj.CustomerEmail" 
		required 
		aria-required="true" 
		aria-invalid="{{activateEmailForm.$submitted && activateEmailForm.Email.$invalid ? true : false}}"/>
		<div ng-messages="activateEmailForm.Email.$error">
			<div ng-message-exp="['required', 'pattern']">
				{{'VALIDATION.EMAIL' | translate}}
			</div>
		</div>
</md-input-container>
```

1. aria-required="true"  was added. It may be redundant with the HTML5 required attr but that is what gave the best results testing with different Screens Readers (SRs) and browsers. More info here - [http://john.foliot.ca/required-inputs/]
2. Added the following to disable ngAria handling the aria-invalid attr
```
app.config(function config($ariaProvider) {
	$ariaProvider.config({
		ariaInvalid: false
	});
});
```
3. Now since the standard is aria-invalid should remain false until the user has had a chance to insert some data and submit the form (more here -  https://www.w3.org/TR/2010/WD-wai-aria-20100916/states_and_properties#aria-invalid), I had to handle it more manually by adding specific logic like so 

`aria-invalid="{{activateEmailForm.$submitted && activateEmailForm.Email.$invalid ? true : false}}"`

where activateEmailForm is the name of the form and Email is the name of the input field.

4. I initially thought just removing the aria-invalid attr entirely and adding it back once the form has been attempted to be submitted would be the better choice which is why I created this issue but it turns out that the Screen Readers will announce any input element with a required element as "Invalid entry" if its empty which is always the case when the form is loaded initially. So the best of both world is to always have the aria-invalid attr and change the value of the attr dynamically.

**Comment by manish2535** [comment]
@marcysutton any views on this?

**Comment by marcysutton** [comment]
Shouldn't this change go into `ngAria`? I think there is already an issue for it https://github.com/angular/angular.js/issues/11883

**Comment by manish2535** [comment]
Yup, it makes sense. I will add my comment to that issue you reference as well. Thanks.

**Comment by ThomasBurleson** [comment]
Closing as a not-Material1 issue.
