### ISSUE TITLE
md-menu opened incorrectly with ng-mouseover

### ISSUE THREAD

**Issue by vovafeldman** [angular/material#9968]
**Actual Behavior**:
 -  When using `ng-mouseover` for opening `md-menu` with `ng-mouseover="$mdOpenMenu($event)"`, the menu is opened on the top left side of the screen instead of next to the triggering button.
 -  Menu should open next to the button.

**CodePen** (or steps to reproduce the issue): *
```html
<md-button class="md-icon-button"
           ng-mouseover="$mdOpenMenu($event)"
           aria-label="Search">
    <i class="fa fa-user fa-fw"></i>
</md-button>
```

**Angular Versions**: *
 -  `Angular Version: 1.4.12`
 -  `Angular Material Version: 1.1.0`

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version:  53.0.2785.143 (64-bit)`
 -  `OS: OS X Yosemite`

**Comment by Splaktar** [comment]
I think that there was a mistake in the docs at some point (that has since been fixed).

This is how to do it:
```html
<md-button aria-label="Search" class="md-icon-button" ng-mouseenter="$mdMenu.open()">
```

You can find more in the docs: https://material.angularjs.org/latest/api/directive/mdMenu
