### ISSUE TITLE
tabs: scrolling up in a textarea element in a md-tab, puts UI in a bad state.

### ISSUE THREAD

**Issue by derrillhd** [angular/material#9969]
**Actual Behavior**:
 -  `What is the issue? *`
Scrolling up in a textarea element in an md-content for an md-tab, puts UI in a bad state that cannot be fixed without refreshing page.

 -  `What is the expected behavior?`
Page Up has no effect or does not put the UI in a bad state.

**CodePen** (or steps to reproduce the issue): *
The can be reproduced easily using Angular's Material demos, but occurs in our app as well.
1) Go to: https://material.angularjs.org/latest/demo/tabs
2) Click on CodePen
3) Within any md-content element put a <textarea></textarea> element
4) Click on the text box, type anything, and then press Page Up.
5) UI is now in a bad state.

**Angular Versions**: *
 -  `Angular Version:` Version used by the demo.
 -  `Angular Material Version:` Version used by the demo.

**Additional Information**:
 -  `Browser Type: *` Chrome 
 -  `Browser Version: *` Version 54.0.2840.71
 -  `OS: *` Linux
 -  `Stack Traces:` N/A

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This appears to have already been fixed as I cannot reproduce this in `1.1.12`. No version is specified in the issue, so I can't test against a known bad version to verify further. I used [this CodePen](https://codepen.io/Splaktar/pen/omdQXe) to verify that it is working properly.
