### ISSUE TITLE
week dates at a time in date calendar with time picker

### ISSUE THREAD

**Issue by Navpreet2289** [angular/material#9971]
Can some one tell me how to show only one week dates at a time in date calendar with time picker like shown in the pic.

<img width="335" alt="screen shot 2016-09-15 at 12 55 05 am" src="https://cloud.githubusercontent.com/assets/23264074/20013102/5e836fbc-a2cb-11e6-8df7-bdee1716178a.png">

**Comment by topherfangio** [comment]
So, based on the styling, I'm going to say that this would be very difficult to do using the existing `<md-calendar>` or `<md-datepicker>` components.

Particularly:

1. The order of the month name and the day names are opposite,
2. The month name is **part of** the table columns/rows which means you can't easily move it,
3. The day names are totally spelled out whereas our calendar uses just the first letter, but most importantly,
4. This calendar appears to start on a different day of the week each time.

Now, you might be able to get past 1/2/3 with enough CSS hacks, but if you really need the functionality for number 4, I think it would be wisest to write your own.
