### ISSUE TITLE
[md-autocomplete] md-not-found click action not working

### ISSUE THREAD

**Issue by paradox41** [angular/material#9975]
**Actual Behavior**:
 -  `What is the issue? *`

Clicking on `md-not-found` item not triggering `ng-click`

 -  `What is the expected behavior?`

Clicking on `md-not-found` should trigger the `ng-click`

**CodePen** (or steps to reproduce the issue): *

This issue is present on the latest docs "Basic Example": https://material.angularjs.org/latest/demo/autocomplete

**Angular Versions**: *
 -  `Angular Version:` 1.5.5
 -  `Angular Material Version:` 1.1.1 (assumed latest)

**Additional Information**:
 -  `Browser Type: Chrome`
 -  `Browser Version: 55`
 -  `OS: MacOS Sierra`
 -  `Stack Traces: None`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by DevVersion** [comment]
It seems to work for me. The `ng-click` is only added to the `Create your own` text in the not found item.

**Comment by paradox41** [comment]
You are correct. It all looked clickable because of the cursor. Thanks!
