### ISSUE TITLE
Dialogs can't open

### ISSUE THREAD

**Issue by Chan4077** [angular/material#9977]
**Actual Behavior**:
 -  `What is the issue? *`When the buttons to open the dialog are clicked, nothing appears except the custom dialog, which fullscreen mode does not work.
 -  `What is the expected behavior?`Buttons should open the dialog when clicked.

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` https://material.angularjs.org/HEAD/demo/dialog
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` HEAD

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 55.0.2883.35 beta (64-bit)
 -  `OS: *` macOS Sierra 10.12.1
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Martin-Andersen** [comment]
Same problem in Safari
