### ISSUE TITLE
Enhancement: [md-chip] - Should be able to make chips editable even when using <md-chip-template>

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/material#9979]
**Actual Behavior**:
 -  `What is the issue? *` Chips are not editable when using `<md-chip-template>`
 -  `What is the expected behavior?` Chips should be editable even when using `<md-chip-template>`. 

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` http://codepen.io/cmacdonnacha/pen/gLbJVN
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:` 1.4
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 49
 -  `OS: *` Windows 7
 -  `Stack Traces:`

**Comment by topherfangio** [comment]
So, this is probably something we won't be able to offer for md1, but will definitely consider for md2.

That said, you can hack around it with the following, but you'll notice that there are some issues you would need to overcome: http://codepen.io/topherfangio/pen/WREooN?editors=0010

Hope this helps.

**Comment by cmacdonnacha** [comment]
Great thanks for the update @topherfangio
