### ISSUE TITLE
mdProgressLinear: What's the point of md-mode="query"?

### ISSUE THREAD

**Issue by PaulMougel** [angular/material#998]
This mode is halfway documented:
> md-mode (string) Select from one of four modes: determinate, indeterminate, buffer or query.

but there is no example.

See this Plunker for an example of an `md-progress-linear` component with `md-mode="query"` in action:
http://plnkr.co/edit/RKDu5IULAebz16hOCVDg?p=preview
![untitled](https://cloud.githubusercontent.com/assets/1788596/5506499/31ed896c-879b-11e4-8b7a-e0ae2f4122a2.gif)

What is the difference between an indeterminate and a query bar? I thought it would be a combination of a determinate bar (filled up to `value` %) and an indeterminate bar on the remaining; but it's not. Can anyone clarify this?

**Comment by warpdesign** [comment]
How about completing the documentation ? I couldn't find what it meant before reading this post.

**Comment by ThomasBurleson** [comment]
@warpdesign, @EladBezalel - if you want to enhance our docs, a Pull Request would be welcomed.

**Comment by EladBezalel** [comment]
@ThomasBurleson i'm on it :smile:

**Comment by EladBezalel** [comment]
#4407

**Comment by warpdesign** [comment]
Nice work @ThomasBurleson ! Explains it perfectly.

**Comment by ThomasBurleson** [comment]
@warpdesign - Actually @EladBezalel made these doc improvements. Kudos to him!
