### ISSUE TITLE
Updating mdSelect and mdRadioButton from model

### ISSUE THREAD

**Issue by serpip** [angular/material#9980]
Example for md-select:
```
<md-select ng-model="selectboxModel.select" >
<md-option ng-repeat="item in kingdomVocabulary" ng-value="{value: item, id: null, uri: null}">
{{item}}
</md-option>
</md-select>
```

When I manually change selectboxModel.select, for example set:
`$scope.selectboxModel.select = {value: "My value", id: null, uri: null}` and
Correct md-option with ng-value =  {value: "My value", id: null, uri: null} should selects as well.

**Comment by figo77ll** [comment]
+1 

I have a similar problem and in my case the md-option is dynamically retrieved from DB via loadModels:

```
                        <md-input-container  style="! margin-bottom: 0px" flex="25">
                            <label>Model</label>
                            <md-select placeholder="Model" ng-model="ctrl.model" md-on-open="ctrl.loadModels()"  md-on-close="ctrl.get()">
                                <md-option ng-value="model" ng-repeat="model in ctrl.models" ng-selected="{{ model.name === ctrl.model.name ? 'true' : 'false' }}">{{model.name}}</md-option>
                            </md-select>
                        </md-input-container>
```
I think ng-selected will resolve the problem by highlighting the value being set by ng-model. But still the select box itself by default is empty (you only see selected value by clicking the box).

Noticed at if md-option is statically defined (not from DB), then it works fine with ng-selected. But looks like it doesn't work for dynamic case.

**Comment by serpip** [comment]
Unfortunally, ng-selected not resolved this problem...

**Comment by Splaktar** [comment]
We would need a CodePen reproduction of this in order to help debug these specific cases. It would also be helpful to know the versions of AngularJS and AngularJS Material that are being used.
