### ISSUE TITLE
md-select is not recognizing input from number pad

### ISSUE THREAD

**Issue by waltersjack** [angular/material#9985]
**Actual Behavior**:
 -  `What is the issue? *` Input from number pad is not recognized in the md-select
 -  `What is the expected behavior?` Input from number pad is recognized in the md-select

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:` NA
 -  `Details:`
See Comment
https://github.com/angular/material/commit/11cbe3a2e1972f1c8703063dbb7641cf4a0e0341#diff-b0894b74b15b75ed0bf50cfc9a02a290R38

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.1

**Additional Information**:
 -  `Browser Type: *` Firefox, IE, Chrome
 -  `Browser Version: *` Latest Versions
 -  `OS: *` Win 8.1
 -  `Stack Traces:` NA

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by Splaktar** [comment]
This [demo](https://codepen.io/Splaktar/pen/MBwzxp?editors=1010#0) shows that this is fixed in 1.1.10 via PR https://github.com/angular/material/pull/11313.
