### ISSUE TITLE
Changing url-text (but not page) causes md-tabs to reset

### ISSUE THREAD

**Issue by chevalierc** [angular/material#9988]
**Actual Behavior**:
 -  `What is the issue? *`
When changing the url via `$location.search()` the tabs reset to the first tab (and I believe reset in general as there is a strange UI glitch when it happens)
 -  `What is the expected behavior?`
the tab should not change

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
Tried. Doesn't look like the url exists in code pen
 -  `Details:`

**Angular Versions**: *
 -  `Angular Version:`1.5.7
 -  `Angular Material Version:`1.1.0-rc.5

**Additional Information**:
 -  `Browser Type: *` chrome
 -  `Browser Version: *`
 -  `OS: *`windows
 -  `Stack Traces:`

**Comment by Splaktar** [comment]
Unfortunately, we can't reproduce this issue without some kind of demo (GitHub repo, CodePen, StackBlitz, etc).
