### ISSUE TITLE
Feat: Generate a color pallete from base colors

### ISSUE THREAD

**Issue by epelc** [angular/material#999]
It would be really nice If you could generate a new color palette from several base colors. Perhaps from the primary warn and accent colors. I think this would go really nicely with the new js theming system.

**Comment by rschmukler** [comment]
Closing this for now. I think that it's not worth introducing the dependencies on the color math to make a best attempt at a palette. For now, users can use 3rd party tools to generate them. I worry that it goes beyond the scope of what we want the project to do.

**Comment by epelc** [comment]
@rschmukler I agree.
I really couldn't figure out the math behind how they picked their colors. Maybe they were hand picked but they don't look like it. Perhaps someone can ask whoever made it at google how it works but it seems unlikely.
