### ISSUE TITLE
It's a css mistake ?<md-autocomplete in md-dialog>

### ISSUE THREAD

**Issue by tianyaxiangdong** [angular/material#9990]
**Actual Behavior**:
 -  `What is the issue? *` i use md-autocomplete in md-dialog ,when i  focused it, the parent scroll (nearest ) not disabled.
 -  `What is the expected behavior?` the scroll disabled

**CodePen** (or steps to reproduce the issue): *
 -  `CodePen Demo which shows your issue:`
 -  `Details:` the `<div class="md-scroll-mask" aria-hidden="true">  <div class="md-scroll-mask-bar"></div></div>` has `z-index:50`, but after element `<div class="md-dialog-container" tabindex="-1">...</div>` has `z-index:80`, so it can never be disabled scroll` disableScrollAround -> disableElementScroll`  no new mask added for md-dialog in autocomplete

**Angular Versions**: *
 -  `Angular Version:`1.5.8
 -  `Angular Material Version:`1.1.1

**Additional Information**:
 -  `Browser Type: *`chrome
 -  `Browser Version: *`54
 -  `OS: *`windows10
 -  `Stack Traces:`

----
Shortcut to create a [new CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd).
Note: `*` indicates required information. Without this information, your issue may be auto-closed.

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by ravikajain** [comment]
I am facing same on page scroll is lock but in md-dialog the scroll of md-dialog is not locked.

**Comment by Splaktar** [comment]
Thank you for taking the time to submit this issue. However it does not follow our required issue template. We need a CodePen demo of the problem so that we can debug it. This may also be related to some other open issues.

Please file a new issue that follows the template. This gives the team the information needed to investigate the bug or prioritize the feature.
