### ISSUE TITLE
Using ngMaterial Tools with string from Contoller and ng-bind-html in HTML

### ISSUE THREAD

**Issue by tahaerden** [angular/material#9991]
**Actual Behavior**:
 -  `What is the issue? *`
I want to add Angular Material tools (such as a button with tooltip) dynamically from controller. In some parts of my code, I add HTML codes as string, and use ng-bind-html on front to display them.

The following code works nicely if I put it in html:
`<md-button aria-label="hello"><i class="fa fa-circle text-success"></i><md-tooltip md-direction="right">hello</md-tooltip></md-button>`

But it does not if I use it with ng-bind-html:
Controller:
`$scope.example = '<md-button aria-label="hello"><i class="fa fa-circle text-success"></i><md-tooltip md-direction="right">hello</md-tooltip></md-button>';`
HTML:
`<div ng-bind-html="example"></div>`

**Angular Versions**: *
 -  `Angular Version:` 1.5.8
 -  `Angular Material Version:` 1.1.0

**Additional Information**:
 -  `Browser Type: *` Chrome
 -  `Browser Version: *` 54.0.2840.71 m

**Comment by sandermendes** [comment]
Same situation here.

Best regards.

**Comment by groudjulien** [comment]
Same situation here with
 - Angular : 1.6.7
 - angular-material : 1.1.5
Best regards.

**Comment by Splaktar** [comment]
Please provide a demo if this is still an issue and I would be happy to look into this.

As is, I can't tell if you imported `angular-sanitize.js` or injected `ngSanitize` in your module, etc. More information on this can be found in https://docs.angularjs.org/api/ng/directive/ngBindHtml.
