### ISSUE TITLE
datepicker: validation behaves differently in IE

### ISSUE THREAD

**Issue by hoanthien92** [angular/material#9994]
**Actual Behavior**:
You can test it here in angular material demos for IE and Chrome:
https://material.angularjs.org/1.1.1/demo/datepicker
 The issue is when you input an invalid value in the date picker in IE with ngMessages, it says "Only Weekends are allowed", then when you add a letter in the input, it doesn't validate it (for example 11/9/2016 and after that input a letter, 11/9/2016t). I was expecting to have this message showed "The entered value is not a date!" but it didn't. It wasn't happening when I was using Angular Material 1.0.8.
In Chrome, it validates correctly so if you add a letter in datepicker input, it says "The entered value is not a date!". This only became an issue from angular material 1.1.0 in IE.

** steps to reproduce the issue**
 -  https://material.angularjs.org/1.1.1/demo/datepicker
 -  `Details:` adding a letter in input "With ngMessages", the validation message stays "Only Weekends are allowed" instead of "The entered value is not a date!".

**Comment by richardhughes** [comment]
The validation on IE is different than Chrome and Firefox:

`return date && date.getTime && !isNaN(date.getTime());`

Will return true in IE for dates '11/13/2016b' but if you add another letter onto the end it returns false.

Haven't looked too much into the issue why its happened from 1.1.0 but will investigate further.
