### ISSUE TITLE
mdContent scroll event?

### ISSUE THREAD

**Issue by Boogie1989** [angular/material#9996]
How can i add scroll event to mdContent directive?

**Comment by remarshy** [comment]
This is not a forum for support, but to report issues with angular material. But to answer your question:


Assuming you will use a directive...

angular.element(element).bind('scroll',` function(e) {

    scope.apply(function() {
        //digest
    });
});

**Comment by mckenzielong** [comment]
There is a google group for these kinds questions here: https://groups.google.com/forum/#!forum/ngmaterial
